### ISSUE TITLE
Not today

### ISSUE THREAD

**Issue by khang06** [yuzu-emu/yuzu#1000]
haha issue #1000 please don't ban me

**Comment by khang06** [comment]
there will be no kpop on this issue

**Comment by slashiee** [comment]
Just kidding.
https://www.youtube.com/watch?v=pFuJAIMQjHk
https://www.youtube.com/watch?v=xRbPAVnqtcs
https://www.youtube.com/watch?v=8Oz7DG76ibY
https://www.youtube.com/watch?v=MBNQgq56egk
https://www.youtube.com/watch?v=V2hlQkVJZhE
https://www.youtube.com/watch?v=vecSVX1QYbQ
https://www.youtube.com/watch?v=Nu2yQ1zYDYU

**Comment by Cyuubi** [comment]
PLEASE DONT SAY YOU ARE LAZY DATTE HONTOU WA CRAZY
