### ISSUE TITLE
Error when finding Boost

### ISSUE THREAD

**Issue by svalx** [yuzu-emu/yuzu#10001]
### Issue

On openSUSE Tumbleweed we have an configure error when finding Boost:
```
[  135s] -- Target architecture: x86_64
[  135s] CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
[  135s]   Could NOT find Boost: Found unsuitable version "1.81.0", but required is
[  135s]   exact version "1.79.0" (found /usr/include, found components: context)
[  135s] Call Stack (most recent call first):
[  135s]   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
[  135s]   /usr/share/cmake/Modules/FindBoost.cmake:2377 (find_package_handle_standard_args)
[  135s]   CMakeLists.txt:213 (find_package)
[  135s] 
[  135s] 
[  135s] -- Configuring incomplete, errors occurred!
```
CMake 3.26

**Comment by Kelebek1** [comment]
You should be able to just set boost 1.81 in cmakelists, the problem with it was fixed and implemented so 1.79 isn't needed anymore.

**Comment by svalx** [comment]
It is a RPM build in [Open Build Service](https://build.opensuse.org/package/show/Emulators/yuzu) and I can't change anything without patching sources. Before last changes this step looks as follows:
```
[   77s] -- Target architecture: x86_64
[   77s] -- Found Boost: /usr/lib64/cmake/Boost-1.81.0/BoostConfig.cmake (found suitable version "1.81.0", minimum required is "1.73.0") found components: context 
[   78s] -- Found enet: /usr/lib64/libenet.so (found suitable version "1.3.17", minimum required is "1.3") 
```
Why _**minimum required**_ transformed to _**exact**_?

**Comment by Morph1984** [comment]
Please see #9989 for context. Boost 1.79 exact was temporarily required for about a day while we were figuring out the issue with 1.81. As a result, Mainline 1382's source is affected by this. The next mainline (1383) should be released in about an hour and remove this requirement.

**Comment by svalx** [comment]
Thank you, I understood.

**Comment by v1993** [comment]
@noloader Pass `-DYUZU_USE_BUNDLED_VCPKG=ON` on CMake step. Yuzu will utilize vcpkg to download missing dependencies, including boost.
