### ISSUE TITLE
Build fails with "invalid operands to binary expression" or "no match for 'operator!='" error

### ISSUE THREAD

**Issue by v-fox** [yuzu-emu/yuzu#10019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1389

### Description of Issue

When I tried to compile snapshot of 1389 in Open Build Service it failed with an obscure error.

### Expected Behavior

Build.

### Reproduction Steps

Build it.

### Log File

```
[  208s] /home/abuild/rpmbuild/BUILD/yuzu-0.1389/src/./core/hle/kernel/k_memory_region.h:174:77: error: invalid operands to binary expression ('iterator' (aka 'Iterator<false>') and 'const_iterator' (aka 'Iterator<true>'))
[  208s]         if (auto it = this->find(KMemoryRegion(address, address, 0, 0)); it != this->cend()) {
[  208s]                                                                          ~~ ^  ~~~~~~~~~~~~
```
for clang-16 and:
```
[  147s] /home/abuild/rpmbuild/BUILD/yuzu-0.1389/src/./core/hle/kernel/k_memory_region.h:174:77: error: no match for 'operator!=' (operand types are 'Common::IntrusiveRedBlackTree<Kernel::KMemoryRegion, Common::IntrusiveRedBlackTreeBaseTraits<Kernel::KMemoryRegion>, Kernel::KMemoryRegion>::Iterator<false>' and 'Kernel::KMemoryRegionTree::const_iterator' {aka 'Common::IntrusiveRedBlackTree<Kernel::KMemoryRegion, Common::IntrusiveRedBlackTreeBaseTraits<Kernel::KMemoryRegion>, Kernel::KMemoryRegion>::Iterator<true>'})
[  147s]   174 |         if (auto it = this->find(KMemoryRegion(address, address, 0, 0)); it != this->cend()) {
[  147s]       |                                                                          ~~ ^~ ~~~~~~~~~~~~
[  147s]       |                                                                          |               |
[  147s]       |                                                                          Iterator<false> Iterator<true>
```
for gcc-13.

### System Configuration

OBS uses VMs on unknown hardware, not that it's relevant.

**Comment by liamwhite** [comment]
gcc 13 isn't released yet, is it? could you get the commit hash that gcc is based on?

**Comment by v-fox** [comment]
> gcc 13 isn't released yet, is it? could you get the commit hash that gcc is based on?

Check out https://build.opensuse.org/package/show/openSUSE:Factory/gcc13
It says "13.0.1+git6669  / revision 42630fadbe248717859d61c0244c821c32b4e52c"

Note that [clang-16](https://build.opensuse.org/package/show/openSUSE:Factory/llvm16) experiences the same.

**Comment by liamwhite** [comment]
This is potentially a libstdc++ breakage then

**Comment by v-fox** [comment]
> This is potentially a libstdc++ breakage then

That would be a very subtle breakage, considering that entire system and all other emulators are built with them just fine.

**Comment by liamwhite** [comment]
> That would be a very subtle breakage, considering that entire system and all other emulators are built with them just fine.
catch2 from vcpkg also doesn't compile with libstdc++13, so it's not that much of a surprise.

The underlying issue is that IntrusiveRedBlackTreeImpl::Iterator<> can no longer deduce the correct operator== to use, even if you overload it. I am asking around about optimal ways to fix this.

**Comment by Kelebek1** [comment]
Does it have to be cend, does just end fix it?
