### ISSUE TITLE
Sports Story v1.0.5 stuck on launching

### ISSUE THREAD

**Issue by jjjustinleblanc** [yuzu-emu/yuzu#10021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3492

### Description of Issue

When trying to launch Sports Story v1.0.5 (I've tried every update to the same effect), it endlessly shows "Launching". I've tried changing every setting under the sun in every different configuration I could possibly think of, without any luck. 

### Expected Behavior

Game expected to launch without being stuck on 'Launching" screen.

### Reproduction Steps

1. Open Yuzu
2. Launch Sports Story

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11129587/yuzu_log.txt)

### System Configuration

CPU: Core i7-6700HQ
GPU/Driver: GTX 960m
RAM: 32GB
OS: Windows 10 x64

**Comment by jjjustinleblanc** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11129594/yuzu_log.txt)
 
Updated log

**Comment by FearlessTobi** [comment]
`nn::fs::MountRom(char const*, void*, unsigned long)`
possible filesystem issue.

**Comment by jjjustinleblanc** [comment]
> `nn::fs::MountRom(char const*, void*, unsigned long)` possible filesystem issue.

Is this something I can fix on my end, or is it a bug?

**Comment by FearlessTobi** [comment]
it is a bug. unless you are a developer, you cannot do anything about it right now

**Comment by jjjustinleblanc** [comment]
game now loads and is fully playable. this issue can be closed
