### ISSUE TITLE
Link's Awakening regression

### ISSUE THREAD

**Issue by widardd** [yuzu-emu/yuzu#10038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

3504

### Description of Issue

Low resolution and weird lines:

![FXSDqu6](https://user-images.githubusercontent.com/5463582/230868142-5eb7a666-63e8-46bd-8a32-875d07908c39.png)

Same settings on Yuzu 2930:
![62ROvyF](https://user-images.githubusercontent.com/5463582/230868309-b2ffd71d-4595-4d83-a92f-11f01d8fe49d.png)

### Expected Behavior

native resolution shouldn't look like that

### Reproduction Steps

just start yuzu and run the game

### Log File

[yuzu_log - Kopie.txt](https://github.com/yuzu-emu/yuzu/files/11189229/yuzu_log.-.Kopie.txt)

### System Configuration

CPU: i3-12100F
GPU/Driver: RX 580, 22.20.27.09-230321a-389799E
RAM: 32GB
OS: Win11 22624.1537

**Comment by FearlessTobi** [comment]
Should be fixed in the next EA build.
