### ISSUE TITLE
Asynchronous Presentation Breaks FSR Filter / Image Quality

### ISSUE THREAD

**Issue by AliciaBurrito** [yuzu-emu/yuzu#10037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3504

### Description of Issue

The FSR filter has regressed image quality caused by the addition of asynchronous presentation.

It appears pixelated, but if the user were to cycle through all filters during gameplay back to FSR the image quality issues are resolved. Happens no matter the resolution scale.

**Xenoblade Chronicles 3**
![Before-Cycle-XC3](https://user-images.githubusercontent.com/16925715/230806676-9fe037fc-ff5f-4188-a08d-fb7f958c0a7f.png)
![After-Cycle-XC3](https://user-images.githubusercontent.com/16925715/230806683-8224c09f-c82e-4d2c-be9c-809f549d9cfb.png)

**Mario Kart 8 Deluxe**
![Before-Cycle-MK8D](https://user-images.githubusercontent.com/16925715/230806704-ff93d0ec-9784-499c-974d-90d448a9e951.png)
![After-Cycle-MKD8](https://user-images.githubusercontent.com/16925715/230806713-e238ff1a-c017-443b-8128-1fe19818c4a0.png)

### Expected Behavior

The FSR filter should output a clean image just as it did in previous releases, and without the need to cycle through filters to achieve it.

### Reproduction Steps

1. Set the filter to FSR before launching a game.
2. Boot any game, and view the image quality (should be fairly pixelated).
3. Cycling through the filters all the way back to FSR.
4. View the changed image quality, which is what is expected.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11186778/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 6800U
GPU/Driver: AMD 680M
RAM: 32GB LPDDR5
OS: Windows 11

**Comment by Lycoris2013** [comment]
FSR does not work in my environment, even if I cycle the filter.

EA3503
![3503](https://user-images.githubusercontent.com/4056381/230826496-edef9dab-b086-47d9-9440-7c005da6dd9d.jpg)
EA3504
![3504](https://user-images.githubusercontent.com/4056381/230826502-9c4c85c8-ad01-4547-90c2-d57523fa4012.jpg)

Log File
[yuzu_log_3503.txt](https://github.com/yuzu-emu/yuzu/files/11187651/yuzu_log_3503.txt)
[yuzu_log_3504.txt](https://github.com/yuzu-emu/yuzu/files/11187652/yuzu_log_3504.txt)

System Configuration
CPU: Intel Core i7 13700K
GPU/Driver: NVIDIA 3080Ti
RAM: 32GB DDR5
OS: Windows 11
Display: 4K
