### ISSUE TITLE
Mario Kart 8 Deluxe crashes mid loading a race on Vulkan only

### ISSUE THREAD

**Issue by lazydevyo** [yuzu-emu/yuzu#10049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1401

### Description of Issue

Mario Kart 8 Deluxe crashes while loading a race in Vulkan, but works in Open GL without issues.
In the log file it seems like it crashes mid compiling shaders? This random crashing in Vulkan happens with other games also.

### Expected Behavior

It should continue running like it does in other hardware.

### Reproduction Steps

You'll need the exacly same hardware as stated in the System Configuration, Every other step is the usual one.
Default settings, running the game.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11211947/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
GPU/Driver: NVIDIA GeForce GTX 650 / NVIDIA 474.14.0.0
RAM: 7.94 GiB
OS: Windows 10 Version 22H2 (Build 19045.2728)

**Comment by UrsoManso** [comment]
I got this same issue. Seems to be a Nvidia GPU thing.

**Comment by lazydevyo** [comment]
> I got this same issue. Seems to be a Nvidia GPU thing.

I think its a Vram issue since the 650 has only 1GB vram but yuzu requires for minimum 2gb

**Comment by UrsoManso** [comment]
I have a 970 with 4GB.

**Comment by lazydevyo** [comment]
Solution: If you go to configuration, then graphics, then advanced, then enable "Use asynchronous shader building (Hack)" and (Not sure if it's necessary) change the "ASTC recompression" to "BC1 (Low Quality)" it solves any crashes related to low VRAM in any game

**Comment by auwsmit** [comment]
This still happens to me even with ASTC recompression set to BC1, and I'm using a 2070S with 8gb vram
