### ISSUE TITLE
Luigi's Mansion 3, Massive FPS drop on 12th floor

### ISSUE THREAD

**Issue by AnArcticPigeon** [yuzu-emu/yuzu#10047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1377-1400

### Description of Issue

Huge performance issues in the elevator hall of floor 12, the performance issues are only present as long as you haven't removed the boat hull blocking the doorway.

Im am not 100% sure but Theses fishing Nets and glass buoy's seem to be causing the fps drops since once i remove them with the vacuum or the  "Super Suction" upgrade  the framerate recovers going back to around 40 fps on my rig once all three are removed  but the buoy's are left(if i only remove 1/3 or 2/3 nets the framerate stays around 20 to 40 fps) and goes back to a full 60 fps with all 3 nets + the buoy's removed.

![Screenshot (28)](https://user-images.githubusercontent.com/65252526/231271741-5816a9f5-de96-4d63-b3fa-951528abf7f5.png)

All fps issues disappear once they are sucked up.

![LuigiMansion3FPSdropNets](https://user-images.githubusercontent.com/65252526/231269129-667b017b-2998-4ba6-81c7-6f7e8e692ee2.gif)

### Expected Behavior

This is the only place where i experienced such fps drops during my whole playthrough. 

### Reproduction Steps

Just go to the elevator hall on the 12th floor before you destroy the boat hull.

### Log File

Log: [yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/11203232/yuzu_log.zip)
Save file on 12th floor: [Luigi'sMansion 3, floor 12.zip](https://github.com/yuzu-emu/yuzu/files/11203248/Luigi.sMansion.3.floor.12.zip)

### System Configuration

Using:
Vulkan and Opengl
Docked
GPU Normal
Game Version:1.4
Game Mods: 60fps,No Dynamic resolution

PC Config:
CPU: R5 3600xt
GPU/Driver: gtx 1060(6gb) / 531.31
RAM:16GB 3600 DDR4
OS:Windows 11

**Comment by AnArcticPigeon** [comment]
PS: I just realized i used a 3 week old version of yuzu because the auto updater didn't work for me, i have since updated to Mainline version 1400 of yuzu and the problem is still present.

**Comment by FishOrBear** [comment]
https://github.com/yuzu-emu/yuzu/issues/9873

**Comment by gidoly** [comment]
this issue can be fixed by unsafe cpu accuracy for this game specifically

**Comment by Dudupool** [comment]
> this issue can be fixed by unsafe cpu accuracy for this game specifically

Thank You so much
