### ISSUE TITLE
Super Mario odyssey audio bug when mario transforms into a lightning rod

### ISSUE THREAD

**Issue by NatePat33** [yuzu-emu/yuzu#10040]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Mainline 1399

### Description of Issue

https://user-images.githubusercontent.com/108880804/230961963-cd6f1c73-db5a-456f-9d2f-7fe16990a085.mp4

### Expected Behavior

Before previous releases it was working just fine but on the latest releases its stretched for some reason
Could it be the emulator that was working the audio?

### Reproduction Steps

This happens during this cutscene
and all kingdoms

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11192660/yuzu_log.txt)

### System Configuration

CPU: Processor Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, 3192 Mhz, 6 Core(s), 12 Logical Processor(s)
GPU/Driver: Nvidia GTX 1060 6gb
RAM: 16 gb
OS: Windows 11

**Comment by Jackcool476** [comment]
> what was it suppose to sound like? high pitch?

ever so slightly faster, ive gone insane comparing the audio to a ripped sound effect

**Comment by bylaws** [comment]
What version did this start with exactly?

**Comment by Jackcool476** [comment]
seems to start with mainline 1389
1388: https://user-images.githubusercontent.com/60570270/231019719-805f4724-703b-4f2e-a999-cff0bed978dd.mp4
1389: https://user-images.githubusercontent.com/60570270/231019748-4b9d3f8a-8431-4878-8160-ad3c18b4b273.mp4

**Comment by bylaws** [comment]
Are you able to build yuzu yourself?

**Comment by Simonxdd** [comment]
The moped in New Donk City also has messed up audio.
