### ISSUE TITLE
VK_ERROR_INITIALIZATION_FAILED on Linux Wayland

### ISSUE THREAD

**Issue by Dirleye** [yuzu-emu/yuzu#10050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

r23542.eeb603066

### Description of Issue

I get the "yuzu has encountered an error while running the video core" error when trying to launch any games using Wayland on Linux. I'm using a slightly modified yuzu-mainline-git (aur) PKGBUILD to build Yuzu, though it happens on the unmodified version as well. I've rebuilt yuzu-mainline-git using old versions of the PKGBUILD that I know worked in the past and they fail too, so I'm pretty sure it's not the package itself that's the issue.

Setting QT_QPA_PLATFORM=xcb to use Xwayland allows everything to work as normal.
I haven't used Yuzu in a month or so, so I'm unable to narrow it down to any particular change on my system and I don't understand the error well enough to know what the problem might be.

I'm using a discrete Pascal Nvidia card with the latest drivers and no integrated graphics.
This log was produced with "Enable Graphics Debugging" checked.

### Expected Behavior

Yuzu successfully launches a game with no error on Wayland.

### Reproduction Steps

Launch any game with Yuzu running on Wayland.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11226109/yuzu_log.txt)

### System Configuration

CPU: Ryzen 7 2700x
GPU/Driver: Nvidia TITAN Xp / 530.41.03
RAM: 32GB
OS: EndeavourOS Linux

**Comment by liamwhite** [comment]
Can you check if #10050 resolves this?

**Comment by Dirleye** [comment]
Works perfectly. Thank you very much.

**Comment by Dirleye** [comment]
Probably shouldn't have closed that until it's merged.
