### ISSUE TITLE
pokemon legends arceus - amd gpu/vulcan crash on startup.

### ISSUE THREAD

**Issue by vsrd2795** [yuzu-emu/yuzu#10070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1405

### Description of Issue

When booting pokemon legends arceus on an amd 6800xt gpu with vulcan i get to the "gamefreak" logo screen followed by a hard gpu driver crash. Screen completely blacks out and becomes unresponsive followed by the screen eventually returning with yuzu closed out. When i open amd adrenaline software there is a notification that settings were reset after "unexpected system failure". After switching to opengl the game makes it to the language selection screen and is responsive. i didn't go past that point but everything seemed to work. I have seen one or two other posts about this game not working on vulcan but they were using either nvidia gpu or intel igpu so not sure if my issue is the same. Also disabling or adjusting various settings in yuzu config made no difference when set to vulcan.

### Expected Behavior

Vulcan works fine for all my other games being:
pokemon brilliant diamond
mario cart 8 deluxe
legend of zelda botw

### Reproduction Steps

Start game with vulcan.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11284087/yuzu_log.txt)

### System Configuration

CPU: amd ryzen 5800x3d
GPU/Driver: amd 6800xt / 23.4.1
RAM: 32gb @ 3600mhz
OS: win 11 home 22621.1555

**Comment by goldenx86** [comment]
It's a regression in the latest AMD drivers, revert to 23.3.1 to solve it.

**Comment by goldenx86** [comment]
Update to driver 23.4.2, just got out. Should solve it.

**Comment by MasterWitcher22** [comment]
hi golden
i am from the yuzu
*yuzu server
i mentioned my issue in windows support but no one helped
Here it is - Whenever i run pokemon arceus using vulkan yuzu crashes , but it works with open gl but the framarates are bad.
my Config - i3 8100 , 1060 3gb , 16 gb ram
yuzu version - 1456
driver version - 531.79
