### ISSUE TITLE
Crashing whenever I launch a game

### ISSUE THREAD

**Issue by TheRandomWeeb** [yuzu-emu/yuzu#10085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Acess 3507

### Description of Issue

Every time I try to launch a game on Yuzu, it crashes immediately. I don't even get into the loading screen or anything.

### Expected Behavior

Load fully into game

### Reproduction Steps

1. Open Yuzu
2. Select Game
3. Start Game
4. Crash

### Log File

[   0.294556] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.294803] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.295784] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 10.0.0.66:26760
[   0.295792] Debug <Critical> common\uuid.cpp:operator ():135: Assertion Failed!
UUID string has an invalid length of 35 characters!
[   0.408864] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.458511] Frontend <Info> yuzu\main.cpp:GMainWindow:359: yuzu Version: yuzu Early Access 3507
[   0.458540] Frontend <Info> yuzu\main.cpp:LogRuntimes:238: MSVC Compiler: 1934 Runtime: 14.34.31938.0
[   0.458541] Frontend <Info> yuzu\main.cpp:LogRuntimes:247: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.458543] Frontend <Info> yuzu\main.cpp:GMainWindow:375: Host CPU: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz | AVX2 | FMA
[   0.458551] Frontend <Info> yuzu\main.cpp:GMainWindow:377: Host CPU Cores: 6
[   0.458551] Frontend <Info> yuzu\main.cpp:GMainWindow:380: Host CPU Threads: 6
[   0.459009] Frontend <Info> yuzu\main.cpp:GMainWindow:381: Host OS: Windows 11 Version 22H2 (Build 22621.1555)
[   0.459028] Frontend <Info> yuzu\main.cpp:GMainWindow:383: Host RAM: 15.94 GiB
[   0.459029] Frontend <Info> yuzu\main.cpp:GMainWindow:384: Host Swap: 0.00 GiB
[   0.459299] Frontend <Info> yuzu\main.cpp:GMainWindow:389: Host Timer Resolution: 0.5000 ms
[   6.567982] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.27.0) applied successfully
[   7.019254] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   7.204523] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.6.0) applied successfully
[   7.285545] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   7.658332] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.23.0) applied successfully
[   7.815636] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.27.0) applied successfully
[   7.871569] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   7.898971] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.6.0) applied successfully
[   7.916585] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   7.967499] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.23.0) applied successfully
[   8.026779] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[  39.966830] Frontend <Info> yuzu\main.cpp:BootGame:1745: yuzu starting...
[  39.979744] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[  39.990052] Config <Info> common\settings.cpp:LogSettings:40: yuzu Configuration:
[  39.990058] Config <Info> common\settings.cpp:operator ():33: Controls_UseDockedMode: true
[  39.990059] Config <Info> common\settings.cpp:operator ():33: System_RngSeed: 0
[  39.990060] Config <Info> common\settings.cpp:operator ():33: System_DeviceName: Yuzu
[  39.990060] Config <Info> common\settings.cpp:operator ():33: System_CurrentUser: 0
[  39.990061] Config <Info> common\settings.cpp:operator ():33: System_LanguageIndex: 1
[  39.990062] Config <Info> common\settings.cpp:operator ():33: System_RegionIndex: 1
[  39.990064] Config <Info> common\settings.cpp:operator ():33: System_TimeZoneIndex: 0
[  39.990066] Config <Info> common\settings.cpp:operator ():33: Core_UseMultiCore: true
[  39.990067] Config <Info> common\settings.cpp:operator ():33: CPU_Accuracy: 0
[  39.990068] Config <Info> common\settings.cpp:operator ():33: Renderer_UseResolutionScaling: 2
[  39.990068] Config <Info> common\settings.cpp:operator ():33: Renderer_ScalingFilter: 1
[  39.990069] Config <Info> common\settings.cpp:operator ():33: Renderer_FSRSlider: 25
[  39.990069] Config <Info> common\settings.cpp:operator ():33: Renderer_AntiAliasing: 1
[  39.990070] Config <Info> common\settings.cpp:operator ():33: Renderer_UseSpeedLimit: true
[  39.990070] Config <Info> common\settings.cpp:operator ():33: Renderer_SpeedLimit: 100
[  39.990071] Config <Info> common\settings.cpp:operator ():33: Renderer_UseDiskShaderCache: true
[  39.990071] Config <Info> common\settings.cpp:operator ():33: Renderer_GPUAccuracyLevel: 1
[  39.990072] Config <Info> common\settings.cpp:operator ():33: Renderer_UseAsynchronousGpuEmulation: true
[  39.990072] Config <Info> common\settings.cpp:operator ():33: Renderer_NvdecEmulation: 2
[  39.990073] Config <Info> common\settings.cpp:operator ():33: Renderer_AccelerateASTC: true
[  39.990073] Config <Info> common\settings.cpp:operator ():33: Renderer_AsyncASTC: false
[  39.990074] Config <Info> common\settings.cpp:operator ():33: Renderer_UseVsync: true
[  39.990074] Config <Info> common\settings.cpp:operator ():33: Renderer_ShaderBackend: 0
[  39.990075] Config <Info> common\settings.cpp:operator ():33: Renderer_UseAsynchronousShaders: false
[  39.990076] Config <Info> common\settings.cpp:operator ():33: Renderer_AnisotropicFilteringLevel: 4
[  39.990076] Config <Info> common\settings.cpp:operator ():33: Audio_OutputEngine: auto
[  39.990077] Config <Info> common\settings.cpp:operator ():33: Audio_OutputDevice: auto
[  39.990077] Config <Info> common\settings.cpp:operator ():33: Audio_InputDevice: auto
[  39.990078] Config <Info> common\settings.cpp:operator ():33: DataStorage_UseVirtualSd: true
[  39.990080] Config <Info> common\settings.cpp:operator ():37: DataStorage_CacheDir: C:\Users\Admin\AppData\Roaming\yuzu\cache
[  39.990081] Config <Info> common\settings.cpp:operator ():37: DataStorage_ConfigDir: C:\Users\Admin\AppData\Roaming\yuzu\config
[  39.990082] Config <Info> common\settings.cpp:operator ():37: DataStorage_LoadDir: D:/Games/Emus/load\
[  39.990082] Config <Info> common\settings.cpp:operator ():37: DataStorage_NANDDir: D:/Games/Emus/nand\
[  39.990083] Config <Info> common\settings.cpp:operator ():37: DataStorage_SDMCDir: D:/Games/Emus/sd\
[  39.990084] Config <Info> common\settings.cpp:operator ():33: Debugging_ProgramArgs: 
[  39.990084] Config <Info> common\settings.cpp:operator ():33: Debugging_GDBStub: false
[  39.990085] Config <Info> common\settings.cpp:operator ():33: Input_EnableMotion: true
[  39.990085] Config <Info> common\settings.cpp:operator ():33: Input_EnableVibration: true
[  39.990086] Config <Info> common\settings.cpp:operator ():33: Input_EnableTouch: true
[  39.990086] Config <Info> common\settings.cpp:operator ():33: Input_EnableMouse: false
[  39.990086] Config <Info> common\settings.cpp:operator ():33: Input_EnableKeyboard: false
[  39.990087] Config <Info> common\settings.cpp:operator ():33: Input_EnableRingController: true
[  39.990087] Config <Info> common\settings.cpp:operator ():33: Input_EnableIrSensor: false
[  39.990088] Config <Info> common\settings.cpp:operator ():33: Input_EnableCustomJoycon: true
[  39.990088] Config <Info> common\settings.cpp:operator ():33: Input_EnableCustomProController: false
[  39.990089] Config <Info> common\settings.cpp:operator ():33: Input_EnableRawInput: false
[  40.007453] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[  40.224583] Render.Vulkan <Warning> video_core\vulkan_common\vulkan_device.cpp:Device:377: NVIDIA Drivers >= 510 do not support MSAA image blits
[  40.487103] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:156: Driver: NVIDIA 531.68.0.0
[  40.487109] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:157: Device: NVIDIA GeForce GTX 1660
[  40.487109] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:158: Vulkan: 1.3.236
[  40.487112] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:159: Available VRAM: 5.28 GiB
[  40.499472] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[  40.514847] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[  40.571155] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:128: Patching ExeFS for title_id=010028600EBDA000
[  40.572109] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:144:     ExeFS: Update (v0.1.0) applied successfully
[  40.572925] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:175:     ExeFS: LayeredExeFS patches applied successfully
[  40.822139] Debug <Critical> common\virtual_buffer.cpp:operator ():26: Assertion Failed!
[  40.822215] Debug <Critical> common\virtual_buffer.cpp:operator ():26: Assertion Failed!

### System Configuration

CPU: I5-9600KF CPU @ 3.70GHz
GPU/Driver: NVIDIA GeForce GTX 1660
RAM: 16.0 GB
OS: Windows 11 (22H2)

**Comment by goldenx86** [comment]
Assign a page file of at least 10GB.

**Comment by TheRandomWeeb** [comment]
Thank you! This worked perfectly! This error has been driving me crazy for the past few days.

**Comment by crazyguy0510** [comment]
> Assign a page file of at least 10GB.

What does this mean?
