### ISSUE TITLE
Scratches graphic glitch when playing Pokémon Legends: Arceus 

### ISSUE THREAD

**Issue by IdeLuxiz** [yuzu-emu/yuzu#10087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu 1398

### Description of Issue

When you start playing the game after pressing "continue"

PS: It also glitches the entire graphic card, making me force to restart the pc in order to work properly again

![image](https://user-images.githubusercontent.com/115427530/233855041-ab4b6714-c667-486e-9359-8594d06ad673.png)

### Expected Behavior

Without any graphic glitches in the start or in the entire game, or after closing the emulator which still happening

### Reproduction Steps

When playing the game with these configurations (probably)
***IMAGE REMOVED***

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11304366/yuzu_log.txt)

### System Configuration

CPU: Intel Core i5-9600KF CPU @ 3.70GHz

GPU/Driver: Radeon RX 570 Series 4GB

RAM: 16GB

OS: Windows 10 Pro 22H2

**Comment by Eloeri** [comment]
@IdeLuxiz We don't support piracy. Everything for yuzu must come from your Nintendo Switch.
