### ISSUE TITLE
cannot install xbc3 dlc wave 4

### ISSUE THREAD

**Issue by Ww-Ei** [yuzu-emu/yuzu#10099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1409

### Description of Issue

with 16.0.2 firmware and keys, only 2.0.0 update works.

### Expected Behavior

install as usual

### Reproduction Steps

try to install dlc 4 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11334450/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11334451/yuzu_log.txt.old.txt)

### System Configuration

CPU:12900k
GPU/Driver:rtx3090 / studio 531.61
RAM:64gb
OS:windows 11

**Comment by german77** [comment]
Piracy is not allowed

**Comment by Ww-Ei** [comment]
it's dumped from my switch

**Comment by Ww-Ei** [comment]
maybe i missed something, or this one should be placed along with base game like torna for xbc2?

**Comment by german77** [comment]
All content should be obtained legally. Your log says otherwise.
