### ISSUE TITLE
yuzu can't read xenoblade 3 savefiles

### ISSUE THREAD

**Issue by jenkshi** [yuzu-emu/yuzu#10106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu 1412 steam deck and PC

### Description of Issue

I imported my save files from edizon to yuzu savefile location in both my PC and steam deck. both didn't read the savefile and the game acts as if there wasn't any.

### Expected Behavior

the game should load my save files this what I expect.

### Reproduction Steps

I import the file to the save folder > load up the game > the menu says "NEW GAME" .

![image](https://user-images.githubusercontent.com/47603870/235005976-5d0a9e9c-0800-4793-8d26-0fba04f37b74.png)
![image](https://user-images.githubusercontent.com/47603870/235006025-1e5f4b5e-502f-47c9-ac1f-e3187e40752e.png)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11348470/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11348471/yuzu_log.txt.old.txt)

### System Configuration

CPU:Processor	AMD Ryzen 9 5900HX with Radeon Graphics, 3301 Mhz, 8 Core(s), 16 Logical Processor(s)
GPU/Driver: Nvidia RTX 3070 Laptop GPU / ver. 31.0.15.3141
RAM: 32 GB
OS: windows 10

**Comment by goldenx86** [comment]
Install the game updates, the game will refuse to load saves for another game version.

**Comment by PlatinumLucario** [comment]
Yeah, and also, if you're experimenting around with different versions, then it's a good idea to organise the saves into separate folders for each version, otherwise they can easily get mixed up.

Also, the name of the installed game in the log file, looks a bit... How should I say it? Questionable?

**Comment by jenkshi** [comment]
thanks for the help
