### ISSUE TITLE
Xenoblade Chronicles 3 : unable to install wave 4 dlc on yuzu emulator 

### ISSUE THREAD

**Issue by DevilAli** [yuzu-emu/yuzu#10101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1409

### Description of Issue

Xenoblade Chronicles 3: unable to install wave 4 DLC on yuzu emulator Wave

### Expected Behavior

the file needs to be installed  

### Reproduction Steps

select the file

### Log File

![IMG-20230426-WA0026](https://user-images.githubusercontent.com/59016570/234702131-2a427d59-42bb-474a-86e5-d353a4d4534f.jpeg)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11337283/yuzu_log.txt)

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by goldenx86** [comment]
This DLC and update seem to require a very recent firmware to work.
Update both the firmware and the keys.

**Comment by DevilAli** [comment]
th

> This DLC and update seem to require a very recent firmware to work. Update both the firmware and the keys.

I did, it did not work

**Comment by Nicolas-Miranda** [comment]
@goldenx86 The same problem happens with recent released games. I'm trying to play Arcade Archives Rezon and the game doesn't show up in rom list. If I try to open it manually it Yuzu displays the error ErrorMissingKeyAreaKey even when I'm using the firmware 16.0.2 with Prod/Title keys 16.0.0

**Comment by RinMaru** [comment]
> th
> 
> > This DLC and update seem to require a very recent firmware to work. Update both the firmware and the keys.
> 
> I did, it did not work

you do realize if anyone confirms otherwise youve just outted yourself right?

**Comment by DevilAli** [comment]
> > th
> > > This DLC and update seem to require a very recent firmware to work. Update both the firmware and the keys.
> > 
> > 
> > I did, it did not work
> 
> you do realize if anyone confirms otherwise you've just outted yourself, right? did you truly dump your keys with the latest lockpick RCM? it works here so i believe your keys are wrong

I have firmware 16.0.2 with Prod/Title keys 16.0.0, I think this is the latest

**Comment by diademiemi** [comment]
Can confirm redumping keys and firmware solved the issue for me

**Comment by morye** [comment]
https://github.com/The-4n/reNXpack/releases/

use this program and repack the NSP file with a proper prod.keys that you have installed, and it will install DLC on yuzu and switch homebrew. you don't need to do this on ryujinx
