### ISSUE TITLE
Be able to modify the analogue stick direction strength but for keyboard users and make modifier button go over 100% 

### ISSUE THREAD

**Issue by Azzie101** [yuzu-emu/yuzu#10114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Being able to modify the original inputs of the keyboard controls (Making the directional buttons weaker or stronger so they either trigger a walk or run without the modifier button held down.). Then be able to use modifier to increase movement speed back to its max.

Any questions about what I mean I will answer.

### Why would this feature be useful?

This is mainly for keyboard users since they do not have analogue sticks. It helps as now directions are just walk and u can use a modifier button as a run button, which increases speed to the max analogue stick power.

This would be especially useful for games like smash bros where there is no run button, increasing precision of movement. Sprinting puts you into a lot of lag which causes you to lose the ability to do tilt attacks which is very annoying. This makes turnaround tilts impossible as well since you'll dash instead of turning slowly.

**Comment by german77** [comment]
There's no need to go past 100% or have the default at any other value that is not 100%. However there are a few tricks that can help you to achieve your goals. 

If you right click on the modifier button you can set it to a toggle button or an inverted button. So if you don't want to keep the modifier button pressed all the time you can make it a toggle button(press once to active, press again to deactivate). With the invert option it will always walk until you press the button.

**Comment by german77** [comment]
![image](https://user-images.githubusercontent.com/5944268/235314322-85d24b2f-ba56-4d65-9206-f4117fbd28da.png)

**Comment by Azzie101** [comment]
I worded this pretty badly I realised and presented my point not well either. I meant like having the default stick not be 100%, but when the modifier button pressed it becomes 100% or whatever value u want it to be. This is really useful for smash because some players want the default to be walk and not run, and makes the modifier a run button. I hope you give this some consideration.

**Comment by Azzie101** [comment]
I worded this pretty badly I realised and presented my point not well either. I meant like having the default stick not be 100%, but when the modifier button pressed it becomes 100% or whatever value u want it to be. This is really useful for smash because some players want the default to be walk and not run, and makes the modifier a run button. I hope you give this some consideration.

**Comment by german77** [comment]
Did you try what I told you before? By inverting the button the default will be whatever % you set the value and when the modifier button is pressed the stick is now at 100%
https://user-images.githubusercontent.com/5944268/235746442-954961b8-6dfa-4883-8686-20cc57f6df8d.mp4
