### ISSUE TITLE
16.0.x games/updates/DLC not recognized

### ISSUE THREAD

**Issue by subworx** [yuzu-emu/yuzu#10120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1414, 1415

### Description of Issue

16.0.x games don't show up in Yuzu at all even though 16.0.2. firmware and prod.keys are installed. 16.0.0 updates/DLC cannot be installed to NAND ("1 file failed to install"). 

Same games show up and play fine in Ryujinx on same firmware and prod.keys.

This persisted for me since 16.0.0 was released. Would there be a way to show the currently installed FW version somewhere to make sure I installed it correctly?

The error message ("different type than its extension") in the log below also shows up for all DLC and update NSPs in my games directory, regardless of required FW version, so I doubt that's the problem.

### Expected Behavior

Games show up and run.

### Reproduction Steps

- Download Yuzu. 
- Obtain most recent prod.keys available and place it in %appdata%\yuzu\keys.
- Obtain most recent "Firmware 16.0.2.zip" and extract its contents to %appdata%\yuzu\nand\system\Contents\registered.
- Place a 16.0.x game into the games directory, or try installing a 16.0.x update/DLC.
- Start Yuzu.
- Try finding the game in the list.

The same steps done in Ryujinx (get and install keys, get firmware, install it with "install firmware zip" function, put game in directory) work fine.

### Log File

```
[   0.233772] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.233788] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.431307] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.454561] Frontend <Info> yuzu\main.cpp:GMainWindow:359: yuzu Version: yuzu 1414
[   0.454580] Frontend <Info> yuzu\main.cpp:LogRuntimes:238: MSVC Compiler: 1934 Runtime: 14.32.31332.0
[   0.454581] Frontend <Info> yuzu\main.cpp:LogRuntimes:247: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.454582] Frontend <Info> yuzu\main.cpp:GMainWindow:375: Host CPU: AMD Ryzen 5 3600 6-Core Processor               | AVX2 | FMA
[   0.454587] Frontend <Info> yuzu\main.cpp:GMainWindow:377: Host CPU Cores: 6
[   0.454587] Frontend <Info> yuzu\main.cpp:GMainWindow:380: Host CPU Threads: 12
[   0.454731] Frontend <Info> yuzu\main.cpp:GMainWindow:381: Host OS: Windows 10 Version 22H2 (Build 19045.2846)
[   0.454743] Frontend <Info> yuzu\main.cpp:GMainWindow:383: Host RAM: 31.91 GiB
[   0.454750] Frontend <Info> yuzu\main.cpp:GMainWindow:384: Host Swap: 2.00 GiB
[   0.454778] Frontend <Info> yuzu\main.cpp:GMainWindow:389: Host Timer Resolution: 0.4991 ms
[   3.096924] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   3.732319] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.3.0) applied successfully
[   3.908499] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.2.0) applied successfully
[   4.143261] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.3.0) applied successfully
[   4.353395] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   4.721047] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   4.914172] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.5.0) applied successfully
[   6.434747] Loader <Warning> core\loader\loader.cpp:GetLoader:257: File Picross S9 [010021A0197BA000][v0][US].nsp has a different type (unknown) than its extension.
```

### System Configuration

CPU: Ryzen 5 3600
GPU/Driver: Geforce 2070 Super / 531.41
RAM: 32 GB
OS: Win10 22H2 19045.2846

**Comment by G-Spawn** [comment]
Update all your cfw payloads on console (Tegra, Lockpick, etc), play the game updated on it, then redump.

**Comment by subworx** [comment]
Not sure if redumping the game helps, as everything that requires 16.0.x does not work, while the dumps work just fine on another emulator.

**Comment by LokeYourC3PH** [comment]
Facing the same issue, several 16.x games don't show up on Yuzu. I've dumped my all my keys again through Lockpick_RCM just to make sure, but they do not show up, while I have no issues on RyujiNX. So it's clearly an issue with Yuzu.

**Comment by LokeYourC3PH** [comment]
@G-Spawn Please open the issue again, several people are facing the same issue, also on Reddit. Updating keys and such doesn't do anything, it's an issue with Yuzu.

**Comment by Squall-Leonhart** [comment]
This is user error, yuzu is fine with 16.x games so long as the correct prod.keys as dumped from their own console and not something they found online pretending to be a 16.0 key despite being dated 2022.
