### ISSUE TITLE
Slow sound effects

### ISSUE THREAD

**Issue by Coderst1** [yuzu-emu/yuzu#10158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1420

### Description of Issue

Sound effects are slow in Kirby Star Allies

https://user-images.githubusercontent.com/101987498/236307913-10decd63-4553-4256-a46f-93f47fb2ea18.mp4

### Expected Behavior

https://user-images.githubusercontent.com/101987498/236308152-70dfe7f5-1b9a-4cac-9e76-1c0fbca0be8a.mp4

### Reproduction Steps

Just do anything that uses sound effects like hovering over stuff in main menu for example

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11400848/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 9 5900HS
GPU/Driver: Nvidia GeForce 3060 Mobile
RAM: 16GB
OS: Windows 10

**Comment by lKomus** [comment]
I have the same problem with Captain Toad, a lot of sound effects are being slowed down while the game runs at 60 FPS.

**Comment by lKomus** [comment]
Captain Toad is fixed! Nice
