### ISSUE TITLE
Option to disable automatic shortcut creation after update (Windows)

### ISSUE THREAD

**Issue by maxomatic458** [yuzu-emu/yuzu#10152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Right now, every time yuzu updates it will create a new Desktop shortcut. I think it would be useful to have an option that can disable this behavior. (I searched the in-app settings, and the config files and I wasn't able to find a setting like this)

### Why would this feature be useful?

People who dont want a shortcut of yuzu, wont have to delete it (the shortcut) everytime if yuzu updates.

**Comment by FearlessTobi** [comment]
Thanks for your report, however your issue belongs into the https://github.com/j-selby/liftinstall/issues repo.
