### ISSUE TITLE
Keyboard shortcut for multiplayer functions 

### ISSUE THREAD

**Issue by null-von-sushi** [yuzu-emu/yuzu#10169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Please consider adding configurable shortcuts for the multiplayer functions like browsing the lobby, create room, direct connect etc.
Ideally this should be configurable under General -> Hotkeys.
Thank you for the hard work thus far, and thank you for considering my request 🙏

### Why would this feature be useful?

Apart from just being useful for players to have this option, this would also allow steam deck users to bing a key to a virtual on-screen menu, thus making Yuzu a lot easier to use with a controller.

While I obviously can't say for sure, I assume this should not be too difficult to implement as yuzu already supports screenshots for stuff like full screen， and multiplayer itself is already implemented (at least fake local wireless is).

**Comment by null-von-sushi** [comment]
sorry, but has this been implemented now? I am used to github issues being closed and specfic changes being referenced, I am not sure what "1 task done" means though.

**Comment by Calinou** [comment]
This doesn't appear to be implemented yet as of yuzu 1689:

![image](https://github.com/yuzu-emu/yuzu/assets/180032/73bd4aa7-af8c-4adc-bbd8-377f77f239fe)

> I am not sure what "1 task done" means though.

The "1 task done" is because the first post in the issue contains a ticked checkbox (for "I have searched the existing issues"), so you can ignore it.

**Comment by null-von-sushi** [comment]
Ooh I see, right.
Thanks for the explanation, I wasn't aware that's how it worked.
