### ISSUE TITLE
Shader precache feature

### ISSUE THREAD

**Issue by DuckersMcQuack** [yuzu-emu/yuzu#10163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I want to request a feature for yuzu to toggle in settings that loads and precache's the entire game's shader library in sequence to compile on game launch, kind of  like ps3 emu does, where it has one cache or whatever it was that compiles one thing per thread of your cpu on launch automatically for every new game you start for the first time. So that when we start a game, and if we have a good multicore cpu, it will then say with a 12 core, process all the shaders of the game individually on each of the 24 threads and queue the next onto the first finished thread available. And if we have a shader cache already acquired, if it's missing something, it will then prescan the existing for missing ones to have a complete precache of each game.

### Why would this feature be useful?

**Note: Downloading shaders has never been legal. You've always been expected to build your own. A feature request like this would help users build it faster or ahead of time**

**Comment by Kelebek1** [comment]
I don't know how the PS3 works, but I don't think it's possible for us to know the shaders ahead of time?

**Comment by goldenx86** [comment]
From what I understand, what Dolphin and RPCS3 do is bruteforce all possible combinations.
Do that for a Maxwell GPU like here and you will get minutes per frame.

**Comment by goldenx86** [comment]
@v1993 is correcting me here. What They do is emulate the fixed function pipeline of those old GPUs.
The difference in complexity between the old D3D9 era of fixed-function shaders and what modern GPUs use is too big to consider this option for now.
Maybe in 10 years.

**Comment by DuckersMcQuack** [comment]
> From what I understand, what Dolphin and RPCS3 do is bruteforce all possible combinations. Do that for a Maxwell GPU like here and you will get minutes per frame.

But it's then already precached by the cpu, so no stuttering if it's already all precached.

And maxwell is hella outdated/old as well.

**Comment by v1993** [comment]
This was noted in the very next comment to be incorrect. Ubershaders are explained very well in [this dolphin blog post](https://dolphin-emu.org/blog/2017/07/30/ubershaders/).

Dolphin's ubershaders are already very demanding, needing a high-end GPU to run in HD, and they are emulating fixed-function pipeline of a truly ancient GPU, while neither applies in yuzu's case. Maxwell was released in *2014*, GameCube in *2001*. 13 years of rapid GPU technology advancement is a ***lot***. It's simple infeasible to make this work at current point in time - even yuzu's version of hybrid ubershaders (use ubershader until specialized shader finished recompiling) would tank framerate to the point of triggering GPU timeouts.
