### ISSUE TITLE
Memory access checking is not always desirable even when GDB stub is in use

### ISSUE THREAD

**Issue by comex** [yuzu-emu/yuzu#10161]
### Issue

`arm_dynarmic_64.cpp` enables checking for invalid memory reads/writes if either the "Enable fallbacks for invalid memory accesses" setting is unchecked, or the GDB stub is enabled:
```
          check_memory_access{debugger_enabled ||
                              !Settings::values.cpuopt_ignore_memory_aborts.GetValue()} {}
```

Unfortunately, Super Mario Maker 2 repeatedly dereferences null pointers when running (this has something to do with fonts and has always been an issue), so GDB keeps stopping with messages like:
```
Thread 2 "Prepare Thread" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 77]
0x0000000008247598 in ?? ()
```
However, the game does work when ignoring the invalid accesses, and I would like to use GDB with it.  Therefore I need `check_memory_access` to be false despite having the debugger enabled.

(For some reason, I haven't had this issue before, even though the above-mentioned code was already in place when I last used the debugger in March.  For now I'll just edit it locally.  Maybe I should investigate the actual cause of the null pointers…)

**Comment by liamwhite** [comment]
I think it would be best to resolve the memory errors. Enabling memory access checking isn't a convenience feature of the gdb server - it's required to have it enabled for watchpoints to work, and nontrivial to toggle at runtime.

**Comment by comex** [comment]
Sorry, I'm an idiot.  I forgot that the only reason I had this working before is that I had added a hack specifically for that purpose.
