### ISSUE TITLE
Yuzu Dragon Ball Z Kakarot Stürzt ab im Hauptmenü

### ISSUE THREAD

**Issue by Emre1008** [yuzu-emu/yuzu#10179]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Affected Build(s)

Yuzu 1422

### Description of Issue

Das Spiel startet stürzt aber im Hauptmenü ab könnte mir einer helfen bitte

### Expected Behavior

?

### Reproduction Steps

?

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11413597/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5 5600G with Radeon Graphics            3.90 GHz
GPU/Driver: Nvidia Geforce rtx 3060
RAM: 32 GB
OS: 64-Bit-Betriebssystem, x64-basierter Prozessor

**Comment by FearlessTobi** [comment]
Das hier ist ein englisches Forum für Softwareentwickler.
Bitte benutze unseren Discord für Support.
