### ISSUE TITLE
Unmapped Read64，unimplemented function 'OpenCacheStorageList'

### ISSUE THREAD

**Issue by xinye0123** [yuzu-emu/yuzu#10177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3559

### Description of Issue

[ 101.245549] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 101.317573] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 101.318480] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 101.319292] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 102.910660] Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:873: called.
[ 102.953312] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 102.961036] Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:873: called.
[ 102.964000] Service.AM <Warning> core\hle\service\am\am.cpp:SetOperationModeChangedNotification:406: (STUBBED) called flag=true
[ 102.964091] Service.AM <Warning> core\hle\service\am\am.cpp:SetPerformanceModeChangedNotification:416: (STUBBED) called flag=true
[ 102.966691] Debug <Critical> core\hle\service\filesystem\fsp_srv.cpp:operator ():897: Assertion Failed!
[ 102.975019] Debug <Critical> core\hle\service\service.cpp:operator ():135: Assertion Failed!
Unknown / unimplemented function 'OpenCacheStorageList': port='fsp-srv' cmd_buf={[0]=0x6, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x1, [6]=0x0, [7]=0x0, [8]=0x49434653}
[ 102.978453] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000008
[ 102.978468] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000010
[ 102.978476] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000000

### Expected Behavior

[ 102.966691] Debug <Critical> core\hle\service\filesystem\fsp_srv.cpp:operator ():897: Assertion Failed!
[ 102.975019] Debug <Critical> core\hle\service\service.cpp:operator ():135: Assertion Failed!
Unknown / unimplemented function 'OpenCacheStorageList': port='fsp-srv' cmd_buf={[0]=0x6, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x1, [6]=0x0, [7]=0x0, [8]=0x49434653}
[ 102.978453] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000008
[ 102.978468] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000010
[ 102.978476] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000000

### Reproduction Steps

[ 102.966691] Debug <Critical> core\hle\service\filesystem\fsp_srv.cpp:operator ():897: Assertion Failed!
[ 102.975019] Debug <Critical> core\hle\service\service.cpp:operator ():135: Assertion Failed!
Unknown / unimplemented function 'OpenCacheStorageList': port='fsp-srv' cmd_buf={[0]=0x6, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x1, [6]=0x0, [7]=0x0, [8]=0x49434653}
[ 102.978453] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000008
[ 102.978468] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000010
[ 102.978476] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000000

### Log File

[  63.782569] Service.AM <Warning> core\hle\service\am\am.cpp:GetGpuErrorDetectedSystemEvent:1794: (STUBBED) called
[  63.796841] Service.AM <Warning> core\hle\service\am\am.cpp:AcquireForegroundRights:92: (STUBBED) called
[  63.797784] Service.AM <Warning> core\hle\service\am\am.cpp:SetFocusHandlingMode:435: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[  63.798737] Service.AM <Warning> core\hle\service\am\am.cpp:SetOutOfFocusSuspendingEnabled:454: (STUBBED) called enabled=false
[  63.803155] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  63.809562] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  63.812458] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  63.818084] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  63.818655] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  63.820250] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.2.0) applied successfully
[  68.111224] Service.AM <Warning> core\hle\service\am\am.cpp:SetFocusHandlingMode:435: (STUBBED) called. unknown0=1, unknown1=0, unknown2=1
[  68.113521] Service.AM <Warning> core\hle\service\am\am.cpp:SetOutOfFocusSuspendingEnabled:454: (STUBBED) called enabled=false
[  68.114781] Service.AM <Warning> core\hle\service\am\am.cpp:SetRestartMessageEnabled:442: (STUBBED) called
[  68.115147] Service.AM <Warning> core\hle\service\am\am.cpp:SetOperationModeChangedNotification:406: (STUBBED) called flag=true
[  68.115528] Service.AM <Warning> core\hle\service\am\am.cpp:SetPerformanceModeChangedNotification:416: (STUBBED) called flag=true
[  68.144613] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  68.163655] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:419: Patching RomFS for title_id=0100F2C0115B6000, type=01
[  68.166259] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.2.0) applied successfully
[  80.632365] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:419: Patching RomFS for title_id=0100F2C0115B6000, type=01
[  80.634826] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.2.0) applied successfully
[  93.606619] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.2.0) applied successfully
[  93.611806] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.2.0) applied successfully
[  93.641590] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:Initialize:153: (STUBBED) called
[  93.647497] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:SetAruid:193: (STUBBED) called, pid=0x87
[  93.649630] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:SetGraphicsFirmwareMemoryMarginEnabled:201: (STUBBED) called
[  93.660114] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetManagerDisplayService:460: (STUBBED) called
[  93.661302] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetSystemDisplayService:452: (STUBBED) called
[  93.662425] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetRelayService:444: (STUBBED) called
[  93.675648] Service.VI <Warning> core\hle\service\vi\vi.cpp:OpenDisplay:476: (STUBBED) called
[  93.678713] Service.AM <Warning> core\hle\service\am\am.cpp:CreateManagedDisplaySeparableLayer:481: (STUBBED) called
[  93.689305] Service.VI <Warning> core\hle\service\vi\vi.cpp:AdjustRefcount:110: (STUBBED) called id=1, addval=00000001, type=00000000
[  93.690623] Service.VI <Warning> core\hle\service\vi\vi.cpp:AdjustRefcount:110: (STUBBED) called id=1, addval=00000001, type=00000001
[  93.698390] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetNativeHandle:121: (STUBBED) called id=1, unknown=0000000F
[  93.801967] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  93.951630] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:AllocGPFIFOEx2:185: (STUBBED) called, num_entries=8000, flags=1, unk0=0, unk1=0, unk2=0, unk3=0
[  93.952538] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:AllocateObjectContext:204: (STUBBED) called, class_num=B197, flags=0
[  93.954440] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:SetErrorNotifier:165: (STUBBED) called, offset=0, size=1000, mem=10
[  93.955330] Service.NVDRV <Info> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:ChannelSetTimeout:343: called, timeout=0x266
[  93.958383] Service.NVDRV <Info> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:ChannelSetTimeslice:351: called, timeslice=0x400
[  93.996506] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  94.023042] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  94.102720] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  94.104400] Service.ACC <Warning> core\hle\service\acc\acc.cpp:InitializeApplicationInfoV2:832: (STUBBED) called
[  94.115425] Service.AOC <Warning> core\hle\service\aoc\aoc_u.cpp:CheckAddOnContentMountStatus:296: (STUBBED) called
[  94.177767] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  94.180797] Service.HID <Info> core\hid\emulated_controller.cpp:SetPollingMode:1209: Set polling mode 0, device_index=3
[  97.019536] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:251: (STUBBED) called
[  97.019546] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:259: Avoiding passing null pointer to memcpy
[ 100.950981] Service.Audio <Info> audio_core\sink\cubeb_sink.cpp:CubebSinkStream:77: Opening cubeb stream ADSP_RenderStream-0 type 0 with: rate 48000 channels 2 (system channels 2) latency 480
[ 101.023336] Service.Audio <Info> audio_core\sink\cubeb_sink.cpp:CubebSinkStream:77: Opening cubeb stream ADSP_RenderStream-1 type 0 with: rate 48000 channels 2 (system channels 2) latency 480
[ 101.127207] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 101.242908] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 101.244803] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 101.245549] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 101.317573] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 101.318480] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 101.319292] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 102.910660] Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:873: called.
[ 102.953312] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 102.961036] Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:873: called.
[ 102.964000] Service.AM <Warning> core\hle\service\am\am.cpp:SetOperationModeChangedNotification:406: (STUBBED) called flag=true
[ 102.964091] Service.AM <Warning> core\hle\service\am\am.cpp:SetPerformanceModeChangedNotification:416: (STUBBED) called flag=true
[ 102.966691] Debug <Critical> core\hle\service\filesystem\fsp_srv.cpp:operator ():897: Assertion Failed!
[ 102.975019] Debug <Critical> core\hle\service\service.cpp:operator ():135: Assertion Failed!
Unknown / unimplemented function 'OpenCacheStorageList': port='fsp-srv' cmd_buf={[0]=0x6, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x1, [6]=0x0, [7]=0x0, [8]=0x49434653}
[ 102.978453] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000008
[ 102.978468] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000010
[ 102.978476] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000000

### System Configuration

CPU: E5 2665
GPU/Driver: GTX1063
RAM: 32G
OS: Win11

**Comment by FernandoS27** [comment]
Which game is this and can you please upload the full log?

**Comment by Squall-Leonhart** [comment]
I suspect this is a certain unreleased game, as the certain unreleased game has a patch that implements said feature.

**Comment by Aniket-x** [comment]
Turning off force maximum clocks fixed it for me.
