### ISSUE TITLE
DS4 Controller Stick Range Limited in 3561

### ISSUE THREAD

**Issue by lordtomtom** [yuzu-emu/yuzu#10184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3561

### Description of Issue

I just updated to 3561 and on my DS4 Controller the stick input ranges are stuck in the upper left of their range, ie, I only have full left and full up on both sticks. Down and right only move about 20% of their range. Anyone else experience this? This behavior is across just using the DS4 Controller direct in Yuzu and using DS4 windows as an emulated 360 controller. Checking in the Windows controller properties shows that the OS is seeing the full stick range.

Posted on Reddit :

https://www.reddit.com/r/yuzu/comments/13aej3x/ds4_controller_stick_range_limited_in_3561/

https://www.reddit.com/r/yuzu/comments/13aej32/ps5_controller_sticks_not_moving_all_the_way/

### Expected Behavior

Playstation controller sticks should show their full range.

### Reproduction Steps

Use any DS4 or DS5 controller in Yuzu

### Log File

None

### System Configuration

CPU: i7-6700k
GPU/Driver: 3080 10GB
RAM: 32 GB
OS: Windows 10

**Comment by german77** [comment]
Already fixed. Wait an hour for the next build
