### ISSUE TITLE
Profile Selection Applet: Start game by double-clicking a profile

### ISSUE THREAD

**Issue by Qigo42** [yuzu-emu/yuzu#10185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

**Allow the user to select a profile and start the game with just a double click in the tree view.**

I modified the source code myself and it works fine:

*src/yuzu/applets/qt_profile_select.cpp:*

In the constructor of class QtProfileSelectionDialog add the line:
```connect(tree_view, &QTreeView::doubleClicked, this, &QtProfileSelectionDialog::accept);```

after
```connect(tree_view, &QTreeView::clicked, this, &QtProfileSelectionDialog::SelectUser);```

### Why would this feature be useful?

It's not a huge change, but I find it more convenient not to have to additionally click OK to start a game with the selected profile.

**Comment by FearlessTobi** [comment]
I agree this is a useful change. Please make a PR then.

**Comment by Qigo42** [comment]
Ok, done:

[PR #10189](https://github.com/yuzu-emu/yuzu/pull/10189)
