### ISSUE TITLE
Silent install option for liftinstall installer

### ISSUE THREAD

**Issue by soredake** [yuzu-emu/yuzu#10190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It would be nice if liftinstall can have options like `--silent --type early_access/mainline` so yuzu liftinstall can be packaged to winget/chocolatey.

### Why would this feature be useful?

For packaging yuzu liftinstall installer to chocolatey/winget.

**Comment by liamwhite** [comment]
Please file this issue here: https://github.com/j-selby/liftinstall
