### ISSUE TITLE
[macOS] Building with Apple Clang fails after #10125

### ISSUE THREAD

**Issue by shinra-electric** [yuzu-emu/yuzu#10193]
### Issue

Issue:
Yuzu no longer builds with Apple Clang after #10125

Checking out the previous commit  82188b2 using git and Yuzu builds fine. #10174
[Terminal Output 82188b2 (Success).txt](https://github.com/yuzu-emu/yuzu/files/11415911/Terminal.Output.82188b2.Success.txt)

Checking out 3547248 and the build fails. #10125
[Terminal Output 3547248 (fail).txt](https://github.com/yuzu-emu/yuzu/files/11415912/Terminal.Output.3547248.fail.txt)

System:
MBP M1 Pro
Ventura 13.3.1
Xcode 14.3

**Comment by liamwhite** [comment]
Do you know if there are any free-for-open-source CIs that run with the latest xcode? Asking for a friend...

**Comment by shinra-electric** [comment]
Your friend might be interested in Cirrus CI...? [RPCS3](https://cirrus-ci.com/github/RPCS3/rpcs3) uses them, they have macOS Arm runners (though RPCS3 only build x64 artifacts right now)

**Comment by shinra-electric** [comment]
Github Actions apparently are have macOS Arm runners [in beta](https://github.com/orgs/github/projects/4247/views/1?pane=issue&itemId=5944419)

**Comment by liamwhite** [comment]
Latest xcode is a hard requirement, we need libc++ either 15 or 16 to compile.

**Comment by shinra-electric** [comment]
I don't claim to know how it works, but as far as I know they set up a docker file that has the Xcode command-line tools installed.

Or something like that...
