### ISSUE TITLE
修复王国之泪地下贴图错误

### ISSUE THREAD

**Issue by Ptuer-swpu** [yuzu-emu/yuzu#10198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

我发现了一个能修复地下贴图错误的代码改动，我觉得你们官方是知道的，但不知道为什么没有修复
打开源码文件夹里的src\shader_recompiler\backend\spirv\emit_spirv_context_get_set.cpp文件，定位到第391行，将"return ctx.OpISub(ctx.U32[1], index, base);"改为"return ctx.OpLoad(ctx.U32[1], ctx.vertex_index);"。

### Why would this feature be useful?

希望能采纳，这样玩家就不用下载其他非官方的exe了，还能使玩家正常游玩地下。

**Comment by bunnei** [comment]
This game is not released yet. We do not condone piracy here.
