### ISSUE TITLE
SDL motion controls not working on Linux

### ISSUE THREAD

**Issue by Mutcholoko** [yuzu-emu/yuzu#10191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3564 / Mainline 1423

### Description of Issue

I'm using Fedora/Arch Linux, and the SDL motion controls doesn't seem to be detected on Yuzu.
I tried with the DualSense Controller, with the 8BitDo Pro 2, and also with the original Switch Pro Controller, with the Flatpak, Appimage, and installed versions. None of them detected the motion controls, and iirc, this used to work just fine on Linux before.

### Expected Behavior

SDL motion controls should be detected, and be easily configurable on the controller settings tab.

### Reproduction Steps

Install any recent version of Yuzu on Linux via flatpak or the default liftinstall version.
Connect a controller with gyro such as the DualSense or the Pro Controller.
Go to settings, controls, and try to set the motion controls by shaking the controller. 

### Log File

[log.txt](https://github.com/yuzu-emu/yuzu/files/11415680/log.txt)

### System Configuration

CPU: Ryzen 7 5700G
GPU/Driver: Nvidia RTX 3060 Ti / Nvidia driver version 530.41.03.
RAM: 32 GB DDR4
OS: Fedora Linux 38 / Arch Linux

**Comment by german77** [comment]
HIDAP is needed to get motion input,  create the following udev rule:
`KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="plugdev"`
Make sure that you're in plugdev group and add yourself to it if you aren't. Reboot once you're done.

**Comment by Mutcholoko** [comment]
Okay, this does seem to solve the problem. Thanks!
