### ISSUE TITLE
Rendering error with Maxwell graphics card

### ISSUE THREAD

**Issue by neuron42** [yuzu-emu/yuzu#10200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1423 & EA 3571 & EA 3549

### Description of Issue

I used an older version of the driver because the latest version of the driver for Maxwell architecture graphics cards does not support vulkan mode.

When I use Mainline 1423, everything renders fine, the only problem is that when I enter the temple to solve the puzzle, the game becomes very laggy.

After I tried all the recent ea versions, I found that the mapping is all black in versions after 3549
Version 3549 and earlier behaved just like the mainline version, rendering everything fine, the only problem was that when I entered the temple to solve the puzzle, the game became stuck.

The only problem was that when I entered the temple to solve the puzzle, the game became very stuck. This investigation showed that the version after 3549 must have caused the rendering problem. And some ea version after that solved the temple lag problem

This error can only be reproduced on Maxwell graphics cards, newer graphics architectures do not have such problems

I'm not a native speaker, if this paragraph in English is difficult to understand , I'm very sorry.

### Expected Behavior

I would like to make sure that the temple puzzles are smooth while the game display works. And the current build can only satisfy one of the two

### Reproduction Steps

This error can only be reproduced on Maxwell graphics cards

### Log File

 
EDITED

### System Configuration

CPU: i7-6700k
GPU/Driver: 512.95
RAM: 16GB
OS: Windows 10 x64

**Comment by goldenx86** [comment]
We can't offer support on piracy.
