### ISSUE TITLE
DualSense Edge not properly recognized - gyro doesn't work and control list doesn't automatically populate

### ISSUE THREAD

**Issue by kin-patsu** [yuzu-emu/yuzu#10214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Acces 3574

### Description of Issue

There is currently no way to have motion controls working with the DualSense Edge. Despite the controller being recognized, shaking it as the config screen says does actually nothing, resulting in Motion always showing [not set]. 

Furthermore, the config doesn't automatically populate the controls like it does on a regular DualSense, but this is only a minor issue

### Expected Behavior

Gyro is recognized and control list automatically populates

### Reproduction Steps

Connect DualSense Edge
Open Controls under config
Command list is empty
Try and shake the controller for gyro
Nothing happens

### Log File

No log, here's a screenshot of what happens when defaulting the commands:

![image](https://github.com/yuzu-emu/yuzu/assets/19828171/29787120-1bd2-4711-97a7-ee4e148ebe64)

### System Configuration

CPU: 12700kf
GPU/Driver: RTX 4090 531.79
RAM: 2x16GB 3600MT CL16
OS: Windows 11

**Comment by german77** [comment]
Edge is only available on sdl3. I will add support once any stable build is available

**Comment by Squall-Leonhart** [comment]
> Edge is only available on sdl3. I will add support once any stable build is available

Thats not true, its present in SDL2 as well.
https://github.com/libsdl-org/SDL/blob/86786ed5447fe32ea2e48f12f0598816a76721c2/src/joystick/SDL_joystick.c#L2372
https://github.com/libsdl-org/SDL/blob/86786ed5447fe32ea2e48f12f0598816a76721c2/src/joystick/hidapi/SDL_hidapi_ps5.c#L493

**Comment by robfrawley** [comment]
@german77 Is there anything I can do to assist in testing DualSense Edge support?

**Comment by german77** [comment]
I opened https://github.com/yuzu-emu/yuzu/pull/10389 to update SDL to latest available. You can try the artifacts if you want. Just waiting for mingw to have this version up-streamed since I didn't noticed they haven't updated yet

**Comment by kin-patsu** [comment]
> I opened #10389 to update SDL to latest available. You can try the artifacts if you want. Just waiting for mingw to have this version up-streamed since I didn't noticed they haven't updated yet

Had the time to test just now, that does indeed do the trick. 
Furthermore, simply replacing the SDL2.dll in the latest Yuzu with the one from your pull (or even with the one downloaded from the SDL github) works just as well

**Comment by german77** [comment]
waiting for mingw to update to latest sdl
