### ISSUE TITLE
RDNA 3 Anisotropic Filtering Visual Artifacting

### ISSUE THREAD

**Issue by NethanTroi** [yuzu-emu/yuzu#10212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1424

### Description of Issue

Using an RDNA3-based GPU, visual Artifacting occurs in Yuzu. CEMU has had the same issue with version 1.26.2f, was fixed in the 2.0 release.

### Expected Behavior

Properly working anisotropic filtering (this seems to be whats causing the issue)

### Reproduction Steps

Use an RDNA3-based GPU
Start a game, Breath of the Wild in my case.
Observe visual artifacting
![yuzzubug2](https://github.com/yuzu-emu/yuzu/assets/114401894/2e6c6c34-a2a4-4193-9e22-7fdcbd1f4196)
![yuzubug](https://github.com/yuzu-emu/yuzu/assets/114401894/4ae85d4b-e1a0-4cf0-ad7c-2c055ff5789c)

### System Configuration

CPU: AMD Ryzen 9 7950X3D
GPU/Driver: AMD Radeon RX 7900 XTX / AMD Software Adrenaline Edition 23.4.3
RAM: 2x16 GB Corsair Vengeance RGB Pro 6000MT CL30
OS: Microsoft Windows 11 Pro 22H2 Build 22621.1635

**Comment by BSoDGamingYT** [comment]
Support is not provided on leaked games. Closing issue
