### ISSUE TITLE
MinGW builds cannot run guests

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#10232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1223 and later

### Description of Issue

Caused by #8858 -- @vonchenplus your input would be valuable here

Trying to boot a game in yuzu compiled via a MinGW toolchain (either Clang or GCC) causes the application to freeze shortly after it starts. The guest fails to run for more than a couple seconds.

Only the null graphics backend can run the game. Both OpenGL and Vulkan are affected by this.

### Expected Behavior

The game should boot and run for an extended period of time.

### Reproduction Steps

- Compile yuzu with a MinGW toolchain, i.e. with our linux-mingw Docker container, used in CI.
- Run a guest program (i.e. es2gears.nro)
- Either yuzu stops at loading the application, or the application loads and runs for a few seconds before 0 fps and freeze

### Log File

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/11454852/yuzu_log.zip)

### System Configuration

CPU: Intel Core i5-11600k
GPU/Driver: NVIDIA RTX A4000 / 528.89
RAM: 16 GB
OS: Windows 10 Pro

**Comment by vonchenplus** [comment]
I can't reproduce the issue on windows.

**Comment by lat9nq** [comment]
Did you run a MinGW build?

**Comment by lat9nq** [comment]
My mistake, the issue might not be #8858

Please make sure the Git commit history is clean before merging in the future, as I am not able to use git bisect around the code in the mentioned PR.

**Comment by lat9nq** [comment]
Caused by #9135
