### ISSUE TITLE
The Legend of Zelda Tears of the Kingdom, Really BAD Burned in Graphics it Corrupts YUZU User FOLDER & 1970 Saves Date!

### ISSUE THREAD

**Issue by Kristijan1001** [yuzu-emu/yuzu#10241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3582

### Description of Issue

VULKAN

First of all the simple problem with the TOTKYuzuFix the person who made it also fixed the dates on the Saves & the one Slot Save Issue, dunno if the one slot issue is present. But since removing the TOTKYuzuFix the 1970 Date on Saves is back. This was not fixed. Pretty sure it won't let u save more than one slot since the time is always 1970 12 AM.

![image](https://github.com/yuzu-emu/yuzu/assets/24441639/d01fbbef-3411-4432-838c-f2f4f7fe58d4)

~~Second more complicated stuff. Broken Aiming with Bow. It is really bad unplayable. This happened once i got to the point where you get to a lower gravity island. Worst part of it, once it happens it sticks and corrupts ur whole YUZU. REALLY BAD. Dunno what file it affects but i tried removing shader cache and the problem was still there. Only way i fixed it is by wiping my Yuzu and starting fresh. You might say how is that possible well i have no idea logs attached. I even restored my user folder from Recycle Bin Afterwards and the issue was back. Again i cleaned the shader cache.~~

~~This took awhile to Test and figure out. Since it drove me mad why was this happening all of a sudden. I even went back and tested older versions issue was still there only way to get rid of it was to wipe my YUZU folder. Then no issue, i return my old YUZU folder issue is back. I also copied all the settings between the 2 yuzu installations so it shouldn't matter.~~

~~Note i have played this game for tens of hours and this is the first time it happened.~~

![yuzu_SsvyvSpKD9](https://github.com/yuzu-emu/yuzu/assets/24441639/b2103dbd-7646-4004-8c75-ee5d35cffded)

### Expected Behavior

^

### Reproduction Steps

^

### Log File

^

### System Configuration

CPU: i9 9900k
GPU/Driver: 2070 Super
RAM: 32GBs
OS: Win 11

**Comment by Squall-Leonhart** [comment]
You do not have the 1.1.0 update, or it is not installed.

the Time / Date issue is being looked into in #10226

**Comment by Kristijan1001** [comment]
> You do not have the 1.1.0 update, or it is not installed.
> 
> the Time / Date issue is being looked into in #10226
> 
> > Worst part of it, once it happens it sticks and corrupts ur whole YUZU. REALLY BAD.
> 
> No, absolutely not, calibrate your motion controls properly or use the stick to aim which also, works fine.

I am not sure what u are talking about this has nothing to do with controller sticks ? Also i do have the update its 1.1.0, i always have the update.

![image](https://github.com/yuzu-emu/yuzu/assets/24441639/71f1e3a1-55f2-4cab-aa91-7b4c69ad5099)

**Comment by Squall-Leonhart** [comment]
Then you must have a corrupted vulkan shader cache, if you experienced any of the color explosions with 1.0.0 they are likely now affecting 1.1.0 too.

> I am not sure what u are talking about this has nothing to do with controller sticks ? Also i do have the update its 1.1.0, i always have the update.

There is no feasible way that bow aiming would be broken in a way that persists across game sessions, short of it being bad motion calibration data, or a controller experiencing interference.

**Comment by Kristijan1001** [comment]
> Then you must have a corrupted vulkan shader cache, if you experienced any of the color explosions with 1.0.0 they are likely now affecting 1.1.0 too.
> 
> > I am not sure what u are talking about this has nothing to do with controller sticks ? Also i do have the update its 1.1.0, i always have the update.
> 
> There is no feasible way that bow aiming would be broken in a way that persists across game sessions, short of it being bad motion calibration data, or a controller experiencing interference.

Not sure why you are bringing up motion calibration data ? What does this have to do with Graphical issues ? 

Also i was never on 1.0, and no the shader cache is not corrpted because i cleaned it and it still happens, only way to get rid of it is to get a new yuzu user directory. 

AFter further testing, on x2 it does this

Flickering when aiming a Bow. (Fixed Using Shadow Resolution Patch "00D075AC 0B808052 00D075B0 17000014")

https://i.imgur.com/j4p2KWn.mp4

on x3 it does what is showed on the picture.

I was the one that provided all the issues in the other thread i never experinced this until now.

**Comment by Kristijan1001** [comment]
Like the game even drops to 15 fps its wild. Such a weird issue i am going to start replacing files in the user directory and see where the problem is.

![image](https://github.com/yuzu-emu/yuzu/assets/24441639/68f81d6f-fa20-45d0-8228-8ef997843892)

**Comment by Kristijan1001** [comment]
After further testing, it seems like it was the update file that was installed, i had a semi portable setup going. Looks like the update got corrupted and stopped loading, but i am confused why it says 1.1.0 still on the top of the title bar instead of bringing up an error. I also know this burn out graphics was something that was an issue in 1.0, but i was confused why it happened on 1.1 this happened after yuzu update. So i thought the version of yuzu was broken so i went back and the same thing happen, removed shader chace still the same. So what i belive happened is corrupt update, yuzu still shows 1.1.0 in title bar but doesnt even load the update hence broken 1.0 issues arise. 

We can close this issue i guess. This took hours to troubleshoot lol, such a dumb thing.

**Comment by Squall-Leonhart** [comment]
Sorry, I misread your post as multiple different issues when you were talking about the graphical bug the whole time, and  took the mention of aiming with the bow as if it was the controller movement during aiming being slow and sluggish

**Comment by Kristijan1001** [comment]
Problems were solved, and a fix for time was pushed.

**Comment by monkersss** [comment]
I am having the exact same issue with my graphics would you mind showing me what you replaced?
