### ISSUE TITLE
zelda totk crashing on intel gpu

### ISSUE THREAD

**Issue by solaskk** [yuzu-emu/yuzu#10242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Acess 3582

### Description of Issue

if you try to open a main cutscene to progress through the game, It just freezes and crashes right after it

### Expected Behavior

just proceed normally like any other gpu

### Reproduction Steps

at the start of the game, and in the last part of the game start, when trying to enter the temple of time

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11457310/yuzu_log.txt)

### System Configuration

CPU: Intel core i5-1035G1
GPU/Driver: Intel UHD Graphics
RAM: 16 gb
OS: Windows 11

**Comment by Squall-Leonhart** [comment]
I'm sorry, but you don't even have an Iris Xe on that cpu, support for vulkan on igp's using the DCH driver is going to be poor.

**Comment by goldenx86** [comment]
Intel stopped support for those products on Windows.
Use Linux.

**Comment by beckbga** [comment]
> I'm sorry, but you don't even have an Iris Xe on that cpu, support for vulkan on igp's using the DCH driver is going to be poor.

The crash when trying to enter the temple of time also happens to Iris XE gpus, Would a fix be possible then?

**Comment by beckbga** [comment]
> Intel stopped support for those products on Windows. Use Linux.

> I'm sorry, but you don't even have an Iris Xe on that cpu, support for vulkan on igp's using the DCH driver is going to be poor.

The crashing in the temple of time happens in iris XE gpus too, then would a patch be possible?

**Comment by goldenx86** [comment]
Xe and Arc GPUs have driver issues. We reported them to Intel.

**Comment by fionnb** [comment]
> Intel stopped support for those products on Windows. Use Linux.

Crash _also_ happens on Linux with Intel GPU (yuzu 3588, TOTK 1.1)
So, not a Windows problem, I guess.

**Comment by amakuramio** [comment]
weird that botw is flawless as flawless can be, other games like smt too, even in totk, just diving for hours from sky so smooth (once shadows rendered) yet it crashes at certain locations with intel iris gpu

**Comment by Soldato79** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Affected Build(s)
> Early Acess 3582
> 
> ### Description of Issue
> if you try to open a main cutscene to progress through the game, It just freezes and crashes right after it
> 
> ### Expected Behavior
> just proceed normally like any other gpu
> 
> ### Reproduction Steps
> at the start of the game, and in the last part of the game start, when trying to enter the temple of time
> 
> ### Log File
> [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11457310/yuzu_log.txt)
> 
> ### System Configuration
> CPU: Intel core i5-1035G1 GPU/Driver: Intel UHD Graphics RAM: 16 gb OS: Windows 11

have you solved the problem? because i have the same problme but in the scene when link open the door after get 3 first powers

**Comment by slimshady392** [comment]
I have the same issue:

intel i7 12700
16gb memory
integrated gpu INTEL UHD Graphics 770

The game just freezes after the first scene ends.

![error zelda](https://github.com/yuzu-emu/yuzu/assets/66808761/ea0478d4-95ca-453f-a353-834f8b451c97)

**Comment by bulentpc** [comment]
Now playable on Ryujinx emulator - thanks to the producer

**Comment by Squall-Leonhart** [comment]
Please don't with the irrelevant commentary.

**Comment by slimshady392** [comment]
Hi everyone. I just downloaded EA3661 and no more crash in the first scene.

My specs:

i7 12700
integrated gpu intel uhd 770
16gb ram

**Comment by fionnb** [comment]
> Hi everyone. I just downloaded EA3661 and no more crash in the first scene.
> 
> My specs:
> 
> i7 12700 integrated gpu intel uhd 770 16gb ram

I  can confirm that. EA3661 on i7-1165G7, no more crash!
