### ISSUE TITLE
British English language for Europe region

### ISSUE THREAD

**Issue by Draaloff** [yuzu-emu/yuzu#10257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The addition of the British English language for the Europe region.

### Why would this feature be useful?

- The settings window displays: Warning: "American English" is not a valid language for region "Europe"
- It affects the date and temperature formats displayed in some games (notably Zelda BotW and TotK)
- Some games have translations for both British and American English

**Comment by cufish** [comment]
You just have to change region to EU and it'll work fine... it's literally right underneath the language setting.

**Comment by Draaloff** [comment]
> You just have to change region to EU and it'll work fine... it's literally right underneath the language setting.
> 
> edit: wait nvm you're setting American English on EU, just scroll down to British English mate... lol
Oops, I didn't see the scroll bar
