### ISSUE TITLE
[Linux] TotK crash with Vulkan Exception VK_ERROR_MEMORY_MAP_FAILED

### ISSUE THREAD

**Issue by YidaozhanYa** [yuzu-emu/yuzu#10258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline Latest (1429)

### Description of Issue

```
terminate called after throwing an instance of 'Vulkan::vk::Exception'
  what():  VK_ERROR_MEMORY_MAP_FAILED
zsh: IOT instruction (core dumped)  yuzu
```

### Expected Behavior

The game should work normally

### Reproduction Steps

Play _The Legend of Zelda: Tears of the Kingdom_

### Log File

```
[   3.848314] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateComputePipeline:706: 0xae60a09485fc53b3
[   3.848526] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateComputePipeline:706: 0xb755e1184a2dce2f
[   3.848722] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0x40b41c7ebf724a6a
[   3.849444] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0xf8f05a4d512da3d2
[   3.849496] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0x530868ee5c7f15b1
[   3.849622] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0x4d9b6b17f9f04ef4
[   3.849751] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0xc2895bd50e65c700

...

[   3.850863] Shader <Warning> shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp:CollectStorageBuffers:395: Storage buffer tracked without bias, index 6 offset 0
[   3.850882] Shader <Warning> shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp:CollectStorageBuffers:395: Storage buffer tracked without bias, index 6 offset 0
[   3.850886] Shader <Warning> shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp:CollectStorageBuffers:395: Storage buffer tracked without bias, index 6 offset 0

...

[  54.568582] HW.GPU <Info> ./video_core/buffer_cache/buffer_cache.h:operator():1686: Binding storage buffer for cbuf index 6, MemoryLayoutSize 0xD1E7000
[  54.568595] HW.GPU <Info> ./video_core/buffer_cache/buffer_cache.h:operator():1686: Binding storage buffer for cbuf index 6, MemoryLayoutSize 0xD277000
[  54.568609] HW.GPU <Info> ./video_core/buffer_cache/buffer_cache.h:operator():1686: Binding storage buffer for cbuf index 6, MemoryLayoutSize 0xD1E7000
[  54.568622] HW.GPU <Info> ./video_core/buffer_cache/buffer_cache.h:operator():1686: Binding storage buffer for cbuf index 6, MemoryLayoutSize 0xD1E7000
````

### System Configuration

CPU: Intel i5-10300H
GPU/Driver: NVIDIA GTX 1650 Ti with driver 530.41.03 (4GB of VRAM)
RAM: 16GB
OS: Arch Linux 6.3.2-1

**Comment by Doguinhoo** [comment]
Also have the same issue.

Build: Early Access 3588
CPU: Intel Core i5-12600K
GPU/Driver: NVIDIA GTX 1060 3GB, driver 530.41.03
RAM: 16GB
OS: Garuda Linux (based on Arch Linux)

**Comment by iFireFly47** [comment]
I have the same issue.
Early Access 3588.
CPU: Intel Core i5 8256U
GPU: NVIDIA MX110, driver 531.79
RAM: 16 GB RAM
OS: Windows 10.
Game runs at 26-30 fps and randomly crashes.

**Comment by Doguinhoo** [comment]
Observation: in my case, as least, it only happened after leaving de starting islands (after SPOILERS!!! opening the big door in the temple of time and getting through the cutscene)

**Comment by iFireFly47** [comment]
> Observation: in my case, as least, it only happened after leaving de starting islands (after SPOILERS!!! opening the big door in the temple of time and getting through the cutscene)

When I load the savedata, it runs for few seconds or 1-2 minutes max and then it crashes.

**Comment by Doguinhoo** [comment]
> > Observation: in my case, as least, it only happened after leaving de starting islands (after SPOILERS!!! opening the big door in the temple of time and getting through the cutscene)
> 
> When I load the savedata, it runs for few seconds or 1-2 minutes max and then it crashes.

I second this, upon loading a save it either crashes almost immediately, or runs pretty well until it inevitably crashes after a few minutes.
