### ISSUE TITLE
TOTK blackscreen on Intel Opengl

### ISSUE THREAD

**Issue by 2Tsk2** [yuzu-emu/yuzu#10259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early access 3578

### Description of Issue

when attempting to play the game on opengl, It doesnt display anything but sound and gameplay seems to be still happening in the background. 

https://github.com/yuzu-emu/yuzu/assets/96981837/89deb948-ac8d-4678-9a39-395275cb5c9a

### Expected Behavior

Its expected to output graphics.

### Reproduction Steps

Run the game on a system with an intel IGPU, use opengl and start the game. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11468702/yuzu_log.txt)

### System Configuration

CPU: i5 8365U
GPU/Driver: Intel UHD 620 | driver version 31.0.101.2121
RAM: 16gb
OS: windows 11

**Comment by goldenx86** [comment]
We can't fix Intel's Windows drivers, and the Gen9/9.5 series (HD500/600 series) is out of support on Windows now.
Use Linux, it's your only way of getting both Vulkan and OpenGL working.
