### ISSUE TITLE
A more intuitive yuzu-cmd?

### ISSUE THREAD

**Issue by ariaththesage** [yuzu-emu/yuzu#10251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I'm have trying the yuzu-cmd executable in Windows because i want to integrate Yuzu with a frontend, but after a few tests and researching i'm quite confused because it seems that the config i have set when i configured the emulator with the QT interface is ignored or something when launching it from yuzu-cmd.

After doing some researching, and as far as i understand, yuzu-cmd reads config from the sdl config and not from the QT one, but then i wonder how do i have to config the SDL side...

The first tests i ran started the emulator but with the game in english (and i have Spanish set tup in the QT side), but after telling it to pick the QT config (with the "--config" parameter), although the language is ok, the keys i mapped aren't here.

So i think yuzu-cmd should provide a input-file switch ("like -i"), for specifying a input config to load.

Or what would be even better... detect a key/button press and load the first input config that have this device assigned and that key mapped to something.

### Why would this feature be useful?

I think it would help to launching the emulator more intuitive when using the terminal or a graphical frontend, because now i don't know how to tell it what input config load, and the "-c" flag for the config file should specify if requires a game ini or the sdl one...

**Comment by german77** [comment]
-h/--help is a common argument to see the available options.  If overhead is not a problem I usually have less issues using yuzu.exe to boot games directly with -g argument, this way it will pick up the qt config and should work fine most of the time.
```
C:\Users\user\AppData\Local\yuzu\yuzu-windows-msvc>yuzu-cmd -h

C:\Users\user\AppData\Local\yuzu\yuzu-windows-msvc>Usage: yuzu-cmd [options] <filename>
-c, --config          Load the specified configuration file
-f, --fullscreen      Start in fullscreen mode
-g, --game            File path of the game to load
-h, --help            Display this help and exit
-m, --multiplayer=nick:password@address:port Nickname, password, address and port for multiplayer
-p, --program         Pass following string as arguments to executable
-u, --user            Select a specific user profile from 0 to 7
-v, --version         Output version information and exit
```

**Comment by ariaththesage** [comment]
Yes,  i knew about the -h option, although i didn't know that the QT version accepts the -g flag as the sdl one...

However, i think yuzu-cmd needs more flexibility with the options.

For example, It cloud allow specifyng config options to override the defsults ones, both with the emulador and with games, like specyfing a input config to use, or even a custom home folder...

**Comment by FearlessTobi** [comment]
yuzu-cmd is only meant as a minimal frontend to ensure that no qt-specific code is introduced into core.
Therefore it is not meant to be feature complete with normal yuzu-qt.
Please use the launch flags for yuzu-qt when running yuzu with other launchers.

Closing

**Comment by DocMAX** [comment]
How can we use -c config? Which config files? I would like to choose vulkan/opengl api via command line. (Like -g in ryujinx)

**Comment by Hexaae** [comment]
> How can we use -c config? Which config files? I would like to choose vulkan/opengl api via command line. (Like -g in ryujinx)

Should be one of the configs in %AppData%\yuzu\config\.... e.g. "sdl2-config.ini" or "qt-config.ini" (this last one should be the one generated when using yuzu.exe with the UI)
