### ISSUE TITLE
Graphic Glitch/Error

### ISSUE THREAD

**Issue by SakamotoGinshi** [yuzu-emu/yuzu#10250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline Build - b64a27db8

### Description of Issue

Graphical Glitches in ToTK

### Expected Behavior

![Screenshot (134)](https://github.com/yuzu-emu/yuzu/assets/93459628/3fa6ba73-8235-49ae-a3dd-bee97e2926fd)
![Screenshot (135)](https://github.com/yuzu-emu/yuzu/assets/93459628/aa4fdb0b-2372-4530-9174-0c957ae999ca)
![Screenshot (132)](https://github.com/yuzu-emu/yuzu/assets/93459628/c4eb78e1-93ba-4272-a08f-583d37529d10)

### Reproduction Steps

playing the game normally, using bow, loading screen and entering shrines

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11464469/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11464470/yuzu_log.txt.old.txt)

### System Configuration

CPU: Ryzen 5 5600g
GPU/Driver: RX 6500XT
RAM: 16gb
OS: Windows 10

**Comment by liamwhite** [comment]
Fixed in mainline 1429, please confirm

**Comment by SakamotoGinshi** [comment]
The loading screens are still scuffed. Sent from Mail for Windows From: liamwhiteSent: Friday, 12 May 2023 9:27 pmTo: yuzu-emu/yuzuCc: Gin; AuthorSubject: Re: [yuzu-emu/yuzu] Graphic Glitch/Error (Issue #10250) Fixed in mainline 1429, please confirm—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by liamwhite** [comment]
Disable "Decode ASTC textures asynchronously (Hack)" to fix the loading screens.

**Comment by SakamotoGinshi** [comment]
Thanks!
