### ISSUE TITLE
Error when running the video core when launching TOTK with vulkan

### ISSUE THREAD

**Issue by OldWorldOrdr** [yuzu-emu/yuzu#10264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1430

### Description of Issue

I get an error when trying to launch TOTK with vulkan, opengl works

### Expected Behavior

launches normally like with opengl

### Reproduction Steps

launch tears of the kingdom nsp

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11468946/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5 5600H
GPU/Driver: Nvidia GTX 1650 mobile 531.79
RAM: 16 GB
OS: Windows 11

**Comment by liamwhite** [comment]
Please run VkDiag and screenshot its output.
https://github.com/13xforever/vkdiag/releases

**Comment by OldWorldOrdr** [comment]
updating my AMD integrated GPU driver fixed the issue, not sure why I had to do that since Yuzu was setup to use my dedicated NVIDIA GPU

**Comment by goldenx86** [comment]
The display is connected to the iGPU.

**Comment by Squall-Leonhart** [comment]
and the old AMD driver had a vulkan layer that caused the device index to return 0 devices.
