### ISSUE TITLE
Zelda Totk instantly crashing after loading

### ISSUE THREAD

**Issue by AbdouLahyani** [yuzu-emu/yuzu#10269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1430 / Yuzu EA-3588

### Description of Issue

I disabled mods, main title works fine, when I load in, yuzu instantly crashes.

### Expected Behavior

Game doesn't crash

### Reproduction Steps

See above

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11469386/yuzu_log.txt)
Save file:
[0100F2C0115B6000.zip](https://github.com/yuzu-emu/yuzu/files/11469388/0100F2C0115B6000.zip)

### System Configuration

CPU: I7-7500u
GPU/Driver: Nvidia 920mx - 531.79
RAM: 20GB
OS: Windows 11

**Comment by Pergmen** [comment]
Evidence of piracy in log file

**Comment by 13r** [comment]
Delete the shader cache files and try again.

**Comment by AbdouLahyani** [comment]
@13r Same problem.

**Comment by FearlessTobi** [comment]
We do not support piracy here.
