### ISSUE TITLE
Graphics modes.

### ISSUE THREAD

**Issue by AshCatBoi** [yuzu-emu/yuzu#10263]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What feature are you suggesting?

You should add an option in the graphics section named "graphics level" or "graphics mode" which could go from potato to low to medium to high to extreme.

### Why would this feature be useful?

it would help people who have no idea what the settings mean, so they can use yuzu to it's fullest potential

**Comment by Squall-Leonhart** [comment]
Emulation is not a PC game, the closest you get is the gpu accuracy mode.

**Comment by AshCatBoi** [comment]
I think you misunderstood me

**Comment by Squall-Leonhart** [comment]
I think you misunderstand emulating a console graphical pipeline.

**Comment by AshCatBoi** [comment]
bro, the yuzu settings. like, this [profanity] here;
![image_2023-05-22_184342727](https://github.com/yuzu-emu/yuzu/assets/97080934/2b91eecc-0997-4e2b-a07f-a93261f7f0e7)
