### ISSUE TITLE
Vulkan not working when hybrid mode (enables igpu) is enabled.

### ISSUE THREAD

**Issue by MrMeisgood** [yuzu-emu/yuzu#10268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1430

### Description of Issue

Games won't launch when using vulkan with hybrid mode enabled, giving the error "yuzu has encountered an error while running the video core" 

When I turn off hybrid mode and restart the computer vulkan starts working. Opengl works no matter what

### Expected Behavior

Games launching

### Reproduction Steps

1. Have hybrid mode enabled 
2. Switch to vulkan by pressing button in bottom left (doing it in settings crashes yuzu)
3. Try launching a game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11469335/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7 4800H
GPU/Driver: NVIDIA GeForce RTX 2060 / 31.0.15.3179
IGPU/Driver: AMD Radeon(TM) Graphics / 27.20.11028.5001
RAM:  16 Gb
OS: Windows 11

It's a lenovo legion 5 15ARH05H

**Comment by Squall-Leonhart** [comment]
DDU the radeon driver off and install the latest, that version has a broken switchable layer that causes 0 devices to be returned to the api.

**Comment by MrMeisgood** [comment]
> DDU the radeon driver off and install the latest, that version has a broken switchable layer that causes 0 devices to be returned to the api.
Just to be sure, do I install the latest driver directly from AMD or from the manufacturer? Because I've got the latest one from the manufacturer already.

**Comment by Squall-Leonhart** [comment]
latest AMDs.

**Comment by MrMeisgood** [comment]
Worked like a charm, thank you so much for the help!
