### ISSUE TITLE
Tears of the Kingdom crashes when trying to enter Temple of Time on Intel iGPU

### ISSUE THREAD

**Issue by fmnm04** [yuzu-emu/yuzu#10272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Acess 3589

### Description of Issue

After completing all the 3 sanctuaries in the zone, trying to open the door of the temple of time results in an unavoidable crash
with every combination of settings. The game just shows a black screen with OpenGL so using it is not a possibility and using any other combination of settings results in the same ending.

### Expected Behavior

Game doesn't crash when trying to open the door

### Reproduction Steps

Try to open the door of the temple of time after completing the 3 sanctuaries

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11469807/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel Core i7 1165G7
GPU/Driver: Intel iRIS Xe
RAM: 8 Gb
OS: Windows 10

**Comment by smiglo5** [comment]
Could you please provide a save right before Temple of Time? I'll gladly test it on my setup.

**Comment by fmnm04** [comment]
https://mega.nz/folder/NMxwzZgB#teTm3j_ylkt0ReCFlWoVOA
The first save is right in front of the temple of time

**Comment by smiglo5** [comment]
I've entered it just fine, touched that yellow blob too, and skipped the cutscene just fine as well
on i7 10700 gtx 1070ti latest drivers and 16gb of ram.

**Comment by pacoa-kdbg** [comment]
Can you give it a try without mods ?

**Comment by fmnm04** [comment]
No luck, the same thing happens without the mod

**Comment by Squall-Leonhart** [comment]
This is an intel driver bug, like the last closed issue on it.
https://github.com/yuzu-emu/yuzu/issues/10242

**Comment by darkezh** [comment]
I have a problem when the first cutscene finish. You have any mod or something like that? Because I have the same gen of processor.

**Comment by Squall-Leonhart** [comment]
#10286 may fix this.

**Comment by fmnm04** [comment]
#10286 doesn't fix this. I tried to do the same in EA 3589 and the same thing happens
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11471995/yuzu_log.txt)

**Comment by TSV3000** [comment]
same thing here

**Comment by amakuramio** [comment]
same problem on intel iris g7 gpu

**Comment by TSV3000** [comment]
I think the issue is with the tear. I can bypass the door opening sequence by switching my graphic API to GLASM which is VERY buggy. The game crashes just as the save made after the gate opens loads

The tear is not there before this cinematic (can see throught wall by coliding my camera with a wall is this a yuzu related bug btw?)

**Comment by TSV3000** [comment]
By using GLASM without "accelerate ASTC texture decoding" and without all adv. graphics I was able to bypass this cinematic. However, logging back with vulkan or interacting with the tear makes me crash

**Comment by goldenx86** [comment]
Intel Windows drivers are broken, wait for Intel to fix them: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/159

**Comment by TSV3000** [comment]
seems that it can take a while...
