### ISSUE TITLE
TOTK Graphic flickers when aiming arrow/weapon

### ISSUE THREAD

**Issue by hyoonh** [yuzu-emu/yuzu#10270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3588

### Description of Issue

TOTK Graphic flickers when aiming arrow/weapon
Yuzu, Vulkan, 2x, FSR 80%, SMAA, Docked mode
![Honeycam 2023-05-13 21-17-57](https://github.com/yuzu-emu/yuzu/assets/133506446/6a0e9d49-ea20-4a23-9bdf-a15ef6e59fe7)

### Expected Behavior

Using "Visual Fixes" mod fixes this issue perfectly, but I thought this issue was fixed by Yuzu update. Following GIF included Visual Fixes mod
![Honeycam 2023-05-13 21-31-13](https://github.com/yuzu-emu/yuzu/assets/133506446/c8d61d0b-79e5-4c68-8239-92192c981fea)

### Reproduction Steps

Aim arrow/weapon (very frequent in the location above and undergrounds)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11469632/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11469633/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 5 5600 6-Core Processor
GPU/Driver: NVIDIA GeForce RTX 3060 Ti 8GB
RAM: 16GB
OS: Windows 10

**Comment by Squall-Leonhart** [comment]
sounds the same as #10241, a fix should be already included.

**Comment by gidoly** [comment]
fixed on lastest release
