### ISSUE TITLE
TOTK freeze and crash when the first scene happens (Intel GPU/Vulkan)

### ISSUE THREAD

**Issue by darkezh** [yuzu-emu/yuzu#10271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA3582 & Yuzu1431

### Description of Issue

I have a problem with that when I open the TOTK the first scene goes well until when they give you control where it freezes and crashes after a few minutes. I also notice how the screen starts flickering when I launch the game. It crashes at this moment: 
![image](https://github.com/yuzu-emu/yuzu/assets/98781069/93f7ca23-0e0f-4573-b399-c86d3283535c)

### Expected Behavior

no crashing and no screen flickering

### Reproduction Steps

I run the yuzu and then the game and everything loads well until the moment they give you the control that it freezes

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11469674/yuzu_log.txt)

### System Configuration

CPU: Intel i5-11400
GPU/Driver: Intel UHD 730
RAM: 16GB
OS: Windows 10

**Comment by fmnm04** [comment]
I had the same problem as you, I just applied a 0.5 downscale and everything worked fine.

**Comment by darkezh** [comment]
> I had the same problem as you, I just applied a 0.5 downscale and everything worked fine.

I test that with different settings but it doesn't work

**Comment by Squall-Leonhart** [comment]
same deal as https://github.com/yuzu-emu/yuzu/issues/10242

**Comment by darkezh** [comment]
> same deal as #10242

Does that mean I just have to wait?

**Comment by Whimfoome** [comment]
Having the exact same problem, on Windows I get to exactly this place and the game crashes. On Linux the game won't even start.

I tried to play on a friend save and I could play without problem on his save, but he was much ahead, I think something in the scene is triggering this issue.

CPU:  Intel(R) Core(TM) i5-1135G7
GPU: Intel(R) Iris(R) Xe Graphics
RAM: 16GB
OS: Windows 11 / Fedora

**Comment by TooFast0205** [comment]
> Having the exact same problem, on Windows I get to exactly this place and the game crashes. On Linux the game won't even start.
> 
> I tried to play on a friend save and I could play without problem on his save, but he was much ahead, I think something in the scene is triggering this issue.
> 
> CPU: Intel(R) Core(TM) i5-1135G7 GPU: Intel(R) Iris(R) Xe Graphics RAM: 16GB OS: Windows 11 / Fedora

Can u send the save file? I'm having the same issue

**Comment by goldenx86** [comment]
Intel Windows drivers are unstable, wait for Intel to fix them: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/159

**Comment by k0lius** [comment]
same issue,
12th Gen Intel(R) Core(TM) i5-1235U   1.30 GHz
Intel Iris Xe
16.0 GB

**Comment by JonathanJJohnson** [comment]
Same here, managed somehow (with luck i guess) to get through the corpse cutscene and saved right before that, but then, after Zelda asks you to procee, it crashes with "HW.Memory <Error> core\memory.cpp:operator ():679: Unmapped Write32 @ 0x00000000C1800010 = 0x0000000000000000", I just get a glimpse of the little loading icon on the bottom left.

i5-13600k
Arc A750
32GBDDR5 RAM

**Comment by k0lius** [comment]
I used a save file to skip the intro and it worked for me. Past into cutscene the game seems to run just fine for me

**Comment by Enocola427** [comment]
> I used a save file to skip the intro and it worked for me. Past into cutscene the game seems to run just fine for me

Can you please provide the save here. been trying for weeks to run it but all the save files are too advanced into the game to the point i dont understand anything...

**Comment by k0lius** [comment]
of course, here it is:
https://pixeldrain.com/u/p9ESBjWQ
It is right after all the intro cutscenes, at the start of the tutorial. If you need a different one just tell me.

I also updated to the latest yuzu 1443 and removed all pipeline cache. I'm using the following mods: DynamicFPS_totk, TOTKYuzuFix, CutsceneFix_totk, BlackscreenFIX from here: https://gbatemp.net/download/loz-tears-of-the-kingdom-fps-static-fps-and-visual-fixes-patch-collection.37996/
The fps is around 20-30, I'm 4 hours into the game and had no crashes/freezes
My specs are: 
12th Gen Intel(R) Core(TM) i5-1235U 1.30 GHz
Intel Iris Xe
16.0 GB DDR4

**Comment by Enocola427** [comment]
> of course, here it is: https://pixeldrain.com/u/p9ESBjWQ It is right after all the intro cutscenes, at the start of the tutorial. If you need a different one just tell me.
> 
> I also updated to the latest yuzu 1443 and removed all pipeline cache. I'm using the following mods: DynamicFPS_totk, TOTKYuzuFix, CutsceneFix_totk, BlackscreenFIX from here: https://gbatemp.net/download/loz-tears-of-the-kingdom-fps-static-fps-and-visual-fixes-patch-collection.37996/ The fps is around 20-30, I'm 4 hours into the game and had no crashes/freezes My specs are: 12th Gen Intel(R) Core(TM) i5-1235U 1.30 GHz Intel Iris Xe 16.0 GB DDR4

Thanks so much! Ivw been searching for this for quite a while! Though I wanna ask if u crashed at temple of time too. Is there a workaround for that or I should just wait for the driver fixes

**Comment by Haroldjesus00** [comment]
The same happens to me 😟

**Comment by samuderaa** [comment]
do you have some save files after temple of time? because i crashed right after that :'c same specs as you too.

**Comment by k0lius** [comment]
Hey. Share your save files with google drive and I’ll pass this for you

**Comment by samuderaa** [comment]
here's the link https://drive.google.com/drive/folders/1D1hfHfvQadxl0b5rcan60WRaZ-HIsTnc?usp=drive_link

**Comment by k0lius** [comment]
Sorry, I tried it but it crushes when entering the temple as well. I passed the shrines, not the temples yet. That's bad news! Hope it gets a solution soon.

**Comment by k0lius** [comment]
Try latest 31.0.101.4382 Intel GPU Driver and see if it helps. https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html 
FIXED ISSUES: • Certain applications using Vulkan* API may experience an application crash

**Comment by Enocola427** [comment]
> 

Still crashes at temple of time. Does it work for you?

**Comment by fabiancgc12** [comment]
> Try latest 31.0.101.4382 Intel GPU Driver and see if it helps. https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html FIXED ISSUES: • Certain applications using Vulkan* API may experience an application crash

did it work? i'm not sure about installing beta versions but i'm having issues with the wind temple

**Comment by harpz111** [comment]
> of course, here it is: https://pixeldrain.com/u/p9ESBjWQ It is right after all the intro cutscenes, at the start of the tutorial. If you need a different one just tell me.
> 
> I also updated to the latest yuzu 1443 and removed all pipeline cache. I'm using the following mods: DynamicFPS_totk, TOTKYuzuFix, CutsceneFix_totk, BlackscreenFIX from here: https://gbatemp.net/download/loz-tears-of-the-kingdom-fps-static-fps-and-visual-fixes-patch-collection.37996/ The fps is around 20-30, I'm 4 hours into the game and had no crashes/freezes My specs are: 12th Gen Intel(R) Core(TM) i5-1235U 1.30 GHz Intel Iris Xe 16.0 GB DDR4

How do I load this save file? There are four slot things :p

**Comment by Whimfoome** [comment]
> How do I load this save file? There are four slot things :p

Right click the game and select "Open Save Data Location". Then drag all the folders you downloaded into it.

**Comment by Whimfoome** [comment]
> Intel Windows drivers are unstable, wait for Intel to fix them: [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#159](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/159)

The issue on their page is closed, because it was fixed for Arc gpu's, but it's not fixed for Iris Xe.

**Comment by slimshady392** [comment]
Hi everyone. I just downloaded EA3661 and no more crash in the first scene.

My specs:

i7 12700
integrated gpu intel uhd 770
16gb ram

**Comment by Squall-Leonhart** [comment]
"Tentatively" Fixed by https://github.com/yuzu-emu/yuzu/pull/10699
