### ISSUE TITLE
TOTK: Vulkan crash after a minute of gameplay

### ISSUE THREAD

**Issue by BenjaminHalko** [yuzu-emu/yuzu#10281]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Mainline 1431

### Description of Issue

I start running around the great sky island and within a minute the game crashes.

https://github.com/yuzu-emu/yuzu/assets/73490201/081f6458-ac58-411f-bf96-2b00090f25d6

### Expected Behavior

Not crashing is the expected behavior.

### Reproduction Steps

Set the API to Vulkan, then load into the great sky island. Then start running around and wait for the game to crash. By the way, no mods have been applied.

![image](https://github.com/yuzu-emu/yuzu/assets/73490201/d20a7947-29db-4523-87d4-6881abad3e36)

![image](https://github.com/yuzu-emu/yuzu/assets/73490201/f9ad7ba6-0298-4838-a742-25444ae1f110)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11470469/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz | AVX2 | FMA
GPU/Driver: NVIDIA GeForce GTX 1050 | NVIDIA 472.12.0.0
RAM: 24 GB
OS: Windows 11 Build 22624

**Comment by liamwhite** [comment]
The GTX 1050 has 2GB of video memory. This is unlikely to be enough.

**Comment by BenjaminHalko** [comment]
Why does it only crash on Yuzu and not Ryujinx then?

**Comment by liamwhite** [comment]
yuzu is very aggressive about using device-local buffers but Ryujinx allows using host-memory buffers in many cases. I am debugging the crash with low memory usage as we speak.

**Comment by TheShotte** [comment]
Actually, I doubt it has anything to do with Sky Island. I keep getting CTD as well on both the EA and mainline builds after about 10-15 minutes of playing regardless of location. If I sent you my save I promise it would be the same. In my instance, the log is writing:
"[4312.485210] Render.Vulkan <Critical> video_core\vulkan_common\vulkan_device.cpp:ReportLoss:527: Device loss occurred!
[4312.506827] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read32 @ 0x0000008834530418
[4312.506832] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read32 @ 0x0000008834530400
..
"
But there is nothing wrong with my GPU (no black screen or anything).

**Comment by BenjaminHalko** [comment]
@TheShotte I am curious, what are your specs?

**Comment by TheShotte** [comment]
> 

i7 12700K
32 Gb DDR4 3200 Mhz RAM
AMD 6600XT GPU
Samsung 980 NVMe SSD

**Comment by Squall-Leonhart** [comment]
#10286 may resolve this.
