### ISSUE TITLE
Adding shader cache limit

### ISSUE THREAD

**Issue by FPGA-Computer** [yuzu-emu/yuzu#10299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Something like a Least Recently Used (LRU) policy would be very useful when program exits and purge the excess shaders.

e.g. a global use counter that gets incremented every time a pre-cached shader is used.  The used shader entry has its count updated.  When program exits, any shaders with count value less than (current count - shader limit) get purged.

### Why would this feature be useful?

Shader cache is not limited, so it can get to unmanageable size or require user frequent purges.  There is a point of diminishing return and resource usage on low end systems.  Also as cache size grows, it takes a very long time for program to exit and appears to hang for literally minutes.  I have seen 78000+ shaders on mine.

**Comment by Squall-Leonhart** [comment]
This is fundamentally a terrible idea.

**Comment by FPGA-Computer** [comment]
I do appreciate the difficulty in the code logic.  Without a limit, the user have either keep all the shaders or purge the entire cache.  There is no middle ground right now.

>windows configuration change
If you mean windows virtual memory paging (not internal code for Yuzu), that's not going to be make a difference for me.  It is a quality of life suggestion in the first place.  

![memory](https://github.com/yuzu-emu/yuzu/assets/8140495/aec28bda-4883-4f3b-9a39-6b5a2d373672)

**Comment by Squall-Leonhart** [comment]
>  If you mean windows virtual memory paging (not internal code for Yuzu), that's not going to be make a difference for me. It is a quality of life suggestion in the first place.

No, i mean Large Page Sizes.

https://devblogs.microsoft.com/oldnewthing/20210510-00/?p=105200
https://devblogs.microsoft.com/oldnewthing/20160614-00/?p=93665

[Windows Large Page Support other than 2MB?](https://stackoverflow.com/questions/35566176/windows-large-page-support-other-than-2mb)
