### ISSUE TITLE
Zelda: TotK - Bad Album Image Quality after using Camera Module

### ISSUE THREAD

**Issue by SDXC** [yuzu-emu/yuzu#10297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3589

### Description of Issue

The image quality of the pictures in the Album and Hyrule Compendium is really bad (image artifacts).
When taking the picture the preview looks nice and crisp but after saving the quality is really bad.

![PreviewGoodQuality](https://github.com/yuzu-emu/yuzu/assets/5290260/0199ae72-87ac-44c3-ba06-823b5dd11317)
![AlbumBadQuality](https://github.com/yuzu-emu/yuzu/assets/5290260/4f3e166e-687f-43ff-bded-ac7542cbbc2c)
![HyruleCompendiumBadQuality](https://github.com/yuzu-emu/yuzu/assets/5290260/316753ec-e2d7-412d-a579-2f216c85e2f7)

### Expected Behavior

The quality should look as good as the preview (it does so on the Switch). But even on the Switch I have the feeling the quality isn't the best possible as well (it might be compressed at 90-95% quality level). So with yuzu being an emulator it would be kinda nice to get that extra quality (99-100% quality level) if possible.

### Reproduction Steps

Simply take a picture with the camera module and check out the Album/Hyrule Compendium.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11472766/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 9 5900X
GPU/Driver: NVIDIA RTX 3080 (531.61)
RAM: 64 GB
OS: Win10 (22H2)

**Comment by liamwhite** [comment]
No, it is not possible to do that, because the game is using its own internal jpeg encoder. You would need a mod to get that to happen. I don't think this is a yuzu bug.

**Comment by SDXC** [comment]
Ah, I had hoped it would be passed to an encoder that yuzu implements.

**Comment by G-Spawn** [comment]
> No, it is not possible to do that, because the game is using its own internal jpeg encoder. You would need a mod to get that to happen. I don't think this is a yuzu bug.

Closing for now 🙏

**Comment by FernandoS27** [comment]
the images are downscaled for the game to read them and the game encodes them in jpg. That's why they look so bad in comparison to your normal resolution.

We cannot download them for the game scaled as the game does not expect them in a higher or lower resolution.

**Comment by D-CODE5** [comment]
Isn't there any mod so that the images are not so bad quality in the album?

**Comment by SDXC** [comment]
There is actually a mod but because it is a romFS mod it needs to be merged with other mods that change the same file which has a high probability as it is a central file that is often changed by other mods. To be on the safe side I won't post a link but you will find the mod when searching for it on Google. It's a reddit page by a user called ChucksFeedAndSeed.
