### ISSUE TITLE
Controller input sometimes drops in TOTK

### ISSUE THREAD

**Issue by sme272** [yuzu-emu/yuzu#10291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu 1431

### Description of Issue

While playing controller will sometimes drop out for 5-30 seconds then return while using an xbobx one controller connected with bluetooth

### Expected Behavior

controller input should remain constant

### Reproduction Steps

happens randomly while playing

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11471831/yuzu_log.txt)

### System Configuration

CPU: intel I3 10100F
GPU/Driver: Nvidia Gtx 1660 Super, driver version 531.79
RAM: 16GB 
OS: Windows 10 build 19044.2486

**Comment by sme272** [comment]
This is the correct log file:
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11471870/yuzu_log.txt.old.txt)

**Comment by BSoDGamingYT** [comment]
This sounds like an OS issue, not an emulator issue

**Comment by FearlessTobi** [comment]
I agree. I've got the same controller configuration and this has never happened to me ever.

**Comment by Squall-Leonhart** [comment]
This is a common issue with Xbox series controllers when using Bluetooth 4.x LE adapters, the LE spec is intended to reduce power usage but this comes at the expense of signal quality, range, and reliability.

Xbox controllers on an LE adapter will install as "Bluetooth LE XINPUT compatible input device"

The controllers are backwards compatible down to 2.1, where the SSP spec was introduced (2.0 adapters will ask for a pin, and are unusable)

If this is an Elite controller, issues involving the rumble support will occasionally cause the controller to "reset" on a Bluetooth adapter unless restricting the rumble duration period.
