### ISSUE TITLE
Zelda TOTK crashes when using vulkan on the third opening cutscene with the whole castle rising upwards scene and/or loading a save past it. 

### ISSUE THREAD

**Issue by tilrr** [yuzu-emu/yuzu#10309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3589 EA 3591

### Description of Issue

If you load into the open world be it by loading a save file or by playing past the prologue, the game crashes with vulkan, if you use opengl, the game does not crash. Even after the low graphics card vram memory fix, this issue is still occurring. There are also numerous other reports of people still having this issue on Reddit as well, past EA 3589. It doesn’t matter what settings you use such as ASTC off or on etc.. 

Before 3589, in the log file, it would crash on HW.Memory <Error> core/memory 

Now it seems to crash/halt on video_core\host1x\vic.cpp:Execute:96: Frame dimensions 1920x1080 don't match (I included in the log file the last part before it halts)

### Expected Behavior

Not crash

### Reproduction Steps

See above

### Log File

[ 119.605499] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0x442b27334f267e63
[ 119.606116] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0x0799b23f3c5d7bc2
[ 134.536859] Service.AM <Warning> core\hle\service\am\am.cpp:SetIdleTimeDetectionExtension:510: (STUBBED) called idle_time_detection_extension=1
[ 134.990236] Service.NVDRV <Info> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:OnOpen:71: NVDEC video stream started
[ 135.001982] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:Initialize:66: (STUBBED) called
[ 135.058894] Service.NVDRV <Info> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:OnOpen:71: NVDEC video stream started
[ 135.059340] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_nvdec_common.cpp:SetSubmitTimeout:178: (STUBBED) called
[ 135.174834] Service.NVDRV <Info> video_core\host1x\codecs\codec.cpp:SetTargetCodec:205: NVDEC video codec initialized to VP9
[ 135.259125] Service.NVDRV <Info> video_core\host1x\codecs\codec.cpp:CreateGpuAvDevice:143: Using d3d11va GPU decoder
[ 135.280850] Service.NVDRV <Info> video_core\host1x\codecs\codec.cpp:GetGpuFormat:53: Could not find compatible GPU AV format, falling back to CPU
[ 135.346708] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame dimensions 1920x1080 don't match surface dimensions 1920x1088
[ 135.364324] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame dimensions 1920x1080 don't match surface dimensions 1920x1088
[ 135.378458] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame dimensions 1920x1080 don't match surface dimensions 1920x1088
[ 135.391527] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame dimensions 1920x1080 don't match surface dimensions 1920x1088
[ 135.395101] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame dimensions 1920x1080 don't match surface dimensions 1920x1088

### System Configuration

CPU:i5 10600kf
GPU/Driver:RX 580 4GB/23.4.3
RAM:8GB DDR4 2666mhz
OS: Windows 11

**Comment by Squall-Leonhart** [comment]
Duplicate #10274
