### ISSUE TITLE
TLOZ Tears of the kingdom: fringing with 2X and above scaling in docked mode

### ISSUE THREAD

**Issue by andyblarblar** [yuzu-emu/yuzu#10304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1434

### Description of Issue

When running the game anywhere with scaling set to 2X (all other settings do not effect this), a single pixel wide transperent boarder is applied to all edges, leading to a horrible oversharpened look. This only takes place in docked mode for some reason. From other user reports elsewhere, I belive this is an issue with AMD on Linux, but this is just speculation for the moment.

Docked mode 2x:
![docked](https://github.com/yuzu-emu/yuzu/assets/22401925/4ac85c1e-0c96-4288-a491-19be8cc0a272)

Handheld 2x:
![handheld](https://github.com/yuzu-emu/yuzu/assets/22401925/f3477919-7c7a-41ca-b048-0179a8ca83b5)

Docked 1x:
![docked1x](https://github.com/yuzu-emu/yuzu/assets/22401925/f9a2391a-56d3-494e-a2e6-d2eadd8ca30f)

Handheld 1x:
![handheld1x](https://github.com/yuzu-emu/yuzu/assets/22401925/3b53243b-7369-4747-8684-871beae88b59)

### Expected Behavior

The image is free of fringing.

### Reproduction Steps

With scaling set to 2X, head to an area with complex geometry to better view the issue. Toggle between docked and handheld, and observe the sigificant difference.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11473719/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5 3600
GPU/Driver: Rx 5700xt mesa
RAM: 32gb 
OS: Ubuntu 22.0.4

**Comment by liamwhite** [comment]
Set anisotropic filtering to default.

**Comment by andyblarblar** [comment]
> Set anisotropic filtering to default.

This fixed it. Thanks for the crazy fast reply!
