### ISSUE TITLE
Allow unbinding of controls

### ISSUE THREAD

**Issue by Gerdathlete** [yuzu-emu/yuzu#10301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Currently there is no way to unbind a button once it has been bound, despite the default configurations including the unbound "[not set]" option:
![image](https://github.com/yuzu-emu/yuzu/assets/25123577/c4dcc3f1-0f2c-4775-8cbb-5201f28282f9)

Users should be able to press a button, such as escape, or a clickable on-screen button in order to unbind a given function.

### Why would this feature be useful?

Certain functions, especially the capture button, can be accidentally bound causing issues for users when the button is accidentally clicked in game. Personally, I have run into this issue and had to reset to default controls in order to unbind the capture button.

**Comment by jarredhiggs** [comment]
Right click the button

![image](https://github.com/yuzu-emu/yuzu/assets/9682198/5f61e7a7-d75f-4e37-8a21-d0df058dea23)

**Comment by Gerdathlete** [comment]
> Right click the button
> 
> ![image](https://user-images.githubusercontent.com/9682198/238213878-5f61e7a7-d75f-4e37-8a21-d0df058dea23.png)

Oh wow, I'm stupid, thanks.
