### ISSUE TITLE
Cannot open Configure in Trisquel 11 (Ubuntu-based 100% free distro)

### ISSUE THREAD

**Issue by davidhedlund** [yuzu-emu/yuzu#10329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1435

### Description of Issue

Menu bar "Emulation -> Configure..." status:
* Yuzu is closing: Trisquel 11 -- is based on Ubuntu 22.04, but is using MATE instead of GNOME.
* Works: Ubuntu MATE 22.04
* [Ubuntu 22.04 has not been evaluated because Yuzu mainline 1435 does not run in it, see https://github.com/yuzu-emu/yuzu/issues/10328]

The distros were upgraded and tested from VMs.

Unfortunately, the bug prevents me
* Unfortunately, the bug prevents me from changing the graphics API from Vulcan to OpenGL in Trisquel.
* Also, I cannot get log files (Configure -> General -> Debug) - https://yuzu-emu.org/help/reference/log-files/

Is there any way I can help with debugging?

### Expected Behavior

I expected Yuzu to run in Trisquel.

### Reproduction Steps

I reproduced the bugs with VMs from virt-manager.

### Log File
[Sorry, I forgot to add it]

### System Configuration

CPU: Intel i7 7700K kaby lake
GPU/Driver: HD Graphics 630
RAM: 32 GB
OS: Trisquel 11

**Comment by kevin2kevin2** [comment]
> Unfortunately, the bug prevents me from changing the graphics API from Vulcan to OpenGL in Trisquel.

At the bottom left of the window, you can switch the graphics API by clicking on the current one:
![Capture d’écran_2023-05-23_18-30-13](https://github.com/yuzu-emu/yuzu/assets/118930644/e0f3b79f-a0ad-4643-a20a-7c31ea1aa4a1)

**Comment by davidhedlund** [comment]
I can open Configure now in Yuzu mainline 1454! Did you do some magic @goldenx86 ?
