### ISSUE TITLE
Totk: visual glitches

### ISSUE THREAD

**Issue by iFireFly47** [yuzu-emu/yuzu#10323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3592

### Description of Issue

Graphics get a lot of visual glitches, after a while I play.
![Immagine 2023-05-15 201826](https://github.com/yuzu-emu/yuzu/assets/133534648/0b87e713-4394-489d-acaa-77172850bf1a)

### Expected Behavior

Visual glitches shouldn't happen.

### Reproduction Steps

It happens randomly while playing.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11480868/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz up to 3.90GHz
GPU/Driver: NVIDIA GeForce MX110, Driver version: 531.79
RAM: 16 GB
OS: Windows 11 64 bit

**Comment by Sincasios** [comment]
Rain and mist doesn't help. I entered to the village in front of the castle with rain and I got this: https://youtu.be/vXMOe9EHwjc
