### ISSUE TITLE
5.1ch Linear PCM output

### ISSUE THREAD

**Issue by Chrono82** [yuzu-emu/yuzu#10338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Requesting 5.1 surrond sound. Switch is Compatible with 5.1ch Linear PCM output.

### Why would this feature be useful?

Very important feature and it is included on Switch specs.

**Comment by Squall-Leonhart** [comment]
Already supported with Cubeb,

**Comment by Chrono82** [comment]
> Already supported with Cubeb,

Okay, ty for the info. Didnt know. Curious thou that auto mode dont work for me.
