### ISSUE TITLE
Yuzu Crashes on Loading

### ISSUE THREAD

**Issue by BenStringer3** [yuzu-emu/yuzu#10345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA3582 EA3593

### Description of Issue

Yuzu crashes when i start Totk using Vulkan. I do not see the same issue with opengl.

### Expected Behavior

yuzu does not crash

### Reproduction Steps

try to launch Totk using Vulkan 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11490895/yuzu_log.txt)
[yuzu_log_no_mods.txt](https://github.com/yuzu-emu/yuzu/files/11490941/yuzu_log_no_mods.txt)

### System Configuration

Steam Deck
CPU: Zen 2 4c/8t, 2.4-3.5GHz (up to 448 GFlops FP32)
GPU/Driver:8 RDNA 2 CUs, 1.0-1.6GHz
RAM: 16 GB LPDDR5 on-board RAM (5500 MT/s quad 32-bit channels)
OS: SteamOS

**Comment by german77** [comment]
Please disable all your mods first and try again.

**Comment by BenStringer3** [comment]
> Please disable all your mods first and try again.
@german77 
done. see updated description for yuzu_logs_no_mods.txt

**Comment by BenStringer3** [comment]
removing my vulkan pipeline cache seems to allow me to get to the loading screen.
