### ISSUE TITLE
[Feature Request] yuzu_cmd should have an option to pass input profile as param

### ISSUE THREAD

**Issue by Makavelic** [yuzu-emu/yuzu#10340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Similar to how you can pass in a user profile with -u it would be good to allow a user to specify an input profile. 

### Why would this feature be useful?

When I play on PC i use a series x controller but when I use moonlight via steamdeck, it uses an xbox 360 controller. Currently I have to manually change the input profile before loading up moonlight.

**Comment by FearlessTobi** [comment]
yuzu-cmd is only meant as a minimal frontend to ensure that no qt-specific code is introduced into core.
Therefore it is not meant to be feature complete with normal yuzu-qt and we have no plans to add input profiles to it.

Closing

**Comment by Makavelic** [comment]
@FearlessTobi is there any workaround or another request / bug I can log instead to make this possible? With more people using steamdeck this is a pretty useful thing to support.

**Comment by FearlessTobi** [comment]
As an end user, I would advise not to use yuzu_cmd at all.
It is missing lots of features from the normal qt ui and breaks quite often.
