### ISSUE TITLE
AMD 7900XT An Error Occured Initializing Video Core - VULKAN

### ISSUE THREAD

**Issue by Ameno-Sagiri** [yuzu-emu/yuzu#10358]
### Is there an existing issue for this?

- [X] I have searched the existing issues - Don't see anyone else having the issue with this GPU specifically

### Affected Build(s)

Mainline 1436 (2023-05-16)

### Description of Issue

When trying to launch anything under Vulkan API, I am instantly given this error.  If any more information is required let me know.

This is ultimately the error the realtime logger gave me upon attempting to launch.
```
[ 378.181156] Render.Vulkan <Error> video_core\vulkan_common\vulkan_instance.cpp:operator ():118: Layer VK_LAYER_KHRONOS_validation not available, removing it

[ 378.212238] Render.Vulkan <Error> video_core\renderer_vulkan\renderer_vulkan.cpp:CreateDevice:75: Invalid device index 1!

[ 378.218639] Render.Vulkan <Error> video_core\renderer_vulkan\renderer_vulkan.cpp:RendererVulkan:107: Vulkan initialization failed with error: VK_ERROR_INITIALIZATION_FAILED

[ 378.218671] HW.GPU <Error> video_core\video_core.cpp:CreateGPU:57: Failed to initialize GPU: Vulkan initialization error VK_ERROR_INITIALIZATION_FAILED

[ 378.218700] Core <Critical> core\core.cpp:Load:279: Failed to initialize system (Error 5)!
```

### Expected Behavior

This shouldn't happen - it should launch

### Reproduction Steps

Have a 7900XT and try to launch anything with Vulkan API.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11494322/yuzu_log.txt)

### System Configuration

CPU: AMD 5900X
GPU/Driver: AMD 7900XT - Driver version 23.4.3 (Newest available)
RAM: 32GB
OS: Windows 11 Pro Workstation

**Comment by Squall-Leonhart** [comment]
DDU and clean install the driver, it looks like your system may have had an older radeon in it at some point and installed an outdated vulkan loader that references a no longer present vulkan json file.

**Comment by Ameno-Sagiri** [comment]
> DDU and clean install the driver, it looks like your system may have had an older radeon in it at some point and installed an outdated vulkan loader that references a no longer present vulkan json file.

Just installed this copy of Windows last week, I actually did run DDU to clean whatever Windows installed by default and manually installed what I had gotten from AMD's website. At this point I'm not really sure what to do then, since I did just that the moment I booted into this copy of Windows for the first time.

**Comment by Ameno-Sagiri** [comment]
Ran DDU in safemode, did a clean install of drivers again. Same issue. Seems the issue is something else them.

**Comment by Moonlacer** [comment]
The same drivers work for many other people on your card, don't try to blame AMD on this as everyone else does, your case is different

**Comment by Ameno-Sagiri** [comment]
> The same drivers work for many other people on your card, don't try to blame AMD on this as everyone else does, your case is different

I am sorry you do not know what you are talking about. This is a clean install of Windows with a fresh install of AMD drivers.

**Comment by Squall-Leonhart** [comment]
Install the latest windows 11 22621 preview cumulative, there might be a solution in it since it references an issue where the systems high performance gpu isn't presented to applications correctly.

**Comment by Ameno-Sagiri** [comment]
> Install the latest windows 11 22621 preview cumulative, there might be a solution in it since it references an issue where the systems high performance gpu isn't presented to applications correctly.
> 
> There may also be something you installed as habit that has a broken VK layer, mirillis action or twitch studio for example?

I will attempt updating Windows to that preview build. As for something I installed out of habit, the only I can think of is K-Lite codec pack for a media player. Other than that, this is a mostly vanilla install aside from Discord, Steam, and FL Studio. I have also installed all vcredist packages available.

**Comment by goldenx86** [comment]
Run this and check for informed warnings and errors. You have something installed messing with Vulkan layers.

**Comment by goldenx86** [comment]
Completely clean, do this, make sure the 7900 is selected in Emulation > Configure > Graphics.

**Comment by Squall-Leonhart** [comment]
The virtual display adapters are actually the cause of the issue, these bind to and make the Microsoft Basic Display Adapter the default device, which has no vulkan support at the present time,

 you can use the selection as goldenx86 has mentioned or set the 7900XT as the preferred device in the advanced windows graphics menu.

![image](https://github.com/yuzu-emu/yuzu/assets/1098176/cf34d4e6-2ebe-4592-8a5b-0f82264aeee2)

![image](https://github.com/yuzu-emu/yuzu/assets/1098176/8341cff9-8c4a-426c-9ec8-70d0985a3cdc)

**Comment by Ameno-Sagiri** [comment]
> Completely clean, do this, make sure the 7900 is selected in Emulation > Configure > Graphics.

These are my current configured settings:
![Yuzu Configuration 1](https://github.com/yuzu-emu/yuzu/assets/5976053/264aab98-c42c-4960-b080-b5b239138123)
![Yuzu Configuration 2](https://github.com/yuzu-emu/yuzu/assets/5976053/0d32a324-f22f-4b97-b162-a45063abc2d6)


I want to mention I can now run games in Vulkan. I am not sure what I did. It wasn't working after restarting after a driver reinstall, but after typing here for awhile and running that Vulkan check tool, it's now working? I will touch on those virtual display adapters though because I was wondering about those being there.  Very odd.

**Comment by Squall-Leonhart** [comment]
Windows for Workstations installs these by default, as they are part of a newer feature that replaces the legacy RDP engine, and are mainly intended for headless configurations.

But i assume your Monitor is attached right to the GPU in this case.
