### ISSUE TITLE
Compilation Error on m1 Mac: Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Ushio-Clover** [yuzu-emu/yuzu#10359]
### Issue

I encountered an error when I followed the steps in the wiki to compile yuzu on my Mac.

## reproduction

I ran the command:
`cmake .. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DYUZU_USE_BUNDLED_VCPKG=ON -DYUZU_TESTS=OFF -DENABLE_WEB_SERVICE=OFF -DENABLE_LIBUSB=OFF`

Everything was fine until I run the command: **ninja**

I got:

`FAILED: bin/yuzu-cmd
: && /Library/Developer/CommandLineTools/usr/bin/c++ -O2 -g -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/config.cpp.o src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/emu_window/emu_window_sdl2.cpp.o src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/emu_window/emu_window_sdl2_gl.cpp.o src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/emu_window/emu_window_sdl2_null.cpp.o src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/emu_window/emu_window_sdl2_vk.cpp.o src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/yuzu.cpp.o -o bin/yuzu-cmd  src/common/libcommon.a  src/core/libcore.a  src/input_common/libinput_common.a  externals/inih/libinih.a  externals/glad/libglad.a  -Xlinker -framework -Xlinker Cocoa  externals/SDL/libSDL2.a  src/core/libcore.a  src/audio_core/libaudio_core.a  src/video_core/libvideo_core.a  src/core/libcore.a  src/audio_core/libaudio_core.a  src/video_core/libvideo_core.a  src/network/libnetwork.a  externals/enet/libenet.a  externals/mbedtls/library/libmbedtls.a  externals/mbedtls/library/libmbedx509.a  externals/mbedtls/library/libmbedcrypto.a  /opt/homebrew/Cellar/opus/1.3.1/lib/libopus.dylib  externals/cubeb/libcubeb.a  /opt/homebrew/Cellar/speexdsp/1.2.1/lib/libspeexdsp.dylib  -framework AudioUnit  -framework CoreAudio  -framework CoreServices  externals/glad/libglad.a  externals/dynarmic/src/dynarmic/libdynarmic.a  externals/dynarmic/externals/mcl/src/libmcl.a  src/shader_recompiler/libshader_recompiler.a  src/common/libcommon.a  vcpkg_installed/arm64-osx/lib/libboost_context.a  vcpkg_installed/arm64-osx/lib/liblz4.a  vcpkg_installed/arm64-osx/lib/libzstd.a  externals/libdemangle.a  vcpkg_installed/arm64-osx/lib/libfmt.a  /opt/homebrew/lib/libavcodec.dylib  /opt/homebrew/lib/libavdevice.dylib  /opt/homebrew/lib/libavfilter.dylib  /opt/homebrew/lib/libavformat.dylib  /opt/homebrew/lib/libavutil.dylib  /opt/homebrew/lib/libswresample.dylib  /opt/homebrew/lib/libswscale.dylib  externals/sirit/src/libsirit.a  externals/SDL/libSDL2.a  -lm  -liconv  -Wl,-framework,CoreVideo  -Wl,-framework,Cocoa  -Wl,-framework,IOKit  -Wl,-framework,ForceFeedback  -Wl,-framework,Carbon  -Wl,-framework,CoreAudio  -Wl,-framework,AudioToolbox  -Wl,-framework,AVFoundation  -Wl,-framework,Foundation  -Wl,-weak_framework,GameController  -Wl,-weak_framework,Metal  -Wl,-weak_framework,QuartzCore  -Wl,-weak_framework,CoreHaptics && :
Undefined symbols for architecture arm64:
  "_jump_fcontext", referenced from:
      Common::Fiber::Rewind() in libcommon.a(fiber.cpp.o)
      Common::Fiber::YieldTo(std::__1::weak_ptr<Common::Fiber>, Common::Fiber&) in libcommon.a(fiber.cpp.o)
  "_make_fcontext", referenced from:
      Common::Fiber::Fiber(std::__1::function<void ()>&&) in libcommon.a(fiber.cpp.o)
      Common::Fiber::Rewind() in libcommon.a(fiber.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1505/1603] Automatic MOC and UIC for target yuzu
AutoMoc: /Users/weizhengyan/yuzu/src/yuzu/util/url_request_interceptor.h:0: Note: No relevant classes found. No output generated.
ninja: build stopped: subcommand failed.`

**Complete error message**
[log.txt](https://github.com/yuzu-emu/yuzu/files/11500381/log.txt)

**OS** : macOS Ventura 13.4 22F63 arm64
**SOC** : Apple M1 Pro (10)
**Host** : MacBook Pro (16-inch, 2021)

**Comment by liamwhite** [comment]
Follow the instructions here: https://github.com/yuzu-emu/yuzu/wiki/Building-for-macOS
