### ISSUE TITLE
totk randomly crashes 

### ISSUE THREAD

**Issue by rookieplayi** [yuzu-emu/yuzu#10368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early acces 3594

### Description of Issue

totk randomly freezes sometimes it automatically drops the fps to 0    but the ram usage isnt even high even vram usage is still low
the fps isnt even that bad its around 20fps

### Expected Behavior

no videos

### Reproduction Steps

i have no idea how this issue works

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11506239/yuzu_log.txt.old.txt)

### System Configuration

CPU: intel celeron n5100
GPU/Driver: intel uhd graphics
RAM: 8gb ram dual channel
OS: windows 11 22h2 64bit

**Comment by goldenx86** [comment]
You're too under minimum requirements to run the game: https://yuzu-emu.org/help/quickstart/#hardware-requirements

**Comment by rookieplayi** [comment]
not really the game sometimes doesnt freeezes for hours if im lucky
