### ISSUE TITLE
disabled extendedDynamicState3ColorBlendEquation on radv

### ISSUE THREAD

**Issue by hurricane-dorian** [yuzu-emu/yuzu#10361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

all

### Description of Issue

da83afd mentions a radv bug report about it fwiw: https://gitlab.freedesktop.org/mesa/mesa/-/issues/8325
Somehow they supposedly tested it fine and marked it resolved a month ago. 
I just tested it myself with da83afd reverted and the issue is definitely not fixed.
Someone should probably reopen the issue with them.

### Expected Behavior

extendedDynamicState3ColorBlendEquation working on radv

### Reproduction Steps

  git revert da83afd 

### Log File

nothing of note

### System Configuration

CPU: ryzen 3600
GPU/Driver: rx5700 mesa-git
RAM: 32
OS: arch

**Comment by hurricane-dorian** [comment]
Other than a few git commands I really don't know anything about programming so I thought someone with a bit more expertise should take charge.

**Comment by FearlessTobi** [comment]
Yeah, I think this belongs into the radv repo.
