### ISSUE TITLE
Crash in the depths with 4gb vram gpu ( Zelda Totk)

### ISSUE THREAD

**Issue by Younescruz** [yuzu-emu/yuzu#10379]
### Issue

many users have this problem. Especially owners of AMD Rx cards with 4 gb of vram. The game crashes or doesn't even load saves at all if you are in the depths with Vulkan api. Please fix it.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
