### ISSUE TITLE
Problem with FXAA on VULKAN

### ISSUE THREAD

**Issue by YooPita** [yuzu-emu/yuzu#10373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1438

### Description of Issue

This is a very old problem, I've been facing it for many years now. This problem is not present at OpenGL. It looks like a stepped transition between colors. This is most noticeable in the blur or in dark places.

The effect reminds me of 8-bit colors. Perhaps there are some solutions that would help increase the bit depth at least up to 16?

![example2](https://github.com/yuzu-emu/yuzu/assets/34219009/2b2e0dd7-4dd1-46cf-8604-10f35611b49d)
![example1](https://github.com/yuzu-emu/yuzu/assets/34219009/30f2aa99-3493-4cbe-afc6-0f07fb21f0b5)

### Expected Behavior

In OpenGL, the colors are smooth, in the VULKAN they are stepped and there are definitely fewer of them.
![example3](https://github.com/yuzu-emu/yuzu/assets/34219009/96ff7a55-8aea-4e69-a91d-41677bf6fca2)
![example4](https://github.com/yuzu-emu/yuzu/assets/34219009/24da5a09-3932-4fec-aaee-cab6c1c10bd8)

### Reproduction Steps

Just launch any game with the selected VULKAN setting

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11510019/yuzu_log.txt)

### System Configuration

CPU: Core i7-12700F
GPU/Driver: GeForce RTX 4080
RAM: 32GB
OS: Windows 11

**Comment by liamwhite** [comment]
Use SMAA or no antialiasing instead of FXAA

**Comment by YooPita** [comment]
Yes, you are right, the problem turned out to be related to the FXAA. As soon as I switched to SMAA, the color problem was gone. I found a similar issue mentioned in another issue [#7095](https://github.com/yuzu-emu/yuzu/issues/7095), but this issue was not addressed by the FXAA.

**Comment by YooPita** [comment]
> Use SMAA or no antialiasing instead of FXAA

Yes, you are right, the problem turned out to be related to the FXAA. As soon as I switched to SMAA, the color problem was gone. I found a similar issue mentioned in another issue [#7095](https://github.com/yuzu-emu/yuzu/issues/7095), but this issue wasn't addressed by the FXAA.

**Comment by v1993** [comment]
@Kobi-Blade

> honestly SMAA is inferior since it is more sharp

This is usually considered *desirable* and SMAA was developed as an improvement over much simpler and older FXAA, although this is ultimately up to your taste.

> it also has same issue as MSAA, it doesn't cover transparent textures unlike FXAA

Now this is just straight wrong (usually). Both FXAA and SMAA operate on post-processed image (which is very different from what MSAA does), and while SMAA *can* use depth in its edge detection algorithm, this is not recommended and not done by Yuzu (which, as looking at source code of shaders reveals, uses color detection - the highest quality method).
