### ISSUE TITLE
Could I collaborate?

### ISSUE THREAD

**Issue by DyeffersonAz** [yuzu-emu/yuzu#1037]
I'd like to translate the docs and the website of yuzu to portuguese. Considering that there's public in Brazil and Portugal that don't speak english.

For that, I'll need the files.

**Comment by DyeffersonAz** [comment]
I'll  download it from a site here. I'll make a collaboration.

**Comment by Relsig** [comment]
https://github.com/yuzu-emu/yuzu-emu.github.io

The files should be in the repo. I'm not a Dev for yuzu but I doubt they would have a problem if you open a PR over there as long as you plan on maintaining the translations.

**Comment by DyeffersonAz** [comment]
Ok! I'll try it in my **spare** time!
