### ISSUE TITLE
Mouse Speed Improvement

### ISSUE THREAD

**Issue by Mitia514** [yuzu-emu/yuzu#10381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It seems to me that when using a regular mouse in this emulator, there is not enough mouse speed when moving the hand as fast as possible. Increasing the resolution of the mouse sensor does not help. I suggest fixing this, and not following the path of emulating joystick sticks.I think adding an on-off setting will suit everyone.while mouse control is sooo slow (like in jelly)

### Why would this feature be useful?

This will greatly improve the gameplay on PC for those who do not have a joystick. There are many people who have a joystick but they do not like the control of the camera and aim. These people love the mouse even though they have a joystick

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/10330.

**Comment by Mitia514** [comment]
Only compatible with 1.1.0 ,The ability to increase the "mouse panning" value to above 100%.Need to get it back like before
