### ISSUE TITLE
Grandia HD collection (v1.01.19)

### ISSUE THREAD

**Issue by psychokinesis9** [yuzu-emu/yuzu#10385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1439

### Description of Issue

The language selected on the root title screen is not applied to each game.
The game version is v1.01.19.
*The display language selection was implemented @ game version v1.01.19. It is not present in v1.0.

### Expected Behavior

The language selected on the first game selection screen will be taken over as the language of Grandia1 or Grandia2.

### Reproduction Steps

1. On the global title screen immediately after startup, set the language to French, German, or Japanese.
1. Start Grandia1
1. The selected language is not applied and all displays are in English

### Log File

None

### System Configuration

CPU: Intel Corei7-1255U / AMD Ryzen 5 3600
GPU/Driver: Intel Iris Xe /  RTX2060
RAM: 32GB
OS: Windows11

**Comment by Squall-Leonhart** [comment]
You're not using a merged XCI are you?

**Comment by psychokinesis9** [comment]
I'm using 0100E0600BBC8000.nsp + update.nsp.
Should I use another romset?
