### ISSUE TITLE
zelda totk cant start

### ISSUE THREAD

**Issue by midos152** [yuzu-emu/yuzu#10384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu zelda totk

### Description of Issue

When I start the game it crashes without showing anything on the screen and yuzu shuts down

The game: the legend of zelda tears of the kingdom

and use vulkan
Emulator: yuzu
I hope for a solution

### Expected Behavior

there is no image shows on the screen

### Reproduction Steps

there is no image shows on the screen

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11518657/yuzu_log.txt)

### System Configuration

CPU: Ryzen 3 3200g
GPU/Driver: Vega 8 used 2gb
RAM: 8 used(6)
OS: windows

**Comment by midos152** [comment]
> You didn't supply a log

what do u mean?

**Comment by midos152** [comment]
> For assistance with your issue, please accurately describe the problem and post a log file. The following guide shows how to get the log file: https://yuzu-emu.org/help/reference/log-files/

idid

**Comment by Squall-Leonhart** [comment]
Looks like an extremely old driver (AMD proprietary driver 2.0.250)

**Comment by german77** [comment]
Use latest mainline. You are using a version way before any totk fix was introduced, latest at the moment is 1439

**Comment by midos152** [comment]
> Use latest mainline. You are using a version way before any totk fix was introduced, latest at the moment is 1439

ok thanks i will try
