### ISSUE TITLE
Yuzu crashes on startup when USB Gamepad is plugged in

### ISSUE THREAD

**Issue by Crashkila101** [yuzu-emu/yuzu#10383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1439, EA 3599

### Description of Issue

If a USB gamepad is plugged in when launching Yuzu, the software immediately crashes. This appears to happen on every previous release of Yuzu. In particular, my Mayflash GameCube adapter appears to cause this, but other gamepads may have the same result. This issue appears to have been known for 4 months: https://www.reddit.com/r/yuzu/comments/xozd1x/comment/j3eg68w/?utm_source=share&utm_medium=web2x&context=3
Behaviour after launching Yuzu:
![image](https://github.com/yuzu-emu/yuzu/assets/2352083/30fcb7fa-f198-400c-8abb-575ea89b5127)

### Expected Behavior

Yuzu is expected to launch. 

### Reproduction Steps

Plug in a Mayflash Gamecube Adapter into your system and launch Yuzu.

### Log File

[   0.283554] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.283587] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.417195] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.457662] Frontend <Info> yuzu\main.cpp:GMainWindow:360: yuzu Version: yuzu Early Access 3599
[   0.457688] Frontend <Info> yuzu\main.cpp:LogRuntimes:239: MSVC Compiler: 1934 Runtime: 14.36.32532.0
[   0.457690] Frontend <Info> yuzu\main.cpp:LogRuntimes:248: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.457691] Frontend <Info> yuzu\main.cpp:GMainWindow:376: Host CPU: AMD Ryzen 7 2700 Eight-Core Processor           | AVX2 | FMA
[   0.457697] Frontend <Info> yuzu\main.cpp:GMainWindow:378: Host CPU Cores: 8
[   0.457698] Frontend <Info> yuzu\main.cpp:GMainWindow:381: Host CPU Threads: 16
[   0.458022] Frontend <Info> yuzu\main.cpp:GMainWindow:382: Host OS: Windows 10 Version 21H2 (Build 19044.2251)
[   0.458039] Frontend <Info> yuzu\main.cpp:GMainWindow:384: Host RAM: 15.93 GiB
[   0.458040] Frontend <Info> yuzu\main.cpp:GMainWindow:385: Host Swap: 4.75 GiB
[   0.458085] Frontend <Info> yuzu\main.cpp:GMainWindow:390: Host Timer Resolution: 0.4991 ms
[   0.458085] Frontend <Info> yuzu\main.cpp:GMainWindow:390: Host Timer Resolution: 0.4991 ms

### System Configuration

CPU: Ryzen 7 2700 @ 3.20 GHz
GPU/Driver: RTX 2080 Ti / 531.79
RAM: 16GB 3200 CL16 Patriot Viper 4 DDR4
OS: Windows 10 Pro

**Comment by Squall-Leonhart** [comment]
This is due to the controller having a faulty FFB library installed that was programmed incorrectly by the OEM that creates the adapters logic board.

You can read about the issue [here](https://forums.dolphin-emu.org/Thread-dolphin-dev-builds-past-5-0-3977-crash-on-startup-with-my-controller-plugged-in?page=2)

**Comment by german77** [comment]
Is the adapter in wii u mode?

**Comment by Squall-Leonhart** [comment]
> Is the adapter in wii u mode?

It won't matter, the crash is thrown due to a bit of code in EZFRD64.DLL being truncated to 32bits, causing a fast fail exception

**Comment by Crashkila101** [comment]
> This is due to the controller having a faulty FFB library installed that was programmed incorrectly by the OEM that creates the adapters logic board.
> 
> You can read about the issue [here](https://forums.dolphin-emu.org/Thread-dolphin-dev-builds-past-5-0-3977-crash-on-startup-with-my-controller-plugged-in?page=2)
