### ISSUE TITLE
Submodule path 'externals/cubeb' Compile fails 

### ISSUE THREAD

**Issue by killown** [yuzu-emu/yuzu#10390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

0

### Description of Issue

fatal: git upload-pack: not our ref 2d817de7c58b33a7c045edf873f3f9c98e4a2082
fatal: remote error: upload-pack: not our ref 2d817de7c58b33a7c045edf873f3f9c98e4a2082
fatal: Fetched in submodule path 'externals/cubeb', but it did not contain 2d817de7c58b33a7c045edf873f3f9c98e4a2082. Direct fetching of that commit failed.

### Expected Behavior

...

### Reproduction Steps

...

### Log File

...

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by Squall-Leonhart** [comment]
sounds like a vcpkg or nuget issue, rather than a bug.

Assistance might be sought better on the discord than here.

**Comment by killown** [comment]
still having the issue 
Submodule path 'externals/SDL': checked out 'f17058b562c8a1090c0c996b42982721ace90903'
Submodule path 'externals/Vulkan-Headers': checked out '63af1cf1ee906ba4dcd5a324bdd0201d4f4bfd12'
Submodule path 'externals/cpp-httplib': checked out '6d963fbe8d415399d65e94db7910bbd22fe3741c'
Submodule path 'externals/cpp-jwt': checked out 'e12ef06218596b52d9b5d6e1639484866a8e7067'
fatal: git upload-pack: not our ref 48689ae7a73caeb747953f9ed664dc71d2f918d8
fatal: remote error: upload-pack: not our ref 48689ae7a73caeb747953f9ed664dc71d2f918d8
fatal: Fetched in submodule path 'externals/cubeb', but it did not contain 48689ae7a73caeb747953f9ed664dc71d2f918d8. Direct fetching of that commit failed.

**Comment by FearlessTobi** [comment]
try `git submodule sync` first
