### ISSUE TITLE
Updating yuzu should not re-add the desktop shortcut

### ISSUE THREAD

**Issue by OldWorldOrdr** [yuzu-emu/yuzu#10395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

When yuzu updates itself it should not attempt to re add the desktop shortcut, or there should at least be an option to disable it.

### Why would this feature be useful?

I don't like having any desktop shortcuts and it's annoying to delete the shortcut every time yuzu updates.

**Comment by FearlessTobi** [comment]
Please open an issue here instead: https://github.com/j-selby/liftinstall/.
