### ISSUE TITLE
yuzu crashes when trying to open emulation settings

### ISSUE THREAD

**Issue by h4rmy** [yuzu-emu/yuzu#10408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All Mainline versions newer than 1422

### Description of Issue

Title says for itself all versions released after 1422 on mainline are crashing, whenever I try to open emulation settings.
video demonstration of the issue: https://youtu.be/6LjuqUzVLfQ

### Expected Behavior

Settings should open without crashing the app

### Reproduction Steps

Start yuzu, open emulation settings.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11529525/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5 3600g
GPU/Driver: RX6600 / 23.2.2
RAM: 16gb
OS: Windows 10 Pro

**Comment by Squall-Leonhart** [comment]
DDU off the radeon driver, then install 23.4.x

Your system hasn't got the vulkan client drivers registered correctly, or there is a issue with the driver itself.

**Comment by Squall-Leonhart** [comment]
@liamwhite @goldenx86  perhaps setting DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1 at runtime would be an idea?

**Comment by h4rmy** [comment]
Actually this wasnt really smart from me opening this issue, I updated amd video drivers and now vulcan started working. Before february this year i used only nvidia and heard from internet that some amd driver updates are breaking stuff and didnt bother updating :P
