### ISSUE TITLE
Steam Deck Memory Leak

### ISSUE THREAD

**Issue by Bcuttsy** [yuzu-emu/yuzu#10409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3602

### Description of Issue

The memory on the steam deck fills up extremely quickly while using any compression method and leads to harsh stutters.

Issue wasn't present in v3591 with the vram fix however the gloom is bugged.

### Expected Behavior

The VRAM shouldn't be filling as quickly as it does and maxes out 
![16847508051636713671360663092848](https://github.com/yuzu-emu/yuzu/assets/134279591/0a1ae3a5-e9d9-498b-b75d-48a75cda7688)

### Reproduction Steps

Just play the game on the deck and you'll see the memory leak.

### Log File

N/A

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

STEAM DECK

**Comment by scorpion81** [comment]
similar to #10407

**Comment by DenoG1997** [comment]
for me it was also so and i looked into the log files and saw that yuzu set the max vram to 6.63 Gb for some reason![image](https://github.com/yuzu-emu/yuzu/assets/74460597/7f09c897-d3ac-4dd6-a099-2e46fd54642a)

**Comment by FearlessTobi** [comment]
Closing as this is a duplicate and the issue template is not filled out correctly.
