### ISSUE TITLE
vulkan menu lag

### ISSUE THREAD

**Issue by Noaski5** [yuzu-emu/yuzu#10401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1440

### Description of Issue

so i play on vulkan and when i close any menu that fills the hoal screen like switching weapons runes and inventory it has a good 2-3 seconds delay but for some reason it does not happen when i use opengl but it makes the game lag to mutch and i dint seem to have this problem with ryujinx

### Expected Behavior

i want the menus to work as expected witch is not supposed to have a delay

### Reproduction Steps

i dont kniw how to reproduse it 

### Log File

i dont know how to get a log file on yuzu

### System Configuration

CPU:11th Gen intel(R) Core(TM) i5-11400H @ 2.70GHZ, 2688 Mhz, 6 Cores(s), 12 Logical Processor(s)
GPU/Driver:RTX 3050 laptop
RAM:16
OS:Microsoft windows 11 pro

**Comment by Noaski5** [comment]
fergot to mention that when i enable Decode ASTC textures asynchronously (Hack) it gets fixed but all the hud textures are mixed up oh and my problem looks a bit like #10274 but it was only about the weapon hud section

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by Squall-Leonhart** [comment]
> This is an issue tracker for developers and not a support forum.

This is a legit bug, its fixed in #10398  :)
