### ISSUE TITLE
TOTK stuck in black screen when booting in 3604 & 3605

### ISSUE THREAD

**Issue by ikahfie** [yuzu-emu/yuzu#10419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3604 and 3605

### Description of Issue

Since updating to EA 3604 and 3605, TOTK 1.1.0 stuck in black screen when booting in the game in both version with and without mod. Reverting back to 3601 makes the game boots normally. Log showing "Userspace PANIC!" and "emulated game broke execution".

Clearing cache, changing CPU accuracy, and changing graphic option has no effect.

![image](https://github.com/yuzu-emu/yuzu/assets/27878762/4d6e32d8-79f2-4c37-a55e-e69b20c7b531)

Here's my settings.

![image](https://github.com/yuzu-emu/yuzu/assets/27878762/b4d6c65d-6ece-44cb-9c82-6fca7c2c14f0)
![image](https://github.com/yuzu-emu/yuzu/assets/27878762/04e6a4de-1fdb-4e4b-b506-1127025512ff)
![image](https://github.com/yuzu-emu/yuzu/assets/27878762/a3ef6c43-27d6-43ab-8049-87be053fce58)
![image](https://github.com/yuzu-emu/yuzu/assets/27878762/316bf2cf-2ef3-4e81-b7da-60cb4b331462)

### Expected Behavior

Game boots normally to main menu.

### Reproduction Steps

Run the game in EA 3604 and 3605. 

### Log File

[yuzu_log - 3604.txt](https://github.com/yuzu-emu/yuzu/files/11540346/yuzu_log.-.3604.txt)
[yuzu_log - 3605.txt](https://github.com/yuzu-emu/yuzu/files/11540355/yuzu_log.-.3605.txt)

### System Configuration

CPU: i5 7600K
GPU/Driver: RX 6500 XT 4GB
RAM: 16GB
OS: Windows 10

**Comment by Squall-Leonhart** [comment]
Is it stuck, or are you just not waiting long enough?

**Comment by ikahfie** [comment]
Redumping the update and reinstalling fixes it thanks.

**Comment by DenoG1997** [comment]
i habe the same problem since 3605 but reinstalling doesent help any ideas?
