### ISSUE TITLE
Immediate crash when going near central hyrule abandoned mine in hyrule and tons of crashes in the depths

### ISSUE THREAD

**Issue by Shiro101010** [yuzu-emu/yuzu#10416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

3588 3605

### Description of Issue

i can explore the game with relatively low crashes but exploring the depths overall leads to crashes between 5 minutes to 10 seconds in the game and going within the proximity of the central mine causes an instant crash on openGL and Vulkan it is necessary to go there for autobuild and i dont know what to do ive gone to yuzu ryujinx and tried different builds and everything but nothing works the game feels unplayable and i dont know what to do when 1/3 of the game is locked from me

### Expected Behavior

https://clipchamp.com/watch/CdHJTb3zqcq

https://clipchamp.com/watch/tlgYs0b1ljd

### Reproduction Steps

in order to reproduce the issue you must just walk near the central hyrule abandoned mine on a system similar to mine

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11539695/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11539697/yuzu_log.txt.old.txt)

### System Configuration

CPU:AMD RYZEN 5600 with RADEON GRAPHICS
GPU/Driver:AMD RADEON RX 5500 4gb
RAM:16gb RAM
OS:Windows

**Comment by chiptunesoprano** [comment]
Have you tried disabling your mods? Mod issue would explain why you're having issues in both emulators.

**Comment by Shiro101010** [comment]
> Have you tried disabling your mods? Mod issue would explain why you're having issues in both emulators.

this seems to be working so far i will try it a bit more and see what happens i dont know why i didnt try this earlier

**Comment by chiptunesoprano** [comment]
> > Have you tried disabling your mods? Mod issue would explain why you're having issues in both emulators.
> 
> this seems to be working so far i will try it a bit more and see what happens i dont know why i didnt try this earlier

Make sure your mods are updated and match the game version you have. The yuzu discord has a GitHub pinned in the mod thread with the latest mod pack.

**Comment by FearlessTobi** [comment]
Closing as this seems to be a mod issue.
