### ISSUE TITLE
Fire Emblem: Three House audio delay issue

### ISSUE THREAD

**Issue by acerfox177** [yuzu-emu/yuzu#10412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 1440

### Description of Issue

No matter what I do, it seems like the game just won’t sync the audio correctly. It has a weird half second delay that is very distracting and I’m just wondering if there is anything that I’d be able to do to get it synced up just right. It’s literally the only problem I’m having with it since everything else is good.

### Expected Behavior

It is expected to sync audio correctly.

### Reproduction Steps

It happens in both cutscenes and regular gameplay.

### Log File

N/A

### System Configuration

CPU: AMD Ryzen 7 5800H
GPU/Driver: Rtx 3070/531.79
RAM: 16GB
OS: Windows 11

**Comment by FearlessTobi** [comment]
Please fill out the issue template completely.

**Comment by Squall-Leonhart** [comment]
I had assumed the DSP change had been backed out after having the EA tag removed?
