### ISSUE TITLE
Crash when launching TOTK

### ISSUE THREAD

**Issue by Playdric** [yuzu-emu/yuzu#10413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1440

### Description of Issue

Yesterday all was fine but this evening I tried launching TOTK just as yesterday (didn't catch if there was a Yuzu update or not)
And Yuzu crashes just after launching TOTK.
I tried other games and they don't crash. 
It doesn't crashes with OpenGL but performances are awful. 
Already tried 5 latest builds, same crash
Already disabled all mods and updates, still crash
There's an error with Vulkan, I tried running VkDiag, it catched one issue with Overwolf overlay, I tried disabling it and still it crashes
![image](https://github.com/yuzu-emu/yuzu/assets/25740839/358b3efe-9e62-421f-9192-2387e2b4ce51)

### Expected Behavior

Launching the game

### Reproduction Steps

* Launch Yuzu
* Launch TOTK
* Crash

### Log File

[yuzu_installer.log](https://github.com/yuzu-emu/yuzu/files/11533896/yuzu_installer.log)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11533908/yuzu_log.txt.old.txt)
I also have the crash dmp if needed

### System Configuration

CPU: AMD Ryzen 9 3900XT
GPU/Driver: 3080Ti
RAM: 64Go
OS: Win11

**Comment by goldenx86** [comment]
Uninstall Overwolf and reboot, stopping the layer doesn't seem to be enough.
Disable asynchronous ASTC decoding for TotK.
Set a bigger page file, at least 10GB.

That should do it.

**Comment by Playdric** [comment]
I did uninstall it and reboot, no change

With ASTC OFF and 10GB page file I got this log : 
[ASTC_off_yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11535904/ASTC_off_yuzu_log.txt.old.txt)

**Comment by Playdric** [comment]
I tried deleting all yuzu folders in `%APPDATA%` and `%LOCALAPPDATA%` and it fixed the issue. closing this, sorry for the non problem
