### ISSUE TITLE
The Legend of Zelda: Tears of the Kingdom - Performance Regression from mainline 1441 onwards

### ISSUE THREAD

**Issue by solarmystic** [yuzu-emu/yuzu#10425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1441 and newer

### Description of Issue

In game performance undergoes a noticeable regression after #10402 got merged to mainline from 1441 onwards.
Mainline 1440 is over 10% faster than mainline 1441. 

Mainline 1440 (before #10402)  - 78 Average FPS

![TOTK1440 1X GPU Normal (12700KF,2080TI)](https://github.com/yuzu-emu/yuzu/assets/4345150/996d71ef-46dc-4eb0-90bf-a3b94ecf9e06)

Mainline 1441 (after #10402) - 70 Average FPS

![TOTK1441 1X GPU Normal (12700KF,2080TI)](https://github.com/yuzu-emu/yuzu/assets/4345150/1914641b-1000-4db0-8673-70e7848e477f)

### Expected Behavior

Performance to remain the same as mainline 1440. 

### Reproduction Steps

EDIT: - Seems to be highly location specific, use my save data for easier reproduction. Scroll all the way to the bottom and select the In-Isa Shrine manual save.

Boot the game using mainline 1441, compare performance with 1440 and you will notice it. 

**Save files for reproduction**
[0100F2C0115B6000.zip](https://github.com/yuzu-emu/yuzu/files/11547767/0100F2C0115B6000.zip)

### Log File

Mainline 1441
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11547635/yuzu_log.txt)

Mainline 1440
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11547647/yuzu_log.txt)

### System Configuration

CPU: 12700KF
GPU/Driver: 2080TI on 527.56 drivers
RAM: 32 GB RAM
OS: Windows 10 21H2

**Comment by OldWorldOrdr** [comment]
update your gpu driver lol

**Comment by solarmystic** [comment]
Closing, since it seems to be highly specific and difficult to repro consistently.

**Comment by Squall-Leonhart** [comment]
The regression is due to additional barriers (resource synchronisation) between in draw calls so that there are no visual artifacts in the ultrahand graphic effect.
