### ISSUE TITLE
1.5x docked/handheld resolutions are switched (1x and 2x behaving normally)

### ISSUE THREAD

**Issue by pahanakun** [yuzu-emu/yuzu#10428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3606

### Description of Issue

While testing out resolutions in TotK as I'm still getting the gloom bug in Vulkan at 2x, I tried 1.5x. Then I noticed the docked/handheld resolutions are somehow swapped. Docked/handheld is working as expected for 1x and 2x in both OpenGL and Vulkan, but as soon as I tried 1.5x they were backwards.

### Expected Behavior

Docked should be 1620p and handheld should be 1080p, not the other way around
![docked-1 5-worse-than-handheld](https://github.com/yuzu-emu/yuzu/assets/45723080/10500149-c501-4273-b9c4-65ef1952b006)
![wonky-reversed-1 5x-handheld-docked](https://github.com/yuzu-emu/yuzu/assets/45723080/7ca6c88b-f6e8-4057-9986-97adc4f87653)

### Reproduction Steps

Set resolution to 1.5x, pressed OK. Clicked HANDHELD in bottom left (was running 2x at 1440p, wanted to try 1620p) and launched the game. Noticed the game got more pixelated instead of sharper, and was definitely running at 1080p (or the lower internal resolution, I have visual fixes disabled for better fps). Clicking DOCKED to switch it to HANDHELD made it sharp again. Opening the config window and doing it from Controls didn't make it behave normally

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11548990/yuzu_log.txt)

### System Configuration

CPU: Intel i7-8700k
GPU/Driver: Geforce 980/531.79 (latest as of posting)
RAM: DDR4-2666
OS: Windows 10 22H2 Build 19045.2965

**Comment by goldenx86** [comment]
If you don't use a mod to disable the integrated FSR of the game, this will happen. The FSR shader doesn't like odd resolution multipliers, so it will only render correctly at 1x, 2x, 4x, 8x.
