### ISSUE TITLE
Zelda TOTK, unmapped read after Colgera boss fight+cutscenes

### ISSUE THREAD

**Issue by TehPlayer14** [yuzu-emu/yuzu#10424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

YUZU EA 3596

### Description of Issue

Game crashes after couple of cutscenes, after defeating COLGERA, in wind temple

Got about 100mb log file filled with this: `[17666.437409] HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000008`

Using couple of mods to run the game as well

![obraz](https://github.com/yuzu-emu/yuzu/assets/7756773/6d581562-fa3c-4078-b5d5-6026dd6748e9)

### Expected Behavior

The game should continue as normal

### Reproduction Steps

Go into Temple of Wind, defeat Colgera, and collect heart container and talk to Tulin to start cutscenes after all the cutscenes game will crash

### Log File

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/11546645/yuzu_log.zip)
(Compress because its 50mb)

### System Configuration

CPU: Xeon e5-1620v3 @ 3.5GHz
GPU/Driver: GTX 980, driver: 527.56
RAM: 80GB @ 2133mhz quad channel 
OS: Windows 10 21h2

**Comment by liamwhite** [comment]
Does it happen if you don't use mods

**Comment by FernandoS27** [comment]
Mods can easily cause this issue.
