### ISSUE TITLE
[Linux] maintenance tool always creates desktop files

### ISSUE THREAD

**Issue by ToxicMushroom** [yuzu-emu/yuzu#10426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Acess 3606

### Description of Issue

The maintenance tool does not adhere to the selected option to not create desktop shortcuts and fails to install/update if obstructed.

background info:
The reason that I don't want desktop shortcuts is because I have my own to tell yuzu to use the xcb qt backend (otherwise it doesn't launch on sway).

My first fix was to make the desktop files immutable so yuzu would stop removing the program specific env variable I added.  -> yuzu didn't update anymore
I then saw that I could tell it to not create desktop shortcuts but this turns out to be broken for me at least.

### Expected Behavior

- Don't crash if you can't write/move a shortcut
- Don't try to create desktop files at all if it's not selected during the installer

### Reproduction Steps

1. check .local/share/applications assert there are no desktop entries, otherwise delete them
2. run the installer: ./liftinstall
3. uncheck create desktop shortcuts
4. install
5. check .local/share/applications
6. desktop entries

### Log File
[yuzu_installer.log](https://github.com/yuzu-emu/yuzu/files/11547992/yuzu_installer.log)

### System Configuration

CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz
GPU/driver: AMD ATI Radeon RX 6650 XT / amdgpu
Memory: 7029MiB / 31997MiB
OS: Arch Linux x86_64 
Kernel: 6.3.3-arch1-1
WM: sway

**Comment by FearlessTobi** [comment]
Thanks a lot for your detailed report.
However, please open your issue here instead: https://github.com/j-selby/liftinstall/.

**Comment by ToxicMushroom** [comment]
> Thanks a lot for your detailed report. However, please open your issue here instead: https://github.com/j-selby/liftinstall/.
> last activity 2 years ago
ye.., I'm not gonna bother then, thanks for the response tho
