### ISSUE TITLE
TOTK framerate all of a sudden goes to 0 fps when entering the water in the Ishodag Shrine

### ISSUE THREAD

**Issue by SonicdomXD** [yuzu-emu/yuzu#10430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3606

### Description of Issue

So I am doing the shrine as usual, using ultrahand and the paraglider, but when I reach the water, suddenly the game freezes.

### Expected Behavior

The game should not freeze.

### Reproduction Steps

Go to Ishodag Shrine
Do the first puzzle
Attempt to do the second puzzle

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11549166/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7 5800X 8 Core Processor
GPU/Driver: Nvidia RTX 3070 Driver Version 531.79
RAM: 32 GB RAM
OS: Windows 10

**Comment by german77** [comment]
Your log file is empty. Please upload a new one

**Comment by SonicdomXD** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11549652/yuzu_log.txt)
it should have text now
hopefully

**Comment by FearlessTobi** [comment]
Please try again without any mods.

**Comment by devmachine1** [comment]
why without mods the mods are what atleast stabilize the game a bit totk without 30/60 fps mods is really slow without the antistropic fix it looks really pixelated dont play without mods maybe use different mods or try to tweak your settings a bit

**Comment by SonicdomXD** [comment]
Tried it with mods on the latest version, seems to run as expected on my part.

**Comment by FearlessTobi** [comment]
Great.
