### ISSUE TITLE
Opengl missing hair on some characters and vulkan has flickering textures

### ISSUE THREAD

**Issue by acerfox177** [yuzu-emu/yuzu#10431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3606

### Description of Issue

This is on the steam deck and the fishing rod is invisible as well. Some characters have no hair and some have partial hair 

### Expected Behavior

They should probably have hair.

### Reproduction Steps

Just looking around the town will show multiple characters without hair.

### Log File

N/A

### System Configuration

Steam Deck

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by acerfox177** [comment]
> This is an issue tracker for developers and not a support forum.
> Please use our Discord for support requests.

My apologies, I closed by last one has well. Won’t happen again.
