### ISSUE TITLE
Every EA build since 3604 crashes with any game

### ISSUE THREAD

**Issue by bobbybudnick** [yuzu-emu/yuzu#10437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3604+

### Description of Issue

When launching any game the emulator window disappears after a few seconds.  The log file just stops after audio initialization.  My first thoughts are needing an updated graphics driver or Microsoft C++ redistributable.  I am hesitant to go changing these unless necessary so I will wait for some more feedback.

### Expected Behavior

Games should start and run.

### Reproduction Steps

Just launch any game.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11556918/yuzu_log.txt)

### System Configuration

CPU: i7 6700k
GPU/Driver: AMD RX 6800 with 23.2.2
RAM: 16 GB
OS: Windows 10

**Comment by devmachine1** [comment]
and the drivers are from a month ago that must be the issue

**Comment by devmachine1** [comment]
your drivers are from feb

**Comment by bobbybudnick** [comment]
I was thinking more about this and it is very unlikely that both Vulkan and OpenGL modes would crash due to old drivers.  February was not that long ago and I prefer to not have the performance of this card artifically limited because the 7 series cards are out.  It is probably the redistributable so I will try the one linked on the Yuzu website.  I have also uploaded the short log that is generated when this happens.

**Comment by devmachine1** [comment]
> I was thinking more about this and it is very unlikely that both Vulkan and OpenGL modes would crash due to old drivers. February was not that long ago and I prefer to not have the performance of this card artifically limited because the 7 series cards are out. It is probably the redistributable so I will try the one linked on the Yuzu website. I have also uploaded the short log that is generated when this happens.

you should download the newest ones like the amd website itself is recommending to do that

https://www.amd.com/en/support/graphics/amd-radeon-6000-series/amd-radeon-6800-series/amd-radeon-rx-6800

**Comment by devmachine1** [comment]
and also please try running a game once again in 3609 if it still doesnt work upload the biggest file in the log directory yuzu wont crash without writing any error message in the log file

**Comment by FearlessTobi** [comment]
Closing as user is unwilling to update their drivers.

**Comment by Squall-Leonhart** [comment]
update to 22h2, 
update your system bios (unpatched skylake microcode has a hyperthread corruption bug)
DDU and reinstall radeon driver (bad vulkan layer state can persist across driver updates unless DDU is used to nuke it)

**Comment by bobbybudnick** [comment]
Thank you Squall-Leonhart for taking the time to post an in depth answer.  I checked the Windows event log and the problem is within ucrtbase.dll which I have seen mentioned on here as a problem before.

Looking into it more it looks like someone said Windows allocates memory differently with the older versions and that is causing problems particularly when the system is under duress and has limited memory anyway.  Perhaps even with this 16 GB GPU and 2x resolution turned on.  Your clue about updating to Windows 11 latest version helped also.

I am running an old version of Windows also to complicate things even FURTHER.  This may be the problem for all three problems I am experiencing frankly.

-----

As for the system BIOS that is neat info but I just do not think that is the problem because I have been gaming continuously on this system since like 2015.

-----

As for the Radeon driver that is probably not the problem because the OpenGL files are not as fragile and OpenGL crashes immediately too.

-----

Thus I will save everyone a lot of time and headache and either install Linux again - I prefer the Devuan distribution - or simply expect instability with such an old version of Windows.  I do not expect you guys to make hacks for the old version of Windows and I am really suprised that Microsoft has made developers go through that.  I cannot imagine how difficult it must be to program something like this.  I will post an update if Linux was successful.  Thanks again.

**Comment by Squall-Leonhart** [comment]
> i cannot upgrade to 22h2, i use windows ltsc

Thats a self inflicted injury and nothing can be done to help you.

**Comment by frenesus** [comment]
so i discovered the problem for me

if i change timezone from automatic to default ( ea 3604 implement this), games runs normally now in the last ea build.

**Comment by bobbybudnick** [comment]
The timezone change to default fixes this particular problem for me also.  Good job finding that.

**Comment by devmachine1** [comment]
what does the timezone have to do with yuzu crashing lol?

**Comment by devmachine1** [comment]
why dont you guys have the katest windows version?
