### ISSUE TITLE
1442 main line opengl textures bug 

### ISSUE THREAD

**Issue by Yolo-BR** [yuzu-emu/yuzu#10442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1442

### Description of Issue

Today i opened yuzu and It automatically updated to the latest vesion, but when I opened Mario Odyssey the Switch controllers screen got black (Some textures are missing in the game too). I went back do 1441 and everything was fine. In vulkan everything looks normal. (Images from 1442 mainline - 24/05/2023)

![image](https://github.com/yuzu-emu/yuzu/assets/134548196/c14dee84-99ac-4b4d-b2d7-cdc59774995f)
 
![image](https://github.com/yuzu-emu/yuzu/assets/134548196/bdba324b-219a-48af-910e-c0271ef1b036)

![image](https://github.com/yuzu-emu/yuzu/assets/134548196/5ef0c335-1b43-4420-bb1a-978a7986e04d)

![image](https://github.com/yuzu-emu/yuzu/assets/134548196/d07f77f0-fa96-444f-a241-cc156d5fbcd7)

### Expected Behavior

This is how it was suposed to be (Images from 1441 mainline - 24/05/2023)

![image](https://github.com/yuzu-emu/yuzu/assets/134548196/08291dda-ad74-497a-b70c-711a582751ff)

![image](https://github.com/yuzu-emu/yuzu/assets/134548196/0fbda8c7-49a0-4a36-b241-81a478a92f38)

![image](https://github.com/yuzu-emu/yuzu/assets/134548196/664a82a9-3b34-4b2d-8266-4ddddca2a633)

![image](https://github.com/yuzu-emu/yuzu/assets/134548196/4b46e722-dc17-4418-a528-f1d436613d2c)

### Reproduction Steps

opened super mario odyssey using Opengl (GLSL and GLASM) in 1442.

### Log File

[1441 Log text.txt](https://github.com/yuzu-emu/yuzu/files/11558260/1441.Log.text.txt) 
[1442 log text.txt](https://github.com/yuzu-emu/yuzu/files/11558263/1442.log.text.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz | AVX
GPU/Driver:  NVIDIA GeForce GTX 650; PCIe; SSE2/474.30
RAM: 16gb DDR3 1333mhz
OS: Windows 10 21h2(Build 19044.2965)

**Comment by goldenx86** [comment]
We are working on removing OpenGL support entirely, this will cause problems for Kepler hardware and older since their Vulkan drivers are not enough for yuzu any more.

I recommend a hardware upgrade.

**Comment by Yolo-BR** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
>         
>       
>   
>       Create an issue with the title I have searched the existing issues. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> 
> ### Affected Build(s)
> Mainline 1442
> 
> ### Description of Issue
> Today i opened yuzu and It automatically updated to the latest vesion, but when I opened Mario Odyssey the Switch controllers screen got black (Some textures are missing in the game too). I went back do 1441 and everything was fine. In vulkan everything looks normal. (Images from 1442 mainline - 24/05/2023)
> 
> ![image](https://user-images.githubusercontent.com/134548196/240719397-c14dee84-99ac-4b4d-b2d7-cdc59774995f.png)
> 
> ![image](https://user-images.githubusercontent.com/134548196/240719842-bdba324b-219a-48af-910e-c0271ef1b036.png)
> 
> ![image](https://user-images.githubusercontent.com/134548196/240719983-5ef0c335-1b43-4420-bb1a-978a7986e04d.png)
> 
> ![image](https://user-images.githubusercontent.com/134548196/240720084-d07f77f0-fa96-444f-a241-cc156d5fbcd7.png)
> 
> ### Expected Behavior
> This is how it was suposed to be (Images from 1441 mainline - 24/05/2023)
> 
> ![image](https://user-images.githubusercontent.com/134548196/240719469-08291dda-ad74-497a-b70c-711a582751ff.png)
> 
> ![image](https://user-images.githubusercontent.com/134548196/240720658-0fbda8c7-49a0-4a36-b241-81a478a92f38.png)
> 
> ![image](https://user-images.githubusercontent.com/134548196/240720762-664a82a9-3b34-4b2d-8266-4ddddca2a633.png)
> 
> ![image](https://user-images.githubusercontent.com/134548196/240720806-4b46e722-dc17-4418-a528-f1d436613d2c.png)
> 
> ### Reproduction Steps
> opened super mario odyssey using Opengl (GLSL and GLASM) in 1442.
> 
> ### Log File
> [1441 Log text.txt](https://github.com/yuzu-emu/yuzu/files/11558260/1441.Log.text.txt) [1442 log text.txt](https://github.com/yuzu-emu/yuzu/files/11558263/1442.log.text.txt)
> 
> ### System Configuration
> CPU: Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz | AVX GPU/Driver: NVIDIA GeForce GTX 650; PCIe; SSE2/474.30 RAM: 16gb DDR3 1333mhz OS: Windows 10 21h2(Build 19044.2965)

Thanks for the fast reply, which version would you recomend for playing opengl in yuzu?

**Comment by Yolo-BR** [comment]
> We are working on removing OpenGL support entirely, this will cause problems for Kepler hardware and older since their Vulkan drivers are not enough for yuzu any more.
> 
> I recommend a hardware upgrade.

Thanks for the fast reply, which version would you recommend to play in opengl?

**Comment by liamwhite** [comment]
Ampere (Nvidia 30 series), or RDNA2 (RX 6000 series) or newer will have a long support period from both the hardware manufacturer and from most application.
