### ISSUE TITLE
Several TOTK failures with AMD on Vulkan

### ISSUE THREAD

**Issue by bobbybudnick** [yuzu-emu/yuzu#10441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All tested versions

### Description of Issue

I am having problems related to all of these issues with the Vulkan mode.  The game window can disappear, the lower part of the window can turn white, an infinite "please wait" will happen, or an infinite loading circle with game freeze will happen.

https://github.com/yuzu-emu/yuzu/issues/10360
https://github.com/yuzu-emu/yuzu/issues/10274
https://github.com/yuzu-emu/yuzu/issues/10346
https://github.com/yuzu-emu/yuzu/issues/10371
https://github.com/yuzu-emu/yuzu/issues/10239
https://github.com/yuzu-emu/yuzu/issues/10364

I have extensively tested all sub-graphics options short of dropping the resolution back to 1x which is not going to happen.  I have been running at 2x since the beginning with a large 4k screen.  I am also running on the 1.0 version of the game because why not throw another element into the mix.  My graphics driver is not the latest because I am paranoid also.  At first these failures happened every few hours but now they happen on average around every 30 minutes which is disrupting gameplay.  It may involve spawning in vehicles because as I have started to use vehicles more and more that is coinciding with more failures.  

So troubleshooting for me boils down to:
1. lowering resolution - blah
2. updating game code - blah
3. updating graphics drivers - blah
I would appreciate any help on this and can provide more information if needed.  For now I will just continue playing and dealing with the failures.  It helps to turn the disk shader cache off so you do not have to go through loading shaders after every crash.

### Expected Behavior

No crashing or unexpected game stoppages.

### Reproduction Steps

Play for between a few minutes and several hours.  It helps to teleport around and go in and out of shrines and spawn large vehicles to make the crashes worse.

### Log File

I will post one the next time it fails.

### System Configuration

CPU: i7 6700k
GPU/Driver: AMD RX 6800 with 23.2.2
RAM: 16 GB
OS: Windows 10

**Comment by devmachine1** [comment]
update the game its way more stable while emulating in 1.1.0+

**Comment by bobbybudnick** [comment]
I knew I forgot something.  I have been monitoring VRAM since it is has been hinted that VRAM is a problem.  This card has 16GB VRAM.  The game typically has been crashing at around 6GB VRAM usage.  So I am not buying the stuff about the driver causing VRAM fragmentation that is leading to the game being unable to allocate VRAM.  If there is 10 GB free "reported" then there should be at least a few "usable" GB.  Other games that use Vulkan would have terrible problems with this memory problem if that were the case.  I have been playing KSP 2 with this same configuration for months with nary a crash.  So in short I am not sure this is VRAM related.

I see that you are posting just as I am.
I will consider updating the game but one thing I worry about is did they "nerf" the graphics to gain better performance?  I believe you but it is weird that the 1.0 would be so unstable under emulation because I am sure it does not crash this much on the Switch.
3571 - 3608 EA versions and this mainline version were tested:
https://github.com/yuzu-emu/yuzu-mainline/commit/32adf371c557bc4335c313beeb11dac861ae925f

**Comment by bobbybudnick** [comment]
I do not want to update drivers unless necessary because these drivers on Windows are proprietary software and could have any kind of code in them including code that slows down older generation cards to make the new generation cards work better.  It has happened before.

**Comment by goldenx86** [comment]
We can't offer support on outdated drivers, move to Linux if this is a concern for you.

**Comment by bobbybudnick** [comment]
No one really knows how often it has happened.  Sometimes it happens out of spite for the user and sometimes it just happens naturally as the code is updated for the newer hardware architectures.

This issue is meant to be a catchall for all of those problems which I suspect are all the same problem.  Vulkan on AMD related and possibly related to VRAM.

I have been working fairly diligently troubleshooting and posting logs.  I was on a good train of thought right now but do not have a log because they were erased by other troubleshooting efforts.  I do plan to post one as I have noted.

I have not noticed the large RAM usage.  I see between 8 and 10 GB RAM usage.

As this very bug tracker notes this is not support but indeed a bug tracker and this issue is definitely a bug.  As you can see I am quite capable of "supporting myself" and this more of a log so that others can see what I am and am not doing to fix the problem.

I use Linux on many other computers on my network but never found success with it on my Wintendo.  The mandatory 25% performance loss is something I have never been able to handle.

**Comment by bobbybudnick** [comment]
So I just "moved to Linux" and the Yuzu experience is total garbage.  I am using the latest "Daedalus" variant of Devuan.  The latest Yuzu appimage launched fine once I did chmod 0755 on it.

I have only come to find out that the developers think Alsa is "old school"  I am using Alsa only and that is that.  I would not have installed Linux for Yuzu if I would have known that.  I think you will find that plenty of Linux users are going to be adamant about not using whatever new audio system they have come up with this week.  I know developers do not want to use Alsa because programming for it can be complicated but compared to making an emulator how hard could it be?  Strike 1.

BOTW does not start at all and TOTK hangs on a black screen with 20 FPS.  All relevant settings tried.  There is a Radeon something or other and an LLVMpipe device for Vulkan and neither work.  OpenGL has the same black screen with GLSL or SPIRV shaders.  I thought it was just loading slow but after a while the TV went completely blank and Linux become totally unresponsive.  Alt-SysRq-S + R required.  Typical Linux stuff when trying to run 3D.  Linux AMD firmware is installed and KDE accelerated window effects are working perfectly.  Strike 2.

Many new games are coming out soon for Windows only.  I am not going to wait for "World of Warcraft Guy" to hack Wine so I can try to run them.  All at a lower FPS than Windows.  No thanks.  Gaming is just too important for me to use Linux.  I cannot put up with the slowness and bugs Linux has when gaming.  I am hardcore about free software and am typing from a FreeBSD computer right now so it pains me to feel this way.  Strike 3.

I wanted this post to serve as a warning to other people that Linux is not the answer.  If the world had to rely on Linux 3D capabilities we would be screwed.  Steam Deck works well partially because it is chock full of Windows-Style malware like Pulseaudio and stuff like that.  The best answer is the latest version of Windows 11 and the Windows version of Yuzu with the correct settings and the latest drivers.  I do not see any further point of messing with Linux if audio is never going to work anyway.  I have Linux installed on another drive because I was not born yesterday and I knew it was going to suck.  I hate the idea of "dual booting" so I am probably going to eventually delete this Linux experiment or take the drive out of the computer and go back to good old Windows only like the Lord intended for playing games.  

In case anyone cares where I am going to go from here I am first going to try the alternative Switch emulator on my existing Windows 10 installation.  From there if that does not work I will be forced to upgrade to Windows 11 to try Yuzu again which compared to all I have tried already is not a big deal.

This was 12 hours wasted but really I have dodged a bullet of infinity hours dealing with Linux gaming problems.  After all, scientifically this was a "result" even if it was a negative one and for that and for improving my knowledge all around with this type of stuff I am at least thankful.  I promise to not inflict any more long winded posts on this already overloaded issue tracker.

**Comment by ParisMolver** [comment]
Interesting.

Have you tried steam OS if possible?

**Comment by bobbybudnick** [comment]
So I have just finished my Linux testing with Yuzu.  I am kind of set on using Devuan and not jumping around with distros.  To me, Steam OS has too much stuff like systemd and pulseaudio and who knows what else and I do not trust it at all.  I only use Devuan, FreeBSD or Windows to keep things simple these days.

Vulkan with normal/medium/low textures - all 3 settings eventually crash just like Windows does.  The Radeon driver is the only one that will work at all.  LLVMpipe crashes at start.  Slightly more stable getting a few more minutes between crashes than Windows.

OpenGL - too slow to test. 10 FPS.  No blue and green flashes like on Windows so if you want to play with .5 resolution on a high end card go for it.  As I said it is 2X resolution or the highway for me.  GLSL is the only option that works.  SPIRV crashes at start.

One cool thing is that the "low" textures look much better than they do on Windows.  The Linux performance tax is closer to 50% now instead of 25% so there is no hope here of having good performance.  I had heard so many great things like Valve has fixed all the problems for the Steam Deck and stuff and things are worse than when I tried it in 2017 on the gaming computer.  Hyper fail.

So I am back to trying the other Switch emulator on my Windows 10 installation and if that does not work installing the latest Windows 11 with the latest graphics driver.  I am really not convinced that Windows 11 will function though because this recent distribution of Linux should have sufficiently updated code to match whatever memory demands Yuzu has of it and it still is not working.  Maybe I have not done enough investigation to accuse Yuzu of being broken so please do tell me what I should do next in order to vindicate the good name of Yuzu here?

**Comment by bobbybudnick** [comment]
It looks like this patch may have fixed it:
https://github.com/yuzu-emu/yuzu/pull/10452

I am trying EA 3612 now since it came out 3 hours ago and the patch was integrated into the codebase 6 hours ago.  I am not familiar with this process though.  Should the patch already be contained inside EA 3612?  Like I said I will try it anyway.

**Comment by VIOLKABRE** [comment]
Having the same issue here, additionally with a similar AMD GPU. I have also tried with the newest EA release with no changes. 

I also have the same error listed about OpenGL being 10-8 frames slow, except my first attempt included models meshing all over the place and glitching. My current experience with OpenGL has nothing but the sky and visual effects visible with the same low framerate, but does not crash where Vulkan usually does.

My experience with Vulkan is almost perfect except for everything after the first Ganon cutscene, being unplayable and crashing if you try going there normally or loading a save that is placed after that cutscene. 

The end of my log ends with this, if that helps. I can provide my log file if it is required
`filesystem\fsp_srv.cpp:operator ():899: Assertion Failed!
`

**Comment by NightHammer1000** [comment]
Can confirm the same. EndavourOS, AMD 7900X3D and a AMD 7900XTX. Both on OpenGL and Vulkan.

After starting a new Game I can't even get to the first Ganon Cutscene without a "Unhandled SIGSEGV" crash.

**Comment by devmachine1** [comment]
if you guys have the newest drivers its a driver issue (maybe). Try out older driver versions because assertion failed means that vulkan isnt able to do something I think

**Comment by NightHammer1000** [comment]
Same Issue with OpenGL too tho.
