### ISSUE TITLE
Flickering Shadows/Lighting

### ISSUE THREAD

**Issue by slowchu** [yuzu-emu/yuzu#10446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3610

### Description of Issue

Flickering on shadows/lighting and cast shadows. Laterns, Torches, stationary, even sunlight cast on grass.

![image](https://github.com/yuzu-emu/yuzu/assets/134579951/5c938aaa-5009-4122-9f35-09d7f6e95b72)
![image1](https://github.com/yuzu-emu/yuzu/assets/134579951/e814679f-62b3-478c-9599-8285540e2cbb)
![image2](https://github.com/yuzu-emu/yuzu/assets/134579951/00dfd370-0b27-40ab-a493-0791b3ed32c6)

https://github.com/yuzu-emu/yuzu/assets/134579951/34bd8de7-b60b-4bae-bb77-460afcfb0bb1

### Expected Behavior

Well... no shimmering/flickering

### Reproduction Steps

![image3](https://github.com/yuzu-emu/yuzu/assets/134579951/ffeeecf2-423a-41e9-a6a7-a17ecb13904b)
Latest build running these mods, at 3x resolution (but it happens at 2x and 1x). Launch the game, look at cast lighting while moving the camera around and moving. 

### Log File

[yuzu_log (1).txt](https://github.com/yuzu-emu/yuzu/files/11561491/yuzu_log.1.txt)

### System Configuration

CPU: AMD Ryzen 5 5600X 6-Core Processor | AVX2 | FMA
GPU/Driver: Nvidia 3070ti / NVIDIA 531.79.0.0
RAM: 32GB DDR4 (4x8GB)
OS: Windows 10 Version 22H2 (Build 19045.2965)

**Comment by devmachine1** [comment]
its the 1024x shadows mod

**Comment by devmachine1** [comment]
and why dont u try the recommended setup on totk mod collections readme

**Comment by slowchu** [comment]
> its the 1024x shadows mod

Issue occurs with no mods loaded as well

**Comment by slowchu** [comment]
Fresh install, no issues. Must be a mod causing it. 1024x doesn't seem to be the culprit though... Discord is assisting.

**Comment by devmachine1** [comment]
> Fresh install, no issues. Must be a mod causing it. 1024x doesn't seem to be the culprit though... Discord is assisting.

nice

**Comment by James-Coyne** [comment]
Has any progress been made on identifying which mod causes this?
