### ISSUE TITLE
Zelda Breath of the Wild: Shadow bug with Vulcan backend

### ISSUE THREAD

**Issue by Ilya87** [yuzu-emu/yuzu#10448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1439 (build 19.05.2023)

### Description of Issue

https://github.com/yuzu-emu/yuzu/assets/1446573/03eb2ba4-702c-475f-9732-788913874b74

Shadows not render corectly, no bug with OpenGL, only with Vulcan, bug stays with or without antialiasing turning on. 

### Expected Behavior

Normal shadows.

### Reproduction Steps

Zelda Breath of the Wild 1.6.0.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11564943/yuzu_log.txt)

### System Configuration

CPU: AMD 5800H
GPU/Driver: AMD Radeon Graphics (iGPU) / 23.5.1
RAM: 16 Gb
OS: Windows 11

**Comment by liamwhite** [comment]
set anisotropic filtering to default.

**Comment by EgoBizarro** [comment]
I believe there's a mod by Wollnashorn that fixes using AF in the game.
