### ISSUE TITLE
Atelier Sophie 2 update failed to install

### ISSUE THREAD

**Issue by misaka00251** [yuzu-emu/yuzu#10445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline Build - 1443

### Description of Issue

I want to install "Atelier Sophie 2 The Alchemist of the Mysterious Dream",

My base game is: ` [0100661013EEE000][JPN][v0]`
My update is: `[0100661013EEE800][JPN][v524288]`

When installing the update, yuzu will crash. However all dlcs can be installed successfully.
It seems even the logs got cut out.

### Expected Behavior

The update was installed successfully.

### Reproduction Steps

1. Install the base game
2. Install the update

### Log File

[   2.614259] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   2.614278] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   2.728507] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   2.882071] Frontend <Info> yuzu\main.cpp:GMainWindow:360: yuzu Version: yuzu 1443
[   2.882099] Frontend <Info> yuzu\main.cpp:LogRuntimes:239: MSVC Compiler: 1934 Runtime: 14.34.31938.0
[   2.882101] Frontend <Info> yuzu\main.cpp:LogRuntimes:248: Qt Compile: 5.15.2 Runtime: 5.15.2
[   2.882102] Frontend <Info> yuzu\main.cpp:GMainWindow:376: Host CPU: AMD Ryzen 7 4800H with Radeon Graphics          | AVX2 | FMA
[   2.882109] Frontend <Info> yuzu\main.cpp:GMainWindow:378: Host CPU Cores: 8
[   2.882109] Frontend <Info> yuzu\main.cpp:GMainWindow:381: Host CPU Threads: 16
[   2.882282] Frontend <Info> yuzu\main.cpp:GMainWindow:382: Host OS: Windows 10 Version 21H2 (Build 19044.2965)
[   2.882308] Frontend <Info> yuzu\main.cpp:GMainWindow:384: Host RAM: 63.87 GiB
[   2.882309] Frontend <Info> yuzu\main.cpp:GMainWindow:385: Host Swap: 9.50 GiB
[   2.882346] Frontend <Info> yuzu\main.cpp:GMainWindow:390: Host Timer Resolution: 0.5000 ms
[   3.366162] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.24.0) applied successfully
[   3.369368] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.2.0) applied successfully
[   3.371996] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.14.0) applied successfully
[   3.374604] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.3.0) applied successfully
[   3.376041] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.3.0) applied successfully
[   3.377423] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.14.0) applied successfully
[   3.378896] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.2.0) applied successfully
[   3.380416] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.75.0) applied successfully
[   3.382078] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.2.0) applied successfully
[   3.386279] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   3.387959] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.9.0) applied successfully
[   3.390637] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.5.0) applied successfully
[   3.392111] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   3.394499] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.3.0) applied successfully
[   3.399819] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   3.401349] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.6.0) applied successfully
[   3.402981] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.4.0) applied successfully
[   3.404683] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.8.0) applied successfully
[   3.406224] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.27.0) applied successfully
[   3.407760] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.2.0) applied successfully
[   3.409267] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.2.0) applied successfully
[   3.410717] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.5.0) applied successfully
[   3.412229] Loader <Info> core\file_sys\patch_mana

### System Configuration

CPU: AMD Ryzen 7 4800H with Radeon Graphics
GPU/Driver: Nvidia RTX 2060
RAM: 64 GB
OS: Windows 10

**Comment by Squall-Leonhart** [comment]
sounds like a bad dump, can the game be run directly from the file?

**Comment by misaka00251** [comment]
The base game does boot up. You mean the update or the game is a bad dump? I tried different sources still no luck.

**Comment by misaka00251** [comment]
Indeed, it's a bad dump...
I download all the versions I can find on the internet, and the only version works is the one from my switch. Huh.
