### ISSUE TITLE
TOTK Vulkan Geometry Glitches ONLY In Depths (NVIDIA Kepler GPU)

### ISSUE THREAD

**Issue by purplesanz** [yuzu-emu/yuzu#10453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1444

### Description of Issue

Constant geometry and texture glitches occur on Vulkan API when traversing the Depths area. The issue is greatly reduced or even fully corrected when standing or gliding from a high altitude, then looking down.

Other than this and the [Issue 1320](https://github.com/yuzu-emu/yuzu/issues/10320), the game plays beautifully on a GTX 660 with BC1 ASTC Recompression. I'm aware this card doesn't meet the minimum Vulkan requirements as stated in the log file (708 & 775), but if there was any workaround for this, it would be amazing.

![0100f2c0115b6000_2023-05-25_09-33-52-020](https://github.com/yuzu-emu/yuzu/assets/24510635/0ea7b508-4440-4c88-8764-a5544c218d1f)
![0100f2c0115b6000_2023-05-25_09-33-52-520](https://github.com/yuzu-emu/yuzu/assets/24510635/20f987ee-abac-4a26-a507-dc748387cd36)

https://github.com/yuzu-emu/yuzu/assets/24510635/9bf9dc9c-5d7d-4ee9-ad7d-48f071e49b46

### Expected Behavior

Being able to traverse the Depths without any graphic glitches.

### Reproduction Steps

Simply enter the Depths using the Vulkan API with a GTX 660. It happens a little bit before touching the ground.

### Log File

[yuzu_log.txt.txt](https://github.com/yuzu-emu/yuzu/files/11567620/yuzu_log.txt.txt)

### System Configuration

CPU: Intel(R) Xeon(R) CPU E3-1240 V2 @ 3.40GHz
GPU/Driver: NVIDIA GTX 660 / 474.30
RAM: 8 GB DDR3
OS: Windows 10 LTSC 21H2

**Comment by Squall-Leonhart** [comment]
Kepler has no support for Vulkan 1.3, and lacks several extensions that Yuzu uses.

**Comment by goldenx86** [comment]
We're deprecating OpenGL and Kepler no longer receives Vulkan updates as Squall says.

**Comment by purplesanz** [comment]
Alright, guys, I have NO IDEA what you did, but this issue is completely fixed on Mainline 1448. Thank you! Thank you so much!!!

**Comment by Squall-Leonhart** [comment]
#10459  probably.

**Comment by Ayouuub0** [comment]
How are you running the game for longer than 10 minutes? As soon as I play for a while the game becomes a white screen and a graphical mess, I have to restart and 2/5 times I have to purge shader cache

**Comment by purplesanz** [comment]
> How are you running the game for longer than 10 minutes? As soon as I play for a while the game becomes a white screen and a graphical mess, I have to restart and 2/5 times I have to purge shader cache

Full PC specs, please?

**Comment by Ayouuub0** [comment]
> > How are you running the game for longer than 10 minutes? As soon as I play for a while the game becomes a white screen and a graphical mess, I have to restart and 2/5 times I have to purge shader cache
> 
> Full PC specs, please?

a 680 lol, so I assume you don't have this issue, thats strange

**Comment by Squall-Leonhart** [comment]
Vulkan 1.3 is an absolute requirement going forward, the 680 only has up to 1.2 (and most only 2GB vram) 
All development for it has ceased from nvidia, both on the linux side and windows side.
