### ISSUE TITLE
TOTK: Fast Travel not enabled.

### ISSUE THREAD

**Issue by Spamm00r** [yuzu-emu/yuzu#10451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1442

### Description of Issue

I made it to the underground level and took a picture of that statue. Now I'm supposed to fast travel back to the surface.

But the game is not offering me the option to fast travel to any location. 

Fats travel should have been activated once completing the first 3 shrines, which I did.

I think this is a yuzu issues, as fast travel should be available once you have progressed so far into the game.

### Expected Behavior

Fast Travel should be available in TOTK.

### Reproduction Steps

Try fast traveling in TOTK.

### Log File

[D5AD6AC71EF53E3E.txt](https://github.com/yuzu-emu/yuzu/files/11565980/D5AD6AC71EF53E3E.txt)

### System Configuration

CPU: 11th gen I7
GPU/Driver: RTX 350TI Mobile
RAM: 32GB
OS: WIn11

**Comment by devmachine1** [comment]
you broke your game, even changing to Early Access versions wont work here try to load the save you had before completing the 3rd shrine do it again if its still doesnt work you need to maybe dump the game again

**Comment by Norstyrm** [comment]
Could you provide a video showcasing the issue in detail as asked of you? And did you complete just three (3) shrines at the Great Sky Island? Because there are four (4) of them that have to be completed before the door even opens

**Comment by Spamm00r** [comment]
These are the shrines I completed in the sky, before i could open the doors.

![0100f2c0115b6000_2023-05-25_21-40-32-212](https://github.com/yuzu-emu/yuzu/assets/14886795/3ea8136d-8511-4729-b5ec-457a03cb52ed)

When I select one of the spots and press A button nothing pops up.

![0100f2c0115b6000_2023-05-25_21-40-57-451](https://github.com/yuzu-emu/yuzu/assets/14886795/ccd6202a-5f78-427a-949d-e83f87ea442d)

**Comment by bm01** [comment]
The thing is either it's an issue with the game itself in which case you should let Nintendo know (somehow), or with one of the cheats you used (the log file you joined isn't a yuzu log file but an aggregation of what appears to be mods), or with the emulator. So unless you know for sure it's an issue with the emulator, I don't think anything can be solved here.

I recommend loading an anterior save and trying to reproduce the issue without any mod loaded.

If you're looking for actual support and a way to fix your save, I think the answer is going to be the same and you should just load an anterior save file.

**Comment by Norstyrm** [comment]
I am curious if this is an issue that may happen on the base version of the game (no updates installed or applied), but figuring this out without a proper log won't really happen

**Comment by Norstyrm** [comment]
Assuming you've been using the cheat file you posted instead of the log it also gives you max hearts, and I would assume you have so. This bypasses the entire sequence where you need four hearts to open the great door.

You start with three hearts, and then you gather one Light of Blessing from each tutorial shrine. To open the door you need all four of them to trade for a heart container, but by using cheats you've managed to skip the very last shrine that unlocks fast travel, and completely softlocked your game.

All you can do now is restart the game from the beginning without any cheats at all.

**Comment by Squall-Leonhart** [comment]
FYI, you can use the online TOTK save editor to change your coordinates to where you need to be to access and unlock the final shrine, which is at the same area in the south that you woke up at.

**Comment by Spamm00r** [comment]
> Assuming you've been using the cheat file you posted instead of the log, it also gives you max hearts. This bypasses the entire sequence where you need to seek out the last shrine for the four hearts required to open the great door.
> 
> You start with three hearts, and then you gather one Light of Blessing from each tutorial shrine. To open the door you need all four of them to trade for a heart container, but by using cheats you've managed to skip the very last shrine that unlocks fast travel, and completely softlocked your game.
> 
> All you can do now is restart the game from the beginning without any cheats at all.

Yeah I guess that's it.
