### ISSUE TITLE
Distorted, buzzy audio in The Legend of Zelda: Tears of the Kingdom after pausing emulation

### ISSUE THREAD

**Issue by mewkia** [yuzu-emu/yuzu#10458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1444, Mainline 1445

### Description of Issue

The audio becomes distorted and buzzy. When I say buzzy think like how antenna television sounded when there was poor signal. It happens when I alt+tab out of the window with "Pause emulation when in background" enabled, or manually pause emulation. Upon returning to the resuming emulation, the audio will sound normal for about a second before returning to being distorted and buzzy. I was able to stop the problem by stopping the emulation, but that does not prevent it from happening again the next time I pause it. I was able to prevent it by disabling "Pause emulation when in background" and not manually pausing the emulation.

https://github.com/yuzu-emu/yuzu/assets/120602526/d32fc2ed-f2e2-465b-ae36-a35475527b44

### Expected Behavior

Play audio normally after unpausing the emulation.

### Reproduction Steps

Run The Legend of Zelda: Tears of the Kingdom. Pause the emulation. Unpause the emulation.

Save file: [0100F2C0115B6000.zip](https://github.com/yuzu-emu/yuzu/files/11571311/0100F2C0115B6000.zip)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11571334/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7 5800H with Radeon Graphics, 3291 Mhz, 8 Core(s), 16 Logical Processor(s)
GPU/Driver: NVIDIA GeForce RTX 3070 Laptop GPU
RAM: 16.0 GB
OS: Microsoft Windows 11 Home Version 10.0.22621 Build 22621

**Comment by bm01** [comment]
It behaves a little differently for me. Upon resuming emulation, any new sound effect appears to be delayed by roughly a second, but it catches up fairly quickly and at that point I start hearing crackling. This lasts about 20 seconds maybe, and eventually returns to normal.

To add to the description of the issue, "Mute audio in the background" but without "Pause emulation when in background" works fine.

**Comment by nebiont** [comment]
I'm pretty sure this issue is related to #10221 as I started experiencing it with EA3605

**Comment by bm01** [comment]
https://github.com/yuzu-emu/yuzu/issues/10293 's author reported crackling and popping audio in EA 3583 and later, and said https://github.com/yuzu-emu/yuzu/pull/10221 was the only PR touching audio since EA 3580 (he didn't test EA 3581 and EA 3582).

I reverted https://github.com/yuzu-emu/yuzu/pull/10221 on the Master branch, and I confirm it removed any audio issue upon resuming a paused emulation.

**Comment by liamwhite** [comment]
@Kelebek1

**Comment by Deleted-Account** [comment]
I encountered this issue with 1445+ and 3607~3617.

3617 has a leap in efficiency/performance in my gaming.
Hope this audio issue could be fixed soon

**Comment by zixiaomiao** [comment]
me too,EA3618,Run The Legend of Zelda: Tears of the Kingdom,this audio issue exist

**Comment by Deleted-Account** [comment]
> me too,EA3618,Run The Legend of Zelda: Tears of the Kingdom,this audio issue exist

this issue has been fixed on my device on 3618

**Comment by Dantasstic** [comment]
Yes, can confirm this audio issue doesn't exist for me now on EA 3621
