### ISSUE TITLE
TOTK doesn't show anything on screen on intel HD 520 (OpenGL)

### ISSUE THREAD

**Issue by IJNavi** [yuzu-emu/yuzu#10487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1450

### Description of Issue

When I launch TOTK it boot up to the title screen. I can hear the sounds of the menu when i use the control to navigate the options, but the screen is black.

### Expected Behavior

It should display the menu/title screen.

### Reproduction Steps

Click to start the game while using a intel HD 520 with OpenGL selected.

### Log File

There is no log since there is no crash.

### System Configuration

CPU: I5-6200U
GPU/Driver: Intel HD 520/ 31.0.101.2115
RAM: 8GB DDR3 Dual Channel
OS: Windows 10

**Comment by Moonlacer** [comment]
Use Linux, your GPU is unsupported by current Windows drivers, so many modern features will be lacking and/or broken

**Comment by goldenx86** [comment]
As Moonlacer says, driver support for this hardware ended and it's drivers are too old for running the latest Switch games. Plus Intel never had good OpenGL drivers.

Use Linux, it's your only remaining option.

**Comment by IJNavi** [comment]
This rig isan't used to play, I just wanted to provide data. But thanks for the quick response.
