### ISSUE TITLE
Assault at the Rite of Rebirth

### ISSUE THREAD

**Issue by rmsanti** [yuzu-emu/yuzu#10485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1442

### Description of Issue

All loadings super fast so far, except for this one. 
It takes a few minutes to fill the loading bar.
No freeze, no crash.
It's just stucked.

### Expected Behavior

After the dialog scene, It suppose to load the next battle but nothing happens.

### Reproduction Steps

1- Load my last save
![Screenshot_4](https://github.com/yuzu-emu/yuzu/assets/134889858/924c5f5a-2620-4650-acdf-e769aeae0d4b)

2 - Starting new chapter
![Screenshot_2](https://github.com/yuzu-emu/yuzu/assets/134889858/0da9ed0c-05cd-4503-bb38-f4d6b0b7ef00)

3 - Dialog scene
![Screenshot_3](https://github.com/yuzu-emu/yuzu/assets/134889858/acd9ab32-d7f8-4e95-9d81-7eb5eeeef5ba)

4 - Infinite load
![Screenshot_1](https://github.com/yuzu-emu/yuzu/assets/134889858/a1381653-bc27-47e4-a038-58bbcf7d8026)

### Log File

**Redacted by moderator due to piracy**

### System Configuration

CPU: Ryzen 5 4600G
GPU/Driver: RX 570 4GB / 23.4.1
RAM: 16GB 3000Hz
OS: Win10 Pro

**Comment by G-Spawn** [comment]
We don't support pirates here
