### ISSUE TITLE
Metroid Prime Remastered doesn't show anything on screen in game (igpu+OpenGL)

### ISSUE THREAD

**Issue by IJNavi** [yuzu-emu/yuzu#10488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1450

### Description of Issue

I can start the game, get to the menu, select what is needed and head to the game. A cutscene starts and nothing is displayed, the cutscene ends and it get to the game. I can hear the sounds of Samus walking and shooting when i use the control, but nothing is displayed on the screen.

### Expected Behavior

The inicial cutscene and the ingame screen should be displayed on screen.

### Reproduction Steps

Click to start the game with a intel hd 520 with OpenGL selected, select tjhe options to start a new game, let the cutscene run until it get in game.

### Log File

There is none, since there is no crash.

### System Configuration

CPU: i5-6200U
GPU/Driver: Intel HD 520/31.0.101.2115
RAM: 8 GB DDR4
OS: Windows 10

**Comment by Moonlacer** [comment]
Same response for me as in your other issue, your GPU will not work well with yuzu on Windows, try Linux

**Comment by gidoly** [comment]
Close as same reason with  previous issue
