### ISSUE TITLE
Syward Sword HD crash (IGPU+VULKAN)

### ISSUE THREAD

**Issue by IJNavi** [yuzu-emu/yuzu#10490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1450

### Description of Issue

Since the answear to the other ones was just use Linux because it wouldn't work and i'm only trying to provide data, I wanted to share this one. This game would be playable if a crash get fixed. Skyward Sword HD has no rendering issue and runs between 30fps to 45fps on this rig at stock resolution, handdeld with the vulkan renderer. But very quickly after the boot, in the save selection screen or ingame, the game crashes. It doesn't run for time enough to really play it, the crashes take less than 5 minutes to happen always. Sometimes it didn't took one minute to crash. This happen with and without the 30fps mod provided on the yuzu official page. The game runs perfectly fine in OpenGl, but with 20fps or less.

### Expected Behavior

To be playable, without constantly crashing.

### Reproduction Steps

Boot the game in a intel HD 520 igpu, wait on the save selection menu or enter in game and wait a bit.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11588105/yuzu_log.txt)

### System Configuration

CPU: i5-6200U
GPU/Driver: Intel HD 520/31.0.101.2115
RAM: 8 GB DDR3
OS: Windows 10

**Comment by goldenx86** [comment]
Yeah, you will hit the same limitations on any game. We can't fix outdated EoL drivers, Linux is the only way for this hardware.
