### ISSUE TITLE
[Vulkan error] Unable to open any game using Vulkan (even the configurations, if Vulkan selected in low bar)

### ISSUE THREAD

**Issue by pedroaquadros** [yuzu-emu/yuzu#10497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1451 / Early Access 3057

### Description of Issue

I used to play on Yuzu normally. Always using Vulkan with great performance. But on friday, I updated my Nvidia drivers and my Windows and my Yuzu never worked with Vulkan again. I tried to rollback my Nvidia drivers and Windows, but still the same.

I can't start any game and if I try to do it, the popup below appears:
![yuzu error](https://github.com/yuzu-emu/yuzu/assets/36547035/375c1e9c-e6c3-41cd-92c1-17e7b42a5cd4)

If I try the menu bar (Emulation -> Configure...) the Yuzu just closes. To do it, I need to select OpenGL via the low bar, then I can access Configure or open games.

I updated also my integrated driver and also set up Yuzu to forcedly use my RTX3050 besides my integrated graphics.

### Expected Behavior

I expected it to function normally, as it used to do.

### Reproduction Steps

Open Yuzu with Vulkan selected -> Try to open any game -> The popup attached appears
![yuzu error](https://github.com/yuzu-emu/yuzu/assets/36547035/c5d56031-4690-4abc-835d-ca2abd5c231d)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11593759/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7 5800H
GPU/Driver: NVIDIA GeForce RTX 3050 Laptop GPU / Radeon Graphics
RAM: 24 GB (3200 MHz)
OS: Windows 11

**Comment by goldenx86** [comment]
We won't offer support on piracy.
