### ISSUE TITLE
Random freezes in TOTK 

### ISSUE THREAD

**Issue by Ryhon0** [yuzu-emu/yuzu#10503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3621

### Description of Issue

The game randomly feezes for multiple seconds. While the game is frozen I can still interact with the emulator UI. After a couple freezes the game freezes indefinitely and sometimes it doesn't let me interact with the UI. Sometimes the UI says shaders are being compiled as it freezes but after the message disappears the game is still frozen. This issue occurs when using Vulkan and OpenGL. Clearing the shader cache, changing graphics settings, deleting the save and disabling mods doesn't do anything

### Expected Behavior

The game doesn't freeze

### Reproduction Steps

Play the game like normal

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11597500/yuzu_log.txt)

### System Configuration

SteamDeck, SteamOS 3.4.6

**Comment by Squall-Leonhart** [comment]
enable BC3 transcoding in advanced graphics.

@liamwhite  maybe this could autoengage for the deck?

**Comment by Ryhon0** [comment]
Doesn't seem to happen anymore on any texture compression anymore on EA 3625
