### ISSUE TITLE
Editing mod files while Yuzu is using them in the game, faster mod dev time

### ISSUE THREAD

**Issue by Waikuteru** [yuzu-emu/yuzu#10507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Hello! I'm a mod developer and I would like to ask if it's possible that you could change that we can edit mod files while yuzu is running and using these files in the game? It would be great for live-testing and -debugging!

If you don't want that to be default, I would also propose a "mod dev mode" that you can toggle. :)

### Why would this feature be useful?

For mod developers to develop mods faster and more efficiently.

Here is an example:
I test a mod, and have let's say 3 things to test.

I go to the first location, I see a bug, I then wanna fix it, but can't.
Then I go to the next bug location. 

_**With the fix, I could fix it on the fly and not after I tested the third and final bug and try to keep all the fixes in the head for when I closed yuzu.**_

**Comment by bylaws** [comment]
For romfs mods, a game-side solution is required using something like https://github.com/skyline-dev/skyline is required due to how the switch impls FS accesses. The game accesses could then be redirected to the SD card and edited live in yuzu, Móði in the reswitched server was investigating something similar iirc.

**Comment by liamwhite** [comment]
The filesystem APIs used by games for assets are based around RomFS. RomFS is a block storage system, wherein the entire file metadata table and the files themselves are stored as a single binary blob, parsed by the game SDK itself (OpenDataStorageByCurrentProcess returns an IStorage, which is just a raw block device interface). What's visible to the emulator is simply that blob as a file. All of the state relating to asset access is therefore not part of the emulator. The only thing we can do is build a custom RomFS the first time the game asks for it.

My general opinion is that this is simply not possible without patching the game to redirect filesystem accesses. yuzu allows you to access the SD card through FS services, but I'm not sure what's possible through the game SDK, so you might have to insert code from libnx to perform this.

**Comment by Waikuteru** [comment]
@bylaws I don't mean editing files live so the changes are seen in-game live as I change the files. I only mean that it would be cool if you can save the file while yuzu is using it. It doesn't have to be live edited in the game (that would be amazing however). It's about the fact that when I test my changes in the game and I find a bug, I used to fix it immediately, save the file, pack it back to the game's format - this way, I don't have to keep multiple fixes in mind for when after yuzu shut down so I can finally save the file. Do you see what I mean?

**Comment by liamwhite** [comment]
yuzu holds files in RomFS mods open as an optimization, to enable quick access to them without consume extra memory. What you described actually will work fine on non-Windows operating systems as they generally don't lock open files.

**Comment by Waikuteru** [comment]
@liamwhite Ok, thanks for the clarification. So it seems working this around is not possible on Windows.
