### ISSUE TITLE
Outdated SDL2 Library causes Switch Pro Controller Stutters on Windows

### ISSUE THREAD

**Issue by MyrTheMoth** [yuzu-emu/yuzu#10502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1444 to 1451

### Description of Issue

Greetings, I found an issue that I discussed on the support discord and it seems to be related to the SDL version present in current nightly builds for Yuzu, causing stutters on first party and third party Nintendo Switch Pro Controllers, the following ocurred:

When using these controllers on Yuzu, every 1-2 seconds, the gyro freezes, and 1-2 seconds after it does, all input freezes for a second or so, then controller works normally, I'm not running any games, the issue happens in controller config and debug, happens in-game as well, Yuzu's current SDL2.dll is version 2.0.18, the current version of SDL2 from official source is 2.26.5 over at https://github.com/libsdl-org/SDL/releases and some updates along the changelog roadmap mention switch controller fixes.

After replacing the SDL2.dll in Yuzu's binary folder with the latest SDL2.dll from libsdl-org, the issues disappeared completely.

Things I've tried before changing SDL2.dll:

- Tried two different bluetooth adapters (TP-Link and ASUS, Bluetooth 4.0)
- UPDATE: Tried a new 5.0 TP-Link Dongle, same deal
- Reinstalled bluetooth drivers
- Removed as much interference from my room as possible
- Bluetooth dongles were on USB 2.0 ports to avoid USB 3.0 interference that happens with some dongles
- Tried 2 different original Switch Pro controllers and an 8bitdo Ultimate in Switch mode
- Still happens after restarts
- Tried with and without direct pro controller drivers
- Tried disabling Vibration

Other observations:

- Doesn't happen in Citra
- Doesn't happen in Dolphin
- Doesn't happen in Steam (I always have Steam Input disabled, I enabled it only to test if it is only Yuzu that is suffering from this issue)
- DualShock 4 Controller over Bluetooth with SDL Gyro doesn't suffer from this issue, it's only Switch Pro Controllers, haven't tested Joycons
- XInput Controllers (No Gyro) on Bluetooth or Wired aren't affected by the issue

Tested Nightlies 1444 to 1451, same behavior

Additional observation, Citra and Dolphin don't have SDL2.dll on their binary folders so I couldn't find which version they were running, but however they are handling SDL, could be tied to their version of Qt, they both seem to have moved to Qt6 while Yuzu is in Qt5, I'm not aware of how these dependencies work, but I assume much newer versions of SDL are somehow bundled in Qt6.

Here's a video of the issue on Yuzu's bundled 2.0.18 SDL2.dll:

https://github.com/yuzu-emu/yuzu/assets/1090506/abea19a3-3e47-4c8d-9acf-3751eea1503b

Here's a video of it working perfectly after replacing it with the latest version from official SDL source:

https://github.com/yuzu-emu/yuzu/assets/1090506/863c8255-4890-4f6d-96c1-ef3c8279bb85

### Expected Behavior

Controller shouldn't freeze all input every few seconds

### Reproduction Steps

Pair any Switch Pro Controller over Bluetooth on Windows, Setup as a Yuzu Controller with any Yuzu Nightly whose SDL2.dll in %AppData%/Local/Yuzu is version 2.0.18, set it up on the controller config with bluetooth, use default settings with motion and vibration.

To Fix, replace Yuzu's SDL2.dll in your Yuzu installation at %AppData%/Local/Yuzu with a newer version sourced from the official SDL source at https://github.com/libsdl-org/SDL/releases such as https://github.com/libsdl-org/SDL/releases/download/release-2.26.5/SDL2-2.26.5-win32-x64.zip 

### Log File

Yuzu Logs don't take this issue into account and present no help for this issue.

### System Configuration

CPU: AMD Ryzen 7 3700X
GPU/Driver: NVIDIA GeForce RTX 3060 Ti / Vulkan
RAM: 32 GB DDR4
OS: Windows 10 Pro 64-Bit

**Comment by MyrTheMoth** [comment]
Related to https://github.com/yuzu-emu/yuzu/pull/10389

**Comment by eUnisk** [comment]
My experience, however, is exactly the opposite. I'm using an NS Pro-compatible controller (Mobapad M073).

Everything is fine with SDL.dll version 2.0.18 but ever since the Yuzu EA replaced it with the newer version my controller stopped working.  Button mapping is different (A&B. X&Y are switched) and motion control is no more working.

**Comment by german77** [comment]
Should be fixed in mainline 1477
