### ISSUE TITLE
Yuzu Android crashes to home screen after adding more games

### ISSUE THREAD

**Issue by K11MCH1** [yuzu-emu/yuzu#10509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

67eac44f6

### Description of Issue

Yuzu on Android crashes when attempting to boot a game after importing more ROMs to the ROM folder.
Reinstalling Yuzu fixes the issue, but, the issue returns after importing more games.

### Expected Behavior

Not crash.

### Reproduction Steps

After the initial setup of the app, add more games to the ROM folder and attempt to run a game.
The app should crash back to the home screen.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11607413/yuzu_log.txt)

### System Configuration

CPU: 8 Gen 2
GPU/Driver: Adreno 740
RAM: 16GB
OS: OriginOS

**Comment by german77** [comment]
On config you can open yuzu folder. You will find a regular log like on PC. But I doubt it has any detailed info about this crash. I will try to replicate and fix on my phone

**Comment by K11MCH1** [comment]
> On config you can open yuzu folder. You will find a regular log like on PC. But I doubt it has any detailed info about this crash. I will try to replicate and fix on my phone

Thanks got it. Posted it.

**Comment by K11MCH1** [comment]
> On config you can open yuzu folder. You will find a regular log like on PC. But I doubt it has any detailed info about this crash. I will try to replicate and fix on my phone

Upon further investigating, I have found that "Use disk shader cache" seems to be part of the issue.
I had initially activated and I thought uninstalling Yuzu would clear data. However after reinstalling this setting was still on and games were working.

To reproduce it:
1. Have a fresh install of the app. Activate "Use disk shader cache"
boot game: works.
2. Import more games.
boot game: crashes.
3. Turn off "Use disk shader cache"
boot game: works again.

**Comment by ttenor12** [comment]
I am experiencing this issue as well, as soon as I open a game, it crashes. Would my device not be supported? It's a Galaxy S20 FE with a Snapdragon 865 at 2.82

**Comment by FearlessTobi** [comment]
@t895 Can you please take a look?

**Comment by t895** [comment]
I just tried to repro this on the latest mainline build and I couldn't get the app to crash. I opened a retail game, imported more games, and then tried to open the same game and things worked fine (Disk shader cache was enabled the whole time). Is there something I'm missing here?

**Comment by K11MCH1** [comment]
> I just tried to repro this on the latest play store build and I couldn't get the app to crash. I opened a retail game, imported more games, and then tried to open the same game and things worked fine (Disk shader cache was enabled the whole time). Is there something I'm missing here?

That about the Disk Shader Cache is another issue that I'm having. I hid that comment and made another issue [here](https://github.com/yuzu-emu/yuzu/issues/10558) for it.

As for this issue, I'm not sure if the bug is resolved but I'm not able to reproduce it anymore.

**Comment by Essa-black** [comment]
> [yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11752553/yuzu_log.txt.old.txt) I am experiencing this issue as well, as soon as I open a game, it crashes. Would my device not be supported? It's a Galaxy S20 FE with a Snapdragon 865 at 2.84 ghz

Hi have you find out the fix cuz I am experiencing the same thing with the same phone.

**Comment by lordmilky** [comment]
I'm having the same issue with my OPPO Find x5 pro running a Snapdragon 8 Gen 1

I load up YUZU, Install my prod keys, Add the games folder and it crashes immediately and then won't launch unless I clear data or reinstall it but then the same thing happens.

**Comment by grythman** [comment]
[   0.354171] Frontend <Info> main/jni/native.cpp:Java_org_yuzu_yuzu_1emu_NativeLibrary_logDeviceInfo:728: yuzu Version: HEAD-2f9487cd3
[   0.354200] Frontend <Info> main/jni/native.cpp:Java_org_yuzu_yuzu_1emu_NativeLibrary_logDeviceInfo:729: Host OS: Android API level 33
[   0.354328] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:20: Device Manufacturer - Xiaomi
[   0.354337] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:20: Device Model - M2102K1G
[   0.354380] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:20: SoC Manufacturer - QTI
[   0.354433] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:20: SoC Model - SM7150
[   0.355420] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:20: Total System Memory - 6.0 GB
[   1.431186] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
[   1.452229] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
[   1.465858] Loader <Warning> core/loader/loader.cpp:GetLoader:259: File primary%3AYuzu%2FTHE%20KING%20OF%20FIGHTERS%20XIII%20GLOBAL%20MATCH%20%5B0100DC701A388000%5D%5Bv0%5D%5BUS%5D.nsp has a different type (unknown) than its extension.
[   1.465883] Loader <Warning> core/loader/loader.cpp:GetLoader:259: File primary%3AYuzu%2FTHE%20KING%20OF%20FIGHTERS%20XIII%20GLOBAL%20MATCH%20%5B0100DC701A388000%5D%5Bv0%5D%5BUS%5D.nsp has a different type (unknown) than its extension.
[   1.531536] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
[   1.538202] Loader <Warning> core/loader/loader.cpp:GetLoader:259: File primary%3AYuzu%2FAssassins%20Creed%20The%20Ezio%20Collection%20%5B0100670014482000%5D%5Bv0%5D%5BUS%5D.nsp has a different type (unknown) than its extension.
[   1.547905] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
[   1.548076] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
[   1.620074] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
[   1.647124] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
[   1.687271] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
[   1.799086] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
[   1.803184] Loader <Warning> core/loader/loader.cpp:GetLoader:259: File primary%3AYuzu%2FAssassins%20Creed%20The%20Ezio%20Collection%20%5B0100670014482000%5D%5Bv0%5D%5BUS%5D.nsp has a different type (unknown) than its extension.
[   1.809609] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
[   1.929736] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
[   2.049291] Debug <Critical> core/file_sys/fssystem/fssystem_nca_reader.cpp:operator():210: Assertion Failed!
