### ISSUE TITLE
No surround sound Cubeb/Alsa

### ISSUE THREAD

**Issue by davidheitman** [yuzu-emu/yuzu#10512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

master-05e38ee14

### Description of Issue

I've tried this with both mainline and master, just rebuilt today. Using cubeb in surround mode, I only get stereo in BotW. I use Alsa, no pulseaudio (I have my reasons, not worth going into here). Surround sound works fine from other sources (steam, kodi, etc), just not Yuzu. I'm connected via hdmi 2.1 on an nvidia 3060 to a denon receiver.

From the logs, cubeb appears to recognize 6 channels:

`[ 601.021912] Service.Audio <Debug> core/hle/service/audio/audren_u.cpp:GetWorkBufferSize:501: called.
Input params:
	Revision 7
	Sample Rate 48000, Sample Count 240
	Execution Mode 0, Voice Drop Enabled 1
	Sizes: Effects 000E, Mixes 001E, Sinks 0001, Submixes 0001, Splitter Infos 0000, Splitter Destinations 0000, Voices 0060, Performance Frames 0000 External Context 0000
Output params:
	Workbuffer size 00064000
[ 601.025715] Service.SM <Debug> core/hle/service/sm/sm.cpp:GetServiceImpl:193: called service=audren:u -> session=140276452286736
[ 601.025804] Service.Audio <Debug> core/hle/service/audio/audren_u.cpp:GetWorkBufferSize:501: called.
Input params:
	Revision 7
	Sample Rate 48000, Sample Count 240
	Execution Mode 0, Voice Drop Enabled 1
	Sizes: Effects 000E, Mixes 001E, Sinks 0001, Submixes 0001, Splitter Infos 0000, Splitter Destinations 0000, Voices 0060, Performance Frames 0000 External Context 0000
Output params:
	Workbuffer size 00064000
[ 601.033172] Service.SM <Debug> core/hle/service/sm/sm.cpp:GetServiceImpl:193: called service=audren:u -> session=140276452286736
[ 601.033208] Service.Audio <Debug> core/hle/service/audio/audren_u.cpp:GetWorkBufferSize:501: called.
Input params:
	Revision 7
	Sample Rate 48000, Sample Count 240
	Execution Mode 0, Voice Drop Enabled 1
	Sizes: Effects 000E, Mixes 001E, Sinks 0001, Submixes 0001, Splitter Infos 0000, Splitter Destinations 0000, Voices 0060, Performance Frames 0000 External Context 0000
Output params:
	Workbuffer size 00064000
[ 601.033481] Service.SM <Debug> core/hle/service/sm/sm.cpp:GetServiceImpl:193: called service=audren:u -> session=140276452286736
[ 601.034347] Service.Audio <Debug> core/hle/service/audio/audren_u.cpp:OpenAudioRenderer:468: Opened new AudioRenderer session 0 sessions open 1
[ 601.034399] Service.Audio <Info> audio_core/sink/cubeb_sink.cpp:CubebSinkStream:74: Opening cubeb stream ADSP_RenderStream-0 type 0 with: rate 48000 channels 6 (system channels 6) latency 1920
[ 601.062397] Service.Audio <Info> audio_core/sink/cubeb_sink.cpp:CubebSinkStream:74: Opening cubeb stream ADSP_RenderStream-1 type 0 with: rate 48000 channels 6 (system channels 6) latency 1920
[ 601.072126] Service.Audio <Debug> core/hle/service/audio/audren_u.cpp:QuerySystemEvent:169: called
[ 601.092296] Service.Audio <Debug> core/hle/service/audio/audren_u.cpp:Start:151: called`

But no surround. This is actually a 7.1 setup (technically 7.2.4, 2 subs and 4 atmos, but just need 5.1 here).  My .asoundrc:

`defaults.pcm.card 0
defaults.pcm.device 3
defaults.ctl.card 0
pcm.dmixer {
  type dmix
  ipc_key 1024
  slave {
    pcm "hw:0,3"
    period_size 4096
    buffer_size 16384
    rate 96000
    channels 8
  }
`

Tried the flatpack, mainline build, and master build. Nada. Any thoughts? And let's avoid the pulse vs alsa holy war please :D

### Expected Behavior

5.1 surround output

### Reproduction Steps

Alsa properly configured for surround output over HDMI to a receiver, cubeb set to surround mode.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11607652/yuzu_log.txt)

### System Configuration

CPU: 12th Gen Intel(R) Core(TM) i9-12900
GPU/Driver: nvidia 3060/525.89.02
RAM:64 GB
OS: Debian bookworm

**Comment by Kelebek1** [comment]
Games can report 6 channels but not actually use them. Use something like Audacity and capture all 6 channels and see what they're outputting, I would guess beyond the front left/right they're all just silence.

Or get more specific with it and build Yuzu and jump into the code and check out the values actually being output.

**Comment by Squall-Leonhart** [comment]
Cubeb only supports multichannel with pulse anyway.

**Comment by davidheitman** [comment]
Ahhhh, that sucks! You have no idea how long I've been screwing around with asoundrc and such trying to fix this! And pulse screws up my passthrough from kodi, which is my primary use for this box. In fact, I just tried pulse for the first time in forever, and it's no even seeing my sound card. Back to the drawing board...

**Comment by Squall-Leonhart** [comment]
you might try pipewire instead.

**Comment by davidheitman** [comment]
OK, got pulse "workimg" again.  But pulse STILL don't support dts-ma passthrough, so I can't use it for a box primarily used for movies.  I'll dig into pipewire, haven't used it yet. I am so close to the perfect media box, this is the only outstanding issue for me...

**Comment by davidheitman** [comment]
Looks like there's no passthrough in pipewire, so that's right out. I guess it's a choice between pulse and lower audio quality in kodi, or alsa and no surround in yuzu. Gotta go with alsa there. So. Very. Close...
