### ISSUE TITLE
When use turnip instant crash

### ISSUE THREAD

**Issue by Ragul32** [yuzu-emu/yuzu#10514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android build 1

### Description of Issue

Instant crash every game even homebrew and small games too

### Expected Behavior

.

### Reproduction Steps

.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11608544/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 
GPU/Driver:720g
RAM:6
OS: Android

**Comment by sigidessl** [comment]
Your device is way below min spec currently at least a Snapdragon 865 with 8gigs ram is required and even that won't run most games smooth...

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a suppport forum.
Please use our Discord for support requests.

Thanks

**Comment by TravMurav** [comment]
FWIW can confirm the same issue (Adreno 618 with Turnip missing mandatory vk features of 8/16 bit access and widelines) with yesterday's top commit using Fedora/aarch64 on Snapdragon 7c gen1 based laptop. 

I guess no one would bother translating data arrays passed from the game (which is what I guess these features are helping to avoid) and not sure if mesa would want/can do anything about it either...

See also: https://gitlab.freedesktop.org/mesa/mesa/-/issues/8424
