### ISSUE TITLE
Mesa 3d driver doesn't support  below sd870- android yuzu

### ISSUE THREAD

**Issue by Rahulk120** [yuzu-emu/yuzu#10524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Please add mesa 3d driver on lower snapdragon processors (below sd870, it doesn't work ).

### Why would this feature be useful?

It will help to load texture in  games ( like botw texture problem ) in lower snapdragon processors (below sd 870).

**Comment by FearlessTobi** [comment]
We are not the developers of the Mesa drivers.

**Comment by Ragul32** [comment]
> We are not the developers of the Mesa drivers.

Ofcourse you not but you guys need to fix it this not mesa issue it's yuzu issue not get supported

**Comment by Rahulk120** [comment]
I noticed that after I update my device to android 13 mesa turnip working in yuzu.I have one more device which has android 12, in this device mesa 3d doesn't work (app crash while clicking game). It seems we need to upgrade android 12 to 13.
