### ISSUE TITLE
"Issue: Bug Report" template suggestion

### ISSUE THREAD

**Issue by davidhedlund** [yuzu-emu/yuzu#10546]
### Issue

![image](https://github.com/yuzu-emu/yuzu/assets/6416073/3f3fe767-a19c-492d-a948-97951ccf28d4)

For https://github.com/yuzu-emu/yuzu/issues/new?assignees=&labels=&projects=&template=bug_report.yml, I suggest that you add
* https://yuzu-emu.org/help/reference/log-files/
* To avoid that people are adding yuzu_installer.log, mention yuzu_log.txt
* For homebrew games, also provide a log for commercial games.

Reference: https://github.com/yuzu-emu/yuzu/issues/10478#issuecomment-1566007406

**Comment by davidhedlund** [comment]
![image](https://github.com/yuzu-emu/yuzu/assets/6416073/c84e81c6-a9b0-492e-bf14-79ccd748c33f)

Please replace "Log file" with "yuzu_log.txt" to avoid people to upload yuzu_installer.log

**Comment by davidhedlund** [comment]
Also, you can open this issue.

"For homebrew games, also provide a log for commercial games." has not been added to https://yuzu-emu.org/help/reference/log-files/ yet.

**Comment by bm01** [comment]
> Also, you can open this issue.
> 
> "For homebrew games, also provide a log for commercial games." has not been added to https://yuzu-emu.org/help/reference/log-files/ yet.

I don't think that's a requirement, it's just that the information contained in your report before edits may not have been enough to identify the problem, so you were asked to provide more information. It isn't rare, and can happen with well written reports too.

In any case since reports related to homebrew games are pretty rare to begin with, I preferred to leave that out to keep the template short and easy to understand (some users may not even know what homebrew means and it could confuse them).

**Comment by davidhedlund** [comment]
> > Also, you can open this issue.
> > "For homebrew games, also provide a log for commercial games." has not been added to https://yuzu-emu.org/help/reference/log-files/ yet.
> 
> I don't think that's a requirement, it's just that the information contained in your report before edits may not have been enough to identify the problem, so you were asked to provide more information. It isn't rare, and can happen with well written reports too.

Oh, that's useful to add to https://yuzu-emu.org/help/reference/log-files/

> 
> In any case since reports related to homebrew games are pretty rare to begin with, I preferred to leave that out to keep the template short and easy to understand (some users may not even know what homebrew means and it could confuse them).

I see

**Comment by davidhedlund** [comment]
@bm01 Do you have permission to edit https://yuzu-emu.org/help/reference/log-files/ ?

**Comment by bm01** [comment]
> @bm01 Do you have permission to edit https://yuzu-emu.org/help/reference/log-files/ ?

I don't have any special permission. I simply did what FearlessTobi suggested and opened a pull request (that's where the contributor tag comes from). Anyone can do it, and I suggest learning a bit about Git and reading this page if you want to give it a try: https://github.com/firstcontributions/first-contributions

In any case the website's sources are in a different repository (https://github.com/yuzu-emu/yuzu-emu.github.io) so this isn't even the right place to suggest changes to it.

**Comment by davidhedlund** [comment]
> ![image](https://user-images.githubusercontent.com/6416073/243099266-c84e81c6-a9b0-492e-bf14-79ccd748c33f.png)
> 
> Please replace "Log file" with "yuzu_log.txt" to avoid people to upload yuzu_installer.log

@bm01 Can you solve this?

**Comment by davidhedlund** [comment]
> > @bm01 Do you have permission to edit https://yuzu-emu.org/help/reference/log-files/ ?
> 
> I don't have any special permission. I simply did what FearlessTobi suggested and opened a pull request (that's where the contributor tag comes from). Anyone can do it, and I suggest learning a bit about Git and reading this page if you want to give it a try: https://github.com/firstcontributions/first-contributions
> 
> In any case the website's sources are in a different repository (https://github.com/yuzu-emu/yuzu-emu.github.io) so this isn't even the right place to suggest changes to it.

Thank you for the repo link.
