### ISSUE TITLE
Android: OpenGL API support

### ISSUE THREAD

**Issue by NekonexDev** [yuzu-emu/yuzu#10556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Header

### Why would this feature be useful?

Some games dont start.

**Comment by FearlessTobi** [comment]
We do not support OpenGL on Android.

**Comment by dogtopus** [comment]
I'd assume that you'll need full GL support for this (rather than just GLES) but last time I checked most mobile GPUs only had GLES and they jumped to Vulkan directly when that became a thing.
