### ISSUE TITLE
3604 Breaks Windows 1809 Compatibility

### ISSUE THREAD

**Issue by HiroTDK** [yuzu-emu/yuzu#10554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3604+

### Description of Issue

Something changed in 3604 that causes Yuzu EA to crash on Windows 1809. The yuzu log is cut-off mid string with no indication of issue, but the Windows crash dump gives this:

> (b8c.edc): Security check failure or stack buffer overrun - code c0000409 (first/second chance not available)
ucrtbase!abort+0x4e:
00007ffb`6b02e77e cd29            int     29h

Yuzu EA crashes, however Yuzu Mainline runs perfectly fine. After encountering someone else with the same issue and OS version, I went back through the source for both EA and Mainline and it looks like the time changes in 3604 haven't been pushed to the mainline Yuzu builds.

Unfortunately, GitHub won't allow me to attach the full crash dump, so I hope this is enough.

### Expected Behavior

Launch games without crashing.

### Reproduction Steps

Use Windows 1809, open Yuzu EA, launch game.

### Log File

[Crash YuzuEA.txt](https://github.com/yuzu-emu/yuzu/files/11628931/Crash.YuzuEA.txt)

### System Configuration

Intel Core i7-6700K CPU @ 4.00GHz, 4 Cores, 8 Threads
Radeon RX 570 (8GB) / AMD 23.5.1
16 GB DDR4
Windows 10.0.17763 Build 17763

**Comment by Squall-Leonhart** [comment]
1809 is end of support.

**Comment by FearlessTobi** [comment]
Correct.

**Comment by anpilley** [comment]
The quickstart guide still lists win 10 1809 as the minimum required version. If it's no longer supported, that probably needs updating.

**Comment by FearlessTobi** [comment]
@anpilley You are right, thanks for spotting this

**Comment by HiroTDK** [comment]
> 1809 is end of support.

No offense, but that's a really bad answer. The guide on the site lists 1809 as supported.  The only thing breaking compatibility is this time_manager in that update, and it's only in the Early Access version. Can you explain why that can't be fixed? Is there an inherent issue in the OS libraries? Anything?

**Comment by Squall-Leonhart** [comment]
> No offense, but that's a really bad answer. The guide on the site lists 1809 as supported. The only thing breaking compatibility is this time_manager in that update, and it's only in the Early Access version. Can you explain why that can't be fixed? Is there an inherent issue in the OS libraries? Anything?

Times change, OS is out of date, the issue occurs due to an unpatched bug in the UCRTBase expression parsing, and its not even the first time such an issue has reared its head.

Nobody is obligated to support you, nor are they obligated to give a qualifying answer to your satisfaction.

**Comment by HiroTDK** [comment]
> the issue occurs due to an unpatched bug in the UCRTBase expression parsing

You could have said that instead of "1809 is end of support." And sure, you're not obligated to give me a qualifying answer, but I did give money to the project for this product and the site explicitly says it supports this OS, so maybe something better than "lol, no" is in order.
