### ISSUE TITLE
Yuzu not receving inputs from Nintendo Pro controlers

### ISSUE THREAD

**Issue by CLANK0624** [yuzu-emu/yuzu#10552]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

EA 3628

### Description of Issue

<img width="1066" alt="procon" src="https://github.com/yuzu-emu/yuzu/assets/93827580/62dbb273-6a1a-4e9a-992c-4ea5710aff0b">

Yuzu not getting inputs from Pro cons

it's on Bluetooth
works fine at other platforms(Steam, Xbox center, App players)
except for YUZU

same with other older versions

tried  restarting PC, YUZU, and controllers
turned off my steam client

### Expected Behavior

To get it to work with pro cons

### Reproduction Steps

N/A

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11627622/yuzu_log.txt)

### System Configuration

CPU: 7950x3d
GPU/Driver: RTX 4090
RAM: 64GB
OS: Windows 11 pro

Controller info: 
Switch Pro Controller
Wireless Gamepad (STANDARD GAMEPAD Vendor: 057e Product: 2009)

**Comment by german77** [comment]
Seems like you have enabled the experimental pro controller driver. Is your controller original? Otherwise I recommend to disable the driver on advanced controller config

**Comment by Squall-Leonhart** [comment]
> Is your controller original?

seems original https://devicehunt.com/view/type/usb/vendor/057E/device/2009
Unless chinese clones are faking VID/PIDS now.

**Comment by CLANK0624** [comment]
> Seems like you have enabled the experimental pro controller driver. Is your controller original? Otherwise I recommend to disable the driver on advanced controller config

Thanks for the help!
That solved the problem

**Comment by german77** [comment]
Th
