### ISSUE TITLE
Screenshots not working

### ISSUE THREAD

**Issue by angel-pg96** [yuzu-emu/yuzu#10565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline

### Description of Issue

I have a suggestion and is that the screenshots with the button do not work? the virtual button does nothing... taking a screenshot with stock android loses the image and leaves at another time... the capture button should work so they would have the resolution of the image of the switch screen and not of android... al press the pause emulation button and seconds are not lost the basic essence of the moment 

### Expected Behavior

that when pressing the virtual capture button, I pause the emulation for a couple of seconds so that it does not lose the essence of the moment 

### Reproduction Steps

screenshots

### Log File

okdkdk

### System Configuration

CPU: SD 888
GPU/Driver: 660
RAM: 8
OS: Android 13 one ui 5.1

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support.
