### ISSUE TITLE
Add joystick click on touch controls in Android 

### ISSUE THREAD

**Issue by rishabruh** [yuzu-emu/yuzu#10569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

There is no way of doing a 'Joystick Click' on the touch controls on android. Looked through all settings and could not figure it out.

### Why would this feature be useful?

Games require joystick click. BOTW relies on joystick clicks for sneaking and using your Slate as a viewfinder.

**Comment by velikoss** [comment]
no progress?
with this issue it's not possible to play Cities: Skylines normally

**Comment by rogerclotet** [comment]
I believe this is already in the overlay controls, I think the issue can be closed.

**Comment by rishabruh** [comment]
The joystick click buttons have been added to yuzu now. Sorry for not closing this issue sooner.
