### ISSUE TITLE
Pokemon shiny diamond wont start anymore after version 1446 mainline

### ISSUE THREAD

**Issue by walikor** [yuzu-emu/yuzu#10571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1455 (Windows)

### Description of Issue

Pokémon Brilliant Diamond not working anymore crash after the initial load, I tried with high gpu and with opengl and vulkan, with mainline 1446 working correctly.

### Expected Behavior

the game should launch after the initial load

### Reproduction Steps

start the game

### Log File

https://www.mediafire.com/file/3gezsjvonetognk/yuzu_log.txt/file

### System Configuration

CPU: HexaCore Intel Core i5-8500, 3.00 GHz 
GPU/Driver: NVIDIA GeForce GTX 1080  (8 GB) driver version 535.98
RAM: 2 Corsair Vengeance LPX CMK8GX4M1A2400C14 8 GB ( 16 GB)
OS: Microsoft Windows 10 Pro 22H2

**Comment by Squall-Leonhart** [comment]
Game boots just fine on EA and mainline here.

**Comment by RenanTafner** [comment]
same issue here with the latest EA 3630

**Comment by Squall-Leonhart** [comment]
Yuzu crashing in AVCodec-59.dll when loading a save, workaround is to use software video decoding for the time being until it gets looked into.

**Comment by Squall-Leonhart** [comment]
This will be fixed in tomorrows Mainline update.

**Comment by walikor** [comment]
> This will be fixed in tomorrows Mainline update.

With Mainline 1460 now is working with NVDEC Hardware Accelerated.

Thanks.
