### ISSUE TITLE
Wayland still not working

### ISSUE THREAD

**Issue by Alleop5** [yuzu-emu/yuzu#10579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline and EA

### Description of Issue

When I launch yuzu after compiling it it crashes (Also happens with the AppImage.

Available platform plugins are: xcb.

The problem here is that I have the wayland plugin installed and I can verify that as it works in keepassxc. I've looked through the issues but no fix there. Also something to note is that the yuzu installer (liftinstall) just worked fine and booted without any issue.

### Expected Behavior

It opens in Wayland.

### Reproduction Steps

Install Void Linux. Then install some Wayland WM (I use dwl). Then install keepassxc (to check if it works and for dependencies) and qt5-wayland. Then open the AppImage of yuzu. Then crash.

### Log File

qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

### System Configuration

CPU: 11th Gen Intel i5-1135G7 (8) @ 4.200GHz
GPU/Driver: Intel TigerLake-LP GT2 [Iris Xe Graphics]
RAM: 661MiB / 7649MiB
OS: Void Linux x86_64

PS: I copied this out of neofetch.

**Comment by liamwhite** [comment]
Seems like a package/distro configuration issue. Official builds don't include the Wayland QPA platform due to numerous compositor issues preventing a good experienced by default. Your own builds must not be including the Wayland platform plugin either. yuzu has worked on Wayland since #7410 was merged, and I personally test on Wayland on a regular basis.

**Comment by Alleop5** [comment]
Did you. Read the entire issue? Keepassxc and liftinstall just works fine. Both wayland apps. Keepassxc is also coded in qt. Though it's really weird that yuzu can't find the wayland plugin as every app uses it.

Also are you 100% sure you aren't using XWayland?

**Comment by hurricane-dorian** [comment]
Try QT6. Works great for me.

**Comment by Alleop5** [comment]
Thanks @hurricane-dorian! It worked and now I'm in yuzu! Yuzu does try to read /usr/share/X11/locale on startup but that doesn't crash yuzu so it's fine I guess.

**Comment by Alleop5** [comment]
Also small note, I've built yuzu with qt6 support. And when I ninja install it works but the executable fails because it doesn't find libQt5Multimedia.so.5 so qt 6 isn't entirely used.

**Comment by Alleop5** [comment]
Also I did all of this for nothing LOL. I forgot that my iGPU has 1/4 a gig of VRAM so it doesn't boot any game. I did get some experience. So I could use it when I upgrade my gpu from a GTX 980.

**Comment by hurricane-dorian** [comment]
Addressing note: Verify qt6-multimedia is installed. (I believe it is just used for camera anyways so you can disable it pretty harmlessly with -DYUZU_USE_QT_MULTIMEDIA=OFF)

**Comment by mikebutash** [comment]
I've been testing wayland with yuzu today for the first time, games would bomb out with vulkan errors.  I followed it back to the QT_QPA_PLATFORM=xcb issue, and launch with that does get TOTK to launch for me.

These threads seem to indicate it resolved, but it would certainly seem not.  Should it be, or reopened?

This is with bleeding edge Arch Linux with KDE 5.27(qt5.15)+wayland, nvidia 5.30, 6.3.6 kernel with yuzu ea 3653 from AUR.

**Comment by liamwhite** [comment]
I have no issues running Tears of the Kingdom on Wayland with mutter. Potentially a compositor issue?

**Comment by mikebutash** [comment]
I would presume it's something yuzu doesn't like from kde's kwin-wayland vs kwin-xorg compositors, but not sure why when every other steam game I've tried with wayland works fine, even Ryujinx, so seems something borked with Yuzu only.  Nothing special or fancy here, so presuming this would bust anyone else using kde+wayland too.
