### ISSUE TITLE
ANDROID: Recent Fix update caused incorrect display for tablet Xiaomi Mi Pad 5

### ISSUE THREAD

**Issue by Saitolai** [yuzu-emu/yuzu#10573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 6273e1f

### Description of Issue

Update of 1st June 2023 caused screen display orientation to not show properly, even when said update description mentions to fix display for tablets, but it breaks the function instead.

### Expected Behavior

![Screenshot_2023-06-02-22-02-43-905_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/95283674/6361246a-b1d6-4e5d-a499-d41593883984)
Correct display should look like this ( Tested from Xiaomi 13 )

![Screenshot_2023-06-02-21-50-58-612_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/95283674/5938c03a-b204-4178-a573-207ace8dc0ad)
![Screenshot_2023-06-02-21-51-18-682_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/95283674/5826140a-2fe9-42a5-8709-c988ada23213)
Issue displayed as above from Xiaomi Mi Pad 5.

### Reproduction Steps

Launch the game ( so far only tested on Cytus Alpha as that is the only game I have at the moment ).

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11636179/yuzu_log.txt)

### System Configuration

CPU: Qualcomm Snapdragon 860 
GPU/Driver: Adreno 640
RAM: 6GB
OS: Android 11

**Comment by kbobk** [comment]
I'm experiencing the same issue on my Xiaomi Mi Pad 5. ):

**Comment by tirmey** [comment]
Same here. Mi pad 5 user, orientation issues after jun 2 update...

**Comment by bunnei** [comment]
Apologies for the trouble here. We should have a fix out within the next day or two.

**Comment by kbobk** [comment]
> Apologies for the trouble here. We should have a fix out within the next day or two.

Glad to hear that!
Thank you very much for the hard work you've been putting into this emulator, we appreciate it very much!

**Comment by jjaykkay222** [comment]
I still have this problem on samsung galaxy tab s8... Was it fixed on other platforms?

**Comment by J0SHO** [comment]
Still an issue on tab s8 after updating.

**Comment by tondo82** [comment]
same on samsung tab s7, a good start!

**Comment by lacrdeveloper** [comment]
Hi, updated today 06/06/2023 i still have the problem, xiaomi pad 5

**Comment by PinciThiago** [comment]
Updated the app and the problem still there

**Comment by PinciThiago** [comment]
> > Updated the app and the problem still there
> 
> How do you update? Every time i check on the app store, it never says update :/

There was no update since the last one on 6/5

**Comment by tirmey** [comment]
Guys, c'mon! The developers already knows about this issue. Give them some space...

**Comment by kbobk** [comment]
> Guys, c'mon! The developers already knows about that issue. Give them some space...

I agree 100% with you bro... But, just clarifying that the guys intentions are just to update the devs. And I take this comment to thank the devs for the awesome work and say that like Tirmey said, no pressure, do it at your own time, we appreciate your work. (:

**Comment by bunnei** [comment]
Should be fixed with today's Play Store update to both mainline and EA (vers. f759ff3a5c)

Can you confirm?

**Comment by kbobk** [comment]
Awesome! We'll bring the feedback

**Comment by kbobk** [comment]
> Should be fixed with today's Play Store update to both mainline and EA (vers. [f759ff3](https://github.com/yuzu-emu/yuzu/commit/f759ff3a5c2ee78d2ddc16af9c57aa03518f4502))
> 
> Can you confirm?

Awesome! We'll bring the feedback

**Comment by tondo82** [comment]
affirmative, thanks a lot guys!

**Comment by tirmey** [comment]
> Should be fixed with today's Play Store update to both mainline and EA (vers. [f759ff3](https://github.com/yuzu-emu/yuzu/commit/f759ff3a5c2ee78d2ddc16af9c57aa03518f4502))
> 
> Can you confirm?

Affirmative. You nailed it!

**Comment by bunnei** [comment]
Glad to hear! Closing as this is fixed.

**Comment by kbobk** [comment]
Fixed!!!! Thanks a lot guys, you are the best!
