### ISSUE TITLE
 error: use of undeclared identifier 'GCAdapter'

### ISSUE THREAD

**Issue by killown** [yuzu-emu/yuzu#10574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)
yuzu-mainline-git r23847.0e4045c7c-1

### Description of Issue

[834/1171] Building CXX object src/input_common/CMakeFiles/input_common.dir/main.cpp.o
FAILED: src/input_common/CMakeFiles/input_common.dir/main.cpp.o 
/usr/bin/clang++ -DARCHITECTURE_x86_64=1 -DBOOST_ASIO_DISABLE_CONCEPTS -DBOOST_CONTEXT_DYN_LINK -DBOOST_CONTEXT_NO_LIB -DFMT_SHARED -DHAVE_SDL2 -DNDEBUG -DYUZU_UNIX=1 -D_FILE_OFFSET_BITS=64 -I/files/trizen/yuzu-mainline-git/src/yuzu/src/. -I/files/trizen/yuzu-mainline-git/src/yuzu/externals/./microprofile -isystem /usr/include/SDL2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -march=znver3 -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto -flto=thin -O2 -g -DNDEBUG -std=gnu++20 -Werror=all -Werror=extra -Werror=missing-declarations -Werror=shadow -Werror=unused -Wno-attributes -Wno-invalid-offsetof -Wno-unused-parameter -Wno-braced-scalar-init -Wno-unused-private-field -Werror=shadow-uncaptured-local -Werror=implicit-fallthrough -Werror=type-limits -mcx16 -fwrapv -Werror=conversion -Winvalid-pch -Xclang -include-pch -Xclang /files/trizen/yuzu-mainline-git/src/build/src/input_common/CMakeFiles/input_common.dir/cmake_pch.hxx.pch -Xclang -include -Xclang /files/trizen/yuzu-mainline-git/src/build/src/input_common/CMakeFiles/input_common.dir/cmake_pch.hxx -MD -MT src/input_common/CMakeFiles/input_common.dir/main.cpp.o -MF src/input_common/CMakeFiles/input_common.dir/main.cpp.o.d -o src/input_common/CMakeFiles/input_common.dir/main.cpp.o -c /files/trizen/yuzu-mainline-git/src/yuzu/src/input_common/main.cpp
/files/trizen/yuzu-mainline-git/src/yuzu/src/input_common/main.cpp:315:21: error: use of undeclared identifier 'GCAdapter'
    std::shared_ptr<GCAdapter> gcadapter;
                    ^
1 error generated.
[847/1171] Building CXX object src/shader_recompiler/CMakeFiles/shader_recompiler.dir/backend/glasm/emit_glasm.cpp.o

### Expected Behavior

compile...

### Reproduction Steps

compile...

### Log File

compile...

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by german77** [comment]
Is ENABLE_LIBUSB enabled?

**Comment by german77** [comment]
Should be fixed. Please open if the issue still persist.
