### ISSUE TITLE
Android - add support for android 10

### ISSUE THREAD

**Issue by guranu** [yuzu-emu/yuzu#10585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

listen i understand that google play wants to only have apps for android 11 and higher. But why can't you add support for android 10 devices? Skyline did so you should also be able to add support for it. Also add support for people in russia to download your emulator.

### Why would this feature be useful?

So that more people can have access to your emulator.

**Comment by goldenx86** [comment]
We decided to restrict the app to Android 11 to cut off support for devices with Vulkan 1.0 drivers (Adreno 500 series for example) and low RAM devices as much as possible.
We don't intend to revert this decision, you're free to compile the app from source and remove the version restriction.

**Comment by Aleixz** [comment]
Why do you insist on running and playing emulators on outdated and underperforming devices? Is this really the way to get the gaming experience?

**Comment by Riot20058** [comment]
@Aleixz really people test smo on pimax portal runs 52fps custom builds so yeah some games run wall thier keep mind pimax portal probably only a10 devices run yuzu at okay framerate best stuck 2d games on it.

**Comment by Riot20058** [comment]
![Screenshot_20230602-221300](https://github.com/yuzu-emu/yuzu/assets/128275823/08e0ab4a-5046-464b-84a4-11f25f9a6630)
![Screenshot_20230603-201816](https://github.com/yuzu-emu/yuzu/assets/128275823/c32764ea-15d9-4c6a-83dc-fc96ed7d2ee6)
![Screenshot_20230603-201912](https://github.com/yuzu-emu/yuzu/assets/128275823/21916f17-3b68-438c-ab68-cb29d327adf4)
Tested on pimax portal
