### ISSUE TITLE
Pokemon sword 1.0 is not starting up

### ISSUE THREAD

**Issue by Emargamer24sv** [yuzu-emu/yuzu#10589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline e8c3f69

### Description of Issue

I upgraded yuzu 1048 to this new version an i whanna run pokemon sword but when i selected it yuzu crashed,im runnig the firmware 15.0.1

### Expected Behavior

Is supposed to be working

### Reproduction Steps

Idk

### Log File

A

### System Configuration

CPU:Intel Core i5-10210U
GPU/Driver: Mesa Intel UHD Graphics (GML GT2)
RAM:8GB
OS:Ubuntu 22.04.2 LTS

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by Squall-Leonhart** [comment]
> This is an issue tracker for developers and not a support forum. Please use our Discord for support requests.

This is a valid bug, but its a duplicate of #10571 , caused by the FFMPEG update
