### ISSUE TITLE
yuzu crashes if the rom path is on a disk that has bitlocker on it

### ISSUE THREAD

**Issue by zero057** [yuzu-emu/yuzu#10597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1455

### Description of Issue

![image](https://github.com/yuzu-emu/yuzu/assets/73668722/24891363-24dc-444b-9c1b-5ab84999e07d)

### Expected Behavior

yuzu should give a warning or something instead of crashing i thought my installation is corrupted when i first got this error

### Reproduction Steps

handle the exception of not having the permission to access some rom

### Log File

it crashes before even making a log file
![image](https://github.com/yuzu-emu/yuzu/assets/73668722/429c8441-4332-459c-bafc-56f1819356d9)

### System Configuration

CPU:Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz   2.71 GHz
GPU/Driver: gtx 1650 super / version 535.98
RAM: 12 GB
OS: windows 10

**Comment by Squall-Leonhart** [comment]
incomplete report, the system configuration is required.

**Comment by zero057** [comment]
> incomplete report, the system configuration is required.

added, sorry about that this my first time reporting an issue

**Comment by melterx12** [comment]
seeing the same issue on my end

**Comment by Squall-Leonhart** [comment]
Is this volume not automatically unlocked on login?

**Comment by melterx12** [comment]
No, it's an external drive. It needs a password to unlock every time it is connected.

**Comment by Squall-Leonhart** [comment]
Yuzu should not crash, a Locked volume should throw 

[   9.484490] Common.Filesystem <Error> common/fs/fs.cpp:IterateDirEntries:417: Filesystem object at path= does not exist
