### ISSUE TITLE
OS Compatibility List

### ISSUE THREAD

**Issue by davidhedlund** [yuzu-emu/yuzu#10593]
### Issue

We have a [Game Compatibility List](https://yuzu-emu.org/game/). I suggest an OS Compatibility List here page (like https://www.ventoy.net/en/isolist.html)

### GNU/Linux distributions

Compatible with
* Trisquel 11 - https://github.com/yuzu-emu/yuzu/issues/10478
* Ubuntu MATE 22.04 - https://github.com/yuzu-emu/yuzu/issues/10328

Incompatible with
* Ubuntu 22.04 - https://github.com/yuzu-emu/yuzu/issues/10328
* Ubuntu 23.04 - https://github.com/yuzu-emu/yuzu/issues/10328

**Comment by FearlessTobi** [comment]
Please open this as a feature request on our website repository instead. 
https://github.com/yuzu-emu/yuzu-emu.github.io

Thanks

**Comment by davidhedlund** [comment]
> Please open this as a feature request on our website repository instead. https://github.com/yuzu-emu/yuzu-emu.github.io
> 
> Thanks

Done. But wouldn't it be useful to find a generated file over compatible OSes in this repo too?
