### ISSUE TITLE
Android: Add support for Mali GPUs

### ISSUE THREAD

**Issue by tnagorran** [yuzu-emu/yuzu#10592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Existing issues -> https://github.com/yuzu-emu/yuzu/issues/10544

Add Mali GPU support to the Android version of yuzu,
You can take inspiration from the work done in Skyline, as this is the only way to run Switch on a Mali GPU (like all Google phones). 

### Why would this feature be useful?

Skyline is discontinued and is the only ways to run Switch Game on Android with Mali GPU (like all Google phone)

**Comment by alfhashut** [comment]
İ waiting mali support too.

**Comment by 990616682** [comment]
Please support MediaTek devices.

**Comment by irishdude5280** [comment]
Me too please! When you have time

**Comment by Cleusonx** [comment]
É compatível gpu mali g68
