### ISSUE TITLE
Please make auto screen rotate function like skyline

### ISSUE THREAD

**Issue by Finblade** [yuzu-emu/yuzu#10602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I suggest to add auto screen rotate function (Not manually turn on rotate button on phone) like skyline. Now yuzu android can play through only one landscape side and it is so uncomfortable while using controller and usb cable for charging.

### Why would this feature be useful?

A lot of people play in different situations like using controller, connecting usb cable for charging. Auto screen rotate function like skyline can be very useful in these situation. Now its uncomfortable since we can only play in one landscape side only.

**Comment by PocVampira** [comment]
Eu não consigo jogar no meu tablet tab s8, pois a tela não gira é o game só abre e modo retrato

**Comment by FearlessTobi** [comment]
This has been implemented.
