### ISSUE TITLE
RAM, CPU, GPU resource meter 

### ISSUE THREAD

**Issue by angel-pg96** [yuzu-emu/yuzu#10604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

a cpu, ram and gpu usage bar, meter 

### Why would this feature be useful?

It would be easier to know the requirements to run the game ... that way it could be used in the compatibility list with that addition

**Comment by angel-pg96** [comment]
thanks. I am supporting buying its paid edition in playstore

**Comment by Squall-Leonhart** [comment]
please edit the issue name to include [Android]

**Comment by FearlessTobi** [comment]
This is not functionality that yuzu needs to provide, there are already third party tools for viewing your resource usage.
