### ISSUE TITLE
0100B04011742000

### ISSUE THREAD

**Issue by AndroidEmu1** [yuzu-emu/yuzu#10606]
### Issue

force close after loading
![Screenshot_2023-06-03-15-17-39-419_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/105457526/e3e1ca13-d4f3-4f58-a12a-ccd5b81a9e7e)

**Comment by Squall-Leonhart** [comment]
You used the developer template instead of the user template.
