### ISSUE TITLE
wiki: faq has broken section link

### ISSUE THREAD

**Issue by NetSysFire** [yuzu-emu/yuzu#10608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I'd have loved to quickly fix this tiny thing myself but the wiki is read-only to everyone but the members of this organization.

https://github.com/yuzu-emu/yuzu/wiki/FAQ#what-are-the-system-requirements-for-yuzu links to the quickstart guide with the anchor of `#hardware`, which has since changed to `#hardware-requirements` (<https://yuzu-emu.org/help/quickstart/#hardware-requirements>).

### Why would this feature be useful?

n/a

**Comment by FearlessTobi** [comment]
Thanks a lot for your report. I have fixed the link now.
To be honest I wasn't even aware our wiki was read-only for normal users.
