### ISSUE TITLE
Screen flipped / mirrored - Guacamelee & others (Android)

### ISSUE THREAD

**Issue by ServerReset** [yuzu-emu/yuzu#10627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Current mainline 

### Description of Issue

Guacamele 1 and 2, as well as a few other gamed reported by other folks and one of 2 more in my library are flipped 180 and mirrored. Oddly enough at least in my case for the pre juicebox intro it's correct for a second. then fucks itself up.

### Expected Behavior

Be right side up and unmirrored, we don't live in Australia.

### Reproduction Steps

Idk play the game, it's good so I think you might wanna continue afterwards anyway.

### Log File

Uhhhhhhhh

### System Configuration

CPU: 8+g1
GPU/Driver: any
RAM: 12+8
OS: Oneui 5.1 atop android 13

**Comment by FearlessTobi** [comment]
Closing for incomplete issue template.
