### ISSUE TITLE
Los Drivers Mesa Turnip no funcionan en mi Poco X3 Pro, pero es raro ya que si funcionan en otros dispositivos iguales a este

### ISSUE THREAD

**Issue by Andrescorde** [yuzu-emu/yuzu#10631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu

### Description of Issue

Se cierra el emulador al intentar abrirlo los juegos con Drivers Mesa turnip en mi Poco x3 Pro

### Expected Behavior

Abrir juegos sin ningún problemas como los haría con driver qualcom

### Reproduction Steps

![Screenshot_2023-06-05-15-15-06-045_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/134086260/cf3b0feb-3ffb-4d37-8df0-8c55ec45ea5f)

### Log File

No se

### System Configuration

CPU:640 adreno
GPU/Driver:mesa turnip
RAM:8
OS:Android 12

**Comment by german77** [comment]
Duplicate of #10629
