### ISSUE TITLE
(Android Build) Only Display in Portrait

### ISSUE THREAD

**Issue by vjjulius** [yuzu-emu/yuzu#10642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access/Mainline 069d7e6be.ver 2023/06/06

### Description of Issue

(Android Build) Only Display in Portrait

### Expected Behavior

Need to rotate the game.

### Reproduction Steps

Running the game,

### Log File

[   0.005891] Frontend <Info> main/jni/native.cpp:RunEmulation:429: starting
[   0.006158] Config <Info> main/jni/config.cpp:LoadINI:46: Successfully loaded /storage/emulated/0/Android/data/org.yuzu.yuzu_emu.ea/files/config/config.ini
[   0.006284] Frontend <Info> main/jni/emu_window/emu_window.cpp:EmuWindow_Android:58: initializing
[   0.006480] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.006504] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.006873] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007156] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007288] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007409] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007567] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007695] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007820] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007933] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.008062] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.008192] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.080361] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_conservative_rasterization
[   0.080373] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_depth_range_unrestricted
[   0.080374] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_extended_dynamic_state
[   0.080375] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_extended_dynamic_state2
[   0.080376] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_extended_dynamic_state3
[   0.080377] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_vertex_input_dynamic_state
[   0.080378] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_NV_geometry_shader_passthrough
[   0.080379] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_NV_viewport_array2
[   0.080393] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_NV_viewport_swizzle
[   0.080394] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:799: Missing required extension VK_EXT_robustness2
[   0.080398] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature customBorderColors
[   0.080398] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature extendedDynamicState
[   0.080399] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature primitiveTopologyListRestart
[   0.080399] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature provokingVertexLast
[   0.080400] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature timelineSemaphore
[   0.080400] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature vertexInputDynamicState
[   0.080401] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature uniformAndStorageBuffer16BitAccess
[   0.080402] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature storageBuffer8BitAccess
[   0.080402] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature uniformAndStorageBuffer8BitAccess
[   0.080403] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature logicOp
[   0.080404] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature multiViewport
[   0.080405] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature wideLines
[   0.080405] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature nullDescriptor
[   0.080406] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature robustBufferAccess2
[   0.080406] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature robustImageAccess2
[   0.080407] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature shaderDemoteToHelperInvocation
[   0.080412] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:927: maxViewports has to be 16 or greater but it is 1
[   0.080420] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:349: Unsuitable driver, continuing anyway
[   0.080441] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:395: Qualcomm and Turnip drivers have broken VK_EXT_custom_border_color
[   0.080442] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:403: Qualcomm drivers have broken VK_EXT_extended_dynamic_state
[   0.080443] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:408: Qualcomm drivers have a slow VK_KHR_push_descriptor implementation
[   0.080445] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:Device:420: Patching Adreno driver to support BCn texture formats
[   0.080826] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:559: Driver does not support native BGR format
[   0.223997] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:157: Driver: Qualcomm Technologies Inc. Adreno Vulkan Driver 512.502.0
[   0.224010] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:158: Device: Adreno (TM) 650
[   0.224011] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:159: Vulkan: 1.1.128
[   0.224037] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:160: Available VRAM: 4.00 GiB

### System Configuration

CPU: 870
GPU/Driver: 650
RAM: 8GB
OS: Android 12

**Comment by vjjulius** [comment]
![rn_image_picker_lib_temp_463821cb-facc-40a1-aeef-83395b3bd43c](https://github.com/yuzu-emu/yuzu/assets/14800655/8127c516-889d-47f6-b922-a185945d0021)

**Comment by FearlessTobi** [comment]
Closing as Duplicate.

**Comment by vjjulius** [comment]
but im still having this issue. the other issue number is also closed......
