### ISSUE TITLE
Pokémon Mystery Dungeon: Rescue Team DX won't start with Vulkan API

### ISSUE THREAD

**Issue by walikor** [yuzu-emu/yuzu#10648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1460 Windows

### Description of Issue

yuzu crashes after a few seconds that you start the game, instead with the opengl API the game starts correctly.

### Expected Behavior

That the game plays the opening cinematic and the game starts

### Reproduction Steps

Start the game with Vulkan API

### Log File

https://www.mediafire.com/file/qlxsxf5lbxmkfgl/yuzu_log(Vulkan).txt/file

https://www.mediafire.com/file/qw5pkb4jzdunug2/yuzu_log(Opengl).txt/file

### System Configuration

CPU: HexaCore Intel Core i5-8500, 3.00 GHz
GPU/Driver: NVIDIA GeForce GTX 1080 (8 GB) driver version 535.98
RAM: 2 Corsair Vengeance LPX CMK8GX4M1A2400C14 8 GB ( 16 GB)
OS: Microsoft Windows 10 Pro 22H2

**Comment by Squall-Leonhart** [comment]
Clear the vulkan pipelines and try starting it again, then post the log.

**Comment by walikor** [comment]
> Clear the vulkan pipelines and try starting it again, then post the log.
> 
> There are some builds in this issue that might be of relevance to test #10600

https://www.mediafire.com/file/qw70cgyl4de883p/yuzu_log.txt/file

Done

**Comment by walikor** [comment]
hi,
with mainline 1483 the game start with vulkan API.
