### ISSUE TITLE
Cassette Beasts with video issues

### ISSUE THREAD

**Issue by LukasSo7th** [yuzu-emu/yuzu#10654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3644

### Description of Issue

The Cassette Beasts game does not start normally, it takes a while and when you go to the main screen it turns completely purple only with the A button on the screen
indicating that it has to be tight

### Expected Behavior

With normal colors without the screen turning completely purple

### Reproduction Steps

Just start the game and on the home screen it already has the problem

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11670864/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11670865/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD RYZEN 5 5600X
GPU/Driver: GEFORCE RTX 3060
RAM:16 GB
OS: WIN 10 PRO 64 BITS

**Comment by Squall-Leonhart** [comment]
This game might require single core emulation, and may be affected by CNT changes.

**Comment by LukasSo7th** [comment]
so there is no prediction of when it will work on the emulator, right? :(

**Comment by Squall-Leonhart** [comment]
it means try mainline with multicore emulation disabled.

**Comment by LukasSo7th** [comment]
I tried but still the same :(

**Comment by Kelebek1** [comment]
Caused by async GPU, you can turn it off to have the game render, but there are other issues.
