### ISSUE TITLE
Luigi mansion 3 yuzu scarecraper problem

### ISSUE THREAD

**Issue by yuzuissueman** [yuzu-emu/yuzu#10653]
### Issue

Hello i have a problem with opening the scarescraper on luigi mansion 3.when i go to co op or online it get me a error.when i click co op it send me to activate the second player but i did that and it still happend again does anyone know this issue or is it possible to open the scarescraper?

**Comment by FearlessTobi** [comment]
Closing for use of wrong issue template.
