### ISSUE TITLE
The Legend Of Zelda:TOTK freezes in GameOver menu

### ISSUE THREAD

**Issue by AmiramJenab** [yuzu-emu/yuzu#10657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzo 1461

### Description of Issue

after pressing the continue button, the game just freezes and There is nothing to do and i should restart game when I die at game
![Screenshot (206)](https://github.com/yuzu-emu/yuzu/assets/135862936/56984a67-3574-4776-b0ff-459775085af5)

### Expected Behavior

What is expected is that the game starts after pressing the continue button

### Reproduction Steps

It happens all the time after the link's death

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11680168/yuzu_log.txt)

### System Configuration

CPU:Intel core i5 11400H
GPU/Driver: RTX 3050Ti Laptop
RAM: 16 GB
OS: Windows 11

**Comment by liamwhite** [comment]
issue is caused by mods
