### ISSUE TITLE
Regression - Mode button on the status bar is no longuer affected by the UI language

### ISSUE THREAD

**Issue by TheBoxyBear** [yuzu-emu/yuzu#10662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1461

### Description of Issue

Previously, running Yuzu in French would have the mode toggle on the status bar say "PORTABLE" and "MODE TV". As of now, the toggle reverts to the English labels "PORTABLE" and "DOCKED" when the rest of Yuzu is in French, either using the System setting or selecting the language manually.

### Expected Behavior

The labels are localized to "PORTABLE" and "MODE TV"

### Reproduction Steps

1. Set Yuzu's UI language to French of launch using the System language while the OS is set to French.
2. Notice the incorrect label on the status bar when in Docked mode.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11682951/yuzu_log.txt)

### System Configuration

CPU: Ryzen 7 2700X
GPU/Driver: RTX 3070
RAM: 16 GB
OS: Windows 11 Pro

**Comment by TheBoxyBear** [comment]
It seems the issue occurs regardless of the language chosen. The label is always in English.

**Comment by german77** [comment]
This is not an issue. The text was changed and a translation hasn't been submitted. Please wait until transifex uploads the new translation file.
