### ISSUE TITLE
Yuzu android using 0% gpu.

### ISSUE THREAD

**Issue by Rahulk120** [yuzu-emu/yuzu#10665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I just noticed that yuzu is using 0% gpu in android. Hope, yuzu will implement code for using gpu just like skyline.

### Why would this feature be useful?

![Screenshot_2023-06-08-09-23-59-38_ff30e97793d7c52fedd433a73d8d09b9](https://github.com/yuzu-emu/yuzu/assets/89052256/f66e215c-47df-41af-9da1-a3499ece7dc5)
![Screenshot_2023-06-08-09-24-30-99_ff30e97793d7c52fedd433a73d8d09b9](https://github.com/yuzu-emu/yuzu/assets/89052256/12433152-fb33-4f38-89f4-45acd3c8a506)

**Comment by liamwhite** [comment]
your system monitor overlay doesn't work correctly. everything you see is rendered with the gpu.
