### ISSUE TITLE
Outlast 2 deja de funcionar

### ISSUE THREAD

**Issue by Andrescorde** [yuzu-emu/yuzu#10664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

069d7e6be

### Description of Issue

El outlas 2 juego de caer el helicóptero al comienzo  del juego,este se sale de la aplicación, a pesar de que va a un buen rendimiento y con muy pocas fallas gráficas

### Expected Behavior

Avanzar sin ningún problema en la historia

### Reproduction Steps

Iniciar el juego abrir una nueva partida y esperar a que el helicóptero se caiga

### Log File

[   0.006355] Frontend <Info> main/jni/native.cpp:RunEmulation:429: starting
[   0.006653] Config <Info> main/jni/config.cpp:LoadINI:46: Successfully loaded /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/config/config.ini
[   0.006804] Frontend <Info> main/jni/emu_window/emu_window.cpp:EmuWindow_Android:58: initializing
[   0.007336] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.007346] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.007636] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007796] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.007939] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.008081] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.008237] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.008394] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.008540] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.008683] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.008837] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.009000] Input <Error> ./common/input.h:CreateDevice:473: Unknown engine name: joycon
[   0.011060] Common.Filesystem <Error> common/fs/file.cpp:Open:282: Failed to open the file at path=/storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/nand/system/save/8000000000000010/su/avators/profiles.dat, ec_message=No such file or directory
[   0.011095] Service.ACC <Warning> core/hle/service/acc/profile_manager.cpp:ParseUserSaveFile:364: Failed to load profile data from save data... Generating new user 'yuzu' with random UUID.
[   0.094202] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_conservative_rasterization
[   0.094221] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_depth_range_unrestricted
[   0.094223] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_extended_dynamic_state
[   0.094225] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_extended_dynamic_state2
[   0.094248] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_extended_dynamic_state3
[   0.094249] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_EXT_vertex_input_dynamic_state
[   0.094251] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_NV_geometry_shader_passthrough
[   0.094252] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_NV_viewport_array2
[   0.094253] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:798: Device doesn't support extension VK_NV_viewport_swizzle
[   0.094255] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:799: Missing required extension VK_EXT_robustness2
[   0.094259] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature customBorderColors
[   0.094260] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature extendedDynamicState
[   0.094262] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature primitiveTopologyListRestart
[   0.094263] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature provokingVertexLast
[   0.094264] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature timelineSemaphore
[   0.094266] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature transformFeedback
[   0.094267] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:865: Device doesn't support feature vertexInputDynamicState
[   0.094268] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature storageBuffer16BitAccess
[   0.094269] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature uniformAndStorageBuffer16BitAccess
[   0.094271] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature storageBuffer8BitAccess
[   0.094272] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature uniformAndStorageBuffer8BitAccess
[   0.094274] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature logicOp
[   0.094275] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature multiViewport
[   0.094276] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature wideLines
[   0.094277] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature nullDescriptor
[   0.094279] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature robustBufferAccess2
[   0.094280] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature robustImageAccess2
[   0.094281] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:866: Missing required feature shaderDemoteToHelperInvocation
[   0.094289] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:927: maxViewports has to be 16 or greater but it is 1
[   0.094290] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:349: Unsuitable driver, continuing anyway
[   0.094373] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:395: Qualcomm and Turnip drivers have broken VK_EXT_custom_border_color
[   0.094377] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:403: Qualcomm drivers have broken VK_EXT_extended_dynamic_state
[   0.094379] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:408: Qualcomm drivers have a slow VK_KHR_push_descriptor implementation
[   0.094382] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:Device:420: Patching Adreno driver to support BCn texture formats
[   0.095056] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:559: Driver does not support native BGR format
[   0.369049] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:157: Driver: Qualcomm Technologies Inc. Adreno Vulkan Driver 512.502.0
[   0.369069] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:158: Device: Adreno (TM) 640
[   0.369071] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:159: Vulkan: 1.1.128
[   0.369089] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:160: Available VRAM: 4.00 GiB
[   0.369180] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[   0.370213] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[   0.373457] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[   0.373513] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   0.373738] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[   0.373767] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   0.506097] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:128: Patching ExeFS for title_id=01003B200B372000
[   0.506308] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:175:     ExeFS: LayeredExeFS patches applied successfully
[   1.114250] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:299: Querying NSO patch existence for build_id=D33817C0C763D8FAF97D9A6534C19DB231FF7271
[   1.141282] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:299: Querying NSO patch existence for build_id=410FF5167BF6389285C54673DD775EC9
[   1.177869] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:299: Querying NSO patch existence for build_id=FA4141AE7E2F9F9D4066801DF626B06E552299E5
[   1.195021] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:299: Querying NSO patch existence for build_id=73F98F5F7A34D4C520BDA7C1A19CD9BDB3AE4F37
[   1.206735] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:299: Querying NSO patch existence for build_id=D95547528DCD684E2813EC83D338A47223C76865
[   1.318929] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontStandard' (0x0100000000000811).
[   1.321659] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.321787] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[   1.324466] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.324665] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[   1.325095] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.325353] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseTraditional' (0x0100000000000813).
[   1.325543] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.325658] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontKorean' (0x0100000000000812).
[   1.326723] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.326908] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[   1.327023] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.327034] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[   1.327050] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.332633] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontStandard' (0x0100000000000811).
[   1.332817] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.332909] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[   1.333289] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.333419] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[   1.333744] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.333855] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseTraditional' (0x0100000000000813).
[   1.333930] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.334002] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontKorean' (0x0100000000000812).
[   1.334135] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.334222] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[   1.334249] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.334257] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[   1.334264] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   1.566948] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   1.591104] Service.AM <Warning> core/hle/service/am/am.cpp:AcquireForegroundRights:93: (STUBBED) called
[   1.593062

### System Configuration

CPU:alcomm® Kryo™ 485, proceso de fabricación de 7 nm, CPU de ocho núcleos de hasta 2,96 GHz - Qualcomm® Adreno™ 640
GPU/Driver: Mesa Turnip 3D
RAM:8
OS:Android 13

**Comment by Squall-Leonhart** [comment]
Yuzu Lime is targetting Vulkan 1.3 devices, yours is 1.1.

**Comment by FearlessTobi** [comment]
We do not accept issue reports in foreign languages anyway.
