### ISSUE TITLE
YUZU ANDROID Screen and commands are not aligned on Samsung tab S8

### ISSUE THREAD

**Issue by jjaykkay222** [yuzu-emu/yuzu#10672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 069d7e6be

### Description of Issue

The commands show as horizontal while the game screen is vertical, there's no way to change the orientation manually.

### Expected Behavior

Comands and screen should be aligned 

### Reproduction Steps

Launching every game

### Log File

Don't know how to do it on android 

### System Configuration

CPU: octa 3gh
GPU/Driver:vulkan
RAM:8gb
OS: android 13

**Comment by tovarishes** [comment]
Same problem with the Surface Duo 2
Installed the latest Yuzu EA on a surface duo 2 but the screen is not shown in landscape but a squashed portrait while the on screen buttons are still landscape.
Another user has the same issue
https://www.reddit.com/r/surfaceduo/comments/13xke8q/running_yuzu_on_duo_2/

**Comment by librehat** [comment]
![Screenshot_20230610_122545_yuzu.png](https://github.com/yuzu-emu/yuzu/assets/1279432/567d57e5-cb56-4f6e-9db2-3220f044a97f)

Same problem here on Galaxy Tab S8. Latest version from Google Play as of today.

**Comment by bunnei** [comment]
Should be fixed

**Comment by librehat** [comment]
Can confirm on my device this is now fixed as of today
