### ISSUE TITLE
[Android] Yuzu struggles to run anything on snapdragon 720G

### ISSUE THREAD

**Issue by nitanmarcel** [yuzu-emu/yuzu#10681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Any

### Description of Issue

So I've just tested yuzu on my Redmi Note 9 Pro running a snapdragon 720g. Compared to skyline, yuzu it struggles to run anything. 

Tested with Cult of the Lamb, the game runs without any glitches, but the framerate sits around 15-20 fps. Now in the skyline emulator I'm using the 862 adreno driver which works amazingly fine for my device, getting rid of any shutters. But when it comes to yuzu I'm welcomed with a black screen and in game audio.

### Expected Behavior

Even if the phone is pretty old and under the recommended soc by yuzu, should run some games pretty fine, at least with the driver specified.

### Reproduction Steps

• Device specific, would need to run yuzu on the same device

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11704298/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 720
GPU/Driver: Adreno 618 / Qualcomm v682 Vulkan Driver
RAM: 6
OS: Android 13

**Comment by FearlessTobi** [comment]
Currently bad performance is to be expected on yuzu on phones.
The android port is still in early stages and many omptimizations haven't been made yet,
