### ISSUE TITLE
Bayonetta 3 crash

### ISSUE THREAD

**Issue by 645797945** [yuzu-emu/yuzu#10696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

3654EA

### Description of Issue

Bayonetta 3 has crashed in many versions, and selecting a chapter after entering the game will cause it to crash.

### Expected Behavior

Should not collapse

### Reproduction Steps

1. Run the game
2. Select Chapter
3. The number of frames changed to 0 during the loading process
4. Simulator crash

### Log File

No records

### System Configuration

CPU:AMD6800h
GPU/Driver:680m
RAM:16G
OS:win11

**Comment by FearlessTobi** [comment]
This is an issue tracker fir developers and not a support forum.
Please use our Discord for support requests,

Closing
