### ISSUE TITLE
Hyrule Warriors: Age Of Calamity crash when entering Zora's Domain for the first time.

### ISSUE THREAD

**Issue by AsrielDewitt** [yuzu-emu/yuzu#10695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1362

### Description of Issue

When entering the Zora's Domain for the first time and skipping the cutscene with Zelda, the game hung up and crash.

The last version of Yuzu that didn't result the crash was 1461 where it can enter Zora's Domain just fine
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11711583/yuzu_log.txt.old.txt)
 Here is the log for the version 1461, the log that is attached at the section for log is for 1462

### Expected Behavior

You should just enter into the main gameplay like normal

### Reproduction Steps

Create a new save, finish the 2 first mission and go to Zora's Domain.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11711581/yuzu_log.txt)

### System Configuration

CPU:Ryzen 5 4600h
GPU/Driver:GTX1650/532.03 
RAM:16GB
OS:Windows 11

**Comment by FearlessTobi** [comment]
Caused by https://github.com/yuzu-emu/yuzu/pull/10583.

**Comment by lat9nq** [comment]
@FearlessTobi was this issue resolved? Even though it is closed, I do not see a PR that resolves it, and I'm being asked to revert the linked PR.

**Comment by FearlessTobi** [comment]
@lat9nq Someone told me this was fixed now.

**Comment by lat9nq** [comment]
@gidoly with regards to https://github.com/yuzu-emu/yuzu/pull/10583#issuecomment-1585507466 can you comment whether this is the issue you were referring to, and possibly if it's still current?
