### ISSUE TITLE
Missing dll File preventing Yuzu from opening

### ISSUE THREAD

**Issue by Logobot757** [yuzu-emu/yuzu#10704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Whatever the latest one is.

### Description of Issue

It says "MSVCP140_ATOMIC_WAIT.dll was not found." 
I have no idea how to fix this. I have C++ on this pc. Anyone know how to fix this?

### Expected Behavior

It should boot up like normal.

### Reproduction Steps

I have no clue,

### Log File

I have no idea where to find the log.

### System Configuration

CPU: Unknown.
GPU/Driver: Idk, but i know its good enough
RAM: 16GB if i remember correctly
OS: Windows 11

**Comment by BaccarWozat** [comment]
I've got nine copies of that file on my HD, most of them are in a build of Stable Diffusion. The file varies from 48kb to 56kb. I wouldn't know where it goes for Yuzu, doesn't seem to be part of the downloaded package. Possibly it uses the one I have on windows\system32.

**Comment by Squall-Leonhart** [comment]
This file is installed into the WinSxS and hardlinked from the System32 folder, it is installed by the Visual C 2015-2022 Redistributable.

while it can be served alongside software such as StableDiffusion, it should not be, but since when are opensource devs known to follow best practices. :D
