### ISSUE TITLE
Cant Add Game

### ISSUE THREAD

**Issue by Logobot757** [yuzu-emu/yuzu#10707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Whatever the latest one is.

### Description of Issue

![Screenshot (1)](https://github.com/yuzu-emu/yuzu/assets/74375048/ab666d26-e725-48d8-b0a3-969f7be3e8cc)
I'm just trying to add MK8DX but this keeps happening.

### Expected Behavior

It should install.

### Reproduction Steps

Try to add MK8DX to your games.

### Log File

I have no idea where to find said log.

### System Configuration

CPU: Unknown, but powerful enough
GPU/Driver: NVIDIA something, its good enough
RAM: 16GB if I remember correctly.
OS: Windows 11

**Comment by german77** [comment]
Update lockpick and dump the latest keys from your switch. Base games aren't installed just updates. For more help ask in discord or citra forum. This isn't a support channel.
