### ISSUE TITLE
Motion unable to be detected while using Nintendo Switch Pro Controller

### ISSUE THREAD

**Issue by bwmgd** [yuzu-emu/yuzu#10708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access  3659 

### Description of Issue

My controller's motion is available in version Early Access 3629. But it's not identifiable right now. My controller is ZD-O Plus CONTROLLER. Use ns mode.

### Expected Behavior

The motion can be detect.

### Reproduction Steps

It can be detected in version 3629 that a direct upgrade to version 3659 is still available. But after disconnecting, it can no longer be connected. I have tried to reconnect the handle and restart the computer, but none of them can detect the motion.
The motion is always available in version 3629.

### Log File

![image](https://github.com/yuzu-emu/yuzu/assets/40416231/6b91d42b-4de5-4c0e-a16d-5ba32ee7e502)

### System Configuration

CPU: 12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
GPU/Driver: NVIDIA GeForce RTX 3070 Ti Laptop GPU
RAM: 32G
OS: Windows11

**Comment by Squall-Leonhart** [comment]
connected by usb or bluetooth?

**Comment by bwmgd** [comment]
> connected by usb or bluetooth?

by Bluetooth

**Comment by Squall-Leonhart** [comment]
See: https://github.com/libsdl-org/SDL/issues/7577

**Comment by MikhailVector** [comment]
same here. bluetooth - controller "Nintendo Switch Pro" - motion has worked flawlessly for long time. since the last few updates i have to start CEMU & breath of the wild, then close it and then start yuzu and re-select the "Nintendo Switch Pro" controller to make it work. if i dont start CEMU before, YUZU wont detect motion. its weird.

**Comment by Squall-Leonhart** [comment]
1.28.0 is getting a prerelease sometime this week, users can test the SDL2.dll from the Release package (replace yuzu's existing one) to see if the issue is resolved.

**Comment by bwmgd** [comment]
> 2.28.0 is getting a prerelease sometime this week, users can test the SDL2.dll from the package (replace yuzu's existing one) to see if the issue is resolved.

I replace the SDL2.dll it works at [2.28.0 RC1](https://github.com/libsdl-org/SDL/releases/tag/prerelease-2.27.1). Thank you very much
