### ISSUE TITLE
Android: Update yuzu bot, and improve logging/sharing options

### ISSUE THREAD

**Issue by sharpy66** [yuzu-emu/yuzu#10709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Update the yuzu discord bot to show the specifications and driver of the device, similar to how the logs already work on windows.

This would also require adding the necessary information to the android logs.

Additionally the current option to share logs could be improved to allow for direct sharing to the #android-support channel on the yuzu discord server. (Although this would be somewhat redundant as you could already just share the file manually)

### Why would this feature be useful?

This would allow people to more easily diagnose problems and provide support on the yuzu discord server, allowing people to avoid the tedious dialog of "What device? - Galaxy a01s - unsupported device." As people could instead ask them to press the share log button in the yuzu app, and have all relevant technical information provided to them.

**Comment by FearlessTobi** [comment]
Please open this issue again in the repository of our discord bot.
https://github.com/citra-emu/discord-bot
