### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by kkxiegouquan** [yuzu-emu/yuzu#10715]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Affected Build(s)

yuzu Android 4ea7da1

### Description of Issue

Mesa Turnip always crashes before starting the game.
I've tried all the radish drivers.
My phone can't upgrade to Android 13
Hope the yuzu team can fix the bug that Android 11 and 12 don't support radish drivers?
thank you

### Expected Behavior

run the game

### Reproduction Steps

Install Turnip drivers
Run a game
Crash

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11714245/yuzu_log.txt)

### System Configuration

CPU:Snapdragon 870
GPU/Driver:650
RAM:8gb
OS:Android 11

**Comment by Squall-Leonhart** [comment]
Duplicate #10629

**Comment by kkxiegouquan** [comment]
> 复制#10629

I just hope to fix that Android 11 and 12 don't support radish drivers

**Comment by FearlessTobi** [comment]
This is an issue tracker for developere and not a support forum.
Please use our Discord for support requests.

Closing
