### ISSUE TITLE
Yuzu crashes upon loading my mod (works with Ryujinx)

### ISSUE THREAD

**Issue by SilentStorm-1986** [yuzu-emu/yuzu#10722]
### Issue

The interesting thing is that the emulator will crash even before starting the game if I right click properties on the game title with my mod in the yuzu mod folder. My mod has thousands of files, so I was thinking that might have something to do with it.

The mod is tested as working on Ryu.

As a side note, does Yuzu do ASTC decoding on the CPU or GPU?

Thanks in advance.

**Comment by FearlessTobi** [comment]
I am going to close this for a lack of information and the wrong template.
You have not even linked the mod you were using. It is very hard to reproduce anything without more information.

**Comment by SilentStorm-1986** [comment]
It's a mod that I created and I have some development experience (including making a custom build of yuzu), so this is not a mislabeled template. The mod is not released yet, so it would not be possible to reproduce. I've made another mod that contains thousands of files and it works fine (very similar kind of mod).

To give more information:
Breath of the Wild mod: 3,677 files and larger total file size (works)
Tears of the Kingdom mod: 9,966 files and smaller total file size (does not work).

**Comment by gidoly** [comment]
It has to do with windows file limits. Ryujinx doesn't have issue cuz c# libary allows 2 times of file (16000 ish)of c++libary does

**Comment by SilentStorm-1986** [comment]
Thanks for the answer. Can you tell me which class handles the parsing of mod files?

**Comment by liamwhite** [comment]
@SilentStorm-1986 please check if this branch allows loading your mod: https://github.com/liamwhite/yuzu/tree/windows-is-a-meme

If it does I will PR it.

**Comment by SilentStorm-1986** [comment]
Was I supposed to build this from: https://github.com/liamwhite/yuzu.git ?

If so it doesn't seem to work either. Thanks though

**Comment by gidoly** [comment]
do this

git remote add liamwhite https://github.com/liamwhite/yuzu.git

git fetch liamwhite

git checkout windows-is-a-meme

**Comment by SilentStorm-1986** [comment]
I can confirm that the windows-is-a-meme build fixes the file limit problem. Will this be pushed to the main commit?
