### ISSUE TITLE
Android Yuzu graphics is broken when using FXAA anti-aliasing method

### ISSUE THREAD

**Issue by tovarishes** [yuzu-emu/yuzu#10730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access ea716eb5cc

### Description of Issue

Whenever FXAA anti-aliasing method is chosen in Graphics Options the video is garbled and messy. This wasn't the case in previous builds.
This problem happens in three different devices with Snapdragon 8 Gen2, 888 and 865 processors on Android 12 and 13

### Expected Behavior

![yuzu](https://github.com/yuzu-emu/yuzu/assets/17121747/78ece436-6538-49f4-8210-b69dc67dc81d)

### Reproduction Steps

Select FXAA anti-alias method in graphics options

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11718292/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 8 Gen 2
GPU/Driver: Adreno 740, System Driver
RAM: 12GB
OS: Android 13

**Comment by chostdz** [comment]
Thats happened to me too

**Comment by Squall-Leonhart** [comment]
Whats the chance https://github.com/yuzu-emu/yuzu/pull/10670 regressed this @liamwhite

**Comment by tovarishes** [comment]
Mesa drivers just crash in the three devices that I have.
