### ISSUE TITLE
ASTC Texture Recompression Glitch

### ISSUE THREAD

**Issue by SilentStorm-1986** [yuzu-emu/yuzu#10745]
### Issue

There is an issue with recompression causing severe artifacts for a few seconds before correcting itself.

Here's a screenshot of the TotK loading screen map with texture recompression set to BC3:
![image_2023-06-12_200034594](https://github.com/yuzu-emu/yuzu/assets/100206842/976a88a7-3911-4422-ba0e-b8ab0f047921)

Here's a screenshot of distorted z-axis textures in-game:
![screenshot_distorted_z-axis](https://github.com/yuzu-emu/yuzu/assets/100206842/ef52ef0b-ec1f-4502-a28f-5e1d3ddbb618)

**Comment by gidoly** [comment]
can you post log and provide system spec

**Comment by gidoly** [comment]
also see if it happen with asynchrnous astc decoding off

**Comment by SilentStorm-1986** [comment]
The issue still happens with asynchronous decoding turned off. This is the log from before I turned off asynchronous decoding (system specs are in the log)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11729209/yuzu_log.txt.old.txt)

**Comment by gidoly** [comment]
log says async astc is on

**Comment by SilentStorm-1986** [comment]
> > log says async astc is on
> This is the log from before I turned off asynchronous decoding 

As I said I tried both and the glitch still occurs. I suspect the issue is reproducible?

**Comment by gidoly** [comment]
it is not sadly

**Comment by SilentStorm-1986** [comment]
Did you try with a recent build? I found this issue on a few builds including 1465 and 1467. Are you using a recent Nvidia card?

**Comment by liamwhite** [comment]
Make sure `Decode ASTC textures asynchronously` is disabled in both global and per-game settings. That option causes this specific graphical issue.

**Comment by SilentStorm-1986** [comment]
Fixed! I'll close this issue.
