### ISSUE TITLE
Feature Request for Audio Functionality

### ISSUE THREAD

**Issue by ameameam3** [yuzu-emu/yuzu#10742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

"Restart Audio" button, or better audio device tracking/management during emulation.

### Why would this feature be useful?

When the main audio device disconnects, Yuzu stops outputting audio to it, even if it reconnects. Perhaps this can be managed by buffering the sound into a different stream that is then played into the output? (managed by Yuzu obviously) I have to mute my pc sometimes and don't have the time to pause the emulator, so it results in audio dropping mid-cutscene and otherwise.

**Comment by Squall-Leonhart** [comment]
it simply needs to have the api's endpoint notification implemented.

**Comment by FearlessTobi** [comment]
Closing in favor of https://github.com/yuzu-emu/yuzu/issues/10800 which suggests a better solution.
