### ISSUE TITLE
Blossom tales 1 & 2 running with black screen (Android)

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#10748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Acces bcdd35e8be

### Description of Issue

In this update the games running with a black screen, the sound is heard but everything is black

### Expected Behavior

this should not happen

### Reproduction Steps

just start the game

### Log File

blossom tales 1
[yuzu_log_blossom tale 1.txt](https://github.com/yuzu-emu/yuzu/files/11730336/yuzu_log_blossom.tale.1.txt)

blossom tales 2
[yuzu_log_blossom tale 2.txt](https://github.com/yuzu-emu/yuzu/files/11730339/yuzu_log_blossom.tale.2.txt)

### System Configuration

CPU: sd860
GPU/Driver: adreno 640/ turnip driver
RAM: 8gb
OS: android 13

**Comment by rassoc** [comment]
Same issue on non-android with latest flatpak version (1546) on OpenSUSE Tumbleweed and Radeon RX 6400. 
Inputs are working, can hear the menu sounds, but screen stays black.

**Comment by brujo5** [comment]
Fixed with android builf v94

![Screenshot_20231007-191606_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/dbac3953-8b4d-436c-ad69-6094c4ce2d64)
![Screenshot_20231007-191528_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/82f18725-02a0-40db-bac0-d4fdd760a0e5)
