### ISSUE TITLE
zelda totk crash in a cutscene  after getting tulin's tear

### ISSUE THREAD

**Issue by rookieplayi** [yuzu-emu/yuzu#10741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early acces 3695

### Description of Issue

so after beating colgera and obtaning the tear there will be a specific cutscene where rito village is no longer in danger but  a second before the cutscene happens the game crashes in the middle of a shader building that caused a shader corrruption i already tried deleting shaders but didnt work                  i already enabled compute pipeline and it worked on my intel gpu         btw the log does not contain any device loss

### Expected Behavior

no more crash

### Reproduction Steps

fix the cutscene crash

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11725194/yuzu_log.txt.old.txt)

### System Configuration

CPU: i3 8th gen
GPU/Driver: intel uhd 630
RAM: 8gb dual channel
OS: win11 22h2

**Comment by liamwhite** [comment]
Try deleting %appdata%/yuzu/shader/0100f2c0115b6000/vulkan_pipelines.bin while yuzu is closed and then trying again?

**Comment by rookieplayi** [comment]
> Try deleting %appdata%/yuzu/shader/0100f2c0115b6000/vulkan_pipelines.bin while yuzu is closed and then trying again?

still crashes because the shader cache itself is corrupted after the cutscene crash  even if i try deleting teh shaders again it will do the same thing

**Comment by rookieplayi** [comment]
> Try deleting %appdata%/yuzu/shader/0100f2c0115b6000/vulkan_pipelines.bin while yuzu is closed and then trying again?

ive managed to load the corrupted shaders by disabling vulkan pipelines but the game still crashes seconds before the rito village cutscene plays       heres the error i think                 [ 445.306994] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame dimensions 1920x1080 don't match surface dimensions 1920x1088
 i dont know what this is

**Comment by rookieplayi** [comment]
> Try deleting %appdata%/yuzu/shader/0100f2c0115b6000/vulkan_pipelines.bin while yuzu is closed and then trying again?

i tried disabling astc   and it still didnt work      im stuck now

**Comment by rookieplayi** [comment]
> Try deleting %appdata%/yuzu/shader/0100f2c0115b6000/vulkan_pipelines.bin while yuzu is closed and then trying again?

im stuck now in the wind temple because the game crashes seconds before the rito village cutscene      you know what i mean

**Comment by rookieplayi** [comment]
> Try deleting %appdata%/yuzu/shader/0100f2c0115b6000/vulkan_pipelines.bin while yuzu is closed and then trying again?

nevermind i fixed it by disabling compute pipelines

**Comment by Merken1** [comment]
i have the exact same issue but the pipelines thing doesnt work
