### ISSUE TITLE
DLCs won't load on Samsung Galaxy S23 Plus on Yuzu Android

### ISSUE THREAD

**Issue by Raistlin43** [yuzu-emu/yuzu#10758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

bcdd35e8be

### Description of Issue

In the latest Update it supposedly has support for DLCs, however on my Samsung Galaxy S23 Plus it does not load DLCs for games that are updated to the latest version. It only gives me the option to update them through Yuzu one at a time. However, even though I have the latest version of Dragon Ball fighter Z already patched it shows up as a base game with no DLCs. Thanks

### Expected Behavior

I have my games already patched to the latest version but Yuzu Android only loads them in base mode.

### Reproduction Steps

Use any game that is up to date on Yuzu for PC in any format and put it into Yuzu for Android. Only the base version is read (at least on my S23 Plus).

### Log File

[yuzu_log (1).txt](https://github.com/yuzu-emu/yuzu/files/11736340/yuzu_log.1.txt)

### System Configuration

CPU: 8 Gen 2 (S23 Plus)
GPU/Driver: Adreno 740
RAM: 8
OS: Android 13

**Comment by FearlessTobi** [comment]
The updates and DLCs installed on yuzu Desktop are not stored in the game file itself.
Therefore they need to be reinstalled on the Android build as well.
