### ISSUE TITLE
Graphical glitches when playing TLOZ Skyward Sword on Vulkan API

### ISSUE THREAD

**Issue by 4njik** [yuzu-emu/yuzu#10753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu 1467

### Description of Issue

There have been issues with The Legend Of Zelda Skyward Sword since the latest updates. I saw a similar error only in posts about intel gpu, but I have an rx 6600 and I just scored on it while waiting for it to be fixed. 

But after a while, when playing the same Zelda, I had incidents similar to the death of a video card. As it turned out later, this only happens when playing yuzu and (seemingly) is not connected with the video card, but at the same time affects the entire computer image (both monitors).

The last time I didn't have an earlier save in the game, I had to run the one shown in the screenshot. This caused a repeat of the broken screens. At the same time, this does not happen when entering through openGL, but I can’t play on it due to bad fps.

![IMG_20230611_150602](https://github.com/yuzu-emu/yuzu/assets/136436507/f5f2743b-ae0c-4a0c-86b5-b28063866f50)
![IMG_20230613_143709](https://github.com/yuzu-emu/yuzu/assets/136436507/9de8c146-7c0d-4db6-a481-9eff90368918)
![image](https://github.com/yuzu-emu/yuzu/assets/136436507/735baf33-5771-4920-abf6-704ff58ddda5)

### Expected Behavior

broke screens

### Reproduction Steps

Just play sometimes on vulkan API

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11732226/yuzu_log.txt.old.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11732227/yuzu_log.txt)

### System Configuration

CPU: ryzen 7 2700
GPU/Driver: rx 6600
RAM: 16gb 3200 Mgz
OS: windows 10 (last)

**Comment by FearlessTobi** [comment]
Since the problem affects both screens and not only yuzu, it has to be an issue with your video card or its driver.
Please contact your manufacturer about it.

Closing

**Comment by goldenx86** [comment]
Try disabling accelerate ASTC texture decoding, maybe the driver degraded in compute again.
