### ISSUE TITLE
TOTK stuck/crash on Launching screen only on 3667

### ISSUE THREAD

**Issue by formaldehydeson** [yuzu-emu/yuzu#10750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3667

### Description of Issue

Works fine on 3663 and mainline, TOTK version 1.1.2. All mods disabled. Shaders load in fine then it just gets stuck on the Launching screen and it shows a crash in the logs 
```[  15.374690] Core.ARM <Critical> core\arm\dynarmic\arm_dynarmic_64.cpp:ExceptionRaised:150: Cannot execute instruction at unmapped address 0x00000000000000
[  15.374692] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:82: Backtrace, sp=000000100DC58C90, pc=0000000000000004
...
```

### Expected Behavior

Should launch the game into the main menu

### Reproduction Steps

Open Yuzu and try and load TOTK from the main screen

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11730728/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 9 7900x
GPU/Driver: NVIDIA RTX 3070 version 535.98 (latest)
RAM: 32GB
OS: Windows 11

**Comment by travellerse** [comment]
I ran into the same problem, in yuzu EA3667, TOTK update1.1.1 didn't seem to load properly and the game version was shown as 1.0.0

**Comment by gidoly** [comment]
uninstall game update and reinstall

**Comment by lordtomtom** [comment]
Removing and reinstalling the game update had no effect for me. Once the game launches, it changes the version description on the newly installed update from 1.1.2 to 0.4.

**Comment by formaldehydeson** [comment]
fixed in 3673
