### ISSUE TITLE
[Android] Introduce a language selector within the app

### ISSUE THREAD

**Issue by marcoslpaulo** [yuzu-emu/yuzu#10756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Introduce a way to have the app in a different language than the one the OS uses

### Why would this feature be useful?

Would allow the user to have the app in english even when their default language is set to a different one, avoiding broken/ incomplete translations

**Comment by FearlessTobi** [comment]
The app translation is handled automatically by the Android OS and not by us.
Beginning from Android 13, Google provides the option to set a different language for each app manually.
