### ISSUE TITLE
[Android] Scan subdirectories in games folder

### ISSUE THREAD

**Issue by Raxcoms** [yuzu-emu/yuzu#10755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Scan subdirectories in the defined game directory

### Why would this feature be useful?

Games organized in folders containing base game, update and dlcs would populate the games list

**Comment by SpideyPlayz** [comment]
I was surprised that this was missing from the Android version

**Comment by NightK15** [comment]
It would also be nice to add multi-folder scan support, so that ROMs from different folders can be all loaded in the same list.

**Comment by FearlessTobi** [comment]
Fixed by https://github.com/yuzu-emu/yuzu/pull/11352.
