### ISSUE TITLE
[Android] Allow batch install of multiple dlcs

### ISSUE THREAD

**Issue by Raxcoms** [yuzu-emu/yuzu#10757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Allow selecting multiple dlcs to be installed at once

### Why would this feature be useful?

Would facilitate installing dlcs for games that have a bunch of it (i.g. SSBU)

**Comment by AbandonedCart** [comment]
I got you, buddy. ;)

**Comment by t895** [comment]
Addressed by #10794
