### ISSUE TITLE
Wiki changes (No PR options)

### ISSUE THREAD

**Issue by AbandonedCart** [yuzu-emu/yuzu#10768]
### Issue

[_Sidebar.md](https://github.com/yuzu-emu/yuzu/files/11741050/_Sidebar.md)

If you use relative links to the wiki, it allows changes to be viewed on a fork for testing secondary pages

[Building-For-Android.md](https://github.com/yuzu-emu/yuzu/files/11744839/Building-For-Android.md)

Android also requires install Visual Studio on Windows or vcpkg installation fails because it's configured as integrated. The Vulkan SDK is required for gslangValidator or it will fail for the missing binary.

Understandably, most people building Android previously built some other platform. On a fresh build setup for Android, though, the prerequisites from other builds won't already exist.

**Comment by FearlessTobi** [comment]
Thanks!

I have made the changes you suggested :)

**Comment by AbandonedCart** [comment]
Not sure if you want to really get into specifics, but I also found an absolute minimum number of C++ items for Visual Studio. It only really matters if you are limited on space, though (building on a ROG Ally lol)

**Comment by AbandonedCart** [comment]
Fair enough. I figured it out and my last experience with Windows was Windows 2007 lol.
