### ISSUE TITLE
Yuzu does not show DLC from games that have previously been updated with NCS Builder

### ISSUE THREAD

**Issue by Raistlin43** [yuzu-emu/yuzu#10762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

bcdd35e8be

### Description of Issue

I have in my PC the games previously updated with all their DLCs in a single .NSP or XCI file thanks to the NCS Builder tool. The problem is that this latest Yuzu update is supposed to detect and install the DLCs but the games I have updated to the latest version with this tool the emulator only shows their base version and not the updates. This does not happen in the PC version that detects all the DLCs directly patched in a single file with NCS Builder, could you solve it, I do not mean to install the DLCs one by one, I mean the games that are patched with their last update in a single file, that Yuzu Android detects it as a base file, I do not know if I explain. Greetings and thanks.

### Expected Behavior

I would like (if possible) that the games I have already patched and updated to the latest version it detects them as such in Yuzu Android just like Yuzu PC does. Thank you.

### Reproduction Steps

Removed.

### Log File

Nothing

### System Configuration

CPU: Snapdragon 8 Gen 2
GPU/Driver: Adreno 740 Turnip 7XX
RAM: 8Gb
OS: Android 13

**Comment by goldenx86** [comment]
We won't provide support on piracy.
