### ISSUE TITLE
Dreamlight Valley Graphic bug

### ISSUE THREAD

**Issue by UncleDirty1988** [yuzu-emu/yuzu#10778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1467

### Description of Issue

In Disneys Dreamlight Valley there's a graphic bug that causes items to light up in various colors instead of the color/s the item should have. There's also trees having weird shapes and also colors which appears to be a bug. I've tried switching from Vulkan to OpenGL as one of the Mods suggested but it didn't help. The only thing that happend was that the performance got worse. For a visualisation of the bugs I took a Screenshot. 
![grafikfehler](https://github.com/yuzu-emu/yuzu/assets/136642718/45cc418c-e892-4441-ae30-874ab9ec0414)

### Expected Behavior

The colors should appear correct and the shape of the trees should be normal. 

### Reproduction Steps

Simply start the game. :D 

### Log File

Removed.

### System Configuration

CPU: AMD Ryzen 7 2700X
GPU/Driver: NVIDIA GTX 1060/ latest
RAM: 16GB 
OS: Windows 10

**Comment by goldenx86** [comment]
Sorry, we can't help with piracy.
