### ISSUE TITLE
TotK: AA not working

### ISSUE THREAD

**Issue by Tobia12** [yuzu-emu/yuzu#10779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Every build

### Description of Issue

I have an issue that AA doesn't work in totk, no matter what I do. It started yesterday, not being able to turn on anti-aliasing. So I tried going to an older version, but it didn't work. I tried setting it to the mainline version, and of course, it didnt work. So then i proceeded to uninstall the emulator and run the game in its most basic config. After that, i checked my settings in nvidia control panel. I installed new GPU drivers to see if there is some problem there but it still didn't fix the issue. So I tried to run another game but everything works fine. I tried some mods that someone suggested to try, but it still didn't fix the issue. Here is a quick video showing my problem:

https://github.com/yuzu-emu/yuzu/assets/25201567/a438feb8-9b1a-430f-9db5-b34bc218c216

Here is my mod list:

![Desktop Screenshot 2023 06 14 - 22 15 58 60](https://github.com/yuzu-emu/yuzu/assets/25201567/20d64291-8483-45f2-b823-14088960f62b)

### Expected Behavior

working AA

### Reproduction Steps

I don't really know what's causing it.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11750222/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7 5700X
GPU/Driver: Nvidia RTX 2060 super
RAM: 16 gb
OS: Windows 11 22H2

**Comment by german77** [comment]
Piracy is not allowed
