### ISSUE TITLE
Hello, I don’t know if yuzu can be emulated on Android 10, but maybe there is a possibility.

### ISSUE THREAD

**Issue by eduardorangelr2r2** [yuzu-emu/yuzu#10784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Hello, I am an Android 10 user and I would love to be able to emulate yuzu on my device. I know that there are powerful phones with 4 to 8 GB of RAM and processors like the snapdragon 845 that could run some Nintendo Switch games. Even though they don’t have the performance of a high-end device or meet the requirements that they say on the website to install yuzu on Android, I think they deserve a chance. Many developers like LG have not updated their phones to Android 11 or other brands, but they are good phones. They are not old phones but high-end ones from 4 years ago that have enough power to run the games efficiently, not as much as you could with a high-end device from past years or this year. Please consider integrating your Android 10 base app so that more users can enjoy yuzu.

### Why would this feature be useful?

Hello, I am an Android 10 user and I would love to be able to emulate yuzu on my device. I know that there are powerful phones with 4 to 8 GB of RAM and processors like the snapdragon 845 that could run some Nintendo Switch games. Even though they don’t have the performance of a high-end device or meet the requirements that they say on the website to install yuzu on Android, I think they deserve a chance. Many developers like LG have not updated their phones to Android 11 or other brands, but they are good phones. They are not old phones but high-end ones from 4 years ago that have enough power to run the games efficiently, not as much as you could with a high-end device from past years or this year. Please consider integrating your Android 10 base app so that more users can enjoy yuzu.

**Comment by gidoly** [comment]
we are not going to support android 10
