### ISSUE TITLE
Android: add "Out of memory" error for not enough RAM available

### ISSUE THREAD

**Issue by EddyHg80** [yuzu-emu/yuzu#10789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Instead of just crashing and going back to the title selection without knowing why, add a message to let the user know the device has not enough RAM available.

### Why would this feature be useful?

I have a SD865+ device with 6GB of RAM, and I've been told on Discord that the reason I cannot get any game to boot is that the emulator is optimized for 8GB only, for now.

So yeah a small message to let the user know what's going on may be useful, and would have spared me some troubleshooting.

BTW thank you for your work, you are amazing!

**Comment by EddyHg80** [comment]
> out of memory already available in log file

That doesn't sound like a really good user experience to me, especially on Android :(

**Comment by t895** [comment]
Addressed by #10869
