### ISSUE TITLE
jogo pokemon sword e shield travam apos um tempo de jogo!!!!

### ISSUE THREAD

**Issue by moshreis** [yuzu-emu/yuzu#10805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

após um tempo de jogo nopokemon  shield e no sword o jogo trava e o yuzu fecha.

### Description of Issue

após um tempo de jogo nopokemon  shield e no sword o jogo trava e o yuzu fecha começou ocorrer isso apos a atualização 1470.

### Expected Behavior

a

### Reproduction Steps

a

### Log File

aaa

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by FearlessTobi** [comment]
Spam
