### ISSUE TITLE
Vulkan Rendering Fails on Momotaro Dentetsu

### ISSUE THREAD

**Issue by JWatersMeet** [yuzu-emu/yuzu#10803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1471

### Description of Issue

Momotaro Dentetsu freezes when loading on a white screen when using the Vulkan renderer. This hard-locks Yuzu, which then has to be quit from Task Manager using the 'End Process Tree' option.

This does not occur when using OpenGL.

### Expected Behavior

Momotaro Dentetsu should load successfully using Vulkan.

### Reproduction Steps

Set output type to Vulkan, load Momotaro Dentetsu, notice white screen and Yuzu frozen.

### Log File

[yuzu_log_momotaro.txt](https://github.com/yuzu-emu/yuzu/files/11771417/yuzu_log_momotaro.txt)

I believe the key error is:

HW.GPU <Warning> video_core/texture_cache/texture_cache.h:RefreshContents:977: MSAA image uploads are not implemented

### System Configuration

CPU: Ryzen 5900HX
GPU/Driver: RTX 3080 with 
RAM: 31.0.15.3118
OS: Windows 11

**Comment by FernandoS27** [comment]
hmn [  68.491966] Debug <Critical> video_core\renderer_vulkan\vk_texture_cache.cpp:operator ():1249: Assertion Failed!
Copying images with different samples is not implemented in Vulkan.

**Comment by JWatersMeet** [comment]
Not sure which PR fixed this, but it's now working fine on Vulkan in the latest EA. Many thanks!
