### ISSUE TITLE
Xenoblade Chronicles 2 crashes when skipping a cutscene on EA3686

### ISSUE THREAD

**Issue by crisdiaz-github** [yuzu-emu/yuzu#10812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early access 3686

### Description of Issue

The emulator crashes if you skip a cutscene in the Events Theater.

It works correctly in EA 3685, EA 3677 and EA 3670.

### Expected Behavior

Skipping cutscenes should not make the emulator crash. :D

### Reproduction Steps

1.Start the game and go to the Events Theater
2.For example, open the third cutscene from Chapter 1
3.Skip the cutscene
4.Crash happens

### Log File

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/11777622/yuzu_log.zip)

Last log lines:
[  67.698441] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:586: 0x2020751716c2158a
[  67.701795] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:586: 0x0b333831076cb52e
[  67.702099] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:586: 0xb98158627303c1a3
[  67.705997] Render.Vulkan <Inf

It seems to cut in the middle of the last line and i don't see any error in the entire log...

### System Configuration

CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz | AVX
GPU/Driver: NVIDIA GeForce GTX 1060 6GB/NVIDIA Driver 516.94.0.0
RAM: 7.90 GiB
OS: Windows 10 Version 21H2 (Build 19044.2965)

**Comment by Squall-Leonhart** [comment]
update the video driver. 516 has crashes and graphical issues.

**Comment by crisdiaz-github** [comment]
> update the video driver. 516 has crashes and graphical issues.

Oh I thought that v516 was the correct one for the 1000 series for Yuzu. What driver is recommended?

I will try with the recommended driver and see if it crashes, but I believe this issue is related to EA3686 because I have no crashes in other builds.

**Comment by crisdiaz-github** [comment]
Just tried EA3690 and everything is working fine.
I guess I'll wait for a few EA builds before opening an issue next time.
