### ISSUE TITLE
Yuzu save file corrupt if loading via cmd line arg, restart of emulation solves issue

### ISSUE THREAD

**Issue by lawhazl** [yuzu-emu/yuzu#10810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1431

### Description of Issue

When loading a game via command line arguments, game loads up and says save game file corruption.

If restart emulation the save game loads totally  fine.

### Expected Behavior

When loading from  command line arguments game loads up without any issue

### Reproduction Steps

start game using command line arguments from a shortcut

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11776671/yuzu_log.txt)

### System Configuration

CPU:  AMD Ryzen 9 5950X
GPU/Driver: NVIDIA 3090 / 535.98
RAM: 16GB
OS: Windows 11

**Comment by Squall-Leonhart** [comment]
I think the update is not being loaded when you start via command line

**Comment by FearlessTobi** [comment]
Closing as duplicate then.
