### ISSUE TITLE
Vulkan Device Loss in fe3h after 3601 ("Barrier feedback loops" option didn't fix it for me)

### ISSUE THREAD

**Issue by louislam125** [yuzu-emu/yuzu#10816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3689

### Description of Issue

Game's running good in 3601 but later builds ramdomly cause device loss which fe3h freezes in loading screen most of the time.
There's a new "Barrier feedback loops" option in the latest ea builds and it solved some people's device loss I believe but not mine. 
The log file below is with the option unchecked.

### Expected Behavior

Game should not freeze during loading screen.

### Reproduction Steps

Play the game for a while. Then the game will freeze usually during loading screen after fast travel, cutscenes and coming back from missions sometime. 

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11778750/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 9 6900HX with Radeon Graphics 3.30 GHz
GPU/Driver: Geforce RTX 3080 laptop GPU/ 535.98
RAM: 16GB
OS: Win 11

**Comment by gidoly** [comment]
3602 merged barrier feedback loop change for first time. so turning off will fix your device loss too

**Comment by louislam125** [comment]
> 3602 merged barrier feedback loop change for first time. so turning off will fix your device loss too

I tested with the new option in the 3689 build both enabled and disabled. And it's didn't solve my case.

**Comment by Squall-Leonhart** [comment]
> 3602 merged barrier feedback loop change for first time. so turning off will fix your device loss too

Lois has the issue reported by Neko in https://github.com/yuzu-emu/yuzu/issues/10660
