### ISSUE TITLE
Support native ASTC textures on M1/M2 GPUs

### ISSUE THREAD

**Issue by DamianPereira** [yuzu-emu/yuzu#10826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Apple sillicon GPUS natively support ASTC textures according to [this table](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf) and this [wikipedia article](https://en.wikipedia.org/wiki/Adaptive_scalable_texture_compression) (keep in mind m1/m2 desktop cpus are a14/a15 gpus, so feature set is shared according to apple itself).

Vulkan itself also seems to support ASTC textures, according to [this](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_texture_compression_astc_hdr.html), not completely sure though, I'm not familiar enough with vulkan to understand it.

So in theory, yuzu on mac could upload ASTC textures directly, without decoding and re-encoding. I don't know if MoltenVK needs to add support for ASTC textures as well, or if it's already there.

### Why would this feature be useful?

This would greatly improve VRAM consumption on mac, and probably benefit performance substantially. I don't know how much when compared with gpu accelerated decoding and cpu re-encoding though.

**Comment by DamianPereira** [comment]
I was under the impression that an experimental mac version could be installed, from this wiki page: https://yuzu-emu.org/wiki/building-for-macos/

Is it the case? Or is a mac version still not available?

**Comment by liamwhite** [comment]
<img width="1072" alt="Screenshot 2023-06-17 at 11 47 31 PM" src="https://github.com/yuzu-emu/yuzu/assets/9658600/c6acae63-dfe9-42ee-bc0f-c17bf103b33a">
I tested native ASTC support explicitly on macOS and it is working.

**Comment by DamianPereira** [comment]
Thank you! The lack of mentioning in the May's progress report made me think that it was not supported. An edit/pd might be a good idea.

**Comment by goldenx86** [comment]
I don't want to report stuff for a platform that isn't playable yet.
