### ISSUE TITLE
Android not show control overlay

### ISSUE THREAD

**Issue by amazingfate** [yuzu-emu/yuzu#10827]
![yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11780573/yuzu_log.txt)

I update the the latest version from Google play today, and the control overlay is gone.

**Comment by german77** [comment]
Go to overlay -> reset overlay. This is a bug from upgrading from 1st release to current.

**Comment by amazingfate** [comment]
Fixed by cleaning app data.
