### ISSUE TITLE
camera not working on totk linux

### ISSUE THREAD

**Issue by JOEYOCHO** [yuzu-emu/yuzu#10823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1472

### Description of Issue

camera does not work on totk and screen hangs with the only way to be able to do anything else is to close it 

https://github.com/yuzu-emu/yuzu/assets/89509487/cccc9b33-8394-4d79-8377-922bf26ac79a

### Expected Behavior

should move on and save the image but it does not it does on windows

### Reproduction Steps

take a picture in totkthen save it on linux

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11780300/yuzu_log.txt)

### System Configuration

CPU: i5 13400f
GPU/Driver: rtx 3060 12gb running nvidia proprietery driver 525
RAM: 32gb 3600mhz
OS: ubuntu 64bit running kde session on wayland

**Comment by liamwhite** [comment]
1. Test with mods disabled before reporting anything
2. Fix your filesystem permissions
    `[ 135.652218] Common.Filesystem <Error> common/fs/file.cpp:Open:281: Failed to open the file at path=/home/imnotexpecting/.local/share/yuzu/nand/user/save/0000000000000000/2C619063842DD486523E49351649A01C/0100F2C0115B6000/album/020_Photo.jpg, ec_message=Permission denied`

**Comment by JOEYOCHO** [comment]
ok

**Comment by JOEYOCHO** [comment]
i have tried giving yuzu write acess to the file system however it does not fix it (i am probably doing it wrong) i have also disabled all mods to no avial

**Comment by JOEYOCHO** [comment]
issue does not happen on ryujinx

**Comment by JOEYOCHO** [comment]
I have fixed the issue it was filesystem
