### ISSUE TITLE
Newer Yuzu Versions Wont load Mods on Skyward Sword HD

### ISSUE THREAD

**Issue by NepsyNep** [yuzu-emu/yuzu#10834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1450+

### Description of Issue

Any versions Above Mainline 1448 Will not load any mod with skyward sword HD  (1450+)

Even with a original game file placed into romfs the game will simply load a black screen and not continue to game 
1448 and below WILL load game just fine without issue

So my guess would be any version of yuzu with new mod loading changes

### Expected Behavior

Game should load up with mods just fine

### Reproduction Steps

Use newest Yuzu
Install mod into skyward sword Romfs folder
Boot game
Fail

Use older Yuzu Build
Install mod into skyward sword Romfs folder
Boot game
Success 

### Log File

[yuzu_log 1448.txt](https://github.com/yuzu-emu/yuzu/files/11782582/yuzu_log.1448.txt)
[yuzu_log Latest.txt](https://github.com/yuzu-emu/yuzu/files/11782451/yuzu_log.Latest.txt)

### System Configuration

CPU: i9 13900k
GPU/Driver: 3090 FE/ 536.23
RAM: 64gb DDR5
OS: Windows 11 Pro

**Comment by liamwhite** [comment]
1430 did not contain any mod loading improvements. It's likely something else. Please provide a mod to test with.

**Comment by NepsyNep** [comment]
> 

1430 is one that works fine as said builds above that seem to fail
Have not tried EVERY version between this and newest
still in testing of doing that
[blue_tunic_a7259.zip](https://github.com/yuzu-emu/yuzu/files/11782548/blue_tunic_a7259.zip)

Just saying it does work on builds before mod loading changes
and no longer works on later builds 

trying to find the EXACT build it starts failing at atm

**Comment by NepsyNep** [comment]
> 1430 did not contain any mod loading improvements. It's likely something else. Please provide a mod to test with.

Updated info with as accurate builds as i can. seems any build above 1448 WILL NOT load mods with this game

**Comment by liamwhite** [comment]
Thanks for the bisect, will investigate this.

**Comment by liamwhite** [comment]
will be fixed by #10841

**Comment by NepsyNep** [comment]
> will be fixed by #10841

sweet!
