### ISSUE TITLE
[TOTK] Dark grass / terrain, blades of grass invisible

### ISSUE THREAD

**Issue by OsoaGH** [yuzu-emu/yuzu#10833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3697

### Description of Issue

Grass is dark and the blades are invisible. Sometimes when I load in, the issue won't be there, but it doesn't stay for long.
![yuzu_2023 06 18-19 48](https://github.com/yuzu-emu/yuzu/assets/33041004/72eaf8bc-3dc4-41b7-bb45-f80c1df8df36)

### Expected Behavior

Grass to not be dark and the blades to be visible.

### Reproduction Steps

1. Load game
2. See error

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11782373/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5 5600
GPU/Driver: RX 6700 XT (23.5.2)
RAM: 32gb
OS: Windows 11

**Comment by FernandoS27** [comment]
Keep Reactive Flushing on.
