### ISSUE TITLE
Yuzu interface is unreadable

### ISSUE THREAD

**Issue by SeaKestrel** [yuzu-emu/yuzu#10836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1473

### Description of Issue

The Yuzu interface's items are not displayed correctly like this
I can't even see what's on the dock
![image](https://github.com/yuzu-emu/yuzu/assets/78849811/981254af-f6f0-4457-b908-8c7c07b6de9d)
![image](https://github.com/yuzu-emu/yuzu/assets/78849811/26d984b4-810e-4b83-ae76-cda074d28484)
![image](https://github.com/yuzu-emu/yuzu/assets/78849811/bea0ce5c-50b6-4475-8dbf-6fc3b53694b9)

### Expected Behavior

I'm supposed to see everything

### Reproduction Steps

Cannot do anything

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11782632/yuzu_log.txt.old.txt)

### System Configuration

CPU:Intel(R) Pentium(R) Gold G6400 CPU @ 4.00GHz
GPU/Driver: Vulkan
RAM:15.12 GiB + 20 GiB of SWAP
OS: Ubuntu 23.04

**Comment by liamwhite** [comment]
This is a problem with your Qt theme. You might want to try adjusting the settings in Configure -> General -> UI -> Theme to see if any improve the readability of text.

**Comment by SeaKestrel** [comment]
I don't see any difference by changing the theme
![image](https://github.com/yuzu-emu/yuzu/assets/78849811/7a5f2405-2663-4754-af62-603deade27d3)
