### ISSUE TITLE
TOTK: Shadow wobbling when link/camera is moved

### ISSUE THREAD

**Issue by IWillPinchU** [yuzu-emu/yuzu#10831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Every EA/Mainline I have used so far

### Description of Issue

The Shadows wobble and flicker when link/camera moves, it seems to be present everywhere and i have noticed this in a few other people's video on discord. 
I have tried on default settings with:
1)Update 1.1.1
2)Resolution Mod
3)Shadow 1024x1024, 512x512, 256x256 (Individually)
The only FIX that has worked so far is bumping up the resolution scale to 3x/4x but this kills nearly half of the performance

### Expected Behavior

Default, 1x, EA 3696/3692/3678/3635/3652(same in all): https://imgur.com/a/t6qhTwt
Res+Shadow, 1x, EA-Same: https://imgur.com/a/128nODe
Default, 3x, EA-Same: https://imgur.com/a/EmQbsup
Default, 1x, Mainline: https://imgur.com/a/7hdvZgO
Default, 3x, Mainline: https://imgur.com/a/4Bm1gV4

### Reproduction Steps

It seems to be present everywhere in varying amount but very noticeable in KYOKUGON SHRINE near FOREST OF SPIRIT.

### Log File

log, default, 1x, EA: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11781366/yuzu_log.txt)
log, default, 3x, EA: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11781378/yuzu_log.txt)
log, default, 1x, Mainline 1472: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11781389/yuzu_log.txt)
log, default, 3x, Mainline 1472: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11781426/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5 5600x
GPU/Driver: Nvidia RTX 2060/536.23
RAM: 16GB DDR4 3200mhz
OS: Windows 11
Yuzu Settings- Same across EA/Mainline- 
![image](https://github.com/yuzu-emu/yuzu/assets/85113709/87b7c58c-33bf-46da-8ea0-a19f5e41e1de)
![image](https://github.com/yuzu-emu/yuzu/assets/85113709/895608bc-4621-48fa-a0e3-a5d2686f86d4)

**Comment by liamwhite** [comment]
That's the way it renders on the switch, idk what you want us to do about it

https://github.com/yuzu-emu/yuzu/assets/9658600/45f142c4-f79e-4162-b517-9ce946817805

**Comment by IWillPinchU** [comment]
oh, i did not know that sorry for the disturbance

**Comment by IWillPinchU** [comment]
That's unfortunate
Do you know why it doesn't happen on 3x resolution scale?

**Comment by liamwhite** [comment]
The shadow resolution in the far cascade might be high enough to resolve most of the aliasing with 3x scaling.
