### ISSUE TITLE
(Fixed 3706) EA 3705 XenoBlade Chronicles 2 Cut scene beeping noise then crashes

### ISSUE THREAD

**Issue by Angeluz01** [yuzu-emu/yuzu#10847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3694-3705

### Description of Issue

XenoBlade Chronicles 2 Cut scene beeping noise /artifacts then crashes

EA - 3694-3705 Vulkan 4K 2x scale

Artifacts : https://youtu.be/XIOB2tqjxTA
Beeping Noise : https://youtu.be/57RPcLudes8

### Expected Behavior

play normal / Vulkan

### Reproduction Steps

save files: https://mega.nz/file/9TBB2QiQ#Yxv8KIPYtYT5D3af78mcUcTzOLZdNgLY6n8hyeG2vl4

### Log File

https://mega.nz/file/xDxhCCQJ#1kfbHJrwQ9rCeiQnP7Hu4Og6ZJqOjtkJMIrWPB7lBng)

### System Configuration

CPU: 13900K
GPU/Driver: 4090 Nvidia 536.23
RAM: 32
OS: Win11 22H2 Latest Update 22621.1848

**Comment by gidoly** [comment]
can you check if mainline has same issue?

**Comment by Kelebek1** [comment]
Those logs do not match what's shown in the video, and you're getting a lot of errors from using some cheat. Try without mods.

**Comment by Angeluz01** [comment]
> Those logs do not match what's shown in the video, and you're getting a lot of errors from using some cheat. Try without mods.

Clean Yuzu EA 3689 without any XBC2 mod - CS Beeping then crash yuzu_log.txt

yuzu_log.txt
https://mega.nz/file/gHoGnBKD#6tbbDS7f4pzXfSz03kW-3IDtRUcEBQV_WUgyHK9UHiM

Video
https://youtu.be/WXBVkVpLPrU

**Comment by Angeluz01** [comment]
> can you check if mainline has same issue? if it happens can you check which mainline introduced?

Mainline Build - ce191ba32 Work without problems with mods  ; )

**Comment by Angeluz01** [comment]
Yuzu EA 3705 - Xenoblade Chronicles 2 CutScenes Beeping noise and crash

Example: 
https://youtu.be/YhTsUpFqJ_4

**Comment by Angeluz01** [comment]
Latest 3706 fixed the cs problem😂

**Comment by Angeluz01** [comment]
3708 CS Beeping noise and crash happen again 🤡
