### ISSUE TITLE
Stop reinitializing Shortcut on the desktop at update

### ISSUE THREAD

**Issue by LeChamalet** [yuzu-emu/yuzu#10849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

At every update of yuzu the shortcut icon on the windows 11 desktop get recreated and thus is being moved from where i moved it to the top left corner of the screen. 

### Why would this feature be useful?

By not systematically recreating the icon at every update, the icon wouldn't move every time.

**Comment by Squall-Leonhart** [comment]
Duplicate https://github.com/yuzu-emu/yuzu/issues/10426, https://github.com/yuzu-emu/yuzu/issues/10395, or https://github.com/yuzu-emu/yuzu/issues/10152

**Comment by liamwhite** [comment]
This is an issue in liftinstall - please file it here: https://github.com/j-selby/liftinstall
