### ISSUE TITLE
Different yuzu phone versions support

### ISSUE THREAD

**Issue by redbearinflames** [yuzu-emu/yuzu#10843]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What feature are you suggesting?

[request] Even though i am thinking this is close to Impossible i decided to ask anyway the title says it all, different phone version for yuzu like :android 8,android 9 etc.

### Why would this feature be useful?

I think it would be a good ideea because not every one has ver 10 or above and some people don't even have pc or just have a bad pc or laptop etc. That's why I think it's a good idea

**Comment by gidoly** [comment]
we are not planned to support old android version
