### ISSUE TITLE
"Building for Windows" wiki page: inconsistent Visual Studio version

### ISSUE THREAD

**Issue by comex** [yuzu-emu/yuzu#10852]
### Issue

(I can't fix this myself because, according to GitHub, "You do not have permission to update this wiki.", and it doesn't seem possible to send pull requests for wiki repositories either.)

The [Building for Windows](https://github.com/yuzu-emu/yuzu/wiki/Building-For-Windows) wiki page first says to install Visual Studio 2022 Community, but then mentions Visual Studio 2019 in three places:
- "Click the "Configure" button and choose `Visual Studio 16 2019`"
   - including screenshot
- "Open the solution file `yuzu.sln` in Visual Studio 2019"
- Under "Building from the command line with MSVC", "`cmake .. -G "Visual Studio 16 2019" -A x64`"

I'm assuming this is a mistake rather than some kind of crazy hybrid version build. :)

**Comment by liamwhite** [comment]
Updated the text references, thanks. Will need someone else to get the images updated.

**Comment by FearlessTobi** [comment]
I botched something together with Gimp.
Should look good enough for now.
