### ISSUE TITLE
TotK: camera target "flickering"

### ISSUE THREAD

**Issue by ModMachine626** [yuzu-emu/yuzu#10855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1474/ Early Access 3698

### Description of Issue

When targeting an object with the camera rune, it seems to repeatedly retry targeting it over and over. Sometimes it tries to add the object to the compendium, other times it just takes a picture.

https://imgur.com/a/mBkZ3U1

Also, during the "Camera Work in the Depths" quest, I took a picture of the statue, and then took a picture of my shield. Both pictures counted as it they were of the statue.

### Expected Behavior

When targeting it should show an orange or blue box around the object with the objects name. once a photo is taken it should always try to put it in the Hyrule Compendium.

### Reproduction Steps

Version 1.0.0
Vanilla game with no mods.

Obtain the camera
Point the camera at a target-able object.

Save: [slot_01.zip](https://github.com/yuzu-emu/yuzu/files/11793794/slot_01.zip)

### Log File

Log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11793774/yuzu_log.txt)

### System Configuration

CPU: i5-10300H 2.5GHz
GPU/Driver: RTX 3050 laptop, Driver: 536.23
RAM: 16GB
OS: Windows 11

**Comment by Squall-Leonhart** [comment]
set GPU accuracy to high or extreme

**Comment by ModMachine626** [comment]
Thanks
