### ISSUE TITLE
Problems with Pokémon Sword

### ISSUE THREAD

**Issue by luuki478** [yuzu-emu/yuzu#10866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

.

### Description of Issue

Hi, my pokemon sword is crashing.
It started crashing on route 3, since then it hasn't stopped crashing. Whenever I start the game, after a few minutes it crashes, sometimes 10 minutes, 5 minutes, or even less...

### Expected Behavior

.

### Reproduction Steps

.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11810808/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz   3.60 GHz
GPU/Driver: AMD Radeon RX 570 Adrenalin Edition
RAM: 8,00 GB
OS: Windows 10

**Comment by Squall-Leonhart** [comment]
No build specified
No reproduction steps or Save file provided.

**Comment by Squall-Leonhart** [comment]
Should be fixed by https://github.com/yuzu-emu/yuzu/pull/10884
