### ISSUE TITLE
We support some Mali devices now. For any other problems, please open new issues.

### ISSUE THREAD

**Issue by chrtylee** [yuzu-emu/yuzu#10861]
We support some Mali devices now. For any other problems, please open new issues.

_Originally posted by @FearlessTobi in https://github.com/yuzu-emu/yuzu/issues/10516#issuecomment-1598771656_
   Still not working on my pixel 7 pro. Same error. Need different drivers.

**Comment by liamwhite** [comment]
The Pixel 7 Pro is a supported device. You have given no information about the game(s) you tried or any log files.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Closing
