### ISSUE TITLE
Enabling Max GPU Clocks causes worse performance

### ISSUE THREAD

**Issue by K11MCH1** [yuzu-emu/yuzu#10868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access e2967c2a65

### Description of Issue

The setting seems to be causing worse performance than having it off. See the following footages of MK8 and Crash Bandicoot N sane Trilogy:

Max GPU off:

https://github.com/yuzu-emu/yuzu/assets/81425424/24a3425e-0603-41ed-8abb-c016bfbe451b

https://github.com/yuzu-emu/yuzu/assets/81425424/37d8cd7a-326a-42dd-9fac-ccafbfd95d3f

Max GPU on:

https://github.com/yuzu-emu/yuzu/assets/81425424/dae23ed4-f4f7-4d58-a720-6bd341bd5f9e

https://github.com/yuzu-emu/yuzu/assets/81425424/a44ff19a-7690-41bd-9656-5d3cd3edb196

### Expected Behavior

It should not behave like this.
Also I'm 99% sure it is not the throttling of my device as i have also tested on a self compiled build that allows max clocks while ignoring thermals. The behavior on both official Yuzu and the modded build is the same.
Note: the log is from official Yuzu.

### Reproduction Steps

- System driver (676.16)
- Filter: ScaleForce
- Disk Shader Cache enabled
- Max GPU Clocks enabled
- Docked mode disabled
Everything else default.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11814460/yuzu_log.txt)

### System Configuration

CPU: 8gen2
GPU/Driver: A740
RAM: 16GB
OS: Android 13

**Comment by goldenx86** [comment]
Yeah I reported this during beta testing too, I didn't find an instance where it helped either.

**Comment by brujo5** [comment]
does not work properly as the effect only lasts for a few seconds.  Root permission is needed for it to work properly.  I know because it has the same effect as GPU boost, only this has a global effect and can be used anywhere.

![Screenshot_2023-06-21-00-16-57-071_com microsoft emmx-edit](https://github.com/yuzu-emu/yuzu/assets/4172898/d21239c1-c782-458b-bd39-29660bd316dc)

**Comment by K11MCH1** [comment]
> Yeah I reported this during beta testing too, I didn't find an instance where it helped either.

Thanks for letting me know.
Thought it was just me since no one else seemed to talk about it.

**Comment by K11MCH1** [comment]
> does not work properly as the effect only lasts for a few seconds. Root permission is needed for it to work properly. I know because it has the same effect as GPU boost, only this has a global effect and can be used anywhere.
> 
> ![Screenshot_2023-06-21-00-16-57-071_com microsoft emmx-edit](https://user-images.githubusercontent.com/4172898/247464004-d21239c1-c782-458b-bd39-29660bd316dc.jpg)

Thats seems to be a different issue?
If it was only lasting a few seconds then the games on my footages wouldnt be slowed down all the way to the last minute.

The strange thing though, with official Yuzu and gpu max on, my game space overlay does not report maxed value.
But it does with my modded Yuzu.

**Comment by Squall-Leonhart** [comment]
On android, the Power manager will try to balance battery concerns between the CPU and GPU based on the load and thermals of the given component, if you're forcing GPU to always clock high on android you're taking power away from the CPU, and raising thermals in the device so overall performance will be lower.

**Comment by ThepuncheXD7** [comment]
There is another problem enable GPU debugging  and try any game makes the emulator crash and close
Early Access builde 2967c2a65
