### ISSUE TITLE
Emulator freezes when pro controller plugged in USB

### ISSUE THREAD

**Issue by MatthiasBenquet** [yuzu-emu/yuzu#10877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1476

### Description of Issue

With Direct Pro Controller driver enabled, the emulator freezes (and then "doesn't respond") when a Pro Controller is plugged in USB.

It goes back to normal just after unplugging the controller.

### Expected Behavior

The emulator not being freezing

### Reproduction Steps

Enable Direct Pro Controller driver [EXPERIMENTAL] in Emulation >Configure > Controls > Advanced
Quit the emulator

1. a) Plug in the Pro Controller via USB  
b) Launch the emulator  
c) Click on Emulation > Configure  
d) Freeze

2. a) Launch the emulator  
b) Go to Emulation > Configure > Controls  
c) Plug in the Pro Controller via USB  
d) Click on input device  
e) Freeze

### Log File

Note that I did the steps and then unplugged the controller to get these log files (I didn't close the emulator while freezed)

[yuzu_log.txt.old1.txt](https://github.com/yuzu-emu/yuzu/files/11837336/yuzu_log.txt.old1.txt)
[yuzu_log.txt.old2.txt](https://github.com/yuzu-emu/yuzu/files/11837345/yuzu_log.txt.old2.txt)

### System Configuration

CPU: AMD Ryzen 5 5600G with Radeon Graphics 3.90 GHz
GPU/Driver: NVIDIA GeForce GTX 1060 GB / 536.23
RAM: 16GB
OS: Windows 11 Family 22H2

**Comment by german77** [comment]
Your controller isn't responding to any command. What controller is this? Original, power A another third party?

**Comment by Angeluz01** [comment]
Not detecting original switch pro controller with the new SDL2.dll

**Comment by MatthiasBenquet** [comment]
> What controller is this? Original, power A another third party?

It is an original pro controller

> Your controller isn't responding to any command.

I am not sure if I understand what you mean. It isn't responding to commands sent by yuzu?

**Comment by german77** [comment]
Yuzu tries to configure the controller. But your controller isn't responding. The freezes you have is from waiting for the controller reply.  Seems weird the original isn't working properly.

**Comment by german77** [comment]
Try restarting the PC or the controller.

**Comment by german77** [comment]
> Not detecting original switch pro controller with the new SDL2.dll

This has been fixed today. Wait for tomorrow mainline

**Comment by Angeluz01** [comment]
> > Not detecting original switch pro controller with the new SDL2.dll
> 
> 
> 
> This has been fixed today. Wait for tomorrow mainline

3705 

SDL2.DLL not detecting original switch pro controller

Replace SDL2.DLL from previous v35xx
controller keep disconnecting every 1sec

**Comment by MatthiasBenquet** [comment]
> Try restarting the PC or the controller.

It did nothing.
Could it be a USB issue? When I go to joy.cpl, the controller shows up but no input is read.

**Comment by Squall-Leonhart** [comment]
has vjoy ever been installed on this machine?

**Comment by MatthiasBenquet** [comment]
I have installed ViGEm Bus Driver once but removed it.
But I have never installed vjoy as far as I remember.

**Comment by german77** [comment]
vjoy or vigem are fine. The problematic ones are hidguardian. I forgot to mention, disable the experimental custom driver for pro controllers. SDL should deal better with your controller.
