### ISSUE TITLE
Android: Yuzu doesn't detect XCI files in the game directory 

### ISSUE THREAD

**Issue by driftywinds** [yuzu-emu/yuzu#10876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

version ec423c6919

### Description of Issue

I have selected a folder that has my XCI file in it but Yuzu fails to detect it as a game and instead shows that there are no games in the folder.

### Expected Behavior

It should detect the XCI file and let me play it.

### Reproduction Steps

Choose a game folder with an XCI game file in it.

### Log File

no log file available

### System Configuration

CPU: 
GPU/Driver: Snapdragon 865
RAM: 12 GB 
OS: Android 13 (Oxygen OS)

**Comment by liamwhite** [comment]
redump your keys, if the issue persists and the file works on desktop seek support on discord
