### ISSUE TITLE
Bayonetta 2 and 3 Slowdown

### ISSUE THREAD

**Issue by BeardedJellyfish** [yuzu-emu/yuzu#10871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1475/ EA3699 - I also used a manual download of 1413 just to see if it would help

### Description of Issue

bayonetta 2 and 3 are running at about 70 to 80% of full game speed

### Expected Behavior

bayonetta 2 and 3 had been working at full speed for months - after tears of the kingdom's official release and first TOK centric update seems to have caused issues

### Reproduction Steps

I have tried running both games on both EA and public build without any additional mods - nothing seems to help.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11826572/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11826573/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel i7 12700K
GPU/Driver: rtx 3070 driver 535.98
RAM: 32 gb ddr 4 3000mghz trident Z rgb
OS: windows 11 pro version 22H2 build 22621.1702
experience feature pack 1000.22641.1000.0

**Comment by Pergmen** [comment]
Disable reactive flushing and test again. This will cause graphical issues in Bayonetta 2

**Comment by BeardedJellyfish** [comment]
I disabled reactive flushing. Bayonetta 2 now performs better - around 90% speed. Bayonetta 3 is still around 50 to 60% of full speed

**Comment by zhm86** [comment]
Same here, I could get 60fps in level selection menu using Ryujinx, I could get only 40fps using Yuzu.

**Comment by zhm86** [comment]
What Pergmen said is right. Disable reactive flushing fix the slowdown.
I found that EA-3552 introduce Reactive flushing, then cause slowdown.
With graphic packs, Bayonetta 2 is better using CEMU than using NS emulator.
You could custom resolution, shadow quality, LOD in CEMU.

**Comment by BeardedJellyfish** [comment]
I uninstalled yuzu. Every game I was trying to play besides mario odyssey wouldn't go above 60% gameplay speed. TOK, links' awakening, new pokemon snap, triangle strategy, kirby forgotton lands. All games that would work 100% fine for months suddenly don't work. I switched to ryujinx
