### ISSUE TITLE
mario kart 8 deluxe take too long to open after it the freeze

### ISSUE THREAD

**Issue by yamenking123** [yuzu-emu/yuzu#10887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1477

### Description of Issue

yuzu bug report

### Expected Behavior

yuzu bug report

### Reproduction Steps

yuzu bug report

### Log File

yuzu bug report

### System Configuration

CPU: i5-12500H
GPU/Driver: rtx 3050 laptop
RAM:8 GB 
OS: windows 11

**Comment by FernandoS27** [comment]
you have to install the firmware.

**Comment by FearlessTobi** [comment]
Closing as spam.
