### ISSUE TITLE
Failing to launch through command line 

### ISSUE THREAD

**Issue by AeroAU** [yuzu-emu/yuzu#10882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1476

### Description of Issue

Up until a week ago I was issue free running games through Steam with command line args, but it seems newer versions of Yuzu have broken that for me. On launch I get a 1-2 second white screen with only the yuzu version in the header, before it completely closes. It also seems that having minidump enabled doesn't allow me to launch directly into a game, only rom select, but any rom I try to launch from there will have an infinite launch screen (so I'm not sure how helpful the minidump will be since it may not be the same issue). Launching the Yuzu client directly and selecting a rom has no issues at all, so this seems be purely a command line issue.

### Expected Behavior

It is expected to launch directly into the title, and set it to fullscreen.

### Reproduction Steps

if I'm launching from Steam or directly from a command line, the arguments used are:

"C:\Users\u-got\AppData\Local\yuzu\yuzu-windows-msvc\yuzu.exe" -f -g "E:\Emulation\Roms\Nintendo\Switch\The Legend of Zelda Tears of the Kingdom\The Legend of Zelda Tears of the Kingdom [0100F2C0115B6000][v0].nsp"

Rolling back to version 1468 gives no issues with the exact same arguments.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11841302/yuzu_log.txt)
[yuzu-crash-20230623084636.zip](https://github.com/yuzu-emu/yuzu/files/11841305/yuzu-crash-20230623084636.zip)
the minidump may not be helpful as it disables the ability to launch directly into my game, so I can't reproduce the same crash with it active.

### System Configuration

CPU: 12th Gen Intel(R) Core(TM) i9-12900K | AVX2 | FMA
GPU/Driver: NVIDIA GeForce RTX 3090 | NVIDIA 536.23.0.0
RAM: 32.0 GB in dual channel configuration
OS: Windows 11 Version 22H2 (Build 22621.1848)

**Comment by german77** [comment]
Call stack

![image](https://github.com/yuzu-emu/yuzu/assets/5944268/b3c8d683-de4b-4a4d-881d-1fe10374ec5e)

**Comment by anpilley** [comment]
Getting a proper minidump for this was hampered by #10881 so I'm not 100% certain we've got the same crash, I wasn't able to reproduce it on my end with the same mainline build.

**Comment by german77** [comment]
Issue has been identified. A fix will probably drop soon.

**Comment by german77** [comment]
Can you test with the linked PR artifacts and confirm the issue is indeed gone

**Comment by AeroAU** [comment]
> Can you test with the linked PR artifacts and confirm the issue is indeed gone

It has seemed to fix the white screen hanging issue, but still gets stuck on an infinite launching screen
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11844321/yuzu_log.txt)
