### ISSUE TITLE
[ 437.352718] Debug <Critical> ./common/intrusive_list.h:operator():52: Assertion Failed!

### ISSUE THREAD

**Issue by VincentAdamNemessisX** [yuzu-emu/yuzu#10885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1476

### Description of Issue

When I finished the gpu driver with dgpu mx150, I can't use multiplayer service. But I can use it with no multiplayer services,  and when I play mhgu, I can find any rooms, but I can't join them, it meaned I can't play with multiplayers.

### Expected Behavior

It should be worked well with multiplayers online game in mhgu.

### Reproduction Steps

Use uos os, and use dgpu to start yuzu with mhgu, and into a room to online game, then if join any room, it will crash and appear below debug logs.

### Log File

[ 411.270010] Service.LDN <Error> core/hle/service/ldn/ldn.cpp:GetNetworkInfo:197: NetworkInfo is not valid 16587
[ 411.276541] Service.LDN <Error> core/hle/service/ldn/ldn.cpp:GetNetworkInfo:197: NetworkInfo is not valid 16587
[ 411.284782] Service.LDN <Error> core/hle/service/ldn/ldn.cpp:GetNetworkInfo:197: NetworkInfo is not valid 16587
[ 411.292015] Service.LDN <Info> core/hle/service/ldn/ldn.cpp:CreateNetwork:383: called
[ 411.300562] Service <Info> core/hle/service/sockets/bsd.cpp:SocketImpl:476: New socket fd=0
[ 411.659856] Service.Friend <Warning> core/hle/service/friend/friend.cpp:GetPlayHistoryRegistrationKey:175: (STUBBED) called, local_play=true, uuid=0x00000000fa50a4a439616bbc0ff34ec2
[ 411.918627] Service.Friend <Warning> core/hle/service/friend/friend.cpp:UpdateUserPresence:165: (STUBBED) called
[ 419.265802] Service.Friend <Warning> core/hle/service/friend/friend.cpp:UpdateUserPresence:165: (STUBBED) called
[ 419.281557] Service.Friend <Warning> core/hle/service/friend/friend.cpp:GetFriendList:188: (STUBBED) called, offset=0, uuid=0x00000000fa50a4a439616bbc0ff34ec2, pid=0
[ 433.142517] Service.Friend <Warning> core/hle/service/friend/friend.cpp:UpdateUserPresence:165: (STUBBED) called
[ 433.747692] Service.Friend <Warning> core/hle/service/friend/friend.cpp:GetFriendList:188: (STUBBED) called, offset=0, uuid=0x00000000fa50a4a439616bbc0ff34ec2, pid=0
[ 436.864424] Service.Friend <Warning> core/hle/service/friend/friend.cpp:GetFriendList:188: (STUBBED) called, offset=0, uuid=0x00000000fa50a4a439616bbc0ff34ec2, pid=0
[ 437.352531] Debug <Critical> ./common/intrusive_list.h:operator():52: Assertion Failed!
[ 437.352619] Debug <Critical> ./common/intrusive_list.h:operator():52: Assertion Failed!
[ 437.352623] Debug <Critical> ./common/intrusive_list.h:operator():52: Assertion Failed!
[ 437.352718] Debug <Critical> ./common/intrusive_list.h:operator():52: Assertion Failed!

### System Configuration

CPU: Intel i5 8250U
GPU/Driver: NVIDIA MX150
RAM: Kingston 16GB
OS: UOS home

**Comment by german77** [comment]
should have been fixed by #10884

**Comment by VincentAdamNemessisX** [comment]
> should have been fixed by #10884

But maybe it doesn't work normally, I update yuzu to -> 1477 version with flatpak, but I still meet this problem, please see the log files, developer.
[Yuzu Log Files](https://github.com/VincentAdamNemessisX/VirtualAssistant/blob/main/yuzu_log.txt.old.txt)

**Comment by Squall-Leonhart** [comment]
> > should have been fixed by #10884
> 
> But maybe it doesn't work normally, I update yuzu to -> 1477 version with flatpak, but I still meet this problem, please see the log files, developer. [Yuzu Log Files](https://github.com/VincentAdamNemessisX/VirtualAssistant/blob/main/yuzu_log.txt.old.txt)

not included in 1477, wait for 1478
