### ISSUE TITLE
Crash at game start

### ISSUE THREAD

**Issue by pepulin** [yuzu-emu/yuzu#10889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline >= 1464

### Description of Issue

When I double click the game name, Yuzu crashes.
I have a copy of Mainline 1463 and it does not happen.

### Expected Behavior

Launch the game properly.

### Reproduction Steps

Double click on the game listed (normal start).

### Log File

[yuzu_log.txt]

### System Configuration

CPU: i7-6700HQ
GPU/Driver: Nvidia 970m lastest drivers
RAM: 16 GB
OS: Windows 10

**Comment by FearlessTobi** [comment]
Should be fixed with Mainline 1477.
If still doesn't work then, let me know and I will reopen this issue.

**Comment by pepulin** [comment]
Hi!
Tested on 1477 and it's not working @FearlessTobi 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11850486/yuzu_log.txt)

**Comment by liamwhite** [comment]
@FearlessTobi I'm not sure where you got this from. PR #10884 (which may have fixed this) was not in 1477, but will be in 1478 (and is in EA 3706+).

**Comment by FearlessTobi** [comment]
Does it work now?

**Comment by 4thanks** [comment]
> Does it work now?

same issue, still crash on yuzu 1478, back to 1463 is ok.
```
System Configuration
CPU: i7-10700k
GPU/Driver: amd5700xt
RAM: 32 GB
OS: Windows 10
```

**Comment by liamwhite** [comment]
What timezone are you in? Does it work if you set the timezone to something like EST?

**Comment by 4thanks** [comment]
> What timezone are you in? Does it work if you set the timezone to something like EST?

wow,set the timezone to EST work for me, thanks~

**Comment by lat9nq** [comment]
Closing due to piracy.

**Comment by FearlessTobi** [comment]
Isn't this still a valid issue?
