### ISSUE TITLE
1476  had major graphic glitch.. 1474 is fine

### ISSUE THREAD

**Issue by pka4916** [yuzu-emu/yuzu#10883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1476

### Description of Issue

![image](https://github.com/yuzu-emu/yuzu/assets/34923634/392c39c2-f885-4526-8659-65a65c4c17fc)

### Expected Behavior

graphics messed up see screenshot

![image](https://github.com/yuzu-emu/yuzu/assets/34923634/7e0e5e81-d839-4965-a9d3-4456f6decbdb)

### Reproduction Steps

start the game

### Log File

none

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by german77** [comment]
Please fill out the issue report properly. I don't even know what game is this.

**Comment by FearlessTobi** [comment]
Closing for lack of proper issue report
