### ISSUE TITLE
Yuzu closes when double-clicking TOTK

### ISSUE THREAD

**Issue by Kipp-s** [yuzu-emu/yuzu#10896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1477 / Early Access 3708

### Description of Issue

Yuzu closes when opening Tears of the Kingdom, other games work fine. Was working until today. Drivers were updated after the issue showed up and did not fix it.

### Expected Behavior

Open the game.

### Reproduction Steps

Double-clicking the game or any form of opening the game.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11854227/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz
GPU/Driver: NVIDIA GeForce GTX 1660 SUPER / Driver: NVIDIA 536.23.0.0
RAM: 16gb
OS: Windows 10

**Comment by german77** [comment]
Piracy is not allowed
