### ISSUE TITLE
Yuzu fails to open after update with "entry point not found" error after yuzu update

### ISSUE THREAD

**Issue by Egnom1975** [yuzu-emu/yuzu#10895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 2fc5dedf6 

### Description of Issue

Since around a day ago, Yuzu has stopped launching for me, and windows throws an “entry point not found” error popup. It still runs the updater, and the installation is therefore up-to-date, but once the update is finished, the error occurs. I have tried reinstalling Yuzu, and all the common fixes listed for entry point not found errors. Yuzu functioned perfectly well for several weeks before this. Thanks in advance for any help, screenshot of error message is attached. Since Yuzu has not properly launched since reinstalling, a log folder does not yet exist.

There is no logs, in the %appdata%\yuzu\log. I have the same error stated above.it started after I updated yesterday.

### Expected Behavior

Yuzu open to gui interface after update routine

### Reproduction Steps

Clicking on yuzu executable. Update goes thru, after update is completed it fails to open

### Log File

There is no logs, in the %appdata%\yuzu\log. I have the same error stated above.it started after I updated yesterday.

### System Configuration

CPU: Intel(R) Core(TM) i7-4770K 
GPU/Driver: Nvidia RTX 2080/531.68
RAM: 16 GB
OS: Windows 10 22H2 build 19045.3086

**Comment by Egnom1975** [comment]
![Capture4](https://github.com/yuzu-emu/yuzu/assets/76527662/480fd7ac-3fb8-4433-80eb-cdf40ad63334)

Attached is pop up error

**Comment by liamwhite** [comment]
update vc redist

**Comment by Egnom1975** [comment]
Thanks
That fix it.
