### ISSUE TITLE
Xenoblade Chronicles 2 latest EA3708 Beeping noise and crash

### ISSUE THREAD

**Issue by Angeluz01** [yuzu-emu/yuzu#10897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3708

### Description of Issue

3706 fixed the problem but latest 3708 XenoBlade Chronicles 2 Cutscenes Beeping noise and crash happen again 

### 

Example: 
https://youtu.be/YhTsUpFqJ_4

### Reproduction Steps

Play normal Vulkan,
start Torna the golden country DLC 

or 

Event theater > chapter2 > Her flames hide something deeper

XBC2 Gamesave
https://mega.nz/file/JPIFUbTK#3yGQsANf6xf5B9zIxBzp4LyHCvUiXDpcmsIkoC4OwZU

### Log File

yuzu_log.txt
https://mega.nz/file/gHoGnBKD#6tbbDS7f4pzXfSz03kW-3IDtRUcEBQV_WUgyHK9UHiM

### System Configuration

CPU: 13900K
GPU/Driver: 4090 , latest NVIDIA driver
RAM: 32G
OS: Was n11 22h2 latest update

**Comment by gidoly** [comment]
your log is from 3698....... and putting clown emoji on your issue definitely not make to fix us to issue quicker

**Comment by Angeluz01** [comment]
> your log is from 3698....... and putting clown emoji on your issue definitely not make to fix us issue quicker

Same glitch on 3705

**Comment by gidoly** [comment]
post the log from 3706. any your vram seems only 8gb available? are you running something on background?

**Comment by goldenx86** [comment]
Can't reproduce here, audio is clear in the water tank cutscene.
Check for audio driver updates from that Creative device.
And post a log of the actual issue in the affected version.

**Comment by Angeluz01** [comment]
> Can't reproduce here, audio is clear in the water tank cutscene. Check for audio driver updates from that Creative device. And post a log of the actual issue in the affected version.

Video 3708 EA (without mods) Cutscenes and DLC Crashes
https://youtu.be/gbkLCtcxtn0

Video 1474 Mainline work (included Mods) without any problems
https://youtu.be/0p2WjkNknAE

-------
logs

Cutscene crash 01
https://mega.nz/file/gLQiSLrK#f3xFcDqnXC1tmoB5qINDp4XzWm1rddZj9RYbrU4JgI4

Cutscene crash 02
https://mega.nz/file/1LxCXbJB#ppZR9OxPfW0ZDSSv16_6kek4tkB4SzmZX1b1OsL5KNw

DLC The Golden Century crash 01
https://mega.nz/file/1PZC2TwS#i__IbyCRW-8lFtl0uUqeauWu7KvQ8rBl18f-hblB-E8

DLC The Golden Century crash 02
https://mega.nz/file/tGAHTa5K#-dNyOAXLhuaTLScmORVqkZO-p2qn0BxMiPdq4EXNyIk

--------

Gamesaves
https://mega.nz/file/JPIFUbTK#3yGQsANf6xf5B9zIxBzp4LyHCvUiXDpcmsIkoC4OwZU


Thanks

**Comment by Angeluz01** [comment]
> post the log from 3706. and your vram seems only 8gb available? are you running something on background?

4090 24G, PC 32G, OBS recording on same pc

**Comment by goldenx86** [comment]
I think only a minidump can help here.
Go to Emulation, Configure, General, Debug, and enable "Create minidump after crash". Reboot yuzu, reproduce the issue, and then upload the .dmp file it generates in yuzu's binary folder. Also, confirm on which EA version the dump was made so I can get the proper debug symbols for it.

**Comment by Angeluz01** [comment]
> I think only a minidump can help here. Go to Emulation, Configure, General, Debug, and enable "Create minidump after crash". Reboot yuzu, reproduce the issue, and then upload the .dmp file it generates in yuzu's binary folder. Also, confirm on which EA version the dump was made so I can get the proper debug symbols for it.

EA 3708 - Cutscene crash 01 - Event theater > chapter 2 > Her flames hide something deeper
https://mega.nz/file/9GYgWBBa#zlu4lcl24ZiWwI81__FtECif80Ja7CTadkafKl7U8eM

EA 3708 - DLC The Golden Century crash
https://mega.nz/file/gDpymZxS#CbX793jKSyYLkLWZWF3lPGbM9XnLG7LiP3EvqyPsYyg

Thanks

**Comment by goldenx86** [comment]
Got a hint there, run VkDiag.exe and post me a pic of it: https://github.com/13xforever/vkdiag/releases/tag/v1.2.1

**Comment by Angeluz01** [comment]
> Got a hint there, run VkDiag.exe and post me a pic of it: https://github.com/13xforever/vkdiag/releases/tag/v1.2.1

![image](https://github.com/yuzu-emu/yuzu/assets/40654079/9b79adb7-6e0f-4260-a239-94cf1e0a1f0d)

**Comment by goldenx86** [comment]
Uninstall Overwolf and XSplit and reboot. If you need them, update them to their latest versions and reboot.

**Comment by Angeluz01** [comment]
> Uninstall Overwolf and XSplit and reboot. If you need them, update them to their latest versions and reboot.

Uninstalled split and overwolf, Restart PC, but still crash on Cutscenes and DLC

**Comment by goldenx86** [comment]
Update RTSS too, both it and xplit show Vulkan 1.1 layers, too old.

**Comment by Angeluz01** [comment]
> Update RTSS too, both it and xplit show Vulkan 1.1 layers, too old.

still crashes
![image](https://github.com/yuzu-emu/yuzu/assets/40654079/129447ca-c1b1-48bc-b458-69886de43baa)

**Comment by Squall-Leonhart** [comment]
You may have uninstalled xsplit, but its vulkan layer is still active and registered on the system.

**Comment by Angeluz01** [comment]
> You may have uninstalled xsplit, but its vulkan layer is still active and registered on the system.
> 
> Delete its line from
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers and HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Khronos\Vulkan\ImplicitLayers
> 
> Also get rid of the virtual monitor software.

still crashes
![image](https://github.com/yuzu-emu/yuzu/assets/40654079/9ebf986b-d259-4f97-93bc-349e09ed7b58)

**Comment by Angeluz01** [comment]
3727 fixed the issues, thanks^^
