### ISSUE TITLE
Tears of the Kindom Vertical Repeated Texture Walls

### ISSUE THREAD

**Issue by Xenosplitter** [yuzu-emu/yuzu#10892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1434

### Description of Issue

I currently am using Vulkan instead of OpenGL, as OGL has been causing some noticeable stuttering. Vulkan runs faster and more consistently but has some disruptive visual bugs. My current graphics config settings are as follows:

<details>
<summary>yuzu Graphics Settings</summary>

![yuzu Graphics Settings Menu](https://github.com/yuzu-emu/yuzu/assets/54556163/f8561a47-a45b-48ab-a858-4ecc734a9423)

![yuzu Advanced Graphics Settings Menu](https://github.com/yuzu-emu/yuzu/assets/54556163/66e97ca7-d75d-4fbc-a674-e3640d5348bc)

</details>

Namely, while traveling the surface, (possibly on borders between sections? I'm not sure, but they seem to happen in a grid-like pattern) walls of a repeating texture, likely what's on the ground at that point, span from the ground to fairly high, blocking view. These can be walked through and shot through, but not seen through. The walls are invisible from the other side and angling the camera up enough can hide the wall until you look down again (maybe there is a piece of the rendered land that causes this glitched spike/wall?).

<details>
<summary>Vertical glitched texture walls, in Lurelin Village</summary>

![Vertical glitched texture walls, in Lurelin Village](https://github.com/yuzu-emu/yuzu/assets/54556163/57d2bf6e-d240-40f3-8872-4de517db0bd5)

Though this example was from Lurelin Village, it is far from the only location the walls occur. Large, open, and flattish areas seem to have more frequent walls, though that's only through my passive observation.
</details>

### Expected Behavior

While traveling the surface, no glitched walls appear and you can see uninterrupted.

### Reproduction Steps

Walk around the surface, keeping the camera roughly level and the surface visible, not looking too high up in the sky.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11851074/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, 8 Core(s), 16 Logical Processor(s)
GPU/Driver: NVIDIA GTX 3060 v526.98
RAM: PNY XLR8 2x16 GB DDR4-3200 CL16
OS: Microsoft Windows 10 Home Version 10.0.19045 Build 19045

**Comment by Squall-Leonhart** [comment]
upgrade the video driver.
