### ISSUE TITLE
Yuzu crashing in audio code in ssbu (smash) 

### ISSUE THREAD

**Issue by anpilley** [yuzu-emu/yuzu#10900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1478

### Description of Issue

In mainline 1477 and 1478, some users have been getting a crash in ssbu while loading. This was not happening in 1476. 

We caught a minidump and it's crashing somewhere in the audio code, from build 1478.

<img width="806" alt="image" src="https://github.com/yuzu-emu/yuzu/assets/12467241/35963b56-b078-4f7f-84b1-ab9bb9e9f7d1">
[yuzu-crash-20230624155718.zip](https://github.com/yuzu-emu/yuzu/files/11857499/yuzu-crash-20230624155718.zip)

### Expected Behavior

Probably shouldn't crash in the audio code :P

### Reproduction Steps

Launch SSBU. This isn't happening for everyone, other people can't reproduce it, so not sure what the specific differences are.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11857506/yuzu_log.txt)

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by Squall-Leonhart** [comment]
Probably duplicate https://github.com/yuzu-emu/yuzu/issues/10712

**Comment by FearlessTobi** [comment]
Okay.

**Comment by Kelebek1** [comment]
The crash is happening unrelated to the backend, according to the callstack, so I highly doubt it.

**Comment by Squall-Leonhart** [comment]
the crash occurs because the WASAPI device graph resets crashes due to a flaw with the steel series audio enhancements, i guess it could be mitigated in Yuzu so that the session recovers though.

**Comment by Kelebek1** [comment]
> the crash occurs because the WASAPI device graph resets crashes due to a flaw with the steel series audio enhancements, i guess it could be mitigated in Yuzu so that the session recovers though.

Whether the backend is active or not should have no bearing on the queue that samples are pushed into. The queue allocates memory as needed, and unless they're running into out of memory errors, which from what I read on discord doesn't seem to be the case, then I don't think that's the problem here.

**Comment by anpilley** [comment]
Morph worked on this with another user in discord yesterday, there were issues with stack exhaustion, apparently. I don't think it's specific to the steelseries sonar stuff (we've had other users in the support channel hit it without that installed, afaik).

**Comment by Kelebek1** [comment]
> Morph worked on this with another user in discord yesterday, there were issues with stack exhaustion, apparently. I don't think it's specific to the steelseries sonar stuff (we've had other users in the support channel hit it without that installed, afaik).

He said that but there's no way, everything from the audio service code is tiny, most don't even have any local variables at all, and the thing I changed in my previous allocation PR was 1 static vector on the stack which is not very big. There's no way it's using 1MB of stack.

**Comment by lionellion21** [comment]
> > Morph worked on this with another user in discord yesterday, there were issues with stack exhaustion, apparently. I don't think it's specific to the steelseries sonar stuff (we've had other users in the support channel hit it without that installed, afaik).
> 
> > > Morph worked on this with another user in discord yesterday, there were issues with stack exhaustion, apparently. I don't think it's specific to the steelseries sonar stuff (we've had other users in the support channel hit it without that installed, afaik).
> > 
> > 
> > He said that but there's no way, everything from the audio service code is tiny, most don't even have any local variables at all, and the thing I changed in my previous allocation PR was 1 static vector on the stack which is not very big. There's no way it's using 1MB of stack.
> 
> I am the 'other user' Morph worked with (lionellion) as I reported in the patreon support channel that I was encountering this issue. The fix they built works totally fine now and I don't have any "steel series" audio equipment or drivers. I was having SSBU crash and give out screeching/buzzing noises any time I tried to load the game. It would successfully load about 1/10 times but soon after crash, all other times it would just crash immediately upon trying to load without screeching/noise. I have an RTX 4090, i9 13900 KF CPU, and 64GB 6000 MHz DDR5 RAM and 2TB NVME drive. Performance isn't an issue, and SSBU worked fine until the recent yuzu EA/mainline builds for me. Suddenly now I can't load SSBU at all because of the problems above.
> 
> Again, morph fixed this with their test builds they sent me on discord, as I tried them out. As you can see here in the video I recorded, I can now play the game just fine, in fact, up to 120 Hz and 8K if I want to, as my system is pretty powerful: https://www.youtube.com/watch?v=n_oDoyXjNsA&t=2s

And here is me playing on one of the last yuzu EA builds that didn't have the problem: yuzu EA 3659:
https://www.youtube.com/watch?v=M5Itf3l_vEw&list=PL_JJUlbBeKRtZWNeit19-eXXUK6BGqIY0&index=12

**Comment by SamdroidVa** [comment]
Solution! (~sort of~) Disable 5.1 Audio support in your soundcard settings, in other words set it to Stereo. I use the Realtek Onboard audio that comes with my Gigabyte Motherboard. I use "Realtek Audio Console" to set speaker support to 5.1 audio or stereo. I think you can use "Realtek HD Audio Manager" as well. Anyhow, I say its "sort of" a solution, because I enjoy 5.1 audio in games like Tears of the Kingdom, it's fantastic!! (try it if you have a 5.1 setup) There were several other games that crashed due to this issue, this should fix it.
