### ISSUE TITLE
Sonic Origins - the game don't save

### ISSUE THREAD

**Issue by JoquiJorlas** [yuzu-emu/yuzu#10910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3708

### Description of Issue

Hello, Sonic Origins game is experiencing some issues.
The game does not save progress.
There is a ring on the game's HUD that indicates when the auto save is saving, and in the case of the yuzu it stays 100% of the time (not normal behavior, normally it stays for a few seconds and it already saves and the autosave ring disappears)
therefore the game is never saved, every time I try to open the progress it starts from zero.

### Expected Behavior

It is expected that the game saves normally, and that the autosave indicator ring only appears when the autosave is actually in action

### Reproduction Steps

1. Start Sonic Origins game (with CPU Multicore disabled)
2. Choose in the menu any of the games in the collection
3. After passing a game level, it should already be saved, but it doesn't happen at any point in the gameplay

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11860521/yuzu_log.txt)

### System Configuration

CPU:  I7 11800H engineering CPU
GPU/Driver: GTX 750 Ti (536.23)
RAM: 31.85 GiB RAM
OS: Windows 11 22H2

**Comment by Squall-Leonhart** [comment]
There is something wrong with your dump, the rom FS version should be 0.4.0, not 0.0.0

My dump is saving just fine.

**Comment by JoquiJorlas** [comment]
To try to solve the problem I tried to perform another dump this time "installing the files in the NAND" but the error continued to occur...

I started testing the game recently because of the new "Plus" DLC that was released, I had never tested it before.

After seeing that it wasn't being saved, I tried deleting the "data.dat" files referring to the saving.
And that made the game not start anymore, staying forever on a black screen.
So I recovered the deleted files and could only make it work again by changing to the EUR region in the per game settings, I don't know if there was a conflict because I tried to change the language in the game menu and before I closed the emulator.

But really the game didn't save as much before as after this process.

**Comment by Squall-Leonhart** [comment]
Oh, its opening duplicate write handles on the save file and deadlocking the write system.

**Comment by JoquiJorlas** [comment]
Thanks for the tip! I will follow these steps! Thank you!

**Comment by FearlessTobi** [comment]
Can you please try again on the latest build?
We recently made some fixes to our filesystem implementation.

**Comment by JoquiJorlas** [comment]
Yes, I did the test in the last build and the problem was fixed, the game has a functional autosave, thank you all for the support!!
