### ISSUE TITLE
yuzu crashed when loading save in TOTK

### ISSUE THREAD

**Issue by 2584191127** [yuzu-emu/yuzu#10918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1478

### Description of Issue

In Event Viewer:
日志名称:          Application
来源:            Application Error
日期:            2023/6/26 19:09:38
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           DESKTOP-2ON9CLD
描述:
错误应用程序名称: yuzu.exe，版本: 0.0.0.0，时间戳: 0x6496e788
错误模块名称: amdvlk64.dll，版本: 27.20.11028.10001，时间戳: 0x5fb6790f
异常代码: 0xc0000005
错误偏移量: 0x000000000003f758
错误进程 ID: 0x27d8
错误应用程序启动时间: 0x01d9a81df7c38980
错误应用程序路径: D:\yuzu-windows-msvc\yuzu.exe
错误模块路径: C:\Windows\System32\DriverStore\FileRepository\u0361383.inf_amd64_cfccffda602342c4\B361368\amdvlk64.dll
报告 ID: 92a7c255-cd93-4e37-bd23-c846212ac4d1
错误程序包全名: 
错误程序包相对应用程序 ID: 
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-06-26T11:09:38.4884404Z" />
    <EventRecordID>5963</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-2ON9CLD</Computer>
    <Security />
  </System>
  <EventData>
    <Data>yuzu.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>6496e788</Data>
    <Data>amdvlk64.dll</Data>
    <Data>27.20.11028.10001</Data>
    <Data>5fb6790f</Data>
    <Data>c0000005</Data>
    <Data>000000000003f758</Data>
    <Data>27d8</Data>
    <Data>01d9a81df7c38980</Data>
    <Data>D:\yuzu-windows-msvc\yuzu.exe</Data>
    <Data>C:\Windows\System32\DriverStore\FileRepository\u0361383.inf_amd64_cfccffda602342c4\B361368\amdvlk64.dll</Data>
    <Data>92a7c255-cd93-4e37-bd23-c846212ac4d1</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

### Expected Behavior

none

### Reproduction Steps

double click TOTK, click continue game, select a save, click load

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11867853/yuzu_log.txt)

### System Configuration

CPU:AMD Ryzen 7 4800U with Radeon Graphics 
GPU/Driver:AMD Radeon(TM) Graphics
RAM:16GB
OS:win10 22h2

**Comment by Squall-Leonhart** [comment]
Please bring your driver up to date, yours is from 2020.
