### ISSUE TITLE
Marvel Ultimate Alliance 3 not running anymore.

### ISSUE THREAD

**Issue by rodiape** [yuzu-emu/yuzu#10917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1478

### Description of Issue

Marvel Ultimate Alliance not running anymore, just closes after launching. Received this error window.
![Screenshot 2023-06-25 211706](https://github.com/yuzu-emu/yuzu/assets/52631810/3578521c-4f33-4632-b01c-945a53ea8ea2)

### Expected Behavior

Used to run well

### Reproduction Steps

Just trying to run the game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11862743/yuzu_log.txt)

### System Configuration

CPU: 13700k
GPU/Driver: 536.23
RAM: 32 gb DDR5
OS: Windows 11

**Comment by gidoly** [comment]
![yuzu_KPDrUe4QeF](https://github.com/yuzu-emu/yuzu/assets/66776795/6b14f666-d14b-48dc-a660-ac63126f1e9b)
works fine here
please visit our discord for support
