### ISSUE TITLE
When launched through Steam, Yuzu fails to load Tears of the Kingdom

### ISSUE THREAD

**Issue by alexander-novo** [yuzu-emu/yuzu#10911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1478 / Early Access 3708

### Description of Issue

When Yuzu is launched through Steam, it fails to load Tears of the Kingdom. After sitting through an extended "Launching..." sequence, it cuts to a black screen for upwards of 5 minutes. Then the main menu of TOTK is displayed, but attempting to start a new save or load a save will cause an extended TOTK loading screen, which will freeze the game after it reaches approximately 100%.

### Expected Behavior

When launched through double clicking a shortcut, TOTK loads just fine within 30 seconds (but Steam input will be disabled). As well, when launched through Steam, other games are just fine (tested with Fire Emblem: Engage). Opening a terminal and executing Yuzu with the same arguments as through Steam will also cause TOTK to load like normal.

### Reproduction Steps

I've tried multiple other builds in an attempt to fix the issue, so I know some older build are affected by this as well. As well, the issue presents itself in "bursts" where I will be able to play the game for a couple of weeks without issue, but then the issue will present itself and restarting/reinstalling will not fix it for a couple of weeks. Then the issue will vanish and the game will be playable again.

As well, this issue has only presented itself on one of my machines (although due to the sporadic nature of it I don't know if that is because of differences in machine).

### Log File

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/11860637/yuzu_log.zip)

### System Configuration

CPU: i9-13900K
GPU/Driver: RTX 2070 Super
RAM: 32 GB
OS: Windows 11

**Comment by liamwhite** [comment]
Retry without mods

**Comment by alexander-novo** [comment]
I  retried and disabled all mods before launching. The issue persists. Here are new logs

[yuzu_log (2).zip](https://github.com/yuzu-emu/yuzu/files/11860747/yuzu_log.2.zip)

**Comment by Squall-Leonhart** [comment]
When you run vulkan games through steam, steam hijacks the VK pipeline cache and does a lengthy recompile of it on some starts.

Try to reproduce it with steams vulkan caches disabled.

**Comment by alexander-novo** [comment]
You seem to have hit the nail on the head - disabling shader precaching (which in the new Steam settings UI can be found under Steam > Settings > Downloads > Shader Pre-Caching) seems to have fixed the issue. It's a shame that this is a global setting and not per-game. I appreciate your knowledge on the situation, thanks.

**Comment by Hexaae** [comment]
> You seem to have hit the nail on the head - disabling shader precaching (which in the new Steam settings UI can be found under Steam > Settings > Downloads > Shader Pre-Caching) seems to have fixed the issue. It's a shame that this is a global setting and not per-game. I appreciate your knowledge on the situation, thanks.

Even with Steam Shader Pre-caching disabled, CEMU, when launched from Steam, takes much longer loading VK pipeline caches than running CEMU alone though...
From my tests with Yoshi's Woolly World:
- from scratch ~3min
- launching CEMU from Steam (with Shader Pre-Cache disabled), still ~2min
- launching CEMU alone 11-15secs
