### ISSUE TITLE
Dualsense vibration is not adjustable and is weak on default

### ISSUE THREAD

**Issue by AliKayal** [yuzu-emu/yuzu#10928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu 1479

### Description of Issue

I've been testing this issue with the older versions, and it seems with the newer versions of Yuzu my Dualsense vibration is not adjustable like it is set always on 100% and changing the scale doesn't help, neither via cable or Bluetooth.

I've actually been only testing this issue on the latest version of The Legend of Zelda: Tears of The Kingdom.

### Expected Behavior

The vibration in game doesn't feel changed either on 1% scale nor 150%, which is not the case with older versions and works fine there.

### Reproduction Steps

Using a Dualsense controller and testing by adjusting the vibration in a game, or compare to an older version like 1436 which was the one I compared to.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11885882/yuzu_log.txt)

### System Configuration

CPU: 12th Gen Intel(R) Core(TM) i9-12900H   2.50 GHz
GPU/Driver: Intel Iris Xe Graphics/ Nvidia Geforce RTX 3070Ti Laptop 8.0 GB
RAM: 24.0 GB
OS: Windows 11 Home 22H2

**Comment by german77** [comment]
Piracy is not allowed.
