### ISSUE TITLE
Unable to load saved game in Pokemon Brilliant Diamond

### ISSUE THREAD

**Issue by bergerkyle** [yuzu-emu/yuzu#10921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline e2967c2a65.ver 2023/06/21 

### Description of Issue

When I try to load a saved game in Pokemon Brilliant Diamond on android, the app crashes.

I am able to open up and play pokemon brilliant diamond on a new save file. I can do everything in the game and then I go to save the game which works and I close the app. When I come back to the game I get to the title screen and it says "press a to continue" and when I do that it loads for a half second and then crashes before going to the screen that displays saved games.

### Expected Behavior

Should be able to hit a button to see saved games and then load them.

### Reproduction Steps

1. Create a new game in pokemon brilliant diamond
2. save the game
3. close the app
4. reopen the app
5. try to navigate past the title screen (crashes)

### Log File

https://discord.com/channels/398318088170242053/402241866935828490/1122919426698776650

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11871437/yuzu_log.txt)

### System Configuration

CPU:Octa-core (2x2.85 GHz Cortex-X1 & 2x2.35 GHz Cortex-A78 & 4x1.80 GHz Cortex-A55)
GPU/Driver: Mali-G710 MP7
RAM: 8GB RAM
OS: Android 13 Pixel 7 pro

**Comment by Squall-Leonhart** [comment]
the file system fix that resolves this was checked in and merged on the 22nd

**Comment by bergerkyle** [comment]
okay great I will stay tuned for the update

**Comment by bergerkyle** [comment]
@Squall-Leonhart still not working with latest early access build. Did that include mainline 1478? 

https://discord.com/channels/398318088170242053/402241866935828490/1123782696368345149

**Comment by bergerkyle** [comment]
I was able to fix this by downgrading to brilliant diamond v1.0

**Comment by AntoineMaille** [comment]
I have the same problem, how do you rollback to 1.0
