### ISSUE TITLE
The player LED will be off

### ISSUE THREAD

**Issue by rcyggdra** [yuzu-emu/yuzu#10920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline-1477

### Description of Issue

The player LED will be off when using the controller from mainline-1477.
Using SDL2 of mainline-1476 can restore normal.
![image](https://github.com/yuzu-emu/yuzu/assets/8652464/2df071a6-00b3-48a6-9bbc-a7d0f861a572)
### Expected Behavior

none

### Reproduction Steps

none

### Log File

[   0.154191] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.154203] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.616983] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.701725] Frontend <Info> yuzu\main.cpp:GMainWindow:361: yuzu Version: yuzu 1477
[   0.701757] Frontend <Info> yuzu\main.cpp:LogRuntimes:240: MSVC Compiler: 1936 Runtime: 14.36.32532.0
[   0.701759] Frontend <Info> yuzu\main.cpp:LogRuntimes:249: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.701761] Frontend <Info> yuzu\main.cpp:GMainWindow:377: Host CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz | AVX2 | FMA
[   0.701767] Frontend <Info> yuzu\main.cpp:GMainWindow:379: Host CPU Cores: 4
[   0.701768] Frontend <Info> yuzu\main.cpp:GMainWindow:382: Host CPU Threads: 4
[   0.701882] Frontend <Info> yuzu\main.cpp:GMainWindow:383: Host OS: Windows 10 Version 1809
[   0.701898] Frontend <Info> yuzu\main.cpp:GMainWindow:385: Host RAM: 15.96 GiB
[   0.701900] Frontend <Info> yuzu\main.cpp:GMainWindow:386: Host Swap: 16.00 GiB
[   0.701973] Frontend <Info> yuzu\main.cpp:GMainWindow:391: Host Timer Resolution: 0.4959 ms
[   0.943486] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.4.0) applied successfully
[   0.945133] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.4.0) applied successfully
[   0.945133] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.4.0) applied successfully

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by rcyggdra** [comment]
> Fixed in [1478](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1478).

Yes, I have already tried.
Still not working.

**Comment by Squall-Leonhart** [comment]
my mistake, 1479 has the LED fix.

**Comment by rcyggdra** [comment]
now it's working.
Thank you for your work.
