### ISSUE TITLE
(Android) Samsung S23 Ultra will not load prod.key file.

### ISSUE THREAD

**Issue by ZeroFoxx** [yuzu-emu/yuzu#10948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access ddcc958336 / Mainline e2967c2a65

### Description of Issue

When attempting to load the product keys file on my Samsung Galaxy S23 Ultra, clicking on the file will not load the keys into the application.

I have attempted using both mainline and early access yuzu from the Play store, as well as verifying that the keys are properly dumped by making sure they load on other devices.

This issue only seems to happen on Samsung Galaxy S23 Ultra, though possibly may happen on other devices as well.

I have attempted reinstalling both applications by both normally uninstalling and manually deleting the application files using my PC. 

Finally, I have verified the location of the keys to be correct, as I've tried multiple locations on my S23 Ultra and had no issue loading the prod.keys from the same folder structure on another device.

### Expected Behavior

When product keys are loaded properly, it is usually accompanied by a pop-up stating such. There is no such pop-up on S23 Ultra, nor does the application function as if keys had been added.

### Reproduction Steps

On a Samsung Galaxy S23 Ultra device, attempt to load the product keys during the initial app setup or through the settings on the listed Yuzu versions.

### Log File

(As the application will not start without product keys, and I have attempted uninstalling multiple times, I do not have a log file at this time.)

### System Configuration

CPU: Snapdragon 8 gen. 2 (Qualcomm SM8550-AC)
GPU/Driver: Adreno 740
RAM: 12GB LPDDR5X
OS: Android 13 (OneUI 5.1)

**Comment by t895** [comment]
What is the name of your keys file? Currently we just check for the ".keys" extension so if you only have ".key" that will not be accepted.

**Comment by ZeroFoxx** [comment]
> What is the name of your keys file? Currently we just check for the ".keys" extension so if you only have ".key" that will not be accepted.

**Comment by ZeroFoxx** [comment]
(accidentally hit close on the issue, my apologies)

I have made sure that the file is prod.keys and not a .key extension.

**Comment by t895** [comment]
Where is the keys file located when you select it?

**Comment by ZeroFoxx** [comment]
I have tried in :/documents/ as well as in :/roms/
I've heard that longer directories can also cause issues and not to put it in downloads, so I avoid that.

**Comment by ZeroFoxx** [comment]
Welp!
I formatted my phone completely and it solved the issue... 
Guess that solves that 乁⁠(⁠ ⁠•⁠_⁠•⁠ ⁠)⁠ㄏ
I'll reopen this issue if it happens again.

**Comment by Smoovsky** [comment]
same problem goes here, though I'm not on Samsung Galaxy S23 Ultra, my device use the same SoC(8gen2 for Galaxy).
I managed to solve it by moving the key file to root folder.
