### ISSUE TITLE
Tales of Symphonia Remastered won't boot

### ISSUE THREAD

**Issue by tesla2105** [yuzu-emu/yuzu#10947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3715

### Description of Issue

The game won't boot, it's stuck on the loading screen. Then, the windows page file size starts to get bigger and bigger, and at about 30 GB the emulator finally crashes. 

### Expected Behavior

The game boots normally 

### Reproduction Steps

Just try to boot the game. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11900684/yuzu_log.txt)

### System Configuration

CPU: Intel Core i7 3770k
GPU/Driver: Nvidia GTX 1080 Driver ver. 536.23
RAM: Kingston HyperX Fury Beast DDR3 16GB 1866Mhz
OS: Windows 10 Pro version 22H2

**Comment by gidoly** [comment]
should boot on last release
