### ISSUE TITLE
Audio rattling.

### ISSUE THREAD

**Issue by Purplened** [yuzu-emu/yuzu#10965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1481 and before.

### Description of Issue

I've encountered an issue with the audio. It only happens with Yuzu, other games or audio sources in my pc don't mess up the output. Neither does the PS4 when the speakers are extracting audio from the monitor.
My setup includes speakers, which take the audio from my monitor via 3.5mm jack, at the same time this one taking the audio/video from my GPU via displayport.
When connecting the speakers directly to my motherboard there's no issue, but it's more convenient for my setup just to use the monitor audio since I have more devices connected to it.
When using the monitor audio, only the emulator distorts it and adds a whining/rattling to the game it's running, really annoying. The rattling changes as the games opens menus, and the audio feels less vibrant.
Only happens once it boots in the game, not before.
I'm just trying to inform the devs, but I'm sure you got lots of work ahead so don't take this as an urgent bug, just something it could be solved if it doesn't take too much time to figure out why this happens (maybe drivers or some displayport/hdmi standard).
Thank you so much for your patience.

### Expected Behavior

Audio being the same with speakers connected to motherboard and with speakers connected to monitor.

### Reproduction Steps

Changing the 3.5mm jack to the monitor, even with the game already booted, messes up the audio as described before.

### Log File

Happens in every pc I've tried, no log needed.

### System Configuration

CPU: AMD 5600X
GPU/Driver: Nvidia RTX 3060ti
RAM: 32GB DDR4 3200MHz
OS: Windows 10

**Comment by liamwhite** [comment]
what game?
is your monitor reporting a 2 channel or 6 channel audio config?
are you using auto audio backend? if so, does SDL backend or cubeb backend change the result?

**Comment by Purplened** [comment]
Games: TOTK and Astral Chain, could try more if you want to.
2/6 audio channel: Who do I check that?
Audio settings all in auto, tried sdl2 and cubeb but there was no difference.

**Comment by Purplened** [comment]
You're awesome, thanks
