### ISSUE TITLE
Android: Pokemon Regressions

### ISSUE THREAD

**Issue by sharpy66** [yuzu-emu/yuzu#10963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access -217e958a9-

### Description of Issue

(The Issue was not present with the same turnip drivers before the latest EA update)

Visual artifacts on the latest version(on turnip drivers, proprietary seems fine); were not present before.
![Screenshot_20230629_172218_yuzu](https://github.com/yuzu-emu/yuzu/assets/40325290/23d3bc1d-bec9-4d38-8829-ca9a84cb3cf4)

### Expected Behavior

Before the update ground textures were still messed up, but there weren't repeating visual artifacts across the screen.
![Screenshot_20230629_172637_Photos](https://github.com/yuzu-emu/yuzu/assets/40325290/bef33370-b0c1-44cc-8915-fac9e1a20d7a)

### Reproduction Steps

Simply run the game with the a7xx turnip drivers on the latest yuzu android EA build.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11911318/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 8+ Gen1
GPU/Driver: Adreno 730, Turnip A7xx V2/Fix2
RAM: 8GB
OS: Android 13, OneUI 5.1

**Comment by thesaviorsrule** [comment]
Here are a few more examples 
![Screenshot_yuzu_2023-06-29-20-19-49-329](https://github.com/yuzu-emu/yuzu/assets/136115244/0ea5a262-10b2-4183-b706-79bca058b086)
![Screenshot_yuzu_2023-06-29-20-18-37-142](https://github.com/yuzu-emu/yuzu/assets/136115244/598c4d6e-8312-456c-b7cd-a581cb76139f)
![Screenshot_yuzu_2023-06-29-20-18-01-472](https://github.com/yuzu-emu/yuzu/assets/136115244/f776e3ae-9306-40c3-9c37-5238d3e71349)

**Comment by sharpy66** [comment]
The issue is not present on Turnip A7xx 23.2.0 V2(the version without fixes)

**Comment by sharpy66** [comment]
Issue is known, and a fix is already in the development pipeline.

**Comment by bunnei** [comment]
The driver is not ready yet, this isn't a yuzu issue.
