### ISSUE TITLE
Android: Performance massively decreases if there's no consistent touch input on the screen

### ISSUE THREAD

**Issue by probablygarry** [yuzu-emu/yuzu#10975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu EA Android ddcc958336

### Description of Issue

In Android, when the game is minimized, it seems that it is running at its supposed performance, but when yuzu is on full screen, performance is presumably lower than what it could perform.

Video of showing the issue:
https://media.discordapp.net/attachments/1120603140895547392/1124617625587159140/Screenrecorder-2023-07-01-15-25-37-7402.mp4

### Expected Behavior

yuzu should be running at the speed/performance as when it is minimized (its supposed performance), not lower performance when on full screen (something is impairing it?)

### Reproduction Steps

- Open any game
- Tab out of yuzu by using the tab gesture/button (the recent apps panel / switching apps panel)
-  Increase in performance should be visible after that compared to when it is in full screen

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11925305/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 870
GPU/Driver: Adreno 650 / Mesa Turnip v23.2.0 Revision 3
RAM: 8 GB
OS: MIUI 14 / Android 13

**Comment by probablygarry** [comment]
UDPATE: It's not being minimized that increases the performance, but **a constant touch input movement** that made it perform better.

This means if there's no touch input on the screen, the performance will significantly drop, but also, if there's no **new touch movement** after a while, even if the finger on the screen (finger staying on one place without moving), the performance will also still drop.

Updated video showing constant touch movement vs no touch movement at all (at 00:30)

https://media.discordapp.net/attachments/1120603140895547392/1124635921933942875/Screenrecorder-2023-07-01-16-36-34-1142.mp4

**Comment by FearlessTobi** [comment]
Sadly this is how Android CPU governors work.
Performance will be throttled if the screen isn't touched.

There is not much we can do about this on our side.
