### ISSUE TITLE
Lockup on close of onscreen keyboard in tears of the kingdom.

### ISSUE THREAD

**Issue by anpilley** [yuzu-emu/yuzu#10983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3730

### Description of Issue

In Tears of the Kingdom, using the on-screen keyboard to save the name of a horse causes the game to lock up with an emulated game stack trace showing in the logs. 

This does not currently reproduce on mainline 1483.

I also think I heard someone complain about this in pokemon violet.

### Expected Behavior

Text entry saves and the player is prompted to save a horse with the name entered.

### Reproduction Steps

1. Play Totk to the point where you can capture and register a horse. 
2. Capture a horse, head to a stable to register.
3. Get to the point of text entry, name the horse, press + to save.
4. Onscreen keyboard closes, but game locks up and is unable to continue.

### Log File

`[ 206.939574] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1552: (STUBBED) called, result=0x0000E401
[ 206.939672] Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:Break:51: Userspace PANIC! info1=0x00000010596D0F78, info2=0x0000000000000004
[ 206.939675] Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:operator ():32: debug_buffer_err_code=E401
[ 206.939680] Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:Break:101: Emulated program broke execution! reason=0x0000000000000000, info1=0x00000010596D0F78, info2=0x0000000000000004
[ 206.939681] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:137: Backtrace, sp=00000010596D0DA0, pc=000000000CF3A498
[ 206.939683] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:139: Module Name         Address             Original Address    Offset              Symbol
[ 206.939683] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:140: 
[ 206.999639] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 0000007100158498    000000000CF3A498    0000000000158498    
[ 206.999646] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 0000007100091718    000000000CE73718    0000000000091718    nn::diag::detail::Abort(nn::Result const*)
[ 206.999647] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710008FD80    000000000CE71D80    000000000008FD80    
[ 206.999648] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710008FE48    000000000CE71E48    000000000008FE48    
[ 206.999648] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710008FF28    000000000CE71F28    000000000008FF28    
[ 206.999650] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710012FD98    000000000CF11D98    000000000012FD98    nn::os::detail::MultiWaitImplByHorizon::CancelWait()
[ 206.999652] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710012AE0C    000000000CF0CE0C    000000000012AE0C    nn::Result nn::os::detail::MultiWaitImpl::InternalWaitAnyImpl<false>(nn::os::detail::MultiWaitHolderBase**, bool, nn::TimeSpan, unsigned int)
[ 206.999652] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710012B138    000000000CF0D138    000000000012B138    nn::Result nn::os::detail::MultiWaitImpl::WaitAnyImpl<false>(nn::os::detail::MultiWaitHolderBase**, bool, nn::TimeSpan, unsigned int)
[ 206.999653] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 0000007100127B94    000000000CF09B94    0000000000127B94    nn::os::WaitAny(nn::os::MultiWaitType*)
[ 206.999654] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 00000071001C6D38    000000000CFA8D38    00000000001C6D38    nn::applet::WaitPopFromInteractiveOutChannelEvent(nn::applet::LibraryAppletHandle)
[ 206.999655] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 00000071003CBFE0    000000000D1ADFE0    00000000003CBFE0    nn::swkbd::ShowKeyboard(nn::swkbd::String*, nn::swkbd::ShowKeyboardArg const&, nn::swkbd::Trigger)
[ 206.999655] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007101B37438    0000000009B3B438    0000000001B37438    
[ 206.999656] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007101B37370    0000000009B3B370    0000000001B37370    
[ 206.999656] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007101ED47A4    0000000009ED87A4    0000000001ED47A4    
[ 206.999657] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007102AE9FDC    000000000AAEDFDC    0000000002AE9FDC    
[ 206.999658] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                00000071007102D8    00000000087142D8    00000000007102D8    
[ 206.999658] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007100B7F2E8    0000000008B832E8    0000000000B7F2E8    
[ 206.999659] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                00000071007102D8    00000000087142D8    00000000007102D8    
[ 206.999660] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007100DC83F4    0000000008DCC3F4    0000000000DC83F4    
[ 206.999660] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                00000071006F8828    00000000086FC828    00000000006F8828    
[ 206.999660] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                00000071006F8614    00000000086FC614    00000000006F8614    
[ 206.999661] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                000000710097E338    0000000008982338    000000000097E338    
[ 206.999661] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                00000071007E75D8    00000000087EB5D8    00000000007E75D8    
[ 206.999662] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007102AE27C8    000000000AAE67C8    0000000002AE27C8    
[ 206.999662] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                000000710078F82C    000000000879382C    000000000078F82C    
[ 206.999663] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                000000710078F190    0000000008793190    000000000078F190    
[ 206.999663] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007102A9E238    000000000AAA2238    0000000002A9E238    
[ 206.999664] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007102A3B388    000000000AA3F388    0000000002A3B388    
[ 206.999664] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710012A518    000000000CF0C518    000000000012A518    
[ 206.999665] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 00000071001302F4    000000000CF122F4    00000000001302F4    
[ 206.999665] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: unknown             0000007100000000    0000000000000000    0000000000000000    
[ 220.373626] Frontend <Warning> yuzu/bootmanager.h:ForceStop:106: Force stopping EmuThread
[ 220.384767] Service.HID <Info> core\hid\emulated_controller.cpp:SetPollingMode:1239: Set polling mode 0, device_index=1
[ 220.787420] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:SerializeVulkanPipelineCache:770: Vulkan driver pipelines cached at: C:\Users\ashridah\AppData\Roaming\yuzu\shader\0100f2c0115b6000\vulkan_pipelines.bin
[ 220.787420] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:SerializeVulkanPipelineCache:770: Vulkan driver pipelines cached at: C:\Users\ashridah\AppData\Roaming\yuzu\shader\0100f2c0115b6000\vulkan_pipelines.bin
`
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11926771/yuzu_log.txt)

### System Configuration

CPU: 12th gen I7-12700k
GPU/Driver: RTX 3070ti 8GB,  536.23.0.0
RAM: 32gb
OS: Win11 22h2

**Comment by tagg7** [comment]
I've experienced the same in multiple games recently (EA 3730) - anytime the onscreen keyboard is required, the game locks up.

**Comment by Squall-Leonhart** [comment]
relevant, formatted snippet

`[ 206.937307] Service.AM <Info> yuzu\applets\qt_software_keyboard.cpp:InitializeKeyboard:1605: 
KeyboardInitializeParameters:
ok_text=
header_text=
sub_text=
guide_text=
initial_text=
max_text_length=9
min_text_length=0
initial_cursor_position=0
type=8
password_mode=0
text_draw_type=0
key_disable_flags=44
use_blur_background=true
enable_backspace_button=true
enable_return_button=false
disable_cancel_button=false
[ 206.939574] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1552: (STUBBED) called, result=0x0000E401
[ 206.939672] Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:Break:51: Userspace PANIC! info1=0x00000010596D0F78, info2=0x0000000000000004
[ 206.939675] Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:operator ():32: debug_buffer_err_code=E401
[ 206.939680] Debug.Emulated <Critical> core\hle\kernel\svc\svc_exception.cpp:Break:101: Emulated program broke execution! reason=0x0000000000000000, info1=0x00000010596D0F78, info2=0x0000000000000004
[ 206.939681] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:137: Backtrace, sp=00000010596D0DA0, pc=000000000CF3A498
[ 206.939683] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:139: Module Name         Address             Original Address    Offset              Symbol
[ 206.939683] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:140: 
[ 206.999639] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 0000007100158498    000000000CF3A498    0000000000158498    
[ 206.999646] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 0000007100091718    000000000CE73718    0000000000091718    nn::diag::detail::Abort(nn::Result const*)
[ 206.999647] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710008FD80    000000000CE71D80    000000000008FD80    
[ 206.999648] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710008FE48    000000000CE71E48    000000000008FE48    
[ 206.999648] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710008FF28    000000000CE71F28    000000000008FF28    
[ 206.999650] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710012FD98    000000000CF11D98    000000000012FD98    nn::os::detail::MultiWaitImplByHorizon::CancelWait()
[ 206.999652] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710012AE0C    000000000CF0CE0C    000000000012AE0C    nn::Result nn::os::detail::MultiWaitImpl::InternalWaitAnyImpl<false>(nn::os::detail::MultiWaitHolderBase**, bool, nn::TimeSpan, unsigned int)
[ 206.999652] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710012B138    000000000CF0D138    000000000012B138    nn::Result nn::os::detail::MultiWaitImpl::WaitAnyImpl<false>(nn::os::detail::MultiWaitHolderBase**, bool, nn::TimeSpan, unsigned int)
[ 206.999653] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 0000007100127B94    000000000CF09B94    0000000000127B94    nn::os::WaitAny(nn::os::MultiWaitType*)
[ 206.999654] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 00000071001C6D38    000000000CFA8D38    00000000001C6D38    nn::applet::WaitPopFromInteractiveOutChannelEvent(nn::applet::LibraryAppletHandle)
[ 206.999655] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 00000071003CBFE0    000000000D1ADFE0    00000000003CBFE0    nn::swkbd::ShowKeyboard(nn::swkbd::String*, nn::swkbd::ShowKeyboardArg const&, nn::swkbd::Trigger)
[ 206.999655] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007101B37438    0000000009B3B438    0000000001B37438    
[ 206.999656] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007101B37370    0000000009B3B370    0000000001B37370    
[ 206.999656] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007101ED47A4    0000000009ED87A4    0000000001ED47A4    
[ 206.999657] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007102AE9FDC    000000000AAEDFDC    0000000002AE9FDC    
[ 206.999658] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                00000071007102D8    00000000087142D8    00000000007102D8    
[ 206.999658] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007100B7F2E8    0000000008B832E8    0000000000B7F2E8    
[ 206.999659] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                00000071007102D8    00000000087142D8    00000000007102D8    
[ 206.999660] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007100DC83F4    0000000008DCC3F4    0000000000DC83F4    
[ 206.999660] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                00000071006F8828    00000000086FC828    00000000006F8828    
[ 206.999660] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                00000071006F8614    00000000086FC614    00000000006F8614    
[ 206.999661] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                000000710097E338    0000000008982338    000000000097E338    
[ 206.999661] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                00000071007E75D8    00000000087EB5D8    00000000007E75D8    
[ 206.999662] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007102AE27C8    000000000AAE67C8    0000000002AE27C8    
[ 206.999662] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                000000710078F82C    000000000879382C    000000000078F82C    
[ 206.999663] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                000000710078F190    0000000008793190    000000000078F190    
[ 206.999663] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007102A9E238    000000000AAA2238    0000000002A9E238    
[ 206.999664] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007102A3B388    000000000AA3F388    0000000002A3B388    
[ 206.999664] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 000000710012A518    000000000CF0C518    000000000012A518    
[ 206.999665] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 00000071001302F4    000000000CF122F4    00000000001302F4    
[ 206.999665] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: unknown             0000007100000000    0000000000000000    0000000000000000    
[ 220.373626] Frontend <Warning> yuzu/bootmanager.h:ForceStop:106: Force stopping EmuThread`

**Comment by pierre-lgb** [comment]
I was experiencing the same issue in EA 3730 but after updating to 3731 it seems to be fixed.

**Comment by UdonOli** [comment]
I have something similar where in fullscreen it requires me to ctrl-alt-del and then exit out of the ctrl-alt-del menu to get the keyboard to appear, but the background game footage is still broken until I am finished typing. It's quite annoying but at least it doesn't crash like it seems to for you guys.

**Comment by Morph1984** [comment]
This was a regression during the development of #10969, which has since been fixed.
