### ISSUE TITLE
Android: "Master Detective Archives: Rain Code"  - Textures displayed as black

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#10980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Acces ddcc958336

### Description of Issue

the game has black textures bug

![Screenshot_20230701-075624_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/f74d73c3-4531-48ac-825c-796c2bfb6e3e)
![Screenshot_20230701-075635_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/46d8b841-a65c-4a18-a08f-d5f916f85390)

### Expected Behavior

it should look like this

![Screenshot_20230701-081350_Fotos](https://github.com/yuzu-emu/yuzu/assets/4172898/dbb1472b-9300-4d20-82bd-bf7b0561abfb)
![Screenshot_20230701-081140_Fotos](https://github.com/yuzu-emu/yuzu/assets/4172898/dca77d14-3639-46e6-bf57-9f42edcc9cff)

### Reproduction Steps

Play normally

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11926483/yuzu_log.txt)

### System Configuration

CPU: sd860
GPU/Driver: adreno 640/ turnip drivers 
RAM: 8gb
OS: android 13

**Comment by fullmetalik** [comment]
Hi , did you get to know how to fix this erro?
