### ISSUE TITLE
exefs skyline mod changes title id, making update & romfs not able to load

### ISSUE THREAD

**Issue by learnmlcolab** [yuzu-emu/yuzu#10982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1482

### Description of Issue

I want to play Summer Pockets: Reflection Blue (0100273013ECA000) on my linux laptop, so I'm trying out yuzu. Since the game isn't in English, I want to load the English mod here: https://github.com/masagrator/SPRB-ENX/releases/tag/1.0.2

But when I tried to run the game, its title id is changed and the update & romfs mod don't load.

The update does load if I run the game without the mod.

* Game properties before running:

![image](https://github.com/yuzu-emu/yuzu/assets/111139833/c52a0c32-1a82-4c18-9b0b-a81670bfc5ac)

* Game properties when running (notice the Title ID is changed and there's nothing in Add-Ons):

![image](https://github.com/yuzu-emu/yuzu/assets/111139833/e65a3ad7-ac2c-4c26-b756-574211950ccc)

### Expected Behavior

* Title ID shouldn't change
* Update & romfs mod should load correctly

### Reproduction Steps

1. Get the game Summer Pockets: Reflection Blue (0100273013ECA000)
2. Load the `v1.0.1` update to NAND.
3. Get the english mod [here](https://github.com/masagrator/SPRB-ENX/releases/tag/1.0.2).
4. Extract, and copy `exefs` & `romfs` to `<yuzu_folder>/load/0100273013ECA000/en/` (or extract it to `<yuzu_folder>/sdmc/`)
5. Run the game.
6. Open Emulation -> Configure Current Game, notice that the Title ID has changed to something else (0100ABD01785C000), version is `1.0.0` and there's nothing in Add-Ons tab.
7. The game UI is translated but the game content isn't, so my guess is that `exefs` is loaded but `romfs` isn't, and version is `v1.0.0` so I guess update is also not loaded.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11926581/yuzu_log.txt)

### System Configuration

CPU: Intel i5-8265U
GPU/Driver: Tried both OpenGL (GLSL) and Vulkan (Intel UHD 620)
RAM: 12GiB
OS: archlinux

**Comment by learnmlcolab** [comment]
Update:

If I also copy the mod to the new title id's load folder, it seems to load correctly, both the game ui and game content are translated. But I see that the version is still v1.0.0 and there's no Update row in Add-Ons tab, so I think the update isn't loaded:
![image](https://github.com/yuzu-emu/yuzu/assets/111139833/612ae2ae-dc26-408c-8c1d-6ad07c4b78dc)

Log for this: 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11926610/yuzu_log.txt)

**Comment by Squall-Leonhart** [comment]
I suspect a fautly mod, because 0100ABD01785C000 is the title id for Portal 2.

**Comment by learnmlcolab** [comment]
Thanks @Squall-Leonhart, the new mod works fine for me.

Since the old mod works for the hardware, I think yuzu should work fine with it too (and mod shouldn't be able to change title id like that). So I'm leaving this issue open, but feel free to close it if the yuzu maintainers think otherwise.

**Comment by Squall-Leonhart** [comment]
Mods "Should" actually be able to change the title ID, i would consider it a limitation on the hardware that it doesn't here, but it is a fact that the hardware behavior deviates from the emulator, and probably doesn't on ryujnx.

**Comment by liamwhite** [comment]
The existing code intentionally rereads the NPDM after patching:
https://github.com/yuzu-emu/yuzu/blob/184ee2d890baa82be7d92af4f9c864e6893f3490/src/core/loader/deconstructed_rom_directory.cpp#L98-L125

If this is inconsistent with how mod loading on hardware works, I can just remove the re-reading.
