### ISSUE TITLE
Secret VR Mode

### ISSUE THREAD

**Issue by Jorerim** [yuzu-emu/yuzu#1099]
Hello everyone, I know it may not be top priority right now, but maybe would be nice to have it implemented. The dolphin emulator has stereoscopic support.
The native VR mode for switch
https://www.fudzilla.com/news/gaming/46977-switch-has-a-secret-vr-mode

**Comment by roblaplante** [comment]
oh my god it could be so fun !!!!!

**Comment by lioncash** [comment]
Locking this due to people not knowing they could have just +1'd the request instead of commenting. The issue itself is still more or less valid.

**Comment by german77** [comment]
Added in #5810
