### ISSUE TITLE
Pikmin 3 Yuzu Crash on results of side stories 

### ISSUE THREAD

**Issue by AbePZ** [yuzu-emu/yuzu#10991]
### Issue

The game crash when trying to continue, any solution???
![Captugdfra](https://github.com/yuzu-emu/yuzu/assets/138341754/382991fd-6526-4bd9-805c-8b6ed855f191)

**Comment by Squall-Leonhart** [comment]
>  A blank issue template for developers only. If you are not a developer, do not use this issue template. **Your issue WILL BE CLOSED if you do not use the appropriate issue template.**
