### ISSUE TITLE
YUZU EA3733 work with SDL 2.28.1 problem

### ISSUE THREAD

**Issue by lovelygfj** [yuzu-emu/yuzu#10995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3733

### Description of Issue

SDL 2.28.1 fixed the issue of the third-party controller (BETOP) not being recognized in NS compatibility mode. However, when working with YUZU, the controller is initially recognized but after approximately 3 minutes of gameplay, all buttons become unresponsive. Switching from fullscreen to windowed mode, or from windowed mode to fullscreen, restores normal functionality for another 3 minutes. Additionally, when replace SDL2.dll to the latest version (V2.28.1) for the first time, YUZU initially detects the gamepad as BETOP NS mode, but subsequently identifies it as a Switch Pro controller, without ever recognizing it as BETOP again. I'm not sure whether I should report this issue to SDL or YUZU. If you could assist in investigating this matter, I would greatly appreciate it.

### Expected Behavior

-

### Reproduction Steps

-

### Log File

-

### System Configuration

CPU: 13900K
GPU/Driver: RTX 4090 Latest
RAM: 64G DDR5
OS: WIN11 PRO

**Comment by lovelygfj** [comment]
SDL V2.0.20 works perfect in YuZu

**Comment by german77** [comment]
I included a few fixes of 2.28.1 due to be relevant for controller support. This sounds like a sdl issue but I don't know why changing Fullscreen mode makes the controller work again.

Make sure steam isn't running on the background.

**Comment by lovelygfj** [comment]
> I included a few fixes of 2.28.1 due to be relevant for controller support. This sounds like a sdl issue but I don't know why changing Fullscreen mode makes the controller work again.
> 
> Make sure steam isn't running on the background.

yes, no steam running in the background.
It's a little bit strange.
