### ISSUE TITLE
GDB Stub still references 3ds hardware

### ISSUE THREAD

**Issue by jroweboy** [yuzu-emu/yuzu#11]
https://github.com/yuzu-emu/yuzu/blob/master/src/core/gdbstub/gdbstub.cpp#L67

The gbdstub is currently very non functional. Making this issue as a reminder to make a new one that could be backported over to citra as well. Currently investigating porting over rosalina's gdbstub as I've heard good things about it in the past. If we aren't going to be fixing it any time soon, perhaps we should consider just removing it then.

**Comment by rodjun** [comment]
Also found some strings mentioning the 3DS and citra while lurking through the code:

https://github.com/yuzu-emu/yuzu/blob/master/src/yuzu/main.cpp#L62

**Comment by jroweboy** [comment]
Fixed in https://github.com/yuzu-emu/yuzu/pull/129
