### ISSUE TITLE
[Question] Yuzu game shutdown time

### ISSUE THREAD

**Issue by x1unix** [yuzu-emu/yuzu#11008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Hello, can you please explain why it takes so much time for Yuzu to close the program compared to the regular Nintendo Switch?

What does Yuzu do during a program close process?
Is there any additional work performed by Yuzu during shutdown compared to the Horizon OS?

Thank you.

### Why would this feature be useful?

n/a

**Comment by sharpy66** [comment]
Because it has to stop emulating the switches CPU/GPU, then clear ram, save shaders to storage, clear any unnecessary temp data still lying around, update the yuzu apps UI, all while windows and other apps are running in the background...
