### ISSUE TITLE
Yuzu ea regression (Android)

### ISSUE THREAD

**Issue by godpow** [yuzu-emu/yuzu#11005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

ddcc958336.ver

### Description of Issue

The issue happens with a couple of games like Pokemon and XenoVerse chronicles and some others on 7xx using the 7xx turnip drivers. It makes the screen glitchy and hard to see the game. The latest mainline build that introduced the mali update doesn't have the issue.

### Expected Behavior

It's supposed to be more clear looking and not glitchy.
![Screenshot_2023-06-29-22-15-56-496](https://github.com/yuzu-emu/yuzu/assets/17231911/2239b5fb-427b-4292-ac89-210817d7531e)
https://youtu.be/76iGzRFzsmU

### Reproduction Steps

On snapdragon 8 gen 1 or gen 2 and possiblity other devices with adreno 7xx use the latest turnip on mainline then try it on the latest ea update.

### Log File

[yuzu_log_ea.txt](https://github.com/yuzu-emu/yuzu/files/11933091/yuzu_log_ea.txt)
[yuzu_log_mainline.txt](https://github.com/yuzu-emu/yuzu/files/11933092/yuzu_log_mainline.txt)

### System Configuration

Red magic 8 pro 

Sd8g2
16gb ram
512 gb

**Comment by sharpy66** [comment]
Also happens on Xenoblade DE and DBZ: Kakarot

**Comment by bunnei** [comment]
This driver is not ready yet. These are driver bugs, not yuzu issues.
