### ISSUE TITLE
TOTK : Game going from 99.95% completion to 00.00% instead of a 100%

### ISSUE THREAD

**Issue by zayydd22** [yuzu-emu/yuzu#11000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3734

### Description of Issue

After discovering my last location, my game completion percentage went from 99.95% to 00.00% instead of a 100%.
It seems that a "1" is missing in "00.00%".

### Expected Behavior

Screenshots : 

![Capture 2](https://github.com/yuzu-emu/yuzu/assets/138397996/9309e473-80ca-4276-b968-f890fa40a63d)

![Capture](https://github.com/yuzu-emu/yuzu/assets/138397996/c6603ed7-450c-48e7-a92c-bb43f2256e1a)

### Reproduction Steps

[Savefile.zip](https://github.com/yuzu-emu/yuzu/files/11931245/Savefile.zip)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11931189/yuzu_log.txt)

### System Configuration

CPU: i5 8400
GPU/Driver: RTX 3070 on driver 531.68
RAM: Corsair 16 GB 2133 Mhz Overclocked to 3200 Mhz
OS: W10 22H2

**Comment by Squall-Leonhart** [comment]
This is a game bug, not a yuzu bug.
