### ISSUE TITLE
Persona 5 Royal System data Corrupted

### ISSUE THREAD

**Issue by blakbin** [yuzu-emu/yuzu#11013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3702++

### Description of Issue

Using Yuzu EA 3702 and up this message appears in game while saving or loading a game, player still can load or save game but with popup came out every save or load. If system data in yuzu save folder is deleted then the game will try creating one but failed to create system file causing endless loop.

![ezgif-3-034d128765](https://github.com/yuzu-emu/yuzu/assets/3345247/de59edc0-ed2e-4257-9de6-8d3f6e67adb1)

This Message will not appear if using Yuzu EA 3701 downward.

The last change about filesystem i think its in [vfs_real: misc optimizations]( https://github.com/yuzu-emu/yuzu/commit/734242c5bcd56dbd7fc69fb49dba5b7d5ca090bc) @liamwhite 

### Expected Behavior

File System successfully saved!

### Reproduction Steps

try loading a game

### Log File

- Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:875: called.

### System Configuration

CPU: Ryzen 5 5500
GPU/Driver: RX580 / AMD
RAM: 16GB
OS: Windows 11

**Comment by liamwhite** [comment]
Provide some save data to test with

**Comment by blakbin** [comment]
Actually this not an error, because in EA3701 it loads the system file without any issue.
[SYSTEM.zip](https://github.com/yuzu-emu/yuzu/files/11941283/SYSTEM.zip)
