### ISSUE TITLE
HD Rumble support using device vibration in Android devices

### ISSUE THREAD

**Issue by tovarishes** [yuzu-emu/yuzu#11019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Currently the android version doesn't support HD rumble using the device's vibration feature. Skyline supports this and has their source code open.
Could Yuzu support HD rumble?

### Why would this feature be useful?

This feature improve the game playing experience of mulitple games as well as support games that need the vibration feature.

**Comment by rogeriskira** [comment]
I second this. Rumble support would definitely be great! Especially with DualSenseJoycons support.

**Comment by tovarishes** [comment]
Open source Skyline already has a decent implementation. Can that not be (re)used?

**Comment by tovarishes** [comment]
HD rumble implementation is now available. Thanks devs.

**Comment by evil-trainer** [comment]
> HD rumble implementation is now available. Thanks devs.

It's actually standard rumble. HD Rumble will com in the future 😁
