### ISSUE TITLE
bug controller ps4  not work 

### ISSUE THREAD

**Issue by fq38** [yuzu-emu/yuzu#11015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

3700

### Description of Issue

since the release of the Yuzu EA 3700 ps4 controller version does not work bug disconnects the controller

### Expected Behavior

not aplly

### Reproduction Steps

not aplly

### Log File

not aplly

### System Configuration

CPU:10600k
GPU/Driver:1660ti
RAM:16
OS:w10

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum. 
Please use our Discord for support requests.
