### ISSUE TITLE
Tears of the Kingdom gloom hands and frox dont spawn. 

### ISSUE THREAD

**Issue by valkyrie743** [yuzu-emu/yuzu#11026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

using early access 3739 but applies ever to past builds since mod came out (24 days ago)

### Description of Issue

In tears of the kingdom running update 1.1.2 with a mod from serfrost called interior defogger here https://gamebanana.com/mods/446995  the game will fail to load 2 enemy types. one is the gloom hands and another is frox. frox will sometimes spawn really quick then appear to fall or clip into the ground and then disappear.  

this mod uses  LayeredFS and uses the Bootup.Nin_NX_NVN.pack.zs file. i've tested this on my computer as well as my physical switch. the issue does not present on my switch nor does it on ryujynx. i've contacted the mod creator serfrost on reddit and believes its an issue with yuzu being that on original hardware and ryujynx this issue is not present. 

below is a video i recorded showing this issue in action. the first half of the video is with the mod enabled and showing the gloom hands not spawning inside the deku tree and then when going to the depths to a spawn location for a frox it will spawn then quickly fall though the ground and disappear. the second half of the video shows with the mod disabled and showing both enemies spawning properly without issues. 

https://youtu.be/rgAMF4FfV3k
 
i understand that this is a mod but being that this issue does not happen on original hardware i figured that there is an issue with how this mod is handled with yuzu and possibly can be fixed 

### Expected Behavior

the enemy types should spawn without issues.

### Reproduction Steps

load the mod with update 1.1.2 and go to the great deku tree and dive into the chasm inside for gloom hands then go into the depths to a frox spawn location . with mod enabled they dont spawn and with mod disabled they spawn. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11954201/yuzu_log.txt)

### System Configuration

CPU: Ryzen 9 5950X
GPU/Driver: RTX 4090 driver 532.03
RAM: 32gb ddr4 3200 mhz 
OS: windows 11

**Comment by liamwhite** [comment]
Does this issue happen on
- 1x scaling
- older versions of yuzu EA (e.g. 3602)

**Comment by valkyrie743** [comment]
> 

just tested with 1x scaling on ea build 3600 as well as mainline 1468 and bug is still present.

**Comment by liamwhite** [comment]
Cannot confirm with yuzu 1487 / latest interior defogger / update 1.1.2, both Froxes and Gloom Spawn appear correctly on my system. (RDNA2 RADV)
![Screenshot from 2023-07-05 21-51-23](https://github.com/yuzu-emu/yuzu/assets/9658600/411e7ea1-7b9c-42db-a4b0-25e3e559d7b1)
![0100f2c0115b6000_2023-07-05_22-01-22-006](https://github.com/yuzu-emu/yuzu/assets/9658600/be58d0f6-3fe9-4ed7-a52c-636702070904)

https://github.com/yuzu-emu/yuzu/assets/9658600/8392caa5-245d-4628-9fc7-b0eb1900b99b

**Comment by valkyrie743** [comment]
> Cannot confirm with yuzu 1487 / latest interior defogger / update 1.1.2, both Froxes and Gloom Spawn appear correctly on my system. (RDNA2 RADV) ![Screenshot from 2023-07-05 21-51-23](https://user-images.githubusercontent.com/9658600/251321717-411e7ea1-7b9c-42db-a4b0-25e3e559d7b1.png) ![0100f2c0115b6000_2023-07-05_22-01-22-006](https://user-images.githubusercontent.com/9658600/251321821-be58d0f6-3fe9-4ed7-a52c-636702070904.png)
> 
>  1.mp4

well this is odd. i just saw that he updated it to work with 1.2.0 patch (i didnt update yet) but i redownloaded the mod and reinstalled it and now its working with no issues.  hmm not sure if he updated it while also updating to work with 1.2.0 or what i had was corrupted?   hmm.  

i was just going to post that after a random set amount of time (with the mod disabled i have another issue with the game just randomly locking up and crashing. i looked at the log file and the last few lines read 

[3531.957631] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:587: 0xac91d35b3a750502
[3531.957855] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:587: 0x9622a34a74f510d6
[3535.091771] Service.FS <Warning> core\hle\service\filesystem\fsp_srv.cpp:Commit:480: (STUBBED) called
[3544.742086] Service.FS <Warning> core\hle\service\filesystem\fsp_srv.cpp:Commit:480: (STUBBED) called
[3552.016320] Render.Vulkan <Critical> video_core\vulkan_common\vulkan_device.cpp:ReportLoss:696: Device loss occurred!
[3552.016473] Render.Vulkan <Critical> video_core\vulkan_common\vulkan_device.cpp:ReportLoss:696: Device loss occurred!
[3563.651067] Frontend <Warning> yuzu/bootmanager.h:ForceStop:106: Force stopping EmuThread
[3563.651489] Service.Nvnflinger <Error> core\hle\service\nvnflinger\buffer_queue_producer.cpp:DequeueBuffer:258: no available buffer slots


so i figured it may be an issue with nvidia drivers and vulkan. but being that this crash happened with the mods disabled it probably was not related.

**Comment by liamwhite** [comment]
Closing until we have a repro for it then
