### ISSUE TITLE
Afterimage

### ISSUE THREAD

**Issue by Darkherman** [yuzu-emu/yuzu#11028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

e2967c2a65

### Description of Issue

Game closes at the beginning of the loading screen

### Expected Behavior

[Video](https://1drv.ms/v/s!AnPmakszDBxwmyWDEDk3FipqgsOn)

### Reproduction Steps

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11959934/yuzu_log.txt)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11959926/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 8 Gen 1
GPU/Driver: None
RAM:8GB
OS: Android 13

**Comment by liamwhite** [comment]
You do not have enough memory to run this game
