### ISSUE TITLE
Remake Buttons and Manual Show Overly 

### ISSUE THREAD

**Issue by Rekkusu09** [yuzu-emu/yuzu#11036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Hide L3 and R3 manually if not usable for other games and make ram available notification show not just once but every time we open new game/ other game. Change design also for the left buttons to be thesame as ppsspp buttons /vita3k buttons . 
![Picsart_23-07-06_21-22-02-311](https://github.com/yuzu-emu/yuzu/assets/133083456/26ced21d-5900-4efd-9bad-c86eebd712db)

### Why would this feature be useful?

Because L3 and R3 are not useful in some games.. and other thing is the button looks way more better thsn the current version of the left side buttons.

**Comment by FearlessTobi** [comment]
You can hide the buttons manually.

**Comment by Rekkusu09** [comment]
> You can hide the buttons manually.

But everything of buttons vanished . I want the unneeded button to be the only one gets hidden such as L3 and R3 . We dont use that always.
