### ISSUE TITLE
cpp-httplib has moved to 0.13 - breaking build.

### ISSUE THREAD

**Issue by solarisfire** [yuzu-emu/yuzu#11044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3743-1

### Description of Issue

Yesterday cpp-httplib changed version numbers from 0.12.6-1 to 0.13.0-1.

CMakeLists.txt is looking for:

find_package(httplib 0.12 MODULE COMPONENTS OpenSSL)

So build is failing with:

`CMake Error at externals/CMakeLists.txt:113 (add_subdirectory):
  add_subdirectory given source "cpp-httplib" which is not an existing
  directory.`

### Expected Behavior

Successful Build

### Reproduction Steps

Build yuzu with cpp-httplib 0.13.0-1.

### Log File

No log file, as this is a build issue not a runtime issue.

### System Configuration

CPU: 5800X3D
GPU/Driver: Nvidia RTX 3090
RAM: 32GB
OS: Arch Linux

**Comment by abouvier** [comment]
If a compatible `cpp-httplib` system library is not found, it will use the one in `externals/cpp-httplib`. But this directory is empty because you didn't udpate the `cpp-httplib` submodule.

**Comment by solarisfire** [comment]
Because "I" didn't update?

I'm just installing via the Arch User Repository...

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yuzu-early-access

Either this needs to be fixed in the AUR PKGBUILD script or needs to be fixed here... It's not down to me to fix either, but it will affect all Arch Linux users until it's fixed. I'm just letting people know...

**Comment by v1993** [comment]
AUR packages are not supported by yuzu team, *especially* not early access one. Please take issues with them to their maintainers, not here.

**Comment by Tortillas-IT** [comment]
> AUR packages are not supported by yuzu team, _especially_ not early access one. Please take issues with them to their maintainers, not here.

"especially not early access one" lol yuzu is open source and it uses the GPL license 3.0, there's no reason to complain users who uses yuzu early access for free, just make this emulator closed source then

**Comment by v1993** [comment]
GPL gives you the right to build yuzu EA yourself, correct. However, it says nothing about anyone being obligated to provide support for such builds. It's that simple.

**Comment by solarisfire** [comment]
Wow, this thread got dramatic (and a little rude) for just changing a 0.12 to a 0.13...

It will have to be updated for the mainline build on every Linux distro (as each one upgrades cpp-httplib eventually). I don't see why someone can't just update a cmakelist...

**Comment by grandchild** [comment]
I posted the required change to the PKGBUILD [on the AUR page](https://aur.archlinux.org/packages/yuzu-early-access#comment-923252).

If yuzu also wants to update their `cpp-httplib` version to `0.13.*` -- that's for them to decide. Seems to build fine with it on Linux on my machine.
