### ISSUE TITLE
Entry Point not Found

### ISSUE THREAD

**Issue by Ch1nd0r** [yuzu-emu/yuzu#11065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline - bcba0867e

### Description of Issue

Yuzu throws error upon startup:

yuzu.exe - Entry Point Not Found
The procedure entry point MiniDumpWriteDump could not be located
in the dynamic link library
C:\Users\User\Desktop\yuzu-windows-msvc-20230709-bcba0867e\yuz
u-windows-msvc\yuzu.exe.

### Expected Behavior

Yuzu is expected to startup.

### Reproduction Steps

Reproduced by starting Yuzu with this problem.

### Log File

Unable to acquire a log file as I cannot start Yuzu.

### System Configuration

CPU: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz (4 CPUs), ~3.4GHz
GPU/Driver: GeForce GTX 950
RAM: 16 GB
OS: Windows 8.1

**Comment by Morph1984** [comment]
Windows 8.1 is not supported.
