### ISSUE TITLE
REQ: Please ADD option to adjust / increase RUMBLE intensity / Duration / Frequency on Pro Controller 🎮 

### ISSUE THREAD

**Issue by Fasto5** [yuzu-emu/yuzu#11066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Issue: 
Rumble on official Pro Controller 🎮 via PC emulation is quite weak.

Feature Request:
Please add settings to allow users to custom specify the intensity of Rumble to match their preference for a game (either intensity such as Low, Med, High, or more Advanced Options for Rumble, such as: Frequency, Duration & Intensity Parsmeters). 

### Why would this feature be useful?

Having custom control over the Rumble will enhance game enjoyment and a player's experience.

**Comment by german77** [comment]
This option already exist. 
![image](https://github.com/yuzu-emu/yuzu/assets/5944268/f72f36c4-bc8f-4f66-a5ee-9d93f6bae648)
