### ISSUE TITLE
gdbstub: Breakpoint regression since 1469

### ISSUE THREAD

**Issue by RoccoDev** [yuzu-emu/yuzu#11062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1469 onwards

### Description of Issue

When using the GDB stub in Yuzu 1469 or newer (1468 is not affected), set breakpoints don't work properly.

Instead of stopping at the requested instruction, a SIGTRAP is generated for the next instruction instead. Because the instructions don't match, GDB doesn't treat it as a breakpoint, making analysis much harder.

### Expected Behavior

When a breakpoint is set at address *A*, the program flow stops before a thread executes the instruction at address *A*.

### Reproduction Steps

1. Enable the GDB stub
2. Start a game
3. Connect to the GDB stub (`(gdb) target remote :6543`)
4. Set a breakpoint (e.g. at the start of `nnMain`)
5. Resume the game (`(gdb) c`)

### Log File

[yuzu-log.txt](https://github.com/yuzu-emu/yuzu/files/11995549/yuzu-log.txt)

### System Configuration

CPU: Ryzen 3600
GPU/Driver: NVIDIA GeForce GTX 1660 Super / 535.54.03
RAM: 32 GB
OS: Fedora 38, based on Linux 6.3.8

GDB client: 
```
GNU gdb (GDB) Fedora Linux 13.1-4.fc38
This GDB was configured as "x86_64-redhat-linux-gnu".
```

**Comment by liamwhite** [comment]
#11063
