### ISSUE TITLE
Auto screen rotation function is gone after update

### ISSUE THREAD

**Issue by Finblade** [yuzu-emu/yuzu#11076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android EA 28598c909

### Description of Issue

Before devs updated auto screen rotation function and it worked perfect. But now after update auto screen rotation function is broken. Unless turn on rotate screen button at phone's status bar, it does not work. It should be rotated well even though the screen rotate button at status bar is turned off. Please fix it.

### Expected Behavior

It should be rotated well even though the screen rotate button at status bar is turned off. 

### Reproduction Steps

Just run the game and rotate the phone and it does not rotate to other landscape side.

### Log File

I think no need to log because its not about graphic or glitch bug.

### System Configuration

CPU: 8+gen1
GPU/Driver: adreno730
RAM: 8gb
OS: android 12

**Comment by t895** [comment]
Fixed in #11337
