### ISSUE TITLE
Dumped romFs for "Klonoa: Phantasy Reverie Series" doesn't dump all assets

### ISSUE THREAD

**Issue by inconsistent-dg** [yuzu-emu/yuzu#11071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1492

### Description of Issue

After dumping the romFs of Klonoa PRS, I do not get all of the files that should be dumped. I am left with an incomplete dump that is ~218mb, compared to it being ~3gb when dumped on the _other_ emulator, or on real hardware.

### Expected Behavior

The entire romFs should be dumped, instead of the small amount of assets it dumps currently. 

### Reproduction Steps

- Dump Klonoa: Phantasy Reverie Series and add it to game list
- Right click on it and dump the full romFs
- Opening the folder, not all files are there

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12011121/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7 5800x
GPU/Driver: AMD Radeon RX 6600 XT, Adrenalin Edition version 23.2.2
RAM: 32gb
OS: Windows 10 22H2, x64

**Comment by liamwhite** [comment]
This game is multiprogram, so only the romfs from the ...000 NCA gets dumped. If you extract the 001 and 002 NCAs with e.g. hactool or hactoolnet, you can dump the romfs from those in yuzu without a problem. Only extracting from the 000 NCA is a well-known limitation at the moment. (I have no clue what you mean by dumping it "on real hardware".)
