### ISSUE TITLE
Mario Kart 8 Deluxe not showing Miis

### ISSUE THREAD

**Issue by Butterscotch96** [yuzu-emu/yuzu#11079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1494

### Description of Issue

Put Mario Kart 8 Deluxe on my Steam Deck using the Yuzu AppImage included with EmuDeck. 
No more video take a screenshot instead. I can't fit it under 10mb.
![Screenshot 2023-07-12 at 5 25 21 PM](https://github.com/yuzu-emu/yuzu/assets/134971065/b463de76-bf24-410c-826b-bb82e33bf6ca)

### Expected Behavior

It shows Miis?

### Reproduction Steps

Just launch Mario Kart.

I have the Firmware, Keys, but no save file.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12032832/yuzu_log.txt)

### System Configuration

CPU: AMD Custom APU 0405
GPU/Driver: AMD Custom GPU 0405
RAM: 11.5 GiB (Shouldn't it be 16?)
OS: SteamOS 3.4.8

**Comment by Butterscotch96** [comment]
Before anyone tells me to update my keys or firmware, I literally just set Yuzu up today.

**Comment by liamwhite** [comment]
> [   4.719220] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'MiiModel' (0x0100000000000802).

This means your firmware dump is incomplete or your keys are mismatched.

**Comment by german77** [comment]
Update lockpick and dump newer keys to fix this issue.

**Comment by FearlessTobi** [comment]
Closing due to user error.

**Comment by Butterscotch96** [comment]
> > [   4.719220] Service.FS  core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'MiiModel' (0x0100000000000802).
> 
> This means your firmware dump is incomplete or your keys are mismatched.

I just copied the Quickstart guide. Anything I could have done wrong?
