### ISSUE TITLE
Regression on graphical problems in version 1462db4694 on 8 Gen 2

### ISSUE THREAD

**Issue by Raistlin43** [yuzu-emu/yuzu#11078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1462db4694

### Description of Issue

As of this release, the alleged graphics issues with the custom Adreno 6XX drivers were fixed. The problem is that this version completely breaks the graphics of when using Turnip drivers for A7XX. I attach images of some games but it happens in all of them. When using Turnip for A7XX (either version v1, v2, v3 or v4) in the latest version of Yuzu "black squares" are visible in the image. Also this version runs much slower than the previous one. I understand that the emulator is in its early stages and I find it amazing how well it works but this version is a big step backwards, as in other versions the Turnip drivers worked perfectly on my Samsung Galaxy S23.

![Screenshot_20230712_182711_yuzu](https://github.com/yuzu-emu/yuzu/assets/136481247/e9433f38-3209-4710-99e2-1d8cc54b6639)

![Screenshot_20230712_182831_yuzu](https://github.com/yuzu-emu/yuzu/assets/136481247/3400364a-8db5-494c-857c-7ea9192072fa)

### Expected Behavior

I would like not to see those black squares on the screen when using Turnip 7XX Driver on my Samsung Galaxy S23 Plus (in previous versions they were not visible and games like Xenoverse 2 were 15-25% faster). Thanks!!

### Reproduction Steps

Put a turnip driver for 7XX and from version 1462db4694 onwards you can see black squares (in previous versions it was perfect and did not appear).

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12030298/yuzu_log.txt)

### System Configuration

CPU: Samsung Galaxy S23 Plus 8 Gen 2
GPU/Driver: Adreno 740
RAM: 8GB
OS: Android 13

**Comment by liamwhite** [comment]
https://github.com/yuzu-emu/yuzu/issues/11005#issuecomment-1617317180
