### ISSUE TITLE
Feature Request - Reshade Compatibility

### ISSUE THREAD

**Issue by vahsuh** [yuzu-emu/yuzu#11082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Reshade has many AO shaders I like using on emulators, problem is there's a lot of flickering or other issues with the depth buffer whenever I try to use these shaders on yuzu.

### Why would this feature be useful?

Reshade depth buffer compatibility would make yuzu better by giving players the freedom to make switch games look better.

**Comment by lat9nq** [comment]
Duplicate of #10253
