### ISSUE TITLE
Mesa Turnip revision 4 driver issue

### ISSUE THREAD

**Issue by Mattlance95** [yuzu-emu/yuzu#11086]
### Issue

The emulator is super fast with the new drivers mesa Turnip revision 4 but there are some graphic issues. It's impossible to play games.
There are black and non black squares everywhere..
I have a Samsung Galaxy flip 4, Snapdragon 8 gen 1, Adreno 730, 8gb ram, android 13.

**Comment by gidoly** [comment]
we don't accept issue report that responsible to experimental driver that not released officially
