### ISSUE TITLE
Yuzu Crashes As Soon As I Start A Game

### ISSUE THREAD

**Issue by SuperDabba** [yuzu-emu/yuzu#11084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

I Use EA 3754 but older versions and stable builds dont work either

### Description of Issue

Whenever I start a game it crashes yuzu after loading cache

### Expected Behavior

Yuzu turns itself off completely

### Reproduction Steps

Intel HD 620
Settings in the log
Start any game on Vulkan
Yuzu crashes

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12040039/yuzu_log.txt)

### System Configuration

CPU: Intel i5 7200u
GPU/Driver: Intel HD 620 / 31.0.101.2125 (I tried to switch drivers to older ones like the 27 line and 30 line but it didnt work)
RAM: 8gb
OS: Windows 10

**Comment by SuperDabba** [comment]
Here is my log file :
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12039946/yuzu_log.txt)

**Comment by SpecialDarkwolf999** [comment]
they won't help you as you download roms
pokemon_violet_v131072(rpgonly.com).nsp
