### ISSUE TITLE
TOTK Storage buffer fail

### ISSUE THREAD

**Issue by Jonav9** [yuzu-emu/yuzu#11091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1496

### Description of Issue

Not even 2 minutes into gameplay and it crashes. 

### Expected Behavior

Able to play without crashing.

### Reproduction Steps

Not sure what to say here, it can happen in different parts o the game.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12058963/yuzu_log.txt.old.txt)

### System Configuration

CPU: 11th Gen Intel(R) Core(TM) i7-1165G7
GPU/Driver: Intel iris xe
RAM: 16GB
OS: Windows 11 Version 22H2

**Comment by anpilley** [comment]
Driver: Intel Corporation 101.2079

Your gpu driver is extremely out of date, try the beta one from [intel](https://www.intel.com/content/www/us/en/products/sku/208921/intel-core-i71165g7-processor-12m-cache-up-to-4-70-ghz-with-ipu/downloads.html) for your processor/gpu

**Comment by Jonav9** [comment]
> Driver: Intel Corporation 101.2079
> 
> Your gpu driver is extremely out of date, try the beta one from [intel](https://www.intel.com/content/www/us/en/products/sku/208921/intel-core-i71165g7-processor-12m-cache-up-to-4-70-ghz-with-ipu/downloads.html) for your processor/gpu

Thank you. In your experience,  overwriting the customized driver with the generic one, will possibly cause any issues? I'm mainly concerned because this Samsung laptop has the pen/tablet function,] that I use since I do illustration, and I wouldn't want to do something that could mess that up.

**Comment by goldenx86** [comment]
I've been doing it since I got my laptop with an Xe, zero issues.
Remember to keep a copy of the driver installer on hand, Windows Update loves to revert to older versions.

**Comment by Morph1984** [comment]
The graphics driver does not affect pen/tablet functionality, that is handled by the screen driver (separate from the graphics driver)

**Comment by Jonav9** [comment]
Thanks a lot everyone! I updated the driver and I've been playing for the last hour, and it's not crashing anymore. I'm going to close this.
