### ISSUE TITLE
[WIP] OOM Zelda Tears of the kingdom

### ISSUE THREAD

**Issue by bibitocarlos** [yuzu-emu/yuzu#11099]
### Issue

I,

Archlinux user, latest kernel, latest mesa.
AMD RX 6600XT, Vulkan. 16Gb of RAM.
Yuzu early access  3708-1.
Decode ASTC textures asynchronously off
Randomly, while playing Zelda Tears of the Kingdom, i get an error which force me to reboot the computer :

Possibly a duplicate of https://github.com/yuzu-emu/yuzu/issues/10355

DMESG LOG
`
juil. 15 08:50:28 bibiserveur pipewire[1149]: spa.alsa: hdmi:0: (0 missed) impossible htimestamp diff:-38089
juil. 15 08:50:28 bibiserveur kernel: 0 pages hwpoisoned
juil. 15 08:50:28 bibiserveur kernel: 0 pages cma reserved
juil. 15 08:50:28 bibiserveur kernel: 101370 pages reserved
juil. 15 08:50:28 bibiserveur kernel: 0 pages HighMem/MovableOnly
juil. 15 08:50:28 bibiserveur kernel: 4175492 pages RAM
juil. 15 08:50:28 bibiserveur kernel: Total swap = 0kB
juil. 15 08:50:28 bibiserveur kernel: Free swap  = 0kB
juil. 15 08:50:28 bibiserveur kernel: 0 pages in swap cache
juil. 15 08:50:28 bibiserveur kernel: 888713 total pagecache pages
juil. 15 08:50:28 bibiserveur kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
juil. 15 08:50:28 bibiserveur kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
juil. 15 08:50:28 bibiserveur kernel: Node 0 Normal: 4068*4kB (ME) 1394*8kB (UME) 6*16kB (UE) 2*32kB (U) 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 27584kB
juil. 15 08:50:28 bibiserveur kernel: Node 0 DMA32: 329*4kB (ME) 269*8kB (UME) 204*16kB (ME) 169*32kB (ME) 118*64kB (ME) 84*128kB (UME) 37*256kB (UME) 15*512kB (M) 10*1024kB (UM) 0*2048kB 0*4096kB = 57836kB
juil. 15 08:50:28 bibiserveur kernel: Node 0 DMA: 1*4kB (U) 1*8kB (U) 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 1*1024kB (U) 2*2048kB (UM) 2*4096kB (M) = 13324kB
juil. 15 08:50:28 bibiserveur kernel: lowmem_reserve[]: 0 0 0 0 0
juil. 15 08:50:28 bibiserveur kernel: Node 0 Normal free:27284kB boost:0kB min:55180kB low:68972kB high:82764kB reserved_highatomic:0KB active_anon:6397476kB inactive_anon:4786116kB active_file:1536kB inactive_file:2744kB unevictable:17>
juil. 15 08:50:28 bibiserveur kernel: lowmem_reserve[]: 0 0 12961 12961 12961
juil. 15 08:50:28 bibiserveur kernel: Node 0 DMA32 free:57588kB boost:0kB min:12336kB low:15420kB high:18504kB reserved_highatomic:0KB active_anon:2833308kB inactive_anon:78084kB active_file:296kB inactive_file:0kB unevictable:0kB write>
juil. 15 08:50:28 bibiserveur kernel: lowmem_reserve[]: 0 2897 15859 15859 15859
juil. 15 08:50:28 bibiserveur kernel: Node 0 DMA free:13324kB boost:0kB min:60kB low:72kB high:84kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:159>
juil. 15 08:50:28 bibiserveur kernel: Node 0 active_anon:9231280kB inactive_anon:4863704kB active_file:1600kB inactive_file:2680kB unevictable:17716kB isolated(anon):0kB isolated(file):0kB mapped:3508252kB dirty:96kB writeback:0kB shmem>
juil. 15 08:50:28 bibiserveur kernel: active_anon:2307820 inactive_anon:1215926 isolated_anon:0
                                       active_file:400 inactive_file:670 isolated_file:0
                                       unevictable:4429 dirty:24 writeback:0
                                       slab_reclaimable:51644 slab_unreclaimable:39833
                                       mapped:877063 shmem:886633 pagetables:17746
                                       sec_pagetables:0 bounce:0
                                       kernel_misc_reclaimable:0
                                       free:24549 free_pcp:62 free_cma:0
juil. 15 08:50:28 bibiserveur kernel: Mem-Info:
juil. 15 08:50:28 bibiserveur kernel:  </TASK>
juil. 15 08:50:28 bibiserveur kernel: R13: 0000000000000023 R14: 0000000000000043 R15: 00007f5a38019020
juil. 15 08:50:28 bibiserveur kernel: R10: 00007f58b80008e0 R11: 0000000000000246 R12: 00000000c0206440
juil. 15 08:50:28 bibiserveur kernel: RBP: 00007f58c7ff78c0 R08: ffff800204c00000 R09: 0000000000000001
juil. 15 08:50:28 bibiserveur kernel: RDX: 00007f58c7ff78c0 RSI: 00000000c0206440 RDI: 0000000000000023
juil. 15 08:50:28 bibiserveur kernel: RAX: ffffffffffffffda RBX: 00007f574aad0430 RCX: 00007fdbd991576f
juil. 15 08:50:28 bibiserveur kernel: RSP: 002b:00007f58c7ff7820 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
juil. 15 08:50:28 bibiserveur kernel: Code: 00 48 89 44 24 18 31 c0 48 8d 44 24 60 c7 04 24 10 00 00 00 48 89 44 24 08 48 8d 44 24 20 48 89 44 24 10 b8 10 00 00 00 0f 05 <89> c2 3d 00 f0 ff ff 77 18 48 8b 44 24 18 64 48 2b 04 25 28 00 00
juil. 15 08:50:28 bibiserveur kernel: RIP: 0033:0x7fdbd991576f
juil. 15 08:50:28 bibiserveur kernel:  entry_SYSCALL_64_after_hwframe+0x72/0xdc
juil. 15 08:50:28 bibiserveur kernel:  ? irq_exit_rcu+0x54/0xf0
juil. 15 08:50:28 bibiserveur kernel:  ? irqtime_account_irq+0x40/0xc0
juil. 15 08:50:28 bibiserveur kernel:  ? do_syscall_64+0x6c/0x90
juil. 15 08:50:28 bibiserveur kernel:  ? syscall_exit_to_user_mode+0x1b/0x40
juil. 15 08:50:28 bibiserveur kernel:  do_syscall_64+0x5d/0x90
juil. 15 08:50:28 bibiserveur kernel:  __x64_sys_ioctl+0x91/0xd0
juil. 15 08:50:28 bibiserveur kernel:  amdgpu_drm_ioctl+0x4e/0x90 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  ? __pfx_amdgpu_gem_create_ioctl+0x10/0x10 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  drm_ioctl+0x26d/0x4b0
juil. 15 08:50:28 bibiserveur kernel:  drm_ioctl_kernel+0xca/0x170
juil. 15 08:50:28 bibiserveur kernel:  ? __pfx_amdgpu_gem_create_ioctl+0x10/0x10 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  ? __pfx_amdgpu_bo_user_destroy+0x10/0x10 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  amdgpu_gem_create_ioctl+0x14c/0x3c0 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  amdgpu_bo_create_user+0x40/0x70 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  ? __pfx_amdgpu_bo_user_destroy+0x10/0x10 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  amdgpu_bo_create+0x1d0/0x5e0 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  ttm_bo_init_reserved+0x146/0x170 [ttm bcb958393907e46e4660d81a30d79225f6419af2]
juil. 15 08:50:28 bibiserveur kernel:  ttm_bo_validate+0x1bc/0x370 [ttm bcb958393907e46e4660d81a30d79225f6419af2]
juil. 15 08:50:28 bibiserveur kernel:  ttm_tt_populate+0x9e/0x140 [ttm bcb958393907e46e4660d81a30d79225f6419af2]
juil. 15 08:50:28 bibiserveur kernel:  amdgpu_ttm_tt_populate+0x39/0x90 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  ttm_pool_alloc+0x29d/0x8b0 [ttm bcb958393907e46e4660d81a30d79225f6419af2]
juil. 15 08:50:28 bibiserveur kernel:  __alloc_pages+0xf13/0x1080
juil. 15 08:50:28 bibiserveur kernel:  warn_alloc+0x165/0x1e0
juil. 15 08:50:28 bibiserveur kernel:  dump_stack_lvl+0x47/0x60
juil. 15 08:50:28 bibiserveur kernel:  <TASK>
juil. 15 08:50:28 bibiserveur kernel: Call Trace:
juil. 15 08:50:28 bibiserveur kernel: R13: 0000000000000023 R14: 0000000000000043 R15: 00007f5a38019020
juil. 15 08:50:28 bibiserveur kernel: R10: 00007f58b80008e0 R11: 0000000000000246 R12: 00000000c0206440
juil. 15 08:50:28 bibiserveur kernel: RBP: 00007f58c7ff78c0 R08: ffff800204c00000 R09: 0000000000000001
juil. 15 08:50:28 bibiserveur kernel: RDX: 00007f58c7ff78c0 RSI: 00000000c0206440 RDI: 0000000000000023
juil. 15 08:50:28 bibiserveur kernel: RAX: ffffffffffffffda RBX: 00007f574aad0430 RCX: 00007fdbd991576f
juil. 15 08:50:28 bibiserveur kernel: RSP: 002b:00007f58c7ff7820 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
juil. 15 08:50:28 bibiserveur kernel: Code: 00 48 89 44 24 18 31 c0 48 8d 44 24 60 c7 04 24 10 00 00 00 48 89 44 24 08 48 8d 44 24 20 48 89 44 24 10 b8 10 00 00 00 0f 05 <89> c2 3d 00 f0 ff ff 77 18 48 8b 44 24 18 64 48 2b 04 25 28 00 00
juil. 15 08:50:28 bibiserveur kernel: RIP: 0033:0x7fdbd991576f
juil. 15 08:50:28 bibiserveur kernel:  entry_SYSCALL_64_after_hwframe+0x72/0xdc
juil. 15 08:50:28 bibiserveur kernel:  ? irq_exit_rcu+0x54/0xf0
juil. 15 08:50:28 bibiserveur kernel:  ? irqtime_account_irq+0x40/0xc0
juil. 15 08:50:28 bibiserveur kernel:  ? do_syscall_64+0x6c/0x90
juil. 15 08:50:28 bibiserveur kernel:  ? syscall_exit_to_user_mode+0x1b/0x40
juil. 15 08:50:28 bibiserveur kernel:  do_syscall_64+0x5d/0x90
juil. 15 08:50:28 bibiserveur kernel:  __x64_sys_ioctl+0x91/0xd0
juil. 15 08:50:28 bibiserveur kernel:  amdgpu_drm_ioctl+0x4e/0x90 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  ? __pfx_amdgpu_gem_create_ioctl+0x10/0x10 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  drm_ioctl+0x26d/0x4b0
juil. 15 08:50:28 bibiserveur kernel:  drm_ioctl_kernel+0xca/0x170
juil. 15 08:50:28 bibiserveur kernel:  ? __pfx_amdgpu_gem_create_ioctl+0x10/0x10 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  ? __pfx_amdgpu_bo_user_destroy+0x10/0x10 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  amdgpu_gem_create_ioctl+0x14c/0x3c0 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  amdgpu_bo_create_user+0x40/0x70 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  ? __pfx_amdgpu_bo_user_destroy+0x10/0x10 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  amdgpu_bo_create+0x1d0/0x5e0 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  ttm_bo_init_reserved+0x146/0x170 [ttm bcb958393907e46e4660d81a30d79225f6419af2]
juil. 15 08:50:28 bibiserveur kernel:  ttm_bo_validate+0x1bc/0x370 [ttm bcb958393907e46e4660d81a30d79225f6419af2]
juil. 15 08:50:28 bibiserveur kernel:  ttm_tt_populate+0x9e/0x140 [ttm bcb958393907e46e4660d81a30d79225f6419af2]
juil. 15 08:50:28 bibiserveur kernel:  amdgpu_ttm_tt_populate+0x39/0x90 [amdgpu 708fbcf5c6c231c6e8ffccf1b30f59e4696dd9c1]
juil. 15 08:50:28 bibiserveur kernel:  ttm_pool_alloc+0x29d/0x8b0 [ttm bcb958393907e46e4660d81a30d79225f6419af2]
juil. 15 08:50:28 bibiserveur kernel:  __alloc_pages+0xf13/0x1080
juil. 15 08:50:28 bibiserveur kernel:  warn_alloc+0x165/0x1e0
juil. 15 08:50:28 bibiserveur kernel:  dump_stack_lvl+0x47/0x60
juil. 15 08:50:28 bibiserveur kernel:  <TASK>
juil. 15 08:50:28 bibiserveur kernel: Call Trace:
juil. 15 08:50:28 bibiserveur kernel: Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./X470 Gaming-ITX/ac, BIOS P4.50 05/11/2021
juil. 15 08:50:28 bibiserveur kernel: CPU: 4 PID: 54359 Comm: GPU Tainted: G        W  OE      6.4.3-zen1-1-zen #1 ac2feb68e64db3182be5fb3800eb0cff7206bde7
juil. 15 08:50:28 bibiserveur kernel: GPU: page allocation failure: order:0, mode:0x104dc2(GFP_HIGHUSER|__GFP_RETRY_MAYFAIL|__GFP_ZERO), nodemask=(null),cpuset=/,mems_allowed=0
juil. 15 08:50:28 bibiserveur kernel: Out of memory: Killed process 54229 (yuzu) total-vm:556199448kB, anon-rss:4217004kB, file-rss:2564kB, shmem-rss:5716992kB, UID:1000 pgtables:24048kB oom_score_adj:200
juil. 15 08:50:28 bibiserveur kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/session.slice/plasma-kded.service,task=yuzu,pid=54229,>
juil. 15 08:50:28 bibiserveur kernel: [  54232]  1000 54232     4443      755    61440        0           200 yuzu
juil. 15 08:50:28 bibiserveur kernel: [  54229]  1000 54229 139049862  2484140 24625152        0           200 yuzu
juil. 15 08:50:28 bibiserveur kernel: [    588]    81   588     2810     1203    65536        0          -900 dbus-daemon
juil. 15 08:50:28 bibiserveur kernel: [    587]     0   587     3104      831    65536        0             0 bluetoothd
juil. 15 08:50:28 bibiserveur kernel: [    586]   974   586     2217      770    57344        0             0 avahi-daemon
juil. 15 08:50:28 bibiserveur kernel: [    584]     0   584     1340      450    53248        0             0 nfsdcld
juil. 15 08:50:28 bibiserveur kernel: [    583]     0   583     1269      614    49152        0             0 rpc.idmapd
juil. 15 08:50:28 bibiserveur kernel: [    575]   976   575    22765      923    90112        0             0 systemd-timesyn
juil. 15 08:50:28 bibiserveur kernel: [    353]     0   353     8607     1280    94208        0         -1000 systemd-udevd
juil. 15 08:50:28 bibiserveur kernel: [    322]     0   322    14567      899   122880        0          -250 systemd-journal
juil. 15 08:50:28 bibiserveur kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
juil. 15 08:50:28 bibiserveur kernel: Tasks state (memory values in pages):
juil. 15 08:50:28 bibiserveur kernel: 0 pages hwpoisoned
juil. 15 08:50:28 bibiserveur kernel: 0 pages cma reserved
juil. 15 08:50:28 bibiserveur kernel: 101370 pages reserved
juil. 15 08:50:28 bibiserveur kernel: 0 pages HighMem/MovableOnly
juil. 15 08:50:28 bibiserveur kernel: 4175492 pages RAM
juil. 15 08:50:28 bibiserveur kernel: Total swap = 0kB
juil. 15 08:50:28 bibiserveur kernel: Free swap  = 0kB
juil. 15 08:50:28 bibiserveur kernel: 0 pages in swap cache
juil. 15 08:50:28 bibiserveur kernel: 889097 total pagecache pages
juil. 15 08:50:28 bibiserveur kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
juil. 15 08:50:28 bibiserveur kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
juil. 15 08:50:28 bibiserveur kernel: Node 0 Normal: 7048*4kB (UME) 3393*8kB (UME) 1*16kB (E) 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 55352kB
juil. 15 08:50:28 bibiserveur kernel: Node 0 DMA32: 384*4kB (UME) 328*8kB (UME) 250*16kB (UME) 200*32kB (UME) 134*64kB (UME) 84*128kB (ME) 38*256kB (UME) 16*512kB (UM) 10*1024kB (M) 1*2048kB (M) 0*4096kB = 64096kB
juil. 15 08:50:28 bibiserveur kernel: Node 0 DMA: 1*4kB (U) 1*8kB (U) 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 1*1024kB (U) 2*2048kB (UM) 2*4096kB (M) = 13324kB
juil. 15 08:50:28 bibiserveur kernel: lowmem_reserve[]: 0 0 0 0 0
juil. 15 08:50:28 bibiserveur kernel: Node 0 Normal free:51996kB boost:0kB min:55180kB low:68972kB high:82764kB reserved_highatomic:0KB active_anon:6773764kB inactive_anon:4409828kB active_file:1328kB inactive_file:2724kB unevictable:17>
juil. 15 08:50:28 bibiserveur kernel: lowmem_reserve[]: 0 0 12961 12961 12961
juil. 15 08:50:28 bibiserveur kernel: Node 0 DMA32 free:63928kB boost:0kB min:12336kB low:15420kB high:18504kB reserved_highatomic:0KB active_anon:2843892kB inactive_anon:67500kB active_file:28kB inactive_file:140kB unevictable:0kB writ>
juil. 15 08:50:28 bibiserveur kernel: lowmem_reserve[]: 0 2897 15859 15859 15859
juil. 15 08:50:28 bibiserveur kernel: Node 0 DMA free:13324kB boost:0kB min:60kB low:72kB high:84kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:159>
juil. 15 08:50:28 bibiserveur kernel: Node 0 active_anon:9615940kB inactive_anon:4479044kB active_file:1644kB inactive_file:2904kB unevictable:17716kB isolated(anon):0kB isolated(file):0kB mapped:3508892kB dirty:96kB writeback:0kB shmem>
juil. 15 08:50:28 bibiserveur kernel: active_anon:2403985 inactive_anon:1119761 isolated_anon:0
                                       active_file:346 inactive_file:791 isolated_file:0
                                       unevictable:4429 dirty:24 writeback:0
                                       slab_reclaimable:51653 slab_unreclaimable:39652
                                       mapped:877223 shmem:886633 pagetables:17743
                                       sec_pagetables:0 bounce:0
                                       kernel_misc_reclaimable:0
                                       free:32312 free_pcp:62 free_cma:0
juil. 15 08:50:28 bibiserveur kernel: Mem-Info:
juil. 15 08:50:28 bibiserveur kernel:  </TASK>
juil. 15 08:50:28 bibiserveur kernel: R13: 00000bb75815e619 R14: 00007f9bb806e880 R15: 00007f9bc9ff9c10
juil. 15 08:50:28 bibiserveur kernel: R10: 0000000000000000 R11: 0000000000000246 R12: 00007f9bb8000be0
juil. 15 08:50:28 bibiserveur kernel: RBP: 00007f9bb806e780 R08: 00007f9bb806e880 R09: 0000000000001a8b
juil. 15 08:50:28 bibiserveur kernel: RDX: 000d000d00000000 RSI: 0000000000000001 RDI: 00007f9bb806e880
juil. 15 08:50:28 bibiserveur kernel: RAX: 0000000000000000 RBX: 00007f9bb8000bd0 RCX: 0000000100000001
juil. 15 08:50:28 bibiserveur kernel: RSP: 002b:00007f9bc9ff9b50 EFLAGS: 00010202
juil. 15 08:50:28 bibiserveur kernel: Code: Unable to access opcode bytes at 0x564ce67657d7.
juil. 15 08:50:28 bibiserveur kernel: RIP: 0033:0x564ce6765801
juil. 15 08:50:28 bibiserveur kernel:  asm_exc_page_fault+0x26/0x30
juil. 15 08:50:28 bibiserveur kernel:  exc_page_fault+0x7f/0x180
juil. 15 08:50:28 bibiserveur kernel:  do_user_addr_fault+0x190/0x9e0
juil. 15 08:50:28 bibiserveur kernel:  handle_mm_fault+0x10ed/0x12c0
juil. 15 08:50:28 bibiserveur kernel:  do_read_fault+0x3e/0x160
juil. 15 08:50:28 bibiserveur kernel:  __do_fault+0x30/0x130
juil. 15 08:50:28 bibiserveur kernel:  ? filemap_map_pages+0x162/0x640
juil. 15 08:50:28 bibiserveur kernel:  ? next_uptodate_page+0x15f/0x1f0
juil. 15 08:50:28 bibiserveur kernel:  filemap_fault+0x316/0x10d0
juil. 15 08:50:28 bibiserveur kernel:  ? page_cache_ra_unbounded+0x138/0x180
juil. 15 08:50:28 bibiserveur kernel:  __filemap_get_folio+0x19d/0x570
juil. 15 08:50:28 bibiserveur kernel:  folio_alloc+0xa2/0x280
juil. 15 08:50:28 bibiserveur kernel:  __alloc_pages+0xf97/0x1080
juil. 15 08:50:28 bibiserveur kernel:  out_of_memory+0x294/0x670
juil. 15 08:50:28 bibiserveur kernel:  oom_kill_process+0xf9/0x190
juil. 15 08:50:28 bibiserveur kernel:  dump_header+0x4a/0x240
juil. 15 08:50:28 bibiserveur kernel:  dump_stack_lvl+0x47/0x60
juil. 15 08:50:28 bibiserveur kernel:  <TASK>
juil. 15 08:50:28 bibiserveur kernel: Call Trace:
juil. 15 08:50:28 bibiserveur kernel: Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./X470 Gaming-ITX/ac, BIOS P4.50 05/11/2021
juil. 15 08:50:28 bibiserveur kernel: CPU: 1 PID: 53885 Comm: LanguageInvoker Tainted: G        W  OE      6.4.3-zen1-1-zen #1 ac2feb68e64db3182be5fb3800eb0cff7206bde7
juil. 15 08:50:28 bibiserveur kernel: LanguageInvoker invoked oom-killer: gfp_mask=0x140cca(GFP_HIGHUSER_MOVABLE|__GFP_COMP), order=0, oom_score_adj=200

`

**Comment by FearlessTobi** [comment]
Thanks for your report, but please open it again using the correct issue template and providing all the required information.
