### ISSUE TITLE
New line at end of files

### ISSUE THREAD

**Issue by komawoyo** [yuzu-emu/yuzu#111]
I see a reoccurring theme where a "new line at the end of files" is needed. Possible need to update the Contribution Guide or add a tool that formats that for you in the ReadMe so everyone is on the same page. This would enhance efficiency and save time in the future

**Comment by MerryMage** [comment]
> add a tool that formats that for you in the ReadMe so everyone is on the same page

Currently we use clang-format at version 3.8 (and only that version).

This can be installed as so:

* MSVC: There should be an extension for this
* apt: `clang-format-3.8`
* macOS: `brew install clang-format@3.8`

**Comment by jroweboy** [comment]
yuzu already has a tool that enforces the style guide, it uses clang format for that. I agree that it would be nice to have a cmake target that runs clang format for all files in the repo that you can use before you push. Then include some instructions in the contribution guidelines to have people run the clang format target before submitting a pull request. I'll try to whip something up to fix this.

**Comment by jroweboy** [comment]
Will be fixed with #117

**Comment by MerryMage** [comment]
Close pls.
