### ISSUE TITLE
Yuzu Crashes In All Games

### ISSUE THREAD

**Issue by SuperDabba** [yuzu-emu/yuzu#11106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3754 , Stable release and all other versions

### Description of Issue

When I try to open any game on yuzu it says launching and then it crashes
It used to work for me a while ago
It might be something I installed thats incompatible but I need help trying to find it because this happened before and I fixed it by deleted Twitch Studio but I dont know what it is this time

### Expected Behavior

Yuzu crashes and turns off

### Reproduction Steps

Have Intel HD 620
i5 7200u and 8 GB Ram
Open any game in yuzu and it crashes after building pipeline cache and launching

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12069066/yuzu_log.txt)
I dont know why the log got cut off in the end at warning but thats where it crashed yuzu

### System Configuration

CPU: i5 7200u
GPU/Driver: Intel HD 620 31.0.101.2125
RAM: 8GB
OS: Windows 10

**Comment by FearlessTobi** [comment]
We still do not support piracy (https://github.com/yuzu-emu/yuzu/issues/11084).
