### ISSUE TITLE
[Linux] verify ownership of flatpak on flathub.org

### ISSUE THREAD

**Issue by Renner0E** [yuzu-emu/yuzu#11101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Verify the ownership of the flatpak like [firefox](https://flathub.org/apps/org.mozilla.firefox).

### Why would this feature be useful?

It adds one more layer of trust for the user (This app is actually by the original devs and can be trusted).

**Comment by FearlessTobi** [comment]
@liushuyu Can you take a look?

**Comment by MMachado05** [comment]
Any progress here? Official download page on the Yuzu website points to flathub, but it's still missing verification.

**Comment by liushuyu** [comment]
It should be verified now. The blue badge may come with a bit of delay.
I will close this issue when the badge is shown with the app.

**Comment by liushuyu** [comment]
![screenshot](https://github.com/yuzu-emu/yuzu/assets/6829345/80136b5c-0977-4dfe-a94a-491231cdff9b)
The badge is now visible. Closing the issue.
