### ISSUE TITLE
Mario Kart 8 Deluxe stuck at select mii screen (Android)

### ISSUE THREAD

**Issue by update-freak** [yuzu-emu/yuzu#11118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1462db4694

### Description of Issue

Hi, on the android App Yuzu Mario Kart 8 Deluxe stuck at select mii screen.
I installed the 16.0.3 Firmware via zip and used the current prod.keys from RyuSak.
Do anyone know how to solve this issue?

### Expected Behavior

No problem with mii screen where no mii could be selected

### Reproduction Steps

1. install all DLCs and Updates for Mario Kart 8 Deluxe
2. installed the 16.0.3 Firmware via zip
3. use prod.keys from RyuSak
4. start game

### Log File

no log file for android

### System Configuration

Samsung Galaxy S23 with current software.

**Comment by BSoDGamingYT** [comment]
Piracy will not be given support
