### ISSUE TITLE
Add Dropdown Option for 6GB & 8GB Extended Memory Layout

### ISSUE THREAD

**Issue by AliciaBurrito** [yuzu-emu/yuzu#11111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Instead of just a checkbox for the 8GB extended memory layout, make a dropdown to select between the 6GB or 8GB extended layouts.

For UX reasons maybe the dropdown would contain 4GB, 6GB, 8GB.

### Why would this feature be useful?

Certain mods that may require an extended memory layout may only require the 6GB layout, and not the 8GB layout. In these cases users would be able to allocate less memory for full functionality which is particularly useful on memory limited systems.

**Comment by lat9nq** [comment]
Not ready to PR due it being downstream of #10839: https://github.com/lat9nq/yuzu/tree/ext-mem-enum
