### ISSUE TITLE
Issues compiling with latest LLVM git

### ISSUE THREAD

**Issue by R1chterScale** [yuzu-emu/yuzu#11115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Git Mainline

### Description of Issue

With the latest LLVM git two errors are thrown when attempting to compile mainline-git.

```
/home/richterscale/yuzu-mainline/src/common/demangle.cpp:26:60: error: too many arguments to function call, expected single argument 'mangled_name', have 4 arguments
   26 |         demangled = llvm::itaniumDemangle(mangled.c_str(), nullptr, nullptr, nullptr);
      |                     ~~~~~~~~~~~~~~~~~~~~~                  ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/llvm/Demangle/Demangle.h:35:7: note: 'itaniumDemangle' declared here
   35 | char *itaniumDemangle(std::string_view mangled_name);
   ```

and

```
/home/richterscale/yuzu-mainline/src/common/detached_tasks.cpp:33:18: error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
   33 |     std::thread([task{std::move(task)}]() {
      |                  ^
/home/richterscale/yuzu-mainline/src/common/detached_tasks.cpp:30:51: note: previous declaration is here
   30 | void DetachedTasks::AddTask(std::function<void()> task) {
      |    
```

### Expected Behavior

For Yuzu to compile

### Reproduction Steps

Attempt to compile yuzu-mainline with the latest llvm-git.

### Log File

Listed above

### System Configuration

CPU: AMD Ryzen 5600X
GPU/Driver: Nvidia GeForce 1080 Ti
RAM: 16GB 3600MT/s
OS: Linux (EndeavourOS)

**Comment by Morph1984** [comment]
We are using the system llvm for demangle, which seems to have changed its api to use string_view instead. This is one of my concerns of using system libraries is that API stability isn't guaranteed. @abouvier What is the proper course of action to take here?

**Comment by R1chterScale** [comment]
Oh, should note that getting rid of the three nullptr does seem to remove that error (I have zero idea if that's a genuine fix for that particular error)

**Comment by zeltermann** [comment]
> Oh, should note that getting rid of the three nullptr does seem to remove that error (I have zero idea if that's a genuine fix for that particular error)

It's not. Please do `demangled = llvm::itaniumDemangle(mangled);` instead.

**Comment by zeltermann** [comment]
> What is the proper course of action to take here?

I think it's fine to leave our own code as-is until LLVM updates in our CI. This issue currently occurs only for those who self-compile, so I believe they should simply patch it themselves.

**Comment by abouvier** [comment]
> What is the proper course of action to take here?

 Reject the system library with a version constraint and use the external :p

`find_package(LLVM 16 MODULE COMPONENTS Demangle)`

**Comment by lat9nq** [comment]
I marked the PR as completing this Issue, but I need to implement @abouvier's suggestion.
