### ISSUE TITLE
Totk Crash when loading save

### ISSUE THREAD

**Issue by beltaro** [yuzu-emu/yuzu#11120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3599

### Description of Issue

Game opens fine but crashes when i try to load into my tears of the kingdom save file
all other related issues say its an old gpu and low vram problem but i cant belive that a 3060 cat run a game made for the nintendo switch

### Expected Behavior

Load the save

### Reproduction Steps

Mods: <img width="335" alt="image" src="https://github.com/yuzu-emu/yuzu/assets/91323981/a71c9dd3-3949-4284-b7ea-2d3257f9d698">
Force maximum clocks is off
Game Ver: 1.0.0

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12109453/yuzu_log.txt)

### System Configuration

CPU: Core i7 12700h
GPU/Driver: rtx 3060/ 536.40
RAM: 16
OS: Windows

**Comment by liamwhite** [comment]
Log file is truncated and doesn't show any game being opened

**Comment by liamwhite** [comment]
What you posted doesn't link to a log file.

**Comment by FearlessTobi** [comment]
Please also disable all mods and try again.

**Comment by Squall-Leonhart** [comment]
isn't visualfixes dead?

**Comment by beltaro** [comment]
i turned off visual fixes and blackscreenfix and faster teleport and durability ui and also enabled force maximum clocks again and the game loaded fine and played for a few minutes but crashed when i used ascend 
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12114385/yuzu_log.txt.old.txt)

**Comment by liamwhite** [comment]
This log does not show any game being booted. Please follow the directions as written on the help page to ensure you aren't overwriting the log files.

**Comment by beltaro** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12114608/yuzu_log.txt)
updated yuzu to 3765 and it still crashed after a few minutes (also i noticed it crashes when swapping abilities but im not sure if its actually because of the ability menu)
i also updated the mods and diabled some mods (the game crashed after a few minutes without any mods too): 
<img width="343" alt="image" src="https://github.com/yuzu-emu/yuzu/assets/91323981/2c68ff23-5ddd-40a1-a2c4-a2d78e6d17d2">

**Comment by beltaro** [comment]
this issue is no longer happening but has been replaced by another bug. will close this issue and open a new one
