### ISSUE TITLE
Pikmin 4 Extreme Issues

### ISSUE THREAD

**Issue by gfrhj** [yuzu-emu/yuzu#11126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1502

### Description of Issue

![image](https://github.com/yuzu-emu/yuzu/assets/57181282/54415c7a-3835-4735-895f-c7a73b06777c)
It just started happening after this update. There's varying levels to its bugginess from weird colors to just pure white.
a bomb went off.

### Expected Behavior

Not this

### Reproduction Steps

Just exist anywhere for a few seconds. Usually anywhere but the hub. I'm not able to attach files, it just gives a local file location.

### Log File

I'm not able to attach files, it just gives a local file location.

### System Configuration

Stock Steam Deck 64GB

**Comment by ASPJulien** [comment]
Hello, I fixed this issue by enabling "high" GPU precision!

**Comment by relu419** [comment]
Set GPU accuracy to high.
