### ISSUE TITLE
Yuzu produces a crash dump on exit since mainline 1504 on Windows

### ISSUE THREAD

**Issue by solarmystic** [yuzu-emu/yuzu#11137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1504 and newer

### Description of Issue

Issue as stated in the title. 

When exiting yuzu on Windows after booting it up, yuzu quits silently as expected but a crash dump file is always produced at `C:\Users\[UserName]\AppData\Local\CrashDumps\`

Last build that behaved normally is Mainline 1503

### Expected Behavior

Yuzu not to produce a crashdump on exit. 

### Reproduction Steps

1. Boot yuzu mainline version 1504 and above
2. Exit yuzu
3. Windows produces a crashdump file on exit at `C:\Users\[UserName]\AppData\Local\CrashDumps\`

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12139055/yuzu_log.txt)

### System Configuration

CPU: Intel Core i7 12700KF
GPU/Driver: NVIDIA RTX 2080TI 527.56
RAM: 64 GB 
OS: Windows 10

**Comment by RUANRUI1995** [comment]
same on yuzu ea version 3700 and above

**Comment by lat9nq** [comment]
Can someone upload the most recent crash dump, reproducing one if you can? Also please report the Mainline version you used.

**Comment by RUANRUI1995** [comment]
[AppCrash_yuzu.exe_de58489836b83b688772ce4a26572874ba7b5f71_b2448047_03a53828-0bf3-42a1-bca3-e201107ad7ba.zip](https://github.com/yuzu-emu/yuzu/files/12167439/AppCrash_yuzu.exe_de58489836b83b688772ce4a26572874ba7b5f71_b2448047_03a53828-0bf3-42a1-bca3-e201107ad7ba.zip)

**Comment by RUANRUI1995** [comment]
C:\ProgramData\Microsoft\Windows\WER\ReportArchive

**Comment by RUANRUI1995** [comment]
Mainline 1507 doesn't crash now but it's always English even if I change to Chinese.EA3778 still crash.

**Comment by solarmystic** [comment]
Resolved by https://github.com/lat9nq/yuzu/commit/1bc0b673aa2fc0510d332286e49f6c8d44568065 added to PR 10839. Closing.
