### ISSUE TITLE
Pikmin 4 slowdown

### ISSUE THREAD

**Issue by Jickes1** [yuzu-emu/yuzu#11143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1505

### Description of Issue

Severe FPS drops when running around and in cutscenes. GPU accuracy already set to high. Frames drop to 2-5 FPS. No graphical issues of any kind aside from this.

### Expected Behavior

Game should run at a solid 30fps consistently

### Reproduction Steps

Roam around the overworked anywhere aside from the hub area long enough and you will encounter frame drops.

### Log File

Can provide later if needed.

### System Configuration

Steam Deck 64GB

**Comment by Conan179** [comment]
https://github.com/yuzu-emu/yuzu/issues/11138
