### ISSUE TITLE
Splatoon 2 / multiplayer lobby crash

### ISSUE THREAD

**Issue by Halivagyok** [yuzu-emu/yuzu#11140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1504

### Description of Issue

In splatoon 2 when i go the the multiplayer lobby my fps drops to zero and the game with the emulator closes.
[video](https://github.com/yuzu-emu/yuzu/files/12143624/2023-07-24.10-42-22.zip)

### Expected Behavior

the multiplayer menu shows up

### Reproduction Steps

1. open the game.
2. just go straight
3. wait

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12143525/yuzu_log.txt)

### System Configuration

CPU: amd ryzen 7 2700X
GPU/Driver: amd radeon rx 580 / 23.7.1 (i use vulkan)
RAM: 2x8 gigabte corsair vengence 3200mzh
OS: windows 10 64-bit

**Comment by gidoly** [comment]
Close due to piracy
