### ISSUE TITLE
LOZ: TOTK - Hard constant stutter in depths and 5 sec freeze after closing map, inventory, skill wheel, weapon selection

### ISSUE THREAD

**Issue by galehawk599** [yuzu-emu/yuzu#11158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1505 / EA 3777

### Description of Issue

I'm here to describe two **BIG** problems that plague Tears of the Kingdom gameplay and make it impossible.

**1 - INTERFACES OUTPUT FREEZING**
Basically, since I'm forced to use the BC3 recompression (no compression: VRAM peak 3,9 GB, BC3: VRAM peak 3,5 GB) of the ASTC textures, I have a 5 second freeze every time I close ANY type of menu (weapons, map, skills, etc...), which is already a good reason to stop playing it because in a game with such a fluid and dynamic gameplay it makes me lose my desire.

**2 - CONSTANT STUTTER WHEN NAVIGATING THE DEPTHS**
Well, it seems that this game is currently **IMPOSSIBLE** for me to play while I'm in the **Depths** map because at any moment of the game (not immediately), after about a few minutes the game starts stuttering **CONTINUOUSLY** every about 0.2 sec until you go back to the surface or on the islands (sometimes even teleporting to another point of the **Depths** allows you to **MOMENTARILY** solve the problem).

I have attached the log regarding the logging down to a few stuttering seconds in the depths.

### Expected Behavior

It should work without stuttering.

### Reproduction Steps

1 - Just open any inventory/map then close to have 5 sec freeze.

2 - Just explore for some minutes depths to encounter this constant endless stutter.

[0100F2C0115B6000.zip](https://github.com/yuzu-emu/yuzu/files/12163935/0100F2C0115B6000.zip)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12163925/yuzu_log.txt)

### System Configuration

CPU: i7-9700
GPU/Driver: RX 570 4 GB / 23.7.1 (latest)
RAM: 16 GB (2 x 8 GB) 2.666 MHz
OS: Windows 10 Pro x64

-

**GRAPHIC SETTINGS*
![TOTK2](https://github.com/yuzu-emu/yuzu/assets/53449659/392cff08-8293-46c9-8a61-a227f21ddf29)
![TOTK1](https://github.com/yuzu-emu/yuzu/assets/53449659/32e3be28-4362-4667-a41d-eb76dda5ee6b)

**Comment by FernandoS27** [comment]
We don't support piracy.
