### ISSUE TITLE
Yuzu Crash On Tears of the kingdom launch

### ISSUE THREAD

**Issue by beltaro** [yuzu-emu/yuzu#11164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3765

### Description of Issue

tears of the kingdom launches and builds shaders and even makes the static sound that it makes when the game launches in blackscreen but it crashes right before the actual main menu loads up

### Expected Behavior

open the main menu

### Reproduction Steps

mods: <img width="343" alt="image" src="https://github.com/yuzu-emu/yuzu/assets/91323981/b56248c4-b92f-4e3c-a3e9-3aa44fb6bb61">

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12178193/yuzu_log.txt.old.txt)

### System Configuration

CPU: i7 12700h
GPU/Driver: rtx 3060/536.67
RAM: 16
OS: windows 11

**Comment by pacoa-kdbg** [comment]
Does it crash without mods ?

If not, can you narrow down which ones (or the combinations) that make it crash ?

**Comment by Squall-Leonhart** [comment]
2 of those mods are not only outdated, but crash causers.

**Comment by beltaro** [comment]
> 2 of those mods are not only outdated, but crash causers.
> 
> and you're also running the base game unpatched, which has issues in itself.

which 2 mods exactly ? and by unpatched do you mean not updated cause i kinda wanna keep the dupe glitch

**Comment by beltaro** [comment]
fixed by applying 1.2.0 patch and restarting windows
