### ISSUE TITLE
Hyrule Warrios Definitive Edition :Softlock And Audio Flicking

### ISSUE THREAD

**Issue by dekasentaialex** [yuzu-emu/yuzu#11161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3776

### Description of Issue

well I don't know what happened some time ago the game was running fine now it's giving audio flickering and softlock right in the first battle

### Expected Behavior

https://github.com/yuzu-emu/yuzu/assets/99848172/f9a603c2-fdba-404a-ac47-3c1960254118

### Reproduction Steps

.

### Log File

.

### System Configuration

CPU: i7 - 11800 2.30GHz
GPU/Driver: Nvidia Geforce 3050 Laptop DGpu
RAM:8GB Ram

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
