### ISSUE TITLE
Memory Leak For Monster Hunter Generations Ultimate

### ISSUE THREAD

**Issue by blueraptor101** [yuzu-emu/yuzu#11174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline-0-1508 and later (might be earlier as well but i havent tried the older builds)

### Description of Issue

Upon entering a quest online in Monster hunter generations ultimate it will spam this line of code not stopping until the game is closed:

[ 341.327968] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 341.329826] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!

(This issue is also happening to my friends with different cards and specs)

### Expected Behavior

Well i haven't ever got it to work properly but i assume that its not supposed to use up that much ram

### Reproduction Steps

Launch monster hunter generations ultimate, 
choose character, 
go to the multiplayer menu,
connect, 
create hub,
walk up to the Wycademy gal/ quest giver, 
choose any quest and depart,
The memory leak will start immediately upon loading into the quest.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12189708/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
GPU/Driver: GTX1070/ 536.40
RAM: 16 GB
OS: Windows 10 Version	10.0.19045 Build 19045

**Comment by Squall-Leonhart** [comment]
No proof of memory leak provided.

**Comment by blueraptor101** [comment]
> 

What would prove that its heppening?
About 25% of the way down the log file you can see that it spams the line of code i was talking about. And it just eats my ram until my computer freezes.

**Comment by blueraptor101** [comment]
> No proof of memory leak provided.

What would prove that its heppening?
About 25% of the way down the log file you can see that it spams the line of code i was talking about. And it just eats my ram until my computer freezes.
I could send a video if that would help.

**Comment by Squall-Leonhart** [comment]
* isn't a server

**Comment by blueraptor101** [comment]
> * isn't a server

If a mem leak isnt the issue what is it then? Because im sure it shouldnt be doing what it is.
