### ISSUE TITLE
Yuzu not opening after native clock changes integer overflow error

### ISSUE THREAD

**Issue by asthemic** [yuzu-emu/yuzu#11172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1476 +

### Description of Issue

Hoping some one can help or point me in the right direction, back in June yuzu mainline prebuilt updates (working build 20230620-a67bdeh2c 1475, crashing 20230621-e3122c5b4 1476) stopped working (yuzu main window doesn't open, APPCRASH in windows event logs, no yuzu log) for me on my mini pc (intel n100), but works fine on my main pc (ryzen 5800x3d) both latest Windows 10. 

I thought it was a missing dependency but finally installed vs and compiled the latest mainline to run debug. 

I'm getting bugcheck 0xc0000095 which points back to an integer overflow, and when run debug in VS2022 (latest build 17.6.5) it gets to unit128.h line 64 "return _udiv128(r[1], r[0], divisor, &remainder);" I see there's mentions of clock changes which when I drill down to the common x64 native_clock.cpp file and change the NSratio::den to a lesser number (divide by 10) Yuzu starts.

![Screenshot 2023-07-27 140124](https://github.com/yuzu-emu/yuzu/assets/8972432/f2a1109d-a8c2-4b0c-acde-bcbdef807ea8)

![Screenshot 2023-07-27 211505](https://github.com/yuzu-emu/yuzu/assets/8972432/a1f88997-8d4a-4f58-9587-317102cc012b)

### Expected Behavior

Expect Yuzu window to start up.

### Reproduction Steps

Not sure, as I can't reproduce it on my AMD dev machine.

### Log File

No log generated.

### System Configuration

CPU: Intel N100
GPU/Driver: Intel UHD  / 31.0.101.4575 11/07/23
RAM: 16GB DDR5
OS: Windows 10 x64 and upgraded to 11 x64
[DxDiag.txt](https://github.com/yuzu-emu/yuzu/files/12188625/DxDiag.txt)

**Comment by asthemic** [comment]
Confirming that changing the check to nano avoids the overflow issue and yuzu starts up. Do you need any more variables from me to help avoid in future? Included screenshot
![Screenshot 2023-07-28 101139](https://github.com/yuzu-emu/yuzu/assets/8972432/68ac534e-f95f-4a82-9ae1-fe282af9ae82)

**Comment by karasuhebi** [comment]
Just out of curiosity: Can a processor with single-threaded performance that low run any games on yuzu?
