### ISSUE TITLE
Foldable support doesn't respect the game's aspect ratio (android)

### ISSUE THREAD

**Issue by kindacozi** [yuzu-emu/yuzu#11185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 482c957f5

### Description of Issue

When partially folding my z fold 3 during gameplay, the game goes into a 3ds style layout with the controls on bottom and the game on top as expected, but the game forces itself to always stretch to touch the sides of the screen, and then on top of that it also adds black bars on the top and bottom (?)
before folding, usual tablet layout
![Screenshot_20230730_102947_yuzu](https://github.com/yuzu-emu/yuzu/assets/12834704/eabe95c6-6644-4da6-8e33-42effce4b85f)

after folding, the game squishes and stretches into a comically malformed window
![Screenshot_20230730_102939_yuzu](https://github.com/yuzu-emu/yuzu/assets/12834704/1bcb014e-0897-46af-b647-41536e22a823)

setting the aspect ratio in the setting to fill the window removes the top/bottom bars which makes it less comically stretched but i'd prefer if it just stayed 16:9
![Screenshot_20230711_221329_yuzu](https://github.com/yuzu-emu/yuzu/assets/12834704/18fc280a-649b-409b-80e0-193e397bdb19)

### Expected Behavior

the view of the game should stay at 16:9 instead of stretching when the aspect ratio isn't set to stretch

### Reproduction Steps

partially fold the device while a game is running (or before the game is running, the order doesnt seem to matter) (note: do not fold non-folding phones)

### Log File

>
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12209613/yuzu_log.txt)

### System Configuration

CPU: snapdragon 888
GPU/Driver: adreno 660 / mesa turnip
RAM: 12gb
OS: android 13

**Comment by t895** [comment]
Could you test again using the latest build here? https://github.com/yuzu-emu/yuzu-android/releases
