### ISSUE TITLE
[android] fastmem issue

### ISSUE THREAD

**Issue by M-hyun** [yuzu-emu/yuzu#11184]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

latest EA build/GitHub build

### Description of Issue

Everytime fastmem is on
-ram usage bulk faster.
-many random crashes more thn before in latest builds {ea or mainline} (like using camera in botw in certain areas...etc).
-unreal engine games don't go in game or crash...as in jump force and db kakarot...

### Expected Behavior

no crashes 

### Reproduction Steps

did tests with and without fastmem

### Log File

nothing shown in log only assertion failed

### System Configuration

CPU:sd870
GPU/Driver:latest turnip
RAM: 8gb
OS: androud 13

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum. Please use our Discord for support requests.
