### ISSUE TITLE
Confirm Exit option is not persisting state

### ISSUE THREAD

**Issue by kathyrollo** [yuzu-emu/yuzu#11187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline Build - b7f0c9074

### Description of Issue

![Screenshot 2023-07-31 152633](https://github.com/yuzu-emu/yuzu/assets/28589393/be0c0969-fd3d-4f82-8745-8b03cb7366b0)

The "Confirm exit" option keeps re-enabling itself after re-launching the emulator.

### Expected Behavior

The option should remain unchecked after the user unchecks it.

### Reproduction Steps

1. Uncheck the Confirm exit option.
2. Clear all hotkeys.
3. Re-assign ESC to Exit yuzu.
4. Re-assign Alt+Return to Fullscreen.
5. Leave all other keyboard/controller hotkeys blank.
6. Launch a game. Press ESC. Works as expected.
7. Re-launch the emulator. Open Emulation > Configure > General > General (tab). **The option is ticked again.**

### Log File

Unable to paste log contents. Maximum character limit reached.

### System Configuration

CPU: Ryzen 7 5800H - https://www.amd.com/en/product/10821
GPU/Driver: AMD Radeon Graphics (integrated) / 23.7.2
RAM: 16GB
OS: Win11 Pro 22H2

**Comment by lat9nq** [comment]
Can you retest using the latest build?

**Comment by kathyrollo** [comment]
@lat9nq The confirm exit state is now persisting after re-launch. Thanks for the quick fix, you can close this ticket. 👍
