### ISSUE TITLE
TOTK material becoms transparent

### ISSUE THREAD

**Issue by chipoez** [yuzu-emu/yuzu#11180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu1511

### Description of Issue

<img width="1209" alt="屏幕截图 2023-07-30 093915" src="https://github.com/yuzu-emu/yuzu/assets/33197406/7b39bb45-850c-4ed5-882a-9d9e2bdbd382">
<img width="976" alt="屏幕截图 2023-07-30 094619" src="https://github.com/yuzu-emu/yuzu/assets/33197406/a6549780-698c-4d41-8add-a81007fc2963">
Material becoms transparent in this version.The last version is normal but 1511 version works like above.

### Expected Behavior

The last version is normal but 1511 version works like above.

### Reproduction Steps

update to 1511 version,resotre settings to default,clear all cache and open TOTK

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12208361/yuzu_log.txt.old.txt)

### System Configuration

CPU:AMD 6800H
GPU/Driver:AMD 680M
RAM:32G
OS:win 11 22H2 22621.1992

**Comment by anpilley** [comment]
Update your AMD driver to the 23.7.2 version, a new one came out on the 25th of July that fixes this bug. Mainline build 1511 removed a block on a Vulkan feature that was buggy in prior AMD driver versions.
