### ISSUE TITLE
Intel UHD 620 + VULKAN instant crash - Metroid Dread (x0.5/0.7)

### ISSUE THREAD

**Issue by darioZIP** [yuzu-emu/yuzu#11189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1512

### Description of Issue

Yuzu VULKAN crashes while loading Metroid Dread, if the resolution is either 0.5 or 0.7. 
Does not matter if DOCKED/HANDLED.
Runs fine when running at resolution x1

OpenGL runs at 0.5, but with a lot of graphical glitches.
Screenshot of my video Yuzu settings.
![image](https://github.com/yuzu-emu/yuzu/assets/59956204/b1d16aa0-9f82-4c4b-baf0-5b67f6ba4fb5)

### Expected Behavior

It should just run...

### Reproduction Steps

Just try opening Metroid Dread from YUZU's interface. 
Will load for a while, then freeze and finally crash.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12215009/yuzu_log.txt)

### System Configuration

CPU: Intel i5-8250U
GPU/Driver: Intel UHD 620, v31.0.101.2125
RAM: 16GB
OS: Windows 11 x64 (build 22621)

My laptop is a HP Elitebook 830 G5.

**Comment by FearlessTobi** [comment]
This GPU is not supported anymore.
