### ISSUE TITLE
I'm playing botw (and totk) and the cutscenes are just... black, there is sound but no vision.

### ISSUE THREAD

**Issue by ArthurPizzaKid** [yuzu-emu/yuzu#11193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1513

### Description of Issue

When I'm playing botw cutscenes are just not loading.

### Expected Behavior

a cutscene

### Reproduction Steps

it is just there, I'm playing the game

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12221936/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD ryzen 5 3600
GPU/Driver: gtx 1660 super
RAM: 2*8 3200 mhz
OS: Windows 10

**Comment by german77** [comment]
Enable nvdec in gou settings

**Comment by ArthurPizzaKid** [comment]
> Enable nvdec in gpu settings

that worked, thank you.
