### ISSUE TITLE
Network Interface Does Save Across Restarts

### ISSUE THREAD

**Issue by AnimatedSwine37** [yuzu-emu/yuzu#11205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1514

### Description of Issue

Whenever Yuzu is started the network interface is always set back None. Having to reset it every time becomes quite annoying.

Looking at the `qt-config.ini` I've seen that `network_interface` gets set to nothing and `network_interface\default` to true as soon as I open Yuzu (before reopening it it `network_interface` has the interface name and `network_interface\default` false).

### Expected Behavior

When Yuzu is started the Network Interface setting should be the same as what it was when it was last closed.

### Reproduction Steps

Set the network interface to anything other than None then close Yuzu and open it again, the network interface will be back to None.

### Log File

Not relevant to this (I think)

### System Configuration

CPU: i5-2600K
GPU/Driver: RTX3060-Ti
RAM: 32GB
OS: Windows 11

**Comment by lat9nq** [comment]
Can this issue be retested?

**Comment by AnimatedSwine37** [comment]
I just tested and it works as expected now, the network interface stays the same on restart.
Thanks for the quick fix <3
