### ISSUE TITLE
Some objects are visible through walls in TOTK on Vulkan

### ISSUE THREAD

**Issue by NoobMaster452** [yuzu-emu/yuzu#11203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1514

### Description of Issue

In TOTK certain objects are visible through walls when using Vulkan. I'm running an RX 6650 XT.
![image](https://github.com/yuzu-emu/yuzu/assets/141193245/a5bc7032-5d7f-4510-a09c-4b732c0657f6)

### Expected Behavior

Objects should not be visible through walls

### Reproduction Steps

Simply run TOTK on vulkan and the issue should be recrated

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12234878/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5 3600
GPU/Driver: Radeon RX 6650 XT
RAM: 24GB DDR4
OS: Windows 10 Home

**Comment by Moonlacer** [comment]
Hello, could you please update to the latest AMD driver and see if the issue persists?

**Comment by anpilley** [comment]
Update your AMD gpu drivers to 23.7.2, you're seeing the result of a bug in the vulkan implementation of an extension in older AMD drivers.

**Comment by NoobMaster452** [comment]
A driver update fixed it, thanks a lot.
