### ISSUE TITLE
Double Dragon Gaiden: Rise of The Dragons Support

### ISSUE THREAD

**Issue by RUANRUI1995** [yuzu-emu/yuzu#11200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1513

### Description of Issue

The game file was added the correct way, but it does not show up.

### Expected Behavior

The game shows up and  runs well.

### Reproduction Steps

Add game file and open yuzu.Check if game shows up.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12226960/yuzu_log.txt)

### System Configuration

CPU:Intel i7 8700
GPU/Driver:AMD Vega 64 / 23.7.2
RAM:16GB
OS:Windows 11 22621.2070

**Comment by esQmo** [comment]
You should dump your keys again

**Comment by brujo5** [comment]
use yanu to patch game + update then will work. 

tested working

**Comment by RUANRUI1995** [comment]
> 

It works,thanks.

**Comment by coolman1282** [comment]
> use yanu to patch game + update then will work.
> 
> tested working

I tried to use yanu to update the base.nsp with update.nsp, but yanu always produces errors. How did you operate it?
