### ISSUE TITLE
svchost.exe uses 100% CPU even after Yuzu is closed.

### ISSUE THREAD

**Issue by SansQuartier** [yuzu-emu/yuzu#11201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline

### Description of Issue

When i start Yuzu and start a game, svchost.exe starts to use about 60-70% of my CPU.

When i close Yuzu, svchost.exe not only stays but starts using 100% of my CPU, i read online that it could be rootkit related but after doing scans with tronscript, it still occurs so i'm 99% that this is Yuzu related since it's somthing that only happens after closing it.

### Expected Behavior

When Yuzu is closed, CPU usage goes back to "baseline"

### Reproduction Steps

-Start Yuzu
-Start a game
-Close the game & Yuzu
-Check CPU usage in task manager

### Log File

Log is way to long, link here : https://github.com/SansQuartier/Perso/blob/main/log

### System Configuration

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
GPU/Driver: RTX 2070 Max-Q
RAM: 16
OS: Windows 11

**Comment by FearlessTobi** [comment]
This is an issue with Windows and not with yuzu.
