### ISSUE TITLE
Mario Kart 8 Deluxe Lan lobbies don’t show up

### ISSUE THREAD

**Issue by Vijuju** [yuzu-emu/yuzu#11222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1517

### Description of Issue

The problem is that I can’t see lan lobbies.
At all, even when I have confirmation that they’re open, so people can join, I can’t see any lobby in lan mode for whatever reason.
I can get into a lobby one time, and everything works perfectly until I quit the lobby. Then I will never see any lobby ever again
It works one time and then it never works again unless I factory reset my steam deck.
That is the only fix I found for this problem, but it works for only one match and it’s not viable for.. obvious reasons.
Maybe re-dumping my Rom would work?
I’m kinda desperate at this point, especially because no one else has this problem.
Thanks in advance.

(Note: Just to clarify, I don’t have firewalls, proxy servers or any other shenanigans.
Im using a mobile hotspot, but that’s clearly not the problem as the one race I had worked perfectly and I haven’t changed any settings since that first race)

### Expected Behavior

Mario Kart 8 Deluxe has a lan mode which works a lot better than normal wireless mode.
It’s accessed by pressing L+R+left thumb stick.
It’s not actual lan, it’s still internet multiplayer because we’re using Yuzu instead of an actual switch.

### Reproduction Steps

Play one or more Lan races and leave the Lan room after or during the race(s).
No Lan lobbies will ever appear again on the Lan menu.
(Wireless Play is not affected by this bug)

### Log File

I don’t think a log will be of much help, because giving the circumstances of this situation, nothing will result wrong in the log, there’s no connection errors or anything like that, it’s just that a thing doesn’t show up when it’s supposed to.
Anyway, here’s the log, I can’t get the actual file because I’m typing this from a phone, but I still can paste the contents of the file here: 
[   0.086428] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.086467] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.248523] Input <Info> input_common/drivers/joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.440511] Frontend <Info> yuzu/main.cpp:GMainWindow:365: yuzu Version: yuzu 1517
[   0.440527] Frontend <Info> yuzu/main.cpp:LogRuntimes:253: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.440529] Frontend <Info> yuzu/main.cpp:GMainWindow:381: Host CPU: AMD Custom APU 0405 | AVX2 | FMA
[   0.440575] Frontend <Info> yuzu/main.cpp:GMainWindow:383: Host CPU Cores: 4
[   0.440577] Frontend <Info> yuzu/main.cpp:GMainWindow:386: Host CPU Threads: 8
[   0.440625] Frontend <Info> yuzu/main.cpp:GMainWindow:387: Host OS: SteamOS
[   0.442425] Frontend <Info> yuzu/main.cpp:GMainWindow:388: Host RAM: 14.49 GiB
[   0.442442] Frontend <Info> yuzu/main.cpp:GMainWindow:390: Host Swap: 1.00 GiB
[   0.633795] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:442:     RomFS: Update (v0.16.0) applied successfully
[   0.637992] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:442:     RomFS: Update (v0.16.0) applied successfully
[   0.637992] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:442:     RomFS: Update (v0.16.0) applied successfully

### System Configuration

CPU: AMD Zen 2
GPU/Driver: Zen 2/RDNA 2 custom AMD APU
RAM: LPDDR5 RAM
OS: Steam OS 3.4.8

**Comment by FearlessTobi** [comment]
Your log is incomplete.

**Comment by Vijuju** [comment]
Ok so I was about to get the new log file when suddenly… it worked? I was able to get into one match of Mario kart and then I got disconnected and since that I’m still not able to see lan lobbies. I tried smash bros online as well and it also didn’t work.
Anyway here’s the log. Most of it is just shader compilation I think..
blob:https://mega.nz/68f5e930-f1a1-4bd2-b809-ab87b5be49f5
