### ISSUE TITLE
GPU usage keep in high load vs Ryuxxnx

### ISSUE THREAD

**Issue by Ryan2603** [yuzu-emu/yuzu#11229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

M1518 / EA3795

### Description of Issue

i don't know if this is an issue, maybe some fine tune i have missing, or maybe the issue if the dev team never know its exist, anyway i insist to inform you by this comparsion, hopefully this will bring some improvement soon.

long story short, GPU usage in average Yuzu >50%, in Ryuxxnx around 35% 

![Clipboard01](https://github.com/yuzu-emu/yuzu/assets/10262883/639c1823-4ec5-4cd4-b6dc-e0019fe57f3f)
![Clipboard02](https://github.com/yuzu-emu/yuzu/assets/10262883/a9dc4edc-f7e2-492e-bb76-8a1bd5086525)

### Expected Behavior

similar performance

### Reproduction Steps

compare both app

### Log File

none

### System Configuration

CPU: 5700X
GPU/Driver: 3060TI
RAM: 64GB
OS: W11 22631

**Comment by gidoly** [comment]
this is expected.
reason for this is ryujinx decode astc texture with cpu while we does on gpu for more performance

**Comment by Ryan2603** [comment]
> this is expected. reason for this is ryujinx decode astc texture with cpu while we does on gpu for more performance you can try compare gpu usage after setting cpu astc decoding if you curious

tested, doesn't help much...
![Clipboard03](https://github.com/yuzu-emu/yuzu/assets/10262883/b5bd245a-02bc-4ef2-86c9-d68bb4dead71)

**Comment by gidoly** [comment]
hmm isee there may be other reason for this. i think it is worth issue open so we can take a look on it in future

**Comment by gidoly** [comment]
can you post your graphic setting for referance?

**Comment by Ryan2603** [comment]
> can you post your graphic setting for referance?

sure, but mostly default settings, 
one special is in Ryuxxnx profile - threaded optimization is off (recommanded)
 
![Clipboard04](https://github.com/yuzu-emu/yuzu/assets/10262883/58ef39cb-8964-4d7d-a0db-dd7dbe944e11)
![Clipboard05](https://github.com/yuzu-emu/yuzu/assets/10262883/a03b04e5-faf6-432b-ad72-b921447cb790)
![Clipboard06](https://github.com/yuzu-emu/yuzu/assets/10262883/bc84aeaa-66cd-4ccf-bac5-332b8b0c8d07)

**Comment by gidoly** [comment]
have you enabled boost maximum clock on graphic advance by chance?

**Comment by Ryan2603** [comment]
> have you enabled boost maximum clock on graphic advance by chance?

nope, personally anti-overclock, if you asking for yuzu setting, here you go
![Clipboard08](https://github.com/yuzu-emu/yuzu/assets/10262883/608d6e2b-0d47-4e70-abbe-882b192bee14)

**Comment by Ryan2603** [comment]
> have you enabled boost maximum clock on graphic advance by chance?

OMG its solved!! 
by disable the "Force maximum clock (vulkan only)"

Big thanks to you @gidoly !!!

**Comment by Squall-Leonhart** [comment]
the setting runs a smaller shader so that the gpu never clocks down from the boost clocks to Low Power 3D, on low intensive games this is fine, and does the job. on high intensive games it interferes with peak performance.
