### ISSUE TITLE
Continue from last save button doesn't work in TOTK

### ISSUE THREAD

**Issue by NoobMaster452** [yuzu-emu/yuzu#11227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1518

### Description of Issue

Whenever I die in TOTK and press the "Continue" button nothing happens. The game just freezes.

### Expected Behavior

It should load the most recent save.

### Reproduction Steps

Simply die while playing TOTK.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12270140/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5 3600
GPU/Driver: AMD Radeon RX 6650 XT
RAM: 24GB at 3000 MHz
OS: Windows 10

**Comment by liamwhite** [comment]
disable fps mod

**Comment by NoobMaster452** [comment]
that worked

**Comment by dagamincrusadr** [comment]
Is there any way to troubleshoot/ workaround this? I would like to still have 60fps but not restart the emulator every time I die. Feel free to let me know if there are any alternative mods I should use, at the moment I am just using Dynamic FPS 1.5.5 1080p 60FPS, Disable Quality Reduction, and the UI Blackscreen fix.

**Comment by liamwhite** [comment]
It's a bug in the game/mod, what are we supposed to do about it?
