### ISSUE TITLE
Cant Progress past this part of rain code due to freeze no matter what I do

### ISSUE THREAD

**Issue by ThatGuyRai** [yuzu-emu/yuzu#11220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3540

### Description of Issue

I get to this one section in the mystery labrynth in Ch0 and it freezes right after I select red herring key, the text freezes and game freezes, and its stuck forever. I checked open gl and vulkan too, no luck and im on a 6800xt latest drivers. So in turn I tried ryujinx and boom! same freeze at the same spot EXCEPT it full on dies there, like crashes fully. I dont get why this is happening and i cant progress cuz of it (pictured below)
![image](https://github.com/yuzu-emu/yuzu/assets/71162577/d8dc02f1-c877-4714-a9bd-7f04a79d8f5e)

### Expected Behavior

I am supposed to be able to advance the dialogue as normal during this part

### Reproduction Steps

Go up to the mystery door in ch0 when youre pointing out zilchs death being a red herring then select, th next dialogue will crash and or freeze the game to an unplayable/uninteractable state yet will still play music.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12267585/yuzu_log.txt)

### System Configuration

CPU: 5800x ryzen 7
GPU/Driver: 6800xt - 23.7.2
RAM: 32 Gb DDR4 3200Mhz
OS: Win 10 Pro

**Comment by anpilley** [comment]
Your Early Access build is over 200 builds old. Update to a current build of yuzu off of the download page at https://yuzu-emu.org/downloads/#windows. 

Follow https://yuzu-emu.org/wiki/faq/#yuzu-will-not-update-further-or-starts-with-a-qt-platform-error if you can't update.

**Comment by ThatGuyRai** [comment]
it was the 1440p mod! a particle effect happens after that text, I presume the 1440p mod broke it causing a crash, Ill disable the 1440p mod for now and if the game crashes like that again ill know to disbale it for a save point!

**Comment by eapiova** [comment]
I had the same problem in Ch2, temporarily disabled 1440p mod and everything worked fine! Thanks
