### ISSUE TITLE
Save data *SHOULD NOT* be stored in AppData!

### ISSUE THREAD

**Issue by T-O-R-U-S** [yuzu-emu/yuzu#11232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Any that use saves

### Description of Issue

In the Windows developer documentation, `AppData` is described: The lifetime of the app data is tied to the lifetime of the app. If the app is removed, all of the app data will be lost as a consequence. Don't use app data to store user data or anything that users might perceive as *valuable and irreplaceable*.

An example of something valuable and irreplaceable is game saves.

And, indeed, when Windows is reset with the 'Keep my Files' option, a setting that keeps all user data, AppData is completely wiped by Windows (or, more accurately, it's moved into `Windows.old`, unless there is a conflicting file in that location).

### Expected Behavior

Yuzu save data should not be stored in the AppData directory; a different location for the save data needs to be selected. Ideally, it would be somewhere in `Documents/My Games`, since that seems to be somewhat standard (and is NOT deleted/altered by Windows).

### Reproduction Steps

Play any game that has save data, and it will be stored in the non-ideal directory.

### Log File

*Not exactly necessary for this issue

Additional considerations:
- Yuzu will have to unfortunately check both AppData AND the new save data folder for user saves if this change goes through.
- How does Yuzu handle conflicts of save data?

### System Configuration

CPU: Ryzen 5900X
GPU/Driver: RTX 3090 / Studio Driver 536.67
RAM: 32 GB
OS: Windows 11

**Comment by Squall-Leonhart** [comment]
I quit this crusade long ago with other emulators, the developers don't care if they've offered portable setups and directory configurability.

**Comment by kathyrollo** [comment]
You can make Yuzu portable. Don't use the installer and download the latest build - https://yuzu-emu.org/downloads/#windows

Extract to your desired location and create a `user` folder in the root directory. Do NOT run the yuzu.exe file until you created the folder first or it will just re-create the config files in AppData again. It works exactly like Citra.

**Comment by FearlessTobi** [comment]
Yuzu is using the Appdata directory just like many other games and emulators ([Dolphin](https://de.dolphin-emu.org/blog/2023/02/12/dolphin-progress-report-december-2022-january-2023/#50-18242-change-default-user-directory-location-to-appdata-on-windows-and-50-18238-menubar-add-action-which-opens-the-user-folder-by-oatmealdome), Minecraft, Citra, etc.).

We have no plans to change this at the current time. If you have concerns about this, you can always create a "user" folder in your yuzu installation directory to make the yuzu instance portable.
