### ISSUE TITLE
Extra popup when game save is about to be overwritten

### ISSUE THREAD

**Issue by FRO4TEN** [yuzu-emu/yuzu#11255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

When the user uses the new version of yuzu to overwrite the old version, the user shoud be reminded that the game saves will also be emptied, and the user should be reminded to make a backup.

### Why would this feature be useful?

Some users may not know that the default location of the game saves are in the directory that will be overwritten, which will reduce their losses

**Comment by FearlessTobi** [comment]
Yuzu does not overwrite game saves when updating.

**Comment by FRO4TEN** [comment]
Thx for replying. Actually, my statement is missing certain details. When you use yuzu_installer to try to update a non-yuzu_installer installed yuzu folder(such as a folder copyed from another disk), that folder will be overwrited. Will yuzu be able to add detection for this situation to avoid unnecessary save loss.

**Comment by FRO4TEN** [comment]
> Yuzu does not overwrite game saves when updating.

Thx for replying. Actually, my statement is missing certain details. When you use yuzu_installer to try to update a non-yuzu_installer installed yuzu folder(such as a folder copyed from another disk), that folder will be overwrited. Will yuzu be able to add detection for this situation to avoid unnecessary save loss. 😊
