### ISSUE TITLE
persona 5 royal crashes quick with 60fps patch and 1080p docked mod

### ISSUE THREAD

**Issue by soredake** [yuzu-emu/yuzu#11250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3795

### Description of Issue

Persona 5 royal quickly crashes when 60fps patch is used, it can crash in main menu, when you select a save, when you load save or rarely after you load save.

### Expected Behavior

No crash.

### Reproduction Steps

1) Install persona 5 royal with 1.0.2 update.
2) Set game to docked mode and accuracy to normal.
2) Extract mods to persona 5 royal mod directory [01005CA01580E000.zip](https://github.com/yuzu-emu/yuzu/files/12299031/01005CA01580E000.zip)

### Log File

[yuzu_log_1.0.2 version.txt](https://github.com/yuzu-emu/yuzu/files/12298987/yuzu_log_1.0.2.version.txt)

### System Configuration

CPU: ryzen 7 1800x
GPU/Driver: rx 560
RAM: 32gb
OS: Windows 11 Pro

**Comment by soredake** [comment]
Setting accuracy to high fixed this, but will need to test longer.

**Comment by FearlessTobi** [comment]
We do not provide support for mods.
