### ISSUE TITLE
Asterix and Obelix XXL graphical issues

### ISSUE THREAD

**Issue by chico34** [yuzu-emu/yuzu#11252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1518 

### Description of Issue

The game suffers from texture corruption and missing particles on this emulator:
![image](https://github.com/yuzu-emu/yuzu/assets/73502484/779d034c-9904-4c8f-9cbc-22b0e356568b)

### Expected Behavior

Game is supposed to look like this:
![image](https://github.com/yuzu-emu/yuzu/assets/73502484/0faff631-00e7-4820-8530-baee28ca809b)

### Reproduction Steps

Just open the game on the emulator and get trought the menus

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12307803/yuzu_log.txt)

### System Configuration

CPU: r 5600g
GPU/Driver: gtx 1050 ti (536.67) 
RAM: 16g 3200mz
OS: Windows 11

**Comment by Squall-Leonhart** [comment]
can you try with the windows artifact attached to this action

https://github.com/yuzu-emu/yuzu/actions/runs/5777579141

**Comment by chico34** [comment]
Hello, it seems to have the same issue

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Squall-Leonhart** [comment]
i've narrowed the potentials to R16G16B16A16, A8B8G8R8, Z24S8, ASTC_2D_4X4 or ASTC_2D_8X8

given that the last 2 are converted to another format, they are the prime candidates.

**Comment by Squall-Leonhart** [comment]
Broken by https://github.com/yuzu-emu/yuzu/commit/01c4568786631515ea13ec8cf991d534272e87b7
