### ISSUE TITLE
Link's Awakening - Froze after 8th Dungeon Dialogue on 1518

### ISSUE THREAD

**Issue by mikegonzalez2k** [yuzu-emu/yuzu#11254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1518

### Description of Issue

In Legend of Zelda: Link's Awakening I beat the 8th boss, picked up the musical instrument.  It went to the usual white screen to tell me where to go.  After the dialogue the game looked like it was trying to auto save.  During that saving process it froze.

This happened on Mainline 1518

### Expected Behavior

After acquiring the music instrument of the 8th Dungeon the game should not freeze.

### Reproduction Steps

Get to the 8th Dungeon (Turtle Rock).
Beat the boss and acquire the musical instrument.
The game will go to a white screen and tell you to go to the egg.
After that dialogue the game will try to auto save.
During this save process the game will freeze.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12311601/yuzu_log.txt)

### System Configuration

CPU: i7-9750H
GPU/Driver: Nvidia Geforce GTX 1650  v 536.40
RAM: 16 GB
OS: Windows 10 Home

**Comment by Squall-Leonhart** [comment]
you ran out of vram, please confirm bugs before opening issues.

> [22253.747977] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_as_gpu.cpp:operator ():410: Assertion Failed!
Failed to allocate free space in the GPU AS!

**Comment by ShimadzuToyohise** [comment]
why this case is getting help and mine got close with we dont support pirates?????
