### ISSUE TITLE
Disney Illusion Island: Map is blank when resuming a save file

### ISSUE THREAD

**Issue by metalmight** [yuzu-emu/yuzu#11266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1520

### Description of Issue

Anytime I resume a save file, the map is blank and I have to start filling it in again from scratch.

### Expected Behavior

The places I had gone previously should be filled in.

### Reproduction Steps

Step 1: Play some of Disney Illusion Island and fill in some of the map.
Step 2: Quit the game.
Step 3: Load the game again.
Step 4: Load your save file that you previously played from Step 1.
Step 5: Open the map.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12326500/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5 3600
GPU/Driver: NVIDIA GeForce RTX 3060 12GB/536.99
RAM: 16GB
OS: Windows 10 Home, Version 22H2, Build 19045.3324, Windows Feature Experience Pack 1000.19041.1000.0

**Comment by gidoly** [comment]
Log contain piracy evidence. Closing
