### ISSUE TITLE
Yuzu crashes while opening any game 

### ISSUE THREAD

**Issue by Shahidshekh** [yuzu-emu/yuzu#11265]
Opening smash ultimate:
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12326518/yuzu_log.txt.old.txt)

Opening totk:
[yuzu_log.txt.txt](https://github.com/yuzu-emu/yuzu/files/12326507/yuzu_log.txt.txt)
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Early access 3801

### Description of Issue

Hey yuzu-ers!

Since yesterday morning, my yuzu began to crash everytime I open a game. At first it threw an error while shaders are loading saying "application could not be started correctly". Then I tried removing all the shader cache but now it began to crash right after "Launching" screen without any message. Then I tried reinstalling yuzu completely but it didn't help. I tried checking logs it says something like "assertion failed" at the end of the log. I can upload it here if necessary. Please help.

Thank you.

### Expected Behavior

Crashes

### Reproduction Steps

NA

### Log File

NA

### System Configuration

CPU: i7 6700
GPU/Driver: GTX 1060 6gb with latest drivers 
RAM: 16gb
OS: Windows 10 pro

**Comment by liamwhite** [comment]
the yuzu log file is necessary for diagnosis, please provide it

**Comment by Shahidshekh** [comment]
> the yuzu log file is necessary for diagnosis, please provide it

Done sir.

**Comment by liamwhite** [comment]
In settings, disable:
General -> Debug -> Enable Graphics Debugging
System -> Custom RTC

See if that fixes it.

**Comment by Shahidshekh** [comment]
> In settings, disable:
> General -> Debug -> Enable Graphics Debugging
> System -> Custom RTC
> 
> See if that fixes it.

No sir.
It was same as before.

**Comment by liamwhite** [comment]
In General -> Debug -> Debugging, enable minidump creation, then restart yuzu and load the game to the point of the crash. Then zip the .dmp file that it generates and upload it here.

**Comment by Shahidshekh** [comment]
> In General -> Debug -> Debugging, enable minidump creation, then restart yuzu and load the game to the point of the crash. Then zip the .dmp file that it generates and upload it here.

Where to find .dmp file sir?

**Comment by liamwhite** [comment]
It should be in `%localappdata%\yuzu\yuzu-windows-msvc\`.

**Comment by Shahidshekh** [comment]
> In General -> Debug -> Debugging, enable minidump creation, then restart yuzu and load the game to the point of the crash. Then zip the .dmp file that it generates and upload it here.

[yuzu-crash-20230812103456.zip](https://github.com/yuzu-emu/yuzu/files/12326630/yuzu-crash-20230812103456.zip)

Here it is sir.

**Comment by liamwhite** [comment]
Please delete of your dump files and then recapture a dump with early access 3803 (latest as of writing this comment). Your logs show testing different versions of yuzu and I cannot load this dump because I do not know which version was used to capture it.

**Comment by Shahidshekh** [comment]
> Please delete your dump files and then recapture a dump with early access 3803 (latest as of writing this comment). Your logs show testing different versions of yuzu and I cannot load this dump because I do not know which version was used to capture it.

[yuzu-crash-20230813143114.zip](https://github.com/yuzu-emu/yuzu/files/12329124/yuzu-crash-20230813143114.zip)

This dump captured from Yuzu EA 3804 (latest).

**Comment by liamwhite** [comment]
Thank you for the update. The dump shows yuzu crashed because the entire system ran out of memory. Try closing other applications first (like those that may live in the system tree) to see if it helps free up enough memory to boot.

**Comment by FearlessTobi** [comment]
This seems to be a problem with the specific computer and not yuzu then.
Closing
