### ISSUE TITLE
Neverwinter Nights Enhanced Edition - Character menu and graphic issue

### ISSUE THREAD

**Issue by klz-fc** [yuzu-emu/yuzu#11277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1520

### Description of Issue

When selecting a pregenerated character, the menu is shifted down and overlaps the button menus, which covers up the button to customize your own character and the Ok button.

![image](https://github.com/yuzu-emu/yuzu/assets/103147197/05541144-92c9-490b-95f2-07432c6d02bc)

After starting the Tutorial, textures and lighting are nto working and objects pop in and out of visibility when moving.

![image](https://github.com/yuzu-emu/yuzu/assets/103147197/b1c5d1dd-1125-448a-9b95-cf1d9e5bda71)
![image](https://github.com/yuzu-emu/yuzu/assets/103147197/2a006c20-a7ef-419c-90fd-767e0eb17c6a)
![image](https://github.com/yuzu-emu/yuzu/assets/103147197/811c07bb-9f60-4ca0-8e80-fe2c4ebc8661)
![image](https://github.com/yuzu-emu/yuzu/assets/103147197/9d1d00b4-505d-4e0b-ac52-d07580460d6e)

### Expected Behavior

The menu and objects are rendered correctly

### Reproduction Steps

Start a new game in the main campaign tutorial and select a pregenerated character.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12328370/yuzu_log.txt)

### System Configuration

CPU: Intel i9-12900H
GPU/Driver: nVidia GeForce RTX 3070 Ti Laptop GPU / Driver: Geforce 536.99
RAM: 32GB
OS: Windows 11 (10.0) Professional 64-bit   (Build 22621)

**Comment by gidoly** [comment]
close due to log having piracy evidence.
