### ISSUE TITLE
-

### ISSUE THREAD

**Issue by nixnothing** [yuzu-emu/yuzu#11279]
-

**Comment by Pergmen** [comment]
A feature where Yuzu issues a warning on launch if the disk the OS is on, or the Yuzu directory is in, is below a certain threshold for free space isn't a bad idea, but you can't ask a car that is already speeding into a brick wall to gracefully stop. If Yuzu can't write to the disk, crashing is the safest thing it can do

**Comment by Squall-Leonhart** [comment]
Not sure where the logic in this is, even windows will crash if the OS disk becomes thoroughly incapable of storing more.

**Comment by nixnothing** [comment]
> Not sure where the logic in this is, even the host OS will crash if the disk becomes thoroughly incapable of storing more.

Not in many cases. If you have a small amount of disk space free, you will run into this issue. Windows has  never crashed on me for this, and I run out of space several times before.

Hey, I was told it would be helpful to report. Doesn't really bother me personally, I already solved the issue on my end...

**Comment by Squall-Leonhart** [comment]
> Not in many cases. If you have a small amount of disk space free, you will run into this issue. Windows has never crashed on me for this, and I run out of space several times before.

Windows will immediately crash on an attempt to write memory backed state content such as the registry to a full disk.
