### ISSUE TITLE
Skyword sword launch crash

### ISSUE THREAD

**Issue by ShimadzuToyohise** [yuzu-emu/yuzu#11274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early accsses 3803

### Description of Issue

Skyword sword crahes on launch

### Expected Behavior

Skyword sword should run and let me in the game

### Reproduction Steps

Open the zelda skyword sword
Wait until it crashes
sometimes gets to logo sometimes right away

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12328324/yuzu_log.txt)

### System Configuration

CPU: Z1 extreme
GPU/Driver: Integrated\22.40.58.04
RAM:16.0 GB (11.7 GB usable) DDR5X
OS: Windows 11

**Comment by gidoly** [comment]
close due to log contains piracy evidence

**Comment by ShimadzuToyohise** [comment]
what exactly what should i do to get help
