### ISSUE TITLE
Skyword Sword crash on vulkan after logo

### ISSUE THREAD

**Issue by ShimadzuToyohise** [yuzu-emu/yuzu#11270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early accsses 3803

### Description of Issue

Playing on Asus Rog Ally had some driver updates, now skyword sword crashes on launch if with shaders with shaders clear crash occurs on logo. Works fine on open gl tho.

### Expected Behavior

Not to crash and launch the game like it was earlier

### Reproduction Steps

Launch the skyword sword 

### Log File

**Log file removed by moderator.**

### System Configuration

CPU: Z1 extreme chip
GPU/Driver: 22.40.58.04
RAM:16 gb 6000mhz ddr5x
OS: windows 11

**Comment by ShimadzuToyohise** [comment]
[yuzu-crash-20230812190440.zip](https://github.com/yuzu-emu/yuzu/files/12327762/yuzu-crash-20230812190440.zip)

**Comment by SleepingSnakezzz** [comment]
We do not support piracy here.
