### ISSUE TITLE
Skyword crash report

### ISSUE THREAD

**Issue by ShimadzuToyohise** [yuzu-emu/yuzu#11276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early accsses 3803

### Description of Issue

Skyword sword crahes on launch

### Expected Behavior

Skyword sword should run and let me in the game

### Reproduction Steps

Open the zelda skyword sword
Wait until it crashes
sometimes gets to logo sometimes right away

### Log File

will be added on demand

### System Configuration

CPU:Z1 extreme
GPU/Driver: Integrated\22.40.58.04
RAM: 16.0 GB (11.7 GB usable) DDR5X
OS:  Windows 11

**Comment by Squall-Leonhart** [comment]
This is a Rog Ally?

Set the dynamic video memory back to defaults in the firmware
