### ISSUE TITLE
game screen size change about galaxy tab s9 

### ISSUE THREAD

**Issue by DunkHimYo** [yuzu-emu/yuzu#11285]
### Issue

Playing "The Legend of Zelda: Breath of the Wild2" on the gen2 specs reportedly yields around 10 to 20 frames per second, but on the Galaxy Tab S9, it performs even worse. In my opinion, this might be due to the larger screen size. Unfortunately, there doesn't seem to be a feature that can reduce the size of the game screen other than changing the resolution. Do you have any plans to add a feature to reduce the game screen size?

**Comment by liamwhite** [comment]
The size of the screen has effectively no impact on the performance. As you pointed out, only the rendering resolution impacts performance. The system is most likely limited by bad thermals.

**Comment by DunkHimYo** [comment]
> The size of the screen has effectively no impact on the performance. As you pointed out, only the rendering resolution impacts performance. The system is most likely limited by bad thermals.


Thank you for your response. Indeed, I have observed significant performance degradation due to throttling issues. It seems that more time will be needed for proper optimization.

**Comment by FearlessTobi** [comment]
Closing due to use of wrong issue template.
