### ISSUE TITLE
Mii applet or mii application

### ISSUE THREAD

**Issue by SudoTheHacker** [yuzu-emu/yuzu#11280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Adding a mii applet or support the official mii application like ryujinx.

### Why would this feature be useful?

Some game need the mii feature like Mario kart 8 deluxe.

**Comment by FernandoS27** [comment]
As a note: You don't need to create a mii to use those games. Just install the firmware and it comes with a few preset Miis.
