### ISSUE TITLE
Any progess on the broken translation vary likely caused by the PR10839#?

### ISSUE THREAD

**Issue by RUANRUI1995** [yuzu-emu/yuzu#11291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline1504+ / EA3770+

### Description of Issue

https://github.com/yuzu-emu/yuzu/pull/10839#issuecomment-1650898777
![微信截图_20230815105301](https://github.com/yuzu-emu/yuzu/assets/18418418/42cf7f40-e8ae-48e1-a00f-a3ba2c0d7b24)

### Expected Behavior

The setting language become correct.

### Reproduction Steps

Update to mainline 1504 or ea 3770.
Change to other language like Chinese.
Almost all settings are still English.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12340882/yuzu_log.txt)

### System Configuration

CPU:i7 8700
GPU/Driver:Vega64/23.7.2
RAM:16GB
OS:Win11 22H2

**Comment by FearlessTobi** [comment]
These settings need to be retranslated sadly, you can help by signing up on on Transifex: https://explore.transifex.com/yuzu-emulator/yuzu/.
