### ISSUE TITLE
Yuzu on Xbox Dev mode.

### ISSUE THREAD

**Issue by ssdecf** [yuzu-emu/yuzu#11306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I know this has been requested a lot, but couldn’t you add yuzu to Xbox Dev Mode? I’m pretty sure Dev Mode can support Open GL and Vulkan.  If it isn’t, then is there anyway for Yuzu to support DirectX12?

### Why would this feature be useful?

Playing Nintendo Switch games on Xbox

**Comment by FernandoS27** [comment]
Xbox only supports D3D12. In the future we may add support through Mesa Dozen but currently there are no plans for a D3D12 backend.
