### ISSUE TITLE
[TotK] Flickering signs and signboards

### ISSUE THREAD

**Issue by askikataski** [yuzu-emu/yuzu#11311]
### Issue

Is there an existing issue for this?
I have searched the existing issues and is not.

Affected build(s)
Every version since launch.

Description of issue
The signs and signboards flicker when you walk near them.

Link to a video showing the issue
https://www.reddit.com/user/askikataski/comments/15ue897/flickering_signs_and_signboards_on_yuzu/

Expected behavior
Fix the flickering signs and signboards.

Reproduction steps
The problem is present with or without any mod at any resolution or framerate. My configuration is the same as the new recomendations on the Holographic Wings GitHub page.

Log file
NONE

System configuration
CPU: 5800x3d
GPU/Driver: RTX 2070 desktop
RAM: 32GB
OS: Win11 with newest update

**Comment by Squall-Leonhart** [comment]
Duplicate https://github.com/yuzu-emu/yuzu/issues/10539, can't be fixed without significant performance drop.

**Comment by askikataski** [comment]
@Squall-Leonhart What do you mean with can't be fixed  without significant performance drop? I know that setting the CPU accuracy at paranoid the glitch is fixed but with a heavy performance cost.
And what extension are your talking about? What other gpus instead desktop gpus exist? laptops?

**Comment by FearlessTobi** [comment]
Closing as duplicate.
