### ISSUE TITLE
ASTC texture always being reloaded after turning camera back. Bayonetta 3

### ISSUE THREAD

**Issue by zhm86** [yuzu-emu/yuzu#11315]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Early Access 3817

### Description of Issue

ASTC texture always being reloaded after turning camera back.
I disable Reactive Flushing.
I purposely set ASTC Decoding Method: CPU Asynchronous, so that we could see the texture reloading.
If I set ASTC Decoding to GPU, the texture reloading turns out big shutter.

![Video_2023-08-18_225224](https://github.com/yuzu-emu/yuzu/assets/16450203/23c3eb9c-7729-4e0a-9c9d-91bb48e8131a)

### Expected Behavior

Do not reload texture while VRAM is not full.

### Reproduction Steps

Enter Chapter 11 - A Familiar Dance

### Log File

**Log file removed by moderator**

### System Configuration

CPU: E3-1231 v3
GPU/Driver: nvidia GTX 1650 4GB VRAM Driver: 536.67
RAM: 10GB
OS: Windows 10 Version 22H2

**Comment by liamwhite** [comment]
yuzu tries to maintain a significant amount of VRAM unused to avoid operating system crashes and allow momentary spikes in usage past steady state. From its perspective, it is full right now and you likely just don't have enough VRAM.

**Comment by SleepingSnakezzz** [comment]
We do not support piracy here.
