### ISSUE TITLE
None of you know anything about Engineering. Mechanical Engineering is the ONLY Engineering. Period.

### ISSUE THREAD

**Issue by ghost** [yuzu-emu/yuzu#11329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I have not searched for existing "issues" in the issue thread.
There is no such this as "reverse" "engineering". Quit using the amazing word "Engineering" in your garbage emulator.  That is the stupidest and most pathetic lie ever. Stop being disrespectful & insulting to Engineering. You know nothing about what Engineering entails. Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with clowns sitting behind a keyboard and decoding/programming/deciphering etc. Software dev is easy and for kids and young teens. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). So quit being wannabes. Ya'll will never even come close to being an engineer. 
Quit making false claims against engineering you. And stop being disrespectful to real engineers (Mechanical Engineering is the ONLY Engineering, PERIOD).

Death to all "universities". Death to every loser who uses the stupid & childish & moronic "titles" when mentioning first names. Death to every donkey who works for the red cross and it's stupid and useless "sector". 

### Why would this feature be useful?

I have not searched for existing "issues" in the issue thread.
There is no such this as "reverse" "engineering". Quit using the amazing word "Engineering" in your garbage emulator.  That is the stupidest and most pathetic lie ever. Stop being disrespectful & insulting to Engineering. You know nothing about what Engineering entails. Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with clowns sitting behind a keyboard and decoding/programming/deciphering etc. Software dev is easy and for kids and young teens. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). So quit being wannabes. Ya'll will never even come close to being an engineer. 
Quit making false claims against engineering you. And stop being disrespectful to real engineers (Mechanical Engineering is the ONLY Engineering, PERIOD).

Death to all "universities". Death to every loser who uses the stupid & childish & moronic "titles" when mentioning first names. Death to every donkey who works for the red cross and it's stupid and useless "sector".

**Comment by FernandoS27** [comment]
lol.
