### ISSUE TITLE
Building for android

### ISSUE THREAD

**Issue by mrx7014** [yuzu-emu/yuzu#11322]
### Issue

How can i rebuild this for android,when i try it with gradle it give me this error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0.
     Required by:
         project :
      > No matching variant of androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0 was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.1' but:
          - Variant 'apiElements' capability androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1')
          - Variant 'runtimeElements' capability androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1')
          - Variant 'sourcesElements' capability androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s

**Comment by liamwhite** [comment]
Close android studio, clean the entire source tree with `git clean -xfdf; git submodule foreach "git clean -xfdf"` and then reopen the src/android directory and pray that it works. Repeat until it actually does work. Android studio is very bad.

**Comment by mrx7014** [comment]
> Close android studio, clean the entire source tree with `git clean -xfdf; git submodule foreach "git clean -xfdf"` and then reopen the src/android directory and pray that it works. Repeat until it actually does work. Android studio is very bad.
> 
> Also, you need at least studio "Giraffe" (2022.3.1)

Actually I use Linux to build using the command ./gradlew build

**Comment by FearlessTobi** [comment]
You are very likely using an outdated version of Android Studio or whatever toolchain you have installed for Android development,.
We might be able to help you further if you join our Discord.
