### ISSUE TITLE
Quit insulting Engineering

### ISSUE THREAD

**Issue by ghost** [yuzu-emu/yuzu#11330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 

### Description of Issue

I have not searched for existing "issues" in the issue thread.
Quit using the amazing word "Engineering" in your garbage emulator. There is no such this as "reverse" "engineering". That is the stupidest and most pathetic lie ever. Stop being disrespectful & insulting to Engineering. You know nothing about what Engineering entails. Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with clowns sitting behind a keyboard and decoding/programming/deciphering etc. Software dev is easy and for kids and young teens. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). Quit making false claims against engineering you. And stop being disrespectful to real engineers (Mechanical Engineering is the ONLY Engineering, PERIOD).

### Expected Behavior

Quit using the amazing word "Engineering" in your garbage emulator. There is no such this as "reverse" "engineering". That is the stupidest and most pathetic lie ever. Stop being disrespectful & insulting to Engineering. You know nothing about what Engineering entails. Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with clowns sitting behind a keyboard and decoding/programming/deciphering etc. Software dev is easy and for kids and young teens. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). Quit making false claims against engineering you. And stop being disrespectful to real engineers (Mechanical Engineering is the ONLY Engineering, PERIOD).

### Reproduction Steps

Quit using the amazing word "Engineering" in your garbage emulator. There is no such this as "reverse" "engineering". That is the stupidest and most pathetic lie ever. Stop being disrespectful & insulting to Engineering. You know nothing about what Engineering entails. Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with clowns sitting behind a keyboard and decoding/programming/deciphering etc. Software dev is easy and for kids and young teens. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). Quit making false claims against engineering you. And stop being disrespectful to real engineers (Mechanical Engineering is the ONLY Engineering, PERIOD).

### Log File

Quit using the amazing word "Engineering" in your garbage emulator. There is no such this as "reverse" "engineering". That is the stupidest and most pathetic lie ever. Stop being disrespectful & insulting to Engineering. You know nothing about what Engineering entails. Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with clowns sitting behind a keyboard and decoding/programming/deciphering etc. Software dev is easy and for kids and young teens. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). Quit making false claims against engineering you. And stop being disrespectful to real engineers (Mechanical Engineering is the ONLY Engineering, PERIOD).

### System Configuration

null

**Comment by gidoly** [comment]
go touch grass fr how you doing this for years
