### ISSUE TITLE
Please fix screen rotation bug in android

### ISSUE THREAD

**Issue by Finblade** [yuzu-emu/yuzu#11335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

In previous version, when i rotate my phone to other landscape side it automatically rotated but after some update it does not rotate unless turn on screen rotation in my phone setting. Please fix it. Skyline support this. Even YouTube support this. I can't understand why dev blocked auto screen rotate to other landscape side in this way. It is so uncomfortable.

### Why would this feature be useful?

This is so uncomfortable when i use usb cable for charging while i play games

**Comment by t895** [comment]
We don't plan on fixing this but you are able to change the rotation of the display from landscape to reverse-landscape as provided by Android.

When using rotation lock, rotate the screen to the desired position, and press the button that appears in the corner of the screen with the "rotate" icon. If you don't see this, it's probably inside the navigation bar which is hidden at the start of emulation. Just reveal the navigation bar and press the button using the steps from before.

**Comment by Finblade** [comment]
> We don't plan on fixing this but you are able to change the rotation of the display from landscape to reverse-landscape as provided by Android.
> 
> When using rotation lock, rotate the screen to the desired position, and press the button that appears in the corner of the screen with the "rotate" icon. If you don't see this, it's probably inside the navigation bar which is hidden at the start of emulation. Just reveal the navigation bar and press the button using the steps from before.

I know the function that you explained but i want to know the reason why you don't have plan to fix it.

**Comment by Finblade** [comment]
I know the function that you explained and it is still uncomfortable. I
want to know the reason why you don't have plan to fix it. It is kinds of
basic function of all android applications you know

2023년 8월 20일 (일) 오후 11:18, Charles Lombardo ***@***.***>님이 작성:

**Comment by t895** [comment]
Actually, you got me thinking. I will have a fix out shortly.

**Comment by Finblade** [comment]
> Actually, you got me thinking. I will have a fix out shortly.

Thanks :) Finally it will be fixed :) i will just wait for next android update.
