### ISSUE TITLE
The Legend of Zelda: Link's Awakening black screen on yuzu 1532 with UHD 620

### ISSUE THREAD

**Issue by Duy-Thanh** [yuzu-emu/yuzu#11339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1532

### Description of Issue

When I play this game with Vulkan, yuzu will immediately close after launching progress bar stopped a bit.

And of course, my GPU device are compatible with Vulkan:

![image](https://github.com/yuzu-emu/yuzu/assets/36120800/26e8f619-1f31-4a3f-86db-a390a5ccaefc)

After failing with Vulkan, I switched to OpenGL GLSL. Now yuzu working, but only black screen and sound work, and FPS say the game running on 43 FPS?

![1](https://github.com/yuzu-emu/yuzu/assets/36120800/35f7a096-925b-4b00-86cd-b6b0c7646c0b)

### Expected Behavior

The game can work and yuzu should render and display correctly

### Reproduction Steps

None

### Log File

 Here's the log when running on Vulkan:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12394921/yuzu_log.txt)

Here is the log when I switched to OpenGL GLSL

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12394996/yuzu_log.txt)

**UPDATED: I have enabled Debug graphics and maybe log contains more useful to investigate this problems:**

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12395063/yuzu_log.txt)

### System Configuration

CPU: Core i3-8145U
GPU/Driver: Intel UHD620 Graphics
RAM: 12 GB
OS: Windows 10 Pro 22H2

**Comment by Squall-Leonhart** [comment]
that IGP has no further support on Windows, which means there will be no fixes for the driver issues that remain an obstacle to using yuzu with them,  you would need to switch to linux.
