### ISSUE TITLE
red dead redemption visual bug

### ISSUE THREAD

**Issue by MrRokiIsBored** [yuzu-emu/yuzu#11333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 689dc4a117

### Description of Issue

when booting the game in yuzu mobile, it runs pretty well, even up to 50 fps but the visuals are broken, like if yoiu move the camera, the texture start to rub the screen like someone taking a poop and whipping it on his nighbors door

### Expected Behavior

like any tps open world game, the game didnt must not do that

### Reproduction Steps

an update that fixes the issue in the yuzu mobile version

### Log File

there is no log file in mobile

### System Configuration

CPU:snapdragon 870
GPU/Driver:mesa turnip adreno driver v23.3.0-devel
RAM:16
OS:android

**Comment by ThepuncheXD7** [comment]
You can catch log file with yuzu app 
![Uploading Screenshot_20230820-184553_yuzu.png…]()

**Comment by MrRokiIsBored** [comment]
@ThepuncheXD7 when i press the pic it reloads the website and doesnt show the pic

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Without a log file and more information, we sadly cannot accept this issue.
