### ISSUE TITLE
GTA Vice City crashes with networking enabled

### ISSUE THREAD

**Issue by piplup55** [yuzu-emu/yuzu#11345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3826

### Description of Issue

it crashes when networking is enabled

Unhandled SIGSEGV at rip 0x00007f56804a8472

### Expected Behavior

it should boot into the main menu of the game
![image](https://github.com/yuzu-emu/yuzu/assets/100526773/0810d86e-51f1-4d2f-b856-fcd648dbf0d4)

### Reproduction Steps

load the game with any update

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12402712/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 9 7900X3D
GPU/Driver: AMD Raphael and AMD Radeon RX 6600 XT
RAM: 64gb
OS: Arch Linux

**Comment by liamwhite** [comment]
@comex

**Comment by piplup55** [comment]
seems to be fixed
![image](https://github.com/yuzu-emu/yuzu/assets/100526773/41359040-f1a7-4895-9366-f2ae00706793)
