### ISSUE TITLE
Title Screen for Fire Emblem Engage is now broken

### ISSUE THREAD

**Issue by MrKisuke** [yuzu-emu/yuzu#11348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2023-08-21 version

### Description of Issue

![0100a6301214e000_2023-08-21_16-47-53-206](https://github.com/yuzu-emu/yuzu/assets/140370462/b7617ae4-a0a8-47ac-b6a9-df21e753d93f)
This is the title screen I now see, there are no text the show, though inputs are possible and the invisible menu can be navigated.  However, doing so doesn't fix the problem and this broken looking visuals carries over into the actual gameplay as well.

### Expected Behavior

![maxresdefault](https://github.com/yuzu-emu/yuzu/assets/140370462/0c9e5ab1-c63a-424d-b1ee-e50957200714)
This is what the title screen should look like normally.

### Reproduction Steps

Simply opening the game.  This occurs whether I run mods or not.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12403516/yuzu_log.txt)

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by german77** [comment]
Works well on vulkan

**Comment by Squall-Leonhart** [comment]
417.77

Old ass driver!

**Comment by gidoly** [comment]
likely caused by outdated driver
