### ISSUE TITLE
Xenoblade Chronicles 3 crashes on Intel ARC

### ISSUE THREAD

**Issue by titoudoc** [yuzu-emu/yuzu#11341]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Mainline 1531 / EA 3824

### Description of Issue

Xenoblade Chronicles crash after the menu, when starting a new game it fails to load the first cutscene and crash.
Crash on mainline and EA on Intel ARC GPU. Don't crash on Nvidia GPU.

### Expected Behavior

No crash.

### Reproduction Steps

Clean the pipeline cache, relaunch the game and still crash after launching new game in the menu.
If no pipeline cache cleaning, game refuse du launch at all.

### Log File

[yuzu_log(EA_XC3).txt](https://github.com/yuzu-emu/yuzu/files/12397030/yuzu_log.EA_XC3.txt)
[yuzu_log(ML_XC3).txt](https://github.com/yuzu-emu/yuzu/files/12397031/yuzu_log.ML_XC3.txt)

### System Configuration

CPU: Intel i7-12700H
GPU/Driver: Intel Arc a770m / 31.0.101.4644 WHQL Certified (ID 785597, date 8/15/2023)
RAM: 32Go
OS: Windows 11 22H2

**Comment by baconwaifu** [comment]
Problem also reproduces on linux/mesa (debian version 23.2.1-1) with an A770 and multiple different cutscenes via event theater. Switching to llvmpipe complains about some geometry shader stuff but doesn't crash (unfortunately I forgot to save those logs, and I'm not sitting through a 5 minute slideshow to get them again), while on the arc it reliably crashes at the same point every time.

**Comment by liamwhite** [comment]
Crashes fixed in driver 31.0.101.5186 - there are a ton of vertex explosions, but that is a different issue that I think has already been filed.
