### ISSUE TITLE
Red Dead Redemption - returning to Main Menu causes crash/restart

### ISSUE THREAD

**Issue by ComoSgt** [yuzu-emu/yuzu#11347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1533

### Description of Issue

From what I've experienced on the Steam Deck, whenever you are in-game and select the option from the pause screen to return to the Main Menu, it will ask for confirmation, and then seemingly crash and restart the game.

### Expected Behavior

The game should return to the Main Menu of Red Dead Redemption.

### Reproduction Steps

1. Load into a save/game of Red Dead Redemption
2. Pause the game and select "Game"
3. Select "Main Menu"
4. Hit "Yes" and confirm
5. Game should now freeze and yuzu will restart

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12403333/yuzu_log.txt)

### System Configuration

CPU: Steam Deck APU 0405
GPU/Driver: Steam Deck APU 0405
RAM:16GB
OS: Steam OS 3.4.8

**Comment by AlvaroNovaes-BR** [comment]
I hardly disagree that, it's not even a bug or a problem with the game itself.
The original console versions on real hardware performed in the way of freezing the game before turning black and getting back to the disclaimer/warning screen.
Let me showcase how it looks on [RPCS3](https://cdn.discordapp.com/attachments/955157530529648721/1143975334170071151/2023-08-23_15-21-56.mp4).

**Comment by ComoSgt** [comment]
Oh wow, I would've figured it would at least show a loading screen! I appreciate you for uploading an example and showcasing it. My mistake, I'll close the issue, thanks again!
