### ISSUE TITLE
TOTK fails to load on Android

### ISSUE THREAD

**Issue by FireBurn** [yuzu-emu/yuzu#11351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Git Master

### Description of Issue

TOTK stops at "loading...." on Android compiled from source

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12411537/yuzu_log.txt)

I successfully got it working with 6a5db5679b61d3d73244e42682f1b34d401e7736 but when I started bisecting I got the following errors:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:runKtlintCheckOverMainSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > /home/fireburn/yuzu/src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/ViewUtils.kt (No such file or directory)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

```

Based on the log I'm thinking it might be one of the vfs or fssystem changes

### Expected Behavior

Game should load as normal

### Reproduction Steps

Load TOTK

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12411561/yuzu_log.txt)

### System Configuration

CPU: Snapdraggon 8 Gen 2
GPU/Driver: Adrino 740 Both system & Turnip
RAM: 16GB
OS: OxygenOS 13.1

**Comment by FireBurn** [comment]
Just spotted https://github.com/yuzu-emu/yuzu/commit/1bc832c9b154d6732eaba2b67d6119baec5f8a83 , I'll try bisecting again

**Comment by FireBurn** [comment]
86f6b6b7b2d930e8203114332b04a5c49a780b06 is the first bad commit
commit 86f6b6b7b2d930e8203114332b04a5c49a780b06
Author: Liam <byteslice@airmail.cc>
Date:   Thu Aug 10 21:34:43 2023 -0400

    vfs: expand support for NCA reading

**Comment by liamwhite** [comment]
disable your cheats, the game isn't booting because it crashed

**Comment by FireBurn** [comment]
Updated log file:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12413623/yuzu_log.txt)

**Comment by liamwhite** [comment]
Do you also have an exefs mod installed? I can observe from your log that the game accessed unmapped memory and crashed again, well after applying the update. The game does boot for me without issue on my device.

**Comment by FireBurn** [comment]
It booted before that commit, I don't think I have any mod's installed, but where would it be if I did?

**Comment by liamwhite** [comment]
Android/data/org.yuzu.yuzu_emu/files/load/0100F2C0115B6000

**Comment by FireBurn** [comment]
Nope that directory is now empty

**Comment by liamwhite** [comment]
I reproduced the issue on a different device and will investigate

**Comment by liamwhite** [comment]
The patched romfs binary is ending up as a different size than the one produced on desktop
