### ISSUE TITLE
[Android] please fix touch haptics

### ISSUE THREAD

**Issue by Finblade** [yuzu-emu/yuzu#11363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Although i enabled touch haptics, it does not work at all.  I have tested both mainline and EA and the result was same. Please fix it. Also it would be good if there was grid in edit overlay.

### Why would this feature be useful?

If touch haptics work properly, it will enhance user's gaming experience.

**Comment by t895** [comment]
What is your device and what android version is it using?

**Comment by Finblade** [comment]
> What is your device and what android version is it using?

My device is Zflip4 and i am using android 13

**Comment by Finblade** [comment]
> Do you have Haptics enabled in system settings? I'm not sure where this would be in OneUI but it's listed as "Vibration & Haptics" for Pixels under accessibility.

I tried to search haptic menu in settings but it does not exist. Instead all vibration is enabled. When i type keyboard, haptics work

**Comment by t895** [comment]
By all means this should work if you have haptics enabled in the touch overlay settings (In Game Menu>Input Overlay>Touch Haptics) and system settings. I'll have to try and repro this on my samsung device when I get home.

**Comment by goldenx86** [comment]
Works fine for me on a base Samsung S23.

**Comment by Finblade** [comment]
> By all means this should work if you have haptics enabled in the touch overlay settings (In Game Menu>Input Overlay>Touch Haptics) and system settings. I'll have to try and repro this on my samsung device when I get home.

The thing was solved. The name of haptics in One Ui is "touch interactions". Actually I didn't know this. In default setting, this is disabled.

After you mentioned system vibration settings, i enabled it and touch haptics worked properly. I never used touch interactions because I didn't even know this thing exist and it was disabled in default setting.

When i used Skyline in past days, touch haptics worked although i didn't change anything in my system settings. This made me to think that haptics will also work in yuzu by nature if i enable touch haptics. I didn't know that I have to enable touch interactions thing in system settings for using touch haptics in yuzu. I apologize. It's my mistake.

Thank you for helping me although you might be busy.

**Comment by t895** [comment]
No worries
