### ISSUE TITLE
Red Dead Redemption performance loss and lens flare bug introduced in 3830 update

### ISSUE THREAD

**Issue by Intoxicus** [yuzu-emu/yuzu#11364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3830

### Description of Issue

After the 3830 update RDR has significant performance loss on both Windows 11 and Steam Deck. 

Also there is a bug with lens flares that creates a flickering orange circle when lens flares should be rendered(I'm calling this "sunspots")

### Expected Behavior

normal performance and proper lens flare rendering

### Reproduction Steps

Play Red Dead Redemption on EA 3830 on either Steam Deck or Windows 11 using Vulkan

### Log File

It's on my Steam Deck and I'm typing on Windows. I did upload it to Discord.

### System Configuration

CPU: Steam Deck / Ryzen 3800X
GPU/Driver: Steam Deck / RTX 3080 w/ latest driver
RAM: Steam Deck / 32GB @ 3200
OS: Steam OS 3.5 / Windows 11

**Comment by FearlessTobi** [comment]
please also upload your logs here.

**Comment by boludoz** [comment]
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/0b9a6d61-8e80-4dcb-aa5f-6f08d8f97f20)
CPU Intensive

**Comment by AAAAAXfda** [comment]
@Intoxicus Hello, sir. Please upload the log. For assistance with your issue, please accurately describe the problem and post a log file. The following guide shows how to __get the log file__: <https://yuzu-emu.org/help/reference/log-files/>

**Comment by AAAAAXfda** [comment]
Upload the fucking log????

**Comment by AAAAAXfda** [comment]
@Intoxicus @boludoz Fixed in EA 3831. Thanks for reporting this.
