### ISSUE TITLE
Yuzu crashing when loading games.

### ISSUE THREAD

**Issue by Jonav9** [yuzu-emu/yuzu#11368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1535

### Description of Issue

Everything was working fine till today. When attempting to open a game, any game, it just closes. Already deleted shaders cache, but the problem persists. 

### Expected Behavior

Work normally again.

### Reproduction Steps

Not sure. 

### Log File

[   0.160945] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.160983] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.209248] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.248229] Frontend <Info> yuzu\main.cpp:GMainWindow:365: yuzu Version: yuzu 1535
[   0.248253] Frontend <Info> yuzu\main.cpp:LogRuntimes:244: MSVC Compiler: 1936 Runtime: 14.34.31938.0
[   0.248255] Frontend <Info> yuzu\main.cpp:LogRuntimes:253: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.248257] Frontend <Info> yuzu\main.cpp:GMainWindow:381: Host CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz | AVX512 | FMA
[   0.248261] Frontend <Info> yuzu\main.cpp:GMainWindow:383: Host CPU Cores: 4
[   0.248261] Frontend <Info> yuzu\main.cpp:GMainWindow:386: Host CPU Threads: 8
[   0.248427] Frontend <Info> yuzu\main.cpp:GMainWindow:387: Host OS: Windows 11 Version 22H2 (Build 22621.2134)
[   0.248441] Frontend <Info> yuzu\main.cpp:GMainWindow:389: Host RAM: 15.68 GiB
[   0.248442] Frontend <Info> yuzu\main.cpp:GMainWindow:390: Host Swap: 23.00 GiB
[   0.248464] Frontend <Info> yuzu\main.cpp:GMainWindow:395: Host Timer Resolution: 0.5000 ms
[   0.579131] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[   0.610091] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[   0.619600] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[   0.635552] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.3.0) applied successfully
[   0.637974] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.3.0) applied successfully
[   0.644542] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.3.0) applied successfully
[   0.647068] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.3.0) applied successfully
[   0.682508] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[   0.682508] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully

### System Configuration

CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz 
GPU/Driver: intel iris xe most current driver 30.0.101.2079
RAM: 16GB
OS: windows 11

**Comment by ThepuncheXD7** [comment]
The same thing happened to me

**Comment by Jonav9** [comment]
> The same thing happened to me

In my case it was the GPU driver. It actually rolled back in the last "upgrade" So I manually installed the last version.
