### ISSUE TITLE
Zelda TOTK: Freeze of some seconds when opening menu, while ASTC recompression is enabled

### ISSUE THREAD

**Issue by yughias** [yuzu-emu/yuzu#11361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1534

### Description of Issue

Since I have only 4 GB of VRAM, I decided to use ASTC Recompression Method. When I use it (BC3/BC1) the game runs ok and does not crash but I'm experiencing small freeze of some seconds every time I do any of these actions:
- Switching weapon, shield, bow
- Switching power
- Open menu and map
- Loading Screen

These freezes appear only while using Vulkan API, they don't occur with OpenGL.

### Expected Behavior

You can experience freeze when switching weapon, changing power, open map and menu.
https://github.com/yuzu-emu/yuzu/assets/75031586/8ae46d29-e0d6-439a-a471-98003ee912e2

### Reproduction Steps

Zelda TOTK Version is 1.1.2
![Immagine 2023-08-23 142546](https://github.com/yuzu-emu/yuzu/assets/75031586/ea8dcc5a-1b7d-462c-a8b2-19ae1c073213)
![Immagine 2023-08-23 142613](https://github.com/yuzu-emu/yuzu/assets/75031586/e2d96501-4ed3-43e1-a36e-6cad0446b71f)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12419187/yuzu_log.txt)

### System Configuration

CPU: i7 11800H
GPU/Driver: RTX 3050 Ti
RAM: 16 GB DDR4
OS: Windows 10

**Comment by FearlessTobi** [comment]
This is very likely the recompression running that freezes your game.
It is to be expected when using this setting.

**Comment by Squall-Leonhart** [comment]
Not exactly, see https://github.com/yuzu-emu/yuzu/pull/10529
