### ISSUE TITLE
Translation not available in Settings

### ISSUE THREAD

**Issue by xujibbs** [yuzu-emu/yuzu#11386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1538

### Description of Issue

Settings can not show translated strings

### Expected Behavior

make the settings translatable

### Reproduction Steps

make the settings translatable

### Log File

N/A

### System Configuration

CPU: 9900K
GPU/Driver: 2080Ti
RAM: Kinstom 16
OS: Win 10 22H2

**Comment by FearlessTobi** [comment]
After a recent settings rework, these strings need to be retranslated.
