### ISSUE TITLE
Android: Buttons missing from ingame overlay

### ISSUE THREAD

**Issue by ReyZen45** [yuzu-emu/yuzu#11391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Acces and Mainline Update Latest Android 

### Description of Issue

Layout Bug Yuzu android Button layout, some button missing
![Screenshot_20230826_161824](https://github.com/yuzu-emu/yuzu/assets/143301857/4f69482b-be33-4ef2-ad20-bf3ec38e8278)

### Expected Behavior

https://github.com/yuzu-emu/yuzu/assets/143301857/9c1ba7e2-ce06-4712-ac6a-812f628155d8

### Reproduction Steps

Open yuzu android and play one games, and layout will bugged.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12447087/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 8 Gen 2
GPU/Driver: 676.32
RAM: 16GB
OS: Android 13

**Comment by german77** [comment]
Try resetting the button position to defaults.

**Comment by sharpy66** [comment]
> Try resetting the button position to defaults.

Already tried, along with restarting device and reinstalling the device. Troubleshooting has already been done. This appears to be a device-specific issue.

**Comment by ReyZen45** [comment]
> Try resetting the button position to defaults.

Still same, already do that.

**Comment by ReyZen45** [comment]
> 

Yes, it happen with specific device. Maybe device with Resolution 2k or up

**Comment by t895** [comment]
Are you still having this issue? If so could I point you towards a build to try?
