### ISSUE TITLE
Text input not visible on screen - probably behind the game

### ISSUE THREAD

**Issue by Ariane-B** [yuzu-emu/yuzu#11397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1539

### Description of Issue

In The Legend of Zelda: Tears of the Kingdom, when you bring a new horse to a stable, you're given a text input to name it. That text input isn't showing up for me. At first, it seems like the game has completely frozen.

But if you do Win+Shift+Left, the text input overlay will change screens and show up on another monitor. Then you can safely input text with your keyboard, then take up your controller again and press +, and everything's fine.

Considering that Win+Shift+Left brought it to _another_ screen, I think it's safe to assume it was on the right monitor, just hidden behind the game.

### Expected Behavior

See the text input interface right away, on the screen I'm using to play.

### Reproduction Steps

1. Bring wild horse to stable
2. Register the horse

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12448323/yuzu_log.txt)

### System Configuration

CPU: AMD 7950X
GPU/Driver: Nvidia RTX 3070, driver 536.23 (yeah out of date; I'll update it soon and tell you if this changes anything)
RAM: 32 GB DDR5-5200 CL40
OS: Windows 11 22H2

Monitors:

- 1440p monitor (set as main monitor), plugged in via DisplayPort.
- 1440p DisplayPort EDID emulator, set to duplicate the main monitor, so that turning the monitor off doesn't shuffle windows around to hell and back.
- 4K TV plugged in via HDMI 2.1, which is where Yuzu lives

Yuzu setup:

- I've got [TOTK Optimizer](https://github.com/MaxLastBreath/TOTK-mods) installed, set up like this:

![image](https://github.com/yuzu-emu/yuzu/assets/6244273/9edef35f-d337-4799-bb74-8c1bd0fbedc5)

- I play in exclusive fullscreen, with resolution set at 1080p, anti-aliasing set to SMAA and window adapting filter AMD FSR.

**Comment by FearlessTobi** [comment]
Due to a problem with QT, this is to be expected to happen when you are using exclusive fullscreen.
As far as I know, we can do nothing about this on our side.

**Comment by Squall-Leonhart** [comment]
why are these text entries implemented as sub windows at all, This should be re-opened as a request for replacing them with an in-renderer overlay just as how the switch itself does it.
