### ISSUE TITLE
Android: Switch xbox/switch button layout or buttons remap for external controllers on android platform.

### ISSUE THREAD

**Issue by beginor** [yuzu-emu/yuzu#11411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Support for external controllers on android platform works well, but we can't config external controller's button in yuzu's settings now.

The `ABXY` buttons has two popular layouts, known as `xbox` and `switch` layout,  the positions of `AB` and `XY` are opposite

![image](https://github.com/yuzu-emu/yuzu/assets/159065/6bbe3ab5-05f0-4b8a-8028-361c59086af5)

![image](https://github.com/yuzu-emu/yuzu/assets/159065/c5962e04-a230-44b1-a6e3-8fec838db9d7)

It would be better if users can select `ABXY` buttons layout in yuzu or remap the button as they like.

### Why would this feature be useful?

If users can select  `ABXY` buttons layout or remap button layout, users can play games with yuzu without caring `ABXY` button position.

**Comment by t895** [comment]
Existing issue already open at #11124
