### ISSUE TITLE
Textures flickering on Red Dead Redemption

### ISSUE THREAD

**Issue by AndrewS100000** [yuzu-emu/yuzu#11414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3843

### Description of Issue

The textures keep glitching (sorry about the quality of the video)

https://github.com/yuzu-emu/yuzu/assets/139455645/f7af9750-5171-41c7-beda-d117e17613c6

### Expected Behavior

The textures are supposed to work without any glitches

### Reproduction Steps

Play RDR with Vulkan and GPU accuracy set to Normal. You'll see that the textures flicker.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12464292/yuzu_log.txt)

### System Configuration

CPU: i5-2500
GPU/Driver: NVIDIA GeForce GT 710 / 474.44 (latest)
RAM: 12GB
OS: Windows 11 22H2

**Comment by Squall-Leonhart** [comment]
High is the default configuration of Yuzu and very few applications are effectively supported at Normal, so no its not a bug, its just a limitation of Normal at the present time and may or may never be resolved.
