### ISSUE TITLE
Bayonetta 3 and Super Mario 3D All-Stars, cannot start when format is XCI including Game+Updates in single file

### ISSUE THREAD

**Issue by rubenjavier** [yuzu-emu/yuzu#11410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1540 / Early Access 3841

### Description of Issue

Both games Bayonetta 3 and Super Mario 3D All-Stars, cannot start when the games are in .XCI format that include the game+updates on the same file and this updates are actives on the game properties.

If the updates are set to inactives on the game properties, the .XCI games do start

This has been tested with manually created .XCI from the NSP files and downloaded "premade" .XCI for both games

This .XCI work perfectly on Ryujinx with the embedded updates enabled

If the NSP are extracted from the .XCI and the update is installed separately, the games do start correctly, also another dozen+ games in .XCI including embedded updates and dlc, work correctly, so its probably something pertinent to this two games.

The log shows yuzu trying to read unmapped memory access

### Expected Behavior

Both games Bayonetta 3 and Super Mario 3D All-Stars when in .XCI format including game+updates in a single file should start

### Reproduction Steps

Get a Bayonetta 3 or Super Mario 3D All-Stars in .XCI format that includes on the same file the game+update, check in the game properties that the update is active to beign applied, try to start the game, crash or infinite load screen caused by unmapped memory access

### Log File

[ 381.474751] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[ 381.641271] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:910: Device doesn't support extension VK_NV_geometry_shader_passthrough
[ 381.641275] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:910: Device doesn't support extension VK_NV_viewport_array2
[ 381.641275] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:910: Device doesn't support extension VK_NV_viewport_swizzle
[ 381.641314] Render.Vulkan <Warning> video_core\vulkan_common\vulkan_device.cpp:Device:567: AMD drivers have broken extendedDynamicState3ColorBlendEquation
[ 381.772327] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:173: Driver: AMD proprietary driver 2.0.270
[ 381.772330] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:174: Device: AMD Radeon RX 7900 XTX
[ 381.772330] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:175: Vulkan: 1.3.250
[ 381.772333] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:176: Available VRAM: 8.00 GiB
[ 382.003753] Service.Audio <Error> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:87: Auto-selecting the cubeb backend
[ 382.122818] Service.Audio <Error> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:87: Auto-selecting the cubeb backend
[ 382.138160] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:131: Patching ExeFS for title_id=01004A4010FEA000
[ 382.138567] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:146:     ExeFS: Update (v0.0.0) applied successfully
[ 382.139205] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:177:     ExeFS: LayeredExeFS patches applied successfully
[ 382.262217] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=567CDD4C5251494C5CD70822E3CCC740C190C2B2
[ 382.346122] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=4FB8D54D22BCC2349852FCACF974B672A7C0B4A1
[ 382.393184] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=357EFC198E728CB5D55265AFF304F03CFC9CC0E3
[ 382.447571] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[ 382.451741] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[ 382.451885] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:LoadVulkanPipelineCache:843: Loaded Vulkan driver pipeline cache: 
[ 382.452353] Frontend <Info> yuzu\main.cpp:BootGame:1972: Booting game: 01004A4010FEA000 | Bayonetta 3 (64-bit) | 1.2.0
[ 382.452462] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:LoadDiskResources:526: Total Pipeline Count: 0
[ 382.452669] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:SerializeVulkanPipelineCache:786: Vulkan driver pipelines cached at: C:\Users\Ruben Javier\Desktop\yuzu_ea\user\shader\01004a4010fea001\vulkan_pipelines.bin
[ 382.706345] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 382.714046] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 382.721343] Service.AM <Warning> core\hle\service\am\am.cpp:SetRequestExitToLibraryAppletAtExecuteNextProgramEnabled:872: (STUBBED) called
[ 382.723086] Service.AM <Warning> core\hle\service\am\am.cpp:GetGpuErrorDetectedSystemEvent:1880: (STUBBED) called
[ 382.729001] Service.AM <Warning> core\hle\service\am\am.cpp:AcquireForegroundRights:94: (STUBBED) called
[ 382.729435] Service.AM <Warning> core\hle\service\am\am.cpp:SetFocusHandlingMode:441: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[ 382.729875] Service.AM <Warning> core\hle\service\am\am.cpp:SetOutOfFocusSuspendingEnabled:460: (STUBBED) called enabled=false
[ 382.731731] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 382.734544] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 382.735665] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 382.738039] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 382.738108] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 383.478830] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 383.481937] Service.AM <Warning> core\hle\service\am\am.cpp:SetFocusHandlingMode:441: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[ 383.482003] Service.AM <Warning> core\hle\service\am\am.cpp:SetOutOfFocusSuspendingEnabled:460: (STUBBED) called enabled=true
[ 383.482110] Service.AM <Warning> core\hle\service\am\am.cpp:SetRestartMessageEnabled:448: (STUBBED) called
[ 383.482382] Service.AM <Warning> core\hle\service\am\am.cpp:SetOperationModeChangedNotification:412: (STUBBED) called flag=true
[ 383.482584] Service.AM <Warning> core\hle\service\am\am.cpp:SetPerformanceModeChangedNotification:422: (STUBBED) called flag=true
[ 383.501444] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 383.502876] Service.HID <Info> core\hid\emulated_controller.cpp:SetPollingMode:1239: Set polling mode 0, device_index=3
[ 383.512043] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 383.515804] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:427: Patching RomFS for title_id=01004A4010FEA001, type=01
[ 383.596994] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:Initialize:152: (STUBBED) called
[ 383.599619] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:SetAruid:192: (STUBBED) called, pid=0x87
[ 383.600409] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:SetGraphicsFirmwareMemoryMarginEnabled:200: (STUBBED) called
[ 383.603845] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetManagerDisplayService:460: (STUBBED) called
[ 383.604275] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetSystemDisplayService:452: (STUBBED) called
[ 383.604697] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetRelayService:444: (STUBBED) called
[ 383.613007] Service.VI <Warning> core\hle\service\vi\vi.cpp:OpenDisplay:476: (STUBBED) called
[ 383.614464] Service.AM <Warning> core\hle\service\am\am.cpp:CreateManagedDisplaySeparableLayer:487: (STUBBED) called
[ 383.618636] Service.VI <Warning> core\hle\service\vi\vi.cpp:AdjustRefcount:110: (STUBBED) called id=1, addval=00000001, type=00000000
[ 383.619111] Service.VI <Warning> core\hle\service\vi\vi.cpp:AdjustRefcount:110: (STUBBED) called id=1, addval=00000001, type=00000001
[ 383.621962] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetNativeHandle:121: (STUBBED) called id=1, unknown=0000000F
[ 383.644420] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 383.690101] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:251: (STUBBED) called
[ 383.690103] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:259: Avoiding passing null pointer to memcpy
[ 383.690483] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:251: (STUBBED) called
[ 383.690485] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:259: Avoiding passing null pointer to memcpy
[ 383.694276] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:AllocGPFIFOEx2:185: (STUBBED) called, num_entries=800, flags=1, unk0=0, unk1=0, unk2=0, unk3=0
[ 383.694673] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:AllocateObjectContext:204: (STUBBED) called, class_num=B197, flags=0
[ 383.695154] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:SetErrorNotifier:165: (STUBBED) called, offset=0, size=1000, mem=C
[ 383.695415] Service.NVDRV <Info> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:ChannelSetTimeout:344: called, timeout=0x266
[ 383.696501] Service.NVDRV <Info> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:ChannelSetTimeslice:352: called, timeslice=0x400
[ 383.714067] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 383.764708] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[ 383.838161] Core.ARM <Critical> core\arm\dynarmic\arm_dynarmic_64.cpp:CheckMemoryAccess:210: Stopping execution due to unmapped memory access at 0x8
[ 383.838164] HW.Memory <Error> core\memory.cpp:operator ():695: Unmapped Read64 @ 0x0000000000000008
[ 383.838166] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:137: Backtrace, sp=0000001086103F30, pc=0000000080FFA21C
[ 383.838167] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:139: Module Name         Address             Original Address    Offset              Symbol
[ 383.838172] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:140: 
[ 383.877061] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007100FF621C    0000000080FFA21C    0000000000FF621C    
[ 383.877064] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: main                0000007100FF6124    0000000080FFA124    0000000000FF6124    
[ 383.877065] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 00000071002DBBD4    0000000085371BD4    00000000002DBBD4    nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
[ 383.877065] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: rtld                00000071000000D4    00000000800000D4    00000000000000D4    

### System Configuration

CPU: Ryzen 5900X
GPU/Driver: Radeon RX 7900XTX 23.7.2
RAM: 64GB
OS: Windows 10 22H2 19045.3324

**Comment by SleepingSnakezzz** [comment]
We do not support piracy here.
