### ISSUE TITLE
Red Dead Redemption crashes EA 3851

### ISSUE THREAD

**Issue by boludoz** [yuzu-emu/yuzu#11424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3851

### Description of Issue

The game has been crashing more frequently since the latest update Early Access 3851.

### Expected Behavior

The game should work normally, as it does in non-Early Access versions.

### Reproduction Steps
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/fcb97cba-65bb-405d-80ac-6e03d41fefe3)
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/a0f37b04-9a1c-4d0f-b751-7dad3ff97c43)

Turn on the game

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12488563/yuzu_log.txt.old.txt)

another log, same crash:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12488667/yuzu_log.txt)

### System Configuration

CPU: i5-8600k
GPU/Driver: RTX 3080
RAM: 16 DDR4 3600 MHz
OS: Windows 11 10.0.22621.2134

**Comment by boludoz** [comment]
It also happens to me on my laptop with an i3 11gen and integrated graphics, the same does not happen when I use normal Yuzu.

**Comment by boludoz** [comment]
I have not suffered crashes with my i3 8 gen and RTX 1070 setup

**Comment by boludoz** [comment]
I've been testing the game on the non Early Access emulator and the game works, with a little stuttering more than normal but it works.

**Comment by german77** [comment]
Piracy is not allowed.
