### ISSUE TITLE
Bayonetta 3 on early access/mainline 1543 builds crashing (EA 3840-3851/MAINLINE 1543/Vulkan/RDNA3)

### ISSUE THREAD

**Issue by flopware** [yuzu-emu/yuzu#11422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3840 (and newer)
Mainline 1543

### Description of Issue

Bayonetta 3 is crashing following early access version 3840 and onwards.
RoT, Prologue playable up until second playable verse (following CMW cutscene).

All other chapters crash.

Relaunching Bayonetta 3 with disk shader cache enabled following initial crash/disk shader cache building leads to game crashing on launch. Deleting disk shader cache files allows game to launch up until situation described in first paragraph.

### Expected Behavior

The game does not crash.

### Reproduction Steps

Play Bayonetta 3 on EA 3840+ with Vulkan/RDNA3 card.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12488737/yuzu_log.txt)

### System Configuration

CPU: Intel Core i7-12700k
GPU/Driver: RX 7900 XTX / Radeon 23.8.1
RAM: 64GB 2x32 DDR5-5600
OS: Windows 11 Pro 22621.2134

**Comment by flopware** [comment]
Output of vkdiag:
`[+] VkDiag version: 1.2.2
[i] CPU: 12th Gen Intel(R) Core(TM) i7-12700K
[+] OS: Microsoft Windows 11 Pro
[+] Version: 10.0.22621 (Windows 11 22H2)
[+] System Vulkan loader version: 1.3.243.0

Found 2 active GPUs:
[-] NVIDIA GeForce RTX 2080 Ti
[v] AMD Radeon RX 7900 XTX
    [+] Driver version: 31.0.21029.1006 (8-14-2023)
    [v] Proper Vulkan driver registration
[v] Intel(R) UHD Graphics 770
    [+] Driver version: 31.0.101.3959 (12-3-2022)
    [!] Please update your video driver
    [v] Proper Vulkan driver registration

User GPU Preferences:
[+] Running with High performance GPU profile

Vulkan registration information:
[+] No explicit driver registration entries
[+] Implicit layers registration (HKEY_LOCAL_MACHINE, 64-bit):
    [+] Open Broadcaster Software hook, v1.8.1.0, API v1.3.216 (obs-vulkan64.json)
    [+] Steam Overlay, API v1.3.207 (SteamOverlayVulkanLayer64.json)
    [+] Steam Pipeline Caching, API v1.3.207 (SteamFossilizeVulkanLayer64.json)
[+] Implicit layers registration (HKEY_LOCAL_MACHINE, 32-bit):
    [+] Open Broadcaster Software hook, v1.8.1.0, API v1.3.216 (obs-vulkan32.json)
    [+] Steam Overlay, API v1.3.207 (SteamOverlayVulkanLayer.json)
    [+] Steam Pipeline Caching, API v1.3.207 (SteamFossilizeVulkanLayer.json)
Everything seems to be fine.

Remember to screenshot or copy this screen content for support.

Press any key to exit the tool...`

**Comment by Pergmen** [comment]
I was able to recreate these exact symptoms

Tested on EA 3851 with an RDNA2 card using RADV from Mesa 23.3.0-devel
Identical behavior on game version 1.0 and on 1.2

CPU: Ryzen 7 5800X
GPU: RX 6800
RAM: 2x16 DDR4-3200
OS: Manjaro Linux, Kernel 6.5.0-1
