### ISSUE TITLE
Service.Audio <Error> audio_core/renderer/voice/voice_context.cpp:GetInfo:48: Invalid voice info index 00BC

### ISSUE THREAD

**Issue by xeon826** [yuzu-emu/yuzu#11421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1498 flatpak

### Description of Issue

Playing TOTK 1.2.0, attacking tree's with spear, lightning strikes, about a second later, game crashes, citing above error. I do see there's a [similar issue](https://github.com/yuzu-emu/yuzu/issues/10673)  but I thought this might be useful considering I'm using a different build and game. I also want to note, my RAM was at a steady 80% capacity at the time of the crash so it might be not a size issue.

### Expected Behavior

Game should not crash at this point, citing audio error.

### Reproduction Steps

Might be flatpak specific but I doubt it so reproduction steps would be to install yuzu 1498, load TOTK 1.2.0. Not sure if the exact context I was in, in the game was necessary but that's when it happened. I should note since the error mentioned audio, all of my audio settings are set to "auto" other than Sound Output Mode which is "Stereo"

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12481561/yuzu_log.txt)

### System Configuration

System:
  Host: radeon Kernel: 6.2.0-26-generic x86_64 bits: 64 compiler: N/A
    Desktop: awesome 4.3 Distro: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
Machine:
  Type: Desktop Mobo: ASUSTeK model: TUF GAMING X570-PLUS (WI-FI) v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 4602
    date: 02/23/2023
CPU:
  Info: 8-core model: AMD Ryzen 7 3700X bits: 64 type: MT MCP arch: Zen 2
    rev: 0 cache: L1: 512 KiB L2: 4 MiB L3: 32 MiB
  Speed (MHz): avg: 2345 high: 3678 min/max: 2200/4426 boost: enabled
    cores: 1: 2200 2: 3600 3: 2049 4: 2075 5: 2077 6: 2200 7: 2200 8: 2200
    9: 2200 10: 2200 11: 2053 12: 2200 13: 2200 14: 3678 15: 2200 16: 2200
    bogomips: 114984
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    driver: amdgpu v: kernel bus-ID: 0a:00.0
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu resolution:
    1: 1920x1080~60Hz 2: 1920x1080~60Hz 3: 1920x1080~60Hz
  OpenGL: renderer: AMD Radeon RX 5700 XT (navi10 LLVM 15.0.7 DRM 3.49
  6.2.0-26-generic)
    v: 4.6 Mesa 23.3~git2308260600.5ce6e0~oibaf~j (git-5ce6e09 2023-08-26
    jammy-oibaf-ppa)
    direct render: Yes

OS: Ubuntu 22.04 jammy

**Comment by liamwhite** [comment]
the current version of yuzu is 1542, this was already fixed #11408
