### ISSUE TITLE
[Bug] Downscale glitches

### ISSUE THREAD

**Issue by boludoz** [yuzu-emu/yuzu#11431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

YU1538

### Description of Issue

Graphic glitches in Red Dead Redemption skybox clouds and texture disappearance in resolutions 0.75 and 0.50 on Intel graphics only. It is a pity since it achieves a good performance.

![image](https://github.com/yuzu-emu/yuzu/assets/11653030/6d716d69-d4e6-4bed-8e47-9de55966d8f4)

### Expected Behavior

It should show the clouds correctly and without glitches.

### Reproduction Steps

[01007820196A6000.zip](https://github.com/yuzu-emu/yuzu/files/12503238/01007820196A6000.zip)
Cloudy game play

### Log File

Not for the moment

### System Configuration

Intel i3 11gen integrated graphics

**Comment by Squall-Leonhart** [comment]
Log is a REQUIREMENT of opening a bug, it gives responders a look into the environment that Yuzu is being run on,

**Comment by boludoz** [comment]
100% understandable, I'm going to try to log the shaders.

**Comment by german77** [comment]
No log provided. Please reopen when log file is uploaded.

**Comment by boludoz** [comment]
> No log provided. Please reopen when log file is uploaded.

I don't understand why it says that my log is pirated, what is the problem?

**Comment by german77** [comment]
This issue has no log https://yuzu-emu.org/help/reference/log-files/

Yuzu is open source but we can only fix issues on official builds. There's no proof of piracy here. Previous issue did have traces of games obtained from piracy websites. Piracy is completely forbidden here.

To obtain your games downloading please dump them using this guide https://yuzu-emu.org/help/quickstart/

**Comment by boludoz** [comment]
> This issue has no log https://yuzu-emu.org/help/reference/log-files/
> 
> Yuzu is open source but we can only fix issues on official builds. There's no proof of piracy here. Previous issue did have traces of games obtained from piracy websites. Piracy is completely forbidden here.
> 
> To obtain your games legally, please dump them using this guide https://yuzu-emu.org/help/quickstart/

I mean #11424
