### ISSUE TITLE
Please support OpenGL-only systems, so systems without Vulkan can be used

### ISSUE THREAD

**Issue by davidhedlund** [yuzu-emu/yuzu#11445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1546

### Description of Issue

[Trisquel](https://trisquel.info/) GNU/Linux supports OpenGL, but not Vulkan.

#### Cannot open games with Vulkan set as graphics API
* At the bottom left of the window, switch the graphics API from "OpenGL" to "Vulkan"
![Capture d’écran_2023-05-23_18-30-13](https://user-images.githubusercontent.com/118930644/240360036-e0f3b79f-a0ad-4643-a20a-7c31ea1aa4a1.png)
* Open a game, then I get this error message: 
![image](https://github.com/yuzu-emu/yuzu/assets/6416073/9670329f-d93b-485c-97da-7b1201f4a67a)
* This will generate an identical ~/.local/share/yuzu/log/yuzu_log.txt. The relevant lines are:
```
[   0.319698] Render.Vulkan <Error> video_core/vulkan_common/vulkan_instance.cpp:AreExtensionsSupported:32: Required instance extension VK_KHR_xlib_surface is not available
[   0.319858] Frontend <Error> yuzu/vk_device_info.cpp:PopulateRecords:64: Failed to enumerate devices with error: VK_ERROR_EXTENSION_NOT_PRESENT
```

### Cannot configure Controllers (requires vulkan)
Earlier, it was not possible to open the Configure window with Vulkan set as in Trisquel, but this has been fixed:
* https://github.com/yuzu-emu/yuzu/issues/10329

However, it is still not possible to save the modified configuration (I'm sure that I configured my controller a few weeks ago in Trisquel):
* https://github.com/yuzu-emu/yuzu/issues/11442

The controller issue generates an identical ~/.local/share/yuzu/log/yuzu_log.txt that is generated when Vulkan failed to load games (see previous section). Again, the relevant lines are:
```
[   0.319698] Render.Vulkan <Error> video_core/vulkan_common/vulkan_instance.cpp:AreExtensionsSupported:32: Required instance extension VK_KHR_xlib_surface is not available
[   0.319858] Frontend <Error> yuzu/vk_device_info.cpp:PopulateRecords:64: Failed to enumerate devices with error: VK_ERROR_EXTENSION_NOT_PRESENT
```

#### Non-free software issue?
Trisquel is [approved by the Free Software Foundation](https://www.gnu.org/distros/free-distros.en.html):

> "These distros are ready-to-use full systems whose developers have made a commitment to follow the [Free System Distribution Guidelines](https://www.gnu.org/distros/free-system-distribution-guidelines.html). This means they will include, and propose, exclusively free software. They will reject nonfree applications, nonfree programming platforms, nonfree drivers, nonfree firmware “blobs,” nonfree games, and any other nonfree software, as well as nonfree manuals or documentation."

I don't know anything about vulkan. Is vulkan or any required vulkan dependencies in yuzu (libraries, etc) (partially) non-free?

### Expected Behavior

Yuzu should be fully compatible with OpenGL-only supported systems.

### Reproduction Steps

* Install [Trisquel](https://trisquel.info/) GNU/Linux
* Install yuzu appimage
* Open Yuzu
* The attached log file will be generated in ~/.local/share/yuzu/log

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12514825/yuzu_log.txt)

### System Configuration

CPU: Intel i7 7700K kaby lake
GPU/Driver: HD Graphics 630
RAM: 32 GB
OS: Trisquel 11

**Comment by liamwhite** [comment]
@lat9nq

**Comment by mr-sihc** [comment]
"GNU/Linux" :nerd_face:

This seems like a bug not like an opengl not supported type crash
so the title can be shortened

**Comment by mr-sihc** [comment]
> It may boil down to non-free software dependencies, since Trisquel does not come with nonfree software or allow nonfree software in its package repositories. I described this in the top post.

thats not GNU specific
but mesa is free software and has vulkan drivers, does it not allow that? Or is your PC not mesa compatible?

anyway, good luck with your Trisquel yuzu

**Comment by davidhedlund** [comment]
> > It may boil down to non-free software dependencies, since Trisquel does not come with nonfree software or allow nonfree software in its package repositories. I described this in the top post.
> 
> thats not GNU specific but mesa is free software and has vulkan drivers, does it not allow that? Or is your PC not mesa compatible?
> 
> anyway, good luck with your Trisquel yuzu

* At the bottom left of the window, switch the graphics API from "OpenGL" to "Vulkan"
![Capture d’écran_2023-05-23_18-30-13](https://user-images.githubusercontent.com/118930644/240360036-e0f3b79f-a0ad-4643-a20a-7c31ea1aa4a1.png)
* Open a game, then I get this error message: 
![image](https://github.com/yuzu-emu/yuzu/assets/6416073/9670329f-d93b-485c-97da-7b1201f4a67a)
* This will generate an identical ~/.local/share/yuzu/log/yuzu_log.txt of the log that I uploaded to the top post. The relevant lines are:
```
[   0.319698] Render.Vulkan <Error> video_core/vulkan_common/vulkan_instance.cpp:AreExtensionsSupported:32: Required instance extension VK_KHR_xlib_surface is not available
[   0.319858] Frontend <Error> yuzu/vk_device_info.cpp:PopulateRecords:64: Failed to enumerate devices with error: VK_ERROR_EXTENSION_NOT_PRESENT
```

**Comment by lat9nq** [comment]
Please do not change the scope or topic of an Issue after creating it, especially after PRs have been created to resolve the initial issue.

**Comment by davidhedlund** [comment]
> Please do not change the scope or topic of an Issue after creating it, especially after PRs have been created to resolve the initial issue.

I respect your concern, but as far as I know the scope is not changed. The log is identical for both issues with dedicated sections in the top post.

**Comment by mr-sihc** [comment]
@davidhedlund what i mean  with the question was, that you'd know why your linux doesn't to vulkan (so i could maybe help), i was interested in why, i already know it cant

@lat9nq yeah, i just wanted to know why his system didn't support vulkan maybe i could help him, he already said it doesn't so idk why he posted the error (i also wanted to keep it short and simple)

but yes, this seems to be a resolved issue when the pr is merged @davidhedlund you can try it and see if it fixes it

**Comment by davidhedlund** [comment]
@liamwhite @lat9nq I can confirm that it is working in Yuzu 1555 that I just upgraded too. Good work guys!

Long live Yuzu
