### ISSUE TITLE
vulkan library not available,start totk error

### ISSUE THREAD

**Issue by 2265290305** [yuzu-emu/yuzu#11444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

every version

### Description of Issue

when i run tears of the kingdom ,it interrupted

### Expected Behavior

在3080的显卡上面可以运行

### Reproduction Steps

open yuzu,
start tears of the kingdom
then it errors

### Log File

[   0.428399] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.428426] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.490902] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.526857] Frontend <Info> yuzu\main.cpp:GMainWindow:365: yuzu Version: yuzu 1546
[   0.526884] Frontend <Info> yuzu\main.cpp:LogRuntimes:244: MSVC Compiler: 1936 Runtime: 14.29.30133.0
[   0.526887] Frontend <Info> yuzu\main.cpp:LogRuntimes:253: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.526889] Frontend <Info> yuzu\main.cpp:GMainWindow:381: Host CPU: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz | AVX2 | FMA
[   0.526893] Frontend <Info> yuzu\main.cpp:GMainWindow:383: Host CPU Cores: 4
[   0.526893] Frontend <Info> yuzu\main.cpp:GMainWindow:386: Host CPU Threads: 4
[   0.527184] Frontend <Info> yuzu\main.cpp:GMainWindow:387: Host OS: Windows 11 Version 22H2 (Build 22621.2134)
[   0.527197] Frontend <Info> yuzu\main.cpp:GMainWindow:389: Host RAM: 11.89 GiB
[   0.527198] Frontend <Info> yuzu\main.cpp:GMainWindow:390: Host Swap: 0.75 GiB
[   0.527254] Frontend <Info> yuzu\main.cpp:GMainWindow:395: Host Timer Resolution: 0.5004 ms
[   0.845992] Render.Vulkan <Error> video_core\vulkan_common\vulkan_instance.cpp:CreateInstance:120: Vulkan library not available
[   0.846537] Frontend <Error> yuzu\vk_device_info.cpp:PopulateRecords:64: Failed to enumerate devices with error: VK_ERROR_INITIALIZATION_FAILED
[   0.874862] Common.Filesystem <Error> common\fs\fs.cpp:IterateDirEntries:418: Filesystem object at path=E:/Windows-Yuzu-EA-3591/yuzu-windows-msvc-early-access/room does not exist
[   0.874869] Common.Filesystem <Error> common\fs\fs.cpp:IterateDirEntries:418: Filesystem object at path=E:/Windows-Yuzu-EA-3591/yuzu-windows-msvc-early-access/room does not exist
[   0.874882] Common.Filesystem <Error> common\fs\fs.cpp:IterateDirEntries:418: Filesystem object at path=G:/Windows-Yuzu-EA-3591/yuzu-windows-msvc-early-access/room does not exist
[   0.874885] Common.Filesystem <Error> common\fs\fs.cpp:IterateDirEntries:418: Filesystem object at path=G:/Windows-Yuzu-EA-3591/yuzu-windows-msvc-early-access/room does not exist
[   0.892117] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[   3.736060] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[   3.937094] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[   3.937493] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[   3.949875] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[   3.954495] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.0.0) applied successfully
[  27.401888] Config <Info> common\settings.cpp:LogSettings:110: yuzu Configuration:
[  27.401899] Config <Info> common\settings.cpp:operator ():103: -- Audio.output_engine: auto
[  27.401900] Config <Info> common\settings.cpp:operator ():103: -- Audio.output_device: auto
[  27.401901] Config <Info> common\settings.cpp:operator ():103: -- Audio.input_device: auto
[  27.401903] Config <Info> common\settings.cpp:operator ():103: -- Audio.volume: 100
[  27.401904] Config <Info> common\settings.cpp:operator ():103: -- Audio.audio_muted: false
[  27.401905] Config <Info> common\settings.cpp:operator ():103: -- Audio.dump_audio_commands: false
[  27.401907] Config <Info> common\settings.cpp:operator ():103: -- Core.use_multi_core: true
[  27.401938] Config <Info> common\settings.cpp:operator ():103: -- Core.memory_layout_mode: Memory_4Gb
[  27.401940] Config <Info> common\settings.cpp:operator ():103: -- Core.use_speed_limit: true
[  27.401942] Config <Info> common\settings.cpp:operator ():103: -- Core.speed_limit: 100
[  27.401944] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpu_accuracy: Auto
[  27.401946] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpu_debug_mode: false
[  27.401947] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_page_tables: true
[  27.401947] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_block_linking: true
[  27.401948] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_return_stack_buffer: true
[  27.401949] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_fast_dispatcher: true
[  27.401951] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_context_elimination: true
[  27.401952] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_const_prop: true
[  27.401952] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_misc_ir: true
[  27.401954] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_reduce_misalign_checks: true
[  27.401955] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_fastmem: true
[  27.401956] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_fastmem_exclusives: true
[  27.401961] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_recompile_exclusives: true
[  27.401962] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_ignore_memory_aborts: true
[  27.401963] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_unsafe_unfuse_fma: true
[  27.401964] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_unsafe_reduce_fp_error: true
[  27.401965] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_unsafe_ignore_standard_fpcr: true
[  27.401966] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_unsafe_inaccurate_nan: true
[  27.401967] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_unsafe_fastmem_check: true
[  27.401969] Config <Info> common\settings.cpp:operator ():103: -- Cpu.cpuopt_unsafe_ignore_global_monitor: true
[  27.401970] Config <Info> common\settings.cpp:operator ():103: -C Renderer.backend: Vulkan
[  27.401975] Config <Info> common\settings.cpp:operator ():103: M- Renderer.shader_backend: Glasm
[  27.401977] Config <Info> common\settings.cpp:operator ():103: MC Renderer.vulkan_device: 18446744073709551615
[  27.401978] Config <Info> common\settings.cpp:operator ():103: -- Renderer.use_disk_shader_cache: true
[  27.401979] Config <Info> common\settings.cpp:operator ():103: MC Renderer.use_asynchronous_gpu_emulation: false
[  27.401981] Config <Info> common\settings.cpp:operator ():103: MC Renderer.accelerate_astc: CpuAsynchronous
[  27.401982] Config <Info> common\settings.cpp:operator ():103: -- Renderer.use_vsync: Fifo
[  27.401984] Config <Info> common\settings.cpp:operator ():103: MC Renderer.nvdec_emulation: Cpu
[  27.401986] Config <Info> common\settings.cpp:operator ():103: -- Renderer.fullscreen_mode: Borderless
[  27.401987] Config <Info> common\settings.cpp:operator ():103: -- Renderer.aspect_ratio: R16_9
[  27.401995] Config <Info> common\settings.cpp:operator ():103: -C Renderer.resolution_setup: Res1X
[  27.401997] Config <Info> common\settings.cpp:operator ():103: -- Renderer.scaling_filter: Bilinear
[  27.401999] Config <Info> common\settings.cpp:operator ():103: -- Renderer.anti_aliasing: None
[  27.402000] Config <Info> common\settings.cpp:operator ():103: -- Renderer.fsr_sharpening_slider: 25
[  27.402001] Config <Info> common\settings.cpp:operator ():103: -- Renderer.bg_red: 0
[  27.402002] Config <Info> common\settings.cpp:operator ():103: -- Renderer.bg_green: 0
[  27.402003] Config <Info> common\settings.cpp:operator ():103: -- Renderer.bg_blue: 0
[  27.402004] Config <Info> common\settings.cpp:operator ():103: -- Renderer.gpu_accuracy: High
[  27.402007] Config <Info> common\settings.cpp:operator ():103: -- Renderer.max_anisotropy: Automatic
[  27.402008] Config <Info> common\settings.cpp:operator ():103: -- Renderer.astc_recompression: Uncompressed
[  27.402009] Config <Info> common\settings.cpp:operator ():103: -- Renderer.async_presentation: false
[  27.402010] Config <Info> common\settings.cpp:operator ():103: -- Renderer.force_max_clock: false
[  27.402010] Config <Info> common\settings.cpp:operator ():103: -- Renderer.use_reactive_flushing: true
[  27.402011] Config <Info> common\settings.cpp:operator ():103: -- Renderer.use_asynchronous_shaders: false
[  27.402012] Config <Info> common\settings.cpp:operator ():103: MC Renderer.use_fast_gpu_time: false
[  27.402014] Config <Info> common\settings.cpp:operator ():103: MC Renderer.use_vulkan_driver_pipeline_cache: false
[  27.402015] Config <Info> common\settings.cpp:operator ():103: -- Renderer.enable_compute_pipelines: false
[  27.402016] Config <Info> common\settings.cpp:operator ():103: -- Renderer.use_video_framerate: false
[  27.402017] Config <Info> common\settings.cpp:operator ():103: -- Renderer.barrier_feedback_loops: true
[  27.402017] Config <Info> common\settings.cpp:operator ():103: -- Renderer.debug: false
[  27.402018] Config <Info> common\settings.cpp:operator ():103: -- Renderer.shader_feedback: false
[  27.402019] Config <Info> common\settings.cpp:operator ():103: -- Renderer.nsight_aftermath: false
[  27.402020] Config <Info> common\settings.cpp:operator ():103: -- Renderer.disable_shader_loop_safety_checks: false
[  27.402024] Config <Info> common\settings.cpp:operator ():103: M- System.language_index: ChineseSimplified
[  27.402026] Config <Info> common\settings.cpp:operator ():103: -- System.region_index: Usa
[  27.402030] Config <Info> common\settings.cpp:operator ():103: -- System.time_zone_index: Auto
[  27.402031] Config <Info> common\settings.cpp:operator ():103: -- System.custom_rtc_enabled: false
[  27.402032] Config <Info> common\settings.cpp:operator ():103: -- System.custom_rtc: 0
[  27.402033] Config <Info> common\settings.cpp:operator ():103: -- System.rng_seed_enabled: false
[  27.402034] Config <Info> common\settings.cpp:operator ():103: -- System.rng_seed: 0
[  27.402035] Config <Info> common\settings.cpp:operator ():103: -- System.device_name: yuzu
[  27.402036] Config <Info> common\settings.cpp:operator ():103: -- System.current_user: 0
[  27.402037] Config <Info> common\settings.cpp:operator ():103: -- System.use_docked_mode: Docked
[  27.402038] Config <Info> common\settings.cpp:operator ():103: -- System.sound_index: Stereo
[  27.402040] Config <Info> common\settings.cpp:operator ():103: -- Data Storage.use_virtual_sd: true
[  27.402041] Config <Info> common\settings.cpp:operator ():103: -- Data Storage.gamecard_inserted: false
[  27.402042] Config <Info> common\settings.cpp:operator ():103: -- Data Storage.gamecard_current_game: false
[  27.402043] Config <Info> common\settings.cpp:operator ():103: -- Data Storage.gamecard_path: 
[  27.402044] Config <Info> common\settings.cpp:operator ():103: -- Debugging.use_gdbstub: false
[  27.402045] Config <Info> common\settings.cpp:operator ():103: -- Debugging.gdbstub_port: 6543
[  27.402046] Config <Info> common\settings.cpp:operator ():103: -- Debugging.program_args: 
[  27.402046] Config <Info> common\settings.cpp:operator ():103: -- Debugging.dump_exefs: false
[  27.402047] Config <Info> common\settings.cpp:operator ():103: -- Debugging.dump_nso: false
[  27.402048] Config <Info> common\settings.cpp:operator ():103: -- Debugging.enable_fs_access_log: false
[  27.402049] Config <Info> common\settings.cpp:operator ():103: -- Debugging.reporting_services: false
[  27.402050] Config <Info> common\settings.cpp:operator ():103: -- Debugging.quest_flag: false
[  27.402051] Config <Info> common\settings.cpp:operator ():103: -- Debugging.extended_logging: false
[  27.402051] Config <Info> common\settings.cpp:operator ():103: -- Debugging.use_debug_asserts: false
[  27.402052] Config <Info> common\settings.cpp:operator ():103: -- Debugging.use_auto_stub: false
[  27.402053] Config <Info> common\settings.cpp:operator ():103: -- Debugging.enable_all_controllers: false
[  27.402054] Config <Info> common\settings.cpp:operator ():103: -- Debugging.create_crash_dumps: false
[  27.402055] Config <Info> common\settings.cpp:operator ():103: -- Debugging.perform_vulkan_check: true
[  27.402056] Config <Info> common\settings.cpp:operator ():103: -- Debugging.dump_shaders: false
[  27.402057] Config <Info> common\settings.cpp:operator ():103: -- Debugging.dump_macros: false
[  27.402058] Config <Info> common\settings.cpp:operator ():103: -- Debugging.disable_macro_jit: false
[  27.402059] Config <Info> common\settings.cpp:operator ():103: -- Debugging.disable_macro_hle: false
[  27.402060] Config <Info> common\settings.cpp:operator ():103: -- Miscellaneous.log_filter: *:Info
[  27.402061] Config <Info> common\settings.cpp:operator ():103: -- Miscellaneous.use_dev_keys: false
[  27.402062] Config <Info> common\settings.cpp:operator ():103: M- Network.network_interface: 无
[  27.402063] Config <Info> common\settings.cpp:operator ():103: M- WebService.enable_telemetry: false
[  27.402068] Config <Info> common\settings.cpp:operator ():103: -- WebService.web_api_url: https://api.yuzu-emu.org
[  27.402069] Config <Info> common\settings.cpp:operator ():103: -- WebService.yuzu_username: 
[  27.402070] Config <Info> common\settings.cpp:operator ():103: -- Controls.enable_raw_input: false
[  27.402071] Config <Info> common\settings.cpp:operator ():103: -- Controls.controller_navigation: true
[  27.402072] Config <Info> common\settings.cpp:operator ():103: -- Controls.enable_joycon_driver: true
[  27.402073] Config <Info> common\settings.cpp:operator ():103: -- Controls.enable_procon_driver: false
[  27.402074] Config <Info> common\settings.cpp:operator ():103: -- Controls.vibration_enabled: true
[  27.402075] Config <Info> common\settings.cpp:operator ():103: -- Controls.enable_accurate_vibrations: false
[  27.402075] Config <Info> common\settings.cpp:operator ():103: -- Controls.motion_enabled: true
[  27.402076] Config <Info> common\settings.cpp:operator ():103: -- Controls.udp_input_servers: 127.0.0.1:26760
[  27.402077] Config <Info> common\settings.cpp:operator ():103: -- Controls.enable_udp_controller: false
[  27.402078] Config <Info> common\settings.cpp:operator ():103: -- Controls.pause_tas_on_load: true
[  27.402079] Config <Info> common\settings.cpp:operator ():103: -- Controls.tas_enable: false
[  27.402080] Config <Info> common\settings.cpp:operator ():103: -- C

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:
my cpu is i5-4690 ,and i had no graphics card
i had install many drivers
ram:forggoten
os win11 family

**Comment by anpilley** [comment]
The iGPU built into your processor is too old to use Yuzu, intel stopped producing updated drivers for it several years ago. Yuzu requires a gpu that is receiving frequent driver updates that include support for recent versions of the Vulkan API.

See [Yuzu's hardware requirements](https://yuzu-emu.org/help/quickstart/#hardware-requirements) for more information about the minimum specs for yuzu, in particular, paying attention to the minimum requirements for Integrated Graphics.
