### ISSUE TITLE
Feedback for the short description of Yuzu

### ISSUE THREAD

**Issue by davidhedlund** [yuzu-emu/yuzu#11446]
### Issue

https://github.com/yuzu-emu/yuzu says: _yuzu is the world's most popular, open-source, Nintendo Switch emulator — started by the creators of [Citra](https://citra-emu.org/)._

Let's break it down:
* _worlds_ -- Very few Nintendo Switch currently exists. As far as I know, only Ryujinx, and Yuzu, exists for desktop OSes.
* _open-source_ -- your project is distributed under a [free software](https://www.gnu.org/philosophy/free-sw.en.html) license. The section "Practical Differences between Free Software and Open Source" at https://www.gnu.org/philosophy/open-source-misses-the-point.en.html is useful reading in order to understand the difference between them.
* _creator_ -- https://www.gnu.org/philosophy/words-to-avoid.en.html#Creator

I think it would be useful to change the text to make it more technically correct, and more relaxed.

I appreciate all the hard time you developers put in your free time to produce this powerful emulator.

**Comment by goldenx86** [comment]
As one of the local deities, I refuse.

**Comment by davidhedlund** [comment]
> As one of the local deities, I refuse.

I respect your decision.

**Comment by FernandoS27** [comment]
I do not find any contradictions personally. We are fully open source, no source code is hidden. As if we are free or not, we are free for you to compile or use anything in github but we only give free binary distributions of what's merged into the project. What's experimental is part of our perks for donations. So we fully fill the definition of open source. Free software is argueable. 

Creators, I see no big issue here and most popular can be easily be considered by number of users and impact.

So, in a common sense perspective, I do not see a need to change it.

**Comment by davidhedlund** [comment]
> I do not find any contradictions personally. We are fully open source, no source code is hidden. As if we are free or not, we are free for you to compile or use anything in github but we only give free binary distributions of what's merged into the project. What's experimental is part of our perks for donations. So we fully fill the definition of open source. Free software is argueable.
> 
> Creators, I see no big issue here and most popular can be easily be considered by number of users and impact.
> 
> So, in a common sense perspective, I do not see a need to change it.

Thank you for your feedback.
