### ISSUE TITLE
Cannot configure the Controls

### ISSUE THREAD

**Issue by davidhedlund** [yuzu-emu/yuzu#11442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1546

### Description of Issue

Regardless if I'm using Nintendo Switch Pro Controller, or Sony DualSense: When I hit the OK button, yuzu crashes. The Cancel button does not crash yuzu.

![image](https://github.com/yuzu-emu/yuzu/assets/6416073/3aa155e1-9edf-45e2-8760-248e8f7b6ae5)

### Expected Behavior

Should not happend.

### Reproduction Steps

* Open the menu Emulation -> Configure
* Click on the Controls tab
* Modify a button (for example, change button "X" from value "Button 1" to "Button 2"), or change to another Controller 
* Click on the OK button, it will crashes yuzu for me.
* Open yuzu again, and open the Controls tab. You'll notice that the setting has not been applied.

I guess this has already been reported, but I could not find it.

### Log File

Not applicable since this is not a game issue.

### System Configuration

CPU: Intel i7 7700K kaby lake
GPU/Driver: HD Graphics 630
RAM: 32 GB
OS: Trisquel 11

**Comment by german77** [comment]
Logs aren't limited to games. They reflect the overall state of the emulator. Please upload it.

**Comment by davidhedlund** [comment]
Sure, but nothing was added to the log after I opened the Controls and pressed the OK button:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12508693/yuzu_log.txt)

**Comment by german77** [comment]
VK_ERROR_EXTENSION_NOT_PRESENT update your gpu drivers. This is not a controller issue.

**Comment by liamwhite** [comment]
You are missing xlib support in your vulkan driver, which crashes, because we require it on Linux. I think this used to be less brittle (@lat9nq ?) and I agree it shouldn't crash, but even if we fix the crashes, you won't be able use Vulkan, which is important for performance and accuracy in most games.

**Comment by davidhedlund** [comment]
> You are missing xlib support in your vulkan driver, which crashes, because we require it on Linux. I think this used to be less brittle (@lat9nq ?) and I agree it shouldn't crash, but even if we fix the crashes, you won't be able use Vulkan, which is important for performance and accuracy in most games.

Did you close the issue because I'm using OpenGL?

**Comment by davidhedlund** [comment]
Vulkan is not available in Yuzu for [Trisquel](https://trisquel.info/) GNU/Linux. So all Trisquel users are forced to use OpenGL.
