### ISSUE TITLE
Jit cache options, write shaders/pipeline in RAM options (save it to disk after exiting the game or emu / minutes), more ram options (under 4 gb unsafe)

### ISSUE THREAD

**Issue by boludoz** [yuzu-emu/yuzu#11443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I see that the emulator is constantly interacting with the hard drive, maybe it's better to do it a few times if the chunks of things are small, and to use the hard drive less often. I don't have much knowledge about the emulator, but I know that it constantly uses my hard drive. RAM is cheaper and faster, maybe you can reserve a small array for data.

### Why would this feature be useful?

I think it solves a bit of the classic stutter when building the shader or other things.

**Comment by FearlessTobi** [comment]
yuzu is already using your RAM for emulating games.
