### ISSUE TITLE
Broken link and addition to wiki/switch-mods

### ISSUE THREAD

**Issue by hww8352** [yuzu-emu/yuzu#11454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

N/A

### Description of Issue

I do not have permission to update the wiki, so I am asking someone who does!

1. On Mario Strikers - https://github.com/yuzu-emu/yuzu/wiki/switch-mods#mario-strikers-battle-league
    - **No Intro/Credits bypass mod** WRONG LINK
FIX: https://github.com/piplup55/switch-mods-cheats/blob/master/Mario%20Strikers%20Battle%20League/cutscene%20skip.7z?raw=true 
Credits **ADD LINK** [piplup55](https://github.com/piplup55/switch-mods-cheats)

2. On Mario Tennis Aces - https://github.com/yuzu-emu/yuzu/wiki/switch-mods#mario-tennis-aces
    - **ADD NEW ENTRY** [60 FPS](https://github.com/theboy181/switch-ptchtxt-mods/blob/main/Mario%20Tennis%20Aces/[0100BDE00862A000]/1.0.0/60fps.rar?raw=true) 
Description: Run at 60fps instead of 30fps.
Credit: [theboy181](https://github.com/theboy181/switch-ptchtxt-mods)

### Expected Behavior

It is a wiki change

### Reproduction Steps

It is a wiki change

### Log File

It is a wiki change

### System Configuration

It is a wiki change

**Comment by FearlessTobi** [comment]
fixed
