### ISSUE TITLE
AIR, the Visual Novel, is unplayable

### ISSUE THREAD

**Issue by Gilles4Prezudent** [yuzu-emu/yuzu#11466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3859

### Description of Issue

The game flashes very rapidly. Likely enough to cause trouble for people with epilepsy.

### Expected Behavior

The game should not flash rapidly.

### Reproduction Steps

Start the game.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12555376/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12555377/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel I9 13900K
GPU/Driver: Nvidia RTX 4080 Driver Ver. 31.0.15.3640
RAM: 32GB DDR5
OS: Windows 11

**Comment by goldenx86** [comment]
Seems to be GPU vendor and settings independent. Other Key visual novels like planetarian are affected too.

**Comment by Aphcity** [comment]
Try mainline build 1441 or before to check if the issue is same to #10433 or try the lastest build in my forked rep, let us check that.

https://github.com/yuzu-emu/yuzu/pull/11554
