### ISSUE TITLE
Mario Galaxy crash after grand star

### ISSUE THREAD

**Issue by GovernedSquid6** [yuzu-emu/yuzu#11474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1545

### Description of Issue

In SM3DAS, after obtaining a grand star in the fountain or kitchen, the game crashes, right around the time Rosalina begins her line that comes before the prompt to save the game. I first started getting this issue consistently first in the fountain, so i skipped ahead on my actual switch, and then now its the same thing for the next dome.

### Expected Behavior

I expect it to progress the game as normally without crashing

### Reproduction Steps

play a new game to the point of the grand star in the fountain, finish the final level in the dome, collect the grand star, continue through all text prompts

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12567022/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 5600x 6-Core Processor
GPU/Driver: NVIDIA GeForce RTX 3060 Ti
RAM:16GB
OS: Windows 11 Pro

**Comment by liamwhite** [comment]
The game crashes or the entire emulator crashes? Log is indicative of emulator crash

**Comment by GovernedSquid6** [comment]
im pretty sure its the entire emulator

**Comment by Squall-Leonhart** [comment]
please update your video driver.

**Comment by GovernedSquid6** [comment]
done, i still get the crash

**Comment by GovernedSquid6** [comment]
does anybody else have this problem?

**Comment by golivax** [comment]
Mario Galaxy randomly crashes the entire emulator when using the Vulkan backend on my ROG Ally. It seems to occur more frequently in the Bowser Jr's Robot Reactor stage (never managed to complete this stage with Vulkan). I'm running latest official drivers and latest BIOS (330) for the Ally. Runs fine with OpenGL (no crashes), but I get slightly lower FPS and considerably more shader compilation stutter.

**Comment by liamwhite** [comment]
@golivax can you provide the latest crash dump available from %appdata%\yuzu\crash_dumps and the version of yuzu you were using when it crashed?

**Comment by golivax** [comment]
@liamwhite hey! I updated to mainline 1590 and tested it again. Game crashed in that same stage after a minute or so. Checked the crash dumps, but it was empty. Is there any setting I should enable on Yuzu to get crash dumps? Glancing through the logs, the only suspicious statements I could find were:

[  20.483189] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  20.483629] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  20.484054] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[  20.484227] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
**[  20.561459] HW.Memory <Error> core\memory.cpp:operator ():695: Unmapped Read8 @ 0x0000000000000038
[  20.561466] HW.Memory <Error> core\memory.cpp:operator ():719: Unmapped Write8 @ 0x0000000000000038 = 0x0000000000000020**
[  20.604405] Service.AM <Warning> core\hle\service\am\am.cpp:SetRestartMessageEnabled:485: (STUBBED) called
[  20.604691] Service.AM <Warning> core\hle\service\am\am.cpp:SetOperationModeChangedNotification:449: (STUBBED) called flag=true

and

[  13.292570] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:1012: Device doesn't support feature depthBiasExact
[  13.292636] Render.Vulkan <Warning> video_core\vulkan_common\vulkan_device.cpp:Device:600: AMD drivers have broken extendedDynamicState3ColorBlendEquation
**[  14.381931] Debug <Critical> video_core\vulkan_common\vulkan_device.cpp:operator ():748: Assertion Failed!
Format=125 with usage=49665 and type=1 has no defined alternatives and host hardware does not support it**
[  14.450806] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:950: Device doesn't support extension VK_EXT_depth_bias_control

and similarly 

[  79.355398] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:1012: Device doesn't support feature depthBiasExact
[  79.355435] Render.Vulkan <Warning> video_core\vulkan_common\vulkan_device.cpp:Device:600: AMD drivers have broken extendedDynamicState3ColorBlendEquation
**[  79.471826] Debug <Critical> video_core\vulkan_common\vulkan_device.cpp:operator ():748: Assertion Failed!
Format=125 with usage=49665 and type=1 has no defined alternatives and host hardware does not support it**
[  79.480365] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:159: Driver: AMD proprietary driver 2.0.270
[  79.480368] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:160: Device: AMD Radeon Graphics


The logs end abruptly:

[ 391.523777] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:589: 0xc342166d1fda1f56
[ 403.182738] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:589: 0x403889feeb47d167
[ 403.183683] Render.Vulkan

**Comment by liamwhite** [comment]
The log cuts off because it was not flushed after a crash. I am a bit confused that the crash dump is missing in this case, as it should have been written. The crash is evidently inside the GPU driver, so maybe Breakpad is ignoring it because of that? I will try to reproduce and get more info tomorrow.

**Comment by golivax** [comment]
Awesome, thanks a lot!

**Comment by liamwhite** [comment]
@golivax Please try the msvc artifact from the following link: https://nightly.link/yuzu-emu/yuzu/actions/runs/6548425108 

I believe this should fix the issue.

**Comment by golivax** [comment]
> @golivax Please try the msvc artifact from the following link: https://nightly.link/yuzu-emu/yuzu/actions/runs/6548425108 
> 
> I believe this should fix the issue.

Awesome! I'll try it out tonight

**Comment by golivax** [comment]
@liamwhite I am happy to report that your PR does fix the issue! Played the same stage 3 times and it never crashed. Thanks a lot! [Just not sure if this is the same problem that the OP was having]

**Comment by Squall-Leonhart** [comment]
It was, yes.
