### ISSUE TITLE
Pikmin 4: Lighting rendering issue (filing with save that can used on demo)

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#11487]
### Issue

Pikmin 4 has lighting issue that will not render lighting and flickers, or never render again after few second
yuzu:

https://github.com/yuzu-emu/yuzu/assets/66776795/d71b2d46-9444-4f89-b791-00b5de8f39a5

console:

![chrome_CALmmjTjIq](https://github.com/yuzu-emu/yuzu/assets/66776795/f2358634-f67d-4692-8dd6-eddfb34472e7)

save:

[A.zip](https://github.com/yuzu-emu/yuzu/files/12583833/A.zip)

2nd save slot should direct to those area

**Comment by IceMaverick** [comment]
[https://github.com/yuzu-emu/yuzu/issues/11125#issue-1815476502](Duplicate Deficiency Report) as this #11125

**Comment by ethaldeman** [comment]
After an update last Friday, November 11, this problem seems to have returned. I didn't have any lighting flickering in Pikmin 4, but after the update on Friday, the flickering returned.
