### ISSUE TITLE
Kirby and the Forgotten Land crashing during gameplay

### ISSUE THREAD

**Issue by goldenx86** [yuzu-emu/yuzu#11485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1555 / Early Access 3863

### Description of Issue

Unmapped reads/writes crash while playing specific worlds areas in Kirby and the Forgotten Land. Happens with no mods enabled.

### Expected Behavior

No crash.

### Reproduction Steps

World 6 Level 5 "The Beast Packs Final Stand" is an example: 
https://cdn.discordapp.com/attachments/400106910231035904/1150961610018521128/IMG_8281.mov

[01004D300C5AE000.zip](https://github.com/yuzu-emu/yuzu/files/12581627/01004D300C5AE000.zip)

### Log File

[yuzu_log (3).txt](https://github.com/yuzu-emu/yuzu/files/12581620/yuzu_log.3.txt)

### System Configuration

CPU: 5800X
GPU/Driver: RTX 3070 Ti / 537.13
RAM: 32GB
OS: Windows 10 22H2

**Comment by liamwhite** [comment]
Reporter found rom to be corrupt
