### ISSUE TITLE
Baten Kaitos HD hangs on loading screen after booting

### ISSUE THREAD

**Issue by jpl83** [yuzu-emu/yuzu#11494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3867

### Description of Issue

There's an in-game selection between Baten Kaitos 1 and 2. After selecting either of them, yuzu shows a launching screen as if it's starting a new game, then shows a black screen instead of what should be the loading screen for BK.

Selection screen: ![0100f28018ca4000_2023-09-13_23-40-21-838](https://github.com/yuzu-emu/yuzu/assets/1453519/e142c0f0-05d5-4c4e-8c02-75bd5ee574dc)
Loading screen that hangs indefinitely: ![0100f28018ca4001_2023-09-13_23-40-27-511](https://github.com/yuzu-emu/yuzu/assets/1453519/527f8aec-a65e-4f5e-aa3b-da638196ae44)

Note: The loading screen in the second screenshot is completely black (no bar visible) in the emulator. It only shows up in the screenshot.

### Expected Behavior

Selecting BK1 or 2 should show a loading screen, which eventually ends in launching either game.

### Reproduction Steps

1) Start game
2) Wait until selection screen for BK1 or 2
3) Select one of the games and confirm

### Log File

[yuzu_log (5).txt](https://github.com/yuzu-emu/yuzu/files/12602193/yuzu_log.5.txt)
[yuzu_log (4).txt](https://github.com/yuzu-emu/yuzu/files/12602195/yuzu_log.4.txt)

### System Configuration

Steam Deck

**Comment by goldenx86** [comment]
Note that Auto-Stub wasn't enough.

**Comment by german77** [comment]
needs ngc:u service.

**Comment by rds19dbz** [comment]
Any fix for this?
