### ISSUE TITLE
Baten Kaitos garbled graphics

### ISSUE THREAD

**Issue by NineKain** [yuzu-emu/yuzu#11498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1558

### Description of Issue

Broken graphics as the image shows
![image](https://github.com/yuzu-emu/yuzu/assets/72826232/7cc1ff29-734a-4176-96d4-c79d7c8ee957)

### Expected Behavior

Not broken graphics

### Reproduction Steps

Open the game, start playing, it can be seen on even the first custcene

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12611422/yuzu_log.txt)

### System Configuration

CPU: 5600x
GPU/Driver: 3060ti 537.34
RAM: 16gb
OS: Win 10

**Comment by NineKain** [comment]
Yeah I think it is, and it is broken on latest mainline

**Comment by german77** [comment]
Tomorrow the game should be playable. I doubt the graphical issue will be fixed on next build.

**Comment by rds19dbz** [comment]
wait.. how did it work, i tried on my end and still black screen
