### ISSUE TITLE
Add "Install Firmware" and "Install Key" Options for Desktop like the Android Version

### ISSUE THREAD

**Issue by AliciaBurrito** [yuzu-emu/yuzu#11495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The Android version has options to import user provided firmware and key files, and ideally this should be "backported" to the desktop version of yuzu as well.

### Why would this feature be useful?

It would cut down on improper firmware and key installations, and bring in-line the updated experience from Android back to the desktop version. A nice usability quality of life change.

**Comment by anpilley** [comment]
Resolved with #13056 and #13047
