### ISSUE TITLE
Super Smash Bros. Ultimate - Crash Report

### ISSUE THREAD

**Issue by xAlbert373** [yuzu-emu/yuzu#11501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1558

### Description of Issue

When you do a critical attack at the last life it should be a red effect and a zoom for it but when it happens the games just crashes without no further information.

### Expected Behavior

I guess that it happens because of my hardware but i don't know really.

### Reproduction Steps

Just play a normal smash till one player reach 1 life left and then get them to a hight percentage and then do a critical attack to them, it should to crash.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12614168/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel(R) Pentium(R) Gold G5420 CPU @ 3.80GHz   3.80 GHz
GPU/Driver: Intel(R) UHD Graphics 610
RAM: 16 GB RAM DDR4
OS: Windows 11 Pro

**Comment by Squall-Leonhart** [comment]
That GPU is unsupported on Windows.

**Comment by FearlessTobi** [comment]
Closing since we don't support this IGPU anymore.

**Comment by xAlbert373** [comment]
Reasons why Ryujinx is always better than Yuzu: 💀
