### ISSUE TITLE
bug report on the site

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [yuzu-emu/yuzu#11514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu Site

### Description of Issue

basically , i deleted my citra account , cause my pfp was not updating no matter what, and i made another account , and i was like "ok time to get my token" , went to get my token , and the site said this error : Error.
There was an error processing your request. Please try again later. , there isnt any error codes for this.

### Expected Behavior

the site to give me my token 

### Reproduction Steps

1 : delete your citra account
2 : try to get your token with a new citra account
3 : the error should be replicated

### Log File

there isnt any logs

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by german77** [comment]
This isn't related to the emulator itself but rather the website. You can ask on the citra forum or discord for support.

**Comment by Amgsdfyhadfgybi** [comment]
ah thank you , i already did that and im waiting for a response
