### ISSUE TITLE
Baten Kaitos show english no matter what language selected

### ISSUE THREAD

**Issue by wo9999999999** [yuzu-emu/yuzu#11511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline Build - 0bc00c1e7

### Description of Issue

no matter what language selected the game show English

### Expected Behavior

show selected language (eg: japanese/ chinese)

### Reproduction Steps

select language other than english when u first start the game

### Log File

-

### System Configuration

CPU:-
GPU/Driver:-
RAM:-
OS:-

**Comment by FearlessTobi** [comment]
You did not correctly fill out the issue template.
Closing.
