### ISSUE TITLE
[Bug] Yuzu dont dump main executable in RDR 

### ISSUE THREAD

**Issue by boludoz** [yuzu-emu/yuzu#11516]
### Issue

Unfortunately Yuzu does not extract all the files from RDR1, it only extracts a part. The internal structure of the game, for example, has a folder called "0" that contains the game executable that can be edited with IDA Pro, for example.

**Comment by boludoz** [comment]
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/d4d1203d-e70c-43e7-a5ee-0269b7af9e44)

**Comment by boludoz** [comment]
It makes life much easier for those of us who modify games to be able to dump all the files.

**Comment by liamwhite** [comment]
The executable is not contained in a directory called 0. It is contained inside the program NCA's ExeFS partition, which you can enable dumping of in Emulation -> Configure... -> System -> Filesystem -> Dump ExeFS.

After booting the game, you can then find the ExeFS contents at `yuzu/dump/01007820196A6000/exefs`.
