### ISSUE TITLE
visual errors pls help me

### ISSUE THREAD

**Issue by elosoislamico** [yuzu-emu/yuzu#11531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1561

### Description of Issue

1/3 of the screen looks weird

### Expected Behavior

not like this i guess

### Reproduction Steps

i opened the game for the first time today

### Log File

![Captura de pantalla 2023-09-17 192233](https://github.com/yuzu-emu/yuzu/assets/145298716/b4d41a59-6d2d-4255-bb2c-5c43775916d1)
![Captura de pantalla 2023-09-17 193123](https://github.com/yuzu-emu/yuzu/assets/145298716/99261296-f595-459f-bcc1-15d3d45b3c69)

### System Configuration

CPU:11th Gen intel(R) core(TM) i5 11400H@2.70GHZ
GPU/Driver:gtx1650 4gb
RAM:16gb 
OS:windows 11

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
