### ISSUE TITLE
Add a 'start' button in maintenancetool

### ISSUE THREAD

**Issue by DanielSvoboda** [yuzu-emu/yuzu#11547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add a 'start' button in liftinstall/maintenancetool

### Why would this feature be useful?

I always open it to check for updates, and then open yuzu, if everything was together it would be a good shortcut.
Or include the update check when opening yuzu.

**Comment by Squall-Leonhart** [comment]
That would be up to the upstream provider

https://github.com/j-selby/liftinstall/issues
