### ISSUE TITLE
External drive, no recent firmware working

### ISSUE THREAD

**Issue by RoueSoify** [yuzu-emu/yuzu#11549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All of them since at least january

### Description of Issue

I have all of my emulation stuff on an external hard drive.
It has always worked very well but yuzu for some reason doesn't want to get firmwares (or keys) working.
I have every game that doesn't require firmware working. (And Mario Kart 8 Deluxe on something like 14.0.2, but it runs very very poorly).
I haven't yet tested every firmware version, will try that if it helps. But at least 16.0.3 not working.

While I'm at it it would be great to have an option in the yuzu installer to install somewhere else.

### Expected Behavior

I shouldn't get the firmware decryption error.

### Reproduction Steps

1. Have an external drive (mine is a 4To Seagate something)
2. Install yuzu
3. Move yuzu to the drive
4. move nand and link everything
5. Open yuzu
6. Get error message

### Log File

Don't think it's log related as it doesn't seem related to emulation.

### System Configuration

CPU: Intel Core i5-11400h
GPU: NVIDIA GeForce RTX 3060 Laptop GPU (consider this a 2060)
RAM: 16Go DDR4 @3200
OS: Windows 11 (pretty sure I had the same problem on W10)

**Comment by german77** [comment]
Check that your keys are updated as well. They aren't in nand. Also logs contain more than just games, they also have file errors.

**Comment by RoueSoify** [comment]
My keys are updated, I transfered the files over to my Steam Deck and they work there.
I'll try to get a log when I get back home.

**Comment by RoueSoify** [comment]
![image](https://github.com/yuzu-emu/yuzu/assets/52323610/8d82e133-7135-4f14-8680-0d02be6d8ae4)
![image](https://github.com/yuzu-emu/yuzu/assets/52323610/1728e5ad-e5f2-4ada-9a52-2fc508bca2b1)

[   0.592024] Frontend <Info> yuzu\main.cpp:GMainWindow:367: yuzu Version: yuzu 1561
[   0.592106] Frontend <Info> yuzu\main.cpp:LogRuntimes:246: MSVC Compiler: 1935 Runtime: 14.36.32532.0
[   0.592108] Frontend <Info> yuzu\main.cpp:LogRuntimes:255: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.592109] Frontend <Info> yuzu\main.cpp:GMainWindow:383: Host CPU: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz | AVX512 | FMA
[   0.592117] Frontend <Info> yuzu\main.cpp:GMainWindow:385: Host CPU Cores: 6
[   0.592118] Frontend <Info> yuzu\main.cpp:GMainWindow:388: Host CPU Threads: 12
[   0.592284] Frontend <Info> yuzu\main.cpp:GMainWindow:389: Host OS: Windows 11 Version 22H2 (Build 22621.2283)
[   0.592298] Frontend <Info> yuzu\main.cpp:GMainWindow:391: Host RAM: 15.77 GiB
[   0.592299] Frontend <Info> yuzu\main.cpp:GMainWindow:392: Host Swap: 17.00 GiB
[   0.592447] Frontend <Info> yuzu\main.cpp:GMainWindow:397: Host Timer Resolution: 0.5000 ms
[   1.115636] Frontend <Warning> yuzu\main.cpp:OnReinitializeKeys:4531: Mii model decryption failed

Seems the problem has something to do with the miis, wich might not be a yuzu problem in itself. Have no idea how to fix though

**Comment by german77** [comment]
We check the mii to make sure your keys can decrypt firmware. This means you hace a mismatched keys/firmware version. So your keys can't read your firmware. Make sure both are latest on your switch. If you are running latest firmware check with a text editor that your keys contain the `_0f` entries if they don't update your homebrew tools to latest and dump them again.

If it's still failing let me know.

**Comment by RoueSoify** [comment]
I tried, still failing.
My prod keys do have the _0f entries

**Comment by german77** [comment]
Can you do a sanity check and test on a portable build on your local drive. I'm testing on a NAS and microsd. None have any issue at all.

I still believe this issue is down to user error. If you can give screenshots of your yuzu folder, keys folder and registered folder. I might have a better view on what's wrong.

**Comment by RoueSoify** [comment]
Works on a clean install.
I guess I did something wrong some time ago and it only appeared after that.
I guess I'll be redoing everything from scratch, but thanks, it's very cool to have received help !

**Comment by Squall-Leonhart** [comment]
if you have a habbit of just unpacking firmware to the folder assuming everything overwrites, it doesn't, you must clear out the existing firmware nca's.

Not saying this is what happened, but you never know.

**Comment by RoueSoify** [comment]
No I do clean evrything once in a while. And the problem solved itself, it simply started working by itself so idk
