### ISSUE TITLE
Mortal Kombat 1 Crashing

### ISSUE THREAD

**Issue by CD912** [yuzu-emu/yuzu#11548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1563

### Description of Issue

When launching, it works fine for the language selection and warnings menu. When you reach the menu that says "Press A to start" with the MK logo. Once you press A, it crashes.

### Expected Behavior

Game shouldn't do this, should just launch. Can't even get to the mode select screen.

### Reproduction Steps

1. Install MK1 with update 1.3.0
2. Use vulkan API (If OpenGL is used, it crashes even earlier.)
3. Proceed with launching game, select language, read health and safety warnings, then press "A"

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12669074/yuzu_log.txt)

### System Configuration

CPU: Ryzen 9 6000 series
GPU/Driver: RTX 3080 TI Laptop GPU w/ v537.13
RAM: 16g
OS: Windows 11

**Comment by Elias-Mardoqueu** [comment]
I have the same problem in my case it still loads for a while and then crashes

**Comment by Turdpeterson** [comment]
only works if you disable the update and play the base game

**Comment by CD912** [comment]
latest update (1.5.0 at the time of writing) just fixes it. Was able to get into a match and play (Surprisingly well, too.) So if you're still struggling with this, just get v1.5.0 or above if applicable

**Comment by joaoafda** [comment]
> latest update (1.5.0 at the time of writing) just fixes it. Was able to get into a match and play (Surprisingly well, too.) So if you're still struggling with this, just get v1.5.0 or above if applicable
> 
> Edit: Should specify, the GAME update. Yuzu still does not work with MK1's 

i have the 1.3.0 where can i update tho 1.5.0?
