### ISSUE TITLE
Kirby Forgotten Land lighting glitches making it almost unplayable

### ISSUE THREAD

**Issue by sharzy720** [yuzu-emu/yuzu#11552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1309

### Description of Issue

When playing Kirby Forgotten Land on Steam Deck with default yuzu settings some of the lighting will have excess bloom that covers up doors and other important spots in certain levels.
![kirby_glitch_1](https://github.com/yuzu-emu/yuzu/assets/69944104/ed74d6b9-aa46-490f-ae16-d73b63aa16a5)
![kirby_glitch_2](https://github.com/yuzu-emu/yuzu/assets/69944104/5a84576c-7fdf-40a4-8eab-6ea07c43e52c)

### Expected Behavior

Basically expected that the lighting is rendered correctly, with no giant bloom over where light is supposed to be.

### Reproduction Steps

With default Yuzu settings and on a Steam Deck play either "The Brawl at the Mall" or "Through the Tunnel". The glitches can be seen within first spawning in each level, "Through the Tunnel" You need to go into the tunnel to see the glitches. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12679298/yuzu_log.txt)

### System Configuration

CPU: Steam Deck
GPU/Driver: Steam Deck
RAM: 16 gb
OS: Steam OS

**Comment by gidoly** [comment]
your yuzu build is extremely outdated pls try on lastest build and let us know if issue persist

**Comment by sharzy720** [comment]
OMG, that fixed it, thought I was auto-updating it through the app store but had to download it from the site. Thanks a bunch
