### ISSUE TITLE
Pokemon Scarlet - Kitakami fly points do not work

### ISSUE THREAD

**Issue by karasuhebi** [yuzu-emu/yuzu#11566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1565 (and some other recent builds)

### Description of Issue

~~When you try to taking a Flying Taxi to Kitakami from Paldea, it doesn't let you.~~ **Update: Found out that the issue is that the Kitakami fly points don't work at all. Even if you're in Kitakami.**

When you try to fly to a Kitakami fly point, the game asks you if you want to fly there and when you say yes, nothing happens. You can fly to any Paldea fly point just fine though.

### Expected Behavior

I expect to be able to fly to the Kitakami fly points.

### Reproduction Steps

Try to fly to any Kitakami fly point.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12695889/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 5 5600X
GPU/Driver: NVIDIA GeForce GTX 1080 Ti /537.34
RAM: 16 GB
OS: Windows 10 Pro Version 22H2

**Comment by karasuhebi** [comment]
Update: Found out that the issue is that the Kitakami fly points don't work at all. Even if you're in Kitakami.

**Comment by karasuhebi** [comment]
Video of the issue
https://www.youtube.com/watch?v=XulTFCX06c0

**Comment by Squall-Leonhart** [comment]
You have a bad dump of the DLC.

**Comment by karasuhebi** [comment]
Nice find! I will re-dump and try again. I'll report back. Thanks!

**Comment by karasuhebi** [comment]
Re-dumped and tried again. I did get an NSP of a different size so I was hopeful but still no luck. :(

Do you happen to own Scarlet and have the 2.0.1 update dumped? If so, is the CRC32 hash for your .nca file A997C66D? It should be in %AppData%\yuzu\nand\user\Contents\registered\0000005E\ and it should be called 55691508695ae3d4bf876b783f966de6.nca.

**Comment by Squall-Leonhart** [comment]
Hash matches for the update data, in B7 the dlc hash for de5e1900a5cea6e1552643b334a5d4ef.nca is 5E8802C4

mind attaching your save?

**Comment by karasuhebi** [comment]
[main.zip](https://github.com/yuzu-emu/yuzu/files/12779986/main.zip)

**Comment by Squall-Leonhart** [comment]
The New Uniform dlc was replaced with combined New Uniform+Teal Mask, it is required for full function of Kitakami.

**Comment by karasuhebi** [comment]
Holy shit, that worked! Thanks for that!

I have some follow up questions though:

1. How do you go about finding out where DLC and updates go once you install the NSP file via yuzu? I would love to know how to do that.

2. How is a user supposed to know that they need to dump the DLC again once the v2.0.1 update came out?

**Comment by FearlessTobi** [comment]
I'm going to close this PR then, feel free to join our Discord or continue dicussing here.

**Comment by karasuhebi** [comment]
I didn't see Squall in the Discord, that's why I was asking. :)
