### ISSUE TITLE
[Bug] [Android] Yuzu closes in Exynos 990

### ISSUE THREAD

**Issue by boludoz** [yuzu-emu/yuzu#11576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest

### Description of Issue

Yuzu closes in Exynos 990 and 6 gb and sometimes in Windows too (16 gb), whatever ram you have, if you don't use a paging file this will close too.

### Expected Behavior

It should start anyway, even if it closes later, in Skyline this does not happen, therefore it is a Yuzu bug. 

### Reproduction Steps

Try to start Cuphead on Android.

### Log File

[yuzu_log (4).txt](https://github.com/yuzu-emu/yuzu/files/12707417/yuzu_log.4.txt)

### System Configuration

CPU: Exynos 990.
GPU/Driver: v38.1.0 ArmProprietary
RAM: 6 gb LPDDR5
OS: Android 13

**Comment by boludoz** [comment]
Log for vulkan:
[yuzu_log (5).txt](https://github.com/yuzu-emu/yuzu/files/12707421/yuzu_log.5.txt)

**Comment by pacoa-kdbg** [comment]
It is not a bug, yuzu uses far more ram than skyline.

Crashes out of memory before rendering but it is trying to start.

**Comment by boludoz** [comment]
> It is not a bug, yuzu uses far more ram than skyline.
> 
> Crashes out of memory before rendering but it is trying to start.

And there is no way to reduce that ram usage?

**Comment by brujo5** [comment]
You have to wait for yuzu to incorporate NCE "native code execution" like Skyline has.  The problem is that it is taking them a long time to work on it.  This is essential and should have been included from the beginning.

**Comment by boludoz** [comment]
> You have to wait for yuzu to incorporate NCE "native code execution" like Skyline has. The problem is that it is taking them a long time to work on it. This is essential and should have been included from the beginning.

Would this NCE also benefit the computer version?

**Comment by brujo5** [comment]
> It is not a bug, yuzu uses far more ram than skyline.
> 
> Crashes out of memory before rendering but it is trying to start.

yuzu uses more RAM than even egg ns for some reason, all the games that crash due to RAM in yuzu work perfectly on egg ns and it doesn't have NCE built in either.  The only thing I have noticed is that egg ns uses swap and zram perfectly compared to yuzu and that is why there are almost no crashes due to low RAM even on phones with 6gb RAM

**Comment by boludoz** [comment]
> > It is not a bug, yuzu uses far more ram than skyline.
> > Crashes out of memory before rendering but it is trying to start.
> 
> yuzu uses more RAM than even egg ns for some reason, all the games that crash due to RAM in yuzu work perfectly on egg ns and it doesn't have NCE built in either. The only thing I have noticed is that egg ns uses swap and zram perfectly compared to yuzu and that is why there are almost no crashes due to low RAM even on phones with 6gb RAM

EGG NS is not closed source?

**Comment by brujo5** [comment]
> > You have to wait for yuzu to incorporate NCE "native code execution" like Skyline has. The problem is that it is taking them a long time to work on it. This is essential and should have been included from the beginning.
> 
> Would this NCE also benefit the computer version?

The switch is ARM CPU just like any Android phone, that means that with nce you will not need to emulate the CPU and would only focus on emulating the GPU.

**Comment by brujo5** [comment]
> > > It is not a bug, yuzu uses far more ram than skyline.
> > > Crashes out of memory before rendering but it is trying to start.
> > 
> > 
> > yuzu uses more RAM than even egg ns for some reason, all the games that crash due to RAM in yuzu work perfectly on egg ns and it doesn't have NCE built in either. The only thing I have noticed is that egg ns uses swap and zram perfectly compared to yuzu and that is why there are almost no crashes due to low RAM even on phones with 6gb RAM
> 
> EGG NS is not closed source?

Yes, but everyone knows that uses the Yuzu code

**Comment by boludoz** [comment]
> > > > It is not a bug, yuzu uses far more ram than skyline.
> > > > Crashes out of memory before rendering but it is trying to start.
> > > 
> > > 
> > > yuzu uses more RAM than even egg ns for some reason, all the games that crash due to RAM in yuzu work perfectly on egg ns and it doesn't have NCE built in either. The only thing I have noticed is that egg ns uses swap and zram perfectly compared to yuzu and that is why there are almost no crashes due to low RAM even on phones with 6gb RAM
> > 
> > 
> > EGG NS is not closed source?
> 
> Yes, but everyone knows that uses the Yuzu code

The one that goes the furthest is Skyline.

**Comment by boludoz** [comment]
> > > > It is not a bug, yuzu uses far more ram than skyline.
> > > > Crashes out of memory before rendering but it is trying to start.
> > > 
> > > 
> > > yuzu uses more RAM than even egg ns for some reason, all the games that crash due to RAM in yuzu work perfectly on egg ns and it doesn't have NCE built in either. The only thing I have noticed is that egg ns uses swap and zram perfectly compared to yuzu and that is why there are almost no crashes due to low RAM even on phones with 6gb RAM
> > 
> > 
> > EGG NS is not closed source?
> 
> Yes, but everyone knows that uses the Yuzu code

https://github.com/strato-emu/strato/tree/master/app/src/main/cpp/skyline/nce

Here it is, we could try to implement it, but I don't think it makes much sense, it means double the effort to have an emulator for Android.

**Comment by FearlessTobi** [comment]
> It is not a bug, yuzu uses far more ram than skyline.
> 
> Crashes out of memory before rendering but it is trying to start.

Closing for this reason.

**Comment by boludoz** [comment]
@FearlessTobi Are there plans for NCE to be implemented in the future?

**Comment by pacoa-kdbg** [comment]
NCE and UMA are planned, but should help with memory usage.
Nobody knows an estimate for them tho

**Comment by brujo5** [comment]
If it is like in Skyline the use of RAM will be minimal, for example the strato devs say that they were able to run Zelda totk on a mobile phone with 6GB of RAM

**Comment by pacoa-kdbg** [comment]
Nobody from the yuzu devs knows for sure how much more optimized memory can be (afaik)

Let's hope for the best :D
