### ISSUE TITLE
[Android] Legend of Nayuta: Boundless Trails crashes on boot

### ISSUE THREAD

**Issue by Alphonsokurukuchu** [yuzu-emu/yuzu#11579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline android build 2921a2426(latest release on September 24)

### Description of Issue

It just crashes when opened(game released newly on 19th September 2023). Produces different kinds of log with turnip driver(23.3.0 rev 6) and Adreno (615.65), attached.

*Attached Skyline's log too(boots in this) for each driver under goldenx86_64's suggestion 

### Expected Behavior

It should just open upto the main menu in-game 

### Reproduction Steps

Open the game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12707956/yuzu_log.txt)
 (turnip 23.3.0 rev6)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12707957/yuzu_log.txt)
 (Adreno 615.65)

[emulation-3.txt](https://github.com/yuzu-emu/yuzu/files/12707976/emulation-3.txt)
(skyline v69 on turnip 23.3.0 rev 6)
[emulation-2.txt](https://github.com/yuzu-emu/yuzu/files/12707977/emulation-2.txt)
(skyline v69 on adreno 615.65)

### System Configuration

CPU: Snapdragon 865+
GPU/Driver: Adreno 650 tried on both turnip 23.3.0 rev6 and Adreno 615.65
RAM:6GB(+2GB virtual)
OS: Android 14 (One UI 5.1.1)

Additionally I've tried various settings including making it 'safest' to run,

**Comment by brujo5** [comment]
Work fine here 
![IMG_20230924_080650_683](https://github.com/yuzu-emu/yuzu/assets/4172898/9125867c-929a-4ea7-9d49-aeba8b88eb7c)

Poco f4 
Work fine with any driver
