### ISSUE TITLE
Portable version, please

### ISSUE THREAD

**Issue by nothingness6** [yuzu-emu/yuzu#11570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I love Yuzu, but my complaint is Yuzu is the only emulator that doesn't support portable version. Portable version is much easier to manage. Thus, I hope the dev team release the portable version soon. 
Thank you!

### Why would this feature be useful?

To manage the emulator easier and efficiently.

**Comment by SleepingSnakezzz** [comment]
I'm assuming you want this for Windows. Just download a manual build from https://yuzu-emu.org/downloads/, then extract it using winrar or 7zip, and create a folder called `user` in the same location as yuzu(.exe). That'll make yuzu store all of its user folders and the like in that `user` folder, making it completely portable.

**Comment by SleepingSnakezzz** [comment]
If this is what you were looking for, feel free to close the issue. If not, please elaborate a bit more on what you want :D

**Comment by nothingness6** [comment]
> I'm assuming you want this for Windows. Just download a manual build from https://yuzu-emu.org/downloads/, then extract it using winrar or 7zip, and create a folder called `user` in the same location as yuzu(.exe). That'll make yuzu store all of its user folders and the like in that `user` folder, making it completely portable.

Thanks for reply, but I'd like to install it on D drive, but Yuzu doesn't provide the option for it. That't the problem.

**Comment by SleepingSnakezzz** [comment]
If you're using the method I just explained to you, you can move that manual build, which you've turned into a portable build, to whatever drive you want.

**Comment by Norstyrm** [comment]
To make yuzu portable, create a folder called "user" in yuzu's installation directory, or download a build manually and create the "user" folder there. Note that auto-updating does not work with portable installs.

**Comment by Squall-Leonhart** [comment]
> Portable builds are manual builds. They don't automatically update. You need to download the latest version then replace the exe if you want to update.

This is not the case, the maintenance tool can update yuzu installs with the user folder in them just fine.

**Comment by german77** [comment]
It's not a recommended operation. If you hit repair it will delete the user folder with your saves and everything

**Comment by FearlessTobi** [comment]
You can already make yuzu portable with the method mentioned above.
If you want a different folder for your yuzu installation, then please open an issue in the installer repo: https://github.com/j-selby/liftinstall.
