### ISSUE TITLE
A7++ driver not working for One Pirate Warriors 4

### ISSUE THREAD

**Issue by tipentil** [yuzu-emu/yuzu#11584]
### Issue

My Device is POCO F4 GT (12/256 Snapdragon 8 gen 1). And i can't play OP pirate warriors 4 with any drivers. I have seen a lot youTube video with gameplay of the game (OP pirate warriors 4) and works well on Snapdragon 888 and below with mesa3d driver. I hope developers can fix this problem. I am very proud of you, this application really has great potential as the best Switch game emulator. good luck!

**Comment by t895** [comment]
Succeeded by #11585
