### ISSUE TITLE
Update Shin Megami Tensei V YUZU mod from 1.0.1 to 1.0.2 

### ISSUE THREAD

**Issue by YingDoge** [yuzu-emu/yuzu#11582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Update the Shin Megami Tensei V YUZU mods to the newest version (1.0.2). As the new verison of the update have a number of new feature like FOV change and many bug fixes. I can actully persoanlly pay the person (Sandvich_Hero, Pug O) 10 US dollar each if they can update this mod especially the ([2K Shadow Mod Collection](https://www.mediafire.com/file/f3dhlbob8gomv80/SMT_V_2k_Shadow_Collection.zip/file)). This is one of my faviourte game of all time i hope i can be played more enjoyble by more peope 

### Why would this feature be useful?

This can give people more enjoyable experince on Shin Megami Tensei V and many people have been requestions it.

**Comment by Squall-Leonhart** [comment]
This is a development repository for the emulator itself, not for the development of mods (barring the odd occasion a game needs a weird fix).

contact Sandvich_Hero, Pug O for the desired update (or an update on any coming)

**Comment by sakuramipha** [comment]
As mentioned already, we aren't the people in charge of updating mods. Please contact the mod creators to get them updated to the latest update version available.
