### ISSUE TITLE
[android] Xbox One Gamepad layout issue on emulated games

### ISSUE THREAD

**Issue by dannygaray60** [yuzu-emu/yuzu#11593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 2921a2426

### Description of Issue

I have noticed that on android when using xbox one gamepad, it keeps the same xbox layout with x,y,a,b buttons. But this hinders the original idea of the emulated game developer.

For example when jumping you use the B in switch which is the button at the bottom, but in xbox the B button is on the right.

I suggest to keep the same "positions" of the buttons as it affects the gameplay (and muscle memory) when using the buttons. Or at least give the possibility to remap the control manually.

### Expected Behavior

Maintain the same position of the buttons regardless of the type of control.

### Reproduction Steps

Use android playstore version. Connect Xbox one controller

### Log File

None

### System Configuration

CPU: Snapdragon 886
GPU/Driver: Snapdragon Adreno
RAM: 12gb
OS: Android 13

**Comment by KscireGamer** [comment]
May provide a button mapping configuration page for users to customize the button mapping.

**Comment by t895** [comment]
Solved by #13034
