### ISSUE TITLE
[Bug/request] The full screen resolution is not correct in both modes

### ISSUE THREAD

**Issue by boludoz** [yuzu-emu/yuzu#11598]
### Issue

For example:
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/7457786c-c4e0-4a47-a405-eb7309c5aaf4)

Exclusive full screen:
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/8a049889-b901-4f73-acff-71544436c46c)

![image](https://github.com/yuzu-emu/yuzu/assets/11653030/4a98731d-5e46-47ea-bc0c-1d0fb14b8bb3)

Borderless Windowed
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/44bc2649-32d9-4bd9-820f-f41102bac6dc)

![image](https://github.com/yuzu-emu/yuzu/assets/11653030/3dcc0f2c-3bf5-47d7-adbf-a44fc5798991)

The resolution must be 720x540 and not 1080p tested in RTX 3080, It was also tested by upscaling to 2k on a 4k monitor with RTX 1070.

Expected behavior at least in Full Screen Exclusive:
Let the emulator change the screen resolution to the correct one, otherwise the screen will always look like if you rescaled from 720p to 4k or 1080p.

**Comment by boludoz** [comment]
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/1b59e613-340d-4a82-9ab2-c28c5fcfa413)
I understand that it can be misinterpreted, but my recommendation is to leave only 720p instead of 720p/1080p, since in reality the resolution is 720p and the size of your monitor and so on for all modes.

**Comment by boludoz** [comment]
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/1d6a07a6-8c85-44bd-aa13-b76e03cb9cf3)
On my 4k monitor 1080p this this is actually 4k.

**Comment by boludoz** [comment]
Is the resolution will be dynamic?

**Comment by german77** [comment]
I see nothing wrong here. This game is 1080p on docked. 720p on handheld. This has nothing to do with full screen mode. You are probably confusing the setting. You can click on the bottom left text where it says docked/handheld to switch modes.

**Comment by german77** [comment]
As for resolution the description is correct. 1x is both 720p and 1080p it really depends on what the game native resolution is.

**Comment by boludoz** [comment]
> As for resolution the description is correct. 1x is both 720p and 1080p it really depends on what the game native resolution is.

No sir, that is not the bug.

**Comment by german77** [comment]
If you have performance issues with a rtx3080 and i5-8600K. I suspect your config is as bad as other issues I just closed. Since your build seemed to be a repack support won't be given.

Yuzu won't change your screen resolution. Just the game resolution. Any scaling artifact should be fixed by selecting the proper  window adapting filter.

**Comment by boludoz** [comment]
> If you have performance issues with a rtx3080 and i5-8600K. I suspect your config is as bad as other issues I just closed. Since your build seemed to be a repack support won't be given.
> 
> Yuzu won't change your screen resolution. Just the game resolution. Any scaling artifact should be fixed by selecting the proper window adapting filter.

I don't have performance problems, I just think your logic is wrong.

**Comment by boludoz** [comment]
@FernandoS27 You who are intelligent can understand what I try to say? Maybe it's a bit capcious but it's right, when you play a game the resolution is the one you choose within the game and not on the desk.

**Comment by boludoz** [comment]
There is no visual difference between using 720p/1080p and 4k.
