### ISSUE TITLE
YS X: Nordics infinite launch game

### ISSUE THREAD

**Issue by muhannad1991** [yuzu-emu/yuzu#11609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1568

### Description of Issue

The game remains in an infinite launching state
![yuzu 1568 _ 伊蘇X -北境歷險- (64-bit) _ 1 0 0 _ NVIDIA 27_09_2023 12_16_28 ص](https://github.com/yuzu-emu/yuzu/assets/54658174/727bb810-0bea-4310-be3b-76c86c1ada24)

### Expected Behavior

![yuzu Early Access 3897 _ 伊蘇X -北境歷險- (64-bit) _ 1 0 0 _ NVIDIA 26_09_2023 11_54_18 م](https://github.com/yuzu-emu/yuzu/assets/54658174/e96676d8-c348-4c94-9f08-d5033c2b9074)

### Reproduction Steps

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12732284/yuzu_log.txt)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12732269/yuzu_log.txt)
#

### System Configuration

CPU: I7 8700K 
GPU/Driver:RTX 2080 /537.42
RAM:16GB
OS:Windows 11

**Comment by gidoly** [comment]
We don't suppirt piracy

**Comment by muhannad1991** [comment]
? piracy ? I bought a game

**Comment by Squall-Leonhart** [comment]
> ? piracy ? I bought a game

you are loading games that you did not dump yourself into the games library,
