### ISSUE TITLE
Vulkan crashing at a specific point everytime

### ISSUE THREAD

**Issue by MaskedAarav** [yuzu-emu/yuzu#11607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1569

### Description of Issue

So I am trying to play Pokemon Let's Go Pikachu on Yuzu emulator with Vulkan.

After I select the language selection option, the game crashes without any information. If I try to use OpenGL, the screen goes black with only audio working and the controls also do not work. 

### Expected Behavior

Game continues to operate without any issue.

### Reproduction Steps

Vulkan
- Open Let's Go Pikachu ROM
- Select Handheld mode
- Intro Screen pops up. Select the language as English
- Game Crashes after this

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12729491/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel i5 7th Gen 7200U Cpu
GPU/Driver: Intel HD Graphics 620
RAM: 8 GB Ram
OS: Windows 11 Pro

**Comment by boludoz** [comment]
Try put accuracy in high. I want to know.

**Comment by MaskedAarav** [comment]
> Try put accuracy in high. I want to know.

No difference. It still closes. Also, I found this message while going through the log :- 

[ 718.041567] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame dimensions 1920x1080 don't match surface dimensions 1920x1088

Maybe this is the error causing all these problems. If it is so, please help me get rid of it.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12739448/yuzu_log.txt)

**Comment by boludoz** [comment]
C:/Users/franc/OneDrive/Documentos/GitHub/yuzu

**Comment by boludoz** [comment]
I don't think it's the problem but try to choose a lower resolution.

**Comment by Squall-Leonhart** [comment]
The HD 620 is not supported on Windows, intel have discontinued driver development for these barring security vulnerabilities.
