### ISSUE TITLE
Ys X Nordics Won't Boot

### ISSUE THREAD

**Issue by tesla2105** [yuzu-emu/yuzu#11624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA-3899

### Description of Issue

The game won't boot, it's stuck on the loading screen. 

### Expected Behavior

The game boots normally

### Reproduction Steps

Try to boot the game.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12744333/yuzu_log.txt)

### System Configuration

CPU: Intel Core i7 3770k
GPU/Driver: Nvidia GTX 1080 Driver ver. 536.23
RAM: Kingston HyperX Fury Beast DDR3 16GB 1866Mhz
OS: Windows 10 Pro version 22H2

**Comment by abelsunme** [comment]
Same situation on EA-3900 and stable 1570, game won't boot in those build versions.
Game boots right with EA-3879, there must be something changed between them.
