### ISSUE TITLE
yuzu crashing in Super Mario Odyssey

### ISSUE THREAD

**Issue by LolscopeDev2022** [yuzu-emu/yuzu#11629]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Mainline 1571

### Description of Issue

About a week ago after the update of emulator, yuzu keeps crushing everytime I press "Resume" in Main Menu (Super Mario Odyssey). Now I just can't continue playing this game normally.

### Expected Behavior

My game loads fine up to main menu. But when I press "Resume", my game crashes while downloading the save file. I've looked at log and saw that there are files missing for Network Interface or something like that.

### Reproduction Steps

Maybe you forget to include those necesarry files for Network Interface? Because I don't know how to explain this in any other way.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12750575/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 5 3550H
GPU/Driver: GTX 1050
RAM: 8 GB
OS: Windows 10

**Comment by german77** [comment]
Install the game update and try again

**Comment by FearlessTobi** [comment]
Author is unresponsive, closing.

**Comment by LolscopeDev2022** [comment]
I've updated the game, still same problem with Network Interface

**Comment by LolscopeDev2022** [comment]
> Install the game update and try again

I did it. Still same issue

**Comment by LolscopeDev2022** [comment]
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12784112/yuzu_log.txt.old.txt)


> Install the game update and try again

**Comment by LolscopeDev2022** [comment]
It finally got fixed!

**Comment by LolscopeDev2022** [comment]
> > It finally got fixed!
> 
> which version?

yuzu 1625 (PC version)
