### ISSUE TITLE
Android: Diablo II Resurrected GUI but no textures

### ISSUE THREAD

**Issue by Luzien12** [yuzu-emu/yuzu#11638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android-Build 2921a2426

### Description of Issue

The gui + sound is returned but in character creation no Figures + Backgrounds are shown. Same goes Ingame. 
![Screenshot_20230930_132142_yuzu](https://github.com/yuzu-emu/yuzu/assets/146541577/572a2583-faa3-45ec-841b-77016bbb0d68)

### Expected Behavior

Figure + Background rendering

### Reproduction Steps

Restart Tablet/ reinstall product keys + newest Firmware 16.1.0

### Log File

[yuzu_log_clipped.txt](https://github.com/yuzu-emu/yuzu/files/12774611/)

### System Configuration

Galaxy Tab S8+

CPU: Qualcomm Snapdragon 8 Gen 1 (SM8450)
GPU/Driver: system default
RAM: 8 GB 
OS: Android v13
Kernel Version 5.10.136-android 12-9-27102101-1bX800XXU5BWH6
Build Nr. TP1A.220624.014.X800XXu5BWH6
One UI-Version: 5.1.1

**Comment by kavmors** [comment]
the same issue on my Galaxy S23+. Any workaround ?

**Comment by WorstGit** [comment]
> the same issue on my Galaxy S23+. Any workaround ?

There is, It is something like L and - (button) in-game to set to vanilla graphics, not the updated Resurrected graphics. 
Game ran well 6+ months ago but haven't tested in a long while. 
I set the emulation speed to 50% for consistent frame pacing and to limit heating at that time
S22 Ultra, SD 8g1

**Comment by Gmentsik** [comment]
Works very well on 7a8a8b3f3 on v676.47 Qualcom driver. First few minutes 25fps, after that quite stable 30 on Rm8 pro, even on Balanced GPU Settings and Docked mode.

However, there are issues with lighting and semi-transparent things.

Also sometimes the Text and UI Elements get messed up (characters missing for instance)

![Screenshot_yuzu_2023-12-25-01-27-17-159](https://github.com/yuzu-emu/yuzu/assets/11612884/3c20d377-ca26-49fd-a01d-075ccb426a73)

**Comment by Gmentsik** [comment]
Here are some screenshots with some bugs present. In some environment the game is unplayable because of missing lights

![Screenshot_yuzu_2023-12-27-19-19-16-604](https://github.com/yuzu-emu/yuzu/assets/11612884/41261d14-c108-4d01-a3f1-af996a4f6023)

Missing Text in UI

![Screenshot_yuzu_2023-12-26-09-34-45-780](https://github.com/yuzu-emu/yuzu/assets/11612884/fadc32d2-4a7d-458c-9cc3-e9c1e25ee549)

**Comment by yusopbalilo** [comment]
Hi, can someone please fix the lightning issue in this game, or can someone please make a mod to fix the lightning same as the Dark Souls remastered, game is playable, but when you are in the cave its very hard to see
