### ISSUE TITLE
[Android] Digital Games Don't Work

### ISSUE THREAD

**Issue by TheAbsol359** [yuzu-emu/yuzu#11633]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Early Access 2921a2426

### Description of Issue

Digital games don't seem to work on yuzu while they do on Skyline. Games I've tried were Toree 3D and Angels with Scaly Wings.
![Screenshot_20230929_023242_yuzu](https://github.com/yuzu-emu/yuzu/assets/146418616/0f374ff9-8c20-4110-9cf8-6153f3dec089)
![Screenshot_20230926_221558](https://github.com/yuzu-emu/yuzu/assets/146418616/12140ba3-4ed2-4d96-a30f-7dc29dd9f007)

### Expected Behavior

Well, I think the expected behavior is that the games just work.

### Reproduction Steps

Simply launching it.

### Log File

[   0.013096] Frontend <Info> main/jni/native.cpp:RunEmulation:571: starting
[   0.013143] Frontend <Info> main/jni/emu_window/emu_window.cpp:EmuWindow_Android:64: initializing
[   0.013326] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.013341] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.013582] Config <Info> common/settings.cpp:LogSettings:110: yuzu Configuration:
[   0.013598] Config <Info> common/settings.cpp:operator():103: -- Audio.output_engine: auto
[   0.013601] Config <Info> common/settings.cpp:operator():103: -- Audio.output_device: auto
[   0.013602] Config <Info> common/settings.cpp:operator():103: -- Audio.input_device: auto
[   0.013605] Config <Info> common/settings.cpp:operator():103: -- Audio.volume: 100
[   0.013607] Config <Info> common/settings.cpp:operator():103: -- Audio.audio_muted: false
[   0.013608] Config <Info> common/settings.cpp:operator():103: -- Audio.dump_audio_commands: false
[   0.013610] Config <Info> common/settings.cpp:operator():103: -- Core.use_multi_core: true
[   0.013613] Config <Info> common/settings.cpp:operator():103: -- Core.memory_layout_mode: Memory_4Gb
[   0.013614] Config <Info> common/settings.cpp:operator():103: -- Core.use_speed_limit: true
[   0.013616] Config <Info> common/settings.cpp:operator():103: -- Core.speed_limit: 100
[   0.013619] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpu_accuracy: Auto
[   0.013621] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpu_debug_mode: false
[   0.013622] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_page_tables: true
[   0.013623] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_block_linking: true
[   0.013624] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_return_stack_buffer: true
[   0.013625] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_fast_dispatcher: true
[   0.013626] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_context_elimination: true
[   0.013627] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_const_prop: true
[   0.013628] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_misc_ir: true
[   0.013629] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_reduce_misalign_checks: true
[   0.013630] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_fastmem: true
[   0.013631] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_fastmem_exclusives: true
[   0.013632] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_recompile_exclusives: true
[   0.013633] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_ignore_memory_aborts: true
[   0.013635] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_unsafe_unfuse_fma: true
[   0.013636] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_unsafe_reduce_fp_error: true
[   0.013637] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_unsafe_ignore_standard_fpcr: true
[   0.013638] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_unsafe_inaccurate_nan: true
[   0.013639] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_unsafe_fastmem_check: true
[   0.013641] Config <Info> common/settings.cpp:operator():103: -- Cpu.cpuopt_unsafe_ignore_global_monitor: true
[   0.013644] Config <Info> common/settings.cpp:operator():103: -- Renderer.backend: Vulkan
[   0.013645] Config <Info> common/settings.cpp:operator():103: -- Renderer.shader_backend: Glsl
[   0.013647] Config <Info> common/settings.cpp:operator():103: -- Renderer.vulkan_device: 0
[   0.013648] Config <Info> common/settings.cpp:operator():103: -- Renderer.use_disk_shader_cache: true
[   0.013649] Config <Info> common/settings.cpp:operator():103: -- Renderer.use_asynchronous_gpu_emulation: true
[   0.013651] Config <Info> common/settings.cpp:operator():103: M- Renderer.accelerate_astc: Cpu
[   0.013653] Config <Info> common/settings.cpp:operator():103: M- Renderer.use_vsync: Immediate
[   0.013656] Config <Info> common/settings.cpp:operator():103: -- Renderer.nvdec_emulation: Gpu
[   0.013658] Config <Info> common/settings.cpp:operator():103: -- Renderer.fullscreen_mode: Exclusive
[   0.013660] Config <Info> common/settings.cpp:operator():103: -- Renderer.aspect_ratio: R16_9
[   0.013662] Config <Info> common/settings.cpp:operator():103: -- Renderer.resolution_setup: Res1X
[   0.013664] Config <Info> common/settings.cpp:operator():103: -- Renderer.scaling_filter: Bilinear
[   0.013666] Config <Info> common/settings.cpp:operator():103: -- Renderer.anti_aliasing: None
[   0.013668] Config <Info> common/settings.cpp:operator():103: -- Renderer.fsr_sharpening_slider: 25
[   0.013669] Config <Info> common/settings.cpp:operator():103: -- Renderer.bg_red: 0
[   0.013670] Config <Info> common/settings.cpp:operator():103: -- Renderer.bg_green: 0
[   0.013671] Config <Info> common/settings.cpp:operator():103: -- Renderer.bg_blue: 0
[   0.013674] Config <Info> common/settings.cpp:operator():103: M- Renderer.gpu_accuracy: Normal
[   0.013676] Config <Info> common/settings.cpp:operator():103: M- Renderer.max_anisotropy: Default
[   0.013678] Config <Info> common/settings.cpp:operator():103: -- Renderer.astc_recompression: Uncompressed
[   0.013679] Config <Info> common/settings.cpp:operator():103: M- Renderer.async_presentation: true
[   0.013680] Config <Info> common/settings.cpp:operator():103: M- Renderer.force_max_clock: true
[   0.013681] Config <Info> common/settings.cpp:operator():103: M- Renderer.use_reactive_flushing: false
[   0.013682] Config <Info> common/settings.cpp:operator():103: -- Renderer.use_asynchronous_shaders: false
[   0.013683] Config <Info> common/settings.cpp:operator():103: -- Renderer.use_fast_gpu_time: true
[   0.013684] Config <Info> common/settings.cpp:operator():103: -- Renderer.use_vulkan_driver_pipeline_cache: true
[   0.013688] Config <Info> common/settings.cpp:operator():103: -- Renderer.enable_compute_pipelines: false
[   0.013689] Config <Info> common/settings.cpp:operator():103: -- Renderer.use_video_framerate: false
[   0.013690] Config <Info> common/settings.cpp:operator():103: -- Renderer.barrier_feedback_loops: true
[   0.013691] Config <Info> common/settings.cpp:operator():103: -- Renderer.debug: false
[   0.013692] Config <Info> common/settings.cpp:operator():103: -- Renderer.shader_feedback: false
[   0.013693] Config <Info> common/settings.cpp:operator():103: -- Renderer.nsight_aftermath: false
[   0.013694] Config <Info> common/settings.cpp:operator():103: -- Renderer.disable_shader_loop_safety_checks: false
[   0.013695] Config <Info> common/settings.cpp:operator():103: -- Renderer.renderdoc_hotkey: false
[   0.013700] Config <Info> common/settings.cpp:operator():103: -- System.language_index: EnglishAmerican
[   0.013702] Config <Info> common/settings.cpp:operator():103: M- System.region_index: Taiwan
[   0.013706] Config <Info> common/settings.cpp:operator():103: -- System.time_zone_index: Auto
[   0.013707] Config <Info> common/settings.cpp:operator():103: -- System.custom_rtc_enabled: false
[   0.013708] Config <Info> common/settings.cpp:operator():103: -- System.custom_rtc: 0
[   0.013709] Config <Info> common/settings.cpp:operator():103: -- System.rng_seed_enabled: false
[   0.013710] Config <Info> common/settings.cpp:operator():103: -- System.rng_seed: 0
[   0.013711] Config <Info> common/settings.cpp:operator():103: -- System.device_name: yuzu
[   0.013712] Config <Info> common/settings.cpp:operator():103: -- System.current_user: 0
[   0.013715] Config <Info> common/settings.cpp:operator():103: M- System.use_docked_mode: Handheld
[   0.013718] Config <Info> common/settings.cpp:operator():103: -- System.sound_index: Stereo
[   0.013719] Config <Info> common/settings.cpp:operator():103: -- Data Storage.use_virtual_sd: true
[   0.013720] Config <Info> common/settings.cpp:operator():103: -- Data Storage.gamecard_inserted: false
[   0.013721] Config <Info> common/settings.cpp:operator():103: -- Data Storage.gamecard_current_game: false
[   0.013722] Config <Info> common/settings.cpp:operator():103: -- Data Storage.gamecard_path: 
[   0.013724] Config <Info> common/settings.cpp:operator():103: -- Debugging.use_gdbstub: false
[   0.013725] Config <Info> common/settings.cpp:operator():103: -- Debugging.gdbstub_port: 6543
[   0.013726] Config <Info> common/settings.cpp:operator():103: -- Debugging.program_args: 
[   0.013727] Config <Info> common/settings.cpp:operator():103: -- Debugging.dump_exefs: false
[   0.013728] Config <Info> common/settings.cpp:operator():103: -- Debugging.dump_nso: false
[   0.013729] Config <Info> common/settings.cpp:operator():103: -- Debugging.enable_fs_access_log: false
[   0.013730] Config <Info> common/settings.cpp:operator():103: -- Debugging.reporting_services: false
[   0.013731] Config <Info> common/settings.cpp:operator():103: -- Debugging.quest_flag: false
[   0.013732] Config <Info> common/settings.cpp:operator():103: -- Debugging.extended_logging: false
[   0.013734] Config <Info> common/settings.cpp:operator():103: -- Debugging.use_debug_asserts: false
[   0.013735] Config <Info> common/settings.cpp:operator():103: -- Debugging.use_auto_stub: false
[   0.013736] Config <Info> common/settings.cpp:operator():103: -- Debugging.enable_all_controllers: false
[   0.013737] Config <Info> common/settings.cpp:operator():103: -- Debugging.create_crash_dumps: false
[   0.013738] Config <Info> common/settings.cpp:operator():103: -- Debugging.perform_vulkan_check: true
[   0.013739] Config <Info> common/settings.cpp:operator():103: -- Debugging.dump_shaders: false
[   0.013740] Config <Info> common/settings.cpp:operator():103: -- Debugging.dump_macros: false
[   0.013741] Config <Info> common/settings.cpp:operator():103: -- Debugging.disable_macro_jit: false
[   0.013742] Config <Info> common/settings.cpp:operator():103: -- Debugging.disable_macro_hle: false
[   0.013744] Config <Info> common/settings.cpp:operator():103: -- Miscellaneous.log_filter: *:Info
[   0.013745] Config <Info> common/settings.cpp:operator():103: -- Miscellaneous.use_dev_keys: false
[   0.013747] Config <Info> common/settings.cpp:operator():103: -- Network.network_interface: 
[   0.013748] Config <Info> common/settings.cpp:operator():103: -- WebService.enable_telemetry: true
[   0.013750] Config <Info> common/settings.cpp:operator():103: -- WebService.web_api_url: https://api.yuzu-emu.org
[   0.013751] Config <Info> common/settings.cpp:operator():103: -- WebService.yuzu_username: 
[   0.013753] Config <Info> common/settings.cpp:operator():103: -- Controls.enable_raw_input: false
[   0.013754] Config <Info> common/settings.cpp:operator():103: -- Controls.controller_navigation: true
[   0.013755] Config <Info> common/settings.cpp:operator():103: -- Controls.enable_joycon_driver: true
[   0.013756] Config <Info> common/settings.cpp:operator():103: -- Controls.enable_procon_driver: false
[   0.013757] Config <Info> common/settings.cpp:operator():103: -- Controls.vibration_enabled: true
[   0.013758] Config <Info> common/settings.cpp:operator():103: -- Controls.enable_accurate_vibrations: false
[   0.013759] Config <Info> common/settings.cpp:operator():103: -- Controls.motion_enabled: true
[   0.013760] Config <Info> common/settings.cpp:operator():103: -- Controls.udp_input_servers: 127.0.0.1:26760
[   0.013761] Config <Info> common/settings.cpp:operator():103: -- Controls.enable_udp_controller: false
[   0.013762] Config <Info> common/settings.cpp:operator():103: -- Controls.pause_tas_on_load: true
[   0.013762] Config <Info> common/settings.cpp:operator():103: -- Controls.tas_enable: false
[   0.013764] Config <Info> common/settings.cpp:operator():103: -- Controls.tas_loop: false
[   0.013765] Config <Info> common/settings.cpp:operator():103: -- Controls.mouse_panning: false
[   0.013766] Config <Info> common/settings.cpp:operator():103: -- Controls.mouse_panning_sensitivity: 50
[   0.013767] Config <Info> common/settings.cpp:operator():103: -- Controls.mouse_enabled: false
[   0.013768] Config <Info> common/settings.cpp:operator():103: -- Controls.mouse_panning_x_sensitivity: 50
[   0.013769] Config <Info> common/settings.cpp:operator():103: -- Controls.mouse_panning_y_sensitivity: 50
[   0.013770] Config <Info> common/settings.cpp:operator():103: -- Controls.mouse_panning_deadzone_counterweight: 20
[   0.013772] Config <Info> common/settings.cpp:operator():103: -- Controls.mouse_panning_decay_strength: 18
[   0.013773] Config <Info> common/settings.cpp:operator():103: -- Controls.mouse_panning_min_decay: 6
[   0.013774] Config <Info> common/settings.cpp:operator():103: -- Controls.emulate_analog_keyboard: false
[   0.013777] Config <Info> common/settings.cpp:operator():103: -- Controls.keyboard_enabled: false
[   0.013778] Config <Info> common/settings.cpp:operator():103: -- Controls.debug_pad_enabled: false
[   0.013780] Config <Info> common/settings.cpp:operator():103: -- Controls.touch_device: min_x:100,min_y:50,max_x:1800,max_y:850
[   0.013781] Config <Info> common/settings.cpp:operator():103: -- Controls.touch_from_button_map: 0
[   0.013782] Config <Info> common/settings.cpp:operator():103: -- Controls.enable_ring_controller: true
[   0.013783] Config <Info> common/settings.cpp:operator():103: -- Controls.enable_ir_sensor: false
[   0.013784] Config <Info> common/settings.cpp:operator():103: -- Controls.ir_sensor_device: auto
[   0.013785] Config <Info> common/settings.cpp:operator():103: -- Controls.random_amiibo_id: false
[   0.013788] Config <Info> common/settings.cpp:operator():107: DataStorage_CacheDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu.ea/files/cache
[   0.013789] Config <Info> common/settings.cpp:operator():107: DataStorage_ConfigDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu.ea/files/config
[   0.013791] Config <Info> common/settings.cpp:operator():107: DataStorage_LoadDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu.ea/files/load
[   0.013793] Config <Info> common/settings.cpp:operator():107: DataStorage_NANDDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu.ea/files/nand
[   0.013795] Config <Info> common/settings.cpp:operator():107: DataStorage_SDMCDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu.ea/files/sdmc
[   0.013916] Input <Error> ./common/input.h:CreateDevice:510: Unknown engine name: joycon
[   0.015119] Input <Error> ./common/input.h:CreateDevice:510: Unknown engine name: joycon
[   0.235226] Loader <Error> core/file_sys/content_archive.cpp:NCA:90: File reader errored out during read of section 1: 0x1f8c02
[   0.606268] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:918: Device doesn't support extension VK_EXT_conservative_rasterization
[   0.606280] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:918: Device doesn't support extension VK_EXT_depth_range_unrestricted
[   0.606282] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:918: Device doesn't support extension VK_NV_geometry_shader_passthrough
[   0.606284] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:918: Device doesn't support extension VK_NV_viewport_array2
[   0.606285] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:918: Device doesn't support extension VK_NV_viewport_swizzle
[   0.606291] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:980: Device doesn't support feature shaderInt8
[   0.606293] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:981: Missing required feature uniformAndStorageBuffer16BitAccess
[   0.606293] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:981: Missing required feature storageBuffer8BitAccess
[   0.606294] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:981: Missing required feature uniformAndStorageBuffer8BitAccess
[   0.606295] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:981: Missing required feature wideLines
[   0.606298] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:RemoveExtensionFeatureIfUnsuitable:377: Removing features for unsuitable extension VK_EXT_provoking_vertex
[   0.606302] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:405: Unsuitable driver, continuing anyway
[   0.606385] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:452: Qualcomm and Turnip drivers have broken VK_EXT_custom_border_color
[   0.764521] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:159: Driver: turnip Mesa driver 23.2.99
[   0.764531] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:160: Device: Turnip Adreno (TM) 650
[   0.764533] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:161: Vulkan: 1.3.261
[   0.764542] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:162: Available VRAM: 4.00 GiB
[   1.052534] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:87: Auto-selecting the cubeb backend
[   1.295233] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:87: Auto-selecting the cubeb backend
[   1.312547] Loader <Info> core/loader/nca.cpp:Load:53: No ExeFS found in NCA, looking for ExeFS from update
[   1.312586] Core <Critical> core/core.cpp:Load:329: Failed to load ROM (Error 26)!

### System Configuration

CPU: Octa-core (1x3.0 GHz Kryo 585 & 3x2.42 GHz Cortex-A77 & 4x1.80 GHz Cortex-A55) - USA
GPU/Driver: Adreno 650 - USA/No Driver Works
RAM: 12GB
OS: Android 13

**Comment by Corrupted346** [comment]
Can I reply here? I have an Issue installing Yuzu on my phone :

![IMG_20230928_171359.jpg](https://github.com/yuzu-emu/yuzu/assets/146454875/013c5100-4934-43fa-af8d-9b1a730b7df1)

Device :

Xiaomi Redmi 8 
Adreno 505 Snapdragon 439
4GB RAM 
64GB ROM


Please help me😭

**Comment by FearlessTobi** [comment]
@TheAbsol359 How exactly did you dump your game?

**Comment by TheAbsol359** [comment]
@FearlessTobi Same way I dumped my physical games. Someone told me to keep the games and updates as separate times, but I did. I redumped them anyway because I wasn't sure, but they just don't work.

**Comment by liamwhite** [comment]
Your dump options are stripping the ExeFS out of the files in your NSP-type dumps. Presumably this isn't happening for the XCI-type dumps because it doesn't tamper with the contents.

**Comment by TheAbsol359** [comment]
@liamwhite I looked at NXDumpTool and I didn't see any options for that. I asked in the NXDumpTool server for some clarification and DarkMatterCore said NXDumpTool doesn't do that.

**Comment by TheAbsol359** [comment]
@liamwhite This is what my settings look like.
![2023092919591000-DB1426D1DFD034027CECDE9C2DD914B8](https://github.com/yuzu-emu/yuzu/assets/146418616/8afae4fd-0fb9-4ac4-bebf-5a4dd6f16f06)
![2023092919591600-DB1426D1DFD034027CECDE9C2DD914B8](https://github.com/yuzu-emu/yuzu/assets/146418616/b7546911-0c27-4050-a155-303c83603ca3)

**Comment by TheAbsol359** [comment]
Generating a ticket less dump worked, but I think this is still technically a problem.
![Screenshot_20230929_205142_yuzu](https://github.com/yuzu-emu/yuzu/assets/146418616/e318e9e0-9f56-441d-9ec9-891f2eec12a5)

**Comment by liamwhite** [comment]
That is interesting. I loaded a fresh install of yuzu android with:
- latest keys from my console generated with lockpick_rcm 1.9.10
- a fresh dump of an eshop title with "remove console-specific data" unset

and did not encounter any parsing errors.

**Comment by Pergmen** [comment]
I had an issue like this with an Eshop title. I fixed it by entering the file system and manually placing the keys like I would on desktop

**Comment by TheAbsol359** [comment]
Digital games seem to work without issue now. I'm closing the issue.
