### ISSUE TITLE
Cocoon freezes with a black screen before rendering anything 

### ISSUE THREAD

**Issue by pacoa-kdbg** [yuzu-emu/yuzu#11641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3905

### Description of Issue

After booting the game, the fps counter goes directly to 0 fps, and nothing renders.

Execution has to be stopped manually.

### Expected Behavior

Renders something 

### Reproduction Steps

Start the game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12775487/yuzu_log.txt)

### System Configuration

CPU: 3900X
GPU/Driver: RTX 3080
RAM: 16GB
OS: Windows 11

**Comment by Squall-Leonhart** [comment]
this title made windows firewall popup, even with network disabled, might be stuck waiting for a server reply

**Comment by pacoa-kdbg** [comment]
Can it be bypassed somehow ?

**Comment by mjd180** [comment]
Looks like a missing services problem (both Vulkan & OpenGL):

_Translate TXQ (b): Mode 2 is not implemented
Translate F2F (reg): F2F CC is not implemented
Translate ISBERD: O is not implemented_

**Comment by cristian64** [comment]
It seems yuzu 20230702 (95ceae40e) gets the game to start:

<img src="https://github.com/yuzu-emu/yuzu/assets/1853278/8a94e771-c95f-4787-a3d2-f97fb8cde93b" alt="Cocoon in yuzu (1)" title="Cocoon in yuzu (1)" width="360"/>

<img src="https://github.com/yuzu-emu/yuzu/assets/1853278/d5d74843-4552-4259-8456-5d11300ee213" alt="Cocoon in yuzu (1)" title="Cocoon in yuzu (1)" width="360"/>

More recent versions show a black screen. I have not tried to bisect when yuzu regressed.

**Comment by pacoa-kdbg** [comment]
Solved on latest mainline
