### ISSUE TITLE
Sea of Stars Not Launching

### ISSUE THREAD

**Issue by nickkeane** [yuzu-emu/yuzu#11643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3905

### Description of Issue

Screen stuck looping on 'Launching...', Execution Error raised in Log.

### Expected Behavior

Program is loaded and gets past "Launching..." screen

### Reproduction Steps

1. Launch Sea of Stars in Yuzu
2. See continuous Yuzu loading screen

### Log File

https://pastebin.com/6y3yVAzC

### System Configuration

CPU: Intel i7 13700HX
GPU/Driver: nVidia RTX 4060 Laptop
RAM: 32 GB
OS: Win 11 Pro

**Comment by Squall-Leonhart** [comment]
Verify your dump, this game is known working.

**Comment by FearlessTobi** [comment]
Very likely caused by a corrupt dump.
