### ISSUE TITLE
Add Option to view build id og games 

### ISSUE THREAD

**Issue by neoragna** [yuzu-emu/yuzu#11661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Please if possible add an option to view the build id of your switch games to the Android version of yuzu als if you can add an option like the free cheat option on dstwo flash cart for nds that allows users to search and edit memory for games to nake cheats

### Why would this feature be useful?

It would be helpful in adding and making new cheats  for switch

**Comment by FearlessTobi** [comment]
I am unsure what you mean by build id.
Also I don't understand the second request.

Since this seems unrelated to the first one, it should probably be its own issue anyway.
