### ISSUE TITLE
Xenoblade Chronicles: Definitive Edition - Graphic artifacts

### ISSUE THREAD

**Issue by LoneWolf31589** [yuzu-emu/yuzu#11680]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Mainline 1577

### Description of Issue

Graphic artifacts instead of grass on the leg of bionis. Only when using OpenGL with GLASM shader. Vulcan does not work on a driver older than 512.95.

### Expected Behavior

![0100ff500e34a000_2023-10-04_17-47-49-300](https://github.com/yuzu-emu/yuzu/assets/90130977/297902fb-11a0-4955-842a-79fadc05e6ca)
![0100ff500e34a000_2023-10-04_17-48-04-034](https://github.com/yuzu-emu/yuzu/assets/90130977/e0da5118-982b-4191-901b-711e6a460be3)

### Reproduction Steps

Use OpenGL with GLASM shaders. Location - for example, the Leg of Bionis.

### Log File

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/12804796/yuzu_log.zip)

### System Configuration

CPU: i7 9700F
GPU/Driver: GTX970, Driver 537.54
RAM: 32GB
OS: Windows 10 X64

**Comment by LoneWolf31589** [comment]
Mainline 1592.
The problem is still there. The version of the video driver does not affect anything. The problem is in Yuzu, when using GLASM shaders.
![0100ff500e34a000_2023-10-18_23-08-37-142](https://github.com/yuzu-emu/yuzu/assets/90130977/cd6e2d2a-ade4-4a3b-9275-aa891cdad8ec)

**Comment by Squall-Leonhart** [comment]
Downgrade driver and use vulkan
