### ISSUE TITLE
Android: Sharp Aquos R5G Overlay Broken(Device-Specific)

### ISSUE THREAD

**Issue by sharpy66** [yuzu-emu/yuzu#11682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android Mainline 2921a2426

### Description of Issue

![Screenshot_-](https://github.com/yuzu-emu/yuzu/assets/40325290/02c98d78-a8a4-41fa-b1ea-6ccb6c8ca450)

Control overlay stretched horizontally - R and ZR buttons missing.

### Expected Behavior

All buttons should be visible
![Screenshot_20231004_105111_yuzu](https://github.com/yuzu-emu/yuzu/assets/40325290/cd27f1ea-3772-4798-be6b-aa4e6b76d973)

### Reproduction Steps

N/A

### Log File

N/A

### System Configuration

CPU: Snapdragon 865
GPU/Driver: Adreno 650
RAM: 12GB
OS: Android 12

**Comment by t895** [comment]
I had confirmation that the fix was to restart the device
