### ISSUE TITLE
[Bug] Strings canonicalization

### ISSUE THREAD

**Issue by boludoz** [yuzu-emu/yuzu#11692]
It's unclear to what exact functionality this comment relates since it's at top of the file rather than attached to any specific code. Besides, it appears to be unrelated to overall changes of this PR? Might be better as an issue report, assuming this indeed causes issues in practice.

(Also, I presume cannon was supposed to refer to the process of Canonicalization? Don't shoot the utf8-encoded message...)

_Originally posted by @v1993 in https://github.com/yuzu-emu/yuzu/pull/11665#discussion_r1346907145_

**Comment by boludoz** [comment]
When we convert a string to another type literally, for example from u8string to wstring, the character is corrupted. Windows provides a native solution to this problem, C++ also does it but it is outdated, the ideal would be to add a specialized library or use the C++ solution. This can be problematic for the file system.

**Comment by v1993** [comment]
But there are no string conversions done on non-windows systems since everything uses UTF-8 anyways? It's less like windows provides a solution and more like other systems don't provide a problem.

**Comment by boludoz** [comment]
> But there are no string conversions done on non-windows systems since everything uses UTF-8 anyways? It's less like windows provides a solution and more like other systems don't provide a problem.

You've asked me to open it as a problem, and it really is and I think it's not just Windows.

**Comment by v1993** [comment]
I've noted that your original comment appears to be unrelated to PR's goal, is unclear to problem in what exact code it refers, and, *assuming it's indeed an existing problem*, would be better as a separate issue *with a proper explanation and ideally a test case*; parts in *italics* not explicitly written but implied.

In the meantime, this issue report is still just your suspicion that some FS code has some sort of problem with UTF-8 handling because of string conversions that do not, to my knowledge, actually happen - file name encodings are almost never a pain point outside of windows (which has to deal with historically adopting UTF-16 with UTF-8 ending up used in most of technology instead). I'd be happy to accept my wrongness if you actually provided an example where encoding-related issues occur with current FS implementation.

Finally, applying canonicalization is unlikely to fix any problems potentially introduced by encoding conversions, since those would most likely produce canonical versions of strings anyways. Actually, *that* theoretically could introduce problems if user somehow managed to create a filename with non-canonicalized characters in it, but canonicalizing post-conversion filename would not help at all and most likely be a no-op by that point.

**Comment by boludoz** [comment]
> I've noted that your original comment appears to be unrelated to PR's goal, is unclear to problem in what exact code it refers, and, _assuming it's indeed an existing problem_, would be better as a separate issue _with a proper explanation and ideally a test case_; parts in _italics_ not explicitly written but implied.
> 
> In the meantime, this issue report is still just your suspicion that some FS code has some sort of problem with UTF-8 handling because of string conversions that do not, to my knowledge, actually happen - file name encodings are almost never a pain point outside of windows (which has to deal with historically adopting UTF-16 with UTF-8 ending up used in most of technology instead). I'd be happy to accept my wrongness if you actually provided an example where encoding-related issues occur with current FS implementation.
> 
> Finally, applying canonicalization is unlikely to fix any problems potentially introduced by encoding conversions, since those would most likely produce canonical versions of strings anyways. Actually, _that_ theoretically could introduce problems if user somehow managed to create a filename with non-canonicalized characters in it, but canonicalizing post-conversion filename would not help at all and most likely be a no-op by that point.

Ok, so this bug only happens on Windows?

**Comment by boludoz** [comment]
> I've noted that your original comment appears to be unrelated to PR's goal, is unclear to problem in what exact code it refers, and, _assuming it's indeed an existing problem_, would be better as a separate issue _with a proper explanation and ideally a test case_; parts in _italics_ not explicitly written but implied.
> 
> In the meantime, this issue report is still just your suspicion that some FS code has some sort of problem with UTF-8 handling because of string conversions that do not, to my knowledge, actually happen - file name encodings are almost never a pain point outside of windows (which has to deal with historically adopting UTF-16 with UTF-8 ending up used in most of technology instead). I'd be happy to accept my wrongness if you actually provided an example where encoding-related issues occur with current FS implementation.
> 
> Finally, applying canonicalization is unlikely to fix any problems potentially introduced by encoding conversions, since those would most likely produce canonical versions of strings anyways. Actually, _that_ theoretically could introduce problems if user somehow managed to create a filename with non-canonicalized characters in it, but canonicalizing post-conversion filename would not help at all and most likely be a no-op by that point.

std::wstring is UTF-16?

**Comment by boludoz** [comment]
I think the problem is only serious if we try to convert a UTF-8 u8string variable to a UTF-16 fixed Wstring.

**Comment by boludoz** [comment]
```
#include <iostream>
#include <string>
#include <filesystem>
#include <fstream>
#include <locale>
#include <codecvt>

using namespace std;
using namespace std::filesystem;

std::wstring ToWString(std::u8string_view utf8_string) {
    std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
    return converter.from_bytes(reinterpret_cast<const char*>(utf8_string.data()));
}

std::u8string ToU8String(std::wstring_view w_string) {
    return std::u8string{reinterpret_cast<const char8_t*>(w_string.data())};
}

int main() {

    // That dont works - ws to u8s
    wstring filenamew = L"😒1.txt";
    u8string filenameu8 = std::u8string{begin(filenamew), end(filenamew)};
    path p = current_path() / filenameu8;
    ofstream(p) << "Test 1!\n";

    // That print "ð.txt" invalid file - u8s to ws
    u8string filenameu8_2 = u8"😒2.txt";
    wstring filenamew_2 = std::wstring{begin(filenameu8_2), end(filenameu8_2)};
    path p_2 = current_path() / filenamew_2;
    ofstream(p_2) << "Test 2!\n";

    // That is ok - u8s to ws
    u8string filenameu8_3 = u8"😒3.txt";
    wstring filenamew_3 = ToWString(filenameu8_3);
    path p_3 = current_path() / filenamew_3;
    ofstream(p_3) << "Test 3!\n";

    // That is ok - ws to u8s
    wstring filenamew_4 = L"😒4.txt";
    u8string filenameu8_4 = ToU8String(filenamew_4);
    path p_4 = current_path() / filenameu8_4;
    ofstream(p_4) << "Test 4!\n";

    return 0;
}
```

**Comment by boludoz** [comment]
```
#include <iostream>
#include <string>
#include <filesystem>
#include <fstream>
#include <locale>
#include <codecvt>

using namespace std;
using namespace std::filesystem;

std::wstring ToWString(std::u8string_view utf8_string) {
    std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
    return converter.from_bytes(reinterpret_cast<const char*>(utf8_string.data()));
}

std::u8string ToU8String(std::wstring_view w_string) {
    std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
    std::string utf8_string = converter.to_bytes(w_string.data(), w_string.data() + w_string.size());
    return std::u8string(utf8_string.begin(), utf8_string.end());
}

int main() {

    // That dont works - ws to u8s
    wstring filenamew = L"😒1.txt";
    u8string filenameu8 = std::u8string{begin(filenamew), end(filenamew)};
    path p = current_path() / filenameu8;
    ofstream(p) << "Test 1!\n";

    // That print "ð.txt" invalid file - u8s to ws
    u8string filenameu8_2 = u8"😒2.txt";
    wstring filenamew_2 = std::wstring{begin(filenameu8_2), end(filenameu8_2)};
    path p_2 = current_path() / filenamew_2;
    ofstream(p_2) << "Test 2!\n";

    // That is ok - u8s to ws
    u8string filenameu8_3 = u8"😒3.txt";
    wstring filenamew_3 = ToWString(filenameu8_3);
    path p_3 = current_path() / filenamew_3;
    ofstream(p_3) << "Test 3!\n";

    // That is ok - ws to u8s
    wstring filenamew_4 = L"😒4.txt";
    u8string filenameu8_4 = ToU8String(filenamew_4);
    path p_4 = current_path() / filenameu8_4;
    ofstream(p_4) << "Test 4!\n";

    return 0;
}
```

**Comment by v1993** [comment]
That is an improvement - but wstring is most likely not even used on non-windows platforms by yuzu fs code. This also has nothing to do with canonicalization.

**Comment by Kelebek1** [comment]
We shouldn't be using those functions for Windows, we use MultiByteToWideChar: https://github.com/yuzu-emu/yuzu/blob/master/src/common/string_util.cpp#L139-L178

**Comment by boludoz** [comment]
> That is an improvement - but wstring is most likely not even used on non-windows platforms by yuzu fs code. This also has nothing to do with canonicalization.

Exactly, it doesn't make sense beyond Windows. The Windows API is handled in UTF-16.

**Comment by boludoz** [comment]
> We shouldn't be using those functions for Windows, we use MultiByteToWideChar/WideCharToMultiByte: https://github.com/yuzu-emu/yuzu/blob/master/src/common/string_util.cpp#L139-L178 are these functions not working correctly?

Yes, but it is always better to find a cross-platform solution.

**Comment by v1993** [comment]
Then I have to ask you to explain what the entire issue is about, because it's borderline impossible to figure it out (and title does not even begin to relate to it). Is fine name handling of yuzu not working right? If so, is that on windows or outside of it? Is it because of using wstring outside of windows? Are you simply dissatisfied with windows having special handling compared to other platforms?

**Comment by boludoz** [comment]
> Then I have to ask you to explain what the entire issue is about, because it's borderline impossible to figure it out (and title does not even begin to relate to it). Is fine name handling of yuzu not working right? If so, is that on windows or outside of it? Is it because of using wstring outside of windows? Are you simply dissatisfied with windows having special handling compared to other platforms?

Yes sir, just that.

**Comment by boludoz** [comment]
Thanks for the explanation, now I understand a little more how this works, I will propose a cross-platform solution using boost locale.

**Comment by boludoz** [comment]
> Then I have to ask you to explain what the entire issue is about, because it's borderline impossible to figure it out (and title does not even begin to relate to it). Is fine name handling of yuzu not working right? If so, is that on windows or outside of it? Is it because of using wstring outside of windows? Are you simply dissatisfied with windows having special handling compared to other platforms?

```
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

#ifdef _WIN32
#include <windows.h>
#endif

int main() {

#ifdef _WIN32
  SetConsoleOutputCP(CP_UTF8);
#endif

  std::string content = "Hello Word 😃";
  std::filesystem::path current_dir = std::filesystem::current_path();

  std::filesystem::path file_path = current_dir / u8"Hello 😃.txt";
  std::ofstream file(file_path, std::ios::binary);
  if (!file.is_open())
    return 1;

  std::cout << content << std::endl;

  file.write(content.c_str(), content.size());
  file.close();
  return 0;
}
```

I think it's too complicated for me, sir, it's simpler than it seems.

Here I show you the tests on Linux and Windows, that works well for both systems.

Windows Subsystem for Linux
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/96d7adf1-aa8a-4643-8397-76cd2c7eeca6)

Clang Windows:
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/1a9da4a1-a567-4a98-89f7-791258792b14)

**Comment by boludoz** [comment]
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/355134c2-2cd8-441c-8721-284cc3e3380c)

**Comment by boludoz** [comment]
```
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

#ifdef _WIN32
#include <windows.h>
#endif

int main() {

#ifdef _WIN32
  SetConsoleOutputCP(CP_UTF8);
#endif

  std::string content = "Hello Word 😃";
  std::filesystem::path current_dir = std::filesystem::current_path();

  std::filesystem::path file_path = current_dir / u8"Hello 😃.txt";
//   std::ofstream file(file_path, std::ios::binary);
//   if (!file.is_open())
//     return 1;

//   std::cout << content << std::endl;

//   file.write(content.c_str(), content.size());
//   file.close();

    std::ofstream shortcut_stream(content);
    if (!shortcut_stream.is_open()) {
        return 1;
    }
    shortcut_stream << content;
    shortcut_stream.close();

  return 0;
}
```

![image](https://github.com/yuzu-emu/yuzu/assets/11653030/c4dcb81e-5527-4e50-b351-60cfc8401f97)

As we see here, not all functions are designed for this new standard.
