### ISSUE TITLE
Pinball FX3 screen stretches vertically to the extreme

### ISSUE THREAD

**Issue by krisring** [yuzu-emu/yuzu#11698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1538

### Description of Issue

When running Pinball FX3 - when you get to the main menu or if you are able to load a table then the image of the table is extremely vertically stretched making the game unplayale.

### Expected Behavior

When you load into the main menu - the game display should be contained vertically and horizontally inside of the app window

### Reproduction Steps

Simply run the game - with or without updates and with or without DLC and it happens.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12837134/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5900X
GPU/Driver: GeForce RTX 3090
RAM: 32GB
OS: Win11

**Comment by krisring** [comment]
Screencap of the issue:

![image](https://github.com/yuzu-emu/yuzu/assets/3709662/967f35d0-6977-4b23-89dd-a1b1ca1fcb54)

**Comment by krisring** [comment]
Thank you for any suggestions for a fix or any efforts that it may take to the code to fix :)

**Comment by Squall-Leonhart** [comment]
This is already fixed in EA/Master

**Comment by krisring** [comment]
Ah! Lovely! Thank you!
