### ISSUE TITLE
Weird shadow/flicker effect in Zelda TOTK

### ISSUE THREAD

**Issue by Charliviv97** [yuzu-emu/yuzu#11717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3914

### Description of Issue

When updating Yuzu EA from version 3913 to 3914, some shadows seem to have been broken (at least in Zelda TOTK), I have played in the mainline version and even in EA 3913 to confirm that this error appears only in the latest version of Yuzu EA.

![Yuzu EA delante](https://github.com/yuzu-emu/yuzu/assets/146231126/97254f71-0b45-4075-8a3e-d3a2be54afea)
![Yuzu EA por detras](https://github.com/yuzu-emu/yuzu/assets/146231126/c47c13e2-4480-4091-af94-bda341331598)

### Expected Behavior

Expected behavior from Yuzu Mainline:

![Yuzu por delante](https://github.com/yuzu-emu/yuzu/assets/146231126/8947fea6-2b95-4799-a9e4-428f395216eb)
![Yuzu por detras](https://github.com/yuzu-emu/yuzu/assets/146231126/0268520d-751f-4ccd-b042-cb7620a771b6)

### Reproduction Steps

If you go to the water temple and fly a little you can see the same problem with shadow flickering included.

### Log File

**log file removed by moderator**

### System Configuration

CPU: Ryzen 9 5950X
GPU/Driver: RX7900XT w/ Adrenalin 23.30.01.02
RAM: 128Gb
OS: Windows 11

**Comment by Squall-Leonhart** [comment]
you have multiple graphic mods that are long outdated due to replacement by other mods or issue being resolved from the emulators side.

**Comment by Squall-Leonhart** [comment]
It won't be an issue in 3915

**Comment by SleepingSnakezzz** [comment]
We do not support piracy. Please dump your game from your own Nintendo Switch using your quickstartguide: https://yuzu-emu.org/help/quickstart/
