### ISSUE TITLE
[Request] Allow to load edited mod files when stopping game with F5

### ISSUE THREAD

**Issue by Waikuteru** [yuzu-emu/yuzu#11724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It would be nice if stopping the game with F5 makes it so that you can edit loaded mod files instead of having to restart the emulator. Yuzu seems to still use the game and/or its loaded mod files pressing F5 so you can't make changes to the files unless you restart.

### Why would this feature be useful?

Faster mod development.

**Comment by liamwhite** [comment]
@Waikuteru Can you confirm that this is fixed in EA 3932+?

**Comment by Waikuteru** [comment]
Yes, this works now! Awesome, this makes mod development even more convenient! Thanks!
