### ISSUE TITLE
TOTK crash on start up after update to ML 1582

### ISSUE THREAD

**Issue by nocnoc94** [yuzu-emu/yuzu#11738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1582

### Description of Issue

After updating to 1582, TOTK crashes after the launching screen. However all other games (MK8, M:O, Katamari) run fine.

I've tried disabling all my mods and deleting the shader cache but it still crashes.

### Expected Behavior

That the game launches fine like it did earlier today before the yuzu update.

### Reproduction Steps

1. Launch game
2. Get error that application has crashed

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12859862/yuzu_log.txt)
[inxi.txt](https://github.com/yuzu-emu/yuzu/files/12859871/inxi.txt)

### System Configuration

CPU: Intel Core i7-8750H
GPU/Driver: GeForce RTX 2070 Mobile 535.113.01
RAM: 32GB
OS: Fedora 38 Workstation
Kernel: 6.5.6-200.fc38.x86_64

**Comment by liamwhite** [comment]
I am unable to reproduce this with mainline 1582 or mainline 1583 (released today).

Can you provide a save file you believe to be affected by the issue?
Does it work when you try an appimage build of an older version known to be unaffected, like 1570?

**Comment by liamwhite** [comment]
The issue is specific to Flatpak and doesn't occur with the AppImage releases. I am debugging now.

**Comment by X6B** [comment]
I can´t launch it either. Super Mario Odissey crashes too.

`/usr/include/c++/13.2.1/span:282: constexpr std::span<_Type, _Extent>::element_type& std::span<_Type, _Extent>::operator[](size_type) const [with _Type = const unsigned char; long unsigned int _Extent = 18446744073709551615; reference = const unsigned char&; size_type = long unsigned int]: Assertion '__idx < size()' failed.
`

I've tried 1582 and 1583 on Linux / RDNA2 card / Mesa 23.2.1 / RADV.

**Comment by X6B** [comment]
1584 is fine.

**Comment by nocnoc94** [comment]
> 1584 is fine.

Ditto, TOTK opens fine on 1584 flatpak. Thanks for the help!

**Comment by Squall-Leonhart** [comment]
my bad guys, i'm still learning the different parameters and stuff.
