### ISSUE TITLE
Desktop shortcut not work

### ISSUE THREAD

**Issue by DanielSvoboda** [yuzu-emu/yuzu#11737]
### Issue

This PR https://github.com/yuzu-emu/yuzu/pull/11705 (Add desktop shortcut support for Windows) presents this error:

![image](https://github.com/yuzu-emu/yuzu/assets/28203966/7b213fc4-4604-47ba-b5d5-40015885215f)
This error happens if I modify my desktop location. Because my desktop is on another unit.
In my version (https://github.com/yuzu-emu/yuzu/compare/master...DanielSvoboda:yuzu:shortcut) I used this code below.

```c++
WCHAR path[MAX_PATH];
SHGetFolderPath(NULL, CSIDL_DESKTOPDIRECTORY, NULL, SHGFP_TYPE_CURRENT, path);
target_directory = path;
```

The code currently has this part:
```c++
target_directory = home_path / "Desktop";
```
  That won't work in Brazil or any other place where the Desktop is not called 'Desktop', here it is called 'Área de Trabalho'.

It is necessary to make some adjustments to the current code remembering the existence of the character 'Á'.

**Comment by german77** [comment]
Seems like this function is windows only. Let me research for one that works on both windows and linux systems

**Comment by DanielSvoboda** [comment]
Yes, this code I shared takes the correct desktop directory without needing ( / "Desktop" ) but it is only for Windows. This code below I believe will work in Linux, I have no way of testing it at the moment...

```c++
#include <cstdlib>
#include <iostream>
#include <array>

std::string getDesktopPath() {
    std::array<char, 128> buffer;
    std::string result;
    FILE* pipe = popen("xdg-user-dir DESKTOP", "r");
    if (!pipe) throw std::runtime_error("popen() failed!");
    while (fgets(buffer.data(), 128, pipe) != nullptr) {
        result += buffer.data();
    }
    auto returnCode = pclose(pipe);
    return result;
}
```

**Comment by v1993** [comment]
@german77 Qt code can use [`QStandardPaths::writableLocation(QStandardPaths::DesktopLocation)`](https://doc.qt.io/qt-6/qstandardpaths.html) for this purpose.

**Comment by DanielSvoboda** [comment]
Thanks for the suggestions, it worked perfectly.
I used QStandardPaths to locate the directories.
And QDir to check, because the previous way didn't work correctly because of the special characters in my language.
