### ISSUE TITLE
Pikmin 4 hangs on loading save on Mainline 1583+

### ISSUE THREAD

**Issue by navaar7sc** [yuzu-emu/yuzu#11764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1583+

### Description of Issue

Pikmin 4 hangs after loading a save file. You can hear the ambient sounds of the game, but are stuck on the loading screen. Occasionally there are audio clicks that can be heard.

I have cleared the various caches and it does not fix the issue.

On Mainline 1582 the game loads and runs as expected.

### Expected Behavior

Game loads and plays.

### Reproduction Steps

Load the game and load this save file, the loading will complete and then the game will hang.

[0100B7C00933A000.zip](https://github.com/yuzu-emu/yuzu/files/12885094/0100B7C00933A000.zip)

### Log File

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/12885176/yuzu_log.zip)

### System Configuration

CPU: Ryzen 5900X
GPU/Driver: nVidia GeForce RTX 3080Ti v537.58
RAM: 32gb DDR4
OS: Windows 11 22H2 (Os Build 22621.2283)
Using Vuklan renderer with High GPU Accuracy

I see the same issue on my Steam Deck with OpenGL + GLSL renderer.

**Comment by liamwhite** [comment]
bisected to https://github.com/yuzu-emu/yuzu/pull/11686

**Comment by ppStarLightShadows** [comment]
I have the same problem, except it waits until the scene is visible and than hangs.
It also hangs upon trying to start a new file as soon as Pikmin are brought out of the onion in the Olimar prologue.

**Comment by liamwhite** [comment]
@navaar7sc @ppStarLightShadows the issue should be resolved by the msvc artifact of this build: https://nightly.link/yuzu-emu/yuzu/actions/runs/6499812562?pr=11766

**Comment by navaar7sc** [comment]
@liamwhite That was fast! I pulled down the build and it works as expected! Should I go ahead and close this issue?

**Comment by liamwhite** [comment]
Wait for tomorrow's mainline and it should be fixed for everyone.
