### ISSUE TITLE
TOTK crash on start up after update to ML 1585 Flatpak (regression)

### ISSUE THREAD

**Issue by nocnoc94** [yuzu-emu/yuzu#11760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1585

### Description of Issue

The issue I [opened 2 days ago which was fixed in ML 1584 is back. ](https://github.com/yuzu-emu/yuzu/issues/11738)

After updating to 1585 Flatpak, TOTK crashes after the launching screen like it did with 1582 and 1583. However all other games (MK8, M:O, Katamari) run fine.

### Expected Behavior

That the game launches fine like it did on 1584

### Reproduction Steps

1. Launch game 
2. Game crashes after launch screen

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12880778/yuzu_log.txt)
[inxi.txt](https://github.com/yuzu-emu/yuzu/files/12880784/inxi.txt)

### System Configuration

CPU: Intel Core i7-8750H
GPU/Driver: GeForce RTX 2070 Mobile 535.113.01
RAM: 32GB
OS: Fedora 38 Workstation
Kernel: 6.5.6-200.fc38.x86_64

**Comment by nocnoc94** [comment]
Linking contributors present in previous issue

@Squall-Leonhart @liamwhite

**Comment by Squall-Leonhart** [comment]
mind clearing the pipelines?

**Comment by nocnoc94** [comment]
> mind clearing the pipelines?

I have now, it still crashes after yuzu launch screen. Here is my log file with the cleared shader cache

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12881532/yuzu_log.txt)

**Comment by Squall-Leonhart** [comment]
The resolution to this crash in the flatpack builds breaks the recall animation, and several other games again, the offending file needs to be torn to pieces and redone from scratch.

**Comment by nocnoc94** [comment]
Just tested with mainline 1593, it's back to working again. I'll close this issue. Thanks for the help!
