### ISSUE TITLE
Have multiple savegame accounts

### ISSUE THREAD

**Issue by YigaUpdate** [yuzu-emu/yuzu#11797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I propose as a new feature to be able to have several savegame accounts like on CEMU.

![Create-Account](https://github.com/yuzu-emu/yuzu/assets/147800620/4699dd9d-487b-4a07-bc6c-a5e3d3a31542)

### Why would this feature be useful?

This would be useful to have multiple saves for a game (For exemple TOTK or BOTW)

![2017022720544500-57b4628d2267231d57e0fc1078c0596d_09026C015D00858475](https://github.com/yuzu-emu/yuzu/assets/147800620/74488d2c-c0ca-4dc8-b132-4318081e4470)

**Comment by G-Spawn** [comment]
you can make multiple user profiles saves in yuzu currently for your games.

![image](https://github.com/yuzu-emu/yuzu/assets/23653025/e2eed83e-ad36-4393-98a4-f55901eb5abf)

![image](https://github.com/yuzu-emu/yuzu/assets/23653025/2bc1695d-fee2-4bef-8823-dee6317fc42a)

then turn on 'prompt for user on game boot' and you can access your saves with right click still and it prompts you which profile to open directory for.

**Comment by YigaUpdate** [comment]
Thank you very much and sorry for the inconvenience.

**Comment by G-Spawn** [comment]
No worries! Does this satisfy your request?

**Comment by YigaUpdate** [comment]
Yes of course

**Comment by G-Spawn** [comment]
Closing then. I do hope you have a wonderful day! Please don't be afraid to make issues / requests in future that's what we're here for :p
