### ISSUE TITLE
Option for whether to create a desktop shortcut in the maintenance tool

### ISSUE THREAD

**Issue by Ritaku02** [yuzu-emu/yuzu#11808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

After updating today, I noticed the maintenance tool placed a shortcut on my desktop. Realizing that people would want an option for whether a shortcut should be on the desktop, I propose making it a checkbox option in the maintenance tool.

### Why would this feature be useful?

I, personally, prefer to keep my desktop as clean as possible, and instead use the taskbar, start menu, and Playnite for opening programs and games. However, I realize there's likely others who prefer the desktop, and as such, I propose making the desktop shortcut an option.

**Comment by german77** [comment]
There's already an option on the installer. Somehow is not visible on the maintenance tool

**Comment by Ritaku02** [comment]
Update; the option also doesn't appear in the installer if there's already and existing install, I had to uninstall first to get the option to appear.

**Comment by FearlessTobi** [comment]
Issues for liftinstall go here: https://github.com/j-selby/liftinstall.
