### ISSUE TITLE
[Windows] Starting games make Yuzu crash

### ISSUE THREAD

**Issue by informagico** [yuzu-emu/yuzu#11807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1591

### Description of Issue

Each game I try to start, makes Yuzu crash

### Expected Behavior

Not to crash

### Reproduction Steps

Just start a game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12937171/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7 5700G with Radeon Graphics
CPU Cores: 8
CPU Threads: 16
GPU: AMD Radeon RX 6700 XT (driver v23.9.3)
OS: Windows 11 Version 22H2 (Build 22621.2500)
RAM: 31.85 GiB
Swap: 19.53 GiB

**Comment by german77** [comment]
Please don't touch the debug tab unless you know what you are doing. Disable enable_fs_access_log and use_debug_asserts on your config.
