### ISSUE TITLE
Option to prevent automatic updates

### ISSUE THREAD

**Issue by davidhedlund** [yuzu-emu/yuzu#11814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### RPCS3 features
Appimages in RPCS3 are self-updating.

![image](https://github.com/yuzu-emu/yuzu/assets/6416073/c28366bf-d046-4ca5-a58c-0a8d58d7ad87)

To make it easy to update the system if "Check for updates on startup" = "No":

![image](https://github.com/yuzu-emu/yuzu/assets/6416073/20607a3f-d2f2-4d1f-bbc5-6eedd3d6d9d7)

#### Yuzu feature request
**Feature request = purple highlighted background color**

Yuzu Maintainance Tool:

![image](https://github.com/yuzu-emu/yuzu/assets/6416073/ca348771-e277-4fb4-8a04-d057355de3b4)

The option should not be placed in the updater itself (that is executed when you run Yuzu from the menu) because that will make it impossible to enable it later:

![image](https://github.com/yuzu-emu/yuzu/assets/6416073/913bb5c6-9ad0-4f79-ab72-638eb77f7d66)

### Why would this feature be useful?
It's useful to know how to run old builds if you encounter regression bugs that have not been reported.

**Comment by davidhedlund** [comment]
I just learned that the Appimages in RPCS3 are self-updating by default, while Appimages cannot be self-updated in Yuzu at all. So the solution to use older version in Yuzu is simply to avoid using the liftintall and download an Appimage instead.

**Comment by FearlessTobi** [comment]
Issues for liftinstall go here: https://github.com/j-selby/liftinstall.

**Comment by davidhedlund** [comment]
> Issues for liftinstall go here: https://github.com/j-selby/liftinstall.

Thank you, I merged it.
