### ISSUE TITLE
Super mario wonders (doesn't boot)

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#11819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android v105

### Description of Issue

The game doesn't boot

Edite: The game has officially been released today in the jp,nz store.

### Expected Behavior

the game should work normally

### Reproduction Steps

Play normally 

### Log File

[doesn't boot_yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13044957/doesn.t.boot_yuzu_log.txt)

### System Configuration

CPU: sd860
GPU/Driver: a640, turnip driver 
RAM: 8gb
OS: android 13

**Comment by FearlessTobi** [comment]
We cannot accept this issue report, since your game is modded.
Therefore we cannot determine if its a problem with yuzu or the mod.

**Comment by brujo5** [comment]
ok but don't close it, I'm going to edit everything and let the game not start only

**Comment by G-Spawn** [comment]
Sigh you ended up making a duplicate. I'll keep it closed then.
