### ISSUE TITLE
Brawlout stuck trying to load

### ISSUE THREAD

**Issue by superheri** [yuzu-emu/yuzu#1181]
![image](https://user-images.githubusercontent.com/30275781/44628991-457d9480-a917-11e8-9e7e-85fd1fc363c9.png)

As you can see in the capture above, the Game i continuously writing the same warning and is stuck there without going any further.

Using Canary e1d2f9e

**Comment by Hexagon12** [comment]
The ResetSignal lockup also happens in: BotW (with update 1.5.0), Pokken Tournament DX (with latest update), Celeste and Octopath Traveler.

**Comment by superheri** [comment]
Same thing happens in Overcooked 2 on my side.

**Comment by Hexagon12** [comment]
Is this issue still relevant?

**Comment by superheri** [comment]
Seems like it's resolved, but I'm not sure about it. So I'll close this for now.
