### ISSUE TITLE
Super Mario Bros Wonder stops rendering at world map

### ISSUE THREAD

**Issue by Arcadius2006** [yuzu-emu/yuzu#11826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1594

### Description of Issue

When playing Super Mario Bros Wonder, there is an issue where the game stops rendering entirely once you reach the world map. For some reason, this issue doesn't happen when the FPS

### Expected Behavior

Game displays world map regardless of FPS

### Reproduction Steps

Boot up the game (with patch mod), Enter a savefile (prefferably an existing one), and see notice how the game seems to freeze when you freeze the world map. Do some controller inputs and notice how your character still makes footstep sounds when walking around.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13055215/yuzu_log.txt)

### System Configuration

CPU: Intel Core I5 10400F
GPU/Driver: NVIDIA GeForce GTX 1650 Super
RAM: 16GB
OS: Windows 11 Pro

**Comment by Arcadius2006** [comment]
may have included the wrong log file, im not sure.

**Comment by Squall-Leonhart** [comment]
should be fixed by https://github.com/yuzu-emu/yuzu/pull/11827

**Comment by Squall-Leonhart** [comment]
Please remove the patch mod as https://github.com/yuzu-emu/yuzu/pull/11825 should fix boot

**Comment by Arcadius2006** [comment]
oh yeah it is fixed, i thought this was closed, though.

**Comment by dsapandora** [comment]
it's works perfect on SMW steam deck
