### ISSUE TITLE
Super mario wonders doesn't boot 

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#11820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android v105

### Description of Issue

The game doesn't boot.

For reference, the game works in Skyline without needing anything but with graphical errors.

![IMG_20231019_093433_292](https://github.com/yuzu-emu/yuzu/assets/4172898/9324c212-31db-4cbe-8a77-0e0925234045)
![IMG_20231019_093430_426](https://github.com/yuzu-emu/yuzu/assets/4172898/ac061038-e89f-40f0-b8e3-126cf5710cc5)
![IMG_20231019_093426_155](https://github.com/yuzu-emu/yuzu/assets/4172898/0b2f84e8-49f8-4339-90af-c4ffeed5dab0)

### Expected Behavior

that shouldn't happen

### Reproduction Steps

Play normally 

### Log File

[doesn't boot_yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13045263/doesn.t.boot_yuzu_log.txt)

### System Configuration

CPU: sd860
GPU/Driver: a640, turnip driver 
RAM: 8gb
OS: android 13

**Comment by brujo5** [comment]
> The game isn't out yet, so why ask for support?

Out in JP, NZ store. 

I think you know that it is already October 20 in those parts of the world.

**Comment by Squall-Leonhart** [comment]
Should be fixed by https://github.com/yuzu-emu/yuzu/pull/11825
