### ISSUE TITLE
ThimbleweedPark Fatal OpenGL error!

### ISSUE THREAD

**Issue by Dantttt** [yuzu-emu/yuzu#1183]
Fatal Error on latest canary (969) on ThimbleweedPark:
[ 248.895147] Render.OpenGL <Critical> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:436: API ERROR 1282: GL_INVALID_OPERATION error generated. <program> object is not successfully linked.
This is a handler issue.

**Comment by M-F-K** [comment]
Here is a log from the mentioned game. Note: the log looks similar to the issue#1186 I have just reported.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2324839/yuzu_log.txt)

**Comment by M-F-K** [comment]
Issue #1186 have been closed, since this issue was the result of the same error: Unimplemented comparison op=1235222912  . So to sum it up, 2 games are aparently failing because of this: Timbleweed park, and The Count Lucanor.

**Comment by Dantttt** [comment]
Right.

**Comment by Hexagon12** [comment]
Does this game still not display anything?

**Comment by M-F-K** [comment]
The uniplemented  comparison up it gone.  Now it crash with another error: GL_INVALID_ENUM error generated. Invalid depth function . This is just one of many critical errors , where invalid depth function and failed in linking shader is also stated in the log. To sum it up: the original error stated is fixed, so I guess that this issue could be closed. If a new issue should be created, - well I leave it up to you @Hexagon12  , - I have attached log from Canary 1321
[yuzu_Cannary1321_log.txt](https://github.com/yuzu-emu/yuzu/files/2484328/yuzu_Cannary1321_log.txt)
