### ISSUE TITLE
void RasterizerVulkan::UpdateDepthBias Update Bring Super Smash Bros. Ultimate Issues Back. 

### ISSUE THREAD

**Issue by BenyHdezM** [yuzu-emu/yuzu#11838]
### Issue

Base on the solution on :  https://yuzu-emu.org/entry/yuzu-progress-report-sep-2021/

The new implementation of  << void RasterizerVulkan::UpdateDepthBias >> in /src/video_core/renderer_vulkan/vk_rasterizer.cpp Line 1024  bring the issue back since Release 1572 After merging : 

Vulkan: Implement Depth Bias Control 
https://github.com/yuzu-emu/yuzu-mainline/commit/6a1ecab2dde1db7d3183d9c98eda393341cca50b

I suggest to test it using an Steam Deck. For the moment I will try to setup the environment for try to solve on mine, but if you have some time to fix it good luck. 

Thanks.

**Comment by Squall-Leonhart** [comment]
you have not used the correct template.
