### ISSUE TITLE
Loading Super Mario Wonder fails when done a second time in a single session of Yuzu 

### ISSUE THREAD

**Issue by krisring** [yuzu-emu/yuzu#11837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1595

### Description of Issue

When playing Super Mario Wonder - if you stop emulation and attempt to reload or just restart emulation - the game does not load.

### Expected Behavior

When loading the game using proper settings as mentioned in 1595 release notes - the game should load fine each time without having to start a new session of the emu

### Reproduction Steps

Load Super Mario Wonder
Stop Emulation
Load Super Mario Wonder again
Game does not load

### Log File

[   0.149950] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.149962] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.150276] Input <Info> input_common\drivers\tas_input.cpp:LoadTasFile:129: TAS file loaded! 0 frames
[   0.150297] Input <Info> input_common\drivers\tas_input.cpp:LoadTasFile:129: TAS file loaded! 0 frames
[   0.150312] Input <Info> input_common\drivers\tas_input.cpp:LoadTasFile:129: TAS file loaded! 0 frames
[   0.150326] Input <Info> input_common\drivers\tas_input.cpp:LoadTasFile:129: TAS file loaded! 0 frames
[   0.150340] Input <Info> input_common\drivers\tas_input.cpp:LoadTasFile:129: TAS file loaded! 0 frames
[   0.150355] Input <Info> input_common\drivers\tas_input.cpp:LoadTasFile:129: TAS file loaded! 0 frames
[   0.150370] Input <Info> input_common\drivers\tas_input.cpp:LoadTasFile:129: TAS file loaded! 0 frames
[   0.150384] Input <Info> input_common\drivers\tas_input.cpp:LoadTasFile:129: TAS file loaded! 0 frames
[   0.150398] Input <Info> input_common\drivers\tas_input.cpp:LoadTasFile:129: TAS file loaded! 0 frames
[   0.150411] Input <Info> input_common\drivers\tas_input.cpp:LoadTasFile:129: TAS file loaded! 0 frames
[   0.264040] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.326417] Frontend <Info> yuzu\main.cpp:GMainWindow:375: yuzu Version: yuzu 1595
[   0.326434] Frontend <Info> yuzu\main.cpp:LogRuntimes:252: MSVC Compiler: 1935 Runtime: 14.36.32532.0
[   0.326435] Frontend <Info> yuzu\main.cpp:LogRuntimes:261: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.326436] Frontend <Info> yuzu\main.cpp:GMainWindow:391: Host CPU: AMD Ryzen 9 5900X 12-Core Processor             | AVX2 | FMA
[   0.326444] Frontend <Info> yuzu\main.cpp:GMainWindow:393: Host CPU Cores: 12
[   0.326445] Frontend <Info> yuzu\main.cpp:GMainWindow:396: Host CPU Threads: 24
[   0.326558] Frontend <Info> yuzu\main.cpp:GMainWindow:397: Host OS: Windows 11 Version 22H2 (Build 22621.2428)
[   0.326569] Frontend <Info> yuzu\main.cpp:GMainWindow:399: Host RAM: 31.92 GiB
[   0.326570] Frontend <Info> yuzu\main.cpp:GMainWindow:400: Host Swap: 3.12 GiB
[   0.326609] Frontend <Info> yuzu\main.cpp:GMainWindow:405: Host Timer Resolution: 0.4992 ms
[   1.092150] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.4.0) applied successfully
[   1.095940] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.12.0) applied successfully
[   1.098013] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.3.0) applied successfully
[   1.100140] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.2.0) applied successfully
[   1.102743] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.1.0) applied successfully
[   1.107079] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.1.0) applied successfully
[   1.109025] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.5.0) applied successfully
[   1.110645] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.3.0) applied successfully
[   1.112244] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Game Boy – Nintendo Switch Online [0100C62011050800][v327680][US].nsp has a different type (unknown) than its extension.
[   1.114587] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.2.0) applied successfully
[   1.116891] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.5.0) applied successfully
[   1.119111] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.16.0) applied successfully
[   1.121184] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:451:     RomFS: Update (v0.16.0) applied successfully
[   1.123196] Loader <Info> core\file_sys\patc

### System Configuration

CPU: Ryzen 5900X
GPU/Driver: Nvidia RTX 3090 (Driver most recent)
RAM: 32GB
OS: Win11

**Comment by FearlessTobi** [comment]
Both your logs are incomplete.

**Comment by Squall-Leonhart** [comment]
should be fixed now

**Comment by krisring** [comment]
Thanks for the support guys - I'll work on my logs for next time I report anything
