### ISSUE TITLE
Yuzu not saving profile data

### ISSUE THREAD

**Issue by Borisyeltsinalco** [yuzu-emu/yuzu#11839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1595

### Description of Issue

Yuzu stating does not have permission to save new profiles, all other functions working, full permission granted through windows

Relevant log
[   0.090227] Common.Filesystem <Error> common\fs\file.cpp:Open:282: Failed to open the file at path=C:\Users\chris\AppData\Roaming/yuzu/nand/system/save/8000000000000010/su/avators\profiles.dat, ec_message=permission denied
[   0.090233] Service.ACC <Warning> core\hle\service\acc\profile_manager.cpp:WriteUserSaveFile:425: Failed to write save data to file... No changes to user data made in current session will be saved.

### Expected Behavior

New profiles should save

### Reproduction Steps

Not sure how to reproduce

### Log File

[   0.090227] Common.Filesystem <Error> common\fs\file.cpp:Open:282: Failed to open the file at path=C:\Users\chris\AppData\Roaming/yuzu/nand/system/save/8000000000000010/su/avators\profiles.dat, ec_message=permission denied
[   0.090233] Service.ACC <Warning> core\hle\service\acc\profile_manager.cpp:WriteUserSaveFile:425: Failed to write save data to file... No changes to user data made in current session will be saved.

### System Configuration

CPU:12700k
GPU/Driver:3080 latest
RAM:32 ddr5
OS:win 11

**Comment by Squall-Leonhart** [comment]
This is caused by not having a profile image for the selected profile
