### ISSUE TITLE
Vibration strength resets to 1 in some cases

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [yuzu-emu/yuzu#11845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1595

### Description of Issue

Vibration strength resets to 1 if you press Cancel after vibration test in settings.

### Expected Behavior

Strength should be same as before.

### Reproduction Steps

1. Go to Emulation -> Configure -> Controls.
2. Check vibration checkbox, it should be on.
3. Click Configure near vibration checkbox.
4. Check vibration strength values. By default they should be 100%.
5. Press any button on gamepad, you'll get vibration.
6. Click Cancel.
7. Click Configure near vibration checkbox.
8. Check vibration strength values, on previously tested gamepad it gonna be 1%.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13062269/yuzu_log.txt)

### System Configuration

CPU: Intel Core i5 10400
GPU/Driver: NVIDIA RTX 2060 Super/ 536.23
RAM: 32GB
OS: Windows 10

**Comment by VladimirVSC** [comment]
The same for me.
