### ISSUE TITLE
Nightly builds are recognized as shared library on Linux

### ISSUE THREAD

**Issue by TotalCaesar659** [yuzu-emu/yuzu#1185]
Hello! On Lubuntu 18.04, Nightly builds are recognized as "shared library", and they can be run only from terminal, and it's not comfortable. Is it possible to build them as executable files or something like this for running from GUI?
![1](https://user-images.githubusercontent.com/14265316/44638484-c728fd00-a9bf-11e8-98ad-25c706c652d6.png)

**Comment by ReaperOfSouls1909** [comment]
ln -T /usr/lib/libsndio.so.7.0 /usr/lib/libsndio.so.6.1
after installing libsndio

**Comment by TotalCaesar659** [comment]
```
1@device:~$ sudo ln -T /usr/lib/libsndio.so.7.0 /usr/lib/libsndio.so.6.1
ln: failed to access '/usr/lib/libsndio.so.7.0': No such file or directory
```
There is only one package **libsndio6.1** that can be installed fron Bionic repos, no 7.0.

**Comment by ReaperOfSouls1909** [comment]
thats lame
man ubuntu sucks these days ok well run yuzu and on the side bar pin it

**Comment by TotalCaesar659** [comment]
I'm on Lubuntu, there is no side bar in LXDE. OK, I'll try to make a shortcut.

**Comment by pihug12** [comment]
Same issue (*libsndio.so*) with Fedora 29.

```
[user@ThinkPad yuzu-linux-20190216-034ee8c]$ cat /etc/fedora-release ; uname -r
Fedora release 29 (Twenty Nine)
4.20.8-200.fc29.x86_64
[user@ThinkPad yuzu-linux-20190216-034ee8c]$ ./yuzu
./yuzu: error while loading shared libraries: libsndio.so.6.1: cannot open shared object file: No such file or directory
[user@ThinkPad yuzu-linux-20190216-034ee8c]$ ll /usr/lib/lib*
ls: impossible d'accéder à '/usr/lib/lib*': No such file or directory
[user@ThinkPad yuzu-linux-20190216-034ee8c]$
```

**Related:**
* https://github.com/citra-emu/citra/issues/3862
* https://github.com/yuzu-emu/yuzu/issues/1061
* https://github.com/yuzu-emu/yuzu/issues/2044

**Comment by leifliddy** [comment]
@pihug12 

#on Ubuntu 18.04.3#
apt-get install libsndio6.1

#transfer this file to your Fedora box
```/usr/lib/x86_64-linux-gnu/libsndio.so.6.1```



#on Fedora 31#

#transfer libsndio.so.6.1 file to /usr/local/lib64

```
[root@black ~]# ll /usr/local/lib64
-rw-r--r--. 1 root root 55520 Dec 21 10:42 libsndio.so.6.1
```

#create ld.so.conf config that contains the directory ```/usr/local/lib64```
ie
```
[root@black ~]# cat /etc/ld.so.conf.d/local.conf 
/usr/local/lib64
```

Now run ldconfig to update dynamic links
```
[root@black ~]# ldconfig
```

#verify libsndio.so.6.1 is linked properly

```
[root@black yuzu]# ldd yuzu
	linux-vdso.so.1 (0x00007ffeb0bf5000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff343cf2000)
	libQt5WebEngineWidgets.so.5 => /lib64/libQt5WebEngineWidgets.so.5 (0x00007ff343cb0000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007ff343c1a000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007ff34393a000)
	libasound.so.2 => /lib64/libasound.so.2 (0x00007ff34383b000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff343834000)
	libsndio.so.6.1 => /usr/local/lib64/libsndio.so.6.1 (0x00007ff343622000)
```

**Comment by leifliddy** [comment]
@pihug12 
Disregard the previous post. If you compile yuzu on Fedora:

https://github.com/yuzu-emu/yuzu/wiki/Building-For-Linux

There will be no libsndio dependency.

**Comment by MysticExile** [comment]
Closing as we do not support Nightly builds anymore.
