### ISSUE TITLE
Broken rendering with Crash Team Racing on Vulkan

### ISSUE THREAD

**Issue by bowlofspiders** [yuzu-emu/yuzu#11853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1597

### Description of Issue

Using a 1080 Ti and the game doesn't render properly using Vulkan. The issues for this (#6731, #8215) were closed because PR #11789 is supposed to fix the issue, but it doesn't.

![277181674-9d185edb-386c-46b6-ac30-c92d10b9be60](https://github.com/yuzu-emu/yuzu/assets/53333627/91ceef75-f724-4511-ba11-82a503af4af0)

### Expected Behavior

Using OpenGL:
![image](https://github.com/yuzu-emu/yuzu/assets/53333627/222e3ab8-bbc4-418b-b4e3-2681a46f3db7)

### Reproduction Steps

Launch the game. As soon as the title screen loads the issue presents itself.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13064176/yuzu_log.txt)

### System Configuration

CPU: i5 13600k
GPU/Driver: Nvidia GTX 1080 Ti, 545.84 driver
RAM: 32GB DDR5
OS: Windows 11 Pro

**Comment by cjunisl** [comment]
yuzu 1597

GTX 1050

![image](https://github.com/yuzu-emu/yuzu/assets/57728845/c7c10c98-9ec7-400d-904f-ae08efd70dcd)

**Comment by cjunisl** [comment]
vulkan bug fixed in 3944. thanks.

**Comment by XxAlcatelxX** [comment]
Audio still stutters on vulkan
