### ISSUE TITLE
yuzu crashes when entering a multiplayer room and launching smash with mods in the sd (disabled)

### ISSUE THREAD

**Issue by Clozent** [yuzu-emu/yuzu#11850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1597

### Description of Issue

When joining a multiplayer room for Smash Ultimate, then launching the game, yuzu just crashes if you have mods in the `sdmc` folder, even if they were disabled in `Properties > Add-Ons > SDMC`. This might also happen with other games, but I don't have any other games to test with.

### Expected Behavior

I expect the game to simply launch.

### Reproduction Steps

This is assuming you have already installed some atmosphere / skyline mods in the SD card folder:

1. Open yuzu.
2. Click on Multiplayer > Browse Public Game Lobby.
3. Tick the "Games I own" checkbox, to only show viable rooms.
4. Enter a room.
5. Launch Smash by double-clicking on it.
6. Yuzu crashes.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13063704/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5 5600X
GPU/Driver: NVIDIA GeForce RTX 3070 / Driver version 537.13
RAM: 32 GB
OS: Windows 10 Pro 64-bit

**Comment by FearlessTobi** [comment]
User has pirated their games.
Closing
