### ISSUE TITLE
 The Count Lucanor, Error linking shader * 2

### ISSUE THREAD

**Issue by M-F-K** [yuzu-emu/yuzu#1186]
2 different times a shader is tried to be linked, this fails. se attached log.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2324816/yuzu_log.txt)

**Comment by Hexagon12** [comment]
> [  12.357788] Debug <Critical> video_core\command_processor.cpp:ProcessCommandList:122: Unimplemented code!
> [  12.357883] Render.OpenGL <Critical> video_core\renderer_opengl\maxwell_to_gl.h:ComparisonOp:293: Unimplemented comparison op=1235222912

Related lines?

**Comment by M-F-K** [comment]
Well the shader link error seems to be the result of missing this comparison op, yes.

**Comment by M-F-K** [comment]
just compared the log (timbleweed park    and     The Count Lucanor ) and both seems to fail because of this unimplemented comparison op=1235222912. Because issue 1183 allready covers this error, I think this issue can be closed as redundant. Sorry for the fuss.
