### ISSUE TITLE
Bayonetta 3 - Consistent Crash and Shader Issue

### ISSUE THREAD

**Issue by AlphaSpectre83** [yuzu-emu/yuzu#11875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1599

### Description of Issue

During Chapter 1, Verse 5, the game will play as expected until reaching the end of the building surfing segment. In the cutscene following this segment, the game will freeze and crash at the exact same point.

![Screenshot (19)](https://github.com/yuzu-emu/yuzu/assets/148910994/369b52b7-b2c3-4241-afd5-36ab6160f44b)

After crashing, relaunching the game will cause it to crash on launch when building shaders. This can be circumvented by deleting the shader cache, but then the process repeats from the start.

This bug is also present on the Steam Deck and was where I first encountered it.

(This issue also existed on the previous build, but this one released today so I wanted to try it.)

### Expected Behavior

No crashing.

### Reproduction Steps

The files should start you on a train if you choose 'Continue' from the main menu.

Play through Chapter 1 as normal until reaching the end of the segment with a demon sliding on collapsing buildings.

[01004A4010FEA000.zip](https://github.com/yuzu-emu/yuzu/files/13127058/01004A4010FEA000.zip)

### Log File

Windows 10 Log
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13127215/yuzu_log.txt.old.txt)

Steam Deck (Emudeck) Log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13183116/yuzu_log.txt)

### System Configuration

CPU: Intel Core i7-9700k @ 3.60GHz (8 Cores)
GPU/Driver: Nvidia RTX 2080ti / 545.84
RAM: 32GB DDR4
OS: Windows 10 Home 64-Bit

**Comment by liamwhite** [comment]
Identified as possible nvidia driver issue in internal testing

**Comment by AlphaSpectre83** [comment]
I should add that this issue is also present on the Steam Deck, which I believe is AMD.

**Comment by makenX64** [comment]
Hi everyone, i can confirmi it's a nvidia driver issue. At least on the green side. I succesfully fix my yuzu 1606 ver. with a downgrade of the nvidia driver ver. 537.58. 
For me, this version is working. 
RTX 3070 here. Win 11. I don't have try superior version of nvidia driver if they work, but i can recall that the problem start to occour from the 545.92 and above.
