### ISSUE TITLE
Pause emulation when unfocused

### ISSUE THREAD

**Issue by moonlumen** [yuzu-emu/yuzu#11872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A setting that makes Yuzu automatically pause when the window is not focused.

### Why would this feature be useful?

I would find this extremely useful as I use playnite and steam big picture, and when focusing either Yuzu is still capturing inputs which can lead to unintended happen-ings in the game.

**Comment by Alleop5** [comment]
General  > Pause emulation when in background
