### ISSUE TITLE
Mario Kart 8 Deluxe doesn't load Mii

### ISSUE THREAD

**Issue by BjornHelheim** [yuzu-emu/yuzu#11874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1599

### Description of Issue

Mario Kart 8 is not loading the Mii list so I'm not able to continue.
![Captura de ecrã 2023-10-24 211155](https://github.com/yuzu-emu/yuzu/assets/52963952/2a570eec-fa8e-4b51-b4be-ae60ba7078e2)

### Expected Behavior

Mario Kart 8 loads the Mii list to be able to choose.

### Reproduction Steps

Open Mario Kart 8. 
Click L + R to start.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13126911/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7600X
GPU/Driver: AMD Radeon 7900 XTX / 23.10.2
RAM: 32GB
OS: Windows 11

**Comment by AliciaBurrito** [comment]
@BjornHelheim This happens if you don't have firmware and keys dumped from your Switch. You can follow the steps here to do so: https://yuzu-emu.org/help/quickstart/#dumping-decryption-keys

For further support reach out on the support channels on the yuzu Discord.

**Comment by BjornHelheim** [comment]
It worked, sorry for the trouble
