### ISSUE TITLE
[Bug] Mii editor crashing on AMD/Vulkan/Win 11

### ISSUE THREAD

**Issue by Immersion95** [yuzu-emu/yuzu#11887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3949

### Description of Issue

The Mii editor is crashing on Vulkan with my 7800 XT when trying to edit a Mii, it works perfectly on OpenGL.

Here is a screenshot of another issue, Miis have graphical errors on Vulkan with their face.

FW is 16.1.0

![Capture d'écran 2023-10-26 121150](https://github.com/yuzu-emu/yuzu/assets/47425204/d6c134df-198b-4297-9252-f8916ef0a586)

This also make Super Smash Bros. Ultimate crashes in the mob mode.

### Expected Behavior

No graphical error + No crash

### Reproduction Steps

Open Mii Editor and try to modify or create a Mii

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13176063/yuzu_log.txt)
Relevant error : Debug <Critical> video_core\renderer_vulkan\vk_blit_screen.cpp:operator ():107: Assertion Failed!
Unknown framebuffer pixel format: 0

### System Configuration

CPU: Ryzen 5700X
GPU/Driver: AMD 7800 XT/Driver 23.10.2
RAM: 32 GB
OS: Windows 11

**Comment by Immersion95** [comment]
This had nothing to do with AMD GPU, the Async CPU ASTC option was causing the issue.

**Comment by abouvier** [comment]
> Here is a screenshot of another issue, Miis have graphical errors on Vulkan with their face.
> 
> ![Capture d'écran 2023-10-26 121150](https://user-images.githubusercontent.com/47425204/278297311-d6c134df-198b-4297-9252-f8916ef0a586.png)

The white "box" in lower left is present when the resolution is superior to 1x.
