### ISSUE TITLE
Xenoblade Chronicles 3 black texture bug on the ground

### ISSUE THREAD

**Issue by darq0n** [yuzu-emu/yuzu#11888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1442 onwards

### Description of Issue

Hi guys. I was wondering if anybody is finding similar texture glitches in Xenoblade Chronicles 3 and knows how to fix them. They started appearing with beginning of August builds, 24th Aug to be exact (mainline **build 1441 is the last one** working fine) and no matter what I try I can't find a way to fix them. I purged all shaders and cache, no filtering is forced. I'm on Nvidia, OpenGL, Vulkan doesn't exhibit these texture issues, but is crashing for me still, especially loading new areas and screen transitions. I'm loving the performance, but the glitches make it hard to play. They appear when I move around and pan the camera. It gets really bad at times. Thanks a lot!

ps. I just noticed a very similar issue in Xenoblade 2.

### Expected Behavior

Black graphical bugs appear. Mostly in areas with grass. The glitches appear when moving and paniing the camera around.
![Screenshot_2023-09-25_203806](https://github.com/yuzu-emu/yuzu/assets/128327525/b2a18357-c1c2-413d-8042-1e6fb418dc7f)
![Screenshot_2023-09-25_203839](https://github.com/yuzu-emu/yuzu/assets/128327525/df179314-359f-4a65-a8da-cac245e58970)
![Screenshot_2023-09-25_203957](https://github.com/yuzu-emu/yuzu/assets/128327525/4e41738d-a945-43a7-9cdf-f6b323cdeca6)
![Screenshot 2023-10-26 120019](https://github.com/yuzu-emu/yuzu/assets/128327525/d3b90021-829e-48ca-85da-f450c086bbf0)

![Screenshot 2023-10-26 115510](https://github.com/yuzu-emu/yuzu/assets/128327525/92b14bdd-47eb-4771-9e84-fb21475a6667)
![Screenshot 2023-10-26 115548](https://github.com/yuzu-emu/yuzu/assets/128327525/82d77952-4c63-4fc6-a709-f5c6ccbfaa0c)

### Reproduction Steps

The texture bugs are always present since mainline build 1422.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13176486/yuzu_log.txt)

### System Configuration

CPU: i5-4670K
GPU/Driver: GTX 970 Driver Nvidia: 537.42
RAM: 16GB
OS: Windows 11 Pro

**Comment by LoneWolf31589** [comment]
I have a similar situation.
https://github.com/yuzu-emu/yuzu/issues/11680

**Comment by Squall-Leonhart** [comment]
https://github.com/yuzu-emu/yuzu/issues/9146

**Comment by darq0n** [comment]
> I have a similar situation. #11680

yeah same thing. If you're really struggling try build 1441. It's not as fast as recent builds, but at least it works for me :)

**Comment by reloxx13** [comment]
> #9146

this ticket is about opengl, ur mentioned issue is vulkan

**Comment by Squall-Leonhart** [comment]
opengl is "dead"

**Comment by reloxx13** [comment]
> opengl is "dead"

this is not the discussion here.

**Comment by Squall-Leonhart** [comment]
the discussion involves an API that is on the verge of getting removed from the emulator.

**Comment by Squall-Leonhart** [comment]
Feel free to leave the issue, since it is not yours in the first place.

**Comment by darq0n** [comment]
The bug is back as of mainline build 1641 onwards.

**Comment by liamwhite** [comment]
@ameerj
