### ISSUE TITLE
yuzu crashes when running in the linux system

### ISSUE THREAD

**Issue by whaleboss** [yuzu-emu/yuzu#11899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

same as title

### Description of Issue

Yuzu crashed when I was running the game and I couldn't see any error message in the log.
Can anyone help me?
thanks a lot

### Expected Behavior

same as title

### Reproduction Steps

same as title

### Log File

[   0.080444] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.080459] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.108754] Input <Info> input_common/drivers/joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.166901] Frontend <Info> yuzu/main.cpp:GMainWindow:375: yuzu Version: yuzu 1595
[   0.166906] Frontend <Info> yuzu/main.cpp:LogRuntimes:261: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.166916] Frontend <Info> yuzu/main.cpp:GMainWindow:391: Host CPU:       Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz | AVX
[   0.166951] Frontend <Info> yuzu/main.cpp:GMainWindow:393: Host CPU Cores: 4
[   0.166952] Frontend <Info> yuzu/main.cpp:GMainWindow:396: Host CPU Threads: 8
[   0.166969] Frontend <Info> yuzu/main.cpp:GMainWindow:397: Host OS: Ubuntu 22.04.3 LTS
[   0.167910] Frontend <Info> yuzu/main.cpp:GMainWindow:398: Host RAM: 15.52 GiB
[   0.167913] Frontend <Info> yuzu/main.cpp:GMainWindow:400: Host Swap: 0.00 GiB
[   4.231286] Frontend <Info> yuzu/main.cpp:BootGame:1908: yuzu starting...
[   4.340621] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:450:     RomFS: Update (v0.0.0) applied successfully
[   4.358109] Config <Info> common/settings.cpp:LogSettings:115: yuzu Configuration:
[   4.358123] Config <Info> common/settings.cpp:operator():108: -- Audio.output_engine: auto
[   4.358126] Config <Info> common/settings.cpp:operator():108: -- Audio.output_device: auto
[   4.358127] Config <Info> common/settings.cpp:operator():108: -- Audio.input_device: auto
[   4.358131] Config <Info> common/settings.cpp:operator():108: -- Audio.volume: 100
[   4.358133] Config <Info> common/settings.cpp:operator():108: -- Audio.audio_muted: false
[   4.358134] Config <Info> common/settings.cpp:operator():108: -- Audio.dump_audio_commands: false
[   4.358137] Config <Info> common/settings.cpp:operator():108: -- Core.use_multi_core: true
[   4.358141] Config <Info> common/settings.cpp:operator():108: -- Core.memory_layout_mode: Memory_4Gb
[   4.358143] Config <Info> common/settings.cpp:operator():108: -- Core.use_speed_limit: true
[   4.358146] Config <Info> common/settings.cpp:operator():108: -- Core.speed_limit: 100
[   4.358149] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpu_accuracy: Auto
[   4.358152] Config <Info> common/settings.cpp:operator():108: M- Cpu.cpu_debug_mode: true
[   4.358153] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_page_tables: true
[   4.358155] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_block_linking: true
[   4.358157] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_return_stack_buffer: true
[   4.358158] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_fast_dispatcher: true
[   4.358162] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_context_elimination: true
[   4.358167] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_const_prop: true
[   4.358169] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_misc_ir: true
[   4.358170] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_reduce_misalign_checks: true
[   4.358172] Config <Info> common/settings.cpp:operator():108: M- Cpu.cpuopt_fastmem: false
[   4.358173] Config <Info> common/settings.cpp:operator():108: M- Cpu.cpuopt_fastmem_exclusives: false
[   4.358174] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_recompile_exclusives: true
[   4.358176] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_ignore_memory_aborts: true
[   4.358178] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_unsafe_unfuse_fma: true
[   4.358180] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_unsafe_reduce_fp_error: true
[   4.358182] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_unsafe_ignore_standard_fpcr: true
[   4.358183] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_unsafe_inaccurate_nan: true
[   4.358185] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_unsafe_fastmem_check: true
[   4.358187] Config <Info> common/settings.cpp:operator():108: -- Cpu.cpuopt_unsafe_ignore_global_monitor: true
[   4.358191] Config <Info> common/settings.cpp:operator():108: M- Renderer.backend: Null
[   4.358194] Config <Info> common/settings.cpp:operator():108: -- Renderer.shader_backend: Glsl
[   4.358197] Config <Info> common/settings.cpp:operator():108: -- Renderer.vulkan_device: 0
[   4.358200] Config <Info> common/settings.cpp:operator():108: -- Renderer.use_disk_shader_cache: true
[   4.358201] Config <Info> common/settings.cpp:operator():108: -- Renderer.use_asynchronous_gpu_emulation: true
[   4.358204] Config <Info> common/settings.cpp:operator():108: -- Renderer.accelerate_astc: Gpu
[   4.358208] Config <Info> common/settings.cpp:operator():108: -- Renderer.use_vsync: Fifo
[   4.358212] Config <Info> common/settings.cpp:operator():108: -- Renderer.nvdec_emulation: Gpu
[   4.358215] Config <Info> common/settings.cpp:operator():108: -- Renderer.fullscreen_mode: Exclusive
[   4.358218] Config <Info> common/settings.cpp:operator():108: -- Renderer.aspect_ratio: R16_9
[   4.362343] Config <Info> common/settings.cpp:operator():108: -- Renderer.resolution_setup: Res1X
[   4.362354] Config <Info> common/settings.cpp:operator():108: -- Renderer.scaling_filter: Bilinear
[   4.362357] Config <Info> common/settings.cpp:operator():108: -- Renderer.anti_aliasing: None
[   4.362359] Config <Info> common/settings.cpp:operator():108: -- Renderer.fsr_sharpening_slider: 25
[   4.362361] Config <Info> common/settings.cpp:operator():108: -- Renderer.bg_red: 0
[   4.362361] Config <Info> common/settings.cpp:operator():108: -- Renderer.bg_green: 0
[   4.362362] Config <Info> common/settings.cpp:operator():108: -- Renderer.bg_blue: 0
[   4.362375] Config <Info> common/settings.cpp:operator():108: -- Renderer.gpu_accuracy: High
[   4.362379] Config <Info> common/settings.cpp:operator():108: -- Renderer.max_anisotropy: Automatic
[   4.362381] Config <Info> common/settings.cpp:operator():108: -- Renderer.astc_recompression: Uncompressed
[   4.362383] Config <Info> common/settings.cpp:operator():108: -- Renderer.async_presentation: false
[   4.362384] Config <Info> common/settings.cpp:operator():108: -- Renderer.force_max_clock: false
[   4.362385] Config <Info> common/settings.cpp:operator():108: -- Renderer.use_reactive_flushing: true
[   4.362386] Config <Info> common/settings.cpp:operator():108: -- Renderer.use_asynchronous_shaders: false
[   4.362387] Config <Info> common/settings.cpp:operator():108: -- Renderer.use_fast_gpu_time: true
[   4.362388] Config <Info> common/settings.cpp:operator():108: -- Renderer.use_vulkan_driver_pipeline_cache: true
[   4.362389] Config <Info> common/settings.cpp:operator():108: -- Renderer.enable_compute_pipelines: false
[   4.362390] Config <Info> common/settings.cpp:operator():108: -- Renderer.use_video_framerate: false
[   4.362391] Config <Info> common/settings.cpp:operator():108: -- Renderer.barrier_feedback_loops: true
[   4.362392] Config <Info> common/settings.cpp:operator():108: M- Renderer.debug: true
[   4.362394] Config <Info> common/settings.cpp:operator():108: M- Renderer.shader_feedback: true
[   4.362395] Config <Info> common/settings.cpp:operator():108: M- Renderer.nsight_aftermath: true
[   4.362397] Config <Info> common/settings.cpp:operator():108: -- Renderer.disable_shader_loop_safety_checks: false
[   4.362399] Config <Info> common/settings.cpp:operator():108: M- Renderer.renderdoc_hotkey: true
[   4.362406] Config <Info> common/settings.cpp:operator():108: -- System.language_index: EnglishAmerican
[   4.362409] Config <Info> common/settings.cpp:operator():108: -- System.region_index: Usa
[   4.362423] Config <Info> common/settings.cpp:operator():108: -- System.time_zone_index: Auto
[   4.362424] Config <Info> common/settings.cpp:operator():108: -- System.custom_rtc_enabled: false
[   4.362428] Config <Info> common/settings.cpp:operator():108: M- System.custom_rtc: 1698500305
[   4.362430] Config <Info> common/settings.cpp:operator():108: -- System.rng_seed_enabled: false
[   4.362432] Config <Info> common/settings.cpp:operator():108: -- System.rng_seed: 0
[   4.362433] Config <Info> common/settings.cpp:operator():108: -- System.device_name: yuzu
[   4.362435] Config <Info> common/settings.cpp:operator():108: -- System.current_user: 0
[   4.362438] Config <Info> common/settings.cpp:operator():108: -- System.use_docked_mode: Docked
[   4.362440] Config <Info> common/settings.cpp:operator():108: -- System.sound_index: Stereo
[   4.362443] Config <Info> common/settings.cpp:operator():108: -- Data Storage.use_virtual_sd: true
[   4.362444] Config <Info> common/settings.cpp:operator():108: -- Data Storage.gamecard_inserted: false
[   4.362445] Config <Info> common/settings.cpp:operator():108: -- Data Storage.gamecard_current_game: false
[   4.362446] Config <Info> common/settings.cpp:operator():108: -- Data Storage.gamecard_path: 
[   4.362448] Config <Info> common/settings.cpp:operator():108: -- Debugging.use_gdbstub: false
[   4.362449] Config <Info> common/settings.cpp:operator():108: -- Debugging.gdbstub_port: 6543
[   4.362450] Config <Info> common/settings.cpp:operator():108: -- Debugging.program_args: 
[   4.362451] Config <Info> common/settings.cpp:operator():108: -- Debugging.dump_exefs: false
[   4.362452] Config <Info> common/settings.cpp:operator():108: -- Debugging.dump_nso: false
[   4.362453] Config <Info> common/settings.cpp:operator():108: -- Debugging.enable_fs_access_log: false
[   4.362454] Config <Info> common/settings.cpp:operator():108: -- Debugging.reporting_services: false
[   4.362455] Config <Info> common/settings.cpp:operator():108: -- Debugging.quest_flag: false
[   4.362456] Config <Info> common/settings.cpp:operator():108: -- Debugging.extended_logging: false
[   4.362457] Config <Info> common/settings.cpp:operator():108: M- Debugging.use_debug_asserts: true
[   4.362458] Config <Info> common/settings.cpp:operator():108: -- Debugging.use_auto_stub: false
[   4.362458] Config <Info> common/settings.cpp:operator():108: M- Debugging.enable_all_controllers: true
[   4.362459] Config <Info> common/settings.cpp:operator():108: -- Debugging.perform_vulkan_check: true
[   4.362461] Config <Info> common/settings.cpp:operator():108: -- Debugging.dump_shaders: false
[   4.362462] Config <Info> common/settings.cpp:operator():108: -- Debugging.dump_macros: false
[   4.362463] Config <Info> common/settings.cpp:operator():108: -- Debugging.disable_macro_jit: false
[   4.362464] Config <Info> common/settings.cpp:operator():108: -- Debugging.disable_macro_hle: false
[   4.362465] Config <Info> common/settings.cpp:operator():108: -- Miscellaneous.log_filter: *:Info
[   4.362466] Config <Info> common/settings.cpp:operator():108: -- Miscellaneous.use_dev_keys: false
[   4.362467] Config <Info> common/settings.cpp:operator():108: M- Network.network_interface: 無
[   4.362470] Config <Info> common/settings.cpp:operator():108: M- WebService.enable_telemetry: false
[   4.362472] Config <Info> common/settings.cpp:operator():108: -- WebService.web_api_url: https://api.yuzu-emu.org
[   4.362475] Config <Info> common/settings.cpp:operator():108: -- WebService.yuzu_username: 
[   4.362477] Config <Info> common/settings.cpp:operator():108: -- Controls.enable_raw_input: false
[   4.362478] Config <Info> common/settings.cpp:operator():108: -- Controls.controller_navigation: true
[   4.362479] Config <Info> common/settings.cpp:operator():108: -- Controls.enable_joycon_driver: true
[   4.362480] Config <Info> common/settings.cpp:operator():108: -- Controls.enable_procon_driver: false
[   4.362483] Config <Info> common/settings.cpp:operator():108: -- Controls.vibration_enabled: true
[   4.362484] Config <Info> common/settings.cpp:operator():108: -- Controls.enable_accurate_vibrations: false
[   4.362485] Config <Info> common/settings.cpp:operator():108: -- Controls.motion_enabled: true
[   4.362486] Config <Info> common/settings.cpp:operator():108: -- Controls.udp_input_servers: 127.0.0.1:26760
[   4.362488] Config <Info> common/settings.cpp:operator():108: -- Controls.enable_udp_controller: false
[   4.362489] Config <Info> common/settings.cpp:operator():108: -- Controls.pause_tas_on_load: true
[   4.362490] Config <Info> common/settings.cpp:operator():108: -- Controls.tas_enable: false
[   4.362491] Config <Info> common/settings.cpp:operator():108: -- Controls.tas_loop: false
[   4.362494] Config <Info> common/settings.cpp:operator():108: -- Controls.mouse_panning: false
[   4.362495] Config <Info> common/settings.cpp:operator():108: -- Controls.mouse_panning_sensitivity: 50
[   4.362496] Config <Info> common/settings.cpp:operator():108: -- Controls.mouse_enabled: false
[   4.362497] Config <Info> common/settings.cpp:operator():108: -- Controls.mouse_panning_x_sensitivity: 50
[   4.362499] Config <Info> common/settings.cpp:operator():108: -- Controls.mouse_panning_y_sensitivity: 50
[   4.362500] Config <Info> common/settings.cpp:operator():108: -- Controls.mouse_panning_deadzone_counterweight: 20
[   4.362501] Config <Info> common/settings.cpp:operator():108: -- Controls.mouse_panning_decay_strength: 18
[   4.362503] Config <Info> common/settings.cpp:operator():108: -- Controls.mouse_panning_min_decay: 6
[   4.362504] Config <Info> common/settings.cpp:operator():108: -- Controls.emulate_analog_keyboard: false
[   4.362505] Config <Info> common/settings.cpp:operator():108: -- Controls.keyboard_enabled: false
[   4.362508] Config <Info> common/settings.cpp:operator():108: -- Controls.debug_pad_enabled: false
[   4.362510] Config <Info> common/settings.cpp:operator():108: -- Controls.touch_device: min_x:100,min_y:50,max_x:1800,max_y:850
[   4.362513] Config <Info> common/settings.cpp:operator():108: -- Controls.touch_from_button_map: 0
[   4.362515] Config <Info> common/settings.cpp:operator():108: -- Controls.enable_ring_controller: true
[   4.362516] Config <Info> common/settings.cpp:operator():108: -- Controls.enable_ir_sensor: false
[   4.362517] Config <Info> common/settings.cpp:operator():108: -- Controls.ir_sensor_device: auto
[   4.362518] Config <Info> common/settings.cpp:operator():108: -- Controls.random_amiibo_id: false
[   4.362520] Config <Info> common/settings.cpp:operator():112: DataStorage_CacheDir: /home/bob/.cache/yuzu
[   4.362522] Config <Info> common/settings.cpp:operator():112: DataStorage_ConfigDir: /home/bob/.config/yuzu
[   4.362525] Config <Info> common/settings.cpp:operator():112: DataStorage_LoadDir: /home/bob/.local/share/yuzu/load
[   4.362526] Config <Info> common/settings.cpp:operator():112: DataStorage_NANDDir: /home/bob/.local/share/yuzu/nand
[   4.362527] Config <Info> common/settings.cpp:operator():112: DataStorage_SDMCDir: /home/bob/.local/share/yuzu/sdmc
[   4.383841] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:450:     RomFS: Update (v0.0.0) applied successfully
[   4.740514] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:86: Auto-selecting the cubeb backend
[   4.744065] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:86: Auto-selecting the cubeb backend
[   4.752890] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[   4.753953] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   4.758672] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:131: Patching ExeFS for title_id=01009CC00C97C000
[   4.759023] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:145:     ExeFS: Update (v0.0.0) applied successfully
[   4.759115] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:177:     ExeFS: LayeredExeFS patches applied successfully
[   4.907509] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=09AA0F157B8CF44DF373510612A0452A4803B2AB, name=rtld
[   4.957112] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=D81D2492B00F45D272097CCD14484E38, name=main
[   5.001102] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=8D073B25B9ABDA677E6967CEF9EF6070178E374E, name=subsdk0
[   5.032134] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=16577266BB9797ABF6029F85025F6D3510E6E8B7, name=subsdk1
[   5.087667] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=184751379007F9C50FC96BA4D26A5DCA76C3525F, name=sdk
[   5.221737] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:450:     RomFS: Update (v0.0.0) applied successfully
[   5.226141] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:450:     RomFS: Update (v0.0.0) applied successfully
[   5.226326] Frontend <Info> yuzu/main.cpp:BootGame:2027: Booting game: 01009CC00C97C000 | DEAD OR ALIVE Xtreme 3 Scarlet (64-bit) | 1.0.5
[   5.249316] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontStandard' (0x0100000000000811).
[   5.254230] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.254562] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[   5.262987] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.263109] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[   5.263281] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.263423] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseTraditional' (0x0100000000000813).
[   5.263514] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.263622] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontKorean' (0x0100000000000812).
[   5.263710] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.263815] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[   5.263825] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.263833] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[   5.263841] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.270361] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontStandard' (0x0100000000000811).
[   5.270630] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.270742] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[   5.271176] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.271284] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[   5.271449] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.271590] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseTraditional' (0x0100000000000813).
[   5.271670] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.271778] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontKorean' (0x0100000000000812).
[   5.271856] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.271962] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[   5.271972] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.271980] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[   5.271988] Service.FS <Info> core/file_sys/system_archive/system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   5.498392] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   5.516978] Service.AM <Warning> core/hle/service/am/am.cpp:AcquireForegroundRights:99: (STUBBED) called
[   5.517998] Service.AM <Warning> core/hle/service/am/am.cpp:SetFocusHandlingMode:493: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[   5.518842] Service.AM <Warning> core/hle/service/am/am.cpp:SetOutOfFocusSuspendingEnabled:513: (STUBBED) called enabled=false
[   5.521882] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   5.524920] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   5.527814] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   5.528486] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   5.528804] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:450:     RomFS: Update (v0.0.0) applied successfully
[   7.681545] Service.NVDRV <Warning> core/hle/service/nvdrv/nvdrv_interface.cpp:Initialize:152: (STUBBED) called
[   7.686193] Service.NVDRV <Warning> core/hle/service/nvdrv/nvdrv_interface.cpp:SetAruid:192: (STUBBED) called, pid=0x87
[   7.688078] Service.NVDRV <Warning> core/hle/service/nvdrv/nvdrv_interface.cpp:SetGraphicsFirmwareMemoryMarginEnabled:200: (STUBBED) called
[   7.696884] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   7.704545] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:427: Patching RomFS for title_id=01009CC00C97C000, type=01
[   7.705921] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:450:     RomFS: Update (v0.0.0) applied successfully
[   7.738185] Service.VI <Warning> core/hle/service/vi/vi.cpp:GetManagerDisplayService:571: (STUBBED) called
[   7.739366] Service.VI <Warning> core/hle/service/vi/vi.cpp:GetSystemDisplayService:563: (STUBBED) called
[   7.740193] Service.VI <Warning> core/hle/service/vi/vi.cpp:GetRelayService:555: (STUBBED) called
[   7.783342] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:72: (STUBBED) called
[   7.920156] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvhost_gpu.cpp:AllocGPFIFOEx2:181: (STUBBED) called, num_entries=800, flags=1, unk0=0, unk1=0, unk2=0, unk3=0
[   7.920974] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvhost_gpu.cpp:AllocateObjectContext:203: (STUBBED) called, class_num=B197, flags=0
[

### System Configuration

CPU: i7
GPU/Driver: GeForce GT 650M
RAM: 16G
OS: Ubuntu 22.04.3 LTS

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

Also your GPU is 11 years old and way below our minimum requirements.

**Comment by whaleboss** [comment]
> This is an issue tracker for developers and not a support forum. Please use our Discord for support requests.
> 
> Also your GPU is 11 years old and way below our minimum requirements.

the discord only has two channels and there is no way to ask questions
