### ISSUE TITLE
How to solve "MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete" in yuzu linux

### ISSUE THREAD

**Issue by whaleboss** [yuzu-emu/yuzu#11897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

same as title

### Description of Issue

My graphics card is relatively old. 
How can I set it up to successfully start the yuzu emulator?
Do you have any recommended settings?

### Expected Behavior

same as title

### Reproduction Steps

./yuzu/squashfs-root/AppRun

### Log File

ioctl (GFEATURE): Invalid argument
ioctl (GFEATURE): Invalid argument
ioctl (GFEATURE): Invalid argument
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
Segmentation fault (core dumped)

### System Configuration

CPU: i7
GPU/Driver: GeForce GT 650M
RAM: 16G
OS: Ubuntu 22.04.3 LTS

**Comment by v1993** [comment]
Please:

* Use yuzu discord for support requests. This is a bug tracker.
* Do not extract appimages before running them. Just run them directly.
* Post log file as requested, not just stdout.

Either way - that warning is coming from *mesa driver*, not yuzu. The only way to *solve* it is by switching to a GPU that is better supported by it. You may have better luck with OpenGL in some games (segfault you've posted is probably from extracting appimage, not logged warning).

**Comment by whaleboss** [comment]
> Please:
> 
>     * Use yuzu discord for support requests. This is a bug tracker.
> 
>     * Do not extract appimages before running them. Just run them directly.
> 
>     * Post log file as requested, not just stdout.
> 
> 
> Either way - that warning is coming from _mesa driver_, not yuzu. The only way to _solve_ it is by switching to a GPU that is better supported by it. You may have better luck with OpenGL in some games (segfault you've posted is probably from extracting appimage, not logged warning).

i solved the problem finally.
use this command:
sudo apt install nvidia-driver-450.
