### ISSUE TITLE
Bayonetta 3 crash when loading any chapter

### ISSUE THREAD

**Issue by garysassano** [yuzu-emu/yuzu#11906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3949

### Description of Issue

Game always crashes when trying to start any chapter, soon after the loading screen where you can freely do combos. It looks like it's a bad shader being built, which results in yuzu instacrash if you try to restart the game with the bad shader in your cache. If you purge the shaders cache, you are able to get back in the game.

### Expected Behavior

No crash.

### Reproduction Steps

Load Chapter 3.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13198053/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5 5600X
GPU/Driver: 545.92
RAM: 32GB DDR4
OS: Windows 10 Version 21H2 (Build 19044.3570)

**Comment by NimboYT** [comment]
I'm having the same issue and its driving me insane. Please we need a fix asap !!!
