### ISSUE TITLE
In Zelda BOTW water looks like milk

### ISSUE THREAD

**Issue by YigaUpdate** [yuzu-emu/yuzu#11921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1603

### Description of Issue

When I play Zelda BOTW, the water looks like milk.
![01007ef00011e000_2023-10-30_14-01-22-661](https://github.com/yuzu-emu/yuzu/assets/147800620/2f4c55c2-1c72-4136-ab99-a0dd86cad907)
![01007ef00011e000_2023-10-30_14-01-09-719](https://github.com/yuzu-emu/yuzu/assets/147800620/92803c3f-e501-43bd-ba02-d2176e75f42e)
![01007ef00011e000_2023-10-30_13-59-45-805](https://github.com/yuzu-emu/yuzu/assets/147800620/adb8aecb-da98-4777-805a-b67fa9eb233a)

### Expected Behavior

Water looks like water.

### Reproduction Steps

Just look at the water.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13205652/yuzu_log.txt)

### System Configuration

CPU: Intel Pentium Gold 8505
GPU/Driver: Intel UHD Graphics / Driver: 31.0.101.4575 (Latest)
RAM: 8GB DDR4 3200Mhz
OS: Windows 11

**Comment by liamwhite** [comment]
Retry after enabling reactive flushing and disabling asynchronous shaders.

**Comment by FernandoS27** [comment]
> Retry after enabling reactive flushing and disabling asynchronous shaders.

nah, he needs to set accuracy to High.

**Comment by YigaUpdate** [comment]
It worked even though my game is slower.

**Comment by FernandoS27** [comment]
> It worked even though my game is slower.

If it costs you performance, you can just load the game in high and then toogle it to Normal when it gets in-game, you must toogle untoogle whenever it loads in/off.

**Comment by Squall-Leonhart** [comment]
GPU/Driver: Intel UHD Graphics / Driver: 31.0.101.4575 (Latest) < not the latest.

https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

**Comment by YigaUpdate** [comment]
I don't have administrator rights so I can't update them even with windows update.
