### ISSUE TITLE
 MHGU-HD-Project: HD Mod not working/detected on Yuzu

### ISSUE THREAD

**Issue by RainbowedAbyss** [yuzu-emu/yuzu#11928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All

### Description of Issue

According to the developer of the mod, the mod does not work on Yuzu due to a problem in the file structure of the emulator.

More feedback from the developer Monke: "From testing, large sized romfs mods always crash the game with yuzu...".

 Link: https://github.com/Monkbreh/MHGU-HD-Project

### Expected Behavior

Mod to work on Yuzu, if possible.

### Reproduction Steps

The Mod is not detected by Yuzu.

### Log File

NA

### System Configuration

CPU: 3-4 GB
GPU/Driver: Nvidia 
RAM: 16GB
OS: Windows 11

**Comment by Squall-Leonhart** [comment]
The author is incorrect, large romfs mods work fine, the mod probably requires changing the emulated memory layout from 4GB to 6+
