### ISSUE TITLE
donkey kong country tropical freeze infinite loading when changing levels

### ISSUE THREAD

**Issue by Brunokamek** [yuzu-emu/yuzu#11926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

ea 3955

### Description of Issue

the bug occurs when leaving one phase and entering another

### Expected Behavior

![Captura de Tela (108)](https://github.com/yuzu-emu/yuzu/assets/100365618/fee0db76-78b9-4adf-9f5d-a977d4ea2af7)

### Reproduction Steps

the bug occurs when leaving one phase and entering another

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13211127/yuzu_log.txt)

### System Configuration

CPU:Intel® Core™ i5-2500K
GPU/Driver:GT 1030
RAM:8gb
OS:Windows 11

**Comment by Squall-Leonhart** [comment]
out of video memory.
