### ISSUE TITLE
Game shortcuts icon overriding the normal yuzu icon in the task bar

### ISSUE THREAD

**Issue by Majora8120** [yuzu-emu/yuzu#11935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1606 & EA 3959

### Description of Issue

The normal yuzu icon will be replaced by the game shortcuts icon until the shortcut is deleted. this only happens when launching yuzu from the games shortcut or the ones yuzu makes automatically. launching right from yuzu.exe will not cause this. 
![image](https://github.com/yuzu-emu/yuzu/assets/91237086/b9c3036a-72d5-4df2-a1c7-a921e1b9751a)

### Expected Behavior

The taskbar icon stays as the normal yuzu or yuzu ea icon
![image](https://github.com/yuzu-emu/yuzu/assets/91237086/b6e1884d-465f-4e91-b65f-1e9525ce0a51)

### Reproduction Steps

Create a desktop shortcut for a game. close yuzu. launch yuzu using the game shortcut. 
Deleting the game shortcut seems to fix the issue

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13222808/yuzu_log.txt)

### System Configuration

CPU: i3 12100f
GPU/Driver: rx 6600 Driver 23.10.2
RAM: 16GB
OS: Windows 10 22H2

**Comment by Squall-Leonhart** [comment]
Windows is responsible for this.
