### ISSUE TITLE
Unable to join multiplayer lobby when connection to the server is made over phone hotspot

### ISSUE THREAD

**Issue by KrisCris** [yuzu-emu/yuzu#11939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3940

### Description of Issue

I have set up a dedicated multiplayer server hosted on my home server, running inside Docker. It's publicly visible on Yuzu's multiplayer room list, and we can directly connect to it using either the IP address or the domain name.

**Normal Gameplay with Standard Connections**: When our gaming PCs, running Yuzu, are connected to the internet via a regular ethernet cable or standard WiFi, everything works perfectly. We can send messages in the room, create game lobbies, and join them without any issues.

**Issues with Mobile Hotspot Connections**: Issues emerge when any of us attempt to connect to the server via a mobile hotspot, often when away from home:

- **Hotspot User as Host**: When a player using a mobile hotspot initiates a game lobby, others find it impossible to join. We can see the lobby but the game indicates an error when we try to join.
- **Hotspot User Joining**: On the other hand, if the hotspot-connected player tries to join a lobby created by us, the player cannot join correctly: They might perceive themselves as having joined or encountering a black screen. However, from our perspective, they never joined the lobby, or our game stuck when they joined.

The server starts to spam this error when we try to join the game lobby (when connecting to the player using the hotspot)

<img width="1117" alt="Screenshot 2023-11-01 at 8 41 12 PM" src="https://github.com/yuzu-emu/yuzu/assets/38860226/2ca78c3f-c27c-4c54-ab63-ea0bc735d0a1">

Server spams:
```
Network <Error> network/room.cpp:HandleProxyPacket:862: Attempting to send to unknown IP address
```
Client spams:
```
Service.LDN <Error> core/hle/service/ldn/ldn.cpp:GetNetworkInfo:217: NetworkInfo is not valid
```

We usually directly connect to the server via the public IP address or domain name. We had also tried Zerotier, then connecting via the LAN IP. We were able to join the Yuzu multiplayer room and send messages, but when we tried to join the game lobby with someone using a hotspot, it wouldn't work.

I thought there might be something wrong with my friend's phone, but when I tried the Phone Hotspot myself, it failed as well. Btw, our cellular plan is not restricting the hotspot in anyway.

### Expected Behavior

Players using cellular hotspot are able to host/join the game lobby correctly.

### Reproduction Steps

Host a dedicated multiplayer server.

Have two gaming PCs running Yuzu. One connects to a home wifi/ethernet cable, and the other uses the phone's cellular data hotspot.

Connect to the multiplayer server, start the same game, create a game lobby, and join.

---

For the logs I uploaded, I tried 3 times:

For the first two times, the laptop is connected to my iPhone's hotspot, and the steam deck is connected to my home wifi. Both of them are connected to the multiplayer server using the public IP address:

1. The laptop is hosting a game lobby, the Steam Deck tries to join, but the game on the SteamDeck says that a multiplayer error occurred.
2. The Steam Deck is hosting a game lobby, and the laptop tries to join. From the perspective of the laptop, it joined successfully, but on the Steam Deck side, no one has joined the lobby.

The last time I connected my laptop to a different home Wi-Fi (I have 2 fiber networks running in my home):
1. Lobby created and joined successfully.

### Log File

[yuzu_log_laptop.txt](https://github.com/yuzu-emu/yuzu/files/13227857/yuzu_log_laptop.txt)
[yuzu_log_steamdeck.txt](https://github.com/yuzu-emu/yuzu/files/13227860/yuzu_log_steamdeck.txt)

### System Configuration

-

**Comment by liamwhite** [comment]
I think the underlying problem here is that yuzu is not set up to perform NAT traversal and the mobile carrier is using CGNAT, which prevents directly addressing the device.

**Comment by FearlessTobi** [comment]
Thanks for your very detailed report, however we cannot do much about this, since it is very likely an issue with your mobile provider.

**Comment by KrisCris** [comment]
I found a workaround by using VPN: simply establish a VPN connection, e.g. by using Zerotier or OpenVPN, then set the network adapter in Yuzu settings to that VPN adapter.
