### ISSUE TITLE
Do not display "00" files entries into "recent files" tab

### ISSUE THREAD

**Issue by VladimirVSC** [yuzu-emu/yuzu#11949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Every time Mii Editor. Album or Amiibo is being opened, the "00" file entry appears into the "recent files"  tab, which looks useless and untidy. It would be great if firmware applets files not being shown in this tab. (Mainline 1608 was used.)

### Why would this feature be useful?

I guess, "recent files" are for GAME files opened only, not for firmware files. Moreover, while more firmware applets will be emulated in the future, the "recent files" tab may completely turn into "00" files history, as all the applets have the same file name.

**Comment by Squall-Leonhart** [comment]
This has nothing to do with Yuzu

**Comment by german77** [comment]
This only happens because we launch applets as if they where a game
