### ISSUE TITLE
Use yuzu android as remote player

### ISSUE THREAD

**Issue by tom8zds** [yuzu-emu/yuzu#11944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

use yuzu android as remote player, while using phone as controller and gyro, maybe also stream the game view to client

### Why would this feature be useful?

moonlight and steam link has poor controller support for ns style and no gyroscope

**Comment by FearlessTobi** [comment]
I think this is really out of scope.
Yuzu is an emulator, not a game streaming software.

You can already use programs like Parsec for something like this.
