### ISSUE TITLE
Star Ocean: The Second Story R doesn't boot 

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#11945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android v120

### Description of Issue

The game doesn't boot 

### Expected Behavior

the game should boot

### Reproduction Steps

Launch The game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13242367/yuzu_log.txt)

### System Configuration

CPU: sd860
GPU/Driver: Adreno 640/ turnip driver 
RAM: 8gb 
OS: android 13

**Comment by bryangerla** [comment]
same issue, game is just stuck on loading

**Comment by Squall-Leonhart** [comment]
mixed reports of success on desktop too, one video confirms it running on EA 3952

**Comment by tet666** [comment]
> mixed reports of success on desktop too, one video confirms it running on EA 3952

Doesn't work i have everything up to date and the game doesn't boot in the newest EA or  3952.

**Comment by brujo5** [comment]
For reference, the game starts in Skyline but there are a lot of graphical errors later on.
![Screenshot_20231101-203437_Skyline Edge](https://github.com/yuzu-emu/yuzu/assets/4172898/88c76df0-583f-4e78-9238-b0de9abd1ec6)
![Screenshot_20231101-203449_Skyline Edge](https://github.com/yuzu-emu/yuzu/assets/4172898/972ce653-00ad-4108-b3e3-b2a6b93baaa9)
![Screenshot_20231101-203600_Skyline Edge](https://github.com/yuzu-emu/yuzu/assets/4172898/346ea952-5611-4418-bfd5-97b474e19305)

in eggy it works perfectly, it is a very simple and easy game to emulate
![IMG_20231103_060944_229](https://github.com/yuzu-emu/yuzu/assets/4172898/e0c85154-4fd6-42d3-bfc2-73e9fbe465d1)
![IMG_20231103_060943_682](https://github.com/yuzu-emu/yuzu/assets/4172898/6b198547-1185-4300-8c64-d0e92d39bb86)

**Comment by Squall-Leonhart** [comment]
Flagging https://github.com/yuzu-emu/yuzu/pull/11460 as the culprit change.

**Comment by tet666** [comment]
> Flagging #11460 as the culprit change.
> 
> Last working build i've tested is 3850, its broken above 3870, not testing further as a fix is in the works.

I just tried all builds from September and the last build it boots is EA-3867 for me it's broken starting with EA-3868

**Comment by AntunesGean** [comment]
It is working in the version EA-3867. Above that, I couldn't run in any. This on PC.

**Comment by StevensND** [comment]
Fixed on Yuzu 1610 too (Mainline)

![imagen](https://github.com/yuzu-emu/yuzu/assets/45856578/fb7c622c-bd2f-4c3b-ae50-401d606bffef)

**Comment by brujo5** [comment]
on android I have to wait for the build tonight
