### ISSUE TITLE
bilinear downscaling not working

### ISSUE THREAD

**Issue by BPplays** [yuzu-emu/yuzu#11975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

ea 3968

### Description of Issue

if i set my scale higher then my monitors res it does not seem to downscale properly using bilinear and looks a lot worse then if i take a screenshot and downscale it to my monitors res

the comparison is of 
- [left] a yuzu screenshot at the internal game res scaled down in photoshop to my monitors res of 1440p 
- [right] a windows capture of yuzu

![compare](https://cdn.discordapp.com/attachments/783368902255575040/1171041582133284954/5--final--nn--500.png?ex=655b3c76&is=6548c776&hm=4571d5468b67a0b76b432b613098d50d30650028c604c40380c8b31c8c09b0d5&)

### Expected Behavior

i would expect downscaling using bilinear to look the the hires screenshot scaled down in photoshop using bilinear

### Reproduction Steps

set scaling to bilinear in yuzu and look at your screen

### Log File

**Log file redacted due to user pirating**
### System Configuration

CPU: r9 5950x
GPU/Driver: rtx 3090 / 537.34
RAM: 64GB
OS: windows 10

**Comment by FernandoS27** [comment]
which algorithm did you use for downscaling the original image?

**Comment by BPplays** [comment]
if by 'original image' you mean the game res screenshot / the left one then bilinear

**Comment by FernandoS27** [comment]
> if by 'original image' you mean the game res screenshot / the left one then bilinear

You downscaled the original image using photoshop, by default photoshop downscales using a combination of a blur filter with bicubic and a sharpen afterwards. So if you did not specify the downscale to be bilinear then it's likely the result is invalid comparison.

**Comment by G-Spawn** [comment]
Piracy is also not supported here. Closing issue.
