### ISSUE TITLE
Crash team racing 4 players screen on low resolution

### ISSUE THREAD

**Issue by Filosodoge1** [yuzu-emu/yuzu#11973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3965

### Description of Issue

When i played in version yuzu early access 3226, resolution of 4 players is so good, but in versions more updates, the screen of each player is so low like in 480p. I dont know why does this happen? 
Anyone can help me with that?

### Expected Behavior

![image](https://github.com/yuzu-emu/yuzu/assets/60509582/3caf9738-4830-4a3b-afa0-6d64df4e61c7)
![image](https://github.com/yuzu-emu/yuzu/assets/60509582/e2e5f88b-9bbd-494c-bfd4-a4077f5b99c8)
![image](https://github.com/yuzu-emu/yuzu/assets/60509582/908acf21-cab5-4148-9843-aa4948906232)

### Reproduction Steps

s

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13261680/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13261681/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 5 5500 3.60 GHz
GPU/Driver: AMD Radeon RX 6600 8GB/ Drivers updates
RAM: 16 GB
OS: Windows 10

**Comment by G-Spawn** [comment]
This happens on console as well within reason. You're rendering a poorly designed 720p game 4 times in smaller panes. Resolution lowers the more players you have on screen.

Besides that for some of the minor visual differences from earlier yuzu to now would may be due your gpu accuracy and all the other settings you've changed for adapting filter etc.

https://www.nintendolife.com/news/2019/06/video_digital_foundry_finds_crash_team_racing_on_switch_easy_to_recommend
"With all versions running at 30fps, the focus is on the resolution. In docked mode, the Switch release runs at 720p and maintains 1280x720. In contrast, other iterations run at 1080p. Overlooking the age differences, Digital Foundry couldn't resist mentioning how Nintendo's [Mario Kart 8 Deluxe](https://www.nintendolife.com/games/nintendo-switch/mario_kart_8_deluxe) run at 1080p and hits the 60fps target. To make up for the lower resolution, it appears Crash has included additional effects such as motion blur and full ambient occlusion.

**In multiplayer, it's 30fps all around as the resolution drops to 1084x576 if more than two players are involved.** In handheld mode, it's 480p and maintains a resolution of 854x480. The only performance hiccups are tied to the battle mode."
