### ISSUE TITLE
[feature request]: Game compatibility column

### ISSUE THREAD

**Issue by davidhedlund** [yuzu-emu/yuzu#11989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

[Vita3K](https://github.com/Vita3K/Vita3K) has a "[Compat](https://vita3k.org/compatibility.html)" column for all OS builds. It would be useful to adopt this for Yuzu.

# Vita3K examples

## Vita3K for GNU/Linux

![image](https://github.com/cemu-project/Cemu/assets/6416073/391c9e00-38df-4466-82c3-c2c90da9ddda)

## [Vita3K for Android](https://github.com/Vita3K/Vita3K-Android)

![image](https://github.com/cemu-project/Cemu/assets/6416073/59f1b3a8-4638-40c2-8d54-eb6e8cc3c105)

### Why would this feature be useful?

* https://yuzu-emu.org/game/ will change over time.
* People frequently forget to check the compatibility page.

**Comment by liamwhite** [comment]
yuzu also has this. did you turn it off?
![image](https://github.com/yuzu-emu/yuzu/assets/9658600/6838d264-1797-4b37-b69b-fae0c78a8f8c)

**Comment by davidhedlund** [comment]
> yuzu also has this. did you turn it off? ![image](https://user-images.githubusercontent.com/9658600/281749499-6838d264-1797-4b37-b69b-fae0c78a8f8c.png)

I'm using GNU/Linux and I cannot see it. How do you turn it off/on?

**Comment by liamwhite** [comment]
configure -> general -> UI -> show compatibility list. it has to be compiled in to be visible (and it is compiled in on the official AppImage builds as well as the flatpaks.)

**Comment by davidhedlund** [comment]
> configure -> general -> UI -> show compatibility list. it has to be compiled in to be visible (and it is compiled in on the official AppImage builds as well as the flatpaks.)

Shouldn't it be enabled by default? It's not enabled by default in GNU/Linux:

![image](https://github.com/yuzu-emu/yuzu/assets/6416073/9076d644-7bda-4412-8997-2186821c7030)

**Comment by liamwhite** [comment]
It is, in fact, enabled by default. You either explicitly disabled it, or installed a version that is not an official build, which turned the column off.

**Comment by davidhedlund** [comment]
> It is, in fact, enabled by default. You either explicitly disabled it, or installed a version that is not an official build, which turned the column off.

I'm using [yuzu-liftinstall](https://github.com/yuzu-emu/liftinstall)

**Comment by davidhedlund** [comment]
> You either explicitly disabled it

The above screenshot is the default setup (I deleted ~/.config/yuzu, ~/.cache/yuzu, ~/.local/share/yuzu)

**Comment by liamwhite** [comment]
Okay, yeah, it seems the default was turned off at some point.

**Comment by davidhedlund** [comment]
> Okay, yeah, it seems the default was turned off at some point.

* Specifically for Liftinstall or for all builds?
* Can you please give me a reference issue that decided to turn it off.
* Don't you think it should be turned on by default?

**Comment by davidhedlund** [comment]
Hi again Liam. Is there a game compatibility column option for Yuzu for Android?

Can you please check?
