### ISSUE TITLE
Mario Wonder not work in intel graphic 620 with vulcan in windows and linux

### ISSUE THREAD

**Issue by wperesbp** [yuzu-emu/yuzu#11991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Fix for run mario wonder in intel graphics 620 for windows and linux

### Why would this feature be useful?

I believe that is util because many people can have this graphic video driver and them want play mario wonder.

**Comment by goldenx86** [comment]
We can't fix EoL Windows drivers.

Can you get a Linux log file?

**Comment by Squall-Leonhart** [comment]
the spirv crash that was fixed in the Iris and Arc xe package has not been fixed in the Linux driver

**Comment by goldenx86** [comment]
Most likely that doesn't affect gen9.5 graphics anyway.

**Comment by Awesomeangotti** [comment]
I tested this with my own intel igpu (uhd 620) on mario wonder and played for an hour. I went through the first four levels and a few cutscenes. The game did not crash. I was playing on windows

**Comment by FearlessTobi** [comment]
You opened your issue with the wrong template. Also you are using a pretty outdated gpu.
