### ISSUE TITLE
Font size option

### ISSUE THREAD

**Issue by fatGandhi** [yuzu-emu/yuzu#11997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It would be nice to have an option to increase/decrease the font size both in the settings and in the library menu.

### Why would this feature be useful?

It would be useful to those of us struggling to read the small text.

**Comment by FearlessTobi** [comment]
Thanks for your request.
Our font size is controlled by your operating system and can be increased in your system settings.
