### ISSUE TITLE
Mii editor for android 

### ISSUE THREAD

**Issue by Acht-the-Deadf1sh** [yuzu-emu/yuzu#11993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A mii editor for android 

### Why would this feature be useful?

useful for mk8 or miitopia

**Comment by t895** [comment]
Already available in the latest nightly builds https://github.com/yuzu-emu/yuzu-android/releases

**Comment by Acht-the-Deadf1sh** [comment]
Thx

**Comment by Acht-the-Deadf1sh** [comment]
Help, I try to open it but it crashes at 50% when compiling shaders for the mii msker

**Comment by Acht-the-Deadf1sh** [comment]
Maker

**Comment by Acht-the-Deadf1sh** [comment]
Not compiling making

**Comment by Acht-the-Deadf1sh** [comment]
Agh I mean building
