### ISSUE TITLE
Alien Hominid Invasion - DRM issues prevent game from starting

### ISSUE THREAD

**Issue by FetusSandwich** [yuzu-emu/yuzu#11998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Current

### Description of Issue

When attempting to start a new game in Alien Hominid Invasion, [the following error message displays](https://www.reddit.com/r/yuzu/comments/17nsdwx/alien_hominid_invasion_error/) when pressing A at the intro screen to presumably introduce a main menu:

"Failed to add a user for an account that is already in the game."

After pressing A to exit the prompt, you are returned back to the intro screen with no way in which to access the start of a new game.

### Expected Behavior

I load the NSP file and am able to navigate through main menus to start a new game.

### Reproduction Steps

Pressing A to enter the game's main menu produces the error.

### Log File

N/A

### System Configuration

N/A

**Comment by G-Spawn** [comment]
Provide a log file when you can please. There's only so much dev's can assume without it.

**Comment by FetusSandwich** [comment]
Sure thing. This was pulled from a Batocera 37 build. Not sure it really provides much insight, but hope it helps in someway. 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13336208/yuzu_log.txt)

**Comment by G-Spawn** [comment]
We cant support piracy here. Closing
