### ISSUE TITLE
ci.appveyo yuzu ?

### ISSUE THREAD

**Issue by KDZ12** [yuzu-emu/yuzu#12]
when that's out for general public

**Comment by zoltx23** [comment]
Considering it's current progress, maybe a month or so (If it's continuously worked upon.) 

But, I don't think there's any way to dump ROMs as of now. So no games until then. 
Although, that's my word. Hopefully they can get a stable build running soon.

**Comment by KDZ12** [comment]
I hope so because aki in Brazil does not buy Nintendo Switch not too expensive a robbery and if you export it comes out more expensive still hope that project will continue in faith and dev continue in the work of the emulator yuzu I do not have Nintendo Switch if I had my part already would have donated a game and firmware.

**Comment by bunnei** [comment]
This is not the right place for this type of discussion.
