### ISSUE TITLE
Shader cache preloading at start produces unnecessarily large baseline ram usage

### ISSUE THREAD

**Issue by BrainDamage** [yuzu-emu/yuzu#12001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1591 / Flatpak Mainline 1615 ( and possibly many more ))

### Description of Issue

I can reproduce this issue both on my desktop and my steam deck.

Baseline ram usage steadily increases as gameplay hours accumulate, while the baseline-to-peak value is largely unchanged. Out of memory killer closing yuzu becoming increasing frequent as the total play time for a game accumulates, until it reaches the point where few minutes of gameplay trigger it.

Manually deleting/moving yuzu's shader cache temporarily resets the ram usage, to be steadily increasing again as hours of play time accumulates.

Some personal testing values, median filtered for the baseline, using Tears of the Kingdom:

After cache reset:
Base value at game start: 6GB
Usage at main menu: 8GB
Usage between 10 min and 1h of wandering/questing: 9GB

Moving back the old shader cache that I kept from using the game the first time:
Base value at game start: 12.5GB
Usage at main menu: 12.5GB
Usage between 10 min and 1h of wandering/questing: 13GB

My suspicion is that more than half of the shaders in the cache are only used for specific certain areas/scenes. Forcing the emulator to load them at start results in large unnecessary baseline ram usage. 

To rub salt on the wound, mesa-based drivers already have a builtin lazy-loaded disk shader cache. When I delete/move yuzu's cache I get no particular stutters/delays, unlike when I did at game start when there was no cache at all and they had to be built. I realize that cross-platform support means you cannot rely on every platform/driver having it, but yuzu's caching policies create large baseline memory usage for marginal gains.

### Expected Behavior

Lazy-loading the shaders from disk cache as they are necessary. I guess having an option to toggle the behaviour between preload and lazy-load at runtime would be the best to allow people to decide, for people with slow storage and large amount ram vs less ram and fast storage.

### Reproduction Steps

Launch a game with empty shader cache and record ram usage,  I guess open-world stye would exacerbate this behaviour the most due to the variability of the environment.

Accumulate several hours of play time in such game.

Temporarily move/delete the shader cache.

Compare baseline ram usage between accumulated time/accumulated time-but deleted shader cache.

### Log File

Not applicable.

### System Configuration

My desktop:
CPU: Intel  i7-7700HQ
GPU/Driver: GeForce GTX 1050 Ti [nvidia 545.29.02]
RAM: 16GB
OS: Arch Linux

Steam Deck:
CPU: AMD Custom APU 0405
GPU/Driver: AMD VanGogh Custom GPU 0405 [mesa 22.2.0.157821]
RAM: 16GB
OS: Steam OS

**Comment by v1993** [comment]
If you find results with no shader cache acceptable, you can completely disable yuzu's own shader cache.

**Comment by BrainDamage** [comment]
I must've missed that option.

I've tried to play a bit with yuzu's cache off and rely entirely on the driver's, and it seem to work, I only get minor performance penalty on scene switch, but no more random OOM. I guess the ticket can be closed for me, but others may have similar issues if their drivers don't do the caching.

**Comment by FernandoS27** [comment]
We did try lazy loading at some point but it did not eliminate stutter.
