### ISSUE TITLE
Endling: Extiction for ever graphical issue

### ISSUE THREAD

**Issue by SeaKestrel** [yuzu-emu/yuzu#12000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1614

### Description of Issue

At some point in the gameplay, graphic entirely bug
![image](https://github.com/yuzu-emu/yuzu/assets/78849811/6b7deaee-1b44-4ef5-8b53-0fba4e335532)

### Expected Behavior

Should be like this
![image](https://github.com/yuzu-emu/yuzu/assets/78849811/698fcf38-b3be-41d2-882c-b7b29907aa81)

### Reproduction Steps

Play Endling: Extinction for ever using Vulkan

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13323900/yuzu_log.txt)

### System Configuration

CPU: Intel pentium gold 6400
GPU/Driver: Intel® UHD Graphics 610/Vulkan
RAM: 16 Go
OS: Ubuntu 23.10

**Comment by Squall-Leonhart** [comment]
You ran out of video memory, there is no fix.
