### ISSUE TITLE
Infinite loading screen on specific level in Kirby and the Forgotten Land

### ISSUE THREAD

**Issue by SoINinja** [yuzu-emu/yuzu#12017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1618

### Description of Issue

https://github.com/yuzu-emu/yuzu/assets/137450180/7049112d-0bc7-4c77-ba72-11df625289e9

When using the "Warp Star" in the "Northeast Frost Street" level, a loading screen appears, and does not load the next part of the level, and instead keeps me on the loading screen endlessly.

### Expected Behavior

Able load into the next part of the level.

### Reproduction Steps

Game save files: [Save.zip](https://github.com/yuzu-emu/yuzu/files/13329161/Save.zip)

1. Select continue on file 1 in the main menu as shown below.
<img width="1280" alt="Capture" src="https://github.com/yuzu-emu/yuzu/assets/137450180/efff9754-1d98-44cd-b7fb-754c519d55d7">
2. Walk to the star that says "To World Map" and jump onto it.
<img width="1280" alt="Capture2" src="https://github.com/yuzu-emu/yuzu/assets/137450180/715ebbd1-b9d8-4cfa-9ca0-14d780e23819">
3. Once in the world map, continue straight until you reach "Northeast Frost Street", then select the level, then select "continue".
<img width="1280" alt="Capture3" src="https://github.com/yuzu-emu/yuzu/assets/137450180/38b28bbd-f337-4743-a109-197b88324dd0">
4. Continue straight through the level until you reach the next "Warp Star", and jump onto it.
<img width="1280" alt="Capture4" src="https://github.com/yuzu-emu/yuzu/assets/137450180/c1c0677d-3c54-4b8c-8525-437b5ff2278d">
You will now be on a loading screen, and will not load past this point.

### Log File

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/13329226/yuzu_log.zip)

### System Configuration

CPU: 12th Gen Intel(R) Core(TM) i9-12900H
GPU/Driver: NVIDIA GeForce RTX 3060 Laptop. Driver: 31.0.15.3758
RAM: 40GB
OS: Windows 10 Home 22H2

**Comment by liamwhite** [comment]
Retry without mods

**Comment by SoINinja** [comment]
> Retry without mods

Deleted all mods from the "Mod Data Location" on Yuzu. Unfortunately, the issue still persis

**Comment by SoINinja** [comment]
> with your save i got past and completed the level ![01004d300c5ae000_2023-11-13_18-47-27-914](https://user-images.githubusercontent.com/2696404/282443290-c719881b-be20-40ec-9b0c-bc5d75442a86.png)

It's encouraging that it works for you. Would you be able to show what settings you're using for Yuzu?

**Comment by FishOrBear** [comment]
Can you try it after turning off 2x?

**Comment by SoINinja** [comment]
> Can you try it after turning off 2x?
No luck. Also, I reset all settings on Yuzu to default to make sure that wasn't the issue. Didn't seem to change anything. Here's an updated log.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13345049/yuzu_log.txt)

**Comment by Squall-Leonhart** [comment]
put your cpu accuracy back to auto.

**Comment by Squall-Leonhart** [comment]
and barrier feedback loops back on.

**Comment by SoINinja** [comment]
> and barrier feedback loops back on.

Still stuck on the loading screen. Perhaps it's a problem with the game itself? Not too sure.

**Comment by benderscruffy** [comment]
my settings are all on default
redump your game

**Comment by SoINinja** [comment]
FIXED. The game was file was corrupted. Redumping solved the problem.
