### ISSUE TITLE
Pokemon Scarlet Graphic Issue

### ISSUE THREAD

**Issue by BoweTheDon** [yuzu-emu/yuzu#12012]
### Issue

I am using Yuzu Early Access on my Galaxy s23 Ultra.  The graphics on pokemon Scarlet would come out discolored and would still play, I just can't see anything.  I have provided screenshots of the issue.
![Screenshot_20231112_131525_yuzu](https://github.com/yuzu-emu/yuzu/assets/150615701/27f6c316-2081-4ebb-97b1-68ef99e52dfa)
![Screenshot_20231112_131530_yuzu](https://github.com/yuzu-emu/yuzu/assets/150615701/260a88e0-0d16-4bc0-9401-ab3f213d34e2)
![Screenshot_20231112_131704_yuzu](https://github.com/yuzu-emu/yuzu/assets/150615701/bed41620-b183-4b46-98e6-3b7e51624924)
![Screenshot_20231112_131748_yuzu](https://github.com/yuzu-emu/yuzu/assets/150615701/e37efbb8-5350-44ca-af06-7a8e8c520fc8)
![Screenshot_20231112_131945_yuzu](https://github.com/yuzu-emu/yuzu/assets/150615701/75c8e29f-d9b7-4ea8-a818-b31c4f8c6f8a)

**Comment by FearlessTobi** [comment]
You are using the incorrect issue template.
