### ISSUE TITLE
Star Ocean The Second Story R Close on Marze city yuzu Android 

### ISSUE THREAD

**Issue by Victorzeuzz** [yuzu-emu/yuzu#12022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

131

### Description of Issue

When I arrive in Marze city the emulator closes I'm using version 131 of Yuzu Android I can't continue the game

### Expected Behavior

;--;

### Reproduction Steps

Try to enter Marze City to continue the story 

### Log File

;--;

### System Configuration

snapdragom 870
RAM:8

**Comment by FearlessTobi** [comment]
Incomplete issue report.
