### ISSUE TITLE
Luigi's Mansion 3 not saving Co-op option after relaunching game

### ISSUE THREAD

**Issue by JohnnyGuir** [yuzu-emu/yuzu#12026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1616

### Description of Issue

Luigi's Mansion 3 doesn't save the in-game Co-op option after relaunching the game. 
It resets and I have to enable Co-op every time to play with 2 players. The yuzu co-op prompt pops up each time normally and both controllers are ON before launching the game.

### Expected Behavior

Co-op option stays saved after exiting and relaunching the game to be able to directly play with 2 players.

### Reproduction Steps

1. Lauch the game and load a save file to play
2. Go to the in-game menu and enable Co-op and confirm the yuzu Co-op prompt.
3. Exit the menu and the game, stop the emulation
4. Relaunch the game, load a save file; you can not play with 2 players until you have enabled it again in the in-game menu.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13342435/yuzu_log.txt)

### System Configuration

CPU: i5-12600K
GPU/Driver: 4070Ti with 537.34 drivers
RAM: 16GB
OS: Windows 11 Pro 22H2 build 22621.2428

**Comment by german77** [comment]
Have you verified this on console? Usually games don't keep the co-op option.

**Comment by FishOrBear** [comment]
NS will not save it, this is not a bug of the simulator.
