### ISSUE TITLE
超级马力欧RPG 闪退

### ISSUE THREAD

**Issue by jiaozhan** [yuzu-emu/yuzu#12037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Service.Audio

### Description of Issue

刚开始游戏到酷霸必定闪退。

### Expected Behavior

刚开始游戏到酷霸必定闪退。

### Reproduction Steps

刚开始游戏到酷霸必定闪退。

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13358757/yuzu_log.txt)

### System Configuration

CPU:i3 8100
GPU/Driver:Rx 550
RAM:16G
OS:Windows11

**Comment by german77** [comment]
This game is not released yet.
