### ISSUE TITLE
[Android] The king of fighters XIII - broken background texture + turnip drivers broken vk_ext_custom_border_color

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#12052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android v134

### Description of Issue

The game have broken background texture in some places but more noticiable in fight matches

![Screenshot_20231116-075005](https://github.com/yuzu-emu/yuzu/assets/4172898/ded6925f-65ce-4ae9-bb98-15a4ba41b8bf)
![Screenshot_20231116-082046](https://github.com/yuzu-emu/yuzu/assets/4172898/b827b08e-b98f-416b-8cdf-b186f59c954f)

### Expected Behavior

that shouldn't happen

### Reproduction Steps

Play normally

### Log File

[yuzu_log_kof.txt](https://github.com/yuzu-emu/yuzu/files/13379820/yuzu_log_kof.txt)

### System Configuration

CPU: sd870
GPU/Driver: Adreno 650/ turnip driver
RAM: 8gb
OS: android 13

**Comment by brujo5** [comment]
Game work fine in skyline

![Screenshot_20231118-130525](https://github.com/yuzu-emu/yuzu/assets/4172898/910107a8-1e6d-40cb-a51a-04b8b34067a2)

**Comment by AbdullahRizwan101** [comment]
> Game work fine in skyline
> 
> ![Screenshot_20231118-130525](https://github.com/yuzu-emu/yuzu/assets/4172898/910107a8-1e6d-40cb-a51a-04b8b34067a2)
> 

Is skyline an emulator ? Cuz it seems it's not being maintained, surprised that it was able to run the game ?

**Comment by brujo5** [comment]
> > Game work fine in skyline
> 
> Is skyline an emulator ? Cuz it seems it's not being maintained, surprised that it was able to run the game ?

yes it is the last edge that bylaws released

**Comment by lacrdeveloper** [comment]
Same issue for me in pc and android
pc data:
ryzen 7 4800 proccesor
radeon rx5600m 6gb video
memory ram 32gb

android data:
xiaomi pad 5, snapdragon 680 with 6gb ram

also i have latest skyline version and has same issues

**Comment by brujo5** [comment]
On skyline work fine. just use Qualcomm driver end enable directo memory import

**Comment by brujo5** [comment]
Fixed on yuzu 173

**Comment by TBrayner** [comment]
> Fixed on yuzu 173

I'm in The Last Yuzu but still broken.
