### ISSUE TITLE
[Android] Regression – All connected gamepads are mapped to player 1

### ISSUE THREAD

**Issue by NCProduction** [yuzu-emu/yuzu#12057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All builds since 119/120

### Description of Issue

Since build 119 or 120, when additional gamepads are connected, they are all assigned to player 1, making multiplayer games impossible to play. There's the same issue on the latest version of the playstore (build 2f9487cd3)

Up to the build 118 gamepad assignment to player 2/3/4 worked correctly.

### Expected Behavior

When additional gamepads are connected, they should be automatically assigned to player 2, then 3, then 4.

### Reproduction Steps

Launch a multiplayer game (e.g. Mario Kart 8), connect 1-3 additional controllers, all of them will control player 1.

### Log File

[yuzu_log_110902.txt](https://github.com/yuzu-emu/yuzu/files/13390366/yuzu_log_110902.txt)

### System Configuration

CPU: Snapdragon 8Gen 2
GPU/Driver: Adreno740 / Mesa Turnip 24.0.0
RAM: 16Go
OS: Android 13
Device : AYN Odin 2

**Comment by chulinx** [comment]
same question with me

**Comment by BREDJIN5** [comment]
Same with me. I think this has spread to all versions now.

**Comment by chulinx** [comment]
> 和我一样。我认为这现在已经蔓延到所有版本了。

i recovery multiple gamepads in my fork 
https://github.com/chulinx/yuzu-android/releases

**Comment by jmgmmjbcmagb** [comment]
Yuzu team, I test the chulinx version and work fine the local multiplayer, thank you @chulinx, my son is very happy now for they can play thogether

**Comment by ChineseHotPot** [comment]
@chulinx  Will you push your changes to this branch?

**Comment by porianli** [comment]
i have the same thing for the last month 
there is a new official version and its have the same problem 
also all the new github version have this problem 

@chulinx how i can get your fork ? 
your link dont have download link inside

**Comment by chulinx** [comment]
> i have the same thing for the last month there is a new official version and its have the same problem also all the new github version have this problem
> 
> @chulinx how i can get your fork ? your link dont have download link inside

you can test on last build

**Comment by porianli** [comment]
i will give it a try and update 
tnx 🫡

**Comment by AndroidInstance** [comment]
It worked very well and now this big feature is really broken. I’m surprised there is a new version with no fix. Is it possible to find official previous yuzu apk somewhere ? Thanks

**Comment by Freedan101** [comment]
chulinx thanks for your work, what is the difficulty in incorporating this into the main branch? any ideas?

**Comment by bimasena25** [comment]
@chulinx ,
Thanks for your best jobs
Your 172 version works well for multiplayers 4 gamepads

Can you upload again for version 200 ?

**Comment by Eljin-Viernes** [comment]
@chulinx 

Thank you for your amazing job at making it work!

Your 172 version works well for multiplayers upto 4 controllers

Are you able to implement the multiplayer support again for the version 201?

Thank you in advanced! You're the best! 👍

**Comment by Stouf-77** [comment]
@chulinx
Same here. Very happy to can play yuzu with friends on your 172 fork. Any way you can add the lines to the official release, so all the new versions will be multiplayers playbale ?
