### ISSUE TITLE
[Android] unable to use 60 fps mod on GitHub build

### ISSUE THREAD

**Issue by Siber009** [yuzu-emu/yuzu#12051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

GitHub andriod 132/133

### Description of Issue

Unable to use MhGU 60 fps mod on GitHub build but it works fine on EA build.

### Expected Behavior

Game runs at 60 fps

### Reproduction Steps

Put 60 fps cheat in load folder 
Run game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13372002/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 8 gen 2
GPU/Driver: Turnip RX
RAM: 8GB
OS: Android 13

**Comment by t895** [comment]
Please provide a log

**Comment by Siber009** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13371966/yuzu_log.txt)

**Comment by Siber009** [comment]
> Please provide a log

Sorry it wouldn't allow me to add it here you go

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13371970/yuzu_log.txt)

**Comment by drainlin** [comment]
In fact, I know this is probably not caused by yuzu.
I once tried to connect my Android device to the computer and transfer the mod file using MTP.
It may be that the encoding cannot be recognized in yuzu. 
The only solution is to transfer your files through other means. Such as WiFi, ssh or zip compression. I think this might help you.

**Comment by Siber009** [comment]
This was actually resolved in the latest NCE artifact. Using the exact same file copy and pasted the exact same way as before ... Not sure what in this build fixed it but it now works without issue

**Comment by XeroraYT** [comment]
Reviving an old commit to mention it appears to be broken again. S24 Ultra, dynamicFPS 1.5.4 and 1.5.5 paired with the DynamicFPS - 60 FPS mod does nothing. Game is updated to 1.2.1, and it runs locked at 30 FPS even with VSYNC off.
