### ISSUE TITLE
Super Mario RPG US - Wrong character colors during load/save menu

### ISSUE THREAD

**Issue by relu419** [yuzu-emu/yuzu#12063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1624

### Description of Issue

Yellow-ish color for standard Mario clothes

### Expected Behavior

Normal "red cap" and "red clothes" for Mario.

### Reproduction Steps

Go through the load/save menu.
![Sem título](https://github.com/yuzu-emu/yuzu/assets/20247714/da2bfc08-a523-41b1-ab75-a1f8a224c2fd)

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13397758/yuzu_log.txt.old.txt)

### System Configuration

CPU: Core I7 3770
GPU/Driver: Nvidia GTX 1060 6GB
RAM: 8GB DDR3
OS: Win 10 Updated

**Comment by liamwhite** [comment]
Is the wrong color an Nvidia only issue? There are other problems on the save menu but I don't have this one (AMD Linux).
![0100bc0018138000_2023-11-17_16-22-49-495](https://github.com/yuzu-emu/yuzu/assets/9658600/1c8fee65-37bf-4896-b2a9-69074b37a5e4)

**Comment by relu419** [comment]
> Is the wrong color an Nvidia only issue? There are other problems on the save menu but I don't have this one (AMD Linux). ![0100bc0018138000_2023-11-17_16-22-49-495](https://user-images.githubusercontent.com/9658600/283942016-1c8fee65-37bf-4896-b2a9-69074b37a5e4.png)

I don't have AMD GPU to test or another Nvidia GPU. Also, I'm using Vulkan API.

**Comment by liamwhite** [comment]
Just booted up my other machine to test. Not only does Mario's color palette render correctly on AMD, the entire game renders like crap on Nvidia. Weird.

**Comment by brujo5** [comment]
Same bug on android but the good thing is that it's random
![Screenshot_20231117-191504](https://github.com/yuzu-emu/yuzu/assets/4172898/f811c366-f9c1-426e-b8d3-1ca0e1f3dac6)
![Screenshot_20231117-191911](https://github.com/yuzu-emu/yuzu/assets/4172898/bfdc1e56-c5f5-448d-94f1-3f2034b007cc)
![Screenshot_20231117-192952](https://github.com/yuzu-emu/yuzu/assets/4172898/30cc8240-1d8f-4d8c-b7dd-3da5f1b61bb8)
![Screenshot_20231117-194525](https://github.com/yuzu-emu/yuzu/assets/4172898/885e44da-39e5-43bb-9570-23f2c662ae57)

**Comment by liamwhite** [comment]
@brujo5 no, that is clearly a different issue.

**Comment by Orion1189** [comment]
The other rendering issues during save/load screen, as well as pause menus, are currently fixed by setting GPU accuracy to High, at least as a workaround. Does not fix the color issues on Mario's model though.
