### ISSUE TITLE
Network Drive Game Location Forgetting

### ISSUE THREAD

**Issue by 0b5d** [yuzu-emu/yuzu#12065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3979

### Description of Issue

I have my game directory set for a local NAS and until 3979 it has always worked and shown as "//<network>/games/" but as of 3979 the folders location seems to forget it is a network drive and changes to something like this "/<network>/games/" and then can not find the directory until I re-add the directory again.

![Screenshot 2023-11-17 201336](https://github.com/yuzu-emu/yuzu/assets/136409545/479c05f8-108f-471f-95db-08f9bdc8a450)
![Screenshot 2023-11-17 201519](https://github.com/yuzu-emu/yuzu/assets/136409545/6e4954ab-878f-4a3d-9063-c5c76e4c82d7)

### Expected Behavior

Network drive should be reading as "//<network>" instead of "/<network>"

### Reproduction Steps

Add network drive for game directory (Success)

Restart Yuzu 3979 and game directory is now showing "/<network>" instead of "//<network>" (Fail)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13398605/yuzu_log.txt)

### System Configuration

CPU: Intel 13900k
GPU/Driver: Nvidia RTX 4090
RAM: 64GB DDR5 6000mhz
OS: Windows 11 64bit

**Comment by Squall-Leonhart** [comment]
3979 did not touch host file system stuff at all.

**Comment by liamwhite** [comment]
@t895

**Comment by t895** [comment]
Just pushed a fix out earlier today. Could you verify that it works by using mainline yuzu?

**Comment by 0b5d** [comment]
> Just pushed a fix out earlier today. Could you verify that it works by using mainline yuzu?

This now seems to be fixed on both mainline and early access, thanks!
