### ISSUE TITLE
Hogwarts Legacy crashes

### ISSUE THREAD

**Issue by redscorpse** [yuzu-emu/yuzu#12073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu 1624 (flatpak)

### Description of Issue

The game works but crashes. I could successfully create the character and launch the game itself, but when I start the game (the playable part) it crashes after few seconds.

### Expected Behavior

Launch and play the game at least with bad quality graphics.

### Reproduction Steps

I try various configurations and they all end up failing.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13401304/yuzu_log.txt)

### System Configuration

System:
  Host: thinkpad Kernel: 6.1.0-13-amd64 arch: x86_64 bits: 64 compiler: gcc
    v: 12.2.0 Desktop: GNOME v: 43.6 Distro: Debian GNU/Linux 12 (bookworm)
Machine:
  Type: Laptop System: LENOVO product: 21JKCTO1WW v: ThinkPad E14 Gen 5
    serial: <superuser required>
  Mobo: LENOVO model: 21JKCTO1WW serial: <superuser required> UEFI: LENOVO
    v: R2AET35W(1.10) date: 07/20/2023
Battery:
  ID-1: BAT0 charge: 37.1 Wh (66.0%) condition: 56.2/57.0 Wh (98.7%)
    volts: 11.6 min: 11.5 model: BYD L22B3PG5 status: discharging
CPU:
  Info: 10-core (2-mt/8-st) model: 13th Gen Intel Core i7-1355U bits: 64
    type: MST AMCP arch: Raptor Lake rev: 3 cache: L1: 928 KiB L2: 6.5 MiB
    L3: 12 MiB
  Speed (MHz): avg: 529 high: 977 min/max: 400/5000:3700 cores: 1: 977
    2: 400 3: 602 4: 400 5: 853 6: 725 7: 400 8: 400 9: 400 10: 400 11: 400
    12: 400 bogomips: 62668
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Raptor Lake-P [Iris Xe Graphics] vendor: Lenovo driver: i915
    v: kernel arch: Gen-13 bus-ID: 00:02.0
  Device-2: Syntek Integrated Camera type: USB driver: uvcvideo
    bus-ID: 1-7:3
  Display: wayland server: X.Org v: 1.22.1.9 with: Xwayland v: 22.1.9
    compositor: gnome-shell driver: X: loaded: modesetting,nvidia
    unloaded: fbdev,nouveau,vesa dri: iris gpu: i915 resolution: 1440x900~60Hz
  API: OpenGL v: 4.6 Mesa 22.3.6 renderer: Mesa Intel Graphics (RPL-P)
    direct-render: Yes
Network:
  Device-1: Intel driver: iwlwifi v: kernel port: N/A bus-ID: 00:14.3
  IF: wlp0s20f3 state: up mac: e0:2e:0b:af:51:45
  Device-2: Intel vendor: Lenovo driver: e1000e v: kernel port: N/A
    bus-ID: 00:1f.6
  IF: enp0s31f6 state: down mac: e8:80:88:d4:32:95
  IF-ID-1: virbr0 state: down mac: 52:54:00:2c:11:39
Drives:
  Local Storage: total: 476.94 GiB used: 391.83 GiB (82.2%)
Info:
  Processes: 303 Uptime: 19h 9m Memory: 23.16 GiB used: 3.62 GiB (15.6%)
  Init: systemd target: graphical (5) Compilers: gcc: 12.2.0 Packages: 2645
  Shell: Zsh v: 5.9 inxi: 3.3.26

**Comment by Squall-Leonhart** [comment]
You have something consuming a fair amount of ram, even before you start Yuzu,

**Comment by Squall-Leonhart** [comment]
Try this

`sudo sysctl -w vm.max_map_count=262144`

**Comment by RedFeatherMacaw** [comment]
Hey, I'm net to yuzu but I experience the exact same problem with hogwarts legacy, could you please explain step by step what did you change to make it work properly? thanks in advance
