### ISSUE TITLE
Add an option to not show the controller dialog.

### ISSUE THREAD

**Issue by MastaG** [yuzu-emu/yuzu#12079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

We use Yuzu exclusively on Steam Deck connected to the television.
We use multiple Xbox controllers.
Everytime we start Mario Kart 8 Yuzu will fire up a conntroller selection gui when we get to the player selection screen.
This is REALLY annoying.
Because we need to get the wireless keyboard out and only press OK.
This is really troublesome for the small children, because they're too young for this.
For Steam Deck this gui is not required because Steam has its own gui for rearranging the controllers to select which Xinput devices are set to P1, P2, etc.
So a checkbox that keeps Yuzu from displaying it would be really helpful here.

### Why would this feature be useful?

Because I say it is.

**Comment by FearlessTobi** [comment]
This feature already exists.
