### ISSUE TITLE
Super Mario RPG crashing at the first battle

### ISSUE THREAD

**Issue by starthink999** [yuzu-emu/yuzu#12071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mineline 1625

### Description of Issue

I don't know why happen, when I hit an enemy the game crash unfortunately. 
I don't understand about this so much. Could you help me? Pleaseee

https://github.com/yuzu-emu/yuzu/assets/127455248/cce01511-f578-4c54-be69-5d84e94cd7ee

### Expected Behavior

I just hope I can hit the enemy without get crash. Thanks

### Reproduction Steps

I have deleted the saved game, the cache, and reinstalled the yuzu, but it still happens.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13401133/yuzu_log.txt.old.txt)

### System Configuration

CPU: DualCore Intel Core i3-1005G1, 3400 MHz (34 x 100)
GPU/Driver: Intel UHD Graphics (1 GB) Ice Lake-U GT2 32EU
RAM: 8 GB DDR4
OS: Windows 10 Home Updated

**Comment by Squall-Leonhart** [comment]
This IGP is not supported on Windows, sorry.

**Comment by starthink999** [comment]
Sorry, what does IGP mean?

**Comment by Squall-Leonhart** [comment]
>  GPU/Driver: Intel UHD Graphics (1 GB) Ice Lake-U GT2 32EU

integrated graphics, yours has had driver support cut off for windows, leaving it in a state that experiences crashes.

**Comment by starthink999** [comment]
oh, I get it, thanks for the answer

**Comment by brujo5** [comment]
> oh, I get it, thanks for the answer

Try to play with sound disabled in emulator "null"

**Comment by Squall-Leonhart** [comment]
> Try to play with sound disabled in emulator "null"

It isn't that sort of crash
> [ 180.287336] Render.Vulkan <Critical> video_core\vulkan_common\vulkan_device.cpp:ReportLoss:767: Device loss occurred!
