### ISSUE TITLE
Games requiring Fastmem disabled freeze after launching with NCE enabled

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#12084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline + NCE 

### Description of Issue

Games requiring Fastmem disabled freeze after launching with NCE enabled
As example:
Dragon Ball z kakarot
Demon slayer Kimetsu no Yaiba

![Screenshot_20231119-093150_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/a1d80725-2b7e-4a70-bc70-d2138a82896b)
freezes with FPS at 0

Note: The game starts well with dynarmic + fastmem OFF but obviously slow and the phone heats up quickly

### Expected Behavior

that shouldn't happen

### Reproduction Steps

Just play normally 

### Log File

NCE + fastmem OFF
[yuzu_log_fastmem OFF.txt](https://github.com/yuzu-emu/yuzu/files/13403868/yuzu_log_fastmem.OFF.txt)

NCE + fastmem ON
[yuzu_log_fastmem ON.txt](https://github.com/yuzu-emu/yuzu/files/13403871/yuzu_log_fastmem.ON.txt)

### System Configuration

CPU: sd860/sd870
GPU/Driver: adreno 640/650 turnip driver 
RAM: 8gb
OS: android 13

**Comment by liamwhite** [comment]
NCE requires fastmem so this is completely unsurprising.

**Comment by brujo5** [comment]
Indeed

**Comment by liamwhite** [comment]
Fixed in 137

**Comment by brujo5** [comment]
> Fixed in 137

Sir, can these games be played with NCE later? I thought they could but no

**Comment by liamwhite** [comment]
if you turn fastmem off you cannot use NCE. there are no alternatives and no workarounds for it.
