### ISSUE TITLE
One piece pirate Warriors 4 broken textures

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#12086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline + NCE 

### Description of Issue

the game has problems with black textures, invisible and other textures appearing and disappearing

![Screenshot_20231119-104034](https://github.com/yuzu-emu/yuzu/assets/4172898/843332f8-c67c-4925-a356-529f0ea6f66c)
![Screenshot_20231119-104234_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/8b60ea16-f568-473b-b001-cbbe3b93946c)
![Screenshot_20231119-104255_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/cec622f1-0fbd-459e-9f02-ef98338b5d4d)
![Screenshot_20231119-104304_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/7668c8db-f890-40bc-8b1f-ef5cc2739a44)
![Screenshot_20231119-104338_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/82cc8624-25c7-48b3-a4ec-7a936f3a36ef)

### Expected Behavior

that shouldn't happen

### Reproduction Steps

Just play normally 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13404036/yuzu_log.txt)

### System Configuration

CPU: sd870
GPU/Driver: Adreno 650, turnip driver 
RAM: 8gb
OS: android 13

**Comment by ericwalker** [comment]
facing same problem, and hope yuzu can help to fix this bug.

**Comment by brujo5** [comment]
![Screenshot_20231220-134042_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/c24206c6-64b8-44e2-bf4f-4bad75326e48)
![Screenshot_20231220-134226_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/9109d771-c043-43a2-8f11-1955c749131a)
![Screenshot_20231220-134248_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/298dcd7f-a0ce-47ad-af23-80b2ba7819cb)
![Screenshot_20231220-134309_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/8f1e0632-c3c1-4805-9208-7472ac7246c1)
![Screenshot_20231220-134856_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/6091c940-5fee-4a35-9b6a-1102ac85960d)
![Screenshot_20231220-135044_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/fe76655f-1800-48d0-a4b3-dbfadbb2d618)
![Screenshot_20231220-135245_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/39b91b14-d00d-4818-8e54-64b720adde5f)

One piece pirate Warriors 4 
Fixed on latest yuzu 😁
Heavy game still need optimization

**Comment by brujo5** [comment]
@M-hyun 
game version 1.6.0
gpu accuracy normal
turnip r12
