### ISSUE TITLE
Mario+Rabbids: sparks of hope stuck at game loading in emulator 

### ISSUE THREAD

**Issue by Alphonsokurukuchu** [yuzu-emu/yuzu#12080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

NCE build

### Description of Issue

Game just gets stuck in 'building shaders' screen(kept it like that for 5 mins before it closing myself)

### Expected Behavior

Should boot into game

### Reproduction Steps

install the nce build being used publicly, keep everything in default settings (same thing with and without NCE enabled, I've reproduced this 3 times)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13402953/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 865+
GPU/Driver: Turnip v24.0.0 RX
RAM:6gb
OS: android 13(one ui 5.1.1)
*Using Tab S7+

**Comment by liamwhite** [comment]
You do not have enough memory to boot this game

**Comment by Alphonsokurukuchu** [comment]
Okay, but I've heard from BSOD and other that few other games like Ori also get stuck like this in shader building screen
