### ISSUE TITLE
[SMBW] Crash with empty resource table

### ISSUE THREAD

**Issue by MonsterDruide1** [yuzu-emu/yuzu#12090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1626

### Description of Issue

When trying to boot Super Mario Bros Wonder with a mod that removes all restrictions on file sizes, the game crashes from what looks like misinterpreting instruction data.

Use the following file, placed as `romfs/System/Resource/ResourceSizeTable.Product.100.rsizetable.zs`: 
[ResourceSizeTable.Product.100.rsizetable.zs](https://github.com/yuzu-emu/yuzu/files/13404500/ResourceSizeTable.Product.100.rsizetable.zs.dmp)
(Note, I changed the file extension, as GitHub doesn't seem to allow uploading `.zs` files)

This file can be made by converting the original SizeTable to some editable format, and removing all contents for specific files (keeping the original hashes). Program: https://gamebanana.com/tools/13409

### Expected Behavior

On console, this allows the game to boot just fine. On Yuzu, it crashes after pressing L+R on the main screen (still shows loading, but console log shows errors).

### Reproduction Steps

1. Place the file listed above at the given location. Verify that it shows up as a mod in Yuzu.
2. Boot the game, and press L+R on the main screen - maybe even select a save file, if it doesn't crash yet.
3. Game seems to still work just fine, but after going through the other screens to start the game, it just loads infinitely.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13404520/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
GPU/Driver: NVIDIA GTX 1060 6GB, Version 546.01
RAM: 32 GB
OS: Windows 10 22H2

**Comment by liamwhite** [comment]
The game's memory allocator returns null at some point, and it then assigns a vtable pointer into this object, which jumping to later causes a crash. It's not immediately evident to me why the memory allocator has returned null?

**Comment by MonsterDruide1** [comment]
It's likely due to "out of memory" on a specific heap. Normally, the game tries to create a separate heap with known size (barely enough to load the file) for each file, where these sizes are stored in the resource table. When removing the entries from the table, that fixes it somehow. I'm not sure what happens internally, but I'm guessing that Yuzu does not properly emulate this behaviour, and tries to allocate the blocks on a (already full) heap instead.

**Comment by liamwhite** [comment]
yuzu doesn't mess with the game's code, so the more likely explanation is that one of the reported size (free memory, system resource etc.) is wrong and this causes the game to fail to allocate memory at some point.

**Comment by liamwhite** [comment]
I checked all the relevant size outputs from svc::GetInfo and yuzu's outputs are 1:1 with console. Is there a place the game could be querying for free/used memory sizes that might be affected by this?

**Comment by RadiantGlw** [comment]
entering world 3 after progressing from fresh save file with provided ResourceSizeTable.Product.100.rsizetable.zs crashes the game on real console

https://github.com/yuzu-emu/yuzu/assets/151887324/ddeaebce-3754-497c-835d-0f17cb38c22d

![image](https://github.com/yuzu-emu/yuzu/assets/151887324/2887dc44-49c3-42d1-ac37-9c4778f4f894)

**Comment by liamwhite** [comment]
Closing this as not a yuzu bug then - feel free to comment if this is not the case and I will reopen
