### ISSUE TITLE
[Android] Dave the diver stuck on shader cacheing 136 NCE

### ISSUE THREAD

**Issue by Siber009** [yuzu-emu/yuzu#12102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

GitHub 136 NCE

### Description of Issue

When launching Dave the diver cant get past the caching shaders loading screen. 
Things I tried:
Turning off shader cache
Changing to turnip drivers
Clearing cache
Making cache with Jit then launching with NCE 

### Expected Behavior

Game boots 

### Reproduction Steps

Boot game with NCE Enabled 

### Log File

[yuzu_log dave the diver nce.txt](https://github.com/yuzu-emu/yuzu/files/13406617/yuzu_log.dave.the.diver.nce.txt)

### System Configuration

CPU:8 gen 2
GPU/Driver: both system and RX
RAM:8
OS: ANDRIOD 13

**Comment by Squall-Leonhart** [comment]
does this game require fastmem off?

**Comment by Siber009** [comment]
No not to my knowledge boots fine with Jit and fast mem on

**Comment by NightK15** [comment]
It also happened to me with Pokemon Brilliant Diamond and Risk of Rain Returns when I updated them.

**Comment by Siber009** [comment]
> It also happened to me with Pokemon Brilliant Diamond and Risk of Rain Returns when I updated them.

Interesting, for risk of rain returns what version are you on ? I'm on 1.0.1 and the game runs extremely well on NCE

**Comment by NightK15** [comment]
> > It also happened to me with Pokemon Brilliant Diamond and Risk of Rain Returns when I updated them.
> 
> Interesting, for risk of rain returns what version are you on ? I'm on 1.0.1 and the game runs extremely well on NCE

I used 1.0.1 as well, I waited around 10 minutes and nothing happened. Could it have something to do with the CPU? Or perhaps it's another thing, I tested the artifact build btw.

**Comment by Siber009** [comment]
> > > It also happened to me with Pokemon Brilliant Diamond and Risk of Rain Returns when I updated them.
> > 
> > 
> > Interesting, for risk of rain returns what version are you on ? I'm on 1.0.1 and the game runs extremely well on NCE
> 
> I used 1.0.1 as well, I waited around 10 minutes and nothing happened. Could it have something to do with the CPU? Or perhaps it's another thing, I tested in the artifact build btw.

Interesting i had it running on artifact and on 136.  i'm on 8 gen 2 so maybe its that? i'm not sure what keys are you on?

**Comment by liamwhite** [comment]
Fixed in 137
