### ISSUE TITLE
Super Robot Wars T [ASIA], High Slowdown Game/Music

### ISSUE THREAD

**Issue by KaosuKishi** [yuzu-emu/yuzu#12108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1627

### Description of Issue

Whe running the game, both music and game act like a slowed-down video, it's hard to describe. Both Super Robot Wars V and X do not have this issue, so I don't know what might be causing this.

### Expected Behavior

Both sound and game should run smoothly, no stuttering like a slowed down video.

### Reproduction Steps

Unfortunately, as I don't know the cause, I don't know how to replicate it.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13418546/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5 3600XT 6-Core Processor 3.79 GHz
GPU/Driver: NVIDIA GeForce RTX 3060 Ti
RAM: 16,0 GB
OS: Windows 10 Pro 19044.3086

**Comment by liamwhite** [comment]
You should probably try disabling your cheats

**Comment by KaosuKishi** [comment]
> You should probably try disabling your cheats

Gah, I feel stupid. Like I said, it didn't happen for the other two.... Thanks.
