### ISSUE TITLE
Label bounties with label:bounty and update all bounties.

### ISSUE THREAD

**Issue by TouchstoneTheDev** [yuzu-emu/yuzu#12103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

![image](https://github.com/yuzu-emu/yuzu/assets/101004444/5561b4ff-08af-463b-9b70-59c6cbd39d93)

### Why would this feature be useful?

For solving feature request faster

**Comment by FearlessTobi** [comment]
All of these bounties have been fixed, therefore no label is necessary.
I have opened a PR to our website to move all of them to the completed status: https://github.com/yuzu-emu/yuzu-emu.github.io/pull/383.
