### ISSUE TITLE
[Android] Manual Controll Mapping for Controllers.

### ISSUE THREAD

**Issue by MIJS1019** [yuzu-emu/yuzu#12119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Allow to manually map a controller. This Issue was mentioned 7Months ago and if I'm not mistaken I believe it was forgotten. 

### Why would this feature be useful?

Since Yuzu Android improves a lot in terms performance I think it's definetly the time that we have a manual mapping feature for a variety of Controllers.

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/11124.
