### ISSUE TITLE
Overcooked 2 ERROR [Request]

### ISSUE THREAD

**Issue by Dantttt** [yuzu-emu/yuzu#1211]
53.280237] Kernel.SVC <Warning> core/hle/kernel/svc.cpp:ResetSignal:811: (STUBBED) called handle 0x0022004C
Overcooked 2 spams this message infinitely,I was booting it for an hour

**Comment by FearlessTobi** [comment]
Again, we don't accept issues that don't contain a full log. Also please report those issues on Discord as we are not really able to help you here.

**Comment by Hexagon12** [comment]
Stop making issues without any info. 

Requesting to close.
