### ISSUE TITLE
Yuzu resets each time I start it up

### ISSUE THREAD

**Issue by V3loc1ty-9** [yuzu-emu/yuzu#12118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1627 & 1628

### Description of Issue

Ever since the 1627 update on 20/11/23 and then later 1628 on 21/11/23, every time I launch Yuzu the emulator is asking me to set up my game's folder and every setting in the emulator is reset, making me manually set the correct games folder and settings each time I close Yuzu and re-open it. Never experienced Yuzu resetting on me each time I open it, it started since the 1627 update.

### Expected Behavior

Yuzu shouldn't reset it's settings each time I start it up.

### Reproduction Steps

Open Yuzu.

### System Configuration

CPU: I5 13600KF
GPU/Driver: RX 6650 XT
RAM: 32GB, 16x2 Dual Channel @3200MHz
OS: Windows 11 64-bit

**Comment by G-Spawn** [comment]
try to post a log file that isn't empty if possible.

**Comment by V3loc1ty-9** [comment]
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13428476/yuzu_log.txt.old.txt)

**Comment by german77** [comment]
Pretty much explains the issue

Frontend <Error> frontend_common\config.cpp:WriteToIni:60: Config file could not be saved!

**Comment by V3loc1ty-9** [comment]
Why is it being automatically deleted each time I launch Yuzu? I've been using Yuzu for over a year and such issue never occurred to me. It seems the emulator isn't remembering my settings and resets them on startup, but I can't figure out why. Like I mentioned, said issue only started happening after the 1627 from yesterday.

**Comment by german77** [comment]
We are migrating our settings to unify Qt, SDL and android frontends. Is not deleting the config, is not even saved. Can you put the full `%appdata%/yuzu ` path here. I wonder if you have a special character on the file path that is preventing from saving to the file

**Comment by V3loc1ty-9** [comment]
Yeah, the name of my Windows user is in Hebrew, which is probably foreign to the emulator as I see it.
Here's the Yuzu Folder path - C:\Users\מאיר בן שלוש\AppData\Local\yuzu. The Folder which is between "Users" and "AppData" is in Hebrew.

**Comment by V3loc1ty-9** [comment]
Ok. Thank you so much for clearing that up!

**Comment by whitewolf1442** [comment]
I would like to chime in and say that I have the exact same issue and my file name is in arabic, pls pls fix this soon im gonna miss the animal crossing npc that spawned today

**Comment by german77** [comment]
Already fixed. Tomorrow build should be good.

**Comment by whitewolf1442** [comment]
Cannot thank you enough, a modern hero

**Comment by german77** [comment]
I didn't fixed this issue. Just keeping track of the issue. All credits go to t895
