### ISSUE TITLE
KarmaZoo loads into a black screen with the game/audio running behind it.

### ISSUE THREAD

**Issue by boomercore** [yuzu-emu/yuzu#12111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3984

### Description of Issue

Upon loading the game, after the initial static splash screen, it'll go to black with audio playing the background.  You can hear the menu being navigated as you mess with the controls and even see the graphics for a millisecond when you toggle handheld/docked.

### Expected Behavior

The game will display its graphics.

### Reproduction Steps

Simply loading the game into the emulator.  This happens regardless of memory size, API, API options, and CPU+GPU accuracy settings.

### Log File

**Log file removed by moderator**

### System Configuration

CPU: AMD 5800X
GPU/Driver: Nvidia 4070 RTX
RAM: 32gb
OS: Win10

**Comment by SleepingSnakezzz** [comment]
We do not support piracy here. Everything for yuzu comes from your own Nintendo Switch.
