### ISSUE TITLE
[Android] Device built-in controls are no longer detected except in specific games

### ISSUE THREAD

**Issue by liartes** [yuzu-emu/yuzu#12121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 2f9487cd3

### Description of Issue

This issue have been observed on a specific Android Handheld (KTR1) by multiple users.

The KTR1 physical buttons were detected seamlessly until recently. Now the physical buttons work in Yuzu's menu, but are not mapped as a controller once in a game.
The community have found one exception so far : the game Sea of Stars have correct physical controls mapping.

This build have the KTR1 controls mapped correctly in the games I have tested : Mainline 2921a2426

### Expected Behavior

The KTR1's physical buttons should be detected and mapped as a controller without extra steps. Just like before, in build number

### Reproduction Steps

I experienced this issue with The Messenger, Volgarr, Voice of Cards, The Mortuary Assistant so far.
Try and run any of these games on the KTR1. The physical buttons are not detected/mapped. Only the overlay work.
Run Sea Of Stars. The physical buttons are correctly detected.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13429857/yuzu_log.txt)

### System Configuration

CPU: Helio G99
GPU/Driver: Mali-G57
RAM: 6Go
OS: Android 12

**Comment by footnmouth5** [comment]
It is the same on my KTR1 device. Additionally, the controls are not recognized in Metroid Dread as well.

**Comment by Shigarui** [comment]
I have experienced the same issue with several of the latest builds, I had to revert to the last Previous Playstore Update from either September or October.

**Comment by footnmouth5** [comment]
Dead Cells is one other game that does recognizes physical controls in yuzu.

**Comment by Shigarui** [comment]
From some testing it appears that Yuzu build Android-159 is detecting the controls on the KTR1 and then assigning them to controller 2. This became evident as I was testing games to see which ones would recognize the controls and which would not. The game Circuit Superstars shows very clearly that we are assigned controller #2 and are considered a Guest by the system. There is no way to change this assignment in the game. I think it's possible that the reason some games recognize the controls and some do not is because some games can respond to either controller as the master input depending on who initiates the game. Is there a way to defer this assignment to controller #1 so that each game will recognize us as the primary user?

**Comment by liartes** [comment]
After further testing, the issue appear between development build 118 and development build 119.
The releases comparison show some work have been done on the file InputHandler.kt, this look like a good starting point to investigate.

**Comment by liartes** [comment]
After inspecting the code, this issue is caused by
` 
val deviceIds = InputDevice.getDeviceIds()
`
in InputHandler.kt, line 418.

The resulting array contains 2 devices ID for the KTR1's gamepad, the first one is in fact not mapped to the device physical buttons.
A quick and dirty fix for this device is to reverse deviceIds content, getting the "real" one on the first position.

`
val deviceIds = InputDevice.getDeviceIds()
deviceIds.reverse()
`

This is not a valid fix to integrate in the code, from Yuzu's perspective giving some user interface to map an input device to a player could be a good way to solve the KTR1's current issue, and maybe useful for others controllers not properly mapped to player 1.

**Comment by Smurf-IV** [comment]
As this is a "Regression" can the problem be fixed soon, 
and 
then create a new "Feature Request" for the key mapping please ?

**Comment by t895** [comment]
Solved by #13034
