### ISSUE TITLE
Choosing a main profile

### ISSUE THREAD

**Issue by andretietz** [yuzu-emu/yuzu#12132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

There are some games where I cannot choose the profile, I want to save my game into (e.g. Pokemon Arceus), it seems that it saves it on the last created profile. 
And there are other games which respect the profiles (e.g. mario wonder).

For this reason I am suggesting a simple flag for a main profile, that is automatically set for the default or the first profile (when created)

### Why would this feature be useful?

with this everyone would be able to save her/his games in which profile they want, even if the games doesn't support it.

**Comment by Squall-Leonhart** [comment]
These games only do an on start profile select, not while the game is loaded, so their behavior is correct. Your suggestion would deviate even further from hardware behavior and ryujinx and is undesirable.

Enable the profile selection prompt in settings, and you'll get the switch behavior of prompting on game start.

**Comment by G-Spawn** [comment]
> These games only do an on start profile select, not while the game is loaded, so their behavior is correct. Your suggestion would deviate even further from hardware behavior and ryujinx and is undesirable.
> 
> Enable the profile selection prompt in settings, and you'll get the switch behavior of prompting on game start.

^ closing for aforementioned reason.
