### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Hariu7** [yuzu-emu/yuzu#12136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 138

### Description of Issue

The legend of zelda breath of wild crash on snapdragon 865 processor 

### Expected Behavior

I should not crash

### Reproduction Steps

No

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13448901/yuzu_log.txt.old.txt)

### System Configuration

CPU:snapdragon 865
GPU/Driver:650
RAM:8+8
OS:android 13

**Comment by Hariu7** [comment]
16 gb of ram only 2.4 gb ram useb

**Comment by FearlessTobi** [comment]
Closing due to incomplete issue template / low-quality report.
