### ISSUE TITLE
[android] iron lung boot to title screen, but black screen ingame

### ISSUE THREAD

**Issue by maskedforver** [yuzu-emu/yuzu#12141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu android

### Description of Issue

They game boot and the title screen works fine the introduction text is visible but after it the screen is all black but still work and can enter the map
![Screenshot_20231123_183338](https://github.com/yuzu-emu/yuzu/assets/135531617/12060931-360b-4bcc-b443-385e22a36fc5)
![Screenshot_20231123_183345](https://github.com/yuzu-emu/yuzu/assets/135531617/51becbf4-aca7-4260-bf9a-993bfe6b8949)

### Expected Behavior

The game textures load and isnt black

### Reproduction Steps

Start a new game

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13452237/yuzu_log.txt.old.txt)

### System Configuration

CPU:sd865
GPU/Driver:any
RAM:8gb
OS:android

**Comment by german77** [comment]
I can't help to notice your screenshots are from skyline

**Comment by maskedforver** [comment]
> I can't help to notice your screenshots are from skyline

Oh i use a frontend iam sorry i didnt notice that i was using skyline will see if it works on yuzu

**Comment by maskedforver** [comment]
> I can't help to notice your screenshots are from skyline

I just retested it using yuzu this time and same exact thing

**Comment by maskedforver** [comment]
> I can't help to notice your screenshots are from skyline

Here are new screenshots ![Screenshot_20231126_114242_yuzu.jpg](https://github.com/yuzu-emu/yuzu/assets/135531617/e08cb4e6-7d27-4905-8fa6-6cdac5d5e5b2)

![Screenshot_20231126_114250_yuzu.jpg](https://github.com/yuzu-emu/yuzu/assets/135531617/c6642c74-9f3e-4191-aa7b-c91131935929)
