### ISSUE TITLE
Yuzu Analog stick Laggy 

### ISSUE THREAD

**Issue by PinoKyooo** [yuzu-emu/yuzu#12143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All yuzu versions 

### Description of Issue

When I play Naruto storm 4 or connections or any game that requires analog to walk the fps drops from 30 to 19 or less , that's why I always avoid using the analog stick while Playing. I really hope this issue gets fixed as soon as possible for us dimensity users.

### Expected Behavior

I hope the fps won't drop when using the analog stick 

### Reproduction Steps

.

### Log File

.

### System Configuration

CPU:Dimensity 1300
GPU/Driver:Mali-G77 MC9
RAM:8
OS:13

**Comment by FearlessTobi** [comment]
Incomplete issue report.
