### ISSUE TITLE
[Android] A hat In Time always crashes at the same place

### ISSUE THREAD

**Issue by mosestyle** [yuzu-emu/yuzu#12185]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Yuzu 233

### Description of Issue

A Hat In Time game works and runs very good and I'm getting a stable 30FPS through the entire game, without any issues.
The crash however occurs whenever i try to play chapter 3, it always crashes at the same spot when it's trying to load the map.

- I'm using Snapdragon 8 gen 2 with 16GB ram, 
- The game is fully updated,
- I'm using latest firmware
- also using Turnip RX and R11-16 driver.

I asked about this in Discord and both Ghost and SwissTe was kind enough to even try this on their PC to see if this only happened on Android or also on PC. Well for some reason it froze their PC and also killed it into BSOD. So in this case it's both on Android and PC.

I'm also going to upload Video of where this crash occurs, the log and a savefile to test this out.

https://github.com/yuzu-emu/yuzu/assets/76072822/26690c8b-b7bf-41e3-894e-d332a79ccc79

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13466546/yuzu_log.txt.old.txt)

[yuzu_saves_-_2023-11-26_02_00.zip](https://github.com/yuzu-emu/yuzu/files/13466547/yuzu_saves_-_2023-11-26_02_00.zip)

### Expected Behavior

The game always crashes when trying to play Chapter 3.

### Reproduction Steps

I uploaded a video and the save file to reproduce this.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13466548/yuzu_log.txt.old.txt)

### System Configuration

Snapdragon 8 gen 2 with 16GB ram.
Yuzu V233
Turnip Driver R11-16+ Qualcomm drivers.
Android 13

UPDATE: (Edited the text since the problem still occurs even on the latest build, which is 233 as i wrote this update).

**Comment by roninspin** [comment]
The same problem exists on PC. It occurs with installed update and DLCs for the game when you load chapter 3. The memory overflows and the emulator crashes.
P.S. Ryujinx doesn't have this problem.

**Comment by mosestyle** [comment]
> The same problem still exists even on PC. It occurs with installed update and DLCs for the game when you load chapter 3. The memory overflows and the emulator crashes. P.S. Ryujinx doesn't have this problem.

So its a memory leak issue? Do you think it would be possible to fix this issue?
I mean if it doesn't crash on Ryujinx, then it should be possible to fix this?.
Other than that it works perfectly.
