### ISSUE TITLE
Building sharder before game start

### ISSUE THREAD

**Issue by Hariu7** [yuzu-emu/yuzu#12182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I think yuzu should add feature that build all sharder of game before start and store it

### Why would this feature be useful?

As it heavy process to build sharder , building sharder before game  start will increase  performance

**Comment by Squall-Leonhart** [comment]
I think you ticked the box without actually searching.

**Comment by goldenx86** [comment]
This isn't viable with the complexity of the Switch's GPU.

It would be faster to convince the game developers to update the game to trigger all shaders at boot. Good luck with that.
