### ISSUE TITLE
[Android] add combo button

### ISSUE THREAD

**Issue by Hariu7** [yuzu-emu/yuzu#12181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It is very hard to use two buttons at one time .
It is easy in case of keyboard or gamepad but in screen touch 

### Why would this feature be useful?

It will help gamer to gain better gameplay experience. 🎮

**Comment by Hariu7** [comment]
Best

**Comment by goldenx86** [comment]
I recommend to buy a gamepad.

**Comment by Hariu7** [comment]
> I recommend to buy a gamepad.

I am student so I have no money

**Comment by G-Spawn** [comment]
Your switch comes with two controllers 🤷‍♂️
