### ISSUE TITLE
Yuzu Android Xbox controller mapping automatically with Nintendo layout

### ISSUE THREAD

**Issue by Sergiow823** [yuzu-emu/yuzu#12197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

external inverted control

### Why would this feature be useful?

original layout for a better experience in external control, which are inverted

**Comment by EgoBizarro** [comment]
You mean you want e.g. the Pro Controller's A button mapped to the XBOX controller's A button?
But then everything feels wrong when you play. Imagine playing Mario and having to hold the A button to run and the B button on the XBOX controller to jump.

**Comment by naif04** [comment]
Also experienced this one. Yuzu 143 has inverted control for external controllers. A turns to B, X turns to Y, and vice versa. In other versions of Yuzu (such as previous 142), it doesn't behave this way.

**Comment by Squall-Leonhart** [comment]
Use a mod.

**Comment by JC0n710** [comment]
Im fine with it turning xbox in switch style in yuzu.
But when i swap my gamesir x2 pro to switch layout. Yuzu then switches it to xbox layout.

I would prefer to leave the switch layout on for rest of my uses.

**Comment by snowsh1ne** [comment]
> Use a mod.

What do you mean? A game mod? So every game with an XBOX controller needs to be modded? Doesnt seem practical.
I would love to just have an option in the settings to switch between XBOX and Nintendo layout globally

**Comment by Day1721** [comment]
As a fellow gamesir x2 controller user having issues with ABXY, I've looked into why it started to swap on my gamesir controller, and from what I can see it is detected as a redmagic controller, for which keys are programmed to be swapped. While this can make sense for redmagic controller (as it follows xbox layout only), gamesir x2 allows users to swap between xbox and nintendo layout.
Best solution would surely be an option for users to remap buttons themselves, but this may take some time to make so I suggest adding an option to swap AB & XY to yuzu settings for time being.
Code line responsible for swapping here: https://github.com/yuzu-emu/yuzu/blob/master/src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/InputHandler.kt#L30C23-L30C48
![Screenshot_20231211-110645_Gamepad_Tester](https://github.com/yuzu-emu/yuzu/assets/12055858/eaf1c40a-3891-490b-9539-464d3d35852e)

**Comment by dannygaray60** [comment]
why not just swap the buttons in the code directly as they did with other control brands for 'getInputXboxButtonKey' in [Inputhandler.kt? L198](https://github.com/yuzu-emu/yuzu/blob/master/src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/InputHandler.kt#L198C22-L198C22)

**Comment by Squall-Leonhart** [comment]
because thats the wrong way to do it.

You can override bad mappings with gamecontrollerdb.txt @ https://github.com/gabomdq/SDL_GameControllerDB

**Comment by t895** [comment]
Solved by #13034
