### ISSUE TITLE
Problemas de falsos positivos desde después de la primera apk con nce

### ISSUE THREAD

**Issue by Benyi25** [yuzu-emu/yuzu#12199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Todas las compilaciones después del la primera beta nce

### Description of Issue

He estado usando la primera versión de nce, intenté seguir actualizando a las siguientes, pero después tuve 2 alertas, seguro son falsos positivos, pero no entiendo, la primera beta nce no tenía ningúna alerta.

Según el análisis el problema está en el archivo classes.dex

Skyhigh (SWG)
BehavesLike.DEX.Suspicious.wg

TrendMicro-HouseCall
TROJ_GEN.R002V01JE23

### Expected Behavior

La primera versión no tuvo problemas

### Reproduction Steps

Según el análisis el problema está en el archivo classes.dex

BehavesLike.DEX.Suspicious.wg" parece ser un nombre asociado a una detección de software sospechoso por parte de un programa antivirus o de seguridad. Este tipo de notificaciones suelen estar relacionadas con comportamientos inusuales o patrones de código que podrían indicar actividad maliciosa

### Log File

Resolver

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by liamwhite** [comment]
This issue tracker only accepts reports in English.

**Comment by Benyi25** [comment]
Espero puedan resolver
