### ISSUE TITLE
[Android] Graphical and sound glitches occuring when recording gameplay 

### ISSUE THREAD

**Issue by SuperoakWood** [yuzu-emu/yuzu#12207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

[Android] GitHub Build Version 136 up to 144 

### Description of Issue

When recording screen using Miui screen recorder,the entire game starts glitching visually and the sound breaks,making everything mute
Supposedly affects other MIUI devices also.
https://github.com/yuzu-emu/yuzu/assets/152236841/31abd43c-d54c-4442-a87b-de0e595fe4d1

### Expected Behavior

It expected for the recorder to not break the graphics and mute the Emulator 

### Reproduction Steps

Load Yuzu, enter the game and start Recording 
Preferably on a Xiaomi Device

### Log File

[Uploading yuzu_log.txt.old.txt…]()

### System Configuration

CPU: Snapdragon 8+ Gen1
GPU/Driver:Adreno 730,Turnip 24.0.0 Revision RX,R11 and Turnip 23.3.0 Revision 9,along with Turnip 24.0.0 WTFV2 
RAM:12GB
OS:MIUI 14.0.16

**Comment by liamwhite** [comment]
I'm not sure how this is a yuzu bug?

**Comment by Weab-chan** [comment]
Does it happen with system drivers? Likely related to the newer turnip drivers

**Comment by Jerriv4** [comment]
Same here, I have a Samsung tab s8 with 8 gen 1 and I get glitches on certain games like Mario Wonder, I don't get it on other games like Donkey Kong tropical freeze or sonic superstars

**Comment by SuperoakWood** [comment]
> I'm not sure how this is a yuzu bug?

The fact it is happening to multiple other people using their system recorder,so it either a problem with system recorders causing a problem with yuzu,or yuzu doesn't support/hates most recording apps

**Comment by Weab-chan** [comment]
Does it happen with system drivers?

**Comment by liamwhite** [comment]
Definitely seems like an issue with turnip then. I do not see any way yuzu can resolve this on its own?

**Comment by liamwhite** [comment]
As this does not happen with the system drivers, and I cannot see any way yuzu can actually cause this problem, I am closing this issue and recommending you file a report for turnip: https://gitlab.freedesktop.org/mesa/mesa/-/issues

**Comment by SuperoakWood** [comment]
> As this does not happen with the system drivers, and I cannot see any way yuzu can actually cause this problem, I am closing this issue and recommending you file a report for turnip: https://gitlab.freedesktop.org/mesa/mesa/-/issues

Thanks,I will do it when I get the time

**Comment by SuperoakWood** [comment]
> Does it happen with system drivers?

Qualcomm ? No but it still breaks sounds like usual

**Comment by liamwhite** [comment]
I expect sound issues to be resolved by https://github.com/mozilla/cubeb/pull/768
