### ISSUE TITLE
 problems with false positives after first apk with nce

### ISSUE THREAD

**Issue by Benyi25** [yuzu-emu/yuzu#12200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android-137 onwards

### Description of Issue

After the first beta with nce on Android, I have not been able to continue using the other versions, they have all been alerting me, they are surely false positives, but according to the review the problem is in the classes.dex files

Skyhigh (SWG)
BehavesLike.DEX.Suspicious.wg

TrendMicro-HouseCall
TROJ_GEN.R002V01JE23

### Expected Behavior

BehavesLike.DEX.Suspicious.wg" appears to be a name associated with a detection of suspicious software by an antivirus or security program. These types of notifications are usually related to unusual behavior or code patterns that could indicate malicious activity

### Reproduction Steps

review

### Log File

review

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by Squall-Leonhart** [comment]
Take it up with trend micro, false positives are not a concern of a bug tracker.
