### ISSUE TITLE
Game not rendering

### ISSUE THREAD

**Issue by xwinno** [yuzu-emu/yuzu#1221]
Hi, when i try to run a game like The Binding Of Isaac, the game doesn't render image, just sound.

Yuzu build:
Canary b4abedf

Hardware:
Nvidia GTX 970
Intel i5 4430 3.00 GHz

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2342547/yuzu_log.txt)

**Comment by ReaperOfSouls1909** [comment]
turn on docked and turn off multi core
