### ISSUE TITLE
Qualcomm V746 driver update broken on yuzu only

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#12215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

V143

### Description of Issue

Hello, I just received a driver update, v746 but for some reason yuzu runs the games with a black screen while the other switch emulators like Skyline, egg ns, strato work well and there is an increase in FPS performance.
I would like to know if there will be any solution or I'll consider it closed.  It's strange that no other emulator has a problem with vulkan.

### Expected Behavior

It should look normal like any other driver

### Reproduction Steps

Just launch game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13492551/yuzu_log.txt)

### System Configuration

CPU: sd870
GPU/Driver: Adreno 650/ v746 Qualcomm driver
RAM: 8gb
OS: android 13

**Comment by BSoDGamingYT** [comment]
Adding a link to the affected driver would be a useful addition to this issue. 

Reproductions isn't quite as simple as "Just launch game".

**Comment by liamwhite** [comment]
If there is a public link to an update zip or factory reset tool from the vendor that includes the driver, we can extract it from that.

**Comment by brujo5** [comment]
> If there is a public link to an update zip or factory reset tool from the vendor that includes the driver, we can extract it from that.

I use the driver in the system, this is a flashable module for magisk (root user) I can convert it to adpkg for adreno tools but I cannot guarantee that it works due to the lack of libraries.  It is for a650 and on other GPUs it can also work but there may be graphic errors due to the lack of sqe firmware

https://anonymfile.com/yrXX/ogl-vk-v746.zip

![Screenshot_20231128-122228_Franco_Kernel_Manager](https://github.com/yuzu-emu/yuzu/assets/4172898/0133ce22-03aa-41b4-986f-be401caf3c63)

**Comment by Weab-chan** [comment]
That driver isn't made for your device so it's normal to see glitches like this.. unless you have a device that ships with it, I wouldn't try to debug this issue

**Comment by brujo5** [comment]
The driver is from Meta Quest 2 and practically uses Adreno 650 just like the Poco F4, both devices are Kona motherboards, and practically any emulator works well with vulkan, even the other switch emulators like Skyline and egg ns as I had already said.
These types of drivers have been used since Skyline with adreno tools and the dev bylaw.
Anyway I appreciate your response.  thx

**Comment by Weab-chan** [comment]
I wonder if this issue happens on the quest 2 too then.. if so, it would be a legitimate issue.. if no one on the dev team got one, I'll try it on my quest 2 when I'm back home

**Comment by brujo5** [comment]
Thx to @liamwhite 

![Screenshot_20231129-220359](https://github.com/yuzu-emu/yuzu/assets/4172898/82d339c1-21ca-4ccb-a997-28aac70ae376)
![Screenshot_20231129-221739_Franco_Kernel_Manager_1](https://github.com/yuzu-emu/yuzu/assets/4172898/60bf448a-0084-4330-9fcf-823f55e5e210)
