### ISSUE TITLE
(Android)HW.memory Unmapped TOTK Subterranean world

### ISSUE THREAD

**Issue by Skyjack89** [yuzu-emu/yuzu#12220]
No issue for this yet.

Description: 

This log is for TOTK subterranean world. The issue is the game crashes after a minute or less making it impossible to play. 

Reprodution steps

You can check the issue by just playing in the underground world.

Config
Device is redmagic 8 pro 16/512.
Latest yuzu 145
latest mesa turnip drivers.24.0.0 rev 11

This issue has been happening for several months. different drivers tested with same result
[yuzu_log.txt.old-1.txt](https://github.com/yuzu-emu/yuzu/files/13501269/yuzu_log.txt.old-1.txt)

**Comment by german77** [comment]
We don't provide support to piracy
