### ISSUE TITLE
Regression: [macOS] Building broken again, possibly due to #11946

### ISSUE THREAD

**Issue by shinra-electric** [yuzu-emu/yuzu#12222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

N/A

### Description of Issue

Fails to build with Apple Clang. 
`FAILED: externals/gamemode/libgamemode.a`

This was likely due to #11946

### Expected Behavior

Builds

### Reproduction Steps

Build

### Log File

[Terminal Saved Output.txt](https://github.com/yuzu-emu/yuzu/files/13504503/Terminal.Saved.Output.txt)

### System Configuration

CPU: M1 Pro
GPU/Driver: M1 Pro
RAM: 16GB
OS: 14.1.1

**Comment by liamwhite** [comment]
I tried to get [CI going for this target recently](https://github.com/liamwhite/yuzu/pull/2). Some issues:
- There is no arm64 version of this runner yet
- There is some sort of intractable build failure with tzinfo that I can't reproduce locally

**Comment by shinra-electric** [comment]
Thanks for looking into the CI...

Regarding this specific issue, it's might be a quick fix changing `if (UNIX)` to 'if (UNIX AND NOT APPLE)`
