### ISSUE TITLE
[Android] FXAA has Screen Artifacts

### ISSUE THREAD

**Issue by JukoSigure** [yuzu-emu/yuzu#12247]
### Issue

![Screenshot_2023-12-01-04-35-05-967_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/72319977/3d8ceecc-ec4f-4572-857e-e824d35a208a)

**Comment by RaduNastase** [comment]
It's exactly the same for me.

Rog 3 
Android 11

**Comment by RaduNastase** [comment]
According to the log it is fixed in version 148?
Haven't tested yet myself.
