### ISSUE TITLE
LTO not compiling with ninja

### ISSUE THREAD

**Issue by OsoaGH** [yuzu-emu/yuzu#12257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1637

### Description of Issue

When I have `-DYUZU_ENABLE_LTO=ON`, ninja fails to build.

### Expected Behavior

Ninja builds successfully.

### Reproduction Steps

1. Add `-DYUZU_ENABLE_LTO=ON` to your build arguments in cmake
2. Run `ninja`
3. See errors

### Log File

[build.log](https://github.com/yuzu-emu/yuzu/files/13532024/build.log)

### System Configuration

CPU: Ryzen 5 5600
GPU/Driver: RX 6700 XT
RAM: 32 GB
OS: Debian 12

**Comment by liamwhite** [comment]
You didn't link avcodec. Pass -DYUZU_USE_BUNDLED_FFMPEG to the cmake command line, or install ffmpeg development libraries

**Comment by OsoaGH** [comment]
> You didn't link avcodec. Pass -DYUZU_USE_BUNDLED_FFMPEG to the cmake command line, or install ffmpeg development libraries

Which libraries would that be? Do I just install ffmpeg with apt?

**Comment by liamwhite** [comment]
For reference: LINK_LIBRARIES from my build.ninja contains the following:
```
/usr/lib64/libavcodec.so  /usr/lib64/libavdevice.so  /usr/lib64/libavfilter.so  /usr/lib64/libavformat.so  /usr/lib64/libavutil.so  /usr/lib64/libswresample.so  /usr/lib64/libswscale.so 
```

**Comment by OsoaGH** [comment]
I don't think I've installed FFMPEG right. `pkg-config libav* --libs` says it wasn't found. Sorry about this, I'm relatively new to Linux.

Do I have to compile and build FFMPEG from source? Would the guide [here](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu) work for Yuzu?

**Comment by OsoaGH** [comment]
Also, I don't have `-W` or `--no-undefined` in my build script, are they found in a different config file perhaps?

**Comment by liamwhite** [comment]
pkg-config libavcodec --libs

**Comment by OsoaGH** [comment]
> pkg-config libavcodec --libs

gives me -lavcodec

**Comment by liamwhite** [comment]
Then FindFFmpeg should be able to find it. Put some debug logging in that cmake module to see why it is not finding it?

**Comment by OsoaGH** [comment]
> Then FindFFmpeg should be able to find it. Put some debug logging in that cmake module to see why it is not finding it?

Sorry to ask so many questions but what would I need to add for this to happen?

**Comment by OsoaGH** [comment]
![image](https://github.com/yuzu-emu/yuzu/assets/33041004/cec67fe7-5093-489c-8eeb-7470ea22ffca)
![image](https://github.com/yuzu-emu/yuzu/assets/33041004/d7e5fb23-5821-4d5d-8f36-13d25ccd1dc0)
![image](https://github.com/yuzu-emu/yuzu/assets/33041004/b7b57725-9301-4387-878f-fffa525ea2b3)
![image](https://github.com/yuzu-emu/yuzu/assets/33041004/c6789467-bc6b-4add-a499-bc3202435422)

All the circled statements are the ones which trigger the message.

**Comment by OsoaGH** [comment]
CMAKE is unable to find the correct FFMPEG files. Doing `export FFMPEG_DIR=/usr/lib/x86_64-linux-gnu` and then building does give an actual error:
```
Could NOT find FFmpeg (missing: FFmpeg_INCLUDE_avcodec
FFmpeg_INCLUDE_avfilter FFmpeg_INCLUDE_avutil FFmpeg_INCLUDE_swscale
avcodec avfilter avutil swscale) (Required is at least version "4.3")
```
I'm honestly unsure as to whether I've installed ffmpeg correctly. I did it with `sudo apt install ffmpeg`, and it works but I just can't find the right folder structure as shown in FindFFMPEG

**Comment by OsoaGH** [comment]
Switched to clang in the end, problem solved.
