### ISSUE TITLE
Master Detective Archives: Rain Code - in game rendering problem

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#12269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android v147

### Description of Issue

When it's time to control the character, the screen mostly doesn't render

![Screenshot_20231201-225958](https://github.com/yuzu-emu/yuzu/assets/4172898/25514d4c-43e9-4d2c-b2a0-f8998cc141c0)
![Screenshot_20231201-230739_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/b6f8c8c4-d4c7-484b-bf09-d71fbdf293fe)
![Screenshot_20231201-230803](https://github.com/yuzu-emu/yuzu/assets/4172898/cce55beb-c085-4216-a9f2-326a9b6ddb85)
![Screenshot_20231201-231500_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/7c0b70b0-e7a2-4f23-b34c-90d085dd9c77)
![Screenshot_20231201-230901_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/9e83fce9-2586-4a98-a421-769699f9e6ef)
![Screenshot_20231201-231521_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/a0245ba4-68f1-47ce-b3c1-282b44795540)

### Expected Behavior

that shouldn't happen

### Reproduction Steps

Just Play normally 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13536746/yuzu_log.txt)

### System Configuration

CPU:sd870
GPU/Driver: Adreno 650/turnip driver/Qualcomm driver 
RAM:8gb
OS: android 13

**Comment by fullmetalik** [comment]
Any fix ?

**Comment by brujo5** [comment]
Fixed since v168 build

![Screenshot_20231222-192734](https://github.com/yuzu-emu/yuzu/assets/4172898/7ddfde56-27ea-4fb9-8454-ec1c0b7e64b2)
![Screenshot_20231222-193858](https://github.com/yuzu-emu/yuzu/assets/4172898/bb9d974e-267e-472f-9a20-75d5b56827d5)
![Screenshot_20231222-192401](https://github.com/yuzu-emu/yuzu/assets/4172898/e12bd68d-fd41-4d91-a7d3-e7ad0fb4b858)
