### ISSUE TITLE
Cant put keys in the default user folder

### ISSUE THREAD

**Issue by MojoJojoDojo** [yuzu-emu/yuzu#1226]
If you put the keys (prod.keys and title.keys) in the default (AppData) folder yuzu wont recognize them.
if you create a portable user folder the keys will be detected and games will launch correctly.
I think it's because my default user folder uses non-latin characters but i could be wrong.

**Comment by tech4me** [comment]
Where did you put your keys?

**Comment by MojoJojoDojo** [comment]
keys folder

**Comment by elemileTLDR** [comment]
I seem to have the same issue.  How did you change the keys target folder (or create a portable user one)? Yuzu only allows us to change the sdcard, games and nand folders.

**Comment by Zenicius** [comment]
> I seem to have the same issue. How did you change the keys target folder (or create a portable user one)? Yuzu only allows us to change the sdcard, games and nand folders.
I dont think theres a way to change keys target folder. To be honest i have this problem quite often so i decided to change  my username...

**Comment by elemileTLDR** [comment]
> 
> 
> > I seem to have the same issue. How did you change the keys target folder (or create a portable user one)? Yuzu only allows us to change the sdcard, games and nand folders.
> 
> I dont think theres a way to change keys target folder. To be honest i have this problem quite often so i decided to change my username...

I see. I can't change my username on Windows 8.1 (or I can, but it doesn't change the main user's path name), so I made a new user, with a strictly unicode name, just for Yuzu. It solved the issue, but damn.

**Comment by Frakatchoo** [comment]
Same here! And I confirm, Yuzu is not compatible with user folder containing special characters (mine is "Jérôme" for exemple). The generated shortcuts to the emulator doesn't work, and the app can't access the keys folder. Hope an update for this issue, I think a lot of people can't try the emulator because of this.

**Comment by Morph1984** [comment]
Fixed by #6270
