### ISSUE TITLE
(Android) yuzu's Nintendo Switch Pro Controller  button XY mapping error

### ISSUE THREAD

**Issue by k1sh1K1** [yuzu-emu/yuzu#12272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android-147

### Description of Issue

When you start the game, the X button uses the Y button function.

### Expected Behavior

When you start the game, the X button uses the X button function.

### Reproduction Steps

Bluetooth connection to Nintendo Switch Pro Controller 
But my brother helped me with this. Change the position of the XY button in the InputHandler file. Is this a code error?
![Cache_-55de92ae5ee17d14](https://github.com/yuzu-emu/yuzu/assets/152763363/d26a58cd-049c-43a6-8da6-4113e52291b7)

### Log File

no

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:Android

**Comment by k1sh1K1** [comment]
I've tested it and the XY buttons have functioned exactly right, will this modification allow for a full joycon experience until the custom controller buttons are updated.

**Comment by k1sh1K1** [comment]
I'm not sure why the Switch Pro Controller Bluetooth connection to the phone would cause the XY buttons to function in reverse. But changing the XY position in it did solve the problem, and I've shared it with other friends who had the same problem and tested it, and the problem has been solved perfectly. Thank you very much for your contribution to Yuzu.

**Comment by danielms5** [comment]
@k1sh1K1 How do you fix this error? Thanks
