### ISSUE TITLE
Yuzu is incompatible with recent versions of Visual Studio

### ISSUE THREAD

**Issue by Adamillo** [yuzu-emu/yuzu#12270]
### Issue

In recent new versions of Visual Studio, yuzu fails to build with the following errors:
![image](https://github.com/yuzu-emu/yuzu/assets/45568316/af863072-0b45-47bc-acd3-5313242af99a)
Here's the full output of the build as well:
[output.txt](https://github.com/yuzu-emu/yuzu/files/13536852/output.txt)

**Comment by Squall-Leonhart** [comment]
Yuzu builds fine with visual studio here, use cmake gui to generate and open the Solution file.
