### ISSUE TITLE
Assassin's Creed: Rogue - impossible to start it

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#12275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android v149

### Description of Issue

Assassin's Creed: Rogue It comes as game DLC of the Rebel collection game and is impossible to start.

![Screenshot_20231203-154929_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/01df1d6f-1c33-4302-b0e3-74d2663183cc)
![Screenshot_20231203-154721_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/ad0ed5fc-f5af-4d61-ac63-6c31438df05b)

Video
https://github.com/yuzu-emu/yuzu/assets/4172898/aca947ea-048c-48eb-9ed1-a5d1f432435a
![ezgif com-video-to-gif](https://github.com/yuzu-emu/yuzu/assets/4172898/6f85040e-c094-4469-a4cd-afc9054c25ab)

### Expected Behavior

the game should run

### Reproduction Steps

Just play normally 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13540486/yuzu_log.txt)

### System Configuration

CPU:sd860
GPU/Driver: Adreno 640/ turnip driver 
RAM:8gb
OS: android 13

**Comment by Wuw3i** [comment]
Meu caso é diferente, eu entro no game, consigo jogar o início até completar a missão de salvar o navio que está sendo atacado, porém, depois dessa parte quando entra no "Animus" o FPS cai pra zero e o Emulador fecha sozinho... Eu uso um Realme X7 Max 5g 8/128 (Dimensity 1200)
