### ISSUE TITLE
Tears of the Kingdom doesn't boot (Unmapped Read)

### ISSUE THREAD

**Issue by alkaris2** [yuzu-emu/yuzu#12282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1626 / 1641

### Description of Issue

I have a bug with Yuzu emulator not working when launching a game. When I load up a game like Tears of the Kingdom it then hangs up after launching the game going from 50-60FPS down to 0 FPS and Frame saying NaN ms. While the console log shows a spam of same errors relating to ARM Core dynarmic that tries to access memory space that doesn't exist.

```
[ 518.706761] HW.Memory <Error> core/memory.cpp:operator():742: Unmapped Read8 @ 0x4F4C2F746E656EFA
[ 518.706761] HW.Memory <Error> core/memory.cpp:operator():742: Unmapped Read8 @ 0x4F4C2F746E656EFB
[ 518.706762] HW.Memory <Error> core/memory.cpp:operator():742: Unmapped Read8 @ 0x4F4C2F746E656EFC
[ 518.706765] HW.Memory <Error> core/memory.cpp:operator():742: Unmapped Read8 @ 0x4F4C2F746E656EFD
[ 518.706765] HW.Memory <Error> core/memory.cpp:operator():742: Unmapped Read8 @ 0x4F4C2F746E656EFE
[ 518.706766] HW.Memory <Error> core/memory.cpp:operator():742: Unmapped Read32 @ 0x502F6D617261504C
[ 518.706767] HW.Memory <Error> core/memory.cpp:operator():742: Unmapped Read32 @ 0x502F6D617261505C[ 488.529303] HW.Memory <Error> core/memory.cpp:operator():306: Unmapped ReadBlock @ 0x0000000000000000 (start address = 0x0000000000000000, size = 8)
[ 488.529338] CheatEngine <Error> core/memory/cheat_engine.cpp:SanitizeAddress:89: Cheat attempting to access memory at invalid address=00000000000000F0, if this persists, the cheat may be incorrect. However, this may be normal early in execution if the game has not properly set up yet.
[ 488.529340] HW.Memory <Error> core/memory.cpp:operator():359: Unmapped WriteBlock @ 0x0000000000000000 (start address = 0x0000000000000000, size = 8)
[ 488.643693] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp:ZBCSetTable:226: (STUBBED) called
[ 495.043969] Service.Audio <Info> audio_core/sink/cubeb_sink.cpp:CubebSinkStream:75: Opening cubeb stream ADSP_RenderStream-0 type 0 with: rate 48000 channels 2 (system channels 2) latency 1200
[ 495.067166] Service.Audio <Info> audio_core/sink/cubeb_sink.cpp:CubebSinkStream:75: Opening cubeb stream ADSP_RenderStream-1 type 0 with: rate 48000 channels 2 (system channels 2) latency 1200
```

it spams this over and over again until Yuzu crashes, or is force quit to close.

I hadn't had any issues with Yuzu the last time I tried it, the last know working version was 1504, I was using version 1626, and I also tried version 1641 which was the AppImage download. Both these versions are seemingly broken with the same exact issue with errors being shown here. This was tested with Mods loaded and without Mods loaded tested in both 1626 and 1641 versions of Yuzu.

### Expected Behavior

Expected behavior is the ARM CPU instructions are interpreted correctly upon loading a game and NOT trying to access unmapped memory that doesn't exist.

### Reproduction Steps

1. Download Yuzu from AUR or AppImage and run tests with versions mentioned.
2. Try with and without mods installed.

Mods used:
- https://github.com/hoverbike1/TOTK-Mods-collection/releases

Default Yuzu Config - Tried changing Renderer from OpenGL to Vulkan, to which neither made a difference. Accuracy is set to it's defaults, no CPU overclock and Cheats disabled.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13549426/yuzu_log.txt)

### System Configuration

**CPU:** intel core i7-7700k
**GPU/Driver:** NVIDIA RTX 3070 - 535.129.03 / Vulkan 1.3.269
**RAM:** 32GB
**OS:** Manjaro Linux (Cinnamon)

**Comment by FearlessTobi** [comment]
Try without any mods and cheats enabled.

**Comment by alkaris2** [comment]
> Try without any mods and cheats enabled.

As I stated I turned those all off. If you had carefully read what I wrote before.

**Comment by liamwhite** [comment]
The game works fine here with and without mods. Please verify that your copy of the game is not corrupted:
1. Right click the game in the game list and select "Verify integrity"
2. In tools, if you have an update installed, select "Verify installed contents"

If both of these verify successfully, then find the last working version of the emulator - there is an archive of all versions here: https://github.com/yuzu-emu/yuzu-mainline/releases

**Comment by liamwhite** [comment]
Closing as we cannot confirm the issue without a response.
