### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by YuenEye** [yuzu-emu/yuzu#12285]
![yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13556815/yuzu_log.txt.old.txt)

Emulator keeps crashing on my device

**Comment by G-Spawn** [comment]
Mali isn't known for working well here overall it is a 'meme' device for majority of people who try it. Besides that you haven't dumped your console files properly. Doesn't look like you set right emulated controller profile for whatever game you're trying either.

**Comment by G-Spawn** [comment]
https://community.arm.com/support-forums/f/graphics-gaming-and-vr-forum/54575/support-for-bcn-texture-formats-on-future-mali-gpus if you want to ask for better driver support ask arm themselves. It's not up to yuzu to fix what your device provider / community is not providing.
