### ISSUE TITLE
Moving Out 2 Character Model Becomes a Mess

### ISSUE THREAD

**Issue by littlefoliage** [yuzu-emu/yuzu#12287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1641

### Description of Issue

I have been using Vulkan to play Moving Out 2 and it was working fine.
Recently, the character suddenly became a mess, like in the screenshot, you should see a character over there but now it's just a mess.
When i change GPU to openGL, it would somehow work fine for one level and the screen starts jittering.
I have tried to clean up cache and rendering and update Moving Out 2 to 1.3.315 but still doesn't work.
![image](https://github.com/yuzu-emu/yuzu/assets/16294401/d39990fc-d167-4c6d-a6e4-850940a9c26d)

### Expected Behavior

This is the result using OpenGL. you can see the character, but after one level the screen starts jittering.
![image](https://github.com/yuzu-emu/yuzu/assets/16294401/56fce5a0-39b9-4392-9025-4525628d003b)

### Reproduction Steps

One day i started the game as regular, it happens

### Log File

![image](https://github.com/yuzu-emu/yuzu/assets/16294401/5b738c59-acd0-4076-bf5e-6d1c20935e41)

### System Configuration

CPU:AMD Ryzen 9 7940hs
GPU/Driver: Radeon 780M
driver version: 23.20.23.01 AMD Software Adrenalin Edition
windows driver version 31.0.22023.1014
Vulkan API 1.3.262
Vulkan driver 2.0.283
RAM:32GB
OS:Windows

**Comment by G-Spawn** [comment]
please upload the log when you can

**Comment by littlefoliage** [comment]
> please upload the log when you can
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13565094/yuzu_log.txt)

Hi G-Spawn, please let me know if this is the right log

**Comment by littlefoliage** [comment]
the issue is resolved after updating the latest ADM driver which is out on 5th
