### ISSUE TITLE
Mario Kart 8 Deluxe audio bugging in tunnels

### ISSUE THREAD

**Issue by 46620** [yuzu-emu/yuzu#12284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu Early Access 4007

### Description of Issue

When in tunnels, audio seems to start glitching, extremely loudly, and instantly stops when leaving
[Video of issue](https://youtu.be/oMbTPFiSCfg)

### Expected Behavior

The audio should reverb a little since it's a tunnel
[Normal audio](https://youtu.be/d1yuggXd8BQ?t=56) (Credit to [GamerJGB](https://www.youtube.com/@GamerJGB))

### Reproduction Steps

1. Play Mario Kart 8 Deluxe
2. Drive into a tunnel

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13553984/yuzu_log.txt)

### System Configuration

CPU: i5-11600KF
GPU/Driver: GeForce RTX 2080 SUPER (31.0.15.4629) (11/29/2023)
RAM: 16GB
OS: Windows 11 10.0.22621 Build 22621

**Comment by liamwhite** [comment]
Fixed in 4008
