### ISSUE TITLE
Dragon Quest Monsters: The Dark Prince weird head graphical bug

### ISSUE THREAD

**Issue by nkeeta** [yuzu-emu/yuzu#12326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 4012

### Description of Issue

for some reasons all human characters heads looks up
![123](https://github.com/yuzu-emu/yuzu/assets/110434590/d32562ad-529b-46f5-93dc-b290f427f9ee)
![1234](https://github.com/yuzu-emu/yuzu/assets/110434590/9828eb07-41b9-4310-b1fa-59f64238e14f)

### Expected Behavior

all human characters should look normal

### Reproduction Steps

start the game
loading
then i see this nightmare
quit

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13625732/yuzu_log.txt.old.txt)

### System Configuration

CPU: i5 3470
GPU/Driver: 1050ti/536.23
RAM: 12gb
OS: Windows 10

**Comment by goldenx86** [comment]
This is hilarious, I love it.
Can you try setting CPU accuracy to Accurate or Paranoid?

**Comment by pacoa-kdbg** [comment]
I don't think it is a cpu issue, I have been playing this on a 
308 + R9 3900X without changing any default setting

**Comment by pacoa-kdbg** [comment]
Oh babe just saw the 3rd Gen Intel

**Comment by goldenx86** [comment]
The 3900X has FMA XD

**Comment by nkeeta** [comment]
> This is hilarious, I love it. Can you try setting CPU accuracy to Accurate or Paranoid?

set cpu accuracy to Accurate and it helped! but fps dropped a little bit

**Comment by goldenx86** [comment]
> > This is hilarious, I love it. Can you try setting CPU accuracy to Accurate or Paranoid?
> 
> set cpu accuracy to Accurate and it helped! but fps dropped a little bit

Then the problem is your CPU, its lack of the FMA instruction set produces this.
Set accurate on a per-game basis, right click the game and go to properties, then set it there.

**Comment by nkeeta** [comment]
> > > This is hilarious, I love it. Can you try setting CPU accuracy to Accurate or Paranoid?
> > 
> > 
> > set cpu accuracy to Accurate and it helped! but fps dropped a little bit
> 
> Then the problem is your CPU, its lack of the FMA instruction set produces this. Set accurate on a per-game basis, right click the game and go to properties, then set it there.

is there any posibility to f up my CPU with this?

**Comment by goldenx86** [comment]
Nope, it's just using a more precise method that is slower on older CPU archs.
