### ISSUE TITLE
(PC) [Yo-kai Watch 1 for Nintendo Switch (妖怪ウォッチ 1 for Nintendo Switch)] Screen Flickering and Texture Bugs

### ISSUE THREAD

**Issue by light8227** [yuzu-emu/yuzu#12332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1631

### Description of Issue

When moving in the world, the screen will rapidly flicker between different tints of colors onscreen.
There are also some texture bugs, such as when catching bugs ingame, some textures will be flipped upside down on the screen while others will be normal.
![ykw1s_bug_texturebug](https://github.com/yuzu-emu/yuzu/assets/58644191/90638368-7210-45e7-b3bc-e2ddebcc15ad)

### Expected Behavior

The screen should not flicker and all textures when catching bugs should be right side up instead of upside down.

### Reproduction Steps

Screen Flickering: Move around the world after the first few events.
Texture Bugs: Successfully catch a bug.
[YKW1S_Save.zip](https://github.com/yuzu-emu/yuzu/files/13629174/YKW1S_Save.zip)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13629170/yuzu_log.txt)

### System Configuration

CPU: 11th Gen Intel(R) Core(TM) i7-11700K
GPU/Driver: NVIDIA GeForce RTX 3060 Ti/Driver version 546.29
RAM: 16.0 GB
OS: Windows 11

**Comment by Squall-Leonhart** [comment]
Users caught with pirated media in the log cannot be assisted.
