### ISSUE TITLE
Enter the Gungeon Graphical Glitches 

### ISSUE THREAD

**Issue by joshuacode751** [yuzu-emu/yuzu#12337]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Yuzu Android v157

### Description of Issue

Enter the Gungeon Graphical Issue even on System driver, Latest Mesa Turnip Driver and on proprietary Qualcomm drivers. 

https://github.com/yuzu-emu/yuzu/assets/32216817/e368e791-4600-4f1d-aa76-c2a0ba4b07c3

![Screenshot_2023-12-09-22-36-45-827_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/32216817/4d3d7399-b1b0-4bdc-85c9-a2646cb1ce44)

### Expected Behavior

Shouldn't have this even on skyline the glitches were non existent.

### Reproduction Steps

Happens everywhere in menu and ingame.

### Log File

**Log file removed by moderator**

### System Configuration

CPU: Snapdragon 7+ gen 2
GPU/Driver: Adreno 725
RAM: 8gb 
OS: MIUI 14.0.7

**Comment by SleepingSnakezzz** [comment]
We do not support piracy here. Please dump your own games from your own Nintendo Switch.

**Comment by Knowitall599** [comment]
Ummmmmmm.... Yes, you support piracy here.  Why else would Nintendo be interested in yuzu?
