### ISSUE TITLE
Delete DLC contents

### ISSUE THREAD

**Issue by Rekkusu09** [yuzu-emu/yuzu#12340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

![Screenshot_20231212-112948](https://github.com/yuzu-emu/yuzu/assets/133083456/d9d4b072-2a0a-4b17-b232-9cdd3cdd427a)
I saw the latest Feature but it lacks the point. I was suggesting to add also the feature of deleting the installed dlc not just the data progress. I hope it gets added next time. 

### Why would this feature be useful?

Its gonna be useful for a reason that only used dlc contents are the ones in the emulator and dlc contents that are no longer needed or used will be removed or deleted in the system.

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/11323 and https://github.com/yuzu-emu/yuzu/issues/12239.
