### ISSUE TITLE
Update FSR to 1.0.3

### ISSUE THREAD

**Issue by YigaUpdate** [yuzu-emu/yuzu#12353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I propose an update to FSR to improve image quality.

### Why would this feature be useful?

This update would be helpful in improving video quality and performance.

**Comment by liamwhite** [comment]
1.0.3 doesn't even exist. The latest version is 1.0.2 which we are already using: https://github.com/GPUOpen-Effects/FidelityFX-FSR

**Comment by FearlessTobi** [comment]
Please stop spamming our repo with Pull Requests like this.
