### ISSUE TITLE
Compressed formats

### ISSUE THREAD

**Issue by AireagoirSteam** [yuzu-emu/yuzu#12355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I'd like to suggest the use of XCZ file format since I saw in a previous issue it was mentioned that other compressed formats maybe added.

XCZ is a compressed version of xci.

### Why would this feature be useful?

Compressed games save space on drives and also means having to buy less drives or allows having ganes on an internal ssd which should mean better loading perhaps.
Xcz's are literally just compressed xci's.

Thank you to anyone that takes the time to read this request and keep up the good work.

**Comment by G-Spawn** [comment]
NSZ & XCZ won't be supported here ever due to their association to piracy.
