### ISSUE TITLE
4096 x 2160 taskbar does not hide in fullscreen

### ISSUE THREAD

**Issue by Awesomeangotti** [yuzu-emu/yuzu#12357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1650

### Description of Issue

when in 4096 x 2160, the task bar does not hide when entering fullscreen. it does hide for every other application i have tested

### Expected Behavior

the taskbar should hide when entering fullscreen

### Reproduction Steps

enter 4096 x 2160 in windows settings and enter fullscreen in yuzu

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13667276/yuzu_log.txt)

### System Configuration

CPU: i7-8700
GPU/Driver: most recent driver - rtx 3070
RAM: 32 GB ddr4 3200 mhz
OS: windows 10 home

**Comment by Squall-Leonhart** [comment]
cannot confirm, task bar hides on fullscreen here.

**Comment by Awesomeangotti** [comment]
Updates since posting seem to have fixed the issue with the task bar. Thanks for that folks
