### ISSUE TITLE
8 gen 2 bug on one piece pirates warriors 4

### ISSUE THREAD

**Issue by daniel120330** [yuzu-emu/yuzu#12365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 160 

### Description of Issue

I have problems with turnip on 8 gen 2 It Crash AND Glicht after loading intro, on 870,765g is fine It happens only on alls my 8gen 2 phones.

### Expected Behavior

.

### Reproduction Steps

Before intro menu
![Screenshot_yuzu_20231214_145558](https://github.com/yuzu-emu/yuzu/assets/49822345/4707df81-bec7-40e5-bb56-d78121a53cc3)
![Screenshot_yuzu_20231214_145648](https://github.com/yuzu-emu/yuzu/assets/49822345/76b67f10-5fba-47f1-9b42-a0aec0fbcd8d)

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13678627/yuzu_log.txt.old.txt)

### System Configuration

CPU:8 gen 2
GPU/Driver: A740
RAM: 12
OS: a13

**Comment by liamwhite** [comment]
If you already know this is a graphics driver bug then why are you reporting it to us and not to turnip? https://gitlab.freedesktop.org/mesa/mesa/-/issues

**Comment by daniel120330** [comment]
Thanks you , im new this Is my first report ,thanks for the reply
