### ISSUE TITLE
[Android] Add local multi-player support 

### ISSUE THREAD

**Issue by Hariu7** [yuzu-emu/yuzu#12361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Local multi-player enable player to play with friends battle with them . I REQUEST YUZU TEAM to add local multi-player supporte to android 

### Why would this feature be useful?

This is already present in pc build. It will player excited as we battle our friend . YUZU team add support to local multi-player

**Comment by german77** [comment]
Technically speaking it already has support. Just no UI interface. We decided to not expose it on android. The reason being is that android performance is still far from ideal so you will likely have many disconnects.

**Comment by Hariu7** [comment]
> Technically speaking it already has support. Just no UI interface. We decided to not expose it on android. The reason being is that android performance is still far from ideal so you will likely have many disconnects.

Please add UI interface I am able to get stable 60 fps in many mario games

**Comment by prkodi** [comment]
I also wrote on official Yuzu Citra support page, for using two or more controllers. They answered to me i have to wait and don't find workaround. Since 1 month I'm using a github repository based on 172 nce version which works well. Any news?
