### ISSUE TITLE
[Android] Uncapped FPS

### ISSUE THREAD

**Issue by SuperLeiyan** [yuzu-emu/yuzu#12360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

On PC we can press Ctrl + U to toggle unlimited frame rate mode, can we have this on android as well? I've seen eggNS emulator having this, but I refuse to use that as it was made based on stolen Yuzu code.

### Why would this feature be useful?

This is an important feature because for many games that I play, there are no 60 FPS patches.

**Comment by Hariu7** [comment]
Disable limit speed perce

**Comment by SuperLeiyan** [comment]
Doesn't seem to work with certain games like Warriors Orochi 4 JP  😞.

"Disable limit speed percentage" is this exactly what CTRL + U does on PC?

**Comment by FernandoS27** [comment]
> > Disable limit speed percentage
> 
> Doesn't seem to work with certain games like Warriors Orochi 4 JP 😞.
> 
> "Disable limit speed percentage" is this exactly what CTRL + U does on PC?

Not all games work with it or you could also be performance limited.

**Comment by RaduNastase** [comment]
Put speed to 200% or more. It works vey well in some games. "Inside" for example, played at 200% actually renders in 60 fps, without speeding up the game.

**Comment by liamwhite** [comment]
Yes, disabling the speed limit is the same as unlocking on desktop:
```
    const auto& settings = Settings::values;
    auto speed_scale = 1.f;
    if (settings.use_multi_core.GetValue()) {
        if (settings.use_speed_limit.GetValue()) {
            // Scales the speed based on speed_limit setting on MC. SC is handled by
            // SpeedLimiter::DoSpeedLimiting.
            speed_scale = 100.f / settings.speed_limit.GetValue();
        } else {
            // Run at unlocked framerate.
            speed_scale = 0.01f;
        }
    }
```

**Comment by Hariu7** [comment]
> Yes, disabling the speed limit is the same as unlocking on desktop:
> 
> ```
>     const auto& settings = Settings::values;
>     auto speed_scale = 1.f;
>     if (settings.use_multi_core.GetValue()) {
>         if (settings.use_speed_limit.GetValue()) {
>             // Scales the speed based on speed_limit setting on MC. SC is handled by
>             // SpeedLimiter::DoSpeedLimiting.
>             speed_scale = 100.f / settings.speed_limit.GetValue();
>         } else {
>             // Run at unlocked framerate.
>             speed_scale = 0.01f;
>         }
>     }
> ```

Hey please add local multi-player support 
And some by disable limit speed present game crash 2 to 3 minutes. Example  pokemon  sword
