### ISSUE TITLE
SSBU Choppy FPS and faster emulation speed than normal game speed

### ISSUE THREAD

**Issue by RakkiMon** [yuzu-emu/yuzu#12373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1652 / Early Access 4021

### Description of Issue

SSBU is running faster than normal game speed (even at locked 60 FPS), and feels choppy due to this.
On previous versions like Mainline 1651 the game runs well and smooth.

This problem seems similar to ol' #8191

### Expected Behavior

Running without speed abnormalities.

### Reproduction Steps

Play a couple of matches.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13691176/yuzu_log.txt)

### System Configuration

CPU: i7-10700K
GPU/Driver: RTX 3070, Driver NVIDIA Ver. 545.84
RAM: 32 GB
OS: Windows 10 up to date

**Comment by liamwhite** [comment]
Try with async presentation disabled

**Comment by RakkiMon** [comment]
I did it and that doesn't solve the problem

**Comment by liamwhite** [comment]
Can you check if this is fixed in EA 4022?

**Comment by RakkiMon** [comment]
I've tested in EA 4023 / Mainline 1653 and seems fixed, i didn't detect any abnormal speed.

**Comment by liamwhite** [comment]
Thanks for checking, marking as fixed
