### ISSUE TITLE
[Android] CardFight Vanguard Dear Days graphic issue

### ISSUE THREAD

**Issue by harpielady16** [yuzu-emu/yuzu#12383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android-161

### Description of Issue

![cardfight vanguard dear days graphic issue](https://github.com/yuzu-emu/yuzu/assets/154029323/6f602462-3264-4b0a-82d0-6f142b46b47a)
Launching and entering the game is fine but when you are starting the card battle in Story mode or in CPU fight mode the cards and the game field turns into black screen and the only visible are the characters picture profile.

### Expected Behavior

![cardfight vanguard dear days(expected behavior)](https://github.com/yuzu-emu/yuzu/assets/154029323/9ad60e20-0b66-434d-be5b-98b34fb84424)
The cards, game field and background should be visible.

### Reproduction Steps

Just using NCE and turnip driver

### Log File

No log file.

### System Configuration

CPU: Snapdragon 7+ Gen 2
GPU/Driver: Adreno 725
RAM: 8GB
OS: Android 13

**Comment by rospec14** [comment]
+1 on this. Dev team has been ignoring fixes for card games. YuGiOh has been stuck in limbo for 4 years. I hope these issues get attention soon.

**Comment by rospec14** [comment]
I found a workaround. Disable shader cache in Graphics settings. Apparently, the existing compiled shader cache causes the black screen.

**Comment by harpielady16** [comment]
Hi Yuzu team! Good day.

I tried to disable the Disk Cache in Graphic Settings but I'm still getting
the same issue. I also tried to Clear Cache the game by pressing and
holding the Game icon and clicking the Clear Cache button at the bottom of
the selection screen then try to play the game again but still same result.

Btw I'm using the Yuzu NCE v185 and gpu driver turnip revision 14.

Thank you for helping, I hope you can update me again for the fix. Thanks
again for your help.

**Comment by harpielady16** [comment]
> I found a workaround. Disable shader cache in Graphics settings. Apparently, the existing compiled shader cache causes the black screen.

Thanks for the input I tried to enable "Use asynchronous shader" after disabling the Disk shader cache in graphics settings and it does the trick.
![IMG_20240109_000905](https://github.com/yuzu-emu/yuzu/assets/154029323/0d203f09-530e-4866-a29b-f0bfeed33537)

I can now play the game properly. The cards, playing field and the background are now visible.
![Screenshot_2024-01-08-17-17-51-089_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/154029323/289aa600-cded-4de7-9440-ced4267bbc4b)

![Screenshot_2024-01-08-17-20-45-425_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/154029323/e24fb4a0-8cad-4f1e-84c7-47dec6b922bf)

***Still using Yuzu NCE v185
***GPU driver used is turnip_24.0.0_Unified_1.3.270_T_Alpha_10_MrPurple_adpkg.zip
