### ISSUE TITLE
[Android] 162 works the best so far but it can be better

### ISSUE THREAD

**Issue by AbdelrhmanAli457** [yuzu-emu/yuzu#12386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Can you please make **adding GPU drivers** option accessible for my device (Vivo v27/Helio g99/Android 13)

### Why would this feature be useful?

I downloaded lego marvel superheroes rom for my vivo v27 on different versions of yuzu and this how it turned out:
Google play ver: didn't even launch
Play ver(adjusted settings): crashed during the intro
v159(with nce): crashed after the first cutscene
v162(with nce): crashed in the second cutscene
As you can see there's a notable improvement and I trust you can fix this crashing one day, you can start by allowing me to add mesa 24 driver which is unavailable for my device
This will make a huge difference thank you

**Comment by pacoa-kdbg** [comment]
Hi,
No possible for Mali devices.

**Comment by gidoly** [comment]
Clise due to impossible request and piracy

**Comment by AbdelrhmanAli457** [comment]
> Hi,
> No possible for Mali devices.
> 

Hi,
So is this problem unfixable? is there any hope I can access this option in the future?
Btw it's Vivo v27e, my mistake
