### ISSUE TITLE
Adding FLUSHING MEMORY in EA 3509

### ISSUE THREAD

**Issue by Mystie6tea** [yuzu-emu/yuzu#12388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Facing the flickering trees in Pokemon Scarlet/Violet, like showed on the video. Can be different ones in different launches, but at least one!
Tested multiple EA versions, from 34xx till 4xxx, also on different hardware (both AMD/NVidia GPUs - 3060, 3060ti, 4080, RX 580 etc, Intel/AMD CPUs - i5-11400f, i9-9900K, R5-2600x, 3600 etc). It always happens no matter what, at least 1 time in 5-6 launches. Happens more frequent with V-Sync (any of it) turned on.
The only version without the issue was 3509. Was testing it for VERY LONG time and faced zero flickering at all! The only trouble of it - it has no "memory flushing" feature yet, so it has black profile picture issue. It would be really GREAT to take 3509 and add "memory flushing", would be the VERY BEST Yuzu version ever!

### Why would this feature be useful?

Facing the flickering trees in Pokemon Scarlet/Violet, like showed on the video. Can be different ones in different launches, but at least one!
Tested multiple EA versions, from 34xx till 4xxx, also on different hardware (both AMD/NVidia GPUs - 3060, 3060ti, 4080, RX 580 etc, Intel/AMD CPUs - i5-11400f, i9-9900K, R5-2600x, 3600 etc). It always happens no matter what, at least 1 time in 5-6 launches. Happens more frequent with V-Sync (any of it) turned on.
The only version without the issue was 3509. Was testing it for VERY LONG time and faced zero flickering at all! The only trouble of it - it has no "memory flushing" feature yet, so it has black profile picture issue. It would be really GREAT to take 3509 and add "memory flushing", would be the VERY BEST Yuzu version ever!

https://github.com/yuzu-emu/yuzu/assets/98742969/bbf96511-a5d0-4bce-acd1-5bca0b4c8837

**Comment by FearlessTobi** [comment]
We will not continue to develop old versions of yuzu.
