### ISSUE TITLE
Yuzu Crash On Intel Graphics After New Updates

### ISSUE THREAD

**Issue by 1br4h** [yuzu-emu/yuzu#12399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 4024

### Description of Issue

Hi so I just updated from yuzu mainline 1448 to ea 4024 for the performance
the same settings and games I played before with vulkan no longer work they will either get stuck on "Launching" or the emulator will stop responding until I end it

### Expected Behavior

Crash or stuck on launching

### Reproduction Steps

Opening any game on newer versions after 1448

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13705536/yuzu_log.txt)

### System Configuration

CPU: i5-7200u
GPU/Driver: Intel HD 620
RAM: 8GB 
OS: Windows 10

**Comment by liamwhite** [comment]
Which games specifically? And have you tried with a clean shader cache?

**Comment by 1br4h** [comment]
> Which games specifically? And have you tried with a clean shader cache?

I have tried Pokémon Legs Go Eevee and Pokémon Legends Arceus
Both games I could run before at 30 FPS on 0.5 res scale
And no I have not deleting shader cache but I will and tell you

**Comment by 1br4h** [comment]
> Which games specifically? And have you tried with a clean shader cache?

I deleted the Shader cache for Pokémon let's Go Eevee but it just crashed after building 2 shaders on the launching screen

**Comment by liamwhite** [comment]
If you deleted the shader cache it shouldn't have built any shaders at all, not 2. Can you provide the most recent crash dump from %appdata%\yuzu\crash_dumps, and the version of yuzu you were using when it was generated?

**Comment by 1br4h** [comment]
Update :
All version after release 1448 seem to crash for me idk what causes it but versions before that seem to work fine

**Comment by 1br4h** [comment]
This the latest log for me on ea 4087 on pokemon sword 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14071505/yuzu_log.txt)

**Comment by liamwhite** [comment]
> Can you provide the most recent crash dump from %appdata%\yuzu\crash_dumps, and the version of yuzu you were using when it was generated?

**Comment by 1br4h** [comment]
ok wait

**Comment by 1br4h** [comment]
I tried to run pokemon sword on yuzu ea 4091 this time to get a crash dump
there was no crash dump but this time yuzu gave a unique error
![image](https://github.com/yuzu-emu/yuzu/assets/154250082/46178d7d-05cf-48d3-9a8b-b097786d6f18)

**Comment by 1br4h** [comment]
could this be because i am using system managed virtual memory?

**Comment by 1br4h** [comment]
I added more virtual memory now there's no error but still crashes on launching

**Comment by 1br4h** [comment]
> > Can you provide the most recent crash dump from %appdata%\yuzu\crash_dumps, and the version of yuzu you were using when it was generated?

No crash dump is being generated when you turns itself off

**Comment by 1br4h** [comment]
I turned on opengl glsl instead of vulkan and the game turns on but it ended up getting stuck at 0fps at the end of the intro :(

**Comment by 1br4h** [comment]
Hello?

**Comment by 1br4h** [comment]
> > Can you provide the most recent crash dump from %appdata%\yuzu\crash_dumps, and the version of yuzu you were using when it was generated?

There is no crash dump after yuzu turns itself off pls help

**Comment by FearlessTobi** [comment]
If you want faster support, please close this issue and ask for help on Discord instead.

**Comment by 1br4h** [comment]
ok

**Comment by 1br4h** [comment]
if u can provide support normally but slower then thats ok
