### ISSUE TITLE
[Android] Please bring back Export/Import of all Save games 

### ISSUE THREAD

**Issue by mnisius** [yuzu-emu/yuzu#12419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Since the last few updates it's not possible anymore to export/import all save games. But I would like to be able to make a fast and easy backup of all my Savegames. 

### Why would this feature be useful?

This freature is useful to backup Savegames or to share them between the ea or GitHub version. 

On Android it's so easy to loose all savegames. If you uninstall the app or delete the storage then your saves are all gone. It's not like windows/Linux where the saves are stored externally and are easy accessable. 

I know I can now export/import savegames of single games but this takes way to long if you have a lot of games. 

And yes I know the export all user data does the same trick but it also takes super long and I don't want to backup multiple gigabyte of data when the only thing I need are some small save files.

**Comment by BorjaRRR** [comment]
+1

**Comment by rospec14** [comment]
+1

**Comment by mnisius** [comment]
Latest GitHub brought back the feature 🎉🎉.  Thank you! This can be closed !
