### ISSUE TITLE
System standby causes time offset

### ISSUE THREAD

**Issue by lfuelling** [yuzu-emu/yuzu#12418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline-0-1657

### Description of Issue

When putting the system (in my case a steam deck) into standby for some time, the emulator clock will be offset from system time.

### Expected Behavior

The emulator clock should stay in line with the system clock as long as the "custom rtc" setting is not used.

### Reproduction Steps

1. Start yuzu
2. Put system in standby (press power button on steam deck)
3. Wait for some time
4. Wake system
5. Emulator rtc is offset from system time

### Log File

There were no relevant entries in the log.

### System Configuration

CPU: AMD Custom APU 0405
GPU/Driver: AMD Custom GPU 0405
RAM: 14.5 GiB
OS: SteamOS 3.5.7

**Comment by ZwipZwapZapony** [comment]
Duplicate of #9932, fixed as of yuzu 1689.

**Comment by lfuelling** [comment]
Can confirm that this works now!
