### ISSUE TITLE
Help low end phone alive

### ISSUE THREAD

**Issue by imsadbro** [yuzu-emu/yuzu#12416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Can you guys make adreno 612 can use turnip driver please? Or just low end phone btw when my adreno 612 use it can join but a little and then it crashed :*(

### Why would this feature be useful?

It help low end phone many thing to their interesting

**Comment by evil-trainer** [comment]
How much RAM do you have? Yuzu 166 just got released yesterday and it _does_ have an Adreno 61x fix, taht might benefit you 😉

**Comment by german77** [comment]
We don't make gpu drivers nor we are inflating hardware requirements. Please open issues for specific games with the corresponding logs instead of a generic make my phone work.
