### ISSUE TITLE
AMD Frame Generation

### ISSUE THREAD

**Issue by lionnesquaer** [yuzu-emu/yuzu#12431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Greetings!

Honestly i don't know all kitchen of AMD Frame Generation, but like i now this is just somekind of intepolation and Frame Generation by self, can work without AMD FSR 3.0 and this tech dont need to implement in game nativetaly, and it goes open-source.
I can be wrong, i don't argue with it. But may be possible to implement Frame Generation to Yuzu. I still have drops in Red Dead Redemption it can be very useful!

Thank you and happy holidays!

### Why would this feature be useful?

Perfomance Increase

**Comment by lionnesquaer** [comment]
Got it, thank for explain. Sadly I have drops In Red Dead Redemption because of cpu Ryzen 5 3600.

**Comment by SleepingSnakezzz** [comment]
This request, if it were possible, would only help with a potential GPU performance bottleneck, not a CPU one. As per the reasons mentioned by Majora above, I'll close this.
