### ISSUE TITLE
[Android] King Of Fighters 13 - Lack of 8Bit/16Bit Support for Sprite-based games

### ISSUE THREAD

**Issue by SamSIM-pro** [yuzu-emu/yuzu#12434]
![Screenshot 2023-12-21 23 53 30](https://github.com/yuzu-emu/yuzu/assets/72478312/8af26a83-9a09-4c3e-8ed7-71d7604bb1b6)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu Android-166

### Description of Issue

This game contains some graphical issues, probably due to a lack of 8Bit/16Bit support. This is what I discovered from checking the log files. Interestingly, I noticed that every time I selected a new Qualcomm driver to boot the game, the game would have less graphical bugs, but if you booted the game again with the same driver, the graphical bugs will be much more severe, so you have to constantly change the Qualcomm drivers used to minimise graphical errors. With Turnip drivers, there is no difference. The graphical issues are the same.  In the screenshots attached, one is more graphically severe than the other:

![Screenshot_20231221_231901_yuzu](https://github.com/yuzu-emu/yuzu/assets/72478312/5ea9a0cc-ae05-4aaf-afd6-ca02cebb2ad4)
![Screenshot_20231221_180605_yuzu](https://github.com/yuzu-emu/yuzu/assets/72478312/aeb16335-d8de-466e-9c84-b896685e8f31)

### Expected Behavior

![KOF13Fixed](https://github.com/yuzu-emu/yuzu/assets/72478312/bb2e48df-bf4b-40d6-ae92-c343769cb713)

### Reproduction Steps

Boot the game with the same Qualcomm driver a second time to reproduce the results. 

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13746826/yuzu_log.txt.old.txt)

### System Configuration

CPU: Qualcomm Snapdragon 865 5G
GPU/Driver: Qualcomm v615.65
RAM: 6GB RAM
OS: Android

**Comment by SamSIM-pro** [comment]
I will also add that in the screenshots I attached, one uses JIT and the other uses NCE but the graphical issues are the same on either, so it's not due to using NCE or JIT.

**Comment by kkxiegouquan** [comment]
530drive

**Comment by SamSIM-pro** [comment]
> 530drive
Great recommendation on v530 driver. Now I can boot the game multiple times on this driver and the game always has less graphical issues. There are still minor graphical issues here and there: 
![Screenshot_20231222_043457_yuzu](https://github.com/yuzu-emu/yuzu/assets/72478312/bf5e219e-5727-4259-80ed-00962ae6a640)
![Screenshot_20231222_043435_yuzu](https://github.com/yuzu-emu/yuzu/assets/72478312/8868380a-4e79-411f-9dc0-a98c2bc0b3f6)
![Screenshot_20231222_043405_yuzu](https://github.com/yuzu-emu/yuzu/assets/72478312/b7c06a0e-5077-4b0d-8d6e-6fa3fe70e62b)
![Screenshot_20231222_043352_yuzu](https://github.com/yuzu-emu/yuzu/assets/72478312/4c473ff7-8781-4d84-99db-89fcaf7bfbc0)

**Comment by kkxiegouquan** [comment]
> > 530drive非常推荐v530驱动。现在我可以在这个驱动程序上多次引导游戏，游戏的图形问题总是比较少。这里还有一些小的图形问题：
> > ![Screenshot_20231222_043457_yuzu](https://private-user-images.githubusercontent.com/72478312/292375036-bf5e219e-5727-4259-80ed-00962ae6a640.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjAyNDUsIm5iZiI6MTcwMzIxOTk0NSwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwMzYtYmY1ZTIxOWUtNTcyNy00MjU5LTgwZWQtMDA5NjJhZTZhNjQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0MzkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZWM1MDA0MzY1NTk1MTIxNDE0Y2IzMGVkNWNhZTEzMWZhNjE5YTUwNThmNmRjODcxNWQ5ODliY2VkZTdkYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.unhgVrwDbE1Paw_tss2XyoM3wvk9yz66rl8-_UvkNp8)
> > ![Screenshot_20231222_043435_yuzu](https://private-user-images.githubusercontent.com/72478312/292375040-8868380a-4e79-411f-9dc0-a98c2bc0b3f6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjAyNDUsIm5iZiI6MTcwMzIxOTk0NSwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwNDAtODg2ODM4MGEtNGU3OS00MTFmLTlkYzAtYTk4YzJiYzBiM2Y2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0MzkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjZDRlMDdlMzRmMmU0N2Y4OWYwNzc2MDg3YWI4YTA2MjRmYjk4MGUwODcyYTg4OTYxODUzMDIxOTgyNDZkZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VNXYjb0fWcPeiefkOVZMxnuhmZElKSXzFhpWjodc5po)
> > ![Screenshot_20231222_043405_yuzu](https://private-user-images.githubusercontent.com/72478312/292375048-b7c06a0e-5077-4b0d-8d6e-6fa3fe70e62b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjAyNDUsIm5iZiI6MTcwMzIxOTk0NSwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwNDgtYjdjMDZhMGUtNTA3Ny00YjBkLThkNmUtNmZhM2ZlNzBlNjJiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0MzkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OWI1YzI3YmFhMjc1NWIwM2VlM2M5ZDMwM2ZhMTNmYjAzZWVlZmNhOTY5ZjNmYzM3MzNmNWYyOTQ3MWJlNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8KoXfd-8DPVmrekHFdhAgBrlgQ0Do69fI8AHnTnaOSs)
> > ![Screenshot_20231222_043352_yuzu](https://private-user-images.githubusercontent.com/72478312/292375053-4c473ff7-8781-4d84-99db-89fcaf7bfbc0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjAyNDUsIm5iZiI6MTcwMzIxOTk0NSwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwNTMtNGM0NzNmZjctODc4MS00ZDg0LTk5ZGItODlmY2FmN2JmYmMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0MzkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjU3Y2E5NTgzNDAwMjJjMjJlYmQ4M2Q0YzcxNTE1MWIzZTg0YmY1N2M2MjJmZmJkZmFjZWU3Mzk0MDJlZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zpcUgGi0fxV51q7LyXI47Aam-3o72jryy0yyuBP7LyU)

**Comment by kkxiegouquan** [comment]
> > 530drive非常推荐v530驱动。现在我可以在这个驱动程序上多次引导游戏，游戏的图形问题总是比较少。这里还有一些小的图形问题：
> > ![Screenshot_20231222_043457_yuzu](https://private-user-images.githubusercontent.com/72478312/292375036-bf5e219e-5727-4259-80ed-00962ae6a640.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjA0NDEsIm5iZiI6MTcwMzIyMDE0MSwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwMzYtYmY1ZTIxOWUtNTcyNy00MjU5LTgwZWQtMDA5NjJhZTZhNjQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1M2FkMWE5YjI5OGU3YmZmZTZkMjJjNTRmODcxNDY1Y2I4NDQ1ZTNiYTA1MWRiNWMzOTY1NjkwMDY1ZjUzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ijM2hTHI9d91csOAg7fxJNrSqSVeoUMrWe7DS_hzj54)
> > ![Screenshot_20231222_043435_yuzu](https://private-user-images.githubusercontent.com/72478312/292375040-8868380a-4e79-411f-9dc0-a98c2bc0b3f6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjA0NDEsIm5iZiI6MTcwMzIyMDE0MSwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwNDAtODg2ODM4MGEtNGU3OS00MTFmLTlkYzAtYTk4YzJiYzBiM2Y2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYzRkYzY0NTI4NzM0M2QxMGY1YmFmNjRlNGMxMDA4NjM0MzgwMDgyOWI4ZmNiZGNlOTY0Yzg3YThhMGJlM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jLbF2FtzSO6Qwg-wkDZHmRTmEXpani2Lazqo8C7YCAA)
> > ![Screenshot_20231222_043405_yuzu](https://private-user-images.githubusercontent.com/72478312/292375048-b7c06a0e-5077-4b0d-8d6e-6fa3fe70e62b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjA0NDEsIm5iZiI6MTcwMzIyMDE0MSwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwNDgtYjdjMDZhMGUtNTA3Ny00YjBkLThkNmUtNmZhM2ZlNzBlNjJiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZWRmY2ZmNGYyZTRkNzc0OGMzNDEzNmZiMTZiMjI3MjY4NzE4MzVjMTQxZjNhMmU2N2M3NzRkZTIzYWI3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FUSXtuBxRYPW2Z4dAhUCGaoLXpl81bfvRXFuEOwZPxs)
> > ![Screenshot_20231222_043352_yuzu](https://private-user-images.githubusercontent.com/72478312/292375053-4c473ff7-8781-4d84-99db-89fcaf7bfbc0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjA0NDEsIm5iZiI6MTcwMzIyMDE0MSwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwNTMtNGM0NzNmZjctODc4MS00ZDg0LTk5ZGItODlmY2FmN2JmYmMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0N2E5ZWRkNGZiYzAyMjgzYmFkOWNjZTgzNWJjZmI2NDcxNmI5Y2RmMDM0NmM4YjI1MGU2OWVlYTQwMDBlMTUmWC1BbXotU2lnbmVkSGVhZGVy

> > 530drive非常推荐v530驱动。现在我可以在这个驱动程序上多次引导游戏，游戏的图形问题总是比较少。这里还有一些小的图形问题：
> > ![Screenshot_20231222_043457_yuzu](https://private-user-images.githubusercontent.com/72478312/292375036-bf5e219e-5727-4259-80ed-00962ae6a640.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjA0OTAsIm5iZiI6MTcwMzIyMDE5MCwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwMzYtYmY1ZTIxOWUtNTcyNy00MjU5LTgwZWQtMDA5NjJhZTZhNjQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0NDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOTVkMTRkYzM2ZTQ4YTEwMzdlY2M5NzQ3YjMzNjliMGYyODY1ZjFiZjU0OTJmNzRhZTg5MmFlYzJjNjQ3MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UQq3llV8XttlUyxNGow2EfVHYIx8jGNWrhWBG-Qk1uM)
> > ![Screenshot_20231222_043435_yuzu](https://private-user-images.githubusercontent.com/72478312/292375040-8868380a-4e79-411f-9dc0-a98c2bc0b3f6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjA0OTAsIm5iZiI6MTcwMzIyMDE5MCwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwNDAtODg2ODM4MGEtNGU3OS00MTFmLTlkYzAtYTk4YzJiYzBiM2Y2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0NDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNDZmYjUxMWYzN2E2NDAwOGI0ZDU2YzM1ODFlN2FjMzY1MTg1MzhiZTM1MGZkMTVhMmIyYTEwNmU5Yzg4ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zlyG5DUNcD80QY4xZO8IPwIjYSVXTEOH--tmBNb0SlI)
> > ![Screenshot_20231222_043405_yuzu](https://private-user-images.githubusercontent.com/72478312/292375048-b7c06a0e-5077-4b0d-8d6e-6fa3fe70e62b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjA0OTAsIm5iZiI6MTcwMzIyMDE5MCwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwNDgtYjdjMDZhMGUtNTA3Ny00YjBkLThkNmUtNmZhM2ZlNzBlNjJiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0NDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YTJlODE2ZmUwOWE0NWUwZjhiNDU1MzU5YjhkYzA5NmI0MjVhODdjOTVjZGRmOTA3YTJhMzVmZDc2ZTgzNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1WzpK4HT7B69o5T6D5zP_b56Q0DxhtQ2eI4nRzGvflc)
> > ![Screenshot_20231222_043352_yuzu](https://private-user-images.githubusercontent.com/72478312/292375053-4c473ff7-8781-4d84-99db-89fcaf7bfbc0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjA0OTAsIm5iZiI6MTcwMzIyMDE5MCwicGF0aCI6Ii83MjQ3ODMxMi8yOTIzNzUwNTMtNGM0NzNmZjctODc4MS00ZDg0LTk5ZGItODlmY2FmN2JmYmMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0NDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMDRkNmU2YTg4YjNiZjBkNTM0YzYwZDNmMzQzMjg0ODM5NDUzMzE5MDRkZmJhMjdhOWFlZGM0YjYyMTc5YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.edFfJX_z3YViggTP8eC9yyn-TZb63jNQSPM2BxmeIpg)

ok Waiting for yuzu to fix it

**Comment by kkxiegouquan** [comment]
ok !
/Waiting for yuzu to fix it

**Comment by Andeer21** [comment]
Skyline doesn't have this bug

**Comment by evil-trainer** [comment]
> Skyline doesn't have this bug

Yes, it doesn't but can't render the cutscenes, so no opening video or any ending for story mode. I know it may not matter as it's a fighting game, but it's always bad not being able to emulate 100% of the game.
