### ISSUE TITLE
OpenGL is faster than Vulkan on Intel N6005

### ISSUE THREAD

**Issue by tuxrinku** [yuzu-emu/yuzu#12436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest mainline

### Description of Issue

After trying multiple settings, OpenGL is actually faster than Vulkan by far (tested in Link's Awakening, Skyward Sword HD, Super Mario Odyssey, Mario Kart 8 Deluxe). It surprises me since Vulkan is supposed to be faster and it's actually the case on my main computer.

Is this normal or am I missing something ?

I'm on Linux (Ubuntu 22.04), using the latest appimage release.

### Expected Behavior

Having a slightly better performance using vulkan

### Reproduction Steps

Select OpenGL instead of Vulkan

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13747430/yuzu_log.txt)

### System Configuration

CPU: Intel N6005
GPU/Driver: UHD Graphics (32 EU)
RAM: 32GB
OS: Ubuntu 22.04

**Comment by FearlessTobi** [comment]
Since OpenGL and Vulkan are two different backends and use different optimization strategies in some places, it is very well possible that OpenGL can be faster in some games.
