### ISSUE TITLE
Enable Gamemode option doesn't get saved

### ISSUE THREAD

**Issue by TGP17** [yuzu-emu/yuzu#12444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

PR 11946 - Mainline 1659

### Description of Issue

The `Enable Gamemode` option on Linux doesn't get saved. I can disable the option, but it gets enabled again if I restart yuzu. I tested this on a portable build to make sure, that I don't have any broken file or configuration.

### Expected Behavior

The Option should be saved

### Reproduction Steps

Open yuzu on linux, disable the `Enable Gamemode` Option and restart yuzu.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13758327/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i3-1005G1
GPU/Driver: Intel UHD Graphics
RAM: 8GB
OS: Linux Mint 21.2

**Comment by flodavid** [comment]
I will look into it when I have some time. I’m curious why you want to disable it though ?

**Comment by TGP17** [comment]
Gamemode is sometimes a bit buggy with my hardware configuration, Super Mario Bros. Wonder for example is very stuttery and has inconsistent frame rate with Gamemode for me, it basically stops the game from locking to 30 fps if it doesn't run at 60, so Framerate and Gamespeed is fluctuating. Another issue I sometimes have with Gamemode is that it can sometimes keep my laptop from boosting the performance when it charges. Game mode works most of the time perfectly, but I'd like to be able to disable it for these edge cases sometimes.

**Comment by flodavid** [comment]
Yeah I get it, it should be possible to save it as disabled.
You may want to create an issue there to describe your problems https://github.com/FeralInteractive/gamemode
