### ISSUE TITLE
[Android] No More Heroes 1 - Black Rendering Issue (32-bit Game)

### ISSUE THREAD

**Issue by SamSIM-pro** [yuzu-emu/yuzu#12456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android-170

### Description of Issue

No More Heroes has a rendering issue. The game plays well but just black rendering. I have tried various drivers and configurations but no improvement on the rendering. 

https://github.com/yuzu-emu/yuzu/assets/72478312/97a0e189-b063-4af7-92fc-6f730940c247

![Screenshot_20231224_073738_yuzu](https://github.com/yuzu-emu/yuzu/assets/72478312/8fa125d7-32c7-4119-861b-dca50e21c093)
![Screenshot_20231224_073514_yuzu](https://github.com/yuzu-emu/yuzu/assets/72478312/387bae0f-3ae0-47b1-8bff-21dd17db6732)
![Screenshot_20231224_073444_yuzu](https://github.com/yuzu-emu/yuzu/assets/72478312/ef699e9b-6983-4899-b2f7-25cb6a923e0d)

### Expected Behavior

![Screenshot 2023-12-24 07 47 33](https://github.com/yuzu-emu/yuzu/assets/72478312/d8fd49dd-1290-45d3-afa0-d980c318f927)

### Reproduction Steps

Play the game.

### Log File

[yuzu_log.txt.old (1).txt](https://github.com/yuzu-emu/yuzu/files/13761163/yuzu_log.txt.old.1.txt)

### System Configuration

CPU: 865 Qualcomm Snapdragon
GPU/Driver: Turnip - R12
RAM: 6GB
OS: Android 13

**Comment by OMGaCoin** [comment]
Same thing happens to me, using a Poco F5
Qualcomm Snapdragon 7+ gen2 Adreno 725
12gb ram
Gpu driver: Tried stock, Turnip rev 10, 14 and 15 drivers to no avail

**Comment by SamSIM-pro** [comment]
> Same thing happens to me, using a Poco F5 Qualcomm Snapdragon 7+ gen2 Adreno 725 12gb ram Gpu driver: Tried stock, Turnip rev 10, 14 and 15 drivers to no avail

I found the solution. Use Turnip 22.0.99 driver. It's the only driver that fixes the graphical issues, as far as I know.

**Comment by SamSIM-pro** [comment]
I will reiterate for the developers that [Turnip 22.0.99] driver fixes the black rendering. This is the only driver that seems to fix the black rendering. Therefore, it could be a driver problem rather than an emulator problem. If there's anything the developers can do to make the game more compatible with other drivers then by all means, but I will close this issue. 

![Screenshot_20240203_201107_yuzu](https://github.com/yuzu-emu/yuzu/assets/72478312/6296ed40-8aa2-4223-8176-75cef6faa36b)

**Comment by GumbyXGames** [comment]
> I will reiterate for the developers that [Turnip 22.0.99] driver fixes the black rendering. This is the only driver that seems to fix the black rendering. Therefore, it could be a driver problem rather than an emulator problem. If there's anything the developers can do to make the game more compatible with other drivers then by all means, but I will close this issue.
> 
> ![Screenshot_20240203_201107_yuzu](https://private-user-images.githubusercontent.com/72478312/302061547-6296ed40-8aa2-4223-8176-75cef6faa36b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzYxMTgsIm5iZiI6MTcwODc3NTgxOCwicGF0aCI6Ii83MjQ3ODMxMi8zMDIwNjE1NDctNjI5NmVkNDAtOGFhMi00MjIzLTgxNzYtNzVjZWY2ZmFhMzZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDExNTY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ODBjYmE4MzUzOTcyODE0MjUzNTk2NDFjZmYyYTZlZDI2NDkwZjI0MDNlZGVlNDcwYzdlZGY1MzRjYTI0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yeSBhWzEKa2CWV06UTH8v1U8X3ciONgvgnyHvYXpNg4)

The game (with update 1.2.0) won't even boot using the 22.0.99 new.TURNIP driver. Yuzu crashes to the home screen

Build: android-267
Device: Motorola Edge Plus (2022)
SoC: SD8 Gen 1
RAM: 8GB
Android Version: 13
