### ISSUE TITLE
Game save data

### ISSUE THREAD

**Issue by Galvy80** [yuzu-emu/yuzu#12450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

To have the option in Yuzu when deleting game save data there should be a warning window pop up when you hit it. Like a box that pops up asking if you are sure you want to delete. 

### Why would this feature be useful?

It would be useful in preventing someone from accidentally hitting that option and it immediately deleting their save data. I did thsi myself last night when changing per game settings.

**Comment by t895** [comment]
This already exists in the app
![Screenshot_20231223-131817.png](https://github.com/yuzu-emu/yuzu/assets/14132249/158af752-d422-4033-8c44-8eb52c1f363b)
