### ISSUE TITLE
Can't connect with anything (even with my code on C#) to a room hosted by yuzu and yuzu-room

### ISSUE THREAD

**Issue by Metafalica** [yuzu-emu/yuzu#12468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1660

### Description of Issue

Yesterday I tried to coop play with my buddy, but spent all day for zero result (my buddy couldn't connect to my room from his yuzu, and I couldn't connect to him when he hosted a room). I tried many things... and decided to write this ticket after finally trying to test yuzu room hosting feature with this code:
`

            TcpClient tcpc = new TcpClient();
            tcpc.Connect("127.0.0.1", 24872); //gives exception here about connection fail due end PC rejected to accept connection

            if (tcpc.Connected)
            {
                Console.WriteLine("Connected!");
                tcpc.Close();
            }
`
I tried both modes in System -> Network -> (Ethernet and Loopback) for my test.
So... if yuzu doesn't accept connections even from local PC, then sure is something wrong with it's code, not with environment.

The rooms I tried to create was a private and public (later), we couldn't connect to any of these anyway.
My port forwarding was sure correct, because when I run python http server on same port (instead of yuzu room), then my buddy could open it in web browser. As soon as I close http server and run yuzu room again - he couldn't connect to me.
I tried to see if that port is open via online port testing tool. When I have http server running, tool says the port is open, as soon as I host yuzu room, tool says port is closed. Using yuzu-room.exe resulting in same failure.

I had Windows firewall request about yuzu and yuzu-room, of course I allowed them to listen for connections, but something is wrong. And since I had that firewall window popup, yuzu is definitely listening for something, I almost think it's listen on wrong port, not the one I specified in yuzu window or yuzu-room startup parameters...

### Expected Behavior

I expect my buddy will connect to my room without failure

### Reproduction Steps

1. Create private room in yuzu.
2. Try to connect there with another yuzu instance

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13764731/yuzu_log.txt)

### System Configuration

CPU: Intel i7 880
GPU/Driver: AMD Radeon RX 570
RAM: 16 GB
OS: Windows 10 x64

**Comment by FearlessTobi** [comment]
Please share screenshots of your router port configuration and your windows firewall port settings.
Hosting rooms should work fine, as you can also see from the server browser.
It's likely something on your side is not set up correctly.

Additionally, you can try running a simple minecraft server on your pc on the same port and see if your friend can ping it.
That should already give an indication if the forwarding was set up correctly.

**Comment by Metafalica** [comment]
It turned out that yuzu use UDP, not TCP. I can connect with UdpClient from C#, so something wrong somewhere else. No issue with yuzu.
