### ISSUE TITLE
[Android] Key mapping option and support for player configuration 

### ISSUE THREAD

**Issue by Hariu7** [yuzu-emu/yuzu#12460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

As all know key mapping option Wil  make any unsupported controller to work and player configuration enable to play co op with friends. 
We can share screen on TV or any else's 

### Why would this feature be useful?

This will enchance gameplay experience

**Comment by german77** [comment]
yuzu support keyboard. I don't know what you are referring with key mapping.

**Comment by Hariu7** [comment]
> I think it refers to being able to configure and assign any button on the game controller.

https://youtu.be/LI8LMPMVBEE?si=p4VUH85ham-yjBd9

**Comment by Hariu7** [comment]
> yuzu support keyboard. I don't know what you are referring with key mapping.

https://youtu.be/LI8LMPMVBEE?si=p4VUH85ham-yjBd9

**Comment by FearlessTobi** [comment]
There's already other issues open for android key remapping.

Closing as duplicate
