### ISSUE TITLE
In game crash

### ISSUE THREAD

**Issue by Hariu7** [yuzu-emu/yuzu#12474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 171

### Description of Issue

It just crash without starting.

### Expected Behavior

Does not crash

https://github.com/yuzu-emu/yuzu/assets/151449327/3fef7030-c235-4972-a877-2d65b25de93a

### Reproduction Steps

It happens from when yuzu crashed android UI when running the legend of zelda breath of wild. All other

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13766191/yuzu_log.txt.old.txt)

### System Configuration

CPU:snapdragon 865
GPU/Driver:Turnip driver v24.0.0 -
Revision 13
RAM:8+8
OS:13

**Comment by Hariu7** [comment]
Previously wrong log f8le uploaded

**Comment by Hariu7** [comment]
[362.917571] Input <Error> ./common/input.h:CreateDevice:510: Unknown engine name: joycon

**Comment by FearlessTobi** [comment]
Please stop opening duplicate issues.
