### ISSUE TITLE
Feature Request: Custom compiling more than 8GB of memory

### ISSUE THREAD

**Issue by SilentStorm-1986** [yuzu-emu/yuzu#12476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

This isn't as much of a feature request, in terms of the public build, as it is a request for information regarding how the memory system works for the Switch. In a nutshell I'm asking how to alter the code so that a compiled build will recognize a memory allocation beyond 8 GiB.

I asked about this a while ago and received a helpful answer about the standard memory mode and the developer 6 GiB and 8 GiB modes (at the time only 6 GiB was included in the public build). When I tried adding additional memory beyond what the current build of Yuzu uses (6547 GiB for app and 562 MiB for applet), the application cannot access any of the additional memory. I figure that this has something to do with how the emulator is coded, because logically the game should be able to take advantage of as much memory as the emulator makes available.

### Why would this feature be useful?

There are very few use cases for this kind of a feature / custom build, but one that comes to mind is extreme texture packs that require more memory.

**Comment by german77** [comment]
If you need more than 8GB you are doing something wrong. If I recall correctly 8GB is the hardware limit for the switch.

**Comment by SilentStorm-1986** [comment]
It's the technical limit for the _hardware_, but there's no reason that the software should be limited. The Switch uses ASLR, not fixed memory regions.

**Comment by liamwhite** [comment]
With a quick hack to change the 8GB memory arrangement to actually be 16GB (and update related limits to allow the heap to be larger than 8GB):
```diff
--- a/src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
+++ b/src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
@@ -78,7 +78,7 @@ size_t KSystemControl::Init::GetIntendedMemorySize() {
     case Smc::MemorySize_6GB:
         return 6_GiB;
     case Smc::MemorySize_8GB:
-        return 8_GiB;
+        return 16_GiB;
     }
 }
 
@@ -113,7 +113,7 @@ std::size_t KSystemControl::Init::GetApplicationPoolSize() {
             return 3285_MiB;
         case Smc::MemoryArrangement_8GB:
             // Real kernel sets this to 4916_MiB. We are not debugging applets.
-            return 6547_MiB;
+            return 14739_MiB;
         }
     }();
 
--- a/src/core/hle/kernel/k_address_space_info.cpp
+++ b/src/core/hle/kernel/k_address_space_info.cpp
@@ -32,7 +32,7 @@ constexpr std::array<KAddressSpaceInfo, 13> AddressSpaceInfos{{
    { .bit_width = 39, .address = 128_MiB     , .size = 512_GiB - 128_MiB, .type = KAddressSpaceInfo::Type::Map39Bit, },
 #endif
    { .bit_width = 39, .address = Size_Invalid, .size = 64_GiB           , .type = KAddressSpaceInfo::Type::MapSmall  },
-   { .bit_width = 39, .address = Size_Invalid, .size = 8_GiB            , .type = KAddressSpaceInfo::Type::Heap,     },
+   { .bit_width = 39, .address = Size_Invalid, .size = 16_GiB           , .type = KAddressSpaceInfo::Type::Heap,     },
    { .bit_width = 39, .address = Size_Invalid, .size = 64_GiB           , .type = KAddressSpaceInfo::Type::Alias,    },
    { .bit_width = 39, .address = Size_Invalid, .size = 2_GiB            , .type = KAddressSpaceInfo::Type::Stack,    },
 }};

--- a/src/core/hle/kernel/k_memory_layout.h
+++ b/src/core/hle/kernel/k_memory_layout.h
@@ -25,7 +25,7 @@ constexpr std::size_t GetMaximumOverheadSize(std::size_t size) {
 }
 
 constexpr std::size_t MainMemorySize = 4_GiB;
-constexpr std::size_t MainMemorySizeMax = 8_GiB;
+constexpr std::size_t MainMemorySizeMax = 16_GiB;
 
 constexpr std::size_t ReservedEarlyDramSize = 384_KiB;
 constexpr std::size_t DramPhysicalAddress = 0x80000000;
```
libnx homebrew now reports a monstrously large InfoType_TotalMemorySize:
![0000000000000000_2023-12-25_22-18-42-863](https://github.com/yuzu-emu/yuzu/assets/9658600/80a9bdfb-1c69-47f4-80af-6465ad5c0618)

**Comment by FernandoS27** [comment]
I think @liamwhite can answer you this better.

First, if you are asking this to allow games to use more themselves. 95% simply don't and even bug when given a layout different to 4Gb. 

This layouts are only practical for modding. 

In general, most games will just allocate a heap and sundivide it. For 4Gb layouts, the heap is 3Gb, for 6Gb it's 5Gb and 8Gb it's 7Gb, anything bigger, they'll still allocate 7Gb Heap.

I'm not sure if there's some kernel primitive which will limit the user app from using more if we allow this. The kernel itself is designed to allow up to 32 Gbs due to shared codebase with Nintendo's next console.
