### ISSUE TITLE
[Android]The legend of zelda breath of wild crash 

### ISSUE THREAD

**Issue by Hariu7** [yuzu-emu/yuzu#12473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 171

### Description of Issue

It just crash without starting.

https://github.com/yuzu-emu/yuzu/assets/151449327/2221f690-2a81-459b-995e-90fb0c2557cc

### Expected Behavior

Does not crash

### Reproduction Steps

It happens from when yuzu crashed android UI when running the legend of zelda breath of wild. All other game are working fine

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13766171/yuzu_log.txt.old.txt)

### System Configuration

CPU:snapdragon 865
GPU/Driver:Mesa Turnip driver v24.0.0 - Revision 13
RAM: 8+8
OS:android 13
One UI

**Comment by FearlessTobi** [comment]
You already opened an issue for this?

https://github.com/yuzu-emu/yuzu/issues/12147
