### ISSUE TITLE
[Android] Fairy Fencer F Advent Dark Force boots on JIT even if NCE is set in the Settings both EA and Github build with frequent crashes

### ISSUE THREAD

**Issue by rospec14** [yuzu-emu/yuzu#12470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

android-171

### Description of Issue

Fairy Fencer F Advent Dark Force boots on JIT even if NCE is set in the Settings both EA and Github build. It also has frequent crashes in boot. I uploaded two logs for crashing and no crash boot. I also remember playing the game on an early NCE build shared on Discord and was working properly and uses NCE.

### Expected Behavior

Expected to use NCE and no crash.

### Reproduction Steps

Start the game set to NCE.

### Log File

[yuzu_log_crash.txt](https://github.com/yuzu-emu/yuzu/files/13765861/yuzu_log_crash.txt)
[yuzu_log_nocrash.txt](https://github.com/yuzu-emu/yuzu/files/13765862/yuzu_log_nocrash.txt)

### System Configuration

CPU: SD 8 Gen 2
GPU/Driver: Adreno 740 / Turnip R13
RAM: 16GB
OS: Android 13

**Comment by FearlessTobi** [comment]
`common/settings.cpp:SetNceEnabled:170: Program does not utilize 39-bit address space, unable to natively execute code`

It is not possible to use NCE with this title, there's nothing we can do about this.

**Comment by rospec14** [comment]
@FearlessTobi Nothing can be done on the NCE part but still crashes with Assertion Failed errors so it's still a problem imo.
