### ISSUE TITLE
Pause emulation does not release RAM

### ISSUE THREAD

**Issue by Rachid90** [yuzu-emu/yuzu#12484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 1663

### Description of Issue

When I pause the emulation, I can see in the Windows 10 Task Manager that Yuzu is still using the RAM

### Expected Behavior

It should release the RAM

### Reproduction Steps

Launch a game and pause emulation

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13774112/yuzu_log.txt)

### System Configuration

CPU: I7 11800H
GPU/Driver: RTX 3050/546.17
RAM: 16 GB
OS: Windows 10 x64 22H2

**Comment by liamwhite** [comment]
If it released the memory when pausing then you would lose all of the game state and it would be unable to resume. Only shutting down emulation can release memory safely.

**Comment by Rachid90** [comment]
@liamwhite 

> If it released the memory when pausing then you would lose all of the game state and it would be unable to resume.

Of course, but I suggest copying all the game data from the RAM to the disk, like a hibernation on Windows.

**Comment by liamwhite** [comment]
That would make pausing very slow and require sufficient available disk space to work.

**Comment by Rachid90** [comment]
Indeed, it is important that we use it while being aware of its drawbacks, as I am among those who find it useful.
