### ISSUE TITLE
[Android] Octopath Traveler 2 - Visual Bug Issue at Normal Accuracy Level

### ISSUE THREAD

**Issue by JustARegularUser8** [yuzu-emu/yuzu#12498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android-v173 

### Description of Issue

there's a visual bug affecting the game display like red/blue glow when entering town or an encounter. This usually happens when using accuracy level: normal

![Screenshot_20231228_005542_yuzu](https://github.com/yuzu-emu/yuzu/assets/155011410/4ecde0f9-0962-41ae-baee-811285226678)
![Screenshot_20231228_004413_yuzu](https://github.com/yuzu-emu/yuzu/assets/155011410/8c750e62-d543-4372-b118-5a37f3ab00db)

### Expected Behavior

when entering town or encountering a situation, there should be no unusual red/blue glow affecting the game display when using normal accuracy level

### Reproduction Steps

Just play normally 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13780661/yuzu_log.txt)

### System Configuration

CPU:SD778g
GPU/Driver:Adreno642L
RAM:8GB
OS:Android 13

**Comment by FearlessTobi** [comment]
Use high accuracy then
