### ISSUE TITLE
Translation: Improve Chinese Simplified translation

### ISSUE THREAD

**Issue by cxsunflower** [yuzu-emu/yuzu#12494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

it is missing part of the Chinese Simplified translation
![Screenshot_20231227-232721_yuzu](https://github.com/yuzu-emu/yuzu/assets/67369886/cc81fc7a-0d68-465b-9549-35c435c81260)
![Screenshot_20231227-232659_yuzu](https://github.com/yuzu-emu/yuzu/assets/67369886/016d4478-14bb-4487-ac18-ea672bd1c1d7)

### Why would this feature be useful?

it is missing part of the Chinese Simplified translation

**Comment by FearlessTobi** [comment]
Please sign up on [Transifex](https://app.transifex.com/yuzu-emulator/yuzu/dashboard/) and complete the translation there.
