### ISSUE TITLE
[Android] Mario Kart 8 Deluxe crashes when trying to play a race for any map

### ISSUE THREAD

**Issue by cantdecideuser100** [yuzu-emu/yuzu#12496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

android-173

### Description of Issue

The game boots fine, im able to select modes and characters but the problem starts when trying to load a course. after choosing a course, loading screens appears, the fps drops to 0 freezes and crashes. I don't know if this is caused by not having enough ram or if its a gpu/cpu problem.

### Expected Behavior

game should not crash and course should load fine.

### Reproduction Steps

choose any course 

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13780454/yuzu_log.txt.old.txt)

### System Configuration

CPU: Helio G80
GPU/Driver: Mali G52
RAM: 4 GB + 4 GB (ram plus)
OS: Android 12

**Comment by hehk1234** [comment]
You already read the Yuzu requeriments ? You need minimum 8GB RAM and Snapdragon Device.

**Comment by goldenx86** [comment]
Mali works fine for MK8, but 4GB of RAM won't get you anywhere on almost all games.

**Comment by cantdecideuser100** [comment]
I knew 8gb ram is the minimum but i thought it was something else since games were booting with the addition of ram plus. Thank you for letting me know what the problem is.

**Comment by hehk1234** [comment]
> I knew 8gb ram is the minimum but i thought it was something else since games were booting with the addition of ram plus. Thank you for letting me know what the problem is.

Your problem is your device, virtual ram don't makes miracles.

**Comment by cantdecideuser100** [comment]
Yeah i should've known better since my phone is in the low mid range side
