### ISSUE TITLE
Input delay 

### ISSUE THREAD

**Issue by Hariu7** [yuzu-emu/yuzu#12493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 173

### Description of Issue

Input delay of 1.25 s

Uploading Screen_Recording_20231227_190939_yuzu.mp4…

### Expected Behavior

It should take less than 1s

### Reproduction Steps

Click on x button

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13778984/yuzu_log.txt)

### System Configuration

CPU:865
GPU/Driver:Mesa Turnip driver v24.0.0 - Revision 13
RAM:8+8
OS:13

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

Closing
