### ISSUE TITLE
RAM Disk?

### ISSUE THREAD

**Issue by styromaniac** [yuzu-emu/yuzu#12508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The ability to set a RAM Disk for games with heavy textures like Metroid Prime Remastered to prevent the doors slowing down the game while they open.

You guys are the pros, but I'm wondering what your thoughts have been on such a feature since you must have thought of it already.

### Why would this feature be useful?

I think it's possible to resolve games slowing down while loading adjacent areas to where your character is.

**Comment by Pergmen** [comment]
If memory serves correctly, the bottleneck is decoding ASTC textures. No amount of read speed will make a difference, unfortunately

**Comment by goldenx86** [comment]
You can test this yourself.
1. Make a RAMDisk.
2. Symlink the yuzu NAND folder.
3. ???
4. Profit.

Still, the stuttering is on the CPU/GPU decoding the textures. Use Async CPU decoding for Metroid Prime.
