### ISSUE TITLE
Crisis Core Reunion : Final Fantasy VII graphic glitch. 

### ISSUE THREAD

**Issue by IrsyadLuffy** [yuzu-emu/yuzu#12507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu NCE 174

### Description of Issue

Even using any turnip driver (that successfully boot the game) glitch will happen. But I notice that if you restart/load a save file after you exit emulation, glitch gone and it will comeback again later. I notice that this also happen on almost UE4 games.
![Screenshot_2023-12-28-23-46-09-31_ff30e97793d7c52fedd433a73d8d09b9](https://github.com/yuzu-emu/yuzu/assets/45539585/ea85919b-4bd7-43a6-a927-b2d4ace2252b)
![Screenshot_2023-12-28-23-49-04-01_ff30e97793d7c52fedd433a73d8d09b9](https://github.com/yuzu-emu/yuzu/assets/45539585/2c2f870c-46a8-4661-a560-d48960a6d59d)

### Expected Behavior

Game running well but glitches almost here and there. 

### Reproduction Steps

Play until you found glitch. Then find a save point to save the game. Exit game and load the save again. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13787854/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 865
GPU/Driver: Adreno 865
RAM: 8GB
OS: Android 13

**Comment by BSoDGamingYT** [comment]
Use high gpu accuracy.

**Comment by gs233169** [comment]
> Use high gpu accuracy.

can't resolve ,still glitch with high frequency.
