### ISSUE TITLE
Help for low end phone

### ISSUE THREAD

**Issue by imsadbro** [yuzu-emu/yuzu#12526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I hope u guys will improve performance in fifa games for low end phone it keep crashing in the lobby pleaseee fix it

### Why would this feature be useful?

Very useful for low end phone

**Comment by goldenx86** [comment]
Low end phone is not a specific product to check its specs and limitations.
No log file.
No info at all.
