### ISSUE TITLE
Yuzu on Android/Google TV 

### ISSUE THREAD

**Issue by cristi7777** [yuzu-emu/yuzu#12528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It is possible to implement it to Android TV??
Thank you!

### Why would this feature be useful?

Because Google TV would allow to play on a bigger screen then a mibile.

**Comment by G-Spawn** [comment]
Unless it has fantastic specs akin to modern mobile soc & android version that yuzu supports already then no. Some context here: https://yuzu-emu.org/entry/yuzu-android/

Otherwise get a pc and use moonlight/parsec from the googletv/android box.
