### ISSUE TITLE
Bayonetta 3 crashes unexpectedly

### ISSUE THREAD

**Issue by nangongjing1** [yuzu-emu/yuzu#12523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Individuals test EarlyAccess 4034 to the latest version, and may appear in earlier versions, but this problem does not exist in EA 4023

### Description of Issue

After running Bayonetta 3, the video memory usage stepped up and crashed unexpectedly when the VRAM usage was about to increase to 80%.

### Expected Behavior

Bayonetta 3 works normally

### Reproduction Steps

At 2X resolution, it will appear in the middle of or at the end of VERSE1 in Chapter 3

### Log File

`
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13797110/yuzu_log.txt)
`

### System Configuration

CPU:Intel Core i7-12700H
GPU/Driver:NVIDIA RTX 3060 Laptop / 537.58
RAM:16GB
OS:Windows 11 23H2 22631.2861

**Comment by Squall-Leonhart** [comment]
This is an Out of memory event, just because you see 20% available doesn't mean that 20% is available in a contiguous block to be used by the next allocation.

**Comment by nangongjing1** [comment]
> 这是一个内存不足事件，仅仅因为您看到 20% 可用并不意味着 20% 在连续块中可用，供下一次分配使用。

Pls how can I fix this?I've also tried running Bayonetta 3 at 1X resolution in EA4037 and still get the same glitch.However, copying the user folder to EA4023 and starting it does not cause this problem.Versions after 4034 have significantly improved the 1% low frame in the TOTK.

**Comment by nangongjing1** [comment]
The previous upload was the log of EA4037, and this comment is accompanied by the log generated by the same operation of EA4023.
[Uploading yuzu_log.txt…]()

**Comment by nangongjing1** [comment]
EarlyAccess 4045 has solved this problem
