### ISSUE TITLE
Dragon ball fiterz crashes 

### ISSUE THREAD

**Issue by glucuphag** [yuzu-emu/yuzu#12547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Last one 178

### Description of Issue

When I start playing dragon ball fiterz crashes

### Expected Behavior

![Screenshot_20240101-123300](https://github.com/yuzu-emu/yuzu/assets/151690341/53672c35-06d4-47dc-8a23-394b6ac591ac)
When I enter story or arcade 

### Reproduction Steps

.

### Log File

When I share the log the bot said no game booted

### System Configuration

CPU: Google tensor
GPU/Driver: standard 
RAM:8
OS: android 14

**Comment by FearlessTobi** [comment]
Closing, as your report is incomplete.

**Comment by glucuphag** [comment]
How to complete it

**Comment by goldenx86** [comment]
Include the log file here, device name.
The Discord bot not knowing how to read Android logs has nothing to do with its content.
