### ISSUE TITLE
DPAD position will not save when Editing Overlay and pressing Done 

### ISSUE THREAD

**Issue by GitGreater** [yuzu-emu/yuzu#12548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu android 178

### Description of Issue

DPAD position will not save when Editing Overlay and pressing Done. Can reproduce bug on Samsung s23 ultra and Note 20.

### Expected Behavior

Expect overlay button positions to save globally, but preferably per game, after closing game and reopening. 

### Reproduction Steps

Edit Overlay, hit Done, overlay does not save 

### Log File

Very easy to reproduce bug on many devices 

### System Configuration

CPU: _sm8550_
GPU/Driver: snap 
RAM: 12
OS: android

**Comment by GayPotatoEmma** [comment]
Most likely has something to with https://github.com/yuzu-emu/yuzu//pull/12518 as I can't seem to reproduce this on earlier versions

Also only goes back after restarting the game/Yuzu, it remains in place as long as you don't close either.

**Comment by GitGreater** [comment]
> Most likely has something to with https://github.com/yuzu-emu/yuzu//pull/12518 as I can't seem to reproduce this on earlier versions
> 
> Also only goes back after restarting the game/Yuzu, it remains in place as long as you don't close either.

Hello! Do you know if this bug is slated to be fixed on next update or Is there an easy way to revert back to a version without this bug without losing my other paths/settings/saves etc? Cheers!!

**Comment by german77** [comment]
Fixed by #12551
