### ISSUE TITLE
Dragon ball fighter z

### ISSUE THREAD

**Issue by ImBest1144** [yuzu-emu/yuzu#12541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Improve Performance of Dragon Ball Fighter Z and fix random crash in that game please

### Why would this feature be useful?

Just improve 1 game to be better cause a 6gb ram game how can it be slower than 16hb ram game

**Comment by german77** [comment]
This isn't an issue we can accept. We can't magically improve the performance for one game. Expect that over time the emulator will get slightly faster.
