### ISSUE TITLE
"Direct Connect" UI bug

### ISSUE THREAD

**Issue by EmulationEnjoyer** [yuzu-emu/yuzu#12550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1669

### Description of Issue

UI bug in the "Direct Connect" window. The previous UI state is saved upon a successful connection but after restarting Yuzu and attempting to use that previously saved state will result in a failed connection.

Basically, the information in all the textboxes is getting saved and loaded properly but the internal state does not reflect what the UI is showing - specifically the **port number** is what is not being loaded into the internal state and it will instead use the default port number until manually updated by the user (once updated the port number will persist until Yuzu is restarted after which the user will need to update it again)

https://github.com/yuzu-emu/yuzu/assets/144477224/caa7ea9d-5dfa-4313-9217-7c151049d0b7

This is obviously a minor bug but has seemly gone unnoticed or unreported considering it's been around for a good while

### Expected Behavior

Load previously saved port number into internal state and not just the UI

### Reproduction Steps

1. Start a local/remote server (specify a port other than the Yuzu default)
2. Direct connect to the IP:Port with Yuzu
3. After successful connect, disconnect from the room
4. Restart Yuzu and attempt to re-connect with the previously saved IP:Port configuration

### Log File

N/A

### System Configuration

N/A

**Comment by german77** [comment]
Oh lol this bug is interesting let me poke at it. Probably is something dumb.

**Comment by EmulationEnjoyer** [comment]
Appreciate the quick fix, I know you guys have been busy with the Android port lately
