### ISSUE TITLE
Why was Yuzu 180 removed?

### ISSUE THREAD

**Issue by Venvvs** [yuzu-emu/yuzu#12572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

180

### Description of Issue

.

### Expected Behavior

.

### Reproduction Steps

.

### Log File

.

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by evil-trainer** [comment]
Because it had a general bug that prevented the emulator to run any game. It crashed as soon a game was loaded.

**Comment by gidoly** [comment]
It was removed becaused it brome all games on android.  Next build should have them fixed
