### ISSUE TITLE
Crashed Dragon Ball Fighter Z

### ISSUE THREAD

**Issue by ImBest1144** [yuzu-emu/yuzu#12573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu nce 181

### Description of Issue

It can play but it will random crashed in the finish

### Expected Behavior

.

### Reproduction Steps

.

### Log File

I cannt share i dont know what happen with my yuzu

### System Configuration

CPU:snapdragon 678
GPU/Driver:adreno 612
RAM:6Gb
OS:

**Comment by FearlessTobi** [comment]
Incomplete report.
