### ISSUE TITLE
Splatoon 2 inkling squid bounces in ink and/or not able to get in ink and not able to climb walls (Affects Android and in some cases Desktop but may be patched)

### ISSUE THREAD

**Issue by NicholasFlamy** [yuzu-emu/yuzu#12574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Long ago all the way to android-181

### Description of Issue

Whenever the FPS dips below exactly 60 FPS the inkling squid bugs and bounces on the surface of the ink and sometimes will just stay on top of the ink rather than in it. It's a problem for climbing walls and refilling ink as well as moving faster, it's key to the game.

#2640 seems to be the exact problem. If I set GPU accuracy to high it fixes this (as well as a bunch of other small things like skin tones being off but I can live with that.) but it drops my 45-60 FPS to less than 30 FPS so the game is not really playable.
#5038 also seems to be the same thing.
#4982 does not seem to be the same thing.

### Expected Behavior

Inkling squid should go in its own ink.

### Reproduction Steps

Go into ink on a device that is not running perfectly steady 60 FPS with GPU accuracy at normal on Android yuzu.
There may be still a combination of settings that does this exact thing on the desktop version but I haven't tested it.

### Log File

I will add a comment with a video and a log file for the issue. (I have to log in on my phone.)

### System Configuration

CPU: Snapdragon 888
GPU/Driver: Adreno 660 [Mesa Turnip driver v24.0.0 - Revision 14](https://github.com/K11MCH1/AdrenoToolsDrivers/releases/tag/v24.0.0_R14) Any driver (that functions) has this problem I think.
RAM: 8GB
OS: OneUI 5.1 Android 13

Samsung Galaxy S21

**Comment by FernandoS27** [comment]
it's expected as Normal accuracy skips frames.

**Comment by NicholasFlamy** [comment]
> it's expected as Normal accuracy skips fences. If the machine is not fast enough, it won't read them when ready.

Is there no tweak that could allow something in-between? Let me send a video, it's super close to working. 

https://github.com/yuzu-emu/yuzu/assets/30300649/5bedae93-9296-48e5-8064-4ae8f825b90f


https://github.com/yuzu-emu/yuzu/assets/30300649/099d7162-e27a-4359-a973-7497e1a10cef


https://github.com/yuzu-emu/yuzu/assets/30300649/6e617b90-b7b9-4445-878e-6c8ba8ae9a67

**Comment by NicholasFlamy** [comment]
> Whenever the FPS dips below exactly 60 FPS

I think it's actually just when the FPS is wavering.

**Comment by NicholasFlamy** [comment]
Also:
              The ink issue is fixed in master/mainline with the merge of #3409, though only with async disabled.

_Originally posted by @ActualMandM in https://github.com/yuzu-emu/yuzu/issues/2640#issuecomment-590024152_
            
In the log file it shows the configured settings. I disabled "Use asynchronous shaders" to be sure that wasn't the problem and the videos have it off. The log shows this option which I think is the same one: `Renderer.use_asynchronous_shaders: false`
I also found:
`Renderer.use_asynchronous_gpu_emulation: true`
`Renderer.async_presentation: true`

But I don't think that's exposed in Android yuzu as an option but this guy said that disabling async fixes it in the original desktop version of yuzu which android yuzu is based off of.

**Comment by NicholasFlamy** [comment]
> it's expected as Normal accuracy skips fences. If the machine is not fast enough, it won't read them when ready.

So what happens when I apply a 30 FPS mod? I set it to high accuracy and the squid won't go in the ink. Like every so often it bounces but otherwise is stuck completely outside of the ink. It's able to get to 30 FPS if I face in a direction with less stuff but FPS doesn't seem to affect the squid going into the ink. So why high accuracy without the mod works but with the mod it doesn't even though it's running at about the same FPS?
