### ISSUE TITLE
Remove Game/Folder Listings on Main Window on Yuzu for Linux (Steam Deck)

### ISSUE THREAD

**Issue by apennismightier** [yuzu-emu/yuzu#12577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

There is no way to remove a folder or game you've added to the Yuzu main menu on Steam Deck. This seems like such a simple and obvious feature that for some reason isn't present. I understand this version of Yuzu may not have regular updates, but it would be great if we had some control over our own game listings in the program.

### Why would this feature be useful?

It seems like a basic out of the box option that is present in nearly every app.

**Comment by t895** [comment]
Right click the directory and select remove

**Comment by apennismightier** [comment]
There is no "right click" on Steam Deck. Holding down the touchpad normally results in a right click function, but it does nothing within Yuzu. Whether I'm in Desktop mode or Gamepad mode, none of the menu items when "right clicked" or selected have any kind of additional menu that allows you to remove it.

**Comment by t895** [comment]
If you press the left trigger you can right click as well
![Screenshot_20240104_144202](https://github.com/yuzu-emu/yuzu/assets/14132249/83377391-7d2f-4eb2-b360-ce480b1ab27d)

**Comment by apennismightier** [comment]
OMFG. Why does no one know about this? Amazing. Ty.
