### ISSUE TITLE
Android - Refresh Rate locked @60hz

### ISSUE THREAD

**Issue by djdp77** [yuzu-emu/yuzu#12578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

android-181

### Description of Issue

While on Yuzu, either navigating its menu or in-game, my screen which supports 120hz is locked at60hz

### Expected Behavior

Refresh Rate stays at 120hz (indifferent if playing at a locked 30/60 fps but allows for playing at 40fps for example with no stutter or play games that run at 60fps at 200% speed)

### Reproduction Steps

Open Yuzu

### Log File

n/a

### System Configuration

CPU: SD7+g2
GPU/Driver: qc / turnip
RAM: 12gb
OS: android 13

**Comment by t895** [comment]
This sounds like an OEM issue. Have you also made sure to disable vsync when in-game?

**Comment by djdp77** [comment]
@t895 
Hi, I tried all the different VSync modes but that didn't solve it. I have my phone set to always 120hz. All other apps work as intended (including emulators such as Dolphin)

There is a submenu for "Apps using high refresh rate" where all apps are selected but Yuzu and Camera which state "Based on app settings" (screenshot attached)

![Screenshot_2024-01-04-19-56-36-498_com xiaomi misettings-edit](https://github.com/yuzu-emu/yuzu/assets/9308718/f47a6abf-79fd-4882-a4ef-7179203f5d0a)

**Comment by t895** [comment]
We don't do anything to override the refresh rate of the app so this seems like an allowlist created by your phone's manufacturer

**Comment by djdp77** [comment]
I can get it to lock at 120hz if I disable "Turn on MIUI optimization" in developer options
