### ISSUE TITLE
Graphical issue flickering shadows/Dead inside eyes Pokémon Sword/Shield

### ISSUE THREAD

**Issue by XOmega27890** [yuzu-emu/yuzu#12580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All

### Description of Issue

Hello,
I'm using yuzu nce latest build with a poco f5 12/256gb and the ea yuzu from the play store in order to play pokemon 
swsh however no matter the driver i use there is always an issue.
Using the mesa 24 R14=flickering shadows
Using the Qualcomm adreno 676 from motorola= all the character got dead inside eyes and gastly is partially invisible the same apply for the gpu driver and all the others drivers none of them can fix this issue.

https://github.com/yuzu-emu/yuzu/assets/155690491/dc89a79e-5419-4c27-9d3c-1d4eccb73bc0

![Screenshot_2024-01-05-00-35-41-520_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/155690491/f5a8c219-3598-4d52-970c-3739eea956d8)

### Expected Behavior

Graphical issue

### Reproduction Steps

I'm using a poco f5 and i put one of these two drivers with the latest build and this is happening.

### Log File

The game is not crashing just a graphical issue.

### System Configuration

CPU:Snapdragon 7+ gen 2
GPU/Driver:Turnip Driver R14/Qualcomm 676/Gpu driver.
RAM:7.4/12
OS:Xiaomi HyperOS/MIUI14

**Comment by FearlessTobi** [comment]
Please fill out the issue template as requested.

**Comment by Hariu7** [comment]
Try by using different driver

**Comment by FearlessTobi** [comment]
User is unresponsive and did not provide a log file.

Closing
