### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by ImBest1144** [yuzu-emu/yuzu#12587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I think you guys should focus to update make 1 update about 1-2 weeks or 1 month to make sure to fix bug or update any new to updrage perfomance

### Why would this feature be useful?

Very useful i guess,instead of just 1 day 1 update and not kinda change anything
Sr if i wrong this just a suggestion 👍🏿👍🏿

**Comment by liamwhite** [comment]
we update every day because we are pushing changes almost every single day; inactive periods are too infrequent to justify a weekly release schedule at this point in time

**Comment by german77** [comment]
Updating once a week will slow down the project overall. If you are concerned about too frequent updates you can execute yuzu.exe directly this will avoid running the maintenance tool and yuzu will not update automatically.
