### ISSUE TITLE
[macOS] Build: Issue with configuring CMake for nx_tzdb

### ISSUE THREAD

**Issue by shinra-electric** [yuzu-emu/yuzu#12581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

N/A

### Description of Issue

CMake configuration fails with M1 Pro/Sonoma 14.3 Beta/Xcode 15.1.

The line that stands out to me is: 
`fatal: not a git repository: /Users/user/yuzu/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tmpsrc/../../../../../../.git/modules/tzdb_to_nx/modules/externals/tz/tz`

### Expected Behavior

CMake configuration should complete

### Reproduction Steps

Try to build on a similar system setup. 

### Log File

[Yuzu Output.txt](https://github.com/yuzu-emu/yuzu/files/13837027/Yuzu.Output.txt)

### System Configuration

CPU: M1 Pro
GPU/Driver: M1 Pro
RAM: 16GB 
OS: Sonoma 14.3 Beta

**Comment by shinra-electric** [comment]
I think that the path is just missing one `../`

**Comment by liamwhite** [comment]
The actual issue is the missing library -lintl which was fixed in https://github.com/lat9nq/tzdb_to_nx/pull/13
`git submodule update --init --recursive` to ensure it's updated

**Comment by shinra-electric** [comment]
My script will clone the repository recursively, so it's usually up to date. 

I've tried from scratch here, and you can see the output: 
[Yuzu Output.txt](https://github.com/yuzu-emu/yuzu/files/13841895/Yuzu.Output.txt)

nx_tzdb is up to date as you can see here: 
![Screenshot 2024-01-05 at 12 10 24](https://github.com/yuzu-emu/yuzu/assets/50119606/c0fadfeb-21a9-476e-9cf0-143455913c15)

**Comment by liamwhite** [comment]
Okay, that's a bit weird. Are we missing installing whatever provides the intl library from homebrew? We have CI steps for mac now which are still passing:
https://github.com/yuzu-emu/yuzu/blob/92a331af76cba638f01490eeb0045ca4d6d27df7/.github/workflows/verify.yml#L80-L90

**Comment by shinra-electric** [comment]
> Okay, that's a bit weird. Are we missing installing whatever provides the intl library from homebrew? We have CI steps for mac now which are still passing:

I can't see anything there that is different (except I'm using latest Boost and Qt6, but I have been using these without issue for ages). 

Are you sure the `not a git repository` error isn't the problem? 

If I cd into the path with the error message, it doesn't exist. But if I add a `/..` in the middle I successfully reach it. 

I can't find where this path is generated though.

**Comment by liamwhite** [comment]
Yeah, I'm sure. If you look at any recent CI run, you'll see the same: ![image](https://github.com/yuzu-emu/yuzu/assets/9658600/c5e31bd1-f811-4d3d-8bb8-c3ff3825b618) It's not fatal, but not finding -lintl is fatal.

**Comment by shinra-electric** [comment]
I think that maybe the Intl library was removed from a recent macOS update. 

See [here](https://alexmanrique.com/blog/development/2022/01/16/Unable-to-load-dynamic-library-intl.html) for details. 

I have a spare Intel Mac on Ventura, I'll give it a shot there...

**Comment by liamwhite** [comment]
If you install gettext from homebrew, does that fix the issue?

**Comment by shinra-electric** [comment]
No, I already have `gettext 0.22.4` installed

**Comment by Steveice10** [comment]
If you're building on Apple Silicon it could be because homebrew installs to `/opt/homebrew` instead of `/usr/local` like on x86_64 systems.

**Comment by shinra-electric** [comment]
But I have always built Yuzu on Apple Silicon. 
Have there been any changes recently that would make this an issue?

**Comment by Steveice10** [comment]
> But I have always built Yuzu on Apple Silicon. Have there been any changes recently that would make this an issue?

nx_tzdb did not link against intl until the PR linked earlier in this issue thread from Nov 29.

**Comment by liamwhite** [comment]
I assume that if you explicitly specify the path to libintl.dylib here <https://github.com/lat9nq/tzdb_to_nx/blob/main/externals/tz/CMakeLists.txt#L18> it will work. What would be a more portable way to specify this than assuming it will be in the default linker search paths?

**Comment by liamwhite** [comment]
Okay, you could try this:
```cmake
find_program(GNU_MAKE make)
if ("${GNU_MAKE}" STREQUAL "GNU_MAKE-NOTFOUND")
    message(FATAL_ERROR "GNU make not found")
endif()

if (APPLE)
    find_package(Intl required)
endif()

if (NOT EXISTS "${TZ_DIR}" OR NOT EXISTS "${TZIF_LIST_FILE}")
    # tz's makefile can only build in-tree, so copy the whole source tree to a
    # separate directory before building.
    file(COPY ${TZ_SOURCE_DIR}/ DESTINATION ${TZ_TMP_SOURCE_DIR})

    if (APPLE)
        set(TZ_MAKEFLAGS "LDLIBS=${Intl_LIBRARY}")
    else()
        set(TZ_MAKEFLAGS)
    endif()
```

**Comment by shinra-electric** [comment]
```
CMake Error at externals/nx_tzdb/tzdb_to_nx/externals/tz/CMakeLists.txt:13 (find_package):
  find_package called with invalid argument "required"
```
[Terminal Saved Output.txt](https://github.com/yuzu-emu/yuzu/files/13878680/Terminal.Saved.Output.txt)

**Comment by liamwhite** [comment]
sorry, REQUIRED instead of required

**Comment by shinra-electric** [comment]
Yes, we're back in business! 

<img width="1162" alt="Screenshot 2024-01-09 at 21 40 51" src="https://github.com/yuzu-emu/yuzu/assets/50119606/b8f6fbe8-3dd8-4aca-a78a-1269d2bcdfe2">

**Comment by Steveice10** [comment]
FYI GitHub just launched M1 runners if you're interested in adding a verification workflow for this.

**Comment by shinra-electric** [comment]
> FYI GitHub just launched free tier M1 runners if you're interested in adding a verification workflow for this.

Yeah, I just saw you added it to Citra. Great news!

**Comment by liamwhite** [comment]
Is it just a matter of changing over to macos-14?

**Comment by Steveice10** [comment]
> Is it just a matter of changing over to macos-14?

Yes, macos-14 runners are always ARM. Assuming the build scripts in the job work on an ARM Mac there shouldn’t be anything else that needs to be done.
