### ISSUE TITLE
[Android] FE:3Houses consuming +1600mA in Main Menu even set at 0.5x graphics

### ISSUE THREAD

**Issue by rospec14** [yuzu-emu/yuzu#12590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

android-184

### Description of Issue

This might not be called a bug since there are no crashes but it's weird that FE:3H is consuming 1600mA in Main Menu where nothing CPU or GPU extensive is happening. The graphics is set at 0.5x and it's making the fan of my Odin 2 run at full throttle.

![image](https://github.com/yuzu-emu/yuzu/assets/117153936/572ef417-0467-47f7-83f3-c50489190651)

### Expected Behavior

I think it should not consume that much battery.

### Reproduction Steps

Start Three Houses with DevInfoOverlay and observe stats in Main Menu

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13850588/yuzu_log.txt)

### System Configuration

CPU: SD 8 Gen 2
GPU/Driver: Adreno 740 / Turnip R14
RAM: 16GB
OS: Android 13

**Comment by german77** [comment]
Menu sometimes are more demanding than the game itself. Similar happens on SSBU. Resolution doesn't influence that much on power consumption. Since this is not an issue but rather an inconvenience we can't fix this. Maybe in a future our hardware requirements will be reduced.
