### ISSUE TITLE
OpenGL ES For android 

### ISSUE THREAD

**Issue by GithubUser559** [yuzu-emu/yuzu#12595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add OpenGL ES to Android with the new NCE feature 

### Why would this feature be useful?

To Improve Compatibility And Fix Crashes on Some Powerful Devices Without Vulkan

**Comment by FearlessTobi** [comment]
No, OpenGL ES will never be supported in yuzu.

Only Vulkan provides all the features we need for emulating the Switch.

**Comment by FernandoS27** [comment]
There are no Powerful devices without Vulkan.
