### ISSUE TITLE
Metroid Dread crash at boot

### ISSUE THREAD

**Issue by HasdelBora** [yuzu-emu/yuzu#12607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1675

### Description of Issue

Freeze or crash in the boot screen

### Expected Behavior

Game doesnt launch

### Reproduction Steps

Just boot the game

### Log File

NO

### System Configuration

CPU:I7
GPU/Driver:Nvidia
RAM:32
OS:W10

**Comment by german77** [comment]
Incomplete issue report.

**Comment by Squall-Leonhart** [comment]
I can't replicate this on mainline or personal builds anyway.
