### ISSUE TITLE
Nier automata glitch bugs fix 

### ISSUE THREAD

**Issue by 2banda2aremywifes** [yuzu-emu/yuzu#12635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Ea Android 

### Description of Issue

There's some sort of glitches on nier when playing, I hope this gets fixed

### Expected Behavior

Idk

### Reproduction Steps

Idk

### Log File

Idk

### System Configuration

CPU: snapdragon 8gen1
GPU/Driver:
RAM:12gb
OS:
Touchos

**Comment by sakuramipha** [comment]
Template filled incorrectly and no information provided to developers. Closing this one, please reopen one that is correctly filled out.
