### ISSUE TITLE
Battery drain faster than usual 

### ISSUE THREAD

**Issue by Bigby69x** [yuzu-emu/yuzu#12630]
### Issue

sir i’m using realme x3 sz (sd 855+ , 8gb ram) recently from last 10 builds of yuzu github i’m experiencing battery drainage very fastly than usual, i play naruto storm connections, pokemon arceus, mario wonder especially in zelda botw & mario odyssey it’s like 20 min play 20-22% drainage, normal default settings , pls fix this.

**Comment by gidoly** [comment]
Fill the issue templet correctly. And specify which version started to do that

**Comment by Bigby69x** [comment]
i'm using android beta version 73f2201b1 today's build & have same issues 10min play 11% battery drain

**Comment by gidoly** [comment]
Yes but which version started to make that happen

**Comment by gidoly** [comment]
So 168 was first build that exposed issue or 171 is?

**Comment by Bigby69x** [comment]
Build v171, (apart from battery drain, performance significantly improved).
