### ISSUE TITLE
android build error: use of undeclared identifier 'save_struct'

### ISSUE THREAD

**Issue by cxsunflower** [yuzu-emu/yuzu#12647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

android-189 6f9d0e1

### Description of Issue

/home/cx/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android30 --sysroot=/home/cx/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DARCHITECTURE_arm64=1 -DBOOST_ASIO_DISABLE_CONCEPTS -DHAS_NCE=1 -DYUZU_UNIX=1 -D_DEBUG -I/home/cx/Works/git_work/yuzu-android/src/. -I/home/cx/Works/git_work/yuzu-android/externals/./microprofile -I/home/cx/Works/git_work/yuzu-android/externals/./stb -I/home/cx/Works/git_work/yuzu-android/externals/opus/include -I/home/cx/Works/git_work/yuzu-android/externals/glad/include -I/home/cx/Works/git_work/yuzu-android/externals/sirit/src/../include -I/home/cx/Works/git_work/yuzu-android/externals/sirit/externals/SPIRV-Headers/include -I/home/cx/Works/git_work/yuzu-android/externals/./bc_decoder -I/home/cx/Works/git_work/yuzu-android/externals/nx_tzdb/include -I/home/cx/Works/git_work/yuzu-android/src/android/app/.cxx/Debug/1x5w452l/arm64-v8a/externals/nx_tzdb/include -I/home/cx/Works/git_work/yuzu-android/externals/./mbedtls/include -I/home/cx/Works/git_work/yuzu-android/externals/dynarmic/externals/mcl/src/../include -I/home/cx/Works/git_work/yuzu-android/externals/oaknut/include -I/home/cx/Works/git_work/yuzu-android/externals/dynarmic/src/dynarmic/.. -isystem /home/cx/Works/git_work/yuzu-android/src/android/app/.cxx/Debug/1x5w452l/arm64-v8a/vcpkg_installed/arm64-android/include -isystem /home/cx/Works/git_work/yuzu-android/externals/./renderdoc -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -flto=thin -fPIC -fwrapv -Werror=all -Werror=extra -Werror=missing-declarations -Werror=shadow -Werror=unused -Wno-attributes -Wno-invalid-offsetof -Wno-unused-parameter -Wno-braced-scalar-init -Wno-unused-private-field -Wno-nullability-completeness -Werror=shadow-uncaptured-local -Werror=implicit-fallthrough -Werror=type-limits -Werror=conversion -Wno-sign-conversion -Wno-cast-function-type -fsized-deallocation -pthread -std=gnu++20 -Winvalid-pch -Xclang -include-pch -Xclang /home/cx/Works/git_work/yuzu-android/src/android/app/.cxx/Debug/1x5w452l/arm64-v8a/src/core/CMakeFiles/core.dir/cmake_pch.hxx.pch -Xclang -include -Xclang /home/cx/Works/git_work/yuzu-android/src/android/app/.cxx/Debug/1x5w452l/arm64-v8a/src/core/CMakeFiles/core.dir/cmake_pch.hxx -MD -MT src/core/CMakeFiles/core.dir/hle/service/filesystem/save_data_controller.cpp.o -MF src/core/CMakeFiles/core.dir/hle/service/filesystem/save_data_controller.cpp.o.d -o src/core/CMakeFiles/core.dir/hle/service/filesystem/save_data_controller.cpp.o -c /home/cx/Works/git_work/yuzu-android/src/core/hle/service/filesystem/save_data_controller.cpp

/home/cx/Works/git_work/yuzu-android/src/core/hle/service/filesystem/save_data_controller.cpp:43:15: error: use of undeclared identifier 'save_struct'
              save_struct.DebugInfo());

### Expected Behavior

build success

### Reproduction Steps

git clone https://github.com/yuzu-emu/yuzu-android.git --recursive
git submodule update --init --recursive 
./gradlew assembleMainline

### Log File

[900/1533] Building CXX object src/core/CMakeFiles/core.dir/hle/service/es/es.cpp.o
  [901/1533] Building CXX object src/core/CMakeFiles/core.dir/hle/service/filesystem/save_data_controller.cpp.o
  FAILED: src/core/CMakeFiles/core.dir/hle/service/filesystem/save_data_controller.cpp.o 
  /home/cx/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android30 --sysroot=/home/cx/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DARCHITECTURE_arm64=1 -DBOOST_ASIO_DISABLE_CONCEPTS -DHAS_NCE=1 -DYUZU_UNIX=1 -D_DEBUG -I/home/cx/Works/git_work/yuzu-android/src/. -I/home/cx/Works/git_work/yuzu-android/externals/./microprofile -I/home/cx/Works/git_work/yuzu-android/externals/./stb -I/home/cx/Works/git_work/yuzu-android/externals/opus/include -I/home/cx/Works/git_work/yuzu-android/externals/glad/include -I/home/cx/Works/git_work/yuzu-android/externals/sirit/src/../include -I/home/cx/Works/git_work/yuzu-android/externals/sirit/externals/SPIRV-Headers/include -I/home/cx/Works/git_work/yuzu-android/externals/./bc_decoder -I/home/cx/Works/git_work/yuzu-android/externals/nx_tzdb/include -I/home/cx/Works/git_work/yuzu-android/src/android/app/.cxx/Debug/1x5w452l/arm64-v8a/externals/nx_tzdb/include -I/home/cx/Works/git_work/yuzu-android/externals/./mbedtls/include -I/home/cx/Works/git_work/yuzu-android/externals/dynarmic/externals/mcl/src/../include -I/home/cx/Works/git_work/yuzu-android/externals/oaknut/include -I/home/cx/Works/git_work/yuzu-android/externals/dynarmic/src/dynarmic/.. -isystem /home/cx/Works/git_work/yuzu-android/src/android/app/.cxx/Debug/1x5w452l/arm64-v8a/vcpkg_installed/arm64-android/include -isystem /home/cx/Works/git_work/yuzu-android/externals/./renderdoc -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -flto=thin -fPIC -fwrapv -Werror=all -Werror=extra -Werror=missing-declarations -Werror=shadow -Werror=unused -Wno-attributes -Wno-invalid-offsetof -Wno-unused-parameter -Wno-braced-scalar-init -Wno-unused-private-field -Wno-nullability-completeness -Werror=shadow-uncaptured-local -Werror=implicit-fallthrough -Werror=type-limits -Werror=conversion -Wno-sign-conversion -Wno-cast-function-type -fsized-deallocation -pthread -std=gnu++20 -Winvalid-pch -Xclang -include-pch -Xclang /home/cx/Works/git_work/yuzu-android/src/android/app/.cxx/Debug/1x5w452l/arm64-v8a/src/core/CMakeFiles/core.dir/cmake_pch.hxx.pch -Xclang -include -Xclang /home/cx/Works/git_work/yuzu-android/src/android/app/.cxx/Debug/1x5w452l/arm64-v8a/src/core/CMakeFiles/core.dir/cmake_pch.hxx -MD -MT src/core/CMakeFiles/core.dir/hle/service/filesystem/save_data_controller.cpp.o -MF src/core/CMakeFiles/core.dir/hle/service/filesystem/save_data_controller.cpp.o.d -o src/core/CMakeFiles/core.dir/hle/service/filesystem/save_data_controller.cpp.o -c /home/cx/Works/git_work/yuzu-android/src/core/hle/service/filesystem/save_data_controller.cpp
  /home/cx/Works/git_work/yuzu-android/src/core/hle/service/filesystem/save_data_controller.cpp:43:15: error: use of undeclared identifier 'save_struct'
                save_struct.DebugInfo());
                ^
  1 error generated.
  [902/1533] Building CXX object src/core/CMakeFiles/core.dir/hle/service/fatal/fatal.cpp.o
  [903/1533] Building CXX object src/core/CMakeFiles/core.dir/hle/service/filesystem/fsp_ldr.cpp.o
  [904/1533] Building CXX object src/core/CMakeFiles/core.dir/hle/service/filesystem/fsp_srv.cpp.o
  [905/1533] Building CXX object src/core/CMakeFiles/core.dir/hle/service/filesystem/fsp_pr.cpp.o
  [906/1533] Building CXX object src/core/CMakeFiles/core.dir/hle/service/friend/friend_interface.cpp.o
  [907/1533] Building CXX object src/core/CMakeFiles/core.dir/hle/service/glue/notif.cpp.o
  [908/1533] Building CXX object src/core/CMakeFiles/core.dir/hle/service/fgm/fgm.cpp.o
  [909/1533] Building CXX object src/core/CMakeFiles/core.dir/hle/service/friend/friend.cpp.o
  [910/1533] Building CXX object src/core/CMakeFiles/core.dir/hle/service/filesystem/filesystem.cpp.o
  ninja: build stopped: subcommand failed.
  

### System Configuration

CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8) @ 2.10 GHz
GPU/Driver: AMD Radeon Vega 8
RAM: 16GiB
OS: Archlinux

**Comment by liamwhite** [comment]
It is never recommended to compile in debug mode, but: https://github.com/yuzu-emu/yuzu/compare/417df3b6ee339ac0068c736285e3cb612f7dd2ff..aae9eea53208fc0924c90ebb1272fcfaa3f23e0c
