### ISSUE TITLE
GPU usage is very high with Turnip drivers

### ISSUE THREAD

**Issue by iamnotkurtcobain** [yuzu-emu/yuzu#12649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All builds

### Description of Issue

I compared prop drivers with every recent Turnip drivers and GPU usage is very high in many games such as Mario Odyssee and BotW. These high GPU usage lead to framedrops and worse performance overall.

Mario Odyssey has a lower GPU usage in docked mode with prop drivers than turnip drivers in handheld mode. That's crazy.

### Expected Behavior

GPU usage shouldn't be 99 or 100% in some games.

### Reproduction Steps

Just use Turnip drivers on a A7xx device with certain games.

### Log File

Not needed 

### System Configuration

CPU: 8gen2
GPU/Driver: Adreno 740 with Turnip 
RAM: 12GB
OS: Android 13

**Comment by liamwhite** [comment]
Does the increased reported usage correspond to increased power consumption?

**Comment by liamwhite** [comment]
Also, I struggle to understand how this would not simply be an issue with Turnip structuring its command lists differently to the prop driver. What is yuzu supposed to do about this? How is this our bug? We are issuing effectively the same Vulkan commands to it that we do to the prop driver.

**Comment by FearlessTobi** [comment]
Agree this is not really our responsibility and sounds more like a Turnip issue, if its an issue at all.

**Comment by hehk1234** [comment]
I don't know if it's very useful, but this situation also happens with Qualcomm's proprietary drivers. Even with glitches or bugs, GPU usage is at the same level as turnip in the games I've tested.
