### ISSUE TITLE
Crashed 

### ISSUE THREAD

**Issue by ImBest1144** [yuzu-emu/yuzu#12663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nce v191

### Description of Issue

It join into the lobby then after 5s it crashed it better than the before version it crashed when i join lobby (I used Mesa turnip driver it crashed but it can run on v682 but bug)

### Expected Behavior

.

### Reproduction Steps

.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13927509/yuzu_log.txt.old.txt)

### System Configuration

CPU:
GPU/Driver:adreno 612
RAM:
OS:

**Comment by FearlessTobi** [comment]
Issue has neither a useful title, nor has the template been filled out correctly.

Closing
