### ISSUE TITLE
yuzu android Cannot start super robot wars under NCE

### ISSUE THREAD

**Issue by Jakojako2020** [yuzu-emu/yuzu#12668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu android 188

### Description of Issue

yuzu android cannot start super robot wars under NCE after version 181 V X T 30

### Expected Behavior

no

### Reproduction Steps

no

### Log File

no

### System Configuration

CPU:855
GPU/Driver:640
RAM:8
OS:android

**Comment by FearlessTobi** [comment]
no
