### ISSUE TITLE
[Android] Final Fantasy XII drop to 0 fps (both dynam and nce)

### ISSUE THREAD

**Issue by RaduNastase** [yuzu-emu/yuzu#12672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All versions including latest

### Description of Issue

The game drops to 0 fps every time when entering the castle and the cutscene would start, right after the tutorial battle.
No graphical or performance issues otherwise.

### Expected Behavior

Should play normally, no crash.

### Reproduction Steps

Play for a couple of minutes and go in the castle.

### Log File

  .

### System Configuration

CPU: Snapdragon 865+
GPU/Driver: Mesa 23.1.0 / 24.0 and few more others tested
RAM: 12 gb
OS: Android 11

**Comment by FearlessTobi** [comment]
Issue is missing a log file. Closing.
