### ISSUE TITLE
SSB amiibos do not save/register

### ISSUE THREAD

**Issue by ethicalhacker7192** [yuzu-emu/yuzu#12675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1680

### Description of Issue

These amiibos will not save/register/formatted, this can be very problematic for games that require the amiibos to be registered, such as super smash bros ultimate. I have duplicated this error with many SSB amibos, including but not limited to the "Fox.bin" amiibos.

### Expected Behavior

This SSB amiibo should be able to be saved/formatted/registered.

### Reproduction Steps

Steps to replicate:
1. Get a SSB Amiibo
2. If any data (backup first or just do with a blank amiibo) format
3. assuming you have data on said amiibo, it should still have it, if the amiibo is blank then try registering it.
4. now that you have registered it, try saving/using it in super smash bros ultimate. If all is duplicated, your data should have not changed at all, when training this amiibo, you also are not able to save to it.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13932878/yuzu_log.txt)

### System Configuration

CPU: 12th Gen Intel(R) Core(TM) i7-12700KF | AVX2 | FMA
GPU/Driver: GPU
AMD Radeon RX 6600
Primary/Discrete
RAM: 64GB
OS: Windows 11 23h2

**Comment by german77** [comment]
Amiibos are encrypted. You can't save/load data on them without encryption keys. Please dump your amiibo keys with lockpick and try again. If you still have issues after that feel free to reopen the issue with a new log.

**Comment by ethicalhacker7192** [comment]
So I have done that but now when I try to register the blank amiibo, it says it is corrupted right then and there afterwards but works (kinda).

**Comment by german77** [comment]
It might contain an invalid state. You can use the amiibo data eraser from the tools menu to fix the amiibo. Upload a log if you want more details it usually prints exactly why it failed

**Comment by german77** [comment]
I think the amiibo restorer will fix corruption as well without deleting game data

**Comment by ethicalhacker7192** [comment]
it didn't work, saying that it was not able to restore the amiibo, I think this is a very good issue to develop on or at least find a (somewhat) way to keep it from corrupting.

**Comment by ethicalhacker7192** [comment]
okay, I have fixed the issue, it has to do with the way the amiibos' are formatted, when they are not formatted properly, you get issues, and by issues, I mean lots of them.
