### ISSUE TITLE
Wrong BGM played while fighting final boss black dragon in Tears of the Kingdom

### ISSUE THREAD

**Issue by 6543x1** [yuzu-emu/yuzu#12670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 4034

### Description of Issue

In yuzu 4034 or 3730(I just tried these two versions),when playing Tears of kingdom,in final boss(black dragon),the bgm played wrong(it became the bgm same with standing in drgaon,not it should be).But when i tried downgrade the version to 3638, the bgm played true.Game version is 1.1.0,and all the saves are same.

### Expected Behavior

final boss in totk

### Reproduction Steps

1、start totk game
2、go fighting final boss black dragon

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13931168/yuzu_log.txt.old.txt)
this log is from 4034 version

### System Configuration

CPU:Ryzen 4800H
GPU/Driver:RTX 2060 ,driver version 546.33
RAM:16G
OS:Windows 10 22H2

**Comment by liamwhite** [comment]
This is a bug in the dynamic FPS mod. As evidence, I offer that it is also broken with the latest version of Ryujinx as of the time of writing, and in both cases only broken when using the mod. Without the mod, the correct audio plays, as expected.

https://github.com/yuzu-emu/yuzu/assets/9658600/e4577c11-faf9-4fb3-b8e9-b421bb8d8843
