### ISSUE TITLE
Resizing doesn't work correcly on Wayland when doing window smaller. It works well when making window bigger.

### ISSUE THREAD

**Issue by scastilloml** [yuzu-emu/yuzu#12684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline-20240115

### Description of Issue

I build yuzu-mainline by myself following instructions at: https://yuzu-emu.org/wiki/building-for-linux/

I'm doing this from some time now and I found that recently yuzu does not resize correctly the game window if i try to make it smaller. It works well when I try to make window bigger. It also works well if I use X11 instead of Wayland.

The problem when sizing down the window under wayland is that the video goes out of the theoretical window size. Aspect ratio get distorted too.

I first noticed this on 01/08/2024. I build today (01/15/2024) version and the problem remains.

I have an "old" binaries from 11/30/2023 and with that version I can resize down the game window with Wayland without problems, so the problem was introduced at some point after 11/30/2023.

### Expected Behavior

The game window can be resized down without image not appearing our of window border.

### Reproduction Steps

Launch a game from yuzu on a system running on a window on Wayland and try to resizing down the window.

### Log File

[yuzu_log-20240115.txt](https://github.com/yuzu-emu/yuzu/files/13942778/yuzu_log-20240115.txt)

### System Configuration

CPU: AMD Ryzen 9 5950X
GPU/Driver: AMD Radeon RX 6650 XT / AMDGPU
RAM: 32 GiB
OS: Debian 12

**Comment by liamwhite** [comment]
This was fixed in newer versions of radv, you might want to update.

**Comment by scastilloml** [comment]
Are you sure that this is a radv bug? I mean that it worked well with the same radv and yuzu-mainline on 11/30/2023.

**Comment by liamwhite** [comment]
Yes. I am currently using radv/mesa 23.1.6 on a wayland session and resizing both larger and smaller works fine.

**Comment by liamwhite** [comment]
Never mind, I had an environment override to use xwayland (the interface is broken on wayland due to factors out of our control) and this bug does appear.
