### ISSUE TITLE
GTX970 TOTK Black screen with 0fps

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [yuzu-emu/yuzu#12698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 4066 and any other versions

### Description of Issue

i got just 0fps and black screen when i start the game with any of the updates.
without updates it's just stuck on the loading screen.

i can't copy all of the log file because it's 100mb.
but i copied the main point of the problem.

### Expected Behavior

to be able to play the game.

### Reproduction Steps

1. Extract yuzu 4066
2. Launch TOTK with any of the updates
3. Game crashes citing this error

### Log File

[  85.215232] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:994: Device doesn't support extension VK_EXT_external_memory_host
[  85.215254] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:1056: Device doesn't support feature shaderFloat16
[  85.216541] Render.Vulkan <Warning> video_core\vulkan_common\vulkan_device.cpp:Device:537: NVIDIA Drivers >= 510 do not support MSAA image blits
[  85.216546] Render.Vulkan <Warning> video_core\vulkan_common\vulkan_device.cpp:Device:684: Pascal and older architectures have broken VK_KHR_push_descriptor
[  85.658616] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:158: Driver: NVIDIA 546.33.0.0
[  85.658623] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:159: Device: NVIDIA GeForce GTX 970
[  85.658624] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:160: Vulkan: 1.3.260
[  85.658631] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:161: Available VRAM: 3.12 GiB
[  85.852830] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:100: Auto-selecting the cubeb backend
[  85.899562] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:100: Auto-selecting the cubeb backend
[  86.093323] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.3.0) applied successfully
[  86.096319] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.3.0) applied successfully
[  86.096643] Frontend <Info> yuzu\main.cpp:BootGame:2033: Booting game: 0100F2C0115B6000 | The Legend of Zelda: Tears of the Kingdom (64-bit) | 1.1.1
[  86.131915] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:LoadVulkanPipelineCache:865: Loaded Vulkan driver pipeline cache: 
[  86.132869] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:LoadDiskResources:548: Total Pipeline Count: 1
[  86.132950] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:610: 0x0cf996422dda788f
[  86.443640] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:SerializeVulkanPipelineCache:808: Vulkan driver pipelines cached at: C:\Users\Dante\AppData\Roaming\yuzu\shader\0100f2c0115b6000\vulkan_pipelines.bin
[  87.474403] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  87.490563] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  87.507093] Service.AM <Warning> core\hle\service\am\am.cpp:SetRequestExitToLibraryAppletAtExecuteNextProgramEnabled:1117: (STUBBED) called
[  87.510843] Service.AM <Warning> core\hle\service\am\am.cpp:GetGpuErrorDetectedSystemEvent:2494: (STUBBED) called
[  87.524388] Service.AM <Warning> core\hle\service\am\am.cpp:AcquireForegroundRights:115: (STUBBED) called
[  87.525208] Service.AM <Warning> core\hle\service\am\am.cpp:SetFocusHandlingMode:510: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[  87.526182] Service.AM <Warning> core\hle\service\am\am.cpp:SetOutOfFocusSuspendingEnabled:529: (STUBBED) called enabled=false
[  87.530223] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  87.536664] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  87.539603] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  87.545370] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  87.545607] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  87.546163] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.3.0) applied successfully
[  90.537170] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.3.0) applied successfully
[  93.156624] Service.AM <Warning> core\hle\service\am\am.cpp:SetFocusHandlingMode:510: (STUBBED) called. unknown0=1, unknown1=0, unknown2=1
[  93.158680] Service.AM <Warning> core\hle\service\am\am.cpp:SetOutOfFocusSuspendingEnabled:529: (STUBBED) called enabled=false
[  93.159741] Service.AM <Warning> core\hle\service\am\am.cpp:SetRestartMessageEnabled:517: (STUBBED) called
[  93.159989] Service.AM <Warning> core\hle\service\am\am.cpp:SetOperationModeChangedNotification:481: (STUBBED) called flag=true
[  93.160395] Service.AM <Warning> core\hle\service\am\am.cpp:SetPerformanceModeChangedNotification:491: (STUBBED) called flag=true
[  93.215991] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  93.240377] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:427: Patching RomFS for title_id=0100F2C0115B6000, type=01
[  93.241538] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.3.0) applied successfully
[  94.683937] Loader <Info> core\file_sys\patch_manager.cpp:ApplyLayeredFS:417:     RomFS: LayeredFS patches applied successfully
[  94.843691] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.3.0) applied successfully
[  94.860231] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.3.0) applied successfully
[  94.899643] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:Initialize:154: (STUBBED) called
[  94.903891] Debug <Critical> core\hle\service\nvdrv\core\container.cpp:OpenSession:106: Preallocation created!
[  94.909541] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:SetAruid:211: (STUBBED) called, pid=0x51
[  94.911728] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:SetGraphicsFirmwareMemoryMarginEnabled:219: (STUBBED) called
[  94.964340] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetManagerDisplayService:571: (STUBBED) called
[  94.965635] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetSystemDisplayService:563: (STUBBED) called
[  94.966626] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetRelayService:555: (STUBBED) called
[  94.977842] Service.VI <Warning> core\hle\service\vi\vi.cpp:OpenDisplay:587: (STUBBED) called
[  94.980661] Service.AM <Warning> core\hle\service\am\am.cpp:CreateManagedDisplaySeparableLayer:600: (STUBBED) called
[  95.021420] Service.VI <Warning> core\hle\service\vi\vi.cpp:AdjustRefcount:113: (STUBBED) called id=1, addval=00000001, type=00000000
[  95.022820] Service.VI <Warning> core\hle\service\vi\vi.cpp:AdjustRefcount:113: (STUBBED) called id=1, addval=00000001, type=00000001
[  95.029246] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetNativeHandle:124: (STUBBED) called id=1, unknown=0000000F
[  95.126515] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  95.306503] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:AllocGPFIFOEx2:169: (STUBBED) called, num_entries=8000, flags=1, unk0=0, unk1=0, unk2=0, unk3=0
[  95.349461] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:AllocateObjectContext:185: (STUBBED) called, class_num=B197, flags=0
[  95.351223] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:SetErrorNotifier:154: (STUBBED) called, offset=0, size=1000, mem=10
[  95.351952] Service.NVDRV <Info> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:ChannelSetTimeout:315: called, timeout=0x266
[  95.354766] Service.NVDRV <Info> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:ChannelSetTimeslice:321: called, timeslice=0x400
[  95.408011] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  95.463405] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  95.544178] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  95.574906] Service.ACC <Warning> core\hle\service\acc\acc.cpp:InitializeApplicationInfoV2:879: (STUBBED) called
[  95.576372] Service.AM <Info> core\hle\service\am\am.cpp:PopLaunchParameter:2118: called, kind=00000002
[  95.582933] Service.AOC <Warning> core\hle\service\aoc\aoc_u.cpp:CheckAddOnContentMountStatus:312: (STUBBED) called
[  95.659788] Service.HID <Info> hid_core\frontend\emulated_controller.cpp:SetPollingMode:1271: Set polling mode 0, device_index=3
[  95.724806] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[  98.233127] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:226: (STUBBED) called
[ 102.535053] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write64 @ 0x0000000000000020 = 0x00000021500F1AF0
[ 102.535077] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write64 @ 0x0000000000000028 = 0x00000021500F1AF0
[ 102.600852] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011B0DFE5EE
[ 103.526945] Service.Audio <Info> audio_core\sink\cubeb_sink.cpp:CubebSinkStream:78: Opening cubeb stream ADSP_RenderStream-0 type 0 with: rate 48000 channels 2 (system channels 2) latency 480
[ 103.578515] Service.Audio <Info> audio_core\sink\cubeb_sink.cpp:CubebSinkStream:78: Opening cubeb stream ADSP_RenderStream-1 type 0 with: rate 48000 channels 2 (system channels 2) latency 480
[ 103.697326] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[ 103.804967] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[ 103.806320] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[ 103.806629] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[ 103.872963] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[ 103.873562] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[ 103.874107] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[ 104.666804] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x000000120EA3B180
[ 105.115050] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011D4319AEC
[ 105.120808] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011DF30C0C3
[ 105.125323] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011DD28DFF4
[ 105.128976] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011CE24B6EE
[ 105.129079] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x000000119D2AD5E9
[ 105.130151] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011E33B76F3
[ 105.131002] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011DE3C14C1
[ 105.147797] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011D63A3AF4
[ 105.153948] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011DD3925F4
[ 105.154824] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011E53710DF
[ 105.162546] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011D04E23E5
[ 105.165785] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011DF4CD0C3
[ 105.173573] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011D3598103
[ 105.173734] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011D328B5EE
[ 105.174527] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011D657B6AE
[ 105.176170] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x000000116F5BDEF9
[ 105.320776] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011E47E12CD
[ 105.330313] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x000000123011B181
[ 105.671086] Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:956: called.
[ 105.735031] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[ 105.745350] Service.AM <Warning> core\hle\service\am\am.cpp:SetOperationModeChangedNotification:481: (STUBBED) called flag=true
[ 105.745430] Service.AM <Warning> core\hle\service\am\am.cpp:SetPerformanceModeChangedNotification:491: (STUBBED) called flag=true
[ 105.747429] Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:956: called.
[ 105.779318] Debug <Critical> core\hle\service\filesystem\fsp_srv.cpp:operator ():982: Assertion Failed!
[ 105.787470] Service.FS <Warning> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataInfoReaderOnlyCacheStorage:1015: (STUBBED) called
[ 105.790344] Core <Warning> core\hle\service\hle_ipc.cpp:WriteBuffer:423: skip empty buffer write
[ 105.814843] Service.AM <Warning> core\hle\service\am\am.cpp:CreateCacheStorage:2409: (STUBBED) called with index=0, size=0x33b0000, journal_size=0x2c000
[ 105.816706] Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:956: called.
[ 105.834585] Service.FS <Warning> core\hle\service\filesystem\fsp_srv.cpp:Commit:494: (STUBBED) called
[ 105.840207] Service.FS <Warning> core\hle\service\filesystem\fsp_srv.cpp:Commit:494: (STUBBED) called
[ 105.840518] Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:956: called.
[ 105.842385] Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:956: called.
[ 106.404142] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:226: (STUBBED) called
[ 106.404971] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:226: (STUBBED) called
[ 110.311134] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[ 111.614933] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000001181A41E51
[ 111.625458] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011B08E4C44
[ 111.655478] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x000000116EB6C56C
[ 111.666300] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011B1CFD26B
[ 111.710940] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000001237D4820D
[ 111.731101] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000001193E63010
[ 111.770715] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000012248613D5
[ 111.796894] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x000000124460B751
[ 111.815815] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000001256040077
[ 111.818344] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011A9EDDDF4
[ 111.826253] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011FE485517
[ 111.891341] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x000000117CFEFD6E
[ 111.921680] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000001244733B5D
[ 112.422512] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000001266C9A412
[ 112.437036] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011F6686528
[ 112.475296] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000001246672DDF
[ 112.483096] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011891C9688
[ 112.489985] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000001194A46B3E
[ 112.492093] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000001226CDA2E5
[ 112.494057] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011D2445138
[ 112.539292] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[ 112.554756] Service.NFC <Info> core\hle\service\nfc\nfc_interface.cpp:Initialize:28: called
[ 112.584605] Service.HID <Info> hid_core\frontend\emulated_controller.cpp:SetPollingMode:1271: Set polling mode 2, device_index=1
[ 112.587119] Service.NFC <Info> core\hle\service\nfc\nfc_interface.cpp:AttachAvailabilityChangeEvent:135: called
[ 112.869014] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x00000011B4311F97
[ 113.859238] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000001213BFF8F8
[ 115.504314] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000038
[ 115.504327] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read32 @ 0x0000000000000040
[ 115.504334] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write8 @ 0xFFFFFFFFFFFFFFFF = 0x0000000000000000
[ 115.504341] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000038
[ 115.504409] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000000000000000
[ 115.504469] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000028
[ 115.504572] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504579] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read32 @ 0x0000000000000020
[ 115.504585] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write8 @ 0xFFFFFFFFFFFFFFFF = 0x0000000000000000
[ 115.504591] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504660] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000000000000000
[ 115.504719] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000008
[ 115.504820] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504825] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read32 @ 0x0000000000000020
[ 115.504827] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write8 @ 0xFFFFFFFFFFFFFFFF = 0x0000000000000000
[ 115.504828] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504829] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000000000000000
[ 115.504831] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000008
[ 115.504832] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504835] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read32 @ 0x0000000000000020
[ 115.504836] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write8 @ 0xFFFFFFFFFFFFFFFF = 0x0000000000000000
[ 115.504837] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504838] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000000000000000
[ 115.504840] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000008
[ 115.504841] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504842] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read32 @ 0x0000000000000020
[ 115.504843] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write8 @ 0xFFFFFFFFFFFFFFFF = 0x0000000000000000
[ 115.504844] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504845] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000000000000000
[ 115.504847] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000008
[ 115.504848] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504848] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read32 @ 0x0000000000000020
[ 115.504850] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write8 @ 0xFFFFFFFFFFFFFFFF = 0x0000000000000000
[ 115.504851] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504852] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000000000000000
[ 115.504853] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000008
[ 115.504855] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504857] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read32 @ 0x0000000000000020
[ 115.504858] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write8 @ 0xFFFFFFFFFFFFFFFF = 0x0000000000000000
[ 115.504859] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504860] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000000000000000
[ 115.504861] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000008
[ 115.504862] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504863] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read32 @ 0x0000000000000020
[ 115.504865] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write8 @ 0xFFFFFFFFFFFFFFFF = 0x0000000000000000
[ 115.504866] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504867] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000000000000000
[ 115.504868] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000008
[ 115.504869] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504870] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read32 @ 0x0000000000000020
[ 115.504872] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write8 @ 0xFFFFFFFFFFFFFFFF = 0x0000000000000000
[ 115.504873] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504874] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000000000000000
[ 115.504876] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000008
[ 115.504877] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504879] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read32 @ 0x0000000000000020
[ 115.504880] HW.Memory <Error> core\memory.cpp:operator ():766: Unmapped Write8 @ 0xFFFFFFFFFFFFFFFF = 0x0000000000000000
[ 115.504881] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504883] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read8 @ 0x0000000000000000
[ 115.504884] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000008
[ 115.504885] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read64 @ 0x0000000000000018
[ 115.504886] HW.Memory <Error> core\memory.cpp:operator ():742: Unmapped Read32 @ 0x0000000000000020

### System Configuration

CPU: AMD A10-7890K
GPU/Driver: GTX970 / Gameready 546.33
RAM: 16GB 1600MHZ CL9
OS: ReviOS Windows 10 Build 19041.vb_release.191206-1406

**Comment by liamwhite** [comment]
Your mods are incompatible and/or your update file is corrupt. The game works fine on even older GPUs

**Comment by goldenx86** [comment]
Get a better CPU, no FX based APU will be remotely decent with this workload.

**Comment by TheOneEyedGrimReaper** [comment]
> Get a better CPU, no FX based APU will be remotely decent with this workload.

are you sure this is a problem with the cpu maaan?
i had a unlocked rx460 before the gtx 970, and you know what, i was able to play totk with 27-30fps.

**Comment by TheOneEyedGrimReaper** [comment]
> Your mods are incompatible and/or your update file is corrupt. The game works fine on even older GPUs

i tried with/without mods too.
the problem is the same when i use any of the updates.
maybe this is related to that the gtx 970 doesn't have 4gb vram?

**Comment by liamwhite** [comment]
I have run TOTK 1.1.0 on a system running Linux and a GTX 780 (3GB of VRAM). It does work, and the update makes the game less demanding, not more.

Your log file shows a huge spew of memory errors, which means one of these things:
1. Incompatible mods used - this is the most likely issue
2. Corrupt update - reading garbage data from the base game or update file, you can easily verify this with the option to verify integrity in the tools menu
3. Actual memory hardware failure - seems unlikely

 This seems more like a support request than a bug report, because the hardware is definitely capable.

**Comment by TheOneEyedGrimReaper** [comment]
> I have run TOTK 1.1.0 on a system running Linux and a GTX 780 (3GB of VRAM). It does work, and the update makes the game less demanding, not more.
> 
> Your log file shows a huge spew of memory errors, which means one of these things:
> 
> 1. Incompatible mods used - this is the most likely issue
> 2. Corrupt update - reading garbage data from the base game or update file, you can easily verify this with the option to verify integrity in the tools menu
> 3. Actual memory hardware failure - seems unlikely
> 
> This seems more like a support request than a bug report, because the hardware is definitely capable.

does xci with merged update gonna work?
if it is, then i gonna get one and try it.

**Comment by TheOneEyedGrimReaper** [comment]
> We don't recommend using modified game files. Please reference the Quickstart Guide in order to dump your games, from your Switch for use with yuzu. https://yuzu-emu.org/help/quickstart/

hoh, nice answer.
I figured it out thanks to @liamwhite 
my nsp was of the fitgirl repack that was the problem, i got an xci then voila, i can play totk again.

it would be nice if the devs make a guide for the log error codes, it would be much easier to figure out what is the real problem.

**Comment by goldenx86** [comment]
That CPU is so weak, driver overhead will decide the performance.
I'm not joking or being elitist, those A10 count as dual core FX in practice, and are known to struggle with too high scheduling demands.
