### ISSUE TITLE
[Android] Skullgirls doesn't work after updating the game to 1.0.7

### ISSUE THREAD

**Issue by TomatoJuicee** [yuzu-emu/yuzu#12697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu version 193

### Description of Issue

After updating skullgirls to 1.0.7 the game will be stuck on yuzu loading screen, the exit emulation option will be all black and clicking on it will make the shutting down to be also stuck forever
![SkullUpdate1](https://github.com/yuzu-emu/yuzu/assets/154700588/4a1edd99-8a89-4c81-bd22-73aa80d78545)
![Skullupdated2](https://github.com/yuzu-emu/yuzu/assets/154700588/e17118af-a12b-414c-bfff-d87c761a50ef)
![Skullupdated3](https://github.com/yuzu-emu/yuzu/assets/154700588/569a17e2-971a-4677-bd8a-c141497abc64)

### Expected Behavior

The game works fine on base version as you can see on these pics, also the updated game by yanu does works on skyline so the update isn't corrupted but it useless since skyline doesn't support dlcs so without yuzu using the updated nsp isn't worth it
![Skull1 0](https://github.com/yuzu-emu/yuzu/assets/154700588/34d3b94b-3768-40d1-9c06-5dda1359278b)
![Skull1 02](https://github.com/yuzu-emu/yuzu/assets/154700588/d9f0f1c0-c431-4dfa-9379-47bd2e5568b5)

### Reproduction Steps

Just update skullgirls to 1.0.7

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13968738/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 680
GPU/Driver: Adreno 610/using both turnip revision 15 and 615.65
RAM:4
OS:Android

**Comment by chugalaefoo** [comment]
I have the same issue. Except I'm on steamdeck.
