### ISSUE TITLE
[Android] Auto battle not working in Pokemon Scarlet and Violet

### ISSUE THREAD

**Issue by jasmohan-narula** [yuzu-emu/yuzu#12692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu Android v195
Yuzu Android v196
Yuzu Android v197

### Description of Issue

Whenever I do auto battle in either Pokemon Scarlet or Pokemon Violet, the game crashes after the Pokemon faints and my Pokemon gains experience. In the logs, sometimes I saw HW.Memory error and sometimes I saw the following error in logs-
Debug <Critical> common/host_memory.cpp:operator():697: Assertion Failed!

### Expected Behavior

On Windows, auto battles complete successfully, and the game does not crash

### Reproduction Steps

Go in the overworld, do auto battle with your Pokemon
Video for proof
https://github.com/yuzu-emu/yuzu/assets/11637422/c1b6d6b2-aefa-4ae4-9ce1-e3996836f54f

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13963692/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13963746/yuzu_log.txt.old.txt)

### System Configuration

CPU: Snapdragon 888
Phone: Realme GT 2
GPU/Driver: Mesa Turnip 15
RAM: 12GB
OS: Android 13

**Comment by fullmetalik** [comment]
Is there any solution?

**Comment by jasmohan-narula** [comment]
Looks like it's fixed in V206

**Comment by jasmohan-narula** [comment]
I can confirm that this issue is fixed. Checked on v210

**Comment by fullmetalik** [comment]
back again the crash on version 222 :S

**Comment by jasmohan-narula** [comment]
@fullmetalik Yes. After auto battling FPS drops to 0 and crashes.

Build: Android 222

**Comment by fullmetalik** [comment]
Still the same in build 224 @jasmohan-narula
