### ISSUE TITLE
Add controller mapping

### ISSUE THREAD

**Issue by Khawlamonib** [yuzu-emu/yuzu#12704]
### Issue

Every controller I plug with emulator the patterns get messed the b works like A, the Y works like  X ,select looks like a start. so if you please add controller mapping I would like to map my own controller and thank you.Ohh and  f*** eggnes  for stealing your code and sell it

**Comment by Khawlamonib** [comment]
Please add controller mapping I would like to map my own buttons and controls and thank you for reading my comment

**Comment by german77** [comment]
duplicate #11124
