### ISSUE TITLE
[Android] Need for speed hot pursuit 2010 showing black screen on boot

### ISSUE THREAD

**Issue by Alphonsokurukuchu** [yuzu-emu/yuzu#12706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android V196 and older build v192

### Description of Issue

Game just shows black screen with 30fps when I open fhe game. I'm not sure when it started but I have this since v192. It used to work perfectly fine in older builds like v172. It works on adreno 7xx

### Expected Behavior

To show the logos and go to main menu on booting 

### Reproduction Steps

Just use v196 and boot the game 

### Log File

[yuzu_log-1.txt](https://github.com/yuzu-emu/yuzu/files/13980058/yuzu_log-1.txt) NCE
[yuzu_log-1.txt](https://github.com/yuzu-emu/yuzu/files/13980062/yuzu_log-1.txt) JIT

### System Configuration

CPU: Snapdragon 865+
GPU/Driver: Adreno 650
RAM: 6GB
OS: Android 13, one ui 5.1.1

**Comment by Alphonsokurukuchu** [comment]
I don't know anymore, it just works randomly on latest version with latest turnip again

**Comment by german77** [comment]
Your issue is probably related due to low ram. Yuzu needs at least 8GB to be stable
