### ISSUE TITLE
Detected trojan on C:\users\myusername\appdata\local\yuzu-windows-msvc\lz4.dll

### ISSUE THREAD

**Issue by Engjell420** [yuzu-emu/yuzu#12714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline Build - 5aab1b86c

### Description of Issue

After updating to the latest version my antivirus immediately reported the file as a trojan virus and quarantined it, i then deleted the whole emulator just to be safe, also the leftover files in appdata.
It could be a false positive though, but i doubt it since i haven't had much problems with false positives earlier (i have been using this antivirus for 2 years, including another device).

### Expected Behavior

yuzu usually opens up without any antivirus issue in my pc.

### Reproduction Steps

I keep my 360Total Security antivirus on all the time even if apps ask me to turn it off some times, just in case, and this time when updating yuzu the antivirus detected a trojan in that exact file.

### Log File

I have deleted the emulator sorry. And there is no log file since it's not a crash, i just closed it before completing the update.

### System Configuration

CPU: AMD RYZEN 5 5600H with Radeon Graphics 3.30 GHz
GPU/Driver: Nvidia GeForce RTX3600 Laptop GPU
RAM: 16GB
OS: Windows 11

**Comment by anpilley** [comment]
![image](https://github.com/yuzu-emu/yuzu/assets/12467241/71662cae-c424-4a32-af8b-25d74152b8f4)

Your Antivirus software seems to not be reflecting the general consensus.

**Comment by liamwhite** [comment]
False positive

**Comment by Weab-chan** [comment]
I know it's closed.. but I doubt anyone in their right mind would use _360Total Security antivirus_

**Comment by Engjell420** [comment]
> I know it's closed.. but I doubt anyone in their right mind would use _360Total Security antivirus_
Can you at least recommend a better one for me that is free to use and does the job correctly, no offense please.

**Comment by Engjell420** [comment]
> ![image](https://private-user-images.githubusercontent.com/12467241/298203602-71662cae-c424-4a32-af8b-25d74152b8f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MDIwNTksIm5iZiI6MTcwNTcwMTc1OSwicGF0aCI6Ii8xMjQ2NzI0MS8yOTgyMDM2MDItNzE2NjJjYWUtYzQyNC00YTMyLWFmOGItMjVkNzQxNTJiOGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDIyMDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NDZkMWExOTk1ODE0ZGE4MmU3ZTM4MjdjNTNmMDc0ZmNjYmMwY2QyYjAwNDg4N2ZjYTc2YzkzMjgyMDlhOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bkdx-RCUZ6xk8u_E5KUJwVqYAcVbzVxUIpGGo2p5DVw)
> 
> Your Antivirus software seems to not be reflecting the general consensus.

Much appreciated brother!

**Comment by Weab-chan** [comment]
> > I know it's closed.. but I doubt anyone in their right mind would use _360Total Security antivirus_
> > Can you at least recommend a better one for me that is free to use has no unnecessary bloatware and does the job correctly, no offense please.

I'd love to compare any of these with your antivirus but they stopped testing it back in 2017...

https://www.av-test.org/en/antivirus/home-windows/windows-11/october-2023/

![image](https://github.com/yuzu-emu/yuzu/assets/93067085/ca484f90-cd7e-4653-912f-4923c7b2bdb1)

**Comment by liamwhite** [comment]
Off topic discussion. When on Windows, the recommended choice is always Microsoft Defender.
