### ISSUE TITLE
Asus ROG ally - controller not working 

### ISSUE THREAD

**Issue by nikosgevre** [yuzu-emu/yuzu#12710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1686

### Description of Issue

controller of Asus rog ally z1 extreme is not recognised or working. in controller configure I cannot manually configure the buttons and even when set as Xbox 360 controller, the keys are not registering. the controller is not recognised 

### Expected Behavior

the Asus rog ally handheld controller should be recognized as a xbox 360 controller 

### Reproduction Steps

i just bought the z1 extreme. did all the windows and bios updates. steam is working fine while playing, xbox app as well. donwloaded yuzu to check it out but controller is not recognised 

### Log File

[   0.302974] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.303006] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.345078] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.387934] Frontend <Info> yuzu\main.cpp:GMainWindow:379: yuzu Version: yuzu 1686
[   0.387972] Frontend <Info> yuzu\main.cpp:LogRuntimes:255: MSVC Compiler: 1937 Runtime: 14.36.32532.0
[   0.387974] Frontend <Info> yuzu\main.cpp:LogRuntimes:264: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.387976] Frontend <Info> yuzu\main.cpp:GMainWindow:395: Host CPU: AMD Ryzen Z1 Extreme                            | AVX512 | FMA
[   0.387984] Frontend <Info> yuzu\main.cpp:GMainWindow:397: Host CPU Cores: 8
[   0.387984] Frontend <Info> yuzu\main.cpp:GMainWindow:400: Host CPU Threads: 16
[   0.388161] Frontend <Info> yuzu\main.cpp:GMainWindow:401: Host OS: Windows 11 Version 22H2 (Build 22621.1928)
[   0.388183] Frontend <Info> yuzu\main.cpp:GMainWindow:403: Host RAM: 11.70 GiB
[   0.388184] Frontend <Info> yuzu\main.cpp:GMainWindow:404: Host Swap: 3.99 GiB
[   0.388272] Frontend <Info> yuzu\main.cpp:GMainWindow:409: Host Timer Resolution: 0.5000 ms
[   0.412415] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'SystemVersion' (0x0100000000000809).
[   0.412427] Common.Filesystem <Warning> core\file_sys\system_archive\system_version.cpp:SystemVersion:17: called - Using hardcoded firmware version 'NintendoSDK Firmware for NX 12.1.0-1.0'
[   0.412450] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   0.412463] Frontend <Info> yuzu\main.cpp:SetFirmwareVersion:4862: Installed firmware: No firmware available
[   0.460299] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.0.0) applied successfully
[   0.469841] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.0.0) applied successfully
[  46.723087] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:100: Auto-selecting the cubeb backend
[  46.788125] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:100: Auto-selecting the cubeb backend
[  53.654981] Config <Info> frontend_common\config.cpp:WriteToIni:74: Writing Global configuration to: C:\Users\nikos\AppData\Roaming\yuzu\config\qt-config.ini
[  53.657211] Config <Info> frontend_common\config.cpp:WriteToIni:74: Writing Global configuration to: C:\Users\nikos\AppData\Roaming\yuzu\config\qt-config.ini
[  53.657211] Config <Info> frontend_common\config.cpp:WriteToIni:74: Writing Global configuration to: C:\Users\nikos\AppData\Roaming\yuzu\config\qt-config.ini

### System Configuration

CPU: amd ryzen z1 extreme 
GPU/Driver: integrated amd radeon graphics 
RAM: 16gb
OS: Windows 11

**Comment by nikosgevre** [comment]
after some more research regarding the rog ally specifically and not the yuzu software i found out and confirmed that in order for the gamepad to be recognized as a controller in yuzu and other emulators, you need to run the software (emulator) from the asus armour crate game library. otherwise it recognizes it as a keyboard and there are a lot of complications. just make sure to run the emualtor from the armour crate game library

**Comment by K11MCH1** [comment]
> after some more research regarding the rog ally specifically and not the yuzu software i found out and confirmed that in order for the gamepad to be recognized as a controller in yuzu and other emulators, you need to run the software (emulator) from the asus armour crate game library. otherwise it recognizes it as a keyboard and there are a lot of complications. just make sure to run the emualtor from the armour crate game library

As an Ally owner myself, I can confirm that this is not necessary. I dont use AC at all, except for the command center panel.

You have to make sure you are in Gamepad mode in the CMD center and not Auto or Desktop.
