### ISSUE TITLE
mii editor is not working

### ISSUE THREAD

**Issue by miku1881** [yuzu-emu/yuzu#12718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1687

### Description of Issue

mii editor does not start 

### Expected Behavior

I copied the mii in miitopia and tried to check it in the editor and it freese  I tried to get them to respond with a discord, but the bot deemed me a pirate and deleted my log file.　On top of that, I got a timeout and a warning.　

### Reproduction Steps

[MiiDatabase.zip](https://github.com/yuzu-emu/yuzu/files/13996725/MiiDatabase.zip)

If you start mii editor with this data, it will freeze.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13996715/yuzu_log.txt)

### System Configuration

CPU:　Intel core5 13400F
GPU/Driver: nvidia geforce rtx 3060 
RAM: 32gb
OS: windows 11

**Comment by german77** [comment]
Seems like you didn't understand the memo. We don't provide support to pirates. Please get all the files from your console.
