### ISSUE TITLE
Yuzu Hollow Knight constant crashing after booting once on a POWERFUL Mali chipset 

### ISSUE THREAD

**Issue by FaRA-07** [yuzu-emu/yuzu#12726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

GitHub build ver 199/ e4f0886

### Description of Issue

Hollow Knight crashes after playing for less then a minute and then it doesn't even boot again, even after clearing shaders, only boots again after a while or if I clear data yuzu.

https://github.com/yuzu-emu/yuzu/assets/133346618/f1e764e2-0f87-4b15-a710-3b92e8c010a1

### Expected Behavior

As you cann see in the video, it will go in-game, then maybe to the playable levels, their crashes pretty soon, and if tried to boot again, crashes without on booting.

https://github.com/yuzu-emu/yuzu/assets/133346618/f819dfd9-17d8-4be2-9bb9-28bd57df15b0

### Reproduction Steps

Install fresh yuzu build from GitHub(currently 199, still had this since issue 137) and boot Hollow Knight, if it doesn't boot, clear data or reinstall yuzu and try again on Dimensity Mali 8100 SoC.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13999142/yuzu_log.txt.old.txt)

### System Configuration

CPU: Dimensity 8100
GPU/Driver: Mali G610 MC6/r32p1
RAM:8
OS:MIUI 14.0.6.0[TLOINXM]

**Comment by pacoa-kdbg** [comment]
Before deleting yuzu data.
Can you try to delete Hollow Knight save and try again

**Comment by FaRA-07** [comment]
I did try that already, I tried importing saves, deleting the existing save files, and even redumped the game, it still shows the same behaviour :⁠-⁠(

**Comment by FaRA-07** [comment]
I tried the latest yuzu version that is 248 today and now the previous HK crashing issued have been resolved!
