### ISSUE TITLE
[Android] All games crashing on v200

### ISSUE THREAD

**Issue by TomatoJuicee** [yuzu-emu/yuzu#12729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu android version 200

### Description of Issue

All my games crash on update v200 after the loading screen and building shaders
![v200crash](https://github.com/yuzu-emu/yuzu/assets/154700588/4824529f-e71f-4188-bcf9-6330b77f2f8a)
![Crash](https://github.com/yuzu-emu/yuzu/assets/154700588/829358a0-7904-4d83-9151-4787d60dd19a)

### Expected Behavior

Games booting and working just fine on v199
![v199](https://github.com/yuzu-emu/yuzu/assets/154700588/03827ab7-95d5-423d-8dd6-071990286723)
![v1992](https://github.com/yuzu-emu/yuzu/assets/154700588/78c1e925-1fb8-4287-911a-f4913312e9cc)

### Reproduction Steps

Update to v200 and try booting games

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14000637/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 680
GPU/Driver: Adreno 610/Driver 690
RAM: 4
OS: Android 13

**Comment by TomatoJuicee** [comment]
After doing my report i tried with turnip Rev 15 and the crash still happens![yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14000661/yuzu_log.txt)

**Comment by xZeanx** [comment]
Me too with 
Sharp R3
6/855

**Comment by The1Renaissance** [comment]
I have the same problem
OnePlus 9RT (A14, 12 ram / Snap 888)
Turnip 15

**Comment by Kelebek1** [comment]
Dump your firmware for now.

**Comment by liamwhite** [comment]
Not able to reproduce this on Adreno 618 - Android 200 (with/without firmware)
![1](https://github.com/yuzu-emu/yuzu/assets/9658600/5f8c4fa1-6857-491f-a43b-4bc6471c289e)

By any chance, do you have a controller connected?

**Comment by TomatoJuicee** [comment]
> Not able to reproduce this on Adreno 618 - Android 200 (with/without firmware)
> ![1](https://github.com/yuzu-emu/yuzu/assets/9658600/5f8c4fa1-6857-491f-a43b-4bc6471c289e)
> 
> By any chance, do you have a controller connected?

Nope i was playing with touchscreen button, i only remove them for the screenshot

**Comment by TomatoJuicee** [comment]
> I think I've fixed this now, so should be fixed in future builds.

Thank you guys❤️

**Comment by german77** [comment]
Just out of curiosity can any of you provide a screenshot of the output of this homebrew?
[templeoftime.zip](https://github.com/yuzu-emu/yuzu/files/14002371/templeoftime.zip)

**Comment by TomatoJuicee** [comment]
Update for reference: V201 still crashing all my games![yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14002585/yuzu_log.txt)

**Comment by solracnauj1990** [comment]
Same to me: with v198 and earlier there was no problem but with v200 and v201 all the games crash.
Device: Xiaomi Redmi Note 10 Pro

**Comment by TomatoJuicee** [comment]
Update for reference: V201 still crashing all my games![yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14002585/yuzu_log.txt)

 Update on v201: After doing a clean install every game now works, so if you have problems too try a clean install

**Comment by solracnauj1990** [comment]
> Update for reference: V201 still crashing all my games![yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14002585/yuzu_log.txt)
> 
> Update on v201: After doing a clean install every game now works, so if you have problems too try a clean install

If a clean install means to uninstall and install the app, I tried it and it didn't work. But what is exactly a clean install?

**Comment by TomatoJuicee** [comment]
> > Update for reference: V201 still crashing all my games![yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14002585/yuzu_log.txt)
> > 
> > Update on v201: After doing a clean install every game now works, so if you have problems too try a clean install
> 
> If a clean install means to uninstall and install the app, I tried it and it didn't work. But what is exactly a clean install?

I made a backup(yuzu files folder) and uninstalled the app, installed 201 alone and my games works on it now, then i moved my files folder again so i can use my saves/shaders and dlc, and still working

**Comment by solracnauj1990** [comment]
Oh thank you so much it worked!! ❤️

**Comment by TomatoJuicee** [comment]
> Oh thank you so much it worked!! ❤️

Shout out to yuzu devs for fixing and miku for teaching me this workaround!

**Comment by evil-trainer** [comment]
> Just out of curiosity can any of you provide a screenshot of the output of this homebrew? Use an older build if it crashes on v200 [templeoftime.zip](https://github.com/yuzu-emu/yuzu/files/14002371/templeoftime.zip)

![Screenshot_2024-01-21-23-59-33-103_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/149848175/9f2351a5-3d6f-48e3-bc6f-117bbc12f6ea)
This?

**Comment by german77** [comment]
Ty seems like argentina is missing
