### ISSUE TITLE
Splatoon 3 | The Shoal doesn't work | Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called; Service.Friend <Warning> core\hle\service\friend\friend.cpp:GetPlayHistoryRegistrationKey:176: (STUBBED) called

### ISSUE THREAD

**Issue by ManiaSonicRUS** [yuzu-emu/yuzu#12732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 4076

### Description of Issue

Not possible to start a match using The Shoal. "A communication error has occurred." happens when trying to do that.
No differences between LDN and LAN from the testing experience. 

### Expected Behavior

I wish it would work like Splatoon 2 does.

### Reproduction Steps

Try to start a match using The Shoal.

### Log File

LDN Server: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14001474/yuzu_log.txt)
LDN Client: [yuzu_log (2).txt](https://github.com/yuzu-emu/yuzu/files/14001476/yuzu_log.2.txt)
LAN Server: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14001478/yuzu_log.txt)
LAN Client: [yuzu_log (3).txt](https://github.com/yuzu-emu/yuzu/files/14001481/yuzu_log.3.txt)

### System Configuration

Vulkan
CPU: i5-12400F
GPU/Driver: GTX 1650 SUPER, 546.65 
RAM: 2x16GB DDR4 3200
OS: Windows 11 Pro 21H2 (22000.2538)

**Comment by FearlessTobi** [comment]
https://github.com/yuzu-emu/yuzu/issues/11141
