### ISSUE TITLE
Paper Mario The Origami King: crash when opening Sea Chart

### ISSUE THREAD

**Issue by ilonachan** [yuzu-emu/yuzu#12731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 4075 / Mainline 1688

### Description of Issue

After unlocking the Marino and Sea Chart, entering the Great Sea opens a prompt forcing me to open the sea chart for the first time.
![image](https://github.com/yuzu-emu/yuzu/assets/16608533/f758a746-c539-4403-96dd-d5c9a4af52cb)

Yuzu crashes when I do that. The first time it managed to draw the chart before crashing, on subsequent restarts only the red boat marker is drawn.
![image](https://github.com/yuzu-emu/yuzu/assets/16608533/f91d8f12-378a-41a7-8af6-6cba14aa98e9)

EDIT: I managed to use Ryujinx to play past the cutscene and un-softlock the game, and I've confirmed that the problem occurs anytime the sea chart is opened at all.

### Expected Behavior

The map should open, and the game shouldn't crash.

### Reproduction Steps

1. ~~Play the game normally, up to where you meet Captain T. Ode (in the desert, then at the museum)~~
2. ~~Go to the docks, watch the Marino cutscene~~
3. Enter the Great Sea
4. ~~The first-time Sea Chart prompt appears, no action other than opening it is possible.~~ Open the Sea Chart
5. Yuzu crashes.

This happens any time the map is opened, so reproducing the first opening cutscene doesn't seem necessary.

In case this is somehow save-specific, here is mine. The game autosaved after entering the Great Sea, meaning this savefile starts from step 4 and is therefore softlocked.
[save.zip](https://github.com/yuzu-emu/yuzu/files/14000740/save.zip)
And in case it helps, here is the same save advanced past the softlock.
[save_unstuck.zip](https://github.com/yuzu-emu/yuzu/files/14000938/save_unstuck.zip)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14000720/yuzu_log.txt)

Note that this log contains no messages from the moment of the crash.

The error message displayed in the console during the crash is consistently "corrupted size vs. prev_size", though exactly one time it was "Unhandled SIGSEGV at rip 0x000055ff82b656f0" instead.

### System Configuration

CPU: AMD Ryzen 7 4700G (with builtin Radeon Graphics)
GPU/Driver: NVIDIA RTX 2060 Super, proprietary driver
RAM: 15.00 GiB (I thought it was 16 GiB but Yuzu logs claim it's just 15)
OS: Manjaro Linux

**Comment by Squall-Leonhart** [comment]
log cuts off early, theres an option to force it to run off-thread that should get the whole log file attached to the action builds relating to this PR https://github.com/yuzu-emu/yuzu/pull/12542, please try it and post the created log.

**Comment by ilonachan** [comment]
You mean, I compile that PR from source and run it with that option? I've _somehow_ managed to do that now, and here's the log.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14050006/yuzu_log.txt)

I'm not sure it's gonna be very useful though, because this time the crash didn't happen! EA4084 and Mainline 1692 also work fine, so I assume this issue got fixed quietly as a side effect of something else? I guess I could try rebasing the sync logging on EA4075 (can't see which commit that was tho) to specifically see what the issue _was_, but since it seems to be fixed anyway I'll just close the issue for now. Thanks!
