### ISSUE TITLE
SNACK WORLD: THE DUNGEON CRAWL fails to launch after recent update

### ISSUE THREAD

**Issue by BikeNom** [yuzu-emu/yuzu#12737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1689 / EA 4078

### Description of Issue

After a recent update to Yuzu, SNACK WORLD: THE DUNGEON CRAWL -- GOLD no longer launches. It was working before the update to mainline 1688. Something in the most recent update broke this game.

It stays stuck on Launching...

I have attempted turning off all optimizations, etc in case it was one of those features.

I am using Linux flatpak, however the issue also affects my Windows version.

### Expected Behavior

Launches as it did on 1688

### Reproduction Steps

Update to mainline 1689 and launch the game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14003518/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5900X
GPU/Driver: Radeon FX6700 XT
RAM: 64GB
OS: Linux (6.6.10-1) also Windows 10

**Comment by Kelebek1** [comment]
Can you put `Service.Time:Trace` in the log filter under Options -> Debug and then post another log.

**Comment by BikeNom** [comment]
Assuming you meant the global log filter, I have done so and attached it.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14003680/yuzu_log.txt)

**Comment by Kelebek1** [comment]
> Assuming you meant the global log filter, I have done so and attached it. [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14003680/yuzu_log.txt) The log looks very similar, perhaps I did it wrong?

No you did it right, we're looking at it.

**Comment by Kelebek1** [comment]
Ok I think I've found the issue and it should be fixed in the next build.

**Comment by BikeNom** [comment]
Can confirm, it is indeed fixed. Great work.
