### ISSUE TITLE
Super Mario 3D All-Stars crashes when starting one of the games

### ISSUE THREAD

**Issue by Jim-dll** [yuzu-emu/yuzu#12748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1690

### Description of Issue

When one of the Super Mario 3D All-Stars game modes is launched, it crashes instantly.

### Expected Behavior

The game launches normally. The game does not crash on Ryujinx.

### Reproduction Steps

Just launch one of the game modes (Mario 64, Mario Sunshine or Mario Galaxy)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14011962/yuzu_log.txt)

### System Configuration

CPU: Intel Pentium Gold 8505
GPU/Driver: Intel UHD Graphics / 31.0.101.5085
RAM: 8GB 3200 Mhz
OS: Windows 11 23H2 (Build 10.0.22631.3007)

**Comment by liamwhite** [comment]
Cannot confirm, all 3 games are working here. Perhaps a GPU driver issue?

Please upload a crash dump file.

**Comment by Jim-dll** [comment]
[1a18d824-e4d2-494d-a687-1af40acf49dc.dmp](https://github.com/yuzu-emu/yuzu/files/14013673/1a18d824-e4d2-494d-a687-1af40acf49dc.dmp)

**Comment by liamwhite** [comment]
Try using hardware video decoding instead of software decoding. Crash is from video decoder...

**Comment by Jim-dll** [comment]
I tested with CPU video decoding and it works even though the game is slow.

**Comment by burgersc12** [comment]
But this happened to me. I disabled MangoHud and it works again :)
