### ISSUE TITLE
[Android] yuzu 200: Problems with custom RTC

### ISSUE THREAD

**Issue by Eror840** [yuzu-emu/yuzu#12743]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Affected Build(s)

Yuzu 200:201:202:203

### Description of Issue

Starting from version 200 of the Yuzu program and higher, a problem appeared related to the display of the date in the game Animal crossing new horizen.
The date in the game jumps forward a week. Changing RTC does not help, I tried changing RTC in global settings and in game settings separately.

### Expected Behavior

After installing custom RTC, RTC does not match.

### Reproduction Steps

проблема возникла после обновления приложения до 200 версии и сохроняется в последующих выпусках. 
Чистая установка, изменение пользовательского RTC не дает результатов.
RTC в Animal crossing  быстрее от RTC в системе телефона. 
Время в игре нас нет идти быстрее.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14006257/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 870
GPU/Driver: adreno 650
RAM: 8
OS: android 12

**Comment by dhirennjaypal** [comment]
Even without using custom RTC, It jumps weeks ahead than phone's date.

**Comment by Eror840** [comment]
there have been some changes.
It is possible to update to newer versions 204+.
After rebooting the smartphone, the time in animal crossing new horizon is synchronized with the system time. after leaving the game and restarting the game, time begins to run forward; the longer the break in the game, the more time runs forward.

**Comment by german77** [comment]
Custom RTC is effectively non functional at the moment on android. I'm waiting on #12499 to be merged to fix this issue. Clocks are sync on game boot however I don't expect time drifting by more than a few minutes after a few hours of continuous game play. Can you put numbers on your issue. By how much time drifts in a period of 5/15/30 minutes?

**Comment by Eror840** [comment]
It's different every time.
I only play Animal Crossing New Horizon.
I came in in the morning at 8.30, after rebooting the phone the time was synchronized.
The second time I entered the game at 10.00, the consumption was for 2 hours in the game where it was 12.00.
The third time I entered at 13.30, the game was already 16.00.
I entered the game for the fourth time at 19.00, the game was 6.30 in the morning on January 24th.

If this can help, I can observe it during the day tomorrow and post a table for the time the game was launched, the period of absence from the game and some kind of movement.

**Comment by german77** [comment]
Just noticed that my phone says February 24th. Which is way off. I will try to find the source of this issue.

**Comment by german77** [comment]
We believe we found the source of the problem. Please test when v208 is out. I will try to see if custom rtc fix can be added as well. But there shouldn't be any more animalities with time.

**Comment by Eror840** [comment]
Monitoring time discrepancies at the time the game starts.

Emulator version 207

1. Game launch time 8.30
game time 8.30
difference 0 minutes
2. Game launch time 11.40
Game time 14.50
Difference 3 hours 10 minutes
3. Game launch time 19.46
Game time 04/07/25 January.
Time difference 10 hours 14 minutes

The time when the game is not running is somehow connected, the discrepancy in time coincides with the system time and when the game is not running. If you don't reboot your smartphone, this will gradually increase every time.

ok, I'll take a look in the next update, thank you very much.

**Comment by german77** [comment]
@dhirennjaypal @Eror840 v208 is out. Please test this issue is now completely fixed.

**Comment by Eror840** [comment]
yes, I just checked version 208 of the emulator.
rts works correctly and matches the system time.
thank you very much!
