### ISSUE TITLE
[ANDROID] Allow user to fully disable log

### ISSUE THREAD

**Issue by ikhoeyZX** [yuzu-emu/yuzu#12745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

we know log are useful for find bug in game but when consider some games are playable log are no need, in some case log cause some device bottle neck (due storage write and sometimes write more than 3MB size) also it's not good for long term usage (tearing solid storage)

### Why would this feature be useful?

maybe increase little bit performance and reduce storage I/O writes

**Comment by t895** [comment]
This will not improve performance and also not affect the long-term lifespan of your internal storage
