### ISSUE TITLE
Can not import DLC or UPDATE

### ISSUE THREAD

**Issue by huangyebiaoke** [yuzu-emu/yuzu#12740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Daily 200~203 version

### Description of Issue

yuzu android 200(not sure)~203 verison, can not import DLC or UPDATE, but older version can (192 and older), not sure if new features introduced the bug.
![9991e17ef22322d0585d0d9b39dc8b84](https://github.com/yuzu-emu/yuzu/assets/26546591/3a52aa38-e9ba-4d75-b05e-8774e2c4a75a)

### Expected Behavior

![ccc0dd55f5f694e0bbd8506e9cadc373](https://github.com/yuzu-emu/yuzu/assets/26546591/29736239-9d32-4b23-b688-22190dcde405)
 older version can import

### Reproduction Steps

update yuzu android version to 200(not sure)~203 verison, import new dlc or update? import error.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14004280/yuzu_log.txt.old.txt)

### System Configuration

CPU: 8gen3
GPU/Driver: Mesa Turnip R16 testv3
RAM: 12GB
OS: Flyme 10.5.0.0A

**Comment by TomatoJuicee** [comment]
I'm using v203 and i can import all my dlcs just fine![Yuzu dlc.jpg](https://github.com/yuzu-emu/yuzu/assets/154700588/462e8d4e-ef49-4b7c-b775-b16f4c99a7c5)

More like a phone issue, must be the lack of path perms, after dump them in wich folder you put the dlcs and updates?

**Comment by huangyebiaoke** [comment]
> I'm using v203 and i can import all my dlcs just fine![Yuzu dlc.jpg](https://private-user-images.githubusercontent.com/154700588/298446691-462e8d4e-ef49-4b7c-b775-b16f4c99a7c5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTUxMDUsIm5iZiI6MTcwNTg5NDgwNSwicGF0aCI6Ii8xNTQ3MDA1ODgvMjk4NDQ2NjkxLTQ2MmU4ZDRlLWVmNDktNGI3Yy1iNzc1LWIxNmY0Yzk5YTdjNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwMzQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmMzYjFhNzM2M2Q3YjVhOGNlMjcyNzdlMzk1YjIwMTVlMDhjMDk0NmMxYzM1OTFjMzI0ZTkxZDk2YzQ4YjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g6SD4IZvJfQFfM0YJpOEj6w8Iv5l7_FHZ1TopRdJc9k)
> 
> More like a phone issue, must be the lack of path perms, after dump them in wich folder you put the dlcs and updates? Oh it says something about your prod.keys also, you could try redump them and installing on yuzu again and see if it works? Can't help much since i can't understand chinese/mandarin

Thank you for your suggestion, First time, I suspected that the path permission is incorrect, so I put the UPDATE in DOWNLOAD/YUZU folder. However, It's still dont work. And my key version is 17.0.0. It's so weird, I've never seen it before. SO, I try rollback install the 193 daily version and reinstall the UPDATE, finally it's work😂

**Comment by TomatoJuicee** [comment]
> > I'm using v203 and i can import all my dlcs just fine![Yuzu dlc.jpg](https://private-user-images.githubusercontent.com/154700588/298446691-462e8d4e-ef49-4b7c-b775-b16f4c99a7c5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTUxMDUsIm5iZiI6MTcwNTg5NDgwNSwicGF0aCI6Ii8xNTQ3MDA1ODgvMjk4NDQ2NjkxLTQ2MmU4ZDRlLWVmNDktNGI3Yy1iNzc1LWIxNmY0Yzk5YTdjNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwMzQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmMzYjFhNzM2M2Q3YjVhOGNlMjcyNzdlMzk1YjIwMTVlMDhjMDk0NmMxYzM1OTFjMzI0ZTkxZDk2YzQ4YjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g6SD4IZvJfQFfM0YJpOEj6w8Iv5l7_FHZ1TopRdJc9k)
> > 
> > More like a phone issue, must be the lack of path perms, after dump them in wich folder you put the dlcs and updates? Oh it says something about your prod.keys also, you could try redump them and installing on yuzu again and see if it works? Can't help much since i can't understand chinese/mandarin
> 
> Thank you for your suggestion, First time, I suspected that the path permission is incorrect, so I put the UPDATE in DOWNLOAD/YUZU folder. However, It's still dont work. And my key version is 17.0.0. It's so weird, I've never seen it before. SO, I try rollback install the 193 daily version and reinstall the UPDATE, finally it's work😂

Not sure why you put that on download folder, but try updating to 203 and installing an update or dlc in other separated folder that isn't inside the download one, pretty sure it will work
Example: make a folder on you phone's external memory(not inside download) called (updates and dlcs) and put your files there, go yuzu 203 and try install the files

**Comment by huangyebiaoke** [comment]
> > > I'm using v203 and i can import all my dlcs just fine![Yuzu dlc.jpg](https://private-user-images.githubusercontent.com/154700588/298446691-462e8d4e-ef49-4b7c-b775-b16f4c99a7c5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTUxMDUsIm5iZiI6MTcwNTg5NDgwNSwicGF0aCI6Ii8xNTQ3MDA1ODgvMjk4NDQ2NjkxLTQ2MmU4ZDRlLWVmNDktNGI3Yy1iNzc1LWIxNmY0Yzk5YTdjNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwMzQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmMzYjFhNzM2M2Q3YjVhOGNlMjcyNzdlMzk1YjIwMTVlMDhjMDk0NmMxYzM1OTFjMzI0ZTkxZDk2YzQ4YjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g6SD4IZvJfQFfM0YJpOEj6w8Iv5l7_FHZ1TopRdJc9k)
> > > 
> > > More like a phone issue, must be the lack of path perms, after dump them in wich folder you put the dlcs and updates? Oh it says something about your prod.keys also, you could try redump them and installing on yuzu again and see if it works? Can't help much since i can't understand chinese/mandarin
> > 
> > Thank you for your suggestion, First time, I suspected that the path permission is incorrect, so I put the UPDATE in DOWNLOAD/YUZU folder. However, It's still dont work. And my key version is 17.0.0. It's so weird, I've never seen it before. SO, I try rollback install the 193 daily version and reinstall the UPDATE, finally it's work😂
> 
> Not sure why you put that on download folder, but try updating to 203 and installing an update or dlc in other separated folder that isn't inside the download one, pretty sure it will work
> Example: make a folder on you phone's external storage(not inside download) called (updates and dlcs) and put your files there, go yuzu 203 and try install the files

I've try as you said, and it's work. But I'm still confused why can't put dlc in download folder or it's subfolder? And why the older version can work?
