### ISSUE TITLE
Access violation in device_memory_manager.h when encountering the lobby in Splatoon 2

### ISSUE THREAD

**Issue by anpilley** [yuzu-emu/yuzu#12741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1689 / EA 4079

### Description of Issue

A user in the discord is hitting an A/V in Splatoon 2

```Call Site
ntdll!NtWaitForSingleObject+0x14
KERNELBASE!WaitForSingleObjectEx+0x8e
yuzu!google_breakpad::ExceptionHandler::WriteMinidumpOnHandlerThread+0x85
yuzu!google_breakpad::ExceptionHandler::HandleException+0xfa
KERNELBASE!UnhandledExceptionFilter+0x1e7
ntdll!RtlUserThreadStart$filt$0+0xa2
ntdll!_C_specific_handler+0x96
ntdll!RtlpExecuteHandlerForException+0xf
ntdll!RtlDispatchException+0x244
ntdll!KiUserExceptionDispatch+0x2e
yuzu!Core::DeviceMemoryManager<Tegra::MaxwellDeviceTraits>::GetPointerFromRaw+0x7 [D:\a\1\s\src\core\device_memory_manager.h @ 133]
yuzu!Core::DeviceMemoryManager<Tegra::MaxwellDeviceTraits>::GetPointer+0x29 [D:\a\1\s\src\core\device_memory_manager.inc @ 343]
yuzu!Vulkan::anonymous namespace'::PrimitivesSucceededStreamer::PopUnsyncedQueries+0x1e6 [D:\a\1\s\src\video_core\renderer_vulkan\vk_query_cache.cpp @ 1109]
yuzu!VideoCommon::QueryCacheBase<Vulkan::QueryCacheParams>::PopAsyncFlushes::__l8::<lambda_1>::operator()+0x1e [D:\a\1\s\src\video_core\query_cache\query_cache.h @ 529]
yuzu!VideoCommon::QueryCacheBase<Vulkan::QueryCacheParams>::QueryCacheBaseImpl::ForEachStreamerIn+0x48 [D:\a\1\s\src\video_core\query_cache\query_cache.h @ 141]
yuzu!VideoCommon::QueryCacheBase<Vulkan::QueryCacheParams>::PopAsyncFlushes+0x10e [D:\a\1\s\src\video_core\query_cache\query_cache.h @ 521]
yuzu!VideoCommon::FenceManager<Vulkan::FenceManagerParams>::PopAsyncFlushes+0x1b8 [D:\a\1\s\src\video_core\fence_manager.h @ 251]
yuzu!VideoCommon::FenceManager<Vulkan::FenceManagerParams>::ReleaseThreadFunc+0x310 [D:\a\1\s\src\video_core\fence_manager.h @ 223]
yuzu!std::_Atomic_integral<unsigned int,4>::fetch_add+0x8 [C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\atomic @ 1508]
yuzu!std::stop_token::{ctor}+0x1c [C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\stop_token @ 128]
yuzu!VideoCommon::FenceManager<Vulkan::FenceManagerParams>::{ctor}::__l5::<lambda_1>::operator()+0x20 [D:\a\1\s\src\video_core\fence_manager.h @ 140]
yuzu!std::invoke+0x2a [C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\type_traits @ 1762]
yuzu!std::thread::_Invoke<std::tuple<VideoCommon::FenceManager<Vulkan::FenceManagerParams>::FenceManager<Vulkan::FenceManagerParams>'::5'::<lambda_1>,std::stop_token>,0,1>+0x3c [C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\thread @ 55]
ucrtbase!thread_start<unsigned int (__cdecl*)(void *),1>+0x42
kernel32!BaseThreadInitThunk+0x14
ntdll!RtlUserThreadStart+0x21
```

This crash was apparently not happening in EA build 3900 (unclear when it started happening, however)

### Expected Behavior

Yuzu doesn't crash

### Reproduction Steps

Quoting the user (dogomaxo) on discord.

`I open the emulator, I enter the game, and when I am in the square I press x, and I go to the expansion (the last section), and while it is loading the game it closes.`

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14004431/yuzu_log.txt)

Crash dump is from mainline build 1689
[9c835298-753e-41d1-b54c-ca460d488ddd.dmp](https://github.com/yuzu-emu/yuzu/files/14004432/9c835298-753e-41d1-b54c-ca460d488ddd.dmp)

### System Configuration

CPU: Intel(R) Core(TM) i5-10300H 
GPU/Driver: NVIDIA GeForce GTX 1650 Ti 546.29.0.0
RAM: 23.84 GiB
OS: Windows 10 Version 22H2

**Comment by ManiaSonicRUS** [comment]
I confirm. Yuzu crashes when entering the Octo Expansion lobby. Worked perfectly previously.

**Comment by anpilley** [comment]
@ManiaSonicRUS do you happen to know the last build that it worked for you, if any?

**Comment by ManiaSonicRUS** [comment]
> @ManiaSonicRUS do you happen to know the last build that it worked for you, if any?
I remember it working on 4045. It sure was already crashing on 4050, so got broken maybe a bit earlier.
Also, Splatoon 2 crashes not just when entering Octo Expansion; it crashes even when entering anything - Lobby, shops, Canyon, Octo Expansion, The Shoal. Just the Square works. That means multiplayer is not playable now for the squid games on yuzu. GG.
Hope they'll find a way to fix Splatoon 3 Shoal though, for me S3>S2 in terms of gameplay (even though its sad that S2 is broken too).

**Comment by ManiaSonicRUS** [comment]
[5211c7cb-4763-4b6d-8b81-c37f7ec6864f.dmp](https://github.com/yuzu-emu/yuzu/files/14006265/5211c7cb-4763-4b6d-8b81-c37f7ec6864f.dmp)
Here's a dump if needed. Doesn't look like log contains anything important.

**Comment by ManiaSonicRUS** [comment]
Can confirm it was fixed on 4084. Thank you so much.
