### ISSUE TITLE
[Android] Please add stick regions

### ISSUE THREAD

**Issue by Finblade** [yuzu-emu/yuzu#12742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

![289776640-87faf2b8-c774-4969-9b6e-ab7ed9dba93a](https://github.com/yuzu-emu/yuzu/assets/135484507/c94c6a43-08ec-41ed-aa61-462717a9a12a)
![289779920-d4c76e72-0c29-479e-b755-72baa450035a](https://github.com/yuzu-emu/yuzu/assets/135484507/f2900955-fd25-4e2c-b515-8be8dd40a5c0)

We can move character and rotate screen by using left and right virtual stick in current yuzu. Stick regions is basically from skyline and it will allow us to use whole left side of screen as left stick and whole right side of screen as right stick.

### Why would this feature be useful?

In current yuzu android, we can move character and rotate camera by using virtual stick only. It means we need to put finger on it everytime moving character and rotate camera and somehow it is bit uncomfortable. However if stick regions is implemented, users can move character by touching anywhere of left side of screen and rotate camera by touching anywhere of right side of screen. It will surely enhance user's play experience.

**Comment by FearlessTobi** [comment]
You already opened an issue for the exact same thing? https://github.com/yuzu-emu/yuzu/issues/12341
