### ISSUE TITLE
Joycons not working on Yuzu 1688 and forwards using steamdeck

### ISSUE THREAD

**Issue by Maciek070707** [yuzu-emu/yuzu#12750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1688

### Description of Issue

Joycons connected to the steamdeck are found and can be set up as a dual joycon (responsive for SteamOS), but after opening Yuzu, the controllers flash and are unresponsive in game. This behavior was not reproducable on Yuzu Mainline 1687.

### Expected Behavior

User can operate any title using joycons connected to Steamdeck via bluetooth.

### Reproduction Steps

1. Install yuzu mainline 1688 or above
2. Make sure you are in game mode
3. Connect Joycons to the Steamdeck device via bluetooth
4. Open Yuzu
5. Select any title
6. Try to use joycons as main controllers
7. Observe the result

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14013593/yuzu_log.txt)

### System Configuration

CPU: AMD Custom APU 0405
GPU/Driver: AMD Custom GPU 0405
RAM: 14.5 GiB
OS: SteamOS 3.6
OS Build: 20240119.1000
OS Variant: steamdeck-main

**Comment by german77** [comment]
Does it work if you disable vibration?

**Comment by german77** [comment]
Can you try narrowing down the issue. from 1680 to 1689 we added so much new stuff that is hard to determine for me where the issue is

**Comment by german77** [comment]
you can get any build from here hattps://github.com/yuzu-emu/yuzu-mainline/releases

**Comment by Maciek070707** [comment]
Apologies for such long waiting time. I had to learn a bit about linux and how to open apps using .Appimage 😄 

The last version in which I was able to use Joycons is Mainline 1687. It has been observed that Joycons on Mainline 1688 do not work anymore (tested in Gaming mode only). 

Thank you for your assistance in getting old Yuzu versions 🙏

**Comment by Maciek070707** [comment]
Ticket updated with relevant information.

**Comment by german77** [comment]
Give it a try with PR 12769 once the artifacts are done. If that doesn't work I will try doing hardware test with my joycons.

**Comment by Maciek070707** [comment]
My apologies but I'm just a humble tester. I've no clue what do I need to do and how to do that. It's my first time meddling with github

**Comment by german77** [comment]
On the bottom you should see the artifacts. Download the build then test. https://github.com/yuzu-emu/yuzu/actions/runs/7629608733

**Comment by Maciek070707** [comment]
Unfortunately Joycons are still unresponsive, although they do not flash anymore when starting any game using Yuzu.
Confirmed the occurrence alongside Yuzu build Mainline 1687 in which the issue does not appear.

Attaching new log file.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14042693/yuzu_log.txt)

**Comment by german77** [comment]
Yeah this one is no good. `GetSubCommandResponse:86: No response from joycon`.

I will try to see what else is bad here.

**Comment by german77** [comment]
Issue didn't get fully fixed

**Comment by peetezaah** [comment]
> Issue didn't get fully fixed

Even in 1687, have you tried motion-based games? Because for me, the motion stops working after 1 or 2 minigames. I can sometimes make it work again by disconnecting and reconnecting the controllers, but it's making motion games pretty much unplayable from start to finish.

**Comment by Maciek070707** [comment]
Yes, motion based games work for me on mainline 1687. It is a known issue that sometimes the Joycons will randomly disconnect (steamOS issue). For any Other issues with Joycons I personalny recommend forgetting both Joycons, restarting steamdeck machine (using "restart" button, NOT "restart steam") and connect the Joycons anew. Works wonders for motion based, joystick drift and Controller pairing issues.

**Comment by Maciek070707** [comment]
Issue seem to be resolved in build 1727 (I did not check when exactly was it fixed.) Ticket can be closed. Thank you.
