### ISSUE TITLE
Discrete GPU not available after opening once with it disabled

### ISSUE THREAD

**Issue by l3ifk** [yuzu-emu/yuzu#12752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1689

### Description of Issue

Whenever I disable my discrete Nvidia GPU and open Yuzu, I then use my integrated Radeon GPU because it's enough for Mario Kart or something similiar. But when I want to play more intense Games like Zelda BOTW I wanna use my discrete GPU. But once I open my Yuzu Emulator with only the integrated GPU the discrete GPU is no longer available in the Graphics tab... 
To solve it I had to delete the App and reinstall it, which is very inconvenienced! 
Just to clarify, I made sure to switch to Hybrid Mode to be able to see the GPU but I still didn't see it. Even on just discrete Graphics mode.
I run Yuzu on  Ubuntu 23.10 with a Ryzen 9 6900HX and a Nvidia RTX 2070 Ti.

### Expected Behavior

After switching the GPU mode to Hybrid again, the discrete GPU should be available again.

### Reproduction Steps

Change GPU mode to Integrated. 
Open Yuzu and play a game with integrated Graphics.
Switch to Hybrid/Discrete GPU mode again.
Open Yuzu and look unter the Graphics tab.

### Log File

[   0.036837] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.036845] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.710360] Input <Info> input_common/drivers/joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.739211] Service.HID <Info> hid_core/frontend/emulated_controller.cpp:SetPollingMode:1298: Set polling mode 0, device_index=1
[   0.739393] Service.HID <Info> hid_core/frontend/emulated_controller.cpp:SetPollingMode:1298: Set polling mode 0, device_index=1
[   0.739522] Service.HID <Info> hid_core/frontend/emulated_controller.cpp:SetPollingMode:1298: Set polling mode 0, device_index=1
[   0.739644] Service.HID <Info> hid_core/frontend/emulated_controller.cpp:SetPollingMode:1298: Set polling mode 0, device_index=1
[   0.739762] Service.HID <Info> hid_core/frontend/emulated_controller.cpp:SetPollingMode:1298: Set polling mode 0, device_index=1
[   0.739880] Service.HID <Info> hid_core/frontend/emulated_controller.cpp:SetPollingMode:1298: Set polling mode 0, device_index=1
[   0.739997] Service.HID <Info> hid_core/frontend/emulated_controller.cpp:SetPollingMode:1298: Set polling mode 0, device_index=1
[   0.740115] Service.HID <Info> hid_core/frontend/emulated_controller.cpp:SetPollingMode:1298: Set polling mode 0, device_index=1
[   0.740228] Service.HID <Info> hid_core/frontend/emulated_controller.cpp:SetPollingMode:1298: Set polling mode 0, device_index=1
[   0.740311] Service.HID <Info> hid_core/frontend/emulated_controller.cpp:SetPollingMode:1298: Set polling mode 0, device_index=1
[   0.740584] Frontend <Info> yuzu/main.cpp:GMainWindow:380: yuzu Version: yuzu 1689
[   0.740586] Frontend <Info> yuzu/main.cpp:LogRuntimes:265: Qt Compile: 5.15.10 Runtime: 5.15.10
[   0.740587] Frontend <Info> yuzu/main.cpp:GMainWindow:396: Host CPU: AMD Ryzen 9 6900HX with Radeon Graphics         | AVX2 | FMA
[   0.740613] Frontend <Info> yuzu/main.cpp:GMainWindow:398: Host CPU Cores: 8
[   0.740614] Frontend <Info> yuzu/main.cpp:GMainWindow:401: Host CPU Threads: 16
[   0.740632] Frontend <Info> yuzu/main.cpp:GMainWindow:402: Host OS: KDE Flatpak runtime
[   0.740642] Frontend <Info> yuzu/main.cpp:GMainWindow:403: Host RAM: 14.88 GiB
[   0.740643] Frontend <Info> yuzu/main.cpp:GMainWindow:405: Host Swap: 16.00 GiB
[   0.782379] Frontend <Info> yuzu/main.cpp:SetFirmwareVersion:4788: Installed firmware: NintendoSDK Firmware for NX 17.0.0-6.0
[   0.829459] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:446:     RomFS: Update (v0.12.0) applied successfully
[   0.844123] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:446:     RomFS: Update (v0.28.0) applied successfully
[   0.849395] Frontend <Warning> yuzu/main.cpp:SetupPrepareForSleep:1677: QDBusConnection system bus is not connected
[   0.851598] Loader <Warning> core/loader/loader.cpp:GetLoader:258: File The Legend of Zelda Breath of the Wild [01007EF00011E800][v786432].nsp has a different type (unknown) than its extension.
[   0.859889] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:446:     RomFS: Update (v0.12.0) applied successfully
[   0.868742] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:446:     RomFS: Update (v0.0.0) applied successfully
[   0.880666] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:446:     RomFS: Update (v0.28.0) applied successfully
[   0.897601] Loader <Warning> core/loader/loader.cpp:GetLoader:258: File The Legend of Zelda Breath of the Wild [01007EF00011E800][v786432].nsp has a different type (unknown) than its extension.
[ 395.691456] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:99: Auto-selecting the cubeb backend
[ 395.699871] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:99: Auto-selecting the cubeb backend
[ 395.748635] Service.HID <Info> hid_core/frontend/emulated_controller.cpp:SetPollingMode:1298: Set polling mode 0, device_index=1
[ 395.752254] Service.HID <Info> hid_core/fronte

### System Configuration

CPU: Ryzen 9 6900 HX
GPU/Driver: Nvidia RTX 2070 Ti Laptop, Driver 535.146.02
RAM: 16 GB
OS: Ubuntu 23.10

**Comment by liamwhite** [comment]
Are you sure? It should only require restarting the emulator to detect changes in available GPUs.

**Comment by l3ifk** [comment]
Yes I even restarted the entire system multiple times. the command nvidia-smi shows me that the nvidia gpu is working fine and detected by the OS and other games correctly

**Comment by l3ifk** [comment]
Is there a manual way to force Yuzu to reload available GPUs or search for changes?

**Comment by liamwhite** [comment]
The way to do it is to restart the emulator. If this isn't turning up anything:
- Install Vulkan validation layer (if needed)
- Tick the box in settings to enable graphics debugging
- Start a game
- Post an updated log

The Vulkan validation layer should record which GPUs are visible on game boot time. (Disable graphics debugging after doing this as it impacts performance.)

**Comment by l3ifk** [comment]
Thank you very much you solved the problem! I installed the vulkan validation layers with `sudo apt install vulkan-validationlayers` and upon starting yuzu, it now recognizes my discrete GPU again! Thanks :)
