### ISSUE TITLE
[Android] Per-game GPU driver switching is extremely not consistent or reliable

### ISSUE THREAD

**Issue by odt1** [yuzu-emu/yuzu#12766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All

### Description of Issue

Setting GPU driver in per-game settings window more often then not does nothing. Loading the game after selecting the driver can often load previous selection or even fallback to system driver. 

Multiple Yuzu restarts, switching drivers back and forth and several attempts in going back to game list screen are often needed to "lock" Yuzu to the selected one. 

It's almost impossible to figure out what GPU driver is loaded right now if you don't know how to look for particular issues with particular driver. 

The issue persists even if the game is launched from game list screen OR from settings screen using the "Play" button.

Feature request: option to see current loaded GPU driver JSON name and .so library in overlay view along with FPS and CPU backend.

### Expected Behavior

Selecting the driver should select the driver.

### Reproduction Steps

Try selecting the driver. 

### Log File

---

### System Configuration

CPU: 8 Gen 2
GPU/Driver: Any
RAM: 8Gb
OS: Android 13

**Comment by iamnotkurtcobain** [comment]
Experiencing the same issue. 

It's completely unreliable.

Please fix it and show the used GPU driver in the overlay.
