### ISSUE TITLE
[Android] Game Cover Icon is more rounded

### ISSUE THREAD

**Issue by yogiags86** [yuzu-emu/yuzu#12773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I know this is trivial and not important, but could the corners of the game cover look more rounded like in Skyline?

### Why would this feature be useful?

This will make the cover icon look more in line with Android's Material You Design.

**Comment by t895** [comment]
I see where you're coming from but there isn't a specific roundness that the images need to be as part of the guidelines. I think the most I would have them rounded would be the "Medium" preset that is suggested for cards and I personally see the Skyline game cards and a little too round.
Here's the general guidelines https://m3.material.io/styles/shape/shape-scale-tokens

**Comment by FearlessTobi** [comment]
This is more a matter of personal choice, therefore i am closing this issue.
