### ISSUE TITLE
[Android] Ultrawide Patch

### ISSUE THREAD

**Issue by yogiags86** [yuzu-emu/yuzu#12770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Most Android phones currently use Ultrawide screen ratios, 18:9, 19.5:9, 20:9 and so on. But Yuzu only supports full screen with Stretch game display. So I hope you add the Ultrawide Patch feature, to have true full screen. You can take an example in the Dolphin Emulator, Widescreen Patch. Thank You.

### Why would this feature be useful?

The game will be full screen following the phone screen ratio, without any Stretch on the game display.

**Comment by liamwhite** [comment]
As you may have guessed, this emulator is not Dolphin. Games need game-specific mods to render at unique aspect ratios, it doesn't work like it does for other consoles.
