### ISSUE TITLE
Opening EA Save or Mod Data Location opens the mainline folder.

### ISSUE THREAD

**Issue by OldManKain** [yuzu-emu/yuzu#12776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 8085

### Description of Issue

Opening the Save or Mod Data Location opens the mainline folder. Opening Transferable Pipeline cache works as intended.
I am using a portable install for both.
![image](https://github.com/yuzu-emu/yuzu/assets/47503099/71c6bbc2-e9e1-410e-9c86-12249552e344)

### Expected Behavior

It should be opening the early access Save and Mod data folder.

### Reproduction Steps

Make mainline and EA portable, right click your game and choose open Save or Mod Data Location.

### Log File

Does not show up in logs.

### System Configuration

CPU: Intel 12700KF
GPU/Driver: Geforce 4070 TI / 551.23
RAM: 32GB
OS: Windows 11

**Comment by german77** [comment]
Save folder works as expected. Mod folder does open the wrong one. Let me check why

**Comment by OldManKain** [comment]
Save folder works for you as intended? or is it supposed to open the mainline folder?  For me it opens mainline from EA.
![image](https://github.com/yuzu-emu/yuzu/assets/47503099/8c66c559-f976-46c9-8c95-f32cf8328c9c)

**Comment by german77** [comment]
Wrong default settings after debugging with the user. Everything is working as intended.
