### ISSUE TITLE
Allow keyboard stick modifier to work differently on the X and Y axis of each stick

### ISSUE THREAD

**Issue by Calinou** [yuzu-emu/yuzu#12774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Right now, when you use the keyboard as stick input, you're limited to 8 directions with 45-degree increments. The modifier doesn't change that as it acts the same on the X and Y axis of the stick: a reduced 45-degree input is still a 45-degree input.

### Why would this feature be useful?

By allowing the modifier to multiply the X and Y axis separately on each stick, it would be possible to input 12 directions (8 without the modifier + 4 with the modifier). For instance, if you set the X modifier to 50% and the Y modifier to 100%, holding the modifier key would only reduce horizontal stick movement, not vertical stick movement. By holding the modifier key, this makes it possible to input a direction that is *mostly* upwards or downwards, but slightly to the left/right as well.

The configuration dialog could look like this (mockup made with GIMP):

![image](https://github.com/yuzu-emu/yuzu/assets/180032/f340f896-acf6-4ba7-8e32-763799727d8c)

I'm interested in implementing this if you'd like :slightly_smiling_face:

**Comment by german77** [comment]
Have you checked analog with keyboard. I allows you to dial any angle without doing something complicated as this.
![image](https://github.com/yuzu-emu/yuzu/assets/5944268/4b2bd331-e1ed-42f6-8796-87beeb087afc)

**Comment by Calinou** [comment]
> Have you checked analog with keyboard. I allows you to dial any angle without doing something complicated as this.

That seems to work great, thanks :slightly_smiling_face: 

I'll close this for now as this seems to fit the bill for me.
