### ISSUE TITLE
[Android] Resolution Lower than 0.5

### ISSUE THREAD

**Issue by yogiags86** [yuzu-emu/yuzu#12782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Once again, I hope there will be a resolution option below 0.5.

### Why would this feature be useful?

Might make emulation a bit lighter for low end device. You may think this is not important, but please let me try the feature for myself. After this I won't bother you, just this once. please....

**Comment by german77** [comment]
Feel free to edit our code to support this the resolution is `up_scale / 2^down_shift` . As we said earlier going lower than 0.5x the benefits are minimal. Please stop opening issues about this. https://github.com/yuzu-emu/yuzu/blob/master/src/common/settings.cpp#L255

**Comment by goldenx86** [comment]
No GPU that can run yuzu is so slow that it benefits from 0.25x.
And if you really want to play games at 180p, I recommend GBC emulators.
