### ISSUE TITLE
[Android] I am using Adreno 730 but yuzu recognize it as adreno 725

### ISSUE THREAD

**Issue by Finblade** [yuzu-emu/yuzu#12785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Recent github

### Description of Issue

I am using 8+gen1 and Adreno 730 but when i show logs, it always says my device is adreno 725

### Expected Behavior

It should not recognize adreno 730 into 725

### Reproduction Steps

Just run any games and make a log. 

### Log File

[yuzu_log.txt.old-2.txt](https://github.com/yuzu-emu/yuzu/files/14052324/yuzu_log.txt.old-2.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14052325/yuzu_log.txt.old.txt)
![Screenshot_20240125_164204](https://github.com/yuzu-emu/yuzu/assets/135484507/003c62c5-f671-4e67-ac4c-aa826cf6fca1)

### System Configuration

CPU: 8+gen1
GPU/Driver: Adreno 730
RAM: 8gb
OS: Android 14

**Comment by liamwhite** [comment]
Turnip only, proprietary driver reports it correctly. Not a yuzu bug.
