### ISSUE TITLE
Black screen on launch with Taiko no Tatsujin Rhythm Festival

### ISSUE THREAD

**Issue by wongcoder** [yuzu-emu/yuzu#12797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1688

### Description of Issue

Game attempts to launch, then black screens.

### Expected Behavior

Game starts up as normal. 

### Reproduction Steps

Download 1687. Validate Taiko no Tatsujin Rhythm Festival starts up appropriately.

Download 1688. Validate Taiko no Tatsujin Rhythm Festival does not start up.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14059603/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz | AVX2 | FMA
GPU/Driver: NVIDIA 528.24.0.0 / NVIDIA GeForce RTX 3080
RAM: 31.94 GiB
OS: Windows 11 Version 22H2 (Build 22621.3007)

**Comment by liamwhite** [comment]
Upload the log as a file, instead of pasting it into the submission

**Comment by wongcoder** [comment]
Updated post with embedded yuzu log as a file.

**Comment by german77** [comment]
Can you set the log level to `Service.HID:Debug` on the debug tab and get me a new log.
