### ISSUE TITLE
Add a Option To disable Vulkan Extensiones in Vulkan 1.1

### ISSUE THREAD

**Issue by GithubUser559** [yuzu-emu/yuzu#12790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add A Option To Disable Vulkan 1.1 Extensions AND get better compatibility 

### Why would this feature be useful?

For PowerVR GPU. In 2D Games PowerVR Can Run It But You Need to Reduce Vulkan Extensions.All PowerVR GPU Has at least Vulkan 1.1

**Comment by liamwhite** [comment]
Disabling the baseline extensions we require just means that the emulator doesn't render anything at all, instead of crashing. There is no benefit to enabling support for a driver that is so far behind the times that the mesa pvr driver has a better chance of becoming compatible.
