### ISSUE TITLE
(The last suggestion) Add OpenGl ES With BGFX.

### ISSUE THREAD

**Issue by GithubUser559** [yuzu-emu/yuzu#12792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Using OpenGl Using BGFX (Investigate First)

### Why would this feature be useful?

Bro, I have already repeated this to you many times. (PowerVR)

**Comment by liamwhite** [comment]
> Bro, I have already repeated this to you many times

And we have told you, repeatedly, that PowerVR drivers are non-viable. Do not file any further issues for PowerVR support.

**Comment by goldenx86** [comment]
Buy usable hardware.
