### ISSUE TITLE
No vulkan devices detected on flatpak until another vulkan app is started

### ISSUE THREAD

**Issue by KayJay7** [yuzu-emu/yuzu#12805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu 1692 (current flatpak version)

### Description of Issue

After the system has just booted up, the combo box for selecting the vulkan graphic device is empty. And starting a game returns an error.

![image](https://github.com/yuzu-emu/yuzu/assets/31775749/caf14435-168e-4bd8-a55f-4680a22df840)

![image](https://github.com/yuzu-emu/yuzu/assets/31775749/b1fead5d-74f9-4496-96ed-1f8c93746940)

This is similar to the symptoms in [!12062](https://github.com/yuzu-emu/yuzu/issues/12062), so I went to the logs.
Unlike in the other issue, yuzu actually selects the device index 0, but gets an unknown vulkan error at initialization

```
...
[   8.391383] Config <Info> common/settings.cpp:operator():109: -C Renderer.vulkan_device: 0
...
[ 521.531084] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:994: Device doesn't support extension VK_EXT_external_memory_host
[ 521.531090] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:1056: Device doesn't support feature shaderFloat16
[ 521.531115] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:537: NVIDIA Drivers >= 510 do not support MSAA image blits
[ 521.531116] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:683: Pascal and older architectures have broken VK_KHR_push_descriptor
[ 521.556256] Render.Vulkan <Error> video_core/renderer_vulkan/renderer_vulkan.cpp:RendererVulkan:110: Vulkan initialization failed with error: VK_ERROR_UNKNOWN
[ 521.556280] HW.GPU <Error> video_core/video_core.cpp:CreateGPU:58: Failed to initialize GPU: Vulkan initialization error VK_ERROR_UNKNOWN
[ 521.556307] Core <Critical> core/core.cpp:Load:362: Failed to initialize system (Error 5)!
[ 521.841411] WebService <Error> web_service/web_backend.cpp:GenericRequest:120: POST to https://api.yuzu-emu.org/telemetry returned error status code: 400
...
```
Full log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14063986/yuzu_log.txt)

The strange part comes now: If you start any other vulkan application (e.g.: vkcube) an restart yuzu, it detects correctly every device and runs normally. Selecting the same device index 0.

```
...
[   8.404986] Config <Info> common/settings.cpp:operator():109: -C Renderer.vulkan_device: 0
...
[   8.631617] Loader <Info> core/file_sys/ips_layer.cpp:Parse:245: [IPSwitchCompiler ('3.0.1.pchtxt')] Parsing patch '21:9 Aspect Ratio (Now working in 2P Mode)' (enabled)
[   8.724732] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:994: Device doesn't support extension VK_EXT_external_memory_host
[   8.724738] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:1056: Device doesn't support feature shaderFloat16
[   8.724763] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:537: NVIDIA Drivers >= 510 do not support MSAA image blits
[   8.724764] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:683: Pascal and older architectures have broken VK_KHR_push_descriptor
[   8.780901] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:994: Device doesn't support extension VK_EXT_external_memory_host
[   8.780907] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:1056: Device doesn't support feature shaderFloat16
[   8.780930] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:537: NVIDIA Drivers >= 510 do not support MSAA image blits
[   8.780932] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:683: Pascal and older architectures have broken VK_KHR_push_descriptor
[   8.794842] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:158: Driver: NVIDIA 545.29.6.0
[   8.794844] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:159: Device: NVIDIA GeForce GTX 1060 3GB
[   8.794844] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:160: Vulkan: 1.3.260
[   8.794847] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:161: Available VRAM: 2.78 GiB
...
```
Full log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14064064/yuzu_log.txt)

### Expected Behavior

Yuzu should detect three vulkan devices: a nvidia 1060, a radeon iGPU, and llvmpipe; and should select use the nvidia one.

### Reproduction Steps

* Install yuzu from flatpak
* Reboot your system
* DON'T run any other program
* Run yuzu (it doesn't detect any vulkan device)
* Run vkcube
* Rerun yuzu (it detects every vulkan device)

### Log File

These are the same log files in the description:

[not-working.txt](https://github.com/yuzu-emu/yuzu/files/14064086/not-working.txt)

[working.txt](https://github.com/yuzu-emu/yuzu/files/14064089/working.txt)

### System Configuration

CPU: Ryzen 7 7700x
GPU/Driver: NVIDIA 545.29.06 (GTX 1060 3GB, headless) / RADV Mesa 23.3.3 (Radeon iGPU, attached to display)
RAM: 2x16GiB
OS: Fedora 39 kde

**Comment by Squall-Leonhart** [comment]
I don't see how this is Yuzu's doing.

**Comment by Squall-Leonhart** [comment]
This is caused by the AMD Switchable Graphics layer which had an early return failure preventing the enumeration of all vulkan devices in the system.

**Comment by KayJay7** [comment]
Understood, thanks, I'm closing this one and take care of that.

One last question to help me troubleshooting: how do you know it's the switchable graphics layer?

I can't find anything about layers on the logs and vulkaninfo doesn't report that layer (sidenote: vulkaninfo seems to be enough to fix the problem, no need to run vkcube). Also I don't use AMDVLK so I shouldn't have that layer to begin with.

the layers reported are:
```
VK_LAYER_FROG_gamescope_wsi_x86_64 Gamescope WSI (XWayland Bypass) Layer (x86_64) 1.3.221  version 1
VK_LAYER_MANGOHUD_overlay_x86      Vulkan Hud Overlay                             1.3.0    version 1
VK_LAYER_MANGOHUD_overlay_x86_64   Vulkan Hud Overlay                             1.3.0    version 1
VK_LAYER_MESA_device_select        Linux device selection layer                   1.3.211  version 1
VK_LAYER_NV_optimus                NVIDIA Optimus layer                           1.3.260  version 1
VK_LAYER_VALVE_steam_fossilize_32  Steam Pipeline Caching Layer                   1.3.207  version 1
VK_LAYER_VALVE_steam_fossilize_64  Steam Pipeline Caching Layer                   1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_32    Steam Overlay Layer                            1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_64    Steam Overlay Layer                            1.3.207  version 1
```

**Comment by Squall-Leonhart** [comment]
Missed the driver version, this is a driver / prime bug specific to flatpak that i'm not sure nvidia has ironed out yet.

https://github.com/flathub/org.yuzu_emu.yuzu/issues/1309

**Comment by KayJay7** [comment]
Got it, thanks for the help 👍🏼
