### ISSUE TITLE
Battle cats unite wont get past the starting loading screen

### ISSUE THREAD

**Issue by Olivierleone** [yuzu-emu/yuzu#12803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1693

### Description of Issue

Battle cats unite wont get past the starting loading screen (black screen with a cat) displays 0 fps. when you close the game the cat in the bottom right corner starts moving

### Expected Behavior

Supposed to load right into the game

### Reproduction Steps

1.Click on the game within yuzu
2. wait and the freeze will be noticeable

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14061429/yuzu_log.txt)

### System Configuration

CPU: 12th Gen Intel(R) Core(TM) i7-12700KF
GPU/Driver: RTX 3070/NVIDIA 546.29.0.0
RAM:32
OS:Windows

**Comment by gidoly** [comment]
regressed on mainline 1568
