### ISSUE TITLE
Running Yuzu on Raspberry Pi 5 with Libreelec - Need Assistance

### ISSUE THREAD

**Issue by joopdo** [yuzu-emu/yuzu#12819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I've been experimenting with running Yuzu on my Raspberry Pi 5 using Libreelec, but I've hit a bit of a roadblock. I attempted to use the appimage, but it seems to be designed for a different architecture. Has anyone successfully managed to run Yuzu on a Raspberry Pi 5? In best case I'd like to run it from Libreelec, but also happy to run on Raspbian.

I'm eager to learn and would greatly appreciate any guidance or tips from those who have experience with this setup. If you've encountered similar challenges and found a solution, please share your insights.

Here's what I've tried so far:

    Running the Yuzu appimage from https://yuzu-emu.org/downloads/#linux, but encountering compatibility issues.
    Exploring alternative methods or builds specifically tailored for the Raspberry Pi 5 architecture.

### Why would this feature be useful?

Useful for Raspberry Pi 5 users

**Comment by merryhime** [comment]
1. AFAIK the provided AppImages only run in x86-64 systems.
2. This will not run very well. The RPi 5 simply does not have the hardware capability. Performance will be terrible.
3. Ensure you're using a LibreELEC distribution for arm64. i.e. You will need to be running on an aarch64 LE 12 nightly.
4. Follow the instructions at [Building for Linux](https://yuzu-emu.org/wiki/building-for-linux/) to build yuzu yourself.
5. This will not be worth it.
