### ISSUE TITLE
Warhammer 40,000 Boltgun [01005FD017E60000] Broken Audio

### ISSUE THREAD

**Issue by Armory9756** [yuzu-emu/yuzu#12829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1694

### Description of Issue

The audio is broken from when the game loads. You can only hear a crackle every second as if it trying to play something. Visuals and latency appear OK, although I haven't progressed much in the game due to this issue.
Game Update Version - 1.0.0.3

### Expected Behavior

The audio should play as expected.

### Reproduction Steps

Load the game and the issue will become apparent from the loading screen.

### System Configuration

- CPU: AMD Ryzen 5 5600G
- GPU: AMD RX 7600
- GPU Driver version: Mesa 23.3.3
- RAM: 16 GB DDR4 3200 MHz
- System: Ubuntu 22.03.3 LTS, Linux Kernel 6.5

**Comment by liamwhite** [comment]
Was this fixed?
