### ISSUE TITLE
The Lara Croft Collection won't even start 

### ISSUE THREAD

**Issue by untouchable6849** [yuzu-emu/yuzu#12828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

#216

### Description of Issue

https://github.com/yuzu-emu/yuzu/assets/78664886/87db510f-d620-468f-8902-c04b0ff5c91f

### Expected Behavior

it loads flashing and then it crashes 

### Reproduction Steps

[The Lara Croft Collection save data - 2024-01-28 10_55.zip](https://github.com/yuzu-emu/yuzu/files/14075544/The.Lara.Croft.Collection.save.data.-.2024-01-28.10_55.zip)

### Log File

[yuzu_log.txt.old_1.txt](https://github.com/yuzu-emu/yuzu/files/14075540/yuzu_log.txt.old_1.txt)

### System Configuration

CPU: SD 8GEN2 
GPU/Driver: R15
RAM: 12
OS: Android 14

**Comment by Squall-Leonhart** [comment]
turnip error, not a yuzu bug.

**Comment by Squall-Leonhart** [comment]
Duplicate of #10981
