### ISSUE TITLE
yuzu just crashes after the loading screen on any game i try

### ISSUE THREAD

**Issue by angermanaged** [yuzu-emu/yuzu#12839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1696

### Description of Issue

wont work, keeps crashing (or closing, there are no crash dumps being produced) every time i try to play a game after it says "launching" after load then the emu closes. i must note that i setup yuzu the exact same way on another computer and it worked perfectly fine. on this computer i have only gotten ryujinx working but as it is too slow i cannot play it

### Expected Behavior

load and run the game

### Reproduction Steps

1.open the emulator
2.select a title
3.wait for loading
4.see yuzu close

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14080155/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i5-1035G1 4 core 3.6ghz
GPU/Driver: Intel(R) UHD Graphics w/ intel 7th-10th gen graphics driver version 31.0.101.2125
RAM: 8gb, 4gbVram
OS: Win10

**Comment by german77** [comment]
Your log says you have firmware 17 yet when you run a game files are missing. Please dump the firmware and keys again. You seem to have either corrupted or incomplete firmware

**Comment by angermanaged** [comment]
i have a question: i manually installed firmware 17 in "AppData\Roaming\yuzu\nand\system\Contents\registered" is there a way to install firmware through the emulator itself like ryujinx? i installed the same firmware to ryujinx through the option in the emulator and it worked fine.

**Comment by angermanaged** [comment]
i tried with new keys and firmware 17.0.1 because 17.0.0 still doesnt work even after fresh install etc. this was the result
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14088544/yuzu_log.txt.old.txt)

**Comment by german77** [comment]
Your new log still has the same issues as the older one for firmware. Does it crash to desktop or just loads forever?

**Comment by angermanaged** [comment]
> Your new log still has the same issues as the older one for firmware. Does it crash to desktop or just loads forever?

i wish i could screen record to make it easier. the screenshot i sent was taken a second before it closes. it does not load forever but it does load concerningly fast and once it says "launching" yuzu just straight up closes, no crash dump

**Comment by german77** [comment]
I'm trying to get some data I can debug on video won't help me much. No crash dump is also really weird. I might try to get this game and test with a debugger.

**Comment by Squall-Leonhart** [comment]
You have an unsupported Intel IGP that has a broken and never will be fixed spirv driver(on windows atleast)

OpenGL or wiping and installing linux are your only recourse.

**Comment by angermanaged** [comment]
> You have an unsupported Intel IGP that has a broken and never will be fixed spirv driver(on windows atleast)
> 
> OpenGL or wiping and installing linux are your only recourse.

ok. will attempt recourse and ill send a log if it doesnt work

**Comment by angermanaged** [comment]
here's a log on successful run on opengl

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14089033/yuzu_log.txt)

**Comment by german77** [comment]
Piracy is not allowed. Nor unofficial version of yuzu.
