### ISSUE TITLE
Gamepad vibrations are not working [Android]

### ISSUE THREAD

**Issue by Eiklaps** [yuzu-emu/yuzu#12841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All builds

### Description of Issue

I have connected my wired Xbox 360 controller to my phone with an OTG cable but while playing games in the Yuzu V212 the game pad does not vibrate. I have also enabled the vibration on inside the game settings but still not getting any type of vibrations. The games I tried are Assassin's creed 4 black flag, Batman Arkham Asylum & Arkham City. The gamepad is working properly & the gamepad vibrations are also working properly while playing games in Aethersx2 & Dolphin emulator.

### Expected Behavior

The gamepad with vibration motors should vibrate as the original console. This thing will be really useful for people who play the emulator with a gamepad that has vibration motors and connect the gamepad to their phone by OTG cable or wireless dongle. I think the vibration feedback also gives a little bit of immersion in games

### Reproduction Steps

Just connect your wired gamepad with vibration motors to your phone with OTG cable or wireless dongle. Make sure you connect the controller with only wired or wireless dongle the vibration does not work in Bluetooth mode also make sure the controller does have working vibration motors. Try playing the games I mentioned or any other game you own the controller vibrations are not going to work but try the controller in Aethersx2 or dolphin emulator and the vibration works fine.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14081522/yuzu_log.txt.old.txt)

### System Configuration

CPU: Snapdragon 888
GPU/Driver: Adreno 660
RAM: 12 GB
ROM: 256 GB
Device: Realme GT2
OS: Android 13

**Comment by evil-trainer** [comment]
Yuzu Android never supported controller vibration and it still is being implemented. The whole controller mapping function is in the works and so is support for vibration.

**Comment by Eiklaps** [comment]
Thanks t895 for fixing this issue. The vibration works fine both in gamepad & mobile motors. I hope to see also HD rumble implemented in future updates.

**Comment by t895** [comment]
Solved by #13034
