### ISSUE TITLE
Allow to change save file directory 

### ISSUE THREAD

**Issue by InnocentAngel** [yuzu-emu/yuzu#12854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I would like the ability to change the save file directory in yuzu that way i can sync saves across devices seamlessly utilizing my google drive.

### Why would this feature be useful?

Its a super fast and efficient way to sync saves between multiple devices.

**Comment by german77** [comment]
Nand folder contains the save files and this folder can be moved.

**Comment by InnocentAngel** [comment]
> Nand folder contains the save files and this folder can be moved.

So if i move the Nand folder to google drive then that "acts" as having a cloud save option? I just want to move the game save files and not the settings for yuzu. So in moving the Nand file it would affect my android settings via emulator settings?? My pc emulator settings are different from android.

**Comment by InnocentAngel** [comment]
> Nand folder contains the save files and this folder can be moved.

Additionally in order to move the Nand folder i have to create a user folder in yuzu. That would create a "mobile" yuzu download. But would i be able to put the user file in google drive and yuzu would recognize this? Or put the Nand folder in google drive and itll continue to put the saves on that folder?? Or would it create a new nand folder in yuzu since it would be missing. In the end i just want my saves to go to google drive so i can sync the save files between device's. It seems simple but on yuzus platform its not as easlily laid out.

**Comment by german77** [comment]
As long as this setting points to the correct folder it will work regardless if yuzu is portable or not. ![image](https://github.com/yuzu-emu/yuzu/assets/5944268/aa23ed97-95de-4269-88ba-be62665a64ee)

Alternatively alternatively you can have a portable yuzu in your google drive. This should work without folder modifications.

**Comment by InnocentAngel** [comment]
> As long as this setting points to the correct folder it will work regardless if yuzu is portable or not. ![image](https://private-user-images.githubusercontent.com/5944268/300862287-aa23ed97-95de-4269-88ba-be62665a64ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MzE5MzMsIm5iZiI6MTcwNjYzMTYzMywicGF0aCI6Ii81OTQ0MjY4LzMwMDg2MjI4Ny1hYTIzZWQ5Ny05NWRlLTQyNjktODhiYS1iZTYyNjY1YTY0ZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMTYyMDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjA3ZmM3YzIwMWJhNjRmMmFkMjg5ZjljMWIzNjc1ZDYxZGVmNWE4OGYwOGY3YmUyZmNkMTExZDU2YTUxN2ZmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Zd7-ZiJQM3RmdT3PWGZJEvN8eWx3X-7zIQGuJ1njXRs)
> 
> Alternatively alternatively you can have a portable yuzu in your google drive. This should work without folder modifications.

Oh perfect!!! Yeah the system filesystem would work perfect. Now sorry again for hopefully last question for you. But i dont see a system/filesystem storage directories prompt on yuzu android. Is the system filesystem only on windows? Or in android do i open yuzu folder and manually move the Nand folder to my google drive? But if manually moved thats where i worry yuzu wont recognize where i moved the Nand folder to on android.

**Comment by german77** [comment]
This setting isn't exposed on android. However it does exist search for `nand_directory` in the settings file located at
`\Android\data\org.yuzu.yuzu_emu\files\config\config.ini` I don't know how google drive works on android so I don't know if it will work properly

**Comment by flodavid** [comment]
If you want to only backup save file on your drive, you could move the folder C:\Users\\%username%\AppData\Roaming\yuzu\nand\user\save to the Google Drive directory, and then, open cmd and run: `mklink /D C:\Users\%username%\AppData\Roaming\yuzu\nand\user\save YOUR_GOOGLE_DRIVE_DIR\save`.
This will create a symbolic link, and make yuzu think your are saving locally when you are not.
