### ISSUE TITLE
Splatoon 3 | Crashing and performance issues (Regression)

### ISSUE THREAD

**Issue by ManiaSonicRUS** [yuzu-emu/yuzu#12865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 4099

### Description of Issue

EA 4099 (maybe A BIT earlier, it was fine like 5 versions ago) leads to new Splatoon 3 issues, the main two of them:
1. The game stopped freezing while compiling shaders at loading screens - instead it compiles shaders much, much slower than previously and freezes exactly within gameplay now instead of doing that at the loading screens.
Its terrible as it can randomly freeze for a ~minute while you're in a level or lobby, also takes minutes to unfreeze from the title screen. Never had such an issue before, pls fix.
2. All system errors that contain codes (and can actually be handled by the real console) lead to crashes, an example, previously it just kicked off the player from the Shoal, but now it crashes the whole emulator. The log tells more.

### Expected Behavior

As its a big regression, I hope it gets fixed, at least to the way it was with some yuzu EA versions before.

### Reproduction Steps

For the 1st issue, just try to boot the game.
For the 2nd issue, try to do something that makes system error messages to appear, like try to enter the Shoal with no Network adapter selected on yuzu, or try to make a lobby in The Shoal when you're not in a LDN room.
That stuff never caused crashes, so something big got regressed.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14103879/yuzu_log.txt)

### System Configuration

Vulkan
CPU: i5-12400F
GPU/Driver: GTX 1650 SUPER, 546.65
RAM: 2x16GB DDR4 3200
OS: Windows 11 Pro 21H2 (22000.2538)

**Comment by ManiaSonicRUS** [comment]
...https://github.com/yuzu-emu/yuzu/issues/11141 is still not fixed. Doesn't matter though, as with the current regression I'd not call the game playable at all, multiplayer is not that important...

**Comment by liamwhite** [comment]
I don't know what caused the first issue but the second is probably from #12760

**Comment by liamwhite** [comment]
First issue is probably from a nvidia driver update

**Comment by llKraiD** [comment]
the second issue its happening with other games like mario kart 8. 
i tested splatoon 3 and the first issue is not happening on EA 4101 with nvidia driver 546.33.

**Comment by liamwhite** [comment]
@llKraiD what are some steps to reproduce in mario kart 8?

**Comment by llKraiD** [comment]
Open the game try to force the connection to nintendo servers and receive the error message.

**Comment by liamwhite** [comment]
Splatoon 3 / MK8D error applet will be fixed in next build by [this](https://github.com/yuzu-emu/yuzu/pull/12760/commits/817d916233adcfb26814fde677e71d9825ce614c)

**Comment by ManiaSonicRUS** [comment]
More info on the peformance/freezing issue.
yuzu.exe, ucrtbase.dll 0xc0000409 at 0x000000000007dd7e
No dump was created. It just crashed after ~40 seconds of a softlock that happened 2 seconds after I left the title screen.
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14112478/yuzu_log.txt.old.txt)

**Comment by ManiaSonicRUS** [comment]
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14113212/yuzu_log.txt.old.txt)
Here it freezed 3 times (for minutes) but didn't crash.

**Comment by ManiaSonicRUS** [comment]
> First issue is probably from a nvidia driver update

To be honest, seems so. I tried yuzu 4087 version where Splatoon 3 worked great and there's the same issue. Going to try the previous Nvidia driver.

**Comment by ManiaSonicRUS** [comment]
Nope that didn't help. Seems its finally the time to reinstall Windows, as nor old yuzu version nor old drivers help.

**Comment by ManiaSonicRUS** [comment]
Reverting to yuzu 4085 and reverting to the previous Nvidia drivers didn't help.
I reinstalled Windows and now the performance issue is gone.

**Comment by ManiaSonicRUS** [comment]
...so, this is fixed. Now I just hope someone tries to handle https://github.com/yuzu-emu/yuzu/issues/11141. Its really close, as its possible to start the match using the spectator mode; the Shoal lobby is also 100% working even when people are connected to the server
