### ISSUE TITLE
game starts at GMT time not my local time

### ISSUE THREAD

**Issue by Ronshere** [yuzu-emu/yuzu#12862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1698

### Description of Issue

I just updated to 1698 and my games start 5 hours ahead to GMT time, not my local New York time.  I have even tried applying a specific time in the configuration settings but it is ignored.

### Expected Behavior

It should start with My time New York City.  Instead it starts with Greenwich time.
I looked in configuration and it reads correctly but does not start correctly. I even tried forcing the time by  choosing a custom RTC date.  No good.

### Reproduction Steps

no idea how to reproduce it

### Log File

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/14102971/yuzu_log.zip)

### System Configuration

CPU:  I7 6700k
GPU/Driver: Nvidia GTX 970
RAM: 32GB
OS: Win 10

**Comment by german77** [comment]
We don't provide support to piracy.
