### ISSUE TITLE
[Metroid Prime Remastered] Regression: Intro Video weird behavior and leading to crash randomly after Reworked NVDEC got implemented

### ISSUE THREAD

**Issue by llKraiD** [yuzu-emu/yuzu#12876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 4104

### Description of Issue

Intro Video is Slow or crashes the emulator randomly on game boot
Video of Issue : https://youtu.be/GQBkLBk6h1U?feature=shared

### Expected Behavior

Have smooth video and not crashes

### Reproduction Steps

Boot the game.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14118391/yuzu_log.txt)

### System Configuration

CPU: i5 10400f
GPU/Driver: NVIDIA RTX 3050 (546.33)
RAM: 16GB
OS: Win 10 Enterprise

**Comment by asp0909** [comment]
same problem here!

**Comment by llKraiD** [comment]
Closing it because its already fixed on EA 4109
