### ISSUE TITLE
[TotK 1.2.1] Objects disappear when getting near them

### ISSUE THREAD

**Issue by scorpion81** [yuzu-emu/yuzu#12872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1698, also happens in Mainline 1428, 1468, 1478 ( a few older builds from around May-June 2023)

### Description of Issue

Objects (in this case the sails laying on the ground) disappear when getting near them. Possibly the most detailed LOD level is not being loaded or so. See the attached video. This doesnt happen in Version 1.0.0 of the game, btw, Tested with the same build of yuzu.

https://github.com/yuzu-emu/yuzu/assets/1172149/95ecd277-380e-4f37-8dae-273a396b51f0

### Expected Behavior

The sails should not disappear, since they are required for progress there.

### Reproduction Steps

Load the first save of this TotK save folder copy and just walk straight on, towards the sails.
[0100F2C0115B6000.zip](https://github.com/yuzu-emu/yuzu/files/14114288/0100F2C0115B6000.zip)

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14114302/yuzu_log.txt.old.txt)

### System Configuration

CPU: Steam Deck CPU (AMD Custom APU 0405 | AVX2 | FMA)
GPU/Driver: Steam Deck GPU (AMD Custom APU 0405 | AVX2 | FMA)
RAM: 16 GB
OS: Steam OS

**Comment by LotP1** [comment]
I've seen 3 other reports of this in the UltraCam discord server.
The last reporter fixed it by switching to game version 1.2.0, can you check if this works for you?

**Comment by scorpion81** [comment]
> I've seen 3 other reports of this in the UltraCam discord server. The last reporter fixed it by switching to game version 1.2.0, can you check if this works for you?

Yup, 1.2.0 seems to work for me as well. Weird issue with 1.2.1 though. I hope i dont need the other fixes which were added after 1.2.0 in order to play the game properly.

**Comment by Squall-Leonhart** [comment]
This has been confirmed to be caused by the 1.2.1 update you are using being faulty / corrupt (IE, illegally downloaded instead of dumped from your own hardware)

**Comment by scorpion81** [comment]
Nevermind, works now. I re-dumped this now again from my hardware. Seems something was wrong with the previous dump.
