### ISSUE TITLE
Yuzu android closet on Vivo Y77 china

### ISSUE THREAD

**Issue by hdk2d** [yuzu-emu/yuzu#12884]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Android-222

### Description of Issue

Yuzu android close

### Expected Behavior

https://github.com/yuzu-emu/yuzu/assets/86883038/133e8763-8548-4745-9aa6-4fcef3e01695

### Reproduction Steps

None

### Log File

[yuzu_log_112730.txt](https://github.com/yuzu-emu/yuzu/files/14127395/yuzu_log_112730.txt)

### System Configuration

CPU:Mediatek Dimensity 930
GPU/Driver:IMG BXM-8-256
RAM:12GB
OS:OriginOS 3 basen on android 13

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please ask for support on our Discord.
