### ISSUE TITLE
Zelda TOTK fails to boot on Snapdraggon 870

### ISSUE THREAD

**Issue by beginor** [yuzu-emu/yuzu#12880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

android-222

### Description of Issue

TOTK stops after "Nintendo presents" and "loading....".

yuzu_log.txt ends with :

```
[ 167.274491] Service.FS <Info> core/hle/service/filesystem/fsp/fsp_srv.cpp:OpenSaveDataFileSystem:448: called.
[ 167.303847] Service.AM <Warning> core/hle/service/am/application_functions.cpp:NotifyRunning:370: (STUBBED) called
[ 167.808495] Service.FS <Warning> core/hle/service/filesystem/fsp/fs_i_filesystem.cpp:Commit:182: (STUBBED) called
[ 167.942224] Service.FS <Warning> core/hle/service/filesystem/fsp/fs_i_filesystem.cpp:Commit:182: (STUBBED) called
[ 168.107448] Service.FS <Warning> core/hle/service/filesystem/fsp/fs_i_filesystem.cpp:Commit:182: (STUBBED) called
[ 168.242298] Service.FS <Warning> core/hle/service/filesystem/fsp/fs_i_filesystem.cpp:Commit:182: (STUBBED) called
[ 168.408905] Service.FS <Warning> core/hle/service/filesystem/fsp/fs_i_filesystem.cpp:Commit:182: (STUBBED) called
[ 168.541167] Service.FS <Warning> core/hle/service/filesystem/fsp/fs_i_filesystem.cpp:Commit:182: (STUBBED) called
[ 172.861999] Render.Vulkan <Critical> video_core/vulkan_common/vulkan_device.cpp:ReportLoss:785: Device loss occurred!
```

### Expected Behavior

The game not crashing.

### Reproduction Steps

Just open TOTK

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14120109/yuzu_log.txt)

### System Configuration

CPU: Snapdraggon 870
GPU/Driver: Adrino 650 Both system & Turnip V16
RAM: 12GB
OS: MIUI 14.0.7

**Comment by liamwhite** [comment]
On A6xx, TOTK requires the newest official Qualcomm drivers to run - doesn't render with older Qualcomm drivers, and has guaranteed device loss in Turnip.

**Comment by beginor** [comment]
Thanks for you reply, I'll try with newest Qualcomm driver.
