### ISSUE TITLE
Ni no Kuni: Wrath of the White Witch - broken cinematics

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#12894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Pr build 12756

### Description of Issue

the game's cinematics are corrupted and pixelated

![Screenshot_20240202-110516_yuzu Debug Release](https://github.com/yuzu-emu/yuzu/assets/4172898/04e38cf5-8db2-40dd-8c9a-5424c8f21e0a)
![Screenshot_20240202-110316_yuzu Debug Release](https://github.com/yuzu-emu/yuzu/assets/4172898/f67845c0-25b9-4fd8-bb7f-0d8d69549b66)

Other than that the game runs fine but with dynarmic, I hope to use NCE

![IMG_20240202_111855_087](https://github.com/yuzu-emu/yuzu/assets/4172898/3ba9edd8-440c-49b9-86b8-f961cf162d06)

### Expected Behavior

the cinematics should look good

### Reproduction Steps

Just play normally 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14143737/yuzu_log.txt)

### System Configuration

CPU: sd860
GPU/Driver: adreno 640, turnip driver 
RAM: 8gb
OS: android 13

**Comment by liamwhite** [comment]
Fixed by #12461, recheck android build later

**Comment by FearlessTobi** [comment]
We only allow issue reports for our Github or Google Play releases, not random Pull Requests.
