### ISSUE TITLE
Invalid Vulkan descriptor set usage

### ISSUE THREAD

**Issue by PixelyIon** [yuzu-emu/yuzu#12891]
### Issue

I was investigating a crash with yuzu on ToTK with Turnip that was reported by users to occur on my [GMEM MR](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/26461) but not with sysmem so initially I assumed it was a regression. As it turned out, this issue was caused by invalid descriptor set usage by yuzu with attempting to use bindings that don't exist, resulting in a GPU page fault which is a non-fatal error emitted by the kernel driver (KGSL/msm-drm) but consumed after logging it. 

This fault occurred on both sysmem/GMEM but on GMEM, due to tiling the fault would occur for every tile per broken draw rather than once per broken draw on sysmem, the kernel has some latency with each fault which is manageable with the smaller amount of faults in sysmem (so it would appear to work fine) but on GMEM this leads to a timeout with an eventual crash due to a kernel limit on timeouts or crashing the kernel driver itself with a mini-DoS from the fault handling.

**Comment by FernandoS27** [comment]
smells like this:
[ 100.207785] Render.Vulkan <Critical> video_core\vulkan_common\vulkan_debug_callback.cpp:DebugUtilCallback:55: Validation Error: [ VUID-vkCmdDrawIndexed-None-09003 ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0x366f780000003922, type = VK_OBJECT_TYPE_IMAGE_VIEW; Object 2: handle = 0x2f1d9c0000003926, type = VK_OBJECT_TYPE_FRAMEBUFFER; Object 3: handle = 0xcc41a70000003925, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0xdca63906 | vkCmdDrawIndexed: Descriptor set VkDescriptorSet 0x0[] Image subresources of VkImageView 0x366f780000003922[] is being read from in Descriptor in binding #1 index 0 and will be written to as VkImageView 0xcc41a70000003925[] in VkFramebuffer 0x2f1d9c0000003926[] attachment # 0 overlap. The Vulkan spec states: If an attachment is written by any prior command in this subpass or by the load, store, or resolve operations for this subpass, it must not be accessed in any way other than as an attachment, storage image, or sampled image by this command (https://vulkan.lunarg.com/doc/view/1.3.261.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-None-09003)

**Comment by PixelyIon** [comment]
Just to recap what we discussed on Discord, that while it's an invalid feedback loop and should be fixed. It wouldn't lead to a GPU page fault in itself, that would be caused by something like:
```
VUID-vkCmdDrawIndexed-None-08600(ERROR / SPEC): msgNum: 941228658 - Validation Error: [ VUID-vkCmdDrawIndexed-None-08600 ] Object 0: handle = 0x9f53500000001c66, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x381a0272 | vkCmdDrawIndexed():  The VkPipeline 0x9f53500000001c66[] (created with VkPipelineLayout 0x28eb5f0000001a8f[]) statically uses descriptor set (index #0) which is not compatible with the currently bound descriptor set's pipeline layout (VkPipelineLayout 0x0[]). The Vulkan spec states: For each set n that is statically used by a bound shader, a descriptor set must have been bound to n at the same pipeline bind point, with a VkPipelineLayout that is compatible for set n, with the VkPipelineLayout used to create the current VkPipeline or the VkDescriptorSetLayout array used to create the current VkShaderEXT , as described in Pipeline Layout Compatibility (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-None-08600)
    Objects: 1
        [0] 0x9f53500000001c66, type: 19, name: NULL
```

I got a bunch of these while replaying a gfxrecon capture with the validation layer on. I've attached a [log](https://github.com/yuzu-emu/yuzu/files/14139643/totk-val.tar.gz) with them that you can look through.

**Comment by PixelyIon** [comment]
After investigating this further, it seems this was a regression with Turnip that existed on more than just yuzu. The bug was successfully fixed on the MR.
