### ISSUE TITLE
Assassin’s Creed: The Ezio Collection - doesnt boot anymore on build 227

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#12898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android v227

### Description of Issue

The game doesnt boot anymore on android build 227 and when I try to close the game the emulator stops responding and I have to force close

https://github.com/yuzu-emu/yuzu/assets/4172898/7907510b-35d8-45a7-9ccf-8ec14ef6cbd8

### Expected Behavior

the game should start

### Reproduction Steps

Just launch game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14150156/yuzu_log.txt)

### System Configuration

CPU: sd860
GPU/Driver: adreno 640, turnip driver 
RAM: 8gb
OS: android 13

**Comment by liamwhite** [comment]
This happens when you are missing the DLC

**Comment by brujo5** [comment]
The last time I tried it I didn't have the DLC installed either and it worked but it had a flickering textura bug.

Anyway I'm going to try with the DLC installed

**Comment by liamwhite** [comment]
Yeah, tried it locally and it's fine. I suspect issues with your dumps.

**Comment by brujo5** [comment]
I have installed all DLC games + update and working great, but the base game AC 2 crashes on new game selection.

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14154217/yuzu_log.txt.old.txt)


Bortherhood

![Screenshot_20240203-115241_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/667e9606-5647-46fd-a435-15edb67b46a6)
![Screenshot_20240203-114155_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/be3f5470-1044-40dc-abf2-ddd54285dc34)

Revelations

![Screenshot_20240203-124551_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/8ea539e0-e152-4120-8f5a-23404a92314e)
![Screenshot_20240203-130045_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/47424801-2b6d-4d55-a50c-a19f42304ee7)
