### ISSUE TITLE
 Alien Isolation - Heavy video glitching

### ISSUE THREAD

**Issue by i2puni** [yuzu-emu/yuzu#12896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 4109

### Description of Issue

The intro videos past the 20th Century Fox one are heavily glitched .
The Main Menu background is not being rendered properly
![1](https://github.com/yuzu-emu/yuzu/assets/38171931/4b638379-5aa6-4742-a217-b5b19b0d88cf)

Ryujinx has no problem.
![4](https://github.com/yuzu-emu/yuzu/assets/38171931/232780b0-01ae-4359-99ef-cc8eb16aa29a)

### Expected Behavior

Main menu should render properly

The problem was reported in July of last year, but has not yet been fixed.

### Reproduction Steps

Install Alien Isolation with the 1.1.5_64113 update
Launch the Game try to start a New Game

### Log File

Does not have it

### System Configuration

CPU: i7-8700
GPU/Driver: GTX 1060 6GB
RAM: 16 GB
OS: WIN10

**Comment by german77** [comment]
Duplicated issue #11057

**Comment by PH6970** [comment]
In the Android version there are still bugs in the computer graphics even on the Yuzu 243 but after the animations the normal game starts on my Poco F5 Pro.
