### ISSUE TITLE
[Zelda TOTK] weapons incorrectly displayed in inventory

### ISSUE THREAD

**Issue by Jim-dll** [yuzu-emu/yuzu#12900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1701

### Description of Issue

![Screenshot 1](https://github.com/yuzu-emu/yuzu/assets/153986739/c915d51c-2c57-4951-9022-789b715f4594)
![Screenshot 2](https://github.com/yuzu-emu/yuzu/assets/153986739/a24ed42d-7a50-48d7-94a2-8fcfe4aecc71)

### Expected Behavior

Weapons display correctly

### Reproduction Steps

You have to go to the inventory

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14151123/yuzu_log.txt)

### System Configuration

CPU: Intel Pentium Gold 8505
GPU/Driver: Intel UHD Graphics / 31.0.101.5186 (Latest)
RAM: 8GB DDR4 3200 Mhz
OS: Windows 11 23H2 (Latest Update)

**Comment by EgoBizarro** [comment]
This happens when having async shader compilation enabled.

**Comment by fanitriastowo** [comment]
drop and pick it up again. that work for me when Async Shader Compilation is enabled. I also clear "Cache Storage" in right click menu on game list to refresh the inventory and autobuild icons
