### ISSUE TITLE
[Android] Resolution Overlay

### ISSUE THREAD

**Issue by yogiags86** [yuzu-emu/yuzu#12906]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What feature are you suggesting?

Added Overlay resolution feature while playing

### Why would this feature be useful?

This will show the resolution being used when playing, but make it an option that can be on/off like FPS.
![Picsart_24-02-04_08-19-19-088](https://github.com/yuzu-emu/yuzu/assets/81731189/e8f9aa00-892a-4022-b2c5-a1d3d5854083)

**Comment by iamnotkurtcobain** [comment]
There should be even more overlay options

**Comment by yogiags86** [comment]
> There should be even more overlay options

Okay, thank you
