### ISSUE TITLE
[Android] Asking for why Yuzu is greatly slowest than Skyline Emulator in terms of performance?

### ISSUE THREAD

**Issue by Samsung-user** [yuzu-emu/yuzu#12918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Most versions

### Description of Issue

I greatly respect this emulator for being compatible with almost all Switch games and gameplay is much smoother when you least successfully achieve full 60 fps performance speed. On the other side is Skyline, using NCE algorithm to emulate the system, fastest, but least compatible. However, implemented NCE in Yuzu doesn't work with MALI devices and with Dynarmic it is a slowest, yeah I mean A LOT MORE SLOWER. I would like to hope that, team will bring some settings to improve speed at the cost of disabling or decreasing some features.

### Expected Behavior

Speed Enhancement Settings

### Reproduction Steps

Idk

### Log File

Not

### System Configuration

CPU:Exynos 9820
GPU/Driver: Mali g-76 mp12 emea/latam
RAM:8GB
OS:Android 11

**Comment by german77** [comment]
Skyline was made from the ground up for android devices.  Also take in mind yuzu android just released a year ago while skyline has been in development more time.

We still have work ahead to expand our compatibility with android devices.

**Comment by Samsung-user** [comment]
> Skyline was made from the ground up for android devices. Also take in mind yuzu android just released a year ago while skyline has been in development more time.
> 
> We still have work ahead to expand our compatibility with android devices.

You ain't mention why it doesn't have better performance and why NCE doesn't work for Mali GPU devices.

**Comment by Samsung-user** [comment]
:(
