### ISSUE TITLE
Monster Hunter Rise, Monster Hunter XX  start the game, only a white screen appears.

### ISSUE THREAD

**Issue by i2puni** [yuzu-emu/yuzu#12913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA4111

### Description of Issue

![1](https://github.com/yuzu-emu/yuzu/assets/38171931/2d54ce9f-e720-4ec5-9733-1dab6f7f2d09)
In recent EA versions I just get a white screen.
This wasn't the case before and there are no issues with the mainline version either.

### Expected Behavior

I hope this issue is fixed

### Reproduction Steps

Monster Hunter Rise, Monster Hunter XX
start the game

### Log File

Does not have it

### System Configuration

CPU: i7 8700
GPU/Driver: GTX1060 6GB  551.23 driver
RAM: 16GB
OS: WIN10

**Comment by german77** [comment]
Provide a log File. We can't magically discover why you have issues. Feel free to reopen once that's done.

The following guide shows how to get the log file: https://yuzu-emu.org/help/reference/log-files/

**Comment by liamwhite** [comment]
Your installed firmware version is too old, update it to the latest.

**Comment by i2puni** [comment]
I tried running version EA 4114 and the problem was fixed. thank you
