### ISSUE TITLE
Mediatek p90 can play yuzu emulator?

### ISSUE THREAD

**Issue by Bayzxn** [yuzu-emu/yuzu#12921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I request that Mediatek P90 can play Yuzu emulator

### Why would this feature be useful?

I request that Mediatek P90 can play Yuzu emulator

**Comment by t895** [comment]
Our github issues are not for support. Please ask for help in our discord server.

**Comment by Bayzxn** [comment]
I request that Mediatek P90 can play Yuzu emulator

**Comment by goldenx86** [comment]
This is not on us, contact PowerVR, the maker of the GPU in that SoC, to provide good Vulkan drivers.
