### ISSUE TITLE
yuzu Xbox series X&S port please !!! 

### ISSUE THREAD

**Issue by Soheilsadri278** [yuzu-emu/yuzu#12945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

please devs we really need a **Xbox** port of this emulator there are lot of guys like me !! we have all nintendo emulators in xbox except switch and wii u.

### Why would this feature be useful?

**_because a lot of people need this port and it can be useful_**

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/6059.
