### ISSUE TITLE
Cubeb could not get min latency, it is not suitable.

### ISSUE THREAD

**Issue by eZtaR1** [yuzu-emu/yuzu#12959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1706

### Description of Issue

No sound devices
![image](https://github.com/yuzu-emu/yuzu/assets/113856704/d3365134-921e-4f70-837a-3fdd4684649a)

### Expected Behavior

Sound devices
![image](https://github.com/yuzu-emu/yuzu/assets/113856704/1c1b7dd1-eda6-4b27-998f-d71aa12f71f5)

### Reproduction Steps

I don't have another system to reproduce on. It started seemingly at random - I don't remember updating any drivers recently and I've disabled exclusive access - but leading up to this sound sometimes disappeared out of the blue.

I have reinstalled yuzu, wiping all my configs to no avail.

### Log File

[   0.189859] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.189874] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.239956] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.284883] Frontend <Info> yuzu\main.cpp:GMainWindow:382: yuzu Version: yuzu 1706
[   0.284973] Frontend <Info> yuzu\main.cpp:LogRuntimes:258: MSVC Compiler: 1937 Runtime: 14.38.33135.0
[   0.284978] Frontend <Info> yuzu\main.cpp:LogRuntimes:267: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.284980] Frontend <Info> yuzu\main.cpp:GMainWindow:398: Host CPU: AMD Ryzen 7 5800X 8-Core Processor              | AVX2 | FMA
[   0.284986] Frontend <Info> yuzu\main.cpp:GMainWindow:400: Host CPU Cores: 8
[   0.284993] Frontend <Info> yuzu\main.cpp:GMainWindow:403: Host CPU Threads: 16
[   0.285062] Frontend <Info> yuzu\main.cpp:GMainWindow:404: Host OS: Windows 11 Version 23H2 (Build 22635.3139)
[   0.285076] Frontend <Info> yuzu\main.cpp:GMainWindow:406: Host RAM: 47.92 GiB
[   0.285078] Frontend <Info> yuzu\main.cpp:GMainWindow:407: Host Swap: 31.00 GiB
[   0.285135] Frontend <Info> yuzu\main.cpp:GMainWindow:412: Host Timer Resolution: 0.5000 ms
[   0.317632] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'SystemVersion' (0x0100000000000809).
[   0.317645] Common.Filesystem <Warning> core\file_sys\system_archive\system_version.cpp:SystemVersion:17: called - Using hardcoded firmware version 'NintendoSDK Firmware for NX 12.1.0-1.0'
[   0.317663] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:94:     - System archive generation successful!
[   0.317670] Frontend <Info> yuzu\main.cpp:SetFirmwareVersion:4607: Installed firmware: No firmware available
[   0.358665] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Mario Kart 8.nsp has a different type (unknown) than its extension.
[   0.368287] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.6.0) applied successfully
[   0.378345] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Mario Kart 8.nsp has a different type (unknown) than its extension.
[   0.391148] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.6.0) applied successfully
[   3.296973] Audio.Sink <Error> audio_core\sink\cubeb_sink.cpp:IsCubebSuitable:379: Cubeb could not get min latency, it is not suitable.
[   3.318174] Audio.Sink <Error> audio_core\sink\sdl2_sink.cpp:IsSDLSuitable:262: SDL failed to open a device, it is not suitable. Error: WASAPI can't activate audio endpoint: 
[   3.318181] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:100: Auto-selecting the null backend
[   3.318697] Audio.Sink <Error> audio_core\sink\cubeb_sink.cpp:IsCubebSuitable:379: Cubeb could not get min latency, it is not suitable.
[   3.318970] Audio.Sink <Error> audio_core\sink\sdl2_sink.cpp:IsSDLSuitable:262: SDL failed to open a device, it is not suitable. Error: WASAPI can't activate audio endpoint: 
[   3.318976] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:100: Auto-selecting the null backend

### System Configuration

CPU: Ryzen 7 5800x
GPU/Driver: 6700 XT v24.1.1
RAM: 48 GB
OS: Windows 11 Pro 23H2.

**Comment by german77** [comment]
Restart the PC. 2 different engines couldn't pick up your audio device. I suspect this is windows fault or something is blocking yuzu to grab the audio output

**Comment by eZtaR1** [comment]
I've rebooted multiple times with the same result. Bitdefender doesn't seem
to be blocking anything either.
I've also uninstalled any apps that control audio on the system.

**Comment by Squall-Leonhart** [comment]
can you supply the devices speaker count configuration and sample rate in the legacy sound control panel properties dialog.

**Comment by Squall-Leonhart** [comment]
oh, this issue is not a yuzu bug, its a headset software issue.

**Comment by eZtaR1** [comment]
> oh, this issue is not a yuzu bug, its a headset software issue.

Could you elaborate on what makes you so certain? Yuzu was the only affected program.

I ended up formatting my machine, which fixed it.
