### ISSUE TITLE
VK_UNKNOWN_ERROR starting TOTK

### ISSUE THREAD

**Issue by r0wanda** [yuzu-emu/yuzu#12956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline latest, Early Access 4096

### Description of Issue

When I try to start TOTK, yuzu freezes and will not close unless I send it a signal (via the kill command). This does not happen on other games (to my knowledge), regardless of Opengl or Vulkan. When running yuzu from a terminal, it spits out the following error right when it freezes:
```
libpng warning: iCCP: known incorrect sRGB profile
terminate called after throwing an instance of 'Vulkan::vk::Exception'
  what():  VK_ERROR_UNKNOWN
```
The libpng warning doesn't concern me; it happens often when I run games and doesn't seem to affect anything.
I understand that VK_ERROR_UNKNOWN isn't a very helpful error message, and I would be happy to provide further information.

### Expected Behavior

TOTK starts normally

### Reproduction Steps

Compile yuzu from source using [these instructions](https://github.com/yuzu-emu/yuzu/wiki/Building-For-Linux) as of [this commit](https://github.com/yuzu-emu/yuzu/commit/4463ded603816eb100249faacf8ceb2c958977d1), or use Early Access version 4096. then attempt to start TOTK on Linux with Wayland using the specified nvidia drivers.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14204538/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5 5600X
GPU/Driver: NVIDIA GeForce RTX 3050, proprietary driver version 545.29.06 (tested with open source drivers as well to no avail)
RAM: 16gb
OS: Arch Linux (with Wayland)

**Comment by liamwhite** [comment]
Does it work with xwayland (eg QT_QPA_PLATFORM=xcb yuzu)?

**Comment by r0wanda** [comment]
No, it has the same result.

**Comment by liamwhite** [comment]
Install vulkan validation layers, and provide a log with the graphics debugging enabled in yuzu

**Comment by r0wanda** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14216065/yuzu_log.txt)

**Comment by liamwhite** [comment]
Enable the option to log to the console and capture the log output from the console - this log is truncated due to the crash

**Comment by r0wanda** [comment]
[log.txt](https://github.com/yuzu-emu/yuzu/files/14217733/log.txt)

**Comment by liamwhite** [comment]
Try with this option (Use Vulkan pipeline cache) disabled:
![image](https://github.com/yuzu-emu/yuzu/assets/9658600/2e573389-0e38-41f3-88af-814ba7eb2100)

**Comment by r0wanda** [comment]
Thanks, that seemed to fix it.
