### ISSUE TITLE
Trails

### ISSUE THREAD

**Issue by torion1974** [yuzu-emu/yuzu#12960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu android nce

### Description of Issue

Trails from zero and to azure stopped after 30 sec or so in nce.
In jit stopped after approximately 5 10 min

### Expected Behavior

Any start

### Reproduction Steps

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14209384/yuzu_log.txt)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14209422/yuzu_log.txt)

### System Configuration

CPU:sd 720g
GPU/Driver:adreno 618 turnip revision 16
RAM:6 gb
OS:miui 14 android 12

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
