### ISSUE TITLE
17.0.1 firmware not working

### ISSUE THREAD

**Issue by jimmy0012** [yuzu-emu/yuzu#12962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

latest main windows, android early access

### Description of Issue

I followed the yuzu guide to dump firmware and keys from my own switch using TegraExplorer to dump firmware and Lockpick_rcm to dump keys.

The keys work but the firmware does not seem to be working as mario kart 8 will not boot and the mii creator starts but can not load mii templates.

### Expected Behavior

Mario Kart 8 boots, able to load Miis

### Reproduction Steps

Use tegraexplorer to dump keys on a 17.0.1 switch. Import into yuzu. Attempt to start MK8 or Mii creator

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14213144/yuzu_log.txt)

### System Configuration

Odin 2 Android

**Comment by german77** [comment]
Please dump your keys with latest lockpick v1.9.11

**Comment by jimmy0012** [comment]
that worked thank you!
