### ISSUE TITLE
Yuzu app crashing randomly

### ISSUE THREAD

**Issue by Yuumaeshin** [yuzu-emu/yuzu#12976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu build 241

### Description of Issue

Yuzu app crashes every time for every game whatever I do on my Oneplus 11, used to work well but now randomly crash for many games, even pixel games. I tried several drivers with no success, games can boot, sometimes it doesn't crash but most of the times it crash.

### Expected Behavior

Not crashing anymore after booting the games

### Reproduction Steps

Just launch any game with any video settings

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14229833/yuzu_log.txt.old.txt)

### System Configuration

CPU: Snapdragon 8 gen 2
GPU/Driver: Adreno 740/Turnip
RAM: 8
OS: Android 14

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
