### ISSUE TITLE
[Android] Yuru camp have a nice day opening laggy

### ISSUE THREAD

**Issue by StevenBeach33** [yuzu-emu/yuzu#12971]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Android-222 and above

### Description of Issue

The opening of this game is bit laggy on 221 and below version, but its more laggy on version 222 and above

Comparison :
On 221 and below, fps is 40+, audio good, but video a bit laggy :
https://github.com/yuzu-emu/yuzu/assets/107557824/a6d887cd-f9bc-4141-9cf3-8d94bb864800

On 222 and above, fps 60, but video and audio more laggy

https://github.com/yuzu-emu/yuzu/assets/107557824/d1c55fb1-be19-4f19-beb6-5aca83ebe734

### Expected Behavior

Opening video has to be smooth like this :

https://github.com/yuzu-emu/yuzu/assets/107557824/46b1b5c7-e7ae-438c-92a0-cb392779eeb7

### Reproduction Steps

Just open the game

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14220154/yuzu_log.txt.old.txt)

### System Configuration

CPU:Snapdragon 855
GPU/Driver:Adreno 640/Turnip
RAM:6gb
OS:Android 11

**Comment by liamwhite** [comment]
Please identify the first build causing the issue

**Comment by StevenBeach33** [comment]
> Please identify the first build causing the issue

It's Android-222

**Comment by StevenBeach33** [comment]
Closed

Its become smooth on latest build
