### ISSUE TITLE
[Android] Official 270p Resolution 

### ISSUE THREAD

**Issue by yogiags86** [yuzu-emu/yuzu#12972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Hello, I hope you guys added the 270p resolution feature officially. This is a screenshot of a custom build at 270p. I don't think it's as bad as 180p, but it makes it a little lighter than 360p.

![Screenshot_20240209-201013](https://github.com/yuzu-emu/yuzu/assets/81731189/b62d7d60-5c09-445e-a05a-94ace2d46bbb)

![Screenshot_20240209-201005](https://github.com/yuzu-emu/yuzu/assets/81731189/348b0a4d-c76f-481f-bb29-ee57867b21e6)
ading Screenshot_20240209-200959.png…]()

![Screenshot_20240209-200959](https://github.com/yuzu-emu/yuzu/assets/81731189/bd0bfd70-ea81-4e1f-9ad0-ac28e74163ad)

### Why would this feature be useful?

Will make it slightly lighter than 360p (0.5). 😁

**Comment by FearlessTobi** [comment]
You already opened an issue for this and got told we won't implement it: https://github.com/yuzu-emu/yuzu/issues/12767.
