### ISSUE TITLE
Pokemon luminescent platinum possible memory leaks

### ISSUE THREAD

**Issue by mysticlapis** [yuzu-emu/yuzu#12983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Andriod 243

### Description of Issue

Frames drop to zero and game freezes

### Expected Behavior

Not that

### Reproduction Steps

Move to another area or moving in general 

### Log File

Can't find a way to send it I'll keep looking 

### System Configuration

CPU:idk
GPU/Driver:snapdragon 888/ latest turnip
RAM:8 gb
OS:andriod

**Comment by FearlessTobi** [comment]
Issue template is incomplete.
