### ISSUE TITLE
[android] add manual detection update function

### ISSUE THREAD

**Issue by cxsunflower** [yuzu-emu/yuzu#13015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

it is a very tedious thing to open the browser and enter github to download every day.

use github restapi to get latest yuzu release  

https://docs.github.com/zh/rest/repos/repos?apiVersion=2022-11-28#list-repository-activities

### Why would this feature be useful?

it is a very tedious thing to open the browser and enter github to download yuzu every day.

**Comment by FearlessTobi** [comment]
If you want regular automatic updates, please use our Play Store releases.
