### ISSUE TITLE
Auto-updater in portable mode

### ISSUE THREAD

**Issue by kathyrollo** [yuzu-emu/yuzu#13029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Is it also possible to have the auto-updater for portable mode?

### Why would this feature be useful?

A little quality-of-life improvement instead of manually downloading the ZIP file.

Also, let me know if this option already exists in portable mode and I totally missed it. Thanks!

**Comment by Squall-Leonhart** [comment]
updater can already be used with portable mode, its not recommended however.

**Comment by kathyrollo** [comment]
Hi @Squall-Leonhart , any particular reason why?

And out of curiosity, can you also share how?

**Comment by FearlessTobi** [comment]
Seems like this is already possible then.

Closing

**Comment by kathyrollo** [comment]
@FearlessTobi Not quite sure it is. @Squall-Leonhart just mentioned how to make Yuzu a portable instance (which is my current setup), but it doesn't really activate an auto-updater. You have to manually download the ZIP file every time for updates while in portable mode.

Hi @goldenx86 , are you able to clarify if auto-updater is present in portable mode?

**Comment by Squall-Leonhart** [comment]
The user folder turns the installed version Portable, and running the installer will allow you to update it.

Making the yuzu app embed an updater is another more problematic matter.

**Comment by kathyrollo** [comment]
@Squall-Leonhart I see. Dolphin and Cemu only come in portable mode and have auto-updaters. Perhaps Yuzu can be more complex.
