### ISSUE TITLE
Allow control remapping 

### ISSUE THREAD

**Issue by RHYTHM1125** [yuzu-emu/yuzu#13028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Yuzu is improving their performance and compatibility but they really should add a feature to configure control / control remapping for player 1 and player 2 and so on. It's a necessary option specially for an emulator.

### Why would this feature be useful?

It will help to use various controller as well as splitting and using keyboard for multiplayer

**Comment by german77** [comment]
Do you. even check for dupicates #11124
