### ISSUE TITLE
Monster Hunter Generations Ultimate Keyboard not working

### ISSUE THREAD

**Issue by JoJoelix** [yuzu-emu/yuzu#13039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1696 and on until current update

### Description of Issue

You cannot use the keyboard function in monster hunter generations ultimate from mainline build 1696 until the latest official release. The keyboard works on mainline 1695 and below, but with a slight visual glitch on the top of the screen as you can see in the attached ss
![Captura de pantalla 2024-02-17 143515](https://github.com/yuzu-emu/yuzu/assets/160329767/2a02186c-5724-4160-8463-ac4e41f15bc0)

### Expected Behavior

Expected behaviour: 
![Captura de pantalla 2024-02-17 143515](https://github.com/yuzu-emu/yuzu/assets/160329767/70ff6eb0-a1cc-4c6a-bb38-5aa7ec8f19ea)

Problem in current builds: https://discord.com/channels/398318088170242053/400106910231035904/1208377969463132190 

### Reproduction Steps

Press ZR to open the chat menu, then press - to open the keyboard, and the screen goes slightly dark for some seconds until it takes you back to the chat menu

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14318986/yuzu_log.txt)

sorry if log is sus but this is an issue affecting everyone i believe

### System Configuration

CPU: ryzen 5 3600
GPU/Driver: rtx 3060ti
RAM: 16gb
OS: windows 10

**Comment by JoJoelix** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14318991/yuzu_log.txt)

sorry i forgot to close yuzu after the issue happening, this is the proper log i guess

**Comment by galvin-SH** [comment]
I have also been having this exact same problem in MHGU.
## From my own log file
[   9.680053] Service.AM <Warning> core\hle\service\am\service\self_controller.cpp:GetLibraryAppletLaunchableEvent:130: (STUBBED) called
[   9.681894] Service.AM <Warning> core\hle\service\am\service\library_applet_accessor.cpp:GetIndirectLayerConsumerHandle:129: (STUBBED) called
[   9.685524] Service.AM <Info> core\hle\service\am\frontend\applet_software_keyboard.cpp:Initialize:56: Initializing Software Keyboard Applet with LibraryAppletMode=3
[   9.685539] Service.AM <Info> core\hle\service\am\frontend\applet_software_keyboard.cpp:InitializePartialForeground:247: Initializing Inline Software Keyboard Applet.
[   9.836476] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[   9.836911] Service.AM <Info> yuzu\applets\qt_software_keyboard.cpp:InitializeKeyboard:1605: 
KeyboardInitializeParameters:
ok_text=
header_text=
sub_text=
guide_text=
initial_text=
max_text_length=500
min_text_length=0
initial_cursor_position=0
type=2
password_mode=0
text_draw_type=1
key_disable_flags=0
use_blur_background=false
enable_backspace_button=true
enable_return_button=false
disable_cancel_button=false
[   9.837446] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:71: (STUBBED) called
[   9.859955] Debug <Critical> core\hle\service\am\frontend\applet_software_keyboard.cpp:operator ():351: Assertion Failed!
Unknown SwkbdRequestCommand=1128548942
[   9.860150] Service.AM <Warning> core\hle\service\am\frontend\applet_software_keyboard.cpp:RequestSetCustomizeDic:793: SetCustomizeDic is not implemented.
## System Configuration
Processor	AMD Ryzen 9 5900X 12-Core Processor               3.70 GHz
GPU   NVIDIA GeForce RTX 4060 Ti
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Pro
Version	21H2
OS build	19044.1766
