### ISSUE TITLE
[ANDROID] The walking dead: new frontier has issues rendering and badly overheats

### ISSUE THREAD

**Issue by tommy-sorce** [yuzu-emu/yuzu#13038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

252

### Description of Issue

Issues with rendering and overheating

### Expected Behavior

Proper rendering and less overheating 

### Reproduction Steps

Launch the walking dead: new frontier 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14318940/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 888
GPU/Driver: Turnip R17
RAM: 8gb
OS: Android 13

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests,

**Comment by tommy-sorce** [comment]
> This is an issue tracker for developers and not a support forum.
> Please use our Discord for support requests,

This is an issue, an issue with yuzu for the devs to hopefully fix. What people on discord are supposed to do ?
