### ISSUE TITLE
[PC] Dragon Quest Monsters: The Dark Prince naming issue & crashing

### ISSUE THREAD

**Issue by petitbambi** [yuzu-emu/yuzu#13033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1716

### Description of Issue

When scouting or synthesizing monsters the game uses Asian characters (unsure if it's kanji or another language) to name the monster despite the game being US version and all other text being in English. The keyboard is also set to English (US).
It often, but randomly crashes after accepting the input and asking me if I'd like to change my party or send the monster to 'The Monster Depot'. 
The naming issue happens with every single monster, sometimes leaving their name completely blank instead of using a different language.
The crashes happen randomly and I can synth or recruit the same monster after reloading without a crash. 
![asfaufshaoai](https://github.com/yuzu-emu/yuzu/assets/35592658/8f2a6241-583c-4b23-b60d-f4d2d516f8fe)
![asfguiasfoaif](https://github.com/yuzu-emu/yuzu/assets/35592658/549a8aed-f712-4690-954b-e4c4bb29b17b)
![jafoisfpo](https://github.com/yuzu-emu/yuzu/assets/35592658/7c01300c-06ab-420a-a65c-e3e058cf63b5)
![asfuhisfoj](https://github.com/yuzu-emu/yuzu/assets/35592658/876f1d05-5e2e-41b1-8d90-673cfb9db69d)
![afsoasfi](https://github.com/yuzu-emu/yuzu/assets/35592658/ecbfe018-4f2b-44cd-9da9-43489ca3d07f)

Game version is 1.0.4. with 11 DLCs 
When I started playing it in late January, neither issue was present. 
It also happens regardless of the game area /map I'm on. 

### Expected Behavior

When recruiting or synthesizing a monster its name should be the English name of the species.
After naming the monster, the game should let me add them to the party or send them to the monster depot without crashing.

### Reproduction Steps

Scout or synthesize any monster within the game. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14316134/yuzu_log.txt)

### System Configuration

CPU: Intel Core i7-10700K CPU @ 3.80GHz
GPU/Driver: NVIDIA GeForce GTX 1060 6GB, Version 546.33 Driver
RAM: 16GB
OS: Windows 10

**Comment by Squall-Leonhart** [comment]
disable  "Barrier Feedback loops" to resolve Pascal related crashing.

**Comment by Squall-Leonhart** [comment]
Believe this is regressed by https://github.com/yuzu-emu/yuzu-mainline/commit/c7e94e2175c02fe22846d89915b08d8b1802ef4f so 1714 should be the last to work fine

**Comment by Squall-Leonhart** [comment]
Regressed by #12756 @liamwhite

**Comment by liamwhite** [comment]
The garbled characters are because of utf8-utf16 conversion issues. That commit didn't regress anything, the keyboard applet still opens fine on latest master

**Comment by petitbambi** [comment]
I disabled "Barrier Feedback loops" and let it update to 1717, but just got another crash. Attaching the log for it as well. 
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14320023/yuzu_log.txt.old.txt)

I did download 1714 but saw that the text/naming issue was still there so I decided to try the newer builds with changed settings to see if that would resolve it, but seems not. I'll try playing on 1714 and see if that stops the crashes.

**Comment by liamwhite** [comment]
If you just want to play the game go to configure -> system -> applets and set keyboard to custom frontend while we figure out the conversion issues.

**Comment by petitbambi** [comment]
Thank you I'll try that 👍
I did experience a crash on 1714 as well so I'm sharing in case it's of any use in figuring out what the issue is 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14320143/yuzu_log.txt)

**Comment by cobrainmatter** [comment]
I am having the exact same problem with my steam deck

**Comment by Squall-Leonhart** [comment]
> The garbled characters are because of utf8-utf16 conversion issues. That commit didn't regress anything, the keyboard applet still opens fine on latest master

you had me so confused here because i'd already ruled out conversion and had started looking at it from the initial memory being garbage for some reason.
