### ISSUE TITLE
Dimensity 8100 supporr

### ISSUE THREAD

**Issue by GreDuNo** [yuzu-emu/yuzu#13043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I have see benchmarks of Mediatek Dimensity 1200 running Assassin's Creed games, but in my Poco X4 GT which has Dimensity 8100, Assassin's Creed games crashes. 

### Why would this feature be useful?

There is a lot of users who have the same processor and support for this cpu will be great for us mali users.

**Comment by FearlessTobi** [comment]
Closing, since this is an issue report and not a feature request.
For more support, please ask for help on our discord.
