### ISSUE TITLE
The Legend of Zelda: Link's Awakening, no rumble with XBox One controller?

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#13053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

ML 1717

### Description of Issue

As far as I can remember this game had vibration when got hit, using the shield, or charging power hit with the sword... Today I noticed is gone (?), no vibration anymore. With other games rumble work fine. Is it just me?
XBox One BT controller.

### Expected Behavior

Controller rumble effect hitting walls, when Link gets hit, using the shield etc.

### Reproduction Steps

Play the game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14320764/yuzu_log.txt)

### System Configuration

CPU: i7-8750H
GPU/Driver: 551.23
RAM: 32GB
OS: Win11 23H2

**Comment by Squall-Leonhart** [comment]
You remember wrong, it doesn't have haptics outside the fishing minigame.

**Comment by Hexaae** [comment]
Ah tank you, this got me nuts! 😊
