### ISSUE TITLE
Sudden FPS boost -- Game going way too fast

### ISSUE THREAD

**Issue by romantyke** [yuzu-emu/yuzu#13069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline Build - 8766303f9

### Description of Issue

I play Zelda Tears of the Kingdom extensively and daily. FPS was always capped at 30 and that was fine by me. The update we have this morning lifted that FPS cap, and I just can't do this. The game is at least twice as fast. Cutscenes are overlapping. Loading times also overlap, and the game kind of breaks after about ten minutes of gameplay. I tried to change settings, resetting them and changing plugins, resetting the pipelines and the cache... Nothing reverts back to 30 FPS. I was forced to revert to yesterday's build. I have a high end PC. I did NOT update the game (I use 1.0.0) and I do NOT use Mods and Cheats. The game is completely vanilla. I also use Docked mode. No ultra graphics settings are applied neither (such as 4K and UltraHD).

### Expected Behavior

For months the 30 FPS cap suits me just fine. It's sensibly as equal to Breath of the Wild. The game runs perfectly that way.

### Reproduction Steps

Just loading the game. Right as you enter the main menu, the FPS is capped at 60. It's running twice as fast from loading to closing. The game eventually overlaps and breaks. Sound is not faster, so it also overlaps.

### Log File

[   0.120757] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.120770] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.146922] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.214523] Frontend <Info> yuzu\main.cpp:GMainWindow:379: yuzu Version: yuzu 1717
[   0.214540] Frontend <Info> yuzu\main.cpp:LogRuntimes:255: MSVC Compiler: 1937 Runtime: 14.31.31103.0
[   0.214541] Frontend <Info> yuzu\main.cpp:LogRuntimes:264: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.214542] Frontend <Info> yuzu\main.cpp:GMainWindow:395: Host CPU: Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz | AVX2 | FMA
[   0.214547] Frontend <Info> yuzu\main.cpp:GMainWindow:397: Host CPU Cores: 8
[   0.214547] Frontend <Info> yuzu\main.cpp:GMainWindow:400: Host CPU Threads: 16
[   0.214665] Frontend <Info> yuzu\main.cpp:GMainWindow:401: Host OS: Windows 10 Version 22H2 (Build 19045.4046)
[   0.214677] Frontend <Info> yuzu\main.cpp:GMainWindow:403: Host RAM: 15.89 GiB
[   0.214677] Frontend <Info> yuzu\main.cpp:GMainWindow:404: Host Swap: 20.00 GiB
[   0.214731] Frontend <Info> yuzu\main.cpp:GMainWindow:409: Host Timer Resolution: 0.4960 ms
[   0.417142] Frontend <Info> yuzu\main.cpp:SetFirmwareVersion:4614: Installed firmware: NintendoSDK Firmware for NX 16.0.3-1.0
[   0.526378] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.21.0) applied successfully
[   0.530575] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Diablo III Eternal Collection [01001B300B9BE000][v1376256].nsp has a different type (unknown) than its extension.
[   0.538034] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Diablo III Eternal Collection [01001B300B9BE800][USA][v1310720].nsp has a different type (unknown) than its extension.
[   0.544046] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Diablo III Eternal Collection [01001B300B9BE800][USA][v1441792].nsp has a different type (unknown) than its extension.
[   0.547673] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.18.0) applied successfully
[   0.550819] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Mario Kart 8 Deluxe [0100152000022800][USA][v1179648].nsp has a different type (unknown) than its extension.
[   0.553820] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Mario Kart 8 Deluxe [Wave 1-6 DLC Unlocker][010015200002300x][USA][v1114112].nsp has a different type (unknown) than its extension.
[   0.557960] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File The Legend of Zelda Tears of the Kingdom [0100F2C0115B6800][USA][v131072].nsp has a different type (unknown) than its extension.
[   0.561208] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File The Legend of Zelda Tears of the Kingdom [0100F2C0115B6800][USA][v393216].nsp has a different type (unknown) than its extension.
[   0.565444] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.21.0) applied successfully
[   0.572442] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Diablo III Eternal Collection [01001B300B9BE000][v1376256].nsp has a different type (unknown) than its extension.
[   0.579742] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Diablo III Eternal Collection [01001B300B9BE800][USA][v1310720].nsp has a different type (unknown) than its extension.
[   0.585814] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Diablo III Eternal Collection [01001B300B9BE800][USA][v1441792].nsp has a different type (unknown) than its extension.
[   0.589302] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.18.0) applied successfully
[   0.595692] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Mario Kart 8 Deluxe [0100152000022800][USA][v1179648].nsp has a different type (unknown) than its extension.
[   0.598832] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File Mario Kart 8 Deluxe [Wave 1-6 DLC Unlocker][010015200002300x][USA][v1114112].nsp has a different type (unknown) than its extension.
[   0.607056] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File The Legend of Zelda Tears of the Kingdom [0100F2C0115B6800][USA][v131072].nsp has a different type (unknown) than its extension.
[   0.610382] Loader <Warning> core\loader\loader.cpp:GetLoader:259: File The Legend of Zelda Tears of the Kingdom [0100F2C0115B6800][USA][v393216].nsp has a different type (unknown) than its extension.
[   1.101049] Config <Info> frontend_common\config.cpp:WriteToIni:74: Writing Global configuration to: C:\Users\roman\AppData\Roaming\yuzu\config\qt-config.ini
[   1.103971] Config <Info> frontend_common\config.cpp:WriteToIni:74: Writing Global configuration to: C:\Users\roman\AppData\Roaming\yuzu\config\qt-config.ini
[   1.103971] Config <Info> frontend_common\config.cpp:WriteToIni:74: Writing Global configuration to: C:\Users\roman\AppData\Roaming\yuzu\config\qt-config.ini

### System Configuration

CPU: Intel Core I9-11900KF
GPU/Driver: Nvidia Gforce RTX 4090
RAM: 32 GB DDR 4
OS: Windows 10 Pro

**Comment by liamwhite** [comment]
already [addressed](https://github.com/yuzu-emu/yuzu/pull/13035/commits/940a71422e18b6305556d0efc2588a90f156ae04) and will be fixed in 1719
