### ISSUE TITLE
Can't select GPU in configuration -> Graphics -> Device

### ISSUE THREAD

**Issue by freejool** [yuzu-emu/yuzu#13061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 4146 and Mainline 1717

### Description of Issue

I have an intergrated GPU and an independent GPU

But I can only select intergrated GPU in configuration -> Graphics -> Device

<img width="1050" alt="Screenshot 2024-02-18 203739" src="https://github.com/yuzu-emu/yuzu/assets/39995589/da16377e-a460-46c7-8ab0-fa6aa2c527cf">
<img width="579" alt="Screenshot 2024-02-18 203811" src="https://github.com/yuzu-emu/yuzu/assets/39995589/15aa4b79-96ba-4bd6-86e1-bc5a68c35eab">

### Expected Behavior

two GPUs show up in the menu

### Reproduction Steps

I don't know.

Before I upgraded both yuzu and gpu driver everything's fine. maybe it's the driver?

does anyone with the latest driver can reproduce the issue?

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14322503/yuzu_log.txt)

### System Configuration

CPU: 13900K
GPU/Driver: RTX4090 551.52
RAM: 64G
OS: Windows 11 Version 22H2 (Build 22621.3155)

**Comment by Squall-Leonhart** [comment]
Is there a monitor plugged into the nvidia card?

**Comment by Squall-Leonhart** [comment]
You need to open the windows advanced graphics settings and set Parsec to use the nvidia one explicitly or set it in the parsec app.

**Comment by freejool** [comment]
@Squall-Leonhart thanks for reply

I have a monitor connected to gpu.

I am not using parsec remote control.

I uninstalled parsec driver and rebooted. The problem remains.

**Comment by Squall-Leonhart** [comment]
reinstall the latest  nvidia display driver, the drivers vulkan json registration has broken somehow.

**Comment by freejool** [comment]
resolved after reinstalling the latest nvidia display driver
