### ISSUE TITLE
[Android] Software Keyboard Continues to Hang and Crash

### ISSUE THREAD

**Issue by MassiveEntropy** [yuzu-emu/yuzu#13074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

android-256

### Description of Issue

titles which require entry from the software keyboard are not prompting the field for entry.
selection of the aforementioned input results in a crash or hang regardless of the title or config.

recently merged PR did not fix the issue.

![304480775-96486926-a050-4102-a411-0b51baca951e](https://github.com/yuzu-emu/yuzu/assets/114634824/370b2675-157c-4b6e-a225-8da23cb1a90d)
![304480832-58137d42-c7b4-408a-a118-8695f676fe68](https://github.com/yuzu-emu/yuzu/assets/114634824/92465f3a-571e-4549-82e1-06d1774b6c50)

### Expected Behavior

![304481064-d2c6481d-f531-4960-9604-b30eb6cc0916](https://github.com/yuzu-emu/yuzu/assets/114634824/6fdde8b5-3132-44c8-8a6a-ffa4c2b9a038)

### Reproduction Steps

text entry triggers the issue.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14326052/yuzu_log.txt.old.txt)

### System Configuration

CPU: Tensor G3
GPU/Driver: Mali G-715
RAM: 12GB
OS: Android 14

**Comment by liamwhite** [comment]
Fixed in 257 please confirm

**Comment by MassiveEntropy** [comment]
@liamwhite confirmed fixed as of 257 onwards
