### ISSUE TITLE
[Android] incorrect yuzu configuration

### ISSUE THREAD

**Issue by OceanSea1** [yuzu-emu/yuzu#13089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Last build 257

### Description of Issue

As per the object, every time you manually configure the application settings configuration file, the next time you restart the yuzu application, the -config.ini- file is rewritten to the default settings.

The yuzu application for Android is already equipped with a setting for resetting the config.ini in case you need to do so.

The problem of rewriting the config.ini file arises if it is modified manually through the editor.

The settings I use for the mobile application are the same as those I use for the Desktop application.

But while in the latter (Desktop) the config.ini settings are also saved in subsequent restarts of the program, in the case of the application (Mobile) this does not happen.

I attach a short log.

### Expected Behavior

Correct management of the config.ini file

### Reproduction Steps

install, start for the first time at default, close the yuzu application for Android.

Then manually edit the config.ini file through editor.

Restart the yuzu application for Android.

### Log File

[   0.000274] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.000286] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.005028] Config <Info> frontend_common/config.cpp:WriteToIni:74: Writing Global configuration to: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/config/config.ini
[   0.006482] Config <Info> frontend_common/config.cpp:WriteToIni:74: Writing Global configuration to: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/config/config.ini
[   0.012324] Frontend <Info> main/jni/native.cpp:Java_org_yuzu_yuzu_1emu_NativeLibrary_logDeviceInfo:642: yuzu Version: HEAD-2c3086dbc
[   0.012346] Frontend <Info> main/jni/native.cpp:Java_org_yuzu_yuzu_1emu_NativeLibrary_logDeviceInfo:643: Host OS: Android API level 34
[   0.012367] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:19: Device Manufacturer - nubia
[   0.012377] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:19: Device Model - NX769J
[   0.012384] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:19: SoC Manufacturer - QTI
[   0.012391] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:19: SoC Model - SM8650
[   0.013074] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:19: Total System Memory - 15.0GB
[   0.339387] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.1.0) applied successfully
[   0.364190] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.3.0) applied successfully
[   0.725942] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.1.0) applied successfully
[   0.779505] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.1.0) applied successfully
[   1.292261] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.3.0) applied successfully
[   1.384990] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:447:     RomFS: Update (v0.3.0) applied successfully
[   1.562464] Frontend <Info> main/jni/emu_window/emu_window.cpp:EmuWindow_Android:53: initializing
[   1.612072] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:996: Device doesn't support extension VK_EXT_depth_bias_control
[   1.612081] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:996: Device doesn't support extension VK_EXT_depth_range_unrestricted
[   1.612082] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:996: Device doesn't support extension VK_EXT_extended_dynamic_state3
[   1.612083] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:996: Device doesn't support extension VK_EXT_external_memory_host
[   1.612084] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:996: Device doesn't support extension VK_NV_geometry_shader_passthrough
[   1.612085] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:996: Device doesn't support extension VK_NV_viewport_array2
[   1.612086] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:996: Device doesn't support extension VK_NV_viewport_swizzle
[   1.612088] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:1058: Device doesn't support feature depthBiasControl
[   1.612089] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:1058: Device doesn't support feature leastRepresentableValueForceUnormRepresentation
[   1.612094] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:1058: Device doesn't support feature depthBiasExact
[   1.612111] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:1059: Missing required feature uniformAndStorageBuffer16BitAccess
[   1.612111] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:1059: Missing required feature uniformAndStorageBuffer8BitAccess

### System Configuration

CPU: SnapDragon gen 3
GPU/Driver: Qualcomm/Turnip 24 Revision 17 V2
RAM: 12 GB
OS: Android 14

**Comment by t895** [comment]
Make sure that you set both
```
<setting you want to change> = <your value>
<setting you want to change>/default = false
```

**Comment by OceanSea1** [comment]
> Make sure that you set both
> 
> ```
> <setting you want to change> = <your value>
> <setting you want to change>/default = false
> ```
No, the issue is not resolved.

Even though I was sure I had set both items in each settings, the problem persists.

Specifically, the values I try to set are the following:

- [Data%20Storage]
use_virtual_sd\default=false
use_virtual_sd=false (the yuzu application resets this value to true)

- [Renderer]
disable_shader_loop_safety_checks\default=true
disable_shader_loop_safety_checks=true (the yuzu application resets this value to false)

disable_buffer_reorder\default=true
disable_buffer_reorder=true (the yuzu application resets this value to false)

Therefore, the issue is not resolved.

**Comment by t895** [comment]
I just tested with those exact settings on my device and I could not reproduce the issue.

**Comment by OceanSea1** [comment]
> I just tested with those exact settings on my device and I could not reproduce the issue.

The device I own (and as can also be seen from the yuzu log) is the RedMagic 9 Pro 12GB/256GB Sleet model.

I also attach screenshots of the issue.
![Uploading Screenshot_20240220_175025.jpg…]()

**Comment by OceanSea1** [comment]
![Screenshot_20240220_175025](https://github.com/yuzu-emu/yuzu/assets/160583350/b9a81ed4-f056-42c2-97a9-a281937042f5)

**Comment by t895** [comment]
Whatever editor you're using is probably failing to write the changes to your config file. I can't really help with that. The only explorer that I use is MiXplorer but that's paid so I can't really recommend it for you to try.

**Comment by OceanSea1** [comment]
> Whatever editor you're using is probably failing to write the changes to your config file. I can't really help with that. The only explorer that I use is MiXplorer but that's paid so I can't really recommend it for you to try.

post scriptum: I noticed a new entry in the settings:

- [Linux]
enable_gamemode\default=true
enable_gamemode=true

Is this a value added recently in the new builds of the yuzu application for Android?

If not, it may then be the GameSpace service of the Nubia Android 14 build.

I'll try to make one last attempt, using the cable connection with the Desktop and working via editor from there.

I'll update the topic.

**Comment by OceanSea1** [comment]
This is the Desktop yuzu for Android modified config.ini file
![Screenshot (15)_1](https://github.com/yuzu-emu/yuzu/assets/160583350/2218f795-5999-484d-94d3-c25c08b1f1a1)

This is the config.ini file re-modified by yuzu application for Android:
![Screenshot_20240220_182407](https://github.com/yuzu-emu/yuzu/assets/160583350/02829fd2-86a7-4296-8403-a7f7e262cc0c)

There is something wrong.

**Comment by t895** [comment]
I just tried the same method you did and everything copied over fine. This must be an issue with your device.
Try these steps
- Make sure yuzu is closed before doing anything
- Copy your existing config file onto your PC
- Delete the config file using a file manager on your device
- Edit the config file and save it
- Copy the edited `config.ini` file to the Android/data/org.yuzu.yuzu_emu/files/config directory

**Comment by OceanSea1** [comment]
> I just tried the same method you did and everything copied over fine. This must be an issue with your device. Try these steps
> 
> * Make sure yuzu is closed before doing anything
> * Copy your existing config file onto your PC
> * Delete the config file using a file manager on your device
> * Edit the config file and save it
> * Copy the edited `config.ini` file to the Android/data/org.yuzu.yuzu_emu/files/config directory

What you suggest, is what I did.

But the problem seems to persist.

It could actually be the build of my device (Android 14) and its (damned) permissions on files and folders, including applications.

In any case, I hope that this issue in my particular case will be resolved with future updates to the yuzu application.

Anyway, thank you for reading and listening to me.
