### ISSUE TITLE
SM3DAS Super Mario Galaxy crash after a few hours of play then return to the launcher with the applet

### ISSUE THREAD

**Issue by FredericVincent0** [yuzu-emu/yuzu#13092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 4154

### Description of Issue

Super Mario Galaxy crash after a few hours of play then return to the launcher with the applet I don't know if this affects other sm64 sms games

https://github.com/yuzu-emu/yuzu/assets/114101261/edf6c1b6-3cf1-4d1e-8e8b-322f118c3cc3

### Expected Behavior

Super Mario Galaxy not crash after a few hours of play then return to the launcher with the applet

### Reproduction Steps

run SM3DAS launcher then run super mario galaxy play some levels then save and exit then exit with the launcher applet

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14345140/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5
GPU/Driver: Nvidia RTX GeForce 2060
RAM: 16GB
OS: Windows 11

**Comment by Squall-Leonhart** [comment]
You ran out of video memory.
