### ISSUE TITLE
Add emulation of joycons To use in a original switch (Yuzu android)

### ISSUE THREAD

**Issue by GithubUser559** [yuzu-emu/yuzu#13108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add a Joycons emulation to use in a original console. Like joycon droid 
 But without root thanks to the emulation

### Why would this feature be useful?

For cases where there are not enough joycons for each person on the original console.

**Comment by liamwhite** [comment]
yuzu cannot do this without rooting the device (and it's totally irrelevant for yuzu's purpose anyway) so this would be worthless for basically all users.
