### ISSUE TITLE
[android] Freeze 0 fps

### ISSUE THREAD

**Issue by Hacce87** [yuzu-emu/yuzu#13102]
### Issue on yzu 253 and newer version 

On yuzu 252 older working fine 
Sd 870 
![Screenshot_2024-02-21-13-31-02-031_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/93820786/828cd6e1-fdf2-443b-9ed0-e44226627ffb)
[Uploading yuzu_log.txt…]()
[Uploading yuzu_log.txt…]()

**Comment by K11MCH1** [comment]
You should post it here instead https://github.com/yuzu-emu/yuzu/issues/12897

**Comment by Hacce87** [comment]
!
