### ISSUE TITLE
[Android] Performance drop on all versions post 251

### ISSUE THREAD

**Issue by serpandrew** [yuzu-emu/yuzu#13101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 252+

### Description of Issue

Performance has dropped in all versions of Yuzu Android 252 and up on RP4 Pro. Tested each release and rolled back to 251.

Device is running in High Performance mode for all examples.

Examples:
Mario vs DK:
Handheld 1x resolution
Android-251 - Runs at full speed
Android 258 - Runs at 45-50 FPS with further drops

Super Mario 3D World: 
Handheld 0.75x resolution
Android-251 - Runs at full speed with occasional dips to 55 FPS
Android 258 - Runs at 40-45 FPS with further drops

Super Mario RPG
Handheld 0.75x resolution
Android-251 - Runs at 55-60 in busy areas, full speed when less busy
Android 258 - Runs at 35-45 FPS

### Expected Behavior

Full speed 60 FPS on Android-251

https://github.com/yuzu-emu/yuzu/assets/74064896/cce1a118-87ec-4750-88df-c9b054ad8af3

### Reproduction Steps

Reduced speed on Android-258

https://github.com/yuzu-emu/yuzu/assets/74064896/c4ce27b3-8342-4ade-9e51-1766be65f956

### Log File

[yuzu_log.txt.old[1].txt](https://github.com/yuzu-emu/yuzu/files/14354696/yuzu_log.txt.old.1.txt)

### System Configuration

CPU: Mediatek Dimensity 1100
GPU/Driver: G77 MC9@836MHz
RAM: 8GB LPDDR4x
OS: Android 13

More detail taken from log:
Host OS: Android API level 33
Device Manufacturer - Moorechip
Device Model - Retroid Pocket 4 Pro
SoC Manufacturer - Mediatek
SoC Model - MT8797Z/CZA
Total System Memory - 8.0 GB

**Comment by gidoly** [comment]
how does 257 runs?

**Comment by serpandrew** [comment]
> how does 257 runs?

Tested on every version from 252 up to 258. Just tried again and can confirm.

**Comment by faelana** [comment]
I would also add that there were no OTA updates between yuzu versions. This is how it is on super mario wonder on the same device:


https://github.com/yuzu-emu/yuzu/assets/46012160/d41a2b2d-2ca2-4b27-b45a-cdad9a6d32f0


https://github.com/yuzu-emu/yuzu/assets/46012160/dcc1ad65-c90f-4e9f-9380-a414ba21570d

**Comment by faelana** [comment]
> how does 257 runs?

@gidoly Hi, here is how 257 runs, there are no improvements


https://github.com/yuzu-emu/yuzu/assets/46012160/e8ae10d2-2d07-467e-bd23-1f75971b0cdd

**Comment by serpandrew** [comment]
> Try disabling vibration

Yep, that seems to have done the trick. I'm now getting same performance on 258 as I did with 251.

Controls > Player 1 > Vibration off.

**Comment by liamwhite** [comment]
Vibration perf should be fixed on 266+, please confirm

**Comment by serpandrew** [comment]
> ~Vibration perf should be fixed on 266+, please confirm~ Rather, it will be fixed in 267+

Tested on 267, confirmed the following are back to their usual performance as at 251 with vibration turned on:
- Mario vs Donkey Kong
- Tunic
- Super Mario RPG
- Super Mario 3D World

Thanks @liamwhite!
