### ISSUE TITLE
[Android] Crash when launching Tears of the Kingdom

### ISSUE THREAD

**Issue by mNJuTxntEr** [yuzu-emu/yuzu#13113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

android-259

### Description of Issue

I have Samsung Galaxy S22 Plus on Exynos 2200/Xclipse 920 and when i launch Tears of the Kingdom and it crash after 10 seconds

### Expected Behavior

The game should run

### Reproduction Steps

Get Samsung Galaxy S22 Plus with Exynos 2200/Xclipse 920 and try it

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14365446/yuzu_log.txt.old.txt)

### System Configuration

CPU: Exynos 2200
GPU/Driver: Samsung Xclipse 920 / Samsung Proprietary driver 2.0.0
RAM: 8GB + 4GB RAM Plus
OS: Android 14

**Comment by liamwhite** [comment]
you do not have enough memory. the minimum requirement is 12GB for this game.
