### ISSUE TITLE
[Android] Toggle mapping on Xbox-type controllers

### ISSUE THREAD

**Issue by fefo-dev** [yuzu-emu/yuzu#13110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The auto map feature still mantains the behavior of A = A and Y = Y, which makes the button mapping inverted. Tested a DS4 controller and it maps Circle as A and Cross as B, keeping the intended position of a Nintendo controller.

If you wish to keep the "gliph" style mapping please add a toogle to favor a Nintendo style mapping, otherwise the automap function kinda loses its purporse.

### Why would this feature be useful?

Mantaining the default button position of the console.

**Comment by BSoDGamingYT** [comment]
Can't you just...remap the buttons yourself? the emulator has custom button mapping.

**Comment by german77** [comment]
So the A button isn't the right most face button?

**Comment by t895** [comment]
Have you made sure to use the latest version of yuzu? I pushed a change to flip the AB/XY buttons in #13067 to accommodate for this.

**Comment by t895** [comment]
What device are you using? I have two other users that are getting the correct auto mapping (Switch layout)
I know that the Odin 2 will break auto mapping with the first connected controller

**Comment by fefo-dev** [comment]
Just tested build 259

DS4 - mapped as a Nintendo controller (already did on 258)
Mocute 61F (using Xbox profile) - mapped as a Nintendo controller (didn't do it on 258)
8bitdo SN30 Pro - mapped inverted (already did on 258)

Dunno how it works internally, but for reference all those controllers mantained Nintendo layout on other android emulators (Skyline, Snes9x, DraStic, etc).

**Comment by t895** [comment]
I'm not sure why you're seeing different mapping behavior between 258 and 259 because nothing changed between those two versions.

All I do to determine whether the buttons need to be flipped or not is check their vendor ID and flip based on a hardcoded list of vendors that need it.

**Comment by fefo-dev** [comment]
I'll do a more throught test in a few hours to check if I messed anything, but I'm certain that the Mocute controller had swapped inputs by default on 258 and older builds, even before mapping support.

The 8bitdo one can be dicey since it's a Xbox controller only in name - while it worked by default like a Xbox controller on Android it has no XInput support - https://www.8bitdo.com/sn30-pro-for-xbox-cloud-gaming-on-android/

**Comment by fefo-dev** [comment]
You were correct @t895, I thought I tested it on 258.

In that case the only controller misbehaving is my 8bitdo. I checked their readings with the controller diagnosis in MupenPlus AE and all three provided the same Xbox-style inputs, I wonder why this is the odd one.

**Comment by t895** [comment]
In that case, I could add it to the list of inputs we flip and send you a build to try. What buttons are flipped? Both A/B and X/Y or just one?

**Comment by fefo-dev** [comment]
> What buttons are flipped? Both A/B and X/Y or just one?

Both. The controller name is '8bitdo SN30 Pro for Android'.

**Comment by t895** [comment]
Try this build and let me know how it goes
https://drive.google.com/file/d/19qOqzVo19q6pIW_oXIykCfUUONmHd-DI/view?usp=sharing

**Comment by fefo-dev** [comment]
@t895 works as told, thank you for this.

Will be closing this issue since the feature is already there and other instances should just be bugs.

**Comment by t895** [comment]
Sounds good, this fix will be in the next yuzu-android build
