### ISSUE TITLE
Games list on main page constant and rapidly refreshing 

### ISSUE THREAD

**Issue by WhtSupremePizza** [yuzu-emu/yuzu#13118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1722

### Description of Issue

The screen keeps flashing and refreshing the roms list. Can't click games because they keep flashing. 

https://github.com/yuzu-emu/yuzu/assets/127848194/2b920b1b-0e6c-46c5-b01d-18296eb59b04

### Expected Behavior

A functional menu screen. 

### Reproduction Steps

You fixing it. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14373364/yuzu_log.txt)

### System Configuration

CPU: i7-10750h
GPU/Driver: 1660ti
RAM:16gb
OS:win11

**Comment by WhtSupremePizza** [comment]
Cool! Thank you.

**Comment by liamwhite** [comment]
Is this a problem in 1722, and not present in 1721? It seems like there might have been a change in your environment, given this repeating log message:
`[   3.324087] Frontend <Info> yuzu\game_list.cpp:RefreshGameDirectory:870: Change detected in the games directory. Reloading game list.`

**Comment by WhtSupremePizza** [comment]
I haven't had any recent changes. This issue just started after an auto
update this morning. I played fire emblem yesterday before work and it was
cool.

**Comment by liamwhite** [comment]
Okay, but does it happen in 1721, 1720, ...? We need to know where the regression point is so we can figure out what changed.

**Comment by WhtSupremePizza** [comment]
As I said before, the issue started this morning upon updating. It updated
the day before as well without issue. So it just started with the
most recent update.

**Comment by liamwhite** [comment]
I do not see any filesystem changes we have made between 1721 and 1722. Please recheck at least 1721 to confirm that the issue is not present. If you can't do this I can't fix the issue.

**Comment by WhtSupremePizza** [comment]
I just got home and opened it. It updated to 1723 and the issue has been
resolved. The menu is now static and appears to be  working as expected. I
do appreciate your time and patience.
