### ISSUE TITLE
Batman Arkham City game crashing in latest yuzu android builds

### ISSUE THREAD

**Issue by Eiklaps** [yuzu-emu/yuzu#13124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 261, 262 & 264

### Description of Issue

The game just start in opening screen & closes or sometimes crashes the yuzu app.

https://github.com/yuzu-emu/yuzu/assets/155968473/8dabbbbe-48eb-44ca-bf0c-93788996b9b7

### Expected Behavior

The game should work as previous versions like 260 & lower versions where you can go in game and able to play the game.

### Reproduction Steps

Just install Android version 261, 262 or 264 and play the Batman Arkham City game.
My yuzu app settings
Accuracy Level: Normal
Resolution: 0.75x
Vsync mode: FIFO on
Windows adapting filter: Bilinear
Disk shader cache: on
Asynchronous shader: on
Cpu backend: NCE
Driver: Mesa Turnip Adreno Driver V23.3.0-devel / Vulcan 1.3.255
GitHub version: Android 264
Rom version: 01003F00163CE000 USA/EUR
Game update Version: 1.0.2

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14382766/yuzu_log.txt.old.txt)

### System Configuration

CPU: Snapdragon 888
GPU/Driver: Adreno 660
RAM: 12GB
Storage: 256GB
OS: Android 13
Device: Realme GT2

**Comment by liamwhite** [comment]
Fixed in 265
