### ISSUE TITLE
Second player accourt never save progression 

### ISSUE THREAD

**Issue by Darknior** [yuzu-emu/yuzu#13120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1721

### Description of Issue

I have discover a bug that is really borring, if i m fine.

By the past i have not try so much games in local multiplayer, where we must log two player account to play. Most of games aure only using one.
But i have try finally "Minecraft Switch Edition" with my litle daugter, and each time the players 2, 3 and 4 losing all there stuff and level when we quit the game. Only player one has his stuff when we launch again the game.
And i ve think it was a Minecraft bug.

But now i have try a new game that use multi account "Borderland Prequel", the only one that i can launch a two gamer game without any crash. The one is now found second controller, the second is crashing.
This one works perfectly. 

We can quit and return to main menu, come back in game, the two player have Always all the good stats level and stuff .
But if we quit the emulator and come back, (like on Minecraft), the second player is reseted 😰
Level one and no stuff anymore...

### Expected Behavior

I think yuzu only save player one profile data and not for others 😰
Is there a way to fix it please ?

This bug make multi-player games impossible to use. Now i m level 5 my daugter only level 1 with nothing to fight, the game is too hard for her, its impossible for her to continue with me.

The only solution is to make yuzu recording player 2 3 and 4 datas please. Or i have miss underground some thing ?? Thanks

### Reproduction Steps

- Launch Borderland Prequel and choose your account
- Press START on title screen
- Press A on second controler to connect
- Choose the good player 2 profile
- Validate and continue game
- When the story is launched, you see the split screen
- Then you can validate the two player heroes for each one, and then you can see that player one has his charcater, ok. But the second onr is level 1 like if he launch the game for the first time ... all progression is lost.

### Log File

I habe no log file

### System Configuration

CPU: AMD Ryzen 9 5900HX 8 core
GPU/Driver: AMD Radeon 2100 MHz
RAM: 16 Go DDR4
OS: Arch Linux (Batocera)

**Comment by FearlessTobi** [comment]
I am sorry, we are unable to understand what this issue is about. And without log file it is almost impossible to diagnose it.

I would suggest you join our Discord and ask for support there. I think you will get better help there than here on GitHub.

**Comment by Darknior** [comment]
> I am sorry, we are unable to understand what this issue is about. And without log file it is almost impossible to diagnose it.
> 
> I would suggest you join our Discord and ask for support there. I think you will get better help there than here on GitHub.

What do you dont understand, i think i m clear.

I have open this issue because a team member has tell me to do it here.
Maybe i Can create a log file but it will change nothing. You must reproduce to test and understand how to fix the problem.

Yuzu only save game progression from player one and not other player. It a big problem for some aventure games to play in multi player local.

**Comment by Squall-Leonhart** [comment]
For the borderlands games on switch and playstation, this is a flaw in the game itself.

The second player must backout on the pause screen first in order to save their own progress, if the First player choses to quit only the first players data is saved.
