### ISSUE TITLE
[Android] Konosuba: Labyrinth of Hope and the Gathering Adventurers Plus

### ISSUE THREAD

**Issue by StevenBeach33** [yuzu-emu/yuzu#13134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android-256

### Description of Issue

Fps become 0 after a while playing game

### Expected Behavior

It has to playable 

### Reproduction Steps

Fps become 0 when playing <1 minutes

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14387504/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 855
GPU/Driver: Turnip
RAM: 6gb
OS: Android 11

**Comment by GayPotatoEmma** [comment]
Post this issue onto #12897

**Comment by FearlessTobi** [comment]
> Post this issue onto https://github.com/yuzu-emu/yuzu/issues/12897

Please do this. Closing.
