### ISSUE TITLE
女神异闻录5皇家版出现闪退

### ISSUE THREAD

**Issue by wp128** [yuzu-emu/yuzu#13138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

主线222或224以后左右。224可以在开高精度下运行，但会掉帧。

### Description of Issue

玩半个小时左右就会出现fps降至0或直接卡掉，由于难以预测准确时间所以没有视频。

### Expected Behavior

可以说在任何场景下都有可能发生这种情况，但是重新进入游戏，经历同样的地方则不会再有相同情况出现。我现在使用的是260，您可以将这款游戏挂机半小时左右实验一下。

### Reproduction Steps

使用默认设置和r17驱动

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14388940/yuzu_log.txt.old.txt)

### System Configuration

CPU:8+1
GPU/Driver:r17
RAM:18G  手机:一加ace2原神联名款
OS:安卓13

**Comment by liamwhite** [comment]
Duplicate of #12897

**Comment by FearlessTobi** [comment]
We also only accept reports in English.

**Comment by wp128** [comment]
> 我们也只接受英文报告。

yuzu v18 will not crash
