### ISSUE TITLE
Rewrite the vulkan code for Android version 

### ISSUE THREAD

**Issue by glucuphag** [yuzu-emu/yuzu#13148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Read bellow

### Why would this feature be useful?

Rewrite the vulkan code will improve Mali preformance,this will be a good thing because yuzu has a lot of mistakes in it will be better than waiting Mesa release a newer driver because not all of decices will support it

**Comment by GayPotatoEmma** [comment]
Ah yes let's rewrite literal years of work to satisfy a small minority of Yuzu users

**Comment by FearlessTobi** [comment]
Vulkan is a cross-platform API. There is no need to rewrite it for Android.

For tracking specific issues with yuzu android and mali, there are a lot of issues open already.

**Comment by goldenx86** [comment]
Ask ARM to produce real drivers, it's simpler and faster.
