### ISSUE TITLE
Tomb Raider I-III Remastered - Bottom half of screen invisible on handheld

### ISSUE THREAD

**Issue by GayPotatoEmma** [yuzu-emu/yuzu#13156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 268 - PC Early Access 4167

### Description of Issue

While playing the Tomb Raider I-III Remaster, the bottom half of the screen is cut off unless you're playing on docked mode. 

### Expected Behavior

You can see the whole screen regardless of what mode you're playing on

### Reproduction Steps

- Make sure Yuzu is set to handheld mode
- Load up the game

### Log File

Android log: [yuzu_log (2).txt](https://github.com/yuzu-emu/yuzu/files/14394962/yuzu_log.2.txt)
PC log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14394964/yuzu_log.txt)

![Screenshot_20240225-022811](https://github.com/yuzu-emu/yuzu/assets/153868115/1467525c-54a2-4a2c-ba2c-baa8d9412e08)

### System Configuration

CPU: Google Tensor G3 (Pixel 8 Pro)
GPU/Driver: Mali G715
RAM: 12GB
OS: Android 14 QPR3

CPU: Ryzen 7 5700U
GPU/Driver: AMD Radeon Vega 8
RAM: 16GB
OS: Windows 11 build 26040

**Comment by Squall-Leonhart** [comment]
This is addressed in https://github.com/yuzu-emu/yuzu/pull/13122 but as it regressed another game it is being reworked.

**Comment by GayPotatoEmma** [comment]
As #13122 has been re-implented this issue is now once again fixed. Thanks for the hard work byte!
