### ISSUE TITLE
Heavy perfomance drops on EA 4168 to 4170

### ISSUE THREAD

**Issue by llKraiD** [yuzu-emu/yuzu#13165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 4168 to 4170

### Description of Issue

The overall emulator performance is oddly worse on Early Access 4168 to 4170.
I've tested on tears of the kingdom and i couldn't reach the 60fps like i normally have. it dropped to 40ish for whatever reason.

![image](https://github.com/yuzu-emu/yuzu/assets/156055262/d04a05dc-5128-4163-9112-a0eb4536e499)
image from 4167

![image](https://github.com/yuzu-emu/yuzu/assets/156055262/f1ce51a9-f3d9-4ec0-922e-51505410e2e4)
image from 4170

### Expected Behavior

Reach the performance from Early Acess 4167.

### Reproduction Steps

Boot the game and check in-game fps.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14397850/yuzu_log.txt)

Save File.
[0100F2C0115B6000.zip](https://github.com/yuzu-emu/yuzu/files/14397855/0100F2C0115B6000.zip)

### System Configuration

CPU: i5 10400f
GPU/Driver: RTX 3050 (546.33)
RAM: 16GB
OS: Win 10 Enterprise

**Comment by german77** [comment]
Is mainline affected?

**Comment by llKraiD** [comment]
No. mainline 1726 is clean

**Comment by liamwhite** [comment]
Identify whether the performance issue is present on the respective builds for:
1. https://github.com/yuzu-emu/yuzu/pull/13159
    build: https://nightly.link/yuzu-emu/yuzu/actions/runs/8035349025?pr=13159
2. https://github.com/yuzu-emu/yuzu/pull/13018
    build: https://nightly.link/yuzu-emu/yuzu/actions/runs/8035462184?pr=13018

**Comment by shehzman** [comment]
Can confirm experiencing the exact same issue with a 5800X3D and an RTX 3080. Mario Wonder also stutters significantly more on these builds for me.

**Comment by sakuka47** [comment]
I tested version 4172, under totk 1.1.1 I'm fine at 60fps with other mods enabled.

Applets are confugured in "real" mode.

**Comment by llKraiD** [comment]
Closing it because its fixed on Early Access 4172

**Comment by iamnotkurtcobain** [comment]
> Closing it because its fixed on Early Access 4172

Is it fixed in Android too?

**Comment by liamwhite** [comment]
It was never an issue on android
