### ISSUE TITLE
[Android] Dragon Ball Z Kakarot crashes on Tooltips

### ISSUE THREAD

**Issue by K11MCH1** [yuzu-emu/yuzu#13167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

240+

### Description of Issue

https://github.com/yuzu-emu/yuzu/assets/81425424/64f049e9-fabd-4bbf-a301-0233e48982f5

The game crashes whenever a gameplay Tooltip appears. (Not controls tooltip)
This started to happen from build 240 and up.
Tested 200, 220, 230, 235, 238, 239. On these it dont happen.

### Expected Behavior

Not crash.

### Reproduction Steps

Reproducible at start of the game fighting the green dude with tentacles on head. Get him to orange HP and a tooltip pops up.
Also reproducible later on when you get to play the green fella.

### Log File

[kakaroot.txt](https://github.com/yuzu-emu/yuzu/files/14399436/kakaroot.txt)

### System Configuration

CPU: 8gen2
GPU/Driver: Turnip RC18 v3
RAM: 16gb
OS: OriginOS

**Comment by brujo5** [comment]
Fixed with v270 tested

**Comment by brujo5** [comment]
@K11MCH1 Can you upload the turnip r18 v3 here?  I would like to try something on my Poco F5, the previous versions of the r18 cause me some red/blue textures that even with gpu accuraccy high are not solved and I ended up using the r17 version.  so you can report it to pixelon or danilo
