### ISSUE TITLE
[android] Pokemon Violet crash after 20min gameplay

### ISSUE THREAD

**Issue by Rhouelyn** [yuzu-emu/yuzu#13162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 268

### Description of Issue

Pokemon Violet crash after 20min gameplay

### Expected Behavior

Pokemon Violet crash after 20min gameplay

### Reproduction Steps

Pokemon Violet crash after 20min gameplay

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14396705/yuzu_log.txt.old.txt)

### System Configuration

CPU: snapdragon 870
GPU/Driver: gmem latest 2-17-2024
RAM: 6gb ram
OS: android 13

**Comment by FearlessTobi** [comment]
You made no effort to fill out the issue template correctly. Closing
