### ISSUE TITLE
Pokemon legend: acreus crashes in exynos 

### ISSUE THREAD

**Issue by anildawadi** [yuzu-emu/yuzu#13182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 

### Description of Issue

pokemon legend acreus crash in exynos / mali when opening 

### Expected Behavior

Crash while opening game

### Reproduction Steps

Crash while opening game

### Log File

Crash while opening game

### System Configuration

CPU:Exynos 1280
GPU/Driver:
RAM: 8 gb
OS: Oneui 6
![maxresdefault](https://github.com/yuzu-emu/yuzu/assets/161447545/856ac091-e4f6-4800-ac60-e4293979e246)

pokemon acreus

**Comment by german77** [comment]
You expect that yuzu crash while opening the game so all is fine then. Also no log file.

You can reopen this issue once you fully follow the issue template.

**Comment by pacoa-kdbg** [comment]
Also 

https://github.com/yuzu-emu/yuzu/issues/11246
