### ISSUE TITLE
How's lawfare for a feature?

### ISSUE THREAD

**Issue by phukyuzu** [yuzu-emu/yuzu#13189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Yuzu Team long spit on Windows 7 hold-outs who refused regressive spyware like 10 or 11 just to use your emulator. You guys didn't just discontinue customer support, like Ryujinx which still works. You went out of your way to sabotage operation of Yuzu on 7, making small changes you knew broke compatibility without leaving former fallbacks in place, silencing discussions around this, and treating paying customers to your Patreon income like rabble or dirt to discard.

In its stubborn commitment to inoperability Yuzu abandoned me, so with nothing to lose from Yuzu I turned against Yuzu. I found 93 somewhat relevant Nintendo emails, and even more social media accounts. I sent many messages to inform them about Yuzu, hoping for a C&D. Like this one:

https://www.imgbly.com/ib/vo7jE0ChTt.jpg

Now I hear news of a lawsuit. Probably from my awareness effort, maybe not. If it's otherwise, you alienated so many people with such similar antagonism over time that someone disgruntled probably acted. This Reddit comment explains it:

https://www.imgbly.com/ib/BwNoOL2rJI.jpg

### Why would this feature be useful?

Every action has a reaction. You're not big enough to act too good for your customers, and should learn that if you insist on sabotage and causing unnecessary problems for people, sabotage and unnecessary problems might also find you.

**Comment by goldenx86** [comment]
Linux would have solved your issues just fine.
