### ISSUE TITLE
Qualcomm drivers crashing

### ISSUE THREAD

**Issue by Paulbrotha** [yuzu-emu/yuzu#13181]
### Issue

When i use qualcomm drivers my games are crashing and its needed to some games so it can be booted but other games can run with turnip driver not Qualcomm driver.How do i fix this? Yuzu Android Snapdragon712

**Comment by SleepingSnakezzz** [comment]
This is an issue tracker for developers, not a support forum. Please direct your support request to our Discord server or the Citra forums. Closing.

**Comment by Paulbrotha** [comment]
> Many of the problems with the official Qualcomm drivers are caused by incorrect or missing settings (see Vulkan extensions), too aggressive settings due to the Linux Kernel security framework (which varies in the development phase, from manufacturer to manufacturer) and above all;
> 
> Little will on the part of Qualcomm developers to support both their own drivers at the software level and with the related support extensions (see Yuzu, Citra, Vita3k, AetherSX2), and the OpenSource MESA-Turnips. (which incidentally and although not as complete as the official Qualcomm drivers, are definitely better than the latter)
> 
> So;
> 
> * The official Qualcomm drivers are deliberately buggy for Vulkan Extensions.
> * The opensource MESA-Turnip drivers, try to patch the official Qualcomm drivers and work better.
> 
> For clarifications and questions, just visit the official Qualcomm technical support forum:
> 
> https://developer.qualcomm.com/forums/software/adreno-gpu-sdk
> 
> And hoping that some expert technician will respond, but above all;
> 
> * act pragmatically to resolve official driver issues.

Alr thanks for the info
