### ISSUE TITLE
[Android] Strange and anomalous connection IPs

### ISSUE THREAD

**Issue by OceanSea1** [yuzu-emu/yuzu#13190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Last Buil 273

### Description of Issue

To the attention of the Team; Yuzu for Android.

From an in-depth analysis of the installation package of the latest build 273 of Yuzu for Android, there appears to be a probable inconsistency in the IP addresses assigned.

The IPs in question, for which and with which the Yuzu application for Android communicates with the cloud, are the following;

- Contacted IP addresses

IP Detections Country:

142.251.143.106
1/ 89

142.251.143.110
1/ 89

142.251.143.129
1/ 89

142.251.143.131
1/ 89

142.251.143.132
1/ 89

142.251.143.138
1/ 89

142.251.143.164
1/ 89

142.251.143.170
1/ 89

142.251.143.174
1/ 89

142.251.143.195
1/ 89

Therefore, additional control regarding assigned IPs is required.

### Expected Behavior

The GitHub repo installation package should be a clean package.

Unlike the playstore repo installation package.

Thank you.

### Reproduction Steps

Through analysis of the installation package.

### Log File

N/A

### System Configuration

CPU: Qualcomm SnapDragon Gen 3
GPU/Driver: Turnip 24 R17 V2
RAM: 12 GB
OS: Android 14

**Comment by german77** [comment]
Did you check the ip with whois? that range of ip seems to be just google domains. Doesn't seem yuzu related maybe telemetry from the google?

Since it's something we aren't in control there's no point on keeping this open. All builds come with source so feel free to build yourself.

![Screenshot_20240228-032648](https://github.com/yuzu-emu/yuzu/assets/5944268/dea3b5e1-eae2-47e4-a527-3ea9f02e4124)

**Comment by german77** [comment]
Oh so they are in the binary. We don't have any IP on our source at most the default for cemu hook that is localhost. The rest are resolved under the dns.

Again if google itself adds these sites as part of the building process we have no control, unless there's a cmake flag to disable them which I'm not aware of at the moment.
