### ISSUE TITLE
Mod Downloader wont register in Yuzu

### ISSUE THREAD

**Issue by Ahamil41** [yuzu-emu/yuzu#13199]
### Issue

I followed the tutorial to add the mod downloader into yuzu, and when I ran it all the mods downloaded. However, when I open yuzu and right click there are no mods available for any games. All my paths/directories are set correctly so I am not sure what I am doing wrong. And as far as I can tell the mods are all compatible with the patches I have installed as well.
![Yuzu Mod Downloader 3_1_2024 2_55_30 AM](https://github.com/yuzu-emu/yuzu/assets/161813784/e65bf55d-7848-454f-9dcd-1e3b4dd452b6)

**Comment by german77** [comment]
We don't have any tool called mod downloader. We can't provide support on stuff we don't manage. Please redirect this issue to the creators of the tool.
