### ISSUE TITLE
Is it real that Nintendo will sue Yuzu?

### ISSUE THREAD

**Issue by GithubUser559** [yuzu-emu/yuzu#13192]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

All

### Description of Issue

In that case I will save the yuzu .exe and apk on Archive.org

### Expected Behavior

.d

### Reproduction Steps

Archive Yuzu to avoid losing switch emulation 

### Log File

.d

### System Configuration

CPU:Helio G37
GPU/Driver:PowerVR GE8320
RAM:6
OS:Android

**Comment by spekkiodancer** [comment]
https://arstechnica.com/gaming/2024/02/how-strong-is-nintendos-legal-case-against-switch-emulator-yuzu/
