### ISSUE TITLE
crash issues

### ISSUE THREAD

**Issue by rahulYUV** [yuzu-emu/yuzu#13197]
### Issue

Is there an existing issue for this?
 I have searched the existing issues
Affected Build(s)
Last Mainbuild

Description of Issue
I use yuzu on batocera since a few year

Monday, i have install .wine game - i don't know if it's in relation

But now impossible to:

launch game - the loading bar begin and crash : no game
go to yuzu menu (F1): crash

**Comment by german77** [comment]
Please follow the issue template, provide a log and don't generalize the build number. If you can find the exact point on where it broke it will be really helpful.
