### ISSUE TITLE
[Linux, Android, Windows] Fearless heart eternal dream

### ISSUE THREAD

**Issue by OceanSea1** [yuzu-emu/yuzu#13204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Be like children, born into existence

Be like children who look at existence

Be like children, who listen to existence

Be like children who touch existence

Never let your smile be dimmed

Be like suns, like stars, like comets

Comets of smiles and hope

### Why would this feature be useful?

Be like the rock,

- continue your journey with firmness and pride.

Be like the air,

- continue your journey with the lightness and freshness of your imagination.

Be like water,

- continue your journey with the infinite creativity of your hearts.

Always be yourself,

Because it is the beauty of a dream that deserves to be followed.

Always follow your dreams.

Never let the uncertainties and doubts of life get you down.

Continue to believe in your dreams.

Because your dreams are ours too.

**Comment by SleepingSnakezzz** [comment]
Please refrain from shitposting GitHub issues.
