### ISSUE TITLE
Assertion Failed! Unimplemented ioctl (Cartoon Network - Battle Crashers)

### ISSUE THREAD

**Issue by yucelkandemir** [yuzu-emu/yuzu#1408]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2424946/yuzu_log.txt)
Hardware Specs :
Nvidia GeForce GTX 970
Intel I5-4670 @ 3.4Ghz
8 GB Of Ram 3200Mhz
Windows 10 Pro
The issue :
When you launch Cartoon network battle crashers, the game crash with the "Assertion Failed! Unimplemented ioctl" error

Log file attached.

**Comment by Hexagon12** [comment]
Please make a proper title with the game name included.

Also, try to use Canary, since Nightly doesn't include some features that would make this and other games boot.

**Comment by yucelkandemir** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2425041/yuzu_log.txt)

Trying canary, screen goes black and crash, new log attached.

**Comment by Hexagon12** [comment]
`[  49.582547] Render.OpenGL <Critical> video_core\renderer_opengl\maxwell_to_gl.h:ComparisonOp:293: Unimplemented comparison op=1235222912`

`[  49.582549] Render.OpenGL <Critical> video_core\renderer_opengl\gl_rasterizer.cpp:SyncAlphaTest:894: Alpha testing is not implemented`

`[  49.584088] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:445: API ERROR 1280: GL_INVALID_ENUM error generated. Invalid depth function.`

These are the 3 related lines. For the second one, @ReinUsesLisp would you care to reply?

**Comment by M-F-K** [comment]
The  Unimplemented comparison op=1235222912 is also present in the following two games: Timbleweed park, The Count Lucanor .

**Comment by Hexagon12** [comment]
Please retest the game with the latest Canary.

**Comment by Hexagon12** [comment]
Does the game work now?

**Comment by Hexagon12** [comment]
The game has been reported to be working now with the game going to the title screen with graphics. If there's any other problems, please open a new issue.
