### ISSUE TITLE
Main thread is never destroyed in tic-tac-toe when stopping emulation

### ISSUE THREAD

**Issue by CarlKenner** [yuzu-emu/yuzu#1413]
As far as I can tell, the main thread is not being destroyed in tic-tac-toe when choosing Stop Emulation from the menu. The main thread owns a shared_ptr to the main process, so the main process is not being destroyed either, which means the main heap is not being destroyed, which means it leaks 4 Gigabytes of heap memory every time you run the game (and a couple of other Gigabytes too that I haven't looked into). On my Windows 10 computer, trying to launch tic-tac-toe a second time causes an exception when it tries to malloc a second 4 Gigabytes on top of the original 6 Gigabytes.

**Comment by DarkLordZach** [comment]
This is a known issue. The current solution is to restart yuzu between games.

**Comment by jroweboy** [comment]
This should be fixed by https://github.com/yuzu-emu/yuzu/pull/1317

**Comment by CarlKenner** [comment]
I tracked down the issue: The thread owns a reference to the scheduler and the scheduler owns a reference to the thread, so neither get freed. But I see someone else already discovered that. lol
Yes, #1317 fixes this issue by changing the thread to use a weak ptr to the scheduler, which is what I was about to try. https://github.com/yuzu-emu/yuzu/pull/1317/commits/2af55f65890139b23a1e0bfd576e32821dbd634c

**Comment by Hexagon12** [comment]
This issue is solved with #1890 and #1901.
