### ISSUE TITLE
Yuzu crashes on loading any games

### ISSUE THREAD

**Issue by lightningboy95** [yuzu-emu/yuzu#1421]
Version: Nightly #1142 
Whenever launching a game yuzu will open a black screen then crash. Attached is the log. Crashes occur when loading both .xci and .nsp filetypes
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2432127/yuzu_log.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2432134/yuzu_log.txt)

**Comment by wladgrsantos** [comment]
Same still happens to me in any 3D games, as reported in closed issue #1333.

**Comment by FearlessTobi** [comment]
Currently most games only run in Nightly due to https://github.com/yuzu-emu/yuzu/pull/615.

Requesting to close.

**Comment by kilyan82** [comment]
for me the black screen doesn't happen, i only see in the bottom of yuzu where there is the fps counter that is doing something for a moment than crashes
