### ISSUE TITLE
AMD HW.GPU <Error> video_core\command_processor.cpp:operator ,Special buffer methods other than Bind are not implemented

### ISSUE THREAD

**Issue by honzapatCZ** [yuzu-emu/yuzu#1427]
Setup
CPU:Intel Core i7-7700
RAM:16GB DDR4
GPU#1:AMD Radeon RX 560
GPU#1:AMD Radeon R9 270
Drivers are up to date.
I tried different versions of yuzu(still same even the latest one), tried support on discord built own version with tweaked params still the same Still the same error.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2439015/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
This is just an unimplemented feature. At this time don't expect any game to run correctly or everything to be fully implemented. 

Requesting to close.

**Comment by honzapatCZ** [comment]
But the game wont display anything not even sound.
