### ISSUE TITLE
Add option to open folder as a game

### ISSUE THREAD

**Issue by mailwl** [yuzu-emu/yuzu#150]
This is implemented, but really annoing to get this via changing file name extensions and select "main" in subdirectory

**Comment by Gamedev1909** [comment]
Having the main file detected and added and having its name detected would save time im sure and would make things better for new users

**Comment by mailwl** [comment]
maybe better to select "main.npdm" metafile as main file of DeconstructedRomDirectory (i think it has info about architecture, armv7 or aarch64 of a game as well)

**Comment by Gamedev1909** [comment]
It does yes

**Comment by mailwl** [comment]
BTW, it's impossible to select the "main" file in open dialog on Mac OS, even with *.* filter. Looks like empty extension not equal to .* :)
Low priority
