### ISSUE TITLE
issue with opening yuzu for a second time

### ISSUE THREAD

**Issue by gugiak** [yuzu-emu/yuzu#1572]
I installed the latest version of yuzu not the zip file the exe installer. I launch for example the nightly  build but then when I close It I cant open it again then I open the canary build same it opens the first time and the second cant. when I try to open it a second time while updating it gets stuck at
 "wrapping up". I don't know how to fix this issue, if someone knows how to fix this issue pls help me.

**Comment by Hexagon12** [comment]
Please direct installer issues to this repo, thanks: https://github.com/j-selby/liftinstall/issues
