### ISSUE TITLE
Console ID creation dosn't work correctly

### ISSUE THREAD

**Issue by FearlessTobi** [yuzu-emu/yuzu#1585]
Console ID creation is stubbed at the moment in yuzu. This could cause some major issues in the future.

All that currently gets displayed for the console ID is either nothing at all - or 0x0 after regenerating.

**Comment by lioncash** [comment]
This is because system console ID generation is currently stubbed. See [here](https://github.com/yuzu-emu/yuzu/blob/master/src/yuzu/configuration/configure_system.cpp#L218)

**Comment by DarkLordZach** [comment]
Requesting to close -- while in citra a console ID was needed for online, in yuzu we can use the user ID
