### ISSUE TITLE
Input for the shoulderbuttons ZL and ZR only sees button push-in

### ISSUE THREAD

**Issue by HookedBehemoth** [yuzu-emu/yuzu#1629]
Currently the Input mapper can only register pushing in the triggerbuttons on a controller.
This means that Mario can only crouch but not stand-up after that.

Version: Canary 1425 | HEAD-4cf8008

Tried with Xbox One Controller with Xinput

**Comment by HookedBehemoth** [comment]
Nevermind I am retarded...

**Comment by HookedBehemoth** [comment]
I don't really know what caused the issue, but after I tried to press-in the tigger and let the calibration catch letting go of the trigger it worked as intended when redoing the normal calibration.

**Comment by mchtt** [comment]
Yes it could be easier for everybody to (axis) invert the input registered.

**Comment by Terricide** [comment]
My game is still doing it even though it has a + instead of -

**Comment by oblitum** [comment]
I got similar issue, I think this should be reopened.
