### ISSUE TITLE
Yuzu Canary #1433 SMO PR #1630

### ISSUE THREAD

**Issue by EmulationChannel** [yuzu-emu/yuzu#1631]
@bunnei Oky after the Worlds Rendering rendering still contains some bug visible flaws and menu SMO PR #1630 
![anotacao 2018-11-01 084444](https://user-images.githubusercontent.com/37957125/47863533-42e76180-ddd6-11e8-9c0b-2bb0eee53f8a.jpg)

**Comment by Yvar192** [comment]
What are the devs supposed to do with this? Obviously they know emulation isn't perfect yet, yuzu is ~1 year old.

**Comment by bunnei** [comment]
We are aware that there are still glitches, thanks for reporting but I do not believe we need an issue tracking this, as this is WIP and not even merged yet
