### ISSUE TITLE
Ultra Street Fighter 2: Random black screens

### ISSUE THREAD

**Issue by legend800** [yuzu-emu/yuzu#1642]
After playing for a while, the video will cut out (black screen) and the game becomes unresponsive, though the music is still playing. 

This issue has been reproduced by other users and has plagued the game since it got emulated. It's the only issue remaining before this game is fully playable.

Version: Canary 1440

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/2545534/yuzu_log.zip)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by Luffykun007** [comment]
@ Legend800 it does not start for me and gives this error what am I doing wrong?

![capturar2](https://user-images.githubusercontent.com/26087621/47965586-32cabe80-e030-11e8-8bb7-06b47f5b8071.PNG)

**Comment by legend800** [comment]
@Luffykun007 You have to use Canary builds. Please take troubleshooting to Discord, not here.

**Comment by Luffykun007** [comment]
@legend800 Okay but this is Canary build 1440.

**Comment by legend800** [comment]
Was able to do a full playthrough on my first attempt on latest master and did not observe any issues. Before I MIGHT get to Vega after a few attempts, but usually black screen halfway through arcade mode.
