### ISSUE TITLE
Brawlhalla for Nintendo Switch crash log #0152deb build 1443

### ISSUE THREAD

**Issue by BFCE** [yuzu-emu/yuzu#1647]
https://hastebin.com/pofemosowa.xml

game is fully 2D

**Comment by FearlessTobi** [comment]
Was this tested in Nightly or Canary? Also the log seems to be cut off.

**Comment by BFCE** [comment]
It has the same behavior on both, but iirec Canary was used.

The emulator will completely stop responding, which might explain the log cutoff. The game doesn't even open.

**Comment by Hexagon12** [comment]
Is this issue fixed?

**Comment by FearlessTobi** [comment]
@Hexagon12 As I already showed on Discord, Brawlhalla boots at least now.

**Comment by BFCE** [comment]
Brawlhalla now launches, and the in-game music is able to play. But absolutely nothing renders. 

https://hastebin.com/ezakimozol.cs

seems like 
`[  79.346485] HW.GPU <Error> video_core\gpu.cpp:CallPullerMethod:224: Special puller engine method Unk2c not implemented`
is the main problem

**Comment by Hexagon12** [comment]
Please upload a full log file.

**Comment by Hexagon12** [comment]
According to a user report, this game should be working fine now in the latest Canary. Please let me know if it doesn't for you.
