### ISSUE TITLE
Input: Analog Triggers

### ISSUE THREAD

**Issue by FreddyFunk** [yuzu-emu/yuzu#1659]
Analog triggers (from controllers like the XBOX controller) would not work due to a different range of their signals (from 0 to 255 on analog triggers instead of -32768 to 32768 on analog joysticks).

**Comment by greggameplayer** [comment]
there is a sort of same behavior on shoulder from xbox controller

**Comment by TheSIlentLink** [comment]
Same issue here on Ubuntu 18.10 with a 360 Controller

**Comment by FreddyFunk** [comment]
This seems to be an SDL bug:
https://github.com/libretro/RetroArch/pull/7444

**Comment by MysticExile** [comment]
This issue appears to have been fixed! If it is not, please open a new issue!
