### ISSUE TITLE
Yuzu nighty not working

### ISSUE THREAD

**Issue by kilyan82** [yuzu-emu/yuzu#1673]

**Comment by MysticExile** [comment]
We uh, can't really do much with this.

**Comment by FearlessTobi** [comment]
Requesting to close.

**Comment by MerryMage** [comment]
Insufficient information to reproduce.

**Comment by kilyan82** [comment]
what do you need?

**Comment by kilyan82** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2573813/yuzu_log.txt)
i found the log, could be helpful :P

**Comment by legoj15** [comment]
That is because on yuzu Nightly you are hitting an assertion and the program crashes. yuzu Canary disabled assertions so in this case Canary seemed like it was more stable

**Comment by kilyan82** [comment]
>           That is because on yuzu Nightly you are hitting an assertion and the program crashes. yuzu Canary disabled assertions so in this case Canary seemed like it was more stable

i see thx for the explanation, so for now is advisable to use canary
