### ISSUE TITLE
Graphical errors in Lego City Undercover

### ISSUE THREAD

**Issue by frykillr** [yuzu-emu/yuzu#1681]
Yuzu Canary 1480

LEGO city Undercover

gettings this message after loading a save game.
```[48029.661969] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:454: API ERROR 1281: GL_INVALID_VALUE error generated. Invalid texture format.```
![image](https://user-images.githubusercontent.com/7881098/48432158-9bf1b680-e741-11e8-9bab-1ee3525c7273.png)

and these errors at title screen.
```
[47710.535576] HW.GPU <Warning> video_core\renderer_opengl\gl_shader_decompiler.cpp:CompileInstr:3736: DEPBAR instruction is stubbed
[47710.781437] HW.GPU <Warning> video_core\renderer_opengl\gl_shader_decompiler.cpp:CompileInstr:1633: RRO instruction is incomplete
[47710.961556] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:454: API ERROR 1282: GL_INVALID_OPERATION error generated. <levels> is out of range.
[47711.044491] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:454: API ERROR 1281: GL_INVALID_VALUE error generated. Invalid texture format.
```

![image](https://user-images.githubusercontent.com/7881098/48432322-0acf0f80-e742-11e8-9993-fbaaa5c23a56.png)

also game is rendered in topleft of the screen.

![image](https://user-images.githubusercontent.com/7881098/48432603-dc056900-e742-11e8-9b81-896a620b9e47.png)

and doesn't go ingame after the loading screen.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2577410/yuzu_log.txt)

<meta name="titleids"  content="01003A30012C0000,010085500130A000,01002B6001364000">

**Comment by Hexagon12** [comment]
Does the issue still happen?

**Comment by frykillr** [comment]
Last time i checked the textures were still purple/black...and even slower then before..last yuzu was 1982.

But it was now full window..not a quarter window.

Also Lego Marvel Super Heroes 2 has weird textures

**Comment by frykillr** [comment]
here is on last yuzu i tried (2213)
![Capture](https://user-images.githubusercontent.com/7881098/56659282-b1f99080-666a-11e9-8b7a-9ac3244ebed4.PNG)

[LEGO City.zip](https://github.com/yuzu-emu/yuzu/files/3112206/LEGO.City.zip)

**Comment by Hexagon12** [comment]
Some of the more interesting lines:

* `Debug <Critical> video_core\renderer_opengl\gl_primitive_assembler.cpp:CalculateQuadSize:24: Assertion Failed! Quad count is expected to be a multiple of 4`
* `Debug <Critical> video_core\engines\maxwell_dma.cpp:HandleCopy:126: Assertion Failed!`

**Comment by MysticExile** [comment]
![legoooo](https://user-images.githubusercontent.com/30736337/80927370-c1430c00-8d9d-11ea-867c-47e3fbde5e0a.png)
This issue is still relevant today.

**Comment by FearlessTobi** [comment]
Could you get us an updated log? @MysticExile

**Comment by benderscruffy** [comment]
here is an updated log
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4605373/yuzu_log.zip)

**Comment by MysticExile** [comment]
![01003a30012c0000_2020-10-15_18-26-06-736](https://user-images.githubusercontent.com/30736337/96158572-f25e6580-0f13-11eb-825c-d2492a25e89d.png)
It's less bad but shadows are black just like in Splatoon 2 and the Skybox is also black.

**Comment by MysticExile** [comment]
![01003a30012c0000_2020-10-15_18-30-26-183](https://user-images.githubusercontent.com/30736337/96159086-89c3b880-0f14-11eb-8828-6fcd4e8bb661.png)
The broken shadows are gone using the 1.0.2 update, the skybox is still black.
Here is also an updated [log](https://github.com/yuzu-emu/yuzu/files/5386428/yuzu_log.txt)

**Comment by SpecialDarkwolf999** [comment]
this game is soft locking on vulkan.
Unimplemented texture format with pixel format=ASTC_2D_8X5_UNORM

**Comment by MysticExile** [comment]
> this game is soft locking on vulkan. Unimplemented texture format with pixel format=ASTC_2D_8X5_UNORM

@SpecialDarkwolf999 Please open a seperate issue for that.

**Comment by MysticExile** [comment]
This issue seems to have been resolved in the latest yuzu version (mainline 966 as of writing this). If you have any other issues with this game, please open a new issue with a log file.
