### ISSUE TITLE
Super Mario Odyssey crashes on boot | master-0072275d2

### ISSUE THREAD

**Issue by JetBr33ze** [yuzu-emu/yuzu#1720]
Yuzu version master-0072275d2
Super Mario Odyssey crashes on boot
To reproduce, boot Super Mario Odyssey
Log: https://drive.google.com/open?id=1JIV73jrXbW5oGT8Rh-TN2uqFYQRmWHxp

**Comment by ReaperOfSouls1909** [comment]
please only use canary builds from https://yuzu-emu.org/downloads/ using anything else gets you no support thanks

**Comment by JetBr33ze** [comment]
Ok

**Comment by Hexagon12** [comment]
Unofficial builds are not supported. Please test the games on the latest Canary releases for now.
