### ISSUE TITLE
Super Mario Odessey: Rendering issue on character's face

### ISSUE THREAD

**Issue by e88z4** [yuzu-emu/yuzu#1729]
Hi, 

I load Super Mario Odyssey with Canary build 1530. The character face has major rendering issue as shown below. 

![yuzu](https://user-images.githubusercontent.com/15828154/48679929-f5078300-eb63-11e8-9d74-25143e17701b.png)

My system is
Ryzen 5 2600, 16gb ram, Radeon HD7950 (amdgpu driver with Mesa 18.2), Debian Sid (unstable).

Let me know if more information is needed.

**Comment by niko1point0** [comment]
Rather than trying to start a new game, I highly recommend you download a completed game save. You will have significantly less glitches if you download a save profile with the game completed

**Comment by e88z4** [comment]
Let's close this issue for now. This seems to be affecting only GCN 1.0 architecture only. I had Tahiti Radeon 7950. 

When I upgraded my system recently to Polaris10 (RX580). This rendering issue didn't exist. This could be an issue with mesa or amdgpu because when I play Mario Kart 8 under CEMU emulator, I see similar behaviour in a few characters like being shown here.
