### ISSUE TITLE
error: unrecognized command line option ‘-fno-new-ttp-matching’

### ISSUE THREAD

**Issue by WovenTide** [yuzu-emu/yuzu#1745]
Hello,

I'm having an error trying to build Yuzu.
I'm on Linux Mint 18.3 and followed exactly the steps on the wiki. I installed all the dependencies, updated cmake to 3.12.4 and I get the following error when trying to build with GCC : 

https://i.imgur.com/uEdkR5i.png

I can help the best I can if you need anything from me but I only have very basic computer knowledge, I can't do anything fancy.
I strictly followed the build instruction, tried the "Building yuzu in Release Mode" way as well but got a similar issue.

Thank you for your work !

**Comment by FernandoS27** [comment]
you probably need to update gcc.

**Comment by WovenTide** [comment]
> you probably need to update gcc.

Thanks, that was exactly the problem.
I hope you have a nice day !
