### ISSUE TITLE
Common Errors when try to boot Puyo Puyo Tetris and The Binding of Isaac AB+

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#176]
## Yuzu Version:
Yuzu Canary Build 21328b3
## Issues :
When I try to boot Puyo Puyo Tetris and The Binding of Isaac Afterbirth+, these games boot but a bit seconds after two common error or more appears :

- Emulated Program broke execution
- Assertion Failed

**Comment by greggameplayer** [comment]
And these issues appears in the nightly build b26cdf1 too.

**Comment by ogniK5377** [comment]
They will appear in pretty much all commercial games as there's still not enough support for them. Assertion issues are most likely unimplemented services. We're constantly trying to work on support to get them running :)

**Comment by greggameplayer** [comment]
these errors not appears in a early version i'm gonna find out what this version is.

**Comment by greggameplayer** [comment]
In the nightly build d1b64cd there is no error but the game crash anyway.

**Comment by mailwl** [comment]
error most likely in function `android::Parcel::ipcSetDataReference` (looks like Nintendo uses Nvidia android code for parcel?). I can't setup debugging to figure out, what's wrong with parameters

**Comment by bunnei** [comment]
Closing this. We are actively working on the mentioned games and will provide an update when they are working.
