### ISSUE TITLE
Super Mario Odyssey freeze.

### ISSUE THREAD

**Issue by xwinno** [yuzu-emu/yuzu#1776]
When you enter in the guide menu of Super Mario Odyssey it freezes with a 100% speed and 60fps. This provoque that when you go the first time from Cascade Kingdom to Desert Kingdom, freezes also and you can't continue. Thanks!

**Comment by bunnei** [comment]
Thanks for reporting! We are aware of these types of issues and are actively working on it. As such, as don't need a Github issue to track this.
