### ISSUE TITLE
Pokemon lets Go BLACK SCREEN

### ISSUE THREAD

**Issue by valb21** [yuzu-emu/yuzu#1788]
Hi,

I'm sorry to bother you but i have a black screen when i launch pokemon lets go pikachu.
Someone has an idea ?
You can find my log here.

Thx ! =)
(it's a cut version of the log because the same message was spammed and the .txt was 50mo ! ^^)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2611702/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
We are aware of the issue. It should be fixed soon.

Requesting to close

**Comment by DarkLordZach** [comment]
You need to use a save. You can find them on our website: https://yuzu-emu.org/game/pokemon-lets-go-pikachu/

**Comment by valb21** [comment]
> You need to use a save. You can find them on our website: https://yuzu-emu.org/game/pokemon-lets-go-pikachu/

I'm using a save. I clicked on "Open Save data location" and i put the save from "https://yuzu-emu.org/game/pokemon-lets-go-pikachu/".

**Comment by valb21** [comment]
> We are aware of the issue. It should be fixed soon.
> 
> Requesting to close

Ok, it is not my fault ? I have not do anything wrong ?
