### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [yuzu-emu/yuzu#18]
Hi, I'm using Fedora 27.  Following error occurs.  What is "unicorn"?

In file included from /home/hoge/aho/yuzu/src/./core/arm/dynarmic/arm_dynarmic.h:11:0,
                 from /home/hoge/aho/yuzu/src/core/arm/dynarmic/arm_dynarmic.cpp:9:
/home/hoge/aho/yuzu/src/./core/arm/unicorn/arm_unicorn.h:7:10: fatal error: unicorn/unicorn.h: No such file or directory
 #include <unicorn/unicorn.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/core/CMakeFiles/core.dir/build.make:63: src/core/CMakeFiles/core.dir/arm/dynarmic/arm_dynarmic.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:617: src/core/CMakeFiles/core.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by Chainsawkitten** [comment]
Have you read the section in [Building for Linux](https://github.com/yuzu-emu/yuzu/wiki/Building-For-Linux) about Building Unicorn?

**Comment by tokumeiwokiboushimasu** [comment]
Oh, sorry.  I can build now.
