### ISSUE TITLE
Sonic Mania Plus is broken

### ISSUE THREAD

**Issue by bunnei** [yuzu-emu/yuzu#1816]
I spent a bit of time on this, and wanted to capture my notes somewhere:
* Sonic Mania Plus is currently broken in yuzu, we get an orange screen, the "Sega" audio, and then the game crashes
* The game was broken with https://github.com/yuzu-emu/yuzu/pull/1396 - Prior to this, it worked fine.
* We suspect the 1.04 update packed into the XCI version of this game is what's causing the problems. This results in the game sending some fairly different GPU command lists, among other things.
* At this point, we're not sure if the update application is broken, or if there are just other bugs in yuzu preventing it from working.

cc @DarkLordZach 

<meta name="titleids"  content="01009AA000FAA000">

**Comment by slashiee** [comment]
It's worth noting that (for me at least) running the digital version with update 1.04 causes an endless spam of unmapped memory reads.
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/2622707/yuzu_log.zip)

**Comment by benderscruffy** [comment]
can be closed as it goes ingame with the 1.04 update

**Comment by slashiee** [comment]
On Early Access it still crashes with single core.

**Comment by slashiee** [comment]
Sonic Mania Plus can now boot under single core and multicore.
<img width="1281" alt="2020-10-24_16-29-18_yuzu" src="https://user-images.githubusercontent.com/15317421/97095580-17d72780-1616-11eb-81dc-8b0650044835.png">
