### ISSUE TITLE
In Game Text Not working on Pokemon lets go.

### ISSUE THREAD

**Issue by burakbir** [yuzu-emu/yuzu#1828]
Hi all,

Im almost sure this has been reported but when I load up Pokemon lets go (both games) I seem to get this error where all the in game text is little blocks and is unreadable.

I am aware that the game is far from perfect and it has a lot of other bugs like pulling over 16GB ram at places and crashing every 3-4 mins with game speed and frames jumping to over 400-500. 

![pokemon lets go](https://user-images.githubusercontent.com/4460772/49257290-be661e00-f429-11e8-90c5-894964892b3c.jpg)

My question: Is there any work around for the in game text so that it is understandable even if it is turning the text red or something like that?

Kind Regards 
Burak

**System specifications**

Intel Core i7 6820HK CPU @ 2.70 GHz
GeForce GTX 980M on GM204-B GPU 8GB
32 GB DDR4 RAM
MSI GT72S 6QE Dominator Pro G

**Yuzu version**

Yuzu Canary 1654

**Comment by Hexagon12** [comment]
Please report this on the PR that causes the issue, since this is not merged yet - #1603.

**Comment by Narugakuruga** [comment]
Pull Request #1603

**Comment by DarthJahus** [comment]
I don't think closing this issue is the best thing to do, since the issue indeed concerns Yuzu and being closed will only misleading people looking for it / for a solution. However, I respect your way of doing things since it is your repository.
