### ISSUE TITLE
Yuzu closes before booting game

### ISSUE THREAD

**Issue by WolfHybrid23** [yuzu-emu/yuzu#1831]
The game doesn't even load, it just crashes the software, no black screen, no nothing. The log file is blank too. I am stumped how do I get my games to work, I have already dumped my keys and stuff and downloaded a rom off the internet and followed the instructions to get it working but still nothing... If it helps I am trying to load `Pokémon: Let's Go Eevee!`.

**Comment by RyudoGaming** [comment]
........ here is the problem, 

" I have already dumped my keys and stuff and downloaded a rom off the internet " 

Back up your game from your switch and it will work.

**Comment by DarkLordZach** [comment]
The github is not for issues like this -- please use the support channels in the discord.
