### ISSUE TITLE
Idea to improve performance on Low-End computers

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#1834]
This idea revolves around lowering the size of texture buffers, vertex buffers, and index buffers. This might result in decreased loading times, and increasing FPS in all games. This can be an option that can be toggled on/off, it will hurt visuals, but help performance

My computer only 8gb of DDR4 ram and 2gb of vram. Surprisingly, Super Mario Odyssey runs on the computer, maxing out ram usage at 6gb. On high-end computers with 16gb of ram, the ram usage usually goes up to 12gb. As a result, my computer is using virtual memory on the hard drive, lowering my performance.

One way to decrease texture buffer size is to have resolution of all texture files decreased when they are being read from ROM. For example, if an original texture in a Switch ROM is 1024x1024, rather than loading every pixel into a buffer, we could have a debug option where only 512x512 pixels are loaded into the buffer, or maybe even 256x256. There can be a percentage that is inputted from the user, that says they only want 50% of all original texture resolutions, or even 25%.

For Vertex and Index buffers, the same idea applies. In the PCSX2 emulator, they have a "skipdraw" setting where a certain number of polygons are skipped. I would like a debug option in Yuzu where a maximum number of polygons can be set, so that I could cap Yuzu to render only 200 polygons.

Of course, these are only suggestions. If this could be made a reality, buffer sizes will be significantly smaller, ram usage will be much lower, and low-end computers will be able to play Yuzu games without using Virtual Memory

Thank you!

**Comment by FearlessTobi** [comment]
I don't think it's acceptable to add such hacks to yuzu, regardless of what other emulators do.

**Comment by Hexagon12** [comment]
This is very much a hack and we are trying to avoid using such approaches as much as possible.

On top of that, we have 3 memory related bugs currently active on the emulator, so there's still a lot to improve.
