### ISSUE TITLE
Remove use of QKeySequence::Cancel 

### ISSUE THREAD

**Issue by VishalRocks** [yuzu-emu/yuzu#185]
I cloned the project yesterday and was running make when I encountered the following error:
[ 98%] Building CXX object src/yuzu/CMakeFiles/yuzu.dir/main.cpp.o
/home/vishal/yuzu/src/yuzu/main.cpp: In member function ‘void GMainWindow::InitializeHotkeys()’:
/home/vishal/yuzu/src/yuzu/main.cpp:190:68: error: ‘Cancel’ is not a member of ‘QKeySequence’
     RegisterHotkey("Main Window", "Exit Fullscreen", QKeySequence::Cancel, Qt::ApplicationShortcut);
                                                                    ^~~~~~
src/yuzu/CMakeFiles/yuzu.dir/build.make:438: recipe for target 'src/yuzu/CMakeFiles/yuzu.dir/main.cpp.o' failed
make[2]: *** [src/yuzu/CMakeFiles/yuzu.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:957: recipe for target 'src/yuzu/CMakeFiles/yuzu.dir/all' failed
make[1]: *** [src/yuzu/CMakeFiles/yuzu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

I have corrected the same by removing the use of Cancel in main.cpp and am mentioning the patch in the comments below. Please review the pull request.

**Comment by VishalRocks** [comment]
https://github.com/yuzu-emu/yuzu/pull/186

**Comment by greggameplayer** [comment]
Please close this issue

**Comment by VishalRocks** [comment]
Better solution in another PR..closing
