### ISSUE TITLE
Orange screen on SD Gundam G Generation Genesis

### ISSUE THREAD

**Issue by SeibaEX** [yuzu-emu/yuzu#1851]
I'm not quite sure if this is related to Sonic Mania Plus, but I get an orange screen when running this game. I have not patched it at all. This is consistent through several canary builds, latest build tried Canary Build - fa19a45, My CPU is an Intel i7-7700hq @2.8, graphics card is a GeForce GTX 1060 with Max-Q Design, and my RAM is 16 GB.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2642069/yuzu_log.txt)

**Comment by Salijour** [comment]
The game has the colored screen, but you can still get past menus into the game by pressing buttons, but the screen doesn't change. 
More detailed log posted and it shoots out this error:
[  18.226332] HW.GPU <Error> video_core\gpu.cpp:CallMethod:146: Special buffer methods other than Bind are not implemented
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/2658741/yuzu_log.zip)

**Comment by SeibaEX** [comment]
Okay, so it's more of "graphics isn't implemented yet", huh.

It slows down a lot at the title screen, I wonder what is attempting to emulate under the orange screen that's causing it so much trouble.

**Comment by SeibaEX** [comment]
Well, tried canary 1769 - 67d2e84. I have these errors to tell me what's going on. 👌

[  66.872806] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:497: API ERROR 1286: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.

[  66.887551] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl.cpp:IocCtrlEventWait:49: (STUBBED) called, syncpt_id=4294967295, threshold=0, timeout=-1, is_async=true

[  66.887839] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:SubmitGPFIFO:156: (STUBBED) called, gpfifo=115BD24398, num_entries=6, flags=104

[  66.887844] HW.GPU <Error> video_core\gpu.cpp:CallPullerMethod:224: Special puller engine method Unk2c not implemented


[  66.887845] HW.GPU <Error> video_core\gpu.cpp:CallPullerMethod:224: Special puller engine method Unk2c not implemented

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2713977/yuzu_log.txt)

**Comment by SeibaEX** [comment]
Well, here's an update:

Orange screen still here. Pressing X doesn't let me pass through menus anymore.

The start has this drop on me:

[   5.000758] Render.OpenGL <Critical> video_core\renderer_opengl\gl_rasterizer.cpp:RasterizerOpenGL:121: Sync fixed function OpenGL state here!

and then it loops through this:

[  15.391138] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl.cpp:IocCtrlEventWait:49: (STUBBED) called, syncpt_id=4294967295, threshold=0, timeout=-1, is_async=true
[  15.391328] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:SubmitGPFIFO:146: (STUBBED) called, gpfifo=115B862368, num_entries=6, flags=104
[  15.391415] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl.cpp:IocCtrlEventWait:49: (STUBBED) called, syncpt_id=4294967295, threshold=0, timeout=0, is_async=true
[  15.391428] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl.cpp:IocCtrlEventWait:49: (STUBBED) called, syncpt_id=0, threshold=21, timeout=100, is_async=true
[  15.391851] HW.GPU <Error> video_core\gpu.cpp:CallPullerMethod:218: Special puller engine method Unk2c not implemented
[  15.391854] HW.GPU <Error> video_core\gpu.cpp:CallPullerMethod:218: Special puller engine method Unk2c not implemented
[  15.424984] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl.cpp:IocCtrlEventWait:49: (STUBBED) called, syncpt_id=4294967295, threshold=0, timeout=-1, is_async=true
[  15.425261] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:SubmitGPFIFO:146: (STUBBED) called, gpfifo=115B862CB8, num_entries=6, flags=104
[  15.425495] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl.cpp:IocCtrlEventWait:49: (STUBBED) called, syncpt_id=4294967295, threshold=0, timeout=0, is_async=true
[  15.425580] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl.cpp:IocCtrlEventWait:49: (STUBBED) called, syncpt_id=0, threshold=24, timeout=100, is_async=true
[  15.425824] HW.GPU <Error> video_core\gpu.cpp:CallPullerMethod:218: Special puller engine method Unk2c not implemented
[  15.425826] HW.GPU <Error> video_core\gpu.cpp:CallPullerMethod:218: Special puller engine method Unk2c not implemented
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2897561/yuzu_log.txt)

**Comment by SeibaEX** [comment]
New version, new errors.

Ongoing: Orange screen still here. Pressing X doesn't let me pass through menus anymore.

canary 1948 - d2433e8

[   8.201942] Kernel.SVC <Error> core\hle\kernel\svc.cpp:MapSharedMemory:1113: Region is not within the ASLR region. addr=0x00000008A5C04000, size=0000000000040000


[  10.540471] HW.GPU <Error> video_core\gpu.cpp:CallPullerMethod:218: Special puller engine method Unk2c not implemented
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2923462/yuzu_log.txt)

**Comment by Hexagon12** [comment]
According to multiple people, this issue should be fixed now. If it isn't, let us know.
