### ISSUE TITLE
Request: Multi-Thread Support

### ISSUE THREAD

**Issue by Ghostotakoi** [yuzu-emu/yuzu#1855]
I know is a lot to ask, this emulator has made awesome progress and is pretty young, but i have a fairly decent cpu i7-6700k 4.0GHz and 16gb ram and gtx-1060 6gb most of recent pc titles run mostly 60fps but SMO in yuzu run at 30-40fps but my cpu usage is like 40-58%. I know emulate a console require a lot of cpu for processing stuff, but multi-thread support will increase performance without have to buy a cpu of 800$. I know this require some time, that´s why this is just a request. And keep working hard, you guy are doing great!

**Comment by ReaperOfSouls1909** [comment]
this is not the place to request things they will add multithread when its ready or when they figure out how

**Comment by jroweboy** [comment]
The developers have plenty of experience profiling and identifying performance bottlenecks. Thank you for your interest, but I will be closing this issue as it doesn't really add anything that we don't already know.
