### ISSUE TITLE
Yuzu is not using my main (Fastest Core)

### ISSUE THREAD

**Issue by Ghostotakoi** [yuzu-emu/yuzu#1856]
Yuzu is not using my main (Fastest Core)
![screenshot_20181204003500](https://user-images.githubusercontent.com/20958581/49421160-bcb79580-f75c-11e8-9739-e38971436b26.png)

**Comment by ReaperOfSouls1909** [comment]
Than set affinity to that fastest core using task manager

**Comment by jroweboy** [comment]
yuzu isn't responsible for scheduling which core it runs on. As @ReaperOfSouls1909 mentioned, you can set the core affinity in windows. For more information, please search about core pinning on windows. As this is an issue tracker for yuzu and this is a question about operating system scheduling, I will close this issue. Thanks for your interest in the project!
