### ISSUE TITLE
Super Mario Odyssey Locking Up 

### ISSUE THREAD

**Issue by e88z4** [yuzu-emu/yuzu#1865]
yuzu Linux Version: Canary 1674  | HEAD-eec8043

How to reproduce the issue:
1. Load the game
2. Start a new game
3. Wait until Mario is about to jump for the first time after being woken up by Cappy
4. System locks up, hard reset is required. Log before system crashed is attached below. 

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/2647288/yuzu_log.zip)

I have tried several different combinations of various kernel and Mesa version. None of the combination below resolve the issue. 
Debian Sid (Ryzen 5 2600, Radeon RX 580)
Kernel 4.19.6 / 4.17.19 / 4.20-rc1
Mesa 18.2.6 / 18.3.0-rc5 / 19.0-development with amdgpu driver.

Let me know if I can help with more information and testing.

**Comment by corossig** [comment]
It seems to be a bug in Mesa/AMDGPU on Vega10 : [https://bugs.freedesktop.org/show_bug.cgi?id=105251](https://bugs.freedesktop.org/show_bug.cgi?id=105251)

**Comment by Hexagon12** [comment]
Closing, because this issue is not particularly related to Yuzu and is a driver bug. We cannot fix this issue.
