### ISSUE TITLE
Some textures deswizzle wrong

### ISSUE THREAD

**Issue by NWPlayer123** [yuzu-emu/yuzu#1869]
I'm using Canary 1680, head-5f7959a (since I assume that has the most recent fixes and such).
On it, some games have textures that are being deswizzled wrong. Easy ones to test with are Freedom Planet (has a few in the intro cutscene and the entire title screen), and ARMS Global Testpunch (I don't have the full game to see).
![screenshot_594](https://user-images.githubusercontent.com/3280345/49524501-1907db80-f869-11e8-831b-907e675ed560.png)
![screenshot_595](https://user-images.githubusercontent.com/3280345/49524502-1907db80-f869-11e8-927d-5837cf7d5dd2.png)

**Comment by Hexagon12** [comment]
Do the issues still happen on the latest Canary?

**Comment by NWPlayer123** [comment]
Fixed 👍 @Hexagon12 
![Screenshot_517](https://user-images.githubusercontent.com/3280345/56480851-400e2500-6479-11e9-8330-a0b2207ae4a4.png)
![Screenshot_518](https://user-images.githubusercontent.com/3280345/56480853-400e2500-6479-11e9-93e7-1048c90bf8e9.png)
![Screenshot_519](https://user-images.githubusercontent.com/3280345/56480854-400e2500-6479-11e9-84c7-c09a6868a0a1.png)
