### ISSUE TITLE
yuzu canary not work from release 1687

### ISSUE THREAD

**Issue by Nerboruto** [yuzu-emu/yuzu#1881]
tested on game Super Mario Odyssey
last working yuzu canary is 1686 for my setup
xeon x3220 ssee3 3.2ghz
8gb ram
fake nvidia quadro gtx 550 ti 1,5gb gddr5 driver 392.00

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum. Please use the yuzu Discord for support requests insteadf.

Requesting to close
