### ISSUE TITLE
stuck on checking for updates

### ISSUE THREAD

**Issue by shageboy** [yuzu-emu/yuzu#1884]
hello, please help me, im stuck one checking for updates as soon as i downloaded yuzu i tried re-installing it but that didn't work, im not sure what to do please help me ;(

**Comment by EtK2000** [comment]
Firstly, if you need help you don't post here.
Secondly, if you think it's an issue you need to supply more info (like logs).

**Comment by badmotherfunk** [comment]
Hi ! Same problem, did you solve it ? Any suggestions please ?

**Comment by Zeroksas** [comment]
I assume you are using installer and stuck on updating? It's probably problem on your PC. Have you try to download canary without using installer?

**Comment by Zeroksas** [comment]
https://yuzu-emu.org/downloads/

**Comment by badmotherfunk** [comment]
Thanks ! I have an other problem now... (maybe I have to create an other topic ?)

When I launch Yuzu I have an error message "Warning Missing Derivation Components" 
I create "keys" and "sysdata" folders with the title.key/prod.key and shared_font.bin files in "Roaming" but nothing change. I always have this error, do you have a solution to fix it please ?

**Comment by legoj15** [comment]
@badmotherfunk https://yuzu-emu.org/help/quickstart/ follow this guide and that popup will go away

**Comment by Zeroksas** [comment]
That guide kind of complicated. Better watch this: https://www.youtube.com/watch?v=nEv3bzhmnY4

**Comment by ReinUsesLisp** [comment]
@Zeroksas Your link had pirated content.

**Comment by Hexagon12** [comment]
The original issue has been resolved. Closing...

**Comment by jccaceres01** [comment]
> Firstly, if you need help you don't post here.
> Secondly, if you think it's an issue you need to supply more info (like logs).

Its not his problem from we, the developers, choose to put the release of our products  in the same place where we develop. Just you will have normal people asking things in the wrong place. Try to by nice.
