### ISSUE TITLE
Yuzu auto builder (AppVeyor) times out, causing building checks to fail

### ISSUE THREAD

**Issue by goedzo** [yuzu-emu/yuzu#1919]
It appears my PR fails building because it times out (taking more then an hour to build), however there are no actual building issues:
https://ci.appveyor.com/project/bunnei/yuzu/builds/21064685/job/942pa0t34040jbh9/messages

>Build execution time has reached the maximum allowed time for your plan (60 minutes).

My pr:
https://github.com/yuzu-emu/yuzu/pull/1910

Is it possible to improve / simplify the autobuild process, or increase the plan for the build? 60 minutes is quite a big time to build.

**Comment by MysticExile** [comment]
Closing this as we don't use AppVeyor anymore.
