### ISSUE TITLE
Handle amiibo application area

### ISSUE THREAD

**Issue by ogniK5377** [yuzu-emu/yuzu#1924]
Currently how we handle application area in amiibos is very wrong. We tell games we have an application area and we return wrong information, we need to find an efficient way of handling the application area. Should we limit it to per user? Should we allow the use of multiple application areas? Do we write it back to the amiibo file and handle the crypto or do we just store it unencrypted and not use keys at all. A proper solution on handling this needs to be worked out.

**Comment by FearlessTobi** [comment]
Getting a solid solution here is important for Citra too.

**Comment by DarkLordZach** [comment]
My opinion:
- Have a subfolder in yuzu/config called amiibo. Within, store the unencrypted application data in a .bin file named the unique identifier (first 8 bytes afaik)

If this is satisfactory, I'm down for implementing this.

**Comment by ogniK5377** [comment]
> My opinion:
> 
> * Have a subfolder in yuzu/config called amiibo. Within, store the unencrypted application data in a .bin file named the unique identifier (first 8 bytes afaik)
> 
> If this is satisfactory, I'm down for implementing this.

Seems like a good place but I disagree with it being in config, it might be nice to store it in yuzu/amiibo since config would get quite big if you're using a lot of amiibos.
