### ISSUE TITLE
Cave Story+ not booting 

### ISSUE THREAD

**Issue by 13yearoldADULT** [yuzu-emu/yuzu#1926]
- Build 1711
- Game shows up fine. When booting it starts with 0 speed 0 fps w/ a white screen
- Game tested: Cave Story+
- Specs:
i7 3770 @ 4.20GHz
GeForce GT 1030 2GB DDR4
Windows 10 Pro
1TiB HDD
- Other:
  - Re-Installed Drivers, other emus such as Cemu, Citra and Xenia work fine
  - PC is fine it never had hardware issues
  - Every yuzu build is like this
  - Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2699307/yuzu_log.txt)

  - Screenshot:
https://cdn.discordapp.com/attachments/453495401199304705/525319123513769996/unknown.png

P.S unban me from the yuzu discord server (@midget#9820) so i can get live help

**Comment by BSoDGamingYT** [comment]
Please stop submitting reports on an old version of the emulator. Cave Story+ is working perfectly on the latest Canary 1740.

![cave story canary 1740](https://user-images.githubusercontent.com/38402209/50292196-cb968b80-0470-11e9-835a-a68ba584a60e.PNG)

**Comment by Hexagon12** [comment]
The old versions of Yuzu may have had bugs that prevented certain games from working. Please get a new installer copy from our official website and updating to the latest Canary builds.
