### ISSUE TITLE
No video Linux Mint 19

### ISSUE THREAD

**Issue by dukenukemx** [yuzu-emu/yuzu#1932]
I compiled the latest Yuzu as per instructions using GCC and Debug Mode and the emulator starts up but when I run Mario Odyssey I get a frame rate number counter at the bottom right along with speed and frame but no sound and no video.  I can stop the emulation and that's it.  I'm running Mint 19 on a AMD FX 8350 and a Radeon Rx 470 with Oibaf PPA for graphic drivers.  I've gotten this to work on Windows 10.

**Comment by ogniK5377** [comment]
You need to compile in release mode

**Comment by dukenukemx** [comment]
I tried that too but same result.

**Comment by ogniK5377** [comment]
Do you have the no assertions PR merged? If you're compiling it yourself, you're most likely hitting an assertion

**Comment by Hexagon12** [comment]
You haven't cloned the Canary build, but Nightly. Canary is required to run games.

`git clone --recursive https://www.github.com/yuzu-emu/yuzu-canary`
