### ISSUE TITLE
Android/armv8 Support

### ISSUE THREAD

**Issue by friesoft** [yuzu-emu/yuzu#1962]
I know yuzu is still very new but I thought this may be a good fit.
With Android support I specifically think about the NVIDIA Shield TV. 
It has a NVIDIA Tegra X1 like the Switch, so I guess porting should be "easier" than emulating all instructions?

Any thoughts on this? Possible? Feasable?

**Comment by Narugakuruga** [comment]
Yuzu's CPU recompiler doesn't support ARMv8 atm.
And, the fact that the guest GPU and host GPU are the same won't benefits emulation speed as you thought.

**Comment by friesoft** [comment]
Okay, thanks for the information :) You may close this issue if you don't think anything will be done in this regard in the coming months/years :)

**Comment by Hexagon12** [comment]
This is not a issue on our part. Yuzu can in fact be compiled without dynarmic on ARMv8. However, if you want faster speeds than just 1-2 FPS, please make a issue on dynarmic's repo.

**Comment by BreadFish64** [comment]
I'm late to the party but yuzu also uses more GPU features than any phone supports. An Android port would be pointless because it would only run on the Shield TV if you're lucky.

**Comment by mailwl** [comment]
switch games can not be played as is on android, because of different OS.
like PS4 games can't be played on Windows, even if they both has same Intel processor

**Comment by BreadFish64** [comment]
I don't know how well virtualization works on arm, but orbital pretty much is running the entire PS4 software stack alongside windows using haxm. Obviously we're not gonna take the same approach, but it's not impossible in theory. @mailwl

**Comment by nex86** [comment]
> like PS4 games can't be played on Windows, even if they both has same Intel processor

PS4 is AMD, but I get your point, they're both X86_64.

**Comment by aecarvalho** [comment]
Now that Citra is finally on Android, I have much more anticipation for Yuzu on Android as well, having a Snapdragon 845 I think at least 10-15 FPS could be theoretically achievable and higher especially with more powerful SOCs coming up

**Comment by maxmadzz** [comment]
Now, is there any hope to reconsider the Android port?

**Comment by frost0512** [comment]
Now with Egg NS launch... Can we reconsider the hypotheses of an android port?
