### ISSUE TITLE
Feature Request: Alert user when compiling shaders

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#1963]
The RPCS3 (PlayStation 3) Emulator has a message in the corner of the screen that says “compiling shaders...” whenever asynchronous compilation occurs. Can Yuzu have this feature?

**Comment by fluffapparition** [comment]
This would especially help with knowing the reason for performance issues and how they may be fixed so yeah I'd like to see this

**Comment by Morph1984** [comment]
Fixed by #4273
