### ISSUE TITLE
[Feature Request] Implement Texture1DBuffer

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#1971]
Texture1DBuffer is required by Mario+Rabbids in order to render

<meta name="titleids"  content="0100E46003042000,010067300059A000,01002E500B0A0000,01002CC003FE6000,0100E66006406000,010057D006492000,0100EAE003A5A000,0100F15003E64000">

**Comment by Hexagon12** [comment]
* Needed for Starlink: Battle For Atlas
* Needed for Octopath Traveler
* Needed for Fire Emblem Warriors

**Comment by camd123** [comment]
any Update on this? Would be awesome to get rabbids working on Yuzu. I saw someone got it booted to the intro menu

**Comment by camd123** [comment]
Mario rabbids*

**Comment by FernandoS27** [comment]
it's implemented.

**Comment by camd123** [comment]
> it's implemented.

Oh cool, does that mean mario rabbids or the other listed games could work soon? I tried it again this morning and it crashed after loading a bit of the text. Thanks Fernando!
