### ISSUE TITLE
Request Multi Core Support

### ISSUE THREAD

**Issue by SpecialDarkwolf** [yuzu-emu/yuzu#1972]
Can you please add soon multicore support for more then 1 core for intel cpu’s and amd cpu’s
Thank you very much.

**Comment by FearlessTobi** [comment]
Yuzu already has multicore support. It can be enabled in the qt-config file. 

Requesting to close.

**Comment by SpecialDarkwolf** [comment]
can this be added to the yuzu option ?

**Comment by Hexagon12** [comment]
No, because it causes a lot of issues. Try it at your own risk.

**Comment by Luckymm21** [comment]
Just change the option "[Core]
use_cpu_jit = true
use_multi_core = true "
but the game does not start: p
