### ISSUE TITLE
emulador brake store pokemon evee

### ISSUE THREAD

**Issue by emuladorfan** [yuzu-emu/yuzu#1986]
issue pokemon when leave store make black screen emulador is brake not able make character move and sound is play

**Comment by chris062689** [comment]
Github Issues is not a support forum. 
Check our GameDB page on the website. These freezes are common. 
Please refrain from submitting Github Code issues and instead discuss on our forums or Discord.

**Comment by emuladorfan** [comment]
sorry about this i go discrod
