### ISSUE TITLE
SMO canary 1801 action guide crash

### ISSUE THREAD

**Issue by WeirdBob** [yuzu-emu/yuzu#1994]
Platform: windows 10 1809 Pro
Build: Canary 1801
Game: Super Mario Odyssey
 
Hi, 
in SMO the action guide was crashing when calling web_browser_view.page(). I had to add a qt.conf file in the yuzu folder to indicate the data path:
```
[Paths]
Data = resources
```
I don't know if this file should be added to the project or if there's another way to correctly reference QTWebEngine resource files.

**Comment by FearlessTobi** [comment]
We are aware of issues with the action guide. As the PR is not merged into Nightly yet, please report the bug there (https://github.com/yuzu-emu/yuzu/pull/1939).

Requesting to close.
