### ISSUE TITLE
Pokemon Let's GO-Match time against Snorlax (and rare pokemons) runs really too fast

### ISSUE THREAD

**Issue by Mickelator** [yuzu-emu/yuzu#1996]
when we have to figth Snorlax (I only tried Snorlax but I guess that it would be the same with others rare pokemon, mewtwo, etc...), there's a match time of 5 minutes. But, in Yuzu, the time goes really too fast! Instead of lasting 5 minutes, the fight lasts.... about ten seconds, and the pokemon can't be catch.
Else, the play time stays at 0m00s. It could be a clue...

**Comment by ExsertWizard** [comment]
The developers are aware of this issue since it has been reported countless times by other users.

**Comment by Mickelator** [comment]
oh ok sorry. In that case, juste take it as a reminder :)

**Comment by ikki84** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/1821
