### ISSUE TITLE
Kernel HLE is innacurate and may need a partial rework

### ISSUE THREAD

**Issue by TuxSH** [yuzu-emu/yuzu#2]
I have found multiple flaws in `kernel.h`, which are the following:

* `enum class HandleType` doesn't reflect the class hierarchy of kernel objects on the Switch
* `KReadableEvent` (sync object) and `KWriteableEvent` are not implemented
* "Domain" is not a kernel object and therefore has no place in there whatsoever
* Timer, Mutex don't exist anymore. ResetType should be deleted.
* `bool IsWaitable()`: all subclasses of `KSynchronizationObject` are waitable for, thus the switch case is innacurate: `KProcess` (state changed), `KClientPort` (port becomes available again), `KReadableEvent`  (event written) are waitable for, etc. See Switchbrew for a listing.
* `IsSyncable` should be `if(GetHandleType() == HandleType::Undefined) UNREACHABLE(); return GetHandleType() == HandleType::ClientSession` instead.

There could be some issues that I missed

**Comment by bunnei** [comment]
#137 partially addresses this:
* Domains are no longer treated as kernel objects, although there is still some logic in our kernel impl. to handle them - this needs to be refactored out
* `SendSyncRequest` is now just for `ClientSession`

**Comment by Subv** [comment]
The Mutex class has been removed as of #370

**Comment by bunnei** [comment]
Closing, these should be all addressed
