### ISSUE TITLE
complie sharder font cashe not is wrok poekmon lets go eeve

### ISSUE THREAD

**Issue by emuladorfan** [yuzu-emu/yuzu#2000]
issue complie sharder font cache yuzu emulador pokemon eeve

**Comment by Hexagon12** [comment]
You have provided zero information on the issue. No log files, no specs, no reproduction steps...

This issue is invalid.

**Comment by ExsertWizard** [comment]
Los desarrolladores de yuzu ya saben de estos problemas porque fue reportado un montón de veces por varios usuarios en GitHub y en el servidor Discord del emulador. Recuerda que yuzu todavía está en las primeras etapas de su desarrollo, y un montón de cosas y problemas pueden ocurrir que la consola nativa, el Nintendo Switch.
