### ISSUE TITLE
mario oddysey black box alway stick to screen

### ISSUE THREAD

**Issue by emuladorfan** [yuzu-emu/yuzu#2006]
is has black blob corner wihch stick to screen try can not remove is stay

**Comment by simontime** [comment]
Emulador Cache Speed Vulkcan Complie Best Sharder Yuzu Emulador.

**Comment by emuladorfan** [comment]
yes complie sharder cache ok but not issue i has it black box on screen is stick

**Comment by simontime** [comment]
Black Box Complie Vulckan Fix Yuzu Emulador Stick Gone

**Comment by emuladorfan** [comment]
tutorial complie vulckan fix for emulador ? if fix black box pls inform how complie for vulckan

**Comment by simontime** [comment]
Vulckan Complie Cache Yuzu Emulafor Not Here, You Wait Vulckan Black Box Stick Fix.

**Comment by R3Spected** [comment]
settings use_vulckan=true

**Comment by simontime** [comment]
Just to clear up any further confusion- no, I don't usually speak like an A-grade imbecile, but apparently that's the only way I can get this guy to understand a word I say.

**Comment by Narugakuruga** [comment]
Vulkan is not a panacea dude. Please don't spam in issue tracker.

**Comment by Yvar192** [comment]
Nca The Sharder Stay Oddysey Hader Yes Try Lets Sharder Sound Brake A Yuzu Store For Remove And If Yuzu Black Box Sometime Ok Can Is Poekmon Eror Lets Font Inform

**Comment by Yvar192** [comment]
Blob

**Comment by emuladorfan** [comment]
can pls eplain how complie vulkcan sharder is very dificulto for me

**Comment by R3Spected** [comment]
you CANT

**Comment by emuladorfan** [comment]
is pople explain fix issue in coment blow

**Comment by Yvar192** [comment]
Difficulo No Eror Blob Box Not Black Yellow ahahah Vulkcan FIx Yurzu frii Easi Try Enjoy Stick Sorry For Has Oddysey Evee Poekmon Brake

**Comment by ikki84** [comment]
@emuladorfan Please, close the issue since its invalid. Vulkan is not ready yet for use.
(Vulkan ainda não está disponível para uso.)

**Comment by Yvar192** [comment]
For A Please Alway On Blow Sorry Hader Vulckan As Hader Me Control ? Character Only Me Music Only Evee

**Comment by Hexagon12** [comment]
Please realize that some of us cannot even understand what are you trying to say. Please use a translator, like https://www.deepl.com/translator, or just type out your issue in your native language.
Also, these kinds of issues need to be reported in our Discord server and not here.

**Comment by Moonlacer** [comment]
This is the best GitHub issue of all time
