### ISSUE TITLE
Support RGB565 framebuffers

### ISSUE THREAD

**Issue by fincs** [yuzu-emu/yuzu#2011]
Currently yuzu only seems to implement support for RGBA8888 framebuffers. This breaks the recently released 2.0.0 release of libnx, which moved the software-rendered console implementation to RGB565 because it saves memory bandwidth.

Some testing on hardware revealed [some other formats](https://github.com/switchbrew/libnx/blob/master/nx/source/display/framebuffer.c#L15-L23) which are also supported by the Switch's compositor other than RGBA8888. Attached is a libnx console example that now exhibits broken behavior on yuzu.

[vt52-demo.zip](https://github.com/yuzu-emu/yuzu/files/2741914/vt52-demo.zip)

**Comment by greggameplayer** [comment]
@fincs test this #2016 please

**Comment by fincs** [comment]
Tested canary c5baa21 (which has #2016) merged; and the same issue appears.

**Comment by greggameplayer** [comment]
@fincs the change isn't in the canary for that moment

**Comment by greggameplayer** [comment]
it's BGRA8 which is in canary for now

**Comment by fincs** [comment]
Alright, I'll test when the next canary gets built.

**Comment by greggameplayer** [comment]
@fincs can you tell me other homebrews who use it in order to do some test ? it will be good

**Comment by fincs** [comment]
That's still not right. It should look something like this: 
![image](https://user-images.githubusercontent.com/581494/51150460-afff8480-1866-11e9-941e-057f43f994ae.png)

**Comment by ReinUsesLisp** [comment]
Closing. This has been addressed by #2793.
