### ISSUE TITLE
Segfault on loading games list

### ISSUE THREAD

**Issue by LordOfDragons** [yuzu-emu/yuzu#2015]
Version: Latest GIT version
System: Linux 64-bit, GenToo
Note: Happens with both latest canary (both Windows and Linux) and build from GIT sources

Run yuzu, then select game directory. Yuzu will instantly segfault:

Since GITHub does not allow attaching logfiles, I put it on my server: [https://rptd.ch/misc/debug/yuzu_crashlog1.txt](https://rptd.ch/misc/debug/yuzu_crashlog1.txt)

**Comment by LordOfDragons** [comment]
I looked into it a more in depth. I can now pin-point the exception. The culprit is:

FileSys::NSP::ReadNCAs (this=this@entry=0x7fff7c02aa80, files=std::vector of length 5, capacity 5 = {...})
    at /opt/games/emulation/yuzu/src/core/file_sys/submission_package.cpp:224

Here are the logs: https://rptd.ch/misc/debug/yuzu_crashlog2.txt

**Comment by LordOfDragons** [comment]
The bug is in the line "if (outer_file->GetName().substr(outer_file->GetName().size() - 9) != ".cnmt.nca") {". size() is an unsigned integer so if the size of the string is smaller than 9 the index becomes negative and because unsigned integer it actually becomes a huge index which throws out range.

I suggest changing the line 224 to read:
if( outer_file->GetName().size() < 9 || outer_file->GetName().substr(outer_file->GetName().size() - 9) != ".cnmt.nca") {

then the bug is fixed.

**Comment by DarkLordZach** [comment]
Thanks for the very helpful and detailed ticket! Sorry for not getting back to you sooner.

This should be addressed in #2430, which is slated to be merged soon.

**Comment by MysticExile** [comment]
It seems like this issue has been fixed. If this has not been fixed, please open a new issue. Thank you!
