### ISSUE TITLE
Request: Add a progress bar when is compiling shader ramdisk

### ISSUE THREAD

**Issue by Ghostotakoi** [yuzu-emu/yuzu#2026]
Could you Add a progress bar when is compiling shaders when you open the emulator. Might be a Qt progress bar in the native UI or something like that.

**Comment by jroweboy** [comment]
Thanks for the suggestion, please keep in mind that the disk shader cache is a work in progress and feature requests should be mentioned on that specific pull request. https://github.com/yuzu-emu/yuzu/pull/2021 As such, I'll be closing this issue.

As an aside, the feature is currently in progress and the prerequisite pull requests are already open. 

https://github.com/yuzu-emu/yuzu/pull/2025
https://github.com/yuzu-emu/yuzu/pull/2017
