### ISSUE TITLE
BlueScreen occurs sometimes when capturing, going to 8 bit zones and some areas in Super Mario Odyssey

### ISSUE THREAD

**Issue by vgisuruex** [yuzu-emu/yuzu#2027]
sometimes, capturing a fireball in luncheon kingdom the whole screen turns into blue. but some ui like coin counter works well. it also works well when using screenshot mode but turns blue again when leaving it. this happens for many captures. but not for all. i got the blue screen in metro kingdom, sand kingdom too.
my yuzu canary version is 1823. here's a screenshot:
![image](https://user-images.githubusercontent.com/44421940/51219959-414f2380-1959-11e9-9579-7e2efc18bc99.png)

**Comment by ExsertWizard** [comment]
There's a workaround: play the game in docked mode

**Comment by vgisuruex** [comment]
change the controller type?

**Comment by vgisuruex** [comment]
Thank you so much!. it works perfectly.
