### ISSUE TITLE
Controllers support broked

### ISSUE THREAD

**Issue by NitroBAY** [yuzu-emu/yuzu#2028]
Hello,
Controllers used to work until like a week ago.
I can bound keys to keyboard an then my game responds accordingly to my input (Mario Odyssey is the only game I have) however when I bound keys to my xbox one controller (wireless) the game doesn't respond to my input. However the game definetely does recognize my controller as I can set bind keys to my controller's keys as keys got detected in the configuration screen.
I restarted the app tried undocked/docked I have version 1824 and it didn'(t work last version but version before that things worked just fine.
BTW there are multiple youtube video pretending yuzu supports super smash bros (that very very unfortunately it does not support yet, soon I hope ?) and rederecting people who want same to this link "http://cloudbox-md.com/-B4yg" like this video https://www.youtube.com/watch?v=djLP8lxc3IA there are other like this one all rederecting to that same fishy link.

**Comment by DarkLordZach** [comment]
I can confirm that link is definitely fake, and policing youtube for fakes is not our business (you can report the video, but you're at the will of youtube)

As for the controller issue, what was the exact last canary version that worked for you?

**Comment by hax4dazy** [comment]
He is right i also have the same problem. Yuzu wont actually bind the keys to the keys that i have specified. As for the latest build that worked i have no clue i think it was like a month ago that it still worked.

**Comment by NitroBAY** [comment]
I can't remember which version work but other users on Reddit report the same problem.

**Comment by DarkLordZach** [comment]
Again, I need to know the exact build numbers so I can diagnose this.

**Comment by NitroBAY** [comment]
Hello,
So I've been go through each version (https://github.com/yuzu-emu/yuzu-canary/releases) and I noticed they all work but then I relaunched 1824 (last version) and I noticed SECOND time it is launched only keyboard will work not controller

**Comment by NitroBAY** [comment]
Well after support broke with second time I launched 1824 I could not use controllers on ANY version (I went back as far as 1810).
I would need to redo everything but launching this time twice every version. Do @DarkLordZach you have a controller to test for this regression or are you only testing with keyboard ?

**Comment by NitroBAY** [comment]
@hax4dazy I found a workaround you go to settings => controls => custom => pro controller and you set bind your controller's keys to virtual controller's keys

**Comment by JOHN30011887** [comment]
Controllers need work yet anyway, in mario odyssey the action guide doesn't seem to work using any controller, got to switch to kb/m

Also in that game the vibration doesn't work so you cant find hidden items that require you to feel for the vibration

**Comment by SputnikKaputtnik** [comment]
I can confirm this is still an issue with all the latest canary builds up to the (ATM) current 1888. controller buttons and axes for my 360 controller as well as my ds4 get recognized in the settings, but in none of the games. Instead the default keyboard keys still function. This is a new bug that must have crept up in January 2019, it worked fine for me in older builds. Let me know if I can be of any further help to circle this bug. I can provide any logs or dxdiag or whatever.

**Comment by NitroBAY** [comment]
@SputnikKaputtnik did you try my workaround 

> settings => controls => custom => pro controller and you set bind your controller's keys to virtual controller's keys

**Comment by SputnikKaputtnik** [comment]
@NitroBAY Your workaround works, thank you! But nevertheless, this should be fixed.

**Comment by MysticExile** [comment]
It appears as though this issue has been fixed. If it has not been fixed for you, please open a new issue.
