### ISSUE TITLE
Super Mario Odyssey can't warp to checkpoints

### ISSUE THREAD

**Issue by vgisuruex** [yuzu-emu/yuzu#2029]
i tried to warp to a checkpoint but it doesn't work. it can't be selected. but i did it in lake kingdom days ago.please help! also i'm using canary 1823
![image](https://user-images.githubusercontent.com/44421940/51289998-724a5980-1a28-11e9-8352-7017f50a2cd2.png)

**Comment by ExsertWizard** [comment]
It only works for keyboard atm. It doesn't work for controllers because the emulator is missing deadzone implementation which is why analog stick drifting is noticeable on the map and therefore you can't properly select a checkpoint.

**Comment by vgisuruex** [comment]
anyway to assign two keys to one?

**Comment by vgisuruex** [comment]
Thank you very much for telling me, i assigned the analog axis as buttons. again thank you very much!

**Comment by HotShot0** [comment]
Can you help me too as I'm facing the same problem.

**Comment by albfan** [comment]
I can confirm adding a deadzone to analog axis it is able to select checkpoints

**Comment by jread444** [comment]
Is it possible to do this in Yuzu? 

I don't see it in controller configuration and a nube
