### ISSUE TITLE
CMake Error on Mac

### ISSUE THREAD

**Issue by aaronliu0130** [yuzu-emu/yuzu#2030]
I'm trying to build yuzu on mac. Cmake errors.
Logs:
[CMakeOutput.log](https://github.com/yuzu-emu/yuzu/files/2767949/CMakeOutput.log)

[CMakeError.log](https://github.com/yuzu-emu/yuzu/files/2767943/CMakeError.log)

**Comment by Hexagon12** [comment]
Mac OS is unsupported. You will not be able to run Yuzu because Apple has deprecated OpenGL support.
