### ISSUE TITLE
Can't launch up nintendo switch roms

### ISSUE THREAD

**Issue by B1ackydecatty** [yuzu-emu/yuzu#2037]
I got this issue when i tried play a game 
![howdoifixthisissue](https://user-images.githubusercontent.com/45589944/51423606-bcd0ff00-1bfd-11e9-9588-9ccae3e5e555.PNG)
how to do fix this issue?

**Comment by Jack-Rickwood** [comment]
@B1ackydecatty @harshu1205 Try updating your gpus drivers. If it still doesnt work, yuzu doesnt support your graphics card.

**Comment by SuWiffdEZ** [comment]
Well I mean it literally says the solution right there ("Please ensure you have the latest graphics driver")
If that doesn't work then you unfortunately aren't able to use Yuzu

**Comment by B1ackydecatty** [comment]
I checked but there is no gpus drivers so what should i do?

**Comment by masagrator** [comment]
Download and install them?

**Comment by ReinUsesLisp** [comment]
At the moment of writing this message yuzu requires OpenGL 4.3, `ARB_multi_bind` and `ARB_direct_state_access` - neither of those two extensions require special hardware features. If updating your drivers doesn't work, blame your GPU vendor for deprecating the driver. You won't be able to run yuzu on Windows with those drivers.

Answering your question (`how to do fix this issue?`) you can try using mesa drivers on GNU/Linux, but it's not generally recommended to install a separate operating system just to run yuzu.

Closing as `wont-fix`.
