### ISSUE TITLE
Fix user directory

### ISSUE THREAD

**Issue by Amnesia1000** [yuzu-emu/yuzu#2041]
In linux, when using the "user" folder accompanying the yuzu executable (e.g. /media/yuzu), when trying to open a directory from yuzu (e.g. "open save file location") always opens "/home/nameuser/user/..." instead of "/media/yuzu/user/...", giving an error when not finding the directory and files.

![screenshot_20190121_234804](https://user-images.githubusercontent.com/45115804/51509216-0d4f8480-1dd7-11e9-8c92-bde29fce0a38.png)

**Comment by QuaiGoner** [comment]
Sorry for bringing a discussion, but why not making user directory inside the yuzu directory?

**Comment by legoj15** [comment]
@QuaiGoner that is an option for portable installations (by putting a file named ``portable.txt`` in the same folder as the yuzu executable), like putting yuzu on a flash drive or other portable storage. The issue with this is that other instances of yuzu will not share the same settings like ROM directory or other user preferences, so it's not always optimal.

**Comment by QuaiGoner** [comment]
@legoj15 oh , thank you, i didnt know that, and somehow didnt noticed it in the tutorial on the site

**Comment by jroweboy** [comment]
@Amnesia1000 yuzu will do a stat on `./user` to see if its supposed to run in portable mode or not. https://github.com/yuzu-emu/yuzu/blob/7b81e1e52565ee867c285e2b0c2526f8d4b82581/src/common/file_util.cpp#L692 

Check your permissions on that folder. Also check to see if your current working directory is the same as the folder executable. Either one of these will cause problems when detecting the portable user folder.

**Comment by Amnesia1000** [comment]
The folder permissions are fine, and the folder to use is in the same folder of the emulator executable.

**Comment by jroweboy** [comment]
@Amnesia1000 You didn't check the second one it sounds like. Current working directory will depend on the command you use to run the application. https://unix.stackexchange.com/questions/94357/find-out-current-working-directory-of-a-running-process

**Comment by Amnesia1000** [comment]
@jroweboy The results:
[amnesia@manjaro ~]$ pwdx 28955
28955: /media/amnesia/Games/.Emuladores/citra-emu

[amnesia@manjaro ~]$ lsof -p 28955 | grep cwd
citra-qt 28955 amnesia  cwd       DIR               8,49     4096   45441 /media/amnesia/Games/.Emuladores/citra-emu

[amnesia@manjaro ~]$ readlink -e /proc/28955/cwd/
/media/amnesia/Games/.Emuladores/citra-emu

**Comment by Morph1984** [comment]
Is this still an issue in the latest versions of yuzu?

**Comment by Morph1984** [comment]
Likely fixed by #6270
