### ISSUE TITLE
Super Mario Oddysey: Wooden Kingdom  boss fight impossible

### ISSUE THREAD

**Issue by Phruneck** [yuzu-emu/yuzu#2045]
yuzu version: HEAD-f0d2c62 (for some reason I do not see version of the Canary build lie 18.xx)
Windows 10 1809

In Flower Thieves of Sky Garden where the boss fight is supposed to start, when I warp to Star Garden Tower Mario is covered with this pink goo even though there is no goo on the floor and looses 1 life point. Then when I move up towards the boss, I loose another life point. When the boss fight starts even if I clear the goo he is producing with hat throws, Mario is still covered with goo and dies :(

**Comment by FearlessTobi** [comment]
This issue is missing a log.

**Comment by bastianastudilloruz** [comment]
Put the game in "Assist mode" and problem solved.

**Comment by Xcedf** [comment]
Someone on discord written it long ago, installing the update 1.2.0 for SMO fixes it

**Comment by Zeroksas** [comment]
"Someone on discord written it long ago, installing the update 1.2.0 for SMO fixes it" - in other words it's game glitch. Close issue please.

**Comment by Phruneck** [comment]
Closing
