### ISSUE TITLE
Golf Story needs a savefile to pass the first loading screen

### ISSUE THREAD

**Issue by mangalexis** [yuzu-emu/yuzu#2046]
Golf Story seems to be stuck on the loading screen which just keep flashing. It may need a savefile to load ingame but can't manage to find one anywhere. 

![capture](https://user-images.githubusercontent.com/34044753/51558373-94583780-1e7f-11e9-9cf3-de5bd79bfff4.PNG)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2784194/yuzu_log.txt)

<meta name="titleids"  content="01005EA00A57E000,0100779004172000">

**Comment by mangalexis** [comment]
Sorry about that.

Here it is 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2799287/yuzu_log.txt)

**Comment by CalX17** [comment]
Hey, did someone found something to fix this ? The loading text is moving but nothing is happening...

**Comment by benderscruffy** [comment]
can be closed as this goes ingame no problems so far
