### ISSUE TITLE
Kirby Star Allies - Current Status

### ISSUE THREAD

**Issue by MichalSy** [yuzu-emu/yuzu#2051]
Version: 5bc98c2 (2019-01-23)
Video: https://youtu.be/t69bYZXeyFA

CPU: Intel Core i7-7820HQ
GPU: NVIDIA Quadro M1200
RAM: 32GB
DISK: SSD

The game runs relatively smoothly. The menu is loaded quickly and the game itself runs with about 30FPS. However, there are still some graphical problems. (See video)

**Comment by Narugakuruga** [comment]
The developers are aware of these obvious errors. But you can open a issue to help them track it if you want.

**Comment by Hexagon12** [comment]
Please make issues for specific error reports only.
