### ISSUE TITLE
Yuzu not enforcing speed percent limit on linux

### ISSUE THREAD

**Issue by youwereeatenbyalid** [yuzu-emu/yuzu#2053]
Version: Canary Build - 5bc98c2 

Currently, the limit speed percent checkbox does not seem to be functioning on the linux build of Yuzu.
Test case is Bayonetta 2, were cutscenes will speed up to 2-3 times their standard speed, instead of obeying the speed limit.

[yuzu_log.txt](https://github.com/citra-emu/citra/files/2785874/yuzu_log.txt)
[System.txt](https://github.com/citra-emu/citra/files/2785873/System.txt)

[video of test case](https://streamable.com/lekrv)

**Comment by Hexagon12** [comment]
Bayonetta is a 30 FPS title. You need to set the speed percentage at 50%, not leave it at 100%.

**Comment by youwereeatenbyalid** [comment]
Noted. Sorry for the fuss.

**Comment by Trapcast-Dan** [comment]
Even with 30fps lock enabled I've notice this still happen in certain places, such as when inputting a name in Let's Go Pikachu/Eevee or during cutscenes, it wants to bypass the limit either entirely or only up to 60fps.

**Comment by FernandoS27** [comment]
This is a core timing issue. I'll look into it soon.
