### ISSUE TITLE
Higurashi no Naku Koro ni Hou - don't started

### ISSUE THREAD

**Issue by Giza** [yuzu-emu/yuzu#2056]
I tried to fix the problem, but did not understand what was happening.
Can you tell where the error causes?
log file:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2796861/yuzu_log.txt)

sorry my bad english

**Comment by MelonSpeedruns** [comment]
yuzu is currently in very early stages of development. Some games usually run less than full-speed even on the best computers. Expect bugs and glitches to appear in most games. Many features found in more mature emulators are still in the works. For any major updates, please visit https://yuzu-emu.org/ or the discord server at: https://discord.gg/u77vRWY

**Comment by Hexagon12** [comment]
FYI, this game requires an accurate implementation of svcMapPhysicalMemory.

**Comment by Hexagon12** [comment]
Closing because of #2626
