### ISSUE TITLE
Request: Add predefined stick motions

### ISSUE THREAD

**Issue by Ghostotakoi** [yuzu-emu/yuzu#2062]
I use to have this issue playing metroid other M, for shooting missile you have to flip your controller to do it, i have to do a lot of thing in the controllers and mouse, so i though what if you add a predefined controller motions to a key, could add basic ones like shake, rise left stick, rise right stick, etc also an option to record a movement, like add custom x, y ,z position or even record them from an android device, it could be an interesting feature, but anyway is no priority, i am just saying my idea.

**Comment by simontime** [comment]
This doesn't make any sense... Metroid: Other M is a Wii title, therefore macro-based motion inputs made sense; on the Switch, yuzu's motion control emulation is not advanced enough to warrant this.

**Comment by Ghostotakoi** [comment]
that´s why i said is no priority, just an idea

**Comment by ExsertWizard** [comment]
Motion providers like cemuhook can be ported to yuzu from Citra once the necessary code for motion controls is done to support that.

**Comment by DarkLordZach** [comment]
Internally me and @ogniK5377 have decided that this would be a poor approach to motion control in the beginning and instead want to focus on either passthrough to a real joycon or using something like cemuhook for 3rd party controllers. 

Requesting to close.

**Comment by Ghostotakoi** [comment]
what about an interface like this... sorry for the quality i made it like in 5 minutes
![sample](https://user-images.githubusercontent.com/20958581/51877379-f7dbdc80-2339-11e9-83f9-2ae3d5e069f2.jpg)

**Comment by honzapatCZ** [comment]
If Iam correct(which iam probably not) there is some parts of motionemu implementation, but they are probably for the switch as a whole not per controller.

**Comment by german77** [comment]
Fixed by #4594
