### ISSUE TITLE
Title Bar does not appear in Canary

### ISSUE THREAD

**Issue by chris062689** [yuzu-emu/yuzu#2080]

**Comment by Yvar192** [comment]
This issue was first started appearing when #2021 got merged, in canary-1835. #2021 is currently unmerged, but #2055 is, which is based on #2021

**Comment by chris062689** [comment]
May be related to https://github.com/yuzu-emu/yuzu/pull/2021/files#diff-51d510d4550ae39e8b05f58bb0befe7dR17

**Comment by MysticExile** [comment]
Fixed with rebase of [#2055](https://github.com/yuzu-emu/yuzu/pull/2055)
