### ISSUE TITLE
Texture Error

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#2094]
I tried using the OpenSource Switchbrew SDK with the Yuzu Emulator to draw a textured cube 

https://github.com/switchbrew/switch-examples/tree/master/graphics/opengl/textured_cube

The code can be found here ^^^, the cube draws, but it is only a black cube, the texture does not load properly. Do you think this can be fixed?

**Comment by ReinUsesLisp** [comment]
Have you updated yuzu? Nightly should hit an assert and Canary should be rendering the cube's texture.

**Comment by FearlessTobi** [comment]
Also providing a log as requested in the issue template would be a good idea.

**Comment by niko1point0** [comment]
Can you tell me how to record a log, and where the log saves to?

**Comment by niko1point0** [comment]
Never mind, I downloaded the latest Canary build and it worked. Thank you
