### ISSUE TITLE
Build fails when in a linked directory

### ISSUE THREAD

**Issue by JuanPotato** [yuzu-emu/yuzu#21]
hash: 22347e8

I'm on Arch Linux

```
[ 88%] Building CXX object src/yuzu/CMakeFiles/yuzu.dir/yuzu_autogen/mocs_compilation.cpp.o
In file included from /home/juan/programming/yuzu/build/src/yuzu/yuzu_autogen/mocs_compilation.cpp:2:0:
/home/juan/programming/yuzu/build/src/yuzu/yuzu_autogen/EWIEGA46WW/moc_about_dialog.cpp:9:10: fatal error: ../../../../../../../Documents/programming/yuzu/src/yuzu/about_dialog.h: No such file or directory
 #include "../../../../../../../Documents/programming/yuzu/src/yuzu/about_dialog.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/yuzu/CMakeFiles/yuzu.dir/build.make:535: src/yuzu/CMakeFiles/yuzu.dir/yuzu_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:921: src/yuzu/CMakeFiles/yuzu.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

I have a folder `programming` inside `Documents` and a link in my home directory to it. When I try to build by going to `~/programming/yuzu` and the following the directions, running `make` gave me this error. The solution was to not go through the link but rather go to `~/Documents/programming/yuzu` and run `cmake` and `make` again. This fixed the issue and the build completed. I don't know if this is an issue with yuzu or cmake, but I just thought I would drop it in here.

**Comment by MerryMage** [comment]
It's a moc issue.

Relevant qt bug report: [QTBUG-51964](https://bugreports.qt.io/browse/QTBUG-51964)

**Comment by bunnei** [comment]
Closing as "Won't Fix" since this isn't a yuzu bug.
