### ISSUE TITLE
Ultra Street Fighter 2: Game is too bright (srgb issue)

### ISSUE THREAD

**Issue by legend800** [yuzu-emu/yuzu#2101]
USF2 is brighter than it should be (related to srgb?).

Yuzu:
![2019-02-10 10_02_52-window](https://user-images.githubusercontent.com/20983844/52537411-84fc3980-2d1b-11e9-9c25-cb681ce36ffb.png)
![2019-02-10 10_03_03-window](https://user-images.githubusercontent.com/20983844/52537412-84fc3980-2d1b-11e9-9c4c-98495e3420f0.png)
![2019-02-10 10_03_22-window](https://user-images.githubusercontent.com/20983844/52537413-84fc3980-2d1b-11e9-8a87-6912af5a44eb.png)

Ryujinx (same settings ):
![2019-02-10 10_05_13-window](https://user-images.githubusercontent.com/20983844/52537417-8e85a180-2d1b-11e9-9b39-ab529b830688.png)
![2019-02-10 10_05_24-window](https://user-images.githubusercontent.com/20983844/52537418-8f1e3800-2d1b-11e9-9ca0-3b2cc33e1f63.png)
![2019-02-10 10_05_51-window](https://user-images.githubusercontent.com/20983844/52537419-8f1e3800-2d1b-11e9-9367-3e60a751a233.png)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4ghz.
16GB RAM

<meta name="titleids"  content="0100BBF0027EC000,01007330027EE000,0100C86000B58000">

**Comment by ReinUsesLisp** [comment]
Can you retest this on latest Canary? I want to know if it has been fixed with recent changes.

**Comment by legend800** [comment]
No change on latest canary.

![2019-05-07 08_19_46-Window](https://user-images.githubusercontent.com/20983844/57311687-f6405400-70a0-11e9-87fb-b287da3b15f5.png)

![2019-05-07 08_19_25-Window](https://user-images.githubusercontent.com/20983844/57311688-f6405400-70a0-11e9-98d7-26efa53b0151.png)

**Comment by Hexagon12** [comment]
* Present in Cadence of Hyrule
* Present in Fire Emblem - Three Houses
