### ISSUE TITLE
Core_UseMultiCore: false

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#2107]
I noticed that there is a boolean for multicore processing in the yuzu-cmd.exe log. Is this for asynchronous GPU, or is this for multithreading the CPU?

If this boolean does enable multithreading in the CPU, can you tell me how to enable it?

**Comment by jroweboy** [comment]
its not functional at the moment which is why its disabled and removed from the ui. the code is still there and the option will remain there until its either completely removed or fixed. I recommend not turning it on. Anyway, this is known behavior and not an issue, so I'll close this then. Thanks!

**Comment by niko1point0** [comment]
Thank you! I’m glad to hear that WIP efforts are being worked on
