### ISSUE TITLE
Request: Add minigames to Shader Cache Compilation

### ISSUE THREAD

**Issue by Ghostotakoi** [yuzu-emu/yuzu#2124]
This is not high priority, but could you add minigames like the dinosaur of google chrome or a space invader to the shader compilation screen. It could be instead of a dinosaur classic pixelated mario or something. I don´t know if you can or cannot add mario due legal issues but is just an idea.

**Comment by greggameplayer** [comment]
@Ghostotakoi speed up the time to compile the shader cache would be better than add a minigame to cover the time spend.

**Comment by Ghostotakoi** [comment]
@greggameplayer yeah, but in the mid time, there is games that are literally 9000 or more shaders, i have yuzu and the game on a Samsung 960 pro evo and 3000 shader so far to smo and the compile time is almost 10 minutes.

**Comment by ReaperOfSouls1909** [comment]
4k shaders for me on smo is only 1-3 mins wait

**Comment by greggameplayer** [comment]
@ReaperOfSouls1909 i have to wait like 15 mins to load all the shaders on smo just release multi-thread shader compilation and the time will drastically lower 😉

**Comment by ReinUsesLisp** [comment]
Uh... yuzu runs on top of an operating system, you can always use something else while it loads.

**Comment by Helios747** [comment]
I don't go here but I just wanted to throw in that this idea owns.

**Comment by Yvar192** [comment]
I was working on random cat facts while it was loading, i might finish that. That's something i guess

**Comment by FearlessTobi** [comment]
This issue clearly should have top priority. :P

**Comment by Hexagon12** [comment]
Sorry to break the fun, but this issue is nonsensical. Not sure if this was supposed to be a joke, but this is not how you would tackle the issue. A logical solution would be to decrease the loading time.

**Comment by Yvar192** [comment]
I bet it's just because you like dogs better smh


/s

**Comment by greggameplayer** [comment]
@Hexagon12 that's what i've said before
