### ISSUE TITLE
yuzu doesn't properly free data from the RAM

### ISSUE THREAD

**Issue by kewlan90** [yuzu-emu/yuzu#2131]
yuzu Canary 1898 | HEAD-7bfad18

AMD FX-8350
NVIDIA GeForce GTX 760 (4 GB)
Driver Version 417.71 (25.21.14.1771)
8 GB RAM with a 16 GB pagefile (8 GB from the SSD plus 8 GB from the HDD.)
Windows 7 Ultimate 64-bit

One time my PC ran out of memory:
1. Started SMO and loading the savefile which put me on the moon.
2. Warped to the Church.
3. Beat Bowser.
4. PC ran out of memory when loading Mushroom Kingdom.

Increasing the pagefile size let me load Mushroom Kingdom, 
where I could then save and restart yuzu and continue.

Another, more easily reproducible, test I did:
1. Loaded savefile placing me in Cap Kingdom.
2. Directly traveled to Cascade Kingdom, then Sand, then Lake, 
then finally to Wooden Kingdom where it ran out memory when loading.

This is the windows message I get: 
![lowonmemory](https://user-images.githubusercontent.com/5352197/52899437-87aed100-31ea-11e9-9ada-dd7926b67165.png)

Log file:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2871865/yuzu_log.txt)
(I always close the application manually when the windows message appears.)

**Comment by DarkLordZach** [comment]
It's not that yuzu can't properly free RAM, it's just that yuzu uses a lot and there's not enough in your computer. For the foreseeable future, all you can really do is upgrade your PC.

Requesting to close.
