### ISSUE TITLE
question c++ vs rust

### ISSUE THREAD

**Issue by jerkstore369** [yuzu-emu/yuzu#2136]
I was just curious as to why the project chose c++. I've read some things about various languages and it seems like rust practically makes everything else in the same category obsolete.

**Comment by lioncash** [comment]
citra was used as the initial base for yuzu, which was written in C++

**Comment by Wunkolo** [comment]
[It was only a matter of time](https://github.com/search?q=rust+rewrite&type=Issues)

**Comment by pent0** [comment]
Stop
