### ISSUE TITLE
Half screen problem

### ISSUE THREAD

**Issue by Djipi71** [yuzu-emu/yuzu#2137]
There is a problem
in  REV 1721 the screen is ok but in Rev 1722 the screen is broken. MAny games have this screen problem , with the new canary build same problem :(

![00](https://user-images.githubusercontent.com/35375131/52965964-65fa4900-33a6-11e9-9c2d-5511da0dcbc3.png)
![01](https://user-images.githubusercontent.com/35375131/52965965-65fa4900-33a6-11e9-8b7b-82aa5e44e14d.png)

**Comment by BSoDGamingYT** [comment]
Pokemon Quests shares this issue. I reported it a few times on Discord but didn't receive much feedback on the problem

**Comment by Djipi71** [comment]
Like Woodle tree Adventure , Uno games, Guacamelee games....

**Comment by slashiee** [comment]
Super Bomberman R also suffers from this issue
![2019-02-18_13-13-23](https://user-images.githubusercontent.com/15317421/52976618-0c325880-337f-11e9-9caf-21edfe79ffed.png)

**Comment by zemzema** [comment]
I don't have this problem, check video.

https://www.youtube.com/watch?v=uyyyX2UMbmE&feature=youtu.be

**Comment by Djipi71** [comment]
Many people have this screen problem. strange that for you no problem on Bomberman.
Anyway , i have find the rev who make this problem , it will be easy i think to identified what caused this strange screen bug.

**Comment by slashiee** [comment]
Looks like the issue with Super Bomberman R depends on if the game is updated or not...
![2019-02-21_19-46-02](https://user-images.githubusercontent.com/15317421/53218536-53d01300-3611-11e9-9fb2-89ef1fbc4004.png)

**Comment by Djipi71** [comment]
Yeah apparently for Bomberman it's the problem. But for all the other game like Bud spencer , Guacamelee, uno game , woodle tree adventure , etc... all this game is a yuzu bug screen problem . Like i said Rev 1721 work well , but 1722 break somethings that break screen size. Now it will be easy to know what causes the problem no?

**Comment by TheShadowIsWithin** [comment]
Hey guys if your problems are half screen
But my game is a black screen
Can you solve this pls?

**Comment by slashiee** [comment]
June's Patreon preview release fixes this issue
![2019-06-12_17-45-30](https://user-images.githubusercontent.com/15317421/59395712-292dd580-8d3a-11e9-8bd6-ea86c1b8276d.png)
![2019-06-12_17-46-47](https://user-images.githubusercontent.com/15317421/59395716-2af79900-8d3a-11e9-8971-1f40ad94b952.png)

**Comment by fluffapparition** [comment]
So what's different about the two builds? @slashiee

**Comment by slashiee** [comment]
patreon build had changes that weren't in canary at the time. The changes are now in the latest canary, so this issue should be fixed

**Comment by Hexagon12** [comment]
Issue fixed by #2601.
