### ISSUE TITLE
Screenshot Feature always at 1080P in Docked

### ISSUE THREAD

**Issue by alinach120602** [yuzu-emu/yuzu#2140]
When making a screenshot using the built-in screenshot Feature of Yuzu, regardless of the size of the Window, it will always output a 1080P image. I don't know if it pushes the frame regardless of Window-size directly from the Renderer (eg at the Game's internal resolution without being downscaled by the Windowscaler)into a png or if it Captures the OGLWindow (using already downscaled pixels)

Canary 1905 | HEAD-d344081 (pull requests of this feature are identical to nightly)

**Comment by SeanPost** [comment]
Um yah 1080p image is a 1080p image its not taking a screenshot of your PC window as its taking a image of the game screen which is irrelevant to window size. Its emulating what a SWITCH screenshot would be not a PC window shot. Is it me or should this be closed quick

**Comment by alinach120602** [comment]
There are 900P Games though

**Comment by alinach120602** [comment]
I guess the viewport is still 1080P internally, just wanted to know how the Screenshot Tool handles it.
