### ISSUE TITLE
erorr while initializing the open gl core

### ISSUE THREAD

**Issue by roman66065** [yuzu-emu/yuzu#2148]
i have opengl 5.4 and latest graphic driver but i am facing the problem while opening games in yuzu That is "error while initializing the opengl core". please solve this problem.please yuzu

**Comment by Hexagon12** [comment]
This is a bug tracker for developers and not a support forum. Please ask on the yuzu Discord or the Citra forum instead. Additionally, try uninstalling your current graphics drivers and try installing the newest ones straight from Nvidia / AMD / Intel.
