### ISSUE TITLE
I am not able to return to the game super mario odeyssey after the ingame web applet comes on. I control the app with a keyboard key that I never assigned and the directional keys but it does nothing when I press the key it has on the bottom of the screen to exit the page. I end up right clicking with my mouse and restoring the page but that only takes me back to the first web applet menu. Please Help.

### ISSUE THREAD

**Issue by MultiCuriousKitty** [yuzu-emu/yuzu#2157]

**Comment by ExsertWizard** [comment]
...you do realize that you just made the longest title ever and that there's a description text box for all of that...

**Comment by Zeroksas** [comment]
Web applet is not functioning correctly for some users from the beginning. In order to bypass this bug you have to enter web applet in windowed mode and the exit it by mouse clicking exit option in top menu.

**Comment by MultiCuriousKitty** [comment]
Oops sorry ExseertWizard I am new to Github. Thank you Zeroksas it worked and I can now continue gaming.
