### ISSUE TITLE
Font error: no fonts in Pokemon let's go Pikachu

### ISSUE THREAD

**Issue by sd098** [yuzu-emu/yuzu#2179]
When i start Pokemon let's go Pikachu there is only an empty box ,and nothing is written on it.  Like when prof oak is telling me something the conversation box comes up but nothing written on it, and then the jumping Pokeboll appears, after pressing "A" button next box comes with same problem . How to solve that problem?

**Comment by ReinUsesLisp** [comment]
What GPU do you have and what operating system are you using?

**Comment by Zeroksas** [comment]
Try this version. You might have downloaded version without fonts data:

https://github.com/yuzu-emu/yuzu-canary/releases/download/canary-1939/yuzu-windows-msvc-20190228-235126e.zip

**Comment by sd098** [comment]
I'm using Windows 10 and amd Radeon 5 .  My pc has 8 gb ram

**Comment by sd098** [comment]
> 
> 
> Try this version. You might have downloaded version without fonts data:
> 
> https://github.com/yuzu-emu/yuzu-canary/releases/download/canary-1939/yuzu-windows-msvc-20190228-235126e.zip

I have already tried this version but  the problem still occurs. This problem started recently , i have played the game several times and i was in the 1st gym, but today when i tried to play the game this problem occurred. I also have the game Cave story+ but it is running fine without  any errror.

**Comment by Hexagon12** [comment]
> amd Radeon 5

Your fonts are not rendering because of a driver issue. They work just fine on Linux, meaning that the Windows driver is behind with the OpenGL features. Closing, since we cannot solve this. Please contact AMD's customer support if you want to see this issue fixed on Windows.
