### ISSUE TITLE
2 different color with Accurate GPU emulation in OCTOPATH TRAVELER

### ISSUE THREAD

**Issue by whoisme007** [yuzu-emu/yuzu#2184]
yuzu canary 1945 | i5-7500 |win10 1809 x64| 16G ddr4 2400| gt1030 2g Vram

2 different color with Accurate GPU emulation.

open Accurate GPU emulation:
![003](https://user-images.githubusercontent.com/6497382/53681985-013ad900-3d2c-11e9-9c7c-145b5905025d.png)

close Accurate GPU emulation:
![004](https://user-images.githubusercontent.com/6497382/53681982-f122f980-3d2b-11e9-85b5-487dcb10b1e4.png)

do not see so much different in other games...

No log.

<meta name="titleids"  content="010057D006492000,0100E66006406000">

**Comment by asbel123** [comment]
Close the issue PC version coming out June 7

**Comment by fluffapparition** [comment]
@asbel123 You're forgetting that we're trying to make an emulator here it seems, we need games to use as samples to test features with. Infact a game being ported to/from the PC (such as 20XX) probably has some small similarities that may slightly help us reverse engineer these games more easily. 

I'd say we leave this issue open, regardless of whether or not an existing PC version renders YuZu emulation obsolete in our case.

**Comment by fluffapparition** [comment]
Hey, just wanted to see if people are still working on this?

**Comment by asbel123** [comment]
Look the price octapath PC pre oder of Brazil region  they using denovo square Enix is a rip off go support Yuzu.
