### ISSUE TITLE
pfba crash with unimplemented function and assertion failed (with unicorn)

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#219]
## Hardware specs :
- Nvidia GeForce GTX 960
- AMD FX-6300
- 8 GB Of Ram
- Windows 7 Pro

## Issue :
when i run pfba with unicorn the crash reason is different than crash reason with dynarmic. Here yuzu crash after couples of seconds with "Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:118: unknown / unimplemented function '8': port: 'ISystemClock' cmd_buf={[0]=0x10004, [1]=0xa, [2]=0x3011000, [3]=0xf7ffe328, [4]=0x49434653, [5]=0x0, [6]=0x8, [7]=0x0, [8]=0x1}" and also with assertion failed

## Log :
major part of the log because there is a bug with the command "yuzu.exe 2> log.txt" causes partial record and fully record when yuzu crash
[Click Here](https://gist.github.com/greggameplayer/70779a3473fcccaea213c95ba81900ba)

**Comment by mailwl** [comment]
Homebrew Launcher crashes with:
unknown / unimplemented function '9': port: 'ISystemClock'

but on swichbrew this port has only 1-4 functions...

**Comment by mailwl** [comment]
after some investigations looks like hbmenu uses function `chdir`, which call `fsFsOpenDirectory`
https://github.com/switchbrew/libnx/blob/master/nx/source/services/fs.c#L503
but instead `fsp-srv` service function 9 calls from `ISystemClock` service

**Comment by greggameplayer** [comment]
so will you and can you correct this issue @mailwl ?

**Comment by Lrios4403** [comment]
same issue

**Comment by yellows8** [comment]
yuzu really shouldn't return RESULT_SUCCESS with no handle, for commands which are supposed to return handle(s) (in this case FSP_SRV::MountSdCard).

**Comment by Lrios4403** [comment]
@yellows8 ok so what is the fix?
