### ISSUE TITLE
Can you provide a offline installer?

### ISSUE THREAD

**Issue by ky0nch3ng** [yuzu-emu/yuzu#2192]
NET SPEED IS VERY SLOW.
If you have distribute problem, you can use offline installer and torrent(p2p).

**Comment by Yvar192** [comment]
You can always download builds directly [here](https://github.com/yuzu-emu/yuzu-canary/releases)

**Comment by Hexagon12** [comment]
No. If you cannot use the installer due to low speeds, it's not an issue on our side. Try using the direct download links.
