### ISSUE TITLE
Log record issue

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#220]
## Hardware specs :
- Nvidia GeForce GTX 960
- AMD FX-6300
- 8 GB Of Ram
- Windows 7 Pro

## The Issue :
when i use the windows command "yuzu.exe 2> log.txt" on an homebrew or game that crashing yuzu the log isn't fully record, the end of the log is being truncated.

**Comment by Hexagon12** [comment]
The same issue is also in Citra and it's because we don't handle asserts correctly.

**Comment by mailwl** [comment]
Citra is old and stable, yuzu not. why posting new issues, which maybe resolved by any PullRequest

**Comment by greggameplayer** [comment]
because it's usefull to know what the issues yuzu have

**Comment by mailwl** [comment]
no. it does not. sorry
