### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by mailwl** [yuzu-emu/yuzu#221]
this was hard, but i did it! now i have switch with first firmware. For now it brand new, but if you want, in some time i will check your homebrew

**Comment by chris062689** [comment]
This is not relative to be opened as an issue.

**Comment by mailwl** [comment]
@chris062689 maybe other variant?

**Comment by lioncash** [comment]
We have a [Discord](https://discord.gg/XQV6dn9) server and an IRC channel (#yuzu-emu on Freenode) that these things can be communicated in.

**Comment by mailwl** [comment]
oh nice! good to know
