### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by barseghyanartur** [yuzu-emu/yuzu#2214]
Building yuzu on Linux is difficult (I still didn't manage; however that's another issue).

To minimise possible issues, perhaps a Docker container would be handy (for handling the latest deps, proper version of `gcc`, `cmake`, etc).

**Comment by alinach120602** [comment]
You install make qt5-dev and gcc + the kernel headers That's it.

**Comment by chris062689** [comment]
We do have build containers and scripts for Citra.

https://github.com/citra-emu/citra?files=1
https://github.com/citra-emu/build-environments?files=1

Would just be a matter of forking it into yuzu-build-enviroments, tweaking the scripts, etc.

**Comment by barseghyanartur** [comment]
@alinach120602:

- Regarding that Docker is part of Citra and could be ported here as well: Great!
- I have all these, but system fails. I'm getting almost exactly [this error](https://github.com/citra-emu/citra/issues/4145).

**Comment by chris062689** [comment]
As far as I am aware Ubuntu 18.04 has always been a build requirement.

**Comment by Morph1984** [comment]
Closing as we have bumped up requirements to 20.04 and have no plans to support older versions of Ubuntu, as well as us already providing docker images for building yuzu
