### ISSUE TITLE
undeclared identifier  'SDL_JoystickFromInstanceID'

### ISSUE THREAD

**Issue by gantarone** [yuzu-emu/yuzu#2225]
Hi ,  
during building on Mac Osx 10.14.3 (Mojave) 
i receive this error:
undeclared identifier 'SDL_JoystickFromInstanceID'
Log:
/Users/XXXXXX/yuzu/src/input_common/sdl/sdl.cpp:166:25: error: use of undeclared identifier
      'SDL_JoystickFromInstanceID'; did you mean 'SDL_JoystickInstanceID'?
    auto sdl_joystick = SDL_JoystickFromInstanceID(sdl_id);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
                        SDL_JoystickInstanceID
/Library/Frameworks/SDL2.framework/Headers/SDL_joystick.h:133:40: note: 'SDL_JoystickInstanceID'
      declared here
extern DECLSPEC SDL_JoystickID SDLCALL SDL_JoystickInstanceID(SDL_Joystick * joystick);
                                       ^
/Users/XXXXXX/yuzu/src/input_common/sdl/sdl.cpp:166:52: error: cannot initialize a parameter of type
      'SDL_Joystick *' (aka '_SDL_Joystick *') with an lvalue of type 'SDL_JoystickID' (aka 'int')
    auto sdl_joystick = SDL_JoystickFromInstanceID(sdl_id);
                                                   ^~~~~~
/Library/Frameworks/SDL2.framework/Headers/SDL_joystick.h:133:78: note: passing argument to
      parameter 'joystick' here
extern DECLSPEC SDL_JoystickID SDLCALL SDL_JoystickInstanceID(SDL_Joystick * joystick);
                                                                             ^
/Users/XXXXXX/yuzu/src/input_common/sdl/sdl.cpp:268:23: error: use of undeclared identifier
      'SDL_JoystickFromInstanceID'; did you mean 'SDL_JoystickInstanceID'?
        CloseJoystick(SDL_JoystickFromInstanceID(event.jdevice.which));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                      SDL_JoystickInstanceID
/Library/Frameworks/SDL2.framework/Headers/SDL_joystick.h:133:40: note: 'SDL_JoystickInstanceID'
      declared here
extern DECLSPEC SDL_JoystickID SDLCALL SDL_JoystickInstanceID(SDL_Joystick * joystick);
                                       ^
/Users/XXXXXX/yuzu/src/input_common/sdl/sdl.cpp:268:50: error: cannot initialize a parameter of type
      'SDL_Joystick *' (aka '_SDL_Joystick *') with an lvalue of type 'const Sint32'
      (aka 'const int')
        CloseJoystick(SDL_JoystickFromInstanceID(event.jdevice.which));
                                                 ^~~~~~~~~~~~~~~~~~~
/Library/Frameworks/SDL2.framework/Headers/SDL_joystick.h:133:78: note: passing argument to
      parameter 'joystick' here
extern DECLSPEC SDL_JoystickID SDLCALL SDL_JoystickInstanceID(SDL_Joystick * joystick);
                                                                             ^
In file included from /Users/XXXXXX/yuzu/src/input_common/sdl/sdl.cpp:5:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:1010:13: error: 
      value of type 'void' is not contextually convertible to 'bool'
        if (__pred(*__first))
            ^~~~~~~~~~~~~~~~
/Users/XXXXXX/yuzu/src/input_common/sdl/sdl.cpp:170:28: note: in instantiation of function template
      specialization
      'std::__1::find_if<std::__1::__wrap_iter<std::__1::shared_ptr<InputCommon::SDL::SDLJoystick>
      *>, (lambda at /Users/XXXXXX/yuzu/src/input_common/sdl/sdl.cpp:171:36)>' requested here
        auto vec_it = std::find_if(map_it->second.begin(), map_it->second.end(),
                           ^
5 errors generated.
make[2]: *** [src/input_common/CMakeFiles/input_common.dir/sdl/sdl.cpp.o] Error 1
make[1]: *** [src/input_common/CMakeFiles/input_common.dir/all] Error 2
make: *** [all] Error 2

any Help?
Thanks

**Comment by DarkLordZach** [comment]
MacOS is not supported as a platform for graphics reasons.
However, master does compile on travis so I'd have to assume its something with your includes/compiler configuration being incorrect.

Requesting to close.
