### ISSUE TITLE
Yuzu crashed with mario odyssey! 

### ISSUE THREAD

**Issue by SuperSevenUp** [yuzu-emu/yuzu#2236]
Hello brothers and sisters! 🌹
I finally completed the setup of yuzu and I can load games normally.. But there's problem with mario odyssey! In the first time when I load the game its just a black screen.. So I wait for an update a few months and trying again.. When I load the game its working okay until main menu then yuzu has crashed again when I press start! What I can do?! 

Specs: i7 2630qm.. GTX 460M 1.5gb.. 8gb ram 1600 mhz.. Windows 10 with last updates.. Using Ssd hard drive.. 
Note.. Cemu and dolphin working perfectly without any problems so I wonder what the problem with yuzu🤔
Thnx in advance and sorry about my bad English xD

**Comment by Hexagon12** [comment]
This is a bug tracker for developers and not a support forum. Please ask on the yuzu Discord or the Citra forum instead.
