### ISSUE TITLE
macOS and Mojave

### ISSUE THREAD

**Issue by azoreseuropa** [yuzu-emu/yuzu#2309]
Hello!

I understand that you do not supported macOS due to OpenGL but since Mojave is released and it is no longer using OpenGL anymore. It is called Vulken. Are you going to support it with Vulken ? I wonder since you are working on this program for Vulken render, I understand, correct ?

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Yes you can talk about yuzu on the forums, and MacOS doesn't support vulkan anyway. Closing this since Mojave doesn't actually have native vulkan support.

**Comment by oscarbg** [comment]
Hi @jroweboy ,
just pointing there is now a MacOS Vulkan SDK (MoltenVK) which translates to Metal2 and is fairly good supporting even tessellation and compute shaders and  allows to run dolphin emulator Vulkan backend and more experimentally also RPCS3 on MacOS!
would be nice once yuzu Vulkan support is more or less mature to start testing via MoltenVK on Mac..

**Comment by jroweboy** [comment]
@oscarbg Hello, I'm very well aware of both moltenVK and vulkan-compatibility, as I mentioned its not *natively* supported either way. Not saying that the aforementioned projects wouldn't work for us, but as it currently stands, there is no one even considering working on a vulkan backend as none of the devs are dedicated to just graphics development.
