### ISSUE TITLE
[Request] Remove GUID from controller input config

### ISSUE THREAD

**Issue by ToppestOfDogs** [yuzu-emu/yuzu#2310]
Right now Yuzu (And Citra) write GUIDs to the config when you set up a controller. This is unnecessary because they already write the controller port to the config, so player one is only ever going to listen to a controller in port 0 for example, there's no concern that it'll accidentally listen to something else because it's only looking for port 0.

The reason I want the GUID removed is because it causes problems whenever a controller is changed in any way. For example, I may be playing a game on an Xbox One controller over bluetooth, the battery dies and I plug it in through USB. Doing this changes the GUID, and now none of the controls work. I have to rebind every single button again even though it's already set up for an Xinput controller on port 0, and when it's done charging, I have to do that again. There are also times where I may just want to use a different controller. Even though my 8bitdo controllers are Xinput, or a DS4 or Switch controller can use Xinput drivers, I have to rebind them all because of GUID.

There shouldn't be any issues removing GUID as long as Yuzu is properly reading controller ports. Most other popular emulators do not require a GUID including Dolphin, PCSX2, RPCS3, Xenia, PPSSPP, CXBX-R, etc.

**Comment by abdulhkeemGit** [comment]
please i also have this issue too it is annoying to re-configure the controller when it charges and on battery!
