### ISSUE TITLE
Double Buffering not working

### ISSUE THREAD

**Issue by Lrios4403** [yuzu-emu/yuzu#233]
So I have been trying to work on a homebrew game for the nintendo switch, however I came across a problem. Whenever I try to flip or use double buffering on the graphics, it never works. However, when I open **singlebuffering.nro** in the examples the emulator seems to work just fine.

So there are a few ways to fix this:
1. Is double buffering enabled
2. How do i single buffer, since the source code isn't in the examples, its just **singlebuffering.nro**

**Comment by WinterMute** [comment]
What is singlebuffering.nro & where did it come from?

**Comment by yellows8** [comment]
That check should just be removed, hw doesn't check that.

0 is the default pixel-format. Changing only the input pixel-format passed to DequeueBuffer has no affect on hw.

**Comment by Lrios4403** [comment]
@WinterMute its one of the .nro projects that doesent have any souce code in the devKitPro, It seemed as if it was the only screen that was working. 

Im going to try out these solutions in the morning.

**Comment by Lrios4403** [comment]
@endrift Do you mind sending me a copy of the folder you use for yuzu in visual studios? For some reason Cmake is deciding to give me a error:

-------------------------------------------------------------------------------------------

CMake Error at common/CMakeLists.txt:91 (create_target_directory_groups):
  Unknown CMake command "create_target_directory_groups".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.11)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by endrift** [comment]
No, I cannot. I am not using MSVC as I am not using Windows.

**Comment by Lrios4403** [comment]
@endrift Commenting out the line you recommended did not work. Anything else?

**Comment by Lrios4403** [comment]
@endrift What if I write to the video memory instead? What is the address of the video memory that yuzu reads?

**Comment by bunnei** [comment]
@Lrios4403 can you post `singlebuffering.nro` as well as an example app for double buffering that works on HW but does not work on yuzu (with source please)? This will make it easier for us to verify a fix. Thanks!

**Comment by Lrios4403** [comment]
@bunnei Ok, for devKitPro there is a file with singlebuffering.nro. I dont know where the source is for it, its just there. Along side of that is a hello world example. However that doesent seem to work (my only guess is that it double buffers. Here are the files:


[singlebuffering.zip](https://github.com/yuzu-emu/yuzu/files/1814218/singlebuffering.zip)
[hello-world.zip](https://github.com/yuzu-emu/yuzu/files/1814219/hello-world.zip)

**Comment by WinterMute** [comment]
Seems a bit pointless worrying about single buffering. We discovered that causes screen artifacts on hw so we're not doing it in libnx any more.
