### ISSUE TITLE
AMD Pokemon regression

### ISSUE THREAD

**Issue by mineas312** [yuzu-emu/yuzu#2363]
After updating yuzu Canary to version 2130, Pokemon: Let's Go, Eevee! is rendering only dialog boxes and menu. Other things like terrain, characters do not render at all. I tried disabling and enabling disk shader cache and asynchronous GPU emulation. Before this update game was working properly only with a text bug.

Here I can see only logo, but terrain with Evee isn't rendered.
![pg1](https://user-images.githubusercontent.com/17180405/55681138-08549880-5923-11e9-8805-7a0f58cbf800.png)

In game dialog boxes are only rendered. I can hear footsteps when I'm moving.
![pg1](https://user-images.githubusercontent.com/17180405/55681181-8d3fb200-5923-11e9-9873-de747448afc4.png)

Character selection seems only to work properly.
![pg1](https://user-images.githubusercontent.com/17180405/55681215-e871a480-5923-11e9-90ce-8f4b60d052fe.png)

Logs:
[log.zip](https://github.com/yuzu-emu/yuzu/files/3051380/log.zip)

My hardware:
AMD Ryzen 7 2700x
AMD Radeon R9 390

**Comment by MerryMage** [comment]
What is the last version that worked?

**Comment by mineas312** [comment]
I don't remember but I updated canary around 27-29th March

**Comment by mineas312** [comment]
I figured out this was caused by Canary version 2088. Version 2087 is working properly.

**Comment by mineas312** [comment]
This problem also happens when using linux but gives white screen instead of black
![screen](https://user-images.githubusercontent.com/17180405/55794755-5bb31c00-5ac6-11e9-8f02-c6f63008c6a4.png)

**Comment by mineas312** [comment]
Regression is caused by merge #2306. After I removed its code, Pokemon is working well.
![image](https://user-images.githubusercontent.com/17180405/55819116-64bce100-5af8-11e9-96f5-e7960628406e.png)

**Comment by FernandoS27** [comment]
We are looking into it.

**Comment by ReinUsesLisp** [comment]
There are two possibilities:
- The game is actually using dynamic AOFFI.
- My "soft" constant folding heuristic is failing.
Relevant part of the log:
```
[   7.621641] HW.GPU <Warning> video_core\shader\decode\texture.cpp:GetAoffiCoordinates:577: AOFFI constant folding failed, some hardware might have graphical issues
```
