### ISSUE TITLE
Build for Linux reporting error despite self-built build working

### ISSUE THREAD

**Issue by some-username-here1** [yuzu-emu/yuzu#2379]
Hello! I would like to report a simple issue I'm having with the recent builds given from the download page itself, for Linux.

and I have tested the recent builds (both from Nightly and Canary), all giving me the same error, being:
```
./yuzu: error while loading shared libraries: libQt5WebEngineWidgets.so.5: cannot open shared object file: No such file or directory
```

The builds have gave me this error despite the build I built myself (from the latest commit, as of 2019-Apr-09, 22∶59∶38 [PST]) is working properly and not giving me that error.

Also, if it'll help, the packages I installed are `libsdl2-dev`, `libsdl2-2.0-0`, `qtbase5-dev`, `libqt5opengl5-dev`, `build-essential`, `cmake`, and `libc++-dev` (I had to install `libsdl2-dev` since it couldn't build with `libsdl2-2.0-0`)

EDIT: My Linux OS is Linux Mint 19.1 "Tessa" Cinnamon (64-bit)

**Comment by Yvar192** [comment]
You need to install the `libQt5WebEngineWidgets` dependency

**Comment by some-username-here1** [comment]
I tried that, it just gave me:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libQt5WebEngineWidgets
```

**Comment by Yvar192** [comment]
try `qtwebengine5`

**Comment by Hexagon12** [comment]
This is a bug tracker for developers and not a support forum. Please ask on the yuzu Discord or the Citra forum instead.

**Comment by bleszzerd** [comment]
> try `qtwebengine5-dev`

Solved, thanks
