### ISSUE TITLE
Yuzu Canary 2167 crashing on Pokémon let's go

### ISSUE THREAD

**Issue by CookieXD** [yuzu-emu/yuzu#2394]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3074505/yuzu_log.txt)

I tried to load either lets go games on the lastest versions, but yuzu does always crash right before the title screen.
Intel Core I5 9600k, GTX 1660Ti Gaming X, 16 GB Ram.
For my GTX 1660TI I got the 425.31 Game Ready driver installed.

The lastest version the game runs for me is the patreon 30 fps build 2019.04.03

I have disabled Asynchronous GPU emulation, enabled disk shader cache and limited my framerate to 100%
I am using the native resolution and tried with and without forced 30 fps.
Without CPU Jit the Launching... takes very long (still waiting for it to finish)
But it's not crashing and I got a permanent 35% CPU load from Yuzu alone.

How it providing a backtrace meant? English is not my native language.
Hopefully the log file is usefull to fix it.

Thanks for your awesome work!

**Comment by BSoDGamingYT** [comment]
The fix for the softlocks is not in current latest Canary. Be patient and it will be re-added when ready

**Comment by Hexagon12** [comment]
This is a bug tracker for developers and not a support forum. Please ask on the yuzu Discord or the Citra forum instead.

**Comment by CookieXD** [comment]
> This is a bug tracker for developers and not a support forum. Please ask on the yuzu Discord or the Citra forum instead.

I thought i was a bug, but if BSoDGaming is right it isn't.
