### ISSUE TITLE
Mipmapping Broken in Yuzu

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#2395]

**Comment by FernandoS27** [comment]
hmn, do you have any screenshots on how it's suppose to look.

I have looked into the doc and I can see the the mipmaps aren't loaded correctly (probably because they are loaded from DMA engine/M2MF)

**Comment by niko1point0** [comment]
I can upload screenshots later today. (As well as an updated NRO, since I’ve changed it)

Also, this isn’t as important, but the loading screen doesn’t work in Yuzu either. We built the loading screen to draw one frame (with png splash screen), then update the buffers, and then we don’t clear the screen or render the next frame until all assets are loaded. Therefore, while the game loads on Switch, it runs 0fps while loading and constantly showing the splash screen. In Yuzu, the splash screen draws for one frame, and then we get a black screen at 16fps. 

However, mipmapping is more important than a splash screen (in my opinion). I’ll have screenshots for mipmapping later today

**Comment by FernandoS27** [comment]
do upload texture arrays btw?

**Comment by FernandoS27** [comment]
Talking about the splash screen, we have problems measuring vblanks. Do you have the source code btw?

**Comment by niko1point0** [comment]
Yes I do. Sorry, I was unable to load screenshots. I'll upload the project to Google Drive and send it

**Comment by niko1point0** [comment]
https://drive.google.com/file/d/1rBZc5KJ0y9feMfobYtTiWoLZrH51Xn-v/view?usp=sharing

For the time being, I am unable to upload the entire project. My apologies for that. In the meantime, here is the engine and the game. The mipmapping is done in engine/Texture.cpp in the function PassToGPU().

If you would like to use the engine I wrote to make more 3D games, I can give you some starter code that allows you to render objects to the screen with only 30 lines, while having 3D objects, textures, shaders, and more, handled by the engine

**Comment by FernandoS27** [comment]
Well the screenshots would be more important. The source code will only be used to get to the vBlank problem we have.

**Comment by niko1point0** [comment]
![1](https://user-images.githubusercontent.com/7824443/56598381-64c1e400-65c2-11e9-9b32-f990345b3ebd.PNG)
![2](https://user-images.githubusercontent.com/7824443/56598389-67243e00-65c2-11e9-8484-a384be8253c2.PNG)
![3](https://user-images.githubusercontent.com/7824443/56598394-68ee0180-65c2-11e9-96d0-ddcfd13721f4.PNG)
![4](https://user-images.githubusercontent.com/7824443/56598397-6b505b80-65c2-11e9-8b41-0ea5ce618502.PNG)
Here are the screenshots. The biggest visual difference between the screenshots, and the NRO I provided, is that the skybox is different, but the rest of the visuals are the same. There might be less lights in the NRO I provided, can't remember. Was this helpful? Is there anything else that I can provide?

**Comment by FernandoS27** [comment]
Ok I investigated it and it's not really a mipmap problem. It's a problem on how Nouveau generates the mipmaps. It uses a weird setup on the rendering triangles which results on invalid triangles being rendered.

So far I suggest you generate the mipmaps yourself and upload them on your own. We'll have to investigate this issue.

@ReinUsesLisp you may be interested on this.

**Comment by ReinUsesLisp** [comment]
I'm writing to point out that this is not forgotten. The current cache has some issues with guest memory sizes and mipmaps as a whole (for example, accurate GPU emulation might not copy mipmaps).

**Comment by niko1point0** [comment]
Hey guys, I just got an idea. Is there any way for my Nintendo Switch code to determine if it is being run in Yuzu rather than a physical Switch? If so, I can disable mipmaps in Yuzu and enable it on physical hardware. Any ideas?

**Comment by DarkLordZach** [comment]
While that is definitely possible, even easy, it is not something we would encourage. We would instead advise you wait until this issue is fixed.

**Comment by niko1point0** [comment]
Ok. I will wait until the issue is fixed

**Comment by FernandoS27** [comment]
There are ways to detect yuzu but requires using lowest functions in libnx directly. The thing is that yuzu stubs some meaningless services, so you can try working with that.

now I'll ask nouveau how they use glGenerateMipmap to know where they upload their vertex data.

**Comment by niko1point0** [comment]
Sounds great. Thank you for the effort!

**Comment by niko1point0** [comment]
Hi everyone, I was re-reading some messages and noticed a while ago that @FernandoS27 suggested 
"I suggest you generate the mipmaps yourself". Currently, this game (racinggame.nro) is able to cross-compile on Switch, PC, Xbox, and PlayStation 4. All versions of the game are generating the mipmaps in a different way, with different helper libraries that are specific to the system; Windows and Switch are the same with OpenGL, Xbox is different with DirectX, and PS4 is different too. Is there any way to manually generate the mipmaps in a way that is API-agnostic? I heard it involves recursively taking the average of 4 pixels from the high-res texture, for each new pixel of the lower-resolution texture, until all mipmaps are made. If it is not possible to make an API-agnostic mipmap generation, are there any OpenGL tutorials that can help me learn how to do this in OpenGL? Has there been any progress towards fixing glGenerateMipmap in Yuzu? Has the bug been fixed in any experimental builds?

**Comment by FernandoS27** [comment]
I actually contacted Nouveau devs about this issue and they told me they did some weird things with them. Also do you have an updated nro?

**Comment by niko1point0** [comment]
[racinggame.zip](https://github.com/yuzu-emu/yuzu/files/3362955/racinggame.zip)
Here is the updated NRO. Some changes have been made with the AI, texture's now use anisotropic filtering instead of linear mipmapping, this build includes the night skybox with blue ambient light, and this weekend my friends and I will make it so players can race against AI cars. I will look into glTextureBarrier and see if I can generate the mipmaps by hand. Does Nouveau have any plans to change their implementation of glGenerateMimaps?

**Comment by FernandoS27** [comment]
theirs works on hardware, in our case we may be missing something.

**Comment by niko1point0** [comment]
Hey, I was thinking pre-generating my mipmaps with a format like DDS, so that I could avoid runtime mipmap generation all together. Would that be an optimal thing to do? Would it take longer to load mipmaps from DDS than it would take to generate them?

Also I found another bug in the emulator with racinggame.nro, this one is a small bug. If you run the game on physical hardware, there is a “Loading” splash screen, but the screen does not show in Yuzu. What I do in the code is draw literally one frame of the loading screen, then stop drawing until loading is done, and then the game loop runs. In Yuzu, while booting the game, there is a black screen at 5fps - 10fps, when really it should only be one frame for 6 seconds. 

The splash screen doesn’t need to be fixed though, just wanted to point it out

**Comment by FernandoS27** [comment]
Pre generated mipmaps are normaly faster and better quality (specially if you use a tool to generate them or photoshop to do bicubic sharper downscaling).

**Comment by niko1point0** [comment]
Thanks, I'll look into that

**Comment by niko1point0** [comment]
Didn't mean to close and reopen, that was an accident.

Anyways, @FernandoS27, I think I found out why this bug is occurring in Yuzu, and I think I know how to fix it. I remember a while ago, you said "It uses a weird setup on the rendering triangles which results on invalid triangles being rendered." I was confused because I have never seen invalid polygons in Yuzu; my vertex buffers and index buffers would always draw correctly, but I just found a new bug that might be related.

I tried to make procedurally-generated geometry in the Vertex Shader, without a vertex buffer or index buffer. I would call glDrawArrays, and then the vertex shader would use gl_VertexID to generate geometry, without a vertex buffer or index buffer. This worked on Windows when compiled to an EXE, and it worked on Nintendo Switch when compiled to an NRO, but it did not work in the Yuzu Emulator.

Is it possible that Noveau is generating mipmaps by using triangles that are procedurally generated in a vertex shader, without using a vertex buffer or index buffer? If so, does this knowledge make the bug easier to solve?

Here is the NRO. Btw I also added like 50-60 more lights
[racinggame.zip](https://github.com/yuzu-emu/yuzu/files/3414022/racinggame.zip)

In the game, if you press the + button on the joycons, it should bring up a pause menu (which doesn't actually freeze the game), and then procedurally-generate geometry is used to draw the following 2D sprites and fonts:

![Capture](https://user-images.githubusercontent.com/7824443/61584605-980c0480-ab18-11e9-8708-9f4b1a2ec3b4.PNG)

**Comment by niko1point0** [comment]
@FernandoS27 I've been doing some more testing with the emulator. I have not gotten a single instance of gl_VertexID to work, regardless if VAO or VBO buffers are binded or not. Is gl_VertexID implemented in Yuzu at all?

**Comment by ReinUsesLisp** [comment]
`gl_VertexID` works on yuzu, are you using a base vertex index? e.g. `glDrawArrays(GL_TRIANGLES, <some first != 0>, count)`

**Comment by niko1point0** [comment]
The exact line was
glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

**Comment by ReinUsesLisp** [comment]
That might not be a `gl_VertexID` issue, but nouveau not optimizing `gl_VertexID / 2` and `gl_VertexID % 2`. Integer division on nouveau is implemented through a Maxwell function call that yuzu doesn't implement. I suggest changing `gl_VertexID / 2` to `gl_VertexID >> 1` and `gl_VertexID % 2` to `gl_VertexID & 1`.

About rendering without vertex data, it's supported. What might not be supported is the indirection generated by nouveau in the shader.

**Comment by niko1point0** [comment]
Thank you very much @ReinUsesLisp, I'll try that and see what happens

**Comment by FernandoS27** [comment]
on your last question, nope. glBegin/glEnd methods are not supported yet (well the nvidia related method)

**Comment by fluffapparition** [comment]
@niko1point0 may I ask why the Windows version uses OpenGL but the xbox port uses directx? Is that to do with lack of OGL support on Xbox?

It's your code so you should write it how you feel it should be written, but as a PC gamer I strongly prefer Directx > opengl or vulkan on Windows systems if possible, mostly for performance reasons. I just find that somewhat strange

Sorry if this seems really off topic, I was just kinda curious

**Comment by niko1point0** [comment]
@fluffapparition The Windows version of the game supports both OpenGL and DirectX 12. Vulkan support is in progress

**Comment by niko1point0** [comment]
Hey guys, I changed the shader to draw quads with VertexID & 1 and VertexID >> 1.
After this change, procedurally generated geometry still does not draw in the homebrew when I test it in Yuzu. Attempting to draw the quads will cause the emulator to crash. On the other hand, if I disable drawing quads, the emulator will draw one frame, and then crash, saying that there is 1000 FPS.

NRO without procedurally generated quads (crashes on first frame)
[racinggame.zip](https://github.com/yuzu-emu/yuzu/files/3566493/racinggame.zip)

NRO with procedurally generated quads (immediate crash)
[racinggame2.zip](https://github.com/yuzu-emu/yuzu/files/3566519/racinggame2.zip)

**Comment by niko1point0** [comment]
Hey everyone, possible new bug. I tried to do basic post processing with offscreen render targets, and the emulator crashed immediately. It worked on PC when compiled to exe, and worked on Switch when compiled to NRO, but not the emulator. I don’t know if the render target is what made it crash, or it could be because I was drawing a fullscreen quad in the final render pass. I had issues with procedurally generating quads before, as mentioned above ^^

I’m currently working on motion blur and deferred lighting optimization in my homebrew game. I really enjoy prototyping with the emulator, even though I have to disable like 4 features. 

Just wanted to give an update. Btw, the new Async GPU works great! It takes 2% of my CPU to run the native exe, and now Yuzu runs mostly around 4% CPU usage, with some occasional spikes of 18%

**Comment by fluffapparition** [comment]
@niko1point0 could you possibly grab the crash logs from the emulator and put them in a separate Issue with more detail

**Comment by niko1point0** [comment]
Sure, I'll get around to that later. Right now I'm studying for some college exams, but I'll do it.

The code I was using was almost identical to the code at this link (below), except I replaced the procedural triangle with a procedural quad (vertexID & 1, vertexID >> 1)

https://github.com/IGME-RIT/Basic-OpenGL-with-GLFW-Rendering-to-Textures

I'll post separate crash logs for the quads that I use in the in-game HUD, the quads used in font, and the quads used in the offscreen render target, then we will see if they're related or not

**Comment by niko1point0** [comment]
I narrowed it down, the reason for the post-processing breaking is definitely because of the fullscreen quad being procedurally generated in the 2nd renderpass, so the issue is connected to other quads not rendering (like HUD and on-screen font) 

I have no clue how mipmapping works in Nouveau, but I have a gut-feeling that it has something to do with procedurally generating polygons, and then rendering on the polygons. If that is the case, then this is really only one bug, and fixing the one problem would fix everything @fluffapparition

**Comment by niko1point0** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3693972/yuzu_log.txt)

Here's the crash log when I generate quads. I'm not an expert on emulators, I could be completely wrong about the mipmap generation and procedurally-generated quads being connected. However, I haven't seen the emulator fail anything else in my homebrew (which is super impressive btw), so that's why I wonder if they're related

**Comment by fluffapparition** [comment]
@niko1point0 so gl_rasterizer.cpp needs to be expanded to better support shaders without buffers is what im gathering from this

**Comment by niko1point0** [comment]
It also needs the ability to make draw calls without using vertex attributes, rather than calling "assert" when no attributes are found

**Comment by niko1point0** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3694611/yuzu_log.txt)

Here's the log that I get when mipmap generation fails. It does not have any problem with Vertex Attributes, but there are some "Critical" Debug notes that overlap with the crash log I get from quads, looks like something in DMA

**Comment by niko1point0** [comment]
By any chance, is the emulator compiling shaders to SPIRV? I just tried converting my shaders to SPIRV in the Windows version of the OpenGL game, and suddenly the procedural quads stopped working, just like how they don't work in the emulator.

**Comment by niko1point0** [comment]
I fixed the bug by changing my own code. This issue should be closed because it will not impact any other games in the emulator, ever, so there is no point

**Comment by fluffapparition** [comment]
@niko1point0 im not so sure about that. Also deleting all of your replies seems to do more harm than good, but you do you.
