### ISSUE TITLE
Multithreading broken in Yuzu

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#2396]
In the most recent release of libnx, the library used in open-source Nintendo Switch homebrew development, we got support for std::thread, which is the standard C++ multithreading method. I implemented multithreading in my homebrew game, and it works fine on Switch, but Yuzu just gives me blank blue screen (blue is the color I set for glClear). Yuzu hasn't crashed, its still updating 60fps, but it draws nothing.

The reason I'm confused is because I assume there is multithreading in Mario Odyssey and Zelda BOTW, and those games work fine in the emulator, even though the emulator itself does not use multithreading (except for async graphics)

If you would like any additional information (my source code, yuzu logs, the NRO for the game, etc), then please let me know

**Comment by ReaperOfSouls1909** [comment]
there is no multithreading sorry

**Comment by FernandoS27** [comment]
Multithreading does exists, we just simply run 1 host thread to emulate all the switch's cores but guest threads are all handled.

First try it in Canary, it has the newest scheduler. Second, if you think the homebrew gets softlocked, pause the emulator (pause not stop), run debugger -> wait tree. Print an image of the debugger and attach it to this post. That will help us diagnose your problem.

**Comment by niko1point0** [comment]
I just realized the problem, I forgot to embed the romfs folder inside the NRO. Usually we load files from USB so that we don’t need to transfer a huge NRO to the Switch every time we recompile. By the time I realized, I already left the office. Tomorrow I’ll compile the NRO again with romfs embedded in the NRO, and then I’ll post the results here

**Comment by niko1point0** [comment]
I recompiled the game, it works fine in Yuzu. It was a careless mistake on my part. Thanks for telling me about the debugger though. I'll use it in the future
