### ISSUE TITLE
Single Window Mode Launch screen freeze

### ISSUE THREAD

**Issue by Heartless255** [yuzu-emu/yuzu#2428]
The emulator gets stuck on the launch screen as of Canary 2130 to the present Canary (2205), however this was fixed by disabling Single Window Mode on the View Tab on the emulator. While this did resolve the issue, it is unknown why this happens, thus why i am reporting the issue
[yuzu_log Single Window Mode On.txt](https://github.com/yuzu-emu/yuzu/files/3102560/yuzu_log.Single.Window.Mode.On.txt)
This log is with Single Window Mode On
[yuzu_log Single Window Mode Off.txt](https://github.com/yuzu-emu/yuzu/files/3102570/yuzu_log.Single.Window.Mode.Off.txt)
And this log is with Single Window Mode Off

**Comment by G-Spawn** [comment]
This shouldn't happen any more on latest yuzu versions. Please update.
