### ISSUE TITLE
Preparing Shader Cache crash

### ISSUE THREAD

**Issue by irmonteiro** [yuzu-emu/yuzu#2432]
I can play pokemon let's go with no precompiled and transferable cache, but when the game build one and passes 4~5mb it begin to crash on PREPARING SHADERS.
Anyone know how to fix it?

**Comment by FernandoS27** [comment]
your cache is corrupted, delete it and recreate it (delete the transferable cache)

**Comment by FreddyFunk** [comment]
Please provide a log and some information about your system. 

Few additional question:

Does the crash occur on other games as well?

Which canary version do you use? 

Did it work on earlier canary versions?

**Comment by Hexagon12** [comment]
It's a shader cache corruption. Right click on the game in Yuzu's game list and select Open Transferable Shader Cache, then delete the file that's selected.

**Comment by Yvar192** [comment]
Shader cache corruption is still an issue though. Shouldn't this stay open? Just deleting it isn't really a proper fix

**Comment by ReinUsesLisp** [comment]
It's very likely that the problem is not related to the shader cache itself but the game blasting through undefined behaviour.

**Comment by kk5dire** [comment]
Wow I have an issue close to this now but Its having an issue loading one shader and no matter what crashes on load even when its deleted and reloaded
