### ISSUE TITLE
Crashing on RTX graphic card

### ISSUE THREAD

**Issue by Keks3r** [yuzu-emu/yuzu#2433]
Since yuzu build 2200+ yuzu not working on any Nvidia RTX graphic card.
Right after shader compiling you see a endless "Launching..." loop.

OS: Windows 10 Build 1809 x64
Installed latest NVIDIA GeForce Experience driver.

Only workaround is using a older yuzu Build under 2200+

**Comment by Hexagon12** [comment]
Here's what I found out more about this issue from others (just to add more info for devs):
* If the accurate GPU emulation option is checked, the game actually goes a bit further and crashes when trying to render 3D.
* The issue started between Canary 2160 and 2161, which indicates that #2387 might be the culprit, but the dev confirmed that the code doesn't have any issues and it fixes other games, which then indicates a driver problem.

**Comment by FernandoS27** [comment]
It's a driver issue, already reported to NVIDIA.

Please close this issue as it does not affect us directly.

**Comment by Patjwmiller** [comment]
I have an RTX 2080 ti and I have literally never crashed in yuzu.
