### ISSUE TITLE
Homepage: macOS support

### ISSUE THREAD

**Issue by ShalokShalom** [yuzu-emu/yuzu#2436]
Hi there :D

Thanks a lot for this project, your Progress is amazing, you know that.

Small hint: There is no mention of macOS support on the homepage, while on the Readme.

P.S: As a personal and honest hint: Give Kdevelop a small chance ;)

**Comment by FernandoS27** [comment]
There's no macOS support because Apple is reluctant to update their OpenGL drivers (in fact they deprecated them entirely) and is reluctant to support Vulkan directly. Sadly we don't have the manpower, hardware or plans to implement a Metal backend.

With that said, we keep yuzu compileable in mac with future plans to address those issues through an api called MoltenVK.

**Comment by ShalokShalom** [comment]
Well, then is your Readme, since it is speaking about macOS support.

There is gfx-rs, a rust library which supports DirectX11 and 12, Vulkan, OpenGL and Metal.

It is open for all languages.

**Comment by ShalokShalom** [comment]
[They already run successful compilations on Dolphin.](https://gfx-rs.github.io/2019/03/22/dolphin-macos-performance.html)

**Comment by DarkLordZach** [comment]
Unfortunately, gfx-rs is not just a "click here and it works" solution. It would require extensive work and time in order for it to get to the state that dolphin has it.

For now, we are focused on improving render quality and performance on our Vulkan and OpenGL backends.

**Comment by FernandoS27** [comment]
Also I'd like to point out that it wasn't a dolphin initiative but gfx-rs's team's intiative to do the porting. Both Dolphin and RPCS3 use a subset of features from Vulkan that fits their emulation needs. In our case, we will require to use more modern features and things that gfx-rs may not yet support.

**Comment by ShalokShalom** [comment]
Yeah, I assumed something like this. Anyway, you are doing a marvelous job :D
