### ISSUE TITLE
SD Card not Implemented?

### ISSUE THREAD

**Issue by Lrios4403** [yuzu-emu/yuzu#247]
Im guessing the SDCard hasnt been implemented into the yuzu emulator? I have tested the SD card. aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaannnnnnnnnnndddddddddddddd this happend.

Here is the source code and screenshot.

[current.zip](https://github.com/yuzu-emu/yuzu/files/1823021/current.zip)
![capture](https://user-images.githubusercontent.com/16861047/37569790-9d19aea0-2aa4-11e8-89fa-fb4eb53cee23.PNG)

**Comment by mailwl** [comment]
libnx? https://github.com/yuzu-emu/yuzu/issues/219 - same issue

**Comment by Lrios4403** [comment]
@mailwl yea libnx

**Comment by Subv** [comment]
Indeed, SD card access is not yet implemented.

**Comment by Lrios4403** [comment]
@Subv Im still getting the same error (nightly-mingw 3/19/2018 8:48pm download). Im getting an assertion failure, but at a different code 

All in all im just going to stay away from SD Card file systems for now. Keep me updated on when you have a dedicated SD card file system!

![capture](https://user-images.githubusercontent.com/16861047/37638049-27cdd07a-2bc8-11e8-93d5-3cab8628d370.PNG)

**Comment by mailwl** [comment]
You have to merge and build it by yourself (until PR will be merged)
