### ISSUE TITLE
Pokemon lets go pikachu amd graphic card wont open the game

### ISSUE THREAD

**Issue by 44trex44** [yuzu-emu/yuzu#2481]
Yuzu emu waiting at the loading screen of nintendo before the game start. Then there is no reaction just loading screen. But sometimes there is an AMD graphic do not access error and give me black screen. Plz help me ı want to play that game :(

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use the Citra forum for support.

Requesting to close

**Comment by Hexagon12** [comment]
Alternatively, you can use Yuzu's Discord server.
