### ISSUE TITLE
Possible Inaccuracies in MME emulation

### ISSUE THREAD

**Issue by FernandoS27** [yuzu-emu/yuzu#2501]
fincs found a few inaccuracies in our MME emulation by analyzing code submitted by NVN. 

He created the next test:
```    5 to r1
.loop
    1 to mem
    dec r1 to r1
    bza r1 .end
    2 to mem
    b .loop
    *3 to mem
    nop

.end
    exit
    nop
```

which should return "Produces: 1 2 3 1 2 3 1 2 3 1 2 3 1"
Accordingly he points out that https://github.com/yuzu-emu/yuzu/blob/master/src/video_core/macro_interpreter.cpp#L125 should actualy be: `if (opcode.is_exit && !is_delay_slot) {`

@Subv introduced the solution as: #2466 

Sadly this implementation produced infinite loops within the MME Interpreter. The change has been temporally reverted in order to be better investigate the inaccuracies in the MME interpreter and figure why such change causes an infinite loop.

**Comment by fincs** [comment]
The inaccuracy has a simple cause: NVN runs this loop inside its FirmwareCall macro; in order to check when D00 changes. yuzu doesn't emulate firmware calls, so now that the loop is correctly emulated it effectively becomes an infloop.

**Comment by ReinUsesLisp** [comment]
Should we open a separate issue for properly emulating FirmwareCalls? Can this be closed?

**Comment by ReinUsesLisp** [comment]
Closing as the main issue has been addressed.
