### ISSUE TITLE
Super Mario Odyssey renders nothing in PR #2485 on iGPU

### ISSUE THREAD

**Issue by windyboy1704** [yuzu-emu/yuzu#2506]
Super Mario Odyssey now renders nothing in PR #2485 on Intel HD 620. Can hear sound though.
![Screenshot (243)](https://user-images.githubusercontent.com/5692900/58107788-c6eb2480-7c14-11e9-883b-ef7e4441d27a.png)
Log file: 
https://ufile.io/j6ux2hwt (will expiry in 30 days)

**Comment by ReinUsesLisp** [comment]
That is not related to the linked PR.

**Comment by windyboy1704** [comment]
Really? I tried older canary version and it works fine.

**Comment by Zeroksas** [comment]
Which canary version are you using? Canary versions 2298 - 2300 had similar problem caused by another PR, but it was fixed in latest canary.

**Comment by windyboy1704** [comment]
Worked again in 2303. Closing now, the problem happens because of the build, not because of that PR, sorry.
