### ISSUE TITLE
Issue with setting Birthday in System Settings

### ISSUE THREAD

**Issue by Eloeri** [yuzu-emu/yuzu#2522]
In the latest releases of both Nightly-2018 and Canary-2318 there is a bug when selecting the date for the Birthday. 

When selecting the system section of yuzu Configuration, you are unable to select the day of the month without first selecting another month. So if you had a birthday in January, you would unable to select the day of the January month without first selecting another month. Here is the window when first selecting [system](https://i.imgur.com/jJ99yxP.jpg), the option to change the day is not available. After changing the month, [you can now select the day of the month](https://i.imgur.com/AIDJVqE.jpg).

**Comment by DarkLordZach** [comment]
The Switch doesn't have a concept of Birthday like the 3DS, so this should instead of fixing it just remove the birthday stuff altogether

**Comment by windyboy1704** [comment]
I guess this is from Citra
