### ISSUE TITLE
Missing libzlib.dll (mingw Windows)

### ISSUE THREAD

**Issue by ampnjdevs** [yuzu-emu/yuzu#2544]
The Windows mingw canary releases 2330-2333 immediately crash due to missing file libzlib.dll. This file is not included in any of the release archives. Commits 17decdc, a0950a5, 35aabb7, f68fa3b are currently affected.

**Comment by ampnjdevs** [comment]
Canary 2351 (or potentially earlier) fixes this issue, closing

**Comment by ampnjdevs** [comment]
Issue has reappeared in Canary 2376-2380

**Comment by DarkLordZach** [comment]
This is from PR #2539, which hasn't been merged yet. I'd say to report it on the PR, but it was already reported there. It will be fixed before BCAT is put back onto canary.

**Comment by Irastris** [comment]
Issue has appeared yet again from Canary 2695-2705 and potentially beyond.

**Comment by Irastris** [comment]
Continued presence in Canary 2708.

Workaround is to make a copy of `zlib1.dll` and rename it to `libzlib.dll`. I have not monitored any regressions in doing this so far.

**Comment by goedzo** [comment]
I can confirm that renaming zlib1.dll to libzlib.dll is indeed a valid workaround for the canary build of yuzu-windows-mingw-20191011-9d29c1b in which this issue still occurs.

**Comment by jbeich** [comment]
Can you check if #2947 fixes this?

**Comment by goedzo** [comment]
Sorry but i cannot since i only download the nightly canary build for testing. I don't build any code at all.

**Comment by lat9nq** [comment]
Appears to have been fixed with either yuzu-emu/build-environments#8 or #3735. Besides MinGW builds no longer being released, it seems that `zlib1.dll` is being packaged with MinGW PR verification builds now.
