### ISSUE TITLE
Missing HLE command 'EnsureIdTokenCacheAsync' in 'IManagerForApplication' (AM)

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#2547]
Super Meat boy gets stuck on launching page without the update 1.0.4
[yuzu_log before update.txt](https://github.com/yuzu-emu/yuzu/files/3257957/yuzu_log.before.update.txt)

still gets stuck on launching page after the update 1.0.4 but windows freeze too
[yuzu_log after update.txt](https://github.com/yuzu-emu/yuzu/files/3257964/yuzu_log.after.update.txt)

By the way,i cut out some thousands of the last lines since they were the same and i couldnt upload them(>10mb).

<meta name="titleids"  content="01004F8006A78000">

**Comment by Hexagon12** [comment]
`[ 182.979275] Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:151: Assertion Failed! Unknown / unimplemented function 'EnsureIdTokenCacheAsync': port='IManagerForApplication' cmd_buf={[0]=0x4, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x2, [6]=0x0, [7]=0x0, [8]=0x49434653}`

Unimplemented service commands

**Comment by DarkLordZach** [comment]
Some more info:
This seems to be used to update the Network Account Service IDs (or some arrangement of those words) internally, which appear to be NEX user IDs.

**Comment by MysticExile** [comment]
Also needed for Youtube
[Reporter log](https://github.com/yuzu-emu/yuzu/files/3694363/01003A400C3DA000_2019-10-06T14-50-30.zip)

**Comment by fluffapparition** [comment]
@MysticExile #2950

**Comment by MysticExile** [comment]
That's a different service though. Both are needed for Youtube.

**Comment by FearlessTobi** [comment]
Used by Brawlhalla

**Comment by Morph1984** [comment]
Used by SSBU

**Comment by fluffapparition** [comment]
@MysticExile Noted.

**Comment by callmenemo491** [comment]
Appears in ACNH, with EA475.
`[ 150.810262] Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:154: Assertion Failed! Unknown / unimplemented function 'EnsureIdTokenCacheAsync': port='IManagerForApplication' cmd_buf={[0]=0x6, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x2, [6]=0x0, [7]=0x0, [8]=0x49434653}`

**Comment by choppymaster** [comment]
Needed for:
* Superbeat: Xonic EX 
* Pang Adventures
* The Mahjong 
Ryujinx/Ryujinx#629

**Comment by choppymaster** [comment]
* Prison Architect
* Feather
* Pokemon Let's go pickachu 
* The Binding of Isaac: Afterbirth+
* Zombie gold rush
* Worms W.M.D
* Crashlands
* Toy Stunt Bike: Tiptop's Trials
* Disco Dodgeball Remix
* Monkey King: Master of the Clouds
* INFINITE mini golf
* Horizon Chase Turbo
* Evil defenders
* RBI Baseball 17, 18 and 19
* Eagle island
* Mushroom wars 2
* Mutant Mudds collection
* Legendary fishing
* Flinthook
* FM touch 2018
* Castlestorm
* Aca neogeo, arcade archives, Sega ages
* Riddled corpes EX
* Sine Mora EX 
* Urban Trial Playground 
* star wars pinball
* Disc jam
* sky bolt zack
* Ghost blade hd
* synaptic drive
* nyan cat
* down well
* possibly other games I think this is an important thing to implement
