### ISSUE TITLE
Missing HLE service command 'GetSharedMemoryNativeHandle' in 'time:u'

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#2556]
Stuck on launching screen, speed >5000%, game fps =0
![thief](https://user-images.githubusercontent.com/51413997/59042562-546c7c80-8883-11e9-81e2-6e375eff8440.png)

Log file:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3262149/yuzu_log.txt)

**Comment by Hexagon12** [comment]
`[  11.584276] Kernel.SVC <Warning> core\hle\kernel\svc.cpp:GetInfo:926: (STUBBED) Unimplemented svcGetInfo id=0x0000000000000016`

Requires `TotalMemoryUsedWithoutMmHeap (22, 6.0.0+)` from `svcGetInfo`.

**Comment by Hexagon12** [comment]
Could you retest the game on the latest Canary? This specific command is now implemented.

**Comment by EliasM108** [comment]
Still stuck on launching screen. Now the speed is around 1500%
LOG FILE:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3271137/yuzu_log.txt)

**Comment by Hexagon12** [comment]
The game now requires a new service command.

```[  20.119260] Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:151: Assertion Failed! Unknown / unimplemented function 'GetAccumulatedSuspendedTickChangedEvent': port='ISelfController' cmd_buf={[0]=0x6, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x6, [6]=0x0, [7]=0x0, [8]=0x49434653}```

**Comment by C3ndre** [comment]
Hello, i don't know if this can help but they fixed this issue on Ryujinx. 

https://github.com/Ryujinx/Ryujinx/pull/702

**Comment by FearlessTobi** [comment]
This isn't Ryujinx.

**Comment by C3ndre** [comment]
I know. Like i said "IF". Both emulator try to load the same game from the same console. Even if one is coded in C# and the other in C++, it could help to find a fix.

**Comment by EliasM108** [comment]
> I know. Like i said "IF". Both emulator try to load the same game from the same console. Even if one is coded in C# and the other in C++, it could help to find a fix.

You got a point

**Comment by Hexagon12** [comment]
This service command is now implemented, please try the game now with the latest Canary.

**Comment by EliasM108** [comment]
> This service command is now implemented, please try the game now with the latest Canary.
Nothing has visually changed. Game fps = 0, Speed ~1450%/100%

Log File:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3317808/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
`[  41.452608] Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:154: Assertion Failed! Unknown / unimplemented function 'GetSharedMemoryNativeHandle': port='time:u' cmd_buf={[0]=0x6, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x1, [6]=0x0, [7]=0x0, [8]=0x49434653}
`
