### ISSUE TITLE
Missing HLE service command 'IsStandardNetworkSystemClockAccuracySufficient' in 'time:u'

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#2569]
When playing without the update, the game runs smoothly with minor sound and visual glitches. But with the update it gets stuck on launching page with speed >5000% and game fps >3000
LOG FILE:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3268942/yuzu_log.txt)

Mod edit: Needed by ARMS >1.0.0.

<meta name="titleids"  content="01009B500007C000">

**Comment by Hexagon12** [comment]
`[  98.232020] Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:151: Assertion Failed! Unknown / unimplemented function 'IsStandardNetworkSystemClockAccuracySufficient': port='time:u' cmd_buf={[0]=0x4, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x1, [6]=0x0, [7]=0x0, [8]=0x49434653}`

Missing service commands.

**Comment by slashiee** [comment]
[Reporter Log](https://github.com/yuzu-emu/yuzu/files/3380479/01009B500007C000_2019-07-10T23-10-32.zip)

**Comment by slashiee** [comment]
Fixed in master/mainline with the merge of #3271, requesting a close.

**Comment by FearlessTobi** [comment]
Fixed by #3271.
