### ISSUE TITLE
Super Meat Boy doesn't boot anymore + Log file

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#2585]
Some weeks before super meat boy could boot only without the update. Now its doen't boot at all. Keeps loading on launching screen and creates a log file around 50MB.
LOG FILE:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3294080/yuzu_log.txt)

**Comment by Hexagon12** [comment]
Duplicate of #2547, you reported the issue before.
