### ISSUE TITLE
The Legend of Zelda Breath of the wild doesn't boot with the update + Log file

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#2586]
When playing without the update 1.5.0 the game starts normally, but if i check the update then the game stops at launching screen showing around 8 game fps
Log file:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3298128/yuzu_log.txt)

<meta name="titleids"  content="01007EF00011E000">

**Comment by FernandoS27** [comment]
bcat is currently off for maintenance, will be fixed soon.

**Comment by Hexagon12** [comment]
#2539 has now been merged and the 1.5.0 update now goes ingame. Closing...
