### ISSUE TITLE
Doom 2016 Patreon Build

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#2588]
I got this error in the Yuzu June 12 Patreon Build, after all the intro logos were done, and prior to getting into the menus. I tried to run Doom in the Yuzu Canary 2384, and I did not get an error message, but instead it crashed and said 1000+ FPS

This is the error I got in the Yuzu Patreon Build
![Capture](https://user-images.githubusercontent.com/7824443/59641197-a8eae400-912e-11e9-9b54-2c9faf43fd8d.PNG)

**Comment by Hexagon12** [comment]
Patreon build support goes in our Discord. GitHub is not applicable for Patreon build issues.

**Comment by niko1point0** [comment]
I’m sorry
