### ISSUE TITLE
Minecraft broken Patreon Build

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#2589]
Minecraft on Yuzu Canary can reach the menus just fine (haven't tried gameplay). However, in the June Patreon Build of Yuzu, Minecraft crashes while the Mojang splash screen is being drawn, and the FPS counter goes 1000+. I did not see any pop-ups or error messages

**Comment by Hexagon12** [comment]
Patreon build support goes in our Discord. GitHub is not applicable for Patreon build issues.

**Comment by niko1point0** [comment]
Oh I’m sorry
