### ISSUE TITLE
Yuzu hangs up linux 

### ISSUE THREAD

**Issue by Cleverking2003** [yuzu-emu/yuzu#2599]
I am trying to run games on linux but it hangs up the whole system. I am using Ubuntu 19.04 and have Nvidia gtx 950m with proprietary driver version 418. The emulator works fine on Windows

**Comment by Yvar192** [comment]
This could very possibly be your system running out of ram, or it just hanging for a while because of your CPU. Try waiting for a few minutes.

**Comment by EchoDuplication** [comment]
This is not an issue with Yuzu, display hangs are caused by graphics drivers usually.

**Comment by Cleverking2003** [comment]
@EchoDuplication Will nouveau work better then?

**Comment by Hexagon12** [comment]
nouveau does not work with Yuzu.

**Comment by EchoDuplication** [comment]
@Cleverking2003 Usually the problem is related to the desktop environment, display manager, or graphics driver. You can probably get help solving the issue [here](https://askubuntu.com/help) or [here](https://ubuntuforums.org/).
