### ISSUE TITLE
Texture Glitch in Zelda Breath of the Wild + Log file + Screenshot

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#2600]
The game initially loaded all the textures normally but suddenly the ground got glitched.
Screenshot:
![screenshot](https://user-images.githubusercontent.com/51413997/59868695-3d0cb380-939a-11e9-8fbf-b20e049aa367.png)

Log File:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3311491/yuzu_log.txt)

<meta name="titleids"  content="01007EF00011E000">

**Comment by Hexagon12** [comment]
This is a issue that will get solved with the new texture cache that's coming soon.

**Comment by C3ndre** [comment]
This happen also in the Cemu version of BOTW in some place.

**Comment by MysticExile** [comment]
This issue has been fixed by PR [2601](https://github.com/yuzu-emu/yuzu/pull/2601)
