### ISSUE TITLE
Yuzu Linux LLVM ERROR: out of memory

### ISSUE THREAD

**Issue by dukenukemx** [yuzu-emu/yuzu#2605]
I'm using Linux Mint 19 with FX 8350 and RX 470.  When I start Mario Odyssey it crashes and terminal shows this error.

qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
QObject::connect: invalid null parameter
libpng warning: iCCP: known incorrect sRGB profile
LLVM ERROR: out of memory
Aborted (core dumped)

**Comment by FernandoS27** [comment]
how much RAM you got?

**Comment by dukenukemx** [comment]
I have 12GB of system memory.

**Comment by FernandoS27** [comment]
@jroweboy any ideas what could it be? Unless he does not have free memory from other programs, this seems a problem in llvm.

**Comment by MerryMage** [comment]
He's actually running out of RAM (it's the [default OOM message](https://github.com/llvm-mirror/llvm/blob/6b547686c5410b7528212e898fe30fc7ee7a70a3/lib/Support/ErrorHandling.cpp#L164) when exceptions aren't enabled).

**Comment by dukenukemx** [comment]
I am using the latest MESA drivers thanks to Oibaf's PPA.  I tried updating today to see if it was fixed but still the same error.

**Comment by FernandoS27** [comment]
You should monitor your RAM usage and make sure you have atleast 8Gb free when executing yuzu.

**Comment by dukenukemx** [comment]
This is what "free -m" shows.  

                   total        used        free      shared  buff/cache   available
Mem:          11965        4339      449          81        7176        7229
Swap:          2047           0         2047

**Comment by Hexagon12** [comment]
Is the issue still present? Try increasing your swap partition to at least 10 GB.

**Comment by ReinUsesLisp** [comment]
Closing as this is not on yuzu's stack. It's true that yuzu uses more memory than what we would like to, but that should be tracked on a separate issue.
