### ISSUE TITLE
Windows mingw builds don't contain the yuzu executable anymore

### ISSUE THREAD

**Issue by FearlessTobi** [yuzu-emu/yuzu#2610]
This is a regression, recently introduced by https://github.com/yuzu-emu/yuzu/pull/2474.

Sample error log: https://travis-ci.org/yuzu-emu/yuzu-canary/jobs/550466063

**Comment by fluffapparition** [comment]
How the hell did this even happen :female_facepalm:

**Comment by FearlessTobi** [comment]
This is fixed.
