### ISSUE TITLE
Missing HLE service command 'SetCpuBoostMode' in 'ICommonStateGetter' (AM)

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2616]
use by Super mario maker 2
![unknown](https://user-images.githubusercontent.com/18043258/60300183-cf660780-9904-11e9-9b63-bc1ca6d2c544.png)

<meta name="titleids"  content="01009B90006DC000">

**Comment by Hexagon12** [comment]
[Reporter log](https://github.com/yuzu-emu/yuzu/files/3340483/01009B90006DC000_2019-06-28T21-59-39.txt)
