### ISSUE TITLE
Missing HLE service command 'GetAccessLogVersionInfo' in 'fsp-srv'

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2617]
also needed for super mario maker 2 and mortal combat 11 
![image](https://user-images.githubusercontent.com/18043258/60300361-3683bc00-9905-11e9-8fab-f834ce58e6c3.png) 
[log.zip](https://github.com/yuzu-emu/yuzu/files/3336608/log.zip)

<meta name="titleids"  content="01009B90006DC000,0100F2200C984000,010086C00AF7C000">

**Comment by Hexagon12** [comment]
* Needed for Yokai Watch 4
