### ISSUE TITLE
Missing HLE service command 'QueryAudioDeviceOutputEvent' in 'IAudioDevice' (audren:u)

### ISSUE THREAD

**Issue by Hexagon12** [yuzu-emu/yuzu#2620]
* Needed for Super Mario Maker 2
* Needed for Yokai Watch 4

<meta name="titleids"  content="01009B90006DC000,010086C00AF7C000,010089700150E000">

[Reporter log](https://github.com/yuzu-emu/yuzu/files/3340491/01009B90006DC000_2019-06-28T22-03-38.txt)

**Comment by ReaperOfSouls1909** [comment]
Needed for dragon marked for death

**Comment by bunnei** [comment]
Resolved by #2658
