### ISSUE TITLE
Missing implementation of TransactionId type 2 'SetBufferCount' in VI service 

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#2621]
* Needed for Super Mario Maker 2

<meta name="titleids"  content="01009B90006DC000">

**Comment by hottestchilipepper** [comment]
Hi, I'm new on yuzu.
I'm struggling to implement 'SetBufferCount', just now at getting informations about this.
I see that I should define 'IGBPSetBufferCountRequestParcel' and 'IGBPSetBufferCountResponseParcel'.
Then at the 'TransactParcel' function I will implement the case of 'SetBufferCount' transaction.
However, at this link [https://switchbrew.org/wiki/Nvnflinger_services#TransactParcel](url) and any other place, there are no information about structs of 'IGBPSetBufferCountRequestParcel' and 'IGBPSetBufferCountResponseParcel'.
Do I have to just test and see values of memory? or are there some docs about these?

**Comment by hottestchilipepper** [comment]
I will modify 'buffer_queue' to implement this one

**Comment by ZiggyDev** [comment]
> I will modify 'buffer_queue' to implement this one

It should be the same as [Android's implementation](https://github.com/shashlik/old-android-frameworks-native/blob/master/libs/gui/IGraphicBufferProducer.cpp#L73), try reading those docs to see if you can find something useful.

Anyway, I can confirm this is an issue with Animal Crossing: New Horizons after locally building with [PR#3531](https://github.com/yuzu-emu/yuzu/pull/3531).

**Comment by hottestchilipepper** [comment]
> Anyway, I can confirm this is an issue with Animal Crossing: New Horizons after locally building with [PR#3531](https://github.com/yuzu-emu/yuzu/pull/3531).
I confirmed it while I tried to play it.
Thank you for your help.
I will implement this.

**Comment by choppymaster** [comment]
Is this the IGraphicBufferProducer: 2 command?

**Comment by choppymaster** [comment]
Needed for: 
* Animal crossing: new horizons 
* 
* Crayon Shin-chan The Storm Called Flaming Kasukabe Runner! 
* Ring fit Adventure 
* Woodle tree 2
* seabed
* wenjia 
* Prison princess
* heaven dust
* tools up
* doom 64
* Manticore - Galaxy on Fire
* blades of time

**Comment by german77** [comment]
This is already implemented. https://github.com/yuzu-emu/yuzu/blob/master/src/core/hle/service/nvflinger/buffer_queue_producer.cpp#L63
