### ISSUE TITLE
Amiibo Support Broken

### ISSUE THREAD

**Issue by Tabby4675** [yuzu-emu/yuzu#2625]
Greetings!

So, I recently dumped my Amiibo files and decided to use them on Yuzu in SMO as they worked perfectly on Cemu and Citra, but when I tried, to my surprise, it didn't work at all.

What I did was I configured the Directional Pad's Right button as H on my keyboard since that button's needed for using Amiibo, when I pressed it, the Amiibo circle appeared, I quickly went to the File tab, selected Load Amiibo option and... it didn't work. The circle was there tho and I went off when I pressed H again and released it.

Another piece of info. After some findings by BSoD Gaming, it seems that Amiibo support broke somewhere between Canary 1237/1686 & Canary 2411/Latest

A mod on Yuzu's Discord told me a log with `*:Debug` filter would be helpful, so here it is, attached below.

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/3338330/yuzu_log.zip)

<meta name="titleids"  content="0100000000010000">

**Comment by DarkLordZach** [comment]
This is because we don't properly emulate the application area, amongst other things.
We are currently discussing/exploring options on how to emulate this effectively.

**Comment by BubblyPopper** [comment]
probably fixed in last mainline
amiibo worked for me in super mario 3d world + bowser's fury

**Comment by Tabby4675** [comment]
@BubblyPopper Indeed it has been, but I've noticed that some special amiibo are not recognised by yuzu for some reason.

For instance, all the wedding amiibo for SMO, when loaded, are seen as normal Mario, Peach and Bowser amiibo, and not their special counterpart. This makes some costumes in the game impossible to get.

And, I am confused on how amiibo can be used in Splatoon 2, when I load the file it says that it has game data on it, asks if I want to overwrite it or quit. Selecting the Delete option does nothing and the amiibo is not summoned, Quit just quits the process. Any help would be apprerciated.

**Comment by Fobenga** [comment]
None of the Animal Crossing New Horizons Amiibos are working too, tried almost everything, if anyone knows a solution, feel free to share it.

**Comment by diogeek** [comment]
wedding-styled amiibos are still not recognized as of now, again if anyone has a solution feel free to share it

**Comment by german77** [comment]
Implementation of amiibos is incomplete. It needs to be completed before they work for all games

**Comment by HidekoHaruna** [comment]
It still doesn't work on version 910...

**Comment by nhasa01** [comment]
Amiibo suport is not working on Zelda BotW too! Amiibo rune is enabled but when i load the file it gives an error sound. Is there any way of overcome this problem?

**Comment by german77** [comment]
See the linked PR. It should fix all these issues

**Comment by cootshk** [comment]
This is still broken for me in 1426
