### ISSUE TITLE
Missing HLE service command 'SetSockOpt' in 'bsd:u'

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#2627]
* Needed for DOOM
* Needed for Minecraft Bedrock Edition

<meta name="titleids"  content="0100416004C00000,0100D76006EF8000,0100D71004694000">

[Reporter log](https://github.com/yuzu-emu/yuzu/files/3340542/0100D71004694000_2019-06-28T22-09-44.txt)

**Comment by Aushera** [comment]
Needed for Little Town Hero

**Comment by Morph1984** [comment]
Implemented in #4397
