### ISSUE TITLE
Missing HLE service command 'GetCurrentIpAddress' in 'IGeneralService' (nifm:u)

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#2630]
* Needed for Minecraft Bedrock Edition

<meta name="titleids"  content="0100D71004694000">

[Reporter log](https://github.com/yuzu-emu/yuzu/files/3340572/0100D71004694000_2019-06-28T22-08-47.txt)

**Comment by bukyapavankumar** [comment]
@ReinUsesLisp  this is the one you are looking for

**Comment by bukyapavankumar** [comment]
@GDhex12 Implemented in #4397

**Comment by ReinUsesLisp** [comment]
Implemented in the mentioned pull request. Closing.
