### ISSUE TITLE
Deleting games installed to the NAND through the yuzu UI

### ISSUE THREAD

**Issue by Eloeri** [yuzu-emu/yuzu#2633]
The current process of deleting a game title, DLC/Update, that has been previously installed to the nand through the yuzu UI is a bit confusing. You need to guess for the file you want to delete based on the file size.

When a file is installed to the nand, the file is meant to be renamed to the NCAID of that particular title, however only part of the file is hashed resulting in the incorrect NCAID. 

Even if the file is already titled by it's [NCAID](https://imgur.com/AfPyKw1), the [new name is incorrect](https://imgur.com/gwWgf32) while the hash is still the same as the previous name.

Seeing as how the current method to find the right file to delete is impossible without generating your own hash of the file to check against some sort of database, please incorporate a function within the UI to delete the file without having to navigate folders and alphanumeric files that would confuse a casual user of the program.

**Comment by Tenome** [comment]
+1

**Comment by Eloeri** [comment]
In my previous example, I was using the Breath of The Wild update to show that yuzu was not generating the correct NCAID of the file when installing. After testing today, the correct NCAID is generated by yuzu, and can be used to determine which file is which. 

![dab3](https://user-images.githubusercontent.com/42394653/80312151-4bd9a900-87a9-11ea-9e40-d34abb07fefb.jpg)

The necessity of being able to uninstall files as easy as they are installed, however, is still required.

**Comment by GizmoTheGreen** [comment]
I don't know if I'm dumb but I just bothered trying yuzu out and I fully expected a "delete title" on the right click on the title... I copied my switch's whole nintendo folder over and it 170gigs xD so I need to delete some games.

**Comment by MolotovCherry** [comment]
Well, for what it's worth. I used a tool called nstool to extract the nsp file, then searched the nand for the file name (NOT the extension(s) after the name! Only the name!), and I was able to locate them and delete them manually.

**Comment by chriolant** [comment]
The closed status of this issue might not be correct because the "Remove" context menu does not remove installed games, at the moment it only removes their DLCs, Updates, etc.

**Comment by Eloeri** [comment]
Considering that you don't install base games, all that would need to be removed are DLC and Updates.

**Comment by GoodSoulGermany** [comment]
Now have the same issue. Installed a game in NAND (all is shown as 0x00000000000000) and the game itself is not working. Now I try to get rid of the game but am unable to do so. 

How to remove that game?

**Comment by Inui-senpai** [comment]
You can remove "empty" titles in NAND, just follow these steps:
1. Create folder wherever you like (e.g. D:\Games\yuzu_gamedir) and copy your **base games** NSPs in it;
2. Launch yuzu and add your folder from the Step 1;
3. After that all titles installed in NAND should have their own indexes instead of "0x0000000000000000" and have type "NCA";
4. Backup all your saves and mods, just to be safe (RMB -> Open game mods location and Open game saves location);
5. Press RMB on the title installed in NAND and select Remove -> Remove all installed game contents and click on Yes;
6. Just press OK in all appearing windows;
7. And voila, title was disappeared from the "Installed NAND titles" column. Now just return all your mods and saves and reinstall DLCs and Updates.

**Comment by reloxx13** [comment]
How to delete old stuff from games the rom was deleted on hdd and cannot be dumped again?   
There is no way to easy find and delete them.    
An easy context menu entry to delete game which ask to 'really delete?' with a checkcbox 'also delete assets (dlc updates cache mods etc).     
Currently you have to delete everything one by one urself before deleting the game rom or its unclear what to use from the menu to delete it completly.    
You could reduce it to 2 menu entries by delete game and delete all cache.    
Alternativly just add a global menu item int the top toolbar to delete all unused content/stuff.
![grafik](https://github.com/yuzu-emu/yuzu/assets/14855001/78c46457-45a6-4c8c-9cc2-70b41f8a061a)

**Comment by robastala** [comment]
Same problem has reloxx13. Rom deleted now what?... how to remove the Updates or DLC, etc...

The easiest way for now is to remove (Updates, DLC, etc...) of the Rom and then remove the game.

Would really need an easy way to cleanup and delete option to regain space on the hard drive. Also to be on the safe side a one button to save settings and backup all saves.
