### ISSUE TITLE
Missing implementation of motion controls

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#2635]
While playing Super Mario odyssey the game asks you to shake your controller to do some moves, but when using a regular controller it is impossible.

<meta name="titleids"  content="0100000000010000,01009B500007C000,01007EF00011E000">

**Comment by BSoDGamingYT** [comment]
Motion controls are currently not implemented in yuzu. There is no missing shake button

**Comment by EliasM108** [comment]
> Motion controls are currently not implemented in yuzu. There is no missing shake button

i mean it needs a button to simulate the shaking of the controller

**Comment by BSoDGamingYT** [comment]
It needs motion controls to be implemented. They will be eventually

**Comment by NovaStorm64** [comment]
Wouldn't it be simple to add support for BetterJoyforCemu?

**Comment by budafuko** [comment]
you do not need to shake to do that move. if you rotate your joystick around clockwize or counter clockwize 1.5 times mario will spin at which point u can throw ur hat and do the move

**Comment by EliasM108** [comment]
> you do not need to shake to do that move. if you rotate your joystick around clockwize or counter clockwize 1.5 times mario will spin at which point u can throw ur hat and do the move

It works, thank you!

**Comment by legend800** [comment]
This shouldn't be closed - there's still 6 moves that are impossible without motion. I wish Nin. would have patched out that dependency but never did. :(

![2020-05-27 10_02_49-Window](https://user-images.githubusercontent.com/20983844/83050385-5df57400-a001-11ea-9d7f-c972f0e229fa.png)

**Comment by german77** [comment]
This has been implemented in #4594
