### ISSUE TITLE
Bug: (Splatoon 2) Unable to go inside ink, can't swim on walls

### ISSUE THREAD

**Issue by SyedOmarNoor** [yuzu-emu/yuzu#2640]
I'm having this issue in the Splatoon 2 tutorial where, when I try to swim, My inkling doesn't go into the ink that they shot. they just swim on top of it, and when i try to jump into a wall covered with ink, my inkling doesn't go into the ink, it just falls back to the ground. This is not good, as there is a part of the tutorial where you have to climb up a wall using ink.

Some other bugs I saw:
-Camera Up/Down don't work (CemU has that problem as well, so i'm not worrying too much, probably motion controls again)
-some amounts of text don't display (for example the last options for making your inkling ("Yes" and "No")) (CemU had that problem as well, so i'm not worrying too much)

Other than that, it's better than expected. Because of my hardware config, Splatoon 2 runs at 15-30 fps.

Specs of laptop:
CPU: i7-4700HQ
Graphics card: Intel HD 4600 and Nvidia GTX 760M (I, of course, use the 760M for yuzu) (760M is similar/less than the 750)
OS: Windows 7 Home Premium x86-64
Nvidia driver version: 417.35 (from 11th/12/2018)
Yuzu version: Canary 2414

**Comment by ReinUsesLisp** [comment]
Splatoon 2 counts the number of samples passed in a renderpass to detect team's ink. In other words, it uses the GPU to query wether you are on ink and what teams'.

yuzu hits an assert in `maxwell_3d` due to the lack of query 21. In OpenGL terms, this is `GL_SAMPLES_PASSED`. We need to properly emulate host queries if we want ink to work.

**Comment by slashiee** [comment]
The ink issue is fixed in master/mainline with the merge of #3409, though only with async disabled.

**Comment by MysticExile** [comment]
Closing this because this is fixed, the motion controls are part of a seperate issue and a PR is open to fix this already.

**Comment by NicholasFlamy** [comment]
> The ink issue is fixed in master/mainline with the merge of #3409, though only with async disabled.

I know this is old but which async? I'm having the same problem (on android yuzu) but the inkling is bouncing in and out of the ink and it works normally when my FPS is exactly 60 I heard that enabling asynchronous rendering fixes it, but that's not an option on Android yuzu.

**Comment by NicholasFlamy** [comment]
I'm gonna create a new issue.

**Comment by NicholasFlamy** [comment]
> -some amounts of text don't display (for example the last options for making your inkling ("Yes" and "No")) (CemU had that problem as well, so i'm not worrying too much)

Those are default driver issues, Mesa Turnip doesn't have that issue.

**Comment by SyedOmarNoor** [comment]
> > -some amounts of text don't display (for example the last options for making your inkling ("Yes" and "No")) (CemU had that problem as well, so i'm not worrying too much)
> 
> Those are default driver issues, Mesa Turnip doesn't have that issue.

Is that available for Windows 7? Forgot to originally mention that

**Comment by NicholasFlamy** [comment]
> > > -some amounts of text don't display (for example the last options for making your inkling ("Yes" and "No")) (CemU had that problem as well, so i'm not worrying too much)
> > 
> > 
> > Those are default driver issues, Mesa Turnip doesn't have that issue.
> 
> Is that available for Windows 7? Forgot to originally mention that

I should have thought about the date of this post. I was referring to the Android version. But, have you tried the latest (supported) graphics drivers? It could also, be that Windows 7 is just not supported anymore.
