### ISSUE TITLE
Missing implementation of NVDEC and it's codecs

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#2643]
This is a issue tracker requested by @DarkLordZach.
There's a PR currently opened that stubs required nvchannel ioctls for games to pass ingame movies (#1703), however, the author decided that it would be too much work for him to properly implement NVDEC.

- [ ] H.264 support
- [ ] H.265 support
- [ ] VP8 support
- [ ] VP9 support

**Comment by bukyapavankumar** [comment]
[  29.974875] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
could you stub this too @DarkLordZach

**Comment by bytesandwich** [comment]
Hey I got the same thing in super mario odyssey:
```
[ 202.552669] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:GetWithId:94: (STUBBED) called
[ 202.553152] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:SetAndWaitWithId:86: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 202.553163] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:operator ():27: Assertion Failed!
Unimplemented ioctl
```
I wonder if it's possible for me to work on this?

**Comment by matthewatman** [comment]
unimplemented ioctl for pokemon sword [#3921](https://github.com/yuzu-emu/yuzu/issues/3921)

**Comment by jojodunet** [comment]
> Hey I got the same thing in super mario odyssey:
> 
> ```
> [ 202.552669] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:GetWithId:94: (STUBBED) called
> [ 202.553152] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:SetAndWaitWithId:86: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
> [ 202.553163] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:operator ():27: Assertion Failed!
> Unimplemented ioctl
> ```
> 
> I wonder if it's possible for me to work on this?

@bytesandwich Could you please get in touch with @GoldenX86 on this discord server https://discord.gg/u77vRWY ? He will allow you to help devs team on the project.

**Comment by jojodunet** [comment]
Hi team, is it possible to use Ryujinx NVDEC code for video in Yuzu ? https://github.com/Ryujinx/Ryujinx/pull/443

This would be great and will help go ahead as https://github.com/yuzu-emu/yuzu/pull/3996 for example

**Comment by Zhao-Qi** [comment]
Same thing happened for Persona 5 Scramble (01005BD010872000). The game keep locking on initial load. Haven't figured out a way to go around this.

```
[ 180.933775] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:SetAndWaitWithId:86: (STUBBED) called, input_id=0x1, min=0xFFFFFC18, max=0xFFFFFFFF
[ 180.933804] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:GetWithId:94: (STUBBED) called
[ 180.933845] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:221: (STUBBED) called
[ 180.970482] Core <Warning> core\hle\kernel\hle_ipc.cpp:WriteBuffer:313: skip empty buffer write
[ 180.971696] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
```
