### ISSUE TITLE
Missing HLE service command 'GetNintendoAccountUserResourceCacheForApplication' in 'IManagerForApplication' (acc:u0)

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#2644]
* Needed for Pokken Tournament DX

<meta name="titleids"  content="0100B3F000BE2000">

[Reporter log](https://github.com/yuzu-emu/yuzu/files/3341638/0100B3F000BE2000_2019-06-29T10-53-26.txt)

**Comment by Morph1984** [comment]
- Needed by SSBU

**Comment by ToxaGaming** [comment]
- Needed by Super Nintendo Entertainment System - Nintendo Switch Online (v1.7.0 tested)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5516082/yuzu_log.txt)

This game works fine on the base version, but at some point it got an update (unsure of which) that broke it and it has since stopped working.

**Comment by choppymaster** [comment]
Needed for Mario Kart 8 deluxe

**Comment by vrichomme** [comment]
I have added the following code(see patch below) and recompiled yuzu and it works fine. 
No more crash here.


```
diff --git a/src/core/hle/service/acc/acc.cpp b/src/core/hle/service/acc/acc.cpp
index 3ec0e1eca..c28c91f0e 100644
--- a/src/core/hle/service/acc/acc.cpp
+++ b/src/core/hle/service/acc/acc.cpp
@@ -508,7 +508,7 @@ public:
             {1, &IManagerForApplication::GetAccountId, "GetAccountId"},
             {2, nullptr, "EnsureIdTokenCacheAsync"},
             {3, nullptr, "LoadIdTokenCache"},
-            {130, nullptr, "GetNintendoAccountUserResourceCacheForApplication"},
+            {130, &IManagerForApplication::GetNintendoAccountUserResourceCacheForApplication, "GetNintendoAccountUserResourceCacheForApplication"},
             {150, nullptr, "CreateAuthorizationRequest"},
             {160, &IManagerForApplication::StoreOpenContext, "StoreOpenContext"},
             {170, nullptr, "LoadNetworkServiceLicenseKindAsync"},
@@ -534,6 +534,12 @@ private:
         rb.PushRaw<u64>(user_id.GetNintendoID());
     }
 
+    void GetNintendoAccountUserResourceCacheForApplication(Kernel::HLERequestContext& ctx) {
+        LOG_WARNING(Service_ACC, "(STUBBED) called");
+        IPC::ResponseBuilder rb{ctx, 2};
+        rb.Push(RESULT_SUCCESS);
+    }
+
     void StoreOpenContext(Kernel::HLERequestContext& ctx) {
         LOG_WARNING(Service_ACC, "(STUBBED) called");
         IPC::ResponseBuilder rb{ctx, 2};
```

**Comment by ToxaGaming** [comment]
> * Needed by Super Nintendo Entertainment System - Nintendo Switch Online (v1.7.0 tested)
>   [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5516082/yuzu_log.txt)
> 
> This game works fine on the base version, but at some point it had an update (unsure of which) that broke it (gets stuck trying to load the game list) as it requires this function. It has since stopped working after said update.

I forgot to report this, but about a week ago I redumped both NES and SNES NSO with their latest updates and this no longer seems to be an issue. Both are able to have their catalogues loaded and and can boot their games.

**Comment by vrichomme** [comment]
yes but the fix does not harm and make it works when people dont' have the right version, what do you think ?
It's better to have an implemented function even if it only returns ok.

**Comment by german77** [comment]
Stubbed in #5977

**Comment by SlayerLord22** [comment]
need Nickelodeon All-Star Brawl

**Comment by german77** [comment]
Are you sure about this? It's been implemented since last year
