### ISSUE TITLE
Missing HLE service command 'StoreSaveDataThumbnail' in 'IAccountServiceForApplication' (acc:u0)

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#2645]
* Needed for Arcade Archives VS. Super Mario Bros

<meta name="titleids"  content="010021D00812A000">

[Reporter log](https://github.com/yuzu-emu/yuzu/files/3341672/010021D00812A000_2019-06-29T10-59-32.txt)

**Comment by Hexagon12** [comment]
* Happens in ACA NEOGEO METAL SLUG 2

**Comment by FearlessTobi** [comment]
Used in Arcade Archives LIFEFORCE.

**Comment by german77** [comment]
Stubbed in #5765
