### ISSUE TITLE
Possible inaccuracies in the VI Parcel function

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#2649]
The games below will try to read VI buffers and fail this assertion: https://github.com/yuzu-emu/yuzu/blob/master/src/core/hle/service/vi/vi.cpp#L72, which in turn causes these games to svcBreak with a guest assertion.

* Needed for Team Sonic Racing
* Needed for The World Ends With You
* Needed for Undertale (docked mode only)
* Needed for Deltarune (docked mode only)

<meta name="titleids"  content="0100C1500B82E000,010084B00B36E000,010029D00B72A000,010080B00AD66000,010023800D64A000">

**Comment by slashiee** [comment]
Undertale and Deltarune were fixed with #2666

**Comment by FearlessTobi** [comment]
Needed for Overcooked 2.

**Comment by benderscruffy** [comment]
Is this still an issue

**Comment by gidoly** [comment]
mentioned game now works so i'll close it for time being
