### ISSUE TITLE
ARMS Crashes often during gameplay + Log

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#2655]
The game crashes randomly during a match. Log file contains every event, from booting the game till the final tutorial showdown(where it crashed).

Log File (Part 1-8):
[yuzu_log1.txt](https://github.com/yuzu-emu/yuzu/files/3343243/yuzu_log1.txt)
[yuzu_log2.txt](https://github.com/yuzu-emu/yuzu/files/3343244/yuzu_log2.txt)
[yuzu_log3.txt](https://github.com/yuzu-emu/yuzu/files/3343270/yuzu_log3.txt)
[yuzu_log4.txt](https://github.com/yuzu-emu/yuzu/files/3343271/yuzu_log4.txt)
[yuzu_log5.txt](https://github.com/yuzu-emu/yuzu/files/3343272/yuzu_log5.txt)
[yuzu_log6.txt](https://github.com/yuzu-emu/yuzu/files/3343273/yuzu_log6.txt)
[yuzu_log7.txt](https://github.com/yuzu-emu/yuzu/files/3343274/yuzu_log7.txt)
[yuzu_log8.txt](https://github.com/yuzu-emu/yuzu/files/3343275/yuzu_log8.txt)

**Comment by Hexagon12** [comment]
This issue tracker is for developers and not for support requests. Crashes or any kind of instability reports should be discussed in our Discord server.
