### ISSUE TITLE
RA BeetlePSX and mGBA cores fail to boot

### ISSUE THREAD

**Issue by Hexagon12** [yuzu-emu/yuzu#266]
Tested with the latest Nightly build.

Yuzu crashes with `[  11.852889] Debug <Critical> core\hle\kernel\process.cpp:Kernel::Process::MirrorMemory:<lambda_2a99f60e6db09029b87ae9ae414b5702>::operator ():282: Assertion Failed!
Backing block doesn't exist for address`

Full log [**here**](https://pastebin.com/cSEGtsVy), happens both with Unicorn and Dynarmic.

**Comment by greggameplayer** [comment]
@Hexagon12 no i think it isn't a 0x80 issue because on Dynarmic log it don't return fallback issue 0x80 in the console. So it might be another error in my opinion.

**Comment by MoochMcGee** [comment]
Can someone check to see if this still happens?

**Comment by Hexagon12** [comment]
This was a issue on the cores themselves.
