### ISSUE TITLE
Missing HLE service command 'DeactivateNpad' in 'hid'

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2663]
Needed By Diablo NX [devilution-nx](https://github.com/lantus/devilution-nx)
[log.zip](https://github.com/yuzu-emu/yuzu/files/3346929/log.zip)

also used by OpenLara

**Comment by ReinUsesLisp** [comment]
This is used on homebrew de-initialization.
