### ISSUE TITLE
Memory Leakage When Playing Super Mario Maker 2

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [yuzu-emu/yuzu#2665]
Playing in 8GB Computer, How ITS POSSIBLE!?

**Comment by ogniK5377** [comment]
Can you post a log file?

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
no

**Comment by ogniK5377** [comment]
We're unable to help you without a log file, sorry!
Please refer to https://community.citra-emu.org/t/how-to-upload-the-log-file/296 for retrieving a log

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
WRONG

**Comment by ogniK5377** [comment]
Without a log we cannot help, sorry!
