### ISSUE TITLE
Missing HLE service command 'CloseLayer' in 'IApplicationDisplayService' (VI)

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2666]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3353364/yuzu_log.txt)
used in harry potter!

**Comment by Hexagon12** [comment]
Please get a reporter log for this command too.

**Comment by MysticExile** [comment]
Used in 
* DELTARUNE Chapter 1
* Mystery of Solarus DX (Homebrew)

**Comment by MysticExile** [comment]
Fixed with #3272

**Comment by bunnei** [comment]
Fixed
