### ISSUE TITLE
Game update version number missing in game's title screens

### ISSUE THREAD

**Issue by Eloeri** [yuzu-emu/yuzu#2668]
No matter the version applied to Super Mario Maker, even if the latest system files are included in yuzu's virtuan nand, the version number does not appear in the bottom right corner of the start menu.

**Comment by Hexagon12** [comment]
* Happens in Xenoblade Chronicles 2

**Comment by simontime** [comment]
It should be reading it from the game's control nca / control.nacp.
Presumably the ipc cmd that handles it has been stubbed?

**Comment by MysticExile** [comment]
Fixed
