### ISSUE TITLE
Missing HLE service command 'SetNpadJoyAssignmentModeSingle' in 'hid'

### ISSUE THREAD

**Issue by Kewlan** [yuzu-emu/yuzu#2671]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3357250/yuzu_log.txt)

Used when booting Pokémon Let's Go in docked mode.

**Comment by Hexagon12** [comment]
Invalid issue. You wouldn't boot the game with joycons docked on the console while it's docked on a actual Switch.

**Comment by Yvar192** [comment]
That's still a valid missing HLE service though?

**Comment by DarkLordZach** [comment]
I own this game, and it is definitely possible to dock the console with the joycons on it and then play on the TV using a 3rd joycon or the pokeball plus.

Reopening as this is still a valid issue.

**Comment by Hexagon12** [comment]
_SetNpadJoyAssignmentModeSingleByDefault_ is already implemented, the command the game calls is actually _SetNpadJoyAssignmentModeSingle_ (a typo in our hid code)

**Comment by Hexagon12** [comment]
* Needed for Ring Fit Adventure (only on certain controller styles, like Left Joycon)
