### ISSUE TITLE
Homebrew text not loading correctly

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#2672]
Hi, this has been a known bug for a while, but something recent has caused the bug to get worse. 
[hello-world.zip](https://github.com/yuzu-emu/yuzu/files/3360956/hello-world.zip)
Prevoiusly, it would wrongly draw all text twice.
Now, it draws text twice, and additionally has a bad flicker effect

**Comment by niko1point0** [comment]
In the upcoming years, I’m hoping to start a high school programming class for Nintendo Switch that utilizes Yuzu, starting with Hello World text, leading to an ASCII Tetris game, and ending with animated MD2 models. I fully understand if this issue is not a priority, I trust that the developers know what is most important for the emulator, but it would be convenient for the students if this bug gets fixed. Thank you everyone working on the emulator for all your hard work

**Comment by MysticExile** [comment]
#2793

**Comment by ReinUsesLisp** [comment]
Closing as this issue seems to be addressed.
