### ISSUE TITLE
Software Keyboard Issue

### ISSUE THREAD

**Issue by yair2000** [yuzu-emu/yuzu#2678]
After your announcement of you, fixing the software keyboard bug I immeditally started checking whether it's true or not. Turns out that the bug wasn't fixed at all. When I started a new Pokemon, Lets Go Eeeve", when asked to give the player a name, the emulator crashes like in previous Yuzu builds. I'm using Yuzu Canary 2435 (HEAD-71a7f50)

**Comment by CaptV0rt3x** [comment]
@yair2000 If you carefully re-read the tweet/announcement, you would find that the said fix for software keyboard isn't available on Canary builds yet. It is currently available for patrons via patreon builds but fret not, it will soon be available for Canary users (1 week).

**Comment by ogniK5377** [comment]
The software keyboard issue has been fixed for patreon builds and will be merged into canary in a few days after extensive testing

**Comment by yair2000** [comment]
Ahh. I didn't realize that because there was no mentioning when it will arrive in Canary builds

**Comment by Yvar192** [comment]
wasn't the rule that issues got closed as soon as they're fixed in master?
