### ISSUE TITLE
Missing HLE service command 'GetAccumulatedSuspendedTickValue' in 'ISelfController' (AM)

### ISSUE THREAD

**Issue by Hexagon12** [yuzu-emu/yuzu#2682]
* Needed for Yokai Watch 4

<meta name="titleids"  content="010086C00AF7C000">

[Reporter log](https://github.com/yuzu-emu/yuzu/files/3364873/010086C00AF7C000_2019-07-06T19-59-26.txt)

**Comment by DarkLordZach** [comment]
Addressed by #2684
