### ISSUE TITLE
Homebrew Algorithm Crashes

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#2698]
Hi everyone. I am working on a WIP homebrew racing game with A-star path following. I wrote two versions of the algorithm. One works on Physical Switch and Yuzu, one is more optimized, but only works on Physical Switch

Broken NRO (works on physical Switch)
[racinggame.zip](https://github.com/yuzu-emu/yuzu/files/3370881/racinggame.zip)

Working code (Yuzu and physical Switch)
[game_Astar.zip](https://github.com/yuzu-emu/yuzu/files/3370884/game_Astar.zip)

Broken code (works on physical Switch)
[Astar.zip](https://github.com/yuzu-emu/yuzu/files/3370885/Astar.zip)

By the way, if you are familiar with how a-star works, gCost is the distance from start, hCost is distance to end, and fCost is the sum of gCost and hCost. One of the things I changed, was that in the original code (that works on Yuzu), the deque was in order of lowest gCost by mistake, and the new code has the deque in order of lowest fCost (which is correct, but wont work on Yuzu). By the way, in the old code, the deque is just named "deque". Just so everybody knows, it is a deque of "unvisited nodes".

**Comment by FernandoS27** [comment]
Why was this closed?

**Comment by niko1point0** [comment]
Because I realized the A-star algorithm was not the problem, I made a new issue. The real problem was Yuzu 2445 crashing the homebrew, not a change in the algorithm @FernandoS27 

https://github.com/yuzu-emu/yuzu/issues/2699
