### ISSUE TITLE
Canary 2444 broke homebrew that worked in Canary 2443

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#2699]
[racinggame.zip](https://github.com/yuzu-emu/yuzu/files/3370949/racinggame.zip)
This homebrew works perfectly fine on a physical nintendo switch. If you see black textures, that is 100% unrelated. The point is that on 2442, the game runs without crashing, and on 2445, the game crashes after the first frame of the scene is drawn

**Comment by niko1point0** [comment]
I also just tested Super Mario Odyssey, and a spinning textured cube. Both work on Yuzu Canary 2442, but crash after rendering the first frame in Yuzu Canary 2445

**Comment by FernandoS27** [comment]
could you test which version in specific is cauing crashes and if it's still there on latest canary?

**Comment by niko1point0** [comment]
Works in 2443, crashes in 2444, I did not see a Windows zip for 2447, so I couldn't test that one, and it crashes in 2446 as well

**Comment by FernandoS27** [comment]
@DarkLordZach could you investigate if any of this PRs caused this homebrew to crash: https://github.com/yuzu-emu/yuzu-canary/commit/8f5aae30746f678eed69d8f311e9b5634a8dd12c
https://github.com/yuzu-emu/yuzu-canary/commit/7b28f954c900536887ce2580d1e654e913580809

It seems to be the only difference between canary 2443 and 2444

**Comment by niko1point0** [comment]
Do I have to compile the PRs manually? Or is there a way to download a built version of each PR?

**Comment by niko1point0** [comment]
This is fixed in 2460

**Comment by niko1point0** [comment]
I take it back, the homebrew is fixed, but Mario Odyssey still does not boot anymore

**Comment by niko1point0** [comment]
Everything works for me now in canary 2463
