### ISSUE TITLE
(Probably long-term goal) connect to switch controllers?

### ISSUE THREAD

**Issue by Elronnd** [yuzu-emu/yuzu#27]
There is [this repository](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering) which basically exists to reverse engineer the controllers.  It'd be cool if yuzu used it in order to support switch joycons.

**Comment by drsirmrpresidentfathercharles** [comment]
Using that repo, I made a Joy-Con driver a few weeks ago in Node.js. If anyone would like to look at it for a reference, it is [here](https://github.com/drsirmrpresidentfathercharles/joycon).

**Comment by ajithmel** [comment]
wow you actually made a way for it to connect, this is good.

**Comment by bunnei** [comment]
Yes, this is of course a long term goal, but not really something that we need an issue tracking at this time. Going to close this.
