### ISSUE TITLE
Can't install yuzu: Install destination ("") is not empty.

### ISSUE THREAD

**Issue by Edralos** [yuzu-emu/yuzu#2701]
Hello there,I just wanted to install through the installer you provided but I only get: Install destination ("") is not empty.
It is the first time I want to install the software and it happens right after selecting canary or nightly version

**Comment by Zeroksas** [comment]
Currently yuzu is automatically to directory C:\Users\?????????\AppData\Local\yuzu. Where ???????? is your username. If directory is not empty then your mentioned error pops-up. Just delete yuzu folder and try to install again.

**Comment by chris062689** [comment]
Please upload a log file from the installer Edralos.

**Comment by Yuutowa997** [comment]
Just make a new folder and then paste the installer in it. Now run the installer and it'll work.

**Comment by Hexagon12** [comment]
This is a bug tracker for developers and not a support forum.

If you require support, please either contact our Discord or the Citra community forums (they're used for yuzu too).

As for your issue, try deleting the yuzu folder in C:/Users/your username/AppData/Local

**Comment by robinhugy** [comment]
no yuzu folder but i see that error message..

**Comment by SolarPortal** [comment]
i found that if the installer was in the downloads or a windows directory with permissions and you havent installed yuzu yet, then place it in a folder on another drive and run it from there, worked for me. :)

**Comment by dhhash** [comment]
[https://youtu.be/stTySIuiHpc](url) check this for fix . Thank me Later .

**Comment by NotRuben** [comment]
> [https://youtu.be/stTySIuiHpc](url) check this for fix . Thank me Later .

thank you so much!

**Comment by TrueXE** [comment]
hey still doesn't work for me it keep saying ''file not empty''

**Comment by neohshanray** [comment]
same
