### ISSUE TITLE
Mystery of Solarus DX Missing HLE service 'CloseLayer': port='IApplicationDisplayService'

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2712]
https://github.com/carstene1ns/zsdx/tree/switch-port Source code

https://www.switchbru.com/appstore/zips/solarus.zip HB app

[log.zip](https://github.com/yuzu-emu/yuzu/files/3379672/log.zip)

**Comment by Hexagon12** [comment]
Please report this game in #2666 instead of making a new issue.

Closing as duplicate.
