### ISSUE TITLE
OpenLara missing HLE Services 'DeactivateNpad': port='hid' and 'Exit': port='ISelfController'

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2713]
[log.zip](https://github.com/yuzu-emu/yuzu/files/3379684/log.zip)

Source code https://github.com/XProger/OpenLara/releases

https://www.switchbru.com/appstore/zips/Openlara.zip app 

missing Services 'DeactivateNpad': port='hid' and 'Exit': port='ISelfController'

**Comment by DarkLordZach** [comment]
Duplicate of #2664 & #2663
