### ISSUE TITLE
Missing HLE service command 'CreateApplicationAndRequestToStart' in 'IApplicationFunctions' (AM)

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#2718]
* Needed for Super Smash Bros. Ultimate (after changing language)

<meta name="titleids"  content="01006A800016E000">

[Reporter log](https://github.com/yuzu-emu/yuzu/files/3381099/01006A800016E000_2019-07-10T22-04-50.txt)

**Comment by german77** [comment]
Stubbed in #7293
