### ISSUE TITLE
Missing HLE service command 'GetBusHandle' in 'hidbus'

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#2721]
* Needed for Starlink: Battle for Atlas

<meta name="titleids"  content="01002E500B0A0000,01002CC003FE6000">

[Reporter log](https://github.com/yuzu-emu/yuzu/files/3381326/01002CC003FE6000_2019-07-11T12-38-17.txt)

**Comment by Hexagon12** [comment]
* Needed for Ring Fit Adventure
