### ISSUE TITLE
Touchscreen issues in Let's Go Eevee

### ISSUE THREAD

**Issue by Tenshinen** [yuzu-emu/yuzu#2727]
I'm having issues with getting the touchscreen working properly in Let's Go Eevee. It worked a few months ago, but recently for one reason or another it has stopped working. When I go into the Partner Play option in the menu, clicking and moving my cursor has Eevee's gaze follow the cursor, but no actual reaction to it. Same with menus, can't click things. Yet the touchscreen is enabled in the options, with the default options selected. 

Can anyone reproduce this? Currently using Canary 2474.

**Comment by Spelly92** [comment]
I have the same problem. Is there already a solution?

**Comment by Tenshinen** [comment]
Have not found anything yet. Even reinstalled Yuzu a few times, nothing.

**Comment by fluffapparition** [comment]
What version were you using when you last had it working? And what version do you recall it stopped working at specifically?

**Comment by Tenshinen** [comment]
I don't specifically remember when it worked last but it was early 2019. Then a few updates pass by until I notice the touch screen issues.
