### ISSUE TITLE
Broken GPU clearing in Super Mario Maker 2 3D World levels

### ISSUE THREAD

**Issue by slashiee** [yuzu-emu/yuzu#2728]
Using Canary 2474, it is broken in both undocked and docked.

Undocked
![undocked_canary](https://user-images.githubusercontent.com/15317421/61174840-d0c93e00-a55a-11e9-8b0b-ab41d761b96a.png)
Docked
![docked_canary](https://user-images.githubusercontent.com/15317421/61174841-d1fa6b00-a55a-11e9-8fa0-53e30971688d.png)

PR #2696 partially fixes this issue, docked mode still doesn't work.

**Comment by FernandoS27** [comment]
yeah I'm looking at a better solution.

**Comment by FernandoS27** [comment]
Fixed by #2735

**Comment by Hexagon12** [comment]
The issue is not solved. The proposed PR is not merged yet.
