### ISSUE TITLE
Crash while loading shader cache for Pokemon Let's Go Eevee

### ISSUE THREAD

**Issue by Kewlan** [yuzu-emu/yuzu#2729]
- Canary 2474

Loading the disk shader cache can still crash yuzu at a specific shader. I got this one by going through the Elite 4 and using all of my team's moves.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3389147/yuzu_log.txt)
[savedata.zip](https://github.com/yuzu-emu/yuzu/files/3389218/savedata.zip)

**Comment by sakshatshinde** [comment]
I have the same issue. When I add the shader cache yuzu just crashes and deletes the file from the transferable folder. It runs fine on the next boot when it creates it's own new shader cache file.

**Comment by Kewlan** [comment]
@sakshatshinde That's another thing separate from this issue and works as intended. You were trying to use an outdated cache that got incompatible after the new texture cache got implemented.

**Comment by sakshatshinde** [comment]
@Kewlan thanks for the info!

**Comment by RyanDaMFLion** [comment]
@Kewlan, do you know of a shader cache that’s not outdated? I’m able to run let’s go eevee at 30fps but without the shader cache it’s around 20 with stuttering in the more intense areas.

**Comment by Kewlan** [comment]
Because the start of this issue would be while playing the game, but not noticed until you load the shader cache when restarting the game it was hard to test. But it seems now that no one has had it happen for a while, including myself, so it's likely it has been fixed.
