### ISSUE TITLE
Super Smash Bros Won't Boot on linux

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2731]
Base Arch with all needed dependices kernel 5.2 and nvidia drivers 430.26-9

Game version is 1.0.0

No save used

log below

canary 2475 

[log.zip](https://github.com/yuzu-emu/yuzu/files/3389404/log.zip)

**Comment by Hexagon12** [comment]
Is this issue fixed yet?

**Comment by lat9nq** [comment]
This issue can be closed. SSBU 1.0.0 - 7.0.0 is bootable on Linux on both EA and Mainline.
