### ISSUE TITLE
Can't play downloaded courses in Super Mario Maker 2?

### ISSUE THREAD

**Issue by Ridley12** [yuzu-emu/yuzu#2732]
When I get the course packs from [this thread](https://gbatemp.net/threads/super-mario-maker-2-top-weekly-course-dumps.542180/) and copy everything from one difficulty setting to the save data folder of a same-difficulty-named profile and I go to play a level from said difficulty setting (because the courses show up under Downloaded Courses for each profile), basically everything is normal except that I cannot move Mario and the timer does not decrease. The same thing happens if I try to play a level in Story Mode.

**Comment by Xevets** [comment]
I have this same issue.  I was able to play the levels only by saving a bunch of dummy levels and then renaming the downloaded levels to replace the dummy levels.  But that is tedious.  I see some people report no problems with playing downloaded levels, would love to figure out what is the difference.

**Comment by Ridley12** [comment]
> I have this same issue.  I was able to play the levels only by saving a bunch of dummy levels and then renaming the downloaded levels to replace the dummy levels.  But that is tedious.  I see some people report no problems with playing downloaded levels, would love to figure out what is the difference.

I didn't rename the levels, but I did make separate profiles for organization.

**Comment by Hexagon12** [comment]
Was this issue fixed?

**Comment by Ridley12** [comment]
> Was this issue fixed?

No, it's still not fixed.

**Comment by Ridley12** [comment]
Update: Tried with the current 2602, and it still is happening.

**Comment by Ridley12** [comment]
I'm gonna try something. I'm going to try extracting the level packs to each "Week" folder because currently, they're still in the zip folder.

**Comment by Ridley12** [comment]
Nope, didn't fix it either.

**Comment by FearlessTobi** [comment]
Why did you close this?

**Comment by pyromancer5** [comment]
still have the same problem it was working fine but now it doesnt

**Comment by Ridley12** [comment]
> Why did you close this?

Honestly? I have no idea, lol.

**Comment by pyromancer5** [comment]
it working on Ryujinx steam deck fine...guess am gona play only on Ryujinx  while the rest on yuzu problem solved tho i like yuzu more but whatever
