### ISSUE TITLE
Missing HLE service command 'DecodeInterleavedWithHardware' (tentative) in 'IHardwareOpusDecoderManager'

### ISSUE THREAD

**Issue by AloXado320** [yuzu-emu/yuzu#2733]
- Needed for Super Smash Bros. Ultimate since 3.0.0

[Reporter log](https://github.com/yuzu-emu/yuzu/files/3390538/01006A800016E000_2019-07-14T18-25-59.zip)

**Comment by Hexagon12** [comment]
Changed the title to reflect the internal command name based on the reporter log's SDK symbols.

**Comment by Hexagon12** [comment]
* Needed for Witcher 3

**Comment by Hexagon12** [comment]
Fixed by #3400
