### ISSUE TITLE
Memory leak on "Tales of Vesperia: Definitive Edition" caused by pr #2675

### ISSUE THREAD

**Issue by Zeroksas** [yuzu-emu/yuzu#2745]
It was first introduced on canary-2453:
![image](https://user-images.githubusercontent.com/44953731/61460481-b8945d00-a966-11e9-82aa-48021b13cf82.png)
This eventually causes yuzu to crash when all memory is used.
It was ok on canary-2452:
![image](https://user-images.githubusercontent.com/44953731/61459795-6dc61580-a965-11e9-98ac-0f51e39cf9f7.png)

https://github.com/yuzu-emu/yuzu/pull/2675 was first-time merged on canary-2453.
Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3406724/yuzu_log.txt)

**Comment by Zeroksas** [comment]
FIxed by https://github.com/yuzu-emu/yuzu/pull/2783

**Comment by legoj15** [comment]
That pull request has not been merged yet into master, only into canary

**Comment by Morph1984** [comment]
PR has been merged this can be closed now
