### ISSUE TITLE
Issue with audout, thread & buffer related

### ISSUE THREAD

**Issue by simontime** [yuzu-emu/yuzu#2746]
When playing a buffer with audout using any libnx function that uses a wait event, unlike real hardware, it doesn't hang the thread until the buffer is released, and therefore plays way too fast; skips, etc.

I have made a test app which demonstrates this issue, attached.
[test.zip](https://github.com/yuzu-emu/yuzu/files/3410676/test.zip)

**Comment by MysticExile** [comment]
This issue has been fixed.
