### ISSUE TITLE
Super Mario Maker 2:  Flashing objects on 3D World levels

### ISSUE THREAD

**Issue by legend800** [yuzu-emu/yuzu#2750]
In SMM2, in 3D World levels, there's flashing junk/objects that randomly appear, small and large, mostly black objects (impossible to screen grab). 

This is NOT present on the July 4th Patreon build. It is only present on Canary (checked 7/18 going back to ~7/10 and issue is always present).

Checked various settings including:  with/without async, with/without shader cache, docked/undocked, etc.

To repro: Start "Hello 3D World" level and play through for a min.

Config:
i7-6700k @ 4GHZ
GeForce GTX 1080
16GB RAM
Windows 10 64-bit

**Comment by MysticExile** [comment]
This appears to have been fixed. If you think/know this is not fixed, please open a new issue.

**Comment by legend800** [comment]
Yep, fixed, thanks for closing!
