### ISSUE TITLE
Various Unity-based game crashes on load

### ISSUE THREAD

**Issue by Peenicks** [yuzu-emu/yuzu#2751]
After launching Yuzu Canary or Nightly, I try to load up Dandy Dungeon by itself and the emulator crashes post loading splash screen (NOTE: Dandy Dungeon game does not pop up, it just crashes or hangs and it crashes at the Switch loading screen). I'm not sure if it changes the fact that it's an eShop game.

I tried installing file to Nand and applying the update that comes with it but it also reacts in the same way. I attached the log file.

Best regards!

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3413913/yuzu_log.txt)

<meta name="titleids"  content="0100dfb00d808000,0100e46006708000,010079200e85c000,010072800cbe8000,010082400bcc6000,010061d00db74000,0100b2e00f13e000">

**Comment by Hexagon12** [comment]
Please get a new log with the `*:Debug` filter present in Emulation - Configure - Debug

**Comment by Peenicks** [comment]
Log with Debug filter uploaded

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3414082/yuzu_log.txt)

**Comment by Hexagon12** [comment]
* Happens in Terraria
* Happens in Omega Labyrinth Life

**Comment by Morph1984** [comment]
- Happens in PC Building Simulator

**Comment by Hexagon12** [comment]
* Happens in Untitled Goose Game

**Comment by Hexagon12** [comment]
* Happens in Ori and the Blind Forest

**Comment by Hexagon12** [comment]
* Happens in Shipped

**Comment by Hexagon12** [comment]
* Happens in Pokemon Mystery Dungeon: Rescue Team DX

**Comment by Hexagon12** [comment]
* Happens in Puzzle & Dragons GOLD

**Comment by FearlessTobi** [comment]
This has been fixed by SciresM in a recent PR.
