### ISSUE TITLE
Missing HLE service command 'IsVibrationPermitted' in 'hid'

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2755]
[log.zip](https://github.com/yuzu-emu/yuzu/files/3415877/log.zip)
Needed for The Legend Of Kay
without it during the first fight the game crashes on the missing service

**Comment by ReaperOfSouls1909** [comment]
was resolved with PR #2836

**Comment by Hexagon12** [comment]
The PR isn't merged yet.

**Comment by Morph1984** [comment]
PR has been merged this can be closed.
