### ISSUE TITLE
Compile the project, prompt the following error, how to deal with？

### ISSUE THREAD

**Issue by chenchizhao** [yuzu-emu/yuzu#2760]
![image](https://user-images.githubusercontent.com/6883210/61694333-d0535300-ad63-11e9-93b4-4747940e7ff3.png)

![image](https://user-images.githubusercontent.com/6883210/61694371-dfd29c00-ad63-11e9-8d89-01f0267dda4c.png)

**Comment by Hexagon12** [comment]
Mac OS is not supported by yuzu, even if you would manage to compile it.

**Comment by fluffapparition** [comment]
I like how theres just absolutely no context to this
