### ISSUE TITLE
Stardew Valley is broken

### ISSUE THREAD

**Issue by TuntunYeh** [yuzu-emu/yuzu#2767]
Stardew Valley base game won't load.
The program throws an exception after executing line 26 in [assert.h](https://github.com/yuzu-emu/yuzu/blob/b0ff3179ef8f4ebb6ccd2bdc9bccc64e3212edee/src/common/assert.h#L26)
Visual Studio message: "yuzu.exe has triggered a breakpoint. occurred"

Then is thows another exception at line 79 in [arm_unicorn.cpp](https://github.com/yuzu-emu/yuzu/blob/b0ff3179ef8f4ebb6ccd2bdc9bccc64e3212edee/src/core/arm/unicorn/arm_unicorn.cpp#L79)
Visual Studio message: "Exception thrown at 0x0000000000000000 in yuzu.exe: 0xC0000005: Access violation executing location 0x0000000000000000. occurred"

This exception seems to be unrecoverable and the game does not load.

**Comment by Hexagon12** [comment]
Please upload a log file.

**Comment by ReaperOfSouls1909** [comment]
Try using Canary instead of nightly also be in docked mode

**Comment by ReaperOfSouls1909** [comment]
![image](https://user-images.githubusercontent.com/18043258/61897652-e68d1a80-aeed-11e9-9e0f-7af2f5479861.png)
Canary

**Comment by Hexagon12** [comment]
You seem to hit assertions, which indicate that you're running on master / nightly. Please run the game on Canary and if any new issues arise, please inform us.
