### ISSUE TITLE
Splatoon 2 shadows not working correctly.

### ISSUE THREAD

**Issue by MysticExile** [yuzu-emu/yuzu#2771]
Canary 2518 commit: d1a04b3
![Canary](https://user-images.githubusercontent.com/30736337/62059044-c7122c80-b222-11e9-9c7a-072ea404c649.png)
Nintendo Switch
![Switch](https://user-images.githubusercontent.com/30736337/62059159-fa54bb80-b222-11e9-887c-dfbeb19d769a.jpg)

As you can see the shadows are pitch black on yuzu. Which on hardware is not the case.

<meta name="titleids"  content="01003BC0000A0000">

**Comment by DrSTONEmc2** [comment]
oui

**Comment by bakugo** [comment]
This issue has become somewhat worse since last year. It may be an overall lighting issue and not just shadows. Here's what the starting area of the DLC used to look like on a build from January 2019 (almost exactly the same as hardware):

![Base Profile Screenshot 2019 01 10 - 14 55 05 46](https://user-images.githubusercontent.com/6014513/81491961-aedc3d00-928b-11ea-87dd-fc3103a0a19d.png)

And here's what it looks like on the latest EA build (520) regardless of GPU settings:

![Base Profile Screenshot 2020 05 10 - 05 38 54 54](https://user-images.githubusercontent.com/6014513/81491970-cd423880-928b-11ea-9a2d-e591031de22d.png)

**Comment by herosilas12** [comment]
How close is this to getting fixed?
the shadows are still REALLY bad
and the lighting looks like the bloom slider is at 3000%

please tell me this is close to done

**Comment by funtimeandrefoxy** [comment]
From an unknown update to yuzu early access, sometimes when I leave the inventory, some dark textures turn blue or green. I don't know if there are other possibilities to obtain this failure
![Sem Título](https://user-images.githubusercontent.com/59577497/93130724-db391780-f6ca-11ea-91d0-91f44ca4e254.png)

**Comment by funtimeandrefoxy** [comment]
> From an unknown update to yuzu early access, sometimes when I leave the inventory, some dark textures turn blue or green. I don't know if there are other possibilities to obtain this failure
> ![Sem Título](https://user-images.githubusercontent.com/59577497/93130724-db391780-f6ca-11ea-91d0-91f44ca4e254.png)

![image](https://user-images.githubusercontent.com/59577497/93136815-74b8f700-f6d4-11ea-92cf-c316d9203a7e.png)
Although most of the dark areas have been corrected, some areas are still dark and I got these shaders corrupted (image above) while playing.

**Comment by Zhao-Qi** [comment]
Shadows/lighting has been a big issue when I was playing Xenoblade Chronicles 2 in a multi-level scene with day light. Looks like the shadows are calculated with incorrect depth. For example the bright cube in the screenshot below seems to be some further away objects which shouldn't be visible.

![image](https://user-images.githubusercontent.com/8041059/93722200-b1fd0900-fb5a-11ea-8a02-9ff0151aa1ad.png)

![image](https://user-images.githubusercontent.com/8041059/93722208-c04b2500-fb5a-11ea-99e1-3c6fcc37608a.png)

**Comment by lidortoz** [comment]
Is there a fix?

**Comment by MysticExile** [comment]
@lidortoz No, if there was a fix this issue wouldn't have been open :)

**Comment by choppymaster** [comment]
Texture cache rewrite and this issue is:

Fixed.

**Comment by v1993** [comment]
If this is fixed since TCR, should this be closed?

**Comment by MysticExile** [comment]
As @v1993 mentioned, this was fixed by the texture cache rewrite.
