### ISSUE TITLE
pokemon lets go pikachu corrupted save files please delete your save files

### ISSUE THREAD

**Issue by yixiatros** [yuzu-emu/yuzu#2775]

**Comment by yixiatros** [comment]
I tried to get back in pokemon lets go and send me in a menu, like the menu that you choose language,tha only has a text that say "your files have been corrupted please delete your save files".
Is there any way to fix my files or am I screwed?

**Comment by Hexagon12** [comment]
This is a bug tracker for developers and not a support forum.

If you require support, please either contact our Discord or the Citra community forums (they're used for yuzu too).
