### ISSUE TITLE
hyrule warrior / Dynasty warrior 8 running in single core

### ISSUE THREAD

**Issue by thesweetiger** [yuzu-emu/yuzu#2776]
Just reporting issue with both game 
when in game, both game run only on a single thread so the game run slowly

Out of that dynasty warrior 8 definitive edition run like a charm if you don't care about fps on canary 2519

**Comment by BSoDGamingYT** [comment]
This is not an issue. It is a current deliberate design decision of the emulator. Usage of multiple cores/threads will be added in future (Possibly) once the emulator has developed/progressed more.
