### ISSUE TITLE
Fruity homebrew - doesn't boot

### ISSUE THREAD

**Issue by Hexagon12** [yuzu-emu/yuzu#278]
Tested with the latest Nightly build (153).

The homebrew app crashes with `[  12.976120] Debug <Critical> core\hle\service\vi\vi.cpp:Service::VI::IHOSBinderDriver::TransactParcel::<lambda_8b2c6f78cd02c175cda987d561176cf9>::operator ():541: Assertion Failed!
Unimplemented`

Full log [**here**](https://pastebin.com/QSrLVTmZ), happens both with Unicorn and Dynarmic.

**Comment by bunnei** [comment]
Can you share a binary as well as link to the source code? Thanks.

**Comment by Hexagon12** [comment]
The crash was caused by missing files in sdmc:/switch/fruity/data.
