### ISSUE TITLE
Fire Emblem: Three Houses - cannot load save data

### ISSUE THREAD

**Issue by Hexagon12** [yuzu-emu/yuzu#2780]
Fire Emblem: Three Houses currently faces an issue that makes the game unloadable if the save has been imported from anywhere else apart from yuzu itself.

If one tries to load a save file that has been generated by an actual Switch, they will be greeted with a message saying that the save data has been corrupted:

![1](https://i.imgur.com/SlCjhwL.png)

This issue doesn't seem to be related to user account UUIDs - if a yuzu generated save is brought to the Switch, it loads fine. Yuzu loads it's own generated saves too.

Reproduction steps:
 1. Select Continue on the title screen
 2. Select the Chapter 3 save from the save file I have included in this issue
 3. Ignore the message about losing bookmarked data

Save file for reproduction: 
[FE3H Save Data.zip](https://github.com/yuzu-emu/yuzu/files/3482245/FE3H.Save.Data.zip)

<meta name="titleids"  content="010055D009F78000">

**Comment by MysticExile** [comment]
This is no longer an issue.

**Comment by goldenx86** [comment]
As far as I can tell, this is related to differences in updates and DLC, it doesn't seem to be a file system problem.

**Comment by ThisNekoGuy** [comment]
I'm getting this issue with Yuzu 1452; the game claims some saves are corrupt but will load others fine despite the same game update and DLCs being used that I dumped from my console. And I know these aren't corrupt because I loaded them on my Switch to double check and they load fine on the hardware...

**Comment by ThisNekoGuy** [comment]
Can this issue be reopened? @goldenx86 @MysticExile

**Comment by ThisNekoGuy** [comment]
These are my affected saves (the autosave, slot 1 [named 0 by filename], slot 8 [named 7 by filename], and slot 25 [named 24 by filename]
[Saves.zip](https://github.com/yuzu-emu/yuzu/files/11640182/Saves.zip)
