### ISSUE TITLE
Game list

### ISSUE THREAD

**Issue by Flocke28** [yuzu-emu/yuzu#2782]
Hi All,

Any plans to chaching the game list? On every start it generate a new game list and needs a lot of time. Chaching should be help.

thanks

**Comment by FearlessTobi** [comment]
As far as I know, we are already cachong the game list.

**Comment by Flocke28** [comment]
hi.. i used the last canary build and all other builds before doesn't chache the game list. It generated a new one on every start of yuzu

**Comment by EliEron** [comment]
The PR #2431 claims to add game list caching but it doesn't really appear to work, at least on my machine. It takes about 20 seconds to build the game list each time I open Yuzu.

**Comment by Zeroksas** [comment]
Disable "Scan Subfolders". That function is slow. Then instead of 20s it only takes 1-2s.

**Comment by EliEron** [comment]
I store my games in a dedicated folder that does not have any subfolders, so as you'd expect the option makes no difference for me. Still takes between 15-20 seconds each time Yuzu opens.

**Comment by fluffapparition** [comment]
What're your specs? Jus curious.

20s isnt that bad either
