### ISSUE TITLE
Stuck in the Launching screen

### ISSUE THREAD

**Issue by xXDarkNovaXx** [yuzu-emu/yuzu#2788]
No matter which game I start somehow it always gets stuck in the launch screen
Sometimes the games start which is very rare and very often it gets stuck in the launch screen.
I've tried a few things, but unfortunately nothing helps.
I'm currently using the Canary version because the Nightly always crashes

I have a Ryzen 2600x, Gigabyte 1070 G1 Gaming, 16GB Ram and 8GB Pagefile

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3502127/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
Your game is using the unimplemented applet 0x0C.

**Comment by Hexagon12** [comment]
This is a bug tracker for developers and not a support forum.

If you require support, please either contact our Discord or the Citra community forums (they're used for yuzu too).
