### ISSUE TITLE
Compile Yuzu Canary Appveyor

### ISSUE THREAD

**Issue by EmulationChannel** [yuzu-emu/yuzu#2790]
Compile yuzu canary appveyor code error Details MSB3073 https://stackoverflow.com/questions/17075279/how-do-i-fix-msb3073-error-in-my-post-build-event
![2019-08-18 (2)](https://user-images.githubusercontent.com/52056267/63228069-79a33280-c1c4-11e9-8a09-f523279ccf64.png)

**Comment by Hexagon12** [comment]
Invalid issue.
