### ISSUE TITLE
SSBU does not start and gets stuck on the loading screen!

### ISSUE THREAD

**Issue by Luffykun007** [yuzu-emu/yuzu#2792]
I'm trying to start SSBU on yuzu but the game gets stuck on the launch screen and doesn't start.

![Capturar](https://user-images.githubusercontent.com/26087621/63367266-cff1ac00-c351-11e9-8d5f-a6c55669ecd1.JPG)

Yuzu Canary #2531  7620ee5

Config:
I5 6400  @3.3 GHZ
Geforce GTX 960
8GB Ram
Windows 10 64 Bits Version 1903 (18362.295)

Log: [SSBU.zip](https://github.com/yuzu-emu/yuzu/files/3521730/SSBU.zip)

**Comment by ReaperOfSouls1909** [comment]
I had the same error it was due to a bad dump of the game

**Comment by Luffykun007** [comment]
Thanks @ ReaperOfSouls1909 I will try a new dump to see if it fixes the problem!

**Comment by Hexagon12** [comment]
This is a bug tracker for developers and not a support forum.

If you require support, please either contact our Discord or the Citra community forums (they're used for yuzu too).

**Comment by fluffapparition** [comment]
Doesnt this count as a bug report? She included logs as if she thought it was a bug.
