### ISSUE TITLE
SSBU tpose in squadstrike

### ISSUE THREAD

**Issue by theincredibleplayer** [yuzu-emu/yuzu#2795]
starting squadstrike will result in a tposing shadow of the current 2 characters playing overlaying the character portraits
![Screenshot (153)](https://user-images.githubusercontent.com/54246318/63473555-27893800-c476-11e9-98ba-d6ef944c4464.png)
![Screenshot (256)](https://user-images.githubusercontent.com/54246318/63474487-9ddb6980-c479-11e9-84a7-895e3e077d45.png)
![Screenshot (249)](https://user-images.githubusercontent.com/54246318/63474498-a59b0e00-c479-11e9-8d0b-c6f4c7f811f5.png)

**Comment by Hexagon12** [comment]
Is this issue still present on the latest mainline release?

**Comment by theincredibleplayer** [comment]
@Hexagon12 unable to test because the character portraits dont appear anymore because the mii menu rendering fix was removed
