### ISSUE TITLE
GCC build fails

### ISSUE THREAD

**Issue by Cleverking2003** [yuzu-emu/yuzu#2798]
GCC build fails with this message:

>In file included from /home/cleverking/yuzu/externals/dynarmic/src/./common/assert.h:9,
                 from /home/cleverking/yuzu/externals/dynarmic/src/./common/bit_util.h:14,
                 from /home/cleverking/yuzu/externals/dynarmic/src/./common/fp/mantissa_util.h:9,
                 from /home/cleverking/yuzu/externals/dynarmic/src/common/fp/fused.cpp:7:
/home/cleverking/yuzu/externals/fmt/include/fmt/format.h:3475:55: error: ISO C++ did not adopt string literal operator templates taking an argument pack of characters [-Wpedantic]
 3475 | FMT_CONSTEXPR internal::udl_formatter<Char, CHARS...> operator""_format() {
      |                                                       ^~~~~~~~

**Comment by Hexagon12** [comment]
What is your GCC version? OS? Full build log please?

**Comment by Cleverking2003** [comment]
GCC version 8.3.0, Ubuntu 19.04
[CMakeOutput.log](https://github.com/yuzu-emu/yuzu/files/3535572/CMakeOutput.log)

**Comment by Cleverking2003** [comment]
GCC version 8.3.0, Ubuntu 19.04
[build log.txt](https://github.com/yuzu-emu/yuzu/files/3535601/build.log.txt)

**Comment by Yvar192** [comment]
Same error occurs with GCC 9.2.0

**Comment by Cleverking2003** [comment]
This issue is caused by libfmt. Using newer versionfixes this but throws another error (because newer version doesn't have fmt/time.h).

**Comment by Cleverking2003** [comment]
To fix building, just replace externals/fmt by a newer version and change <fmt/time.h> to <fmt/chrono.h>    in src/core/reporter.cpp and src/core/hle/service/fatal/fatal.cpp.
