### ISSUE TITLE
Missing HLE service command 'GetGpuErrorDetectedSystemEvent' in 'IApplicationFunctions' (AM)

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2799]
needed by ONINAKI 
8.0.0+ services

[log.zip](https://github.com/yuzu-emu/yuzu/files/3536132/log.zip)

**Comment by AloXado320** [comment]
- Hotline Miami Collection

[Reporter Log](https://github.com/yuzu-emu/yuzu/files/3536730/0100D0E00E51E002_2019-08-23T20-09-14.zip)

**Comment by mailwl** [comment]
#2827 was merged
