### ISSUE TITLE
Better Multi-Threading Support

### ISSUE THREAD

**Issue by hotyute** [yuzu-emu/yuzu#2803]
I know this issue had been brought up before.. But given the vast improvements made over the last few updates I'd Imagine that increased multi-threading support is possible now? I haven't had a time to breeze through the code but Hasn't the Kernel and Scheduler been re-done a bit to support  this? Just asking and looking for thoughts.

**Comment by hotyute** [comment]
Please don't "Close" my Thread like that other guy's last one.. I know the dev's are fully capable and know that this needs to be looked at. However I want to know from them where it stands and what can be done to help the situation. It seems that graphics processing has come a long way in yuzu, but this core issue still stands.

**Comment by jonsn0w** [comment]
Please only use the open an issue feature for actual issues. After you get a chance to “breeze through the code” feel free to document any issues within the code itself, or offer up a plan on how to implement your request.

**Comment by jroweboy** [comment]
You seem to be already aware that this isn't the place to discuss this, so please don't open an issue here anyway.

We thank you for your enthusiasm, and hope you'll be able to contribute someday.

**Comment by Yvar192** [comment]
There is no open issue about multicore support, though. Wouldn't that make this an valid issue, since that's an emulation inaccuracy?

**Comment by FernandoS27** [comment]
Who said it’s an emulation inaccuracy? We are implementing the 4 Arm cores. We just run them concurrently in 1 host thread. Sadly using multiple host threads will take a while as we need to redesign Core Timing for it and refactor a bunch of things in the kernel

**Comment by hotyute** [comment]
I do hope to contribute someday. Right now my job has me a bit preoccupied but once I have the free time I'm going to pump straight into Yuzu. I love C++ and have been at it for quite a few years (Have built many Apps using OpenGL and C++). Anyway I'm sorry if I stirred up any troubles, just wanted sort of a brief "status" update on this as I was unable to go through the code myself at this time. 

Apologies again.
