### ISSUE TITLE
Yuzu doesn't read games located on network drives

### ISSUE THREAD

**Issue by PuffyVulva** [yuzu-emu/yuzu#2805]
I store my roms on a NAS and yuzu doesn't seem to be able to read them, but when copied across to a local drive they load up fine.
When i try to load a game from the nas i get the error below
The game list also shows all files as 0x000000000000
Using canary-2544 on windows

![yuzu error](https://user-images.githubusercontent.com/54502195/63650421-11d58480-c78e-11e9-8370-e4b4bbbc6cde.jpg)

**Comment by ExsertWizard** [comment]
Opening game dumps from a NAS works in yuzu as long as you map your NAS network directory as a network drive.

**Comment by PuffyVulva** [comment]
Thanks, I tried to add as a network drive and added an exception to the firewall but have the same problem. I'll ask on discord or something 😂👌
