### ISSUE TITLE
Core Timing: "ForceExceptionCheck" Performance cost and Accuracy

### ISSUE THREAD

**Issue by FernandoS27** [yuzu-emu/yuzu#2809]
**Background for understanding:**
Some background. Originally there were 2 methods for scheduling events into Core Timing: ScheduleEvent & ScheduleEventThreadsafe. They worked completely differently: ScheduleEvent inserted the event into the main queue directly and ran a process called "ForceExceptionCheck" (this is important) which directs the current execution's timecount to reduce to the next event. "ScheduleThreadsafe" was different and was mostly used by everything in yuzu, it didn't schedule directly to the main queue but into a temporary threadsafe queue, it also DIDN't do "ForceExceptionCheck", thus the main execution unit will continue to run even if it passed the timeout. 

**What changed recently:**
Both methods were unified into a single method that was threadsafe, scheduled directly to main queue and did "ForceExceptionCheck" in #2583 . This meant that all actions using ScheduleEventThreadsafe are now doing  "ForceExceptionCheck"., this means yuzu became more accurate but at an unpredictable cost.

**The issue:**
It turns out that for yuzu, it's very costy to use "ForceExceptionCheck". Many events are scheduled under very low cycle counts (even lower than clock cycles o_0) and worse, they reschedule after triggered. This means that the games which schedule events for very little are constantly pausing dynarmic, thus forcing a supervisor recovery, running core timing and then loading back the dynarmic execution context. This is VERY COSTY for us. In the switch this is no issue as 

1. Timer interrupts are run in core 3 without interrupting the other cores
2. They have a bunch of cycle delays we don't count  in yuzu, 
3. Rescheduling is a lot less expensive.

**The possible solutions:**
Before we weren't doing "ForceExceptionCheck" anywhere, it seems the switch didn't require that much accuracy on timing events. There are 3 possible solutions:

1. Imitate the switch and run core timing on Core 3 with a different host thread. This solution sadly requires that we implement multicore kernel, emulate the OS handling in core 3 with certain accuracy and emulate hardware interrupts accurately. The last part is unfeasible unless we use a host timer, the downside of cycle timers is that we need to track progress.
2. Limit "ForceExceptionCheck" to a set amount of cycles to reduce to the downcount. This solution is not too accurate but works pretty well on values of 4k cycles, we lose some accuracy though.
3. Just remove "ForceExceptionCheck" and do it like before. Not really fund of this solution and would prefer solution B instead.

**Comment by v1993** [comment]
This seems outdated (`ForceExceptionCheck` is nowhere to be seen in source code). Was this fixed with multicore CPU emulation?

**Comment by MysticExile** [comment]
Closing because this issue is no longer relevant
