### ISSUE TITLE
Failed to complete framework shutdown 

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#2813]
Error Message:
Failed to complete framework shutdown - Unable to start application: Os { code: 2, kind: NotFound, message: "The System Cannot find the File Specified (~translated~)" }

Log File:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3550548/yuzu_log.txt)

**Comment by Hexagon12** [comment]
This is a bug tracker for developers and not a support forum.

If you require support, please either contact our Discord or the Citra community forums (they're used for yuzu too).
