### ISSUE TITLE
Missing HLE service command 'GetAudioDeviceOutputVolumeAuto' in 'IAudioDevice' (audren:u)

### ISSUE THREAD

**Issue by Morph1984** [yuzu-emu/yuzu#2815]
Needed for Yoshi's Crafted World
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3552767/yuzu_log.txt)

<meta name="titleids"  content="01006000040C2000">

**Comment by choppymaster** [comment]
#4987

**Comment by german77** [comment]
Stubbed in #2829
