### ISSUE TITLE
Kernel: Weakness to Yield Bombing

### ISSUE THREAD

**Issue by FernandoS27** [yuzu-emu/yuzu#2816]
Yuzu's kernel and execution environment is currently very weak towards "Yield Bombing"

**What is "Yield Bombing"?**
The kernel permits threads to yield execution when they don't have anything else to do. When a thread is the only highest priority thread in a CPU Core, has no other sibling at the same priority level or higher and has no work to do and continually yields it's execution. This is called a yield bombing as the thread will keep yielding without rescheduling occurring as there's nothing else to do in that CPU Core.

Yield bombing has little to no effect in the switch as redundant yielding does not change scheduling and the core is effectively "idle". In yuzu, it brings a set of problems as A. dynarmic execution is always interrupted after yielding even if the yield is redundant (a fix will be appended to .#2364, later on) B. Core Timing does not advance on SVCs so only the few instructions executed in the thread count towards the timer. C. Process Yield Count is not implemented in yuzu, this is mostly an optimization to reduce SVCs work but has little benefit to solving the overall yield bombing problem. D. If A & B are fixed, the thread may take the core timing slice hostage, not allowing the next cores to execute any instructions, this weakness will be adressed in another issue.

**Which games exhibit this behavior?**
- Fire Emblem Three Houses.
- Xenoblade 2.
- Stardew Valley (Reported, not verified).

**Solution plan:**
1. Append the new scheduler to avoid cutting execution on redundant yields.
2. Add a set amount of ticks to Core Timing on Redundant Yields.
3. Correct the timeslice sharing issue. (placeholder for the issue reference).

**Extra info:**
This issue used to occur in our sibling project: Citra on the game Super Smash Brothers 3DS during adventure mode.

**Comment by FearlessTobi** [comment]
Confirmed to be fixed by @FernandoS27.
