### ISSUE TITLE
Games crash when skipping videos 

### ISSUE THREAD

**Issue by Aushera** [yuzu-emu/yuzu#2825]
Happens in the following games:
- ToeJam and Earl: Back in the Groove! (skipable intro video but crashes when skipped on canary)
- Just Shapes and Beats (unskipable intro video but its a short one crashes afterward on canary)
- 2064: Read Only Memories (extras menu plays a unskipable video before loading the extras menu waiting for it crashes on canary)
- Crystal Crisis (skipable intro video but crashes when skipped on canary)
- Sega Genesis/MegaDrive Classics (unskippable intro video)

Stacktrace:
![image](https://user-images.githubusercontent.com/46408167/64070356-dde5dd80-cc2b-11e9-9717-a7001273b8fc.png)
linked to something within UpdateAudioRenderer as you can bypass the issue with commenting out 
`ctx.WriteBuffer(renderer->UpdateAudioRenderer(ctx.ReadBuffer()));`
after doing that those games get past that intro video or whatever video it is
Just Shapes & Beats:
![image](https://user-images.githubusercontent.com/46408167/64070408-cb1fd880-cc2c-11e9-827d-a817e46191b6.png)
Crystal Crisis:
![image](https://user-images.githubusercontent.com/46408167/64070445-f2c37080-cc2d-11e9-9ceb-9d8d8304e371.png)
ToeJam & Earl: Back in the Groove!:
![image](https://user-images.githubusercontent.com/46408167/64070472-ad537300-cc2e-11e9-933b-114cc57782ba.png)
i was unable to get a image of 2064's extras menu due to the game softlocking after the video is over

**Comment by Hexagon12** [comment]
* Happens in Hollow Knight
* Happens in Spyro Reignited Trilogy

**Comment by Hexagon12** [comment]
* Happens in Ben 10

**Comment by Hexagon12** [comment]
* Happens in AI: The Somnium Files

**Comment by Hexagon12** [comment]
Fixed by #3159.
