### ISSUE TITLE
Missing HLE service command 'Ioctl3' in 'nvdrv'

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2843]
## LOG 
[log.zip](https://github.com/yuzu-emu/yuzu/files/3580891/log.zip)

**Comment by AloXado320** [comment]
- Hotline Miami Collection

[Reporter Log](https://github.com/yuzu-emu/yuzu/files/3582231/0100D0E00E51E002_2019-09-05T23-30-39.zip)

**Comment by Hexagon12** [comment]
* Needed for SNES - Nintendo Online

**Comment by develoqqer** [comment]
- Needed for TLoZ: Link’s Awakening Remaster

**Comment by ReinUsesLisp** [comment]
@develoqqer Please don't refer to leaked information or games. That game releases this Friday.

**Comment by develoqqer** [comment]
- Needed for The Legend of Zelda: Link's Awakening

**Comment by ReaperOfSouls1909** [comment]
Fixed as off #2873

**Comment by Hexagon12** [comment]
Please do not close the issues if the requested service has not been fully merged to master.

**Comment by ReaperOfSouls1909** [comment]
Great pr hell for the next 6 months

**Comment by Morph1984** [comment]
This has been merged now, can be closed.
