### ISSUE TITLE
Left and Right analog keyboard circle approximation issue

### ISSUE THREAD

**Issue by Fueramanta** [yuzu-emu/yuzu#2845]
Hi everyone, this used to be an issue when playing diablo 3 in rpcs3 just with keyboard, but was fixed, I was wondering if the same could be done with Yuzu. I have tried many ways to do it myself, such editing the qt-config file, and downloading Vjoy, but to no success at all.

The left analog is approximated by wasd keys in keyboard, while we can use two adjacent keys to do 45 degree of the analog, it could not do 22.5 degree, this makes 22.5 degree analog unemulatable at present.
As a test case, we can take Diablo 3>Inventory>select belt or armor
I dont know how nest could it be resolved, but I have 1 idea in mind.Mabye implement 1 key that emulates analog rotation, could be 1degree/200ms for counter closewise rotation then another key for clockwise rotation.

It would awesome if it worked the same as in rpcs3, as long as it is not too difficult to do it.

Thanks a lot.

**Comment by Fueramanta** [comment]
Isn’t there anyway to fix this?, I know I could use a controller, but can’t buy one for personal reasons. I’d really appreciate it if anybody gives me an answer.

Thanks again

**Comment by german77** [comment]
Fixed by #4905
