### ISSUE TITLE
Action Guide in Super Mario Odyssey is Broken

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2852]
![image](https://user-images.githubusercontent.com/18043258/64643329-7deaf600-d3e6-11e9-909b-2bfb8a4af39f.png)
image of Softlock after action guide is called to open.

if any other info is required give me 2 hours

<meta name="titleids"  content="0100000000010000">

**Comment by DarkLordZach** [comment]
Can you track down which canary started this?

**Comment by Miguejun** [comment]
Same problem in latest versions of yuzu

**Comment by MysticExile** [comment]
This issue appears to have been (mostly) fixed with #3477 if the softlock still occurs please open a new issue, preferably with a log too.

**Comment by ConBil16** [comment]
Hey! I am currently experiencing this problem and I don't know how to do the steps described in #3477 below I've attached my log although I am not entirely sure what that mean.
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6120503/yuzu_log.txt.old.txt)
