### ISSUE TITLE
hid: Input from Single Joycons do not register in some games.

### ISSUE THREAD

**Issue by Morph1984** [yuzu-emu/yuzu#2865]
As a result of this, some games that exclusively makes use of Single Joycons and do not work with the Pro Controller or Dual Joycons will not work properly due to no input being provided.

Keep in mind that input with single joycons would have them rotated horizontally, with the joysticks on the left.

A notable example would be Pokemon: Let's Go in docked mode, where the only accepted inputs are the left and right joycons, and the Pokeball Plus

**Comment by ogniK5377** [comment]
This is untrue, games do register single joycons.
See snipperclips:
<img width="295" alt="2019-09-17_14-32-176075e7-646a-4c5a-a4a4-d4553e4e7edd-2c935d88" src="https://user-images.githubusercontent.com/25727384/65011752-070aab80-d958-11e9-8797-fb0a3bd148e1.png">

I would also like to mention that input does work as well

**Comment by Morph1984** [comment]
#2876 got Single Joycons detected within Pokemon Let's Go, however, input is still not detected.

**Comment by ogniK5377** [comment]
Undocked mode of links awakening has an odd issue as well. Input works for 1 frame then ceases to work

**Comment by fluffapparition** [comment]
Does this happen when switching to single joycons or starting with single joycons?
