### ISSUE TITLE
Add support of xci files [Request Feature]

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#287]
Is there a way to add the support of xci files, which are the extension for encrypted switch games ?

**Comment by Hexagon12** [comment]
That would be possible if there are any local decrypting tools available. Maybe we could make the decryption keys as a part of the system archives that could be dumped from the console? (Computer generated keys won't come for a long time though.)

Of course, this kind of request could also enable piracy on Yuzu very quick too.

**Comment by greggameplayer** [comment]
@Hexagon12 there is already a tool in order to decrypt xci created by SciresM. I let you the link below :
[Click Here](https://github.com/SciresM/hactool)

**Comment by mailwl** [comment]
in .nfo for release of Bayoneta 2 they add 2 more master keys, which should be enough for decrypting all games except Bayoneta 2 itself. it would be nice if someone write tutorial, how to decrypt .xci

**Comment by Hexagon12** [comment]
@mailwl That is piracy. Master keys should only be gotten from your very own console.

**Comment by mailwl** [comment]
@Hexagon12 , you catch me) anyway i have 2 Switches and some cartriges, for me just proper emulation mean, on my PC games is much better (like Ni No Kuni 2)

**Comment by greggameplayer** [comment]
@mailwl in order to decrypt xci you can use hactool created by SciresM and you can also use HACToolGUI in order to simplify your life.
You can find HACToolGui on this thread : [Click Here](https://gbatemp.net/threads/release-hactoolgui-v0-2-a-very-simple-gui-for-hactool.499526/)

**Comment by Hexagon12** [comment]
@greggameplayer Yes, you can use hactool, but what's the process of getting various keys from the console? There's currently no way of doing that (except private scene work).

**Comment by greggameplayer** [comment]
@Hexagon12 currently yes there is no way of getting these with a console

**Comment by Shideravan** [comment]
How about a pre-decrypted NCA files support?

**Comment by greggameplayer** [comment]
@Shideravan i think you should write an issue for that request

**Comment by greggameplayer** [comment]
I close that because it's not useful anymore.
