### ISSUE TITLE
Missing HLE service unimplemented function 'GetCurrentIpAddress': port='IGeneralService'

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2875]
## needed by Grid Auto sports

[log.zip](https://github.com/yuzu-emu/yuzu/files/3629640/log.zip)

**Comment by ReaperOfSouls1909** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3629660/yuzu_log.txt)
just incase the log above is not the right one

**Comment by Hexagon12** [comment]
Duplicate of #2630
