### ISSUE TITLE
Missing Shader Instructions and Texture Format for Cardfight Vanguard EX

### ISSUE THREAD

**Issue by IceshadeComets** [yuzu-emu/yuzu#2902]
[   7.148688] Debug <Critical> video_core\shader\decode.cpp:DecodeInstr:153: Assertion Failed! Unhandled instruction: 7c0d03b80e070605
[  49.209170] HW.GPU <Critical> video_core\surface.cpp:PixelFormatFromTextureFormat:371: Unimplemented format=18, component_type=2
Log:
https://cdn.discordapp.com/attachments/400106910231035904/625032078907539485/yuzu_log.zip

**Comment by ReinUsesLisp** [comment]
According to envytools the shader instruction is an `HSET` variant and the texture format is `A4B4G4R4`.

**Comment by IceshadeComets** [comment]
Texture Format has been fixed from https://github.com/yuzu-emu/yuzu/pull/2966
Shader Instructions still awaiting a fix.

**Comment by IceshadeComets** [comment]
Issue has been fixed one year later, will close now. Thanks :D
