### ISSUE TITLE
DisconnectNpad getting called due to AcquireNpadStyleSetUpdateEventHandle

### ISSUE THREAD

**Issue by ogniK5377** [yuzu-emu/yuzu#2905]
Upon research, hid breaking in many games depending on control styles(Pokemon lets go, links awakening) is caused due to DisconnectNpad being called. The reason why it's being called is unclear however I have reason to believe it's related to the AcquireNpadStyleSetUpdateEventHandle call. This needs to be further investigated.

Few things to note, AcquireNpadStyleSetUpdateEventHandle MUST be signaled at some point for a controller to actually be considered "activated". 
#2904 seems to signal it in a more appropriate location as it allows multiple controllers to show up in Pokemon Lets go instead of a single controller.
Input DOES work if we disable DisconnectNpad for these controllers which rules out the issue of incorrect shared memory sections or items like that. However, an incorrect shared memory could also be the reason why "DisconnectNpad" is being called.

<meta name="titleids"  content="01006BB00C6F0000,0100187003A36000,010003F003A34000">

**Comment by laurens94** [comment]
Is this issue the reason my DS4 controller doesn't do anything in Link's Awakening?
