### ISSUE TITLE
Changing controllers in the UI does not update them accordingly in HID

### ISSUE THREAD

**Issue by ogniK5377** [yuzu-emu/yuzu#2906]
The configuration UI would need to have an overhaul to the way controllers are updated during gameplay. Controllers are never initialized when they are changed whilst in-game and the styleset changed event will never be called. We'll need to rework how the configuration ui<->hid work together

**Comment by Morph1984** [comment]
I guess this explains why handheld controls are preserved when you switch to docked mode while in game.
