### ISSUE TITLE
crashes on AMD CPU&Radeon Graphic

### ISSUE THREAD

**Issue by Flocke28** [yuzu-emu/yuzu#2931]
Hi Team,

since intergration of yuzu for Link Awakening with canary 2628 the emulator crashes on all games on a AMD CPU&Radeon Graphic system. 

Could you please check it.

Thanks

**Comment by BSoDGamingYT** [comment]
Please update to the latest Canary version and test again, issues made on an old emulator version can be inaccurate. Thank you

**Comment by Flocke28** [comment]
i tried as last 2689.. same problem.. hangs in loading screen

**Comment by FernandoS27** [comment]
Drivers, OS, last functional canary (exact), GPU Model.

**Comment by Flocke28** [comment]
Win 10 x64 all updates installed, Graphic drivers up to date Radeon 19.9.3, Radeon RX 480, 8 core CPU AMD FX-8320 3,6 GHZ, 8GB RAM, last working version previous 2628 all other version after white screen or flickering white squares. And later chrashes or hanging in launching screen. Only Mario Odessey is booting,  Breath of the wild, Oceanhorn (intro/menu) for example hangs

**Comment by FernandoS27** [comment]
We looked at the issue on gcn1 and gcn3 GPUs. Not on polaris though, so it may be drivers or faulty hardware.

**Comment by hcasquet** [comment]
Hi, it happened to me also. Win10 1903, Drivers 19.9.3 on a Radeon RX480, Ryzen 1700X 8 cores, 16GB RAM. Installed latest Yuzu Canary (2692) and Link's Awakening is indeed hanging Yuzu on loading screen. 

I have a log pastebin here: [https://pastebin.com/5B64z9Av](https://pastebin.com/5B64z9Av), but this is the last log entry and error (dunno if related): 

> Render.OpenGL <Error> video_core\renderer_opengl\gl_rasterizer.cpp:DispatchCompute:767: Compute is currently not supported on this device due to the lack of GL_ARB_compute_variable_group_size

**Comment by Hexagon12** [comment]
Link's Awakening issue is irrelevant here, as it uses a shader instruction (BRX) that AMD GPUs do not like and cause the shader to compile in anywhere between 14 minutes and a hour. We are currently working to get this fixed, however.

**Comment by FernandoS27** [comment]
Oh it's LA only? Then it's a known issue. We got a fix in the works that will be released very soon.

**Comment by Flocke28** [comment]
Sound good..

Some game hangs in the launching screen and the speed jump up to 1200%/100%.  The game Link Botw won't boot with 2896 but if I generate a shader cache with a old version 2628 and run then the last canary then botw Boots with the older shader cache.. any plans for a shader database that loads the right shaders if game starts or is it a question of legal?

**Comment by fluffapparition** [comment]
probably could add shader compatibility options for each game

**Comment by Hexagon12** [comment]
Does this crash still happen on the latest mainline release?

**Comment by MysticExile** [comment]
Appears to have been fixed. If anyone still experiences this? Please open a new issue, thanks!
