### ISSUE TITLE
Graphic Driver Issues (resource)

### ISSUE THREAD

**Issue by komawoyo** [yuzu-emu/yuzu#2934]
https://github.com/RPCS3/rpcs3/wiki/Graphics-Driver-Issues

Sharing as resource, may be useful for developers

**Comment by ReinUsesLisp** [comment]
Thanks for sharing. Although GitHub issues have to be actionable; closing as this is not an issue in yuzu itself.

If you'd like to discuss driver issues, feel free to join our Discord server.
