### ISSUE TITLE
Missing HLE service command 'StopSevenSixAxisSensor' in 'hid'

### ISSUE THREAD

**Issue by MysticExile** [yuzu-emu/yuzu#2939]
Needed for The Legend of Zelda: Breath of the Wild v1.6.0
[Reporter log](https://github.com/yuzu-emu/yuzu/files/3687389/01007EF00011E000_2019-10-03T19-49-05.zip)

<meta name="titleids"  content="01007EF00011E000">

**Comment by Morph1984** [comment]
Relevant commands:
InitializeSevenSixAxisSensor
FinalizeSevenSixAxisSensor
StartSevenSixAxisSensor
StopSevenSixAxisSensor
GetSevenSixAxisSensor
IsSevenSixAxisSensorAtRest
ResetSevenSixAxisSensorTimestamp
SetSevenSixAxisSensorFusionStrength
GetSevenSixAxisSensorFusionStrength

**Comment by ytrezq** [comment]
@MysticExile : why did you close this ? Is it implemented ?

**Comment by labib2002** [comment]
has it been implemented and therefore closed?
