### ISSUE TITLE
Can't compile in Linux or Windows.

### ISSUE THREAD

**Issue by 3EGaming** [yuzu-emu/yuzu#295]
I am using #3610 tring to compile the main.cpp but I just get this error,

In file included from /usr/include/c++/4.6/cinttypes:35:0,
                 from main.cpp:5:
/usr/include/c++/4.6/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.
main.cpp:9:23: fatal error: glad/glad.h: No such file or directory
compilation terminated.

I am trying to compile in linux, but I also tried in windows, but it gets a similar error.

**Comment by MerryMage** [comment]
> /usr/include/c++/4.6/

Please ensure libstdc++ is up to date. You should probably be on 7.1.

**Comment by bunnei** [comment]
Closing this, as it's not a real issue. Update your tools and it should work. If you need help, please ask on Discord (or IRC).
