### ISSUE TITLE
Missing HLE service command 'GetInternetConnectionStatus' in 'IGeneralService'

### ISSUE THREAD

**Issue by MysticExile** [yuzu-emu/yuzu#2950]
Needed for
* Youtube
[Reporter log](https://github.com/yuzu-emu/yuzu/files/3694361/01003A400C3DA000_2019-10-06T14-50-31.zip)

<meta name="titleids"  content="01003A400C3DA000">

**Comment by choppymaster** [comment]
Needed for hb-menu

**Comment by MysticExile** [comment]
Fixed by #8685
