### ISSUE TITLE
Broken link on the yuzu-emu.org website

### ISSUE THREAD

**Issue by OnTheLink** [yuzu-emu/yuzu#2958]
The link to the exact page: [https://yuzu-emu.org/entry/yuzu-migration/](https://yuzu-emu.org/entry/yuzu-migration/)

**_On this line_**: Starting today, users will be able to get the new and improved yuzu builds via the installer from our **[website](https://yuzu-emu.org/download/)** or our **[GitHub](https://github.com/yuzu-emu/yuzu-mainline/releases/)**. And if you are already using our installer, you will be automatically migrated to the latest yuzu build.

The "website" link is wrong,
It now links to: [https://yuzu-emu.org/download/](https://yuzu-emu.org/download/)
But it should be linked to: [https://yuzu-emu.org/downloads/](https://yuzu-emu.org/downloads/)

the current link is broken so please fix it

**Comment by FearlessTobi** [comment]
This issue is now fixed in our website backend and should become propagated to the frontend soon. Thanks!
