### ISSUE TITLE
QWaylandGLContext: failed to create EGLContext, error=3009

### ISSUE THREAD

**Issue by MastaG** [yuzu-emu/yuzu#2960]
Hi I've compiled yuzu from source on Fedora 31 (Gnome 3.34 on Wayland).
The GUI opens fine and I can configure my stuff.
However it seems to segfault when trying to run a game (Mario Odyssey in my case):

[mastag@FedoraWS yuzu]$ yuzu
QSocketNotifier: Can only be used with threads started with QThread
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QWaylandGLContext: failed to create EGLContext, error=3009
QWaylandGLContext: failed to create EGLContext, error=3009
QObject::connect(QWindow, GRenderWindow): invalid null parameter
Segmentatiefout (geheugendump gemaakt)

I find this a bit strange, since I'm on mesa 19.3 (devel) and the i965 driver supports OpenGL 4.6 core profile.

See my glxinfo: https://pastebin.com/YXAg3hVt

**Comment by MastaG** [comment]
It seems to happen because QT_QPA_PLATFORM is set to wayland by default (I'm running Gnome on wayland... so it should be).

However when I run yuzu with: QT_QPA_PLATFORM=xcb then it seems to work.
So Yuzu on QT_QPA_PLATFORM=wayland seems to broken for the moment.

**Comment by MastaG** [comment]
Some debug information:

EGL_LOG_LEVEL=debug yuzu
QSocketNotifier: Can only be used with threads started with QThread
libEGL debug: pci id for fd 27: 8086:1916, driver i965

libEGL debug: MESA-LOADER: dlopen(/usr/lib64/dri/i965_dri.so)

libEGL debug: found extension `DRI_Core'
libEGL info: found extension DRI_Core version 2
libEGL debug: found extension `DRI_IMAGE_DRIVER'
libEGL debug: found extension `DRI_DRI2'
libEGL info: found extension DRI_DRI2 version 4
libEGL debug: found extension `DRI_DriverVtable'
libEGL debug: found extension `DRI_ConfigOptions'
libEGL debug: found extension `DRI_Core'
libEGL debug: found extension `DRI_IMAGE_DRIVER'
libEGL debug: found extension `DRI_DRI2'
libEGL debug: found extension `DRI_DriverVtable'
libEGL debug: found extension `DRI_ConfigOptions'
libEGL info: found extension DRI_ConfigOptions version 1
libEGL debug: found extension `DRI_TexBuffer'
libEGL info: found extension DRI_TexBuffer version 3
libEGL debug: found extension `DRI2_Fence'
libEGL debug: found extension `DRI2_Flush'
libEGL info: found extension DRI2_Flush version 4
libEGL debug: found extension `DRI_IMAGE'
libEGL info: found extension DRI_IMAGE version 16
libEGL debug: found extension `DRI_RENDERER_QUERY'
libEGL debug: found extension `DRI_MutableRenderBufferDriver'
libEGL debug: found extension `DRI_CONFIG_QUERY'
libEGL debug: found extension `DRI_Robustness'
libEGL debug: found extension `DRI_NoError'
libEGL debug: found extension `DRI2_Blob'
libEGL debug: found extension `DRI_TexBuffer'
libEGL debug: found extension `DRI2_Fence'
libEGL info: found extension DRI2_Fence version 2
libEGL debug: found extension `DRI2_Flush'
libEGL debug: found extension `DRI_IMAGE'
libEGL info: found extension DRI_IMAGE version 16
libEGL debug: found extension `DRI_RENDERER_QUERY'
libEGL info: found extension DRI_RENDERER_QUERY version 1
libEGL debug: found extension `DRI_MutableRenderBufferDriver'
libEGL info: found extension DRI_MutableRenderBufferDriver version 1
libEGL debug: found extension `DRI_CONFIG_QUERY'
libEGL info: found extension DRI_CONFIG_QUERY version 1
libEGL debug: found extension `DRI_Robustness'
libEGL info: found extension DRI_Robustness version 1
libEGL debug: found extension `DRI_NoError'
libEGL info: found extension DRI_NoError version 1
libEGL debug: found extension `DRI2_Blob'
libEGL info: found extension DRI2_Blob version 1
libEGL debug: did not find optional extension DRI2_BufferDamage version 1
libEGL debug: did not find optional extension DRI2_Interop version 1
libEGL debug: did not find optional extension DRI_FlushControl version 1
libEGL debug: No DRI config supports native format ABGR16F
libEGL debug: No DRI config supports native format XBGR16F
libEGL debug: No DRI config supports native format XRGB2101010
libEGL debug: No DRI config supports native format ARGB2101010
libEGL debug: No DRI config supports native format XBGR2101010
libEGL debug: No DRI config supports native format ABGR2101010
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
libEGL debug: EGL user error 0x3009 (EGL_BAD_MATCH) in eglCreateContext: dri2_create_context

libEGL debug: EGL user error 0x3009 (EGL_BAD_MATCH) in eglCreateContext: dri2_create_context

QWaylandGLContext: failed to create EGLContext, error=3009
libEGL debug: EGL user error 0x3009 (EGL_BAD_MATCH) in eglCreateContext: dri2_create_context

libEGL debug: EGL user error 0x3009 (EGL_BAD_MATCH) in eglCreateContext: dri2_create_context

QWaylandGLContext: failed to create EGLContext, error=3009
QObject::connect(QWindow, GRenderWindow): invalid null parameter
libEGL debug: mincore failed: Cannot allocate memory
Segmentatiefout (geheugendump gemaakt)

**Comment by Morph1984** [comment]
Launch yuzu with the following environment variables
`vblank_mode=0 mesa_glthread=true MESA_GL_VERSION_OVERRIDE=4.6 ./yuzu`

**Comment by MastaG** [comment]
Then it segfaults:

Starting program: /usr/local/bin/yuzu 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.30-5.fc31.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe4281700 (LWP 130837)]
QSocketNotifier: Can only be used with threads started with QThread
[New Thread 0x7fffe28f6700 (LWP 130839)]
[New Thread 0x7fffe20f5700 (LWP 130840)]
[New Thread 0x7fffe18d9700 (LWP 130841)]
[New Thread 0x7fffe10d8700 (LWP 130842)]
[New Thread 0x7fffcbfff700 (LWP 130847)]
[New Thread 0x7fffcb7fe700 (LWP 130848)]
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
[New Thread 0x7fffc98e4700 (LWP 130849)]
[New Thread 0x7fffc90e3700 (LWP 130850)]
[New Thread 0x7fffc88e2700 (LWP 130851)]
[New Thread 0x7fffbbfff700 (LWP 130852)]
[New Thread 0x7fffbb6de700 (LWP 130853)]
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QObject::connect(QWindow, GRenderWindow): invalid null parameter
[Thread 0x7fffe18d9700 (LWP 130841) exited]
[New Thread 0x7fffe18d9700 (LWP 130948)]
[New Thread 0x7ffefd833700 (LWP 130949)]
libpng warning: iCCP: known incorrect sRGB profile

Thread 1 "yuzu" received signal SIGSEGV, Segmentation fault.
0x00007ffff7fb35fd in wl_proxy_marshal () from /lib64/libwayland-client.so.0
Missing separate debuginfos, use: dnf debuginfo-install GConf2-3.2.6-27.fc31.x86_64 SDL2-2.0.10-1.fc31.x86_64 adwaita-qt5-1.1.0-4.fc31.x86_64 alsa-lib-1.1.9-2.fc31.x86_64 at-spi2-atk-2.34.1-1.fc31.x86_64 at-spi2-core-2.34.0-1.fc31.x86_64 atk-2.34.1-1.fc31.x86_64 bzip2-libs-1.0.8-1.fc31.x86_64 cairo-1.16.0-6.fc31.x86_64 cairo-gobject-1.16.0-6.fc31.x86_64 dbus-glib-0.110-6.fc31.x86_64 dbus-libs-1.12.16-3.fc31.x86_64 expat-2.2.8-1.fc31.x86_64 flac-libs-1.3.3-1.fc31.x86_64 fontconfig-2.13.92-3.fc31.x86_64 freetype-2.10.0-3.fc31.x86_64 fribidi-1.0.5-4.fc31.x86_64 gdk-pixbuf2-2.40.0-1.fc31.x86_64 glib2-2.62.1-1.fc31.x86_64 gmp-6.1.2-10.fc31.x86_64 gnutls-3.6.10-1.fc31.x86_64 graphite2-1.3.13-1.fc31.x86_64 gsm-1.0.18-5.fc31.x86_64 gtk3-3.24.12-1.fc31.x86_64 harfbuzz-2.6.1-2.fc31.x86_64 jasper-libs-2.0.14-9.fc31.x86_64 jbigkit-libs-2.1-17.fc31.x86_64 libICE-1.0.10-2.fc31.x86_64 libSM-1.2.3-4.fc31.x86_64 libX11-1.6.8-3.fc31.x86_64 libX11-xcb-1.6.8-3.fc31.x86_64 libXau-1.0.9-2.fc31.x86_64 libXcursor-1.1.15-6.fc31.x86_64 libXdamage-1.1.4-17.fc31.x86_64 libXext-1.3.4-2.fc31.x86_64 libXfixes-5.0.3-10.fc31.x86_64 libXinerama-1.1.4-4.fc31.x86_64 libXrandr-1.5.2-2.fc31.x86_64 libXtst-1.2.3-10.fc31.x86_64 libasyncns-0.8-17.fc31.x86_64 libblkid-2.34-3.fc31.x86_64 libcap-2.26-6.fc31.x86_64 libdatrie-0.2.9-10.fc31.x86_64 libdrm-2.4.99-2.fc31.x86_64 libepoxy-1.5.3-4.fc31.x86_64 libffi-3.1-23.fc31.x86_64 libgcc-9.2.1-1.fc31.x86_64 libgcrypt-1.8.5-1.fc31.x86_64 libglvnd-1.1.1-5.fc31.x86_64 libidn2-2.2.0-2.fc31.x86_64 libjpeg-turbo-2.0.2-4.fc31.x86_64 libmng-2.0.3-10.fc31.x86_64 libmount-2.34-3.fc31.x86_64 libogg-1.3.3-3.fc31.x86_64 libpciaccess-0.15-2.fc31.x86_64 libpng-1.6.37-2.fc31.x86_64 libselinux-2.9-5.fc31.x86_64 libsndfile-1.0.28-11.fc31.x86_64 libstdc++-9.2.1-1.fc31.x86_64 libtasn1-4.14-2.fc31.x86_64 libunistring-0.9.10-6.fc31.x86_64 libuuid-2.34-3.fc31.x86_64 libwayland-client-1.17.0-2.fc31.x86_64 libwayland-cursor-1.17.0-2.fc31.x86_64 libwayland-egl-1.17.0-2.fc31.x86_64 libwayland-server-1.17.0-2.fc31.x86_64 libwebp-1.0.3-2.fc31.x86_64 libxcb-1.13.1-3.fc31.x86_64 libxkbcommon-0.8.4-2.fc31.x86_64 libxshmfence-1.3-5.fc31.x86_64 lz4-libs-1.9.1-1.fc31.x86_64 nettle-3.5.1-3.fc31.x86_64 p11-kit-0.23.16.1-2.fc31.x86_64 pango-1.44.6-1.fc31.x86_64 pcre-8.43-2.fc31.1.x86_64 pulseaudio-libs-13.0-1.fc31.x86_64 qgnomeplatform-0.5-17.fc31.x86_64 qt5-qtbase-5.12.5-1.fc31.x86_64 qt5-qtbase-gui-5.12.5-1.fc31.x86_64 qt5-qtwayland-5.12.5-1.fc31.x86_64 sssd-client-2.2.2-1.fc31.x86_64 systemd-libs-243-3.gitef67743.fc31.x86_64 xz-libs-5.2.4-6.fc31.x86_64 zlib-1.2.11-19.fc31.x86_64
(gdb) bt full
#0  0x00007ffff7fb35fd in wl_proxy_marshal () at /lib64/libwayland-client.so.0
#1  0x00007fffe4444521 in QtWaylandClient::QWaylandAbstractDecoration::contentImage() () at /lib64/libQt5WaylandClient.so.5
#2  0x00007fffe0070640 in QtWaylandClient::DecorationsBlitter::blit(QtWaylandClient::QWaylandEglWindow*) ()
    at /usr/lib64/qt5/plugins/wayland-graphics-integration-client/libqt-plugin-wayland-egl.so
#3  0x00007fffe006fd47 in QtWaylandClient::QWaylandGLContext::swapBuffers(QPlatformSurface*) () at /usr/lib64/qt5/plugins/wayland-graphics-integration-client/libqt-plugin-wayland-egl.so
#4  0x00007ffff6fa0871 in QOpenGLContext::swapBuffers(QSurface*) () at /lib64/libQt5Gui.so.5
#5  0x00007ffff6fa49e5 in QOpenGLWindowPrivate::flush(QRegion const&) () at /lib64/libQt5Gui.so.5
#6  0x00007ffff6f97799 in QPaintDeviceWindow::exposeEvent(QExposeEvent*) () at /lib64/libQt5Gui.so.5
#7  0x00007ffff6f7157d in QWindow::event(QEvent*) () at /lib64/libQt5Gui.so.5
#8  0x00007ffff6f9783d in QPaintDeviceWindow::event(QEvent*) () at /lib64/libQt5Gui.so.5
#9  0x00007ffff7a08ad6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#10 0x00007ffff7a12150 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#11 0x00007ffff6b93de8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#12 0x00007ffff6f68c16 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () at /lib64/libQt5Gui.so.5
#13 0x00007ffff6f68e54 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib64/libQt5Gui.so.5
#14 0x00007ffff6f4554b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Gui.so.5
#15 0x00007fffe44695e4 in userEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5WaylandClient.so.5
#16 0x00007ffff54d84a0 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#17 0x00007ffff54d8830 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#18 0x00007ffff54d88d3 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#19 0x00007ffff6be8cb5 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#20 0x00007ffff6b92ceb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#21 0x00007ffff6b9aa16 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#22 0x0000000000544895 in main(int, char**) (argc=1, argv=0x7fffffffd638) at /home/mastag/src/yuzu/src/yuzu/main.cpp:2346
        detached_tasks = 
          {static instance = 0x7fffffffd480, cv = {_M_cond = {__data = {{__wseq = 0, __wseq32 = {__low = 0, __high = 0}}, {__g1_start = 0, __g1_start32 = {__low = 0, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 0, __wrefs = 0, __g_signals = {0, 0}}, __size = '\000' <repeats 47 times>, __align = 0}}, mutex = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, <No data fields>}, count = 0}
        scope_exit_helper_2315 = {func = {<No data fields>}}
        app = <incomplete type>
        main_window = 
                  {<QMainWindow> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x7ffff7f14ee0 <QMainWindow::staticMetaObject>, stringdata = 0x11ff9a0 <qt_meta_stringdata_GMainWindow>, data = 0x1200720 <qt_meta_data_GMainWindow>, static_metacall = 0x436c8a <GMainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, static max_recent_files_item = 10, discord_rpc = std::unique_ptr<DiscordRPC::DiscordInterface> = {get() = 0x1f904c0}, ui = {<Ui_MainWindow> = {action_Install_File_NAND = 0x1fbbc00, action_Load_File = 0x1fbbc20, action_Load_Folder = 0x1fbbc40, action_Load_Symbol_Map = 0x1ce0f70, action_Exit = 0x1f9ce40, action_Start = 0x1ce0f90, action_Pause = 0x1f9ce60, action_Stop = 0x1fbd5b0, action_Rederive = 0x1fbd6d0, action_About = 0x1fbd610, action_Single_Window_Mode = 0x1fbd6f0, action_Configure = 0x1fbd970, action_Display_Dock_Widget_Headers = 0x1fbda50, action_Show_Filter_Bar = 0x1fbdb30, action_Show_Status_Bar = 0x1fbdc10, action_Select_Game_List_Root = 0x1fbdcf0, action_Select_NAND_Directory = 0x1fbddd0, action_Select_SDMC_Directory = 0x1fbdeb0, action_Fullscreen = 0x1fbdf90, action_Restart = 0x1fbe070, action_Load_Amiibo = 0x1fbd990, action_Report_Compatibility = 0x1fbe230, action_Open_yuzu_Folder = 0x1fbe310, actio--Type <RET> for more, q to quit, c to continue without paging--
n_Capture_Screenshot = 0x1fbe3f0, centralwidget = 0x1e0e3e0, horizontalLayout = 0x1df1b40, menubar = 0x1fbfe00, menu_File = 0x1fc4940, menu_recent_files = 0x1f9c490, menu_Emulation = 0x20084f0, menu_View = 0x20091f0, menu_View_Debugging = 0x2009570, menu_Tools = 0x20098b0, menu_Help = 0x2009c80}, <No data fields>}, debug_context = std::shared_ptr<Tegra::DebugContext> (use count 2, weak count 2) = {get() = 0x1e50e30}, render_window = 0x1f9d2a0, game_list = 0x20baa80, loading_screen = 0x20f6770, game_list_placeholder = 0x2073bb0, message_label = 0x20cfe00, emu_speed_label = 0x20d3e90, game_fps_label = 0x20d4300, emu_frametime_label = 0x20d4490, status_bar_update_timer = <incomplete type>, config = std::unique_ptr<Config> = {get() = 0x1dd7fc0}, emulation_running = true, emu_thread = std::unique_ptr<EmuThread> = {get() = 0x37816c0}, game_path = {static null = {<No data fields>}, d = 0x7fffb001e410}, auto_paused = false, vfs = std::shared_ptr<FileSys::VfsFilesystem> (use count 3, weak count 0) = {get() = 0x1e50c10}, provider = std::unique_ptr<FileSys::ManualContentProvider> = {get() = 0x1f8d600}, profilerWidget = 0x100c5bd3b00, microProfileDialog = 0x2157f50, graphicsBreakpointsWidget = 0x2158d90, waitTreeWidget = 0x22363d0, actions_recent_files = {0x2250710, 0x2250730, 0x2250b90, 0x2250f70, 0x2251370, 0x2251750, 0x2251b30, 0x2251f10, 0x2252380, 0x2252710}, default_theme_paths = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x20abd40}, d = 0x20abd40}}, <No data fields>}, hotkey_registry = {hotkey_groups = std::map with 1 element = {[{static null = {<No data fields>}, d = 0x1208be0 <{lambda()#2}::operator()() const::qstring_literal>}] = std::map with 15 elements = {[{static null = {<No data fields>}, d = 0x1208ba0 <{lambda()#1}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x2253630}, shortcut = 0x22551f0, context = Qt::ApplicationShortcut}, [{static null = {<No data fields>}, d = 0x1209580 <{lambda()#43}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x22544a0}, shortcut = 0x2255390, context = Qt::ApplicationShortcut}, [{static null = {<No data fields>}, d = 0x1208c60 <{lambda()#4}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x2253650}, shortcut = 0x2254630, context = Qt::WindowShortcut}, [{static null = {<No data fields>}, d = 0x1208d20 <{lambda()#7}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x2253e90}, shortcut = 0x2254eb0, context = Qt::ApplicationShortcut}, [{static null = {<No data fields>}, d = 0x1208ea0 <{lambda()#13}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x2254150}, shortcut = 0x22549d0, context = Qt::WindowShortcut}, [{static null = {<No data fields>}, d = 0x1208de0 <{lambda()#10}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x2253fa0}, shortcut = 0x0, context = Qt::WindowShortcut}, [{static null = {<No data fields>}, d = 0x1208f40 <{lambda()#16}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x2254330}, shortcut = 0x2254850, context = Qt::WindowShortcut}, [{static null = {<No data fields>}, d = 0x1208fe0 <{lambda()#19}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x2254350}, shortcut = 0x2254d10, context = Qt::ApplicationShortcut}, [{static null = {<No data fields>}, d = 0x12090a0 <{lambda()#22}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x2254370}, shortcut = 0x2255050, context = Qt::ApplicationShortcut}, [{static null = {<No data fields>}, d = 0x1209140 <{lambda()#25}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x2254390}, shortcut = 0x2254510, context = Qt::WindowShortcut}, [{static null = {<No data fields>}, d = 0x1209200 <{lambda()#28}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x22543b0}, shortcut = 0x2254740, context = Qt::WindowShortcut}, [{static null = {<No data fields>}, d = 0x12092a0 <{lambda()#31}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x22543d0}, shortcut = 0x0, context = Qt::WindowShortcut}, [{static null = {<No data fields>}, d = 0x1209340 <{lambda()#34}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x22543f0}, shortcut = 0x0, context = Qt::WindowShortcut}, [{static null = {<No data fields>}, d = 0x1209400 <{lambda()#37}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x2254410}, shortcut = 0x2254b70, context = Qt::ApplicationShortcut}, [{static null = {<No data fields>}, d = 0x12094c0 <{lambda()#40}::operator()() const::qstring_literal>}] = {keyseq = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff72d7860, data = 0x7ffff72d75c0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x2254430}, shortcut = 0x0, context = Qt::WindowShortcut}}}}}
--Type <RET> for more, q to quit, c to continue without paging--
        result = 0

**Comment by MastaG** [comment]
nevermind.. let's close this for now

**Comment by iMonZ** [comment]
> It seems to happen because QT_QPA_PLATFORM is set to wayland by default (I'm running Gnome on wayland... so it should be).
> 
> However when I run yuzu with: QT_QPA_PLATFORM=xcb then it seems to work.
> So Yuzu on QT_QPA_PLATFORM=wayland seems to broken for the moment.

This is just a temporary workaround. The issue is still there
