### ISSUE TITLE
Black rendering in Fire Emblem Three Houses with RTX 2060 super

### ISSUE THREAD

**Issue by UIysse** [yuzu-emu/yuzu#2967]
Graphical bug with Fire Emblem three Houses.
Screenshot : https://imgur.com/a/MJcLJ17

i7 4790k ; RTX 2060 super ; 16 gb ram

Edit : 
This is normal rendering : 
https://imgur.com/a/wY5QcyH

spec : laptop i7 7700 HQ
GTX 1070
16 gb ram

<meta name="titleids"  content="010055D009F78000">

**Comment by MysticExile** [comment]
Is this still an issue?

**Comment by Karlos007** [comment]
Yes the bug is still there in RTX.

**Comment by Karlos007** [comment]
Workaround for **RTX**: use **Vulkan** although the performance drops on lot of areas.

**Comment by Hexagon12** [comment]
Fixed with #3646
