### ISSUE TITLE
Links Awakening... not rendering anything? 

### ISSUE THREAD

**Issue by Velislide** [yuzu-emu/yuzu#2975]
Been having issues with the newest public release, trying to get this working. It's not rendering anything at all, menu works, but in game, I only see the static image background which is black with a blue hue to it. I can see messages from talking to NPC's. Very new to this, as of yesterday. Looked into the log, seems like theres issues with my graphics drivers possibly? Fresh windows install with newest Nvidia drivers, running a 1080 Ti. 

Here is one of the messages it repeats in the log. I also will upload the log.

[ 109.623895] Render.OpenGL <Warning> video_core\renderer_opengl\gl_rasterizer.cpp:AccelerateDisplay:873: Framebuffer pixel_format is different
[ 109.639721] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:498: API ERROR 1282: GL_INVALID_OPERATION error generated. <program> object is not successfully linked.
[ 109.640571] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:RequestUpdateImpl:94: (STUBBED) called

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3727213/yuzu_log.txt)

**Comment by ReaperOfSouls1909** [comment]
you need the Patreon release

**Comment by Velislide** [comment]
Thanks for the quick reply.

**Comment by ReaperOfSouls1909** [comment]
you can close this now

**Comment by Yvar192** [comment]
nah, it's not fixed in master yet

**Comment by Hexagon12** [comment]
The game now renders on the latest mainline builds. Fixed by #2976.
