### ISSUE TITLE
SEGFAULT when launching a game

### ISSUE THREAD

**Issue by FaithLV** [yuzu-emu/yuzu#2988]
Hello! Whenever I try to load a game I get a segfault.

- yuzu-linux-20191016-5e721c71c
- Arch Linux (5.3.6-zen)
- crash: https://gist.githubusercontent.com/FaithLV/bc22ba72d4525b8e4f6e09162e118cac/raw/f2971ca1ef706f452643dc9edd84d865dee85eec/yuzu-segv1
- backtrace:https://gist.githubusercontent.com/FaithLV/b448612a66b3182e017760787d35f6d3/raw/76fd0f67230fba5f5225f70879a9b85b8a0504ed/yuzu-bt

Compiled from source: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yuzu-canary-git

**Comment by cociorbaandrei** [comment]
Did you launch yuzu without having any keys? If so it might be the same issue as #2996.

**Comment by FaithLV** [comment]
Yes, the issue was lack of keys!
