### ISSUE TITLE
Yuzu Libretro core

### ISSUE THREAD

**Issue by FinixFighter** [yuzu-emu/yuzu#2997]
Are there any plans for a Libretro port of Yuzu core? If there are not any plans, do you think that you will consider porting it to libretro some day?

**Comment by chris062689** [comment]
If a potential libRetro port would be done, it is likely to be done by the libRetro team themselves or a third party. 

We have no plans to officially support a libRetro core at this time.

**Comment by blacklat** [comment]
the whole libretro team is made up of hypocrites, the justification for not carrying the yuzu is that the console is very new and they are against piracy but the whole project uses pirated content, so you can use anything involved with game emulation you need of roms, bios ... all of this is piracy, so in my opinion it's logical, the libretro guys are hypocritical assholes who use piracy in everything they do and don't admit, people without character or honor.
