### ISSUE TITLE
Several games softlock at MountSaveData if its save folder does not exist

### ISSUE THREAD

**Issue by Morph1984** [yuzu-emu/yuzu#2999]
Several games, such as Fire Emblem Warriors, BOTW and potentially many others softlock at MountSaveData when their corresponding save folder does not exist.

Example:

Fire Emblem Warriors (Title ID: 0100F15003E64000)

If this folder doesn't exist, the game will not launch
`yuzu\nand\user\save\0000000000000000\...\0100F15003E64000`

The current workaround is as follows:

Right click on the affected game, click "Open Save Data Location". This will generate the folder with the appropriate title id.

This issue is related to #2963

Update:

Both #2963 and this issue are caused by #2430

**Comment by fluffapparition** [comment]
Generate the save directory automatically on boot.

**Comment by Hexagon12** [comment]
The issue no longer appears on the latest mainline builds. Fixed by #3007.
