### ISSUE TITLE
This is illegal

### ISSUE THREAD

**Issue by caiozf** [yuzu-emu/yuzu#3]
Fuck you cock-suckers who are developing this,
emulators must be for non-commercial consoles only

**Comment by MoochMcGee** [comment]
Uh, m8, Bleem vs Sony.

**Comment by LogPod** [comment]
Hey you go back to your switch and let us do our thing

**Comment by shadowbrony33** [comment]
Nope, this is legal since the code uses data from the console being reverse-engineered.

**Comment by LogPod** [comment]
:shipit:

**Comment by LogPod** [comment]
@caiozf m8 what is process?

**Comment by rodrigogs** [comment]
Is it ilegal to open source now? hahaha

**Comment by wertherhunt** [comment]
process is "to sue". he is brazilian and he used the word that was more common to use in these kind of sentences in portuguese. 

Clueless kid
