### ISSUE TITLE
Missing HLE service command 'GetGyroscopeZeroDriftMode' in 'hid'

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#3002]
* Needed for Ring Fit Adventure

[Reporter log](https://github.com/yuzu-emu/yuzu/files/3747152/01002FF008C24000_2019-10-19T23-07-23.txt)

**Comment by german77** [comment]
This has been implemented in #4594

**Comment by Morph1984** [comment]
Actually, was implemented in #4138
