### ISSUE TITLE
Pokemon Let's Go saving issue

### ISSUE THREAD

**Issue by yair2000** [yuzu-emu/yuzu#3011]
There's an issue regarding saving the progress in Pokemon Let's Go games. The game starts normally, but when I want to save it, the emualtor freezes and the speed has skyrocketed to 1000+ percent

I played the Pokemon Let's Go games on the yuzu 22 build and on an older yuzu Canary build, Canary 2681 HEAD fdecfac

These are my computer specs (Laptop Specs)
Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
GeForce 840M
Windows 10 x64

**Comment by Hexagon12** [comment]
This is a bug tracker for developers and not a support forum.

If you require support, please either contact our Discord or the Citra community forums (they're used for yuzu too).

**Comment by fluffapparition** [comment]
@Hexagon12 The user has implied this as a bug. If you could ask for logs instead, we could see what we can do. I advise we keep it open.

_Sent from my Galaxy S9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
