### ISSUE TITLE
Super Mario Odyssey: Stutters when jumping

### ISSUE THREAD

**Issue by legend800** [yuzu-emu/yuzu#3017]
Despite the game running at 60fps, when performing any jumps in the game (sans short hops), there is a momentary pause right before landing. 

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4.5ghz
16GB RAM

<meta name="titleids"  content="0100000000010000">

**Comment by ReaperOfSouls1909** [comment]
maybe you should add the stubbed service name and a log with it showing

**Comment by saban1234** [comment]
Same issue here and it still persists, very annoying.
i9-9900k, RTX 2080
intel HD audio, or Realtek HD audio
win10 1809
Tell me which kind log would help to pinpoint the problem ?

**Comment by legend800** [comment]
One of the devs recently commented that this is actually an **_audio_** issue, meaning they have the info they need for now. Unfortunately audio is one of the weaker areas of yuzu and gets the least updates, but you never know.

**Comment by RyuDanuer** [comment]
I have it too!

**Comment by ReaperOfSouls1909** [comment]
It’s related to audio and when audio is stripped using a mod the issue is solved so #3266 we need someone to work on all those services.

**Comment by FearlessTobi** [comment]
Fixed by the audio interpolation overhaul.
