### ISSUE TITLE
Link's Awakening Softlock/Crash

### ISSUE THREAD

**Issue by SAIYAN48** [yuzu-emu/yuzu#3018]
After completing some of Dampe's challenges and exiting the menu to save/autosave, yuzu will either crash or softlock.

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/3763850/yuzu_log.zip)

**Comment by SAIYAN48** [comment]
New Log
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/3763993/yuzu_log.zip)

**Comment by Hexagon12** [comment]
`[1037.759349] Debug <Critical> core\memory.cpp:Read:168: Assertion Failed! Mapped memory page without a pointer @ 00000010B64CB3F0`

**Comment by SAIYAN48** [comment]
Issue seems to be resolved as of version 27.

**Comment by SAIYAN48** [comment]
Correction: Issue occurs with versions 27-29 on the final challenge, new log added.
[yuzu_log - final challenge softlock.zip](https://github.com/yuzu-emu/yuzu/files/3774202/yuzu_log.-.final.challenge.softlock.zip)

**Comment by SAIYAN48** [comment]
Issue fixed on version 31
