### ISSUE TITLE
Missing svcGetInfo function 'IdleTickCount'

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#3019]
* Needed for Witcher 3

<meta name="titleids"  content="0100bfe00e9ca000">

**Comment by MysticExile** [comment]
[svcBreak Report.zip](https://github.com/yuzu-emu/yuzu/files/4409429/svcBreak.Report.zip)
Here is the svcBreak Report of The Witcher 3.

**Comment by MysticExile** [comment]
Fixed by #7193
