### ISSUE TITLE
yuzu should bail early (and display an error to the user) for 32-bit apps

### ISSUE THREAD

**Issue by bunnei** [yuzu-emu/yuzu#302]
This is a good task for someone new who wants to make a contribution to yuzu. yuzu only supports aarch64 apps, which is like 99% of Switch games/homebrew. However, it's possible for apps to be 32-bit (e.g. Mario Kart 8 is). We currently try to run them, but instead should bail out early and display an error to the user. We already detect whether an app is 32-bit (see https://github.com/yuzu-emu/yuzu/blob/master/src/core/file_sys/program_metadata.cpp#L95 ), so this should be a really simple change.

Note, we probably will support 32-bit Switch apps *some day*... but that will likely be a long time in the future and is not a priority right now.

**Comment by WJK2002** [comment]
So will Mario Kart 8 Deluxe not be able to be emulated until long after other games? Also are there any other games like this?

**Comment by N00byKing** [comment]
@WJK2002 first part is true, mk8dx will be probably a bit late. I dont know of any other games that are affected though

**Comment by mhvuze** [comment]
Just as an addition, Monster Hunter XX/Generations Ultimate is also 32bit apparently.

**Comment by perkel666** [comment]
Yup i just confirmed it. MHXX/Generations Ultimate is 32bit

**Comment by Narugakuruga** [comment]
MHXX, Captain Toad, New Super Mario Bros. U.
They all come from Wii U or 3DS.
