### ISSUE TITLE
Missing implementation of TransactionId type 17 'ListFrameHistory' in VI service

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#3021]
* Needed for Witcher 3

<meta name="titleids"  content="0100bfe00e9ca000">

**Comment by rotecode** [comment]
* Needed for Luigi's Mansion 3 (v1.3.0 & above)

**Comment by liamwhite** [comment]
Present as of https://github.com/yuzu-emu/yuzu/commit/56284bff6c312da130eb0f2d0cda80cd29c82046
