### ISSUE TITLE
add system file interface [Request Feature]

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#303]
I have seen that some commercial games and even all the commercial games required a system file interface in order to run, which is currently not available or unimplemented.
So anyone can correct this common issue ?

**Comment by Hexagon12** [comment]
"system file interface"? What is that supposed to mean? Please provide more information. And bear in mind that we know all of the commercial game bugs and just try to solve them ourselves for the time being.

**Comment by greggameplayer** [comment]
that is said in the log of any commercial games like Cave Story Plus or The Binding Of Isaac Afterbirth Plus.

> core/hle/service/filesystem/fsp_srv.cpp:OpenDataStorageByCurrentProcess:438: no file system interface available !

**Comment by Hexagon12** [comment]
Is that the last log line for those games? If no, we don't accept random service feature requests. We will implement that when time comes.

**Comment by greggameplayer** [comment]
@Hexagon12 
the last line is

> core/hle/kernel/svc.cpp:operator():295: Assertion Failed!

The line i gave you before is set as critical in the console such as assertion failed.
It's also the first critical issue who appear in the console and after appear assertion failed and then the game crash yuzu.

**Comment by Hexagon12** [comment]
The "system file interface" isn't the cause for the game to not boot. Currently, many crashes say something that may be very well an issue in a other place altogether, and that's why we ask people to not report issues on commercial games yet.

**Comment by bunnei** [comment]
Yeah, as Hexagon12 said, this is not the root problem with these games. Expect them to boot further soon - for now, I don't think we need an issue tracking their progress.

**Comment by greggameplayer** [comment]
@Hexagon12 Ok
