### ISSUE TITLE
Yuzu Frame nan ms error 'fire emblem threehouses'

### ISSUE THREAD

**Issue by songwonseock** [yuzu-emu/yuzu#3030]
yuzu playing game 'fire emblem threehouses'

but sometimes error...
-->
https://user-images.githubusercontent.com/17524471/67613214-e3a00f80-f7e5-11e9-86a3-bdff27101072.PNG

frame error!!! 0FPS....

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum. Please use the [**forums**](https://community.citra-emu.org/) or our Discord for support requests.

Closing
