### ISSUE TITLE
Luigi's Mansion 3 show charging and then close

### ISSUE THREAD

**Issue by FranciscoReMo** [yuzu-emu/yuzu#3040]
This is the log. I don't understand but you know what happens. Thanks.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3778547/yuzu_log.txt)

This game isn't in Game Wiki and the Website. Show this and then close.

![image](https://user-images.githubusercontent.com/43990816/67677102-70340480-f983-11e9-9fdd-a850c668fcb6.png)

For me, it's in Intro / Menu.

**Comment by Hexagon12** [comment]
Please refrain on making issues of unreleased games. Report the issue once the game is out.

**Comment by fluffapparition** [comment]
My question is how and why he even has a copy of an unreleased game in the first place.

**Comment by FranciscoReMo** [comment]
Because when you make a pre-purchase you download the game in the Swicth (then to play it in the Swicth you have to wait for that day because it is so programmed apparently).

And a great job for Yuzu, today it's out and it's now in Okey.
![image](https://user-images.githubusercontent.com/43990816/67930228-88906300-fbbf-11e9-9918-be9698f74196.png)
![image](https://user-images.githubusercontent.com/43990816/67930250-98a84280-fbbf-11e9-9410-e0c193d09812.png)
![image](https://user-images.githubusercontent.com/43990816/67930302-c1c8d300-fbbf-11e9-8db7-75ababc6fc9c.png)

**Comment by FranciscoReMo** [comment]
Firtst, I'm have bug with log. I'm try up log file for this block. 
![image](https://user-images.githubusercontent.com/43990816/67934989-43712e80-fbc9-11e9-9c42-eab5dfcd084c.png)
![image](https://user-images.githubusercontent.com/43990816/67935024-5421a480-fbc9-11e9-91df-20996b5a3022.png)
It's all in white from there and it's 750mb in .txt . I collect all log in this file and now it's 12mb.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3793060/yuzu_log.txt)

**Comment by fluffapparition** [comment]
@FranciscoReMo i cant see the entire log, can you paste it ?

**Comment by FranciscoReMo** [comment]
Of course. The last 25 lines is:

[ 106.402082] HW.GPU <Warning> video_core\shader\decode\other.cpp:operator ():75: MOV_SYS instruction with InvocationInfo is incomplete
[ 106.402110] HW.GPU <Warning> video_core\shader\decode\other.cpp:DecodeOther:254: ISBERD instruction is incomplete
[ 106.402114] Debug <Critical> video_core\shader\decode\video.cpp:GetVideoOperand:101: Assertion Failed! Unimplemented code!
[ 106.402191] HW.GPU <Warning> video_core\shader\decode\other.cpp:DecodeOther:254: ISBERD instruction is incomplete
[ 106.402196] Debug <Critical> video_core\shader\decode\video.cpp:GetVideoOperand:101: Assertion Failed! Unimplemented code!
[ 106.402207] HW.GPU <Warning> video_core\shader\decode\other.cpp:DecodeOther:254: ISBERD instruction is incomplete
[ 106.402213] HW.GPU <Warning> video_core\shader\decode\other.cpp:DecodeOther:254: ISBERD instruction is incomplete
[ 106.402442] Render.OpenGL <Info> video_core\renderer_opengl\gl_shader_cache.cpp:BuildShader:260: called. TCS96C783AF779CEB73
[ 106.402479] Debug <Critical> video_core\shader\decode\other.cpp:operator ():98: Assertion Failed! Unhandled system move: 17
[ 106.402481] HW.GPU <Warning> video_core\shader\decode\other.cpp:operator ():75: MOV_SYS instruction with InvocationInfo is incomplete
[ 106.402495] HW.GPU <Warning> video_core\shader\decode\other.cpp:DecodeOther:254: ISBERD instruction is incomplete
[ 106.402498] Debug <Critical> video_core\shader\decode\video.cpp:GetVideoOperand:101: Assertion Failed! Unimplemented code!
[ 106.402538] HW.GPU <Warning> video_core\shader\decode\other.cpp:DecodeOther:254: ISBERD instruction is incomplete
[ 106.402542] Debug <Critical> video_core\shader\decode\video.cpp:GetVideoOperand:101: Assertion Failed! Unimplemented code!
[ 106.402548] HW.GPU <Warning> video_core\shader\decode\other.cpp:DecodeOther:254: ISBERD instruction is incomplete
[ 106.402552] HW.GPU <Warning> video_core\shader\decode\other.cpp:DecodeOther:254: ISBERD instruction is incomplete
[ 106.402708] Debug <Critical> video_core\renderer_opengl\gl_shader_cache.cpp:GenerateGLSL:180: Assertion Failed! Unimplemented program_type=2
[ 106.402711] Debug <Critical> video_core\renderer_opengl\gl_shader_util.cpp:GetStageDebugName:25: Assertion Failed! Unimplemented code!
[ 106.402731] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:498: API ERROR 1280: GL_INVALID_ENUM error generated. <shaderType> enum is invalid; expected GL_VERTEX_SHADER_ARB, GL_CG_VERTEX_SHADER_EXT, GL_FRAGMENT_SHADER_ARB, GL_CG_FRAGMENT_SHADER_EXT, GL_GEOMETRY_SHADER_EXT, GL_TESS_CONTROL_SHADER or GL_TESS_EVALUATION_SHADER.
[ 106.402741] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:498: API ERROR 1281: GL_INVALID_VALUE error generated. One or more handles do not refer to an object generated by OpenGL.
[ 106.402756] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:498: API ERROR 1281: GL_INVALID_VALUE error generated. One or more handles do not refer to an object generated by OpenGL.
[ 106.402765] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:498: API ERROR 1281: GL_INVALID_VALUE error generated. Object handle does not refer to an object generated by OpenGL.
[ 106.402770] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:498: API ERROR 1281: GL_INVALID_VALUE error generated. Object handle does not refer to an object generated by OpenGL.
[ 106.669653] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:498: API ERROR 1281: GL_INVALID_VALUE error generated. Object handle does not refer to an object generated by OpenGL.
[ 107.386997] Render.OpenGL <Error> video_core\renderer_opengl\gl_shader_util.cpp:LoadShader:48: Error compiling unknown shader:
