### ISSUE TITLE
Failed to build on Ubuntu 18.04 and Debian 10

### ISSUE THREAD

**Issue by Sunderland93** [yuzu-emu/yuzu#3044]
Hello. Yuzu is failed to build on Ubuntu 18.04 and Debian 10 due to Tests error:
Running tests...
```
/usr/bin/ctest --force-new-ctest-process -j8
Test project /media/DATA/Repos/Ubuntu_18.04/yuzu-0.0.0~git20191025/obj-x86_64-linux-gnu
    Start 1: example
Could not find executable example
Looked in the following places:
example
example
Release/example
Release/example
Debug/example
Debug/example
MinSizeRel/example
MinSizeRel/example
RelWithDebInfo/example
RelWithDebInfo/example
Deployment/example
Deployment/example
Development/example
Development/example
Unable to find executable: example
1/3 Test #1: example ..........................***Not Run   0.00 sec
    Start 2: example64
Could not find executable example64
Looked in the following places:
example64
example64
Release/example64
Release/example64
Debug/example64
Debug/example64
MinSizeRel/example64
MinSizeRel/example64
RelWithDebInfo/example64
RelWithDebInfo/example64
Deployment/example64
Deployment/example64
Development/example64
Development/example64
Unable to find executable: example64
2/3 Test #2: example64 ........................***Not Run   0.00 sec
    Start 3: tests
3/3 Test #3: tests ............................***Exception: SegFault  0.11 sec


0% tests passed, 3 tests failed out of 3

Total Test time (real) =   0.34 sec

The following tests FAILED:
          1 - example (Not Run)
          2 - example64 (Not Run)
          3 - tests (SEGFAULT)
Errors while running CTest
make[1]: *** [Makefile:122: test] Error 8
make[1]: Leaving directory '/media/DATA/Repos/Ubuntu_18.04/yuzu-0.0.0~git20191025/obj-x86_64-linux-gnu'
dh_auto_test: cd obj-x86_64-linux-gnu && make -j8 test ARGS\+=-j8 returned exit code 2
make: *** [debian/rules:9: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

**Comment by ReaperOfSouls1909** [comment]
`Termimal: sudo apt install libsdl2-dev

Termimal: sudo apt install build-essential

Termimal: sudo apt install cmake git

Termimal: sudo apt install libqt5webenginewidgets5 libsndio-dev qtbase5-dev libqt5opengl5-dev
`

`Termimal: sudo ln -T /usr/lib/x86_64-linux-gnu/libsndio.so.7.0 /usr/lib/x86_64-linux-gnu/libsndio.so.6.1
`
should have no issues if all that is done i compiled today on ubuntu 18.04 just to make sure no changes would fail yuzu

**Comment by lioncash** [comment]
Hi, this is due to zlib not disabling its tests by default within its CMakeLists.txt file. This can be ignored for the meantime. The binaries themselves still build correctly.

**Comment by Sunderland93** [comment]
@lioncash Ok, but how ignore it at build time? This error prevents to make *deb package

**Comment by ReaperOfSouls1909** [comment]
what i added means you wont have to compile and can use the mainline builds

**Comment by lioncash** [comment]
@Sunderland93 once #3045 is merged you won't need to do anything and it should work out of the box. But in the meantime, not running ctest (or specifying `-E "(example|example64)"` for the invocation of ctest to ignore the tests) is likely the best means of avoiding it.

**Comment by Sunderland93** [comment]
Solved with override_dh_auto_test: in debian/rules
