### ISSUE TITLE
Astral Chain testing(locking after a while)

### ISSUE THREAD

**Issue by Andryshik345** [yuzu-emu/yuzu#3052]
Commit 04b838c, version 34.

Locking up after a while, may earlier or late.

First start locking:
![first start](https://user-images.githubusercontent.com/24612088/67886346-20179680-fb6b-11e9-99aa-33ad4c216547.jpg)
[yuzu_log_first.txt](https://github.com/yuzu-emu/yuzu/files/3790533/yuzu_log_first.txt)

After that, if I run the game a second time(game create a save on first start):
Small gif:
![ezgif com-optimize(6)](https://user-images.githubusercontent.com/24612088/67886926-29553300-fb6c-11e9-91bc-3e3d495627e6.gif)
[yuzu_log_second.txt](https://github.com/yuzu-emu/yuzu/files/3790566/yuzu_log_second.txt)
On both runs after lock emulator just crashing after a few seconds.

Specs:
Ryzen 1600, GTX 750 Ti 2 GB(driver 436.15), 16 GB RAM

<meta name="titleids"  content="01007300020fa000">

**Comment by Andryshik345** [comment]
Version 69(commit 0e60afb) now game is locking(with the emu crashing) right before show the main menu.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3879374/yuzu_log.txt)

**Comment by vapopescu** [comment]
Version 218. Game crashes after around 8 minutes of gameplay. Most frequent critical errors are in order:

1. `Debug <Critical> video_core\shader\shader_ir.cpp:GetConditionCode:363: Assertion Failed! Unimplemented condition code: 28`
2. `Debug <Critical> video_core\shader\decode\other.cpp:operator ():103: Assertion Failed! Unhandled system move: 30`
3. `Debug <Critical> video_core\shader\decode\other.cpp:operator ():103: Assertion Failed! Unhandled system move: 31`
4. `Debug <Critical> video_core\shader\decode.cpp:DecodeInstr:287: Assertion Failed! Unhandled instruction: 50e2432111170000`
5. `Debug <Critical> video_core\shader\decode\arithmetic_integer.cpp:DecodeArithmeticInteger:110: Assertion Failed! Condition codes generation in ISCADD is not implemented`
6. `Debug <Critical> video_core\shader\decode.cpp:DecodeInstr:287: Assertion Failed! Unhandled instruction: f0a81b8000070000`
7. `Debug <Critical> core\hle\kernel\hle_ipc.cpp:ReadBuffer:298: Assertion Failed! BufferDescriptorX invalid buffer_index 1`
8. `Debug <Critical> video_core\shader\decode\texture.cpp:DecodeTexture:327: Assertion Failed! AOFFI is not implemented`
9. `Debug <Critical> video_core\shader\decode.cpp:DecodeInstr:287: Assertion Failed! Unhandled instruction: ebf9000000880002`

[yuzu_log_critical.txt](https://github.com/yuzu-emu/yuzu/files/4431748/yuzu_log_critical.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4431749/yuzu_log.txt)

**Comment by Andryshik345** [comment]
@vapopescu what the config you have?

**Comment by MysticExile** [comment]
The issue has been fixed, the game now fully functions!
