### ISSUE TITLE
Massive Performance regression in Let's Go Eevee's Partner Play menu

### ISSUE THREAD

**Issue by Tenshinen** [yuzu-emu/yuzu#3055]
Comparing performance about 5 months ago and the latest version, it's clear there has been a massive regression. I would assume Let's Go Pikachu would also have this.

Yuzu 36, today.
![Yuzu 36](https://user-images.githubusercontent.com/36275083/67996289-989f5580-fc46-11e9-8151-02d8c933cab3.png)

Canary 2384, 5 months ago.
![Yuzu Canary 2384](https://user-images.githubusercontent.com/36275083/67996312-a8b73500-fc46-11e9-97d3-e35a358bb416.png)

Specs:
AMD Ryzen 5 1600
16GB DDR4 3000
AMD RX Vega 56

<meta name="titleids"  content="0100187003a36000">

**Comment by chris062689** [comment]
Can you please pinpoint what version did not have this regression, and which version starting having this regression? 

"About 5 months ago" doesn't give us much to go on.

**Comment by Tenshinen** [comment]
I already mentioned it in the post, right above the screenshot. But the version that ran well is Canary 2384, the second picture I added.

**Comment by Hexagon12** [comment]
He was asking for the last build everything was good and the very first build this started to happen in. Was 2384 the last good build and 2385 wasn't?

**Comment by Tenshinen** [comment]
I don't know, I haven't used it since then, and every time I try to use older builds, it refuses to launch not finding a dll it needs.

**Comment by chengts95** [comment]
2419 is good, 
![image](https://user-images.githubusercontent.com/6616679/68535740-98691f00-0304-11ea-9aaf-50542519e8e3.png)
But when I tried 2595 it only has 3 fps.

**Comment by ReaperOfSouls1909** [comment]
This is dma pr this was already a known issue blink has mentioned it before

**Comment by fluffapparition** [comment]
@ReaperOfSouls1909 Issue # please?

**Comment by vuabongro** [comment]
can you give me link yuzu canary2419

**Comment by Morph1984** [comment]
This is a known issue, it is tracked to #2765

**Comment by catlover1019** [comment]
Can confirm that partner platy is still borked

**Comment by yuwenhua653** [comment]
Has been fixed in the latest version

**Comment by MysticExile** [comment]
Appears to have been fixed as mentioned by the above user. Do you still experience this issue? Please open a new issue. Thanks!

**Comment by BitGrub** [comment]
Seems like this compatibility regression has been re-regressed. Can we reopen this issue?
![2021-06-13 (1)](https://user-images.githubusercontent.com/20694416/121794579-59e2c700-cc01-11eb-8c83-e3ff96b37d50.png)

**Comment by BSoDGamingYT** [comment]
This problem continues to affect the Vulkan API. Reopening

**Comment by liamwhite** [comment]
Should have been fixed by https://github.com/yuzu-emu/yuzu/pull/8658
