### ISSUE TITLE
Character rendering incorrect in Duck Game

### ISSUE THREAD

**Issue by xorinzor** [yuzu-emu/yuzu#3061]
In the game "Duck Game" something odd seems to be going on in emulation vs normal gameplay.
Somehow the body of the character:
- doesn't get rendered at all when standing/walking/jumping
- get's rendered upside-down when sliding
- rendered with (I suppose) an incorrect sprite-offset when dropped to the floor.

I figured this was interesting to report in order to improve the GPU emulation and perhaps help out emulation in other software with it too.

Running on build 67a594bae

System:
windows 10 x64
i7-4790k
RTX 2070

What the character looks like in Yuzu -vs- what it should look like:
![bugged-main](https://user-images.githubusercontent.com/4212335/68082204-051e7e00-fe1a-11e9-8e3c-4edcb92a6876.png)
![normal-main](https://user-images.githubusercontent.com/4212335/68082205-051e7e00-fe1a-11e9-96e8-fa2a6b7bc3f6.png)

What dropped looks like in Yuzu -vs- what it should look like:
![bug-dropped](https://user-images.githubusercontent.com/4212335/68082206-09e33200-fe1a-11e9-88a0-e32c92a7b887.png)
![normal-dropped](https://user-images.githubusercontent.com/4212335/68082207-09e33200-fe1a-11e9-9d38-e399b3436bbe.png)

<meta name="titleids"  content="0100750001c70000">

**Comment by bunnei** [comment]
Can you share a log? (See C:\Users\USERNAME\AppData\Roaming\yuzu\log)

**Comment by xorinzor** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3801390/yuzu_log.txt)

**Comment by VallyFcs** [comment]
I think this might also be related to the issue, just that to me it was on Pokemon: Let's Go Pikachu.
     Yesterday was running smoothly, had like 9 hours played continuous, after this morning update this bug happened. Even after reinstalling yuzu several times since it's auto-updating, i've had obtained same results as the screens below.

My System Specs:
![SysSpec](https://user-images.githubusercontent.com/57322329/68087250-9d3d5700-fe5c-11e9-9898-bec2552f19e6.jpg)
Also the log file:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3801690/yuzu_log.txt)



      Here are some Screen Shots, with the problem that occured:
![ss, gpu glitch](https://user-images.githubusercontent.com/57322329/68087064-daa0e500-fe5a-11e9-9a65-1109fa577a03.jpg)
![ss, gpu glitch1](https://user-images.githubusercontent.com/57322329/68087065-db397b80-fe5a-11e9-939f-d90909e4732c.jpg)
![ss, gpu glitch2](https://user-images.githubusercontent.com/57322329/68087066-db397b80-fe5a-11e9-97e7-17485686fd31.jpg)
![ss, gpu glitch3](https://user-images.githubusercontent.com/57322329/68087067-db397b80-fe5a-11e9-8936-2b8c84bd46e9.jpg)

**Comment by xorinzor** [comment]
looks pretty similar. Was this the halloween build? :P That's horror material haha.

**Comment by VallyFcs** [comment]
> looks pretty similar. Was this the halloween build? :P That's horror material haha.

If it was... i for sure am displeased with the occurrence :)

**Comment by fluffapparition** [comment]
Texture mapping.

**Comment by fluffapparition** [comment]
Texture mapping.

**Comment by FranciscoReMo** [comment]
It's the same with this.
 
![image](https://user-images.githubusercontent.com/43990816/68091345-d4bcfb00-fe7e-11e9-91aa-7747f789c10a.png)
![image](https://user-images.githubusercontent.com/43990816/68091358-0930b700-fe7f-11e9-851e-7515e6565aa9.png)

And the performance is worse.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3802078/yuzu_log.txt)

**Comment by xorinzor** [comment]
That doesn't seem the same issue that I'm having, lets not get things mixed
up here. You might be better off opening a new issue

**Comment by FranciscoReMo** [comment]
It seems to me, more or less the same. Why? Because it is between a visual failure that does not load the texture or the light does not render well. Either characters or scenes. Look at the Pokemon Let's Go. And it affects starting to update.

**Comment by xorinzor** [comment]
Yes, but I wasn't referring to that in the pokemon go pictures. It looked
to me like sprites were incorrectly oriented (ie: Pikachu's eyes). If thats
just texture mapping issues, it's not the same as my issue either and thus
would need it's own issue as well.

Look at my pictures for the subject that this issue is about

**Comment by FearlessTobi** [comment]
Please open seperate issues for problems in other games.

**Comment by benderscruffy** [comment]
still has all the problems from the first post
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4607436/yuzu_log.zip)

**Comment by MysticExile** [comment]
Fixed

**Comment by bblolol** [comment]
How?? can you help me?
