### ISSUE TITLE
Link's Awakening renders black screen only

### ISSUE THREAD

**Issue by mdindoffer** [yuzu-emu/yuzu#3068]
Happens on the latest public build.
![Clipboard01](https://user-images.githubusercontent.com/12681399/68092839-967c0780-fe8f-11e9-9ff2-94cbd552604b.png)

Nvidia 1050 Ti, Win 10 x64 (10.0.17763.805) , WHQL driver 441.08
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3802213/yuzu_log.txt)

Edit:
Results are the same whether the Async GPU rendering is on or off, even without shader disc caching.

<meta name="titleids"  content="01006bb00c6f0000">

**Comment by ReaperOfSouls1909** [comment]
cause you have amd gpu?

**Comment by mdindoffer** [comment]
> 
> 
> What driver?

Sorry, accidentaly posted an empty issue. Edited now.

**Comment by Hexagon12** [comment]
The next mainline build will have this fixed.

**Comment by mdindoffer** [comment]
Confirmed, v43 now renders as expected.
