### ISSUE TITLE
Super Mario Odyssey - Crashes system using Ubuntu

### ISSUE THREAD

**Issue by Damien5497** [yuzu-emu/yuzu#3069]
Hello! So I just got started using Yuzu on Ubuntu, since I, unfortunately, use an AMD RX 560 4GB. My other games run fine with my R7 2700, 16 GB DDR4, and RX 560, but during the intro, it completely locks up my PC when on Ubuntu with the Mesa drivers, since I have a dual-booting setup. I don't know if it's a driver problem, but if you know the problem, just give me a friendly reply. In the future, I'm planning to upgrade to an Nvidia RTX 2060. Cheers, mate!

<meta name="titleids"  content="0100000000010000">

**Comment by Hexagon12** [comment]
Could you check the console log to check if there's any AMDGPU entries about a ring timeout?

**Comment by z0z0z** [comment]
Can confirm this on RX580 8GB. Been like this as long as I can remember, going back to 2018. It will freeze Xorg, sometimes you can kill it or get to another tty to kill it

**Comment by MDTech-us-MAN** [comment]
I had a few crashes on the intro cutscene on Ubuntu 19.04, running Mesa 19.1.4 on a RX 580.
[yuzu-dmesg](https://gist.github.com/MDTech-us-MAN/1df038b5de77e429899667309cebfd2e)

Once I figured out to skip it, I got in-game. (although the performance was awful, I blame my old CPU)

**Comment by ReinUsesLisp** [comment]
This should be tested again once Ubuntu 20.04 releases with a new mesa version.

**Comment by ihsa1998** [comment]
In my case I have a crash after 10 seconds of gameplay initiated on Ubuntu 20.04.1, running Mesa 20.20 on my RX 580. The game runs pretty smoothly using OpengGL and docked mode tho.

**Comment by robzombie91** [comment]
Using mesa 22.1.0 completely crashes my system forcing a complete reboot

**Comment by liamwhite** [comment]
I can't reproduce this personally with my 560 4GB on Fedora 35. Comment if it still is an issue and you can provide a yuzu log.
