### ISSUE TITLE
i dont have shader folder in my yuzu file

### ISSUE THREAD

**Issue by dijgof** [yuzu-emu/yuzu#3095]

**Comment by Yvar192** [comment]
it'll get generated when yuzu compiles & caches some shaders.

**Comment by jonsn0w** [comment]
As yvar state, it generates after you compile and cache shaders for your games. Please run your games first to build a cache.

**Comment by dijgof** [comment]
i am trying to load super mario maker 2 but it keeps saying missing files

**Comment by jonsn0w** [comment]
You need to dump your keys from your nintendo switch. please follow this guide:

https://yuzu-emu.org/help/quickstart/

**Comment by dijgof** [comment]
wait. you need a Nintendo switch

**Comment by jonsn0w** [comment]
Yes. Have a nice day.

**Comment by dijgof** [comment]
:( :( :(

**Comment by Yvar192** [comment]
you should probably close this issue, as it isn't exactly valid
