### ISSUE TITLE
issue with controls after a cutscene  POkemon * yuzu 56 build

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3099]
[ 496.914562] HW.GPU <Critical> video_core\surface.cpp:PixelFormatFromTextureFormat:400: Unimplemented format=3, component_type=4
[ 496.914573] Debug <Critical> video_core\surface.cpp:PixelFormatFromTextureFormat:401: Assertion Failed! Unreachable code!
[ 496.990286] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called
[ 496.991566] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called
[ 496.993078] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called
[ 496.994221] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called
[ 496.999946] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called
[ 497.025239] Render.OpenGL <Warning> video_core\renderer_opengl\gl_rasterizer.cpp:AccelerateDisplay:836: Framebuffer pixel_format is different
[ 497.026207] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called
[ 497.034168] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:501: API OTHER 65536: Framebuffer unsupported. Framebuffer object 3 is unsupported because the depth and stencil attachments are mismatched.
[ 497.076807] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:501: API PERFORMANCE 131186: Buffer performance warning: Buffer object 140 (bound to GL_SHADER_STORAGE_BUFFER (3), GL_SHADER_STORAGE_BUFFER (4), GL_SHADER_STORAGE_BUFFER (5), and GL_SHADER_STORAGE_BUFFER (6), usage hint is GL_DYNAMIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.
[ 497.099070] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:501: API PERFORMANCE 131186: Buffer performance warning: Buffer object 140 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), GL_SHADER_STORAGE_BUFFER (3), GL_SHADER_STORAGE_BUFFER (4), and GL_SHADER_STORAGE_BUFFER (5), usage hint is GL_DYNAMIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.
[ 497.106178] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:501: API PERFORMANCE 131186: Buffer performance warning: Buffer object 140 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), GL_SHADER_STORAGE_BUFFER (3), GL_SHADER_STORAGE_BUFFER (4), GL_SHADER_STORAGE_BUFFER (5), and GL_SHADER_STORAGE_BUFFER (6), usage hint is GL_DYNAMIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.
[ 497.108223] HW.GPU <Critical> video_core\surface.cpp:PixelFormatFromTextureFormat:400: Unimplemented format=3, component_type=4
[ 497.108233] Debug <Critical> video_core\surface.cpp:PixelFormatFromTextureFormat:401: Assertion Failed! Unreachable code!
[ 497.147141] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called
[ 497.150401] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called
[ 497.152962] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called
[ 497.158455] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called
[ 497.159976] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called
[ 497.162010] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:490: (STUBBED) called

**Comment by ReaperOfSouls1909** [comment]
add game name please

**Comment by Schplee** [comment]
Was this log file from Pokemon Let's Go?

**Comment by ReaperOfSouls1909** [comment]
PixelFormatFromTextureFormat:400: Unimplemented format=3, component_type=4 is not from lets go

**Comment by Schplee** [comment]
Closing issue.

We don't provide support for piracy. If you obtained this game legitimately earlier than release, please wait until the game has been officially released to submit issues.

**Comment by bukyapavankumar** [comment]
> Closing issue.
> 
> We don't provide support for piracy. If you obtained this game legitimately earlier than release, please wait until the game has been officially released to submit issues.

how you know what it is ?lol

**Comment by ReaperOfSouls1909** [comment]
@bukyapavankumar PixelFormatFromTextureFormat:400: Unimplemented format=3, component_type=4  is in one game only pokemon sword i was sent logs when it leaked
