### ISSUE TITLE
Chinese and Korean fonts are displayed as ??? in Pokemon: Let's Go

### ISSUE THREAD

**Issue by lgjx123** [yuzu-emu/yuzu#3101]
game (mutilple language include), select Chinese, and show all text with ????
sure about shared_font.bin in sysdata folder and by the way, Japanese work fine.
test game: Pokemon Sword, Link's Awakening

<meta name="titleids"  content="010003F003A34000,0100187003A36000">

**Comment by Morph1984** [comment]
@lgjx123 ensure you have your system archives dumped from your nand and place it in %APPDATA%\yuzu\nand\system\Contents\registered

**Comment by lgjx123** [comment]
> @lgjx123 ensure you have your system archives dumped from your nand and place it in %APPDATA%\yuzu\nand\system\Contents\registered

@Morph1984 patreon release october 2019 work fine. and recently mainline no. like yuzu 54

**Comment by FearlessTobi** [comment]
Korean has the same issue.

**Comment by FearlessTobi** [comment]
Caused by https://github.com/yuzu-emu/yuzu/pull/2897.

**Comment by Morph1984** [comment]
The issue has been attributed to broken OSS fonts. Fonts from dumped sysarchives work properly.

**Comment by lgjx123** [comment]
@Morph1984 sorry I didn't check system archives fonts. now download from the web and solved. I just used shared_font.bin before and it work fine all the time until recent yuzu version.  
@psw14kr you can google "yuzu system archive" and download archive files, put all the file into nand\system folder to solved this problem.

**Comment by DarkLordZach** [comment]
Piracy is against our rules.

**Comment by rathakorn9** [comment]
ok

**Comment by chris062689** [comment]
Fixed by https://github.com/yuzu-emu/yuzu/commit/8a7cdfc3ff1956f7895bec1c60cfe1a0abc21b12

**Comment by Bluefissure** [comment]
The fix was reverted in https://github.com/yuzu-emu/yuzu/pull/3365, is it still breaking the ci flow now?
