### ISSUE TITLE
Pokemon sword yuzu 56 issue with controls after a cutscene

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3108]
[1468.980475] HW.GPU video_core\surface.cpp:PixelFormatFromTextureFormat:400: Unimplemented format=3, component_type=4
[1468.980485] Debug video_core\surface.cpp:PixelFormatFromTextureFormat:401: Assertion Failed! Unreachable code!

**Comment by FearlessTobi** [comment]
This issue doesn't meet our standards for our issue report and talk about this game isn't allowed yet as per our rules. 

Closing

**Comment by bukyapavankumar** [comment]
when can i talk about this?

**Comment by AniLeo** [comment]
His entire GitHub history these past days is spamming leaked game issues on here and Ryujinx 🤔

The game is barely out on the Australian eShop, people aren't idiots

**Comment by bukyapavankumar** [comment]
I know that

**Comment by fluffapparition** [comment]
@bukyapavankumar where is "here"? Lol.

**Comment by bukyapavankumar** [comment]
can i reopen the issue now?

**Comment by ReaperOfSouls1909** [comment]
> can i reopen the issue now?

No the issue was solved with a pr today

**Comment by bukyapavankumar** [comment]
Which build?

**Comment by bukyapavankumar** [comment]
> > can i reopen the issue now?
> 
> No the issue was solved with a pr today
Do you have a  build with or merged?

**Comment by bukyapavankumar** [comment]
Do you have a build with pr merged?
