### ISSUE TITLE
Each game boot with own custom configuration

### ISSUE THREAD

**Issue by FranciscoReMo** [yuzu-emu/yuzu#3115]
For example, the Pokemon Let's Go needs a specific configuration and Super Mario Odess is other, etc. You need a boot with own custom configuration for each game. It's a suggestion that could be useful. This option's integrated in RPCS3 and Cemu.

**Comment by fluffapparition** [comment]
@FranciscoReMo Im pretty sure this is in Dolphin too. It wouldnt hurt to learn from the other emulators and implement it here too

**Comment by DarkLordZach** [comment]
Disagree - this leads to developers making game specific hacks and not actually trying to find the hardware accurate behavior

At one point I was going to add a feature like this, but it was only going to be custom button inputs per game, not graphics settings.

**Comment by FranciscoReMo** [comment]
Ok on that I also agree. Cause the emulator needs to improve a lot.
When the emulator is more advanced, could it be added? This is very useful for the user.

**Comment by Morph1984** [comment]
Closed by #4098
