### ISSUE TITLE
 Pokemon Sword & Shield - Running in Tall Grass isn't possible

### ISSUE THREAD

**Issue by BSoDGamingYT** [yuzu-emu/yuzu#3116]
In pokemon sword and shield, it is currently not possible to run/sprint in any tall/long grass in the game (While it is possible on switch) The player character simply defaults to the slow-moving/sneaking animation, regardless of input.

Video Example off the problem: https://youtu.be/16obz1-pwBM

I have tried each input configuration and none of them fix the problem, as well as setting different deadzone values in the config files.

Tested on Latest release at the time of this issues post (yuzu 56)

<meta name="titleids"  content="0100ABF008968000,01008DB008C2C000">

**Comment by toMY4534** [comment]
How you got here to me does not continue at all in the beginning of the forest

**Comment by MysticExile** [comment]
Superseded by #3320

**Comment by goldenx86** [comment]
Should this be closed?

**Comment by shoval787** [comment]
zcxczx

**Comment by Janmm14** [comment]
Cannot reproduce

**Comment by neutrOYey** [comment]
zczc
