### ISSUE TITLE
Pokemon Sword and Shield - The bike not work

### ISSUE THREAD

**Issue by FranciscoReMo** [yuzu-emu/yuzu#3117]
When I tried the game with my saved game on the Switch, if you press X, the game puts you on the bike. But you in the yuzu 60 you get this error. And then softlock.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3852846/yuzu_log.txt)
![image](https://user-images.githubusercontent.com/43990816/68968604-441ddd80-07e3-11ea-89c6-de595d57d731.png)

**Comment by BSoDGamingYT** [comment]
You are pressing the wrong buttons.

In Sw/Sh, you press + or - to get on the bike.

You have  clearly pressed Y and called the online service, causing that crash

**Comment by FranciscoReMo** [comment]
I feel my explanation, I said press X but it was my mistake, because I have the buttons changed for comfort on the keyboard. Only work, for me A or B or Y or move, other button say this error. I have Nvidia 970.

PD: Too fast they closed it without letting me explain. But it's okay, I'll continue playing in the Swicth.
