### ISSUE TITLE
Shader ballot is unavailable but required by the shader

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3120]
Debug <Critical> video_core\shader\control_flow.cpp:ParseCode:261: Assertion Failed! Shader passed the current limit!

[  31.945509] Debug <Critical> video_core\shader\decode.cpp:DecodeInstr:248: Assertion Failed! Unhandled instruction: 0

[  31.946170] Render.OpenGL <Error> video_core\renderer_opengl\gl_shader_decompiler.cpp:ShuffleIndexed:1971: Shader ballot is unavailable but required by the shader

[  31.946204] Render.OpenGL <Error> video_core\renderer_opengl\gl_shader_decompiler.cpp:FSwizzleAdd:1387: Shader ballot is unavailable but required by the shader

required by pokemon sword and shield

tested in yuzu 60

**Comment by BSoDGamingYT** [comment]
If your GPU is an Intel iGPU...this issue is caused by their windows driver not having support for Shader_ballot. This is not a yuzu issue if that is the case

**Comment by bukyapavankumar** [comment]
I have nvidia GPU  and igpu

**Comment by FearlessTobi** [comment]
Invalid issue.

**Comment by bukyapavankumar** [comment]
At least explain why this is invalid and close?
