### ISSUE TITLE
Failed to find process ID

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3122]
[  50.032951] Service.ACC <Warning> core\hle\service\acc\acc.cpp:InitializeApplicationInfoRestricted:333: (Partial implementation) called, process_id=0
[  50.032960] Service.ACC <Error> core\hle\service\acc\acc.cpp:InitializeApplicationInfoBase:355: Failed to find process ID

Error in  pokemon sword and shield

tested in yuzu 60

**Comment by FearlessTobi** [comment]
Invalid issue.

**Comment by bukyapavankumar** [comment]
Invalid?
