### ISSUE TITLE
yuzu crash when loading Pokemon Sword

### ISSUE THREAD

**Issue by Oopsy1** [yuzu-emu/yuzu#3124]
I did try hard and "yuzu.exe" still "stopped working". How can i do to fix this :<
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3853574/yuzu_log.txt)

**Comment by Schplee** [comment]
Our issue tracker isn't for support requests. Please ask in the discord server or our forum.

**Comment by fluffapparition** [comment]
What did you "try hard"?
