### ISSUE TITLE
No 3D output in Sword/Shield on AMD

### ISSUE THREAD

**Issue by Tenshinen** [yuzu-emu/yuzu#3125]
Tested on Yuzu 60. 

GPU I'm using is an RX Vega 56.

AMD GPUs don't get any 3D output. Text, loading screens, intro menu, and the logo appear, but no 3D is rendered, resulting in just black. 

I can choose my photo, type in a name, but once the intro begins the screen is completely black except for the text boxes. The framerate stutters as if it is loading and compiling shaders.

<meta name="titleids"  content="0100ABF008968000,01008DB008C2C000">

**Comment by z0z0z** [comment]
This also effects Linux with mesa drivers on an RX580.

**Comment by Hexagon12** [comment]
Please upload a log file.

**Comment by Tenshinen** [comment]
> Please upload a log file.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3854084/yuzu_log.txt)

Uploaded a log. Lots of spam, resulting in a large log file, 6.79MB. 

Hope that helps~

**Comment by drudigger** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3854330/yuzu_log.txt)


Heres my log. R9 290x

**Comment by z0z0z** [comment]
So what I'm seeing in these logs and mine is this:

`Render.OpenGL <Warning> video_core/renderer_opengl/gl_rasterizer.cpp:AccelerateDisplay:837: Framebuffer pixel_format is different`

I edited gl_rasterizer.cpp from this

```
if (params.pixel_format != pixel_format) {
    LOG_WARNING(Render_OpenGL, "Framebuffer pixel_format is different");
}
```
to this
```
LOG_WARNING(Render_OpenGL, "Framebuffer pixel_format is different, ppf={:X}, pf={:X}", params.pixel_format, pixel_format);
```

Now I can see in my log what the actual difference is between `params.pixel_format` and `pixel_format`:

`Framebuffer pixel_format is different, ppf=26, pf=0`

Spammed over and over again. I am assuming the pixel_format of 0 not matching params.pixel_format of 26, means regular pixel_format is totally invalid to start with?

RX580 mesa-git Linux 5.4-rc7

**Comment by phede86** [comment]
> Tested on Yuzu 60.
> 
> GPU I'm using is an RX Vega 56.
> 
> AMD GPUs don't get any 3D output. Text, loading screens, intro menu, and the logo appear, but no 3D is rendered, resulting in just black.
> 
> I can choose my photo, type in a name, but once the intro begins the screen is completely black except for the text boxes. The framerate stutters as if it is loading and compiling shaders.

the same thing happens with amd RX590, Windows 10, latest amd driver

> Tested on Yuzu 60.
> 
> GPU I'm using is an RX Vega 56.
> 
> AMD GPUs don't get any 3D output. Text, loading screens, intro menu, and the logo appear, but no 3D is rendered, resulting in just black.
> 
> I can choose my photo, type in a name, but once the intro begins the screen is completely black except for the text boxes. The framerate stutters as if it is loading and compiling shaders.

the same thing happens with amd RX590, Windows 10, latest amd driver

**Comment by z0z0z** [comment]
Fixed for me.

**Comment by Tenshinen** [comment]
> Fixed for me.

Fixed for me too. Only issue that remains is wireframe across all the models, but that's a separate issue.

**Comment by Yvar192** [comment]
This is not fixed in master yet, though. Should probably re-open this issue.
[Link to PR which fixes this](https://github.com/yuzu-emu/yuzu/pull/3141)
