### ISSUE TITLE
Softlocks in pokemon sword and shield

### ISSUE THREAD

**Issue by AayuRockzzz** [yuzu-emu/yuzu#3128]
there are hell lot of softlocks in pokemon sword and pokemon shield. please fix those as soon as possible(huge request) since i dont wanna play em on my small switch screen(where i cant even record gameplay easily)

<meta name="titleids"  content="01008DB008C2C000,0100ABF008968000">

**Comment by bukyapavankumar** [comment]
They are already working on it .so close this issue

**Comment by jonsn0w** [comment]
This isn’t a GitHub issue. This is a personal request. The team is very aware of the soft locks.

**Comment by Yvar192** [comment]
This personal request still address a valid issue, though?

**Comment by Hexagon12** [comment]
The issue was reopened because it's valid.

**Comment by FernandoS27** [comment]
Don't add kernel-issue until we can confirm it's a kernel issue. So far there have been no sights from it.

**Comment by fluffapparition** [comment]
@aayurockzzz logs?

**Comment by AayuRockzzz** [comment]
@fluffapparition how to send that?

**Comment by drudigger** [comment]
Go into debug tab in yuzu options and click to open the folder. The log should be in there.

**Comment by sharkiller** [comment]
here are my logs from a softlock at the start. one log is with all the spam removed and the other is the untouched.

softlocks related log should be the last seconds of the log.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3854528/yuzu_log.txt)
[yuzu_log_filtered.txt](https://github.com/yuzu-emu/yuzu/files/3854529/yuzu_log_filtered.txt)

**Comment by nnDropZz** [comment]
The first Softlock is 1-2 minute into the game while the Intro plays and should be on the end of the log file.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3854532/yuzu_log.txt)

**Comment by AayuRockzzz** [comment]
yeah this is one of the million softlogs in the game. further into the game there is a softlog almost everytime we encounter our rival, or the champion or the professor or when we enter the wild area

**Comment by AayuRockzzz** [comment]
i know you guys are working hard but atleast you guys could give a proper eta aswell? so we dont have to check in daily in curiosity?

**Comment by AayuRockzzz** [comment]
when is this gonna get resolved been 10days since this was posted

**Comment by DarkLordZach** [comment]
You seem to misunderstand that this is a volunteer-run project, and the softlocks issue is not straight forward enough to know exactly how long it will take.

Further spam/off-topic/rude comments will get you banned from our GitHub.

Thanks, Zach

**Comment by fluffapparition** [comment]
@AayuRockzzz that depends on how long the yuzu team takes to find the root cause.

**Comment by Trigcase** [comment]
So is anyone stuck on that sequence where ur staring at ur phone and the dude is supposed to knock on ur door but he just doesn't

**Comment by AayuRockzzz** [comment]
Yes

**Comment by FearlessTobi** [comment]
Superseded by #3320.
