### ISSUE TITLE
Shader cache Error

### ISSUE THREAD

**Issue by zer0gold** [yuzu-emu/yuzu#3131]
Everytime a trie to load pokemon Let's go pikachu, with a preloaded shader cache from the internet, the yuzu not read it, instead create another shader cache and overwrite the one ia have downloaded

**Comment by Hexagon12** [comment]
Our issue tracker isn't for support requests. Please ask in the discord server or our forum.

Shader cache downloading is piracy. Build your own cache.

**Comment by FearlessTobi** [comment]
Downloading shader caches is illegal. 
Closing

**Comment by fluffapparition** [comment]
Shader caches might have traces of code from the game and therefore downloading them is prettymuch piracy, let Yuzu compile them from *YOUR OWN* copy of the game like it's supposed to. The emulator is doing its job, you arent.

**Comment by zer0gold** [comment]
Sorry, i didn't know, thanks for sharing
