### ISSUE TITLE
Pokémon SwSh Box screen not rendering properly

### ISSUE THREAD

**Issue by xZekro51** [yuzu-emu/yuzu#3132]
The box screen is not being rendered properly, here's how it looks in Yuzu 61;

![immagine](https://user-images.githubusercontent.com/28503323/68995819-3b381500-0892-11ea-987d-3e803c700f62.png)

Here's how it should look:
![immagine](https://user-images.githubusercontent.com/28503323/68995822-5571f300-0892-11ea-851f-d1b48325c2d4.png)

<meta name="titleids"  content="0100ABF008968000,01008DB008C2C000">

**Comment by MysticExile** [comment]
Superseded by #3320

**Comment by JoseFreitas990** [comment]
Hey, where did you get the xci from?
