### ISSUE TITLE
Pokemon Sword & Shield - Weird graphical glitch

### ISSUE THREAD

**Issue by Swagarot** [yuzu-emu/yuzu#3134]
![unknown](https://user-images.githubusercontent.com/57872907/69011882-128a4b00-0978-11ea-9539-59aedc43a08d.png)
im pretty sure its just stuff not loading properly.

<meta name="titleids"  content="0100ABF008968000,01008DB008C2C000">

**Comment by R3Spected** [comment]
where i cant see

**Comment by Swagarot** [comment]
![223233](https://user-images.githubusercontent.com/57872907/69012548-bcb9a100-097f-11ea-99d5-9f6accc2395c.PNG)
this is how it should look like, the shadow is off and the textures in the emulator looks a lot worse might be less visible because of compression though

**Comment by Swagarot** [comment]
i think you can mainly see it on the trainer

**Comment by fluffapparition** [comment]
Can you clarify exactly what is wrong here, and also upload a higher resolution image, and through Imgur or some other site if neccessary?

**Comment by ogniK5377** [comment]
> Can you clarify exactly what is wrong here, and also upload a higher resolution image, and through Imgur or some other site if neccessary?

An screenshot on how it was suppose to look was posted as well as an outline of the issue. Your commets are quite unnecessary

**Comment by Swagarot** [comment]
![emuwrong](https://user-images.githubusercontent.com/57872907/69053742-c213fb80-0a12-11ea-8acf-68950f0a6270.PNG)
![emuwrongagain](https://user-images.githubusercontent.com/57872907/69053743-c2ac9200-0a12-11ea-89f8-21b465c3219d.PNG)
![emuright](https://user-images.githubusercontent.com/57872907/69053745-c2ac9200-0a12-11ea-88ab-773b9aeef1b4.PNG)
i added a picture that is the same place so the bug can be seen better,
also for some reason the bug doesn't happened at the first second of launching the game (second image), you can see the bug again at the third image

**Comment by Swagarot** [comment]
in some building it doesn't happen also and in-battle it doesn't happen

**Comment by R3Spected** [comment]
Thats just docked mode vs undocked. it switches to undocked cause of the low performance i guess
![undocked](https://user-images.githubusercontent.com/46446942/69054388-bd981480-0a0b-11ea-86ac-8035197838dd.png)
![docked](https://user-images.githubusercontent.com/46446942/69054404-c688e600-0a0b-11ea-99fc-356e38f7b454.png)

**Comment by MysticExile** [comment]
Superseded by #3320
