### ISSUE TITLE
Critical errors in Pokemon sword

### ISSUE THREAD

**Issue by yuzuerroreport** [yuzu-emu/yuzu#3135]
<Critical> video_core\shader\control_flow.cpp:ParseCode:261: Assertion Failed! Shader passed the current limit!

 <Critical> video_core\shader\decode.cpp:DecodeInstr:248: Assertion Failed! Unhandled instruction: 0

 <Critical> video_core\shader\decode\memory.cpp:TrackGlobalMemory:319: Assertion Failed! Global memory tracking failed

 <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:466: API ERROR 1282: GL_INVALID_OPERATION error generated. <program> is not successfully linked.

 <Critical> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:163: Assertion Failed!
 <Critical> core\hle\kernel\hle_ipc.cpp:WriteToOutgoingCommandBuffer:234: Assertion Failed! Handle descriptor bit set but no handles to translate
 <Critical> core\hle\kernel\hle_ipc.cpp:WriteToOutgoingCommandBuffer:239: Assertion Failed! Sending PID is not implemented

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for such reporting and support requests.

Closing

**Comment by yuzuerroreport** [comment]
Reporting in discord server results in no proper answering   and here closing the issue

**Comment by mailwl** [comment]
just wait for fix, this game probably most wanting, so it will work soon

**Comment by fluffapparition** [comment]
@mailwl It is never safe to lazily assume that someone else already has a problem handled, In other words, dont deny that a problem exists just because someone else already is aware of it. The Yuzu team is able to fix these issues faster if they have more evidence of how these problems are occurring.
