### ISSUE TITLE
Wireframe on certain models in Sword/Shield on AMD 

### ISSUE THREAD

**Issue by Tenshinen** [yuzu-emu/yuzu#3144]
Tested on Yuzu 65, which is the first version to have functioning 3D output for AMD in this title.

Certain NPCs have a wireframe mesh across them.

Seems to be most NPCs and the player character, but not any Pokémon themselves.

![yuzu65](https://user-images.githubusercontent.com/36275083/69242376-a2a6db00-0b98-11ea-8bc4-1b3098f7dd85.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3869435/yuzu_log.txt)

<meta name="titleids"  content="0100ABF008968000,01008DB008C2C000">

**Comment by phede86** [comment]
I go to 7 fps with a rx580

**Comment by jwissink** [comment]
> 
> 
> I go to 7 fps with a rx580

Try and disable "Game mode"

**Comment by FernandoS27** [comment]
Funny we had that issue before in PLGE on Windows AMD driver. I don't recall what fixed that or if it was ever fixed.

**Comment by osbodav** [comment]
> Funny we had that issue before in PLGE on Windows AMD driver. I don't recall what fixed that or if it was ever fixed.
> There are however, good news and bad news:
> Bad news is that we will be pretty much cutting support for AMD OpenGL.
> Good news is that Vulkan is around the corner and we already tested this game in Vulkan AMD. Runs flawlessly.

when do you think this will be released?

**Comment by Tenshinen** [comment]
> Funny we had that issue before in PLGE on Windows AMD driver. I don't recall what fixed that or if it was ever fixed.
> There are however, good news and bad news:
> Bad news is that we will be pretty much cutting support for AMD OpenGL.
> Good news is that Vulkan is around the corner and we already tested this game in Vulkan AMD. Runs flawlessly.

You scared me for a moment there, haha. Good to hear Vulkan is on the way though!

PLGE also had the issue, yeah. It wasn't fixed entirely, but the issue was definitely reduced. Originally, every model had it. Nowadays only trees, plants, and the edges of those ledges you can jump down have it. I can't tell you which version fixed it, because I honestly don't know. :p

**Comment by FernandoS27** [comment]
After some discussion with my partner, let me clarify something. We still be supporting AMD OGL to some extent but we will give greater importance to Vulkan backend fixes than to AMD OGL. In general, it will be weighting which backend works better for a game. If Vulkan backend works better for game X and OGL backend has issues in that game for AMD, we'll give more priority to Vulkan.

**Comment by phede86** [comment]
> After some discussion with my partner, let me clarify something. We still be supporting AMD OGL to some extent but we will give greater importance to Vulkan backend fixes than to AMD OGL. In general, it will be weighting which backend works better for a game. If Vulkan backend works better for game X and OGL backend has issues in that game for AMD, we'll give more priority to Vulkan.
> 
> Released date of Vulkan backend is very soon (tm).

and multicore support and AMD GPUs?

**Comment by Shinary** [comment]
a mi tambien me pasa lo mismo yo tengo y amd a8 7410 apu radeon r5 graphics

**Comment by MysticExile** [comment]
Superseded by #3320

**Comment by krinke54** [comment]
hola alguien sabe como arreglar este problema

**Comment by KillTimer777** [comment]
Vulkan Getting crashed evertime after running smoothly for 3 min
