### ISSUE TITLE
Blue Flashes Seen during Battle

### ISSUE THREAD

**Issue by ankurbhardwaj1234** [yuzu-emu/yuzu#3148]
I am seeing blue screen flashes during battle in Pokemon Sword.
I am using Acer Aspire 5
I just dumped into nand 
ALso just applied a texture mod and updated yuzu from 67 to 68

**Comment by FearlessTobi** [comment]
This is an issue trackers for developers and not a support forum.
Please use our forum or Discord for support requests.
