### ISSUE TITLE
Some games crash seconds after being ingame

### ISSUE THREAD

**Issue by goldenx86** [yuzu-emu/yuzu#3161]
Seems to be related to changes after yuzu 78, including it.
Affects as far as I know, it affects Pokémon Sw/Sh and Yu-Gi-oh!

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3888912/yuzu_log.txt)
[yuzu_log_270x.txt](https://github.com/yuzu-emu/yuzu/files/3888914/yuzu_log_270x.txt)

<meta name="titleids"  content="0100abf008968000,01008DB008C2C000,010022400be5a000">

**Comment by goldenx86** [comment]
Fixed by https://github.com/yuzu-emu/yuzu/pull/3162

**Comment by UndeadlyBan** [comment]
Cual es la solución????
