### ISSUE TITLE
Luigis Mansion 3 particular performance drop

### ISSUE THREAD

**Issue by CJBok** [yuzu-emu/yuzu#3179]
Version: Yuzu 84
CPU: i7-8700
GPU: RTX2070
[save_file_lm3_perf_drop.zip](https://github.com/yuzu-emu/yuzu/files/3900221/save_file_lm3_perf_drop.zip)

When walking around on this balcony the performance drops by 50%
![image](https://user-images.githubusercontent.com/3213428/69782826-61bf4f80-11b2-11ea-9bf9-574d2b0fe1cd.png)

When you pickup the watering can and then walk around nice stable performance
![image](https://user-images.githubusercontent.com/3213428/69782840-6a178a80-11b2-11ea-9348-c2247eef8771.png)

**Comment by FearlessTobi** [comment]
Unstable performance should be expected at this early stage of development.
Also it's very well poasible the game is more demanding on the real console in this particular area too. 
I'm going to close this as this is no major regression or anything with a proof of an emulator issue.
Thanks for your help though!
