### ISSUE TITLE
yuzu cannot save some of the begining save files of some titles

### ISSUE THREAD

**Issue by JeonDohyeon** [yuzu-emu/yuzu#3180]
The unplayable glitches of official titles of Nintendo, [Luigi's Mansion 3] and [Pokemon Sword/Shield(from GameFreak)], are based on the UNSAVEABLE biggining savefiles.
Luigi's Mansion 3 stops when it tries to save.
Pokemon Sword/Shield stops because one of the reason is that it didn't save the savefile on the directory.

Last trial at yuzu 85

**Comment by FearlessTobi** [comment]
The softlock issues of those two games have nothing to do with save file size. For LM3, it's an VFS issue, for Pokemon we don't know yet.
Closing
