### ISSUE TITLE
Compilation on Mac issu

### ISSUE THREAD

**Issue by quentincrn** [yuzu-emu/yuzu#3186]
Hello, 

I have an issue on my Mac (Catalina 10.15.1) when i launch this command : make -j4

/Users/Quentin/Logiciels/yuzu/src/video_core/renderer_opengl/gl_shader_cache.cpp:143:9: error: 
      no matching function for call to 'hash_combine'
        boost::hash_combine(unique_identifier, boost::hash_value(code_b));

Can anyone help me ? 
Thanks.

**Comment by FearlessTobi** [comment]
Mac isn't officially supported anymore by us at this current point in time.

Closing

**Comment by z0z0z** [comment]
This is likely because the boost libraries you're trying to compile against are very out of date.
