### ISSUE TITLE
Pokemon Sword & Shield - Resetting Hour Glitch

### ISSUE THREAD

**Issue by Fougeta** [yuzu-emu/yuzu#3187]
Everytime the game boots, the current time always rollback to 01/01/1970, making it impossible to do time based events like:
- Strong Pokemon in the Wild Area respawns
- Coffee Shop rematches
- Poké Jobs
- Berry trees replenishment
- Market guys on a city in the game that have time based stocks
- Probably more things that I can't remember/don't know

No idea if it's already reported, if so, please ignore this.

**Comment by FernandoS27** [comment]
One of the developers has a fix for that, but you'll need to dump some files from your switch (sysmodules)

**Comment by Real96** [comment]
> One of the developers has a fix for that, but you'll need to dump some files from your switch (sysmodules)

Can you share the link pls?

**Comment by ReaperOfSouls1909** [comment]
That’s wip code you need to wait till it’s done

**Comment by slashiee** [comment]
Was superseded by #3320 and fixed in master/mainline with #3271, requesting a close.
