### ISSUE TITLE
Source code included with automated (Early Access) builds from the installer are missing main CMakeLists.txt

### ISSUE THREAD

**Issue by z0z0z** [yuzu-emu/yuzu#3190]
I want to become yuzu patron on Patreon, but only if I know the source code bundled with Early Access builds can compile on Linux.

I know you only provide the Early Access builds and source code through the Windows-only yuzu installer. That's fine, I can just use a Windows VM (because it doesn't work in Wine). However I tested this out with regular yuzu-mainline, and the source code that was bundled with it is missing the main CMakeLists.txt file (https://github.com/yuzu-emu/yuzu/blob/master/CMakeLists.txt) needed for regular compilation.

On Discord I was told that this CMakeLists.txt file isn't actually supposed to be missing, and suggested that I could report it on Github.

**Comment by ReaperOfSouls1909** [comment]
just checked and it's there

**Comment by ReaperOfSouls1909** [comment]
![image](https://user-images.githubusercontent.com/18043258/70094740-90498a00-15f9-11ea-8e36-93d83d222701.png)

**Comment by z0z0z** [comment]
That's not the main CMakeLists.txt file.

**Comment by ReaperOfSouls1909** [comment]
Where is it than I can double check

**Comment by FernandoS27** [comment]
It's weird, the sourcecode is packed from the Azure builder, should be the exact same used to build it.

**Comment by jroweboy** [comment]
It should go live in the next build, sorry about that!
