### ISSUE TITLE
BOTW (audio issue, not support)

### ISSUE THREAD

**Issue by Demannu35** [yuzu-emu/yuzu#3193]
Yuzu botw v1.5 has an audio issue. Audio persisting stuttering on intro and save file. 

No support is required just a yuzu fix. Thank you.

**Comment by FearlessTobi** [comment]
Audio stuttering is caused by the emulator not running fullspeed. 
This in itself isn't a yuzu issue, but an issue with your PC being too slow.

Please stop opening the same issue over and over again as we might need to consider excluding you from our rpository otherwise. Thanks.
