### ISSUE TITLE
Saga Scralet Grace: Ambitions - Blurry Graphics on world map

### ISSUE THREAD

**Issue by CeruleanSky** [yuzu-emu/yuzu#3194]
I am submitting this issue to have this documented. I tried this game on Yuzu Mainline 92.  I tried various combinations of async gpu and accurate gpu emulation togged but blurying still occurred.  It could be a DOF issue similiar to the zelda issue.

Using a Nvidia GTX 1070 with recent drivers.

![a1](https://user-images.githubusercontent.com/2829875/70192972-86905700-16cb-11ea-8bf8-1803669d2db8.png)
![a2](https://user-images.githubusercontent.com/2829875/70192977-8b550b00-16cb-11ea-84f0-b6929790783c.png)

Here is what is looks like on the switch, which does have blurriness in the distance, but is sharp up close, and text in the distance up to a point is fine as well.

![a3](https://user-images.githubusercontent.com/2829875/70193804-51d1cf00-16ce-11ea-84b2-d778f925618d.png)

If you need any additional info or logs please ask.  They tend to get quite large and as this was a graphics issue which can be compared with the switch itself, I omitted them at this point, but I am more than happy to adjust log filtering or upload relative excerpts.

**Comment by Zeroksas** [comment]
This issue is fixed in upcoming vulkan API.

**Comment by CeruleanSky** [comment]
Just tested today and it seems like the blurriness went away in Saga Scarlet and it is working properly at least by Yuzu Mainline 102

Thanks for the hard work.

![image](https://user-images.githubusercontent.com/2829875/70878739-aad41980-1f90-11ea-9e39-f504d6662822.png)
