### ISSUE TITLE
CDescriptors not implemented

### ISSUE THREAD

**Issue by ogniK5377** [yuzu-emu/yuzu#32]
As of [this commit](https://github.com/yuzu-emu/yuzu/blob/713c1ed2037e73d3eadcc605c839f069aefc4853/src/core/hle/kernel/hle_ipc.cpp#L883) C Descriptors are currently unimplemented. CDescriptors are needed for "nvdrv" ioctls and various other IPC messages.

**Comment by bunnei** [comment]
Fixed by #96
