### ISSUE TITLE
OpenGL <Error>

### ISSUE THREAD

**Issue by ToniKuipers** [yuzu-emu/yuzu#3207]
Hi guys,

I run duo boot windows 10 on my mac book pro to run Yuzu but i stuck at a white screen each time i launch a game.

Windows 10 Pro
MacBookPro15,1
Intel(R) Core(TM) i7-8850H CPU @2,60GHz, 6 core('s)
OpenGL version: 4.6
Vulkan version: 1.1.70

`[  24.895708] Render.OpenGL <Error> video_core\renderer_opengl\gl_shader_util.cpp:LoadShader:48: Error compiling fragment shader:
Fragment shader failed to compile with the following errors:
ERROR: 0:5: error(#366) Extension GL_ARB_shader_viewport_layer_array is not supported on this card
ERROR: error(#273) 1 compilation errors.  No code generated`

**Comment by Yvar192** [comment]
you need a newer GPU

**Comment by goldenx86** [comment]
GPU is fine, drivers are too old.

**Comment by ToniKuipers** [comment]
@goldenx86 How to update the drivers?

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord or our forums on help with driver/outdated hardware issues.

**Comment by fluffapparition** [comment]
@ToniKuipers well, I mean, to be honest. Intel driver support on Windows is absolutely horrible.

Also, intel integrated cards arent good for high end games, therefore I would suggest a dedicated card for running Yuzu. My suggestion would be a NVidia GeForce GTX 1070 or better.
