### ISSUE TITLE
Text in color is missing in Zelda Link's Awakening

### ISSUE THREAD

**Issue by lgjx123** [yuzu-emu/yuzu#3220]
![image](https://user-images.githubusercontent.com/7222057/70697418-6f232080-1d00-11ea-9bbb-608e70f44423.png)

**Comment by komawoyo** [comment]
This post might be useless without any hardware/settings information and/or logs

**Comment by lgjx123** [comment]
Early Access 81 solved this problem

**Comment by Yvar192** [comment]
you should not close issues until they are fixed in master.

**Comment by MysticExile** [comment]
This issue has been fixed!
