### ISSUE TITLE
pokemon sw are lagging

### ISSUE THREAD

**Issue by pbass401** [yuzu-emu/yuzu#3225]
pokemon sw are lagging

how to fix ??
My pc 
i3 8100
ram 8 GB
GTX1050 TI

**Comment by Yvar192** [comment]
buy a better computer

**Comment by z0z0z** [comment]
Buy a 3950X or a 9900KS and overclock past 5GHz.

Even then, I don't think you'll get 30fps everywhere in open world.

**Comment by pbass401** [comment]
i can play let go pikachu not lag

**Comment by z0z0z** [comment]
Yes that's lighter more optimized game for yuzu.

**Comment by pbass401** [comment]
if me change 1080 ti Will be better or not ?

**Comment by z0z0z** [comment]
No your GPU practically doesn't matter so long as it's any modern Nvidia GPU

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
