### ISSUE TITLE
Controller profiles are Broken/Unusable for many people

### ISSUE THREAD

**Issue by BSoDGamingYT** [yuzu-emu/yuzu#3226]
The controller profiles "Single Player - Handheld - Undocked" & "Single Player - Dual Joycons - Docked" (shown below) rarely work and cause more issues than they solve for emulator usability.

![Yuzu controller profiles](https://user-images.githubusercontent.com/38402209/70852397-4e460100-1ea1-11ea-98e3-50b78ea11e92.PNG)

As far as I know, these were only implemented to deal with users playing Pokemon Let's Go (It requires the Joycons Docked Controls to function)

But, since the listed profiles have not been fully functional for a long time (No input detected when the profiles are used), they need to either be fixed or removed and the GUI window for them replaced with the fully functional Custom Controller configuration screen (Shown below)

![Custom yuzu controller mapping](https://user-images.githubusercontent.com/38402209/70852500-55b9da00-1ea2-11ea-8a6a-2596ccdf621d.PNG)

**Comment by goldenx86** [comment]
The undocked profile allows to catch pokémons in Let's go just by pressing A. I haven't found a way to replicate that on the custom profiles, so I think that's the only of the two profiles with something valuable.

**Comment by BSoDGamingYT** [comment]
You can catch pokemon in Let's Go with the A button by mapping the Joycons Docked Controller and only having it alone active (Player 1 controller set to None)

**Comment by MysticExile** [comment]
This appears to have been fixed! If they have not been, please open a new issue!
