### ISSUE TITLE
Invisible ground when using Intel iris driver

### ISSUE THREAD

**Issue by Joey11904** [yuzu-emu/yuzu#3229]
![Screenshot_20191216_144853](https://user-images.githubusercontent.com/33566635/70889401-1a8be800-2015-11ea-8714-82924b42c2e1.png)

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/3966643/yuzu_log.zip)

This doesn't happen with nvidia gpu

**Comment by lat9nq** [comment]
Can you confirm if this still happens. I cannot reproduce it here. Using iris, UHD 750 to test.

**Comment by Joey11904** [comment]
@lat9nq doesn't seem to happen anymore on iris :)
sorry for the late reply

![image](https://user-images.githubusercontent.com/33566635/145702039-1cd5303c-aeb2-41e2-9060-47a8c59dc2f6.png)
