### ISSUE TITLE
Yuzu forces standard display orientation when it gains focus

### ISSUE THREAD

**Issue by kuchenmitsahne** [yuzu-emu/yuzu#3242]
OS: Windows 10 Pro version 1909
CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
Yuzu version: HEAD-mainline-636-737-gf276676f0

This has nothing to do with the actual emulation. As soon as Yuzu gets past the updater on launch, my display (which is usually rotated 180° due to the physical orientation of my convertible laptop) gets flipped back to the standard orientation. If I then rotate the display using Ctrl+Alt+Down, it will remain in my desired orientation and stay that way if Yuzu loses focus. However, as soon as Yuzu regains focus, it will unflip my display. This issue also occurs with 90° and 270° rotations.

I've been experiencing this behavior since I installed Yuzu in January of this year. When bisecting to discover the offending build, I noticed something odd. With the [nightly](https://github.com/yuzu-emu/yuzu-nightly) and [canary](https://github.com/yuzu-emu/yuzu-canary) builds, the newest builds (as well as some older builds I tried) don't exhibit the bug. However, with [the mainline builds](https://github.com/yuzu-emu/yuzu-mainline), the oldest build I could access (mainline-0-7) as well as the newest (mainline-0-109, which is the version listed above) both exhibited the bug. Not sure what that means, but hopefully someone can make sense of that.

I've encountered an analogous bug with [Calibre](https://github.com/kovidgoyal/calibre) that was introduced in v4.0.0. It's perhaps also worth noting that I do not encounter (and to my recollection, _have_ not encountered) this behavior in Citra.

I think the most important thing I discovered while testing is that, not only did this bug not occur on a separate Windows 10 desktop, but it did not occur on the SAME MACHINE when I placed the laptop bottom-down (rather than in [propped-up convertible mode](https://user-images.githubusercontent.com/25233413/71326190-82cf4380-24c5-11ea-9b63-7748d83f642b.jpg)) and rotated the display. This was true of both Yuzu and Calibre. The laptop reports to Windows 10 when it is in convertible mode (it happens when the display is opened a bit past 180°) which triggers a Windows notification asking if the user wishes to switch to tablet mode (although toggling tablet mode and rotation lock does not appear to affect the bug). This state must be the root cause of the problem. Accelerometer data doesn't appear to play into this, as I also didn't encounter the bug when holding the laptop upside-down in traditional laptop mode.

Builds tested:

canary-200
canary-996
canary-2878

nightly-1245
nightly-1874
nightly-2174
nightly-2444

mainline-0-7
mainline-0-109

**Comment by benderscruffy** [comment]
Is this still an issue ??

**Comment by liamwhite** [comment]
Please report back if this is still an issue. Thanks!
