### ISSUE TITLE
Mario Tennis Aces and other games Fail when a profile picture is set.

### ISSUE THREAD

**Issue by Luffykun007** [yuzu-emu/yuzu#3252]
OS: Windows 10 Pro version 1909
CPU: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Yuzu version: Early access 90 HEAD-78e2b8f6c

When I try to launch Mario tennis aces on yuzu with a set profile image the game gets stuck on the loading screen (shader loading screen) If I don't set a profile image the game enters normally, there seems to be something causing this error while setting a user profile picture that is affecting some games.

Without a defined profile picture the game works normally:

![1](https://user-images.githubusercontent.com/26087621/71546097-0a0f3200-2972-11ea-8f7c-c58bd44a8e0b.JPG)

![2](https://user-images.githubusercontent.com/26087621/71546101-13989a00-2972-11ea-99c0-f1cf02291a72.JPG)

Already with a profile picture the game crashes on the shader loading screen and does not enter.

![3](https://user-images.githubusercontent.com/26087621/71546118-55294500-2972-11ea-9f71-c1ea51f836df.JPG)

![4](https://user-images.githubusercontent.com/26087621/71546121-59edf900-2972-11ea-8f7c-723cacdd0d91.JPG)

Log with the error: [Log yuzu.zip](https://github.com/yuzu-emu/yuzu/files/4007184/Log.yuzu.zip)

PS: The game Mario + Rabbits also crashes if there is a defined profile image.

**Comment by Hexagon12** [comment]
Please upload a proper log file. You only uploaded a snippet of the full log.

**Comment by Luffykun007** [comment]
@Hexagon12 Here: 

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4007316/yuzu_log.zip)

**Comment by mauroottavi** [comment]
same for me! thanks for the workaround

**Comment by FongMi** [comment]
Same here
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5623570/yuzu_log.zip)

**Comment by german77** [comment]
Works on mainline 454

**Comment by brainli13** [comment]
same problerm on main 739

**Comment by LuismaSP89** [comment]
This issue still happens for Mario tennis, please, we need to reopen the issue. It's very annoying because there's no way to delete the profile image unless you completely delete the profile with all the savegames.

**Comment by german77** [comment]
fixed by #7246 if anyone still have this issue upload a new profile image so the old one gets updated
