### ISSUE TITLE
Flickering in Pokemon Sword/Shield

### ISSUE THREAD

**Issue by BSoDGamingYT** [yuzu-emu/yuzu#3253]
In several areas of the game, the shadows will violently flicker like this. It can be replicated by standing in this exact spot/area in Hulbery (Though it also occurs in many other places)

The same bug occurs on OpenGL & Vulkan, with and without Async GPU

![p8RdC7pywi](https://user-images.githubusercontent.com/38402209/71546568-89176100-2998-11ea-8e6a-5a72233243bd.gif)

**Comment by MysticExile** [comment]
Superseded by #3320
