### ISSUE TITLE
Is macOS still deprecated, even with Vulkan support?

### ISSUE THREAD

**Issue by losh11** [yuzu-emu/yuzu#3256]
I imagine as yuzu now supports Vulkan, there shouldn't be a problem with the deprecated OpenGL apis?

**Comment by Yvar192** [comment]
MacOS unfortunately doesn't officially support Vulkan either

**Comment by Hexagon12** [comment]
Unfortunately, even other projects aiming to implement Vulkan via Metal, such as MoltenVK or gfx-portability do not currently support all of the Vulkan extensions we require.
