### ISSUE TITLE
List of Optimum libraries for source code build

### ISSUE THREAD

**Issue by vedvalsangkar** [yuzu-emu/yuzu#3263]
I cloned the repo and am trying to build yuzu. While I get no issues on the build, configuration (cmake) output says "\<lib> missing, using external lib", indicating fallback option is used. What are the libraries expected to be on the build machine?

I am not a developer, just a hobbyist trying out the application so may not have the libraries generally taken for granted. It would be good to have a consolidated list for reference.

**Comment by jroweboy** [comment]
Theres no real reason to use your own system libraries. Its not going to make it any more optimized if you do that or anything, so don't worry about it downloading from externals.
