### ISSUE TITLE
Luigi Mansion 3 save fix mod for v1.2.0?

### ISSUE THREAD

**Issue by oscarbg** [yuzu-emu/yuzu#3265]
save fix are for up to v1.1.0..

**Comment by ReinUsesLisp** [comment]
Mods are not part of the emulator. Closing as offtopic.

**Comment by BSoDGamingYT** [comment]
This is not what github issues are for. Please ask questions like this on the official discord page.

**Comment by oscarbg** [comment]
ok sorry..
