### ISSUE TITLE
Zelda Links Awakening Cheep Cheep figurine bug

### ISSUE THREAD

**Issue by LoneWolf43** [yuzu-emu/yuzu#3280]
Unable to place the Cheep Cheep figurine. Cant even read what it says on the pedestal for it at all.
Seems to be some kind of problem with the placement?

/// Cheep Cheep figurine belong in old man Ulria’s house – that’s the house to the left of the phone booth house in Mabe Village. ///

**Comment by lgjx123** [comment]
![bug](https://user-images.githubusercontent.com/7222057/74304286-7a91d700-4d97-11ea-9180-1bbf38a7c6de.jpg)
kill six birds and the door still be closed, maybe it's a softlock problem?

**Comment by schanze1** [comment]
i also have this bug

**Comment by fluffapparition** [comment]
@schanze1 Simply saying "me too" doesnt quite help. If you would like to help us solve this issue please provide more context.

Logs, screenshots, and further explanation would be appreciated.

**Comment by schanze1** [comment]
sorry bout that, i will do so :)

**Comment by psxlover** [comment]
There is no prompt to check the stand at all (no matter where you position link):
![Στιγμιότυπο οθόνης (9)](https://user-images.githubusercontent.com/1429524/77849786-c7f6c600-71d6-11ea-92b0-426cef8a4dbb.png)

In comparison the blooper stand shows a "Check" prompt when you get near it:
![Στιγμιότυπο οθόνης (8)](https://user-images.githubusercontent.com/1429524/77849768-b3b2c900-71d6-11ea-94e9-791e82b779ad.png)

**Comment by ridsama** [comment]
To show what it's supposed to happen on a Switch: [Youtube](https://youtu.be/VfSoGmxuhC0?t=502)
