### ISSUE TITLE
LB and LS are not working on the undocked right controller

### ISSUE THREAD

**Issue by Dovydasr** [yuzu-emu/yuzu#3281]
Tried to play Snipperclips plus, but LB and LS are not working on the undocked right controller. Tried rebinding the keys to something else, same issue.

**Comment by aidolov23** [comment]
> Tried to play Snipperclips plus, but LB and LS are not working on the undocked right controller. Tried rebinding the keys to something else, same issue.

I have same problem. But I found solution. If set for Player 1 "Single Left Joycon" and fo Player 2 too "Single Left Joycon", then SL and SR buttons work properly for two players in the game "Snipperclips"
