### ISSUE TITLE
Mods with exeFS folder structure don't get recognized in Linux

### ISSUE THREAD

**Issue by Gustav0ar** [yuzu-emu/yuzu#3285]
I'm having trouble adding mods to Super Mario Odyssey with exeFS folder structure in yuzu, latest mainline compiled from source in linux. Yuzu just doesn't recognize mods with that folder structure

![image](https://user-images.githubusercontent.com/628398/72035101-aa6c2d00-3275-11ea-802f-ba3b26604448.png)

The ones that show up has "romfs" folder structure, but the ones with exeFS don't
Tried restarting, keeping only a mod with exeFS, reseting metadata cache but nothing seems to help.

![image](https://cdn.discordapp.com/attachments/400106910231035904/664667493863784474/unknown.png)

Example of a mod that doesn't show up:
https://cdn.discordapp.com/attachments/453495401199304705/664664481250541578/Disable-Dynamic-Resolution-Switching.7z

My system information:
![image](https://i.imgur.com/JKvO2x3.png)

**Comment by ReaperOfSouls1909** [comment]
it affects yuzu as a whole on all distro's

**Comment by DarkLordZach** [comment]
Linux is typically used with a case-sensitive, in contrast to windows. Yuzu only looks for an exact folder named `exefs` (all lowercase). In the pictures in discord and that mod 7zip, the FS is capital so it is not the same folder.

Please try renaming to `exefs` and report back.

**Comment by Gustav0ar** [comment]
It works!!! Thanks DarkLord!!!!!

**Comment by ReaperOfSouls1909** [comment]
Wicked will try tomorrow

**Comment by Gustav0ar** [comment]
I guess I'll close the issue since it's sorted out. The devs can reopen if they plan to change the app to make case insensitive in linux.
