### ISSUE TITLE
Kirby Star Allies crash upon rendering the title screen using Vulkan

### ISSUE THREAD

**Issue by scoofz** [yuzu-emu/yuzu#3289]
Hello there, 

Kirby star allies works with Opengl but completely crashes on the game menu using Vulkan, I have an AMD card so i'd really appreciate Vulkan support on this :) . I have no idea how to provide a log, so if you can point me in the right direction, I'd gladly provide one. 

Thank you

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by scoofz** [comment]
And? 

I'm not asking for support, I know what to look for in terms of compatibility, other users reported the same thing on YT and reddit, I'm reporting a problem that anyone can easily reproduce that's all. 

I was asking for direction for logs in case you wanted one. 

I also don't demand for the game to work, I know I'm a patreon for an experimental emulator, I don't expect it to work perfectly with every game...

**Comment by Yvar192** [comment]
This tells you how to get a log: https://yuzu-emu.org/help/reference/log-files/

And yeah, opening issues for actual issues is what they're supposed for, aren't they

**Comment by scoofz** [comment]
Thank you Yvar192 

So here is the full log of the crash : https://pastebin.com/KmFYGhEi

We can see at the end when Yuzu crashes : 

[ 163.929131] Debug <Critical> video_core\shader\decode\conversion.cpp:DecodeConversion:93: Assertion Failed! Unimplemented code!
[ 163.929885] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:GetGraphicsPipeline:224: Compile 0x76A9E15588B44898
[ 163.931094] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:RequestUpdateImpl:95: (STUBBED) called
[ 163.932146] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:RequestUpdateImpl:95: (STUBBED) called
[ 163.935612] Debug <Critical> video_core\renderer_vulkan\maxwell_to_vk.cpp:VertexFormat:398: Assertion Failed! Unimplemented vertex format of type=4 and size=1

**Comment by Hexagon12** [comment]
I'm sorry for closing this issue. I see that we currently have other Vulkan related issues open.

Reopening this issue...

**Comment by theboy181** [comment]
Close?

**Comment by ReinUsesLisp** [comment]
Fixed by #3435. Closing.
