### ISSUE TITLE
Input Lag

### ISSUE THREAD

**Issue by turkeynaruto** [yuzu-emu/yuzu#3291]
The time Yuzu needs to realize I give an Input is too high. 
In Mario Odyssey noticable when changing the running direction of Mario. 
I added 2 Videos showing Pokemon Sword at 0,25x Speed with 36FPS on Yuzu and 32-37FPS on Ryujinx. 
In the beginning when I go left you can see it the best how directly the Character reacts compared to Yuzu. 
This aint a big "Issue" of Yuzu but just wanted to say it so you know it if you didnt.

Yuzu 128 Mainline
i5 8600K@4.9/16GB Ram/GTX 1660Ti 

EDIT: New Video of Mario Odyseey both Emulators at 60FPS Heavy Slowmotion: 
![ezgif-7-1e6cceb5f8ab](https://user-images.githubusercontent.com/18088164/73799947-ade0ce80-47b7-11ea-8185-03720395250b.gif)

Yuzu
![Yuzu Pokemon Input](https://user-images.githubusercontent.com/18088164/72204511-339f8180-3479-11ea-9dd9-d7d440eb2335.gif)

Ryu
![Ryujinx Pokemon Input](https://user-images.githubusercontent.com/18088164/72204512-3601db80-3479-11ea-9430-d130d1e4644d.gif)

The GIF have low FPS here are Links to the Original Videos: 
https://streamable.com/3nrd7
https://streamable.com/eqv9y
https://streamable.com/f8gdj

**Comment by ChocoChopin** [comment]
I'm guessing this is a problem with this individual user's configuration. I'm very sensitive to input lag, and Yuzu feels like it adds one or two frames at the most relative to an actual Switch, which is entirely acceptable for emulation.

**Comment by turkeynaruto** [comment]
> 
> 
> I'm guessing this is a problem with this individual user's configuration. I'm very sensitive to input lag, and Yuzu feels like it adds one or two frames at the most relative to an actual Switch, which is entirely acceptable for emulation. Yuzu's relatively _low_ input lag consistently impresses me.

This is not normal Input Lag I feel like its only the change of directions the player moves (I also tested it with Keyboard still the same). 
I took Pokemon Sword as example because Ryujinx coulndt get enough FPS for a real comparison in Mario Odyseey. but you can see it WAY better in Mario. 
Run in a square "Up, left, down, right" all the time and I feel like someone else is playing the game BUT when I press A to jump its almost no lag.
