### ISSUE TITLE
Development blog

### ISSUE THREAD

**Issue by lenormf** [yuzu-emu/yuzu#33]
Hi,

Do you plan on setting up and maintaining a development blog?

Other emulators such as [dolphin](https://dolphin-emu.org/) or [rpcs3](https://rpcs3.net/) have greatly benefited from that approach exposure-wise, and it's also generally interesting to read about emulation on a monthly basis.

Thanks.

**Comment by RavenHome1** [comment]
well the same people who are writing for citra might become interested in writing for yuzu, it is up to them. but currently there is not much to write about since the emulator still in very early stages.

**Comment by lenormf** [comment]
Sure, there might not be anything to write about now, but if the intent to setup a blog is made public as soon as that changes, it might encourage people (such as myself, only interested in the technical bits) to come back/stick around.

**Comment by chris062689** [comment]
We already have a website setup for the ability for a blog, but we've had issues getting writers onboard in the past. We'll probably just stick with tweets for now. 
https://yuzu-emu.org

**Comment by Gamedev1909** [comment]
Best I could do is a video blog if that helps

**Comment by yawuvo** [comment]
I can try for technical blog :)

**Comment by bunnei** [comment]
Noted! We will probably blog in the future. Going to close this, since it's not an emulator issue.
