### ISSUE TITLE
[Linux] Vulkan option unavailable in yuzu-mainline

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#3315]
As of yuzu-mainline commit e041f33569b887bfea757740be9474f3fe5b079f, vulkan option is unavailable in graphics settings.  Note that it hasn't been available in any previous builds tested since vulkan was introduced.

Test system is linux mint 19.3 with kernel 5, using Nvidia gtx 1070m with driver 440.48.  Yuzu mainline compiled using gcc 9.2.1.

**Comment by BSoDGamingYT** [comment]
Vulkan is currently only available in the Early Access branch. Please have patience and wait for it to be merged into master/mainline. 

This issue tracker is not the place for this kind of problem

**Comment by Shoegzer** [comment]
Ah, got it.  Wasn't tracking the project closely enough but since there were vulkan-related commits such as the one in my original message above, figured it had been incorporated into master/mainline.  Thanks for the update!
