### ISSUE TITLE
Posible Ram leak SMO yuzu EA 132

### ISSUE THREAD

**Issue by Ghostotakoi** [yuzu-emu/yuzu#3331]
I was playing SMO in OGL render for around 10 min and my ram is almost full, this should be some kind of ram leak. 
![ScreenShot_20200119211806](https://user-images.githubusercontent.com/20958581/72695697-7b707980-3b07-11ea-8034-4a53da54eb29.png)

A few minutes later it crash and my monitor go completely black, after a few moments waiting my 1st monitor came back but my 2nd monitor kept black, this is what yuzu error message shown.

![ScreenShot_20200119212202](https://user-images.githubusercontent.com/20958581/72695710-83301e00-3b07-11ea-927a-ad0ffa16cf98.png)

I had to reboot my entire system in order to recover the 2nd monitor output. 
My specs
I7-6700 3.4ghz ~ 3.8ghz
16GB RAM
Gigabyte Windforce GTX 1060 6GB driver ver. 441.66

**Comment by Luffykun007** [comment]
Yes, I also had this same problem here, my pc crashed and the emulation ended.
