### ISSUE TITLE
Possible to add GameProfile Settings -> Controller Settings

### ISSUE THREAD

**Issue by xsasx** [yuzu-emu/yuzu#3333]
Hi,

is it possible to add something like in CEMU. That you can do special configurations for any game differently like in CEMU ?

Cause wanna use Launchbox to start my games- problem is that for different games i must set different controller settings. for example:

Pokemon

Custom Preset option in Emulation > Configure > Controls and Map/Use ONLY the Joycons Docked Controller Do not enable Docked Mode.

Zelda
Controller Configuration: Single Player - Dual Joycons - Docked

So if I set it up for pokemon and start Zelda via launchbox - i cant play it cause of the wrong controller settings...

Would be great to set it different per game.

Thanks

**Comment by BSoDGamingYT** [comment]
This is an issue thread for existing code, not an area for feature requests.
