### ISSUE TITLE
RetroArch fails to boot due to bsd:u Write function not being implemented

### ISSUE THREAD

**Issue by qeeg** [yuzu-emu/yuzu#3335]
Version: yuzu Early Access 139
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4091867/yuzu_log.txt)

**Comment by ReaperOfSouls1909** [comment]
thats a network service and won't be added anytime soon but if you wait long enough retroarch will boot or should

**Comment by MoochMcGee** [comment]
Why shouldn't it be added? Network access is a function of the Nintendo Switch too

**Comment by liamwhite** [comment]
Present as of https://github.com/yuzu-emu/yuzu/commit/f7d59f3e0e63a33e758b92a857ca4add0a8ee524
