### ISSUE TITLE
Texture Format: G8R24 unimplemented Luigi's Mansion 3 v1.2.0

### ISSUE THREAD

**Issue by CJBok** [yuzu-emu/yuzu#3342]
Following log is spammed in Luigi's Mansion 3 V1.2.0

`Debug <Critical> video_core\texture_cache\format_lookup_table.cpp:GetPixelFormat:182: Assertion Failed! texture format=14 srgb=false components={4 2 2 2}`

Usefull for GPU Project?

**Comment by FernandoS27** [comment]
Sadly there's no Vulkan/OpenGL equivalent. It needs to be converted by hand.

**Comment by Morph1984** [comment]
@CJBok This is G24R8, not G8R24

**Comment by Morph1984** [comment]
#3020 related

**Comment by MysticExile** [comment]
Fixed by #4005
