### ISSUE TITLE
Virus in Yuzu Download

### ISSUE THREAD

**Issue by Devilishness** [yuzu-emu/yuzu#3367]
I've downloaded what should be the latest version of Yuzu for the first time tonight and as soon as it finished installing my Avast immediately blocked and quarantined it for containing a virus called IDP. Generic. 

Screen capture of it in my Avast Virus Chest:

![Capture](https://user-images.githubusercontent.com/60534645/73587800-245a9500-4475-11ea-937d-b394c5c12658.PNG)

Though shortcuts remain in my start menu I can't open the software. It errors out because of the quarantined download file. 

I'm using a Lenevo Flex 14 laptop with Windows 10. 

It's just as well, however, since apparently Pokemon Shield is entirely unplayable.

**Comment by goldenx86** [comment]
Check the files with https://www.virustotal.com/gui/home/upload
We get false positives with Avast.

**Comment by Devilishness** [comment]
> Check the files with https://www.virustotal.com/gui/home/upload
> We get false positives with Avast.

Thank you. 
It came back clean in that link. 
I've restored the file from the vault and can open the software but I'm now getting the following message:
![Capture2](https://user-images.githubusercontent.com/60534645/73588103-bebcd780-4479-11ea-9505-f1bd36a60079.PNG)
I don't even understand what it means. Is it something I should be concerned about?

**Comment by bunnei** [comment]
Please see https://yuzu-emu.org/help/quickstart/ for details on setting up yuzu
