### ISSUE TITLE
Link's Awakening - nearly all sound effects missing

### ISSUE THREAD

**Issue by ChocoChopin** [yuzu-emu/yuzu#3368]
Using latest early access version of Yuzu at time of writing, 168. This appears to be a known issue since it's mentioned on the game's compatibility page, but I was unable to find an entry for it here. In Link's Awakening, nearly all sound effects are missing, with the exception of several character voices. The music tracks all sound to work properly. This issue can be observed in many YouTube playthroughs of LA in Yuzu, and it appears unchanged even in the latest release. https://youtu.be/RCLMulpACLg

**Comment by ChocoChopin** [comment]
There doesn't appear to be a way for me to add a label to this issue. If I'm missing something, please let me know.

**Comment by hammer300** [comment]
I was just going to add this.  hopefully maybe it can be fixed.

**Comment by ChocoChopin** [comment]
It appears that this issue has been resolved with the latest sound engine rewrite. Apparently, some sound effects are still a little too quiet, but that's very minor by comparison, and it's a problem that seems to occur in other games as well.
