### ISSUE TITLE
Logitech HOTAS. X52

### ISSUE THREAD

**Issue by CoryNull** [yuzu-emu/yuzu#3373]
I play games that sometimes use a flight stick. Leaving the X52 connected while trying to edit the config causes the program to crash with a "corrupted double-linked list" and segmentation faults according to GDB. Yuzu should blacklist controllers or look to see if the controller is a gamepad and not a controller with 32+ buttons and several axis inputs. This confused me for an hour. 

It happens in the latest git built version. (157eb37)

Connecting any controller with an excessive amount of inputs should reproduce the issue.

Systems specs irrelevant, however I'm on Linux (Ubuntu Budgie 18.04.4 LTS).

Logs, files, and other info probably not required.

I'd patch it for you guys but I'm still unfamiliar with the project but I think I could eventually figure it out. Hope this helps someone else who's probably a little frustrated trying to get this to work. :)

**Comment by CoryNull** [comment]
Segmentation faults even if I disconnect the controller... I jumped the gun writing an issue. My apologizes. I will look more into the issue and see if I can't fix it myself, otherwise I will open a new issue later with the proper info and details.

**Comment by Yvar192** [comment]
https://github.com/yuzu-emu/yuzu/issues/2957 could be this?
