### ISSUE TITLE
Yuzu Vulkan closing itself

### ISSUE THREAD

**Issue by lendor928** [yuzu-emu/yuzu#3380]
Yuzu Vulkan closing itself, any help please [:)]

LOG:
[   0.735238] Input <Info> input_common\udp\client.cpp:StartCommunication:197: Starting communication with UDP input server on 127.0.0.1:26760
[   0.778040] Frontend <Info> yuzu\main.cpp:GMainWindow:210: yuzu Version:  | HEAD-mainline-636-1024-ge17216f82
[   0.778053] Frontend <Info> yuzu\main.cpp:GMainWindow:212: Host CPU: AMD Ryzen 5 1600 Six-Core Processor            
[   0.778122] Frontend <Info> yuzu\main.cpp:GMainWindow:214: Host OS: Windows 10 (10.0)
[   0.858947] Config <Info> core\settings.cpp:LogSettings:84: yuzu Configuration:
[   0.858955] Config <Info> core\settings.cpp:LogSetting:80: System_UseDockedMode: true
[   0.858956] Config <Info> core\settings.cpp:LogSetting:80: System_RngSeed: 0
[   0.858958] Config <Info> core\settings.cpp:LogSetting:80: System_CurrentUser: 1
[   0.858959] Config <Info> core\settings.cpp:LogSetting:80: System_LanguageIndex: 1
[   0.858960] Config <Info> core\settings.cpp:LogSetting:80: Core_UseMultiCore: false
[   0.858972] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseResolutionFactor: 0.0
[   0.858973] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseFrameLimit: true
[   0.858974] Config <Info> core\settings.cpp:LogSetting:80: Renderer_FrameLimit: 100
[   0.858975] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseDiskShaderCache: true
[   0.858976] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseAccurateGpuEmulation: false
[   0.858980] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseAsynchronousGpuEmulation: true
[   0.858981] Config <Info> core\settings.cpp:LogSetting:80: Audio_OutputEngine: auto
[   0.858982] Config <Info> core\settings.cpp:LogSetting:80: Audio_EnableAudioStretching: true
[   0.858982] Config <Info> core\settings.cpp:LogSetting:80: Audio_OutputDevice: auto
[   0.858983] Config <Info> core\settings.cpp:LogSetting:80: DataStorage_UseVirtualSd: true
[   0.858986] Config <Info> core\settings.cpp:LogSetting:80: DataStorage_NandDir: C:\Users\ddfs\AppData\Roaming/yuzu/nand/
[   0.858987] Config <Info> core\settings.cpp:LogSetting:80: DataStorage_SdmcDir: C:\Users\ddfs\AppData\Roaming/yuzu/sdmc/
[   0.858988] Config <Info> core\settings.cpp:LogSetting:80: Debugging_UseGdbstub: false
[   0.858989] Config <Info> core\settings.cpp:LogSetting:80: Debugging_GdbstubPort: 0
[   0.858990] Config <Info> core\settings.cpp:LogSetting:80: Debugging_ProgramArgs: 
[   0.858991] Config <Info> core\settings.cpp:LogSetting:80: Services_BCATBackend: boxcat
[   0.858992] Config <Info> core\settings.cpp:LogSetting:80: Services_BCATBoxcatLocal: false
[  20.230687] Config <Info> core\settings.cpp:LogSettings:84: yuzu Configuration:
[  20.230694] Config <Info> core\settings.cpp:LogSetting:80: System_UseDockedMode: true
[  20.230696] Config <Info> core\settings.cpp:LogSetting:80: System_RngSeed: 0
[  20.230697] Config <Info> core\settings.cpp:LogSetting:80: System_CurrentUser: 1
[  20.230698] Config <Info> core\settings.cpp:LogSetting:80: System_LanguageIndex: 1
[  20.230698] Config <Info> core\settings.cpp:LogSetting:80: Core_UseMultiCore: false
[  20.230701] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseResolutionFactor: 0.0
[  20.230702] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseFrameLimit: true
[  20.230703] Config <Info> core\settings.cpp:LogSetting:80: Renderer_FrameLimit: 100
[  20.230704] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseDiskShaderCache: false
[  20.230704] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseAccurateGpuEmulation: true
[  20.230705] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseAsynchronousGpuEmulation: true
[  20.230706] Config <Info> core\settings.cpp:LogSetting:80: Audio_OutputEngine: auto
[  20.230707] Config <Info> core\settings.cpp:LogSetting:80: Audio_EnableAudioStretching: true
[  20.230709] Config <Info> core\settings.cpp:LogSetting:80: Audio_OutputDevice: auto
[  20.230709] Config <Info> core\settings.cpp:LogSetting:80: DataStorage_UseVirtualSd: true
[  20.230710] Config <Info> core\settings.cpp:LogSetting:80: DataStorage_NandDir: C:\Users\ddfs\AppData\Roaming/yuzu/nand/
[  20.230711] Config <Info> core\settings.cpp:LogSetting:80: DataStorage_SdmcDir: C:\Users\ddfs\AppData\Roaming/yuzu/sdmc/
[  20.230712] Config <Info> core\settings.cpp:LogSetting:80: Debugging_UseGdbstub: false
[  20.230713] Config <Info> core\settings.cpp:LogSetting:80: Debugging_GdbstubPort: 0
[  20.230714] Config <Info> core\settings.cpp:LogSetting:80: Debugging_ProgramArgs: 
[  20.230714] Config <Info> core\settings.cpp:LogSetting:80: Services_BCATBackend: boxcat
[  20.230715] Config <Info> core\settings.cpp:LogSetting:80: Services_BCATBoxcatLocal: false
[  24.103318] Frontend <Info> yuzu\main.cpp:BootGame:977: yuzu starting...
[  24.195868] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontStandard' (0x0100000000000811).
[  24.196513] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[  24.196758] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[  24.197746] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[  24.197881] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[  24.198149] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[  24.198431] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontChineseTraditional' (0x0100000000000813).
[  24.198755] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[  24.198888] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontKorean' (0x0100000000000812).
[  24.199147] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[  24.199282] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[  24.199301] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[  24.199309] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[  24.199319] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[  24.199604] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[  24.199635] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[  24.199791] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[  24.199805] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[  24.201070] Render.Vulkan <Info> video_core\renderer_vulkan\vk_device.cpp:Create:125: Device doesn't support float16 natively
[  24.201073] Render.Vulkan <Info> video_core\renderer_vulkan\vk_device.cpp:Create:133: Device doesn't support packed UBOs
[  24.201074] Render.Vulkan <Info> video_core\renderer_vulkan\vk_device.cpp:Create:141: Device doesn't support uint8 indexes
[  24.278107] Render.Vulkan <Info> video_core\renderer_vulkan\renderer

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our forums or our Discord for support requests.

Thanks.
