### ISSUE TITLE
No headbar icon on Linux mailline builds

### ISSUE THREAD

**Issue by TotalCaesar659** [yuzu-emu/yuzu#3384]
There is no headbar icon on Linux [mailline builds](https://yuzu-emu.org/downloads/), despite I've [fixed](https://github.com/yuzu-emu/yuzu/pull/3316) this a long time ago.
![1](https://user-images.githubusercontent.com/14265316/73988123-ce915b80-4952-11ea-9b83-bd984197074d.png)

**Comment by soredake** [comment]
No progress on this?

**Comment by TotalCaesar659** [comment]
No, same result on latest mailline build.
![1](https://user-images.githubusercontent.com/14265316/98482324-bd42eb80-2211-11eb-8f14-2757a61e3d99.png)

**Comment by MC-The-Pro** [comment]
this PR https://github.com/yuzu-emu/yuzu/pull/5274 seems to fix it.

**Comment by german77** [comment]
Latest build is fine
