### ISSUE TITLE
Error while initialising OpneGL 4.3

### ISSUE THREAD

**Issue by BogdanTheGeek** [yuzu-emu/yuzu#3390]
Hi, I have been trying to run Yuzu on Manjaro (i know its not supported but Linux is Linux) for a few days now. I have compiled from the latest git mainline and master, aur packages, tried the bin files posted on the website and in all I get the same error while trying to launch SMO.
Error while initialising OpneGL 4.3 on OpenGL
and in Vulkan it fills up the all of my 8Gb of ram and half of my swap and then freezes.

These are my specs and drivers I am using:
$ inxi -G                                                          
Graphics:
  Device-1: Intel UHD Graphics 630 driver: i915 v: kernel 
  Device-2: NVIDIA driver: nvidia v: 440.59 
  Display: x11 server: X.org 1.20.7 driver: nvidia 
  resolution: <xdpyinfo missing> 
  OpenGL: renderer: GeForce GTX 1650/PCIe/SSE2 v: 4.6.0 NVIDIA 440.59
In case it matteres I am running an i5 9300H CPU on The latest Manjaro with all of the shared libraries from the build documentation installed

I have tried Yuzu before on a windows machine with 8Gb of ram and had no issue(appart from the expeted poor performance)

The output of  ./yuzu is:
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: custom style sheet is disabled
QObject::connect(QWindow, GRenderWindow): invalid nullptr parameter
QObject::connect(QWindow, GRenderWindow): invalid nullptr parameter

On build d0d76d097 it also gives a segmentation fault when trying ot acces the config menu
I have attached the core dump

[core.yuzu.zip](https://github.com/yuzu-emu/yuzu/files/4175093/core.yuzu.zip)

Edit1:
I have tested the windows build with wine and it does work with opengl.

**Comment by bukyapavankumar** [comment]
Runs fine for me on popos19.10 with Intel hd 5500 8gb ram

**Comment by bukyapavankumar** [comment]
Have you tried compiled builds?

**Comment by BogdanTheGeek** [comment]
> Have you tried compiled builds?

Yes, the coredump is from the latest mainline build

**Comment by bukyapavankumar** [comment]
Compiled in optimised mode and run .

**Comment by BogdanTheGeek** [comment]
> Compile in optimised mode and run .

could you please link or paste the arguments to build in optimised mode

**Comment by BogdanTheGeek** [comment]
> Compile in optimised mode and run .

Do you mean -O2 argument for make?

**Comment by Sansyyxd** [comment]
yuzu supports 4.5 not 4.3 gl

**Comment by BogdanTheGeek** [comment]
> yuzu supports 4.5 not 4.3 gl

My GPU has support for OpenGL 4.6 and the drivers are the latest. This is interesting as the error might come from an unexpected place.

**Comment by BogdanTheGeek** [comment]
I've just pulled the latest commits in mainline and recompiled YUZU in release mode and I can now load into games with Vulkan, opengl gives the same error.
Here is something weird though, the renderer seems to be transparent
![Screenshot from 2020-02-09 18-42-15](https://user-images.githubusercontent.com/8824186/74106086-3ec6f980-4b6c-11ea-97cd-d1942f844852.png)
![Screenshot from 2020-02-09 18-42-22](https://user-images.githubusercontent.com/8824186/74106091-46869e00-4b6c-11ea-90ec-422d189c7f7f.png)

**Comment by BogdanTheGeek** [comment]
Any ideas? I know there are a lot of commits every day and they might fix the issue, but i would still appreciate some constructive debugging methods.

**Comment by dnmodder** [comment]
i have the same error in arch linux

**Comment by BogdanTheGeek** [comment]
Could this be because of Xorg? I think Ubuntu still uses Wayland.

**Comment by dnmodder** [comment]
Now it's working, I guess they fixed it

**Comment by BogdanTheGeek** [comment]
Indeed, opengl now seems to render fine, but Vulkan still has the same issue. ill close this issue and open a new one.

**Comment by BogdanTheGeek** [comment]
The new issue regarding vulkan is here : https://github.com/yuzu-emu/yuzu/issues/3476
