### ISSUE TITLE
Control input not working properly through remote play

### ISSUE THREAD

**Issue by Rayken** [yuzu-emu/yuzu#3392]
**Yuzu version**: 160 (a952fbc5b385fb133ad7534c8defc128878bb1dc)

When launching a game or yuzu.exe through Steam (added as a non-steam game) for remote play (Steam Link) and trying to configure a controller (Steam Controller in this case), xInput seems to fail. So "A" is 'return' and "B" is 'space' etc. Instead of A being A, B being B, etc. This does not happen in CEMU though.

So in CEMU, same approach. And to setup controllers, I pause the game, go to input settings and configure the controller as any other controller and it recognizes the inputs. However, in Yuzu this unfortunately doesn't work.

Is there a workaround for us remote players?

**Comment by BSoDGamingYT** [comment]
This is not a legitimate issue with yuzus codebase. Please do not open such issues like this here. If you need assistance with such problems, use the yuzu discord server

**Comment by DarkLordZach** [comment]
^^ Previous comment

Also yuzu doesn't use XInput for joypads, we use SDL2 (which for a steam controller would just use mouse/keyboard directinput anyway).
