### ISSUE TITLE
problem running a game through yuzu-cmd.exe(Yuzu160)

### ISSUE THREAD

**Issue by Amin-Shiravand** [yuzu-emu/yuzu#3394]
all of the prerequisites set for yuzu and running a game through yuzu is work fine, but when I want to run a game using yuzu-cmd.exe below message appears but nothing happens

"yuzu-cmd.exe "C:\PKG\M__S[010002C00C270000][v0].nsp"
[   0.014216] Common.Filesystem <Debug> common\file_util.cpp:CreateFullPath:199: path exists C:\Users\a.shiravand\AppData\Roaming/yuzu/log/
[   0.139017] Input <Info> input_common\udp\client.cpp:StartCommunication:197: Starting communication with UDP input server on :26760"

also the yuzu_log.txt log file at 
"C:\Users\|%User%\AppData\Roaming\yuzu\log" 
is empty.

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
