### ISSUE TITLE
Build fails due to missing SDL.h

### ISSUE THREAD

**Issue by mark2185** [yuzu-emu/yuzu#3426]
Building fails after commit https://github.com/yuzu-emu/yuzu/commit/68043dd2337feab0b0ccc9868cd535b2254335ea, even though I have SDL2 installed, and the find_package(SDL2 REQUIRED) in `CMakeLists.txt:159` sets `SDL2_FOUND` to `1`

`gcc` build, tried it on a new clone, fails on every commit after the one mentioned above, same error.

**Comment by brianclinkenbeard** [comment]
Operating system? Are you using the latest version of SDL2?

**Comment by mark2185** [comment]
**OS:** Arch, 5.5.3-arch1-1, **SDL** 2.0.10
I used `ninja` instead of `make`.

Logs:
[cmake_log.txt](https://github.com/yuzu-emu/yuzu/files/4210302/cmake_log.txt)
[ninja.log](https://github.com/yuzu-emu/yuzu/files/4210303/ninja.log)

**Comment by brianclinkenbeard** [comment]
Can you try adding the following after line 159 in `CMakeLists.txt`:
```
if("${SDL2_LIBRARIES}" STREQUAL "")
    message(WARNING "SDL2_LIBRARIES wasn't set, manually setting to SDL2::SDL2")
    set(SDL2_LIBRARIES "SDL2::SDL2")
endif()
```

**Comment by mark2185** [comment]
That seems to have done it. Now the linker fails regarding to the unicorn. In the meantime I tried going even further than the commit mentioned in my first post, and it seems to be the same error. I checked the submodules, they're all up to date.
[linker_error.log](https://github.com/yuzu-emu/yuzu/files/4210472/linker_error.log)

**Comment by ReaperOfSouls1909** [comment]
Install python2 sudo pacman -S python2

**Comment by mark2185** [comment]
> Install python2 sudo pacman -S python2
Already installed, as well as python3.

**Comment by Joey11904** [comment]
brian's suggested fix didn't work for me. it gave me an error when running cmake

**Comment by Joey11904** [comment]
i tried compiling with that modified CMakeLists.txt file but still the same SDL error
[compile-log.txt](https://github.com/yuzu-emu/yuzu/files/4213900/compile-log.txt)

here's my modified cmakelists.txt (maybe i edited it the wrong way?)
[CMakeLists.txt](https://github.com/yuzu-emu/yuzu/files/4213907/CMakeLists.txt)

**Comment by brianclinkenbeard** [comment]
@Joey11904 It looks like you are on an older commit that uses `FindSDL2.cmake`, try on the latest revision and use the same fix if it doesn't work.
