### ISSUE TITLE
Having mods inside the mod folder causes Yuzu to exhibit strange behaviour in multiple games even when the mod is disabled

### ISSUE THREAD

**Issue by swablueme** [yuzu-emu/yuzu#3427]
Even though a mod is disabled, it may cause strange problems in games that only deleting all contents in the mod folder may remedy.
**Affects:** Latest mainline (yuzu 167)
**OS:** Windows 10/1050 ti Nvidia

For example, in Pokemon Sword and Shield:
- I had a completely empty cheat code file inside a folder and the mod was disabled (marked as D in the emulator)
- The weather always stayed the same no matter what
- After deleting the contents of the mod folder, the weather changed back to normal

For example, in Fire Emblem: Three Houses 1.2.0 with Wave 4 DLC
-  I had a cheat code file inside a folder and the mod was disabled (marked as D in the emulator)
- I became completely unable to talk to characters (empty dialogue) inside the Abyss and inside the Cindered Shadows side story. I was also unable to recruit DLC characters
- After deleting the contents of the mod folder, I was then able to talk to characters and to interact with them.

**Comment by BSoDGamingYT** [comment]
Can confirm Pokemon issues...If a mod file is present in the mod directories of pokemon sword or shield, the weather systems in the game do not work or render

Example with files or mods in mod directory
![with files in mod folder](https://user-images.githubusercontent.com/38402209/76482571-cf675280-6414-11ea-8d2e-0921e3bcdf56.PNG)

With no files or mods in the mod directory
![with no mods in folder](https://user-images.githubusercontent.com/38402209/76482708-3f75d880-6415-11ea-92d2-5d5283b62fa2.PNG)

**Comment by gguga12** [comment]
>     * I became completely unable to talk to characters (empty dialogue) inside the Abyss and inside the Cindered Shadows side story. I was also unable to recruit DLC characters
How did you install Cindered Shadows? most of my dlcs are missing in Three Houses

**Comment by swablueme** [comment]
@gguga12
Your game updates and dlcs are saved to C:\Users\USERNAME\AppData\Roaming\yuzu\nand\user\Contents\registered. To perform a clean update (as people have reported that the game fails to correctly update if you merely just try and update without first wiping anything), you may need to wipe the whole folder and then reinstall all the new versions of the DLC and install the 1.2.0 update (hopefully you have not downloaded/updated other games and if so you have hopefully backed up the updates/dlcs or recorded the folder names so that you may only wipe out Fire Emblem DLC/Updates). 

All DLC must be wave 4 in addition to CS! If you have 3 wave 3 dlc and cindered shadows it will never show up. https://www.reddit.com/r/fireemblem/comments/f33drb/side_story_option_not_appearing_in_main_menu/

**Comment by gguga12** [comment]
@swablueme 
Thanks man, i hope one day they fix it so we can have all the wave 3dlcs along cindered shadows

**Comment by swablueme** [comment]
Fixed

**Comment by andrewmyles2** [comment]
Has this been fixed, though? because I'm using EA 591 and I have exactly the same problem as described above. I use BSoD gaming's texture pack mod. With the mod, no weathers. Without, instantly weathers appear again.
