### ISSUE TITLE
Audio distortion in several games

### ISSUE THREAD

**Issue by slashiee** [yuzu-emu/yuzu#3428]
Several games such as A Hat in Time and Hatsune Miku Project DIVA MEGA39's suffer from distortion in their audio playback. This issue is based around yuzu mainline 167.

A Hat in Time:
[Switch output](https://drive.google.com/open?id=1erKUCpiD8NMvq8SNePatTwe5HPG1GOBN)
[yuzu output](https://drive.google.com/open?id=1o1lIoOL2Qi8w2GLXeVXvqqDkmhWWTZE_)

MEGA39s:
[Switch output](https://drive.google.com/open?id=1e4pHiMlabCLiCT81trWPoUTukpZJweg-)
[yuzu output](https://drive.google.com/open?id=1FzLf7i8VZ4CYnLZk6SGBWResAP7nj4ej)

**Comment by slashiee** [comment]
- Happens in Diablo 3
- Happens in Toki Tori

**Comment by FearlessTobi** [comment]
All those games seem to be using audren.

**Comment by Ghostotakoi** [comment]
hope this can be fixed soon
