### ISSUE TITLE
Broken Cutscene Audio on Luigis Mansion 3

### ISSUE THREAD

**Issue by BSoDGamingYT** [yuzu-emu/yuzu#3445]
Currently, all cutscenes in LM3 on yuzu have broken audio (Mostly character voices). You can see examples of yuzu/Switch audio below. 

Yuzu
https://streamable.com/u6g5q

Switch
https://streamable.com/vnfaj

**Comment by FearlessTobi** [comment]
For reference, the game uses audout.

**Comment by MysticExile** [comment]
Fixed by Apollo
