### ISSUE TITLE
Anisotropic filtering hack

### ISSUE THREAD

**Issue by Margen67** [yuzu-emu/yuzu#3447]
Unlike Dolphin and various other emulators, yuzu lacks an option to force Anisotropic filtering, which would improve texture fidelity, especially in games like Pokemon SwSh.

I recently discovered you can do this by changing
`return static_cast<float>(1U << max_anisotropy);` to
`return static_cast<float>(16U << max_anisotropy);` at [src/video_core/textures/texture.h#L331](https://github.com/yuzu-emu/yuzu/blob/master/src/video_core/textures/texture.h#L331).

## Screenshots:
<details><summary>AF off (click to expand)</summary>

![Off](https://cdn.discordapp.com/attachments/472575665334648833/680879846334660613/noaf.png)
</details>
<details><summary>AF on (click to expand)</summary>

![On](https://cdn.discordapp.com/attachments/472575665334648833/680879786590994461/af.png)
</details>

**Comment by ReaperOfSouls1909** [comment]
after testing, if this causes any issues with games I can say it's a great idea to add as a graphics option maybe choose between 2-16x and a button to turn it on

**Comment by ReaperOfSouls1909** [comment]
![image](https://user-images.githubusercontent.com/18043258/75116729-a9366a00-5641-11ea-8ee1-3994bc15c809.png)
look at the detail in the distance
