### ISSUE TITLE
Repeating sound effects in several games

### ISSUE THREAD

**Issue by slashiee** [yuzu-emu/yuzu#3449]
In Hatsune Miku Project DIVA MEGA39s and Usotsuki Hime, the audio will keep repeating sound effects over and over and will sometimes turn into garbage data.

[MEGA39s Samples](https://drive.google.com/open?id=1Mp-MQqAjLBKvTZPOsAgMhtlcZbs2OU7A)

**Comment by nevespt** [comment]
no idea of whats is causing this issue?

**Comment by slashiee** [comment]
Fixed with #4310
