### ISSUE TITLE
Xbox One controller buttons lose sensibility after ZL or ZR

### ISSUE THREAD

**Issue by Blaztix** [yuzu-emu/yuzu#3450]
I try play Super Mario Maker 2 (2.0.0) and I can't do a little jump (Press B a little) after using ZL or ZR.

In the minimal time pressed, Mario make a full jump.

![image](https://user-images.githubusercontent.com/4962591/75120651-c5e79780-566b-11ea-87b5-60f67d0cf6d7.png)

If I go to the configuration, and "edit" and accept it (without changes), I can a "little jump" again, until I press ZL or ZR again.

**Comment by GodKratos** [comment]
I have the same issue. Just tried playing SMO (which has been working perfectly fine previously) and as soon as you press ZL or ZR the rest of the controls stop functioning.

If however you hold ZL or ZR the other buttons will work again. I thought it might be related to the reversed ZL/ZR bug but it doesn't appear to be the same issue as the buttons are not working backwards and the control configuration has + on the buttons.

If you hold ZL and move the left stick the controls start working again and you can release ZL for them to continue working but only until you stop moving the stick or pushing other buttons. You can also resolve the problem by opening the configuration options and hitting OK and then all buttons work again until ZL/ZR is pushed.

**Comment by Blaztix** [comment]
It's seen ok now

**Comment by Torped13** [comment]
Same here:

> I'm having some jump sensibility issues on SMM2 with my X360 controller.
> 
> At start it works fine, I can do all the jumps, short and high ones, until I press ZL or ZR, then I can only do the highest jump.
> 
> It's only on SMM2 though, SMO works just fine..
