### ISSUE TITLE
Feature Request: Print game ID to the console

### ISSUE THREAD

**Issue by quinton-ashley** [yuzu-emu/yuzu#3456]
Feature Request: Command line option to identify a game by printing the game ID to the console.  This would make it much easier for my frontend app [Nostlan](https://github.com/quinton-ashley/nostlan) to identify games without trying (and often failing) to match the file name with a database of game titles.

**Comment by ogniK5377** [comment]
https://github.com/yuzu-emu/yuzu/pull/2883 Games already print out their title ID when they boot

**Comment by quinton-ashley** [comment]
I'm using [gametdb](https://www.gametdb.com/Switch/Downloads) to get game art and it doesn't use title IDs it uses a different game ID. 

Sample of that database:
```
AAAAA = The Legend of Zelda: Breath of the Wild
AAABA = Super Smash Bros. Ultimate
AAACA = Super Mario Odyssey
AAB6A = Splatoon 2
AAB6B = Splatoon 2
AAB6C = Splatoon 2
AAB7A = Monster Hunter XX: Double Cross Nintendo Switch Ver.
AAB7B = Monster Hunter - Generations - Ultimate
AAB8A = Super Bomberman R
AABPA = Mario Kart 8 Deluxe
AABQA = ARMS
AACAA = Makai Senki Disgaea 5
AACAC = Disgaea 5 Complete
AACCA = 1-2-Switch
```

**Comment by DarkLordZach** [comment]
@quinton-ashley I don't know what those Game IDs are, but real switch game ids are 16-digit hex numbers. That seems to be some sort of custom-GameTDB mapping. The games don't actually have that information in them as far as I can tell.
I would suggest switching to the Title ID, as that is the official way games are identified.

**Comment by quinton-ashley** [comment]
Oh interesting.  Is there a game database file with the game titles and game ids that yuzu or the yuzu game wiki uses?  I tried to look for it on the game wiki but all I see are screenshots of the games.

**Comment by ogniK5377** [comment]
Looks like "game ids" are partial serials of the serials on game carts. Afaik, there's none of that information stored in the nacp or the npdm

**Comment by quinton-ashley** [comment]
dang that's weird cause for other systems gametdb uses the proper game id.  Do you have a database file with the game titles and title ids?

**Comment by DarkLordZach** [comment]
No, I don't think any of us have ever seen these style IDs before. I think it'd be better for you to try to find another game database source which uses title IDs.

**Comment by quinton-ashley** [comment]
I understand that now.  I'm asking if there's a database with the game titles and their proper title ids.

**Comment by quinton-ashley** [comment]
Should I post a new issue?
