### ISSUE TITLE
Time based events in Pokemon Sw/Sh don't seem to progress as expected

### ISSUE THREAD

**Issue by MBTheGamingMaster** [yuzu-emu/yuzu#3462]
Yuzu version: mainline; version 172
Operating System: Windows 10 1909 64-bit

Issue Description: Time based events like power replenishment of dens do not seem to progress as expected on a real Switch system. Time is being recorded/recognised correctly though.

Steps to reproduce:
1. Visit any power den and obtain power(watts)
2. Check the same den after few days(or by changing system's Time and Date settings).(checked both)
3. No power replenishment is observed.

System specifications are not provided as they don't seem to be important for the issue in question. It can be added if required.
Regards,
MB

**Comment by BSoDGamingYT** [comment]
Time is not changeable at runtime in yuzu (Currently). If you naturally allow time to pass, the events should occur (As long as you aren't using a custom RTC)

This behavior can be observed in timed pokemon jobs

**Comment by MBTheGamingMaster** [comment]
How should time pass actually:
1. While keeping the game open.
2. Saving on date X and then checking back on X+1

**Comment by BSoDGamingYT** [comment]
By waiting in realtime. Yuzu doesn't currently work as the switch does for time

**Comment by FernandoS27** [comment]
if you save, close yuzu, change time, reload, it should work.

**Comment by MBTheGamingMaster** [comment]
This means I should keep the game running for time to actually pass in game as well(for events like mentioned above)?

**Comment by BSoDGamingYT** [comment]
> if you save, close yuzu, change time, reload, it should work.

It currently doesn't behave like this. Or at least didn't when I tested the last changes made by Bunnei

**Comment by MBTheGamingMaster** [comment]
> if you save, close yuzu, change time, reload, it should work.

Actually I tried that to no avail actually.

**Comment by MBTheGamingMaster** [comment]
Closing this issue for the time being as it is already notified in the "issue compilation" by a fellow user.
