### ISSUE TITLE
Megaman Zero/ZX Legacy Collection, no input method works

### ISSUE THREAD

**Issue by goldenx86** [yuzu-emu/yuzu#3465]
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4258147/yuzu_log.zip)

Game won't get past the splash screen due to input problems.
Tried most possible combinations.

**Comment by mrtzera** [comment]
> [yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4258147/yuzu_log.zip)
> 
> Game won't get past the splash screen due to input problems.
> Tried most possible combinations.

same here

**Comment by RonDragon** [comment]
> > [yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4258147/yuzu_log.zip)
> > Game won't get past the splash screen due to input problems.
> > Tried most possible combinations.
> 
> same here

Same..

Yuzu dev's thanks you!
