### ISSUE TITLE
Crashes on linux after loading game

### ISSUE THREAD

**Issue by ComLarsic** [yuzu-emu/yuzu#3468]
When i run any games on Linux, it immediately crashes.
This is what gets shown in the terminal: 

`QObject::connect(QWindow, GRenderWindow): invalid nullptr parameter
libpng warning: iCCP: known incorrect sRGB profile`

there is nothing in the log file

i have tested this on both PopOS and Arch Linux.
my specs:
-i5 core
-gtx 1650
-8gb of ram

**Comment by ReinUsesLisp** [comment]
Can you post a gdb backtrace?

**Comment by ComLarsic** [comment]
> Can you post a gdb backtrace?

I'm sorry if this is a stupid question, but how would I go about doing that?

**Comment by ReinUsesLisp** [comment]
If you've built yuzu yourself, run this:
```
$ gdb bin/yuzu
r
(make yuzu crash)
bt
(copy whatever it shows after you type bt)
```

**Comment by ComLarsic** [comment]
All i seem get after that is "No stack."

**Comment by ComLarsic** [comment]
I figured out the issue, yuzu was taking up too much of my ram so the Linux kernel killed it. After upgrading my ram to 16gb and adding a swapfile the problem was fixed
