### ISSUE TITLE
Yuzu GUI program fails to respond on Windows 10

### ISSUE THREAD

**Issue by CyangYu** [yuzu-emu/yuzu#3472]
The Yuzu uses the Qt development interface, but on Windows 10, the interface program developed by Qt may become unresponsive. For example, when I click a button, the process must be closed. I don't know why Qt has not solved this problem.

**Comment by Joey11904** [comment]
This sounds like a QT issue, not a yuzu issue. have you tried reporting this bug to QT?

**Comment by CyangYu** [comment]
Yes, but when I click the button, the yuzu doesn't respond. I download yuzu from yuzu's official githut release website.
![微信截图_20200229165007](https://user-images.githubusercontent.com/17793260/75604528-7e9e5280-5b14-11ea-8b04-437505786343.png)

**Comment by CyangYu** [comment]
When I click the button to expand the game list, or the button to expand the NAND list above, the interface becomes unresponsive

**Comment by CyangYu** [comment]
The version of yuzu is "yuzu-windows-msvc-20200222-1fe5612a0"
