### ISSUE TITLE
Could I have the database yuzu uses to get game info?

### ISSUE THREAD

**Issue by quinton-ashley** [yuzu-emu/yuzu#3474]
I need a switch game database with entries that have the title id and title of the game:
```
010003F003A34000 | Pokémon: Let's Go, Pikachu!
```
Yuzu and the yuzu game wiki must use such a database.  Could I have that file?

**Comment by Morph1984** [comment]
yuzu gets this info directly from the game itself which means there is no need for a database.

**Comment by FearlessTobi** [comment]
What Morph said is correct. For info on how we do it, I'd suggest looking in our loader code.

**Comment by momala454** [comment]
https://switchbrew.org/wiki/Title_list/Games

**Comment by DarkLordZach** [comment]
@momala454 That database isn't kept extremely up to date.

**Comment by DarkLordZach** [comment]
@quinton-ashley Since this is your second issue on the topic, would you like to join our discord & we could discuss a solution in DMs?

**Comment by quinton-ashley** [comment]
If yuzu doesn't have a database with game info does that mean all the game wiki pages were done seperately?

Also I think I'll use that switchbrew database and fallback on fuzzy searching the title for newer games.  Thanks for the help!  I'll ask on discord if I have questions relating to this in the future.

**Comment by Morph1984** [comment]
The game wiki pages are either
1) Auto generated when game compatibility reports are sent (Game name and TID are sent from the yuzu client)
2) Manually made if no game compatibility reports are sent (this is highly unlikely now)

**Comment by quinton-ashley** [comment]
okay good to know.  Thank you all!
