### ISSUE TITLE
Link's Awakening Crash caused by Unmapped Read

### ISSUE THREAD

**Issue by mastercoks** [yuzu-emu/yuzu#3488]
Even using the "Softlock Fixes" mod or the game presents the error HW.Memory <Error> core \ memory.cpp: Read: 541: Unmapped Read32
[yuzu_log.txt](https://drive.google.com/file/d/1jrCePDi69cSl4UCe7ouZST3sLt6QdH89/view?usp=sharing)

**Comment by namkazt** [comment]
PR #3483 may fix that.

**Comment by Hexagon12** [comment]
Does the game work normally without the mod?

**Comment by mastercoks** [comment]
> PR #3483 may fix that.

I upgraded to version 192 and the error occurred again.

In the change log it informs that this problem has been solved, but I still have it.
[6669b35](https://github.com/yuzu-emu/yuzu-mainline/commit/6669b359a3857c265bd4d1ed77c1bce6bcd6a912)

**Comment by mastercoks** [comment]
I'm having a problem with this part, I've tried it on vulkan / opengl
![image](https://user-images.githubusercontent.com/7410215/76475244-00c42c00-63dd-11ea-84e1-4b8e8ad0f43f.png)

**Comment by MysticExile** [comment]
@mastercoks Are you still having this issue?

**Comment by mastercoks** [comment]
> @mastercoks Are you still having this issue?

Nop.
