### ISSUE TITLE
Monster Boy and the Cursed Kingdom Audio issues in EA

### ISSUE THREAD

**Issue by theboy181** [yuzu-emu/yuzu#3492]
![image](https://user-images.githubusercontent.com/9299743/76268997-47732400-622d-11ea-93c2-e1f9a22cac25.png)

As of this date I tested yuzu 191 (mainline) and the audio works, but in EA 258 the audio is extremely broken.

**Comment by Hexagon12** [comment]
How is it broken? Do you have any audio examples of how it should sound and how it sounds while being broken?

**Comment by theboy181** [comment]
The audio in EA seems to have timing issues. BGM will play for a bit then stop and the and voices like jump will not always play.

**Comment by theboy181** [comment]
https://cdn.discordapp.com/attachments/294667243235573760/686947268644962329/Videos.zip

Here are two video of the audio

**Comment by bunnei** [comment]
Probably #3321

**Comment by theboy181** [comment]
An other observation about this game is setting the game to 30fps the audio will slow down. The audio is linked to the frame rate. The games pacing will adjust to 30fps properly though.

**Comment by german77** [comment]
Works fine on yuzu 680
