### ISSUE TITLE
GL_INVALD_OPERATION error on Intel iGPUs after mainline build 192

### ISSUE THREAD

**Issue by randompasser** [yuzu-emu/yuzu#3507]
The underlying issue causing this is ostensibly fixed for Nvidia and AMD by #3494, but the OpenGL renderer remains broken for Intel GPUs.

Attempting to launch the following games (and likely many others) with mainline 192 (8e554e7c7) or newer either crashes the emulator or nothing renders on screen with the following error in log `Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:283: API ERROR 1282: Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error`:

- Project Diva Mega39's
- Dark Witch Music Episode: Rudymical
- Untitled Goose Game

The same games render correctly
 on 191 and earlier. Not certain if this issue is fixable but it would be great if someone could look into it.

[Log file from Untitled Goose Game on EA build 270](https://github.com/yuzu-emu/yuzu/files/4331119/yuzu_log.txt)

**Comment by benderscruffy** [comment]
Is this still an issue ??

**Comment by liamwhite** [comment]
Tested with OpenGL and Windows 11 on an i5-12600K and I did not get any errors. Comment with an updated log if this still occurs.
