### ISSUE TITLE
Error Build Yuzu 271 in Linux 

### ISSUE THREAD

**Issue by iWeaker4you** [yuzu-emu/yuzu#3511]
When I'm compiling this Build on Linux I get this problem:

vk_shader_decompiler.cpp:840:21: error: converstion from  ‘int’ to  ‘u8’
[-Werror=conversion]  element += static_cast<u8>(num_components);

In previous builds I did not have this problem.

I'm using Arch Linux ,

**Comment by victords** [comment]
Hi, I am having the same error in Linux Mint 19.
