### ISSUE TITLE
Ben 10 doesnt register gamepad in Main-Menu

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#3514]
Game boots smoothly till Main Menu both using Vulkan and OpenGL but when the game asks you to press "A" to continue, nothing happens. My gamepad registers buttons button in yuzu options but doesnt get recognised by this game.
Log File:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4333531/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
Use the custom/Pro Controller configs (yuzus controller profiles are broken)
![controls](https://user-images.githubusercontent.com/38402209/76692369-de891300-6655-11ea-8725-7d3e39e8691f.PNG)

Github is also not the place for these types of things, the discord server is best suited to them

**Comment by EliasM108** [comment]
I'm already using pro controller config. Mario odyssey works fine. I'm having issues only with this game.

**Comment by Aris-t2** [comment]
Any chance the game does not support Pro Controller at all?

Works fine with emulated Dual Joycons (using Xbone controller):
![joycons](https://user-images.githubusercontent.com/6013569/86017128-f4172280-ba23-11ea-9eb8-878fd963ff30.JPG)

**Comment by EliasM108** [comment]
> Any chance the game does not support Pro Controller at all?
> 
> Works fine with emulated Dual Joycons (using Xbone controller):
> ![joycons](https://user-images.githubusercontent.com/6013569/86017128-f4172280-ba23-11ea-9eb8-878fd963ff30.JPG)

As it turns out only Pro Controller has this malfunction. By the way, when using the dual joycons, i diagonal directions dont register. You can test it at the start where it asks you to transform into cannonbolt.

**Comment by Aris-t2** [comment]
>As it turns out only Pro Controller has this malfunction. By the way, when using the dual joycons, diagonal directions dont register. You can test it at the start where it asks you to transform into cannonbolt.

I can not confirm that. Diagonal directions register fine here. Maybe your "Deadzone" value is too high. 10% was OK for my Xbone controller.
Try to reconfigure left/right axis using "Set Analog Stick" dialog window buttons shown on above's screenshot.

Regardless of the results of this workaround, "Pro" controller still has the issue.

**Comment by Morph1984** [comment]
This game does not support the Pro Controller, this is corroborated by a [review](http://gamerhub.tv/article/851517/ben-10-review) and the npad style set showing that the Pro Controller and Single Joycons are not supported.

Only the Dual Joycons and Handheld mode are supported.

> A major issue I had right off the bat playing Ben 10 was that it doesn’t use the Pro Controller as a mode on control, which is a major hassle. You can use the Joy Cons as well as play on the Switch in mobile/off TV mode but not having the Pro Controller as an option is a pain to deal with.

**Comment by EliasM108** [comment]
The game works fine now!
