### ISSUE TITLE
Animal Crossing: New Horizons doesn't start

### ISSUE THREAD

**Issue by ANIMEFANATIC91** [yuzu-emu/yuzu#3528]
I'm using Yuzu 191
The emulator gets stuck in launching screen, no matter how I configure it.

**Comment by Hexagon12** [comment]
The game has not been officially released yet. Please wait for the official release.

**Comment by TheMysticLynx** [comment]
The game has been officially released.

**Comment by burstpup** [comment]
Re-open the issue for the release of the game? I've got my copy, lol

**Comment by Evernow** [comment]
@Hexagon12 Re-open, the game has been released.
