### ISSUE TITLE
The Liar Princess and the Blind Prince audio glitch

### ISSUE THREAD

**Issue by sixgjack** [yuzu-emu/yuzu#3532]
Help! When I am playing The Liar Princess and the Blind Prince, there is an audio proplem which the voice of the narrator keeps repeating in the prologue part. Is there anything I can do to get rid of this problem?
 The game ID is  010064B00B95C000 and the Compatibility is shown as "Great". 
Many thanks!

**Comment by FearlessTobi** [comment]
This report is missing important information such as your yuzu log for example.

**Comment by kekosminek** [comment]
I have the same problem.

The audio of the game is repeating 3 times. Other than that the game runs fine.
I am on windows, using the newest build of Yozu EA 668. Game version 010064B00B95C000

The Yozu log is just repeating "Service.AM <Warning> core\hle\service\am\am.cpp:GetCurrentFocusState:674: (STUBBED) called" even when i'm not doing anything.

[
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4944748/yuzu_log.txt)
](url)

**Comment by benderscruffy** [comment]
doesnt repeat now
just plays normal
can be closed
