### ISSUE TITLE
gl_texture_cache.cpp:Attach:416: Assertion Failed! Unimplemented code!

### ISSUE THREAD

**Issue by cmho2007** [yuzu-emu/yuzu#3536]
Luigi Mansion 3 always freeze/crash when walking through the B1 basement corridor, when using recent EA version. 

The log file shows :gl_texture_cache.cpp:Attach:416: Assertion Failed! Unimplemented code!

Below is the log file

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4354328/yuzu_log.zip)

Here's the location of the freeze/crash

![image](https://user-images.githubusercontent.com/62342979/77066384-ff6ab300-6a1d-11ea-8cad-ad364eaf7c08.png)

**Comment by SilverBeamx** [comment]
1) What version of Yuzu are you using? That doesn't seem to be from Mainline at all. Update your files.
2) File names in log are suspicious. I suspect some piracy going on here.

**Comment by cmho2007** [comment]
Thx for the reply. Im using EA 290 version. May be i try again with mainline version. 
Yes frankly thats from a downloaded LM3 rom. 




傳送自 Android 上的 Yahoo Mail 
 
  在 2020 年 3月 月 19 日 週四，時間： 20:43，SilverBeamx<notifications@github.com>寫道：   

   
   - What version of Yuzu are you using? That doesn't seem to be from Mainline at all. Update your files.
   - File names in log are suspicious. I suspect some piracy going on here.

**Comment by Eloeri** [comment]
Please understand that we don't support piracy. You need to dump your games and keys from your Nintendo Switch.

**Comment by cmho2007** [comment]
Noted with thx. 

傳送自 Android 上的 Yahoo Mail 
 
  在 2020 年 3月 月 19 日 週四，時間： 21:06，Eloeri<notifications@github.com>寫道：   


Please understand that we don't support piracy. You need to dump your games and keys from your Nintendo Switch.
