### ISSUE TITLE
Cant uninstall

### ISSUE THREAD

**Issue by thegamerx1** [yuzu-emu/yuzu#3537]
![image](https://user-images.githubusercontent.com/34986564/77128107-3dcc9600-6a4f-11ea-9099-839e0629a276.png)

When trying to uninstall from windows start menu
![image](https://user-images.githubusercontent.com/34986564/77128153-5e94eb80-6a4f-11ea-9e65-f7229177ca03.png)
![image](https://user-images.githubusercontent.com/34986564/77128137-55a41a00-6a4f-11ea-99f8-47b874b25d58.png)

It doesnt appear on control panel or revo uninstaller

**Comment by goldenx86** [comment]
Github is not for support.
Go to %localappdata%\yuzu, run the maintenancetool.exe, uninstall it from there.
