### ISSUE TITLE
The interface becomes unresponsive

### ISSUE THREAD

**Issue by CyangYu** [yuzu-emu/yuzu#3538]
When I click the button in the game list, as shown by the arrow, the interface becomes unresponsive

![Snipaste_2020-03-20_16-01-00](https://user-images.githubusercontent.com/17793260/77145768-6cd11f00-6ac4-11ea-9a50-579347ebe29e.png)
![Snipaste_2020-03-20_16-01-59](https://user-images.githubusercontent.com/17793260/77145773-6fcc0f80-6ac4-11ea-8269-41cb5ba3da8b.png)

**Comment by german77** [comment]
Not an issue in yuzu 680
