### ISSUE TITLE
Make -j4 sırasında hata

### ISSUE THREAD

**Issue by TunahanYeniyayla** [yuzu-emu/yuzu#3551]
After applying make -j4 command, I get the following error in 75% order:

`27 warnings and 1 error generated.`
`make[2]: *** [src/video_core/CMakeFiles/video_core.dir/renderer_opengl/gl_rasterizer.cpp.o] Error 1`
`make[1]: *** [src/video_core/CMakeFiles/video_core.dir/all] Error 2`
`make: *** [all] Error 2`

I'm using Mac Os 10.15.3

**Comment by TunahanYeniyayla** [comment]
Mac Os 10.15.3 kullanıyorum

**Comment by FearlessTobi** [comment]
macOS is not officially supported by us.
