### ISSUE TITLE
missing instructions where to put keys.prod file

### ISSUE THREAD

**Issue by jug007** [yuzu-emu/yuzu#3553]
I was not able to find any instructions on where to put the keys.prod file.
Someone in discord told me it goes into ~/.local/share/yuzu/keys/
That folder was not even created by yuzu.

I feel like the folder should be created by yuzu at runtime and that there should be instructions on where to put the keys.prod file in the first place.

I was using build 20200324-2e484ccc7 for this.

**Comment by ToxaGaming** [comment]
the yuzu quickstart guide [https://yuzu-emu.org/help/quickstart/](url) tells you to place the keys files in the `%YUZU_DIR%/keys` directory. The yuzu directory is always in `User/AppData/Roaming/yuzu`. I do think that this could be specified a little clearer on the site

**Comment by jug007** [comment]
Maybe this would be more clear if the instructions had an own section for saving the stuff on your computer.
I didn't even look into "Dumping Prod.keys and Title.keys" because I already have them dumped.

**Comment by MysticExile** [comment]
This is a non-issue

**Comment by tomlube** [comment]
> This is a non-issue

Considering I had to find this issue on GitHub before I could actually see *where* the keys had to be placed, I don't know if I agree with this assessment. A little clarity on the website would go a long way.

**Comment by C0rn3j** [comment]
@MysticExile at least 8 people ran into this specific issue (and I do mean this specific URL) - is there any reason not to at least automatically generate the folders upon startup?
