### ISSUE TITLE
missing instructions on how to run linux build

### ISSUE THREAD

**Issue by JulianGro** [yuzu-emu/yuzu#3554]
The prebuild of yuzu comes with no instructions on how to actually use it.
Most linux users will realize that they can just use ./yuzu , but some newbies might not know that.
There is also no dependency list for the prebuild version. This makes you need to either start yuzu and try to install whatever it says missing until it actually runs, or you need to install the dependencies for builiding it yourself, which uses a lot more space than would be needed.

I feel like yuzu should at least come with a readme listing the dependencies and how to actually run it.

EDIT: this is on build 20200324-2e484ccc7

**Comment by degasus** [comment]
Have you seen this page https://github.com/yuzu-emu/yuzu/wiki/Building-For-Linux ?
What do you think is missing there?

**Comment by jug007** [comment]
That page is for building Yuzu. Not running the prebuilt package.
If you followed that build guide you would install hundreds of megabytes of packages which you don't need.

**Comment by degasus** [comment]
Honestly, I recorment to build yuzu on your own instead of using the prebuild package. But for the binary-only early-access packages, this really sounds like a good idea.

**Comment by german77** [comment]
If you are using linux this should be self intuitive. AppImage can be executed with double click
