### ISSUE TITLE
Closing settings menu temporarily freezes system

### ISSUE THREAD

**Issue by JulianGro** [yuzu-emu/yuzu#3557]
When closing the settings menu on my Linux Mint 19.3 machine, the whole system freezes for 1-5 seconds.
This is a minor issues, but makes Yuzu feel really janky of course.
Happendes on build 20200324-2e484ccc7 for me.
I was told that the log doesn't show anything useful: [yuzu_freeze_system.log](https://github.com/yuzu-emu/yuzu/files/4380413/yuzu_freeze_system.log)

**Comment by german77** [comment]
This issue hasn't been reported on the last year or so. Please reopen if the issue is still present
