### ISSUE TITLE
Yuzu Memory Issue (Unmapped Read)

### ISSUE THREAD

**Issue by AsTraXx2610** [yuzu-emu/yuzu#3558]
Hello i have a issue when luanching mystery dunguen DX
[   4.940820] HW.Memory <Error> core\memory.cpp:Read:165: Unmapped Read8 @ 0x800000000
[   4.940834] HW.Memory <Error> core\memory.cpp:Read:165: Unmapped Read64 @ 0x800000000
If you know how to fix it ? :)

Complete log 

[   0.552653] Frontend <Info> yuzu\main.cpp:GMainWindow:214: yuzu Version:  | HEAD-mainline-636-550-g748ee4daf
[   0.552660] Frontend <Info> yuzu\main.cpp:GMainWindow:216: Host CPU: AMD Ryzen 5 3600X 6-Core Processor             
[   0.552679] Frontend <Info> yuzu\main.cpp:GMainWindow:218: Host OS: Windows 10 (10.0)
[   0.618350] Config <Info> core\settings.cpp:LogSettings:84: yuzu Configuration:
[   0.618355] Config <Info> core\settings.cpp:LogSetting:80: System_UseDockedMode: true
[   0.618356] Config <Info> core\settings.cpp:LogSetting:80: System_RngSeed: 0
[   0.618356] Config <Info> core\settings.cpp:LogSetting:80: System_CurrentUser: 0
[   0.618357] Config <Info> core\settings.cpp:LogSetting:80: System_LanguageIndex: 2
[   0.618358] Config <Info> core\settings.cpp:LogSetting:80: Core_UseMultiCore: false
[   0.618366] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseResolutionFactor: 1.0
[   0.618367] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseFrameLimit: true
[   0.618367] Config <Info> core\settings.cpp:LogSetting:80: Renderer_FrameLimit: 100
[   0.618368] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseDiskShaderCache: true
[   0.618370] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseAccurateGpuEmulation: false
[   0.618371] Config <Info> core\settings.cpp:LogSetting:80: Renderer_UseAsynchronousGpuEmulation: true
[   0.618372] Config <Info> core\settings.cpp:LogSetting:80: Audio_OutputEngine: auto
[   0.618372] Config <Info> core\settings.cpp:LogSetting:80: Audio_EnableAudioStretching: true
[   0.618374] Config <Info> core\settings.cpp:LogSetting:80: Audio_OutputDevice: auto
[   0.618375] Config <Info> core\settings.cpp:LogSetting:80: DataStorage_UseVirtualSd: true
[   0.618376] Config <Info> core\settings.cpp:LogSetting:80: DataStorage_NandDir: C:\Users\Alban\AppData\Roaming/yuzu/nand/
[   0.618377] Config <Info> core\settings.cpp:LogSetting:80: DataStorage_SdmcDir: C:\Users\Alban\AppData\Roaming/yuzu/sdmc/
[   0.618378] Config <Info> core\settings.cpp:LogSetting:80: Debugging_UseGdbstub: false
[   0.618378] Config <Info> core\settings.cpp:LogSetting:80: Debugging_GdbstubPort: 24689
[   0.618379] Config <Info> core\settings.cpp:LogSetting:80: Debugging_ProgramArgs: 
[   0.618379] Config <Info> core\settings.cpp:LogSetting:80: Services_BCATBackend: boxcat
[   0.618380] Config <Info> core\settings.cpp:LogSetting:80: Services_BCATBoxcatLocal: false
[   2.291499] Frontend <Info> yuzu\main.cpp:BootGame:965: yuzu starting...
[   2.408845] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontStandard' (0x0100000000000811).
[   2.409084] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   2.409243] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[   2.409546] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   2.409656] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[   2.409835] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   2.410048] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontChineseTraditional' (0x0100000000000813).
[   2.410125] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   2.410234] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontKorean' (0x0100000000000812).
[   2.410312] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   2.410435] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[   2.410448] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   2.410456] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:75: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[   2.410467] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:90:     - System archive generation successful!
[   2.410964] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:AddTelemetryFields:248: GL_VERSION: 4.6.0 NVIDIA 442.50
[   2.410967] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:AddTelemetryFields:249: GL_VENDOR: NVIDIA Corporation
[   2.410968] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:AddTelemetryFields:250: GL_RENDERER: GeForce GTX 1060 3GB/PCIe/SSE2
[   2.415981] Render.OpenGL <Info> video_core\renderer_opengl\gl_device.cpp:Device:73: Renderer_VariableAOFFI: true
[   2.415984] Render.OpenGL <Info> video_core\renderer_opengl\gl_device.cpp:Device:74: Renderer_ComponentIndexingBug: false
[   2.415985] Render.OpenGL <Info> video_core\renderer_opengl\gl_device.cpp:Device:75: Renderer_PreciseBug: false
[   3.177226] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:60: Patching ExeFS for title_id=01003D200BAA2000
[   3.394164] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:235: Querying NSO patch existence for build_id=39E10C07096696C9C4E228496C4BC44D6B9E0041
[   3.696918] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:235: Querying NSO patch existence for build_id=CA19D0695861144B8A0FD0C438264A76
[   3.725037] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:235: Querying NSO patch existence for build_id=BAEE264D3658FC6B6B581E5CBB662E3ABFE6782B
[   3.776660] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:235: Querying NSO patch existence for build_id=E30D2170165E907ABA457C79FD83383D5ECD2C3D
[   3.829798] Frontend <Info> yuzu\main.cpp:BootGame:1011: Booting game: 01003D200BAA2000 | Pokémon Mystery Dungeon Rescue Team DX
[   3.856170] Render.OpenGL <Info> video_core\renderer_opengl\gl_shader_disk_cache.cpp:LoadTransferable:136: No transferable shader cache found for game with title id=01003D200BAA2000
[   3.987586] Kernel <Warning> core\hle\kernel\vm_manager.cpp:GetTotalPhysicalMemoryAvailable:1041: (STUBBED) called
[   4.001150] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:46: (STUBBED) called
[   4.011548] Service.AM <Warning> core\hle\service\am\am.cpp:GetCurrentFocusState:658: (STUBBED) called
[   4.012240] Service.AM <Warning> core\hle\service\am\am.cpp:AcquireForegroundRights:95: (STUBBED) called
[   4.012847] Service.AM <Warning> core\hle\service\am\am.cpp:SetFocusHandlingMode:408: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[   4.013408] Service.AM <Warning> core\hle\service\am\am.cpp:SetOutOfFocusSuspendingEnabled:427: (STUBBED) called enabled=false
[   4.015544] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:46: (STUBBED) called
[   4.017381] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:46: (STUBBED) called
[   4.018845] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:46: (STUBBED) called
[   4.018883] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:46: (STUBBED) called
[   4.018968] Service.PCTL <Warning> core\hle\service\pctl\module.cpp:Initialize:119: (STUBBED) called
[   4.019623] Kernel <Warning> core\hle\kernel\vm_manager.cpp:GetTotalPhysicalMemoryAvailable:1041: (STUBBED) called
[   4.202225] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:46: (STUBBED) called
[   4.203011] Service.LM <Info> core\hle\service\lm\manager.cpp:InitializeLog:124: Initialized new log session
[   4.203015] Service.LM <Info> core\hle\service\lm\manager.cpp:FinalizeLog:130: Finalized current log session
[   4.203713] Service.APM <Info> core\hle\service\apm\controller.cpp:SetClockSpeed:84: called, mhz=000006F9
[   4.227475] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:46: (STUBBED) called
[   4.232655] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:46: (STUBBED) called
[   4.233752] IPC <Warning> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:145: Domain request has no DomainMessageHeader!
[   4.234716] IPC <Warning> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:145: Domain request has no DomainMessageHeader!
[   4.314851] Service.NVDRV <Warning> core\hle\service\nvdrv\interface.cpp:Initialize:120: (STUBBED) called
[   4.320791] Service <Warning> core\hle\service\sm\controller.cpp:DuplicateSessionEx:40: (STUBBED) called, using DuplicateSession
[   4.322284] Service.NVDRV <Warning> core\hle\service\nvdrv\interface.cpp:SetClientPID:150: (STUBBED) called, pid=0x51
[   4.323244] Service.NVDRV <Warning> core\hle\service\nvdrv\interface.cpp:FinishInitialize:158: (STUBBED) called
[   4.327535] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetManagerDisplayService:905: (STUBBED) called
[   4.328269] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetSystemDisplayService:897: (STUBBED) called
[   4.328722] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetRelayService:889: (STUBBED) called
[   4.333055] Service.AM <Warning> core\hle\service\am\am.cpp:SetRestartMessageEnabled:415: (STUBBED) called
[   4.333210] Service.AM <Warning> core\hle\service\am\am.cpp:SetPerformanceModeChangedNotification:389: (STUBBED) called flag=true
[   4.333362] Service.AM <Warning> core\hle\service\am\am.cpp:SetOperationModeChangedNotification:379: (STUBBED) called flag=true
[   4.403739] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:369: Patching RomFS for title_id=01003D200BAA2000, type=01
[   4.406429] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:369: Patching RomFS for title_id=01003D200BAA2000, type=01
[   4.940820] HW.Memory <Error> core\memory.cpp:Read:165: Unmapped Read8 @ 0x800000000
[   4.940834] HW.Memory <Error> core\memory.cpp:Read:165: Unmapped Read64 @ 0x800000000

**Comment by Hexagon12** [comment]
`[ 0.552653] Frontend yuzu\main.cpp:GMainWindow:214: yuzu Version: | HEAD-mainline-636-550-g748ee4daf`

You have an outdated version of yuzu. The game was fixed with #3340.
