### ISSUE TITLE
Yuzu version missing from log file

### ISSUE THREAD

**Issue by SilverBeamx** [yuzu-emu/yuzu#3559]
Yuzu's log file misses a "human-readable" version number. It looks like it is supposed to be placed before the git hash, but i was told this feature has been broken some time ago. Could someone look into it? I think this would help a lot identifying reported issues stemming from outdated/EA builds.

**Comment by goldenx86** [comment]
This would simplify giving support a lot.

**Comment by SilverBeamx** [comment]
After a bit of snooping around, it seems that the backtrace to the root of the problem is:
https://github.com/yuzu-emu/yuzu/blob/master/src/yuzu/main.cpp  <-
https://github.com/yuzu-emu/yuzu/blob/master/src/common/scm_rev.cpp.in <-
https://github.com/yuzu-emu/yuzu/blob/master/CMakeModules/GenerateSCMRev.cmake <-
https://github.com/yuzu-emu/yuzu/blob/master/src/common/CMakeLists.txt

Can someone check if the "BUILD_TAG" flag is set at compile time? Or anywhere else. I think that the if that sets the version number in GenerateSCMRev.cmake is skipped due to the unset variable.
