### ISSUE TITLE
SMO: Bowser does only 1 jump phase

### ISSUE THREAD

**Issue by sludgybeast** [yuzu-emu/yuzu#3570]
Its really small and unimportant, but in cloud kingdom, bowser always does only 1 jump before next phase, usually thats really hard to get and saves a bunch of time. But also playing on yuzu naturally loses a bunch of time and i doubt anyone would care for a yuzu speedrun
but still fairs fair

**Comment by german77** [comment]
Emulation should now be fast enough to match the console. Please test again.

**Comment by G-Spawn** [comment]
^ Please reopen issue if this still happens to you and provide a log like the issue template asked for.
