### ISSUE TITLE
Weird Smash attack on all characters

### ISSUE THREAD

**Issue by turkeynaruto** [yuzu-emu/yuzu#3575]
If you hold direction+A and load the smash the end animation frezzes to long. 
Happens on Vulkan and OpenGL on Yuzu EA 308 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18088164/77811568-91686080-709b-11ea-93f9-f196534960ba.gif)

Heres a Video of it:
https://streamable.com/pl6jo

**Comment by slashiee** [comment]
This is intended by the game itself. Requesting a close.

https://streamable.com/f29jz
