### ISSUE TITLE
BGRA color issues when using OpenGL

### ISSUE THREAD

**Issue by theboy181** [yuzu-emu/yuzu#3581]
OpenGL
![image](https://user-images.githubusercontent.com/9299743/77856200-60c31c80-71aa-11ea-9c22-91522f5a0f0e.png)

From the picture above you can see that the Jumbotron `https://en.wikipedia.org/wiki/Jumbotron inverts the colors, each pass that is captured to the frame buffer. You will see the color of Mario's hat go from blue, to red, then blue to red, ect...

Vulkan
![image](https://user-images.githubusercontent.com/9299743/77856315-227a2d00-71ab-11ea-98c1-1e10d5e83230.png)

In Vulkan the Jumbotron fails to render the frame buffer effect.

**Comment by exalented** [comment]
![Screenshot_290](https://user-images.githubusercontent.com/9328864/77858085-15af0680-71b6-11ea-9d8b-528283ade1c6.png)
The earliestive seen this documented was Sept 11th 2019. https://discordapp.com/channels/398318088170242053/472575665334648833/621447702244229131

**Comment by slashiee** [comment]
Hatsune Miku Project DIVA MEGA39s also has this issue
<img width="961" alt="2020-04-18_12-53-55" src="https://user-images.githubusercontent.com/15317421/79669877-ab193700-8173-11ea-8e77-6244582c34c2.png">

**Comment by theboy181** [comment]
she looks like she has more fun as a blond @slashiee

**Comment by slashiee** [comment]
Also happens with RollerCoaster Tycoon 3's ride textures, fixed when using Vulkan.
<img width="1281" alt="2020-10-09_17-58-41_yuzu" src="https://user-images.githubusercontent.com/15317421/95641959-62737400-0a5a-11eb-9348-6fa88c8a290c.png">
<img width="1281" alt="2020-10-09_18-06-42_yuzu" src="https://user-images.githubusercontent.com/15317421/95641966-7323ea00-0a5a-11eb-9e43-ff4e667506fa.png">

**Comment by RodrigoTR04** [comment]
Also happens on the 3 Steins;Gate games
![My Darling's Embrace](https://user-images.githubusercontent.com/65554156/100558684-24424600-328e-11eb-99fc-c6cb14af77bd.png)
![Steins;Gate 0](https://user-images.githubusercontent.com/65554156/100558686-25737300-328e-11eb-94e6-06d71b44bf3b.png)
![Steins;Gate ELITE](https://user-images.githubusercontent.com/65554156/100558688-25737300-328e-11eb-940f-ba32f72e5fee.png)

**Comment by ActualMandM** [comment]
SSBU's jumbotron shows up in latest EA, it does not have BGRA issues.
<img width="961" alt="2020-11-29_17-11-50_yuzu" src="https://user-images.githubusercontent.com/15317421/100559087-019c3700-3266-11eb-840e-8062c34c785d.png">

**Comment by gidoly** [comment]
dragon quest 11 and octopath traveler have issue as well

octopath traveler:

open gl
<img width="1251" alt="20201130_101011" src="https://user-images.githubusercontent.com/66776795/100559152-c85ed800-32f4-11eb-8ef6-ee7e5edbea32.png">

vulkan
<img width="1250" alt="20201130_101232" src="https://user-images.githubusercontent.com/66776795/100559156-ceed4f80-32f4-11eb-931f-0a7a20d09580.png">

dragon quest 11

open gl
<img width="1255" alt="fd" src="https://user-images.githubusercontent.com/66776795/100559172-df9dc580-32f4-11eb-9ccd-e7ade0f1acdf.png">

vulkan
<img width="1258" alt="20201130_100703" src="https://user-images.githubusercontent.com/66776795/100559179-e62c3d00-32f4-11eb-8936-af5a6ecaa244.png">
