### ISSUE TITLE
No input on Linux

### ISSUE THREAD

**Issue by victords** [yuzu-emu/yuzu#3582]
Hi,
I'm using yuzu-mainline (commit: a560834f8b57ccd0159b9cd09f3cf2bc18958574, tag: mainline-0-207), built it myself on Linux Mint 19, using the Linux build guide, setting the option -DENABLE_VULKAN=No in the cmake step.
The emulator opens and the configuration window as well, I'm able to set the controls for both keyboard and joystick. However, when a game is loaded, the input doesn't work at all (neither keyboard nor joystick). I tested with Snipperclips (compatibility according to the site: Great) and Ittle Dew 2 (compatibility: Perfect).
Below is the log from the last attempt.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4399678/yuzu_log.txt)

**Comment by goldenx86** [comment]
Set your input as custom like this: https://media.discordapp.net/attachments/400106910231035904/659301290114809879/unknown.png?width=412&height=567
That should work on most games.

**Comment by victords** [comment]
Wow, it actually worked... checking "Use docked mode" did the trick. Thanks!
