### ISSUE TITLE
yuzu crashes on ubuntu 19.04 running KDE with plasma 5 and nvidia driver 440.26 with the following message.

### ISSUE THREAD

**Issue by Nilot352** [yuzu-emu/yuzu#3583]
malloc(): invalid next size (unsorted)
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = yuzu path = /usr/local/bin pid = 26610
KCrash: Arguments: /usr/local/bin/yuzu 
QSocketNotifier: Invalid socket 6 and type 'Read', disabling...
QSocketNotifier: Invalid socket 32 and type 'Read', disabling...
The X11 connection broke (error 1). Did the X11 server die?

**Comment by Nilot352** [comment]
This happens when opening the configure window.

**Comment by Hexagon12** [comment]
Try opening the configure window without internet connection. If it opens, go to System - Services and set Boxcat to none.

**Comment by Nilot352** [comment]
Holy Shit! that worked.
Please close this.

**Comment by IvarWithoutBones** [comment]
shouldn't that be a non issue with #3526 being merged

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/2957.

**Comment by FearlessTobi** [comment]
@IvarWithoutBones It is fixed now, but only for new users of the emulator.
