### ISSUE TITLE
Graphical regression in ARMS

### ISSUE THREAD

**Issue by BSoDGamingYT** [yuzu-emu/yuzu#3584]
Opening this issue to keep track of a regression to ARMS

This occurred between Mainline 195 and Mainline 197

Mainline 195
![Capture (1)](https://user-images.githubusercontent.com/38402209/77958734-c3fd9d80-72d5-11ea-9e2b-916fd79f1ba3.png)

Mainline 197
![Capture (2)](https://user-images.githubusercontent.com/38402209/77958758-cd870580-72d5-11ea-93bb-09abbf28ae86.png)

This issue is currently present in both Mainline and Early Access builds.

**Comment by ReinUsesLisp** [comment]
This regression started when transform feedbacks was merged. Investigating.

**Comment by ReinUsesLisp** [comment]
As far as I could see today, this can work randomly depending on when the shader cache is enabled or disabled. This regression can be older than yuzu 195, because that's when shader caches got invalidated.

**Comment by ReinUsesLisp** [comment]
I can no longer reproduce this locally in master. I consistently get this now:
![imagen](https://user-images.githubusercontent.com/26564870/78108719-56816800-73ce-11ea-865b-68828319f071.png)

@BSoDGamingYT can you try deleting your cache for Arms and switch between it on and off?

**Comment by KChunStry** [comment]
I've noticed the same issue, but deleting or switching between on and off did not fix the problem, then using the newer updates causes weird glitches and a big loss in performance in-game.

**Comment by KChunStry** [comment]
![2020-04-01 14_50_10-Window](https://user-images.githubusercontent.com/60659350/78139044-2961a380-7428-11ea-8b7d-74d1cc53c96f.png)
Idk if this can help but using accurate gpu fixes the issue(well, 3 fps is the max i could get lol)

**Comment by ReinUsesLisp** [comment]
I've tried again today. I still can't reproduce this.

**Comment by ReinUsesLisp** [comment]
Does this still happen after we updated to MSVC 2019 on mainline and EA releases?

**Comment by BSoDGamingYT** [comment]
> Does this still happen after we updated to MSVC 2019 on mainline and EA releases?

I will check this ASAP

**Comment by BSoDGamingYT** [comment]
Fixed with #3599
