### ISSUE TITLE
Super Smash Bros. Ultimate Mii Crashes

### ISSUE THREAD

**Issue by theincredibleplayer** [yuzu-emu/yuzu#3587]
Creating a Mii or joining century smash or going into a stage with a mii in it (Find Mii, Tomadachi life) causes the game to softlock.

Creating Mii log:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4405668/yuzu_log.zip)
![Screenshot (1105)](https://user-images.githubusercontent.com/54246318/77965723-ed242b00-72e1-11ea-9755-568a103c94ad.png)

Century smash log:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4405683/yuzu_log.zip)
crashes after selecting character and starting,doesnt progress to gameplay.
![Screenshot (1106)](https://user-images.githubusercontent.com/54246318/77965714-e7c6e080-72e1-11ea-81db-248ae689250f.png)

tomadachi life stage log:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4405732/yuzu_log.zip)

Tested on yuzu Early access 317

**Comment by hyoretsu** [comment]
So can we assume we aren't gonna need a Switch or Ryujinx to create a save on games like Mario Kart 8 Deluxe in the near future?
