### ISSUE TITLE
Adapt ingame screen ratio to certain resolutions when window is maximized

### ISSUE THREAD

**Issue by Mimimax** [yuzu-emu/yuzu#3590]
Certain monitor/TV resolutions, such as 1360X768, have the bottom of the emulator's window cut off a bit while a game is running, which includes the entire status bar and a small portion of the game screen display. Found in Windows 10 x64, not sure if it applies to any OS.
Example screenshot attached.

![yuzuScreenBottomCut](https://user-images.githubusercontent.com/17322555/78074335-eeecfd80-7378-11ea-8d6f-9df8c3c31622.png)

**Comment by Morph1984** [comment]
Fixed by #3413
