### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by joker5bb** [yuzu-emu/yuzu#3596]
I am running debian, Kernel 5.6.1.
I have have successfully built the latest yuzu with no errors.

How can I debug to trace the issue of segmentation fault?

**Comment by FearlessTobi** [comment]
Where or when exactly does it segfault?

**Comment by joker5bb** [comment]
(gdb) run
Starting program: /usr/local/bin/yuzu 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__GI___pthread_rwlock_wrlock (rwlock=0x0) at pthread_rwlock_wrlock.c:27
27	pthread_rwlock_wrlock.c: No such file or directory.

**Comment by joker5bb** [comment]
Issue is solved by installing libressl
https://github.com/yuzu-emu/yuzu/issues/2969#issuecomment-541362356
