### ISSUE TITLE
RNG Seed not working for Pokemon Let's Go Pikachu/Eevee

### ISSUE THREAD

**Issue by Cunningosorey** [yuzu-emu/yuzu#3598]
I was told that changing the RNG seed would randomize trainers and encounters so before loading the game I changed the RNG seed but it did not change anything and I am unsure as to whether that's what changing the RNG seed does  or whether I am doing it wrong.
![image](https://user-images.githubusercontent.com/63131088/78414293-6211a080-7613-11ea-81f8-33a5ce5be323.png)

**Comment by Benedani** [comment]
I think they meant the RNG seed for the randomizer? The emulator doesn't provide randomization for you, unless it is built into the romhack.

**Comment by liamwhite** [comment]
This seems to have been based on a misunderstanding? Comment if you think this issue is still valid, but I checked and the RNG seed configuration affects random number generation in all the places it is provided by the emulator.
