### ISSUE TITLE
Mario Golf (in Sports Superstars) runs at 50% speed

### ISSUE THREAD

**Issue by legend800** [yuzu-emu/yuzu#3604]
Mario golf in this collection runs at 60fps while the rest runs at 30fps. I think that's why it never tops 30fps which is 50% for this game, and not my pc specs which runs every 3ds game at full speed. 

![sports](https://user-images.githubusercontent.com/20983844/78461347-eea47900-767c-11ea-99ea-02c9acb80c44.png)

![2020-04-04 13_50_54-Window](https://user-images.githubusercontent.com/20983844/78461349-f06e3c80-767c-11ea-9aec-a875b51d9987.png)

[sports.zip](https://github.com/yuzu-emu/yuzu/files/4432523/sports.zip)

Version: 
1633

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4.5 ghz
16GB RAM

**Comment by BSoDGamingYT** [comment]
I believe you posted this issue in the wrong place. These are issues for Citra, not yuzu
