### ISSUE TITLE
VCRUNTIME140_1.dll not found

### ISSUE THREAD

**Issue by Kenzo95** [yuzu-emu/yuzu#3609]
I have started yuzu(Mainline 218 last working version) 10 seconds ago and it have done the same update and then:

error(In Italian) "L'esecuzione del codice non può proseguire perché VCRUNTIME140_1.dll non è stato trovato. Per risolvere il problema prova a reinstallare il programma."

translated:

The esecution of the code can't go further because VCRUNTIME140_1.dll has not found. For solve the problem try to reinstall the program.

I've tried to redownload the program and same error.

**Comment by BSoDGamingYT** [comment]
You need to install C++ redist 2019 for the latest yuzu versions
https://aka.ms/vs/16/release/VC_redist.x64.exe

**Comment by Kenzo95** [comment]
Thanks, solved
