### ISSUE TITLE
Animal Crossing: New Horizons crash at Launching...

### ISSUE THREAD

**Issue by VirgilFabre** [yuzu-emu/yuzu#3613]
Animal Crossing: New Horizons crash at Launching...
Yuzu version 219
Is there any way to help improve Yuzu so it works? I really want to play this game its killing me

**Comment by BSoDGamingYT** [comment]
This is a low-quality issue that provides no useful information, please close it.

**Comment by SilverBeamx** [comment]
(Sorry for the offtopic)
I agree with BSoD. Also, if you are "itching" so much you should just play it on your Switch. Please remember that the Yuzu team doesn't condone piracy.

**Comment by VirgilFabre** [comment]
Thanks for the support glad you're here to help.
Oh and if I had 700 Canadian $ to spend on a switch don't you think I'd do it?
But I don't. Useless comment.
