### ISSUE TITLE
Yuzu Applet causes black screen

### ISSUE THREAD

**Issue by YourUncleGubsy** [yuzu-emu/yuzu#3615]
Hi, I've been trying to play Smash Ultimate but whenever I select the smash mode the web applet pops up. It says "ERR_FILE_NOT_FOUND" and whenever I attempt to exit the applet either by clicking exit or by hitting the enter key, my screen will go black. The background music changes like normal and sometimes when I press buttons on my controller I can hear things being selected, but the screen is still black. I also get 60fps and 100%/100% speed. I'm probably missing something but if someone can help me that would be great.

**Comment by BSoDGamingYT** [comment]
If you press Enter, the black screen should pass. I'm not sure what causes this issue though

**Comment by qwell** [comment]
I had this happen when I had DLC enabled.  Once I disabled it, it started working just fine.

**Comment by YourUncleGubsy** [comment]
Does DLC not work?

**Comment by xVisery** [comment]
Can confirm it happens the same as you, i tried disbaling DLC as stated above and it didn't work. I just can't access smash mode or anything that makes applets pop up.

**Comment by xVisery** [comment]
y

> Can confirm it happens the same as you, i tried disbaling DLC as stated above and it didn't work. I just can't access smash mode or anything that makes applets pop up.

I managed to get past it somehow, but after choosing a rulseset it goes compeletly black, just audio playing. This started to happen as soon as i tried getting in Stage Builder and for some reason it went black all the time afterwards.

**Comment by xVisery** [comment]
I found a fix, you need to go to the game files (Just go to your save file and head back from there) and delete the stages folder.

**Comment by dokannon** [comment]
> I found a fix, you need to go to the game files (Just go to your save file and head back from there) and delete the stages folder.

hi , where is that?? thankz

**Comment by BruceLeeFan88** [comment]
Any one here know how to stop the random black screens on "Spirits" mode? The game loads and I can hear audio but the screens just black. I was able to get past the first 2 stages.

**Comment by superbros45** [comment]
> stages

i had the same issues here, using intel and gtx 1650

**Comment by DOFsan** [comment]
Ok. Seemingly deleting the "stages" file does help. C:\Users\INSERT YOUR USER NAME\AppData\Roaming\yuzu\nand\user\save\0000000000000000\442330EB594860DE0AF0513A2749CD93\01006A800016E000\save_data\stage  is where the file is. People complain about black screen in world of light mode, then in other modes. What i feel is happening, is somehow world of light CORRUPTS your game. I played for 5 hours with no black screens before i tried world of light. Then, it was a problem every single match until i deleted stages. I know thread is sort of old, but people are still trying to emulate smash.
