### ISSUE TITLE
Smash Crash Navi

### ISSUE THREAD

**Issue by goblino117** [yuzu-emu/yuzu#3616]
When going into a game of smash with a navi card the game will crash. I am using the latest version of yuzu, i can load up smash and navigate the menu fine, i can pick a character and stage but when i press okay to fight it tries to load but then crashes, this happens on both windows 10 and linux, its even worse on linux as it is just black. I was told that this was only for navi cards

**Comment by Hexagon12** [comment]
Please upload a log file. List your complete specs (CPU / GPU / RAM).

**Comment by goblino117** [comment]
> Please upload a log file. List your complete specs (CPU / GPU / RAM).

GPU Rx 5700xt
CPU i7 9700k
16gb DDR4
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4440511/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Please let us know if this still happens to you on newest yuzu version & gpu drivers.
