### ISSUE TITLE
error: GLSL 4.40 is not supported

### ISSUE THREAD

**Issue by joker5bb** [yuzu-emu/yuzu#3617]
Hello,
I am using Linux debian 5.6.1 with the nouveau driver for 
01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GT 750M Mac Edition] (rev a1)

output of yuzu_log.txt
[  39.105025] Render.OpenGL <Critical> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:186: SHADER_COMPILER ERROR 3: 0:2(10): error: GLSL 4.40 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 4.00, 4.10, 4.20, 4.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES
[  39.105041] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadShader:48: Error compiling vertex shader:
0:2(10): error: GLSL 4.40 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 4.00, 4.10, 4.20, 4.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

[  39.105049] Render.OpenGL <Error> ./video_core/renderer_opengl/gl_shader_util.h:LoadProgram:79: Error linking shader:
error: linking with uncompiled/unspecialized shader

**Comment by goldenx86** [comment]
Dude, use an OS from this decade, if possible, with a driver from this decade too.

**Comment by ReinUsesLisp** [comment]
If you are using nouveau you are already probably forcing a compatibility profile. You can override the GLSL version using the `MESA_GLSL_VERSION_OVERRIDE` environment variable.

**Comment by ReinUsesLisp** [comment]
Can you post what the output of this command looks like?
```
$ MESA_GLSL_VERSION_OVERRIDE=440 glxinfo | grep OpenGL
```

**Comment by joker5bb** [comment]
OpenGL vendor string: nouveau
OpenGL renderer string: NVE7
OpenGL core profile version string: 4.4 (Core Profile) Mesa 18.3.6
OpenGL core profile shading language version string: 4.40
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.3 (Compatibility Profile) Mesa 18.3.6
OpenGL shading language version string: 4.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Comment by joker5bb** [comment]
NVIDIA dropped 700M series support in their new drivers, I get 15fps unfortunately. I think there is room for better performance. I would like to see nouveau shine.

**Comment by degasus** [comment]
Mesa 18.3 does not support compatible profile. So may you please update your distribution? Debian is pretty stable, but also outdated. Debian testing should be fine AFAIK.

**Comment by WSLUser** [comment]
debian 5.6.1 is old. Buster is 8. Bullseye is 9 (in testing). Update to one of those.

**Comment by Tachi107** [comment]
You should definitely update your distro, I think that it would solve a lot of issues. I personally use Debian Testing (currently Bullseye, 11), that always gets updated drivers, and never had any issue.
If you don't feel like Testing is a thing for you (but I see no reason why it shouldn't), you can just use the latest stable release, Buster 10.4.
