### ISSUE TITLE
Crash Bandicoot™ N. Sane Trilogy

### ISSUE THREAD

**Issue by joker5bb** [yuzu-emu/yuzu#3625]
The game loads, crashes before level starts in the same place every time.

user@user-MacBookPro:~$ gdb yuzu
GNU gdb (Ubuntu 8.3-0ubuntu1) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from yuzu...
(gdb) run
Starting program: /usr/local/bin/yuzu 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff06bf700 (LWP 2649)]
[New Thread 0x7fffeed47700 (LWP 2650)]
[New Thread 0x7fffee546700 (LWP 2651)]
[New Thread 0x7fffedce3700 (LWP 2652)]
[New Thread 0x7fffed3cf700 (LWP 2653)]
[New Thread 0x7fffeca4e700 (LWP 2654)]
[New Thread 0x7fffd7fff700 (LWP 2655)]
[New Thread 0x7fffd54b5700 (LWP 2656)]
[New Thread 0x7fffcffff700 (LWP 2658)]
[New Thread 0x7fffcf7fe700 (LWP 2659)]
[New Thread 0x7fffceffd700 (LWP 2660)]
[Thread 0x7fffcffff700 (LWP 2658) exited]
[New Thread 0x7fffcffff700 (LWP 2675)]
[New Thread 0x7fffce2d2700 (LWP 2676)]
[Thread 0x7fffcf7fe700 (LWP 2659) exited]
[Thread 0x7fffcffff700 (LWP 2675) exited]
[New Thread 0x7fffcffff700 (LWP 2677)]
[Thread 0x7fffce2d2700 (LWP 2676) exited]
[New Thread 0x7fffce2d2700 (LWP 2678)]
libpng warning: iCCP: known incorrect sRGB profile
[New Thread 0x7fffcf7fe700 (LWP 2679)]
[New Thread 0x7fff32ff7700 (LWP 2680)]
[New Thread 0x7fff327f6700 (LWP 2681)]
[New Thread 0x7fff12e4f700 (LWP 2682)]
[New Thread 0x7fff1254e700 (LWP 2683)]
[New Thread 0x7fff11b7a700 (LWP 2684)]
[New Thread 0x7fff11186700 (LWP 2685)]
[New Thread 0x7ffefbfff700 (LWP 2686)]
[New Thread 0x7ffefb7fe700 (LWP 2687)]
[Thread 0x7fffcf7fe700 (LWP 2679) exited]
[Thread 0x7fff32ff7700 (LWP 2680) exited]
[Thread 0x7fff327f6700 (LWP 2681) exited]
[Thread 0x7fff11b7a700 (LWP 2684) exited]
[Thread 0x7fff12e4f700 (LWP 2682) exited]
[Thread 0x7fff11186700 (LWP 2685) exited]
[Thread 0x7fff1254e700 (LWP 2683) exited]
[Thread 0x7ffefbfff700 (LWP 2686) exited]
[Thread 0x7ffefb7fe700 (LWP 2687) exited]
[Thread 0x7fffcffff700 (LWP 2677) exited]
[New Thread 0x7fffcffff700 (LWP 2691)]
[Thread 0x7fffd54b5700 (LWP 2656) exited]
[New Thread 0x7fffd54b5700 (LWP 2760)]

Thread 16 "EmuThread" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x7fffce2d2700 (LWP 2678)]
0x00005555556d2ef9 in void assert_noinline_call<VideoCommon::Shader::ShaderIR::GetVideoOperand(std::shared_ptr<std::variant<VideoCommon::Shader::OperationNode, VideoCommon::Shader::ConditionalNode, VideoCommon::Shader::GprNode, VideoCommon::Shader::CustomVarNode, VideoCommon::Shader::ImmediateNode, VideoCommon::Shader::InternalFlagNode, VideoCommon::Shader::PredicateNode, VideoCommon::Shader::AbufNode, VideoCommon::Shader::PatchNode, VideoCommon::Shader::CbufNode, VideoCommon::Shader::LmemNode, VideoCommon::Shader::SmemNode, VideoCommon::Shader::GmemNode, VideoCommon::Shader::CommentNode> >, bool, bool, Tegra::Shader::VideoType, unsigned long)::{lambda()#1}>(VideoCommon::Shader::ShaderIR::GetVideoOperand(std::shared_ptr<std::variant<VideoCommon::Shader::OperationNode, VideoCommon::Shader::ConditionalNode, VideoCommon::Shader::GprNode, VideoCommon::Shader::CustomVarNode, VideoCommon::Shader::ImmediateNode, VideoCommon::Shader::InternalFlagNode, VideoCommon::Shader::PredicateNode, VideoCommon::Shader::AbufNode, VideoCommon::Shader::PatchNode, VideoCommon::Shader::CbufNode, VideoCommon::Shader::LmemNode, VideoCommon::Shader::SmemNode, VideoCommon::Shader::GmemNode, VideoCommon::Shader::CommentNode> >, bool, bool, Tegra::Shader::VideoType, unsigned long)::{lambda()#1} const&) [clone .isra.0] ()
(gdb) bt
#0  0x00005555556d2ef9 in void assert_noinline_call<VideoCommon::Shader::ShaderIR::GetVideoOperand(std::shared_ptr<std::variant<VideoCommon::Shader::OperationNode, VideoCommon::Shader::ConditionalNode, VideoCommon::Shader::GprNode, VideoCommon::Shader::CustomVarNode, VideoCommon::Shader::ImmediateNode, VideoCommon::Shader::InternalFlagNode, VideoCommon::Shader::PredicateNode, VideoCommon::Shader::AbufNode, VideoCommon::Shader::PatchNode, VideoCommon::Shader::CbufNode, VideoCommon::Shader::LmemNode, VideoCommon::Shader::SmemNode, VideoCommon::Shader::GmemNode, VideoCommon::Shader::CommentNode> >, bool, bool, Tegra::Shader::VideoType, unsigned long)::{lambda()#1}>(VideoCommon::Shader::ShaderIR::GetVideoOperand(std::shared_ptr<std::variant<VideoCommon::Shader::OperationNode, VideoCommon::Shader::ConditionalNode, VideoCommon::Shader::GprNode, VideoCommon::Shader::CustomVarNode, VideoCommon::Shader::ImmediateNode, VideoCommon::Shader::InternalFlagNode, VideoCommon::Shader::PredicateNode, VideoCommon::Shader::AbufNode, VideoCommon::Shader::PatchNode, VideoCommon::Shader::CbufNode, VideoCommon::Shader::LmemNode, VideoCommon::Shader::SmemNode, VideoCommon::Shader::GmemNode, VideoCommon::Shader::CommentNode> >, bool, bool, Tegra::Shader::VideoType, unsigned long)::{lambda()#1} const&) [clone .isra.0] ()
#1  0x00005555556d2fd7 in VideoCommon::Shader::ShaderIR::GetVideoOperand(std::shared_ptr<std::variant<VideoCommon::Shader::OperationNode, VideoCommon::Shader::ConditionalNode, VideoCommon::Shader::GprNode, VideoCommon::Shader::CustomVarNode, VideoCommon::Shader::ImmediateNode, VideoCommon::Shader::InternalFlagNode, VideoCommon::Shader::PredicateNode, VideoCommon::Shader::AbufNode, VideoCommon::Shader::PatchNode, VideoCommon::Shader::CbufNode, VideoCommon::Shader::LmemNode, Vi--Type <RET> for more, q to quit, c to continue without paging--
deoCommon::Shader::SmemNode, VideoCommon::Shader::GmemNode, VideoCommon::Shader::CommentNode> >, bool, bool, Tegra::Shader::VideoType, unsigned long) [clone .cold] ()
#2  0x0000555555c6cda7 in VideoCommon::Shader::ShaderIR::DecodeVideo(std::vector<std::shared_ptr<std::variant<VideoCommon::Shader::OperationNode, VideoCommon::Shader::ConditionalNode, VideoCommon::Shader::GprNode, VideoCommon::Shader::CustomVarNode, VideoCommon::Shader::ImmediateNode, VideoCommon::Shader::InternalFlagNode, VideoCommon::Shader::PredicateNode, VideoCommon::Shader::AbufNode, VideoCommon::Shader::PatchNode, VideoCommon::Shader::CbufNode, VideoCommon::Shader::LmemNode, VideoCommon::Shader::SmemNode, VideoCommon::Shader::GmemNode, VideoCommon::Shader::CommentNode> >, std::allocator<std::shared_ptr<std::variant<VideoCommon::Shader::OperationNode, VideoCommon::Shader::ConditionalNode, VideoCommon::Shader::GprNode, VideoCommon::Shader::CustomVarNode, VideoCommon::Shader::ImmediateNode, VideoCommon::Shader::InternalFlagNode, VideoCommon::Shader::PredicateNode, VideoCommon::Shader::AbufNode, VideoCommon::Shader::PatchNode, VideoCommon::Shader::CbufNode, VideoCommon::Shader::LmemNode, VideoCommon::Shader::SmemNode, VideoCommon::Shader::GmemNode, VideoCommon::Shader::CommentNode> > > >&, unsigned int) ()
#3  0x0000555555c2717c in VideoCommon::Shader::ShaderIR::DecodeInstr(std::vector<std::shared_ptr<std::variant<VideoCommon::Shader::OperationNode, VideoCommon::Shader::ConditionalNode, VideoCommon::Shader::GprNode, VideoCommon::Shader::CustomVarNode, VideoCommon::Shader::ImmediateNode, VideoCommon::Shader::InternalFlagNode, VideoCommon::Shader::PredicateNode, VideoCommon::Shader::AbufNode, VideoCom--Type <RET> for more, q to quit, c to continue without paging--
mon::Shader::PatchNode, VideoCommon::Shader::CbufNode, VideoCommon::Shader::LmemNode, VideoCommon::Shader::SmemNode, VideoCommon::Shader::GmemNode, VideoCommon::Shader::CommentNode> >, std::allocator<std::shared_ptr<std::variant<VideoCommon::Shader::OperationNode, VideoCommon::Shader::ConditionalNode, VideoCommon::Shader::GprNode, VideoCommon::Shader::CustomVarNode, VideoCommon::Shader::ImmediateNode, VideoCommon::Shader::InternalFlagNode, VideoCommon::Shader::PredicateNode, VideoCommon::Shader::AbufNode, VideoCommon::Shader::PatchNode, VideoCommon::Shader::CbufNode, VideoCommon::Shader::LmemNode, VideoCommon::Shader::SmemNode, VideoCommon::Shader::GmemNode, VideoCommon::Shader::CommentNode> > > >&, unsigned int) ()
#4  0x0000555555c2843f in VideoCommon::Shader::ShaderIR::Decode() ()
#5  0x0000555555c09781 in VideoCommon::Shader::ShaderIR::ShaderIR(std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned int, VideoCommon::Shader::CompilerSettings, VideoCommon::Shader::Registry&) ()
#6  0x0000555555bd49e8 in OpenGL::CachedShader::CreateStageFromMemory(OpenGL::ShaderParameters const&, Tegra::Engines::Maxwell3D::Regs::ShaderProgram, std::vector<unsigned long, std::allocator<unsigned long> >, std::vector<unsigned long, std::allocator<unsigned long> >) ()
#7  0x0000555555bd54c2 in OpenGL::ShaderCacheOpenGL::GetStageProgram(Tegra::Engines::Maxwell3D::Regs::ShaderProgram) ()
#8  0x0000555555bbd629 in OpenGL::RasterizerOpenGL::SetupShaders(unsigned int)
    ()
#9  0x0000555555bbe30c in OpenGL::RasterizerOpenGL::Draw(bool, bool) ()
--Type <RET> for more, q to quit, c to continue without paging--
#10 0x0000555555b68899 in Tegra::Engines::Maxwell3D::FlushMMEInlineDraw() ()
#11 0x0000555555b69c48 in Tegra::Engines::Maxwell3D::CallMethod(Tegra::GPU::MethodCall const&) ()
#12 0x0000555555b66a77 in Tegra::DmaPusher::DispatchCalls() ()
#13 0x0000555555ac00df in Service::Nvidia::Devices::nvhost_gpu::SubmitGPFIFO(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> >&) ()
#14 0x0000555555ac086e in Service::Nvidia::Devices::nvhost_gpu::ioctl(Service::Nvidia::Devices::nvdevice::Ioctl, std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<unsigned char, std::allocator<unsigned char> >&, Service::Nvidia::IoctlCtrl&, Service::Nvidia::IoctlVersion) ()
#15 0x00005555559aa12a in Service::Nvidia::NVDRV::IoctlBase(Kernel::HLERequestContext&, Service::Nvidia::IoctlVersion) ()
#16 0x00005555559aaa0b in Service::Nvidia::NVDRV::Ioctl(Kernel::HLERequestContext&) ()
#17 0x00005555559b2ec5 in Service::ServiceFrameworkBase::HandleSyncRequest(Kernel::HLERequestContext&) ()
#18 0x00005555558f06d3 in Kernel::ServerSession::CompleteSyncRequest() ()
#19 0x0000555555813a2e in Core::Timing::CoreTiming::Advance() ()
#20 0x0000555555a19dc9 in Core::CoreManager::RunLoop(bool) ()
#21 0x0000555555814b5c in Core::CpuManager::RunLoop(bool) ()
--Type <RET> for more, q to quit, c to continue without paging--
#22 0x000055555580e1b2 in Core::System::RunLoop(bool) ()
#23 0x0000555555740409 in EmuThread::run() ()
#24 0x00007ffff6c17c92 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff77fd669 in start_thread (arg=<optimized out>)
    at pthread_create.c:479
#26 0x00007ffff6733323 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) quit
A debugging session is active.

	Inferior 1 [process 2645] will be killed.

Quit anyway? (y or n) y

**Comment by FernandoS27** [comment]
You need Ignore Asserts for non development builds: https://github.com/yuzu-emu/yuzu/pull/1340
