### ISSUE TITLE
Super Smash Bros Ultimate crashing on Linux startup

### ISSUE THREAD

**Issue by mulukou** [yuzu-emu/yuzu#3626]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4452807/yuzu_log.txt)

Have tried changing from vulkan-radeon to amdvlk, with async and without async. Also tried with swap on and off, never used more than 30% of my RAM

My Specs: 
CPU:Ryzen 7 1800x
RAM: 2x 8GB 3333mhz
GPU: Radeon HD 7970

**Comment by ReinUsesLisp** [comment]
You have to disable asserts to run Smash Ultimate.

**Comment by ReaperOfSouls1909** [comment]
add the chaotic-aur repo and do sudo pacman -S yuzu-mainline-git

**Comment by mulukou** [comment]
using the chaotic-aur to download the yuzu-mainline didnt work, but downloading through yay worked, now I can get ingame, thanks for the help (if anyone else looks through this issue, i was using yuzu-git before)
