### ISSUE TITLE
System error

### ISSUE THREAD

**Issue by vinnyg0621** [yuzu-emu/yuzu#3628]
Log: 
//You're mean.
The code execution can't proceed because VCRUNTIME140_1.dll wasn't found. Reinstalling the program may fix this problem.

What do I do???

**Comment by vinnyg0621** [comment]
When I try to load the program, it keeps giving me the error message I forgot to say

**Comment by Zeroksas** [comment]
Reinstall Microsoft Visual C++ redistributable.

**Comment by Hexagon12** [comment]
[Follow the FAQ.](https://github.com/yuzu-emu/yuzu/wiki/FAQ#yuzu-starts-with-the-error-vcruntime140_1dll-was-not-found)
