### ISSUE TITLE
SMO Drop low FPS Yuzu EA 330

### ISSUE THREAD

**Issue by mytique38** [yuzu-emu/yuzu#3629]
Hello Team, 

I have an issue with SMO with Yuzu EA 330

My configuration 

-i5 8600K
-32 GB DDR4
-GTX 1660 ti 
-SSD M2 970 Pro 
-Last Windows 10x64  and Nvidia drivers 

The game run well @60 fps but at the moment in game I have a drop fps I configure my Nvidia control panel (setting bsod gaming YouTube) and power plan windows and I use mod SMO 

Disable dynamic and low end mod

I tried with a shared cache found on the internet (complete game) but when I drop file shared cache on correct location it there it gets overwritten and creates a new file.

Any idea to run 60 FPS constant ? 

Thanks

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
