### ISSUE TITLE
i cant even install yuzu!pls help!

### ISSUE THREAD

**Issue by tzabass** [yuzu-emu/yuzu#3632]
when i try to install yuzu ,always i see this issue!
Error while sending HTTP request: Error(Io(Custom { kind: TimedOut, error: "timed out" }), "https://api.github.com/repos/yuzu-emu/yuzu-mainline/releases")
pls help me!

**Comment by ExsertWizard** [comment]
You internet is too slow to connect to Github servers. Use a VPN and try again.

In the future, please ask for help in the yuzu Discord server instead, this place is for issues regarding the code.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum. Please use our Discord for support requests. Thanks

**Comment by MierLu** [comment]
> 您的互联网速度太慢，无法连接到Github服务器。请使用 VPN，然后重试。
> 
> 将来，请在柚子 Discord 服务器中寻求帮助，这个地方是关于代码的问题。
连接VPN下载速度也很慢，安装发生错误Failed to read resource: Custom (kind: TimedOut, error: "timed out")
youtube看4k都没问题

**Comment by MierLu** [comment]
> when i try to install yuzu ,always i see this issue! Error while sending HTTP request: Error(Io(Custom { kind: TimedOut, error: "timed out" }), "https://api.github.com/repos/yuzu-emu/yuzu-mainline/releases") pls help me!

Install Watt Toolkit to start the github script to speed up the test
