### ISSUE TITLE
Super Smash Bros. Ultimate softlock on EA 346+ in Linux

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#3639]
Since EA 346, SSBU began to softlock (i.e. ~9000% speed) in a couple places in the game. First, it locks immediately out of the splash screen. This can be bypassed if the Boot to Menu mod is installed (can be found in the #game-mods channel on the Discord server), then the game will play normally until after a round ends and it loads the map selection screen, where in the black transition it will most likely lock. The softlock is NOT present in EA 344, and I did not get a chance to download 345.

I tested first on my computer:
Manjaro Linux 19.0.2
Kernel 5.6.2-arch1-1-vfio
AMD Ryzen 7 2700X 8C/16T
16GB 3200MHz Memory @ 3400MHz (stable OC, tested with memtest86+)
GTX 980 Ti 440.64

Later I tried in VMs:
Manjaro Linux 19.0.2
Kernel 5.4.31-1-MANJARO
host-passthrough 8 core CPU (thus same CPU extensions as host)
12GB Memory
GTX 970 440.82
and
Xubuntu 20.04 Daily Build
Kernel 5.4.0-21-generic
host-passthrough 8 core
8GB Memory
GTX 970 440.64

I replicated the softlock on all machines. I tried different combinations of Vulkan/OpenGL/asynchronous GPU, but they all produce softlocks. RAM usage was around 4.5 GB at the time of the lock. The stage loaded prior to the softlock did not seem to reliably affect its occurrence, however playtime did (the longer the match, the more likely the softlock).

**Comment by lat9nq** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4464164/yuzu_log.txt)
Forgot the log! And I will retest my memory OC tomorrow just to be sure.

**Comment by FearlessTobi** [comment]
Seems to be an issue with NRO loading.

**Comment by lat9nq** [comment]
I played Link's Awakening for an hour on my computer today and had no issues in EA 348, but this issue still persists in SSBU. Link's Awakening was running with the No DOF Blur and Softlock Fixes mods enabled.

I also confirmed that my memory OC is stable in Memtest86 (couldn't get Memtest86+ running). It's been a while since I last did a test.

**Comment by bunnei** [comment]
I pushed a fix today, should be available in EA 377+ (whenever this is available, hopefully within an hour). Thanks for reporting this -- please confirm the fix works for you.

**Comment by lat9nq** [comment]
EA 377 fixes the soft lock in SSBU in Linux. Thank you @bunnei and everyone else on the Yuzu team! You guys rock!
