### ISSUE TITLE
Kirby Star Allies - Shading on Kirby and plants broken since mainline 214

### ISSUE THREAD

**Issue by Its-Rei** [yuzu-emu/yuzu#3640]
I bisected this yesterday after it was noticed by @slashiee 

The shading on Kirby and flowers/trees etc. is broken.

Mainline 213
![213](https://user-images.githubusercontent.com/61669744/79040182-eb623d80-7be6-11ea-9b4e-a87ef316a542.png)

Mainline 214
![214](https://user-images.githubusercontent.com/61669744/79040183-f0bf8800-7be6-11ea-9148-4a533895ca87.png)

**Comment by KChunStry** [comment]
Same

**Comment by Its-Rei** [comment]
confirmed fixed by #3749

**Comment by Hexagon12** [comment]
The issue can be closed when the PR gets merged.
