### ISSUE TITLE
Compilation terminated on building mainline

### ISSUE THREAD

**Issue by joker5bb** [yuzu-emu/yuzu#3641]
user@user-MacBookPro:~/yuzu-mainline/build$ make 
[  0%] Built target unicorn-build
[  0%] Built target fmt
[  9%] Built target dynarmic
[  9%] Built target glad
[  9%] Built target inih
[ 10%] Built target SoundTouch
[ 17%] Built target opus
[ 19%] Built target sirit
[ 21%] Built target libzstd_static
[ 21%] Built target lz4_static
[ 23%] Built target common
[ 56%] Built target crypto
[ 58%] Built target ssl
[ 59%] Built target tls
[ 59%] Built target lurlparser
[ 59%] Built target web_service
[ 62%] Built target mbedcrypto
[ 63%] Built target mbedx509
[ 64%] Built target mbedtls
[ 64%] Built target speex
[ 65%] Built target cubeb
[ 66%] Built target z
[ 72%] Built target zip
[ 80%] Built target video_core
[ 80%] Built target audio_core
[ 95%] Built target core
[ 96%] Built target input_common
[ 96%] Built target tests
[ 96%] Built target yuzu-cmd
[ 96%] Built target yuzu-tester
[ 96%] Automatic MOC and UIC for target yuzu
[ 96%] Built target yuzu_autogen
[ 96%] Building CXX object src/yuzu/CMakeFiles/yuzu.dir/bootmanager.cpp.o
/home/user/yuzu-mainline/src/yuzu/bootmanager.cpp:19:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   19 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/yuzu/CMakeFiles/yuzu.dir/build.make:271: src/yuzu/CMakeFiles/yuzu.dir/bootmanager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2821: src/yuzu/CMakeFiles/yuzu.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by Hexagon12** [comment]
I see that you're trying to compile on Mac. Building on macOS is currently experimental and it will not build with the current code. Check if it builds with #3593, if it does not, please report the issue in that PR.

**Comment by joker5bb** [comment]
> I see that you're trying to compile on Mac. Building on macOS is currently experimental and it will not build with the current code. Check if it builds with #3593, if it does not, please report the issue in that PR.

Im running Ubuntu bro, not an opengl issue

**Comment by joker5bb** [comment]
Apparently there is a new dependence for ubuntu 
qtbase5-private-dev

**Comment by asbestosjuulpod** [comment]
This also goes for Debian Sid. Fixed by installing qtbase5-private-dev.
