### ISSUE TITLE
Zelda Link's Awakening - locks with unmapped read32 on save select screen with vulkan api

### ISSUE THREAD

**Issue by Its-Rei** [yuzu-emu/yuzu#3642]
I've traced this back all the way to mainline 153 which introduced vulkan to the mainline builds. The issue happens with all of them with vulkan. Open GL is fine (at least with Nvidia).

Once you get to the save select screen right after the title screen these errors are thrown:
`[ 255.886102] Debug <Critical> core\memory.cpp:Read:630: Assertion Failed! Mapped memory page without a pointer @ 00000020BA0B4030`

It will then get stuck spamming unmapped Read64 and 32 and lock up. Sometimes it takes a few instaces of mapped memory page without a pointer like in this screenshot:

![ZLA_unmapped_read](https://user-images.githubusercontent.com/61669744/79044358-ef04bd00-7c04-11ea-9afe-aa182183890a.png)

Here's also one example log. (I truncated the 27k unmapped read lines in the end to make it smaller)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4464641/yuzu_log.txt)

EDIT: to clarify, this only happens on the save select screen. If you quickly press A and select a save as soon as the screen comes up the game will work fine. If you stay on the save select screen, yuzu will lock as decribed above eventually. Sometimes it takes 20+ seconds to lock but often it is within seconds of the save select screen being displayed.

**Comment by MysticExile** [comment]
Fixed
