### ISSUE TITLE
Super Mario Odyssey - Regression, display error in Wooded Kingdom since mainline 223

### ISSUE THREAD

**Issue by Its-Rei** [yuzu-emu/yuzu#3647]
The lighting/mist in Wooded Kingdom displays in moving horizontal lines since mainline 223.

Both OpenGL and Vulkan, async and without async are affected. Early Access as well.

Mainline 222
![222](https://user-images.githubusercontent.com/61669744/79071683-51c98780-7cdd-11ea-8ddd-30468de0bf8b.png)

Mainline 223
![223](https://user-images.githubusercontent.com/61669744/79071689-59892c00-7cdd-11ea-8c18-4274286c5a33.png)

**Comment by FernandoS27** [comment]
The issue has been identified, a fix will be deployed soon.

**Comment by FernandoS27** [comment]
Fixed by #3649.
