### ISSUE TITLE
BotW + async gpu system memory overallocation and VRAM shared memory leak on NVIDIA Turing GPUs

### ISSUE THREAD

**Issue by Morph1984** [yuzu-emu/yuzu#3650]
<meta name="titleids"  content="01007EF00011E000">

After the fixes from #3646, BotW was able to go in game past the title/loading screen with async gpu. However, with it enabled, the "Committed" memory and GPU shared memory (both shown in task manager) increases until the emulator crashes.

This issue can only be replicated with an NVIDIA Turing based GPU (GTX 16 series, RTX 20 series) with asynchronous GPU enabled. Occurs on both OpenGL/Vulkan. Other generations of NVIDIA gpus such as Pascal / Maxwell v2 are not affected.

![image](https://user-images.githubusercontent.com/39850852/79086020-a0404b80-7d08-11ea-828b-1d05fba6fb62.png)

![image](https://user-images.githubusercontent.com/39850852/79086035-ae8e6780-7d08-11ea-9cf1-724a0a8b1ca9.png)

logfile:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4467676/yuzu_log.zip)

**Comment by Morph1984** [comment]
Fixed between EA 438 and 443

**Comment by Morph1984** [comment]
Reopening as `Fast GPU Time` is a hack

**Comment by Sciroccogti** [comment]
There's still memory leak while the `Fast GPU Time` is open.

**Comment by FabrizioTedoldi** [comment]
df
tjdxtjx

**Comment by v1993** [comment]
Was this fixed by project reaper?

**Comment by labib2002** [comment]
is this fixed yet ? @Morph1984

**Comment by Morph1984** [comment]
Since I no longer have a Turing gpu to verify this with, and it being over 2 years since the issue occurred, this is very likely fixed by multiple rewrites to various aspects of GPU emulation.
Closing.

**Comment by Alfyar** [comment]
where or how can i download roms for yuzu ?? in all the sites i was tryed doesn't work
