### ISSUE TITLE
Animal Crossing New Horizons crash on startup

### ISSUE THREAD

**Issue by CJBok** [yuzu-emu/yuzu#3652]
![image](https://user-images.githubusercontent.com/3213428/79113527-69f2e280-7d81-11ea-851d-f6add4d101b8.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4469106/yuzu_log.txt)

**Comment by goblino117** [comment]
animal crossing is only for ryujinx rn and it doesnt seem like yuzu has any plans to add animal crossing

**Comment by callmenemo491** [comment]
i believe the "BypassBootCrash" mod is what you need and/or update yoru ACNH to 1.2.0.
https://yuzu-emu.org/game/animal-crossing-new-horizons/

**Comment by CJBok** [comment]
> i believe the "BypassBootCrash" mod is what you need:
> https://yuzu-emu.org/game/animal-crossing-new-horizons/

Which is a temporary work-around.

**Comment by IamCharliezard** [comment]
> i believe the "BypassBootCrash" mod is what you need:
> https://yuzu-emu.org/game/animal-crossing-new-horizons/

I can't find this mod at the link you sent. Is there anywhere else it might be?

**Comment by FearlessTobi** [comment]
This issue should be long fixed by now.
