### ISSUE TITLE
Shader Cache folder isnt being created

### ISSUE THREAD

**Issue by TitanTigger** [yuzu-emu/yuzu#3658]
Im running yuzu **Early Access 347**. I have changed the settings to use disk shader cache but in my \AppData\Roaming\yuzu **there is no shader folder**. So Super Smash Ultimate and other games arent running all to well. 
My GPU is an AMD rx5700xt.
I recently reinstalled everything thats why my Log file is quite empty.
Heres my LOG:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4476524/yuzu_log.txt)

I have tried turning the setting on and off multiple times

Thanks Alot!

**Comment by mariobro1233** [comment]
You disabled "use shader cache"

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by TitanTigger** [comment]
[  39.737507] Config <Info> core\settings.cpp:LogSetting:80:
Renderer_UseDiskShaderCache: true

shows that I have it enabled

**Comment by goldenx86** [comment]
If you are using Vulkan, it doesn't generate a cache for now.
