### ISSUE TITLE
Ram "Issue" since Animal Crossing update

### ISSUE THREAD

**Issue by turkeynaruto** [yuzu-emu/yuzu#3669]
Maybe this is even intended by you then just close it here but since that update the Ram usage is not normal anymore in every game for me. 
It fills up to my whole 16GB and then empties himself and goes to like 5GB ram usage and sometimes ingame it goes up again and then empties itself again and is normal again. 
Because of that I cant use for example Parsec anymore to stream the Emulator, because when I try to use Parsec the Ram usage goes insanly high again and Programms like parsec cant work right anymore. 

Here are Videos which demonstrate the Problem: 
Yuzu EA 360: https://streamable.com/97pqik
Yuzu EA 365: https://streamable.com/naqlm0

**Comment by FernandoS27** [comment]
Shader Compiling memory usage is unoptimized, we are working on it.
