### ISSUE TITLE
OpenGL shaders consume large amounts of memory on EA

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#3690]
I could not track down the exact EA build, since I did not download any EAs on April 14, but sometime between 20200413-ac26e0ced and 20200415-96595dd43, during the loading process, shaders began consuming larger amounts of memory. Below I recorded the system RAM usage needed to enter the main menu in Smash Ultimate.

SSBU with approximately 5000 shaders cached:
EA 20200413-ac26e0ced: 3.5 GB
EA 20200415-96595dd43: 8.1 GB
Current mainline 7e4a132a7: 6.9 GB
The most recent EA I have, 20200415-db13fcdfb (377): 8.2 GB

SSBU with 0 shaders cached:
EA 20200413-ac26e0ced: 2.0 GB
EA 20200415-96595dd43: 2.0 GB
Mainline 7e4a132a7: 4.1 GB
EA 20200415-db13fcdfb (377): 2.0 GB

Unfortunately I don't have other games with currently large shader caches to test with. I was running SSBU with OpenGL and async on. My specs are:
Manjaro Linux 19.0.2
Kernel 5.6.3-arch1-1-vfio
Ryzen 7 2700X
16GiB DDR4 3400 MHz
GTX 980 Ti (440.82)

Currently my Windows 10 VM only has  8 GB of RAM, and does not boot SSBU some of these situations in a timely manner, so I did not test on Windows. However an exacerbated case of the shaders causing horrid RAM usage may be found [here](https://discordapp.com/channels/398318088170242053/476077620350418964/700212958382391336) in #patreon-support.

I am happy to test other EAs if I have them. The earliest EA I have is 308. Let me know which log I should upload, or if there is any other information you might need.

**Comment by lat9nq** [comment]
EA 20200416-e242ec490 (385) requires 9.5 GB to enter the main menu in SSBU with 5000 shaders loaded after recreating the precompiled archive ([yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4485427/yuzu_log.txt)). 8.7 GB with precompiled shaders ([yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4485442/yuzu_log.txt)), and 2.4 GB with 0 shaders ([yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4485449/yuzu_log.txt)).

I forgot to mention in the original post that the Boot to menu mod was enabled since I cannot enter the main menu in some of those builds without it (fixed in EA 377). For this post, I disabled the mod.

**Comment by lat9nq** [comment]
I've been advised to @bunnei, which I should have done originally.

**Comment by turkeynaruto** [comment]
[https://github.com/yuzu-emu/yuzu/issues/3669](url) 

I mentioned that here too its like the new Ram reducing implementation aint working right anymore

**Comment by lat9nq** [comment]
The revert in PR #3703 prevents this issue.
