### ISSUE TITLE
Performance regression on Vulkan since yuzu 215 (Super Mario Odyssey)

### ISSUE THREAD

**Issue by Emogop** [yuzu-emu/yuzu#3691]
i3 6100 @ 4,5 Ghz
16 Gb Ram
GTX 1060 442.88 (vulkan 1.2)
I updated my graphics card drivers, thought the problem was there, but turned out it wasn't.

![Screenshot_303](https://user-images.githubusercontent.com/42875723/79459097-6f5b6180-7ffb-11ea-99ea-3ae243860367.png)
![Screenshot_304](https://user-images.githubusercontent.com/42875723/79459102-71252500-7ffb-11ea-9413-ce2fde751c9d.png)

**Comment by FernandoS27** [comment]
We cannot seem to find anything unusual between those two versions.

**Comment by Emogop** [comment]
Also CPU load has significantly increased at the same time, from 48-55 percent in 214 to 78-83 percent in 215 and on.

**Comment by ReinUsesLisp** [comment]
I get the same performance on both yuzu Mainline 214 and 215.

**Comment by Emogop** [comment]
I'm pretty sure I got this right. Also two more people thumbed up my post, so it seems I'm not alone with this issue.
Moreover, the increased CPU load has something to do with it. So limiting number of cores / threads in BIOS or task manager should reveal it.

**Comment by goldenx86** [comment]
Tested it with my Vega 11, saw no difference, same area as the screenshot.

**Comment by Its-Rei** [comment]
tested this as well with GTX 970 and newest nvidia drivers, same area as the screenshot. Exact same FPS and frame time in both 214 and 215.

**Comment by Morph1984** [comment]
This issue has been reported to be fixed, closing.
