### ISSUE TITLE
Yuzu Early Access 390 - Just Shapes & Beats Does Not Render Properly and inputs will randomly occur when there is no input from the user on menu's and even in game

### ISSUE THREAD

**Issue by AlternatePeace** [yuzu-emu/yuzu#3701]
My Pc has a Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz and I am Using Yuzu 390

When attempting to play Just shapes and beats the menu and everything except for the game studios intro loads correctly. But when you get to the menu and start giving inputs it will freak out giving random inputs that are not coming from the user. Also if you manage to get into a game it loads almost correctly with a couple sounds not rendering as your hurt sound does not load. If you try the story mode the game just becomes an unplayable mess with the camera being what appears to be not fitting the screen correctly and if you somehow manage to get on top of a level the audio breaks making a pixelish noise of a dying cat. You can try to get into a level by playing in party mode but its going to be hard with the random inputs occurring. 

If i missed any issues let me know and please fix this.

**Comment by Hexagon12** [comment]
Please test this game on mainline releases and upload a log file from it.

**Comment by AlternatePeace** [comment]
> Please test this game on mainline releases and upload a log file from it.

I tested it on a main build and it does the exact same bug's and for some reason my log file wont update

**Comment by SilverBeamx** [comment]
You have to close the emulator, otherwise the log won't be flushed to file.

**Comment by AlternatePeace** [comment]
> You have to close the emulator, otherwise the log won't be flushed to file.

I did close the Emulator, if you want to get a log file I wont be able to so your going to need to do it yourselves

**Comment by AlternatePeace** [comment]
> You have to close the emulator, otherwise the log won't be flushed to file.

i messed up and accidentally closed the issue

**Comment by AlternatePeace** [comment]
> You have to close the emulator, otherwise the log won't be flushed to file.

and yes i did do that and it still did not update

**Comment by PacoAvelar** [comment]
This has been solved, now it renders properly and no fake inputs are registered,
Tested on Yuzu EA - 1855
