### ISSUE TITLE
Rom not working

### ISSUE THREAD

**Issue by Farty1** [yuzu-emu/yuzu#3705]
I finally got a rom that actually appears in the directory (Pokemon Mystery Dungeon DX) but after it finishes loading the screen remains black and nothing happens. 
please advise.

**Comment by ExsertWizard** [comment]
This is an issue tracker for developers and not a support forum. Please use our Discord for support requests. Thanks

**Comment by goldenx86** [comment]
We don't offer support on piracy, and this isn't the place for troubleshooting.
Go to the Discord server for help.
