### ISSUE TITLE
Luigi's Mantion 3 doesn't work

### ISSUE THREAD

**Issue by JoseGuzmanHN** [yuzu-emu/yuzu#3722]
**Luigi Mantion 3 doesn't work**

Yuzu version 220
I'm using PS4Windows v2.0.16 for my PS4 DualShock Controller

PC Specs
- CPU:	AMD Ryzen 7 2700 Eight-Core Processor 
- RAM:	16GB DDR4
- GPU:	NVIDIA GeForce GTX 1050 Ti
- MB:	Gigabyte B450 I AORUS PRO WIFI-CF

![image](https://user-images.githubusercontent.com/22600113/79677918-2e0db200-81b3-11ea-9929-96de9ae6443a.png)

![image](https://user-images.githubusercontent.com/22600113/79677858-a162f400-81b2-11ea-8917-1ee5ef527bb8.png)

Logs

`[  74.384108] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[  74.384134] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:503: (STUBBED) called
[  74.404908] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:503: (STUBBED) called
[  74.404912] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[  74.404913] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[  74.404965] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:503: (STUBBED) called
[  74.595754] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:503: (STUBBED) called
[  74.595759] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[  74.595760] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[  74.595855] Service.HID <Warning> core\hle\service\hid\controllers\npad.cpp:VibrateController:503: (STUBBED) called
[  74.612237] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:397:     RomFS: Update (v0.4.0) applied successfully
[  74.614202] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:397:     RomFS: Update (v0.4.0) applied successfully
[  75.324126] Debug <Critical> core\hle\service\vi\vi.cpp:TransactParcel:592: Assertion Failed! Unimplemented
[  75.326974] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1329: (STUBBED) called, result=0x00000272
[  75.327416] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:628: Signalling debugger, PANIC! info1=0x0000002287FFF7C8, info2=0x0000000000000004
[  75.327419] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:operator ():609: debug_buffer_err_code=272
[  75.327425] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:679: Emulated program broke execution! reason=0x0000000000000000, info1=0x0000002287FFF7C8, info2=0x0000000000000004
[  75.327427] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:201: Backtrace, sp=000000000000000E, pc=000000000A087BA8
[  75.327429] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:203: Module Name         Address             Original Address    Offset              Symbol
[  75.327429] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:204:
[  75.401318] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: subsdk0             00000071001801E8    0000000009E891E8    00000000001801E8    _ZN2nn4diag6detail5AbortEPKNS_6ResultE
[  75.401326] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: subsdk0             000000710017ED38    0000000009E87D38    000000000017ED38    _ZN2nn4diag6detail10VAbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoERKNS0_14MetaLogContextES3_St9__va_list
[  75.401328] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: subsdk0             000000710017EE04    0000000009E87E04    000000000017EE04    _ZN2nn4diag6detail9AbortImplEPKcS3_S3_iPKNS_6ResultES3_z
[  75.401329] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: subsdk0             000000710033C744    000000000A045744    000000000033C744    _ZN2nn6result6detail17OnUnhandledResultENS_6ResultE
[  75.401330] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: subsdk0             000000710033C75C    000000000A04575C    000000000033C75C    _ZN2nn6result6detail18ConvertInvalidImplENS_6ResultE
[  75.401331] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: subsdk0             00000071003ABEB0    000000000A0B4EB0    00000000003ABEB0    _ZN2nn2vi16ListFrameHistoryEPNS0_9FrameInfoEiPKNS0_5LayerE
[  75.401333] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: main                0000007100B6B1F0    0000000008B791F0    0000000000B6B1F0
[  75.401334] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: main                0000007100470340    000000000847E340    0000000000470340
[  75.401335] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: main                000000710078DB84    000000000879BB84    000000000078DB84
[  75.401336] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: main                0000007100798D44    00000000087A6D44    0000000000798D44
[  75.401337] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: main                0000007100798A34    00000000087A6A34    0000000000798A34
[  75.401338] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: main                0000007100B4E358    0000000008B5C358    0000000000B4E358    nnMain
[  75.401340] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: subsdk0             0000007100296C98    0000000009F9FC98    0000000000296C98    _ZN2nn4init5StartEmmPFvvES2_
[  75.401341] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:209: rtld                00000071000000BC    00000000080000BC    00000000000000BC
[  75.401412] Debug <Critical> core\hle\kernel\svc.cpp:Break:686: Assertion Failed!
[  75.401415] Debug <Critical> core\hle\kernel\process.cpp:operator ():254: Assertion Failed! Exiting processes with non-waiting threads is currently unimplemented`

**Comment by ReaperOfSouls1909** [comment]
![image](https://user-images.githubusercontent.com/18043258/79678416-b8fda500-81d1-11ea-9ae8-93bf732de278.png)
turn that update off and next time ask in the discord

**Comment by ReaperOfSouls1909** [comment]
if you want to run 1.3.0 Try EA 390 or newer

**Comment by Hexagon12** [comment]
Closing in favor of #3723
