### ISSUE TITLE
Please help!!! [3589.672946] Debug <Critical> video_core\shader\decode.cpp:DecodeInstr:287: Assertion Failed! Unhandled instruction: 0

### ISSUE THREAD

**Issue by mila215** [yuzu-emu/yuzu#3728]
shader cache is failing.... Help me please !!!

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4499959/yuzu_log.zip)

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by FernandoS27** [comment]
Fix is already in EA. a few more days of testing and it will be on mainline.

Also 2 things, this issue didn't happen about 50 versions ago so you want to get an older version.
2nd use OpenGL for that game in AMD. It runs just as great with OpenGL in that specific game.

**Comment by mila215** [comment]
Thank you guys, its been 2 weeks trying to get yuzu to work and finaly 3 days ago it started working cant stop now ;).  
ill try fernandos way first then Hexagon

**Comment by RenanZX** [comment]
I'm having the same issue in mainline build with Mario Kart 8.
