### ISSUE TITLE
YUZU.exe crashes directly after showing up an empty window with build no for 2s.

### ISSUE THREAD

**Issue by ct-soft** [yuzu-emu/yuzu#3737]
YUZU.exe crashes directly after showing up an empty window with build no for 2s. No error message displayed. Nothing in log files. Exactly this, nothing more, nothing less. On an Wintel10 x64 i7 16GB with GeForce GT 610. No matter which version I try the actual 233 oder the early build 390 - no difference at all. What is this?

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by ct-soft** [comment]
lol, top answer @Hexagon12
