### ISSUE TITLE
Yuzu crashes when starting any application due to nullptr

### ISSUE THREAD

**Issue by reanimus** [yuzu-emu/yuzu#3740]
Whenever I attempt to launch any software, I'm getting an exception that causes a crash:

```
**Common::VirtualBuffer<enum Common::PageType>::operator[]**(...) returned nullptr.
```

The log leading up to the crash is at https://pastebin.com/1RWMpDKe and a stack trace is at https://pastebin.com/xCaQ53Jz. I've confirmed this occurs with both yuzu and yuzu-mainline, commits 4932010c6f5fc5f2d0c78e69285eaccd64a32c0f and 4af522e4a5698edc53b7e506867be4f3d8713991 respectively.

System Specifications:
  Processor: Intel Core i7-6700K
  RAM: 32GB
  Motherboard: MSI Z170A GAMING M7 (MS-7976)
  Video Card: ASUS DUAL RTX 2080 Super EVO OC

**Comment by Hexagon12** [comment]
Please test if this happens on the precompiled mainline release.

**Comment by reanimus** [comment]
I built these versions because it happens on the precompiled releases. On those it manifests as a crash with no error or exception message. It just crashes. I had to compile my own binary in order to even get a stack trace or useful exception message. The precompiled binaries just result in a truncated log file.

**Comment by reanimus** [comment]
(I also asked and posted this info on the discord support channel but that didn't go anywhere so I'm posting here)

**Comment by Qufyy** [comment]
I was having the same issue but they released an update today and it's all good now

**Comment by reanimus** [comment]
No longer occurs, closing this.
