### ISSUE TITLE
Unable to set Analog sticks properly using GC Adapter w/ controller.

### ISSUE THREAD

**Issue by xVisery** [yuzu-emu/yuzu#3743]
When trying to play Smash Bros. Ultimate with a GC Adapter and a GC controller I have a problem trying to use the "Set Analog Sticks" option. For some reason after setting it up by moving the left joystick from horizontal to vertical and trying it in game, horizontal (left & right) moves on the menu up and down and i'm unable to move left and right.

I went head to training mode using a PS4 controller and with no surprise it worked perfectly. With the PS4 controller i could do precise movemnet like walking and dashing whenever i want, then i switched to the GC controller, only thing i could do was walking and i couldn't crouch or use the Tap Jump option.

The same things happens with the right stick.

Gamecube Controller layout after setting analog sticks:
![image](https://user-images.githubusercontent.com/63909838/79777839-d92e8080-8305-11ea-9b62-02eda1ad7d51.png)

PS4 controller layout after setting analog sticks:
![image](https://user-images.githubusercontent.com/63909838/79777990-0bd87900-8306-11ea-901d-c9d43f06485a.png)

Video using a PS4 controller, i can dash, walk and move precisly:
https://youtu.be/p6Ez5o7E06Y

Video with GC Controller/Adapter, notice how i sometimes fail to set the analog settings correctly because it's setting completly diffrent axis for no reason, can happen with the right stick too:
https://youtu.be/dfDNhzDKIy8

In the GC Controller video, you can notice sometimes i don't move at all, that's me trying to move the joysticks but it does nothing even though it shows the sticks are set.

GoldenX86 did tell me to try and use X360ce and set binds there and then try to set the analog sticks using that but i tried everything i could and it just made everything worse on my end.

I know it isn't an issue with the adapter nor my controller since Smash Wii U works perfectly on Cemu and dolphin works perfectly with the same set up. 
 
Hope this is something that can be fixed with ease, thanks for all your efforts!

**Comment by xVisery** [comment]
Also, while trying to bind the L and R buttons with the gamecube Instead of button 4 and 5 i get Axis 3-,3+, 4- or 4+, i really don't understand.

**Comment by ichronox** [comment]
Hello, did you sort this out ? 

I have not been able to configure my Original GC controller + Official Nintendo GC Adapter on Yuzu, (no inputs detected when trying to map).
Which software was used to get it to work ? Thanks!
