### ISSUE TITLE
EmuWindow_SDL2_VK fails to get information from the window manager

### ISSUE THREAD

**Issue by H27CK** [yuzu-emu/yuzu#3752]
When using the Vulkan backend, `yuzu-cmd` fails with
```
[   0.090162] Frontend <Critical> yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp:EmuWindow_SDL2_VK:33: Failed to get information from the window manager
```
This is due to a missing `SDL_VERSION(&wm.version);` call in `yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp`. As shown in the example [here](https://wiki.libsdl.org/SDL_GetWindowWMInfo), it is necessary to initialise the info structure with SDL version info. This issue is resolved with:
```
SDL_SysWMinfo wm;
SDL_VERSION(&wm.version);
if (SDL_GetWindowWMInfo(render_window, &wm) == SDL_FALSE) {
  LOG_CRITICAL(Frontend, "Failed to get information from the window manager");
  std::exit(EXIT_FAILURE);
}
```

**Comment by barolo** [comment]
I'm getting this again with yuzu-cmd and latest builds, is it a regression?
