### ISSUE TITLE
"-Werror=conversion" error after merging PR #3718 in Linux

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#3754]
Building yuzu on master and mainline in Linux, I get the following errors:
```
In file included from yuzu/src/./video_core/engines/kepler_compute.h:10,
                 from yuzu/src/video_core/renderer_vulkan/vk_rasterizer.cpp:20:
yuzu/src/./common/bit_field.h: In instantiation of ‘constexpr void BitField<Position, Bits, T, EndianTag>::Assign(const T&) [with long unsigned int Position = 0; long unsigned int Bits = 1; T = short unsigned int; EndianTag = KeepTag]’:
yuzu/src/./video_core/renderer_vulkan/fixed_pipeline_state.h:131:51:   required from here
yuzu/src/./common/bit_field.h:183:63: error: conversion from ‘int’ to ‘BitField<0, 1, short unsigned int>::StorageTypeWithEndian’ {aka ‘short unsigned int’} may change value [-Werror=conversion]
  183 |         storage = (static_cast<StorageType>(storage) & ~mask) | FormatValue(value);
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
```
```
In file included from yuzu/src/./video_core/renderer_vulkan/vk_rasterizer.h:20,
                 from yuzu/src/video_core/renderer_vulkan/renderer_vulkan.cpp:31:
yuzu/src/./video_core/renderer_vulkan/fixed_pipeline_state.h: In member function ‘void Vulkan::FixedPipelineState::VertexInput::SetBinding(std::size_t, bool, u32, u32)’:
yuzu/src/./video_core/renderer_vulkan/fixed_pipeline_state.h:132:35: error: conversion from ‘u32’ {aka ‘unsigned int’} to ‘short unsigned int’ may change value [-Werror=conversion]
  132 |             binding.stride.Assign(stride);
      |                                   ^~~~~~
```

The second was obtained by modifying the first error to `storage = (u_int16_t)(static_cast<StorageType>(storage) & ~mask) | (u_int16_t)FormatValue(value);`. If I modify the second to read `binding.stride.Assign((u_int16_t)stride);`, the build will complete, but games softlock immediately, so there is something I don't understand well enough to fix the error correctly.

My system specs are:
Manjaro Linux 20.0
Kernel 5.6.5-10-tkg-pds
Ryzen 7 2700X
gcc (Arch Linux 9.3.0-1) 9.3.0

The error is NOT detected by the Linux:MingW Docker build environment (`-DENABLE_VULKAN=OFF` is a CMake argument in `.ci/scripts/windows/docker.sh`). I do not have the Linux Docker environment setup.

**Comment by H27CK** [comment]
I have found this to be an issue myself. An unsafe fix, and not one that I recommend: remove `-Werror=conversion` from `src/video_core/CMakeLists.txt`. I'm not sure whether its a safe conversion, but yuzu functions as expected. Can `stride` exceed `USHRT_MAX`?

**Comment by H27CK** [comment]
It seems as though problems begin at `RasterizerVulkan::SetupVertexArrays`, in which we do
```
vertex_input.SetBinding(std::size_t index, bool enabled, u32 stride, u32 divisor)
```
The third argument of `SetBinding` is `u32 stride`. We then attempt to assign this `u32 stride` to the `stride` (bitfield member) of `binding` (of type `Binding`), defined by
```
union Binding {
  u16 raw;
  BitField<0, 1, u16> enabled;
  BitField<1, 12, u16> stride;
};
```
set as `u16`. This is the (potentially unsafe) conversion which the compiler is warning us about. I have been through things and I can only see two calls to `SetBinding`:
```
vertex_input.SetBinding(index, false, 0, 0);
```
and, a couple of lines later,
```
vertex_input.SetBinding(
  index, true, vertex_array.stride,
  regs.instanced_arrays.IsInstancingEnabled(index) ? vertex_array.divisor : 0);
```
The data type of `vertex_array.stride` is `BitField<0, 12, u32>`. To remind: `stride` of `Binding` is defined as `BitField<1, 12, u16> stride`. Since an explicit cast to `u16`, i.e.
```
binding.stride.Assign((u16)stride)
```
causes issues, should we redefine `Binding`:
```
union Binding {
  u32 raw;
  BitField<0, 1, u32> enabled;
  BitField<1, 12, u32> stride;
};
```
to be consistent with
```
union {
  BitField<0, 12, u32> stride;
  BitField<12, 1, u32> enable;
};
```
when defining vertex_array in `video_core/engines/maxwell_3d.h`?

**Comment by degasus** [comment]
GCC provided the right warning, but C is very tricky here. The affected line is:
`storage = (static_cast<StorageType>(storage) & ~mask) | FormatValue(value);`
As summery, this is:
`u16_a = u16_b | u16_c`
Now the bad stuff about C: Operators with integers smaller than int on both sides will propagate the result to a signed integer. You can safely cast the result back to the original type, however you need to do so. The mentioned flag bailed out if you lack to do so.

**Comment by H27CK** [comment]
@degasus but the error suggests `conversion from ‘u32’ {aka ‘unsigned int’} to ‘short unsigned int’` is problematic. It does not complain about conversion from `int` to `short unsigned int`. Am I misinterpreting? Can you suggest a specific change to verify your theory so I can try. So far, I've only had success by matching the type of `stride` in `Binding` with the type of `stride` in `vertex_array` to give:
```
union Binding {
  u32 raw;
  BitField<0, 1, u32> enabled;
  BitField<1, 12, u32> stride;
};
```
as I previously suggested.
