### ISSUE TITLE
Pokémon Shield

### ISSUE THREAD

**Issue by yoracle5252** [yuzu-emu/yuzu#3769]
Hello I wanted to know if the latest version of Citra is stable even for PCs not having a very high configuration? and also I can't install update 1.1.0 on pokémon Shield, what should I do? thank you in advance

**Comment by Schplee** [comment]
Github issues aren't for support requests. Please ask your questions in either the Citra or yuzu Discord servers respectively.

**Comment by yoracle5252** [comment]
I just went on a discord yuzu by asking this same question to a moderator who referred me to the github so I don't understand

**Comment by Schplee** [comment]
Our Mod team wouldn't have referred you to Github to create an issue. Please ask your question again in the appropriate support channel in the server.
