### ISSUE TITLE
PR 3718 breaks vulkan on Linux (amdgpu)

### ISSUE THREAD

**Issue by RealJohnGalt** [yuzu-emu/yuzu#3772]
On Polaris and linux, PR #3718 causes a black screen, with audio occurring behind it (and fps ramps up as usual with video). Tested radv/aco, radv/llvm, amdvlk, and amdgpu-pro vulkan drivers. All but amdgpu-pro have the black screen, and it just crashes.

Log: https://bpaste.net/RSFA

This commit only builds on linux with either static casting or removing the cflag. So worth noting this behavior happens with either compilation workaround implemented. With this commit reverted there's no problem.

**Specs:**
 - Arch Linux
 - Mesa git
 - Ryzen 3600 @ 4.3ghz
 - rx580 8G

**Comment by lat9nq** [comment]
I tested yuzu with #3718 merged using the `-Werror=conversion` compilation workaround. It seems at least GCN 1.0 is not affected on the amdgpu/radv llvm driver, as I am able to boot SSBU and get into a match with minor mesh artifacts.

My specs are:
Manjaro Linux 20.0
Kernel 5.4.32-1-MANJARO
host-passthrough 8 core (AMD Zen+ CPU extensions)
8 GB RAM (Host is DDR4 3200 MHz @ 3400 MHz)
R5 340 2GB
