### ISSUE TITLE
Compile error on Jetson Nano (aarch64)

### ISSUE THREAD

**Issue by tkircher** [yuzu-emu/yuzu#3782]
In physical_core.cpp when ARCHITECTURE_x86_64 is false:

/testing/yuzu/src/core/hle/kernel/physical_core.cpp: In constructor ‘Kernel::PhysicalCore::PhysicalCore(Core::System&, std::size_t, Core::ExclusiveMonitor&)’:
/testing/yuzu/src/core/hle/kernel/physical_core.cpp:30:63: error: cannot convert ‘std::shared_ptr<Core::ARM_Unicorn>’ to ‘Core::ARM_Interface*’ in assignment
     arm_interface = std::make_shared<Core::ARM_Unicorn>(system);

A new Core::ARM_Unicorn is instantiated with std::make_shared<T> but assigned to a Core::ARM_Interface* which isn't a shared_ptr.

**Comment by tkircher** [comment]
Incidentally, instantiating a new object with

arm_interface = new Core::ARM_Unicorn(system);

makes it build successfully, but who knows what chaos that will bring. It did actually launch after it finished building.
![yuzu_jetson_nano](https://user-images.githubusercontent.com/19326823/80176439-0fd5f680-85a5-11ea-8c22-1d4e6c9f161a.jpeg)

**Comment by tkircher** [comment]
Just saw the patch that @lioncash posted. Going to close this.

**Comment by AuroraRAS** [comment]
I hope to know more about your experiment.
Due to the similar structure to Switch, jetson may be the most suitable hardware platform for yuzu.

**Comment by jesuslg123** [comment]
> Just saw the patch that @lioncash posted. Going to close this.

Hi! Could you share you experience and how to compile it for nano please?

**Comment by tkircher** [comment]
@AuroraRAS I definitely wish it were possible to run Switch games natively, considering that the only real difference in hardware is that the Switch has more CUDA cores.

@jesuslg123 I didn't get it to run, just to compile. I thought there might have already been a way to bypass the ARM emulation to run code natively, but that turned out not to be the case.

**Comment by FearlessTobi** [comment]
I'm not sure if this will help you, but an ARM64 port of dynarmic (our JIT) is in the making.

**Comment by tkircher** [comment]
I think that will be extremely helpful. If not for the Jetson specifically, maybe for faster ARM systems.

**Comment by bigfatbrowncat** [comment]
>I'm not sure if this will help you, but an ARM64 port of dynarmic (our JIT) is in the making.

@FearlessTobi, I have a question.

How is the current optimization/performance on the Jetson? 
How does it work in the case of "almost the same hardware"?

Does it take the advantage of running directly on the ARM?
Does it use the shader compatibility at some way?

And what is the status of the development?
(I'm pretty much interested in all that because I am thinking of buying myself a Jetson ;) )
