### ISSUE TITLE
Pokemon Shield crashes randomly with Memory Manager failure

### ISSUE THREAD

**Issue by matze19999** [yuzu-emu/yuzu#3789]
Version: Early Access 455

Hardware:
Intel Core i9-9900k
AMD Radeon VII 16GB
32GB DDR4 RAM
1TB SATA SSD

I get random crashes in Pokemon Shield, the last error the last time was:

[ 457.465105] Debug <Critical> video_core\memory_manager.cpp:UnmapRange:443: Assertion Failed!

I attached the log file:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4529915/yuzu_log.txt)

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
