### ISSUE TITLE
yuzu mainline Linux: Vulkan crash with Nvidia beta driver

### ISSUE THREAD

**Issue by d4rkf4b** [yuzu-emu/yuzu#3794]
Config:
i7-4790k
16GB DDR3
Nvidia GTX970
Manjaro 20

With Nvidia driver 440.82, yuzu-mainline works fine with Vulkan API. When I switch to Nvidia Vulkan beta driver 440.66.11 (Today, same with previous versions), Yuzu mainline crashes with info: 

`terminate called after throwing an instance of 'Vulkan::vk::Exception'
  what():  VK_ERROR_OUT_OF_DEVICE_MEMORY
`

No problem with other Vulkan applications.

**Comment by MushPsykotik** [comment]
Same issue here :

 i7-8700
GeForce GTX 1660
16 GB RAM
Ubuntu 20.04

With the same beta driver 440.66.11 (who i'm trying to run with Vulkan 1.2 to resolve some others obscures compiling shaders bugs), problem occur with yuzu-mainline and canary (not tried with nightly)

**Comment by iWeaker4you** [comment]
This problem was caused in recent versions of the emulator, I have always had the Nvidia beta drivers and it worked wonderfully until after certain builds it stopped working.

**Comment by sergeyhist** [comment]
Same issue with 440.66.14 beta driver

**Comment by mitigd** [comment]
440.66.15 as well.

**Comment by d4rkf4b** [comment]
tested with 450.36.06, same bug

**Comment by jhol** [comment]
Same issue with 440.82

**Comment by d4rkf4b** [comment]
> Same issue with 440.82

Works for me with 440.82 (Manjaro)

**Comment by lat9nq** [comment]
Currently an issue on the normal Nvidia driver 450.51 (replaces 440.82).

**Comment by qurious-pixel** [comment]
Nvidia updated to stable driver 450.57. Causes same error message as beta drivers.
`VK_ERROR_OUT_OF_DEVICE_MEMORY`
8 GB GDDR6 VRAM
https://www.nvidia.com/en-us/drivers/unix/
