### ISSUE TITLE
Asynchronous GPU emulation incompatible with yuzu-cmd

### ISSUE THREAD

**Issue by H27CK** [yuzu-emu/yuzu#3796]
When enabling asynchronous GPU emulation (which is off by default, despite the comments in `sdl2-config.ini`), `yuzu-cmd` produces no output (other than creating a window), irrespective of the rendering API selected ~~, before segfaulting in `GPU::WaitFence`~~. I've stepped through execution of both `yuzu` and `yuzu-cmd` simultaneously without finding much to give any clues. To at least each programs respective `Core::System::GetInstance().RunLoop()` call, everything seems to be consistent.

**Comment by G-Spawn** [comment]
Should be fixed in newer yuzu versions.
