### ISSUE TITLE
[Linux] Smash opengl broken on recent mainline and EA builds

### ISSUE THREAD

**Issue by RealJohnGalt** [yuzu-emu/yuzu#3806]
Recently on mainline and EA builds, smash has been broken on opengl with linux amdgpu. Another user with a gcn 1.0 card also verified the same behavior on a mainline build. It only displays solid colors on screen (white, red, blue, etc).

Vulkan works as expected on all vulkan drivers (radv/aco, radv/llvm, amdgpu-pro, amdvlk). And opengl works properly on SMO.

**Specs:**
 - Arch Linux
 - Mesa git
 - Ryzen 3600 @ 4.3ghz
 - rx580 8G

Log: http://ix.io/2jMq

**Comment by goldenx86** [comment]
This problem is also present on the OpenGL Windows driver for Vega and newer cards, but it is fixed for Polaris. This may suggest some sort of "incompatibility" between yuzu and the mesa driver, as Nvidia and the Vulkan AMD for Vega and Navi drivers are not affected by it.

**Comment by toccata10** [comment]
Same pb on r9 fury, Archlinux, mesa 20.0: with Ogl, I just have flashing colors with Smash.
With Vulkan (radv), after a while, it completely freezes the display which becomes black.
Connecting by ssh gives me this dmesg:
```
[ 6478.143262] amdgpu 0000:01:00.0: ib ring test failed (-110).
[ 6478.295108] amdgpu 0000:01:00.0: GPU BACO reset
[ 6478.549625] amdgpu 0000:01:00.0: GPU reset succeeded, trying to resume
[ 6478.549659] [drm] PCIE GART of 1024M enabled (table at 0x000000F400300000).
[ 6478.549666] [drm] VRAM is lost due to GPU reset!
[ 6478.726627] [drm] UVD initialized successfully.
[ 6478.827666] [drm] VCE initialized successfully.
[ 6478.827714] [drm:amdgpu_register_gpu_instance [amdgpu]] *ERROR* Cannot register more gpu instance
[ 6478.843094] amdgpu 0000:01:00.0: [drm:amdgpu_ib_ring_tests [amdgpu]] *ERROR* IB test failed on uvd (-110).
[ 6478.843330] amdgpu 0000:01:00.0: ib ring test failed (-110).
```

**Comment by RealJohnGalt** [comment]
> Same pb on r9 fury, Archlinux, mesa 20.0: with Ogl, I just have flashing colors with Smash.
> With Vulkan (radv), after a while, it completely freezes the display which becomes black.
> Connecting by ssh gives me this dmesg:
> 
> ```
> [ 6478.143262] amdgpu 0000:01:00.0: ib ring test failed (-110).
> [ 6478.295108] amdgpu 0000:01:00.0: GPU BACO reset
> [ 6478.549625] amdgpu 0000:01:00.0: GPU reset succeeded, trying to resume
> [ 6478.549659] [drm] PCIE GART of 1024M enabled (table at 0x000000F400300000).
> [ 6478.549666] [drm] VRAM is lost due to GPU reset!
> [ 6478.726627] [drm] UVD initialized successfully.
> [ 6478.827666] [drm] VCE initialized successfully.
> [ 6478.827714] [drm:amdgpu_register_gpu_instance [amdgpu]] *ERROR* Cannot register more gpu instance
> [ 6478.843094] amdgpu 0000:01:00.0: [drm:amdgpu_ib_ring_tests [amdgpu]] *ERROR* IB test failed on uvd (-110).
> [ 6478.843330] amdgpu 0000:01:00.0: ib ring test failed (-110).
> ```

The radv issue is different, and can be worked around by using amdvlk. But yes, the smash issue seems to be polaris+ on linux, and navi+ on windows.

**Comment by toccata10** [comment]
I opened an issue on the mesa bug tracker here:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/2946#note_497539

**Comment by lat9nq** [comment]
This can be closed as [mesa/merge_requests/5167](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/5167) has been merged, thus a non-yuzu issue.
