### ISSUE TITLE
[Linux] OpenGL displaying incorrectly when using Qt/Kde/Plasma scaling factor

### ISSUE THREAD

**Issue by amunabv** [yuzu-emu/yuzu#3828]
Hey, on my install (Arch5.6.8, i5 6600k, 16GB, GTX980 Ti) this is the output I get from Yuzu

![unknown](https://user-images.githubusercontent.com/9385838/80703930-f8869400-8ae3-11ea-9c32-b54d8091d84b.png)

I think the problem has VERY much affinity with this (solved) one:
https://github.com/ioquake/ioq3/issues/422

It's probably a HiDPI problem (which I use).
My scaling is set to 162.5% with a forced font size of 156DPI
(Set via KDE Management applet)

- When I run yuzu-cmd from the commandline the window is displaying correctly. 
- I tried removing qtconfig.ini that didn't help.
- Setting the scale to normal in KDE Plasma (100%) solves the problem
- (Maybe this can be solved by adding <key>NSHighResolutionCapable</key><false/> to a certain "plist" (check the link))
- Seems to be Nvidia-only
- Fix for now: Launch yuzu with QT_SCREEN_SCALE_FACTORS=1

Thanks!

**Comment by Cloudperry** [comment]
I'm having the same issue on OpenSUSE Tumbleweed with KDE 5.18.4 and Qt 5.14.1. My global scaling factor is set to 125% and I'm using a 1440p display. My GPU is AMD Vega 56 so it seems this issue affects AMD GPUs as well. My Yuzu version is mainline 243.

Setting the scaling factor to 100% or running yuzu with QT_SCREEN_SCALE_FACTORS=1 solves the problem for me. Thanks for the qt screen scale factor fix. It fixes many other applications as well (for example qbittorrent and kdenlive).

**Comment by Cloudperry** [comment]
Okay so it seems that this was a qt bug. Opensuse Tumbleweed just got qt 5.15 and with that it is fixed. All the other applications that had this bug also got fixed (kdenlive, qbittorrent, vlc, citra).

**Comment by mirh** [comment]
This can be closed then?
