### ISSUE TITLE
Missing HLE service command 'Poll' in 'bsd:u'

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3836]
i am providing the log here .
my specs:i5 5200u 
8gb ram 
nvidia geforce 820m
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4559146/yuzu_log.txt)

**Comment by bukyapavankumar** [comment]
[yuzu_log_linux.txt](https://github.com/yuzu-emu/yuzu/files/4559272/yuzu_log_linux.txt)

**Comment by bukyapavankumar** [comment]
Unknown / unimplemented function 'ResolveEx': port='nsd:u'
Unknown / unimplemented function 'GetCurrentNetworkProfile': port='IGeneralService' 
Unknown / unimplemented function 'Poll': port='bsd:u'

**Comment by callmenemo491** [comment]
Unknown / unimplemented function 'ResolveEx': port='nsd:u'
=> ticket already open for it:  #3014

Unknown / unimplemented function 'GetCurrentNetworkProfile': port='IGeneralService'
=> ticket already open for it:  #2629

**Comment by bukyapavankumar** [comment]
Ok just for poll then

**Comment by ReinUsesLisp** [comment]
Poll has been implemented in #4397.
