### ISSUE TITLE
Yuzu hangs and closes automatically while running devil may cry 3special edition 

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3841]
Apparently it doesn't have any log error ,while closing.

**Comment by bukyapavankumar** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4560509/yuzu_log.txt)

**Comment by bukyapavankumar** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4560540/yuzu_log_linux_ogl.txt)

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by bukyapavankumar** [comment]
Noted. It

**Comment by bukyapavankumar** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4563018/yuzu_log.txt)
turned out that log was not proper so sharing the new.errors i noticed

[  11.476200] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:186: API ERROR 1281: GL_INVALID_VALUE error generated. <levels>, <width> and <height> must be 1 or greater.
[  11.521246] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:186: API ERROR 1286: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.

**Comment by callmenemo491** [comment]
@bukyapavankumar , ur issue is related to these Issue ticket"  #1681, #3620, #3406

**Comment by bukyapavankumar** [comment]
#1681 maybe complete black screen and yuzu crashes
