### ISSUE TITLE
Render.OpenGL - ANCH - API PERFORMANCE 131186: Buffer performance warning

### ISSUE THREAD

**Issue by callmenemo491** [yuzu-emu/yuzu#3850]
- Yuzu Version      : Early Access 475 | HEAD-b6a1daccd
- Game Title        : Animal Crossing New Horizons
- Game Version      : 1.2.0
- Game TitleId      : 01006F8002326000
- Mods              : Yes
- Mods List         : BypassBootCrash, CrashFixCamera, DisableDoF
- DLC               : Yes
- DLC List          : 300, 301

Issue Observed:
there are thousands of these type of messages!

```
[ 644.029060] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:189: API PERFORMANCE 131186: Buffer performance warning: Buffer object 146 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (11), GL_SHADER_STORAGE_BUFFER (6), GL_SHADER_STORAGE_BUFFER (7), GL_SHADER_STORAGE_BUFFER (8), and GL_SHADER_STORAGE_BUFFER (9), usage hint is GL_DYNAMIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.
```
and
```
[ 430.701770] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:189: API PERFORMANCE 131186: Buffer performance warning: Buffer object 146 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (2), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (7), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (8), GL_SHADER_STORAGE_BUFFER, GL_SHADER_STORAGE_BUFFER (0), GL_SHADER_STORAGE_BUFFER (6), GL_SHADER_STORAGE_BUFFER (7), GL_SHADER_STORAGE_BUFFER (8), and GL_SHADER_STORAGE_BUFFER (9), usage hint is GL_DYNAMIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.
```

Reproduction:
1. Play the game.

Log: (~51 MB)
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4562984/yuzu_log.zip)

**Comment by bukyapavankumar** [comment]
you need not create a issue for every error it shows .just close this

**Comment by goldenx86** [comment]
In this particular case, that's something the game asks, so it is normal native behaviour.

**Comment by bukyapavankumar** [comment]
when i have similar error lines my issue was closed sic

**Comment by callmenemo491** [comment]
@goldenx86 , if its 'normal', i think the logs should be marked with 'debug' (as the log gets 'big')

**Comment by Hexagon12** [comment]
These log lines are normal behaviour.
