### ISSUE TITLE
GetLoader - complains NSP file is different type than its extension

### ISSUE THREAD

**Issue by callmenemo491** [yuzu-emu/yuzu#3852]
- Yuzu Version      : Early Access 475 | HEAD-b6a1daccd
- Game Title        : Animal Crossing New Horizons
- Game Version      : 1.2.0
- Game TitleId      : 01006F8002326000
- Mods              : Yes
- Mods List         : BypassBootCrash, CrashFixCamera, DisableDoF
- DLC               : Yes
- DLC List          : 300, 301

Seems some validation logic is not right... Yuzu displays the game format as 'NSP'
but in the log, it complains that the type is different to extension.

Issue Observed:
```
[   0.646007] Loader <Warning> core\loader\loader.cpp:GetLoader:237: File AnimalCrossingNewHorizons_-_DLC_-_NookIncSilkRug.nsp has a different type than its extension.
[   0.720161] Loader <Warning> core\loader\loader.cpp:GetLoader:237: File AnimalCrossingNewHorizons_-_DLC_-_SpecialOrderTicketPocketCamp.nsp has a different type than its extension.
[   0.890174] Loader <Warning> core\loader\loader.cpp:GetLoader:237: File AnimalCrossingNewHorizons_v1.2.0_-_Update.nsp has a different type than its extension.
```

How To Reproduce:
1. Put files into GameFolder
2. Open and Close Yuzu.

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4563205/yuzu_log.txt)

![Yuzu](https://user-images.githubusercontent.com/13878580/80796393-03bbeb80-8bda-11ea-8d94-e07e21e64cb6.jpg)

Suggested Solution:
- N/A

**Comment by Hexagon12** [comment]
That's a normal log output. If the DLC and updates work, you shouldn't worry. It's telling that the files actually have a different extension (probably NCA in this case).

**Comment by callmenemo491** [comment]
@Hexagon12 ,  DLC/Update works.
to test if the format of the file was wrong - renamed one of the files (from NSP) to NCA.
```
[   1.182705] Loader <Warning> core\loader\loader.cpp:GetLoader:237: File AnimalCrossingNewHorizons_v1.2.0_-_Update.nca has a different type than its extension.
```
