### ISSUE TITLE
where angels cry stuck on launching

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3855]
Game            : where angels cry
Title ID          : 010027D011C9C000
yuzu version : Early access 475
steps to produce error:
just launch the game.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4564050/yuzu_log.txt)

**Comment by bukyapavankumar** [comment]
errors you might be interested in:
[  17.751517] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:KickoffPB:200: Assertion Failed! Unimplemented code!
[  17.751563] Debug <Critical> video_core\dma_pusher.cpp:Step:55: Assertion Failed!
[  25.038900] HW.Memory <Error> core\memory.cpp:Write:669: Unmapped Write32 0x80020049 @ 0x00000000000000A4
[  25.038936] HW.Memory <Error> core\memory.cpp:Write:669: Unmapped Write32 0x20080200 @ 0x00000000000000A8
[  25.038937] HW.Memory <Error> core\memory.cpp:Write:669: Unmapped Write32 0x00000000 @ 0x00000000000000AC
[  25.038939] HW.Memory <Error> core\memory.cpp:Write:669: Unmapped Write32 0x00100000 @ 0x00000000000000B0

**Comment by BSoDGamingYT** [comment]
Please stop opening these issues. There is nothing of interest in these logs. 

Issues with zero information on a real problem arent helpful. It basically equates to "My game does work, fix it"

**Comment by bukyapavankumar** [comment]
how can i provide more debugging info?

**Comment by BSoDGamingYT** [comment]
You can start by joining the yuzu discord and stating your issues there. Posting tonnes of unuseful logs just clutters this issue tracker with pointless information

**Comment by theboy181** [comment]
top notch help ;)
