### ISSUE TITLE
Vulkan + Linux performance issues

### ISSUE THREAD

**Issue by alexdesaint** [yuzu-emu/yuzu#3856]
CPU : AMD Ryzen 9 3900 (4 gHz oc)
GPU :  AMD RX 480

I have a dual boot Windows/ArchLinux.
**Only tested on vulkan**
Linux driver : vulkan-amdgpu-pro 19.30_934563 (proprietary drivers from AMD)

Games used for tests : 
- SUPER MARIO ODYSSEY
- The Legend of Zelda: Link's Awakening

On Windows :
- I'm close to 80%~100% all the time

![Capture](https://user-images.githubusercontent.com/33799602/80805288-e83fe900-8bb7-11ea-8f44-462b87600e10.PNG)
![Capture2](https://user-images.githubusercontent.com/33799602/80805290-e8d87f80-8bb7-11ea-8e5b-db45f0bf7846.PNG)

On Linux (yuzu-mainline  429f8cb  21d0053f681fb6d1cd370d686227c5b6a) :
- 60%~70% all the time

![image](https://user-images.githubusercontent.com/33799602/80805531-99df1a00-8bb8-11ea-90b1-658e9801cfcf.png)
![image](https://user-images.githubusercontent.com/33799602/80806241-6f8e5c00-8bba-11ea-88e1-0ada776b78d1.png)

~~On Linux (zuzu 3a13552  db854036db4267ed21ce1e3f7f000568a) :~~
- ~~Crash on loading~~
```
[  18.916025] Service.AM <Warning> core/hle/service/am/am.cpp:SetRestartMessageEnabled:428: (STUBBED) called
[  18.916387] Service.AM <Warning> core/hle/service/am/am.cpp:SetOperationModeChangedNotification:392: (STUBBED) called flag=true
[  18.916546] Service.AM <Warning> core/hle/service/am/am.cpp:SetPerformanceModeChangedNotification:402: (STUBBED) called flag=true
[  18.917067] Service.AM <Warning> core/hle/service/am/am.cpp:SetFocusHandlingMode:420: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[  18.917372] Service.AM <Warning> core/hle/service/am/am.cpp:SetOutOfFocusSuspendingEnabled:440: (STUBBED) called enabled=true
[  18.919744] Service.APM <Info> core/hle/service/apm/controller.cpp:SetClockSpeed:84: called, mhz=000003FC
[  19.834956] Service <Warning> core/hle/service/sm/controller.cpp:QueryPointerBufferSize:43: (STUBBED) called
[  19.836583] Debug <Critical> core/hle/kernel/hle_ipc.cpp:operator():297: Assertion Failed!
BufferDescriptorX invalid buffer_index 1
```

Is it possible to check the name of the driver used ?

I have been playing for a month now, updating regularly to the last git version and it's the same issue since the beginning.

Amazing emulator btw :)

**Comment by Hexagon12** [comment]
The last issue happens because you're using master, while you're supposed to use mainline instead.

**Comment by G-Spawn** [comment]
Please reopen this issue if it still happens for you on latest yuzu & provide new log 🙏
