### ISSUE TITLE
Missing HLE service command  'OpenCacheStorageList' in 'fsp-srv' 

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3858]
required by mortal comat 11
unimplemented function 'OpenCacheStorageList': port='fsp-srv'
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4565832/yuzu_log.txt)

**Comment by callmenemo491** [comment]
duplicate of: #2882
