### ISSUE TITLE
 NARUTO SHIPPUDEN: ULTIMATE NINJA STORM 4 ROAD TO BORUTO black screen while launching

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3864]
Game         :     NARUTO SHIPPUDEN: ULTIMATE NINJA STORM 4 ROAD TO BORUTO
TITLE ID     :      01003F800CF5C000 
yuzu mainline 244

**Comment by bukyapavankumar** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4567296/yuzu_log.txt)

**Comment by bukyapavankumar** [comment]
you can close this issue if you didnt find anything in the log that is useful

**Comment by Hexagon12** [comment]
Related log lines:
```
[  71.388245] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:KickoffPB:200: Assertion Failed! Unimplemented code!
[  71.388323] Debug <Critical> video_core\dma_pusher.cpp:Step:53: Assertion Failed!
```

**Comment by bukyapavankumar** [comment]
Book of demons has this too

**Comment by LastChalice** [comment]
Did you clear corrupted shaders?

**Comment by bukyapavankumar** [comment]
i have tried with and without shader cache

**Comment by benderscruffy** [comment]
@bukyapavankumar 
is this still a problem

**Comment by bukyapavankumar** [comment]
> @bukyapavankumar
> is this still a problem

I don't know . Don't have this game installed now

**Comment by ARKseal** [comment]
Here's a specific line
`[  34.589095] HW.GPU <Critical> video_core\macro\macro_jit_x64.cpp:WarnInvalidParameter:607: Macro JIT: invalid parameter access 0x26066352f98 (0x26066352eb0 is the last parameter)`

**Comment by gidoly** [comment]
fixed with yfc part 1
