### ISSUE TITLE
Missing HLE service commands  'GetAppletInfo' in 'IRequest', 'GetCurrentIpConfigInfo' in 'IGeneralService' (nifm:u)

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3867]
required by  lets sing 12 
title id : 0100AC000DF4E000

error:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4567538/yuzu_log.txt)

[ 124.016144] Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:154: Assertion Failed! Unknown / unimplemented function 'GetAppletInfo': port='IRequest' cmd_buf={[0]=0x1000006, [1]=0xD, [2]=0x1000, [3]=0x37538E3C, [4]=0x4, [5]=0x0, [6]=0x0, [7]=0x0, [8]=0x140001}
[ 124.016209] Debug <Critical> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:167: Assertion Failed!
[ 124.016214] Debug <Critical> core\hle\kernel\hle_ipc.cpp:WriteToOutgoingCommandBuffer:266: Assertion Failed!
[ 126.084971] Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:154: Assertion Failed! Unknown / unimplemented function 'GetCurrentIpConfigInfo': port='IGeneralService' cmd_buf={[0]=0x6, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x2, [6]=0x0, [7]=0x0, [8]=0x49434653}
[ 126.085016] Debug <Critical> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:167: Assertion Failed!
[ 126.085019] Debug <Critical> core\hle\kernel\hle_ipc.cpp:WriteToOutgoingCommandBuffer:266: Assertion Failed!
[ 127.475255] Service.FS <Info> core\hle\service\filesystem\fsp_srv.cpp:OpenSaveDataFileSystem:829: called.
[ 127.920524] Service.FS <Warning> core\hle\service\filesystem\fsp_srv.cpp:Commit:474: (STUBBED) called
[ 128.237950] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:43: (STUBBED) called
[ 128.240104] Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:154: Assertion Failed! Unknown / unimplemented function 'ListAudioInsAuto': port='audin:u' cmd_buf={[0]=0x1000006, [1]=0xC09, [2]=0x0, [3]=0x0, [4]=0x0, [5]=0x0, [6]=0x0, [7]=0x0, [8]=0x49434653}
[ 128.240110] Debug <Critical> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:167: Assertion Failed!

**Comment by ogniK5377** [comment]
ListAudioInsInAuto is already an open PR #3811

**Comment by bukyapavankumar** [comment]
Ok then the other two are required

**Comment by choppymaster** [comment]
`GetAppletInfo` is also needed for 
* My Friend Pedro: Blood Bullets Bananas
* Pokémon HOME
* Tetris 99
* Sea king
* Dragon's Dogma: Dark Arisen 
* Level Head
* American Ninja Warrior: Challenge
* Pushy and Pully in Blockland
* Ghost blade hd 
* doom 1993
* doom 2
* Pawarumi
* damsel
* racedierun
* super jumpy ball
* Arcade Archives plus alpha
* contra rogue rops
* freedom finger
* synaptic drive 
* Burnout paradise remastered 
* vector wars
* roll'd
* tools up
* Darksiders II Deathinitive Edition 
* invisigun reloaded 
* knight squad
* puchitto karasuta
* monster farm
* squidgies takeover
* rocket wars

**Comment by bukyapavankumar** [comment]
Oh Many games require it

**Comment by ogniK5377** [comment]
Implemented with #5856 #4390
