### ISSUE TITLE
video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:186: API ERROR 1286: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete

### ISSUE THREAD

**Issue by Elementrix1** [yuzu-emu/yuzu#3869]

**Comment by Elementrix1** [comment]
[ 298.731192] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:189: API UNDEFINED_BEHAVIOR 131222: Program undefined behavior warning: The current GL state uses a sampler (1) that has depth comparisons disabled, with a texture object (2DArray@0x0000000000000000) with a non-depth format, by a shader that samples it with a shadow sampler. This will result in undefined behavior.
[ 298.734517] Debug <Critical> video_core\texture_cache\format_lookup_table.cpp:GetPixelFormat:184: Assertion Failed! texture format=14 srgb=false components={4 2 2 2}
[ 298.736270] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[ 298.736273] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[ 298.736953] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[ 298.736956] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[ 298.738178] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[ 298.738181] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[ 298.738811] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[ 298.738814] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[ 298.739471] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[ 298.739474] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[ 298.740085] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[ 298.740089] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[ 298.741391] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[ 298.741395] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[ 298.742121] Service.HID <Warning> core\hle\service\hid\hid.cpp:IsSixAxisSensorAtRest:425: (STUBBED) called, handle=131075, applet_resource_user_id=347892350976
[ 298.742142] Service.HID <Warning> core\hle\service\hid\hid.cpp:IsSixAxisSensorAtRest:425: (STUBBED) called, handle=131331, applet_resource_user_id=347892350976
[ 298.742153] Service.HID <Warning> core\hle\service\hid\hid.cpp:IsSixAxisSensorAtRest:425: (STUBBED) called, handle=131587, applet_resource_user_id=347892350976
[ 298.742164] Service.HID <Warning> core\hle\service\hid\hid.cpp:IsSixAxisSensorAtRest:425: (STUBBED) called, handle=131843, applet_resource_user_id=347892350976
[ 298.742173] Service.HID <Warning> core\hle\service\hid\hid.cpp:IsSixAxisSensorAtRest:425: (STUBBED) called, handle=132099, applet_resource_user_id=347892350976
[ 298.742184] Service.HID <Warning> core\hle\service\hid\hid.cpp:IsSixAxisSensorAtRest:425: (STUBBED) called, handle=132355, applet_resource_user_id=347892350976
[ 298.742194] Service.HID <Warning> core\hle\service\hid\hid.cpp:IsSixAxisSensorAtRest:425: (STUBBED) called, handle=132611, applet_resource_user_id=347892350976
[ 298.742205] Service.HID <Warning> core\hle\service\hid\hid.cpp:IsSixAxisSensorAtRest:425: (STUBBED) called, handle=132867, applet_resource_user_id=347892350976
[ 298.742214] Service.HID <Warning> core\hle\service\hid\hid.cpp:IsSixAxisSensorAtRest:425: (STUBBED) called, handle=139267, applet_resource_user_id=347892350976
[ 298.750361] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[ 298.750367] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[ 298.755789] Kernel <Error> core\hle\kernel\readable_event.cpp:Reset:40: Handle is not signaled! object_id=709, object_type=ReadableEvent, object_name=IAudioDevice:AudioOutputDeviceSwitchedEvent:Readable
[ 298.806785] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[ 298.806789] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[ 298.807961] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 10
[ 298.807966] Debug <Critical> core\hle\service\hid\controllers\npad.cpp:NPadIdToIndex:70: Assertion Failed! Unknown npad id 11
[ 298.808039] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:189: API PERFORMANCE 131186: Buffer performance warning: Buffer object 111 (bound to GL_SHADER_STORAGE_BUFFER, and GL_SHADER_STORAGE_BUFFER (0), usage hint is GL_DYNAMIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.
[ 298.808863] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:186: API ERROR 1286: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.
[ 298.808962] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:186: API ERROR 1286: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.
[ 298.808985] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:189: API PERFORMANCE 131186: Buffer performance warning: Buffer object 3 (bound to GL_UNIFORM_BUFFER (1), GL_UNIFORM_BUFFER (43), and GL_UNIFORM_BUFFER_EXT, usage hint is GL_STREAM_DRAW) is being copied/moved from VIDEO memory to HOST memory.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers. Please use our Discord for support.
