### ISSUE TITLE
crash after launch the game

### ISSUE THREAD

**Issue by alfonsodeso** [yuzu-emu/yuzu#3870]
you can close this issue if you didnt find anything useful from this log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4568249/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers. Please use our Discord for support.

**Comment by alfonsodeso** [comment]
where can i find you on discord ? sorry for bad english and i'm new to this

Pada tanggal Sab, 2 Mei 2020 pukul 23.55 Tobias <notifications@github.com>
menulis:

**Comment by callmenemo491** [comment]
@alfonsodeso , https://yuzu-emu.org/help/reference/asking/
