### ISSUE TITLE
hlr_kernel - Handle is not signaled - ISelfController,IAudioDevice,IUser,IRequest

### ISSUE THREAD

**Issue by callmenemo491** [yuzu-emu/yuzu#3874]
- Yuzu Version      : Early Access 486 | HEAD-942ae0eeb
- Game Title        : Animal Crossing New Horizons
- Game Version      : 1.2.0
- Game TitleId      : 01006F8002326000
- Mods              : Yes
- Mods List         : BypassBootCrash, CrashFixCamera, DisableDoF
- DLC               : Yes
- DLC List          : 300, 301

Issue Observed:
These appear thousands of times...
I did a 'sort/uniq' on the log to make things easier to pick out the 'events':
```
Kernel <Error> core\hle\kernel\readable_event.cpp:Reset:40: Handle is not signaled! object_id=529, object_type=ReadableEvent, object_name=ISelfController:AccumulatedSuspendedTickChangedEvent:Readable
Kernel <Error> core\hle\kernel\readable_event.cpp:Reset:40: Handle is not signaled! object_id=732, object_type=ReadableEvent, object_name=IAudioDevice:AudioOutputDeviceSwitchedEvent:Readable
Kernel <Error> core\hle\kernel\readable_event.cpp:Reset:40: Handle is not signaled! object_id=1292, object_type=ReadableEvent, object_name=IUser:AvailabilityChangeEvent:Readable
Kernel <Error> core\hle\kernel\readable_event.cpp:Reset:40: Handle is not signaled! object_id=1306, object_type=ReadableEvent, object_name=IRequest:Event1:Readable
```

Reproduction:
1. Play the game.

Log: (Unzipped ~51 MB)
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4569364/yuzu_log.zip)

Suggested Solution:
- N/A

If these are considered "normal" (not of a concern),
please change code (loglevel) to output these "debug"

**Comment by FernandoS27** [comment]
It's of no concern. Somebody added it thinking it was abnormal behavior when in reality it's normal behavior to reset events that aren't signaled.
