### ISSUE TITLE
Retarget for boost version 1.67

### ISSUE THREAD

**Issue by cbondurant** [yuzu-emu/yuzu#3876]
I was recently attempting to build Yuzu-mainline in Debian Buster (stable), and while the process mostly worked without issue, there was a version mismatch between the needed version of boost and the version of boost that Buster has. 

There is a single boost feature that is used one time in `video_core/textures/astc.cpp:194` that seemingly is the only feature not in Boost version 1.67.0, [boost::container::static_vector_options](https://www.boost.org/doc/libs/1_73_0/doc/html/boost/container/static_vector_options.html)

Debian Buster currently only has library support for version 1.67.0, however this feature was not added until seemingly 1.71, coincidentally the version that Ubuntu currently has.

While normally I would completely understand the use of newer versions of a library in the name of newer features. After removing the offending line of code (as this is only a helper class for adding options to a static vector) I was able to then build Yuzu without issue. This is a very cost effective change that would result in a significant increase in the compatibility of the codebase, as Buster will be the stable release of Debian for at least another year before the testing branch is frozen and made into the new stable.

**Comment by degasus** [comment]
FYI: #3735 is merged now and the requirements are bumped to 1.71. So when you retry to compile yuzu, it shall automatically download (and cache) the newer version of boost by conan.

However I agree, this kind of usage is a bit gross for a dependency upgrade.
