### ISSUE TITLE
 Unimplemented ioctl 

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3877]
error: Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
 Debug <Critical> core\hle\service\nvdrv\devices\nvhost_vic.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
required by gears of unlimited 2

**Comment by callmenemo491** [comment]
why open a duplicate ticket?
u put the same info into:  #2643   (yesterday).

**Comment by bukyapavankumar** [comment]
Yes but some are stubbed and these are not that's why I opened a new issue

**Comment by Hexagon12** [comment]
Duplicate of #2643
