### ISSUE TITLE
goto configure - results in console log output 'Unknown property overflow"

### ISSUE THREAD

**Issue by callmenemo491** [yuzu-emu/yuzu#3883]
Version: yuzu Early Access 493 | HEAD-47231b3f1
- Issue?
console log output 'Unknown property overflow"

i tried searching github for the "unknown property...." printout in the code,
but i cannot find any reference to it... so not sure where this error is coming from.

- How To Reproduce:
1. Start Yuzu
2. goto "Emulation -> Configure... ->Debugging -> Enable "Show Log Console"
3. quit yuzu
4. start Yuzu
5. goto Emulation -> Configure..."
6. look at log console for the error printout (as per screenshot attached)

- Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4572842/yuzu_log.txt)
![Yuzu_SystemLog__when_User_goes_to_ConfigurationOption](https://user-images.githubusercontent.com/13878580/80937365-b923b480-8e0f-11ea-9315-367d507b89ba.jpg)

**Comment by Hexagon12** [comment]
Please do not nitpick at every log line you find. This is normal behaviour.

**Comment by callmenemo491** [comment]
could you please educate me, as to why this is "normal"
1st time for me seeing this... if something is 'unknown' & 'overflow', it gives impression something is not right...

**Comment by callmenemo491** [comment]
i believe i found where in the code, this error originates from:

- yuzu/dist/qt_themes/qdarkstyle/style.qss 
```
QTabWidget::tab-bar {
    overflow: visible;
}
```

the parameter "overflow" is not defined prior, therefore the reason as "unknown property"
