### ISSUE TITLE
Pokemon Sword : Popup windows bug the emulation speed

### ISSUE THREAD

**Issue by thomas-chn** [yuzu-emu/yuzu#3888]
This bug is present in Yuzu 246 on Pokemon Sword.
When a popup window is opened, the emulation speed reaches 900% even if the limitation to 100% is activated. This is not seen graphically but the music becomes super accelerated.

There is another bug which is complementary to this one: When opening Y-COMM with Y key, a popup window appears to notify us of an error, the bug occurs, but in addition Yuzu crash :
![image](https://user-images.githubusercontent.com/48118348/81081429-2f004c80-8ef2-11ea-9dbc-5c91cb522226.png)

**Comment by bukyapavankumar** [comment]
You shouldn't use the y key

**Comment by G-Spawn** [comment]
At least for the y comm issue the error is now bypassed within emu so you don't need mod. Can you let us know if the emulation speed in singlecore still affects audio for you?

**Comment by gidoly** [comment]
should be fixed. and now you should able to use y menu while ldn room is opened
