### ISSUE TITLE
outfit glitched.

### ISSUE THREAD

**Issue by atrixiwnl** [yuzu-emu/yuzu#3889]
So I reached motostoke and the first thing I did was shop an outfit. I completely changed my looks and then went to check in at the gym thingy. After checking in my outfit got reset. I figured maybe it was just a little bug and it would go away but once the opening ceremony of the gyms began and I was the only one wearing normal clothing instead of a battle outfit I noticed this was a bigger glitch.

**Comment by atrixiwnl** [comment]
I kinda do not want to restart the game and I hate the looks of the normal player model, so if anyone has a male save file that's at motostoke I would gladly take it.

**Comment by Hexagon12** [comment]
Are you using the "Disable Gym Uniforms" mod?

**Comment by atrixiwnl** [comment]
I am not using any mods, I don't even know how to lmfao.

**Comment by atrixiwnl** [comment]
If you need any screenshots or gifs lmk.

**Comment by atrixiwnl** [comment]
I have figured out what caused this, when you go into the first gym, and you give don't give an actual number to your challenger kit but just an A or ??, this happens.
