### ISSUE TITLE
[CRASH] Exception Unhandled 

### ISSUE THREAD

**Issue by Khapato** [yuzu-emu/yuzu#3891]
Greetings,

I am experiencing this message before the application crashes.

"Unhandled exception at 0x00007FF7C29FA463 in yuzu.exe: 0xC0000005: Access violation reading location 0x000001DF4480E788. occurred"

The piece of code from the disassembly  where the exception happens is as follow:
00007FF7C29FA453  mov         r8,0FFFFFFFFFFFFFFFFh  
00007FF7C29FA45A  nop         word ptr [rax+rax]  
00007FF7C29FA460  inc         r8  
**00007FF7C29FA463  cmp         byte ptr [rdx+r8],0**   -- here it throws the exception --
00007FF7C29FA468  jne         00007FF7C29FA460  
00007FF7C29FA46A  lea         rcx,[rsp+30h]  
00007FF7C29FA46F  call        00007FF7C2867C50  
00007FF7C29FA474  nop  

it says also that the heap got corrupted by that time.

Using yuzu 246 mainline-636-2034-g57812d3e5 (2020-05-05).

Found the issue while playing the games pokémon mystery dungeons dx (occasionally) and pokémon sword (more frequently) and even after some idle time after yuzu starts up.

Hope the information provided will help you guys figure some other problems in the game. For what it is worth, the effort you are all puting in this project is memorable. keep up with the hard work.

Best regards,

**Comment by ogniK5377** [comment]
Can you please attach a log?

**Comment by choppymaster** [comment]
STILL missing a log file.

**Comment by G-Spawn** [comment]
Please reopen this issue and provide a log file should you still have issue on latest Mainline (785 or newer as of this date of closing)
