### ISSUE TITLE
Super Mario Odyssey image gets frozen

### ISSUE THREAD

**Issue by Slender1264** [yuzu-emu/yuzu#3893]
CPU: i9 9900k
GPU: RTX 2080
Using windows and only tested in OpenGL
Using the latest version of Yuzu and the latest graphics drivers. (Yuzu 249)

In Super Mario Odyssey if i go to the Action Guide menu either from the main menu or when the game takes me there to show me a new ability when i exit the game's image freezes, the sound becomes super slow but it's still possible to interact with the game and "continue playing" even if the image is frozen.

Every time i enter the Action Guide menu the emulator gives me a message to either use the game provided controls in order to exit or select the "Exit Web Applet" option which is at the menu bar. Both options bring the results which i stated above, this can get fixed if you restart the game but if you enter the Action Guide menu it once again happens. 
Sometimes while you're ingame the game will force you to enter the Action Guide menu to show you new controls. First time it forces you is when you leave the Cascade Kingdom for the first time, while inside the Odyssey ship Cappy forces you to enter the Action Guide menu and after that the image gets frozen making you unable to continue the game. If you restart it'll take you back at the start of Cascade Kingdom.

**Comment by FearlessTobi** [comment]
How exactly did you dump your game?

**Comment by Slender1264** [comment]
> 
> 
> How exactly did you dump your game?

I didn't dump it from my own switch, instead got the file from the internet.
Also the file is a .xci and it's version is 1.1.0
I have to mention that the rom is trimmed but i don't think it'd create such a problem.

**Comment by FearlessTobi** [comment]
Either it being pirated or it being trimmed is the issue here, as expected already by me for a long time. I tried working around this, but there's not much more I can really do as you're using a pirated ROM.
