### ISSUE TITLE
Rumble Support

### ISSUE THREAD

**Issue by bytesandwich** [yuzu-emu/yuzu#3894]
This issue is to complete rumble support.

# Summary
we break out all the data and process it, we just don't vibrate the controller itself. Ultimately we just want to call SDL to update the rumble state and such.

https://github.com/yuzu-emu/yuzu/blob/fe2173429a678a497207deb5849438ed7bccbc35/src/core/hle/service/hid/controllers/npad.cpp#L513

# Background
@FearlessTobi already did a v0 of this change:

https://github.com/yuzu-emu/yuzu/compare/master...FearlessTobi:new-rumble

`input_common` code uses the factory pattern so that the implementation of the devices is completely independent of what the emulation core sees. 

The emulation core gets a `ButtonDevice` for each of the buttons and a `AnalogDevice` for each of the joysticks.

This works well for everything that is an `InputDevice` aka something that the emu core will read state from, but that doesn't really work for rumble, which is more like an `OutputDevice`. 

We tried adding `SendFeedback` to the `InputDevice` class, but that doesn't really make sense since an Input device represents each individual button or analog on a controller, and not the whole controller itself.

Let's add a new abstraction for `OutputDevice` which has a `SetState` virtual method and `RumbleDevice` should be an Output device that takes whatever the core needs to pass to it.

Maybe the stuff for `SDLHaptic` can be moved directly into `SDLJoystick` instead of in its own class.

**Comment by bytesandwich** [comment]
It seems like citra doesn't have rumble and input_common came from citra?

**Comment by jojodunet** [comment]
> from

@bytesandwich Could you please get in touch with @GoldenX86 on this discord server https://discord.gg/u77vRWY ? 
He will allow you to help devs team on the project.

**Comment by jojodunet** [comment]
> It seems like citra doesn't have rumble and input_common came from citra?

@bytesandwich Could you please get in touch with @GoldenX86 on this discord server https://discord.gg/u77vRWY ? 
He will allow you to help devs team on the project.
