### ISSUE TITLE
Timezone Select Support

### ISSUE THREAD

**Issue by lgjx123** [yuzu-emu/yuzu#3897]
Custom RTC setting seems no effect in Animal Crossing.
Maybe yuzu team can consider developing a feature, like Timezone Select.

**Comment by nyakze** [comment]
RTC does have an effect, but you have to manually change it everytime, which is troublesome. Timezone select would be nice.

**Comment by nyakze** [comment]
It's now added to latest EA build. Though it needs much more timezones or a clear selection of offset from UTC (+3/-3, etc)

**Comment by lgjx123** [comment]
> It's now added to latest EA build. Though it needs much more timezones or a clear selection of offset from UTC (+3/-3, etc)

good job!
