### ISSUE TITLE
Frequent Crashes Following "Prometheus" Early Access Update

### ISSUE THREAD

**Issue by NonstopSuperguy** [yuzu-emu/yuzu#3898]
These crashes occur in every game I've tried at seemingly random times. No error codes are displayed; the program simply closes. 

Games involved: 
- Luigi's Mansion 3
- Super Mario Odyssey
- Pokemon Sword

System:
- AMD RYZEN 9 3900X
- Nvidia GTX 1080Ti
- 16GB DDR4@3600MHz

Games run almost flawlessly until the crashes occur. In most cases they occur during area transitions or as dialogue/actions are triggered.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4602755/yuzu_log.txt)

**Comment by Iphex** [comment]
I got similar issues in CTR Nitro Fueled, also during transition (loading screen). Looking at task manager, it seems like yuzu suddenly jumps to an insane RAM value. I have 32gb RAM in my system and YUZU takes up 25 GB! Even forced Chrome to close itself.

System:
AMD Ryzen 3700x
AMD 5700 xt
32 DDR4@3200MHz 16cl
YUZU running on an SSD
Vulkan, Async, Multicore, Docked.

Next time it crashes I will supply the log file

**Comment by german77** [comment]
This issue is too generic and old. Please reopen any individual issues that still happen for each game.
