### ISSUE TITLE
Graphics totally broken in Samurai Shodown

### ISSUE THREAD

**Issue by awksie** [yuzu-emu/yuzu#3900]
Hello, I was advised to open an issue for this game by GoldenX86 on Discord.
Launching the game Samurai Shodown gives no useful video output. At first, the display is completely blue, and then the main menu is blue with black bars where the menu options should be.
Screenshot:
![unknown](https://user-images.githubusercontent.com/8469453/81468343-81689400-91a4-11ea-85cb-c379f3072ce9.png)
I am testing using yuzu Early Access 517 | HEAD-199a85ff2. I have tried using all three GPU accuracy levels, GPU fast time on/off, OpenGL and Vulkan, Multi-core on and off, Async on and off, and even tried disabling the update and DLC packages in the game's options, but literally nothing had any effect at all.

Log file: 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4603002/yuzu_log.txt)

My hardware: Ryzen 9 3900X | GeForce RTX 2080 Super
Let me know if you need any additional information.

**Comment by chz8494** [comment]
just tested this game on my rig: i7-6700, 64G RAM and Nvdia 1080. I can boot up game but some graphic can only be displayed under Vulkan and OpenGL with single core

**Comment by benderscruffy** [comment]
can be closed now
goes ingame with graphics now
![Screenshot 2023-05-13 133921](https://github.com/yuzu-emu/yuzu/assets/2696404/bcb68e01-1784-42f1-a6af-07c2931c2eab)
