### ISSUE TITLE
Problems persists with Luigis Mansion 3

### ISSUE THREAD

**Issue by kevinmarangoni** [yuzu-emu/yuzu#3901]
Im using yuzu early access (ver 518) with multicore and im experiencing problems with Luigi's Mansion 3 (ver 1.0.0). I use OpenGL, Async on and all recomended mods. It just freeze and crash, closing yuzu.  

Even before de prometheus update i had that same problem. It gets worse with Vulkan.

My setup is :
Ryzen 5 3400g Turbo to 4.2ghz (and i tried at base clock 3.7 as well)
GTX 1660 (Turing Architecture)
24gb (2x8 dual channel + 1 single channel)

**Comment by benderscruffy** [comment]
@KevinMarangoni 
is this still a problem
