### ISSUE TITLE
Feature Request: Possible to add support for multicontent NSP's?

### ISSUE THREAD

**Issue by Masamune3210** [yuzu-emu/yuzu#3906]
Version:![image](https://user-images.githubusercontent.com/1053504/81489436-fa1a2f80-923a-11ea-8538-e74219d18237.png)

Would it be possible to add support for multicontent NSP files? They are NSP files that have been packed together with their updates and dlc, which makes them easier to store and manage. As far as I know the most that would have to do is scan for more than one cmnt.xml and install the resulting nca files as well as the main one but I could be wrong

**Comment by deadair3210** [comment]
Please excuse me and close this if this is not the right place or isnt accepted

**Comment by ExsertWizard** [comment]
Afaik, that is only possible on cartridge images, you may have mistaken NSP with XCI. yuzu already supports this.

**Comment by deadair3210** [comment]
You can build multicontent nsp files with NSC_BUILDER, they fill the same purpose for the most part as multicontent xci files with the added benefit of being able to install the game and all related files all at once instead of one at a time

**Comment by Masamune3210** [comment]
Any update on this? I can't help much on the coding side of things, but I can help with examples, samples, explanations and the like if needed
