### ISSUE TITLE
Fire Emblem Three Houses pink graphics

### ISSUE THREAD

**Issue by Zane0000** [yuzu-emu/yuzu#3908]
began only with the most recent yuzu early access revision (520). only a problem with open gl renderer. only 'conversation' segments. problem with shaders I think?
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4605198/yuzu_log.txt)

![fire emblem 2](https://user-images.githubusercontent.com/65062059/81491472-f697a000-925c-11ea-943d-686ae358abc1.png)

**Comment by swablueme** [comment]
EA 517 → EA 520 (_purple intensifies_)

**Comment by Zane0000** [comment]
fixed in revision 523
