### ISSUE TITLE
Wireframe persists on EA 518 - Pokemon Sword

### ISSUE THREAD

**Issue by dom2047** [yuzu-emu/yuzu#3911]
PC Specs:

Ryzen 5 3600
RX 5700 XT (Driver Version: 20.4.2)
16GB RAM

Yuzu Settings (multicore enabled, tested in docked and undocked)

OGL (wireframe issue) 17fps or less.

Vulkan (no wireframe issue) 25+ fps but it crashes in less that a minute.

I have dumped the shadercache into the transferable file location and it has not helped. I have seen some users on youtube using this build with the same CPU hitting 30fps flawlessly, I'm assuming its just down to the AMD driver for my GPU which sucks.

Is there any known fix or helper for Vulkan?
![Capture](https://user-images.githubusercontent.com/65119513/81500551-c4bd2280-92ca-11ea-834a-0f879e1fdf36.PNG)

**Comment by Morph1984** [comment]
AMD fixed the wireframe issue on Vulkan after a driver update, they do not really care to fix their opengl drivers due to priority being focused on D3D and Vulkan.
This is an issue with their drivers, not yuzu,

**Comment by dom2047** [comment]
The wireframe does not affect Vulkan it just crashes almost immediately. Wireframe is only on OpenGL.

I'd like to use Vulkan but it won't run for longer than 40 seconds.

**Comment by Morph1984** [comment]
Update your early access version using the installer, this was fixed in EA 520+.

Requesting to close
