### ISSUE TITLE
Diablo III Eternal Collection Graphical Issues AMD RX graphics - vulkan +(Log)

### ISSUE THREAD

**Issue by pow4me123** [yuzu-emu/yuzu#3912]
Anyone have this bug? I use Rx 5700 xt.. the performance of the game is 90% perfect like 60fps overall  but i face this graphical bug!
![Screenshot_1](https://user-images.githubusercontent.com/51249003/81505190-378fc300-92f6-11ea-9f85-ca70bc399fad.png)
 one more 
![Screenshot_2](https://user-images.githubusercontent.com/51249003/81519021-7189b500-9348-11ea-9840-32004a71eac8.png)

LOGS HERE:
[Logs.zip](https://github.com/yuzu-emu/yuzu/files/4625119/Logs.zip)

**Comment by needo2** [comment]
It has been same ever since the first Vulkan builds. Vertex explosion in Diablo III and Xenoblade Chronicles: DE

**Comment by pow4me123** [comment]
> It has been same ever since the first Vulkan builds. Vertex explosion in Diablo III and Xenoblade Chronicles: DE

no one bothered to fix it if can be fixed...it past a long time that i post it and tried latest yuzu and still happens

**Comment by cetinodinson** [comment]
I had the same issue. I hope we get a mod for that. Super Mario has one.

**Comment by pow4me123** [comment]
> I had the same issue. I hope we get a mod for that. Super Mario has one.

yes thats true! i think no one care about this bug/glitch in this game :P

**Comment by pow4me123** [comment]
Problem finally fixed after texture Cache Rewrite update...the only thing remaining is best performance on amd graphics!

**Comment by alymarzouk** [comment]
@pow4me123 Can you please adise how can I update the emulator?
