### ISSUE TITLE
Good Job! : The percentage didn't increase

### ISSUE THREAD

**Issue by ted1030** [yuzu-emu/yuzu#3917]
When I clean the pink goo, the percentage(blue circle) didn't increase on Yuzu 237 and newer versions.
But there was no problem on Yuzu 236 and older versions.
![image](https://user-images.githubusercontent.com/37107237/81520867-12dc2f80-9378-11ea-89d6-1280bb0d7629.png)
Is it a bug?

**Comment by ted1030** [comment]
I compared the difference of yuzu logs between version 523 and 236.
The following appeared in version 523 but not version 236.
[ 293.149396] Debug <Critical> core\memory.cpp:Write:686: Assertion Failed! Mapped memory page without a pointer @ 00000011B9A6CC20
[ 294.686856] Debug <Critical> core\memory.cpp:Write:686: Assertion Failed! Mapped memory page without a pointer @ 00000011AF42B820
[ 295.518057] Debug <Critical> core\memory.cpp:Write:686: Assertion Failed! Mapped memory page without a pointer @ 00000011B9AACC20
[ 296.617413] Debug <Critical> core\memory.cpp:Write:686: Assertion Failed! Mapped memory page without a pointer @ 00000011AF4BB820
[ 299.420384] Debug <Critical> core\memory.cpp:Write:686: Assertion Failed! Mapped memory page without a pointer @ 00000011AF4BBC10
[ 312.065094] Debug <Critical> core\memory.cpp:Write:686: Assertion Failed! Mapped memory page without a pointer @ 00000011B9A6CC20
[ 314.995968] Debug <Critical> core\memory.cpp:Write:686: Assertion Failed! Mapped memory page without a pointer @ 00000011AF42B820
[ 315.231012] Debug <Critical> core\memory.cpp:Write:686: Assertion Failed! Mapped memory page without a pointer @ 00000011AF42B820
[ 324.806634] Debug <Critical> core\memory.cpp:Write:686: Assertion Failed! Mapped memory page without a pointer @ 00000011A20506E0
[ 330.343429] Debug <Critical> core\memory.cpp:Write:686: Assertion Failed! Mapped memory page without a pointer @ 00000011B9B05030

This line appeared in both version 523 and 236, but the line number is different.
Version 523:
[ 202.005365] Kernel.SVC <Error> core\hle\kernel\svc.cpp:MapSharedMemory:1203: Address does not fit within the map region, addr=0x000000170F204000, size=0x0000000000040000
Version 236:
[   6.073729] Kernel.SVC <Error> core\hle\kernel\svc.cpp:MapSharedMemory:1172: Address does not fit within the map region, addr=0x000000170F204000, size=0x0000000000040000

**Comment by german77** [comment]
It's working on mainline 445
![image](https://user-images.githubusercontent.com/5944268/100530299-e671ee80-31b5-11eb-90cf-594167821b7b.png)
