### ISSUE TITLE
Particles/sprites instancing creates heavy spike lags in Pokemon Sword, Win 10

### ISSUE THREAD

**Issue by Baccanno** [yuzu-emu/yuzu#3920]
Followed this guide, async GPU did a lot for enhancing the perf https://github.com/yuzu-emu/yuzu-games-wiki/wiki/pokemon-sword-shield

The game works quite flawlessly with minimal slow-down most of the time (music/FPS stutter a little bit but nothing too important)

However I can notice heavy spikes when particles effects are instantiated. What do I mean
- First pokeball opening creates a heavy lag spike. second works seamlessly.
- First time an attack effect is performed lag occurs, consequent attacks have no spikes.
- Launch battle wave sprite effect causes spikes (not the battle launch itself)
- I just started to play some more example/precision may arise. 

I'm very confident its related to some X Model/Texture being instantiated, then as it cached things go flawlessly. The engine might release the particles/model at a certain moment and then the lag spike will occur again. It might not be only Pokemon Sword related.

System Spec : 2060 RTX/Ryzen 5 3600/32go Ram/Win 10
Yuzu : yuzu-windows-msvc-20200507-e0e0030ec

Please feel free to ask any subsequent infos.
Best

**Comment by Baccanno** [comment]
- Lag occurred at the loading of a sound. (The growl you hear at the beginning of the game)

**Comment by ToxaGaming** [comment]
The spike lags are caused by something called "shader compilation stuttering" where every new effect you encounter and any new animation you see will stutter the first time as yuzu is compiling the shaders into a shadercache. This process it resource intensive, hence why it lags :)

**Comment by Baccanno** [comment]
Allright. Thanks for the info. Is there anyway to precompile those shader to avoid stuttering along the game ?

**Comment by ToxaGaming** [comment]
sadly there is no way to precompile them, you'll just have to endure the stuttering

**Comment by Baccanno** [comment]
Glad you answered, sad to hear. Is there a cache limit implemented somewhere that would cause the shader to be released? Would there be a way to disable the release (I feel I have enough memory for that)

**Comment by ToxaGaming** [comment]
All your compiled shaders are precompiled and loaded to RAM on the next game launch so that yuzu can just "pull" the shaders whenever they're called, so it does not release unused shaders. (this is what I'm guessing it does). However this issue tracker is also meant for developers so i'd be thankful if we could take this discussion to yuzu's Discord servers :)

**Comment by ogniK5377** [comment]
Enable the "Use disk shader cache" option in Emulation->Configure->Graphics
![image](https://user-images.githubusercontent.com/25727384/81560956-c1628d80-93d5-11ea-819a-a8f313d6e9c0.png)

Once you have built the shader once, every time you reboot the game, the shader will be built and cached on the game's launch.

**Comment by EliEron** [comment]
It's worth mentioning that the disk shader cache only applies to OpenGL at the moment. Vulkan does not store its cache, and is therefore reset each time you stop the game. 

So if you want to be able to build a persistent cache, make sure you use OpenGL, and not Vulkan.

**Comment by Baccanno** [comment]
@ogniK5377 @ToxaGaming Thank you for the thorough information. Indeed perf starts are getting better and better. Wonderful work done on this emulator.
