### ISSUE TITLE
Dead Cells screen upside down with Vulkan (Opengl is alright)

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#3928]
![dead](https://user-images.githubusercontent.com/2696404/81648127-c1f43600-9460-11ea-95dd-9bcce57b37bb.PNG)
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4613878/yuzu_log.zip)

**Comment by Magviin** [comment]
Why are you using an emulator for dead cells, there is literally a PC version for both windows and Linux, both of which are controller compatible, so why not get either of those? Oh but wait, this seems like BS because only the a in dead and the Ls and S are upside-down.

**Comment by benderscruffy** [comment]
still a problem in  EA 565

**Comment by benderscruffy** [comment]
now both Yuzu EA and Yuzu both crash out nearly straight away

**Comment by benderscruffy** [comment]
has been fixed
