### ISSUE TITLE
Question: take advantage of VK_EXT_pipeline_creation_cache_control for less stuttering like Cemu?

### ISSUE THREAD

**Issue by oscarbg** [yuzu-emu/yuzu#3931]
Hi,
first sorry for not asking this on Discord #development channel but seems I have no access..
maybe be a noob question, but seeing Cemu 1.19.0 (http://cemu.info/changelog/cemu_1_19_0.txt) takes advantage of VK_EXT_pipeline_creation_cache_control extension for greatly reduced shader stuttering ("asynchronous compilation of shaders and pipelines")
I'm just asking if it makes sense for Yuzu devs of taking advantage of that extension for similar purpose as used by Cemu i.e. reduce stuttering due to ingame shader compilation & pipeline creation..
thanks..

**Comment by goldenx86** [comment]
Some games rely on shaders for gameplay, physics, etc. Async compilation would break them.

**Comment by oscarbg** [comment]
thanks @goldenx86 , interesting note..
 curious how Cemu avoids issues in such cases..

**Comment by mineas312** [comment]
Cemu compiles shaders that are required synchronously and these that would not break games asynchronously. Why yuzu could not do the same in this situation?

**Comment by goldenx86** [comment]
Can be considered, but it's not a priority for now.

**Comment by MysticExile** [comment]
@FearlessTobi There is no reason to keep this issue open, asynchronous shader compilation has already been added with #4443 , According to @ReinUsesLisp this extension is only used with a pipeline cache which we don't have, and even if we did have a pipeline cache Rodrigo said we don't need it.

**Comment by MysticExile** [comment]
Closing this for the reasons stated in my previous comment. If you think this issue is still applicable please open a new issue with a title that is fitting of a feature request along with more detail.
