### ISSUE TITLE
Input translation

### ISSUE THREAD

**Issue by FerLuisxd** [yuzu-emu/yuzu#3933]
The left stick won't translate the input properly, 
For example, whenever I play SSBU there is no way to "walk" you can only run.
So if I move the left stick SLIGHTLY it will inmediatly run which is not intended.

This happens on the 530 build

**Comment by goldenx86** [comment]
Use the "Set Analog Stick" buttons, don't map the axis directly.

**Comment by FerLuisxd** [comment]
true!
