### ISSUE TITLE
early access 533 Control input issue Pokken dx

### ISSUE THREAD

**Issue by avid789** [yuzu-emu/yuzu#3934]
![screenshot 1](https://user-images.githubusercontent.com/65339752/81919266-862bae80-95cf-11ea-993f-d9a63e1f7f9e.png)
I dont know if im posting in the right place.
Im new here 
Basically ive got an issue selecting controllers 
I couldnt make sense of the log file.
Sorry i dont think im going to be much help on here.
Kind regards 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4627366/yuzu_log.txt)

**Comment by auranticus** [comment]
You should link your Discord to your Patreon account and open this issue in there. Iirc they won’t support EA builds on Github

**Comment by avid789** [comment]
Thanks
