### ISSUE TITLE
Wifi Crash Pokemon Shield/Sword Update 1.1.0

### ISSUE THREAD

**Issue by Baccanno** [yuzu-emu/yuzu#3947]
Could someone either update the mod for wifi crash, or let met know the steps for looking at modding the update myself. I didn't find any info on the mod in the issue list.
The pchtxt file seems quite simple but which tool should I use to look into this ?

Or was it already looked into and it appears the bugfix is not feasible with the new version ?

Best,

**Comment by bukyapavankumar** [comment]
Just don't configure y button when playing that game

**Comment by Baccanno** [comment]
> Just don't configure y button when playing that game

The Y button si quite useful in battles. Now I could do that (And I did), but just had a look at the mod file and it does not look very complicated. I just wonder what should be done to update the patch.

Would it need a hacked switch or can it be done by debugging the emulator solely ? Is this only an address that has changed or other mecanism ? 

Original patch by @theboy181
`@nsobid-8DAFEDBB5BE81C2C0160161159A791E67E3D6162
// nsobid found in main @ offset 0x40

# pkmS

@flag print_values
@flag offset_shift 0x100

// Wifi Fix

@enabled
00E766E4 1F2003D5
@stop
`

**Comment by CrusadingNinja** [comment]
Fixed with #5920. The mod is no longer needed.
