### ISSUE TITLE
#2385: Issue new Open: Problem with Switchable Grafic

### ISSUE THREAD

**Issue by suerion** [yuzu-emu/yuzu#3950]
Please look on #2385

**Comment by MysticExile** [comment]
Please don't open issues to bring attention to another issue

**Comment by suerion** [comment]
The other issue is closed already :( but this issue is already given :(

**Comment by goldenx86** [comment]
Yuzu is not compatible with any Terascale GPU, or any Intel GPU older than Gen9 (Gen8 in Linux with the IRIS driver).
