### ISSUE TITLE
Crash in Seaside Kingdom

### ISSUE THREAD

**Issue by SgtPepperman** [yuzu-emu/yuzu#3957]
When I'm fighting that octopus boss at Bubblaine, my emulator crashes. Specifically when the boss is close to the checkpoint where's an island of grass and lava. The game makes a very awful sound before crashes (a noisy screech).
I tried everything: Changing to Vulkan, deactivating the mods, force 30 FPS, the crash workaround, and ASYNC.
Do you think it is because of my PC? Everything worked well until this point in the game.
Specs:

Windows 10 64 bit
Intel Core i3 8100 3.6 GHz
8 GB RAM
NVIDIA GeForce GT 1030 2 GB

Thank you.

**Comment by BSoDGamingYT** [comment]
Disable the game update. this issue doesn't happen in 1.0.0

**Comment by SgtPepperman** [comment]
Last time I got this.
![image](https://user-images.githubusercontent.com/65516972/82164768-d331ae00-9877-11ea-8612-4940c02f7edc.png)

**Comment by SgtPepperman** [comment]
> Disable the game update. this issue doesn't happen in 1.0.0

Thanks, that was the solution.
Do you know why does it happen when the game has the update?

**Comment by momala454** [comment]
the game is "seaside kingdom" ?

**Comment by FigureItOut1990** [comment]
Just want to verify the same crashes in both opengl and vulkan on Yuzu 258, SMO 1.3.0. Fixed by disabling updates for now.

**Comment by ManApart** [comment]
Same crash and fix in EA 565

**Comment by G-Spawn** [comment]
This shouldn't happen anymore on updated yuzu versions. Please reopen and provide log should it still persist for you somehow.
