### ISSUE TITLE
Crash in Pokemon Sword And Shield

### ISSUE THREAD

**Issue by liyuhaolol** [yuzu-emu/yuzu#3959]
version 540
if you enable multicore CPU.
after you defect Leon，Game start show subtitles, it will 100% crash.
disable multicore CPU can fix this.
this is a bug?

**Comment by Zeroksas** [comment]
Upload log file. Does it crash on both vulkan and openGL?

**Comment by FernandoS27** [comment]
Yeah it's bug but it doesn't happen in every machine, making it a nuance to debug.

**Comment by ultayfalabo1121** [comment]
I've been facing the same issue, except that disabling multicore doesn't work. Any ideas?
