### ISSUE TITLE
Unimplemented texture format "B8G8R8A8_SRGB" on vulkan

### ISSUE THREAD

**Issue by Zeroksas** [yuzu-emu/yuzu#3960]
Debug <Critical> video_core\renderer_vulkan\maxwell_to_vk.cpp:SurfaceFormat:221: Assertion Failed! Unimplemented texture format with pixel format=50

Required by: Bravely Default II

**Comment by Morph1984** [comment]
This is B8G8R8A8_SRGB

**Comment by Morph1984** [comment]
DXT1_SRGB is already implemented on Vulkan

**Comment by Zeroksas** [comment]
> DXT1_SRGB is already implemented on Vulkan

I think I mislead you. I first tested on EA build and it gave format 50 but now when I tried on week old mainline it gave:
Debug video_core\renderer_vulkan\maxwell_to_vk.cpp:SurfaceFormat:221: Assertion Failed! Unimplemented texture format with pixel format=49 
which is VK_FORMAT_B8G8R8A8_SINT = 49

**Comment by Morph1984** [comment]
Which EA version is that btw? Can you upload the log?

**Comment by Zeroksas** [comment]
EA 540
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4645853/yuzu_log.txt)

**Comment by Morph1984** [comment]
I mean the one with

```
video_core\renderer_vulkan\maxwell_to_vk.cpp:SurfaceFormat:221: Assertion Failed! Unimplemented texture format with pixel format=49
```

**Comment by Zeroksas** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4645881/yuzu_log.txt)

**Comment by Morph1984** [comment]
and that one is from which EA?

**Comment by Zeroksas** [comment]
It's not from EA. I compiled it on my own pc from week old mainline code. It has formats defined like this:
typedef enum VkFormat {
    VK_FORMAT_UNDEFINED = 0,
    VK_FORMAT_R4G4_UNORM_PACK8 = 1,
    VK_FORMAT_R4G4B4A4_UNORM_PACK16 = 2,
    VK_FORMAT_B4G4R4A4_UNORM_PACK16 = 3,
    VK_FORMAT_R5G6B5_UNORM_PACK16 = 4,
    VK_FORMAT_B5G6R5_UNORM_PACK16 = 5,
    VK_FORMAT_R5G5B5A1_UNORM_PACK16 = 6,
    VK_FORMAT_B5G5R5A1_UNORM_PACK16 = 7,
    VK_FORMAT_A1R5G5B5_UNORM_PACK16 = 8,
    VK_FORMAT_R8_UNORM = 9,
    VK_FORMAT_R8_SNORM = 10,
    VK_FORMAT_R8_USCALED = 11,
    VK_FORMAT_R8_SSCALED = 12,
    VK_FORMAT_R8_UINT = 13,
    VK_FORMAT_R8_SINT = 14,
    VK_FORMAT_R8_SRGB = 15,
    VK_FORMAT_R8G8_UNORM = 16,
    VK_FORMAT_R8G8_SNORM = 17,
    VK_FORMAT_R8G8_USCALED = 18,
    VK_FORMAT_R8G8_SSCALED = 19,
    VK_FORMAT_R8G8_UINT = 20,
    VK_FORMAT_R8G8_SINT = 21,
    VK_FORMAT_R8G8_SRGB = 22,
    VK_FORMAT_R8G8B8_UNORM = 23,
    VK_FORMAT_R8G8B8_SNORM = 24,
    VK_FORMAT_R8G8B8_USCALED = 25,
    VK_FORMAT_R8G8B8_SSCALED = 26,
    VK_FORMAT_R8G8B8_UINT = 27,
    VK_FORMAT_R8G8B8_SINT = 28,
    VK_FORMAT_R8G8B8_SRGB = 29,
    VK_FORMAT_B8G8R8_UNORM = 30,
    VK_FORMAT_B8G8R8_SNORM = 31,
    VK_FORMAT_B8G8R8_USCALED = 32,
    VK_FORMAT_B8G8R8_SSCALED = 33,
    VK_FORMAT_B8G8R8_UINT = 34,
    VK_FORMAT_B8G8R8_SINT = 35,
    VK_FORMAT_B8G8R8_SRGB = 36,
    VK_FORMAT_R8G8B8A8_UNORM = 37,
    VK_FORMAT_R8G8B8A8_SNORM = 38,
    VK_FORMAT_R8G8B8A8_USCALED = 39,
    VK_FORMAT_R8G8B8A8_SSCALED = 40,
    VK_FORMAT_R8G8B8A8_UINT = 41,
    VK_FORMAT_R8G8B8A8_SINT = 42,
    VK_FORMAT_R8G8B8A8_SRGB = 43,
    VK_FORMAT_B8G8R8A8_UNORM = 44,
    VK_FORMAT_B8G8R8A8_SNORM = 45,
    VK_FORMAT_B8G8R8A8_USCALED = 46,
    VK_FORMAT_B8G8R8A8_SSCALED = 47,
    VK_FORMAT_B8G8R8A8_UINT = 48,
    VK_FORMAT_B8G8R8A8_SINT = 49,
    VK_FORMAT_B8G8R8A8_SRGB = 50,

**Comment by Morph1984** [comment]
on my end compiled mainline gave me 50, not 49

**Comment by Morph1984** [comment]
try add my pr to see if that fixes it on your end, because I am certain those are the correct ones.

**Comment by Zeroksas** [comment]
Tried both while assert message is gone still crash on
Debug <Critical> video_core\renderer_vulkan\vk_rasterizer.cpp:SetupImage:1132: Assertion Failed! Unimplemented code!
Probably there are other issues not related to this.

**Comment by Morph1984** [comment]
That one is similar to what some other games have like The Walking Dead series of games.

**Comment by Morph1984** [comment]
its unrelated to this
