### ISSUE TITLE
Black sky in Girls und Panzer Dream Tank Match DX since #3734 was merged

### ISSUE THREAD

**Issue by wilkovatch** [yuzu-emu/yuzu#3962]
Since #3734 was merged (yuzu-emu/yuzu@4e37825 and mainline 239) the sky in Girls und Panzer Dream Tank Match DX is completely black. In some cases the clouds are visible albeit corrupt (this indicates that the add/mul operators modified by #3734 are not working properly). This bug happens both with OpenGL and Vulkan.

Tested on Windows 10, using both an Nvidia GTX 1070 (OpenGL and Vulkan) and Intel UHD 630 (Vulkan)

Log (probably useless in this case): [yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4646966/yuzu_log.zip)

Title screen with the bug (4e37825)
![1](https://user-images.githubusercontent.com/29335145/82262084-91306700-9960-11ea-84e7-ad2e6aef25ef.jpg)

Title screen without the bug (d1e7cf3)
![2](https://user-images.githubusercontent.com/29335145/82262090-9392c100-9960-11ea-95f6-395fcb06c974.jpg)

Ingame with the bug (4e37825), corrupt clouds are visible
![3](https://user-images.githubusercontent.com/29335145/82262095-95f51b00-9960-11ea-94f6-32ae386431b6.jpg)

Ingame without the bug (d1e7cf3)
![4](https://user-images.githubusercontent.com/29335145/82262126-9f7e8300-9960-11ea-844d-69d07593db63.jpg)

**Comment by darkfalzx** [comment]
Still broken as of mainline 352. Bummer - the game runs great otherwise.

**Comment by obronca** [comment]
30 December, still no fixes

**Comment by wilkovatch** [comment]
Fixed as of mainline 701.

Screenshot (this is OpenGL, but it's fixed on Vulkan too):
![Screenshot (1565)](https://user-images.githubusercontent.com/29335145/127215078-49971ad0-361e-463e-83ce-818408531a95.jpg)
