### ISSUE TITLE
Super Mario Odyssey - line visible in shading on OpenGL

### ISSUE THREAD

**Issue by ActualMandM** [yuzu-emu/yuzu#3963]
There is a line in the middle of the shading when using OpenGL.

yuzu mainline 258

GeForce RTX 2080
Ryzen R9 3950X

Emulator:
<img width="960" alt="2020-05-18_19-44-23" src="https://user-images.githubusercontent.com/15317421/82278856-0c355580-9940-11ea-9f41-68ad6441c1f4.png">

Console:
<img width="960" alt="2020-05-18_19-31-35" src="https://user-images.githubusercontent.com/15317421/82278858-0f304600-9940-11ea-8da5-ee75c05e0e84.png">

Vulkan does not have this issue.
<img width="960" alt="2020-05-18_19-47-14" src="https://user-images.githubusercontent.com/15317421/82279018-61716700-9940-11ea-9851-566117447365.png">

Log:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4647941/yuzu_log.zip)

**Comment by slashiee** [comment]
Fixed with #4967/EA 1144
<img width="961" alt="2020-11-23_11-56-37_yuzu" src="https://user-images.githubusercontent.com/15317421/100008925-ecfe0180-2d82-11eb-9484-8f1a8da293cc.png">
