### ISSUE TITLE
Very Poor FPS in Sand Kingdom

### ISSUE THREAD

**Issue by thundersdestiny** [yuzu-emu/yuzu#3968]
Computer Specs: AMD Ryzen 7 2600x, 32 GB Ram, RTX 2070

The game is playable for the most part in the first 2 kingdoms running around 30-60 fps with some dips and audio glitches but once I got to the Sand Kingdom I saw substantial dips in framerate. It struggles to run over 15 fps despite changing many options.

**Comment by goldenx86** [comment]
Ask for support on the Discord server or the Forums please.
