### ISSUE TITLE
OpenGl: using textureLod not supported for sampler2DArrayShadow

### ISSUE THREAD

**Issue by KytoDragon** [yuzu-emu/yuzu#3969]
When loading up BOTW (version 1.6.0 + DLC 1,2) on an AMD R9 290 graphics card multiple shaders will fail to compile with the following error:

```
[  87.355571] Render.OpenGL <Error> video_core\renderer_opengl\gl_shader_util.cpp:LoadShader:48: Error compiling compute shader:
Compute shader failed to compile with the following errors:
ERROR: 0:3698: error(#202) No matching overloaded function found: textureLod
ERROR: error(#273) 1 compilation errors.  No code generated
 
[  87.355590] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.h:LoadProgram:79: Error linking shader:
Compute shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 
```
 

This is because the textureLod(sampler2DArrayShadow, vec4, float) function requires the [EXT_texture_shadow_lod](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_shadow_lod.txt) extension which is not supported on that graphics card.

According to a similar issue in another Project (https://github.com/KhronosGroup/SPIRV-Cross/issues/207) you could use the textureGrad function as a workaround for sampler2DArrayShadow sampling.

yuzu Mainline 260
Full log with shader source: https://pastebin.com/WQ6U3va0

**Comment by tarceri** [comment]
Not the Linux opensource drivers support this extension but it fails to compile it because the shader does not enable it as its missing:

#extension GL_EXT_texture_shadow_lod : require

**Comment by RealJohnGalt** [comment]
http://ix.io/2npq Fixes that shader linking, however then there is a new unrecoverable crash (as in reboot required).
