### ISSUE TITLE
Would it be OK if I submitted yazu to the AUR

### ISSUE THREAD

**Issue by rhysperry111** [yuzu-emu/yuzu#3971]
Currently, to download yazu on Arch Linux it is a bit of a pain. Would you guys be ok if I created a package for the AUR. I would greatly appreciate if you also mentioned this in the installation page of the wiki

**Comment by ToxaGaming** [comment]
yuzu is already on the AUR last time I checked

**Comment by rhysperry111** [comment]
I can't seem to find it: https://aur.archlinux.org/packages/?O=0&K=yazu

**Comment by iCaitlyn** [comment]
@rhysperry111 Typo, here you go: https://aur.archlinux.org/packages/?O=0&SeB=nd&K=yuzu

**Comment by rhysperry111** [comment]
Sorry for opening the issue. I have been reading the name wrong this whole time
