### ISSUE TITLE
Ninja Saviours Color Errors - Yuzu 261- AMD card

### ISSUE THREAD

**Issue by orderorder** [yuzu-emu/yuzu#3973]
Yuzu 261 - Color errors - This seems to happen in AMD graphic cards: Tested in RX580 and APU R7 240  

![Ninja Savior](https://user-images.githubusercontent.com/7293829/82581875-83155d00-9b91-11ea-85d5-15389a05d8aa.png)

**Comment by benderscruffy** [comment]
happens with both Opengl and Vulkan
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4666703/yuzu_log.zip)

**Comment by benderscruffy** [comment]
can be closed 
see #5317

**Comment by G-Spawn** [comment]
> can be closed see #5317

Thank you Bender
