### ISSUE TITLE
Fire Emblem Three Houses eye mesh glitch on OpenGL

### ISSUE THREAD

**Issue by vapopescu** [yuzu-emu/yuzu#3984]
Some meshes have a thin wireframe rendered when they shouldn't. This happens on the eyes of all 3D characters, causing them to look like their irises are white from a distance. Some background mountains in the map '~~Remire~~ Mountains' (Oil and Water paralogue and optional battles) that appear during the combat animations also present this issue (~~will take a screenshot when I get that map again~~).

![Closeup 1](https://user-images.githubusercontent.com/14800198/82671782-b8788400-9c3f-11ea-9aaf-f4dadba0f67e.png)
![Closeup 2](https://user-images.githubusercontent.com/14800198/82671790-ba424780-9c3f-11ea-9f34-22a7aed18dae.png)

Edit: I should also mention that this happens everytime the characters are rendered, not only cutscenes.
![Level Up](https://user-images.githubusercontent.com/14800198/82672954-5a4ca080-9c41-11ea-84b2-426517e9d401.png)

Edit 2: Monster battle on 'Mountains'. You can see the glitch on the rocks and mountains in the background as well as the monster's eyes.

![Mountains 1](https://user-images.githubusercontent.com/14800198/82730835-f094cb00-9d02-11ea-8355-8c1b688ece5d.png)
![Mountains 2](https://user-images.githubusercontent.com/14800198/82730832-eecb0780-9d02-11ea-8377-8f6abffbcd49.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4668265/yuzu_log.txt)

Using Yuzu EA 548
AMD Ryzen 3700X
AMD Radeon Vega 56

**Comment by soredake** [comment]
Still present.

**Comment by vapopescu** [comment]
Fixed as of EA1905. Public release has not merged the fixes yet.
![Screenshot during chapter battle.](https://user-images.githubusercontent.com/14800198/133084351-0cf2cc2e-756a-4519-aba7-af083797bb9e.png)
![Screenshot during free roam.](https://user-images.githubusercontent.com/14800198/133085706-c946b161-36f5-49c2-b804-6cfcba79d62d.png)
![Screenshot during support conversation.](https://user-images.githubusercontent.com/14800198/133085847-989e15f3-3bac-4921-9417-7ae07075f94e.png)
