### ISSUE TITLE
random crashs pokemon sword

### ISSUE THREAD

**Issue by alonmyburgh** [yuzu-emu/yuzu#3985]
yuzu EA 543
using Vulkan, multicore.
during play, the game crashes (randomly).
I'm attaching the full log.
looks like the issue is:
HW.Memory <Error> core\memory.cpp:Read:641: Unmapped Read32
or
Assertion Failed! Unimplemented shadow convert format: 8

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4670045/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
