### ISSUE TITLE
here was an error while attempting to install the provided file.

### ISSUE THREAD

**Issue by cd781107** [yuzu-emu/yuzu#3987]
Install yuzu
keys and sysdata
Have already been set
Download Pokemon Sword
After opening, the following text appeared

there was an error while attempting to install the provided file. lt could have an incorrect format or be missing metadate. please double-check your file and try again

How to solve this

**Comment by Joey11904** [comment]
can you upload a screenshot here?

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord server for support requests.
Thanks
