### ISSUE TITLE
The Legend of Zelda Breath of the Wild crashes on Turing GPU's

### ISSUE THREAD

**Issue by MysticExile** [yuzu-emu/yuzu#3988]
The Legend of Zelda Breath of the Wild crashes on Turing (GTX 16XX & RTX20XX) GPU's when closing the inventory.

Steps to reproduce:
* Press '+' to get into the inventory
* Press 'B' to exit the inventory
If performed correct the game should now freeze

Here is a [log](https://github.com/yuzu-emu/yuzu/files/4674602/yuzu_log.zip)
[And here is a video of it in action](https://streamable.com/sic50c)

**Comment by MysticExile** [comment]
A little update on this issue, I can no longer get in-game on Turing. Here is a log [yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4828320/yuzu_log.zip)

**Comment by MysticExile** [comment]
No longer an issue

**Comment by MysticExile** [comment]
Workaround for this issue is enabling "Fast GPU Time", but it's still an issue so this issue should remain open.

**Comment by Morph1984** [comment]
This issue has been reported to be fixed, closing.
