### ISSUE TITLE
yuzu Unable to load

### ISSUE THREAD

**Issue by cd781107** [yuzu-emu/yuzu#3990]
Install yuzu
keys and sysdata
Have already been set
Download Pokemon Sword
After opening, the following text appeared

there was an error while attempting to install the provided file. lt could have an incorrect format or be missing metadate. please double-check your file and try again

How to solve this
![123](https://user-images.githubusercontent.com/65854230/82827338-6c4c6e80-9ee1-11ea-84c6-881ff6f32b75.jpg)

**Comment by MysticExile** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord server for support requests.
Thanks
