### ISSUE TITLE
Add more information about the running game

### ISSUE THREAD

**Issue by jojodunet** [yuzu-emu/yuzu#3997]
To the devs team.

Hi team,

When a game is launched, and on the Yuzu window corner,

Could you please to complete the [Game Title] with the following ?
*The [Game ID], 
*The [Game launched version] ( ex : [v1.0.0] ), 
*The [Quantity of DLC running] ( ex: [14 DLC] ) 

Preview for example :

[Minecraft Dungeons][01006C100EC08000][v1.0.0][14DLC]

This will help to see the information about the running game on the screenshoots in #media discord.

**Comment by G-Spawn** [comment]
Satisfied by https://github.com/yuzu-emu/yuzu/pull/4063 to at least show game version in title bar. Listing dlc would be a little extra (and you can already confirm this in game properties or the ui listing for addons)
