### ISSUE TITLE
Things that should be ported over from Citra

### ISSUE THREAD

**Issue by FearlessTobi** [yuzu-emu/yuzu#40]
[This](https://pastebin.com/ECBKedRb) is a list @jroweboy posted, for features that would be good to be ported over from Citra. The checked ones are already implemented.

- [ ] [#3027](https://github.com/citra-emu/citra/pull/3027)  (In review)
- [x] [#3001](https://github.com/citra-emu/citra/pull/3001)
- [x] [#3116](https://github.com/citra-emu/citra/pull/3116)
- [x] [#3333](https://github.com/citra-emu/citra/pull/3333)
- [x] [#3005](https://github.com/citra-emu/citra/pull/3005)
- [x] [#2972](https://github.com/citra-emu/citra/pull/2972)
- [x] [#3240](https://github.com/citra-emu/citra/pull/3240)
- [x] [#3052](https://github.com/citra-emu/citra/pull/3052)
- [x] [#3034](https://github.com/citra-emu/citra/pull/3034)
- [x] [#3030](https://github.com/citra-emu/citra/pull/3030)
- [x] [#3318](https://github.com/citra-emu/citra/pull/3318)
- [x] [#3109](https://github.com/citra-emu/citra/pull/3109)
- [x] [#2949](https://github.com/citra-emu/citra/pull/2949)
- [x] [#3295](https://github.com/citra-emu/citra/pull/3295)
- [x] [#3306](https://github.com/citra-emu/citra/pull/3306)
- [x] [#3093](https://github.com/citra-emu/citra/pull/3093)
- [x] [#3336](https://github.com/citra-emu/citra/pull/3336)
- [x] [#2912](https://github.com/citra-emu/citra/pull/2912)
- [x] [#2918](https://github.com/citra-emu/citra/pull/2918)
- [x] [#2982](https://github.com/citra-emu/citra/pull/2982)
- [x] [#2849](https://github.com/citra-emu/citra/pull/2849)
- [x] [#3320](https://github.com/citra-emu/citra/pull/3320)
- [x] [#3352](https://github.com/citra-emu/citra/pull/3352)
- [x] [#3275](https://github.com/citra-emu/citra/pull/3275)
- [x] [#3064](https://github.com/citra-emu/citra/pull/3064)
- [x] [#3043](https://github.com/citra-emu/citra/pull/3043)
- [x] [#3184](https://github.com/citra-emu/citra/pull/3184)
- [x] [#3101](https://github.com/citra-emu/citra/pull/3101) 

PRs by lioncash which he will update himself
- [x] [#3161](https://github.com/citra-emu/citra/pull/3161)
- [x] [#3262](https://github.com/citra-emu/citra/pull/3262)
- [x] [#3263](https://github.com/citra-emu/citra/pull/3263)
- [x] [#3264](https://github.com/citra-emu/citra/pull/3264)
- [x] [#3266](https://github.com/citra-emu/citra/pull/3266)
- [x] [#3294](https://github.com/citra-emu/citra/pull/3294)
- [x] [#3312](https://github.com/citra-emu/citra/pull/3312)

Feel free to take over one of the mentioned PRs. Just leave a comment and I will mention it in the list. I will try to keep the list up to date while we are making more progress.

**Comment by N00byKing** [comment]
Remove 3318, not Relevant (as in probably already fixed 'n stuff)

**Comment by N00byKing** [comment]
Done:
- 3052 (Proposed)
- 3295 (Proposed)
- 3306 (Proposed)
- 3333 (Merged)

**Comment by nkatz565** [comment]
#3081 Isn't relevant. Whoever remade the about box for Yuzu did it properly, and the issues described here don't occur.

**Comment by spycrab** [comment]
@nkatz565 I just copied the layout from citra ``master`` and modified a bit, so the fix is already applied ^^.

**Comment by nkatz565** [comment]
#2829 appears to already be in Yuzu. The Citra PR was from back in July which was probably before Yuzu forked since It's the same commit on both Yuzu and Citra

**Comment by nkatz565** [comment]
#2949 only had one relevant change, see #57

**Comment by lioncash** [comment]
I'll move over all the stuff that was done by me, so no one else has to take on the burden of doing it.

**Comment by Subv** [comment]
We need https://github.com/citra-emu/citra/pull/3101 too

**Comment by FearlessTobi** [comment]
I've added it to the list

**Comment by VishalRocks** [comment]
Can I take up 3184?

**Comment by N00byKing** [comment]
@VishalRocks if youvwant to sure, you can do so and submit a PR, note that i already have a PR open for the same Issue

**Comment by VishalRocks** [comment]
In that case I will take up 3101, if its fine.

**Comment by N00byKing** [comment]
@VishalRocks Do that, though when I began working on it i was told to stop on the Discord channel because @Subv wasnt finished yet. That was a while ago though, so I guess now is as good time as any to start so knock yourself out i guess

**Comment by VishalRocks** [comment]
Thanks for the heads up

**Comment by VishalRocks** [comment]
Completed it..will test it and submit the pull request for review

**Comment by superheri** [comment]
Shouldn't there be the auto-updator from citra too?

And it would be nice if when the multi folders is in citra, that it would be ported here too.

**Comment by greggameplayer** [comment]
All your things have been merged so please close this issue

**Comment by N00byKing** [comment]
@greggameplayer no they have not. See #194 and #102

**Comment by greggameplayer** [comment]
@N00byKing ok but it's not listed on the first post

**Comment by N00byKing** [comment]
What are you talking about? The list includes 2 PRs still in Review, unmerged

**Comment by ChristoferMinestar** [comment]
Dark theme?

**Comment by Hexagon12** [comment]
All PRs have been merged into Yuzu from Citra from this list. We constantly make merges from Citra if it's applicable here.

Requesting to close, as this issue has completed it's purpose.

**Comment by FearlessTobi** [comment]
@Hexagon12 This isn't true as https://github.com/yuzu-emu/yuzu/pull/194 is still waiting to get merged, but I'm fine with closing this PR anyway as it has lost its relevance.
