### ISSUE TITLE
ACNH & SMO Crashing

### ISSUE THREAD

**Issue by w3bb** [yuzu-emu/yuzu#4015]
https://webber.rocks/a56d21c79fa0f1.txt
https://webber.rocks/706f35841ecd2d.txt 

ACNH crashes after the first text box pops up but before any text is actually displayed. The intial crash for Super Mario Odyssey happened as the camera was zooming down on Mario at the beginning of the game. I wasn't able to get the logs from then, but now it crashes before the game even starts, so sadly I can't reproduce that exactly.

**Comment by BSoDGamingYT** [comment]
Please use the discord for this kind of problem. This is an issue tracker for developers, not a support forum

**Comment by w3bb** [comment]
I figured it was bug, sorry about that then. Is there a place other than Discord that I can get support?

**Comment by w3bb** [comment]
Sorry, figured it was a bug
