### ISSUE TITLE
Add play time like Cemu

### ISSUE THREAD

**Issue by StreetModeTS** [yuzu-emu/yuzu#4018]
Hi team,

I wonder if it would be possible that you add to the menu of yuzu the time playing  for each game like The emulator Cemu

Thank you

**Comment by Pab10Suarez** [comment]
it would be cool to see game time

**Comment by ipkpjersi** [comment]
I'm a bit surprised to see this hasn't been implemented. RPCS3 and CEMU both have this functionality. Are there any blockers preventing this (like there was for Xenia IIRC)?

**Comment by v1993** [comment]
This is going to be a part of a larger interface rework.

**Comment by jelliedpizza** [comment]
I would love this as well, even if it's simply just another column in the list

**Comment by Flaming-Dorito** [comment]
Yeah this would be great. Any plans to implement it yet? This issue is from May 2020..

**Comment by imagochan** [comment]
would love to see this feature get implemented.

**Comment by SyntaxisCS** [comment]
+1 on this feature

**Comment by Turkmen48** [comment]
+1 on this feature

**Comment by Hitacium** [comment]
+1 on this feature

**Comment by minimalistjack** [comment]
+1 on this feature

**Comment by gabliltraydev** [comment]
+1 add it please
