### ISSUE TITLE
Linux : Error building any multicore build - undefined reference to __sync_bool_compare_and_swap_16

### ISSUE THREAD

**Issue by 7oxicshadow** [yuzu-emu/yuzu#4020]
When attempting to build any multicore enabled version of Yuzu it fails to compile on Linux.

It gives the following error:

`undefined reference to __sync_bool_compare_and_swap_16`

The solution is to provide the following compiler option:

`-mcx16`

I can confirm that multicore is providing good performance gains on Linux.

This issue can be closed if the solution is already implemented for mainline.

**Comment by joaorb64** [comment]
What are the steps you follow for your build?
I tried the following:

- clone from https://github.com/FernandoS27/yuzu
- `git checkout prometheus-final`
- `git submodule update --init --recursive`
- edit `src/CMakeLists.txt` adding `-mcx16` at around line 62
- the usual build steps (mkdir, ninja cmake, ninja)

My build fails with undefined references to `"jump_fcontext"`

Based on https://github.com/yuzu-emu/yuzu/pull/3955#issuecomment-630171537, I also add `-lboost_context -lfmt` and `link_libraries("-lboost_context -lfmt")` to `src/CMakeLists.txt` (all changes mentioned in the linked comment). Now it builds, but crashes as soon as most games start.

**Comment by 7oxicshadow** [comment]
Building on Fedora 32.

git clone -b prometheus-final https://github.com/FernandoS27/yuzu.git
git submodule update --init --recursive
cd yuzu
mkdir build
cd build
<now edit src/CMakeLists.txt and add -mcx16 around line 62>
cmake ..
make -j5

Did not have to mess with boost or additional libraries.

**Comment by 7oxicshadow** [comment]
You might have to manually install conan.

pip install --user conan

or it might be 

pip3 install --user conan

**Comment by joaorb64** [comment]
Thank you for the fast answer!

I'm using Ubuntu 20.04.

Followed your steps and got errors with `"make_fcontext"` `"jump_fcontext"`, same as before. Then I added all changes stated in the comment I linked earlier, but now I'm using `cmake` and `build` directly just like you instead of using ninja.

But just like before: Smash Ultimate, Mario Maker 2, Zelda LA crashed after launching screen; Mario Odissey crashed as soon as a level loaded; Cave Story ran without problems. I don't know if it's related, but all games that gave me problems were in nsp format, while Cave Story is a xci.

I found out that I had conflicting libcrypto entries, I'm waiting for a build to finish so I can see if it works.

**Comment by 7oxicshadow** [comment]
If it doesn't work for you i would delete the build directory and re-create the build folder again.
Install conan (the cmake script uses it to download dependancies that might be missing i think)
Then run cmake .. again and build

**Comment by joaorb64** [comment]
After finding out an old manual install of libressl, I removed it, deleted the build directory and built Yuzu again from scratch.
Again, had to make all the changes stated in the post I linked earlier for Yuzu to link correctly on Ubuntu 20.04.
Still can only run Cave Story without crashes.

**Comment by luziferius** [comment]
> Still can only run Cave Story without crashes. Tested a xci for the Mario 64 port that also crashed on launch with "Trace/breakpoint trap".

I think you have to merge the Prometheus branch into the mainline repository master branch. As far as I know, the Prometheus branch branched off the main repository, which has all kinds of assert statements active, which mainline has not. If any game triggers an assert, the emulator crashes on purpose.
I’m not able to launch any of my games on plain `yuzu`, but `yuzu-mainline` works just fine (from the player perspective).

I had to fiddle several hours to get the linker happy for a single successful build, though…

**Comment by joaorb64** [comment]
Thank you so much!
Can confirm @luziferius 's solution works on default Ubuntu 20.04. For building I followed the official build guide using ninja.

**Comment by 7oxicshadow** [comment]
Closing this issue as it has been added to mainline via the following commit 626cc44d7ababf037cbf1f0a6fd1372efc296b64
