### ISSUE TITLE
Yuzu crashes in Pokemon Shield

### ISSUE THREAD

**Issue by MRHirsch20** [yuzu-emu/yuzu#4021]
Hi, 
when i try to play Pokemon Shield it crashes after the character selection
Here's my log file:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4706330/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
This is an issue tracker for developers, not a help forum. Please use the discord for this kind of thing
