### ISSUE TITLE
gyroscope yuzu

### ISSUE THREAD

**Issue by phoenix-38** [yuzu-emu/yuzu#4022]
Hello everyone ! 
It's possible to use the gyroscope function on the emulator yuzu with PS3 or PS4 pad ? 
Thank you

**Comment by BSoDGamingYT** [comment]
This is an issue tracker for developers, not a help forum. Please use the discord for this kind of question

**Comment by FearlessTobi** [comment]
Yuzu doesn't have Gyro support yet.

**Comment by phoenix-38** [comment]
Hello,
Can you help me please ?
I have few files in the folders of the emulator Yuzu but I dn't know where install them, for obtain de gyroscope function in Yuzu
Thank you

________________________________
De : Tobias <notifications@github.com>
Envoyé : samedi 30 mai 2020 23:06
À : yuzu-emu/yuzu <yuzu@noreply.github.com>
Cc : phoenix-38 <phoenix384@live.fr>; Author <author@noreply.github.com>
Objet : Re: [yuzu-emu/yuzu] gyroscope yuzu (#4022)


Yuzu doesn't have Gyro support yet.
