### ISSUE TITLE
When i start my Pokemon sword it says yuzu.exe has stopped working. But i can play my  Pokemon let's go Pikachu without any issues. Please help me find out why this problem occurs only with Pokemon sword because iam dying to play the game

### ISSUE THREAD

**Issue by sky81230** [yuzu-emu/yuzu#4028]

**Comment by ExsertWizard** [comment]
This place is for issue trackers for developers. For user support, please join the yuzu Discord server. Requesting to close.

**Comment by auranticus** [comment]
Wtf is this lol…
Also you _don’t_ even provide your log when Pokemon Sword crashes

**Comment by MerryMage** [comment]
Closed issue due to lack of useful information and nonspecificity.

Please also refer to <https://yuzu-emu.org/game/pokemon-lets-go-pikachu/> regarding current playability state.
