### ISSUE TITLE
Pokemon Sword crash on Save when using Mod

### ISSUE THREAD

**Issue by Adrenaline67** [yuzu-emu/yuzu#4029]
Pokemon Sword crashes when attempting to save via the menu or on automatic save states. The mod I'm using is Pokemon Sacred Sword. The game works perfectly fine when I'm not using this mod (I can save with no problem). 

yuzu Early Access 576 | HEAD-ecda6c706
Nvidia Geforce GTX 770 950 MHz 2048 Mo
Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
Windows 10

This is the log file when the game crashed after attempting to save via the menu.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4710658/yuzu_log.txt)

Thank you for you help!

**Comment by AnotherMei** [comment]
As far as I know, that kind of mod breaks the game on Yuzu, but next time, join the Yuzu Discord server for user support. This place is for issue trackers for developers.

**Comment by Adrenaline67** [comment]
Okay, will do. Sorry for the trouble!
