### ISSUE TITLE
Regression - EA 572 onward:  Diablo 3: Eternal Collection no longer launches with/ multicore on

### ISSUE THREAD

**Issue by thefooz** [yuzu-emu/yuzu#4035]
Hi Folks,

It appears that, at least on my hardware ( Ryzen 1600 AF + Nvidia 1660 Super), any EA version of Yuzu after 571 no longer launches Diablo 3: Eternal Collection. The loading screen spins continuously (I left it for 30+ minutes at one point to no avail). Version 571 and prior work flawlessly.

This is with standard settings+multicore on and OpenGL.

Thanks for everything you're all doing.

**Comment by garyd1234** [comment]
Also having this issue on a Turing card with RTX 2600. CPU is AMD 3600

I've attached log files of v554 (the only copy i have where it works) vs v587 where it doesnt work.

[yuzu_log v554 Diablo 3.txt](https://github.com/yuzu-emu/yuzu/files/4726386/yuzu_log.v554.Diablo.3.txt)
[yuzu_log v587 Diablo 3.txt](https://github.com/yuzu-emu/yuzu/files/4726387/yuzu_log.v587.Diablo.3.txt)

**Comment by Morph1984** [comment]
Crashes after moving to 4 JITs multicore, does not crash in singlecore.

Request to amend the title to reflect that it no longer launches with/on multicore.

**Comment by thefooz** [comment]
@Morph1984 , title has been edited. 

Interestingly enough, whatever changed between 571 and 572 caused the issue to start occurring. 

From what I can see, the only significant changes made were the following:

- PR#4025 gl_device: Enable compute shaders for Intel proprietary drivers
- remove PR#4006 glsl: Squash constant buffers into a single SSBO when we hit the limit

**Comment by garyd1234** [comment]
Can confirm it works without multicore enabled. Albeit performance is lower of course.

**Comment by thefooz** [comment]
This appears to be resolved in the latest ARB-enabled builds: 

Tested EA 593

I'll go ahead and close this issue.

**Comment by thefooz** [comment]
Looks like it was likely the removal of 4 JITs multicore in 590 and 591 that did it.

**Comment by blackwind** [comment]
Issue has been active again in EA for at least the past several months worth of builds. Multicore off starts reliably, multicore on doesn't. Can you reopen, @thefooz?
