### ISSUE TITLE
Pokemon Shield crashing too much

### ISSUE THREAD

**Issue by Caue92** [yuzu-emu/yuzu#4037]
My Pokemon Shield can't even start properly ... it always crashes when I say "SAVE", And the game keeps crashing ... Is there any way to decrease the quality of the graphics, so that it requires less of the hardware? or not, just expect better compatibility from YUZU? My PC runs well until Xbox one game and can't stand Yuzu

[DxDiag.txt](https://github.com/yuzu-emu/yuzu/files/4718833/DxDiag.txt)

**Comment by AnotherMei** [comment]
This place is for issue trackers for developers. For user support, please join the yuzu Discord server and ask in #yuzu-support-windows or #yuzu-support-linux depending of your Operating System. Also you don’t even provide your Yuzu log when Pokemon Shield crashes and that's mandatory if you want to receive help. Logs help us to find what's responsible for the crash. Requesting to close.
