### ISSUE TITLE
FAST RMX - Missing Graphics In-Game

### ISSUE THREAD

**Issue by ActualMandM** [yuzu-emu/yuzu#4043]
yuzu Mainline 271

GeForce RTX 2080
Ryzen R9 3950X

Dynamic Exposure on:
The exposure make the screen almost entirely white.
<img width="961" alt="2020-06-03_17-38-38" src="https://user-images.githubusercontent.com/15317421/83702365-5c0f5000-a5c1-11ea-9619-787b4f5f4292.png">

Dynamic Exposure off:
While you can see outlines of models in the game, you don't see the textures of them.
<img width="961" alt="2020-06-03_17-38-27" src="https://user-images.githubusercontent.com/15317421/83702372-603b6d80-a5c1-11ea-813f-5e850a5bc764.png">

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4726842/yuzu_log.zip)

**Comment by bunnei** [comment]
Probably still relevant, no need to close :)

**Comment by legend800** [comment]
Still quite broken - missing shaders, broken lighting and runs at 2fps (on a high-end pc)

![2021-01-13 13_02_41-](https://user-images.githubusercontent.com/20983844/104533527-69fd6880-55c7-11eb-9eae-8485e690d82b.png)
![2021-01-13 13_00_51-yuzu Early Access 1315 _ FAST RMX](https://user-images.githubusercontent.com/20983844/104533559-784b8480-55c7-11eb-946d-ac3ecb46e3d1.png)
![2021-01-13 13_01_53-yuzu Early Access 1315 _ FAST RMX](https://user-images.githubusercontent.com/20983844/104533566-7da8cf00-55c7-11eb-850c-765d2814cd2b.png)

**Comment by benderscruffy** [comment]
still broken on Vulkan and Opengl
![01009510001ca000_2021-12-05_19-00-03-418](https://user-images.githubusercontent.com/2696404/144743872-f47e5f91-6aca-4ff3-bbc0-0d8e1320760c.png)
![01009510001ca000_2021-12-05_19-01-22-045](https://user-images.githubusercontent.com/2696404/144743873-cca7b35a-0d2a-4dc1-9119-a48729a15324.png)
![01009510001ca000_2021-12-05_18-59-13-752](https://user-images.githubusercontent.com/2696404/144743870-c3d5300a-f222-47f4-99ca-3fd1ab7f79a3.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7655720/yuzu_log.txt)

**Comment by german77** [comment]
Fixed. Lighting issues still remain. But models are rendered
