### ISSUE TITLE
svcBreak in CreateWithAdjustableSystemClock with error code 0xCC74

### ISSUE THREAD

**Issue by Morph1984** [yuzu-emu/yuzu#4045]
<meta name="titleids"  content="0100FB700D224000">

- Used by LAYTON’S MYSTERY JOURNEY™: Katrielle and the Millionaires’ Conspiracy – Deluxe Edition

[svc_break_report.zip](https://github.com/yuzu-emu/yuzu/files/4731160/svc_break_report.zip)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4731161/yuzu_log.txt)

**Comment by german77** [comment]
Used by Yo-Kai Watch
[yuzu_log (10).txt](https://github.com/yuzu-emu/yuzu/files/6136057/yuzu_log.10.txt)

**Comment by DocMAX** [comment]
LAYTON’S MYSTERY JOURNEY still doesnt work right?

**Comment by Morph1984** [comment]
@DocMAX I haven't confirmed if it is fixed in that game, but it should be fixed if this is the only error.

**Comment by DocMAX** [comment]
to me the game isn't booting at all, black screen, same for you?

**Comment by Morph1984** [comment]
Did you compile yuzu with the fix PR?

**Comment by DocMAX** [comment]
No, which PR is needed here?

**Comment by Morph1984** [comment]
The PR linked to this issue: #6214

**Comment by DocMAX** [comment]
Applied the PR now Layton runs :-). Only issue is, my screen is flipped/mirrored in all axis. I read that this is a vulkan driver issue. Using latest of nvidia...

**Comment by Morph1984** [comment]
Did you try opengl?

**Comment by DocMAX** [comment]
Yes, it's better but screen looks like this in OGL:
![image](https://user-images.githubusercontent.com/5351323/115568503-a58d8a00-a2bc-11eb-99bb-eadd513ae028.png)

**Comment by DocMAX** [comment]
The game still has issues :-(. Most of the time black screen with subtitles and audio.

**Comment by Krako13** [comment]
Same thing on Windows with Vulkan and OpenGL

**Comment by german77** [comment]
This issue was about CreateWithAdjustableSystemClock. Those are different issues. Consider opening a new one with the appropriate description
