### ISSUE TITLE
Cytus α: Tutorial Video Black Screen and Touchscreen not working

### ISSUE THREAD

**Issue by KyRuS-SH** [yuzu-emu/yuzu#4047]
When the game loads you can only hear the sound when using just OpenGL without asynchronous GPU emulation. You can still make inputs and also get in-game, just with a black screen. This does not occur when using OpenGL with ASYNC, Vulkan with ASYNC, or Vulkan without ASYNC. I've attached the logs from my testing.

- Tested with Yuzu 271
- AMD Ryzen 5 3600 6-Core Processor
- GeForce GTX 1060 6GB
- Windows 10
- 16 GB RAM

Logs:
[OpenGL.txt](https://github.com/yuzu-emu/yuzu/files/4732686/OpenGL.txt)
[OpenGL_ASYNC.txt](https://github.com/yuzu-emu/yuzu/files/4732685/OpenGL_ASYNC.txt)
[Vulkan.txt](https://github.com/yuzu-emu/yuzu/files/4732698/Vulkan.txt)
[Vulkan_ASYNC.txt](https://github.com/yuzu-emu/yuzu/files/4732699/Vulkan_ASYNC.txt)

**Comment by SCP-Oreki** [comment]
Hey! Can you actually play Cytus alpha on yuzu? The game start properly but screen just turned black after selecting songs and clicking Start on my PC (3700x with 1060 too)

**Comment by KyRuS-SH** [comment]
Hey SCP-Oreki!
What you're seeing is actually the tutorial video being played. Yuzu can't display it and it lags horribly. You can either skip it with the A-Button or wait long enough until it stops playing.

I've tested various settings with the latest Yuzu Build and here is what I got:

    Tested with Yuzu 271
    AMD Ryzen 5 3600 6-Core Processor
    GeForce GTX 1060 6GB
    Windows 10
    16 GB RAM

Playing Cytus Alpha is possible with the latest build. OpenGL and Vulkan without Async make the game playable with a little bit of lag in-game, longer loading times, and laggy menus.
The worst method to play the game is with Async enabled, as it adds delay to the audio, making the game basically unplayable.
The menus and load times get better with Async though. 
The best method is to either play the game with OpenGL or Vulkan with Multicore enabled. It almost completely removes any lag from all menus and in-game, removes any noticeable audio delay and the load times get reduced even more (I think it's loading slightly faster with OpenGL).

Remaining Issues:

    - You can't access any songs, that need unlocking with the touchscreen
    - The tutorial produces a black screen and is unwatchable

**Comment by SCP-Oreki** [comment]
Thank you sooooo much for your generous help! The UI and animation in Cytus Alpha is so exquisite.

But the's a slight problem. 
After tweaking the Note Calibration, the notes animation seems to be playing ahead of schedule in some songs.
When the scan line is close to the notes, the notes even disappear because of the early animation.

l'm wondering if you have the same issue when playing, or maybe it's just my individual problem.

**Comment by KyRuS-SH** [comment]
Hi again.

I'm also experiencing the same issue.
![Cytus Note disappearing](https://user-images.githubusercontent.com/57010770/91724693-f7eb3080-eb9d-11ea-8caf-15037caa2623.png)
You can see, that the top right note is disappearing before the line gets even close to it.
Sadly this is not fixable, because it is a bug present in the original game:
https://www.youtube.com/watch?v=tM1iRIO5iOs

This is most likely a problem with the game engine, because the note is too far away from its original position, and the animation cant play out as it should. Notice for example that in the Note Calibration menu, when you set it to 0.50, for example, the note won't pulse, when the line overlaps with it. A safe Calibration value is 0.15, if you go any higher than this you will start seeing the bug again.

So If you're experiencing audio delays try disabling audio stretching, make sure that in the audio options your main audio output is selected, and use either OpenGL or Vulkan with Multicore enabled (!). You also might want to check if your PC is running any processor-heavy applications in the background as it may impact performance drastically. If you're still experiencing issues please provide more information or an example video.

**Comment by german77** [comment]
Touch implementation was improved considerably. Please test again!

**Comment by KyRuS-SH** [comment]
Thanks for the notice!

The new tests were performed with these specifications:

    Tested with Yuzu 733
    AMD Ryzen 5 3600 6-Core Processor
    GeForce GTX 1060 6GB
    Windows 10
    16 GB RAM

The game is able to run great now, when run with the correct settings.
 
### **OpenGL vs. Vulkan**
![3Vulkan](https://user-images.githubusercontent.com/57010770/131386426-e726714a-e5fb-4dfb-94ec-93d0c8f6a9a6.png)

The game is now super stable on both OpenGL and Vulkan with Normal GPU settings. The game is able to run constantly at 60 FPS and they are no audio stutters. Vulkan had a tiny audio delay of around 2-3ms, but this does not affect gameplay.
Disabling audio stretching caused only barely noticeable shutters in-game, that can easily be ignored.

Enabling or disabling the shader cache does not affect performance since the game is not very shader-heavy.
The "Accelerate ASTC texture decoding" and "NVDEC emulation" settings also did not change the performance or stability.

### **Touchscreen**
![4](https://user-images.githubusercontent.com/57010770/131388213-40ef0f79-b750-49d5-b5ee-f7bef29f631c.png)

The new touchscreen improvements work very well in-game. It is now possible to navigate the game menus and select the secret levels. The touchscreen only works correctly in Undocked mode. In Docked mode, the inputs are offset to the left by a considerable amount. If playing with touchscreen controls I recommend setting the input diameters for touchscreen controls to 10-12 instead of 15 for more precise inputs (I managed to hit the pause button with the bigger radius a few times).

### **Tutorial Black screen**
![5](https://user-images.githubusercontent.com/57010770/131389484-be2438ff-1991-422f-8532-d031414731b7.png)

The Tutorial no longer displays a black screen and now runs correctly on both OpenGL and Vulkan. The audio stutters and the performance have also been fixed.

### **Corrupted Shadercache**
![1](https://user-images.githubusercontent.com/57010770/131382413-8619a718-4c7c-477e-beb6-24a6a32cb5db.png)
![2](https://user-images.githubusercontent.com/57010770/131384761-abd967c9-d7b8-4bcf-896f-0ab536742f37.png)

Sometimes when the game is run with different settings, the shader cache would randomly be corrupted, causing a completely white screen with no logos or texts, or other graphical issues. Some graphics can be seen when traversing the menus, and the logos and menus partially return after revisiting to a previous screen. It's also possible to get in-game, which results in no text being shown in-game. However, the game still remained stable and playable. You can fix this issue by deleting the shader cache or disabling the Disk-Shader-Cache option in the graphic settings. This does not affect performance.

OpenGL log: [OpenGL.txt](https://github.com/yuzu-emu/yuzu/files/7078843/OpenGL.txt)
Vulkan log:  [Vulkan.txt](https://github.com/yuzu-emu/yuzu/files/7078845/Vulkan.txt)


The original issue has been solved with these improvements. Incredible work by everyone involved with the project!

**Comment by german77** [comment]
Consider that you can't use the touch screen while docked on a real switch so wrong behavior is expected

**Comment by KyRuS-SH** [comment]
Would be interesting to see what a real switch would do, if you could access the touchscreen while docked. It's probably just disabled. The offset I was talking about must be because of the changed resolution when docked...

**Comment by german77** [comment]
It does nothing. There are dock stations that doesn't block the touch screen. I can fix it but in reality we should disable it completely
