### ISSUE TITLE
Missing service: SetNpadCommunicationMode

### ISSUE THREAD

**Issue by Aushera** [yuzu-emu/yuzu#4048]
Used by:
- Borderlands: Game of the Year Edition
- Borderlands 2: Game of the Year Edition

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4732728/yuzu_log.txt)
[svc_break_report.zip](https://github.com/yuzu-emu/yuzu/files/4732729/svc_break_report.zip)

**Comment by benderscruffy** [comment]
used by Xeodrifter  aswell

**Comment by german77** [comment]
used by Micetopia
