### ISSUE TITLE
GCC compiles Tegra::MacroJITx64Impl constructor into >250,000 instructions taking >40 minutes

### ISSUE THREAD

**Issue by comex** [yuzu-emu/yuzu#4051]
Yuzu commit: 22369df357fc4e9fdc21bd4096128b84aebc41a2
Reproduced on Debian sid with both of these versions of GCC:
- `gcc (Debian 9.3.0-13) 9.3.0`
- `gcc (GCC) 10.1.0` (stock)
on Debian sid.

CPU: AMD Ryzen Threadripper 3970X (2.2GHz)

CMake invocation: `cmake .. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo`

Compiler invocation: `/usr/bin/c++  -DARCHITECTURE_x86_64=1 -DBOOST_ALL_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DHAS_VULKAN -DNDEBUG -DXBYAK_NO_OP_NAMES -D_FILE_OFFSET_BITS=64 -I/home/comex/.conan/data/catch2/2.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I../src/. -I../src/video_core/sirit -I../src/video_core/../../externals/Vulkan-Headers/include -I../externals/./microprofile -I../externals/glad/include -I../externals/sirit/src/../include -I../externals/sirit/externals/SPIRV-Headers/include -isystem /home/comex/.conan/data/fmt/6.2.0/_/_/package/f54287fc3dbd09590f968b580bebb565ea4a4b17/include -isystem /usr/include/SDL2 -isystem ../externals/dynarmic/externals/xbyak/xbyak -O2 -g -DNDEBUG   -Wall -Werror=implicit-fallthrough -Werror=missing-declarations -Werror=reorder -Wextra -Wmissing-declarations -Wno-attributes -Wno-unused-parameter -Werror=conversion -Wno-error=sign-conversion -std=gnu++17 -MD -MT src/video_core/CMakeFiles/video_core.dir/macro/macro_jit_x64.cpp.o -MF src/video_core/CMakeFiles/video_core.dir/macro/macro_jit_x64.cpp.o.d -o src/video_core/CMakeFiles/video_core.dir/macro/macro_jit_x64.cpp.o -c ../src/video_core/macro/macro_jit_x64.cpp`

As-is, this command runs for at least 40 minutes; I gave up waiting for it to finish.

If I either disable debug info (remove `-g`) or add `-fno-var-tracking-assignments`, it takes "only" 2 minutes 20 seconds.  In the resulting .o file, according to [`bloaty`](https://github.com/google/bloaty), the function `Tegra::MacroJITx64Impl::MacroJITx64Impl()` is compiled to *2.63MB* of object code.  (Not debug info, actual code.)

In contrast, if I switch to `clang++`, compilation completes in 2.5 seconds, and the .o file uses less than 64KB for the entire .text section.

Investigating further, the problem has to do with these fields:
```
    std::array<Xbyak::Label, MAX_CODE_SIZE> labels{};
    std::array<Xbyak::Label, MAX_CODE_SIZE> delay_skip{};
```

When constructing `MacroJITx64Impl`, GCC needs to call the default constructor of `Xbyak::Label` on each array element; that constructor just initializes the object's two fields to 0.  The expected approach, of course, would be to generate a loop.  Better yet, it could detect that the loop is just writing zeroes to memory and optimize it into a `memset` call.  But no…

For some crazy reason, GCC generates code for each individual array element to initialize it.  Yes, for each and every one of the 131,072 array elements (0x10000 elements per array * 2 arrays), GCC dedicates two instructions to initializing that element, for a total of 262,144 instructions.  No wonder it takes so long.

Looking through the GCC bug tracker, I found this:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55402

\[Edit: Actually, these reports are more on point:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92385
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80272
I bet they're all the same issue though.\]

It seems to be a known issue related to the use of aggregate initialization.  So I tried simply removing the `{}` from `labels` and `delay_skip`, causing them to instead be constructed with `std::array`'s default constructor (which should still properly initialize the elements, since as I said, `Label`'s default constructor zeroes its fields).  And sure enough, GCC now compiles the file in 3 seconds.

Looks like this was introduced by commit eca3d16e548451f403cc4cc2e9fb38ed96693102:
```
Author: David Marcec <dmarcecguzman@gmail.com>
Date:   Thu Jun 4 22:23:07 2020 +1000

    Default init labels and use initializer list for macro engine
```

**Comment by ReinUsesLisp** [comment]
Thanks for reporting this
