### ISSUE TITLE
No exclusive fullscreen functionality

### ISSUE THREAD

**Issue by nursejoychan** [yuzu-emu/yuzu#4053]
Exclusive full screen includes benefits like increased performance and decreased input lag; allowing the emulator to become a lot more responsive. I think it would be a huge benefit to the emulator if this function was implemented.

**Comment by HarvsG** [comment]
It would be great if there was an .exe flag to launch it into a fullscreen mode

**Comment by v1993** [comment]
Note: on Linux exclusive fullscreen does not exist at all, but disabling compositor (Alt+Shift+F12 in KDE) gives similar results.

**Comment by turntablez123** [comment]
I was hoping for a command line full screen function so shortcuts could be made to specific games and most emulators have -f or —fullscreen as a command to be able to do this.  If this was made available this would be very nice.  Thank you!

**Comment by german77** [comment]
> I was hoping for a command line full screen function so shortcuts could be made to specific games and most emulators have -f or —fullscreen as a command to be able to do this. If this was made available this would be very nice. Thank you!

Take a look at #5331 you can lunch yuzu in fullscreen mode

**Comment by Hasster1** [comment]
Shouldn't this be closed by now?

**Comment by Bitwolfies** [comment]
Shouldnt the option be disabled on the Linux build if  it does nothing?

**Comment by liamwhite** [comment]
Exclusive fullscreen is supported on Windows and Linux (Xorg only) now.
