### ISSUE TITLE
Yuzu unable to detect more than 4 controllers (SSBU 8-player smash)

### ISSUE THREAD

**Issue by Bruniiin** [yuzu-emu/yuzu#4057]
I'm streaming SSBU with some friends and other people over Parsec and it's working fine, I configured all 8 controller ports on qt-config.ini and are working accordingly, they all show up as 'connected' in game, but it seems that only 4 players are able to join in. 
I heard that Xinput only has support for 4 players but I can't find if yuzu uses Xinput or Directinput (which supports 8) anywhere on the web, or how to use Directinput on yuzu instead of whatever they have. Any way to fix this?

**Comment by SmokePuddingEveryday** [comment]
Yuzu uses XInput but I'm not sure how it handles DInput. After 4 users have connected their controlls in Parsec, the last 4 players are registered as DInput on your computer.
