### ISSUE TITLE
latest Yuzu crashes on Mint 19.3

### ISSUE THREAD

**Issue by dukenukemx** [yuzu-emu/yuzu#4058]
Compiled Yuzu from this Github and it does start up and run but every game that tries to load will  just close, which I assume is a crash.  This is running a Ryzen 7 1700 with a Radeon Fury on Ming 19.3.  When I run it through Terminal I get this. 

`ATTENTION: default value of option vblank_mode overridden by environment.
qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 185, resource id: 0, major code: 140 (Unknown), minor code: 20
libpng warning: iCCP: known incorrect sRGB profile
Trace/breakpoint trap (core dumped)`

Here's the log.
[https://pastebin.com/zgUk5DSg](url)

**Comment by joaorb64** [comment]
Did you compile from yuzu-mainline?
I don't really know how to read the log, but recently I had a similar problem so it might help. Yuzu has some asserts and it forces a stop if they aren't satisfied. Mainline removes the asserts. May be the source of your issue.

**Comment by dukenukemx** [comment]
@joaorb64 I just tried compiling from yuzu-mainline and it works.  Not sure why this worked.  Vulkan works too it seems.  It did crash in Mario Odyssey after like 15 minutes of playing but I consider that a separate bug.
