### ISSUE TITLE
FIX DQ11

### ISSUE THREAD

**Issue by Wyrick** [yuzu-emu/yuzu#4060]
No one gives a shit about nintendo crap

**Comment by theboy181** [comment]
wut?

**Comment by goldenx86** [comment]
The project is open source, you're free to fix it yourself.

**Comment by VolcaEM** [comment]
This is not the right place to ask "fix x game", especially without posting logs or anything so that the developers can actually know what the problem with the game is.
Eventually it will be fixed, there's no need to be so aggressive.
If you want it to be fixed so much, fix it yourself.
