### ISSUE TITLE
[Linux/Fedora]  Conan failed to  install boost 1.72

### ISSUE THREAD

**Issue by iWeaker4you** [yuzu-emu/yuzu#4061]
I get this error when I try to apply Cmake, since Fedora 32 only supports up to version 1.69, but I don't know if there is any other way to use Boost like Citra does.

![Captura de pantalla de 2020-06-07 21-56-05](https://user-images.githubusercontent.com/49424816/83993965-e16c6a80-a909-11ea-82d0-3000510d82a3.png)

**Comment by lat9nq** [comment]
Can you retest this after deleting the `~/.conan` directory? Seems like a Conan package is corrupted.

**Comment by dsshin1us** [comment]
Change the boost version in the CMakeList.txt
all 1.73.0 to 1.75.0
