### ISSUE TITLE
SR and SL keys are not recognized by games 

### ISSUE THREAD

**Issue by clovxt** [yuzu-emu/yuzu#4062]
When playing local coop with two xbox one controller (snipperclips and super mario odyssey) SR and SL keys cannot be recognized by games. 

I set two players one with right joy con and the other with left joy con (the orientation took me a while to make it work) but the SR and SL keys have no effects upon pressing in game no matter which key i assign them to.

**Comment by DoobySnaX** [comment]
Had similar issue, found solution here. https://github.com/yuzu-emu/yuzu/issues/3281
Setting both players to "single left joycon" fixed it for me
