### ISSUE TITLE
Black Screen in Super Mario Maker 2 + Log File

### ISSUE THREAD

**Issue by jeremy10tie** [yuzu-emu/yuzu#4065]
Past the launching screen there is only a black screen and music playing behind it. Pressing buttons interacts with the game(sound play too) but everything remains black.

version yuzu 277  

https://file.io/LtVXcFFv (log file )

**Comment by BSoDGamingYT** [comment]
Disable ARB (Assembly Shaders) in your Early Access build.

**Comment by jeremy10tie** [comment]
it's ok thanks :)

**Comment by edenpark-ai** [comment]
le jeu s’arrête pendant le lancement

**Comment by FearlessTobi** [comment]
According to reports on Discord, this issue has been fixed.
