### ISSUE TITLE
Animal Crossing: New Horizons Game hangs when K.K. Slider visit island

### ISSUE THREAD

**Issue by rdude** [yuzu-emu/yuzu#4071]
This bug was present using an RTX 2080 Super in Vulkan/OpenGL. EarlyAccess Build 603.
Game version - 1.2.0

Bug reproducing, when K.K. Slider visit my island.

![1](https://user-images.githubusercontent.com/5602243/84312250-4d9ad880-ab6d-11ea-9bc3-3636c12ed0c4.jpg)

Right after K.K. should play his song game hangs on scene, where characters stay around K.K.

![2](https://user-images.githubusercontent.com/5602243/84312544-c7cb5d00-ab6d-11ea-9971-dc331b17731b.jpg)

Game is not freeze (characters still shakes and frames redrawing), but nothing more happening after. I waiting a lot of time.

Maybe is related with when K.K. Slider should play his song at start of the game no sound was played on emulator (other issue).

No workaround was found.

I can provide any kind of information: save, logs, etc.

Thank you in advance!

**Comment by develoqqer** [comment]
This is a known issue  and that's why ACNH is not considered playable.

**Comment by Aris-t2** [comment]
In case someone is still interested:
the games does not freeze/crash anymore "when K.K. Slider visit island" using current EA builds.

Tested with game version 1.2.1.

**Comment by Zuchter** [comment]
Fixed in #4080
