### ISSUE TITLE
Hard crash with Luigi's Mansion (Turing GPU)

### ISSUE THREAD

**Issue by garyd1234** [yuzu-emu/yuzu#4072]
Hi Team,

I get a lot of crashes in Luigi's Mansion. I have a turing card, RTX 2060, which i know can be problematic in Yuzu.

I have attached a save file (Ballroom area) and also a log file. Basically if i walk around in this Ballroom area enough it will cause Yuzu to crash. This is not the only area where it crashes but it is very repeatable here. It seems to be in areas where the lighting changes rapidly.

It could be something at my end, but the other games i have (Diablo and SMO) both run fine.

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4761490/yuzu_log.zip)
[0100DCA0064A6000.zip](https://github.com/yuzu-emu/yuzu/files/4761497/0100DCA0064A6000.zip)

**Comment by LinkFLOZ** [comment]
Same happens to me with also a rtx 2060, so It seems Turing is the problem, because tried on 1050ti and not a single room crashes

**Comment by roblaplante** [comment]
Same problem here with my RTX 2080ti !!

**Comment by TheIceMagmaCube** [comment]
Yup, to run the game, I need to use Vulkun. Anyway, with the setting tweaked, the game start IN 10FPS
Idk why it's doing that ... Any clues about this issue ?

**Comment by G-Spawn** [comment]
@TheIceMagmaCube https://yuzu-emu.org/wiki/switch-mods/ Please be sure to use the required mod for the game (Disable dynamic resolution) and use updated yuzu.

**Comment by G-Spawn** [comment]
@garyd1234 Please reopen issue if it still happens for you on latest yuzu versions & provide new log if possible. Mod wise you only need the disable dynamic resolution one now.
