### ISSUE TITLE
Pokemon Sword/Shield daily events broken

### ISSUE THREAD

**Issue by MohamedAarab** [yuzu-emu/yuzu#4074]
None of the daily events can be done, such as pokejobs, max raids, berry trees, etc because the time doesn't advance. Pokejobs say that there is 24 hours remaining, but it never goes down.

I tried changing my computer time/date but that didn't fix it either.

**Comment by MohamedAarab** [comment]
Apparently there is an unofficial patch going around that fixes this? Perhaps the team could use this as inspiration for the official fix:
https://www.reddit.com/r/yuzu/comments/gu0vxt/why_do_daily_events_not_work_its_as_if_time/fsh5jas/

**Comment by takeruadelbert** [comment]
I really hope that the team would fix this.

**Comment by KostaSaizo7** [comment]
This stiil happens in Yuzu mainline 417

**Comment by ackile** [comment]
Nop, this is not fixed. All of my Tree berry are empty, and i can't fight in the battle pub.

**Comment by RiedleroD** [comment]
still an issue, pokejobs don't advance, even with custom RTC. Didn't try the patch bc it's work I don't want to do rn.

**Comment by G-Spawn** [comment]
> still an issue, pokejobs don't advance, even with custom RTC (edit: when set while the game isn't playing). Didn't try the patch bc it's work I don't want to do rn.

You're supposed to change custom rtc while the game is running, not when it isn't.

**Comment by RiedleroD** [comment]
yes, I got that now. Still very annoying though.

**Comment by FedericoValeri** [comment]
> still an issue, pokejobs don't advance, even with custom RTC (edit: when set while the game isn't playing). Didn't try the patch bc it's work I don't want to do rn.

Any news?

**Comment by G-Spawn** [comment]
The news is custom rtc still works. Besides that there is nothing. @FedericoValeri

**Comment by Fluffisaurus** [comment]
bump, also are there any plans to fix this issue? 🙏

**Comment by G-Spawn** [comment]
Yes they plan on fixing it in future. No ETA.

**Comment by KostaSaizo7** [comment]
This got fixed in Ryujinx btw https://github.com/Ryujinx/Ryujinx/pull/4822

**Comment by german77** [comment]
Fixed in latest mainline
