### ISSUE TITLE
Fire Emblem 3 Houses doesn't crash mid-battle on Turing GPU

### ISSUE THREAD

**Issue by mariobro1233** [yuzu-emu/yuzu#4075]
I have confirmed the fact that FE3H mid-battle crashes that occur randomly is not an issue if user has turing card.
I am attaching my log and an EA log from a patreon for confirming that as well. It's an observation so I hope it is noted and actions are taken accordingly.

If required I can upload a video on youtube and link for this purpose if asked.

Thank you.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4764002/yuzu_log.txt)  (mainline)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4764081/yuzu_log.txt)  (EA)

**Comment by robsonn** [comment]
thanks to share this information

**Comment by FearlessTobi** [comment]
Thanks for the info but something working is not really a report that is actionable.
Closing

**Comment by Ryuuseiz** [comment]
With EA513 - and im using GTX 1080 no Crash happened 
this is the LOG of EA 513 after playing around 2 hours quite big around 50MB - cant upload directly to Github, Plus EA 603 Log of FE3H crash at the start of the battle or mid-battle
Mainline Yuzu 279 suffer the same issue 
I can post youtube video if you want
https://drive.google.com/file/d/1E2h_QkhleKtZF4D4h_Q9CXADAcEgNJwQ/view?usp=sharing
