### ISSUE TITLE
FE3H Keep Crashing with EA603 and Mainline - Those With Turing Card didn't

### ISSUE THREAD

**Issue by Ryuuseiz** [yuzu-emu/yuzu#4077]
With EA513 - and im using GTX 1080 (Pascal Card) no Crash happened
this is the LOG of EA 513 after playing around 2 hours quite big around 50MB - cant upload directly to Github, Plus EA 603 Log of FE3H crash at the start of the battle or mid-battle
Mainline Yuzu 279 suffer the same issue
I can post youtube video if you want
https://drive.google.com/file/d/1E2h_QkhleKtZF4D4h_Q9CXADAcEgNJwQ/view?usp=sharing
someone confirm the Turing Card with this Post :
https://github.com/yuzu-emu/yuzu/issues/4075

**Comment by Ryuuseiz** [comment]
[yuzu_log Mainline 279.txt](https://github.com/yuzu-emu/yuzu/files/4767593/yuzu_log.Mainline.279.txt)
Updated with mainline Log File - it can finish 1 batle - the next one Crash

**Comment by AlMasque** [comment]
this continues up to the current EA build EA621 can confirm
