### ISSUE TITLE
Super Smash Ultimate doesn't work anymore + Log File

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#4078]
I am using
Yuzu Early Access 603
OpenGL, Multicore, ARB enabled(tried with ARB disabled, same problem)
Super Smash Ultimate, version 6.1.0, NSP type.

When i run the game, yuzu goes past the launching screen. Then the Frame tabs shows above 1200ms and after that it shows "NAN". Plays no sound, nor displays anything.

Log File:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4770145/yuzu_log.txt)

**Comment by Bruniiin** [comment]
Try using 7.0.0, 6.1.0 may not work with this update, but i'm just guessing

**Comment by EliasM108** [comment]
> Try using 7.0.0, 6.1.0 may not work with this update, but i'm just guessing

update 7.0.0 works fine, but i'll leave the issue open for future fix.
