### ISSUE TITLE
Dedicated online multiplayer feature

### ISSUE THREAD

**Issue by jojodunet** [yuzu-emu/yuzu#4079]
To the devs team.

Hi team,

It could be fun to add dedicated online multiplayer feature between Yuzu users.

Online multiplayer is highly requested by the Yuzu community

**Comment by goldenx86** [comment]
It is planned, but it's not a top priority for now.

**Comment by Ghostotakoi** [comment]
It could be very nice if is implemented like citra, allowing to host server locally using LAN IP, because the real switch can host using wifi locally.

**Comment by goldenx86** [comment]
Yep, that's the idea.

**Comment by daniel221086** [comment]
> It is planned, but it's not a top priority for now.

november 2020 any news on the subject??
or is it still not a priority?

**Comment by anthr76** [comment]
Something to tie in with lan-play/ldn_mitm would be nice

**Comment by Ghostotakoi** [comment]
> 
> 
> Something to tie in with lan-play/ldn_mitm would be nice
i think ryuujinx has something like that

**Comment by CardboardTurtle** [comment]
Apologies for necro, but is there any update to plans for multiplayer, whether online or local wireless?

**Comment by FearlessTobi** [comment]
We are actively working on an LDN (local wireless) online implementation.

**Comment by Labaman** [comment]
It seems that you can select a network interface in the settings, but the two PCs in the same network do not find each other. Or find, but can connect to the host. 
Can someone explain - does this function work or has been eliminated (temporarily eliminated)?
