### ISSUE TITLE
Input lag with PS4 controller

### ISSUE THREAD

**Issue by sircheer** [yuzu-emu/yuzu#4084]
As the title states, Yuzu has nasty input lag with PS4 controller. Its bad enough to the point where games are unplayable. I can't count how many times I've died in SMO because of it. Important things to know: I tried using DS4windows. I tried the hide controller option. I tried using set analog stick in config. I tried numerous configs in yuzu. I updated all my driver's, windows 10 updates. Also, the PS4 controller has no input lag on any other emulators or on native PC games, so I know it's an issue with yuzu, as it works fine with absolutely anything and everything else. Please fix. I have spent days trying to fix this. Yes, I'm a Patreon and support the project

**Comment by Eloeri** [comment]
This isn't what github is for.
