### ISSUE TITLE
Smash Bros Ultimate Crashes upon title

### ISSUE THREAD

**Issue by nveen498** [yuzu-emu/yuzu#4102]
Every time I try to load Smash Ultimate, it crashes right before the title. I have tried both version 1.0.0 and 7.0.0 of the game. It used to work on older builds with no issue. I also tried disabling multicore and change to Vulkan, but the crashes keep appearing. This has happened for a while on both the Early Access builds and the mainline (Canary) builds. Settings include OpenGL, multicore, and Async all enabled. Looking at the log file, looks like it has something to do with hle_ipc.cpp and/or memory.cpp

Also I have tested other games like Super Mario Odyssey and Mario Maker 2 and it all works fine no crashes. Only this game

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4794028/yuzu_log.txt)

**Comment by FernandoS27** [comment]
Well this issue tracker is not for support. That's on discord. This is for us to organize our own issues and bugs after technical analysis. Please forward this to support channels in discord.

**Comment by acoolstraw** [comment]
> Well this issue tracker is not for support. That's on discord. This is for us to organize our own issues and bugs after technical analysis. Please forward this to support channels in discord.

Why discord?
