### ISSUE TITLE
Super Smash Bros. Ultimate - reverse LOD on effects

### ISSUE THREAD

**Issue by theincredibleplayer** [yuzu-emu/yuzu#4103]
The effects in SSBU have reversed LOD BIAS on effects this happens with alot of effects in the game and can be seen in the following screenshots:

### close to the effect:

![Screenshot (1608)](https://user-images.githubusercontent.com/54246318/84962584-7ab82f80-b107-11ea-8baf-00c2af78fe61.png)

![Screenshot (1612)](https://user-images.githubusercontent.com/54246318/84962557-6d9b4080-b107-11ea-9e56-c0cb314b7c51.png)

![Screenshot (1619)](https://user-images.githubusercontent.com/54246318/84962623-96bbd100-b107-11ea-832f-d644c0f7c678.png)

### far away from the effect:

![Screenshot (1613)](https://user-images.githubusercontent.com/54246318/84962571-725ff480-b107-11ea-9c43-fe5d515402d7.png)

![Screenshot (1616)](https://user-images.githubusercontent.com/54246318/84962601-860b5b00-b107-11ea-9f0e-1212db8f9a5a.png)

![Screenshot (1622)](https://user-images.githubusercontent.com/54246318/84962638-a20efc80-b107-11ea-80f9-51a8304a2f31.png)

**Comment by theboy181** [comment]
Having a hard time seeing the issue.   can you help?

**Comment by theincredibleplayer** [comment]
> Having a hard time seeing the issue. can you help?

it's clearer when zooming in on the screenshot, the red effect is pixelated when the camera is close to it but sharp when far away from it, this is not the case on real HW.

**Comment by benderscruffy** [comment]
is this still a problem ??

**Comment by liamwhite** [comment]
Comment if this is still relevant
