### ISSUE TITLE
Super Smash Bros. Ultimate - Replay data softlock

### ISSUE THREAD

**Issue by theincredibleplayer** [yuzu-emu/yuzu#4104]
entering the replay data menu in SSBU results in a softlock

Log file: 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4795612/yuzu_log.txt)

**Comment by Bruniiin** [comment]
Taking a screenshot also crashes the game. This also happened once when making a mii but i'm not sure if it happens everytime.

**Comment by theincredibleplayer** [comment]
> Taking a screenshot also crashes the game. It also softlocked for me when making a mii but i'm not sure if it happens everytime.

Yes they both happen everytime also when choosing the find mii or tomadachi life stage #3587

**Comment by Morph1984** [comment]
Fixed by #4737
