### ISSUE TITLE
Yuzu causes windows to crash

### ISSUE THREAD

**Issue by citrinemachine** [yuzu-emu/yuzu#4116]
I am reporting a bug.  I have encountered this bug after updating to nvidia 455.38 and EA626 (d35fabb50) .  
Windows freezes when trying to run BOTW, Super Mario Odyssey.
My system is Win 10 (20h2), with Ryzen 5 3600, nvidia 2070 Super and 16 gb ram.  
Windows freezes if I load game with Async and Multicore.  I have to reset my computer.
Otherwise (without Async and multicore) Yuzu just crashes on opening games.
Previous to this Yuzu has been able to load games and they work.

Here is the log:
[   0.736374] Input <Info> input_common\udp\client.cpp:StartCommunication:206: Starting communication with UDP input server on 127.0.0.1:26760
[   0.805020] Frontend <Info> yuzu\main.cpp:GMainWindow:219: yuzu Version: yuzu Early Access 626 | HEAD-d35fabb50
[   0.805025] Frontend <Info> yuzu\main.cpp:GMainWindow:221: Host CPU: AMD Ryzen 5 3600 6-Core Processor              
[   0.805058] Frontend <Info> yuzu\main.cpp:GMainWindow:223: Host OS: Windows 10 (10.0)
[   0.805075] Frontend <Info> yuzu\main.cpp:GMainWindow:225: Host RAM: 15.93 GB
[   0.805076] Frontend <Info> yuzu\main.cpp:GMainWindow:227: Host Swap: 10.00 GB
[   0.876768] Config <Info> core\settings.cpp:LogSettings:99: yuzu Configuration:
[   0.876774] Config <Info> core\settings.cpp:LogSetting:95: System_UseDockedMode: false
[   0.876775] Config <Info> core\settings.cpp:LogSetting:95: System_RngSeed: 0
[   0.876776] Config <Info> core\settings.cpp:LogSetting:95: System_CurrentUser: 0
[   0.876776] Config <Info> core\settings.cpp:LogSetting:95: System_LanguageIndex: 1
[   0.876777] Config <Info> core\settings.cpp:LogSetting:95: System_RegionIndex: 1
[   0.876781] Config <Info> core\settings.cpp:LogSetting:95: System_TimeZoneIndex: 0
[   0.876782] Config <Info> core\settings.cpp:LogSetting:95: Core_UseMultiCore: true
[   0.876782] Config <Info> core\settings.cpp:LogSetting:95: Renderer_UseResolutionFactor: 1
[   0.876783] Config <Info> core\settings.cpp:LogSetting:95: Renderer_UseFrameLimit: true
[   0.876784] Config <Info> core\settings.cpp:LogSetting:95: Renderer_FrameLimit: 100
[   0.876784] Config <Info> core\settings.cpp:LogSetting:95: Renderer_UseDiskShaderCache: true
[   0.876785] Config <Info> core\settings.cpp:LogSetting:95: Renderer_GPUAccuracyLevel: 0
[   0.876785] Config <Info> core\settings.cpp:LogSetting:95: Renderer_UseAsynchronousGpuEmulation: true
[   0.876786] Config <Info> core\settings.cpp:LogSetting:95: Renderer_UseVsync: false
[   0.876787] Config <Info> core\settings.cpp:LogSetting:95: Renderer_UseAssemblyShaders: false
[   0.876787] Config <Info> core\settings.cpp:LogSetting:95: Renderer_AnisotropicFilteringLevel: 0
[   0.876788] Config <Info> core\settings.cpp:LogSetting:95: Audio_OutputEngine: auto
[   0.876789] Config <Info> core\settings.cpp:LogSetting:95: Audio_EnableAudioStretching: false
[   0.876789] Config <Info> core\settings.cpp:LogSetting:95: Audio_OutputDevice: auto
[   0.876790] Config <Info> core\settings.cpp:LogSetting:95: DataStorage_UseVirtualSd: true
[   0.876791] Config <Info> core\settings.cpp:LogSetting:95: DataStorage_NandDir: C:\Users\citrine\AppData\Roaming/yuzu/nand/
[   0.876792] Config <Info> core\settings.cpp:LogSetting:95: DataStorage_SdmcDir: C:\Users\citrine\AppData\Roaming/yuzu/sdmc/
[   0.876793] Config <Info> core\settings.cpp:LogSetting:95: Debugging_UseGdbstub: true
[   0.876793] Config <Info> core\settings.cpp:LogSetting:95: Debugging_GdbstubPort: 24689
[   0.876796] Config <Info> core\settings.cpp:LogSetting:95: Debugging_ProgramArgs: 
[   0.876797] Config <Info> core\settings.cpp:LogSetting:95: Services_BCATBackend: none
[   0.876797] Config <Info> core\settings.cpp:LogSetting:95: Services_BCATBoxcatLocal: false
[   0.905310] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:421:     RomFS: Update (v0.4.0) applied successfully
[   0.911024] Loader <Warning> core\loader\loader.cpp:GetLoader:237: File Super Mario Odyssey [0100000000010800][v1.3.0][v262144].nsp has a different type than its extension.
[   0.914665] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:421:     RomFS: Update (v0.4.0) applied successfully
[   0.923142] Loader <Warning> core\loader\loader.cpp:GetLoader:237: File Super Mario Odyssey [0100000000010800][v1.3.0][v262144].nsp has a different type than its extension.
[   0.926879] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:421:     RomFS: Update (v0.12.0) applied successfully
[   0.932411] Loader <Warning> core\loader\loader.cpp:GetLoader:237: File The Legend of Zelda Breath of the Wild [01007EF00011E800][v786432].nsp has a different type than its extension.

I am not sure how to do back trace.

- You have provided the version (commit hash) of yuzu you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

-->

**Comment by BluelyTASer** [comment]
You need to upgrade your GPU to GTX 960 or above for yuzu to stop crashing windows...

**Comment by mirh** [comment]
That sounds more like a windows/driver problem than really the emulator.

**Comment by german77** [comment]
Re-open if still happens. This is probably a driver issue
