### ISSUE TITLE
PKMN Sword/Shield- Can't install updates or DlC (NSP) 

### ISSUE THREAD

**Issue by Mickelator** [yuzu-emu/yuzu#4117]
On yuzu, I have errors when i try to install pokemon shield DLC. Could you chek this this? (file is NSP. It says "check your file". 
(but I succeed in installing extension pass, just missing the main part) . 
Thanks , and thanks for all your work.

**Comment by BSoDGamingYT** [comment]
This is not a help forum. Please use the discord server for this kind of thing

**Comment by goldenx86** [comment]
Or the official forums: https://community.citra-emu.org/c/yuzu-support/14

**Comment by Mickelator** [comment]
Sorry,
but are you telling me that the setup of the DLC is possible on yuzu ? and the updates, for those pkmn games?

**Comment by Mickelator** [comment]
(maybe I didn't say it in the right way, I thought it was an issue, a bug, for everyone)

**Comment by BSoDGamingYT** [comment]
Again....This is not a help forum. Please use the discord server for this kind of thing

**Comment by Mickelator** [comment]
Again,
I thought I was recording a real issue, or bug (as softlocks or anything else). My bad if its not the case.
