### ISSUE TITLE
Snipperclips tutorial stage glitched

### ISSUE THREAD

**Issue by DoobySnaX** [yuzu-emu/yuzu#4119]
Something seems glitched to me in the tutorial stage Snipperclips.  

When gameplay first starts and control of the character is first handed over to the play, you are asked to move the character(s) into the doted area and the indicator in the top right is supposed to gauge how well you have fit the character(s) into the dotted area.

For me, the dotted areas disappear as soon as control is given over to the player and the indicator in the top right starts spinning round and round in circles rapidly.  I dont seem to be able to proceed from here.

thanks!

**Comment by BSoDGamingYT** [comment]
Set GPU accuracy to Extreme

**Comment by DoobySnaX** [comment]
That worked great, thanks!
