### ISSUE TITLE
Pokémon Sword

### ISSUE THREAD

**Issue by XeroZen** [yuzu-emu/yuzu#4130]
The game freezes with the audio playing once a battle is completed in vulkan. Tried in opengl and the same freezing occurs
Pc Specs:-
R5 3600, Vega 64, 16gb RAM.

**Comment by BSoDGamingYT** [comment]
This is not a help forum, please use the discord server or forums for this kind of thing

**Comment by XeroZen** [comment]
This happened in yuzu version 620. I only said that there were freezes in vulkan for this title

**Comment by german77** [comment]
Re-open with with a log attached if this still happens
