### ISSUE TITLE
No Sound and Splitscreen not working bug on Resident evil 5

### ISSUE THREAD

**Issue by knightwalker1794** [yuzu-emu/yuzu#4149]
According to the Yuzu Compatibility List, Resident evil should be emulated perfectly now but the problem is that as Early Access build 642 the game only works without graphic issues on Vulkan Renderer and theres no sound at all, I tried different settings and no fix, also tried other games like Smash Ultimate and sound was doing alright, also another thing is that splitscreen mode is not detected even though I have a second controller available I keep pushing splitscreen option and nothing happens. 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4822067/yuzu_log.txt)

**Comment by VolcaEM** [comment]
Can you send a log please?

**Comment by knightwalker1794** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4822059/yuzu_log.txt)

**Comment by knightwalker1794** [comment]
> Can you send a log please?
yes, here you go 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4822088/yuzu_log.txt)

**Comment by benderscruffy** [comment]
please close
no update
