### ISSUE TITLE
What causes the no file interface available ? 

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#415]
## Hardware Specs :
- Nvidia GeForce GTX 960
- Intel I7-7700k @ 4.5Ghz
- 8 GB Of Ram 3200 Mhz
- Windows 10 Pro

## The issue :
How to resolve the "No file interface available" because this error happen with all commercial games, does this have to do with shared fonts missing file ?

**Comment by mailwl** [comment]
what exactly game gives such error? maybe you don't have some files? just check "One Piece" game, no such errors
![onepiece](https://user-images.githubusercontent.com/629437/39400813-1a2e2c8e-4b40-11e8-8ac7-d49e185fc8c7.png)

**Comment by greggameplayer** [comment]
@mailwl But you reported The Binding Of Isaac Afterbirth+ and Cave Story Plus as working game so i test it but it gives "No file interface available" error so how have you been able to enter in this game ?

**Comment by mailwl** [comment]
I reported???? sorry, but i am not from yuzu team
anyway. looks like you don't rename ROM file from _romfs.iStorage to .romfs

**Comment by greggameplayer** [comment]
@mailwl i have to rename the extension ?

**Comment by mailwl** [comment]
for yuzu - yes, for Ryujinx - no. There is some mess in file extensions

**Comment by greggameplayer** [comment]
@mailwl ok i test and i tell you if it's work

**Comment by mailwl** [comment]
i don't think so. For so fast development any database will be obsolete for every new commit

**Comment by chris062689** [comment]
We already have the same type of thing for Citra. The C++ side just hasn't been ported over to yuzu.

**Comment by greggameplayer** [comment]
@chris062689 that's what i'm talking about

**Comment by Hexagon12** [comment]
This error is caused by not having the appropriate file type for the RomFS file. It has to be .romfs.
Both emulators support this, so .istorage can be dropped completely.

If this would be a shared font issue, you would notice the pl:u calls before the assertion, but since Yuzu creates a blank font file for you to pass that, you shouldn't worry.

Requesting to close.

**Comment by greggameplayer** [comment]
ok I close the issue.
