### ISSUE TITLE
Stopping or restarting a game crashes yuzu in Linux

### ISSUE THREAD

**Issue by potatoeggy** [yuzu-emu/yuzu#4161]
On latest mainline as of 25 June 2020: 4639b23cd9777ef11d61da8d6198b6ebb4f21dd2

Hardware:
 - Ryzen 5 4500U
 - 8 GB DDR4 3200 MHz RAM
 - Arch Linux on kernel 5.7.0

When using F5, F6, or the "Stop" or "Restart" buttons to return to the main menu for both OpenGL and Vulkan, yuzu segfaults.

Steps to reproduce:
 - Open a game
 - Click "Emulation"
 - Click "Stop" or "Restart".

Backtrace:
```
Thread 39 "EmuThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe3696f700 (LWP 1928155)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x0000555555bb2329 in  ()
#2  0x00007ffff687db74 in std::execute_native_thread_routine(void*) (__p=0x555558038430) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#3  0x00007ffff6994422 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff6585bf3 in clone () at /usr/lib/libc.so.6

```

**Comment by premraj59** [comment]
I have the same issue with same specs. Whenever I want to stop or restart, I am now dropping to a different tty and killing yuzu through htop there.

**Comment by psppwner300** [comment]
Similar to OP, this is the output in the terminal after stopping a game:
`dynarmic: POSIX SigHandler: Exception was not in registered code blocks (rip 0x00000000000000)
Segmentation fault (core dumped)`

**Comment by soredake** [comment]
```
dynarmic: POSIX SigHandler: Exception was not in registered code blocks (rip 0x007fca14aa90ac)
fish: './yuzu' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by soredake** [comment]
For me it crashes when starting link's awakening with vulkan.

**Comment by v1993** [comment]
@soredake It is completely different issue, related to Vulkan.

**Comment by mirh** [comment]
The original issue is still a thing btw. 
I'm also having it when I simply want to exit yuzu. 
This doesn't happen in windows.

**Comment by bibitocarlos** [comment]
Still a thing on linux, preventing testing Yuzu on Linux.

**Comment by mirh** [comment]
As you can see between our comments, there is a pending PR (if not even two) for this.

**Comment by bibitocarlos** [comment]
Yep i saw, thank you, but i get conflict to merge it with early-access build so cant test (and i  dont understand which PR i should use ^^)

**Comment by v1993** [comment]
@bibitocarlos I'm not sure how are you trying to merge that PR to get conflicts.

PR #5337 is perfectly mergeable into EA patched yuzu. It does not fix all of hangs on exit, but a large amount of them. I use it without any problems.

PR #5780 is a better solution from technical standpoint, which is not EA-ready because of conflicts with BCR. Don't try to use it for now.

**Comment by v1993** [comment]
Update: commit eae9f2e4404f6bdf8a192bc9c09e53cd87e4359d should mostly fix this issue.

**Comment by potatoeggy** [comment]
Can confirm that the issue resolved in latest mainline.

**Comment by SlimJim192** [comment]
I seem to be experiencing this issue on mainline. Yuzu freezes and I see a white box where there would usually be a status "closing" or something like that
