### ISSUE TITLE
Yuzu 652 EA on FE3H puts you on LSD

### ISSUE THREAD

**Issue by puneet1999** [yuzu-emu/yuzu#4163]
So... whatever was commited between 650-651,652 broke FE3H on opengl during monastery  

![image](https://user-images.githubusercontent.com/59244280/85777532-8f339380-b6d6-11ea-9c94-c2c83c88999e.png)

**Comment by swablueme** [comment]
An issue with 655 as well
![0GxsDvm](https://user-images.githubusercontent.com/10569495/85817444-55838b00-b7b1-11ea-9847-171aeed736ec.png)
