### ISSUE TITLE
Luigi Mansion 3 softlocks on launch with update 1.4.0

### ISSUE THREAD

**Issue by ClaudevonRiegan** [yuzu-emu/yuzu#4181]
when using yuzu 294 mainline, Luigi mansion 3 is stuck with infinite loading screen with update 1.4 but it has no such issue with base version with or without any mods. For reference I have attached a log as well.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4839965/yuzu_log.txt)

![Untitled](https://user-images.githubusercontent.com/63413745/85914705-29721380-b85e-11ea-8710-136863d8be99.png)

**Comment by marianoarga** [comment]
It also happends to me at 1.3.0

**Comment by ReaperOfSouls1909** [comment]
An issue is already opened about what it needs implemented to boot these updates

**Comment by auntcindy29** [comment]
> An issue is already opened about what it needs implemented to boot these updates
> …

and where is the link?

**Comment by Gazoon007** [comment]
Any news about this issue?

**Comment by theboy181** [comment]
![image](https://user-images.githubusercontent.com/9299743/138537506-b9fe4615-5a81-488a-a6b7-40895fc8276c.png)

**Comment by G-Spawn** [comment]
This issue should be corrected on latest yuzu. Please reopen if it still happens. You also require the new 1.4.0 disable dynamic resolution mod https://github.com/theboy181/switch-ptchtxt-mods/blob/main/Luigi's%20Mansion%203/%5B0100DCA0064A6000%5D/1.4.0/Disable-Dynamic-Resoluiton.rar
