### ISSUE TITLE
EA677 Crashing almost everygame

### ISSUE THREAD

**Issue by Kindasecret** [yuzu-emu/yuzu#4197]
**Updated my Nvidia driver to: 451.48**
After that yuzu is just permanently crashing. 
Already cleared the shader Cache

**Tested Games:**
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4842137/yuzu_log.txt)
**Animal Crossing New Horizon:**
- Before: solid 30 FPS
- After: Wont Start - Yuzu crashing.

**Super Mario Odyssey:**
- Before: almost solid 60 FPS, only the cutscenes were bit laggy
- After: 10 FPS, crashing after 30 seconds in game.

**My Specs:**
Intel I5 7500 @3400GHz
Geforce GTX 1060 Driver 451.48
16Gb Ram @ 3400MHz
Windows 10 Version 2004

**Comment by BSoDGamingYT** [comment]
Please use discord for this kind of thing in future. these issues are not for this sort of thing. This issue will be solved in the next EA build

**Comment by ogniK5377** [comment]
The issue should be fixed in the next EA build. 677 was a bad build spat out by our build system. Use EA 678
