### ISSUE TITLE
Implement ioctl [Request]

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#420]
## Hardware Specs :
- Nvidia GeForce GTX 960
- Intel I7-7700k @ 4.5Ghz
- 8 GB Of Ram 3200Mhz
- Windows 10 Pro

## The issue :
When you launch Super Bomberman R, the game crash with the "assertion failed, unimplemented ioctl" error

**Comment by Hexagon12** [comment]
That doesn't tell us anything. No log, no anything. Even the title doesn't tell the exact problem.

**Comment by greggameplayer** [comment]
@Hexagon12 I can't give you the complete log because of the fact that it doesn't write all the log in the file

**Comment by greggameplayer** [comment]
@Hexagon12 That the part i'm able to give : https://gist.github.com/greggameplayer/c9086303e871ff653cc593e051b2db08

**Comment by greggameplayer** [comment]
@Tempacc129 why are you saying that ?

**Comment by greggameplayer** [comment]
@Tempacc129 you want to get banned. You've never do a thing for yuzu so close your mouth and delete your comment.

**Comment by greggameplayer** [comment]
Cartoon network Battle Crashers have the same issue both in single and multi-cores.
And also i have tested Super Bomberman R in multi-cored and the issue happen too.

**Comment by greggameplayer** [comment]
Tiny Barbarian DX have the same issue both in single and multi-cores.
But this is game is reported to work on RyujiNX. So in my opinion you have to look in the RyujiNX in order to correct this issue on this game. I will try the others games, i have reported in order to see if they work on RyujiNX.

**Comment by greggameplayer** [comment]
## Some good news : 
Tiny Barabarian DX now work but has weird textures and freeze at the end of the intro and super bomberman R now go further but are stuck on AppendAudioOutBuffer and GetReleasedAudioOutBuffer. 

## One Bad news : 
cartoon network battle crashers continue to do this error.

**Comment by Hexagon12** [comment]
Most of the required ioctl commands used by games have been implemented. If both games do not crash anymore due to this, please close this issue.

**Comment by Hexagon12** [comment]
Bumping to close this issue.

**Comment by Dantttt** [comment]
No more crashes,please close!!

**Comment by bukyapavankumar** [comment]
Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl

getting this error ,is this issue  not solved properly?
