### ISSUE TITLE
Smash Bros Ultimate Softlock Character Selection. 

### ISSUE THREAD

**Issue by JaviBOT96** [yuzu-emu/yuzu#4200]
Hi, guys i have an issue with Yuzu emulator while im playing Super Smash Bros Ultimate, there's a softlock after a match or during character selection.

Sometimes the character selection gets slow, or frozen for a few seconds, after that  it gets softlocked. 
I've already tried the basic troubleshoot provided by YuzuDiscord Patreon Support Channel, but it's the same, issue is happening at this point only on that mentioned game. YuzuLog doesn't show enough info.
I'm using 

YuzuEA 681
GTX 1650 SUPER
16GB RAM DDR4 2600Mhz 
SSD 240GB for Yuzu only. 
30.000MB pagefile.
Ryzen 5 3600

Thanks in advance, if there's any other troubleshoot i must do, just let me know.

**Comment by psppwner300** [comment]
Can confirm I'm also getting the same issue on Linux. Running the game through the terminal I get this message on the CSS or random other places:
`terminate called after throwing an instance of 'Vulkan::vk::Exception'
  what():  VK_ERROR_OUT_OF_DEVICE_MEMORY
Aborted (core dumped)`

It's definitely not out of memory as I just upgraded my rig to 16 GB of RAM; it barely pushes past 8.

- Yuzu 309
- i5-8400
- RX 570
- 16 GB RAM

**Comment by Morph1984** [comment]
This issue has been reported to be fixed, closing.
