### ISSUE TITLE
Setting Location of AppData Folders to Manual Location

### ISSUE THREAD

**Issue by RaijinXBlade** [yuzu-emu/yuzu#4201]
Hi there. I've been told on the Discord to submit this here.

I have 2 drives, and I installed Yuzu onto my second drive, however the appdata contents are automatically set to my main drive by default. Someone mentioned that it was done that way because in the past, you'd get too many questions because people installed things in strange places and nothing would work, so, how about making it behave like it does currently by default for people like those, but also having an option somewhere in the installer to manually set where to install/have the appdata contents (this can also be appIied to Citra)?

Best regards!

**Comment by Nezarn** [comment]
you can just create a "user" folder in yuzu's folder (where the exe is) then it will save everything there and not in AppData.

**Comment by FearlessTobi** [comment]
What Nezarn said is correct.
