### ISSUE TITLE
Save File Issue using Vulcan

### ISSUE THREAD

**Issue by mgfreak** [yuzu-emu/yuzu#4205]
Hi there I have been told to post this error here,

I know the game just released Last June 25, but it is 100% playable in EA Build 654 until EA build before 678, I played it smoothly.

but the updates today, June 29th 2020, won't let me load the my save file. It just freezes in the loading screen after I clicked my load file. fortunately I have a build 654 backup, I made a backup because all my games are running really Great in this build except Pokemon Sword (Fps drop). 

Currently I'm using 654 build and it loads my save file just like before and smoothly.

Best Regards.

UPDATE: I tried using Open GL and it works on the current EA build. So Might be Vulcan Issue.

**Comment by liamwhite** [comment]
Comment with a yuzu log if this is still relevant
