### ISSUE TITLE
Random softlocks on Linux

### ISSUE THREAD

**Issue by potatoeggy** [yuzu-emu/yuzu#4207]
Hardware:
 - AMD Ryzen 5 4500U
 - 8 GB DDR4 3200 MHz RAM
 - Arch Linux, kernel 5.7.0

Reproduction steps:
 - Open a game
 - Play the game normally until it is no longer responsive

This has been observed in Pokémon Shield, Pokémon: Let's Go, Eevee!, Pokkén Tournament DX, Super Mario Odyssey, and Pokémon Mystery Dungeon: Rescue Team DX on the latest mainline as of writing (f84cbf6429926f5c0e9dcd7a7b26198d41343d4c).

Sometimes, with async GPU emulation, multicore, and OpenGL enabled (untested with other combinations), the screen freezes while any music continues playing in the background. The audio seems to randomly either loop a specific section or continue playing normally. There is no feedback from the game if buttons are pressed. yuzu itself seems to be fine, as the Qt UI is still responsive.

The primary issue in the log seems to be the following line: 
`[  26.269271] HW.Memory <Error> core/memory.cpp:Read:641: Unmapped Read32 @ 0x00238284`
which is repeated with addresses in increasing order.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4847725/yuzu_log.txt)

**Comment by potatoeggy** [comment]
I attached the wrong log; here's the actual one: https://mega.nz/file/e3wR0ARa#bQhBR9rGXpT3QdmvJw1vIhRJsynVHakwWdrcSpgeFKM (~50 MB)

**Comment by liamwhite** [comment]
I cannot reproduce this issue with current mainline builds and have been playing for hours daily without issues. Comment if this is still relevant.
