### ISSUE TITLE
Yuzu crashes with the following error: "libboost_context.so not found"

### ISSUE THREAD

**Issue by Nilot352** [yuzu-emu/yuzu#4212]
`./yuzu: error while loading shared libraries: libboost_context.so.1.71.0: cannot open shared object file: No such file or directory`

The OS is Ubuntu 19.04
The GPU is 1060 6GB variant running nvidia driver 440 
and the CPU is an i5 7600k.

**Comment by Morph1984** [comment]
Update to 20.04

**Comment by leolucca518** [comment]
I'm on Ubuntu 20.04 already did an apt-update/ upgrade  same issue

./yuzu: error while loading shared libraries: libboost_context.so.1.71.0: cannot open shared object file: No such file or directory`

GPU is RX 580 running mesa driver
CPU is Ryzen 3 3200g

**Comment by evilynux** [comment]
Do you have libboost-context1.71.0 installed?

**Comment by iWeaker4you** [comment]
19.04 is EOL, is not supported since September / October last year.
19.10 will stop having support this month.
You require a library that from a distro that is updated as of 20.04

**Comment by gdelazzari** [comment]
It's funny that on Arch Linux I have the opposite problem: I have `libboost_context.so.1.72.0.so` which is newer than what yuzu requires. I'm not blaming yuzu of course, I know this is Arch Linux being "too much up-to-date" sometimes. But maybe a better approach could be to statically link with the needed libraries? I'm wondering if the fact that yuzu requires those dynamic libraries is something introduced recently or it has always been like this.

**Comment by WittyNameHere** [comment]
The same error now appears in Fedora 32 (latest). From the bug tracker report makes it appears that building it is not easy and the current plan is [Boost will be on 1.69 until Fedora 33 ships](https://bugzilla.redhat.com/show_bug.cgi?id=1558278) in the fall.

**Comment by EternalBlueFlame** [comment]
Installing `libboost-context1.71.0` from the ubuntu focal repo fixed this for me.

Not sure how helpful it is to users of non-debian based linux, but Canonical hosts the debian installers for the package here: https://packages.ubuntu.com/focal/libboost-context1.71.0

**Comment by lat9nq** [comment]
Besides 19.04 no longer being a supported OS, this is a non-issue now with the build system statically linking libboost_context to yuzu (so there's no libboost_context1.73.0 to link to at all now.)
