### ISSUE TITLE
Pokemon sword Freezing

### ISSUE THREAD

**Issue by Eroc444** [yuzu-emu/yuzu#4229]
Game freezes to 0 frames and audio is still played.

Using Yuzu 300.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4867437/yuzu_log.txt)

Happens after battles or during cutscenes.

**Comment by Amuren** [comment]
I'm struggling with that problem too.

**Comment by Aris-t2** [comment]
Last working yuzu build was EA 678.

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/4227.
