### ISSUE TITLE
Yuzu emulator sound bug in Crash team racing 

### ISSUE THREAD

**Issue by ScorpionX3** [yuzu-emu/yuzu#4231]
whatever i do it doesn't work i have tested every setting but still no sound in the game unless i make multicore out only then i have 10-15fps in the game

I made a video so that you can understand exactly what I mean
i have really tried a lot
and yuzu EA is same problem 
https://www.youtube.com/watch?v=O8DF67wu8Bk&feature=youtu.b

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by ScorpionX3** [comment]
i dont want halp its a issue what a post or i say HELP ME !!! ??? open it or i repost it

**Comment by legend800** [comment]
I hit this issue a bunch yesterday. Either cuts out at menu or on race start and never comes back. Happened numerous times on EA and on master. I changed to docked and haven't seen the issue since thankfully.
