### ISSUE TITLE
UltimateModLoader controller not working.

### ISSUE THREAD

**Issue by Nilot352** [yuzu-emu/yuzu#4232]
I am using the latest yuzu mainline version and have followed the following [guide](https://gamebanana.com/tuts/13154) and am using an Xbox One S Controller which works in the games but not with this homebrew as in I cannot interact with this ModLoader at all by pressing any button on the controller, I am loading this modloader via the .nro file.

I cannot therefore install any Smash Bros. ultimate mods at all.

Tell me if you need any further info.

**Comment by ClaudevonRiegan** [comment]
It works perfectly fine on Yuzu mainline 300 (latest rn). You must have messed something kindly try again. I am sure of it
