### ISSUE TITLE
animal crossing new horizons 1.3.0 boot crash

### ISSUE THREAD

**Issue by alexandrage** [yuzu-emu/yuzu#4233]
[  14.713401] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:258: Backtrace, sp=000000000000000E, pc=000000000C8DF734
[  14.713403] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:260: Module Name         Address             Original Address    Offset              Symbol
[  14.713404] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:261:
[  14.753085] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 00000071001464D8    000000000C68F4D8    00000000001464D8    _ZN2nn4diag6detail5AbortEPKNS_6ResultE
[  14.753090] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 0000007100144D80    000000000C68DD80    0000000000144D80    _ZN2nn4diag6detail10VAbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoES3_RSt9__va_list
[  14.753091] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 0000007100144E54    000000000C68DE54    0000000000144E54    _ZN2nn4diag6detail9AbortImplEPKcS3_S3_iPKNS_6ResultES3_z
[  14.753093] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 00000071003C489C    000000000C90D89C    00000000003C489C
[  14.753103] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 00000071003C4554    000000000C90D554    00000000003C4554    _ZN2nn2vi11CreateLayerEPPNS0_5LayerEPNS0_7DisplayE
[  14.753104] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: main                0000007101BBC834    0000000009BC0834    0000000001BBC834
[  14.753105] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: main                0000007101EB8354    0000000009EBC354    0000000001EB8354
[  14.753106] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 00000071002A3C00    000000000C7ECC00    00000000002A3C00    _ZN2nn4init5StartEmmPFvvES2_S2_
[  14.753107] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: rtld                00000071000000D0    00000000080000D0    00000000000000D0

**Comment by ogniK5377** [comment]
Please refer to the issue template. Please provide a log file & the version of yuzu you are using next time.
