### ISSUE TITLE
Missing HLE service command 'CreateManagedDisplaySeparableLayer' in 'ISelfController' (AM)

### ISSUE THREAD

**Issue by VolcaEM** [yuzu-emu/yuzu#4235]
- Needed for 'Animal Crossing: New Horizons' version 1.3.0

The service command was introduced in Switch version 10.0.0.

[From Switchbrew](https://switchbrew.org/wiki/Applet_Manager_services#CreateManagedDisplaySeparableLayer):
"No input, returns two output u64 LayerIds.

sdknso now uses this instead of #CreateManagedDisplayLayer. sdknso caches the output from the cmd so that it's only used once. The first u64 is used the same as the original LayerId from #CreateManagedDisplayLayer. nn::vi::CreateRecordingLayer uses the second LayerId, the layer creation is identical besides which LayerId is used."

Reporter log (not mine): [here](https://github.com/yuzu-emu/yuzu/issues/4234)

**Comment by Aris-t2** [comment]
Full HLE error area from that log.

[  19.701776] Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:154: Assertion Failed! Unknown / unimplemented function 'CreateManagedDisplaySeparableLayer': port='ISelfController' cmd_buf={[0]=0x6, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x6, [6]=0x0, [7]=0x0, [8]=0x49434653}

[  19.701780] Debug <Critical> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:173: Assertion Failed!

[  19.701781] Debug <Critical> core\hle\kernel\hle_ipc.cpp:WriteToOutgoingCommandBuffer:271: Assertion Failed!

[  19.704890] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1345: (STUBBED) called, result=0x0001A80A

[  19.705391] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:615: Signalling debugger, PANIC! info1=0x000000100D503C20, info2=0x0000000000000004

[  19.705395] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:operator ():596: debug_buffer_err_code=1A80A

[  19.705399] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:667: Emulated program broke execution! reason=0x0000000000000000, info1=0x000000100D503C20, info2=0x0000000000000004

**Comment by Aris-t2** [comment]
Fixed on EA 710.
