### ISSUE TITLE
Mssing "GetVideoOperand"

### ISSUE THREAD

**Issue by Axeels** [yuzu-emu/yuzu#4236]
Groove Coaster Wai Wai Party no longer boots cause of unimplemented codes.
EA 703.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4870819/yuzu_log.txt)

Debug <Critical> video_core\shader\decode\video.cpp:GetVideoOperand:109: Assertion Failed! Unimplemented code!

HW.GPU <Warning> video_core\shader\decode\other.cpp:DecodeOther:292: ISBERD instruction is incomplete

**Comment by german77** [comment]
The game is working on yuzu 680
