### ISSUE TITLE
How can I help Yuzu/ Devs  improve BOTW?

### ISSUE THREAD

**Issue by citrinemachine** [yuzu-emu/yuzu#4238]
I have EA and low frame rate.

**Comment by Ghostotakoi** [comment]
You should ask on their discord, their git is not for this.
You can or help them programming in C++ or pledging on their Patreon. But the low framerate probably is because your pc is not powerful enough to run it well.

**Comment by ExsertWizard** [comment]
It would be appreciated if the repository wasn't cluttered with these types of messages for issue tracking. You can help the devs by doing what's mentioned above.

Requesting to close.
