### ISSUE TITLE
Unimplemented service command 'LoadIdTokenCache' in 'IManagerForApplication'

### ISSUE THREAD

**Issue by ghost** [yuzu-emu/yuzu#4239]
This is a follow-up to [Issue 3919](https://github.com/yuzu-emu/yuzu/issues/3919) where the game wouldn't boot up at all because of a missing opcode. Now with the opcode implemented, the game boots up with a popup, but shortly after crashes due to another missing opcode. The line in question is:
`Unknown / unimplemented function 'LoadIdTokenCache': port='IManagerForApplication' cmd_buf={[0]=0x1000006, [1]=0xC, [2]=0xC00, [3]=0x1007CA49, [4]=0x0, [5]=0x0, [6]=0x0, [7]=0x0, [8]=0x100001}`

I built from commit [3096adb](https://github.com/yuzu-emu/yuzu/commit/3096adb3471af1b094d670751e476c337007d299).

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4872188/yuzu_log.txt)

**Comment by benderscruffy** [comment]
can be closed
