### ISSUE TITLE
Animal Crossing singing bug

### ISSUE THREAD

**Issue by Haki2k1** [yuzu-emu/yuzu#4244]
My villagers won't sing correctly. Every time they sing, they are off-sync and off-tune. I've been searching a solution for weeks but it seems like I'm the only one getting this issue

Example: https://mega.nz/file/J7ZCWIQZ#TsQVeSWjoiFEhmgqXx7sdz6opz61dwFebnVrW9P8veM

**Comment by i32cagoa** [comment]
I haven't tried it but i'm sure that it will happen to me too because in some areas the speech is too fast.
Are you in AMD or NVIDIA GPU? 
Probably, we just have to wait for it to be fixed in future updates.

**Comment by Haki2k1** [comment]
I have NVIDIA, and well, it seems like the bug is being fixed since EA 749 thanks to Apollo project. The only problem is that the audio of the villagers' dialogues is bugged now. Hope they fix it soon in part 2.

**Comment by german77** [comment]
Please confirm if this is fixed now

**Comment by G-Spawn** [comment]
Feel free to reopen issue if this still happens to you on latest yuzu versions & gpu drivers.
