### ISSUE TITLE
can 't use vulkan anymore. crash immediately when boot games by vulkan

### ISSUE THREAD

**Issue by Lkids-innocence** [yuzu-emu/yuzu#4246]
After I update the Nvidia Game Ready drive to 451.48,i can 't use vulkan anymore.I  guess maybe the reason is nivida update its vulkan instance version to 1.2.131.So I wonder how to deal with this problem ^-^ Thanks for your hardwork

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord server for support requests.
