### ISSUE TITLE
Mario + Rabbids Crashes right after launch

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#4251]
Mario+Rabbids v1.9.5 with all dlcs crashes after the launching page on yuzu 709

Log File:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4875519/yuzu_log.txt)

**Comment by BornIncompetence** [comment]
Are you sure you pasted the correct log file?

The log file shows you were trying to load Spongebob: Battle for Bikini Bottom.

As for M+R, I have Intel CPU and GTX 1060 6GB as well, and I'm able to boot into game on 737.

**Comment by EliasM108** [comment]
> Are you sure you pasted the correct log file?
> 
> The log file shows you were trying to load Spongebob: Battle for Bikini Bottom.
> 
> As for M+R, I have Intel CPU and GTX 1060 6GB as well, and I'm able to boot into game on 737.

I deleted the spongebob game and retried to play M+R but nothing changed. Here is my log file on EA 737 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4908170/yuzu_log.txt)

**Comment by EliasM108** [comment]
dock mode fixed the problem
