### ISSUE TITLE
Fire Emblem Three Houses memory leak

### ISSUE THREAD

**Issue by HyrHT** [yuzu-emu/yuzu#4252]
Three houses memory leak/spike leading to crash, in battle just as a fight animation was loading. Happens with some regularity most places in game, but only momentary freeze to then resume. Yuzu 710 version.

ryzen 5 3600x
16gb ram
5700xt

[yuzu_log - Copy.txt](https://github.com/yuzu-emu/yuzu/files/4876358/yuzu_log.-.Copy.txt)

**Comment by HyrHT** [comment]
To put it mildly, Yuzu is using a /lot/ more ram than this https://www.patreon.com/posts/new-feature-35856792 even when running smoothly far away from anny freeze or crash. Now booting up at the same place it crashed, it's using slightly less than 9gb ram

**Comment by Alex-Aralis** [comment]
I've also been seeing a similar crash for FE:3H. Cut off log output an all. After about 90mins in a map the game falls over. I can watch the memory usage stack up in real time.

**Comment by HyrHT** [comment]
This was with vulkan, have now played through battle without async shader with opengl, no issues encountered.

**Comment by Alex-Aralis** [comment]
I've been running with opengl and seeing the crash. I'll try without async shaders and see if that fixes the issue.
