### ISSUE TITLE
Animal Crossing: New Horizons Black fog in the background on 1.3.0 even with Disable DOF Mod.

### ISSUE THREAD

**Issue by rdude** [yuzu-emu/yuzu#4256]
This bug was present using an RTX 2080 Super in Vulkan and OpenGL. EarlyAccess Build.

Scenery in the distance and rivers is black.

On version 1.2.0/1.2.1 fixing by Mod (Disable DOF), but on version 1.3.0 issue is still present even with mod.

Thank you in advance!

**Comment by ToxaGaming** [comment]
download the updated mod for the yuzu mod site. for future reference, this is an issue tracker for developers, not for general issues. those should be reported in the yuzu Discord server :)

**Comment by rdude** [comment]
Thank you! Mod page on site (https://yuzu-emu.org/wiki/switch-mods/) has none actual versions of mods, but page on github has actual ones.
