### ISSUE TITLE
Using the super smash bross ultimate dlc, the main menu after the intro gets very slow.

### ISSUE THREAD

**Issue by YeisonVelez11** [yuzu-emu/yuzu#4260]
When I use the super smash bross dlcs the menu gets very slow, but the fights are shown at normal speed, this does not happen if I use VULKAN.

Yuzu early access 710

**Comment by raven02** [comment]
Revert back to use 446.14 Nvidia driver if are you are using Nvidia Card

**Comment by YeisonVelez11** [comment]
@raven02  Thank you very much for your answer. I actually have an nvidia 1080 ti. Do you recommend resetting to that version or better I hope this is corrected in the future?

**Comment by raven02** [comment]
Yes reinstall to that version fixed the issue
