### ISSUE TITLE
Monster Hunter Generations Ultimate - Black screen and loading times

### ISSUE THREAD

**Issue by Blitz255** [yuzu-emu/yuzu#4262]
Everytime after beginning a quest there's a black screen that takes like a minute or 2 to disappear and load the quest, then again when in the quest it takes more 2 minutes to switch between each area.

**Comment by FearlessTobi** [comment]
Can you please provide a log file?

**Comment by Desmondchaser27** [comment]
I don't have this issue exactly, but I do get infinite loading/freezing every once in awhile on the Jurassic Frontier map.

**Comment by Desmondchaser27** [comment]
This was the log file for the game loading forever when trying to load the Jurassic Frontier map.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5080371/yuzu_log.txt)

**Comment by Desmondchaser27** [comment]
Okay, so I figured out what triggers it.  Vsync breaks the game if you're using the 60FPS Cheat.  I think the game loads first, which tells Yuzu that Vsync should be set for 30FPS.  Then the cheat is applied and runs at 60FPS.  This causes some issues when loading sometimes, I guess.  Turning off Vsync solved my freezing issue.

**Comment by benderscruffy** [comment]
please close

**Comment by Blitz255** [comment]
Solved 😊

**Comment by Desmondchaser27** [comment]
> Solved 😊

Assuming this issue no longer exists, very nice!
