### ISSUE TITLE
[Request] Citra Tools

### ISSUE THREAD

**Issue by BrunoRaji** [yuzu-emu/yuzu#4264]
this must be very early, it is, as far as I know the Yuzu developers are the same as Citra so I would like to ask for the same tools like: Record Movie, Frame Advance and Dump Video

just for developers to know that there are people who are interested in these tools

Thanks for the attention

**Comment by MiYakuGaming** [comment]
I second this, it's why I haven't used Yuzu yet outside of testing, I want to be able to record input and video / audio just like Citra does.

**Comment by liamwhite** [comment]
Seems to be a duplicate of https://github.com/yuzu-emu/yuzu/issues/3750
