### ISSUE TITLE
Yuzu crashed after i defeat leon in pokemon shield 

### ISSUE THREAD

**Issue by Sushant1965** [yuzu-emu/yuzu#4267]
I'm using yuzu 303

CPU: AMD FX-8320E Eight-Core Processor
Ram 8 GB
GT 730 DDR5 2GB

Log:-
[Uploading yuzu_log.txt…]()

![Microsoft Game DVR - yuzu Early Access 703 _ Pokémon Shield - VLC media player 07_Jul_2020 9_35_03 PM](https://user-images.githubusercontent.com/67960240/86810112-367ed600-c09a-11ea-8585-c19c9c558ce6.png)
![Microsoft Game DVR - yuzu Early Access 703 _ Pokémon Shield - VLC media player 07_Jul_2020 9_35_35 PM](https://user-images.githubusercontent.com/67960240/86810122-38489980-c09a-11ea-9a34-4a81124f18aa.png)
![Microsoft Game DVR - yuzu Early Access 703 _ Pokémon Shield - VLC media player 07_Jul_2020 9_35_03 PM](https://user-images.githubusercontent.com/67960240/86810153-40a0d480-c09a-11ea-9be5-622a2127a548.png)

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our forums or our Discord for support requests.

**Comment by MIKA123123** [comment]
whats the discord server?
