### ISSUE TITLE
Yuzu doesn't react to button pressing after disconnecting and connecting DS4 again during gaming

### ISSUE THREAD

**Issue by Emogop** [yuzu-emu/yuzu#4268]
I got DS4 controller connected through micro usb. Sometimes during excessive motions it briefly disconnects from PC. After that Yuzu stops react on it until I remapped the buttons or relaunch the application entirely. It's annoying to say the least.
I'm using it without DS4 Windows wrapper, with it it's fine.

**Comment by EgoBizarro** [comment]
I (and someone else who tested so it's not just me) have a similar issue that might or might not be connected to this one:
I'm using an Xbox One Controller, sometimes wireless, sometimes with cable (to charge). Unfortunately, yuzu doesn't seem to recognize the controller as the same, and each time I change to or from wireless, I have to rebind everything.

**Comment by Zuchter** [comment]
> I (and someone else who tested so it's not just me) have a similar issue that might or might not be connected to this one:
> I'm using an Xbox One Controller, sometimes wireless, sometimes with cable (to charge). Unfortunately, yuzu doesn't seem to recognize the controller as the same, and each time I change to or from wireless, I have to rebind everything.

I have the same issue with an Xbox one controller, it also happens in Citra and maybe Cemu but im not exactly sure about that one.

**Comment by EgoBizarro** [comment]
I know it doesn't happen in Dolphin. I can disconnect the controller in-game and continue playing wirelessly; also re-connecting via cable works the same. So I guess it should theoretically be possible in an emulator.

**Comment by umarnet** [comment]
I have an issue where Yuzu (322) does not detect input when mapping keys using the DS4 controller. I have tested the controller with Citra and Cemu and it's working fine. I'm using the latest DS4windows with ViGEmBus Driver.

**Comment by Emogop** [comment]
It hasn't been fixed for me. I managed it one time, but all the other times Yuzu would just crashed after I tried to go to the settings menu after disconnection took place.
Here's the log:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5143301/yuzu_log.zip)
