### ISSUE TITLE
Two players Animal Crossing New Horizons

### ISSUE THREAD

**Issue by SrAlvaritop** [yuzu-emu/yuzu#4271]
Hi there!
I have my own savegame of ac:nh created in other emulator, but i see that yuzu works much better in animal crossing with vulkan, so now i'm starting using yuzu.

The problem is that i want to create a second player (using the profiles option in yuzu), but yuzu crash in character creation of the second player so i cant create the new secondary player :( (In the other emulator the profile option is not developed)

I have an RX 480 4GB, 16 GB RAM and I5 9400F.

Can someone help me? Another option I have contemplated is to use a saved game from someone with two players already created, but I can't find any ... I would be very grateful if someone who had a game like this could send it to me.

Srry for my english, I hope someone can help me <3

![image](https://user-images.githubusercontent.com/9350674/86861383-47920c00-c0c7-11ea-9844-58f25fd7d112.png)

**Comment by Aris-t2** [comment]
You said you created your save state with Ryujinx, so use this workaround:

1. Move your savegame to Yuzu (you did this already) and do not create a new villager on startup, load the current one.
2. Start/load the game, save the game and exit the game.
3. Move save state from Yuzu back to Ryujinx.
4. Create second villager.

The game does not offer you a way to chose the villager on startup, so you have to move savegames between Yuzu and Ryujinx, if you want to use the "other" villager.

**Comment by i32cagoa** [comment]
If I move my actual Yuzu savegame back to Ryujinx, the game starts in Ryujinx with my 1st and main villager and i haven't chance to create a new profile to create a second villager.

I'm creating a new savegame in Yuzu EA365 and AC:NH 1.1.1, because in that version i can create a character without crash. 
If I succeed I will upload my savegame in case someone is in the same situation and want to play with a friend. ^^

Thanx for answer :3

**Comment by Aris-t2** [comment]
I tested this with **ACNZ v1.3.0** in **Yuzu EA 71x** and **Ryujinx 1.0.4864**.
It was possible to create a new one or to use the current/old one.

Can't tell much about how this is handled by "Yuzu EA365 and AC:NH 1.1.1".

**Comment by i32cagoa** [comment]
Woops, I was not able to do it with that method. I just create a new villager with **Yuzu EA 365** and **AC:NH 1.1.1**, it works for me.

![image](https://user-images.githubusercontent.com/9350674/86941926-d2fdb280-c144-11ea-992e-cdd91a18abee.png)

I leave the gamesave here for everyone who wants to use it, you can change the name with external programs to edit the savegame (NHSE). Have fun!

DOWNLOAD: https://drive.google.com/uc?id=1wTsuFlv_YkLu9ZMtFsOXZghrwaGKUMz7

**Comment by i32cagoa** [comment]
Well here i am once again, 
after playing several hours with friends I have noticed that the game stops randomly, although it is almost always when loading something. It looks like a memory overflow but I see it normal, this is an emulator in development.

Anyway I am amazed with the performance of this emulator in Vulkan, good job Yuzu Team ^^

**Comment by benderscruffy** [comment]
Is this still an issue ??

**Comment by liamwhite** [comment]
Comment with a yuzu log if this is still relevant
