### ISSUE TITLE
Yuzu crashes on connecting generic USB Gamepad

### ISSUE THREAD

**Issue by YashSinha1996** [yuzu-emu/yuzu#4274]
I am having an issue where yuzu doesn't launch as long as I have my controller connected
I am using a cheap off-brand controller and use x360ce to help run it on normal PC games (for better controller mapping)
Any idea what could be happening and/or what I can do to make it not happen?
If I have yuzu launched and then I connect my controller, yuzu proactively crashes

yuzu version: Mainline build 306
OS: Windows 10
Gamepad: USB Joystick (Vendor: 0079 Product: 0006) from https://html5gamepad.com/ 
([This one](http://live-tech.in/gp01.php) for what it's worth)

Event log from Windows event logger
```
Faulting application name: yuzu.exe, version: 0.0.0.0, time stamp: 0x5f05bc6b
Faulting module name: yuzu.exe, version: 0.0.0.0, time stamp: 0x5f05bc6b
Exception code: 0xc0000005
Fault offset: 0x000000000016d972
Faulting process id: 0x3c4c
Faulting application start time: 0x01d6553bcec379d9
Faulting application path: C:\Users\Yash Sinha\AppData\Local\yuzu\yuzu-windows-msvc\yuzu.exe
Faulting module path: C:\Users\Yash Sinha\AppData\Local\yuzu\yuzu-windows-msvc\yuzu.exe
Report Id: 8d707c27-be89-4577-80ee-f5ef29fea66e
Faulting package full name: 
Faulting package-relative application ID: 
```
and 

```
Faulting application name: yuzu.exe, version: 0.0.0.0, time stamp: 0x5f05bc6b
Faulting module name: EZFRD64.DLL, version: 0.0.0.0, time stamp: 0x4693218c
Exception code: 0xc0000005
Fault offset: 0x0000000000003654
Faulting process id: 0x313c
Faulting application start time: 0x01d6553e83a08c2d
Faulting application path: C:\Users\Yash Sinha\AppData\Local\yuzu\yuzu-windows-msvc\yuzu.exe
Faulting module path: C:\WINDOWS\USB Vibration\7906\EZFRD64.DLL
Report Id: b728b48d-af28-4184-b58e-f321498aa33c
Faulting package full name: 
Faulting package-relative application ID: 
```

The same issue existis in Citra too, with the same faulting module

**Comment by YashSinha1996** [comment]
Figured it out. This was due to faulty drivers of my shitty gamepad. Fixed it by removing the custom drivers. Similar to another error here:
https://forums.codemasters.com/topic/43460-grid-2019-error-ezfrd64dll/

Working well now.  Thanks!

**Comment by matiasramirez1601** [comment]
I solved it with this video
https://www.youtube.com/watch?v=bT3b7kzV8LQ&ab_channel=RAZORBIGPC
