### ISSUE TITLE
[Request] Warning for end-user when pagefile is too small

### ISSUE THREAD

**Issue by jon-reid** [yuzu-emu/yuzu#4278]
Show the user a warning message if their pagefile is below the recommended size based on their RAM amount and current pagefile size.

This would hopefully reduce the number of support requests received.

**Comment by psppwner300** [comment]
How does one make a pagefile in Ubuntu?

**Comment by G-Spawn** [comment]
this *kind of* is already satisfied by yuzu's error for werfault https://yuzu-emu.org/wiki/faq/#games-fail-to-launch-with-the-error-werfaultexe---application-error---the-application-was-unable-to-start-correctly
