### ISSUE TITLE
MK8D: Tracks are sometimes invisible/don't render

### ISSUE THREAD

**Issue by Jatoxo** [yuzu-emu/yuzu#4299]
On MK8D, particularly on "Cloudtop Cruise", the track doesn't render in some places, and in others instead leaves a trail of artifacts where it is supposed to be ~~when Assembly Shaders are turned on (just like Splatoon 2)~~. This happens on EA 733. Some other tracks seem to be affected as well, however, it might not be track specific. "Sunshine Airport" had the same artifact rendering the first time, but after exiting, playing a different track, and coming back it was rendering normally.

Invisible Track 
![2](https://user-images.githubusercontent.com/39669932/87227996-ac3ab880-c39e-11ea-8253-74170d1c6320.jpg)

Artifacts
![1](https://user-images.githubusercontent.com/39669932/87228011-b8267a80-c39e-11ea-99e9-6f393aea8847.jpg)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4907052/yuzu_log.txt)

**Comment by Lightwolve18** [comment]
I think it's not a arb problem for this game

**Comment by Jatoxo** [comment]
Tested the first time with ARB, issue was there. Tested again on Vulkan, issue was gone. Tested again with ARB, issue was there again. Tested on OpenGL without ARB, issue was not there.

Maybe the RNG gods made me draw a false conclusion but I'm pretty sure it's related

**Comment by 7oxicshadow** [comment]
I have just done some quick testing on Linux and for me the problems shown in the screenshots above happen regardless of the renderer or the on/off state of assembly shaders.

On the plus side, the performance was great. The only thing i noticed was missing was the videos which if i recall correctly, support for x264 decoding was needed on CEMU.

**Comment by legend800** [comment]
Yeah, I've tested this game for several hours in the past few days and loading tracks hundreds of times and there's no setting or configuration that affects anything. It's mostly, for each session, you have to load the track once and then it might render correctly on a second time. But that's not of guarantee. I sat there and loaded the same track 7 times and it was broken every time. And that makes Grand Prix impossible to playthrough. 

We just need a proper emulator fix to the texture loading here. There's no workaround.

**Comment by raven02** [comment]
It also happened in Vulkan API.

**Comment by Jatoxo** [comment]
Seems like this issue is fixed by #4430

**Comment by Jatoxo** [comment]
Fixed
