### ISSUE TITLE
Mario odyssey has extreme graphic stutter

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#4307]
Tried with and without the 1.3.0 dlc, but the results are the same. Also, deleted the old shader cache.
Log file:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4908161/yuzu_log.txt)

![Χωρίς τίτλο](https://user-images.githubusercontent.com/51413997/87241262-e43b0d80-c429-11ea-9df7-8829ee5bb89b.png)

**Comment by goldenx86** [comment]
Disable the game update and enable assembly shaders in the advanced tab of graphics settings.
Also, GitHub is for error reporting, not for providing support.

**Comment by EliasM108** [comment]
> Disable the game update and enable async shaders in the advanced tab of graphics settings.
> Also, GitHub is for error reporting, not for providing support.

I know. I tried multiple configurations including the one you suggested but the stutter persists, so i believe its a yuzu issue.
Log File (without dlc and with async shaders on):
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4908201/yuzu_log.txt)

**Comment by Jatoxo** [comment]
Enable docked

**Comment by EliasM108** [comment]
> Enable docked

that actuallly fixed it. Even the 1.3.0 is playable!
