### ISSUE TITLE
Wierd green bug when entering route 1 in pokemon sword/shield

### ISSUE THREAD

**Issue by monodogie** [yuzu-emu/yuzu#4325]
![image](https://user-images.githubusercontent.com/68215740/87273349-85d16600-c4e1-11ea-952c-ca09e6597dac.png)
When entrering to route 1 I encountered a green scatter that looks like it is coming from afar.
Did anyone encounter this befor?

**Comment by Morph1984** [comment]
Can you provide information such as
1. The yuzu log
2. Your hardware specs

Please read the issue template and provide the necessary info prior to creating the issue

**Comment by FearlessTobi** [comment]
Closing for now as creator is unresponsive.
I'll reopen if we actually get the required info.
