### ISSUE TITLE
yuzu bug report for the development

### ISSUE THREAD

**Issue by ScorpionX3** [yuzu-emu/yuzu#4326]
whatever i do it doesn't work i have tested every setting but still no sound in the game unless i make multicore out only then i have 10-15fps in the game

I made a video so that you can understand exactly what I mean
i have really tried a lot
and yuzu EA is same problem
https://www.youtube.com/watch?v=O8DF67wu8Bk&feature=youtu.b

**Comment by BSoDGamingYT** [comment]
This is not what github issues are for. Please use the discord server for support
