### ISSUE TITLE
Save File Corrupted

### ISSUE THREAD

**Issue by Syaoran96** [yuzu-emu/yuzu#4336]
I'm having headache about this problem. 
First, I play PKMLG normally and save in game
Then I close it. Open PkHex to edit stats and shiny and some items
Replace the save file with the one I edited.
Open the game and can still play it normally... for a while
I still can save in game tho but there is a chance that when I save, yuzu crashes. And when I open the game again, it says my save file is corrupted and needs to be deleted
I replace the corrupted one with backup one. But it still happens. Crash and save file corrupted.
What should I do now?

**Comment by FearlessTobi** [comment]
We don't give support for edited save files.
It is very well possible that a corruption by Pkhex might be causing your game crashes and other issues.
