### ISSUE TITLE
Rune Factory 4 Special Graphical issue

### ISSUE THREAD

**Issue by Alyn3103** [yuzu-emu/yuzu#4339]
Hey,as i last checked in the compatibility page,rune factory 4 special was showing no boot status
but i tried starting the game and it worked except it had some massive graphical issue 
there no problem in performance as i was getting  60 fps in the starting section
my specs are ---i3 2120 and gt 710 ----as low as they can get
here the pic of graphical bug
![1](https://user-images.githubusercontent.com/54231190/87451714-e36acd00-c61d-11ea-972a-3bd7c6357e74.png)
![2](https://user-images.githubusercontent.com/54231190/87451781-f9788d80-c61d-11ea-807d-9420545c54db.png)
![Annotation 2020-07-14 220700](https://user-images.githubusercontent.com/54231190/87452106-70158b00-c61e-11ea-8e4f-0ee1da35da1c.jpg)

i was using yuzu 308 

edit- i just  tried opening the game again and i got another weird bug
the game only get to the menu screen if i press any action key {plus,a,b,x,y} during when the logo such as marvelous are showing 
if i didnt press anything..it  get to a whitescreen and  fps goes from 60 fps to 0 fps and it stops responding
also if i reach menu and stop using the controller..the menu too stop responding like this
here the log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4920152/yuzu_log.txt)

**Comment by CSX142857** [comment]
Can confirm that all these issues are still happening ,including the whitescreen freeze, on Yuzu Early Access 757 build.
Audio seems to be fine however. 

My specs are : RTX2080ti and intel i9-9900k.

I reported the game compatibility as Bad through the Yuzu "Report Compatibility" button since technically you can go beyond the start menu without it crashing.

**Comment by YukiSakuma** [comment]
Recently, I tested Yuzu again so it updated, and it is now able to play the animation like the opening or the character introduction animation unlike before it makes the game hang (you can't proceed beyond Clorica's introduction), so you can now progress but the graphic glitch is still there though
