### ISSUE TITLE
Yuzu freezes when opening game with vulkan

### ISSUE THREAD

**Issue by chenxi050402** [yuzu-emu/yuzu#4349]
[ 210.609326] Render.Vulkan <Critical> video_core\renderer_vulkan\renderer_vulkan.cpp:DebugCallback:62: terminator_CreateDevice: Failed in ICD C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5a8b943d6aee4596\.\nvoglv64.dll vkCreateDevicecall
[ 210.609328] Render.Vulkan <Critical> video_core\renderer_vulkan\renderer_vulkan.cpp:DebugCallback:62: vkCreateDevice:  Failed to create device chain.
[ 210.609330] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:DebugCallback:66: Unloading layer library C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5a8b943d6aee4596\.\nvoglv64.dll
[ 210.609333] Render.Vulkan <Error> video_core\renderer_vulkan\vk_device.cpp:Create:344: Failed to create logical device
[ 210.612552] Core <Critical> core\core.cpp:Load:216: Failed to initialize system (Error 5)!

Didn't even show booting screen

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4929963/yuzu_log.txt)

**Comment by RokkumanX** [comment]
For starters, stop pirating the bloody game.
Luigis Mansion 3[0100DCA0064A6800][v1.2.1][v196608] **Switch-xci.com**.nsp

**Comment by chenxi050402** [comment]
> For starters, stop pirating the bloody game.
> Luigis Mansion 3[0100DCA0064A6800][v1.2.1][v196608] **Switch-xci.com**.nsp

![20200716161723](https://user-images.githubusercontent.com/62318879/87645341-ea115580-c77f-11ea-969d-1773f437beee.jpg)
Fine.

**Comment by RokkumanX** [comment]
It must feel better supporting the companies that brings you all these games, you did the right thing!

As for your problem it ain't your specs, that's for sure since it's more than enough.
Does the game work with OpenGL?

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
You're better off asking for Vulkan support on our Discord.
If this turns out to be an issue in yuzu that can be fixed by us, we can reopen it.
