### ISSUE TITLE
GC Adapter randomly stops working

### ISSUE THREAD

**Issue by iDekuNut** [yuzu-emu/yuzu#4351]
I am using the newest early access and whenever I try to use my gamecube controller in any game it will work for a minute or two and then randomly the emulator will just stop accepting inputs from it in game and in the yuzu menus until I close and reopen the emulator, I have tested other controllers and none have this issue just the gamecube controller

**Comment by VolcaEM** [comment]
Try testing to see if https://github.com/yuzu-emu/yuzu/pull/4261 fixes your issue

**Comment by iDekuNut** [comment]
Sorry I'm a pretty new to using github, what should I do with that?

**Comment by ameerj** [comment]
Sounds like the adapter disconnects from the usb port. Can you post a log of when this issue happens?

**Comment by iDekuNut** [comment]
So after realizing that if your adapter disconnects it doesn't rescan for it what you said makes sense, so I disconnected my adapter and put it into the usb 2.0 instead of 3.0 and it appears to have fixed It but it has worked for a while and then stopped before so Im reluctant to close the issue yet.

**Comment by iDekuNut** [comment]
Yup you were right, the it was the usb was disconnecting from the port, thanks for the idea to check that, it probably should have been the first thing I checked...

**Comment by ameerj** [comment]
Thanks for confirming the cause of the issue! As of now hotplug isn't implemented. But it is a feature I'd like to try to implement when I have the time.
