### ISSUE TITLE
PR #4346 breaks linux build

### ISSUE THREAD

**Issue by Gustav0ar** [yuzu-emu/yuzu#4354]
This is mainly for devs to track this issue.

I merged #4346 from main repo to mainline repo in my local machine and it causes issue with linux build.
I'm on PopOS 20.04 based on Ubuntu 20.04.
I tried with GCC/G++ 9.3 and 10.0.1, with both same error occurs
Reverting that PR solves the issue.

Here are the logs:

https://pastebin.com/WmyrBiL2

**Comment by VolcaEM** [comment]
I think the relevant part is:

../src/core/hle/kernel/thread.cpp:228:29:   required from here
/usr/include/c++/9/array:110:56: error: ‘std::array<_Tp, _Nm>::_M_elems’ has incomplete type
  110 |       typename _AT_Type::_Type                         _M_elems;
      |                                                        ^~~~~~~~

**Comment by Gustav0ar** [comment]
Fixed in #4356
