### ISSUE TITLE
EA 781 async shader building gone

### ISSUE THREAD

**Issue by Kryptuq** [yuzu-emu/yuzu#4375]
async shader building is gone on newest EA

![image](https://user-images.githubusercontent.com/68452851/87842711-c39e0800-c8ae-11ea-893e-9ccb9c01ef3f.png)

**Comment by EliEron** [comment]
The Async shader PR was untagged 6 hours ago. According to [this](https://github.com/yuzu-emu/yuzu/pull/4273#issuecomment-660343865) comment on the PR it was causing build issues. Discussion about Async shaders should ideally be kept in that PR, and not in a separate issue like this.
