### ISSUE TITLE
MSVS 2017 15.7.1 - fail to compile

### ISSUE THREAD

**Issue by mailwl** [yuzu-emu/yuzu#438]
103 errors, mostly C2894 and similar about linkage templates in C
15.7.0 - still ok
don't update VS

**Comment by legoj15** [comment]
only yuzu-cmd doesn't compile for me, gui yuzu still compiles

**Comment by greggameplayer** [comment]
It happen too on appveyor with msvc compilation it might be due to the boost dependency version because it said in the console that we have to update boost dependency.

**Comment by greggameplayer** [comment]
and there is also a lot of C Linkage error

**Comment by Hexagon12** [comment]
This issue is fixed now with #464 and the release of VS 15.7.2.

Requesting to close.
