### ISSUE TITLE
Zelda Breath of the Wild locks up when entering first tower cut-scene

### ISSUE THREAD

**Issue by jhol** [yuzu-emu/yuzu#4386]
- Version: `mainline-0-321`
- System
  - Debian Testing
  - GeForce GTX 1650

# Steps to reproduce
1. Start a new game
2. Head out of the shrine, down the hill to the first way-point on the Sheika slate
3. Activate the tower - a cut-scene begins, rumbling effects. The screen fades to black. The game gets stuck here.

**Comment by FearlessTobi** [comment]
This issue report is missing a log file.

**Comment by jhol** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4959824/yuzu_log.txt)

Something to do with `SetAndWaitOld` ?

**Comment by jhol** [comment]
Doesn't lock up any more, but the cutscene video is not played - just the audo

**Comment by danielsanfr** [comment]
I am having the same error: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12753085/yuzu_log.txt)
