### ISSUE TITLE
Zelda Breath of the Wild Ground and Water Lighting are messed up in Vulkan renderer

### ISSUE THREAD

**Issue by jhol** [yuzu-emu/yuzu#4387]
- Version: `mainline-0-321`
- System
    - Debian Testing
    - nVidia GeForce GTX 1650

The ground is dark green, and the water is glowing white:
![botw-vulkan](https://user-images.githubusercontent.com/1449493/87986912-b020b600-cad5-11ea-87b1-f4634072d175.jpg)

The OpenGL renderer seems to do a better job:
![botw-opengl](https://user-images.githubusercontent.com/1449493/87986922-b3b43d00-cad5-11ea-86b2-4def44ae4a80.jpg)

**Comment by FearlessTobi** [comment]
This issue report is missing a log file.

**Comment by jhol** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4959837/yuzu_log.txt)

**Comment by MysticExile** [comment]
Does this still happen on the latest driver and yuzu version?

**Comment by jhol** [comment]
Just retested on `mainline-0-422` with NVidia 450.66. Still a problem.

![20201027-yuzu-zelda-vulkan-screenshot-broken-water](https://user-images.githubusercontent.com/1449493/97456027-5d566600-1930-11eb-8471-15b3855e671b.jpg)
