### ISSUE TITLE
Luigu's Mansion 3 : Slowdowns and glitches

### ISSUE THREAD

**Issue by rsilverside** [yuzu-emu/yuzu#4395]
Fps in not stable at 60fps on any hardware.
At 30 fps is ok but still slowdowns. 
Graphical glitches.
Two player coop slows down the game.
New update 1.4 makes the game stay in infinite loading screen.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
