### ISSUE TITLE
Vulkan error - Hatsune Miku: Project DIVA Mega Mix (初音ミク Project DIVA MEGA39's)

### ISSUE THREAD

**Issue by pcardosoprog** [yuzu-emu/yuzu#4398]
This is the last log from de CMD of yuzu when launching any version of hatsune miku on vulkan!

![image](https://user-images.githubusercontent.com/68587189/88031429-7cc14400-cb34-11ea-9a80-d2c77c25a539.png)

**Comment by pcardosoprog** [comment]
maxwell_3d? even if my GPU is Pascal?

**Comment by pcardosoprog** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4952312/yuzu_log.txt)

**Comment by slashiee** [comment]
Duplicate of #3717
