### ISSUE TITLE
Pokemon sword/shield 1.2.1 wifi problem

### ISSUE THREAD

**Issue by Alwayshelping** [yuzu-emu/yuzu#4402]
So when i try to press Y it enters the online screen then leaves fast i dont know if my internet is the problem or the mod.
Please send any problem if you are also having problems with this or if you have a fix for this.

**Comment by ToxaGaming** [comment]
this is what the mod does to prevent the emulator from crashing when trying to connect online. It does not make the game able to connect online if that was what you thought it did. I'd also like to note that this is an issue tracker for developers and that general questions should be asked in either the official forum or the yuzu discord server.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
