### ISSUE TITLE
Zelda: Breath of the Wild -- OpenGL crash building shaders

### ISSUE THREAD

**Issue by behunin** [yuzu-emu/yuzu#4403]
This is my first dive into this code base and I would like to be helpful in debugging this problem and any other that arise for this game.

What might cause TrackGlobalMemory to fail the base_address != nullptr assert?

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4957387/yuzu_log.txt)
[yuzu_log1.txt](https://github.com/yuzu-emu/yuzu/files/4975023/yuzu_log1.txt) -- Used continue while in debug

**Comment by ShyCode-analyst** [comment]
HI ! do u try run with vulkan ? you have amd, right ? maybe be better...
OpenGL is better on Intel/Nvidia.
