### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by YACO99** [yuzu-emu/yuzu#4404]
Error CTR:NF MULTICORE "ON"
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4957408/yuzu_log.txt)

Error CTR:NF MULTICORE "OFF"
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4957426/yuzu_log.txt)

i5 4 gen
8 GB ram + 4 c: +4 d:
GPU RTX 2070

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord or our forums for support requests.
