### ISSUE TITLE
#4373 Breaks Clang Build

### ISSUE THREAD

**Issue by RealJohnGalt** [yuzu-emu/yuzu#4406]
Error:
```
/home/redacted/source/yuzu-linux-downloader/yuzu-windows-msvc-source-20200721-86423219f/src/./common/alignment.h:72:9: error: no matching function for call to 'operator delete'
        ::operator delete (p, n * sizeof(T), std::align_val_t{Align});
        ^~~~~~~~~~
```

I believe it must be defined in source simply using malloc for clang builds as part of this change.

Edit: I found #4306 also breaks clang builds, due to no matching member function for emplace on L449 and L539.

**Comment by german77** [comment]
Solved on current master
