### ISSUE TITLE
Implement 214 Texture Format (Known as sRGB format) [Request]

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#441]
## Hardware Specs :
Nvidia GeForce GTX 960
Intel I7-7700k @ 4.5Ghz
8 GB Of Ram
Windows 10 Pro

## The issue :
When you launch 1.2.Switch both in single core and in multi-cores the game crash with the `unimplemented format=214` error and `Assertion Failed ! Unreachable code !` error.
 
## Part of the log i'm able to give :
[Part of the log in single core](https://gist.github.com/greggameplayer/ac1c8f601329b7be03094bd64daacf25)

[Part of the log in multi-cores](https://gist.github.com/greggameplayer/e94129fa3bf6afd698088769f0b69733)

**Comment by Subv** [comment]
Note: That is the sRGB format

**Comment by greggameplayer** [comment]
@Subv so i rename the title of this issue ?

**Comment by Hexagon12** [comment]
Both of these formats are needed by ARMS and Splatoon 2.

**Comment by greggameplayer** [comment]
@Hexagon12 ok so it might be usefull to implement it.

**Comment by greggameplayer** [comment]
Resolved by #476 Thanks to @Subv

**Comment by Subv** [comment]
No it was not
