### ISSUE TITLE
Black screen after loading shader and launching 

### ISSUE THREAD

**Issue by fireball025** [yuzu-emu/yuzu#4412]
i need to end the game because my game does not shows up when i open it . It shows loading shader 8/8 then the launching screen appears after that a black screen appears NO SOUND NO VIDEO nothing shows up. I have tried using savefile but the outcome are same.
PLZ HELP ASAP

GAME: POKEMON LET'S GO PIKACHU
INTEL(R) HD GRAPHICS 620
SHAER VERSION: 5.1
OPENGL VERSION: 4.5
RAM: 4 GB
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4974031/yuzu_log.txt)

**Comment by ShyCode-analyst** [comment]
hi, you try run with MultiCore ?

**Comment by fireball025** [comment]
I tried but my pc hangs and a black screen appears so I have to force
restart it.... Thank you for your efforts

**Comment by benderscruffy** [comment]
can be closed
this is fixed
