### ISSUE TITLE
Source shipped with releases does not supply submodule code.

### ISSUE THREAD

**Issue by Alex-Aralis** [yuzu-emu/yuzu#4413]
Dist URLs provided with releases do not contain submodule code.  

example URL. https://github.com/yuzu-emu/yuzu-mainline/archive/mainline-0-325.tar.gz

**Comment by Alex-Aralis** [comment]
Also the folder inside the archive is named `yuzu-mainline-mainline-${version}`. which I don't expect was intened.

**Comment by Morph1984** [comment]
Source code provided by github does not include any submodules for space saving reasons.
Furthermore, we provide our own copy of the source which includes the submodule code: [yuzu-windows-msvc-source-20200725-8c82b5ba3.tar.xz](https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-326/yuzu-windows-msvc-source-20200725-8c82b5ba3.tar.xz)
