### ISSUE TITLE
callers of NVFlinger::Lock() do not hold onto the unique_lock

### ISSUE THREAD

**Issue by comex** [yuzu-emu/yuzu#4424]
`NVFlinger::Lock` returns a `unique_lock`, a lock guard which will automatically unlock the mutex when it is destroyed.

Each its three callers (two in vi.cpp and one in nvflinger.cpp) simply calls `Lock();`, discarding the return value.  This causes the mutex to be locked and then immediately unlocked.  I am pretty sure this is not intended.

Instead, they should probably do something like `auto guard = Lock();`, in order to hold onto the mutex for the rest of the scope.

**Comment by lioncash** [comment]
Resolved in #4426. Thanks for the report!
