### ISSUE TITLE
configuration dialog has two different "Dump Decompressed NSOs" checkboxes; only one works

### ISSUE THREAD

**Issue by comex** [yuzu-emu/yuzu#4427]
This also applies to "Dump ExeFS".

One set of checkboxes is in General -> Debug:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/47517/88467925-4b78a900-ce91-11ea-8488-cbb5ed35d6b4.png">

The other set is in System -> Filesystem -> Patch Manager:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/47517/88467932-6e0ac200-ce91-11ea-848e-e9db4e44e74b.png">

But only the second set of checkboxes is actually hooked up to anything.  The first set always starts unchecked each time you open the configuration dialog, and checking the boxes and pressing OK does nothing.  Indeed, `configure_debug.cpp` does not mention the names of these controls at all (`dump_decompressed_nso` and `dump_exefs`).

Reproduced on a2e1810287b8b7ffead994dcb17e8e0ba6bc0914.

**Comment by FearlessTobi** [comment]
Those were introduced in https://github.com/yuzu-emu/yuzu/commit/f92cbc55018b5a3d98dd2093354f20c62ace5fda#diff-ddadd129e7513e22a5a0b64323184275 for some reason.
I'll PR a fix soon.

**Comment by lioncash** [comment]
Fixed in #4429. Thanks for the report!
