### ISSUE TITLE
"Mapped memory page without a pointer" still happens

### ISSUE THREAD

**Issue by comex** [yuzu-emu/yuzu#4428]
Yuzu revision: a2e1810287b8b7ffead994dcb17e8e0ba6bc0914 (master as of now)
Game: Super Mario Maker 2 (3.0.0)
OS: Linux
CPU: Threadripper 3970X (lots of cores, good for triggering race conditions)
Settings: Multicore on, asynchronous GPU on, Vulkan

Not long after starting the game, it sometimes crashes with this error.  It's somewhat hard to reproduce.
```
[  83.364561] Debug <Critical> core/memory.cpp:operator():647: Assertion Failed!
Mapped memory page without a pointer @ 00000020948E5530
```
#4245 was supposed to fix this, but apparently wasn't enough.  That PR message did warn:

> Please not however that this is not a guaranteed fix because the compiler may reorder this operation during optimization.

However, I checked the two things it patched and neither of them were reordered, so the issue has to be somewhere else.  (Still, it would be better to use atomics properly so there isn't any possibility of reordering.)

For the record, this is the state of the page table after the crash:
```
(gdb) p current_page_table->pointers.base_ptr[0x00000020948E5530 >> PAGE_BITS]
$28 = (unsigned char *) 0x7fde84400000 <error: Cannot access memory at address 0x7fde84400000>
(gdb) p current_page_table->attributes.base_ptr[0x00000020948E5530 >> PAGE_BITS]
$30 = Common::PageType::Memory
```

The assertion failure can only occur if the `pointers` entry is 0, so it seems that it was updated after the crashing thread read from it.

**Comment by liamwhite** [comment]
Comment with a new yuzu log if this is still relevant
