### ISSUE TITLE
Changing system language to Chinese wont boot any game

### ISSUE THREAD

**Issue by tsunamilx** [yuzu-emu/yuzu#4433]
Hi, the game is running fine with English as system language, as well as other languages except Chinese, the boot screen is infinitely loading. 

Is it because Chinese as system language is not supported yet or do I need to install some kind of font files? Please advise, thanks.

Yuzu version: ALL
OS: Windows

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4979837/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
I'm able to boot games just fine when Chinese is selected as the language.
Most probably, you're missing the shared fonts for Chinese which can be dumped with the yuzu Quickstart guide.
If the problem persists after dumping your files, you can ask for support on our Discord server.
