### ISSUE TITLE
Mismatched UI bottom bar's values when using midnight blue and midnight blue colorful qt-themes

### ISSUE THREAD

**Issue by Zeroksas** [yuzu-emu/yuzu#4435]
Bugs:
1. Selecting Vulkan API changes background color to darker "disabled" - color should be light "enabled" for both vulkan and opengl.
2. ASYNC, MULTICORE and DOCK values are mismatched: enabling them on bottom bar UI disable them in settings.

**Comment by ToxaGaming** [comment]
regarding your second bug it's working fine for me according to this image where Left = Enabled and Right = Disabled
![image](https://user-images.githubusercontent.com/41490344/88552044-e30e0100-d023-11ea-87a8-295124de2c7e.png)
about the first bug you're mentioning, that can maybe be fixed

**Comment by Zeroksas** [comment]
Still wrong here: in setting bar Multicore is enabled but Multicore on botton bar is not highlited.
![image](https://user-images.githubusercontent.com/44953731/88552615-354b2400-d01c-11ea-8c35-6de8c435d9a3.png)

**Comment by Zeroksas** [comment]
> regarding your second bug it's working fine for me according to this image where Left = Enabled and Right = Disabled
> ![image](https://user-images.githubusercontent.com/41490344/88552044-e30e0100-d023-11ea-87a8-295124de2c7e.png)
> about the first bug you're mentioning, that can maybe be fixed

So you are saying if background is highlighted that means "disabled"?

**Comment by ToxaGaming** [comment]
yes

**Comment by ToxaGaming** [comment]
> So you are saying if background is highlighted that means "disabled" not "enabled"?

yes

**Comment by Zeroksas** [comment]
> > So you are saying if background is highlighted that means "disabled" not "enabled"?
> 
> yes

Then all I can say this theme is quite confusing because for example in this screenshot settings which are "enabled" like "Debug Controller" and "Touchscreen" have same background and letters colors as in this topic while "disabled" Mouse has darker background color while letters are also darker.
![image](https://user-images.githubusercontent.com/44953731/88557462-236c7f80-d022-11ea-8290-25a1a58ff77b.png)
