### ISSUE TITLE
Crash when trying to open menu

### ISSUE THREAD

**Issue by godpow** [yuzu-emu/yuzu#4436]
I was playing pokemon sword and I just caught a pokemon then when I tried to open the menu to save it gives me this error. 
![Annotation 2020-07-27 125009](https://user-images.githubusercontent.com/17231911/88568952-98be5d00-cfee-11ea-8685-66578798d893.png)

**Comment by BSoDGamingYT** [comment]
You pressed Y, this attempted to connect to the internet. Dont press Y
