### ISSUE TITLE
Dark Souls: Remastered (wont boot async enabled)

### ISSUE THREAD

**Issue by theboy181** [yuzu-emu/yuzu#4441]
Dark Souls started booting in EA 815 - However you it will freeze if async is on.
Windows 10 

No yuzu log, as the issue can be reproduced by loading the game with async.

**Comment by theboy181** [comment]
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4985787/yuzu_log.zip)

**Comment by KaitoCodado** [comment]
with screen sync off, does the problem persist?

[  16.688386] Config <Info> core\settings.cpp:operator ():98: Renderer_UseFrameLimit: true
[  16.688386] Config <Info> core\settings.cpp:operator ():98: Renderer_FrameLimit: 100

I noticed here that you are using with limits.

**Comment by KaitoCodado** [comment]
with screen sync off, does the problem persist?

[16.688386] Configure core \ settings.cpp: operator (): 98: Renderer_UseFrameLimit: true
[16.688386] Configure core \ settings.cpp: operator (): 98: Renderer_FrameLimit: 100

I noticed here that you are using with limits.

**Comment by KaitoCodado** [comment]
"[  16.688387] Config <Info> core\settings.cpp:operator ():98: Renderer_GPUAccuracyLevel: 1" can u have to change it to better ?

**Comment by KaitoCodado** [comment]
i just a analist. please if i have a solition, pls tell me, (right here) I got interested. and I will be happy to know the solution, for now I know some things that can help from what I saw in your LOG, but I'm not sure if the alternatives I have in mind will solve the case.
