### ISSUE TITLE
MHGU Vulkan issues

### ISSUE THREAD

**Issue by Ktuky** [yuzu-emu/yuzu#4447]
When using Vulkan with Monster Hunter Generations Ultimate a lot of the foliage(some other things as well looks like static images?) is not rendering properly.
R5 2600
Vega 64
On opengl some areas don't render properly but this problem is fixed.
![yyyy](https://user-images.githubusercontent.com/68561207/88690542-10c67900-d0fc-11ea-9a0b-400554c99f19.PNG)
![ysds](https://user-images.githubusercontent.com/68561207/88690561-13c16980-d0fc-11ea-940f-51458ce19f4c.PNG)

**Comment by FearlessTobi** [comment]
Could you please provide a log file?

**Comment by Ktuky** [comment]
> 
> 
> Could you please provide a log file?

I hope I did it right, launched the game got to the broken stuff and exited emulator.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5010262/yuzu_log.txt)

**Comment by Desmondchaser27** [comment]
This issue was resolved in the release Yuzu Early Access 1126

They fixed alpha culling (transparency maps) in that update.  This game can now be played on Vulkan with no graphical issues, that I've seen.

**Comment by Desmondchaser27** [comment]
Here is an example of the same area.
![MHGUVulkan](https://user-images.githubusercontent.com/6407087/99691879-aee9a080-2a57-11eb-86eb-969134990168.png)
