### ISSUE TITLE
The game screen of Dragon Quest I&II&III can not be displayed normally... Just black screen...

### ISSUE THREAD

**Issue by qiuyang1008** [yuzu-emu/yuzu#4449]
The game screen of Dragon Quest I&II&III can not be displayed normally in EA 570-818.
Black screen all the time but you can hear the game sounds.
However it can be correctly displayed in EA early version like EA400+ and 500+.
I hope this problem could be fixed in future releases. 
Thanks very much. : )

**Comment by FearlessTobi** [comment]
Could you please provide a log file?

**Comment by qiuyang1008** [comment]
> Could you please provide a log file?
Sure, I am glad to upload the log files. Here's the download links.  : )
https://drive.google.com/file/d/16D9N0Cvc5mxgRbe1UNcKyB2U1cNDB05O
Pass: Yuzu_EA824_DQ1-3_Logs

**Comment by Vegeta780** [comment]
> @FearlessTobi
> Sure, I am glad to upload the log files of DQ1-3.
> Here's the download links of the three logs. : )
> https://drive.google.com/file/d/16D9N0Cvc5mxgRbe1UNcKyB2U1cNDB05O
> Pass: Yuzu_EA824_DQ1-3_Logs
> 
> DQ1: Wait for a long time and hear the opening music but black screen all the time.
> DQ2: Black screen and no music all the time...
> DQ3: Can hear the opening music but black screen all the time.
> 
> PS: DQ1-2 Can be played correctly in early EA 400+ version.
which version is playable all three games Dragon quest  ? am searching 

05/24/2020 | lori19981 on 05/25/2020 | Intel(R) Core(TM) i5-3470 CPU @ 3.20GHzGeForce GT 740/PCIe/SSE2Windows | Mainline Build39bc457 | Great
-- | -- | -- | -- | --

but could found it

 i have a issue with black screen

**Comment by Vegeta780** [comment]
look at this i can play all of them with  Yuzu Early Access 823 - Sin  {{Just change Vulkan to OPENGL}}
![Screenshot (3)](https://user-images.githubusercontent.com/31349213/89582734-919b1880-d852-11ea-8bdb-5e4f8c4b39aa.png)

**Comment by qiuyang1008** [comment]
@Vegeta780 
Great, you are right. 
You may play the games DQ1-3 stably in some EA Yuzu version and there're just some unnormal green lines.

**Comment by Zealut** [comment]
> You may play the games DQ1-3 stably in some EA Yuzu version and there're just some unnormal green lines.

It runs well aside from minor graphical glitches (like colored lines under text) on most versions, even mainline as long as you disable "Use assembly shaders" in the Adv. Graphics section.

1 and 2 seem to be pretty much fully playable, 3 has some other rendering bugs that make it hard to progress in certain sections.

**Comment by FearlessTobi** [comment]
So is the original issue fixed now?

**Comment by Zealut** [comment]
Depends on what you consider fixed. The games work on every version I tested as long as you disable the assembly shaders setting. So the original black screen issue wasn't really an issue to begin with, but having to disable assembly shaders for these games is still a persistent issue.

**Comment by FearlessTobi** [comment]
Thanks for the info, I think the remaining issues can be better tracked here: https://github.com/yuzu-emu/yuzu/issues/4073.
