### ISSUE TITLE
Update Disable DOF & CameraFix for AnimalCrossing 1.4

### ISSUE THREAD

**Issue by hidethepainharold** [yuzu-emu/yuzu#4459]
Please update Disable DOF & CameraFix for AnimalCrossing 1.4

**Comment by ExsertWizard** [comment]
This is an issue tracker for developers addressing problems regarding yuzu's code or functionality. We're not in charge of keeping mods up to date, that depends on the creator of the mods.

You can however join our Discord server and ask for modders for an update in the appropriate channel.
