### ISSUE TITLE
Implement some audio modules [request]

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#446]
I have seen that there aren't  these audio modules implement : 
- audout:a
- audin:a
- audrec:a
- audren:a
- audin:d
- audout:d
- audrec:d
- audren:d
- audctl
- hwopus

And i think we should implement it in order to have the audio properly work.

**Comment by Hexagon12** [comment]
All of those are completely unnecessary for games to produce audio (except hwopus, but that one hasn't been seen used in games).

Please do more research before making issues / requests like these. Like we said before, we don't need requests, since the devs already know of these issues.

**Comment by greggameplayer** [comment]
ok so i close it
