### ISSUE TITLE
Fire Emblem Three Houses Crash before battle

### ISSUE THREAD

**Issue by Razucky** [yuzu-emu/yuzu#4460]
Game crashes on loading screen on second battle. Tried disabling assembly shaders.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5012537/yuzu_log.txt)

**Comment by NielsGx** [comment]
This is for devs, ask for support in the discord server
(No fix available for the random crashes in Yuzu when playing feth)

**Comment by ShyCode-analyst** [comment]
many Debug <Critical> error.
You try run without OpenGL ?

**Comment by ShyCode-analyst** [comment]
i think it is API error maybe OpenGL. Do you try run with Vunkan ?

**Comment by FearlessTobi** [comment]
Probably a duplicate of https://github.com/yuzu-emu/yuzu/issues/4038.
Please add your log as a comment on the original issue.
