### ISSUE TITLE
Yuzu does not respond

### ISSUE THREAD

**Issue by ShyCode-analyst** [yuzu-emu/yuzu#4462]
[yuzu_installer.log](https://github.com/yuzu-emu/yuzu/files/5012764/yuzu_installer.log)

**Comment by SebastianLukman** [comment]
That is the installation log.

**Comment by SebastianLukman** [comment]
That is the installation log. Try looking for yuzu_log.txt

**Comment by ShyCode-analyst** [comment]
i solved, its a key problem.

tks.
