### ISSUE TITLE
Skully doesnt boot

### ISSUE THREAD

**Issue by PacoAvelar** [yuzu-emu/yuzu#4487]
Game starts, screen goes black then it crashes and yuzu closes
GPU usage spikes to 100%
RAM usage start to allocate memory at a high rate until it crashes (without reaching the max memory available)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5024173/yuzu_log.txt)

![image](https://user-images.githubusercontent.com/29181120/89337708-01e24800-d661-11ea-9426-3126975b580c.png)

**Comment by ShyCode-analyst** [comment]
hi!, do you try run with vulkan Api ?

**Comment by ShyCode-analyst** [comment]
hi, you try run with vulkan api mode ?

**Comment by ShyCode-analyst** [comment]
its hapen with any game or a single game ?
You uptade the firmware ?
I see on your log many errors... I recomend (if you want) try another version of Yuzu, Im use firmware (Firmware 10.0.4) and version Yuzu: 845 or 852.
 If the problem persist past in here a new log of the new version yuzu.

**Comment by PacoAvelar** [comment]
Game now boots to menu and in-game, even that it doesnt render while in-game
