### ISSUE TITLE
Corrupted camera images in BOTW

### ISSUE THREAD

**Issue by EmK530** [yuzu-emu/yuzu#4499]
How I made this occur: Obtain the Camera rune on the Sheikah Slate then simply take a picture and save it.
If you then look at it in album then you will see that the image you saved got corrupted.

Played on yuzu Release 337

Screenshot of Yuzu:
![corruptedimage_2](https://user-images.githubusercontent.com/50961259/89580659-fd22bd00-d835-11ea-9f02-ef6c89d054a2.PNG)

Nintendo Switch & Yuzu comparison image:
![corruptedimage_comparison](https://user-images.githubusercontent.com/50961259/89582659-4aecf480-d839-11ea-990b-9c41cc75e2e7.jpg)

If you need any clearer images, ask anytime!

EDIT:
Didn't feel a log file was necessary, but now I do. So here:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5038002/yuzu_log.txt)
(4MB hope that's not too much)

**Comment by MysticExile** [comment]
This issue has been fixed, if you think this issue still applies please open a new issue with a new log.
