### ISSUE TITLE
Yuzu fails to build

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#4500]
As of commit 1cc0e4b4d81af64217cb488375af97dfbc8f984f, Yuzu fails to build.  Compile log excerpt:

```
[1097/1594] Building CXX object src/core/CMakeFiles/core.dir/arm/dynarmic/arm_dynarmic_64.cpp.o
FAILED: src/core/CMakeFiles/core.dir/arm/dynarmic/arm_dynarmic_64.cpp.o 
/usr/bin/c++  -DARCHITECTURE_x86_64=1 -DBOOST_ALL_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DCPPHTTPLIB_OPENSSL_SUPPORT -DENABLE_WEB_SERVICE -DNDEBUG -DOPUS_VERSION="\"\\\"1.3.1\\\"\"" -DYUZU_ENABLE_BOXCAT -D_FILE_OFFSET_BITS=64 -I/home/darren/.conan/data/catch2/2.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I../src/. -I../externals/./microprofile -I../externals/./mbedtls/include -I../externals/opus/opus/include -I../externals/unicorn/include -I../externals/./httplib -I../externals/./libressl/include -I../externals/dynarmic/src/../include -isystem /home/darren/.conan/data/fmt/7.0.1/_/_/package/b911f48570f9bb2902d9e83b2b9ebf9d376c8c56/include -isystem /home/darren/.conan/data/nlohmann_json/3.7.3/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -isystem /usr/local/include/SDL2 -O3 -DNDEBUG    -Wall -Werror=implicit-fallthrough -Werror=missing-declarations -Werror=reorder -Wextra -Wmissing-declarations -Wno-attributes -Wno-unused-parameter -mcx16 -std=gnu++17 -MD -MT src/core/CMakeFiles/core.dir/arm/dynarmic/arm_dynarmic_64.cpp.o -MF src/core/CMakeFiles/core.dir/arm/dynarmic/arm_dynarmic_64.cpp.o.d -o src/core/CMakeFiles/core.dir/arm/dynarmic/arm_dynarmic_64.cpp.o -c ../src/core/arm/dynarmic/arm_dynarmic_64.cpp
../src/core/arm/dynarmic/arm_dynarmic_64.cpp: In member function ‘std::shared_ptr<Dynarmic::A64::Jit> Core::ARM_Dynarmic_64::MakeJit(Common::PageTable&, std::size_t) const’:
../src/core/arm/dynarmic/arm_dynarmic_64.cpp:196:16: error: ‘struct Dynarmic::A64::UserConfig’ has no member named ‘enable_optimizations’; did you mean ‘unsafe_optimizations’?
  196 |         config.enable_optimizations = false;
      |                ^~~~~~~~~~~~~~~~~~~~
      |                unsafe_optimizations
../src/core/arm/dynarmic/arm_dynarmic_64.cpp:197:16: error: ‘struct Dynarmic::A64::UserConfig’ has no member named ‘enable_fast_dispatch’
  197 |         config.enable_fast_dispatch = false;
      |                ^~~~~~~~~~~~~~~~~~~~

```

Attempted on Linux Mint 20, kernel 5.4, gcc 9.3.0.

**Comment by FearlessTobi** [comment]
It seems like your yuzu source is out of date. 
https://github.com/yuzu-emu/yuzu/blob/master/src/core/arm/dynarmic/arm_dynarmic_64.cpp#L196 is a blank line.
Closing for now as this likely is an issue on your end.

**Comment by Shoegzer** [comment]
@FearlessTobi I was using the latest source but had merged in #4291 as I was trying to help test it (should have mentioned that).  Could that have somehow caused the issue?

**Comment by FearlessTobi** [comment]
That PR doesn't modify the file either. Either way, we don't provide support making custom builds.
I'd suggest you git reset your repo and then try building again.

**Comment by german77** [comment]
Currently they are transitioning from c++ 17 to c++ 20. Probably you grab something mid way through. You can use my master fork and add the changes related to that PR or wait until the transitioning is merged completely.

**Comment by Shoegzer** [comment]
@german77 Thank you, that makes sense.  c++17 is [still recommended](https://github.com/yuzu-emu/yuzu/wiki/Building-For-Linux) so I figured gcc 9.3.0 would work.  I'm aware there are features of c++20 that are only supported by gcc 10 though, so I suppose that will be needed to compile future yuzu builds successfully.

That said however, today's "yuzu-mainline" at commit f5d538f118b4b25237a0d0234a51fcb815ca98d1 compiles without error (though with lots of integer expression-related warnings near the end) and I assume it includes all the updates that my failed "yuzu" build had from yesterday.  Shouldn't that have failed too?

**Comment by german77** [comment]
I don't know. Sometimes when I update to latest  yuzu-master fails to compile with random errors and after some days it's fixed. I have looked to the changes made since then and never saw what solved the problem. I guess I don't have the knowledge to find it.

That's why I have a know copy of yuzu-master that works. And if I can't get yuzu to compile with something strange I always delete everything and start again with that copy. It's a tedious process but at least I know if the error is persistent the problem it's mine.
