### ISSUE TITLE
How do cheat on yuzu?

### ISSUE THREAD

**Issue by rice1234** [yuzu-emu/yuzu#4506]
I want to use cheat with SXOS or Atomosphere on yuzu. not mods.
How do I do for using SXOS or Atomosphere on yuzu?

**Comment by auranticus** [comment]
yuzu doesn't have cheat function yet, so there's no "how-tos" for you

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
