### ISSUE TITLE
Yuzu crash every time after a few minutes playing  memory.cpp:TrackGlobalMemory:476: Assertion Failed

### ISSUE THREAD

**Issue by silverioparreira** [yuzu-emu/yuzu#4517]
yuzu Early Access 859 crash after some minutes later, playing pokemon sword, no mods, 
but it also gives the error in any other game, like SPO!

I'm using it in opengl, multicore, dock and assync!
this is the  log, does anyone know help me?

CPU: RYZEN 2600
GPU: RTX 2060 driver 451.67
MEMORY: 16GB

[ 958.522673] IPC <Warning> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:155: Domain request has no DomainMessageHeader!
[ 958.522709] IPC <Warning> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:155: Domain request has no DomainMessageHeader!
[ 958.522742] IPC <Warning> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:155: Domain request has no DomainMessageHeader!
[ 958.522764] IPC <Warning> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:155: Domain request has no DomainMessageHeader!
[ 958.522784] IPC <Warning> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:155: Domain request has no DomainMessageHeader!
[ 958.522811] IPC <Warning> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:155: Domain request has no DomainMessageHeader!
[ 958.522835] Service <Warning> core\hle\service\sockets\bsd.cpp:RegisterClient:131: (STUBBED) called
[ 958.522855] Service <Warning> core\hle\service\sockets\bsd.cpp:StartMonitoring:140: (STUBBED) called
[ 958.522889] Debug <Critical> core\hle\kernel\svc.cpp:CreateThread:1531: Assertion Failed!
[ 958.540134] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:43: (STUBBED) called
[ 958.540185] IPC <Warning> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:155: Domain request has no DomainMessageHeader!
[ 958.540803] Debug <Critical> core\hle\kernel\svc.cpp:CreateThread:1531: Assertion Failed!
[ 958.541518] Debug <Critical> core\hle\kernel\svc.cpp:CreateThread:1531: Assertion Failed!
[ 958.559431] Debug <Critical> core\hle\kernel\svc.cpp:CreateThread:1531: Assertion Failed!
[ 958.633680] Service.APM <Info> core\hle\service\apm\controller.cpp:SetClockSpeed:84: called, mhz=000003FC
[ 958.656668] Render.OpenGL <Info> video_core\renderer_opengl\gl_shader_cache.cpp:BuildShader:163: VS4494B9375579EF14
[ 958.682942] Render.OpenGL <Info> video_core\renderer_opengl\gl_shader_cache.cpp:BuildShader:163: FSDE68F6952465A821
[ 958.683257] Render.OpenGL <Warning> video_core\renderer_opengl\gl_arb_decompiler.cpp:YNegate:2056: (STUBBED)
[ 958.695628] Render.OpenGL <Info> video_core\renderer_opengl\gl_shader_cache.cpp:BuildShader:163: VS0B524CCF750BB316
[ 958.696287] Render.OpenGL <Info> video_core\renderer_opengl\gl_shader_cache.cpp:BuildShader:163: FS40099F4577D4E860
[ 958.700625] Debug <Critical> video_core\shader\decode\memory.cpp:TrackGlobalMemory:476: Assertion Failed! Global memory tracking failed
[ 958.700647] Debug <Critical> video_core\shader\decode\memory.cpp:TrackGlobalMemory:476: Assertion Failed! Global memory tracking failed
[ 958.700690] Debug <Critical> video_core\shader\decode\memory.cpp:TrackGlobalMemory:476: Assertion Failed! Global memory tracking failed
[ 958.700719] Debug <Critical> video_core\shader\decode\memory.cpp:TrackGlobalMemory:476: Assertion Failed! Global memory tracking failed
[ 958.700787] Debug <Critical> video_core\shader\decode\memory.cpp:TrackGlobalMemory:476: Assertion Failed! Global memory tracking failed
[ 958.700811] Debug <Critical> video_core\shader\decode\memory.cpp:TrackGlobalMemory:476: Assertion Failed! Global memory tracking failed
[ 958.700847] Debug <Critical> video_core\shader\decode\memory.cpp:TrackGlobalMemory:476: Assertion Failed! Global memory tracking failed
[ 958.700996] Debug <Critical> video_core\shader\decode\memory.cpp:TrackGlobalMemory:476: Assertion Failed! Global memory tracking failed

**Comment by ShyCode-analyst** [comment]
Hi, Good Night. Did this error happen with another version ?
You try uptade firmware or open with vulkan api ?
happens to any specific game or to anyone ?

pls if u have a log, past in here complet, maybe others can help you if i can't.

**Comment by silverioparreira** [comment]
hi,  today I am using version 347, and it is giving error too and in any game I play for a while, follow my log! i play without firmware, in vulkan many Stuttering happens!
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5077740/yuzu_log.txt)

**Comment by silverioparreira** [comment]
here is another log, sometimes it seems that each time is a different error !?
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5077754/yuzu_log.txt)

**Comment by ShyCode-analyst** [comment]
hello, you can try to use a more current version, or try to put a firmware, I use Firmware 10.0.4.
the versions I use yuzu: 845 or 852. better than trying to fix global memory errors in c ++ (at least what I saw is this.) not that this is the solution but I am giving my opinion.

**Comment by silverioparreira** [comment]
thanks bro, i will test it and put it here if it solved!

**Comment by silverioparreira** [comment]
in version 876 EA it seems that it solved the problem with the option of "use asynchronous shader building (experimental)"!

**Comment by ShyCode-analyst** [comment]
hmm, well, I'm glad you did. enjoy the emulator :)
