### ISSUE TITLE
yuzu keeps closing during startup

### ISSUE THREAD

**Issue by hiseullie** [yuzu-emu/yuzu#4525]
hello why does yuzu keeps closing when i try to open it? i've installed everything everything required for it to install properly. pls fix this issue. thank you for your hard work!

**Comment by ogniK5377** [comment]
Please attach a log file

**Comment by hiseullie** [comment]
i can't the log file is empty

**Comment by hiseullie** [comment]
![image](https://user-images.githubusercontent.com/69679835/90253577-90c64000-de6b-11ea-8227-fb819f5e90f0.png)
here is a screenshot of the log file

**Comment by hiseullie** [comment]
hello! apparently yuzu keeps closing because i have a usb gamepad plugged into my pc. so when i plugged the gamepad in to play it'll just close but when i didn't have the gamepad it run just fine oh and also i'm using a generic single usb controller i hope you can fix this issue soon. thank you for your hard work as always!

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
