### ISSUE TITLE
Why does GPU temperature go up when launching Yuzu before any game is run?

### ISSUE THREAD

**Issue by Jimmy03** [yuzu-emu/yuzu#4534]
I am using Mainline v339
https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-339

Win 10 1909
i9-9900k
GTX2080

When I launch Yuzu, my GPU temps go way up, like 20+ degrees, this is before I launch any game.
I would expect GPU temps to rise only when a game is selected and run.

Edit: I don't see any GPU load in task manager, but I see the temps go up in hwmonitor. Is this something to do with Windows game mode? I still don't get what's causing the temps to rise if Yuzu is just sitting at the menu screen, no data is being processed, so where are the temps coming from?

**Comment by Zuchter** [comment]
Yuzu is compilling shaders and your 9900K is generating so much heat that it transfers to the GPU

**Comment by Jimmy03** [comment]
> 
> 
> Yuzu is compilling shaders and your 9900K is generating so much heat that it transfers to the GPU

The CPU is liquid cooled, but it might be that the GPU clock speed is increased because windows turns on Game mode or something.

**Comment by ichronox** [comment]
Check CPU/GPU usage + loads when temps rise while using MSI afterburner cna give you some hints about what is happening.

Compiling shaders uses a LOT of cpu power, so in my case, it does happen to transfer SOME heat to the GPU.
