### ISSUE TITLE
Yuzu crashes when click on Configure

### ISSUE THREAD

**Issue by Paulolego28** [yuzu-emu/yuzu#4543]
Hello people,

I have this wierd issue with Yuzu, every SECOND time I click the configure button (after launching Yuzu), the emulator will crash, just like that. To be more clear, everytime I launch Yuzu, everything works fine, the first time I click on configure the emulator opens the tab, and everything fine, but when I click ok or "X" and I close that tab, and re-open it again, the emulator just crashes. I have tried setting my page file to 30gb, but its the same.

GoldenX helped me and asked me to build Yuzu in Visual Studio Community 2019 I think, to see what was causing the problem exactly, but the emulator doesnt crash when I was testing it in VS, so there wasnt any thing I could do, just close it manually and that didnt generate any "error" in the log, so Golden told me he was out of ideas and told me to post my issue here so... Here I am, I would like to get some help with this because its very annoying to change my settings only once everytime I boot Yuzu, anyways thanks!

Note: This also happens with right click on a game and select properties.

**Comment by ShyCode-analyst** [comment]
its a Early acess version or not ?
do you have a log ?

**Comment by Paulolego28** [comment]
> its a Early acess version or not ?
> do you have a log ?

Nope, its mainline, and this error does not generate any line in log.

**Comment by ShyCode-analyst** [comment]
hello, you can try to use a more current version of yuzu, or try to put a firmware, I use Firmware 10.0.4.
the versions I use yuzu: 845 or 852. Not that this is the solution, but I am giving my opinion.

**Comment by Paulolego28** [comment]
I just wanted to say that this is a really wierd error, because I have tried almos everything, it doesnt work and doesnt show why it istn working, I have installed the most recent firmware, reinstalled the keys, reinstalled Yuzu itself, it has happened this to me in every version, since the first version I installed Yuzu (around 100) to the current one, but just nothing.

**Comment by calico-crusade** [comment]
I am getting this issue as well. The application is throwing an error within event viewer, however, the given error is not very useful (to me)
Faulting application name: yuzu.exe, version: 0.0.0.0, time stamp: 0x5f5233bc
Faulting module name: nvoglv64.dll, version: 26.21.14.4614, time stamp: 0x5ebf2a80
Exception code: 0xc0000005
Fault offset: 0x0000000000b4186e
Faulting process id: 0x2060
Faulting application start time: 0x01d682e99ff74bbc
Faulting application path: C:\Users\Cardboard\AppData\Local\yuzu\yuzu-windows-msvc\yuzu.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nvaki.inf_amd64_0f88d2cb68bb2156\nvoglv64.dll
Report Id: fa2132d1-c049-4f6d-9c4e-3c24835ca02e
Faulting package full name: 
Faulting package-relative application ID: 

I've tried on the latest release of the NVidia drivers, I've rolled back to 446.14 (as suggested in the discord). 
So, it's not an outdated driver issue like [this issue](https://github.com/yuzu-emu/yuzu/issues/4000) was closed for. 
A saw a reddit thread pointing to the issue being with multiple GPUs, I have a 1080 TI and a 1050 TI, upon disabling the 1050, I'm still getting the crashing issue.

**Comment by benclau** [comment]
Seems to me that i had to delete all .ini files in the config folder "C:\Users\XXXX\AppData\Roaming\yuzu\config" including qt-config.ini

I had to reconfigure the main config as well as all "per game config" but its not a big deal anyway.

That did the trick for me.

**Comment by acsstudios** [comment]
Delete %appdata%\yuzu\config\qt-config.ini and if you've installed  Bandicam, Action and Screenrec, uninstall them. This worked for me.

**Comment by swhju006** [comment]
I had the same issue and this works for me too. I tried to change settings of input (adding profile), before this happened, so I just deleted input and it worked.

**Comment by german77** [comment]
> I had the same issue and this works for me too. I tried to change settings of input (adding profile), before this happened, so I just deleted input and it worked.

Are you able to make it fail again. or recover the deleted folder? I need a config file that breaks yuzu

**Comment by blacktide082** [comment]
If you have GShade installed it will also cause this issue. Opening the GShade Control Panel and disabling Vulkan on the Installations tab fixed the issue for me.

**Comment by Gare-Ng** [comment]
Just remove the config folder under the %appdata%\yuzu\config, restart the yuzu, it will regenerate that folder and everythings works fine.

**Comment by german77** [comment]
Do you still have this issue?

**Comment by Paulolego28** [comment]
I didn't realize this was still open. It was a vulkan_layer thing, prom a recording software, removing it solved the issue.

**Comment by moiian** [comment]
> If you have GShade installed it will also cause this issue. Opening the GShade Control Panel and disabling Vulkan on the Installations tab fixed the issue for me.

It really works!!! I can never imagine that gshade could cause such problem.

**Comment by UndeadlyEye** [comment]
i have the same problem. Did you fix it cause ive been tryign to fix it for DAYS just so i can play snipperclips.
