### ISSUE TITLE
HDR disables in Windows 10 when you enter fullscreen

### ISSUE THREAD

**Issue by theboy181** [yuzu-emu/yuzu#4545]
Lately I have noticed a few things about yuzu and brightness levels.

In the game Volgarr the Viking the game is really dark when my monitor is set to SD so I have been using HDR mode. In HDR mode the game in a Window looks correct, but as soon as you go full-screen it will revert to SD, and exiting will also change the desktop to SD. 

I was hoping that the app could support HDR modes, and/or the ability to adjust yuzu's brightness for the games that don't have in game gamma support.

**Comment by theboy181** [comment]
Updated title - 

Could the Windows 10 support for HDR be a trivial addition to the code base?

**Comment by goldenx86** [comment]
I believe Nvidia fixed this in recent drivers.

**Comment by FigureItOut1990** [comment]
There was a way around this with changing dpi settings but it no longer works and new drivers also do not keep HDR Turned on. Pretty annoying.
