### ISSUE TITLE
The Legend of Zelda: BotW - poor open world performance, magnet power not working

### ISSUE THREAD

**Issue by Julien-Peeters** [yuzu-emu/yuzu#4551]
Running BotW on an r2700x and a Radeon VII nets me 10-20fps in the open world, menus and trial areas run almost flawlessly.
Though, when i encountered the first trial, i noticed the magnet power didn't work, anywhere...
~~I'm working on getting some footage, and perhaps logs when i figure that out.~~
Here's the [footage](https://youtu.be/kmrwmzfMLM0) i was talking about.
I also found the log. (i hope its the right one)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5098801/yuzu_log.txt)

**Comment by behunin** [comment]
This game does some strange things like calling the compute pipeline randomly and copying between image formats that are dissimilar. (to name a few) It will be a while to get all the weirdness handled correctly.
The opening scene (where link wakes up at the very beginning of the game) contains all the weird things this game does. It's a test of sorts... Once yuzu can play the opening scene without issue, this game will be playable, but that will be a lot of work.
If you can get a log from the opening scene that might help in sorting things out.
I have been looking into this for a bit now but I am new to the project so I don't understand it all yet.

**Comment by Julien-Peeters** [comment]
@behunin What about the broken core mechanics then?

**Comment by behunin** [comment]
Once yuzu can pass the through the opening scene of this game without issue. All the mechanics of the game will be working. I cannot for the life of me find the interview with the creators of this game where he talks about this. I remember him talk about how he had put these weird things into the game as a kind of master quest for the programmers  that would create the switch emulator. He knew it would be created one day and he feels it is in the spirit of the game. The yuzu team are very talented so I am confident the they will complete this. I am going to make sure of it once I have the a good grasp on the codebase. 
❤️❤️❤️ this game 😍haha

**Comment by Julien-Peeters** [comment]
Well, it would be great if you could forward the evidence i collected to the current working devs. It might be of use to them.

**Comment by MysticExile** [comment]
Do you still have this issue or has it been fixed?

**Comment by RuinerVoid** [comment]
I came here to post about this exact thing. I'm having trouble with the Magnesis rune not working (as in, it won't highlight an object yellow to allow for selection). Strangely, when I swapped from Vulkan to OpenGL, this bug did not happen.

I'm currently using a 5700xt (and a 3900x, if that matters)

I also get poor open world performance, but a steady 30fps in the Magnesis shrine with Vulkan.

**Comment by ToxicFrog** [comment]
Tested this on an RX480 with driver version 21.2.2 and yuzu version 553 (49f8b7b18), same behaviour as above -- in Vulkan mode entering Magnesis sometimes crashes the game, and when it doesn't items aren't hilighted yellow when you target them and can't be grabbed with the magnet. In OGL mode it works fine (no crashes so far, item hilighting/grabbing works) but with a significant performance hit.

**Comment by shelldoesthings** [comment]
same for me, magnesis is not working at all, but my performance is around a pretty solid 25+ fps.

**Comment by RinMaru** [comment]
Happens here as Well on my RX 480, i5 6402P, 20GB RAM. Also weird artifacting when outside.

**Comment by RuinerVoid** [comment]
Just decided to re-check BotW on EA version 1638.

Yuzu setup:
Vulkan, Async, Multicore, Docked mode.

Hardware:
CPU: 3900x
GPU: 5700xt
32gb ram

Open world performance has vastly improved, which is awesome. However the magnesis rune will not target viable items yet with these settings. This is a game breaking bug, and I find it odd that it's not been fixed yet.

**Comment by supertron9000** [comment]
Using magnesis results in a crash of the whole OS (Manjaro linux) with graphical glitches in 100% of the cases. Everything else is buttery smooth, even open world. Using OpenGL works fine with magnesis but the overall performance is horrible.

Yuzu Version: yuzu-20210427-cebacd9bb.AppImage | HEAD-mainline-636-5151-gcebacd9bb-dirty
Yuzu Settings: Vulkan, Async, Multicore, Docked mode.
OS: Manjaro Linux
Graphics Card: Radeon RX 580 8GB
Graphics Driver: mesa 21.0.3-2 / vulkan-radeon 21.0.3-2
Processor: AMD Ryzen 5 3600 6-Core Processor
RAM: 16 GB

**Comment by steven-a-wilson** [comment]
Stasis also fails similarly, and Camera can take pictures but doesn't recognize objects for addition to Hyrule Compendium. It seems that there's some underlying "identify the object under the cursor" function that is failing with the current Vulkan code. Common approaches to this seem to essentially use the GPU to turn the "object picking" problem into a "color picking" problem, so I guess this might have something to do with the game being able to read pixels and get the expected color values.

@supertron9000: I am using linux-5.12.1-arch1-1 and mesa/vulkan-radeon 21.0.3-3 with an RX 5700 XT GPU and Ryzen 3900X CPU and do not see a crash, just the previously described behavior where a target can't be selected for Magnesis. Although your crash is presumably triggered by something Yuzu is doing, bringing down the entire OS suggests a driver bug.

**Comment by glenkalarikkal** [comment]
Is there any update on this issue? Maybe a fix in the nightly/early access builds ? I only get 15-20fps in open world with Ryzen 5600x + RTX 3070 in opengl. The game gives much better performance in vulkan , so that I have to stop -> switch graphics API -> stop and switch back if I have to do magnesis to have playable framerates

**Comment by RinMaru** [comment]
Even with Hades it still runs like crap on AMD in VK. Compared to Nvidia being able to reach 60fps in OpenGL.

**Comment by soredake** [comment]
> 
> 
> Even with Hades it still runs like crap on AMD in VK. Compared to Nvidia being able to reach 60fps in OpenGL.

Amd drivers are really bad, easier to install linux to dualboot.
