### ISSUE TITLE
yuzu mod error

### ISSUE THREAD

**Issue by hklgc** [yuzu-emu/yuzu#4553]
i am playing pokemon sword and i downloaded some mods and added them to mod data location. I downloaded the mods from yuzu's official site but when i opened properties page there were no add ons except the dcl and update please help 

-->

**Comment by Julien-Peeters** [comment]
did you unpack the zip/rar files into the game's mod folder, and then remove the zip/rar files from the folder again?

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
