### ISSUE TITLE
Fire Emblem: Three Houses audio echo issue with latest build

### ISSUE THREAD

**Issue by Dane0** [yuzu-emu/yuzu#4554]
Audio was working well and a lot of the original issues were fixed (see this post for details on the audio/bugs that were encountered):

https://yuzu-emu.org/game/fire-emblem-three-houses/

With build 866 of early access the issue is not present. 

When using the latest build (909) the echo is present anytime there is dialogue.

**Comment by FearlessTobi** [comment]
Can you please provide a log file?


@ogniK5377 This is probably related to your audio rewrite?

**Comment by Dane0** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5120167/yuzu_log.txt)
This is the latest log using build 902.

**Comment by CassiusKahn** [comment]
@FearlessTobi I'm also having this issue on Early Access 926. Audio is set to Auto, and I have tried multiple audio devices.

**Comment by ichronox** [comment]
Have seen others complain about this also, stating that it started with the newer builds and still happening.

**Comment by AnymoreRex** [comment]
Using build 443, the issue is still here.

**Comment by Morph1984** [comment]
This issue has been reported to be fixed, closing.
