### ISSUE TITLE
"yuzu-cmd" doesn't work anymore

### ISSUE THREAD

**Issue by jinzouningen** [yuzu-emu/yuzu#4556]
Hello everyone, I have a question... For the last few months, I noticed that "yuzu-cmd" doesn't work anymore... When I try to load a game, it freezes with "reloading present frame"... Is it my problem or not? Citra-qt works like a charm, but I need to use yuzu-cmd sometimes...

**Comment by FearlessTobi** [comment]
I'm also able to reproduce this issue.

**Comment by G-Spawn** [comment]
This should be fixed with newer yuzu builds.
