### ISSUE TITLE
Good Job! visual bugs on OpenGL and Vulkan

### ISSUE THREAD

**Issue by ImAkemi** [yuzu-emu/yuzu#4567]
Yuzu version: EA 896
Problem: OpenGL has incorrect visuals, it appears much brighter than in Vulkan. Vulkan has some minor issues I have noticed.

This is how Manufacturing should look like on a Switch (Floor 6)
![Switch_Manufacturing](https://user-images.githubusercontent.com/57920314/90987356-014a1c80-e550-11ea-9b39-da6910b44456.png)

This is how it looks in OpenGL with the incorrect colors and ice not looking right (Floor 6)
![Yuzu_OpenGL_Manufacturing](https://user-images.githubusercontent.com/57920314/90987375-35bdd880-e550-11ea-9d9e-5201f28c4be7.png)

This is how it looks in Vulkan, with just incorrect ice (Floor 6)
![Yuzu_Vulkan_Manufacturing](https://user-images.githubusercontent.com/57920314/90987546-5fc3ca80-e551-11ea-94f1-6c6b1e115bff.png)

### The other issues I have noticed in Vulkan was with a water stream, a water hose, object heating, and ice. The last 2 are mainly their aura. These issues are not present in OpenGL.

Water stream & water hose on Switch (Floor 3, room 301)
![Switch_Garden](https://user-images.githubusercontent.com/57920314/90987542-59355300-e551-11ea-98fc-d23f94e79aa2.png)

And on Vulkan (Floor 3, room 301)
![Yuzu_Vulkan_Garden](https://user-images.githubusercontent.com/57920314/90987560-7702b800-e551-11ea-92d7-42000fbeacfc.png)

Heating aura on Switch (Floor 4, room 402)
![Switch_Heat](https://user-images.githubusercontent.com/57920314/90987618-ef697900-e551-11ea-803d-0f93efd30192.png)

Heating aura on Vulkan (Floor 4, room 402)
![Yuzu_Vulkan_Heat](https://user-images.githubusercontent.com/57920314/90987627-04dea300-e552-11ea-9e14-1a68b8b87895.jpg)

Ice on Switch
![Switch_Ice](https://user-images.githubusercontent.com/57920314/90987675-6e5eb180-e552-11ea-94a0-dd6816d7ead3.png)

Ice on Vulkan (Floor 5, room 501)
![Yuzu_Vulkan_Ice](https://user-images.githubusercontent.com/57920314/90987705-94845180-e552-11ea-9db3-fcd314b36877.png)

From playing it mainly seems OpenGL is graphically fine, aside from the brighter visuals. I'm not sure why, but when you go through a loading screen the game is visually correct during these, here is an example of what I am talking about: [Video example](https://youtu.be/e4tzmveKnZo)

**Comment by choppymaster** [comment]
Is this fixed after the TCR @ImAkemi ?

**Comment by G-Spawn** [comment]
^ Please reopen issue if this still happens to you on latest yuzu versions and provide new log.
