### ISSUE TITLE
kernel/scheduler: Data race in GlobalScheduler::Lock

### ISSUE THREAD

**Issue by ReinUsesLisp** [yuzu-emu/yuzu#4585]
`current_owner` can be read without holding a mutex in `GlobalScheduler::Lock`:
https://github.com/yuzu-emu/yuzu/blob/b8885aa03bed5f9a374163d3fdcb67e59ab4c441/src/core/hle/kernel/scheduler.cpp#L554
while `GlobalScheduler::Unlock` (holding a mutex) writes to it in:
https://github.com/yuzu-emu/yuzu/blob/b8885aa03bed5f9a374163d3fdcb67e59ab4c441/src/core/hle/kernel/scheduler.cpp#L572

This has been reported by clang's thread sanitizer.

I considered opening an issue to document this bug. I tried fixing it but I don't understand the code to properly fix it.

**Comment by garrettgu10** [comment]
I can't see the data race potential here, since current_owner is always set to null whenever the lock is available. This implies that a thread can never observe current_owner as itself when it doesn't hold the lock, even without using volatile or atomic variables. Can you please provide more detail? Thanks!

**Comment by ReinUsesLisp** [comment]
`current_owner` can be read in the expression `current_thread == current_owner` without holding a mutex in one thread while `current_owner = Core::EmuThreadHandle::InvalidHandle();` is evaluated (holding a mutex) in the other. This means `current_owner` doesn't have a defined value when read in `current_thread == current_owner`.

**Comment by garrettgu10** [comment]
@ReinUsesLisp I agree that can happen, however current_owner is only used in thread A outside of a lock in that one instance, where it is used to check against the current thread. If some other thread B is in the process of setting the current_owner to null, it must be switching the owner from B to null. In both cases, thread A will observe that the current owner is not equal to itself, so execution is unaffected.

**Comment by ReinUsesLisp** [comment]
It is still undefined behavior. From [cppreference](https://en.cppreference.com/w/cpp/language/memory_model#Threads_and_data_races):
>A program that has two conflicting evaluations has a data race unless
>
>    - both evaluations execute on the same thread or in the same signal handler, or
>    - both conflicting evaluations are atomic operations (see std::atomic), or
>    - one of the conflicting evaluations happens-before another (see std::memory_order) 

This code doesn't do anything of that.

From a practical standpoint, having this kind of issues doesn't allow us to detect problematic data races in the code through sanitizers because everything is signalling data races.

**Comment by liamwhite** [comment]
The scheduler has been rewritten to match the scheduler from Mesosphere, which should not have any race conditions.
