### ISSUE TITLE
Project DIVA Mega Mix - Desync Bugs in NVIDIA GPU with Multicore Enabled

### ISSUE THREAD

**Issue by DeathChaos25** [yuzu-emu/yuzu#4592]
Yuzu Early Access 909

GeForce RTX 2060
Ryzen 7 3700X

The game has a series of desync issues on NVIDIA GPUs.

On Single Core, almost no desync issues exist, however the game is prone to shader stutter on 1080p.

On Multi Core, there seem to be no issues with shader stutter for the most part, however the game audio desyncs very easily and gets progressively more out of sync, rendering the game unplayable.

[Example of minor desync in Single Core (Camera desync).](https://cdn.discordapp.com/attachments/531648057452789771/748288461508968549/GhostRuleDesyncYuzuComparison.mp4)

[Example of extreme audio desync with Multi Core enabled](https://cdn.discordapp.com/attachments/531648057452789771/748288466546065518/AudioDesyncYuzu.mp4)

**Comment by slashiee** [comment]
Isn't the audio desync issue related to the audio lag that happens overall in multicore?

**Comment by DeathChaos25** [comment]
I have a friend with same processor, AMD GPU (AMD Radeon RX 5500 XT 8GB), they have no audio desync issues in Multi Core.

**Comment by Goldenboy22** [comment]
Only to ADD that the extreme audio desync issue happens also in **ASTRAL CHAIN** (only in cutscenes though)

Yuzu EA 909
Nvidia GeForce GTX 1070
Intel Core i7 7700

With MULTICORE ENABLED every cutscene in the game is heavily desynced, during gamplay, instead, audio is perfectly synced.
The issue could be easily examined in the opening custscene.

**Comment by slashiee** [comment]
Audio desync can get pretty abysmal with songs in Mega Mix that use NVDEC. (ex. [Black Rock Shooter](https://youtu.be/fIyYGK9Xab8))

**Comment by german77** [comment]
Please test if this still happens

**Comment by DeathChaos25** [comment]
This still happens to me on the newly released EA 1866 (Project Hades)
https://streamable.com/gwjos8

**Comment by Artins90** [comment]
I also have desync with:

EA 2736
RTX 2080Ti
i7 7820X

I have the JP version of the game with patch 1.0.7 installed.
Going back to yuzu 960 fixes the issue.

**Comment by kaninhot004** [comment]
> 

Thanks! It's sync perfecty now. (With 960 build)

**Comment by liamwhite** [comment]
This should have been fixed with the audio rewrite https://github.com/yuzu-emu/yuzu/pull/8545 - comment if this issue is still occurring.
