### ISSUE TITLE
yuzu uses shared memory instead of VRAM (?)

### ISSUE THREAD

**Issue by darwpm4gs** [yuzu-emu/yuzu#4595]
i7 6700k \ RX 570 \ 12gb ram. 
Yuzu 360
most games start to use shared memory instead of filling up the VRAM
if I understand correctly shared memory used when VRAM  is in near full use. but yuzu starts to use it (shared memory) right away

screen: https://1drv.ms/u/s!AmAQiChbx02AhpA9OwQfkSP28ipydQ?e=G49PKf
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5137833/yuzu_log.txt)

**Comment by ReinUsesLisp** [comment]
yuzu uses host visible memory to upload and download resources from the host GPU. Images and large buffers are stored in VRAM.

High shared memory consumption on AMD may be caused by the large descriptor pool yuzu creates at boot and 256 MiB reserved for the stream buffer.

**Comment by PacoAvelar** [comment]
How would a high memory GPU would behave on yuzu ? lets say RTX Titan with 24GB of GDDR6 VRAM, would it store almost everything needed just on VRAM ? or current implementations as a max allocation limit ?

**Comment by liamwhite** [comment]
This is not a bug and is working as intended. 
@pacoa-kdbg it would behave the same -- only things that are involved in the on-card rendering pipeline are stored in device local memory.
