### ISSUE TITLE
[Windbound] Game stuck at infinite loading screen (in game) 

### ISSUE THREAD

**Issue by PacoAvelar** [yuzu-emu/yuzu#4607]
After booting, game gets stuck at infinite loading screen, logo continues moving at 4-5 fps, progress bar doesnt move at all.

Yuzu doesnt crash, memory resources doesnt increase, game has to bet "stopped" 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5145877/yuzu_log.txt)

**Comment by bukyapavankumar** [comment]
This should be discussed on discord support

**Comment by willfaust** [comment]
> After booting, game gets stuck at infinite loading screen, logo continues moving at 4-5 fps, progress bar doesnt move at all.
> 
> Yuzu doesnt crash, memory resources doesnt increase, game has to bet "stopped"
> 
> [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5145877/yuzu_log.txt)

same situation for me!

**Comment by lioncash** [comment]
Fixed in #5831
