### ISSUE TITLE
Yuzu Failed to build on Jetson Xavier NX

### ISSUE THREAD

**Issue by zhiyan114** [yuzu-emu/yuzu#4610]
Commit Hash: `3db9a259771a44278ff34168ba140c2c7815a1cf`
Jetson Xavier NX is basically same thing as Jetson Nano but with more compute power.
I managed to get pass the cmake using this command: `cmake -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 ..` but when I tried to build it (`ninja` command), it throws error that `dynarmic` files not found.

Partial Error:
```
../src/core/arm/dynarmic/arm_dynarmic_64.cpp:7:10: fatal error: dynarmic/A64/a64.h: No such file or directory
    7 | #include <dynarmic/A64/a64.h>
__________________________________________________________________________________________
../src/./core/arm/dynarmic/arm_exclusive_monitor.h:10:10: fatal error: dynarmic/exclusive_monitor.h: No such file or directory
   10 | #include <dynarmic/exclusive_monitor.h>
```
There are two other more files are not found.

I built it on:
`Ubuntu 18.04`
`GCC 10.1`
`G++ 10.1`

**Comment by goldenx86** [comment]
yuzu is AMD64 only for now.

**Comment by zhiyan114** [comment]
> yuzu is AMD64 only for now.

oh ok. Is there any old commit that I can use it to build it on? (I seen someone built it on arm device once so just wondering)

**Comment by YLinXin** [comment]
> > yuzu is AMD64 only for now.
> 
> oh ok. Is there any old commit that I can use it to build it on? (I seen someone built it on arm device once so just wondering)

The newest code also lacks ARM support. 一年半过去了还是没有支持ARM，哎。

**Comment by liamwhite** [comment]
See https://github.com/yuzu-emu/yuzu/issues/5290 for continued discussion
