### ISSUE TITLE
Pokemon Sword - Isle of armor, Instant Freeze only en new Yuzu builds.

### ISSUE THREAD

**Issue by Nico00007566** [yuzu-emu/yuzu#4615]
-Yuzu 363

-I have a problem that is very strange and not even in the discord support they know what it is, when trying to run Pokemon Sword and enter the DLC area isle of armor the game freezes instantly and only the background music remains, this Error only runs in the most recent versions of Yuzu, since in old ones like Yuzu 290 It works perfectly, I already tried disabling options, changing from vulkan to opengl, I am not using any mod (I never installed it) I find it strange that if I works in old builds, and not in new ones, that's why it leads me to suspect that maybe it is something of the new builds

-I5 8400 - RX 570 8gb - 16gb ram ddr4.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5152801/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
This is not a support forum. Keep these types of things on the discord where they belong
