### ISSUE TITLE
yuzu can lot load ROM directory from a mapped network drive.

### ISSUE THREAD

**Issue by UrielCh** [yuzu-emu/yuzu#4616]
Hi,

I stored some switch ROM on a NAS shared folder, and mapped a network as *R:/*

If I click on `File` > `Load Folder...` and select my *R:/rom/* directory, I get the following error:

**The directory you have selected does not contain a 'main'**

Loading a single ROM from the mapped networks drive works fine. not like issue #2805

I'm using `yuzu 363 . | HEAD-mainline-636-3283-g4298061c6 (2020-08-30)`

By the way, copying folder to a local drive make Folder import works.

**Comment by renA21** [comment]
The `Load Folder...` option is used to load **a** ROM with its **game files extracted to a folder**, not to load multiple ROMs. If you want to add multiple games, just click on `+ Add New Game Directory` and specify your ROMs folder.

**Comment by shayaansiddiqui** [comment]
This is not working for me

**Comment by GregoryRudinsky** [comment]
This is me from the future. I can confirm mapping a SMB folder works. 

**Do not** `File > Load Folder`  Instead, click/drop directory on the big ol' graphic: **Double-click to add a new folder to the game list**
- ![2024-01-28 20_26_40-yuzu-setup](https://github.com/yuzu-emu/yuzu/assets/115956307/9f700401-91b8-4fef-b28e-ab16c26ab4c0)
