### ISSUE TITLE
Yuzu Crashes on Linux Using Vulkan

### ISSUE THREAD

**Issue by titan-91** [yuzu-emu/yuzu#4617]
I am using Yuzu Development Build | HEAD-mainline-636-3283-g4298061c6-dirty on Linux Mint 20 x64. I have an AMD Ryzen 7 3700x with no overclock, 16GB of PC4-2400 memory, with an AMD RX 580. I'm using Vulkan 1.2.128 provided from AMD RADV POLARIS10 (LLVM 10.0.0). My log is attached.

Yuzu is crashing when running Super Smash Bros. Ultimate with dual core and asynchronous GPU emulation turned on. I try to turn async GPU off in the global and post-game setting but it becomes re-enabled when the next game is started or emulator is re-opened. I have the Yuzu folder in my home directory with full read and write permissions. The game does not crash immediately, often a few minutes in at the match settings screen or during a match. I can reproduce it in training and normal smash modes. On one occasion this has also froze my entire system and caused my video card to stop sending a signal entirely. This particular kernel level freeze happened when attacking a smash ball, probably due to compiling shaders.

I don't have any other games to test, but Groundbreaking-Ad274 on Reddit has also reported this with Ninja Warriors. I have asked him to comment on this issue to add more information.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5156018/yuzu_log.txt)

**Comment by bukyapavankumar** [comment]
When Multi-core is on.async will be always on .

**Comment by goldenx86** [comment]
This is something that should be asked in the support channels, either the forums or the discord server.
Try using a newer mesa version, and also install the AMDVLK driver to have an alternative. Linux Vulkan drivers are not as stable as the Windows one, so I recommend sticking to OpenGL, where the Linux driver is actually a LOT better than on Windows.

**Comment by albfan** [comment]
Why there's no way to choose GPU on opengl like in vulkan?

**Comment by G-Spawn** [comment]
Please feel free to reopen issue @titan-91  if this happens to you on latest yuzu versions & gpu driver.
