### ISSUE TITLE
Yuzu Pokemon Sword/Shield 2-5 FPS while moving on non FMA CPUs

### ISSUE THREAD

**Issue by varunashiki** [yuzu-emu/yuzu#4620]
Is it possible to resolve this issue where you have 2-5 fps when you walk in pokemon sword/shield for Yuzu? My CPU is non FMA CPU.

I otherwise get 40-50 FPS normally except when I start walking.

**Comment by BSoDGamingYT** [comment]
Enable the unsafe mode in the configure/CPU section. This will aid your performance in CPUs not supporting FMA
