### ISSUE TITLE
graphics problem with sand in luigi's mansion 3

### ISSUE THREAD

**Issue by luizjr860** [yuzu-emu/yuzu#4623]
The sand is not showing, I tested it on the last 5 EA versions, my current one is 929
![image](https://user-images.githubusercontent.com/6024699/92038324-99fb4c00-ed49-11ea-9fc7-d1d3b8319f6e.png)
![image](https://user-images.githubusercontent.com/6024699/92038394-ada6b280-ed49-11ea-847b-3f43204336fe.png)

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by luizjr860** [comment]
I understand that this is for developers, in fact it was the supports that asked to open it here, but thanks

**Comment by luizjr860** [comment]
I understand that this is for developers, in fact it was the supports that asked to open it here, but thanks

**Comment by choppymaster** [comment]
Reference: #3446

**Comment by txuki2005** [comment]
![Sin título](https://user-images.githubusercontent.com/12988083/113889610-ace46c00-97c3-11eb-9969-1afd0b1885e0.png)

I have solved the problem momentarily. I've always been using Vulkan but made a few changes so the sand can be seen. In some other zones are invisible.

Yuzu - 585

Luigis mansion 3 1.0

mods: 60fps and disable-Dynamic-Resolution

Graphics: OpenGL API
                   shaders cache on disk- on
                   asyncronimus GPU emulation - on
                   NVDEC emulation - on
Advanced graphics:
Precision: High
Vsync: on
Two experimental shaders- OFF
GPU speed temp - ON

MY PC: i7-8700 - 16 gb ram - GTX 1080
