### ISSUE TITLE
lag and freeze on ACNH Nook Terminal 

### ISSUE THREAD

**Issue by alekzandah** [yuzu-emu/yuzu#4624]
https://gyazo.com/13e52d29e983f6f75ca22442aa709309

THIS LOG IS OF A FREEZE [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5165176/yuzu_log.txt)

THIS LOG IS OF A CRASH [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5165185/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for those things.

Also I see that you have multiple outdated mods activated. 
This is already a very likely cause of your crashes.

**Comment by alekzandah** [comment]
I was told by a discord mod to open this ticket.

**Comment by jremick2** [comment]
also having this issue, any fix?

**Comment by FearlessTobi** [comment]
Closing in favor of https://github.com/yuzu-emu/yuzu/issues/5006.
