### ISSUE TITLE
I really wish VS and Mystery Gifts work

### ISSUE THREAD

**Issue by messelol80** [yuzu-emu/yuzu#4628]
Yuzu is an excellent switch emulator, i could finally play pokemon Sword int that, but I really wish that the internet connections work(except the y comm coz the y comm is trash even in real nintendo switch) but i wish i could do max raid battles with my friends and battle them 
So Thanks in advance
Please implement internet in yuzu just like Citra

**Comment by RodrigoTR04** [comment]
It's intended to have something like Citra, Mystery Gifts won't work because it needs Nintendo servers, also this is an issues tracker for development, things like this go on the discord server.

**Comment by jonsn0w** [comment]
This isn't an issue. This is not the place to request personal features.
