### ISSUE TITLE
Conan conflict when building yuzu under linux

### ISSUE THREAD

**Issue by Narice** [yuzu-emu/yuzu#4631]
Under the current version of yuzu (commit 80a56), I get the following error by using the wiki build instructions:
```
WARN: qt/5.14.1@bincrafters/stable: requirement zstd/1.4.4 overridden by your conanfile to zstd/1.4.5
WARN: libmysqlclient/8.0.17: requirement openssl/1.1.1g overridden by qt/5.14.1@bincrafters/stable to openssl/1.1.1d
ERROR: Conflict in libsndfile/1.0.28:
    'libsndfile/1.0.28' requires 'sqlite3/3.29.0' while 'qt/5.14.1@bincrafters/stable' requires 'sqlite3/3.31.0'.
    To fix this conflict you need to override the package 'sqlite3' in your root package.
CMake Error at build/conan.cmake:402 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  build/conan.cmake:497 (conan_cmake_install)
  CMakeLists.txt:284 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/home/narice/dev/yuzu/build/CMakeFiles/CMakeOutput.log".
ninja: error: loading 'build.ninja': No such file or directory
```
I don't really know the conan build system, so I don't really know how to fix it but I'm willing to help as much as possible.
I'm on linux, more precisely on nixos 20.03 but I don't think my distribution matters. I can test if needed on another distribution if you want.

**Comment by G-Spawn** [comment]
> This also shouldn't happen anymore, you can easily not use conan at all on linux with the CMake changes since then (and that's probably a better idea than using it)
