### ISSUE TITLE
Paradise Killer [01007FB010DC8000]+[v1.0.8] -- Ingame Menu then crash at loading game

### ISSUE THREAD

**Issue by talhakammybond** [yuzu-emu/yuzu#4637]
![yuzu](https://user-images.githubusercontent.com/6057150/92414482-ff986f80-f171-11ea-965d-0d9eb209f727.png)

![yuzu 2](https://user-images.githubusercontent.com/6057150/92414486-03c48d00-f172-11ea-9667-09ca1902c44c.png)

**Comment by BSoDGamingYT** [comment]
Please post a log after the crash has occurred as per the instructions given when opening new issues. Two images and a decription do not help this issue get solved

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by slashiee** [comment]
This is also not the right place to report game compatibility, that should be done on the wiki at [yuzu-games-wiki](https://github.com/yuzu-emu/yuzu-games-wiki/wiki).

**Comment by talhakammybond** [comment]
> 
> 
> This is an issue tracker for developers and not a support forum.
> Please use our Discord for support requests.


Oh I see! Sure! thanks!
