### ISSUE TITLE
Kirby Star Allies: DOF effect not applied to portion of screen

### ISSUE THREAD

**Issue by v1993** [yuzu-emu/yuzu#4639]
Here's an example screenshot:
![Screenshot_20200909_223421](https://user-images.githubusercontent.com/16255906/92645544-ad7c5900-f2ed-11ea-8dc4-2c9f25ac6dab.png)

And here's zoom in near right border of screen:

![Screenshot_20200909_223421-1](https://user-images.githubusercontent.com/16255906/92645862-31cedc00-f2ee-11ea-83a0-9619b7e3b50b.png)

It appears that effect area is offset to the left by 32-34 pixels. Tested on OpenGL (but IIRC vulkan have the same issue), assembly shaders off, multicore on. OS: KUbuntu 20.04, proprietary NVidia drivers, GTX 960.

**Comment by v1993** [comment]
Interestingly, in undocked mode portion that is left unaffected by DOF effect on screenshot above ends up heavily blurred (likely by DOF) instead.

**Comment by v1993** [comment]
This have actually gotten worse on recent Yuzu (EA patched)
![Screenshot_20201126_194042](https://user-images.githubusercontent.com/16255906/100375718-497d4d00-301f-11eb-836a-2f200f65ed7a.png)

Now it seemingly also happens near topmost section of the screen.

**Comment by BParks21** [comment]
In the latest build's it seems to have a white line at the top of the screen that I don't remember being there.
![Screenshot (43)](https://user-images.githubusercontent.com/12180630/222112471-4fd89b39-22c5-48b4-a894-ca107d058f2a.png)

**Comment by v1993** [comment]
White line is a result of sampling NaN values from texture (which wouldn't happen during normal execution), so changes to shader recompiler also may change it. It's also a bit less intrusive in OpenGL, I think.

**Comment by v1993** [comment]
Finally fixed in latest version! Most likely by PR #10074.
