### ISSUE TITLE
crash team racing nitro issues

### ISSUE THREAD

**Issue by teamracingfan** [yuzu-emu/yuzu#4640]
hi team

What happens is that when I play Crash Team Racing Nitro Fuel, very often, the RAM usage keeps going higher until it reaches 100% and yuzu crashes and Windows freezes, and there's no sound.

My specs: Nvidia GTX 1650 SUPER 4GB - 16GB RAM DDR4 - Intel Core i3 9100

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5197773/yuzu_log.zip)

**Comment by FearlessTobi** [comment]
This sounds like the kind of issue that could be better handled on our Discord server.
