### ISSUE TITLE
Diablo 3 no longer goes ingame on EA (good EA917) (bad EA918)

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#4641]
goes ingame in EA 917
 freezes up on the autosave screen in EA 918
![diablo 3](https://user-images.githubusercontent.com/2696404/92667735-5606d900-f33f-11ea-8638-26aa9e94c22d.PNG)

**Comment by Morph1984** [comment]
Can you check that this game works in the current mainline release? I cannot replicate your issue.

**Comment by benderscruffy** [comment]
yes works fine in mainline release

**Comment by Morph1984** [comment]
Can you close this issue as it's no longer an issue on the latest builds?

**Comment by benderscruffy** [comment]
still an issue in EA 951

**Comment by Morph1984** [comment]
Can you p[lease provide a log?

**Comment by benderscruffy** [comment]
ok
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5212424/yuzu_log.zip)

**Comment by Morph1984** [comment]
Can you try increasing your pagefile size to at least 24576 MB? Try to increase it as yuzu demands a lot of virtual memory

**Comment by Morph1984** [comment]
In this auto save screen, a dialog is supposed to show up prompting you to select a controller, does that show up for you?

**Comment by benderscruffy** [comment]
yes
after you press ok on controller screen then it freezes up

**Comment by benderscruffy** [comment]
changing the pagefile did not fix it

**Comment by Morph1984** [comment]
@benderscruffy Can you try deleting the qt-config.ini folder in the `%appdata%\yuzu` directory? I've found that a bad configuration can cause this to happen.

**Comment by benderscruffy** [comment]
that fixed it
