### ISSUE TITLE
Crash Team Racing Nitro-Fueled crashes during gameplay

### ISSUE THREAD

**Issue by teamracingfan** [yuzu-emu/yuzu#4644]
Crash Team Racing Nitro-Fueled

during the game, it freezes and I have this error.
Full log yuzu_log.txt is attached below

`[ 859.335524] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:613: Signalling debugger, PANIC! info1=0x0000000000000000, info2=0x0000000000000000
[ 859.335540] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:665: Emulated program broke execution! reason=0x0000000000000000, info1=0x0000000000000000, info2=0x0000000000000000
[ 859.335546] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:258: Backtrace, sp=000000000000000A, pc=000000000E152998
[ 859.335548] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:260: Module Name         Address             Original Address    Offset              Symbol
[ 859.335548] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:261:
[ 859.492055] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 0000007100333180    000000000E0FC180    0000000000333180    nnosBreak
[ 859.492060] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 0000007100519C0C    000000000E2E2C0C    0000000000519C0C    __nnmusl_osBreak
[ 859.492061] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 00000071004CBD80    000000000E294D80    00000000004CBD80    abort
[ 859.492062] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 00000071004C81DC    000000000E2911DC    00000000004C81DC
[ 859.492063] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 00000071004C7BE8    000000000E290BE8    00000000004C7BE8    __cxa_pure_virtual
[ 859.492065] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 0000007100254334    000000000E01D334    0000000000254334    _ZN2nn3hid13VibrationNode16SyncSampleNumberEv
[ 859.492066] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 00000071002543D0    000000000E01D3D0    00000000002543D0    _ZN2nn3hid13VibrationNode6UpdateEv
[ 859.492068] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: main                0000007100376B30    000000000837AB30    0000000000376B30    _ZN7Display24igNxVibrationClipUpdater23vibrationThreadFunctionEPv
[ 859.492068] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: main                0000007101778D9C    000000000977CD9C    0000000001778D9C    _ZN4Core18igNxThreadFunctionEPv
[ 859.492069] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 00000071003344B4    000000000E0FD4B4    00000000003344B4
[ 859.492070] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 0000007100338980    000000000E101980    0000000000338980
[ 859.492071] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: sdk                 00000070F2236FFC    FFFFFFFFFFFFFFFC    FFFFFFFFF2236FFC
`

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5203920/yuzu_log.txt)

**Comment by Myers78** [comment]
Have you found a solution for this? I'm having the exact same problem as yours...

**Comment by teamracingfan** [comment]
at moment with the last yuzu version, YuzuEA-1110. I have this error only on 1 track:

prehistoric playground

I can play all other tracks without issues for hours.

My video card is GeForce GTX 1650 SUPER.
My CPU Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz

**Comment by teamracingfan** [comment]
Do you have the Firmware 10.2.0 ?

I had a significantly improvement when I started to use this firmware.

**Comment by Myers78** [comment]
> Do you have the Firmware 10.2.0 ?
> 
> I had a significantly improvement when I started to use this firmware.

Wow, it worked! I totally forgot about this. I was still using 10.0 firmware. Thanks, dude. You are a real lifesaver!

**Comment by RayHarley** [comment]
I'm having this problem too and already tried different things:

1) Use Firmware 10.2.0 (didn't notice any improvements)
2) Tweak settings (not much to tweak since default settings are perfect for NVIDIA users)
3) Create a 30gb Pagefile (RAM was never an issue playing this but still gave it a try)
4) Switch to Vulkan (game still crashes randomly but now I get weird textures on the screen)
5) Disable multicore (some people suspect this might be the issue, but the game drops to 10fps at best so not viable)

I noticed the game only freezes during races, never had it happen in the main menu, adventure mode map, podium results, or cutscenes. Some tracks tend to freeze more than others, for example: Sewer Speedway, Tiny Arena, Polar Pass and Cortex Castle (these are some of the bigger maps in the game).

Running Yuzu Mainline 446 as of this post.

**Comment by Myers78** [comment]
> I'm having this problem too and already tried different things:
> 
> 1) Use Firmware 10.2.0 (didn't notice any improvements)
> 2) Tweak settings (not much to tweak since default settings are perfect for NVIDIA users)
> 3) Create a 30gb Pagefile (RAM was never an issue playing this but still gave it a try)
> 4) Switch to Vulkan (game still crashes randomly but now I get weird textures on the screen)
> 5) Disable multicore (some people suspect this might be the issue, but the game drops to 10fps at best so not viable)
> 
> I noticed the game only freezes during races, never had it happen in the main menu, adventure mode map, podium results, or cutscenes. Some tracks tend to freeze more than others, for example: Sewer Speedway, Tiny Arena, Polar Pass and Cortex Castle (these are some of the bigger maps in the game).
> 
> Running Yuzu Mainline 446 as of this post.

I thought I had fixed this problem after the suggestion from the creator of the post (to use the latest firmware), but after some time it crashed again. I talked to one of the devs, and he said that this is the last option you mentioned. For some reason the multicore is causing instability for some games, and CTR is one of those. We'll have to wait until they fix it, or at least in my case, upgrade my cpu for one that has a better single core performance (I have a r3 2200g and without multicore, I have even worse fps than yours, around 6 or 7 fps in cutscenes, I haven't even waited to see how it goes during races)

**Comment by teamracingfan** [comment]
> Running Yuzu Mainline 446 as of this post.

this is the issue, Yuzu Early Access has less problems but I had many with Yuzu Mainline.

At moment with Firmware 10.2.0  and CTR (version 1.0.15) I can play all tracks without issues for hours, except the prehistoric playground (it crashes always in 2 players, and time by time in single player).

**Comment by teamracingfan** [comment]
> I thought I had fixed this problem after the suggestion from the creator of the post (to use the latest firmware), but after some time it crashed again

compared to before, is much better?

**Comment by teamracingfan** [comment]
multicore has improved yuzu enormously. It was unplayable CTR without this feature, I play 60 fps with the 60 fps mod for CTR and multicore enabled

**Comment by Myers78** [comment]
> > I thought I had fixed this problem after the suggestion from the creator of the post (to use the latest firmware), but after some time it crashed again
> 
> compared to before, is much better?

At first when I played after updating to 10.2.0 firmware, I was able to play for like one hour straight (It had never happened before), but when I was assuming it was fixed, and I was intending to play the last of races for that day, when I less expected, it crashed again. I tried to play after this multiple times but never reached 1 hour straight again without crashing. 

Let me ask you something, which windows version are you using? If you are using multicore and don't have this much of crashes, I think even the devs could be wrong then.

**Comment by teamracingfan** [comment]
Windows 10 202H now, but with 1909 was working good the same

**Comment by Myers78** [comment]
Hm, I am using this same version now, but also used with this 1909, and for me both are crashing, so I think it doesn't have to do with windows then. 

Now I'm confused, I really thought it was multicore, but you said it's better in the latest builds. It could be anything in this case. Maybe they've implemented something for intel users that corrected this issue. I'm really in the dark about this issue now.

**Comment by RayHarley** [comment]
> Hm, I am using this same version now, but also used with this 1909, and for me both are crashing, so I think it doesn't have to do with windows then.
> 
> Now I'm confused, I really thought it was multicore, but you said it's better in the latest builds. It could be anything in this case. Maybe they've implemented something for intel users that corrected this issue. I'm really in the dark about this issue now.

I have an Intel CPU too and the problem persists.

i5-4460
GTX 1660 6gb
8gb RAM

It might be a hardware issue but to be honest I have no clue about this stuff.

Game freezes on both 1.0 and 1.0.15 versions. I'm running a .xci file to play, maybe .nsp works better? It shouldn't matter but at this point I take anything into account.

**Comment by choppymaster** [comment]
How is .nsp and .xci both possible on 1 switch?

**Comment by Myers78** [comment]
I use .nsp, so I think we can discard this option. I really don't know what it could be. I've done everything recommended, gpu drivers updated, c++ updated, pagefile increased, yuzu and nvidia settings are the same as Bsod's. Maybe we just aren't lucky with this game 😔

**Comment by Myers78** [comment]
> How is .nsp and .xci both possible on 1 switch?
> 

He just wondered if .nsp would work better. He didn't say he'd try .nsp after trying .xci

**Comment by teamracingfan** [comment]
@RayHarley, try Yuzu Early Access

**Comment by Myers78** [comment]
@RayHarley I think I got it now. Been playing for 2 hours straight without a crash. I disabled all my dlcs (I don't know how I didn't try it before) and now it works. I also updated my Yuzu EA to 1152 (I was using 1122 when I got the crashes). Now I don't know if it was the dlcs or because I updated my Yuzu. But I noticed that from Yuzu EA 1125 and on, for CTR the audio is crackling a lot, so I'll try to run it on Yuzu EA 1124 without dlcs to make sure if it was the dlc or the Yuzu EA with rewritten shaders which corrected it and I'll update results here.

**Comment by RayHarley** [comment]
I disabled all my DLC (except for version 1.0.15 update) and managed to beat an adventure mode cup without crashes. However, it crashed on the next cup I played. Did you disable all DLC including the 1.0.15 update?

I heard that one of the new versions of EA broke the audio, so you have to play an older build until it gets fixed.

**Comment by Myers78** [comment]
It just happened to me on EA 1122, so I think they fixed it on the newer versions with the addition of rewritten shaders. Now the sound is the problem ☹️

**Comment by teamracingfan** [comment]
the same I have crackling sound too with new Yuzu EA 1156.

At moment I use EA 1121 and is almost perfect.

I have all DLC activated from 1 to 8, 60 fps mod, CTR update 1.0.15 and DOCK mode (on the lower left in the YUZU window you can choose the DOCK mode)

**Comment by teamracingfan** [comment]
Limit Speed Percent disabled

**Comment by teamracingfan** [comment]
The System Profile User in the yuzu configuration. Remove and create a new one if you have updated the firmware.

**Comment by Myers78** [comment]
@teamracingfan how to delete a profile?

**Comment by teamracingfan** [comment]
- Open yuzu
- Emulation
- Configure
- System
- Profiles
- Remove the existing one
- Add a new one

**Comment by RayHarley** [comment]
Tried EA 1152 with all DLC disabled except update 1.0.15 and managed to beat 2 cups without crashes (8 races, about 38 min playtime).

Then I tried EA 1121, enabled all DLC (1 to 7), disabled Limit Speed Percent, created a new profile (deleted the old one too) and my game crashed on the third race I played. I was playing Thunder Struck which is the only track, so far, that drops my fps to 20-25, so I don't know if that track made my game crash or it was the usual random crash we are dealing with.

I'll keep playing a bit more with EA 1152 (with and without DLC) and see if it actually fixed the random crashes for me or I was just lucky that time.

**Comment by teamracingfan** [comment]
>  I was playing Thunder Struck which is the only track, so far, that drops my fps to 20-25

![immagine](https://user-images.githubusercontent.com/71040364/100540700-1e714400-323f-11eb-8e01-500c3b931d26.png)

disable debug logs and try again

**Comment by liamwhite** [comment]
Comment with an updated yuzu log if this is still relevant.
