### ISSUE TITLE
Softlock in New Super Mario Bros U Deluxe

### ISSUE THREAD

**Issue by goldenx86** [yuzu-emu/yuzu#4649]
Both mainline 376 and EA 952 are affected.
Game softlocks after taking a pipe in the Boo Haunted ship in World 3.
GPU vendor, API, Asynchronous GPU or Multicore are irrelevant.
Partial Wait tree:
![wait tree](https://user-images.githubusercontent.com/42481638/93029551-0bf94e00-f5f2-11ea-95d3-a8a6ea7efafb.png)

Affected area:
![Screenshot_215](https://user-images.githubusercontent.com/42481638/93029558-1ae00080-f5f2-11ea-811d-32169102fa1b.png)

**Comment by FearlessTobi** [comment]
log file is missing :p

**Comment by goldenx86** [comment]
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5215897/yuzu_log.zip)

**Comment by Morph1984** [comment]
This issue has been reported to be fixed, closing.
