### ISSUE TITLE
[Feature Request] Pokéball Plus Support

### ISSUE THREAD

**Issue by nevespt** [yuzu-emu/yuzu#4650]
Add the profile in controllers setting for pokéball plus
![image](https://user-images.githubusercontent.com/50218490/93101003-afee0280-f6a1-11ea-8e85-36a9fcefeb2c.png)

Also send realtime data beteween the game and the controller, incluide rumble, sounds, lights, motions and trading pokemons.

A reference guide of features of the controller: https://www.youtube.com/watch?v=WtNV7DURZS8

**Comment by german77** [comment]
Let me get this right. You want to be able to use your real pokéball controller. Or a simulated one?

**Comment by nevespt** [comment]
both

**Comment by german77** [comment]
This is a very game specific controller type.  Reverse engineering/documentation of this controller is poor to use a real one. Investing time and effort on this controller is just not worth it at the moment.

Maybe in a few years or when someone thinks it's worth the time and effort to implement this controller.

**Comment by german77** [comment]
I implemented some stuff. But seems like main feature use online services. Let me know if there's any feature that doesn't require an online service

**Comment by liamwhite** [comment]
Partially implemented in #8934
