### ISSUE TITLE
Freeze while collecting any moon in Super Mario Odyssey

### ISSUE THREAD

**Issue by mephiles06** [yuzu-emu/yuzu#4654]
so i have a problem in mario odyssey EVERY moon i touch ii have to wait 60 sec for it to be collected (freez for 60 sec) i never had this problem but for some reason i have it now and my laptop is core i7-9750H and 16 ram and gtx 1650 
i need yuzu team to find a fix for it please

**Comment by RodrigoTR04** [comment]
Video of the issue: https://discordapp.com/channels/398318088170242053/400106910231035904/755102072600526969

![IMG_20200914_181540](https://user-images.githubusercontent.com/65554156/93145393-96a97e00-f6c2-11ea-9372-b2a3bbc35cea.png)

**Comment by Schplee** [comment]
User regenerated their `yuzu` folder and all their problems were resolved.
