### ISSUE TITLE
Super Mario Odyssey: Black screen flickering when undocked

### ISSUE THREAD

**Issue by Jatoxo** [yuzu-emu/yuzu#4656]
Tested on Yuzu EA954. 
R5 3600, GTX1070, Win10

~~When in-game and not in docked mode, the right part of the screen gets distorted. Speech bubbles however still render normally. This happens on both Vulkan and OpenGL, regardless of the yuzu configuration.
[image](https://user-images.githubusercontent.com/39669932/93148863-40a1fe00-f6f5-11ea-8549-0da6c52e9ae4.png)~~ 

This is caused by mods (disable dynamic resolution, 1080p mod)

When using OpenGL and Assembly Shaders, the screen additionally flickers black. Sometimes when moving the camera the flickering stops and the screen remains black (UI elements excluded).

Video (Click):

[![IVideo link](https://i.imgur.com/RzKtdSH.jpg)](https://youtu.be/aL4M36gY43U)

Log (OpenGL, Assembly Shaders, Undocked):
[yuzu_log_flickering_distortion_smo.txt](https://github.com/yuzu-emu/yuzu/files/5221655/yuzu_log_flickering_distortion_smo.txt)

**Comment by slashiee** [comment]
This bug happens due to the dynamic resolution mod.

**Comment by Jatoxo** [comment]
Confirmed, the distortion disappears without the dynamic res and 1080p mod, however, the flickering on OpenGL with assembly shaders remains

**Comment by auranticus** [comment]
>  flickering on OpenGL with assembly shaders

I've also got this issue for months, and I thought it was my GPU... Have to use docked mode for the time being.

**Comment by choppymaster** [comment]
Issue is listed on #4073.

**Comment by G-Spawn** [comment]
This issue should be corrected on latest yuzu. Please reopen if it still happens.
