### ISSUE TITLE
Unimplemented function 'LoadOpenContext'

### ISSUE THREAD

**Issue by PabloG02** [yuzu-emu/yuzu#4660]
Used by:

- Dr Kawashima’s Brain Training for Nintendo Switch

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5231215/yuzu_log.txt)

**Comment by choppymaster** [comment]
Needed for:
Clubhouse Games: 51 Worldwide Classics
Grandia HD Collection
XCOM 2 Collection
Baldur's Gate 1/2
Super Mario 3D All-Stars

**Comment by german77** [comment]
Stubbed in #4678
