### ISSUE TITLE
Luigi's Mansion 3 softlock on loading screen

### ISSUE THREAD

**Issue by Darth-Koopa** [yuzu-emu/yuzu#4667]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5240271/yuzu_log.txt)
![1](https://user-images.githubusercontent.com/45894930/93494028-252a3380-f93f-11ea-989c-acbf2fe96bb2.png)
![unknown](https://user-images.githubusercontent.com/45894930/93494034-26f3f700-f93f-11ea-9637-16903d0b1f3a.png)

I tried to get help from discord, and they suggested me to set pagefile and update GPU driver. I did so but the issue is still here. Note that I can boot into the game by using an earlier version of yuzu but when I use the Dark light on paints, the game crash (https://tb-video.bdstatic.com/tieba-smallvideo-transcode-crf/8081964_b43dffbff95b2ff00f1bbc0a8952a93b_0.mp4)

**Comment by FearlessTobi** [comment]
Please provide a log file.

**Comment by Darth-Koopa** [comment]
> Please provide a log file.

I did. It is at the very top of the page

**Comment by G-Spawn** [comment]
Please use updated yuzu and the required mod for the game (https://cdn.discordapp.com/attachments/356187763139280896/957353725574393916/Disable-Dynamic-Resolution.zip), and use Vulkan and not opengl for intel igpu (on updated driver). Feel free to reopen issue after trying all this and provide new log file
