### ISSUE TITLE
Pokemon Sword Issue 

### ISSUE THREAD

**Issue by Gratox** [yuzu-emu/yuzu#4669]
Every time a try to open the game animation stops, the game still running since we can hear the music however is not possible to play. here a video of the issue https://youtu.be/9nfxWHG0Hu8

System Information

Operating System: Windows 10 64
CPU: Xeon E-2620 V3
GPU:RX 580 8GB
Yuzu Version (found in the title bar): YUZU EA 960
Game: Pokemon Sword
yuzu_log.txt (194.7 KB) `shorturl.at/sDGYZ`

Please help.

**Comment by FearlessTobi** [comment]
The log you provided isn't available publicly because GDrive access control is configured wrongly.

**Comment by Gratox** [comment]
> The log you provided isn't available publicly because GDrive access control is configured wrongly.

my apologies, the link has been changed to Mega.

**Comment by leonardofalk** [comment]
@Gratox 

It freezes for me at this exact place in the DLC. You can bypass by loading a previous save and trying again, although I think it's impossible to finish the DLC now. At the title screen, where you press A to start the game, press UP + X + B instead and load the backup save.

**Comment by benderscruffy** [comment]
is this still an issue ???

**Comment by benderscruffy** [comment]
please close

**Comment by G-Spawn** [comment]
@Gratox Please heed what was mentioned above and if it still happens to you on latest yuzu version and after trying the above, please provide a new log.
