### ISSUE TITLE
Problems with non-original controls

### ISSUE THREAD

**Issue by Theriser44** [yuzu-emu/yuzu#4679]
Hello everyone, I wanted to inform that I have an error in yuzu since they placed the automatic control configuration, the issue is that pirate or false controls the automatic configuration does not work, for example, my left joystick above is axis 3- but the yuzu automatically puts Axis 4 and my command does not correspond so I wanted to ask if you could put an option where I can deactivate and activate the automatic configuration   

the first image is my control then when I want to configure the missing ones it automatically switches me to axis 4

![prueba numero 1](https://user-images.githubusercontent.com/71484101/93561254-3b91b880-f95a-11ea-87a8-75d528ab66e1.png)

![Sin título](https://user-images.githubusercontent.com/71484101/93561305-4e0bf200-f95a-11ea-87d6-49a28b6187a6.png)

**Comment by Morph1984** [comment]
Fixed by #4866
