### ISSUE TITLE
unimplemented function 'StoreSaveDataThumbnail' (Arcade Archives LIFEFORCE )

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#4681]
after you choose your game Yuzu just freezes up 
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5244330/yuzu_log.zip)

**Comment by FearlessTobi** [comment]
Duplicate of #2645.

**Comment by benderscruffy** [comment]
thanks was about to close
