### ISSUE TITLE
[Super Smash Bros. Ultimate] Missing Icons on nvidia

### ISSUE THREAD

**Issue by opcod3** [yuzu-emu/yuzu#4682]
Yuzu 380/HEAD-mainline-636-3412-g22fd2484fc

In SSBU Ultimate (Update 8.1.0) certain icons don't appear in the controller settings menu, other menus have not been tested.

## Yuzu Nvidia
![yuzu](https://user-images.githubusercontent.com/5721873/93580141-ac0ef880-f99f-11ea-8a31-77a59fab3eff.png)

## Yuzu AMD
![yuzu_amd](https://user-images.githubusercontent.com/5721873/93580879-a8c83c80-f9a0-11ea-9014-3f60b0b8ffbd.png)

## Original Hardware
![switch](https://user-images.githubusercontent.com/5721873/93578962-35bdc680-f99e-11ea-81e2-7f7ffad8ecf4.jpg)

## Details
This occurs both with Vulkan and OpenGL. Async, ARB, or Multicore emulation have no effect on this bug.
Bug is not present on AMD regardless of any settings.

Tested on:
- Nvidia Quadro P1000
- AMD  Radeon VII

### Log
Both OpenGL and Vulkan logs:
[ssbu_misisng_icon_logs.zip](https://github.com/yuzu-emu/yuzu/files/5244600/ssbu_misisng_icon_logs.zip)

**Comment by Voltzu** [comment]
Installing switch firmware fix this issue

**Comment by benderscruffy** [comment]
please close
