### ISSUE TITLE
Slowdowns in Smash Ultimate intro and Paper Mario Origami King Nvidia Opengl drivers newer than 446.14

### ISSUE THREAD

**Issue by IDSG** [yuzu-emu/yuzu#4687]
I wanna know if this issue is from nvidia side (driver related bug) or some kind implementation that "worked" but some driver messed things up, reverted to 446.14 driver is not an option anymore if user having 30xx series cards, and wants  fixes for newer games, so there's something you can report back to nvidia dev team to fix the issue or make a change in yuzu to behave correctly in newer drivers? 

BTW, using vulkan everyhing works right, but vulkan doesnt have shader cache

**Comment by ReinUsesLisp** [comment]
As a temporary workaround if you attach Nsight Graphics to yuzu, the issue is fixed.

**Comment by goldenx86** [comment]
That means you can't profile the issue with the official tool... Great job Nvidia.

**Comment by ReinUsesLisp** [comment]
Upon further investigation, it's caused by our vsync implementation.

**Comment by theboy181** [comment]
I noticed that too. Any word on Blink?

**Comment by IDSG** [comment]
Oh nice, it's working fine on EA 978 build, thanks, i know its a workround, hope you finde the right fix

**Comment by ReinUsesLisp** [comment]
Thanks for reporting this.
