### ISSUE TITLE
unimplemented function 'TryPopFromFriendInvitationStorageChannel' (Mini Motor Racing X)

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#4691]
when you go to boot the game it freezes up nearly straight away
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5251285/yuzu_log.zip)
Clan N has the same problem

**Comment by choppymaster** [comment]
Needed for fightcrab

**Comment by choppymaster** [comment]
Used by: 
* PGA tour 2k21
* Spit lings
* Borderlands 2: Game of the Year Edition
