### ISSUE TITLE
Cecconoid 01007A1012852000 pefromance issues

### ISSUE THREAD

**Issue by theboy181** [yuzu-emu/yuzu#4695]
Both Vulkan and OpenGL tested. This game runs really slow no matter what settings are used in yuzu. 

Ryujinx the game is running at full speed (as well as Ryujinx can)

No log, as there was no specific errors or missing settings.

The game is entertaining, but just a good case study for improvement to yuzu.

**Comment by Eloeri** [comment]
Github is for specific issues, not general compat reports. Please mention missing services or unimplemented services in any future issues you report.
