### ISSUE TITLE
Super Mario 3D All-Stars - Mono audio in launcher

### ISSUE THREAD

**Issue by ActualMandM** [yuzu-emu/yuzu#4704]
yuzu Early Access 988

GeForce RTX 2080
Ryzen R9 3950X

The audio in 3D All-Stars's launcher outputs in mono, when it should be outputting in stereo.

[yuzu playback](https://streamable.com/2ukgrf)
[Switch playback](https://streamable.com/kon7h1)

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5272129/yuzu_log.zip)

**Comment by bunnei** [comment]
Probably still relevant, no need to close :)

**Comment by CaptV0rt3x** [comment]
Probably still relevant, no need to close :)

**Comment by german77** [comment]
Fixed by #6567
