### ISSUE TITLE
Kirby Fighters 2 - Crash before Title Screen under Assembly Shaders & Vulkan

### ISSUE THREAD

**Issue by ActualMandM** [yuzu-emu/yuzu#4707]
yuzu 387

GeForce RTX 2080
Ryzen R9 3950X

Kirby Fighters 2 will crash right before the title screen. No setting aside from using GLSL (OpenGL, assembly disabled) changes this behavior. Nothing appears in the log file, but it cuts off at the same spot every time.

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5273200/yuzu_log.zip)

**Comment by v1993** [comment]
I can't reproduce this issue on latest EA build based on git master, so it might have already been fixed:
![Screenshot_20200926_120710](https://user-images.githubusercontent.com/16255906/94337148-fcfe9c80-fff0-11ea-96a4-984b88c9848e.png)
I'm using Linux with GeForce GTX 960. I haven't tried getting into game yet, but title screen and menu work fine.

**Comment by slashiee** [comment]
Just checked, the game works under GLSL only.
<img width="1281" alt="2020-09-26_08-17-34_yuzu" src="https://user-images.githubusercontent.com/15317421/94343956-bef18080-ffd0-11ea-88e4-949f6f8ce0dd.png">

**Comment by Morph1984** [comment]
I'll add my findings here as well:

OpenGL GLSL (assembly shaders off) is the only one that allows this game to go in game. Both GLASM and Vulkan cause this game to crash (with GLASM crashing the NVIDIA driver). However, even with GLSL it seems that it crashes randomly with the success rate being anywhere from 1 to 20%.

Once in game however it works well without issue.

**Comment by v1993** [comment]
I've played it for a bit and can report that game runs very well aside from rare crashes. At boot time a lot of messages are written into log:

```
...
[  44.824186] Debug <Critical> video_core/texture_cache/surface_params.cpp:TextureTypeToSurfaceTarget:40: Unreachable code!
[  44.824187] Debug <Critical> video_core/engines/maxwell_3d.cpp:GetStageTexture:709: Assertion Failed!
[  44.824187] Debug <Critical> video_core/memory_manager.cpp:Read:159: Unreachable code!
[  44.824188] Debug <Critical> video_core/texture_cache/surface_params.cpp:TextureTypeToSurfaceTarget:40: Unreachable code!
[  44.824189] Debug <Critical> video_core/engines/maxwell_3d.cpp:GetStageTexture:709: Assertion Failed!
[  44.824189] Debug <Critical> video_core/memory_manager.cpp:Read:159: Unreachable code!
[  44.824190] Debug <Critical> video_core/texture_cache/surface_params.cpp:TextureTypeToSurfaceTarget:40: Unreachable code!
[  44.824191] Debug <Critical> video_core/engines/maxwell_3d.cpp:GetStageTexture:709: Assertion Failed!
[  44.824191] Debug <Critical> video_core/memory_manager.cpp:Read:159: Unreachable code!
[  44.824192] Debug <Critical> video_core/texture_cache/surface_params.cpp:TextureTypeToSurfaceTarget:40: Unreachable code!
[  44.824193] Debug <Critical> video_core/engines/maxwell_3d.cpp:GetStageTexture:709: Assertion Failed!
[  44.824193] Debug <Critical> video_core/memory_manager.cpp:Read:159: Unreachable code!
[  44.824194] Debug <Critical> video_core/texture_cache/surface_params.cpp:TextureTypeToSurfaceTarget:40: Unreachable code!
...
```
Aside from that, singleplayer under OpenGL runs nearly flawlessly without notable visual glitches. Thanks to extensive autosaving crashes don't pose too much of an issue, so game is well playable.

**Comment by v1993** [comment]
I haven't tested Vulkan, but for me GLASM works more or less ok. It have some crashes and preforms worse than just GL (later is the case for all games for me), but I was able to get in-game and battle.

**Comment by bunnei** [comment]
Probably still relevant, no need to close :)

**Comment by v1993** [comment]
It now crashes before title screen for me as well, but it happens on GLSL too (not caused by BCR).
