### ISSUE TITLE
The Legend of Zelda: Breath of the Wild - Several issues occur when a cinematic plays for the first time.

### ISSUE THREAD

**Issue by Kables07** [yuzu-emu/yuzu#4715]
yuzu Early Access 990

The Legend of Zelda: Breath of the Wild v.1.0.0
DLC 1 & 2 Activated, Not Tested Without
Not Tested on v.1.6.0

NVIDIA GeForce GTX 1080 using drivers 456.38
Intel Core i5-8400
16GB RAM

Description:
Several issues are observed when a cinematic video plays for the first time, such as causing the game to stop rendering forcing the user to reboot the game. The user can reboot the game and get the cinematic to play without any major issues. 

Steps to Reproduce:
1. Launch yuzu EA 990.
2. Boot The Legend of Zelda: Breath of the Wild v1.0.0.
3. Reach a cinematic.
4. Skip the cinematic, causing the game to stop rendering.
5. Stop emulation.
6. Boot the game again.
7. Trigger the same cinematic as step 3.
8. Observe that the cinematic can be heard and subtitles are visible. It is also possible to skip it without any issues.

Observed when the cinematic plays for the first time:
1. No video visible (black screen) (possibly a known issue across all games on yuzu).
2. No audio audible.
3. No subtitles visible.
4. User has the prompt to skip the cinematic but doing so causes the game to stop rendering and NOT doing so causes the game to be stuck on a black screen.

Observed when returning in-game and triggering the same cinematic:
1. No video visible (black screen) (possibly a known issue across all games on yuzu).
2. Audio is audible and plays without any issue.
3. Subtitles are visible.
4. User has the prompt to skip the cinematic. Skipping the cinematic skips as expected. Not skipping the cinematic is fine too, the user returns in-game as expected.

Notes:
- Log was attached.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5279811/yuzu_log.txt)
- Video of the issue occurring attached.
[BOTW_Cinematic_FirstPlay.zip](https://github.com/yuzu-emu/yuzu/files/5279837/BOTW_Cinematic_FirstPlay.zip)
- This issue was reproduced with 4 different cinematics.
- The workaround to this issue works for some cinematics. Upon trying to reproduce the issue one specific cinematic could not be passed at all.

**Comment by G-Spawn** [comment]
Could you please confirm if this happens to you on latest yuzu versions? Feel free to reopen issue if it does & provide new logs.
