### ISSUE TITLE
The Legend of Zelda: Breath of the Wild - Clouds, fog and smoke effects do not animate properly.

### ISSUE THREAD

**Issue by Kables07** [yuzu-emu/yuzu#4716]
yuzu Early Access 990

The Legend of Zelda: Breath of the Wild v.1.0.0
DLC 1 & 2 Activated, Not Tested Without
Not Tested on v.1.6.0

NVIDIA GeForce GTX 1080 using drivers 456.38
Intel Core i5-8400
16GB RAM

Description:
Fog, clouds and smoke effects do not animate properly. The texture will be seen moving in a direction due to wind but then reset at the previous position then start moving again, then reset, etc. causing its animation to loop weirdly.

Steps to Reproduce:
1. Launch yuzu EA 990.
2. Boot The Legend of Zelda: Breath of the Wild v1.0.0.
3. Walk around and observe smoke/fog textures. Observe clouds atop mountains at night too.
4. Observe the texture's animation looping.

Notes:
- Log was attached.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5279872/yuzu_log.txt)
- Videos of the issue occurring attached.
Fog: https://streamable.com/bou43l
Smoke: https://streamable.com/aged4n
Clouds: https://streamable.com/k7obwp
- Seems to occur pretty much anywhere in-game.

**Comment by MysticExile** [comment]
Setting the Accuracy level to 'High' Advanced Settings tab should fix this.

**Comment by MysticExile** [comment]
As for the aforementioned reason, I am closing this issue.
