### ISSUE TITLE
Missing service: StoreOpenContext

### ISSUE THREAD

**Issue by Aushera** [yuzu-emu/yuzu#4725]
Used in:

-Super Mario 3D All-Stars
-XCOM 2 Collection (requires save file to get past the EULA screen)

Mario 3D log:
[Mario3dAllStars_log.txt](https://github.com/yuzu-emu/yuzu/files/5285728/Mario3dAllStars_log.txt)

XCOM 2 log: 
[XCOM2_log.txt](https://github.com/yuzu-emu/yuzu/files/5285734/XCOM2_log.txt)

**Comment by german77** [comment]
Stubbed in #4793
