### ISSUE TITLE
Super Mario Odyssey: Crash when getting back from fish shape

### ISSUE THREAD

**Issue by Innsmouthian** [yuzu-emu/yuzu#4730]
Hello everybody and thanks for the great work,

I've been able to play the game until Lake Kingdom, first episode ('Broodals Over the Lake').

There, when I use the cap to transform Mario in a fish, and then try to become Mario again, the game freezes and Yuzu suddenly closes. I've tried it at least five times just to get the same output.

I'm using Yuzu 393, but I've had the same problem with the three previous builds. I don't know the behaviour of past versions because I started using the emulator one week ago. 

My specs are the following (everything is in its default values):

- Core i7-4790
- Asus Z97-AR
- 16GB DDR3 G.Skill Ripjaws @1866mhz
- WD Black NMVE 256GB (where yuzu is installed **and** the game is stored).
- Asus Geforce GTX 1060 6GB, with the latest 456.55 Nvidia driver (had the same problem with the previous one)

Otherwise, the game runs smoothly, with very minor stutter at the beginning. I suffer the 'light polygons' glitch in the same screen but I understand it is common issue.

If I can be of any other help, please just ask me.

**Comment by Morph1984** [comment]
Please post a log file of the crash

**Comment by BSoDGamingYT** [comment]
If you re using any 1080p mods, please disable them. Also, please post a log file after having encountered the crash as per the instructions on issue posting.

**Comment by Innsmouthian** [comment]
Where can I find the log? My yuzu_log.txt file is blank.
I'm not using any mods.

Thanks.

**Comment by Innsmouthian** [comment]
OK, I just realized that the log gets empty everytime Yuzu is reopened.

Here's the log after the last crash:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5300016/yuzu_log.txt)

**Comment by RodrigoTR04** [comment]
Go to the discord server, will be better able to assist you there @Innsmouthian

**Comment by Innsmouthian** [comment]
> 
> 
> Go to the discord server, will be better able to assist you there @Innsmouthian

Coming!

**Comment by Innsmouthian** [comment]
Solved after:
- Enabling dock mode
- Switching to OpenGL instead of Vulkan
- Creating 20GB Windows pagefile

Thanks again!
