### ISSUE TITLE
Games where rumble does not work

### ISSUE THREAD

**Issue by german77** [yuzu-emu/yuzu#4738]
This is a list to keep track of all know games where rumble does not work.

- **1-2 Switch**: Has multiple vibration at the same time

- **Fast RMX**: No rumble signals, uses ActivateVibrationDevice.
- **Xenoblade Definitive Edition**: No rumble signals.
- **Xenoblade 2**: No rumble signals.

- **Fire Emblem Three Houses**: Sends rumble signals with 0 strength for 1 player.
- **Pinball FX3**: Sends rumble signals with 0 strength for 8 players.
- **Star Wars Pinball**: Sends rumble signals with 0 strength for 8 players.

- **Streets of Rage 4**
- **Hollow Knight**

**Comment by Shoegzer** [comment]
Please add "Star Wars Pinball" as well.

**Comment by BSoDGamingYT** [comment]
1-2 Switch also has no rumble.

**Comment by Its-Rei** [comment]
Hollow Knight

**Comment by gidoly** [comment]
xenoblade deinitive edition / xenoblade 2 / fire emblem three houses

**Comment by gidoly** [comment]
links awakening (fishing minigame)
