### ISSUE TITLE
Legend of Zelda: Breath of the wild: Camera Blur

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#4740]
When using the camera rune to take pictures, most of the time its blurry. Also, for some reason the objects are not recognised when using the camera which makes some missions impossible.

For example:
Here it doesnt recognise the apple.

![01007ef00011e000_2020-10-01_13-39-57-626](https://user-images.githubusercontent.com/51413997/94799622-138b6600-03ec-11eb-95ef-e65cbf75003c.png)

![01007ef00011e000_2020-10-01_13-43-43-641](https://user-images.githubusercontent.com/51413997/94799665-230aaf00-03ec-11eb-8abd-ea1a4baffd2b.png)

Log File (if it helps):
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5311297/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
Use normal GPU accuracy

**Comment by EliasM108** [comment]
> Use normal GPU accuracy

Thank you, it worked. But if it is a bug, please reopen it.
