### ISSUE TITLE
Xenoblade Chronicles 2 Textures issue

### ISSUE THREAD

**Issue by XeroZen** [yuzu-emu/yuzu#4743]
![Snapshot_20-10-03_09-34-59](https://user-images.githubusercontent.com/67195657/94982916-14dba080-055c-11eb-95a8-261080529e43.png)
![Snapshot_20-10-03_09-35-46](https://user-images.githubusercontent.com/67195657/94982922-1dcc7200-055c-11eb-8100-d23a314a8719.png)
![Snapshot_20-10-03_09-36-24](https://user-images.githubusercontent.com/67195657/94982924-23c25300-055c-11eb-867d-8a3a9dc998f5.png)

The textures for Xenoblade chronicles 2 is not working properly, although there is no crash the game is not in a playable state.
This issue persists on both opengl and vulkan api.
Pc specs: R5 3600, Vega 64, 32gb RAM
Amd driver version: 20.9.2
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5315898/yuzu_log.txt)

**Comment by german77** [comment]
Can you upload an example with log. I have been playing 10+ hours with only crashes between menus.

**Comment by XeroZen** [comment]
I have only just started the game, but there are graphical issues, more in vulkan compared to ogl. Hope you can tell me your specs.

**Comment by Zhao-Qi** [comment]
Try to use High or Extreme accuracy mode, it should reduce the texture stretch issue @XeroZen 

![image](https://user-images.githubusercontent.com/8041059/94983988-28134f80-050d-11eb-9466-a34efb9d41fc.png)

**Comment by XeroZen** [comment]
> 
> 
> Try to use High or Extreme accuracy mode, it should reduce the texture stretch issue @XeroZen
> 
> ![image](https://user-images.githubusercontent.com/8041059/94983988-28134f80-050d-11eb-9466-a34efb9d41fc.png)

I have already tried using both high and extreme accuracy level, but still the same.

**Comment by Zhao-Qi** [comment]
Looks like this is related to hardware @XeroZen. Mine is Nvidia 2060s with i5-8259u. Initially had the similar issue but after switching it to High accuracy level the issue has been gone.

I've played XB2 for about 60 hours from start to finish. There were very few graphics issues for me, but I had audio issues frequently when in battles. To avoid random crashes, I had to lock my yuzu to v374.

**Comment by XeroZen** [comment]
> Looks like this is related to hardware @XeroZen. Mine is Nvidia 2060s with i5-8259u. Initially had the similar issue but after switching it to High accuracy level the issue has been gone.
> 
> I've played XB2 for about 60 hours from start to finish. There were very few graphics issues for me, but I had audio issues frequently when in battles. To avoid random crashes, I had to lock my yuzu to v374.

Maybe this problem is associated with only amd GPUs. I just hope vulkan for amd will be optimised soon, since for opengl the graphics are ok but fps is very low and hence unplayable.

**Comment by XeroZen** [comment]
The Same problem occurs in Xenoblade chronicles definitive edition.
Here is a screenshot
![Snapshot_20-10-05_09-46-17](https://user-images.githubusercontent.com/67195657/95039987-f5757c80-06ef-11eb-8c26-009203af7573.png)

**Comment by choppymaster** [comment]
Does this fix in TCR?

**Comment by Morph1984** [comment]
This issue has been reported to be fixed, closing.
