### ISSUE TITLE
Xenoblade Chronicles 2 (torna golden country) - Foot prints do not render properly

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#4748]
switch:
![2020100211244300-4CBEE39065EC88984BABA68A511DDD19](https://user-images.githubusercontent.com/66776795/94887935-83642400-04b2-11eb-8dd2-4b42e2ff0129.jpg)
yuzu:

<img width="960" alt="0100c9f009f7a000_2020-10-02_12-33-13-013" src="https://user-images.githubusercontent.com/66776795/94888117-0c7b5b00-04b3-11eb-8202-94012c094f93.png">

xenoblade 2 games have minor issue that did not render foot print properly
my hardware is i7 8700k 16gb ram 2080s driver version 456.55
here is the log:
[foot print log.txt](https://github.com/yuzu-emu/yuzu/files/5315975/foot.print.log.txt)

**Comment by Zhao-Qi** [comment]
I have the same issue in the main Xenoblade 2 game as well. Yuzu v374, OpenGL, Nvidia 2060s
![image](https://user-images.githubusercontent.com/8041059/94888428-b66cd000-043e-11eb-84b4-88110c43f90e.png)
