### ISSUE TITLE
Pokémon Mystery Dungeon: Rescue Team DX - Graphics issue

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#4750]
switch:
![2020100211225400-A5A477B869AFD225B3DAF74249D70FF2](https://user-images.githubusercontent.com/66776795/94888387-e3a79580-04b3-11eb-9905-3fb11da68abf.jpg)
yuzu:

<img width="960" alt="01003d200baa2000_2020-10-02_12-27-36-592" src="https://user-images.githubusercontent.com/66776795/94888396-ed30fd80-04b3-11eb-9dd0-235e1a8e4edb.png">

there is minor graphic glitch when selecting pokemon 
my hardware is i7 8700k 16gb ram 2080s driver version 456.55
here is the log:
[mystery dungeun.txt](https://github.com/yuzu-emu/yuzu/files/5316004/mystery.dungeun.txt)

**Comment by gidoly** [comment]
it is solved thanks to texture cache rewrite

**Comment by slashiee** [comment]
The issue should stay open until the PR is merged to master.
