### ISSUE TITLE
Xenoblade Chronicles definitive edition - Shadows not rendered properly

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#4752]
switch:
![2020100212375100-8625352D7931559E8BE3042D46DE9738](https://user-images.githubusercontent.com/66776795/94888574-85c77d80-04b4-11eb-8eff-46ff0de4db41.jpg)
yuzu:

<img width="960" alt="0100ff500e34a000_2020-10-02_12-12-35-253" src="https://user-images.githubusercontent.com/66776795/94888587-95df5d00-04b4-11eb-8dc6-fbd2958c1b7c.png">

xenoblade definitive edition and other xc title have graphic glitch like this 
my hardware is i7 8700k 16gb ram 2080s driver version 456.55
here is the log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5316018/yuzu_log.txt)

**Comment by Zhao-Qi** [comment]
Similar issues here #2771, my hardware is i5-8259u 2060s OpenGL.

**Comment by gidoly** [comment]
fixed thanks to shader decompiler rewrite
