### ISSUE TITLE
Yuzu not responding when i try to play a game

### ISSUE THREAD

**Issue by Darmix4707** [yuzu-emu/yuzu#4753]
I'm trying to load pokemon sword but every time i go to load the file the emulator frezes.
Hoping for help plz
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5316027/yuzu_log.txt)

**Comment by renA21** [comment]
Sorry but we have a couple of problems here:

- This place is for developers to track issues, not a support forum.
- We do not support piracy. Support will not be given if your copy hasn't been legally obtained.

**Comment by Darmix4707** [comment]
I think it's ok because i bought it for switch and so i feel like i've already supported the developers

**Comment by renA21** [comment]
Technically it is not. You've obtained an illegal copy from a third party source -- that is someone else's copy of the game, not yours. In order to obtain a legal copy of the game, you're required to have a hackable Nintendo Switch to transfer it to your computer.
