### ISSUE TITLE
Controller Rumble Issue

### ISSUE THREAD

**Issue by Cavermendes** [yuzu-emu/yuzu#4760]
I don't know if this is an issue with Yuzu or me just not knowing how to configure controls. I've gotten all my controllers working perfectly, everything except the rumble. For some reason Yuzu will only vibrate one controller for everything. In Smash, I have 2 Xbox 360 controllers set up and ready to go, and another 2 Gamecube controllers for a total of 4. Any time a character is chosen or any character dies, only one controller vibrates for every event. Like player 1 will rumble every time for any reason instead of the actual controllers stuff is happening to. Player 3 dies? Player 1 rumbles. Player 2 picks character? Player 1 rumbles. And the other controllers don't vibrate at all. I've tested both Xbox controllers and they rumble just fine. Gamecube is still a work in progress. Still, even if they weren't working, then no controllers should rumble at all, instead of just the one for all the others. Is there some setting I've missed? Will close this if so.

**Comment by Its-Rei** [comment]
That is normal and a current limitation of the implementation. Rumble will currently only work for one device.

**Comment by Cavermendes** [comment]
Hey, thanks for the answer man. Happy to know I wasn't just being an idiot hahaha. I couldn't find any other topics about this on github so maybe we should leave this open, as I'm sure this is something the developers might want to fix in the future.

**Comment by v1993** [comment]
PR #4762 should address this issue.

**Comment by Cavermendes** [comment]
Awesome. Thank you guys for all you do. Should be working now? I'm not home so I can't test it for myself.

**Comment by v1993** [comment]
@Cavermendes No, said PR wasn't merged or marked for EA builds yet, so official builds don't have this fixed as for now.

**Comment by Cavermendes** [comment]
Good to know, still, it looks like as soon as it's merged it should be fixed, so I'll close this.
