### ISSUE TITLE
[EA 978+][Nvidia][OGL] huge performance loss independent of Vsync option [invalid - causes by G-Sync settings]

### ISSUE THREAD

**Issue by Aris-t2** [yuzu-emu/yuzu#4767]
EA 976 - performance is fine: ~60 FPS
EA 978(-10xx) - performance is heavily reduced: 25 FPS (same games)

Using: OpenGL - Async - Multicore - Dock

Nvidia driver:  **456.71** WHQL on a RTX 2070

Happens with both Vsync enabled and disabled in Yuzu and/or in Nvidia settings:
Nvidia Vsync On - Yuzu On/Off
Nvidia Vsync Off - Yuzu On/Off

Reduced performance (EA 976->978+):
Mario Kart 8 Deluxe - 25 FPS
Mario Tennis Aces - 25 FPS
MARIO & SONIC AT THE OLYMPIC GAMES TOKYO 2020 - 25 FPS
New Super Mario Bros. U Deluxe - 25 FPS
SUPER MARIO ODYSSEY - 25 FPS
ULTRA STREET FIGHTER™ II The Final Challengers - 25 FPS

Identical performance (EA 976->978+):
Panzer Dragoon: Remake ~60 FPS

Whatever happened in or with https://github.com/yuzu-emu/yuzu/pull/4692, https://github.com/yuzu-emu/yuzu/pull/4688, https://github.com/yuzu-emu/yuzu/issues/4687 seems to be responsible for the issue, because the issue is not present in EA 976 using the same drivers and config.

Other settings, that have no effect on the results:
Speed limit: 100%, 200%, unlimited
CPU Accuracy; Accurate, Unsafe
Assembly shaders / async shader building

**Comment by BSoDGamingYT** [comment]
Are you saying the driver introduced these issues or is it a problem in yuzu? Did you test on different drivers?

**Comment by Aris-t2** [comment]
Not sure about the driver 456.71, but the issue does not occur on EA 976 using the same driver. Can anybody confirm?

**Comment by Aris-t2** [comment]
The issue is indeed caused by the Nvidia driver and its G-Sync settings.
Using the option to apply G-Sync to "window and fullscreen" causes the performance cut.
Keeping the default one there set to "fullscreen only" resolves the problem.

OK, this can be closed.

**Comment by Morph1984** [comment]
Please close the issue if it can be closed
