### ISSUE TITLE
ARMS "Winner" Screen is black.

### ISSUE THREAD

**Issue by shukenmg** [yuzu-emu/yuzu#4776]
Using YUZU 403 e4fee37
CPU i7-8700k 
GPU GTX 1060 6G || Nvidia driver version 456.71
Tested with ARMS 1.0.0 and 5.4.0

The ARMS "Winner" Screen is black.
This is what displays.
![image](https://user-images.githubusercontent.com/18000205/95646803-a4ee8c80-0afe-11eb-9934-5fd736be334f.png)
There normally is a cutscene where the character does a pose.
Like this https://youtu.be/IRUU_t9poe0?t=416 at 6:56.

These are the settings used for the game.
Multicore = True
Graphics:
 ![image](https://user-images.githubusercontent.com/18000205/95646881-5f7e8f00-0aff-11eb-9004-1674181189a9.png)

Adv. Graphics:
 ![image](https://user-images.githubusercontent.com/18000205/95646876-5097dc80-0aff-11eb-8e6d-27cea5e08cd4.png)

Addons:
 ![image](https://user-images.githubusercontent.com/18000205/95646891-7a510380-0aff-11eb-9b6a-e379198d4963.png)

YUZU log:
 https://drive.google.com/file/d/1DRL1X3DmKm5acoK5zcWGjxxShtM6K7Ae/view?usp=sharing
YUZU GPU log:
 https://drive.google.com/file/d/1bDv8TmVpJBlWgli_c528sijfOMoB4EZ6/view?usp=sharing

**Comment by G-Spawn** [comment]
Please feel free to reopen issue should this still happen to you on latest yuzu versions.
