### ISSUE TITLE
Zelda Breath of the Wild Crashes Randomly when using the Camera

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#4777]
The game itself plays great, but sometimes when i unpause the game and quickly open the camera it crashes. Most of the times it is just random while just playing and opening the camera. The log below contains the crash while in "Lanayru Great Springs" and just opening the camera.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5360863/yuzu_log.txt)

**Comment by Ghostotakoi** [comment]
@EliasM108  I know this is a bug and devs should investigate it, but since you are playing on PC why you just don´t take a screenshot instead?

**Comment by EliasM108** [comment]
> @EliasM108 I know this is a bug and devs should investigate it, but since you are playing on PC why you just don´t take a screenshot instead?

The camera is an essential aspect of the game, many side quest depend on taking pictures of places and it also helps the player log mobs and items to easily search for them.

**Comment by Ghostotakoi** [comment]
@EliasM108 I know, I have already beat the game on CEMU where it run flawless, but as you said the camera is mainly for side quest, the only main quest I remember that require a camera was at Impa´s lab. IDK if there will be a fix for that issue soon tho, but you can try to avoid all camera related quest for now until it is fixed, you still have plenty more quest to do meanwhile.

**Comment by choppymaster** [comment]
The latest commit in the #4967 states that it fixes this.

**Comment by EliasM108** [comment]
its fixed

**Comment by choppymaster** [comment]
But this issue is not be closed as it is not merged on mainline. @EliasM108

**Comment by EliasM108** [comment]
> But this issue is not be closed as it is not merged on mainline. @EliasM108

reopening till it gets merged into the mainline.

**Comment by Morph1984** [comment]
The aforementioned PR has been merged, closing.
