### ISSUE TITLE
SSBU 9.0 - Incorrect rendering of some textures (too pixelated)

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#4789]
Certain textures in SSBU are rendering more pixelated than is accurate. Specifically, when using Steve in SSBU, crafting to make gold tools or iron tools, and the down tilt attack is rendering incorrectly. The gold ingot is not pictured, but it is similar to the iron ingot pictures below. Reproduced on both Vulkan and OpenGL backends.

yuzu:
![Screenshot_2020-10-13_22-27-12](https://user-images.githubusercontent.com/22451773/95938051-0fc1f100-0da7-11eb-8098-2da6c6bc7b55.png) ![Screenshot_2020-10-13_22-27-12_2](https://user-images.githubusercontent.com/22451773/95938052-105a8780-0da7-11eb-8fc5-1a4f24546f2f.png)

Switch:
![2020101322413200-0E7DF678130F4F0FA2C88AE72B47AFDF_crop](https://user-images.githubusercontent.com/22451773/95938063-19e3ef80-0da7-11eb-9f46-e56ad2277032.jpg) ![2020101322420200-0E7DF678130F4F0FA2C88AE72B47AFDF_crop](https://user-images.githubusercontent.com/22451773/95938065-19e3ef80-0da7-11eb-8452-170e57e8c80d.jpg)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5375351/yuzu_log.txt)

Requires SSBU update 9.0 and Challenger Pack 7 DLC to reproduce.

**Comment by benderscruffy** [comment]
is this still an issue ???

**Comment by TheEmacc** [comment]
Yes this is still an issue on update 13.0.1 with all DLC

**Comment by TheEmacc** [comment]
![01006a800016e000_2023-03-10_15-15-39-431](https://user-images.githubusercontent.com/127462926/224446239-a89f9d4b-f4ff-452c-97e7-8ed4a8f4b74f.png)
![01006a800016e000_2023-03-10_15-17-01-618](https://user-images.githubusercontent.com/127462926/224446266-eaad5d96-1acf-4568-8496-4b0e1b8b2c1f.png)

**Comment by gidoly** [comment]
appears to fixed on last mainline

https://github.com/yuzu-emu/yuzu/assets/66776795/f8abdd42-7bf7-4aee-8338-82d94a2674ef
