### ISSUE TITLE
Yuzu Crashes on every game during loading screen after EA 1030

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#4794]
Tried EA 1032 and 1033 and both load shaders normally, but suddenly crash on "loading" screen. Apparently, EA 1030 works fine, so something in the newer builds caused this.

Log while loading Breath of the Wild on EA 1033:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5383716/yuzu_log.txt)

**Comment by iDekuNut** [comment]
Are you able to open the configure menu still?

**Comment by EliasM108** [comment]
> Are you able to open the configure menu still?

Now that you mentioned it, i checked the yuzu configuration and it displays everything correctly but then it freezes and crashes.

**Comment by iDekuNut** [comment]
try removing your qt-config from the folder and then try booting a game, if it works then yeah Its a weird bug when you update it breaks your config I had this problem yesterday

**Comment by EliasM108** [comment]
> try removing your qt-config from the folder and then try booting a game, if it works then yeah Its a weird bug when you update it breaks your config I had this problem yesterday

I deleted the qt-config file, re-set the config as it was before and there was no problem until i enabled boxcat, then it crashed again. If everything is fine and enabling boxcat is crashing yuzu, then the problem is boxcat, thats my theory.

**Comment by JMVS** [comment]
> 
> 
> > try removing your qt-config from the folder and then try booting a game, if it works then yeah Its a weird bug when you update it breaks your config I had this problem yesterday
> 
> I deleted the qt-config file, re-set the config as it was before and there was no problem until i enabled boxcat, then it crashed again. If everything is fine and enabling boxcat is crashing yuzu, then the problem is boxcat, thats my theory.

Yuzu Mainline 411. Had this same problem with every game I tried. Disabling boxcat fixed the problem (no need to delete qt-config file in my case).

**Comment by FearlessTobi** [comment]
Is this fixed now?

**Comment by EliasM108** [comment]
> Is this fixed now?

no, still with boxcat enabled no game goes past the yuzu loading screen, except mario odyssey, which displays safety controls and then crashes, I am currently using EA 1041.

**Comment by german77** [comment]
A reminder to close the issue if fixed or upload a new log with latest mainline

**Comment by GlassICE** [comment]
> try removing your qt-config from the folder and then try booting a game, if it works then yeah Its a weird bug when you update it breaks your config I had this problem yesterday

It worked for me thanks alot
I have no idea why Yuzu was crashing after update and opening every game
However i have to reconfig the games n stuff again though

**Comment by G-Spawn** [comment]
Feel free to reopen issue and provide log from latest yuzu should this still happen to you. Closing issue to hopefully prompt action from OP user.
