### ISSUE TITLE
Important stutter caused by vibration fonction

### ISSUE THREAD

**Issue by backgamon** [yuzu-emu/yuzu#4800]
Hi,

I suffer heavy stuttering since a few versions of Yuzu, it doesn't happen before...but now it's very annoying.

Latest working version for me are Yuzu 393:

https://www.youtube.com/watch?v=VtZiN2AG1Go

Since 394 stutter happen:

https://www.youtube.com/watch?v=KlXyhlVN3oo
-> The sound on video are wrong, but it work when playing (it's from shadowplay recording).

->Just checked rev.411 and it's worst :( 

Windows 10 x64 Pro[19041.572]
I78700k@4.7Ghz
32Gb DDR4 Gskill Trident Z RGB 3466Mhz@XMP3200Mhz
Gigabyte 2070 RTX 8G OC[456.71]
LOG:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5395756/yuzu_log.txt)

EDIT:
A user on discord solved my issue:
Must disable all vibration function on the controller tab, i unchecked motion too.

**Comment by BSoDGamingYT** [comment]
This issue should not be closed. You should note that vibration causes slowdowns and reopen it
