### ISSUE TITLE
Vigil: The Longest Night- Only saves at main menu

### ISSUE THREAD

**Issue by german77** [yuzu-emu/yuzu#4803]
This game only creates a save file if it's on the main menu. Inside the game auto-saves and user-saves don't modify the save file, even if it was deleted. No stubbed, error functions from FS are called when saving the game.

If you go to the main menu while you are in game it will always create or modify the save file.

The game has no problem reading the save files.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5398239/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
Please still provide a log file for this problem.
