### ISSUE TITLE
Yuzu not booting

### ISSUE THREAD

**Issue by Ning1253** [yuzu-emu/yuzu#4810]
I mean there isn't more to this than the title - I have all the dependencies, I installed (and reinstalled, and updated,) yuzu via the official website and launched it from the icon in Windows. It opens the maintenance tool, runs it completely successfully (the maintenance log finishes on "now launching /path/to/yuzu.exe" (where the path is the correct path to the yuzu exe) ), and then does nothing - looking at task manager the yuzu task opens and instantly terminates, without displaying any errors, messages etc. No other app on my PC does this, and I'm running the latest windows update. If it helps when there was still yuzu nightly and yuzu canary, I remember that whichever was the non preview version behaved in the same way, but the preview/snapshot version worked correctly...

**Comment by goldenx86** [comment]
Confirm that no USB gamepad, antimalware giving a false positive, or screen recording software (besides OBS or GPU driver based ones) are bothering.

**Comment by Ning1253** [comment]
Ok so when I unplugged my Wii U Pro Controller adapter, it booted. Is there a reason why it does not boot if a controller is connected?

**Comment by FearlessTobi** [comment]
Yes, we've had this issue with certain third-party controllers in the past.
I think this a problem in SDL or libusb and not yuzu.

**Comment by german77** [comment]
I found the exact place that makes yuzu not boot. 
It's caused by this function `libusb_get_device_list(libusb_ctx, &devices);` on the GC adapter. I'm looking for a fix.

**Comment by german77** [comment]
I included the fix in #4781
