### ISSUE TITLE
All rumble is directed to controller 0

### ISSUE THREAD

**Issue by MastaG** [yuzu-emu/yuzu#4818]
Hi I'm on the latest EA build of Yuzu with a very nice new gui for setting up the controllers.
I'm using 4 xbox 360 controllers and they were mapped to 4 Pro Controllers by just selecting Xinput 0-3 for each tab.

Now they all 4 of them work correctly for each player.. but the rumbling from all 4 controllers are directed to the first one.
So player 1 gets the rumble effects from itself and the other 3 as well.

I'm running it on Windows 10 btw.

**Comment by german77** [comment]
That's a know problem. It will be fixed "soon"

**Comment by MastaG** [comment]
Alright, thanks for the heads up.
