### ISSUE TITLE
SSBU only 1.0 works

### ISSUE THREAD

**Issue by MastaG** [yuzu-emu/yuzu#4819]
I'm on the latest Yuzu EA and I got SSBU working (after browsing this issue tracker and finding out I had to disable the boxcat thing.. else Yuzu simply closes after opening the game).

Now I have a problem with it.
When Update 7.0 or 9.0 are enabled, the game will get me a black screen after selecting Smash in the main menu.
Music keeps playing but I'm stuck.

When I disable the update and play the base version (1.0) it works and I can select a profile after hitting "Smash".

Enabling/disabling DLC or removing save files doesn't help here.

Any workaround for this?
I'd like to play the updated version.

**Comment by renA21** [comment]
This place is a issue tracker for developers. Other users are able to boot update 9.0.0, so I suggest to request for user support at our [Discord server](https://discord.gg/u77vRWY) or [yuzu forums](https://community.citra-emu.org/c/yuzu-support).

**Comment by MastaG** [comment]
Aight.
