### ISSUE TITLE
Animal Crossing New Horizons crash when opening customize furniture menu

### ISSUE THREAD

**Issue by DanMossa** [yuzu-emu/yuzu#4823]
Yuzu: ea20b5c970cb261df93743803a227fafd5403d02

Can't progress in Animal Crossing New Horizons when working on the customize furniture tutorial and the menu opens

This is my log:
https://discord.com/channels/398318088170242053/476077620350418964/769243951747170397

GPU: RX 580 8gb
CPU: Ryzen 5 3600
RAM: 16gb
Swap File: 25.43 GB
Using Vulkan

**Comment by lat9nq** [comment]
Duplicate of #4821

**Comment by Anakinzinnnn** [comment]
same thing here, is there any solution?

**Comment by yanis404** [comment]
same thing is happening to me :( im not able to customize
