### ISSUE TITLE
Pokémon shield dlc freeze

### ISSUE THREAD

**Issue by Hayatoeevee** [yuzu-emu/yuzu#4825]
my pokémon shield everytime i enter in a dlc area (isle of armor or crown of tundra) after a little while playing, the emulation stops and the fps drops to 0.

version: early access 1062

GeForce GTX 1050 Ti
Intel core i5 2400 3.10GHz
Windows 10
8gb ram
64-bit Operating System

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5434139/yuzu_log.txt)

**Comment by Hayatoeevee** [comment]
![yuzu Early Access 1062 _ 3BD378582831B509D186D9F43A220FF0 nca 25_10_2020 00_54_01](https://user-images.githubusercontent.com/73413983/97098546-d28a1880-165c-11eb-9d04-53785bf6366d.png)

**Comment by Koen1999** [comment]
Your title suggests that this issue does not occur without the DLC. Is this true?

**Comment by adamantinum** [comment]
Hi, I'm writing because I have the same issue and I was searching for solutions. 
The issue occurs accessing in some areas of the DLC map or loading the game if I have saved in any area inside DLC map, in other cases the game works properly.
I hope it could be useful.

**Comment by aecarvalho** [comment]
My issue is worse, right after facing the girl outside the Isle of Armor station the whole thing freezes to absolute zero. Have to restart the PC to fix it.

**Comment by gidoly** [comment]
close due to ditto
