### ISSUE TITLE
nvdec: Video rendering stops before the video ends

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#4841]
Videos apparently stop rendering before the video ends. Unknown if this applies to only certain videos or all videos, but in the following cuts it is quite visible that the video is not being entirely rendered. FE:TH is VP9. Joker's FS in SSBU is H.264.

*The following list is not meant to be exhaustive, only demonstrative.*

On Switch (apologies for lacking capture setup):
FETH: https://streamable.com/dc7j6k
SSBU: https://streamable.com/fhsp73

On yuzu:
FETH: https://streamable.com/dek2kj
SSBU: https://streamable.com/6ogull

SSBU log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5443909/yuzu_log.txt)

**Comment by ameerj** [comment]
Fixed by #4996 and #5002
