### ISSUE TITLE
Feature Request: Restart game without reloading shaders

### ISSUE THREAD

**Issue by KostaSaizo7** [yuzu-emu/yuzu#4843]
Yuzu in its current state softlocks in some games and the game must be restarted. Restarting the game and having to wait for the shaders to load again, can be annoying. I wonder if it is possible to add an option in the UI like "Restart (without reloading shaders)".

**Comment by BSoDGamingYT** [comment]
Such an option would likely introduce more issues than it would solve.

**Comment by FearlessTobi** [comment]
I agree with BSoD here. If you don't want your shader cache to be used, you can always disable it in the settings.
I don't think there needs to be another UI option for this, especially because playing without a cache results in a far inferior experience.
