### ISSUE TITLE
Implement GetAvailableLanguageCodes2 [Request]

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#485]
## Hardware Specs : 
- Nvidia GeForce GTX 960
- Intel I7-7700K @ 4.5Ghz
- 8 GB Of Ram 3200Mhz
- Windows 10 Pro

## The issue : 
When you launch Kirby Star Allies yuzu crash with the error "Unimplemented function GetAvailableLanguageCodes2".
Also i can't give you a log because if I do "yuzu.exe 2> log.txt" on cmd it give me nothing

**Comment by mailwl** [comment]
request to close
