### ISSUE TITLE
Textures Formats to implement and decode [Request]

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#486]
Here is the list of the textures to implement and decode all textures formats checked have been already implemented and decoded : 
- [X] R32_G32_B32_A32
- [X] R32_G32_B32
- [X] R16_G16_B16_A16
- [X] R32_G32
- [ ] R32_B24G8
- [ ] ETC2_RGB
- [ ] X8B8G8R8
- [X] A8B8G8R8
- [X] A2B10G10R10
- [ ] ETC2_RGB_PTA
- [ ] ETC2_RGBA
- [X] R16_G16
- [ ] G8R24
- [ ] G24R8
- [X] R32
- [X] BC6H_SF16
- [X] BC6H_UF16
- [ ] A4B4G4R4
- [ ] A5B5G5R1
- [X] A1B5G5R5
- [X] B5G6R5
- [ ] B6G5R5
- [X] BC7U
- [X] G8R8
- [ ] EAC
- [ ] EACX2
- [X] R16
- [ ] Y8_VIDEO
- [X] R8
- [ ] G4R4
- [ ] R1
- [ ] E5B9G9R9_SHAREDEXP
- [X] BF10GF11RF11
- [ ] G8B8G8R8
- [ ] B8G8R8G8
- [X] DXT1 
- [X] DXT23 
- [X] DXT45
- [X] DXN1
- [ ] DXN2
- [X] Z24S8
- [ ] X8Z24
- [ ] S8Z24
- [ ] X4V4Z24__COV4R4V
- [ ] X4V4Z24__COV8R8V
- [ ] V8Z24__COV4R12V
- [X] ZF32
- [X] ZF32_X24S8
- [ ] X8Z24_X20V4S8__COV4R4V
- [ ] X8Z24_X20V4S8__COV8R8V
- [ ] ZF32_X20V4X8__COV4R4V
- [ ] ZF32_X20V4X8__COV8R8V
- [ ] ZF32_X20V4S8__COV4R4V
- [ ] ZF32_X20V4S8__COV8R8V
- [ ] X8Z24_X16V8S8__COV4R12V
- [ ] ZF32_X16V8X8__COV4R12V
- [ ] ZF32_X16V8S8__COV4R12V
- [X] Z16
- [ ] V8Z24__COV8R24V
- [ ] X8Z24_X16V8S8__COV8R24V
- [ ] ZF32_X16V8X8__COV8R24V
- [ ] ZF32_X16V8S8__COV8R24V
- [X] ASTC_2D_4X4
- [ ] ASTC_2D_5X5
- [ ] ASTC_2D_6X6
- [X] ASTC_2D_8X8
- [ ] ASTC_2D_10X10
- [ ] ASTC_2D_12X12
- [X] ASTC_2D_5X4
- [ ] ASTC_2D_6X5
- [ ] ASTC_2D_8X6
- [ ] ASTC_2D_10X8
- [ ] ASTC_2D_12X10
- [X] ASTC_2D_8X5
- [ ] ASTC_2D_10X5
- [ ] ASTC_2D_10X6

**Comment by Dantttt** [comment]
Please Update!

**Comment by greggameplayer** [comment]
@Dantttt it's normally updated

**Comment by Dantttt** [comment]
the two texture formats required by arms are not in

On Sep 15, 2018 23:55, "greggameplayer" <notifications@github.com> wrote:

@Dantttt <https://github.com/Dantttt> it's normally updated

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yuzu-emu/yuzu/issues/486#issuecomment-421641408>, or mute
the thread

**Comment by Dantttt** [comment]
Add ASTC 8X8

**Comment by greggameplayer** [comment]
@Dantttt they are in #1092

**Comment by Hexagon12** [comment]
This issue / request is nonsensical, since we only implement new texture formats only if we see games using them for something.
