### ISSUE TITLE
Blocky ground texture in Hyrule Warriors: Age of Calamity (Demo) on Turing

### ISSUE THREAD

**Issue by MysticExile** [yuzu-emu/yuzu#4861]
As stated in the title, Hyrule Warriors: Age of Calamity (Demo) [0100A2C01320E000] has a graphical glicth occuring on Turing GPU's only. This only happens with GLSL (not ARB/GLASM). Here is a comparison between Turing and Pascal.

* Turing
![Capture](https://user-images.githubusercontent.com/30736337/97566365-bc76b200-19e6-11eb-8057-78398d661f71.PNG)

* Pascal
![AOC_Pascal_Ground](https://user-images.githubusercontent.com/30736337/97566587-cac4ce00-19e6-11eb-9162-4bd1aaa60704.png)

**Comment by G-Spawn** [comment]
This shouldn't happen anymore with the new compiler. If it does please reopen the issue - post another log on updated yuzu.
