### ISSUE TITLE
unmapped read errors with many 0 Byte files inside LayeredFS

### ISSUE THREAD

**Issue by Hinkiii** [yuzu-emu/yuzu#4870]
If a single or even combination of mods or even updates makes the total number of files patched through PatchRomFS exceeds ~900 files it causes random instabilities and unmapped read errors for modified files.

CPU: Ryzen 7 3700x
Memory: 16GB DDR4 3400Mhz
GPU: GTX 970

Tested this on 3 systems all had the same issue.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5463306/yuzu_log.txt)

**Comment by Hinkiii** [comment]
Could be related to how the files are 0 Bytes size on disk but 20 bytes in size, does vmm allocate based off logical or physical size

**Comment by ain-soph** [comment]
I'm not quite sure. But you can try putting firmware NCA files in [yuzu_folder]\nand\system\Contents\registered.
That solve the error `HW.Memory <Error> core\memory.cpp:Read:644: Unmapped Read8` for me.
See the original post at
[Problems with no words displayed in games](https://community.citra-emu.org/t/problems-with-no-words-displayed-in-games/154734)

**Comment by Hinkiii** [comment]
Didn't work for me when I tried previously
