### ISSUE TITLE
Crashes During Gameplay - Hyrule Warriors AoC 

### ISSUE THREAD

**Issue by BSoDGamingYT** [yuzu-emu/yuzu#4871]
On Early Access (1088) you can get into gameplay, but upon attacking enemies, the game will force crash the emulator. 

Another issue with this title occurs when you enter the character screen in the mission select screen. GPU usage spikes to 100%, causing system a deadlock. Enclosed is a save to easily reproduce both issues

Game Save
[svdt.zip](https://github.com/yuzu-emu/yuzu/files/5465991/svdt.zip)

Log from in gameplay enemy fighting crash
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5465996/yuzu_log.zip)

System Tested:
i7 10700k
GTX 1080ti (Driver 456.80)

**Comment by YuNarukamii** [comment]
Just uncheck use assembly shaders at Adv. Graphics

**Comment by YuNarukamii** [comment]
And with char crash you need to use ryunijx to change chars
1. Copy Savefile from Yuzu to ryunijx (data name= svtd)
2. Start the Game at ryunijx
3. Change and Manage Chars
4. Save Game
5. Copy Savefile from ryunijx to Yuzu
if you dont want to use ryunijx you need to wait until they patch the EA build thats the only thing what you can do now

**Comment by Moonlacer** [comment]
@BSoDGamingYT This should be fixed with Hades, right? I haven't experienced any crashes since

**Comment by Jaizu** [comment]
I had a few crashes with Vulkan and latest yuzu. Let me know where I can find the logs to share them if they are helpful.
