### ISSUE TITLE
Multicore crashes in Pokémon Sword and Shield

### ISSUE THREAD

**Issue by RodrigoTR04** [yuzu-emu/yuzu#4875]
Users experience crashes related to the multicore feature in multiple places while playin Sword and Shield, currently known spots are the ones listed below:

Talking to the digging duo,
Playing the lottery in Pokémon centers,
Inserting a wishing piece in a well,
Fighting the champion Leon,
Entering the Dynamax adventures in Max Lair (Crown Tundra)

Zipped below are included logs for all these crashes, save files to help them be replicated, also included instructions to beat Leon faster and digging duo, save files are included for both Sword and Shield version of the game, their save files are not compatible between versions. Tested primarily with Early Access 1062

[Pokémon Sword and Shield logs and save files.zip](https://github.com/yuzu-emu/yuzu/files/5468377/Pokemon.Sword.and.Shield.logs.and.save.files.zip)
![Loto-ID](https://user-images.githubusercontent.com/65554156/97768966-c3481680-1b05-11eb-9af3-7fce547e30a2.PNG)
![Wishing well](https://user-images.githubusercontent.com/65554156/97768967-c511da00-1b05-11eb-9010-c42cb61e2194.PNG)
![Digging duo](https://user-images.githubusercontent.com/65554156/97768970-c7743400-1b05-11eb-8a52-13d8b7f579d5.PNG)
![Leon fight](https://user-images.githubusercontent.com/65554156/97768971-c93df780-1b05-11eb-8f1c-fd4b70de3f90.PNG)
![Dynamax adventures](https://user-images.githubusercontent.com/65554156/97768973-ca6f2480-1b05-11eb-9576-093d9ee9d319.PNG)

**Comment by ogniK5377** [comment]
Are you able to retest with the latest Early Access? #4869 was recently tagged and it fixed some issues with soft locks in various games, it might be worth retesting

**Comment by RodrigoTR04** [comment]
@ogniK5377 Tried with EA 1091 same crashes, all are consistent besides the Leon fight, that I've found to be hit or miss most of the time.
New logs:
[EA 1091 logs.zip](https://github.com/yuzu-emu/yuzu/files/5468446/EA.1091.logs.zip)

**Comment by RodrigoTR04** [comment]
After TCR released to EA I retested every place that it crashes, here are the logs for version EA 1144 - TCR
[EA 1144 - TCR.zip](https://github.com/yuzu-emu/yuzu/files/5580869/EA.1144.-.TCR.zip)

**Comment by RodrigoTR04** [comment]
I'm leaving yuzu for the time being.

**Comment by FearlessTobi** [comment]
This still seems to be a valid issue.

**Comment by RodrigoTR04** [comment]
I request that these aren't reopened, another user will be having an identical issue opened. I want mine closed.
