### ISSUE TITLE
No More Heroes 1 not going beyond first logo, and crashing my PC in the process

### ISSUE THREAD

**Issue by Emogop** [yuzu-emu/yuzu#4877]
Due to overall harmful nature of the issue I refuse to launch the game for more than a few sec.
And during even that time Yuzu created a log almost 50 mb in size.
At my first try of booting the game, my HDD started swapping like it was possessed by a demon. The PC was barely reacting on anything during that. It lasted some time, then it finally stopped. But the screen went black and the only thing alive on it was a mouse cursor. The only thing for me to do at that time was a hard reboot.
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5468433/yuzu_log.zip)

**Comment by benderscruffy** [comment]
goes ingame now 
can be closed
