### ISSUE TITLE
Graphical glitch in Kamen Rider: Memory of Heroez

### ISSUE THREAD

**Issue by Night9Knight** [yuzu-emu/yuzu#4879]
The gameplay is done on the latest Yuzu version (422) with a firmware version of 10.2.0

The information is shown in this link: https://imgur.com/a/dyPvpOa

Thank you in advance for your effort in looking into this issue.

**Comment by FearlessTobi** [comment]
Can you please provide a log file?

**Comment by dragodrex237** [comment]
I also encountered the same situation in this game. Here is my log file. Hope it helps.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5486772/yuzu_log.txt)

**Comment by UltraMegaMagnus** [comment]
I found the same issue, here is how to input each password, negative value is how many time you press the button to the left, positive value, input to the right how many time you press the button to the left :  
alive
3 
-2 
-1
0 
1

digal
-3
-1
0
-2
-2

raito
-1
-2
0
-2
-1

I believe the font is not loading for the dial password, the game also have blinking bloom or ambiant occlusion
[mezul and blinking blue glow yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5497276/mezul.and.blinking.blue.glow.yuzu_log.txt)

**Comment by UltraMegaMagnus** [comment]
yuzu 432 problem is gone, thank you :
![yuzu_8Hrr4yfXUt](https://user-images.githubusercontent.com/69069991/98941758-4b0e2780-24ed-11eb-9b0b-125a4126c412.png)
