### ISSUE TITLE
Crash Team Racing audio glitch on Windows 2004

### ISSUE THREAD

**Issue by danishblunt** [yuzu-emu/yuzu#4881]
Tested the mainstream version of the emulator with crash team racing. The sound effects play normally, however the background music will run very slowly and crackling a lot for the first 2-3 seconds then loop the next second endlessly, only happens on windows 10 version 2004. Tested the same yuzu emu files and confgs on another windows 1909 build and the glitch was completely gone.

**Comment by FearlessTobi** [comment]
This sounds a lot like a very Windows specific issue.
Can you please try to resolve your problem on our Discord server? 
If this doesn't help, we can always reopen this issue.

**Comment by danishblunt** [comment]
I already talked with a mod and a couple of people there, all point towards an issue with windwos 2004 build. I did the same test on the same rig with windows 1909 version and the issue dissapeared, this is probably a common theme once the 2004 build gets more and more popular, so I think it might be a good idea to find the cause before the 2004 build gets really common and everyone is complaing about it.
