### ISSUE TITLE
Alpha Issues on Final Fantasy X-X2 Remaster

### ISSUE THREAD

**Issue by Djipi71** [yuzu-emu/yuzu#4883]
There is apha problems on certain textures like hair jewels necklasses...
![0100fe500d0ca000_2020-11-01_14-23-48-482](https://user-images.githubusercontent.com/35375131/97804626-77a28380-1c51-11eb-9d77-5b921f754b60.png)

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by Djipi71** [comment]
it's a graphical problem... what's wrong???? i'm not checking a support , i report alpha problem on 2D texture!

**Comment by Schplee** [comment]
Reopening issue as the user was told to create the issue.

**Comment by Djipi71** [comment]
thanks

**Comment by BSoDGamingYT** [comment]
To add to this issue. This occurs on OpenGL (GLSL & GLASM) and also Vulkan. 

Tested on EA 1095

GPU: GTX 1080ti

Yuzu
![1](https://user-images.githubusercontent.com/38402209/97817506-2fa94e00-1c9d-11eb-8743-303d30bf3c52.PNG)

Switch
![2](https://user-images.githubusercontent.com/38402209/97817512-346e0200-1c9d-11eb-9956-a28b3cfdfee1.PNG)

**Comment by FearlessTobi** [comment]
This is still missing a log file.

**Comment by choppymaster** [comment]
This issue is same as #4880  ?

**Comment by ameerj** [comment]
fixed by #4946

**Comment by Djipi71** [comment]
Test with EA 1630 And te problem is always here sorry :(

**Comment by Morph1984** [comment]
Reopened as the aforementioned issue is not fixed by the linked PR

**Comment by benderscruffy** [comment]
is this still an issue ???

**Comment by Djipi71** [comment]
No. Now it's fixed :) . it can be closed :)

![Sans titre-1](https://github.com/yuzu-emu/yuzu/assets/35375131/c609b345-557c-4e2f-a689-1653a924edc6)
