### ISSUE TITLE
Smash Ultimate freeze in Spirits Menu

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#4884]
I created a new game, cutscene played perfectly, but when i selected the first stage by pressing "A" it just froze. 
Log file:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5471626/yuzu_log.txt)

**Comment by choppymaster** [comment]
**[  38.882304] Debug <Critical> video_core\shader\decode\other.cpp:operator ():87: Assertion Failed! S2R WscaleFactorXY is not implemented
[  38.882307] Debug <Critical> video_core\shader\decode\other.cpp:operator ():90: Assertion Failed! S2R WscaleFactorZ is not implemented
[  38.882324] Debug <Critical> video_core\shader\decode\warp.cpp:DecodeWarp:110: Assertion Failed! Unhandled warp instruction: VOTE_VTG
[  38.882326] Debug <Critical> video_core\shader\shader_ir.cpp:GetConditionCode:343: Assertion Failed! EXIT.FCSM_TR is not implemented**

Observed in your log.
