### ISSUE TITLE
Hyrule warriors age of calamity audio issue

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#4885]
Hyrule warriors age of calamity have audio issue on jp voice
(possibly occur on other language too)

here is example

https://youtu.be/qx0KWCWt0-A

hyrule king quote start part repeated and render normally

https://youtu.be/HWHep1buJYE

zelda's quote repeat it
hardware: i7 8700k 16gb ram rtx2080s
log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5473289/yuzu_log.txt)

**Comment by benderscruffy** [comment]
has this been fixed by #8545 ???

**Comment by gidoly** [comment]
For me yes. But i haven't tested recently could be regressesed
