### ISSUE TITLE
Memory page Assert failure

### ISSUE THREAD

**Issue by Sumerin** [yuzu-emu/yuzu#4886]
Given:

1. Not runned game yet
2. Memory pages set o 0mb (16GB ram)
3. Windows 10

When:

1. Starting the game

Then:

1. Yuzu closes (no warning, info even log file is empty)

Via yuzu-cmd.exe I found that virtual_buffer.cpp line 27 Assert fails.
I raised the page memory size from 0MB to 2396MB (recommended by windows). Still same issue.
I raised the page memory size to 8000MB. It works.

I try to dump console log for u but after the first run changing page memory size to 0MB (with required system reboot) does not cause this issue.

TODO:

- [ ] PopUp ("Too small page memory size" ) or log with information should be provided to user instead of closing application

- [ ] Add this solution to FAQ

**Comment by benderscruffy** [comment]
Is this still an issue ??

**Comment by Sumerin** [comment]
No idea it was 2 years ago.

**Comment by benderscruffy** [comment]
just close it then
