### ISSUE TITLE
Random freezes on Breath of the Wild since yuzu 427

### ISSUE THREAD

**Issue by Kewlan** [yuzu-emu/yuzu#4893]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5493360/yuzu_log.txt)

I've been playing Breath of the Wild for several days now, and only after updating to yuzu 427 the game completely freezes up at random times. What stands out in the log is: 
`[4341.407682] HW.GPU <Critical> video_core\dma_pusher.cpp:Step:103: CommandList at addr=0x2C48A0BE0 is corrupt, skipping!`
My guess it's something related to #4869.

**Comment by bunnei** [comment]
@Kewlan can you see if #4903 helps?

**Comment by Kewlan** [comment]
Will do! If this works I'll report back in a day or two to make extra sure, since it took over an hour for the freeze to happen that time.

**Comment by Kewlan** [comment]
I've had no other softlock yet, so that surely did it. Thanks!

**Comment by bunnei** [comment]
Awesome, thanks for testing!
