### ISSUE TITLE
Pokémon Sword crash key item

### ISSUE THREAD

**Issue by QwEekYhyo** [yuzu-emu/yuzu#4897]
So, everything was wokring fine until I catch a rotom, then beat the rotom guy in wyndom who gave me the rotom catalog and try to open the key item pocket. Every time I open it my game crashes. I don't know if it occured before because I don't often look in this pocket of the bag. I'm playing with yuzu 427, I tried disabling max res mod, I tried changing opengl to vulkan, I tried using single core but it still crashes.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5500045/yuzu_log.txt)

**Comment by QwEekYhyo** [comment]
*EDIT*
I used a save editor to remove the rotom catalog and it still crashes so I guess it's not that item

**Comment by G-Spawn** [comment]
This issue should be corrected on latest yuzu or by just continuing to play the game. Please reopen if it still happens
