### ISSUE TITLE
ANIMAL CROSSING NH CRASH

### ISSUE THREAD

**Issue by Lulbit8** [yuzu-emu/yuzu#4898]
When i just open the game at YUZU loading screen it just crush And i have YUZU EARLY ACCESS

**Comment by G-Spawn** [comment]
new version crashes regardless of game. Revert to old backup or something for now.

**Comment by Lulbit8** [comment]
ok i should use normal yuzu and update it? OH 
i forget to ask if the game can run on 4 gb of ram sooooooo yuzu its not like ryujinx that the game texture become black 
and dosent work proply and the game just chop 3d models rigthhhhhh????

**Comment by Lulbit8** [comment]
nope i open yuzu and the game crash so why

**Comment by G-Spawn** [comment]
Post a log.. or join the discord and ask there lol.

**Comment by Lulbit8** [comment]
are you taking fun of me XD WAS KIDDING yuzu have a good community not like ryujinx that they just say THATS NOT A PROBLEEEEEMMMM sooooo now take the log file oh they say Danche no no thats the song They say that I CANN PLAY ON A LAPTOOOOOOOOPPPP
and yuzu can run switch games on 4 gb of ram??? bc i consider yuzu better like the interface is sooooo cool and edd and i wanna to test it soooo i foun the log file
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5504886/yuzu_log.txt) here this is all

**Comment by Lulbit8** [comment]
im italian sorry for bad english

**Comment by DanMossa** [comment]
The game doesn't crash during start up for me at all.

**Comment by Lulbit8** [comment]
yeah buuuuuuuuuuut i play animal crossing new horyzions on ryujinx but graphic suks and dosent render

**Comment by G-Spawn** [comment]
As much as I'd love to help and have a chat on GITHUB I'd much rather you guys just join the discord server if you're going to have this kind of issues - discussions.

**Comment by G-Spawn** [comment]
and that sounds about right for your hardware Lulbit. File reader errored out during header read. Means something is corrupted (besides the hardware limitations you have)

**Comment by G-Spawn** [comment]
Dan it launches on the newest mainline just fine. The only known issues atm I think still are some weirdness with things that trigger Boxcat. (Nooks atm etc)

**Comment by G-Spawn** [comment]
It works so perhaps try redumping your game or join the discord server for more personal help 👍 
![image](https://user-images.githubusercontent.com/23653025/98451684-0ca3f180-2116-11eb-97bf-48932830ed61.png)

**Comment by G-Spawn** [comment]
> since i downloaded the game the game has a graphic bug
> oh thank you i should buy a switch but OK

Its either your vernacular or the fact you don't own a Nintendo switch but I don't think you'll get support for piracy any further than this.

**Comment by DanMossa** [comment]
Can we close this?

**Comment by G-Spawn** [comment]
Please. I'll try to ask someone otherwise.

**Comment by Lulbit8** [comment]
ok
