### ISSUE TITLE
Undertale - Extreme slow down in "Lab"

### ISSUE THREAD

**Issue by RickAndTired** [yuzu-emu/yuzu#4902]
Undertale 1.0 and 1.11

When entering the map the Lab the frame rate drops to about 1 frame every 30-60 seconds

Yuzu 429 (tested on many previous versions as well)

Windows 10
Ryzen 5 2600 and AMD RX 570 (20.11.1)
Ubuntu 20.04 and 20.10 
Ryzen 5 2600 and AMD RX 570 (Mesa 20.2.1)

Another user in the Yuzu Discord was able to reproduce the issue also

This same issue happens in Ryujinx if that has any relevance

Issue happens in the map (Lab) directly right of the save
[undertale save.zip](https://github.com/yuzu-emu/yuzu/files/5504390/undertale.save.zip)

**Comment by FearlessTobi** [comment]
Could you please provide a log file as well? Thanks

**Comment by RickAndTired** [comment]
[yuzu_log - Undertale.txt](https://github.com/yuzu-emu/yuzu/files/5532856/yuzu_log.-.Undertale.txt)
