### ISSUE TITLE
The controller settings panel UI is messed up with Scale and Layout set to 200% on Window 10 

### ISSUE THREAD

**Issue by nauxliu** [yuzu-emu/yuzu#4904]
The controller settings panel UI is messed up with Scale and Layout set to 200% on Window 10 

Yuzu 429
Windows10 20H2

![image](https://user-images.githubusercontent.com/9570112/98444000-18a9a680-214a-11eb-9e68-f945c803bfbd.png)

**Comment by benderscruffy** [comment]
is this still an issue ???
