### ISSUE TITLE
[Feature Request] Ring-Con Support

### ISSUE THREAD

**Issue by cooperate** [yuzu-emu/yuzu#4911]
It would be great to have support for the Ring-Con accessory (and consequently Ring Fit Adventure).  Apparently, the Ring-Con is not a simple passive device.  I believe it passes a float value to represent the "flex" of the device through a sensor built into it.

See this video here:
https://youtu.be/RRX7Ds0e2F8

**Comment by drnooooo** [comment]
> Has anyone tested it? Is Ring Fit Adventure now fully playable with Ring Con?

I've tested it and unfortunately no, it doesn't get past the "Squeeze the Ring Con" screen. It doesn't seem to detect squeezing/pulling at all.

**Comment by pktiuk** [comment]
> > Has anyone tested it? Is Ring Fit Adventure now fully playable with Ring Con?
> 
> I've tested it and unfortunately no, it doesn't get past the "Squeeze the Ring Con" screen. It doesn't seem to detect squeezing/pulling at all.

I think, that in this case this issue should be reopened, because in current state Ring-Con can't be considered as "working".
