### ISSUE TITLE
Yuzu only detects the first four Wirelessly Connected Xbox One Controllers on Windows 10

### ISSUE THREAD

**Issue by cooperate** [yuzu-emu/yuzu#4912]
I'm not sure if there is a graceful fallback to direct input or raw input but because this is a specific Windows 10 issue it might be worthwhile to use [gaming.input](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input?view=winrt-19041) for xbox one controllers, which will provide trigger feedback support and avoid the issues surronding triggers in dInput (not able to use both at once).

As it stands only the first four controllers are detected under xInput.  Any subsequent xbox one controller that connects cannot be detected by yuzu.

**Comment by FearlessTobi** [comment]
SDL uses XInput by default, which only supports 4 controllers.

**Comment by cooperate** [comment]
SDL actually has a fallback in place now for more than 4 controllers.  I'm not sure if it's mainline or maybe the SDL yuzu uses is out of date but you read about this patch here:
https://discourse.libsdl.org/t/supporting-more-than-4-xinput-capable-devices-on-windows-rfc/25666/24
@FearlessTobi

**Comment by mrpinkcat** [comment]
Any news ?

**Comment by german77** [comment]
solved by #6950 enable 8 player support on advanced settings
