### ISSUE TITLE
Crash when opening configure menu on Vulkan while running a game.

### ISSUE THREAD

**Issue by RodrigoTR04** [yuzu-emu/yuzu#4913]
When opening the "Configure" menu to select an input device with the Vulkan API, game was started with no controller connected so it needed to be selected in the menu.

1. Start game with no controller connected while using Vulkan
2. Wait to get past the loading shaders screen
3. Try to open the configure menu to select input device
4. Crash

Logs from The Legend of Link's Awakening and Steins;Gate 0, both games better played in Vulkan due to better rendering.
[Configure-Steins;Gate.txt](https://github.com/yuzu-emu/yuzu/files/5512975/Configure-Steins.Gate.txt)
[Configure Link's Awakening.txt](https://github.com/yuzu-emu/yuzu/files/5512976/Configure.Link.s.Awakening.txt)

Video posted on Discord: https://discord.com/channels/398318088170242053/402001453381713920/776523760248815646

**Comment by german77** [comment]
Does it happens on mainline?

**Comment by RodrigoTR04** [comment]
> Does it happens on mainline?

Yes this is happening as of Mainline 432, also Vulkan is being used in the per game configuration, global is set to OpenGL if it makes any difference.

**Comment by german77** [comment]
I have to check that. Yesterday I followed your instructions and it worked fine

**Comment by german77** [comment]
Tested with 432. No problems on my system

**Comment by RodrigoTR04** [comment]
Mine only happens with Vulkan, when switched to OpenGL it goes back to normal again, deleting and starting a new config file doesn't fix the issue.

**Comment by RodrigoTR04** [comment]
I'm leaving yuzu for the time being.

**Comment by FearlessTobi** [comment]
This still seems to be a valid issue.

**Comment by RodrigoTR04** [comment]
I request that these aren't reopened, another user will be having an identical issue opened. I want mine closed.
