### ISSUE TITLE
Resident Evil 5 and 6 Crash problem

### ISSUE THREAD

**Issue by Djipi71** [yuzu-emu/yuzu#4915]
On resident Evil 5 , when you try to open a door the emu crash. On resident evil 6, after loading new game with Leon , emu freeze on black screen. 

Run on Vulkan because openGL have black screen ingame.
Test without Assembly Shader disable , same result .

SPECS:
Win10 / GEFORCE RTX 2060 S / 16DDR / Core-i 7 4770K

Here's the log on RE5
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5523104/yuzu_log.txt)

Here's the log on RE6
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5523129/yuzu_log.txt)

**Comment by Djipi71** [comment]
Now Resident evil 5 Work well.

For Resident Evil 6 there is graphicals issues like No hair on main characters
![Sans titre-1](https://user-images.githubusercontent.com/35375131/121148307-f42dbe00-c841-11eb-9fc4-884fda089e35.png)
Plus others characters and some zombies have no  head...

**Comment by benderscruffy** [comment]
can be closed
