### ISSUE TITLE
Profile controllers and online games

### ISSUE THREAD

**Issue by rezq41** [yuzu-emu/yuzu#4918]
Hello, I have a problem in yuzu, I would like to save a controller profile but I cannot create a profile for my two controllers, I click on the new icon and nothing happens.
How to do?
So it takes me any device even if I change the settings and when I launch mario kart and go to local multiplayer, a yuzu window opens asking to configure the controllers but nothing helps and with this window that freeze the game force to restart yuzu.

Also how to play online? I added my web token, but when I launch online multiplayer on mario kart I have the error code: 2474-0212.

thank you in advance

**Comment by german77** [comment]
Controller profiles are only enabled in EA at the moment. There is no online multiplayer for yuzu. Next time ask in discord for such questions. This is only to track development issues.

**Comment by rezq41** [comment]
Ok no worries, I have no discord.

What is EA?

Are you going to put the mode online soon?

**Comment by german77** [comment]
EA = Early access.
No ETA's are given for new features. They will arrive when they are ready to.

**Comment by rezq41** [comment]
Thank you I took the early access it works nickel for the controller profiles.
However, online does not work anyway: /: / I really hope they will put it soon.
