### ISSUE TITLE
Hyrule Warriors: Age of Calamity (Demo) freeze or hang during character selection prior to starting a mission.

### ISSUE THREAD

**Issue by G-Spawn** [yuzu-emu/yuzu#4919]
https://streamable.com/a60qit 
footage from fellow user (Gidoly) Shows how to replicate the issue and an example of it

Personal log when replicating his issue below
yuzu Early Access 1121 | HEAD-acfe7caae
i9-9900k
RTX2070S
16gb memory + 30gb page file
Updated Drivers (457.30 I believe it is atm)

Upon attempting his save file I am able to replicate the slowdown / freezing of the game when selecting a character or going through the selection screen. I'm unable to tell specifically what the issue is as it is quite early but I hope the log provides more insight + save file. It seems to drop frame rate down to 0-2fps when the issue hits and doesn't pick back up. Memory usage seems relatively stable same with cpu.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5535509/yuzu_log.txt)

Save file for more context:

[aoc-save-freeze.zip](https://github.com/yuzu-emu/yuzu/files/5535545/aoc-save-freeze.zip)

**Comment by gidoly** [comment]
here is my log too
i7 8700k
16gb ram
rtx 2080 super
driver 457.30 ver
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5535612/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Dupe of https://github.com/yuzu-emu/yuzu/issues/4871 My bad!
