### ISSUE TITLE
Crash Team Racing Nitro Fueled Colored Squares

### ISSUE THREAD

**Issue by R4to0** [yuzu-emu/yuzu#4920]
No matter which settings (OpenGL or Vulkan, async or not) I get the same issue. At first I thought it was due to missing NVDEC feature but since it is a thing now I have no idea.

Yuzu EA 1121 / HEAD-acfe7caae
Crash Team Racing Nitro Fueled v1.0.15

Windows 10 Pro 64-bit 20H2
AMD Radeon R7 260X (Radeon Software Version 20.10.1)
AMD Ryzen 5 3600X 6 Cores/12 Threads 3.8GHz/4.4GHz
16GB DDR4 2400MHz

Vulkan:
![yuzu Early Access 1121 _ Crash™ Team Racing Nitro-Fueled 2020-11-13 13-39-50 mp4_snapshot_00 17 578](https://user-images.githubusercontent.com/3608184/99099528-59297a00-25b9-11eb-945d-31bc2e440db4.jpg)

OpenGL:
![ogl_1121_2](https://user-images.githubusercontent.com/3608184/99099556-63e40f00-25b9-11eb-9d34-ef4dc8b66f17.png)

Demonstration video: https://streamable.com/cwnaw4

Logs:
[yuzu_log_opengl.txt](https://github.com/yuzu-emu/yuzu/files/5538278/yuzu_log_opengl.txt)
[yuzu_log_vulkan.txt](https://github.com/yuzu-emu/yuzu/files/5538279/yuzu_log_vulkan.txt)

**Comment by bukyapavankumar** [comment]
Do you get these in local arcade too?

**Comment by G-Spawn** [comment]
Try deleting your shader cache. Right click game >> remove >> remove shader cache

**Comment by R4to0** [comment]
> 
> 
> Do you get these in local arcade too?

Still same, and worse when playing in opengl mode.
![image](https://user-images.githubusercontent.com/3608184/99211547-47a5c500-27a7-11eb-8cc3-71bb5f5f923a.png)
![image](https://user-images.githubusercontent.com/3608184/99211557-4e343c80-27a7-11eb-916b-f1a3da0e6713.png)

The game is unplayable on my GPU when using OpenGL as it uses 100% GPU with ~15FPS, while in Vulkan I get ~40-60fps with ~50-60% GPU usage.

> 
> 
> Try deleting your shader cache (least for opengl) . Right click game >> remove >> remove shader cache
Did that before and the results are the same as the above.

**Comment by GeorgeMendes08** [comment]
I run this game in my setup with Ryzen 2600 and RX 570 and have the same problems, I use the Vulkan API... For what I know until now this only affects Radeon GPUs, any gameplay that I see on NVIDIA cards don't have this issue, even on Vulkan. On Radeon cards however all gameplays that I watched have this very same problem.

**Comment by KChunStry** [comment]
I hava a Ryzen 5 3600 and Gtx 1060, with vulkan i have weird glitches too, not on OpenGL Tho.

Vulkan:

![2020-11-18 09_24_21-Window](https://user-images.githubusercontent.com/60659350/99504511-ec7afa80-297f-11eb-8b4b-d2d54bfd17e9.png)
![2020-11-18 09_24_38-Window](https://user-images.githubusercontent.com/60659350/99504513-edac2780-297f-11eb-98bc-6832c2ea0afc.png)

**Comment by GeorgeMendes08** [comment]
I downloaded older versions of Yuzu for trying to see if I could find the source of the problem. Well, for my tests I discovered that theses colored squares only started showing on the 750 EA, where the 749 EA don't have this problem, but has other graphical bugs.
I'm not a developer, but for anyone who can solve this problem, I believe that is where it starts.

**Comment by cooperate** [comment]
Was hoping the texture cache rewrite would correct these colored squares but that doesn't seem to be the case.

![ctr_colored_blocks](https://user-images.githubusercontent.com/13011766/99930786-3577d980-2d07-11eb-9d19-d5ed1926f24a.png)

**Comment by bukyapavankumar** [comment]
It won't

**Comment by buddyto** [comment]
Same issues here

**Comment by hunterOO1** [comment]
Same here
Running at AMD Ryzen 1600x and AMD RX580 8GB VRAM

**Comment by sombree** [comment]
Issue still exists in yuzu EA 1283. Games run smoothly but with colored/black squares randomly appearing throughout the screen.
There are also issues with some textures but they can be mitigated by disabling "Surface Format Optimization" in Radeon Software.
Running on: Ryzen 3600 and RX580 4GB (Adrenalin 20.12.1).

**Comment by R4to0** [comment]
This seems fixed in EA 1381, not sure in which one this was fixed but it is soooooooooo clean now!
![image](https://user-images.githubusercontent.com/3608184/105921378-895cb280-6017-11eb-9bff-8525824f1539.png)

In same place as the first picture I posted:
![image](https://user-images.githubusercontent.com/3608184/105921581-c7f26d00-6017-11eb-8b5c-489479567ee5.png)


Thank you whoever fixed this in the code!

**Comment by FearlessTobi** [comment]
Nice! I'll close this issue then.
