### ISSUE TITLE
Pokémon: Let's Go, Pikachu!'s Play with pokemon screen actually 1-2 fps

### ISSUE THREAD

**Issue by LurkSienn** [yuzu-emu/yuzu#4921]
Playing with pokemon window is not working at all. It's showing 3 fps max. Any other scenes or locations are good and stable.
Playing in Vulkan mode. Waiting of shaders loading in OpenGL is also not working, Please, help.
Specs:
GeForce GTX 1070
i7-7700HQ 2.80GHz
16GB RAM

![image](https://user-images.githubusercontent.com/74370896/99102988-142d3400-2609-11eb-9f06-93e41e54f28a.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5538406/yuzu_log.txt)

**Comment by bukyapavankumar** [comment]
It's known issue

**Comment by LurkSienn** [comment]
So it won't be fixed in near future?

**Comment by LurkSienn** [comment]
> It's known issue

So it won't be fixed in near future?

**Comment by G-Spawn** [comment]
Not a direct link but if you were in the support discord you'd have seen it mentioned almost Every other day to those who ask about the game.

**Comment by LurkSienn** [comment]
> Not a direct link but if you were in the support discord you'd have seen it mentioned almost Every other day to those who ask about the game.

Thanks you. I hope this issue will be fixed sometime!

**Comment by G-Spawn** [comment]
This should be fixed on newer yuzu versions. Feel free to reopen if it still happens to you
