### ISSUE TITLE
heavy graphical bugs in dragon quest 11

### ISSUE THREAD

**Issue by apwvanharen** [yuzu-emu/yuzu#4925]
![image](https://user-images.githubusercontent.com/74477751/99160895-90e50e80-26ec-11eb-9880-24a7224a1f6e.png)
![image](https://user-images.githubusercontent.com/74477751/99160904-aa865600-26ec-11eb-83e7-64da76fc1a48.png)

yuzu ver. #436 (don't know what ''commit hash'' is or how i do that)

graphical bugs include: misplaced textures (see water on pic 2), character textures are glitching out. 
when i move my camera up or down, some textures like the water moves with the camera (see pic 1)
sometimes the character will ''freak out'' by stretching out for like 0.5 of a second. so i am not able to get a screenshot of it.

i use openGL but also tried with vulcan, but that was even worse.
the rest of the settings are default settings.

pc specs:
Intel Core i5 9400f 2.90 GHz
nvidia geforce gtx 1660 super
8 gb RAM

i hope i am in the right place, as this is the first time doing this. if not: sorry and please send me in the right direction.

**Comment by FearlessTobi** [comment]
Can you please also provide a log file?

**Comment by apwvanharen** [comment]
i deleted the game because the graphical glitches were to much for me to handle.
but i can link a youtube video of someone showcasing dragon quest 11 on Yuzu, with the exact same graphical glitches.
https://www.youtube.com/watch?v=MCNAIDpIKnQ&t=70s&ab_channel=Emulators%26GameplayHD
it seems that this is a glitch that exists for a while now (at least 3 months) although the same glitches can be seen in the yuzu early access version 823.

hope this helps in future bug solving

**Comment by Nakotei** [comment]
Hi, I'm new here, and I have exactly the same issue. I don't have programming knowledge, but I want to fix the game. If you need information about something, tell me.

Pc:
Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz    1.99GHz
RAM 8,00 GB
NVIDIA GeForce GTX 1050

**Comment by benderscruffy** [comment]
is this still an issue ???

**Comment by gidoly** [comment]
game should render properly on lastest mainline
