### ISSUE TITLE
Yuzu not saving input devices

### ISSUE THREAD

**Issue by Oppion44** [yuzu-emu/yuzu#4928]
Whenever I choose an input device in the controls settings (doesn't matter if it's KBM or a controller) it always resets to the "Any" options, effectively making it impossible to bind controls and to use the emulator at all.

Video of the problem: https://i.imgur.com/AoMy7Pr.mp4

![image](https://i.imgur.com/39dRtwF.png)

Specs:
GTX 1070
i7 7700K @ 5.1 GHz
16GB RAM
Windows 10 Pro x64

**Comment by G-Spawn** [comment]
Yeah that's normal. You should be able to bind - map controller or keyboard from what you select in the input device category. Yes it'll revert to any when you browse to the page again but it still works.
