### ISSUE TITLE
Updates aren't applied

### ISSUE THREAD

**Issue by GRAnimated** [yuzu-emu/yuzu#4938]
HEAD-mainline-636-3743-ge3672ee10
CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz | AVX2 | FMA
GPU: RTX 2060 KO 6GB
OS: Windows 10 (10.0)
RAM: 23.94 GB

I've been testing a little oddity between Super Mario Odyssey versions, but I was observing inaccurate behavior between yuzu and the console. After digging in the code, a 1.0.0 only function was being done with a 1.2.0 update applied.

_Pseudocode from 1.0.0 hiding a layout if the version string matches_
![image](https://user-images.githubusercontent.com/23510999/99486632-8f0c8c80-2932-11eb-81c2-ec0a868d83d9.png)

_Pseudocode from 1.2.0 that hides the layout no matter what_
![image](https://user-images.githubusercontent.com/23510999/99486685-aba8c480-2932-11eb-9c9c-a22857337982.png)

The oddity comes when you launch the game with the 1.2.0 update applied. The layout pane is visible and shows '1.2.0'.
![image](https://user-images.githubusercontent.com/23510999/99486782-e14dad80-2932-11eb-93a8-870e77688e55.png)

This is the behavior 1.0.0 would represent, not 1.2.0.

![image](https://user-images.githubusercontent.com/23510999/99486416-1f969d00-2932-11eb-9021-40f5585a7cdd.png)
After checking my log, I noticed the 1.2.0 exefs wasn't being applied. 1.2.0's main build id is `F5DCCDDB37E97724EBDBCCCDBEB965FF`, but it's not being loaded.
![image](https://user-images.githubusercontent.com/23510999/99486334-0988dc80-2932-11eb-9ea7-5f32e355ce72.png)

I've deleted my NAND folder and reinstalled the update with no change. I'm unsure if the patched romfs is being applied or not, either.

**Comment by BSoDGamingYT** [comment]
Close the dead exe you have open and idle in task manager/details....reinstall the update

**Comment by GRAnimated** [comment]
there's only one open in task manager.
also if you wanna try it: 1.3.0 normally shows the button to play in VR and luigi would be in kingdoms, both are missing

**Comment by GRAnimated** [comment]
realized this was still open, redid my windows a while back and it stopped happening so
