### ISSUE TITLE
inserting new prod keys games not starting anymore.

### ISSUE THREAD

**Issue by Axel577** [yuzu-emu/yuzu#4943]
Hi,
I'm using yuzu mainline 439. When I'm putting the new 10.2.0 prod.keys in yuzu folder, no game is starting anymore.
Can you explain to me why?

**Comment by BSoDGamingYT** [comment]
No, because you didnt provide any information, or a log for the game you are trying to play. Please adhere to the information provided in the issue guidelines

**Comment by Axel577** [comment]
I'm trying to play luigis mansion. it's working fine with the current prod.keys. with the new prod keys 10.2.0 it's stuck at launching status bar. I comapred the log file, there is no difference. Can you explain to me what is prod.keys and title.keys for? Can you also tell me if I can provide more useful information to solve the issue?

**Comment by choppymaster** [comment]
Do you dumped the prod.keys from your own Nintendo switch? If you don't have a switch you can't use yuzu.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
With the info you provided we can't really help you here.
Please join our Discord or our forums for further assistance.
