### ISSUE TITLE
Pokemon Shield Doesn't Launch with yuzu early access

### ISSUE THREAD

**Issue by Amrsamir88** [yuzu-emu/yuzu#4961]
Guys, i've installed yuzu early access 1131 and i can play pokemon let's go eevee ,,but when i try to open pokemon shield it doesn't launch and crashes (yuz has stopped working )
My pc specs 
![1](https://user-images.githubusercontent.com/74810154/99869967-eed79180-2bd7-11eb-8fbf-75a04f68c330.png)

![Untitled](https://user-images.githubusercontent.com/74810154/99869924-9dc79d80-2bd7-11eb-9a45-d1145280959d.png)

**Comment by goldenx86** [comment]
If you have an Intel GPU on that laptop, you don't meet the minimum requirements to run yuzu.

**Comment by Amrsamir88** [comment]
so why does it crash ??

**Comment by G-Spawn** [comment]
post a log maybe that'd be more insightful.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
