### ISSUE TITLE
yuzu just crash when run super mario odissey on win 7x 64

### ISSUE THREAD

**Issue by JIuBeP** [yuzu-emu/yuzu#4962]
pc win 7 x64 ryzen 2600 ram 8 gb gtx 950
crash always on launch game with error c++ / i have install vs c++ 2005-2019
Can u help me? 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5577716/yuzu_log.txt)

**Comment by Morph1984** [comment]
This is an issue tracker for developers, not a support forum. Please head to either the Citra forums or our discord server for support
