### ISSUE TITLE
Audio stutter/lag when playing under multicore

### ISSUE THREAD

**Issue by ActualMandM** [yuzu-emu/yuzu#4964]
yuzu 444/Early Access 1156

GeForce RTX 2080
Ryzen R9 3950X

This is an extension of the second part of #4592. In every game, there is a chance that the game's audio will stutter. (aka momentarily pause for a split second)

https://youtu.be/yF9CndnePy0

In some major/extreme cases, it will cause the audio to lag with slower playback. This mainly happens when NVDEC playback is happening. (Fixed with #5051)

https://youtu.be/pzPg4HLTyj0

However for some games that don't end up syncing visuals with audio, (ex. cutscenes, rhythm games) this issue will cause the audio to go out of sync.

https://youtu.be/vDYq1ydIFZE

**Comment by bunnei** [comment]
Probably still relevant, no need to close :)

**Comment by Wishmater** [comment]
This I issue is very important in my opinion, and vital for rhythm games like Project Diva Mega Mix.
Are there any plans to solve this, or any usable workarounds?

**Comment by liamwhite** [comment]
This should have been fixed with the audio rewrite https://github.com/yuzu-emu/yuzu/pull/8545 - comment if this issue is still occurring.
