### ISSUE TITLE
Regression: some games fail to boot or load

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#4965]
Caused by #4907 @ogniK5377 

yuzu (since Mainline 444) no longer can load a save in BOTW 1.0.0 ~~nor boot MK8D 1.0.0~~ (MK8D is possibly an unrelated issue)

[Log of BOTW 1.0.0](https://github.com/yuzu-emu/yuzu/files/5579835/yuzu_log.txt)

**Comment by bunnei** [comment]
Fixed by #4981
