### ISSUE TITLE
hyrule warriors age of calamity crashes is some points of the game

### ISSUE THREAD

**Issue by noamb14** [yuzu-emu/yuzu#4971]
when you will fix that?

**Comment by choppymaster** [comment]
Pls tell your pc specs, operating system and provide a log file.

**Comment by noamb14** [comment]
@choppymaster yes but its in the real game not in the demo.

**Comment by noamb14** [comment]
all the games I played worked more then fantastic but just this crushes @choppymaster

**Comment by choppymaster** [comment]
> Pls tell your pc specs, operating system and upload the log file here.

**Comment by noamb14** [comment]
![image](https://user-images.githubusercontent.com/44144862/99955850-b1b50000-2d8d-11eb-8f7a-85941df69966.png)

**Comment by noamb14** [comment]
![image](https://user-images.githubusercontent.com/44144862/99955920-cdb8a180-2d8d-11eb-978b-377eeb48f320.png)

**Comment by choppymaster** [comment]
Yeah, there are no performance issues, and demo have the same engine as the original version. (Log pls.)

**Comment by noamb14** [comment]
somehow is not crush now.

**Comment by choppymaster** [comment]
If you want support, pls come to [yuzu's discord server](https://discord.gg/u77vRWY). And if you are opening issues, pls provide a log file.
