### ISSUE TITLE
Pokémon Sword graphical issues unique to EA

### ISSUE THREAD

**Issue by PhoenixOnARoof** [yuzu-emu/yuzu#4979]
### **_You hurt my boy. How could you hurt my boy._**
Ahem, so I've got some graphical glitches on EA 1146 that does not happen on mainline. Comparison screenshots are attached. I blame the cache rewrite but that's just me 👀

The hardware in my pc that may or may not matter:
AMD Ryzen 5 3600 & AMD Radeon RX 580

In both mainline and EA I am using vulkan, async, and multicore (and docked if it matters)

### On to the screenshots
A log for this run: [yuzu_mainline.txt](https://github.com/yuzu-emu/yuzu/files/5587233/yuzu_mainline.txt)
As you can see in this screenshot. Everything is all good and nice.
![yuzu_XDe96LlpQW](https://user-images.githubusercontent.com/11891199/100042726-4be66980-2dc9-11eb-80ac-d95f37d33493.jpg)

Log for this run: [yuzu_ea.txt](https://github.com/yuzu-emu/yuzu/files/5587235/yuzu_ea.txt)
In this one my boy is very sick. He needs some (medical) help
![yuzu_ySZI1QZGLL](https://user-images.githubusercontent.com/11891199/100042767-602a6680-2dc9-11eb-871e-0c7b8f777296.jpg)

A video showing the bug in all it's terrifying glory https://youtu.be/jIOFtlOWRPc

**Comment by Banjo-Kazooie-fan** [comment]
AMD Ryzen 5 3600 & AMD Radeon RX 570
![Pokemon Bug 2](https://user-images.githubusercontent.com/74963292/100092500-7599a200-2e56-11eb-936e-975c3f4e14c1.PNG)
![Pokemon Bug](https://user-images.githubusercontent.com/74963292/100092506-792d2900-2e56-11eb-9e84-8279756c16a5.PNG)

**Comment by Itamai** [comment]
> AMD Ryzen 5 3600 & AMD Radeon RX 570
> ![Pokemon Bug 2](https://user-images.githubusercontent.com/74963292/100092500-7599a200-2e56-11eb-936e-975c3f4e14c1.PNG)
> ![Pokemon Bug](https://user-images.githubusercontent.com/74963292/100092506-792d2900-2e56-11eb-9e84-8279756c16a5.PNG)

Have the same issue on early access build
CPU: AMD Ryzen 7 3700
GPU: AMD Radeon RX 580 8 GB

**Comment by Banjo-Kazooie-fan** [comment]
Seems to be a Vulkan issue which is related to the new Texture cache rewrite Pr

**Comment by tino0318** [comment]
ryzen 5 1600 AMD Radeon RX 570.
in my case it was solved by changing the drivers to the previous version.

**Comment by Banjo-Kazooie-fan** [comment]
> ryzen 5 1600 AMD Radeon RX 570.
> in my case it was solved by changing the drivers to the previous version.

20.11.1? (i am using 20.11.2 atm)

**Comment by Banjo-Kazooie-fan** [comment]
okay: Rolling back to 20.11.1 fixed it
thx for telling us tino0318:)
still need to be fixed for the latest drivers!

**Comment by ReinUsesLisp** [comment]
It's caused by depth blits, I'm working on emulating them with `CmdDraw` instead of `CmdBlitImage`.
![imagen](https://user-images.githubusercontent.com/26564870/100184933-5e43ce80-2ec1-11eb-9edd-0c80fd0c2d89.png)

**Comment by ReinUsesLisp** [comment]
Fixed locally. I'll clean up the code and push it to the relevant pull request.
