### ISSUE TITLE
Oceanhorn 2 : freeze after obtain Captain Chest and sound Lag(very bad sound)

### ISSUE THREAD

**Issue by Djipi71** [yuzu-emu/yuzu#4983]
After Killing the First Boss , you obtain a key for opening the captain chest. After obtain the captain chest treasure , black screen and freeze.

Game update 1.1 use / test with 1.0 same result

For the sound , it's very slow and laggy , crackling

SPECS:
Win10 / GEFORCE RTX 2060 S / 16DDR / Core-i 7 4770K

Yuzu EA 1152 use. Open GL

After restart yuzu, impossible to reload the save, it freeze.

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5588842/yuzu_log.zip)

**Comment by choppymaster** [comment]
Sound is fixed by #5051

**Comment by german77** [comment]
Fixed by #6498
