### ISSUE TITLE
Blair Witch - Start and freeze on black screen

### ISSUE THREAD

**Issue by Djipi71** [yuzu-emu/yuzu#4985]
You can start the game , intro video load and after that , it freeze and crash.

SPECS:
Win10 / GEFORCE RTX 2060 S / 16DDR / Core-i 7 4770K

Yuzu EA 1152 use. Open GL

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5588890/yuzu_log.zip)

**Comment by benderscruffy** [comment]
can be closed
goes ingame now
