### ISSUE TITLE
Darksiders 2 - White texture everywhere

### ISSUE THREAD

**Issue by Djipi71** [yuzu-emu/yuzu#4986]
You can play the game , but many texture are white
SPECS:
Win10 / GEFORCE RTX 2060 S / 16DDR / Core-i 7 4770K

Yuzu EA 1152 use. Open GL

![010071800ba98000_2020-11-24_10-48-49-002](https://user-images.githubusercontent.com/35375131/100077477-ad96ea00-2e42-11eb-8d6b-9210388b56c3.png)
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5588911/yuzu_log.zip)

**Comment by gidoly** [comment]
it is fixed on last versions afaik feel free to reopen if it persist
