### ISSUE TITLE
Yoshi's Crafted World - Freeze after loading screen

### ISSUE THREAD

**Issue by Djipi71** [yuzu-emu/yuzu#4987]
When you load the game, we see loading screen and after that  only black screen.

SPECS:
Win10 / GEFORCE RTX 2060 S / 16DDR / Core-i 7 4770K

Yuzu EA 1152 use. Open GL

Update use 1.0.1 - Test with 1.0.0 same result

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5588931/yuzu_log.zip)

**Comment by choppymaster** [comment]
Ah all over the log I'm seeing:

H.W Memory <Error> core\memory.cpp: Read : 644:  Unmapped Read32

**Comment by Djipi71** [comment]
hope this could help to go ingame 👍
