### ISSUE TITLE
Serious Sam Collection - Freeze after first music start

### ISSUE THREAD

**Issue by Djipi71** [yuzu-emu/yuzu#4988]
When you start the game, only black screen. You can start listening music.

SPECS:
Win10 / GEFORCE RTX 2060 S / 16DDR / Core-i 7 4770K

Yuzu EA 1152 use. Open GL

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5588948/yuzu_log.zip)

**Comment by benderscruffy** [comment]
can be closed
goes ingame now with graphic glitches
