### ISSUE TITLE
Pumpkin Jack - 3d Graphics not rendering

### ISSUE THREAD

**Issue by Djipi71** [yuzu-emu/yuzu#4989]
The game start , but graphism don't render.

SPECS:
Win10 / GEFORCE RTX 2060 S / 16DDR / Core-i 7 4770K

Yuzu EA 1152 use. Open GL

![Sans titre-0](https://user-images.githubusercontent.com/35375131/100078808-35c9bf00-2e44-11eb-887a-c7c15bd375bd.png)
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5588983/yuzu_log.zip)

**Comment by benderscruffy** [comment]
graphics render now
can be closed
