### ISSUE TITLE
Sakuna: Of Rice and Ruin (Title ID:0100B1400E8FE000)  has a sound glitch

### ISSUE THREAD

**Issue by Crazy-serial** [yuzu-emu/yuzu#4990]
Sakuna: Of Rice and Ruin (Title ID:0100B1400E8FE000)  has a sound glitch

this game is famous in japan.
iI think it is better to cure this bug as soon as possible.

video:https://www.youtube.com/watch?v=0HQmy_kFjHQ&feature=youtu.be

**Comment by choppymaster** [comment]
Log?

**Comment by german77** [comment]
Fixed by #6498
