### ISSUE TITLE
Thread 24 "yuzu:VSyncThrea" received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by quarterturn** [yuzu-emu/yuzu#4991]
backtrace:
(gdb) bt
```
#0  std::condition_variable::wait<Tegra::GPU::WaitFence(u32, u32)::<lambda()> >
    (__p=..., __lock=..., this=0x55555792ea40) at /usr/include/c++/9/condition_variable:100
#1  Tegra::GPU::WaitFence(unsigned int, unsigned int)
    (this=this@entry=0x55555792d050, syncpoint_id=<optimized out>, value=0) at ../src/video_core/gpu.cpp:100
#2  0x00005555558efe7a in Service::NVFlinger::NVFlinger::Compose() (this=0x5555571752c0)
    at ../src/core/hle/service/nvflinger/nvflinger.cpp:254
#3  0x00005555558f0362 in Service::NVFlinger::NVFlinger::SplitVSync() (this=0x5555571752c0)
    at ../src/core/hle/service/nvflinger/nvflinger.cpp:47
#4  0x00007ffff4f63d84 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5d1c609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007ffff4c51293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
commit hash:
fbda5e9ec93fad65c86afd2c20695100651cd6e6

uname -a:
Linux nzxt-tower 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

OS:
Ubuntu 20.04

GPU:
GPU 0: GeForce RTX 2080 SUPER

GPU driver:
NVIDIA-SMI 455.38       Driver Version: 455.38       CUDA Version: 11.1  

game used:
spacenx.nro

**Comment by benderscruffy** [comment]
is this still an issue ??

**Comment by quarterturn** [comment]
On September 3, 2022 1:21:11 AM EDT, benderscruffy ***@***.***> wrote:
>is this still an issue ??
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/yuzu-emu/yuzu/issues/4991#issuecomment-1236051730
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Please treat as stale and close.
