### ISSUE TITLE
Animal Crossing: New Horizons | waiting for mods update...

### ISSUE THREAD

**Issue by Ashuzi** [yuzu-emu/yuzu#4993]
Please update the mods for Animal Crossing: New Horizons [1.6.0]. It's been almost 1 week since the new version was released.

**Comment by RodrigoTR04** [comment]
The github is meant to track yuzu issues, not mod updating, mods are maintained by their creators or people that take interest.

**Comment by renA21** [comment]
This is an issue tracker for developers and not a support forum.
You're better off contacting the mod creator(s) yourself.
