### ISSUE TITLE
Catherine: Full Body - Black screen on startup

### ISSUE THREAD

**Issue by NovaGit66** [yuzu-emu/yuzu#4994]
Yuzu Mainline 447

Intel Core i5-9600K
NVIDIA GeForce GTX 980
16 GB RAM

It seems that every time the game is loaded, it sits on a black screen- No graphics, no audio, no crashes- just a black screen. On Vulkan, the emulator crashes after the game is closed.

![Capture](https://user-images.githubusercontent.com/74826408/100157916-59f3c300-2e79-11eb-8213-6976847ba726.PNG)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5593075/yuzu_log.txt)

**Comment by GashetaUwU** [comment]
i have the same exact problem, but i have an i5 3570, rx 470 and 16 gb of ram, i always got a black screen i tried everything and yet nothing happened if you founded a solution for this or someone else please i would be very happy if you can share some kind of solution for this :c
