### ISSUE TITLE
Xenoblade Chronicles DE Lack of Grass/Flickering/Extruding Grass

### ISSUE THREAD

**Issue by DomesticatedG0at** [yuzu-emu/yuzu#5004]
Log (1174):
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5613034/yuzu_log.txt)

Log (1152):
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5599931/yuzu_log.txt)

**EDITS:**

**Tested on EA 1159.**
**No difference has been noticed.**

**Tested on EA 1174.**
**No difference has been noticed.**

Here's some footage of the grass in-game.
(The video was taken with the driver version 20.11.1 since it gave better performance):
https://youtu.be/f8RBkk2xMys

Specs:
CPU: AMD Ryzen 3700x
GPU: AMD RX5600xt 6gb (tested with its old and new bios)
RAM: 16gb DDR4 3600MHz
SSD: 1tb Samsung 860 EVO
Windows 10 Pro Version: 2004

Graphics Drivers Tested: 
        - AMD Adrenaline 20.11.2 (Used during screenshots)
        - AMD Adrenaline 20.11.1 (Get a constant 30 FPS when using this driver, but the graphical issues remain)

YUZU Settings (while taking screenshots):
![image](https://user-images.githubusercontent.com/75050502/100296824-701d8400-2f4a-11eb-8b76-fec38334905a.png)
![image](https://user-images.githubusercontent.com/75050502/100296847-7ad81900-2f4a-11eb-8ac0-ee49674975fa.png)
![image](https://user-images.githubusercontent.com/75050502/100296866-84618100-2f4a-11eb-8b80-3de66a1e66e7.png)
![image](https://user-images.githubusercontent.com/75050502/100297054-0651aa00-2f4b-11eb-8e92-945b375f9ed3.png)

I looked for an existing report for this and found nothing so hopefully this hasn't been discussed already.

This seems to only occur on the VULKAN API because running OpenGL crashes yuzu right away on my system so I could not test it. The grass is there on Ryujinx, so I'm sure the grass isn't a problem on OpenGL in yuzu either. 

Launching Xenoblade Chronicles DE on any version of yuzu, EA 1152 or MAINLINE 448, shows a lack of grass on the main screen, and flickering/extruding grass in game. The log I provided is from EA 1152 since the MAINLINE still has the vertex explosions and causes a crash after a while. 
All other textures seem to be working properly, characters, HUD, and menus have text and run without a hitch.

This was tested on all updates of Xenoblade Chronicles DE and nothing seems to change in each update, so I'm assuming that has nothing to do with it (Screenshots were taken .

Here are some screenshots of it occurring right as the game launches:
![TitleScreen - Start](https://user-images.githubusercontent.com/75050502/100295557-22534c80-2f47-11eb-826d-b66a5e50e31a.jpg)

Changing the camera angle also messes with it, making it a little more sporadic depending on how high the angle is:
The higher the angle the taller the grass.
The lower the angle the shorter and more non existent the grass.
![InGame-Start1](https://user-images.githubusercontent.com/75050502/100297211-65172380-2f4b-11eb-8aa3-f2157381f8ae.jpg)

![InGame-Start2-MovedCamera](https://user-images.githubusercontent.com/75050502/100295773-b6251880-2f47-11eb-9bda-6c94416d2be5.jpg)

Moving positions in game after a while yields no difference, it's either no grass, or crazy grass.
However, some other graphical bugs show up as well (The dark transparent texture on the left of the first image below):
![InGame-5mins-MovedLocations](https://user-images.githubusercontent.com/75050502/100295847-f2f10f80-2f47-11eb-8d1b-9531158a0510.jpg)
![InGame-5mins-AnotherLocation](https://user-images.githubusercontent.com/75050502/100295849-f6849680-2f47-11eb-98f7-845efa08ded1.jpg)
![Screenshot 2020-11-25 181457](https://user-images.githubusercontent.com/75050502/100296705-29c82500-2f4a-11eb-9753-cd5384f07aae.jpg)

There are also some shadow bugs (I think they're shadows at least):
![Screenshot 2020-11-25 181554](https://user-images.githubusercontent.com/75050502/100296763-52e8b580-2f4a-11eb-9cca-f8dc52d60f82.jpg)

I let the game run on the main screen for a while to let the title screen cinematic play through and then it reloads the title screen and I see this instead:
_To achieve this if it wasn't clear, just let the title screen cinematic play through._
![TitleScreen - After Cinematic](https://user-images.githubusercontent.com/75050502/100295967-3b103200-2f48-11eb-849b-cbd65a0cf2df.jpg)

I let the title screen run for about another 5 minutes and the green streaks slowly get longer and touch the bottom of the screen:
![TitleScreen - After Cinematic-After about 5 minutes](https://user-images.githubusercontent.com/75050502/100296167-c093e200-2f48-11eb-8cae-fc61326ff043.jpg)

This screenshot does show that the grass is being lit though. You can see the tip being illuminated by the Monado's blue light:
![TitleScreen - Monado Light on grass](https://user-images.githubusercontent.com/75050502/100296421-61829d00-2f49-11eb-8d56-c6a05ab631b5.jpg)

This second state of floating grass seems to repeat after the title screen cinematic for about 2 more iterations and does not return to the initial state of just "no grass" but instead gets worse:
![TitleScreen - After 4or5 cinematics](https://user-images.githubusercontent.com/75050502/100296499-a6a6cf00-2f49-11eb-9d9f-062820b7d5fd.jpg)
![Screenshot 2020-11-25 181142](https://user-images.githubusercontent.com/75050502/100296518-b58d8180-2f49-11eb-87ed-a4b8e2424a59.jpg)

**Comment by DomesticatedG0at** [comment]
Tested on EA 1159. 
No difference has been noticed.

**Comment by kimbulre** [comment]
Same problem here
AMD 5700XT

![title](https://user-images.githubusercontent.com/86902174/124372712-56ee6a00-dcc7-11eb-8a38-09b8c80acb8d.png)
