### ISSUE TITLE
Xenoblade Chronicles 2 Lighting/Shadow and Pixelated Textures/Effects issues

### ISSUE THREAD

**Issue by DomesticatedG0at** [yuzu-emu/yuzu#5007]
Log (1174):
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5613059/yuzu_log.txt)

Log (1152):
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5600197/yuzu_log.txt)
**At the end of the video below I do crash and when checking the log it says something about unreachable code and that I ran out of VRAM which makes sense since I only have 6gb to go around, but I'm pretty sure the VRAM is a separate issue from these graphical bugs**

**EDITS:**

**Tested on EA 1159.**
**No difference noticed.**

**Tested on EA 1174.**
**The lighting has become a little more washed out, since there isn't a shadow following you around anymore, instead they're almost non existent now. Everything else has remained the same.**
![image](https://user-images.githubusercontent.com/75050502/100555893-b41acc80-325b-11eb-9991-84b727a77843.png)
![image](https://user-images.githubusercontent.com/75050502/100555903-bed56180-325b-11eb-9937-402ea6aec6ab.png)
![image](https://user-images.githubusercontent.com/75050502/100555909-c72d9c80-325b-11eb-812d-a5650dcc2d20.png)

Here's some footage of the the graphical bugs in-game.
(The video was taken with the driver version 20.11.1 since it gave better performance):
https://youtu.be/KARn45wFOnE

Specs:
CPU: AMD Ryzen 3700x
GPU: AMD RX5600xt 6gb (tested with its old and new bios)
RAM: 16gb DDR4 3600MHz
SSD: 1tb Samsung 860 EVO
Windows 10 Pro Version: 2004

Graphics Drivers Tested:
- AMD Adrenaline 20.11.2 (Used during screenshots)
- AMD Adrenaline 20.11.1 (Get a constant 30 FPS when using this driver, but the graphical issues remain)

Xenoblade Chronicles 2 does not seem to run on the latest DLC and update, so everything you see here is without all of that.
Another note to make is that, just like #5004, OpenGL does not work. Therefore, this is a problem that is occurring on on a Navi based card on the VULKAN API. There is no rainbow flickering at all like in @Banjo-Kazooie-fan report #4995. Here we get lighting issues and large overcast shadows, and pixelated/flickering cloud textures.

Tests were done so far on both EA 1152 and MAINLINE 448, but for obvious reasons everything seen here is going to be from the EA build since it has the least amount of issues. 

To recreate any of these issues you must:

- Be an unfortunate owner of a Navi based AMD GPU (or Polaris if you want the fun in #4995)
- Be on Vulkan
- Be on the two drivers I stated above, or maybe others, but definitely those ones would do it
- Run the the game without DLC or Updates
- Use EA version 1152 (I haven't tested it on the newer versions yet, but will update this when I do)

YUZU Settings:
![image](https://user-images.githubusercontent.com/75050502/100310987-e67eae00-2f6b-11eb-8587-eee7e26163eb.png)
![image](https://user-images.githubusercontent.com/75050502/100311012-f0a0ac80-2f6b-11eb-83d3-aefb1db84b56.png)
![image](https://user-images.githubusercontent.com/75050502/100311024-f4ccca00-2f6b-11eb-825f-7b11e8e2f097.png)
![image](https://user-images.githubusercontent.com/75050502/100311032-fa2a1480-2f6b-11eb-8be4-3524c7a56248.png)

There is a lot of flickering too. This can be seen in the video posted at the top. (I guessing this is just shader compilation though).

Here are some screen shots of the shadows and lack of shadows, as well as the weird cloud stuff that's happening:
![Screenshot 2020-11-25 194428](https://user-images.githubusercontent.com/75050502/100302020-a82ac400-2f56-11eb-9d23-44fbc6df8664.jpg)

Getting in game, the text on the HUD are just fine, but as you can see there is an apparent lack of shadows and the clouds look fairly funky:
![Screenshot 2020-11-25 184330](https://user-images.githubusercontent.com/75050502/100302056-bc6ec100-2f56-11eb-8ae5-0387e24a6941.jpg)
![Screenshot 2020-11-25 184430](https://user-images.githubusercontent.com/75050502/100302078-c7295600-2f56-11eb-8988-382bfc81b1f4.jpg)

Once we turn around to an area with a lot more shadows going around, we can see that when Rex is inside the shadow square, he looks a lot less bleached:
![Screenshot 2020-11-25 184517](https://user-images.githubusercontent.com/75050502/100302184-00fa5c80-2f57-11eb-98b0-9ad5a76dad38.jpg)

Moving on into the building, the shadow follows us around, and the exposure does change as it should, meaning that the exposure does change when going from a bright place to a dark place to adjust to less light.
However, after it does that, a large shadow bow follows us around and eventually shadows disappear altogether:
![Screenshot 2020-11-25 184543](https://user-images.githubusercontent.com/75050502/100302274-3acb6300-2f57-11eb-97ec-1014b26af5f2.jpg)
![Screenshot 2020-11-25 184606](https://user-images.githubusercontent.com/75050502/100302277-3bfc9000-2f57-11eb-9290-a52a5bb9b926.jpg)
![Screenshot 2020-11-25 184631](https://user-images.githubusercontent.com/75050502/100302279-3d2dbd00-2f57-11eb-96d2-81f33c84da40.jpg)

There are probably more issues in other area with foliage and stuff shown by @gidoly in bug report #4923, edited it (10 days before this post) saying that it only occurred during multi-core rendering, however I haven't gotten to that point to see if that is the case yet so I'm not sure.

**Comment by KawaiiDinosaur** [comment]
Yuzu **EA 2889**
API: **Vulkan**
GPU: AMD 5700 XT
CPU: Ryzen 3700X
Driver: Mesa 22.1.4
System: Arch Linux

Lighting and shadows look fine, performance is good. But all those clouds don't render like they should.


![0100e95004038000_2022-08-04_22-07-43-676](https://user-images.githubusercontent.com/36821201/182982398-899a8d51-f91b-4dc0-a4ee-466076fdd07f.png)
![0100e95004038000_2022-08-04_22-07-59-878](https://user-images.githubusercontent.com/36821201/182982405-1fe1c23a-741c-4e17-a0e9-e1895ec10b9d.png)
![0100e95004038000_2022-08-04_22-08-24-547](https://user-images.githubusercontent.com/36821201/182982407-02448919-3896-4e7d-8157-17e6c92b8f44.png)
![0100e95004038000_2022-08-04_22-08-46-907](https://user-images.githubusercontent.com/36821201/182982408-727ef978-54ca-43e6-b682-1977f9f92f2a.png)
![0100e95004038000_2022-08-04_22-09-48-327](https://user-images.githubusercontent.com/36821201/182982409-e7a1e7b0-6315-4324-b81d-f59ef3b836a5.png)
![0100e95004038000_2022-08-04_22-11-48-448](https://user-images.githubusercontent.com/36821201/182982410-3d8ca959-325e-46f0-bacb-6bfdf7b7bca2.png)
![0100e95004038000_2022-08-04_22-13-29-321](https://user-images.githubusercontent.com/36821201/182982412-8b482026-17d1-4841-8d97-d78fef15b69c.png)
![0100e95004038000_2022-08-04_22-14-27-651](https://user-images.githubusercontent.com/36821201/182982416-aac00761-140f-4654-9c13-48306beefbcb.png)
![0100e95004038000_2022-08-04_22-15-05-248](https://user-images.githubusercontent.com/36821201/182982418-7ec77d59-4251-45bd-9809-18dbd88889ca.png)
![0100e95004038000_2022-08-04_22-20-18-450](https://user-images.githubusercontent.com/36821201/182982420-4f3ae8af-0549-4712-9334-7e9b5c31f3f3.png)

**Comment by gidoly** [comment]
fixed, for issue on comment pls open seperate issue
