### ISSUE TITLE
Missing HLE service commmand 'SaveReportWithUser' (prepo:u)

### ISSUE THREAD

**Issue by choppymaster** [yuzu-emu/yuzu#5008]
#### which unimplemented function are reporting?

SaveReportWithUser (prepo:u)

#### which games does it need?

From my information, It is needed for Animal crossing new horizons.

#### How do you found this issue?

I was reading the log that was uploaded by the ones on #5006, then I found the issue. 

#### Log?

Log is available on #5006, I'm suffering from a slow Internet :(

#### Labels

Unimplemented, HLE issue

**Comment by german77** [comment]
duplicated of #5006. Please do not open a issue referencing the same problem of another issue. Even if you already interpreted the problem.

**Comment by choppymaster** [comment]
My bad. Will never repeat.

**Comment by choppymaster** [comment]
> duplicated of #5006. Please do not open a issue referencing the same problem of another issue. Even if you already interpreted the problem.

Hey @german77 it is also needed for Snes: Nintendo switch online  (Ryujinx issue 807)
Requesting to reopen....
