### ISSUE TITLE
BLADE ARCUS Rebellion from Shining (0100C4400CB7C000) New Glitches

### ISSUE THREAD

**Issue by Aurez** [yuzu-emu/yuzu#5009]
New glitches after EA 1141 (and some fixes also :) )

My specs : W10-64 / i7-3770K / DDR3-16GB / RTX-2060S (457.09)
Log :  [yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5601472/yuzu_log.zip)

Yuzu EA 1141 (and earlier) : Only a few effects (mostly bloom/smoke) were broken (the rest was nearly perfect)
https://i.postimg.cc/prgVxkft/1141-1.jpg
https://i.postimg.cc/gcwZ97pQ/1141-2.jpg
https://i.postimg.cc/XNTyng7J/1141-3.jpg

Later versions : The bloom/smoke effects are now fixed but there are now many new glitches everywhere
https://i.postimg.cc/Jz37VNt9/1156-1.jpg
https://i.postimg.cc/tJVyrPLv/1156-2.jpg
https://i.postimg.cc/pTrPF3kH/1156-3.jpg

I hope it helps

**Comment by gidoly** [comment]
it is fixed on lastest build
![yuzu_AWELyPcfid](https://github.com/yuzu-emu/yuzu/assets/66776795/a66f8273-372b-4c14-be12-1af98424d747)
