### ISSUE TITLE
Crash Team Racing Nitro-Fueled graphical issues

### ISSUE THREAD

**Issue by tino0318** [yuzu-emu/yuzu#5012]
Yuzu EA 1163/ryzen 5 1600 AMD Radeon RX 570 8gb/drivers version 20.11.2/windows 10
something similar happened in pokemon sword EA 1146,already solved
but now the graphical issues happens to Crash.
log file : 
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5605314/yuzu_log.zip)

Undocked
![1](https://user-images.githubusercontent.com/56278811/100384780-bed92580-2fff-11eb-96a3-14d66a7d4d97.png)

![2222](https://user-images.githubusercontent.com/56278811/100384734-a10bc080-2fff-11eb-9c83-be9695971ea1.png)

Dock corrects it but the shadows dance
![1 5](https://user-images.githubusercontent.com/56278811/100384728-9c470c80-2fff-11eb-80f1-e9e2921ccff0.png)
![444](https://user-images.githubusercontent.com/56278811/100385091-6a827580-3000-11eb-9319-ed1954b3170c.png)

**Comment by FearlessTobi** [comment]
Please provide a log file.

**Comment by tino0318** [comment]
SOLVED IN EA 1170
