### ISSUE TITLE
Xenoblade 2 menu soft lock

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#5024]
xc2 randomly get soft lock on menu screen

screen after press save menu button screen locks and not show save screen:

<img width="1252" alt="20201127_161739" src="https://user-images.githubusercontent.com/66776795/100421843-84898a00-30cc-11eb-9d4d-689ba413f8c3.png">

how to replicate: need to go in to save menu and go out many times it will randomly occur

hardware: 
i7 8700k
16gb ram
rtx 2080s

driver version:
457.30

log:
[xc2.zip](https://github.com/yuzu-emu/yuzu/files/5606451/xc2.zip)

**Comment by gidoly** [comment]
close since issue made right after this one provide more info then this

**Comment by choppymaster** [comment]
One user also this problem (#5025)
