### ISSUE TITLE
Kirby Fighters 2: vibration stuck for a long time

### ISSUE THREAD

**Issue by v1993** [yuzu-emu/yuzu#5026]
Introduced by and first reported in #4866.

To reproduce:

1. Boot Kirby Fighters 2 (ver. 1.0.0)
2. Proceed to the main screen and go to settings (gear icon)
3. Switch rumble OFF and then back ON

As a result, after quick rumble peak (as expected), controller will keep vibrating slightly for a long time (about 2 mins, I think).

Log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5607281/yuzu_log.txt)

**Comment by Morph1984** [comment]
I was never able to get this game to boot after some time now, can you post a log with the following log filter applied?

`*:Info, Service.HID:Debug`

**Comment by v1993** [comment]
Log with filter applied: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5607858/yuzu_log.txt)
