### ISSUE TITLE
Yuzu crashes when loading games on EA

### ISSUE THREAD

**Issue by mineas312** [yuzu-emu/yuzu#5027]
I tried playing Super Smash Bros. Ultimate and emulator crashed on first loading screen before I could get to menu. Animal crossing: New Horizon seems to behave in the same way. 

SSBU:
![image](https://user-images.githubusercontent.com/17180405/100450094-5b113400-30b5-11eb-83af-42d7beb7676e.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5607854/yuzu_log.txt)

Animal crossing:
![image](https://user-images.githubusercontent.com/17180405/100450339-c4914280-30b5-11eb-8a85-6100fb00d56b.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5607863/yuzu_log.txt)

On the other hand, Pokemon: Let's Go, Evee! works as should:
![image](https://user-images.githubusercontent.com/17180405/100450554-281b7000-30b6-11eb-98ec-aae57438a5c7.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5607869/yuzu_log.txt)

I provide you all game logs and I want to tell that this issue applies only to EA version (I use EA1165). On yuzu 449 everything is fine. I changed various settings and I do not see any way to fix it.

My pc:
CPU: Ryzen 7 2700X
GPU: AMD R9 390
RAM: 16GB

**Comment by BSoDGamingYT** [comment]
This is not a support forum, please use the discord server for this kind of thing

**Comment by v1993** [comment]
Try experimenting with settings, like using OpenGL, turning off multicore and assembly shaders.

**Comment by OneHundredThousandWelcomes** [comment]
I've had a similar experience with the latest EA versions. It seems to be a Vulkan-specific issue. Try reverting to 1141.

**Comment by mineas312** [comment]
@BSoDGamingYT I am not asking for support, I am sure that this is a regression caused by latest merges. Tomorrow I will test which pr caused that.

**Comment by mineas312** [comment]
@BSoDGamingYT I am not asking for support, because it must be a regression if it works on a public version where on EA not.

Yes, Vulkan is causing the issue. OpenGL seems to work well.

**Comment by mineas312** [comment]
Today I found which EA version caused that. I tried EA 1141 and everything works properly but on 1144 not. I am afraid texture cache rewrite caused that. Maybe it is something wrong with AMD drivers.

**Comment by mirh** [comment]
It's definitively something with that. 
On my 2500U I can play until at least the intro of ACNH with the latest official version. 
If I run the new-texcache branch, I barely pass the loading screen, if even.

**Comment by choppymaster** [comment]
It occurs now?

**Comment by german77** [comment]
Probably fixed. Re-open if needed
