### ISSUE TITLE
OceanHorn 30 vs 60 fps audio issues. 1144 build Texture Cache Rewrite feature which makes the game render. 

### ISSUE THREAD

**Issue by somewhereintherainbow** [yuzu-emu/yuzu#5032]
Hello, i know this is experimental. I just wanted to report something about OceanHorn 2. On native 30FPS the audio is breaking a lot, but if you put the 60 FPS mod, and run it at those fps, the audio seems to be working properly. Also i will attach here the 60fps mod video with the audio working properly. 

I do have enable "Enable audio stretching" from yuzu options. 
Accuracy lvl high - normal and extreme. Same issue with 30 fps for those 3 options.

With native 30 fps: 
https://streamable.com/n28akj

With 60 FPS Patch
https://streamable.com/o2faof

**Comment by BSoDGamingYT** [comment]
Why are you labeling an audio issue as related to the texture cache rewrite?

**Comment by ogniK5377** [comment]
Please also attach a log file, thanks!

**Comment by somewhereintherainbow** [comment]
Hello, thanks for replying me BSoD. 

The answer to your question is because i'm testing the game on that specific build.  Yuzu 1144. 
![Capture](https://user-images.githubusercontent.com/75169583/100517444-8bf67500-3158-11eb-9725-d8ea0fa37179.PNG)

**Comment by somewhereintherainbow** [comment]
I'm trying to get the logs. But it won't boot now. I'm trying to install Yuzu from zero. Regards.

**Comment by BSoDGamingYT** [comment]
Please remove the TCR tag, this issue has no relation to the texture cache

**Comment by somewhereintherainbow** [comment]
> 
> 
> Please also attach a log file, thanks!

[Yuzu 60 fps MOD oceanhorn 2.txt](https://github.com/yuzu-emu/yuzu/files/5610770/Yuzu.60.fps.MOD.oceanhorn.2.txt)
[Yuzu 30 fps mod oceanhorn 2.txt](https://github.com/yuzu-emu/yuzu/files/5610771/Yuzu.30.fps.mod.oceanhorn.2.txt)


Here you have the logs files you were asking for. Thanks for replying and show interest in the topic. 
Best wishes.

**Comment by choppymaster** [comment]
Nice work :D

**Comment by choppymaster** [comment]
Hey @somewhereintherainbow , can you say who made this mod and which game versions does it works? Thanks.

**Comment by german77** [comment]
fixed by #6498
