### ISSUE TITLE
Feature request: Command line option "-f" to open in full screen mode

### ISSUE THREAD

**Issue by tastyratz** [yuzu-emu/yuzu#5033]
While you can often remember window size if terminating abruptly, some AHK terminations and less graceful quits while reliability is improved result in frequent window mode launches via a front end.

A full screen command line -f switch that ensures it always starts in full screen mode would improve upon this greatly for expected result.

**Comment by choppymaster** [comment]
Mentioning: #5177

**Comment by KINGLIFER** [comment]
was this implemented? I tried and did not see a result. is it a different character used?
