### ISSUE TITLE
Unreachable code error in Smash Ultimate

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#5035]
Tried to play spirits adventure in a new game. When i loaded the first level nothing was renderering, only sounds came out. Even when i managed to exit the match, everything was still black.

Log file:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5612100/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Pretty sure this is a known issue. Besides patience for it to be worked out I don't believe you'll be receiving support for piracy.
