### ISSUE TITLE
Age of Calamity Char selection bug

### ISSUE THREAD

**Issue by YuNarukamii** [yuzu-emu/yuzu#5036]
When i try to go the char menu it drops to 0 FPS and crashes.
Im using Yuzu EA 1131
My Specs:
Intel I5 5500k Professor
GTX 1050 Ti
16GB Ram

**Comment by G-Spawn** [comment]
Please consider this which should have been shown to you when you hit 'create new issue'
- You have read the above.
- You have provided the version (commit hash) of yuzu you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

**Comment by G-Spawn** [comment]
Besides that I believe this is known / reported before as the game is unstable for the time being?

**Comment by YuNarukamii** [comment]
Yeah But with #4871 you only Need to uncheck Use assambly shaders

**Comment by G-Spawn** [comment]
this isn't something you'd receive a 'quick' answer for. Time - patience as the emulator gets further developed to handle oddball games like this. I've yet to see any setup get past this character selection screen smoothly.

**Comment by YuNarukamii** [comment]
K

**Comment by choppymaster** [comment]
As G spawn said, this is a duplicate of #5001. Also log is needed.

**Comment by YuNarukamii** [comment]
Im getting it

**Comment by YuNarukamii** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5612236/yuzu_log.txt)
here ya go

**Comment by G-Spawn** [comment]
Thank you. Hopefully the issue will get sorted out someday as for now there is none that I know of.

**Comment by YuNarukamii** [comment]
Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
thats the last line seems like the texture_cache is broke

**Comment by YuNarukamii** [comment]
or something in it

**Comment by YuNarukamii** [comment]
im looking in it

**Comment by YuNarukamii** [comment]
I can switch chars with ryunjix so my game isnt corruptet

**Comment by YuNarukamii** [comment]
that bug is with no reason away lol

**Comment by BSoDGamingYT** [comment]
This is a duplicate of issue #4871

**Comment by ReinUsesLisp** [comment]
Closing as duplicate.

**Comment by YuNarukamii** [comment]
@BSoDGamingYT it is a duplicate of #5001 stupid
