### ISSUE TITLE
Hyrule Warriors AOC character menu broken

### ISSUE THREAD

**Issue by CaesarMagno96** [yuzu-emu/yuzu#5037]
Hyrule Warriors AOC 1.0.1
YUZU 452
Windows 10
I5 10500
RTX2070
DDR4 32GB

Everytime I open the character menu (where you change outfit and weapons) Yuzu and the pc freezes to death
Attached the log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5612710/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
This is a duplicate issue...please look to see if an existing issue exists before opening a new one

**Comment by ReinUsesLisp** [comment]
Closing as duplicate.
