### ISSUE TITLE
Splatoon 2 Bug - Can't Climb Some Walls

### ISSUE THREAD

**Issue by Tabby4675** [yuzu-emu/yuzu#5038]
Quite some time ago, the "not being able to dive in ink" bug was fixed in yuzu. However, I've came across some weird instances where the game doesn't let me climb the walls after inking them, this makes some Sunken Scrolls impossible to get (Sector 1 Level 3) and can be quite annoying.

Do note that not all walls behave this way, some of them work as intended while others just don't let you climb them at all. I've tried with both async enabled and disabled just to be sure and it did not fix the issue.

One more thing to note is my GPU, which is an Intel iGPU, maybe its an issue exclusive to these? Either way, this should be looked into.

The Yuzu version is the latest as of writing this, Yuzu 452.

**Comment by choppymaster** [comment]
Please provide a log file please. Thanks.

**Comment by FearlessTobi** [comment]
Closing in favor of https://github.com/yuzu-emu/yuzu/issues/4982.

**Comment by Tabby4675** [comment]
@FearlessTobi Both issues are different tho?
