### ISSUE TITLE
Animal Crossing New Horizons freezes at Nook Shopping at ABD

### ISSUE THREAD

**Issue by zivshek** [yuzu-emu/yuzu#5039]
Here's a screenshot of when it freezes, 
![Screenshot 2020-11-30 093928](https://user-images.githubusercontent.com/24230685/100623305-f68de900-32ef-11eb-8dbc-6e5529df8937.png)
and here's the log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5616538/yuzu_log.txt)

yuzu Version: yuzu 452             . | HEAD-mainline-636-3894-geba9c52ad
Host CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz | AVX2 | FMA
Host OS: Windows 10 (10.0)
Host RAM: 15.85 GB
Host Swap: 39.06 GB

**Comment by Krendeled** [comment]
Having the same issue. When is this getting fixed?

**Comment by choppymaster** [comment]
Devs don't report when it is going to be fixed. It will be fixed when they implement the services needed for it.

**Comment by benderscruffy** [comment]
is this still an issue ??

**Comment by liamwhite** [comment]
Comment with an updated yuzu log if this is still relevant
