### ISSUE TITLE
kingdom hearts melody of memory-crash after cinematic

### ISSUE THREAD

**Issue by tino0318** [yuzu-emu/yuzu#5052]
Yuzu EA 1180/ryzen 5 1600 AMD Radeon RX 570 8gb/drivers version 20.11.1/windows 10

after entering the museum to see the cinematics (it also happens when playing in story mode) only the first frame is seen and it pauses when trying to exit the cinematics the game crashes.
-previously it was possible to reproduce cinematics but with stuttering with 60fps

yuzu log : [yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5625048/yuzu_log.zip)

![11111111111111](https://user-images.githubusercontent.com/56278811/100788952-92088200-33f4-11eb-87ec-e832bf97cbed.png)

only 1 frame
![2222222222222](https://user-images.githubusercontent.com/56278811/100788972-97fe6300-33f4-11eb-9642-a2748eb72ee7.png)

crash
![3333333333333333](https://user-images.githubusercontent.com/56278811/100788983-9a60bd00-33f4-11eb-8b88-e2af95cfd263.png)

**Comment by G-Spawn** [comment]
This issue shouldn't happen on latest yuzu (mainline/early access). Feel free to reopen issue should it still still happen to you once you update & provide new log.
