### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by Jiunginlix** [yuzu-emu/yuzu#5053]

**Comment by G-Spawn** [comment]
Please read the FAQ:
https://yuzu-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of yuzu you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).


In case you missed it the first time.
