### ISSUE TITLE
Parameter to use specific profile

### ISSUE THREAD

**Issue by DanMossa** [yuzu-emu/yuzu#5054]
As it is currently, for me to switch profiles I have to open Yuzu and then change a profile. It would be nice to specify a profile in the command line when opening up a game directly.

**Comment by choppymaster** [comment]
Do you meant the feature like #4896 ?

**Comment by DanMossa** [comment]
@choppymaster  I do not.
That is game specific input.
I'm looking to have two shortcuts on my desktop to run acnh with yuzu.
I want one shortcut to use one game profile, and the second shortcut to use the other.

**Comment by choppymaster** [comment]
Ah okay. I understand. Sorry for the  corruption.

**Comment by german77** [comment]
Implemented in #6116
