### ISSUE TITLE
Splatoon 2: missing body texture (OpenGL)

### ISSUE THREAD

**Issue by XPoppyX** [yuzu-emu/yuzu#5055]
This happened after fixing the shadows
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5629640/yuzu_log.txt)

![splatoon2 65](https://user-images.githubusercontent.com/61259627/100879466-3c7eb480-348a-11eb-8233-db1a6e0becee.png)

-----------------------------------
Yuzu EA **1181**
Windows 10 20H2
i7 8700k
GTX 1080 Ti
16 GB Ram

**Comment by choppymaster** [comment]
There is an issue in Pascal GPUS where characters do not render properly when assembly shaders are turned on. It's a known issue.

**Comment by XPoppyX** [comment]
I see, thanks
