### ISSUE TITLE
Textures and lighting broken after upgrating to a RTX 3080

### ISSUE THREAD

**Issue by lunfardo** [yuzu-emu/yuzu#5056]
Yesterday I upgraded my GPU from a 1660 super to 3080. Everything was working perfectly on my 1660s, but after upgrading Yuzu stopped rendering correctly (normal games are fine).  I tried older drivers, switch between Vulkan/OpenGL, shader cache on/off but nothing worked.

Yuzu Version 455
CPU: Ryzen 2700x
GPU: Nvidia 1660S/3080
Graphics backend: Both Vulkan and OpenGL

![broke3080](https://user-images.githubusercontent.com/5571855/100884004-42d45700-34b1-11eb-86df-718a38a87ce1.png)

**Comment by choppymaster** [comment]
Please provide a log file. BTW which game you tested?

**Comment by lunfardo** [comment]
I will post logs in a moment, I just connected my 1660 super again, test the same scene and works perfectly (same configuration, drivers, etc..)

![1660sworks](https://user-images.githubusercontent.com/5571855/100887419-3e11a200-34b5-11eb-9ff8-184f76537b61.png)

**Comment by lunfardo** [comment]
Game is "Fire Emblem: Three Houses", here are the logs for the 3080
[logs_broken_texture_lighting_three_houses.txt](https://github.com/yuzu-emu/yuzu/files/5630062/logs_broken_texture_lighting_three_houses.txt)

**Comment by goldenx86** [comment]
Try with the latest driver version, you are using an early release one. Also, test OpenGL.

**Comment by Sir-BLaDE** [comment]
I have the exact same issue with my 3080 latest driver 457.51 Windows 10 20H2

**Comment by goldenx86** [comment]
Unfortunately the situation in our country doesn't allow @ReinUsesLisp or me to get an Ampere for now. A 3060Ti is selling for 1000 USD.
We will wait for real prices, until then, test playing with async and assembly shaders, Vulkan and OpenGL.

**Comment by SpaceCowboy321** [comment]
I am having the same issue. I am running version 573 with an Nvidia RTX 3080 with the latest drivers. I have attached the log file below.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7043415/yuzu_log.txt)

**Comment by v1993** [comment]
Version 573 is a very old one. Please update to something more recent and try again.

**Comment by gidoly** [comment]
this should be fixed on last mainline with disabling float 16 for those hardware
