### ISSUE TITLE
Just Dance 2019 & 2020 Crash to Desktop after texture cache rewrite

### ISSUE THREAD

**Issue by AshTrayMaze** [yuzu-emu/yuzu#5057]
As the title says, from EA 1144 Just Dance 2019 and 2020 make yuzu crash to desktop just after shaders loading. Disabling NVDEC, Async Shaders or Use of shaders cache doesn't make any difference.

Before EA 1144 those title went ingame but with songs videos broken, blurried of pixelated.

**Comment by BSoDGamingYT** [comment]
None of these issues are related to those changes. The are caused by the new texture cache rewrite

**Comment by AshTrayMaze** [comment]
Sorry, i'm not code savy, tell me if i have to edit the issue to leave a helpful hint for the devs or should i remove it.

**Comment by FearlessTobi** [comment]
Can you please provide a log file as well?

**Comment by AshTrayMaze** [comment]
Yes, it's from 1184 but the issue still exist.
[yuzu_log - JD20 crash.txt](https://github.com/yuzu-emu/yuzu/files/5646656/yuzu_log.-.JD20.crash.txt)

**Comment by AshTrayMaze** [comment]
Issued fixed in EA 1195
