### ISSUE TITLE
Tried to unwrap empty ResultVal [error]

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#506]
## Hardware Specs : 
- Nvidia GeForce GTX 960
- Intel I7-7700K @ 4.5Ghz
- 8 GB Of Ram 3200Mhz
- Windows 10 Pro

## The issue : 
When I launch for example 1.2.Switch or splatoon 2, yuzu crash with the error "Tried to unwrap empty ResultVal", @Hexagon12 said to me to restart the game another but even if i restart it the error appear.

## List of games with this error : 
- 1.2.Switch
- Splatoon 2
- Mario+Rabbids Kingdom Battle

## the 1.2.Switch Log : 
[→ Click Here ←](https://gist.github.com/greggameplayer/8b6510a79ff74f24effbad688375dc93)

The last part of the log : 
![image](https://user-images.githubusercontent.com/33609333/40926959-c96e146c-681d-11e8-814a-f788372848cc.png)

**Comment by Hexagon12** [comment]
Enable the logging level to Debug and look for the path that will be written next to the assert. Now create the path manually, since games sometimes try to access save data even before the folders get created.

**Comment by mailwl** [comment]
then. need to return error to game, maybe it creates new save (instead of yuzu crash)

**Comment by Hexagon12** [comment]
We need to hwtest the exact error code that happens when the games try to access a non-existant folder.

**Comment by greggameplayer** [comment]
@Hexagon12 how to enable the logging level ?

**Comment by greggameplayer** [comment]
You're right i have been able to go further when i have create the save folder myself

**Comment by Hexagon12** [comment]
This should be fixed with VFS implementing automatic savedata folder creation.

Requesting to close.
