### ISSUE TITLE
[Feature Request] Implementation of motion controls via SDL2

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#5060]
As discussed in PR #4594, this would permit reading motion control data from input devices via SDL2.  As @v1993 indicated in the above PR, SDL2 registers input devices with axles that correspond to acceleration and gyro inputs.  

This relatively lightweight implementation would be particularly useful in cases such as ds4 pads or wiimotes under linux where CemuHook is more cumbersome to setup and use.

**Comment by german77** [comment]
As I said before. I need a single example that does this. I never had any controller output the gyro as an axis.

**Comment by v1993** [comment]
On Linux, Switch Pro Controller and JoyCons with https://github.com/nicman23/dkms-hid-nintendo driver (which you want thanks to improved support over generic driver anyways) do this, so does WiiMote without any extra drivers.

AFAIK this is not the case on Windows, or at least so I read in Dolphin emulator blog from around 2016-2018.

**Comment by JMC47** [comment]
There's no good way to get motion controls via Windows Controller APIs (yet?) but on Linux it is anything goes.  A lot of the MotionInput stuff that had to be done custom on Windows via specialized drivers could just be done on Linux without issues.

**Comment by MaddTheSane** [comment]
If you are on macOS Big Sur or later, the GameController framework also allows you to query if a controller has a gyroscope. And yes, the GameController framework does support PS4 controllers. And yes, SDL 2.0.14 should be able to use the GameController framework on GC-compatible controllers.

**Comment by v1993** [comment]
So after a bit of extra research about this topic and poking Dolphin around...

There's currently no good (that is, non-hacky) way to read Accel/Gyro using SDL2. However, it would be possible with libevdev/libudev input backend as it is done in Dolphin. Only caveat is that there's no really standard orientation, so it still would need to be configured manually.

I guess the easiest solution for now is to write libevdev based DSU server. I'll hopefully get to it soon.

**Comment by v1993** [comment]
@german77 By the way, can you, please, share "SixAxis tester" mentioned in [September's blogpost](https://yuzu-emu.org/entry/yuzu-progress-report-sep-2020/)? It would be of great help for testing DSU implementations.

P.S.: does it display picture as if display was horizontal? It's a little confusing to me.

**Comment by german77** [comment]
yes it's horizontal. I'm pretty bad with opengl. Contact me via discord

**Comment by german77** [comment]
Implemented here #6244

**Comment by Shoegzer** [comment]
Thanks @german77 .  Looking forward to testing this on my ds4 pad when it's ready.

**Comment by Shoegzer** [comment]
Posting detailed SDL2 motion test results here since it's more relevant here than on the PR thread.  I tested against commit bfe8816f7c2bb4338efff9763a6f7abb1b66977a, by selecting "Pro Controller" and "PS4 Controller 0" as input device, then clicking "Motion 1" in the UI.  The message "Shake!" remains even after shaking the controller, and nothing appears to be set.

To rule out this being hidraw permissions related, I added the following udev rule in `/etc/udev/rules.d/99-hidraw.rules`:

`KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="plugdev"`

I then restarted with `udevadm control --reload` and ran the test again but still no motion was detected.

Test platform is Linux Mint 20.1 / kernel 5.11 with ds4 controller connected via bluetooth.  All other controller settings (button mappings, rumble etc.) work properly.  Tested against a yuzu binary compiled with gcc 10.2.0 straight from the source directory build/bin/yuzu.

**Comment by v1993** [comment]
Are you in plugdev group (you need to be)? Use `groups` to check.

Again, please take this to discord.

Also, this issue probably can be closed now that relevant PR was merged.

**Comment by Shoegzer** [comment]
Confirmed, the user running yuzu is in the plugdev group.  I'm not on discord.  I'll close this issue since it was related to a feature request that has been fulfilled (thanks again to both you @v1993 and @german77) and started #6325 to help further testing on the residual issue itself.
