### ISSUE TITLE
does my ishue abear on diskord

### ISSUE THREAD

**Issue by NotWhatYouExpected** [yuzu-emu/yuzu#5063]

**Comment by NotWhatYouExpected** [comment]
does it

**Comment by NotWhatYouExpected** [comment]
someone in their discord pls tell me I got ban

**Comment by G-Spawn** [comment]
this is meant for tracking issues with the emulator. Nobody care's about your ban.

**Comment by NotWhatYouExpected** [comment]
shut the fuck up loser

**Comment by NotWhatYouExpected** [comment]
sorry

**Comment by NotWhatYouExpected** [comment]
do you now were I can get nsps?

**Comment by NotWhatYouExpected** [comment]
hello?
@G-Spawn

**Comment by G-Spawn** [comment]
As this issue serves no purpose and you are just wasting time I'd suggest you just close this issue. You get 0 support for piracy and you get your files from your switch period.

**Comment by NotWhatYouExpected** [comment]
shut the fuck u ploser

**Comment by NotWhatYouExpected** [comment]
ok I just bought a switch

**Comment by NotWhatYouExpected** [comment]
how do I get games now pls pls pls pls pls

**Comment by NotWhatYouExpected** [comment]
@G-Spawn

**Comment by G-Spawn** [comment]
Cool. It needs to be a moddable switch. This is an issue tracker for an emulator not a how to do things github. https://yuzu-emu.org/help/quickstart/

**Comment by NotWhatYouExpected** [comment]
it is

**Comment by NotWhatYouExpected** [comment]
ok do you discord

**Comment by NotWhatYouExpected** [comment]
send #

**Comment by G-Spawn** [comment]
No.
