### ISSUE TITLE
[Feature Request] Right click the game to open compatibility page.

### ISSUE THREAD

**Issue by choppymaster** [yuzu-emu/yuzu#5120]
Opened by seeing the feature on cemu.
Feature request to add an option for opening the specific game's compatiblity page by right clicking the game. It would be very user friendly and easy to open compatiblity page for game specific configuration, known issues and the current state. (After updating the compatibility list.)

**Comment by Morph1984** [comment]
This feature already exists named "Navigate to GameDB entry"

**Comment by choppymaster** [comment]
Oh my bad
