### ISSUE TITLE
Dead or Alive Xtreme 3 Scarlet

### ISSUE THREAD

**Issue by jojorne** [yuzu-emu/yuzu#5125]
I was trying to run Dead or Alive Xtreme 3 Scarlet Free Edition on an AMD Phenom II x4 with the unsafe option, 16GB of RAM and a GTX 1060 6GB VRAM. You can get a free copy of the game from the official japanese site.

Any version of yuzu before the Texture Cache Rewrite will not run it, yuzu spends a huge amount of disk bandwidth and CPU power trying to write all the non-stopping shader errors and stubs to the log file.

Here is the "*:Error" part of the log after running it for awhile:

> libpng warning: iCCP: known incorrect sRGB profile
> Kernel.SVC <Error> core\hle\kernel\svc.cpp:MapSharedMemory:1268: Address does not fit within the map region, addr=0x00000011CA604000, size=0x0000000000040000
> Debug <Critical> core/hle/ipc_helpers.h:ValidateHeader:157: Assertion Failed! normal_params_size value is incorrect
> Debug <Critical> core\hle\service\am\applets\applets.cpp:GetApplet:263: Assertion Failed! No backend implementation exists for applet_id=00! Falling back to stub applet.
> QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
> Debug <Critical> core\hle\service\am\applets\controller.cpp:Execute:213: Assertion Failed! ControllerSupportMode=1 is not implemented
> HW.GPU <Error> video_core\texture_cache\image_base.cpp:AddImageAlias:136: Compressed to compressed image aliasing is not implemented

And here are the problems I encountered:

- Any settings other than the Default Anisotropic Filtering will produce shader artifacts;
- Very long loading times, even after going back and forth multiple times;
- Just leaving the game running in the menus or playing will cause the entire system to freeze for a few seconds from time to time;
- ~~The very own yuzu's screenshot system crashes after a few minutes of playing the game, going back and forth from the menus or changing the poses and scenes. It does not recover~~ [fixed since ea 1220];
- The opening video doesn't run smoothly with the NVDEC option. It starts and freezes, but the sound continues normally;
- All characters will have a burning scar on their face, chin and neck;
- If you try to open the eShop, the online manual or even if you try to use the ingame screenshot system, the entire emulator crashes and damages the disk shader cache. After that, the game will no longer start unless you delete the disk shader cache files;
- And of course, the ingame screenshot system doesn't work. Trying to take pictures or accessing the pictures ingame will crash yuzu.

Other than that, the game runs well, thank you. I would be very grateful if someone could take a look at these issues and again,

Thank you.

**Comment by FearlessTobi** [comment]
Please also provide the full log file.
