### ISSUE TITLE
Atelier Shallie DX: unimplemented function 'GetAudioOutPlayedSampleCount'

### ISSUE THREAD

**Issue by heavysink** [yuzu-emu/yuzu#5129]
Build from mainline 458.
Starting new game, after intro movie it freezes. Log file shows:
[ 139.221061] Debug <Critical> core/hle/service/service.cpp:ReportUnimplementedFunction:152: Assertion Failed! Unknown / unimplemented function 'GetAudioOutPlayedSampleCount': port='IAudioOut' cmd_buf={[0]=0x6, [1]=0x8, [2]=0x0, [3]=0x0, [4]=0x49434653, [5]=0x1, [6]=0xA, [7]=0x0, [8]=0x1E8F6730}
[ 139.221067] Debug <Critical> core/hle/kernel/hle_ipc.cpp:ParseCommandBuffer:173: Assertion Failed!
[ 139.223582] Service.AM <Warning> core/hle/service/am/am.cpp:SetTerminateResult:1373: (STUBBED) called, result=0x0001A80A
[ 139.223934] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:612: Signalling debugger, PANIC! info1=0x0000001033C47E90, info2=0x0000000000000004
[ 139.223938] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:operator():594: debug_buffer_err_code=1A80A
[ 139.223940] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:662: Emulated program broke execution! reason=0x0000000000000000, info1=0x0000001033C47E90, info2=0x0000000000000004
[ 139.223941] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:266: Backtrace, sp=000000000000000E, pc=0000000009C3F998
[ 139.223943] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:267: Module Name         Address             Original Address    Offset              Symbol
[ 139.223944] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:269: 
[ 139.244152] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:273: sdk                 0000007100183AD8    0000000009A39AD8    0000000000183AD8    _ZN2nn4diag6detail5AbortEPKNS_6ResultE
[ 139.244157] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:273: sdk                 000000710018249C    0000000009A3849C    000000000018249C    _ZN2nn4diag6detail10VAbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoES3_St9__va_list
[ 139.244158] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:273: sdk                 0000007100182560    0000000009A38560    0000000000182560    _ZN2nn4diag6detail9AbortImplEPKcS3_S3_iPKNS_6ResultES3_z
[ 139.244159] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:273: sdk                 000000710009A358    0000000009950358    000000000009A358    _ZN2nn5audio28GetAudioOutPlayedSampleCountEPKNS0_8AudioOutE
[ 139.244159] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:273: main                0000007100530600    0000000008534600    0000000000530600    
[ 139.244160] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:273: main                00000071005304C8    00000000085344C8    00000000005304C8    
[ 139.244161] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:273: sdk                 00000071003344B4    0000000009BEA4B4    00000000003344B4    
[ 139.244162] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:273: sdk                 0000007100338980    0000000009BEE980    0000000000338980    
[ 139.244162] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:273: sdk                 00000070F6749FFC    FFFFFFFFFFFFFFFC    FFFFFFFFF6749FFC 

Full log file attached.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5646471/yuzu_log.txt)

**Comment by choppymaster** [comment]
Also needed for **Atelier Escha and Logy Tasogare no Sora no Renkinjutsushi DX** ,
**Medarot Classics Plus Kuwagata Ver** and **Medarot Classics Plus Kabuto Ver**.

**Comment by reina-n** [comment]
Ciel Nosurge Ep03 - Ch13 , Ep04 - Ch00 (prologue) also needs GetAudioOutPlayedSampleCount.
> port='IAudioOut' cmd_buf={[0]=0x6, [1]=0x8, [2]=0x0, [3]=0x0, [4]=0x49434653, [5]=0x1, [6]=0xA, [7]=0x0, [8]=0x49434653}

both scenes seem waiting playback's tail and want to go the next scenes with white filled screen.
InfoUpdater::UpdateRendererInfo seems know how many samples were queued . is it nearly equal played one isnt it.

**Comment by reina-n** [comment]
think you for the implementation of GetAudioOutPlayedSampleCount in  mainline 667
it works very well. i think the counter had to be cleared when playback is ended.

**Comment by ogniK5377** [comment]
Implemented with #6504
