### ISSUE TITLE
Feature request: option to limit how many threads can work when loading a disk shader cache with OpenGL.

### ISSUE THREAD

**Issue by RodrigoTR04** [yuzu-emu/yuzu#5137]
When loading a disk shader cache with OpenGL CPU usage goes up to 100% and makes temperatures go way too high, making almost all laptops with H letter processors (both Intel and AMD CPUs) thermal throttle. 
Gray line is clock speed, purple is temperature, orange is CPU usage %. (This was loading a cache of ~5000 shaders in SWSH 4 consecutive times with Assembly shaders turned on, with it off is almost impossible to use a disk cache)
![image](https://user-images.githubusercontent.com/65554156/101258180-7dcbca00-36ff-11eb-8b23-a4ef69f8591d.png)
Parameters of the graphic above. Tested with an i7-9750H (Lenovo Y540)
![Screenshot 2020-12-05 134200](https://user-images.githubusercontent.com/65554156/101258201-b66ba380-36ff-11eb-99cc-dc72d9f206dd.png)
![Screenshot 2020-12-05 135324](https://user-images.githubusercontent.com/65554156/101258442-4bbb6780-3701-11eb-807c-bdd34363b663.png)
![Screenshot 2020-12-05 135424](https://user-images.githubusercontent.com/65554156/101258465-67267280-3701-11eb-8d2d-6b4e723a0660.png)

Request is to add an option to limit how many threads (suggestion 3-4) can be used to load the shader cache from disk on game boot, so that thermal throttling doesn't happen, these are the current gen laptop CPUs that suffer with the problem:

Intel:
i9-10980HK | 8c/16t 
i7-10875H   | 8c/16t 
i7-10850H   | 6c/12t
i7-10750H   | 6c/12t
i5-10400H   | 4c/8t
i5-10300H   | 4c/8t
(Same goes for 8th and 9th gen, but those are very rarely sold anymore after 10th launched)

AMD:
Ryzen 5 4600H(S) | 6c/12t
Ryzen 7 4800H(S) | 8c/16t
Ryzen 9 4900H(S) | 8c/16t
(Ryzen 3000 series is underpowered and doesn't suffer nearly as much)

**Comment by adityaruplaha** [comment]
1. Is this specific to transferable or precompiled shaders?
2. Do other heavy I/O operations suffer similarly?

I'm just trying to figure out which step is causing the spike in usage. If it is the `Load()` function (not the I/O operation), is it even possible to keep temps under control without reducing loading speed significantly?

(I'm not very familiar with yuzu's codebase, so sorry if I said something stupid.)

**Comment by RodrigoTR04** [comment]
Only used shaders compiled locally, didn't transfer, for other I/O operations I have no idea, slowing things down only makes matter worse, with Assembly shaders it's a bit too slow when you pass the ~4000 shaders so throttles for a split second, without it thermal throttles for a longer period because it still hits all the CPU threads.

**Comment by goldenx86** [comment]
Temporal workaround, migrate to AMD, they driver doesn't allow multithreaded building. ¯\_(ツ)_/¯

**Comment by NielsGx** [comment]
amd cpu ? seriously?

**Comment by RodrigoTR04** [comment]
> amd cpu ? seriously?

Still thermal throttles, it's all about the laptop model. A properly cooled Intel can be 20°C less than a terribly cooled AMD and vice versa.

**Comment by ReaperOfSouls1909** [comment]
Use task manager and limit yuzu affinity wise till its finished that can do for now

**Comment by RodrigoTR04** [comment]
I'm leaving yuzu for the time being.

**Comment by FearlessTobi** [comment]
This still seems to be a valid issue.

**Comment by RodrigoTR04** [comment]
This is not an issue, it's a feature request and it's no longer being requested, closing it again.
