### ISSUE TITLE
Yuzu crashing Linux Mint 20

### ISSUE THREAD

**Issue by dukenukemx** [yuzu-emu/yuzu#5138]
I've compile yuzu from github and tested it on two machines.  One being my Ryzen 1700 with R9 Fury and the other a FX8350 with a Radeon HD 7850.  Both machines are using AMDGPU for a driver and both have vulkan support.  I've tried both OpenGL and Vulkan and turned off and on many features, but it still crashes after trying to load a game.  The Yuzu build is master-f2f346e11.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5647526/yuzu_log.txt)

[yuzu_strace.txt](https://github.com/yuzu-emu/yuzu/files/5647538/yuzu_strace.txt)

**Comment by Danacus** [comment]
Have you followed [these steps](https://yuzu-emu.org/wiki/recommended-gpu-drivers-for-linux/)? For yuzu to work on AMD, Mesa must be compiled with LLVM 12. Also note that using Vulkan may crash the driver when using AMD GPUs on Linux, so you might be better off using OpenGL.

**Comment by dukenukemx** [comment]
I'm already using Oibaf PPA for drivers.  Unfortunately this seems to be the same issue from a while back.  https://github.com/yuzu-emu/yuzu/issues/4058  I was compiling from master not mainline.  Compiling from mainline got the emulator to stop crashing but like you said Vulkan seems unstable as it either crawls in performance or Mario is missing his face in Odyssey.  OpenGL fixes those problems but I can stop the emulator without force quitting it.  It seems as time goes on, Linux support gets worse for Yuzu.

**Comment by Danacus** [comment]
> It seems as time goes on, Linux support gets worse for Yuzu.

I"m having the same impression. Although the performance with OpenGL had doubled on my system compared to a few months ago. I just wish they could fix Vulkan on Linux, but it's probably not that easy.

**Comment by gal20** [comment]
This is expected behaviour. The yuzu-emu/yuzu repository is for development. Use the yuzu-emu/yuzu-mainline instead.

**Comment by dukenukemx** [comment]
> 
> 
> This is expected behaviour. The yuzu-emu/yuzu repository is for development. Use the yuzu-emu/yuzu-mainline repo instead.
Just tried compiling from mainline and got this error.  

FAILED: src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/yuzu.cpp.o 
/usr/bin/c++  -DARCHITECTURE_x86_64=1 -DBOOST_ASIO_DISABLE_CONCEPTS -DBOOST_DATE_TIME_NO_LIB -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DHAS_VULKAN -DNDEBUG -DYUZU_UNIX=1 -D_FILE_OFFSET_BITS=64 -D_GLIBCXX_USE_CXX11_ABI=1 -I/home/demetrius/.conan/data/catch2/2.13.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/home/demetrius/.conan/data/nlohmann_json/3.8.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/home/demetrius/.conan/data/zlib/1.2.11/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/include -I../src/. -I../src/yuzu_cmd/../../externals/Vulkan-Headers/include -I../externals/./microprofile -I../externals/inih/. -I../externals/glad/include -isystem /home/demetrius/.conan/data/boost/1.73.0/_/_/package/020be167c6748e1e82d613b2837bf63074e10744/include -isystem /home/demetrius/.conan/data/fmt/7.1.2/_/_/package/b911f48570f9bb2902d9e83b2b9ebf9d376c8c56/include -isystem /home/demetrius/.conan/data/bzip2/1.0.8/_/_/package/da606cf731e334010b0bf6e85a2a6f891b9f36b0/include -isystem /usr/include/SDL2 -O3 -DNDEBUG    -D_GLIBCXX_USE_CXX11_ABI=1 -Wall -Werror=implicit-fallthrough -Werror=missing-declarations -Werror=reorder -Werror=unused-result -Wextra -Wmissing-declarations -Wno-attributes -Wno-invalid-offsetof -Wno-unused-parameter -fconcepts -mcx16 -pthread -std=gnu++2a -MD -MT src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/yuzu.cpp.o -MF src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/yuzu.cpp.o.d -o src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/yuzu.cpp.o -c ../src/yuzu_cmd/yuzu.cpp

**Comment by FearlessTobi** [comment]
The "crashes" are very likely caused by you using a build that has assertions enabled.
As for your build issues, I'd suggest opening a new issue or hopping onto our Discord in order to get support.
