### ISSUE TITLE
Motion server port autoreset in EA 1195

### ISSUE THREAD

**Issue by AshTrayMaze** [yuzu-emu/yuzu#5169]
I'm using Betterjoyforcemu with non default server port. 

Under the control menu (motion) in EA 1195 i set the custom port identical to the one in betterjoy but as soon i click OK yuzu reset the port to the default one. 

In previous build it worked fine now the workaround is to change bettercemu port to yuzu's default. 

Not a big deal but i hope this report may help.

**Comment by german77** [comment]
Please make sure that you click the add server button. You should see your custom server in the list to the left.
![image](https://user-images.githubusercontent.com/5944268/101527890-325e2980-3954-11eb-8c29-83b555e0a499.png)

You can also verify by looking at the log file.
![image](https://user-images.githubusercontent.com/5944268/101528297-c29c6e80-3954-11eb-9b7a-1c947b327bf0.png)

**Comment by AshTrayMaze** [comment]
Sorry, you're right. Didn't saw that because text of the buttons is only partially visible with win10 screen 250% adjustment. (i'm using a 65" tv).
