### ISSUE TITLE
Feature request: Ability to resize to 1080p using "reset window size"

### ISSUE THREAD

**Issue by momala454** [yuzu-emu/yuzu#5175]
I have a 1440p monitor, so I can't use fullscreen mode to display in 1080p, because pixels are not 1:1 (they're blurry) in full screen.

There is a feature to reset the window size, but it reset only to 720p (code : https://github.com/yuzu-emu/yuzu/blob/44f7067cab5c8999a69f8dd92574a2b6e8edfe34/src/yuzu/main.cpp#L2254 ). I would like the feature to be able to choose between 720p and 1080p when reseting the window size.
Or if possible, detect the current native resolution of the game and resize to it ?
I don't know if many games are 720p in docked mode, but maybe we could detect docked and use the docked resolution when reseting the window size instead of the undocked ?

thank you

**Comment by choppymaster** [comment]
After the buffer cache rewrite, a `resolution scaler` will be developed, which helps to play in `2160p` , 1480p ot any resolution. `Docked mode` is 900p.

**Comment by momala454** [comment]
thanks but it's probably a good idea to allow to resize to pixel perfect size ?

**Comment by choppymaster** [comment]
Yes.
