### ISSUE TITLE
[Request] Launch qt in fullscreen via launch parameter

### ISSUE THREAD

**Issue by ActualMandM** [yuzu-emu/yuzu#5177]
Currently it's only possible to launch yuzu in fullscreen if you use yuzu-cmd, which is completely busted. The main executable does not allow for any launch parameters, so you have to manually make the game fullscreen when launching yuzu via a shortcut.

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/5033.
