### ISSUE TITLE
[Linux] Yuzu now fails to build

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#5182]
Yuzu now fails to build on Linux systems.  I haven't had time to bisect but can if needed.

- OS: Linux Mint 20, Kernel 5.8
- Compiler: gcc 9.3.0
- Compile log: [here](https://pastebin.com/dHgj7wdQ)
- Bad commit: 6d6115475b4edccdf1bb4e96ecc3d3b1be319e76
- Last known good commit: 6b7320add44bf3d933063d0b93296222fd522ef6

**Comment by RodrigoTR04** [comment]
Afaik you need gcc 10 instead of 9.3.0, also this can be asked in the #yuzu-support-linux channel on the Discord server.

**Comment by Shoegzer** [comment]
Thanks, but according to the [build instructions](https://github.com/yuzu-emu/yuzu/wiki/Building-For-Linux), gcc 7 is the minimum.

**Comment by lat9nq** [comment]
Sounds like the build instructions need updated. We switched to C++20 a while back, among other things. The build bots are now using GCC 10 due to GCC 9 being insufficient. I recommend you do the same.

**Comment by lat9nq** [comment]
Questions like this can be directed first to our [Discord server](https://discord.gg/u77vRWY) or the [yuzu support forum](https://community.citra-emu.org/c/yuzu-support).

**Comment by Shoegzer** [comment]
Ah okay, thanks @lat9nq.  I'll close this out when I can successfully compile with gcc 10 unless someone else wants to before then.

**Comment by Shoegzer** [comment]
**Update:** Yuzu compiles on this system with upgraded gcc 10.2.0, so I'm closing this issue.  I also noticed the build instructions page noted above has been updated to reflect gcc 10 as a minimum, that should help avoid issues like these in the future, so thanks to whomever did that!
