### ISSUE TITLE
 yuzu freezes on my pc and emulation with 0fps and background sound.

### ISSUE THREAD

**Issue by kernelacel** [yuzu-emu/yuzu#5194]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5685696/yuzu_log.txt)
[pc specs.txt](https://github.com/yuzu-emu/yuzu/files/5685697/pc.specs.txt)
![yuzu bug](https://user-images.githubusercontent.com/17055099/102026658-1223d580-3d6d-11eb-820d-712bef5b86f5.png)
![yuzu bug1](https://user-images.githubusercontent.com/17055099/102026661-14862f80-3d6d-11eb-89ee-5452e72c66eb.png)
![yuzu bug2](https://user-images.githubusercontent.com/17055099/102026662-151ec600-3d6d-11eb-8f07-695c4a07ed62.png)
![yuzu bug3](https://user-images.githubusercontent.com/17055099/102026664-151ec600-3d6d-11eb-8a14-4ba77d223f41.png)

**Comment by goldenx86** [comment]
Pokémon Sw/Sh games are not stable in long runs yet, specially with multicore enabled.

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/4227.
