### ISSUE TITLE
Exiting or using Stop causes yuzu to lock

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#5195]
Regressed with #4542 

When a guest program is running, yuzu will lock up if the user tries to close yuzu or use Emulation -> {Stop,Restart}. In this state, yuzu needs to receive SIGKILL from an external process to exit.

Backtrace of c96930fd9d09e49355225ecd538510b9db2a7158 running es2gears, after hitting CTRL+C in GDB once yuzu is in a locked state: [gdb.txt](https://github.com/yuzu-emu/yuzu/files/5691172/gdb.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5691173/yuzu_log.txt)

Disabling Multicore/Async, using a different OpenGL renderer (such as NVIDIA or llvmpipe), switchting to Vulkan, or enabling/disabling Macro JIT does not change its behavior and produces the same backtrace.

**Comment by goldenx86** [comment]
This also affects Windows under most conditions.

**Comment by lat9nq** [comment]
> This also affects Windows under most conditions.

Yup, I reproduced this in Windows. Updating issue title.

**Comment by gidoly** [comment]
Adressed by 7019
