### ISSUE TITLE
compile on Ubuntu 20.04 fails with libusb errors

### ISSUE THREAD

**Issue by rcampbel3** [yuzu-emu/yuzu#5197]
I'm compiling from source on Ubuntu 20.04. Installed recommended and conan as per linux install docs.

commit 37bec068c2e3814bf23f1b8c1c6dd00d80191d27 (HEAD -> master, origin/master, origin/HEAD)

I've run cmake as follows:

```
cmake .. -GNinja -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
```

~/project/yuzu/build $ ninja
[10/73] Linking CXX executable bin/yuzu-cmd
FAILED: bin/yuzu-cmd 
: && /usr/bin/g++-10  -O3 -DNDEBUG   src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/config.cpp.o src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/emu_window/emu_window_sdl2_gl.cpp.o src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/emu_window/emu_window_sdl2.cpp.o src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/yuzu.cpp.o src/yuzu_cmd/CMakeFiles/yuzu-cmd.dir/emu_window/emu_window_sdl2_vk.cpp.o  -o bin/yuzu-cmd -L/home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib   -L/home/ross/.conan/data/catch2/2.13.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib   -L/home/ross/.conan/data/fmt/7.1.2/_/_/package/b173bbda18164d49a449ffadc1c9e817f49e819d/lib   -L/home/ross/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib   -L/home/ross/.conan/data/bzip2/1.0.8/_/_/package/91a8b22c2c5a149bc617cfc06cdd21bf23b12567/lib   -L/home/ross/.conan/data/libiconv/1.16/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib -Wl,-rpath,/home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib:/home/ross/.conan/data/catch2/2.13.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib:/home/ross/.conan/data/fmt/7.1.2/_/_/package/b173bbda18164d49a449ffadc1c9e817f49e819d/lib:/home/ross/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib:/home/ross/.conan/data/bzip2/1.0.8/_/_/package/91a8b22c2c5a149bc617cfc06cdd21bf23b12567/lib:/home/ross/.conan/data/libiconv/1.16/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib:  lib/libcommon.a  lib/libcore.a  lib/libinput_common.a  lib/libinih.a  lib/libglad.a  -lrt  lib/libcore.a  lib/libaudio_core.a  lib/libvideo_core.a  lib/libcore.a  lib/libaudio_core.a  lib/libvideo_core.a  lib/libmbedtls.a  lib/libmbedx509.a  lib/libmbedcrypto.a  lib/libopus.a  -lzip  lib/libweb_service.a  /usr/lib/x86_64-linux-gnu/libssl.so  /usr/lib/x86_64-linux-gnu/libcrypto.so  lib/libdynarmic.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_program_options.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_stacktrace_addr2line.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_stacktrace_basic.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_stacktrace_noop.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_stacktrace_backtrace.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_wserialization.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_timer.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_tr1.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_tr1l.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_c99f.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_tr1f.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_nowide.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_wave.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_c99.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_c99l.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_type_erasure.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_unit_test_framework.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_prg_exec_monitor.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_test_exec_monitor.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_contract.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_iostreams.a  /home/ross/.conan/data/bzip2/1.0.8/_/_/package/91a8b22c2c5a149bc617cfc06cdd21bf23b12567/lib/libbz2.a  /home/ross/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libz.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_graph.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_fiber.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_coroutine.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_log_setup.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_log.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_regex.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_filesystem.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_random.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_locale.a  /home/ross/.conan/data/libiconv/1.16/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libiconv.a  /home/ross/.conan/data/libiconv/1.16/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libcharset.a  lib/libSoundTouch.a  lib/libcubeb.a  lib/libcommon.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_context.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_thread.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_atomic.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_chrono.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_container.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_date_time.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_serialization.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_exception.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_system.a  -lrt  -lpthread  /home/ross/.conan/data/fmt/7.1.2/_/_/package/b173bbda18164d49a449ffadc1c9e817f49e819d/lib/libfmt.a  /usr/lib/x86_64-linux-gnu/liblz4.so  -lzstd  lib/libglad.a  -ldl  /usr/lib/x86_64-linux-gnu/libavcodec.so  /usr/lib/x86_64-linux-gnu/libavutil.so  /usr/lib/x86_64-linux-gnu/libswscale.so  lib/libsirit.a  -lSDL2  -lusb  -pthread && :
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::UpdateVibrations()':
gc_adapter.cpp:(.text+0xf08): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: gc_adapter.cpp:(.text+0xf28): undefined reference to `libusb_error_name'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::SendVibrations()':
gc_adapter.cpp:(.text+0x10ae): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: gc_adapter.cpp:(.text+0x10d8): undefined reference to `libusb_error_name'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::AdapterInputThread()':
gc_adapter.cpp:(.text+0x1338): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::CheckDeviceAccess()':
gc_adapter.cpp:(.text+0x15ad): undefined reference to `libusb_control_transfer'
/usr/bin/ld: gc_adapter.cpp:(.text+0x15bf): undefined reference to `libusb_kernel_driver_active'
/usr/bin/ld: gc_adapter.cpp:(.text+0x15d5): undefined reference to `libusb_close'
/usr/bin/ld: gc_adapter.cpp:(.text+0x15ee): undefined reference to `libusb_detach_kernel_driver'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1606): undefined reference to `libusb_claim_interface'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::GetGCEndpoint(libusb_device*)':
gc_adapter.cpp:(.text+0x17b1): undefined reference to `libusb_get_config_descriptor'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1890): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::Setup()':
gc_adapter.cpp:(.text+0x1951): undefined reference to `libusb_open_device_with_vid_pid'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1975): undefined reference to `libusb_get_device'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1a1b): undefined reference to `libusb_release_interface'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1a23): undefined reference to `libusb_close'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::AdapterScanThread()':
gc_adapter.cpp:(.text+0x1b28): undefined reference to `libusb_release_interface'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1b31): undefined reference to `libusb_close'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::ClearLibusbHandle()':
gc_adapter.cpp:(.text+0x1c96): undefined reference to `libusb_release_interface'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1c9e): undefined reference to `libusb_close'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::Reset()':
gc_adapter.cpp:(.text+0x1da4): undefined reference to `libusb_release_interface'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1dac): undefined reference to `libusb_close'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::Adapter()':
gc_adapter.cpp:(.text+0x207a): undefined reference to `libusb_init'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::~Adapter()':
gc_adapter.cpp:(.text+0x2461): undefined reference to `libusb_release_interface'
/usr/bin/ld: gc_adapter.cpp:(.text+0x2469): undefined reference to `libusb_close'
/usr/bin/ld: gc_adapter.cpp:(.text+0x24d8): undefined reference to `libusb_exit'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::Reset()':
gc_adapter.cpp:(.text+0x1e21): undefined reference to `libusb_exit'
collect2: error: ld returned 1 exit status
[11/73] Linking CXX executable bin/yuzu-tester
FAILED: bin/yuzu-tester 
: && /usr/bin/g++-10  -O3 -DNDEBUG   src/yuzu_tester/CMakeFiles/yuzu-tester.dir/config.cpp.o src/yuzu_tester/CMakeFiles/yuzu-tester.dir/emu_window/emu_window_sdl2_hide.cpp.o src/yuzu_tester/CMakeFiles/yuzu-tester.dir/service/yuzutest.cpp.o src/yuzu_tester/CMakeFiles/yuzu-tester.dir/yuzu.cpp.o  -o bin/yuzu-tester -L/home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib   -L/home/ross/.conan/data/catch2/2.13.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib   -L/home/ross/.conan/data/fmt/7.1.2/_/_/package/b173bbda18164d49a449ffadc1c9e817f49e819d/lib   -L/home/ross/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib   -L/home/ross/.conan/data/bzip2/1.0.8/_/_/package/91a8b22c2c5a149bc617cfc06cdd21bf23b12567/lib   -L/home/ross/.conan/data/libiconv/1.16/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib -Wl,-rpath,/home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib:/home/ross/.conan/data/catch2/2.13.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib:/home/ross/.conan/data/fmt/7.1.2/_/_/package/b173bbda18164d49a449ffadc1c9e817f49e819d/lib:/home/ross/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib:/home/ross/.conan/data/bzip2/1.0.8/_/_/package/91a8b22c2c5a149bc617cfc06cdd21bf23b12567/lib:/home/ross/.conan/data/libiconv/1.16/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib:  lib/libcommon.a  lib/libcore.a  lib/libinput_common.a  lib/libinih.a  lib/libglad.a  -lrt  lib/libcore.a  lib/libaudio_core.a  lib/libvideo_core.a  lib/libcore.a  lib/libaudio_core.a  lib/libvideo_core.a  lib/libmbedtls.a  lib/libmbedx509.a  lib/libmbedcrypto.a  lib/libopus.a  -lzip  lib/libweb_service.a  /usr/lib/x86_64-linux-gnu/libssl.so  /usr/lib/x86_64-linux-gnu/libcrypto.so  lib/libdynarmic.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_program_options.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_stacktrace_addr2line.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_stacktrace_basic.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_stacktrace_noop.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_stacktrace_backtrace.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_wserialization.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_timer.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_tr1.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_tr1l.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_c99f.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_tr1f.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_nowide.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_wave.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_c99.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_math_c99l.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_type_erasure.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_unit_test_framework.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_prg_exec_monitor.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_test_exec_monitor.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_contract.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_iostreams.a  /home/ross/.conan/data/bzip2/1.0.8/_/_/package/91a8b22c2c5a149bc617cfc06cdd21bf23b12567/lib/libbz2.a  /home/ross/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libz.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_graph.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_fiber.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_coroutine.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_log_setup.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_log.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_regex.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_filesystem.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_random.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_locale.a  /home/ross/.conan/data/libiconv/1.16/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libiconv.a  /home/ross/.conan/data/libiconv/1.16/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libcharset.a  lib/libSoundTouch.a  lib/libcubeb.a  lib/libcommon.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_context.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_thread.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_atomic.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_chrono.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_container.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_date_time.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_serialization.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_exception.a  /home/ross/.conan/data/boost/1.73.0/_/_/package/47bdab31d0a101fe1d798e4846e78966feed955f/lib/libboost_system.a  -lrt  -lpthread  /home/ross/.conan/data/fmt/7.1.2/_/_/package/b173bbda18164d49a449ffadc1c9e817f49e819d/lib/libfmt.a  /usr/lib/x86_64-linux-gnu/liblz4.so  -lzstd  lib/libglad.a  -ldl  /usr/lib/x86_64-linux-gnu/libavcodec.so  /usr/lib/x86_64-linux-gnu/libavutil.so  /usr/lib/x86_64-linux-gnu/libswscale.so  lib/libsirit.a  -lSDL2  -lusb  -pthread && :
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::UpdateVibrations()':
gc_adapter.cpp:(.text+0xf08): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: gc_adapter.cpp:(.text+0xf28): undefined reference to `libusb_error_name'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::SendVibrations()':
gc_adapter.cpp:(.text+0x10ae): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: gc_adapter.cpp:(.text+0x10d8): undefined reference to `libusb_error_name'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::AdapterInputThread()':
gc_adapter.cpp:(.text+0x1338): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::CheckDeviceAccess()':
gc_adapter.cpp:(.text+0x15ad): undefined reference to `libusb_control_transfer'
/usr/bin/ld: gc_adapter.cpp:(.text+0x15bf): undefined reference to `libusb_kernel_driver_active'
/usr/bin/ld: gc_adapter.cpp:(.text+0x15d5): undefined reference to `libusb_close'
/usr/bin/ld: gc_adapter.cpp:(.text+0x15ee): undefined reference to `libusb_detach_kernel_driver'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1606): undefined reference to `libusb_claim_interface'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::GetGCEndpoint(libusb_device*)':
gc_adapter.cpp:(.text+0x17b1): undefined reference to `libusb_get_config_descriptor'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1890): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::Setup()':
gc_adapter.cpp:(.text+0x1951): undefined reference to `libusb_open_device_with_vid_pid'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1975): undefined reference to `libusb_get_device'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1a1b): undefined reference to `libusb_release_interface'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1a23): undefined reference to `libusb_close'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::AdapterScanThread()':
gc_adapter.cpp:(.text+0x1b28): undefined reference to `libusb_release_interface'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1b31): undefined reference to `libusb_close'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::ClearLibusbHandle()':
gc_adapter.cpp:(.text+0x1c96): undefined reference to `libusb_release_interface'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1c9e): undefined reference to `libusb_close'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::Reset()':
gc_adapter.cpp:(.text+0x1da4): undefined reference to `libusb_release_interface'
/usr/bin/ld: gc_adapter.cpp:(.text+0x1dac): undefined reference to `libusb_close'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::Adapter()':
gc_adapter.cpp:(.text+0x207a): undefined reference to `libusb_init'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::~Adapter()':
gc_adapter.cpp:(.text+0x2461): undefined reference to `libusb_release_interface'
/usr/bin/ld: gc_adapter.cpp:(.text+0x2469): undefined reference to `libusb_close'
/usr/bin/ld: gc_adapter.cpp:(.text+0x24d8): undefined reference to `libusb_exit'
/usr/bin/ld: lib/../src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o: in function `GCAdapter::Adapter::Reset()':
gc_adapter.cpp:(.text+0x1e21): undefined reference to `libusb_exit'
collect2: error: ld returned 1 exit status
[15/73] Building CXX object src/yuzu/CMakeFiles/yuzu.dir/applets/controller.cpp.o
../src/yuzu/applets/controller.cpp: In function ‘void {anonymous}::UpdateController(Settings::ControllerType, std::size_t, bool)’:
../src/yuzu/applets/controller.cpp:40:40: warning: ‘static Core::System& Core::System::GetInstance()’ is deprecated: Use of the global system instance is deprecated [-Wdeprecated-declarations]
   40 |     Core::System& system{Core::System::GetInstance()};
      |                                        ^~~~~~~~~~~
In file included from ../src/yuzu/applets/controller.cpp:10:
../src/./core/core.h:128:86: note: declared here
  128 |     [[deprecated("Use of the global system instance is deprecated")]] static System& GetInstance() {
      |                                                                                      ^~~~~~~~~~~
../src/yuzu/applets/controller.cpp:40:52: warning: ‘static Core::System& Core::System::GetInstance()’ is deprecated: Use of the global system instance is deprecated [-Wdeprecated-declarations]
   40 |     Core::System& system{Core::System::GetInstance()};
      |                                                    ^
In file included from ../src/yuzu/applets/controller.cpp:10:
../src/./core/core.h:128:86: note: declared here
  128 |     [[deprecated("Use of the global system instance is deprecated")]] static System& GetInstance() {
      |                                                                                      ^~~~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by edisionnano** [comment]
- Clone the yuzu repo using `git clone https://github.com/yuzu-emu/yuzu`
- Install the needed dependencies using `sudo apt install gcc-10 g++-10 glslang-tools p7zip-full git build-essential ninja-build make cmake libsdl2-dev qtbase5-dev libqt5opengl5-dev qtbase5-private-dev python python3-pip libboost-dev libboost-context-dev libzip-dev liblz4-dev libmbedtls-dev libssl-dev libopus-dev zlib1g-dev libzstd-dev libavcodec-dev libavutil-dev libswscale-dev xorg-dev libx11-xcb-dev libxcb-dri3-dev`
- Get conan using `wget https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_32_1.deb` and `sudo dpkg -i conan-ubuntu-64_1_32_1.deb`, if it installs without errors remove it using `rm -f conan-ubuntu-64_1_32_1.deb`
-  CD inside the repo using `cd yuzu`
- Create a build folder and cd inside using `mkdir build && cd build`
- Switch globally to GCC and G++ 10 using `sudo apt install gcc-10 g++-10` and `sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10` and `sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10`
- Generate with `cmake ..`
- And lastly build using `make`
You can use ccache to speed compilation up
