### ISSUE TITLE
yuzu EA1244 onwards freezes and eventually crashes

### ISSUE THREAD

**Issue by jojorne** [yuzu-emu/yuzu#5219]
yuzu micro freezes a lot and eventually crashes to desktop on an AMD Phenom II x4 with the unsafe option, 16GB of RAM and a GTX 1060 6GB VRAM.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5729486/yuzu_log.txt)

**Comment by Morph1984** [comment]
The log you posted is incomplete and is not useful for debugging, please post a complete log

**Comment by Morph1984** [comment]
Also provide the game you are trying to run

**Comment by jojorne** [comment]
Okay, thanks. I'll update this with more useful information once the issue or the log system #5224 is fixed.

**Comment by Morph1984** [comment]
Your log only contains the <Critical> logs, this is incomplete

A standard log comes with a lot more information than this

**Comment by Morph1984** [comment]
4 lines won't tell me anything, if you posted a log with the standard logging information it would tell us what game you are playing, what hardware configuration you are using, etc. Your modified log lacks all these

![image](https://user-images.githubusercontent.com/39850852/103003265-762d6300-44fe-11eb-9e03-b3dc56942996.png)

**Comment by jojorne** [comment]
Issue fixed on EA1250.
