### ISSUE TITLE
yuzu return the clothes to default clothes 

### ISSUE THREAD

**Issue by 7Han-maker** [yuzu-emu/yuzu#5222]
When we change any clothes Yuzu dont show the new clothe changed in all yuzu versions

-->

**Comment by ChrisNonyminus** [comment]
What?

**Comment by G-Spawn** [comment]
Please keep in mind the things mentioned that you should provide when you create a new issue (context as to what game, what yuzu version, and especially a log).

 If you're talking about Pokemon sword or shield yes this happens, several people have reported it in the discord, I don't think there is a fix.

**Comment by 7Han-maker** [comment]
Thanks

**Comment by yuwenhua653** [comment]
Do you mean that Pokémon Sword and Shield cannot change clothes?  That’s because your League Card ID is not a number

**Comment by 7Han-maker** [comment]
Yes, that is correct. :)

**Comment by 7Han-maker** [comment]
Thanks

**Comment by FearlessTobi** [comment]
This is not a proper issue report a developer can look into.
Closing
