### ISSUE TITLE
If yuzu crashes, the log file will not be saved completely

### ISSUE THREAD

**Issue by jojorne** [yuzu-emu/yuzu#5224]
It will end with incomplete lines like:
`[ 488.315279] Render.OpenGL <Debug> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:123: API OTHER 131185: Buf`

**Comment by Morph1984** [comment]
When a program exits unexpectedly, it cannot complete writing to the file

**Comment by jojorne** [comment]
So, yeah... Asking me for the full log file when the app crashes won't help you. There's nothing there that indicates what caused, since it's not recorded, unfortunately.

**Comment by Jcw87** [comment]
Google breakpad manages to generate and send crash dumps during an application crash. Could you not do something similar to call flush on the log stream?
