### ISSUE TITLE
Super Mario Odyssey: Freeze when showing transition movie when flying to Luncheon Kindom

### ISSUE THREAD

**Issue by goedzo** [yuzu-emu/yuzu#5234]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5744845/yuzu_log.txt)
When playing odyssey I cannot fly to the luncheion kingdom. The transition scene starts showing, and the blimb goes high in the sky. Sounds keeps playing, but after 2 seconds the video freezes, whilst the sound keeps playing. After 7 seconds the sound is also over and then the frozen screen stays. Game does not recover and have to restart yuzu. Tried several options with openGL, vulkan, synchronous, asynchronous, audio slowdown etc, but everyhting has the same result. I tried skipping the movie witrh +, which does transition the scene to inside the blimb, however then immediately the game freezes as well. I also tried to fly to a different world first and then go back to the luncheon kingdom, but this results in the same problem.

My build: yuzu-windows-msvc-20201225-b9f600f08 and logfile is attached,

**Comment by G-Spawn** [comment]
This is an issue tracker for the emulator, perhaps join the discord if you need support for it instead?

**Comment by benderscruffy** [comment]
can be closed
this is fixed
