### ISSUE TITLE
Moon: Remix RPG Adventure crashes before the Name Character screen in EA and mainline since 491

### ISSUE THREAD

**Issue by lightgod87** [yuzu-emu/yuzu#5238]
Good day,

The motive for this message is to report a crash that's happening in Yuzu Early Access. In Moon: Remix RPG Adventure (with update v1.1.2), before you make it to the screen where you name your character, Yuzu suffers a CTD. This is with EA 1255.

By sheer curiosity, I tested this on mainline (version 486) as well, and there, I can get to that screen.

I'll be attaching both logs for EA and mainline (regular and debug) so you can take a look at the situation. Probably an issue related with an EA implementation that isn't in mainline, so please keep that in mind.

I'll be waiting for a prompt answer.

[yuzu_log_mainline.txt](https://github.com/yuzu-emu/yuzu/files/5747471/yuzu_log_mainline.txt)
[yuzu_log_EA.txt](https://github.com/yuzu-emu/yuzu/files/5747472/yuzu_log_EA.txt)
[yuzu_log_ea_debug.zip](https://github.com/yuzu-emu/yuzu/files/5747505/yuzu_log_ea_debug.zip)
[yuzu_log_mainline_debug.zip](https://github.com/yuzu-emu/yuzu/files/5747530/yuzu_log_mainline_debug.zip)

**Comment by lightgod87** [comment]
I checked the issue again after some changes done in EA 1260. The issue still persists. I attach the new debug log.
[yuzu_log_ea_debug_1260.zip](https://github.com/yuzu-emu/yuzu/files/5751138/yuzu_log_ea_debug_1260.zip)

**Comment by lightgod87** [comment]
Welp... this just in... in EA 1264, it doesn't even make it to the the part after the Push Start button after watching the first cutscenes. I dunno what happened, but it seems like the game became less stable in EA.

[yuzu_log_ea_debug_1264.zip](https://github.com/yuzu-emu/yuzu/files/5752995/yuzu_log_ea_debug_1264.zip)

**Comment by lightgod87** [comment]
Alright, I tested in Yuzu Mainline 491 (the version where TCR has been merged), and the game has been crashing now, then I checked back in the version I checked before (486) and it didn't crash. I think it's a regression caused by TCR.

[yuzu_log_mainline_debug_491.zip](https://github.com/yuzu-emu/yuzu/files/5756118/yuzu_log_mainline_debug_491.zip)

I think that should be it for now.

**Comment by lightgod87** [comment]
I did another test in EA 1287, which had this changelog:

- Fixed data race in buffer queue queue_sequence access. This fixes games randomly freezing/crashing when requesting to acquire a buffer slot

So I checked this issue again, and... lo and behold, it CTD'd again. One thing I've noticed, is that the game can cause a CTD in those three places:

1. After the faux-title screen in the intro and before the faux-file selection.
2. After the faux-file selection and before inserting the name of your character.
3. After you try to leave the castle right at the beginning after you speak with the king.

Here's the new log file:

[yuzu_log_ea_debug_1287.zip](https://github.com/yuzu-emu/yuzu/files/5764928/yuzu_log_ea_debug_1287.zip)

That's all for now.

**Comment by lightgod87** [comment]
[yuzu_log_ea_debug_1356.zip](https://github.com/yuzu-emu/yuzu/files/5853157/yuzu_log_ea_debug_1356.zip)

Just so you know, the issue is still happening, even after various underlying changes beneath with shaders and stuff. This one crashed before the screen where you name your character.

**Comment by HomeStarRunnerTron** [comment]
Bro, deeply grateful to you for explained the last version that ran correctly-- I FINALLY got it running again today without crashing every few minutes thanks to this explanation. FROM LEVEL 1 to LEVEL 9, WAHEE~

http://www.skyetheguy.com/nextdotdotdotlevel.png

All the best, and sure do hope this can get sorted out eventually. :  )

**Comment by lightgod87** [comment]
[yuzu_log_ea_debug_1551.zip](https://github.com/yuzu-emu/yuzu/files/6251674/yuzu_log_ea_debug_1551.zip)

A new debug log for the Moon issue. It still happens, but hopefully this can help to detect the cause of the issue.

**Comment by auwsmit** [comment]
Hey, not sure which update caused this, but on build 1635 I'm able to reliably get past the intro and out of the starting town on both OpenGL and Vulkan. I'll keep playing and see if any other big issues/crashes happen further into the game.

**Comment by lightgod87** [comment]
Good day,

To comment that the issue has been fixed since Mainline 596 and also the latest EA versions. This was fixed by a PR from Lioncash:

https://github.com/yuzu-emu/yuzu/pull/6218/

With that, the issue can be closed.
