### ISSUE TITLE
Vulkan crash right after launching the game

### ISSUE THREAD

**Issue by jojorne** [yuzu-emu/yuzu#5241]
Game: DEAD OR ALIVE Xtreme 3 Scarlet 0x01009CC00C97C000
CPU: AMD Phenom(tm) II X4 965 Processor

[yuzu_log-vk1.txt](https://github.com/yuzu-emu/yuzu/files/5747736/yuzu_log-vk1.txt)
[yuzu_log-vk2.txt](https://github.com/yuzu-emu/yuzu/files/5747738/yuzu_log-vk2.txt)

Note: OpenGL runs normal.

**Comment by goldenx86** [comment]
Update your GPU driver.
This is not a support section, please use the official Discord server or forums for problems like this.

**Comment by jojorne** [comment]
I can't update. I play other vulkan games that crash on latest drive too. Such a bummer...

**Comment by goldenx86** [comment]
Sounds like time to migrate to Windows 10 then.

**Comment by jojorne** [comment]
No, it happens on Windows 10 too... [Hud disappeared](https://forum.egosoft.com/viewtopic.php?f=180&t=430534&start=60).
