### ISSUE TITLE
InsertHostThread:218: Assertion Failed! Too many host threads

### ISSUE THREAD

**Issue by BadHarry00** [yuzu-emu/yuzu#5243]
I'm will play Animal Crossing 1.6.0 with Yuzu Early Access 1259 (Head-5935e194e   2020-12-29).
Loading Game ok. I can play until I arrive on the island, after which Yuzu quits without an error message.

The last 5 rows from Yuzu log, this repeats all the Time:
`[ 562.474433] Service.NVDRV <Info> video_core\command_classes\codecs\codec.cpp:SetTargetCodec:47: NVDEC video codec initialized to 9
[ 562.498189] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:SetAndWait:87: (STUBBED) called, input_id=0x1, min=0xABA9500, max=0xFFFFFFFF
[ 562.498373] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:Get:95: (STUBBED) called
[ 562.498801] Debug <Critical> core\hle\kernel\kernel.cpp:InsertHostThread:218: Assertion Failed! Too many host threads`

The error is reproducible.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5750480/yuzu_log.txt)

**Comment by G-Spawn** [comment]
You don't need to make duplicate issues.
