### ISSUE TITLE
Suggested Shader Improvement

### ISSUE THREAD

**Issue by RedxUndead** [yuzu-emu/yuzu#5244]
Hi,

Firstly its difficult to give a version number as this is a recurring issue that i've been able to reproduce the last few times i've updated Yuzu.  Early access.

I have noticed that any existing shader caches that compiles at boot of any game the 1st time I run the subsequent version of the emulator, seems to aid gameplay in absolutely zero way - it behaves as if no shader cache exists. Each action/asset etc caches again and the shader total increases. not only this, but it seems to impede the correct caching of the same shaders ever again. for example, in pokemon sword, if i encountered a sandshrew in a previous version and this is cached correctly (and it pops in seemlessly with no stutter from then on), the subsequent version will NEVER handle this shader correctly, it will always stutter, even if encountered again and the shader count increasing would appear to indicate it has been collected anew. (The larger the existing shader, the greater the symptoms outlined above appear to be. Even if i cycle through each area 15 times in different conditions it will always stutter, unless the cache is completely re-built on a per version basis.) 

It's such a shame because if i manually purge the 'precompiled' folder with each update, albeit having to recache things from the beginning; i don't run into this behaviour (recurring stutter in the same places seemingly based on contents of the previous version's cache)  at all - it works exactly as intended and it works really well. 

It begs the question, why not just purge the 'precompiled' folder automatically for each update? it would 100% solve this problem, because rebuilding a fresh shader cache atop an old one brings, not only graphical issues (SMO Cap kingdom flickering in the past for example) , but seems to , at least in some cases, prevent optimal performance with the emulator from ever being attained! This takes away from the user experience as not every single user would extensively test this and find workarounds such as these.

I've used Yuzu for a lengthy period, as have many others and i'm sure we can all agree a fresh cache with each version just works better.. so why not make the emulator enable that position by default?  

Specs as below;

Ryzen 3300X
GTX 1660TI
16 GB 3400Mhz DDR4
500GB SSD / 2TB HDD

**Comment by german77** [comment]
Shaders have been completely reworked. Re open if necessary
