### ISSUE TITLE
WriteBuffer size greater than the buffer_size [Error]

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#525]
## Hardware Specs : 
- Nvidia GeForce GTX 960
- Intel I7-7700K @ 4.5Ghz
- 8 GB Of Ram 3200Mhz
- Windows 10 Pro

## The issue : 
When I launch Retro City Rampage DX or Rayman Legends definitive edition, for retro city rampage DX it does the error  "Core <Critical> core\hle\kernel\hle_ipc.cpp:WriteBuffer:278: size (00000000000020E0) is greater than buffer_size (0000000000000900)" and it crash after it and for Rayman Legends definitive edition it does the error "Core <Critical> core\hle\kernel\hle_ipc.cpp:WriteBuffer:278: size (00000000000020E0) is greater than buffer_size (00000000000001C0)" but it don't crash with it.

## The Retro City Rampage DX Log : 
![image](https://user-images.githubusercontent.com/33609333/40992145-358fc0d6-68f6-11e8-933d-646a61466365.png)

## The Rayman Legends definitive edition Log : 
![image](https://user-images.githubusercontent.com/33609333/40992095-0f6377fe-68f6-11e8-88c9-39486f81b0ea.png)

**Comment by Hexagon12** [comment]
Same errors happen in DOOM and Seiken Densetsu Collection.

**Comment by mailwl** [comment]
looks like AudioRenderer implements Revision4 only (fw 4.0+ I think). other revisions has different structures size

**Comment by mailwl** [comment]
it has the same mean on iPhone - Safari, or even WebKit uses it for JavaScript JIT, i think, HOS uses it for JS too (in WebKit)

**Comment by greggameplayer** [comment]
ok, so a change in audio module is needed.

**Comment by mailwl** [comment]
don't check DOOM, but other games pass this error.
Request to close

**Comment by greggameplayer** [comment]
@mailwl ok
