### ISSUE TITLE
new texture cache xenoblade games ram leak

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#5256]
with new texture cache xenoblade games got ram leak issue( more noticeable on long cutscenes  )
xenoblade definetive edition:
this pic is after see long cutscene in event theater
<img width="788" alt="20201230_174840" src="https://user-images.githubusercontent.com/66776795/103347908-b7fc7180-4adb-11eb-8b9f-50fb1b295588.png">
on mainline(version that not have new texture cache)
<img width="742" alt="20201230_173517" src="https://user-images.githubusercontent.com/66776795/103347959-e417f280-4adb-11eb-9456-23ded190f253.png">
log:
[yuzu log.zip](https://github.com/yuzu-emu/yuzu/files/5754039/yuzu.log.zip)

xenoblade 2 torna golden country
<img width="834" alt="20201230_203016" src="https://user-images.githubusercontent.com/66776795/103348632-ef6c1d80-4add-11eb-9f44-0a229a18be65.png">
on mainline
<img width="761" alt="20201230_203546" src="https://user-images.githubusercontent.com/66776795/103348958-dfa10900-4ade-11eb-9a90-7c0e6f1576f4.png">

log:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5754043/yuzu_log.zip)

yuzu version early access:1265

hardware:
i7 8700k
rtx 2080 super

**Comment by gidoly** [comment]
garbage collector pr fixed

**Comment by gidoly** [comment]
seems texture cache itself leaks ram but reaper frees those leaked ram core problem still persist reopen

**Comment by MillZou** [comment]
Similar issue happen to Xenoblade Chronicles 2. It eats up all my 128 GB RAM.
yuzu build: mainline 676
game info: Xenoblade Chronicles 2 (USA), with all DLC and updates enabled.

**Comment by german77** [comment]
Enable GPU garbage collector. Should fix your issue

**Comment by MillZou** [comment]
That is a new option I did not realize.
With it enabled, the RAM usage is good and the game runs stably at 30fps.
