### ISSUE TITLE
[Feature Request] Add right click context menu in-game for going in and out of fullscreen mode

### ISSUE THREAD

**Issue by GreatNewHope** [yuzu-emu/yuzu#5257]
For people that play over Moonlight or Parsec, sometimes a keyboard is not available, and all they have is a phone screen that emulates a touchpad and XInput touch overlay. In such scenario, going into fullscreen would mean that you no longer can go out of fullscreen mode. Would it be possible to add a context menu inside the game that when you right click it, displays the option of going out of fullscreen mode?

Thank you very much

**Comment by GreatNewHope** [comment]
As a temporal fix for those in the same situation, this is a small autohotkey script that will spawn a "Esc" keyboard press anytime you select "Start" followed by a "Select". That will take you out of FullScreen Mode. Run this script on log in

Loop {
2Joy7::
if GetKeyState("2Joy8")=1
{
    Send {Esc}
}
return
}

**Comment by Morph1984** [comment]
A right click context menu would interfere with some functions that may require the right mouse button, so a solution with controller hotkeys would be ideal #4566
