### ISSUE TITLE
Yuzu now failing to build [Linux] 

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#5259]
Yuzu is now failing to build on linux systems.  I haven't had time to do a bisect but can if needed.

* OS: Linux Mint 20 / kernel 5.8
* Compiler: gcc 10.2.0
* CMake: 3.16.1
* Build log: [Here](https://pastebin.com/xAdGAd7V)
* Bad commit: da07977db0b71e52f5870e3adf8c2fa0ada3c706
* Last good commit: 0dc4ab42cc1efba566d428c84221a82ef5c76283

**Comment by Shoegzer** [comment]
@ReinUsesLisp Please reopen?  The issue still occurs after the above PR was merged.

**Comment by ReinUsesLisp** [comment]
Can you post a build log for it? It can't be happening if the PR is merged.

**Comment by Shoegzer** [comment]
Thanks, and yes actually I was just getting ready to do that.  Looking further it seems the error is now a bit different though:

[Build log](https://pastebin.com/bPCt1R1E)

**Comment by ReinUsesLisp** [comment]
It's addressed here https://github.com/yuzu-emu/yuzu/pull/5263.

**Comment by Shoegzer** [comment]
Ah yes, and it's building now.  Thanks.
