### ISSUE TITLE
Can only be set in English of UI language

### ISSUE THREAD

**Issue by Skyjaython** [yuzu-emu/yuzu#5272]
Directory /dist/languages/ exists, but can only be set in English. It seems to be disabled translating in CMakeLists.txt, why?

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum. From your report, I don't really understand what your issue is about. For precompiled Windows builds, translations are shipped by default, for manual builds you need to enable the corresponding Cmake flags.

Closing
