### ISSUE TITLE
Add a frame buffer option to Yuzu for Parsec level playing field

### ISSUE THREAD

**Issue by lGidyl** [yuzu-emu/yuzu#5282]
Right now, more people in the Smash community are setting up Yuzu along with Parsec to play Smash Ultimate and get a better online experience. One problem with this setup is that when hosting on parsec over longer distances parsec adds extra frame delay based on ping. This creates an unfair advantage if the person is hosting on Parsec and running Smash Ultimate itself since they are practically playing offline while the Parsec clients experience delay albeit less delay than Nintendo Switch Online If Yuzu could have a feature that lets users set a frame delay for each individual player in the controls tab this would help remedy this issue and attract more people to set up Yuzu+Parsec to play Smash Ultimate via this method.

**Comment by NielsGx** [comment]
How could you have a delay only for you, but not for other players ? As parsec stream your windows. Would need to have multiple window for each player on the host ? ew
And transmitting a stream to a player, and another stream with a slight delay for another user, would use so much bandwidth. Basically, 3 online players would mean 3 time the bandwidth

**Comment by FearlessTobi** [comment]
I agree that this is an issue that is not really yuzus responsibility to fix.
As was already suggested, you should look into alternative methods of making the game fair for everyone.
Also this problem will probably disappear when yuzu gets Local Wireless support sometime in the future.
