### ISSUE TITLE
windows vs2019 msvc compile error with constexpr and std::ranges

### ISSUE THREAD

**Issue by spacejumpunreal** [yuzu-emu/yuzu#5287]
I am using vs2019 community 14.26.28801 toolchain, got the following compile error:
1>C:\checkout\yuzu\src\video_core/textures/texture.h(225,20): error C3615: constexpr function 'Tegra::Texture::TICEntry::operator ==' cannot result in a constant expression
1>C:\checkout\yuzu\src\video_core/textures/texture.h(226,20): message : failure was caused by call of undefined function or one not declared 'constexpr'

1>C:\checkout\yuzu\src\video_core/texture_cache/descriptor_table.h(32,22): error C2039: 'fill': is not a member of 'std::ranges'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\span(277): message : see declaration of 'std::ranges'
1>C:\checkout\yuzu\src\video_core/texture_cache/descriptor_table.h(80): message : see reference to class template instantiation 'VideoCommon::DescriptorTable<Descriptor>' being compiled
1>C:\checkout\yuzu\src\video_core/texture_cache/texture_cache.h(521,22): error C2039: 'transform': is not a member of 'std::ranges'

cmake configuration and generation got no error, am I missing anything?

**Comment by Morph1984** [comment]
Update it to the latest version, 16.8 added support for `std::ranges::fill`
