### ISSUE TITLE
Crash when opening Web Applet

### ISSUE THREAD

**Issue by aleasto** [yuzu-emu/yuzu#5291]
On linux (Fedora 33), after #5042 yuzu crashes when trying to open the Action Guide in SMO, or How To Play in SMBU.
Happens both when compiling with and without YUZU_USE_QT_WEB_ENGINE.
Reverting the merge commit stops the crash:
 - If compiling with YUZU_USE_QT_WEB_ENGINE the browser opens and works (I have no issues with inputs)
 - If compiling without, it immediatly gets back to the game (though i thought it was supposed to show a warning dialog, it doesn't)

**Comment by lat9nq** [comment]
I'm able to reproduce the issue here on ace8a8e86ebff443b1bc594516e4168626943896.

[gdb-ace8a8e86.txt](https://github.com/yuzu-emu/yuzu/files/5770924/gdb-ace8a8e86.txt)

**Comment by Morph1984** [comment]
Something of note is that it crashes attempting to extract the shared fonts https://github.com/yuzu-emu/yuzu/blob/master/src/core/hle/service/ns/pl_u.cpp#L69

**Comment by Morph1984** [comment]
@aleasto Could you comment out this line to see if it works? https://github.com/yuzu-emu/yuzu/blob/master/src/core/hle/service/am/applets/web_browser.cpp#L241

**Comment by myman2343** [comment]
hi i am having the same issue where whenever the how to play menu is open my game crashes saying 66%webapplet. i am able to load things like training mode and world of light without much issue but whenever i open smash, since i have a new account the how to play screen opens up and my game crashes. Im not really sure how to fix this since im on windows. could you help me?

**Comment by aleasto** [comment]
> @aleasto Could you comment out this line to see if it works? https://github.com/yuzu-emu/yuzu/blob/master/src/core/hle/service/am/applets/web_browser.cpp#L241

Oh, that stops the crashing when building without YUZU_USE_QT_WEB_ENGINE.
Building with YUZU_USE_QT_WEB_ENGINE=ON it now crashes later (i think?), but only when **not** running in gdb :thinking:
