### ISSUE TITLE
Dark color in game? PLG

### ISSUE THREAD

**Issue by darkarp** [yuzu-emu/yuzu#5295]
Latest mainline build 259f709ec
The colors in game are way too dark. Perhaps this is something other people have experienced and know how to fix?
![Capture](https://user-images.githubusercontent.com/22871633/103638574-632e8000-4f4d-11eb-86b4-2414d11da916.PNG)

Using AMD Pro Radeon 5500M
Using OpenGL because Vulkan doesn't work as it gives me an error: vk_ERROR_EXTENSION_NOT_PRESENT

Strangely enough, the image starts with normal colors for a couple frames and then transitions into very dark for the rest of the session.

EDIT: This does NOT happen in Early access build, only on the mainline one.

**Comment by Morph1984** [comment]
Fixed by #5288
