### ISSUE TITLE
Rumble stopped working in ACNH with 497

### ISSUE THREAD

**Issue by LimticRage** [yuzu-emu/yuzu#5301]
after the yesterdays patch 497 rumble on my Xbox one controller stopped working in Animal Crossing: New horizons...

Any fix for that?

**Comment by german77** [comment]
Can you verify on 496. rumble haven't been changed for quite a while. make sure your setting for rumble are correct

**Comment by LimticRage** [comment]
it worked fine before the update, i found a temporary fix... switching to another game like Pokemon sword then getting back to Animal crossing the rumble works again...

i will check tho

**Comment by german77** [comment]
Re-open if needed
