### ISSUE TITLE
Memory leak after latest big update

### ISSUE THREAD

**Issue by daggina** [yuzu-emu/yuzu#5303]
After new big update many games that was working fine, but with animation lags, started to have memory leak issue. 
log:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5777564/yuzu_log.zip)
yuzu version 498
Games: Gensou Kissa Enchanté, Piofiore no Banshou -Ricordo-,  Reine des Fleurs

**Comment by BSoDGamingYT** [comment]
Please follow the format for issue opening you were given. You have not stated a game or emulator version you used. This makes tracking this issues 10 more difficult than it needs to be

**Comment by daggina** [comment]
> Please follow the format for issue opening you were given. You have not stated a game or emulator version you used. This makes tracking this issues 10 more difficult than it needs to be

I edited it, this happens in almost all the games I own.

**Comment by german77** [comment]
There are no know memory leak that applies for most games on yuzu 680. Logs shows something unrelated to this issue. Re-open with a new log if this is not fixed
