### ISSUE TITLE
New Super Marion Bros. U Deluxe - Hangs after splash screen

### ISSUE THREAD

**Issue by bigfatbrowncat** [yuzu-emu/yuzu#5313]
After starting the game the splash screen is shown, it says "Press L+R". After pressing the buttons the screen goes back.

One CPU core is used infinitely.
In the log lines
`[  47.636184] HW.Memory <Error> core\memory.cpp:Read:604: Unmapped Read32 @ 0x00000164`
are inserted infinitely (with counting address value on the right)

App version: "yuzu 499" (installed from the site)
![image](https://user-images.githubusercontent.com/317189/104000140-de42a100-51ae-11eb-9e2c-65b7b00bdad3.png)

**Comment by bigfatbrowncat** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5786400/yuzu_log.txt)

**Comment by CaptV0rt3x** [comment]
You need to dump the firmware from your switch and install it or games that use Miis such as Mario Kart 8 Deluxe or New Super Mario Bros U Deluxe etc. will not work.
