### ISSUE TITLE
Sid Meier's Civilization VI - The game doesn't start

### ISSUE THREAD

**Issue by bigfatbrowncat** [yuzu-emu/yuzu#5314]
Subj.

Log attached:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5786531/yuzu_log.txt)

App version: "yuzu 499" (installed from the site)
![image](https://user-images.githubusercontent.com/317189/104000140-de42a100-51ae-11eb-9e2c-65b7b00bdad3.png)

**Comment by Morph1984** [comment]
Game boots as of mainline 1202 
![image](https://user-images.githubusercontent.com/39850852/196258039-f237cb45-f708-49bc-8d30-3718312253b7.png)
