### ISSUE TITLE
Implement portable mode

### ISSUE THREAD

**Issue by ElektroStudios** [yuzu-emu/yuzu#5315]
This is a (basic and must-have) feature request that I do supposing that **Yuzu** still not implemented it (otherwise please let me know):

Please consider to implement portable mode, that is the **config**, **dump**, **load**, and **nand** and the other directories and any other files must be read/written from root directory of **yuzu.exe**. 

I cannot think of a good, modern and active emulator that is not portable itself or that does not provide the user a functionality to make it portable, like **PCSX2**, **RPCS3**, **Dolphin**, **Cemu**, **Citra**, **Cxbx-R** and recently **Xemu** [!] (**Xemu**'s devs said they will implement it soon in a next release) just to mention some of them.

Please take into account that a vast of users will need emulators to be portable, not to save settings in the user roaming folder like **Yuzu** does :(

Just let the end user the chance to decide the default behavior of the software in this meaning.

One easy way for all users to set portable mode probably would be to let them create a "portable.txt" file in the root folder of **yuzu.exe**, and then **Yuzu** should do the magic to recognize the installation as a portable mode. Or through an option in the emulator UI.

Just consider this feature request. Thanks in advance.

**Comment by BSoDGamingYT** [comment]
Yuzu already has a portable mode. It always has...you make a "user" folder beside your build .exe...load said .exe and that folder will populate with all the folders and sub folders required to be portable.

**Comment by ElektroStudios** [comment]
Thanks a lot, I really tried to investigate about the way to make it portable but I found nothing. Maybe documentation about it should be more easier to find.

In any case, problem solved. Keep up the great job you all are doing with **Yuzu** guys!!
