### ISSUE TITLE
Monster Hunter Rise Demo

### ISSUE THREAD

**Issue by fuhuan416** [yuzu-emu/yuzu#5316]
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5788422/yuzu_log.zip)

**Comment by german77** [comment]
needs #5312  to pass from this point

**Comment by fuhuan416** [comment]
> needs #5312 to pass from this point

Thank you man, I think I can test it soon :)

**Comment by german77** [comment]
The game currently works at 2fps and crashes before going in game. Not playable at the moment

**Comment by fuhuan416** [comment]
> The game currently works at 2fps and crashes before going in game. Not playable at the moment

OK, I heard that the problem is caused by the "Parental Control Service" function is not implemented, or that this is one of the issues.

**Comment by german77** [comment]
It's a dynarmic issue what causes the slowdown. Needs to be investigated.

**Comment by FearlessTobi** [comment]
Should be fixed by https://github.com/yuzu-emu/yuzu/pull/5312.
