### ISSUE TITLE
Ninja Saviors/Warriors Once Again, palette issues and final stage issue.

### ISSUE THREAD

**Issue by n1ghttrap** [yuzu-emu/yuzu#5317]
This has been a long running issue that's likely been ignored because it's a lower profile game, but this game has some palette issues that I can't seem to work around, and has been recurring on a 1060, RX 580, and 2060S, so I don't believe it's driver related.  

Still happening in the latest official but I can recall this being an issue for the last year or two.  What's odd is that I've seen youtube vids with this issue not present, so it makes me wonder if I'm overlooking something.  It does it in both Vulkan and OGL for me.  Kunoichi's kunai are colored incorrectly, and all the destructible crates and pickups are wrongly colored too.  There's also a massive, show stopping layering issue in the last stage but I don't currently have a save to replicate this.

**Comment by n1ghttrap** [comment]
![warriors bug](https://user-images.githubusercontent.com/30274474/104048650-35de0e00-51a9-11eb-80a9-b327ba2376be.png)

**Comment by n1ghttrap** [comment]
In case it's not apparent from the UI, I'm using Win10 20H2, tried removing my shaders/configs and this still occurs on both NAND installed and loaded NSP versions of the game.  Tried combinations of Vulkan, OGL, accuracy, and shader compilation options to no avail.

**Comment by FearlessTobi** [comment]
Could you please also provide a log file?

**Comment by n1ghttrap** [comment]
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/5859209/yuzu_log.txt.old.txt)

**Comment by n1ghttrap** [comment]
Works in the Hades builds now
