### ISSUE TITLE
Prinny 1&2 - Black Screen With Full Speed Audio

### ISSUE THREAD

**Issue by OldClassicGamer** [yuzu-emu/yuzu#5318]
Tried both docked and undocked, both OpenGL and Vulkan, messed with accuracy levels in GPU settings, and no luck.
The games are 2D sidescrollers and should in no way be demanding to run but I can't get the screen to show.
Audio works perfectly which to me indicates that there is potential to emulate games flawlessly.

**Comment by BSoDGamingYT** [comment]
Can you please post a log file, and also include the build on which this was tested, thanks

**Comment by OldClassicGamer** [comment]
> Can you please post a log file, and also include the build on which this was tested, thanks

Sure, I'll post the log file and I tested the games on multiple builds, the latest one I tested being EA 1295.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5789018/yuzu_log.txt)

**Comment by Tellilum** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6020573/yuzu_log.txt)
Same issue here, Yuzu 546

**Comment by benderscruffy** [comment]
using both the latest mainline and EA show graphics now
can be closed
