### ISSUE TITLE
Yuzu crashes in SMO [Heart of the Forest, throwing Cappy at the T-Rex].

### ISSUE THREAD

**Issue by noeom** [yuzu-emu/yuzu#5325]
Whenever I try to control the T-Rex in Heart of the Forest by throwing Cappy at it, Yuzu crashes. I have tried:

- In both OpenGL and Vulkan.
- With Assembly Shaders on and off.
- With CPU accuracy in both Accurate and Unsafe settings.

You can see the bug in action here, along with the console output: https://youtu.be/3Vqr5kNDKao

Log file attached (the log file is from a different run than the one in the video, but triggering the same bug).
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5792937/yuzu_log.txt)

**Comment by iWeaker4you** [comment]
I think it is a problem that happens after defeating a "boss" and apparently it only happens in Linux, in my case it happens when I defeat the boss of Oasis Desert, it always crashes, I modify the settings and it keeps happening.

**Comment by WipeoutMan** [comment]
I am getting the exact same error but on Windows 10. Maybe my log will help.

[
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5935581/yuzu_log.txt)
](url)

**Comment by martinmed** [comment]
I'm having the exact same problema Windows 10

**Comment by WipeoutMan** [comment]
If you turn off dock mode before attempting to capture the t-rex then it works! Dock mode can be enabled again right after capturing it.

I think the same issue happens with the taxi in new donk city.

**Comment by martinmed** [comment]
> If you turn off dock mode before attempting to capture the t-rex then it works! Dock mode can be enabled again right after capturing it.
> 
> I think the same issue happens with the taxi in new donk city.

thx man this worked for me switching from undocked to docked!
