### ISSUE TITLE
command line not working

### ISSUE THREAD

**Issue by powerpuffboysz** [yuzu-emu/yuzu#5331]
using the latest mainline yuzu 502, the new shortcut commands don's seem to work. whenever i try to make a shortcut with the "-f" command yuzu opens saying there was a rom format error even if the game works fine when selecting it manually through the menu or dragging and dropping the rom onto the yuzu executable. tried with standalone shortcuts and using launchbox/bigbox

**Comment by Morph1984** [comment]
You must specify "-g path_to_game"

**Comment by Morph1984** [comment]
```
yuzu.exe "path_to_game" - Launches a game at path_to_game
yuzu.exe -f - Launches the next game in fullscreen
yuzu.exe -g "path_to_game" - Launches a game at path_to_game
yuzu.exe -f -g "path_to_game" - Launches a game at path_to_game in fullscreen
```

**Comment by Morph1984** [comment]
Also, the command line arguments will only work in the next mainline, not the current one

**Comment by powerpuffboysz** [comment]
sorry. the progress report made it seem like it was in the current one
