### ISSUE TITLE
Pokemon sword and shield ending logo crash

### ISSUE THREAD

**Issue by judah-b2** [yuzu-emu/yuzu#5332]
My game crashes when the game ends and the sword logo pops up with a flare
![unknown](https://user-images.githubusercontent.com/66715197/104164471-f835eb00-541d-11eb-85d5-65c9619a87a9.png)
im using Yuzu Build 504, Windows 10, Multicore is off, using opengl, CPU: i7-97700f, GPU: 2060 SUPER, RAM: 32GB
here is the log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5794871/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/4916.

**Comment by MIKA123123** [comment]
so do i use the .txt and drag it into keys?

**Comment by judah-b2** [comment]
what do u mean by that
