### ISSUE TITLE
texture_cache: Various games eventually freeze after TCR implementation

### ISSUE THREAD

**Issue by hlriffel** [yuzu-emu/yuzu#5334]
Yuzu version 491
Manjaro 20.2 Nibia / Linux Kernel 5.10.2-2 / KDE Plasma 5.20.4
CPU: I5-7300HQ
RAM: 16GB
GPU: Nvidia GTX 1050 non-TI 4GB VRAM

After updating Yuzu to mainline 491, the emulation eventually comes to a point where it freezes. It happens with all games, regardless of OpenGL or Vulkan. I recorded two videos showing the freezes and the difference between the versions 491 and 487.

The game where it happens earliest for me is Dragon Ball FighterZ, which is the game that I used in both videos.

Yuzu 491 video:
https://youtu.be/VWc98hwz_6o

The first freeze happens at 4:38;
The second happens at 10:49;
The third happens at 20:40.

Yuzu 487 video:
https://youtu.be/J8QP1ebhJqA

Also, I apologize for the lengthy videos, but the reason is that I wanted to make the issues clear.

I must also emphasize that it happens with all games. Sooner or later, they freeze. For Pokemon Sword, it happens around 20 min into the game, but when I'm in Motostoke, it happens around 5 min, depending on the area of the city. It also happened with Crash Team Racing Nitro-Fueled, which is another game I used to record the first video.

The logs for the 3 attempts in the first video are attached:
[log.zip](https://github.com/yuzu-emu/yuzu/files/5799052/log.zip)

Thanks

EDIT: Typo.

**Comment by goldenx86** [comment]
Can you try the latest mainline 503?

**Comment by hlriffel** [comment]
I'm gonna test the 503 tomorrow, but I can say that the freezes also happen using the 502, because I tested it yesterday.

**Comment by JRBdatascience** [comment]
Am I allowed to mention here that I also have this issue. Sometimes I can play for a hour fine before it happens if it ever does. Sometimes it happens after 5 minutes, or even a couple seconds in game and happens in quick succession, making it difficult to play the game In my case I am playing Pokemon Shield..

Yuzu version: 491
OS: Windows 10 20H2 19042.685
CPU: R5-4500U
RAM: 12GB (4 GB Soldered, 8 GB SODIMM)
GPU: Integrated Vega (Drivers: Adrenalin 2020 Edition 20.12.1)

I mainly play in Vulkan since even though I am using integrated graphics, I can get full speed or close to full speed, and AMD has rendering issues and is much slower in OpenGL. I have had it happen with both backends however. I can aim to upload a log when I have some free time. I should also mention I don't see the same issue on a system using Intel Graphics, but I haven't tested intensively there.

**Comment by hlriffel** [comment]
I just gave mainline 504 a shot and it still happens. The log is attached below.

[yuzu_log - 504.txt](https://github.com/yuzu-emu/yuzu/files/5805605/yuzu_log.-.504.txt)

Thanks

**Comment by JRBdatascience** [comment]
I attached my logs from mainline 491 and 504.

[491.txt](https://github.com/yuzu-emu/yuzu/files/5808151/491.txt)

[504.txt](https://github.com/yuzu-emu/yuzu/files/5808155/504.txt)

**Comment by hlriffel** [comment]
Just an update on this, guys. Last I tested it was on EA 1366 and the freezes still happen. The only difference this time is that I switched Dragon Ball FighterZ to OpenGL and I could play smoothly with no freezes for 20 minutes and after that I switched games. So for this game in specific I think the freeze is more related to the Vulkan usage, since it has no good memory management.

Okay, then I switched to Pokémon Sword and I got the freeze in 5-10 minutes into the game. I sought support on the Discord channel and I was told it could be something related to the Multicore bug in Poke Sword. Then I disabled Multicore and could play fine for several minutes. The downside is that I experience a awful FPS drop without Multicore. 

Since then, I have been playing Pokémon Sword in Mainline 488 with Multicore enabled with no freezes whatsoever. Also, I can play for several hours without any freeze. Based on this, I really think the freezes are related to TCR.

Thanks

**Comment by codbugpatrol** [comment]
@hlriffel does the Dragon Ball FighterZ still works on OpenGL for you ? I've'open an issue for the openGL(https://github.com/yuzu-emu/yuzu/issues/6625) and also one for the vulkan for the freeze (https://github.com/yuzu-emu/yuzu/issues/6604)

**Comment by gidoly** [comment]
from my test on various game it is depands on game please open seperate issue for those games
