### ISSUE TITLE
Command-line arguments does not support xci format

### ISSUE THREAD

**Issue by altiereslima** [yuzu-emu/yuzu#5335]
Command-line arguments does not support xci format.
![image](https://user-images.githubusercontent.com/18044879/104259071-71a1fd80-545f-11eb-90a4-4b908f36a627.png)

**Comment by G-Spawn** [comment]
yuzu.exe -f -g "D:\example-game-dir\example.xci" works fine here in shortcut or cmdline.

**Comment by FearlessTobi** [comment]
Closing as this is likely a user error then.
