### ISSUE TITLE
Intel iris plus (gen11) Vulkan feature shaderStorageImageMultisample not present (seg fault)

### ISSUE THREAD

**Issue by IGCIT** [yuzu-emu/yuzu#5338]
ArchLinux, mesa-stable
latest yuzu appimage, as well as latest yuzu built from source
intel i5-1035g7

vulkan is no longer working since a few months apparently.
this is the output when running any game with vulkan:

`dynarmic: POSIX SigHandler: Exception was not in registered code blocks

Segmentation fault`

**Comment by IGCIT** [comment]
was able to get a log

crash reason: **vulkan_device.cpp: shaderStorageImageMultisample VK_FEATURE_NOT_PRESENT**

**Comment by goldenx86** [comment]
Sounds like a regression in the ANV driver.
We're trying to get hardware with Gen11 graphics, please wait a bit more so we can start with native testing on it.

**Comment by IGCIT** [comment]
ok thanks, vulkan crashes on windows too btw, but for a different reason, the log is truncated

**Comment by ReinUsesLisp** [comment]
I added that requirement recently. It's currently unused (we don't emulate imageStore on MS images). I'll remove it.
