### ISSUE TITLE
SUPER MARIO ODYSSEY 1.0.0 - черный экран и вылетает программа после взятия лун на уровне "Темная луна"

### ISSUE THREAD

**Issue by MONKAKAK** [yuzu-emu/yuzu#5346]
Добрый день! 

Играю на yuzu версии 5.06, характеристики компьютера, следующие:
Windows 10 pro / AMD Ryzen 5 1600 Six-Core Processor 3.20 GHz / Оперативная память 16,0 ГБ / NVIDIA GeForce GTX 1050 Ti
Игра SUPER MARIO ODYSSEY 1.0.0.
Настройки выставлены следующие: 

<a href="https://ibb.co/193CVvw"><img src="https://i.ibb.co/193CVvw/4.png" alt="4" border="0"></a>   

Прошел всю игру до уровня «Темная луна». После того как убиты все боссы и показываются финальные 3 луны, Марио берет их и далее черный экран 10 секунд и Yuzu сам автоматически закрывается (вылетает). При повторном запуске игры, сохранение с начала уровня «Темная луна» и приходиться заново всех боссов убивать… И так пробовал два раза пройти уровень – безрезультатно. 
Также попробовал поменять на «Vulkan» в настройках графики – безрезультатно.
Просьба помочь исправить ошибку, т.к. невозможно пройти до конца данный уровень. 
Спасибо!

---------------------------------------------------

Good day!

I play on yuzu version 5.06, the characteristics of the computer are as follows:
Windows 10 pro / AMD Ryzen 5 1600 Six-Core Processor 3.20 GHz / 16.0 GB RAM / NVIDIA GeForce GTX 1050 Ti
SUPER MARIO ODYSSEY 1.0.0 game.
The settings are as follows:

<a href="https://ibb.co/193CVvw"><img src="https://i.ibb.co/193CVvw/4.png" alt="4" border="0"></a>

Completed the entire game up to the "Dark Moon" level. After all the bosses are killed and the final 3 moons are shown, Mario takes them and then a black screen for 10 seconds and Yuzu automatically closes (crashes). When you restart the game, save from the beginning of the level "Dark Moon" and have to kill all the bosses again ... And so I tried to pass the level twice - to no avail.
I also tried changing it to "Vulkan" in the graphics settings - to no avail.
Please help fix the error. it is impossible to complete this level.
Thank you!

**Comment by BSoDGamingYT** [comment]
Can you upload a save? for this area?

**Comment by murlakatamenka** [comment]
#5202 is similar, it seems.

**Comment by MONKAKAK** [comment]
> Можете ли вы загрузить сохранение? для этой области?

Yes? thanks.


[save.zip](https://github.com/yuzu-emu/yuzu/files/5815432/save.zip)

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/5202.
