### ISSUE TITLE
big big issue!

### ISSUE THREAD

**Issue by denis-hash** [yuzu-emu/yuzu#5375]
![meme-1](https://user-images.githubusercontent.com/76909378/104817704-83065380-582b-11eb-8e8a-0173f342ff7b.jpg)
![meme-2](https://user-images.githubusercontent.com/76909378/104817705-84d01700-582b-11eb-83b9-3f285599870c.jpg)
![meme-3](https://user-images.githubusercontent.com/76909378/104817707-8568ad80-582b-11eb-8a69-adb4a2ffd928.jpg)
![meme-4](https://user-images.githubusercontent.com/76909378/104817709-8699da80-582b-11eb-8b57-1244fd225921.jpg)
![meme](https://user-images.githubusercontent.com/76909378/104817711-8699da80-582b-11eb-886f-fec7708b3881.jpg)

**Comment by Ecks1337** [comment]
![image](https://user-images.githubusercontent.com/68333357/104818553-2fdad380-5820-11eb-9fc2-bc6b3506475e.png)

**Comment by VirtualZillaGIT** [comment]
![Uploading Screenshot from 2021-01-16 18-38-52.png…]()

**Comment by VirtualZillaGIT** [comment]
![Uploading Screenshot from 2021-01-16 18-39-58.png…]()

**Comment by VirtualZillaGIT** [comment]
![Uploading Screenshot from 2021-01-16 18-40-46.png…]()
