### ISSUE TITLE
Rewrite our texture cache

### ISSUE THREAD

**Issue by Subv** [yuzu-emu/yuzu#540]
The current cache has evolved across many iterations to fit the requirements of the 3DS.
The Switch GPU is (hopefully) much more sane and doesn't need all this cruft, for example, I don't expect we'll ever see a need for overlapping compressed textures.

A simple cache would suit our needs just fine and reduce complexity quite a bit (and thus allow us to implement more stuff easily).

**Comment by Hexagon12** [comment]
Is this issue still relevant after all of the rasterizer cache changes?

**Comment by Dantttt** [comment]
Requesting to close

**Comment by niko1point0** [comment]
Is this still relevant? Has the cache been changed within the last year?

**Comment by Hexagon12** [comment]
A new texture cache is in the works.

**Comment by Hexagon12** [comment]
Solved by #2601
