### ISSUE TITLE
macos build instructions correction 

### ISSUE THREAD

**Issue by Gamedev1909** [yuzu-emu/yuzu#56]
from this 

cmake .. -DCMAKE_OSX_ARCHITECTURES="x86_64;x86_64h" -DCMAKE_BUILD_TYPE=Release should be
cmake .. -DCMAKE_OSX_ARCHITECTURES="x86_64;x86_64" -DCMAKE_BUILD_TYPE=Release

**Comment by Pavo-IM** [comment]
This is based on the make cmd in https://github.com/yuzu-emu/yuzu/wiki/Building-for-macOS btw

**Comment by MerryMage** [comment]
Remove that argument altogether if you don't want a fat binary. Why was this failing? Unicorn?

**Comment by Pavo-IM** [comment]
Yeah it was building Unicorn with x86_64h instead of x86_64

**Comment by jroweboy** [comment]
Removed the line from the build instructions, thanks for pointing out that we were having people build a fat binary for local development 👍 @bunnei can close this now

**Comment by bunnei** [comment]
ty, lgtm 👍

**Comment by Shmadul** [comment]
Thank You, I was getting all sorts of errors from qsettings.h, but after running your corrected version, it compiled perfectly :)
