### ISSUE TITLE
Age of Calamity Shimmering Effect and Black Screen - Vulkan - EA 1332

### ISSUE THREAD

**Issue by lordtomtom** [yuzu-emu/yuzu#5747]
Hi!

Here are a few issues I've found playing Age of Calamity on EA 1332 using Vulkan. First off, the BCR has made Age of Calamity incredibly playable on Vulkan now. 

System Specs:
i7-6700k
32 GB Ram
RTX 3080
Windows 10

There are two issues at play.

-Shimmering Effect-
I'm seeing an RGB shimmering effect in the middle distance in whatever direction the character is looking. See the attached shimmer screen shots. It's only at the middle distance, anything near or far is not affected by this and it moves as the character moves forward and back. See yuzu_log_shimmer_completed_mission.txt for the log file and yuzu_vulkan_shimmer1.png and yuzu_vulkan_shimmer2.png for image examples

-Black Screen in the Shadows-
This issue only pops up in dark maps, so Faron region, Hebra mountains, rito maps, etc. When walking into shadows from specific points of view, the entire screen goes black, with the exception of the HUD. Rotating the camera to a different angle or moving a bit out of it clears the issue, but moving back into the space, the problem reoccurs. See yuzu_log vulkan black screen.txt and yuzu_vulkan_black_screen.png. NOTE: This issue is was also prevalent in older versions on OpenGL as well, (but I can't give a comparison on EA 1332 at this time).

[yuzu_log_vulkan black screen.txt](https://github.com/yuzu-emu/yuzu/files/5825753/yuzu_log_vulkan.black.screen.txt)
[yuzu_log_vulkan_shimmer_completed_mission.txt](https://github.com/yuzu-emu/yuzu/files/5825754/yuzu_log_vulkan_shimmer_completed_mission.txt)
![yuzu-vulkan-black screen](https://user-images.githubusercontent.com/44859458/104835548-49017580-585c-11eb-8bc0-9be3e044d23a.PNG)
![yuzu-vulkan-shimmer1](https://user-images.githubusercontent.com/44859458/104835549-49017580-585c-11eb-92e3-086d1c2326f9.PNG)
![yuzu-vulkan-shimmer2](https://user-images.githubusercontent.com/44859458/104835550-499a0c00-585c-11eb-8f5f-a52718fa1582.PNG)

**Comment by Morph1984** [comment]
Fixed by #6585
