### ISSUE TITLE
Xenoblade Chronicles Definitive Edition Graphical Corruptions - Vulkan, Regardless of Settings - Mainline 509

### ISSUE THREAD

**Issue by GetBucked** [yuzu-emu/yuzu#5756]
Xenoblade Chronicles runs with severe graphical glitches on my configuration regardless of emu config and on the latest drivers.

![XCDE](https://user-images.githubusercontent.com/55707169/104867869-7c4d0e80-5907-11eb-8e57-9a1603f3c90e.PNG)

CPU: Ryzen 5 2500U
GPU: Radeon RX 560X
RAM: 16GB
OS: Windows 10
Driver: 20.12.1

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5827553/yuzu_log.txt)

**Comment by Niwu34** [comment]
![Unbenannt](https://user-images.githubusercontent.com/67392333/104891544-5fe5bc00-5971-11eb-8d7d-67b0340fd254.PNG)
same thing for me

Gpu Rx570, latest drivers

seems to be something similar to:
https://github.com/yuzu-emu/yuzu/issues/4995

**Comment by gidoly** [comment]
should fixed on last ea and mainline feel free to reopen if still happens
