### ISSUE TITLE
Unable to use the wishing stone / crashes after getting asked to save 

### ISSUE THREAD

**Issue by Red001469** [yuzu-emu/yuzu#5758]
Current yuzu version : 509 
Bug : the game crashes after using the wishing stone after the player is asked to save the progress [ normal save using the menu works fine ]
Device : msi GL65 leopard 
![16109521906515378985232247042091](https://user-images.githubusercontent.com/77605854/104880990-92e67a80-5986-11eb-9d64-cb38919c2744.jpg)
[The point of crash]

**Comment by v1993** [comment]
I think you should put game name into issue title, it's not self-explanatory right now.

**Comment by FearlessTobi** [comment]
Can you please provide a log file?

**Comment by gidoly** [comment]
close due to duplicated issue
