### ISSUE TITLE
[Feature Request] Make button A, B, X and Y mapped to where the XBOX counterparts are as a DEFAULT.

### ISSUE THREAD

**Issue by Emogop** [yuzu-emu/yuzu#5760]
Now the A is to the right where the cancelation button is, and it's counter intuitive for me. The same thing is with Y and X button. Y for me is always the top one.
I know that the current mapping also makes sense in regards to where the buttons on Nintendo controllers are. 
Or let's put it this way: if Yuzu detects Joycons, Pro, or any other Nintendo controller it maps them as they are. But if it detects Xinput or even Dualshock (which uses X as a conformation button in the west and is placed where the A button in an XBOX controller is) it changes the scheme to an XBOX one.
Here is an illustration in case I didn't make my thought clear.

![Screenshot_804](https://user-images.githubusercontent.com/42875723/104940482-dbbc2480-59c2-11eb-962f-efe0e7ba1def.png)

**Comment by Its-Rei** [comment]
That doesn't make sense in any way. We are emulating a switch here and not an XBOX. If you want to manually change the order of buttons you can certainly do so. Be advised that that may actually also make games much harder to play such as when you may need to use B and X at the same time in platformers or such - good luck when that is the left and right button instead of top and bottom.

**Comment by Emogop** [comment]
> If you want to manually change the order of buttons you can certainly do so.
I already have. First thing I did actually.



> Be advised that that may actually also make games much harder to play such as when you may need to use B and X at the same time in platformers or such - good luck when that is the left and right button instead of top and bottom.

The only game I can think of which may be relevant here is Super Mario Odyssey. But in SMO there are two jump buttons - A and B and two throw cap buttons - X and Y which is super convenient for cap jumps, either you remapped buttons XBOX style or not.

**Comment by Jatoxo** [comment]
This comes down to user preference, I also like having the button labels match, not their position, but I'm pretty sure other people have different preferences. Position wise basically every game will be fine with either, so having in-game button prompts match their button label would be of more value IMO.
Maybe there should be a poll to see which is more common and then the controls can be mapped according to that.

**Comment by Emogop** [comment]
> Maybe there should be a poll to see which is more common and then the controls can be mapped according to that.

Yeah, the poll, I'm thinking the same thing. I have a feeling I won't be alone in this request.



> Position wise basically every game will be fine with either, so having in-game button prompts match their button label would be of more value IMO.

How often are you looking at your controller after an in-game prompts? Never if you are more or less experienced with controllers. We should assume the majority of Yuzers aren't doing that, whether they used to one scheme or the other.

**Comment by goldenx86** [comment]
And what about single joy-con setups? Switch games display that visually telling you to press "the top button" or "the right button". Changing that will be a mess, if we set it as default.

**Comment by Emogop** [comment]
> Switch games display that visually telling you to press "the top button" or "the right button".

When a game tells me "Press A" my finger instinctively gravitates towards the bottom, not towards the right, 'cause I'm a western player, not a japanese one.

**Comment by goldenx86** [comment]
And if a game tells you to press left, like BotW, and you are pressing down?

**Comment by Emogop** [comment]
> And if a game tells you to press left, like BotW, and you are pressing down?

Analog sticks are working the same anywhere. And I didn't mention them in my header.

**Comment by Jatoxo** [comment]
Yuzu knows which controller is selected, so you could map it based on location when it's single joy one and button labels when it's the pro controller

**Comment by german77** [comment]
Yuzu doesn't know if the single joycon will be horizontal or vertical. The game decides that on run time

**Comment by Jatoxo** [comment]
I'm saying to leave things as they are and only apply the auto map change to the configurations that are static like the Pro Controller

**Comment by Maverynthia** [comment]
Please no XBOX as default for a Nintendo console even with an XBOX controller plugged in. (Who has had these button mappings since the SNES days and one could argue that Microsoft is doing it wrong. Even Playstation had these mapping before Sony US remapped it all)

**Comment by Morph1984** [comment]
This really doesn't make sense to me at all.
First of all, we're emulating a Nintendo console, which you are expected to own and would be somewhat accustomed to its button layout. We map based on its physical location, not how other platforms decide to map their controllers.
Second of all, there are controller adapters or w/e that emulate the Xbox controller, and so it would affect more than just the Xbox controller.
Third of all, you can manually map the alternate layout if you so desire and save it as a controller profile.
As such, this does not provide much value to the end user who in most cases would very much prefer using the Nintendo layout on a Nintendo console emulator by default.

**Comment by Wuawydu** [comment]
PLZ, i'm a visual dependency and close to autism player, i need this set right. Help me, us.
It's something that could break the game you know ...
Like, sometimes it jus breack my immersion.
There was a time that LoZ BotW 
had this option, a plugin!?
Or maybe i'm a very crazy one...
<3

**Comment by Mister-Curious** [comment]
Its an easy switch to accomplish if you use DS4Windows to remap the buttons. I do it for all Yuzu games.
