### ISSUE TITLE
Known games that run at about 2fps

### ISSUE THREAD

**Issue by german77** [yuzu-emu/yuzu#5761]
Many games have 2fps performance regardless of hardware. They all seem to have high usage of dynarmic and almost anything else on idle.

- Absolute drift
- Angry Video Game Nerd 1 & 2 Deluxe
- Cecconoid
- Cobra Kai
- Dustoff Z
- Fight
- Foregone
- Gleamlight
- JDM Racing 2
- Johnny Rocket
- Jump the rope
- Monster hunter rise demo
- My hidden things
- PHOGS!
- Roah
- Shing
- Spiritfarer
- Supper robot wars
- Windbound

**Comment by bunnei** [comment]
Can confirm the high dynarmic usage. This is with Johnny Rocket.

@MerryMage can ideas what could be going on here? Thank you!

![image](https://user-images.githubusercontent.com/6956688/104964757-ee6a3580-5991-11eb-9842-2d79e38ab020.png)

**Comment by bunnei** [comment]
Monster Hunter Rise demo

![image](https://user-images.githubusercontent.com/6956688/104968234-2aa19400-599a-11eb-88b8-35bd7fc2b219.png)

**Comment by Its-Rei** [comment]
Windbound, Spiritfarer & Gleamlight do the same thing.

**Comment by german77** [comment]
My hidden things
![image](https://user-images.githubusercontent.com/5944268/105125233-8276f280-5aa1-11eb-839a-543b4a74b2e2.png)

**Comment by german77** [comment]
Dustoff Z
![image](https://user-images.githubusercontent.com/5944268/105268150-4aca8200-5b57-11eb-9a15-28b32e105477.png)

**Comment by german77** [comment]
Fight
![image](https://user-images.githubusercontent.com/5944268/105268204-6170d900-5b57-11eb-86ad-433dd54b9185.png)

**Comment by german77** [comment]
Foregone
![image](https://user-images.githubusercontent.com/5944268/105268234-6d5c9b00-5b57-11eb-9e2a-d743d1d50ebc.png)

**Comment by german77** [comment]
JDM Racing 2
![image](https://user-images.githubusercontent.com/5944268/105382088-565c8e00-5bd5-11eb-9433-d8b934128ebb.png)

**Comment by theboy181** [comment]
PHOGS!
![image](https://user-images.githubusercontent.com/9299743/105432433-7fe4dc00-5c0c-11eb-9f75-83cdd227dbb5.png)
