### ISSUE TITLE
How do I build on Ubuntu?

### ISSUE THREAD

**Issue by CHJ85** [yuzu-emu/yuzu#5762]
Hi there. I'm trying to build Yuzu on Ubuntu 20.10. I followed the CMake + Ninja instructions, which did not work.
I know there's a snap available, but I ain't doing snaps. Not to be complicated or anything. 😀
I also tried to build from the CMakeLists file, but that was also a bust. I believe it even said that in the instructions.
So, long story short. How do I go about building it? Honestly I wish there was a deb package, or even a Flatpak would do.

**Comment by goldenx86** [comment]
https://github.com/yuzu-emu/yuzu/wiki/Building-For-Linux Did you follow the dependencies requirement?

**Comment by CHJ85** [comment]
@goldenx86 Yes of course. These were the instructions I followed.

**Comment by lat9nq** [comment]
This is a place for issues with the emulator, not for support. When you created this issue, you were linked to two avenues to get support, our Discord server and the Citra Support Forums. I recommend taking one of those suggestions if you really need to build yuzu.

I assume you really just want to run the emulator and are not necessarily interested in development. As for what you can do to get yuzu running, if you go to [our downloads page](https://yuzu-emu.org/downloads/) you'll see a download link for our AppImage and instructions on how to use it.

**Comment by CHJ85** [comment]
Right and thank you. I didn't realize there was an appimage.
Sorry for wasting your time.
