### ISSUE TITLE
Mario kart Video Playback issue - Vulkan

### ISSUE THREAD

**Issue by Banjo-Kazooie-fan** [yuzu-emu/yuzu#5768]
My Specs:
- Ryzen 5 3600, Rx570, 32gb Ram.
- latest driver 20.12.1 

Yuzu has issues loading this nvdec playback seen in the screenshots - fps stayed at 60fps and the emulator froze for a few secs before the screen (on the latest [ea 1342]) was taken : 
The log:
[Mario kart - video playback issue.txt](https://github.com/yuzu-emu/yuzu/files/5837870/Mario.kart.-.video.playback.issue.txt)

latest Build (Ea 1342):
![Mario kart 8 - freeze in menu](https://user-images.githubusercontent.com/74963292/105076523-71bb8200-5a8b-11eb-80ea-1ed6682467d5.PNG)

older build (Ea1339) [working]: 
![still working in 1339](https://user-images.githubusercontent.com/74963292/105076679-a62f3e00-5a8b-11eb-87bc-b374d4f7e1b0.PNG)

**Comment by Banjo-Kazooie-fan** [comment]
i retried and was able to get this playback shown this time - seems random - i'll leave this PR open for now and let the devs decide wether they want to keep this pr open or not...

**Comment by v1993** [comment]
Note: PR refers to pull request and this is not one (it's an issue).

**Comment by Banjo-Kazooie-fan** [comment]
> Note: PR refers to pull request and this is not one (it's an issue).

Thank you!
I corrected it.

**Comment by benderscruffy** [comment]
can be closed 
this is fixed
