### ISSUE TITLE
Games running on the Vulkan Api freeze at the loading screen after Ea 1332

### ISSUE THREAD

**Issue by Banjo-Kazooie-fan** [yuzu-emu/yuzu#5769]
My Specs:

Ryzen 5 3600, Rx570, 32gb Ram.
latest driver 20.12.1

A big variety of games can not load into gameplay - i am able to get past the menu and load the progressbar, then the emulator drops to 0 fps... Sound goes on

*Those are the few i tested so far - they all worked on Early Access 1334, failed afterwards*

Mario kart:
![mk 8 freeze - loading screen](https://user-images.githubusercontent.com/74963292/105079090-38851100-5a8f-11eb-9be1-8522e84a08ca.PNG)
Log:
[Mario kart - freeze.txt](https://github.com/yuzu-emu/yuzu/files/5837991/Mario.kart.-.freeze.txt)

Breath of the wild:
![botw loading bar freeze](https://user-images.githubusercontent.com/74963292/105080337-f4930b80-5a90-11eb-9756-c68dc3afb1f4.PNG)
Log:
[botw - freeze.txt](https://github.com/yuzu-emu/yuzu/files/5838030/botw.-.freeze.txt)

Super Mario Odyssey:
no picture as it is just black - 0 Fps as usual
Log:
[smo - freeze.txt](https://github.com/yuzu-emu/yuzu/files/5838060/smo.-.freeze.txt)

Not all games were affected: Super Smash Bros Ultimate eg is fine.

**Comment by xatornet** [comment]
> My Specs:
> 
> Ryzen 5 3600, Rx570, 32gb Ram.
> latest driver 20.12.1
> 
> A big variety of games can not load into gameplay - i am able to get past the menu and load the progressbar, then the emulator drops to 0 fps...
> 
> _Those are the few i tested so far - they all worked on Early Access 1334, failed afterwards_
> 
> Mario kart:
> ![mk 8 freeze - loading screen](https://user-images.githubusercontent.com/74963292/105079090-38851100-5a8f-11eb-9be1-8522e84a08ca.PNG)
> Log:
> [Mario kart - freeze.txt](https://github.com/yuzu-emu/yuzu/files/5837991/Mario.kart.-.freeze.txt)
> 
> Breath of the wild:
> ![botw loading bar freeze](https://user-images.githubusercontent.com/74963292/105080337-f4930b80-5a90-11eb-9756-c68dc3afb1f4.PNG)
> Log:
> [botw - freeze.txt](https://github.com/yuzu-emu/yuzu/files/5838030/botw.-.freeze.txt)
> 
> Super Mario Odyssey:
> no picture as it is just black - 0 Fps as usual
> Log:
> [smo - freeze.txt](https://github.com/yuzu-emu/yuzu/files/5838060/smo.-.freeze.txt)
> 
> Not all games were affected: Super Smash Bros Ultimate eg is fine.

you can add Luigi's Mansion 3, it loads to blackscreen menu, with only audio.

**Comment by ReinUsesLisp** [comment]
This should be fixed in the last commit.

**Comment by Banjo-Kazooie-fan** [comment]
Thanks a lot @ReinUsesLisp everything works again!

**Comment by freerangerstudios** [comment]
I'm having the same issue on the latest version now
