### ISSUE TITLE
Splatoon 2 is too bright - Vulkan

### ISSUE THREAD

**Issue by Banjo-Kazooie-fan** [yuzu-emu/yuzu#5770]
My Specs:

Ryzen 5 3600, Rx570, 32gb Ram.
latest driver 20.12.1

This started with 1332 iirc

When i boot up Splatoon 2:
![Splatoon 2 boot ](https://user-images.githubusercontent.com/74963292/105082712-42f5d980-5a94-11eb-82ad-3794b43a04a2.PNG)

This can be fixed by going into the weapon selection for a sec (pressing +):
![Splatoon 2 fixed by going into the weapon selection](https://user-images.githubusercontent.com/74963292/105082798-5ef97b00-5a94-11eb-8859-fb99ea9f0187.PNG)

**Comment by Banjo-Kazooie-fan** [comment]
The log file:
[Splatoon 2 log.txt](https://github.com/yuzu-emu/yuzu/files/5838184/Splatoon.2.log.txt)

**Comment by ReinUsesLisp** [comment]
I can't reproduce this on 20.11.2, I'll try updating later.

**Comment by Banjo-Kazooie-fan** [comment]
same thing on 20.11.2 - maybe something specific to my gpu model..
https://rog.asus.com/graphics-cards/graphics-cards/rog-strix/rog-strix-rx570-8g-gaming-model/

**Comment by G-Spawn** [comment]
Please reopen issue if this still happens to you on newer yuzu version and updated drivers and provide updated log. This shouldn't be an issue anymore
