### ISSUE TITLE
backup loading problem Zelda BOTHW EA1344

### ISSUE THREAD

**Issue by Drakod** [yuzu-emu/yuzu#5773]
hangs when loading backup
 yuzu EA 1344

[yuzu_log.EA1343.txt](https://github.com/yuzu-emu/yuzu/files/5841485/yuzu_log.EA1343.txt)

ok with the EA1334

[yuzu_log.EA1334.txt](https://github.com/yuzu-emu/yuzu/files/5841487/yuzu_log.EA1334.txt)

thank you

**Comment by Banjo-Kazooie-fan** [comment]
same issue as me:
https://github.com/yuzu-emu/yuzu/issues/5769

**Comment by ReinUsesLisp** [comment]
This should be fixed in the last commit.

**Comment by Drakod** [comment]
ils ok thx
