### ISSUE TITLE
pokemon sword not opening EA 1336  and up 

### ISSUE THREAD

**Issue by alin0484** [yuzu-emu/yuzu#5775]
pokemon shield stuck at loading last working build was ea 1332
My PC:
Amd Ryzen 5 2600 
16 gb ram 
Amd radeon rx 570 4gb 
OS:Windows 10
![Screenshot 2021-01-20 144124](https://user-images.githubusercontent.com/77732007/105177675-ad0f8c80-5b2f-11eb-9d28-879992cefb01.png)

**Comment by BSoDGamingYT** [comment]
please post a log, and if you are using extreme GPU accuracy, set it to high

**Comment by alin0484** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5842579/yuzu_log.txt)

**Comment by alin0484** [comment]
is working on opengl EA 1344

**Comment by alin0484** [comment]
![Screenshot 2021-01-24 120201](https://user-images.githubusercontent.com/77732007/105626938-2531c700-5e3c-11eb-9ccb-3645ab04f1e3.png)
good is working now
