### ISSUE TITLE
Super Mario Party crashed

### ISSUE THREAD

**Issue by cwalker** [yuzu-emu/yuzu#5791]
Super Mario Party crashed after players select

specs: 
Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz
16GB
GeForce GTX 1060 3GB

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5854870/yuzu_log.txt)

**Comment by legend800** [comment]
I can confirm this issue. It's a regression which started in the late summer/early fall of 2020.

**Comment by legend800** [comment]
This can be closed.

**Comment by cwalker** [comment]
Yes, Works on latest EA builds.
