### ISSUE TITLE
black screens in ultimate, unreachable code error.

### ISSUE THREAD

**Issue by Caironyx** [yuzu-emu/yuzu#5793]
Whenever I try loading up a stage for versus matches a lot of times I get this error. I checked the log file afterwards and it still said its 0KB (this was running console log and extended log while in game.) My specs are:  
MD Ryzen 7 1700 Eight-Core processor 3GHz
16GB ram
x64
Nvidia Geforce RTX 2060 for GPU 

I don't know if it's my PC or the emulator, I really don't know what to do and it's frustrating. (Also no idea why it picked this for my pfp lol)
![image](https://user-images.githubusercontent.com/77861050/105551282-6c17a380-5cfa-11eb-8868-d156fd2f6896.png)

**Comment by Cyber506** [comment]
i have the same problem :(

**Comment by G-Spawn** [comment]
This should be fixed on latest mainline yuzu versions.
