### ISSUE TITLE
Resident Evil Zero/One - Graphical regression

### ISSUE THREAD

**Issue by BSoDGamingYT** [yuzu-emu/yuzu#5801]
Both Resident Evil Zero and Resident Evil no longer render on Vulkan after the new texture cache rewrite. Last working build is mainline 488.

Resident Evil Zero Before
![Capture](https://user-images.githubusercontent.com/38402209/105579388-90b95d00-5d86-11eb-9e5f-04b302ae7a44.PNG)

Resident Evil Zero Now
![Capture](https://user-images.githubusercontent.com/38402209/105579427-d7a75280-5d86-11eb-8a76-65613aa5097a.PNG)

Resident Evil before
![Capture](https://user-images.githubusercontent.com/38402209/105579670-1a1d5f00-5d88-11eb-89b5-6c59330d2bcb.PNG)

Resident Evil Now
![RE 1](https://user-images.githubusercontent.com/38402209/105579676-23a6c700-5d88-11eb-9a83-5b261c0213bd.PNG)

**Comment by FearlessTobi** [comment]
Missing a log file.

**Comment by benderscruffy** [comment]
@FearlessTobi 
both games render the graphics properly on Vulkan now
can be closed
