### ISSUE TITLE
Disgaea 6 low FPS and some graphics issues

### ISSUE THREAD

**Issue by fuhuan416** [yuzu-emu/yuzu#5802]
It's just in the main menu. The background is 2D, and the FPS is about 8±1. 
After entering the game and starting to fight, there are graphics problems, and the FPS is still stable at 8 frames
![01005ee013888000_2021-01-23_21-27-37-021](https://user-images.githubusercontent.com/6281757/105579785-95503680-5dc3-11eb-9d48-9c2753291f60.png)
![01005ee013888000_2021-01-23_21-39-49-037](https://user-images.githubusercontent.com/6281757/105579786-98e3bd80-5dc3-11eb-9695-b3e23fccdf88.png)
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5860277/yuzu_log.zip)

**Comment by fuhuan416** [comment]
This is a screenshot of the Swtich
![Disgaea-6-Gameplay-Images-ps5-scaled](https://user-images.githubusercontent.com/6281757/105580678-c848f900-5dc8-11eb-8d86-7753dfa464ef.jpg)

**Comment by fuhuan416** [comment]
EA-1366, It's fixed! Amazing works! Let me test the Valkyria Chonicles 4
![yuzu 2021-01-23 21-37-58-703](https://user-images.githubusercontent.com/6281757/105634967-95236a00-5e9b-11eb-9e07-7bbeb06e4da4.png)

**Comment by fuhuan416** [comment]
EA-1366, It's fixed! Amazing works! Let me test the Valkyria Chonicles 4
![yuzu 2021-01-24 23-46-07-412](https://user-images.githubusercontent.com/6281757/105636012-09144100-5ea1-11eb-8201-f2c37e398073.png)

**Comment by fuhuan416** [comment]
> EA-1366, It's fixed! Amazing works! Let me test the Valkyria Chonicles 4
> ![yuzu 2021-01-24 23-46-07-412](https://user-images.githubusercontent.com/6281757/105636012-09144100-5ea1-11eb-8201-f2c37e398073.png)

I can display the scene after using Vulkan, but there are still problems with the character display, all of which are squashed.

**Comment by cself99** [comment]
The framerate is also fixed if you go to the first page of in-game settings and change the setting at the very bottom. Went from stable 8fps to stable 30fps.

**Comment by fuhuan416** [comment]
> The framerate is also fixed if you go to the first page of in-game settings and change the setting at the very bottom. Went from stable 8fps to stable 30fps.

The method you provided really worked! FPS reached 30, maybe I should pay attention to the game settings before reporting issues.

**Comment by fuhuan416** [comment]
> The framerate is also fixed if you go to the first page of in-game settings and change the setting at the very bottom. Went from stable 8fps to stable 30fps.

The method you provided really worked! FPS reached 30, maybe I should pay attention to the game settings before reporting problems.
EA-1384
The image issue remains the same.

**Comment by alucaltair** [comment]
EA-1392 
Image issue remains the same.
Could you pls try to fix it

**Comment by alucaltair** [comment]
1405 EA
and still dont work

**Comment by fuhuan416** [comment]
EA-1463
Vulkan's graphics issues has been solved, and he looks perfect!
But the issuess of OpenGL still exists.

![yuzu 2021-02-16 04-37-49-413](https://user-images.githubusercontent.com/6281757/107991050-c44b7800-7010-11eb-955f-269c450cc384.png)
[yuzu_log_OpenGL_EA-1463_Disgaea 6.zip](https://github.com/yuzu-emu/yuzu/files/5984013/yuzu_log_OpenGL_EA-1463_Disgaea.6.zip)

**Comment by german77** [comment]
The game issues seem fixed on latest EA 1855. Performance is fixed by using the latest game update. Re-open if needed.

**Comment by lolcatsnin** [comment]
Vulken on intel XE gpu have the same issue as the 3d models.
Device OneXplayer
