### ISSUE TITLE
Port to Xbox Series X|S and Xbox One

### ISSUE THREAD

**Issue by AyderProgramic** [yuzu-emu/yuzu#5827]
Will the emulator work on Xbox serias x|s, and will you port it?
It would be nice to play Nintendo switch games on the xbox!

**Comment by G-Spawn** [comment]
No..

**Comment by CrusadingNinja** [comment]
Bruh...

**Comment by degasus** [comment]
Please use this tracker for issues, not for generic feature requests.

**Comment by goldenx86** [comment]
The Xbox series enforces the use of DirectX12, which is not suitable for yuzu.
