### ISSUE TITLE
texture cache rewrite regression flickering detail on lake hylia bridge pillar

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#5833]
breath of the wild have some graphic weirdness going on
1st (tested on mainline 488 which don't have new texture cache if it is tcr regression, it was new texture cache regression)

https://youtu.be/njZ-JOWKKkA
video to show issue and reproduce step
save used in this video

[01007EF00011E000.zip](https://github.com/yuzu-emu/yuzu/files/6910941/01007EF00011E000.zip)
hardware:
ryzen 5800x 
rtx 2080 super
GG-Ghost pc
i9-9900k
rtx 2070 super

log:
[log.zip](https://github.com/yuzu-emu/yuzu/files/5878513/log.zip)

**Comment by G-Spawn** [comment]
Also noticeable with the Trees in great plateau and other places with assembly shaders off 

https://streamable.com/5x2weo

**Comment by gidoly** [comment]
2nd issue fixed thanks to accuracy high fix

**Comment by gidoly** [comment]
upated issue name and post for better representation
