### ISSUE TITLE
NBA 2k21 can't boot

### ISSUE THREAD

**Issue by fuhuan416** [yuzu-emu/yuzu#5839]
EA-1384
I waited for a few minutes after the emulator started the game and kept the black screen.
This is the log file
[yuzu_log - nba 2k21.zip](https://github.com/yuzu-emu/yuzu/files/5885253/yuzu_log.-.nba.2k21.zip)

**Comment by benderscruffy** [comment]
@FearlessTobi 
goes ingame now
can be closed
