### ISSUE TITLE
The Elder Scrolls V: Skyrim stuck on menu

### ISSUE THREAD

**Issue by fuhuan416** [yuzu-emu/yuzu#5844]
EA-1391
You can enter the menu interface through the LOGO, but to display the menu options, you must cancel the game after asking you whether to enter the NS SHOP dialog box via the Internet. At this time, I can still move the cursor to select yes or no, just in At this time, I haven't clicked Yes or No, and the following code appeared in the log file:

> Audio <Error> audio_core\splitter_context.cpp:RecomposeDestination:385: Invalid splitter info size! size=0

Once this line of code appears, the game will be completely stuck, the cursor cannot be moved, and the fps will become 0.
This line of code is between a large number of Bad splitter data headers, as follows:

> [49.673069] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [49.707559] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [49.741578] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [49.775616] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [49.809706] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [49.843710] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [49.877715] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [49.911571] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [49.950143] Audio <Error> audio_core\splitter_context.cpp:RecomposeDestination:385: Invalid splitter info size! size=0
> [49.950151] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [49.986481] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [50.020647] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [50.054677] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [50.088701] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [50.122577] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [50.156919] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header
> [50.191686] Audio <Error> audio_core\splitter_context.cpp:UpdateInfo:305: Bad splitter data header

[yuzu_log - The Elder Scroll V Skyrim.zip](https://github.com/yuzu-emu/yuzu/files/5895111/yuzu_log.-.The.Elder.Scroll.V.Skyrim.zip)

**Comment by gidoly** [comment]
Close due to issue resolved
