### ISSUE TITLE
input: Handheld controller is potentially always connected in addition to user controllers

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#5873]
Caused by #5805

In addition to any of the controllers configured, the handheld controller is also always enabled. So for multiplayer games, if for example the user has a Pro Controller configured, there will be two inputs in yuzu from the same controller. SSBU for example takes it as 2 players. This also causes the Docked switch to be disabled in the settings.

Though it's a regression introduced in Mainline 522, this issue affects older versions of yuzu *after* experiencing the bug in a recent version.

Reproduction steps:

0. Start yuzu Mainline 522 or later
1. Open the controller config with only Player 1's controller configured.
2. Set the controller type to Handheld
3. Save the configuration by pressing Okay
4. Open the controller config again
5. Set Player 1's controller type to any controller type other than Handheld
6. Save the configuration by pressing Okay

This can be fixed by using any older version of yuzu and following the same steps (then starting a recent version if you so desire).

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5924129/yuzu_log.txt)

**Comment by OZtistic** [comment]
Would this be an issue in Controller mappings (and QT) or a flag for handheld that is set?
Or, would yuzu just hold onto these/set these for handheld regardless of configuration?
What is the current logic?

Wouldn't this be the correct way of handling it, be the default? Handheld? 
(I know we and the games tend to prefer Docked mostly for performance reasons)
I just thought I'd ask

So, for configuration, we should be flavoring the user configured settings and not applying handheld regardless as a fallback?
Am I correct?
Does this affect any other controller transform types (is that the term?) i.e: Gamecube etc

Is there a service that turns off controller input from the handheld, when another device is detected?

I don't know why I wrote this, I'm just spitballing for someone to get an idea

**Comment by lat9nq** [comment]
Fixed by #5870, however there is no migration code, so users affected by this issue need to follow the reproduction steps listed above to solve it in newer versions.
