### ISSUE TITLE
Massive Delay on Switch Pro Controller

### ISSUE THREAD

**Issue by Samford1** [yuzu-emu/yuzu#5882]
I am on Yuzu 520, using ProconXInput because otherwise it doesn't receive any input. I am using the latest version of Windows 10 and the latest GPU drivers from NVIDIA. My controller is plugged in, because Bluetooth doesn't seem to work with ProconXInput.

When I press a button or move the sticks around, it takes a full second to register. It happens on all games. I tried switching to keyboard just to see if there was delay, and there wasn't. My PlayStation 4 controller doesn't have any delay either. I don't know if it's an issue with Yuzu, my controller or ProconXInput. Is there anyway to fix this? I don't know if you need any more information, so if you do, let me know. I've attached my log just in case you need it.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5936375/yuzu_log.txt)

**Comment by v1993** [comment]
If other controllers work fine I suspect the issue is not with Yuzu. Maybe test controller with some other native software than Yuzu? I also doubt the issue is with controller itself.

You also can try disabling vibrations in input menu and see if that helps in any way.

**Comment by TechnikEmpire** [comment]
It's not their controller. It's Yuzu. You can go into the configure menu and watch it track as you move the joysticks, and even that screen will freeze reading the inputs. Ryujinx 1.1.191 has no issue, same controller, same pc. Yuzu 1107 is dying just reading inputs inside the configure screen, never mind any game.

**Comment by Veticia** [comment]
I've noticed a massive uneven lag (sometimes over half a second), as well as gyro controls either not reacting in time or not stopping when movements stop. It occurred when I enabled direct Pro Controller driver. It works fine and is very accurate and responsive without it (except then amiibos don't work).

Mainline yuzu 1534

**Comment by rotj** [comment]
I'm experiencing this too. It doesn't happen all the time, but will come and go. I have the controller debug window up as I play and Yuzu sees button presses instantly, but the game will take about a half second to respond. It usually takes about 5 to 10 seconds to go away on its own, but I've noticed that if I alt tab twice to lose and gain focus, the delay immediately goes away.

**Comment by german77** [comment]
This is a signal issue. Sadly there's not much yuzu can do here to fix it.

**Comment by Samford1** [comment]
> This is a signal issue. Sadly there's not much yuzu can do here to fix it.

nope. i fixed this a while ago, it was a driver issue. windows chose the wrong driver for it
