### ISSUE TITLE
Mario odyssey fullscreen fps drop

### ISSUE THREAD

**Issue by srw20166** [yuzu-emu/yuzu#5884]
Ver.EA1331 
When play Mario odyssey in fullscreen fps drop (etc.move slow) . But in windows mode fps be safe.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5936541/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/5936553/yuzu_log.txt.old.txt)

**Comment by BSoDGamingYT** [comment]
Enable triple buffering in the nvidia control panel

**Comment by FearlessTobi** [comment]
I'll close this for the time being as BSoD has already provided a solution.
Also, with so few information given, it would be hard to narrow down the issue anyway.
If the problem persists, I would suggest asking for support on our Discord server.
