### ISSUE TITLE
Pokemon sword/ Texture bugged/ Yuzu

### ISSUE THREAD

**Issue by emeishin** [yuzu-emu/yuzu#5898]
Hi i don't know how to fix this problem.
My textures are bugged.
Anyone got ideas?
Thanks in advance.
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/78765856/107290125-4a424e80-6a66-11eb-9bb3-c6e889d91a4a.PNG">

**Comment by goldenx86** [comment]
Blind guess, sounds like outdated GPU driver.
Please use our forums or discord server for requesting assistance, this is a bug tracker.
