### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by EZElkins** [yuzu-emu/yuzu#59]
>MacOS platform

How to resolve it?

`-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (include):
  include could not find load file:`

    DownloadExternals

`-- CMake version: 3.10.1
-- Version: 3.0.2
-- Build type: Release
-- Performing Test HAVE_STD_CPP11_FLAG
-- Performing Test HAVE_STD_CPP11_FLAG - Success
-- Performing Test FMT_CPP11_CMATH
-- Performing Test FMT_CPP11_CMATH - Success
-- Performing Test FMT_CPP11_UNISTD_H
-- Performing Test FMT_CPP11_UNISTD_H - Success
-- Performing Test FMT_CPP11_SNPRINTF
-- Performing Test FMT_CPP11_SNPRINTF - Success
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES - Success
-- Performing Test SUPPORTS_INITIALIZER_LIST
-- Performing Test SUPPORTS_INITIALIZER_LIST - Success
-- Performing Test SUPPORTS_ENUM_BASE
-- Performing Test SUPPORTS_ENUM_BASE - Success
-- Performing Test SUPPORTS_TYPE_TRAITS
-- Performing Test SUPPORTS_TYPE_TRAITS - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Looking for open
-- Looking for open - found
CMake Error at glad/CMakeLists.txt:9 (create_directory_groups):
  Unknown CMake command "create_directory_groups".`

`CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as`

    cmake_minimum_required(VERSION 3.10)

  `should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.`

`-- Configuring incomplete, errors occurred!`

**Comment by Ubernerd23** [comment]
You need to update cmake

**Comment by EZElkins** [comment]
I received an error when I upgrade cmake. The latest version has been installed.

`Error: cmake 3.10.1 already installed`

**Comment by jroweboy** [comment]
You are running cmake against the wrong `CMakeLists.txt` You need to run it against the one in the root yuzu directory and not the one in src

**Comment by bunnei** [comment]
Please ask on Discord for support on building yuzu, the issues tracker is for emulator bugs and tasks.
