### ISSUE TITLE
Amiiboo issue With Animal Crossing New Horizon

### ISSUE THREAD

**Issue by Clayman201** [yuzu-emu/yuzu#5906]
The load Amiiboo feature don't work on Animal Crossing version 1.7.0 (others version not tested), (Amiiboo can be load but the game write that amiibo reading fail), the same amiiboo works on others game like mario odyssey and the amiiboo tested work on real switch. 

Anyways for an experimental software yuzu works very nice, congratulations

**Comment by FearlessTobi** [comment]
Closing in favor of https://github.com/yuzu-emu/yuzu/issues/6089, as the report is a bit more detailed.
