### ISSUE TITLE
Yoshi's Crafted World graphics issue

### ISSUE THREAD

**Issue by fuhuan416** [yuzu-emu/yuzu#5907]
EA-1440
This is a screenshot of the actual Switch
![01官图](https://user-images.githubusercontent.com/6281757/107600071-99060900-6c5d-11eb-9f3b-3b581ae59835.jpg)
And this is the OpenGL
![yuzu 2021-02-11 11-31-00-239](https://user-images.githubusercontent.com/6281757/107600035-7542c300-6c5d-11eb-8ff2-6ebc4fbb711c.png)
This is Vulkan
![yuzu 2021-02-11 11-35-11-926](https://user-images.githubusercontent.com/6281757/107600042-7f64c180-6c5d-11eb-93a6-33d0c6547542.png)

![OpenGL](https://user-images.githubusercontent.com/6281757/107600695-7248d200-6c5f-11eb-8681-3daaf8ac1977.gif)
![yuzu 2021-02-11 01-26-46-064](https://user-images.githubusercontent.com/6281757/107600682-69f09700-6c5f-11eb-9184-05f6c3c38ec2.png)
![yuzu 2021-02-11 01-26-47-578](https://user-images.githubusercontent.com/6281757/107600687-6c52f100-6c5f-11eb-87ac-89d872a57159.png)

Whether it is Vulkan or OpenGL, there are image problems after entering the game
And here are the Log files:
[yuzu_Yoshi's_OpenGL.zip](https://github.com/yuzu-emu/yuzu/files/5963044/yuzu_Yoshi.s_OpenGL.zip)
[yuzu_Yoshi's_Vulkan.zip](https://github.com/yuzu-emu/yuzu/files/5963045/yuzu_Yoshi.s_Vulkan.zip)

**Comment by fuhuan416** [comment]
EA-1458
The BGR isseus of the OpenGL main menu is really solved!
Vulkan's issues still exist, refer to the screenshot above.
Then the issues of entering the game screen still exists
![01006000040c2000_2021-02-14_17-46-43-491](https://user-images.githubusercontent.com/6281757/107873480-c668e600-6eed-11eb-87f7-8d003b93206f.png)

[yuzu_log_OpenGL_EA-1458_Yoshi's.zip](https://github.com/yuzu-emu/yuzu/files/5977399/yuzu_log_OpenGL_EA-1458_Yoshi.s.zip)

**Comment by applepie1234a** [comment]
same problem with ea1495
main menu is terrible

**Comment by benderscruffy** [comment]
using EA 1939
graphics are getting better
In Poochy's Tape Trail
when the creatures roll up and unroll the fabric (or carpet) the fabric (or carpet ) is glitched
here is a save game aswell
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/6890426/yuzu_log.zip)
[01006000040C2000.ZIP](https://github.com/yuzu-emu/yuzu/files/6890428/01006000040C2000.ZIP)
![Capture](https://user-images.githubusercontent.com/2696404/127266474-0ea87739-8b91-41f3-8f21-e49041425f2c.PNG)

**Comment by G-Spawn** [comment]
This issue should be corrected on latest yuzu. Please reopen if it still happens
