### ISSUE TITLE
button to update version of yuzu

### ISSUE THREAD

**Issue by manel547** [yuzu-emu/yuzu#5911]
<!please put a button to update version of yuzu---
Please keep in mind yuzu is EXPERIMENTAL SOFTWARE.

Please read the FAQ:
https://yuzu-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of yuzu you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

-->

**Comment by manel547** [comment]
because if I don't have to download a new version every day

**Comment by renA21** [comment]
You can just use the installer to download and install yuzu instead of just downloading manual builds. The installer checks for updates every time you open yuzu from the Start Menu.

**Comment by german77** [comment]
The installer also installs the maintenance tool that allows to update yuzu to the latest version manually with a single click or just like ren said opening yuzu from the start menu
![image](https://user-images.githubusercontent.com/5944268/107662278-c0ee7000-6c4f-11eb-9531-4a8b16eed9d7.png)

**Comment by manel547** [comment]
In the linux version you cannot

**Comment by v1993** [comment]
I think this can serve as a valid feature request if renamed to "Linux version of yuzu updater". It's true that there isn't a single-click way of updating AppImage builds yet.
