### ISSUE TITLE
Hollow Knight: Transparent character textures on latest game version

### ISSUE THREAD

**Issue by ToxaGaming** [yuzu-emu/yuzu#5912]
I'm opening an issue for this as I haven't seen any other ones for this specific issue (do close if I happen to be wrong).

**Tested on Early Access 1443**

**Description:**
Currently Hollow Knight has an issue with some transparent character textures on the latest version of the game (v1.4.3.2)
This issue is not present on the base version (v1.3.2.9) where all character textures are opaque as they are supposed to.

The health bar and soul-meter in additon to these character textures are also suffering the same issue. There could be more textures plagued by this but I'll have to test some more if examples are desired.

**LOG FOR LATEST VERSION:**
[yuzu_log_HK_LatestVer.txt](https://github.com/yuzu-emu/yuzu/files/5968641/yuzu_log_HK_LatestVer.txt)

**LOG FOR BASE VERSION:**
[yuzu_log_HK_BaseVer.txt](https://github.com/yuzu-emu/yuzu/files/5968642/yuzu_log_HK_BaseVer.txt)

Here are some comparison screenshots showing what some of the characters look like on the latest update versus the base version of the game:

**LATEST VERSION**
![0100633007d48000_2021-02-11_22-27-18-704](https://user-images.githubusercontent.com/41490344/107702544-b1f0d780-6cba-11eb-86c8-a6962d021d81.png)
![0100633007d48000_2021-02-11_22-29-46-251](https://user-images.githubusercontent.com/41490344/107702602-c59c3e00-6cba-11eb-8127-9a5c6c524616.png)
![0100633007d48000_2021-02-11_22-30-22-634](https://user-images.githubusercontent.com/41490344/107702728-f3818280-6cba-11eb-8d93-1bb1620cbe9b.png)
![0100633007d48000_2021-02-11_22-32-29-764](https://user-images.githubusercontent.com/41490344/107702643-d8167780-6cba-11eb-9047-0e025e3844c9.png)

**BASE VERSION**
![0100633007d48000_2021-02-11_22-37-01-248](https://user-images.githubusercontent.com/41490344/107702669-dfd61c00-6cba-11eb-97cd-c3ff9cd61887.png)
![0100633007d48000_2021-02-11_22-37-52-830](https://user-images.githubusercontent.com/41490344/107702673-e19fdf80-6cba-11eb-8cf8-4471c3e06e6d.png)
![0100633007d48000_2021-02-11_22-38-48-395](https://user-images.githubusercontent.com/41490344/107702705-ea90b100-6cba-11eb-961e-bc9d542f24d1.png)

**Comment by ToxaGaming** [comment]
I'd also like to note that this was tested using GLASM, however the issue is also present GLSL and Vulkan. If logs are desired for these APIs as well then do let me know!

**Comment by ToxaGaming** [comment]
Fixed by #6585

**Comment by v1993** [comment]
Hades is now in master.

**Comment by ToxaGaming** [comment]
Just saw it, closing.
