### ISSUE TITLE
Animal Crossing: New Horizons LayeredFS mods don't boot

### ISSUE THREAD

**Issue by guighub** [yuzu-emu/yuzu#5918]
I'm developing a mod for ACNH and I'm only using files that pretty much don't change throughout updates (sounds, images, etc.) my problem is that yuzu will not boot when I enable this mod when Ryujinx does. It'll boot forever and clicking Emulation/Stop will cause yuzu to crash.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5975265/yuzu_log.txt)

**Comment by KuronekosHerald** [comment]
From my experience (I used LayeredFS mods like items expansion) yuzu needs some time to load (10-15 minutes) when using mods with LayeredFS, but it works eventually. Did you tried to leave yuzu loading for at least 10 minutes?

**Comment by xActTM** [comment]
> From my experience (I used LayeredFS mods like items expansion) yuzu needs some time to load (10-15 minutes) when using mods with LayeredFS, but it works eventually. Did you tried to leave yuzu loading for at least 10 minutes?

I left it on for over 30 minutes and it eventually booted, but thats too long of a wait for someone whose developing a mod.

**Comment by KuronekosHerald** [comment]
Yes, 30 minutes are way too much, it isn't normal. Let's hope they'll fix it.

**Comment by cbartondock** [comment]
Seeing the same issue. Definitely an issue in Yuzu.

**Comment by cmod31** [comment]
would be cool if the loading time will be shorter at all. For making mods 10-15 minutes is a bit long especially when you have to do a lot of trial and error. In my case i sold my modded switch but wanted to finish a few mods

**Comment by v1993** [comment]
IIRC there's a VFS rewrite in works that will fix it. In the meantime the best solution is probably to use Riujinx while modding, which (I'm fairly sure) doesn't have this issue.

**Comment by TechnikEmpire** [comment]
I've run into this issue and have been profiling. The iteration over the rom file system takes up a huge portion of this time. I was able to solve it by introducing a fast lock system and parallelizing the whole iteration process but it still hangs for a long time.

Also the logging system is a huge impact on performance. During layeredfs loading there's a ton of logging calls. Each logging call does complex string formatting where it isn't necessary. For instance, paths are stripped down for source locations in every single log call. This can be converted into a constexpr function against __FILE__. Etc, etc. Still investigating.

**Comment by vermillion-excl** [comment]
Any update on this?

**Comment by Wynadorn** [comment]
Can confirm that waiting a while does eventually work, very strange though, because it's not like there's a lot of disk activity during this period.

**Comment by FensBK** [comment]
It's not fixed yet can confirm it.
The ryu competitor works fine with LayeredFS mods

**Comment by Zetakuu** [comment]
> Any update on this?

It's still not fixed.

**Comment by Lordmau5** [comment]
This issue is still present on build 1207.

As other users pointed out it works fine on Ryujinx but the performance isn't as good when run on the Steam Deck so I'd prefer to keep using Yuzu for this

**Comment by TheOrbOfDestiny** [comment]
for me it takes an eternity to launch then i finally get to an ingame loading screen then it crashes and i've effectively wasted 30 minutes of my life

**Comment by Fusseldieb** [comment]
Yep, same issue... It is essentially stuck at `Loading...` for eternity.

**Comment by someone5678** [comment]
Still doesn't fixed even in Early Access build...
