### ISSUE TITLE
Speed ​​reduction in version 538

### ISSUE THREAD

**Issue by ChrisM20** [yuzu-emu/yuzu#5922]
Hello, today I updated from version 536 to 538 and I notice a decrease in fps, in pokemon sword when walking under 11 to 5-7 in the title screen to touch button A under 20 to 9, After updating I see that some settings are changed by themselves

**Comment by CrusadingNinja** [comment]
Use high GPU accuracy for Pokemon games after BCR as it will run faster. Also, please keep the issue thread clear for bug reports, not for generic support requests.
