### ISSUE TITLE
TCR Regression in Cities Skylines

### ISSUE THREAD

**Issue by CrusadingNinja** [yuzu-emu/yuzu#5926]
In Cities Skylines with OpenGL and GLASM, there is a regression in the rendering of the text. This is not present with GLSL or Vulkan. 

![csprebcrasem](https://user-images.githubusercontent.com/77567969/107861531-f50e9000-6e0b-11eb-831a-fd7aabf13627.PNG)
488, Pre TCR
[citiesskylinespretcr.txt](https://github.com/yuzu-emu/yuzu/files/5976523/citiesskylinespretcr.txt)

![csbrokentext](https://user-images.githubusercontent.com/77567969/107861539-035cac00-6e0c-11eb-8ce4-26eaad155100.PNG)
535
[citiesskylinesbrokentext.txt](https://github.com/yuzu-emu/yuzu/files/5976524/citiesskylinesbrokentext.txt)

**Comment by CrusadingNinja** [comment]
Fixed by #6585

**Comment by BSoDGamingYT** [comment]
This should remain open until merged to master.
