### ISSUE TITLE
yuzu EA 1456 Pokémon Sword Rain Texture Bug

### ISSUE THREAD

**Issue by PhoenixOnARoof** [yuzu-emu/yuzu#5928]
There is an issue with the rain texture in pokemon sword where the rain will get stuck on the screen either when in a specific area or looking in a specific direction (If I move somewhere else that same rain is no longer a problem until I return to go back into that area) 

Here are some videos showing the issue.

[Video 1 (In the overworld)](https://user-images.githubusercontent.com/11891199/107865489-432f8d80-6e24-11eb-8c18-d001a0ca9a59.mp4)

[Video 2 (During a battle)](https://youtu.be/rlI0WTtfYJM)

I'm not sure how helpful this log will be but here
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/5976823/yuzu_log.txt.old.txt)

**Comment by hklgc** [comment]
hey did you got any fix

**Comment by hklgc** [comment]
i got it just set accuracy to high

**Comment by Moonlacer** [comment]
Enable Async GPU and use High accuracy

**Comment by gidoly** [comment]
should fixed on last ea and mainline feel free to reopen if still happens
