### ISSUE TITLE
Navi GPU Issue after BCR - Super Mario Odyssey

### ISSUE THREAD

**Issue by Loreciao** [yuzu-emu/yuzu#5932]
Since the newest BCR update on the mainline, Super Mario Odyssey seems to feature a game-breaking bug on my hardware (RX 570, R5 3600). The game boots and runs, but it's almost completely black. Mario can move around and interact with obejcts, but nothing can be seen.
Edit: Still broken with drivers 21.2.2 released on 05/02/2021.
Proof:
https://youtu.be/VIF4PFeiI8o

![unknown](https://user-images.githubusercontent.com/69169909/107873343-1629bc00-6eb2-11eb-8b52-45bb6c48f139.png)

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5977387/yuzu_log.txt)

**Comment by goldenx86** [comment]
Update to the latest 21.2.2 optional driver. VK_EXT_extended_dynamic_state was broken on previous drivers like yours.

**Comment by Loreciao** [comment]
@goldenx86 Still broken. Edited the post.

**Comment by gidoly** [comment]
iirc fixed by later amd driver update
