### ISSUE TITLE
Link’s Awakening Vulkan Crash

### ISSUE THREAD

**Issue by IavnFGV** [yuzu-emu/yuzu#5934]
Starting 
Link’s Awakening 

![image](https://user-images.githubusercontent.com/11654266/107880511-ce258c00-6ee7-11eb-820a-68e4b85f2faf.png)

getting yuzu shutdown during playing  intro with this logs

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5977956/yuzu_log.txt)

Previuosly (3-4 months ago) it was working via VULKAN
In Opengl mode it is working

**Comment by G-Spawn** [comment]
They don't support piracy just a by the way.
