### ISSUE TITLE
Mod Issue

### ISSUE THREAD

**Issue by renaejazzi** [yuzu-emu/yuzu#5938]
Hello I'm submitting an issue regarding a Romfs mod issue on yuzu involving New Super Mario Bros U. Deluxe..

the reason I'm submitting this is the fact how when I load Yuzu with (RomFs) or (LayeredFs) it makes the Launching Screen go into a boot loop unable to let New Super Mario Bros U. Deluxe load I have sent some pictures so you people can at least get an idea on what I'm trying to get at... the when I open those layeredfs aka romfs files the game goes straight into a boot loop I really hope yuzu team can fix this because my followers enjoy my Custom Peachette Levels and can't continue on if Yuzu keep going on a boot loop screen just because all those files in romfs that's making it run into a bootloop
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5980293/yuzu_log.txt)
**[Image deleted by Moderator]**
![Capture5](https://user-images.githubusercontent.com/79078298/107922162-3d759d00-6f35-11eb-99bf-4aa182d6e07a.PNG)

**Comment by Schplee** [comment]
Piracy is not supported. Please redump your game and try again. If the issue persists, please ask for support on our [Discord](https://discord.gg/u77vRWY) server, as the issue tracker isn't a support forum.
