### ISSUE TITLE
HDR Issue when exiting off fullscreen

### ISSUE THREAD

**Issue by MiltonAngelSoto** [yuzu-emu/yuzu#5940]
HDR Issues when exiting off fullscreen by pressing F11 or clicking other monitors in multi-setup. Program tries to disable hdr and makes displays darker colors. only work around ways is powering monitor off then back on, clicking hdr "off" then back on. To have hdr on but want to use other monitors with mouse go into hdr settings and clicking the hdr brightness bar but once i click on that monitor where the yuzu game is, it happens all over again. Does not happen to other emulators i have tried and rarely happens in other programs. Most likely code or other built in software is at fault and not my pc. I noticed there was another post about this issue but was closed and did not have the information and somewhat annoying fixes i have found to make work but is very inconvenient to always do. Nvidia updates do not fix issue and did all clean installations. Windows is always up to date and there is no integrity violations. Also only happens when actually playing on hdr monitors vs a non hdr monitor in multi-monitor setup and not disabling gsync because i like to play multiple games at once (steam, yuzu, etc)

All settings and guides still cause issues with what im experiencing so made some tweaks to make yuzu better to my needs

YUZU Settings:

Multicore CPU Emulation on
CPU Accuracy Accurate
OpenGL
Disk shader cache on
Asynchronous GPU emulation on
Nvdec emulation on
GPU Accuracy High
VSync off
Assembly shaders off
Asynchronous shaders building on
Fast GPU Time on
Anisotropic Filtering 16x

PC:

CPU : I9-10900kf
GPU: RTX 3090
Ram: 128 GB
SSD: 2 TB
HDD: 2 TB

Monitors:

34 Inch Ultrawide Alienware Gsync
27 Inch 4k LG HDR 6 Gsync
27 Inch 1080p LG HDR 10 Gsync

**Comment by gortyx** [comment]
I've got exactly the same issue! After leaving yuzu, my hdr is disabled and I have to disable/enable it on my screen (yuzu disabled it but my screen tells me it's still enabled in settings menu)! Last tested on mainline version 549!

Yuzu settings :

Multicore CPU Emulation on
CPU Accuracy Accurate
OpenGL
Disk shader cache on
Asynchronous GPU emulation on
Nvdec emulation on
GPU Accuracy normal
VSync on
Assembly shaders on
Asynchronous shaders building off
Fast GPU Time on
Anisotropic Filtering 8x

PC:

CPU : i5-9600kf
GPU: GTX 1080
Ram: 16 GB
SSD: 256 GB
HDD: 1,5 TB

Screen :

55" 4K LG TV UH605V

**Comment by hurricane-dorian** [comment]
Try "disable full-screen optimization" from right-click on yuzu icon -> properties -> Compatibility tab.

**Comment by hurricane-dorian** [comment]
Even my previous suggestion works, I would recommend you could use something like https://github.com/bradgearon/hdr-switch to switch hdr on/off from the taskbar.
HDR shouldn't be on unless you are viewing hdr content anyways.
Non-hdr applications on hdr mode is inherently an ugly hack that,  Windows applies filters on non-hdr aware applications otherwise they would be too bright. What you have been experiencing is this filter making apps darker while HDR is off.

**Comment by MiltonAngelSoto** [comment]
Problem fixed with borderless windows mode
