### ISSUE TITLE
Controller randomly stops working

### ISSUE THREAD

**Issue by GregariousJB** [yuzu-emu/yuzu#5941]
Yuzu 538
Game: Super Mario 3D World
Controller: Dualshock 4 (DS4), plugged in with USB (not using Bluetooth)
Also using [DS4Windows](https://github.com/Ryochan7/DS4Windows) v2.2.6
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5984246/yuzu_log.zip)

After ~2 minutes of play, the controller simply stops working. Reconnecting the controller by unplugging the USB cable and then plugging it back in fixes the issue, and then it stops again a minute or so later.

I see the following line repeated in the yuzu_log that might be relevant: 

```[1564.751330] Service.APM <Info> core\hle\service\apm\controller.cpp:SetClockSpeed:84: called, mhz=000003FC```

It also appears at the end of the log, which is right when my controller stopped working and I forcibly closed Yuzu and came here to report this. Maybe that `SetClockSpeed` function is stopping controller functionality?

Also relevant: When using CEMU I don't have this issue - same DS4Windows, same cable, same controller, etc - which leads me to believe this issue is specific to Yuzu.

Might be partially related to #4268 or #4852 

Thank you for this awesome emulator.

**Comment by antigamer101** [comment]
i also had the same problem but it got fixed after getting the lastest update tho it might be the controller itself
i am using an xbox 360 controller plugged with usb that was made for windows 10

**Comment by german77** [comment]
Might be wort it to try again. SDL was updated

**Comment by benderscruffy** [comment]
Is this still an issue ???

**Comment by Adesin-fr** [comment]
I'm also experiencing this.
I have to quit YUZU then relaunch it to continue playing.
PS : opening controller settings when it has "disconnected" makes yuzu unresponsive

**Comment by GregariousJB** [comment]
FYI - I managed to fix this by not using DS4Windows at all. Just plug the controller in and let Windows do its thing. Don't ever launch DS4Windows. My DS4 controller works fine on Yuzu without it. Currently on Yuzu build 3601, but it was working fine for about a dozen builds before that.

**Comment by Adesin-fr** [comment]
> FYI - I managed to fix this by not using DS4Windows at all. Just plug the controller in and let Windows do its thing. Don't ever launch DS4Windows. My DS4 controller works fine on Yuzu without it. Currently on Yuzu build 3601, but it was working fine for about a dozen builds before that.

I'm not using Windows neither DS4Windows ;)

**Comment by GregariousJB** [comment]
¯\_(ツ)_/¯

Should probably make a new issue then. This was originally a Windows issue when I made it.

I guess there's still technically a problem between DS4Windows and Yuzu, but I can play fine on Yuzu with my DS4 now, so I'll go ahead and close this.
