### ISSUE TITLE
SM3DW + BF pernamently softlock

### ISSUE THREAD

**Issue by BluelyTASer** [yuzu-emu/yuzu#5945]
A few inches later the fire flower is spawned, the game freezes then it softlocked.

https://user-images.githubusercontent.com/59511669/108061572-477fc480-7037-11eb-9ad8-b9b9f535d5e9.mp4

**Comment by BSoDGamingYT** [comment]
Please provide a log and the additional information the issue format asked for, thank you.

**Comment by BluelyTASer** [comment]
Closing this because i forgot to provide log so it automatically overwritten when I restarted yuzu and played the game.
