### ISSUE TITLE
Overblooming in Kirby Star Allies (Linux, nvidia and amd)

### ISSUE THREAD

**Issue by toccata10** [yuzu-emu/yuzu#5946]
I was advised by Goldenx86 to report this overblooming issue on Kirby Star Allies.
Testing config: Archlinux with r9 fury and a laptop with nvidia 970M.
The effect is extreme in some places: for example: echo's edge (2nd world), and present in others.
A few comparisons.
Yuzu:
![2021-02-16_18-41](https://user-images.githubusercontent.com/7478580/108102369-bfc2a600-7088-11eb-9768-3e887e20b44e.png)
Expected:
![2021-02-16_18-46](https://user-images.githubusercontent.com/7478580/108102387-c7824a80-7088-11eb-9269-f99f2cbf553e.png)
Yuzu:
![2021-02-15_23-31](https://user-images.githubusercontent.com/7478580/108102426-d36e0c80-7088-11eb-8836-67a3dda32688.png)
Expected:
![2021-02-15_23-09](https://user-images.githubusercontent.com/7478580/108102455-da951a80-7088-11eb-851e-3e04e8969108.png)
Tested on mainline and latest ea: no difference. No testing on Vulkan due to the very quick crash (on amd).
With mesa (amd), the game was launched with force_integer_tex_nearest=true to avoid some black glitches.
And the log:
[yuzu_log-kirbyoverblooming.txt](https://github.com/yuzu-emu/yuzu/files/5990607/yuzu_log-kirbyoverblooming.txt)

**Comment by v1993** [comment]
This issue have been around for me (Linux, Nvidia) well before both BCR and TCR, so it's probably not directly related to those rewrites.

**Comment by v1993** [comment]
This is working correctly on latest yuzu version (tested on Nvidia). Can be closed.
