### ISSUE TITLE
Yo-kai watch 4++ Unable to start the game

### ISSUE THREAD

**Issue by fuhuan416** [yuzu-emu/yuzu#5947]
You can enter the main menu of the game through Intro. After pressing start the game, the emulator will automatically close after a while. This is the final Log file:

[yuzu_log_Yo-kai watch 4++.zip](https://github.com/yuzu-emu/yuzu/files/5991700/yuzu_log_Yo-kai.watch.4%2B%2B.zip)

**Comment by einekratzekatze** [comment]
If you copy an existing Savefile (in my case from Ryujinx where the game work but has some fps issues) you can load said savefile but during the loading screen the same error will occur

**Comment by AeroRush** [comment]
> If you copy an existing Savefile (in my case from Ryujinx where the game work but has some fps issues) you can load said savefile but during the loading screen the same error will occur

Now sometimes loads and other times crash as before, but ingame will crash after you move

**Comment by fuhuan416** [comment]
Hey guys, it's fixed, i thini i can close this issue.
