### ISSUE TITLE
[Vulkan Renderer] SM3DW + BF (Bowser's Fury Game) Completely unbeatable due to RAM overflow on final boss of the game

### ISSUE THREAD

**Issue by BluelyTASer** [yuzu-emu/yuzu#5949]
On a computers with memory RAM equal or lower than 8 GB, can't progress the game due to RAM Overflowing, probably filling Memory RAM with models, textures and sound effects, because of this, people with equal or under than 8 GB RAM is unable to beat Bowser's Fury due to RAM Overflow, if could you rewrite the RAM Cache or implement a feature of RAM in SSD/HDD, It would be helpful.
# Screenshot:
![Image](https://cdn.discordapp.com/attachments/630479746798452746/811394243288891422/SPOILER_unknown.png)
# Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5992473/yuzu_log.txt)

**Comment by ameerj** [comment]
Can you test if this occurs using OpenGL as the rendering API?

**Comment by BluelyTASer** [comment]
> Can you test if this occurs using OpenGL as the rendering API?

Seems like the OpenGL solves the RAM Overflow issue and managed to beat this game on second day, took me over than 13 or 14 hours of playtime however the Shader Cache and Shader Building on OpenGL is so slower than Vulkan API, also, thanks to telling me that to test on OpenGL, your help is very appreciated!🙃

![image](https://user-images.githubusercontent.com/59511669/108191720-3d6ecc00-70f2-11eb-9e11-82c3553b5b1b.png)

**Comment by Chocobobobo** [comment]
You need 100 Nekoshine to beat the game, not 50. And I didn't know it was possible to have a PC with 8 GB of Ram in 2021...

**Comment by BluelyTASer** [comment]
> You need 100 Nekoshine to beat the game, not 50. And I didn't know it was possible to have a PC with 8 GB of Ram in 2021...

100 Nekoshine are nearly impossible to find without watching walkthroughs and this is the only PC with 8 GB of RAM that I have in the moment, I can't afford for a RTX 2060 laptop yet, I'll need to either wait for years or I get a job and earn enough money for that.

**Comment by gidoly** [comment]
should be fixed after texture reaper implemented feel free to reopen issue if it still happening
