### ISSUE TITLE
Vulkan 1.1 is not enough to run Yuzu anymore

### ISSUE THREAD

**Issue by GMaxera** [yuzu-emu/yuzu#5950]
I'm running Yuzu version 542 and since I've updated to this version I'm not able anymore to run games using the Vulkan drivers.

The error on the log reports that my Vulkan driver is missing "VK_EXT_robustness2" and looking into the vulkaninfo report ... indeed it's missing that extension.
From a quick research, it seems that the required extensions has been added to Vulkan 1.2.162 and I'm running 1.2.131

So, it seems that something needs to be updated, or the quickstart guide saying that more recent Vulkan is needed ... or the code lowering down the requirements to match Vulkan 1.1 as the guide reports.

[vulkaninfo.txt](https://github.com/yuzu-emu/yuzu/files/5996378/vulkaninfo.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5996379/yuzu_log.txt)

**Comment by ToxaGaming** [comment]
Per the buffer cache rewrite yuzu now requires the extension VK_EXT_Robustness2 which all Graphics vendors include in their latest drivers. It is therefore advised that everyone updates to these.

**Comment by GMaxera** [comment]
> Per the buffer cache rewrite yuzu now requires the extension VK_EXT_Robustness2 which all Graphics vendors include in their latest drivers. It is therefore advised that everyone updates to these.

Unfortunately, it's not my case. 
My latest installable drivers on my laptop are 1.2.131 ... and it's only a 2 years old laptop :-(
So, I'm out

**Comment by GMaxera** [comment]
By the way, I'm not asking to go back to allow me run Yuzu ... but at least the website should reflect that the requirements are (much) higher than what stated :-(

**Comment by goldenx86** [comment]
@GMaxera you don't need to follow the outdated vendor driver.
Download the latest zip version from here: https://downloadcenter.intel.com/download/30148/
Then follow the instructions here: https://www.youtube.com/watch?v=BZG50Nm5sOM&t=72s

Intel no longer blocks generic official drivers if custom ones are installed, it just requires manual intervention once, and then you can update to the latest official ones.

**Comment by FearlessTobi** [comment]
Closing as this issue seems to have been resolved.

**Comment by GMaxera** [comment]
@FearlessTobi The website getting started guide still reports as requirement Vulkan 1.1 instead of the new requirements.

```
GPUs must support OpenGL 4.6 & OpenGL Compatibility profile, or Vulkan 1.1 (or higher).
To find out if your GPU meets these requirements, visit https://opengl.gpuinfo.org or https://vulkan.gpuinfo.org/ and check your GPU details.
```

**Comment by neosarchizo** [comment]
![capture](https://user-images.githubusercontent.com/5792283/110511741-e33cb600-8147-11eb-986c-eea2a764eefc.PNG)

My vulkan version is 1.2.131. But I also got same error, `VK_EXT_robustness2`.
