### ISSUE TITLE
Project TRIANGLE STRATEGY Debut DEMO Graphics issues

### ISSUE THREAD

**Issue by fuhuan416** [yuzu-emu/yuzu#5959]
Whether it is Vulkan or OpenGL, the two games have the same graphics issues, the UI part of the dialog box can be rendered, and the rest is black. The game is developed using the Unreal4 engine.

I paused the yuzu when the screen was black, and got the log file as soon as possible

The picture above is from SWTICH
The picture below is of the yuzu

![triangle1](https://user-images.githubusercontent.com/6281757/108452849-3c7d9c00-72a4-11eb-8c28-b71b07669c14.jpg)
![yuzu 2021-02-19 11-18-21-883](https://user-images.githubusercontent.com/6281757/108452856-3e475f80-72a4-11eb-8088-0d1345b6bbcb.png)
[yuzu_log_EA-1473_Project_TRIANGLE_STRATEGY_Debut_Demo_OpenGL.zip](https://github.com/yuzu-emu/yuzu/files/6007425/yuzu_log_EA-1473_Project_TRIANGLE_STRATEGY_Debut_Demo_OpenGL.zip)
[yuzu_log_EA-1473_Project_TRIANGLE_STRATEGY_Debut_Demo_Vulkan.zip](https://github.com/yuzu-emu/yuzu/files/6007426/yuzu_log_EA-1473_Project_TRIANGLE_STRATEGY_Debut_Demo_Vulkan.zip)

**Comment by gidoly** [comment]
game is not perfectly render yet however mentioned issue is fixed
