### ISSUE TITLE
Integer Overflow Exception in GetFixedPoint64Factor()

### ISSUE THREAD

**Issue by tcaputi** [yuzu-emu/yuzu#5960]
### Generic info
- Git hash: 540014e837782096b7e8ce2990ca896f2603b731 (yuzu-mainline 2/19/21)
- System Specs: Ryzen 3600X, 16GB RAM, RTX 2070S.

I am running this as a KVM virtual machine running on an Ubuntu 20.04 server. The RTX 2070S is passed through with VFIO. My goal is to have a gaming PC running on my personal server when I want it, including yuzu. This is a very fresh install of Windows. The only things installed are yuzu (and the development tools I needed to build it), Steam, WSL, and Discord. Based on the call stack I don't think this is related to the GPU passthrough.

### What happened
I installed yuzu from the website a couple days ago, but had issues with my game dumps. Today, I went to try again so I deleted my keys files. I forgot to put the new ones back before I relaunched the app, but I dont think thats relevant. Anyway, from this point on yuzu would no longer launch. Windows Event viewer said there was an exception so I built it from source and this is the exception that I get:

### Call stack
```
yuzu.exe!Common::GetFixedPoint64Factor(unsigned __int64 numerator, unsigned __int64 divisor) Line 66
    at C:\Development\projects\yuzu-mainline\src\common\uint128.h(66)
yuzu.exe!Common::StandardWallClock::StandardWallClock(unsigned __int64 emulated_cpu_frequency_, unsigned __int64 emulated_clock_frequency_) Line 25
    at C:\Development\projects\yuzu-mainline\src\common\wall_clock.cpp(25)
[External Code]
yuzu.exe!Common::CreateBestMatchingClock(unsigned int emulated_cpu_frequency, unsigned int emulated_clock_frequency) Line 75
    at C:\Development\projects\yuzu-mainline\src\common\wall_clock.cpp(75)
yuzu.exe!Core::Timing::CoreTiming::CoreTiming() Line 41
    at C:\Development\projects\yuzu-mainline\src\core\core_timing.cpp(41)
yuzu.exe!Core::System::Impl::Impl(Core::System & system) Line 133
    at C:\Development\projects\yuzu-mainline\src\core\core.cpp(133)
[External Code]
yuzu.exe!Core::System::System() Line 427
    at C:\Development\projects\yuzu-mainline\src\core\core.cpp(427)
yuzu.exe!`dynamic initializer for 'Core::System::s_instance''() Line 85
    at C:\Development\projects\yuzu-mainline\src\core\core.cpp(85)
[External Code]
```

![image](https://user-images.githubusercontent.com/1920053/108467597-77a3af00-7253-11eb-955f-42bd9ca23f70.png)

I am pretty technical (although my experience is mostly with Linux kernel development) and I am happy to help out in anyway I can. I mostly work from home these days so I'm available a lot to help. I'll watch this issue, but feel free to reach me on discord (Tom3#4584).

**Comment by v1993** [comment]
Do builds before/after merge of #5121 behave differently in any way? There have been recent changes to discussed section of code.

**Comment by adityaruplaha** [comment]
Initial ask: https://discord.com/channels/398318088170242053/400106910231035904/812180486129582172

**Comment by FernandoS27** [comment]
hmn, why is it using the common wall clock instead of the x86-64 wall clock. Also, that intrinsic shouldn't overflow with those parameters.

**Comment by tcaputi** [comment]
@v1993 i can try that as soon as im done with work

**Comment by FernandoS27** [comment]
@tcaputi make sure to check your KVM configuration, you shouldn't be hitting the standard clock on a Ryzen processor. The fact it's hitting it, means that for some reason you are not compiling to X86-64 or cpuid is not being exposed to the guest virtual machine.

**Comment by tcaputi** [comment]
@FernandoS27 cpu-z seems to detect everything correctly...

![image](https://user-images.githubusercontent.com/1920053/108573404-72417580-72e2-11eb-87cb-e56c7e7bfc75.png)

As for compilation, I originally tried it with the official installer from the website, so I don't think thats it. It would be crazy if KVM exposed the cpu as anything other than x86_64. What else would it pick? :P

I think i found the issue.... I will post back here with thee results in a few minutes.

**Comment by tcaputi** [comment]
I figured it out. Thanks for the tip about the kvm clock.

For anyone else looking at this in the future, I needed to adjust the following to my virsh config for the VM:
```
  <cpu mode='host-passthrough' check='none'>
    ...
    <feature policy='require' name='invtsc'/>
  </cpu>
  <clock offset='localtime'>
    ...
    <timer name='kvmclock' present='no'/>
  </clock>
```

**Comment by bunnei** [comment]
Re-opening, as this is still a real bug. Thanks for reporting!

**Comment by tcaputi** [comment]
Ok. Let me know if you need me to test anything.
