### ISSUE TITLE
No simplified chinese support for some games

### ISSUE THREAD

**Issue by Amondo124** [yuzu-emu/yuzu#5966]
I dumped and installed the font for FontChineseSimplified.ttf in user/sysdata. However, the following games are not working properly in yuzu 545.
- Pokémon Sword shows ???? instead of characters.
- The Legend of Zelda: Link's Awakening shows no text at all.

**Comment by goldenx86** [comment]
Dump the system firmware to get correct font rendering: https://yuzu-emu.org/help/quickstart/#dumping-system-update-firmware

**Comment by Amondo124** [comment]
Thanks for your incredibly fast reply. It works fine now.
