### ISSUE TITLE
An error occurred initializing the video core

### ISSUE THREAD

**Issue by DJZarking** [yuzu-emu/yuzu#5967]
running ACNH in vulkan

error happened after update 
log:
[  40.171847] Core <Critical> core\core.cpp:Load:229: Failed to initialize system (Error 5)!

specs:
CPU AMD R5 2400g
GPU Radeon RX 580
RAM 16GB

(gpu driver is updated already)

**Comment by G-Spawn** [comment]
try using latest optional amd drivers not the latest recommended

**Comment by goldenx86** [comment]
Install the latest Optional driver to get support for the required VK_EXT_robustness2 extension. Get 20.12.1 or newer (current latest is 21.2.2).

**Comment by DJZarking** [comment]
much thanks @G-Spawn @goldenx86  
error fixed
