### ISSUE TITLE
LM3 Save picture broken

### ISSUE THREAD

**Issue by MiloseviciVucic** [yuzu-emu/yuzu#5970]
![1](https://user-images.githubusercontent.com/79383701/108610777-aac37b00-73d8-11eb-83e4-1a28ba1cbfd0.png)

I deleted save pictures and change it with good ones, now it works, but I disabled assembly shaders, otherwise issue will happen again.

**Comment by MiloseviciVucic** [comment]
Asy. shaders are on in order do prevent issue.

**Comment by MiloseviciVucic** [comment]
Also I am using OpenGL.

**Comment by gidoly** [comment]
fixed with reactive flushing on
