### ISSUE TITLE
Fire Emblem Warriors Freezing

### ISSUE THREAD

**Issue by fuhuan416** [yuzu-emu/yuzu#5972]
It got stuck a few seconds after the game started, here's log file:
After the game started, it got stuck for a few seconds, and the log indicated that some functions were not implemented

>[ 223.750490] HW.GPU <Warning> video_core\shader\shader_ir.cpp:SetInternalFlagsFromInteger:393: Condition codes implementation is incomplete
[ 223.750500] Debug <Critical> video_core\shader\decode\arithmetic_integer.cpp:DecodeArithmeticInteger:133: Assertion Failed! Condition codes generation in ISCADD is not implemented
[ 223.750502] HW.GPU <Warning> video_core\shader\shader_ir.cpp:SetInternalFlagsFromInteger:393: Condition codes implementation is incomplete
[ 223.750510] Debug <Critical> video_core\shader\decode\arithmetic_integer.cpp:DecodeArithmeticInteger:133: Assertion Failed! Condition codes generation in ISCADD is not implemented
[ 223.750513] HW.GPU <Warning> video_core\shader\shader_ir.cpp:SetInternalFlagsFromInteger:393: Condition codes implementation is incomplete
[ 223.750529] Debug <Critical> video_core\shader\decode\arithmetic_integer.cpp:DecodeArithmeticInteger:133: Assertion Failed! Condition codes generation in ISCADD is not implemented

[yuzu_log_EA-1478_Fire_Emblem_Warriors_OpenGL.zip](https://github.com/yuzu-emu/yuzu/files/6017182/yuzu_log_EA-1478_Fire_Emblem_Warriors_OpenGL.zip)
[yuzu_log_EA-1478_Fire_Emblem_Warriors_Vulkan.zip](https://github.com/yuzu-emu/yuzu/files/6017183/yuzu_log_EA-1478_Fire_Emblem_Warriors_Vulkan.zip)

**Comment by ghalib5000** [comment]
any update on this?

**Comment by Enoss99** [comment]
Yup, any update on the issue ?

**Comment by Maximilian-Reuter** [comment]
Just tried to run the game and it worked perfectly up to the point of the end of the intor video. When starting to fight it just stops outputting andy frames until it dies a short while after.

[yuzu_log_1000_VK.zip](https://github.com/yuzu-emu/yuzu/files/8594503/yuzu_log_1000_VK.zip)

both in Vulkan and in OpenGL

**Comment by SeongGino** [comment]
For the record, still happening; game and emu hangs a few moments after the start of a battle. But it seems the rest of the game looks accurate otherwise.

Linux/NVIDIA, using Vulkan.

**Comment by BKasin** [comment]
Still crashing with Yuzu 2850 on Windows/NVIDIA using OpenGL. Occurs as soon as combat starts. Sometimes music and voices continue after the visual crash.

**Comment by Maximilian-Reuter** [comment]
just for reference, with the current Ryujinx 1.1.171 it does run at least albeit with frame hangs every few seconds. But it doesnt crash or stop outputting frames.

**Comment by BKasin** [comment]
Some update: Yuzu 2830 and 2833 seem to have fixed Warriors: Three Hopes, but Warriors fails at the same point.

**Comment by gidoly** [comment]
game should be playable on lastest mainline now

**Comment by My1** [comment]
Doesn't seem the case for me at the very least
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10776677/yuzu_log.txt)
