### ISSUE TITLE
[RFC/UX] Disable Unfuse FMA by default on hardware supporting FMA in Unsafe CPU Accuracy mode.

### ISSUE THREAD

**Issue by adityaruplaha** [yuzu-emu/yuzu#5974]
This is a UX improvement suggestion of Unsafe CPU Accuracy mode.

Currently Unfuse FMA is enabled by default even on hardware supporting FMA, causing issues like that with hitboxes in Smash.

Unfuse FMA should be locked to ON if your CPU doesn't support FMA, and should default to OFF (but not locked, for debug purposes) if FMA is supported.

**Comment by Morph1984** [comment]
Addressed in #6573

**Comment by v1993** [comment]
Additionally, FWIW - Unfuse FMA is a no-op on processors that support FMA.

**Comment by adityaruplaha** [comment]
> Additionally, FWIW - Unfuse FMA is a no-op on processors that support FMA.

Yeah, it should be, don't remember why I made this issue, probably some support request on Discord. Anyway, don't bother about this.
