### ISSUE TITLE
xenoblade 2 explosion effect broken

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#5976]
<img width="1174" alt="20210221_175928" src="https://user-images.githubusercontent.com/66776795/108620326-e4df5c00-746e-11eb-8c82-d4ee12037d9b.png">
<img width="1174" alt="20210221_175912" src="https://user-images.githubusercontent.com/66776795/108620328-e6108900-746e-11eb-810d-7dba8330b718.png">
on some cutscene this game have proken effect like this

it is how it looks like on switch
<img width="215" alt="20210221_180437" src="https://user-images.githubusercontent.com/66776795/108620409-5c14f000-746f-11eb-8556-6941ca90a7a1.png">
<img width="705" alt="20210221_180452" src="https://user-images.githubusercontent.com/66776795/108620413-5ddeb380-746f-11eb-9656-dda13d158d62.png">

it is reproducable on "Crossroads of Destiny" cutscene

log:

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/6017439/yuzu_log.zip)

**Comment by Morph1984** [comment]
Fixed by #6597
