### ISSUE TITLE
Slow perfomance yuzu ea 1480

### ISSUE THREAD

**Issue by blaz1e** [yuzu-emu/yuzu#5979]
Well, i used to play Pokemon Shield on yuzu, but i formatted the pc today, since then, my fps went to 30 stable before i formatted to 20 - 23 now, i really dont know what to do, and whats the problem. I did the same configuration that I had done before too.

PC Specs: i3 9100f
16GB RAM
RX 570 4GB
![Captura de tela 2021-02-21 145925](https://user-images.githubusercontent.com/79417229/108634027-5828a400-7456-11eb-9794-8be9db3defa0.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6018222/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
Please leave a log and information on this problem. This issue will be closed if more is not provided

**Comment by BSoDGamingYT** [comment]
> Well, i used to play Pokemon Shield on yuzu, but i formatted the pc today, since then, my fps went to 30 stable before i formatted to 20 - 23 now, i really dont know what to do, and whats the problem. I did the same configuration that I had done before too.
> 
> PC Specs: i3 9100f
> 16GB RAM
> RX 570 4GB
> ![Captura de tela 2021-02-21 145925](https://user-images.githubusercontent.com/79417229/108634027-5828a400-7456-11eb-9794-8be9db3defa0.png)
> 
> [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6018222/yuzu_log.txt)

Please enable high GPU accuracy

**Comment by blaz1e** [comment]
> > Well, i used to play Pokemon Shield on yuzu, but i formatted the pc today, since then, my fps went to 30 stable before i formatted to 20 - 23 now, i really dont know what to do, and whats the problem. I did the same configuration that I had done before too.
> > PC Specs: i3 9100f
> > 16GB RAM
> > RX 570 4GB
> > ![Captura de tela 2021-02-21 145925](https://user-images.githubusercontent.com/79417229/108634027-5828a400-7456-11eb-9794-8be9db3defa0.png)
> > [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6018222/yuzu_log.txt)
> 
> Please enable high GPU accuracy
 It worked, thank u a lot
