### ISSUE TITLE
Super mario 3d world crashes with Vulkan API on world 1-5

### ISSUE THREAD

**Issue by mrshroomy** [yuzu-emu/yuzu#5982]
Version: Yuzu EA 1481
Reproduce: 
1. Use vulkan api
2. Go into super mario 3d world and into level 1-5
3. Yuzu and game freezes

Graphics API
Vulkan 1.2.145

Graphics Renderer
AMD RADV RX 580 (ACO)

GPU Driver Version
radv 20.3.4

**Comment by BSoDGamingYT** [comment]
Please post a log as per the instructions on issue formats

**Comment by adamantike** [comment]
In case it's relevant, the Cemu emulator has had issues with level 1-5 for the Wii U version of the game too.

* Reported issue in Super Mario 3D World [wiki entry](https://wiki.cemu.info/wiki/Super_Mario_3D_World) (`Previously known issues for older cemu builds` section)

> **Level 1-5 is slow/crashes**
> This is because Super Mario 3D World creates many dynamic textures in this level.
> This also leads to visual bugs.
> Larger GPU Memory and/or Bandwidth is required to reduce/eliminate its impact.
> Dual Channel memory might help.
> More powerful GPU may be required.

* [1.22.8 changelog](https://cemu.info/changelog/cemu_1_22_8.txt)

> **HLE: Prevent dynamic resolution scaling in Super Mario 3D World**
>     This fixes a long standing issue where mirror effects in Level 1-5 would cause the texture cache to be flooded, leading to stutter and sometimes even crashes if not enough VRAM is available

**Comment by FanderWasTaken** [comment]
> Please post a log and a game save for the area, as per the instructions on issue formats

Save: [save.zip](https://github.com/yuzu-emu/yuzu/files/6410118/save.zip)
Log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6410119/yuzu_log.txt)

Same issue here. I have RX 570 with dirvers 21.4.1. Using Vulkan.

**Comment by FanderWasTaken** [comment]
Also this level breaks in the same way: 

![20210502184501_1](https://user-images.githubusercontent.com/48799496/116817431-57f40580-ab77-11eb-80b1-ad1b6038962c.jpg)

Save: [save.zip](https://github.com/yuzu-emu/yuzu/files/6411612/save.zip)
Log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6411613/yuzu_log.txt)

**Comment by ameerj** [comment]
Fixed by #6635
