### ISSUE TITLE
Super Mario 3D Worlds + Bowser's Fury can't run with Vulkan Graphics

### ISSUE THREAD

**Issue by jlarmijos** [yuzu-emu/yuzu#5983]
Please help me if possible.
I have a PC with a core i3 processor with integrated Intel UHD 630 graphics and when configuring the game with Vulkan graphics I get the message "Yuzu has encountered an error when executing the video core". I have the system and the graphics driver updated. Is there any solution? Thank you for your time.

**Comment by goldenx86** [comment]
Run the latest GPU driver, VK_EXT_robustness2 is now mandatory, and it's pretty recent.

**Comment by jlarmijos** [comment]
> Run the latest GPU driver, VK_EXT_robustness2 is now mandatory, and it's pretty recent.

Install the system again, check for updated drivers and nothing.

**Comment by ashen00** [comment]
https://downloadcenter.intel.com/product/80939/Graphics
