### ISSUE TITLE
Super Mario Odyssey Purple water explosion caused stutter for opengl

### ISSUE THREAD

**Issue by lgczszs** [yuzu-emu/yuzu#5992]
ubuntu 20.04
gpu rx580
cpu r5 3600
ram 16gb
mesa latest

![0100000000010000_2021-02-24_16-23-22-534](https://user-images.githubusercontent.com/23278901/108969553-b48cfd00-76bc-11eb-9cec-94347fc37ce8.png)
Pixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
libpng warning: iCCP: known incorrect sRGB profile
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
Mesa: User error: GL_INVALID_OPERATION in glCompressedTextureSubImage3D(invalid texture level 9)
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6034447/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
Stutter is a totally normal occurrence when shaders are being compiled.
The best you can do to combat this is to either use Vulkan or at least GLasm.

**Comment by lgczszs** [comment]
My native language is not English, so I may not express it well
This is not a cache problem. I have already loaded the cache. When the water explodes, the stuttering here is only 5 frames. If the water does not explode, there are 60 frames. This is continuous.

**Comment by lgczszs** [comment]
My native language is not English, so I may not express it well
This is not a cache problem. I have already loaded the cache. When the water explodes, the stuttering here is only 5 frames. If the water does not explode, there are 60 frames. This is continuous.
