### ISSUE TITLE
Memory leaks found in Yuzu for Pokemon SH/SW (potentially more games affected)

### ISSUE THREAD

**Issue by janphi001** [yuzu-emu/yuzu#5995]
Here's what FrostyNips, BSoD, I'mOZtistic and me  janphi001 found on Discord.
We found a small leak in version 458. Then after we hit version 520 the leakage is getting worse every version.

**Comment by janphi001** [comment]
Okay found another in Yuzu 421 VERY small found by @Law on Discord

**Comment by OZtistic** [comment]
It is also worthy to mention all testers are on NVidia GPU's of varying models - Pascal, Turing and Ampere 
(no AMD testers were available or stepped forward at the time of testing)
Another note worth mentioning is, the leak seems to be worse between Mainline 520 and 540
456 does not have this issue, while 458 does
latest mainline seems to be leaking at a rough rate of ~5MB every second or so and steadily climbs until completely consuming available RAM and crashing yuzu
current EA is also affected
I don't think logs will shine any light on this, it is easily reproducible
I will add any more details to my comment if I think of anything I neglected to include

**Comment by RinMaru** [comment]
I have AMD but no Pokemon. If any other games are affected I'll try them for y'all if I have them

**Comment by Uranite** [comment]
i can confirm memory leak with docked with 456 but its as small as 0.1-1MB/s

**Comment by hemnesen** [comment]
can confirm. happening on 543 on both shield and sword.

**Comment by Itamai** [comment]
amd rx 580 user here.
tested on latest mainline version 549 with the latest amd optional drivers on vulkan api.
can confirm  the memory leak its about 70KB/s increase for me in pokemon sword standing still in front of the mother's house

**Comment by OZtistic** [comment]
> 
> 
> amd rx 580 user here.
> tested on latest mainline version 549 with the latest amd optional drivers on vulkan api.
> can confirm the memory leak is about 70KB/s, in working set, increase for me in pokemon sword standing still in front of the mother's house. The commit increase is way more than working set that increases 5000KB/s

on Vulkan? (I assume so, would just help to clarify)

**Comment by Itamai** [comment]
> > amd rx 580 user here.
> > tested on latest mainline version 549 with the latest amd optional drivers on vulkan api.
> > can confirm the memory leak is about 70KB/s, in working set, increase for me in pokemon sword standing still in front of the mother's house. The commit increase is way more than working set that increases 5000KB/s
> 
> on Vulkan? (I assume so, would just help to clarify)
quote from my post:
> tested on latest mainline version 549 with the latest amd optional drivers on vulkan api.

**Comment by SnowKai1** [comment]
I use a GTX1660S and splatoon 2 consumes all my ram (16GB) in the 549
![image](https://user-images.githubusercontent.com/79730809/109370862-b810b780-7867-11eb-855d-92551e211c1c.png)

**Comment by german77** [comment]
First leak is on mainline 522 from 58MB/min to 158MB/min. Second leak is on mainline 539 with 305MB/min
