### ISSUE TITLE
Bravely Default 2 does not render

### ISSUE THREAD

**Issue by HarlockSama** [yuzu-emu/yuzu#6001]
Hello !

Maybe it is a little early, but Bravely Default 2 can't render 3D models and environments on Yuzu. The menus and title work perfectly, apparently it is only when coming in game that the problem happens. We can only see dialogs and overlay on a black screen.

Thanks for your help \o/

**Comment by G-Spawn** [comment]
Do try to provide a log like the create new issue asks.

**Comment by Antorell** [comment]
Here two logs for Bravely Default II.
one run with Vulkan and another run with OpenGL
[OpenGL_yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/6051308/OpenGL_yuzu_log.zip)
[VULKAN_yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/6051309/VULKAN_yuzu_log.zip)

**Comment by Noreille** [comment]
Yep same problèm here ..

**Comment by doxidox** [comment]
Hi, same, any solution?

**Comment by Temperhoof** [comment]
I just wanted to add toggling on **Use Assembly Shaders (Experimental, Nvidia OpenGL only)**, does produce render artifacts. All are black of course, but I loaded a save where there was moving textures -- like water falls -- and it could get a very faint indication of the water falls present as those were the source of the random, rapid jittering.
