### ISSUE TITLE
Pokemon Sword crash on Vulkan

### ISSUE THREAD

**Issue by TheAllMaker** [yuzu-emu/yuzu#6003]
Hey, my game Pokemon Sword crashes often and this is my log.
My Yuzu Version: 1480
Everything was smooth until a start with a pokemon startet and then it suddenly freezed and crashed

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6053363/yuzu_log.txt.old.txt)

**Comment by TomatDividedBy0** [comment]
Try switching to OpenGL, from my experience Vulkan support is pretty bad with the game

**Comment by OZtistic** [comment]
There is currently a memory leak in both Sword and Shield which is being internally investigated

**Comment by TheAllMaker** [comment]
I have an AMD Graphics card thats why I use AMD.
Ok I will try to use the version 456 thank you :)

**Comment by Svarr** [comment]
Question: could this memory leak be related to the freeze when the game saves before going into the dynamax adventure?

It's consistent at this exact situation, independendly of the chosen renderer. Though the music keeps on playing, the status bar shows 0 fps and inputs don't seem to do anything.

**Comment by gidoly** [comment]
this is ditto of multicore issue issue. closes due to dup
