### ISSUE TITLE
Emulator stuck on launching

### ISSUE THREAD

**Issue by Joselu25** [yuzu-emu/yuzu#6005]
Yesterday i was playing PLG and everything was perfect, but today i tried to enable assembly shaders to test its performance and then it crashed. Now every game gets stuck on launching screen and nothing happens
I add my log file 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6054885/yuzu_log.txt)

**Comment by OZtistic** [comment]
Cannot progress past the Controller selection screen for PokeMon Let's GO! Pikachu
even though my controller is set correctly, and is interpreted in the Controller Manager in yuzu just fine
tried on Docked and Undocked, latest EA
