### ISSUE TITLE
<vulkan_device: Require VK_EXT_robustness2> broke Vulkan Mode of (AMD GPU)

### ISSUE THREAD

**Issue by okt04175** [yuzu-emu/yuzu#6009]
After this change <757fd1e vulkan_device: Require VK_EXT_robustness2>, Any game running in Vulkan mode on AMD GPU will crash immediately.
https://github.com/yuzu-emu/yuzu-mainline/commit/757fd1e91716d6734a564cd5bfdd47e362afd2ac

CPU: Intel i7-4790K
RAM: 1600MHz 32GB
GPU: AMD RX Vega56
GPU Driver: 21.2.3
Vulkan API : 1.2.162
Yuzu : Mainline 537

**Comment by BSoDGamingYT** [comment]
Update your GPU drivers to the latest optional

**Comment by jochuan** [comment]
21.2.3 is already the latest optional version

**Comment by OZtistic** [comment]
@jochuan _provide a log of your crash_

**Comment by jochuan** [comment]
> @jochuan _provide a log of your crash_

I don't have this crash...

**Comment by RinMaru** [comment]
> > @jochuan _provide a log of your crash_
> 
> I don't have this crash...

I dont either. RX 480 Here

**Comment by Mantis-89** [comment]
I have the same problem:
CPU: AMD FX-8320E 
RAM: 32 GB
GPU RX 580 8GB
GPU Driver: 21.3.1
Vulkan API : 1.2.170
Yuzu : Mainline 577
OS: Windows 7 SP 1 

Log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6231497/yuzu_log.txt)

**Comment by Mantis-89** [comment]
The problem also occurs with drivers 21.3.2

**Comment by Mantis-89** [comment]
> @jochuan _provide a log of your crash_

Hi, I've tried to reinstall the graphics driver but yuzu keeps crashing launching the game. I have attached the log in the previous messages, this is GPU-Z. Any suggest? Thank you
![GPU-Z(0)](https://user-images.githubusercontent.com/81647255/115151459-3b32da80-a06d-11eb-8dc9-7ee3e3592138.gif) ![GPU-Z(1)](https://user-images.githubusercontent.com/81647255/115151410-04f55b00-a06d-11eb-8f01-cf07b54ce898.gif) ![GPU-Z(2)](https://user-images.githubusercontent.com/81647255/115151409-045cc480-a06d-11eb-97b4-55b6d1a39021.gif)

**Comment by benderscruffy** [comment]
same problem here
i have Radeon RX 580 and drivers 21.4.1 and crashes out straight away using Vulkan

**Comment by Mantis-89** [comment]
@benderscruffy OS? Windows 7? 
I suspect the problem is the drivers for Windows 7..

**Comment by benderscruffy** [comment]
@Mantis-89 
yep Windows 7

**Comment by Mantis-89** [comment]
@benderscruffy @okt04175 @BSoDGamingYT 
I did a fresh install of Windows 10, Yuzu is back to working with my hardware configuration, and GPU-Z correctly shows VK_EXT_robustness2 support.
So the problem is the missing functionality from the AMD driver with Windows 7. Having AMD discontinued support for Windows 7, they will never fix the problem.
I think the requirements need to be changed, indicating that Yuzu cannot use Vulkan in Windows 7 with AMD GPUs.

**Comment by benderscruffy** [comment]
yes it is a windows 7 problem
i have upgraded to windows 10 and the problem has gone
