### ISSUE TITLE
Unmapped Read/Write and memory leak in the Legend of Zelda Breath of the Wild

### ISSUE THREAD

**Issue by Vorlon0815** [yuzu-emu/yuzu#6010]
Got the following error 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6057796/yuzu_log.txt)

[   5.725285] Debug <Critical> video_core\shader\decode\memory.cpp:TrackGlobalMemory:477: Assertion Failed! Global memory tracking failed
...
[  82.045079] HW.Memory <Error> core\memory.cpp:Read:604: Unmapped Read8 @ 0x37027EDDA5
[  82.045084] HW.Memory <Error> core\memory.cpp:Read:604: Unmapped Read8 @ 0x37027EDDA6
[  82.045085] HW.Memory <Error> core\memory.cpp:Read:604: Unmapped Read8 @ 0x37027EDDA7
[  82.045086] HW.Memory <Error> core\memory.cpp:Read:604: Unmapped Read8 @ 0x37027EDDA8
[  82.045088] HW.Memory <Error> core\memory.cpp:Write:642: Unmapped Write8 0x00000000 @ 0x00000037027EDDA5
[  82.045089] HW.Memory <Error> core\memory.cpp:Write:642: Unmapped Write8 0x00000000 @ 0x00000037027EDDA6
[  82.045090] HW.Memory <Error> core\memory.cpp:Write:642: Unmapped Write8 0x00000000 @ 0x00000037027EDDA7
[  82.045092] HW.Memory <Error> core\memory.cpp:Write:642: Unmapped Write8 0x00000000 @ 0x00000037027EDDA8

**Comment by BSoDGamingYT** [comment]
Please be more specific in issues. Game, emulator version and hardware used

**Comment by Vorlon0815** [comment]
Game: Zelda BOTW
Version: Mainline 550
Hardware: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz, GeForce GTX 760/PCIe/SSE2, Windows 10

thx

**Comment by G-Spawn** [comment]
This type of error can happen with corrupted files (save / update-dlc) It wouldn't hurt to try redumping it to rule out oddity.

**Comment by gidoly** [comment]
can you test issue again, if there is no response i wanna close this as it doesn't reported to happens to other and teams hardware
