### ISSUE TITLE
Yo kai Watch 4 Driver Timeout (AMD)

### ISSUE THREAD

**Issue by einekratzekatze** [yuzu-emu/yuzu#6011]
I tryed to play Yo Kai Watch 4 on yuzu. When I press a on the title screen i get a Error Window from AMD that tells me a Driver Timeout happend.
The Game stays white and when i stop or reload the game Yuzu doesn't react
I use the latest Yuzu version which is out a the time this issue got submited
My Log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6058131/yuzu_log.txt)
What I installed
![image](https://user-images.githubusercontent.com/48450457/109435568-5f821b80-7a1b-11eb-8d5a-60a45e94e736.png)
Title Screen
![image](https://user-images.githubusercontent.com/48450457/109435647-abcd5b80-7a1b-11eb-9e6e-a7c0fea26d96.png)
Error Window (German)
![image](https://user-images.githubusercontent.com/48450457/109435664-c30c4900-7a1b-11eb-84a0-f92627ce70b3.png)

**Comment by FearlessTobi** [comment]
Possibly related to https://github.com/yuzu-emu/yuzu/issues/5947?
