### ISSUE TITLE
Switch to QT6?

### ISSUE THREAD

**Issue by iMonZ** [yuzu-emu/yuzu#6012]
So is it possible to switch with yuzu to QT6?

**Comment by german77** [comment]
There is no need to migrate to Qt6 at the moment since it will not bring any real benefit. It's planned to switch at some point to Qt5

**Comment by iMonZ** [comment]
> There is no need to migrate to Qt6 at the moment since it will not bring any real benefit. It's planned to switch at some point to Qt5

It has a better benefit. Arm64 support which was best Introduced with Qt6
Also, the UI is using Vulkan instead of OpenGL.
So yeah it will definitely has some benefits efficiency and performance
