### ISSUE TITLE
Controller undetected DS4windows

### ISSUE THREAD

**Issue by Wakoles** [yuzu-emu/yuzu#6017]
Hello, 
I try to play with my PS4 controller but Yuzu don't detect this. In Cemu, for WII u emulator, that work fine. It's only Yuzu, he don't wan't work. 

Thanks

![image](https://user-images.githubusercontent.com/31617631/109476175-e1536280-7a76-11eb-99ab-28b2c996abf8.png)

**Comment by Vorlon0815** [comment]
works fine for me... but only with cable..
seems there is a problem with bluetooth connection in ds4windows
try cable and / or update ds4windows

**Comment by v1993** [comment]
You have opened motion configuration and added motion source there, right?

**Comment by Wakoles** [comment]
> works fine for me... but only with cable..
> seems there is a problem with bluetooth connection in ds4windows
> try cable and / or update ds4windows

Doesn't work with me..

**Comment by Wakoles** [comment]
> You have opened motion configuration and added motion source there, right?

Yes, the motion is detected, but not the controller in options

**Comment by v1993** [comment]
Have you tested it with other emulators, e.g. Dolphin? It doesn't seem to be a yuzu issue to me, because this exact setup it known to work well. Maybe try one of different motion servers available, e.g. ones for phones, to see if you can use them from yuzu.

P.S.: avoid installing games to NAND. It's known to cause issues for now.

**Comment by Wakoles** [comment]
> Have you tested it with other emulators, e.g. Dolphin? It doesn't seem to be a yuzu issue to me, because this exact setup it known to work well. Maybe try one of different motion servers available, e.g. ones for phones, to see if you can use them from yuzu.
> 
> P.S.: avoid installing games to NAND. It's known to cause issues for now.

On Dolphin and Cemu it works fine. I will try with a Xbox controlller.

**Comment by Wakoles** [comment]
I start a game, and the controller spawned lmao. Thanks ^^

**Comment by soredake** [comment]
That's still a problem, yuzu still don't see ds4 controller.
