### ISSUE TITLE
Mouse input not detected anymore

### ISSUE THREAD

**Issue by giacam59** [yuzu-emu/yuzu#6018]
Hello. After updating yuzu to version 551, the mouse just disappears in-game letting me only use the controller, and all the games in my library meet the same issue. The fact is that I also updated Windows and some of my drivers before doing so on yuzu, so, for a better understanding purpose, I tried running my games on Ryujinx and none of this happens.

**Comment by BSoDGamingYT** [comment]
Can you please be a bit more descriptive as to what this issue is. Are you using mouse and keyboard? are you using a controller?

Issue format also requires a log to be posted after reproducing said issue

**Comment by german77** [comment]
You might enabled the mouse panning feature accidentally. Press F9 to make your mouse visible again

**Comment by giacam59** [comment]
@german77 Thank you, I solved the issue, even though I don't remember enabling anything accidentally.
