### ISSUE TITLE
problems with Bowser´s Fury on Intel UHD 630

### ISSUE THREAD

**Issue by jlarmijos** [yuzu-emu/yuzu#6025]
Hello, I have had problems with the game Bowser´s Fury. In some parts it just stops working. I have been checking the official Yuzu website for the hardware requirements and found that Intel UHD 630 graphics are recommended. I have updated graphics drivers, and a 4.09 Ghz processor. of 4 cores and 8 threads. Could anyone help Intel users who use these specs? I thank you for your time.

![Inkedvsdf_LI](https://user-images.githubusercontent.com/79478556/109682812-c2270480-7b4c-11eb-9e6a-0995214d2295.jpg)

**Comment by v1993** [comment]
Please provide a log file. Also, explain in details if it crashes or hangs, it isn't entirely clear from your report.

**Comment by jlarmijos** [comment]
> Please provide a log file. Also, explain in details if it crashes or hangs, it isn't entirely clear from your report.

Hello, thanks for answering. I am attaching the log file with the errors. On the other hand, the emulator allows me to get to where it can be seen in the image, then it simply freezes. After a few seconds sound is heard again but the image remains frozen. Thanks again.
![freezed](https://user-images.githubusercontent.com/79478556/109692709-d40da500-7b56-11eb-986b-ad6ff7805cda.jpg)

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/6070751/yuzu_log.zip)


> Hello, I have had problems with the game Bowser´s Fury. In some parts it just stops working. I have been checking the official Yuzu website for the hardware requirements and found that Intel UHD 630 graphics are recommended. I have updated graphics drivers, and a 4.09 Ghz processor. of 4 cores and 8 threads. Could anyone help Intel users who use these specs? I thank you for your time.
> 
> ![Inkedvsdf_LI](https://user-images.githubusercontent.com/79478556/109682812-c2270480-7b4c-11eb-9e6a-0995214d2295.jpg)
