### ISSUE TITLE
Run Yuzu on MacBook Pro 16-inch AMD Radeon (supports Vulkan)

### ISSUE THREAD

**Issue by KohlerVG** [yuzu-emu/yuzu#6026]
Hey Yuzu Team!

I'm a huge fan of yuzu and want to get it working on MacOS, I see that macOS isn't supported anymore because of OpenGL Deprecation, but macOS still supports Vulkan, is there any way to make yuzu run on macOS using the Vulkan API?

Thanks for any help!
Kohler

**Comment by v1993** [comment]
MacOS does not support Vulkan, it only supports Metal. MoltenVK exists, but it is not enough for yuzu's needs.

Also, this would be more appropriate for yuzu's discord server, since it is a question, not a bug.

**Comment by goldenx86** [comment]
The current options are Windows via BootCamp, running the latest drivers from here: https://www.bootcampdrivers.com/
Or a Linux distribution.
