### ISSUE TITLE
MacBook Pro 16-inch OpenGL issue

### ISSUE THREAD

**Issue by KohlerVG** [yuzu-emu/yuzu#6033]
Hi,
I recently partitioned my mac to get windows 10 using bootcamp so that I can run yuzu, but when I try to use OpenGL it is super slow (around 10-15fps)?
I have a really fast GPU and 8core CPU, what am I missing and how can I improve my OpenGL performance? I have the latest boot camp AMD Radeon Adrenaline driver installed as well.

Here are my computer specs:
MacBook Pro: (16-inch, 2019)
Processor: 2.4 GHz 8-Core Intel Core i9
Memory: 64 GB 2667 MHz DDR4
Graphics: AMD Radeon Pro 5500M 8 GB

Any help is appreciated!
Thanks

**Comment by v1993** [comment]
It is expected that you'll get low performance on OpenGL with AMD video card. Use Vulkan instead.

Also, yuzu's discord is better suited for questions. This is a bug tracker, not a Q&A site or forum.

**Comment by iMonZ** [comment]
> Hi,
> I recently partitioned my mac to get windows 10 using bootcamp so that I can run yuzu, but when I try to use OpenGL it is super slow (around 10-15fps)?
> I have a really fast GPU and 8core CPU, what am I missing and how can I improve my OpenGL performance? I have the latest boot camp AMD Radeon Adrenaline driver installed as well.
> 
> Here are my computer specs:
> MacBook Pro: (16-inch, 2019)
> Processor: 2.4 GHz 8-Core Intel Core i9
> Memory: 64 GB 2667 MHz DDR4
> Graphics: AMD Radeon Pro 5500M 8 GB
> 
> Any help is appreciated!
> Thanks

I can recommend you more booting Ubuntu Desktop on your Mac PC instead of Windows 10.
(The only tricky part was to get Wi-Fi working, but it's really easy at the end)

**Comment by KohlerVG** [comment]
How would I do that with my Mac is there is no bootcamp assistant for Ubuntu on macOS internal, do I need to re-partition my macOS hard drive to a certain format? I don’t have any external device to use as a hard drive for Ubuntu.
Thanks for any help on this subject!
Kohler

**Comment by iMonZ** [comment]
> How would I do that with my Mac is there is no bootcamp assistant for Ubuntu on macOS internal, do I need to re-partition my macOS hard drive to a certain format? I don’t have any external device to use as a hard drive for Ubuntu. Thanks for any help on this subject! Kohler
> […](#)

Well thats pretty easy you prepartition your drive to whatever and after that you can reformat that drive to brtfs and install linux on that.

**Comment by KohlerVG** [comment]
Could you show me the steps? I don’t want to mess up my Mac system files

**Comment by KohlerVG** [comment]
I would use a VM (Virtual Machine), but it only supports up to OpenGL 3.3, which will not work with yuzu because it’s needs OpenGL 4.6

**Comment by iMonZ** [comment]
> Could you show me the steps? I don’t want to mess up my Mac system files
> […](#)

At first which model do you have? 
You can find it: 
/AboutThisMac/ Below the macOS version

**Comment by iMonZ** [comment]
> I would use a VM (Virtual Machine), but it only supports up to OpenGL 3.3, which will not work with yuzu because it’s needs OpenGL 4.6
> […](#)

Well for Yuzu and modern gaming please forget these two things:
Virtual Machines and OpenGL

**Comment by KohlerVG** [comment]
My model is:
MacBook Pro: (16-inch, 2019).
Processer: 2.4 GHz 8-core Intel Core i9.
Memory: 64 GB 2667 MHz DDR4
Graphics: AMD Radeon Pro 5500M 8 GB.

**Comment by iMonZ** [comment]
> My model is: MacBook Pro: (16-inch, 2019). Processer: 2.4 GHz 8-core Intel Core i9. Memory: 64 GB 2667 MHz DDR4 Graphics: AMD Radeon Pro 5500M 8 GB.
> […](#)

oh dawn you can only dual boot the Ubuntu System with an external drive on your MacBook (for now)
So for Ubuntu the only way is an external drive.
And for performance wise I can recommend you Linux much more than windows

**Comment by KohlerVG** [comment]
Thanks for the info, I see that you don’t need an external drive because I can partition my Macintosh HD and make a drive for booting like Windows,
If I am wrong please correct me

**Comment by iMonZ** [comment]
Hey please open the GitHub website I have edited a few comments.

**Comment by KohlerVG** [comment]
Got it, thanks.

Ok, so I do have a 8gb USB thumb drive to run Ubuntu on, would that work?

**Comment by v1993** [comment]
I strongly recommend moving to Yuzu discord. This it an issue tracker, not a chat.

**Comment by FearlessTobi** [comment]
Closing as low performance is to be expected on such a configuration.
Also as it has been mentioned, the conversation is better suited for our Discord.
