### ISSUE TITLE
[Vulkan Issue] Screen goes black kindof

### ISSUE THREAD

**Issue by ItsMeSleepy** [yuzu-emu/yuzu#6035]
http://prntscr.com/10dfsn1
**specs:
Geforce GTX 1050 2gb
Intel(R) Core i5 9400F
16GB DDR4 2400mhz**
https://cdn.discordapp.com/attachments/522217638143852552/817260012606062612/log.7z
_this has happened a total of 3 times to me and whenever it does it gives me a partially or fully black screen and it only has happened so far when bowser is out in bowser's fury.
Here is a separate occasion where I started recording myself trying to figure out what happened without a debug tool because I had turned it off. I also didn't include the full video because I was too lazy to edit it down._ https://gyazo.com/76cd3a34d59a9fdab00b35bb919e31a5
_the only thing I found out of the ordinary in the logs was this:_
### HW.GPU <Warning> video_core\shader\shader_ir.cpp:SetInternalFlagsFromInteger:393: Condition codes implementation is incomplete
_it seems to be a Vulkan issue after discussing it with some discord members correct me if they were wrong
if you want to contact me for more information or to correct something in my ticket please friend me on discord: Sleepy#1014
**Thanks and bye!**_

**Comment by G-Spawn** [comment]
When you're able to can you please try this on latest yuzu? If it doesn't happen anymore you can close issue.

**Comment by gidoly** [comment]
close due to lack of response and tested on very old yuzu version before memory reaper
