### ISSUE TITLE
Yuzu crashes on latest Windows 10 Update

### ISSUE THREAD

**Issue by Areidz** [yuzu-emu/yuzu#6037]
Today I was playing Super Smash Bros Ultimate on latest patch in Yuzu. It went flawless. After that, I installed a couple of Windows 10 updates and Yuzu is crashing when loading some textures, and it's even closing another programs (Firefox / Discord). 

The updates are the following:

![imagen](https://user-images.githubusercontent.com/8595185/110134906-2f959800-7dce-11eb-9054-8a9389ecf5ac.png)

I'm using a Ryzen 7 3700X, NVIDIA RTX 2070 with latest drivers, I have tested with the latest Yuzu (555) and the one I usually play with (532) and this is the log I have:
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6091423/yuzu_log.txt.old.txt)

Probably this happen to be an issue on these updates, but I'm posting it just in case this could help the development.

Thanks in advance.

**Comment by FearlessTobi** [comment]
Does this issue still exist?

**Comment by Areidz** [comment]
It was a problem with a lack of memory loading the shaders. I fixed it by adding a several GB of virtual memory and it's working flawless.
