### ISSUE TITLE
What build to work on for macOS

### ISSUE THREAD

**Issue by KohlerVG** [yuzu-emu/yuzu#6042]
Hi Yuzu Team,

I have begun developing yuzu for macOS, I have been watching, exploring sample code for Metal macOS GPU back-end, the only thing that is holding me back is what build to use and where exactly to place Metal inside Yuzu, I see that there are Windows & Linux builds, which one would be the closet to macOS? I know that macOS is built upon a Linux kernel.
I really want to dive deep into this and if anyone can help me on the way I would greatly appreciate it!

Thanks,
Kohler

**Comment by MerryMage** [comment]
It would likely be easier to communicate in real time on [discord](https://discord.gg/u77vRWY).

**Comment by MerryMage** [comment]
Have you done any C++ development with CMake before? The build is similar to how one would typically do.

Assuming you have macbrew and a very very recent version of XCode:
```
brew install pkgconfig sdl2 qt5 cmake
git clone --recursive https://github.com/yuzu-emu/yuzu
git submodule update --init --recursive

mkdir build
cd build

export Qt5_DIR=$(brew --prefix)/opt/qt5
cmake .. -DCMAKE_BUILD_TYPE=Release

make -j12
```

**Comment by MerryMage** [comment]
> Yuzu even have DirectX support
There is no DirectX support.

**Comment by iMonZ** [comment]
> > Yuzu even have DirectX support
> 
> There is no DirectX support.

Sorry then I messed up something 😅
Wasn't there some DirectX support in Yuzu?
Or is Yuzu Vulkan only?

**Comment by SleepingSnakezzz** [comment]
Yuzu started with OpenGL and then added Vulkan later.
