### ISSUE TITLE
Wrong character's appearence

### ISSUE THREAD

**Issue by Napolitaiin** [yuzu-emu/yuzu#6044]
![Capture d’écran 2021-03-03 182645](https://user-images.githubusercontent.com/79996623/110244660-04db4900-7f60-11eb-92ff-df4bd88f3828.png)

This is how I look while playing.

![Capture d’écran 2021-03-03 182823](https://user-images.githubusercontent.com/79996623/110244680-24727180-7f60-11eb-931e-d851ca669c3a.png)

This is how I should be.

**Comment by BSoDGamingYT** [comment]
You set your trainer ID to an illegal character. AKA, you used letters instead of numbers. Edit it to only numbers with PKhex

**Comment by Napolitaiin** [comment]
> You set your trainer ID to an illegal character. AKA, you used letters instead of numbers. Edit it to only numbers with PKhex
