### ISSUE TITLE
Crash after emulator's window loses focus

### ISSUE THREAD

**Issue by dsp2003** [yuzu-emu/yuzu#6048]
When running a game, either doing Alt-Tab or manually switching to another window, then (not) restoring the focus, causes the emulator to crash. Happens with both OpenGL and Vulkan renderers.

OS: Windows 7 x64 SP1 / Aero theming disabled
Video: GeForce 660GTX 2 GiB (driver version: 461.72)
HW: Athlon-II x64 620 @3.4GHz Quadcore / 16 GiB DDR3

**Comment by lat9nq** [comment]
Please try reproducing this issue on a supported operating system: Windows 8, 8.1, or 10, or any Linux distribution with glibc version >= 2.27 (e.g. Ubuntu 18.04, Fedora 33). Windows 7 is not supported, and (evidently) you may run into novel issues by running yuzu on it.

Please upload a log file once you've done that, as well.

**Comment by FearlessTobi** [comment]
Closing as author is unresponsive.

**Comment by dsp2003** [comment]
Unresponsive? I don't see a point in providing empty logs because crash happens on WinAPI/GDI level, which is irrelevant to emulation itself.

You don't handle the WinAPI calls (and window handle, pun intended) properly. You've also marked Windows 7 as unsupported, but aside this crash literally nothing else breaks.
