### ISSUE TITLE
The ability for Yuzu to use cheat codes is very poorly documented

### ISSUE THREAD

**Issue by nullavisus** [yuzu-emu/yuzu#6051]
More people need to know this is a thing imo. In addition, the exact method for allowing Atmosphere based cheats needs to be made more obvious. I was scratching my head for the past hour trying to remember how cheats worked wondering why they weren't showing up in my patch list (I assumed the path was just yuzu/load/<titleID>/cheats/<buildID>) until I finally found the answer buried in the FAQ page that the cheats folder needs to be in another subdirectory. Maybe have yuzu drop a text file inside the load directory or something detailing this feature better.

Also this kept coming up, the readme here is incorrect as it fails to mention needing to use a subdirectory, might want to fix that. It was confusing the hell out of me [https://github.com/yuzu-emu/yuzu-games-wiki/tree/master/cheats#yuzu-game-cheats](url)

**Comment by BSoDGamingYT** [comment]
Poorly documented, apart from being clearly documented in the yuzu FAQ.
