### ISSUE TITLE
yuzu fails to start on intel iris plus with vulkan,opengl slowed down

### ISSUE THREAD

**Issue by LoreBadTime** [yuzu-emu/yuzu#6060]
mainline 561,on previous versions there were no problem like this,

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6132799/yuzu_log.txt)

**Comment by goldenx86** [comment]
Update to the latest driver version from Intel's site.

**Comment by LoreBadTime** [comment]
Fixed

**Comment by LoreBadTime** [comment]
Fixed
