### ISSUE TITLE
Underwater audio issue in SM3DW+BF and Captain Toad: TT

### ISSUE THREAD

**Issue by IceWolf762** [yuzu-emu/yuzu#6066]
There appears to be an audio issue in **Super Mario 3D World + Bowser's Fury**. When underwater, instead of the music being muffled, the volume of the music gets louder. This also happens in **Captain Toad: Treasure Tracker**.

**Comment by IceWolf762** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6135844/yuzu_log.txt)

**Comment by SixelAlexiS90** [comment]
I just want to confirm that this is still an issue. Captain Toad have crackling audio issues too.
