### ISSUE TITLE
Bug When Trying To Use Multiplayer

### ISSUE THREAD

**Issue by busterposeyry** [yuzu-emu/yuzu#6068]
So let me preface this by saying i love yuzu. I think its amazing software and apreaciate the devolopers for working so hard on it. Here is my bug: When i do multiplayer in mario kart 8 deluxe it just freezes up when it asks for what control i would like to use. I have tried just a simple restart to turning off vsync and i cant get anything to work. This is apparently happens to other people so im not alone on this one.

**Comment by german77** [comment]
Press LR with the second controller at the start menu screen.

**Comment by Eldoris27** [comment]
THANK YOU SO MUCH
