### ISSUE TITLE
Pokemon let's go - Pokémon Tower misaligned fog

### ISSUE THREAD

**Issue by IGCIT** [yuzu-emu/yuzu#6071]
ArchLinux, mesa 20.3.4, opengl, latest yuzu

Lavender Town, Pokémon Tower

the effect shown in the screenshot is misaligned

![pkm](https://user-images.githubusercontent.com/76787191/111071237-7b82c400-84d5-11eb-83e0-4c1c8c9cd93c.jpg)
[yuzu_log.txt.zip](https://github.com/yuzu-emu/yuzu/files/6136787/yuzu_log.txt.zip)

**Comment by BSoDGamingYT** [comment]
Have you confirmed that these issues you are reporting are not driver issues?

**Comment by IGCIT** [comment]
i don't know if it is a mesa issue, i don't have other hw to test
