### ISSUE TITLE
Crash Team Racing: Nitro-Fueled

### ISSUE THREAD

**Issue by RyuumaH** [yuzu-emu/yuzu#6072]
the game with the 60 fps mod after some time the audio is out of sync.

**Comment by OZtistic** [comment]
This is an extremely bad way to report issues
please follow what the template asks for, when reporting issues
It's extremely hard to guesstimate what your issue is with no details other than "game broke, 60fps, fix"

**Comment by IGCIT** [comment]
actually, this is not a 60fps mod issue, i have no mod and the audio goes out of sync after a while (it is too fast)
i thought it was my fault, maybe not

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
