### ISSUE TITLE
OpenGL: MangoHud sometimes fails to be presented

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#6073]
Regression from #4692

The [MangoHud](https://github.com/flightlessmango/MangoHud) overlay currently only shows up on specific titles in OpenGL. Vulkan is unaffected: the overlay displays properly everywhere I tested. This issue seems unrelated to the GL driver in use (I had consistent results between NVIDIA, radeonsi, and LLVMpipe).

For example (and to define "sometimes"), MangoHud works with SSBU, fails with BOTW and es2gears.

**Comment by benderscruffy** [comment]
Can be closed
No update

**Comment by lat9nq** [comment]
Was this issue fixed or was it just closed for little reason?
