### ISSUE TITLE
SSBU moding | SaltySD/Skyline support, feature request

### ISSUE THREAD

**Issue by Daitan9** [yuzu-emu/yuzu#6076]
Hello, that's a feature request : 

So, I think you're too busy to think about Smash Ultimate modding;
But One (or two) thing that would be great is skyline and Salty SD support for yuzu !
Hope you'll find time to do this and
Keep up the good work !

**Comment by tech-ticks** [comment]
The main missing piece here is support for instruction cache invalidation when Skyline patches code at runtime. In addition, an Atmosphère-specific kernel patch would need to be emulated. See https://github.com/Ryujinx/Ryujinx/pull/2451/files#diff-b501f7d7eb3735111198bbf574cd0917c2eaf869108895f35c1e539d6c20f756R1878

**Comment by jam1garner** [comment]
I don't personally think saltynx support should be worked on, it has long been deprecated and there haven't been many mods written in it in recent time, while Skyline is the basis for modding in ult and a few other games and is still maintained. As tech-ticks stated icache invalidation + re-JITing after a hook is set is the most important thing, and also requires development effort from someone more familiar with yuzu.

External contributors would be more likely to handle the atmosphere kernel extension (I believe we only use it in Skyline for getting the processes' own title ID) but likely not the "dual-mapped memory invalidating icache on write" portion of implementation.

**Comment by gidoly** [comment]
closing due to duplicate with 7392 and more details available there
