### ISSUE TITLE
Figuring out a way to codify the input

### ISSUE THREAD

**Issue by samyoed** [yuzu-emu/yuzu#6082]
At the moment I'm still familiarizing myself with the codebase and I was just wondering if there is currently a way to take in inputs through code. I can't seem to pinpoint the area where inputs are being read but it would be extremely helpful if someone could point it out for me.

**Comment by german77** [comment]
Take a look at https://github.com/yuzu-emu/yuzu/blob/master/src/yuzu/configuration/configure_input_player_widget.cpp this a simplified widget that reads the controller input. The inputs are initialized with the parameters stored in the configuration then you call GetStatus() to obtain the input data.

**Comment by german77** [comment]
Here is were the input data is written so the game can actually read it https://github.com/yuzu-emu/yuzu/blob/master/src/core/hle/service/hid/controllers/npad.cpp

**Comment by samyoed** [comment]
Thanks! I'll take a look

**Comment by FearlessTobi** [comment]
Hey and thanks for your interest in contributing to yuzu. If you want to communicate with other developers I would suggest joining our Discord (or IRC channel).
For now, I'll close this issue as it isn't really something actionable.
