### ISSUE TITLE
DOA Xtreme 3 Scarlet Plant Pop-In OpenGL Glitch 

### ISSUE THREAD

**Issue by davidgamek** [yuzu-emu/yuzu#6086]
When playing beach volleyball in OpenGL, a plant pop-in at the center of the net waving back and forth. Occurring the most at Niki Beach.

![1CBB56BA-E832-485D-BF29-FCA458639A7E](https://user-images.githubusercontent.com/80833520/111478058-18c43f00-8706-11eb-961e-f48db0066f76.png)

**Comment by FearlessTobi** [comment]
Could you please also provide a log file?

**Comment by G-Spawn** [comment]
Closing for lack of log file & issue should be fixed iirc in latest yuzu. Please feel free to reopen issue and provide log file from newest yuzu should it still happen to you.
