### ISSUE TITLE
Leisure Suit Larry: Wet Dreams Don't Dry Freezing at certain pont

### ISSUE THREAD

**Issue by Dime333** [yuzu-emu/yuzu#6087]
Using a save created with Ryujiinx, I managed to go ingame without issues.

Spoiler alert!

At one point in the game you can try to give "Gluten Free Bread" to a pidgeon.  When you do this, the game freezes and the FPS counter goes down to 0. The music continues to play like normal. I have tried with both version 566 and EA 1523.

<img width="960" alt="larry" src="https://user-images.githubusercontent.com/42482063/111482532-458f4b00-8734-11eb-8e59-4191983d2c6e.png">

Operating System: Windows 10 x64
Processor/CPU: Intel Core i7-7700K
Video Card/GPU: Nvidia GeForce GTX 1060 3GB
Memory/RAM: Unknown/16GB

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/6157042/yuzu_log.zip)

[save.zip](https://github.com/yuzu-emu/yuzu/files/6157044/save.zip)

**Comment by Dime333** [comment]
Update: After applying game update 1.0.2, the issue doesn't happen anymore.

**Comment by gidoly** [comment]
fixed with game update
