### ISSUE TITLE
Adding full Wayland support

### ISSUE THREAD

**Issue by iMonZ** [yuzu-emu/yuzu#6088]
Hey, please add the full support for the Wayland display protocol.
There is already a QT module for that

**Comment by lat9nq** [comment]
I assume you mean for the AppImage? There's already an open PR to fix running yuzu on Wayland with the AppImage, it just needs merged. In the meantime, you can run the AppImage with `XAUTHORITY=${HOME}/.Xauthority DISPLAY=:0.0 ./yuzu-20210318-fc9cd297b.AppImage`.

Mentioned PR is [here](https://github.com/yuzu-emu/build-environments/pull/28).

**Comment by iMonZ** [comment]
> I assume you mean for the AppImage? There's already an open PR to fix running yuzu on Wayland with the AppImage, it just needs merged. In the meantime, you can run the AppImage with `XAUTHORITY=${HOME}/.Xauthority DISPLAY=:0.0 ./yuzu-20210318-fc9cd297b.AppImage`.
> 
> Mentioned PR is [here](https://github.com/yuzu-emu/build-environments/pull/28).

Hey, thanks!
Maybe this will fix my crash!
Do you use Flatpak? Are you experiencing any sandboxing problems?

**Comment by iMonZ** [comment]
> I assume you mean for the AppImage? There's already an open PR to fix running yuzu on Wayland with the AppImage, it just needs merged. In the meantime, you can run the AppImage with `XAUTHORITY=${HOME}/.Xauthority DISPLAY=:0.0 ./yuzu-20210318-fc9cd297b.AppImage`.
> 
> Mentioned PR is [here](https://github.com/yuzu-emu/build-environments/pull/28).

And do you know if flatpak support wayland too?

**Comment by goldenx86** [comment]
We don't officially maintain flatpak, only appimage.

**Comment by iMonZ** [comment]
> We don't officially maintain flatpak, only appimage.

An official option with some kind of package manager support would be nice to have

**Comment by iMonZ** [comment]
> I assume you mean for the AppImage? There's already an open PR to fix running yuzu on Wayland with the AppImage, it just needs merged. In the meantime, you can run the AppImage with `XAUTHORITY=${HOME}/.Xauthority DISPLAY=:0.0 ./yuzu-20210318-fc9cd297b.AppImage`.
> 
> Mentioned PR is [here](https://github.com/yuzu-emu/build-environments/pull/28).

Hey, today I have tried the  ad50f4543 build of Yuzu and still there is no full Wayland support

**Comment by lat9nq** [comment]
Can you elaborate on what you mean by "full Wayland support"? yuzu starts and runs with no issues here in Wayland.

**Comment by iMonZ** [comment]
> Can you elaborate on what you mean by "full Wayland support"? yuzu starts and runs with no issues here in Wayland.
> 
> ...aside from those inherent to using Wayland itself...

Currently yuzu is starting inside xwayland and not Wayland in the latest AppImage build.

**Comment by GitThisBugOff** [comment]
Under GNOME-Wayland, Yuzu still starts with xwayland as of the latest mainline build e6a178237

**Comment by iMonZ** [comment]
> Under GNOME-Wayland, Yuzu still starts with xwayland as of the latest mainline build e6a178237

That is the problem.

**Comment by iMonZ** [comment]
> Can you elaborate on what you mean by "full Wayland support"? yuzu starts and runs with no issues here in Wayland.
> 
> ...aside from those inherent to using Wayland itself...

The problem about running in xwayland mode is that you can’t use the Wayland only features and xwayland is suffering the performance

**Comment by iMonZ** [comment]
> Can you elaborate on what you mean by "full Wayland support"? yuzu starts and runs with no issues here in Wayland.
> 
> ...aside from those inherent to using Wayland itself...

The goal is to completely abandon xWayland in the future.

**Comment by e00E** [comment]
```
$ env QT_QPA_PLATFORM=wayland ./yuzu-20220317-7256129ac.AppImage
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

```
$ env QT_QPA_PLATFORM=xcb ./yuzu-20220317-7256129ac.AppImage
works and runs in xwayland mode
```

**Comment by baconwaifu** [comment]
Ran face-first into this myself, found this issue through search. Underlying cause is an issue with the cmake config. External QT package *has* the needed libraries, it's just that they aren't packaged into the bin folder with yuzu, so it can't *see* them when running. Need to copy the platform plugin, and the dependencies into the output folder. Unfortunately, I have no idea how yuzu does that, so I can't make the PR myself.

Libraries to copy for wayland support:
* `plugins/wayland-*`
* `plugins/platforms/libwayland-*`
* `libs/libQt5WaylandClient.so`

Tested with a fresh build, no wayland support, manually copied those files, and although it still complains "ignoring XDG_PLATFORM_TYPE", it runs in wayland just fine with the env override. For future reference, a way to "prioritize" wayland for QT applications is `QT_QPA_PLATFORM="wayland;xcb"` which will cause it to fall back to XCB if wayland doesn't work.

**Comment by liamwhite** [comment]
Should be fixed by #7410

**Comment by Wemmy0** [comment]
Because of https://gitlab.freedesktop.org/xorg/xserver/-/issues/1317 this makes yuzu very stuttery because of xWayland

**Comment by GioPanaro** [comment]
@liamwhite - @Wemmy0 is correct, using xWayland is not a viable solution for all systems using NVIDIA. Yuzu needs native wayland support

**Comment by liamwhite** [comment]
Self-builds work fine with wayland, but official releases disable it. I don't know when we will enable wayland in official releases because of the compositor bugs I have mentioned elsewhere.
