### ISSUE TITLE
Animal Crossing New Horizons Amiibos not working at all.

### ISSUE THREAD

**Issue by fobdev** [yuzu-emu/yuzu#6089]
When you head to File > Load Amiibo or press F2 and select the .bin file of the Animal Crossing amiibo and press Open, nothing happens in game while in Nook's Shop or Harv's Island when there is the amiibo icon showing up waiting for a amiibo to be added.

Is this a known issue? I could'nt find this particular problem documented elsewhere.
None of the amiibos that I have from ACNH worked at all.

I tested this issue in Yuzu 558 and Yuzu EA 1525, both with same result.
I used to have older versions of Yuzu EA and this also happened in them, no specific version but all of them didn't worked.
I try this every emulator update and end up with the same result.

**Comment by mayuumi** [comment]
same in yuzu EA 1532

**Comment by Enluria** [comment]
Same on Yuzu 569! However, in Super Mario Odyssey it works normally.

**Comment by imjustcaden** [comment]
same on yuzu 704

**Comment by Necirays** [comment]
Still not working on Yuzu EA 2016, but I think it has to do with ACNH updates not Yuzu.
Any idea to make it work ?

**Comment by radicaldreamer** [comment]
Amiibos used to work great in New Horizons all the way back in July of 2020, but now the game acts like no amiibo is loaded
![raymond](https://user-images.githubusercontent.com/2251114/141399877-fbbe0c7c-2ca4-4596-a0ea-974198b5037d.png)
.

**Comment by german77** [comment]
If they worked before do you have the mainline version? I tried from release date of amiibos till present. Not a single one worked

**Comment by radicaldreamer** [comment]
> If they worked before do you have the mainline version? I tried from release date of amiibos till present. Not a single one worked

Amiibos definitely worked in "early access 715" version.

**Comment by Loveless33** [comment]
I am unable to load amiibo in version 811 as well.

**Comment by bai0012** [comment]
EA 2265 as well,ACNH 2.0.3 and 3DlCs
maybe ACNH's fault?

**Comment by TheVoidIsBees** [comment]
Same here in yuzu 867. Maybe it's from ACNH and not yuzu? But in either case, it sucks.
