### ISSUE TITLE
Audio in games just sounds like clicks in my left ear

### ISSUE THREAD

**Issue by Tenkomanker** [yuzu-emu/yuzu#6094]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6176882/yuzu_log.txt)

I was trying to run Pokemon Sword and Shield on yuzu and when I first launched it there was no sound, so I played around and then got something to the tune of every time there's a sound effect like selecting a language or picking my character a really loud, static-y click goes off in my left ear. I have no idea why it happens because in every other game this is perfectly fine, it only happens with these 2 pokemon games.

Happening with yuzu 569, don't know how to get the commit hash but I got it off of the main yuzu page
Specs are:
Ryzen 5 3600
MSI GeForce 1660 Super
Not sure which other specs are relevant

I'll also attach screenshots of my settings
![yuzu_k7wKG5ZEc4](https://user-images.githubusercontent.com/26466631/111894713-7052fb00-89e3-11eb-9e4e-ea94d67da8fa.png)
![yuzu_KoAD65sjuP](https://user-images.githubusercontent.com/26466631/111894714-7052fb00-89e3-11eb-8f8e-6db80b49a13c.png)
![yuzu_PfLuvBetwS](https://user-images.githubusercontent.com/26466631/111894715-7052fb00-89e3-11eb-98f0-883efa09ee70.png)
![yuzu_PlYglvk3IU](https://user-images.githubusercontent.com/26466631/111894716-70eb9180-89e3-11eb-920b-969c578f78ef.png)
![yuzu_SylEI1gfwI](https://user-images.githubusercontent.com/26466631/111894717-70eb9180-89e3-11eb-8c22-bd9f09513d43.png)
![yuzu_uPZRG0MxUB](https://user-images.githubusercontent.com/26466631/111894718-70eb9180-89e3-11eb-8ee3-ec30236b1762.png)
![yuzu_uYLijP2D39](https://user-images.githubusercontent.com/26466631/111894719-70eb9180-89e3-11eb-8e46-ca69a5540eea.png)

**Comment by gidoly** [comment]
does this still happens? planning to close since user haven't reported same issue recently

**Comment by Tenkomanker** [comment]
Nope, issue has been resolved, thanks
