### ISSUE TITLE
Vulkan Error on bootcamp

### ISSUE THREAD

**Issue by johnsmith1232541** [yuzu-emu/yuzu#6098]
I have a Macbook  Pro 2019, with an AMD Radeon Pro 5500M. I'm running Windows 10 via bootcamp.
I also have Yuzu early access and the issue happens in all versions.
I can play fine with OpenGL but since I have an AMD card I thought I'd try Vulkan since some games aren't smooth.

However, with Vulkan enabled, no game starts and gives an error. I included the log file but the problem seems to be: `[ 146.665037] Render.Vulkan <Error> video_core\renderer_vulkan\renderer_vulkan.cpp:RendererVulkan:121: Vulkan initialization failed with error: VK_ERROR_EXTENSION_NOT_PRESENT`.

I tried googling solutions but I didn't find anything.
Any ideas?

**Comment by iMonZ** [comment]
> I have a Macbook Pro 2019, with an AMD Radeon Pro 5500M. I'm running Windows 10 via bootcamp.
> I also have Yuzu early access and the issue happens in all versions.
> I can play fine with OpenGL but since I have an AMD card I thought I'd try Vulkan since some games aren't smooth.
> 
> However, with Vulkan enabled, no game starts and gives an error. I included the log file but the problem seems to be: `[ 146.665037] Render.Vulkan <Error> video_core\renderer_vulkan\renderer_vulkan.cpp:RendererVulkan:121: Vulkan initialization failed with error: VK_ERROR_EXTENSION_NOT_PRESENT`.
> 
> I tried googling solutions but I didn't find anything.
> Any ideas?
> 
> [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6178083/yuzu_log.txt)

Hey,
this could be if you installed the wrong AMD drivers.
Have you tried Vulkan with the internal GPU?

**Comment by johnsmith1232541** [comment]
The only option I get is to use it with the ADM Radeon Pro 5500M. Should I try to uninstall the drivers and reinstall them?

**Comment by iMonZ** [comment]
> The only option I get is to use it with the AMD Radeon Pro 5500M. Should I try to uninstall the drivers and reinstall them?

Yes you can try that.
Or you can try installing Linux(Ubuntu) this fixed a lot of issues for me!

**Comment by darkarp** [comment]
If you want to use it on windows, you can't use the official AMD bootcamp drivers. Instead, install [these drivers](https://www.bootcampdrivers.com/). Select the latest one for you. At this point in time it would be "Adrenalin March 2021". Select the one which says better for FPS.

These are unofficial drivers, but they work better than the official ones and are regularly updated. After installing, you can switch to vulkan without problems. You should also expect a much better perfomance in and outside Yuzu.

Caution: These drivers are unofficial so if you're not comfortable with that, don't install them.

**Comment by johnsmith1232541** [comment]
This worked! @darkarp

**Comment by itachi239** [comment]
@johnsmith1232541 Hi, have you played pokemon sword and shield? If yes, how much fps do you get?

**Comment by johnsmith1232541** [comment]
@itachi239 I haven't played those yet. So far I've played Animal Crossing New Horizon with 28-30 fps and Super Mario Odyssey with 60 fps

**Comment by itachi239** [comment]
@johnsmith1232541 could you please try pokemon sword and tell how much fps you get. Only when you have enough time. That would be nice

**Comment by FearlessTobi** [comment]
Issue seems to be resolved.
