### ISSUE TITLE
Fast RMX - Major graphical glitches.

### ISSUE THREAD

**Issue by HauruI** [yuzu-emu/yuzu#6103]
Test conditions : Windows 10 20H1 - Intel i5-9300HF @ 2.1-4.2GHz - Nvidia Geforce RTX 2060 @ 6Gb - 16Gb RAM - EUR ROM - yuzu Mainline g2256f5a19 (2021-03-21)
Log file : [yuzu_log.txt.txt](https://github.com/yuzu-emu/yuzu/files/6187623/yuzu_log.txt.txt)

What occurs : Textures loaded incorrectly leading the game to be unplayable.

![fastrmx_bug_opengl_yuzu570](https://user-images.githubusercontent.com/37268710/112108475-88c44080-8bb0-11eb-886c-f3850e2d5cde.png)
Real hardware comparison :
![image](https://user-images.githubusercontent.com/37268710/112108583-af827700-8bb0-11eb-9b2b-cd8aa6bd1805.png)

How to reproduce : 
1. Launch any course in the Championship mode.

**Comment by lat9nq** [comment]
Duplicate of #4043

**Comment by HauruI** [comment]
Oopsie, I opened the issue because no one was visible on the compat page - I forgot searching on the issues as well... My bad!
