### ISSUE TITLE
Black spots on screen in Fire Emblem: 3 Houses

### ISSUE THREAD

**Issue by Paradoxilicious** [yuzu-emu/yuzu#6104]
There seems to be some strange shadow outside a certain distance darkening everything and causing black spots(including the political map expose in the intro). More particularly, major characters like Edelgard get a flickering black square drawn on them when in that "shadow", and seem to fine when outside of it. (see picture 1 and 2 in succession) I have attached my log and a comparison screenshot of the game on the switch.
My specs:
i5 10300h
Rtx 3060 mobile
16 GB RAM dual channel @2933mhz
m2 pcie nvme SSD
![Screenshot 2021-03-24 041611](https://user-images.githubusercontent.com/81267886/112228970-20309e80-8c58-11eb-8aac-fbaf924816ac.png)
![Screenshot 2021-03-24 041808](https://user-images.githubusercontent.com/81267886/112228972-21fa6200-8c58-11eb-9c81-e8c05a8f6028.png)
![Screenshot 2021-03-24 041444](https://user-images.githubusercontent.com/81267886/112228973-232b8f00-8c58-11eb-9a3e-d2ab4d34b2c8.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6193174/yuzu_log.txt)

**Comment by SpaceCowboy321** [comment]
I am having the same issue. I am running version 573 with an Nvidia RTX 3080. I have attached the log file below.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7043403/yuzu_log.txt)

**Comment by v1993** [comment]
@SpaceCowboy321 As I've suggested in another issue, please update yuzu before reporing bugs. A lot of important changes happened since yuzu version you're using.

**Comment by Paradoxilicious** [comment]
@SpaceCowboy321 All of this has been fixed since the Hades release of Yuzu. I switched to EA a while back but I am pretty sure the current public version is much, much higher than 573.
