### ISSUE TITLE
no audio 

### ISSUE THREAD

**Issue by Ievian** [yuzu-emu/yuzu#6107]
so basically i use my headset through my ps4 controller which is connected through usb and dont have audio, ive looked around and apparently yuzu dosent support usb. Ive tried basically all I can idk what else there is to do

**Comment by Coldbane** [comment]
using xbox one controller via usb and headset plugged in, works great.
u should check your sound settings in windows(or which OS u use)

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
