### ISSUE TITLE
MONSTER HUNTER XX (JPN version) can't name new character.

### ISSUE THREAD

**Issue by randomdice101** [yuzu-emu/yuzu#6117]
I tried to get start a new save in the old monster hunter game I only got the japanese copy. You can't name the character however thus blocking progress. The screen just shows the limitations for the name but you can't enter anything, no yuzu textbox shows up. I have update 1.5.1 installed as an NSP. 
![image](https://user-images.githubusercontent.com/4016932/112735421-307b9e80-8f22-11eb-989c-d0b920b5c72c.png)

I disabled the patch and tried again and for a split second the UI changes but then it reverts back to the above screen and no name can be inserted either.
![image](https://user-images.githubusercontent.com/4016932/112735431-40937e00-8f22-11eb-8f14-6cec758b2332.png)

this is the Yuzu build I'm using.
![image](https://user-images.githubusercontent.com/4016932/112735441-5dc84c80-8f22-11eb-9ea5-5b8d09cfbb9d.png)

**Comment by G-Spawn** [comment]
Some options I can think of are: Using the other switch emulator if it lets you generate a save there with a name you can bring it back to yuzu, or you could google a save online for the game, lastly you could just export the save from your Nintendo Switch using something like Checkpoint (mentioned in the yuzu quickstart guide )

**Comment by randomdice101** [comment]
I didn’t know there was another emulator? I can make a save on the switch and bring it over, I was just asked to report it on discord when I noticed this bug lol

On Mar 28, 2021, at 03:07, Ghost ***@***.***> wrote:

﻿

Some options I can think of are: Using the other switch emulator if it lets you generate a save there with a name you can bring it back to yuzu, or you could google a save online for the game, lastly you could just export the save from your Nintendo Switch using something like Checkpoint (mentioned in the yuzu quickstart guide )

**Comment by FearlessTobi** [comment]
Could you please provide a log file for your issue?
