### ISSUE TITLE
Dragon Quest XI Graphical issues with AMD Graphics Cards (Mainline #575)

### ISSUE THREAD

**Issue by DragonsFear** [yuzu-emu/yuzu#6121]
Mainline Build 575 
Hardware Specs 
Ryzen 1600
16GB DDR4 3200
RX570 8GB PG (OC Edition )
NVMe OS 
SSD for Yuzu 

graphical glitches accure with AMD graphic cards , see Screenshots in Dragon Quest XI , 

![Dragon Quist XI Graphics glitch Yuzu 1](https://user-images.githubusercontent.com/81340701/112778190-3cf81800-9044-11eb-96b4-fadcd9f0c7fd.jpg)
![Dragon Quist XI Graphics glitch Yuzu 2](https://user-images.githubusercontent.com/81340701/112778202-408b9f00-9044-11eb-864c-98f812936439.jpg)
![Dragon Quist XI Graphics glitch Yuzu 3](https://user-images.githubusercontent.com/81340701/112778204-42556280-9044-11eb-8cc0-9261a83dec2b.jpg)
[yuzu_log.txt.txt](https://github.com/yuzu-emu/yuzu/files/6218771/yuzu_log.txt.txt)

**Comment by goldenx86** [comment]
So far, as a workaround, only the Linux RADV Vulkan driver driver produces good results in this game.

**Comment by DragonsFear** [comment]
Already traid that , and even in Linux the distortion stays on the weapon , and overtime ( 30 to 40 minutes) it will distort the envirement with a high light reaction
So its a Yuzu general problem , and not so much a windows only problem

**Comment by benderscruffy** [comment]
this should be fixed with #9194

**Comment by DragonsFear** [comment]
> This is not fixed,
> 
> ![image](https://user-images.githubusercontent.com/15495525/226154069-2515fdca-651f-480d-9de8-e76fd46685ae.png)

indeed , sofar havent seen any fixes , and all version have the same problem 

on a brighter note , luckely XI S is now also on PC and (even in ultrawide) it works like a charm
