### ISSUE TITLE
Is there Yuzu support for AMD R7 260 graphics?

### ISSUE THREAD

**Issue by jlarmijos** [yuzu-emu/yuzu#6136]
Hi, it happens that I am trying to play Bowser's Fury with the Radeon R7 260 graphics card, I have display problems when using OpenGL graphics as it appears in the image. Also when using Vulkan annoying pauses occur without having massive load of vram or ram. I have checked and unchecked all possible settings. I have updated drivers and also a headache. I attach a log using OpenGL and another with Vulkan. Thank you.
PS: The same does not happen with another Nvidia GT 710 graphics that runs the game perfectly.
[yuzu_log Vulkan.txt.txt](https://github.com/yuzu-emu/yuzu/files/6253617/yuzu_log.Vulkan.txt.txt)
[yuzu_log_OpenGl.txt](https://github.com/yuzu-emu/yuzu/files/6253618/yuzu_log_OpenGl.txt)

**Comment by goldenx86** [comment]
Make sure to run the latest GPU driver, you're a bit outdated there.

**Comment by jlarmijos** [comment]
> Asegúrese de ejecutar el controlador de GPU más reciente, está un poco desactualizado allí.
> Utilice el controlador de juegos habitual, no el empresarial.

I also tested it even with Windows from scratch and it remains the same ...
![image](https://user-images.githubusercontent.com/79478556/113493347-156dd900-94a4-11eb-9c27-fb352fc75026.png)

**Comment by ReinUsesLisp** [comment]
That's a known bug in master and it's fixed on work in progress changes.

It happens due to different floating point precision when handling interpolation on AMD GPUs compared to Nvidia.

**Comment by jlarmijos** [comment]
> That's a known bug in master and it's fixed on work in progress changes.
> 
> It happens due to different floating point precision when handling interpolation on AMD GPUs compared to Nvidia.

Thanks

**Comment by jlarmijos** [comment]
> That's a known bug in master and it's fixed on work in progress changes.
> 
> It happens due to different floating point precision when handling interpolation on AMD GPUs compared to Nvidia.


On the other hand, it makes me crazy to think that a graphics with such good performance does not allow me to use the Yuzu emulator well, unlike one with such low performance...

![comparative](https://user-images.githubusercontent.com/79478556/113494752-02add100-94b1-11eb-93a7-025211e4059d.png)

**Comment by CrusadingNinja** [comment]
> > That's a known bug in master and it's fixed on work in progress changes.
> > It happens due to different floating point precision when handling interpolation on AMD GPUs compared to Nvidia.
> 
> On the other hand, it makes me crazy to think that a graphics with such good performance does not allow me to use the Yuzu emulator well, unlike one with such low performance...
> 
> ![comparative](https://user-images.githubusercontent.com/79478556/113494752-02add100-94b1-11eb-93a7-025211e4059d.png)

GPU size (which is what G3D is trying to quantify here) matters much less than driver quality for emulation. In this case, Nvidia's drivers are very much superior to AMD's Windows drivers, so the Nvidia card will perform better even though it is less powerful in terms of raw rasterization performance.

**Comment by jlarmijos** [comment]
> > > That's a known bug in master and it's fixed on work in progress changes.
> > > It happens due to different floating point precision when handling interpolation on AMD GPUs compared to Nvidia.
> > 
> > 
> > On the other hand, it makes me crazy to think that a graphics with such good performance does not allow me to use the Yuzu emulator well, unlike one with such low performance...
> > ![comparative](https://user-images.githubusercontent.com/79478556/113494752-02add100-94b1-11eb-93a7-025211e4059d.png)
> 
> GPU size (which is what G3D is trying to quantify here) matters much less than driver quality for emulation. In this case, Nvidia's drivers are very much superior to AMD's Windows drivers, so the Nvidia card will perform better even though it is less powerful in terms of raw rasterization performance.

surely AMD engineers don't think the same ...

**Comment by jlarmijos** [comment]
I had to put my graphic card up for sale ...

![for sale](https://user-images.githubusercontent.com/79478556/113522277-c76cda00-9564-11eb-8875-11ded15ab37c.png)

**Comment by jlarmijos** [comment]
> That's a known bug in master and it's fixed on work in progress changes.
> 
> It happens due to different floating point precision when handling interpolation on AMD GPUs compared to Nvidia.

Excuse me, how long do you estimate the fix will come out? Thak you.
