### ISSUE TITLE
Animal Crossing New Horizons previous events not unlocking

### ISSUE THREAD

**Issue by Nepov** [yuzu-emu/yuzu#6137]
I'm using latest Yuzu mainline build, installed latest Animal Crossing New Horizons 1.9.0 game update, tried to time travel the hole emulator with the program RunAsDate to two different events on the game from last year: Easter Egg on April 1st 2020 and Nature Day on April 23rd 2020. Both dates shows on the clock inside the game, but neither events are announced. Yuzu region is set to USA, inside the ACNL game, I've set the region to be USA and northern hemisphere.

**Comment by G-Spawn** [comment]
Please try using custom rtc in updated yuzu while game is running. This should work better for acnh events. To have it take affect you can change custom rtc  when game is running then reload game/save.
