### ISSUE TITLE
Super Smash Bros. Ultimate S2R WscaleFactorXY is not implemented

### ISSUE THREAD

**Issue by Deadhuntz** [yuzu-emu/yuzu#6140]
Latest EA Yuzu is crashing on loading shaders in Super Smash Bros. Ultimate 10.1.0
Vulkan just crashes after the loading message disappeared.
yuzu Version: yuzu Early Access 1555 | HEAD-early-access-0-1545-10-gc92a211e7

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6254724/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
Unrelated issue, this isnt causing the crash
