### ISSUE TITLE
Monster Hunter XX/GU Shoutout keyboard not appearing

### ISSUE THREAD

**Issue by eperhub** [yuzu-emu/yuzu#6149]
On Yuzu version EA 1559, the new project Eleuthia keyboard works fine for character and palico names, but doesn't work for Shoutout editing in game. A good factor despite not appearing is that the game doesn't softlock anymore despite not being able to edit texts in game. As said above everything works fine for Character name or Palico name instead. This is completely a minor thing for the game, and nothing serious, just wanted to report because there may be some diffent calls that the new keyboard software can't recognize properly maybe?

![Untitled](https://user-images.githubusercontent.com/69272247/113575910-e8920100-961e-11eb-9273-b764cef96616.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6258236/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
You are pressing the wrong button to edit the shoutout. Press Y, not X

**Comment by BSoDGamingYT** [comment]
Closing since this isnt actually a problem. User is pressing the wrong input for invoking the software keyboard
