### ISSUE TITLE
Mario Kart 8 Deluxe: visual glitch with Vulkan graphics API

### ISSUE THREAD

**Issue by AquoDev** [yuzu-emu/yuzu#6151]
I've been experiencing this issue in the latest versions of yuzu, mainline build.

Look at the first screenshot, there's an "hidden" square of 1024x1024 pixels in the left half of the screen where light effects behave strangely.
![glitch](https://user-images.githubusercontent.com/14019792/113781852-d7c9b400-9720-11eb-9cec-a8f0f2e24d96.png)

This is the same screenshot but the borders are colored in red for better visibility.
![glitch - 1024x1024](https://user-images.githubusercontent.com/14019792/113781829-d00a0f80-9720-11eb-8d26-fb00381e9f98.png)

Steps to reproduce:
1. Launch Mario Kart 8 Deluxe + 1.7.1 update, no mods enabled.
2. Start a time trial in Twisted Mansion (Flower Cup).
3. Go backwards to the spot that's shown in the picture and you should see the glitch.

This happens in every track, but is more noticeable in darker tracks because the headlight is cut in half.
This doesn't happen when the graphics API is OpenGL, light effects work as expected in that case.

Log is attached here with my system specs and yuzu settings, I've enabled graphics debugging and can provide more information as requested.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6267704/yuzu_log.txt)

**Comment by CrusadingNinja** [comment]
Does this still occur with an Nvidia Driver version prior to 465? The 465 drivers have known regressions and issues with Vulkan.

**Comment by AquoDev** [comment]
> 
> 
> Does this still occur with an Nvidia Driver version prior to 465? The 465 drivers have known regressions and issues with Vulkan.

I don't know, maybe I could try an older driver later this week and report the results back. Any recommendations for which driver I should try?

**Comment by CrusadingNinja** [comment]
> > Does this still occur with an Nvidia Driver version prior to 465? The 465 drivers have known regressions and issues with Vulkan.
> 
> I don't know, maybe I could try an older driver later this week and report the results back. Any recommendations for which driver I should try?

The latest 461 driver should be fine.

**Comment by RinMaru** [comment]
happens on AMD too RX 480

**Comment by serious-raul** [comment]
happens on gtx 1650, xeon x3470 too. Mainline and early access build both.
