### ISSUE TITLE
Super Smash bros ultimate Crash while loading a map

### ISSUE THREAD

**Issue by TheAllMaker** [yuzu-emu/yuzu#6163]
Hey guys, my Super smash bros ultimate game crashed today. You can see the errors at the end of the log
Version: Early Access 1560
How to reproduce: I tried playing on the "big battlefield" map and it crashed on the loading screen
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6271643/yuzu_log.txt)

My PC: 
AMD Radeon rx 5700
I7 4770
16gb DDR3 RAM

**Comment by abi-21** [comment]
@G-Spawn Not an expert or anything, but are you sure both logs link to same issue?
Log files seems bit different on quick check.

**Comment by G-Spawn** [comment]
Stability with smash should be addressed in latest mainline versions of yuzu & early access. Please post a log from updated yuzu & reopen issue should it still happen to you.
