### ISSUE TITLE
clock_types: Signed integer overflow in Pokémon Sword and LGPE Demo

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#6165]
Undefined behaviour sanitizer reports `src/./core/hle/service/time/clock_types.h:66:25: runtime error: signed integer overflow: 139682469932695 * 1000000000 cannot be represented in type 'long int'` while starting Pokemon Sword and Pokemon Let's Go Pikachu/Eevee Demo. This occurs when meeting Hop for the first time in Sword, or meeting Prof. Oak for the first time in LGPE Demo.

Backtrace (different instance than the above report): [clock_mul_overflow.txt](https://github.com/yuzu-emu/yuzu/files/6275017/clock_mul_overflow.txt)

I would have tried suggesting a fix in a PR like the other ubsan issues I've PR'd on, but this one seems to be a deeper issue that I don't understand. Minor severity?

**Comment by KostaSaizo7** [comment]
Is this related to #4074?
