### ISSUE TITLE
Celeste Unmapped Read64 Spam

### ISSUE THREAD

**Issue by khang06** [yuzu-emu/yuzu#617]
Log: https://gist.github.com/khang06/f0546615d051ad299d44217b712c2cdf
Commit 3dab0e2

**Comment by khang06** [comment]
Looks like this is fixed now. I have no idea what commit fixed it. The game freezes up while loading now, but this particular issue is fixed.

**Comment by Subv** [comment]
It was due to us not saving the TPIDR_EL0 register across context switches, https://github.com/yuzu-emu/yuzu/pull/751
