### ISSUE TITLE
Pokémon Let's Go, Pikachu - Black Screen at catching screen

### ISSUE THREAD

**Issue by Undeon** [yuzu-emu/yuzu#6176]
I'm using yuzu-mainline, build 585. When I encounter a wild pokemon e choose Get ready the screen turns black. The game dont crash, because if I click the A button, It's hear the sound of throwing the pokéball and the wild pokemon makes noises normally, and after a few moments the pokemon ran away and the screen return back to normal again.

**Comment by gerbilOFdoom** [comment]
@Undeon I'm on build 587, could not replicate your issue. What graphics settings are you using?

**Comment by Undeon** [comment]
> @Undeon I'm on build 587, could not replicate your issue. What graphics settings are you using?

You're right. At 587 the problem was solved. 👍

**Comment by Undeon** [comment]
The problem was solved at the build 587.
