### ISSUE TITLE
Command sequence formatting error for Linux builds on Wiki

### ISSUE THREAD

**Issue by OZtistic** [yuzu-emu/yuzu#6177]
the build guide on the wiki is broken for linux, is a CSS error I assume. I tried to find where the wiki is on github but I either don't have permission, or it's hidden/private
specifically the section where you pass the commands to the package manager to get and use conan
![image](https://user-images.githubusercontent.com/71381851/114260438-37bda480-9a18-11eb-8e43-18df8dee9512.png)
it should be literal **&&** in the command string, and instead it's literal HTML **amp;amp;**
Addendum: I just had the same issue trying to add the HTML amp for & here to demonstrate lol
It's an easy issue to fix I'm sure

**Comment by lat9nq** [comment]
The version on GitHub should be accessible here, it renders the ampersands correctly:
https://github.com/yuzu-emu/yuzu/wiki/Building-for-Linux

**Comment by OZtistic** [comment]
thank you for the other link. I will close this issue, but it really should be fixed on the main site

**Comment by lat9nq** [comment]
> it really should be fixed on the main site

This is still a valid issue and should remain open.
