### ISSUE TITLE
Pokemon: Let's Go Pikachu Stuttering

### ISSUE THREAD

**Issue by gerbilOFdoom** [yuzu-emu/yuzu#6178]
Using this mainline build: https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-587/yuzu-windows-msvc-20210410-108df67ae.tar.xz

Using Let's go Pikachu with update 1.02 installed. Game stutters while moving the character around the game world but the emulator only occasionally shows a drop in FPS from 30 to 28. Game runs at between 22% and 25% CPU utilization with no CPU core bursting beyond 50% utilization in Windows Task Manager. Cannot guarantee CPU usage isn't spiking to 100% on a single core during stuttering given limitations in task manager. 

Stutters do not coincide with shader compilation, the symptoms of which are most commonly seen during battles when a previously unused move is executed and results in a second or two of the game freezing. 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6290826/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Please feel free to reopen this issue if it still happens to you on updated yuzu versions.
