### ISSUE TITLE
SSBU Graphical Issue

### ISSUE THREAD

**Issue by Jfig27** [yuzu-emu/yuzu#6200]
# Yuzu Early Access 1604
System Specs: 
CPU; Intel i9-9900K CPU
GPU: NVIDIA RTX 2080 SUPER
RAM: 32gb

## Video of graphical error happening
https://user-images.githubusercontent.com/79497737/114824610-274c5780-9d93-11eb-82d3-697400c58ddc.mp4

Seems like the eyes went missing right after landing with an air-dodge. I have not been able to replicate.

## Graphical Error Yuzu
![ness no eyes](https://user-images.githubusercontent.com/79497737/114824746-4f3bbb00-9d93-11eb-97ca-c72e6f3a8a9a.png)

## Switch hardware
![Switch ness eyes](https://user-images.githubusercontent.com/79497737/114824866-75f9f180-9d93-11eb-902c-fca089eefdbf.JPG)

## Log
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6321652/yuzu_log.txt.old.txt)

**Comment by goldenx86** [comment]
A log file would help a lot.

**Comment by Jfig27** [comment]
> A log file would help a lot.

It's been edited.

**Comment by gidoly** [comment]
does this still happens? planning to close if no response done since we had no reporter that says same issue and  can't reproduce on team's pc
