### ISSUE TITLE
Build fails in linux

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#6203]
Build log is [here](https://pastebin.com/QPB8S55D).  The libudev-related log excerpt below might provide a reason the build is failing (though libudev-dev is installed).

Test system:

* Linux Mint 20.1 / kernel 5.11
* Compiler: gcc-10.2.0
* Build tested: 0a5bc8ec14619080cabe3168a1b82c6da4a63a0f
```
CMake Warning at externals/libusb/CMakeLists.txt:79 (find_package):
  By not providing "FindLibudev.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Libudev", but
  CMake did not find one.

  Could not find a package configuration file provided by "Libudev" with any
  of the following names:

    LibudevConfig.cmake
    libudev-config.cmake

  Add the installation prefix of "Libudev" to CMAKE_PREFIX_PATH or set
  "Libudev_DIR" to a directory containing one of the above files.  If
  "Libudev" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by lat9nq** [comment]
This title of this issue and the issue described here by the CMake *warning* are separate issues. Assuming you mean the SDL compilation issues, not the udev issue.

Seems to be an issue with the older version of SDL2 that's available to Linux Mint 20 (and probably Ubuntu 20.04).

**Comment by lat9nq** [comment]
A workaround would be to install the same PPA that the build container uses for SDL2: https://launchpad.net/~cybermax-dexter/+archive/ubuntu/sdl2-backport

From here, though keep in mind that this is intended for Bionic, not Focal: https://github.com/yuzu-emu/build-environments/blob/master/linux-fresh/Dockerfile

**Comment by Shoegzer** [comment]
Thanks @lat9nq.  The cmake excerpt only provides a hint as to why the build is failing.  I've updated the summary to reflect this more clearly. 

If it's truly an SDL2 issue,  where are you seeing that the minimum SDL2 version has changed?  2.0.10 (as available in the Ubunut focal repo) was always fine; however 2.0.14 is the latest.

**Comment by lat9nq** [comment]
Line 495 (and the related following lines) of your build log is the issue. Your version of SDL2 is missing symbols that yuzu expects to have.

> If it's truly an SDL2 issue, where are you seeing that the minimum SDL2 version has changed?
This issue is likely due to #6021. Before, your machine was likely using Conan to manage the SDL2 version, but we removed that since the provider for that version is closing down in the coming month.

Seems that the required version of SDL is 2.0.12, the same as in the SDL2-backport PPA. However, trying to set `find_package(SDL2 2.0.12 REQURIED)` fails because SDL2 does not set the version in their find package module.

**Comment by Shoegzer** [comment]
Thanks @lat9nq.  I wonder why that PR created the issue since yuzu-mainline compiled fine only a few days ago?

Also, if the process to update SDL2 as you posted is for bionic, how would I do it for focal?  I could compile SDL2 from source, but then I'd have to redo that whenever the ubuntu repo changed, so i'd rather avoid it if possible.

**Comment by lat9nq** [comment]
> I wonder why that PR created the issue since yuzu-mainline compiled fine only a few days ago?

6201 was created and merged yesterday

> Also, if the process to update SDL2 as you posted is for bionic, how would I do it for focal?

See #6204

**Comment by Shoegzer** [comment]
> 6201 was created and merged yesterday

My apologies, I was looking at something else when I wrote that

Thanks for the fix.

**Comment by qurious-pixel** [comment]
Latest version is SDL2-2.0.14.
```
export SDL2VER=2.0.12

cd /tmp
curl -sLO https://libsdl.org/release/SDL2-${SDL2VER}.tar.gz
tar -xzf SDL2-${SDL2VER}.tar.gz 
cd SDL2-${SDL2VER} 
./configure --prefix=/usr 
make && sudo make install 
rm ../SDL2-${SDL2VER}.tar.gz```
