### ISSUE TITLE
Yuzu Build 1612 - Web applet kills all inputs

### ISSUE THREAD

**Issue by nebulakid** [yuzu-emu/yuzu#6209]
Hi yuzu Team,

not sure in which build this started, as I've updated yuzu yesterday after a few weeks and haven't played SMO for a while now, but once the web applet is shown, all inputs besides mouse are dead. Restarting the game does not help. The controlls are dead for the runtime of yuzu. Disabling and re-enabling the first controller does not help (Yuzu will recognize that no controller is connected, but after enabling nothing changes).

Build 1612 - yuzu-windows-msvc-source-20210418-c55fddf70
System Specs:
CPU: AMD Ryzen 5900x
GPU: NVIDIA RTX 2070 SUPER
RAM: 32 GB

The console shows following:
[ 137.354834] Service.AM <Info> core\hle\service\am\applets\web_browser.cpp:ExecuteOffline:447: Opening offline document at G:\Switch\Yuzu Early Access\user\cache\offline_web_applet_manual\0100000000010000\html-document\htmlcontents.htdocs\html\EUde\index.html?0?100?101100000000000000000000?0?1
Qt WebEngine ICU data not found at G:/Switch/Yuzu Early Access/resources. Trying parent directory...
Installed Qt WebEngine locales directory not found at location G:/Switch/Yuzu Early Access/translations\qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location G:/Switch/Yuzu Early Access\qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at G:/Switch/Yuzu Early Access/resources. Trying parent directory...
js: Uncaught ReferenceError: end_applet is not defined
js: Uncaught ReferenceError: end_applet is not defined
js: Uncaught ReferenceError: end_applet is not defined
js: The Web Audio autoplay policy will be re-enabled in Chrome 70 (October 2018). Please check that your website is compatible with it. https://goo.gl/7K7WLu

Hope this helps.

https://user-images.githubusercontent.com/70169953/115140479-ca250000-a037-11eb-8cdd-7244cb5ecded.mp4

**Comment by laurens94** [comment]
I encounter the same problem in yuzu 1615 with a wireless Xbox One controller. Reconnecting it with a cable makes the controller usable again.

**Comment by Naii-the-Baf** [comment]
This issue starts on mainline 592. Affects SDL devices, GC and keyboard/mouse are unaffected. I'm looking for a fix

**Comment by german77** [comment]
This regression started in #6201 probably using a different version of SDL

**Comment by neico** [comment]
I've been wondering for a while now why they keep using SDL in Qt builds anyway.
As far as I've seen it's only for controller support, but Qt has an API for that too, which imo is pretty straightforward (which even uses SDL2 internally in certain conditions without the extra implementation burden)
https://doc.qt.io/qt-5/qtgamepad-index.html

Note: I'm aware of SDL being used more for the non-gui build, but that shouldn't matter much for the average end-user, no?

**Comment by german77** [comment]
Works in yuzu 680
