### ISSUE TITLE
Yuzu fails to start due to SDL2

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#6220]
Yuzu fails to start with the error below thrown to console.  This was likely due to PR #6207, which itself was an attempt to resolve an issue related to outdated SDL2 libraries.  @lat9nq thanks for any thoughts here.

`:08:43.839: stderr[#20]: /home/shoegzer/Emulators/Yuzu/yuzu: symbol lookup error: /home/shoegzer/Emulators/Yuzu/yuzu: undefined symbol: SDL_GameControllerGetType`

System specs:

- Linux Mint 20.1, kernel 5.11
- Compiled with gcc 10.2.0
- DS4 controller connected using bluetooth

**Comment by qurious-pixel** [comment]
@Shoegzer If you are building from source, you need SDL2 version 2.0.12 for the `SDL_GameControllerGetType` symbol. The AppImage uses _ppa:cybermax-dexter/sdl2-backport_ which exposes 2.0.12 on Ubuntu Bionic.

**Comment by Shoegzer** [comment]
Unless I'm missing something, the point of the above PR was to avoid the need for 2.0.12 to be separately installed as it pulls 2.0.14 from externals.

**Comment by lat9nq** [comment]
@Shoegzer can you try cleaning your build folder, rebuild, and upload the build log here? I am assuming you are building yuzu, but you did not specify.

I am unable to reproduce this issue in my Linux Mint 20 virtual machine.

**Comment by Shoegzer** [comment]
My apologies @lat9nq, this must have been something on my end that I can't replicate now but after compiling again it's working fine (I assume it's still recommended to compile against yuzu-mainline due to asserts causing crashes with other builds?).  

Many thanks for your help.  Closing this now.

**Comment by Shoegzer** [comment]
Actually I discovered the reason it was failing: the yuzu binary is copied out of the source directory and run from there.  This works as long as the original source directory exists, but if it's deleted or the binary is put on a separate filesystem, yuzu won't start because it can't find `build/lib/ libSDL2-2.0.so.0.14.0`.  What can I do to avoid this?  I was looking for a portable mode in the CMake options but didn't find it.

**Comment by Shoegzer** [comment]
Update: I've tried various methods to get the binary to detect the SDL2 library in a place other than the original source dir but without luck.  I've tried using cmake with `-DCMAKE_INSTALL_PREFIX=<install_dir>` and then avoiding ninja so I could use a traditional make;make install with the prefix set, but I still get the error as I posted above.

@lat9nq thanks for any thoughts you may have here.

**Comment by qurious-pixel** [comment]
Yuzu will continue to fail if the system SDL2 lib is missing the symbols. 

`LD_PRELOAD=/<path to build root>/build/lib/libSDL2-2.0.so.0.14.0 ./yuzu`

Are you placing `libSDL2-2.0.so.0.14.0` in `/usr/local/lib` with a symlink from `libSDL2-2.0.so.0`? 

Yuzu should look in that dir without having to replace system lib.

**Comment by Shoegzer** [comment]
Thanks @qurious-pixel .  I was hoping for a more portable way to do this - for example getting yuzu to recognize libSDL2-2.0.so.0.14.0 in the yuzu path rather than require changes made to the system-wide /usr/local/lib.  Shouldn't there be a way to do that?

Yuzu never required the extra step to install a library before, however prior to recent changes it could use ubuntu's default SDL2 package which as you know is 2.0.10 (outdated).

**Comment by qurious-pixel** [comment]
`patchelf` can be used to set relative path.

`patchelf --set-rpath $ORIGIN/lib/ yuzu`

yuzu will look in the subdirectory `lib` for libraries.

**Comment by Shoegzer** [comment]
Hey thanks @qurious-pixel .  That seems like it should work, but the same result is returned as if the lib directory is deleted from the source tree.  Here's what I do after compiling:
```
$ cp bin/yuzu /home/testing/Yuzu
$ mv lib /home/testing/Yuzu
$ cd /home/testing/Yuzu
$ patchelf --set-rpath $ORIGIN/lib/ yuzu
$ ./yuzu
./yuzu: symbol lookup error: ./yuzu: undefined symbol: SDL_GameControllerGetType
```

**Comment by qurious-pixel** [comment]
Yuzu is looking for `libSDL2-2.0.so.0` in `/home/testing/Yuzu/lib`. If it is not there, it falls back to LD_LIBRARY_PATH (the system lib) and fails without the symbols present in 2.0.12 and above.

`ldd yuzu` should show the path yuzu is looking for the lib.

`mv /home/testing/Yuzu/lib/libSDL2-2.0.so.0.14.0 /home/testing/Yuzu/lib/libSDL2-2.0.so.0`

**Comment by Shoegzer** [comment]
That makes sense, but I've confirmed `libSDL2-2.0.so.0` is symlinked to `libSDL2-2.0.so.0.14.0`, which should also work right?
```
$ cd /home/testing/Yuzu
$ ls -la lib |grep SDL
lrwxrwxrwx 1 testing testing       16 Apr 21 15:11 libSDL2-2.0.so -> libSDL2-2.0.so.0
lrwxrwxrwx 1 testing testing       21 Apr 21 15:11 libSDL2-2.0.so.0 -> libSDL2-2.0.so.0.14.0
-rwxrwxr-x 1 testing testing  2015136 Apr 21 15:11 libSDL2-2.0.so.0.14.0
$ patchelf --set-rpath $ORIGIN/lib/ yuzu
$ ldd yuzu |grep SDL
	libSDL2-2.0.so.0 => /lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007fc031886000)
```

**Comment by qurious-pixel** [comment]
Replace `$ORIGIN` with `.`

`patchelf --set-rpath ./lib:$ORIGIN yuzu`

This should be discussed further on Discord, if necessary.

**Comment by Shoegzer** [comment]
Thanks @qurious-pixel, that did it.
