### ISSUE TITLE
Feature Request: Disk Shader cache RAM saver mode

### ISSUE THREAD

**Issue by phly95** [yuzu-emu/yuzu#6221]
When there are lots of shaders, when loading a game with Disk Shader cache enabled, it can use a lot of RAM. When using transferable shader cache however, one option is to enable disk shader cache to compile the shaders, then disable it on future runs to prevent crashing. Since the shaders are already compiled, this is basically transparent (at least on an NVME SSD), but can reduce ram usage and waiting time.

What this feature could do is just check that all transferrable shaders have already been compiled, but don't load them into RAM on launch.

**Comment by german77** [comment]
Enable the Garbage collector
