### ISSUE TITLE
Yuzu EA build 1631: Ridiculous CPU load while sitting in SSBU character select screen.

### ISSUE THREAD

**Issue by GreyscaleStudios** [yuzu-emu/yuzu#6240]
CPU is being loaded by nothing to go up 20C while only sitting at the menu screen, while CPU usage stays unchanged.
This issue is only present while at the character select screen in Super Smash Brother Ultimate.

Pre character screen temps: 50C
While sitting at the character screen temps: 75C
in game temps: 50C.
CPU usage: stays at 10% 
The reason I think this is extremely odd is Prime95 on max stress test doesn't cause the CPU to reach this temperature.

CPU: Ryzen 9 5900x
GPU: RTX 3080
RAM: 32GB.

**Comment by Marteicos** [comment]
Ryzen 7 5800X here, I have more or less the same temps, the character select screen is quite demanding.

CPU: Ryzen 7 5800X
GPU: GTX 1070
RAM: 32GB

**Comment by GreyscaleStudios** [comment]
> Ryzen 7 5800X here, I have more or less the same temps, the character select screen is quite demanding.
> 
> CPU: Ryzen 7 5800X
> GPU: GTX 1070
> RAM: 32GB

It shouldn't be more demanding than a artificial stress test designed to test CPU stability though. Something weird is definitely going on in the backend.

**Comment by v1993** [comment]
Try changing GPU Accuracy setting between High and Normal. One of them (High IIRC) appears to work better (decrease CPU usage) in menus while another does the same during gameplay.

**Comment by gidoly** [comment]
this should be got better after bcr but it is indeed most demanding area of game. it is nature of game rather than yuzu issue
