### ISSUE TITLE
Opening bag in battle freezes game POKEMON SHIELD

### ISSUE THREAD

**Issue by markusita** [yuzu-emu/yuzu#6249]
since your last update on yuzu
when i am in battle on pokemon shield and i open the bag to pull the poke ball the game freezes and does not start anymore

**Comment by A-w-x** [comment]
is your game on latest update 1.3.1?

this is a bug since at least a month, pokemon update 1.2.x freezes yuzu when you open the bag in battle
i fixed this by updating to latest version

**Comment by G-Spawn** [comment]
Feel free to reopen issue if this still happens to you on newest yuzu version and gpu drivers @markusita
