### ISSUE TITLE
Luigi's Mansion 3 | MULTICORE memory leak

### ISSUE THREAD

**Issue by zero334** [yuzu-emu/yuzu#6251]
-> This issue **only** occurs when MULTICORE is enabled.

Log: [yuzu_log_20210427.txt](https://github.com/yuzu-emu/yuzu/files/6386813/yuzu_log_20210427.txt)
Yuzu Version: 600 | HEAD-mainline-636-5151-gcebacd9bb
CPU: i7-6700K CPU @ 4.00GHz | AVX2 | FMA (base clock)
GPU: Nvidia GTX 970 - Driver v. 466.11 (latest)
RAM: 32 GB 

I've got an **alway** occurring memory leak on Luigi's Mansion 3.
The memory usage of yuzu grows very fast directly after the shader loading phase.
On my system it takes about 30~40 seconds to fill up 12 GB RAM.
Changing the rendering backend (OPENGL / VULKAN), docked / undocked & CPU Accuracy level makes no difference - the leak is still there.

In the log are many failed assertions from:
`video_core\rasterizer_accelerated.cpp:operator ():24`

I had a look at that file in the source code, but I am not entirely sure if this is related to the bug at all..
If I can help somehow to trace the bug down I am more than happy to do so.

![memoryLeak](https://user-images.githubusercontent.com/1432845/116294520-5baf1300-a798-11eb-8d13-8c16d214fe15.png)
_Example image of the memory usage after 45 seconds in the main menu_

**Comment by BSoDGamingYT** [comment]
Use the disable dynamic resolution mod found in the yuzu mod repo to solve this problem temporarily

https://github.com/yuzu-emu/yuzu/wiki/Switch-Mods

**Comment by zero334** [comment]
@BSoDGamingYT Yes, using the dynamic resolution mod solves the problem. 
However I did not find any open or closed issues regarding the memory leak, so I did want to report it (I thought it's unknown).
Thanks for replying - btw. love your work!

**Comment by FernandoS27** [comment]
It's pretty well known, also happens in Splatoon 2.

Sadly, I can't seem to figure why it happens, the game is suppose to run out of guest memory from using those textures, so it should unmap them and trigger all our deletion mechanisms.
