### ISSUE TITLE
SSBU, starting any Mob Smash mode causes guest exception

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#6253]
In Smash Ultimate, trying to start any of the Mob Smash modes in the "Games & More" category will cause the guest to throw a C++ exception and a guest softlock. Brief reproduction steps would be to select a Mob Smash mode, select stage, character, and start the match. It will crash while loading (should see loading hints on screen).

Tested on b096ec68cdbf6f1064a8b6b855489d38c3e59f6a, though this has never worked from what I remember.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6389276/yuzu_log.txt)

**Comment by rubenguip** [comment]
Using version 1226 of yuzu (from today 6 November 2022), Mob smash stays in infinite loading (any of the mob smash modes)

**Comment by TinyCK** [comment]
Yes, same as rubenguip. Mob smash is not work with an infinite loading. Yuzu EA 3708 and 2023 June 25.
