### ISSUE TITLE
Yuzu crash on ubuntu linux 20.04lts

### ISSUE THREAD

**Issue by Jonathanr67** [yuzu-emu/yuzu#6255]
Hi, yuzu crash when i start a game after some second. Music stop and screen freeze. I try mario kart 8 with different rom.
I am on ubuntu 20.04 on a core i7 32 gb ram laptop.

Here the logs :+1: 

` 155.988911] HW.Memory <Error> core/memory.cpp:Write:641: Unmapped Write8 0x00000000 @ 0x00000000068A0018
[ 155.988912] HW.Memory <Error> core/memory.cpp:Write:641: Unmapped Write32 0x00000000 @ 0x00000000068A0014
[ 155.988913] HW.Memory <Error> core/memory.cpp:Write:641: Unmapped Write32 0x00000000 @ 0x00000000068A0010
[ 155.988914] HW.Memory <Error> core/memory.cpp:Write:641: Unmapped Write32 0x00000000 @ 0x00000000068A000C
[ 155.988915] HW.Memory <Error> core/memory.cpp:Write:641: Unmapped Write32 0x00000000 @ 0x00000000068A0008
[ 155.988916] HW.Memory <Error> core/memory.cpp:Write:641: Unmapped Write32 0x00000000 @ 0x00000000068A0004
[ 155.989016] HW.Memory <Error> core/memory.cpp:Write:641: Unmapped Write32 0x00E726D4 @ 0x00000000068A0000
[ 155.989021] HW.Memory <Error> core/memory.cpp:Write:641: Unmapped Write32 0x00000000 @ 0x00000000068A0004
[ 155.989022] HW.Memory <Error> core/memory.cpp:Write:641: Unmapped Write32 0x00000000 @ 0x00000000068A0008
[ 155.989023] HW.Memory <Error> core/memory.cpp:Write:641: Unmapped Write32 0x00000000 @ 0x00000000068A000C
[ 155.989023] HW.Memory <Error> core/memory.cpp:Write:641: Unmapped Write32 `0x00``

`[ 673.788587] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ 0x000770F0
[ 673.797471] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ 0x000770F4
[ 673.806476] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ 0x000770F8
[ 673.815436] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ 0x000770FC
[ 673.824023] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ 0x00077100
[ 673.833119] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ 0x00077104
[ 673.842204] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ 0x00077108
[ 673.851106] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ 0x0007710C
[ 673.859848] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ 0x00077110
[ 673.869130] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ 0x00077114
[ 673.877937] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ 0x00077118
[ 673.886886] HW.Memory <Error> core/memory.cpp:Read:604: Unmapped Read32 @ `0x0007711C``

Thanks

**Comment by gidoly** [comment]
did you installed firmware files?

**Comment by Jonathanr67** [comment]
> did you installed firmware files?

Yes, prod.keys and title.keys in keys file

**Comment by Jonathanr67** [comment]
I can start the game but after some second music and screen freeze

**Comment by gidoly** [comment]
firmware file is not prod.keys and title.keys file

**Comment by gidoly** [comment]
<img width="569" alt="20210428_172446" src="https://user-images.githubusercontent.com/66776795/116371705-ac7d4500-a846-11eb-8ef2-a872e6162bc7.png">

**Comment by Jonathanr67** [comment]
Ok thank you. Will try this

**Comment by Jonathanr67** [comment]
Perferct works fine !
Thank's again

**Comment by lat9nq** [comment]
In the future, please utilize the Support channels that we have, either the Discord or the Citra forums. No need to make issues for support requests.

**Comment by Jonathanr67** [comment]
> In the future, please utilize the Support channels that we have, either the Discord or the Citra forums. No need to make issues for support requests.

ok
