### ISSUE TITLE
Super Mario Odyssey: Orange flickering in Bowser's Kingdom skybox in OpenGL

### ISSUE THREAD

**Issue by Jujumatic** [yuzu-emu/yuzu#6256]
Hello :) this is to report an issue with flickering in Bowser's Kingdom's skybox where an orange glow rapidly appears and disappears on random parts of the sky, made worse by moving the camera around. This is on version 601 of Yuzu but also happened on version 600. Using an Intel 9600KF and an RTX 2060 Super on driver version 466.11, with 16GB of RAM. All you need to do is go to Bowser's Kingdom and look at the skybox, the flickering seems to appear wherever you go in the level, but not indoors. I think it is related to the flame particles that float around while in this level. This only appears when using OpenGL - Vulkan does not have this issue.

Here are attached comparison log files as well as videos.

Vulkan:
Log [yuzu_log VULKAN.txt](https://github.com/yuzu-emu/yuzu/files/6392508/yuzu_log.VULKAN.txt)
Video https://streamable.com/l5a87r

OpenGL (EPILEPSY WARNING):
Log [yuzu_log OPENGL.txt](https://github.com/yuzu-emu/yuzu/files/6392518/yuzu_log.OPENGL.txt)
Video https://streamable.com/up8e57

Please message if you need any more info or clarification!

**Comment by BSoDGamingYT** [comment]
Set GPU accuracy to high...these are flame particles

**Comment by Jujumatic** [comment]
> 
> 
> Set GPU accuracy to high...these are flame particles

This also happened with OpenGL GPU accuracy on high - on Vulkan the issue does not occur whether set on normal or high

**Comment by BSoDGamingYT** [comment]
> > Set GPU accuracy to high...these are flame particles
> 
> This also happened with OpenGL GPU accuracy on high - on Vulkan the issue does not occur whether set on normal or high

Noted. I will alert a dev to this issue

**Comment by gidoly** [comment]
fixed on lastest build

https://github.com/yuzu-emu/yuzu/assets/66776795/cb270f16-982e-49af-89a4-4d43c169bd86
