### ISSUE TITLE
New Pokemon Snap pictures taken are of very low resolution halting game  

### ISSUE THREAD

**Issue by nimbian** [yuzu-emu/yuzu#6260]
![yuzu](https://user-images.githubusercontent.com/3602942/116558121-1b9d7c80-a8cd-11eb-8697-578d2f4d88b4.png)
I have tried a multitude of versions both stable and EA 1637 1638 and 1639.  All result in the same issue.  As you can see the picture is graining and results in the pokemon not being detected.  I've talked with people on discord and reddit who are dealing with the same result.  A handful of individuals noted running VULKAN API works.  I did not have any luck with this.  Today I tried adjusting the accuracy level and I was able to get my first detection when set to EXTREME unfortunately it only detected one of the pokemon and the pictures were of very low resolution.

I'm currently working on trouble shooting this and will post any additional findings.

**Comment by BSoDGamingYT** [comment]
Piracy is not supported by the yuzu project or team, Closing
