### ISSUE TITLE
New Pokemon Snap crashes after finishing first jungle level

### ISSUE THREAD

**Issue by Legacyy2k21** [yuzu-emu/yuzu#6271]
EAD-early-access-0-1591-141-gc6ee4a11e
RTX 3060Ti, i5 10600k
Geforce Driver 466.27

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6411393/yuzu_log.txt)

**Comment by Daniz0r** [comment]
I have the same problem as well I have tried 4 times finishing first jungle level and 4 times crashes, I give up

**Comment by Arnocaster** [comment]
Hello same for me, i solved It by using Vulkan.

**Comment by Legacyy2k21** [comment]
Tried Vulkan, works fine.
Seems only an issue with openGL

**Comment by Daniz0r** [comment]
> Tried Vulkan, works fine.
> Seems only an issue with openGL

I just traid vulkan and crashes again omg a dont know what I need to do

**Comment by myeroph** [comment]
I tried Vulkan still crashes on second playthrough (level 2) during teleportal usage

GTX 970
i7-4790k

**Comment by myeroph** [comment]
Ok using Yuzu 607 and this time it got past the 2nd run of the jungle AND the nightime outing but crashed during the illumina encounter.

**Comment by ShauryaGupta27** [comment]
@Legacyy2k21 This issue is fixed now, if you haven't noticed yet!
