### ISSUE TITLE
New Pokemon Snap Crash After First Illumina Mission

### ISSUE THREAD

**Issue by HaroPla** [yuzu-emu/yuzu#6273]
Yuzu Version: yuzu Early Access 1648 | HEAD-early-access-0-1591-141-gc6ee4a11e
System: Ryzen 5 3600, RTX 2060
GeForce Driver: 466.27

Tried 10 times, all resulting in crashes.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6411521/yuzu_log.txt)

**Comment by Weirdyy1** [comment]
for me it didn't crash, maybe yuzu fix it do it again and test that yuzu fix it

**Comment by Weirdyy1** [comment]
try vulkan

**Comment by Weirdyy1** [comment]
> Yuzu Version: yuzu Early Access 1648 | HEAD-early-access-0-1591-141-gc6ee4a11e
> System: Ryzen 5 3600, RTX 2060
> GeForce Driver: 466.27
> 
> Tried 10 times, all resulting in crashes.
> [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6411521/yuzu_log.txt)

try vulkan to see if it not going to crash

**Comment by myeroph** [comment]
I tried Vulkan still crashes on second playthrough (level 2) during teleportal usage

GTX 970
i7-4790k

**Comment by jobins1492** [comment]
Is it fixed? If not if you are using OpenGL, don't turn accuracy higher than High.

**Comment by german77** [comment]
It doesn't crash on yuzu 680
