### ISSUE TITLE
Partial Pokemon Snap detection in EA-1644 onward

### ISSUE THREAD

**Issue by dazemc** [yuzu-emu/yuzu#6276]
Autosave was fixed in EA-1644 but detection has become partially broken. 
Tutorial no longer detects Vivillon and a few other Pokemon that are in the Park.
I tested this on Build 605, EA-1650, EA-1651, EA-1644 and EA-1643. 
Vivillon and all other Pokemon were detected on EA-1643

I'm using OpenGL with Assembly Shaders on and Accuracy set to High in all tests

EA-1645 Log Aattached

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6412579/yuzu_log.txt)

**Comment by gelson-zord** [comment]
Finally I got pass the Vivillon detection! Although my emulator settings were as recommended (OpenGL on High / Vulkan on Extreme accuracy, CPU on accurate, and every option checked) I kept getting that error where Vivillon detection fails, the way to pass is, you need to wait for the pointer to recognize the pokémon as Vivillion, and then you have to take the picture when Vivillon is facing the camera.

Tested on Yuzu EA 1654.

**Comment by dazemc** [comment]
> Finally I got pass the Vivillon detection! Although my emulator settings were as recommended (OpenGL on High / Vulkan on Extreme accuracy, CPU on accurate, and every option checked) I kept getting that error where Vivillon detection fails, the way to pass is, you need to wait for the pointer to recognize the pokémon as Vivillion, and then you have to take the picture when Vivillon is facing the camera.
> 
> Tested on Yuzu EA 1654.

That is a workaround and not how the game normally operates. Also does not fix the numerous photos that do not get detected throughout the Park. Some get detected and others that should, do not. The same photos on my brother's switch detect those Pokemon, while this does not. 

I wouldn't have posted this if I hadn't done all my available research first. There are other users experiencing the same issue as well

[https://www.reddit.com/r/yuzu/comments/n2mscj/comment/gwmqbgl]()

**Comment by HiDe-Techno-Tips** [comment]
[Heres](https://github.com/yuzu-emu/yuzu/issues/6850) one more issue with Pokemon Snap that I reproduced apart from this.
Can you reproduce it as well?

**Comment by dazemc** [comment]
Yes, I also found that the "size" score remains a constant score of "1214"

**Comment by OZtistic** [comment]
I cannot reproduce this with current EA
Use OpenGL - GLSL in the appropriate Render settings

**Comment by HiDe-Techno-Tips** [comment]
> Yes, I also found that the "size" score remains a constant score of "1214"

Try using High GPU accuracy.

**Comment by HiDe-Techno-Tips** [comment]
I cannot reproduce this as well. I am using Vulkan with high GPU accuracy.

**Comment by CarrionXR** [comment]
Checking in March 2022, the vivillion detection issues are still present in the tutorial. I'm trying to get the perfect capture as people have said is a workaround, but this isn't the easiest task.

**Comment by dazemc** [comment]
They are most likely not to fix the issue. It seems to be a game specific issue. I had previously identified the issue started with the patch that fixed the game saving correctly. So basically your options are to run a build that will never save or a build that will never identify the Pokemon correctly. Even if you get pass the Vivillion detection you will notice that the "Size" category in your score will be maxed out at acertian point. I also found that not all Pokemon will get detected anyways. I hope they fix it but unfortunately the only other options are not emulating or using the emulator which we won't name instead.

**Comment by CarrionXR** [comment]
Well,  good to know. For what it's worth I did achieve a perfect picture, and the issues persisted.

**Comment by v1993** [comment]
FWIW, this is a perfectly valid issue, and as such will eventually be fixed. It's just that fixing singular issues is often impossible (e.g. when issue is caused by an incorrect assumption made during design stage, meaning that entirely new approach is required) and bigger reworks (which are underway) are required.

**Comment by gidoly** [comment]
should fix on last ea and mainline feel free to reopen if it still happens
