### ISSUE TITLE
On crash latest log entry not printed

### ISSUE THREAD

**Issue by mailwl** [yuzu-emu/yuzu#628]
Latest log entry right before crash doesn't prints at all

**Comment by Hexagon12** [comment]
These bugs are solved if the qt-config.ini file is regenerated.

**Comment by Hexagon12** [comment]
This only happens when debugging in Visual Studio, running Yuzu normally prints out the assertions fine.

**Comment by Hexagon12** [comment]
Is this fixed? Visual Studio should properly log and print the very last log line in the Output tab,
