### ISSUE TITLE
Pokemon Snap crashes after completing a level

### ISSUE THREAD

**Issue by ShauryaGupta27** [yuzu-emu/yuzu#6280]
The problem occurs on both pressing + and quitting and on using the teleporter

**Comment by ShauryaGupta27** [comment]
This problem isn't related to any particular level, it can occur on any level.
It occurs on Nvidia and Intel's OpenGL and Vulkan.
It can occur on both Preview and Mainline Versions...

Please fix this

**Comment by myeroph** [comment]
Yeah I can play like one level then the following level crashes at the end teleportal

**Comment by ShauryaGupta27** [comment]
Even that's a problem with me, it is more like it may or may not crash but it mostly does

**Comment by darknessblade** [comment]
does it happen every level? or once in a while?

Maybe give some system specs

**Comment by ShauryaGupta27** [comment]
Fixed in the latest EA(1960) as per the patchnotes on discord, and I cross checked with a friend too!

Closing the Issue
