### ISSUE TITLE
New Pokemon Snap Crashes on opening Photodex

### ISSUE THREAD

**Issue by ShauryaGupta27** [yuzu-emu/yuzu#6285]
As soon as you open Photodex(in the Lab) you find, that after few seconds, before you can open a Pokemon's Page, the game will crash

Log-https://drive.google.com/file/d/1506nW7WOt9aFnVMPizlYWZRKfkz4e2hG/view?usp=sharing

**Comment by G-Spawn** [comment]
Would you please provide a log, like the create new issue template asks for?

**Comment by ShauryaGupta27** [comment]
https://drive.google.com/file/d/1506nW7WOt9aFnVMPizlYWZRKfkz4e2hG/view?usp=sharing
@G-Spawn

**Comment by darknessblade** [comment]
Regarding the crashing:
"New pokemon snap" also crashes once in a while when starting or leaving a cutscene, 
restarting the game "fixes" it.
sometimes it crashes on loading the level. though other times it is just fine.
-------------
Currently i do not have any logs.  as i did not know yuzu clears the log upon restart.
as it happens at random i cannot know when it happens again.
-----------

**Comment by darknessblade** [comment]
Link for the latest crash i had:
https://drive.google.com/file/d/1MZj2JsBBwONYPkZP2rzayZbfbksyn5eX/view?usp=sharing
-----------------
system specs:
-Ryzen 9 5900x
-32GB memory [running at 3200mhz]
-RX6800xt
-------------------
the Radeon/AMD  video card driver/software also gave a driver timeout. it could be a issue with the Vulcan encoding.
The issue happened on the loading screen of the meganium stage after completion [after getting the orbs].

Ram usage during gameplay was around 6-10GB
-Smart access memory is enabled

**Comment by ShauryaGupta27** [comment]
Thanks for fixing the issue, I can now open the Photodex and it doesn't crash!

Closing the Issue
