### ISSUE TITLE
pokemon sword can noat be rendered

### ISSUE THREAD

**Issue by Devgulani** [yuzu-emu/yuzu#6311]
it is just black and white in languge select page.

**Comment by OZtistic** [comment]
Excellent description
With no context
Please forward you questions to the official discord (you will see an avi link to discord on the yuzu main site - above all the main body text - at the top of your window to the right)
please ask there
Shield does not have issues, unless you haven't updated your GPU drivers in a century

**Comment by lat9nq** [comment]
Please accurately describe the issue you are having and provide the resources we require when making Issues. Without accurately describing the issue, without providing any log file, or _at least_ providing the specifications for the environment you are running yuzu in, there is nothing that we can do about this.

If this is a support request, please make use of our support channels and close this Issue. GitHub already linked you to both the [Discord Server](https://discord.gg/u77vRWY) and the [Citra Support Forums](https://community.citra-emu.org/) before you started writing this Issue.

**Comment by ameerj** [comment]
Closing as the author did not provide meaningful details, and the game is known not to have "black and white" rendering issues.
