### ISSUE TITLE
Game crash in 622 that wasn't previously present 

### ISSUE THREAD

**Issue by BFCE** [yuzu-emu/yuzu#6314]
Upon completion of a cutscene in 五等分の花嫁∬　～夏の思い出も五等分～, the game will crash with the following output:
```

[ 115.093022] Service.NVDRV <Info> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:OnClose:69: NVDEC video stream ended
[ 115.097507] Debug <Critical> audio_core\stream.cpp:operator ():51: Assertion Failed!
Unimplemented code!
```
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6483332/yuzu_log.txt)
Changing backends or emulation accuracy doesn't change behavior. As stated, the game ran fine on previous versions.

**Comment by Mynameisthom1** [comment]
same error for me 
game : acnh 
after the plane take off there is a video and the game crash

**Comment by gidoly** [comment]
can you test it again?

**Comment by gidoly** [comment]
close as no response from user
