### ISSUE TITLE
sporadic emulator panic on yuzu 623 (tested with BotW)

### ISSUE THREAD

**Issue by WarpspeedSCP** [yuzu-emu/yuzu#6315]
Here's the log starting from when I launched the game from the ui:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6488148/yuzu_log.txt)

Yuzu version as seen in the about header: HEAD-mainline-636-5293-g4facd7650
This issue seems like a race condition of some kind... It tends to happen pretty randomly after about 10 - 15 minutes.

My specifications:

Intel i5 7200U
Geforce 940MX
12GB of RAM

This has happened both in windows and linux, but the logs are from windows alone.

**Comment by G-Spawn** [comment]
Try to update your gpu drivers and consider following the settings Bsod - the Discord refer to in their pinned settings https://youtu.be/93xsKERji60
