### ISSUE TITLE
"we discourage users installing base games to nand"

### ISSUE THREAD

**Issue by sebpn** [yuzu-emu/yuzu#6329]
Hi, I'm getting this error when trying to install anything from either NSP to XCI. This didn't happen before last update, maybe there's something wrong from your side. And, anyway, how could I override your discouragement since I know what i'm doing?

**Comment by v1993** [comment]
Why are you installing base game to NAND anyways? This is known to cause issues and doesn't really have any benefits, thus this was disabled. You can extract game files with yuzu for purposes of e.g. modding without installing base game.

**Comment by german77** [comment]
Unless you are installing an update or DLC, base games shouldn't be installed to NAND. You should add base games to the game folder directory. Having games in a folder adds more flexibility without affecting performance or loading times.

**Comment by sebpn** [comment]
where should i put the NSP files then? 

anyway why would you change this from one release to another without warning? or at least leaving an option to disable this discouragement?

**Comment by G-Spawn** [comment]
Re read what german just said. Base game nsp/xci's go into a game directory, updates - dlc go to nand.

**Comment by G-Spawn** [comment]
Likely better to solve the issue with a broad stroke than leaving it as a toggle-able option for users to dig themselves into a hole.

**Comment by sebpn** [comment]
i don't see any game directory

**Comment by sebpn** [comment]
![image](https://user-images.githubusercontent.com/83230362/118512852-28113a00-b701-11eb-9d7a-d719ef53ca8b.png)

**Comment by G-Spawn** [comment]
Please just join the discord this is beyond the responsibilities of this issue tracker

**Comment by sebpn** [comment]
ok sorry

**Comment by BSoDGamingYT** [comment]
As was stated previously, please use the official discord for such questions/requests. https://discord.gg/u77vRWY
