### ISSUE TITLE
how can i disable auto update and/or install a specific version?

### ISSUE THREAD

**Issue by sebpn** [yuzu-emu/yuzu#6330]
Hi. I want to disable auto update and be able to install a specific version of the emulator, whenever I find one that works perfectly fine for me, which was the case on the last version before it auto updated.

How can I achieve this?

**Comment by G-Spawn** [comment]
By relying on the yuzu.exe manually called in the local appdata yuzu folder. This is an issue tracker for the emulator not general support. Please consider joining the discord for further assistance.

**Comment by sebpn** [comment]
thank you and i'm sorry, but could yo tell me how to go back to another version?

**Comment by G-Spawn** [comment]
If you're using mainline there is an entire page of releases at your disposal https://github.com/yuzu-emu/yuzu-mainline/releases. For early access you're expected to backup your given versions since its a subscription that eventually runs out if you don't pay monthly and the versions constantly update.

**Comment by G-Spawn** [comment]
Downgrading versions doesn't change the fact you shouldn't install base games to nand, btw.

**Comment by BSoDGamingYT** [comment]
> Hi. I want to disable auto update and be able to install a specific version of the emulator, whenever I find one that works perfectly fine for me, which was the case on the last version before it auto updated.
> 
> How can I achieve this?

Please do not use github for these types of questions. This is not what it is for. If you have questions on emulator usage, feel free to join the official discord:  https://discord.gg/u77vRWY
