### ISSUE TITLE
Miitopia Demo hangs when attempting to "create a Mii from scratch"

### ISSUE THREAD

**Issue by assignmentchampionship** [yuzu-emu/yuzu#6335]
It just stays on the orange/yellow screen.

**Comment by OZtistic** [comment]
Please follow the requested format when submitting a ticket
The devs want to see logs, screenshots etc as well as your system specs etc
(everything that is asked for in the issue template)
making tickets like this makes it hard to fix anything with no information, and kind of fills up the issue list with empty submissions

**Comment by KingGamingYT** [comment]
The game hangs because Yuzu is unable to create miis as of this time. You'd need to have a preexisting save file for it to work.

**Comment by gegegegel974** [comment]
comment faire un fichier de sauvegarde préexistant

**Comment by gegegegel974** [comment]
> Le jeu se bloque car Yuzu est incapable de créer des miis à partir de ce moment. Vous auriez besoin d'un fichier de sauvegarde préexistant pour que cela fonctionne.

comment faire

**Comment by german77** [comment]
Closing in favour of #6429
