### ISSUE TITLE
World's End Club Demo Lighting/Shimmering glitch when pushing a box.

### ISSUE THREAD

**Issue by assignmentchampionship** [yuzu-emu/yuzu#6336]
Some effect, screen flare (?) isn't being emulated properly. Possible other locations as-well. But it's definitely noticeable when pushing the block in that one area.

**Comment by OZtistic** [comment]
Please follow the requested format when submitting a ticket
The devs want to see logs, screenshots etc as well as your system specs etc
(everything that is asked for in the issue template)
making tickets like this makes it hard to fix anything with no information, and kind of fills up the issue list with empty submissions
