### ISSUE TITLE
LAYTON’S MYSTERY JOURNEY - make that game work!

### ISSUE THREAD

**Issue by DocMAX** [yuzu-emu/yuzu#6350]
As explained in https://github.com/yuzu-emu/yuzu/issues/4045 i would like to see
LAYTON’S MYSTERY JOURNEY
fully working.

Currently the game has lots of issues.
Thank you!

**Comment by BSoDGamingYT** [comment]
Please do not abuse issues like this. If you wish to create a new issue, including the issues a game encounters, please do so.
