### ISSUE TITLE
Captain Toad: Treasure Tracker ‘Spinwheel Cog Ruins’ (Episode 2-10) | Missing background

### ISSUE THREAD

**Issue by FanderWasTaken** [yuzu-emu/yuzu#6359]
### Yuzu version: EA 1707, Vulkan backend
**PC: Ryzen 5 1600, RX 570 4GB, 8GB RAM, Windows 10.**

When loading the level 10 of 2nd episode there is no background:

![yuzu](https://user-images.githubusercontent.com/48799496/119538382-1cc2ac00-bd9c-11eb-9813-3afcfea1dd02.jpg)

This is what it should look like:

![cttt_2_10__0006_Layer_3](https://user-images.githubusercontent.com/48799496/119539115-e5a0ca80-bd9c-11eb-931e-1c2d19d33ace.jpg)

Log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6541046/yuzu_log.txt)
Save file: [GameData.zip](https://github.com/yuzu-emu/yuzu/files/6541050/GameData.zip)

**Comment by G-Spawn** [comment]
This issue should be corrected on latest yuzu - amd drivers. Please reopen if it still happens.
