### ISSUE TITLE
only one joycon vibrating in Fitness Boxing 2: Rhythm & Exercise

### ISSUE THREAD

**Issue by taifengdian** [yuzu-emu/yuzu#6363]
Fitness Boxing is a favorite game for me. Yuzu can almost run it without much bugs.
but there is a problem boring me a lot. 
when i punch the joycon should give me  a vibrate to feed back, like left hand punch left joycon vibrate and  right hand punch right joycon vibrate .
But now is always left hand joycon vibrate, no matter which hand I punched.   
I would appreciate it if this problem could be corrected.
Thanks a lots.

**Comment by german77** [comment]
Do you mind giving me info on your controller config.

**Comment by taifengdian** [comment]
of course, What shall I do?

**Comment by german77** [comment]
A screen capture of the current controller config. If you can give me the control section of %appdata%/yuzu/config/qt-config.ini beware that other sections might contain data that you might not want to share online

**Comment by taifengdian** [comment]
ok,ignore the input device and motion 1 and motion 2 selection, because I was remote my home's computer to capture the screen, so I can't connect the joycon right now.
![2021-05-26 125814](https://user-images.githubusercontent.com/83751474/119604702-1d9e2100-be22-11eb-9776-ed5dae4e84ed.png)

**Comment by taifengdian** [comment]
[qt-config - contorl.txt](https://github.com/yuzu-emu/yuzu/files/6543949/qt-config.-.contorl.txt)

**Comment by taifengdian** [comment]
@german77 just try the new version include native dual joycon support ,it perfect! the motion and the vibrate all great! thanks for the perfect work!
