### ISSUE TITLE
[Feature Request] Support for building with gcc-11

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#6380]
Currently conan only supports gcc-10 and below by default, which causes the yuzu build process to fail since it relies on conan.  Attempts to build yuzu on this test system resulted in failure as noted in the log below.

This can be resolved by hand-editing `~/.conan/settings.yml` to add "11" and "11.1" to the gcc section, however the build itself eventually fails (build log is [here](https://pastebin.com/8eKY1jC0)).  At this point I'm not sure if it's possible to compile yuzu on systems that have upgraded to gcc-11 to meet the needs of other projects that now require it.
```
=11 -s compiler.libcxx=libstdc++11 -g=cmake -g=cmake_find_package_multi -g=cmake --build=missing
ERROR: Invalid setting '11' is not a valid 'settings.compiler.version' value.
Possible values are ['10', '10.1', '4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '6.5', '7', '7.1', '7.2', '7.3', '7.4', '7.5', '8', '8.1', '8.2', '8.3', '8.4', '9', '9.1', '9.2', '9.3']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
CMake Error at build/conan.cmake:402 (message):
  Conan install failed='1'
```

**Comment by lat9nq** [comment]
Please post the actual build error. What you have posted is an issue with Conan, not yuzu.

**Comment by Shoegzer** [comment]
Thanks, posted above.  I thought I had done that but apparently not.

**Comment by lat9nq** [comment]
This is either a bug in Qt or a bug in GCC, not a yuzu issue.

Apparently it's fixed upstream in Qt (https://codereview.qt-project.org/c/qt/qtbase/+/339417), but I'm not sure if Qt is willing to backport this change to 5.15.2. On my own machine, I manually applied the change to `/usr/include/qt/QtConcurrent/qtconcurrentthreadengine.h`.

**Comment by Shoegzer** [comment]
Thanks @lat9nq.  Applying the change works, though it had to be applied to two Qt5 configs as there are more than one on this system (5.12 from stock Ubuntu repo and 5.15 from PPA).

There doesn't seem to be a way to force conan to recognize newly-supported gcc versions via commandline somewhere in the yuzu build process unless you know of a way?  Otherwise `~/.conan/settings.yml` will need to be hand-edited whenever gcc is updated, and I'm not even sure new gcc versions would be added to that file when conan itself is updated.

Unless there's any other comments beyond that, I'll close this issue (and thanks for your help).

**Comment by lat9nq** [comment]
> There doesn't seem to be a way to force conan to recognize newly-supported gcc versions via commandline somewhere in the yuzu build process unless you know of a way?

I'm not aware of anything like that. Conan will eventually update it, but for now you just have to edit the settings.yml. It should only need to be done once.

**Comment by Shoegzer** [comment]
Once per update anyway.  When gcc 11.2 is released it would have to be done again.  My point being the way conan accounts for changes like this is suboptimal, but if there's no way around it then we'll have to accept it.  Thanks for your thoughts.  I'm closing this issue now.
