### ISSUE TITLE
Link's awakening crash after take conch horn

### ISSUE THREAD

**Issue by Alfinnete** [yuzu-emu/yuzu#6390]
![01](https://user-images.githubusercontent.com/19777804/120101729-d5327c00-c11d-11eb-81d0-d04404ec316d.jpg)
![02](https://user-images.githubusercontent.com/19777804/120101731-d663a900-c11d-11eb-905d-58ca2380424e.jpg)

Hey, guys. I have a problem with the game not loading as soon as I get the conch horn. The transition screen out of the cave is white, does not load and the emulator closes.

**Comment by G-Spawn** [comment]
Would you mind providing a log file like the create new issue template asks for and as well a  save file in your post so we can try to replicate the issue? (Right click the game open save dir and zip the save file contents and upload here when you can)

**Comment by G-Spawn** [comment]
Logs are located in %appdata%\yuzu\log\ if you don't mind providing that as well.

**Comment by Alfinnete** [comment]
> Logs are located in %appdata%\yuzu\log\ if you don't mind providing that as well.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6566214/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6566215/yuzu_log.txt.old.txt)

**Comment by G-Spawn** [comment]
Try with mods disabled. For whatever reason you applied an acnh ultrawide mode to ZLA.

**Comment by BSoDGamingYT** [comment]
I cant reproduce this on an nvidia GPU based system. Does this crash happen every time you get to the part of the game, or was it just a random once off crash?

**Comment by Alfinnete** [comment]
> Try with mods disabled. For whatever reason you applied an acnh ultrawide mod to ZLA.

I remove UWide and all fine now! Ty!

**Comment by G-Spawn** [comment]
np. Glad that fixed it :p
