### ISSUE TITLE
World's End Club lightning glitches

### ISSUE THREAD

**Issue by Tharag21** [yuzu-emu/yuzu#6391]
[WEC.docx](https://github.com/yuzu-emu/yuzu/files/6566390/WEC.docx)

The game gets huge lightning glitches on both OpenGL and Vulkan
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6566400/yuzu_log.txt)

**Comment by G-Spawn** [comment]
They don't support piracy here fwiw.
