### ISSUE TITLE
Dokapon UP! Mugen no Roulette (Endless Roulette) non render on multiplayer select window - rest of the game is flawless

### ISSUE THREAD

**Issue by biccdaddy** [yuzu-emu/yuzu#6399]
the multiplayer game window (second option does not render)

https://i.imgur.com/0MhXAp2.png Screencap of white non rendering window

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6580598/yuzu_log.2.txt)

**Comment by SilencieuxToast** [comment]
Seems to still be a problem on version 107 
 To replicate just chose singleplayer or offline mode (top 2 options) and they will not load 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9050934/yuzu_log.txt)
6

**Comment by liamwhite** [comment]
Is this fixed by #9703?

**Comment by SilencieuxToast** [comment]
Yes, It's working as of Yuzu 1327 on Vulkan and OpenGl with normal Gpu accuracy on both.

**Comment by liamwhite** [comment]
Glad to hear, thanks!
