### ISSUE TITLE
Feature Request: Double click to enter / exit fullscreen

### ISSUE THREAD

**Issue by darksaboteur** [yuzu-emu/yuzu#6417]
Using a PS4 controller for Yuzu it is impossible to toggle in and out of fullscreen.
It would be great if it supported double clicking anywhere in the game window to toggle fullscreen as the touchpad on the DS4 functions as a mouse.
RPCS3 has this functionality and is what inspired this request

**Comment by BSoDGamingYT** [comment]
This cant be added to the emulator, as many games require a double touchscreen input for gameplay. Instead use the F11 hotkey, or remap it to a key of your liking

**Comment by Jatoxo** [comment]
> This cant be added to the emulator, as many games require a double touchscreen input for gameplay. Instead use the F11 hotkey, or remap it to a key of your liking

If there is a way to disable touch, you could enable this gesture when touch is disabled

**Comment by Morph1984** [comment]
As mentioned by @BSoDGamingYT, this feature cannot be added to the emulator since touch, a feature of the Nintendo Switch, will not be disabled for this functionality.
