### ISSUE TITLE
Yuzu crash Randomly on version 646

### ISSUE THREAD

**Issue by ChrisM20** [yuzu-emu/yuzu#6427]
I realized that soon after the game yuzu stops closing randomly, I tried without doing anything when entering Pokémon sword and it stopped 2 times in less than a minute, another time it took a little longer.  It happens since version 645 although I'm not sure.
Intel i5 2450m
Nvidia geforce 540m 1gb
Windows 10 pro 21H1

Update:
Currently in the 647 the image freezes but the sound continues and remains like that all the time

**Comment by Zienack** [comment]
to com o mesmo problema, meu yuzu fecha sozinho ao entrar no pokemon shield alguns minutos dps na versão647

**Comment by bunnei** [comment]
Should be fixed by #6428, feel free to reopen if latest mainline 648+ still has this issue
