### ISSUE TITLE
Miitopia: game works perfectly (as far as I've tested it anyway), but requires existing save/Mii data

### ISSUE THREAD

**Issue by ElBiggus** [yuzu-emu/yuzu#6429]
Managed to get Miitopia working by dumping some Mii data and a save from an existing game, and as far as I can tell as long as you stay away from any Mii customisation the game works perfectly - no graphical or audio glitches, good performance, etc. - so as a feature request, implementation of whatever is missing to enable Mii creation (or even random generation of a bunch of Miis would probably do as a stop-gap).

**Comment by OZtistic** [comment]
A Mii editor is planned in the future. An App interface needs to be made for it

**Comment by german77** [comment]
We don't require a save file since yuzu now generates a default mii.
