### ISSUE TITLE
Games only render half of the screen on Intel cards

### ISSUE THREAD

**Issue by Hexagon12** [yuzu-emu/yuzu#643]
Tested both with the latest Nightly and Canary.

Games tend to only show half of the screen on Intel HD Graphics cards. I'm currently using Intel HD Graphics 530 with the driver version 24.20.100.6136 (which is the latest driver). I did not have this issue with a Nvidia GeForce GTX 750 Ti card. Screenshot:

![fiksavimas](https://user-images.githubusercontent.com/25362478/42468862-b477f3c2-83be-11e8-97d9-6f2868f5f6b0.PNG)

**Comment by greggameplayer** [comment]
@Hexagon12 it's not the latest driver the latest driver is 24.20.100.6229

**Comment by Hexagon12** [comment]
This issue is related to Intel's drivers. If you rollback to drivers which do not support OpenGL 4.5, this issue shouldn't happen. The best solution would be to contact Intel in some way to report this bug.
