### ISSUE TITLE
Pokemon shield Assertion Failed! error

### ISSUE THREAD

**Issue by MrDark0o0** [yuzu-emu/yuzu#6432]
The problem started with yuzu's update to 647, the game lunches fine but after loading in for about 5 minutes the game freezes suddenly always at a random point.

I tried using Vulcan and openGL the same eror 

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6618766/yuzu_log.txt.old.txt)

**Comment by ChrisM20** [comment]
I think it was already solved in 648, I am testing in pokemon sword and it has not frozen since it happened instantly but right now I could play a while and it has not happened

**Comment by bunnei** [comment]
Should be fixed in 648 by PR #6428. Please let us know if you still have this issue.
