### ISSUE TITLE
Yuzu Crashes while playing Pokemon shield using Vulcan & OpenGL.

### ISSUE THREAD

**Issue by MrDark0o0** [yuzu-emu/yuzu#6437]
I'm using yuzu version 648

the game runs normally but after playing for sometime yuzu freezes and then close down.
the time i got before crashing varies a lot some times i get 1/2 an hour other times i can't play for 5 min
[yuzu_log-Valcan.txt](https://github.com/yuzu-emu/yuzu/files/6623686/yuzu_log-Valcan.txt)
[yuzu_log-OpenGL.txt](https://github.com/yuzu-emu/yuzu/files/6623687/yuzu_log-OpenGL.txt)

**Comment by BSoDGamingYT** [comment]
It is not advised to use async shaders for this title. Please try without

**Comment by MrDark0o0** [comment]
still dies after playing for 20 minutes
[yuzu_log-Vulcan-2.txt](https://github.com/yuzu-emu/yuzu/files/6623922/yuzu_log-Vulcan-2.txt)

**Comment by XInflict** [comment]
Have you tried without the 60 FPS mod?

I'm having the exact oposite problem with 648. It is the most stable built for my system, the game rolls for almost 5h non stop, with some stutter now and then, but it stabilizes.

Windows10
I7 3770
RX 5600XT
12GB

Maybe we can find a way to make it work! 

PS: On the 649 build it breaks out again, I manage to play like 30 min before it crash.
PS2: If you want some file from my system just ask, I'm kind new here!

**Comment by MrDark0o0** [comment]
tried it again with version 649 
yuzu is the one that crashed this time
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6626342/yuzu_log.txt.old.txt)

**Comment by XInflict** [comment]
I read one thing about a RAM leak on yuzu when using Vulkan API, that sucks your RAM all the way up until the emulator eventualy crashes. The only change I have made is that I expanded my Page Memory on the Windows System configuration, maybe that solved the issue. I went from 20GB to 170GB. Maybe you could give it a shot.

**Comment by MrDark0o0** [comment]
Yuzu now crashes instantly in 651 but it gives an error

[ 200.860313] Debug <Critical> common\fiber.cpp:operator ():95: Assertion Failed!
Destroying a fiber that's still running

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6630912/yuzu_log.txt)

**Comment by MrDark0o0** [comment]
As of version 654, I was able to run the game for an hour without crashing

**Comment by bunnei** [comment]
This can still happen in latest master

**Comment by lKobi** [comment]
Still happening on yuzu 1080, it only started happening when I reached Route 6.

**Comment by gidoly** [comment]
duplicate sw sh multicore crash issue thread
