### ISSUE TITLE
Pokemon Snap: Score calculation is broken

### ISSUE THREAD

**Issue by reggermont** [yuzu-emu/yuzu#6447]
Since the beginning I'm playing Pokemon Snap from Yuzu, I really felt like the score calculation of pictures is broken. 

I made some tests on EA1776 and now I'm really sure it is

Here is a basic example of what I'm talking about (sorry for French texts)
![image](https://user-images.githubusercontent.com/14902909/121612045-ea7ea300-ca59-11eb-9455-4404d725c3e7.png)
![image](https://user-images.githubusercontent.com/14902909/121612090-01bd9080-ca5a-11eb-9879-f82238ecae11.png)
![image](https://user-images.githubusercontent.com/14902909/121612152-1bf76e80-ca5a-11eb-8308-b30be779f4a2.png)

For the stats:
- **Pose** seems to work well (really dunno how it works anyway)
- **Size** is the main issue here. You can see that a Wingull far from me get the same score (1214) than a very close Pikachu and Octillery
- **Direction, Placement, Other Pokémon** and **Background** seems ok

Here are the logs generated: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6634965/yuzu_log.txt)

FYI, I have more examples and I can provide you more if needed :smile:

Specs:
- Nvidia GeForce 1070
- Intel i7-9700K

Config:
- Pokemon Snap Version: 1.2.0
- CPU Accuracy: Accurate & Unsafe (tried both)
- Graphics API: OpenGL
- Graphics Accuracy Level: High

**Comment by HiDe-Techno-Tips** [comment]
Check my issue about Pokemon Snap [here](https://github.com/yuzu-emu/yuzu/issues/6850).
Can you reproduce this as well?

**Comment by pacoa-kdbg** [comment]
Hi @reggermont 
Is this issue still going on on the latest yuzu version ?

Thanks

**Comment by reggermont** [comment]
Can't check right now, will try tomorrow

**Comment by reggermont** [comment]
Confirm it's fixed on latest EA (2948)

Tried an exploration and I have better values

![image](https://user-images.githubusercontent.com/14902909/190153386-a9c0c4a1-7e2a-436b-845a-2b85db476e7e.png)
![image](https://user-images.githubusercontent.com/14902909/190153399-d239deb0-4fca-47c0-9c78-f6a29c85106c.png)
![image](https://user-images.githubusercontent.com/14902909/190153419-c7483306-42c6-4853-8669-0439868a3c2e.png)

You see that all previous **Size** values were at `1214` points, and now they are more accurate

Even the very far Wingull has a very bad **Size** score 😄

Closing this issue
