### ISSUE TITLE
Crash on Super Smash Bros. Ultimate

### ISSUE THREAD

**Issue by lizardguts73** [yuzu-emu/yuzu#6449]
When I encountered villager as a new fighter it got stuck on his loading screen for around 5-10 minutes then crashed.

Specs: 
Ryzen 9 3950x
16GB Ram 3600mhz
GTX 1060 6GB
Windows 10 Pro 64-bit
Running Yuzu 654

Smash Ultimate had all dlc and the latest update installed.

Github wont let me upload the txt file as is, and I cant use pastebin since the log file is so long it just ends up crashing the webpage when i paste it. So I uploaded it to google drive instead 
https://drive.google.com/file/d/1zvbpSCNDLgHDBCLMoHR340RG3mGqsJ8l/view?usp=sharing

**Comment by lizardguts73** [comment]
The latest update yuzu 655 seems to have broken it even more now it just crashes when I win a fight.
Log: https://drive.google.com/file/d/1z-OD-bO_DN_12-XPFWkrveVV5a-CateY/view?usp=sharing

**Comment by G-Spawn** [comment]
Closing in favour of https://github.com/yuzu-emu/yuzu/issues/6163. Feel free to reopen if it still happens.
