### ISSUE TITLE
SDL2-based motion no longer detected on DS4 pad 

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#6454]
Yuzu has stopped detecting SDL-based motion control on the ds4 pad used in testing.  This had been working soon after support was added and other issues were resolved.  Specifically, Motion 1 appears as [not set], and efforts to set it involve Yuzu indicating "Shake!" but nothing happens when the controller is shaken.

Note that while the binary used in testing was manually compiled, the pre-built AppImage doesn't support motion either. 

Support information:

OS: Linux Mint 20.1 / kernel 5.11
Compiler: gcc 11.1.0 / CMake 3.20.2
Build Log: [here](https://pastebin.com/eWwjMjDF)

**Comment by v1993** [comment]
Can you, please, test if this is caused by PR #6450? Your build log doesn't indicate any issues (you indeed have hidapi library).

**Comment by Shoegzer** [comment]
Thanks @v1993, I tried against commit c1b8e59ea0669d213535516606d4a14e210b3f22 immediately prior to when PR #6450 was merged, but it's still not detecting any motion.  I also started a fresh `~/.config/yuzu` but same results.  Finally I tested with a second ds4 pad to rule out hardware issues, but same results.

Is there a log to enable with verbosity that might provide more clues?

**Comment by v1993** [comment]
First, I suggest you do

```
sudo chmod a+rw /dev/hidraw*
```

and then try again to rule out permission issues (please note that it is NOT a permanent fix - it will not persist over reboot). If that fails - try finding some early commit that does work with SDL motion for you and then use git bistect (there are some good tutorials on how to use it, but feel free to ask if you encounter problems).

As for log - there is a way to enable verbose logging for HID, but they are likely to show nothing if it's happening inside SDL (pretty likely).

**Comment by Shoegzer** [comment]
Thanks @v1993, that was helpful.  Setting `sudo chmod a+rw /dev/hidraw*` worked, but I'm somewhat surprised it did, because when I first encountered the issue, I added the following udev rule in `/etc/udev/rules.d/99-hidraw.rules`:

`KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="plugdev" `

I then restarted with `sudo udevadm control --reload-rules` but motion was still undetected.  

However, I just noticed that `chmod 664` resulted in no motion detected while `chmod 666` did.  I tried setting to:

`KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0666", GROUP="plugdev" `

But this had no effect on hidraw perms or motion detection in yuzu.

Note also that the controller is connected via bluetooth, which gets a new /dev/hidraw file with reset perms whenever reconnected.  So I don't believe the setting would apply automatically upon reboot.  Is there a way to make this permanent?

**Comment by v1993** [comment]
Your later ruler should work just fine after reboot. However, I suggest you use first one (`MODE="0664"`) and add yourself to `plugdev` group (issue seems to be that you aren't part of it).

**Comment by Shoegzer** [comment]
Thanks again.  You're right that 644 would be better, though the user that runs yuzu was already in the `plugdev` group.  So I suppose 666 perms is the only way?

**Comment by v1993** [comment]
It have to be 664, not 644. There is no way 666 will work and 664 won't work for plugdev group member (you need to relogin/reboot after adding your user to plugdev group).

Either way, good to know that it isn't an issue with yuzu.

**Comment by Shoegzer** [comment]
Sorry, typo - I meant 664.  User has always been in plugdev group, I checked this several weeks ago and have since rebooted several times, so I assume 666 is the only way, just not sure why that's the case.
