### ISSUE TITLE
Joycons drift when selecting input device Dual joy-con 0?

### ISSUE THREAD

**Issue by KirbyFighter** [yuzu-emu/yuzu#6455]

**Comment by KirbyFighter** [comment]
Hello, i have been using betterjoyforcemu with yuzu for a long time and with the newest update i find that i can now use my joycons as on controller without betterjoyforcemu but i guess we can't have nice things without bugs. For some weird reason the controllers will start to drift and thats with selecting the input device of (Dual joy-con 0) which our my joycons and so that kind of annoying, with betterjoyforcemu i don't have this problem at all so it's not my controllers that are drifting. The input device of (Xbox 360 Controller is betterjoyforcemu connecting my controllers as an xbox 360 controller)

![image_2021-06-11_193809](https://user-images.githubusercontent.com/71234367/121757748-8ce76680-caec-11eb-8e46-a2d99ba1689d.png)

![image_2021-06-11_194521](https://user-images.githubusercontent.com/71234367/121757977-8dccc800-caed-11eb-8043-8ce01a6930f8.png)

**Comment by german77** [comment]
Increase the deadzone by a bit. Betterjoy does re-center the stick at boot. I will add this to yuzu in a future
