### ISSUE TITLE
Pokemon sword crash when you enter dinamax adventures

### ISSUE THREAD

**Issue by erneston666** [yuzu-emu/yuzu#6457]
hello my yuzu closes when trying to save the game before entering a dinamax adventure.
the pokemon version is 1.3.1 and yuzu early access 1636.

greetings and thanks

**Comment by Uranite** [comment]
have you tried latest early access or mainline?

**Comment by erneston666** [comment]
I have tried several versions including the last one

**Comment by G-Spawn** [comment]
Disable multicore and try again. Beyond that you should probably provide a log for good measure.

**Comment by G-Spawn** [comment]
Please reopen issue should you still experience problem. Don't forget to provide a log file.
