### ISSUE TITLE
Yuzu closes itself when i play both Xenoblade Chronicles DE and Xenoblade Chronicles 2 without any errors

### ISSUE THREAD

**Issue by cloudzack83** [yuzu-emu/yuzu#6461]
Hi everyone, I have this problem from the beginning
I downloaded the iso of the games Xenoblade Chronicles DE and Xenoblade Chronicles 2 but on both when I play after some time that can change from 10 minutes to half an hour the emulator closes without any error message
I tried all the various settings, the problem appears with both vulkan and opengl

this is my configuration
Processor: Intel i7 8700k
graphics card: Nvidia Geforce 1070ti
RAM: 16gb
OS: windows 10 pro

**Comment by BSoDGamingYT** [comment]
Issue structure not followed as instructed and piracy will not be supported. Closing
