### ISSUE TITLE
Mario Kart 8 Deluxe Crash - Yuzu 658

### ISSUE THREAD

**Issue by Bonejob** [yuzu-emu/yuzu#6466]
Crash after transitioning from startup to game shows the main splash screen, framerate drops to 0 then Yuzu ABENDS.y

Console output shows an infinite loop of "HW.Memory" where the read address is incrementing.

```
[  64.003971] HW.Memory <Error> core\memory.cpp:Read:630: Unmapped Read32 @ 0x000122E4
[  64.005615] HW.Memory <Error> core\memory.cpp:Read:630: Unmapped Read32 @ 0x000122E8
[  64.007232] HW.Memory <Error> core\memory.cpp:Read:630: Unmapped Read32 @ 0x000122EC
[  64.008808] HW.Memory <Error> core\memory.cpp:Read:630: Unmapped Read32 @ 0x000122F0
[  64.010397] HW.Memory <Error> core\memory.cpp:Read:630: Unmapped Read32 @ 0x000122F4
[  64.011940] HW.Memory <Error> core\memory.cpp:Read:630: Unmapped Read32 @ 0x000122F8
[  64.013448] HW.Memory <Error> core\memory.cpp:Read:630: Unmapped Read32 @ 0x000122FC
```
Microprofiler can not capture as the Read:630 error starts. Trying to figure out how to get more information.

**Comment by FernandoS27** [comment]
Install the firmware.

**Comment by BSoDGamingYT** [comment]
To dump and install firmware, please see here: https://yuzu-emu.org/help/quickstart/#dumping-system-update-firmware
