### ISSUE TITLE
Animal Crossing New Horizons audio skipping since fastmem

### ISSUE THREAD

**Issue by Zeke-Green** [yuzu-emu/yuzu#6467]
Starting with mainline version 656, the audio in Animal Crossing New Horizons skips regularly every 3 seconds. Version 655 was fine and I tried 656 with vsync and assembly shaders disabled, but with no effect. Both versions run at a steady 30-31 FPS and 33ms frame time. 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6651020/yuzu_log.txt)

**Comment by OZtistic** [comment]
version 658 is the latest
try with that, I am not getting the same issues as you at all
By "skipping" you you mean slight intermittent desync which corrects itself almost instantly?
Try turning assembly shaders off
If you would like this issue ticket to get more traction please follow all the details the issue template asks for
you also don't need a 65gig Swap space/virtual memory setting either. that is kinda overkill unless you use it for video productions or something

**Comment by Zeke-Green** [comment]
I was using 658 today and with assembly shaders off. Funny enough, having it off actually made it worse. I suppose you could call it desyncing, but it goes silent for like 200ms~ in-between so I'd call it a skip.

The 64GB pagefile isn't something I set up for Yuzu, that's for my other work, which is mostly video-related.

Threaded optimization is globally turned on in my driver settings.

Thanks for helping and sorry if my post didn't quite meet code. No one mentioned a template.

**Comment by OZtistic** [comment]
I have a feeling this is "shader stutter":
Shaders are small programs running on a graphic card that are responsible for rendering graphics like terrain, explosions, characters etc. Since a PC cannot directly execute yuzu shaders, We first has to translate them to a format a PC can understand. This translation process can be time consuming and you'll notice it in two ways:

1). While playing, if yuzu needs to translate a new shader, the game might stutter. Loading into a game for the first time can give long freezes due to the amount of shaders. As you keep playing, the amount of stuttering will decrease rapidly.

2). When launching a game, the shader cache is loaded. To speed up this process there exists an additional "precompiled" cache. This cache may get reset every time you update yuzu or install a new GPU driver. The precompiled cache will then be compiled from scratch, causing a longer load time.

**Comment by Zeke-Green** [comment]
I know what shaders are and how they work.

I had gone over that possibility with some guys on the Yuzu Discord, but I discounted it for the reason that, while standing in my house, not changing anything and not even moving for over 10 minutes, at which point I wouldn't expect it to be compiling any new shaders, the skipping still persisted.

At the same time, there's no stutter in the video, which I would think would be the case if it were a shader issue.

**Comment by OZtistic** [comment]
I just noticed you are running Windows 7 SP 1
The addition of fastmem means that you need to have a modern Operating System (Windows 10 v1803+)

Alternatively, you can disable fastmem in Emulation --> Configure --> CPU
Change CPU Accuracy to Debug Mode
![image](https://user-images.githubusercontent.com/71381851/122238424-76ce1180-cf03-11eb-9af6-0da1705bf302.png)
Then on the Debug Tab right beside it, untick **Enable Host MMU Emulation**
![image](https://user-images.githubusercontent.com/71381851/122238811-c6144200-cf03-11eb-914e-3e2aa105c694.png)

You really should consider upgrading to Windows 10 though. Windows 7 is a security risk at this point

**Comment by Zeke-Green** [comment]
They explained that on the Discord. I could honestly never understand, though, how Dolphin emulator has had that feature (or at least a similar one) for years before that update of Windows 10 ever existed and of course has worked just fine on 7.

For the record, too, I have ESU updates for Windows 7, so it's not much of a security risk. I REALLY despise Windows 10, though, and the way Microsoft uses it to spy on people.

**Comment by Zeke-Green** [comment]
Version 665 today had no stutter in it, so whatever it was must have been fixed.

Thanks for the help.

**Comment by degasus** [comment]
> They explained that on the Discord. I could honestly never understand, though, how Dolphin emulator has had that feature (or at least a similar one) for years before that update of Windows 10 ever existed and of course has worked just fine on 7.
> 
> For the record, too, I have ESU updates for Windows 7, so it's not much of a security risk. I REALLY despise Windows 10, though, and the way Microsoft uses it to spy on people.

As written in the yuzu fastmem report, yuzu requires 4k alignment. Windows did not support this until 10 v1803. Dolphin is very fine with the old 64k alignment as it only emulate their BAT tables with fastmem, which are 128k aligned. Small detail, but with a large impact.
