### ISSUE TITLE
Pokemon Sword Shield and Lets Go  crash after a while playing randomly.

### ISSUE THREAD

**Issue by MaiLord96** [yuzu-emu/yuzu#6468]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6651826/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
Disable async shaders for pokemon games, it has a tendency to make them crash!

**Comment by MaiLord96** [comment]
> le async shaders for pokemon games, it has a tendency to make them c

I already have it deactivated

**Comment by BSoDGamingYT** [comment]
> > le async shaders for pokemon games, it has a tendency to make them c
> 
> I already have it deactivated

This log shows that it is enabled

![Capture](https://user-images.githubusercontent.com/38402209/121976745-bd493200-cd84-11eb-97a8-ea0aca7f6237.PNG)

**Comment by MaiLord96** [comment]
> > > le async shaders for pokemon games, it has a tendency to make them c
> > 
> > 
> > I already have it deactivated
> 
> This log shows that it is enabled
> 
> ![Capture](https://user-images.githubusercontent.com/38402209/121976745-bd493200-cd84-11eb-97a8-ea0aca7f6237.PNG)

You are right I have it disabled in the general settings but not in the custom settings of the Game but even after correcting this it remains the same.

**Comment by gidoly** [comment]
can you test again and report back? i want close this issue since i recently haven't saw report regarding this

**Comment by gidoly** [comment]
closes due to no response
