### ISSUE TITLE
Zelda Link's Awakening the trees are seen with black shadows and the iron ball of mario no slae instead shows a light

### ISSUE THREAD

**Issue by MaiLord96** [yuzu-emu/yuzu#6473]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6656979/yuzu_log.txt)

**Comment by OZtistic** [comment]
Please remove that first link (the picture link to something.... that isn't even a legit discord attachment) and follow the original issue template as closely as possible
With zero information and a dodgy link, I highly doubt this will be addressed

**Comment by MaiLord96** [comment]
> (the picture link to something.... that isn't even a legit disco

sorry for the link, I already use Vulkan, I thought that all the information you need is in the log file.

**Comment by gidoly** [comment]
closes due to lack of visual with graphical glitch and decribe poorly
