### ISSUE TITLE
Smash Bros Black Screen in specific moments (Map and Battle).

### ISSUE THREAD

**Issue by cristianosiebert-itajai** [yuzu-emu/yuzu#6482]
Hello everyone.

When i play Smash Bros Ultimate (with the dlc's) the game runs really well, with a good FPS.
But in world of light mode, when i start a battle, the screen turns black, but game still running with audio and controls.
If i jump off the stage and die, the rematch menu are visible. And the the fight runs normally.
After winning, the map shows up and kirby glow a light, after that, the screen turn black again and only return if i walk to a next enemy (when a popup with the picture opens).

Oh, and i don't able to use the web applet, the applet loads, but my controls didn't work, so, i disabled that (the applet).

My pc specs:
Yuzu version early 1787
Windows 10
8GB Ram
NVidia Geforce mx110

Yuzu log:
I'll find and post it ASAP.

**Comment by kevincox** [comment]
I know https://github.com/yuzu-emu/yuzu/issues/6898 is newer but it has gathered more info so this should probably be closed as a duplicate.

**Comment by G-Spawn** [comment]
> I know #6898 is newer but it has gathered more info so this should probably be closed as a duplicate.

Indeed. Thank you.
