### ISSUE TITLE
Monster Hunter Genrerations Ultimate distorted color

### ISSUE THREAD

**Issue by Narugakuruga** [yuzu-emu/yuzu#6489]
This happen in certain maps. Every thing is distorted except HUD

![0100770008dd8000_2021-06-19_08-58-29-551](https://user-images.githubusercontent.com/31060534/122626403-05e25180-d0dd-11eb-86fc-32bb49d41170.png)

**Comment by OZtistic** [comment]
This is a known issue. I have seen this before in this exact area. It should be fixed in the upcoming project hades release

**Comment by BSoDGamingYT** [comment]
This issue has not been fixed in master yet. Reopening
