### ISSUE TITLE
Dragon Quest 2 Corrupted Graphics

### ISSUE THREAD

**Issue by kturcotte1980** [yuzu-emu/yuzu#6507]
Having some graphical issues with Dragon Quest 2 on Yuzu (663/171dd9c0d from 19 June 2021). Played around with options, but doesn’t seem to make any difference. Also tried with anisotropic filtering in default, as suggested, and that did not change anything. Battle graphics seem to do this with the first battle upon entering the area (If I just exited a town/castle/dungeon), and the same with the map errors, though the map graphics errors stay until I exit the area (Even between fights)
![010062200efb4000_2021-06-21_17-30-19-854](https://user-images.githubusercontent.com/86271969/122844715-4524c400-d2d0-11eb-89e7-ae8e2e709cd2.png)
![010062200efb4000_2021-06-21_17-30-02-759](https://user-images.githubusercontent.com/86271969/122844718-45bd5a80-d2d0-11eb-8db0-c05a18a61b75.png)
![010062200efb4000_2021-06-21_17-29-48-866](https://user-images.githubusercontent.com/86271969/122844719-4655f100-d2d0-11eb-9c66-744744111ae1.png)
![010062200efb4000_2021-06-20_16-41-45-582](https://user-images.githubusercontent.com/86271969/122844723-47871e00-d2d0-11eb-8ef6-17a49ccc083a.png)
![010062200efb4000_2021-06-20_16-42-12-274](https://user-images.githubusercontent.com/86271969/122844726-47871e00-d2d0-11eb-8a35-1765182b34ae.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6690158/yuzu_log.txt)

**Comment by Willlux** [comment]
This is still an issue as of early access 2905

**Comment by benderscruffy** [comment]
@FearlessTobi 
this has been fixed
can be closed
