### ISSUE TITLE
Vertex explosions on Yuzu since 21.1.0 mesa driver

### ISSUE THREAD

**Issue by Lithium64** [yuzu-emu/yuzu#6513]
I have a R7 260X GPU and with **21.1.3** mesa driver i get some vertex explosions while playing, on Pokémon shield it is more evident like you can see on video below. But it happens on other games like Super Mario Odyssey too. It started happen since **21.1.0** was released.

The video was recorded with latest mainline build and mesa **21.1.3**, on mesa **21.0.3** driver it works fine. Probably it is a regression on mesa driver.

https://www.youtube.com/watch?v=HrMFRaAJiKs

**My specs:**

Intel i3-10100f
AMD Radeon R7 260X
16GB RAM
Ubuntu 20.04.2 LTS x86_64
Kernel: 5.8.0-55-generic
Mesa 21.1.3

**Comment by FernandoS27** [comment]
I don't want to be rude but why are you reporting this bug here and not on mesa? It's clearly a driver bug on their end.

**Comment by Lithium64** [comment]
> I don't want to be rude but why are you reporting this bug here and not on mesa? It's clearly a driver bug on their end.

I don't know how to report a bug on mesa correctly, I tried to report a bug there once and they never paid attention to it. I reported the bug here, because it involves the emulator and some developer can report the bug on mesa better than me, as I have no experience with this. Sorry to bother you, I just wanted to call attention to the issue.

**Comment by FernandoS27** [comment]
I understand your frustation, so it is for us. However, I do believe Mesa dev are more open to bug reports and you should try there first before coming here. It's kind of rude to throw us the issue if you haven't eliminated all other options before.

**Comment by ReinUsesLisp** [comment]
This seems related to uniform buffer robustness.

**Comment by Lithium64** [comment]
> I understand your frustation, so it is for us. However, I do believe Mesa dev are more open to bug reports and you should try there first before coming here. It's kind of rude to throw us the issue if you haven't eliminated all other options before.

I did a bug report on mesa gitlab
https://gitlab.freedesktop.org/mesa/mesa/-/issues/4987

> This seems related to uniform buffer robustness.

Rpor

**Comment by ReinUsesLisp** [comment]
I'm reopening this to keep track of it.

**Comment by Mershl** [comment]
Fix for this issue is included in mesa master and should be included in the next bugfix release 21.1.4.

**Comment by Lithium64** [comment]
> Fix for this issue is included in mesa master and should be included in the bugfix release 21.1.4 (released 30th of June).
> 
> Can someone confirm this issue fixed with mesa 21.1.4?

I tested it here and the bug was fixed.
