### ISSUE TITLE
mGBA's UI fails to render

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#6516]
Though gameplay renders okay, mGBA's UI (needed for file navigation and configuring settings within the emulator) does not render on yuzu. The shader recompiler rewrite fixes mGBA releases prior to and including 0.8.4, but later releases look like the following on all versions of yuzu as a result of mgba-emu/mgba@9ac93662579e12e7a19f1413d137cc5329ed1e32 (credits to @gidoly for the screenshot):

<img src="https://cdn.discordapp.com/attachments/799182828038258698/857134236679012382/20210623_144406.png" width=640 />

[yuzu_log.txt.tar.gz](https://github.com/yuzu-emu/yuzu/files/6699402/yuzu_log.txt.tar.gz)

**Comment by Kelebek1** [comment]
![Untitled-1](https://user-images.githubusercontent.com/34639600/123204944-f1bd9c00-d4b0-11eb-84ae-bef2953118df.png)

I can get the text back by forcing instancing and setting a bunch of instances. I don't know how to fix this though, the GPU regs indicate that there's 0 instances, and Draw is called through DrawArrays which sets instancing to false, and it just falls into glDrawArrays. It's definitely being used to draw though: https://github.com/mgba-emu/mgba/blob/master/src/platform/switch/gui-font.c#L477

This is one for @ReinUsesLisp and @FernandoS27. :)

**Comment by gidoly** [comment]
fixed on lastest yuzu
