### ISSUE TITLE
Feature Request: Please Add DirectX 11/12 Renderer 

### ISSUE THREAD

**Issue by danprice142** [yuzu-emu/yuzu#6520]
This would allow Yuzu to function on many more devices

**Comment by Joshua-Ashton** [comment]
No it wouldn't.

**Comment by goldenx86** [comment]
It has been considered in the past, it's not viable. Current Direct3D versions lack features we require.

**Comment by ReinUsesLisp** [comment]
D3D11 and D3D12 lack the following features:
- Per-face stencil properties
- Uint8 indices
- Triangle fans (and all the other topologies not available on Vulkan)
- Native support for blits
- Texture views between formats of different number of components (e.g. RGBA8_UNORM and R32_FLOAT)
- Most legacy functionality
- Most Nvidia exclusive extensions
- OpenGL's NDC
- Unrestricted depth ranges (I'm not sure about this one)
- Masked color clears
- Communication channels to report driver issues we find
- An extension model

D3D11 in particular lacks:
- Any kind of bindless resources
- Multi draw indirect

D3D12 requires shaders to be signed, wasting runtime and development time on a useless task.
