### ISSUE TITLE
(Feature request) Fidelity FX Super Resolution

### ISSUE THREAD

**Issue by AtilaSaraiva** [yuzu-emu/yuzu#6524]
Hello yuzu devs!

I just wanted to say that the work you're doing is awesome. Just a glance of the website is enough to notice the amount of thought you all put in this software.

With that said, I'd like to see the Fidelity FX Super Resolution on Yuzu, since from what I could gather, it is very simple to implement.

Thanks!

**Comment by Morph1984** [comment]
We'll have to wait for AMD to release the source to the shader(s) used for FSR. Furthermore, they have not created shaders for OpenGL, only for DirectX and Vulkan. It has yet to be known whether 1. It can be ported to OpenGL and 2. Apply shader effects in an emulated rendering context.

**Comment by AtilaSaraiva** [comment]
Okay! It is nice to see that you've already thought about this. Let's keep on hoping.

**Comment by AtilaSaraiva** [comment]
https://github.com/GPUOpen-Effects/FidelityFX-FSR

Seems like it is out!

**Comment by TobiPeterG** [comment]
I'd like to see it as well, maybe as Vulkan only feature, as yuzu supports Vulkan as well?

Would be great if it was implemented e.g. as up-scaling algorithm, as I have a 4K screen and it would really be beneficial here.

For example a Proton version (used to play Windows games on linux) also implements FSR as upscaling method, so it would be applied after everything is rendered. Might be easier to implement this way.

**Comment by DartPower** [comment]
Like this project, which support the FSR and other like Anime4k
https://github.com/7Brandyn7/Magpie

https://github.com/GPUOpen-Effects/FidelityFX-FSR
https://github.com/igv/FSRCNN-TensorFlow
https://github.com/bloc97/Anime4K
