### ISSUE TITLE
NEO : The World Ends with you (DEMO) - Abnormal light source processing

### ISSUE THREAD

**Issue by vojo915** [yuzu-emu/yuzu#6530]
# NEO : The World Ends with you (DEMO) - 01001AB0141A8000

**Yuzu:** 668

**CPU:** Ryzen 5 3600
**GPU:** GeForce GTX 1660 Ti
**RAM:** 16GB

The light source is displayed with abnormal emphasis. Depending on the location, it may cover the screen and may not be visible at all. The operation is almost normal, but it is difficult to play. It also crashes over time.

Probably the same bug as "World's End Club ([01005A2014362000](https://github.com/yuzu-emu/yuzu/issues/6391) / 01008C2014340000 / [0100BE101453E000](https://github.com/yuzu-emu/yuzu/issues/6336))".

![1_q99](https://user-images.githubusercontent.com/84438932/123513351-c1037f80-d6c7-11eb-8c00-b3e1fb6f1d86.jpg)

**Log file:** [yuzu_668_01001AB0141A8000.zip](https://github.com/yuzu-emu/yuzu/files/6720106/yuzu_668_01001AB0141A8000.zip)

**Comment by gidoly** [comment]
seems to fixed on shader decompiler rewrite
