### ISSUE TITLE
[Dead or Alive Xtreme 3 Scarlet] Stuck on launching screen if Multicore is turned on.

### ISSUE THREAD

**Issue by hoshinocomet** [yuzu-emu/yuzu#6538]
-The game will be stuck on the launching screen on versions of Yuzu after 570.
-The solution is to **turn off the Multicore option** at the bottom of the screen, and the game will boot and run successfully.
-Would appreciate if the team could look into this. Thank you.

**Comment by babyfish0226** [comment]
After i turn off the Multicore option and it still stuch on the launching screen.  My yuzu version is 676

**Comment by elkay** [comment]
Came here to open a ticket but one already open. I am experiencing the same issues with the same workaround working (albeit poor performance because of it). Others on Discord report the same problem.

**Comment by elkay** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7205502/yuzu_log.txt)
Log attached of opening Yuzu, running DOAX Scarlet, stuck at loading, stop emulation, close Yuzu.

**Comment by elkay** [comment]
Just to add more detail to this, build 581 is what broke this. Build 580 loads into game fine.

**Comment by TheNamelessWonderer** [comment]
This isn't fixed for me on 1105. It just gets stuck on a black screen if multicore is on.
