### ISSUE TITLE
[BUG REPORT] (Astro Duel Deluxe) Triangle Point Displaced & Choppy Replays

### ISSUE THREAD

**Issue by nickkeane** [yuzu-emu/yuzu#6543]
When running Astro Duel Deluxe, a point on some of the triangles/quads are located incorrectly in menus and in-game.

[Screenshot](https://drive.google.com/file/d/18sbRxFNqI1kTlqTpElp77idfQOAbYXK9/view)

Also, game slows down during certain Instant Replays, becomes very choppy. Otherwise it seems to work and run well.

Yuzu Version: EA 1835

**Comment by G-Spawn** [comment]
If you could provide a log for good measure as well that would be preferred.

**Comment by benderscruffy** [comment]
this is fixed
can be closed
