### ISSUE TITLE
Tony Hawk’s Pro Skater 1 + 2 glitches

### ISSUE THREAD

**Issue by pavlikdc** [yuzu-emu/yuzu#6546]
Hello. Could You update / fix Yuzu emulator to be compatible with Tony Hawk’s Pro Skater 1 + 2?
With the latest ver of emulator the game is botable but not playble.

Check the video:

https://youtu.be/8J9WY9ZSjBA?t=158

https://youtu.be/8J9WY9ZSjBA?t=237

I've read some info from Ryujinx Changelog, it may help you.

"2021-06-29 Changed:
Cleanup AOC service and implement some stub calls in AM service. Tony Hawk’s Pro Skater 1+2 is now bootable."

On Ryujinx after this fixes game runs almost perfectly with small, minor glitches.
Thanks in advance

**Comment by cclecle** [comment]
can not see video to check if it is the same issue but here on yuzu 1335 + game ver 1.0.2 I cannot play.

Game load, I am reaching menu, but can not start any game, endless loading screen.
Sometime also freeze in the menu.

I tried in both Vulkan and OpenGL.
Running on and Amd ryzen 7 5800X3D + Radeon RX5700 XT / Win11, all driver updated.
