### ISSUE TITLE
Dragon Quest III with white screen on AMD Video Card and possible corrupted graphics and such...

### ISSUE THREAD

**Issue by chaosjs0010** [yuzu-emu/yuzu#6548]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6749704/yuzu_log.txt)

Hello to all, I am experiencing on Linux Mint 20.1 Linux OS with an AMD Radeon 5700XT Video Card with Dragon Quest III on OpenGL a white screen with possible corrupted graphics and on Vulkan a Black Screen with nothing on it and audio working properly as well..  on Latest to greatest Mainline release as of Today also.. Thanks for listening and Have a great day ahead and stay safe also..

**Comment by ameerj** [comment]
Is this still a reproducible issue?

**Comment by vonchenplus** [comment]
From the logs, it seems that shader does not support legacy attributes in Opengl mode, Vulkan should be fine.
