### ISSUE TITLE
A problem with Audio

### ISSUE THREAD

**Issue by shujynx** [yuzu-emu/yuzu#6550]
I recently bought speakers for my PC.
I was playing Pokemon Sword on yuzu and decided to use them, but my output was on my headphones.
As soon as I switched the Output device, Yuzu crashed.
I tried this on all of the available audio codecs and the only one that didn't crash was obviously null.
Also tried with Audio Strech off and the same problem occurs.
I'm using the latest version as of now (Yuzu 674 Mainline).

**Comment by OZtistic** [comment]
Please follow the issue template as closely as you can (it was displayed when you made this ticket)
__
Also might want to change the title to something more descriptive like: "[BUG REPORT] Pokemon Sword Audio issues with my hardware", and follow the directions above

**Comment by nyarosu** [comment]
Could you post the log file?
Windows key + R, %appdata% -> yuzu/log.

**Comment by LiverBlow** [comment]
I am seeing this issue also on Linux:

Pop_OS!
Kernel: 5.13.0
Nvidia 3080fe
Ryzen 5900x

Logs:
`[   0.017803] Input <Info> input_common/gcadapter/gc_adapter.cpp:Adapter:21: GC Adapter Initialization started
[   0.249934] Input <Info> input_common/udp/client.cpp:Client:164: Udp Initialization started
[   0.249950] Input <Info> input_common/udp/client.cpp:StartCommunication:309: Starting communication with UDP input server on 127.0.0.1:26760
[   0.278599] Frontend <Info> yuzu/main.cpp:GMainWindow:235: yuzu Version: yuzu 782
[   0.278606] Frontend <Info> yuzu/main.cpp:GMainWindow:250: Host CPU: AMD Ryzen 9 5900X 12-Core Processor             | AVX2 | FMA
[   0.278625] Frontend <Info> yuzu/main.cpp:GMainWindow:252: Host OS: KDE Flatpak runtime
[   0.278637] Frontend <Info> yuzu/main.cpp:GMainWindow:253: Host RAM: 31.29 GB
[   0.278640] Frontend <Info> yuzu/main.cpp:GMainWindow:255: Host Swap: 15.86 GB
[   0.282079] Frontend <Warning> yuzu/game_list.cpp:LoadCompatibilityList:693: Game compatibility list is empty
[  35.003928] Config <Info> common/settings.cpp:LogSettings:41: yuzu Configuration:
[  35.003933] Config <Info> common/settings.cpp:operator():34: Controls_UseDockedMode: true
[  35.003934] Config <Info> common/settings.cpp:operator():34: System_RngSeed: 0
[  35.003935] Config <Info> common/settings.cpp:operator():34: System_CurrentUser: 0
[  35.003936] Config <Info> common/settings.cpp:operator():34: System_LanguageIndex: 1
[  35.003936] Config <Info> common/settings.cpp:operator():34: System_RegionIndex: 1
[  35.003937] Config <Info> common/settings.cpp:operator():34: System_TimeZoneIndex: 0
[  35.003937] Config <Info> common/settings.cpp:operator():34: Core_UseMultiCore: true
[  35.003938] Config <Info> common/settings.cpp:operator():34: CPU_Accuracy: 0
[  35.003938] Config <Info> common/settings.cpp:operator():34: Renderer_UseResolutionFactor: 1
[  35.003939] Config <Info> common/settings.cpp:operator():34: Renderer_UseSpeedLimit: true
[  35.003940] Config <Info> common/settings.cpp:operator():34: Renderer_SpeedLimit: 100
[  35.003942] Config <Info> common/settings.cpp:operator():34: Renderer_UseDiskShaderCache: true
[  35.003942] Config <Info> common/settings.cpp:operator():34: Renderer_GPUAccuracyLevel: 1
[  35.003943] Config <Info> common/settings.cpp:operator():34: Renderer_UseAsynchronousGpuEmulation: true
[  35.003944] Config <Info> common/settings.cpp:operator():34: Renderer_NvdecEmulation: 2
[  35.003944] Config <Info> common/settings.cpp:operator():34: Renderer_AccelerateASTC: true
[  35.003944] Config <Info> common/settings.cpp:operator():34: Renderer_UseVsync: true
[  35.003945] Config <Info> common/settings.cpp:operator():34: Renderer_ShaderBackend: 1
[  35.003946] Config <Info> common/settings.cpp:operator():34: Renderer_UseAsynchronousShaders: false
[  35.003946] Config <Info> common/settings.cpp:operator():34: Renderer_AnisotropicFilteringLevel: 0
[  35.003946] Config <Info> common/settings.cpp:operator():34: Audio_OutputEngine: auto
[  35.003947] Config <Info> common/settings.cpp:operator():34: Audio_OutputDevice: Yeti Nano Analogue Stereo
[  35.003947] Config <Info> common/settings.cpp:operator():34: DataStorage_UseVirtualSd: true
[  35.003949] Config <Info> common/settings.cpp:operator():38: DataStorage_CacheDir: /home/farhanghani/.var/app/org.yuzu_emu.yuzu/cache/yuzu
[  35.003949] Config <Info> common/settings.cpp:operator():38: DataStorage_ConfigDir: /home/farhanghani/.var/app/org.yuzu_emu.yuzu/config/yuzu
[  35.003951] Config <Info> common/settings.cpp:operator():38: DataStorage_LoadDir: /home/farhanghani/.var/app/org.yuzu_emu.yuzu/data/yuzu/load
[  35.003952] Config <Info> common/settings.cpp:operator():38: DataStorage_NANDDir: /home/farhanghani/.var/app/org.yuzu_emu.yuzu/data/yuzu/nand
[  35.003953] Config <Info> common/settings.cpp:operator():38: DataStorage_SDMCDir: /home/farhanghani/.var/app/org.yuzu_emu.yuzu/data/yuzu/sdmc
[  35.003954] Config <Info> common/settings.cpp:operator():34: Debugging_ProgramArgs: 
[  35.003954] Config <Info> common/settings.cpp:operator():34: Input_EnableMotion: true
[  35.003955] Config <Info> common/settings.cpp:operator():34: Input_EnableVibration: tr^A^C
`

**Comment by G-Spawn** [comment]
Feel free to reopen this issue should it still happen to you & provide a log file to go along with it.
