### ISSUE TITLE
[BUG REPORT] Pro Controller Left Stick is offset a bit to the left and down

### ISSUE THREAD

**Issue by SoRadGaming** [yuzu-emu/yuzu#6555]
Yuzu 676
The Pro Controller Left stick is offset for a bit.
Yuzu Controller
![image](https://user-images.githubusercontent.com/47128515/124373125-11379e80-dcd3-11eb-89e5-05ce656df3f0.png)
Taken at the same time on Cemu (Not Drifting/ Haven't Touched Controller between Images)
![image](https://user-images.githubusercontent.com/47128515/124373150-214f7e00-dcd3-11eb-89bc-e7777eb9b3f5.png)

I can recreate this for both my pro controllers and even my fake Wii U pro controller, with the exact same result.
While you might want to ride this off as joystick drift, I have two new pro controllers (From Nintendo) and have already calibrated them on the switch and using windows 10 Xbox calibration software. This issue is not seen in steam games, or in other emulators like Cemu. I do remember the Cemu emulator having the same issue, but was fixed in an update (https://github.com/Davidobot/BetterJoy/issues/2) that was the issue. Might be the same issue with Yuzu.

EDIT: I already know a Higher dead zone will fix this

**Comment by german77** [comment]
I have the same issue. Needs a way to recenter the joystick on yuzu

**Comment by OZtistic** [comment]
This non-recentering on Luigi's Mansion is a nightmare in later levels. What you can do though, for this game is make your deadzone a little larger in the Input Configurator (the thing you screencapped)
But it up to like 18% or 20%
![image](https://user-images.githubusercontent.com/71381851/124375548-2669f880-dce6-11eb-9c57-dde5bc2d3836.png)

**Comment by stressatoo** [comment]
[That's your controller's fault](https://www.reddit.com/r/PS4/comments/9ay2p5/controller_deadzone_shift_fix/). I solved this changing mine multiple times. Set your deadzone higher.

**Comment by german77** [comment]
Re-centering externally doesn't always reflects on yuzu. A higher deadzone will fix the issue when idle. But if you move straight up you still move slightly to either side. I will add the option when I have a chance

**Comment by taifengdian** [comment]
recenter it with switch can fix the issue. go to find one switch.

**Comment by SoRadGaming** [comment]
Made a video that might help. It's weird, the controller works fine then as soon as any button is pressed they go off centre, https://youtu.be/KIuTDmDZCgM.
