### ISSUE TITLE
[Ciel Nosurge] yuzu 676+ cannot boot due to incomplete audio initialize

### ISSUE THREAD

**Issue by reina-n** [yuzu-emu/yuzu#6568]
It seems HLE issue.
676+ infinity  says "Unimplemented instruction ". it is completely stacking.

> [  12.272757] Service.AM <Warning> core\hle\service\am\am.cpp:InitializeApplicationCopyrightFrameBuffer:1363: (STUBBED) called
> [  12.288746] Service.AM <Warning> core\hle\service\am\am.cpp:SetApplicationCopyrightImage:1370: (STUBBED) called
> [  12.824503] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:59: (STUBBED) called
> [  12.825195] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioTvOutput, volume=0.5
> [  12.826954] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:59: (STUBBED) called
> [  12.826984] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioUsbDeviceOutput, volume=1
> [  12.827473] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:59: (STUBBED) called
> [  12.827499] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioStereoJackOutput, volume=1
> [  12.828076] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:59: (STUBBED) called
> [  12.828118] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioBuiltInSpeakerOutput, volume=1
> [  12.828804] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:59: (STUBBED) called
> [  12.828867] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:246: (STUBBED) called. name=AudioUsbDeviceOutput, volume=1
> [  12.852505] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:QuerySystemEvent:129: (STUBBED) called
> [  12.876063] Core.ARM <Error> core\arm\dynarmic\arm_dynarmic_64.cpp:InterpreterFallback:87: Unimplemented instruction @ 0x83B919C for 1 instructions (instr = E7FFDEFE)
> [  12.876070] Core.ARM <Error> core\arm\dynarmic\arm_dynarmic_64.cpp:InterpreterFallback:87: Unimplemented instruction @ 0x83B919C for 1 instructions (instr = E7FFDEFE)
> [  12.876072] Core.ARM <Error> core\arm\dynarmic\arm_dynarmic_64.cpp:InterpreterFallback:87: Unimplemented instruction @ 0x83B919C for 1 instructions (instr = E7FFDEFE)
> [  12.876074] Core.ARM <Error> core\arm\dynarmic\arm_dynarmic_64.cpp:InterpreterFallback:87: Unimplemented instruction @ 0x83B919C for 1 instructions (instr = E7FFDEFE)
> ...

675- says "start" after QuerySystemEvent

>    9.067945] Service.AM <Warning> core\hle\service\am\am.cpp:InitializeApplicationCopyrightFrameBuffer:1363: (STUBBED) called
> [   9.079918] Service.AM <Warning> core\hle\service\am\am.cpp:SetApplicationCopyrightImage:1370: (STUBBED) called
> [   9.581144] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:59: (STUBBED) called
> [   9.581742] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:244: (STUBBED) called. name=AudioTvOutput, volume=0.5
> [   9.583346] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:59: (STUBBED) called
> [   9.583373] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:244: (STUBBED) called. name=AudioUsbDeviceOutput, volume=1
> [   9.583969] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:59: (STUBBED) called
> [   9.584022] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:244: (STUBBED) called. name=AudioStereoJackOutput, volume=1
> [   9.584512] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:59: (STUBBED) called
> [   9.584538] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:244: (STUBBED) called. name=AudioBuiltInSpeakerOutput, volume=1
> [   9.585023] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:59: (STUBBED) called
> [   9.585051] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:SetAudioDeviceOutputVolume:244: (STUBBED) called. name=AudioUsbDeviceOutput, volume=1
> [   9.620582] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:QuerySystemEvent:127: (STUBBED) called
> [   9.664655] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:Start:111: (STUBBED) called
> [  10.439860] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
> [  10.442042] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
> [  10.599972] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:247: (STUBBED) called
> [  10.989714] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
> [  10.991149] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
> [  10.999983] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:247: (STUBBED) called

I set all of debug checkbox, but error is same. this is maximum information.
there are no ppl who caused same issue when initialize even though its release was 4days ago.
so please just notice this error. thank you.

**Comment by german77** [comment]
Please provide a full log. Your issue seems relevant but without a way to reproduce it's near imposible to fix

**Comment by reina-n** [comment]
[yuzu_log.676.2.zip](https://github.com/yuzu-emu/yuzu/files/6773908/yuzu_log.676.2.zip)
okay, attached. I trimmed too looong last messages repeat.

**Comment by reina-n** [comment]
ah... *:Debug log said the reason of stack...

> Log Text: KTSL: assertion "nn::audio::GetAudioRendererState(m_AudioRendererHandle) == nn::audio::AudioRendererState_Stopped" failed: file "E:/KTGLIBS/KTSL/trunk/Source/NX/KtslDeviceCore.cpp", line 2051

[yuzu_log.679Debug.zip](https://github.com/yuzu-emu/yuzu/files/6788027/yuzu_log.679Debug.zip)

**Comment by Sage-of-Mirrors** [comment]
It doesn't seem like this ever got fixed. Is there a way to resolve it?

**Comment by benderscruffy** [comment]
goes ingame now
please close

**Comment by german77** [comment]
Fixed by #8545
