### ISSUE TITLE
[VULKAN][LINUX][MESA/RADV] Xenoblade Chronicles 2 Vulkan crash

### ISSUE THREAD

**Issue by DistantThunder** [yuzu-emu/yuzu#6572]
When loading a save in the early game forest, Yuzu crashes while attempting to compile shaders:

kernel log:
```
yuzu[964686]: segfault at 150 ip 00007f6cd67c2979 sp 00007f6cd5468190 error 4 in libVkLayer_khronos_validation.so[7f6cd67a7000+8de000]
```

Logfile: 
[yuzu.log.gz](https://github.com/yuzu-emu/yuzu/files/6785103/yuzu.log.gz)

**Comment by ReinUsesLisp** [comment]
This happens when the game binds a "null buffer" to the transform feedback bindings. We could fix this by creating a 4 byte buffer and pass a size of zero to `vkCmdBindTransformFeedbackBuffersEXT`, similar to what we do for null index buffers.

**Comment by ReinUsesLisp** [comment]
@DistantThunder Can you test if the linked pull request fixes the issue for you?

**Comment by ReinUsesLisp** [comment]
We tested it, it's indeed crashing building a shader. I'll try to dump it, maybe RADV doesn't support sliced transform feedbacks.

**Comment by DistantThunder** [comment]
@Joshua-Ashton Apologies for summoning you out of nowhere but would you know if RADV "support[s] sliced transform feedbacks"?

**Comment by Joshua-Ashton** [comment]
Sorry, I have no idea. I know very little about xfb.

**Comment by DistantThunder** [comment]
Thanks I thought you might with your extensive history of Vulkan workloads on RADV. Guess you won't get around dumping the shader and dissecting it, even though I've little idea how to do it.

**Comment by ReinUsesLisp** [comment]
Reopening as it still needs #6585.

**Comment by DistantThunder** [comment]
Tested with Shader Recompiler Rewrite and indeed it loads fine now.

![image](https://user-images.githubusercontent.com/3923810/126301137-159a10b9-b80c-4aae-af75-4ea55aba1d23.png)

We've lost all perf in the meantime it appears though.

**Comment by FernandoS27** [comment]
> Tested with Shader Recompiler Rewrite and indeed it loads fine now.
> 
> ![image](https://user-images.githubusercontent.com/3923810/126301137-159a10b9-b80c-4aae-af75-4ea55aba1d23.png)
> 
> We've lost all perf in the meantime it appears though.

are you running it on a debugger? if so, you'll lose perf because of fastmem conflicting with the debugger.

**Comment by DistantThunder** [comment]
@FernandoS27 Hi,

Indeed, the Wait Tree debugging option was forgotten enabled at some point. 
So I retried with debugging disabled:

![image](https://user-images.githubusercontent.com/3923810/127034812-77a992e8-1110-4462-8c6b-fae023d59116.png)
---
![image](https://user-images.githubusercontent.com/3923810/127034914-befaa434-ce94-4550-be8f-47dbeb3f2d4b.png)


And I still notice significant perf drop compared to OGL backend which maitains solid 30 fps:

![image](https://user-images.githubusercontent.com/3923810/127034157-e3d85d33-e256-495f-a36e-642497d9bf64.png)

Unfortunately it's a catch 22 for me because OGL suffers from a pretty annoying graphical glitche on this game:

https://github.com/yuzu-emu/yuzu/issues/6739
