### ISSUE TITLE
Yuzu locks up again

### ISSUE THREAD

**Issue by ChrisM20** [yuzu-emu/yuzu#6578]
I have noticed that yuzu closes again randomly and I had seen that it had disappeared but I don't know if 3 versions started to close randomly when playing pokemon sword.

My specs in case they help :
Intel i5 2450m
Nvidia gt540m

**Comment by goldenx86** [comment]
Without a log or more information, it sounds like lack of RAM.

**Comment by ChrisM20** [comment]
I have 8 gb of ram, I do not know how to see if there is an error log to check the reason but yuzu closes without error, I do not know if it started from 678

**Comment by german77** [comment]
For assistance with your issue, please accurately describe the problem and post a log file. The following guide shows how to get the log file: https://yuzu-emu.org/help/reference/log-files/

**Comment by ChrisM20** [comment]
I have this two files:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6788353/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6788354/yuzu_log.txt.old.txt)

**Comment by G-Spawn** [comment]
![image](https://user-images.githubusercontent.com/23653025/125017184-a1157980-e040-11eb-915a-eb81a457d693.png)
are you using the latest driver for your gpu?

**Comment by ChrisM20** [comment]
It is the latest version and if it does not support vulkan but even so I can play without problems or at least from the 678 that locks up after a short time and it did not happen to me but like that right now I return or I have noticed it there was an occasion that it stuck to the minute more or less it is very similar to that occasion but this one takes longer
