### ISSUE TITLE
Axiom Verge: UI upside down

### ISSUE THREAD

**Issue by mailwl** [yuzu-emu/yuzu#658]
the game itself in normal state (except white textures)

![axiom](https://user-images.githubusercontent.com/629437/42698169-c2a48d5c-86c5-11e8-9203-99a2f305d1ad.png)

<meta name="titleids"  content="0100B1F00660E000">

**Comment by ReinUsesLisp** [comment]
Textures are white because the game renders its tileset from a super-tileset each frame. This rendering is upside-down, so the world pass ends up reading trash instead of expected tileset.

**Comment by MysticExile** [comment]
Is (probably) fixed with #3885

**Comment by benderscruffy** [comment]
not fixed on my AMD RX 580  with #3885

**Comment by savaloi** [comment]
> not fixed on my AMD RX 580 with #3885

I also have an RX580 & have the exact same issue on the latest build of Yuzu. Tried both OpenGL and Vulkan - same result.

**Comment by benderscruffy** [comment]
this should be fixed by #8809

**Comment by MysticExile** [comment]
I will close this issue as it is fixed by #8809. If you're still experiencing this issue feel free to open a new issue with a new log
