### ISSUE TITLE
[Shader Decompiler Rewrite] Smash Ultimate graphics are broken

### ISSUE THREAD

**Issue by nullavisus** [yuzu-emu/yuzu#6586]
The Shader decomp rewrite (EA 1866) completely breaks Smash Ultimate.

GPU: GTX 970M
GPU Accuracy: Normal
Shader backend: GLASM
![screenshots01006a800016e000_2021-07-09_15-19-12-540](https://user-images.githubusercontent.com/67781060/125141351-a9fe5d80-e0c9-11eb-8ea0-db9e14e99a67.png)
![screenshots01006a800016e000_2021-07-09_15-18-38-081](https://user-images.githubusercontent.com/67781060/125141364-b682b600-e0c9-11eb-8cda-9a2cd1348a64.png)
![screenshots01006a800016e000_2021-07-09_15-18-20-383](https://user-images.githubusercontent.com/67781060/125141366-b97da680-e0c9-11eb-8a9a-70a4185757c4.png)

**Comment by FernandoS27** [comment]
@nullavisus could you post a log? also have you updated your drivers to latest? does this happen only on GLASM or also on GLSL?

**Comment by nullavisus** [comment]
@FernandoS27 Graphics are still broken after switching to GLSL, here's a log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6794170/yuzu_log.txt)

**Comment by nullavisus** [comment]
I was able to narrow it down, disabling asynchronous shader building fixes the graphics. So somehow this conflicts with the shader decomp rewrite. Should I close this issue or leave it open?

**Comment by goldenx86** [comment]
Yes, async shaders is strongly recommended to stay disabled.

**Comment by FernandoS27** [comment]
asynchronous shaders are known to cause graphic issues, it's the price you pay for them. It's a risky option.
