### ISSUE TITLE
[Feature Request] Limit Speed Percent & Uncap Framerate Combination

### ISSUE THREAD

**Issue by VPGx** [yuzu-emu/yuzu#6591]
Allow both "Limit Speed Percent" and "Uncap Framerate" options to be used in combination while emulating.

For example, if a game runs at 30fps, and the user wishes to run it at specific higher speed, they would Uncap the framerate, and set the limited speed percent to their choosing. Setting it to 200% would increase the maximum FPS to 60.

**Comment by OZtistic** [comment]
interesting idea I guess
I have a feeling this would cause more problems than it would solve, desync of timed service calls, kernel interruptions and complete desync of SVC and IPC calls. Sounds like a mess
Interesting idea though

**Comment by gidoly** [comment]
implemented recently
