### ISSUE TITLE
RAM consumption

### ISSUE THREAD

**Issue by Kalos6376** [yuzu-emu/yuzu#6592]
As you progress through the game Pokémon Shield, there is a gradual increase in the use of RAM until the emulator crashes.
Yuzu version 683
pc characteristics:
Ryzen 3600
ram 16gb 3200mgh
gtx 1650 super
game settings

![bY4rU97Pg40](https://user-images.githubusercontent.com/87235083/125166505-aa1f5b80-e1a4-11eb-802f-1e6ec3c94261.jpg)
![j7PQNKJvjA8](https://user-images.githubusercontent.com/87235083/125166507-ab508880-e1a4-11eb-9f4b-0e696931e0f5.jpg)
![DolnVMux2Rg](https://user-images.githubusercontent.com/87235083/125166510-ab508880-e1a4-11eb-87ec-4a97b53b6134.jpg)
![2oVgNAyRmmQ](https://user-images.githubusercontent.com/87235083/125166511-abe91f00-e1a4-11eb-8232-905f5ace816c.jpg)
![UrzT2y7sCqo](https://user-images.githubusercontent.com/87235083/125166512-abe91f00-e1a4-11eb-9603-f7c2db5aff7e.jpg)
![j-hBGIlJrms](https://user-images.githubusercontent.com/87235083/125166513-abe91f00-e1a4-11eb-96de-930fa0134019.jpg)

**Comment by german77** [comment]
This is a issue tracker not a support forum. Enable GPU cache garbage collection. Please consider using discord for this kind of issues
