### ISSUE TITLE
Catherine Full Body graphical issues and low fps on idle title screen cutscene

### ISSUE THREAD

**Issue by jochuan** [yuzu-emu/yuzu#6595]
After the Hades update Catherine Full Body is now finally rendering but there still a lot of graphical glitches happening in the game and all of them appear randomly so if you found a graphical glitch and then restart the emulator there is a possibility of that glitch to dissapear but then another thing will be rendering wrong. Here are some of them that i found:

Rin hair is glitched (Girl playing the piano)
![image](https://user-images.githubusercontent.com/11268912/125174655-52c9bd00-e19d-11eb-94cd-1c03a655233b.png)
![image](https://user-images.githubusercontent.com/11268912/125174665-6c6b0480-e19d-11eb-866a-56bed171fadb.png)

Corrupted fog
![image](https://user-images.githubusercontent.com/11268912/125174682-902e4a80-e19d-11eb-89e5-eb333ea285fc.png)

Texture corruption on some blocks and sometimes gold ingots
![image](https://user-images.githubusercontent.com/11268912/125174723-dbe0f400-e19d-11eb-9b3d-b30a921cfee9.png)

Also sometimes the facial animations of the main character become distorted. Other problem that i found is that the idle screen cutscene for some reason drops the fps significantly compared to other cutscenes of the game, in this particular cutscene i get around 14-19 fps while in the other cutscenes of the game i get around 25-30fps

![image](https://user-images.githubusercontent.com/11268912/125174892-c61ffe80-e19e-11eb-9274-f82028b5b14e.png)

The yuzu version used was EA 1867 and my specs are a Ryzen 5 3500u with a Radeon 540x.
Log: 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6795862/yuzu_log.txt)

**Comment by CrusadingNinja** [comment]
Asynchronous GPU emulation needs to be off in order for Catherine Full Body to render correctly.

**Comment by ele3131** [comment]
> Asynchronous GPU emulation needs to be off in order for Catherine Full Body to render correctly.

Can confirm here, after testing option by option, only Asynchronous GPU causes the Fog Glitch, without it the game is Playable although with slowdowns (20 ~ 25 fps), also it seems the performance drops overtime. (i7 7700HQ / GTX 1050 Ti Mobile).

Glad to see the game is playable, i finished it 2 times without major problems or workarounds.

**Comment by jochuan** [comment]
So i have been playing this game since EA 2031 and i didn't noticed the corrupted fog anymore also looks like the low fps on the idle title screen cutscene only happens if you are using gpu high. The only problems that are happening now are texture corruptions ( they are pretty rare to happen now different from before) and characters having distorting facial animations (happens everytime).

**Comment by dante3732** [comment]
Facial animations of the all character become distorted. The mouth may not move or textures may blink in the area of the eyes and mouth.

**Comment by dante3732** [comment]
On EA 2602, face animation works fine.

**Comment by gidoly** [comment]
should fixed on last ea and mainline feel free to reopen if still persist

**Comment by jochuan** [comment]
Well it is a different issue but for me now the game is hanging on the main menu with only sound playing
![image](https://user-images.githubusercontent.com/11268912/236340515-50ed74ba-7854-44a2-8f81-8f2f0f5e0efc.png)
