### ISSUE TITLE
Street Fighter 30th Anniversary - Upside Down

### ISSUE THREAD

**Issue by codbugpatrol** [yuzu-emu/yuzu#6603]
Game: Street Fighter 30th Anniversary

The game is upside down.
Using Early Access 1868. Mainline has the same problem.

Host CPU: AMD Ryzen 5 3600 6-Core Processor | AVX2 | FMA
Host OS: Windows 10 (10.0)
Host RAM: 15.93 GB
Host Swap: 19.53 GB
Driver: NVIDIA 466.77.0.0
Device: NVIDIA GeForce GTX 670
Vulkan: 1.2.168

![upsidedown_streetfighter_30_anniversary](https://user-images.githubusercontent.com/85196112/125183308-f5a92800-e1eb-11eb-92cb-bc76e9f4fd43.png)

**Comment by Immersion95** [comment]
I have an AMD card and it's working great, SOR4 unfortunately is upside down though.

**Comment by codbugpatrol** [comment]
@Immersion95, Axion Verge, Bastion have the same problem in my testing.

**Comment by codbugpatrol** [comment]
No longer happens on Yuzu EA 2074 and Nvidia driver 471.41.
