### ISSUE TITLE
xenobade chronicle 2 weird shadow on chacter head on cutscenes

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#6606]
seems xc2 have weird shadow issue while on cutscene (last cutscene of ch1)

yuzu:
![yuzu_iF0R7vObQV](https://user-images.githubusercontent.com/66776795/125191103-ac081e00-e27b-11eb-90d2-6bff07474b47.jpg)
switch:
![chrome_SGxgzRSDdr](https://user-images.githubusercontent.com/66776795/125191161-ea054200-e27b-11eb-9e57-37bfc44996ce.jpg)
issue part:
![ys](https://user-images.githubusercontent.com/66776795/125191207-410b1700-e27c-11eb-9d64-4eb143a8e991.jpg)
log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6796724/yuzu_log.txt)

**Comment by themasontwin** [comment]
yeah I've been having that same issue too 
![pyrap](https://user-images.githubusercontent.com/87954194/126918173-30b36564-e04b-40d7-a1ff-e85e3bcf3fca.png)

**Comment by gidoly** [comment]
also reproducable with xc de pretty faster than xc2 method.
Min menu > Even theater > Extra story > Facing the fog king video (3rd last on the list)

Issue look in the box you will noptice shadow on nene's head:

![yuzu_RzRtdBY6aC](https://user-images.githubusercontent.com/66776795/225173144-caedb80d-ae99-4230-a4f3-4aff1a292187.jpg)

how it should look:

![msedge_NPMha1SEJJ](https://user-images.githubusercontent.com/66776795/225173377-92d4a071-9943-4fc1-8db1-ccea71f8141d.png)

save:

[bfsmeria00.zip](https://github.com/yuzu-emu/yuzu/files/10974949/bfsmeria00.zip)

**Comment by jacky400** [comment]
Not too sure if Mario Spark also have similar shadow issue. When you move the angle , the scene will be rendered correct .

![image](https://user-images.githubusercontent.com/2836720/226097265-8e1c46d8-bb29-46c9-810b-5f760f1e07a5.png)
