### ISSUE TITLE
The Legend of Zelda Link's Awakening - Chomp Ball (Mario's Ball) Glitch/Issue

### ISSUE THREAD

**Issue by codbugpatrol** [yuzu-emu/yuzu#6608]
Game: 01006BB00C6F0000 | The Legend of Zelda: Link's Awakening (64-bit) | 1.0.1

Host CPU: AMD Ryzen 5 3600 6-Core Processor | AVX2 | FMA
Host OS: Windows 10 (10.0)
Host RAM: 15.93 GB
Host Swap: 19.53 GB
Driver: NVIDIA 466.77.0.0
Device: NVIDIA GeForce GTX 670
Vulkan: 1.2.168
 
Inside the game, in the area that have the chomp ball chained in a house. When you enter with Vulkan / Normal Accuracy the chomp ball do not appear. After enter in any other section of the game, the ball will present a big glitch that will go all around the screen.

IF you turn accuracy to HIGH, the chomp ball will go to normal.
IF you turn accuracy back to NORMAL, the chomp ball glitch will be fixed.

This make me wonder that this is a shader decompiler problem on the first run, something is wrong and fixing this maybe will fix other games with this kind of problem.

1) Chomp ball not showing (Vulkan, Normal Accuracy)
![ball1_TLOZLA](https://user-images.githubusercontent.com/85196112/125198103-df748980-e236-11eb-9188-5898aa3248f3.png)

2) Entering the  house  (Glitch starts) (Vulkan, Normal Accuracy)
![ball2_TLOZLA](https://user-images.githubusercontent.com/85196112/125198139-10ed5500-e237-11eb-8cf7-3c0be396f909.png)

3) Exiting the house (Glitch already running) (Vulkan, Normal Accuracy)
![ball3_TLOZLA](https://user-images.githubusercontent.com/85196112/125198156-23678e80-e237-11eb-9e22-3ea6aa3798eb.png)

4) Changing Accuracy to HIGH
![ball4_high_TLOZLA](https://user-images.githubusercontent.com/85196112/125198164-31b5aa80-e237-11eb-8560-33a67bc91c2a.png)

5) Changing Accuracy back to NORMAL - GLITCH IS FIXED
![ball5_normal_TLOZLA](https://user-images.githubusercontent.com/85196112/125198176-3aa67c00-e237-11eb-9d51-ec15d40b00d1.png)

In my humble opnion, this seems not to be related to the accuracy, but other thing compiling the shader wrong. And the accuracy compiles correctly e the shader stays. 

Error found in the log (no other error found other than this one):
...
 188.938169] Debug <Critical> video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298496 exceeds input size 8294400!
[ 188.938175] Debug <Critical> video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298512 exceeds input size 8294400!
[ 188.938179] Debug <Critical> video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298560 exceeds input size 8294400!
[ 188.938182] Debug <Critical> video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298576 exceeds input size 8294400!
[ 188.938188] Debug <Critical> video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298624 exceeds input size 8294400!
[ 188.938191] Debug <Critical> video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298640 exceeds input size 8294400!
[ 188.938198] Debug <Critical> video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298688 exceeds input size 8294400!
[ 188.938201] Debug <Critical> video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298704 exceeds input size 8294400!
[ 188.938208] Debug <Critical> video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8299008 exceeds input size 8294400!
[ 188.938211] Debug <Critical> video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8299024 exceeds input size 8294400!
[ 188.938217] Debug <Critical> video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8299072 exceeds input size 8294400!
...

**Comment by BSoDGamingYT** [comment]
Use high accuracy

**Comment by codbugpatrol** [comment]
@BSoDGamingYT, changing to HIGH make me my fps (as with many others) drop too much. I think that this must be verified by the development team, because this can fix other things, not only this game glitch. Different from other games, where the fix of a problem only occurs in the HIGH accuracy, in this case HIGH accuracy just fixes the glitch and the NORMAL accuracy maintain the fix, which is a different behavior so far.

**Comment by codbugpatrol** [comment]
@BSoDGamingYT why closing it ?

**Comment by BSoDGamingYT** [comment]
> @BSoDGamingYT, changing to HIGH make me my fps (as with many others) drop too much. I think that this must be verified by the development team, because this can fix other things, not only this game glitch. Different from other games, where the fix of a problem only occurs in the HIGH accuracy, in this case HIGH accuracy just fixes the glitch and the NORMAL accuracy maintain the fix, which is a different behavior so far.

If you arent able to run at fullspeed at high accuracy, your system has other problems. I have the same CPU and am able to run at over 100 FPS in this same area.

**Comment by codbugpatrol** [comment]
It is not about just the speed with a poor workaround, is the problem itselft. 
This have potencial, with the correct analysis of a proper developer, to work correctly. 
I'll create this issue many time as possible if you not reopen it.

**Comment by BSoDGamingYT** [comment]
> It is not about just the speed with a poor workaround, is the problem itselft.
> This have potencial, with the correct analysis of a proper developer, to work correctly.
> I'll create this issue many time as possible if you not reopen it.

Your provided information is factually incorrect and this is not a valid issue. If you wish to open one for "Lower performance in high accuracy mode" feel free. I have already given you the information as to why this issues statements are not true
