### ISSUE TITLE
The Legend of Zelda Link's Awakening - Lower Performance with High GPU Accuracy

### ISSUE THREAD

**Issue by codbugpatrol** [yuzu-emu/yuzu#6609]
Game: 01006BB00C6F0000 | The Legend of Zelda: Link's Awakening (64-bit) | 1.0.1

>>>>DO NOT CLOSE this without a proper developer analysis in the code and just a poor workaround.
Different from other games, where the fix of a problem only occurs in the HIGH accuracy (which drops de FPS to the ground), in this case HIGH accuracy just fixes the glitch and the NORMAL accuracy maintain the fix (and keeps the FPS OK), which is a different behavior so far.

Host CPU: AMD Ryzen 5 3600 6-Core Processor | AVX2 | FMA
Host OS: Windows 10 (10.0)
Host RAM: 15.93 GB
Host Swap: 19.53 GB
Driver: NVIDIA 466.77.0.0
Device: NVIDIA GeForce GTX 670
Vulkan: 1.2.168

Inside the game, in the area that have the chomp ball chained in a house. When you enter with Vulkan / Normal Accuracy the chomp ball do not appear. After enter in any other section of the game, the ball will present a big glitch that will go all around the screen.

IF you turn accuracy to HIGH, the chomp ball will go to normal but the FPS will drastically DROP.
IF you turn accuracy back to NORMAL, the chomp ball glitch will be fixed and FPS is OK again.

This make me wonder that this is a shader decompiler problem on the first run, something is wrong and fixing this maybe will fix other games with this kind of problem.

Chomp ball not showing (Vulkan, Normal Accuracy)

This make me wonder that this is a shader decompiler problem on the first run, something is wrong and fixing this maybe will fix other games with this kind of problem.

1) Chomp ball not showing (Vulkan, Normal Accuracy)
![ball1_TLOZLA](https://user-images.githubusercontent.com/85196112/125199038-d5ed2080-e23a-11eb-9143-0898ab21f4af.png)

2) Entering the house (Glitch starts) (Vulkan, Normal Accuracy)
![ball2_TLOZLA](https://user-images.githubusercontent.com/85196112/125199041-d84f7a80-e23a-11eb-9d54-4feafb1456ce.png)

3) Exiting the house (Glitch already running) (Vulkan, Normal Accuracy)
![ball3_TLOZLA](https://user-images.githubusercontent.com/85196112/125199049-e1404c00-e23a-11eb-92e7-e829a342a1e0.png)

4) Changing Accuracy to HIGH
![ball4_high_TLOZLA](https://user-images.githubusercontent.com/85196112/125199052-e3a2a600-e23a-11eb-89db-45ed29d4d20f.png)

5) Changing Accuracy back to NORMAL - GLITCH IS FIXED
![ball5_normal_TLOZLA](https://user-images.githubusercontent.com/85196112/125199063-ec937780-e23a-11eb-819d-ecdb29f4195d.png)

In my humble opnion, this seems not to be related to the accuracy, but other thing compiling the shader wrong. And the accuracy compiles correctly e the shader stays.

Error found in the log (no other error found other than this one):
...
188.938169] Debug video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298496 exceeds input size 8294400!
[ 188.938175] Debug video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298512 exceeds input size 8294400!
[ 188.938179] Debug video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298560 exceeds input size 8294400!
[ 188.938182] Debug video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298576 exceeds input size 8294400!
[ 188.938188] Debug video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298624 exceeds input size 8294400!
[ 188.938191] Debug video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298640 exceeds input size 8294400!
[ 188.938198] Debug video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298688 exceeds input size 8294400!
[ 188.938201] Debug video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8298704 exceeds input size 8294400!
[ 188.938208] Debug video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8299008 exceeds input size 8294400!
[ 188.938211] Debug video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8299024 exceeds input size 8294400!
[ 188.938217] Debug video_core\textures\decoders.cpp:operator ():70: Assertion Failed!
offset 8299072 exceeds input size 8294400!
...

**Comment by BSoDGamingYT** [comment]
As I said when you opened the last issue...the glitch is NOT fixed when you change back to normal accuracy. Please only provide accurate information when reporting issues

**Comment by codbugpatrol** [comment]
@BSoDGamingYT , ''As was stated above and on the last issue you opened, swapping back to normal accuracy does NOT fix the graphical corruption on the chain chomp''..., YES, IT DOES, see the screenshot 5. It may not fix in the literal way, but the problem stop while playing.

''This is not a shader decompiler issue, it is a buffer cache issue'', thanks for the analysis, so it is an issue as stated in the topic.

**Comment by BSoDGamingYT** [comment]
> @BSoDGamingYT , ''As was stated above and on the last issue you opened, swapping back to normal accuracy does NOT fix the graphical corruption on the chain chomp''..., YES, IT DOES, see the screenshot 5. It may not fix in the literal way, but the problem stop while playing.
> 
> ''This is not a shader decompiler issue, it is a buffer cache issue'', thanks for the analysis, so it is an issue as stated in the topic.

Can you post a full game log. I believe I know what your issue is, but need a log to confirm. Simply boot the game, close emulator and then post the log

**Comment by codbugpatrol** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6802250/yuzu_log.txt)

@BSoDGamingYT, as requested. Hope insight is right.

**Comment by BSoDGamingYT** [comment]
> [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6802250/yuzu_log.txt)
> 
> @BSoDGamingYT, as requested. Hope insight is right.

It was not what I believe it to be. 

Can you downgrade to base game version (1.0) and use this mod? Check if the game is any faster, or if you are being GPU limited by your GTX 670

Mod: https://cdn.discordapp.com/attachments/356187763139280896/724250990928461834/Stable-60fps-v2.zip

**Comment by codbugpatrol** [comment]
@BSoDGamingYT , checking here.
1) Changing to base version did not fix the glitch problem not even the high accuracy performance.
2) Adding the mod did not fix the glitch problem but fixes the high accuracy performance. Thanks. But is a workaround right ?

What do you think, keep this open so the developers fix also the glitch issue and the high performance issue ?

**Comment by BSoDGamingYT** [comment]
> @BSoDGamingYT , checking here.
> 
> 1. Changing to base version did not fix the glitch problem not even the high accuracy performance.
> 2. Adding the mod did not fix the glitch problem but fixes the high accuracy performance. Thanks. But is a workaround right ?
> 
> What do you think, keep this open so the developers fix also the glitch issue and the high performance issue ?

So high accuracy is not fixing the chain chomps rendering for you?

**Comment by codbugpatrol** [comment]
It does fix, but have to use a mod to make it work, is not natural of the emulator. But I will close this nevertheless . Thanks @BSoDGamingYT!

**Comment by FernandoS27** [comment]
> It does fix, but have to use a mod to make it work, is not natural of the emulator. But I will close this nevertheless . Thanks @BSoDGamingYT!

that's a different issue though.
