### ISSUE TITLE
Vulkan fixed DOAX3S graphical issues but OpenGL

### ISSUE THREAD

**Issue by jojorne** [yuzu-emu/yuzu#6610]
I just want to point that Yuzu EA 1867 Vulkan fixed graphical issues on characters' faces in DOAX3S but is still present in OpenGL (I've tested only GLASM). Feel free to close this report.

**Comment by BSoDGamingYT** [comment]
While we appreciate the report. these require the information asked for in the issue format. If this isnt provided in the next hour or so. I will close the issue

Info we need is as follows

- Build used
- Image of issues
- Reproduction steps if required
- Log after having run the game
