### ISSUE TITLE
AMD DK Tropical Freeze Issue

### ISSUE THREAD

**Issue by RinMaru** [yuzu-emu/yuzu#6612]
Windows 10
AMD RX 480 4GB Adrenalin 21.6.2
20GB DDR4 RAM
Ryzen 5 5600 6Cores 12 Threads

not related to HADES but is less severe on HADES

![Screenshot_2021-07-11_175602](https://user-images.githubusercontent.com/15071652/125211994-52522480-e278-11eb-99ff-f098bb24b231.png)
![Screenshot_2021-07-11_180929](https://user-images.githubusercontent.com/15071652/125211995-53835180-e278-11eb-8696-109268c243c0.png)

Log from mainline
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6797783/yuzu_log.txt)

**Comment by FernandoS27** [comment]
hmn, could be an issue with transform feedback and AMD.

**Comment by RinMaru** [comment]
> hmn, could be an issue with transform feedback and AMD.
> 
> Edit: Does this happen in OpenGL as well?

On mainline it's not an issue in GL. The updater won't let me roll back to EA so waiting on another build to go through to test on Hades

**Comment by benderscruffy** [comment]
on the latest EA and on mainline
it is still an issue
![Screenshot 2021-07-29 105114](https://user-images.githubusercontent.com/2696404/127424038-d986f3cf-dfe4-4195-8bb5-4bc6638692b3.png)
