### ISSUE TITLE
[Brawlhalla] [Iris Xe] [Vulkan] Upside down render

### ISSUE THREAD

**Issue by PacoAvelar** [yuzu-emu/yuzu#6616]
Game : Brawlhalla
CPU : i7 1165G7
GPU : Intel Iris Xe - Driver Version : 9670
Ram : 16GB
OS : win 11
Yuzu EA : 1869

Config: Default

Issue:
Game renders upside down.

Proof:
![image](https://user-images.githubusercontent.com/29181120/125240732-1a66d380-e2b0-11eb-9c74-86b1c44737fb.png)

log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6799013/yuzu_log.txt)

**Comment by goldenx86** [comment]
IIRC, viewport swizzles is needed to solve this on Vulkan.

**Comment by codbugpatrol** [comment]
Other games such: Axion Verge, Bastion and Street Fighter 30th anniversary has the same issue.

**Comment by PacoAvelar** [comment]
Solved

**Comment by german77** [comment]
fixed by #6765
