### ISSUE TITLE
Catherine full body graphical glitch

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#6626]
catherein full body seems have several graphic issues currently
pictures:
broken/black face of character model on right side of screen
![unknown-2](https://user-images.githubusercontent.com/66776795/125361276-0ef6d380-e3a8-11eb-8137-aac84b09d69e.png)
broken texture on piano and glass, broken shadow of ironstands

![](https://cdn.discordapp.com/attachments/708570691875897385/864261762751397959/unknown.png)

![](https://cdn.discordapp.com/attachments/708570691875897385/864262222547779624/unknown.png)

log:
[catherein.txt](https://github.com/yuzu-emu/yuzu/files/6804628/catherein.txt)
special setting
enabled cpu debug option context elimination for workaround glitches it could have caused other glitches

thanks to pepsiman94x from discord for letting me know these issues and provide log

**Comment by jochuan** [comment]
I don't know but maybe this is a duplicate of https://github.com/yuzu-emu/yuzu/issues/6595

**Comment by gidoly** [comment]
closing as duplicated
