### ISSUE TITLE
The Legend of Zelda: Link's Awakening isn't opening on GTX 1000-series using Vulkan

### ISSUE THREAD

**Issue by viniciuslira** [yuzu-emu/yuzu#6628]
In the 1866 version the game worked using asynchronous shader building, but since the 1867 version, in which this option was temporarily disabled, it is impossible to start ZLA using Vulkan on cards with Pascal architecture.

Host CPU: Intel Core i5-8300H | AVX2 | FMA3
Host OS: Windows 10 Pro 21H1
Host RAM: 16 GB
Driver: NVIDIA 471.11
Device: NVIDIA GeForce GTX 1050

log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6804898/yuzu_log.txt)

**Comment by Ba6yhulk** [comment]
Host CPU: Intel Core i7-10700K
Host OS: Windows 10 Pro 21H1
Host RAM: 32 GB
Driver: NVIDIA 471.11
Device: NVIDIA GeForce GTX 1070

I'm having the same issue. I've attached my logs in case they are of any use. I'm having what I believe to be the same issue in Empire of Angels IV. 
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6805801/yuzu_log.txt.old.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6805802/yuzu_log.txt)

**Comment by viniciuslira** [comment]
Mario + Rabbids also doesn't open using Vulkan, but further testing of other Pascal card users is needed to confirm that it's the same problem.

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6806252/yuzu_log.txt)

**Comment by v1993** [comment]
FYI, async shaders are enabled once again in latest builds. But 1866 introduces huge changes (#6585) in and out of itself and async shaders aren't likely source of trouble.

**Comment by viniciuslira** [comment]
Based on issue #6631 what is happening with Mario + Rabbids is not the same as with ZLA.

**Comment by v1993** [comment]
How did you concluded that? Your log from first message also ens with

```
[ 285.552677] Render.Vulkan <Critical> video_core\vulkan_common\vulkan_device.cpp:ReportLoss:590: Device loss occured!
```

Which is the exact same end result (device loss) as described in #6631. Now, those may have different origins (device loss is a very inexact error), but they also may have the exact same cause. More information is required to say for sure.

**Comment by viniciuslira** [comment]
I deduced that the source of the error is different, because the error with ZLA happens on boards with Pascal architecture. But issue #6631 happens on a GTX 660.

If the error can still have the same origin, then I take back what I said.

**Comment by v1993** [comment]
Well, it may be an error specific to Nvidia boards older than specific generation (e.g. they might lack some extension and extension-less codepath causes crash, or some driver quirk or many other things). What's for sure - driver responds the same way in both cases.

**Comment by Ba6yhulk** [comment]
> In the 1866 version the game worked using asynchronous shader building, but since the 1867 version, in which this option was temporarily disabled, it is impossible to start ZLA using Vulkan on cards with Pascal architecture.
> 
> Host CPU: Intel Core i5-8300H | AVX2 | FMA3
> Host OS: Windows 10 Pro 21H1
> Host RAM: 16 GB
> Driver: NVIDIA 471.11
> Device: NVIDIA GeForce GTX 1050
> 
> log:
> [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6804898/yuzu_log.txt)

Try this. I'm not sure if it will help devs narrow down the problem, but this has allowed me to get the game to boot:

1. Open yuzu and change the per game settings to OpenGL, GLASM, and turn async shaders off. Boot into gameplay. 
2. Go to emulation, stop (make sure you don't close yuzu)
3. Change the video backend back to Vulkan (keep async shaders off)
4. Boot the game. This usually works for me. If you can't get it to work, remove shaders.

**Comment by viniciuslira** [comment]
I tried this method and it worked. That's probably what I did in the 1866 version to open the game, but I thought it was the Async Shader turned on that had made the game boot.

I tried it on Mario + Rabbids too, but it didn't work.

log after this method:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6811223/yuzu_log.txt)

**Comment by v1993** [comment]
Does it also work if you boot into some *different* game in step one? (To be honest - just being curious. This is some odd behavior based on driver's internals that most surely doesn't point towards proper solution.)

**Comment by viniciuslira** [comment]
What bizarre behavior! I tried to do what you said. The random game I opened using OpenGL was Hyrule Warriors DE, then I opened ZLA using Vulkan and it worked!

**Comment by Ba6yhulk** [comment]
> Does it also work if you boot into some _different_ game in step one? Or, for the record, boot into ZLA on step 1 and then into M&Rabbids? (To be honest - just being curious. This is some odd behavior based on driver's internals that most surely doesn't point towards proper solution.)

Ok it gets even stranger. I wasn't sure if it would work using a different game first, so I ran pokemon sword in opengl, then ZLA and it booted. Which made me curious. I tried pokemon sword using Vulkan, stopped emulation, then ran ZLA. The first try, yuzu crashed when ending emulation under vulkan. Second try, ZLA booted. It seems like it's working as long as you successfully boot something else first without closing yuzu. I have better success deleting ZLAs shader cache first. The workaround seems to stop working if this gets too large. 

That being said, I'm glad this is working for other people. I was starting to think I was going crazy.

**Comment by Ba6yhulk** [comment]
> I tried this method and it worked. That's probably what I did in the 1866 version to open the game, but I thought it was the Async Shader turned on that had made the game boot.
> 
> I tried it on Mario + Rabbids too, but it didn't work.
> 
> log after this method:
> [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6811223/yuzu_log.txt)

I think you were on to something with the async shader option on version 1866. I was able to get it to work using this method, but it's stopped working for me as well and I can't figure out why. I had already figured out the workaround I posted when I find the async fix, so I know it wasn't that.

**Comment by v1993** [comment]
It looks like booting some other game first changes something in driver's internal state which prevents it from breaking on whatever causes it to break. Moreover, loading big shader cache probably causes driver's *own* cache to overflow or something, causing error once again. Drivers are full of performance-oriented tricks that (rightfully) assume valid input, go figure...

**Comment by viniciuslira** [comment]
Apparently the problem was solved, I don't know if by the latest driver from Nvida, 471.41, or by some update from Yuzu. In version 1909, the problem is no longer happening, so the workaround discovered by user @Ba6yhulk is no longer needed.

Confirmation of other users with 1000 series cards is necessary to ensure that the problem has been resolved and to confirm whether by driver or by a Yuzu update.

**Comment by Ba6yhulk** [comment]
> Apparently the problem was solved, I don't know if by the latest driver from Nvida, 471.41, or by some update from Yuzu. In version 1909, the problem is no longer happening, so the workaround discovered by user @Ba6yhulk is no longer needed.
> 
> Confirmation of other users with 1000 series cards is necessary to ensure that the problem has been resolved and to confirm whether by driver or by a Yuzu update.



> Apparently the problem was solved, I don't know if by the latest driver from Nvida, 471.41, or by some update from Yuzu. In version 1909, the problem is no longer happening, so the workaround discovered by user @Ba6yhulk is no longer needed.
> 
> Confirmation of other users with 1000 series cards is necessary to ensure that the problem has been resolved and to confirm whether by driver or by a Yuzu update.

It looks like it was fixed on yuzu's end. I just tested both games I had issues with workout updating my driver. Both worked!

**Comment by viniciuslira** [comment]
Problem solved
