### ISSUE TITLE
[The Last Remnant Remastered] Voices/Some of the SFX does not play at all

### ISSUE THREAD

**Issue by fayaine** [yuzu-emu/yuzu#6633]
Yuzu Early Access 1874/ Mainline 686

Ryzen 5 5600X
16GB DDR4
RTX 3070
Latest Win 10

The Last Remnant Remastered

Upon starting the game the music plays just fine but most SFX and Voices in the game do not play at all.
Easy to reproduce since the game just needs to be booted.
Most noticeable by the character usually screaming "Let's do this" when being on the field and pressing ZR to innitiate fights.
All battle SFX like swords and other sound is also missing with just the music playing.

A video showing of the issue is available here : https://drive.google.com/file/d/1KJ88po_hpQGRWK7Becge-hPJLIjN5QYX/view

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6810233/yuzu_log.txt)

**Comment by DCS78** [comment]
I have had the same issue. I don't think I the audio loss occurred before Project Hades (I believe it was) dropped. Despite some graphical glitches the least the game is playable. Running v1.0.1 of the game and 12.1.0 firmware.

**Comment by fayaine** [comment]
The issue also exists pre hades. I tried the latest main line has the same issue

**Comment by gidoly** [comment]
fixed with project andio
