### ISSUE TITLE
Trivial Pursuit Live is crashing on Vulkan 

### ISSUE THREAD

**Issue by Shinzuh** [yuzu-emu/yuzu#6634]
- Nvidia 2080 super 
- Intel(R) Core(TM) i7-10875H
- 16gb  Ram

How to reproduce : 

- Vulkan
- Launch a game
- Select characters, set ready and launch
- Lock then crash during the loading
![image](https://user-images.githubusercontent.com/13969521/125496378-66aa2f4e-ee71-4dc6-a088-ea32a833c37d.png)

Logfile : 
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6810768/yuzu_log.txt.old.txt)

**Comment by v1993** [comment]
Does this happen on pre-Hades builds (e.g. mainline) as well?

**Comment by Shinzuh** [comment]
Yes, It used to work months ago, I'll test pre-bcr/tcr in some hours.

**Comment by v1993** [comment]
Ah, it would be especially great if you could find out what exact build introduced the regression.

**Comment by Shinzuh** [comment]
Will do right now

**Comment by Shinzuh** [comment]
Yuzu Mainline 554 is the last working build on Vulkan for me. After this one the crash at loading (issue/screen above) occur.

**Comment by v1993** [comment]
Looking at changes in mainline 555, it's probably caused by PR #5989. Looks like this game manages to hit the new limit, which likely needs to be increased a little bit.

**Comment by codbugpatrol** [comment]
Maybe this is related to https://github.com/yuzu-emu/yuzu/issues/6604
Where I can find the mainline 554 to check ?

**Comment by v1993** [comment]
@codbugpatrol I really doubt it is, but you can get mainline 554 here: https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-554.

**Comment by codbugpatrol** [comment]
@v1993 you are absolutely right. Dragon ball still crashes on that (Vulkan), unfurtunatelly =(

**Comment by Shinzuh** [comment]
I can now confirm the bug is caused by PR #5989. I reverted it in the latest mainline and managed to get the game launching after the loading phase : 
![image](https://user-images.githubusercontent.com/13969521/125741970-f5d44617-eac4-4cc9-b289-22688a6b96f8.png)

By the way, 64 seems to be the least for the game to pass throught the loading. (32 and less crashs).

**Comment by Shinzuh** [comment]
Seems like #6669 fixed this issue. It now work like a charm !

**Comment by Shinzuh** [comment]
Nevermind, the game crash when the party is finished at the loading screen which should lead to the menu.

**Comment by FernandoS27** [comment]
you seem to be able to compile the game. Do you use Visual Studio by any chance? It would be useful if you ran the game with a debugger (you must enable CPU debugging and disable Host MMU to avoid unnecessary breaks)

**Comment by Shinzuh** [comment]
![image](https://user-images.githubusercontent.com/13969521/126121683-8498dcac-3e29-41a2-a83f-24b0158f61a2.png)
 This time the game crashed at the first loading phase (the one which I initially talked about). Feel free to ask for more.

**Comment by v1993** [comment]
Can you, please, include backtrace into your screenshot (or just post backtrace, for that matter)? Right now it's only apparent that some Vulkan function have failed.

**Comment by FernandoS27** [comment]
What's the result?

If it's device loss then, it's hard to debug without Nvidia Aftermath.

**Comment by Shinzuh** [comment]
If you are talking about this : 
![image](https://user-images.githubusercontent.com/13969521/126159171-aed90322-3f4b-4129-8344-36258592dd95.png)
Here is it : 
![image](https://user-images.githubusercontent.com/13969521/126159195-cf0421cd-0736-476e-aff6-1997603ef02d.png)
If not I'll be happy to learn how to do it

**Comment by v1993** [comment]
Yup, that's what I've been talking about. And what @FernandoS27 asks for is probably shown under "exception parameters" (I've never used VS, but it seems reasonable).

**Comment by Shinzuh** [comment]
![image](https://user-images.githubusercontent.com/13969521/126180151-43029e5b-adb4-4760-a3a0-7fab45e889fa.png)
![image](https://user-images.githubusercontent.com/13969521/126180280-ac1596c8-dac4-422e-92cf-8fdf0c71c068.png)

**Comment by v1993** [comment]
That doesn't seem to tell much. Can you inspect value of variable "result"?

**Comment by Shinzuh** [comment]
![image](https://user-images.githubusercontent.com/13969521/126184785-1f6e3320-f4a2-4340-a8e5-f676d959ddeb.png)

**Comment by v1993** [comment]
So, have it crashed in another place this time? Also, it looks like error is `VK_NOT_READY`, which is more of (unexpected by yuzu) status than error.

**Comment by Shinzuh** [comment]
On vk_query_cache yes. 
![image](https://user-images.githubusercontent.com/13969521/126188807-18e9e95a-c091-4475-b073-f319c7bca2df.png)
It's may be because BlinkHawk suggested me on Discord to add **"#pragma optimize("", off)"** at the top of the file where it was crashing for to obtain the result value : 
![image](https://user-images.githubusercontent.com/13969521/126188963-05213944-0d48-4c3f-9f5b-324230c0f81e.png)

**Comment by benderscruffy** [comment]
@FearlessTobi 
doesnt crash out on Vulkan anymore
can be closed
