### ISSUE TITLE
MINGW64 build fails to start up

### ISSUE THREAD

**Issue by gyorokpeter** [yuzu-emu/yuzu#6643]
I tried to follow the instructions at https://github.com/yuzu-emu/yuzu/wiki/Building-For-Windows for MINGW64. I had to make a few changes (e.g. move the .conan directory to the D: drive, and touching a standard library file that otherwise made the Boost build fail). Now the build succeeds, however when I run yuzu.exe it just quits without doing anyhting. It doesn't seem to create any logs in %APPDATA%/yuzu/log.
yuzu-cmd.exe is a bit better, at least it prints something on the console. However when I try to load a rom with it (it's a game with a BASE and an UPD .nsp file, for this experiment I'm passing in the full path to the BASE one) it crashes with a bad_alloc:
```
[   4.734321] HW.Memory <Debug> core/memory.cpp:MapPages:557: Mapping 00000000B3C00000 onto 000000100B204000-000000100B304000
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
Even though the same game does launch successfully with the binary download version of yuzu.

**Comment by v1993** [comment]
About that message - does it go away if you disable fastmem in yuzu-cmd's config?

**Comment by lat9nq** [comment]
If you try running `yuzu.exe` from the terminal, what output do you get?

**Comment by lat9nq** [comment]
The error you are likely running into is that the bundled FFmpeg libraries were not copied to the bin directory. Dor running `cp -v externals/ffmpeg*/bin/*.dll bin/` from the build directory solve it?

**Comment by gyorokpeter** [comment]
```
D:\Projects\other\yuzu\build\bin>dir
 Volume in drive D has no label.
 Volume Serial Number is 6A71-E290

 Directory of D:\Projects\other\yuzu\build\bin

2021. 07. 14.  08:59    <DIR>          .
2021. 07. 14.  08:59    <DIR>          ..
2021. 02. 09.  20:41         3 121 166 avcodec-58.dll
2021. 02. 09.  20:41           657 422 avutil-56.dll
2021. 07. 06.  10:21            82 097 libgcc_s_seh-1.dll
2021. 01. 09.  11:49           205 953 liblz4.dll
2021. 07. 06.  10:21         1 745 041 libstdc++-6.dll
2021. 07. 14.  08:51           684 097 libusb-1.0.dll
2021. 06. 28.  09:07            59 643 libwinpthread-1.dll
2021. 05. 15.  06:58           999 818 libzstd.dll
2021. 07. 11.  21:51         7 051 998 Qt5Core.dll
2021. 04. 14.  15:24         9 446 658 Qt5Gui.dll
2021. 04. 14.  15:24         8 922 361 Qt5Widgets.dll
2021. 02. 09.  20:41           551 438 swscale-5.dll
2021. 07. 14.  08:54         2 902 747 tests.exe
2021. 07. 14.  08:54        29 544 645 yuzu-cmd.exe
2021. 07. 14.  08:55        32 597 625 yuzu.exe
              15 File(s)     98 572 709 bytes
               2 Dir(s)  465 948 344 320 bytes free

D:\Projects\other\yuzu\build\bin>yuzu

D:\Projects\other\yuzu\build\bin>
```
So there is no message. Originally it did complain about all of those DLLs so I had to copy them over, and that's not just the ffmpeg ones.

What do I have to change to disable fastmem?

**Comment by gyorokpeter** [comment]
Looks like the behavior is different if I run the executable by double-clicking it. It complains about more DLLs then. But since there are so many I just made this launch script:
```
set PATH=D:\msys64\mingw64\bin;D:\Projects\other\yuzu\build\externals\ffmpeg-4.3.1\bin;%PATH%
bin\yuzu
```
But when I try to launch it, it complains about not being able to find the entry point of ```_ZdaPv``` in Qt5Gui.dll.

**Comment by benderscruffy** [comment]
can be closed
