### ISSUE TITLE
[Feature Request] Let us decide the deadzone of controller triggers (right now the input is registered at 80% of pressure)

### ISSUE THREAD

**Issue by SixelAlexiS90** [yuzu-emu/yuzu#6644]
Hello! Basically Yuzu (both latest stable version and Early Access version) register trigger inputs almost at full pressure (around 80% more or less) and it's quite annoying.
I've made a video to easily show the behavior (it was too big to attach as a file):
https://www.youtube.com/watch?v=Lj9K-dMxtFs

Here a video from another user showing it live in a game with an Xbox One controller:
https://streamable.com/t0c95s

I've tried with the Dualshock 4 too and it's the same, it's something related to how Yuzu handle inputs. 

The fact that ZL and ZR are digital inputs makes the matter even more annoying, since the soon you read the input the better, the fact that you have to press the triggers almost all the way down gives an unresponsive feedback.

I think that this really need a specific function to adjust the deadzone of the triggers to decide if inputs are going to be registered as soon you press it or at specific grade of pressure, especially since all other aspect of controller support are highly customizable, it would be really useful to have something for triggers too, thanks.

**Comment by german77** [comment]
50% to be precise. I will probably will add this at some point

**Comment by SixelAlexiS90** [comment]
> 50% to be precise. I will probably will add this at some point

It's definitely more then 50%, no doubt on that since you can see it from the video but thank you very much for looking into this <3

**Comment by german77** [comment]
50% no doubt. In the mean time you can modify the threshold manually in "%appdata%/yuzu/config/qt-config.ini".
Search for the line player_0_button_zl="..." set the threshold to a different value

**Comment by SixelAlexiS90** [comment]
> 50% no doubt. In the mean time you can modify the threshold manually in "%appdata%/yuzu/config/qt-config.ini".
> Search for the line player_0_button_zl="..." set the threshold to a different value

Nope, the threshold is wrongly configured, once at "0.0" it actually start from 50% of pressure.
If you put "0.5" (aka default) then it start from 75% of pressure (make sense since is halfway between 50% and 100%).

I've did various test and I confirm is like this, since at "0.1" it start at little more over 50% of pressure and so on.
At "0.9" it activate at the very and of the course and at "1.0" it doesn't activate at all (I guess it goes in conflict with a 100% state).

At that point I've tried negative values and I confirm that it works, so:

"-0.5" = 25% of pressure
"-0.9" = it start after a tiny bit
"-1.0" = 0% of pressure, so it start right away

So yeah, something got messed up with the threshold but it looks easily fixable.

**Comment by german77** [comment]
That's weird. If I recall correctly the analog values aren't negative at all. But your claims make sense if -1 is not pressed and 1 is fully pressed. If this is true the default threshold value should be changed to zero. Please test with both triggers and if posible with other controller brands like PS4, PS5 or xbox360

**Comment by SixelAlexiS90** [comment]
> That's weird. If I recall correctly the analog values aren't negative at all. But your claims make sense if -1 is not pressed and 1 is fully pressed. If this is true the default threshold value should be changed to zero. Please test with both triggers and if posible with other controller brands like PS4, PS5 or xbox360

I've tested this with a Dualshock 4 controller and Xbox One S controller, they both shows the same results on both triggers (you just have to modify the "qt-config.ini" again since the threshold value got resetted once you change controller).

Yeah, the changes are really linear, it's mathematically perfect in this sense, since the pressure bar from the windows control panel is linear aswell, so you can easily see how much % you are pressing.

The only little weird thing of using at "-1.0" is that once you start the Yuzu controller test or a game, they will read the triggers in an always active state, but you just have to press them once to make them working, at that point there is no false input or so during gameplay or while being fully released.

It makes sense that Yuzu is probably confused at start since you have a 0% value but once you press them and make Yuzu "read" the triggers, from that moment they works perfectly just as soon as you press them, VERY satisfying :)
