### ISSUE TITLE
Audio issues in specific games

### ISSUE THREAD

**Issue by EgoBizarro** [yuzu-emu/yuzu#6645]
I've always had an audio issue with yuzu (and until recently thought it's just a general problem that everyone's having, but on the discord server I was told otherwise).
In specific games, I get sound pops every few seconds (not in regular intervals, though). I'm sure there were a few more but right now I can say it's in ACNH, Monster Hunter Stories 2 and - the worst of them - BotW (that one sounds pretty much distorted all the time).
I've tried all kinds of settings in yuzu, audio backends, audio setups, audio stretching, no multicore, etc.
I also tried changing stuff in my audio driver and windows audio setup; had also re-installed Windows fresh at some point. Nothing helped with the issue.
As to what could cause the issue, I don't know. Especially strange is that most games' audio is fine, e.g. SMO, even when it goes below full speed. In the affected games, slowdowns and loading stuff seems to make the issue worse - however, it persists at all times, even in very untaxing moments (like on simple menu screens).
I'm thinking, maybe yuzu is somehow incompatible with my sound card, a Creative Sound Blaster Z. 

Specs: 
Intel Core i5-4690K 
16GB RAM
Geforce GTX 1070
Creative Sound Blaster Z

Using yuzu mainline version 687 right now, but the issue has been there a looong time, maybe even as long as yuzu has had audio support.

[sorry for the zips, github wouldn't let me upload mp3 format]

[ACNH.zip](https://github.com/yuzu-emu/yuzu/files/6816327/ACNH.zip)
[BotW.zip](https://github.com/yuzu-emu/yuzu/files/6816328/BotW.zip)

**Comment by EgoBizarro** [comment]
So, it seems I'm not the only one with the issue. In this video I hear the same kind of slight audio distortion /pops that I'm having. It's not nearly as easy to hear as in my BotW example, but you can hear it (at least I can, and I found it pretty annoying). You hear it best when there's music, e.g. here: https://youtu.be/BP3FblYReyk?t=600

**Comment by ChocoChopin** [comment]
I'm having exactly this problem with Skyward Sword, and have also troubleshooted in all the ways you've mentioned. Yes, the fact that this is only happening in select games while most other games (especially games that have had a lot of individualized compatibility updates, like Fire Emblem, which definitely used to do this but no longer does) have no audio issues tells me that it's a problem with Yuzu's audio pipeline being unable to accommodate every game's quirks.

**Comment by EgoBizarro** [comment]
Do you have a sound card installed, perchance?

**Comment by ChocoChopin** [comment]
No sound card, only onboard audio for me. And actually, I'm noticing it happening in other games too--it's just not equally obvious in all of them.

By comparison, Ryujinx has no audio crackling whatsoever, but it also seems to have significantly more audio lag. I'm guessing the problem is that Yuzu's audio pipeline just has too small of a default buffer, and there isn't any kind of option to adjust the audio buffer.

**Comment by EgoBizarro** [comment]
Ok, so I guess it's not just a one-off compat issue with my sound card, then. 
Yeah, in Ryujinx my audio is always crystal-clear. Actually, I have no such issue in any other emu or game or program whatsoever.
Yeah, might have something to do with buffering, I don't know.

**Comment by ChocoChopin** [comment]
If you ever use RetroArch, you can turn the audio latency down (which reduces the audio buffer) and get basically the same thing--intermittently staticy/crackly audio, which can vary by individual game and platform emulated but all ultimately sounds pretty similar. Just based upon the character of the audio, I'm guessing the same thing is happening here. I really wish I could just dig into the code and adjust the audio buffer to test the theory out, but that would probably take me way too long to figure out how to do.

**Comment by Ryrin45** [comment]
Just want to add that I'm getting the same thing in the recently release Tsukihime remake. Intermittent audio popping that doesn't exist in Ryujinx. The only setting I could find that eliminates the problem is turning off multicore CPU emulation. Which also causes a significant drop in performance so it's not a practical solution, but I figure the issue must have something to do with how audio works when multicore CPU emulation is turned on.

**Comment by EgoBizarro** [comment]
Hm, well, at least in ACNH when inside and the game is at full speed, indeed there is no popping without multicore while there is some with it enabled. 
Except for those pops (which even seems to happen at full speed sometimes), there's this awful crawling, dragging audio (as can be heard in my sound sample for BotW in my original post) which seems to happen when the game doesn't reach full speed.
However, there's no such issue in Ryujinx, even when the FPS is lower there.
Maybe the way yuzu's threading works kinda chokes the audio thread or something when the graphics thread is struggling? (I don't know how these things work)

**Comment by vivi3107** [comment]
Try to set Yuzu's priority to "high" in task manager.

**Comment by EgoBizarro** [comment]
What the heck? I did not think that would do anything; but it totally does! I thought by this point Windows should have figured out when a program needs more resources. 
After testing those three games (just a bit, but the difference is immediately clear), I've heard no popping. I did have one or two very short audio cut-outs (like, no audio at all for a quarter second or something), but that was when running around in BotW with no shader cache, so I can live with that.
Also, it's not just that there's no audio popping. Performance is also much better, especially in BotW (stable 30 instead of a weird up-and-down between 23 and 30 every 2-3 seconds).
Any idea why this would be only the case in some people's systems? Or would it be the same for everyone with a rather old CPU?
Windows still doesn't have a function to save the priority setting for specific programs, eh?

**Comment by vivi3107** [comment]
> Windows still doesn't have a function to save the priority setting for specific programs, eh?
Right click the Yuzu's shortcut, select Properties and type the following in the Target area.
`C:\Windows\System32\cmd.exe /C start /high C:\[path to yuzu folder]\yuzu.exe`

**Comment by EgoBizarro** [comment]
That didn't quite seem to work. However, this did.
C:\WINDOWS\System32\cmd.exe /c start "runhigh" /high "C:\[path to yuzu folder]\yuzu.exe"

Thanks a lot for your advice!
I guess this issue can be closed...? Though maybe it's worth a look into why this makes such a gigantic difference in yuzu while there's no difference in Ryujinx when changing the priority.
And if it's not possible to change this, maybe this tip (putting yuzu in high priority) should be more prominent so that users can see it, pinned on the discord channel or in the user's guide or whatever.

**Comment by Ryrin45** [comment]
Ah I guess my issue is different then because setting Yuzu to high priority in task manager does not make a difference.

**Comment by Luukuton** [comment]
Just reporting that I'm not experiencing the intermittent audio popping in Tsukihime remake anymore, at least with the latest mainline version 860. 

Same specs as above aside from some minor Windows and driver updates.

> ### Environment
> * OS: Windows 10 64-bit (version 21H1, OS Build 19043.1415)
> * CPU: AMD Ryzen 5800X
> * GPU: AMD Radeon RX 6800XT 16GB
> * RAM: G.Skill 32GB Flare X DDR4 3600MHz CL16
> * SSD: Samsung 980 PRO PCIe4 1TB (C drive, Yuzu and game located here)

**Comment by EgoBizarro** [comment]
Hm, yeah, I guess your issue was another one than mine. For me it's still the same: I always need to have yuzu running at high priority to get mostly smooth sound in those games (though BotW is still not great).

**Comment by Luukuton** [comment]
It could be that there has been some optimizations to Yuzu that allows my setup (afterall 5800X is a top of the line CPU) to run at least Tsukihime without the issue. Obviously there might still be issues with other heavier games.

**Comment by EgoBizarro** [comment]
So, this issue seems to be fixed in Early Access 2667. I don't even need to run yuzu at high priority anymore to have stable audio. Complete audio cutouts for half a second that I got in BotW frequently are also gone. 
So this issue seems to have something to do with low thread count or generally older CPUs.
A pity the mutex change had to be reverted (I didn't have any issues on SSBU, btw). I hope it'll come back in some form.
