### ISSUE TITLE
ACA NEOGEO METAL SLUG - 0100EBE002B3E000 no music or sound fx

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#6646]
tried yuzu 687 and EA 1880
no music or sound fx at all
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6821378/yuzu_log.txt)

**Comment by Galcian79** [comment]
So this is a specific game issue indeed. Bad choice for testing yuzu on my Linux system :\

**Comment by benderscruffy** [comment]
has music and sound fx now
