### ISSUE TITLE
AMD Vulkan specific crashes on Team Sonic Racing

### ISSUE THREAD

**Issue by Moonlacer** [yuzu-emu/yuzu#6650]
Team Sonic Racing seems to not be able to render any 3D objects on AMD Vulkan without crashing. After the game crashes, booting into the game is impossible because it crashes after the shaders load, making it impossible to load in without deleting the Vulkan shader cache. It also just appears to happen on AMD hardware, I had Law in the Discord server test on his Nvidia system using Vulkan, and it at least loaded the character menu and even went into a race, along with zero crashing from his reports.
Test for reproducing:
![image](https://user-images.githubusercontent.com/79172044/125844839-194beca9-d017-473f-badd-0d5665349010.png)
![image](https://user-images.githubusercontent.com/79172044/125844886-1b1d0117-4dd6-4d3e-a29c-d3b5ef8444f6.png)
![image](https://user-images.githubusercontent.com/79172044/125844920-7c90b99b-1936-446b-bb47-463eec1feef0.png)
![image](https://user-images.githubusercontent.com/79172044/125844985-526d1602-4b0f-4f9c-be13-db1cdec9f825.png)
The last picture is the last thing seen before the game crashes when it loads the character selection menu
It does work on OpenGL, but AMD's OpenGL is horribly slow
Picture of OpenGL:
![image](https://user-images.githubusercontent.com/79172044/125845513-572797db-110d-422a-a013-96101d67ed4c.png)

My Specs:
Ryzen 3 3100
RX 480 4gb
16gb RAM

Law's Specs:
Ryzen 9 3900x
GTX 1070ti
32gb RAM

Tested on latest EA 1883
Thanks for looking into it!
Let me know if any more information is needed :)

**Comment by Moonlacer** [comment]
![Screenshot from 2021-07-24 18-01-35](https://user-images.githubusercontent.com/79172044/126883361-8de8e0dc-6d06-4341-aa20-9afe2f7bcd47.png)
While the game loads and runs on RADV using latest Mesa, all characters float in the air above their cars
Sorry for the bad screenshot, it's hard to get a windowed screenshot on Linux while keeping all characters cars in frame

The original issue opened was on Windows, this is a Linux issue

**Comment by Moonlacer** [comment]
Long overdue for retesting, will reopen if the issue persists

**Comment by RinMaru** [comment]
![010092b0091d0000_2023-05-12_18-46-59-491](https://github.com/yuzu-emu/yuzu/assets/15071652/439ed7c6-b96c-48d3-b5b7-17656111383f)
graphics are currupted thats about it
