### ISSUE TITLE
Bravely Default II - Audio Stuttering

### ISSUE THREAD

**Issue by cupelix1** [yuzu-emu/yuzu#6662]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6833512/yuzu_log.txt)

**Comment by german77** [comment]
How to reproduce? what part of the audio stutters? Please be a little bit more descriptive

**Comment by cupelix1** [comment]
I have an Intel I7-8700 and Nvidia 1660 Pro TI Video card, the audio has a bunch of static in it playing music or voice SFX this has not only been confirmed by me but a few friends who have tried it. I tested on Ryujinx and this does not occur thus is a problem with Yuzu.

**Comment by cupelix1** [comment]
This happens at very beginning of the game btw

**Comment by tet666** [comment]
This might be related to the very uneven frametimes this game has in both vulkan and ogl (screen is only vulkan since it looks exactly the same ogl).

![yuzu_2021_07_18_12_45_16_718](https://user-images.githubusercontent.com/35034841/126064489-6c8cfcbb-ac33-4292-8122-1223e86916e4.jpg)

**Comment by cupelix1** [comment]
https://www.youtube.com/watch?v=r_HsGzyJSL8

Please see linked video for exact problem at timestamp 3:16

**Comment by cupelix1** [comment]
With some advice from a friend, it seems by using Vulkan instead of OPENGL fixes the problem with audio. Guess from now on I will have to test game compatibility first with OPENGL and then Vulkan before posting here.

Cupe
