### ISSUE TITLE
Luigi's Mansion 3 - Black image after video cutscenes

### ISSUE THREAD

**Issue by fer2346** [yuzu-emu/yuzu#6664]
Happened 2 times: 
on the 13th floor (get a call e.gadd requiring you to go to the lab) 
And the 15th floor when a video is shown on the room entrance.

All but the HUD display goes black.

Video Sample from the 13th floor:

https://youtu.be/gHjoiYUUvBU

Tried on vulkan, all 3 variants of opengl, disabled 60fps and dynamic resolution mods, disabling NVDEC i could hear the video sound, but no image, after the video image goes black too.

I've found that if a enter (blind) to the elevator, i get 3d image back, going to a different floor makes the game go normal)

Unfortunately i could not grab a .log file to post here, as i finished the game and it doesn't allows to repeat these scenes.

SYSTEM SPECS:
Yuzu Version: yuzu Early Access 1879
CPU: Intel Core i5-6400 CPU @ 2.70GHz | AVX2 | FMA
RAM: 16GB 
VIDEO: Nvidia GTX 1060 6 GB - Driver 471.11
Windows 10 21H1

**Comment by CaptV0rt3x** [comment]
Piracy is strictly prohibited and you will not recieve any support.
