### ISSUE TITLE
Luigi's Mansion 3 - Broken Reflections on OPENGL

### ISSUE THREAD

**Issue by fer2346** [yuzu-emu/yuzu#6665]
Happens on 13th floor, there's a puzzle to solve using mirrors, 
Using any of the 3 opengl variants (introduced in Project Hades) 
Works ok in vulkan:

OPENGL
https://youtu.be/6rTuWq186q4 
(something is wrong too with luigi's shadow)

VULKAN
https://youtu.be/DoPI5YXl3B8

Noticed something strange triggering the bug on the 15th floor mirrors (OPENGL):
https://youtu.be/UiVWZKeVAwc

SPECS:
Yuzu Early Access 1884
CPU: Intel Core i5-6400 
RAM: 16GB
VIDEO: Nvidia GTX 1060 6 GB - Driver 471.11
Windows 10 21H1

LOG 
[yuzu_log.txt.old - opengl.txt.zip](https://github.com/yuzu-emu/yuzu/files/6834461/yuzu_log.txt.old.-.opengl.txt.zip)

SAVE STATE To the training rrom on 13th floor : 
[Luigis mansion 3 - savestate - training room - 0100DCA0064A6000.zip](https://github.com/yuzu-emu/yuzu/files/6834464/Luigis.mansion.3.-.savestate.-.training.room.-.0100DCA0064A6000.zip)

**Comment by CaptV0rt3x** [comment]
Log shows pirated content. Piracy is strictly prohibited and you will not receive any support.
