### ISSUE TITLE
No more Parsec button overlay since EA<640~750

### ISSUE THREAD

**Issue by Betamarrajr** [yuzu-emu/yuzu#6674]
Hello,
It's since yuzu Early Access <640~750 that when using yuzu with parsec, 
the overlay that should appear on the screen (the chat and the button on top of left corner) won't appear anymore

![Acquisisci](https://user-images.githubusercontent.com/58048418/126062246-d2e273b6-c6a0-4e49-890d-ca70d9f8213c.JPG)

I'm talking about that overlay
I know it's not an urgent Bug to resolve, but it would be good since it was already working on older version , so maybe it's an easy fix :D

**Comment by OZtistic** [comment]
Does this happen on current EA? 
EA 640 to 750 is well over a year ago now
Please test on latest EA and mainline and report back

**Comment by Betamarrajr** [comment]
Yep it happened from 750> till the current build , i've tried also with evry update , but none of them shows the overlay

**Comment by Betamarrajr** [comment]
> 
> 
> Does this happen on current EA?
> EA 640 to 750 is well over a year ago now
> Please test on latest EA and mainline and report back

Yep it happened from 750> till the current build , i've tried also with evry update , but none of them shows the overlay

**Comment by german77** [comment]
EA are hard to track. if you can find a mainlime version it would be a lot better

**Comment by Betamarrajr** [comment]
> 
> 
> EA are hard to track. if you can find a mainline version it would be a lot better

mainline-0-350 the overlay it's working , i will test upper version and i will report ;)

**Comment by german77** [comment]
This is the PR that made it fail. Sadly it was removed because it had performance issues #4692

**Comment by Betamarrajr** [comment]
> 
> 
> This is the PR that made it fail. Sadly it was removed because it had performance issues #4692

So, i think unfixable.....sadge
Thanks
