### ISSUE TITLE
MSVC: Access violation in debug mode

### ISSUE THREAD

**Issue by gyorokpeter** [yuzu-emu/yuzu#6675]
I have built the master branch in MSVC. In release mode, after loading a game an access violation keeps popping up, but I can uncheck "Break when this exception type is thrown". However in debug mode the exception still pops up and the checkbox has no effect, and even pressing continue just causes the same exception to reappear, unlike in release mode when a different one comes up every time. The exception comes from this function:
```
namespace Dynarmic::IR {

class LocationDescriptor {
...
    bool operator==(const LocationDescriptor& o) const {
        return value == o.Value();
    }
```
Is there a way to bypass this exception in debug mode?

**Comment by german77** [comment]
"turn off the SIGSEGV breaks" this started happening since fastmem was introduced

**Comment by gyorokpeter** [comment]
Is it like this?
1. Options -> General -> Debug -> Enable CPU Debugging
2. Options -> General -> Debug ->CPU ->Enable Host MMU Emulation
This seems to work but it's not very intuitive.

**Comment by v1993** [comment]
Can this be closed? This is expected to happen due to how fastmem works.
