### ISSUE TITLE
Slow fps in TLoZ SSHD

### ISSUE THREAD

**Issue by stumts** [yuzu-emu/yuzu#6676]
Specs:

SO: Ubuntu 20.04
Graphics: AMD Radeon RX 580 + mesa3d-7492513
CPU: i9-9900KF
Yuzu EA 1887

Hi guys. I've realized poor performance in The Legend of Zelda Skyward Sword HD with OpenGL in Yuzu EA 1887 with Mesa3d-7492513. I didn'd test other yuzu versions and it didn't happen on windows, only on Linux.

I noticed this also happen with Ryujinx after PR ca5ac37 and they fix it with PR 10e17ab.

I don't know if the problem is the same on both emulators.

https://github.com/Ryujinx/Ryujinx/issues/2486
https://github.com/Ryujinx/Ryujinx/pull/2489

Some pictures below:
On Linux:
![Captura de tela de 2021-07-17 18-26-31](https://user-images.githubusercontent.com/30453661/126079757-e4e8f211-8829-4ed5-b9a2-6469e8423e87.png)

On Windows:
![Captura3r](https://user-images.githubusercontent.com/30453661/126079771-809a6b75-3a37-450a-9cdd-34670407da3a.PNG)

**Comment by lat9nq** [comment]
Try disabling asynchronous GPU Emulation (Emulation -> Configure... -> Graphics -> Disabled Use asynchronous GPU Emulation)

**Comment by stumts** [comment]
Problem solved.

**Comment by lat9nq** [comment]
In the future, please make use of our support forums, like the [Discord server](https://discord.gg/u77vRWY) or the [Citra Community Forums](https://community.citra-emu.org/), before making an Issue on GitHub.

**Comment by stumts** [comment]
Thanks for your help. No problem, next time I'll ask for support in the correct place.
