### ISSUE TITLE
Pokemon Sword - Game with sharp edges/artifacts

### ISSUE THREAD

**Issue by hemfreitas11** [yuzu-emu/yuzu#6680]
When models are very close, you can see some dark artifacts around the edges: (Click the images to be able to see it better)
![image](https://user-images.githubusercontent.com/67705052/126099335-d3b31461-2c2b-483f-a07e-44037b8431ca.png)

![image](https://user-images.githubusercontent.com/67705052/126099391-555538f3-a842-4981-a3c7-59cc988f7af3.png)

The edges of models look too sharp, as if it is running in a very low resolution:
![image](https://user-images.githubusercontent.com/67705052/126099266-eafbab6b-7475-4c9e-9000-7e1f79298ccc.png)
Here is a comparison image: (got it from [here](https://github.com/yuzu-emu/yuzu/issues/6636#issuecomment-879406324))
![](https://user-images.githubusercontent.com/866831/125525560-c5a599f3-5898-415c-b6c0-32bd0049600d.jpg)

I have an i3-9100F, RX 570 4GB and 8GB of ram. My monitor's resolution is 1280x1024 (5:4), but the game is running in 16:9

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6837775/yuzu_log.txt)

**Comment by german77** [comment]
Enable docked mode.

**Comment by hemfreitas11** [comment]
> Enable docked mode.

Wow, i'm an idiot
