### ISSUE TITLE
Yuzu is somewhat stuck since version 695

### ISSUE THREAD

**Issue by ChrisM20** [yuzu-emu/yuzu#6701]
Hello, I have noticed that the emulator is somewhat stuck since version 695 when playing in pokemon sword, it is very noticeable when playing in pokemon Camp it is no longer fluid as before.

**Comment by german77** [comment]
695 was two days ago. Run the maintenance tool or delete the yuzu folder in %localappdata% and run the installer again. Are you using the keyboard or a controller?

**Comment by ChrisM20** [comment]
Keyboard
