### ISSUE TITLE
Yuzu crash on Configure

### ISSUE THREAD

**Issue by ripps818** [yuzu-emu/yuzu#6703]
Fresh install of Yuzu (renamed old yuzu folder in appdata/roaming so a fresh config will be generated), and the Yuzu won't let me open the Configure option from menu, and just crashes. Here's the log:

```
[   0.506392] Input <Info> input_common\gcadapter\gc_adapter.cpp:Adapter:21: GC Adapter Initialization started
[   0.755649] Input <Info> input_common\udp\client.cpp:Client:164: Udp Initialization started
[   0.755686] Input <Info> input_common\udp\client.cpp:StartCommunication:309: Starting communication with UDP input server on 127.0.0.1:26760
[   0.779741] Frontend <Info> yuzu\main.cpp:GMainWindow:246: yuzu Version: yuzu 697
[   0.779754] Frontend <Info> yuzu\main.cpp:GMainWindow:261: Host CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz | AVX2 | FMA
[   0.779780] Frontend <Info> yuzu\main.cpp:GMainWindow:263: Host OS: Windows 10 (10.0)
[   0.779793] Frontend <Info> yuzu\main.cpp:GMainWindow:265: Host RAM: 31.92 GB
[   0.779794] Frontend <Info> yuzu\main.cpp:GMainWindow:267: Host Swap: 42.00 GB
[  12.800351] Common.Filesystem <Error> common\fs\file.cpp:Open:262: Failed to open the file at path=C:\Users\ripps\AppData\Roaming\yuzu\nand\system/save/8000000000000010/su/avators\profiles.dat, ec_message=no such file or directory
```

It seems to be unable to open a profiles.dat in a folder that was never created, and then gives up. If there's additional steps to setup or configuration needed, it isn't communicated in any meaningful way.

**Comment by german77** [comment]
Do you have a recording program installed. Like OBS?

**Comment by OZtistic** [comment]
What is the game, firstly?
The error log suggests it is trying to read from an account

**Comment by ripps818** [comment]
@german77 I have streamlabs obs installed, but it was not running at the time.
@OZtistic I haven't added any games yet, this is literally first start.

**Comment by OZtistic** [comment]
does a 2KB file now exist at that location? - If so, that is just a Filesystem logging that file file doesn't exist
Seems strange that you aren't the first person to report not being about to open 'Configure' today though
Bear with my while I get some confirmation

**Comment by german77** [comment]
The file error is quite common on the first try since the file din't exist to begin with and have to be created. OBS is know to cause the config button to crash when installed. Using the latest version of normal OBS usually fixes this issue. Try uninstalling OBS then checking if yuzu is working properly. After that install OBS again

**Comment by ripps818** [comment]
@OZtistic Nope. In fact, there appears to be no nand/system/save folder. The nand directory only contains Contents with empty placehld and registered.

**Comment by OZtistic** [comment]
Okay, while I await a response from someone that will know, could you try uninstalling SLOBS and try it, as German77 suggested?
StreamLabs OBS is a finicky beast as it is. Normal OBS studio is much better to use (I have "normal" OBS installed and don't get this issue, ever)
The blame may rest with SLOBS and the weird things it does

**Comment by ripps818** [comment]
I uninstalled both OBS and SLOBS, tried to goto Configure from Yuzu. Same error:
`[  17.061056] Common.Filesystem <Error> common\fs\file.cpp:Open:262: Failed to open the file at path=C:\Users\ripps\AppData\Roaming\yuzu\nand\system/save/8000000000000010/su/avators\profiles.dat, ec_message=no such file or directory`
I have no idea how a program that isn't even running do something like this, I'd love to hear how that could happen.

**Comment by OZtistic** [comment]
Same. I just know that SLOBS in particular can cause this issue. Normal OBS shouldn't have this issue. I don't know what the particular error associated with OBS is, only that I don't experience it with legit OBS (whether it's running or not)
I will update further when I have confirmation of why this seems to be bugging out on new users

**Comment by german77** [comment]
Consider asking for help on yuzu discord. We can give better support there.

**Comment by ripps818** [comment]
As a sanity check, I restored the nand folder from an older backup from a year ago. It still crashes when I select Configure, but the log file is completely empty, as in 0kb. I don't even know where to look, since the log isn't even giving errors.

**Comment by german77** [comment]
Yuzu doesn't crash anymore when opening the config. Please reopen if it still happens
