### ISSUE TITLE
Texture processing abnormal after starting a new game in DQ3 

### ISSUE THREAD

**Issue by vonchenplus** [yuzu-emu/yuzu#6707]
Hello Guys,

Recently, I’m trying to solve the problem that displays incorrect graphics at the beginning of DQ3.

Abnormal:
![image](https://user-images.githubusercontent.com/3349963/126891372-c403926e-94db-44d6-b385-cc9d92147824.png)

Normal:
![image](https://user-images.githubusercontent.com/3349963/126891351-55a99142-b190-4798-bdea-589eb673edfe.png)

After my debugging, I finally found that there was a problem with the background texture, Under normal circumstances this texture should look like this:
![image](https://user-images.githubusercontent.com/3349963/126891476-85cdb167-aff3-4fd2-aff9-ea6c83864d24.png)

But the result given by yuzu is like this:
![image](https://user-images.githubusercontent.com/3349963/126891492-0d7e6e17-48c9-4a2a-983a-a7a332d61d4a.png)

We can find that there is a piece in the middle that should be transparent, but the data actually obtained is not transparent.

I debugged the code that handles the texture, but in the end I didn’t find the cause of the problem. Can anyone provide me with a little help? Thanks!

**Comment by FernandoS27** [comment]
Come by Discord and contact me. I'll help you out: Blinkhawk#2544. Today I'm a bit busy with personal matters but I can always answer any questions.

**Comment by vonchenplus** [comment]
OK, thanks.
