### ISSUE TITLE
Integer Overflow Exception thrown at NativeClock contructor when calling GetFixedPoint64Factor

### ISSUE THREAD

**Issue by Kappie37** [yuzu-emu/yuzu#6708]
Also occurs on clean setup (fresh install)
![image](https://user-images.githubusercontent.com/44774200/126905780-1332f691-16ca-4552-a332-97588aa5e810.png)
![image](https://user-images.githubusercontent.com/44774200/126905799-a2eec51c-538f-4e32-bdc6-f5834e99b87e.png)
CPU: i7-4790k, GPU: 780ti, RAM: 16GB

**Comment by FernandoS27** [comment]
Could you get me the numerator and divisor in hexadecimal if possible ?

add `#pragma optimize("", off)` at the start of that file and then run it until it crashes. Then on debug view, look for the Locals.

Thank you very much.

**Comment by Kappie37** [comment]
Thank you for replying.
![image](https://user-images.githubusercontent.com/44774200/126910271-9ee94e2a-7861-4442-b1ca-d12c914fc14c.png)
So, numerator: 0x000000003B9ACA00 and divisor: 0x000000002fa7f7b3

**Comment by Kappie37** [comment]
@FernandoS27 Is this what you needed?

**Comment by Kappie37** [comment]
@lioncash Do you know who to assign for this issue and what labels to apply? thanks

**Comment by FernandoS27** [comment]
@Kappie37 was this ever soleved?

**Comment by Kappie37** [comment]
@FernandoS27 I am able to use Yuzu again, but not because this was solved I think. I can't remember what I did, it just worked out of nowhere after a couple of months again. A lot of reinstalling of windows and yuzu haha.

I would leave this issue open because someone mentioned that there should be a check for CPUs with 'high/irregular' (can't remember what was said) and should be an easy fix.
