### ISSUE TITLE
Few unpolished things from Project Hades

### ISSUE THREAD

**Issue by v1993** [yuzu-emu/yuzu#6710]
Opening an issue since Hades PR was merged. Those were reviews/comments there.

1. "General -> Debug -> General" tab is squeezed with addition of all new stuff (gtk2 theme):
![Screenshot_20210710_180257](https://user-images.githubusercontent.com/16255906/125167468-6713b700-e1a9-11eb-955f-1446b483c065.png)
Probably move graphics options into a separate tab? Oddly, Debugging section ("General -> Debug -> General -> Debugging" is a weird one) is not squeezed in the same manner for whatever reason.
2. https://github.com/yuzu-emu/yuzu/blob/7e272d3cd81656b65b21f5a569fc9a2d76cac758/src/shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp#L108-L109
Comment is clearly copied from previous function and needs an update.
3. https://github.com/yuzu-emu/yuzu/blob/7e272d3cd81656b65b21f5a569fc9a2d76cac758/src/shader_recompiler/frontend/ir/opcodes.inc#L5
Second `arg4` is most surely intended to be an `arg5`.

**Comment by FernandoS27** [comment]
oh thankfully this r just typos. Nothing serious.

**Comment by v1993** [comment]
Yeah (with exception of squeezed GUI?), that's why those are "unpolished" rather than "unfinished" or "broken" or "regressed".
