### ISSUE TITLE
Strange chinese error when entering name in famicom detective club

### ISSUE THREAD

**Issue by soredake** [yuzu-emu/yuzu#6712]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6876887/yuzu_log.txt)

![изображение](https://user-images.githubusercontent.com/5204968/126911258-c3866703-053a-49c9-a259-2ed92f32e796.png)

**Comment by Morph1984** [comment]
Could you re-upload the log? It does not contain the entries that show the software keyboard is being invoked

**Comment by sbruder** [comment]
I’m having the same problem. Also, once the error message appears, yuzu is unresponsive and I can’t gracefully quit it any more (only `kill -9` can close it).

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6874510/yuzu_log.txt)

**Comment by soredake** [comment]
> 
> 
> Could you re-upload the log? It does not contain the entries that show the software keyboard is being invoked

Log updated.
