### ISSUE TITLE
Molten VK is really awesome

### ISSUE THREAD

**Issue by ebellumat** [yuzu-emu/yuzu#6716]
What we need to port YUZU to Mac OS? Migrate from GCC to LLVM? What more? 

![image](https://user-images.githubusercontent.com/26942680/126926686-58896092-756c-4400-9abe-bc876dc42dd1.png)

**Comment by german77** [comment]
A dev that is familiar with Mac OS and willing to port yuzu to Molten VK. Although this API is missing some features that are used by yuzu. Duplicate of #6527 please read comments of this issue.
