### ISSUE TITLE
Windbound: Texture corruption

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#6719]
Some textures are corrupt, particularly the ground textures of many islands.  This is apparent in the following screenshot, which shows texture garbage instead of grass:

![pic](https://user-images.githubusercontent.com/12475371/154776017-05a68431-d68f-4400-991e-f6ed97456cb1.png)

Information:
* OS: Linux Mint 20.3 / kernel 5.13
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070 / driver 510.47 (also tested on 410.57)
* Compiler: gcc-11.1.0
* Commit: 83a84f1c2dce5a9f90404f2486da569e236f96fa
* Settings: Default, tested with OpenGL and Vulkan

**Comment by Shoegzer** [comment]
Update: Upon testing against commit 7f0d0dd17773f1f6c865907bc6c95e0630e3b886, unfortunately this title has regressed even further recently (possibly after the Y.F.C. merge).  Islands now don't render properly at all, appearing as a series of vertical columns:

![pic](https://user-images.githubusercontent.com/12475371/199096687-1967abad-cdaa-4bc8-8283-376c3a89e8ab.png)

**Comment by Shoegzer** [comment]
Update: tested against #9194 but with no discernable difference unfortunately.

**Comment by Shoegzer** [comment]
Update: The issues raised above have been resolved from some commit between my last post and now.  Grass textures sometimes flicker though, so I'm willing to keep this open since the game isn't perfectly rendered unless there are objections.

**Comment by benderscruffy** [comment]
is this still an issue ???

**Comment by Shoegzer** [comment]
Thanks for the reminder - I haven't tested this title in a while.  It seems fine now, not even the grass is flickering, at least as far as I can tell.  I'm closing this one.
