### ISSUE TITLE
Big meshes when using Vulkan in EA and Mainline Yuzu with Crash Team Racing. 

### ISSUE THREAD

**Issue by wesmoen** [yuzu-emu/yuzu#6731]
The game worked normally before, even for a while when Project Hades got into EA. Since a certain EA version, Meshes of some models will be huge. This issue also came into Yuzu 700, versions prior to 700 don't have this issue.  

I already tried:
- renewing my cache
- Switching to OpenGL (Works as intended)
- Disabling mods
- GPU Accuracy to normal
- Updating GPU drivers. 

Running the game on a i7-2600k, 8GB DDR3-1333, GTX 970.

Can't really wrap my head around it. Thanks and keep up the good work!

![CrashbigobjectRacing](https://user-images.githubusercontent.com/20476068/126966280-0595767d-479f-43b9-8032-a8a323c4cab4.png)
![crashbigracing](https://user-images.githubusercontent.com/20476068/126966281-0a3a0fd3-d9f6-4952-8cae-bad59bd5f311.png)
![crashcurseracing](https://user-images.githubusercontent.com/20476068/126966286-daa9b197-9760-4bb7-bf58-9c7090f1c18a.png)
![CrashLizRacing](https://user-images.githubusercontent.com/20476068/126966289-c793c05b-bbd6-4062-819d-438f290dcbca.png)
![CrashOxideRacing](https://user-images.githubusercontent.com/20476068/126966292-b8951c95-649d-4c67-89bb-60d97167a1b2.png)
![crashtinyracing](https://user-images.githubusercontent.com/20476068/126966295-f1db0a0c-bf78-4702-936f-4c99bbafe517.png)

Log file:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6877221/yuzu_log.txt)

**Comment by JustBuddy** [comment]
+1, having the same issues as OP since the HADES Vulkan update on 700 and 701.
Specs:
i5 10400
GTX 1060 6GB
16GB RAM

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6883377/yuzu_log.txt)

**Comment by MauMauMlK** [comment]
I have the same problem :(

i5-7400
8GB RAM
GTX 160 6GB

OpenGL works fine, only on vulkan

**Comment by nyxover** [comment]
![image](https://user-images.githubusercontent.com/22452629/128747556-18f86bde-016e-4c05-97c5-8c46d53ad97c.png)
SAME vulkan  👎 Work on OpenGL
i7 1080
32GB Ram

**Comment by bowlofspiders** [comment]
Happens here on 1080ti (Vulkan only) with Nvidia 471.96
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7119561/yuzu_log.txt)

![unknown](https://user-images.githubusercontent.com/53333627/132298232-e5663b6c-ea12-471e-9cad-c124909df1bd.png)

**Comment by KiNGKiMO** [comment]
It's a bug with older NVIDA GPUS, happens with me 1080Ti

It first started at yuzu build 700 exactly, so latest working version is build 699, also ea1884 is the latest ea build that works fine.

Hope devs with older Nvidia cards can check this.

Thank you.

**Comment by MauMauMlK** [comment]
> It's a bug with older NVIDIA GPUS, happens with me 1080Ti
> 
> It first started at yuzu build 700 exactly, so latest working version is build 699, also ea1884 is the latest ea build that works fine.
> 
> Hope devs with older Nvidia cards can check this.
> 
> Thank you.

The way is to wait for the correction.
I hope they see this topic.

Thank you friend

**Comment by wesmoen** [comment]
> It first started at yuzu build 700 exactly, so latest working version is build 699, also ea1884 is the latest ea build that works fine.

That's dedication! kudos to that!

**Comment by v1993** [comment]
Build 700 is Project Hades, that's one of first points to check when bisecting graphical issue.

**Comment by arcanechocolate** [comment]
I subscribe to this issue. Still happening on EA 2171.
I also own a pascal card (1080ti).

Would be lovely to know if it happens on AMD cards and Turing cards (since we know at least that it doesn't happen on Ampere).

**Comment by DonelBueno** [comment]
It's also happening on my end, GTX 1070 user here.

Hope it gets fixed, because Vulkan is much better than OpenGL when running at 2-3x resolution scaling.

**Comment by SirRFI** [comment]
EA 1884 is the last build that doesn't have this issue for me - 1885 is already affected. Hopefully this will help narrow the issue down.

**Comment by MauMauMlK** [comment]
> EA 1884 is the last build that doesn't have this issue for me - 1885 is already affected. Hopefully this will help narrow the issue down.

From 1885 to now many versions have passed, I believe developers are not looking at this problem :(

**Comment by KiNGKiMO** [comment]
> > EA 1884 is the last build that doesn't have this issue for me - 1885 is already affected. Hopefully this will help narrow the issue down.
> 
> From 1885 to now many versions have passed, I believe developers are not looking at this problem :(

Unfortunately yes.

**Comment by SirRFI** [comment]
The bug is still present as of build 2488. That's over 500 builds later. Affects Vulkan only, it's fine on OpenGL. GTX 1080Ti

**Comment by Gonckzilla** [comment]
GTX 1050 (mobile) here, following the trend. Updating to say that it's still present on latest build March 14th. Only on Vulkan as well, clearly specific to GTX 10-series (and older?) GPUs.

**Comment by bowlofspiders** [comment]
Still occurs on Nvidia 512.15 drivers with my 1080 Ti while using Vulkan.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8343418/yuzu_log.txt)

![picture](https://user-images.githubusercontent.com/53333627/159961722-4c8cd7e4-6c7c-4d3e-871a-7e1808436aec.png)

**Comment by arcanechocolate** [comment]
I have faith that they'll look into it sooner or later.

**Comment by KiNGKiMO** [comment]
> I have faith that they'll look into it sooner or later.

Really hope so, since Vulkan is supposed to be yuzu's default as stated.

**Comment by G-Spawn** [comment]
This issue is oddly specific to 1k series nvidia gpu users. They are looking into it but it is not active priority atm (apologies)

**Comment by EslamHULK** [comment]
1/8/2023
![Untitled](https://github.com/yuzu-emu/yuzu/assets/35035933/f76c89d0-799d-4e29-a6ea-f453622abb84)

**Comment by EslamHULK** [comment]
YUZU Early Access 1880 < Vulkan is work good and sound work good . but in other versions right now not work good in sound and graphic

**Comment by EslamHULK** [comment]
![Untitled](https://github.com/yuzu-emu/yuzu/assets/35035933/83a0a543-572a-450e-9cbb-5a9a904aada8)

this is last version YUZU 1513 , Vulkan not work like old version YUZU 699

**Comment by EslamHULK** [comment]
![Untitled](https://github.com/yuzu-emu/yuzu/assets/35035933/bc3b93ac-12c0-4ca1-927e-8a0a06adbe34)
 
this old version YUZU 699 Vulkan work good and sound good , need this work in new versions right not to play it in 4K Vulkan

**Comment by EslamHULK** [comment]
![Screenshot 2023-08-01 185837](https://github.com/yuzu-emu/yuzu/assets/35035933/0493a955-eada-4a31-8baa-d8eab86fbc7b)
YUZU 1514 Vulkan not work
![Screenshot 2023-08-01 185701](https://github.com/yuzu-emu/yuzu/assets/35035933/10f188fe-cf40-4232-8344-b566591b4e22)
YUZU Early 3787 Vulkan not work

**Comment by EslamHULK** [comment]
![Screenshot 2023-08-01 185701](https://github.com/yuzu-emu/yuzu/assets/35035933/60a1cb9a-11b6-426a-8f39-7153b1de0dbe)
latest version of YUZU  Vulkan not working in crash team racing
![Screenshot 2023-08-01 185837](https://github.com/yuzu-emu/yuzu/assets/35035933/edf17767-0a1c-4be0-9e08-97de6f1f99a0)
latest version of YUZU  Vulkan not working in crash team racing
   
but in old version look it work
![Screenshot 2023-08-01 010004](https://github.com/yuzu-emu/yuzu/assets/35035933/4107d8d1-d7bc-48b9-8a31-bb4bb01f54af)
![Screenshot 2023-08-01 011442](https://github.com/yuzu-emu/yuzu/assets/35035933/f6e7defd-a419-4b10-a63b-ad07510a6127)

 can fix it soon , and thank u

**Comment by bowlofspiders** [comment]
This is not fixed. Using the latest mainline build which includes #11789 
![image](https://github.com/yuzu-emu/yuzu/assets/53333627/9d185edb-386c-46b6-ac30-c92d10b9be60)

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13064051/yuzu_log.txt)

**Comment by MauMauMlK** [comment]
Problem solved on last version :)
