### ISSUE TITLE
Quest of Dungeons Black Screen on OpenGL

### ISSUE THREAD

**Issue by Emalix** [yuzu-emu/yuzu#6734]
Game produces black screen when using OpenGL, audio can still be heard.

CPU: i7 4770
GPU: Nvidia Geforce GTX 780
Yuzu: Mainline v700

[yuzu_log_QuestOfDungeons_GLSL.txt](https://github.com/yuzu-emu/yuzu/files/6877215/yuzu_log_QuestOfDungeons_GLSL.txt)
[yuzu_log_QuestOfDungeons_GLASM.txt](https://github.com/yuzu-emu/yuzu/files/6877216/yuzu_log_QuestOfDungeons_GLASM.txt)

**Comment by benderscruffy** [comment]
using mainline v703
graphics are ok
Raedon RX 580 card
![Screenshot 2021-07-30 173458](https://user-images.githubusercontent.com/2696404/127635034-b2f3e5b3-c9c5-49b6-9fbc-3e9e8bc4158e.png)

**Comment by benderscruffy** [comment]
can be closed
this is fixed
