### ISSUE TITLE
[flatpak] yuzu doesn't show compatibility of games in flatpak version

### ISSUE THREAD

**Issue by TobiPeterG** [yuzu-emu/yuzu#6746]
I'm using latest version of yuzu (mainline-0-701) and every game is stated as "not tested", but the snap and appimage versions show the compatibility.
I'm using Ubuntu 21.04

Can this issue be confirmed?

**Comment by G-Spawn** [comment]
I don't know if they are the one's maintaining the flatpak version. Perhaps that is a part to play?

**Comment by TobiPeterG** [comment]
> Edit: They do maintain it. They'll look into the issue thank you for reporting.

Ah, thank you very much!

**Comment by liushuyu** [comment]
Hi, I am the current maintainer of the Flatpak. We will address this issue in the near future.

**Comment by TobiPeterG** [comment]
> Hi, I am the current maintainer of the Flatpak. We will address this issue in the near future.

Hey there, thank you very much!
I don't want to create a new issue, so I'll just tell you here, I also noticed that the "Open yuzu folder" doesn't work, which is just minor though.

**Comment by liushuyu** [comment]
> > Hi, I am the current maintainer of the Flatpak. We will address this issue in the near future.
> 
> Hey there, thank you very much!
> I don't want to create a new issue, so I'll just tell you here, I also noticed that the "Open yuzu folder" doesn't work, which is just minor though.

This is confirmed to be a Flatpak bug and it's tracked here: https://github.com/flatpak/xdg-desktop-portal/issues/594. There's no workaround or even hack available since it's the only way to notify the host OS to open the folder.

**Comment by liamwhite** [comment]
This seems to be working as of flatpak 1322.
