### ISSUE TITLE
[FEATURE REQUEST] Display Button Name In Controls Configuration

### ISSUE THREAD

**Issue by CassiusOtho** [yuzu-emu/yuzu#6750]
In the controls configuration it would be great if mapped buttons would show the button name instead of "Input X". For example, instead of “Button 1", yuzu would display “Button A” (or “Button X” for Play Station users). This would make it easier for us to check for any erroneous mappings. This would be a great feature to have for all buttons, triggers, Dpad, ,etc. To provide a little sample of how that would look, I have attached an image below for just the “ABXY” buttons. 
![Display Button Name](https://user-images.githubusercontent.com/63135347/130438806-641c3123-83f8-45fa-b855-75e17d703b12.jpg)

**Comment by v1993** [comment]
This should be doable at least for some controllers (namely, those with `SDL_GameController` interface), but can be tricky.
