### ISSUE TITLE
Black edges reduce graphic quality in Pokémon Sword

### ISSUE THREAD

**Issue by ChrisM20** [yuzu-emu/yuzu#6755]
This started in version 700-701

Hello, I have noticed that some black edges have appeared when playing in Pokemon Camp, below I leave a comparison, as it seems to me that it looks lower quality in graphics, I do not know if it is because some parts are darker, as well to report a future addition in the properties of the games, for example the modification of the RTC since I see that time does not count when leaving the game idle and it bothers because some things cannot be refreshed, if someone could help me in this apart from time I would appreciate it. 

My specs:
Intel i5 2450m and nvidia gt540m 1gb, only in opengl 
New update
![0100abf008968000_2021-07-27_12-11-24-456](https://user-images.githubusercontent.com/60308449/127200372-4798d7bb-836a-4c43-b965-38e2707ff376.png)
Old Update
![105661566-54bfee00-5e93-11eb-8ad8-b67dd160e011](https://user-images.githubusercontent.com/60308449/127200447-591a87d3-d79d-42ae-b825-adb6d8071130.png)

I don't know if it's any configuration or if it's a shader, but I think it looks much better in graphics compared to the new update.

I would appreciate if you can fix it.

**Comment by BSoDGamingYT** [comment]
This is just how the game looks

**Comment by BSoDGamingYT** [comment]
Dude...this is how the game looks.
