### ISSUE TITLE
Scarescraper doesn't work on Luigi's Mansion 3

### ISSUE THREAD

**Issue by Darckray5** [yuzu-emu/yuzu#6756]
The Scarescraper mode can't be played on the emulator in any of the builds. I understand that this is an online mode but it also gives you the option to play offline, in solo and co-op mode. Both of these options give an error when selected, preventing the game to be fully completed taking into account that certain ghosts can only be found in the Scarescraper, among other things.

I'd really like to be able to play this because it's what i liked most about the previous game, i'd be really grateful if you could tell me what your stance on this problem is at this time. Thank you!!

**Comment by OZtistic** [comment]
The error you are receiving **2203-0022/0x2ccb** is LDN services not initializing - LDN handles all local network communication

You will not be able to play this mode until LDN is implemented

**Comment by Darckray5** [comment]
Are there any plans for this to happen? I just looked up LDN and it seems ryujinx already has this available, i don't know if this is still the case but it would be cool to know if yuzu will be getting this feature too in the near future.

**Comment by OZtistic** [comment]
Planned. Although, as with any feature - no ETA
Rest assured - It will happen :)

**Comment by gidoly** [comment]
this should be now fuctional with ldn implemented
