### ISSUE TITLE
Any fix for Yo-kai Watch 4 Graphical glitches?

### ISSUE THREAD

**Issue by Fuzzy64** [yuzu-emu/yuzu#6757]
I tried OpenGL and Vulkan but it remains the same thing, the game runs 20-30fps and is playable, but this graphic bug annoys me and i can't play the game with that.
![Screenshot_2](https://user-images.githubusercontent.com/88057380/127217557-4699493b-93bf-48d4-9830-f6ddd566b1ce.png)
![Screenshot_3](https://user-images.githubusercontent.com/88057380/127217572-b0c84f55-8107-4687-a07e-4a08e942f956.png)
![Screenshot_1](https://user-images.githubusercontent.com/88057380/127217582-c932dd79-d0e8-4826-8d2d-32b0b7f98fe0.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6909696/yuzu_log.txt)

**Comment by Fuzzy64** [comment]
😢

**Comment by gidoly** [comment]
fixed yfc 1
