### ISSUE TITLE
Super Mario Odyssey - Vertex explosion after breaking "cube"

### ISSUE THREAD

**Issue by K0bin** [yuzu-emu/yuzu#6764]
After breaking a [moon rock](https://www.mariowiki.com/Moon_Rock#/media/File:Mysterious_Cube_SMO.jpg) on desert kingdom, I'm seeing exploding vertices. I can provide a save if you want. The issue isn't 100% reliably reproducible but I did manage to reproduce it a second time with that save without too many attempts.
[Once I also ended up with some minor flickering instead.](https://drive.google.com/file/d/1J4KUHJIKEXMwZjwAowvFa_bHFXO0ACEn/view?usp=sharing)

![yuzu bug](https://user-images.githubusercontent.com/1131720/127402095-c303f855-954f-46bb-9865-ba79490a649d.png)

Super Mario Odyssey 1.3
Nvidia GTX 1070, driver: 470.57.02
Yuzu commit b2b3fcdccda8399735a0307114a0ad5c2f118421, Linux build
It does not seem to happen with the OpenGL renderer.

I took a look at it in Renderdoc and it seems like the Index buffer is messed up, causing out of bounds reads.
![image](https://user-images.githubusercontent.com/1131720/127402203-ebab9e87-1e32-4b60-97e7-54ad2e299966.png)

On the other hand, the mesh looks fine (I think) in the VS In tab of the mesh viewer and the issue only shows up after the vertex shader.

![image](https://user-images.githubusercontent.com/1131720/127402300-c135e0e3-c93e-4474-9fee-c86b4d53dc7e.png)
![image](https://user-images.githubusercontent.com/1131720/127402313-c083b107-8cbb-433b-9016-db75b11d5092.png)

![image](https://user-images.githubusercontent.com/1131720/127404187-cb5e6a6c-246f-42bc-9203-67b13b87c447.png)
The data in the index buffer only seems sensible starting with index 128,.

I compared the same draw call in another capture where I didn't run into the bug and the first 128 indices are correct. So it's either not copying the first 256 bytes (16bit int indices) or it's copying garbage into it.

I already talked to Rodrigo on Discord, and sent him both the Renderdoc capture and the save, I'm opening this regardless to keep track of the bug.

The moon rock is located here:
![image](https://user-images.githubusercontent.com/1131720/128072017-fe5fb1a7-8f75-40dc-bc1b-69918702fee0.png)
but you should be able to see it from the spawn location.

**Comment by G-Spawn** [comment]
For good measure would you mind providing a log as well when possible? :P

**Comment by K0bin** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6910930/yuzu_log.txt)

**Comment by K0bin** [comment]
I made a gfxreconstruct capture of it and replaying it with the `rebind` memory mode fixes the issue. So this might be a bug in the Vulkan memory allocator.

**Comment by K0bin** [comment]
I'm pretty convinced this is a driver bug.

I managed to get a Renderdoc capture of the exact frame that corrupts the index buffer data. It's a `vkCmdCopyBufferToImag`call and the destination image is a 64x8x1 3D image. According to the Vulkan memory requirements, it needs 512 bytes and Yuzu manages to squeeze that in exactly before the index buffer. That copy call happens to write past those 512 bytes though.
