### ISSUE TITLE
[BUG REPORT] Luigi's Mansion 3 - 12F Black Screen after visiting the Doc

### ISSUE THREAD

**Issue by OZtistic** [yuzu-emu/yuzu#6766]
_Background Info:_
Luigi's Mansion 3 on 12F you are asked to come back to the lab by the Doc in order for him to speak to you about something important - Upon doing this, a small cut-scene plays. After the video, all rendering ceases to function except the top 2D layers for UI etc. 
Asking in the Discord, It was explained to me that this has been an issue even before Project hades was released. I have not seen an Issue raised for this, so here it is for visibility
I have a sneaky suspicion that the video is somehow breaking the rendering, as even the video itself is quite corrupted 
(possible NVDEC issue?)
This issue affects mainline and EA

I have tried visiting the Doc using the Lab teleport and visiting him on foot just testing, and it's always the conclusion of the cut-scene that kills any 3D rendering

_Method to reproduce:_
Nothing special at all, just use the provided save
This affects Vulkan and OpenGL
Interestingly during my testing, trying to go back saves - I was met with 
*``Core.ARM** <Error> core\arm\dynarmic\arm_dynarmic_64.cpp:InterpreterFallback:87: Unimplemented instruction @ 0x8B0F550 for 1 instructions (instr = E7FFDEFE)``* error whilst trying to backload myself to my oldest save to the Boat section - Upon doing this (on OpenGL) Luigi broke his legs and the game softlocked continually spitting the above error, even after the title and yuzu was closed

_Files and Screenshots:_
![image-1](https://user-images.githubusercontent.com/71381851/127452605-af16b388-289b-4bc8-bef2-05496626abbb.png)
![image-2](https://user-images.githubusercontent.com/71381851/127452614-cc5a27f7-97e1-45b1-aa19-bb74729df785.png)
![image-3](https://user-images.githubusercontent.com/71381851/127452625-5761a7c7-152f-4246-88d1-0da877ed5e01.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6898807/yuzu_log.txt)
[yuzu_log_LM3.txt](https://github.com/yuzu-emu/yuzu/files/6898808/yuzu_log_LM3.txt)
[yuzu_log-[interpreter-fallback-error].zip](https://github.com/yuzu-emu/yuzu/files/6898840/yuzu_log-.interpreter-fallback-error.zip)

_Save file at location to reproduce:_
Just walk inside the Lab and speak to the Doc
[LM3-save-point-Vulkan-Issue.zip](https://github.com/yuzu-emu/yuzu/files/6898846/LM3-save-point-Vulkan-Issue.zip)

_Specs:_
i5-7400
16gig RAM
1060 6gig

Notes:
Will build latest Mainline and EA and provide stack traces for both asap

_Updates:_
Cannot seem to reproduce "broken-legs" in limited testing. Will keep trying as time permits
Original issue in ticket still stands

**Comment by benderscruffy** [comment]
using your saving i talk to the doc watch the movie and went out the door
no problem for me
i am using an AMD RX580 graphics card
![Screenshot 2021-07-30 145406](https://user-images.githubusercontent.com/2696404/127613365-c819aeba-c352-4706-896c-2ab9c10b641f.png)

**Comment by OZtistic** [comment]
And you didn't get any back screen, like my pics?
neither OpenGL or Vulkan function correctly on Nvidia then, if so
Whether this is a Pascal issue or not remains to be seen

**Comment by dece870717** [comment]
What does it mean when this happens on a only month's old Nintendo Switch OLED with the actual game bought from Target? 
![received_1301570023711678](https://user-images.githubusercontent.com/112725402/188218424-736968d5-f221-4f5d-b248-8db4b4e447f8.jpeg)
