### ISSUE TITLE
Marvel Ultimate Alliance 3 graphical issues

### ISSUE THREAD

**Issue by FacundoFortes** [yuzu-emu/yuzu#6777]
I have seen videos on Youtube of people playing this game on the latest EA builds and running somehow smoothly and with proper shading. However, when I try that on my pc it would run with the same issues it already had for a while. The common feature for all of those users that I don't have is an Nvidia GPU. Is this still a common issue for AMD users?

My specs:
Ryzen 5 5600X Stock speeds
3200 Mhz CL 16 2X8GB RAM
Asrock RX 570 Stock speeds
Running yuzu games off of NVME ssd

![image](https://user-images.githubusercontent.com/88208461/127704759-e51a3152-3afc-46e0-8171-4bf8e00d86a0.png)

**Comment by FacundoFortes** [comment]
I should add that I'm running this with Vulkan API, asynch shaders on and have already tried turning on and off disk cache

**Comment by Moonlacer** [comment]
Looks like an AMD bug
