### ISSUE TITLE
Arcade Archives crashing out on the menu

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#6781]
using the latest EA
titles such as Track and Field and X Multiply and a couple of other crash out on the menu when you press + or -
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6910835/yuzu_log.txt)
[ 101.736121] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1500: (STUBBED) called, result=0x0000D401
[ 101.736820] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:565: Signalling debugger, PANIC! info1=0x00000010422EFC78, info2=0x0000000000000004
[ 101.736823] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:operator ():546: debug_buffer_err_code=D401
[ 101.736838] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:616: Emulated program broke execution! reason=0x0000000000000000, info1=0x00000010422EFC78, info2=0x0000000000000004
[ 101.736843] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: Backtrace, sp=0000000000000000, pc=0000000009C54F28
[ 101.736847] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:268: Module Name         Address             Original Address    Offset              Symbol
[ 101.736849] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:269: 
[ 101.776052] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 000000710017761C    0000000009A5B61C    000000000017761C    _ZN2nn4diag6detail5AbortEPKNS_6ResultE
[ 101.776059] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 0000007100175EFC    0000000009A59EFC    0000000000175EFC    _ZN2nn4diag6detail10VAbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoES3_St9__va_list
[ 101.776061] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 0000007100175FC0    0000000009A59FC0    0000000000175FC0    _ZN2nn4diag6detail9AbortImplEPKcS3_S3_iPKNS_6ResultES3_z
[ 101.776063] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 0000007100320FF4    0000000009C04FF4    0000000000320FF4    _ZN2nn2os6detail25SharedMemoryImplByHorizon5UnmapEjPvm
[ 101.776064] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 000000710031B81C    0000000009BFF81C    000000000031B81C    _ZN2nn2os19DestroySharedMemoryEPNS0_16SharedMemoryTypeE
[ 101.776066] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 00000071003753D4    0000000009C593D4    00000000003753D4    _ZN2nn4time8FinalizeEv
[ 101.776068] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                000000710000B478    000000000800F478    000000000000B478    
[ 101.776070] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                000000710000B9C0    000000000800F9C0    000000000000B9C0    
[ 101.776071] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                000000710000BD00    000000000800FD00    000000000000BD00    
[ 101.776073] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                00000071000198E8    000000000801D8E8    00000000000198E8    
[ 101.776080] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                0000007100019AD0    000000000801DAD0    0000000000019AD0    
[ 101.776082] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                00000071000CDB60    00000000080D1B60    00000000000CDB60    
[ 101.776084] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                00000071000CE2B8    00000000080D22B8    00000000000CE2B8    
[ 101.776085] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                00000071000CDDD0    00000000080D1DD0    00000000000CDDD0    
[ 101.776087] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 000000710031D3B4    0000000009C013B4    000000000031D3B4    
[ 101.776089] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 0000007100321814    0000000009C05814    0000000000321814    
[ 101.776090] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 00000070F671BFFC    FFFFFFFFFFFFFFFC    FFFFFFFFF671BFFC

**Comment by OZtistic** [comment]
This sounds like a similar issue to 3D All-Stars - emulating inside of emulation - this will take some time, and may never actually come to fruition. There is hope, but emulating inside of emulation is difficult
Maybe when yuzu can boot HOS (Horizon OS in the distant future) it will work
Big N has a habit of using emulation themselves to implement games from older hardware
Despite their hard stance on "emulation" as a whole

**Comment by benderscruffy** [comment]
same issue using the latest EA and mainline
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7740211/yuzu_log.txt)

**Comment by benderscruffy** [comment]
dont crash out anymore
