### ISSUE TITLE
LAYTON’S MYSTERY JOURNEY: Katrielle and the Millionaires’ Conspiracy – Deluxe Edition issue

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#6785]
previous issue was gone but game still not renders if you start new game on both renderer

![yuzu_tYqPKdydDS](https://user-images.githubusercontent.com/66776795/196159528-4ad3f73a-ae80-4b2c-a509-73011c0251d8.png)

log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9799692/yuzu_log.txt)

**Comment by danilaml** [comment]
Looks like the same issue as in https://github.com/yuzu-emu/yuzu/issues/9635
