### ISSUE TITLE
Layton Mystery Journey Strange Viewing Angle 

### ISSUE THREAD

**Issue by Moodie92** [yuzu-emu/yuzu#6798]
while Inializing the game is viewing on side angle and while second luch it freeze YUZU
![0100fb700d224000_2021-08-02_15-56-32-825](https://user-images.githubusercontent.com/40892036/127875131-c0e4bba3-63af-4bb9-8c9d-4c1142a5ad53.png)
![0100fb700d224000_2021-08-02_15-58-46-528](https://user-images.githubusercontent.com/40892036/127875149-143de9c5-598d-44ee-b591-8e88db71be0f.png)

YUZU LOGS :
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6917556/yuzu_log.txt)

API: VULKAN
GPU ACCURACY :HIGH
Mode : DOCKED

**Comment by gidoly** [comment]
this is fixed but has still remain issues i made seperate issue thread for those issues
