### ISSUE TITLE
Yuzu +700:Any solution to these black lines in Pokemon Sword? 

### ISSUE THREAD

**Issue by ChrisM20** [yuzu-emu/yuzu#6804]
Hello, I have seen that since version 700 some black borders appeared that in my opinion make the game look less realistic, I liked it better without those lines and I prefer version 691, here is a comparison of version 706 with version version 691 would be very good if an option were added to remove those edges, I have also seen that this is how the original game looks but without those edges for me the game looks much better.
691:
![comparacion 4](https://user-images.githubusercontent.com/60308449/127925518-b40eaed1-6bcc-4775-ba52-010464ebd4f3.png)
![comparacion](https://user-images.githubusercontent.com/60308449/127925522-b1c752f7-463e-400e-af67-f2b849a92fc9.png)
700:
![Comparacion 3](https://user-images.githubusercontent.com/60308449/127925551-6fb6b875-aa98-44db-aed6-954c5bd907d9.png)
![comparacion 5](https://user-images.githubusercontent.com/60308449/127925607-d4a1e0e0-acd6-4af2-9e37-c8a2f211d694.png)

**Comment by PacoAvelar** [comment]
Can yoy upload a log?
Are you using any mods?
If not, there is a "No outlines" mod on the wiki page

**Comment by BSoDGamingYT** [comment]
This is how the game looks...the black lines are meant to be there.

**Comment by ChrisM20** [comment]
> This is how the game looks...the black lines are meant to be there. Please stop opening issues for this

It is the only way I have to report, it is an opinion, I know it looks like this on the switch but before it looked better to me and it can be a next addition to remove those lines,It was also not necessary to remove my comment, I want to see what other people think

**Comment by ChrisM20** [comment]
> Can yoy upload a log?
> Are you using any mods?
> If not, there is a "No outlines" mod on the wiki page

I have the mod of no outlines but I had it deactivated and even so the lines did not appear so it seemed strange to me that they appeared in version 700, but when I activated it again they disappeared, as I don't know much English I did not know what it was for but I fixed it, it was what I was looking for thanks.
