### ISSUE TITLE
Pokemon sword graphics issues

### ISSUE THREAD

**Issue by ChrisM20** [yuzu-emu/yuzu#6806]
Hello, I have noticed that when shaking the trees the berries fall with a few lines, the closer to the tree the longer they appear, as on one occasion the menu appeared flashing, I have the outlines mod and deactivating they continue to appear, the problem of the The menu only appeared once, here below I leave some screenshots, I don't even know if fighting takes me out of the game and they go about twice.
Nvidia gt540m, only opengl

And the log:
[yuzu_log-1.txt](https://github.com/yuzu-emu/yuzu/files/6926261/yuzu_log-1.txt)
[yuzu_log.txt.old-1.txt](https://github.com/yuzu-emu/yuzu/files/6926262/yuzu_log.txt.old-1.txt)

![Screenshot_20210803_113027_com huawei himovie overseas](https://user-images.githubusercontent.com/60308449/128052325-54321a94-0095-4909-97e0-b7fbe5a3a3eb.jpg)
![Screenshot_20210803_112912_com huawei himovie overseas](https://user-images.githubusercontent.com/60308449/128052329-d54cbde6-529c-4124-87db-d0ee97ba139b.jpg)

**Comment by G-Spawn** [comment]
as the template of the create new issue asks, please provide a log as well.

**Comment by OZtistic** [comment]
A GT 540M is painfully old, even Nvidia don't support anymore

your first log:
_[  22.785259] Frontend <Error> yuzu\configuration\configure_graphics.cpp:RetrieveVulkanDevices:264: Failed to enumerate devices with error: VK_ERROR_INITIALIZATION_FAILED_
Your second log:
_GL_VERSION: 4.6.0 NVIDIA 391.35_
![image](https://user-images.githubusercontent.com/71381851/128637022-efef370a-3bc7-4d24-a604-36b76d2e66c3.png)
Thatd river came out in 2018

Use Linux and Mesa to play it, you will have a much better time all round for gaming
