### ISSUE TITLE
bsd: blocking sockets don't seem to be working correctly

### ISSUE THREAD

**Issue by spholz** [yuzu-emu/yuzu#6807]
Trying to start the LAN mode in games like Mario Kart 8 Deluxe seems to correctly set up 3 UDP sockets. However after creating a room only one call to RecvFrom is logged. I'm not entirely sure why that is the case, but it seems that the service thread is blocked due to the game not requesting a non-blocking socket. But if the whole service is blocking the game isn't able to send broadcast messages announcing the room (Maybe the game starts multiple threads each controlling a blocking socket?). When I used a real switch connected to the same network I noticed it sent some broadcast packets. These packets seemed to stop the bsd service from blocking and the log showed that the game called RecvFrom again and even did two calls to SendTo. The real switch seems to have stopped the thread block. With this knowledge I wrote a small [script](https://gist.github.com/spholz/9480c72249dd6c93b58aedf80ab5da97) in python (note: this script is for linux only. I don't know if and how you can get the size of the receive queue on Windows) that constantly checks if one of the ports used by the game has an empty receive queue and fills it up with zeroes so that the game can continue handling other events and even announce the room correctly. This script indeed made Mario Kart 8 Deluxe running inside yuzu able to communicate with a real switch. After applying a small patch to IGeneralService::GetCurrentIpConfigInfo that hardcodes the local IP address of my PC I was even able to start a race. This patch combined with the script made the LAN mode of Mario Tennis Aces work, too. However, the Splatoon 2 LAN mode hangs when creating or joining a room.

**Comment by spholz** [comment]
I'm not sure what's the root cause that stops the game from creating more calls to RecvFrom and SendTo.

**Comment by spholz** [comment]
Another bug: When stopping the game inside the emulator it doesn't close the sockets opened by the game and therefore the emulator has to be restarted each time after going into LAN mode. Because after starting the game again without closing the emulator creates duplicate sockets with the same ports which leads to the LAN mode not working anymore.

**Comment by spholz** [comment]
Splatton 2 LAN mode now works after implementing some missing functions that are part of the IAudioIn service

**Comment by PacoAvelar** [comment]
Does that actually means that you can play multiplayer using 2 yuzu instances? (same or diff pc)
Or that it just doesnt get stuck/crash

**Comment by spholz** [comment]
I can actually play multiplayer with another pc (has to have a different IP address) or with a real switch. You only have to be in the same network.

**Comment by FernandoS27** [comment]
Hi spholz, you can contact me in discord if you want (Blinkhawk#2544) I can help you with the socket issues. I'm a bit tight on time but I can dedicate some if you need.
