### ISSUE TITLE
Xinput analog thumbstick not clipped to circle

### ISSUE THREAD

**Issue by FPGA-Computer** [yuzu-emu/yuzu#6814]
In Monster Hunter Story 2, there are some head to head showdown that requires rotating the right thumbstick. e.g. Monsties shooting fire or water against each other.

The game have problem tracking the rotation when the thumbstick is outside the circle area.  The rotating thumbstick icon going on/off as it crosses the threshold.  For the rest of the game, this is not an issue.  

The following under Windows with a Xbox 360 controller.

![controller](https://user-images.githubusercontent.com/8140495/128205587-2638c2ae-7981-4a77-a5b0-5c45361bba9d.png)

[Ryujinx PR - Clamp controller sticks to circle, instead of square #2493](https://github.com/Ryujinx/Ryujinx/pull/2493) reported issue with Skyward Sword "Superwalk" when thumbstick at diagonal.

>Xinput devices provides axis data with square ranges, ie +-32767. Moving the sticks to diagonal ends means that it will have the max range values for both axes. This causes fast motion of player characters in games that do not clamp their input.

>This fixes it by clamping the input to a circle. Fixes Link sprinting without using up stamina when the controller sticks are at diagonals

**Comment by german77** [comment]
The blue dot it's what I call raw data view it shows the literal input from the controller not the clamped one of the emulation. On the animated joystick you can see it always stays inside it's circle. I should probably add a second dot showing the actual input the game sees.

But I can guarantee that all input it's clamped to the unit circle. Make sure you are using latest EA. I broke calibration in a EA version recently

**Comment by german77** [comment]
I added the dot here #6815

**Comment by german77** [comment]
The PR has already been merged. Feel free to test
