### ISSUE TITLE
Pokemon Sword & Shield - Event need to Save the Game Rarely CRASH

### ISSUE THREAD

**Issue by lovanto** [yuzu-emu/yuzu#6821]
When I try to get fossil items for pokemon fossil always going crashes or stops working just for the left guy ONLY.
CRASH when start for saving the game.

Version: Yuzu Early Access 1965.
Game: Pokemon Sword (Ver 1.3.2) + 2 DLC.

**Comment by BSoDGamingYT** [comment]
Please post a game log

**Comment by FernandoS27** [comment]
and a save file :).

**Comment by lovanto** [comment]
Here I got more the same bug too when I try on another place. Especially when the game asks to save the game to continue. @FernandoS27 @BSoDGamingYT 
Game Log: 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6944588/yuzu_log.txt)
Save File: 
[0100ABF008968000.zip](https://github.com/yuzu-emu/yuzu/files/6944606/0100ABF008968000.zip)

**Comment by G-Spawn** [comment]
We don't support piracy here. Closing in favor of pre-existing issues regarding sw/sh stabilty.
