### ISSUE TITLE
英雄伝説 閃の軌跡：改,英雄伝説 閃の軌跡Ⅱ：改 issue

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#6824]
there is 2 issues on these game
1. both game not booting on early access 1967 but it boots fine on mainline 708
early access log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6942116/yuzu_log.txt)

2.英雄伝説 閃の軌跡：改 crashes due to unimplemented shader

<img width="1045" alt="Discord_BxQcqpAjS1" src="https://user-images.githubusercontent.com/66776795/128434677-7b368452-66e6-4af1-ade7-20ddceaace9d.png">

3.  改,英雄伝説 閃の軌跡Ⅱ：改 vulkan crashes due to unimplented texture  format

log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6942128/yuzu_log.txt)

**Comment by OZtistic** [comment]
Just for devs looking at this, games are:
The Legend of Heroes: Trails of Fire
and
The Legend of Heroes: Trails of Fire II

**Comment by gidoly** [comment]
weirdly enough recent game update fixed all issue on yuzu so i will close it

**Comment by kurenaihana** [comment]
> Just for devs looking at this, games are: The Legend of Heroes: Trails of Fire and The Legend of Heroes: Trails of Fire II

Just a heads-up, but the localized titles are actually `The Legend of Heroes: Trails of Cold Steel I` and `The Legend of Heroes: Trails of Cold Steel II`.
