### ISSUE TITLE
Xenoblade Games Crashing on AMD

### ISSUE THREAD

**Issue by RinMaru** [yuzu-emu/yuzu#6826]
Windows 11
AMD RX 480 4GB Adrenalin 21.7.2
20GB DDR4 RAM
Ryzen 5 5600 6Cores 12 Threads

Xenoblade DE
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6942302/yuzu_log.txt)
Xenoblade C2
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6942305/yuzu_log.txt)

Crashes started shortly after Hades landed on EA

**Comment by goldenx86** [comment]
Confirmed that this is a Windows only issue, Mesa is stable. that should help narrow it down.

**Comment by RinMaru** [comment]
its caused by the DLC if you disable them the game loads. so a regression happened somewhere. it also happens in Xeno DE but once you disable the update it loads
