### ISSUE TITLE
Splatoon 2 ignores Garbage Collection on OpenGl

### ISSUE THREAD

**Issue by Lt-knb** [yuzu-emu/yuzu#6848]
Ryzen 7 2700
RAM 16 GB
Gtx 1070
Windows 10 1909
Nvidia driver game ready 471.11
Yuzu Early Access 1978

Splatoon 2 completely ignores Garbage Collection on OpenGl renderers.
For this reason #6611 and #5307 are only fixed on Vulkan for now, also the latter still happens and is unrelated to Hades so i highly recommend to reopen it

**Comment by FernandoS27** [comment]
in OGL memory will fill and the driver will do the cleaning. The Garbage Collector works differently on GL than Vulkan. While in vulkan we immediatly free the memory as we control memory directly. In OGL, we just free the texture and the driver decides when to recycle that memory.

**Comment by Lt-knb** [comment]
> in OGL memory will fill and the driver will do the cleaning. The Garbage Collector works differently on GL than Vulkan. While in vulkan we immediatly free the memory as we control memory directly. In OGL, we just free the texture and the driver decides when to recycle that memory.

Is there a solution to this?

**Comment by Lt-knb** [comment]
Tested #6897. Behavior remains the exact same

**Comment by Lt-knb** [comment]
Just tested and it works now
