### ISSUE TITLE
Broken photo evaluation: Pokemon Snap cannot detect Pokemons in Photos. Says "You have no photos to show to the professor. Skipping evaluation"  and "No Subject" as caption in each photo taken.

### ISSUE THREAD

**Issue by HiDe-Techno-Tips** [yuzu-emu/yuzu#6850]
# Pokemon Snap cannot detect Pokemons in Photos:

* Game: `Pokemon Snap`
* yuzu Version: `Early Access 1984`
* OS: Windows 10 64-bit 21H1
* Specs:
  * CPU: `Core i5 7200U`
  * RAM: `8GB`
  * GPU: `GeForce 940MX 2GB`
* Logs: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6958896/yuzu_log.txt)

I am impressed by how beautiful the Graphics of this game is, yet the framerates are so satisfying. Team yuzu has done a great job, as right now, even games like Zelda BOTW runs so well in even mid range PCs. This is really impressive.

However, I found a problem in Pokemon Snap that makes it completely implayable despite the smooth and high framrates. I hope yuzu Team will see this report of mine and will continue making yuzu even better than ever.

# Ways to reproduce:
* I took about 72 photos of 13 unique pokemons evident from the Screenshot below:
![yuzu Early Access 1984 _ New Pokémon Snap (64-bit) _ 1 2 0 _ NVIDIA 8_10_2021 9_09_38 AM](https://user-images.githubusercontent.com/61367380/128805679-afadbbba-82f5-40ef-af3b-7ab49dd4422a.png)

* When I continue ahead with the gameplay, its time to show those photos to the professor, but i end up in a situation shown in the below Screenshot:
![yuzu Early Access 1984 _ New Pokémon Snap (64-bit) _ 1 2 0 _ NVIDIA 8_10_2021 9_09_55 AM](https://user-images.githubusercontent.com/61367380/128805943-c38d9b47-4c54-4f6b-9771-4144e3adab42.png)

* This is strange because if you see the screenshots below, the pokemons are clearly visible in the photos taken, yet you see the `No Subject` caption below each photo in the screenshot:
![yuzu Early Access 1984 _ New Pokémon Snap (64-bit) _ 1 2 0 _ NVIDIA 8_10_2021 9_11_44 AM](https://user-images.githubusercontent.com/61367380/128806138-50e39ffe-2afd-4c4b-aa66-242b5de3b66b.png)
![yuzu Early Access 1984 _ New Pokémon Snap (64-bit) _ 1 2 0 _ NVIDIA 8_10_2021 9_11_27 AM](https://user-images.githubusercontent.com/61367380/128806148-3b98c51f-962e-4233-b946-23015b8fb435.png)
![yuzu Early Access 1984 _ New Pokémon Snap (64-bit) _ 1 2 0 _ NVIDIA 8_10_2021 9_11_36 AM](https://user-images.githubusercontent.com/61367380/128806153-a2b07fa7-5bb9-4fb8-a71a-4afcdb18e094.png)
![yuzu Early Access 1984 _ New Pokémon Snap (64-bit) _ 1 2 0 _ NVIDIA 8_10_2021 9_11_38 AM](https://user-images.githubusercontent.com/61367380/128806156-61ca6bcf-e409-4aed-b134-d4de345543da.png)

**Comment by dazemc** [comment]
I first noticed this issue in EA 1644, after the autoclave fix.

**Comment by ameerj** [comment]
Have you tried setting GPU Accuracy to High?

**Comment by HiDe-Techno-Tips** [comment]
> Have you tried setting GPU Accuracy to High?

I have not tried yet, but i will.
BTW, how is this supposed to be a GPU problem? Its not related to graphics, I guess.

**Comment by dazemc** [comment]
I have tried every possible combination of vulkan/opengl settings and CPU settings. I have even made builds in Linux to verify it wasn't a graphics driver issue. I have a 1950x threadripper with a 1050 ti. The only emulator I have found to properly produce accurate results is Ryujinx, but I get major performance issues due to my graphics card.

**Comment by HiDe-Techno-Tips** [comment]
> Have you tried setting GPU Accuracy to High?

Thanks @ameerj, I was able to solve this problem by setting GPU Accuracy to High.

@dazemc, maybe you should try the same. Go to `Emulation`>`Configuration`>`Graphics`>`Advanced` in yuzu and set `Accuracy Level:` to `High`.

I am cIosing this issue now, but I would really appreciate an explaination on why this works with High GPU Accuracy, even when its not a Graphics related problem.

**Comment by goldenx86** [comment]
If the game uses shaders for this logic, it is a graphics problem.

**Comment by dazemc** [comment]
Lol, maybe you missed the part where I said I tried every combination. Honestly, I'm done with Yuzu, shitty fucking support.

**Comment by dazemc** [comment]
> > Have you tried setting GPU Accuracy to High?
> 
> Thanks @ameerj, I was able to solve this problem by setting GPU Accuracy to High.
> 
> @dazemc, maybe you should try the same. Go to `Emulation`>`Configuration`>`Graphics`>`Advanced` in yuzu and set `Accuracy Level:` to `High`.
> 
> I am cIosing this issue now, but I would really appreciate an explaination on why this works with High GPU Accuracy, even when its not a Graphics related problem.

Yes I have tried that.... In fact, that is my most upvoted comment in the Yuzu reddit thread. SMH your problem isn't fixed. Pay attention to the "Size" score.

**Comment by dazemc** [comment]
Lol you probably even got that from my comment

**Comment by dazemc** [comment]
And just to, REITERATE; THIS PROBLEM HAS BEEN PERSISTENT SINCE EA-1644. FFS I am a programmer, this is a bug, end of sentence. Stop sending me this, "did you try....", Yes I fucked tried it, stfu.

**Comment by ameerj** [comment]
@dazemc the suggestion to use High accuracy was for the issue author, not you. Their issue was that none of their photo subjects were being recognized, which is alleviated with a higher accuracy to allow further progression.

There is an issue with subject detection in general, and this was greatly improved recently compared to when the game first launched, likely due to shader and buffer cache updates. I know this because i was going to look into fixing the tutorial detection issue and saw that it was consistently being recognized.

Regarding your statement about the yuzu subreddit. That is not an official support platform, and none of the yuzu staff moderate it (GoldenX86 drops by every once in a while though). The official support channels are Discord and the Citra forums.

**Comment by goldenx86** [comment]
The usual reddit attitude shows. Part of the reason I get "vacations" from helping there.

**Comment by dazemc** [comment]
Honestly, learn how to read. I reference the stable releases in my bug report. You all are stupid and ignorant as fuck
