### ISSUE TITLE
New Pokemon Snap crashes or softlocks on opening Photodex

### ISSUE THREAD

**Issue by HimDek** [yuzu-emu/yuzu#6851]
# New Pokemon Snap crashes or softlocks on opening Photodex:

* Game: `New Pokemon Snap`
* Game version: `1.2.0`
* yuzu Version: `Early Access 1984`
* OS: Windows 10 64-bit 21H1
* Specs:
  * CPU: `Core i5 7200U`
  * RAM: `8GB`
  * GPU: `GeForce 940MX 2GB`
* Logs: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6959361/yuzu_log.txt)

Solving this crash on Photodex issue might actually make this Game almost perfectly Compatible in yuzu.
There was one more problem in this game apart from this and the autosave problem, that is [this problem](https://github.com/yuzu-emu/yuzu/issues/6850) with evaluation of photos. This is however solved by setting GPU accuracy to High.

# Ways to reproduce:
* Just open the Photodex in New Pokemon Snap and the game will crash or maybe its softlock as sounds will still be heard.

#### EDIT: This happens in both OpenGL and Vulkan, however slightly delayed in Vulkan but almost instantly after open Photodex while using OpenGL.

**Comment by OZtistic** [comment]
@HiDe-Techno-Tips 
I cannot reproduce this on EA 1984. Including using the 1.2.0 Snap update and starting a game from scratch
Everything worked as expected
Photodex opened fine when it became available

![image](https://user-images.githubusercontent.com/71381851/128852431-65937d7b-117b-4897-9cb7-e0df9ae59379.png)


**_Solution:_**
Firstly, turn off Asynchronus Shader building **(Emulation --> Configure --> Graphics --> Advanced**
then update your GPU drivers on Nvidia's Geforce driver site. Yours are a bit old
`[  95.145828] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:185: Driver: NVIDIA 466.47.0.0`
The current version is 471.41
 
 Seeing as you only have 8gig of RAM, I would highly suggest enlarging your Pagefile/Virtual Memory in Windows to 20gig to avoid any memory issues with other titles as well
 
 In future please use the Discord or yuzu Forums for troubleshooting issues. They will tell you if you should lodge a Issue ticket here or not
 Thanks!

**Comment by HiDe-Techno-Tips** [comment]
> @HiDe-Techno-Tips
> I cannot reproduce this on EA 1984. Including using the 1.2.0 Snap update and starting a game from scratch
> Everything worked as expected
> Photodex opened fine when it became available
> 
> ![image](https://user-images.githubusercontent.com/71381851/128852431-65937d7b-117b-4897-9cb7-e0df9ae59379.png)
> 
> **_Solution:_**
> Firstly, turn off Asynchronus Shader building **(Emulation --> Configure --> Graphics --> Advanced)**
> then update your GPU drivers on Nvidia's Geforce driver site. Yours are a bit old
> `[ 95.145828] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:185: Driver: NVIDIA 466.47.0.0`
> The current version is 471.41
> 
> Seeing as you only have 8gig of RAM, I would highly suggest enlarging your Pagefile/Virtual Memory in Windows to 20gig to avoid any memory issues with other titles as well
> 
> In future please use the Discord or yuzu Forums for troubleshooting issues. They will tell you if you should lodge a Issue ticket here or not
> Thanks!

What is your config? Could you share the qt-config.ini file so that I could test while using your settings?

**Comment by pacoa-kdbg** [comment]
hi @HimDek 
Is this issue still happening to you ?

**Comment by gidoly** [comment]
can you test this again i haven't heard same issue for while i want to close if there is no update for month

**Comment by gidoly** [comment]
can you test this again i haven't heard same issue for while i want to close if there is no update for month

**Comment by HimDek** [comment]
I am not playing that game anymore so I don't really care.
