### ISSUE TITLE
Please add Dead or Alive Xtreme 3: Scarlet to Game Compatibility List

### ISSUE THREAD

**Issue by danielgmz** [yuzu-emu/yuzu#6856]
I would like to see Dead or Alive Xtreme 3: Scarlet into game compatibility list so I can tell if this game has been tested.
Thanks.

**Comment by Mangaclub** [comment]
It works great on Vulkan. IT has problems switching between different levels gettign stuck.

**Comment by danielgmz** [comment]
> It works great on Vulkan. IT has problems switching between different levels gettign stuck.

It seems to work, but sadly they don't want to add this game to the official YUZU compatibility list.

**Comment by liamwhite** [comment]
[Compatibility updates go here](https://github.com/yuzu-emu/yuzu-games-wiki/wiki).
