### ISSUE TITLE
yuzu mainline 708 Bug - Pokemon Sword & Shield characters noticeably darker in overworld than on real hardware

### ISSUE THREAD

**Issue by emufa** [yuzu-emu/yuzu#6859]
Version - yuzu mainline 708

Pokemon Sword & Shield have an issue with characters in the overworld being cast darker than they do on real hardware. The problem can be fixed by toggling the Adv. Graphics Accuracy level to Extreme and then back to High again, but obviously that's tedious to do whenever I start the game. This also only affects the models that are on-screen currently -- It seems like if I fly to another location, NPCs in that new location are also shadowy.

Example Image:

![before](https://user-images.githubusercontent.com/88774135/129013722-ba630e81-dca4-4a5b-ade4-194db2417855.png)

How it should look, both on real hardware and after toggling the GFX Accuracy:

![after](https://user-images.githubusercontent.com/88774135/129013798-632c9aa4-159f-4999-8756-97c219bc996c.png)

**Comment by cybercjt** [comment]
I believe the issue here is incorrect lighting, I've experimented on this one by going in and out of shades beside random buildings. Setting the accuracy level to Extreme might fix it but it comes with other bugs like stationary rainstorm / rain not dropping etc.

**Comment by Lewchube** [comment]
Yeah, those things do happen when setting to Extreme. Besides, it's also far laggier that way for obvious reasons so just keeping it on there is less than ideal performance-wise. Also can confirm that over time, whether it's flying to another area or just entering different locations does the lighting bug return post-toggle. It's just astoundingly noticeable at this point.

**Comment by gidoly** [comment]
fixed on last mainline and ea
