### ISSUE TITLE
Yo-kai watch 4++ Overbright bug

### ISSUE THREAD

**Issue by einekratzekatze** [yuzu-emu/yuzu#6864]
Yo-kai watch 4++ (妖怪ウォッチ4++) 010086C00AF7C000
Issue: while in the world most of the screen renders white. you can see a bit  trough the mini-map. All Menus render normally even those who overlay 
I have no other Issues and at least 30 fps no matter if i use Vulkan or OpenGL and Normal or High Accuracy Level 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6796230/yuzu_log.txt)

![image](https://user-images.githubusercontent.com/48450457/125180775-7cff9700-e1fe-11eb-9b7d-9cf31e8af1ea.png)
Text Box has no errors under it
![image](https://user-images.githubusercontent.com/48450457/125181124-f77de600-e201-11eb-989e-2671096bbc5e.png)
When Entering a new area you can see fine while it fates out and in 
If you want to buy the game for testing:
https://www.youkai-watch.jp/8th-anniversary/sale/ 
the game costs during that offer just 3780 Yen which is about 29 Euro
it goes until 2.8. 

I have created this in #6585 which was not the place for it so i copied it over.

**Comment by Fuzzy64** [comment]
I'm having the same bug as you 
![image](https://user-images.githubusercontent.com/88057380/129409988-802dd016-5dd6-48c9-935f-7fb79fff71e3.png)

**Comment by gidoly** [comment]
fixed with yfc 1
