### ISSUE TITLE
VULKAN ERRO

### ISSUE THREAD

**Issue by italo17476** [yuzu-emu/yuzu#6865]
"Yuzu encountered an error while running the video core."

[https://imgur.com/a/yATqLH8](url)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6978811/yuzu_log.txt)

[ 695.059525] Render.Vulkan <Error> video_core\vulkan_common\vulkan_device.cpp:CheckSuitability:741: Missing required extension: VK_KHR_shader_float_controls
[ 695.063835] Render.Vulkan <Error> video_core\renderer_vulkan\renderer_vulkan.cpp:RendererVulkan:121: Vulkan initialization failed with error: VK_ERROR_EXTENSION_NOT_PRESENT
[ 695.063900] HW.GPU <Error> video_core\video_core.cpp:CreateGPU:51: Failed to initialize GPU: Vulkan initialization error VK_ERROR_EXTENSION_NOT_PRESENT
[ 695.070906] Core <Critical> core\core.cpp:Load:231: Failed to initialize system (Error 5)!

**Comment by goldenx86** [comment]
Update your GPU driver.

**Comment by italo17476** [comment]
> Update your GPU driver.

I updated and now the emulator closes when starting the game!

**Comment by goldenx86** [comment]
Please get in contact with us in the support channels, our forums or the Discord server.
https://community.citra-emu.org/c/yuzu-support/14
https://discord.gg/u77vRWY
