### ISSUE TITLE
Paper Mario memory leaks when loading a new area.

### ISSUE THREAD

**Issue by xxgamerpro** [yuzu-emu/yuzu#6871]
Yuzu Version : 71d8d84
Reproduce : Going into new areas and fighting battles will fill up memory loading the area.
Log : [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6985316/yuzu_log.txt) (cut off during the crash)

**Comment by xxgamerpro** [comment]
> Yuzu Version : [71d8d84](https://github.com/yuzu-emu/yuzu/commit/71d8d84b59ae6e1cfad37d70e6ea7d61001326f3)
> Reproduce : Going into new areas and fighting battles will fill up memory loading the area.
> Log : [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6985316/yuzu_log.txt) (cut off during the crash)

Enabling GPU garbage collection seems to have fixed the issue.

**Comment by v1993** [comment]
Please confirm that leak have been fixed by turning GC on and close if it was. It worked fine for hours for me on OpenGL without any leaks.

It would also be nice if you clarified if you're talking about VRAM leak or RAM leak since those are very different kinds of leaks.
