### ISSUE TITLE
Input device always set to ANY when dual Joycon is selected

### ISSUE THREAD

**Issue by KirbyFighter** [yuzu-emu/yuzu#6872]
This is pretty weird but for what ever reason when i connect my Joycons to my and launch yuzu, if i set input to Nintendo Dual Joy-cons when i close the settings window and reopen it the input device will be set to ANY no matter what i do.

https://user-images.githubusercontent.com/71234367/129453303-b4bcccbc-503e-464b-965c-1443443d6a5a.mp4

**Comment by german77** [comment]
Dual joycon is made up of two separate devices left joycon and right joycon. Any is set when more than one device is detected. I can make a exception for dual joycons but so far it hasn't worked correctly. This is a logical bug, play wise nothing should be affected

**Comment by dairi2566** [comment]
I think you forgot to press save.

**Comment by german77** [comment]
No. The issue is real. It will work fine. Just show any in the drop down box
