### ISSUE TITLE
Pokémon Sword & Shield - Evento necessário para salvar o jogo resultando em CRASH

### ISSUE THREAD

**Issue by RonaldoKeizer** [yuzu-emu/yuzu#6873]
Quando eu tento obter itens fósseis, ou tentar a Lotu nos computadores, ou ativar um daqueles terminais com uma estrela de desejo ou ate mesmo nos npc que escavam pra vc á procura de itens, ou na maquina de reciclagem de itens na ilha da armadura sempre vai travar, resumindo crasha quando é necessario dar esse save para que o npc ou maquina possa realizar e concluir a atividade, sendo o save um pré requisito para isso

Versão: Yuzu Early Access 1993.
Jogo: Pokémon Sword (Ver 1.3.2) + 2 DLC.

Vi que já foi reportado a 10 dias atrás em uma versão anterior contudo vejo que o erro persiste

**Comment by gidoly** [comment]
duplicate of sw sh multicore issue thread closes due to duplicate and plz make issue with english in future :)
