### ISSUE TITLE
[Crash] Pokemon Sword crash when I arrive at Wedgehurst Town

### ISSUE THREAD

**Issue by Schneitizel** [yuzu-emu/yuzu#6876]
Hello everyone!

Yesterday, while playing Pokemon Sword, the game suddenly froze and Yuzu immediately closed, this happened when I arrived in Wedgehurst Town, after receiving my first Pokemon (So I already welcomed the champion before)

Attached is the error log

Thank you for having !

Yuzu version : EA 1993
CPU accuracy : Auto
Video API : OpenGL (GLASM)
Video accuracy : Normal
Processor : Intel Core i5-7600K
GC : GeForce GTX 1070 8Gb
Memory : 2x8Gb

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6988830/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
This log is basically empty. Please provide a complete log

**Comment by Schneitizel** [comment]
Haha, how I am stupid, Yuzu deleted the log
I'll make one again right now, sorry :/

**Comment by Schneitizel** [comment]
Well, obviously, the game does not crash anymore :)
I'll play, and try to reproduce the bug, sorry ><

**Comment by Schneitizel** [comment]
Here, I edited my first message
For info, it did it to me again while I was confronting the squirrel at the beginning, while he was attacking

**Comment by gidoly** [comment]
this seems related to multicore issue for sw sh closing due to duplicate
