### ISSUE TITLE
Latest Yuzu crash my laptop

### ISSUE THREAD

**Issue by HaziqBD** [yuzu-emu/yuzu#6880]
I played Sword before and it's running fine. Then I got the latest update and it makes my laptop to BSOD. The game stuck at launching and after a while, it crashes my laptop. Not just Yuzu. Here's a log file if it helps.

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6998704/yuzu_log.txt.old.txt)

**Comment by G-Spawn** [comment]
Disable the mods and try again or perhaps redump the game's update. If you need further support please consider joining the discord and asking there https://discord.gg/u77vRWY. The issue doesn't seem to be consistent here on either of my rigs with same update in use.

**Comment by HaziqBD** [comment]
> Disable the mods and try again or perhaps redump the game's update. If you need further support please consider joining the discord and asking there https://discord.gg/u77vRWY. The issue doesn't seem to be consistent here on either of my rigs with same update in use.

It works. thanks. I remove the update and disable the mods.

**Comment by Moonlacer** [comment]
Can be closed now
