### ISSUE TITLE
Rune Factory 5 graphic issues and icon missing

### ISSUE THREAD

**Issue by Hikari753** [yuzu-emu/yuzu#6892]
Hi, I would like report some problems about  Rune Factory 5 that I encountered while using yuzu721.
I don't really use English often, but I will try to use some images and videos to explain.

1. Using garbage collection will cause graphic issues and missing the black background while entering an event.
(both Opengl and Vulkan)

Without garbage collentions:

https://user-images.githubusercontent.com/89215186/130209520-401ef9ae-8f0d-4e54-ad47-d466f0e82d07.mp4

With garbage collentions:
![9](https://user-images.githubusercontent.com/89215186/130211352-c300a0d8-040a-4297-829b-121cbf7079b5.png)

https://user-images.githubusercontent.com/89215186/130209591-2ef09926-29c6-4671-aa5e-505860b8c1c8.mp4

2. And is seems like if you don't set cpu accuracy to accurate will cause a problem.
 (This two npcs's skirts will bug.)

![1](https://user-images.githubusercontent.com/89215186/130212578-203f0add-4ec2-47e4-8ae2-537d3c64245a.png)
  
when set to accurate:

![2](https://user-images.githubusercontent.com/89215186/130212599-2f344c3c-ce5d-4929-906c-ca98ebfed071.png)

3. And it seems like if you don't set gpu to extreme it will also cause a problem.
(Icon and text missing when you second open any containers in the game. The first time after you open the game is normal though.) 
(The request board will be missing its text and icons once there's any new requests popping out.)

![3](https://user-images.githubusercontent.com/89215186/130212707-bef36ee5-1828-4dc0-8d96-05cebdce46d3.png)
![4](https://user-images.githubusercontent.com/89215186/130210807-87965dc3-46be-4943-abf7-ea6b5547b49a.png)
normal:

![5](https://user-images.githubusercontent.com/89215186/130214218-1a8d34b0-9e1d-4c37-a333-793d2a89e48c.png)
![6](https://user-images.githubusercontent.com/89215186/130214262-c2c2c876-fea6-42ff-a9b0-7c60d762bde2.jpg)

graphic issues after changing maps:
(This will happen when you change maps more than two times.)

![7](https://user-images.githubusercontent.com/89215186/130214280-690bb559-863c-4721-94fc-f27b5239d4dd.png)

normal(with gpu set to extreme):
![8](https://user-images.githubusercontent.com/89215186/130214309-aa635c06-7e8c-4f2c-af4c-5c767dcf41c0.jpg)

And after playing for a while, using Vulkan will crash before it complete building the shade
![00](https://user-images.githubusercontent.com/89215186/130211945-8d1aaa3d-325d-4382-80e2-e1be0ed39a12.png)

My Spec:
Windows 10
Cpu: Intel(R) Core(TM) i7-8565U
Gpu: Intel(R) UHD Graphics 620
        NVIDIA GeForce GTX 1650 with Max-Q Design
Ram: 16G

If there's any files I could provide, please tell me!

**Comment by BSoDGamingYT** [comment]
Please provide a log file and a game save please

**Comment by Hikari753** [comment]
Hi, thanks for the replying.
Here's my log and save files.
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7020779/yuzu_log.txt.old.txt)

[save flies rf5.zip](https://github.com/yuzu-emu/yuzu/files/7020807/save.flies.rf5.zip)

**Comment by exjah** [comment]
Hi, it seems to be happen even though i set graphic to extreme. Did you fix this issue?

**Comment by v1993** [comment]
First one should be gone by now since GC was rewritten.

**Comment by exjah** [comment]
> First one should be gone by now since GC was rewritten.

yes! first one seemed to be fixed but third one (Icon and text missing) is still happening.

**Comment by gidoly** [comment]
should fixed on last ea and mainline plz reopen if you still experiance this
