### ISSUE TITLE
Random crashes with Vulkan on Windows

### ISSUE THREAD

**Issue by Lithium64** [yuzu-emu/yuzu#6895]
There have been random crashes on yuzu for quite some time when playing on windows using vulkan. Even after Hades the problem continues, I suspect it's a bug in AMD's driver. Because when I play on Linux the emulator is very stable and never crash playing with Vulkan backend. 

Specs:

CPU: Intel i3 10100F
GPU: AMD R7 260X 2GB VRAM
RAM: 16 GB DDR4 3000 Mhz
Motherboard: MSI H410M-A Pro
Windows 10 Pro 21H1

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7023201/yuzu_log.txt)

**Comment by Lithium64** [comment]
I don't understand why, but a bios update that enabled above 4G decoding and resizable BAR fixed the issue.

**Comment by benderscruffy** [comment]
please close
no update for a couple of years
