### ISSUE TITLE
Super Smash Bros. Ultimate: World of Light Blackscreen (Menu, Map, and Battle)

### ISSUE THREAD

**Issue by pixel-monster24** [yuzu-emu/yuzu#6898]
Hello,

Since the Hades update, Super Smash Bros. Ultimate has been working really well using Vulkan for me. However in the World of Light Adventure mode, I am not able to start a battle without a black screen. There is still audio, and I can blindly walk off the edge and die to exit back into the map or quit via the pause screen. 

This black screen behavior also occurs occasionally in the World of Light map, as well as the World of Light menu. Sometimes I am able to pause/unpause in the map and have the screen restored, but I am unable to see the battle regardless of what I try. 

I have tried "Remove All Shader Caches" and relaunched, but the issue still persists.

I believe this is a similar issue that user "cristianosiebert-itajai" posted before the Hades update, but I'm not sure. Regardless he/she did not provide a log file (yet), so I will provide mine in case it is the same issue and/or a new one. 

Specs:
CPU: Intel i7 6700 (non-K)
GPU: NVIDIA GeForce GTX 980 Ti
RAM: 16 GB DDR4 2133 MHz
Swap: 20 GB
Windows 10 Pro 20H2
Yuzu Version 722 

Yuzu log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7024260/yuzu_log.txt)

**Comment by G-Spawn** [comment]
This is known and happened prior to hades update as well.

A slight workaround for now is

"When you load into a WOL fight, you are going to be met with a black screen. Once you hear "ready", press pause (+) then press down, then press A, then press A again. You'll hear a screenshot sound and get an error pop up. Press OK on the error....then press B twice to get back to gameplay. Once in gameplay, run right to run off the stage and die....Once you do this, the game will start to render, allowing you to complete the fight"

Beyond that it'll require further fixes in emu.

**Comment by darkthirsty** [comment]
Change the Shader Backend to: GLSL
and try playing it

**Comment by G-Spawn** [comment]
> Change the Shader Backend to: GLSL and try playing it

Easier to just wait for yfc project part one to be in mainline. This change is already in early access and world of light works there.

**Comment by darkthirsty** [comment]
> > Change the Shader Backend to: GLSL and try playing it
> 
> Easier to just wait for yfc project part one to be in mainline. This change is already in early access and world of light works there.

Yeah, on the early access release part 1, change the shader backend to GLSL it worked, but it didnt work without glsl even with early access

**Comment by gidoly** [comment]
fixed with yfc part 1
