### ISSUE TITLE
Monster Hunter Rise Corrupted Models

### ISSUE THREAD

**Issue by toto621-linux** [yuzu-emu/yuzu#6899]
yuzu Early Access 2005
CPU: Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz | AVX2 | FMA
GPU: NVIDIA GeForce RTX 2070
RAM: 31.94 GB
OS: Windows 10

As you can see on the screenshot below, it do not render as it should. Tested on Vulkan and OpenGL
![MHR](https://user-images.githubusercontent.com/88256778/130301338-5486e73a-46ad-46be-ba55-11d9c15bbdd7.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7024410/yuzu_log.txt)

**Comment by G-Spawn** [comment]
I'm pretty sure this has already been reported but thanks.

**Comment by toto621-linux** [comment]
Couldn't found already reported issue related to this problem (I probalby missed it) so I decided to make a report.

**Comment by G-Spawn** [comment]
No worries. It's a very common problem for the users on discord so if it wasn't already reported here it is appreciated.

**Comment by lKobi** [comment]
Be advised this is not fixed whasoever, just tested with version 1.0 of games on Yuzu 2820.

Also recent update and expansion, causes even more severe issues, https://github.com/yuzu-emu/yuzu/issues/8519

**Comment by Jenoz504** [comment]
> fixed with vulkan and gpu accuracy high

the game don´t start with vulkan
