### ISSUE TITLE
legend of mana blackscreen

### ISSUE THREAD

**Issue by ziifr000** [yuzu-emu/yuzu#6902]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7025186/yuzu_log.txt)

**Comment by G-Spawn** [comment]
please disable async shaders and compare.

**Comment by ziifr000** [comment]
async shaders in advance graphics setting already disable

**Comment by ziifr000** [comment]
in main menu

**Comment by G-Spawn** [comment]
Then you have it configured per game please disable it in game properties. Per game async set can take precedence over global.

**Comment by kiaoru** [comment]
i didn't know it was on 😅, i turn it off still black screen

**Comment by ziifr000** [comment]
i didn't know it was on 😅, i turn it off still black screen

**Comment by seanluse41** [comment]
any progress? love this game

**Comment by gidoly** [comment]
fixed with yfc 1
