### ISSUE TITLE
BOTW and Hyrule Warrior: AOC Crashing on Vulkan

### ISSUE THREAD

**Issue by LAVEXLEON** [yuzu-emu/yuzu#6906]
As mentioned above in the title, both BOTW and Hyrule Warrior are crashing on the Zelda Loading Screen (the latter at the beginning of the first area just after the cutscene finishes). It works fine on OpenGL, but it barely gives me any speed to the point where I can play smoothly (15-20 FPS). Switching to Vulkan just ends up in a crash.

Pc Specs: 
8th Gen Intel Core i5
8GB ram
AMD Radeon GPU

Thanks in Advance!

**Comment by BSoDGamingYT** [comment]
Please post a log as per the issue format instructions

**Comment by LAVEXLEON** [comment]
@BSoDGamingYT Here is the log
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7025797/yuzu_log.txt.old.txt)

**Comment by BSoDGamingYT** [comment]
> @BSoDGamingYT Here is the log
> [yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7025797/yuzu_log.txt.old.txt)

Please disable async shader building and make sure your GPU drivers are up to date

**Comment by LAVEXLEON** [comment]
> > @BSoDGamingYT Here is the log
> > [yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7025797/yuzu_log.txt.old.txt)
> 
> Please disable async shader building and make sure your GPU drivers are up to date

I have already done it but it still ends up in a crash on Vulkan

**Comment by FernandoS27** [comment]
@LAVEXLEON was this fixed?

**Comment by codbugpatrol** [comment]
@FernandoS27 , after reading you question I went testing, on EA 2086, because I was having the same issue. 
And the problem in AoC crashing while in loading screen in Vulkan seems to be better, but not fixed
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7237209/yuzu_log.txt)
@LAVEXLEON , this issue should be kept open.
