### ISSUE TITLE
[WINDOWS][AMD][VULKAN] Fire Emblem : Three Houses - Lighting graphical glitches - Yuzu 724

### ISSUE THREAD

**Issue by DocTdb** [yuzu-emu/yuzu#6911]
Hi, 

In Fire Emblem Three houses lighting produces square artifacts in Vulkan.
Choosing OpenGL doesn't not produce those glitches but lighting seems totally absent.
I use Yuzu 724 released today.

My hardware : 
Ryzen 5900x
AMD Radeon 6800 XT - AMD software 21.6.1 Recent fresh install
Ram 32 Gb
Windows 10 Pro 21H1

Original Switch screenshot : 

![Cap_FETH_Switch](https://user-images.githubusercontent.com/54248720/130361630-e232c5cf-ab52-4444-95e7-41d820ab1c6f.png)

Vulkan screenshot : 

![Cap_FETH_Vulkan](https://user-images.githubusercontent.com/54248720/130361658-a6cad9f7-01e5-4d68-93b0-236f7832f818.png)

OpenGL screenshot : 

![Cap_FETH_OpenGL](https://user-images.githubusercontent.com/54248720/130361669-b8e4cdd4-6de9-4193-ac9a-601ba9251bcd.png)

Vulkan Log : 

[yuzu_Vulkan_log.txt](https://github.com/yuzu-emu/yuzu/files/7027675/yuzu_Vulkan_log.txt)

Do not hesitate if you need more info.
Thanks for all the work.

**Comment by kevin98761234** [comment]
I think this artifact and lighting is specific to AMDRadeon.
This shows up fine in NVIDIA.
![2021-08-23 014510](https://user-images.githubusercontent.com/88806005/130363365-abad9b3d-46d8-4e7e-9119-a8bca7543dab.jpg)

**Comment by DocTdb** [comment]
Thanks for the input kevin98761234. 

I've updated my drivers to 21.8.1 since some Vulkan extensions have been added / updated in 21.7.1.

Nothing changed sadly...

**Comment by soredake** [comment]
RX 560, latest beta drivers, windows 10, https://streamable.com/riwufa
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7040887/yuzu_log.txt)

**Comment by DocTdb** [comment]
Thanks Soredake for chiming in.

Another reference of the problem : 

https://github.com/yuzu-emu/yuzu/pull/6585#issuecomment-877526591

It confirm what kevin98761234 said, it's purely an AMD quirk.

**Comment by DocTdb** [comment]
Glitches are still present in Yuzu 730 + Amd drivers 21.8.2.

#6803 seems linked.

**Comment by DocTdb** [comment]
After quickly scrolling thru the logs, I saw some unsupported devices when loading the vulkan renderer.

It's maybe due to the use of some vendor specific Vulkan extension like VK_NV_geometry_shader_passthrough or VK_NV_viewport_swizzle unsupported on AMD hardware.

I'm almost totally Vulkan illiterate, so am I wrong if I say that it's not only driver related ?

**Comment by Katafiora** [comment]
I have tried FE3H on Ubuntu with 5700XT, can confirm that the OpenGL does not produce those "squares" yet the light is still missing. Actually, it looks exactly the same on windows, except faster game speed.

**Comment by soredake** [comment]
> I have tried FE3H on Ubuntu with 5700XT, can confirm that the OpenGL does not produce those "squares" yet the light is still missing. Actually, it looks exactly the same on windows, except faster game speed. 

Test with vulkan, please.

**Comment by Katafiora** [comment]
> > I have tried FE3H on Ubuntu with 5700XT, can confirm that the OpenGL does not produce those "squares" yet the light is still missing. Actually, it looks exactly the same on windows, except faster game speed.
> 
> Test with vulkan, please.

![Screenshot from 2021-08-30 15-34-03](https://user-images.githubusercontent.com/88550054/131311483-54fefc36-698c-4f72-aea1-ee8c9db30e8b.png)
Vulkan on Linux is quite a mess

**Comment by soredake** [comment]
> 
> 
> > > I have tried FE3H on Ubuntu with 5700XT, can confirm that the OpenGL does not produce those "squares" yet the light is still missing. Actually, it looks exactly the same on windows, except faster game speed.
> > 
> > 
> > Test with vulkan, please.
> 
> ![Screenshot from 2021-08-30 15-34-03](https://user-images.githubusercontent.com/88550054/131311483-54fefc36-698c-4f72-aea1-ee8c9db30e8b.png)
> Vulkan on Linux is quite a mess

When you move do you see more artifacts?

**Comment by Katafiora** [comment]
> > > > I have tried FE3H on Ubuntu with 5700XT, can confirm that the OpenGL does not produce those "squares" yet the light is still missing. Actually, it looks exactly the same on windows, except faster game speed.
> > > 
> > > 
> > > Test with vulkan, please.
> > 
> > 
> > ![Screenshot from 2021-08-30 15-34-03](https://user-images.githubusercontent.com/88550054/131311483-54fefc36-698c-4f72-aea1-ee8c9db30e8b.png)
> > Vulkan on Linux is quite a mess
> 
> When you move do you see more artifacts?

Not small artifacts, but big artifacts. And sometimes there are large big shadows, especially in battles.

**Comment by soredake** [comment]
> 
> 
> > > > > I have tried FE3H on Ubuntu with 5700XT, can confirm that the OpenGL does not produce those "squares" yet the light is still missing. Actually, it looks exactly the same on windows, except faster game speed.
> > > > 
> > > > 
> > > > Test with vulkan, please.
> > > 
> > > 
> > > ![Screenshot from 2021-08-30 15-34-03](https://user-images.githubusercontent.com/88550054/131311483-54fefc36-698c-4f72-aea1-ee8c9db30e8b.png)
> > > Vulkan on Linux is quite a mess
> > 
> > 
> > When you move do you see more artifacts?
> 
> Not small artifacts, but big artifacts. And sometimes there are large big shadows, especially in battles.

So RADV is affected as well on linux. Can you also test with AMDVLK?

**Comment by DocTdb** [comment]
Thanks to ameerj and to those who participated in this thread.

Closing since it's solved.

**Comment by TheRealRws** [comment]
Hello this issue is back on the steam deck in some aspect. Running flatpack 1039 with fire emblem 1.2.0 update.

Seems to be draw distance related? The lighting seems to go full dark when a certain distance from the player.

![Screenshot_3](https://user-images.githubusercontent.com/92763718/173198203-4d90eaf1-67e3-403e-ae86-778790711f97.png)

There is quite a sharp line no matter where you go.
![Screenshot_4](https://user-images.githubusercontent.com/92763718/173198283-585ebe8e-74b7-4788-840d-9d0f4b00fa85.png)

When moving the camera around it changes with it.
![Screenshot_5](https://user-images.githubusercontent.com/92763718/173198320-4eb597e2-3550-4231-a5a9-9dda70743404.png)
![Screenshot_6](https://user-images.githubusercontent.com/92763718/173198332-a15b750f-25c6-427a-9c23-56404a5b2554.png)

Im not 100% sure if its the same issue as previous but it looks quite similar. Present on both vulkan and openGL.
