### ISSUE TITLE
Skyward Sword HD Incorrect/Dark Lighting on Vulkan

### ISSUE THREAD

**Issue by mjd180** [yuzu-emu/yuzu#6914]
<img width="960" alt="opengl" src="https://user-images.githubusercontent.com/61510543/130363515-aae7b210-d8c6-4f3b-b4ba-534ec51e4eb3.png">
<img width="960" alt="vulkan" src="https://user-images.githubusercontent.com/61510543/130363516-fdfd7592-4b98-44fc-b013-5297df436240.png">

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7028006/yuzu_log.txt)

**Comment by G-Spawn** [comment]
as the create new issue states could you please post a log. Vulkan oddities with sshd are relatively known. Ogl renders it best for now.

**Comment by Moonlacer** [comment]
More context would also be appreciated

**Comment by german77** [comment]
Duplicate of #7133
