### ISSUE TITLE
Controller right vibration device error 

### ISSUE THREAD

**Issue by xinfs** [yuzu-emu/yuzu#6915]
![2864f9b043bb1337](https://user-images.githubusercontent.com/89407398/130485201-456e262c-5268-4780-8535-6fb11058c2b9.png)
![-68fe56914b88605d](https://user-images.githubusercontent.com/89407398/130485211-ee3b0d99-173b-48c9-b9c5-2deda77bb581.png)
![1fa97c28089d1683](https://user-images.githubusercontent.com/89407398/130485220-6e6ed34d-dc86-43ba-8c30-f6becaae2427.png)
![-77d0a20f47bc3c00](https://user-images.githubusercontent.com/89407398/130485223-2bddcd0f-d97f-48ef-94a5-3eae17b841eb.png)
Controller right vibration device error.My pro controller has the same problem as my xbox controller.

**Comment by v1993** [comment]
Can you elaborate what the issue is aside from what you see in config files?

**Comment by german77** [comment]
Is vibration missing on a specific controller type? when a single controller is mapped only one rumble device is linked since that's technically correct. If you for example use a real dual joycon you will have 2 devices mapped to vibration

**Comment by xinfs** [comment]
> 除了您在配置文件中看到的内容之外，您能否详细说明问题所在？

During the game,my right vibration device didn't work.It's strange,everything was fine before yesterday.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7033651/yuzu_log.txt)

**Comment by xinfs** [comment]
> 特定控制器类型是否缺少振动？当一个控制器被映射时，只有一个隆隆声设备被链接，因为这在技术上是正确的。例如，如果您使用真正的双操纵杆，您将有 2 个设备映射到振动



> 特定控制器类型是否缺少振动？当一个控制器被映射时，只有一个隆隆声设备被链接，因为这在技术上是正确的。例如，如果您使用真正的双操纵杆，您将有 2 个设备映射到振动

I chose the pro controller,so both vibration devices should work,and right now only the left vibration device works.

**Comment by xinfs** [comment]
I thoughtI had a hardware problem with my controller,but apparently after choosing Right JoyCon,the right vibration device is recognized,so it's not a hardware problem.

**Comment by xinfs** [comment]
> Is vibration missing on a specific controller type? when a single controller is mapped only one rumble device is linked since that's technically correct. If you for example use a real dual joycon you will have 2 devices mapped to vibration

I chose the pro controller,so both vibration devices should work,and right now only the left vibration device works.

**Comment by german77** [comment]
I will take a look on that game. Thanks for reporting

**Comment by xinfs** [comment]
> Can you elaborate what the issue is aside from what you see in config files?

During the game,my right vibration device didn't work.It's strange,everything was fine before yesterday.
[Uploading yuzu_log.txt…]()

**Comment by xinfs** [comment]
p

> Can you elaborate what the issue is aside from what you see in config files?

During the game,my right vibration device didn't work.It's strange,everything was fine before yesterday.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7033717/yuzu_log.txt)

**Comment by german77** [comment]
This game only supports dual joycon and handheld. It also sends vibrations specifically to one controller but not the other. Some internal changes had to be made for your controller to work properly. In the mean time you can copy the controller string on both vibration devices.
