### ISSUE TITLE
D-Pad is drawn incorrectly in controller settings

### ISSUE THREAD

**Issue by v1993** [yuzu-emu/yuzu#6916]
I remember this being an issue at some earlier point in time:

![Screenshot_20210824_010758](https://user-images.githubusercontent.com/16255906/130525735-5d522e86-1921-4cf0-bc2d-3f274d67bd62.png)

Probably (not tested) caused by #6890 by me, will have to check.

**Comment by german77** [comment]
Is a compiler optimization error

**Comment by v1993** [comment]
Yeah, I remember that (is it actually a wrong optimization or UB uncovered by it?). Also, nope, it's not caused by linked PR.

**Comment by v1993** [comment]
Might be caused by more aggressive optimization settings and/or GCC 11.

**Comment by v1993** [comment]
Can't reproduce this anymore - likely related to fixes in GCC 12. Closing.
