### ISSUE TITLE
[BUG] Network test is failing

### ISSUE THREAD

**Issue by Gusted** [yuzu-emu/yuzu#6918]
Hi, I've decided to give yuzu a try again after having some fun on it on a Pop_OS! machine by which I was using pre-compiled AppImages. I'm currently on a arch system and using the `yuzu-git` package from the AUR which let me customize some compile settings like LTO. 

The compiling goes all good except for a few normal warnings etc. However the tests seems to be failing:

It's coming from the network.cpp test it seems. And simply says It's being aborted by a `SIGABRT` signal and thus let the test fail.

```
-> % ctest --rerun-failed --output-on-failure
Test project /home/gusted/.cache/yay/yuzu-git/src/yuzu/build
    Start 1: tests
1/1 Test #1: tests ............................Subprocess aborted***Exception:   0.22 sec

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests is a Catch v2.13.6 host application.
Run with -? for options

-------------------------------------------------------------------------------
Network::Errors
-------------------------------------------------------------------------------
/home/gusted/.cache/yay/yuzu-git/src/yuzu/src/tests/core/network/network.cpp:10
...............................................................................

/home/gusted/.cache/yay/yuzu-git/src/yuzu/src/tests/core/network/network.cpp:10: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases:  31 |  30 passed | 1 failed
assertions: 200 | 199 passed | 1 failed



0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.22 sec

The following tests FAILED:
          1 - tests (Subprocess aborted)
Errors while running CTest
```
I've tried debugging it with gdb, but I wasn't able to find why SIGABRT was being called. Only that this `connect()` function is failing and errors a error code 111(which is passed to get a humanized string).

https://github.com/yuzu-emu/yuzu/blob/bed0c3c92a6db45b29e787016fd21542606a031a/src/tests/core/network/network.cpp#L24

**Comment by Gusted** [comment]
Here is a backtrace of running gdb while the ./bin/tests is compiled with debug symbols.
[gdb.log](https://github.com/yuzu-emu/yuzu/files/7046066/gdb.log)

**Comment by v1993** [comment]
Further debugging leads to crash here:

https://github.com/yuzu-emu/yuzu/blob/bed0c3c92a6db45b29e787016fd21542606a031a/src/common/logging/backend.cpp#L163-L165

Which happens because some module tries to use logging, but logging singleton is not set up in testing program.

**Comment by v1993** [comment]
With PR #6917 applied, tests no longer abort. This, however, is rather odd, given that it just replaces abort statement in question with throw.

**Comment by Gusted** [comment]
> With PR #6917 applied, tests no longer abort. This, however, is rather odd, given that it just replaces abort statement in question with throw.

Repeating myself from discord:

Ah I think I found why it's not failing. That PR toggles initialization_in_progress_suppress_logging to true which is used in the FmtLogMessageImpl function which is the one calling Impl::Instance() https://github.com/yuzu-emu/yuzu/blob/4654fb96b0e2eb1b57857ae7f0438341fb2f9292/src/common/logging/backend.cpp#L299-L306

Which is confirmed by @v1993 to works as intended.
