### ISSUE TITLE
[regression][linux][intel] broken graphics in multiple games

### ISSUE THREAD

**Issue by A-w-x** [yuzu-emu/yuzu#6930]
archLinux, mesa git, i7-1165g7

this issue affects both glsl and spir-v

mystery dungeon dx example

![Screenshot_2021-08-27_12-40-05](https://user-images.githubusercontent.com/80461138/131102508-4ac22752-9aa8-4f84-a692-fca0a6f4fd8c.jpg)
![Screenshot_2021-08-27_12-40-05(1)](https://user-images.githubusercontent.com/80461138/131102513-4429e873-04ee-4560-bc65-32c1e1cce3be.jpg)

in game UI is also broken like that

dungeon dx log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7065736/yuzu_log.txt)

mario odyssey example

![Screenshot_2021-08-27_13-08-12](https://user-images.githubusercontent.com/80461138/131103446-8ec49c01-fe0a-45f9-a541-5b543fd0a748.jpg)

could affect more games but i didnt test much

**Comment by A-w-x** [comment]
anv (mesa git) is not affected

**Comment by FernandoS27** [comment]
if it's specific to Xe. It's likely a driver issue.

**Comment by A-w-x** [comment]
can you confirm this?
i will open a mesa issue
