### ISSUE TITLE
Skyward Sword HD OpenGL Issue

### ISSUE THREAD

**Issue by Kimex123** [yuzu-emu/yuzu#6940]
When using OpenGL part of the desert don't render.

OpenGL 
![Screenshot (130)](https://user-images.githubusercontent.com/89701010/131224374-1e2dcbd7-c41a-4de4-9596-d881c230695e.png)
Vulkan
![Screenshot (131)](https://user-images.githubusercontent.com/89701010/131224376-24b8c030-83b5-4da7-bfe1-7c3d7acfeb1a.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7071025/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
Please disable async shader building

**Comment by Kimex123** [comment]
That fixed it, thank you
