### ISSUE TITLE
Yokai Watch 1 Switch Remake Full Speed But Graphical Bugs

### ISSUE THREAD

**Issue by AstroQuote** [yuzu-emu/yuzu#6942]
Yokai Watch 1 runs at full speed on both OpenGL and Vulcan. But it is stretched and upside down on Vulcan, and blurry with fully black characters on OpenGL. It is not blurry in menus though.

![Screenshot 2021-08-28 234413](https://user-images.githubusercontent.com/75824998/131241315-010eaeb6-ac99-4cb9-9f4e-38771a640dfb.png)
![Screenshot 2021-08-28 233905](https://user-images.githubusercontent.com/75824998/131241318-378ca79d-2735-43d3-a51b-b7f171fb4b49.png)

Opengl Logs

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7072043/yuzu_log.txt)

Vulcan Logs
[yuzu_log(1).txt](https://github.com/yuzu-emu/yuzu/files/7072045/yuzu_log.1.txt)

**Comment by MysticExile** [comment]
Superseded by #9053

**Comment by G-Spawn** [comment]
Reopening it as the aforementioned post by Mystic had to be closed.

**Comment by metcalsr28** [comment]
Can confirm last post is still accurate on both Nvidia and AMD.
