### ISSUE TITLE
AoC: 100% CPU usage during part of first cutscene

### ISSUE THREAD

**Issue by DiegoMadGlez** [yuzu-emu/yuzu#6947]
Yuzu Mainline 734
Not a regressions since it also happens in Mainline 600,699,700

Running the first cutscene of AOC starts perfect with 20-50% utilization of cpu 
![image](https://user-images.githubusercontent.com/75719050/131536946-d3dd6224-d386-4ccc-a0ed-aa464c4c19c4.png)
then when you hit the part of the king talking cpu utilization goes to 100% and game starts to die, going from 0-15fps all times with major stutters and audio desync 
![image](https://user-images.githubusercontent.com/75719050/131538055-e7a110f3-0f63-4af6-a7f5-c48454294fcf.png)
When moblins show up things go back to normal, cpu utilization 30% and 30fps
![image](https://user-images.githubusercontent.com/75719050/131537144-4e156b90-a90f-4848-ae9d-a28e9438c1c3.png)
Game runs perfect its just that part. 
CPU: i5 6500
GPU: GTX 1060 6gb 
OS: Windows 10
RAM: 16GB 2400mhz

LOG: 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7085344/yuzu_log.txt)

**Comment by DiegoMadGlez** [comment]
There is more people with this problem and with other games

**Comment by FernandoS27** [comment]
uhm it's likely an issue on ffmpeg library. In EA there's GPU decoding, likely it could help with your CPU

**Comment by v1993** [comment]
Build with PR #6846 doesn't seem to help either, so doesn't looks like ffmpeg CPU decoder issue. I suspect that game tries to load stuff in background during cutscene, leading to slowdown.

**Comment by TheAllMaker** [comment]
I also had the same issue. Cutscenes were fine but sometimes they extremly started to stutter and audio also desynced.
CPU: Ryzen 5600X
GPU: RX 5700 8gb
OS: Windows 10
RAM: 16GB 3000mhz

**Comment by maverick-hunter** [comment]
I've got an older machine (i5 4690, GTX 950, 12gb ram) and the first cutscene runs mostly fine, but as soon as King Rhoam speech begins it lags real bad. First map has drops, but is playable.

**Comment by EgoBizarro** [comment]
This is MUCH better in Early Access 2667, so I guess it happens on systems with low thread count or generally older CPUs.

**Comment by DiegoMadGlez** [comment]
#8172 Fixes this issue

**Comment by G-Spawn** [comment]
> #8172 Fixes this issue

^
