### ISSUE TITLE
Audio is broken on ACNH (bugging)

### ISSUE THREAD

**Issue by SeaKestrel** [yuzu-emu/yuzu#6949]
I'm using this version of yuzu : _yuzu Development Build | HEAD-mainline-636-6905-gb6905b16c-dirty_

To reproduce, simply play to ACNH 

The problem is that the audio is bugging, like when a game freeze (the screen stop moving for ms at repeating times but for audio). The error I got is **Audio <Error> audio_core/splitter_context.cpp:RecomposeDestination:385: Invalid splitter info size! size=0**

Here it is my pc specs :
[   3.576316] Frontend <Info> yuzu/main.cpp:GMainWindow:244: Host CPU: Intel(R) Pentium(R) Gold G6400 CPU @ 4.00GHz
[   3.576333] Frontend <Info> yuzu/main.cpp:GMainWindow:246: Host OS: Ubuntu 21.04
[   3.576342] Frontend <Info> yuzu/main.cpp:GMainWindow:247: Host RAM: 15.27 GB
[   3.576344] Frontend <Info> yuzu/main.cpp:GMainWindow:249: Host Swap: 14.90 GB

and the log file piece :

[ 908.003726] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.003873] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.004018] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.004133] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.004240] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.004358] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.004477] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.004919] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.005230] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.005365] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.005526] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.005670] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.007185] Audio <Error> audio_core/splitter_context.cpp:RecomposeDestination:385: Invalid splitter info size! size=0
[ 908.007190] Audio <Error> audio_core/splitter_context.cpp:RecomposeDestination:385: Invalid splitter info size! size=0
[ 908.008242] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.008380] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.008588] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.008710] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.010948] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.015025] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.015142] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[ 908.015259] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called

**Comment by BSoDGamingYT** [comment]
Please use a mainline or early access build. we do not allow issue opening on custom builds. Please also provide a log file as per the issue format request

**Comment by SeaKestrel** [comment]
> Please use a mainline or early access build. we do not allow issue opening on custom builds. Please also provide a log file as per the issue format request

i'd like to send you the log but it was 34 Mo...

**Comment by SeaKestrel** [comment]
[yuzu_log.txt.old.zip](https://github.com/yuzu-emu/yuzu/files/7096948/yuzu_log.txt.old.zip)

**Comment by FernandoS27** [comment]
hmn it seems people get bad sound depending on their audio setup. Which setup you got?

**Comment by SeaKestrel** [comment]
I have this in my settings
![Capture d’écran du 2021-09-05 16-47-59](https://user-images.githubusercontent.com/78849811/132131112-4ba305ad-d062-4607-ba20-1b0910be13f6.png)

**Comment by javierchip** [comment]
any solutions this far?

**Comment by SeaKestrel** [comment]
Yes, the sound isn't bugging anymore
