### ISSUE TITLE
[Iris Xe][Mesa][ANV][Vulkan] Donkey Kong Country : Tropical Freeze rendering issues 

### ISSUE THREAD

**Issue by pacoa-kdbg** [yuzu-emu/yuzu#6955]
Game : Donkey Kong Country : Tropical Freeze (base)
Yuzu Version : EA 2031
CPU : i7 1165G7
RAM : 16GB
GPU : Iris Xe
GPU Driver : Mesa 21.2.1
OS: Debian 11
Kernel : 5.13.13-xanmod1

Issue : 
![Screenshot from 2021-09-02 21-52-32](https://user-images.githubusercontent.com/29181120/131943496-5fc9c361-f7bb-4fd1-b614-0bcab4bfe311.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7103032/yuzu_log.txt)

**Comment by FernandoS27** [comment]
seems native ASTC are f*** up in ANV.

**Comment by pacoa-kdbg** [comment]
Same issue still present on

Yuzu Version : 834
CPU : i7 1165G7
RAM : 16GB
GPU : Iris Xe
GPU Driver : Mesa 21.2.6
OS: Debian 11
Kernel : 5.15.6-xanmod1

**Comment by pacoa-kdbg** [comment]
Issue no longer present
Yuzu 980
Mesa driver 21.3.5
OS : Pop OS
Kernel 5.16
