### ISSUE TITLE
Shadow Issue BOTW OpenGL  Spir-V

### ISSUE THREAD

**Issue by Nizz05** [yuzu-emu/yuzu#6960]
GPU: RTX 2080
Driver: 471.68
CPU: i7 8700k
Windows 10
Early Access 2031

![image](https://user-images.githubusercontent.com/85291391/131968965-0e5380d8-f1c5-47ba-8d5b-e40acacc4acf.png)

**Comment by BSoDGamingYT** [comment]
SPIR-V OGL is not meant to be used on Windows, The GUI itself states that it is for Linux MESA only.
