### ISSUE TITLE
Roof Rage crashes out just before the intro

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#6967]
using both EA and mainline
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7109151/yuzu_log.txt)

**Comment by v1993** [comment]
Your last screenshot is not related to this problem. Those are a normal part of yuzu's fastmem. Disable catching those (or use debug CPU setting and turn fastmem off) if you want to find actual problem.

**Comment by benderscruffy** [comment]
ok thanks for that

**Comment by benderscruffy** [comment]
how do i turn off fastmem
i cannot see it in any of the debug settings ???

**Comment by benderscruffy** [comment]
in the ini do i change any of these
cpuopt_unsafe_fastmem_check\default=true
cpuopt_unsafe_fastmem_check=true
cpuopt_fastmem\default=false
cpuopt_fastmem=false

**Comment by benderscruffy** [comment]
goes ingame now no problems
