### ISSUE TITLE
can't find the Raduce fish

### ISSUE THREAD

**Issue by hamoude** [yuzu-emu/yuzu#6970]
still no solution for this bug, for the problem on yuzu and ryujinx.
Is there someone who can save me until this stage?
because the door cannot be opened without the key fish.
excuse for english i translate thanks to google
a safe guard after opening the door that's all?
I am stuck...!!!
thank you

Game :Super Smash Bros Ultimate (base)
Yuzu Version : EA 2032
CPU : Core(TM) i7-3770
RAM : 16GB

<a href="https://www.up-00.com/ba4t6h7trpv3" target=_blank>Untitled_Project.mp4 - 13.1 MB</a>

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7110661/yuzu_log.txt)

**Comment by german77** [comment]
This is not a support forum. We also don't provide support to unofficial yuzu applications. This part works perfectly on mainline.
