### ISSUE TITLE
[Feature Request]How to disable controller applet?

### ISSUE THREAD

**Issue by eshion** [yuzu-emu/yuzu#6982]
the applet keeps popping up with "ok" grayed out. I already setup the controller settings, why is it having this pop up? Even though I already set up the controller, it's not working in game.is there a way to disable controller applet? 

![image](https://user-images.githubusercontent.com/1287467/132304833-4631b77d-1fc4-4174-ba35-90c360393420.png)

**Comment by Moonlacer** [comment]
Are you sure the "OK" is grayed out in that picture? It looks like you could just click "OK" and continue, but that could just be the contrast on my screen being awful

**Comment by Schplee** [comment]
This appears to be a local issue versus and issue with the emulator. The bug tracker isn't for support requests. Please reach out to use in Discord for further support: https://discord.gg/u77vRWY

If our team determines it's a valid bug, we will submit an issue or instruct you to create a new issue with the appropriate information.
