### ISSUE TITLE
Yuzu wont start/boot

### ISSUE THREAD

**Issue by HeyImFika** [yuzu-emu/yuzu#6991]
I installed Yuzu yesterday and it worked i set it up and i started super mario odyssey but it wouldnt start so i went and searched on the internet and found that it couldnt run because of my older gpu software so I updated it. After updating i launche Yuzu but it shuts down on its own it goes to the yuzu installer and it closes on its own.

**Comment by german77** [comment]
This is a issue tracker for developers. we don't give support here. Please ask us on discord
