### ISSUE TITLE
Pokemon sword Getting Stuck at 0 fps

### ISSUE THREAD

**Issue by AirShadow12** [yuzu-emu/yuzu#6994]
Hello, Im trying to play pokemon sword but its getting stuck at a certain point like inside the first house where you start , im getting around 25-30 fps and when it showed outside the house for few seconds it was running at 20-25 fps but the problem occurs when i try to go outside of the house , when i go outside it loads for 5-10 seconds then gets stuck with 0 fps and i have to end task yuzu with the task manager because the whole app gets stuck. As for my specs i dont think thats the issue because i have seen other guys playing on same specs as mine like intel hd 520 an intel processor with 2 cores 4 thread(mine i3 6th gen, the guy i saw the game play of had i5 6200) and 8 Gigs of ram. Already tried with supports on discord and forum and the mods said to post the issue here. Thank you.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7145815/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Disable Async Shaders.

**Comment by AirShadow12** [comment]
> Disable Async Shaders.

Already tried

**Comment by AirShadow12** [comment]
> Disable Async Shaders.

![Uploading IMG_20210911_131330.jpg…]()

**Comment by ChrisM20** [comment]
> Disable Async Shaders.

You already put in imprecise cpu as it might not have FMA

**Comment by AirShadow12** [comment]
> > Disable Async Shaders.
> 
> You already put in imprecise cpu as it might not have FMA

Sorry not able to understand what you are saying

**Comment by ChrisM20** [comment]
> > > Disable Async Shaders.
> > 
> > 
> > You already put in imprecise cpu as it might not have FMA
> 
> Sorry not able to understand what you are saying

Try to go to configuration, cpu, and in the only option that is there in automatic, change it to imprecise

**Comment by AirShadow12** [comment]
> > > > Disable Async Shaders.
> > > 
> > > 
> > > You already put in imprecise cpu as it might not have FMA
> > 
> > 
> > Sorry not able to understand what you are saying
> 
> Try to go to configuration, cpu, and in the only option that is there in automatic, change it to imprecise

There is no imprecise option, there is auto, accurate and unsafe

**Comment by ChrisM20** [comment]
So unsafe is the option, I have it in Spanish and it appears as imprecise, if you don't change the game with that option, I don't know what it might be

**Comment by AirShadow12** [comment]
> So unsafe is the option, I have it in Spanish and it appears as imprecise, if you don't change the game with that option, I don't know what it might be

Yep unsafe was imprecise,. and I don't think this game will work with vulkan on my pc open gl runs but with too many graphical glitches, I have tried every possible solution and still didn't work so yeah thanks for helping.

**Comment by AirShadow12** [comment]
> So unsafe is the option, I have it in Spanish and it appears as imprecise, if you don't change the game with that option, I don't know what it might be

It's like my whole pc gets stuck and I have to force close it by pressing power off button for few seconds

**Comment by FernandoS27** [comment]
could you provide a save just before the issue

**Comment by AirShadow12** [comment]
> could you provide a save just before the issue

Sorry I deleted the game..  is it related to solution?

**Comment by AirShadow12** [comment]
> could you provide a save just before the issue

If it's a solution you are thinking of , can you tell which type of solution it is because I have tried many solution , and if yours is the same then my internet will be wasted...

**Comment by FernandoS27** [comment]
I was going to debug the game as I'm a developer but it seems my time is being wasted....

**Comment by AirShadow12** [comment]
> I was going to debug the game as I'm a developer but it seems my time is being wasted....

Oh sorry didn't knew you were a dev, I will download the game as soon as possible and then save at the point before going outside

**Comment by AirShadow12** [comment]
> I was going to debug the game as I'm a developer but it seems my time is being wasted....

Downloading it......

**Comment by AirShadow12** [comment]
> I was going to debug the game as I'm a developer but it seems my time is being wasted....

Log- [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7176293/yuzu_log.txt)
Save- 
[main.zip](https://github.com/yuzu-emu/yuzu/files/7176307/main.zip) Uploaded it in zip format as save game's format was unsupported. I saved it right before getting outside , this time the game didn't got stuck at loading but after loading it got stuck on a black screen then the emulator was not responding after few secs, Thanks for looking into this.

**Comment by AirShadow12** [comment]
> I was going to debug the game as I'm a developer but it seems my time is being wasted....

Got any clue why is this happening?

**Comment by gidoly** [comment]
this is duplicate sw sh multocpre issue thread
