### ISSUE TITLE
Crashing immediately before starting game

### ISSUE THREAD

**Issue by realNZZN** [yuzu-emu/yuzu#6995]
(Yuzu 745 on Windows 11 21H2 / Ryzen 2300X / RX 570 8GB)

Starting any game through the yuzu frontend causes a sudden crash, no loading screen or any change after starting the game, just a crash right after clicking.

Directly pasted log:
> [   0.374397] Input <Info> input_common\gcadapter\gc_adapter.cpp:Adapter:21: GC Adapter Initialization started
[   1.376764] Input <Info> input_common\udp\client.cpp:Client:164: Udp Initialization started
[   1.376781] Input <Info> input_common\udp\client.cpp:StartCommunication:309: Starting communication with UDP input server on 127.0.0.1:26760
[   1.401865] Frontend <Info> yuzu\main.cpp:GMainWindow:230: yuzu Version: yuzu 745
[   1.401872] Frontend <Info> yuzu\main.cpp:GMainWindow:245: Host CPU: AMD Ryzen 3 2300X Quad-Core Processor           | AVX2 | FMA
[   1.401921] Frontend <Info> yuzu\main.cpp:GMainWindow:247: Host OS: Windows 10 (10.0)
[   1.401934] Frontend <Info> yuzu\main.cpp:GMainWindow:249: Host RAM: 15.94 GB
[   1.401935] Frontend <Info> yuzu\main.cpp:GMainWindow:251: Host Swap: 7.74 GB
[   1.999050] Loader <Warning> core\loader\loader.cpp:GetLoader:264: File Splatoon2.nsp has a different type than its extension.
[   2.086567] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:437:     RomFS: Update (v0.48.0) applied successfully
[   2.093867] Loader <Warning> core\loader\loader.cpp:GetLoader:264: File Splatoon2.nsp has a different type than its extension.
[   2.141908] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:437:     RomFS: Update (v0.48.0) applied successfully
[ 116.448032] Config <Info> common\settings.cpp:LogSettings:41: yuzu Configuration:
[ 116.448042] Config <Info> common\settings.cpp:operator ():34: Controls_UseDockedMode: false
[ 116.448043] Config <Info> common\settings.cpp:operator ():34: System_RngSeed: 0
[ 116.448044] Config <Info> common\settings.cpp:operator ():34: System_CurrentUser: 0
[ 116.448045] Config <Info> common\settings.cpp:operator ():34: System_LanguageIndex: 1
[ 116.448046] Config <Info> common\settings.cpp:operator ():34: System_RegionIndex: 2
[ 116.448046] Config <Info> common\settings.cpp:operator ():34: System_TimeZoneIndex: 0
[ 116.448047] Config <Info> common\settings.cpp:operator ():34: Core_UseMultiCore: true
[ 116.448048] Config <Info> common\settings.cpp:operator ():34: CPU_Accuracy: 2
[ 116.448049] Config <Info> common\settings.cpp:operator ():34: Renderer_UseResolutionFactor: 1
[ 116.448050] Config <Info> common\settings.cpp:operator ():34: Renderer_UseSpeedLimit: true
[ 116.448051] Config <Info> common\settings.cpp:operator ():34: Renderer_SpeedLimit: 100
[ 116.448052] Config <Info> common\settings.cpp:operator ():34: Renderer_UseDiskShaderCache: true
[ 116.448053] Config <Info> common\settings.cpp:operator ():34: Renderer_GPUAccuracyLevel: 0
[ 116.448053] Config <Info> common\settings.cpp:operator ():34: Renderer_UseAsynchronousGpuEmulation: true
[ 116.448054] Config <Info> common\settings.cpp:operator ():34: Renderer_UseNvdecEmulation: true
[ 116.448055] Config <Info> common\settings.cpp:operator ():34: Renderer_AccelerateASTC: true
[ 116.448055] Config <Info> common\settings.cpp:operator ():34: Renderer_UseVsync: true
[ 116.448056] Config <Info> common\settings.cpp:operator ():34: Renderer_ShaderBackend: 0
[ 116.448057] Config <Info> common\settings.cpp:operator ():34: Renderer_UseAsynchronousShaders: true
[ 116.448057] Config <Info> common\settings.cpp:operator ():34: Renderer_AnisotropicFilteringLevel: 0
[ 116.448058] Config <Info> common\settings.cpp:operator ():34: Audio_OutputEngine: cubeb
[ 116.448058] Config <Info> common\settings.cpp:operator ():34: Audio_EnableAudioStretching: true
[ 116.448060] Config <Info> common\settings.cpp:operator ():34: Audio_OutputDevice: auto
[ 116.448061] Config <Info> common\settings.cpp:operator ():34: DataStorage_UseVirtualSd: true
[ 116.448064] Config <Info> common\settings.cpp:operator ():38: DataStorage_CacheDir: C:\Users\NZZN_\AppData\Roaming\yuzu\cache
[ 116.448066] Config <Info> common\settings.cpp:operator ():38: DataStorage_ConfigDir: C:\Users\NZZN_\AppData\Roaming\yuzu\config
[ 116.448067] Config <Info> common\settings.cpp:operator ():38: DataStorage_LoadDir: C:\Users\NZZN_\AppData\Roaming/yuzu/load/
[ 116.448070] Config <Info> common\settings.cpp:operator ():38: DataStorage_NANDDir: C:\Users\NZZN_\AppData\Roaming/yuzu/nand/
[ 116.448071] Config <Info> common\settings.cpp:operator ():38: DataStorage_SDMCDir: C:\Users\NZZN_\AppData\Roaming/yuzu/sdmc/
[ 116.448071] Config <Info> common\settings.cpp:operator ():34: Debugging_ProgramArgs: 
[ 116.448072] Config <Info> common\settings.cpp:operator ():34: Services_BCATBackend: none
[ 116.448073] Config <Info> common\settings.cpp:operator ():34: Services_BCATBoxcatLocal: false
[ 123.472564] Frontend <Info> yuzu\main.cpp:BootGame:1307: yuzu starting...
[ 123.474748] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:437:     RomFS: Update (v0.48.0) applied successfully
[ 123.481137] Config <Info> common\settings.cpp:LogSettings:41: yuzu Configuration:
[ 123.481148] Config <Info> common\settings.cpp:operator ():34: Controls_UseDockedMode: false
[ 123.481148] Config <Info> common\settings.cpp:operator ():34: System_RngSeed: 0
[ 123.481150] Config <Info> common\settings.cpp:operator ():34: System_CurrentUser: 0
[ 123.481152] Config <Info> common\settings.cpp:operator ():34: System_LanguageIndex: 1
[ 123.481153] Config <Info> common\settings.cpp:operator ():34: System_RegionIndex: 2
[ 123.481154] Config <Info> common\settings.cpp:operator ():34: System_TimeZoneIndex: 0
[ 123.481154] Config <Info> common\settings.cpp:operator ():34: Core_UseMultiCore: true
[ 123.481155] Config <Info> common\settings.cpp:operator ():34: CPU_Accuracy: 2
[ 123.481156] Config <Info> common\settings.cpp:operator ():34: Renderer_UseResolutionFactor: 1
[ 123.481156] Config <Info> common\settings.cpp:operator ():34: Renderer_UseSpeedLimit: true
[ 123.481157] Config <Info> common\settings.cpp:operator ():34: Renderer_SpeedLimit: 100
[ 123.481158] Config <Info> common\settings.cpp:operator ():34: Renderer_UseDiskShaderCache: true
[ 123.481159] Config <Info> common\settings.cpp:operator ():34: Renderer_GPUAccuracyLevel: 0
[ 123.481159] Config <Info> common\settings.cpp:operator ():34: Renderer_UseAsynchronousGpuEmulation: true
[ 123.481160] Config <Info> common\settings.cpp:operator ():34: Renderer_UseNvdecEmulation: true
[ 123.481160] Config <Info> common\settings.cpp:operator ():34: Renderer_AccelerateASTC: true
[ 123.481161] Config <Info> common\settings.cpp:operator ():34: Renderer_UseVsync: true
[ 123.481162] Config <Info> common\settings.cpp:operator ():34: Renderer_ShaderBackend: 0
[ 123.481163] Config <Info> common\settings.cpp:operator ():34: Renderer_UseAsynchronousShaders: true
[ 123.481164] Config <Info> common\settings.cpp:operator ():34: Renderer_AnisotropicFilteringLevel: 0
[ 123.481165] Config <Info> common\settings.cpp:operator ():34: Audio_OutputEngine: cubeb
[ 123.481165] Config <Info> common\settings.cpp:operator ():34: Audio_EnableAudioStretching: true
[ 123.481166] Config <Info> common\settings.cpp:operator ():34: Audio_OutputDevice: auto
[ 123.481167] Config <Info> common\settings.cpp:operator ():34: DataStorage_UseVirtualSd: true
[ 123.481168] Config <Info> common\settings.cpp:operator ():38: DataStorage_CacheDir: C:\Users\NZZN_\AppData\Roaming\yuzu\cache
[ 123.481170] Config <Info> common\settings.cpp:operator ():38: DataStorage_ConfigDir: C:\Users\NZZN_\AppData\Roaming\yuzu\config
[ 123.481171] Config <Info> common\settings.cpp:operator ():38: DataStorage_LoadDir: C:\Users\NZZN_\AppData\Roaming/yuzu/load/
[ 123.481172] Config <Info> common\settings.cpp:operator ():38: DataStorage_NANDDir: C:\Users\NZZN_\AppData\Roaming/yuzu/nand/
[ 123.481173] Config <Info> common\settings.cpp:operator ():38: DataStorage_SDMCDir: C:\Users\NZZN_\AppData\Roaming/yuzu/sdmc/
[ 123.481174] Config <Info> common\settings.cpp:operator ():34: Debugging_ProgramArgs: 
[ 123.481175] Config <Info> common\settings.cpp:operator ():34: Services_BCATBackend: none
[ 123.481176] Config <Info> common\settings.cpp:operator ():34: Services_BCATBoxcatLocal: false
[ 123.600731] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:437:     RomFS: Update (v0.48.0) applied successfully
[ 123.646406] Render.OpenGL <Info> video_core\renderer_opengl\gl_device.cpp:Device:188: Renderer_VariableAOFFI: false
[ 123.646414] Render.OpenGL <Info> video_core\renderer_opengl\gl_device.cpp:Device:189: Renderer_ComponentIndexingBug: true
[ 123.646415] Render.OpenGL <Info> video_core\renderer_opengl\gl_device.cpp:Device:190: Renderer_PreciseBug: false
[ 123.646416] Render.OpenGL <Info> video_core\renderer_opengl\gl_device.cpp:Device:192: Renderer_BrokenTextureViewFormats: true
[ 123.646417] Render.OpenGL <Warning> video_core\renderer_opengl\gl_device.cpp:Device:194: Asynchronous shader compilation enabled but not supported
[ 123.678729] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:AddTelemetryFields:284: GL_VERSION: 4.6.14761 Compatibility Profile Context 21.30.11.01 30.0.13011.1004
[ 123.678737] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:AddTelemetryFields:285: GL_VENDOR: ATI Technologies Inc.
[ 123.678739] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:AddTelemetryFields:286: GL_RENDERER: Radeon (TM) RX 570 Graphics
[ 123.711508] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontStandard' (0x0100000000000811).
[ 123.711876] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[ 123.712375] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[ 123.712871] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[ 123.713261] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontChineseSimple' (0x0100000000000814).
[ 123.713573] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[ 123.714222] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontChineseTraditional' (0x0100000000000813).
[ 123.714391] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[ 123.714776] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontKorean' (0x0100000000000812).
[ 123.714902] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[ 123.715290] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[ 123.715320] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[ 123.715591] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'FontNintendoExtension' (0x0100000000000810).
[ 123.715614] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[ 123.718115] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 123.718151] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[ 123.718656] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:76: Synthesizing system archive 'TimeZoneBinary' (0x010000000000080E).
[ 123.718696] Service.FS <Info> core\file_sys\system_archive\system_archive.cpp:SynthesizeSystemArchive:91:     - System archive generation successful!
[ 123.719670] Loader <Info> core\file_sys\patch_manager.cpp:Patc

**Comment by G-Spawn** [comment]
Ask on discord this isn't a support forum.
