### ISSUE TITLE
Yuzu FPS issue

### ISSUE THREAD

**Issue by Apocalypxe** [yuzu-emu/yuzu#7004]
HI i am apoclaypxe. I have been using yuzu from 3 months and today i encountered a issue we cant call it frame drop 
its like every 10 secs the game drops to 10 fps then after 10 secs back to 40-50 fps.  i have uploaded the logs please check and reply
fast.
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7153474/yuzu_log.txt.old.txt)

**Comment by FernandoS27** [comment]
hmn first eliminate the FPS hack, you no longer need it. B set speed limit 100. C. use discord for support, this is for tracking real issues that developers set.
