### ISSUE TITLE
Pokemon Sword and Shield LAN not working

### ISSUE THREAD

**Issue by PrinceBubloo** [yuzu-emu/yuzu#7008]
I tried using LAN on Pokemon Sword but it's not working,
I can't even press Y to open a local network window to trade or battle over LAN.
Raid Battles also don't work.
I know that devs are quite busy with LDN and Project Gaia, but if you guys can look into it, It would really mean alot.

**Comment by v1993** [comment]
Trading is not supported over LAN (only LDN). It's a game limitation.

**Comment by FernandoS27** [comment]
yes the game needs some LDN code to even work on LAN.

**Comment by PrinceBubloo** [comment]
Thanks for your reply sir.
Well that sucks,I was looking forward to playing with friends.
Any Idea when LDN will be implemented, What are the challenges you are currently facing in LDN implementation.

**Comment by FernandoS27** [comment]
a bit slow since the developer behind it lives in Australia must do home schooling for her daughter due to pandemic.

**Comment by PrinceBubloo** [comment]
Alright, thanks for everything sir. We'll wait.
