### ISSUE TITLE
Xenoblade Chronicles Definitive Edition random crashes using vulkan

### ISSUE THREAD

**Issue by Razziell** [yuzu-emu/yuzu#7016]
Vulkan has random crashes at different times.
yuzu Early Access 2062
Win 10 21H1
CPU Ryzen 2600
RAM 16 GB
GTX 760 2GB (NVIDIA 471.96)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7171947/yuzu_log.txt)
![Image 1](https://user-images.githubusercontent.com/7115882/133476840-f63f60c3-1a58-4f6d-8065-db97d21b9e7a.png)
![Image 2](https://user-images.githubusercontent.com/7115882/133476843-a52b42ac-c7e4-4dbd-9e30-7af32abbbc80.png)

And I use this shader - 
[lib_nx.zip](https://github.com/yuzu-emu/yuzu/files/7171994/lib_nx.zip)

**Comment by goldenx86** [comment]
Please confirm if OpenGL is stable. Kepler cards don't have the best Vulkan support.

**Comment by G-Spawn** [comment]
Please default anisotropic as well.

**Comment by Razziell** [comment]
> Please confirm if OpenGL is stable. Kepler cards don't have the best Vulkan support.
In opengl, performance is lower and in map mode it (map) behaves inadequately (background and icons move independently).

**Comment by Razziell** [comment]
OpenGL:![Image 4](https://user-images.githubusercontent.com/7115882/133479800-2d46213f-b5e5-41dd-9922-4f74e92303d9.png)
![Image 5](https://user-images.githubusercontent.com/7115882/133479806-c6630181-8d5e-4927-a2aa-3c2cbfea0f62.png)

**Comment by Zlva** [comment]
Nvidia 2GB cards have a lote of probs. whith yuzu. But you can put your VM memory start and end at last at 20GB. that might help once you have your shaders build

**Comment by v1993** [comment]
If you have fixed this issue, it would be very helpful to know what was the cause.

**Comment by Razziell** [comment]
I just resigned myself and use preservation more save

**Comment by Pozuelos78** [comment]
> I just resigned myself and use preservation more save


if you still have the Gtx 760 try the 466.77 driver,  is the best Nvidia driver for Kepler architecture cheers!

**Comment by humanana** [comment]
I have the same problem random crash on xenoblade with vulkan now going to test with opengl
build 1088 i5 6500 gf1060 6gb ram 32g
