### ISSUE TITLE
A Hat in Time splash screen does not render

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#7025]
The splash screen in A Hat in Time does not render, yuzu produces a black screen during it instead.

Expected outcome (captured via [SysDVR](https://github.com/exelix11/SysDVR/)):

https://user-images.githubusercontent.com/22451773/133538757-c90012ab-0e79-4f9c-9a0c-9ae000e3ed53.mp4

yuzu:

https://user-images.githubusercontent.com/22451773/133539445-2da466a1-5998-4bed-b6c3-3571227a8eef.mp4

[yuzu_log.txt.tar.gz](https://github.com/yuzu-emu/yuzu/files/7174502/yuzu_log.txt.tar.gz)

**Comment by benderscruffy** [comment]
@FearlessTobi 
renders now
can be closed
