### ISSUE TITLE
Visual Glitches in Ultra Age.

### ISSUE THREAD

**Issue by PrinceBubloo** [yuzu-emu/yuzu#7030]
Ground dosent render correctly, it often shows black ground instead of normal.
I hope that it makes sense.

**Comment by G-Spawn** [comment]
please provide a screenshot and a log.

**Comment by PrinceBubloo** [comment]
let me test with the latest EA 2066 first.
Fixed some shadows issue with the latest EA , hopefully, the problems I encountered are also fixed.
Ill update after the testing.
