### ISSUE TITLE
Splatoon2 (01003BC0000A0000) 5.4.0 LAN battle Freezen

### ISSUE THREAD

**Issue by JumpingY** [yuzu-emu/yuzu#7032]
The screen freezen when start LAN battle in 5.4.0 update .But there is no such problem in 1.0.0

![1](https://user-images.githubusercontent.com/54348327/133655337-7057c5c4-132f-4907-bb7f-e4c6ef55c561.png)

The log is here
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7179750/yuzu_log.zip)

**Comment by german77** [comment]
Fixed with #7018
