### ISSUE TITLE
Yuzu EA 2066: Yuzu crashing after showing initial screen , on Vulcan with GTX 1650

### ISSUE THREAD

**Issue by PrinceBubloo** [yuzu-emu/yuzu#7034]
Cruis N Blast working fine on my Vulcan GPU, apart from the visual glitch on select car screen.
on Nvidia Graphics card it's crashing after showing the initial screen, I have also tried with Auto Stub Enable.

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7180688/yuzu_log.txt.old.txt)

**Comment by FernandoS27** [comment]
seems there was a device loss.

**Comment by PrinceBubloo** [comment]
Deleting my pipeline shader cashe seems to have fixed this problem,
Maybe my shader file was corrupted which is strange.

**Comment by FernandoS27** [comment]
likely it was the case.

**Comment by PrinceBubloo** [comment]
Thank you SIr,
I will close the issue since it is resolved.
