### ISSUE TITLE
Unmapped reads when trying to go on splitscreen multiplayer on Minecraft

### ISSUE THREAD

**Issue by tree-png** [yuzu-emu/yuzu#7035]
As the title says, the Bedrock version of Minecraft on Switch works normally on singleplayer, but seems to crash/freeze when trying to add another player to the game.

log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7181201/yuzu_log.txt)

game normally:
![image](https://user-images.githubusercontent.com/85036471/133691713-5601c9f1-c0b5-4ee1-a56b-9c466bbed349.png)

game when trying to add another player (stuck on this screen):
![image](https://user-images.githubusercontent.com/85036471/133691756-a3265263-bec2-44f7-8a9e-8f0fa32a9dc9.png)

**Comment by gidoly** [comment]
Closes due repirted to be resolved
