### ISSUE TITLE
WarioWare Get It Together! Not loading

### ISSUE THREAD

**Issue by SilverCalamity** [yuzu-emu/yuzu#7037]
My WarioWare Get It Together! is not loading after some seconds, what should I do?
![Screenshot (18)](https://user-images.githubusercontent.com/90917826/133801687-d327eba3-3836-44dc-936a-d33669eff592.png)

**Settings:**
Yuzu 752
Vulkan 
Gpu Normal
Dock
Cpu Auto

**System Specs:**
Windows 10
8 GB Ram
Geforce GTX 760
Intel i5-2500 3.30 GHz

**Comment by v1993** [comment]
Please use yuzu's discord for support requests. This is a bug tracker, not a support forum.

**Comment by SilverCalamity** [comment]
Ok

**Comment by OZtistic** [comment]
This issue can be closed

**Comment by german77** [comment]
Feel free to re open with a proper log
