### ISSUE TITLE
Yu-Gi-Oh Legacy of the duelist Link Evolution - Regressions

### ISSUE THREAD

**Issue by MYSTERlOUSGUY** [yuzu-emu/yuzu#7038]
I was told on Discord to report my finding here.

This game was fully playable on yuzu 488 (only minor graphical bugs).

Starting from yuzu 491 and Texture Cache Rewrite - all card textures are messed up (Both OpenGL and Vulkan), but game is stable and doesnt crash.

Starting from Yuzu 700 (Project Hades) - on Vulkan only  - game is booting then shortly after Konami logo it drops to 0 FPS and freezes. making it fully unplayable. OpenGL is fine. (still messed up card textures).

My GPU is AMD RADEON RX 560.
Sending log fine up to the moment when it froze.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7187228/yuzu_log.txt)

**Comment by Anuskuss** [comment]
> all card textures are messed up (Both OpenGL and Vulkan)

[Same on Intel](https://github.com/yuzu-emu/yuzu/issues/3146#issuecomment-890649765).

**Comment by Anuskuss** [comment]
Fixed.

**Comment by AnimeHeaven** [comment]
> Fixed.

No I have still the issue :(
