### ISSUE TITLE
mario sports games same graphics glitch

### ISSUE THREAD

**Issue by Danqwerty11** [yuzu-emu/yuzu#7041]
odyssey, party, and smash are working well only these have these glitches, the olympic one is not that bad
the cutscenes and 2d things are ok for all of them
rx 590, ryzen 5 1600x
I tried changing the settings and I saw on the tennis one yuzu page a screenshot of the same exact glitch saying is fixed with mods but there's just one for the resolution 

![yuzu_gwZDkfy9kU](https://user-images.githubusercontent.com/90934642/133849493-f072f66f-43eb-457f-8192-9179d60a7f1f.png)
![yuzu_VtfJgcCaxP](https://user-images.githubusercontent.com/90934642/133849512-5f1b3a35-20d0-4c69-8376-0d88b41e828e.png)
![yuzu_1kx5zZbq3c](https://user-images.githubusercontent.com/90934642/133849520-f357d357-50b6-4ff5-99a5-8dc4be39515f.jpg)

**Comment by german77** [comment]
Provide a log file please. https://yuzu-emu.org/help/reference/log-files/

**Comment by Danqwerty11** [comment]
@german7
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7188398/yuzu_log.txt)
7

**Comment by G-Spawn** [comment]
They won't support you here with piracy.
