### ISSUE TITLE
No More Heroes 3 Depth of Field Not Scaling With Resolution

### ISSUE THREAD

**Issue by NikkMann** [yuzu-emu/yuzu#7048]
### What's the issue you encountered?

When increasing the resolution of the game via mods, as the resolution increases from the game's default of 720p, the depth of field in cutscenes becomes more wrong. It looks like the focal length moves closer to the camera as resolution increases.

### How can the issue be reproduced?

Watch cutscenes with the 4k mod. The cutscene where Gold Joe is introduced after defeating Mr. Blackhole is a good example.

### Environment?

- Yuzu Mainline version: 753
- Game version: 1.0.1
- System Specs:
  - OS: Windows 10 (Fully Updated)
  - CPU: AMD 5900X
  - GPU: NVIDIA RTX 3090
  - RAM: 32GB
- Applied Mods : Yes, 4k Graphics Mod
### Additional context?

Here are some screenshots. Neither character should have depth of field on them in the cutscene:
https://imgur.com/a/8dzUIVO

**Comment by german77** [comment]
We don't give support to builds with mods. As the mod could be the one making the issues.
