### ISSUE TITLE
Accelerate DMA causes a hard crash on Dragon Quest Builders

### ISSUE THREAD

**Issue by ameerj** [yuzu-emu/yuzu#7052]
Booting Dragon Quest Builders with the OpenGL backend causes a hard memory crash. This seems to be a regression caused by #6629. 

To reproduce, boot Dragon Quest Builders with the OpenGL backend. Make sure to save all your work beforehand since the memory crash can corrupt opened programs.

By reverting the dependent fixup 84b9c42 and original merge commit, c53b688 , The crashes no longer occur.

**Comment by NineKain** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7288573/yuzu_log.txt)
