### ISSUE TITLE
Games are not working since Canary 485

### ISSUE THREAD

**Issue by Luffykun007** [yuzu-emu/yuzu#706]
The games are not working for me since the canary 485, i having this error now....it was not possible to load the rom. 
Last build that worked and still works is canary 485.
-----------------------------------------------------------------------------------------------------------------
Tested with commit a2c91db Canary 509

![capturar1](https://user-images.githubusercontent.com/26087621/42965758-340f03c8-8b71-11e8-89af-a31882f54f5d.JPG)

-----------------------------------------------------------------------------------------------------------------
Windows 10 pro 64 bits 1709
I5 6400
GTX 960
Log: [Log.zip](https://github.com/yuzu-emu/yuzu/files/2211396/Log.zip)

**Comment by bunnei** [comment]
Guessing this is a separate regression from VFS. Related to #698, but not the same. @DarkLordZach ping.

@Luffykun007 can you try booting Sonic Mania from File->Open ? It should work (works here)

**Comment by Luffykun007** [comment]
@Bunnei I opened the file by File-> Open and still have the same error!

Tested with commit cd4fca84

![capturar1](https://user-images.githubusercontent.com/26087621/42961492-4ecea684-8b65-11e8-9a19-435fc50d7224.JPG)
--------------------------------------------------------------------------------------------------------------
![capturar2](https://user-images.githubusercontent.com/26087621/42961510-59dfeb5a-8b65-11e8-8669-b089535167d3.JPG)
--------------------------------------------------------------------------------------------------------------
![capturar3](https://user-images.githubusercontent.com/26087621/42961527-657630aa-8b65-11e8-8aa2-a00cd79f4a26.JPG)

**Comment by Luffykun007** [comment]
@Bunnei resolved, it a problem with the files folder created in C: \ Users \ username \ AppData \ Roaming \ yuzu I deleted it and re-created a new folder then the games came back to work, closing it now.

**Comment by DarkLordZach** [comment]
@bunnei I did notice while working on #670 that random gliches and bugs could sometimes be alleviated by deleting the `nand` or `yuzu` folders. Its something to investigate, but I don;t think its vfs
