### ISSUE TITLE
revision 2019 in the hurry (demoscene) crashes out straight away

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#7063]
using latest mainline and EA
crashes out Yuzu nearly straight away
https://www.pouet.net/prod.php?which=81161

**Comment by german77** [comment]
what's up with the pouet links? I can't find anything related to yuzu there. Just drop the log in github. put it in a zip if it's too big

**Comment by benderscruffy** [comment]
that is where you download the demos from so anyone can try them out for themselves
