### ISSUE TITLE
 graphical issues：screen blurred in 2 minutes

### ISSUE THREAD

**Issue by lzkk4** [yuzu-emu/yuzu#7065]
- The yuzu early access 2072
- vulkan 
- Xeonblade 2 first scene
- the screen will blur in 2 or 3 minutes,100% recurrent
- GTX960-2G vram ，i7-4790k，4g+8g ram

![image](https://user-images.githubusercontent.com/67060386/134017991-2044c51f-a22e-410c-9a30-a75a471a4982.png)

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7196339/yuzu_log.txt.old.txt)

**Comment by lzkk4** [comment]
bug still exist...

**Comment by lzkk4** [comment]
still

**Comment by gidoly** [comment]
duplicated issue
