### ISSUE TITLE
The Legend of Zelda: Breath of the Wild (Torch sparks are not moving in "The Lost Woods")

### ISSUE THREAD

**Issue by Scarkritter** [yuzu-emu/yuzu#7066]
Hi,

it seems that there is a slight bug?!? with the rendering of sparks of torches in "The Legend of Zelda: Breath of the Wild". When I went into the "The Lost Woods". I couldn't figure the riddle out until I watched a youtube video which stated, that those sparks apparently should move to guide the way. As it seems right now when I emulate the game with Yuzu version "755 (2021-09-20)" this is not the case. It is really nothing major, but if this could be fixed it would be awesome :-).

![image](https://user-images.githubusercontent.com/11291234/134075400-537d27bb-be29-4762-86c5-6c7ece6d0ad2.png)

**Comment by goldenx86** [comment]
Use high GPU accuracy.

**Comment by G-Spawn** [comment]
Is this an issue? They do move.. you have to look very closely. I'll edit my post once I try mainline but it's fine in ea.

**Comment by Scarkritter** [comment]
> Use high GPU accuracy.

Will try right now.

**Comment by Scarkritter** [comment]
Yeah high GPU accuracy fixes that... very sorry for claming it to be an issue...
