### ISSUE TITLE
No bundled Qt binaries for your toolchain

### ISSUE THREAD

**Issue by Leebais** [yuzu-emu/yuzu#7067]
No bundled Qt binaries for your toolchain.  Disable YUZU_USE_BUNDLED_QT and
  provide your own.

**Comment by lat9nq** [comment]
Need a good bit more to go on than copy/pasting the error from https://github.com/yuzu-emu/yuzu/blob/master/CMakeLists.txt#L353. Operating system, compiler and version, yuzu commit, CMake version or installed Qt version, attempted solutions, any of that information would be miles more helpful than what you've posted.

**Comment by Morph1984** [comment]
Closing as the issue lacks required information
