### ISSUE TITLE
Xenoblade Chronicles DE Stutter

### ISSUE THREAD

**Issue by NineKain** [yuzu-emu/yuzu#7071]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7218166/yuzu_log.txt)

Specs: Ryzen 5 5600x, 3060ti, 16gb 3600mhz, running off of SSD.

My problem is heavy stutter in **Xenoblade Chronicles DE**, I have **60fps and x1.25 speed mods enabled**, but with them disabled it stutters heavily too, other games run fine, I have been told it's a "presentation issue" in the official Yuzu Discord. I have tried various options and none of them resolve my issue, here is a video demonstating the issue:

https://user-images.githubusercontent.com/72826232/134521191-0d6177bc-3528-4aa1-b382-c00837d88464.mp4

**Comment by FernandoS27** [comment]
It's known. I'll address it soon.

**Comment by NineKain** [comment]
That's nice to hear

**Comment by v1993** [comment]
If you're desperate with this issue, it can be worked around for now by reverting commit 92b2003ff8b1c1c95b91a1a2a71ea6d6c971719b (to avoid merge conflicts) and merging PR https://github.com/yuzu-emu/yuzu/pull/6787. However, that's know to cause rendering issues in a few other games.

**Comment by NineKain** [comment]
I'm patient, it's ok

**Comment by FernandoS27** [comment]
or get an EA 30 versions older than current.

**Comment by gidoly** [comment]
fixed by yfc 1
