### ISSUE TITLE
[Diablo II Resurrected] Doesnt boot

### ISSUE THREAD

**Issue by pacoa-kdbg** [yuzu-emu/yuzu#7072]
Game : Diablo II resurrected
Game Update : 1.0.0.1
Yuzu version : EA 2077
FW: 13.0.0
Latest keys
Yuzu stuck at loading, but able to "stop" emulation to go back to menu 

Lots of broken stuff on the log

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7219835/yuzu_log.txt.old.txt)

**Comment by smiglo5** [comment]
Can confirm that

**Comment by fuhuan416** [comment]
Of course you can boot it, just chencked Auto-stub and get different log.txt.

**Comment by PacoAvelar** [comment]
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7222059/yuzu_log.zip)

Auto-stub enabled (lol)

**Comment by fuhuan416** [comment]
I just enter the game, people must checked Auto-stub.
First picture is Vulkan performance, has some graphic glitches, like vertex boom?
2nd picture is OpenGL with GLASM performance.
Whatever OGL or Vulkan, they both are not render openning CG and any text
![image](https://user-images.githubusercontent.com/6281757/134672160-b5d8215e-d53c-41c9-864a-1fe97a8ac7cd.png)

![image](https://user-images.githubusercontent.com/6281757/134673782-8a9b1f56-c194-47a1-8baa-a4bb7b99d6a2.png)
[yuzu_log_OpenGL+Auto-Stub.zip](https://github.com/yuzu-emu/yuzu/files/7225596/yuzu_log_OpenGL%2BAuto-Stub.zip)
[yuzu_log_Vulkan+Auto-Stub.zip](https://github.com/yuzu-emu/yuzu/files/7225602/yuzu_log_Vulkan%2BAuto-Stub.zip)

**Comment by Darkywolf999** [comment]
it works without autostub now but the rest is still the same

**Comment by Darkywolf999** [comment]
vp8 is required for the videos.
not sure yet what is missing to make the text working.

**Comment by gandalfthewhite19890404** [comment]
I think issue should be closed now, other things like vertex explosions and missing text/textures was non-related to current issue itself.

**Comment by pacoa-kdbg** [comment]
Boot issue solved also in mainline.
Render issue solved by YFC
<img width="960" alt="image" src="https://user-images.githubusercontent.com/29181120/173997310-471e29b4-386f-4d93-9d04-f1652d774624.png">

**Comment by gidoly** [comment]
issue is fixed afaik feel free to comment if it is not fixed
