### ISSUE TITLE
Log gets spammed with "(STUBBED) called" in Mario Kart 8

### ISSUE THREAD

**Issue by Einheit-101** [yuzu-emu/yuzu#7073]
Hello, the following message is spammed in my Log, using Yuzu ver.755 20.09.2021:

Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:247: (STUBBED) called

Yuzu Log: 
https://www.dropbox.com/s/besyetloc1qs9wg/yuzu.txt?dl=0

**Comment by ToxaGaming** [comment]
This is expected behavior, and not an issue or bug as the game calls a service that the developers have stubbed. Unless the log mentions a critical issue then there's nothing to worry about.

**Comment by Einheit-101** [comment]
It would be beneficial if we could disable such warnings as they are useless then. And they make it more difficult to find real problems. I was searching through the Logs to find something meaningful as Information why Mario Party sometimes crashes the whole program after a while, but i just found 40 Megabytes of junk :D

**Comment by ToxaGaming** [comment]
They're not really useless as the purpose of logs is to log called services and such, whether they log expected or unexpected behavior
