### ISSUE TITLE
Assertion fail error spam in Mario Kart 8

### ISSUE THREAD

**Issue by Einheit-101** [yuzu-emu/yuzu#7074]
Hello, the following message is spammed in my Log, using Yuzu ver.755 20.09.2021:

Debug <Critical> video_core\rasterizer_accelerated.cpp:operator ():35: Assertion Failed!
Count may underflow!
Debug <Critical> video_core\rasterizer_accelerated.cpp:operator ():33: Assertion Failed!
Count may overflow!

Yuzu Log:
https://www.dropbox.com/s/besyetloc1qs9wg/yuzu.txt?dl=0

**Comment by v1993** [comment]
Please stop opening those issues. These are expected to happen for now since yuzu is still an experimental emulator.

**Comment by ToxaGaming** [comment]
> Please stop opening those issues. These are expected to happen for now since yuzu is still an experimental emulator.

Actually regarding the over/underflow count I mean to recall Blinkhawk mentioning that this isn't supposed to happen. Unsure if this would make this a valid issue though, so I'd like a devs input in that.

**Comment by Einheit-101** [comment]
You can do what you want with this Information, i just have seen toxic log spam and i reported it.
