### ISSUE TITLE
[BUG] Dumping exeFS no longer works (only romFS is dumped)

### ISSUE THREAD

**Issue by OZtistic** [yuzu-emu/yuzu#7081]
As per title
Turning on Dump exeFS in Filesystem Settings does nothing
romFS is still dumped, just no exeFS
This is the case for normal dump and SDMC dumping

_*Steps to replicate:*_
Simply turn on exeFS Dumping in the System --> Filesystem Settings
Attempt to dump any Title

**Comment by FearlessTobi** [comment]
Byte confirmed this is working properly again.
