### ISSUE TITLE
Luigi's Mansion 3 Still not fixed in EA

### ISSUE THREAD

**Issue by ArkhamTitty** [yuzu-emu/yuzu#7094]
Since PR #7077 was merged the game is stable and playable for the most part, but will still cause the AMD driver to crash when trying to load 15F, the final floor of the game.

The issue can be easily replicated by loading a save with access to 15F and attempting to enter the area, either through an auto save or from taking the elevator up from a lower floor.

**Comment by PacoAvelar** [comment]
@ArkhamTitty 
A save with 15F would be nice to replicate,
Also a log would be helpful

**Comment by ArkhamTitty** [comment]
> @ArkhamTitty
> A save with 15F would be nice to replicate,
> Also a log would be helpful

Good point. Don't seem to have the log for some reason but here's the save.

If you load the lounge from the main menu the driver will crash before loading into the game, but if you load the elevator save just beneath it, you should find that you're able to explore the entirety of the game other than 15F as the game will crash while the area is being loaded in.

[Luigi Save.zip](https://github.com/yuzu-emu/yuzu/files/7232472/Luigi.Save.zip)

**Comment by ArkhamTitty** [comment]
Crashes confirmed fixed by #7101.
