### ISSUE TITLE
Could you please to add calibration function to joycons?

### ISSUE THREAD

**Issue by PapperMirror** [yuzu-emu/yuzu#7098]
Still have joystick drift issue in using joycons after #6698.
I noticed that there is a function called ‘dump_calibration_data’ in Betterjoy which read 'user calibration data' or use 'factory stick calibration data' to calibrate joysticks.Could you please to add this function to Yuzu?
Thanks,and sorry for my bad English.

**Comment by PapperMirror** [comment]
https://github.com/Davidobot/BetterJoy/blob/50b64b1165ef311b5a18c21f92b2c27a201e6ea5/BetterJoyForCemu/Joycon.cs#L1171

**Comment by german77** [comment]
The linked PR already calibrates your joycons. If you find your joycon off center select it again from the devices list. This will recalíbrate them again

**Comment by PapperMirror** [comment]
Thank you for your help!
It do re-center the joystick when I select device again, but the joystick is still not accurate , when I push joysticks to one side, the blue point (in controller UI) can't reach the edge of the circle in some directions,and this problem does not occur when I'm using betterjoy.

**Comment by RiedleroD** [comment]
@german77 I've had mad troubles with the recalibration, especially after reconnecting controllers. Can you guys please add a manual calibration thingy? Something that measures the resting point and maximum axis values. That'd be really great!

Also, a few times the stick drift got so bad that the controls wouldn't let me assign the (hw) stick to the (sw) stick, so keep that in mind for any possible future PR.

note: my sticks don't drift on the actual switch and they're the stock joy-cons that came with my switch.

**Comment by german77** [comment]
You can manually center the axis with right click then selecting center axis. Implemented on #7860

**Comment by RiedleroD** [comment]
thanks a lot!
