### ISSUE TITLE
[Feature Request] Separate window version of the controller display in the control configuration

### ISSUE THREAD

**Issue by hlaaftana** [yuzu-emu/yuzu#7108]
yuzu's controls configuration shows a nice display of the currently used controller, the positioning of the stick and button presses in real time.

![image](https://user-images.githubusercontent.com/10591326/135309762-31f30276-3aa3-41df-8b46-b1eae2adc7a3.png)

This would be very useful to show in videos or streams of gameplay where precise controls are important, however the configuration window blocks the game window from being focused, so it is not very convenient to keep it open. In this sense, it would be helpful to be able to display it in its own separate window that does not steal the focus.

**Comment by Jatoxo** [comment]
There is a debug feature that does this in the top menu

**Comment by german77** [comment]
view - > debugging - > controller p1
