### ISSUE TITLE
Yuzu crash on window switching

### ISSUE THREAD

**Issue by SeaKestrel** [yuzu-emu/yuzu#7123]
Hi

I'm using Linux Ubuntu 21.04
Yuzu 9b3cdb401

I was playing ACNH using yuzu and just switched to discord using the Alt-Tab. Yuzu crashed.

The log is linke
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7272871/yuzu_log.txt.old.txt)
d

**Comment by liushuyu** [comment]
Hi there,

You seem to be running a very old self-compiled version of Yuzu.

You could try to compile a newer version of Yuzu or use our official AppImage version (https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-777) or our official Flatpak version (https://flathub.org/apps/details/org.yuzu_emu.yuzu).

**Comment by G-Spawn** [comment]
^ Please try newer yuzu versions and feel free to reopen if it still persists
