### ISSUE TITLE
Yuzu CTD while playing Mario Party

### ISSUE THREAD

**Issue by Einheit-101** [yuzu-emu/yuzu#7124]
Yuzu completely crashes to desktop randomly on Yuzu 755

Game:
Super Mario Party 1.0.1
ID: 
010036B0034E4000
File Format:
NCA

GeForce GTX 1060 on Vulkan

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7273656/yuzu_log.txt)

**Comment by G-Spawn** [comment]
If that is a repack we do not support such here. Please provide an unedited log from official updated yuzu if this issue still happens to you.
