### ISSUE TITLE
Steel Assault no showing anything only audio.

### ISSUE THREAD

**Issue by jvhellraiser** [yuzu-emu/yuzu#7125]
I hope i am doing this correct,

My Specs are :
32 gb Ram
9700k 8 cores
Nvidia 2060 RTX

Yuzu use is build EA 2105 

Issues is:
Yuzu loads the game it has audio and everything but there is nothing in the screen, 
you can change it from OpenGL to Vulcan but is always the same results.

**Comment by PrinceBubloo** [comment]
Share log pls

**Comment by jvhellraiser** [comment]
how do i do that? location?

**Comment by benderscruffy** [comment]
using the latest EA and mainline
still an issue

**Comment by benderscruffy** [comment]
goes ingame with graphics showing
no problems so far
can be closed
