### ISSUE TITLE
Yuzu mainline compile failing

### ISSUE THREAD

**Issue by re2mind** [yuzu-emu/yuzu#7126]
Using ubuntu 21.10, I try to compile yuzu-mainline to use environment variable for mesa. and, it keeps failing.

LOG:
re2mind@re2mind-Lenovo-ideapad-730S-13IWL:~/yuzu-mainline/build$ ninja
[225/1323] Building C object externals...ary/CMakeFiles/mbedtls.dir/ssl_tls.c.o
../externals/mbedtls/library/ssl_tls.c: In function ‘ssl_calc_finished_tls_sha384’:
../externals/mbedtls/library/ssl_tls.c:6408:5: warning: ‘mbedtls_sha512_finish_ret’ accessing 64 bytes in a region of size 48 [-Wstringop-overflow=]
 6408 |     finish_sha384( &sha512, padbuf );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../externals/mbedtls/library/ssl_tls.c:6408:5: note: referencing argument 2 of type ‘unsigned char *’
In file included from ../externals/mbedtls/include/mbedtls/ssl_internal.h:74,
                 from ../externals/mbedtls/library/ssl_tls.c:73:
../externals/mbedtls/include/mbedtls/sha512.h:165:5: note: in a call to function ‘mbedtls_sha512_finish_ret’
  165 | int mbedtls_sha512_finish_ret( mbedtls_sha512_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
[341/1323] Building C object externals...Files/speex.dir/src/speex/resample.c.o
../externals/cubeb/src/speex/resample.c: In function ‘update_filter’:
../externals/cubeb/src/speex/resample.c:674:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
  674 |          for (j=0;j<st->filt_len;j++)
      |                    ^
../externals/cubeb/src/speex/resample.c: In function ‘speex_resampler_process_float’:
../externals/cubeb/src/speex/resample.c:946:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
  946 |            for(j=0;j<ichunk;++j)
      |                     ^
../externals/cubeb/src/speex/resample.c:949:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
  949 |           for(j=0;j<ichunk;++j)
      |                    ^
../externals/cubeb/src/speex/resample.c: In function ‘speex_resampler_process_int’:
../externals/cubeb/src/speex/resample.c:1002:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1002 |          for(j=0;j<ichunk;++j)
      |                   ^
../externals/cubeb/src/speex/resample.c:1009:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1009 |          for(j=0;j<ichunk;++j)
      |                   ^
../externals/cubeb/src/speex/resample.c:1019:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1019 |      for (j=0;j<ochunk+omagic;++j)
      |                ^
[436/1323] Building CXX object externa...kend/x64/exception_handler_posix.cpp.o
FAILED: externals/dynarmic/src/dynarmic/CMakeFiles/dynarmic.dir/backend/x64/exception_handler_posix.cpp.o 
/usr/lib/ccache/c++ -DARCHITECTURE_x86_64=1 -DBOOST_ALL_NO_LIB -DBOOST_ASIO_DISABLE_CONCEPTS -DBOOST_DATE_TIME_NO_LIB -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DDYNARMIC_ENABLE_CPU_FEATURE_DETECTION=1 -DDYNARMIC_IGNORE_ASSERTS=1 -DFMT_USE_USER_DEFINED_LITERALS=1 -DXBYAK_NO_OP_NAMES -DYUZU_UNIX=1 -I/home/re2mind/.conan/data/catch2/2.13.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/home/re2mind/.conan/data/nlohmann_json/3.8.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/home/re2mind/.conan/data/zstd/1.5.0/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646/include -I../externals/dynarmic/src/dynarmic/.. -I../externals/dynarmic/externals/mp/include -I../externals/dynarmic/externals/zydis/include -Iexternals/dynarmic/externals/zydis -I../externals/dynarmic/externals/zycore/include -Iexternals/dynarmic/externals/zydis/zycore -isystem /home/re2mind/.conan/data/fmt/8.0.0/_/_/package/2c09c8f84c016041549fcee94e4caae5d89424b6/include -isystem ../externals/dynarmic/externals/robin-map/include -isystem externals/xbyak/include -O3 -DNDEBUG  -Wall -Wextra -Wcast-qual -pedantic -pedantic-errors -Wno-missing-braces -std=c++2a -MD -MT externals/dynarmic/src/dynarmic/CMakeFiles/dynarmic.dir/backend/x64/exception_handler_posix.cpp.o -MF externals/dynarmic/src/dynarmic/CMakeFiles/dynarmic.dir/backend/x64/exception_handler_posix.cpp.o.d -o externals/dynarmic/src/dynarmic/CMakeFiles/dynarmic.dir/backend/x64/exception_handler_posix.cpp.o -c ../externals/dynarmic/src/dynarmic/backend/x64/exception_handler_posix.cpp
../externals/dynarmic/src/dynarmic/backend/x64/exception_handler_posix.cpp: In constructor ‘Dynarmic::Backend::X64::{anonymous}::SigHandler::SigHandler()’:
../externals/dynarmic/src/dynarmic/backend/x64/exception_handler_posix.cpp:67:50: error: no matching function for call to ‘max(long int, int)’
   67 |     constexpr size_t signal_stack_size = std::max(SIGSTKSZ, 2 * 1024 * 1024);
      |                                          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/array:40,
                 from /usr/include/c++/11/tuple:39,
                 from /usr/include/c++/11/functional:54,
                 from ../externals/dynarmic/src/dynarmic/../dynarmic/backend/x64/exception_handler.h:8,
                 from ../externals/dynarmic/src/dynarmic/backend/x64/exception_handler_posix.cpp:6:
/usr/include/c++/11/bits/stl_algobase.h:254:5: note: candidate: ‘template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)’
  254 |     max(const _Tp& __a, const _Tp& __b)
      |     ^~~
/usr/include/c++/11/bits/stl_algobase.h:254:5: note:   template argument deduction/substitution failed:
../externals/dynarmic/src/dynarmic/backend/x64/exception_handler_posix.cpp:67:50: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long int’ and ‘int’)
   67 |     constexpr size_t signal_stack_size = std::max(SIGSTKSZ, 2 * 1024 * 1024);
      |                                          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/array:40,
                 from /usr/include/c++/11/tuple:39,
                 from /usr/include/c++/11/functional:54,
                 from ../externals/dynarmic/src/dynarmic/../dynarmic/backend/x64/exception_handler.h:8,
                 from ../externals/dynarmic/src/dynarmic/backend/x64/exception_handler_posix.cpp:6:
/usr/include/c++/11/bits/stl_algobase.h:300:5: note: candidate: ‘template<class _Tp, class _Compare> constexpr const _Tp& std::max(const _Tp&, const _Tp&, _Compare)’
  300 |     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
/usr/include/c++/11/bits/stl_algobase.h:300:5: note:   template argument deduction/substitution failed:
../externals/dynarmic/src/dynarmic/backend/x64/exception_handler_posix.cpp:67:50: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long int’ and ‘int’)
   67 |     constexpr size_t signal_stack_size = std::max(SIGSTKSZ, 2 * 1024 * 1024);
      |                                          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/vector:62,
                 from /usr/include/c++/11/functional:62,
                 from ../externals/dynarmic/src/dynarmic/../dynarmic/backend/x64/exception_handler.h:8,
                 from ../externals/dynarmic/src/dynarmic/backend/x64/exception_handler_posix.cpp:6:
/usr/include/c++/11/bits/stl_algo.h:3461:5: note: candidate: ‘template<class _Tp> constexpr _Tp std::max(std::initializer_list<_Tp>)’
 3461 |     max(initializer_list<_Tp> __l)
      |     ^~~
/usr/include/c++/11/bits/stl_algo.h:3461:5: note:   template argument deduction/substitution failed:
../externals/dynarmic/src/dynarmic/backend/x64/exception_handler_posix.cpp:67:50: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘long int’
   67 |     constexpr size_t signal_stack_size = std::max(SIGSTKSZ, 2 * 1024 * 1024);
      |                                          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/vector:62,
                 from /usr/include/c++/11/functional:62,
                 from ../externals/dynarmic/src/dynarmic/../dynarmic/backend/x64/exception_handler.h:8,
                 from ../externals/dynarmic/src/dynarmic/backend/x64/exception_handler_posix.cpp:6:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: candidate: ‘template<class _Tp, class _Compare> constexpr _Tp std::max(std::initializer_list<_Tp>, _Compare)’
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
/usr/include/c++/11/bits/stl_algo.h:3467:5: note:   template argument deduction/substitution failed:
../externals/dynarmic/src/dynarmic/backend/x64/exception_handler_posix.cpp:67:50: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘long int’
   67 |     constexpr size_t signal_stack_size = std::max(SIGSTKSZ, 2 * 1024 * 1024);
      |                                          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
[445/1323] Generating ../../../externals/libusb/libusb/configure
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:23: installing './compile'
configure.ac:27: installing './config.guess'
configure.ac:27: installing './config.sub'
configure.ac:26: installing './install-sh'
configure.ac:26: installing './missing'
Makefile.am: installing './INSTALL'
examples/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
ninja: build stopped: subcommand failed.

**Comment by liamwhite** [comment]
Please retest with 22.04, thanks!
