### ISSUE TITLE
yuzu freezes when i create a local mp hub on mhgu

### ISSUE THREAD

**Issue by LuisFellp** [yuzu-emu/yuzu#7128]
my specs:
ryzen 5 3400g
16gb ram

issue: 
when i create a online hub on mhgu (local) it freezes. i followed all steps to play lan

log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7281725/yuzu_log.txt)
:

**Comment by G-Spawn** [comment]
We still can't provide you support with piracy.
