### ISSUE TITLE
Metroid Dread - videos not rendering

### ISSUE THREAD

**Issue by ZoruaLoL** [yuzu-emu/yuzu#7129]
Many elements of Metroid Dread work with .webm video playback (The title screen being one of them, the prologue sequence, the upgrade explanation, etc.)

![010093801237c000_2021-10-05_01-55-05-865](https://user-images.githubusercontent.com/49895285/135962674-6757ebde-d05a-48ef-be51-9200ff1992a2.png)

What should be on the background:

![vlcsnap-2021-10-05-01h57m40s708](https://user-images.githubusercontent.com/49895285/135962638-000743e9-33ec-4b65-884d-899cc2b87d37.png)

Outside of that the game seem to render perfectly and at a flawless performance minus certain sudden split-frame mesh pop-ins. 

**Settings:** 
- Yuzu 768
- Vulkan
- GPU Normal
- Dock
- Other settings on default

**System Specs:**
- Windows 10
- AMD FX-8320E 
- 8GB RAM
- AMD RX 580 8GB (Adrenalin 21.10.1)

**Comment by german77** [comment]
We don't give support to piracy
