### ISSUE TITLE
Metroid Dread - All videos glitch in specific room

### ISSUE THREAD

**Issue by megaboyx90** [yuzu-emu/yuzu#7149]
Mainline Build - 33c453503
Title - Metroid Dread
Issue: When loading into this specific room, all video files break including: game over screen, power up menu videos, and
background videos. Issue doesn't persist when room is exited. Happens with OpenGL & Vulkan renderers.
![image](https://user-images.githubusercontent.com/45728868/136645979-6ab94fa2-1e9a-4e32-9702-86760901e34d.png)
![image](https://user-images.githubusercontent.com/45728868/136646008-64425e52-a052-4123-9628-c0babd1de688.png)
![image](https://user-images.githubusercontent.com/45728868/136646017-56c63b4a-497f-4642-8eeb-44264e14b698.png)
Specs: 
- Ryzen 5 2600
- GTX 1050 ti 
- 16gb DDR4 ram

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7315047/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Could you provide a save file and try auto cpu accuracy?

**Comment by smiglo5** [comment]
I can confirm that
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7315117/yuzu_log.txt)

Here is the log, and here is the savefile, its the room below yellow saveroom:
[010093801237C000.zip](https://github.com/yuzu-emu/yuzu/files/7315119/010093801237C000.zip)

**Comment by smiglo5** [comment]
https://user-images.githubusercontent.com/30460684/136672643-b53f35a0-1106-416a-a6d8-70cf9f859c34.mp4

Here is a video showing this bug

**Comment by Hootek** [comment]
same, in cutscene too

**Comment by vasishath** [comment]
This bug is also triggered on viewing any video after viewing a shuttle travelling cutscene. Even the game over screen video is affected. It can also cause the game/emulator to crash/freeze as well if u die a few times.

**Comment by G-Spawn** [comment]
This should be fixed on updated yuzu. Please reopen should it still happen.
