### ISSUE TITLE
Stuttering in Fullscreen (and only there)

### ISSUE THREAD

**Issue by spyro2000** [yuzu-emu/yuzu#7150]
Version: 1.0.7066
HW: Nvidia GTX 1070, AMD Ryzen 7 3800X

Performance (Metroid Dread) seems absolutely flawless, even at 4x scale mode. For some strange reason, I've to deactivate (!) V-Sync (red) to make it run in full 60 fps. But in Fullscreen, the game has stuttering. As soon as I leave fullscreen again, everything is smooth again...

Is there a possiblity to run the game in borderless window mode?

Thank you!

**Comment by G-Spawn** [comment]
Yuzu doesn't have scaling nor that version numbering. Perhaps you're thinking of the other emulator called Ryujinx.

**Comment by G-Spawn** [comment]
If you use latest mainline yuzu you'll be fine. Please consider closing this issue. Scaler will be a thing someday in yuzu when it is done being developed.
