### ISSUE TITLE
Cruis'n Blast glitched vehicle icons

### ISSUE THREAD

**Issue by ghost** [yuzu-emu/yuzu#7177]
- Using EA 2127
- Missing/glitched out textures for some menu selections
- Using OpenGL on a GTX 1070 Ti, driver version 472.12.
What yuzu looks like:
![image](https://user-images.githubusercontent.com/92214833/137245910-ea75a06c-6a30-4ac1-a196-bd76becc0617.png)

What it's supposed to look like:
![image](https://user-images.githubusercontent.com/92214833/137246125-d8fd823b-665f-4daa-a96b-1e19e5ded2b8.png)

**Comment by G-Spawn** [comment]
Provide a log file please as the new issue template states.

**Comment by G-Spawn** [comment]
Closed as the user no longer exists on github
