### ISSUE TITLE
Eastward Save Issues

### ISSUE THREAD

**Issue by Nayrrrr** [yuzu-emu/yuzu#7220]
Eastward is unable to generate a save file for any of the file slots.

But a workaround was found that by creating a subfolder within the save file directory and naming them "slot1", "slot2" and "slot3" fixed this and was able to generate the files for each slot.

Can confirm this works on manual save locations and the autosave feature.

Simple workaround for a stupid bug.

Eastward Update 1.0.5f
Tested on Early Acces 2156

Hardware:
CPU: AMD Ryzen 7 4800H
OS: Windows 10
RAM: 32 GB
Device: NVIDIA GeForce GTX 1660 TI
Driver: NVIDIA 472.33

**Comment by StelioKantos** [comment]
Yuzu 972 here and I still experience this issue. Creating the slot1, slot2, etc. folders doesn't work for me. I tried making them in the main save directory as well as the savedata folder. Am I doing something wrong? Do I need to delete the savedata folder? Thanks!
