### ISSUE TITLE
[Bug] Dying Light Premium Edition - black screen after intro cutscene

### ISSUE THREAD

**Issue by Darth-Cthoras** [yuzu-emu/yuzu#7225]
Yuzu: version 789 mainline

Game: Dying Light Platinum Edition 1.0.0 / 1.0.1 (occurred in both)

Details: game starts fine, goes into intro cutscene, screen stays black after cutscene but the FPS counter does *not* drop to zero. Log shows a Unknown / unimplemented function 'PopPurchasedProductInfo' is called, and then 'emulated program broke execution'. Game has offline single-player and non-forced online co-op.

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7407449/yuzu_log.txt.old.txt)

**Comment by benderscruffy** [comment]
using the latest EA and mainline
this is still an issue

**Comment by benderscruffy** [comment]
@FearlessTobi 
goes ingame now can be closed
