### ISSUE TITLE
vulkan doesnt work on Xenoblade Chronicles 1

### ISSUE THREAD

**Issue by ISuckGood** [yuzu-emu/yuzu#7226]
Vulkan is broken in xenoblade chronicles 1 
Works fine in OpenGL

![2021-10-24_23h13_28](https://user-images.githubusercontent.com/42075250/138693980-e891896f-c2c5-4c1b-8163-2a0d6f4a7021.png)
![2021-10-25_14h18_55](https://user-images.githubusercontent.com/42075250/138693991-74ed2112-466b-40ca-b1e3-d2f02f3e2a33.png)

**Comment by reloxx13** [comment]
duplicate #5756

**Comment by jrobeson** [comment]
this doesn't just happen on vulkan. It occasionally happens on opengl as well. It's certainly rare though. I haven't come up with a reproducible case.

**Comment by ISuckGood** [comment]
done
