### ISSUE TITLE
Steve looks like a black cross (Smash Bros. Ultimate)

### ISSUE THREAD

**Issue by hatoving** [yuzu-emu/yuzu#7234]
I've played Smash on yuzu for a while now, it runs great! But it can't escape graphical bugs, of course.
I've loaded up a random stage with a random CPU with me playing as Steve, leading to his bug:

![unknown](https://user-images.githubusercontent.com/64536760/138878644-114e4b7e-f246-4a1b-a1c0-5e6b1990bf6a.png)

Meanwhile he's supposed to look like this (sorry for using a different image instead of actual hardware lol):

![201001_nsw_ssbu_screenshot_ssbu_steve_alex__homepage_1](https://user-images.githubusercontent.com/64536760/138878814-f7c05679-a96e-484a-982a-d65dc1a5ad12.jpg)

I've used yuzu 790 with a GTX 1650. Somehow I wanted to include that. Beside that glitch, everything else was fine.

Here's the log file if anyone needs it (sorry for using Google Drive, GitHub doesn't allow me to upload the file for some reason): https://drive.google.com/file/d/1PzczSJ1o8tlATtwdqLDvKG5NroBBRI_t/view?usp=sharing

**Comment by G-Spawn** [comment]
Can you please try on latest version to see if this issue persists?
