### ISSUE TITLE
hyrule warriors definitve edition regression since mainline 781

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#7235]
hyrule warriors definitve edition got text corruption issue since 781
780 was last fine build on my test

![yuzu_ATJiLiv1tY](https://user-images.githubusercontent.com/66776795/138952596-9499eddd-954c-4608-9e54-c5346693b400.jpg)
how to reproduce:
since it is random i tried restart 30times to confirm it happens.
log from newest build:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7421191/yuzu_log.txt)

**Comment by v1993** [comment]
If this is indeed introduced by 781, #7187 looks like a very likely candidate for causing it.

**Comment by ValiantBlade** [comment]
Very late update from a user, but this issue appears to have been fixed by some other commit relatively recently, as this issue is now gone from mainline. As to which one, that will likely need some investigation by someone who knows more about the changes that could cause this than I do.

**Comment by v1993** [comment]
If it's gone, I'm guessing it was nvflinger rewrite/fixups that fixed this.

**Comment by gidoly** [comment]
fixed with yfc 1
