### ISSUE TITLE
Metroid Dread: Corpius, poison balls are rendered invisible

### ISSUE THREAD

**Issue by lemmingfactory** [yuzu-emu/yuzu#7239]
Metroid Dread, version 1.01, Yuzu 792 (and other versions as well, AFAIK), GTX 1070, 8700K, Windows 10.

In the first boss fight with Corpius, the poison balls being tossed at you are invisible.  They are rendered correctly on real hardware and on Ryujinx.

**Comment by G-Spawn** [comment]
still waiting. if you are on latest nvidia driver blame that for issue. 472.12 is non issue for corpius poison.

**Comment by lemmingfactory** [comment]
Thanks for responding.  Sorry, was not available for a while.  Just installed 472.12 and poison balls are still invisible.  Here's a copy of the log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7464656/yuzu_log.txt)
.

**Comment by lemmingfactory** [comment]
Reset everything and now rendering seems normal.  Sorry for the trouble.

**Comment by G-Spawn** [comment]
Not a problem. Glad to hear it is fixed.
