### ISSUE TITLE
Metroid Dread, version 1.01, Yuzu 794 (Sourround not working)

### ISSUE THREAD

**Issue by yandritos** [yuzu-emu/yuzu#7248]
Metroid Dread, version 1.01, Yuzu 794 (Sourround not working), RTX 2070 super (Vulkan), ryzen 2700x, Windows 10. 

-Yuzu is configured with the  Output sound "Sourround" ("Envolvente" in spanish) and auto (tested with the libraries instead of auto with the same result).

My sorround amplifier is working properly (tested with the windows audio tool) but there is not way to play Metroid Dread with sourround, the rear speakers are not reproducing any kind of sound.

Thanks in advance!

**Comment by Its-Rei** [comment]
Surround is just a placeholder at this point. There's only stereo even if you select surround.

**Comment by yandritos** [comment]
Oki,  good to know, thanks for the fast feedback and good work!
