### ISSUE TITLE
Keyboard Softlock on Monster hunter generation ultimate

### ISSUE THREAD

**Issue by Kristianno** [yuzu-emu/yuzu#7249]
softlock keyboard returns after playing for awhile, character creation is fixed but if you play further the keyboard will crash and softlock your game. I can no longer rename my item and equipment sets when i got into g-rank

**Comment by Kristianno** [comment]
here's the log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7445691/yuzu_log.txt)

**Comment by WoefulWombat** [comment]
Experiencing the same. For me, it's accepting the HR3 urgent quest to fight Narkarkos that vanishes it. Stays gone indefinitely afterwards. Trying a first time results in the screen dimming for a few seconds, then returning to normal and letting you play again. A second try without restarting leaves the game unresponsive to inputs for good.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7456602/yuzu_log.txt)

**Comment by fanitriastowo** [comment]
Since there's no definitive solution, I suggest anyone to download yuzu from previous version BEFORE 10 November 2021. Those versions are specific for MHGU keyboard applet issue. I've no idea if it will compatible with the game that you play using the latest version
