### ISSUE TITLE
Hyper Light Drifter does not boot (All versions)

### ISSUE THREAD

**Issue by JWayn596** [yuzu-emu/yuzu#7252]
Yuzu EA build 2171

Issue:  Hyper Light Drifter will not boot regardless of settings, refuses to load shaders, logs show an attempt to load followed by a timeout, that infinitely loops.

Log attached.  Vulkan used, however, the game will not load regardless of: GPU Drivers, Vulkan, OpenGL, various graphical settings including asynchronous shader loading.

Log: 
[yuzu_Log_HyperLightDrifter.txt](https://github.com/yuzu-emu/yuzu/files/7447670/yuzu_Log_HyperLightDrifter.txt)

**Comment by JWayn596** [comment]
Yuzu EA build 2212:

No change, still does not boot

**Comment by JWayn596** [comment]
Yuzu EA build 2273:  No change at all

**Comment by Vertimusmaximus** [comment]
Yuzu tells me it won't boot. But I'm playing it. 
![16542134147048164198286350043193](https://user-images.githubusercontent.com/104597050/171757929-40a51ed2-b629-4279-b5e9-56173b833cc5.jpg)

**Comment by Vertimusmaximus** [comment]
No sound maybe too.

**Comment by benderscruffy** [comment]
goes ingame no problems so far
can be closed
