### ISSUE TITLE
Can't start any game with Vulkan in Hybrid Mode (`Invalid device index 0!`)

### ISSUE THREAD

**Issue by akaita** [yuzu-emu/yuzu#7258]
Every time I try to start any game with Vulkan, I get the error:
![Screenshot 2021-10-31 112953](https://user-images.githubusercontent.com/10153800/139580903-40ba473b-4622-4d0a-a48e-20ba14dcbbb0.png)

With the **log** [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7448653/yuzu_log.txt)
```
[ 548.531094] Render.Vulkan <Error> video_core\renderer_vulkan\renderer_vulkan.cpp:CreateDevice:88: Invalid device index 0!
[ 548.534016] Render.Vulkan <Error> video_core\renderer_vulkan\renderer_vulkan.cpp:RendererVulkan:116: Vulkan initialization failed with error: VK_ERROR_INITIALIZATION_FAILED
[ 548.534050] HW.GPU <Error> video_core\video_core.cpp:CreateGPU:51: Failed to initialize GPU: Vulkan initialization error VK_ERROR_INITIALIZATION_FAILED
[ 548.535347] Core <Critical> core\core.cpp:Load:258: Failed to initialize system (Error 5)!
```

I have Hybrid Mode enabled in my Lenovo Legion laptop. 
I have set up Windows 10 and Nvidia Control panel to use the Nvidia GPU with Yuzu.
The Nvidia GPU activity monitor shows that Yuzu is indeed using the GPU:
![Screenshot 2021-10-31 113230](https://user-images.githubusercontent.com/10153800/139581012-f578767b-56b5-4d27-aa7c-db0da717edfe.png)

If I disable Hybrid Mode (which is annoying, because it requires a restart), Yuzu can run Vulkan perfectly fine.

Details of my set up:

> Yuzu version: 794
> OS version: Windows 10 21H1 x64
> OS Build: 19043.1288
> Laptop: Legion 5 Pro 16ACH6H
> CPU: AMD Ryzen 7 5800H with Radeon Graphics
> GPU: NVIDIA RTX 3070 Laptop

**Comment by german77** [comment]
Update both GPU drivers

**Comment by akaita** [comment]
Today Lenovo updated the GPU driver for the AMD GPU. The new version is 27.20.15026.8004
I can confirm that now Vulkan works good with Hybrid Mode in my machine (Yuzu 799).

Thanks for your work!
