### ISSUE TITLE
Mad Rat Dead vibration not working properly

### ISSUE THREAD

**Issue by SilentHeII** [yuzu-emu/yuzu#7263]
Mad Rat Dead is a rhythm platformer that makes use of controller vibration by having the controller vibrate to the beat of the music to help keep you in rhythm. It also uses it for cinematic moments and just a ton in general. However, for whatever reason, the game will vibrate the controller in the settings menu when you toggle the vibration, but it won't vibrate anywhere else in the game. You can test this for yourself at the very beginning of the game once the gameplay starts proper.
![Style](https://user-images.githubusercontent.com/29898818/140454993-554beef0-d360-487c-9731-e462c1c9037b.png)

I'm on Early Access 2173. My specs are as follows:
Windows 10
Ryzen 7 3700X
16GB RAM
NVIDIA GTX 1080ti

I'm using an official Nintendo Switch Pro Controller with the default mapping provided by Yuzu. The accurate vibration setting also doesn't resolve the issue.

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7449882/yuzu_log.txt.old.txt)

**Comment by SilentHeII** [comment]
I just tested it again on EA 2189 and it appears to be working correctly now.

**Comment by german77** [comment]
Oh nice to know. Kraken might have fixed it
