### ISSUE TITLE
Crash on game startup - common\virtual_buffer.cpp:operator

### ISSUE THREAD

**Issue by denisidoro** [yuzu-emu/yuzu#7266]
```
Debug <Critical> common\virtual_buffer.cpp:operator ():27: Assertion Failed!
```

I'm able to play a game for, say, 25min. Then it crashes.

After I reopen yuzu, it crashes immediately after selecting a game.

It only works again after a system reboot.

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7452672/yuzu_log.txt.old.txt)

**Comment by v1993** [comment]
You have no swap/virtual memory/page file allocated. Make one that's at least 20GB big.

P.S.: please use [yuzu discord](https://discord.gg/yuzu-emu) for support requests. This is a bug tracker.
