### ISSUE TITLE
Saviors of Sapphire Wings & Stranger of Sword City Revisited, stuck at very beginning "Lancement" (launch in french)

### ISSUE THREAD

**Issue by Tsuru55** [yuzu-emu/yuzu#7267]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7452934/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Downgrade gpu driver to 472.12 or try redumping game from console to rule out corruption.

**Comment by Tsuru55** [comment]
@G-Spawn Sadly i got totally no clue how to any of the 2 things you said ^^"
Even though i should be the generation that should mock their parents for being terrible at computers, myself i am quite incompetent ^^"

**Comment by G-Spawn** [comment]
https://us.download.nvidia.com/Windows/472.12/472.12-notebook-win10-win11-64bit-international-dch-whql.exe run this pick custom, then enable clean install checkbox.

For redumping game it is the same thing you did the first time to get it from your switch, but again. https://yuzu-emu.org/help/quickstart/

**Comment by G-Spawn** [comment]
Please reopen this issue if it still happens to you on latest yuzu & provide a log file from updated version https://yuzu-emu.org/help/reference/log-files/
