### ISSUE TITLE
The "Services" tab doesn't seem to exist

### ISSUE THREAD

**Issue by PixelQiwi** [yuzu-emu/yuzu#7275]
As said in the title, I can't seem to find the "Services" tab in the "System" menu of configuration screen.
I have seen screenshots on [a forum post](https://community.citra-emu.org/t/yuzu-boxcat-is-offline/349939) from as recently as January of 2021 where a person (DeathFreak0990) has these, but it doesn't seem to be there for me. [Here's my screenshot of the same row of tabs.](https://i.imgur.com/fpt4Js7.png)

- [ ] Am I doing something wrong?
- [ ] Am I blind?

Please help.
I really want the ACNH events, and they only come in BCATs.

Yuzu versions: Stable 791 and EA 2160

**Comment by G-Spawn** [comment]
boxcat files manually placed so n otg work here yet. you will have easier time waiting for emulator improvement or for the next game update to come out, then you use custom rtc to jump back.

**Comment by AliciaBurrito** [comment]
The Boxcat service was also removed recently since it was no longer being maintained / worked. Like G-Spawn said, the devs are planning for future functionality where you provide your own BCAT files.

**Comment by PixelQiwi** [comment]
Ah, okay, that makes sense then.
Well, I do hope that I'll get to feed the game my own BCAT files _eventually_.

Sucks that I'll have to miss out on the Halloween event, but thank you for your answers anyway, that's at least one less mystery for me.

**Comment by soredake** [comment]
related https://github.com/yuzu-emu/yuzu/issues/6134
