### ISSUE TITLE
BoTW Zelda's Ballad always crashes on Vulkan.

### ISSUE THREAD

**Issue by ghost** [yuzu-emu/yuzu#7284]
So I as stated above when using the Zelda's Ballad mod with both Hotfixes applied yuzu keeps crashing when using the Vulkan API, even at 1x. I have tried clearing the Vulkan pipeline cache and increasing my page file to 20000 and still crashes. So I was asked to submit an issue request so here it is.

**Comment by chaudois** [comment]
hi, can you share the method or a link to the documentation of the method you used to install this mod pls?
