### ISSUE TITLE
Luigis Mansion 3 softlock at start when added into list

### ISSUE THREAD

**Issue by rufengsuixing** [yuzu-emu/yuzu#7286]
Luigis Mansion 3[v1.4.0][0100DCA0064A6000][US][v327680](1G+1U+2D).xci
early access 2182 with all mods on
i find it will be lock at start if i add the game Path into the list.once i add the game into list even then remove it from list,it won't start until i reboot the pc or rename the yuzu program dir.only this game have the bug，other game can be add into list and run 
although i stop the game  the log is still increasing

[new 2.txt](https://github.com/yuzu-emu/yuzu/files/7477665/new.2.txt)

**Comment by G-Spawn** [comment]
Disable the game update then all your mods will work, or download newer mods for it from our mods page https://yuzu-emu.org/wiki/switch-mods/
