### ISSUE TITLE
Death Gambit Afterlife random crashs

### ISSUE THREAD

**Issue by s3ruX** [yuzu-emu/yuzu#7295]
Actually get in game with not visual problems, performance seems ok scale and anisotropic works but load times is kind slow... take sometime to load it feels the emulator crashs but if you wait he run the game.

the main problem is the random crashs sometimes in 5 minutes sometimes in seconds. 

[Log removed by moderator]

**Comment by german77** [comment]
We don't allow piracy. However the issue may exist. If anyone can verify please upload a log of this error with a valid switch dump

**Comment by s3ruX** [comment]
Well i could not make my dump actually work 1 in 10 game i dump works lol, next week when i get my switch back i try to dump again, sorry for the trouble was not my intention.

**Comment by benderscruffy** [comment]
Please close
No update
