### ISSUE TITLE
Bioshock Remaster : Softlock

### ISSUE THREAD

**Issue by Djipi71** [yuzu-emu/yuzu#7298]
Try with the EA 2189 and olders.
Game update 1.0.2

The game work well but at one stage , there is a softlock, i can't passed it :(

LOG:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7490262/yuzu_log.zip)

SAVE:
[Save.zip](https://github.com/yuzu-emu/yuzu/files/7490261/Save.zip)

**Comment by benderscruffy** [comment]
please close
no update

**Comment by Djipi71** [comment]
Test on the Last EA, now it's not crash . Can be closed.
