### ISSUE TITLE
Mario Party Superstars Eatsa Pizza Broken

### ISSUE THREAD

**Issue by Codyjames34526** [yuzu-emu/yuzu#7300]
Pizza appears broken with interlaced lines and AI doesn't seem to work properly.
![image](https://user-images.githubusercontent.com/47513920/140611468-7a8f8d44-cdf5-4d9f-853f-472ffe0ce85a.png)

**Comment by FernandoS27** [comment]
this is a duplicate of the general mario party bugs issues.
