### ISSUE TITLE
Cannot recognize my controller correctly 

### ISSUE THREAD

**Issue by zzhzero** [yuzu-emu/yuzu#7301]
version 2189 Cannot recognize my controller correctly ，version 801 no problem 。

You can see the screenshot below，version 801 is right.

![image](https://user-images.githubusercontent.com/26578967/140646897-06ac8f46-68e9-41fb-8022-84cb39d5f8a1.png)

**Comment by smiglo5** [comment]
If the problem is only on the side of incorrectly assigned analog axes, assign them manually as reverse axes.

**Comment by zzhzero** [comment]
> If the problem is only on the side of incorrectly assigned analog axes, assign them manually as reverse axes.

The allocation process is automatic，I cannot manually specify every direction

**Comment by zzhzero** [comment]
yuzu\config\input:
change invert_y:-
