### ISSUE TITLE
SMT 5 Crash after loading screen in linux

### ISSUE THREAD

**Issue by LeandroElZar** [yuzu-emu/yuzu#7306]
After the cutscene in Takanawa Tunnel (first minutes of gameplay) yuzu crashes in the following loading screen. 
Tested with both Vulkan and OpenGL (mesa)

using Yuzu Mainline Build - 662a417cb
-yuzu-20211108-662a417cb.appimage directly from yuzu website 

OS: Arch Linux
Kernel: 5.10.71-1-lts
CPU: AMD R5 2600
GPU: Radeon RX570 
DRIVERS: AMDGPU 5.10.78-1-lts
RAM: 16GB 

LOG:
-->
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7501473/yuzu_log.txt)

I didn't find a way to retrieve a backtrace

**Comment by german77** [comment]
Leaks are not allowed here.

**Comment by LeandroElZar** [comment]
Ohh srry it wasn't in the rules but i should have though it.
Ill pray that the following update can fix it so i don't need to post the issue again.
