### ISSUE TITLE
Shin Megami Tensei V problem

### ISSUE THREAD

**Issue by Kira030** [yuzu-emu/yuzu#7307]
When entering character's name at the start of the game it's impossible to confirm it.
After pressing confirm button game shows this:
![bug](https://user-images.githubusercontent.com/88405846/140857430-1e74e13d-345e-491c-8f1f-1df883a110d6.png)
s:
Emulator itselves softlocks, all menus becoming unusable, and it's impossible to close it without terminating the process with the taskbar.

**Comment by AliciaBurrito** [comment]
Please do not open issues about leaks. The game has not officially released yet.

**Comment by bloodypala** [comment]
how about now, can someone fix it?
