### ISSUE TITLE
Feature Request: Double buffering, Triple buffering or V-sync equilavent for Vulkan

### ISSUE THREAD

**Issue by DelghLay** [yuzu-emu/yuzu#7310]
Feature Request: Double buffering, Triple buffering or V-sync equilavent for Vulkan.

This one will helps to reduce frame skipping to create a more smooth playing experience and the most important thing, reduce excesive screen tearing.
OpenGL has his own exclusive OpenGL V-sync into Yuzu Emulator, why Vulkan couldn't have something similar.

Forcing v-sync from Nvidia Control Panel doesn't solve those problems.

Thanks you all folks!

**Comment by BreadFish64** [comment]
Vulkan by default uses a "mailbox" swapchain which is equivalent to triple buffering. If that mode isn't available then it uses "immediate" mode which is the same as V-Sync off.

**Comment by DelghLay** [comment]
Sorry i'm ignorant but, there is no way to add an option to always force double or triple buffering on Vulkan? (like Cemu).
Sometimes 60 FPS native games displays as if they were less than 60 fps (losing image smoothness) at the same time that Yuzu shows me 60 fps locked of performance, this doesn't occur on OpenGL (i know, sounds strange).
This problem is not related to shader cache compilation or PC performance problems, the only partial solution i've found is activate Rivatunner's Scaleline Sync at 60 FPS + to run Yuzu's Vulkan, but this mess up OpenGL, it's a bit annoying enable and disable constantly that.

**Comment by Squall-Leonhart** [comment]
Believe this is closeable now?
