### ISSUE TITLE
Yuzu mainline crashes since version 768 

### ISSUE THREAD

**Issue by Yohan050** [yuzu-emu/yuzu#7312]
Hi, since the version 768, Yuzu don't to start on my system.

I waited a few weeks thinking there would be a fix, but nothing has changed.
I checked and reinstalled Yuzu, but there were no more changes.

According to the Windows event log, it is ntdll.dll and/or gdi32full.dll that crashes when yuzu.exe starts. With version 767 I have absolutely no problem. But if I run the latest Yuzu version in Windows Sandbox or a virtual machine, it starts normally.  And the cmd version manages to start, the emulation starts with the sound but the screen remains black or blinks and does not react to the commands of my controller. So I don't understand.

According to the changelog for version 768, the changes were fixes for memory leaks and a version update for QT.

I even tried compiling Yuzu myself, but the error is still the same with ntdll or gdi32full.
 
Everything leads me to think that it could come either from the new version of QT, or from a conflict with another process on my machine.

Here is my configuration:

Windows 10.0.19043.1320
I7-5820K
32 GB RAM
GTX 960 4 GB pilot version 496.49

Here are the event log logs:
```
Faulting application name: yuzu.exe, version: 0.0.0.0, time stamp: 0x61697941
Faulting module name: ntdll.dll, version: 10.0.19041.1288, time stamp: 0xa280d1d6
Exception code: 0xc00000fd
Fault offset: 0x000000000002d19a
Faulting process id: 0x1ad8
Faulting application start time: 0x01d7c1f7a4ebc739
Faulting application path: C:\Users\yves\AppData\Local\yuzu\yuzu-windows-msvc\yuzu.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 2345d320-eb5d-4a13-970d-16ce5ebac2ab
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Faulting application name: yuzu.exe, version: 0.0.0.0, time stamp: 0x618a7b3e
Faulting module name: gdi32full.dll, version: 10.0.19041.1110, time stamp: 0xb24bb404
Exception code: 0xc00000fd
Fault offset: 0x0000000000005ae5
Faulting process id: 0x2174
Faulting application start time: 0x01d7d5d10d5e8a63
Faulting application path: C:\Users\yves\AppData\Local\yuzu\yuzu-windows-msvc\yuzu.exe
Faulting module path: C:\WINDOWS\System32\gdi32full.dll
Report Id: 2e2a646d-f5c2-4541-abb8-1eb0a273fbd7
Faulting package full name: 
Faulting package-relative application ID: 
```
And here is the log of yuzu-cmd:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7509664/yuzu_log.txt)

Hoping it might help find the root of the problem.

**Comment by german77** [comment]
Have you tested with yuzu.exe?

**Comment by Yohan050** [comment]
Yes. Yuzu instantly crashes when I want to run it and produces these two reports.
[Lof gdi32full.txt](https://github.com/yuzu-emu/yuzu/files/7509984/Lof.gdi32full.txt)
[Log ntdll.txt](https://github.com/yuzu-emu/yuzu/files/7509985/Log.ntdll.txt)

**Comment by G-Spawn** [comment]
Please reopen issue if it persists on a fresh windows install & latest yuzu versions. It sounded like something went awry with your windows setup atm.
