### ISSUE TITLE
Memory Leak on Brilliant Diamond with OpenGL

### ISSUE THREAD

**Issue by ibrokemypie** [yuzu-emu/yuzu#7331]
On Yuzu early access 2196, Yuzu suffers from a huge memory leak in Pokemon Brilliant Diamond on opengl mode. The memory leak doesn't seem to occur in Vulkan. Memory usage seems stable for about 15 minutes then starts climbing until eventually Yuzu is OOM killed after using all the remaining memory (increases by about 4GB before this happens). This occurs with both  GLSL and SPIR-V, and still occurs after deleting the opengl shader cache entirely.

System specs:
i7 4770k
16GB ram
rx 6600xt
Arch Linux

Log (stopped emulation before Yuzu was killed, but after memory balloned by >3GB)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7533282/yuzu_log.txt.old.txt)

**Comment by CaptV0rt3x** [comment]
We don't support piracy - leaked games. Please wait until the game is officially out and dump it from your console if you desire support.
