### ISSUE TITLE
Diablo 2 Resurrected In Game Texts

### ISSUE THREAD

**Issue by retta1** [yuzu-emu/yuzu#7333]
![Screenshot_7](https://user-images.githubusercontent.com/53008113/141678165-d4466631-24be-4054-ae3c-424087b6e307.png)
Texts are not shown
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7533591/yuzu_log.zip)

**Comment by SpecialDarkwolf999** [comment]
this works fine on ryu so we are missing texture formats on yuzu to get this working.

**Comment by SpecialDarkwolf999** [comment]
[  33.071348] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CC200000 bytes
[  33.071559] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CC000000 bytes
[  33.071562] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CBE00000 bytes
[  33.071563] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CBC00000 bytes
[  33.071564] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CBA00000 bytes
[  33.071565] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CB800000 bytes
[  33.071566] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CB600000 bytes
[  33.071567] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CB400000 bytes
[  33.071568] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CB200000 bytes
[  33.071569] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CB000000 bytes
[  33.071570] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CAE00000 bytes
[  33.071572] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CAC00000 bytes
[  33.071573] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CAA00000 bytes
[  33.071574] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CA800000 bytes
[  33.071575] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CA600000 bytes
[  33.071576] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CA400000 bytes
[  33.071577] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CA200000 bytes
[  33.071578] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size CA000000 bytes
[  33.071579] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C9E00000 bytes
[  33.071580] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C9C00000 bytes
[  33.071581] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C9A00000 bytes
[  33.071582] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C9800000 bytes
[  33.071583] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C9600000 bytes
[  33.071584] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C9400000 bytes
[  33.071585] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C9200000 bytes
[  33.071586] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C9000000 bytes
[  33.071587] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C8E00000 bytes
[  33.071588] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C8C00000 bytes
[  33.071589] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C8A00000 bytes
[  33.071590] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C8800000 bytes
[  33.071591] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C8600000 bytes
[  33.071592] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C8400000 bytes
[  33.071593] Kernel <Error> core\hle\kernel\k_page_table.cpp:SetHeapSize:863: Could not reserve heap extension of size C8200000 bytes

with opengl

**Comment by gidoly** [comment]
afaik this issue is fixed. but if it is not case feel free to reopen issue.
