### ISSUE TITLE
[Crash] Random memory leak in Pokemon Brillant Diamond

### ISSUE THREAD

**Issue by Schneitizel** [yuzu-emu/yuzu#7334]
Hello to all!

I tried to play Pokemon Brilliant Diamond twice, and both times, the emulator froze and crashed
At that time, the memory of the System Commit was exceeded in one go, and went from 16Gb used to ~26Gb
It did it to me the first time when I wanted to visualize which pokeball had which starter, and there, at the beginning of a fight against a wild pokemon

Here is my configuration and the log

Yuzu version : EA 2198
CPU accuracy : Auto
Video API : Vulkan
Video accuracy : Normal
Resolution : x1
Window Adapting Filter : ScaleForce
AAM : None
Processor : Intel Core i5-7600K
GC : GeForce GTX 1070 8Gb
Memory : 2x8Gb
System Commit/Virtual memory limit : 24Gb 
Language : Frence

Tanks for your help!

[yuzu_log .txt](https://github.com/yuzu-emu/yuzu/files/7534089/yuzu_log.txt)

**Comment by G-Spawn** [comment]
We don't support leaks or piracy here @Schneitizel
