### ISSUE TITLE
Feature Request / Bug: Cheats that require "Hold L", "Hold R" don't seem to work

### ISSUE THREAD

**Issue by Eleiyas** [yuzu-emu/yuzu#7343]
Not sure if this is a bug or a feature to request, but after much fiddling around, I got cheats working for my game, but only ones that don't require button input. Anything that requires button input doesn't seem to work.

Example:

> `[Shiny Pokemon (HOLD L) 1.1]
> 040A0000 024685A8 54000720
> 040A0000 024685B8 54000820
> 80000040
> 040A0000 024685A8 14000045
> 040A0000 024685B8 14000041
> 20000000`

**Comment by CaptV0rt3x** [comment]
We don't support piracy - leaked games. Please wait until the game is officially out and dump it from your console if you desire support.
