### ISSUE TITLE
Pokémon Brilliant Diamond Graphic Error and two more

### ISSUE THREAD

**Issue by PKromt** [yuzu-emu/yuzu#7344]
Hello, I'm sorry for the late hour.
This is a user playing Pokemon Brilliant Diamond.
Battle graphics error and turn off while playing Pokemon Brilliant Diamond.
Update 1.1.0 version file is not installed either.
Please check when Pokemon Brilliant Diamond is officially released and correct it if it's a bug.

Thank you. Have a good day~

**Comment by CaptV0rt3x** [comment]
We don't support piracy - leaked games. Please wait until the game is officially out and dump it from your console if you desire support.
