### ISSUE TITLE
remain issue for Luigi's mansion 3

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#7350]
https://user-images.githubusercontent.com/66776795/142161344-1490e44e-af7b-4fc9-8ad3-7900e7621e32.mp4

there is 2 issue you can see here 
first is flickering lens flare issue on vulkan
second is flichering shadow infront of fire

log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7552824/yuzu_log.txt)

save to reproduce
[0100DCA0064A6000.zip](https://github.com/yuzu-emu/yuzu/files/7552831/0100DCA0064A6000.zip)
:

**Comment by dante3732** [comment]
Same on AMD RX Vega 64.

**Comment by SpecialDarkwolf999** [comment]
on vulkan & opengl errors :

Core.ARM core\arm\dynarmic\arm_dynarmic_64.cpp:InterpreterFallback:86: Unimplemented instruction @ 0x8B803D0 for 1 instructions (instr = E7FFDEFE)

Render.Vulkan video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:567: Incompatible types F32 and U32

Kernel core\hle\kernel\svc.cpp:MapSharedMemory:1248: Failed with result: 56321

Debug video_core/texture_cache/texture_cache.h:operator ():1853: Assertion Failed!
Unimplemented code!

**Comment by AnArcticPigeon** [comment]
Same issue here as of mainline 1377 on vulkan with a gtx 1060.
log:[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11051106/yuzu_log.txt)

**Comment by gidoly** [comment]
it is fixed on my end with lastest build feel free to reopen if happens on other system
