### ISSUE TITLE
Super Mario Odysset BSOD with Async Shaders On (Nvidia 496.76)

### ISSUE THREAD

**Issue by thethiny** [yuzu-emu/yuzu#7360]
I've been asked to post [the logs](https://github.com/yuzu-emu/yuzu/files/7559232/yuzu_log.txt.old.txt) as turning on Async Shaders is causing Stutters and BSOD and crashes in Yuzu when playing Mario Odyssey and an effect/animation plays (Example, putting the hat on an enemy). This issue was not present in Yuzu 808, it's new to Yuzu 813. Turning off Async Shaders fixes the issue.

[yuzu_log](https://github.com/yuzu-emu/yuzu/files/7559232/yuzu_log.txt.old.txt)

**Comment by german77** [comment]
fixed in #7629
