### ISSUE TITLE
[Pokemon BDSP] Crash at random/wild encounter

### ISSUE THREAD

**Issue by pacoa-kdbg** [yuzu-emu/yuzu#7365]
Yuzu EA: 2212
Game version : v.1.1.1
RTX 3080
16GB 
windows 11

Game crashes at any wild encounter each time,

openGL : it happens with GLSL and GLASM

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7566425/yuzu_log.txt.old.txt)

Save
[0100000011D90000.zip](https://github.com/yuzu-emu/yuzu/files/7566432/0100000011D90000.zip)

**Comment by FernandoS27** [comment]
hmn. What about mainline?

**Comment by pacoa-kdbg** [comment]
@FernandoS27 same result, with same output at log 


"[  57.550798] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl_gpu.cpp:ZBCSetTable:253: Avoiding passing null pointer to memcpy
[  57.604819] Debug <Critical> video_core\texture_cache\image_view_base.cpp:operator ():29: Assertion Failed!
Image view format S8_UINT_D24_UNORM is incompatible with image format B10G11R11_FLOAT"

**Comment by pacoa-kdbg** [comment]
Also with vulkan
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7566499/yuzu_log.txt)

**Comment by FernandoS27** [comment]
oh F*** why is that happening? that shouldn't happen!

**Comment by DeviousDream** [comment]
I tested that save, and got no problems on wild encounter. OpenGL - GLASM, 16x AF, GPU High, async GPU, 4x scaling, FXAA, Nearest, Fast GPU Time.

**Comment by pacoa-kdbg** [comment]
I found out how to avoid the crash, 
here are 2 videos showing the crash and how to WA it , also the log after the WA and doing some encounters
crash -> just encounter a wild pokemon on the left 
https://youtu.be/JjZ4N6v-eVU

no crash -> battle a trainer first, then go back to wild pokemons
https://youtu.be/HE6QeKeq-qg

Log after avoiding the crash
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7566639/yuzu_log.txt)

**Comment by pacoa-kdbg** [comment]
Will close this issue as seems to be solved on yuzu EA 2215 (https://github.com/yuzu-emu/yuzu/pull/7368)

**Comment by CrusadingNinja** [comment]
Issues should be kept open until the relevant PR is merged into master
