### ISSUE TITLE
Front-End QoL: Button size changing with text content

### ISSUE THREAD

**Issue by thethiny** [yuzu-emu/yuzu#7366]
This is not a bug nor a feature request, it's a QoL request.
At the bottom of the emulation screen, if you click on any of the buttons with text, it cycles through them one by one. However if you cycle to another one that has less words, then the button becomes smaller, and you end up pressing on another button by accident. Probably padding / separator would be a good idea.
Example: Switching from AMD's FidelityFX filter to Nearest Neighbor by clicking on the right edge of the button.

**Comment by german77** [comment]
Padding could be added but we already have issues with this. As expected we have too much stuff going on there.
![image](https://user-images.githubusercontent.com/5944268/142516852-fdfcdfe1-1fe0-4759-aad1-deac3e3be4e6.png)

**Comment by german77** [comment]
A better solution would be to have smaller text than AMD Fidelity super resolution... "AMD FSR" then add a constant width

**Comment by thethiny** [comment]
That would also work. The purpose is to have a consistent button width.
