### ISSUE TITLE
[Pokemon BDSP][Vulkan] Crash at pokemon battle

### ISSUE THREAD

**Issue by pacoa-kdbg** [yuzu-emu/yuzu#7370]
Yuzu EA: 2215
Game version : v.1.1.1
RTX 3080
16GB
windows 11

This crash only happens on vulkan
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7567687/yuzu_log.txt.old.txt)

Let me know if there are any dev settings to enable to generate a better log

BD save
[0100000011D90000.zip](https://github.com/yuzu-emu/yuzu/files/7567731/0100000011D90000.zip)

**Comment by FernandoS27** [comment]
Could you upload a save?

**Comment by pacoa-kdbg** [comment]
> Could you upload a save?

Done 👍

**Comment by FernandoS27** [comment]
Does not seem to crash on latest EA or i ahve the wrongsave.

**Comment by pacoa-kdbg** [comment]
Doesnt seem to crash for me anymore,
~1 hour without crashes on 2234 
Should this be closed or leave until merged changes to mainline ?

**Comment by pacoa-kdbg** [comment]
Issue is not present on mainline 834
