### ISSUE TITLE
NSPs with FS entry offsets outside of the total NCA length cannot be decrypted

### ISSUE THREAD

**Issue by CrusadingNinja** [yuzu-emu/yuzu#7371]
Ruined King: A League of Legends Story cannot boot due to the emulator unable to decrypt the file.
This also applies to Last Stop, Lost in Random, No More Heroes 3 (eShop dump), and Hextech Mayhem: A League of Legends Story.

Narr confirmed with me that this is a known issue and is being looked into but for archival purposes and to keep track of it I open this issue.

Mainline 815
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7568203/yuzu_log.txt)

**Comment by Djipi71** [comment]
Update : EA 2865 - Same problem Lost in random and others aren't find due to encrypt NSP

**Comment by CrusadingNinja** [comment]
This also affects the eshop dumps of Bayonetta 3 and Splatoon 3.

**Comment by Djipi71** [comment]
EA 3266 : Same result games are not decrypt....
