### ISSUE TITLE
[Vulkan] G-sync stopped working with Yuzu on Vulkan after 812 but still works with OpenGL

### ISSUE THREAD

**Issue by Ameer2002** [yuzu-emu/yuzu#7373]
Yuzu and G-sync have always worked till after 812 version. Changing any setting does nothing, except switching to OpenGL. G-sync works everywhere else on my computer, including Dolphin Emu's Vulkan API. My monitor has a built in frame counter which shows when G-sync is working as well as Nvidia's own tool to check, and both confirm it is not active with Vulkan.

I had this exact bug occur on Cemu a while back, and the developers were able to fix it. It was the exact same set of behaviours, with it being a Vulkan issue only.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7570155/yuzu_log.txt)
![Vulkan](https://user-images.githubusercontent.com/94689221/142622176-e9267805-72c4-42b0-a10a-bf68f06453d0.jpg)
![OpenGL](https://user-images.githubusercontent.com/94689221/142621927-b9a83d0a-8254-4eff-a1fe-cda90b70f8a5.jpg)

System Specs:
i7 8700k
GTX 1080Ti
32GB DDR4 
Windows 10 21H2

**Comment by benderscruffy** [comment]
Please close
No update
