### ISSUE TITLE
Motion controls only working on first controller (using original Pro Controllers), and cease to work on reconnect

### ISSUE THREAD

**Issue by rubenjavier** [yuzu-emu/yuzu#7381]
Im using the latest yuzu on win10 64bits with two orginal swiych Pro controllers, and the motion controls only work on the first controller (the one that gets the first led on the left) also if the controller is disconnected an reconnected with yuzu opened, the buttons works but the motion controls cease to work until yuzu is closed completely, and the controller is set as the first (first led on the left), the same is true if the one controllers s disconnected and a second is connected to continue playing, tested with Mario Odyssey and Zelda BotW
Thanks in advance
Best regards

**Comment by german77** [comment]
Latest yuzu is not clear enough. Please mention the number.

**Comment by rubenjavier** [comment]
Hello,
Mainline Build - 224d7cae4

**Comment by german77** [comment]
are you on linux?

**Comment by rubenjavier** [comment]
Im on Win10 64bits, fully updated

**Comment by rubenjavier** [comment]
I have 2 more pieces of info for you:
.-I've tested the EA build 2228, the build also have this behaviour
.-The controller must be paired ideally before you start yuzu, so the controller, even the first one, get to SYNC as the first led on the left, if you disconnect and reconnect with yuzu already started, the the controllers can get a random led assigned and the gyro doesnt work. If you close yuzu, and re-start yuzu, then the controller change its led to the first one on the left

My conclusion is that the correct assignement only happens wen yuzu start and check for controllers, posteriors connections and reconnections dont assign the controller correctly and the led (controller number) is random, loosing the gyroscope.

Also a controller connected after yuzu started, show a left stick drift

Thanks in advance
Best regards

**Comment by rubenjavier** [comment]
check-in update, Ive tested the most recent version to date EA 2321 (december 18 2021) and the issue is still happening, if the controller is not connected before yuzu starts, the motion controls doesn't work
thanks in advance
best regards
