### ISSUE TITLE
Arcaea handheld mode display is cut off.

### ISSUE THREAD

**Issue by jheelme** [yuzu-emu/yuzu#7382]
When Arcaea is changed to Handheld mode, some of the damage in the ratio is cut off like picture.
Once this problem is resolved, I am willing to purchase EA immediately.
Please fix it.
※ Please understand the translator.
(https://user-images.githubusercontent.com/85222692/142703519-70292624-db56-478a-ab21-ed611466e5bd.png)
</font>![화면 캡처 2021-11-20 082433](https://user-images.githubusercontent.com/85222692/142703519-70292624-db56-478a-ab21-ed611466e5bd.png)
</font>

**Comment by G-Spawn** [comment]
Like asked on the discord please post a log when you can

**Comment by jheelme** [comment]
I reinstalled yuzu and tried running it again with Nvidia, but it still looks cut like a picture.
OpenGL and Vulkan all show the same symptoms
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7574341/yuzu_log.txt)
.

**Comment by OrionGamerCat** [comment]
I'm also facing the same issue on my NVIDIA Arch Linux install and the AMD Steam Deck. 
I've attached the log file below. 

![Screenshot_20221231_021439](https://user-images.githubusercontent.com/31542793/210120727-bbd2aeb0-9ea2-4585-9bd8-1aa0f87371fb.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10326656/yuzu_log.txt)

**Comment by lisiyaki** [comment]
same issue for me too
![image](https://user-images.githubusercontent.com/77812141/217433188-a2c163dc-d8ae-4713-92ed-ff72f883f849.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10681636/yuzu_log.txt)

**Comment by dumcatt** [comment]
did anyone find a fix for this?

**Comment by Abbentai** [comment]
Yeah turns out i have the same issue as well on the windows build, tried both OpenGL and Vulkan rendereds, same issue happens on both 
![image](https://github.com/yuzu-emu/yuzu/asset
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12705984/yuzu_log.txt)
s/104551802/ffcad64f-8a9d-40f0-bee1-172e1aa32612)
