### ISSUE TITLE
Problems in control config?

### ISSUE THREAD

**Issue by jvhellraiser** [yuzu-emu/yuzu#7383]
I have no idea what's going on but this is what i see.
![Screenshot 2021-11-19 195133](https://user-images.githubusercontent.com/16488761/142705344-1ee29c7c-1505-4ce2-8329-52eeafb95635.png)

Yuzu EA 2223

Windows 11 
Nvidia 2060 RTX
4K monitor at  3840 x 2160

**Comment by G-Spawn** [comment]
the issue is typically usage of high dpi or scaling in windows

**Comment by jvhellraiser** [comment]
i already lower the resolution on Yuzu to 720p/1080p and it still has the same issue.

**Comment by vonchenplus** [comment]
DPI does not refer to the resolution, if you are a Windows10, you can change it through display settings.

**Comment by 0jsg** [comment]
It looks the same on my system. I've never seen it presented any other way, so I assumed it was just a weird screen. Do you have a screenshot of how it is supposed to look?

**Comment by german77** [comment]
This is not a resolution problem. It's a windows font scaling + big window size. This PR aims to fix the issue https://github.com/yuzu-emu/yuzu/pull/4949 but needs some edge case handling. 

In any case this is how it's supposed to look
![image](https://user-images.githubusercontent.com/5944268/154991002-5fbc20cc-7453-4513-b62e-5c34d5f232b4.png)
