### ISSUE TITLE
Dragon Quest Builders bugs

### ISSUE THREAD

**Issue by NineKain** [yuzu-emu/yuzu#7385]
![image](https://user-images.githubusercontent.com/72826232/142729020-fb1b2de7-fe52-408f-83b5-35f04471a2e7.png)
weird lines everywhere

**Comment by NineKain** [comment]
![image](https://user-images.githubusercontent.com/72826232/142729069-41400cba-df79-4122-af07-b97411a92164.png)
menus and the game in general it's pretty broken (there should be a tree branch on the red arrow)

**Comment by NineKain** [comment]
![image](https://user-images.githubusercontent.com/72826232/142729090-50fa4f20-f0b0-4c62-8d66-d4d165f81506.png)
broken menus

**Comment by NineKain** [comment]
![image](https://user-images.githubusercontent.com/72826232/142729135-b8fca9bb-5625-47c6-8e11-6eea549ecc07.png)
going fullscreen crashes the game too

**Comment by benderscruffy** [comment]
please close
no update

**Comment by NineKain** [comment]
Update, the game now doesnt have as much problems, but menus dont work correctly, so you cant load your saved game
