### ISSUE TITLE
Super Smash Bros. Ultimates - Freeze during stage loading

### ISSUE THREAD

**Issue by abi-21** [yuzu-emu/yuzu#7386]
It also crashes during gameplay but this log is currently for freezing problem.
Had to upload to gdrive since log is about 100mb.
https://drive.google.com/file/d/1tR7UuGdIGEBcspIj5Em4Ue2ZKjW6NR9t/view?usp=sharing

**Comment by G-Spawn** [comment]
Closing in favour of https://github.com/yuzu-emu/yuzu/issues/6163

**Comment by abi-21** [comment]
@G-Spawn Not an expert or anything, but are you sure both logs link to same issue?
Log files seems bit different on quick check.
