### ISSUE TITLE
SMT V castle zone stuttery despite high fps

### ISSUE THREAD

**Issue by NineKain** [yuzu-emu/yuzu#7387]
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7574809/yuzu_log.txt.old.txt)

FPS counter its about 50-70 but this area in particular is crazy stuttery, savegame for reference.
[010063B012DC6000.zip](https://github.com/yuzu-emu/yuzu/files/7574811/010063B012DC6000.zip)

**Comment by NineKain** [comment]
Can confirm that the Temple of Eternity has the same issue, they are similar built places

**Comment by gidoly** [comment]
can you verify if it is fixed with yfc part 1?

**Comment by NineKain** [comment]
Not really, I had to wipe my hdd and redumping the whole game its too much of a pain

**Comment by benderscruffy** [comment]
Please close
No update
