### ISSUE TITLE
[Linux/mesa-specific] DOA-X3 missing hair, eyes and skybox

### ISSUE THREAD

**Issue by Channeira** [yuzu-emu/yuzu#7390]
## Description

Tested same settings and hardware on both Windows 10 and Fedora 35 (tested using mesa 21.2.2, 21.2.5 and mesa-git).

Different Accuracies, Scales or AA filters did not show a difference.

Spec: RX6800 (RDNA2), 32GB RAM

## mesa 21.2.5 and mesa-git

![grafik](https://user-images.githubusercontent.com/45535201/142743080-320481ec-5135-4be9-ac67-64eeb9e7604f.png)

## Same hardware & settings: Windows

![grafik](https://user-images.githubusercontent.com/45535201/142743086-87ce2b23-5feb-413c-872b-c9680d5c0e97.png)

**Comment by Channeira** [comment]
Updated mesa to latest stable `21.2.2 -> 21.2.5`. The issue are still reproduciable.

**Comment by Mershl** [comment]
The issue can be reproduced on latest `mesa-git` as well as on the Steam Deck (tested on 512GB model, latest SteamOS).

**Comment by Channeira** [comment]
The issue can be reproduced on latest `mesa-git` as well as on the Steam Deck (tested on 512GB model, latest SteamOS).

**Comment by Channeira** [comment]
As requested by Lord @goldenx86 a log with `Enable Graphics Debugging` and Vulkan Validation Layers enabled on latest mainline-master.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9591275/yuzu_log.txt)

**Comment by Channeira** [comment]
The issue is reproduciable on latest yuzu-stable (1337) and mesa-git (53283bc2).

**Comment by Channeira** [comment]
The issue is reproduciable on latest yuzu-stable (1437) and mesa-git (dabc5289).

**Comment by Channeira** [comment]
I'd like to report this to mesa but without requiring them to setup a yuzu environment. I've used gfxreconstruct and renderdoc for these usecases before though with Yuzu I'm facing two show stoppers so far.

gfx reconstruct: The capture is created and the first frame can be replayed. Continuing further causes a GPU hang and crashes the replay.
renderdoc: the captures only contain a baked command buffer call and the very last color pass - presenting the finished frame. The interesting bits are missing.

Are there better tools available for yuzu, or compatibility modes in yuzu available that allow the usage of those tools?

**Comment by Channeira** [comment]
Created: https://gitlab.freedesktop.org/mesa/mesa/-/issues/9187

The latest mesa main commits also started crashing on DOA-X3 (I could not reproduce this crash in any other game).
On startup (tested with yuzu clean install as well) it shows:
```
[   3.150511] Frontend <Info> yuzu/main.cpp:BootGame:1934: Booting game: 01009CC00C97C000 | DEAD OR ALIVE Xtreme 3 Scarlet (64-bit) | 1.0.6
[   3.155000] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:LoadVulkanPipelineCache:826: Loaded Vulkan driver pipeline cache: 
[   3.155127] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:LoadDiskResources:526: Total Pipeline Count: 4
[   3.155196] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:587: 0x244de737d416ae09
[   3.155218] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:587: 0xd1d71374dbefbc2b
[   3.155219] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateGraphicsPipeline:587: 0xfed108e4e97219da
[   3.155227] Render.Vulkan <Info> video_core/renderer_vulkan/vk_pipeline_cache.cpp:CreateComputePipeline:720: 0x0910a9f2422af0b4
Unhandled SIGSEGV at rip 0x00007ee48175cf0c
```

**Comment by Channeira** [comment]
https://github.com/yuzu-emu/yuzu/commit/fcfa8b680b6aedd4b51757d4e33e97ef2cdae048
seems to fix this issue completely. I'll continue testing and close the issue once confirmed.

**Comment by Channeira** [comment]
Upstream fix is also available in mesa fixing the issue for older yuzu versions (funny that it happened right around the same time).

**Comment by Channeira** [comment]
@liamwhite https://github.com/yuzu-emu/yuzu/commit/fcfa8b680b6aedd4b51757d4e33e97ef2cdae048 fixed this issue (confirmed in mainline 1658), but the issue was reintroduced somewhere between mainline 1659 and mainline 1663).

**Comment by liamwhite** [comment]
Yes the reason is because of #12467
The solution I gave is not correct to our shader compiler because it requires 8 clip distances in multiple locations. I need to fix the UB that is caused instead.
