### ISSUE TITLE
[Feature Request] Add support for Skyline modding framework

### ISSUE THREAD

**Issue by jam1garner** [yuzu-emu/yuzu#7392]
Spinning this off from #6076 as it's unspecific and doesn't provided any technical details about what it'd entail.

### Motivation

[Skyline](https://github.com/skyline-dev/skyline), for those who aren't familiar, is a framework for modifying the code of games. It acts as a subsdk (overriding subsdk9, as no current game uses it) and uses a plugin system in order to allow users to load their own code, and provides an API for users to patch existing game code in order to redirect into user re-implementations of functions.

It's desirable to support due to its usage across a variety of games, most notably Smash Ultimate, which requires it to do [any serious patching of game files](https://github.com/Raytwo/ARCropolis), but it is also the framework used for moveset edits among other things. It's also been used some in the {Animal Crossing New Horizon, Pokemon SwSh/BdSp, Spelunky, etc} modding scenes, and other developers seem to be showing interest in it. (For example Pokemon Mystery Dungeon has shown interest but needs emulator support first: https://github.com/tech-ticks/hyperbeam/issues/3#issuecomment-967349620)

### Outstanding Issues

* **SVC Support**
  * [x] Support `MapProcessMemory` SVC
    * Implementation status: https://github.com/yuzu-emu/yuzu/pull/7519
  * [x] Support `UnmapProcessMemory` SVC
    * Implementation status: https://github.com/yuzu-emu/yuzu/pull/7519
  * [x] Support `CreateCodeMemory` SVC
    * Implementation status: https://github.com/yuzu-emu/yuzu/pull/7519
  * [x] Support `ControlCodeMemory` SVC
    * Implementation status: https://github.com/yuzu-emu/yuzu/pull/7519
  * [x] Support `SetProcessMemoryPermission` SVC
    * Implementation status: https://github.com/yuzu-emu/yuzu/pull/7394  
* **CPU Emulation Level Support**
  * [x] Support Instruction Cache Clearing
    * Seems to be mostly implemented as it's implemented in dynarmic (See https://github.com/merryhime/dynarmic/pull/562), just requires a `InstructionCacheOperationRaised` callback be implemented for yuzu's [`DynarmicCallbacks64`](https://github.com/yuzu-emu/yuzu/blob/f178a8ef0ce1ba602b0c857ed5993880a74d6a69/src/core/arm/dynarmic/arm_dynarmic_64.cpp#L29) to actually handle the cache clear, which shouldn't be too hard as `parent.InvalidateCacheRange(...)` should do the trick.
    * Implementation status: https://github.com/yuzu-emu/yuzu/pull/7407
* **IPC Service Support** 
  * [x] Atmosphere's [`pm:info` extension](https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/components/modules/pm.md#extensions), notably `AtmosphereGetProcessId`
    * This is decently easy, and such an implementation could effectively just return a constant due to the application being the only real concept of a process under yuzu. The only input actually of interest to Skyline is `0xFFFF8001`, Atmosphere's Program ID assigned for getting the current process' Process ID. The hardcoded process ID it could return for the application should then be usable with the SVCs mentioned before (`MapProcessMemory`, `UnmapProcessMemory`, `SetProcessMemoryPermission`)
    * Implementation status: https://github.com/yuzu-emu/yuzu/pull/7393
  * [x] Atmosphere's [`pm:dmnt` extension](https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/components/modules/pm.md#ipc-commands)'s [`AtmosphereGetProcessInfo`](https://github.com/Atmosphere-NX/Atmosphere/blob/77fe5cf6f574a0df4198015af672acfad4b88acb/libraries/libstratosphere/source/pm/pm_ams.c#L47-L72)
    * Similar to `GetProcessId`, Skyline only cares about the special `0xFFFF8001` handle, which is used to the process info for the current process. Skyline uses this to get a handle to the current process.
    * Implementation status:  https://github.com/yuzu-emu/yuzu/pull/7847
* **Loader**
  * [x] Load `subsdk`s properly (e.g. support `subsdk8` and `subsdk9`) 
    * Implementation status: https://github.com/yuzu-emu/yuzu/pull/7523 
* **Misc**
  * [ ] Debugging Skyline and ensuring no other functionality is missing/dysfunctional in Yuzu
    * Status: Blocked on yuzu debugging, ~~see [comment by tech-ticks below](https://github.com/yuzu-emu/yuzu/issues/7392#issuecomment-1038082570)~~ undocumented memory issue
    * Note: may result in finding additional issues to be added above 

### Next Steps

~~I'm willing to provide some development time to help with the above implementation, but would appreciate guidance/thoughts first, in order to avoid submitting non-trivial PRs without being sure they'd be excepted.~~

~~I'm also willing to provide help for any Yuzu developers on the Skyline end of things, as I'm certainly not asking for Yuzu devs to have to debug skyline code.~~

Update: I do not have time or resources to dedicate at this time. I'm doing my best to keep this thread updated but my organizational/PR help is done for the time being.

**Comment by FernandoS27** [comment]
@jam1garner hi jam if you need help with this we can do this tomorrow. feel free to contact me on discord:

@Morph1984 has implemented some so you have a base guideline on how to proceed.

you can contact me at: Blinkhawk#2544 on discord

**Comment by TheHomerOfSteel** [comment]
I hope you will finish this
I'm too excited to play all the mods on yuzu :)

**Comment by Applemaster21** [comment]
I just want to say thank you for doing this. Even if this never sees the light of day or isn't ever completed fully, taking the time out of your day to do something like this is amazing. Everyone who contributed to this project is awesome :)

**Comment by rafamariofan** [comment]
I really wish success to this project, I wish I knew how to help.

Having skyline on emulators will be revolutionary to smash bros modding, specially as hacked switches are getting harder to get each day.

**Comment by Rafario448** [comment]
I really wish success to this project, I wish I knew how to help.

Having skyline on emulators will be revolutionary to smash bros modding, specially as hacked switches are getting harder to get each day.

**Comment by kir-alt** [comment]
I really hope this can be finished! Practicing SSBU on a emulator would be cool

**Comment by NiQR1** [comment]
I really hope this can be finished! Modding SSBU on a emulator would be cool.

**Comment by NiQR1** [comment]
you guys got this good job! I cant wait too mod smash ultimate!

**Comment by JulesBarbe** [comment]
I am in no way a good enough programmer to help with this project, but I'm following your with the utmost curiosity. The potential of eventually having access to the training mod on yuzu could completely change the competitive scene for the better.

**Comment by cykeswiki** [comment]
Any further updates on this? I noticed that most (if not all, according to tech-ticks' post) of the prerequisites are ready to go, so is it just a matter of backend testing we're not privy to?

**Comment by LazerSmith** [comment]
this is amazing. ive been wanting this for awhile now

**Comment by PrinceBubloo** [comment]
> I am in no way a good enough programmer to help with this project, but I'm following your with the utmost curiosity. The potential of eventually having access to the training mod on yuzu could completely change the competitive scene for the better. 

@bunnei is looking into it,
It will be done soon

**Comment by PrinceBubloo** [comment]
> Any further updates on this? I noticed that most (if not all, according to tech-ticks' post) of the prerequisites are ready to go, so is it just a matter of backend testing we're not privy to?

@bunnei is looking into it, so its in good hands.
It will be done soon hopefully

**Comment by rings2006** [comment]
i hope this all works out, good luck to everyone

**Comment by NicholasR18** [comment]
Hey so if you can send me the stuff you have been working on I can have my dad help he's worked at Microsoft for 20 years now and codes daily I think I can get him to help

**Comment by Ruther92** [comment]
Hi! There is any update?

**Comment by nsragow** [comment]
I'd be happy to contribute, want to get this done

**Comment by JoeBudson** [comment]
Any updates on this?

**Comment by Wfree86** [comment]
Hey folks if you need someone to test this let us know. If someone wrote up a test case I'm willing to help out.

**Comment by FerLuisxd** [comment]
Hello? Any updates on this?

**Comment by p-victor** [comment]
Everything for skyline seems ready I think. Is it time to close this issue @bunnei  @tech-ticks ?

**Comment by PrinceBubloo** [comment]
Which comment, last comment is 7 months old

**Comment by p-victor** [comment]
Yes and the comment states that the previous issue (which if I understand correctly is the last remaining) is no longer an issue for skyline.

**Comment by jam1garner** [comment]
> Yes and the comment states that the previous issue (which if I understand correctly is the last remaining) is no longer an issue for skyline.
> 

"Skyline loads but is not working" doesn't tell one anything except that loading non-sequential subsdks works, not anything regarding skyline itself working.

**Comment by abi-21** [comment]
Is this still being worked on?

**Comment by FearlessTobi** [comment]
Fixed.
