### ISSUE TITLE
Crash on transitions (mprotect failed: Cannot allocate memory)

### ISSUE THREAD

**Issue by bograt** [yuzu-emu/yuzu#7397]
The emulator is consistently crashing at certain cutscenes/loading screens of certain games. Previously, I've been able to workaround these issues, but I cannot get it working for SMT V. I get similar results with OpenGL and Vulkan and with different graphics settings. It crashes with a bunch of these errors:

`[  92.169728] Debug <Critical> common/host_memory.cpp:operator():426: Assertion Failed!
mprotect failed: Cannot allocate memory`

`[  92.190877] Debug <Critical> common/host_memory.cpp:operator():405: Assertion Failed!
mmap failed: Cannot allocate memory`

and

`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc`

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7575746/yuzu_log.txt)

Yuzu release: Development Build (2021-11-21) which I upgraded to while trying to troubleshoot.
OS: Arch Linux
Display server: XOrg
CPU: AMD Ryzen 5700G
GPU: Integrated (Vega 8)
RAM: 64GB

If there's any other info you need, I can provide it since I can reliably reproduce this crash at certain cutscenes. I bet it's just my crappy iGPU... :pensive:

**Comment by Moonlacer** [comment]
That's not a crappy iGPU, that's the best one there is :P

**Comment by G-Spawn** [comment]
This is expected issue for now or output on linux for smtv until emu improvement comes. Windows gets it's own memory related issues.

**Comment by FernandoS27** [comment]
uhm you are running out of virtual memory. Hmn

**Comment by bograt** [comment]
> That's not a crappy iGPU, that's the best one there is :P

Haha that's why I bought it, but the best iGPU is still an iGPU. It'll do until 6900s come back to msrp.

> uhm you are running out of virtual memory. Hmn

I don't have any swap on this system. Should I add some?

**Comment by G-Spawn** [comment]
It can help but even with one set users have same issue in that game for now.

**Comment by v1993** [comment]
Current workaround is to use

```bash
sudo sysctl -w vm.max_map_count=262144
```

**Comment by bograt** [comment]
@v1993 
Thanks! That got it working. What exactly does this do? Pass a kernel parameter to limit virtual memory?

**Comment by v1993** [comment]
Please reopen this issue, since it's a valid yuzu bug. Said command increases maximum count of memory mappings that can be used by process at once. SMTV somehow hits that limit, possibly by extreme memory fragmentation.

**Comment by Gakomi** [comment]
> Current workaround is to use
> 
> ```shell
> sudo sysctl -w vm.max_map_count=262144
> ```

Man you are a life saver, I've been searching for a fix from the moment the game got released, thought it was something like this but I had no idea how to incress the maximum count. Also I think it might be related to having no swap cause just like bograt I have no swap set either !

**Comment by rujiel** [comment]
I was still getting this issue after setting sysctl. Strangely I had to edit /etc/sysctl.conf directly because the setting wouldn't last after restart.

**Comment by v1993** [comment]
> Strangely I had to edit /etc/sysctl.conf directly because the setting wouldn't last after restart.

For the record - it isn't strange, that's exactly what's supposed to happen.

**Comment by SViN24** [comment]
yes this also happened to me (SMT V on Fedora silverblue)
My hardware is a Ryzen 5 5600X with an RX560 4GB and 16GB of ram
Thank's v1993 for the solution yeah this is not supposed to ever happen

**Comment by bunkbail** [comment]
Had a similar issue on Bravely Default II, spent hours searching for a fix, the sysctl workaround finally did it for me.
