### ISSUE TITLE
[Windows][Vulkan] Sometimes, particle effects stop being casted correctly (Pokémon Brilliant Diamond v1.1.1)

### ISSUE THREAD

**Issue by LOuroboros** [yuzu-emu/yuzu#7401]
**Version of Yuzu**: EA 2232
**Details**: I brought this up in **[one of my 2 previous Issue tickets](https://github.com/yuzu-emu/yuzu/issues/7377)**.
I asked if I should make a new Issue ticket or not almost a full day ago, but since I didn't get a response, I figured the previous Issue ticket got brushed off as just the battle background getting glitchy and decided to open this one for the problem with the particle effects.

The problem can be seen in the video I uploaded on that same ticket at 00:37, when the wild Chansey uses Tail Whip, however, **[I also recorded a video on EA 2226](https://github.com/yuzu-emu/yuzu/issues/7377#issuecomment-974661436)**, and I recorded another one for this Issue ticket using EA 2332 as well.

https://user-images.githubusercontent.com/4485172/142763936-54066dab-2c55-4b50-8f5b-9da1bd976d87.mp4

For reference, this is how a stat debuff animation should look like, see this wild Staravia's Growl:

https://user-images.githubusercontent.com/4485172/142730992-dd7e83d8-d380-4eba-bf02-d66f02eb63c2.mp4

As it can be inferred from the video above, the issue doesn't always happen. Sometimes you can boot up the game and have a couple of battles without glitches, but sooner or later *(at least in my experience)*, you'll notice the particle effects are no longer casted on the screen correctly.

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7576340/yuzu_log.txt)

**Comment by FernandoS27** [comment]
I'm looking into that. It seems to only happen on Vulkan.

**Comment by NineKain** [comment]
Can confirm, buffs and debuffs dont render correctly on Vulkan

**Comment by LOuroboros** [comment]
I think there's a good chance this has been fixed in the past 2 days. I've been playing Brilliant Diamond using EA 2238 for about 20 minutes, and I haven't noticed this problem with the particle effects anymore.
Heck, I haven't even had Yuzu crash on me yet, which is pretty darn cool too.

I'm not closing the ticket yet, in case you want to add any info or confirm this @FernandoS27.

**Comment by LOuroboros** [comment]
Closing this, see: https://github.com/yuzu-emu/yuzu/issues/7536#issuecomment-997042053
