### ISSUE TITLE
Luigi's mansion 

### ISSUE THREAD

**Issue by DragonsFear** [yuzu-emu/yuzu#7402]
after the latest EA build (2232), Luigi's mansion crashes before the game loads 

in previous builds the game still worked without issues

**Comment by teozan** [comment]
Same for me. With the 3x mods (save fix, 60 FPS and disable ynamic res) it worked like a charm before the last release and managed to gt up to the 9th floor level. Now it loads but stops at the intro (new game) or while loading the saved data. I did not change the  graphical config of course (open GL, etc). I'm on a NVIDIA 1650. Maybe the changelog gives an idea but I'm not a developer...

**Comment by SpecialDarkwolf999** [comment]
on vulkan & opengl errors :

Core.ARM <Error> core\arm\dynarmic\arm_dynarmic_64.cpp:InterpreterFallback:86: Unimplemented instruction @ 0x8B803D0 for 1 instructions (instr = E7FFDEFE)

Render.Vulkan <Error> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:567: Incompatible types F32 and U32

**Comment by G-Spawn** [comment]
Please reopen issue if this still happens to you & try to provide a log file. LM3 has been stable with mods for quite some time now.
