### ISSUE TITLE
yeah. your pussy emu freezes all the fucking time

### ISSUE THREAD

**Issue by gorxk** [yuzu-emu/yuzu#7408]
Yuzu  latest numbfuck number. freezes all the fucking time: metroid dread. and pokemon  diamond.
16 gigs of ram. Ryzen 5
1 shit ton of space.
GeForce 16606
I've probably lost 4 hours because you assholes can't or won't fix fucking bugs and drag this carcus to the finish line. And for it to stop
being gay and fucking work, and fucking work titty fucking well.

Now hurry up and fix the fucking problems asswhipes.

**Comment by german77** [comment]
We can't accept this issue.

**Comment by lioncash** [comment]
![yeah](https://user-images.githubusercontent.com/712067/142799974-d3175edb-3c30-47ac-a64a-7f9127ea19a7.jpg)

**Comment by gorxk** [comment]
https://giphy.com/gifs/aww-bfd-ACEWc4xcm2B1u
