### ISSUE TITLE
Massive FPS drop between release 820 and 822

### ISSUE THREAD

**Issue by Infinality** [yuzu-emu/yuzu#7413]
Was getting mostly 60FPS in Link's Awakening using Vulkan with 2x / bilinear / FXAA on build 820.  Builds 821 & 822 reduce this to under 30FPS.  I reverted to 820 and the issue went away.  Perhaps this is known by devs already but I wanted to report in case this wasn't known.

EDIT:  Running Windows 10 with Nvidia RTX 2060.
EDIT 2:  Regression only seems to happen under "high" GPU setting.

**Comment by v1993** [comment]
Given changelog of those revisions, this seems to be linked to changes in #7396. @FernandoS27 Can you investigate?

**Comment by Infinality** [comment]
Maybe unrelated, but every since the resolution scaling release, BOTW is no longer playable for me at 60FPS, no matter the factor (.5x .75x 1x 2x etc).  Basically tried changing every setting inculding rendering backends, buffering in nvidia control panel, etc.

**Comment by german77** [comment]
Can you try on mainline 823 there was a issue fixed by blink

**Comment by Infinality** [comment]
Another important point:  If I set the GPU to "normal" on 823, the FPS goes back up to around 60.  However GPU "high" on 820 doesn't suffer this issue.  So it appears whatever the regression was shows up only under "high" GPU setting.

**Comment by FernandoS27** [comment]
> Another important point: If I set the GPU to "normal" on 823, the FPS goes back up to around 60. However GPU "high" on 820 doesn't suffer this issue. So it appears whatever the regression was shows up only under "high" GPU setting.

are you using the 60 fps stable mod?

**Comment by Infinality** [comment]
Yes, the one from the official mod page for BOTW.

**Comment by FernandoS27** [comment]
> Yes, the one from the official mod page for BOTW.

I'm talking of Link's Awakening.

**Comment by Infinality** [comment]
Ah, crap I got confused.  Yes, I'm using that one:

![image](https://user-images.githubusercontent.com/1253650/142965687-43cc5683-be45-495e-b213-f407a44288ee.png)

**Comment by Infinality** [comment]
![image](https://user-images.githubusercontent.com/1253650/142966021-3ccf2dd9-a4bb-497e-b127-7ebcf3742986.png)

**Comment by Infinality** [comment]
FWIW, I've noticed that particularly with the newest nvidia driver that yuzu will display that it is rendering at 60 FPS when it clearly isn't.  I get this in Metroid Dread, Odyssey, and others.  I'm guessing that is the fault of the driver.

**Comment by kitzik** [comment]
I've got 15FPS in BOTW in the latest Yuzu versions (GTX 1066). Toggling from fullscreen to the windowed mode and back again to the fullscreen fixes my FPS. Probably it has to be done multiple times.

**Comment by v1993** [comment]
There have been some fixes to suspected part of code recently. Can you retest, please?

**Comment by Infinality** [comment]
So, with 827, it appears the issue is still there.  I'm still getting between 30 and 50 fps with "high" gpu setting.  If I change to undocked mode, it seems to go back to 60 fps (but I don't like using that as it produces other visual issues.)

**Comment by Infinality** [comment]
Issue appears to be fixed with 828!
