### ISSUE TITLE
Black Screen Pokemon Shining Diamond

### ISSUE THREAD

**Issue by PyrDeus** [yuzu-emu/yuzu#7424]
Yuzu 2218
The screen does not display the game (black screen), but it displays when you are in the menu and the dialog boxes work fine. The music plays during the blackscreen too.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7588808/yuzu_log.txt)

**Comment by Norstyrm** [comment]
You're running the 1.0.0 version of the game, which does not have cutscenes in it at all. Use the latest version of the game

**Comment by PyrDeus** [comment]
The issue is the same with the last update 1.1.1.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7589412/yuzu_log.txt)

**Comment by german77** [comment]
The yuzu version is also too old. use latest EA or mainline.

**Comment by Norstyrm** [comment]
Also we don't support piracy, as is evident in the log

**Comment by G-Spawn** [comment]
Closing for reasons above. Dump all of your files from your nintendo switch if you desire support here or in the forums - discord.
