### ISSUE TITLE
Pokémon BDSP, sometimes battle backgrounds break

### ISSUE THREAD

**Issue by Jaizu** [yuzu-emu/yuzu#7425]
Latest Early Access.
Pokémon Brilliant Diamond 1.1.1

After some attack animations or after sending a shiny Pokémon the battle background breaks once it gets reset with another attack animation. 
![image](https://user-images.githubusercontent.com/18596778/143070266-2fe67842-fc21-4992-9ae1-ee0c35411b64.png)

**Comment by G-Spawn** [comment]
Would you mind posting a log as well for good measure?

**Comment by Jaizu** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7610288/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7610289/yuzu_log.txt.old.txt)

**Comment by G-Spawn** [comment]
We don't support piracy here sorry. Dump all your files from your console then feel free to make a support request.
