### ISSUE TITLE
[Windows][Vulkan] Sometimes, corruption-like(?) visual effects can appear on the screen (Pokémon Brilliant Diamond v1.1.1)

### ISSUE THREAD

**Issue by LOuroboros** [yuzu-emu/yuzu#7426]
**Version of Yuzu**: EA 2238
**Details**: I've been testing out EA 2238. The game seemed to be running perfectly fine and no longer displayed any weird issues such as **[the one I reported with the move animation and Poké Balls particles](https://github.com/yuzu-emu/yuzu/issues/7401)**, until I noticed that I had the Internal Resolution increased.
Since the game was stuttering quite a bit every now and then when I had it set to 2x *(probably because my poor GPU can't handle resolutions above 1080p safely)*, I decided to save the game, restart Yuzu and set the IR back to 1x.

After I did that though, I had the problem with the particles happen one time, and now... this. I don't even know how to describe it 🤣 ...
It's as if a virus was injected inside the game's world or something. Of course, it's a mere visual glitch.

https://user-images.githubusercontent.com/4485172/143074698-aae9305e-a257-4856-bf27-5b00bc28cc88.mp4

As I was finishing the battle to save the game, exit and upload the log here, I noticed that the font vanished completely.
It's as if something was effectively being corrupted pretty badly.
![yuzu_2215](https://user-images.githubusercontent.com/4485172/143075001-da4f5209-8f0e-4866-a03b-5de8c102c6a3.png)

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7590029/yuzu_log.txt)

Save:
[SaveData.zip](https://github.com/yuzu-emu/yuzu/files/7590054/SaveData.zip)

**Comment by LOuroboros** [comment]
I think this has happened to me again? I was moving on bike in Route 213 using the EA 2316 when from one moment to another, this started to happen out of nowhere.

https://user-images.githubusercontent.com/4485172/146235475-808e2b26-ede0-48f0-9114-7274bef92e3d.mp4

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7721347/yuzu_log.txt)

**Comment by LOuroboros** [comment]
Closing this, see: https://github.com/yuzu-emu/yuzu/issues/7536#issuecomment-997042053

**Comment by FernandoS27** [comment]
you have way too little ram. Just the RAM you have is what the switch itself uses, pretty much forces all our systems to their limits.

You'll need 8Gb atleast. Can't you upgrade RAM? It shouldn't be hard/costy.

**Comment by LOuroboros** [comment]
> you have way too little ram. Just the RAM you have is what the switch itself uses, pretty much forces all our systems to their limits.
> 
> You'll need 8Gb atleast. Can't you upgrade RAM? It shouldn't be hard/costy.

I can't. Not at this point in time. As I said many times by now, I am perfectly aware of how weak my hardware is and that the fact I was able to run games reliably *(on the NVIDIA GLASM renderer anyway)* at all was purely a miracle.

Thank you.
