### ISSUE TITLE
Apply Button Bug

### ISSUE THREAD

**Issue by Begueiro** [yuzu-emu/yuzu#7427]
So, after using an older version of yuzu for a few days, I decided to get the latest release (v823) and set it up. I noticed there's a new button (at least, compared to the version I had) in the Configuration panel, the Apply button, and it is quite convenient, so, thanks for that.

Now, the thing is I noticed that my emulation was pausing, on window inactivity, even though the option to do so was unticked. Ticking it had the opposite effect as well, it would cause the emulation to continue, on window inactivity.

What happened was that I used the Apply button to change that setting and it did save the checkbox state, but the change didn't actually take effect in the software.
I don't know if this bug affects anything else, as I wouldn't know how to check, but it's possible this oversight extends to other settings. It doesn't affect the RTC setting, that one works fine, at least. 😁

**Comment by heinermann** [comment]
I'm not able to reproduce this in ee76b546d

**Comment by german77** [comment]
I haven't seen these issues recently. Reopen if it still happens
