### ISSUE TITLE
F6 (Restart) will crash yuzu

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#7429]
BUG:

1. set View > Fullscreen + Single Window Mode
2. run a game
3. press F6 to restart

yuzu will close/crash (Italian Windows report):

```
Nome dell'applicazione che ha generato l'errore: yuzu.exe, versione: 0.0.0.0, timestamp: 0x619cf259
Nome del modulo che ha generato l'errore: yuzu.exe, versione: 0.0.0.0, timestamp: 0x619cf259
Codice eccezione: 0xc0000005
Offset errore 0x00000000002443be
ID processo che ha generato l'errore: 0x69a8
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d7e121d37d4ee1
Percorso dell'applicazione che ha generato l'errore: C:\Users\Luca\Yuzu\yuzu.exe
Percorso del modulo che ha generato l'errore: C:\Users\Luca\Yuzu\yuzu.exe
```

I use fullscreen mode = exclusive in general config.
yuzu-windows-msvc-20211123-abd99b2af

_Gaming laptop ASUS GL703GS, Win 10, i7-8750H (6+6 cores), NVidia 1070 8GB, 32GB RAM, 1920x1080 144Hz G-Sync laptop screen, NVMe + SSD_

**Comment by Hexaae** [comment]
BTW, no Hotkey works when in Fullscreen (exclusive) + Single Window Mode OFF.

**Comment by NineKain** [comment]
Happens to me too always, at least on SMTV
