### ISSUE TITLE
Crash on quit after switching Single Window Mode + Fullscreen ON/OFF

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#7430]
BUG:

1. set View > Fullscreen (and disable Single Window Mode), and run a game
2. quit with ALT+F4, since no hotkey is working...
3. set View > Single Window Mode (and disable Fullscreen), and run a game
4. quit emu with F5
5. set View > Fullscreen ON + Single Window Mode ON
6. quit yuzu (Exit from menu)

A silent crash by Qt5Gui.dll will be logged in Windows Event Viewer, e.g. (Italian Windows report):
```
Nome dell'applicazione che ha generato l'errore: yuzu.exe, versione: 0.0.0.0, timestamp: 0x619cf259
Nome del modulo che ha generato l'errore: Qt5Gui.dll, versione: 5.15.2.0, timestamp: 0x5fa4ddbb
Codice eccezione: 0xc000041d
Offset errore 0x00000000000439b3
ID processo che ha generato l'errore: 0x4a70
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d7e1274e019ced
Percorso dell'applicazione che ha generato l'errore: C:\Users\Luca\Yuzu\yuzu.exe
Percorso del modulo che ha generato l'errore: C:\Users\Luca\Yuzu\Qt5Gui.dll
```
I use fullscreen mode = exclusive in general config.
yuzu-windows-msvc-20211123-abd99b2af

_Gaming laptop ASUS GL703GS, Win 10, i7-8750H (6+6 cores), NVidia 1070 8GB, 32GB RAM, 1920x1080 144Hz G-Sync laptop screen, NVMe + SSD_

**Comment by benderscruffy** [comment]
Please close
No update

**Comment by Hexaae** [comment]
Ok. Unreproducible anymore on recent builds. Closed.
