### ISSUE TITLE
[Windows][Vulkan] RAM Consumption is bigger when using the Vulkan renderer compared to the OpenGL one

### ISSUE THREAD

**Issue by LOuroboros** [yuzu-emu/yuzu#7434]
**Version of Yuzu**: EA 2241
**Details**: I'm noticing a considerable difference in the amount of RAM consumed by Yuzu, depending on which renderer it's using.
During battles at Pokémon Brilliant Diamond for example, Vulkan seems to hog around 1.3-1.6 GB of my RAM.
Meanwhile, when Yuzu uses the OpenGL renderer and the GLASM Shader Backend, it doesn't eat even 1.
![yuzu_2261](https://user-images.githubusercontent.com/4485172/143490137-9429f7f8-f807-420b-b7d1-e57f3c4f68b9.png)
![yuzu_2262](https://user-images.githubusercontent.com/4485172/143490953-41c3078b-a5fb-485b-b3bc-c57d01c99cae.png)

My settings haven't changed for the most part since **[my last Issue tickets](https://github.com/yuzu-emu/yuzu/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+author%3ALOuroboros)**.
I assume the logs I dropped in them track my Yuzu settings nicely.

What I did was to set GPU to Normal instead of High, and I also disabled the Disk Pipeline Cache.
I wanted to see what effect those had in the gaming experience with my hardware.
I don't think it's too relevant to mention this, but right now, with those 3 changes *(GPU Normal, Disk Pipeline Cache Disabled and NVIDIA GLASM instead of Vulkan)*, I'm getting a much smoother experience compared to before.

Here's 2 logs.
The first one was generated by me booting up the game with Vulkan, running around and doing a couple of battles before shutting down Yuzu.
The second one is the same, but using NVIDIA GLASM instead.
[yuzu_log_nvidia.txt](https://github.com/yuzu-emu/yuzu/files/7605146/yuzu_log_nvidia.txt)
[yuzu_log_vulkan.txt](https://github.com/yuzu-emu/yuzu/files/7605147/yuzu_log_vulkan.txt)

**Extra note**: It's rather funny, but it feels like the more time I keep playing, the *less* resources Yuzu consumes?
Right now I'm still playing BDSP, before generating those logs. and the consumption of RAM by Yuzu's process has gone down from around 900MB to about 510MB, as far as Windows' Task Manager reports.
![yuzu_2266](https://user-images.githubusercontent.com/4485172/143492743-218ea7ac-9733-4b7d-89be-738f5d0af376.png)

This is some pretty cool magic trick guys. I don't know how or why is this happening, but I sure like it lol 🤣

**Comment by RinMaru** [comment]
Vulkan using more memory is normal afaik

**Comment by LOuroboros** [comment]
> Vulkan using more memory is normal afaik

Oh, alright then. I wasn't sure so I just reported it in case it wasn't. I'll leave the confirmation and closing o the ticket to a mantainer or a developer of the project then.

**Comment by LOuroboros** [comment]
Slightly relevant. On EA 2252, the NVIDIA renderer is now taking as much RAM as the Vulkan renderer, around 1.5 GB.
I suppose it wasn't intentional though?

**Comment by LOuroboros** [comment]
Closing this, see: https://github.com/yuzu-emu/yuzu/issues/7536#issuecomment-997042053
