### ISSUE TITLE
 Animal Crossing: New Horizons - Corrupted text selection on Passport Menu

### ISSUE THREAD

**Issue by RemnantDrive** [yuzu-emu/yuzu#7436]
When accessing the Passport for the first time, the disclaimer window letting the player know that this information can be seen by other players has a corrupted 'yes' selection. Does not impact functionality.

![01006f8002326000_2021-11-25_19-42-44-057](https://user-images.githubusercontent.com/79406880/143511115-0e9765b8-ebda-4f0c-bcbe-ed244d7b3b60.png)

Yuzu 826
Vulkan
Windows 10
RTX 3080, driver version 496.13
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7605646/yuzu_log.txt)

**Comment by RemnantDrive** [comment]
Additionally, corruption can be seen on the brown "Resident stamp" on the regular screen, as well as other selection items in the Passport app on the Nookphone.

**Comment by G-Spawn** [comment]
please provide a log file as well when you can.

**Comment by RemnantDrive** [comment]
Log attached to main post.

**Comment by RemnantDrive** [comment]
On further research, this issue is identical to the issue opened here: https://github.com/yuzu-emu/yuzu/issues/7292

To add: The corruption happens indoors (in Tom Nook's tent) as well.

**Comment by german77** [comment]
Duplicated of  #7292
