### ISSUE TITLE
[Windows][Vulkan] Reflections indoors can get glitchy during extended gaming sessions (Pokémon Brilliant Diamond v1.1.1)

### ISSUE THREAD

**Issue by LOuroboros** [yuzu-emu/yuzu#7437]
**Version of Yuzu**: EA 2241
**Details**: After playing for a couple of hours, I noticed when I entered the Trophy Garden that... the reflections inside of the building I'm guessing, got glitchy.
Thankfully, restarting Yuzu solved it, but I figured I should report it since it's an issue and it probably shouldn't happen.

The log makes reference to some unimplemented stuff in `video_core/texture_cache/texture_cache.h`, so maybe that'd solve it?
I know little to nothing about actual programming, so I've no idea.

Glitchy:
![yuzu_2279](https://user-images.githubusercontent.com/4485172/143518381-d3ab20c9-baf9-4eeb-8473-f12f9a1949c7.jpg)

How it's supposed to look:
![yuzu_2280](https://user-images.githubusercontent.com/4485172/143518845-01772ac1-7634-496e-a6ca-5e9abe69af3e.jpg)

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7605941/yuzu_log.txt)

Save:
[0100000011D90000.zip](https://github.com/yuzu-emu/yuzu/files/7605994/0100000011D90000.zip)

**Comment by GitMooseNC** [comment]
I'm experiencing the exact same problem. It's like some static background image that doesn't move. v1.1.1, vulkan on a mobile RTX 2060, 472.12 drivers. Same yuzu EA version.
.

**Comment by zeff9801** [comment]
Same happened to me but i wasn't inside any building so i don't think it's related to that
Rx 480 latest drivers

**Comment by GitMooseNC** [comment]
Don't know if it's related, but with the latest EA build 2249, entire application crashes after a few minutes. I honestly don't know how to read the majority of stuff on the coding side so I'm not able to check for myself if some fix had been implemented for the gfx issue and it accidentally caused the crash issue.

**Comment by LOuroboros** [comment]
Closing this, see: https://github.com/yuzu-emu/yuzu/issues/7536#issuecomment-997042053
