### ISSUE TITLE
Puyo Puyo Tetris no longer goes in game on latest master

### ISSUE THREAD

**Issue by bunnei** [yuzu-emu/yuzu#744]
Boot Puyo, try to go in game in "Tetris" mode. The game softlocks.
Bisecting, we see the first bad commit is 29aff8d5 (VFS).
@DarkLordZach cc

**Comment by Subv** [comment]
This seems to work with Multicore on, and is fixed by #638
I'd say this is one of those cases where things just worked by chance.

**Comment by Hexagon12** [comment]
This issue is fixed.

Requesting to close.
