### ISSUE TITLE
Flatpak 829 missing dependency or a different version needed for ffmpeg?

### ISSUE THREAD

**Issue by Githob2021** [yuzu-emu/yuzu#7448]
I updated Yuzu flatpak to 829 and when I click the icon in my KDE task manager it does nothing now.

When I try to run it via terminal it says:
flatpak run org.yuzu_emu.yuzu
bwrap: Can't mkdir /app/lib/ffmpeg: Read-only file system
error: ldconfig failed, exit status 256

I checked the dependency and I have it, but it may be a different version other flatpaks are using. Yuzu was working fine in the previous flatpak version.

flatpak list --runtime
ffmpeg-full     org.freedesktop.Platform.ffmpeg-full         21.08              system

**Comment by Githob2021** [comment]
I also updated Flatseal to 1.7.5 today so that could be the issue too as it is talking about a "Read only file system". However I tried playing with permissions in Flatseal and had no luck.

**Comment by liushuyu** [comment]
Hi there, please report Flatpak-specific issues to https://github.com/flathub/org.yuzu_emu.yuzu/issues.

> [...]
> When I try to run it via terminal it says: flatpak run org.yuzu_emu.yuzu bwrap: Can't mkdir /app/lib/ffmpeg: Read-only file system error: ldconfig failed, exit status 256
> 

I can't seem to reproduce this issue on my system.

> I checked the dependency and I have it, but it may be a different version other flatpaks are using. Yuzu was working fine in the previous flatpak version.
> 
> flatpak list --runtime ffmpeg-full org.freedesktop.Platform.ffmpeg-full 21.08 system

The new version added a new requirement for `ffmpeg-full`, version `21.08`.

**Comment by Githob2021** [comment]
> Hi there, please report Flatpak-specific issues to https://github.com/flathub/org.yuzu_emu.yuzu/issues.
> 
> > [...]
> > When I try to run it via terminal it says: flatpak run org.yuzu_emu.yuzu bwrap: Can't mkdir /app/lib/ffmpeg: Read-only file system error: ldconfig failed, exit status 256
> 
> I can't seem to reproduce this issue on my system.
> 
> > I checked the dependency and I have it, but it may be a different version other flatpaks are using. Yuzu was working fine in the previous flatpak version.
> > flatpak list --runtime ffmpeg-full org.freedesktop.Platform.ffmpeg-full 21.08 system
> 
> The new version added a new requirement for `ffmpeg-full`, version `21.08`.

I downgraded Flatseal so that wasn't what is breaking it. I will try downgrading Yuzu next.

From the flatpak list --runtime you can see i Have 21.08 installed so that should be fine.

**Comment by Githob2021** [comment]
> Hi there, please report Flatpak-specific issues to https://github.com/flathub/org.yuzu_emu.yuzu/issues.

Sorry I didn't know about that. We can close this ticket here.

**Comment by Githob2021** [comment]
I downgraded to 827 and it works again. I will just mask Yuzu for the time being.
