### ISSUE TITLE
Vulkan: Graphics card is not displayed

### ISSUE THREAD

**Issue by Menemey11** [yuzu-emu/yuzu#7449]
I have an Acer Nitro 5 an515-45 with an RTX 3060 and have the problem that no graphics card is displayed for Vulkan. A few minutes ago I was able to select my graphics card there and play with Vulkan, but now it no longer works. All my drivers are up-to-date, Windows is also up-to-date, but I still can't see my graphics card there.

https://ibb.co/yVWMRB8

**Comment by goldenx86** [comment]
Update the driver of your integrated GPU and both will show up.

**Comment by Menemey11** [comment]
My integrated GPU is an AMD Radeon (TM) and the Radeon software says that the driver is up to date.

**Comment by G-Spawn** [comment]
Closing as this isn't entirely a yuzu issue it is user hardware based. Please be sure to update your amd radeon drivers from your product website not windows device manager update. For your nvidia gpu you can go to product website as well to grab latest.
