### ISSUE TITLE
Website features

### ISSUE THREAD

**Issue by thethiny** [yuzu-emu/yuzu#7453]
The website's wiki does not update when the wiki gets updated.
Also please give us the option to add a game that's "Not Tested" into the gameDB, I'm pretty sure you can automate that since it's already automated.

**Comment by CaptV0rt3x** [comment]
The website is configured to update once per day. So you'll not immediately notice the results of your changes.

**Comment by thethiny** [comment]
> Coming to gameDB, we haven't been considering requests to add games to our db, as it is auto built using public titledb data. We might choose to do it in the future.

What about newly released games, aren't they in the public data? Please note that this is not sarcastic as it is a genuine question. My question is about Mario party and Wario ware as they're new but they remain Not Tested for a while.

**Comment by CaptV0rt3x** [comment]
@thethiny, unfortunately the gameDB automation seems to have not synced in the recent past. I've notified the dev and we'll sync the gameDB with the current public data, very soon. I hope that answers your questions.

**Comment by thethiny** [comment]
> You can do this by going into Help menu, and clicking submit compatibility while the game is running. Once you report compatibility, it'll show up on the website.
> 
> I hope that answers your questions.

Yes I'm already reporting my own compatibility reports but I was skeptical and afraid that I'm doing them for nothing, since there are no pages for them. Thanks and yes you did answer my questions.
