### ISSUE TITLE
Melty Blood Type Lumina - no sound effects, only music

### ISSUE THREAD

**Issue by tapperp** [yuzu-emu/yuzu#7457]
GAME: Melty Blood Type Lumina 01001E30126A0000

ISSUE: sound effects do not play, only music/FMV. This includes menu sounds, game sounds, voices etc.

Tested on various recent Yuzu builds including 831, using multiple PC's running Windows 10, with various hardware configurations. 1.04 update is applied and all DLC in NAND. Other games that seem to use a similar engine like BlazBlue Cross Tag do not have this problem.

Not sure a log will be useful for this issue? Thank you.

**Comment by Holo4life** [comment]
I have the same issue 
Did you know how to solve it?

**Comment by tapperp** [comment]
> I have the same issue Did you know how to solve it?

Update yuzu. They fixed it.
