### ISSUE TITLE
Pokemon Evolution Sequence Triggers the Invisible Box Glitch

### ISSUE THREAD

**Issue by DeviousDream** [yuzu-emu/yuzu#7458]
The infamous BD/SP invisible pokemon box glitch is seemingly caused by pokemon evolution,as of now EA 2252, has been happening for a while too. Attaching a save file with a bunch of magikarp ready to evolve and rare candies.

[SaveData.bin.zip](https://github.com/yuzu-emu/yuzu/files/7614115/SaveData.bin.zip)

**Comment by DeviousDream** [comment]
Seems like evolving pokemon that are already evolving in the dex didn't trigger it, but strangely I've been testing for a bit now and no matter what I do it doesn't happen again. I'm a bit baffled. Will update if I find anything else

**Comment by gidoly** [comment]
is this still happening with yfc part 1?

**Comment by gidoly** [comment]
closing due to being gitto with #7422
