### ISSUE TITLE
Random crashes in Pokemon BDSP Overworld due to "Image view format B10G11R11_FLOAT is incompatible with image format S8_UINT_D24_UNORM"

### ISSUE THREAD

**Issue by DeviousDream** [yuzu-emu/yuzu#7460]
In these random Pokemon BD/SP crashes, the last line of the log is always "Image view format [insert format here] is incompatible with image format S8_UINT_D24_UNORM". It happens most often while trying to fly to another place, but also pretty randomly while roaming around. One of these occurences is `[ 237.217136] Debug <Critical> video_core\texture_cache\image_view_base.cpp:operator ():29: Assertion Failed!
Image view format B10G11R11_FLOAT is incompatible with image format S8_UINT_D24_UNORM`

**Comment by DeviousDream** [comment]
This crash is quite frequent, this time instead of B10G11R11 it's about A8B8G8R8.
 `[ 237.217136] Debug <Critical> video_core\texture_cache\image_view_base.cpp:operator ():29: Assertion Failed!
Image view format A8B8G8R8_UNORM is incompatible with image format S8_UINT_D24_UNORM`

**Comment by gidoly** [comment]
close due to lack of log. feel free to open new issue with log attatched if problem persist.
