### ISSUE TITLE
Super Mario Odyssey Graphical Glitches (Cloud, Smoke ) [Vulkan]

### ISSUE THREAD

**Issue by iWeaker** [yuzu-emu/yuzu#7461]
It is through Vulkan the problem, in OpenGL it does not happen, but in the latest updates, the performance is fatal with OpenGL, I no longer get the stable 60fps as a few months ago.

PC
Ryzen 3 3300X 
16gb Ram 
GPU: NVIDIA GTX1060 
Driver 495.44
OS: Debian 11 + X.org 

Video demostration: 
https://www.youtube.com/watch?v=YYGCDugPOS4

**Comment by v1993** [comment]
Does this happen if you use nvidia drivers from 47x series? Newer ones are known to have issues.

**Comment by iWeaker4you** [comment]
> Does this happen if you use nvidia drivers from 47x series? Newer ones are known to have issues.

Thanks, its fixed with NVIDIA Driver 470.86 ...
maybe GBM support its bugged ? or that EGL is not being used correctly?

**Comment by v1993** [comment]
No, this is a known issue in nvida drivers that happens on windows too. They (nvidia guys) are working on fixing it.

**Comment by gidoly** [comment]
is this adressed?

**Comment by gidoly** [comment]
closed as no response and example video being deleted
