### ISSUE TITLE
Can't Input Japanese name on game that supports it in US version.

### ISSUE THREAD

**Issue by Maverynthia** [yuzu-emu/yuzu#7464]
Yuzu v. 827 (2021-11-26)

I'm playing Rune Factory 4 Special and have to use Yuzu as it seems to emulate it at the proper speed.
Upon name entry I put the Japanese in and "??????" comes up in confirm box. This is not an issue in other emulator/real game.
![MWSnap203](https://user-images.githubusercontent.com/2293000/143799579-7338abaf-6f9f-4e76-a6d9-d1491b951a55.png)

When I was playing this on Ryujinx before however I was able to input the name fine and have it display fine.
![MWSnap201](https://user-images.githubusercontent.com/2293000/143799622-50b5d309-e6b8-41c4-9597-082e8ea7d5d4.png)

Versus the reload of the save on Yuzu:
![010051d00e3a4000_2021-11-28_21-37-04-944](https://user-images.githubusercontent.com/2293000/143800063-7155d052-7c3a-49b2-8d95-0763fb16bc81.png)

What's going on? Is is a SHIFT-JIS vs UTF-8 issue? Or is the software keyboard broken some how? Is there a work around?

Things I've tried is saving it in Ryujinx with the proper name and copying the save file over and it will still display "??????" in the game. Is there some fonts missing in Yuzu?

**Comment by german77** [comment]
Can you upload a save with the correct name

**Comment by Maverynthia** [comment]
I found the solution when uhh... getting yuzu to auto install to where *I* wanted it to install and not on my C:\ Drive.

SOLUTION!
Make sure the Switch `firmware` (The one's Nintendo nags you about updating to before you can eShop)  files are where they need to be `nand\system\Contents\registered`

What had happened was that the nand files were in the AppData and of course now Yuzu wasn't looking there anymore.
Really wish I could install Yuzu where I wanted.

I will leave the solution here in case anyone else has the same trouble. (Instead of "I fixed it" and another user that needs help going "how?")
