### ISSUE TITLE
[Windows][NVIDIA] Glitchy textures (Shin Megami Tensei III: Nocturne HD Remaster)

### ISSUE THREAD

**Issue by LOuroboros** [yuzu-emu/yuzu#7468]
**Version of Yuzu**: EA 2254
**Details**: I booted up my savefile which I made sometime ago, interacted with an NPC, entered the room in Shinjuku Medical Center's Underground Facility where you can heal up, interacted with the NPC that does the healing, and when I left that room, I was met with this:
![yuzu_2393](https://user-images.githubusercontent.com/4485172/143875481-e690830e-acf5-4822-8844-4e005902a123.png)

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7618382/yuzu_log.txt)

Save:
[SaveData.zip](https://github.com/yuzu-emu/yuzu/files/7618385/SaveData.zip)

**EDIT**: It seems to happen consistently. I restarted Yuzu, loaded up the savefile, entered the room, spoke with the NPC and when I left the textures around got as glitchy as they are in the picture above.

**Comment by G-Spawn** [comment]
Thank you for the report. Closing in favor of existing issue however. https://github.com/yuzu-emu/yuzu/issues/4882
