### ISSUE TITLE
Super Mario Odyssey - Far from the "great" compatability listed on the compatability list.

### ISSUE THREAD

**Issue by INFINITY99K** [yuzu-emu/yuzu#7471]
**How did I know this?**
Ok, I played Super Mario Odyssey from start to finish twice one for the pure enjoyment of it and a 2nd one for the graphical glitches hunting and glitches I found let's start, shall we!
and a small note every issue present here is with all shader cache compiled and completed.

**Graphical Glitches**
- Some particles are not rendered correctly.
- Stutters are triggered by video sequences when they pop up.
- Stuttering in some specific areas when using res scaling and I need to note that I have a powerful CPU and I saw other people with 11th gen processors and 5th gen Ryzen having the same issue.
- Flickering.
- OpenGL stuttering issues.
So, let's start detailing them one by one, shall we?

edit: **System Specs**
- RTX 2070 SUPER.
- Ryzen 3700x.
- All tested using Vulkan unless said.

**Corrupted Particles!**
This can be easily spotted in Bowser's Kingdom all the particles should be moving but, for some reason some of them get stuck not moving while glitching and moving up and down, you could also see this in wooden kingdom though, not as clear but gonna explain it anyway, the pipes are supposed to show a fog effect the problem it behaves in the same exact way as the particles in other kingdoms and oh, sth to note here the game seems to exhibit this behavior on v1.0 more than on version 1.3.0.
Tested at Normal, High and extreme GPU Accuracy.

**Stutters triggered by video pop-up**
This is subtle actually this is the most subtle thing on this list you can notice that in Cascade Kingdom after you beat the boss and go to the odyssey a pop-up video will show up a tutorial on how to throw cappy that will trigger a stutter the first time you open the game and I need to note that this is with all shader cache compiled.
Tested using CPU Video Decoding and GPU Video Decoding.

**Stuttering when using res. scale**
This happens on any platform regardless of your CPU or, GPU a notable example is in the tutorial when - tested at 2x res scale(and higher) using a 2070 Super with a 3700X and 16GB Ram - when you throw cappy on a frog a 0FPS stutter is triggered another example is present when you finish the game and get 100% go to metro kingdom then, get behind major Pauline a 0FPS stutter is triggered another extremely notable example is when you open the menu in metro kingdom at 2x res scale or higher a 0FPS stutter is triggered another example is when you open mario's closet and it's pretty noticeable.
Tested using 2x res scale and 3x scale and 1440p ( Using Ultra Graphics mode undocked)

**Flickering**
When you open your save file after you launch a game a white or black flicker. Present on V1.0.0 only and I think it's supposed to show an applet on the top-right of the screen cause this is how it behaves in v1.3.0.
Tested on both Vulkan and OpenGL.

**OpenGL stutter**
When you open the game sound a 0FPS stutter when mario pops up on the screen and when the white thing pops up on the screen.
Tested on: GLSL, GLASM, SPIR-V

**Compatibility**
I think this should be reverted back to either Okay or Bad until issues above are fixed.

**Log File**
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7621588/yuzu_log.txt)

and this isn't like the issue no. #7461as this was tested on 47x.xx drivers.

edit: Working on editing some gameplay sequence to better demonstrate the issues and will post as soon as I finish them as they are quite long.

**Comment by Norstyrm** [comment]
Okay, there's several stuff here that should be looked into. Personally I haven't encountered any of these problems except for one which I know why happens, this issue being the "corrupted particles".

Now the reason this issue happens is because you're running the game with **Normal** GPU Accuracy, when for SMO's effects to render correctly it has to be set to **High**.

As for the other issues there could be serveral causes to these, but I'd advise you to reach out to yuzu's Discord server so they can be looked into. The server invite link is https://discord.gg/u77vRWY

Now as stated I haven't experienced the issues you've mentioned, and in my opinion I think the game is running great, or even perfectly fine. However if it's running bad currently then we can't manually change the status of a game, as it's based on user-submitted reports. Do hope you join the server so we could look into the issues you're having with the game!

**Comment by INFINITY99K** [comment]
At high they render better not correctly as they rather start fine then for a frame they get corrupted then they start out again that is why I mentioned it being subtle as opposed to when accuracy on normal as it was much worse and about those other issues I can send you the 100% save file you can test it out yourself and to be honest there's nothing here that I can consider '"severe" they are just some bugs I wanted to point out to move the game from Great compatibility to Perfect.

**Comment by INFINITY99K** [comment]
And small question cause am new to the Discord Channel where can I post this?

**Comment by Norstyrm** [comment]
> And small question cause am new to the Discord Channel where can I post this?

You can post them in the yuzu-support-windows channel. Just make sure you read and agree with the rules first so you get access to the rest of the channels if you can't see it

**Comment by INFINITY99K** [comment]
Thanks!

**Comment by gidoly** [comment]
close as it has more to do with support request.
