### ISSUE TITLE
Metroid Dread bug: firing and other actions underwater don't have dimmed sound

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#7473]
When Samus is underwater, original game on console plays fire sounds and other actions by Samus with a dimmed underwater effect, missing when playing through Yuzu. I hope will be implemented in the future...

**Comment by vasishath** [comment]
I can confirm this issue. The sounds are exactly the same while inside/outside water. Looks like an unimplemented DSP filter to  me.
