### ISSUE TITLE
Bombslinger [010087300445a000] doesn't detect any inputs on controllers or keyboard

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#7475]
Bombslinger [010087300445a000]
gets to the title screen and say press any button to start
doesn't detect any buttons on the controller or keyboard
so it is stuck on the title screen
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7622570/yuzu_log.txt)

**Comment by german77** [comment]
This game supports handheld and dual joycons in the switch.  Doesn't seem to detect any input on yuzu
