### ISSUE TITLE
[Windows][NVIDIA]The latest EA builds are crashing quite often

### ISSUE THREAD

**Issue by LOuroboros** [yuzu-emu/yuzu#7477]
**Version**: EA 2254 and EA 2256
**Details**: I'm experiencing crashes every now and then in Pokémon Brilliant Diamond, and they seem to have started around the EA 2254.
I think I experienced a total of 4 crashes today.
The first one was for a test I brought up in #7434.
The second one was after I saved the game after running around for a while to raise the friendship of one of my Pokémon.
The third one was like 30 minutes ago right after I defeated a boss *(Team Galactic Admin Saturn in Lake Valor)*.
The fourth and last one happened a couple of fights later. As I saved right before that fight, I had to repeat it, then I had 2 more battles in Lake Verity and then Yuzu crashed again.
 
Here's the log generated after that fourth crash which I experienced a couple of minutes ago.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7622845/yuzu_log.txt)

**EDIT**: I disabled Async GPU Emulation and Yuzu has been behaving nicely so far.

**EDIT2**: Nevermind. I alt+tabbed for a moment to type something on Discord as a battle against a wild Snover was starting, and then Yuzu crashed again.

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7623082/yuzu_log.txt)

**Comment by gidoly** [comment]
Your hardware is weaker then minimum spec that we recommand pls check https://yuzu-emu.org/help/quickstart/#hardware-requirements

**Comment by LOuroboros** [comment]
Fair enough. It was working just fine before though, that's why I reported it. Because the frequent crashing only started in one of the latest EA builds.

I went back to EA 2247 for example, and everything has been working nicely for the past hour since I last edited my post above.

If you want to close this ticket though, do go ahead.

**Comment by FernandoS27** [comment]
hmn this is interesting. Howe about mainline?

evenn though you are under min specs. We plan to expand to low spec devices, so it's important this is fixed.

**Comment by LOuroboros** [comment]
> hmn this is interesting. Howe about mainline?
> 
> evenn though you are under min specs. We plan to expand to low spec devices, so it's important this is fixed.

I've been trying out Yuzu 832 for over 2 hours and a half, and that's been working nicely too stability wise. No crashes.
I did come across **[an occasional visual glitch where the battle background went black when my Infernape used Flame Wheel every now and then](https://user-images.githubusercontent.com/4485172/144079116-eb147893-357c-4dae-a4e3-93229ba5d741.png)**, in case that's worth a mention.
It didn't happen consistently, and it only happened while I was in one of Team Galactic's buildings at Veilstone City.

Don't mind the framerate in those pictures. The game actually ran at 30 FPS all the time back then.
There *are* areas that are taxing, but that's probably because my hardware is underpowered, like for example the routes surrounding Pastoria City, so again, I'm fully aware that I probably shouldn't be using Yuzu and that it's already amazing enough that the game is running as well as it does on such a weak PC at all, so if my Issue tickets are deemed unfit, I will accept that and move on.

Here's the log, in case it's useful at all:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7626953/yuzu_log.txt)

Current savefile:
[0100000011D90000.zip](https://github.com/yuzu-emu/yuzu/files/7627039/0100000011D90000.zip)

**Comment by FernandoS27** [comment]
your title says that the crashes are "often" Does A. happened but less likely before? B. have you tried with Vulkan ?

**Comment by LOuroboros** [comment]
> your title says that the crashes are "often" Does A. happened but less likely before? B. have you tried with Vulkan ?

The crashes are "often" because there's plenty of them, and they happen often.

As I explained above, yesterday alone, I had like 4 crashes in total as I used EA 2254 and EA 2256.

> B. have you tried with Vulkan ?

Nope.
I've been avoiding using the Vulkan renderer for the most part since I noticed its high consumption of RAM compared to the NVIDIA renderer, see #7434.

I switched to it as I was testing different combination of settings in Emulation -> Configure -> Graphics, but I always ended up going back to my current settings with NVIDIA GLASM, no Disk Pipeline Cache and GPU Normal.

I can try to play for an hour or two using EA 2258 and the Vulkan renderer later today to see what happens.

**Comment by LOuroboros** [comment]
So, I've been testing the game on the EA 2260 using the Vulkan renderer for about 30 minutes, and I just had the game crash on me as I was exploring the market at Sunyshore City.
I ended up enabling Async GPU Emulation just in case, but I suspect I would have gotten a crash either way, just like I did in EA 2256 which I mentioned above in the main post of this ticket.

For whatever it's worth, I'm noticing RAM consumption in Vulkan has gone down quite a lot, so that's nice.
It used to be in the 1.5 GB of RAM area, but now it's in the 700-800 MB range instead.

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7630892/yuzu_log.txt)

**Comment by LOuroboros** [comment]
I tried out Mainline 834, and it crashed within 10-15 minutes of gameplay, so I'll keep sticking to either EA 2247 or Mainline 832 for now.

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7642363/yuzu_log.txt)

**Comment by bunnei** [comment]
@LOuroboros any updates here if you are still experiencing this issue in more recent mainlines?

**Comment by LOuroboros** [comment]
> @LOuroboros any updates here if you are still experiencing this issue in more recent mainlines?

Funnily enough, I've been testing out the latest mainline, Yuzu 840, for about 30-40 minutes now.

So far so good. I'll keep going for a while, but it feels like the crashes may have been solved.

**Comment by LOuroboros** [comment]
Closing this, see: https://github.com/yuzu-emu/yuzu/issues/7536#issuecomment-997042053
