### ISSUE TITLE
My Save Files Gots Corrupted, Please Repair the corrupt file 

### ISSUE THREAD

**Issue by this-is-praveen** [yuzu-emu/yuzu#7478]
I Had Renamed Extension Bin with ZIP 
My Computer gots hanged on restart there is issue in the drive, after that PKBD gots black screen on loading
I'm just completed 8th gym

I know it is support request, what I like is to uncorrupt the save file from yuzu
or merge the data into new save file

Kindly help me over this 

[SaveData.zip](https://github.com/yuzu-emu/yuzu/files/7623343/SaveData.zip)

**Comment by gidoly** [comment]
We don't have tool to repair saves.
Even if it is possible github issue is for document missing service, glitches, crashes of emulater. Not for support

**Comment by this-is-praveen** [comment]
No tools available for repair 🔢

**Comment by G-Spawn** [comment]
Can't fix broken 99% of the time.
