### ISSUE TITLE
Vulkan device not detected

### ISSUE THREAD

**Issue by Adri8863** [yuzu-emu/yuzu#7485]
<!---
Please keep in mind yuzu is EXPERIMENTAL SOFTWARE.

Please read the FAQ:
https://yuzu-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of yuzu you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

- Yuzu Vulkan device can't seem to detect both my gpu and intergradet gpu, it was there when I first launch my game, the second time it's just blank, I'm on an AMD laptop

**Comment by goldenx86** [comment]
Very descriptive.

**Comment by Adri8863** [comment]
Could've sworn I wrote it

**Comment by Adri8863** [comment]
Sorry first time commentting here, but the thing is my gpu and igpu isn't detected by vulkan, on a AMD laptop

**Comment by goldenx86** [comment]
99% of the time this happens when the integrated Vega GPU has an outdated driver. Manually install the latest one and it should be fixed.
Keep that installer, Windows Update has a tendency to love downgrading drivers at random recently.

**Comment by Adri8863** [comment]
So I have to update my I gpu drivers again? Okay, my nvidia is on the latest version

**Comment by INFINITY99K** [comment]
I just had the same issue recently just reinstall your drivers and restart your device it worked for me.

**Comment by Manaplayer** [comment]
Same problem with Nvidia 1050Ti and latest drivers (complete uninstall and reinstall)
For opengl yuzu says, there is no compatble devices (intel 630 (latest drivers) and Nvidia 1050Ti) are compatible with opengl 4.6 - gpu-z says. Only intel 630 with Vulkan can start a game.
