### ISSUE TITLE
Linux freezing on latest yuzu flatpak release

### ISSUE THREAD

**Issue by omanwhatiscomputer** [yuzu-emu/yuzu#7487]
The latest flatpak release freezes Ubuntu 21.04 (Gnome 3.38.5) system on yuzu launch. No error logs, no error messages, nothing. (forces manual system restart)

Version: mainline-0-834
System Specs: 
[Vulkan] AMD strix rx570 4GB
Ryzen r5 3600; 16 GB ddr4 ram

**Comment by liushuyu** [comment]
Hi there,

Please report Flatpak-specific issues to https://github.com/flathub/org.yuzu_emu.yuzu/issues/new.
Also, please include operating system details (which distro, which version, what display API are you using [e.g. X11/Wayland], which graphics driver are you using [e.g. ACO/AMDVLK]). You can obtain the information using `inxi -v4` (assuming you have `inxi` installed), and then try to __redact__ the unnecessary details (like serial numbers).
