### ISSUE TITLE
[Bugs/Crashes] Bravely Default II

### ISSUE THREAD

**Issue by Korr4** [yuzu-emu/yuzu#7496]
General info: 
-Specs: GeForce 2060, 32 GB ram, i59500k, SSD
-Yuzu latest build
-PC drivers all updated
-Nvidia overlay and RivaTuner Disabled
-No background apps opened, pc has been wiped recently

It has been a couple of days since I'm trying to make the game work. Note that I used both Jap and US version, the latter is classified as "good" on the compatibility list, and they present the SAME behaviour.
I have problems with both Vulkan and OpenGL. First of all, with both of them the logs keeps repeating, and never stops, this warning when I open the game:
"Kernel <Warning> core\hle\kernel\k_process.cpp:GetTotalPhysicalMemoryAvailable:179: capacity 3426447360 != application pool size 3444572160"

If I use Vulkan, after a couple of minutes, Yuzu simply crashes (there is no specific in-game action that triggers it) with a long series of these messages:
"HW.Memory <Error> core\memory.cpp:operator ():216: Unmapped ReadBlock"

If I switch to OpenGL then the game works, but it doesn't load the texture properly. See this image as reference [link](https://user-images.githubusercontent.com/83434355/116632577-e1b09280-a92d-11eb-893f-b7b8c8ca3072.png). It's not mine, but I have the exact (not figuratively speaking) same black spots around the map. Note that I tried also Ryujinx, which should also use OpenGL, and the same texture issue is there too.

Note that I tried to change the other options, but nothing seems to matter. Performance wise, until the game works, it runs perfectly with both Vulkan and OpenGL. Finally, there are plenty of older videos that show no problem running the game.

Here is the trimmed log when running Vulkan https://pastebin.com/QFwkdpyG

PS: the final lines before the readblock error starts are these:

[ 312.789075] Kernel <Warning> core\hle\kernel\k_process.cpp:GetTotalPhysicalMemoryAvailable:179: capacity 3426447360 != application pool size 3444572160
[ 312.793674] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.794146] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.795116] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.795580] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.798191] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.798884] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.802766] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.803246] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.804279] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.804759] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.805696] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.806240] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.808398] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.809000] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.911977] Kernel <Warning> core\hle\kernel\k_process.cpp:GetTotalPhysicalMemoryAvailable:179: capacity 3426447360 != application pool size 3444572160
[ 312.914145] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.914619] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 312.931234] Kernel <Warning> core\hle\kernel\k_process.cpp:GetTotalPhysicalMemoryAvailable:179: capacity 3426447360 != application pool size 3444572160
[ 312.940796] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:247: (STUBBED) called
[ 312.942303] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocFree:247: (STUBBED) called
[ 312.962286] Kernel <Warning> core\hle\kernel\k_process.cpp:GetTotalPhysicalMemoryAvailable:179: capacity 3426447360 != application pool size 3444572160

**Comment by G-Spawn** [comment]
Closing in favour of https://github.com/yuzu-emu/yuzu/issues/6828 to save duplicate issues. Hopefully this will be fixed in future .
