### ISSUE TITLE
BOTW calls some kind of abort function when the DLC is installed before it loads

### ISSUE THREAD

**Issue by MobSlicer152** [yuzu-emu/yuzu#7498]
As stated in the title, when I attempt to launch The Legend of Zelda: Breath of the Wild, yuzu hangs on the loading screen. The log seems to indicate that it calls some kind of abort function while it's loading the DLC. The full log is attached. I have been experiencing this issue for a few months now, and it occurs on every build of yuzu I've tried, which include building it from the GitHub repo, the mainline builds, the regular builds, and the Early Access build in the Arch User Repository (I tried the last one just to see if this issue had already been solved and I should just wait for the mainline branch to receive whatever changes fixed it). Any help with this is appreciated.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7654218/yuzu_log.txt)

**Comment by MobSlicer152** [comment]
The AUR early access build seems to work, but crash after launching, which I presume to be a driver issue that I intend to resolve.

**Comment by benderscruffy** [comment]
can be closed
