### ISSUE TITLE
No audio after sleep mode

### ISSUE THREAD

**Issue by SpeedFire0** [yuzu-emu/yuzu#7499]
This issue is easily reproducible.
When emulation is running I close the notebook. 
When notebook is opened and windows go out of sleep emulation continues to run fine except for sound (no sound at all).
I have to restart the game for sound to come back.

Is it possible to fix this? On some other emulators (for example Citra or Dolphin) sound returns to normal fine after sleep.

**Comment by liunice** [comment]
Yes I encountered this issue too!

**Comment by tbsp** [comment]
I am experiencing this as well.

**Comment by myyuan43** [comment]
I encountered this as well

**Comment by myyuan43** [comment]
and yuzu have no quick save funtion, this problem is annoyed.

**Comment by slovechki** [comment]
Did anyone found a workaround. This is highly annoying. In my case it not only not resumes after hybernation but if I switch TV off and on again the sound is gone 😔.

**Comment by liunice** [comment]
> Did anyone found a workaround. This is highly annoying. In my case it not only not resumes after hybernation but if I switch TV off and on again the sound is gone 😔.

change audio output engine to SDL2, not Auto.

**Comment by slovechki** [comment]
> 

Thanks @liunice, that partially worked. Now when I switch off/on TV - sound remains (though I haven't waited long between off/on).
After hybernation the sound is still not playing. Cemu didn't have this problem.

The only way around this is to use Windows Resource Manager and suspend yuzu processes before hybernation and resume after. However in some games you have to wait a while before you can resume after hybernation.

**Comment by slovechki** [comment]
Was hoping that pausing the emulation would solve the problem but no such luck. Will try ryujinx next

**Comment by slovechki** [comment]
There is a surprising workaround for this problem - the Dualsense controller.
I've recently bought a Dualsense controller and decided to try it with Yuzu to my surprise all the sound issues disappeared.
I can switch TV on/off, hibernate and the sound comes back after a minute. I guess my problems stemmed from the Xbox controller...

**Comment by rollercoaster** [comment]
Same on Ayaneo 2
