### ISSUE TITLE
F5 and crash clicking out of yuzu window, reproducible

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#7502]
I've found it's easy to reproduce this kind of crashes (mainline build 837):

1. start any game (doesn't matter fullscreen or windowed or exclusivefs)
2. quit back to yuzu main window with F5
3. at this point click out of yuzu window on the desktop

this should make yuzu UI unresponsive and crash soon after...

Windows 10 21H1

**Comment by german77** [comment]
I can't reproduce at all. Just followed these steps 30 times in a row. Tested with multiple games and waited different times before pressing F5. Anything more detailed? a log perhaps.

**Comment by Hexaae** [comment]
Mmmh, I can reproduce 100% here.
Log https://www.toptal.com/developers/hastebin/ciyonogoqo.yaml

**Comment by german77** [comment]
Is this issue recent? does it happens with older mainline as well?

**Comment by Hexaae** [comment]
834 still present... attempt with old 824 and doesn't crash! Should I hunt exactly WHEN it started? :-\

**Comment by Morph1984** [comment]
so that means this caused it https://github.com/yuzu-emu/yuzu/pull/7419

**Comment by heinermann** [comment]
I can't reproduce this either.

**Comment by Hexaae** [comment]
Sharing cfg file could help?
[qt-config.ini.txt](https://github.com/yuzu-emu/yuzu/files/7655131/qt-config.ini.txt)

**Comment by heinermann** [comment]
Thanks, can repro with *Pause emulation when in background* enabled.

**Comment by heinermann** [comment]
Have a fix, give me a moment.
