### ISSUE TITLE
Crashing/Freezing in Bravely Default 2 in Overland and Combat

### ISSUE THREAD

**Issue by CHiZZoPs** [yuzu-emu/yuzu#7504]
Never crashes in town or in dialogue, only during combat or in the field, and it's usually in the transition into combat. Set to Vulkan. GPU=normal seems to make it happen less often, but graphics are glitchy during comabt, while GPU=high produces nearly flawless graphics, but crashes more often. No other changes into the settings have seemed to make a difference.

I had the latest Nvidia drivers, and then went back to the Vulkan Beta 1.2 drivers. No change in the issue between them.
Log repeats this over and over:
HW.Memory <Error> core\memory.cpp:operator ():216: Unmapped ReadBlock @ 0x00000000003FD000 (start address = 0x00000000003F0000, size = 65536)
***This seems to be the same error and the same type of crash people are getting in Shin Megami Tensei. See [https://github.com/yuzu-emu/yuzu/issues/7323](https://github.com/yuzu-emu/yuzu/issues/7323) and [https://github.com/yuzu-emu/yuzu/issues/7338] (https://github.com/yuzu-emu/yuzu/issues/7338)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7655155/yuzu_log.txt)

**Comment by G-Spawn** [comment]
https://github.com/yuzu-emu/yuzu/issues/6828 Closing in favour of.
