### ISSUE TITLE
The Smurfs Mission Vileaf Hangs on Loading Screen

### ISSUE THREAD

**Issue by SpecialDarkwolf999** [yuzu-emu/yuzu#7507]
The game hangs on the loading screen on opengl and vulkan

This was tested on the mainline version 837 and also tested on EA 2296

Debug <Critical> video_core\memory_manager.cpp:operator ():72: Unreachable code!
Unmapping non-existent GPU address=0x112470000

Debug <Critical> video_core\engines\maxwell_dma.cpp:operator ():56: Assertion Failed!

both logs added.

[yuzu_log OpenGL.txt](https://github.com/yuzu-emu/yuzu/files/7655515/yuzu_log.OpenGL.txt)
[yuzu_log Vulkan.txt](https://github.com/yuzu-emu/yuzu/files/7655516/yuzu_log.Vulkan.txt)

**Comment by benderscruffy** [comment]
goes ingame now
can be closed
