### ISSUE TITLE
Missing HLE service command 'GetHostByNameRequest' in sfdnsres

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#7509]
used in Chess Ultra [0100A5900472E000]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7655679/yuzu_log.txt)

**Comment by benderscruffy** [comment]
used in Pinball FX3 when you update to 1.0.5 or higher

**Comment by Istador** [comment]
This might have been fixed with https://github.com/yuzu-emu/yuzu/pull/10912
