### ISSUE TITLE
Switch GPU texture Formats

### ISSUE THREAD

**Issue by SpecialDarkwolf999** [yuzu-emu/yuzu#7511]
maybe this is usefull and if not you can close it but i'm sure yuzu is missing a couple of those.

<html>
<body>

Value | Format
-- | --
0x01 | R32_G32_B32_A32
0x02 | R32_G32_B32
0x03 | R16_G16_B16_A16
0x04 | R32_G32
0x05 | R32_B24G8
0x06 | ETC2_RGB
0x07 | X8B8G8R8
0x08 | A8B8G8R8
0x09 | A2B10G10R10
0x0a | ETC2_RGB_PTA
0x0b | ETC2_RGBA
0x0c | R16_G16
0x0d | G8R24
0x0e | G24R8
0x0f | R32
0x10 | BC6H_SF16
0x11 | BC6H_UF16
0x12 | A4B4G4R4
0x13 | A5B5G5R1
0x14 | A1B5G5R5
0x15 | B5G6R5
0x16 | B6G5R5
0x17 | BC7U
0x18 | G8R8
0x19 | EAC
0x1a | EACX2
0x1b | R16
0x1c | Y8_VIDEO
0x1d | R8
0x1e | G4R4
0x1f | R1
0x20 | E5B9G9R9_SHAREDEXP
0x21 | BF10GF11RF11
0x22 | G8B8G8R8
0x23 | B8G8R8G8
0x24 | DXT1 (a.k.a. BC1)
0x25 | DXT23 (a.k.a. BC2)
0x26 | DXT45 (a.k.a. BC3)
0x27 | DXN1
0x28 | DXN2
0x29 | Z24S8
0x2a | X8Z24
0x2b | S8Z24
0x2c | X4V4Z24__COV4R4V
0x2d | X4V4Z24__COV8R8V
0x2e | V8Z24__COV4R12V
0x2f | ZF32
0x30 | ZF32_X24S8
0x31 | X8Z24_X20V4S8__COV4R4V
0x32 | X8Z24_X20V4S8__COV8R8V
0x33 | ZF32_X20V4X8__COV4R4V
0x34 | ZF32_X20V4X8__COV8R8V
0x35 | ZF32_X20V4S8__COV4R4V
0x36 | ZF32_X20V4S8__COV8R8V
0x37 | X8Z24_X16V8S8__COV4R12V
0x38 | ZF32_X16V8X8__COV4R12V
0x39 | ZF32_X16V8S8__COV4R12V
0x3a | Z16
0x3b | V8Z24__COV8R24V
0x3c | X8Z24_X16V8S8__COV8R24V
0x3d | ZF32_X16V8X8__COV8R24V
0x3e | ZF32_X16V8S8__COV8R24V
0x40 | ASTC_2D_4X4
0x41 | ASTC_2D_5X5
0x42 | ASTC_2D_6X6
0x44 | ASTC_2D_8X8
0x45 | ASTC_2D_10X10
0x46 | ASTC_2D_12X12
0x50 | ASTC_2D_5X4
0x51 | ASTC_2D_6X5
0x52 | ASTC_2D_8X6
0x53 | ASTC_2D_10X8
0x54 | ASTC_2D_12X10
0x55 | ASTC_2D_8X5
0x56 | ASTC_2D_10X5
0x57 | ASTC_2D_10X6

</body>
</html>

**Comment by Morph1984** [comment]
We already have these texture formats listed in an enum, sorry, it isn't useful.

**Comment by heinermann** [comment]
https://github.com/yuzu-emu/yuzu/blob/bde6b899a1ac4204f5c3f50695a467aa6ccca45b/src/video_core/textures/texture.h#L14-L91
