### ISSUE TITLE
Ring fit adventure does not display menus

### ISSUE THREAD

**Issue by SeerZero** [yuzu-emu/yuzu#7512]
Ring fit adventure should have displayed the main menu after skipping the start guidance video, but it didn't.

EA2273

log
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7655881/yuzu_log.txt.old.txt)

video
https://user-images.githubusercontent.com/31216691/144747634-25faf80d-d15e-4687-be84-fe72345e3941.mp4

**Comment by german77** [comment]
Ring fit needs this PR #6558  and on top of that the game still crashes. I haven't found the cause.
