### ISSUE TITLE
Send Compatibility Report crashes right after sending vote

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#7515]
Tried twice with two games, but Yuzu mainline 838 always crashed right after sending vote about compatibility (Good, Bad...) about some "Not Tested" games...

Windows 10 21H1

**Comment by G-Spawn** [comment]
This issue seems to be only happening to you at the moment. I'm unsure as to what's blocking it but perhaps try another game? If you use another antivirus besides defender it could be something related to that perhaps.

**Comment by Hexaae** [comment]
Tested with 3 tested games and it always crashed.

**Comment by Hexaae** [comment]
To be exact it crashes when I click Next button to send report after I selected "Good, Ok, Bad, etc..."

**Comment by G-Spawn** [comment]
This issue is still only happening to you. Please be patient or try a few things like reinstalling potentially.

**Comment by Hexaae** [comment]
There's nothing wrong with my installation and my system. It crashes systematically if you send report from main window when no game is running. It's easy to reproduce. I noticed it **doesn't crash** if I do it while the game is running in a window though.
Repro steps:
- run a game and quit with F5
- from main window now select any game and try to send a report
it will crash when you click 'Next' button to send your vote...

**Comment by G-Spawn** [comment]
I've asked a few people to try you're still sadly the only one to have reported this in the last week+. Could you try clearing your qt-config.ini perhaps and add back your game dir - token to the app and give that another whirl?
