### ISSUE TITLE
Fix gamepad G-Shark GS-GP702

### ISSUE THREAD

**Issue by 64ghost** [yuzu-emu/yuzu#7528]
Problem:
Not working right stick( function up and down) on gamepad G-Shark GS-GP702

Solution:

1.Open file SDL2.dll in hex-editor and find your G-Shark
2.Change righty:a4 on righty:a3
![0](https://user-images.githubusercontent.com/77530734/144918211-b068524d-cde3-4269-a9f2-7e20025f6fac.jpg)

Or please update SDL2.dll to 2.0.18.0 .This will solve the problem with gamepad

**Comment by german77** [comment]
The update is already there. Just linked to another PR. Let me make an independent PR for that

**Comment by Rsyah43** [comment]
How to update?
