### ISSUE TITLE
Shadow issue in Zelda BOTW

### ISSUE THREAD

**Issue by Juzeee** [yuzu-emu/yuzu#7533]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7664748/yuzu_log.txt)

The problem occurs on all object edges, I've already tested it in several versions of the emulator, I just haven't tested it with other drivers.

![yuzu 840 _ The Legend of Zelda_ Breath of the Wild (64-bit) _ 1 6 0 _ AMD 06_12_2021 22_07_01](https://user-images.githubusercontent.com/95663478/144949671-4aaf39ac-c1b2-45cf-941c-fb9f228a1e10.png)
![yuzu 840 _ The Legend of Zelda_ Breath of the Wild (64-bit) _ 1 6 0 _ AMD 06_12_2021 22_07_18](https://user-images.githubusercontent.com/95663478/144949673-c39c87ac-2be0-4c94-973c-91e6dacf7be4.png)

**Comment by G-Spawn** [comment]
We don't support piracy here.
