### ISSUE TITLE
How to run unpacked game with yuzu?

### ISSUE THREAD

**Issue by thx4ever** [yuzu-emu/yuzu#7534]
Hi, i'm new here, i want to know how to run a unpacked game folder in yuzu, i tried with different ways but no manage to get it working
in yuzu debug show this [  13.621015] Service.FS <Critical> core\hle\service\filesystem\fsp_srv.cpp:OpenDataStorageByCurrentProcess:964: no file system interface available!
I'm trying to run a game from a folder.

Regards

thx4ever

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/quickstart/ Guide mentions all required of you. This is an issue tracker, not a support forum.
