### ISSUE TITLE
the controller switching logic problem(ring-con in fitness ring adventure)

### ISSUE THREAD

**Issue by brainli13** [yuzu-emu/yuzu#7535]
the ring-con controller is Respond ,The fitness ring adventure will always automatically disconnect the controller connection of the player's position.The controller has a switching logic problem.All in the video(https://streamable.com/vo8d0a)

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7668381/yuzu_log.txt.old.txt)

**Comment by german77** [comment]
Not a problem in logic. the game manipulates the controllers a lot. the final result is player 1 with right joycon and player to with dual joycon(only left connected). UI doesn't show this mode properly

**Comment by brainli13** [comment]
> Not a problem in logic. the game manipulates the controllers a lot. the final result is player 1 with right joycon and player 2 to with dual joycon(only left connected). UI doesn't show this mode properly
I set it up according to this method, but the controller cannot be recognized when prompted to install Joy-Con(R) to Ring-Co
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7672235/yuzu_log.txt.old.txt)
n
![20211208073447](https://user-images.githubusercontent.com/29792608/145122583-8480633a-ad23-4c16-a914-555176cd3a15.png)
.

**Comment by german77** [comment]
No wonders if you look at your log you will se a bunch of this error. This means ringcon is not implemented on EA 2281
```
[  81.344154] Debug <Critical> core\hle\service\service.cpp:operator ():157: Assertion Failed!
Unknown / unimplemented function 'GetBusHandle': port='hidbus' cmd_buf={[0]=0x6, [1]=0xE, [2]=0x0, [3]=0x0, [4]=0x49434653, [5]=0x1, [6]=0x1, [7]=0x0, [8]=0x0}
```
I forgot to mention but there is a WIP that adds support to the ringcon #6558 feel free to test with the artifact made by azure. The ringcon force is controller by the left stick. Let me know if you get in game

**Comment by brainli13** [comment]
I tried the test build given to me by Narr the Reg, yuzu doesn't detect a real ringcon yet. Try with both players 1 and 2 as dual joycon. The left joycon’s joystick was used to replace the pressure-sensitive action, and it was finally stuck at the position where data was written to the ring-con.
https://youtu.be/lsPgQOB03oA

**Comment by taifengdian** [comment]
Hello  everyone,  From last monthly report I notice that the newest Yuzu version can support ring-con partly, but I tried a lot times and didn't get the ring-con work.  Any one can tell me how to config the controller? I'm really confuse about it.

**Comment by german77** [comment]
Let me explain a little bit. I implemented the service for the game to work but I didn't added support for a real ringcon.

to use the ringcon you must use a program that translates the ring to xinput then map the ring on controller -> advanced - > ring controller - > config

I will add support for the ringcon eventually. But for now the game works without it

**Comment by taifengdian** [comment]
I finally understand. thank you for the wonderful work. hope the work will be get done soon.

**Comment by rellystop** [comment]
> 让我稍微解释一下。我实现了游戏服务，但我没有添加对真正 ringcon 的支持。
> 
> 要使用 ringcon，您必须使用将环转换为 xinput 的程序，然后将环映射到控制器 -> 高级 -> 环控制器 -> 配置
> 
> 我最终会添加对 ringcon 的支持。但是现在游戏没有它也能正常工作

thank you very much！！！

**Comment by rellystop** [comment]
> Let me explain a little bit. I implemented the service for the game to work but I didn't added support for a real ringcon.
> 
> to use the ringcon you must use a program that translates the ring to xinput then map the ring on controller -> advanced - > ring controller - > config
> 
> I will add support for the ringcon eventually. But for now the game works without it

thank you very much！！！

**Comment by mastrerfail** [comment]
soo is this on the non early access verison allready? or not.

**Comment by german77** [comment]
Still on EA. Someone that's not me needs to review the code. I'm not a perfect programmer so we can't merge the code until it's reviewed

**Comment by mastrerfail** [comment]
Oh ok guess I'll have to wait or get patroon member, but still thanks for all you work on yuzu

**Comment by german77** [comment]
You can use the artifact from the PR. Everyone can download that

**Comment by SeerZero** [comment]
I've tested the PR version.

Controller 2 is automatically disconnected when entering and cannot be reconnected anyway.

This is the first time I have used the PR version. I'm not sure whether it's my own setting problem or the program itself.

Thank you very much for your fantastic work.

**Comment by taifengdian** [comment]
@german77 I wonder how long will be taken for the real ring con support, just can't wait to play it. Thanks a lot.

**Comment by german77** [comment]
first we need a custom joycon driver working

**Comment by mastrerfail** [comment]
> You can use the artifact from the PR. Everyone can download that

hi its me again, and i juyt wanted to ask, how do you implement a PR into yuzu, i have the build downloaded, and do i just copy the text into the right text and hit override? or is there something that i should do? sorry if its a dumb question.

**Comment by mastrerfail** [comment]
hi, i just wanted to aks something, so i cloned this https://github.com/german77/yuzu.git and build it, i can execute everything, but the point is, i still cant get the ringcone to work, it would be greatfull if someone can help, and pls dont be mad if i overlooked something obviouse, im not an expert with this.

**Comment by taifengdian** [comment]
@mastrerfail how did you make the ringcon work?

**Comment by mastrerfail** [comment]
ok so, if you mean how i only got the ringcon to wokr it was pretty simple, just downloaded [https://github.com/ringrunnermg/Ringcon-Driver/releases/tag/1.0.3](url) <-- this and configured the press to be a stick or smh, and then in  yuzu configured the press to the stick.

but you need a "custom" version of yuzu by building cloning [https://github.com/german77/yuzu](url) and building this version with cmake, and then using cisual studios 2019 to do the rest, or just follow [https://yuzu-emu.org/wiki/building-for-windows/](url) and instead of cloning yuzu's version you clone german77's version with this link [https://github.com/german77/yuzu](url) .

hope you get it to work, and i know im terrible at describing things, especially when its not my nativ language, but i hope it helps, and what helped me was trial and error my way through.

oh and another thing, after i start a level in story mode and i encounter a enemy  it just goes to a withscreen, and have to restart yuzu, oh and overlays dont work for me.

what came to my mind now is that you have to configure the joy cons in a weird way so that it works and under the advanced control option there you'll find the ringcon config.

**Comment by pktiuk** [comment]
> first we need a custom joycon driver working

Do you mean Windows driver?  
What about Linux drivers? There are already [Ring-Con drivers in kernel](https://www.phoronix.com/scan.php?page=news_item&px=Nintendo-HID-For-Linux-5.16).
