### ISSUE TITLE
[Windows][Vulkan]The latest Mainline builds crash quite often (Pokémon Brilliant Diamond v1.1.2)

### ISSUE THREAD

**Issue by LOuroboros** [yuzu-emu/yuzu#7536]
**Version**: Yuzu 840.
**Details**: I'm experiencing crashes every now and then in Pokémon Brilliant Diamond while using this build with the Vulkan based renderer.
I had the game crash on me about 33 minutes ago after I defeated my rival, Barry, and I also had it crash 5 minutes ago after I defeated Flint.
In the second instance though, I feel one of my Pokémon were about to evolve because the music was muted.

In both situations, what happened is that after the battle, the screen went black and the framerate went down to 0 FPS.
A couple of seconds later, Yuzu just crashed.

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7670332/yuzu_log.txt)

**Comment by german77** [comment]
Your PC is under the minimum recommended specs. We can't warrantee a stable game with just 4GB of ram

**Comment by LOuroboros** [comment]
> Your PC is under the minimum recommended specs. We can't warrantee a stable game with just 4GB of ram

Alright, that's fair. It doesn't happen with the NVIDIA renderer though.

At the end of the log there's interesting errors too. It's about effects that are not implemented yet, like "Compressed Image Aliasing" or "Multisample AntiAliasing" *(MSAA)*, and that could perhaps be causing these crashes.
I'd imagine that if the game couldn't successfully call the code that executes X or Y visual effect, it could crash as a result, but that I'm not sure of. I'm not a full-fledged programmer so I'm unable to determine that.

On top of that, the game barely consumes a full GB of my RAM, at least on Yuzu 840. Task Manager says I'm not using the full extent of my 4GB either.

![explorer_2640](https://user-images.githubusercontent.com/4485172/145082933-a6579145-f8de-4662-a757-143ae0412c66.png)

Considering all that, would you still say that my lack of RAM is the problem?

If you would, I will close the Issue ticket immediately.

**Comment by german77** [comment]
If by barely you mean 95%(last 5% is usually keep for system to avoid bluescreen) of the total memory available is used. Then yeah upgrading at least the ram will improve your experience significantly. 8GB is the minimum but I recommend 16GB.

The GPU is fine for most games, the cpu will be better if you have at least 6 threads.

**Comment by german77** [comment]
The game crashed from a GPU error. But there is a big change that the gpu is crashing due to lack of vram and ram.  Regardless of yuzu your computer will be a lot faster with 8GB of ram since you aren't writing to the disk all the time

**Comment by LOuroboros** [comment]
> The game crashed from a GPU error. But there is a big chance that the gpu is crashing due to lack of vram and ram.

Alright then. Should I wait for further confirmation or just close the ticket now?

**Comment by G-Spawn** [comment]
> 

Stick to using auto cpu accuracy please. Enable async gpu emulation in config graphics.

**Comment by LOuroboros** [comment]
> > 
> 
> Stick to using auto cpu accuracy please. Enable async gpu emulation in config graphics.

Async GPU Emulation doesn't seem to do anything of value besides increasing the usage of RAM. I don't perceive much of a difference myself. As I said back in [#7477](https://github.com/yuzu-emu/yuzu/issues/7477#issue-1066773008), it actually delays the occurence of a crash.

As for the CPU Accuracy, I do normally keep it on Auto. It's just that from time to time, I set it to Unsafe to test out if there's a performance difference in one area or another inside a videogame 😅 

I haven't tested out EA since I wrote this issue ticket. I'll check later if it's still crashing with the Vulkan renderer.

**Comment by G-Spawn** [comment]
There isn't really much we can address. Older hardware sometimes just isn't up to par with modern emulation. Keep async gpu emulation on period. Beyond that your console would honestly outperform your pc in many regards.

**Comment by LOuroboros** [comment]
> There isn't really much we can address. Older hardware sometimes just isn't up to par with modern emulation. Keep async gpu emulation on period. Beyond that your console would honestly outperform your pc in many regards.

I'm aware, but the NVIDIA renderer doesn't crash.

Does that mean that the Vulkan based renderer is just more intensive, and that's why the crashes while using it occur, meaning it's all expected behavior?

**Comment by G-Spawn** [comment]
I get trying to use older hardware but none of your visual issues are normal honestly. They're specific to you and your dated hardware.

**Comment by LOuroboros** [comment]
> I get trying to use older hardware but none of your visual issues are normal honestly. They're specific to you and your dated hardware.

Alright then. If that's the conclusion that was reached by analyzing the logs, that's that. Thanks and sorry for bothering you.

Should I close all of them?

**Comment by G-Spawn** [comment]
It's not a bother, we do apologize for not being able to get you further along. If you could close them that may be ideal.
