### ISSUE TITLE
[Windows] Borderless Fullscreen Windows Resolution Off-by-One Pixel

### ISSUE THREAD

**Issue by Andon13** [yuzu-emu/yuzu#7537]
Borderless Fullscreen windows (when toggled using F11) do not qualify for fullscreen optimization on Windows because an extra vertical pixel is being added.

![unknown](https://user-images.githubusercontent.com/10385276/145089685-8d9d12ea-0118-4a8e-a562-7e45c52bef62.png)

This off-by-one problem only affects the menu toggle, moving the window between monitors with Windows + Shift + Left / Right computes the correct window dimensions.

**Comment by Morph1984** [comment]
This is intentional, since using the correct dimensions is what "Exclusive Fullscreen" uses
You will notice there is a difference in window behavior between the 2 options

**Comment by Andon13** [comment]
Ah, okay. I see now.

![image](https://user-images.githubusercontent.com/10385276/145092010-42863535-842d-4bda-9fa2-e89a3c22e060.png)

All modes are borderless windows, I assumed "Fullscreen Exclusive" would be making a call to `ChangeDisplaySettings` to set the output resolution to match the framebuffer and wanted to avoid that, but it is not necessary.
