### ISSUE TITLE
Resolution 0.25X (180p/270p) possible?

### ISSUE THREAD

**Issue by phasermaniac83** [yuzu-emu/yuzu#7538]
Hi! I already asked if was it possible to have 0,333 resolution for Ninja Warriors Once Again, but I was wrong.
This game uses the base resolution 480x270, so it's 1920x1080 (Docked) x 0,25.
Is it possible to add Resolution 0.25X (180p/270p)? I think this may be useful with this and other games for CRT users, which displays at very low resolutions (240p/288p), as lowering resolution in yuzu improves performance noteceably
Thanks

**Comment by goldenx86** [comment]
You just made our GPU dev cry.

**Comment by german77** [comment]
0.5x is already a very low resolution for modern hardware. 0.25x will make games look really bad and could cause severe graphical issues.  I consider playing on the switch much better at this point

**Comment by phasermaniac83** [comment]
I know nowadays 270p is a shit, but pixel art games in a CRT looks amazing.
Pixel art games looks the same and preform better lowering resolution. You have to know which base resolution uses the game for setting it correctly:
Ninja Warriors for example, do not display right at 720p, you can see pixel glitches. You have to set it in 1080p (docked). If you do an screenshot, tou can see every 1x1 pixel is actually 4x4 pixels, so the base resolution is 480x270. I have tried this and Clockwork Aquario and looks perfect at 0,5 and should look perfect at 0,25.
Anyway I understand few people would benefit from this.
Thanks

**Comment by goldenx86** [comment]
I would look into integer scaling, instead of forcing a lower resolution that could have undesired effects.

**Comment by degasus** [comment]
This is for sure possible, but pointless. Your point about getting a speedup is very likely wrong. Please check my next calculation:

`0,5` scaling renders 25% of the pixels compared to `1` scaling. So if you are limited by pixel processing performance, you should see a speedup of factor 4. If your speedup is significat smaller than the factor of 4, you won't see any performance improvements based on a scaling factor of `0,25` at all.

Which speedup factor do you get for `0,5` vs `1` as scaling factor? Is it close to 4? My bet is closer to 2 than to 4.

**Comment by phasermaniac83** [comment]
mm, It seems it depends on the game:
Clockwork aquario: 
1x  -> 33-39fps
0,5x -> 59-61fps
Ninja warriors once again: 
1x  -> 22-24fps
0,5x -> 26-28fps
So yes, you have reason, at least in Ninja Warriors it's pointless. Why this difference? Shouldn't both games behave the same way?

**Comment by degasus** [comment]
So your speedup factor is 1.5 .. 1.8 for clockwork aquario and 1.1 .. 1.2 for ninja warriors.

Nowhere close to 4, so reducing the resolution will not increase the speed at all. Please tell me if you prefer the visuals of 0.25 over 0.5 at the same performance, but I strongly doubt so.

In case you wonder about my math, please try the slowdown factor of `2` vs `1` as rescaling factors ;)
