### ISSUE TITLE
Immortal Fenix Rising is missing texture format R16G16_UINT and Unmapped Read32

### ISSUE THREAD

**Issue by SpecialDarkwolf999** [yuzu-emu/yuzu#7540]
Tested on EA: 2292 ( i have patreon )

This is immortal fenix 1.3.4 plus the three expansion dlc's

Immortal fenix rising is missing texture format R16G16_UINT and Unmapped Read32 on vulkan.

Debug <Critical> video_core\renderer_vulkan\maxwell_to_vk.cpp:operator ():233: Assertion Failed!
Unimplemented texture format with pixel format=R16G16_UINT

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7677165/yuzu_log.zip)

**Comment by G-Spawn** [comment]
Posting the log in full and providing the yuzu version used goes a long way.

**Comment by SpecialDarkwolf999** [comment]
oh sorry forgot.
will upload and update my first post

**Comment by SpecialDarkwolf999** [comment]
with R16G16_UINT  added now the ingame movie plays a little now and then crash without an warning or error.
