### ISSUE TITLE
Star Ocean First Departure R rendering issue

### ISSUE THREAD

**Issue by NineKain** [yuzu-emu/yuzu#7546]
![image](https://user-images.githubusercontent.com/72826232/145279727-e5004cbe-481d-417c-87ae-ad723b61363a.png)

Main character is pink

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7678754/yuzu_log.txt)

**Comment by NineKain** [comment]
![image](https://user-images.githubusercontent.com/72826232/145280024-b4c31a10-cf52-414f-91d2-b8dfa6ff4fe7.png)
opengl solves the issue

**Comment by benderscruffy** [comment]
using the latest EA and mainline
this is still an issue

**Comment by Hector-Ariceaga** [comment]
Still noticing this issue. Not aware of a fix yet with latest drivers and early access build.

**Comment by gidoly** [comment]
Fixed by 11562
