### ISSUE TITLE
Compilation now fails in linux

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#7547]
Compilation now fails in linux.  Excerpted from build log:
```
[952/1369] Building CXX object src/video_core/CMakeFiles/video_core.dir/command_classes/codecs/codec.cpp.o
FAILED: src/video_core/CMakeFiles/video_core.dir/command_classes/codecs/codec.cpp.o 
```
Can provide a bisect if needed.

Information:
* OS: Linux Mint 20.2 / kernel 5.13
* Compiler: gcc-11.1.0
* Commit tested: 7dd2764f2a7e3bc88ed12b160aceed7dda007329
* Last good commit: 54f007efc6ed311a8356238ea136b9744b68eb75
* Build log: [Here](https://pastebin.com/mAqz6J7s)

**Comment by Shoegzer** [comment]
Update: had time to perform a bisect - apparently this is the target commit: cd27f211c8ad67c73c831e57a4eb298f9693253f.

@liushuyu Can you offer your thoughts / assistance?

**Comment by liushuyu** [comment]
> Update: had time to perform a bisect - apparently this is the target commit: [cd27f21](https://github.com/yuzu-emu/yuzu/commit/cd27f211c8ad67c73c831e57a4eb298f9693253f).
> 
> @liushuyu Can you offer your thoughts / assistance?

What's the version of your `ffmpeg`? The second and third errors should be false-positive since the type-inference is broken due to incomplete definition.

**Comment by Shoegzer** [comment]
Thanks.  It's from the stock ubuntu repo.  Here's the info:
```
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
```

**Comment by liushuyu** [comment]
> Thanks. It's from the stock ubuntu repo. Here's the info:
> 
> ```
> ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
>   built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
> ```

That seems to be the issue, the `ffmpeg` on our CI is version `4.4`.

You have the following options:
- Add `-DYUZU_USE_BUNDLED_FFMPEG=ON` this would use bundled `ffmpeg` (requires `cuda` headers)
- Update `ffmpeg` to a newer version by using a third-party repository (PPA)
- I could change the code so that the offending API is not used when using older `ffmpeg` (but expect issues with video decoding in this case)

**Comment by Shoegzer** [comment]
Interesting.  In that case, I'll try a hybrid of your first and second options; i.e. compiling with `DYUZU_USE_BUNDLED_FFMPEG` but will removing the option once the stock repo is updated.  This is because I'm trying to limit the number of PPAs on this test system for various reasons.  Out of curiosity, what is the minimum ffmpeg version for yuzu?

Incidentally, yuzu now compiles properly with your first option, so unless you have any other suggestions I'll close the issue report.

Thanks for your help!

**Comment by liushuyu** [comment]
> Interesting. In that case, I'll try a hybrid of your first and second options; i.e. compiling with `-DYUZU_USE_BUNDLED_FFMPEG` but removing the option once the stock repo is updated. This is because I'm trying to limit the number of PPAs on this test system for various reasons.
> 
> Incidentally, yuzu now compiles properly with your first option, so unless you have any other suggestions I'll close the issue report.
> 
> Thanks for your help!

No problem. If you have any other questions, you could still post it here; if not, I think we could close this issue.
