### ISSUE TITLE
Lego City Undercover Vulkan Missing Texture ASTC_2D_8X5_UNORM and format 249

### ISSUE THREAD

**Issue by SpecialDarkwolf999** [yuzu-emu/yuzu#7548]
Tested on EA: 2296

Unimplemented texture format with pixel format=ASTC_2D_8X5_UNORM
Unimplemented format=249
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7687662/yuzu_log.txt)

**Comment by Morph1984** [comment]
249 is listed here: #6074

**Comment by SpecialDarkwolf999** [comment]
morph your are fast and thanks

**Comment by PrinceBubloo** [comment]
@Morph1984
Is it not possible to add all missing formats rnow or at once?.
I saw that couple days ago  you implemented one more missing format.

**Comment by Morph1984** [comment]
@PrinceBubloo It's better if we have a game that can be tested for the missing formats, otherwise it would not be known whether it works or not.

**Comment by SpecialDarkwolf999** [comment]
this one is solved only 249 still  remains and reserve heap problems but most of the time game runs on 30 fps and sometimes an stuttering to 6 / 8 fps
morph do you know what 249 is ?
