### ISSUE TITLE
Disaster Report 4 Summer Memories issues unmapped memory readblock Vulkan

### ISSUE THREAD

**Issue by SpecialDarkwolf999** [yuzu-emu/yuzu#7550]
Tested on EA: 2296

several diffent HW.Memory <Error> core\memory.cpp:operator ():216: Unmapped ReadBlocks

game hangs on loading screen after the first part of the game play on vulkan
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7688032/yuzu_log.txt)
.

**Comment by G-Spawn** [comment]
This issue shouldn't happen on recent Yuzu versions. Please reopen issue if it still happens to you on updated mainline / early access Yuzu.
