### ISSUE TITLE
Yuzu Main Program Problems

### ISSUE THREAD

**Issue by SpecialDarkwolf999** [yuzu-emu/yuzu#7556]
This is bothering me now for a long time.

sometimes when you startup yuzu it take ages to load everything like 5 minutes max and many times it's only less then 5 seconds to load the program plus games etc and what is causing this i don't know,

i don't know how to debug this what is causing this.

the program is also non stop searching or reading something after it has been loaded after you have it on idle.
you can hear the hard drive trying to search or reading something non stop and this is only with yuzu open.

i have nothing else on this hard drive.

if yuzu is off then the drive is also off.

when you are closing yuzu your hardrive gets a spike till 100% disk usages for 2 seconds and after that it's zero and this is the same if you open yuzu

**Comment by german77** [comment]
Do you have many games? or have you checked the disk health? disk usages at 100% usually means there's a bad sector

**Comment by SpecialDarkwolf999** [comment]
i have 20 games and drive is in 100% condition and no bad sectors.

**Comment by german77** [comment]
I got around 150 games and it loads in about 2-5 seconds. After adding a update it takes about 15 seconds to refresh. But never anywhere close to more than 1 minute. What do you mean with one game? It takes 5 minutes to load a game or to load the game list?

**Comment by SpecialDarkwolf999** [comment]
to load the yuzu game list but this is random and most of the time this does not happen. 
it takes sometimes longer then 3 / 5 minutes but most of the time it takes 2 a 3 seconds.
if this happen the yuzu program stays blank and if you press on the window it crashes.

Don't know if this only happens on HDD'S or also on an SSD ?

**Comment by aecarvalho** [comment]
I can confirm the same but that only happens to me after yuzu crashes or has to be force closed especially. I only have two games but a lot of other stuff too on my drive, mainly software.
Disk spiking at 100% is accurate but that often happens otherwise too, especially with the Kaspersky Internet Security running.

**Comment by SpecialDarkwolf999** [comment]
here is it again when opening yuzu and i dont have any anti virus on my windows al is disabled and still it is happening.
![image](https://user-images.githubusercontent.com/93608381/145666887-b747da61-ff14-49ab-957b-3b55088f6b66.png)

**Comment by aecarvalho** [comment]
If you have less RAM then it will use paging file memory, that could be the issue

**Comment by SpecialDarkwolf999** [comment]
Les ram ? I have 32gb ram and a page file on both drives on 40 gig so thats not the problem

**Comment by aecarvalho** [comment]
You don't need page file if you have enough RAM actually, it makes things slower rather than the other way around

**Comment by SpecialDarkwolf999** [comment]
Ok i can try that and yes they are

**Comment by SpecialDarkwolf999** [comment]
no difference with or without page file

**Comment by SpecialDarkwolf999** [comment]
also found something else with debugging yuzu.
it reads multiple times the same firmware files when opening yuzy and same with this on the latest switch firmware version : 

several param_packages not found is also popping up 10 or  more times with the same files with booting yuzu and after that it 

dont know if this is correct normally it should read the files 1 time right ?

it looks like yuzu has an problem that it reads the same file multiple times.

**Comment by SpecialDarkwolf999** [comment]
found also something odd with debugging yuzu when openen inprgram but not sure if this correct.
it reads multiple time the same folders \ files in Yuzu\user\nand\user\Contents\registered and Yuzu\user\nand\system\Contents\registered

**Comment by aecarvalho** [comment]
Disk usage is unusual though, try updating prod keys and system files to match the latest firmware update 13.2.0

**Comment by SpecialDarkwolf999** [comment]
found also something odd with debugging yuzu when openen inprgram but not sure if this correct.
it reads multiple time the same files in the folder
Yuzu\user\nand\user\Contents\registered
Yuzu\user\nand\system\Contents\registered

and same with the param_package.ccp and this one is more then 10 times. ( see attached param part log )
param.txt

this is with the last firmware version of the switch and EA 2300

do i miss something or is this an yuzu bug ?
[param.txt](https://github.com/yuzu-emu/yuzu/files/7698593/param.txt)

**Comment by SpecialDarkwolf999** [comment]
> Disk usage is unusual though, try updating prod keys and system files to match the latest firmware update 13.2.0
> 
> High disk usage isn't a yuzu program problem because it depends on the size of the game and the resources yuzu is trying to pull

yes i allready did and because this is the only program on that drive,  if i remove yuzu from that drive and put an pc game or something on it then i don't have this problem.

this only happens 1 a day with opening yuzu so yuzu is causing it.

**Comment by aecarvalho** [comment]
Only one solution left then, switch to SSD, yuzu is trying to read too many small files spread over the hard drive so the louder HDD noise and longer loading time. Comparatively SSD being flash storage will have not much issue with random read speed.

**Comment by SpecialDarkwolf999** [comment]
ye will do that thx

**Comment by SpecialDarkwolf999** [comment]
this seems to be fixed on EA: 2305

**Comment by german77** [comment]
Just as a follow up. From two days ago until EA 2305 there isn't any significant change that will affect this issue. I did some test on HDD had no issues either

**Comment by SpecialDarkwolf999** [comment]
It was probarly something on my pc thats effected it

**Comment by german77** [comment]
This doesn't seem to be a yuzu issue
