### ISSUE TITLE
Twelve Minutes Vulkan / Opengl Issues

### ISSUE THREAD

**Issue by SpecialDarkwolf999** [yuzu-emu/yuzu#7559]
Tested on  EA:2300

Controls working odd with controller or keyboard and game runs on 11 fps with stuttering and graphical issues on vulkan and 30 fps on opengl with the same problems.

Graphics are flikkering / blurring and very dark sometimes.

Tested on both drivers.

![image](https://user-images.githubusercontent.com/93608381/145674363-85dad757-5995-4057-b843-eef57d9e7fef.png)
![image](https://user-images.githubusercontent.com/93608381/145674408-09a3cbad-19ad-4017-8fe5-379ce19b2112.png)
[yuzu_log Opengl.txt](https://github.com/yuzu-emu/yuzu/files/7696859/yuzu_log.Opengl.txt)
[yuzu_log Vulkan.txt](https://github.com/yuzu-emu/yuzu/files/7696860/yuzu_log.Vulkan.txt)

**Comment by benderscruffy** [comment]
no problems so far 
can be closed
