### ISSUE TITLE
Restarting game on Linux causes memory leak

### ISSUE THREAD

**Issue by Joey11904** [yuzu-emu/yuzu#7562]
On Linux, if you restart a game using `Emulation > Restart` or `Emulation > Stop` then relaunch game, the previous game's memory is not deleted, meaning that the system's RAM will fill up completely if you restart enough times.

Here's the log:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7697031/yuzu_log.zip)

**Comment by SpecialDarkwolf999** [comment]
almost same on windows. 
it doesn't clear all the memory when used for that game if you do restart or stop the game.
only if you close yuzu completly it free up the memory that was in used for the game and program.

**Comment by SpecialDarkwolf999** [comment]
for me on windows this seems to be fixed on EA: 2305

**Comment by Joey11904** [comment]
#7603 doesn't seem to fix the issue for me. Memory leak still happens but much slower than before
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7776013/yuzu_log.zip)

**Comment by ameerj** [comment]
@Joey11904 does this happen on all titles or have you only seen this behavior in Pokemon Pearl?

**Comment by Joey11904** [comment]
@ameerj happens on all games
