### ISSUE TITLE
yuzu fails to compile on debug mode

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#7567]
recent yuzu sources fails to compile exe on debug mode
 it says input_common\debug\input_common.lib can't be open

<img width="518" alt="devenv_DjoEpsuuNk" src="https://user-images.githubusercontent.com/66776795/145701437-a0719e74-c961-4187-9d0e-3c0a9e604740.png">

**Comment by vonchenplus** [comment]
In general, a full recompile will solve the problem.

**Comment by german77** [comment]
boost is missing this change https://github.com/boostorg/crc/pull/6 
Since there's over a year without merge my hopes of fixing this issue are near none.

**Comment by german77** [comment]
A workaround has been set
