### ISSUE TITLE
WarioWare: Get It Together! Inaccuracies

### ISSUE THREAD

**Issue by garc302** [yuzu-emu/yuzu#7571]
[Video](https://cdn.kapwing.com/final_61b6b31828dfbc003dcca14d_483395.mp4)

1. (Already reported) Coins are invisible in the bonus game
2. Although hard to hear, the pitch bending at the results of the bonus game is limited to the BFSEQ timebase, making it less smooth
3. [There's supposed to be a muffle effect in the "Music Mischief" microgame](https://youtu.be/Hp3FvYvOAyA?t=441)

**Comment by G-Spawn** [comment]
Provide a log file please like the issue template asks for.

**Comment by benderscruffy** [comment]
is this still an issue ???
