### ISSUE TITLE
"Assertion '__n < this->size()' failed." when Keyboard Applet launches

### ISSUE THREAD

**Issue by m-hugo** [yuzu-emu/yuzu#7573]
Pokemon Sword crashes before i get to choose my uniform number (on vulkan so I tried again on opengl, same crash) , the game worked perfectly a few hours ago when choosing my name, etc.

latest flatpak yuzu / sway / fedora / ryzen 5600h with igpu

pinging @Morph1984 since the only thing I found about the Applet is this:  https://yuzu-emu.org/entry/yuzu-applet-overlays/

note that it's an instant crash as soon as the dialogue with the receptionist ends, no popup or anything appears

> [ 153.304696] Service.AM <Warning> core/hle/service/am/am.cpp:GetLibraryAppletLaunchableEvent:379: (STUBBED) called
[ 153.317806] Service.AM <Info> core/hle/service/am/applets/applet_software_keyboard.cpp:Initialize:54: Initializing Software Keyboard Applet with LibraryAppletMode=0
[ 153.317823] Service.AM <Info> core/hle/service/am/applets/applet_software_keyboard.cpp:InitializeForeground:184: Initializing Normal Software Keyboard Applet.
[ 153.317891] Service.AM <Info> yuzu/applets/qt_software_keyboard.cpp:InitializeKeyboard:1533:
KeyboardInitializeParameters:
ok_text=
header_text=Please enter your uniform number.
sub_text=
guide_text=
initial_text=
max_text_length=3
min_text_length=1
initial_cursor_position=0
type=1
password_mode=0
text_draw_type=0
key_disable_flags=0
use_blur_background=true
enable_backspace_button=true
enable_return_button=false
disable_cancel_button=false
/usr/include/c++/11.2.0/array:188: constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](std::array<_Tp, _Nm>::size_type) [with _Tp = std::array<std::array<QPushButton*, 12>, 5>; long unsigned int _Nm = 2; std::array<_Tp, _Nm>::reference = std::array<std::array<QPushButton*, 12>, 5>&; std::array<_Tp, _Nm>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.

**Comment by v1993** [comment]
This is a valid issue, but as a workaround - use appimage build for now. It has asserts off.

**Comment by m-hugo** [comment]
> use appimage build for now. It has asserts off.

Thanks, it worked perfectly with the appimage

**Comment by Morph1984** [comment]
Thanks for reporting the issue! I have fixed it in the PR above
