### ISSUE TITLE
All text display question mark

### ISSUE THREAD

**Issue by GF-Huang** [yuzu-emu/yuzu#7582]
Language: Chinese

![image](https://user-images.githubusercontent.com/4510984/145938243-553cf736-32f9-4c99-a8d5-62ce1abf1630.png)

**Comment by G-Spawn** [comment]
this isn't a support forum but try dumping your firmware from your nintendo switch to see if that helps.  https://yuzu-emu.org/help/quickstart/#dumping-system-update-firmware

**Comment by G-Spawn** [comment]
Providing a log file like the issue template asks for can go a long way as well.

**Comment by GF-Huang** [comment]
Sorry, I have no Switch.

**Comment by german77** [comment]
This error is due no firmware

**Comment by G-Spawn** [comment]
> Sorry, I have no Switch.

We don't support piracy here then.
