### ISSUE TITLE
Game audio randomly disappears on Linux

### ISSUE THREAD

**Issue by Joey11904** [yuzu-emu/yuzu#7585]
For some reason, game audio (sfx and bgm) can completely disappear at random times during gameplay. This is most notable on `Pokemon Brilliant Diamond/Shining Pearl.` Its a bit hard to trigger this reliably, since the audio can disappear shortly after starting the game or long into the game.

Here's the log
[yuzu_log_audio-loss.zip](https://github.com/yuzu-emu/yuzu/files/7717109/yuzu_log_audio-loss.zip)

**Comment by wilkovatch** [comment]
It doesn't happen only on Linux, it happened to me too on Windows in Project Diva Mega Mix.

In Project Diva Mega Mix it happens after a while when scrolling through the song list, it can take from 5 to 10 minutes to appear.

Here's the log (trace level, it happened around the 374s-375s mark, I can't find any errors in it though...): [yuzu_log_audio-loss_trace.zip](https://github.com/yuzu-emu/yuzu/files/7722857/yuzu_log_audio-loss_trace.zip)

**Comment by no1d** [comment]
Yeah, in Project Diva SFX randomly disappear between songs and then come back. Happens pretty much after every song.
I'm on Windows 10.

I believe [this pr](https://github.com/yuzu-emu/yuzu/pull/6498) introduced this behavior.
