### ISSUE TITLE
Problem with The Binding of Issac 

### ISSUE THREAD

**Issue by Sammojr614** [yuzu-emu/yuzu#7591]
Yuzu Ver 849
Main Issue: Save Corrupt, Crashing
Lesser issues: Screen Flashes.

So, When i Launch the binding of isaac, The Game says the Main File is Corrupt. I checked the File on the Switch. The game said it was fine. if you wait a hot min on yuzu the screen will start Flashing, Followed by what i assume is a Crash.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7722854/yuzu_log.txt)

**Comment by benderscruffy** [comment]
goes ingame 
no problems so far 
can be closed
