### ISSUE TITLE
Cruis'n Blast: Permanent vibration since yuzu 828

### ISSUE THREAD

**Issue by YesterPlay80** [yuzu-emu/yuzu#7592]
Since merging PR7255 (Project Kraken) in version 828, my Xbox One controller starts vibrating during the initial loading screen in Cruis'n Blast and won't stop unless I stop emulation or exit yuzu. Switching back to 827, everything works fine again. The issue persist up to the latest release as of writing this (849).
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7722978/yuzu_log.txt)

**Comment by german77** [comment]
I got the game but I couldn't make my controller vibrate before or after kraken. Is not an issue with config since the controller vibrates properly on other games. Does it vibrate properly on 827?

**Comment by YesterPlay80** [comment]
Yes, with 827 vibration only kicks in when boosting, jumping or battling with other cars, exactly as I'd expect it to happen on the original console.

**Comment by german77** [comment]
Can you test with the PR artifact just to ensure everything is working as it did before kraken. https://dev.azure.com/yuzu-emu/yuzu/_build/results?buildId=16616&view=results

**Comment by YesterPlay80** [comment]
With the test build (extracted in a separate folder) it only vibrates for a few moments during the loading screen, which didn't happen before. I assume this is the testing the games do mentioned in PR7593. But after that, in game, it works great again! :D

**Comment by german77** [comment]
Thanks for testing. Yes the slight vibrations are to confirm that vibration do arrive to the controller.

**Comment by YesterPlay80** [comment]
> Thanks for testing.
Thanks for fixing! ;)

**Comment by YesterPlay80** [comment]
Argh, too early. Now, after a restart, the unwanted vibrations are back, not as permamanent and intense as before, but the controller vibrates softly every now and then in the loading screens and the menus again. :(

**Comment by german77** [comment]
ahh. It was too easy to be true. I will try to find a better solution. To begin with I don't have any vibration

**Comment by legend800** [comment]
@german77 This is broken again in the latest EA(2968). Once menus are enters, controller just rumbles forever until you shut down yuzu.

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9630990/yuzu_log.txt)

**Comment by hjkcai** [comment]
+1 I had the same issue playing Super Mario Party using yuzu mainline 1181 (2022-09-26)
