### ISSUE TITLE
Pinball FX3 only shows half a screen (Vulkan) and black screen with sound (opengl) when updated from 1.0.0 [AMD - GCN issue]

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#7595]
using base 1.0.0
all screens are great takes up the full screen
if you update the base to say 1.0.7 or higher then it shows only half a screen when using Vulkan
when using Opengl nothing but a black screen with the sound
![0100db7003828000_2021-12-16_20-59-44-989](https://user-images.githubusercontent.com/2696404/146377341-84924934-4b07-4bfb-9419-7d7106445e36.png)
![0100db7003828000_2021-12-16_21-00-00-435](https://user-images.githubusercontent.com/2696404/146377351-4dd70cad-dcc9-45d1-b4d2-4fa294bb1b47.png)
![0100db7003828000_2021-12-16_21-00-34-532](https://user-images.githubusercontent.com/2696404/146377358-1c019452-be54-413c-8cbb-087fb3416a09.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7727478/yuzu_log.txt)

**Comment by benderscruffy** [comment]
still an issue using latest EA and mainline

**Comment by benderscruffy** [comment]
still an issue using latest EA and mainline

**Comment by JonAbrams** [comment]
This happens to me with every version of Pinball FX 3 I've tried **except** for base 1.0.0. Using latest Yuzu on Steam Deck (Vulkan + AMD).

**Comment by Malbeth81** [comment]
Also getting the same issue.

**Comment by ddrmaster18** [comment]
Not getting this problem on my desktop, I can apply all updates and it runs fine, but I am getting this issue on my steam deck once updating the game from 1.0 to either v655360 or v786432.

**Comment by abouvier** [comment]
The problem is fixed for me with yuzu mainline-0-1271, game version 1.0.11.0 and Vulkan backend (mesa 22.2.3 on linux 6.0.12).

**Comment by benderscruffy** [comment]
still happens 
![Capture](https://user-images.githubusercontent.com/2696404/208215586-b0c94bae-903a-4100-a713-d14282af193c.PNG)

**Comment by exerkaoss** [comment]
i unfortunately solved this switching to ryujinx. i still use both for some games, but stuff like some mario games (kart included) work only on ryu, others only on yuzu.... *shrugs*

**Comment by benderscruffy** [comment]
have upgraded to a new computer so can not test it with old computer anymore

**Comment by benderscruffy** [comment]
have upgraded to a new computer so can not test it with old computer anymore
