### ISSUE TITLE
Bayonetta Visual Glitching in Chapter XIII

### ISSUE THREAD

**Issue by DomoPANDAS** [yuzu-emu/yuzu#7598]
The cutscene seems to play fine but once you actually get to gameplay you can't even see Bayonetta most of the time because she's "underwater". Idk if the water textures are being loaded too high or if somehow Bayo's actor is being placed too low beneath the surface but it's obviously not working as intended. I've fiddled with a few options and none of them seemed to make a difference. Hopefully I just missed something but everything else in the game appeared well enough and this is the first glaring visual bug I've encountered. Additionally I've recently noticed the game's volume is significantly quieter than other games despite using the exact same settings.

In the examples the first pictures are with the camera in a "normal" position, and the second picture is of it as far down as it can go, which is ends up below the water's surface in Yuzu.

How it looks currently:
https://ibb.co/wYLvyVX
https://ibb.co/XVBB959

How it should look:
https://ibb.co/nLgk7zV
https://ibb.co/Dg0yhNn

My Setup:
Yuzu: v853 (was 824)
CPU: R7 2700X
GPU: GTX 1080Ti
OS: Win10 v19042
Nvidia Driver: v472.12

Here's an upload of the autosave at the chapter in question for testing:
https://mega.nz/file/PEMCgBTI#pL7anyL6LPwupRQRmLiV39Fwk6GyOHDfqIR3HRPTBdw

Log File:
https://mega.nz/file/HQlWCJoY#JIK2u5tJgvePWRC2cUxf4mjZmeuh24KxMRYyByEGcKI

Log File after updating/changing settings and reverting Nvidia driver:
https://mega.nz/file/jA0BSapK#kaainfAgUgNyk1ebAvvo6r9e9Mc5_yAZGlRG-Htpf58

**Comment by G-Spawn** [comment]
Could you please provide a log file as well

**Comment by G-Spawn** [comment]
Could you please provide a log file as well

**Comment by DomoPANDAS** [comment]
> Could you please provide a log file as well

Log file has been uploaded.

**Comment by G-Spawn** [comment]
If you're able to compare on updated yuzu that would be to your benefit. Settings wise please keep async shaders disabled in config graphics advanced. As well cpu accuracy set to auto please.

**Comment by DomoPANDAS** [comment]
> If you're able to compare on updated yuzu that would be to your benefit. Settings wise please keep async shaders disabled in config graphics advanced. As well cpu accuracy set to auto please.
> 
> Also there is issues with the newer nvidia driver. If you could compare with 472.12 driver that would be helpful to rule out that.

Tested again and the issue persists after updating Yuzu to 853, making the requested settings changes, and reverting my Nvidia driver to 472.12.

I added the new log file as well.

**Comment by gidoly** [comment]
this should be adressed on new build
![yuzu_IMcwc08fYY](https://user-images.githubusercontent.com/66776795/175807612-6d224e54-76fe-4894-b9aa-dfebe6a8c509.jpg)
s

**Comment by gidoly** [comment]
sorry false alarm mistake with bayo 2

**Comment by Bjorn29512** [comment]
can you upload the save again the game doesnt seem to detect the one you provided

**Comment by gidoly** [comment]
can be fix by enabling reactive flushing option
