### ISSUE TITLE
Should "stop emulation", "restart emulation" actions have hotkeys by default? 

### ISSUE THREAD

**Issue by rujiel** [yuzu-emu/yuzu#7601]
Right now they default to F5 and F6. I didn't know about these hotkeys and hit one of them by accident when picking up my keyboard. If that were in the middle of a game save, I think that could potentially be bad.

**Comment by G-Spawn** [comment]
You can remap them in the yuzu hotkeys as long as it is valid.

**Comment by rujiel** [comment]
I know you can change them, my point was whether it *should* default to those when it can be prone to user error

**Comment by G-Spawn** [comment]
Hasn't been an issue yet. You're the only one to really bring that up.

**Comment by G-Spawn** [comment]
Haven't heard of this even with users playing with keyboard / mouse. So I don't imagine it impacts the majority of the user base. Especially since the restart - stop hotkeys break anyways depending on if you're windowed - fulslcreen.

**Comment by rujiel** [comment]
It would be nice if there were a way to map those keys to nothing. I don't really need those hotkeys, they are a liability. 

And sure maybe I'm an idiot, but this is gaming software meant for anybody, not an IDE meant for devs. I'm just the first least common denominator user to mention it. In a few years maybe you'll have someone else whine about how their save game was corrupted by their cat jumping on their keyboard.

**Comment by G-Spawn** [comment]
![image](https://user-images.githubusercontent.com/23653025/146654910-e77b6f23-bd45-414e-a28f-b02f32193f3c.png)
 Right click clear perhaps ?

**Comment by rujiel** [comment]
Ahh thank you.
