### ISSUE TITLE
[Vulkan] Broken shadows in Monster Hunter Generations Ultimate

### ISSUE THREAD

**Issue by Narugakuruga** [yuzu-emu/yuzu#7606]
yuzu EA 2359
Windows 10 
AMD 4500U intergrated graphics
Drivers 21.8.2

This part of shadow will flicker heavily if the camera is moving. otherwise it will be still.
I think the older version (months ago) does not have the glitch

![屏幕截图(4032)](https://user-images.githubusercontent.com/31060534/146728259-4f6f8694-1f09-4c09-b5e5-bd24bff26fd8.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7743266/yuzu_log.txt)

**Comment by G-Spawn** [comment]
We don't support piracy here
