### ISSUE TITLE
[Vulkan] Broken shadows in Monster Hunter Generations Ultimate

### ISSUE THREAD

**Issue by Narugakuruga** [yuzu-emu/yuzu#7607]
yuzu EA 2359
Windows 10
AMD 4500U intergrated graphics
Drivers 21.8.2

This part of shadow will flicker heavily if the camera is moving. otherwise it will be still.
I think the older version (months ago) does not have the glitch
![146728259-4f6f8694-1f09-4c09-b5e5-bd24bff26fd8](https://user-images.githubusercontent.com/31060534/146730337-7d724cef-393c-4022-9aa3-242d5245eacc.png)

(The game in in official Chinese language setting)
![IMG_20211220_154656](https://user-images.githubusercontent.com/31060534/146730974-535ae7e7-b8dd-42f0-9ae3-02f916a679b5.jpg)

**Comment by G-Spawn** [comment]
We still don't support piracy here. Stop making issues or you'll be banned.
