### ISSUE TITLE
The analog of virtual joycon is reversed

### ISSUE THREAD

**Issue by 020794** [yuzu-emu/yuzu#7611]
YUZU version was bd40aee3c.

The input device was "PS4 Controller".

The virtual gamepad was set to "Left Jonycon".

"Left Stick" was configured and I moved joystick "Vertically" first.

Then the up and down of the virtual joycon analog was reversed, btw the left and right was correct.

Same problem occured for the "Rigth Joycon".

**Comment by german77** [comment]
Nintendo is the one with the Y axis inverted. I actually fix this issue by flipping the Y axis on all controllers but since you are mapping the controller inverted this workaround is not valid anymore.

Yuzu allows to invert any axis with right click over the axis button.

**Comment by 020794** [comment]
> Nintendo is the one with the Y axis inverted. I actually fix this issue by flipping the Y axis on all controllers but since you are mapping the controller inverted this workaround is not valid anymore.
> 
> Yuzu allows to invert any axis with right click over the axis button.

Thx
