### ISSUE TITLE
Rogue Trooper Redux [01001CC00416C000] sky is broken and flashing in Opengl (vulkan is fine) [AMD - GCN issue]

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#7612]
using the latest EA
sky is broken and flashing in OpenGL
![01001cc00416c000_2021-12-21_16-55-44-025](https://user-images.githubusercontent.com/2696404/146901251-65964830-e67b-41cd-8318-2f793725ff36.png)
![01001cc00416c000_2021-12-21_16-55-51-449](https://user-images.githubusercontent.com/2696404/146901309-f7b350c8-00ca-4dee-bd91-f8bbc9b50f8f.png)
Using Vulkan no problems so far
![01001cc00416c000_2021-12-20_18-40-16-272](https://user-images.githubusercontent.com/2696404/146901393-51a0a2b1-1519-4d3e-9105-eaeb3b918c2d.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7750968/yuzu_log.txt)

**Comment by G-Spawn** [comment]
windows support for ogl and amd is very shoddy. You'd have better experience for ogl on linux. Do stick to vulkan on windows for best results.

**Comment by benderscruffy** [comment]
have upgraded to a new computer so can not test it with old computer anymore
