### ISSUE TITLE
[Regression]  World of Goo - 010009E001D90000 doesnt boot anymore

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#7617]
the last version that booted it was EA 1298 and then EA 1308 doesn't
so something in-between those 2 killed it
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7761389/yuzu_log.txt)

**Comment by german77** [comment]
Your report doesn't make sense. EA 1298-1308 but the log is 2334??

**Comment by bunnei** [comment]
@german77 that appears to be the log with it broken on a recent EA

**Comment by bunnei** [comment]
Looks like the change was https://github.com/yuzu-emu/yuzu/pull/5324/

Which is just changing the default to docked mode. This game still works in undocked mode, which was the same behavior as before. 

Still digging into the root cause.

**Comment by german77** [comment]
I already debugged the cause. It only works in undocked. On mainline 502 works, 503 doesn't. The default docked mode changed to false to true. 

The game works on mainline 855 only in undocked.

**Comment by german77** [comment]
![image](https://user-images.githubusercontent.com/5944268/147136229-24516c41-33c0-4b08-abb6-2990411617f2.png)

**Comment by Augusto7743** [comment]
@benderscruffy
Excuse ... I not see how send email
benderscruffy you can help in that thread issue about Spelunker ?
You have replied about music tempo being slow.
https://github.com/RPCS3/rpcs3/issues/4904
Thanks

**Comment by benderscruffy** [comment]
this works in hand held mode and TV mode and tabletop mode
https://www.nintendo.com/store/products/world-of-goo-switch/
