### ISSUE TITLE
Ruiner: Hangs on new game start

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#7619]
Game loads to main menu, but then attempting to launch a game from there results in yuzu hanging.  Occurs with both Vulkan and OpenGL backends.

Information:
* OS: Linux Mint 20.2 / kernel 5.11
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070 / driver 470.86
* Compiler: gcc-11.1.0
* Commit: b85f5b13323965ea296a17e9aa81a1c8c8369ea0
* Log: [yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7765339/yuzu_log.zip)

**Comment by gidoly** [comment]
Please post log

**Comment by german77** [comment]
Did this game eat your 32 GB of ram?  try with 8GB of swap. The problem is very likely to be yuzu and not your PC

**Comment by Shoegzer** [comment]
@german77 agreed it does seem to be yuzu.  I created an 8GB swapfile with swapon but with the same results i.e. log being spammed with lines like this:

`
[4356.019363] HW.Memory <Error> core/memory.cpp:operator():498: Unmapped Read32 @ 0x00000000003BE0F4`

**Comment by Shoegzer** [comment]
Update: I just noticed that after updating to 8GB of swap, yuzu spans the new log with lines like this (see end of file):

`[ 142.007840] Core.ARM <Error> core/arm/arm_interface.cpp:LogBacktrace:273: sdk                 00000070F1476FFC    FFFFFFFFFFFFFFFC    FFFFFFFFF1476FFC`

Not sure how this could be related to swap size specifically though.

New log: [yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7793785/yuzu_log.zip)

**Comment by benderscruffy** [comment]
goes ingame now
![Screenshot 2023-05-11 133409](https://github.com/yuzu-emu/yuzu/assets/2696404/00b2bc0e-cdb0-4cff-bde7-05fb4e5c9ecb)
can be closed

**Comment by Shoegzer** [comment]
@german77 can you please re-open this? In testing the latest commit, this title now causes yuzu to crash before the menu loads.  This happens with OpenGL or Vulkan on default settings.  Also in case it matters, tested against title update 1.0.1.  Log excerpt reveals memory issue prior to crash:
```
[  52.950834] Debug <Critical> common/host_memory.cpp:operator():429: Assertion Failed!
mmap failed: Cannot allocate memory
```
Updated information (all else same as above):
* OS: Linux Mint 21.1 / kernel 5.15
* GPU driver: 525.105
* Compiler: gcc-12.1.0
* Commit: 182221b9ffdee68c0f8c3749868918799f5b3d0f
* Log: [yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/11455428/yuzu_log.zip)
