### ISSUE TITLE
Sound delayed on Pokemon BDSP with unlocked fps

### ISSUE THREAD

**Issue by Mermoud46** [yuzu-emu/yuzu#7626]
Hey, On Yuzu 858 after a more or less long time (from a few minutes to one hour) with fps unlocked (limited to 60 fps) on Pokemon BDSP (here its on Brillant Pokemon) the sound becomes delayed by approximately 1s. It happen on OpenGL/Vulkan and on every output engines (Cubeb,sdl2,auto). I'don't know why this happen but it happen every time i'play Pokemon BDSP and its just so boring. Thanks for your time and good christmas

**Comment by FernandoS27** [comment]
that feature may break things as it's not expected by the game. Use a 60 fps mod instead.

**Comment by Mermoud46** [comment]
Bug still happen with mod when it doesn't on real console, so i'think its a yuzu bug?

**Comment by FernandoS27** [comment]
bug is only yuzu's responsability if and only if it does not happen on hardware. Mods may alter the game and make it do things it did not intend, you must check on your switch.
