### ISSUE TITLE
King's Bounty II crashes with what(): std::bad_alloc Aborted (core dumped)

### ISSUE THREAD

**Issue by mozo78** [yuzu-emu/yuzu#7628]
Hello,
Yuzu always crashes at the same place for King's Bounty II on Linux. The game is starting fine, you can navigate through the main menu, to select a hero or change some options, but as soon as you start a new game, Yuzu always crashes at the loading screen with the following error:
`QPixmap::scaled: Pixmap is a null pixmap
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
terminate called after throwing an instance of 'std::bad_alloc'
 what():  std::bad_alloc
Aborted (core dumped)`

I tried many appimage versions (newest, newer and older), yuzu-git, yuzu-mainline-bin and yuzu-mainline-git. I tried on Arch and Linux Mint with the same result. I tried many different options configurations but they made no difference. The game is running fine with the Windows version of Yuzu and Wine though but it can't be started in Vulkan mode for it crashes. Only OpenGL mode is working with Wine.

I'm using NVIDIA GTX 1080Ti with the latest available driver. I also tried with older versions to no avail.

**Comment by mozo78** [comment]
Tries the latest version from today - still no dice.

**Comment by mozo78** [comment]
Using `sudo sysctl -w vm.max_map_count=262144` solves the problem.

**Comment by v1993** [comment]
I think it may be a good idea to keep this issue open, since it's valid. This seems to be related to SMVT crashes in #7397 (which is where you got this command, I presume).

**Comment by mozo78** [comment]
From a Reddit thread, but yes, it was for SMVT :)

**Comment by Tachi107** [comment]
@mozo78 could you please close issue #7569? You reported this crash twice

**Comment by mozo78** [comment]
Done.

**Comment by benderscruffy** [comment]
please close
