### ISSUE TITLE
Request - Please, reopen https://github.com/yuzu-emu/yuzu/issues/3252

### ISSUE THREAD

**Issue by LuismaSP89** [yuzu-emu/yuzu#7632]
Please, reopen the issue https://github.com/yuzu-emu/yuzu/issues/3252 since this is not yet fixed and still happens to everybody who has set a profile image.

**Comment by german77** [comment]
Upload a new profile image to your user. This issue was fixed long ago. Old profiles images will still cause issues

**Comment by LuismaSP89** [comment]
Nice! Thank you so much @german77 now it's solved.

Btw, maybe they should update the game's database page in order to help other people to solve this issue.
