### ISSUE TITLE
Metroid Dread Room Transition Crash

### ISSUE THREAD

**Issue by BOB74j** [yuzu-emu/yuzu#7638]
Metroid Dread frequently crashes when transitioning between rooms, about every 10-20 minutes of gameplay. No error message is displayed on exit. The door transition just remains black momentarily before yuzu disappears.

- yuzu version: 861 (2021-12-28)
- OS: Windows 10 21H1
- CPU: i7-7500U CPU @ 2.70GHz
- GPU: Nvidia 940MX
- RAM: 8GB
- Renderer: OpenGL

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7786679/yuzu_log.txt)

**Comment by gidoly** [comment]
Try vulkan api, set page file to 20gb
Github is for  issue tracker not support forum.
For support please visit our discord

**Comment by gidoly** [comment]
close as issue is more of support request
