### ISSUE TITLE
Audio breaks up while using nvdec in Skyward Sword HD

### ISSUE THREAD

**Issue by mark007** [yuzu-emu/yuzu#7645]
**The Problem**
I am having very smooth performance with yuzu on my system, even at 2X resolution. However when I tried Skyward Sword HD for the first time today, I notice the opening intro scene (which I understand uses nvdec to play back), it plays what looks like perfectly visually, however the audio stutters/glitches fairly badly.

After a brief discussion in the discord channel, and not being able to find the same issue logged as an issue, I thought best to log it here.

**My Setup - Software**
Yuzu: Version 863
Game: The Legend of Zelda™: Skyward Sword HD (01002DA013484000), patch 1.0.1
OS: Windows 11, latest windows updates.

**My Setup - Hardware**
CPU: AMD Ryzen 9 5950x
Motherboard: ASUS Crosshair VIII Dark Hero
GPU: MSI RTX 3080, driver 497.29
Mem: 32GB DDR 3600
Screen: 4k LG C1 77 TV
Audio: Sending audio directly through HDMI out to the TV. (Tried sending audio out through a VR headset and I heard the same audio distortion).

**Things I have tried:**
Switching between OpenGL/Vulkan
Switching graphics scaling between 2x and 1x
Trying NVDEC set to use gpu/cpu. (Only disabled eliminates the audio issue, I guess because the 'video' doesn't play back at all.)

Logs attached with graphics debugging enabled. I can provide more if required.

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7791184/yuzu_log.zip)

**Comment by G-Spawn** [comment]
This issue doesn't seem to be present on latest yuzu versions. Please reopen this issue should it still be apparent to you on updated yuzu.

**Comment by mark007** [comment]
Unfortunately on build 915 it still happens for me. The audio sounds like its glitching/stretching for the entire opening intro video. Should it be reopened? I guess its specific to my cpu/gpu model but I see other forums and discord questions about it so I assume many others can reproduce it.

**Comment by G-Spawn** [comment]
Yeah doesn't hurt to reopen. Thank you for testing and reporting back!

**Comment by mark007** [comment]
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/8055535/yuzu_log.zip)
Log attached. The only errors I see are some audio related ones, so not sure if they give a hint as to why it has a slightly garbled/torn/stretched sound. I do see on the MSI Afterburner / RTSS frame time graph, the fps is 60, but has a slight jitter to it. Nothing too bad but slight. Even going down to 1x instead of 2x, it stays at 60fps with the slight jitter. Is it possible that the jitter in the frame times matches the jitter in the sound I hear. I can see that slight hitch/jitter on screen also, its never perfectly smooth but I imagine my hardware should be able to play back the video fine.

`[ 136.339191] Audio <Error> audio_core\splitter_context.cpp:RecomposeDestination:385: Invalid splitter info size! size=0
[ 136.339194] Audio <Error> audio_core\splitter_context.cpp:RecomposeDestination:385: Invalid splitter info size! size=0`

**Comment by G-Spawn** [comment]
@mark007 Please try to use auto cpu accuracy and let us know if this issue still persists. Sorry it took me so long to get back to you XD

**Comment by mark007** [comment]
Hi @G-Spawn I have my cpu accuracy set to Auto. I rechecked in build 1047 now and it still has the strange sound issue in the main introduction clip when the game starts. Have you guys also reproduced it, just so that I know its not me.

**Comment by mark007** [comment]
Strangely it happens also with Ryujinx when I downloaded and tested it this morning. I wonder do they share some common piece of code that could be responsible, either that or I need to redump the game.

**Comment by G-Spawn** [comment]
This seems to also be capable of happening on native console. It isn't something that will be easily solved in emu.

**Comment by Kelebek1** [comment]
This is a hard one to solve, the game just submits audio data too slowly. Looked at it for a few hours but couldn't figure out what can be, no idea why the game is going too slowly. Not sure if it's related to bad video playback timing or something else...

**Comment by mark007** [comment]
Thanks so much for looking into it. I assume you have been able to reproduce it also or is it the case that only some machines would show it?

**Comment by mark007** [comment]
Ah ok thanks for the explanation. Has there ever been a cpu implementation of the decoding to compare against nvdec. It might be an option if it's fast enough for some users, and doesn't exhibit the issue?

**Comment by mark007** [comment]
I'm wondering what the physical hardware is doing. As a complete guess, does it have some particular size of an audio buffer, so that even if chunks of video/audio are delivered at different intervals, the audio buffer ensures there's no audio glitches. Does the old/new audio back-end have control over the audio buffer to ensure that there's no 'gaps' if that's the right terminology.

**Comment by mark007** [comment]
Oh wow thanks for the fix for this @liamwhite Out of interest, what was the solution to solve this one as I know it was of the strange / odd one out type audio issues.

**Comment by liamwhite** [comment]
The entire audio backend was rewritten to more closely match what would be done on the console.
