### ISSUE TITLE
Huge glow at YW4 

### ISSUE THREAD

**Issue by Greninjashme** [yuzu-emu/yuzu#7655]
When I start the game in any version of yuzu the game looks like I have 15 or 20 lights in front of me all the time, the bug only occurs when leaving Nathan's house. 

![Captura de pantalla (61)](https://user-images.githubusercontent.com/96908919/147816256-8fb87872-bba5-48c6-9591-79a382fabc88.png)
![Captura de pantalla (62)](https://user-images.githubusercontent.com/96908919/147816257-50845221-67ca-4e30-8039-6ce145a1c3d7.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7797452/yuzu_log.txt)

**Comment by gidoly** [comment]
Please post log on issue

**Comment by Greninjashme** [comment]
> Please post log on issue

I already put the log under the images

**Comment by G-Spawn** [comment]
Will be fixed by the project mentioned above. (https://github.com/yuzu-emu/yuzu/pull/8467)
