### ISSUE TITLE
Manjaro linux : error while loading shared libraries

### ISSUE THREAD

**Issue by Catiks** [yuzu-emu/yuzu#7665]
In manjaro system, i get this error:
yuzu: error while loading shared libraries: libboost_context.so.1.78.0: cannot open shared object file: No such file or directory
## boost-libs
The system boost-libs version is 1.76.0-2
sudo pacman -S boost-libs
警告：boost-libs-1.76.0-2 已经为最新 -- 重新安装
正在解析依赖关系...
正在查找软件包冲突...

软件包 (1) boost-libs-1.76.0-2

## System information
OS: Manjaro 21.2.0 Qonos
Kernel: x86_64 Linux 5.15.7-1-MANJARO

**Comment by Joey11904** [comment]
are you using appimage or the .tar.xz binaries?

**Comment by Catiks** [comment]
> 

I install it using the AUR: pacman -S yuzu,  yuzu-early-access-2362-1 is installed:  https://aur.archlinux.org/packages/yuzu-early-access/

**Comment by Tachi107** [comment]
@Catiks that's probably an issue with the build provided by the AUR, there's not much the yuzu devs can do here, you should report this error to the package maintainer. Also, if you want to use the Early Access version, consider supporting the yuzu team on Patreon - while using the EA builds for free is legally allowed, it's not really respectful :)

**Comment by gidoly** [comment]
close with reason that  tachi mentioned

**Comment by Cytomax55** [comment]
I am getting this exact bug using manjaro... strange that it just popped up for me when this has been present since January 2 2022

**Comment by Tachi107** [comment]
> just realized yuzu git is out of date

Please clarify. You mean that the yuzu-git package shipped in Arch Linux's AUR is outdated?

**Comment by Cytomax55** [comment]
i was using yuzu-git on the aur and i got the same error just now... it went to look and it hasnt been updated since June 14, 2022 and it is claimed to be out of date as of July 25 2-22
https://aur.archlinux.org/packages/yuzu-git

**Comment by Tachi107** [comment]
Please report AUR issues to the AUR maintainer. The yuzu team can't do anything about issues with downstream packages (and downstream packagers should avoid distributing poor packaging...).
