### ISSUE TITLE
[WarioWare: Get It Together!] Certain microgames crash Yuzu, and cause corrupted Vulkan shaders?

### ISSUE THREAD

**Issue by iCeParadox64** [yuzu-emu/yuzu#7667]
**CPU:** Ryzen 5 2600 @4.1GHz  
**RAM:** 16GB DDR4  
**GPU:** GTX 1660 Ti
**API:** Vulkan *(issue does not happen with OpenGL)*

In *WarioWare: Get It Together!*, certain microgames instantly crash Yuzu when using the Vulkan API. Not only that, but afterwards, the game will not launch at all. It will only begin loading the shaders, then get stuck on the very last one before crashing again. The only way to get the game to launch again is to delete its `vulkan.bin` shader file, but the exact same thing will happen again upon coming across one of the offending microgames, making me think this crash somehow corrupts the shader cache and makes the game unplayable. This issue does not happen when using OpenGL.

These are the broken microgames that I've found, along with a log file for the crash (I'll add more as I find them):  
[**The Legend of Zelda: Breath of the Wild**](https://www.mariowiki.com/The_Legend_of_Zelda:_Breath_of_the_Wild) (9-Volt) - [Log File](https://github.com/yuzu-emu/yuzu/files/7800759/yuzu_log.txt)  
[**Luigi's Mansion**](https://www.mariowiki.com/Luigi%27s_Mansion_(microgame)) (9-Volt) - [Log File](https://github.com/yuzu-emu/yuzu/files/7800764/yuzu_log.txt)
[**Burst Your Bottle**](https://www.mariowiki.com/Burst_Your_Bottle) (Ashley) - [Log File](https://github.com/yuzu-emu/yuzu/files/7800183/yuzu_log.txt)  

If any more info is required from me, please let me know!

**Comment by angelNight20** [comment]
The coins in the bonus stage are invisible.

**Comment by benderscruffy** [comment]
tested these 3 mini games and had no problem at all
can be closed
