### ISSUE TITLE
AMD Graphic issues in Unreal Engine games

### ISSUE THREAD

**Issue by RinMaru** [yuzu-emu/yuzu#7671]
Windows 11 x64
AMD RX 480 4GB 21.11.3
R5 5600X
20GB Ram

EA 2365

![0100c3c012718000_2021-11-16_20-35-55-142](https://user-images.githubusercontent.com/15071652/148002662-85f558b9-6894-4484-83fe-dde724408e11.png)
![01006000040c2000_2022-01-03_21-42-27-933](https://user-images.githubusercontent.com/15071652/148002677-12d7ae6d-3dc3-486a-8a39-a91c9248577f.png)
![010073401175e000_2022-01-03_21-45-19-322](https://user-images.githubusercontent.com/15071652/148002826-b7743c9e-b7e7-4794-a9b5-f760076a2cf4.png)
![0100ad10102b2000_2022-01-03_21-47-11-408](https://user-images.githubusercontent.com/15071652/148002974-75f5b09e-46d4-406d-aa9f-13af7f0811ff.png)

**Comment by FernandoS27** [comment]
Could you be descriptive on the bugs?

Some may not be AMD bugs but GCN bugs instead.

**Comment by RinMaru** [comment]
First 3 games exhibit what looks like mipmap issues square dots on textures that appear along with rainbow textures in some places. Bioshock on the ground the tickets on the floor disappear when distant (the rectangle outlines)

**Comment by bearoso** [comment]
> Could you be descriptive on the bugs?
> 
> Some may not be AMD bugs but GCN bugs instead.

This is the same as #7321.  It's also there on Vega and RDNA 1/2.

I think it's a texture barrier problem. My thought is the blocky pattern probably means the texture is being used before it's done converting.

**Comment by RinMaru** [comment]
all fixed as of #9194
