### ISSUE TITLE
Mandarin font showing as ????

### ISSUE THREAD

**Issue by Casiyus** [yuzu-emu/yuzu#7676]
Hello so i found that the solution to this problem is in https://github.com/yuzu-emu/yuzu/pull/3151/files/845a5dbca9a456696202b96ad895e78949790ee8 but I do not understand how to fix it manually, where to put the file or code. I would appreciate some help. Thank you.

**Comment by german77** [comment]
You need to dump your firmware and add it to yuzu

**Comment by Casiyus** [comment]
Can you please elaborate further, I am a total noob in this. Where is my firmware and where in yuzu should I dump it ?

**Comment by CaptV0rt3x** [comment]
Nintendo Switch firmware needs to be dumped from your console and then added to yuzu.

You'll find detailed how-to instructions in our quickstart guide https://yuzu-emu.org/help/quickstart/#dumping-system-update-firmware

**Comment by Casiyus** [comment]
Is there a way I can do this without a console ?

**Comment by german77** [comment]
No, an unpatched switch is required to use yuzu.
