### ISSUE TITLE
Vulkan API not working since the last update

### ISSUE THREAD

**Issue by dolansete** [yuzu-emu/yuzu#7685]
I've been playing for some days smash bros ultimate, mario oddysey and zelda BOTW with the Vulkan API but since the last update it doesn't work (OpenGL works)

**Comment by Norstyrm** [comment]
Please add a detailed issue description

**Comment by G-Spawn** [comment]
Update gpu drivers. If you're already updated, reinstall the update.

Beyond that please stick to support in the discord as this is an issue tracker for the emulator.

**Comment by dolansete** [comment]
Thank you! I downgraded my AMD drivers and it worked again
