### ISSUE TITLE
Loading Invalid TAS Recording Causes Crash

### ISSUE THREAD

**Issue by VD-15** [yuzu-emu/yuzu#7686]
## Description

Loading an invalid or malformed TAS script with TAS features enabled will cause Yuzu to crash and may subsequently cause yuzu to crash on launch. I found this happens with TAS scripts with one or more frame numbers missing midway through the file, I imagine there are other edge cases that could cause this, too.

## Steps to Reproduce

1. In a file explorer, open yuzu's user directory and in the `tas` subdirectory, create or edit the file `script0-1.txt` with the following content (note the whitespace at the beginning of line 4):

```
0 NONE 0;0 0;0
1 NONE 0;0 0;0
2 NONE 0;0 0;0
  NONE 0;0 0;0
```

2. In yuzu, go to `Tools -> TAS -> Configure TAS...` and check `Enable TAS features`
3. Launch a game
4. Go to `Tools -> TAS -> Reset` (Or press Ctrl+F6) and yuzu will crash

Yuzu will also fail to launch after crashing this way. Presumably due to it attempting to load the malformed file on startup. Fixing the syntax error in `tas/script0-1.txt` or deleting it will then allow yuzu to launch normally.

## System Information

Issue was confirmed present on yuzu-mainline release 872 (commit 4e9911a) installed via AUR package.

- OS: Arch Linux
- Kernel: x86_64 Linux 5.15.13-arch1-1
- CPU: AMD Ryzen 7 3800XT 8-Core @ 16x 3.9GHz
- GPU: AMD Radeon RX 6700 XT (NAVY_FLOUNDER, DRM 3.42.0, 5.15.13-arch1-1, LLVM 13.0.0)

## Logfiles and Backtraces

I've attached yuzu's logfile generated from my session reproducing the crash. I was not able to generate a backtrace from this session but I was able to generate one when Yuzu was crashing on launch, which i have also attached:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7833647/_yuzu_log.txt)
[backtrace.txt](https://github.com/yuzu-emu/yuzu/files/7833649/backtrace.txt)

**Comment by german77** [comment]
Thanks for reporting I will fix it soon

**Comment by MonsterDruide1** [comment]
There are probably a lot of similar issues to this one, regarding misformatted files. The current implementation does not have many checks in place to avoid crashing from broken files, so fixing this one might be better done in a complete overhaul of the file loading code, introducing checks for ... _everything_.

**Comment by german77** [comment]
This is what happens when you let users input their own data.  I already addressed this issue. But the overall file reader should be made more robust.
