### ISSUE TITLE
Issue with Loading "Shaders x / y" and "Launching..." screen visuals

### ISSUE THREAD

**Issue by MarioPossamato** [yuzu-emu/yuzu#7688]
## Description
If Fullscreen is toggled while on the "Loading Shaders x / y" or "Launching..." screens, the visuals stop updating.
## Steps to Reproduce
Start a game, and toggle Fullscreen, either by navigating to `View -> Fullscreen` or by pressing F11.
## Release Version
This issue is present in [mainline-0-873](https://github.com/yuzu-emu/yuzu-mainline/tree/mainline-0-873) ([0903f3c](https://github.com/yuzu-emu/yuzu-mainline/commit/0903f3c01fc568cf518acc12ad94a42598b7e1b9)).

If any more information is required, please let me know!

**Comment by G-Spawn** [comment]
Please reopen this issue should it happen to you still on latest yuzu
