### ISSUE TITLE
[Vulkan/Xenoblade DE] The emulator closes before loading the shaders.

### ISSUE THREAD

**Issue by borrrris** [yuzu-emu/yuzu#7693]
AMD Ryzen 5 2400G @3.9GHz
Radeon Vega 11 @1.5GHz (Software Radeon 21.12.1 - latest update)
2x8GB RAM DDR4 2.4GHz
Windows 10 Home 64bit 21H1
Yuzu 875
------------------------------------------------------------
When running Xenoblade the emulator closes before loading the shaders, this only happens using Vulkan (with OpenGL it runs normally), in addition to being the only game with this problem. This problem is maintained by changing other parameters in the configuration.

(Image of the moment before the emulator closes):
![xenoproblem](https://user-images.githubusercontent.com/87919087/148817754-df0afa51-2ed5-4475-bb3a-7284c3ac7b83.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7841048/yuzu_log.txt)

**Comment by pacoa-kdbg** [comment]
@gidoly it works here, latest AMD software, using Vega 8 (5825U) and mainline 1090
![image](https://user-images.githubusercontent.com/29181120/179158330-7461dd9b-ad8b-47c5-a0fe-7756c759aa32.png)
