### ISSUE TITLE
Slow motion controls are stuttering

### ISSUE THREAD

**Issue by krisvasq** [yuzu-emu/yuzu#7696]
I'm using yuzu 875 on win10 64 bit, i-9700, gtx1080ti, 16gb ram. 

In recent yuzu releases, i'm selecting native input device support (PS4, Dual Joycons) and found motion aiming too laggy and stuttering when moving very slowly for precision aiming - it mostly stops like it's caught in a deadzone, which is pretty annoying when playing games like RE revelations 1,2, Botw etc. 

I'm sure I never experienced this before, when I was using DS4windows or Betterjoy in previous yuzus.
However, interestingly, now DS4windows or Betterjoy method are also stuttering like a native controller in yuzu.

Have tested botw in cemu, and some other shooting games in Dolphin with the same controllers, and slow motion aiming works like a charm without any lag or stuttering, so I guess it's yuzu specific.   Some kind of accelerometer handling issue inside yuzu?  I don't know. 

Please advise.   Thanks.

**Comment by german77** [comment]
Can you verify that they work fine in https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-872 I recently pushed up the deadzone to avoid gyro drift

**Comment by krisvasq** [comment]
Thank you very much!
I verified 872 works just fine.  So will the deadzone be removed in a later release?
I'm not sure what the gyro drift is, but I would definitely choose precision aiming if I had to trade them off. 
Thanks again, german77!

**Comment by german77** [comment]
Are you on discord? I would like to agree on a deadzone value that works for both. I'm narr the reg.

**Comment by krisvasq** [comment]
Sorry I can't join discord now.
To me, the current deadzone level in 872 is already quite on the edge,  so if it becomes greater, then I believe the aiming will get unsatisfactory again. 
My suggestion is that other than hardcoding dz value, would it be possible for you to add a UI in config so users can adjust dz at their own taste?  
Thank you.

**Comment by german77** [comment]
872 is literally no deadzone. I will open a PR with a lower value so you can test the artifact.

I can open the motion config but most custom values would break the motion and render it unusable like in your case. Here I just guessed a small value to be considered safe. But in your case you are using "precision aiming" which reduces the amplitude of the motion requiring an even smaller value.

**Comment by krisvasq** [comment]
Let me know once a new build is out with an adjusted deadzone.   I will test if it is still an acceptable level.  
Thanks for your support.

**Comment by german77** [comment]
The new build has been ready for an hour https://dev.azure.com/yuzu-emu/yuzu/_build/results?buildId=17013&view=results

**Comment by krisvasq** [comment]
Thanks.  I have tested yuzu-windows-mingw-20220112-ac7decbca_pr-verify, and the slow & accurate motion aiming feels pretty good mostly like 872.   Will it be included in an official build soon? 
Thank you again for listening to the feedback and for the immediate fix !

**Comment by german77** [comment]
It's already on EA. Should be merged soon. Thanks for making sure it workd now
