### ISSUE TITLE
joycons  not correct to horizontally control

### ISSUE THREAD

**Issue by Fzx42** [yuzu-emu/yuzu#7702]
Hi~~some games like Heave Ho,Unruly heroes,Moving out....etc. need joycon  hold horizontally to control,but alaways vertical....how to fix it,Thx

i use real joycon  BT AX200

**Comment by german77** [comment]
Have you confirmed that a real switch handles them horizontally. I will test one soon in the mean time

**Comment by Fzx42** [comment]
Hi~i use same joycon,same controller setting!play mario 3d world and mario kart8!joycon correct work on horizontally!but play Heave Ho...etc!not correct work on horizontally!become vertical

**Comment by xiananliu** [comment]
hi，my 3rd part joycon work well on mario kart8, but can not work on Mario tennis and Mario golf。mybe the same question。

**Comment by xiananliu** [comment]
Additional ，when i use yuzu version 782 ，my joycon work well on Mario tennis and Mario golf

**Comment by german77** [comment]
latest mainline should work well with mario tennis. This is unrelated to this issue.

**Comment by german77** [comment]
This can be solved by manually mapping it horizontally
