### ISSUE TITLE
Bug: Board in Picross S2 stays blank

### ISSUE THREAD

**Issue by TheFloydman** [yuzu-emu/yuzu#7708]
Yuzu Version: 878
Game: Picross S2 versions 1.0.0 and 1.2.0
Log file: https://pastebin.com/95juDpB3
System info: https://pastebin.com/TpEN2EWb

Details:
When playing Picross S2 with yuzu, there is a purely graphical issue that makes gameplay impossible. When starting the game, the first puzzle you start will allow you to make one mark on the board. Trying to place a second mark makes all marks invisible thereafter. The game correctly tracks where you have placed marks, but you cannot see them and cannot complete the puzzle without perfect memorization. This bug occurs with standard puzzles and Mega variants. I have run the game with both OpenGL and Vulkan, and the issue is identical. The issue does not appear to exist in Picross S and Picross S3.

Images:
<img width="438" alt="box" src="https://user-images.githubusercontent.com/22880199/149439559-eb616bd3-b416-4f57-af69-ebca969c577c.png">

<img width="438" alt="blank" src="https://user-images.githubusercontent.com/22880199/149439553-9027165e-17af-456c-be54-99d633d4c25a.png">

**Comment by Mino260806** [comment]
also encountred this issue. strangely it doesnt happen in all other picross S games (1, 3, 4, 5, 6, 7)

**Comment by subworx** [comment]
+1, just stumbled over this.
Yuzu 1181 on Steam Deck, as well as 1183 on Windows, both on Vulkan, game version 1.2.0.

**Comment by TheFloydman** [comment]
Playing this on Steam Deck right now with the latest stable build, and it seems to have been resolved. Can anyone else confirm?

**Comment by subworx** [comment]
Yuzu 1378, Picross S2 1.4.0: works as expected, tried one level only.

**Comment by TheFloydman** [comment]
We'll, lucky us. Seems to have been indirectly fixed somewhere along the way.
