### ISSUE TITLE
Nvidia driver 511.23 causes graphical issues.

### ISSUE THREAD

**Issue by RodrigoTR04** [yuzu-emu/yuzu#7714]
The recent Nvidia driver 511.23 (Jan 14th 2022) introduces graphical issues on yuzu on many games (users reported that it also affects other programs). Some screenshots are attached below for the games Animal Crossing: New Horizons, Super Mario Odyssey and Pokémon Brilliant Diamond, but it also affects many other games.

Seems to only occur on the Vulkan API (from the games I tested)
Last working driver is 497.29 (Dec 20th 2021) <https://www.nvidia.com/en-us/drivers/results/184717/>

![image](https://user-images.githubusercontent.com/65554156/149621081-ff993505-6b49-4912-9bc5-6cf2def37bbb.png)
![image](https://user-images.githubusercontent.com/65554156/149621086-ee5c5e6d-387d-40da-9314-38b22a5abdf0.png)
![image](https://user-images.githubusercontent.com/65554156/149621088-3e8cad8f-d2de-4df1-8170-accf66d117b7.png)

**Comment by SleepingSnakezzz** [comment]
The devs are probably already aware, but for anyone looking for why their game has graphical glitches on the issue page, maybe add on what APIs this occurs (if it doesn't occur on both), as well as link the last driver that works here until NVIDIA gets their crap together or yuzu's devs figure out how to work around the new bugs?
