### ISSUE TITLE
joycons can not work on mario tennis & mario golf

### ISSUE THREAD

**Issue by xiananliu** [yuzu-emu/yuzu#7723]
My 3rd party joycons can recognize， work well on mario kart 8. But on  mario tennis & mario golf,
My joycons only works for the first few minutes, and then ，there was no response to motion Sensing.
Only mainline version 782 can work correctly，i tested the leatest version 880 ，it Still not working properly.

I hope you can solve this problem first, because it makes many motion Sensing games completely unusable. Thank you very much

**Comment by german77** [comment]
Does they work properly on 827? https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-827
And are they broken on 828? https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-828

I pushed a fix on 880 and used motion without issues on Mario tennis. So I need a way to reproduce the issue or at least have a hint on where it broke

**Comment by xiananliu** [comment]
827 ,828 , 880  all broken , only 782 work properly .
In swing mode, there is no response when waving the racket.

**Comment by german77** [comment]
That's rather strange from 782 to 827 there aren't any change that affects motion. Maybe it's just a mapping issue try remapping motion on a newer build.

If that doesn't work is it too much to ask to find the mainline that broke it? you should be able to find it by testing 5 mainline with a binary search

**Comment by xiananliu** [comment]
ea 2437 ，one pair can work properly,p1 p2  together broken

**Comment by dlutwy** [comment]
@german77 
https://github.com/yuzu-emu/yuzu/issues/7915
There is a bug related to motion. Hope it can be fixed soon.

**Comment by german77** [comment]
This should be fixed
