### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by camoltoni** [yuzu-emu/yuzu#7736]
I found this solution for a problem with a game:

Kirby Star Allies
Issues:
*Depth of field effect not works properly

Additional notes:
AMD GPU users running Mesa with OpenGL should set the environment variable force_integer_tex_nearest=true to resolve black texture issues.

I'm in Kubuntu 21.10 where I have to set that environment variable exactly
Thanks in advance

**Comment by v1993** [comment]
It's done the same way as with any other environment variable for any given program, e.g. `force_integer_tex_nearest=true yuzu`. Please use yuzu's discord for support - this is a bug tracker, not forum.

**Comment by camoltoni** [comment]
Thanks
Sorry
