### ISSUE TITLE
Yuzu suddenly closes before launching the game

### ISSUE THREAD

**Issue by aguirre-erriuga** [yuzu-emu/yuzu#7739]
Early Access: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7891746/yuzu_log.txt)

Regular version: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7891847/yuzu_log.txt)

**Comment by german77** [comment]
Use latest version of yuzu, update your GPU drivers, disable async shaders and set a bigger page file of at least 15GB. After all of this is set upload a new log if the issue still persist.

**Comment by aguirre-erriuga** [comment]
gpu drivers are already updated and i'll set a bigger virtual memory.

regards.

**Comment by aguirre-erriuga** [comment]
updates.

same problems

Early Access: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7891900/yuzu_log.txt)
Regular version: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7891903/yuzu_log.txt)
 
 
and i found this:

[   7.211279] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:Device:396: Device doesn't support float16 natively
[   7.211288] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:Device:448: Device doesn't support list topology primitive restart
[   7.211292] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:Device:486: Device doesn't support extended dynamic state
[   7.211294] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:Device:520: Device doesn't support provoking vertex last
[   7.211295] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:Device:532: Device doesn't support vertex input dynamic state

this is something that i need to worry about?

**Comment by german77** [comment]
Your GPU drivers aren't updated latest is 511.23 you are on 456.71 please use the nvidia website to get the latest driver. Windows updater is not good enough.

**Comment by aguirre-erriuga** [comment]
it was exactly that.

sorry about that... 
I made a windows clean installation yesterday and forgot to update my GPU
thanks for taking your time to help me.

farewell.
