### ISSUE TITLE
Yuzu freezes to 0 fps when I open Photodex in New Pokemon Snap

### ISSUE THREAD

**Issue by arnavraut2006** [yuzu-emu/yuzu#7744]

**Comment by arnavraut2006** [comment]
Please Help

**Comment by v1993** [comment]
This is a bug tracker, not a forum or chat. For direct assistance yuzu discord must be used instead.

**Comment by G-Spawn** [comment]
> This is a bug tracker, not a forum or chat. For direct assistance yuzu discord must be used instead.

Closing for aformentioned reason & lack of relevant information that would help (log, yuzu version, etc)
