### ISSUE TITLE
Yuzu Crashes when using Vulkan for Demon Gaze Extra

### ISSUE THREAD

**Issue by FurbyTime** [yuzu-emu/yuzu#7753]
The title is the entire thing. Yuzu simply crashes (closes) when attempting to start Demon Gaze Extra with the Vulkan backend. It books up successfully with OpenGL. Other games also work with Vulkan without issue.

Log attached is the crash record when booting with Vulkan.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7906984/yuzu_log.txt)

**Comment by NineKain** [comment]
x2, happens to me too

**Comment by NineKain** [comment]
there are also some effects glitched when entering a battle (opengl)

**Comment by FurbyTime** [comment]
I've already beaten the game, but here's what I noticed:

1: The topic of this, where Vulkan just doesn't work anymore on the game and it crashes on boot. There's that, BUT...
2: Early after it's release (A week ago?), Vulkan DID work and boot, but it was lacking numbers on the status screens (So you couldn't, for example, see the actual values of your stats).
3: Any opening effect for the Demons (Be it the starting animation, or when they come out and they have that chain swirling animation) will occasionally glitch out and remain so throughout the fight (It looks like an old texture pointer issue like from back when you used to mess with GB games).
4: The results screen after a battle will occasionally mess up and the demons themselves will be glitchy textures.
5: The texture on 3D objects in the Dungeons (Event Indicators, Items, spawn points, etc) will occasionally either glitch out or just not load, painting the object itself with either a glitchy texture or none (Making it grey).

Vulkan not working is the main concern, of course, but these others do exist.

**Comment by NineKain** [comment]
![image](https://user-images.githubusercontent.com/72826232/150436842-0e64bbb6-fb2e-412a-82cb-19a8cb9ca8e9.png)

**Comment by FurbyTime** [comment]
Wow, that's actually worse than it ever was for me.

**Comment by NineKain** [comment]
> Wow, that's actually worse than it ever was for me.

i think ill keep playing it on switch for the time being, playing it on yuzu rn is worse

**Comment by FurbyTime** [comment]
I did fully beat it on Yuzu, up to and including the Post Game, so it is possible and it's only ever those visual glitches. It might have something to do with the different shader systems (I have a distinct feeling all of what we're talking about were done through shaders rather than anything else).

**Comment by benderscruffy** [comment]
had no problems using vulkan so far
this can be closed
