### ISSUE TITLE
Fire emblem three houses Graphic Issue with 3080 ampere issue?

### ISSUE THREAD

**Issue by CrimsonBrawler** [yuzu-emu/yuzu#7757]
Hi, I upgraded my gpu from a 2060 to a 3080 and when I did the graphic glitch I fixed when I was on a 2060 is back on now that I upgraded to the 3080. The glitch is dark blue/purple and blonde hair have pixels all over them, the blue knife on your hip has a bunch of red pixels and blonde hair has green pixels sprinkled on them.  When I was using the 2060 I would only have this problem when I was on opengl, Vulkan fixed it but for the 3080 neither work in resolving the issue idk if its a 30 series issue I also rollbacked drivers to see if that would resolve the issue and it didn't. Yuzu support said it might be a ampere issue I have no idea how that works though hope this can get resolve.

![glitch 1](https://user-images.githubusercontent.com/98193061/150611452-f497e17b-4800-4e0f-856f-fb7afae2b59d.png)
![glitch 2](https://user-images.githubusercontent.com/98193061/150611453-0d1629a7-1b75-4dea-b96a-bea7585a874f.png)

**Comment by G-Spawn** [comment]
https://github.com/yuzu-emu/yuzu/issues/7653 closing in favour of existing issue
