### ISSUE TITLE
Add option to disable Gamepad support on the Game List

### ISSUE THREAD

**Issue by BuggingYou** [yuzu-emu/yuzu#7758]
Please Add an option to disable Gamepad support on the Game List.

The issue is that i need to use an Xbox controller with JoyToKey to control my PC,
in most recent versions of Yuzu the Game List responds to controller buttons, 
since most of the interface still needs mouse support this is creating a conflict,
games are being accidentally launched and Yuzu seems to crash sometimes.

Thanks for reading.

**Comment by german77** [comment]
Lol, I saw this coming. Generally you don't want to do something else when playing yuzu but I will push a setting as soon as I have time.
