### ISSUE TITLE
Add the ability to invert the control stick modifier key.

### ISSUE THREAD

**Issue by pianoboy8** [yuzu-emu/yuzu#7759]
This is a feature request to basically mimic the "!" (or "NOT") logic function that you can apply to keys within the Dolphin emulator. For the context of the modifier key, the idea is that you can invert the logic of the modifier key so that instead of decreasing the stick's position to a percentage, it will instead increase the stick's position to a percentage.
This would allow players who prefer walking to be the default movement when using a keyboard, and requiring the pressing down or toggle of the modifier key to start running (rather than running by default).

Here's an image below regarding how this is implemented within Dolphin. Normally to set this up within Dolphin, you have the range of each control stick direction decreased to a value under 100 (e.g. 80), and have the modifier key's value set to 200 (i.e. doubling the range from 80 to 160).
![image](https://user-images.githubusercontent.com/3158887/150620733-2103a8f4-b92b-4fa5-96aa-6425979c0e16.png)

Thank you.

**Comment by G-Spawn** [comment]
![image](https://user-images.githubusercontent.com/23653025/150621799-b841ec69-e539-4068-967b-37e293206661.png)
This is technically already achievable. The walking - running with keyboard/mouse layout is defaulted to shift. Holding it down affects the speed chars run in many games.

**Comment by pianoboy8** [comment]
> Isn't this what you are looking for? ![image](https://user-images.githubusercontent.com/5944268/150621252-f468f85f-4f25-4630-8e03-cf681f959e13.png)

I'm pretty sure that's a binding for the left stick button. I'm specifically talking about the stick range modifier where by default it allows keyboard users to walk while using a standard wasd or arrow key stick layout instead of run when holding down the modifier key.

Basically I'm requesting to allow to do the reverse, so you can run instead of walk while holding down the modifier key.
