### ISSUE TITLE
yuzu keeps crashing 

### ISSUE THREAD

**Issue by justjdfanofficial** [yuzu-emu/yuzu#7766]
Hello Whoever Reading this

Yuzu keep crashing on my pc on non admin account on admin account works good
I have no log file but i have screen shot P.S I have polish pc so maybe you can use google translate 
![16429414916902092320790772171026](https://user-images.githubusercontent.com/98263697/150678747-4c5c4b11-78b4-4ec5-8f8f-a8b3981336c5.jpg)

Iam using yuzu 887 pc specs : i dont really know OP:Windows 10 

Thank u very much justjdfan

**Comment by german77** [comment]
Please provide a log. There are multiple reasons for yuzu to crash.  Consider asking on the discord server for help.

**Comment by justjdfanofficial** [comment]
Log Files Are Empty 
![image](https://user-images.githubusercontent.com/98263697/150792651-09015afd-1355-4e53-825c-9d9a201e244d.png)
![image](https://user-images.githubusercontent.com/98263697/150792700-c8619801-6ea2-40c7-8359-0be6ff8e7724.png)

**Comment by justjdfanofficial** [comment]
I will do it tomorrow
Im lazy 😴

**Comment by justjdfanofficial** [comment]
i will try to send log right now
wait

**Comment by justjdfanofficial** [comment]
Still empty

**Comment by justjdfanofficial** [comment]
BRUH

**Comment by justjdfanofficial** [comment]
![Uploading 16432895284272482888701856687617.jpg…]()
An picture of running on admin acc

**Comment by justjdfanofficial** [comment]
lol this issue dead

**Comment by german77** [comment]
Just a follow up. Download latest version of yuzu and try again. I fixed an error where yuzu crashes at boot

**Comment by justjdfanofficial** [comment]
Thank you it works for now
