### ISSUE TITLE
From version 838 not possible to use pro controller instead of Joycons 

### ISSUE THREAD

**Issue by JosefP** [yuzu-emu/yuzu#7776]
Hello,

Some games like Super mario party are originaly only playable with Joycons. But before version 838 Yuzu bypass this and you was able to play with Pro controller with no additional settings(no need to rotate controller and so) . So I just ran Super mario party with 4 normally configured Pro controllers and it worked. From version 838 it is not possible. Is it possible to have some setting to enable this behavior(bypass allowed controllers)? I know that correct checking of controller type is wanted functionality but play game without need to reconfigure controllers is really comfortable.

Thank you for considering implementing this functionality.

**Comment by german77** [comment]
This version started to check if the connected controller is valid. If not it gets disconnected. I will not add a config for this since it's inaccurate.

If a real switch allows such controller let me know

**Comment by JosefP** [comment]
You are true. This functionality is not possible on real switch. So workaround is to wait for controller profiles functionality.
Thank you.
