### ISSUE TITLE
Pokemon Legend Arceus Black screen

### ISSUE THREAD

**Issue by PrinceBubloo** [yuzu-emu/yuzu#7785]
Pokemon legend arceus boots fine.
After entering the name its just black screen.
Wont boot into the story.

**Comment by henres** [comment]
Hello,

I can go further with spamming the f4 key !

**Comment by sakuka47** [comment]
No supported leak game

**Comment by fenpaws** [comment]
Well I got further, after you captured the Pokémon and talk to the Prof you look at the thing in the sky, after that black screen. I noticed that the emulator ate up my entire RAM. Could even force kill it.

But damn, I played at 2x resolution, and it worked so well.

If I look into my logs they are quite empty, here you go.

```
[   0.330955] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:140: Udp Initialization started
[   0.330964] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:329: Starting communication with UDP input server on 127.0.0.1:26760
[   0.422609] Frontend <Info> yuzu\main.cpp:GMainWindow:248: yuzu Version: yuzu Early Access 2428
[   0.422611] Frontend <Info> yuzu\main.cpp:GMainWindow:263: Host CPU: AMD Ryzen 7 5800H with Radeon Graphics          | AVX2 | FMA
[   0.422653] Frontend <Info> yuzu\main.cpp:GMainWindow:265: Host OS: Windows 10 Version 2009
[   0.422663] Frontend <Info> yuzu\main.cpp:GMainWindow:267: Host RAM: 31.36 GiB
[   0.422664] Frontend <Info> yuzu\main.cpp:GMainWindow:268: Host Swap: 30.55 GiB

```

**Comment by PrinceBubloo** [comment]
Pls open another issue and post log there. Ty @fenpaws

**Comment by PrinceBubloo** [comment]
Closing this cause the softlock is gone.
Ty @bunnei @ameerj

**Comment by DuIslingr** [comment]
@PrinceBubloo would you please post what hardware you are using driver version yuzu build and what rendering api trust resulted in the black screen.

**Comment by PrinceBubloo** [comment]
As mentioned,
Latest commits from Bunnei and Epicboy (sorry if I am mispronouncing his name) fixed that softlock.

**Comment by DuIslingr** [comment]
So to clarify the black screen did not occur in game?
