### ISSUE TITLE
Keyboard not working on Linux

### ISSUE THREAD

**Issue by Vladimir-A** [yuzu-emu/yuzu#7789]
On **yuzu-20211207-ba7c60229** keyboard is working.
After **yuzu-20211208-2361cd820** keyboard does not working.

Changing the keyboard settings did not give any result.

**Comment by liberodark** [comment]
For me keyboard work on linux.
Have test on 3 PC.

**Comment by german77** [comment]
There are no keyboard settings on yuzu. Unless you are using a game that requires keyboard(let me know if one exist). You should try remapping the controller

**Comment by liberodark** [comment]
Yep on my side im use evmapy to set controller to keyboard if is needed but mostly im play with x360 controller.

**Comment by Vladimir-A** [comment]
Changing connect controller (input device - keyboard) from Dual Joycons to Pro Controller helps me. Maybe I think so, but also if i choosing Dual Joycons yuzu shut down very slow.

**Comment by german77** [comment]
The emulated controller has nothing to do with performance. Some games don't support certain controller types. Like mario party only allows single joycons. See if your game allows that controller first

**Comment by gidoly** [comment]
is this still happens?

**Comment by german77** [comment]
Closed due inactivity. Please reopen if the issue persist.
