### ISSUE TITLE
Medieval Tower Defense [01008890162A8000] cannot start a new game

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#7794]
just stuck on the title screen
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7956328/yuzu_log.txt)

**Comment by ken7877** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8010446/yuzu_log.txt)

**Comment by benderscruffy** [comment]
@german77 
maybe you could take a look at this ??

**Comment by benderscruffy** [comment]
can be closed 
game on supports handheld mode
