### ISSUE TITLE
Emulator Freezes and locks up in Pokémon-Legenden: Arceus 

### ISSUE THREAD

**Issue by fenpaws** [yuzu-emu/yuzu#7795]
The game runs great up to a point where the Emulator locks up and eats my entire RAM. At that points I'm unable to close the program and had to wait a few minutes. 

This happens after you completed the mission of capturing the three initial Pokémon and look at the swirly thing in the sky.

Well i tried it again so i could get a log file (i have overwritten mine from before) and now I got a bit further. I was in a cutscene that showed some kind of village. Then the same happened again.

**yuzu version:** 892
**renderer:** vulkan (GPU HIGH)
**LOG:** [yuzu_log.txt](https://gist.github.com/fenpaws/97134a2f101b52864b00f900b1570f0f)

I also played at 1x and 2x Scale, i also noticed that the Log file is not complete, i have the console open while i play and after the lock happens there are two to three more lines that don't get written to the log file.

Since my PC locks up, i can't copy and paste them here.

**Comment by pacoa-kdbg** [comment]
I think softlocks should be solved by https://github.com/yuzu-emu/yuzu/pull/7787

**Comment by fenpaws** [comment]
So its waiting for a new version then right? Since i dont have acces to the early builds

**Comment by pacoa-kdbg** [comment]
Yes, you can keep an eye to github and see when it gets closed and commited
or join discord
https://discord.gg/u77vRWY

**Comment by fenpaws** [comment]
Will do, thanks.

**Comment by kuroganashi** [comment]
> I think softlocks should be solved by #7787

it helps but it doesn't fix it, the issue still remains.

**Comment by hypno99** [comment]
the issue still remains. 
Vulkan RX 580
