### ISSUE TITLE
Missing cutscenes video in Layton's mystery journey with vulkan

### ISSUE THREAD

**Issue by Gioele927** [yuzu-emu/yuzu#7798]
In Layton's mystery journey, with Vulkan, 
the game does not show cutscenes, audio and subtitles works but for the cutscenes you see only 
a black image, the rest of the game seems to work, tested with the latest EA 2440 build.  As gpu I use a Nvidia RTX 2060.
![Immagine 2022-01-28 173232](https://user-images.githubusercontent.com/98606228/151585464-0df9155c-80cc-4974-9418-ca1ae39c3336.jpg)

this is an image taken from youtube showing how it should be displayed:
<img width="1429" alt="Schermata 2022-01-28 alle 17 37 52" src="https://user-images.githubusercontent.com/98606228/151586176-241c39da-c2b7-4617-8bad-82165d304597.png">

**Comment by FearlessTobi** [comment]
Closing as https://github.com/yuzu-emu/yuzu/issues/9635 has more information.
