### ISSUE TITLE
Texture stretching in Pokémon Legends : Arceus

### ISSUE THREAD

**Issue by Loris19** [yuzu-emu/yuzu#7803]
**Yuzu version :** 896
**Renderer :** Vulkan (high)
**GPU :** Nvidia GTX 1060
**Graphic settings :** Disk pipeline cache, asynchronous GPU emulation and accelerated ASTC texture decoding on. GPU video decoding, 2X resolution, FSR
**Log file :** [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7963813/yuzu_log.txt)

The game is running fine (except some FPS drops in Jubilife), but I frequently encounter some graphical glitches with textures stretching out and expanding from entities.

Examples with NPCs (note that shadows are problematic as well) :
![bug1.jpg](https://user-images.githubusercontent.com/9156871/151663822-001be309-4f65-4fad-b18c-ecbcc0aeb266.jpg)
![bug2](https://user-images.githubusercontent.com/9156871/151663872-11db07f0-71ee-43e7-ad82-5282646f9ee4.jpg)

The player's hand :
![bug3](https://user-images.githubusercontent.com/9156871/151663894-2b08cd59-8bd3-45c5-b680-aaaed1a69fbf.jpg)

And whatever this is (this is supposed to be a base camp):
![bug4](https://user-images.githubusercontent.com/9156871/151663902-ad9c1213-3a10-48bd-9333-6748e42454a1.jpg)

This also occurs with Pokémons and clothing (e.g. the player's scarf), but I was unable to capture that.

**Comment by PrinceBubloo** [comment]
Is it happening without down scaling?.
Like on 1x resolution

**Comment by Loris19** [comment]
> Is it happening without down scaling?. Like on 1x resolution

Yes, I just tried it and was able to run into this within a minute :
![buga](https://user-images.githubusercontent.com/9156871/151664223-63494b27-c245-48ec-b280-aa1be3d3f83a.jpg)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7963848/yuzu_log.txt)


NB : This is now on Yuzu 897. I should also mention that the game is in 1.0.1.

**Comment by OZtistic** [comment]
This is what is called Vertex Explosion - the team are aware of it, and are actively investigating. Thank you for taking the time to report this

**Comment by FernandoS27** [comment]
We've found the cause. We'll release a temporary fix now and a better fix later.

**Comment by PrinceBubloo** [comment]
Ty for the quick fix.
I know you guys are very busy @FernandoS27

**Comment by Loris19** [comment]
Thank you very much for the work !

**Comment by delunatriestocode** [comment]
Still happening to me

**Comment by Superduashwin** [comment]
So, if u keep in "_**GPU High**_" this vertex explosion stops.. but it lags so much in GPU high.. Here are the settings to **_"Max FPS"_** in gpu high  - 
0) REMOVE ALL 60 FPS MODS (they only reduce fps) :(
1)Remove Qol enhancements mod (if u have).. just keep the required bin files like removeblackscreen and switchsprintkeys...
2)Settings - (**CPU- Auto**) AND **_"HANDHELD"_**
![image](https://user-images.githubusercontent.com/88470329/232234126-12cb6818-677e-4bdc-94f7-75c560b4fa76.png)
![image](https://user-images.githubusercontent.com/88470329/232230217-9dae9b74-5163-4f11-a15a-d4d7f1b21e55.png)
![image](https://user-images.githubusercontent.com/88470329/232230224-49ddf29c-ab8b-477c-b149-65568a3c6f85.png)

Hope it works :)
