### ISSUE TITLE
Pokemon Legends Arceus Crash (AMD APU)

### ISSUE THREAD

**Issue by liberodark** [yuzu-emu/yuzu#7808]
CPU : AMD Ryzen 5 4500U
RAM : 16 Go
OS : Linux
Driver : Mesa 21.3.4
Vulkan : 1.2.195
Yuzu Build : 11099dda2e2ab67ba4861d1e927afaa2ccce1efa

Hi,

I often crash after a few minutes.
Sometimes without even moving. 

Im using : VK + FSR + FXAA + DOCK
My log : [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7966321/yuzu_log.txt)
My save : [01001F5010DFA000.zip](https://github.com/yuzu-emu/yuzu/files/7966338/01001F5010DFA000.zip)

Best Regards

**Comment by BSoDGamingYT** [comment]
You have no swap/pagefile. Please try setting it to 10-15gbs (12000mbs min and max) and try again

**Comment by liberodark** [comment]
Do you think 12GB is not enough for yuzu?
Because I don't really want to set up swap on my SSD only because there is a memory overflow.
Which also happens.

**Comment by ZantsuRocks** [comment]
With crash you are saying that the emulator freezes completely? or the Emulator closes? Maybe stuck with 0fps and sound playing?

**Comment by liberodark** [comment]
I had both cases and an F4 is not enough to restart the game.

**Comment by ZantsuRocks** [comment]
For the 0 fps on AMD CPU there is a workaround: https://github.com/yuzu-emu/yuzu/issues/7804#issuecomment-1025077913
Setting cpu affinity to 4 (5 is better). You can use `taskset` for this.

**Comment by liberodark** [comment]
Probably this PR help one of my issue : https://github.com/yuzu-emu/yuzu/pull/7812

**Comment by FernandoS27** [comment]
PR https://github.com/yuzu-emu/yuzu/pull/7812 is on latest EA, let me know if it fixes the crashing.

**Comment by liberodark** [comment]
Have test a Yuzu 2450 have check your pr is integrated.
And yes have see more stability with your PR.
Before, you could have memory overflows. It seems that is no longer the case. I would have to do more intensive testing but already during my first tests I did not have a crash. 

@FernandoS27

**Comment by Darkblader24** [comment]
I'm not sure if it's related, but it doesn't fix being stuck at 0fps for me. Even the affinity fix doesn't help

CPU : AMD Ryzen 7 3700X
RAM : 32 GB
OS : Win 11
Driver : NVIDIA 511.23.0.0
Vulkan : 1.2.194
Yuzu Build : EA 2450

**Comment by FernandoS27** [comment]
It seem this affects all Zen 2 CPUs.

**Comment by ZantsuRocks** [comment]
> It seem this affects all Zen 2 CPUs.

It is true for 0 fps.
It is not true for crashes.
I have a Ryzen 7 2700 and didn't have any single crash, just the 0 fps issue that can be workarounded with CPU Affinity.

**Comment by liberodark** [comment]
@FernandoS27 Have make new build from f56226e17f4cf4f73201e8162bc8bdefc6468451
Im running test on Ryzen 5 4500U & Ryzen 9 5900HX

**Comment by liberodark** [comment]
Fixed by https://github.com/yuzu-emu/yuzu/commit/f56226e17f4cf4f73201e8162bc8bdefc6468451
