### ISSUE TITLE
Several issues on Intel Xe GPU

### ISSUE THREAD

**Issue by I-LoveCpp** [yuzu-emu/yuzu#7815]
CPU : i5-1135G7
GPU : Intel Iris Xe Graphics
RAM : 8GB
OS : Windows 10
Driver : 30.0.101.1191
Yuzu Build : Early Access 2450

OpenGL : Almost all 3D parts are not rendered.
Vulkan :
Xenoblade Chronicles and Xenoblade2 freeze to 0 FPS and crash on load.
Fire Emblem: Three Houses freeze to 0 FPS and crash randomly.
Hyrule Warriors: Age of Calamity crash while loading animation.
Pokemon Legends: Arceus freeze to 0 FPS randomly.
Taiko no Tatsujin: Rhythmic Adventure Pack has weried color as #6341

**Comment by liberodark** [comment]
Hi i think this PR : https://github.com/yuzu-emu/yuzu/pull/7806
Can help you if you have time to test.

**Comment by I-LoveCpp** [comment]
Well, in all of yuzu ea it won't works

**Comment by I-LoveCpp** [comment]
Xenoblade 2 freeze to 0 FPS while loading animation
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7977891/yuzu_log.txt)

**Comment by goldenx86** [comment]
Intel Windows drivers are broken, wait for Intel to fix them: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/159
