### ISSUE TITLE
yuzu cant read Xci

### ISSUE THREAD

**Issue by conitsua** [yuzu-emu/yuzu#7817]
![Screenshot 2022-01-31 214336](https://user-images.githubusercontent.com/98486947/151861708-f17e9902-be50-488b-9b17-cf15f74cd077.jpg)
![xci file](https://user-images.githubusercontent.com/98486947/151862071-367518bc-ec9e-45bc-8b4d-5c4fd6437722.jpg)

**Comment by german77** [comment]
We don't allow piracy here
