### ISSUE TITLE
Black and Yellow Graphic over Game

### ISSUE THREAD

**Issue by Triskowicz** [yuzu-emu/yuzu#7819]
![0100ce500d226000_2022-02-01_00-42-15-330](https://user-images.githubusercontent.com/91310999/151892490-110c9e09-4b3e-4eef-861d-8cce1afe0fe9.png)
I have tried to start the game Laytons_Mystery_Journey_Katrielle_and_the_Millionaires_Conspiracy_-_Deluxe_Edition_Eur_NSP. However whenever the game begins there is this black and yellow graphic that shows up on the screen. I have increased my page file and and set my CPU accuracy to automatic. This however was unable to remedy the issue. I wonder if it is some form of piracy protection.

**Comment by german77** [comment]
Duplicated of #7820
