### ISSUE TITLE
Black and Yellow Graphic over Game

### ISSUE THREAD

**Issue by Triskowicz** [yuzu-emu/yuzu#7820]
![0100ce500d226000_2022-02-01_00-42-15-330](https://user-images.githubusercontent.com/91310999/151892922-18fdabd7-b084-4bd0-8fbd-6ba8fd58ffb1.png)
I have tried to start the game Laytons_Mystery_Journey_Katrielle_and_the_Millionaires_Conspiracy_-_Deluxe_Edition_Eur_NSP. However whenever the game begins there is this black and yellow graphic that shows up on the screen. I have increased my page file and and set my CPU accuracy to automatic. This however was unable to remedy the issue. I wonder if it is some form of piracy protection.

**Comment by german77** [comment]
Duplicated of #6352
