### ISSUE TITLE
Was working perfectly, but not anymore

### ISSUE THREAD

**Issue by eugostodebatata12** [yuzu-emu/yuzu#7823]
When i try to open any game (be clicking 2 times or open the file) yuzu just closes and i need to open it again, any help?

**Comment by pacoa-kdbg** [comment]
Please provide a log

**Comment by giftinglass** [comment]
This is exactly my same experience. Until yesterday, everything was fine, but now no games launch under Vulkan in Intel, as I mentioned here [https://github.com/yuzu-emu/yuzu/issues/7818](url). I just checked the log of pacman (the package manager) and I realized that, before the problem appeared, three packages were updated:

```
[2022-01-31T20:42:14+0100] [ALPM] upgraded expat (2.4.3-1 -> 2.4.4-1)
[2022-01-31T20:42:14+0100] [ALPM] upgraded lcms2 (2.12-1 -> 2.13-1)
[2022-01-31T20:42:15+0100] [ALPM] upgraded qt5-declarative (5.15.2+kde+r43-3 -> 5.15.2+kde+r44-1)
```

Do you think any of these may be causing the problem?

**Comment by eugostodebatata12** [comment]
ye but the problem is, my pc was working in open gl AND vulkan but now this say my video card are don't support open gl 4.6 and when i try vulkan this happen, i try to update my drives but still dind't work

**Comment by v1993** [comment]
Please use yuzu discord for support. It will be faster and easier for everyone involved.

**Comment by G-Spawn** [comment]
Closing for aforementioned reason above.
