### ISSUE TITLE
pokemon legends arcues isnt really playable in docked mode

### ISSUE THREAD

**Issue by Jorge9811** [yuzu-emu/yuzu#7836]
you cant use the handheld controller in docked mode because ???
dual joycons dont work (i press a in the titlescreen and nothing ever happens)
the pro controller in docked mode is shit bcuase when i press R to aim a poke ball item or whatever yuzu decides to switch to the next item too because ???

wtf is wrong with this shit

**Comment by BSoDGamingYT** [comment]
This is not a support forum, please join and use the discord server for such requests: https://discord.gg/u77vRWY
