### ISSUE TITLE
Lock in 30 fps in Yuzu, the game: Monster Hunter Stories 2: Wings of Ruin

### ISSUE THREAD

**Issue by Sonnlluns** [yuzu-emu/yuzu#7837]
![image](https://user-images.githubusercontent.com/98832981/152130774-024757b7-83eb-4d10-a70c-7fdbef779104.png)

Have a metod to lock in 30 fps?
But the sound and game glitching to get 60 fps to run?
The Gpu is a AMD Radeon R9 200 Series (3gvram)
And the CPU is I5 3330 (IVY BRIDGE)

**Comment by BSoDGamingYT** [comment]
This is not a support forum, or a place to ask for game modifications. Please use the discord server for such questions: https://discord.gg/u77vRWY
