### ISSUE TITLE
Yuzu crash on Intel Xe GPU

### ISSUE THREAD

**Issue by I-LoveCpp** [yuzu-emu/yuzu#7845]
CPU : i5-1135G7
GPU : Intel Iris Xe Graphics
RAM : 8GB
OS : Windows 10
Driver : 30.0.101.1191
Yuzu Build : Early Access 2450

Xenoblade Chronicles and Xenoblade2 freeze to 0 FPS and crash on load.

My log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7993704/yuzu_log.txt)

**Comment by PrinceBubloo** [comment]
Use the latest EA and update.
Ty

**Comment by I-LoveCpp** [comment]
> Use the latest EA and update. Ty

It still has this issue...

**Comment by michael1986** [comment]
have the same issue, before going to act 2 it crashes, anybody knows smth about it?

**Comment by goldenx86** [comment]
Intel Windows drivers are broken, wait for Intel to fix them: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/159
