### ISSUE TITLE
Splatoon 2 Entering Multiplayer Results in a crash

### ISSUE THREAD

**Issue by mantasx1001** [yuzu-emu/yuzu#7846]
CPU :i5-9400F
GPU :AMD Radeon RX 580 Series
RAM :16 gb
OS :Manjaro
Yuzu Build :906

When I try to enter multiplayer the game crashes after updating to update 5.5.0 previously it loaded the room with a message Update to the latest version.

**Comment by german77** [comment]
Local multiplayer or online multiplayer?

**Comment by galax20002** [comment]
I have the same problem, i modded the game and added a bcat cache and also made the online lobby use of lan mode with an exefs patch. But the game just crashes when you go in

**Comment by mantasx1001** [comment]
> Local multiplayer or online multiplayer?

Just trying to enter the tower

**Comment by JumpingY** [comment]
please try to go back to 5.4.0

> CPU :i5-9400F GPU :AMD Radeon RX 580 Series RAM :16 gb OS :Manjaro Yuzu Build :906
> 
> When I try to enter multiplayer the game crashes after updating to update 5.5.0 previously it loaded the room with a message Update to the latest version.

**Comment by galax20002** [comment]
I dont have it anymore it and 5.4 is useless if everyone is on 5.5

**Comment by JumpingY** [comment]
> I dont have it anymore it and 5.4 is useless if everyone is on 5.5

Remove the shader cache ,they are incompatible with 5.5.0

**Comment by gidoly** [comment]
is this still persist?

**Comment by mantasx1001** [comment]
I just decided to buy a switch I will only use the counter to play some
Mario kart with two players because practically none of my friends have a
switch

2022-06-17, pn 08:05, gidoly ***@***.***> rašė:

**Comment by gidoly** [comment]
closes due to author appearantly referred to online feature.
