### ISSUE TITLE
R analog stick is not centered when mouse inputs are binded to it 

### ISSUE THREAD

**Issue by jcl4068** [yuzu-emu/yuzu#7853]
**Version:** yuzu 908 (2022-02-04)
**Issue:** R analog stick is not centered when mouse inputs are binded to it 

The control settings are all the default ones for keyboard/mouse input as seen below:
![5](https://user-images.githubusercontent.com/85395111/152634095-85feadae-95dc-4a0e-810c-adff73a7b1ce.jpg)

Following pictures display the debugging controller P1 when moving the cursor to different corners:
**Top left:**
![1](https://user-images.githubusercontent.com/85395111/152634129-5c77fc3f-1827-49d7-afe3-0a4764a03584.jpg)
**Top right:**
![2](https://user-images.githubusercontent.com/85395111/152634134-78bc69fa-6c7a-4a24-83fd-2a130ccfa3b6.jpg)
**Bottom right:**
![3](https://user-images.githubusercontent.com/85395111/152634159-700c9db8-c8aa-48c8-8301-62082633edd4.jpg)
**Bottom left:**
![4](https://user-images.githubusercontent.com/85395111/152634166-9c658c2d-4408-4951-9ddf-9ddf530b4e76.jpg)

From these pictures the centre appears to be at the top left of the screen. 
Currently in BoTW, the camera is stuck looking at the ceiling and can only rotate clockwise.

There are similar results when binding the L analog (centre is not centered).

**Comment by PrinceBubloo** [comment]
@german77

**Comment by german77** [comment]
do you have two monitors?

**Comment by german77** [comment]
Just tested. I have no issues. Take in mind the center is located where you first click with the mouse.

**Comment by jcl4068** [comment]
> do you have two monitors?

I do have two monitors do you think that is an issue?

**Comment by jcl4068** [comment]
> Just tested. I have no issues. Take in mind the center is located where you first click with the mouse.

I unplugged my second monitor and clicked on the centre when mapping the analog stick, but I am getting similar results.

**Comment by Metal-666** [comment]
I'm facing the same issue (I also have 2 monitors, if that matters)

**Comment by german77** [comment]
Qt reported a wrong position with the mouse if it had 2 monitors. If you are able to start yuzu with a single monitor then check if mouse works well that will help me a lot

**Comment by Metal-666** [comment]
Nope, doesn't work. Disconnected the monitor, started yuzu, game still thinks top-left corner is the center

**Comment by Amppa** [comment]
Same problem
Dual monitor, the center always on left-top corner.
Reboot pc, start yuzu with single monitor, doesn't work.
