### ISSUE TITLE
[Feature Resquest] Check for GPU driver updates

### ISSUE THREAD

**Issue by NineKain** [yuzu-emu/yuzu#7856]
Lots of people come to the Discord server asking for help for an issue, the support channels get clogged and saturated, and 90% of the time, the reason is outdated drivers.

Would a simple one-time message that said something like "Your GPU driver might be outdated, consider updating it to the latest version to avoid any potential bugs on Yuzu". 

Maybe on the bottom right, just a little "Driver update available!" that could be dismissed if needed.

**Comment by nullavisus** [comment]
That sounds a bit too far out of the scope of an emulator. I would imagine trying to account for every single instance of PEBKAC would easilly lead to feature bloat. Not Yuzus fault that people don't maintain their drivers.

**Comment by G-Spawn** [comment]
This will kind of be satisfied by https://github.com/yuzu-emu/yuzu/pull/8393. Better user prompt and fix in error & defaulting of vulkan.
