### ISSUE TITLE
Labyrinth of Labyrinth:Coven of Dusk[01007010157B4000] cannot start a new game

### ISSUE THREAD

**Issue by ken7877** [yuzu-emu/yuzu#7857]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8010455/yuzu_log.txt)

**Comment by gidoly** [comment]
Please upload explanation, hardware spec

**Comment by ken7877** [comment]
> Please upload explanation, hardware spec

12700
GTX980
ddr4 3000

**Comment by G-Spawn** [comment]
We only provide support for official releases of Yuzu (https://yuzu-emu.org/downloads/) . Regardless, this issue has little to no details, replication steps, or screenshots that explain the issue. 

Closing issue. Please create a new issue if issues persist in Mainline.
