### ISSUE TITLE
ACNH freezes and shuts down upon load in

### ISSUE THREAD

**Issue by TheVoidIsBees** [yuzu-emu/yuzu#7858]
I updated yuzu to 910 and played the game as normal for about half an hour. Then I saved as normal, closed down yuzu and took about a 20 minute break. Then I reopened yuzu to play ACNH again and after about 1 minute the game froze and shut down. I tried fiddling with settings and downgrading to version 909 (which worked for me when I played yesterday) but the issue persists. I open yuzu, start up the game, it loads me in, I play for 10 - 80 seconds and it freezes and crashes again. I use vulkan and here's the log from my last attempt 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8011392/yuzu_log.txt)

**Comment by G-Spawn** [comment]
We don't support piracy here. Dump all your files from your nintendo switch. Closing issue for such reason.
