### ISSUE TITLE
Tela Azul

### ISSUE THREAD

**Issue by idfidjopf** [yuzu-emu/yuzu#7869]
Quando abro o jogo por exemplo lets go pikachu no começo tudo normal mas quando chega a parte de escolher o idioma a tela fica azul e uma parte pequena fica branca queria saber como consertar por farvor

**Comment by german77** [comment]
This is not a support forum. Please ask on our discord or on our support forum https://community.citra-emu.org/

Provide a log to be able to help you more quickly
