### ISSUE TITLE
Yuzu crash randomly

### ISSUE THREAD

**Issue by dariuxzy** [yuzu-emu/yuzu#7880]
hi, I'm trying to play Super Mario 3D World on my PC, I managed to set Yuzu to play smoothly, but I don't understand why sometimes Yuzu crashes randomly. Am I doing something wrong? I am using the latest AMD drives
i5-3550
Vega 64
24GB RAM
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8051914/yuzu_log.txt)

**Comment by G-Spawn** [comment]
As this isn't a support forum I'd suggest asking on discord initially before making a github issue.
