### ISSUE TITLE
Zelda BOTW asynchronous GPU emulation issue

### ISSUE THREAD

**Issue by nkolovos** [yuzu-emu/yuzu#7886]
I am running zelda botw with asynchronous GPU emulation enabled . Once i tried disabling in the avatar is "sinking" into the ground like surface not working correct. I saw it was an issue on older emulators but was "fixed". On pokemon arceus i had this setting off and made the game run prety smoothly without any issue at all.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8054469/yuzu_log.txt)
![asdad](https://user-images.githubusercontent.com/58826147/153727459-f9b5fd7e-285e-4c94-8686-67d0e6ad535e.png)

**Comment by BSoDGamingYT** [comment]
Dont disable it

**Comment by nkolovos** [comment]
Thanks....I guess obviously had it enabled just was wondering wether you were aware of this situation and just let it unsolved cause there wasn't any solution?

**Comment by nkolovos** [comment]
Ok i saw how gpu emulation is working(i7 6700k CPU on my system) apparently on 4 core systems (not logical threads/cores) disabling one core makes a huge difference in terms of overheads in a given game. It's causing spikes that are similar in a case  of a multilevel app where "high occupancy" occurs  and the current resources are not available so latency in the pipelines is present. Watching the architecture of tegra x1 it looks like on a system like mine removing one core makes a huge a difference(4-8 cores on the 6700k fits perfectly on the 4-4cores of the tegra(but gpu emulation is breaking this nice fit))...nice scheduling problem for someone to solve and improve "wish i had the time :)".

**Comment by PrinceBubloo** [comment]
I dont understand what you said, but if you think it will improve emulation you can leave a message in discord with your findings
