### ISSUE TITLE
Cheats in .txt format bug, cheat load but no changes is applied to game (.log included)

### ISSUE THREAD

**Issue by felixthecat1970** [yuzu-emu/yuzu#7889]
Yuzu 912
windows 11 21h2

-cheats in .txt format looks like load but code are not applied, using faq guidelines and check debug log:
file folder structure used : 
game: GetsuFumaDen: Undying Moon
id : 010042A013DB8000
"open mod data location" > 60fps > cheats > dc43f416a9b08d2a.txt  (*build id verified from main file 0x40 and .log load)

 dc43f416a9b08d2a.txt file content:

[60fps]
580F0000 0782FD60
580F1000 00000080
780F0000 00000F14
640F0000 00000000 00000001

" the [60fps] line cause log warning about possible incorrect cheat format, deleted this line, warning not show anymore. "

-log show patch manager load cheats from buid id :
[   6.515891] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:295: Querying NSO patch existence for build_id=DC43F416A9B08D2A48CC3F4ACB01325 ]

-trying change .txt filename to 1.0.0.txt (cheat is not loaded)
-happens others 60 fps .txt cheats format from gbatemp thread [https://gbatemp.net/threads/60-fps-cheats-for-nswitch.592464/](url) (shin megami tensei nocture, etc)
-verifing codes are working ok on other emulator (ryujinx) codes are loaded and works ok (60 fps codes are loaded in game)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8056267/yuzu_log.txt)

**Comment by lKobi** [comment]
Yeah cheats are not working on yuzu right now, I have exactly the same issue as stated,

`core\file_sys\patch_manager.cpp:HasNSOPatch:301: Querying NSO patch existence for build_id=A36DAC0E0A5ED3B41482B6BB85625C73EECD0023`

The same file is working perfectly fine on Ryujinx, exactly as OP.

**Comment by Immersion95** [comment]
Same thing here

**Comment by lKobi** [comment]
Only way I got it to work was to convert the cheat as a MOD, honestly the current Cheat implementation on yuzu is horrible, especially considering the far superior implementation in Citra.

**Comment by unuruu5760** [comment]
> Only way I got it to work was to convert the cheat as a MOD, honestly the current Cheat implementation on yuzu is horrible, especially considering the far superior implementation on Citra.

How do I change a txt format cheat code to a mod?

**Comment by Djipi71** [comment]
How can we convert cheats to a MOD please? Because cheat not working on the lasts EA

**Comment by felixthecat1970** [comment]
testing againg lastest EA works now, using "mod data location" foldernamecheat">cheats>(bid:#)xxxxxxx.txt remember use only a [namecheat] line per cheat .txt, multiple [cheatnames ] on 1 file dont work you divide each cheat.
