### ISSUE TITLE
Tales of Vesperia - Water Shader Issues

### ISSUE THREAD

**Issue by Lengualo** [yuzu-emu/yuzu#7895]
I'm testing out Yuzu on a 2020 Macbook Air running Windows 10 via bootcamp. I know this isn't high spec, but I was curious as to how it performs. Generally, it's performing pretty well maintaining between 30 and 60 FPS, and minus some occasional FPS dips and some minor audio stutter, most games I've tested seem pretty stable. 

However, I'm encountering a couple of persistent issues in Tales of Vesperia Definitive Edition. None are game breaking.

The first are water shader glitches, where white polygon artifacts appear with both standing and flowing water, and the FPS has a tendency to dip below 30 when there is flowing water with audio. I've had to reduce the resolution scale in these areas because it can get pretty wonky.

I've attached screenshots of some of the water glitches.

![Vesperia - Water Glitches 2](https://user-images.githubusercontent.com/99680810/153919250-a00a43b2-a361-4f3c-8040-ca2732f5eec3.png)
![Vesperia - Water Glitches 3](https://user-images.githubusercontent.com/99680810/153919255-cdd8cc00-742a-4478-b6f0-cb538a2fa0ec.png)
![Vesperia - Water Glitches 4](https://user-images.githubusercontent.com/99680810/153919257-138d7ba8-003a-493f-99d2-e2e2f3abd9fb.png)
![Vesperia - Water Glitches 5](https://user-images.githubusercontent.com/99680810/153919261-ddd8da0b-0011-404e-b680-a0267be5100f.png)
![Vesperia - Water Glitches](https://user-images.githubusercontent.com/99680810/153919266-42e56f9e-7d23-4af5-a789-4a2a3ed3403d.png)

System Specs:
CPU: Intel Core i5-8210Y CPU 1.60GHz (Quad-Core)
RAM: 8GB
GPU: Intel UHD 617 - 1GB
OS: Windows 10

**Comment by BSoDGamingYT** [comment]
Duplicate issue of https://github.com/yuzu-emu/yuzu/issues/7879

**Comment by Lengualo** [comment]
That issue has been closed unresolved or resolved?

**Comment by v1993** [comment]
That issue was not closed at all.

**Comment by Lengualo** [comment]
Oh, OK. I thought it was.
