### ISSUE TITLE
If andorid's cpu is an arm mobile phone, can ptrace simulate svc to run switch games directly ？？

### ISSUE THREAD

**Issue by 344389541** [yuzu-emu/yuzu#7901]
I have a question to ask.
Yuzu uses Unicorn to simulate arm. If andorid's cpu is an arm mobile phone, can use ptrace simulate svc to run switch games directly.

```
//parent process
ptrace(PTRACE_ATTACH, pid, NULL, NULL)

while(1){
   // execute svc
   ptrace(PTRACE_SYSCALL, pid, NULL, NULL);
   work();
}
ptrace(PTRACE_DETACH, pid, NULL, NULL);
```

Can this solution directly run switch games on android?

**Comment by german77** [comment]
Yuzu uses dynarmic not unicorn.

**Comment by bylaws** [comment]
Ptrace is crazy slow, see skyline and our NCE technique for the fastest way to do it
