### ISSUE TITLE
Nintendo Switch Sports does not boot

### ISSUE THREAD

**Issue by CrusadingNinja** [yuzu-emu/yuzu#7902]
`Unknown / unimplemented function 'ListAudioOutputDeviceName': port='IAudioDevice' cmd_buf={[0]=0x1000006, [1]=0x8, [2]=0x300, [3]=0xC2E29B0, [4]=0x4, [5]=0x0, [6]=0x0, [7]=0x0, [8]=0x49434653}`

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8077529/yuzu_log.txt)

**Comment by PrinceBubloo** [comment]
@Morph1984

**Comment by CrusadingNinja** [comment]
More details in #7972
