### ISSUE TITLE
Astral Chain Particle Effects Issue

### ISSUE THREAD

**Issue by Peduls** [yuzu-emu/yuzu#7904]
The particle effects when summoning or dismissing your legion in Astral Chain appear blocky and broken. They also don't dissipate and just linger on the screen until you dismiss your legion. This issue also occurs when attacking certain entities such as targets during the shooting practice side-quest.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8084374/yuzu_log.txt)

**Comment by Peduls** [comment]
![01007300020fa000_2022-02-16_16-28-42-607](https://user-images.githubusercontent.com/34750422/154376282-66699e46-2707-45bc-bce1-6dbe7a931dfe.png)

**Comment by Peduls** [comment]
![01007300020fa000_2022-02-16_16-33-03-943](https://user-images.githubusercontent.com/34750422/154376308-0f1644aa-9e13-4103-8bb6-c7e4743054d5.png)

**Comment by Peduls** [comment]
Setting GPU Accuracy to "High" seems to fix this issue.

**Comment by gidoly** [comment]
close as gpu high can fix issue
