### ISSUE TITLE
Yuzu freezing over when trying to dump romFS on certain games

### ISSUE THREAD

**Issue by ZoruaLoL** [yuzu-emu/yuzu#7905]
I was trying to dump the romFS of **Gunvolt Chronicles: Luminous Avenger iX 2** or **Yo-kai Watch 1 for Nintendo Switch** and Yuzu would become irresponsible before ever prompting the options window. At the same time, the entire system would slow down until the app is force-quit.

**Comment by german77** [comment]
This is normal. When you dump big games you are basically decrypting, reading and writing several GB of data to the disk.  Even if the yuzu UI becomes unresponsive the program is working normally. Give it a few minutes to finish. 

You can open the task manager to see if it's writing data to the disk.

**Comment by ZoruaLoL** [comment]
It's not the same because I have been able to dump much bigger games (+5gb) and while it takes a while it's nowhere as catastrophic as with Gunvolt Chronicles: Luminous Avenger iX 2 which is only 1.4gb

**Comment by ZoruaLoL** [comment]
The issue I'm describing is that the system will freeze before ever promoting the dumping options ("full" or "skeleton") so the dumping never reallybegins. 
For most games it only takes a matter of seconds, this one seems to run out of memory.

**Comment by german77** [comment]
Alright I can confirm it has a noticiable memory leak.

**Comment by chengyuhui** [comment]
Seeing this on the just released Return to Shironagasu Island (0100E5C018B4A000) with yuzu 1239, yuzu freezes upon clicking the menu item, and memory consumption goes up to 2 GiB+ until I killed it (the game itself is 1.6 GiB). Disk I/O basically sits at 0.

**Comment by MontyMole98** [comment]
I know that it's been over a year since this was posted, but I have the same problem with a dumped XCI of Super Mario 3D All-Stars from my modded Switch. Yuzu seems to freeze when this happens and when looking in Task Manager, it is still using CPU and Memory, but it is not unfreezing. It didn't even open up the dump menu, just as described. Was a solution found for this?
