### ISSUE TITLE
[Feature Request] Expansion of Emulated 4GB Memory Limit

### ISSUE THREAD

**Issue by BearadactylPrime** [yuzu-emu/yuzu#7906]
So, this is something I spent a fair amount of time seeing if it had been requested or even mentioned across this repository and I personally didn't see any requests while browsing. 

As the modding community for Switch games grows and matures, the hard cap of 4GB looks like it's becoming more of an issue, especially in the realm of visual mods.

Is it feasible, or even in the scope of Yuzu to potentially see about expanding it? I am mentioning it because Ryujinx is currently experimenting with it, with an expansion hack of up to 6GB of memory, and from what I can tell that extra headroom is going a very long way with users who want to mod their games more extensively.

I know and understand the projects are both entirely separate, and scope is different for each, but I felt it wouldn't hurt to request the feature or to at least ask if there's been any consideration for it.

**Comment by Morph1984** [comment]
Added in #7932
