### ISSUE TITLE
"Pajama Sam: No Need to Hide When it's Dark Outside" triggers an assertion failure and crashes on launch

### ISSUE THREAD

**Issue by ChrisNonyminus** [yuzu-emu/yuzu#7910]
As the title says, when launching Pajama Sam, the game triggers an assertion failure involving Maxwell DMA; the regs.launch_dma.semaphore_type enum is expected to be None when, oddly, it's initialized by the game as 0x18e. The game also continously calls ResetSignal on the same handle, refusing to launch. The game then crashes Yuzu. This was tested with the latest version of upstream.

Here is the log file.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8089808/yuzu_log.txt)

**Comment by benderscruffy** [comment]
goes ingame now
can be closed
![Screenshot 2023-05-11 122213](https://github.com/yuzu-emu/yuzu/assets/2696404/30ff1f62-7ec4-42a0-9672-e491af2aac44)
