### ISSUE TITLE
N++ | 01000D5005974000 not booting.

### ISSUE THREAD

**Issue by MikeGoop** [yuzu-emu/yuzu#7914]
I have tried several cpu/gpu configs but nothing seems to work.

I have tried to run the game with Ryujinx and it's playable, but at the very beginnig I get a network error, which I suspect might be the cause of the issue.
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/8096244/yuzu_log.txt.old.txt)

**Comment by CrusadingNinja** [comment]
This issue is confusing. You posted a yuzu log, but a Ryujinx screenshot? Are you reporting a yuzu issue or Ryujinx issue? If the former, this screenshot is not very relevant to the issue. If the latter, this is the wrong repo to report that.

**Comment by MikeGoop** [comment]
The game does not boot at all in yuzu, just a black screen.

I also tried to run the game with Ryujinx just for a comparison: since I saw this network issue I figured I should post it to give more details.

Sorry for the confusion.

**Comment by benderscruffy** [comment]
@FearlessTobi 
using mainline 1557
goes ingame now
no problems
can be closed
