### ISSUE TITLE
Super Mario Odyssey graphic is broken.

### ISSUE THREAD

**Issue by nonamuoo** [yuzu-emu/yuzu#7917]
![image](https://user-images.githubusercontent.com/97642615/154740511-1561195f-4cb7-4a14-92f8-7b226b1c6b9c.png)
Background breakage occurs in Super Mario Odyssey's Luncheon Kingdom.
It appears when using Vulkan and operates normally in an OpenGL environment.

Computer:
cpu: ryzen5 3500
gpu: gtx 1650 4GB (driver: 456.71)
ram: 32GB 
yuzu version: 921

**Comment by nonamuoo** [comment]
> Contributor

Is it possible to do a higher version?

**Comment by FernandoS27** [comment]
> 

yes but you'll may have issues in some games on the newest like Lugi's Mansion and Hyrule warriors AoC. https://developer.nvidia.com/vulkan-driver

**Comment by leordsong** [comment]
I had the same issue; updating to the latest EA version works.

**Comment by nonamuoo** [comment]
![image](https://user-images.githubusercontent.com/97642615/154783141-5c2dc639-943a-4d72-886a-2c273068eaf1.png)

It was resolved after upgrading the driver to 511.79 version.
