### ISSUE TITLE
PLA crash during loading after title screen

### ISSUE THREAD

**Issue by RinoXz** [yuzu-emu/yuzu#7923]
When I want to launch PLA, the game launches up to the title screen but a few seconds after yuzu crashes and closes immediately (try on yuzu EA 2496).
I also tried to remove my shaders cache but nothing does

I am on the latest dev build (22557) of Win11.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8101995/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
Piracy is not supported by this project. Please legally dump the games from your Nintendo Switch: https://yuzu-emu.org/help/quickstart/
