### ISSUE TITLE
Transparent window on wayland

### ISSUE THREAD

**Issue by ghost** [yuzu-emu/yuzu#7928]
![Screenshot_20220220_213713](https://user-images.githubusercontent.com/92721485/154863466-71b5e0bc-5dfc-4f40-b27f-d87e8bd9c2a7.png)
Hi, when I open a game in yuzu on wayland session, there isn't video output, only audio and the window is transparent. In xorg session is ok. I tried with openGL and vulkan, but is the same thing. The version of yuzu is yuzu-linux-20220219-60c527fd0.

**Comment by CactiChameleon9** [comment]
I would like to mention that I have the same issue, however only with vulkan. Furthermore the issue does not occur on gnome wayland.
I am running wayfire, and have an integrated AMD GPU

**Comment by RiedleroD** [comment]
same problem in sway, except that OpenGL just straight up crashes. I tried both with `QT_QPA_PLATFORM=wayland` and `QT_QPA_PLATFORM=wayland-egl`. For now, prepending the command with `QT_QPA_PLATFORM=xcb` works, but wayland support would be nice.

[OpenGL wayland log](https://github.com/yuzu-emu/yuzu/files/8149186/yuzu_log.txt), [Vulkan wayland log](https://github.com/yuzu-emu/yuzu/files/8149191/yuzu_log.txt), [Vulkan xcb log](https://github.com/yuzu-emu/yuzu/files/8149193/yuzu_log.txt), [OpenGL xcb log](https://github.com/yuzu-emu/yuzu/files/8149194/yuzu_log.txt)

**Comment by puyoxyz** [comment]
Same here. Maybe it's the same situation as Dolphin emulator where the UI supports 
Wayland (because Qt does) but not the emulator?

**Comment by GreyXor** [comment]
I'm on Sway and it's working with `SDL_VIDEODRIVER=x11 QT_QPA_PLATFORM=xcb`.

We still need an native Wayland support and not rely on XWayland

**Comment by jefferyrlc** [comment]
I run into the same issue on KDE Plasma Wayland.

**Comment by raiguard** [comment]
Same here, Sway on Arch Linux.

Running it in xwayland works for now though.

**Comment by BionicKnight** [comment]
Having the exact same problem here, Hyprland on Archlinux.

**Comment by jbeich** [comment]
Should be fixed by #7410.

**Comment by RiedleroD** [comment]
can confirm, fixed in latest master
