### ISSUE TITLE
[Feature Request] Motion control with mouse

### ISSUE THREAD

**Issue by SysVR** [yuzu-emu/yuzu#7929]
Right-click to move the position of the gyro sensor.

Left-click to motion action key.
(Right-click+Left-click)

**Comment by BSoDGamingYT** [comment]
This feature already exists in the emulator

**Comment by SysVR** [comment]
> This feature already exists in the emulator

The automatic motion assignments do exist, but
But I can't find the setting for the operation I'm requesting.

I couldn't find it in the help either.

I searched for "Yuzu mouse motion", but the only way I could find was to use a device with a gyro sensor.

**Comment by german77** [comment]
If you double click on the motion input boxes "motion 1/2" it will assign the mouse as a motion input device. Here you will be able to to click and drag to use motion or if you enable mouse panning(Ctrl + F9) any mouse movement will move the motion too.

On a side note. Mouse is one of the worst types of motion input since 2D movements don't correlate to 3D movements

**Comment by SysVR** [comment]
> On a side note. Mouse is one of the worst types of motion input since 2D movements don't correlate to 3D movements

thank you.

**Comment by german77** [comment]
Depends on the game. Some use the gravity vector that is not supported by the mouse.

**Comment by tleydxdy** [comment]
I'm trying to run splatoon 3, I see in the code that the mouse movement doesn't seem to be translated into BasicMotion at all, only as normal axis?

**Comment by german77** [comment]
Splatoon is one of these games that use the gravity vector and not the gyro sensor. You need a real motion device

**Comment by tleydxdy** [comment]
interesting, basically I would need to map the mouse movement to accel_x and accel_z rather than gyro_x and gyro_z?

**Comment by tleydxdy** [comment]
basically I want to achieve something similar to this https://www.consoletuner.com/forum/viewtopic.php?p=83386#p83386 which translates mouse to motion control aim for splatoon

**Comment by Megasonic999** [comment]
I try using the mouse motion with new super mario bros u deluxe but it doesn't work, I can't use tilt controls.
Please help me.
No external controllers though please.
