### ISSUE TITLE
Allow the possibility to create a single save file (.sav)

### ISSUE THREAD

**Issue by watercranberrycornfig** [yuzu-emu/yuzu#7937]
https://github.com/yuzu-emu/yuzu/commit/2f45e999d8b4a7df2edc40bee28c7b4907c9f92a

Description:
In yuzu, by default, the save files from the games are saved in yuzu directory instead of the path where the game file is located. In addition, there can be several save files with different filenames.

This should be changed. It should be added an alternative possibility e.g. as an option that the save files are created as a single save file with the filename of the game file, or in case of existing ones, or, in the case of existing ones, that they can be converted. The save location is by default where the game file is located, but it is also possible to choose an individual save location. 

An example how it should look like.

Default:
Desktop/xxx.nsb
Desktop/xxx.sav

Individual:
Desktop/Games/xxx.nsb
Desktop/Saves/xxx.sav

**Comment by german77** [comment]
While this is practical it's inaccurate. Games are able to read other game save files and they need to be in the correct format and location.

**Comment by OZtistic** [comment]
This.. This is not how any of this works
The saves are in the same format that whatever specific game saves them in. 
Additionally, they are saved to the same folder location they are in the NAND on real hardware
You request will never be able to be fulfilled. It simply breaks too many things and it not the same as the hardware it originates from

**Comment by Morph1984** [comment]
Not only is it inaccurate, it is also impractical. All switch save managers import and export save data as directory save data. As a result, this solution cannot be implemented.

**Comment by Morph1984** [comment]
Closing.

**Comment by watercranberrycornfig** [comment]
It is a request for the future if the real hardware no longer exists.

It is also additionally an alternative solution instead of directory save data a file save data solution is offered. Similar to what you know from GBA and other emulators. The user can then decide for himself in which location he wants to choose and is not dependent on yuzu directory structure or real hardware.

**Comment by OZtistic** [comment]
This, as explained is a terrible idea. It would mean making a special format no one will support and fragment save files for no good reason other than to satisfy your want for a single save file. It can be done, with a LOT of work, but there is absolutely no need for it now or into the future. If the hardware doesn't support it, why should yuzu?
You also have to think about this if this format was ever supported, there will be people saying - "I have an xyz save, how do I use it on real hardware?"
Honestly, sorry. it's a bad idea that no other emu is gonna do, lest alone real hardware where you can dump your saves normally - and interchangeably with homebrew
You are more than welcome to develop this format on your own and PR it though
