### ISSUE TITLE
Xenoblade Chronicles 2 weird lines with  3x, 5x or 6x scaling resolution  (2x or 4x works perfect)

### ISSUE THREAD

**Issue by Phoenomenal** [yuzu-emu/yuzu#7938]
Hello, noticed weird lines when playing Xenoblade Chronicles 2  with 3x resolution (2160/3240p) on my 1440p monitor , same thing with 5x and 6x.  And the thing is either 2x or 4x don't have this problem.   Using  Yuzu 927  with this settings  : Vulkan, 3x resolution, bicubic,  fxaa,  gpu extreme, docked)  Tried change vulkan to opengl,  bicubic to other filters,  disable fxaa but same thing,  and as i write above only on 3x, 5x  or 6x   (2x and 4x run perfect)    Thats very strange, any ideas what to do to make it disappear ?   Tested some other games and 3x run fine there without these graphic bugs.   

Pictures below like in main screen noticeble lines where it supposed to be sea and in game many areas have similar problems :  
![Screenshot_1](https://user-images.githubusercontent.com/68902338/155485705-5d2b6571-97ca-42cc-ae6a-b008c17c7910.png)
![Screenshot_2](https://user-images.githubusercontent.com/68902338/155485720-2cdef225-0b55-42ae-9a3b-0daec2e8e9f1.png)

**Comment by G-Spawn** [comment]
Closing as this can be considered duplicates of https://github.com/yuzu-emu/yuzu/issues/7400 and / or https://github.com/yuzu-emu/yuzu/issues/7854 + many already reported issues of similar nature. The game is notorious for visual oddity with Scaler still. Pardon the inconvenience.
