### ISSUE TITLE
Linux: Pokemon let's go: unable to play with or feed pikachu and eevee

### ISSUE THREAD

**Issue by A-w-x** [yuzu-emu/yuzu#7950]
gpd win 3, x11 xfce4
portrait screen rotated using xorg conf files (screen and touch matrix)

something wrong with touchscreen inputs, cannot grab or move berries, they are stuck at the right side of the screen
working with a mouse

i can touch buttons just fine, but not pikachu and the berries

also the user hand is not rendered

![Screenshot_2022-02-25_23-22-56](https://user-images.githubusercontent.com/80461138/155811684-e210aac4-21a6-469b-afe5-43c780dee20b.png)

seems useless in this case (maybe useful for hand not rendered?)
not sure how to take logs for this
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8145265/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Are you able to try on updated intel drivers? 22 is a little dated. I believe they're on 30.x now.

**Comment by A-w-x** [comment]
30?
i m using mesa git, we are still at 22.1 devel

**Comment by G-Spawn** [comment]
30.x driver for windows seems to treat intel users fine. I can't attest for linux.

**Comment by A-w-x** [comment]
touch inputs are now working
