### ISSUE TITLE
Certain code not implemented in Kernel

### ISSUE THREAD

**Issue by funtimeandrefoxy** [yuzu-emu/yuzu#7958]
(Sorry for the vague title)
I decided to search the internet to see if there was any unofficial port of any counter strike on the nintendo switch.
And I found a port of the 1999 version of the game.

I tried running the game on this emulator and it just crashes.
One of the two reasons is because there is kernel-related unimplemented code.

I don't know what is not implemented regarding this code:

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8147511/yuzu_log.txt)

**Comment by gidoly** [comment]
ditto of #7957
