### ISSUE TITLE
Mario Kart 8 Multicore Emulation causes FPS drop

### ISSUE THREAD

**Issue by knightwing5432** [yuzu-emu/yuzu#7961]
The problem only started happening recently and whenever I turn on multi-core emulation the FPS drops to 1-5fps, however, when multi-core emulation is turned off FPS is 40-50 with terrible audio. The version of Yuzu that I am currently using is Yuzu 930.

System Specs:
 
Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 2001 Mhz, 4 Core(s), 8 Logical Processor(s)
Ram: 16gb
GPU: Nividia GTX 1050
Integrated Graphics: Intel UHD 620

attached below is a log file.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8148360/yuzu_log.txt)

Thank you

**Comment by knightwing5432** [comment]
I don't know the exact build, but I know around the time when it worked fine. It worked well around February 14th. In addition, pokemon arceus has become just a blank black screen and the last time it worked was around that time as well.

**Comment by PrinceBubloo** [comment]
It would be easier for ys if you can figure out the exact number.
Will be easier for us to fix it.

**Comment by knightwing5432** [comment]
Is there a way to access old builds, I'll just go through them and see which one works.

**Comment by knightwing5432** [comment]
Is there a way to access old builds I can go through them and see.

**Comment by knightwing5432** [comment]
Is there a way to access old builds I can go through them and see.

**Comment by PrinceBubloo** [comment]
https://github.com/yuzu-emu/yuzu-mainline/releases

**Comment by knightwing5432** [comment]
I ended up being able to solve the issue by deleting everything yuzu related and reinstalling it. Don't know what happened. Thank you!
