### ISSUE TITLE
Feature request: LDN play in the main build?

### ISSUE THREAD

**Issue by OctoTheBitch** [yuzu-emu/yuzu#7962]
For a while now, I've been struggling to play online with friends using Ryujinx LDN, and it'd be a great help for a lot of people if somehow LDN play could be implemented.

**Comment by FernandoS27** [comment]
It's in the works (slowly) and has made some nice progress recently. Sadly we are at full capacity everywhere working in a bunch of future projects. we expect that as we get the other projects working faster, we can allocate more resources for it.

**Comment by OctoTheBitch** [comment]
Ahh, fair. Thanks a lot for the reply though, nice to know that it's being worked on :] I wish you guys good luck!
