### ISSUE TITLE
documentation feature request

### ISSUE THREAD

**Issue by DeSchmiddi** [yuzu-emu/yuzu#7965]
The building instructions don't mention, that after installing conan, you will have to restart or relogin on linux before you can build. It would just be a sensual thing to write there as a note as this may cost new users or those unfamiliar with conan (like me) tons of time in troubleshooting.

**Comment by merryhime** [comment]
It's already documented, though probably not that clearly (see paragraph starting with "After installing Conan, ").

I'll add a section title to make it stand out a bit more.
