### ISSUE TITLE
Nvidia vulkan: Super Mario Odyssey: Texture not loading correctly

### ISSUE THREAD

**Issue by Macrox14** [yuzu-emu/yuzu#7968]
Hello, I having this issue with Mario Odyssey since today (a week ago was fine):

![1](https://user-images.githubusercontent.com/31378074/156100650-842c04cc-afee-43ec-a22b-05dec248f68f.png)
![2](https://user-images.githubusercontent.com/31378074/156100655-db087360-0732-41c6-934e-38ab016d8c04.png)

YUZU EA 2520

**Comment by gidoly** [comment]
Can you upload log with system spec?

**Comment by Macrox14** [comment]
hope this helps
AMD 5800x + Nvidia RTX3080 + W11
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8158604/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Can you please try using default resolution scaling, disabling async shaders in config graphics advanced, and right clicking the game and removing all pipeline caches and attempting it again?

**Comment by Macrox14** [comment]
I've just tried using default resolution scaling and disabling async shaders and the game started to working well! Then I enabled again 2x resolution and async shaders and was also working well. I don't know if disabling/enabling fixed the issue or the new update (EA 2524)
