### ISSUE TITLE
Games that need the latest audio revision 10

### ISSUE THREAD

**Issue by german77** [yuzu-emu/yuzu#7972]
These games use the newest audio features that are currently unimplemented 

Nintendo Switch™ Sports Online Play Test
[yuzu_log (1).zip](https://github.com/yuzu-emu/yuzu/files/8172690/yuzu_log.1.zip)

Atelier Sophie 2: The Alchemist of the Mysterious Dream
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/8172675/yuzu_log.zip)

TRIANGLE STRATEGY
[yuzu_log (40).zip](https://github.com/yuzu-emu/yuzu/files/8198896/yuzu_log.40.zip)

All Cave games
#8001 

Fire Emblem Warriors: three hopes demo

Missing functions 
```
Unknown / unimplemented function 'ListAudioOutputDeviceName': port='IAudioDevice' cmd_buf={[0]=0x1000006, [1]=0x8, [2]=0x300, [3]=0xC2E29B0, [4]=0x4, [5]=0x0, [6]=0x0, [7]=0x0, [8]=0x49434653}
```
```
Unknown / unimplemented function 'GetActiveAudioOutputDeviceName': port='IAudioDevice' cmd_buf={[0]=0x1000006, [1]=0x8, [2]=0x100, [3]=0x3F243168, [4]=0x10000008, [5]=0x0, [6]=0x0, [7]=0x0, [8]=0x49434653}
```
```
Debug <Critical> audio_core\effect_context.cpp:operator ():54: Unreachable code!
Unimplemented effect 7
```
```
Audio <Error> audio_core\audio_renderer.cpp:UpdateAudioRenderer:208: Audio buffers were not consumed!
Audio <Error> audio_core\info_updater.cpp:CheckConsumedSize:487: Output is not consumed! Consumed 5520, but requires 5904. 384 bytes remaining
```
```
Audio <Error> audio_core\audio_renderer.cpp:UpdateAudioRenderer:207: Audio buffers were not consumed!
Audio <Error> audio_core\info_updater.cpp:CheckConsumedSize:486: Output is not consumed! Consumed 10608, but requires 10864. 256 bytes remaining
```

**Comment by RinMaru** [comment]
is Bullet storm one of them?

**Comment by LainX84** [comment]
Atelier Sophie 2: The Alchemist of the Mysterious Dream : Same error : 
`[1075.134142] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:QuerySystemEvent:127: (STUBBED) called
[1075.153659] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:57: (STUBBED) called
[1075.154994] Service.Audio <Warning> core\hle\service\audio\audren_u.cpp:GetActiveAudioDeviceName:265: (STUBBED) called
[1075.165985] Audio <Error> audio_core\info_updater.cpp:CheckConsumedSize:487: Output is not consumed! Consumed 10800, but requires 12976. 2176 bytes remaining`

**Comment by alexfeed1990** [comment]
Im waiting on this too.

**Comment by AsafCohen9898** [comment]
I'm also waiting on this

**Comment by soleymanhz** [comment]
Im waiting on this too.

**Comment by german77** [comment]
We are aware that this feature needs to be implemented in many games. Please keep this issue open for listing new games or development questions.

**Comment by AsafCohen9898** [comment]
hi, is there any news on this issue? Thank you

**Comment by thojohns** [comment]
It appears as if this is the issue causing the Fire Emblem Warriors: Three Hopes demo not to boot - log is spammed with the following:

`[   9.605107] Audio <Error> audio_core/info_updater.cpp:CheckConsumedSize:485: Output is not consumed! Consumed 8624, but requires 10544. 1920 bytes remaining
[   9.605110] Audio <Error> audio_core/audio_renderer.cpp:UpdateAudioRenderer:207: Audio buffers were not consumed!`

I am assuming the same will apply to the full game as well.
