### ISSUE TITLE
Enabling Controller vibration causes frame drops

### ISSUE THREAD

**Issue by Distriived** [yuzu-emu/yuzu#7981]
It took awhile for me to troubleshoot this but I finally figured it out. I haven't tested it with any other games but I've been playing Luigis Mansion 3. I use an Xbox one controller over bluetooth and when the controller starts to vibrate ingame it causes a severe slowdown it even crashed a few times. After disabling controller vibration it solved the issue. I'm not a programmer so I don't know what could be causing this issue.

**Comment by v1993** [comment]
SDL probably blocks on vibration command. Dolphin solves this by handling vibration in a separate thread. @german77 - this is your domain.

**Comment by Bonk-Choy** [comment]
I got the same problem, whether the accurate vibration is enabled or not.

**Comment by Bonk-Choy** [comment]
It seems the problem is only with my Xbox One controller. When using DualSense, the FPS doesn't drop.

**Comment by german77** [comment]
Are you on discord? I got a build I want you to test
