### ISSUE TITLE
My Time at Portia - Crash/corrupted shader after char creation

### ISSUE THREAD

**Issue by Darth-Cthoras** [yuzu-emu/yuzu#7984]
Yuzu 943

Using Vulkan, run My Time at Portia with 1.0.9 patch. New Game, create character, hit + to finalize and okay, set birthday, game then crashes in load screen. When relaunching game, the final shader crashes Yuzu until MTaP's vulkan pipeline is deleted.

EDIT: Haven't tested with OpenGL.

AMD RX 6800XT, Ryzen 9 5900X, 32 GB DDR4.

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/8193703/yuzu_log.txt.old.txt)

**Comment by benderscruffy** [comment]
goes ingame with 1.0.9 no problem 
can be closed
