### ISSUE TITLE
Issue: GVC: Luminous Avenger iX 2 doesn't boot up

### ISSUE THREAD

**Issue by OctoTheBitch** [yuzu-emu/yuzu#7987]
Last night I dumped my copy of LAiX 2 for play on yuzu, and when I went to go and start it up, it just hung on launching for half an hour. I've tried troubleshooting on the official yuzu server for a while and nothing seemed to work, the log wasn't too useful either. 
I'm using yuzu 943.

**Comment by NineKain** [comment]
Post the log even if it wasn't useful there

**Comment by OctoTheBitch** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8197815/yuzu_log.txt)

**Comment by MarkIVPS** [comment]
Any news on that?

**Comment by OctoTheBitch** [comment]
So far, still no

**Comment by MarkIVPS** [comment]
I tested on Ryujinx... it works. But it slows down during gameplay.

**Comment by benderscruffy** [comment]
using the latest EA and mainline 
it is still an issue

**Comment by FearlessTobi** [comment]
Can confirm this game goes ingame now.
