### ISSUE TITLE
Intel: Linux: OpenGL [GLSL]: Legend Arceus: glitches and vertex explosions

### ISSUE THREAD

**Issue by A-w-x** [yuzu-emu/yuzu#7988]
same issue described here #7944 about weird gpu accuracy switch behaviour applies here too

the game has broken particles on boot with high that can be fixed by swithing to normal or viceversa, the difference is that when switching gpu accuracy in ogl there is no fps drop, the game is solid 30fps all the time

it has ramdom glitches while moving around

[yuzu_log.txt.zip](https://github.com/yuzu-emu/yuzu/files/8199523/yuzu_log.txt.zip)

about explosions:
![Screenshot_2022-03-07_17-57-41](https://user-images.githubusercontent.com/80461138/157082537-18b75fc4-1775-48a0-8b07-a0ff18e40a80.png)
![Screenshot_2022-03-07_17-58-37](https://user-images.githubusercontent.com/80461138/157082548-822e7e65-44de-463c-b654-0ec5238d2b43.png)
![Screenshot_2022-03-07_17-59-30](https://user-images.githubusercontent.com/80461138/157082556-9524b217-38a5-4af2-aae9-9dab2a28ff88.png)
![Screenshot_2022-03-07_18-00-02](https://user-images.githubusercontent.com/80461138/157082560-83e7b2c1-56c5-46f6-a624-6f0c5acc13c6.png)

**Comment by A-w-x** [comment]
fixed by iris cache rework in mesa

**Comment by Superduashwin** [comment]
So, if u keep in "_**GPU High**_" this vertex explosion stops.. but it lags so much in GPU high.. Here are the settings to **_"Max FPS"_** in gpu high  - 
0) REMOVE ALL 60 FPS MODS (they only reduce fps) :(
1)Remove Qol enhancements mod (if u have).. just keep the required bin files like removeblackscreen and switchsprintkeys...
2)Settings - (**CPU- Auto**) AND **_"HANDHELD"_**
![image](https://user-images.githubusercontent.com/88470329/232234126-12cb6818-677e-4bdc-94f7-75c560b4fa76.png)
![image](https://user-images.githubusercontent.com/88470329/232230217-9dae9b74-5163-4f11-a15a-d4d7f1b21e55.png)
![image](https://user-images.githubusercontent.com/88470329/232230224-49ddf29c-ab8b-477c-b149-65568a3c6f85.png)

Hope it works :)
