### ISSUE TITLE
Triangle Strategy NVIDIA corruptions

### ISSUE THREAD

**Issue by NineKain** [yuzu-emu/yuzu#7990]
Graphical corruptions on nvidia, log is not when the corruptions happened, just the normal log

![image](https://user-images.githubusercontent.com/72826232/157140969-df563ccd-5d9f-4846-ac8a-73266d685a69.png)
![image](https://user-images.githubusercontent.com/72826232/157140981-d2dc3122-61ee-4b7d-9e7c-914a766a60fa.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8201681/yuzu_log.txt)

**Comment by macaon** [comment]
OpenGL related. Works fine with Vulkan on nvidia.

**Comment by NineKain** [comment]
> OpenGL related. Works fine with Vulkan on nvidia.

Uh, no, I use Vulkan on a 3060ti

**Comment by JonathanWolfe** [comment]
This only happens when in docked mode:
![0100cc80140f8000_2022-03-20_20-35-32-954](https://user-images.githubusercontent.com/1449779/159193064-1dfc181c-6fe1-4b4c-9bcd-1bb3ea1cb3de.jpg)
handheld mode: 
![0100cc80140f8000_2022-03-20_20-41-50-603](https://user-images.githubusercontent.com/1449779/159193098-3beaa455-b92c-4160-9480-e256c62a6b38.jpg)

**Comment by Koby411** [comment]
White screens (as shown in the screenshots above), extremely bright sprites so i can't see whats going on in battles, floors becoming a rainbow mess, etc... all happening for me on Vulkan in mainline 963.

**Comment by darkedone02** [comment]
Same thing as well, on both OpenGL and Vulkan, at first I thought it was the cheats but apparently it's not.
I've not tried it undocked, but if that's what prevent it in the first place, then that's a workaround till they fixed docked.

![OMKwEQhKv7](https://user-images.githubusercontent.com/24425224/161345156-65659187-d0cf-4b29-a07d-a155e741b917.png)
![nN8YwyNN6N](https://user-images.githubusercontent.com/24425224/161345158-cccba1a6-18d5-45fd-b082-dd925a4b3809.jpg)

**Comment by Quoorex** [comment]
Had the same issue on an AMD GPU, both with OpenGL and Vulkan. I was able to fix it by turning off the depth of field effect in-game.

**Comment by Koby411** [comment]
> Had the same issue on an AMD GPU, both with OpenGL and Vulkan. I was able to fix it by turning off the depth of field effect in-game.

I've always had the DoF setting off.... yet the issues persist.

**Comment by coverton341** [comment]
Having similar issues to OP, 6900XT running Vulkan or OpenGL, depth of field off in the game. Complete white out of screen during battles. Had screen tearing that was fixed by turning off depth of field, but the white battle screen persists

**Comment by angrybear88** [comment]
Hi
Currently on 1050 TI max Q, anyone know what's with these white blocks that show up during fights? Thanks

![Screenshot 2022-06-21 085434](https://user-images.githubusercontent.com/107943717/174844675-6cbc3436-d0e4-4c17-87cf-86ebdedca23a.png)
!

**Comment by kirbyanator** [comment]
@angrybear88 it's an issue with depth of field, which you can turn off from Triangle Strategy's main menu. However, there seem to be other lighting and texture issues with both Vulkan and OpenGL on yuzu right now. I'm playing it on Ryujinx with a shader cache downloaded from emuSAK and it's running much better and accurately.

**Comment by Koby411** [comment]
> @angrybear88 it's an issue with depth of field, which you can turn off from Triangle Strategy's main menu. However, there seem to be other lighting and texture issues with both Vulkan and OpenGL on yuzu right now. I'm playing it on Ryujinx with a shader cache downloaded from emuSAK and it's running much better and accurately.

Again, this is wrong... because it's ALWAYS been an issue with this game to me and I've ALWAYS had DoF off.

**Comment by angrybear88** [comment]
> @angrybear88 it's an issue with depth of field, which you can turn off from Triangle Strategy's main menu. However, there seem to be other lighting and texture issues with both Vulkan and OpenGL on yuzu right now. I'm playing it on Ryujinx with a shader cache downloaded from emuSAK and it's running much better and accurately.

thanks, will try and report back.

**Comment by angrybear88** [comment]
Thanks friends, disabling depth of field in game got rid of the white box glitch, only issue left the frame timing above 30, everything still feels sluggish. I hope they optimize yuzu for this game soon, such a gem.

**Comment by vonchenplus** [comment]
Please test with the latest EA version and reopen the issue if you still have problems.
