### ISSUE TITLE
Pokémon Sword: Failures with the climates.

### ISSUE THREAD

**Issue by Xisnok** [yuzu-emu/yuzu#7991]
CPU: AMD Ryzen 3 3200G
RAM: 16 GB
OS: Windows 10 Home
Driver: AMD Radeon(TM) Vega 8 Graphics
Vulkan Driver: 2.0.213
Vulkan API: 1.3.203
Yuzu EA Build: 2531 (And other versions)

Pokémon Sword: The rain, the snow and the sandstorm freeze with normal gpu when playing and reaching the areas with these climates, 
the animation of these freezes and they act abnormally with the advance of the avatar these are freeze. 

Yuzu Log: 
[yuzu_log.txt.old.txt](https://github.com/yuzuemu/yuzu/files/8202483/yuzu_log.txt.old.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8202485/yuzu_log.txt)

Video:
https://user-images.githubusercontent.com/94726053/157161243-6fb9be4d-5df5-41d3-8e6f-7d07821c8703.mp4

**Comment by BSoDGamingYT** [comment]
Using high GPU accuracy is the fix...yes it will cost performance...but that is the price of accurate rendering
