### ISSUE TITLE
Flickering lens flare effect in Captain Toad: Treasure Tracker

### ISSUE THREAD

**Issue by v1993** [yuzu-emu/yuzu#7996]
Screenshot demonstrating the problem (cutscene level "The Hunt for the Great Bird's Lair", episode 1) - it's very apparent in this specific level due to camera positioning, but happens elsewhere too:

![01009bf0072d4000_2022-03-08_22-50-46-594](https://user-images.githubusercontent.com/16255906/157314727-96de258a-f4f8-4757-a295-dcca662fe7c9.png)

Happens both in OpenGL and Vulkan.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8209252/yuzu_log.txt)

**Comment by lKomus** [comment]
This glitch still happens in the latest versions. 
Here are some more screenshots, some showcasing a weird squared triangle effect:
![yuzu_Zdam2D1P97](https://github.com/yuzu-emu/yuzu/assets/4800879/504a71fc-004e-483a-9a7d-a93841120c10)
![yuzu_VasR53tAj9](https://github.com/yuzu-emu/yuzu/assets/4800879/cc6c1345-ca58-4147-9cf1-cd59115bd00a)
![yuzu_3n6hD2kAYP](https://github.com/yuzu-emu/yuzu/assets/4800879/27071dae-28ac-487f-b855-a96c360695c0)

**Comment by v1993** [comment]
Issue seems to be fixed on up-to-date yuzu version, closing.
