### ISSUE TITLE
AppVeyor errors

### ISSUE THREAD

**Issue by valentinvanelslande** [yuzu-emu/yuzu#8]
MinGW: C:/projects/yuzu/src/core/arm/unicorn/arm_unicorn.h:7:10: fatal error: unicorn/unicorn.h: No such file or directory
MSVC: Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)

**Comment by jroweboy** [comment]
@valentinvanelslande appveyor and travis are just copy pasted from citra. if you would like an easy contribution, fixing them to at least compile shouldn't be that hard <3 (at least for msvc on appveyor. i'd recommend not worrying about mingw on appveyor for now)

**Comment by N00byKing** [comment]
I'm gonna give it a try if y'all don't mind

**Comment by Hexagon12** [comment]
Make sure you both are following the building process correctly, you should select `Visual Studio 15 2017 Win64`, but not `Visual Studio 15 2017`.

**Comment by bobthecooldad** [comment]
not the mingw, i looked and i was like.. oh.. i dont do programming, i was just problem solving

**Comment by N00byKing** [comment]
don't close yours, i am pretty much a beginner mate, just trying my best.

You got one working so thats something @bobthecooldad

**Comment by bobthecooldad** [comment]
To fix the appveyor it needs to download the qt and the sdl2 inside and not in the cmake, I dont know how to do this, i am asking if you have any solutions?

**Comment by N00byKing** [comment]
On Line 25 the dependencies are listed for MinGW, probably for MSVC too, would start looking there (or just get the SDL Binaries and copy em, dont know if thats allowed doe)

**Comment by bobthecooldad** [comment]
Will try and add it there as it hangs on c compile and then goes back and gets the modules

**Comment by N00byKing** [comment]
Welp, looks like my stuff is obsolete
