### ISSUE TITLE
Cave games not booting with new game update.

### ISSUE THREAD

**Issue by Ragnar-es** [yuzu-emu/yuzu#8001]
Espgaluda II (update 1.05)
MushihimeSama (update 1.05)
DoDonPachi Resurrection (update 1.01)

Those 3 games are not booting with the new game update, I get an endless "launching" screen.

If I disable the new update or install the previous one it works.

Looks like Cave / LiveWire did something with that update that makes the games not bootable on Yuzu.

I attach the log in case it's needed.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8228965/yuzu_log.txt)

**Comment by shinslash** [comment]
also Deathsmiles 1+2

**Comment by Ragnar-es** [comment]
> 

Deathsmiles I - II (update 1.0.4) boots fine. Deathsmiles II when you go into DS II X or Arrange game mode Yuzu freezes for like 40 seconds, but then unfreezes and it works fine, Arcade mode doesn't freeze, works fine. Deathsmiles I works fine. Since this is another problem that has nothing to do with the one discussed here, I suggest you to make a new issue about that and attach a log.

Do the same with My Hero game, make another Issue for that game if you have any problems.

**Comment by german77** [comment]
Fixed by project Andio
