### ISSUE TITLE
decode.cpp error: constexpr function never produces a constant expression [-Winvalid-constexpr]

### ISSUE THREAD

**Issue by Dadada-77** [yuzu-emu/yuzu#8002]
Hello dear Yuzu developpers !

I’m filling a bug report as I’m trying to compile Yuzu (currently Yuzu EA 2538) on Gentoo Linux with the following toolchain :

LLVM / Clang 13.0.1
Musl 1.2.2

I’m stuck with some errors related to the file decode.cpp 

/var/tmp/portage/games-emulation/yuzu-early-access-2538/work/pineapple-src-EA-2538/src/shader_recompiler/frontend/maxwell/decode.cpp:67:16: error: constexpr f
unction never produces a constant expression [-Winvalid-constexpr] 
constexpr auto SortedEncodings() { 
              ^ 
/var/tmp/portage/games-emulation/yuzu-early-access-2538/work/pineapple-src-EA-2538/src/shader_recompiler/frontend/maxwell/decode.cpp:69:5: note: non-constexpr
function 'operator()<std::array<Shader::Maxwell::(anonymous namespace)::InstEncoding, 279> &, (lambda at /var/tmp/portage/games-emulation/yuzu-early-access-2
538/work/pineapple-src-EA-2538/src/shader_recompiler/frontend/maxwell/decode.cpp:69:29), ranges::identity>' cannot be used in a constant expression 
   ranges::sort(encodings, [](const InstEncoding& lhs, const InstEncoding& rhs) { 

There's some more errors on decode.cpp, probably linked to the first error. The log file of the compilation try is also provided.
[build.log](https://github.com/yuzu-emu/yuzu/files/8232234/build.log)

As Clang is only partially supporting std::ranges library, I’m also using range-v3 (https://github.com/ericniebler/range-v3), which provides all I need, and explaining why there's a ranges::sort instead of the current std::ranges::sort. However, after some searching, it seems that std::ranges::sort and ranges::sort are a bit different in their implementations of sort. I’d like to precise that decode.cpp can be compiled by switching from LLVM/Clang to GCC 11.2.1. So I don’t think the culprits are musl or range-v3, but really Clang not being able to guess the constexpr result hard enough, as GCC at least.

I’m not a C++ developer (I don’t really know the basics of this language), could you provide me some help in order to resolve this issue ?

Thanks by advance :)

**Comment by german77** [comment]
We won't provide support to unofficial builds.
