### ISSUE TITLE
Ys VIII: Unimplemented Texture Format 249

### ISSUE THREAD

**Issue by Lengualo** [yuzu-emu/yuzu#8014]
Yuzu is hanging on Ys VIII and throws some unimplemented formats and unknown framebuffer pixel formats. This happens occasionally on the title screen, but mainly during play after the first boss battle where after a cutscene the screen transitions to two moons and hangs either as this second scene starts or during the scene. Music continues to play but rendering pauses.

Error log reveals a few errors, mainly a heap of "[ 313.544704] Debug <Critical> video_core\surface.cpp:operator ():188: Assertion Failed! Unimplemented format=249"

Log: (trimmed for duplicate entries, there are many, its cascading the error):

```
[  32.573311] Debug <Critical> video_core\surface.cpp:operator ():188: Assertion Failed!
Unimplemented format=249
... (many duplicates) ...

[ 115.633842] Debug <Critical> video_core\surface.cpp:operator ():202: Assertion Failed!
Unimplemented format=2

[ 115.634107] Debug <Critical> video_core\renderer_vulkan\vk_blit_screen.cpp:operator ():107: Assertion Failed!
Unknown framebuffer pixel format: 2
... (many duplicates) ...

[ 119.306754] Debug <Critical> video_core\surface.cpp:operator ():188: Assertion Failed!
Unimplemented format=249
... (many duplicates) ...

[ 169.379514] Debug <Critical> video_core\texture_cache\format_lookup_table.cpp:operator ():223: Assertion Failed!
texture format=18 srgb=false components={1 0 3 2}
[ 169.379520] Debug <Critical> video_core\texture_cache\image_info.cpp:operator ():43: Assertion Failed!
[ 169.391074] Debug <Critical> video_core\surface.cpp:operator ():188: Assertion Failed!
Unimplemented format=249
... (many duplicates) ...

```

**Comment by PrinceBubloo** [comment]
@Morph1984

**Comment by Lengualo** [comment]
Just thought I would post an update after getting the chance to do some experimenting. I think this issue might not only be the unimplemented formats but another issue.

Firstly, this issue isn't just appearing on the logo splashes, its all fmv style cutscenes. So something about how they're orchestrating their cutscenes is throwing Yuzu. 

I'm a technical artist, not a programmer as such so this is just a hunch. But, I suspect its some kind of synchronisation issue between layers and/or audio are out of sync, and its hanging the renderer.

If Im fast and skip the splash screen or FMV sequence, the game runs really well. As an aside, occasionally the splash and fmvs will play, sometimes they dont.

Additionally, if I disable Multicore CPU Emulation the problem resolves. However this severely impacts performance.

**Comment by alexandar76** [comment]
I have same errors in log file for this game: Debug <Critical> video_core\surface.cpp:operator ():188: Assertion Failed!
Game works good, but text is highlighted and not good readable. This only happens for Vulkan. When i change to Opengl text is good but graphics not good. I have ATI GPU.

**Comment by gidoly** [comment]
close as duplicated with #6074
