### ISSUE TITLE
Rune Factory 4 x2 speed

### ISSUE THREAD

**Issue by RinMaru** [yuzu-emu/yuzu#8018]
RF4 runs at 2x the speed it should by default on yuzu

Windows 11 x64
AMD RX 480 4GB 22.2.3
R5 5600X
20GB Ram

EA 2545
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8241964/yuzu_log.txt)

**Comment by v1993** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/6605.
