### ISSUE TITLE
Graphical bug on Dragon Quest 2 in Vulkan/Opengl

### ISSUE THREAD

**Issue by qiuyang1008** [yuzu-emu/yuzu#8042]
There're some graphical bugs in the battle interface.
Log Pass: 123

![1](https://user-images.githubusercontent.com/38851431/159015820-a7e4f8ee-26d4-41e4-b6ba-3872467a5bfb.png)
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/8304990/yuzu_log.zip)

**Comment by qiuyang1008** [comment]
For the similar issue, you can also refer to the following link:
https://github.com/yuzu-emu/yuzu/issues/6507

**Comment by qiuyang1008** [comment]
The same with main map.. Graphical bug...

System Specs:

OS: Windows 10 Version 2009
CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz | AVX512 | FMA
GPU: Nvidia Titan Xp
RAM: 32 GiB

**Comment by benderscruffy** [comment]
@FearlessTobi 
has been fixed
can be closed
