### ISSUE TITLE
Breath of the Wild, Link clips into grass when moving slowly or standing still + Image + Log File

### ISSUE THREAD

**Issue by InsaneBrainGame** [yuzu-emu/yuzu#8045]
When running Breath of The Wild on Early Access using Vulkan or Open GL, Link will clip through grass if he is moving slowly or standing still.

This doesn't happen on stone etc.

![Open GL](https://user-images.githubusercontent.com/101916941/159108058-914237f1-939b-4771-9058-8ee236cceb8b.png)
![Vulkan](https://user-images.githubusercontent.com/101916941/159108062-2976a9f5-fb2b-4a79-8f63-a75aa0f9e952.png)
[yuzu_log_OpenGL.txt](https://github.com/yuzu-emu/yuzu/files/8308638/yuzu_log_OpenGL.txt)
[yuzu_log_Vulkan.txt](https://github.com/yuzu-emu/yuzu/files/8308640/yuzu_log_Vulkan.txt)

**Comment by G-Spawn** [comment]
Enable async gpu emulation. This is due to that being off.
