### ISSUE TITLE
Skylanders Imaginators not working

### ISSUE THREAD

**Issue by lukatorre** [yuzu-emu/yuzu#8049]
Skylanders Imaginators has never worked on this emulator, at most the game boots up save file and immediately crashes, at worst the game crashes at activision logo, but it doesn't crash the emulator, most of the time, just freezes the game.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8309163/yuzu_log.txt)

**Comment by G-Spawn** [comment]
This game is not going to work here anytime soon. The dev who tried improving amiibo functions experienced hardships trying to get imaginators to work.

**Comment by Francesco2426** [comment]
who the fuck would want to play that shit

**Comment by G-Spawn** [comment]
Removed the previous comment as it was condescending and had no place here.

**Comment by Francesco2426** [comment]
condescending because I called the game shit?

**Comment by G-Spawn** [comment]
Doesnt make it any less a valid issue. Save your comments for elsewhere.

**Comment by german77** [comment]
Yuzu now has native skylander support with a joycon or pro controller.
