### ISSUE TITLE
Controls panels is unreadable on 4K screen

### ISSUE THREAD

**Issue by LifeIsStrange** [yuzu-emu/yuzu#8051]
the inputs overflow the texts making them unreadable. I suppose this is because of HIDPI.
(15" screen)

**Comment by G-Spawn** [comment]
Yes yuzu doesn't really scale well with higher resolution or dpi. Using default dpi should help you a bit or 1080p.

**Comment by dkoluris** [comment]
Instead of workarounds, is there an option to enable hidpi support for QT?

**Comment by G-Spawn** [comment]
Not currently.

**Comment by jvhellraiser** [comment]
I report  this like a month ago when using Yuzu with my 4k display 
they haven't even try to fix the issue yet so don't expect for them to 
do it anytime soon.
