### ISSUE TITLE
[Enhancement] Support for AMD FSR 2.0

### ISSUE THREAD

**Issue by LifeIsStrange** [yuzu-emu/yuzu#8052]
https://www.phoronix.com/scan.php?page=news_item&px=AMD-FidelityFX-Super-Res-2.0
The 2.0 should be opensourced in the coming weeks and can improve the rendering quality of games :)

**Comment by FIocker** [comment]
And requires game implementation just like DLSS including access to the depth buffer and temporal data like motion-vectors.

You can't just implement this into emulators like FSR 1.0

**Comment by LifeIsStrange** [comment]
You are probably right, however I think Yuzu could attempt to integrate [this solution](https://jcgt.org/published/0010/03/02/) as a potential sucessor to FSR since it is temporal based has the innovative property fo not requiring motion vectors

**Comment by G-Spawn** [comment]
> And requires game implementation just like DLSS including access to the depth buffer and temporal data like motion-vectors.
> 
> You can't just implement this into emulators like FSR 1.0

^ Closing for aforementioned reason.
