### ISSUE TITLE
Mario Kart 8 Vulkan Render Regression from Project ART

### ISSUE THREAD

**Issue by Stiffy360** [yuzu-emu/yuzu#8053]
Mario Kart 8 had a Vulkan regression in rendering from project ART (Build 812) This issue persists into the current mainline build (at the time of writing, Build 956)

The rendering regression seems to affect maps with cloud shadows and in general lightmapping. The effect is extremely pronounced at 3x Rendering scale but still didn't look correct even at 1x scaling on the Vulkan back-end. Open GL GLASM does not have this issue and renders the scene correctly. The Cache was cleared every time a version was changed and the RHI was changed as well.

Here are some images detailing the regression. These were tested on Time Trial on the course "Moo Moo Meadows" in the Shell Cup, but other courses see regressions in rendering as well.

This is Build 956 (Current)

Vulkan 1x
https://i.imgur.com/FH9KDlG.jpeg
Vulkan 3x
https://i.imgur.com/uQ0cJ3J.jpeg
OGL GLASM 3x
https://i.imgur.com/1f2VggB.jpeg

Here is Build 812 (Project ART)

Vulkan 1x
https://i.imgur.com/zynidoO.jpeg

Vulkan 3x
https://i.imgur.com/aIa7kCP.jpeg
OGL GLASM 3x

Here is Build 811 (Version before Project Art)

Vulkan 1x
https://i.imgur.com/fZ0oYA8.jpeg
OGL GLASM
https://i.imgur.com/MbwUAgy.jpeg

This was all tested on Version 1.7.2 of Mario Kart 8 Deluxe

Logs from Each Build attached.

[yuzu_log_956.txt](https://github.com/yuzu-emu/yuzu/files/8310610/yuzu_log_956.txt)
[yuzu_log_811.txt](https://github.com/yuzu-emu/yuzu/files/8310611/yuzu_log_811.txt)
[yuzu_log_812.txt](https://github.com/yuzu-emu/yuzu/files/8310612/yuzu_log_812.txt)

Additional information can be provided as needed

**Comment by FIocker** [comment]
Now I know why Moo Moo Meadows felt so dark lately.

**Comment by gidoly** [comment]
seems it is issue caused by anistrophic filter auto. use default to fix this issue
