### ISSUE TITLE
A Boy and His Blob runs upside down

### ISSUE THREAD

**Issue by mavlok** [yuzu-emu/yuzu#8056]
A Boy and His Blob appears reversed, both vertically and horizontally.

Yuzu version 957, but the problem exists for at least a year now.
Intel i5-8500, Radeon RX580, 16GB

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8315541/yuzu_log.txt)

![Screenshot 2022-03-21 150331](https://user-images.githubusercontent.com/101994820/159266553-7d5c12bd-01c3-48f4-83e0-83d7ea43cf7f.jpg)

**Comment by dkoluris** [comment]
I have this problem on several Games too. Guacamelee and Streets of Rage to name a few. The problem as far as I understand is that both our GPUs do not support `Viewport Swizzle` even with the latest drivers update. I would love if there was an alternative implementation to this somehow.

**Comment by m1steron** [comment]
Same here. A number of games experience this issue and others that should work, displaying a blank screen.
As it's an issue that seems to effect the AMD RX XXX series of cards is it possible to implement an option in Yuzu to flip the rendered output some how?

Related issues:

vk_rasterizer: Flip viewport on Y_NEGATE #6765

Proper viewport flip emulation #2703
