### ISSUE TITLE
An error occurred initializing the video core. [Bug Report]

### ISSUE THREAD

**Issue by thunderzx69** [yuzu-emu/yuzu#8059]
When I try to run any game, it either gives me an error or it doesn't respond. (I waited 10 minutes, nothing) 
<img width="247" alt="image" src="https://user-images.githubusercontent.com/102067070/159357207-759ca8b2-0ef0-4d87-8102-a8d23bfbf890.png">

I checked the log files... it seems to have something to do with Vulkan? I have an Intel GPU so it would be better to use Vulkan.. if I use OpenGL It doesn't respond again
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8319021/yuzu_log.txt)

I'm not sure if it's something to do with my specs but I'll put them here anyway.
CPU - i7-1165G7
Memory - 16GB 
GPU - Intel Iris Xe Graphics

**Comment by goldenx86** [comment]
Outdated GPU driver in use, manually update to the latest version: https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html?
