### ISSUE TITLE
[Enhancement] Nvidia Reflex support

### ISSUE THREAD

**Issue by LifeIsStrange** [yuzu-emu/yuzu#8060]
https://www.nvidia.com/en-us/geforce/news/reflex-low-latency-platform/
It would allow to improve FPS/latency, that would be amazing. Not everybody has the hardware to run breath of the wild in 60FPS :/

**Comment by BreadFish64** [comment]
This is not feasible to implement in an emulator and the SDK license is incompatible regardless.

**Comment by LifeIsStrange** [comment]
@BreadFish64 However I think you could add support for https://github.com/ishitatsuyuki/LatencyFleX, it is hardware agnostic, has no licence issue and seems to not require deep integration!
The performance improvements are huge!

**Comment by G-Spawn** [comment]
> 

Closing for aforementioned reason by dev.
