### ISSUE TITLE
[Enhancement] Support for Intel XeSS

### ISSUE THREAD

**Issue by LifeIsStrange** [yuzu-emu/yuzu#8061]
https://www.reddit.com/r/linux_gaming/comments/p7ifnf/intel_xess_4k_upscaling_demo_crossvendor_aibased/
Works on any hardware and can offer better results than FSR 1.0

**Comment by LifeIsStrange** [comment]
What @BreadFish64 The problem you are refering is the need of motion vectors info right?
I don't think FSR 2.0 has this problem but this is likely an issue for XeSS

**Comment by BreadFish64** [comment]
All of these technologies require **accurate** motion vectors, the depth buffer (we would need to guess which depth buffer is the right one if it exists at all), and a way to add sub-pixel jitter to the 3D project, which is not feasible to do since games render things that shouldn't be jittered or will be re-used in other scenes.
I attempted to add DLSS as experiment and the end result is not something you'd ever want to use:
https://www.youtube.com/watch?v=B1-X1w2bzFg

**Comment by LifeIsStrange** [comment]
That's unfortunate to hear, I hope that a solution will one day be found. Support for other antialiasing algorithms than FXAA is probably the priority regarding graphical impact for Yuzu though.

**Comment by v1993** [comment]
Running at higher resolution than your screen with appropriate window filter (that is, bilinear/bicubic/gaussian, depending on resolution difference) already acts as SSAA. TAA is currently possible with use of external tools (I use vkBasalt).

**Comment by CrusadingNinja** [comment]
> That's unfortunate to hear, I hope that a solution will one day be found. Support for other antialiasing algorithms than FXAA is probably the priority regarding graphical impact for Yuzu though.

Rendering at a higher resolution and then subsequently downsampling to your monitor's resolution is already supported in yuzu and yields better results than any anti aliasing technique ever will.

**Comment by LifeIsStrange** [comment]
@BreadFish64 For posterity, there exists some temporal based FSR 2.0/DLSS/XeSS competitor that does not require motion vector. See e.g. https://jcgt.org/published/0010/03/02/ This might be the future ideal successor for FSR 1.0 in emulators that cannot provide motion vectors.

**Comment by gidoly** [comment]
closing due to have no feasible way to implememnt like bread fish told
