### ISSUE TITLE
[Enhancement] Support for AMD CAS

### ISSUE THREAD

**Issue by LifeIsStrange** [yuzu-emu/yuzu#8063]
apparently it can be complementary to FSR when combined https://gpuopen.com/fidelityfx-cas/
https://www.reddit.com/r/Amd/comments/o60bcc/psareshade_cas_improves_fsr_dramatically/

**Comment by BreadFish64** [comment]
RCAS is the second step of FSR. It's already built-in.

**Comment by LifeIsStrange** [comment]
I was not aware of that
