### ISSUE TITLE
XC2 graphics glitches using vulkan

### ISSUE THREAD

**Issue by lovebabyx** [yuzu-emu/yuzu#8069]
I got this kinda stuff using vulkan, doesn't happen on opengl. does anyone know what's happening? i only get this visual blurry when using mainline version , the EA version still works normally , Usually happens after about 15-30 minutes of play time or some kind of transition like a cutscene

Yuzu version : yuzu mainline 958
CPU accuracy : Auto
Video API : Vulkan
Video accuracy : High
Resolution : x1
Window Adapting Filter : FSR
AAM : FXAA
Processor : Intel Core i7-3770
GC : GeForce GTX 1050 2GB
Memory : 8GB
System Commit/Virtual memory limit : 25Gb
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8323836/yuzu_log.txt)
![nhoe](https://user-images.githubusercontent.com/102152983/159473709-53e19a24-d522-45d0-8838-e1165ad119ba.png)
![yuzu crashhh](https://user-images.githubusercontent.com/102152983/159475671-223f60c1-aeda-422a-acf6-3ba492a06609.png)

**Comment by lovebabyx** [comment]
Ive even set page file to 100gb and still not working ,I don't understand why only the mainline version has this error , other versions work fine.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8330061/yuzu_log.txt)
![other log](https://user-images.githubusercontent.com/102152983/159632074-8c334bdf-71f3-4d9f-9185-9039f0098478.png)

**Comment by CrusadingNinja** [comment]
There are known issues with Vulkan and GPUs with low VRAM (2 GB or less) such as yours. If you say EA does not have the issue while mainline has it, it is almost certain #7720 fixes it since that PR is not yet present in mainline.

**Comment by lovebabyx** [comment]
> There are known issues with Vulkan and GPUs with low VRAM (2 GB or less) such as yours. If you say EA does not have the issue while mainline has it, it is almost certain #7720 fixes it since that PR is not yet present in mainline.

yea all EA versions before 2506 work fine , after EA version 2506 I still get this issues sometimes but only after a few hours of playing.

**Comment by lovebabyx** [comment]
> There are known issues with Vulkan and GPUs with low VRAM (2 GB or less) such as yours. If you say EA does not have the issue while mainline has it, it is almost certain #7720 fixes it since that PR is not yet present in mainline.

can you pls recommend me which yuzu versions fix this error?
thanks anw!

**Comment by CrusadingNinja** [comment]
> > There are known issues with Vulkan and GPUs with low VRAM (2 GB or less) such as yours. If you say EA does not have the issue while mainline has it, it is almost certain #7720 fixes it since that PR is not yet present in mainline.
> 
> can you pls recommend me which yuzu versions fix this error? thanks anw!

any new version should fix or at least alleviate it. The PR I mentioned was recently merged. Unfortunately, no real guarantees as Vulkan generally has trouble with low VRAM GPUs.

**Comment by gidoly** [comment]
closing due to resolved. grabage collector can aggresive to low vram count. it is limitation of low vram. we can not clean vram to avoid issue but it will leak ram and crash yuzu with in hours.
