### ISSUE TITLE
Are the icons8 icons used actually CC BY-ND 3.0?

### ISSUE THREAD

**Issue by 06kellyjac** [yuzu-emu/yuzu#8077]
Are the icons8 icons actually CC BY-ND 3.0?

https://github.com/yuzu-emu/yuzu/blob/master/license.txt#L344-L361

This license below doesn't look CC BY-ND 3.0, did they used to be licensed that way?

https://intercom.help/icons8-7fb7577e8170/en/articles/5534926-universal-multimedia-licensing-agreement-for-icons8

---

When packaging yuzu for nixpkgs we dont distribute a cached build since it uses CC BY-ND 3.0 icons let alone whatever that custom unfree license is.

**Comment by Docteh** [comment]
This appears to be where the icons8 icons are claimed to be CC BY-ND 3.0
https://github.com/yuzu-emu/yuzu/blob/master/dist/license.md

I didn't immediately clue in, but it looks like the main license.txt was updated around the time you opened this issue. 
[Highlighted lines, previous version](https://github.com/yuzu-emu/yuzu/blob/fd40d55a4ff2b02bf79e86b5c996cc1b520ba6ac/license.txt#L344-L361)

This appears to be a PR covering the last revision to the icons: https://github.com/yuzu-emu/yuzu/pull/3574

Looks like they used to be available under that license. 

My first thought was to go to Internet Archive to see what is available. The oldest pages mention a VisualPharm company, and the exact license is only mentioned inside the .zip

https://web.archive.org/web/20111128005248/http://icons8.com/download-huge-windows8-set

https://github.com/citra-emu/citra/pull/5093#issuecomment-604676784

Just to confirm, it looks like the comment I'm linking, and you are stating that the "CC BY-ND 3.0" license, particularly the Non Derivative part are not good for package distribution?

**Comment by 06kellyjac** [comment]
Thanks for doing that digging.

> you are stating that the "CC BY-ND 3.0" license, particularly the Non Derivative part are not good for package distribution?

Yeah, in nixpkgs we don't touch `CC BY-ND 3.0` and have it build on the end-user's machine like the rest of our packages marked unfree (`free = false`)
https://github.com/NixOS/nixpkgs/blob/master/lib/licenses.nix#L212-L216

> https://github.com/citra-emu/citra/pull/5093#issuecomment-604676784

And it looks like most others dont too

Also I just wanted to double check if that license even still applied and let you all know
