### ISSUE TITLE
Animal Crossing: New Horizons - RDNA2  Issue

### ISSUE THREAD

**Issue by PaintFoxV** [yuzu-emu/yuzu#8078]
Windows 10 x64 21H2
AMD Radeon  6600XT -  22.2.3+
R5 2600X
16GB Ram
Vulkan 
OpenGL untested
Game Version: 2.02

**Occured with:** 

Async GPU On/Off 
Async Shaders On/Off
Res Scaler 1x/2x 
Every AA Method 
Every Windows Adapting Filter 

**Yuzu 960**

![unknown](https://user-images.githubusercontent.com/52379593/159961097-148c5060-bf75-4b66-ac10-fcee6c0f8e06.png)

No issues with Driver Version 22.1.2 :  
![image](https://user-images.githubusercontent.com/52379593/159962711-99965b5a-f477-406c-936c-7cafa7efbd3d.png)

**Comment by gidoly** [comment]
closes issue as it is driver issue rather than yuzu issue
