### ISSUE TITLE
Observed crashes on cutscenes in Rune Factory 5

### ISSUE THREAD

**Issue by KylerNyhagen** [yuzu-emu/yuzu#8081]
It's unfortunately not very reproducible, but every now and then the cutscenes cause crashes in RF5. Yuzu itself hard crashes.

**Comment by ajseavey** [comment]
I haven't specifically had issues with cutscenes, but have seen runaway VRAM usage causing graphical glitches including corrupted cutscenes ultimately leading to the game crashing, usually on scene transition including to a cutscene.

**Comment by gidoly** [comment]
please post log and pc sepc

**Comment by gidoly** [comment]
closes due to not provide log and detailed info
