### ISSUE TITLE
Systematic crash on quit after I run a game

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#8083]
yuzu 960 (2022-03-23)
Gaming laptop ASUS GL703GS, Win 10, i7-8750H (6+6 cores), NVidia 1070 8GB, 32GB RAM, 1920x1080 144Hz G-Sync laptop screen, NVMe + SSD

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8352451/yuzu_log.txt)

If I run Yuzu and just quit, it's all right.
**After I run a game** (any game, it doesn't matter) and then quit the emulator with CTRL+Q or from menu I noticed there's a silent Yuzu crash logged in Event Viewer, e.g.:

Nome dell'applicazione che ha generato l'errore: yuzu.exe, versione: 0.0.0.0, timestamp: 0x623b181b
Nome del modulo che ha generato l'errore: yuzu.exe, versione: 0.0.0.0, timestamp: 0x623b181b
Codice eccezione: 0xc0000005
Offset errore 0x000000000019ed32
ID processo che ha generato l'errore: 0x2410
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d84067a47170c2
Percorso dell'applicazione che ha generato l'errore: C:\Users\Luca\Yuzu\yuzu.exe
Percorso del modulo che ha generato l'errore: C:\Users\Luca\Yuzu\yuzu.exe
ID segnalazione: cb5f93f8-c1bb-4d65-a1c2-80df6d309ce0
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore: 

I tried to change cfg (screen modes, CPU modes, default settings, audio output=null...), UI cfg, general cfg but can't solve this. Maybe is audio related because I can hear a sort of click sound when it silently crashes (I notice it crashes because 1 sec after I quitted yuzu, the pointer turns to pointer+wheel, like when there's some task background activity).

**Comment by Abyss777111** [comment]
This also happens on yuzu after starting the game and exiting

if you start the emulator without starting the game and close it, then there are no errors in the windows log

  on Ryujinx exit without error

**Comment by v1993** [comment]
Yuzu is pretty infamous for its exit crashes. This is well known among developers, but not that high priority for now.

**Comment by Hexaae** [comment]
Note: you can gracefully "exit" the emulator brutally killing its task from Task Manager instead of CTRL+Q or menu. This won't generate crashes ;-)

**Comment by Abyss777111** [comment]
Understandably

but it’s probably worth fixing and not postponing it for later, because the crooked interface is sometimes pretty annoying

  + probably not many people paid attention to this problem, they can forget about it

I want my favorite emulsion to work perfectly

**Comment by Hexaae** [comment]
Am I wrong or it has been fixed using latest Mainline Build - 1a4d4f205 for Windows?

**Comment by Hexaae** [comment]
Problem solved with latest updates. There are still some crashes in some specific situations, but this one is solved.
