### ISSUE TITLE
More Aspect Ratio options

### ISSUE THREAD

**Issue by Destroyer4LP** [yuzu-emu/yuzu#8084]
There are currently three  aspect ratio options in yuzu. More and more laptops are getting 16:10 displays.
Can we get more aspect ratio options, please?
Thank you

**Comment by CrusadingNinja** [comment]
That's what the "Stretch to Window" option is for.

**Comment by Emogop** [comment]
> More and more laptops are getting 16:10 displays.

Are we sure living in 2022?

**Comment by SilverDarkBlade** [comment]
> That's what the "Stretch to Window" option is for.

An option for custom ratios with black borders would be ideal.
