### ISSUE TITLE
Bowser's Fury Game Freezing on startup, leading to crash.

### ISSUE THREAD

**Issue by FloorWasTaken** [yuzu-emu/yuzu#8086]
Hello, I am having some trouble with Super Mario Bros 3D World, mainly the Bowser's Fury side of the game. Which, it worked PERFECTLY but then just recently, the game froze, the emulator closed, I tried reopening the game, restarting my computer, and It wouldn't work. I had 2 other games, Super Mario Odyssey and Super Mario Maker 2, those still work just fine, but it's mainly that game that I'm having issues with.  The game will open just fine, I'll click on "resume" the loading will finish, and the FPS will just drop straight to 0. (I have a pretty good pc) And it would just stay there, and a few seconds later, Yuzu closes completely. 

If you have any solutions, that would be great!

Have a good rest of your day,
Floor 
:)

Image of issue:
![Screenshot 2022-03-25 222731](https://user-images.githubusercontent.com/80715900/160221315-87e2c175-b5da-49b0-a07f-0011a95bfad7.png)

**Comment by G-Spawn** [comment]
Please provide a log file when possible https://yuzu-emu.org/help/reference/log-files/

**Comment by G-Spawn** [comment]
"The game will open just fine, I'll click on "resume" the loading will finish, and the FPS will just drop straight to 0" This kind of sounds like you're pausing the game after it launches. Since you can't 'resume' it unless it is paused. The game will drop to 0 fps when paused.

**Comment by G-Spawn** [comment]
> Please provide a log file when possible https://yuzu-emu.org/help/reference/log-files/
