### ISSUE TITLE
Rune Factory 5 Crash

### ISSUE THREAD

**Issue by DDC4321** [yuzu-emu/yuzu#8111]
Rune Factory 5 

Keeps crashing on launching window. Version 967
but version 925 works.

MY specs are Win 8.1 
12 Gb Ram
Super 165
Attaching log also
[yuzu_log - RF5.txt](https://github.com/yuzu-emu/yuzu/files/8368294/yuzu_log.-.RF5.txt)

**Comment by gidoly** [comment]
while issue is valid it will be hard to track issue in futrure since we dropped windows 8 support. closing, feel free to open another issue if you face same issue on windows 10/11
