### ISSUE TITLE
Legends Arceus crashes after intro screen on Vulkan AMD

### ISSUE THREAD

**Issue by LAVEXLEON** [yuzu-emu/yuzu#8114]
I am experiencing this issue since the release of pokemon legends Arceus. The Arceus intro scene works just fine but it crashes soon after the intro is over. The game works fine in OpenGL which confirms that this issue is specifically for Vulkan API. Here are my specs: 
AMD Radeon 535
Intel Core i5 8th Gen 8250u
Ram: 8GB
OS: Win 11

**Comment by Itamai** [comment]
Post a log: https://yuzu-emu.org/help/reference/log-files/

**Comment by G-Spawn** [comment]
If this issue still happens to you please feel free to reopen issue & provide a log file from latest yuzu(https://yuzu-emu.org/help/reference/log-files/).
