### ISSUE TITLE
Super Mario 3D World won't start after a yuzu update

### ISSUE THREAD

**Issue by dejancg** [yuzu-emu/yuzu#8119]
Super Mario 3D World crashes just after the music starts playing before the "Resume/New Game" screen is displayed. That's after the game selection screen where you are able to switch between this game and Bowser's fury.
Using yuzu 969 (2022-03-30)
Log file here: [https://pastebin.com/4HucE7FE](https://pastebin.com/4HucE7FE)

This issue has started with yuzu 964 (yuzu-windows-msvc-20220326-16c20e585).
The game works fine with 963 (yuzu-windows-msvc-20220325-15bf148da).

**Comment by v1993** [comment]
Does this still happen in latest yuzu version? If so, this appears to be caused by https://github.com/yuzu-emu/yuzu/pull/8088.

**Comment by dejancg** [comment]
@v1993 Just tried with version 20220331-98ae39f75.
It still doesn't work, but the behavior seems to be a little bit different. It freezes for a second or two before crashing. The log file is also larger.

Log here: [https://zerobin.net/?331aba8cee264cb8#ciWXLEpnU09tbtxQA6oN5HeDYD8x2OCxs0YiggHaSr4=](https://zerobin.net/?331aba8cee264cb8#ciWXLEpnU09tbtxQA6oN5HeDYD8x2OCxs0YiggHaSr4=)

**Comment by dejancg** [comment]
Confirmed working with yuzu 972 (20220402-6f57f3944). Thanks!
