### ISSUE TITLE
Yuzu crashing when trying to open Configure

### ISSUE THREAD

**Issue by aaron-axisa** [yuzu-emu/yuzu#8125]
I am trying to use the non-early-access version of yuzu and whenever i try to open the configure menu it crashes. 

Version of yuzu: 970 (2022-03-31) 

OS: Windows 11 Pro version 21H2 build 22000.556
Processor: AMD Ryzen 9 5950x
RAM: 128GB

Crash report:
```
Faulting application name: yuzu.exe, version: 0.0.0.0, time stamp: 0x6245a308
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process ID: 0xb0f0
Faulting application start time: 0x01d8451683bfa426
Faulting application path: C:\Users\Aaron\AppData\Local\yuzu\yuzu-windows-msvc\yuzu.exe
Faulting module path: unknown
Report ID: 877f1429-8355-405e-8687-f4bb393f779f
Faulting package full name: 
Faulting package-relative application ID: 
```

I cleared the log file before replicating it and nothing gets added to the log file.

Nvidia control panel is set to use the GeForce RTX 3090

**Comment by aaron-axisa** [comment]
Gshade is installed in fact. 
Is there no way to run it without uninstalling it since that would mean being unable to run yuzu and other games really...

Would this work if it's run inside a vm of a pc that has gshade?

**Comment by aaron-axisa** [comment]
To whoever has the same issue.

I started up a vm on my pc with windows 11 (fairly clean)

installed the C++ distributable and yuzu,  and seems to be not crashing anymore. 

As for performance in this setup I guess but it's better than not being able to use it at all I guess.

**Comment by G-Spawn** [comment]
> To whoever has the same issue.
> 
> I started up a vm on my pc with windows 11 (fairly clean)
> 
> installed the C++ distributable and yuzu, and seems to be not crashing anymore.
> 
> As for performance in this setup I guess but it's better than not being able to use it at all I guess.

Don't bother using a vm for yuzu. It won't work and 90% of windows hypervisors do not provide gpu passthrough. Only linux qemu-kvm and a few others do. Please just uninstall Gshade if you'd like to use yuzu normally on your host machine. As you were previously advised.

**Comment by ryaav** [comment]
I fixed this by turning off nvidia shadowplay
