### ISSUE TITLE
[Windows] [Feature Request] Controllers applet - always opening

### ISSUE THREAD

**Issue by DmitryOlenin** [yuzu-emu/yuzu#8132]
There is an annoying situation (all versions including last Windows-Yuzu-EA-2629).
Every time I try to play split screen, pop-up window from Controllers applet appears.
It's a modal window, I can't press any button in game until I close it (press OK).
If game was in fullscreen mode (f11), you need to Alt+Tab and close that applet.

My suggestion.
Save last controllers settings and apply it automatically (without opening applet).
If user want to change something in controllers (3 players insted of 2 for example), he can open settings.
Applying last controllers settings could be switchable (On/Off) in global settings.

[![FastPic.Ru](https://i116.fastpic.org/thumb/2022/0401/11/4ff0395a2f1ad470605898e062047911.jpeg)](https://fastpic.org/view/116/2022/0401/4ff0395a2f1ad470605898e062047911.jpg.html)

**Comment by G-Spawn** [comment]
A way to avoid the applet entirely is to just have the last connected controller do the L+R menu and then use first player to navigate to multiplayer.

**Comment by tastyratz** [comment]
This drives me nuts too because the applet requires a keyboard and mouse while I use a controller and front end for everything else.

I almost always just click ok. I wish it didn't pop when I have nothing to change or do.

@G-Spawn what do you mean? Hit L+R when the applet pops to dismiss it using the controller?

**Comment by G-Spawn** [comment]
> This drives me nuts too because the applet requires a keyboard and mouse while I use a controller and front end for everything else.
> 
> I almost always just click ok. I wish it didn't pop when I have nothing to change or do.
> 
> @G-Spawn what do you mean? Hit L+R when the applet pops to dismiss it using the controller?

"have the last connected controller do the L+R menu and then use first player to navigate to multiplayer"

Let's say you setup 2 controllers for yuzu prior to game launch. You run game and then have the second controller hit L+R in that intro menu. Then when the first controller navigates to multiplayer. The popup for applet does not happen.

**Comment by maddox** [comment]
>A way to avoid the applet entirely is to just have the last connected controller do the L+R menu and then use first player to navigate to multiplayer.

This is practically impossible for my kids to remember, and a complete impossibility for friends that are over that just want to play a little. While I'm glad there's a work around, I really hope that there's plans to ease this problem in the future.

**Comment by mdac3564444** [comment]
Agreed...family & friends finds this a big hassle. A way to shut off these messages would be preferred.

**Comment by dennore** [comment]
> There is an annoying situation (all versions including last Windows-Yuzu-EA-2629). Every time I try to play split screen, pop-up window from Controllers applet appears. It's a modal window, I can't press any button in game until I close it (press OK). If game was in fullscreen mode (f11), you need to Alt+Tab and close that applet.
> 
> My suggestion. Save last controllers settings and apply it automatically (without opening applet). If user want to change something in controllers (3 players insted of 2 for example), he can open settings. Applying last controllers settings could be switchable (On/Off) in global settings.
> 
> [![FastPic.Ru](https://camo.githubusercontent.com/a790523bcb98853a8e1648f6b877cca4ee879cc48a14ef6eff2ee81bac28ead7/68747470733a2f2f693131362e666173747069632e6f72672f7468756d622f323032322f303430312f31312f34666630333935613266316164343730363035383938653036323034373931312e6a706567)](https://fastpic.org/view/116/2022/0401/4ff0395a2f1ad470605898e062047911.jpg.html)

Just made a Autohotkey script which enables the second controller and clicks ok as soon as this window „Controller-Applet“ appears. Works even in fullscreen when this window is not visible on screen. My kids love it

**Comment by tastyratz** [comment]
I feel like the official workaround here isn't really good or what people want so I'm not really thinking this one is "closed" @G-Spawn ? It's still getting attention. I agree like others have mentioned it's neither intuitive or approachable for new users.

@dennore do you mind posting your ahk? I could add this to Launchbox for yuzu and it sounds like the best option right now over fixing it natively.

**Comment by dennore** [comment]
Sure here is my autoitscript which is running in „shell:startup“ which i dont care. Cause i use this computer for emulation only…
It also might be possible to have it only running when you launch a game… im using playnite as gamelauncher (its awesome)

`
while 1 {
winwaitactive, Controller-Applet
mouseclick,left,650, 435, 1, 0 ; tries to click OK
sleep, 50
mouseclick,left,595, 435, 1, 0 ; clicks on box to activate second controller
sleep, 50
mouseclick,left,650, 435, 1, 0 ; tries to click OK again
sleep 5000
} `

**Comment by dennore** [comment]
No i was just to lazy to make it look for the pixel…
If you divide x and y through 2 it should be fine… my dpi scale is 200%

tastyratz ***@***.***> schrieb am Do. 10. Nov. 2022 um 19:20:

**Comment by Hixbot2** [comment]
Hi, this is still a big problem.. why is it closed?  should I start a new request?

**Comment by Pozuelos78** [comment]
Workaround with JoyTokey
assign the keyboard key "Enter" to the guide button on the Xbox 360 controller 1 and 2 (my case) the controls must be previously configured.
When the applet control appears, just press the guide button on control 1 or the guide button on control 2.
I use Yuzu with hyperspin with RocketLauncher

![360_controller](https://user-images.githubusercontent.com/76235602/211986506-db6ab5f3-27ae-4ddb-918e-b2d6cc75ef5a.png)
![1](https://user-images.githubusercontent.com/76235602/211986525-1a382bd3-7544-4b1b-9e1a-e6338af92060.png)
![2](https://user-images.githubusercontent.com/76235602/211986552-4230c90a-6fcc-4c98-a219-7d6b1f392d08.png)
![Sin título3](https://user-images.githubusercontent.com/76235602/211986734-11b75786-edfb-44be-95e3-44a2781132cf.jpg)

**Comment by tastyratz** [comment]
There sure are a lot of custom workarounds in this report by a lot of people who have the same issue for a case that's "closed"

**Comment by FearlessTobi** [comment]
Please refer to this issue that is still open: https://github.com/yuzu-emu/yuzu/issues/8552.

**Comment by DmitryOlenin** [comment]
Btw, I don't know why is this case "closed".
Problem is alive, no solution at all. 
You can use second controller to press keys at start, but it awful.

**Comment by Pozuelos78** [comment]
[#9663](https://github.com/yuzu-emu/yuzu/pull/9663)

**Comment by Kotaghul** [comment]
Here a modified version of dennore script working with yuzu in 2023. It's working in all multiplayers games i tested so far. For those using Launchbox, just copy/paste the script in the "Running script" section of the configuration of Yuzu

while 1 {
winwaitactive, Controller Applet
send {Enter}
sleep 100
send {Space}
sleep 50
send {Enter}
sleep 5000
}

**Comment by 0luc** [comment]
Could be missing something but I modified Kotaghuls script to work with AutoIT. Just compile and go.

CloseControllerPrompt()
	Func CloseControllerPrompt()
		WinWaitActive ("Controller Applet")
		send("{ENTER}")
		sleep(100)
		send("{SPACE}")
		sleep(50)
		send("{Enter}")
		sleep(5000)
	EndFunc

**Comment by MastaG** [comment]
I dont get it..
I'm using Yuzu on the Steam Deck connected to my TV using a dock and 4 Xbox controllers.
I can perfectly configure the controller order using the Steam quick settings menu.

So I only need to press OK everytime the dialog pops up...
Which requires me to painfully navigate the mouse using the Deck's touchscreen.. while the thing is sitting in the Dock...
Why not just disable it and leave it the way it is?

**Comment by FearlessTobi** [comment]
Again, please don't comment on this closed issue but on the open one instead: https://github.com/yuzu-emu/yuzu/issues/8552.
