### ISSUE TITLE
LEGO® Star Wars™ The Skywalker Saga

### ISSUE THREAD

**Issue by jvhellraiser** [yuzu-emu/yuzu#8145]
- You have provided the version (commit hash) of yuzu you are using.
   Yuzu EA 2639

- You have provided sufficient detail for the issue to be reproduced.
loading from Opengl game loads bu has graphical issues/FPS drops to 4 FPS in some scenes/on Vulkan it crashes

- You have provided system specs (if relevant).
windows 11
16 gb of ram
I7 9700k
Nvidia RTX 2060

- Please also provide:
 - For graphical issues, comparison screenshots with real hardware.
 ![Screenshot 2022-04-02 234036](https://user-images.githubusercontent.com/16488761/161410600-212e06e2-49a4-4010-8820-809a4d385bb7.png)

**Comment by goldenx86** [comment]
We won't offer support on piracy or leaked copies.
