### ISSUE TITLE
Graphical bug pokémon shield

### ISSUE THREAD

**Issue by Lithium64** [yuzu-emu/yuzu#8146]
The training court keep flashing and then disappears, on OpenGL this works fine. Tested with RADV and AMD proprietary driver on windows.

Video: https://www.youtube.com/watch?v=AA1ax4o16bw

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8403895/yuzu_log.txt)

**Comment by goldenx86** [comment]
I've seen pre GCN3 hardware do this on RADV. Can you try if AMDVLK is better?

**Comment by Immersion95** [comment]
I'm on WIndows 11 + AMD drivers and same thing happens on Vulkan.

**Comment by goldenx86** [comment]
Then AMDVLK won't help here, D32 is too precise compared to what the game expects.
The proper solution is AMD adding support for D24. Most Switch games use D24 and only AMD refuses to add it.

**Comment by Immersion95** [comment]
It is now solved on latest EA + Windows 11 + AMD :)
