### ISSUE TITLE
Bug Pokemon Sword e Shield Vulkan AMD

### ISSUE THREAD

**Issue by Nextking1986** [yuzu-emu/yuzu#8151]

**Comment by BSoDGamingYT** [comment]
please follow the issue format. Stating which version of the emulator, your system specs and providing a log.

**Comment by Nextking1986** [comment]
Build EA 2642.

**Comment by Nextking1986** [comment]
[   0.283754] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:140: Udp Initialization started
[   0.283768] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:332: Starting communication with UDP input server on 127.0.0.1:26760
[   0.366541] Frontend <Info> yuzu\main.cpp:GMainWindow:244: yuzu Version: yuzu Early Access 2642
[   0.366543] Frontend <Info> yuzu\main.cpp:GMainWindow:259: Host CPU: AMD Ryzen 5 1600 Six-Core Processor             | AVX2 | FMA
[   0.366596] Frontend <Info> yuzu\main.cpp:GMainWindow:261: Host OS: Windows 10 Version 2009
[   0.366620] Frontend <Info> yuzu\main.cpp:GMainWindow:263: Host RAM: 15.94 GiB
[   0.366621] Frontend <Info> yuzu\main.cpp:GMainWindow:264: Host Swap: 19.53 GiB
[   1.912333] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   1.916309] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.4.0) applied successfully
[   1.932280] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.2.0) applied successfully
[   1.934286] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.7.0) applied successfully
[   1.936335] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   1.938638] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   1.942277] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.5.0) applied successfully
[   1.944459] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.3.0) applied successfully
[   1.946468] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.2.0) applied successfully
[   1.959993] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   1.970692] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   1.974215] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.2.0) applied successfully
[   1.979384] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.11.0) applied successfully
[   1.983464] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.2.0) applied successfully
[   1.985499] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.12.0) applied successfully
[   1.987588] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   1.989366] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.5.0) applied successfully
[   1.991404] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.3.0) applied successfully
[   1.993492] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.7.0) applied successfully
[   1.995508] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.5.0) applied successfully
[   1.997496] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.7.0) applied successfully
[   1.999414] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.001292] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.003326] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.005237] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.7.0) applied successfully
[   2.021630] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.045520] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.26.0) applied successfully
[   2.056895] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.3.0) applied successfully
[   2.058821] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.060798] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.072587] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.4.0) applied successfully
[   2.082968] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.0.0) applied successfully
[   2.095039] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.2.0) applied successfully
[   2.100446] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.7.0) applied successfully
[   2.106602] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.112908] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.123624] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.5.0) applied successfully
[   2.130060] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.3.0) applied successfully
[   2.136399] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.2.0) applied successfully
[   2.144517] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.0.0) applied successfully
[   2.153073] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.0.0) applied successfully
[   2.160968] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.182471] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.189675] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.2.0) applied successfully
[   2.199090] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.11.0) applied successfully
[   2.207021] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.2.0) applied successfully
[   2.212662] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.12.0) applied successfully
[   2.218643] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.223604] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.5.0) applied successfully
[   2.228476] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.3.0) applied successfully
[   2.234827] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.7.0) applied successfully
[   2.240226] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.5.0) applied successfully
[   2.246073] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.7.0) applied successfully
[   2.251964] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.258284] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.262977] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.267300] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.7.0) applied successfully
[   2.278210] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.0.0) applied successfully
[   2.290945] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully
[   2.332258] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.26.0) applied successfully
[   2.339228] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.0.0) applied successfully
[   2.355218] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.3.0) applied successfully
[   2.361768] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.1.0) applied successfully

**Comment by Nextking1986** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8411459/yuzu_log.txt)

**Comment by Nextking1986** [comment]
> please follow the issue format. Stating which version of the emulator, your system specs and providing a log.

I have already added the data requested above.
