### ISSUE TITLE
Dragon Quest Builders 2 : control problem since 973

### ISSUE THREAD

**Issue by flogal** [yuzu-emu/yuzu#8155]
Hello, since the 973 version, Dragon Quest Builders 2 is unplayable, because the left and right sticks are not working properly. I tested a few other games and they are not impacted.
In this game, the hero runs in circle and camera is turning around indefinitely, both sticks are acting like they were full left. When i push the stick full right, the hero and the camera stop moving, and it's impossible to go right or to turn the camera to the right.

**Comment by german77** [comment]
Confirmed. I'm working on a fix
