### ISSUE TITLE
Doom 64 Load Error

### ISSUE THREAD

**Issue by BoomyTrevor101** [yuzu-emu/yuzu#8163]
When trying to load DOOM 64 get and Error and just stays on switch loading screen.

Log: 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8426987/yuzu_log.txt)

Build 975 "I think that what your asking for. Idk when I open yuzu it has yuzu 975 on the top left."

Specs: 
NVIDIA GeForce RTX 2070 Super, 32gb of ram and Intel Core i7-10700 2.90hz

Sorry first time posting something like this so Idk what I'm doing but I hope this helps

**Comment by german77** [comment]
Your file is corrupted. Dump a newer one along with the keys
