### ISSUE TITLE
Yuzu EA 2641 and above - broke UI fix in Rune Factory 5

### ISSUE THREAD

**Issue by Avrution** [yuzu-emu/yuzu#8166]
Bad title, sorry.

Most know about the UI bug in RF5 that is fixed by setting the GPU to Extreme.  

EA build 2615 fixed that problem in both OGL and Vulkan where you could run in Normal GPU mode without issue.  

As of build 2641 things still worked, but build 2642 broke the UI again - as well as all builds since.

I've been hoping for the game for work better with Vulkan, so test most builds.  Not sure what changed between 41 and 42, but it was enough to screw up the game.

**Comment by Hikari753** [comment]
Thanks for sharing this information!

UI and light issues seem not happening in build 2641, but not the skirt bug.

The one solution I know to fix the skirt bug is to change CPU to accurate and it really drops a lot FPS.

**Comment by gidoly** [comment]
should addressed with yfc 1
