### ISSUE TITLE
Corrupted "nested" hooks in Skyline plugins

### ISSUE THREAD

**Issue by tech-ticks** [yuzu-emu/yuzu#8174]
Related to #7392

The Skyline modding framework allows loading plugin NROs that can register dynamic hooks. The NROs load fine, but hooks get corrupted if the following sequence occurs (the error can probably also reproduced in other ways):
1. Skyline loads the plugin NRO after the game mounts the romfs and executes the plugin's main entrypoint function
2. The plugin hooks a function from the main executable (in the attached example, it's a function that is executed every frame)
3. *Inside* that hook, another hook is registered, this time for a function in the SDK

Code of the Skyline plugin (`libyuzu_repro.nro`): https://github.com/tech-ticks/skyline_yuzu_repro_plugin/blob/main/src/lib.rs

## Expected behaviour

The plugin registers a hook to `nn::fs::OpenFile` that logs every accessed file and then calls the original function. The log output on console looks like this:

```
...
[PluginManager] Loading plugins...
[PluginManager] Loaded 'rom:/skyline/plugins/libyuzu_repro.nro'
[PluginManager] Running `main` for rom:/skyline/plugins/libyuzu_repro.nro
[repro_plugin] main() in yuzu repro plugin. Installing hook for game function 0x182050 (GroundManager_Update)..
[PluginManager] Finished running `main` for 'rom:/skyline/plugins/libyuzu_repro.nro' (0x0)
[skyline_main] loaded plugins
[repro_plugin] Inside GroundManager_Update, installing hook for SDK function 'nn::fs::OpenFile'

-- Yuzu prints the same lines until here --

[repro_plugin] !!! nn::fs::OpenFile called with path rom:/Data/Resources/unity_builtin_extra
[repro_plugin] !!! nn::fs::OpenFile called with path rom:/Data/Resources/unity default resources
[repro_plugin] !!! nn::fs::OpenFile called with path rom:/Data/resources.assets.resS
...
```

## Actual behaviour

The hook that is supposed to log file access is broken on Yuzu. On my machine, one of two things happen at random:
- The game hangs during startup
- The game loads, but the hook is never called. The original `nn::fs::OpenFile` seems to be called instead, no logs show up.

## Reproduction steps

Yuzu build: `master-2db5076ec`

Copy this folder to `$appdata/yuzu/load/01003D200BAA2000`:
[skyline_plugin_hook_repro.zip](https://github.com/yuzu-emu/yuzu/files/8453791/skyline_plugin_hook_repro.zip)

and run **Pokèmon Mystery Dungeon Rescue Team DX** (version **1.0.2**). An offset that depends on this version is used, so it won't work with other game versions.

## Other Resources

Yuzu log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8453674/yuzu_log.txt)
Skyline branch of the included build (uses `svcOutputDebugString` instead of TCP logging): https://github.com/tech-ticks/skyline/tree/yuzu-repro

**Comment by merryhime** [comment]
Does A64HookFunction call invalidate code cache as required? (Can't find a source for this.)

**Comment by tech-ticks** [comment]
@merryhime It does, I think `svcUnmapCodeMemory` should implicitly invalidate icache too (though I‘m not sure if that‘s implemented correctly in Yuzu) https://github.com/skyline-dev/skyline/blob/e831ae3899268a54ae7abbb112f40b9022e4a89e/source/skyline/inlinehook/controlledpages.cpp#L149
