### ISSUE TITLE
Bug Atelier Sophie 2

### ISSUE THREAD

**Issue by Nextking1986** [yuzu-emu/yuzu#8175]
the game starts but stays on black screen. Needs repair.

Build EA: 2663

Hardware: RADEON RX 560 OC 4GB; 16GB DE RAM; RYZEN 5 1600
Driver: 22.4.1

![Sem título](https://user-images.githubusercontent.com/102981461/162507890-635c76d0-1dab-4d79-b8e2-7ddba2afad09.png)

**Comment by german77** [comment]
Please provide a log file
