### ISSUE TITLE
Black screen when entering the menu interface of DragonBall Xenoverse 2

### ISSUE THREAD

**Issue by CyangYu** [yuzu-emu/yuzu#8181]
The latest version. After the video is played, the menu screen is black. But the Ryujinx emulator can show it.
Key log information is as follows:
[ 232.430334] Debug <Critical> video_core\engines\maxwell_dma.cpp:operator ():58: Assertion Failed!
[ 232.430335] Debug <Critical> video_core\engines\maxwell_dma.cpp:operator ():59: Assertion Failed!
[ 232.430342] Debug <Critical> video_core\memory_manager.cpp:operator ():210: Unreachable code!

**Comment by G-Spawn** [comment]
Upload the log file in full please.

**Comment by CyangYu** [comment]
[Uploading yuzu_log.txt…]()

**Comment by CyangYu** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8459172/yuzu_log.txt)
