### ISSUE TITLE
Animal Crossing New Horizons LayeredFS mods doesn't load

### ISSUE THREAD

**Issue by FensBK** [yuzu-emu/yuzu#8184]
The game doesn't boot if any LayeredFS mod is installed.

Specs:
Intel Core i5-7300HQ
8GB RAM
256GB SSD 
Windows 11

**Comment by RinMaru** [comment]
#5918 dupe

**Comment by G-Spawn** [comment]
> #5918 dupe

Closing in favour of issue above. This will be improved someday when we work on the filesystem of yuzu.
