### ISSUE TITLE
Crash when taking screenshot to folder without Windows permissions

### ISSUE THREAD

**Issue by OmegaNemesis28** [yuzu-emu/yuzu#8186]
Yuzu mainline 979
Windows 10 Pro 21H2 x64

Simply put, if the directory under Settings -> General -> UI -> Screenshots path is a folder that the current Windows user does not have permissions to write to, Yuzu crashes upon taking a screenshot.

I had set up Yuzu using a different Windows user, and upon switching users, I realized I had not set yuzu to use a shared folder path between the users. It was set to C:\Users\User1\... while I was logged into User 2.

Simple fix on my side to switch the folder and no longer crash on screenshots, but wanted to report the crash.

**Comment by german77** [comment]
I can't make it crash. The dialog offers me a new location if the folder is not read/writable and if it fails it just prints an error to the log.

**Comment by OmegaNemesis28** [comment]
The dialog to select a folder is what says it's not read/writable right? But if the folder is already set that you had access to, and you later lose access to it (either the folder has permissions set after or you switch users on a folder that the previous user had set), then it will crash on screenshot. I was able to reproduce by setting `Screenshots\screenshot_path=` as well


[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8460117/yuzu_log.txt)

Here's a log if it helps

**Comment by german77** [comment]
I couldn't make it crash as you described but I found one way to make it crash. Solved here #8192 please test and see if it still happens

**Comment by gidoly** [comment]
is it adressed?

**Comment by gidoly** [comment]
closes due to fix pr made but reporter had no response for month
