### ISSUE TITLE
[Audio] Deadly Eating Adventure Meshi | no sound

### ISSUE THREAD

**Issue by rolmerin** [yuzu-emu/yuzu#8187]
Game Title:Deadly Eating Adventure Meshi (屍喰らいの冒険メシ)
![1](https://user-images.githubusercontent.com/88316690/162615890-c438b870-8ec0-44cc-893a-09c481d4ea00.jpg)

Game runs fine,but no sound.

[   4.135598] Audio <Error> audio_core\info_updater.cpp:CheckConsumedSize:487: Output is not consumed! Consumed 82736, but requires 84784. 2048 bytes remaining
[   4.135601] Audio <Error> audio_core\audio_renderer.cpp:UpdateAudioRenderer:208: Audio buffers were not consumed!

Spec:
R5 5600X
AMD RX590
Windows 11

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8458853/yuzu_log.txt)

**Comment by german77** [comment]
#7972

**Comment by benderscruffy** [comment]
this has been fixed
please close
