### ISSUE TITLE
Breath of the Wild: Hero's Path doesn't render in Vulkan

### ISSUE THREAD

**Issue by goldenx86** [yuzu-emu/yuzu#8189]
Mainline 980. 

Play for a while, open the map and check the Hero's Journey path, it will only render correctly when zoomed out. 
Affects both Turing and RDNA2 hardware, and the issue seems to be there since ever, I couldn't find a mainline build that started it.

![01007ef00011e000_2022-04-10_16-13-56-608](https://user-images.githubusercontent.com/42481638/162636225-dad6061d-85e0-4dce-bee2-5ef1b4865f55.jpg)

![01007ef00011e000_2022-04-10_16-14-01-432](https://user-images.githubusercontent.com/42481638/162636234-98cb2ca9-a075-4376-89f2-de145de0bd83.jpg)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8459743/yuzu_log.txt)

**Comment by dml360** [comment]
The tracing does not render when zooming, to help understand this problem I made a video and posted it, here is the link

https://youtu.be/boSiiNDjyQY

**Comment by gidoly** [comment]
fixed with vulkan topology pr
