### ISSUE TITLE
Skyline fails to load plugins properly

### ISSUE THREAD

**Issue by Struggleton** [yuzu-emu/yuzu#8200]
On Yuzu, early access (**v2672, current latest, and Super Smash Bros. Ultimate with all character DLCs + update v13.0.1**), when loading [Training Modpack](https://github.com/jugeeya/UltimateTrainingModpack) (A plugin for Super Smash Bros. Ultimate implementing new features to the Training Mode of the game) from SDMC along with Skyline, the emulator boots into the game and plays like normal until you try to load a fight in Training mode where the game hangs and displays 0 FPS on the FPS counter.

Steps to reproduce:
- Download [SkylineTrainingModRepro.zip](https://github.com/yuzu-emu/yuzu/files/8478326/SkylineTrainingModRepro.zip)
- Extract the folders + file into **%appdata%/yuzu/sdmc**
- Enable SDMC from the Properties > Add-Ons list for Super Smash Bros. Ultimate and load the game
- Navigate to Training Mode (Games and More > Training > any stage + character combination) and start a game. The emulator should hang.

A similar situation happens when using another plugin for Smash, [Arcropolis](https://github.com/Raytwo/ARCropolis) (a file replacement and addition loader.) The game hangs on the shader loading screen and closing the emulator through the exit button or File > Exit seems to leave the emulator process behind in Task Manager.

Repro steps for Arcropolis hang
- Download [SkylineArcropolisRepro.zip](https://github.com/yuzu-emu/yuzu/files/8478359/SkylineArcropolisRepro.zip)
- Extract the folders + file into **%appdata%/yuzu/sdmc**
- Enable SDMC from the Properties > Add-Ons list for Super Smash Bros. Ultimate and load the game. The emulator should hang on the shader loading screen.

Specs for this setup are:
- RTX 2060 @ 6GB of VRAM
- Ryzen 5 3600XT 
- 16 GB of RAM @ 3000mhz
- 45 GB page file

Logs are attached for both plugin hangs:
- [yuzu_log_skyline_arcropolis.txt](https://github.com/yuzu-emu/yuzu/files/8478375/yuzu_log_skyline_arcropolis.txt)
- [yuzu_log_skyline_trainingmod.txt](https://github.com/yuzu-emu/yuzu/files/8478376/yuzu_log_skyline_trainingmod.txt)

**Comment by TheHomerOfSteel** [comment]
Does other mods work with arcropolis ?

**Comment by liamwhite** [comment]
Fixed by #11326, it is a bug in skyline
