### ISSUE TITLE
bug pokemon sword

### ISSUE THREAD

**Issue by paf2014** [yuzu-emu/yuzu#8203]
In both versions Early Access 2673 or 983 whenever I put a wishing pierce in dens from pokemon sword and shield before saving the game crashes if the option: multicore cpu emultion is enabled in Api vulcan or openGL.If I disable the option: multicore cpu emultion, the game won't boot. is there any solution for this?

**Comment by G-Spawn** [comment]
provide a log file and ideally ask for support on discord.

**Comment by paf2014** [comment]
There is not a log file just the game crashes in the situation I explained
above

Em qua., 13 de abr. de 2022 20:36, Ghost ***@***.***>
escreveu:

**Comment by G-Spawn** [comment]
https://discord.gg/u77vRWY Ask for help on here. Yes there is a log file if the game crashes, you just have to know where to look ( %appdata%\yuzu\log\ )

**Comment by G-Spawn** [comment]
Feel free to reopen issue when you can provide a log & if it still persists.
