### ISSUE TITLE
Smash Ultimate knockback effect in the wrong place/flashing/stretching

### ISSUE THREAD

**Issue by TheHammerSSBU** [yuzu-emu/yuzu#8209]
Texture flashing stretching and a bit when I launch with forward air,
https://user-images.githubusercontent.com/103712865/163510734-a17d62fc-1f51-4b6c-b47f-cd7b1ecbb9eb.mp4

Texture appears a few units away from where it's supposed to be
https://user-images.githubusercontent.com/103712865/163511581-373d65ff-40a9-4b85-b2a3-46fd770b9ea4.mp4

I'm new here so I'm not sure what to write
PC Specs : 
I7 6700
GT 1030 DDR5
16GB DDR4 RAM
2TB External HDD

**Comment by CrusadingNinja** [comment]
@TheHammerSSBU As stated in the issue template, please upload a log file for issues. Otherwise, your report will likely be ignored.

**Comment by alexgbor** [comment]
I have the same issue after a few games. Logs:
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/8513929/yuzu_log.txt.old.txt)

**Comment by G-Spawn** [comment]
> @TheHammerSSBU As stated in the issue template, please upload a log file for issues. Otherwise, your report will likely be ignored.

^ Feel free to reopen when you can provide a log file. https://yuzu-emu.org/help/reference/log-files/
