### ISSUE TITLE
Regression: Super Mario Galaxy cannot be progressed past the first cutscene

### ISSUE THREAD

**Issue by liamwhite** [yuzu-emu/yuzu#8211]
Caused by #8148, @merryhime

The game has significant audio glitches in the FMV and now softlocks at the end of the first video after this PR. No relevant console output is logged. Guest stack traces also produce no useful output.

**Comment by liamwhite** [comment]
A lot of investigation later has shown that this is an honest to goodness game bug. The game is able to cope with receiving an interrupt when executing code in MainThread inside three specific basic blocks, starting at the following addresses:
- `main+0x15b1c`
- `main+0x8bc2c` (this is the entrypoint)
- `main+0x1ab248`

By using Atmosphere's dmnt.gen2 sysmodule to place breakpoints at `main+0x8bc2c`, yuzu's strange behavior can be observed on the actual console as well:

https://user-images.githubusercontent.com/9658600/178571225-86d4e7fa-9df1-4d57-b6a0-168f44a02b52.mp4

https://user-images.githubusercontent.com/9658600/178571240-879a6263-c9fa-4467-8623-79882e6eb42a.mp4

Previously, no interrupt was taken in any of these blocks, because Dynarmic would attempt to run for a minimum amount of cycles on entry before checking for halt again. Now interrupt is checked on the end of all basic blocks.

The interrupt that causes MainThread to get preempted in this case is a VI from SurfaceFlinger. The reason this does not manifest on the console is probably that this block of code executes quickly enough to avoid being interrupted by SurfaceFlinger.

I have yet to confirm whether this is the root cause, but on yuzu, these basic blocks are recompiled when entering a video cutscene, and this might be introducing a substantial enough delay to cause the interrupt to fire at an inopportune moment. Given that the bug is particularly more likely to appear when running with the framerate unlocked in yuzu, that is my best guess as to what's happening.

@merryhime

**Comment by xordspar0** [comment]
Mario Galaxy can't progress past the first cutscene again as of Yuzu 1680.
