### ISSUE TITLE
Crash Team Racing - graphical glitches when using Vulkan

### ISSUE THREAD

**Issue by duke912** [yuzu-emu/yuzu#8215]
When playing CTR nitro fueled under vulkan api, most characters and kart becomes glitched (characters and karts becomes huge and all over the place), doesn't happen in ogl, but ogl seems to have  a memory leak issue.

Tested on latest early acces version.

**Comment by PrinceBubloo** [comment]
Log

**Comment by duke912** [comment]
![001](https://user-images.githubusercontent.com/62965569/163653739-0fd081b9-4b16-4fde-b623-123daebd3480.png)


[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8498950/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Sadly this issue is expected atm on your generation of gpu. We're looking into it.

**Comment by rakantoh** [comment]
i have the same issue, it's only with this game, with or without update, dlc and/or 60fps mod, and in ogl the 60fps mod affects the sound...

**Comment by G-Spawn** [comment]
1k series nvidia gpu or 'pascal'

**Comment by zerr10** [comment]
same bug here space:

i7 6700 3.4 Ghz DDR4 8GB 2133 Mhz dual channel Card : GTX 1070 8GB

**Comment by rakantoh** [comment]
i think that is a bug in the emulator code specifically with this game, if the bug is only in nvidia 1000 series in vulkan, then all games in vulkan are glitched, but is only with ctr nf.

**Comment by G-Spawn** [comment]
Indeed it is specific to this game. I can't recall any other titles that are afflicted like this.

**Comment by pepodmc3** [comment]
I have the same problem with a geforce 750 ti 2gb, so its not an nvidia 1000 series bug only

**Comment by pepodmc3** [comment]
> 1k series nvidia gpu or 'pascal'

I have the same problem with a geforce 750 ti 2gb, so its not an nvidia 1000 series bug only

**Comment by EslamHULK** [comment]
![Screenshot 2023-08-01 185701](https://github.com/yuzu-emu/yuzu/assets/35035933/60a1cb9a-11b6-426a-8f39-7153b1de0dbe)
latest version of YUZU  Vulkan not working in crash team racing
![Screenshot 2023-08-01 185837](https://github.com/yuzu-emu/yuzu/assets/35035933/edf17767-0a1c-4be0-9e08-97de6f1f99a0)
latest version of YUZU  Vulkan not working in crash team racing
   
but in old version look it work
![Screenshot 2023-08-01 010004](https://github.com/yuzu-emu/yuzu/assets/35035933/4107d8d1-d7bc-48b9-8a31-bb4bb01f54af)
![Screenshot 2023-08-01 011442](https://github.com/yuzu-emu/yuzu/assets/35035933/f6e7defd-a419-4b10-a63b-ad07510a6127)

 can fix it soon , and thank u

**Comment by cjunisl** [comment]
The last PR didn't solve the problem.

**Comment by cjunisl** [comment]
Yuzu EA 3940 - GTX 1050

![ctr ea 3940](https://github.com/yuzu-emu/yuzu/assets/57728845/85f63ef5-0092-4ad3-8d8c-98ca686dc523)
