### ISSUE TITLE
GPL version clarification

### ISSUE THREAD

**Issue by bgermann** [yuzu-emu/yuzu#8218]
Lately you changed the project's license to GPLv3+. src/yuzu/aboutdialog.ui and the translation files still say it is GPLv2.0. Please update those references.

**Comment by Docteh** [comment]
I did a CTRL+F on the translation files, and I guess you're referring to the translations of the about dialog?

If this is what you're referring to, changing the aboutdialog.ui file will disconnect those translations. 

Please correct me if I'm wrong.
