### ISSUE TITLE
Skyline Emulator license exception is problematic

### ISSUE THREAD

**Issue by bgermann** [yuzu-emu/yuzu#8219]
@Tachi107 is developing a package for inclusion in Debian, which I am currently reviewing.

There is one license condition that is fishy. You introduced it with e6a0ca5f2c0597d0f8a4300464ae7e8db244f097.
I think that this exemption is not thought to discriminate against the Skyline-Emulator Team but rather to grant them the additional MPL license. However, it reads as though you do not want them to be able to use the project under GPL, which would contradict the GPL.

Please do not use a GPL exception for this but rather grant the team the additional rights under MPL.
With that exception the project is unfit for Debian inclusion.

**Comment by bylaws** [comment]
Lmao thinking about it this probably even contradicts the MPL too since it's GPL compatible and this would add extra restrictions... Licenses are funny sometimes

**Comment by Tachi107** [comment]
@bgermann do you think that this would be more clear?

`The Skyline-Emulator Team may choose to use the code from these contributors under the GPL-3.0-or-later OR MPL-2.0: FernandoS27, lioncash, bunnei, ReinUsesLisp, Morph1984, ogniK5377, german77, ameerj, Kelebek1 and lat9nq`

I've used an SPDX expression to avoid potential ambiguities

**Comment by bgermann** [comment]
Yes, that is okay. Thanks.
