### ISSUE TITLE
Xenoblade Chonicles 2 cutscene chrash 

### ISSUE THREAD

**Issue by KevinGandler** [yuzu-emu/yuzu#8221]
The game crashes after this and the following cutscene.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8502372/yuzu_log.txt)

Video: https://youtu.be/XULxRVSzGt0

**Comment by G-Spawn** [comment]
Please try disabling all mods and try again.

**Comment by KevinGandler** [comment]
Does it make a difference if I have a new graphics card? I Upgraded from the GTX 1060 6GB to the RTX 3070Ti over this time.

**Comment by G-Spawn** [comment]
If it still happens sure you can keep issue open. If it doesnt happen anymore you can close
