### ISSUE TITLE
Steamdeck Crash when launched from game mode

### ISSUE THREAD

**Issue by Qowy** [yuzu-emu/yuzu#8226]
Hi,
running yuzu from Desktop mode works fine.

But when I try launching it from GameMode (which uses Wayland and Gamescope afaik) it crashes after the Loading screen

Log: https://pastebin.com/raw/0MwAqWUa

**Comment by PrinceBubloo** [comment]
Check if 8228 fixed it

**Comment by Qowy** [comment]
is 8228 already part of a released binary?

**Comment by Qowy** [comment]
Mainline Appimage 1417 seems to work
