### ISSUE TITLE
Yuzu crashes when The Legend of Zelda: Breath of the Wild launched in vulcan mode

### ISSUE THREAD

**Issue by evilrussian** [yuzu-emu/yuzu#8227]
App closing without error when im trying to run The Legend of Zelda: Breath of the Wild in vulcan mode
I'd tried to run game with updates and without it.

windows 10
yuzu 990
GTX 1060 6Gb
nvidia driver 512.15
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8514915/yuzu_log.txt)

**Comment by Docteh** [comment]
Looks like it got stuck making pipelines? I just tried BOTW 1.0.0 on the same GPU driver and Yuzu version, that said it was a fresh start of the game

My GTX1080 only made 10 pipelines. 

[  47.396226] Frontend <Info> yuzu\main.cpp:BootGame:1486: Booting game: 01007EF00011E000 | The Legend of Zelda: Breath of the Wild (64-bit) | 1.0.0
[  47.409289] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateComputePipeline:614: 0x4ad1427eb2941e96
[  47.410234] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateComputePipeline:614: 0x9449147cc25aa5b5
[  47.410516] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateComputePipeline:614: 0x94c6c3fb4bb4036b
[  47.412564] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateComputePipeline:614: 0x75dcb2691b20d5a1
[  47.412574] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateComputePipeline:614: 0xf52c1c78e3749eb8
[  47.412782] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateComputePipeline:614: 0xf049b1c0a2afb7ed
[  47.413776] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateComputePipeline:614: 0x8b2e5195407598b3
[  47.423197] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:LoadDiskResources:449: Total Pipeline Count: 10
[  47.705429] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateComputePipeline:614: 0xaf0d5a62767030f5
[  47.705434] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateComputePipeline:614: 0x797495a2ac608770
[  47.709218] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateComputePipeline:614: 0xd014ebe6b65f22b4

**Comment by dennajort** [comment]
@evilrussian usually when my game crash on startup, I remove all pipeline cache and it works again. Maybe you can try that.

**Comment by G-Spawn** [comment]
Please reopen issue if this happens to you on latest yuzu mainline @evilrussian
