### ISSUE TITLE
Cruisin' Blast - Vulkan crashes on multiple PC's

### ISSUE THREAD

**Issue by tapperp** [yuzu-emu/yuzu#8230]
------------------------------------

UPDATE: it was nvidia drivers. 

Game runs with Vulkan in latest Yuzu under old driver 472.12. But using new driver 512.15 it will crash.

This has also been confirmed by GG-Ghost on Yuzu discord.

------------------------------------
------------------------
Original post follows:
------------------------
Cruisin' Blast has been crashing on the past several builds of Yuzu I tried when using Vulkan. The game will start loading, i.e. you'll see the spinning wheel animations etc., and then Yuzu will hard crash and close. Tested on 2 different computers using Nvidia cards (1060 laptop and 1080 desktop) with same result. 

Please see attached log. Thank you.

[yuzu_log_cruisin_blast_vulkan_crash.txt](https://github.com/yuzu-emu/yuzu/files/8525942/yuzu_log_cruisin_blast_vulkan_crash.txt)

**Comment by PrinceBubloo** [comment]
It use to run on vulcan,
Can you find out the last working version.

Also @german77

**Comment by legend800** [comment]
It's been like that from the start. I had to clear my cache and now VK works for me. Only started working in the past month or so. Before it would always crash there no matter what.I think it's a shader compiler related issue with that backend. 

I've played the game for hours and had zero issues with rumbler.

**Comment by tapperp** [comment]
I just cleared all shader cache and the results are the same. Yuzu completely crashes and closes after the spinning wheel graphics. 

Log contains the following at the end before the crash:

> [  52.942597] HW.GPU <Warning> video_core/texture_cache/texture_cache.h:RefreshContents:703: MSAA image uploads are not implemented
[  52.942603] HW.GPU <Warning> video_core/texture_cache/texture_cache.h:JoinImages:1085: Copying between images with different samples is not implemented
[  52.984712] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_ctrl.cpp:IocCtrlClearEventWait:209: cleared event wait on, event_id: 0
[  53.087718] HW.GPU <Warning> video_core/texture_cache/texture_cache.h:RefreshContents:703: MSAA image uploads are not implemented
[  53.089746] Render.Vulkan <Critical> video_core\vulkan_common\vulkan_device.cpp:ReportLoss:751: Device loss occurred!

Attached is the full log.

[yuzu_log_cruisin_blast_vulkan_after_clearing_shader_cache.txt](https://github.com/yuzu-emu/yuzu/files/8534262/yuzu_log_cruisin_blast_vulkan_after_clearing_shader_cache.txt)
.

**Comment by tapperp** [comment]
I can confirm it seems to be related to nvidia drivers.

I was using latest nvidia driver 512.15.

Just now I reverted back to 472.12, and Cruis'n Blast is running OK in latest Yuzu builds with Vulkan backend.

Bad part is I prefer to keep my video drivers up to date for normal PC gaming.

**Comment by benderscruffy** [comment]
is this still an issue ???

**Comment by legend800** [comment]
It's fine on Vulkan now

**Comment by benderscruffy** [comment]
can be closed
