### ISSUE TITLE
Parameter to use specific profile doesn't work

### ISSUE THREAD

**Issue by Anabas27** [yuzu-emu/yuzu#8235]
Hello, first of all thanks to everybody working on this project, you're amazing!

I'm having a problem with a feature to use specific profile via parameter. -u isn't working. 
I've tried everything
- inputting my exact profile name after -u 
- inputting profile numbers after -u

It seems like it broke in one of the merges. I'm using Yuzu Early Access 2690

[Here's the link to the feature](https://github.com/yuzu-emu/yuzu/pull/6116)

**Comment by german77** [comment]
Can you share the command you are using. Just to discard bad formatting

**Comment by Anabas27** [comment]
> Can you share the command you are using. Just to discard bad formatting

Sure! I have three profiles setup User1, User2, User3

Since i couldn’t figure out the formatting for -u parameter i’ve tried all the combinations i could come up with:

yuzu.exe -f -u User2 -g “Path”
yuzu.exe -f -u 2 -g “Path”
yuzu.exe -f -u “User2” -g “Path”

**Comment by german77** [comment]
Second one should work. take into account first profile is 0

**Comment by Anabas27** [comment]
> Second one should work. take into account first profile is 0

Yep, It **does work**. Guess I had trouble with formatting. Thank you and sorry for inconvenience!
