### ISSUE TITLE
GPL-2.0-only files (license incompatibility)

### ISSUE THREAD

**Issue by bgermann** [yuzu-emu/yuzu#8242]
There are still some GPL-2.0-only files in the project, copyright by Atmosphère-NX:

           src/common/bit_set.h
           src/core/file_sys/fsmitm_romfsbuild.cpp
           src/core/file_sys/fsmitm_romfsbuild.h
           src/core/memory/dmnt_cheat_types.h
           src/core/memory/dmnt_cheat_vm.cpp
           src/core/memory/dmnt_cheat_vm.h

**Comment by bgermann** [comment]
You can ask upstream if it would be okay to license them as GPL-2.0-or-later.

**Comment by Docteh** [comment]
Asking upstream appears to be unnecessary 

https://github.com/Atmosphere-NX/Atmosphere

The [yuzu Nintendo Switch emulator](https://github.com/yuzu-emu/yuzu) and the [Ryujinx Team and Contributors](https://github.com/orgs/Ryujinx) are exempt from GPLv2 licensing. They are permitted, each at their individual discretion, to instead license any source code authored for the Atmosphère project as either GPLv2 or later or the [MIT license](https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/licensing_exemptions/MIT_LICENSE). In doing so, they may alter, supplement, or entirely remove the copyright notice for each file they choose to relicense. Neither the Atmosphère project nor its individual contributors shall assert their moral rights against any of the aforementioned projects.
