### ISSUE TITLE
Convert source file copyright comments over to SPDX

### ISSUE THREAD

**Issue by lioncash** [yuzu-emu/yuzu#8244]
A good first issue for anyone looking to contribute to yuzu, considering this is mostly a find-replace operation.

At the top of several of our C++ source and header files, we have a comment that looks like so:

```cpp
// Copyright [year] yuzu emulator team
// Licensed under GPLv2 or any later version
// Refer to the license.txt file included.
```

e.g.

```cpp
// Copyright 2018 yuzu emulator team
// Licensed under GPLv2 or any later version
// Refer to the license.txt file included.
```

The problem here is, since we relicensed, these comments are no longer accurate. Since they would all need to be changed anyway, this would be a good time to use [SPDX](https://spdx.dev), a standardized way to communicate licensing information (which would make doing find/replaces nicer in the future if we ever need to do that again).

So, the above comment corrected for our current license would look like:

```cpp
// Copyright 2018 yuzu emulator team
// SPDX-License-Identifier: GPL-3.0-or-later
```

One nice thing being we don't need 3 lines, just two.

Note that the year should be left as is. It establishes the creation year, not a "last updated" year.

**Comment by bgermann** [comment]
The individual files can be left at GPL-2.0-or-later. The combination with the Apache 2.0 licensed files or a GPL-3.0-or-later file makes the project as a whole GPL-3.0-or-later.

When you consider SPDX, the copyright line should also be changed. There is the SPDX-FileCopyrightText verb for it.

**Comment by lioncash** [comment]
Ah cool, I didn't know about `SPDX-FileCopyrightText`
