### ISSUE TITLE
"Danganronpa V3: Killing Harmony" launching problem.

### ISSUE THREAD

**Issue by IrisImmortal** [yuzu-emu/yuzu#8248]
I downloaded **all parts** of "Danganronpa V3: Killing Harmony" from a website called **"MK Production"**. Then I **extracted** them and **put them in one file** like this:

![Picture Nr  1](https://user-images.githubusercontent.com/95183270/164915679-16783d82-32ae-4526-ae02-abaf5287df72.png)

I tried to **launch** it, **but an error came up**:

![Picture Nr  3](https://user-images.githubusercontent.com/95183270/164915692-6e8e3fe3-9a8c-44f4-9d3f-9a7c8ebdfd62.png)

Then I **put all of the parts in part one** like this:

![Picture Nr  2](https://user-images.githubusercontent.com/95183270/164915706-848d1afa-c065-48ee-9203-5606979722e8.png)

**Launched** it again, and the **same error came up**.

Can you please tell me what is wrong or what am I doing wrong because I really want to play this game?

P.S. The highlighted words might be important, so that is why I highlighted them.

**Comment by FernandoS27** [comment]
Please read our rules. No piracy.
