### ISSUE TITLE
Please add Xbox support using ANGLE

### ISSUE THREAD

**Issue by nomaE12** [yuzu-emu/yuzu#8258]
Please add support for the Xbox dev mode by using [ANGLE](https://github.com/google/angle). Retroarch all ready has[ OpenGL support](https://www.youtube.com/watch?v=BLg57Sa0aMc) with ANGLE.

**Comment by goldenx86** [comment]
ANGLE is for OpenGL ES, not for full OpenGL 4.6 Compatibility Profile.
