### ISSUE TITLE
Feature Request - Keep Controllers Connected

### ISSUE THREAD

**Issue by Eksno** [yuzu-emu/yuzu#8276]
# Feature:
An optional selection box that keeps a certain number of controllers always connected or reconnects them automatically when disconnected through a button in the game.

# Reason:
The reason I am asking for this is that when I play SSBU with friends and one of us has to go for a moment, we usually disconnect using the in-game disconnect button. This also disconnects the controller from yuzu which means we have to go into the yuzu config and reconnect whenever they come back.

It would be really handy if this reconnection was automatic so that the person only has to touch the controller again to reconnect.

**Comment by benderscruffy** [comment]
Can be closed
