### ISSUE TITLE
Yomawari 3 (夜廻三) has no sound

### ISSUE THREAD

**Issue by Frederisk** [yuzu-emu/yuzu#8278]
## Game Info

- Name: 夜廻三
- Version: 1.00
- Game ID: 0100F47016F26000
- Type: NSP

## Yuzu Info

- Version: yuzu 998 (2022-04-27)

## Description

The game has no sound at all, after entering the game. However, the display of the game looks normal.

I tried changing the sound engine, the sound channel, and even graphics, but that didn't work.

In other games, everything works fine.

## Log

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8581596/yuzu_log.txt)

**Comment by german77** [comment]
another one to the list #7972
