### ISSUE TITLE
Puyo Puyo™ Tetris® 2 Freezing Randomly 

### ISSUE THREAD

**Issue by dunia01** [yuzu-emu/yuzu#8279]
**Client Version:**
Yuzu Public Client 851 / 960 / 998~1021

**Operating System:**
Windows 10

**Game:**
Puyo Puyo™ Tetris® 2 [010038E011940000]
(Game Version 1.3.2 with DLC Version 1)

**Issue:**
I've been having constant problems with the game freezing randomly, with no certain way to replicate it.

The video output freezes and the audio output keeps playing the background sound of the game if any was playing before the freeze. If I change to Windowed or Fullscreen after the freeze, the screen becomes pure white. This happens on both Vulkan and OpenGL.

.ĢG-No-Re#6685 on Discord suggested that I created an issue here.

**Logs:**
[puyo2_yuzu_log_Vulkan.txt](https://github.com/yuzu-emu/yuzu/files/8582670/yuzu_log.txt)
[puyo2_yuzu_log_OpenGL1.txt](https://github.com/yuzu-emu/yuzu/files/8694449/puyo2_yuzu_log_OpenGL2.txt)
[puyo2_yuzu_log_OpenGL2.txt](https://github.com/yuzu-emu/yuzu/files/8694457/puyo2_yuzu_log_OpenGL3.txt)
[puyo2_yuzu_log_OpenGL3.txt](https://github.com/yuzu-emu/yuzu/files/8694476/puyo2_yuzu_log_OpenGL4.txt)
[puyo2_yuzu_log_OpenGL4.txt](https://github.com/yuzu-emu/yuzu/files/8728467/puyo2_yuzu_log_OpenGL4.txt)

Aside from that, a premonition that the game can possibly freeze after a long time running normally is that letters start to disappear, as seen on the screenshot. This can happen on every menu, I think.

![010038e011940000_2022-04-28_10-35-03-743](https://user-images.githubusercontent.com/15158071/165764946-2d5bb1d8-00a2-4631-b9e8-1fb28e299621.png)

**Edit:** I was trying other builds to see if Puyo Puyo Tetris 2 works fine on them and I thought I found one: Public Client 851

Loading times were not that great, but it managed to work for more than 3 hours without freezing. After a larger time than normal, when changing modes, the freeze happened again. 

![image](https://user-images.githubusercontent.com/15158071/169299929-58ae39a7-11ed-422c-b428-50f725f9429e.png)

I have a feeling that it's more prominent to freeze between loads. I hope it should be easy to fix this one.

Comparing all the logs I've submitted and others that I still have, there is a warning that repeats itself whenever I'm running the game:
`Service.ACC <Warning> core\hle\service\acc\acc.cpp:CheckAvailability:537: (STUBBED) called`

Instead of 537, sometimes it's 539.

After that sequence, sometimes it gives this:
`Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:571: Signalling debugger, PANIC! info1=0x000000100AF02EF8, info2=0x0000000000000004
Debug.Emulated <Critical> core\hle\kernel\svc.cpp:operator ():552: debug_buffer_err_code=EA01
Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:622: Emulated program broke execution! reason=0x0000000000000000, info1=0x000000100AF02EF8, info2=0x0000000000000004
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:79: Backtrace, sp=000000100AF02D20, pc=000000000A463D34
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:81: Module Name         Address             Original Address    Offset              Symbol
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:82: 
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100146158    000000000A216158    0000000000146158    _ZN2nn4diag6detail5AbortEPKNS_6ResultE
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100144A00    000000000A214A00    0000000000144A00    _ZN2nn4diag6detail10VAbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoES3_RSt9__va_list
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100144AD4    000000000A214AD4    0000000000144AD4    _ZN2nn4diag6detail9AbortImplEPKcS3_S3_iPKNS_6ResultES3_z
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 000000710042752C    000000000A4F752C    000000000042752C    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 000000710041A858    000000000A4EA858    000000000041A858    _ZN7android8BpBinder8transactEjRKNS_6ParcelEPS1_j
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100437BC8    000000000A507BC8    0000000000437BC8    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100440284    000000000A510284    0000000000440284    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100417CFC    000000000A4E7CFC    0000000000417CFC    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 0000007100416BB4    000000000A4E6BB4    0000000000416BB4    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 000000710046C1B0    000000000A53C1B0    000000000046C1B0    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                000000710044E318    0000000008452318    000000000044E318    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                0000007100886548    000000000888A548    0000000000886548    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                00000071008CA620    00000000088CE620    00000000008CA620    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                000000710083C3F4    00000000088403F4    000000000083C3F4    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                000000710063A628    000000000863E628    000000000063A628    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                00000071006770C4    000000000867B0C4    00000000006770C4    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                0000007100676888    000000000867A888    0000000000676888    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                0000007100675F00    0000000008679F00    0000000000675F00    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: main                0000007100000564    0000000008004564    0000000000000564    
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: sdk                 00000071002A3750    000000000A373750    00000000002A3750    _ZN2nn4init5StartEmmPFvvES2_S2_
Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:87: rtld                00000071000000D0    00000000080000D0    00000000000000D0    
Debug <Critical> core/hle/kernel/k_auto_object.h:operator ():161: Assertion Failed!`

**Comment by dunia01** [comment]
It's possible to change the compatibility mention of the game for any other category instead of 'Perfect' while this issue still remains? I'll keep editing with more tests and logs whenever the Public Version updates.

**Comment by liamwhite** [comment]
Almost certainly fixed by #9474
