### ISSUE TITLE
CHRONO CROSS: THE RADICAL DREAMERS EDITION fails to boot

### ISSUE THREAD

**Issue by Morph1984** [yuzu-emu/yuzu#8288]
Title. Opening issue for tracking purposes.

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8596116/yuzu_log.txt)

**Comment by benderscruffy** [comment]
using the latest EA and mainline
this is still an issue

**Comment by benderscruffy** [comment]
goes ingame now
 can be closed
