### ISSUE TITLE
yuzu crashing when you're downloading games into game folder

### ISSUE THREAD

**Issue by Redpoll2** [yuzu-emu/yuzu#8298]
I've noticed that yuzu searching for the new games even while you're playing a game. Because of it, when you're downloading a game through utorrent, yuzu can't read it and crashes silensly. I think "Don't search new games while playing" button will be useful :)

YUZU version : 1003 (2022-05-02)
Logs : [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8606448/yuzu_log.txt)

**Comment by goldenx86** [comment]
Do I even have to...
We don't provide support on piracy.
