### ISSUE TITLE
Model Debut Nicola 2 not launching

### ISSUE THREAD

**Issue by namyu25** [yuzu-emu/yuzu#8299]
Yuzu ver. 1003
I've tried every combination of settings possible and it just won't launch, which is weird because the first one works.

**Comment by G-Spawn** [comment]
uploading a log file helps us much more than what's currently provided.

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/reference/log-files/

**Comment by namyu25** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8607846/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Ah well sadly we cannot support pirated files. You'll have to dump everything from your console if you desire support here / on our forums.
