### ISSUE TITLE
Shin Megami Tensei V stuck at launching with any DLC installed

### ISSUE THREAD

**Issue by jqueuniet** [yuzu-emu/yuzu#8305]
Starting Shin Megami Tensei V with any DLC installed will result in the emulator locking at the Launching screen, after loading shaders. I tried with either of the free DLC available, the Japanese voice one (~3GB) and the easy mode one (~100KB), both with the same result. Attached is a cut version of the log since they get very large very fast (I guess there's a 100MB limit on those files?). Basically it's the same error message flooding the logs with only the memory address incrementing at each line.

```
[ 499.822771] HW.Memory <Error> core\memory.cpp:operator ():497: Unmapped Read64 @ 0x00000000000030C0
[ 499.822792] HW.Memory <Error> core\memory.cpp:operator ():497: Unmapped Read64 @ 0x00000000000030C8
[ 499.822809] HW.Memory <Error> core\memory.cpp:operator ():497: Unmapped Read64 @ 0x00000000000030D0
[ 499.822825] HW.Memory <Error> core\memory.cpp:operator ():497: Unmapped Read64 @ 0x00000000000030D8
[ 499.822869] HW.Memory <Error> core\memory.cpp:operator ():497: Unmapped Read64 @ 0x00000000000030E0
[ 499.822886] HW.Memory <Error> core\memory.cpp:operator ():497: Unmapped Read64 @ 0x00000000000030E8
[ 499.822899] HW.Memory <Error> core\memory.cpp:operator ():497: Unmapped Read64 @ 0x00000000000030F0
[ 499.822912] HW.Memory <Error> core\memory.cpp:operator ():497: Unmapped Read64 @ 0x00000000000030F8
```

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8626504/yuzu_log.txt)

At this point, the launching will continue indefinitely, and the GUI starts behaving erratically. I can get it to close gracefully using the windows red cross most of the time, sometime not and it will crash. Any other kind of interaction like trying to stop the emulation will deadlock the UI for a while, starting to show typical behaviour of a non-responding application with the blue ring, white veil and "yuzu.exe is not responding" message. Actually waiting a few minutes rather than killing it outright, it does recover and goes back to the main Yuzu menu.

The game starts as expected as soon as all DLC are removed. Changing OpenGL to Vulkan or removing the shader directory didn't solve anything either.

This issue is 100% reproducible, using early access build 2720.

Overall specs are as follows:
Intel i7-8700K
32GB of RAM
Nvidia GeForce GTX 3080 with driver 512.15
Latest Windows 11 general release

I noticed a few Reddit threads mentioning a similar issue a few months back, but nothing on the Citra forums.

https://www.reddit.com/r/yuzu/comments/sbfmzk/smtv_stuck_on_launching_screen/
https://www.reddit.com/r/yuzu/comments/qsozql/installed_smt_v_on_yuzu_getting_errors_about/

**Comment by G-Spawn** [comment]
please try to redump your dlc/update. corruption can happen to the files and yield memory issue like you've shown in log.

**Comment by jqueuniet** [comment]
Alright, I redumped everything, compared the checksums, new files are identical to the old ones and I'm still having the same issue.

I didn't mention it, but the 1.0.2 update I dumped works is fine by the way, only DLC seems to cause this.

**Comment by cannon9009** [comment]
For me, disabling the 1.0.2 update would make the game launch with DLC, but turning it on would produce a similar result as to being shown here, however there is no errors output to log; the emulator just is stuck on Launching without any log updates.

Turning the DLC off would have the same effect if 1.0.2 wasn't disabled. I'm not entirely sure how it will help, since my log doesn't have anything pointing to an obvious issue (it just has log outputs that normally show up when I play games, which don't have issues). Using EA2720 as well.

**Comment by jqueuniet** [comment]
Ok, I managed to solve this issue, for me at least. Root cause seemed do be with the DLC title keys in the end. I redumped and updated both my prod.keys and title.keys files, didn't work at first, but after deleting the title.keys_autogenerated the game started booting with DLC enabled.

My last prod.keys dump was sometime in January, I read somewhere firmware 14.0 came with new master keys, hence the idea to update the yuzu keys. That's just speculation from my uninformed part, but maybe Yuzu tried to derive the DLC title keys from the outdated prod.keys file and autogenerated useless keys? I have no idea if DLC keys are generated on the fly at download time, or if they're set in stone after publishing.

So, no big underlying problem with SMT5 or DLC, sorry for the noise on that part. My only remaining suggestion is that a more user-friendly error message would be welcomed when facing this kind of issue.

**Comment by jqueuniet** [comment]
More speculation, but the update might have worked for me because it was downloaded in late December when I initially got the game and encrypted with older keys (1.0.2 was already published by then). The DLC were downloaded two weeks ago and probably encrypted with the latest keys.

Someone who had working DLC and non-working update might be in a different scenario where they downloaded the DLC closer to release and updated the game later after the firmware update?

**Comment by G-Spawn** [comment]
Glad you managed to solve it.
