### ISSUE TITLE
Yuzu loading delay for multiple parts. EA 2721 and at least one previous

### ISSUE THREAD

**Issue by RuinerVoid** [yuzu-emu/yuzu#8315]
I open the Yuzu link from the desktop, it updates fine and starts up fine.

This is where things seem to get odd and it's due to a change that's happened in the past month. I don't know which EA version started this because I'd been binging the PC version of LEGO Skywalker Saga.

Anyway, here goes:

File -> Everything under this heading works as expected
Emulation -> Configure: Severe delay before loading
View -> Everything under this heading works as expected
Tools -> Everything under this heading works as expected
Help -> Everything under this heading works as expected

Opening a game -> Severe delay before loading starts

And as you can see, there nothing in the log that mentions any issues.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8645396/yuzu_log.txt)

**Comment by G-Spawn** [comment]
This issue is likely particular to your setup. I simply cannot replicate the things you've mentioned and so far no other patreon user has reported it in our discord. If you want to try earlier version it is much easier to use mainline for tracking issue like this https://github.com/yuzu-emu/yuzu-mainline/releases

**Comment by RuinerVoid** [comment]
> This issue is likely particular to your setup. I simply cannot replicate the things you've mentioned and so far no other patreon user has reported it in our discord. If you want to try earlier version it is much easier to use mainline for tracking issue like this https://github.com/yuzu-emu/yuzu-mainline/releases

Oddly, the most recent mainline version runs it all fine, and it seems to be loading all the same files.

**Comment by RuinerVoid** [comment]
Yeah. I'm confused now too. I reset and it's happening with all of them now.

It it supposed to open a second yuzu.exe process when the configuration window or a game loads? It's the only thing I've noticed that seemed odd of anything. In the task manager, the process seems to take a huge amount of power, reports as Not Responding, then a second process is opened (and also reports as Not Responding), and whenever the file fully loads (configuration or game) it goes back to normal power usage, starts responding again, and one of the processes disappears.

If this is my system and something new is happening to make yuzu hang, I'd love to get to the bottom of that too. I really like the program.

**Comment by G-Spawn** [comment]
> Yeah. I'm confused now too. I reset and it's happening with all of them now.
> 
> It it supposed to open a second yuzu.exe process when the configuration window or a game loads? It's the only thing I've noticed that seemed odd of anything. In the task manager, the process seems to take a huge amount of power, reports as Not Responding, then a second process is opened (and also reports as Not Responding), and whenever the file fully loads (configuration or game) it goes back to normal power usage, starts responding again, and one of the processes disappears.
> 
> If this is my system and something new is happening to make yuzu hang, I'd love to get to the bottom of that too. I really like the program. Found something that may be causing it, and it looks like it may be a combination of a windows 11 and yuzu audio device detection issue.
> 
> My audio devices are... messy at best. I've got a monitor that has speakers, speakers connected to my system, an attached TV, a mic from the webcam, a usb headset with mic, an oculus 2 that I hook up the PC, and Steam has added a 'streaming mic and speakers'. I've cleaned it up on the Windows setting so I can just swap between 3 output settings.
> 
> When I look in yuzu's audio devices (defaulted to auto) there's 54 lines of devices listed, many that are repeats. Possible issue, but I don't know, the lag is still there even with a completely fresh reinstall.
> 
> That said, I'll keep looking into this and leave this closed until (and if) I can narrow down the cause.

I would consider potentially reinstalling windows to rule out system instability. It wouldn't be the first time windows has screwed someone over :(

**Comment by RuinerVoid** [comment]
> > Yeah. I'm confused now too. I reset and it's happening with all of them now.
> > It it supposed to open a second yuzu.exe process when the configuration window or a game loads? It's the only thing I've noticed that seemed odd of anything. In the task manager, the process seems to take a huge amount of power, reports as Not Responding, then a second process is opened (and also reports as Not Responding), and whenever the file fully loads (configuration or game) it goes back to normal power usage, starts responding again, and one of the processes disappears.
> > If this is my system and something new is happening to make yuzu hang, I'd love to get to the bottom of that too. I really like the program. Found something that may be causing it, and it looks like it may be a combination of a windows 11 and yuzu audio device detection issue.
> > My audio devices are... messy at best. I've got a monitor that has speakers, speakers connected to my system, an attached TV, a mic from the webcam, a usb headset with mic, an oculus 2 that I hook up the PC, and Steam has added a 'streaming mic and speakers'. I've cleaned it up on the Windows setting so I can just swap between 3 output settings.
> > When I look in yuzu's audio devices (defaulted to auto) there's 54 lines of devices listed, many that are repeats. Possible issue, but I don't know, the lag is still there even with a completely fresh reinstall.
> > That said, I'll keep looking into this and leave this closed until (and if) I can narrow down the cause.
> 
> I would consider potentially reinstalling windows to rule out system instability. It wouldn't be the first time windows has screwed someone over :(
> 
> For the audio devices in yuzu them doubling is normal as far as I know. It had to do with how windows reports them to yuzu or something odd. Selecting one of the doubled entries should still work.

Reinstalling windows is the current plan. It's gonna be a bit before I can get there since I'm also installing a couple of giant HDDs and transferring files over to them. The odd thing is that I'm not getting any issues in any other programs, just yuzu for this issue, and even then, it's only when it's opening the configuration or a game, not any other thing in yuzu. That's why it leads me to believe it has something to do with the configuration files, since the games now have per-game configuration settings too, which means they're likely pulling info from the same area for default configs. Speaking of which, if I right click and check properties on a game, the same delay happens (and it locks up the entire program while this delay happens).
