### ISSUE TITLE
Feature Request - Play Time 

### ISSUE THREAD

**Issue by c4lkevin** [yuzu-emu/yuzu#8316]
### Feature:
When you boot Yuzu, games that you have put in your directory would show how long you've played the game along with other things yuzu shows already _that being Compatibility, Add-ons, File Type, & Size_

**Comment by G-Spawn** [comment]
https://github.com/yuzu-emu/yuzu/issues/4018 Closing in favour of previous request that is same as this one. They may be able to do something for this someday but not yet.
