### ISSUE TITLE
Xenoblade Chronicles 2 - Vulkan RGB Clownfest in "Land of Morytha"

### ISSUE THREAD

**Issue by LokeYourC3PH** [yuzu-emu/yuzu#8321]
Yuzu Build: yuzu 978 (2022-04-08)
System Specs:
- OS: Windows 11 Pro x64
- CPU: AMD Ryzen 5 3600 @4.2GHz
- GPU: NVIDIA RTX 3070 (emTek Xenon)
- RAM: ADATA XPG SPECTRIX D60G @3200MHz - 32GB
- SSD 1: CT120BX500SSD1 120GB
- SSD 2: Mystor SSD S910 512GB
- HDD 1: Seagate BUP Slim 4TB
- MOTHERBOARD: ASRock B450M Steel Legend (AM4)

Issue Description: In the game "Xenoblade Chronicles 2", while playing it in Vulkan on the current latest Yuzu build at the following settings:
- CPU Accuracy: Accurate
- API: Vulkan
- Use disk pipeline cache/Use asynchronous GPU emulation/Accelerate ASTC texture decoding = ALL Enabled
- Resolution: 2x (1440p/2160p) (Docked)
- Window Adapting Filter: AMD FidelityFX Super Resolution
- Adv. Graphics Accuracy Level: Extreme
- Use Fast GPU Time (Hack): Enabled

With these settings (or any for that matter), the "Land of Morytha" (and a few other places, although very rare throughout the game), look like an RGB Clownfest party that went on for too long. Image for reference:
![image](https://user-images.githubusercontent.com/5807595/167338403-d5779228-5c1c-4a84-9690-dd482440a09e.png)

This issue happens most notably in the _**ENTIRE**_ "Land of Morytha" region, and loses its charm after about the first 30 seconds.

Steps to recreate issue: Apply same or similar settings to mine, play Xenoblade Chronicles 2, visit "Land of Morytha" (if a save file is needed, I can provide it).

**Comment by PrinceBubloo** [comment]
Kindly provide safe file and log

**Comment by LokeYourLord** [comment]
Also, the pinnacle has got to be this cutscene where 95% of the stuff is just plain white, or so blinding that it isn't possible to see practically anything at all. It happens when you enter the Church in Elysium:
![image](https://user-images.githubusercontent.com/5807595/167442275-c3e9ab33-f028-402e-bf11-d0e2664ed019.png)

**Comment by G-Spawn** [comment]
Please try disabling mods and clearing your game shaders (right click game remove all pipeline cache). I'd also consider sticking to gpu normal or high not extreme for testing issue. As well auto cpu accuracy not accurate / unsafe.

**Comment by cannon9009** [comment]
IIRC, this issue also plagues SMT5. Are they made with the same engine (ex. Unity, UE4), by chance? If they are, it could be an engine issue.

**Comment by G-Spawn** [comment]
> IIRC, this issue also plagues SMT5. Are they made with the same engine (ex. Unity, UE4), by chance? If they are, it could be an engine issue.

Nah they have different engines and particular issues.

**Comment by G-Spawn** [comment]
> > Please try disabling mods and clearing your game shaders (right click game remove all pipeline cache). I'd also consider sticking to gpu normal or high not extreme for testing issue. As well auto cpu accuracy not accurate / unsafe.
> 
> Indeed, removing the shader cache solved the issue (I didn't delete/remove it, merely just renamed it in the folder). I used a shader cache I had imported, but that ultimately means that the "transferable shader cache pipeline" isn't as "transferable" as it would seem like if you cannot import old shader caches from your own/previous machine or from someone else's either (without these issues appearing that nearly break the game).

Using someone else shaders is illegal and can in fact cause this type of issue. Using your own from machines you own is fine but it is ultimately best to just make fresh shaders on new machine. Vulkan building times for shaders should treat you just fine.

**Comment by LokeYourLord** [comment]
> > > Please try disabling mods and clearing your game shaders (right click game remove all pipeline cache). I'd also consider sticking to gpu normal or high not extreme for testing issue. As well auto cpu accuracy not accurate / unsafe.
> > 
> > 
> > Indeed, removing the shader cache solved the issue (I didn't delete/remove it, merely just renamed it in the folder). I used a shader cache I had imported, but that ultimately means that the "transferable shader cache pipeline" isn't as "transferable" as it would seem like if you cannot import old shader caches from your own/previous machine or from someone else's either (without these issues appearing that nearly break the game).
> 
> Using someone else shaders is illegal...

Don't threaten me with a good time. Hahahaha seriously don't make me laugh, it is in no way "illegal", what you mean to say it is definitely advised against and can cause these issues for a multitude of reasons. But "illegal"? Don't be ridiculous.

And yeah the building times are mostly fine... I guess? I'm sometimes considering to use the Asynchronous Shader Building function to avoid the lag, because even having the game on my SSD (I had it on my HDD first and it lagged so badly), it still has microstutters that dip down to below 10FPS at times (although much less frequent than when it was on the HDD).

**Comment by G-Spawn** [comment]
shaders contain parts of the game when they're compiled so it is in fact illegal to be shared.

**Comment by gidoly** [comment]
should be fixed on last ea and mainline feel free to reopen if still happens
