### ISSUE TITLE
Unable to run any game on Ryzen 2400G ( from yuzu 991)

### ISSUE THREAD

**Issue by streng12** [yuzu-emu/yuzu#8323]
After some update, all games on yuzu stopped working. I'm not sure about certain build where the issue occurs, but yuzu not working anymore on yuzu 1010 or 1009 but when i rollback to 922 then it start working again.
The issue is that during first loading screens when shader loading should occur a yuzu application crashes. There is a completely empty log file with 0 bytes, so it crashes before log anything.
In the windows event viewer is this specific issues:

Faulting application name: yuzu.exe, version: 0.0.0.0, timestamp: 0x62766e93
Missing module name: ucrtbase.dll, version: 10.0.16299.1059, timestamp: 0x27fc3e10
Exception code: 0xc0000409
Error spacing: 0x000000000006b0be
Faulting process identification: 0x17a0
Faulting Application Start Time: 0x01d862e5f356cf8b
Faulting Application Path: C: \ Users \ User \ AppData \ Local \ yuzu \ yuzu-windows-msvc \ yuzu.exe
Faulting Module Path: C: \ Windows \ System32 \ ucrtbase.dll
Report ID: c569ba2d-6faf-4e16-98f2-5dfd1afeab0d
Faulting package full name:
Identifying the faulty application with respect to the package:

Computer specifications:
CPU: AMD Ryzen 5 2400G
GPU: Integrated - Vega11
RAM: 16GB 3200Mhz CL16 (OC)
MB: Gigabyte AB350N
OS: Win10

**Comment by Docteh** [comment]
You might need to update your Visual C runtime

https://yuzu-emu.org/downloads/ has a link to it.

**Comment by streng12** [comment]
It was a first thing which I tried and doesnt help

**Comment by german77** [comment]
3400G still works in here. Can you narrow the build number where it broke https://github.com/yuzu-emu/yuzu-mainline/releases

**Comment by Docteh** [comment]
Try 974, there was a log posted with it in the discord server on a 2400G.

**Comment by streng12** [comment]
So I made a research and for me, the latest working build is a 990. It starts crashing from 991.
Also tried 974 mentioned above and works fine.

**Comment by philectro** [comment]
restarting yuzu make an empty log, that's how it works.
may be related to the bug i reported today

**Comment by stu640978** [comment]
Same issue here, the latest build will crash when loading game.
Build 990 works fine too.

**Comment by vladkosi** [comment]
It looks like you are using [Windows 10 version 1709](https://support.microsoft.com/en-us/topic/march-19-2019-kb4489890-os-build-16299-1059-76c49d3e-dd54-eba7-c33f-ae6e382f6a77) - `ucrtbase.dll, version: 10.0.16299.1059`

I have two partitions with old versions 1511 and 1803. Yuzu is crashing on both since mainline 991.

Probably related to #8247 and #8386.

**Comment by streng12** [comment]
> It looks like you are using [Windows 10 version 1709](https://support.microsoft.com/en-us/topic/march-19-2019-kb4489890-os-build-16299-1059-76c49d3e-dd54-eba7-c33f-ae6e382f6a77) - `ucrtbase.dll, version: 10.0.16299.1059`
> 
> I have two partitions with old versions 1511 and 1803. Yuzu is crashing on both since mainline 991.
> 
> Probably related to #8247 and #8386.

You are right, I realized it some time ago but forgot to mention. Also need to note, once update to something newer than 1709, then build 990 and older start crashing. So in 991 something change when windows update needed.

**Comment by stu640978** [comment]
> Same issue here, the latest build will crash when loading game. Build 990 works fine too.

I just got a solution that can fix my issue from someone in the yuzu discord channel.
If you are using 3rd-party antivirus(For example: I'm using ESET Internet Security)
You might need to add the yuzu folder to the whitelist of your antivirus.
After doing this, now my yuzu works fine as expected(I'm using early access build now).

https://yuzu-emu.org/wiki/faq/#yuzu-closes-when-launching-game

**Comment by vladkosi** [comment]
This should be fixed by https://github.com/yuzu-emu/yuzu/pull/8745. You can try the latest [mainline build](https://github.com/yuzu-emu/yuzu-mainline/releases).

**Comment by benderscruffy** [comment]
Can be closed
