### ISSUE TITLE
Atelier Ryza 2 fails to launch (latest version)

### ISSUE THREAD

**Issue by Lengualo** [yuzu-emu/yuzu#8327]
Atelier Ryza 2 is failing to launch on the latest builds of Yuzu. It was working on earlier builds (upper 900's) but current builds its failing.

The game boots up, passes the first loading screen, the intro OP plays, then during the transition into the main menu the game hard crashes to desktop while the voice says "Atelier Ryza" with nothing rendered to screen. 

I cant post a crash log because its producing an empty log.

**Comment by G-Spawn** [comment]
provide a log from the version that works when you can so it provides more info for us to go off of.

**Comment by RinMaru** [comment]
Plays fine on YuzuEA 27220

**Comment by G-Spawn** [comment]
provide a log from the version that works please.

**Comment by RinMaru** [comment]
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/8657633/yuzu_log.zip)

**Comment by G-Spawn** [comment]
meant more for the OP to provide a log as they're the one with issue :p

**Comment by gidoly** [comment]
closes due to complete
