### ISSUE TITLE
yuzu won't install. please help.

### ISSUE THREAD

**Issue by Mjseverino** [yuzu-emu/yuzu#8329]
![Capture](https://user-images.githubusercontent.com/62778140/167731136-0d787f3b-a74a-4c2b-b91b-15a2ec3bf0ff.PNG)
I can't seems to install yuzu because of this error. went to FAQS but can't find the solution. Please help

**Comment by CrusadingNinja** [comment]
The issue tracker is for bug reports or feature requests only. Please use the yuzu discord server or the citra forums for help with support requests.

**Comment by G-Spawn** [comment]
Closing for aforementioned reason. https://discord.gg/u77vRWY Feel free to ask here.
