### ISSUE TITLE
Ezio Collection Main Menu loop

### ISSUE THREAD

**Issue by Mjseverino** [yuzu-emu/yuzu#8330]
Can't start my Ezio Collection dump. 
Whenever i choose to play any of the ac versions in the collection, it always brings back to main menu selection

**Comment by G-Spawn** [comment]
Please provide a log when you can like asked on the discord.

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/reference/log-files/

**Comment by yajun6666** [comment]
The same problem log has been submitted, version 2888

**Comment by MrChickenDipper** [comment]
Was a solution ever found?

**Comment by Blackbird88** [comment]
Seems to go ingame now, but no idea what fixed it
![image](https://github.com/yuzu-emu/yuzu/assets/4414625/96933bc4-35d8-485f-9c1f-93b12c397721)

**Comment by ChickenDipps** [comment]
For me ac2 works but the rest are in a constant state of loading

**Comment by ChickenDipps** [comment]
Are you able to boot into all 3 games or just AC2?

**Comment by ChickenDipps** [comment]
You can install the DLC on yuzu
