### ISSUE TITLE
Legends arceus crashes after intro screen

### ISSUE THREAD

**Issue by LAVEXLEON** [yuzu-emu/yuzu#8331]
Pokemon Legends arceus crashes once the intro scene is done (just prior to the first cutscene). I am using AMD Vulkan and problem doesnt seem to happen in OpenGL. But as I run AMD GPU, vulkan performance is much better than Open GL.

Here's the log:
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/8684015/yuzu_log.txt.old.txt)

**Comment by G-Spawn** [comment]
please try updating gpu driver.

**Comment by G-Spawn** [comment]
Well?

- This is going to get old quickly

**Comment by LAVEXLEON** [comment]
My driver is already updated to the latest version, is there any fix??

**Comment by G-Spawn** [comment]
Atm no. Linux would treat you the best for amd gpu as you would get more option than just Vulkan.

**Comment by pascalpuffke** [comment]
Runs perfectly fine here (apart from some minor graphical glitches and audio stuttering, nothing too bad) on yuzu 1022 with AMD + Vulkan. No crashes this far 5 hours in

**Comment by pacoa-kdbg** [comment]
@LAVEXLEON 
Can you give it a try with resolution scaling set to "x1" ?

**Comment by pacoa-kdbg** [comment]
@LAVEXLEON can you confirm your issue is not present anymore ?

**Comment by LAVEXLEON** [comment]
No, it's not.
