### ISSUE TITLE
Dead Or Alive Xtreme 3 Scarlet loading issue in build 1014

### ISSUE THREAD

**Issue by Laurimutso** [yuzu-emu/yuzu#8335]
Dead Or Alive Xtreme 3 Scarlet at random intervals gets stuck in endless loading when going into any game mode. Also happens with sports store but only in the mornings for some reason. Restarting the emulation helps to get around it.

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/8692959/yuzu_log.txt.old.txt)

**Comment by SirionX** [comment]
I'm also playing DoA Xtreme Scarlet this days but never faced that problem. The game sometimes hangs a little bit on location selection screen but other than that runs flawlessly. Build 1014 and 1.0.6 game version, Nvidia GPU with Vulkan and FSR selected. Yuzu and the game both running from an SSD if that matter.

 I've also locked the framerates at 40fps to make it a little smoother. 60fps doubles the game speed making it unplayable.

**Comment by Laurimutso** [comment]
I have 1.0.5 game version but I am running with RTX 2060 with Vulkan and from SSD. It's not like the game freezes, it just gets stuck in infinite loading on screens that usually take just a second or two to load. I've let it go for up to 10 minutes on occasion with nothing changing.

**Comment by SirionX** [comment]
I'm rocking the same GPU! 2060 with a Ryzen 3600. Yuzu settings that i've changed is 

1. Extended memory layout 
2. Accuracy Level Normal (From default High)
3. Vulkan - 2060 as Device 
4. 2x Resolution 2k-4k
5. Amd FSR as adapting filter. 

Lastly from my Nvidia Control panel i just enabled the Thread optimization and locked the fps at 40.

**Comment by gidoly** [comment]
is this resolved?

**Comment by MysticExile** [comment]
Any updates on this issue?

**Comment by gidoly** [comment]
closes due to lack of response
