### ISSUE TITLE
Binding of Isaac Afterbirth+ Input Issue

### ISSUE THREAD

**Issue by Deadzulu** [yuzu-emu/yuzu#8341]
Yuzu Version = mainline 1014
I've been trying to play The Binding Of Isaac: Afterbirth+ on yuzu and inputs are broken, I don't know what causes it and the first thing I'm going to try is reinstalling the game with my other available file extension.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8695646/yuzu_log.txt)

**Comment by german77** [comment]
Can you give me an update on this issue. I wonder if it's still broken

**Comment by german77** [comment]
Base game doesn't have pro controller. Support please use the latest game update since your log says 1.7 I suggest to install the update again.
