### ISSUE TITLE
AMD Unbelievably Slow H.264 decoding

### ISSUE THREAD

**Issue by RinMaru** [yuzu-emu/yuzu#8343]
At one-point Super Mario 3D Allstars played its opening video at a full 60fps but now its locked to 25 with FSR and 35 without. plays at the same speed regardless of CPU or GPU settings. both RX 480 and RX 6700XT play the video slow at the same speed.

Windows 11 Beta Insider
24GB DDR4 RAM
ASUS DUAL RX 6700XT OC
AMD R5 5600XT

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8697135/yuzu_log.txt)

**Comment by liamwhite** [comment]
The opening video is H.264, not VP9. I think this is something else.

**Comment by RinMaru** [comment]
> Can you pinpoint the last normal working version, It would be a big help

Not possible unless someone has access to Testing PRs from EA when NVDEC was being optimized

**Comment by RinMaru** [comment]
this has improved with YFC so ill close this

**Comment by RinMaru** [comment]
this issue is back its been back for awhile

**Comment by golivax** [comment]
I also have the same problem when using the Vulkan backend on the ROG Ally. The introduction video plays very slowly and the main menu navigation is also very slow. Works fine with OpenGL.

**Comment by liamwhite** [comment]
Note: no issue on linux

**Comment by golivax** [comment]
@liamwhite is it driver-related then?

**Comment by FernandoS27** [comment]
i wouldn't close it as there's only a workaround.
