### ISSUE TITLE
Seven Pirates H has horrible audio issues, but otherwise seems to run flawlessly

### ISSUE THREAD

**Issue by cannon9009** [yuzu-emu/yuzu#8345]
Since S.P.H released, I thought I might as well test how well it runs on Yuzu right out of the gate. I must say, it's faring better than I had hoped.

The only issue that I have noticed, and I mean **really noticed,** is a very bad audio issue that's apparent even as soon as you see the developer logos. Dev logos have zero sound, and sounds from the main menu produce... _very irritating noises._ If needed, I will post a video to demonstrate what I mean, but in the meantime, here is a log of what's going on.

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/8697420/yuzu_log.txt.old.txt)

**Comment by german77** [comment]
Another to the list #7972
