### ISSUE TITLE
Yuzu cannot run in Windows 11 build 22621

### ISSUE THREAD

**Issue by Slemoon** [yuzu-emu/yuzu#8357]
Yuzu cannot run in Windows 11 build 22621 when open XCI file

**Comment by Docteh** [comment]
Any particular error to share?

**Comment by Slemoon** [comment]
> Any particular error to share?

it's crashed and exit。

**Comment by Slemoon** [comment]
> For assistance with your issue, please accurately describe the problem and post a log file. The following guide shows how to get the log file: https://yuzu-emu.org/help/reference/log-files/


[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8730373/yuzu_log.txt)

**Comment by Slemoon** [comment]
> For assistance with your issue, please accurately describe the problem and post a log file. The following guide shows how to get the log file: https://yuzu-emu.org/help/reference/log-files/



> Any particular error to share?
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8730410/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Join the yuzu discord and read the pinned messages in the windows support channel regarding pagefile. This isnt really worth an issue for here.

**Comment by SpecialDarkwolf999** [comment]
Yuzu works fine on Windows 11 even on that build

**Comment by G-Spawn** [comment]
Please.
> Join the yuzu discord and read the pinned messages in the windows support channel regarding pagefile. This isn't really worth an issue for here.
https://discord.gg/u77vRWY
