### ISSUE TITLE
Xenoblade Chronicles 2 unplayable on yuzu 1014

### ISSUE THREAD

**Issue by yofoke9708** [yuzu-emu/yuzu#8365]
I´ve been playing Xenoblade 2 since November and it worked just fine till a few months ago stopped working. It started to lag very hard, the FPS were dropping constantly to 10 FPS or even less (with my modest setup, I had 20-30 fps stable all the time, no lag) until it suddenly crashed without warning (on battle, doing specials, during a cutscene etc) a few minutes into the gameplay (no more than 15 minutes of gameplay).

The last version I tried is yuzu 1021 (#e89660a) (18/05/2022) but I have had this problem with all the updates since March 2022. I even tried with the Nvidia driver 512.77 (the latest one right now) but the result was the same, lag and crash.

I´ll stick a few logs of the crashes of yuzu 1014 (#4d5eaaf) (12/05/2022), because I didn´t even bother to grab logs from yuzu 1021. I also uploaded a save so you can test it.

I can confirm firsthand that Xeno is running fine on Yuzu 865 (31/12/2021) with Nvidia driver 472.12 (the one I had when I started playing Xenoblade Chronicles 2).

English is not my native language, so sorry if you notice any mistakes or weird grammar.

System Specs:
OS: Windows 10
CPU: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz 
GPU: NVIDIA GTX 1050 4GB VRAM
RAM: 8GB
Nvidia Driver: 512.77
OpenGL: 4.6
SSD: 256 GB

Yuzu settings:
CPU Accuracy: Accurate
API: Open GL
Use disk pipeline cache/Use asynchronous GPU emulation/Accelerate ASTC texture decoding = ALL Enabled
Shaders: GLASM
GPU High
Dock
Bilineal
No AA

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8744906/yuzu_log.txt)
[yuzu_log_old.txt](https://github.com/yuzu-emu/yuzu/files/8744907/yuzu_log_old.txt)
[Save.zip](https://github.com/yuzu-emu/yuzu/files/8744912/Save.zip)

**Comment by G-Spawn** [comment]
We don't support piracy here.
