### ISSUE TITLE
G-sync doesn't work on Vulkan but does work on OpenGL backend

### ISSUE THREAD

**Issue by Ameer2002** [yuzu-emu/yuzu#8371]
G-sync has been broken on Yuzu Vulkan since 812 now, on OpenGL exclusive full screen it works with no issues. I have tried disabling full screen optimizations, adjusting any and all graphics related settings in Yuzu etc to no avail. Neither borderless nor full screen works for Vulkan. The exact same problem occured with CEMU, but was fixed by the devs after I posted about it. It was an identical situation to this one. 

I7 8700k
32GB Ram
GTX 1080Ti 
Windows 10 21H2

**Comment by G-Spawn** [comment]
Closing in favor of the already existing issue. (https://github.com/yuzu-emu/yuzu/issues/7373) making new issue for it wont speed it along faster.
