### ISSUE TITLE
Compiling Error: "‘constexpr’ static data member ‘dummy_flow_block’ must have an initializer"

### ISSUE THREAD

**Issue by HurricanePootis** [yuzu-emu/yuzu#8376]
# Compiling Error: "‘constexpr’ static data member ‘dummy_flow_block’ must have an initializer"
## System Information
Arch Linux
* Linux `5.18.0`
* glibc `2.35`
* glslang `11.9.0`
* libfdk-aac `2.0.2`
* libxkbcommon `1.4.1`
* lz4 `1.9.3`
* mbedtls `2.28.0`
* opus `1.3.1`
* QT5 `5.15.4+kde+r144`
* SDL `2.0.22`
* boost `1.78.0`
* boost-libs `1.78.0`
* catch2 `2.13.9`
* ffmpeg `5.0`
* GCC `12.1.0`
* clang `13.0.1`

## Build Options/Flags
```
    cmake .. \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release \
      -DYUZU_USE_QT_WEB_ENGINE=ON \
      -DYUZU_USE_EXTERNAL_SDL2=OFF \
      -DUSE_DISCORD_PRESENCE=ON \
      -DENABLE_QT_TRANSLATION=ON \
      -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON \
      -DBUILD_TAG=${pkgver} \
      -DTITLE_BAR_FORMAT_IDLE="yuzu | ${pkgver} {}" \
      -DTITLE_BAR_FORMAT_RUNNING="yuzu | ${pkgver} | {}" \
      -DYUZU_USE_BUNDLED_OPUS=OFF \
      -DYUZU_USE_BUNDLED_FFMPEG=OFF \
      -DYUZU_USE_BUNDLED_LIBUSB=OFF \
      -DYUZU_USE_BUNDLED_QT=OFF
```
```
CPUARCH=znver1
CFLAGS="-march=$CPUARCH -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"
```
## Yuzu Version
`r21409.4eb7f6c04`

## My Issue
Whenever the build process get's to building the shader recompiler's frontend, `src/shader_recompiler/frontend/maxwell/structured_control_flow.cpp` throws up the following issue.
```
/home/hurricane/yuzu-git/src/yuzu/src/shader_recompiler/frontend/maxwell/structured_control_flow.cpp:981:34: error: ‘constexpr’ static data member ‘dummy_flow_block’ must have an initializer
  981 |     static constexpr Flow::Block dummy_flow_block;
      |                                  ^~~~~~~~~~~~~~~~
```
Even using a different compiler, like clang, gives the same issue (with more debug information)
```
/home/hurricane/yuzu-git/src/yuzu/src/shader_recompiler/frontend/maxwell/structured_control_flow.cpp:981:34: error: constexpr variable cannot have non-literal type 'const Flow::Block'
    static constexpr Flow::Block dummy_flow_block;
                                 ^
/home/hurricane/yuzu-git/src/yuzu/src/./shader_recompiler/frontend/maxwell/control_flow.h:69:16: note: 'Block' is not literal because it has base class 'boost::intrusive::set_base_hook<boost::intrusive::link_mode<boost::intrusive::normal_link>>' of non-literal type
struct Block : boost::intrusive::set_base_hook<
```
And, whenever I compile without any set buildflags, the problem persists.

**Comment by xcfrg** [comment]
Clang bug, patch:
```diff
--- a/src/shader_recompiler/frontend/maxwell/structured_control_flow.cpp
+++ b/src/shader_recompiler/frontend/maxwell/structured_control_flow.cpp
@@ -977,7 +977,7 @@ private:
     bool uses_demote_to_helper{};
 
 // TODO: C++20 Remove this when all compilers support constexpr std::vector
-#if __cpp_lib_constexpr_vector >= 201907
+#if (__cpp_lib_constexpr_vector >= 201907) && !(defined(__clang__))
     static constexpr Flow::Block dummy_flow_block;
 #else
     const Flow::Block dummy_flow_block;
```

**Comment by HurricanePootis** [comment]
@xcfrg Thank you for the patch, but this problem both happens with GCC and clang. I have tried the patch, successfully compiling yuzu with clang. However, I am still unable to compile yuzu with GCC, which is my prefer choice of compiler and system default

**Comment by liamwhite** [comment]
GCC 12 is currently unable to compile yuzu due to [numerous](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105420) [compiler](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105423) [bugs](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105424) that you must wait for the compiler writers to fix. The occurrences of this bug are so numerous that and the bugs are so obvious that it doesn't make much sense to work around them.

**Comment by xcfrg** [comment]
Clang offers much better optimizations with it's LTO as well
I would recommend its use to compile yuzu even after the GCC 12 compiler bugs are fixed

**Comment by HurricanePootis** [comment]
I was able to compile yuzu fully with GCC 12 using this modified version of the patch

```
--- a/src/shader_recompiler/frontend/maxwell/structured_control_flow.cpp
+++ b/src/shader_recompiler/frontend/maxwell/structured_control_flow.cpp
@@ -977,7 +977,7 @@ private:
     bool uses_demote_to_helper{};
 
 // TODO: C++20 Remove this when all compilers support constexpr std::vector
-#if __cpp_lib_constexpr_vector >= 201907
+#if (__cpp_lib_constexpr_vector >= 201907) && !(defined(__clang__)) && !(defined(__GNUC__))
     static constexpr Flow::Block dummy_flow_block;
 #else
     const Flow::Block dummy_flow_block;
```
If y'all think it's best, I'll just put this patch in the AUR PKGBUILD's for yuzu and yuzu-mainline until the compiler bugs are fixed, and a new version of GCC is pushed.

**Comment by HurricanePootis** [comment]
> Clang offers much better optimizations with it's LTO as well I would recommend its use to compile yuzu even after the GCC 12 compiler bugs are fixed

Thank you for your recommendation, but I have a few unrelated questions to this issue. Does clang really provide better lto optimizations than GCC? I mean, I already use GCC as my default compiler because I think it'd be rather tedious to manually edit every AUR PKGBUILD I download to use clang, and I already hit a stable and acceptable FPS in all the games I play on yuzu.

**Comment by xcfrg** [comment]
For me at least, I get around a 10-12% increase in performance with my clang build flags over defaule gcc: `-GNinja -DYUZU_USE_EXTERNAL_SDL2=OFF -DYUZU_USE_BUNDLED_OPUS=OFF -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON -DCMAKE_POLICY_DEFAULT_CMP0069=NEW -DCMAKE_CXX_FLAGS="-march=native -mtune=native" -DCMAKE_C_FLAGS="-march=native -mtune=native" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold"` (`-march=native` plays a part in this too), but this is worth it for me to do due to my lower-end hardware (i7 10750h, rtx 2060) that can't reach full speed on some games without this

No point in doing this for all AUR PKGBUILDs, just when it makes sense to do so

**Comment by HurricanePootis** [comment]
> 

How did you benchmark this performance boost? I'm now curious and want to see what gains I can get on my system as well

**Comment by xcfrg** [comment]
This was just an average over me testing all the games I owned that did not run at full speed, with mangohud logs, nothing scientific
