### ISSUE TITLE
[Feature Request] Create empty folders with TitleID and title name in saves/DLC folders for readability

### ISSUE THREAD

**Issue by KonaKona7** [yuzu-emu/yuzu#8378]
How the save/DLC folders currently look:
0100ABF008968000
0100AE00096EA000
0100F4300BF2C000
01000B900D8B0000
01001F5010DFA000

How the save/DLC folders would look with named empty folders:
0100ABF008968000
0100ABF008968000 Pokemon Sword
0100AE00096EA000
0100AE00096EA000 Hyrule Warriors Definitive Edition
0100F4300BF2C000
0100F4300BF2C000 New Pokemon Snap
01000B900D8B0000
01000B900D8B0000 Cadence of Hyrule
01001F5010DFA000
01001F5010DFA000 Pokemon Arceus Legends

I've manually done this for all my modded consoles to make organizing and searching through folders more easy, but it would be great if this was automated by Yuzu. This is especially helpful when you want to edit saves with an editor like PKHex and need to browse for the save file manually, or simply making backups for a specific title.

![Untitled](https://user-images.githubusercontent.com/67726146/170184312-8ee093a8-c893-40f1-b5a9-3b97387acabd.png)

**Comment by Docteh** [comment]
This seems like a thing to do in a separate tool. The English names are available in XML format from http://nswdb.com/ 

for Windows maybe C++, Rust or GO would be good language.

**Comment by Morph1984** [comment]
As said by docteh, this kind of feature is best left to an external tool. What you propose may be perceived as unnecessary bloat when opening the save directory within the emulator is sufficient for most users.

**Comment by G-Spawn** [comment]
> 

Closing for aforementioned reason.
