### ISSUE TITLE
Dairoku: Agents of Sakuratani is not opening or doesn't start at all, it crashes at Loading Shaders

### ISSUE THREAD

**Issue by lamegirlhiks** [yuzu-emu/yuzu#8390]
When i first started the game, it was the same as others like click "Load File" and then **Loading Shaders** then it work but this, it keeps **loading shaders** and doesn't start or open the game at all

![image](https://user-images.githubusercontent.com/106467450/170859184-5ed3b7f6-79f9-4c14-87a2-a55a280efc68.png)

and my laptop spec is
Graphics: NVIDIA GeForce GTX 1650Ti 4GB
Processor: AMD Ryzen 5 4600HS with Radeon Graphics, 3.00 GHz
RAM: 8,00 GB
System type: 64-bit operating system

**Comment by goldenx86** [comment]
Please include a log file.

**Comment by G-Spawn** [comment]
We don't support piracy here.
