### ISSUE TITLE
Dragon Quest XI flatpak vs. mainline issues

### ISSUE THREAD

**Issue by username227** [yuzu-emu/yuzu#8399]
Hi all,

Hope somebody can advise. I am trying to play Dragon Quest XI. In the past, it worked well with this flatpak yuzu, with some minor graphical glitches. Now, however, on a replay, I am getting significant blinking and graphical glitches that basically prevent from starting. I read on another issue that Vulkan works without these glitches so I tried Vulkan. The latest flatpak with this game crashes Yuzu when I try to start with Vulkan. Log file  attached.

Interestingly enough, I found an appimage which is labeled as HEAD-mainline-636-8849-ga526692c2-dirty. Two differences I noticed with this version - 1) the games show the compatibility; on the flatpak they all say not tested. 2) DQ11 will start and run pretty much perfectly (with testing so far) on Vulkan, and it doesn't crash.

So in the short term, the answer is to obviously to use this version. But why does it crash in the flatpak version? Is the flatpak version not as advanced? All graphics settings on both versions were identical.

I'm running Nvidia geforce/amd 5600 series with Linux Mint 20.3.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8810330/yuzu_log.txt)

**Comment by G-Spawn** [comment]
iirc appimage uses your system mesa which may not be the same one the flatpack uses. 
![image](https://user-images.githubusercontent.com/23653025/171310520-87fed016-daae-414a-a3bc-72d08ccbb57e.png) <https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/wikis/mesa-git>

**Comment by G-Spawn** [comment]
You can try what was shown to you in picture & source context link. Or consider closing issue and joining discord for further support.

**Comment by G-Spawn** [comment]
Closing as I feel it would be better to continue this in the discord server if you continue to have problem. It's not entirely yuzu related issue for flatpack not using appropriate mesa. https://discord.gg/u77vRWY
