### ISSUE TITLE
Translation issue - french Windows game list settings section

### ISSUE THREAD

**Issue by ErixTricittey** [yuzu-emu/yuzu#8407]
Translation issue: In french frontend, game icon size and folder icon size option labels have been inverted. So setting game icon size would set the folder size value instead, and setting folder icon size sets game icon size. Just changing frontend text would fix this.

![Capture d’écran 2022-06-01 085753](https://user-images.githubusercontent.com/101439928/171409815-2c349c6f-8d03-40c7-91ce-23faca87779e.png)

**Comment by G-Spawn** [comment]
this should be corrected on Transifex now if I'm not mistaken. If not please discuss in the Translation channel on discord.

**Comment by G-Spawn** [comment]
![image](https://user-images.githubusercontent.com/23653025/173757801-88d3e6ba-a9e5-42f6-8f51-a29ce3b568dc.png)
Seems the user who meant to change it didn't. So I did. It should be reflected in mainline-early access whenever the changes are pushed through.
