### ISSUE TITLE
Hyrule Warriors: AOC - Level - Polishing His Technique - Yuzu 1036

### ISSUE THREAD

**Issue by mikegonzalez2k** [yuzu-emu/yuzu#8408]
Entire level is black.   UI is visible, seemed like a lighting issue.
After attempting to reload the level 3 times it finally worked perfectly.
It's not a lighting issue, it's  possibly something with the loading of the assets for that level.
Restarted the emulator, first time intot the level the lighting worked, but the terrain was stretched.

![Zelda AOC - Polishing His Technique -  Restarted Emulator](https://user-images.githubusercontent.com/6504617/171458778-a3256b03-c5ec-4ed7-90ed-424e2538adc9.png)

Mission: 
Polishing His Technique

Location:
Eldin Moutains (see screenshot)
![Zelda AOC - Polishing His Technique](https://user-images.githubusercontent.com/6504617/171457155-0211b7ee-bd69-4bee-9fcd-ec9d76be9fe3.png)

Yuzu 1036
GPU Settings: Vulkan

My GPU
Nvidia GTX 1650

**Comment by german77** [comment]
Upload a log please. https://yuzu-emu.org/help/reference/log-files/

**Comment by G-Spawn** [comment]
iirc this may also happen when you corrupt your save? Log will def help

**Comment by G-Spawn** [comment]
I would also try clearing your shaders since you mentioned in closed issue a few hours ago that you recently updated your gpu drivers. (Right click game remove all pipeline cache)

**Comment by mikegonzalez2k** [comment]
I enabled Graphic log and Shader logs.
Restarted Yuzu.
Ran that level 3 times.
1st time, ran perfect
2nd time, stretched textures
3rd time, perfect

Here are the screens from my 2nd test
![Zelda AOC - Polish - Test 2 01](https://user-images.githubusercontent.com/6504617/171524003-2fae30c3-b792-411c-8e84-8ae84a829196.png)

![Zelda AOC - Polish - Test 2 02](https://user-images.githubusercontent.com/6504617/171524012-c523d014-df47-4aef-bbb8-ed88017e33e8.png)


Here is the log from the test.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8819594/yuzu_log.txt)

**Comment by mikegonzalez2k** [comment]
Okay so more info on this bug as I've been seeing it throughout gameplay (currently at end of game).
The bug seems to ONLY occur during certain lighting conditions related to the changing of Time of Day in the game.

Specifically between early morning and morning there are light rays that cast particular shadows on maps you are in.
These rays seems to be calculated incorrectly.

**Comment by benderscruffy** [comment]
is this still an issue ??

**Comment by mikegonzalez2k** [comment]
I haven't played since then so I don't know if it happens on the latest version.

**Comment by benderscruffy** [comment]
please close then

**Comment by mikegonzalez2k** [comment]
Old issue not tested on latest version.
