### ISSUE TITLE
Sonic Colors missing lighting effects

### ISSUE THREAD

**Issue by Hadrianneue** [yuzu-emu/yuzu#8411]
Mesa Version: 22.0.4
GPU R7 360 2G GCN2
CPU xeon 1230 V2
![010040e0116b8000_2022-06-01_22-47-51-145](https://user-images.githubusercontent.com/24306541/171530961-0524dcba-ee97-4796-bedf-104a198bf03c.png)
![010040e0116b8000_2022-06-01_22-48-56-914](https://user-images.githubusercontent.com/24306541/171530964-4db7567b-9365-4b29-b104-6323e21cc519.png)

Pretty much as the title says, perhaps because this is a GCN2 GPU, there's #7432 which is similar which is also a GCN GPU but running under windows...

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8819929/yuzu_log.txt)

**Comment by benderscruffy** [comment]
is this still an issue ???

**Comment by RinMaru** [comment]
no issue with RDNA2 aside from certain objects not rendering
