### ISSUE TITLE
Hyrule Warriors: AOC - GPU - Floor Textures Missing - Yuzu 1036

### ISSUE THREAD

**Issue by mikegonzalez2k** [yuzu-emu/yuzu#8412]
Floor Textures are missing on parts of the level.

Location: Gerudo Desert
Mission: Nap Quest
Yuzu 1036

![Zelda AOC - Floor Missing](https://user-images.githubusercontent.com/6504617/171534069-35670c0c-b699-4809-935c-f77911580948.png)

Log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8819973/yuzu_log.txt)

**Comment by G-Spawn** [comment]
You can keep it in one issue as it looks to be related.
