### ISSUE TITLE
Infernax

### ISSUE THREAD

**Issue by Vertimusmaximus** [yuzu-emu/yuzu#8415]
Infernax is running good. 

https://user-images.githubusercontent.com/104597050/171758967-219e6860-797b-41bc-9992-dbf28049ca43.mp4

**Comment by lat9nq** [comment]
If a game is running well then there is no need to create frivolous issues like this.

**Comment by Vertimusmaximus** [comment]
Oh. I thought there needed to be an issue to get it added to the list of compatible games. Yuzu says hyper light drifter and infernax don't work or are untested. Was making an entry to fix that. Hopefully.

**Comment by lat9nq** [comment]
I believe you're looking for this, then: https://github.com/yuzu-emu/yuzu-games-wiki

Keep in mind that the compatibility report seen in yuzu is based on user-generated data is should be taken with a grain of salt, regardless.

**Comment by Vertimusmaximus** [comment]
The list says hyper light drifter won't boot. Am I able to submit fixes to
the list or suggest retesting? Hyper light drifter was running just fine.
For me.

**Comment by Vertimusmaximus** [comment]
How do you find GitHub users email? I've been trying to contact the skyline
owner in email but can't Find it.
