### ISSUE TITLE
Test of The witcher 3

### ISSUE THREAD

**Issue by Rafilou3321** [yuzu-emu/yuzu#8416]
The game is clearly impossible to play, even with determination, the screen keeps switching from one to the other, which is a pain for the eyes, the sounds are ok.
(im using a AMD Ryzen 5 4600H and the link is a video of the test)
https://drive.google.com/file/d/1uQNzF6ZP3OMDiJBjKWkmcUwl71DQR_80/view?usp=sharing
![Films et TV 03_06_2022 02_36_43 (1)](https://user-images.githubusercontent.com/106785676/171762502-10f7f6a1-c9ae-43eb-9e0a-3d560205768a.png)
![Films et TV 03_06_2022 02_36_37 (2)](https://user-images.githubusercontent.com/106785676/171762515-78c8d013-8706-49e5-a4c8-6118e9700daa.png)

**Comment by G-Spawn** [comment]
Please provide a log file like the issue template asked for 🙏

**Comment by Rafilou3321** [comment]
The game works correctly, ils just visual (you can see that on the minimap

**Comment by Rafilou3321** [comment]
> Please provide a log file like the issue template asked for 🙏

Sorry to bother you more but how to do that?

**Comment by Rafilou3321** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8831666/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Ah well I'm afraid we cant support piracy here.  Closing. You'll  be expected to dump all your files from your Nintendo switch to legally proceed & receive support here.
