### ISSUE TITLE
Hyrule Warriors AOC - Performance - Decrease from 1036 to 1040

### ISSUE THREAD

**Issue by mikegonzalez2k** [yuzu-emu/yuzu#8417]
Updated Yuzu from 1036 to 1040 and saw a pretty significant frame drop.

Previously I used the mission EXPLOSIVE WITH CARE to farm money and it ran at 30 fps consistently.  Absolutely zero slow down.
On Yuzu 1040 getting frame drops as low as 13 fps... with average around low 20s.  Something changed that lowered overall framerates in missions.

Log File
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8830682/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Did you enable shader feedback in debug? Perhaps that is affecting it as well.

**Comment by mikegonzalez2k** [comment]
Definitely not shaders.. I completely turned off debugging and still the same frame rates.

**Comment by G-Spawn** [comment]
Ty for ruling it out

**Comment by mikegonzalez2k** [comment]
So it looks like the very low dips in frames happen when there are explosions and fire in the game.  Maybe it's something to do with resources used by physics engine to calculate the particle effects.

**Comment by mikegonzalez2k** [comment]
What's weird is that on the previous version (1036) it remained a solid 30 fps. with only minor dips to 29.
It ran almost perfectly before.

**Comment by G-Spawn** [comment]
I will ask other tester-staff if they can replicate or narrow down potential cause.

**Comment by benderscruffy** [comment]
Is this still an issue ??
