### ISSUE TITLE
Poly Bridge graphical issues

### ISSUE THREAD

**Issue by piplup55** [yuzu-emu/yuzu#8421]
**Version:**
Linux: **Flatpak KDE** Yuzu 1026 [cb17e67061f85d645bf217fc50c861028a8a1bcf](https://github.com/flathub/org.yuzu_emu.yuzu/commit/cb17e67061f85d645bf217fc50c861028a8a1bcf)

Windows: **Yuzu [1040](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1040)**

**To reproduce:**
Load a level/menu with vulkan

**Logs:**
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8837698/yuzu_log.txt) (for some reason the emulator crashes when closing the game unrelated but just though i would say it)

**Screenshots:**
yuzu with vulkan on linux: ![image](https://user-images.githubusercontent.com/100526773/171999179-0dd9f5cb-aa57-4801-9eb9-2b1fbc80889c.png)

real switch: ![image](https://user-images.githubusercontent.com/100526773/171999412-cb4edc7f-2808-46c8-9765-34a4808ed375.png)

**More details:**
Works fine on opengl: ![image](https://user-images.githubusercontent.com/100526773/171999093-6b955afe-6f29-45a1-b615-2e416dcd0205.png)
also happens on windows:
![image](https://user-images.githubusercontent.com/100526773/171999107-296a1fa0-0e15-464b-aa1f-a90f9e9fa6af.png)

**System Specs:**
Linux:
 - OS: Arch Linux
 - CPU: AMD Ryzen 7 3700X
 - GPU: RX6600 XT
 - Memory: 80GB, Swap: 256GB
 - GPU Driver: Mesa 21.3.8, radv 21.3.8

Windows:
 - OS: Windows 10 21H1
 - CPU: AMD Ryzen 7 3700X
 - GPU: RX6600 XT
 - Memory: 48GB, Pagefile: 3.63GB
 - GPU Driver: 22.5.2

**Comment by benderscruffy** [comment]
using the latest EA and mainline 
this is still an issue

**Comment by benderscruffy** [comment]
it has been fixed on windows
![Screenshot 2023-09-27 154311](https://github.com/yuzu-emu/yuzu/assets/2696404/1d6148d1-7920-48be-a962-605d6d49cfe5)

**Comment by piplup55** [comment]
doesn't' look like it's fully fixed on radv at least
![image](https://github.com/yuzu-emu/yuzu/assets/100526773/4886d704-0f56-4832-9d43-68bc89d311bd)
![image](https://github.com/yuzu-emu/yuzu/assets/100526773/df1f9d9d-138e-47bc-8d0c-0f1ae39a3e78)
![image](https://github.com/yuzu-emu/yuzu/assets/100526773/cdc41b0b-c046-479d-85fc-31badf2551bb)

**Comment by benderscruffy** [comment]
soi t is bugged on AMD
as i have a Nvidia card

**Comment by piplup55** [comment]
seems to be fixed on my end now
![image](https://github.com/yuzu-emu/yuzu/assets/100526773/c5993778-662a-4329-bc60-430f40f303b3)
