### ISSUE TITLE
Feature request: Switch profile from command line for multiuser front end compatibility

### ISSUE THREAD

**Issue by tastyratz** [yuzu-emu/yuzu#8423]
Yuzu has the capability of multiple user profiles which is brilliant. When launching yuzu by command line in full-screen mode, if I was able to choose a specific user profile I could create 2 "emulators" in Launchbox by user. Then I could easily choose different users and maintain different savegames for people in the household.

**Comment by german77** [comment]
This already exist https://github.com/yuzu-emu/yuzu/pull/6116

**Comment by tastyratz** [comment]
Oops! I searched the issue list beforehand too. I didn't realize more command-line arguments were added. My mistake! I'll close this. Thanks for directing me to how it can be done!
