### ISSUE TITLE
Super Mario Odyssey - UI - Action Guide Menu Missing - Yuzu 1042

### ISSUE THREAD

**Issue by mikegonzalez2k** [yuzu-emu/yuzu#8429]
In Super Mario Odyssey there is a menu option called the Action Guide.
Normally it has a menu that teaches you all of Mario's moves.
This menu is missing in the UI.

Reproduce:
Launch the game.
While in game press start to pause the game.
Select "Action Guide"

Expected Behavior:
A sub menu should appear with options to view Mario's basic moves.
See this video for what should happen.
https://www.youtube.com/watch?v=EUmdWfYdKk8

Actual Behavior:
When the Action Guide is selected nothing happens.
https://user-images.githubusercontent.com/6504617/172082956-34d362fa-0f5f-46ea-b7d1-810411d0517a.mp4

Yuzu 1042
Logfile
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8841350/yuzu_log.txt)

**Comment by Morph1984** [comment]
Super Mario Odyssey uses the web applet to display the action guide. The web applet is essentially a cut down web browser.
We have disabled the web applet by default as some users have encountered issues with it.
If you would like to enable it, go to `Emulation > Configure > General > Debug` and untick `Disable Web Applet`

![image](https://user-images.githubusercontent.com/39850852/172104003-be0871f3-0ccb-4766-b0b9-14eb3d85ff6d.png)

**Comment by pinguluk** [comment]
> Super Mario Odyssey uses the web applet to display the action guide. The web applet is essentially a cut down web browser. We have disabled the web applet by default as some users have encountered issues with it. If you would like to enable it, go to `Emulation > Configure > General > Debug` and untick `Disable Web Applet`
> 
> ![image](https://user-images.githubusercontent.com/39850852/172104003-be0871f3-0ccb-4766-b0b9-14eb3d85ff6d.png)

Still doesn't work for me. It just fade to black then goes back to menu
