### ISSUE TITLE
BUG Memory

### ISSUE THREAD

**Issue by Soi9x** [yuzu-emu/yuzu#8430]
![image](https://user-images.githubusercontent.com/94919121/172147892-eac78fbd-54a7-4af7-ad94-5d3b85d12725.png)
Hello I Get This Error When I Press Button (A) Start Game On Emulator!

![image](https://user-images.githubusercontent.com/94919121/172148093-f7066adc-8b56-41b8-b882-fe0877e81cb3.png)

![image](https://user-images.githubusercontent.com/94919121/172148158-5e2a96f2-6bb4-4733-8d9b-e01fe162b16e.png)

This Is My Configuration!

If This Is A Memory Leak When Running Emulator , I Ask Yuzu To Offer Memory Optimization On Emulator!

![image](https://user-images.githubusercontent.com/94919121/172148367-07cbd91b-07ca-46fe-af73-9052ada6dad2.png)

![image](https://user-images.githubusercontent.com/94919121/172148704-6a0c3770-c666-4ae7-9afc-ff079642ebab.png)

**Comment by G-Spawn** [comment]
Provide the log file for yuzu like the issue template asked for when you can please. Upload the text file to here

**Comment by G-Spawn** [comment]
Feel free to reopen issue when you can provide log file. Closing to hopefully prompt you to do such.
