### ISSUE TITLE
Yo Kai watch 4 overbright world

### ISSUE THREAD

**Issue by ChiragKetchum** [yuzu-emu/yuzu#8437]
Has someone found a fix to the bug in yo kai watch 4 where the world is too bright ? 
It occasionally becomes visible while entering stores or cut scenes but for only a second then again goes to full white.  Please fix it 🙏 will be grateful

**Comment by G-Spawn** [comment]
https://github.com/yuzu-emu/yuzu/issues/6864 Closing in favor of existing issue for it. No there isn't really a solution for it that I'm aware of yet.
