### ISSUE TITLE
pokemon legends arceus crashing randomly when entering or exiting a building

### ISSUE THREAD

**Issue by piplup55** [yuzu-emu/yuzu#8438]
**To reproduce:**
enter and exit a building multiple times

**Logs:**

7 cores: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8852373/yuzu_log_7cores.txt)

4 cores: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8852379/yuzu_log_4cores.txt)

**More details:**
 - seems to be fine on anything above 4 cores (tested 4,6,12 cores)

**System Specs:**

Windows:
 - OS: Windows 10 21H1
 - CPU: AMD Ryzen 7 3700X
 - GPU: RX6600 XT
 - Memory: 48GB, Pagefile: 3.63GB
 - GPU Driver: 22.5.2

Linux: N/A, didn't test linux

**Comment by solarmystic** [comment]
Reproduced with an i5-12400F, NVIDIA GTX 1070TI system running on Windows 10 21H1.

Affinity set to 4 cores:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8852405/yuzu_log.txt)

Couldn't reproduce on thread counts higher than 6 as stated above.

**Comment by Superstarlife** [comment]
This seems to be causing problems in games like Pokemon Arceus, at least on the steam deck, in the mainline version 985 I can play for hours without crashing or freezing problems

**Comment by WillBillDillPickle** [comment]
did you have enough ram?

**Comment by G-Spawn** [comment]
![image](https://user-images.githubusercontent.com/23653025/174221978-59d3e150-4f42-4d3c-9d41-d0f5d0d9781d.png)
Yes they do have enough memory :p

**Comment by piplup55** [comment]
i would also like to point out aswell i put my system specs in the issue
![image](https://user-images.githubusercontent.com/100526773/174285059-5de3ae54-c901-4159-808c-c4bf465823d4.png)

**Comment by piplup55** [comment]
can reproduce the issuse on yuzu 1233 [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9998737/yuzu_log.txt), can't reproduce the issue on yuzu EA 3118

**Comment by piplup55** [comment]
can't reproduce on yuzu 1392/yuzu Early Access 3497, will reopen if the issue is reported again
