### ISSUE TITLE
Yuzu weird graphical glitches

### ISSUE THREAD

**Issue by boofiboi** [yuzu-emu/yuzu#8442]
Yuzu worked fine in the afternoon today, except for very laggy games.
I was directed on the discord to try the AppImage, so I did.

Now every version of yuzu contains these annoying graphical glitches, and I am not the only one with these.

![image](https://user-images.githubusercontent.com/79476279/172712192-ba2494cc-290d-4908-b2e8-7ce1cf95dadf.png)
A picture of what it looks like.
![image](https://user-images.githubusercontent.com/79476279/172712256-b1e952b4-fe7b-4a61-aa88-85c6b5787b11.png)
A close up to reveal even more.

This is on RADV + AMDVLK
![image](https://user-images.githubusercontent.com/79476279/172712332-f5f3c27d-cf95-41c2-8ad4-24badf7a77c3.png)
This green on the rock shouldnt be here.

Also running yuzu with RADV doesnt even work for me.

**Comment by piplup55** [comment]
i can confirm this bug to happens on the appimage doesn't appear on flatpak seems to happen on mesa 22.0 and above? so might be a mesa regression

**Comment by realriccio** [comment]
Bump. This happens on my Steam Deck (both beta and non-beta SteamOS).

**Comment by boofiboi** [comment]
Using AMDVLK-pro fixes these issues, and the games run even a lot faster!
