### ISSUE TITLE
Hyrule Warriors AOC - Crash on Cutscene - Final Mission - Yuzu 1049

### ISSUE THREAD

**Issue by mikegonzalez2k** [yuzu-emu/yuzu#8452]
Hyrule Warriors Age of Calamity crashes on the final mission "The Future of Hyrule" on Yuzu 1049.

Repro steps:

On Yuzu 1049 once the game is beaten select the Blood Moon quest "The Future of Hyrule".
Play through the level until the final fight with Calamity Ganon.
During that fight there is a cutscene to weaken him.
The crash should occur during cutscene.
Initially you will hear audio only and the video will cut to black.

This mission could be completed on previous versions of Yuzu without crashing.

Here is the log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8885287/yuzu_log.txt)

**Comment by benderscruffy** [comment]
is this still an issue ???
