### ISSUE TITLE
Allow remote connections to GDB stub

### ISSUE THREAD

**Issue by nikvoid** [yuzu-emu/yuzu#8453]
Currently GDB server seems to accept connections only from localhost, as I cannot connect from the remote machine.

**Comment by german77** [comment]
This was done intentionally as having ports open would result in a security risk.

**Comment by nikvoid** [comment]
> You can always edit the code to allow remote connections.

I`m doing this now.

> This was done intentionally as having ports open would result in a security risk.

Yeah, but this should be an option. Lots of people have something like router that don`t allow connections from outside world, so in most cases connections just limited to a local network.
