### ISSUE TITLE
Diablo 3 update breaks the game meanwhile base game is working fine.

### ISSUE THREAD

**Issue by damacaner** [yuzu-emu/yuzu#8466]
Log file from past [844.019051] line, where I try to launch the game.
[It just goes on like this for the next 100 lines.](https://github.com/yuzu-emu/yuzu/files/8908828/ihavefinalexamtomorrow.txt)

Base-game (title-ID => 01001B300B9BE000) works fine DLC's (versions 100,101,102) works fine but update 2.7.2.79496 straight breaks the game and game doesn't launch.

Graphic settings and everything is the same while launching the base game and launching the update.

**Comment by german77** [comment]
Please provide the full log. This error just means something went really wrong

**Comment by damacaner** [comment]
[Uploaded. Didnt launch any game after trying to launch D3.](https://github.com/yuzu-emu/yuzu/files/8910462/yuzu_log.txt)

**Comment by damacaner** [comment]
Log file is over 25 mb.
https://we.tl/t-YOPc9cjkxa

**Comment by german77** [comment]
> Log file is over 25 mb. https://we.tl/t-YOPc9cjkxa
> 
> Didnt launch anything after trying D3.

Zip the file and upload it. They usually compress really well. Your link doesn't redirect me to any download

**Comment by damacaner** [comment]
[Seems like it is not done](https://github.com/yuzu-emu/yuzu/files/8912886/yuzu_log.txt)

When game is updated, base-game and update is not using the same files, using rerolled another save file in another folder.

**Comment by german77** [comment]
Piracy is not allowed
