### ISSUE TITLE
yuzu segfault when multicore is disabled

### ISSUE THREAD

**Issue by A-w-x** [yuzu-emu/yuzu#8471]
cannot boot any game, mainline

[dump.log](https://github.com/yuzu-emu/yuzu/files/8918652/dump.log)

i7-1165g7, 16gb ram
archlinux

**Comment by A-w-x** [comment]
updated, same specs as my other issues, need other info?

unless i'm the only with this crash, it does not seem something that require support but just a bug.

**Comment by G-Spawn** [comment]
Are you using Wayland per chance?

**Comment by A-w-x** [comment]
no, xfce4 xorg

**Comment by A-w-x** [comment]
updated to new release, issue gone
