### ISSUE TITLE
Mario strikers gets stuck on black screen/loading screen, or crashes at random time

### ISSUE THREAD

**Issue by dF-Ex** [yuzu-emu/yuzu#8481]
hello, mario strikers just came out... and for some resason it either waits on loading screen or crashes at random time from 10 to 20 minutes/Seconds i dont even know what the problem is with it, but if u know how to fix it next release please do thx

**Comment by G-Spawn** [comment]
this is an issue page not personal pleading for fixes. it wont happen anytime soon to fix strikers. the game is new. even with mods it has issues.

**Comment by G-Spawn** [comment]
Closing as you were not able to follow issue template. Feel free to reopen when you can provide everything needed.
