### ISSUE TITLE
real ring-con in fitness ring adventure

### ISSUE THREAD

**Issue by taifengdian** [yuzu-emu/yuzu#8489]
I have been paying attention to the use of real ring con in Yuzu. It seems that german77 has implemented this function, but it has not been integrated into the released version. I want to know what the problem is?

**Comment by fedeshoker** [comment]
Hi! Any updates for real ring con ? Thank you

**Comment by taifengdian** [comment]
it's looks like no progress ！

**Comment by HisNoodlyServant** [comment]
Also going to join in on the request. Be cool as heck to be able to use my Ring Fit with the Deck.

**Comment by taifengdian** [comment]
chech this post every week

**Comment by Gordoras** [comment]
I would really appreciate an update :)
It would really be great to use the real ring con and play the game how it is supposed to be played.

**Comment by taifengdian** [comment]
sad

**Comment by pktiuk** [comment]
> The problem is that it needs a custom joycon driver. I have made a driver but it's purely experimental. The ring does work there but the feature as such needs to be polished so it doesn't crash yuzu or the driver under any circumstance


Maybe it would be good to just put it into some test/nightly release to let people test and break it (and collect logs) to know where it fails.

**Comment by german77** [comment]
The driver is ready and needs to be tested. Ping me on discord(Narr the reg) if you want to join to the testing

**Comment by dario7218** [comment]
Can i join the testing?

**Comment by pktiuk** [comment]
Unluckily currently I am not able to test it, but I see you already have another volunteer. :)

**Comment by dario7218** [comment]
Is the testing going on?

**Comment by german77** [comment]
Yes. about 7 have tested. Original joycons and ring work perfectly. 3rd party not at all. Right now I'm finishing the code to add it to EA

**Comment by nahlahman** [comment]
I'm really excited about this feature. Thank you for working on it!

**Comment by taifengdian** [comment]
what a wonderful news, about one year waiting is valuable. Thanks very much to german77's great work.

**Comment by netrunner7** [comment]
+1 !!!

**Comment by taifengdian** [comment]
@german77 I have tried the early access 3246 version and couldn't get the ring-con work. I don't know if the version doesn't get ready for ring-con or I operated somewhere wrong?  could you show me  some guide. thank you very much.

**Comment by german77** [comment]
Ringcon requires a very specific setup to work properly. Logs will print whatever the ring was detected or not. 

-Custom driver enabled.
-Player 1 as right joycon. With right joycon mapped.
-Player 2 as dual joycon. With left joycon mapped.
-Ring connected before booting the game

**Comment by SaiKai** [comment]
this setup does not seem to work for me, even with the newest EA version. 
the ringcon is not detected at all (no info in logs), even though the joycon is inserted into it.

Custom driver is enabled.
joycon configuration is exactly as described.

Is there a setup step I am missing currently?

**Comment by german77** [comment]
I'm going to add a test button for making this easier to setup

**Comment by german77** [comment]
Next EA will have this option under ring configuration. Configure your controller first then click the test button. If an error occurs a dialog explaining why will pop up. If all is good the window will start displaying the raw values from the ring.

![image](https://user-images.githubusercontent.com/5944268/209576486-29ba5e98-7a00-4e5e-9512-2c7b5afce1c7.png)

**Comment by taifengdian** [comment]
test again , doesn't find my ring-con. I will borrow my friend's ring-con and test again.

**Comment by fedeshoker** [comment]
Hey! Try to update your joycons. I had de same problem and after updated works

**Comment by german77** [comment]
Oh right. That's another thing I could check before even attempting to use the ring controller.

**Comment by binarycounter** [comment]
Adding to this: I have the same issue with the ring not being detected. 
I've updated the joycons to firmware v4.21 (according to Joycon Toolkit) and it does not help. 
[This program](https://github.com/ringrunnermg/Ringcon-Driver) is able to detect my ring-con and map it to an axis without issue, so I am very sure it's not a problem with my hardware.

**Comment by taifengdian** [comment]
I can see the raw data in configure when update firmware of joycons. but in game can't recognise the ring. and when I open the configure again i need enable the ring control again to read the raw data. It's seems that the ring controller's configure can't be saved.

**Comment by chikatana** [comment]
I got 2 pairs of joy cons just for yuzu but I do not own any switch. How can I update the firmware without connecting it to switch?

**Comment by nahlahman** [comment]
> I've got 2 pairs of joy cons just for yuzu but I do not own any switch.

You should probably take that question elsewhere or frame the question in a different way, because Yuzu developers don't offer any support to piracy and don't want to be associated with it.

**Comment by german77** [comment]
Due to safety reasons. Basically I don't want to make yuzu responsible on bricking your joycon. Firmware updates and editing any calibration value is not supported. The only way to update firmware will be with a switch console.

Also there's a small bug when detecting the ring on ringfit. I will fix it soon

**Comment by chikatana** [comment]
I asked my friend to update the joy cons firmware for me.
I run early access build 3307 and it can detect the ring push & pull now.
However, after I press OK and fire up Ring Fit Adventure v1.2
the game doesn't seems to respond to the ring controller.
I went back to "Configuration" -> "Controls" -> "Advanced" -> "Ring Controller" -> "Configure"
and found that "Ring Sensor Value" stay "Not connected"
No matter how many times I enable it and it will be disconnected after passing "OK"

**Comment by fedeshoker** [comment]
> I asked my friend to update the joy cons firmware for me. I run early access build 3307 and it can detect the ring push & pull now. However, after I press OK and fire up Ring Fit Adventure v1.2 the game doesn't seems to respond to the ring controller. I went back to "Configuration" -> "Controls" -> "Advanced" -> "Ring Controller" -> "Configure" and found that "Ring Sensor Value" stay "Not connected" No matter how many times I enable it and it will be disconnected after pressing "OK"

Hey! on 3308 works great. Try it.!

**Comment by chikatana** [comment]
![Snap2](https://user-images.githubusercontent.com/65479211/212447657-01786c0d-2daa-4a90-afab-a351bb7439ec.png)
![Snap3](https://user-images.githubusercontent.com/65479211/212447660-302f90bb-6603-40fb-b900-8e160c2b3730.png)
![Snap5](https://user-images.githubusercontent.com/65479211/212447661-44c0c517-30db-43eb-a049-0590c7a9eba9.png)
I tried 3308 and it is the same. Any idea?

**Comment by chikatana** [comment]
Is there any log file I can provide so that german77 can get a better understanding about what is going on?

**Comment by german77** [comment]
I have pushed the latest fixes but it will be on EA 3309+. I might need to change the behavior but the tester should only be used while the game is not running. Because when the game is running it actually sets the wrong configuration and the ring will stop working until the game is restarted.

I also fixed the dual joycon display. Now it will remember dual joycon properly. This needs remapping as old config is now invalid.

This config seems to work well for me with the latest changes. Player 1 and 2 as dual joycon. Only player 1 connected.

**Comment by chikatana** [comment]
Thanks for your hard work

**Comment by binarycounter** [comment]
Just wanna update on this: The latest [artefact](https://github.com/yuzu-emu/yuzu/actions/runs/3919258581) from the [PR](https://github.com/yuzu-emu/yuzu/pull/9492) seems to have fixed the issue for me. The game now recognises the ring without issue. I'm still having trouble with the IR camera for the pulse sensing and some of the help menus seem to softlock the game, but that's completely unrelated to this. 
Thank you so much for putting the work into this!

**Comment by yuanqiuye** [comment]
Wanna mention one issue: With EA 3309, Joycon-R will disconnect very often (another game like super smash bro have no problem), and when reconnect it, ring sensor value become not connected, and need to reopen the game.
Once again thanks for your hard work, finally can play Ring fit with my computer, without you it couldn't be done!

**Comment by chikatana** [comment]
I can't believe It finally works for me on EA 3309. I purchased the ring and joycons more than a year ago just sit and waiting for a working software. And it finally arrives. Thanks.

**Comment by german77** [comment]
> Wanna mention one issue: With EA 3309, Joycon-R will disconnect very often 

This could certainly happen if you don't have a good connection. I suggest to disable rumble.
I need remove a hack where yuzu thinks the ring is always connected. So the game automatically request to turn the ring back on without needing a restart.

**Comment by taifengdian** [comment]
The ring con finally get worked after use  a fresh install . Thanks very much to German77 's  wonderful work. 
There are some little bug in the ring fit game, can't creat new user ,can't  get in setup menu in adventrue mode. hope the bugs will be fix soon.

**Comment by yuanqiuye** [comment]
> > Wanna mention one issue: With EA 3309, Joycon-R will disconnect very often
> 
> This could certainly happen if you don't have a good connection. I suggest to disable rumble. I need remove a hack where yuzu thinks the ring is always connected. So the game automatically request to turn the ring back on without needing a restart.

Surprisingly, disable rumble really fix the disconnected issue! But it will lose lots of fun cuz ring fit's rumble is so good on the original Switch version, maybe it's Linux's problem? I'm now using Steam OS 3.4 with Steam Deck

**Comment by german77** [comment]
Not linux issue. Is a quality of signal issue. Rumble saturates the bluetooth protocol and starts missing packages

**Comment by nahlahman** [comment]
> > > Wanna mention one issue: With EA 3309, Joycon-R will disconnect very often
> > 
> > 
> > This could certainly happen if you don't have a good connection. I suggest to disable rumble. I need remove a hack where yuzu thinks the ring is always connected. So the game automatically request to turn the ring back on without needing a restart.
> 
> Surprisingly, disable rumble really fix the disconnected issue! But it will lose lots of fun cuz ring fit's rumble is so good on the original Switch version, maybe it's Linux's problem? I'm now using Steam OS 3.4 with Steam Deck

In my experience, the joy-con signal is very weak. I couldn't have a proper motion control experience until I got a bluetooth adapter with an antenna attached (very powerful signal). Now the connection is perfect.

**Comment by mjoach** [comment]
Was excited to see the progress and decided to try with 3334 on Windows. Got ringcon recognized indeed, but I wasn't able to start the adventure mode and got stuck at strengh calibration screen (showing "Press it now" if I recall). What happens is while the game responds to squeezing the ringcon, some incorrect samples (perhaps zeros) are being picked up intermittenly, so the ringcon on screen keeps randomly flipping between being squeezed and fully open (sometimes many times per second). Since the game expects you to squeeze for a certain time, this makes it impossible to progress beyond this screen. Getting closesr to the BT transeiver and turning off vibrations didn't seem to make an impact. Is it something anyone else encountered? In any case, huge thanks for the progress on this issue!

**Comment by fedeshoker** [comment]
> Was excited to see the progress and decided to try with 3334 on Windows. Got ringcon recognized indeed, but I wasn't able to start the adventure mode and got stuck at strengh calibration screen (showing "Press it now" if I recall). What happens is while the game responds to squeezing the ringcon, some incorrect samples (perhaps zeros) are being picked up intermittenly, so the ringcon on screen keeps randomly flipping between being squeezed and fully open (sometimes many times per second). Since the game expects you to squeeze for a certain time, this makes it impossible to progress beyond this screen. Getting closesr to the BT transeiver and turning off vibrations didn't seem to make an impact. Is it something anyone else encountered? In any case, huge thanks for the progress on this issue!

Hey! You have to enable direct JoyCon driver in Controls -> Advanced. Restart Yuzu and select Dual Joycons in Player1 and Player2, P2 Disconnected 
![Captura de pantalla 2023-01-28 090639](https://user-images.githubusercontent.com/105258627/215265653-901bab79-46ba-47fe-a6b8-4132d6f8e713.jpg)
![Captura de pantalla 2023-01-28 090701](https://user-images.githubusercontent.com/105258627/215265655-a18d775f-b6c7-4fe7-8b5e-f68b4ad9cebe.jpg)

**Comment by german77** [comment]
mjoach when it looks random is probably due reading motion data instead of the ring. This happens when the joycon wasn't able to configure properly or another thing changed the config. Follow what fedeshoker mentioned

**Comment by mjoach** [comment]
german77 and fedeshoker, thanks for pointing me in the right direction. I gave it another try and it seems the problems was caused by me incorrectly assuming we are supposed to detect and assign Pull/Push axis in the ring controller panel after enabling ringcon, whereas I think they are meant to be mutually exclusive sources of input. So as a result I was mixing up signals from Axis 100 and ringcon driver. Perhaps this is something that could be clarified or directly prevented in the GUI at a later time. In any case, awesome work, thanks again!

**Comment by hlebushekhub** [comment]
hey guys! your work is amazing. playing Ring Fit right now on yuzu and it's blessing really. One question, is there anything I can do with micro slowdowns on exercises? They are not work with fullspeed which is the only problem I ran into

**Comment by gaowanliang** [comment]
When using Joycon direct drive and clicking `Enable`, the software prompts the `Unexpected driver result : 8`, what is the error?

**Comment by german77** [comment]
8 = NoDeviceDetected. Basically you haven't mapped the joycon to player 1

**Comment by nahlahman** [comment]
Looks like there aren't any Ring-con updates in the public build of this month. Hopefully in the next one!

**Comment by gaowanliang** [comment]
It's not related to driving the fitness ring, but I'd like to ask if there's a reason why it gets stuck every time I press the left button to open the settings.

**Comment by german77** [comment]
Settings a special web applet mode. Which we currently don't support, so the emulator softlocks. Avoid using it. Not sure when it will be implemented.

**Comment by sieluccakeine** [comment]
> Settings a special web applet mode. Which we currently don't support, so the emulator softlocks. Avoid using it. Not sure when it will be implemented.

thanks german77 for all your hard work! i have it working now, but for some reason the rotations and movement of the motion controls are mirrored? any suggestion

**Comment by german77** [comment]
Ring buttons should face your face. That will give you correct rotations

**Comment by sieluccakeine** [comment]
> Ring buttons should face your face. That will give you correct rotations

im embarrased. lol

**Comment by sebasx2112** [comment]
Excuse me. Does it work with third-party Ringcon today?

**Comment by vshijiav** [comment]
> Settings a special web applet mode. Which we currently don't support, so the emulator softlocks. Avoid using it. Not sure when it will be implemented.

Is there any other method we can change the settings? Currently is seems no way to adjust exercise level

**Comment by ClassicalTrekkie** [comment]
Anyone know if this is pushed out to the main branch? Haven't been able to get the Ring-Con working.

**Comment by nahlahman** [comment]
I think it's all there except for the settings (which hasn't been implemented anywhere). 

I realized recently that although the installer kept telling me I was fully updated, I had to do a fresh install to properly get all the latest features (including for the ring-con).

**Comment by ClassicalTrekkie** [comment]
So I see the Ring-Con controller in the advanced settings.  Enable Ring Input just give me "unexpected result 8".  Have tried P1 Dual con + P2 Dual con but disconnected, the variation in the "configure Ring Controller", and the stuff above. Also tried reinstalling and nope. :/ What control variation are you guys using?  Oh and are you saying it isn't pushed out yet just the settings are there. Thanks.

**Comment by vshijiav** [comment]
I have to go to advanced settings and enable ringcon each everytime I boot up yuzu, Is there any solution to this?

**Comment by nahlahman** [comment]
That seems wrong. Maybe you have something set to read-only? I'd recommend a clean install.

**Comment by ClassicalTrekkie** [comment]
Thanks nahlahman. That was it!

**Comment by bechigi1** [comment]
Is it only possible to run on the EA version?

**Comment by bechigi1** [comment]
I bought a genuine Joycon now. Should Ring Fit Ring be genuine too? Can I use a compatible product?

**Comment by fedeshoker** [comment]
> I bought a genuine Joycon now. Should Ring Fit Ring be genuine too? Can I use a compatible product?

Yes! i use a 3rd party Ring and it works great.
Remember to update the joycons in a real switch.

**Comment by nahlahman** [comment]
Sadly I've spent hours trying to get this to work to no avail. 

I've followed the instructions and I have original fully updated joy-cons and an original ring-con, but the game won't recognize ring pushes/pulls. The tool does perfectly recognize pushes/pulls, but as others reported earlier, it seems like it doesn't get saved. If I close the tool and open it again, I have to enable it once again. But it just won't stick.

Reinstalling Yuzu hasn't worked either.

**Comment by german77** [comment]
Things to get the ring working.

- Fully updated joy-cons
- Ring attached to right joycon
- Map player 1 with right joycon both physical and emulated
- Map player 2 with left joycon physical and dual joycon emulated.
- Save config
- Check that ringcon is enabled on advanced controller config and use the tester to very it can pull values
- Close config and run the game
- Never open the config window while the game is running. That will screw up the ring detection on the game.

**Comment by RyenRaftery** [comment]
> Things to get the ring working.
> 
> * Fully updated joy-cons
> * Ring attached to right joycon
> * Map player 1 with right joycon both physical and emulated
> * Map player 2 with left joycon physical and dual joycon emulated.
> * Save config
> * Check that ringcon is enabled on advanced controller config and use the tester to very it can pull values
> * Close config and run the game
> * Never open the config window while the game is running. That will screw up the ring detection on the game.

Hello, @german77! I'm on version 1440.

<img width="624" alt="image" src="https://github.com/yuzu-emu/yuzu/assets/18535319/cf89236f-ee9e-47cb-8377-91d5522ddca0">
<img width="626" alt="image" src="https://github.com/yuzu-emu/yuzu/assets/18535319/7c5335a4-8e42-4e31-91dc-4d0d61b6e198">
<img width="436" alt="image" src="https://github.com/yuzu-emu/yuzu/assets/18535319/57b8eaa3-9451-4c34-9f1d-f40918f6958f">
<img width="174" alt="image" src="https://github.com/yuzu-emu/yuzu/assets/18535319/0c15a836-9499-44d7-afad-1bebdba4a5e7">

Problem is, each time I click OK after I finish testing the Ring-Con driver for push/pull values, it goes back to 'disconnected'. How can I rectify this and finally play Ring-Fit Adventure on my PC? Thank you so much for helping out!

**Comment by bechigi1** [comment]
I bought a genuine Ringcon and it works really well.
But do you have to reconnect batteryjoy?
After rebooting, the device must be removed and reconnected.

**Comment by RyenRaftery** [comment]
> Betterjoy doesn't have support for the ring. In fact it conflicts with yuzu and will break support for the ring. Please don't use any other 3rd party program.
> 
> I decided to invest time in reworking this feature so the game can actually know when the ring is actually connected.

Hi, @german77! How has progress been going?

**Comment by Antmortician** [comment]
> Things to get the ring working.
> 
>     * Fully updated joy-cons
> 
>     * Ring attached to right joycon
> 
>     * Map player 1 with right joycon both physical and emulated
> 
>     * Map player 2 with left joycon physical and dual joycon emulated.
> 
>     * Save config
> 
>     * Check that ringcon is enabled on advanced controller config and use the tester to very it can pull values
> 
>     * Close config and run the game
> 
>     * Never open the config window while the game is running. That will screw up the ring detection on the game.

I think you forgot to mention that player 3 is the right joy con mapped as dual joycons. Or at least that seems to be how it finally recognised ring inputs ingame for me.

**Comment by german77** [comment]
Player 3 is never used. This player is created because you opened the config. It's actually a bug. Player 2 is dual joycon with just the left joycon connected. But our UI doesn't handle that so it saves as two joycons on player 2 the game then proceeds to split the controllers again and now you have 3 players. Open the config again and now you have 4 and so on...

Hence why the last point is really important. Never open the config window while the game is running. I'm still working on the rewrite, that takes time, is not something I can pull off in a week. This will aim to fix inaccuracies like these and actually allow the game to report if the ring is functional or has been disconnected mid game.

**Comment by Kurixu** [comment]
> Things to get the ring working.
> 
> * Fully updated joy-cons
> * Ring attached to right joycon
> * Map player 1 with right joycon both physical and emulated
> * Map player 2 with left joycon physical and dual joycon emulated.
> * Save config
> * Check that ringcon is enabled on advanced controller config and use the tester to very it can pull values
> * Close config and run the game
> * Never open the config window while the game is running. That will screw up the ring detection on the game.

Hello! I followed these steps. But when I try to configure the ringcon, it wont recognize my push/pulls. Also, when I enable ring input, the ring sensor value changes depending on the motion of my ringcon (I assumed that number is for how hard you pull/push the ringcon, since it doesn't make much sense to represent 3d motion with one number)
![ringcon](https://github.com/yuzu-emu/yuzu/assets/54726974/c38c224f-3a37-4326-9a8e-0e549318ddb7)

Now, when I actually boot up the game...
![ringcon1](https://github.com/yuzu-emu/yuzu/assets/54726974/1eaa5a7e-f9b4-4d21-b45e-dc86bca5dff5)
I managed to get past this section by using the default mapping for pull and push (keyboard A and D). 

When I reach this part...
![ringcon2](https://github.com/yuzu-emu/yuzu/assets/54726974/cad0590f-187c-41eb-aaa5-5932e5c914bc)
...the ringcon on screen follows the motion of my physical ringcon. However, the strength value changes depending on how I tilt my ringcon. The strength value doesn't change when I push/pull my ringcon. The strength value flashes -99.99 or 99.99 for a split second when I push A or D on my keyboard.

The left joycon on my leg seems to work just fine.

This is the description of my issue. I hope you can help me. 

Thank you so much for your hard work.

**Comment by Kurixu** [comment]
Update: 
I did this mapping: 
Map player 1 with right joycon BOTH physical and emulated
Map player 2 with dual joycons BOTH physical and emulated

and it fixes the issue of the motion registering as push or pulls. 
Yuzu still can't recognize the pulls/ push on my physical ringcon tho.

**Comment by nahlahman** [comment]
> Update: I did this mapping: Map player 1 with right joycon BOTH physical and emulated Map player 2 with dual joycons BOTH physical and emulated
> 
> and it fixes the issue of the motion registering as push or pulls. Yuzu still can't recognize the pulls/ push of my physical ringcon tho.

Player 2 should not both be dual. One of the options should be the left joy-con and the other dual.

**Comment by Kurixu** [comment]
> > Update: I did this mapping: Map player 1 with right joycon BOTH physical and emulated Map player 2 with dual joycons BOTH physical and emulated
> > and it fixes the issue of the motion registering as push or pulls. Yuzu still can't recognize the pulls/ push of my physical ringcon tho.
> 
> Player 2 should not both be dual. One of the options should be the left joy-con and the other dual.

Yes that is what I did at first. 
Map player 1 with right joycon both physical and emulated
Map player 2 with left joycon physical and dual joycon emulated.

However, as I mentioned in my first comment, this makes the game recognize the motion of my ringcon as push or pull.

**Comment by nahlahman** [comment]
> > > Update: I did this mapping: Map player 1 with right joycon BOTH physical and emulated Map player 2 with dual joycons BOTH physical and emulated
> > > and it fixes the issue of the motion registering as push or pulls. Yuzu still can't recognize the pulls/ push of my physical ringcon tho.
> > 
> > 
> > Player 2 should not both be dual. One of the options should be the left joy-con and the other dual.
> 
> Yes that is what I did at first. Map player 1 with right joycon both physical and emulated Map player 2 with left joycon physical and dual joycon emulated.
> 
> However, as I mentioned in my first comment, this makes the game recognize the motion of my ringcon as push or pull.

Oh, I see. That's a tough one. Could be a bug, could be a physical issue with the ring-con. My advice would be to reinstall yuzu, which has helped me with several issues before. And if you have access to another ring-con, it may be worth trying the other one.

Because of all the possibilities of what could be wrong, I don't think you can count on the dev to look into it unless other people report the same issue.

**Comment by Kurixu** [comment]
> > > > Update: I did this mapping: Map player 1 with right joycon BOTH physical and emulated Map player 2 with dual joycons BOTH physical and emulated
> > > > and it fixes the issue of the motion registering as push or pulls. Yuzu still can't recognize the pulls/ push of my physical ringcon tho.
> > > 
> > > 
> > > Player 2 should not both be dual. One of the options should be the left joy-con and the other dual.
> > 
> > 
> > Yes that is what I did at first. Map player 1 with right joycon both physical and emulated Map player 2 with left joycon physical and dual joycon emulated.
> > However, as I mentioned in my first comment, this makes the game recognize the motion of my ringcon as push or pull.
> 
> Oh, I see. That's a tough one. Could be a bug, could be a physical issue with the ring-con. My advice would be to reinstall yuzu, which has helped me with several issues before. And if you have access to another ring-con, it may be worth trying the other one.
> 
> Because of all the possibilities of what could be wrong, I don't think you can count on the dev to look into it unless other people report the same issue.

I see. Thank you so much for your help.  One last favor tho...
Can you show me what the Virtual Ring Sensor Parameters is supposed to look like if everything is working properly?

Mine looks like this:
![ringcon3](https://github.com/yuzu-emu/yuzu/assets/54726974/2afde477-cfc7-4759-b882-e9186236683d)

**Comment by nahlahman** [comment]
The Virtual Ring Sensor Parameters look the same for me. But as I understand it, they are not important. It's not the virtual ring you want to get working (which mimics the ring-con by assigning buttons to its functions), but the Direct Joycon Driver below it (using your real ring-con).

The Ring Sensor Value should be close to zero when you're not pressing/pulling on it, which yours is. When pressing hard, it should go all the way to 1.000. And when pulling hard, it should go to -1.000.

**Comment by gaowanliang** [comment]
> Settings a special web applet mode. Which we currently don't support, so the emulator softlocks. Avoid using it. Not sure when it will be implemented.

Can modify the settings indirectly by providing a `cheat codes`, I think this may be easier to achieve.

**Comment by Ju5raj** [comment]
Anyone else have crashes? I crash when doing the victory pose and whenever i go into "Health and Safety" at the starting menu. The infrared sensor didn't work either.

**Comment by nahlahman** [comment]
> Anyone else have crashes? I crash when doing the victory pose and whenever i go into "Health and Safety" at the starting menu. The infrared sensor didn't work either.

Yeah, initially I was able to get past the victory pose, but more recently I've been crashing there consistently. The infrared sensor did not work for me either. I don't know about the health and safety menu, but that may use some web applet and is probably a very low priority.

I didn't have enough time on my hands to look into the crashes, but my initial guess is that it can be fixed by reverting to a previous yuzu version, or by changing some settings. I also think it's an especially heavy shader event, because even when it was working my first victory pose was super stuttery. Unfortunately I lost my shaders at some point.

**Comment by german77** [comment]
I will take a look today

**Comment by german77** [comment]
also locking due of topic of this issue. Please open new ones as I don't see closed issues.
