### ISSUE TITLE
[Splatoon 2] Amiibo do not work correctly and cannot be saved to

### ISSUE THREAD

**Issue by Nicolas-GE** [yuzu-emu/yuzu#8493]
issue:
in Splatoon 2, tapping an amiibo works but trying to save to an amiibo does not, restricting the ability to use the amiibo, as it needs to be registered to work

steps to reproduce:
1.get an amiibo .nbt file
2.go up to the amiibo box in the plaza
3.scan an amiibo
4.after talking to the amiibo, scan it again

Expected result: the amiibo is saved and allows gear to be obtained
Actual result: ![image](https://user-images.githubusercontent.com/42648527/175269391-62b79687-c89c-45b5-a829-02295ea46bca.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8966048/yuzu_log.txt)

**Comment by german77** [comment]
Saving data to an amiibo is not implemented yet.

**Comment by german77** [comment]
You should be able to save data on splatoon 2 on latest mainline
