### ISSUE TITLE
UI - Amibo Not Supported - Metroid Dread - Yuzu 1064

### ISSUE THREAD

**Issue by mikegonzalez2k** [yuzu-emu/yuzu#8496]
When attempting to add an Amibo to Metroid Dread I get the message Amibo Not Supported.

![image](https://user-images.githubusercontent.com/6504617/175546811-e044edd4-08f4-4e9d-b800-dd004578c156.png)

Log

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8976556/yuzu_log.txt)

**Comment by german77** [comment]
Log seems like it loaded just fine. Are you sure thee amiibo is valid on a real switch?

**Comment by german77** [comment]
Just tested seems like it's indeed not working. I will take a look in the following days

**Comment by yoyotam3** [comment]
can confirm this still isnt working

**Comment by Zeroxdz** [comment]
I have the same problem, but with Super Mario Odyssey, loading the amiibo .bin file fails and a box appears saying: "Error loading Amiibo data" "Unable to load Amiibo data."
![Yuzu error amiibo SMO](https://user-images.githubusercontent.com/113661952/190567407-2cd7a183-ee2f-4ed0-944f-90bbc4127b2d.png)

**Comment by german77** [comment]
SMO amiibos definitively work make sure you have dumped a real amiibo, pre generated ones don't work with yuzu.
