### ISSUE TITLE
Can't play any game with R9 360

### ISSUE THREAD

**Issue by kfg81** [yuzu-emu/yuzu#8497]
CPU: Intel i3-8100
RAM:32G
OS:Ubuntu 20.04/22.04
Display Card: UHD 620/ AMD R9 360（Dell OEM/ Tobago/ 1002-665f）
I try to run many games with R9 360，yuzu can't start any one and than FC。
Try to run games with UHD 620, It only can be "run"。
How to fix it? thank you very much.
![CoreCtrl](https://user-images.githubusercontent.com/12681019/175565128-fe1b8f18-2ac4-41d3-959d-a10d53682dd3.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8977209/yuzu_log.txt)

**Comment by G-Spawn** [comment]
This isnt a support forum. Please ask on the yuzu discord or citra forum for support.
