### ISSUE TITLE
Super Zangyura - US version blackscreens on start; JP version loads and plays fine

### ISSUE THREAD

**Issue by boomercore** [yuzu-emu/yuzu#8498]
Issue has been around since the game's release a few months ago.  From builds at that point to the present.  Currently using 2800.  Same case on two different machines, one Nvidia 3060 + Ryzen 5800X and another an Nvidia 1060 + i7 8750h laptop.  Both Win10.  I would guess this wouldn't be too hard to solve as the JP version runs, but I wouldn't know for sure.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8981682/yuzu_log.txt)

**Comment by n1ghttrap** [comment]
The same US ROM runs in Ryujinx so I don't think it's (too) bad of a dump.

**Comment by german77** [comment]
Needs audio changes #7972

**Comment by benderscruffy** [comment]
this goes ingame now no problems so far
can be closed
