### ISSUE TITLE
Hyrule Warriors: AOC – Shadow Bug (Regression)

### ISSUE THREAD

**Issue by INFINITY99K** [yuzu-emu/yuzu#8505]
### **Description**
There is a shadow bug in the game that I didn't encounter before.
You can notice this very clearly in the opening mission, where the shadows appear as if they were clipping through each other.

### **Demonstration**
https://user-images.githubusercontent.com/73315805/175805621-51f167b5-297c-436c-8188-2e8263b32e9a.mp4

Edit: For some reason, the camera behaves like this, but only in OBS, not while I am playing.
yuzu EA build: 2801
LOG: [yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/8986193/yuzu_log.txt.old.txt)

### **System Specs**
Ryzen 7 3700X
RTX 2070 SUPER (516.40 WHQL).
16 GB RAM

**Comment by gidoly** [comment]
it is known as nvidia driver regression rather than yuzu. you can use previous triver to bypass for now

**Comment by INFINITY99K** [comment]
Thanks for the tip!

**Comment by eropse** [comment]
516.XX nvidia drivers is the problem, in hyrule warriors AOC and fire emblem warrios three hopes weird shadow bug in vulkan, rollback to 512.95 and its fine.
I hope it will be fixed soon by nvidia or by yuzu update.
thanks in advance.

**Comment by P3rf3ctXZer0** [comment]
It still has not been fixed and nvidia just released more drivers; the big issue is these drivers target games that have had crashes on DLS as well as games with fidelity issues. Are you sure this is not a regression? It feels like it. (Also greatly fixed LOD in games like modern warfare so good luck asking people to go backwards.

![u3qQ5v2 1](https://user-images.githubusercontent.com/10351221/204952713-7e7afc16-08a7-475b-8473-9c000be60207.png)

If it is a regression has anyone informed the nvidia team? They can't fix it if they don't know its broken. It's the same for any tech issue.

**Comment by P3rf3ctXZer0** [comment]
This can be closed. 
![Animation](https://user-images.githubusercontent.com/10351221/205125182-0d86ba89-762f-4d54-94f8-933b1a582739.gif)

100% no more shadow bug. 

So others can benefit I will share my settings.

### Nvidia

![3MohZ18 1](https://user-images.githubusercontent.com/10351221/205125417-8d7b4cac-0805-4d2f-a64e-5954652ab117.png)

![U8e7MOT 1](https://user-images.githubusercontent.com/10351221/205125496-c0b304a3-4b4c-4890-97d2-7764e7158040.png)

![kn6G39N 1](https://user-images.githubusercontent.com/10351221/205125586-12df34a2-bdc3-42ef-9a41-41066b70aea7.png)

![jRxnZ2W 1](https://user-images.githubusercontent.com/10351221/205125714-18e5a87e-ca51-48c2-b0b8-67ee2130f93e.png)

### Yuzu EA 3172

![mVfOApx 1](https://user-images.githubusercontent.com/10351221/205125912-05904cb0-0503-445c-8f8e-a5cf81d53b2e.png)

![vsiGM6d 1](https://user-images.githubusercontent.com/10351221/205125986-060caf79-80e8-42e9-a092-83e265a1ca36.png)

![VPBGDKc 1](https://user-images.githubusercontent.com/10351221/205126154-3bf7888a-5a91-4739-82d7-8b1db66d82e6.png)

![L7WT9MG 1](https://user-images.githubusercontent.com/10351221/205126248-7d5c4866-518c-45f6-ae6b-622592816678.png)

**Comment by gidoly** [comment]
fixed with lastest 527.37 nv driver
