### ISSUE TITLE
Feature Request: The ability to install software from NSZ files directly to NAND.

### ISSUE THREAD

**Issue by TomTurbine** [yuzu-emu/yuzu#8515]
I understand that games can't be ran as NSZ files are compressed files.
But the ability to install stuff directly from them into NAND should be possible.

**Comment by Docteh** [comment]
I haven't heard of anyone dumping files off of their own switch and bothering with NSZ. seems like a very odd extra step to want to do. Is nsz somehow superior to 7z?

**Comment by TomTurbine** [comment]
NSZ is drastically superior to 7z when it comes to NSP files from what I have tested, it meant specifically for compressing NSP files.

And many try to backup stuff to be used later if they need it again without having to download or dump or anything like that. And being able to just install from an NSZ directly into NAND having it decompress on the fly as it goes would be a nice quality of life improvement.

**Comment by gidoly** [comment]
closing because we will not support nsz files even on future.
NSZ files has benifit of saving but since this format is most commonly used for piracy we shouln't support otherwise it will put project in to risk.
+ file system rewrite that working on will remove install file to  nand function.

**Comment by TomTurbine** [comment]
Ah, understood. Last thing I want to do is risk the project. My apologies.
