### ISSUE TITLE
MinGW compilation, patch required in SDL

### ISSUE THREAD

**Issue by psfree** [yuzu-emu/yuzu#8524]
The following patch is required to compile yuzu on mingw:

``` 
+++ /yuzu/externals/SDL/src/joystick/windows/SDL_windows_gaming_input.c
@@ -34,6 +34,11 @@
 #include <cfgmgr32.h>
 #include <roapi.h>
 
+#ifdef __MINGW32__
+#define __FIReference_1_int __FIReference_1_INT32
+#define __FIReference_1_int_get_Value __FIReference_1_INT32_get_Value
+#define __FIReference_1_int_Release __FIReference_1_INT32_Release
+#endif

struct joystick_hwdata
 {
```

This can be fixed by updating the SDL repo past https://github.com/libsdl-org/SDL/commit/d2c4d74dd0302369251dce9375b49f394e54f76a

**Comment by lat9nq** [comment]
Can you be more specific with regards to "required to compile ... on mingw"? Like do you have issues using MSYS2, or is this for cross-compiling on some system other than Fedora or Arch Linux? Or is this resolving some runtime issue? Asking because we regularly check compiling yuzu on MinGW with and without the bundled SDL2 sources.

**Comment by psfree** [comment]
Using msys2 on windows starting from fresh and following the Building For Windows steps listed.

`[ 51%] Building CXX object externals/dynarmic/src/dynarmic/CMakeFiles/dynarmic.dir/frontend/A64/translate/impl/floating_point_conditional_compare.cpp.obj
[ 51%] Building C object externals/SDL/CMakeFiles/SDL2-static.dir/src/haptic/windows/SDL_dinputhaptic.c.obj
C:/msys64/home/USERNAME/yuzu/externals/SDL/src/joystick/windows/SDL_windows_gaming_input.c: In function 'WGI_JoystickOpen':
C:/msys64/home/USERNAME/yuzu/externals/SDL/src/joystick/windows/SDL_windows_gaming_input.c:641:13: error: unknown type name '__FIReference_1_int'; did you mean '__FIReference_1_INT32'?
  641 |             __FIReference_1_int *full_capacityP, *curr_capacityP;
      |             ^~~~~~~~~~~~~~~~~~~
      |             __FIReference_1_INT32
In file included from C:/msys64/mingw64/include/windows.gaming.input.h:622,
                 from C:/msys64/home/USERNAME/yuzu/externals/SDL/src/joystick/windows/SDL_windows_gaming_input.c:33:
C:/msys64/home/USERNAME/yuzu/externals/SDL/src/joystick/windows/SDL_windows_gaming_input.c:643:114: `

Eventually leading to  
`make[1]: *** [CMakeFiles/Makefile2:1967: externals/SDL/CMakeFiles/SDL2-static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....`

Applying the patch allowed me to compile successfully.
