### ISSUE TITLE
yuzu vulkan cant work when both radv and amdvlk are installed

### ISSUE THREAD

**Issue by davidbepo** [yuzu-emu/yuzu#8533]
radv only:
![Captura desde 2022-07-02 23-58-35](https://user-images.githubusercontent.com/18667173/177017258-3289c504-75a8-46be-bf1f-56028bf0a721.png)
amdvlk only:
![Captura desde 2022-07-02 23-57-34](https://user-images.githubusercontent.com/18667173/177017268-ca472ce4-b717-40e1-8daa-1705fb60fa8d.png)
both:
![Captura desde 2022-07-02 23-58-08](https://user-images.githubusercontent.com/18667173/177017273-e1fe66bc-8bc3-4fd0-9b49-3cd56ced270c.png)

trying to open a game with both installed fails

**Comment by liamwhite** [comment]
works for me
![image](https://user-images.githubusercontent.com/9658600/177017364-4e853451-dfb3-40e2-a9d3-19a846a7c13a.png)

**Comment by davidbepo** [comment]
> works for me ![image](https://user-images.githubusercontent.com/9658600/177017364-4e853451-dfb3-40e2-a9d3-19a846a7c13a.png)

did some more research, this isnt a yuzu bug but rather and AMDVLK one DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1 fixes it, that layer not only prevents yuzu fr4om working but also other things, even vulkaninfo
so closing
