### ISSUE TITLE
Mario tennis aces

### ISSUE THREAD

**Issue by Duduceretta** [yuzu-emu/yuzu#8534]
Low fps in local game with 2 or more people

**Comment by G-Spawn** [comment]
<!---
Please keep in mind yuzu is EXPERIMENTAL SOFTWARE.

Please read the FAQ:
https://yuzu-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of yuzu you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

Please try to provide a log when you can.

**Comment by benderscruffy** [comment]
Please close
No update
