### ISSUE TITLE
Zelda: Link's Awakening pixelated DOF issue (Pascal GPU issue)

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#8546]
![yuzu Screenshot 2022 07 07 - 09 44 14 97](https://user-images.githubusercontent.com/8591462/177720729-590d5244-ca1e-4453-bd4f-984d96ad35b2.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9061503/yuzu_log.txt)

Some DOF issues with latest builds I didn't see with old versions: in the bottom part of the screen is visible an ugly pixelated DOF (?) I couldn't see with previous yuzu builds (but I can't say when it started). Distant DOF (upper part of the screen) is OK instead.

**Comment by gidoly** [comment]
are you using disable dof mod?

**Comment by Hexaae** [comment]
No I don't use disable DOF mod. It worked fine before I upgraded to latest yuzu nightly

**Comment by goldenx86** [comment]
That's... how the game is supposed to look natively.
You may have been running a build old enough to not render the blur correctly.

**Comment by goldenx86** [comment]
Try setting anisotropic to default, CPU accuracy to auto, and if that's not enough, revert the driver to 512, the 516 series is known to cause issues with Pascal and Maxwell GPUs.

**Comment by Hexaae** [comment]
Sounds more like a bug in recent builds as the upper DOF is correct instead...

**Comment by gidoly** [comment]
<img width="1920" alt="01006bb00c6f0000_2022-07-07_17-15-02-633" src="https://user-images.githubusercontent.com/66776795/177725544-fb96e77d-a6f9-498e-8482-1b5142e081a3.png">
looks fine on my 2080s must be pascal issue

**Comment by Hexaae** [comment]
Uh... thanks for checking this out. So it really looks a driver issue (weird, only at the bottom). What's your Zelda settings BTW?

**Comment by gidoly** [comment]
graphic renderer: vulkan
resolution: x2
window adapting filter: bicubic
gpu accuracy: high
use fast gpu time
anistrophic filter 16x

**Comment by goldenx86** [comment]
I can confirm it renders correctly for me with the 516 branch on a 1660 SUPER, so it really sounds like a driver issue,

**Comment by Hexaae** [comment]
Just FYI: tested 516.93 SD today and had the same issue on my 1070. Rolled back again to 512.96 SD.

**Comment by Hexaae** [comment]
Still affected: 516.94 SD, yuzu 1127.
Wondering if I should re-open this issue for a devs reminder. It seems a persistent issue with recent NVidia drivers vs yuzu, at least on Pascal GPUs...

**Comment by Hexaae** [comment]
Re-opened.

**Comment by G-Spawn** [comment]
Ideally stick to 512 until we deem it safe to update NV driver 🙏

**Comment by Hexaae** [comment]
> Ideally stick to 512 until we deem it safe to update NV driver 🙏

Ok thanks, It's just a problem with Link's Awakening blur effect for DOF. The other games seem to run fine on 516.xx even on Pascal, so I can live with it 'till you'll find a workaround/fix 😃

**Comment by Hexaae** [comment]
Just for the chronicles, yuzu 1170 + NVidia 517.40 SD, VK API for Zelda LA, even disabling all optimizations (ASTC, Fast GPU Time hack, async shaders compile...) the DOF issue is still present.

**Comment by Hexaae** [comment]
yuzu 1203 + NVidia 522.30 SD the issue with bottom DOF is still reproducible.

**Comment by Hexaae** [comment]
...Hoping for a fix with bottom DOF effect on Pascal for XMas 🎁

**Comment by Hexaae** [comment]
Sometimes wishes come true... Yuzu nightly 1264 + NVidia 527.56 SOLVED any issue with bottom DOF effect in this game, for my Pascal 1070! 🎉
