### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [yuzu-emu/yuzu#8547]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@zer0h-bb) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by bunnei** [comment]
Hey there -

We are happy to discuss bugs with you in private if you wish, but given that yuzu is not a server application, and does not download code from the internet, the scope of any vulnerabilities cannot lead to anything other than potentially local compromise.

With that in mind, if you have anything urgent to discuss, please reach out to me directly either via Discord (bunnei#0166), or email, bunneidev [at] gmail.com. For non-urgent things, please open specific issue(s) for bugs within yuzu that should be fixed. Furthermore, we welcome direct contributions to the repository, if you so wish!

Thank you,
bunnei

**Comment by JamieSlome** [comment]
@bunnei - thanks for your response.

I've sent you a friend request on Discord. Just for reference, both reports can be found here:

https://huntr.dev/bounties/b29eeaba-12a5-4961-81e4-62cc22db6c20/
https://huntr.dev/bounties/b3a945e9-694c-4b5f-9c92-3a99f6eb0b56/

They are private and only accessible to maintainers with repository write permissions 👍
