### ISSUE TITLE
Triangle Strategy Lighting Issue

### ISSUE THREAD

**Issue by kirbyanator** [yuzu-emu/yuzu#8548]
Using version 1080 (7-7-2022), but this problem has existed for a while. Both renders have significant issues with Triangle Strategy's lighting. In Vulkan, only one light source will be rendered at a given time, which is problematic in environments with multiple sources (nearly everywhere). 

In Vulkan, Yuzu will switch between rendering different light sources as the camera moves, which makes them all flicker on and off.

Example A:
![image](https://user-images.githubusercontent.com/87253531/177845200-cfb20103-35bb-4ba0-a10c-0183996cc75d.png)
Light is shown on left table
Example B:
![image](https://user-images.githubusercontent.com/87253531/177845309-5470f980-f603-4e61-8eed-132ed108d570.png)
By just shifting the camera slightly the light blinks over to the table at the top of the frame. Rapidly panning the camera makes them flicker and forth.

Here's what the same room should look like with all light sources rendered:
![image](https://user-images.githubusercontent.com/87253531/177846435-4590eb34-7344-4cef-aaaa-65d18e44bd31.png)
notice the middle light source isn't rendered at all on yuzu

Textures are also prone to corrupt, which has been documented in https://github.com/yuzu-emu/yuzu/issues/7990

In OpenGL, lighting sources aren't rendered correctly at all, and all cause rapid flickering on the entire screen.

Here's my log file from a run in Vulkan, in the same area from my screenshots.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9066500/yuzu_log.txt)

Hoping this game can get some love since switch is the only platform it's on currently.
Thank you!

**Comment by kirbyanator** [comment]
Here are my specs, which I forgot to include:
Nvidia RTX 3070 (mobile)
Ryzen 5800h

This issue seems to be a regression, as older versions of Yuzu simply wouldn't render the light sources at all.
Here's a link to a video that showcases the issue:
https://youtu.be/JUBpZr5b_Cw

**Comment by zwq4869cloud** [comment]
I experience the same issue on older build of mainline and EA with Vulkan.
On newer build e.g. 2905 EA, flying small fire spark cause pixilation on the entire screen. (Vulkan)
Haven't test on OPGL yet.
