### ISSUE TITLE
Bugs in Skyward Sword HD

### ISSUE THREAD

**Issue by Healthboost213** [yuzu-emu/yuzu#8550]
Yuzu Version 1080 
Hardware - i5-1135G7 / Intel Iris Xe (Vulkan)
Game: **The Legend Of Zelda: Skyward Sword HD**

There are 2 Bugs

1st Bug
--------

The First Bug is present in some of the character's eyes where they appear glitched out

_Zelda_

![zelda](https://user-images.githubusercontent.com/79184740/177912076-870043b4-e233-4821-8c39-7d133b7f0386.png)

_Link & Groose_

![groose](https://user-images.githubusercontent.com/79184740/177912142-733d5f10-5423-419a-be87-671a0eb2c727.png)

-------------------------------------------------------------------------------------------------------------------------------------------

2nd Bug
---------

The Next Bug is present all the time. There is a slight slowdown in each alternating frame. 
The Frame movement isn't smooth and this doesn't happen in other games. I'm pretty sure this isn't a hardware 
issue either because MSI Afterburner says that I am getting 30+ FPS. I will try to capture a video and upload it ASAP.

**Comment by G-Spawn** [comment]
That looks rather haunting lol. Would you mind providing a log as well when possible? https://yuzu-emu.org/help/reference/log-files/

**Comment by gidoly** [comment]
it has already opened issue for this closing due to duplicated
