### ISSUE TITLE
Splatoon 2 Glitch, Getting Damaged (Slowed Down) on random surfaces

### ISSUE THREAD

**Issue by GraphUserInt** [yuzu-emu/yuzu#8555]
Playing splatoon 2 on yuzu saw that sometimes i would just take damage out of nowehere even with the ground covered on my own ink (like if i was stepping in enemy ink), but it doesnt seem that its on random surfaces, only on specific ones
Here are some screenshots of my findings
![image](https://user-images.githubusercontent.com/108961984/178084395-56bc5dc9-12c7-40ec-b27c-8b49c4243b49.png)
![image](https://user-images.githubusercontent.com/108961984/178084523-3777f55a-e022-4c14-9d60-4ac21c75510d.png)

**Comment by lat9nq** [comment]
Duplicate of #4982
