### ISSUE TITLE
Audio Loudness issue in Fire Emblem Warriors: Three Hopes

### ISSUE THREAD

**Issue by Petrifyingz** [yuzu-emu/yuzu#8556]
Version: yuzu Early Access 2820 & 2823

Bug Description: Music will occasionally become incredibly loud when a new track plays. I've only observed this issue in Warriors Three Hopes. Issue will go away when a new track plays, but can return again. Changing the music volume setting does nothing when this bug is active.

Footage: https://streamable.com/9kml1i , https://streamable.com/r5howe , https://streamable.com/seyqb5 , https://streamable.com/pidu6m 

Additional info: Output Engine is set to auto, tested and can verify that this does happen on cubeb.

Specs:
Windows 10 21H1 (Build 19043.1645)
CPU - Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz (8 CPUs), ~3.6GHz
GPU - NVIDIA GeForce RTX 2060
Memory - 32GB

**Comment by G-Spawn** [comment]
Provide logs as well when you can for good measure. The guide for it was mentioned in issue template.

**Comment by Petrifyingz** [comment]
Apologies, here's the log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9075777/yuzu_log.txt)
.

**Comment by Petrifyingz** [comment]
Update: Think I've found another detail out. It seems like this issue always occurs when the game goes to play a new track for the 4th time, 8th time, 12th time, etc. Here's a video with this issue occurring and a counter included: https://www.youtube.com/watch?v=927scDzAo8g

**Comment by Moonlacer** [comment]
> Update: Think I've found another detail out. It seems like this issue always occurs when the game goes to play a new track for the 4th time, 8th time, 12th time, etc. Here's a video with this issue occurring and a counter included: https://www.youtube.com/watch?v=927scDzAo8g

@Kelebek1 Might be some information to narrow your search. (Timing, possibly?)

**Comment by Petrifyingz** [comment]
Another update: This issue does not occur on the sdl2 output engine. The issue only occurs on auto and cubeb.

**Comment by EgoBizarro** [comment]
Cubeb seems to have a lot of issues with the audio rewrite (mixed up audio channels, awful static in some games, etc). SDL seems fine except for audio delay.

**Comment by Petrifyingz** [comment]
Issue has been narrowed down to yuzu opening with 6 channels due to my audio output device being 8 channels. The issue can be reproduced with a Logitech G Pro X headset and by installing the Logitech G Hub software. Unsure if this is an issue with any other output devices that support 6 or 8 channels.

**Comment by EgoBizarro** [comment]
Yeah, I have a sound blaster z and a 5.1 surround system.

**Comment by gidoly** [comment]
Can you giys check if issue is fixed on last ea? 2834

**Comment by Petrifyingz** [comment]
@gidoly Checked the latest ea 2828, issue isn't fixed. However, sdl2 works fine and no longer has a noticeable audio delay. For the time being I think it's the best workaround.

SDL2 seems to always force yuzu to open with 2 audio channels, while cubeb is opening with 6. I think that's the reason for SDL2 working fine. Here are my two log files for cubeb and SDL2.
[yuzu_log - cubeb.txt](https://github.com/yuzu-emu/yuzu/files/9087320/yuzu_log.-.cubeb.txt)
[yuzu_log - SDL2.txt](https://github.com/yuzu-emu/yuzu/files/9087321/yuzu_log.-.SDL2.txt)
.

**Comment by EgoBizarro** [comment]
Huh, interestingly, for me it seems to be fine now with cubeb.

**Comment by Macrox14** [comment]
> Sorry, I gotta take that back. The channel issue seems to be fixed with cubeb, but there's still only weird static in many games, e.g. Rayman Legends.

I'm having static noise in Super Mario Bros U

**Comment by Petrifyingz** [comment]
Did a quick test and yuzu ea 2833 seems to have fixed the loudness issue! Will do more testing with cubeb soon.

**Comment by Kelebek1** [comment]
> Sorry, I gotta take that back. The channel issue seems to be fixed with cubeb, but there's still only weird static in many games, e.g. Rayman Legends.

Can you get a list of more games? I don't have Rayman Legends.

> I'm having static noise in Super Mario Bros U
With which version?

**Comment by Macrox14** [comment]
> > Sorry, I gotta take that back. The channel issue seems to be fixed with cubeb, but there's still only weird static in many games, e.g. Rayman Legends.
> 
> Can you get a list of more games? I don't have Rayman Legends.
> 
> > I'm having static noise in Super Mario Bros U
> 


> With which version?
Still hapenning in the last version 2833, after some minutes playing.
Here the log [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9113159/yuzu_log.txt)
Here a video with the issue
https://user-images.githubusercontent.com/31378074/179020450-3d248034-a7b6-42e8-b211-b1f094ff0ad2.mp4

**Comment by Macrox14** [comment]
> Are you doing anything specific? Is it only in that level? is it only in cave levels? A specific powerup or enermy, anything? Can you just stand still not moving for a few minutes and get it? Are you using any mods?

I played again and the issue only happened in cave levels (Rock Candy Mines-4 and 6), nothing specific. It appears randomly, I haven't be able to replicate it standing for minutes. Not using mods

**Comment by EgoBizarro** [comment]
Maybe some issue with reverb effects?

**Comment by Macrox14** [comment]
Just an update, I've continued playing Super Mario Bros U and after a lot the issue appears only again in the level "Hammerswing caverns", so to me only have happened in **Cave levels**.
I couldn't replicate it thought, appears after 5 tries randomly.
