### ISSUE TITLE
Animal Crossing: New Horizons changes timezone to default

### ISSUE THREAD

**Issue by ecogice** [yuzu-emu/yuzu#8558]
In configuration > system, there is an option to change the timezone, which is useful especially for games like Animal Crossing, but no matter the setting, it is always UTC time, which is 4 hours ahead of my local time. Each and every timezone on the list does not make an effect in-game

![image](https://user-images.githubusercontent.com/106189920/178095452-5439bebe-012c-412c-88b1-dda6cf1707bd.png)
EST timezone chosen

![image](https://user-images.githubusercontent.com/106189920/178095526-9483c6af-1e5f-48e2-b395-124546adf97a.png)
Tom says it's 7:02 am, 4 hours ahead of local time

I think the selections in the menu should be changed too, so the dropdown goes like this 

PST / UTC - 8:00
MST / UTC - 7:00
CST / UTC - 6:00
EST / UTC - 5:00

Timezones are complex and the auto setting is difficult to get right, and daylight savings time is a factor too, so maybe if you choose Auto, it asks for your state or territory

**Comment by Docteh** [comment]
Just as a curiosity, what did Auto do on your computer? And do you have firmware dumped or not? 

https://github.com/yuzu-emu/yuzu/blob/a3b12e3809e388e9c9b0608b14d85c0985e412c3/src/core/hle/service/time/time_manager.cpp#L305-L311

Since yuzu takes the place of firmware, there might be a few layers to the problem that need unraveling. 

On my switch there is 84 options to scroll through, and looking at the yuzu code I suspect those options are associated with https://www.iana.org/time-zones definitions. 

UTC -07:00 Tijuana
UTC -07:00 Los Angeles, Vancouver
UTC -07:00 Phoenix

Phoenix is UTC-7 all year round. But the other two currently UTC -7 options will "fall back" to UTC-8

**Comment by ecogice** [comment]
Yup Auto does the same thing. The firmware is dumped as well

**Comment by ecogice** [comment]
I tried the NRO you gave me, and it works perfectly fine

![image](https://user-images.githubusercontent.com/106189920/178527239-f09fdeef-8204-4529-b9af-2d77ec128381.png)
Auto timezone (correct time)

![image](https://user-images.githubusercontent.com/106189920/178527950-ec279624-914e-4d09-b696-e23aa01981a5.png)
EST timezone is also correct

I'm thinking there's something about Animal Crossing which messes up the timezones

**Comment by ecogice** [comment]
![image](https://user-images.githubusercontent.com/106189920/178531704-2accbfcb-4af0-45b9-9f78-46c22dff70e3.png)
Also here is Hong Kong time, again 4 hours ahead of local time (GMT+8 in Hong Kong)
I did make the save in Yuzu but I can see if making another save does anything

**Comment by Docteh** [comment]
I actually wrote the NRO _after_  getting some positive reports from users. When you have the timezone set to auto, I am unclear as to how the game could possibly access UTC time. 



![image](https://user-images.githubusercontent.com/190571/178616241-fb5396e9-2f23-443b-b89c-da12187dc3e3.png)

![image](https://user-images.githubusercontent.com/190571/178615806-008702a4-346a-40a1-8848-bc6a1f98af5a.png)

When you specify a timezone, I can see how the game could get an idea of what UTC is

![image](https://user-images.githubusercontent.com/190571/178627505-81731cfa-397f-458d-9dea-9c92a9fd72ba.png)

For auto I'm not seeing how a game could easily give you UTC in a game as it's clearly given the local time and told its GMT

![image](https://user-images.githubusercontent.com/190571/178627665-0f08b31e-ae62-456a-86b6-130d9c620486.png)

GitHub is picky about extensions, so I zipped up the Updated NRO, it pushes the Location name to the top left: [time.zip](https://github.com/yuzu-emu/yuzu/files/9098045/time.zip)

**Comment by ecogice** [comment]
Tried with NZ-CHAT but still same thing
![image](https://user-images.githubusercontent.com/106189920/178636902-9ad04341-9f6c-4b3b-961c-4b84d7fa5fc0.png)
There has to be a way that it's accessing UTC time
Also the app fails for me on nz-chat
![image](https://user-images.githubusercontent.com/106189920/178637288-e66e786a-5ce5-4d14-a016-c75d791972bc.png)

**Comment by Docteh** [comment]
NZ-CHAT fails? please post a log from running that.

**Comment by ecogice** [comment]
It's also worth mentioning that when I play, the time zone goes to "Default" and goes grey
![image](https://user-images.githubusercontent.com/106189920/178639800-e87f58a4-743b-40f8-a246-018b9bdbace8.png)
I took the time to make a new animal crossing save too, but it's the same time
![image](https://user-images.githubusercontent.com/106189920/178639900-e2b8de55-b0fd-46d9-af5f-255043aca6e8.png)

**Comment by ecogice** [comment]
Here's the log
`[   3.327995] Render.Vulkan <Warning> video_core\vulkan_common\vulkan_device.cpp:Device:642: NVIDIA Drivers >= 510 do not support MSAA image blits
[   3.456154] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:184: Driver: NVIDIA 516.59.0.0
[   3.456160] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:185: Device: NVIDIA GeForce GTX 1650 SUPER
[   3.456161] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:186: Vulkan: 1.3.205
[   3.711456] Debug <Critical> core\hle\service\time\time_manager.cpp:operator ():114: Assertion Failed!
[   3.841376] Frontend <Info> yuzu\main.cpp:BootGame:1570: Booting game: 0000000000000000 | time (64-bit) | 
[   5.702470] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[   5.703826] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[   5.704275] Service.SET <Warning> core\hle\service\set\set_sys.cpp:GetFirmwareVersionImpl:24: called - Using hardcoded firmware version 'NintendoSDK Firmware for NX 12.1.0-1.0'
[   5.705378] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[   5.706207] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[   5.709263] Service.AM <Warning> core\hle\service\am\am.cpp:GetCurrentFocusState:752: (STUBBED) called
[   5.709577] Service.AM <Warning> core\hle\service\am\am.cpp:AcquireForegroundRights:92: (STUBBED) called
[   5.710115] Service.AM <Warning> core\hle\service\am\am.cpp:SetFocusHandlingMode:431: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[   5.710428] Service.AM <Warning> core\hle\service\am\am.cpp:SetOutOfFocusSuspendingEnabled:450: (STUBBED) called enabled=false
[   5.710736] Service.AM <Warning> core\hle\service\am\am.cpp:NotifyRunning:1645: (STUBBED) called
[   5.711261] Service.AM <Warning> core\hle\service\am\am.cpp:SetOperationModeChangedNotification:402: (STUBBED) called flag=true
[   5.711356] Service.AM <Warning> core\hle\service\am\am.cpp:SetPerformanceModeChangedNotification:412: (STUBBED) called flag=true
[   5.711669] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[   5.719883] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[   5.722180] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[   5.728039] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[   5.728731] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetRelayService:442: (STUBBED) called
[   5.729178] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetSystemDisplayService:450: (STUBBED) called
[   5.729264] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetManagerDisplayService:458: (STUBBED) called
[   5.729360] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetIndirectDisplayTransactionService:466: (STUBBED) called
[   5.729735] Service.VI <Warning> core\hle\service\vi\vi.cpp:OpenDisplay:474: (STUBBED) called
[   5.730109] Service.AM <Warning> core\hle\service\am\am.cpp:CreateManagedDisplayLayer:464: (STUBBED) called
[   5.731811] Service.VI <Warning> core\hle\service\vi\vi.cpp:AdjustRefcount:113: (STUBBED) called id=1, addval=00000001, type=00000000
[   5.732011] Service.VI <Warning> core\hle\service\vi\vi.cpp:AdjustRefcount:113: (STUBBED) called id=1, addval=00000001, type=00000001
[   5.732246] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetNativeHandle:124: (STUBBED) called id=1, unknown=0000000F
[   5.738510] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[   5.744099] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:Initialize:155: (STUBBED) called
[   5.744842] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:SetAruid:200: (STUBBED) called, pid=0x51
[   5.747680] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocGetId:148: called
[   5.771252] Debug <Critical> core\hle\service\service.cpp:operator ():160: Assertion Failed!
Unknown / unimplemented function 'GetTotalLocationNameCount': port='ITimeZoneService' cmd_buf={[0]=0x4, [1]=0x8, [2]=0x0, [3]=0x0, [4]=0x49434653, [5]=0x0, [6]=0x2, [7]=0x0, [8]=0x49434653}
[   5.772166] Service.AM <Warning> core\hle\service\am\am.cpp:GetCurrentFocusState:752: (STUBBED) called
[  11.434097] Service.NVFlinger <Error> core\hle\service\nvflinger\buffer_queue_producer.cpp:DequeueBuffer:257: no available buffer slots
`

**Comment by Docteh** [comment]
What version of firmware do you have on there? I can dump 14.1.2 if that is what you've got. 

This is what I got when I tried fresh copy of yuzu, no firmware
![image](https://user-images.githubusercontent.com/190571/178646427-dbb577fa-28c1-4884-ae31-5318cf6b2268.png)

**Comment by ecogice** [comment]
I have 12.1 but I wouldn't mind a newer one lol

**Comment by ecogice** [comment]
So here's this, when I load the time program the time zone option is not greyed out and is at what I selected
![image](https://user-images.githubusercontent.com/106189920/179131686-33fa5370-e407-43ff-a286-6b7c051f1279.png)
And when I load Animal Crossing, the option turns to Default and greys out
![image](https://user-images.githubusercontent.com/106189920/179131933-e3b28834-f981-4405-b04e-5a34ebccc60a.png)
The default option is UTC and 4 hours ahead of local time, so animal crossing is making yuzu go to default

**Comment by Docteh** [comment]
According to the System settings, they should ALL be disabled when a game is running. 
![image](https://user-images.githubusercontent.com/190571/179348908-16cb347d-ebb9-4841-8fab-c7e3b8c2245c.png)

Just to isolate the issue, if its firmware, or your system, how about run the NRO with no keys and no firmware? 


Grab a build, like this one: https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-1087/yuzu-windows-msvc-20220713-36ecf4f9d.zip

unzip it somewhere, inside the folder with yuzu.exe create a folder called `user` and then run `yuzu.exe`

![image](https://user-images.githubusercontent.com/190571/179349609-b7c9a146-1cd9-42a6-b908-6305d1ca5d44.png)
Just hit OK

Hit either yes or no to the question about anonymous statistics, doesn't matter, although maybe go with no ;)

Go into configuration and choose NZ-CHAT

Drop the time.nro onto the yuzu window, and it'll run.

![image](https://user-images.githubusercontent.com/190571/179349528-e7ecd8f2-aec6-4c2c-9bd4-22e3afd647e3.png)

timeGetLocationName should say NZ-CHAT, if it fails exit yuzu and post the entire log, it'll be in the log directory under that user directory

Expected time without firmware is going to be UTC, but it should list the Location as NZ-CHAT

**Comment by ecogice** [comment]
![image](https://user-images.githubusercontent.com/106189920/179381784-229dbd04-8cdd-4fd6-9e03-988fb4a71acd.png)
It does indeed work

**Comment by Docteh** [comment]
Ah, that's good for you, that means we've ruled out the operating system causing trouble, only thing left to try is updating firmware.

**Comment by ecogice** [comment]
![image](https://user-images.githubusercontent.com/106189920/184713927-ae728bc6-38dc-4ece-8b9a-3da814472ab2.png)
I just figured out that I had animal crossing specifically set to default
