### ISSUE TITLE
hitting watchpoint corrupts register state

### ISSUE THREAD

**Issue by comex** [yuzu-emu/yuzu#8563]
Reproduced on 6c72b7f01109300f98a7ba6465285657f330df4c, Linux x86-64

To reproduce:
- Enable CPU debugging and disable all of the optional CPU optimizations (that are exposed in the GUI).  Enable GDB stub.
- Run [this test case](https://github.com/yuzu-emu/yuzu/files/9079782/watch-bug.zip).
- Attach in GDB (also reproduced in LLDB but required manually enabling/disabling the watchpoint on each hit)
- Start running without a watchpoint.  Note that each output line has two numbers: one is always `100.000000`; the other increments each frame.
- `watch counter`
- When watchpoint is hit, continue.
- Notice that in the next line to be printed, the first number is `0.000000`.  This continues as long as the watchpoint is enabled.

This appears to be because `d0` is being corrupted.  This doesn't occur if you set an instruction breakpoint at either the store instruction (to `counter`) or the instruction following.

This also is not caused by some kind of miscommunication when GDB writes register state, as according to the output with `set debug remote on`, GDB doesn't write anything.  (But it does automatically disable the watchpoint, step, and re-enable it.)

I've only seen floating point registers being corrupted, but I don't know if the issue is limited to them.

**Comment by comex** [comment]
Seemingly related: if I `awatch` instead of `watch`, I see a hit on addresses 0x80001b4, 0x80001b8, 0x80001bc, 0x80001c0 (GDB itself reports each of those as one instruction later due to its hidden step).  0x80001b4 is a load and 0x80001c0 is a store but the other two instructions do not access memory.  I also see register values consistent with instructions being executed more than once.

**Comment by liamwhite** [comment]
Instructions being executed twice is expected for now. What is surprising is the modification of the vector registers in the thread context, as they are being saved correctly when the thread unloads (in RewindBreakpointInstruction). I am looking into it.
