### ISSUE TITLE
Most games crash when loading with latest Flathub release

### ISSUE THREAD

**Issue by Beanow** [yuzu-emu/yuzu#8577]
Currently the Flatpak version on Flathub is the mainline-1086 build.
This has a regression compared to the mainline-1085 where the vast majority of games crash when loading.

I found one example so far of games that load normally: Sakuna: Of Rice and Ruin.
Everything else I tried crashes (like Mario Kart 8 Deluxe, if you need an example).

Was reported here first: https://github.com/flathub/org.yuzu_emu.yuzu/issues/570

Logs I looked at were not particularly helpful as they _cut off mid sentence_.
But was able to confirm that downgrading to `mainline-1085` fixes the issue.

**Comment by german77** [comment]
This is know. 1086 was reverted. Please use 1087 or 1088

**Comment by Beanow** [comment]
Glad to hear, currently though 1087 or 1088 are not yet released to Flathub.
And if you install or update right now, you get 1086.
