### ISSUE TITLE
Animal Crossing: New Horizons LayeredFS mods long time loading

### ISSUE THREAD

**Issue by Zetakuu** [yuzu-emu/yuzu#8578]
I have tried several mods (LayeredFS) that are compatible with version 2.0.X of ACNH and takes between 10 to 15 minutes to load. However, if I don't put any mods and leave ACNH only with the latest update + DLCs it only takes 20-30 seconds to load.

My specs:

Intel Core i7 8700K 3.70GHz
NVIDIA GeForce RTX 2080
16 GB RAM

**Comment by G-Spawn** [comment]
Closing in favor of existing issue https://github.com/yuzu-emu/yuzu/issues/5918
