### ISSUE TITLE
Legends arceus crash on yuzu after the intro scene

### ISSUE THREAD

**Issue by LAVEXLEON** [yuzu-emu/yuzu#8583]
This is probably the third time I am posting this issue. This issue persisted since the launch of legends Arceus. The game crashes every time after loading exactly 13 shaders after the first intro scene where the game asks about the protagonist. Yuzu closes soon afterward.
I am on the latest build of mainline yuzu hoping every day that a fix would come, I would also appreciate knowing whether it's my hardware or yuzu itself for causing this problem.

This issue happens on Vulkan and doesn't seem to happen in OpenGL API(tho I haven't tested OGL for a while) and as I have an AMD card I get maximum performance on Vulkan so I prefer Vulkan over OGL. I am using the latest yuzu with the latest supported drivers (Adrenalin 22.6.1) and here's the log file where Legends crashed.

Thanks in Advance!
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9117662/yuzu_log.txt.old.txt)

**Comment by G-Spawn** [comment]
https://github.com/yuzu-emu/yuzu/issues/8331 Closing in favour of your existing issue. Making duplicate ones does not speed up the process of fixing it in the slightest.
