### ISSUE TITLE
Windows BSOD with stop code MEMORY_MANAGEMENT

### ISSUE THREAD

**Issue by LunarTulip** [yuzu-emu/yuzu#8603]
This afternoon, playing *Tsukihime -A piece of blue glass moon-* in yuzu, I experienced a Windows BSOD, with stop code `MEMORY_MANAGEMENT`. I'm pretty confident that this is a yuzu-level bug rather than merely a game-level bug, given that it propagated all the way up to the point of crashing the OS rather than just crashing yuzu itself.

I was running the game in yuzu 1093 (2022-07-17), on Windows 10 build 19043.1826. I have 16GB of RAM, and, per `dxdiag` as of the time of my writing this report, `Page file: 7852MB used, 24843MB available`. The settings at the bottom of the main yuzu window were `VULKAN`, `GPU HIGH`, `DOCKED`, `BILINEAR`, and `NO AA`. The game had been running for approximately three hours as of the time of the crash.

Unfortunately, there are no log files or backtraces I've managed to find for the issue; `yuzu/log/yuzu_log.txt` is entirely empty (0kb in size), `yuzu/log/yuzu_log.txt.old.txt` is nonempty but was last updated about two hours *before* my launch of the game, and insofar as there's anywhere a backtrace might have been logged aside from those files I'm unaware of it.

I apologize for the sparseness of my report; if the issue arises again, I'll do my best to capture more detail. (In particular, I'll avoid relaunching yuzu after the system restarts until after checking for any logs which might be overwritten by said launch.) But, for the moment, this is the best I can offer, and I hope this is at least *nonzero* amounts of helpful, even if less helpful than I'd have preferred to be.

**Comment by german77** [comment]
Yuzu is not able to crash the OS on it's own. However if you run out of things like ram it's very likely for a issue like this to happen

**Comment by LunarTulip** [comment]
Just had my second BSOD with the same error code, this time with yuzu not running in any capacity at the time of the BSOD. So probably this wasn't a yuzu problem to begin with, but rather some other sort of problem related to the general aging of my computer, and it just happened to first occur while I was using yuzu in an unfortunately-confusing bit of timing.
