### ISSUE TITLE
Hyrule Warriors: Age of Calamity - Occassional infinite freeze on map loading screen

### ISSUE THREAD

**Issue by SDXC** [yuzu-emu/yuzu#8608]
This probably was or still is a permanent topic somewhere, but I didn't find this particular issue addressed here.

Playing AoC in Yuzu (either 1090 or EA 2847 doesn't matter) works actually quite good with stable 29/30 fps. However, after some time playing a few missions, the loading screen when starting the next mission freezes infinitely and the fps going to 0, etc.

Stopping the emulation and then restarting the game, or any other game, results in a CtD. Only by restarting Yuzu itself can fix this problem.

For this issue I recreated the issue after playing for around 40 minutes, completing 6 sidequests and with the 7th having the freeze. The attached screenshot is the exact state when the game freezes
![hwaoc-yuzu-ea2847](https://user-images.githubusercontent.com/5290260/179811026-9f3849a6-3853-41bc-9790-f3abbed9467c.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9143305/yuzu_log.txt)
.

Additional Information:
Yuzu EA 2847 x64
Win10 21H2 (19044.1706) x64
VC++ 14.32.31332.0 x64
NVIDIA 512.95

AoC 1.3.0 including DLC 1-4, no mods.
100% CPU Speed
Multicore enabled
CPU = Auto
Vulkan
Disk Pipeline Cache enabled
Async GPU-Emulation enabled
Acc ASTC enabled
NVDEC = GPU
Resolution 2X (this doesn't matter, also happens in 1X)
WAF = AMD FidelityFX (also doesn't matter)
AA = none
Precision of Emulation = high
Fast GPU Time enabled
AF = Auto

AMD Ryzen 9 5900X
64 GB RAM
NVIDIA RTX 3080 12 GB VRAM

**Comment by SDXC** [comment]
I also happened to have similar effect in Hyrule Warriors Definitive Edition: When playing about 3-4 Legendary Story maps in one session, the next maps afterwards have massive graphical issues like misaligned ground textures which makes it impossible to play as you partially don't see what you're doing. After resetting the game, the problem is fixed until further gameplay.

I guess this might in both cases be some kind of memory leak and/or a mismanaged garbage collection.

**Comment by SDXC** [comment]
Freeze doesn't happen anymore. However, after playing for some time it seems the performance gets gradually bad. For now I simply restart the game when that happens.

**Comment by aphirst** [comment]
Sorry for the radio chatter. On closer considerion, I think the issue I've been having is this one. It happened again just now. Every so often, the loading screen just hangs. Reloading the game then attempting to load the exact same mission usually works.

Ryzen 5700X, Win10 (12 of 16 cores assigned to VM on Proxmox), Radeon RX 6700 XT (PCIE passthrough to the VM), 24GB of RAM (64GB physical, dual-channel 3200MT/s), latest Adrenaline drivers etc. Game is fully updated to 1.3.0.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11991452/yuzu_log.txt)

**Comment by SDXC** [comment]
The CtD doesn't happen anymore. That was an issue in some yuzu builds at the time but has been solved. I had this issue with other games as well when I tested that further. So you might have exactly the same issue as me. I may just have been lucky when I last posted, but because of TotK I'm not playing for the time being to do further tests. Hope it will be fixed though, if it really is still present.
