### ISSUE TITLE
We need yuzu-mainline Debian Package (.deb) and Redhat Package (.rpm) for Linux user

### ISSUE THREAD

**Issue by ghost** [yuzu-emu/yuzu#8613]
We need yuzu-mainline Debian/Ubuntu Linux Package (.deb) and Fredoa Package (.rpm) for Linux user

**Comment by liushuyu** [comment]
> We need yuzu-mainline Debian/Ubuntu Linux Package (.deb) and Fredoa Package (.rpm) for Linux user

We currently have AppImage and Flatpak distributions that are suitable for many Linux distributions. Are there any reasons that we should also prepare distro-specific packages?

**Comment by Slemoon** [comment]
> > We need yuzu-mainline Debian/Ubuntu Linux Package (.deb) and Fredoa Package (.rpm) for Linux user
> 
> We currently have AppImage and Flatpak distributions that are suitable for many Linux distributions. Are there any reasons that we should also prepare distro-specific packages?

Appimage and flatpak do not conform to the philosophy of unified software management through package manager in Linux. Their shortcomings include:

Updating software becomes very troublesome

It takes up a lot of computer disk space and is very bloated

It is not convenient to view the program running directory and configuration file

In fact, you only need to provide DEB（Debian/Ubuntu） and RPM（Fedora） software packages to meet the needs of the vast majority of Linux users.

You know, most Linux distributions are generally based on Debian or fedora

Arch Linux has AUR and does not need developers to worry about it

**Comment by JakobDev** [comment]
Maintaining packages for a lot of distributions is a lot of work. I think providing Flatpak and AppImage from Upstream is enough. Some Debian/Fedora Maintainer can still build a Package and upload it to the Repos like it is done with almost every other Program.

**Comment by rcz01** [comment]
AppImages are fine - only one little annoyance, though. Every time I want to update I need to go to website, do few clicks to get to link to latest one, right click, copy and then wget. Or download and copy to my gaming machine.
That is not scriptable, which is annoying.

RPCS3 got around this by having same link (https://rpcs3.net/latest-appimage) to latest AppImage. With trivial script I download the latest, rename it and change permissions and all just works. Would be great if Yuzu also had something like that.

Oh, packages inside repos would also require lots of old versions - stuff does break in Yuzu so sometimes going to old versions is a good idea. With AppImages I can always keep old working versions for whenever I need them - I can even fire up old one just for one game and use latest for everything else. That is actually better than any other method as there is no need to reinstall anything!

**Comment by Slemoon** [comment]
> Maintaining packages for a lot of distributions is a lot of work. I think providing Flatpak and AppImage from Upstream is enough. Some Debian/Fedora Maintainer can still build a Package and upload it to the Repos like it is done with almost every other Program.

I wish I could find Debian/Fedora Maintainer

**Comment by qurious-pixel** [comment]
@Slemoon you can use CPACK with the latest CMAKE to create a local deb or rpm package. 

@rcz01 yuzu-mainline has the update information packaged into the appimage. Using appimageupdate, it will download the latest version for you.
https://github.com/AppImage/AppImageUpdate
`./AppImageUpdate.AppImage yuzu-mainline*.AppImage` or select it from the file picker.

**Comment by G-Spawn** [comment]
Closing as OP has deactivated their account.
