### ISSUE TITLE
EA-2858: Kernel panic (BSOD) while playing SM3DW - KERNEL_SECURITY_CHECK_FAILURE

### ISSUE THREAD

**Issue by RavenMacDaddy** [yuzu-emu/yuzu#8638]
**Yuzu version:** 

EA-2858

**Specs:** 

OS: Windows 11
CPU: AMD Ryzen 3600
GPU: NVIDIA GTX 1080
MB: MSI B450 Gaming Plus MAX

**Graphics API:** 

Vulkan

[Log](https://pastebin.com/nFHB00d2)

After playing SM3DW for about 5 min. with a buddy, we were met by the system having a kernel panic (BSOD) with the error code `KERNEL_SECURITY_CHECK_FAILURE`.

The security software is only the built-in Windows Defender.

This hasn't happened with any other apps, or games for that matter, only with Yuzu, and many of the other games use Vulkan as well.

One thing I could think of is, since I'm running an older GPU driver that's provided through Windows Update (cause the newest ones for NVIDIA GPUs suffers from heavy stuttering) - 457.51 - maybe Yuzu is trying to call a Vulkan function that isn't supported by the old driver, and eventually that leads to a crash?

**Comment by liamwhite** [comment]
Unprivileged applications should not be able to crash the operating system, so yuzu causing a kernel panic would not really be a bug in yuzu, it'd be a bug in the operating system. As you mention, this is very likely just a driver issue.

**Comment by Docteh** [comment]
The pin for recommended driver versions in `#yuzu-support-windows` has a link to 512.95

https://www.nvidia.com/download/driverResults.aspx/189681/en-us/

**Comment by RavenMacDaddy** [comment]
Good, I'll test it later today.

**Comment by RavenMacDaddy** [comment]
Doing a clean install of the suggested version has so far been a great improvement, obviously with no crashes - closing for now.
