### ISSUE TITLE
[Linux] Dark text on dark system themes

### ISSUE THREAD

**Issue by SViN24** [yuzu-emu/yuzu#8643]
![2022-07-26_10-09](https://user-images.githubusercontent.com/51864332/180945424-15b66e7c-1258-44f9-bdbd-cb59d85ed7b3.png)

I am using the yuzu flatpak under KDE(wayland) with the breeze dark theme(although i do think this may also affect other desktops too without having tested them)
These buttons do not change their color to a light variant under a dark theme making them unreadable.

**Comment by Docteh** [comment]
Is wayland required for that? I've got an nvidia card, and I've heard it's no good for wayland

**Comment by SViN24** [comment]
@Docteh I only specified i use wayland to be as transparent as possible with my issue. It is probably unrelated to it and it probably also affects X11

**Comment by Docteh** [comment]
Looks like it's just due to yuzu being set to use "default" theme. Only certain things are specified in the default theme, so it's mostly using your OS theme.
