### ISSUE TITLE
Yuzu:- Vulkan Initialization failed during boot from mainline 1107 onwards

### ISSUE THREAD

**Issue by solarmystic** [yuzu-emu/yuzu#8644]
## Details

When starting up Yuzu on mainline 1107 onwards, the emulator displays the `Vulkan initialization failed during boot` message. 

![image](https://user-images.githubusercontent.com/4345150/180967340-f30a05fb-b04b-40e2-95a0-508eba61c68a.png)
![image](https://user-images.githubusercontent.com/4345150/180967428-056a32b6-a3c6-404d-8ca3-052fc0f02d93.png)

This does not occur on mainline 1105 and below. The emulator starts up as expected and Vulkan can be used with no issues. 

![image](https://user-images.githubusercontent.com/4345150/180967826-0f1566cc-2740-4af7-ab0e-f702ca355a8a.png)

## Logs

Mainline 1107 (1st faulty build)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9188314/yuzu_log.txt)

Mainline 1105 (Last working build)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9188309/yuzu_log.txt)

## System Configuration

12th Gen Intel i5-12400F
NVIDIA RTX 2080 TI with 511.79 drivers
32 GB RAM
Windows 10 21H1

**Comment by NiGame** [comment]
Ditto also get this on my steam deck, had to revert back to 1105

**Comment by Titaniumtown** [comment]
Can also reproduce on linux (steam deck).

**Comment by solarmystic** [comment]
On further investigation, it seems like if the executable filename is the default yuzu.exe, the error does not trigger at all. 

New issue reproduction steps:-

1. Run mainline 1105 (last build without issues) using the default yuzu.exe file name. Close it.

2. Rename mainline 1107's exe to something else (yuzu 1107.exe). Run it.

3. `Vulkan initialization failed during boot` error will appear

Another quirk of this issue is that once you've booted up a 1107+ build successfully without the vulkan error at least once, you may rename any of those executables and run them without issue. 

But if you run any mainline 1105 build and below (for regression testing etc), you have to once again, run a 1107+ build with the default yuzu.exe name at least once. All subsequent boots will be fine after that with whatever yuzu file name.

**Comment by gidoly** [comment]
closes due to reported to resolved
