### ISSUE TITLE
Xenoblade Chronicles 2 Lighting Issue

### ISSUE THREAD

**Issue by 0rb1t5l** [yuzu-emu/yuzu#8651]
This is how it looks on Yuzu.
![Yuzu](https://user-images.githubusercontent.com/95211784/181115291-90a6f74f-3cc8-4075-906f-abcc19f82635.png)
And this is how it's supposed to look like, screenshot from Switch.
![Switch](https://user-images.githubusercontent.com/95211784/181115335-30bd3374-a1cb-404f-a393-b54054a03ece.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9193452/yuzu_log.txt)

**Comment by liamwhite** [comment]
probably dup of https://github.com/yuzu-emu/yuzu/issues/5255

**Comment by 0rb1t5l** [comment]
> probably dup of #5255

This also does happen on Xenoblade Chronicles 1 Definitive Edition.

**Comment by 0rb1t5l** [comment]
> probably dup of #5255

I played 1 DE as well and it has the same issue, I think it's related to the engine of the game so that's why both games have the same issue.

**Comment by 0rb1t5l** [comment]
OpenGL on 512.95 drivers.
![OpenGL](https://user-images.githubusercontent.com/95211784/181123789-8ebb325a-a9b8-4284-9be3-d8a158cf7f7c.png)
Vulkan.
![Vulkan](https://user-images.githubusercontent.com/95211784/181123847-3d3bf23d-d5a9-43c3-bf75-d151d9b468fc.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9193706/yuzu_log.txt)
=

**Comment by 0rb1t5l** [comment]
On the first screenshot I was using an upscaling mod so that might be the cause of the issue, if that's true then close the issue and sorry.
