### ISSUE TITLE
Switch controllers (8BitDo Pro 2 - Switch mode): Analog stick drift

### ISSUE THREAD

**Issue by RavenMacDaddy** [yuzu-emu/yuzu#8655]
Related to #6555

**Yuzu EA 2859** when testing the last time.

Controllers:

**8BitDo Pro 2** and **SN30 Pro+**

---

Playing SM3DW in this case - or simply configuring the controllers in settings - there's very noticeable drifting that interrupts gameplay, and it's only for Switch controllers or controllers that use the same API (AFAIK).

Wrapping the controller input to something else like DS4 or Xinput with software like BetterJoy or DS4Windows makes the drifting go away - even if the controller is actually running in Switch mode hardware-wise, so it's purely a software issue.

The same goes for running the same controller in Xinput mode through the hardware switch on either controller - no drifting occurs in the emulator since the Switch API (or SDL probably, I don't personally know what serves as the base) isn't used.

If a log would help, I'll gladly provide it when possible.

**Comment by german77** [comment]
So the stick is a bit of center? Since that issue we added a manually center option with `right click center stick`
![image](https://user-images.githubusercontent.com/5944268/181277571-55208b29-1a85-4a37-ac90-7fb7d93e83e3.png)

**Comment by RavenMacDaddy** [comment]
So the fix does work, but the stick shouldn't be even a bit off axis as it's - just using other APIs solves the problem when the hardware, stick position and mode is the same.

I'm only wrapping it in software and the readings become what they should be from the get-go in the emulator, as well as reading correctly in other apps even without wrapping, or any other manipulation - as also described in the original issue that's closed.

This is the reading from 8BitDo's own software:

![image](https://user-images.githubusercontent.com/67732686/181294568-ffe886fd-4bb6-4e13-a5ca-8a52b9f9fe02.png)

...and if I manually move it to the corresponding 3%:

![image](https://user-images.githubusercontent.com/67732686/181294729-0d75b9b6-bd7f-4707-82a0-34319c9ecf96.png)

---

Appreciate the input so far.

**Comment by german77** [comment]
Let me provide a bit of info, SDL doesn't provide data until the stick is used. So at first it will appear as they are spot on but in reality no input has been given. Move them in a circle motion to ensure you are looking at the real values. Calibrate after this by selecting the controller again or right click center axis.

Second issue. On switch mode you have 2 calibration settings, one is the factory and the other is the user calibration. SDL by default only reads the factory calibration this is often wrong hence why you get the drift. Most programs like ds4windows or better joy do read both calibrations and take the best one

**Comment by RavenMacDaddy** [comment]
I see.

Out of curiosity, the user calibration, how is that usually accessed on a controller? 

Seemingly 8BitDo's own software is using the custom stock calibration to get the proper readings. 

In any case closing the issue since as you say it's not an issue with Yuzu itself but rather how SDL reads calibration data.
