### ISSUE TITLE
Dont starve Switch Edition Crash log

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#866]
just trying to help so here is the log for the game and some info with multi core enabled it crashes back to the GUI with it off it crashes to desktop 
[yuzu_log_no multicore.txt](https://github.com/yuzu-emu/yuzu/files/2240367/yuzu_log_no.multicore.txt)
[yuzu_log_with multicore.txt](https://github.com/yuzu-emu/yuzu/files/2240370/yuzu_log_with.multicore.txt)

**Comment by Hexagon12** [comment]
Both logs are incomplete.

**Comment by Hexagon12** [comment]
Does the issue still happen?
