### ISSUE TITLE
Xenoblade Chronicles 3 crashing on startup with Vulkan renderer

### ISSUE THREAD

**Issue by Cyber-Snake** [yuzu-emu/yuzu#8662]
Happens shortly after boot. You are able to see first loading screen and hear some sounds but game crashes without reaching main screen. On subsequent launches game crashes during shader cache loading unless you delete it.

Build: Yuzu EA 2867

System Specs:
NVIDIA RTX 2080 Driver 516.79
AMD Ryzen 3700X
32GB RAM
Windows 11 Version 21H2

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9214812/yuzu_log.txt)

**Comment by 0rb1t5l** [comment]
Same issue for me
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9214910/yuzu_log.txt.old.txt)

**Comment by MarcoEstevez** [comment]
same here, OpenGL works though

**Comment by Starcrater21** [comment]
Running Yuzu with VS seems to point to a Exception Access Violation
"Exception thrown at 0x00007FFD19C8C51D (ntdll.dll) in yuzu.exe: 0xC0000005: Access violation accessing location 0x0000000000000000."

![image](https://user-images.githubusercontent.com/48496899/181657401-51e0a3ed-1dab-46e7-8aad-70fd41a8aa18.png)

**Comment by rabidcopy** [comment]
Can confirm on RX 570 with latest optional driver 22.7.1. No meaningful output in the log. (Vulkan does work on Linux however in my case, but then has this issue #8669 consistently.)

**Comment by Cyber-Snake** [comment]
It boots now however there are other issues.

**Comment by RinMaru** [comment]
still happens on AMD

**Comment by farendaibiao** [comment]
still happens on AMD APU +1 with [EA-2878]

**Comment by joshuakalejaiye** [comment]
still happens on amd van gogh apus

**Comment by Cyber-Snake** [comment]
Reopening since AMD still has issues apparently.

**Comment by goldenx86** [comment]
This is caused by lack of a texture format on hardware.
We'll emulate it with a similar one.

**Comment by piau9000** [comment]
It's still crashing. Just after the loading up.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9262732/yuzu_log.txt)
