### ISSUE TITLE
Xenoblade Chronicles 3 missing particles

### ISSUE THREAD

**Issue by 0rb1t5l** [yuzu-emu/yuzu#8663]
Yuzu OpenGL
![010074f013262000_2022-07-26_23-49-12-280](https://user-images.githubusercontent.com/95211784/181654764-54b87765-c312-46d1-8882-04ee228682fe.png)
How it's supposed to look like on Switch
![switch](https://user-images.githubusercontent.com/95211784/181654785-0ac0c2b3-45bc-4ed3-bd68-11dd5808efd9.png)
Yuzu OpenGL
![010074f013262000_2022-07-26_09-39-18-856](https://user-images.githubusercontent.com/95211784/181654796-7607156f-f508-4592-b596-20a7d7363299.png)
How it's supposed to look like on Switch
![switch2](https://user-images.githubusercontent.com/95211784/181654808-6c946e0f-565d-42b4-af9a-2fd73a8e7764.png)

Build: Yuzu 1114
RTX 3060 Ti Driver version 512.95
16 GB RAM
Ryzen 5 2600x
Edition	Windows 10 Pro
Version	21H2
Installed on	‎23/‎07/‎2022
OS build	19044.1826
Experience	Windows Feature Experience Pack 120.2212.4180.0

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9214918/yuzu_log.txt)

**Comment by liamwhite** [comment]
Provide a save file and quick reproduction steps if possible

**Comment by Cyber-Snake** [comment]
> Provide a save file and quick reproduction steps if possible

First cutscene from screenshots is about five minutes into the game if you skip opening cinematic and those particle effects are extremely common at the beginning of the game . Issue apparently happens only on subsequent launches possibly when shader cache is built however I haven't confirmed that myself.

**Comment by 0rb1t5l** [comment]
> Provide a save file and quick reproduction steps if possible

Here are the save files.
[Save files.zip](https://github.com/yuzu-emu/yuzu/files/9214979/Save.files.zip)
Best way to reproduce and test the bug with the save files is to go to the Event Theater.
![010074f013262000_2022-07-29_03-06-45-743](https://user-images.githubusercontent.com/95211784/181657422-d1d8a0ee-aeba-4e2d-8fda-f181c7a38113.png)
And play the highlighted cutscene, which is where the last two screenshots are from (Keep Your Heads Screwed On)
![010074f013262000_2022-07-29_03-07-02-072](https://user-images.githubusercontent.com/95211784/181657468-4224610f-ee9f-4770-bcb0-c3c37c0f789a.png)

**Comment by 0rb1t5l** [comment]
> > Provide a save file and quick reproduction steps if possible
> 
> First cutscene from screenshots is about five minutes into the game if you skip opening cinematic and those particle effects are extremely common at the beginning of the game . Issue apparently happens only on subsequent launches possibly when shader cache is built however I haven't confirmed that myself.

It happens when building shaders and even after shaders are built.
Here is a screenshot of when shaders are building.
![shaders](https://user-images.githubusercontent.com/95211784/181658342-93011397-8dbf-415c-b87a-45cc42d19b7e.png)
And after shaders are built.
![Screenshot 2022-07-29 032304](https://user-images.githubusercontent.com/95211784/181658365-927cd0ae-4bbf-4aaa-94c4-aa3fad8a7c52.png)

**Comment by 0rb1t5l** [comment]
Also here's a video of the issue.
https://user-images.githubusercontent.com/95211784/181665947-10765140-6438-4f7c-9a96-ed002758026d.mp4

**Comment by 0rb1t5l** [comment]
https://user-images.githubusercontent.com/95211784/181668641-d9d2b4ad-2727-444e-ab5d-2740e99b6863.mp4

**Comment by GenericMeow** [comment]
Just to confirm that that this is occurring in Vulkan renderer (AMD GPU) as well. Apologies for the duplicate submission.

**Comment by laststand0810** [comment]
is this issue fixed and have it merged to yuzu 1124 2022-08-06? Cuz as far as I see, there's no improvement on it...

**Comment by tet666** [comment]
> is this issue fixed and have it merged to yuzu 1124 2022-08-06? Cuz as far as I see, there's no improvement on it...

No no one is working on it atm as you can see.

**Comment by Naith01** [comment]
Too bad, I still hope that soon someone will work on it. It does take away some of the atmosphere, I don't know if it's the same problem but it also lacks the rain although it is sometimes visible for a short time the effect disappears all at once and you can only hear the sounds of the rain and see the rain when you look through a transparent [character.]

https://user-images.githubusercontent.com/112326802/187076477-545b87c2-94ac-42e9-87a2-d65f7d8b3852.mp4

**Comment by tet666** [comment]
> Too bad, I still hope that soon someone will work on it. It does take away some of the atmosphere, I don't know if it's the same problem but it also lacks the rain although it is sometimes visible for a short time the effect disappears all at once and you can only hear the sounds of the rain and see the rain when you look through a transparent character. Otherwise it runs very well on 

Rain works fine for me so this is very likely something else but this not the place to discuss this maybe mention it on Discord if you are sure about make a issue report here.

**Comment by PlatinumLucario** [comment]
As of Mainline 1263, it seems to have improved slightly in Vulkan, but the particles still aren't rendered correctly.
![image](https://user-images.githubusercontent.com/1906189/206654361-5cbe802c-2024-4c65-b87b-223c3e410c9c.png)

**Comment by PlatinumLucario** [comment]
After inspecting this and testing it multiple times on the same Yuzu version, and the latest, I can now confirm that the particles issue actually hasn't improved at all. It fluctuates between being drawn at a distance that can be seen, and being drawn at a distance that can't be seen. But there's one part that the particles will never render: When it shows the particles filling the flame clock.

Has anyone looked at the draw distance for certain particles? It's likely that it can't draw particles that are too close to the in-game camera.

**Comment by 0rb1t5l** [comment]
Stop using a shitty emulator that steals code from Ryujinx

**Comment by goldenx86** [comment]
Funny, last I heard, Ryujinx is still open source.

**Comment by PlatinumLucario** [comment]
I think this user's account has been compromised, this issue may have to be locked to prevent any edits.

**Comment by 0rb1t5l** [comment]
Here is all of the Pull Requests Bunnei stole from them (btw these are all hidden, Bunnei hid them) (https://github.com/yuzu-emu/yuzu/pull/5274) (https://github.com/yuzu-emu/yuzu/pull/5328) (https://github.com/yuzu-emu/yuzu/pull/5830) (https://github.com/yuzu-emu/yuzu/pull/5337) (https://github.com/yuzu-emu/yuzu/pull/5364)

The commit made by Bunnei (https://github.com/yuzu-emu/yuzu/commit/eae9f2e4404f6bdf8a192bc9c09e53cd87e4359d)

> I think this user's account has been compromised, this issue may have to be locked to prevent any edits.

Your brain is compromised.

**Comment by G-Spawn** [comment]
> 

Sadly locking it doesn't stop them from editing already made posts.

**Comment by goldenx86** [comment]
We don't accept contributions from piracy groups.
