### ISSUE TITLE
SMO Online crashes on linux

### ISSUE THREAD

**Issue by piplup55** [yuzu-emu/yuzu#8666]
**Version:**
**Yuzu 1114** 
Commit: [a159f4c83](https://github.com/yuzu-emu/yuzu-mainline/commit/a159f4c83),
[Appimage](https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-1114/yuzu-20220728-a159f4c83.AppImage)

**To reproduce:**
Load the game

**Logs:**
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9215663/yuzu_log.24.txt)

**More details:**
- mod works fine on windows
- [link to the mod](https://cdn.discordapp.com/attachments/481993523424395297/1001729564558495835/yuzu_unofficial.zip) mod requires 1.0.0

**System Specs:**

 - OS: Arch Linux
 - CPU: AMD Ryzen 7 3700X
 - GPU: RX6600 XT
 - Memory: 80GB, Swap: 256GB
 - GPU Driver: Mesa 22.1.3, radv 22.1.3

**Comment by iMonZ** [comment]
Any news here?

**Comment by piplup55** [comment]
fixed by using the latest dev build of the mod
