### ISSUE TITLE
Feature Request： make the game sound amplified to more than 100%

### ISSUE THREAD

**Issue by cxhttt233** [yuzu-emu/yuzu#8668]
The sound of some games is so low that the actual playing experience is not very good, even when the volume of both the device and the emulator is adjusted to 100%. So is it possible to add a feature to make the game sound amplified to more than 100%. 

Take this chrome extension for example, it can amplify the sound of a window page up to 600%.
https://chrome.google.com/webstore/detail/volume-master/jghecgabfgfdldnmbfkhmffcabddioke

**Comment by G-Spawn** [comment]
https://github.com/yuzu-emu/yuzu/pull/8756 this should satisfy your request.
