### ISSUE TITLE
Xenoblade Chronicles 3 - Cutscenes crash Yuzu with Vulkan renderer

### ISSUE THREAD

**Issue by AzureLumina** [yuzu-emu/yuzu#8669]
Fastest and easiest way to reproduce is to boot the game and launch the "Event Viewer" on the main menu to watch any cutscene, sometimes it crashes the first time and some others the second or third attempt. This will make Yuzu crash to desktop inmediately.

Please let me know if I can upload anything else for further assistance. I'd be more than happy to.

Build: Yuzu Early Access 2872 
nVIDIA RTX2070 Super Driver version 512.77
16 GB RAM
Ryzen 5 5600x
Windows 10 Version 21H2

[SaveFile.zip](https://github.com/yuzu-emu/yuzu/files/9217759/SaveFile.zip)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9217892/yuzu_log.txt)

**Comment by rabidcopy** [comment]
Happens to me on Linux. First cutscene or two will play out, then the third cutscene at the start of the game will always crash. (Windows crashes before the title screen when attempting to use Vulkan on AMD, seems to also effect some Nvidia users as well per #8662)

RX 570 with latest mesa drivers available on an Arch-based distro.

**Comment by Anthonordique** [comment]
> Le moyen le plus rapide et le plus simple de reproduire est de démarrer le jeu et de lancer le "Visionneur d'événements" dans le menu principal pour regarder n'importe quelle cinématique, parfois il plante la première fois et d'autres la deuxième ou la troisième tentative. Cela fera planter Yuzu sur le bureau immédiatement.
> 
> S'il vous plaît laissez-moi savoir si je peux télécharger autre chose pour plus d'aide. J'en serais plus qu'heureux.
> 
> Version : Yuzu Early Access 2872 nVIDIA RTX2070 Super Driver version 512.77 16 Go de RAM Ryzen 5 5600x Windows 10 Version 21H2
> 
> [SaveFile.zip ](https://github.com/yuzu-emu/yuzu/files/9217759/SaveFile.zip) [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9217892/yuzu_log.txt)

I have exactly the same problem
But I didn't have time to try it on the latest early access

Version : Yuzu Early Access 2865
CPU : i7-8700 - 3,20 GHz
GPU : Nvidia GTX 1660 Super (Driver : version 516.59)
RAM : 16 Go (2 x 8Go) - 2666 (1333MHz) - CL19
OS : Windows 10 Version 21H2

**Comment by Anthonordique** [comment]
> Fastest and easiest way to reproduce is to boot the game and launch the "Event Viewer" on the main menu to watch any cutscene, sometimes it crashes the first time and some others the second or third attempt. This will make Yuzu crash to desktop inmediately.
> 
> Please let me know if I can upload anything else for further assistance. I'd be more than happy to.
> 
> Build: Yuzu Early Access 2872 nVIDIA RTX2070 Super Driver version 512.77 16 GB RAM Ryzen 5 5600x Windows 10 Version 21H2
> 
> [SaveFile.zip](https://github.com/yuzu-emu/yuzu/files/9217759/SaveFile.zip) [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9217892/yuzu_log.txt)

I have exactly the same problem
But I didn't have time to try it on the latest early access

Version : Yuzu Early Access 2865
CPU : i7-8700 - 3,20 GHz
GPU : Nvidia GTX 1660 Super (Driver : version 516.59)
RAM : 16 Go (2 x 8Go) - 2666 (1333MHz) - CL19
OS : Windows 10 Version 21H2

**Comment by Bjorn29512** [comment]
> 

pretty sure vulkan didnt even boot the game on that build so its not really the same issue

**Comment by 0rb1t5l** [comment]
Also getting a crash each time I try to view a cutscene in the Event Theater
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9220549/yuzu_log.txt)
.

**Comment by danky1** [comment]
still crashes on boot up for me 

Build: Yuzu Early Access 2872
AMD Radeon RX 6900 XT
32 GB RAM
AMD Ryzen 7 5800X 8-Core Processor            
Windows 10 Version 21H2
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9221774/yuzu_log.txt)

**Comment by bluetsutsu** [comment]
Crashes upon going into event viewer and viewing a cutscene. First attempt will load the cutscene but when a demanding amount of shaders need to be built, the crash occurs. Relaunching and attempting to view the cutscene again will not even load the cutscene before crashing.

Build: Yuzu Early Access 2872
NVIDIA 3070 512.15
32 GB RAM
AMD Ryzen 7 5800X 8-Core Processor
Windows 10 Version 21H2
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9221797/yuzu_log.txt)

**Comment by Leicalol** [comment]
Fwiw this only happens on specific cutscenes. Going into the event viewer and watching the "Keep Your Heads Screwed On" (chapter 1) will produce a crash 100% of the time, it doesn't happen for all cutscenes though.

**Comment by widardd** [comment]
> still crashes on boot up for me
> 
> Build: Yuzu Early Access 2872 AMD Radeon RX 6900 XT 32 GB RAM AMD Ryzen 7 5800X 8-Core Processor Windows 10 Version 21H2 [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9221774/yuzu_log.txt)

I've read that AMD driver versions after 22.4.1 introduced this issue. But there's no way in hell I'm going to drop the awesome opengl performance of 22.7.1.
