### ISSUE TITLE
Kirby and the Forgotten Land unexpected performance drop at Fast-Flowing Waterworks

### ISSUE THREAD

**Issue by Titaniumtown** [yuzu-emu/yuzu#8672]
Build: Yuzu EA 19956
On the Steam Deck (Linux + AMD + Mesa)

At the first bossfight at the Fast-Flowing Waterworks there is a sudden and extreme performance degradation when the bossfight starts, going from a locked 30 fps to 17 and only ending when the bossfight is over. This is very strange as there is no complexity in the enemies' models or anything that would indicate a workload unable to be handled easily.

**Comment by G-Spawn** [comment]
That isn't a valid number for ea build or mainline. When you can please try to post a log https://yuzu-emu.org/help/reference/log-files/ . Latest ea is 2872 and latest mainline 1115

**Comment by Titaniumtown** [comment]
> That isn't a valid number for ea build or mainline. When you can please try to post a log https://yuzu-emu.org/help/reference/log-files/ . Latest ea is 2872 and latest mainline 1115

ah, that was what `curl https://api.yuzu-emu.org/downloads/earlyaccess/` gave me for a version number 😕

**Comment by Titaniumtown** [comment]
Log: https://paste.gg/p/anonymous/35b9ff2ecfa342269741ea07fadca5c7

And the EA version would then be 2872 then if that's the latest, as I just built the latest source EA tarball.

**Comment by Morph1984** [comment]
This is tracked to #8650

**Comment by Morph1984** [comment]
The latest EA should have this fixed

**Comment by Morph1984** [comment]
Fixed in #8650
