### ISSUE TITLE
FSR 2.0 support

### ISSUE THREAD

**Issue by Titaniumtown** [yuzu-emu/yuzu#8673]
It seems FSR 1.0.2 is being used instead of [FSR 2](https://github.com/GPUOpen-Effects/FidelityFX-FSR2). Updating the FSR version would result in graphical improvements to the upscaled image. This would be great for mobile and low-powered systems such as the Steam Deck and various laptops.

**Comment by german77** [comment]
FSR 2 uses motion data which games doesn't provide. So it's not possible to add support to this filter

**Comment by Titaniumtown** [comment]
Oh really? Darn. Well that's a shame
