### ISSUE TITLE
EVE ghost enemies , Character is not displayed.

### ISSUE THREAD

**Issue by q36yznmh** [yuzu-emu/yuzu#8680]
The standing character is not displayed.
In all scenes.

**Yuzu.**
![000](https://user-images.githubusercontent.com/73178917/181903626-a66cdf80-1868-41a4-bdb1-301155691b16.png)
**Originally, the character is displayed.**
![61Co9utGasL _AC_SL1000_](https://user-images.githubusercontent.com/73178917/181903634-51765709-a5ae-4694-8ad5-767186b77818.jpg)

i9 9900k
32GB RAM
RTX2070

**Logs.**
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9225874/yuzu_log.txt)
Many warnings have been generated.

**Comment by gidoly** [comment]
Can you post save issue to reproduce issue quickly?

**Comment by vonchenplus** [comment]
#9194 should be fix this issue.
