### ISSUE TITLE
SIGSEGV & Segmentation fault on Linux with specific Titles (ex. Metroid Dread) & recents Yuzu Mainline builds

### ISSUE THREAD

**Issue by Linskun** [yuzu-emu/yuzu#8683]
With recents yuzu Mainline builds some titles (as Metroid Dread or Link Awakening) don't start.
Yuzu window remain blank and after a while it crashes with error : 
```
Unhandled SIGSEGV at rip 0x007fd3dbae8814
Segmentation fault (core dumped)
```

It worked well on old builds 873 - 877

I've also tried with latest 1116 without success (in vulkan mode)

**Software information** 
    * OS: Arch Linux x86_64
    * Resolution: 1920x1080
    * Dm/Wm: GNOME
    * gcc (GCC) 12.1.0
    * **yuzu 1116**

**System information**
    * Kernel:** Linux 5.18.15-zen1-1-zen
    * CPU: AMD Ryzen 5 1600X (12) @ 3.600GHz
    * Memory: 16GB
    * GPU: NVIDIA GeForce GTX 1060 6GB
    * Driver: nvidia 515.57

**Comment by liamwhite** [comment]
Provide a stack trace of the crash so we can investigate further

**Comment by Linskun** [comment]
Done

Here the GDB log --> [https://pastebin.com/W4sE2ugc](https://pastebin.com/W4sE2ugc)
Here the Yuzu log --> [https://pastebin.com/KwJFvUqb](https://pastebin.com/KwJFvUqb)

**Comment by liamwhite** [comment]
Please get the GDB log again, but do not run `handle SIGSEGV nostop` as your crash is due to an unhandled SIGSEGV.

**Comment by Linskun** [comment]
Done

Here the new GDB log --> [https://pastebin.com/RuXiNaQB](https://pastebin.com/RuXiNaQB)

**Comment by liamwhite** [comment]
It seems like your VAAPI system library is broken. Try changing NVDEC emulation to CPU video decoding in the graphics settings.

**Comment by Linskun** [comment]
Ok i confirm.
I've uninstalled the vdpau backend for vaapi (libva-vdpau-driver) and now it work without problem

**Comment by john-peterson** [comment]
I am completely confused

How can I debug if it's spamming sigbal 11 all the time

If I stop on signals I can never run anything. If I don't I can't debug it

HOW DO I COMPLETELY DISABLE MULTI THREADING

What am I missing

**Comment by john-peterson** [comment]
```
Unhandled SIGSEGV at rip 0x00007ffff74ad1cf

**Comment by john-peterson** [comment]
Now what the hell is that. Why do I get an address
