### ISSUE TITLE
Xenoblade Chronicles 3 texture flickering on Vulkan

### ISSUE THREAD

**Issue by 0rb1t5l** [yuzu-emu/yuzu#8688]
Vulkan

https://user-images.githubusercontent.com/95211784/182033455-78bd34e2-991f-4f43-9b58-c11f8962ce5f.mp4

OpenGL

https://user-images.githubusercontent.com/95211784/182033460-10c3a790-b079-44c3-8337-b65bb00832fb.mp4

For testing:
Load the save file on this slot and it will start the game in the location from the videos. (10:43)
![010074f013262000_2022-07-31_18-19-39-563](https://user-images.githubusercontent.com/95211784/182033540-8266034b-e599-4758-b2fe-53db4594fd74.png)

[Save files.zip](https://github.com/yuzu-emu/yuzu/files/9229163/Save.files.zip)

Build: Yuzu EA 2878
RTX 3060 Ti Driver version 512.95
16 GB RAM
Ryzen 5 2600x
Edition Windows 10 Pro
Version 21H2
Installed on ‎23/‎07/‎2022
OS build 19044.1826
Experience Windows Feature Experience Pack 120.2212.4180.0
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9229148/yuzu_log.txt)

**Comment by joshuakalejaiye** [comment]
I have the same problem

Version : Yuzu Early Access 2884
CPU : Ryzen 5600x
GPU : Nvidia GTX 3070
RAM : 16 Gb (2 x 8Gb)
OS : Windows 11

**Comment by AaronKelley** [comment]
This issue has been bugging me as well.  I think PR #9802 might solve this?  It hasn't merged yet but I'm going to try to do a build today and check it out .....

**Comment by Ryan2603** [comment]
> This issue has been bugging me as well. I think PR #9802 might solve this? It hasn't merged yet but I'm going to try to do a build today and check it out .....

nope, tested on EA3400, still flickering, and got this error line somewhere.

[  91.417252] Debug <Critical> video_core\shader_environment.cpp:operator ():59: Assertion Failed!
Unimplemented code!

**Comment by AaronKelley** [comment]
EA wouldn't be good to test on for this; the PR hasn't been merged yet, so EA builds would not contain the "fix".
(I just did my own build but haven't had time to test it quite yet.)

**Comment by AaronKelley** [comment]
It seems good to me.

- I checked out the yuzu-mainline project and compiled it using the build instructions, ran XC3 using this build and confirmed that I still see flickering.  (This was my first time ever doing a yuzu build, it took some time to get dependencies loaded into a VM and then go through the steps to do the compilation.)
- Then I implemented the fix (changes to maxwell_3d.cpp — three lines added from the single PR commit, and also an addition to IsMethodExecutable as requested by @vonchenplus) and built again.  With this build I am no longer able to reproduce the terrain flickering.

This was just a quick check but I'm glad to have this fixed as I have recently started playing through XC3.  I'll give it a more detailed check when I have time to actually play later today.  Hopefully the PR gets sorted out and this fix makes its way into official builds (both EA and mainline) soon.

**Comment by AaronKelley** [comment]
The PR is merged so you should be able to check it in the _next_ EA build.  After more time with it I have found that this definitely improves but does not fully correct the terrain glitching in XC3.

**Comment by 0rb1t5l** [comment]
Stop using a shitty emulator that steals code from Ryujinx, also the devs and mods are cunts.

**Comment by goldenx86** [comment]
Enjoy the report to GitHub.

**Comment by 0rb1t5l** [comment]
Here is all of the Pull Requests Bunnei stole from them (btw these are all hidden, Bunnei hid them) (https://github.com/yuzu-emu/yuzu/pull/5274) (https://github.com/yuzu-emu/yuzu/pull/5328) (https://github.com/yuzu-emu/yuzu/pull/5830) (https://github.com/yuzu-emu/yuzu/pull/5337) (https://github.com/yuzu-emu/yuzu/pull/5364)

The commit made by Bunnei (https://github.com/yuzu-emu/yuzu/commit/eae9f2e4404f6bdf8a192bc9c09e53cd87e4359d)
