### ISSUE TITLE
luminous avenger ix 2 stuck on launching screen

### ISSUE THREAD

**Issue by icarustar245** [yuzu-emu/yuzu#8689]
as the title says, LAiX2 is stuck on the launching screen

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9229260/yuzu_log.txt)

**Comment by liamwhite** [comment]
No obvious unimplemented service. May be a timing issue. See if it works with multicore disabled?

**Comment by icarustar245** [comment]
> No obvious unimplemented service. May be a timing issue. See if it works with multicore disabled?

tried it just now, still won't get past the launching screen

**Comment by benderscruffy** [comment]
please close 
duplicate of #7987
