### ISSUE TITLE
Xenoblade Chronicles 3 broken lighting and reflections on Vulkan

### ISSUE THREAD

**Issue by 0rb1t5l** [yuzu-emu/yuzu#8690]
Vulkan

https://user-images.githubusercontent.com/95211784/182042533-f03c4b49-42be-4327-a9e3-bbf959e82969.mp4

OpenGL

https://user-images.githubusercontent.com/95211784/182042539-87227f21-01d4-4e35-9833-5ff6d4bef846.mp4

Some later areas are also affected and not just waterfalls:
![unknown](https://user-images.githubusercontent.com/95211784/182042667-47b9a405-b0a1-4edb-b438-42056815daca.png)
![unknown (1)](https://user-images.githubusercontent.com/95211784/182042670-dacf242e-bd3d-41eb-8f3c-c84c6b05ef5f.png)
![unknown (2)](https://user-images.githubusercontent.com/95211784/182042673-8f817e0d-566b-4a65-a7de-14da58fce028.png)

For testing:
Load the save file on this slot and it will start the game in the location from the videos. (0:32)
![010074f013262000_2022-07-31_22-33-23-787](https://user-images.githubusercontent.com/95211784/182042560-3405c0e6-ac1d-4ea9-a8e1-7b634fdbbfdf.png)
[Save files.zip](https://github.com/yuzu-emu/yuzu/files/9229605/Save.files.zip)

Build: Yuzu EA 2878
RTX 3060 Ti Driver version 512.95
16 GB RAM
Ryzen 5 2600x
Edition Windows 10 Pro
Version 21H2
Installed on ‎23/‎07/‎2022
OS build 19044.1826
Experience Windows Feature
Experience Pack 120.2212.4180.0
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9229607/yuzu_log.txt)

**Comment by Taekro** [comment]
Issue seems to have disappeared on AMD GPU (at least as tested on the Steam Deck), but still persists on my PC with an 2060 Super.
Tested without mods and with Vulkan, EA 2888.

**Comment by ykoneee** [comment]
The issue seems to have disappeared after setting 2x resolution, and it seems that any setting that is not 1x resolution will resolve the issue. Of course this is only a temporary solution.

**Comment by SPARKisnumber1** [comment]
> The issue seems to have disappeared after setting 2x resolution, and it seems that any setting that is not 1x resolution will resolve the issue. Of course this is only a temporary solution.

Not working for me, I'm getting these lighting errors on every res scale. i7 9700k, RTX 3070

**Comment by zhujingwei** [comment]
Same issue here.
