### ISSUE TITLE
Xenoblade Chronicles 3 - Broken save file thumbnails

### ISSUE THREAD

**Issue by Cyber-Snake** [yuzu-emu/yuzu#8691]
Save file thumbnails appear corrupted as pure black images with some trash pixels scattered randomly. Instead they should show a screen of your game taken at the time of saving.

![yuzu Early Access 2878 _ Xenoblade Chronicles 3 (64-bit) _ 1 1 0 _ NVIDIA 31_07_2022 21_53_00](https://user-images.githubusercontent.com/48720219/182042917-52cdbd9c-5675-4a4a-95a0-dc1f84c16acc.png)

Build: Yuzu EA 2878

System Specs:
NVIDIA RTX 2080 Driver 516.79
AMD Ryzen 3700X
32GB RAM
Windows 11 Version 21H2

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9229631/yuzu_log.txt)

**Comment by 0rb1t5l** [comment]
Vulkan

https://user-images.githubusercontent.com/95211784/182043244-2b298480-53bc-4cbd-9cfe-0972bc70869a.mp4

OpenGL


https://user-images.githubusercontent.com/95211784/182043250-ff60351c-ea55-465f-ab0a-a3dfd06ed0fa.mp4

Save files with location from videos.
[Save.files.zip](https://github.com/yuzu-emu/yuzu/files/9229645/Save.files.zip)

**Comment by joshuakalejaiye** [comment]
I have the same problem

Version : Yuzu Early Access 2884
CPU : Ryzen 5600x
GPU : Nvidia GTX 3070
RAM : 16 Gb (2 x 8Gb) 
OS : Windows 11

**Comment by fedast** [comment]
Xenoblade Chronicles DE has the same issue.

**Comment by sq8192** [comment]
I'm getting the same issue in Xenoblade Chronicles DE!
![Capture](https://user-images.githubusercontent.com/29742260/189785221-eeb0491a-a4c9-48eb-a2df-2ed58e12d2ab.PNG)

**Comment by gidoly** [comment]
fixed by reactive flushing option on
