### ISSUE TITLE
Xenoblade Chronicles 3 - Crash [After Fix ?]

### ISSUE THREAD

**Issue by Anthonordique** [yuzu-emu/yuzu#8706]
Hello/Good evening everyone

First please forgive me for my english

I think this topic has already been covered, but I see that the problem persists even after the so-called fix
To make it simple, I will first share the two files related to the logs

As usual the problem occurs after about thirty minutes of play before suddenly crashing the first time it was towards the end of chapter 2 at the time of the 3 fights with a cutscene between each fight (4 cutscenes in total)

The second crash happened between the end of chapter 2 and during the walk in the colony 4 (This time I completely zapped the cutscenes with the "X" key)

**Version : Yuzu Early Access 2888 - OpenGL
CPU : i7-8700 - 3,20 GHz
GPU : Nvidia GTX 1660 Super (Driver : version 516.59)
RAM : 16 Go (2 x 8Go) - 2666 (1333MHz) - CL19
OS : Windows 10 Version 21H2**

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9245666/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9245669/yuzu_log.txt.old.txt)

**Comment by Bjorn29512** [comment]
These crashes are part of memory leak issue that are still being worked on, its not fixed in its entirety yet.

**Comment by Anthonordique** [comment]
I see, I really thought it was solved since the so-called fix, in doubt I still preferred to report it

Thank you for the feedback, I will do what is necessary to pass the message on my side

**Comment by G-Spawn** [comment]
> These crashes are part of memory leak issues https://github.com/yuzu-emu/yuzu/issues/8670 that are still being worked on, its not fixed in its entirety yet.

^ Closing in favour of existing issue https://github.com/yuzu-emu/yuzu/issues/8670
