### ISSUE TITLE
1 instace crash when running 3 yuzu instances

### ISSUE THREAD

**Issue by mightymariomanlol** [yuzu-emu/yuzu#8709]
Log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9249446/yuzu_log.txt)

old log
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9249447/yuzu_log.txt.old.txt)
hello, i was trying to run 4 instances of yuzu, and for some reaslon it crashed, has anyone seen this bug before, if any team or anybody know how to solve this issue manualy or just a fix please let me know heres a video

video https://www.youtube.com/watch?v=8NJClKWjDQo

**Comment by Titaniumtown** [comment]
why did you make a duplicate issue if your own issue

**Comment by german77** [comment]
Duplicate of #8708
