### ISSUE TITLE
Xenoblade Chronicles 3 - Incorrect rendering under OpenGL

### ISSUE THREAD

**Issue by chengyuhui** [yuzu-emu/yuzu#8710]
## System Specs
```
CPU: AMD R7 3700X
GPU: AMD RX 470D
System: Manjaro with kernel version 5.18.14, default open-source GPU driver
```

## Configuration
OpenGL with GLSL shader (Vulkan and SPIR-V both crashes upon boot). No other setting changed.

## Screenshots
Game version: 1.1.0

![010074f013262000_2022-08-03_22-04-28-172](https://user-images.githubusercontent.com/1381736/182629529-9146401f-16d8-43a4-bd55-657d69752fdc.png)
![010074f013262000_2022-08-03_22-03-30-163](https://user-images.githubusercontent.com/1381736/182629561-1b4453bb-7593-4a33-879f-324a10992225.png)

## Save File
I don't think is required, even the title screen does not render correctly.

## Logs

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9252103/yuzu_log.txt.old.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9252104/yuzu_log.txt)

**Comment by liamwhite** [comment]
Note: this is a bug in radeonsi
