### ISSUE TITLE
Mario Kart 8 + Update 2.1.0 

### ISSUE THREAD

**Issue by jvhellraiser** [yuzu-emu/yuzu#8718]
- Yuzu EA 2888.
- And error appear after loading Mario Kart with update 2.1.0 game wont crash just this error appear...
![Screenshot 2022-08-04 204534](https://user-images.githubusercontent.com/16488761/182979799-7daef9d2-e23a-4583-9f3b-7baa8c888cae.jpg)

- I7 9700k , 16gb ram, Nvidia RTX 2060
- For any issues, a log file
  [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9264390/yuzu_log.txt)

**Comment by german77** [comment]
We don't support piracy
