### ISSUE TITLE
Xenoblade Chronicles 3 still crashing with vulkan, even with PR 8702.

### ISSUE THREAD

**Issue by piau9000** [yuzu-emu/yuzu#8721]
Xenoblade Chronicles 3 is still crashing at startup with vulkan for me. I'm using the newest build (1123) that's supposed to have #8702 merged. The crash happens right after the loading screen.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9270546/yuzu_log.txt)

**Comment by solarmystic** [comment]
Issue confirmed on a 12400F, RTX 2080TI system running mainline 1123 on Windows 10 21H1. Still crashes with Vulkan renderer. 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9273923/yuzu_log.txt)

**Comment by liamwhite** [comment]
This is expected with the mainline version right now as it does not contain PRs #8667 or #8700.
