### ISSUE TITLE
Yuzu crashes when launching game

### ISSUE THREAD

**Issue by Elvisass** [yuzu-emu/yuzu#8726]
Yuzu Build : EA 2890 (and same bug with EA 2856, idk if other verisons can work)
CPU : AMD Ryzen 5 1600 Six-Core Processor @ 3.20 GHz
GPU : NVIDIA GeForce RTX 2080
GPU Driver : 461.92
VRAM : 4 GB
RAM : 24 GB
OS : Windows 10 (1709)

When I upgrade yuzu version from EA 2105 to EA 2890 ( to get better support for Xenoblade3 ), yuzu crashes during launching the game ( Start the game - loading shaders - launching - crash ).
I tried to open some other games that older yuzu can normally start, but the new version crashes at the same point.
I tried to remove the whole yuzu folder (AppData\Roaming\yuzu, except the prod.keys file) but it did not help.

I found some error info in logs but have no idea what they mean:
```
HW.Memory <Critical> common\host_memory.cpp:GetFuncAddress:77: Failed to load CreateFileMapping2
HW.Memory <Critical> common\host_memory.cpp:HostMemory:501: Fastmem unavailable, falling back to VirtualBuffer for memory allocation
...
assertion failed: conf.global_monitor && conf.fastmem_pointer
```
[yuzu_log_from_console.txt](https://github.com/yuzu-emu/yuzu/files/9275533/yuzu_log_from_console.txt)

**Comment by liamwhite** [comment]
Fastmem was unable to be used and your settings are incompatible with it. You must either upgrade to a later version of Windows 10 which supports the new virtual memory management APIs, or enable CPU debugging and disable Host MMU emulation.
