### ISSUE TITLE
whats wrong？

### ISSUE THREAD

**Issue by krokyhui** [yuzu-emu/yuzu#8738]
when i install this program it prompts me:
Your computer is out of date.
Make sure that your computer is up to date, and that you have Internet Explorer 11 installed.
Please note we do not support pirated or unsupported versions of Windows.

My computer system is activated win7,does this program not support win7?

**Comment by lightgod87** [comment]
yuzu stopped supporting Windows 7 since yuzu 961 due to some changes that forced deprecation of previous OS to Windows 10. Sadly, nothing that can be done.

**Comment by G-Spawn** [comment]
You will have to update to bare minimum windows 10 1809
