### ISSUE TITLE
Yuzu performance drops when in fullscreen and windows 1080p etc..

### ISSUE THREAD

**Issue by unuruu5760** [yuzu-emu/yuzu#8740]
Does anyone have the same symptoms as me?
YUZU VULKAN suffers from performance degradation in 1080P windows and full screen. Curiously, maximizing the window returns the original performance.
I am using GTX1080 and driver version 511.23 (I tried the latest version but the result is the same)
And I added YUZU in nvidia control panel and turned on sync and triple buffering, but in the end it's the same.

![MAXIMIZE WINDOW](https://user-images.githubusercontent.com/69958962/183613993-2bdc1b91-b0e4-4aff-8122-71fe046e68cf.png)
![1080P WINDOW](https://user-images.githubusercontent.com/69958962/183614039-546b8c95-0da8-4307-9f86-1d080e468332.png)
![FULL SCREEN](https://user-images.githubusercontent.com/69958962/183614062-ccd97658-7cbc-46c8-97f8-130f9d4d2414.png)
![2022-08-09 18 08 42](https://user-images.githubusercontent.com/69958962/183614093-ea19f8d5-c923-45d4-a263-2459bb9edb07.png)

**Comment by G-Spawn** [comment]
do you have a gsync or freesync capable monitor?

**Comment by unuruu5760** [comment]
> do you have a gsync or freesync capable monitor?

yes. my monitor is freesync

**Comment by G-Spawn** [comment]
That can attribute to this kind of issue then. If you have ability to disable gsync-freesync that would be ideal for yuzu. Otherwise the workaround was like changing app focus or alt tabbing?

**Comment by unuruu5760** [comment]
> That can attribute to this kind of issue then. If you have ability to disable gsync-freesync that would be ideal for yuzu. Otherwise the workaround was like changing app focus or alt tabbing?

It is the same with App Focus and Alt+Tap. I changed the alt+tab and focus a lot to take a screenshot from the beginning.

**Comment by G-Spawn** [comment]
If you can then try disabling the feature. Gsync and freecync have been odd for yuzu for a long time now.

**Comment by G-Spawn** [comment]
If you can disable it'll help you narrow down if it is the culprit or not.

**Comment by unuruu5760** [comment]
> If you can then try disabling the feature. Gsync and freesync have been odd for yuzu for a long time now.

What function is disabled? freesync?
I turned off FreeSync. But the result is the same.

**Comment by G-Spawn** [comment]
Please upload a log when you can.

**Comment by unuruu5760** [comment]
> Please upload a log when you can.

I found the problem. It was because of the reshade. If I don't use reshade, it works fine, but when I use reshade, the frame drops in fullscreen and window size.
Interestingly, it shows the above symptoms even before applying the re-shade effect.
[yuzu_log.txt.old_no reshdae.txt](https://github.com/yuzu-emu/yuzu/files/9302781/yuzu_log.txt.old_no.reshdae.txt)
[yuzu_log_reshade.txt](https://github.com/yuzu-emu/yuzu/files/9302784/yuzu_log_reshade.txt)

**Comment by G-Spawn** [comment]
Interesting. At least you narrowed it down! I know some Reshade presets can bog down some heavier pc games so it wouldn't shock if it did similar with some heavy yuzu games.

**Comment by unuruu5760** [comment]
> Interesting. At least you narrowed it down! I know some Reshade presets can bog down some heavier pc games so it wouldn't shock if it did similar with some heavy yuzu games.

I found the cause of the performance degradation even before applying the reshade effect.
It no longer causes fps degradation when "generic depth" is turned off. Now you can freely use the reshade effect.
![2022-08-13 17 24 42](https://user-images.githubusercontent.com/69958962/184525003-bd2448a8-56b8-4e97-8215-29521129629f.png)
