### ISSUE TITLE
Request: HLSL Shader model 5 assembly support in Vulkan

### ISSUE THREAD

**Issue by kevincrans** [yuzu-emu/yuzu#8743]
Some say Vulkan is experimental, well GLASM is bugged.
Hey, Microsoft's assembly shaders are fast and supports Vulkan and AMD, why not use that? (and on Nvidia Maxwell/[tesselator quads features](https://www.nvidia.com/content/GTC-2010/pdfs/2157_GTC2010.pdf) maybe on D3D only tho)
Even tho SM5 might not increase performance on unsupported platforms, I always say, the PC port is the biggest attraction (maybe users use WSL/wine then or whatever).

**Comment by liamwhite** [comment]
See #6520

**Comment by kevincrans** [comment]
Relevant, although SM5 on Vulkan is still different

**Comment by liamwhite** [comment]
Yuzu already translates Maxwell shaders directly into SPIR-V for the Vulkan backend; this diagram implies using HLSL would add an extra step.

**Comment by kevincrans** [comment]
So the Diagram is wrong or is there no benefit in SM5 assembly?
