### ISSUE TITLE
disabling cpu debugging/ host MMU emulation not working

### ISSUE THREAD

**Issue by mightymariomanlol** [yuzu-emu/yuzu#8744]
hello, what I'm going to say is more about settings, if u want to know more here is the log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9293771/yuzu_log.txt)

anyway, so about the host MMU emulation, it has a lot to do with virtual memory.
to me i wish virtual memory wasn't really in yuzu in the first place, not that its bad because its a good idea and when it comes to yuzu u need Aa lot of power to use yuzu
i just wish there was a thing that people don't have to use, and that's CPU debugging and host MMU emulation heres the video

https://user-images.githubusercontent.com/107736543/183736045-2119e590-a1a6-472d-a9bd-cad20326f182.mp4

**Comment by german77** [comment]
You need to set cpu accuracy to debug mode

**Comment by mightymariomanlol** [comment]
how?

**Comment by G-Spawn** [comment]
you tried changing it in the config of emulator where CPU accuracy is?

**Comment by mightymariomanlol** [comment]
idek if i did

**Comment by G-Spawn** [comment]
Wouldnt hurt.

**Comment by gidoly** [comment]
seems functional here
how to disable:
enable cpu debugging on debug tab and disable host mmu options on cpu tab.
feel free to reopen issue if you still have problem on disable them.
