### ISSUE TITLE
Vsync for Vulkan + Double Buffering setting?

### ISSUE THREAD

**Issue by Missingphy** [yuzu-emu/yuzu#8747]
I've been testing this emulator, and have also been testing with RyuJinx and a few games like MK8DX and Mario Odyssey. I have also used CEMU in the past and they all work great with one exception.

In CEMU, there is a Double Buffering setting for Vsync, as well as a Triple Buffering one. Triple Buffering gives me duplicate/triplicate frames which make seem like the game is lagging, when in reality it is not (the fps counter marks 60fps always). Disabling vsync completely gives me horrible tearing, and Nvidia control panel's vsync option for programs won't work for me.

Double buffering is the only setting I have found to achieve perfect emulation, but unfortunately it is not present on Yuzu, and Vsync on OPENGL works, but every game crashes at some point. So a double buffering option for Vulkan would be greatly appreciated.

Currently using RyuJinx, will switch to Yuzu since it has more features, when the option is added. And someone kindly notify me if the option is indeed added as I do not have Yuzu/early Yuzu installed. Thanks!

**Comment by liamwhite** [comment]
see #8735

**Comment by Missingphy** [comment]
> see #8735

my apologies, would you merge my issue with that one? thanks

**Comment by Docteh** [comment]
@Missingphy check out tomorrows (12-13 hours from now) regular yuzu build. Or take your time.

**Comment by Missingphy** [comment]
> @Missingphy check out tomorrows (12-13 hours from now) regular yuzu build. Or take your time.

hello so uhm, unfortunately it's still the same, I get a lot of frame skipping but the emulator fps counter shows 60fps at all times, any other solution?
