### ISSUE TITLE
Kirby and the Forgotten Land-Hongtongtong Restricted Area - Cadres Called -can't cross the bridge

### ISSUE THREAD

**Issue by kukufeng** [yuzu-emu/yuzu#8749]
<img width="960" alt="Desktop Screenshot 2022 08 11 - 03 53 32 04" src="https://user-images.githubusercontent.com/32658719/184007792-fd39748f-eb7d-4ac2-8505-da2b79f1c382.png">

**Comment by G-Spawn** [comment]
please provide a log file and consider looking up a game walkthrough for that area you are stuck at in case you missed something.

**Comment by kukufeng** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9304303/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9304304/yuzu_log.txt.old.txt)

**Comment by kukufeng** [comment]
I searched the Internet for the way to pass the level, that is to hit the board, and then the board collapsed to pass, but I couldn't knock down the board, I was stuck in this level

**Comment by kukufeng** [comment]
https://www.youtube.com/watch?v=w1G_QenSuK0&ab_channel=kukufengkukufeng

**Comment by G-Spawn** [comment]
I would consider redumping the game from console to rule out corruption or oddity.

**Comment by G-Spawn** [comment]
this issue has been confirmed to be specific to you. you have to get through the bridge in sufficient enough time or you get stuck.  they are pretty generous with the timer as well.

**Comment by G-Spawn** [comment]
![unknown-36](https://user-images.githubusercontent.com/23653025/184065540-327d622c-4aa6-4d88-b1f7-87c77406be43.png)

**Comment by kukufeng** [comment]
thanks
