### ISSUE TITLE
Yuzu Crash while opening a game

### ISSUE THREAD

**Issue by Opuestos** [yuzu-emu/yuzu#8751]
I have this PC:
AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 
I have installed Yuzu  and i have followed all the steps, but when i open a game it doesn0t work and instantly crash

**Comment by G-Spawn** [comment]
update your gpu drivers and provide a log like the issue template you deleted asked for please.

**Comment by G-Spawn** [comment]
Please feel free to reopen issue when you can provide a log. https://yuzu-emu.org/help/reference/log-files/
