### ISSUE TITLE
Yuzu crashes randomly when there is a cinematic in The Legend of Zelda: Breath of the wild

### ISSUE THREAD

**Issue by dennajort** [yuzu-emu/yuzu#8753]
Hi ! When playing Breath of the Wild for some time, it sometimes crashes when there is a cinematic. For example during the blood moon, when you meet kass and he plays a song or when viewing a memory.

Version EA 2895
CPU Ryzen 5 5600X
GPU RTX 3060 Ti
Vulkan, scaling 1x, bilinear, no AA
No async shaders
CPU clock Auto

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9311532/yuzu_log.txt)

Thanks for the amazing work !

**Comment by G-Spawn** [comment]
Can you try using opengl the game has kind of preferred it for the last while. Can you also see if downgrading gpu driver to 512.95 helps any? Nvidia's newer driver is kind of weird for some generations of nvidia gpu. Issue happens mostly on older (pascal - maxwell) but it wouldn't hurt to see if it helps fix your vulkan issue. You can also try right clicking game and clearing vulkan pipeline cache to see if it is related to corrupted shader built as well.

**Comment by liamwhite** [comment]
This specific crash (`IncrementSyncpointMaxExt:86: Unreachable code!`) is fixed by latest EA (commit https://github.com/yuzu-emu/yuzu/pull/8467/commits/314f6675d0c1953887b9f6208f262e29254de113)
