### ISSUE TITLE
Feature request: drop IR and compile ARB / SPIR-V from GLSL or decompile directly from SPIR-V for performance.

### ISSUE THREAD

**Issue by kevincrans** [yuzu-emu/yuzu#8760]
Shaders work kind of slow on my Nvidia card, so I thought it needs to be enhanced.
If the switch was a normal system, it wouldn't matter so much, but it's a 64-bit 1ghz system.
So the point is, maybe converting things to and from the IR is an extra bottleneck, Khronos provides their tools to (de-)compile to and from Vulkan shaders, this way u can use standard shaders instead of an IR.

The only doubt I have is if SPIRV-cross is actually faster than the IR, so I recommend compiling it from GLSL.

I also don't know if the IR is already really much like one of these, meaning this is basically already how it works.

I have to add my system specs, I have 4 4.2ghz dual-threaded cores, a GTX1070 (8GB vram) and 32GB Ram

**Comment by liamwhite** [comment]
Generating SPIR-V directly from Maxwell shaders is extremely fast and accounts for <5% of shader compile time. The bottleneck in shader compilation has always been in the _driver_, which yuzu has no control over.
