### ISSUE TITLE
Metroid Dread Phantom Cloak Mode issue (OpenGL)

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#8762]
In OpenGL mode (GLASM or GLSL) Samus Phanotm Cloack (AKA stealth mode) makes player disappear completely. GLSL makes it all black. Correct shader is visible only in VK mode, but it runs way sluggish compared to OGL.

GTX 1070 8GB, NVidia 512.96 SD

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9331671/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Would you mind seeing if similar happens with auto-default anisotropic filtering? Some games act up when anisotropic is set. Wouldn't hurt to try disabling async shaders as well (the one in config >> graphics >> advanced)

**Comment by Hexaae** [comment]
Oh, you're right:
**Use asynchronous shader building (Hack)** = OFF
solves the issue when in Phantom Cloack mode under OpenGL.
Thank you for quick reply.

**Comment by G-Spawn** [comment]
Glad that helped 🙏 I may leave issue open for now as async shaders still technically needs to be fixed here.

**Comment by gidoly** [comment]
closing as disabling hack fixes issue
