### ISSUE TITLE
SDL motion stop working after controller reconnect

### ISSUE THREAD

**Issue by Labaman** [yuzu-emu/yuzu#8763]
SDL motion stop working after controller reconnect
The Nintendo switch pro controller via blluetooth.
If you disconnect and reconnect the controller from the PC during the game in any way, the SDL movements stop working.
Also, I still have the problem with the occasional random disconnection of the controller (as described in https://github.com/yuzu-emu/yuzu/issues/5941).
The problem occurs in both Appimage and Flatpak versions.
Yuzu version: 1130
OS: Arch Linux
How you reproduce:
- Connect the Nintendo Pro controller via Bluetooth
- Launch any game with Yuzu 
- Make sure the sdl motion works
- Any way you can break the connection (restart your bluetooth, disconnect the controller)
- Reconnect the controller
- Everything will work except the motion sensor
[yuzulog.zip](https://github.com/yuzu-emu/yuzu/files/9331676/yuzulog.zip)

**Comment by dlutwy** [comment]
https://github.com/yuzu-emu/yuzu/issues/7915
same
