### ISSUE TITLE
Diablo 2 Resurrected: Glitches with lighting. 

### ISSUE THREAD

**Issue by Labaman** [yuzu-emu/yuzu#8765]
Diablo2 Resurrected has lighting glitches: instead of playing light on textures, you see flickering and flashes of light nearby the light source.
The problem is reproduced on both Vulkan and OpenGL backend.

- Yuzu Version: 1131
- Steps to reproduced: Just start new game and walk around start camp
- System specs: 
-System:
  Host: rog-lab Kernel: 5.19.1-zen1-1-zen arch: x86_64 bits: 64 compiler: gcc
    v: 12.1.1 Desktop: GNOME v: 42.4 Distro: Arch Linux
Machine:
  Type: Laptop System: ASUSTeK product: ROG Strix G712LWS_G712LWS v: 1.0
    serial: <superuser required>
  Mobo: ASUSTeK model: G712LWS v: 1.0 serial: <superuser required>
    UEFI: American Megatrends v: G712LWS.314 date: 04/27/2021
CPU:
  Info: 6-core model: Intel Core i7-10750H bits: 64 type: MT MCP
    arch: Comet Lake rev: 2 cache: L1: 384 KiB L2: 1.5 MiB L3: 12 MiB
  Speed (MHz): avg: 3598 high: 3601 min/max: 800/5000 cores: 1: 3600
    2: 3600 3: 3588 4: 3600 5: 3594 6: 3599 7: 3600 8: 3600 9: 3600 10: 3600
    11: 3600 12: 3601 bogomips: 62399
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel CometLake-H GT2 [UHD Graphics] vendor: ASUSTeK driver: i915
    v: kernel arch: Gen-9.5 bus-ID: 00:02.0
  Device-2: NVIDIA TU104M [GeForce RTX 2070 SUPER Mobile / Max-Q]
    vendor: ASUSTeK driver: nvidia v: 515.65.01 arch: Turing bus-ID: 01:00.0
  Display: x11 server: X.Org v: 21.1.4 with: Xwayland v: 22.1.3 driver: X:
    loaded: modesetting,nvidia unloaded: nouveau
    gpu: i915,nvidia,nvidia-nvswitch resolution: 1: 3440x1440 2: N/A
  OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 22.1.6
    direct render: Yes
Info:
  Processes: 359 Uptime: 1h 1m Memory: 31.14 GiB used: 9.55 GiB (30.7%)
  Init: systemd Compilers: gcc: 12.1.1 clang: 14.0.6 Packages: 1274
  Shell: Zsh v: 5.9 inxi: 3.3.20

LOGS:
[d2yuzulog.zip](https://github.com/yuzu-emu/yuzu/files/9333810/d2yuzulog.zip)
---------------
Video of the gameplay with a demonstration of the problem: https://disk.yandex.ru/i/lYbryKkbFbkMPA

**Comment by Labaman** [comment]
Also, sometimes textures are broken:
Glitch:
![Снимок экрана от 2022-09-03 23-20-55](https://user-images.githubusercontent.com/30574992/188286952-17cebe3e-ea17-4626-aaf6-fbaad909abae.png)
![Снимок экрана от 2022-09-03 23-21-40](https://user-images.githubusercontent.com/30574992/188286959-3419c1d6-7677-45b3-8cdf-ae782e7126cb.png)

**Comment by benderscruffy** [comment]
#9194 might fix it

**Comment by Labaman** [comment]
@benderscruffy Unfortunately, no. The problem with flickering and glare is still relevant.

**Comment by Labaman** [comment]
After a long break, I decided to recheck the relevance of the problem, and found that the problem was no longer relevant.
The glitches with the lighting are gone.
At the moment, the configuration is as follows:
Yuzu 1431
Diablo 2 version 1.0.3.0
Nvidia Drivers version 530.41.03
OS: Arch Linux x86_64 
Kernel: 6.3.1-zen2-1-zen
