### ISSUE TITLE
Xenoblade Chronicles 3 - Graphical issues [AMD/Vulkan]

### ISSUE THREAD

**Issue by Armakeen** [yuzu-emu/yuzu#8768]
Hello, I'm using Yuzu version 1134
There are still major graphical glitches in some areas of the game. I am in chapter 3, and it's literally unplayable. I don't even see what's happening on the screen in those areas: Uraya's Tunnels & Great Cotte Falls

I have an AMD graphic card and I'm using Vulkan. My drivers are up to date
The Vulkan_Workaround mod made by theboy181 sadly didn't fix the issue

<a href="https://zupimages.net/viewer.php?id=22/33/5q20.png"><img src="https://zupimages.net/up/22/33/5q20.png" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=22/33/9uq4.png"><img src="https://zupimages.net/up/22/33/9uq4.png" alt="" /></a>

**Comment by Pvictox** [comment]
This issue is the same as #8732. Unfortunately there is still no solution to this problem and by solution I mean this area in a playable way using AMD/VULKAN

**Comment by danky1** [comment]
the work around for this, is revert to driver 22.6.1 and run area in opengl.

**Comment by Pvictox** [comment]
> the work around for this, is revert to driver 22.6.1 and run area in opengl.

Why revert the drive version? Version 22.8.1 (recent) has problems?

**Comment by danky1** [comment]
> > the work around for this, is revert to driver 22.6.1 and run area in opengl.
> 
> Why revert the drive version? Version 22.8.1 (recent) has problems?

most amd users were crashing in opengl on 22.7.1 and 22.8.1

**Comment by Pvictox** [comment]
> > > the work around for this, is revert to driver 22.6.1 and run area in opengl.
> > 
> > 
> > Why revert the drive version? Version 22.8.1 (recent) has problems?
> 
> most amd users were crashing in opengl on 22.7.1 and 22.8.1

Yeah, I can confirm that.

**Comment by G-Spawn** [comment]
https://github.com/yuzu-emu/yuzu/issues/8712 Closing in favour of existing issue(s). Please continue there.
