### ISSUE TITLE
Feature Request - Remove extra source files from already deployed builds on next update 

### ISSUE THREAD

**Issue by Masamune3210** [yuzu-emu/yuzu#8769]
Was reading the Progress Report and got to the part where its talking about the bundled source files that come with yuzu. Are these also being removed from any current install, and if not could that be a option? I know its not a lot but if the files are truly extra to people who have no current intention of building it, would be nice if the space was saved say for people with space constraints

**Comment by Docteh** [comment]
its down to 8 megabytes. not much of a saving. you could make a script that deletes it once a day.

**Comment by Morph1984** [comment]
This is more a job for the installer to optionally provide the source during installation. We cannot make it optional when bundling as we must fulfill the GPL license requirements.
