### ISSUE TITLE
Super Mario Odyssey - Emulator avoids crash

### ISSUE THREAD

**Issue by GRAnimated** [yuzu-emu/yuzu#8776]
In Super Mario Odyssey, the game normally crashes when the first moon is collected in any scenario other than the first visit to Cascade Kingdom. Yuzu has never crashed collecting this moon, and at some point within the last year or so, changed from being a softlock to a timefreeze where Mario can still move around.

The crash on console can be seen in this video https://youtu.be/7jnF9L72Md4?t=81

Here is a save file on File 4 that brings you into a reproduceable case. Collect the first moon and wait for the bridge cutscene to play out.
[First Moon Crash.zip](https://github.com/yuzu-emu/yuzu/files/9367932/First.Moon.Crash.zip)

This is all I can get my error log to show. It spams this while the game continues to run.
![image](https://user-images.githubusercontent.com/23510999/185302957-f4f6fb5c-d722-4547-80be-4698af8c64e6.png)

When yuzu was much younger (probably just a year ago), it was a softlock there. For some reason, now, the cutscene camera that would start there doesn't, so Mario is able to move around freely as the demo state never gets cleared.

I'm hoping this could finally be fixed, and hopefully it would make yuzu fully viable for debugging mods.

**Comment by liamwhite** [comment]
It is possible to make the emulator crash the game on unmapped memory accesses. However, it has some performance impact to allow it to be able to stop emulation in this condition, so I would gate it behind a setting. Is this the desired behavior?

**Comment by GRAnimated** [comment]
Making the emulator/game crash would be desirable. (it would be nice if I can pull a stack trace from GDB though, so maybe the game should just freeze?) How big is the performance hit? I think it would be the correct behavior for it to crash, but I understand putting it behind an option either way.
