### ISSUE TITLE
Zelda Breath of The Wild randomly crash

### ISSUE THREAD

**Issue by SeaKestrel** [yuzu-emu/yuzu#8778]
I was playing and Zelda BOTW crashed. 
I'm on Ubuntu 22.04 using the version yuzu 1136
Here's the log, there is no way to reproduce this crash
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9373639/yuzu_log.txt.old.txt)

**Comment by gidoly** [comment]
ditto of linked issue
