### ISSUE TITLE
XCI,NCA Bug Keys 

### ISSUE THREAD

**Issue by EmulationChannel** [yuzu-emu/yuzu#878]
Personal I followed the instructions from the website of https://github.com/yuzu-emu/yuzu/wiki/Dumping-Decryption-Keys-from-a-Switch-Console for I could open XCI, NCA plus Yuzu simply says min says that my keys are not valid and that the errors of the images ah low as you can notice some suggestion and my keys are correctly for errors of telemetry_id that is also giving yuzu-canary, yuzu-nightly
![anotacao 13](https://user-images.githubusercontent.com/37957125/43461329-a06da808-94a9-11e8-9d00-56281b4d4d1e.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2245378/yuzu_log.txt)

**Comment by bunnei** [comment]
This is not a feature that has even been merged yet. If you have questions/issues with it, I suggest asking on the PR, or on Discord.

**Comment by EmulationChannel** [comment]
@bunnei Oky plus this feature is in Canary Yuzu Follow this PR here https://github.com/yuzu-emu/yuzu/pull/849
