### ISSUE TITLE
Goat Simulator The Goaty Crashes at Launch No Matter What

### ISSUE THREAD

**Issue by Yosh0000** [yuzu-emu/yuzu#8787]
Using The Latest Mainline Build And The Recommended Nvidia Drivers Game Crashes No Matter What With Both Open GL And Vulkan, Already Contacted Support But The solution I Was Provided Didn't Work

Specs:
Intel Core I7 10th Gen 10750H
16gb Ram
Geforce Rtx 2070 Laptop Edition

**Comment by benderscruffy** [comment]
duplicate of #7775

**Comment by Yosh0000** [comment]
Though it wasn't the
