### ISSUE TITLE
Triangle Strategy: Graphical Issues

### ISSUE THREAD

**Issue by modoxy** [yuzu-emu/yuzu#8788]
![yuzu 1138 _ TRIANGLE STRATEGY (64-bit) _ 1 0 0 _ NVIDIA 2022_8_19 21_59_50](https://user-images.githubusercontent.com/89689473/185636687-bbfeb082-b832-4f9a-a198-bd815cf1fb78.png)
![新建 BMP 图像](https://user-images.githubusercontent.com/89689473/185638126-ca103fa3-9c8c-421a-aaf8-8a98e5891c71.jpg)
![无标题](https://user-images.githubusercontent.com/89689473/185646006-f35bbf4b-b3f9-4a46-9fc0-aa4f3d394fcd.jpg)

Hello yuzu developers, I'm an yuzer from China. Starting in 2021, because orochi 3 ultimate began to contact yuzu emulator

.As an SRPG enthusiast, in April this year I started using the yuzu emulator to play the HD 2D SRPG game triangle strategy produced by SE.The first time I played the game, I encountered a bug like the one shown, which appeared in almost every scene, which caused me to delete the game halfway through the main storyline

Four months later, when I opened this open triangle strategy with the latest version of yuzu, the bug was still not solved.I really like this game and hope that the developers can fix these graphics issues as soon as possible.

Also, in my recent tests of HD 2D games, only triangular strategy had this serious graphics problem. Neither Tripartite nor the recent LIVE A LIVE found similar problems

My English level is not very good, so I can only communicate with you with a translator.If there is something that does not go well, please be more inclusive。

**Comment by G-Spawn** [comment]
issues for games can take as long as they need to be fixed. they will try to address it when they can but some are harder to solve than others. it's a waiting game essentially.

https://yuzu-emu.org/help/reference/log-files/ please provide a log for good measure like the issue template asked

**Comment by Bjorn29512** [comment]
i recommend disabling depth of field in the game graphic settings to fix that
