### ISSUE TITLE
Maintenance tool is broken

### ISSUE THREAD

**Issue by pastel-n0va** [yuzu-emu/yuzu#8789]
it cant uninstall 😠

**Comment by german77** [comment]
Delete the folder in `%localappdata%/yuzu` to uninstall the executables and the folder in `%appdata%/yuzu` to uninstall all data. Like saves, fw, nand, etc.

**Comment by pastel-n0va** [comment]
uh nevermind i found the yuzu app, now i need the rom file for Pokemon Sword (i cant go to an external website, so you might aswell hand me the file for it)

**Comment by pastel-n0va** [comment]
uh nevermind i found the yuzu app

**Comment by Docteh** [comment]
![duck-no](https://user-images.githubusercontent.com/190571/186042810-1370e1ea-c6a9-4c5b-b813-562c6f25a2a4.gif)

**Comment by G-Spawn** [comment]
> 

You would always be expected to provide everything you want to emulate from your own nintendo switch console & purchases.
