### ISSUE TITLE
New Super Mario goes black

### ISSUE THREAD

**Issue by rube200** [yuzu-emu/yuzu#8792]
Version: Last release (not experimental) at 19/08/2022 - 1138
Game: New Super Mario Bros U Deluxe
Extras: None
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9385690/yuzu_log.txt.old.txt)
Description:
After starting the game it loads and asks to press L + R, i do it and after that goes completly black but still shows 60fps and 15ms

**Comment by german77** [comment]
We don't allow piracy
