### ISSUE TITLE
[Optimization] Parallel shader compile at the driver level

### ISSUE THREAD

**Issue by LifeIsStrange** [yuzu-emu/yuzu#8800]
https://registry.khronos.org/OpenGL/extensions/ARB/ARB_parallel_shader_compile.txt
Seems to me like a worthwhile optimization.

**Comment by liamwhite** [comment]
Yuzu's shader compiler already uses num_cores - 1 threads to compile shaders through a shared context.
https://github.com/yuzu-emu/yuzu/blob/7fab7b829cf53c0f64ef43fb36418657b4acd8dd/src/video_core/renderer_opengl/gl_shader_cache.cpp#L547-L550

**Comment by LifeIsStrange** [comment]
Thanks for the quick answer.
Well that seems similar although I wonder wether this is the same. I don't see why this extension exists if it can be trivially emulated with a threadpool.
I suspect there must be a subtle difference, with the extension the threads are (?) owned by the user space GPU driver and not by the application? That would allow maybe to allocate multiple threads to a single shader while current yuzu approach would be one thread per shader?

No idea, not my domain of expertise

**Comment by liamwhite** [comment]
GLSL compilation is generally quite slow due to the amount of string parsing involved. ARB shaders are quite a bit faster in this regard, but we intend to put most future focus for the project in the Vulkan backend, which already offers extremely fast shader compilation times.
