### ISSUE TITLE
Icon of some Chinese regional games will not show in the gamelist.

### ISSUE THREAD

**Issue by MichaelMBJ** [yuzu-emu/yuzu#8802]
Some games lost their icon in yuzu‘s gamelist and properties
These games' language only support Simplified Chinese or Traditional Chinese.
EA 2914
Title ID : 010038D0133C2000 
Name : “Shin Megami Tensei” 
Chinese name : “真・女神轉生Ⅴ”
Region : HongKong(should be HK only)
![image](https://user-images.githubusercontent.com/111728618/185855781-a7058e13-27ac-4f71-93d4-28aeca54af8c.png)

![IMG_7459(20220822-142816)](https://user-images.githubusercontent.com/111728618/185853832-9aa13ee2-07e3-4506-b3ef-665d74029a83.PNG)

![IMG_7460](https://user-images.githubusercontent.com/111728618/185853787-4172bbc1-3d0d-42a7-bf4d-cdd80d5a8e73.PNG)

When I extract the Nca files.The icon file is exist in the right folder.
![image](https://user-images.githubusercontent.com/111728618/185857529-354cc943-fedc-4ea8-8675-bdbd69dfdd0f.png)

Ryujinx can read the icon and  show it correctly.
![image](https://user-images.githubusercontent.com/111728618/185857972-4e557b98-1506-4d10-b460-cacf4e2fd511.png)

**Comment by yuwenhua653** [comment]
Fixed by https://github.com/yuzu-emu/yuzu/pull/10591
