### ISSUE TITLE
Eiyuden Chronicle: Rising - Some textures are not being rendered

### ISSUE THREAD

**Issue by MarcoEstevez** [yuzu-emu/yuzu#8806]
Current yuzu render, Vulkan and OpenGl
![image](https://user-images.githubusercontent.com/3447089/186137990-bc0dba3c-f5b4-481c-8d9a-d76cfaec9fca.png)

Correct rendered scene
![image](https://user-images.githubusercontent.com/3447089/186138419-4f8a164e-85d0-4f96-87ea-1c4f824310dc.png)

**Comment by mcastellonc201** [comment]
I update the SDL and Decoder, for yuzu-cmd.exe.
SDL from Vulkan SDK v1.3.224.0
HEVC Decoder from FFMPEG v5.1

https://download1347.mediafire.com/8xv27g6dn7sg/o7mc033sjatesmt/yuzu_cmd.zip

Good luck.
Regards

**Comment by mcastellonc201** [comment]
QT version.
https://github.com/mcastellonc201/yuzu_cmd-update082022/blob/main/Release.zip

Thanks.

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/reference/log-files/ provide a log when you can please @MarcoEstevez

**Comment by MarcoEstevez** [comment]
Here it is:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9446028/yuzu_log.txt)

**Comment by G-Spawn** [comment]
We dont support piracy here.
