### ISSUE TITLE
Pokemon Sword/Shield stuck in the Stow-on-Side gym with keyboard

### ISSUE THREAD

**Issue by Legarad** [yuzu-emu/yuzu#8814]
stuck in the Stow-on-Side gym, the gym mission asks to rotate the Control Stick left or right and it is impossible to do it with the keyboard. Any solution?

**Comment by german77** [comment]
Map your mouse to the stick and move the mouse in circles. This is a yuzu forum for issues. Not support. Ask on discord if you need support
