### ISSUE TITLE
Games are running normally but have no video output 

### ISSUE THREAD

**Issue by MichaelMBJ** [yuzu-emu/yuzu#8815]
Only Vulkan mode cause the issue.

Game is running(audio is playing)but it has no video output since EA2918.

Xenoblade Chronicles,
![image](https://user-images.githubusercontent.com/111728618/186551526-81fa76de-5b07-4ce9-8f8a-43d3557226e1.png)
Diablo 3,
![image](https://user-images.githubusercontent.com/111728618/186553832-075e6c98-c795-4663-bc2e-603c0db5ef65.png)
Astral Chain
![image](https://user-images.githubusercontent.com/111728618/186553303-ae19ed5d-9276-44ed-9806-e092b3c57d31.png)
The issues also happen in Xenoblade Chronicles2 and Xenoblade Chronicles3.

Diablo 3 has another issue.If audio output Engine is auto,game keep 15Fps.
![image](https://user-images.githubusercontent.com/111728618/186553729-782cbcc3-f644-41d9-9f73-95cc83026012.png)
Game will run prefectly if audio output Engine change to SDL2.

**Comment by xSchroe** [comment]
delate the shader cache, i was having the same problem with xc3.

**Comment by MichaelMBJ** [comment]
Thank you very much for helping me solve the problem.

But if it could fix i won't lost and rebulid my shader pipline cache.
It is really too much, like  this
![image](https://user-images.githubusercontent.com/111728618/186555761-17bbe42c-da71-4195-b7f1-80e18154779c.png)
Building shader pipline cache affects the smoothness of the game.

**Comment by DiegoMadGlez** [comment]
This is caused by #8752 only way to fix it, it's cleaning shader caches

**Comment by MichaelMBJ** [comment]
> This is caused by #8752 only way to fix it, it's cleaning shader caches

Thank you for your reply.
I will clean all old shader caches and close the issues^^
