### ISSUE TITLE
Yuzu crash after open Super Mario Odyssey with OpenGL

### ISSUE THREAD

**Issue by Morigaz** [yuzu-emu/yuzu#8817]
I have an i5, gtx 1650 super, 12gb ram

**Comment by Docteh** [comment]
https://raw.githubusercontent.com/yuzu-emu/yuzu/master/.github/ISSUE_TEMPLATE/bug-report-feature-request.md 

I notice the issue template doesn't mention the discord 

https://yuzu-emu.org/ has a link to https://discord.gg/u77vRWY

**Comment by G-Spawn** [comment]
@Morigaz ^ Provide a log file or issue will be closed like your previous ones .

**Comment by G-Spawn** [comment]
Closing for lack of provided information required to help user. Please just join discord if you need help.
