### ISSUE TITLE
Xenoblade Chronicles 3 crashes in a cinematic fighting the final boss.

### ISSUE THREAD

**Issue by xSchroe** [yuzu-emu/yuzu#8820]
Build: Yuzu EA 2919
Game version : 1.1.0
Api: Vulkan
CPU : AMD Ryzen 5 5600X 6-Core Processor
GPU : Rx 5700
VRAM : 8GB
RAM : 32GB
OS : Windows 11 Version 21H2 (Build 22000.832)
Driver : 22.8.2

Someone else having this issue?.

video:

https://user-images.githubusercontent.com/110557543/186787769-f2d4594a-f93d-4865-a2b9-8c05bbfed30a.mp4

save:
[bf3game00a.zip](https://github.com/yuzu-emu/yuzu/files/9428818/bf3game00a.zip)

Log:
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9428802/yuzu_log.txt.old.txt)

**Comment by G-Spawn** [comment]
The log you sent covered next to nothing about actual issue. Please try sending another.

**Comment by xSchroe** [comment]
oh, my bad, didnt see the log was almost empty. i will play that part again and send another log, it might take a couple of hours, that part of the game is quite long to reach the crash point.

**Comment by G-Spawn** [comment]
No rush whenever you can 🙏  Thank you!

**Comment by xSchroe** [comment]
alright, played it a second time, didnt crash. im closing this issue.
