### ISSUE TITLE
Dead or Alive extreme 3

### ISSUE THREAD

**Issue by Sonnebirke** [yuzu-emu/yuzu#8821]
Found two annoying bugs. Anyone had similar experiences?
My rig:
Ryzen 3600
RTX 2060
16GB
SSD

1.)
https://www.youtube.com/watch?v=jSH4iEmz8IU
annoying reproduce laggs in the main menu.
https://drive.google.com/file/d/1mc7zzKajVKdnODPYobQJyZEjcudzZoIG/view?usp=sharing

2.)
https://www.youtube.com/watch?v=-oTV3Imkusk
Performance issues every few matches, or should I rather say it feels out of round and slightly laggy.
Over the log file: The match in the video was the last one, after that I closed Yuzu, so only thats important, not the beginning.
https://drive.google.com/file/d/1MAM1yOEIHcMo_wjKcMPcIQHYJvx3x_rH/view

**Comment by G-Spawn** [comment]
qe dont bother to support piracy here
