### ISSUE TITLE
[Super Mario Maker 2, yuzu 1044] Crash when respawning in a 3D World style level

### ISSUE THREAD

**Issue by Catomax262** [yuzu-emu/yuzu#8823]
For some reason, in the 3rd job level on Story mode, whenever i die, the game may crash or slightly lag for a moment.
Specs:
GPU: NVIDIA GeForce GTX 1050 Ti
CPU: Intel Core i5-8400 CPU @ 2.80GHz (6 CPUs)
Memory: 16 Gigabytes
API: OpenGL
Shader support: GLASM
Graphics: High
Console mode: Docked

**Comment by G-Spawn** [comment]
please provide a log file. be sure not to use latest gpu driver for nvidia either. your older gpu will have issue with it. stick to 512.95 if you aren't already.

**Comment by Catomax262** [comment]
Fixed. It's just that it was OpenGL and not Vulkan.
