### ISSUE TITLE
Feature request: Select games with controller

### ISSUE THREAD

**Issue by Janmm14** [yuzu-emu/yuzu#8825]
Allow simple selection of games with buttons up - down - a 
Maybe left-right for opening / closing folders (a also for toggling open/close of folders)

Could maybe be implemented similar to hotkeys (in general section of the settings), just that it disables ingame.

**Comment by Norstyrm** [comment]
This was already added to yuzu with this pull request: https://github.com/yuzu-emu/yuzu/pull/7452

**Comment by german77** [comment]
Good needs we already have that. Enable controller navigation on advanced input settings

**Comment by andygrillo** [comment]
With multiplayer now added, it would be great to be able to select rooms and then return to a game using the controller (I play with steam OS). Could this be added to controller navigation ?
