### ISSUE TITLE
Problems with update Flatpak version of Yuzu

### ISSUE THREAD

**Issue by Labaman** [yuzu-emu/yuzu#8826]
There have been problems with updates to the flatpak version of yuzu for over a month now. 
What's wrong?
Is the Flatpak version no longer supported?

**Comment by liamwhite** [comment]
Need more info. Are there Flatpak-exclusive crashes, etc. that are not already reported on its [issue tracker](https://github.com/flathub/org.yuzu_emu.yuzu/issues)?

**Comment by Labaman** [comment]
No, that's not what I mean.
![Снимок экрана от 2022-08-27 22-46-41](https://user-images.githubusercontent.com/30574992/187046074-f7f86564-03c4-430f-8b56-739137cf54f1.png)

Either your automation is broken, or there is a problem with alerts (unless, of course, support is discontinued).
The current version of Yuzu on flathub is 1140. Autobuilds of the last 7 builds have not been validated.
There was also a problem last week with bot builds not merging with the main build. As a result, version 1130 was updated directly to 1139.
Actually hence the question - is the flatpak version over or what?

**Comment by german77** [comment]
There's no reason to kill the flatpak version. But I don't know who is exactly in charge of that

**Comment by liamwhite** [comment]
It looks like there is some kind of issue with the zstd dependency from the build logs, but it's not my specialty. No, the flatpak builds aren't dead, there just will have to be some delay while it is investigated.

**Comment by Docteh** [comment]
Copying the relevant error over here. I took a look through the PR's for [1141](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1141) and it's looking like #8660 instigated it, but...
```
CMake Error in src/common/CMakeLists.txt:
  Imported target "PkgConfig::libzstd" includes non-existent path

    "/usr/local/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

Kind of odd to see on a runner, PkgConfig is supposed to look around for an item and report back where it is, but it's clearly not reporting back properly, it's also not reporting an error itself😅

**Comment by liushuyu** [comment]
Sorry for the inconvenience, this should have been fixed by now.

Please check the update in your OS-provided Flatpak manager.
