### ISSUE TITLE
[Coursed to Golf] Doesn't boot

### ISSUE THREAD

**Issue by pacoa-kdbg** [yuzu-emu/yuzu#8836]
Yuzu mainline 1150 and EA 2924

Game : Coursed to Golf
Version :Base game

System details :
 CPU : R9 3900X
 GPU : NVIDIA RTX 3080
 RAM : 16GB
 OS : W11 

full log : 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9457875/yuzu_log.txt)

**Comment by benderscruffy** [comment]
using the latest EA and mainline
this is still an issue
