### ISSUE TITLE
Streets of Rage 4 upside down on Vulkan (Intel, AMD and Android)

### ISSUE THREAD

**Issue by rgbarros120** [yuzu-emu/yuzu#8839]
Another bug for your collection. The game is upside down. It was not resolved according to the information in the changelogs. On Ryujnxy this has already been resolved only on yuzu that is buggy.

My Specs: Radeon RX 560 OC 4GB; RYZEN 5 1600; 16GB DE RAM.
DRIVER: 22.8.1

![Bug](https://user-images.githubusercontent.com/73244003/187778440-8b356b6a-50e9-4b70-ac5d-3ad5113ef241.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9464883/yuzu_log.txt)

**Comment by prog-amateur2** [comment]
Hello, I have the same strange issue. Would it be related to the "gyroscope" aspect ? Thank you

**Comment by AtlasSkyholder** [comment]
Yup, I got this issue too.
It used to crash the emulator when you tried to launch it, they fixed that.

Now, when you launch the game, the window stays black while there is sound playing, so the intro animation does not play, when you press a button on the controller, you are sent to the start menu that is displayed upside down.

AMD driver: 22.10.3
Yuzu ver: 1222

CPU: AMD 6 core 5600x
GPU: RX 6700XT
RAM: 32Gb 3200Mhz
OS: Windows 10

**Comment by Squall-Leonhart** [comment]
This is probably due to a lack of viewport swizzle support on AMD.

**Comment by lacrdeveloper** [comment]
Yes same Problem  in pc ryzen 4800H and RTX 5600M amd radeon
also in android:  xiaomi pad 5

**Comment by imranali4** [comment]
Hi, same issue on steam deck

**Comment by NicoFC34** [comment]
Hi, same problem for me on steam deck too...

**Comment by shadow2560** [comment]
Not only Vulcan problem, with Opengl on Steam Deck the problem is also present.

**Comment by EmuAl** [comment]
yes, i have same issue, game is rendered upside down and mirrored
i have AMD 6900XT GPU

**Comment by EmuAl** [comment]
works now for me with the new fix, thank you

**Comment by NicoFC34** [comment]
It works now, thanks a lot.
But there is still a problem during cinematics.
The screen stays black, the sound works ans only subtitles are displayed. 
Am I the only one to have this problem ?
