### ISSUE TITLE
Yuzu deleting SDMC folders and data

### ISSUE THREAD

**Issue by Brawlballbob19** [yuzu-emu/yuzu#8840]
I dumped Smash Ultimate's romfs to sdmc, I also installed Ultimate Mod Manager. Everything was good until today when I went to yuzu sdmc folder and both the Ultimate Mod Manager folder and the dumped romfs folder were gone. I don't think this a UMM problem as that wouldn't result in the romfs data being gone.

**Comment by german77** [comment]
Yuzu doesn't delete any file on it's own specially sdmc.

**Comment by MysticExile** [comment]
Closing per above as it's not a yuzu issue
