### ISSUE TITLE
Mod fill by error Code

### ISSUE THREAD

**Issue by bagarang** [yuzu-emu/yuzu#8845]
dear creator, would you like to check that code. when im open that mod using notepad that fill by error code.. it's that okay ? 

![image](https://user-images.githubusercontent.com/110575081/188045339-e94a39e9-fc82-4190-bf03-2691cfc5c1aa.png)

**Comment by german77** [comment]
This forum is for yuzu issues. Not for general user support. Please feel free to ask on our discord.
