### ISSUE TITLE
SDL motion - PS5 controller motion stops working after a while

### ISSUE THREAD

**Issue by kkhair** [yuzu-emu/yuzu#8846]
The PS5 controller is connected via bluetooth, when I start Yuzu, the sdl motion works perfectly, but after playing for a while it stops, and I have to restart Yuzu to get to work again.
Turning the controller off and back on does not solve the issue 

The game is Paper Mario: The Origami King

**Comment by Dev-draco** [comment]
When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of yuzu you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

**Comment by german77** [comment]
Please test the artifact of the linked PR once it's done compiling
