### ISSUE TITLE
Super Mario 3D All-Stars - Issues with languages

### ISSUE THREAD

**Issue by cabca123** [yuzu-emu/yuzu#8850]
Hello!

The language displayed in each game does not correspond to the one chosen in the main menu and it varies depending on the system language. Here are some test:

System language:  English

Mario 64 displayed in English 
Mario Sunshine displayed in English
Mario Galaxy displayed in English

System language: Spanish

Mario 64 displayed in Japanese
Mario Sunshine displayed in English
Mario Galaxy displayed in Spanish

System language:  French

Mario 64 displayed in French
Mario Sunshine displayed in English
Mario Galaxy displayed in French

All 3 games are always displayed in the indicated language, even if I choose another language in the menu.

Thanks

**Comment by MegaMimh** [comment]
Indeed to this day, still the same problem.
I hope it will be fixed soon.
