### ISSUE TITLE
Nintendo Pro Controller is disconnected when you use the motion sensor in Yuzu.

### ISSUE THREAD

**Issue by Labaman** [yuzu-emu/yuzu#8852]
Nintendo Pro Controller is disconnected when you use the motion sensor in Yuzu.

**Steps for reproduce:**
Launch a game with motion control support (I tested with Zelda BOTW and Super Mario Odyssey).
In the case of Super Mario Odyssey:
Start the game.
Gain the ability to throw the hat. Perform several hat throws using the motion controls (circular, up/down, etc.).
After a few throws, the controller will turn off (the lights on the controller go out). After reconnecting the SDL motion will not work  (https://github.com/yuzu-emu/yuzu/issues/8763 https://github.com/yuzu-emu/yuzu/issues/8846).  

**Additional info:**
Tested with several controllers to rule out hardware failure. 
This problem is reproduced only when using Yuzu. 
When using motion control in Ryujinx or Steam - the controller is not disconnected.

**Logs:**
[log_yuzu_mario.zip](https://github.com/yuzu-emu/yuzu/files/9482274/log_yuzu_mario.zip)

**System specs:**
Yuzu version: 1154
OS: Arch Linux
The problem occurs in both Appimage and Flatpak versions.

**Comment by OZtistic** [comment]
The team are aware of the issue, it doesn't seem to only affect Pro Controllers.
There is a current PR that may possibly fix this issue here: #https://github.com/yuzu-emu/yuzu/issues/8852
is it not merged yet, as it requires some testing to ensure it fixes the issue.

**Comment by german77** [comment]
Motion is enabled from the very moment you start yuzu to keep an accurate track of the position of your controller. There's no game motion broke my controller. However rumble has been reported to cause some issues.

Disable vibrations and see if it happens. while you are on it test the artifact of the PR OZ linked

**Comment by Labaman** [comment]
@german77 Yes, after disabling vibrations the controller does not disconnect (at least not as often as before)

> while you are on it test the artifact of the PR OZ linked

Tested it. Unfortunately, no change. Logs in the PR discussion. SDL still does not work after reconnecting the controller. Doesn't matter if it was disabled due to a vibration bug or if I disabled it manually (sync button)

**Comment by mcastellonc201** [comment]
Use: 
yuzu-cmd.exe

add to file: %appdata%\yuzu\config\sdl2-config.ini

[ControlsP0]
button_a=engine:sdl,guid:030000007e0500000920000000006800,button:0
button_b=engine:sdl,guid:030000007e0500000920000000006800,button:1
button_x=engine:sdl,guid:030000007e0500000920000000006800,button:2
button_y=engine:sdl,guid:030000007e0500000920000000006800,button:3
button_minus=engine:sdl,guid:030000007e0500000920000000006800,button:4
button_home=engine:sdl,guid:030000007e0500000920000000006800,button:5
button_plus=engine:sdl,guid:030000007e0500000920000000006800,button:6
button_lstick=engine:sdl,guid:030000007e0500000920000000006800,button:7
button_rstick=engine:sdl,guid:030000007e0500000920000000006800,button:8
button_l=engine:sdl,guid:030000007e0500000920000000006800,button:9
button_r=engine:sdl,guid:030000007e0500000920000000006800,button:10
button_dup=engine:sdl,guid:030000007e0500000920000000006800,button:11
button_ddown=engine:sdl,guid:030000007e0500000920000000006800,button:12
button_dleft=engine:sdl,guid:030000007e0500000920000000006800,button:13
button_dright=engine:sdl,guid:030000007e0500000920000000006800,button:14
button_screenshot=engine:sdl,guid:030000007e0500000920000000006800,button:15
button_zl=engine:sdl,guid:030000007e0500000920000000006800,axis:4,threshold:0.5,invert:+
button_zr=engine:sdl,guid:030000007e0500000920000000006800,axis:5,threshold:0.5,invert:+
lstick=axis_x:0,engine:sdl,invert_x:+,guid:030000007e0500000920000000006800,axis_y:1,offset_x:-0.000000,offset_y:0.000000,invert_y:+
rstick=axis_x:2,engine:sdl,invert_x:+,guid:030000007e0500000920000000006800,axis_y:3,offset_x:-0.000000,offset_y:0.000000,invert_y:+
motionleft=engine:sdl,motion:0,guid:030000007e0500000920000000006800
motionright=engine:sdl,motion:0,guid:030000007e0500000920000000006800

----
Run game:
yuzu-cmd -f game.nsp

Good luck.
