### ISSUE TITLE
shattered graphics when using ansiotropic filtering settings other than "default"

### ISSUE THREAD

**Issue by CardboardTurtle** [yuzu-emu/yuzu#8856]
using a 6900XT with Vulkan on Arch Linux using version 1153.
I wanted to play games at 16x ansiotropic, but whenever ansiotropic filtering is set to anything other than "default", graphics have this effect.

![yuzu graphics bug](https://user-images.githubusercontent.com/43497630/188285291-b815b829-06ac-4ed2-a764-84d6ab7bea9f.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9483249/yuzu_log.txt)

**Comment by theboy181** [comment]
Does auto work? as this is the default setting, and if there are issues with auto then there is the need to make yuzu choose default instead

**Comment by MysticExile** [comment]
The ansiotropic filtering setting does not work perfectly on all games, it overrides the game's request for the level of ansiotropic filtering for each draw. So if the game depends on a specific level of ansiotropy it will break the rendering.

**Comment by CardboardTurtle** [comment]
> Does auto work? as this is the default setting, and if there are issues with auto then there is the need to make yuzu choose default instead

auto has the same issues.

**Comment by theboy181** [comment]
Excellent report, hopefully AUTO is set to default by the developers.
