### ISSUE TITLE
Pokémon Shining Pearl bug wander pkmn

### ISSUE THREAD

**Issue by NeoChaoticTTV** [yuzu-emu/yuzu#8860]
Hi sorry for my english,

I've been playing pokemon sparkling pearl for quite a while but every time I try to enter Peaceful Square in Unionpolis the game freezes and nothing responds. I then have to restart the game. Otherwise all the functionalities of the game work except the walk, which I cannot have until I enter the peaceful square.

[Capture](https://user-images.githubusercontent.com/112823170/188327585-85768f4c-eb17-4234-9ba1-c84cfb96071b.PNG)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9485250/yuzu_log.txt)

**Comment by G-Spawn** [comment]
We don't support piracy in our issue tracker either. Same as on discord and the Citra forums. Please dump your games legally or don't bother asking for help in future 🙏
