### ISSUE TITLE
[Feature Request] ZL and ZR toggle

### ISSUE THREAD

**Issue by unuruu5760** [yuzu-emu/yuzu#8862]
Right now I can toggle A,B,Y,X , L ,R ,DPAD but I can't toggle ZL ,ZR...this is true for both controller and keyboard.
I would appreciate it if you could add ZL and ZR toggle.

**Comment by german77** [comment]
Only buttons can be toggleable. ZL and ZR have this feature. Make sure you are using latest mainline 1157
![image](https://user-images.githubusercontent.com/5944268/188486416-74cd8c38-25ad-4eb9-97ed-4b62201d3a02.png)

**Comment by unuruu5760** [comment]
> Only buttons can be toggleable. ZL and ZR have this feature. Make sure you are using latest mainline 1157 ![image](https://user-images.githubusercontent.com/5944268/188486416-74cd8c38-25ad-4eb9-97ed-4b62201d3a02.png)

I mostly use EA2895, but the most recent version, EA2935, has the same problem. I have a video of testing both the controller and keyboard.

https://youtu.be/f3ffBRypZLM

**Comment by german77** [comment]
I see.  You can always open `view->debugging->controller P1` to view your inputs in real time. Seems like the toggle is set correctly on the config but not the game.

I just confirmed the issue on my side. I will push a fix soon
