### ISSUE TITLE
Splatoon 3 Buggy lagging  pls develope more for splatoon 3 story mode

### ISSUE THREAD

**Issue by TrollPassi** [yuzu-emu/yuzu#8868]
I will love to see that we can play splatoon 3 story fully smoth on yuzu I hope some of the developer team see this
Please keep in mind yuzu is EXPERIMENTAL SOFTWARE.

Please read the FAQ:
https://yuzu-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of yuzu you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

-->

**Comment by G-Spawn** [comment]
we dont support leaked games here. nor did you provide enough information to even help. wait for assistance when the game is globally  out on the 9th.
