### ISSUE TITLE
Graphics rendering issue on Mario + Rabbids Kingdom Battle

### ISSUE THREAD

**Issue by MaxALEau** [yuzu-emu/yuzu#8872]
Hello,

I report to you a small graphic bug that I had on yuzu 1161

Thanks!

https://user-images.githubusercontent.com/52678500/189476152-e6bfa268-ff53-413d-94f9-5a948326c177.mp4

**Comment by G-Spawn** [comment]
Provide a log please like the issue template asked for 🙏 https://yuzu-emu.org/help/reference/log-files/

**Comment by MaxALEau** [comment]
> Provide a log please like the issue template asked for 🙏 https://yuzu-emu.org/help/reference/log-files/

I restarted the same cutscene and here is the corresponding log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9541444/yuzu_log.txt)

**Comment by gidoly** [comment]
this can be solve with enabling pessimistic buffer flush on gpu advance setting iirc plz report back after try it

**Comment by MaxALEau** [comment]
> this can be solve with enabling pessimistic buffer flush on gpu advance setting iirc plz report back after try it

That's work!
Thanks!
