### ISSUE TITLE
[FEATURE REQUEST] Make/Use Custom Drivers for Controllers

### ISSUE THREAD

**Issue by Deadzulu** [yuzu-emu/yuzu#8885]
For this feature you can do one of two things: Use (not package w/ yuzu) Steam's Xbox controller driver which allows for up to 16 xbox controllers to be plugged in at once, To download/install the drivers a user would have to go through the following steps on steam,
Instructions (not big picture mode)
Go to settings
Go to Controller settings 
Select General controller settings
Enable Xbox Configuration support (if not already enabled)
Enable Xbox Extended Feature Support and wait for popup
Restart computer and the drivers will be installed.

OR

Make custom drivers that allow for up to 16 of Any/Multiple controller type(s) and ship them with yuzu.

**Comment by german77** [comment]
Enable this setting in advanced input. Then restart yuzu. It will allow yuzu to detect any number of controllers
![image](https://user-images.githubusercontent.com/5944268/189562652-d65ae820-f024-4581-a1e8-def64e24bd85.png)

**Comment by MysticExile** [comment]
Solution was provided above
