### ISSUE TITLE
Mario Kart 8 Deluxe fails to get to title screen using any firmware past 12.0.3

### ISSUE THREAD

**Issue by Azure-Agst** [yuzu-emu/yuzu#8886]
Hey team! Just got my Steam Deck and wanted to use your software to set up my Switch library on it. While doing so, I found a peculiar issue. Attempting to Run Mario Kart 8 Deluxe with any firmware past 12.0.3 causes the game to perpetually load on launch and fail to get to the title screen.

Here's the setup I used for testing:

- **OS:** Windows 10 Education (lol)
- **CPU:** Ryzen 7 5900x
- **GPU:** Nvidia RTX 2070
- **Yuzu:** Yuzu 1163 (2022-09-11, f0a6d73fe)

Here's the loading screen in question:

![image](https://user-images.githubusercontent.com/10553730/189561962-004fc248-5e21-432b-971c-e35fa8c58c44.png)

I have tried using plenty of firmware versions to test confirm that it was a firmware compatibility, and here are my results:

- **Works:** 10.0.4, 12.0.3
- **Fails:** 12.1.0, 13.0.0, 14.0.0, 14.1.2 Rebootless

I've attached some logs from my attempts to run the game on a working firmware version (12.0.3) and a non-working version. (12.1.0) Hopefully this helps with debugging. Let me know if you need any other info from me to help out.

[yuzu_log-1163-MK8D-12.0.3.txt](https://github.com/yuzu-emu/yuzu/files/9544103/yuzu_log-1163-MK8D-12.0.3.txt)
[yuzu_log-1163-MK8D-12.1.0.txt](https://github.com/yuzu-emu/yuzu/files/9544104/yuzu_log-1163-MK8D-12.1.0.txt)

**Comment by german77** [comment]
You have old or mismatched firmware and keys. Please dump the latest and try again

**Comment by Azure-Agst** [comment]
...You're correct. Updating Lockpick_RCM and dumping new 14.1.2R keys fixed the issue. Feeling a little dumb right now. Closing this issue.
