### ISSUE TITLE
[FEATURE REQUEST] 16 controller slots.

### ISSUE THREAD

**Issue by Deadzulu** [yuzu-emu/yuzu#8894]
Me and the boys need to have smash tourneys and half of them don't have switches, there's 17 of us, 2 can share controllers, but we don't have more than 8 controller slots on yuzu, we need minimum 16, I'm willing to wait months but we still need that tourney, we've been playing melee for our tourneys for over 4 years now and would like to switch to the switch so we can switch to ultimate, on the (emulated) switch.

**Comment by merryhime** [comment]
A physical Switch can only support up to 8 controllers.

Game software developed for the Switch will likely be working under this assumption, and it is very unlikely game developers would support more than 8 controllers.

**Comment by german77** [comment]
The switch only has enough memory for 10 players. 8 regular controllers, 1 handheld and 1 for debug. No game is capable of having 16 players.

we can add future support to map 2 controllers to the same player. But not having more players since that's a switch design limitation.
