### ISSUE TITLE
I cannot play Mario Kart 8 Deluxe on yuzu.

### ISSUE THREAD

**Issue by cookieiz** [yuzu-emu/yuzu#8895]
https://user-images.githubusercontent.com/111113097/189798251-4573eaf2-16a9-43ce-8bf4-72e1d630f1a4.mp4

Stuck here

**Comment by german77** [comment]
Your video doesn't work. This is not a support forum. If it's stuck on boot you need to update your keys and firmware. Feel free to ask on the citra forum or discord
