### ISSUE TITLE
MONSTER HUNTER GENERATIONS ULTIMATE Using mod will cause you to be unable to enter the game

### ISSUE THREAD

**Issue by xixiyii** [yuzu-emu/yuzu#8905]
The mod file is not modified in any way, the source file is used directly. Drag into the mod loading folder, open the game and display the request to exit, select no, it will always be loaded

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9565599/yuzu_log.txt)

![dump](https://user-images.githubusercontent.com/113516814/190133758-148b2276-4ed1-4d71-a434-f3611795ce5a.png)

![load](https://user-images.githubusercontent.com/113516814/190133766-2d886fc4-cfe8-4648-ada1-6fca2199769d.png)

![exit](https://user-images.githubusercontent.com/113516814/190134565-6c2d9a8f-b09e-47cb-9b05-174bdcf4cecb.png)

**Comment by MavericK99966** [comment]
Same issue, trying to run the Cope Edition romFS mod on Monster Hunter Generations Ultimate.

**Comment by MavericK99966** [comment]
Still seems to be an issue, any update on this?

**Comment by Squall-Leonhart** [comment]
The game is crashing in Guest executed code itself, rather than the emulator generating an exception. There might be some anti-tamper mechanism at play that doesn't trigger on other emulators.
