### ISSUE TITLE
Zelda BOTW doesn't work with ACO shader compiler

### ISSUE THREAD

**Issue by megumintyan** [yuzu-emu/yuzu#8907]
The game stops working after loading a savefile (immediately or after 10-20 sec) when using Vulkan.
It works good with `RADV_DEBUG=llvm`.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9568281/yuzu_log.txt)

**Comment by liamwhite** [comment]
Possible upstream issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/7257
I personally do not reproduce this issue with Mesa 21.x.

**Comment by megumintyan** [comment]
I have Mesa 22.1.7

**Comment by HurricanePootis** [comment]
Works for me with latest mesa

**Comment by megumintyan** [comment]
I've updated mesa it works now
