### ISSUE TITLE
[BUG REPORT] TAS not working as intended

### ISSUE THREAD

**Issue by OZtistic** [yuzu-emu/yuzu#8908]
According to a user report on the yuzu Discord, TAS has massive latency.
It was always the rule to select TAS Controller in the Controls dialog, however recent changes(?) may have stopped it from working as intended. It no longer exists as an option to select for end users in the Controls Dialog.
The TAS dialog is also broken (Tools --> TAS) and refuses to load the TAS help page, however right-clicking on the blue link to help and copying the web address to a browser works fine.
![TAS](https://user-images.githubusercontent.com/71381851/190352813-7fac7576-632b-4b54-a647-3a6bfb9426de.png)

Clicking the link just makes a blue outline around the entire UI dialog
paging @german77 for resolution to this issue

**Comment by german77** [comment]
TAS is not selectable. Is always active regardless of your controller config. It doesn't have a massive latency the ssbu script was waiting for the battle to end. Link is fixed on #8909
