### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by RainbowTaro2022** [yuzu-emu/yuzu#8912]
error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
-- Running vcpkg install - failed
CMake Error at externals/vcpkg/scripts/buildsystems/vcpkg.cmake:863 (message):
  vcpkg install failed.  See logs for more information:
  G:\万能彩芋创造：Clone\yuzu-latest\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  CMakeLists.txt:50 (include)

**Comment by german77** [comment]
Make sure you selected a valid compiler. If you are on windows visual 2019 or visual 2022 should work

**Comment by RainbowTaro2022** [comment]
I have chosen VS2022 as the compiler, but it is still useless
[vcpkg-manifest-install.log](https://github.com/yuzu-emu/yuzu/files/9585688/vcpkg-manifest-install.log)
[stdout-x64-windows.log](https://github.com/yuzu-emu/yuzu/files/9585693/stdout-x64-windows.log)
[config-x64-windows-out.log](https://github.com/yuzu-emu/yuzu/files/9585694/config-x64-windows-out.log)

**Comment by german77** [comment]
It might be a stupid question but do you have visual 2022 installed, with c++ and on the latest update? https://visualstudio.microsoft.com/vs/
I compiled yuzu from scratch yesterday just to verify and it compile fine.

**Comment by amilamad** [comment]
Issue still exiists on linux build as well. Tried on Ubuntu 22.04 
Workaround should be for Linux to set the evn variables before running cmake .. -G 
export CC=gcc-11
export CXX=g++-11

For windoes similar work around might needs to be done 
set CC=path to vc
set CXX=path to vc

**Comment by fengahan** [comment]
I encountered the same problem, and finally found that a certain file was created during the execution of cmake, which was removed by Windows Defender as a virus. When I tried to allow the change operation, everything went smoothly.

**Comment by fengahan** [comment]
@RainbowTaro2022 @german77  I encountered the same problem, and finally found that a certain file was created during the execution of cmake, which was removed by Windows Defender as a virus. When I tried to allow the change operation, everything went smoothly.
![Uploading 17053757632832.png…]()

**Comment by fengahan** [comment]
![17053757632832](https://github.com/yuzu-emu/yuzu/assets/21169773/b706e1d2-8e03-4370-a948-b12a8a9b7db3)
