### ISSUE TITLE
Crash on ALT+TAB after build 1158

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#8913]
Under Windows, after build 1158, when switching from VK fullscreen to another program with usual ALT+TAB yuzu feezes and crashes. Seems easy to reproduce with any 116x build... 

Win 10 x64 21H1, NVidia 512.96 SD, GTX 1070 8GB.

**Comment by Docteh** [comment]
Just regular fullscreen  or like an exclusive fullscreen option? I fired up Mario kart, went full screen, ALT+TAB over to browser to ask for clarification.  I'm on 1163 today.

**Comment by Hexaae** [comment]
Build 1167 and I can't reproduce it anymore for some reason. Better that way.
