### ISSUE TITLE
GUI error while using Ps4 Controller

### ISSUE THREAD

**Issue by guill3sm** [yuzu-emu/yuzu#8917]
- Any button pressed with dualshock 4 controller in game does something related to the emulator itself. so for example

- Press a button = amiibo window opens
- press menu button = quit yuzu confirmation window

- Same with all buttons

**Comment by german77** [comment]
Seems like you somehow have the "home" button always active. What you describe are controller hotkeys. There are 2 ways to solve this issue. You can either remove the mappings of the home button or disable controller navigation in advanced input

**Comment by guill3sm** [comment]
Fixed, sorry, thought was a bug, have a great day
