### ISSUE TITLE
Recent update of AppImage Yuzu mainline 1168 won't run on Mint 20.3 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by Wohlstand** [yuzu-emu/yuzu#8919]
Hello! 

Since recent time, I attempted to run Yuzu, and I got the next error:
```
./usr/bin/yuzu: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./usr/bin/yuzu)
./usr/bin/yuzu: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./usr/bin/yuzu)
```

The previous version worked flawlessly. 

OS: Linux Mint 20.3 (Ubuntu 20.04). I will update later, but currently, I am required to use Ubuntu 20.04-based core in order to keep building and debug software for my main work (where are Ubuntu 20.04 machines in most).

**Comment by Docteh** [comment]
Interestingly enough the AppImage is built on Ubuntu 18.04. The AppImage has some magic that I've obviously broken ;)

Hopefully I can get 20.3 ISO still?

**Comment by Wohlstand** [comment]
But which GCC version and which libc/libstdc++ version were targeted? Is that a custom installed latest GCC or used in-system old GCC?

Yes, 20.3 ISO is available here: https://www.linuxmint.com/download_all.php

**Comment by Docteh** [comment]
Next build for #8871 should work for you, should be done about 50 minutes after this comment at https://github.com/yuzu-emu/yuzu/actions/runs/3075514723 

According to this comment, 
https://github.com/yuzu-emu/yuzu/blob/3a5f9409c897f12e69cfc1d395e743b4850330ec/.ci/scripts/linux/docker.sh#L60

it has to do with using a newer GCC to compile than various distros have

**Comment by Wohlstand** [comment]
Okay, that build works!
Now I will wait for the mainline build when it gets an update...

**Comment by Docteh** [comment]
1171 is there, fingers crossed

**Comment by Wohlstand** [comment]
Downloaded, and... it works!
Thanks for the help!

**Comment by Wohlstand** [comment]
(p.s. for my needs, I made the python script that pulls the update from the latest release of yuzu-mainline and Citra canary. So, I made that to quickly get all recent updates and see new features ~~and bugs~~ quickly)
