### ISSUE TITLE
emulator crashes when i try to load Pokemon Shield

### ISSUE THREAD

**Issue by pastel-n0va** [yuzu-emu/yuzu#8926]
i dont have the firmware and im too much of an idiot to download said firmware, can anyone assist me?

**Comment by german77** [comment]
This place is not for support. Please ask on discord or citra forum

**Comment by pastel-n0va** [comment]
i actually found the firmware and keys download, thanks for not being that much of help >:3c

**Comment by G-Spawn** [comment]
We don't support piracy so we would never have bothered to help you anyways. Thank you for wasting time.
