### ISSUE TITLE
My SDL2 game won't launch on Yuzu mainline 1172 (Yuzu stops emulation with asserts in a log), on hardware works

### ISSUE THREAD

**Issue by Wohlstand** [yuzu-emu/yuzu#8931]
Hello!

Recently I found that my homebrew game won't launch on Yuzu. However, one of my buddies verified the work of this on real hardware, and it works.

In the log file, I found several stubbed calls references:
```
[  17.968993] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
...
  17.976478] Service.AM <Warning> core/hle/service/am/am.cpp:SetFocusHandlingMode:431: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[  17.976809] Service.AM <Warning> core/hle/service/am/am.cpp:SetOutOfFocusSuspendingEnabled:451: (STUBBED) called enabled=false
[  17.977219] Service.AM <Warning> core/hle/service/am/am.cpp:NotifyRunning:1652: (STUBBED) called
[  17.977854] Service.AM <Warning> core/hle/service/am/am.cpp:SetOperationModeChangedNotification:403: (STUBBED) called flag=true
[  17.977969] Service.AM <Warning> core/hle/service/am/am.cpp:SetPerformanceModeChangedNotification:413: (STUBBED) called flag=true
...
[  18.001966] Service.VI <Warning> core/hle/service/vi/vi.cpp:AdjustRefcount:112: (STUBBED) called id=1, addval=00000001, type=00000000
[  18.002206] Service.VI <Warning> core/hle/service/vi/vi.cpp:AdjustRefcount:112: (STUBBED) called id=1, addval=00000001, type=00000001
...
etc.
```

and the assertions at the final:
```
[  18.227456] Debug <Critical> ./core/hle/kernel/k_auto_object.h:operator():164: Assertion Failed!
[  18.227462] Debug <Critical> ./core/hle/kernel/k_auto_object.h:operator():164: Assertion Failed!
[  18.227471] Debug <Critical> ./core/hle/kernel/k_auto_object.h:operator():164: Assertion Failed!
[  18.227475] Debug <Critical> ./core/hle/kernel/k_auto_object.h:operator():164: Assertion Failed!
```

- Game binary: ~~[thextech.nro.zip](https://github.com/yuzu-emu/yuzu/files/9604081/thextech.nro.zip)~~ Updated version: [thextech.nro.zip](https://github.com/yuzu-emu/yuzu/files/9604511/thextech.nro.zip)

- [Source code is here](https://github.com/Wohlstand/TheXTech/tree/wip-switch-port) (Use `wip-switch-port` branch, not main)
- Log file: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9604082/yuzu_log.txt)

**Note:** This game needs resources placed on an SD card (no embedded resources and no romfs used)
- Download this archive: https://wohlsoft.ru/projects/TheXTech/_downloads/thextech-adventure-of-demo-assets-full.7z
- At the root of the SD card, create the `TheXTech` directory
- Put the content of the downloaded archive into that directory
- Game can work

**Comment by liamwhite** [comment]
The game is calling ISelfController::Exit in am. I am attempting to recompile with more debug info to get a trace.

**Comment by liamwhite** [comment]
When compiling your project with `cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug .. -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/devkitA64.cmake` I get this build error:

```
/home/liam/source/TheXTech/3rdparty/FreeImageLite/Source/3rdParty/LibPNG/arm/arm_init.c:48:4: error: #error "PNG_ARM_NEON_FILE undefined: no support for run-time ARM NEON checks"
   48 | #  error "PNG_ARM_NEON_FILE undefined: no support for run-time ARM NEON checks"
      |    ^~~~~
```

Did I need to install something else? I already have switch-libpng in pacman.

**Comment by MonsterDruide1** [comment]
@liamwhite As far as I can tell from the building README stuff, a modified version of `FreeImage` is required:
https://github.com/WohlSoft/libFreeImage
Maybe that is the issue here?

**Comment by liamwhite** [comment]
I am using that fork already (it is a submodule). Seems like there might be some uncommitted changes needed to the submodules to get this version compiling.

**Comment by Wohlstand** [comment]
> When compiling your project with `cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug .. -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/devkitA64.cmake` I get this build error:
> 
> ```
> /home/liam/source/TheXTech/3rdparty/FreeImageLite/Source/3rdParty/LibPNG/arm/arm_init.c:48:4: error: #error "PNG_ARM_NEON_FILE undefined: no support for run-time ARM NEON checks"
>    48 | #  error "PNG_ARM_NEON_FILE undefined: no support for run-time ARM NEON checks"
>       |    ^~~~~
> ```
> 
> Did I need to install something else? I already have switch-libpng in pacman.

You should switch to the `wip-switch-port` branch, the main branch is not ready. Please change the branch, pull submodules, and try to configure again. (the previous attempt you should remove)

**Comment by Wohlstand** [comment]
> I have these libraries installed, both in pacman and in my system package manager. Have you encountered this issue?

Weird... did you install devel packages for libpng and libjpeg? At me they gets recognised. Lemme to find  which packages I got installed...

**Comment by Wohlstand** [comment]
These I have:
```
~$ sudo dkp-pacman -Q
3ds-cmake 1.4.0-1
3ds-examples 20220129-1
3ds-pkg-config 0.28-5
3dslink 0.6.1-1
3dstools 1.3.0-1
citro2d 1.6.0-1
citro3d 1.7.0-1
default-arm7 0.7.4-7
deko3d 0.4.0-1
devkit-env 1.0.1-2
devkitA64 r19-2
devkitA64-gdb 11.2-1
devkitARM r58-2
devkitARM-gdb 10.2-3
devkitPPC r41-2
devkitPPC-gdb 7.6.2-1
devkita64-cmake 1.1.1-1
devkita64-rules 1.0.1-2
devkitarm-cmake 1.1.1-1
devkitarm-crtls 1.1.1-1
devkitarm-rules 1.2.1-2
devkitppc-cmake 1.1.2-1
devkitppc-rules 1.1.1-1
devkitpro-keyring 20180316-1
dkp-cmake-common-utils 1.4.1-1
dstools 1.3.0-1
dswifi 0.4.2-1
gamecube-cmake 1.0.0-2
gamecube-examples 20210525-1
gamecube-pkg-config 0.28-5
gamecube-tools 1.0.3-1
general-tools 1.2.0-2
grit 0.9.1-1
libctru 2.1.1-2
libfat-nds 1.1.5-1
libfat-ogc 1.1.5-2
libfilesystem 0.9.14-2
libnds 1.8.2-1
libnx 4.2.1-1
libogc 2.3.1-1
maxmod-nds 1.0.15-1
mmutil 1.9.1-1
nds-cmake 1.1.0-1
nds-examples 20200727-1
nds-pkg-config 0.28-4
ndstool 2.1.2-1
ogc-cmake 1.1.0-1
picasso 2.7.0-1
ppc-libogg 1.3.4-1
ppc-libvorbisidec 1.2.1-2
ppc-pkg-config 0.28-5
switch-bzip2 1.0.6-3
switch-cmake 1.4.0-1
switch-examples 20201219-1
switch-flac 1.3.2-4
switch-freetype 2.10.1-2
switch-glad 0.1.27-1
switch-glm 0.9.9.7-2
switch-libdrm_nouveau 1.0.1-2
switch-libjpeg-turbo 2.1.2-2
switch-libmodplug 0.8.9.0-2
switch-libogg 1.3.4-2
switch-libopus 1.3-2
switch-libpng 1.6.37-1
switch-libvorbisidec 1.2.1-2
switch-libwebp 1.0.2-2
switch-mesa 20.1.0-4
switch-mpg123 1.25.10-4
switch-opusfile 0.10-3
switch-pkg-config 0.28-4
switch-sdl2 2.0.14-1
switch-sdl2_gfx 1.0.4-2
switch-sdl2_image 2.0.4-1
switch-sdl2_mixer 2.0.4-2
switch-sdl2_net 2.0.1-3
switch-sdl2_ttf 2.0.15-1
switch-tools 1.12.0-1
switch-zlib 1.2.11-3
tex3ds 2.3.0-1
uam 1.1.0-1
wii-cmake 1.0.0-1
wii-examples 20210525-1
wii-pkg-config 0.28-5
wiiload 0.5.2-1
wiiu-cmake 1.2.0-1
wiiu-pkg-config 0.28-4
wiiu-sdl2 2.0.9-3
wut 1.1.1-1
wut-tools 1.3.3-1
```

**Comment by Wohlstand** [comment]
For my convenience I made the next bashrc script (and I have to run `switch-cmake` in a same way as default one):

```bash
if [[ -d /opt/devkitpro ]]; then
    export DEVKITPRO=/opt/devkitpro
    export DEVKITARM=/opt/devkitpro/devkitARM
    export DEVKITPPC=/opt/devkitpro/devkitPPC
    export DEVKITA64=/opt/devkitpro/devkitA64

    export WIILOAD=tcp:172.16.9.145

    alias wii-cmake="cmake -DCMAKE_TOOLCHAIN_FILE=$DEVKITPRO/cmake/Wii.cmake -DCMAKE_INSTALL_PREFIX=$DEVKITPRO/portlibs/wii"
    alias nds-cmake="cmake -DCMAKE_TOOLCHAIN_FILE=$DEVKITPRO/cmake/NDS.cmake -DCMAKE_INSTALL_PREFIX=$DEVKITPRO/portlibs/nds"
    alias 3ds-cmake="cmake -DCMAKE_TOOLCHAIN_FILE=$DEVKITPRO/cmake/3DS.cmake -DCMAKE_INSTALL_PREFIX=$DEVKITPRO/portlibs/3ds"
    alias switch-cmake="cmake -DCMAKE_TOOLCHAIN_FILE=$DEVKITPRO/cmake/Switch.cmake -DCMAKE_INSTALL_PREFIX=$DEVKITPRO/portlibs/switch"
fi
```

**Comment by liamwhite** [comment]
If this is for the system version of these libraries, I have libpng-devel and libjpeg-turbo-devel installed through my system package manager. CMake cannot find them, because it is looking in the wrong place:
```
  find_library considered the following locations:

    /opt/devkitpro/devkitA64/lib/(lib)png(\.so|\.a)
    /opt/devkitpro/devkitA64/(lib)png(\.so|\.a)
    /opt/devkitpro/devkitA64/aarch64-none-elf/lib/(lib)png(\.so|\.a)
    /opt/devkitpro/devkitA64/aarch64-none-elf/(lib)png(\.so|\.a)
    /opt/devkitpro/tools/lib/(lib)png(\.so|\.a)
    /opt/devkitpro/tools/(lib)png(\.so|\.a)

  The item was not found.
```
It is in /usr/lib64/libpng.so.

**Comment by Wohlstand** [comment]
> It is in /usr/lib64/libpng.so.

That's the libPNG of OS itself, you need to have libPNG installed at your devkitA64 environment, compiled for Switch especially. If you want to build the game for Switch, you need to use `dkp-pacman` and install libraries into DevkitPro's environment.

If you try to build the game using default arguments and system-wide CMake, then it will be built for local system and will use libraries installed at the actual system.

**Comment by Wohlstand** [comment]
Anyway, at Switch, actual libpng / libjpeg / etc. appear at:
```
/opt/devkitpro/portlibs/switch/lib
```

**Comment by liamwhite** [comment]
Compiled with `-DCMAKE_PREFIX_PATH=/opt/devkitpro/portlibs/switch`. Looking into the issue now.

**Comment by liamwhite** [comment]
One of the libraries you use, TCLAP, expects argv to always contain elements, but yuzu doesn't load the arguments array when launching programs -- in other words, it doesn't treat them differently from games. This patch to your code allows it to boot normally for your testing.
```diff
--- a/lib/tclap/CmdLine.h
+++ b/lib/tclap/CmdLine.h
@@ -440,15 +440,12 @@ inline void CmdLine::parse(std::vector<std::string> &args) {
     try {
         if (args.empty()) {
             // https://sourceforge.net/p/tclap/bugs/30/
-            throw CmdLineParseException(
-                "The args vector must not be empty, "
-                "the first entry should contain the "
-                "program's name.");
-        }
-
-        // TODO(macbishop): Maybe store the full name somewhere?
-        _progName = basename(args.front());
-        args.erase(args.begin());
+           _progName = "program";
+        } else {
+            // TODO(macbishop): Maybe store the full name somewhere?
+            _progName = basename(args.front());
+            args.erase(args.begin());
+       }
 
         int requiredCount = 0;
         std::list<ArgGroup *> missingArgGroups;
```
I will fix this issue on our side for consistency with [nx-hbloader behavior](https://github.com/switchbrew/nx-hbloader/blob/master/source/main.c#L311).

**Comment by Wohlstand** [comment]
Very interesting... Gonna test out some... Gonna try this and verify the work...

**Comment by Wohlstand** [comment]
It now works!
Now, there is only one thing left - sound stream in some cases may get dropped and turned into full silence.

**Comment by Wohlstand** [comment]
As the problem is solved, I'll close this. So, regarding the discussion, there are two of cases:
- Yuzu doesn't sends any argc/argv, causing it to be empty.
- An error at my program side, that doesn't expects this case.
Anyway, as my friend @ds-sloth noted, the same mess happen on Wii too.
