### ISSUE TITLE
[Local Multiplayer] Groove Coaster Wai Wai Party - Crashes when your Start Local Multiplayer Match

### ISSUE THREAD

**Issue by UiharuKazari2008** [yuzu-emu/yuzu#8936]
Create Multiplayer Room
Me and a friend connect directly
Select Local Multiplayer
Create new Room
Once the other people was there I click Start Game
Game Freezes and Crashes

Other that the games runs perfectly fine just wireless multiplayer does not start a match

yuzu Version: yuzu 1173
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
GPD Win 3 Docked on Ethernet

IP Address of the other player has been partial censored for obvious reasons 

**Log redacted due to pirated content**

**Comment by G-Spawn** [comment]
We can't support users who pirate here. Please dump everything from your console without exception.
