### ISSUE TITLE
Games not booting in SingleCore (stuck at `Launching...`)

### ISSUE THREAD

**Issue by MonsterDruide1** [yuzu-emu/yuzu#8937]
**Version/Commit hash**:
8d4458ef24e473e57b9931d7a9d1442b51fb0b1a / `yuzu 1175`

**Game**:
Happens in a few games, for example `Super Mario Odyssey`

**Details**:
When disabling `Multicore CPU Emulation` in `Emulation -> Configure`, some games cannot boot anymore and just get stuck in the `Launching...` screen. Super Mario Odyssey is affected by this behaviour, but apparently there are exceptions (`Q.U.B.E. 2` works just fine)

**Log File**:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9616990/yuzu_log_.txt)

**Comment by liamwhite** [comment]
ea9ff71725113b8dbb159917c57aa536bba0cb53 is the first bad commit
commit ea9ff71725113b8dbb159917c57aa536bba0cb53
Author: @Kelebek1
Date:   Mon Aug 1 02:58:13 2022 +0100

    Rework audio output, connecting AudioOut into coretiming to fix desync during heavy loads.

**Comment by Kelebek1** [comment]
I don't know why you'd ever want to play anything in single core...

**Comment by MonsterDruide1** [comment]
@Kelebek1 If you really want a response to that question:
I'm doing some tests with implementing something like framedump, however it only works by slowing down the GPU thread to about half speed, while everything else works at normal speed, most notably the audio thread. This means that I end up with 30 seconds of audio, while only 15 seconds of video are there. I'm hoping that disabling multicore would lock the threads together and only produce audio at the same rate as video.
