### ISSUE TITLE
Taiko no Tatsujin: Rhythm Festival [01002460135A4000] fails to launch

### ISSUE THREAD

**Issue by Scandiaca** [yuzu-emu/yuzu#8949]
Yuzu EA 2970
Game version : 1.1.1

Windows 10 21H2
11th Gen Intel(R) Core(TM) i5-1135g7 @ 2.40GHz
Intel(R) Iris(R) Xe Graphics 80EU
Driver 31.0.101.3616
RAM 8GB

Log :
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9638117/yuzu_log.txt)

**Comment by G-Spawn** [comment]
You'd always want to stick to vulkan on intel IGPU. Opengl will be terrible.

**Comment by Switch0r** [comment]
The demo works fine on Yuzu but the full game does not start.

**Comment by BrodyGaming420** [comment]
same issue over here, full game crashes but the demo works just fine

**Comment by BrodyGaming420** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9649775/yuzu_log.txt)
here is a log of yuzu trying to open the base game on the latest mainline build

**Comment by Blackbird88** [comment]
Seems to be due to #4509

**Comment by tarunio** [comment]
Anyway to fix this?

**Comment by BrodyGaming420** [comment]
> 

no, the devs needs to implement cache saving in order to fix this issue, wich they ignored ever since 2019

**Comment by Squall-Leonhart** [comment]
Can this be closed now?

**Comment by Morph1984** [comment]
This is not properly implemented, so it cannot be closed until it is

**Comment by FearlessTobi** [comment]
Boots fine now.
