### ISSUE TITLE
Popsong Party 1.1 Unknown / unimplemented function 'GetHostByNameRequestWithOptions': port='sfdnsres'

### ISSUE THREAD

**Issue by Switch0r** [yuzu-emu/yuzu#8950]
The game will not start because of online check.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9638245/yuzu_log.txt)

[ 125.772926] Service.NIFM <Warning> core\hle\service\nifm\nifm.cpp:GetCurrentNetworkProfile:301: (STUBBED) called
[ 125.776386] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:56: (STUBBED) called
[ 125.776424] Debug <Critical> core\hle\service\service.cpp:operator ():160: Assertion Failed!
Unknown / unimplemented function 'GetHostByNameRequestWithOptions': port='sfdnsres' cmd_buf={[0]=0x1220006, [1]=0x80000C0D, [2]=0x1, [3]=0x0, [4]=0x4F434653, [5]=0x121040, [6]=0x263B6C0, [7]=0x3C1041, [8]=0xCC9C10B0}
[ 131.317382] Debug <Critical> core/hle/kernel/k_auto_object.h:operator ():164: Assertion Failed!

**Comment by gidoly** [comment]
we do not plans to add online supoort. it will likely put project in to risk if we does.

**Comment by german77** [comment]
This is a valid issue. It shouldn't be closed

**Comment by benderscruffy** [comment]
just add to #3015

**Comment by benderscruffy** [comment]
can be closed
issue is at #3015
