### ISSUE TITLE
OneShot: World Machine Edition fails to boot

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#8951]
Tested build version hash: 1b1b99f (Mainline and Early Access builds - 1177 and 2970 respectively exhibit the same result)

System specs: Intel Core i5-10300H, Nvidia GTX 1660 Ti (driver 517.00), 16 GB RAM, Windows 11 Dev Preview build 25201.

As of the time of writing this report, the newly released title "OneShot: World Machine Edition" completely fails to boot further than the "Launching..." screen. Furthermore, the log reveals that the game gets stuck around initializing the `nvdrv` system service. No unimplemented service functions, error or critical messages were logged.

Reproduction rate: 5/5, no amount of emulator setting modifications change the outcome and last logged message.

The following settings were attempted with no avail: OpenGL mode, CPU accuracy to Accurate / Paranoid, single core mode.

A debug filter applied log will be attached below, some personal / sensitive information was omitted.

[**OneShot: WME logs**](https://github.com/yuzu-emu/yuzu/files/9638982/WMElog_Debug.txt)

**Comment by benderscruffy** [comment]
using the latest EA and mainline
it is still an issue
