### ISSUE TITLE
cadence of hyrule crash to desktop

### ISSUE THREAD

**Issue by triadne** [yuzu-emu/yuzu#8953]
I don't understand how these things fully work, but I was just playing the game and it crashed completely. 
I don't know how to provide all the info you need, I found a log file but it doesn't appear to show any reference to a crash. 
I have a ryzen 7, a rtx 2080, and windows 10.

**Comment by german77** [comment]
Log contains your current config. It's always worth it to post it. I completed cadence on yuzu so it should be fully playable

**Comment by triadne** [comment]
i just put it on again and it didn't crash in same place so no idea what happened. 
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9639863/yuzu_log.txt.old.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9639864/yuzu_log.txt)

**Comment by german77** [comment]
No support is provided for piracy
