### ISSUE TITLE
cadence of hyrule crash to desktop

### ISSUE THREAD

**Issue by triadne** [yuzu-emu/yuzu#8954]
I don't understand how these things fully work, but I was just playing the game and it crashed completely.
I don't know how to provide all the info you need, I found a log file but it doesn't appear to show any reference to a crash.
I have a ryzen 7, a rtx 2080, and windows 10.

P.s. don't judge me just because I don't have the hardware or know how to backup my own games, so I got some help with it, don't be such snobs and just take the error report as it is. TO HELP YOU FIX YOUR SOFTWARE.

**Comment by G-Spawn** [comment]
We do not support piracy here. You'll always be expected to dump the things you want to emulate from your console. You're not helping us at all by trying to ask for help with stolen material.
