### ISSUE TITLE
[Regression] Cruis'n Blast: Permanent vibration

### ISSUE THREAD

**Issue by legend800** [yuzu-emu/yuzu#8994]
This exact issue has returned on new EA builds as of 9/25: https://github.com/yuzu-emu/yuzu/issues/7592

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9643273/yuzu_log.txt)

**Comment by hjkcai** [comment]
+1 I had the same issue playing Super Mario Party using yuzu mainline 1181 (2022-09-26)

**Comment by yayitazale** [comment]
Same issue here playing Super Mario Party under YUZU 12.04 on Linux. 

Enable Accurate Vibration checkbox doesn't make any difference. Lowering virbation % neither. While playing, the vibration starts when a vibration occurs and stops when another vibration happens on the game.

**Comment by german77** [comment]
This should be fixed on latest mainline. What is yuzu 12.04?

**Comment by legend800** [comment]
Confirmed. All fixed! Thanks!
