### ISSUE TITLE
Yuzu emulator not responding on Windows 11 22H2

### ISSUE THREAD

**Issue by ajayfaul** [yuzu-emu/yuzu#8998]
I think this is bug and error that need to be fixed, because since i upgraded my Windows 11 to Windows 11 22H2 from Windows 11 21H2. My Yuzu emulator is always not responding when starting games.

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/reference/log-files/ provide a log when you can and try to right click games that have issue and use the remove pipeline cache button.

**Comment by ajayfaul** [comment]
> https://yuzu-emu.org/help/reference/log-files/ provide a log when you can and try to right click games that have issue and use the remove pipeline cache button.

I finally solve this issue. 

The problem is on Windows. i found that after upgrading to Windows 11 22H2. Windows is installing another VGA driver, so yuzu-emu can't recognize what vga is installed. and I solved it by reinstalling the vga driver.

**Comment by Wakku45** [comment]
Nice emulator
