### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by fancymelonub** [yuzu-emu/yuzu#9]
Everyime I try running the homebrew things that work with yuzu, I get a "Assertion Failed" error before the homebrew app loads and yuzu also crashes. Anyone know a way to fix it?

version: master-feae1c4c
seems it comes from the unicorn dll

**Comment by bunnei** [comment]
This is not the right place for these types of questions! Please as on Discord (https://discord.gg/XQV6dn9) if you'd like help building.
