### ISSUE TITLE
Triangle Strategy - Crash occurs after going out room in rpg scene 

### ISSUE THREAD

**Issue by garyliu0816** [yuzu-emu/yuzu#9007]
i7-8750H + 1060 + 16G 2667MHZ
yuzu early access 2979
the last log before crash is :
[ 424.753021] Render.Vulkan <Critical> video_core\vulkan_common\vulkan_device.cpp:ReportLoss:811: Device loss occurred!
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9690313/yuzu_log.txt.old.txt)
I guess it's about yuzu use old vulkan api that newer nvidia driver not support?

**Comment by garyliu0816** [comment]
Nvidia driver version is 472.12

**Comment by german77** [comment]
Piracy is not allowed
