### ISSUE TITLE
Bug Atelier Ryza with opengl e vulkan

### ISSUE THREAD

**Issue by rgbarros120** [yuzu-emu/yuzu#9017]
The game atelier ryza has a bug in the text boxes and also in the characters' speech. Both the ogengl and vulkan api have the same bug.

**Comment by Titaniumtown** [comment]
Did you just choose to ignore the issue format?
> - You have read the above.
> - You have provided the version (commit hash) of yuzu you are using.
> - You have provided sufficient detail for the issue to be reproduced.
> - You have provided system specs (if relevant).
> - Please also provide:
>  - For any issues, a log file
>  - For crashes, a backtrace.
>  - For graphical issues, comparison screenshots with real hardware.
>  - For emulation inaccuracies, a test-case (if able).

**Comment by gidoly** [comment]
close as non of relevent detail posted to track issue, and i believe there is already same issue foir this.
