### ISSUE TITLE
LEGO Games - graphical issues 

### ISSUE THREAD

**Issue by ChouGary** [yuzu-emu/yuzu#9029]
LEGO Games in mutiplayer mode player1 has graphical issues 

**LEGO MARVEL HERO2**
![未命名](https://user-images.githubusercontent.com/8294943/194605151-7087102d-a4df-4444-adab-ba103ba076fd.png)
![未命名2](https://user-images.githubusercontent.com/8294943/194611125-75be648d-5b26-40cc-a414-012593e2a771.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9735713/yuzu_log.txt)

**LEGO Movie2**
![未命名](https://user-images.githubusercontent.com/8294943/194605397-70885ed6-6e26-47be-83bb-a2f44576e22f.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9735718/yuzu_log.txt)

**LEGO the incredibles**
![未命名](https://user-images.githubusercontent.com/8294943/194605483-0fa6b0da-4a80-4e12-b384-30e55ef6fa66.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9735734/yuzu_log.txt)

Specs:
yuzu Version: yuzu 1191
MSVC Compiler: 1933 Runtime: 14.30.30704.0
Host CPU: i7-8750H CPU @ 2.20GHz
Host OS: Windows 10 Version 21H2 (Build 19044.2006)
Host RAM: 31.86 GiB
Driver: NVIDIA 517.48.0.0
Device: Device: NVIDIA GeForce GTX 1060
Vulkan: 1.3.205 (also occurs with OGL)

**Comment by german77** [comment]
Oh bluzu is back.

**Comment by varpness** [comment]
> LEGO Games in mutiplayer mode player1 has graphical issues
> 
> **LEGO MARVEL HERO2** ![未命名](https://user-images.githubusercontent.com/8294943/194605151-7087102d-a4df-4444-adab-ba103ba076fd.png) ![未命名2](https://user-images.githubusercontent.com/8294943/194611125-75be648d-5b26-40cc-a414-012593e2a771.png)
> 
> [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9735713/yuzu_log.txt)
> 
> **LEGO Movie2** ![未命名](https://user-images.githubusercontent.com/8294943/194605397-70885ed6-6e26-47be-83bb-a2f44576e22f.png)
> 
> [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9735718/yuzu_log.txt)
> 
> **LEGO the incredibles** ![未命名](https://user-images.githubusercontent.com/8294943/194605483-0fa6b0da-4a80-4e12-b384-30e55ef6fa66.png) [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9735734/yuzu_log.txt)
> 
> Specs: yuzu Version: yuzu 1191 MSVC Compiler: 1933 Runtime: 14.30.30704.0 Host CPU: i7-8750H CPU @ 2.20GHz Host OS: Windows 10 Version 21H2 (Build 19044.2006) Host RAM: 31.86 GiB Driver: NVIDIA 517.48.0.0 Device: Device: NVIDIA GeForce GTX 1060 Vulkan: 1.3.205 (also occurs with OGL)

Were you able to get this figured out with a workaround?

**Comment by ChouGary** [comment]
after update NVIDIA Driver 527.37 issue is fix
