### ISSUE TITLE
even if TEMPEST: no graphics

### ISSUE THREAD

**Issue by Ileca** [yuzu-emu/yuzu#9031]
I tried playing Even if TEMPEST and while the game appears to be working well, it doesn't display any graphics (except the ones for the GUI). It's a visual novel so there is no 3D involved, just static 2D artworks. Here is an example:

![Screenshot from 2022-10-08 02-12-52](https://user-images.githubusercontent.com/17970230/194677509-17505285-6111-4cc6-9980-259167482b14.png)
![Screenshot from 2022-10-08 02-13-36](https://user-images.githubusercontent.com/17970230/194677510-24635e29-53c8-4db4-a855-dfde33d633cd.png)

What it should look like, you can find screenshots at the bottom of this page > https://vndb.org/v32555

Log file in this pastebin > https://pastebin.com/LXWS8vnb.
I am on Ubuntu if that matters but I am not the only one to get this issue as you can see here (and I had the same issue on W10 anyway and the Ryujinx fix talked in the thread didn't work for me)  > https://old.reddit.com/r/NewYuzuPiracy/comments/v8zdhc/black_screen_when_playing_even_if_tempest/

**Comment by Titaniumtown** [comment]
pirate lol

**Comment by G-Spawn** [comment]
Yeah we won't support pirates here ever.
