### ISSUE TITLE
Crash Team Racing Nitro-Fueled - Audio issues

### ISSUE THREAD

**Issue by AndrewBasaraba** [yuzu-emu/yuzu#9035]
- Yuzu version 1191
- Game on default patch(1.0.0) works fine, but after updating to 1.0.15, game have terrible sound cracking and stuttering issues, game itself plays smoothly, disabling patch and going back to 1.0.0 give stable ingame sound. Is there some possibility to fix this issue?
- SteamDeck, SteamOS 3.3.2

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/reference/log-files/

**Comment by G-Spawn** [comment]
Please provide a log when you can

**Comment by AndrewBasaraba** [comment]
@G-Spawn So i tried to run game 5 times, 3 times sound was terrible, 1 time sound was kinda ok, but still cracking, and 1 time sound was ok(was watching intro video for 30 seconds), here 3 log files for 2 bad and 1 ok case.
[yuzu_log_bad_2.txt](https://github.com/yuzu-emu/yuzu/files/9738864/yuzu_log_bad_2.txt)
[yuzu_log_bad.txt](https://github.com/yuzu-emu/yuzu/files/9738865/yuzu_log_bad.txt)
[yuzu_log_good.txt](https://github.com/yuzu-emu/yuzu/files/9738866/yuzu_log_good.txt)

**Comment by Kelebek1** [comment]
Try using SDL, does that help?

**Comment by AndrewBasaraba** [comment]
@Kelebek1 Can you please specify where i can try that option?

**Comment by OZtistic** [comment]
> @Kelebek1 Can you please specify where i can try that option?

@AndrewBasaraba it's in Emulation --> Configure --> Audio 
Change it from Auto to SDL.

**Comment by AndrewBasaraba** [comment]
@OZtistic Thx for advice, didn’t notice that one. Changing sound engine to sdl2 solved cracking issue.
