### ISSUE TITLE
Xenoblade Chronicles 3 crashes during the first loading screen after EA 2979 and Mainline 1189

### ISSUE THREAD

**Issue by xSchroe** [yuzu-emu/yuzu#9038]
Build: Yuzu EA 2979 - 3007
Game version : 1.1.1
CPU : AMD Ryzen 5 5600X 6-Core Processor
GPU : Rx 5700
API: Vulkan
VRAM : 8GB
RAM : 32GB
OS : Windows 11 Version 22H2 (Build 22621.608)
Driver : 22.10.1

after the EA 2979 and Mainline 1189  the game crashes during the first loading screen.

Logs:

[yuzu_log xc3 2979.txt](https://github.com/yuzu-emu/yuzu/files/9740080/yuzu_log.xc3.2979.txt)

[yuzu_log xc3 3007.txt](https://github.com/yuzu-emu/yuzu/files/9740082/yuzu_log.xc3.3007.txt)

**Comment by kemiz4** [comment]
Regression of #9005. Also happens on polaris/Zen1.

**Comment by liamwhite** [comment]
PR 9005 was not included in EA 2979.

EA 2979 was forked from d9e375ac and included the following PRs:

- 6598
- 8876
- 8992
- 8987
- 8955
- 8874
- 8467
- 4042

**Comment by liamwhite** [comment]
This doesn't seem to be a regression introduced by any recent PR. I am seeing crashes all the way back to EA 2901; no version of yuzu, EA or mainline is able to successfully boot this game for me on AMD Windows. (Linux performance is completely unaffected.)

**Comment by kemiz4** [comment]
I compiled master yesterday to test it out. Reverting 9005 allowed me to enter the game again. 
Mainline 1188 was the last one that worked, updated to 1191 and started getting crashes 100% of the time.

**Comment by liamwhite** [comment]
@kemiz4 mainline 1188 does not work for me with Xenoblade 3 on AMD Windows.

**Comment by kemiz4** [comment]
Mainline 1188
![1188](https://user-images.githubusercontent.com/34376685/194739902-e68bd41b-c7b2-4030-89cb-4bbbe165e97e.PNG)
And here's the 1189
![1189](https://user-images.githubusercontent.com/34376685/194739906-c904db90-5d67-4c1e-8af2-6e1a71b655f9.PNG)

W10 21H2 22.9.1 Driver, didn't see any relevant changes between this and 22.10.1
Will update later and try both mainline versions, and master without PR later. 

@xSchroe could you also check mainline 1188 and 1189?

**Comment by xSchroe** [comment]
@kemiz4  sure

**Comment by xSchroe** [comment]
The 1189 mainline crashed the game, the 1188 did not. 
[yuzu log xc3 1188.txt](https://github.com/yuzu-emu/yuzu/files/9742127/yuzu.log.xc3.1188.txt)
[yuzu log xc3 1189.txt](https://github.com/yuzu-emu/yuzu/files/9742129/yuzu.log.xc3.1189.txt)

**Comment by goldenx86** [comment]
1188 doesn't work for me, I'm suspefcting the 22H2 for Windows 11.

**Comment by liamwhite** [comment]
Looks like this was a driver bug that was hidden by another bug in macro JIT. By enabling the macro interpreter on any version you will experience this crash. I reproduced a crash using amdvlk on Linux as well. We are looking at reporting this to the driver team.

**Comment by xSchroe** [comment]
Any news about this issue?

**Comment by liamwhite** [comment]
The bug has been reported to AMD but they have not done anything with it so far.

**Comment by linh1987** [comment]
I might want to mention that Steam Deck user (or Windows user, specifically) is very unlikely to receive a new driver even when a new one is available from AMD (due to the way Valve is releasing its drivers to their Windows userbase). Is there a way for us to band-aid this issue ourselves?

**Comment by liamwhite** [comment]
This issue should not occur on the Steam Deck's default operating system because it uses the "radv" driver in Mesa, which does not experience this issue.

**Comment by linh1987** [comment]
yes, the issue is affecting Steam Deck Windows users specifically as the provided driver is very outdated.

**Comment by xSchroe** [comment]
it works now with Early Access 3123
