### ISSUE TITLE
strange graphic glitch in zelda botw

### ISSUE THREAD

**Issue by vaztin13** [yuzu-emu/yuzu#9046]
Hi! i have a visual glitch in botw, there's a straight line in which from there the shadows look strange, this does not happen for example when there are no shadows (when a cloud passes), hope you see it in the images below.

![image](https://user-images.githubusercontent.com/107971732/194818794-7c6e44eb-bd54-4cfb-a422-9d5f3e858458.png)

![image](https://user-images.githubusercontent.com/107971732/194818855-52f1eb2a-9994-4825-a961-4a6744307439.png)

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/reference/log-files/ provide a log please.

**Comment by vaztin13** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9744225/yuzu_log.txt)

**Comment by G-Spawn** [comment]
ah well we cannot provide support to pirates here. Please dump everything from your console if you want help.
