### ISSUE TITLE
YFC Part 1 introduces model flickering in AC:NH

### ISSUE THREAD

**Issue by pixelqiwi** [yuzu-emu/yuzu#9050]
Version: Yuzu Mainline 1191-1194 (as of now)
Game version: 2.0.5
CPU: AMD Ryzen 5 3600
GPU: GTX 1060
API: Vulkan
VRAM: 5GB
RAM: 16GB
OS: Windows 10 Version 21H2 (19044.2006)
Driver: Game Ready Driver 512.15

Versions of Yuzu starting from 1191 have made the objects in the game flicker. This issue was already on Yuzu EA, but now it is also on Mainline.

The objects flicker on any screens, that display a model over UI, like in Able sisters, Nook Shopping, DIY crafting, and any similar inventories.

On Mainline 1190 there was no such issue and the rendering was fine.
Other people in our community have also reported having these flicker issues on these versions of Yuzu, and no problems with rendering on 1190.

Here's an example of the issue itself.
https://user-images.githubusercontent.com/13924553/195006891-004021ff-4749-4ea8-8b44-3bbe5c28e83b.mp4

Here's a log, where I launch the game in Mainline 1194, browse flickering Nook Shopping for a minute, and turn off the game.
[yuzu_log.txt acnh 1194](https://github.com/yuzu-emu/yuzu/files/9751537/yuzu_log.txt)

And here's a different log, where I launch the game in Mainline 1190, browse perfectly fine Nook Shopping for a bit, and also turn off the game.
[yuzu_log.txt acnh 1190](https://github.com/yuzu-emu/yuzu/files/9751554/yuzu_log.txt)

I dearly hope this gets fixed, as it was not an issue in the past, but for now our only solution for enjoyable gameplay is to not update past 1190.

**Comment by SuperZoops** [comment]
Also present on the EA-3013 build under Linux.

Game version: 2.0.5
CPU: AMD Ryzen 7 1700
GPU: GTX 1060 as well
API: Vulkan
VRAM: 3GB
RAM: 16GB
OS: Arch Linux, kernel 5.19.13-zen
Driver: Nvidia 515.49.19 - vulkan dev branch

**Comment by MysticExile** [comment]
@FernandoS27 Likely a regression from YFC Part 1

**Comment by Elfykins** [comment]
Getting the same issue on 1195.

Version: Yuzu Mainline 1195
Game version: 2.0.5
CPU: 12th Gen Intel(R) Core(TM) i7-12700K 
GPU: GeForce RTX 3080ti
API: Vulkan
VRAM: 12GB
RAM: 32GB
OS: Windows 10 Pro V 21H2 (Build 19044.2006)
Driver: Game Ready Driver 517.48

**Comment by MysticExile** [comment]
I have confirmed with a dev that this is indeed a regression from the YFC Part 1 #8467 PR. The dev is aware and will tackle the issue asap.

**Comment by MikeOwaR** [comment]
Any update on this issue?

**Comment by gidoly** [comment]
Fixed by #9095 merge
