### ISSUE TITLE
Pokemon Sword

### ISSUE THREAD

**Issue by killerdevildog11** [yuzu-emu/yuzu#9052]
Please keep in mind yuzu is EXPERIMENTAL SOFTWARE.

Please read the FAQ:
https://yuzu-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

When submitting an issue, please check the following:

- You have read the above.
- READ
- You have provided the version (commit hash) of yuzu you are using.
- Version is yuzu-mainline-20221001-25192917a.AppImage
- You have provided sufficient detail for the issue to be reproduced.
- load pokemon sword and save then close music still plays
- You have provided system specs (if relevant).
- Product Name: GE76 Raider 11UE
- OS: Linux Ubuntu 22.04
- CPU 11th Gen Intel i7-11800H 
- GRAPHICS are:
- 00:02.0 VGA compatible controller: Intel Corporation TigerLake-H GT1 [UHD Graphics] (rev 01)
01:00.0 VGA compatible controller: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)
- 64013MiB of RAM
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

no logs availiable

**Comment by OZtistic** [comment]
@killerdevildog11 Please follow the guidelines and edit the title of the issue to be more descriptive
