### ISSUE TITLE
Yo-kai Watch 1 visual bugs

### ISSUE THREAD

**Issue by CraftyArmy** [yuzu-emu/yuzu#9053]
Yuzu Version: 1193
Windows 11
CPU: Intel i7-12700K 3.60GHz
GPU: Nvidia GeForce RTX 3060 Ti 8GB
Ram 16GB DDR4
1. The screen is blurred on vulcan - this happens soon as you start the game
![yo-kai watch 1 bugs 1](https://user-images.githubusercontent.com/46542969/195180738-afdf0f42-85d6-4a62-b24c-2abf65980bbc.jpg)

2. when you encounter any 3d model there is no model at all - at the start the game you can encounter a insect that will have no model I have checked and there is no model with yo-kai aswell

3. when you catch a yo-kai or any bug/fish there is alot of broken ui - thats when you catch any yo-kai or bugs with the lens or befriend them 
![broekn ui](https://user-images.githubusercontent.com/46542969/195180766-e0746e9e-0a8d-4b4f-b2d8-c805ca00ffd6.jpg)

**Comment by MysticExile** [comment]
Thanks for your submission, could you also provide a log?

**Comment by MysticExile** [comment]
Here are more examples and additional logs provided by @AstroQuote

[OpenGL Log](https://github.com/yuzu-emu/yuzu/files/9759282/yuzu_log.txt)
[Vulkan Log](https://github.com/yuzu-emu/yuzu/files/9759283/yuzu_log.1.txt)
![131241318-378ca79d-2735-43d3-a51b-b7f171fb4b49](https://user-images.githubusercontent.com/30736337/195184622-e4eb79dd-ddea-4c7e-8b1b-4660dedcaa3f.png)

**Comment by CraftyArmy** [comment]
@MysticExile 
Here is the log for yuzu
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9759418/yuzu_log.txt)

**Comment by CraftyArmy** [comment]
@MysticExile quick question this is on the list of things that will get fixed in a future update right?

**Comment by G-Spawn** [comment]
Closing issue in favour of other one with proper valid logs.
