### ISSUE TITLE
joycon IMU doesn't work on linux

### ISSUE THREAD

**Issue by yshui** [yuzu-emu/yuzu#9057]
There are some complications with using joycon on linux:

1. The joycon IMU is listed as a separate device.
2. The IMU device is not listed when the `SDL_HINT_ACCELEROMETER_AS_JOYSTICK` hint is set

So first we should remove the hint, then we need to combine the IMU with the main joystick device.

**Comment by german77** [comment]
We disable that hint already https://github.com/yuzu-emu/yuzu/blob/master/src/input_common/drivers/sdl_driver.cpp#L412

We also use the hidapi driver to interact with joycons. Make sure to have the right driver and rule for them to work properly
![image](https://user-images.githubusercontent.com/5944268/195216675-574a84fd-00df-4ba7-a60d-26cabaf314f2.png)

**Comment by german77** [comment]
The custom joycon driver + the hidraw rule should fix this issue.
