### ISSUE TITLE
Kirby and the Forgotten Land black boxes

### ISSUE THREAD

**Issue by piplup55** [yuzu-emu/yuzu#9059]
Kirby has a black box under him in some version and in him in other versions

**Tested Versions:**
[Yuzu 1190 (before YFC)](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1190)
[Yuzu 1196 (after YFC)](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1196)
Yuzu Early Access 3014

**Tested Kernels:**
Linux-zen 5.19.13
Linux 5.19.13

**Yuzu 1190/1196**:
OpenGL: 
![image](https://user-images.githubusercontent.com/100526773/195430517-89806b75-c794-4b5d-8bb2-e513d9db4795.png)
Vulkan: 
![image](https://user-images.githubusercontent.com/100526773/195430866-d9c9ab52-93bc-4c81-9854-2e5f3b61aa7f.png)

**Early Access 3014**: 
OpenGL:
![image](https://user-images.githubusercontent.com/100526773/195430310-49ba171c-6953-4e72-be40-f204a843bdc8.png)
Vulkan: 
![image](https://user-images.githubusercontent.com/100526773/195430403-70ccd700-8dd6-4433-89ff-0fe6925b681a.png)

**System Specs:**
Linux:
 - OS: Arch Linux
 - CPU: AMD Ryzen 7 3700X
 - GPU: RX6600 XT
 - Memory: 64GB, Swap: N/A
 - GPU Driver: Mesa 22.1.7, radv 22.1.7

**Comment by z0z0z** [comment]
I can confirm this happens on OpenGL / 5500XT / mesa-git / yuzu-git / Arch btw
