### ISSUE TITLE
Softlocks all the time pokémon sword yuzu

### ISSUE THREAD

**Issue by rgbarros120** [yuzu-emu/yuzu#9060]
Pokemon sword and shield is impossible to play on yuzu. It's giving softlocks all the time reaching 0fps and making the emulator crash.

I saw a bunch of people complaining about the same problem. You have to review what is causing this.

My Specs: RYZEN 5 1600; GTX 1650 OC 4GB; 16GB DE RAM (2400MHZ)
DRIVER: 517.48

**Comment by liberodark** [comment]
Duplication > https://github.com/yuzu-emu/yuzu/issues/9002

**Comment by gidoly** [comment]
close due to duplicated
