### ISSUE TITLE
[Mod Request] Memory allocation for BOTW

### ISSUE THREAD

**Issue by SilentStorm-1986** [yuzu-emu/yuzu#9062]
I've been working on textures for BOTW and running into some memory glitches. Large textures cause panic moons to spawn, scaling them down a bit eliminates this issue, but some still remain such as textures disappearing and not rendering properly.

I'm curious if there any devs who would be interested in making a mod that maps the texture memory into the extra 2GB provided by the emulator. Something similar to extended memory for cemu, except as much as possible allocated to the resource heap.

**Comment by liamwhite** [comment]
This isn't an issue with yuzu. I would suggest looking at how game uses the GPU driver to allocate memory in this case if you wanted a place to get started.

**Comment by SilentStorm-1986** [comment]
I figured that because the mod repository is within the Yuzu repo that it
would be alright to request mods. I would work on this myself, however my
disassembly knowledge is very limited.

**Comment by liamwhite** [comment]
What do you mean by within the yuzu repo? The project doesn't ship any mods...

**Comment by SilentStorm-1986** [comment]
I meant the mod wiki.
