### ISSUE TITLE
Super Mario Odyssey crash with new nvidia drivers

### ISSUE THREAD

**Issue by coolllman** [yuzu-emu/yuzu#9063]
Super Mario Odyssey crash (vulkan and opengl) with upscale and new nvidia drivers 522.25 (rtx 3060), crash on start screen or level

**Comment by G-Spawn** [comment]
provide a log please https://yuzu-emu.org/help/reference/log-files/

**Comment by coolllman** [comment]
Sorry, issue fix reboot and download last version yuzu, close

**Comment by G-Spawn** [comment]
All good as long as it works :P Happy emulating.
