### ISSUE TITLE
Shin Megami Tensei V - Texture corruption on MC/World elements after heading into World of Shadows since mainline 1191

### ISSUE THREAD

**Issue by solarmystic** [yuzu-emu/yuzu#9068]
## Summary:-

The main character's textures get bugged out after heading into the World of Shadows since **yfc part 1 got merged in mainline 1191**. In addition, abnormally large and sparkly elements appear in the world after exiting the World of Shadows.

Mainline 1190 is the last build not to have the issue.

SMTV is well known to have rendering issues on Vulkan when paired with AMD cards in the past, but this is the first time i've seen it on NVIDIA cards too.

## Reproduction steps:-

1) Remove pipeline shader caches before booting game for consistent reproduction accuracy.
2) Head into World of Shadows from a save point.
3) Select Apotheosis, then Learn Miracles.
4) The MC will display the wrong colored/stripy textures on his skin, as you repeatedly swap back and forth between Sophia and him. 
5) In addition, when you head out back to the game world, there will be abnormally big sparkly elements accompanying your character.

## Screenshots of the issue:-
Discolored/Corrupted textures on MC in mainline 1191:-
![1191mc](https://user-images.githubusercontent.com/4345150/195798553-86ef0708-b895-4f6f-9f45-0dcbf8156610.PNG)

Abnormally large and sparkly elements after exiting World of Shadows:-
![1191sparkly](https://user-images.githubusercontent.com/4345150/195798567-858202a2-1765-4e8f-8d6d-d96bfd8bb8d8.PNG)

Correct textures on the MC in mainline 1190:-
![1190n](https://user-images.githubusercontent.com/4345150/195800434-da6f5ee9-206e-4cc0-843d-d1bcce0db431.PNG)

## Videos of the issue:-

Mainline 1191 (bugged)

https://user-images.githubusercontent.com/4345150/195796875-71dd202e-fb6b-427b-b0aa-0ed9a223a5b0.mp4

Mainline 1190 (working)

https://user-images.githubusercontent.com/4345150/195796855-f9037ea0-e39f-4605-bb04-78dca8c9ed08.mp4

## Logfiles:-

Mainline 1191 (bugged textures)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9783946/yuzu_log.txt)

Mainline 1190 (working textures)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9783876/yuzu_log.txt)

## System Specifications:-

Intel i5-12400F
NVIDIA RTX 2080 TI on 522.25 drivers
32 GB RAM
Windows 10 21H1

**Comment by OZtistic** [comment]
I think this is a regression n with Y.F.C - I have seen other worse examples in SMT V
#https://github.com/yuzu-emu/yuzu/pull/8467

**Comment by solarmystic** [comment]
> I think this is a regression with Y.F.C - I have seen other worse examples in SMT V ##8467
> 
> Does the same thing happen on mainline 1190? Please update if this fixes it or not

I did mention that the aforementioned issues are resolved with 1190, making it a yfc related issue.

I couldn't find any other worse SMTV examples in that PR, they may have been buried in the conversations. Can you point to those specific examples?

**Comment by Ghaleon7771** [comment]
Dont know if posting this here or opening a new issue, but it has worsen significatively. Even though Yuzu perfomance skyrocketed with lastest EA, this awesome games is still having terrible issues with the graphics as shown here.
![Issue 1](https://github.com/yuzu-emu/yuzu/assets/87739309/ad8156cd-61fb-4490-a1c2-ec2a2d6bf643)
![Issue 2](https://github.com/yuzu-emu/yuzu/assets/87739309/16f361b6-8394-45b2-8a25-7d6c3d0c58e7)

I really hope this gets fixed, Yuzu became my main Switch emu and that is why i became a patreon for the EA builds.

**Comment by solarmystic** [comment]
Finally fixed with mainline 1483/Early Access 3725. Does require GPU HIgh, as per the release notes https://discord.com/channels/398318088170242053/668532415257509958/1124123713982443672

https://github.com/yuzu-emu/yuzu/assets/4345150/06540994-9a08-4dc0-910a-ab699886a65e

Closing.
