### ISSUE TITLE
Yuzu Mainline 1188+ breaks amiibo scanning

### ISSUE THREAD

**Issue by pixelqiwi** [yuzu-emu/yuzu#9070]
Tested on Yuzu Mainline versions: 1180, 1185, 1187, 1188, 1190, 1199
Test Game: AC:NH 2.0.5

When you try to scan a valid .bin file of an amiibo on 1188 or greater, it gives out an error with an error code of 2115-0144 (0x00012073) whereas if you scan one on versions lower than that, it works as intended. When you scan an invalid .bin file though the game just says that it's invalid, as expected, no error there.

Here's a screenshot of the error window.
![unknown](https://user-images.githubusercontent.com/13924553/195922664-b0bbd495-eb17-43ff-849a-add1ac9adb96.png)

Here's a log from 1190, with it giving the error.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9789404/yuzu_log.txt)

Here's a log from 1187, with it working well.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9789432/yuzu_log.txt)

Hoping for this issue to get noticed fast as well!

**Comment by G-Spawn** [comment]
Please use lockpick to dump your amiibo keys and apply it to yuzu in the same place you would your title and prod

**Comment by pixelqiwi** [comment]
That's the first time I hear about amiibo keys in general, everything worked just well as is, on previous versions at least.

**Comment by G-Spawn** [comment]
indeed. This is recent change from @german77 . It will be updated in the quickstart guide in time.

**Comment by pixelqiwi** [comment]
Why though? Why change something that worked well anyway?

**Comment by german77** [comment]
New implementation fully implements amiibos, this includes reading and writing data. As such amiibo keys are mandatory. As for the guide it will be updated once the new guide is reviewed.

Before we didn't need keys because most was faked. Right now is not possible without making the code really messy and confusing.

I will add a warning msg if anyone attempts to load an amiibo without keys

**Comment by pixelqiwi** [comment]
Alright, that makes sense. I'll be sure to spread the word around my community, thank you for your quick responses!
