### ISSUE TITLE
Can't execute the game w/ Vulkan on Intel Arc Pro A30M(similar to A380)

### ISSUE THREAD

**Issue by huki** [yuzu-emu/yuzu#9072]
Using Vulkan w/ Intel Arc Pro A30M and execute the game and force close the yuzu.
But if I use UHD Graphics 770 can run normally.
the attach is the yuzu log file.
<img width="855" alt="image" src="https://user-images.githubusercontent.com/150319/195995901-b265e859-142f-4e7f-b319-913bb3620ac7.png">

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9792524/yuzu_log.txt)

**Comment by liamwhite** [comment]
We have purchased a device and are waiting for it to arrive (ETA 2022-10-19).

**Comment by JeroenAdam** [comment]
Same issue here, tried with Zelda BOTW and Super Mario 3D World.
Crashes with Vulkan, runs with OpenGL and also runs with IGP (Iris Xe) on Vulkan.

**Comment by huki** [comment]
@liamwhite I used EA version(3044 or 3045) and it should include this change,
but I can't execute the game w/ Vulkan on the Intel ARC graphic card.

**Comment by liamwhite** [comment]
@huki you must disable this option in global settings to take advantage of the workaround:
![Screenshot from 2022-10-23 10-21-06](https://user-images.githubusercontent.com/9658600/197397379-a6bec90e-b9a2-4e4b-be0c-cc292c866dee.png)

**Comment by huki** [comment]
Thanks, @liamwhite.
You are right. After disabling the ASTC in the graphic sheet, I can execute it normally.
Thanks a lot.

> @huki you must disable this option in global settings to take advantage of the workaround: ![Screenshot from 2022-10-23 10-21-06](https://user-images.githubusercontent.com/9658600/197397379-a6bec90e-b9a2-4e4b-be0c-cc292c866dee.png)
> 
> Many games still do not work, we are investigating and planning to file issues for Intel.
