### ISSUE TITLE
Mario + Rabbids Kingdom Battle - Texture error

### ISSUE THREAD

**Issue by KazuyaZW** [yuzu-emu/yuzu#9074]
After cutscene in Mario's universe, all textures look like this.
Using Vulkan, 3060ti  (Yuzu 1200 version). Game version 1.98 

![image](https://user-images.githubusercontent.com/115897762/196004654-f7350da4-8f14-4d56-87c9-664876484472.png)

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/reference/log-files/ Please post a log and stick to one issue for the game ideally.

**Comment by G-Spawn** [comment]
This game is already known to be hilariously cursed here. It hasn't been fixed here in years.

**Comment by MysticExile** [comment]
Seems to be duplicate of #9075
