### ISSUE TITLE
Persona 5 Royal black battle screen

### ISSUE THREAD

**Issue by bepis41** [yuzu-emu/yuzu#9081]
When playing persona 5 royal the battle screen is black and only the ui elements show up.

I have attached an example image below.

![p5r black screen](https://user-images.githubusercontent.com/72521428/196047803-5802593b-73a5-4d28-a51e-2278026bd7bb.png)

And this is how it looks on real hardware.

![real hardware](https://user-images.githubusercontent.com/72521428/196048032-0ca72eb9-887e-4a71-884f-dbd220bad263.png)

**Comment by MysticExile** [comment]
This game isn't out yet. We do not support piracy.
