### ISSUE TITLE
Building yuzu-mainline from source fails with VS 17 2022

### ISSUE THREAD

**Issue by perfStack** [yuzu-emu/yuzu#9089]
Was able to build yuzu-mainline using "Visual Studio 17 2022" up until 12th October. After that it fails to build. 

[Error](https://pastebin.com/V4TQhzw1) recieved during build.

Os: Windows 10 21H2

**Comment by perfStack** [comment]
Well I am referring to building from src as mentioned in this [guide](https://github.com/yuzu-emu/yuzu/wiki/Building-For-Windows). My problem is not with the pre-built binaries. Apologies if i am mistaken.

I was able to build [yuzu-mainline](https://github.com/yuzu-emu/yuzu-mainline)[master] from src using "Visual Studio 17 2022" up until 12th October. After that I am receiving this [error](https://pastebin.com/V4TQhzw1) while trying to build yuzu.

**Comment by Docteh** [comment]
ah, looking at the repo it looks like that file was last changed in 1199

Not sure why you're having issues compiling, the MSVC builds are compiled with Visual Studio 2022 on Windows server 2022




refreshenv && mkdir build && cd build && cmake -G "Visual Studio 17 2022" -A x64 -DYUZU_USE_BUNDLED_QT=1 -DYUZU_USE_BUNDLED_SDL2=1 -DYUZU_USE_QT_WEB_ENGINE=ON -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON -DYUZU_ENABLE_COMPATIBILITY_REPORTING=${COMPAT} -DYUZU_TESTS=OFF -DUSE_DISCORD_PRESENCE=ON -DENABLE_QT_TRANSLATION=ON -DDISPLAY_VERSION=1202 -DCMAKE_BUILD_TYPE=Release -DYUZU_CRASH_DUMPS=ON .. && cd ..
========================== Starting Command Output ===========================
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\e8a87881-9523-4753-9adf-270d43d849fa.cmd""
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
-- The C compiler identification is MSVC 19.33.31630.0
-- The CXX compiler identification is MSVC 19.33.31630.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped

I have C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629

Checking compiler version might be good start.

**Comment by perfStack** [comment]
Successfully managed to build 1202, seems like a file must have corrupted while copying to another drive, a fresh clone and everything went smoothly. Thanks for the response.
