### ISSUE TITLE
The Legend of Zelda: Breath of The Wild - Broken Particles in Korok Forest

### ISSUE THREAD

**Issue by Bjorn29512** [yuzu-emu/yuzu#9092]
**DESCRIPTION :** 

Particles in the Korok Forest area of the game are broken and don't animate correctly, testing was done on latest mainline(1202) vulkan with gpu high, additional details have been attached below.

**SYSTEM SPECS :**

- 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.82 GiB RAM | TSC: 2.496GHz | AVX-512+ | FMA3
- Operating system: Windows, Major: 10, Minor: 0, Build: 22000, Service Pack: none, Compatibility mode: 0
- GPU: 'NVIDIA GeForce GTX 1660 SUPER' running on driver 522.25.0.0

**MEDIA FILES SHOWCASING THE ISSUE :**

Bugged :

https://user-images.githubusercontent.com/110204265/196414472-1a44f0ef-eee1-4039-be48-28b87d2c8d81.mp4

Working :

https://user-images.githubusercontent.com/110204265/196411323-fda0aa58-a327-440d-8f17-4c67f574e977.mp4

REPRODUCTION STEPS AND SAVE FILE : 
- Press continue and load the Korok Forest save.
[01007EF00011E000.zip](https://github.com/yuzu-emu/yuzu/files/9809597/01007EF00011E000.zip)

**LOG FILE :** 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9809625/yuzu_log.txt)

**Comment by MysticExile** [comment]
What was the difference between the working and bugged footage, did you use a older yuzu version? If so which one?

**Comment by Bjorn29512** [comment]
> What was the difference between the working and bugged footage, did you use a older yuzu version? If so which one?

i used the 60fps mod since for some reason that makes them work right

**Comment by MysticExile** [comment]
Cool, I can reproduce the issue. Thank you for reporting it!

**Comment by Bjorn29512** [comment]
FIXED
