### ISSUE TITLE
mario+rabbids: kingdom battle crashes after 20 minutes 

### ISSUE THREAD

**Issue by FresheR2007** [yuzu-emu/yuzu#9098]
Hello, I need help. After 20 minutes of playing mario+rabbids: Kingdom Battle, the game crashes without any notification or anything. The emulator just picks up and crashes. Because of this, I'm stuck on a part of the game and can't continue. Put the worst graphics, everything crashes smoothly. If you can please help.
Characteristics PC.
CPU-Intel Core i5 @ 2.80GHz
RAM-16GB
NVIDIA Ge-force Gtx 1060 3gb

**Comment by G-Spawn** [comment]
Stick to the game on your console for now. It hasn't been improved here in a year+. I don't see this changing anytime soon.
