### ISSUE TITLE
Super Mario Party - Texture issues

### ISSUE THREAD

**Issue by yunnieXx** [yuzu-emu/yuzu#9100]
Some texture/graphic issues with some textures with the game Super Mario Party, at the start of the game there are some texture issues as you can see in this screen recording.

Version: yuzu 1205

My Specs:

AMD Ryzen 5 5600H

16gb of ram

GTX 1650

How its Emulated on Yuzi 1205:
https://user-images.githubusercontent.com/33263991/196985891-0c10ce14-2a35-4427-8c4d-25f888dd498f.mp4

How it Should look:
https://user-images.githubusercontent.com/33263991/196986148-f0bd0b87-1f34-44c5-8e3c-d5e431806286.mp4

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/reference/log-files/ provide a log file please

**Comment by yunnieXx** [comment]
> https://yuzu-emu.org/help/reference/log-files/ provide a log file please

Here's the log
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9832173/yuzu_log.txt.old.txt)

**Comment by yunnieXx** [comment]
Heres a log of the game with the new update that I dumped:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9833485/yuzu_log.txt)

**Comment by G-Spawn** [comment]
can you please try using native scaling (x1) and use docked mode? The mario party games aren't really known for working well with the resolution scaler here without some visual issues.

**Comment by yunnieXx** [comment]
> can you please try using native scaling (x1) and use docked mode? The mario party games aren't really known for working well with the resolution scaler here without some visual issues.

The issue is still reproducible even with x1

https://user-images.githubusercontent.com/33263991/197170431-2a4f371f-3f98-49ec-b346-5e1916f8967e.mp4

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9837983/yuzu_log.txt)

**Comment by yunnieXx** [comment]
The issue is still reproducible with x1 and in docked mode.

https://user-images.githubusercontent.com/33263991/197171739-92f37dd4-5b45-482c-9ae7-443c95a9c305.mp4

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9838034/yuzu_log.txt)

**Comment by angiepapa** [comment]
Not sure if you have resolved this already but I was having this issue as well and switching from Vulkan to OpenGL worked for me

https://user-images.githubusercontent.com/36694910/201499559-40369151-dde9-4d21-95ee-6b1b594cc35b.mp4

**Comment by benderscruffy** [comment]
@FearlessTobi 
using Vulkan 
this has been fixed
can be closed

**Comment by ryudious** [comment]
No.  Incorrect.  Using OPENGL fixes it!  Vulcan doesn't work well in this game with textures.
