### ISSUE TITLE
Mouse pointer goes wrong position in docked mode

### ISSUE THREAD

**Issue by min945** [yuzu-emu/yuzu#9111]
**Screenshot for docked mode:** ❌
![docked-mode](https://user-images.githubusercontent.com/2870231/197204454-d9bbe1df-a9fb-47a4-b7b0-0092caf2b36d.png)

**Screenshot for handheld mode:** ✔
![handheld-mode](https://user-images.githubusercontent.com/2870231/197204374-61953850-da52-4807-a4b8-8fdce6dd1044.png)

**Comment by german77** [comment]
Have you ever tried to use touch while docked on the switch. This is unexpected behavior, depends on the game if it's handled correctly or not.
