### ISSUE TITLE
Dorfromantik crashing Yuzu completely with default Vulcan, only works with OpenGL/GLSL

### ISSUE THREAD

**Issue by BananaAcid** [yuzu-emu/yuzu#9116]
Probably Vulcan backend is missing something triggers an error? 01007F2019132000 (v1.1.1) crashes the emulator (Yuzu 1207, 2022-10-22) back to desktop after the intro.

**Comment by gidoly** [comment]
please post log

**Comment by BananaAcid** [comment]
I solved the problem by moving to ryujinx.
