### ISSUE TITLE
Please remove the modding file limit so BDSP can shine. 

### ISSUE THREAD

**Issue by Ullrrific** [yuzu-emu/yuzu#9120]
So currently the Switch and Ryujinx don't have this issue, but I like Yuzu way better than those platforms.

Pokemon Brilliant Diamond is absolutely getting busted wide open atm, modders are adding EVERY SINGLE POKEMON into the game + custom mons, new story content, and new everything basically.

This is a big deal for us fans, but Yuzu currently won't allow the number of files needed to accomplish this goal.

This means that Ryujinx is going to be the only emulator available to us. This is unfortunate because Yuzu is way nicer in-game graphically and runs better for me.

I implore you to remove the file limit so that modding on Yuzu can thrive.

Thank you so much for all the work you've done so far, but **_please_** fix this limitation for us.

![image](https://user-images.githubusercontent.com/63162176/197389963-69c134a6-8bcb-4c34-a629-abaaf0012f5b.png)

**Comment by Docteh** [comment]
![image](https://user-images.githubusercontent.com/190571/197391042-77234e60-169f-4095-a98a-3cb76ea07c60.png)

The first line is the most important there.

**Comment by Squall-Leonhart** [comment]
This issue was resolved in #10729 and can be closed.
