### ISSUE TITLE
yuzu-cmd.exe work perfectly, but Pro Controller, does not Rumble

### ISSUE THREAD

**Issue by mcastellonc201** [yuzu-emu/yuzu#9142]
yuzu-cmd.exe
SDL2 + Vulkan work perfectly, but Nintendo Switch Pro Controller, does not Rumble.

What changes do I need to make to the driver for it to work?
https://github.com/yuzu-emu/yuzu/blob/master/src/input_common/drivers/sdl_driver.cpp

Please.

Regards

**Comment by german77** [comment]
Can you try again. I partially fixed the config

**Comment by mcastellonc201** [comment]
Ok, I will try.
Thanks.

**Comment by mcastellonc201** [comment]
Negative. Not Rumble.
If I do this source, the control vibrates. maybe it will help you.

#include <SDL.h>
#include <stdio.h>

int main(int argc, char* argv[]) {
    SDL_Init(SDL_INIT_JOYSTICK);

    SDL_Joystick* joystick;
    joystick = SDL_JoystickOpen(0);

    printf("Name: %s\n", SDL_JoystickNameForIndex(0));
    char guid[64];
    SDL_JoystickGetGUIDString(SDL_JoystickGetGUID(joystick), guid, sizeof(guid));
    printf("Guid: %s\n", guid);

    SDL_Event event;
    while (1) {
        SDL_WaitEvent(&event);
        if (event.type == SDL_JOYBUTTONDOWN && event.jbutton.button == SDL_CONTROLLER_BUTTON_A) {
            printf("Rumble: Level %i\n", event.jbutton.button);
            SDL_JoystickRumble(joystick, 0x2000, 0x2000, 125);
        }
        if (event.type == SDL_JOYBUTTONDOWN && event.jbutton.button == SDL_CONTROLLER_BUTTON_B) {
            printf("Rumble: Level %i\n", event.jbutton.button);
            SDL_JoystickRumble(joystick, 0x4000, 0x4000, 250);
        }
        if (event.type == SDL_JOYBUTTONDOWN && event.jbutton.button == SDL_CONTROLLER_BUTTON_X) {
            printf("Rumble: Level %i\n", event.jbutton.button);
            SDL_JoystickRumble(joystick, 0x8000, 0x8000, 500);
        }
        if (event.type == SDL_JOYBUTTONDOWN && event.jbutton.button == SDL_CONTROLLER_BUTTON_Y) {
            printf("Rumble: Level %i\n", event.jbutton.button);
            SDL_JoystickRumble(joystick, 0xFFFF, 0xFFFF, 1000);
        }
    }

    SDL_JoystickClose(joystick);
    SDL_Quit();
    return 0;
}

**Comment by mcastellonc201** [comment]
INFO:	
Name: Nintendo Switch Pro Controller
Guid: 030000007e0500000920000000006803
JoystickHasRumble: 1
JoystickHasRumbleTriggers: 0
GameControllerHasRumble: 1
GameControllerHasRumbleTriggers: 0

SOURCE:
#include <SDL.h>
#include <stdio.h>

int main(int argc, char* argv[]) {
    SDL_Init(SDL_INIT_JOYSTICK | SDL_INIT_GAMECONTROLLER);

    SDL_Joystick* joystick = SDL_JoystickOpen(0);
    SDL_GameController* gamecontroller = SDL_GameControllerOpen(0);
    
    if (joystick)
    {
        printf("Name: %s\n", SDL_JoystickNameForIndex(0));
        char guid[33];
        SDL_JoystickGetGUIDString(SDL_JoystickGetGUID(joystick), guid, sizeof(guid));
        printf("Guid: %s\n", guid);
        printf("JoystickHasRumble: %d\n", SDL_JoystickHasRumble(joystick));
        printf("JoystickHasRumbleTriggers: %d\n", SDL_JoystickHasRumbleTriggers(joystick));
    }
    else
    {
        printf("Couldn't open Joystick\n");
    }

    if (gamecontroller)
    {
        printf("GameControllerHasRumble: %d\n", SDL_GameControllerHasRumble(gamecontroller));
        printf("GameControllerHasRumbleTriggers: %d\n", SDL_GameControllerHasRumbleTriggers(gamecontroller));
    }
    else
    {
        printf("Couldn't open Gamecontroller\n");
    }

    SDL_JoystickClose(joystick);
    SDL_GameControllerClose(gamecontroller);
    SDL_Quit();
    return 0;
}

**Comment by VgaCich** [comment]
I'm still have no vibration on Pro Controller in yuzu-cmd, version ea-3382.

```
[ControlsGeneral]
debug_pad_enabled = 0
enable_raw_input = 0
enable_joycon_driver = 1
enable_procon_driver = 0
vibration_enabled = 1
enable_accurate_vibrations = 1
motion_enabled = 1
touch_device=
udp_input_servers =
mouse_panning = 0
mouse_panning_sensitivity = 1.0
emulate_analog_keyboard = 0
mouse_enabled = 0
keyboard_enabled = 0

[ControlsP0]
button_a=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:0
button_b=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:1
button_x=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:2
button_y=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:3
button_lstick=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:7
button_rstick=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:8
button_l=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:9
button_r=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:10
button_zl=engine:sdl,port:0,guid:030000007e0500000920000010026800,axis:4,threshold:0.500000,invert:+
button_zr=engine:sdl,port:0,guid:030000007e0500000920000010026800,axis:5,threshold:0.500000,invert:+
button_plus=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:6
button_minus=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:4
button_dleft=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:13
button_dup=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:11
button_dright=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:14
button_ddown=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:12
button_lstick_left=
button_lstick_up=
button_lstick_right=
button_lstick_down=
button_sl=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:9
button_sr=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:10
button_home=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:5
button_screenshot=engine:sdl,guid:030000007e0500000920000010026800,button:15
lstick=axis_x:0,engine:sdl,invert_x:+,port:0,guid:030000007e0500000920000010026800,axis_y:1,offset_x:-0.019715,offset_y:0.040651,invert_y:+,deadzone:0.150000
rstick=axis_x:2,engine:sdl,invert_x:+,port:0,guid:030000007e0500000920000010026800,axis_y:3,offset_x:0.008850,offset_y:0.052614,invert_y:+,deadzone:0.150000,range:0.950000
motionleft=engine:sdl,guid:030000007e0500000920000010026800,port:0,pad:0,motion:0
motionright=engine:sdl,motion:0,port:0,guid:030000007e0500000920000010026800
```

**Comment by FishOrBear** [comment]
> 我在 yuzu-cmd 版本 ea-3382 中的 Pro Controller 上仍然没有振动。
> 
> ```
> [ControlsGeneral]
> debug_pad_enabled = 0
> enable_raw_input = 0
> enable_joycon_driver = 1
> enable_procon_driver = 0
> vibration_enabled = 1
> enable_accurate_vibrations = 1
> motion_enabled = 1
> touch_device=
> udp_input_servers =
> mouse_panning = 0
> mouse_panning_sensitivity = 1.0
> emulate_analog_keyboard = 0
> mouse_enabled = 0
> keyboard_enabled = 0
> 
> [ControlsP0]
> button_a=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:0
> button_b=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:1
> button_x=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:2
> button_y=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:3
> button_lstick=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:7
> button_rstick=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:8
> button_l=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:9
> button_r=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:10
> button_zl=engine:sdl,port:0,guid:030000007e0500000920000010026800,axis:4,threshold:0.500000,invert:+
> button_zr=engine:sdl,port:0,guid:030000007e0500000920000010026800,axis:5,threshold:0.500000,invert:+
> button_plus=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:6
> button_minus=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:4
> button_dleft=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:13
> button_dup=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:11
> button_dright=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:14
> button_ddown=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:12
> button_lstick_left=
> button_lstick_up=
> button_lstick_right=
> button_lstick_down=
> button_sl=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:9
> button_sr=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:10
> button_home=engine:sdl,port:0,guid:030000007e0500000920000010026800,button:5
> button_screenshot=engine:sdl,guid:030000007e0500000920000010026800,button:15
> lstick=axis_x:0,engine:sdl,invert_x:+,port:0,guid:030000007e0500000920000010026800,axis_y:1,offset_x:-0.019715,offset_y:0.040651,invert_y:+,deadzone:0.150000
> rstick=axis_x:2,engine:sdl,invert_x:+,port:0,guid:030000007e0500000920000010026800,axis_y:3,offset_x:0.008850,offset_y:0.052614,invert_y:+,deadzone:0.150000,range:0.950000
> motionleft=engine:sdl,guid:030000007e0500000920000010026800,port:0,pad:0,motion:0
> motionright=engine:sdl,motion:0,port:0,guid:030000007e0500000920000010026800
> ```

My vibration is also lost, but sometimes it seems to be good again, should I create a new issue?
