### ISSUE TITLE
yuzu font displayed when use chinese and korea

### ISSUE THREAD

**Issue by yzzyzz** [yuzu-emu/yuzu#9145]
device: steamdeck and pc
os: steamos and win11 22H2
yuzu version: 1212 
system: I've tested v15.0 v14.1.2 and v13.2,all of them has problems.

i dump switch firmware 14.1.2 and put them  to nand registered directory and keys,but fonts dosent display correctly.
game : mario odyssey(chinese display as ???),Zelda Link's Awakening(font dosent show),kingdom rush(font dosent show)

there are lots of user reports the problems on website, but there is no solution that can  actual work . i used to run yuzu with old version.the fonts problome can be solved by  dump switch firmware to yuzu nand registered directory. but now ,the new version yuzu cannot be solved by this method.

relative links:
https://github.com/yuzu-emu/yuzu/issues/3101
https://github.com/yuzu-emu/yuzu/issues/7676
and some reddit discussions can be searched.

**Comment by german77** [comment]
Are the keys up to date? Mismatched keys might cause the firmware to fail to load.

**Comment by yzzyzz** [comment]
> Are the keys up to date? Mismatched keys might cause the firmware to fail to load.

of course.
i get v15.0 v13.2 keys and firmwares from intenet.
i dump 14.1.2 keys and firmware from my switch

**Comment by yzzyzz** [comment]
latest : 
i update the 1214,it seems normal now.
