### ISSUE TITLE
Graphical Glitches in Xenoblade Chronicles 3 Keves Castle starting in mainline version 1213

### ISSUE THREAD

**Issue by RenanTafner** [yuzu-emu/yuzu#9147]
Starting in mainline version 1213, there is a graphical glitch when running around in Keves Castle in Xenoblade Chronicles 3, as follows:

https://user-images.githubusercontent.com/5459223/198857829-a0e96f95-4c6f-4b6a-8fb4-932a032a48a7.mp4

Issue dont happen in mainline version 1212 and starts happening in mainline version 1213, so the problem might be some code change in mainline version 1213.

Issue happens with both Vulkan and OpenGL, but the flickering is stronger in Vulkan (the video above is using Vulkan).

Issue still happens even with all mods disabled.

Save file attached (select "Quicksave"):

[saveFileXenoblade3.zip](https://github.com/yuzu-emu/yuzu/files/9894848/saveFileXenoblade3.zip)

Edit:

My Specs:

Laptop Alienware M15 R6

Intel Core I7 11800H
32GB Ram DDR 4 3200MHZ
Geforce RTX 3070 Laptop

Log File:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9894868/yuzu_log.txt)

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/reference/log-files/ Provide a log when you can please.

**Comment by RenanTafner** [comment]
> https://yuzu-emu.org/help/reference/log-files/ Provide a log when you can please.

Post edited with log file.

**Comment by solarmystic** [comment]
In addition to these glitches, i'd like to report that the game's performance also takes a bit of a dive from 1213, it is a more stuttery experience and prone to occasional frame time spikes that weren't present in mainline 1212.
