### ISSUE TITLE
Compilation error: cubeb/cubeb.h: No such file or directory

### ISSUE THREAD

**Issue by KAMiKAZOW** [yuzu-emu/yuzu#915]
Checked out source tree with all submodules.
Tried both -DENABLE_CUBEB on and off – no difference.

In all cases:

```
[  754s] In file included from /home/abuild/rpmbuild/BUILD/yuzu-0.0.20180803+git.c1d54f4a/src/audio_core/cubeb_sink.cpp:8:
[  754s] /home/abuild/rpmbuild/BUILD/yuzu-0.0.20180803+git.c1d54f4a/src/./audio_core/cubeb_sink.h:10:10: fatal error: cubeb/cubeb.h: No such file or directory
[  754s]  #include <cubeb/cubeb.h>
[  754s]           ^~~~~~~~~~~~~~~
[  754s] compilation terminated.

```

If your require more info, you can find everything here: https://build.opensuse.org/package/show/home:KAMiKAZOW:Emulators/yuzu

**Comment by mailwl** [comment]
`git submodule update --init --recursive` ?

**Comment by KAMiKAZOW** [comment]
> git submodule update --init --recursive ?

https://build.opensuse.org/package/view_file/home:KAMiKAZOW:Emulators/yuzu/_service?expand=1
`<param name="submodules">enable</param>` !

**Comment by hcorion** [comment]
that doesn't do it recursively though?

**Comment by jroweboy** [comment]
@hcorion cubeb is a top level submodule and doesn't needed recursive. additionally i *believe* we removed any recursive submodule requirements a while ago

**Comment by hcorion** [comment]
cubeb requires the sanitizers-cmake submodule to be inited, and optionally the googletest submodule, if you want to build it with tests.

**Comment by KAMiKAZOW** [comment]
Citra and Dolphin both have cubeb and the compile fine in OBS.

The cmake command is in https://build.opensuse.org/package/view_file/home:KAMiKAZOW:Emulators/yuzu/yuzu.spec?expand=1 between lines 82 and 89.

**Comment by Hexagon12** [comment]
Is this issue still relevant?

**Comment by KAMiKAZOW** [comment]
Works now
