### ISSUE TITLE
Missing Particle Effects - Bayonetta 3

### ISSUE THREAD

**Issue by BSoDGamingYT** [yuzu-emu/yuzu#9150]
There are many missing smoke/fog particles in Bayonetta 3 currently. As these are critical to some parts of gameplay (Touching them respawns/kills you), their being missing makes it difficult to pass certain parts of the game.

**How it looks on yuzu**
![Screenshot 2022-10-30 105847](https://user-images.githubusercontent.com/38402209/198872926-2439515c-b909-4177-86f2-61ba77d50761.png)

**How it should look (Switch screenshot)**
![Screenshot 2022-10-30 104849](https://user-images.githubusercontent.com/38402209/198872940-71429e96-2798-4da6-9bdb-e9c9e170659a.png)

**System tested:**
AMD Ryzen R9 7900x
Nvidia RTX 4090 (Driver 526.47)

**Log:**
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9895564/yuzu_log.txt)

Reproduction:
Add the provided game save(See below), then select continue from the title screen. Once in gameplay, rotate your camera to see the area with missing particles

Save file: 
[01004A4010FEA000.zip](https://github.com/yuzu-emu/yuzu/files/10096306/01004A4010FEA000.zip)

**Comment by dante3732** [comment]
Same on:
Windows 11 Pro x64 21H2
AMD Ryzen 5 3600 4.2 Ghz
MSI Radeon VEGA 64 8 Gb HBM2 
2x8 Gb DDR4 3200

**Comment by K3nnyn3v** [comment]
Same happened to me

System: 
AMD Ryzen 5 5600X
Nvidia RTX 3070 (Driver 526.47)
2x8 GB DDR4 3200

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9936201/yuzu_log.txt)

**Comment by Pergmen** [comment]
Same on:

Manjaro Linux (Kernel 6.1.1-1)
Ryzen 7 5800X
Radeon RX 6800 (Mesa 22.3.1)
2x16 GB DDR4 3200

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10365848/yuzu_log.txt)

**Comment by Badsombra** [comment]
Same on:

Win 11 22h2
Ryzen 7 4800H 
RTX 3050 (517.48 driver, its the same with current drivers too) 
2x8 GB DDR4 3200

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10511615/yuzu_log.txt)

**Comment by jwxa** [comment]
Same on:

Win 11 22h2
i9 9700k
RTX 2070s
2x 16GB DDR4 3600

**Comment by lithiumfox** [comment]
Still appears to be an issue. While this does _seem_ to only impact some visuals, there are areas where during fights these things can cause damage to you, impacting gameplay.

**Comment by lKomus** [comment]
Fixed in EA 3820:
![yuzu_ltjGnMRbod](https://github.com/yuzu-emu/yuzu/assets/4800879/db2fffde-ee4b-44ad-9da2-19d91b37e9a5)

**Comment by lithiumfox** [comment]
> Fixed in EA 3820:
> ![yuzu_ltjGnMRbod](https://github.com/yuzu-emu/yuzu/assets/4800879/db2fffde-ee4b-44ad-9da2-19d91b37e9a5)
> 

Yup! Seems to be fixed!

**Comment by gidoly** [comment]
fixed on lastest build
