### ISSUE TITLE
Splatoon 3 lighting issue

### ISSUE THREAD

**Issue by piplup55** [yuzu-emu/yuzu#9152]
**Tested Versions:**
[Yuzu 1215](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1215)
Yuzu Early Access 3065

splatoon 3 has a lighting issue when you apply any update, this maybe amd only as it doesn't happen on nvidia i don't know about intel

**1.0.0**:
![image](https://user-images.githubusercontent.com/100526773/198892109-da36a9c2-75f3-46a7-ad3f-9aa083645bb4.png)
![image](https://user-images.githubusercontent.com/100526773/198892166-cffa7beb-6d66-47d5-bd89-1835b6c07c84.png)

**1.1.2**:
![image](https://user-images.githubusercontent.com/100526773/198891950-b2809561-c0e9-44ba-8c5b-77de82964d4f.png)
![image](https://user-images.githubusercontent.com/100526773/198892001-313dc813-1e52-4499-8571-ba1fe699046d.png)

**1.2.1**: 
![image](https://user-images.githubusercontent.com/100526773/198891459-6619781c-feeb-4ec9-8d80-9f6d45819d90.png)
![image](https://user-images.githubusercontent.com/100526773/198891692-c031fa70-c601-4664-8b75-d0c2495c6290.png)

**System Specs:**
Linux:
 - OS: Arch Linux
 - CPU: AMD Ryzen 7 3700X
 - GPU: RX 6600 XT
 - Memory: 64GB, Swap: N/A
 - GPU Driver: Mesa 22.2.1, radv 22.2.1

**Comment by goldenx86** [comment]
Seems to be mesa only. Yay.

**Comment by mio-19** [comment]
I can confirm this on Splatoon 3 update 2.0.1
