### ISSUE TITLE
Yomawari Cover not display

### ISSUE THREAD

**Issue by Pinelliagulu** [yuzu-emu/yuzu#9160]
Game Name：Yomawari: The Long Night Collection - 010043D00BA3200
Screenshots :
![1](https://user-images.githubusercontent.com/116891120/198992611-eab1c071-43aa-427c-975a-325ecb4b60ef.PNG)

![2](https://user-images.githubusercontent.com/116891120/198992618-0875d54d-1615-40db-871b-ac29770bc14a.PNG)

On Ryujinx normal.
![3](https://user-images.githubusercontent.com/116891120/198993280-bdd4f19e-29fd-4974-9ac0-4dfbc1fb6ac9.PNG)

**Comment by gidoly** [comment]
Closes due to including pirated content
