### ISSUE TITLE
Bayonetta 3 - Severe Flashing and Flickering in cutscenes and other instances.

### ISSUE THREAD

**Issue by Bjorn29512** [yuzu-emu/yuzu#9162]
**DESCRIPTION :** 

Game suffers from occasional flickering in cutscenes and other scenarios like new enemy introduction screen.

**SPECS :**

   - 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.82 GiB RAM | TSC: 2.496GHz | AVX-512+ | FMA3
   - Operating system: Windows, Major: 10, Minor: 0, Build: 22000, Service Pack: none, Compatibility mode: 0
   - GPU: 'NVIDIA GeForce GTX 1660 SUPER' running on driver 526.47.0.0

**MEDIA FILES SHOWCASING THE ISSUE :**

https://user-images.githubusercontent.com/110204265/199000961-07aaea21-8f86-4124-96df-e08e3f91b297.mp4

https://user-images.githubusercontent.com/110204265/199001057-6f761014-03ac-4303-85ef-fc06462b61fc.mp4

**REPRODUCTION STEPS AND SAVE FILE :**

- Select the 3rd checkpoint in chapter 1 at the chapter select menu.
- walk forward to play the relevant cutscene
[01004A4010FEA000.zip](https://github.com/yuzu-emu/yuzu/files/9900755/01004A4010FEA000.zip)

**LOG FILE :** 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9900779/yuzu_log.txt)

**Comment by dante3732** [comment]
Same on.
Windows 11 Pro x64 21H2
AMD Ryzen 5 3600 4.2 Ghz
MSI Radeon VEGA 64 8 Gb HBM2 
2x8 Gb DDR4 3200

**Comment by ISS-Daniel** [comment]
Used to having this issue, resolved by update to latest GPU driver (526.98) while cleaning shader cache.

My spec
CPU: AMD Ryzen 5950x 
GPU: Nvidia Geforce RTX 4090 
RAM: 32GB DDR4 3800mhz

One Emulator settings:
Graphic backend: Vulkan (Async shader building ON)
GPU Accuracy: HIGH

**Comment by gidoly** [comment]
close as reported to fix by driver update
