### ISSUE TITLE
Xenoblade 3 check board artifact regression caused by mainline 1193 gpu reg pr

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#9164]
xenoblade 3 graphic ally regressed since mainline 1193

issue that represent video:

https://user-images.githubusercontent.com/66776795/199120539-a308f4df-95ff-47d5-8151-89b581db6c85.mp4

mainline before 1192

![yuzu_ZqGovYuq8A](https://user-images.githubusercontent.com/66776795/199121042-47fb236a-aab3-4aef-b8a1-e9933d602268.jpg)

save for this area:

[bf3game00a.zip](https://github.com/yuzu-emu/yuzu/files/9905375/bf3game00a.zip)

**Comment by solarmystic** [comment]
@gidoly Strange, I cannot reproduce the issue even on the newer mainlines after 1192 (using mainline 1218 here)

![image](https://user-images.githubusercontent.com/4345150/199171820-c2380db9-5358-4036-a1f8-0926b52364e7.png)

Using default settings, with GPU High on a 12400F/2080TI machine on 522.25 drivers

**Comment by Amer-xyz** [comment]
Can confirm this still happens on the latest mainline on AMD hardware
![yuzu_vuFkkujkHf](https://user-images.githubusercontent.com/12303550/205559091-c31909f0-b60f-4627-b5aa-8dee63cfdb40.jpg)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10150984/yuzu_log.txt.old.txt)
