### ISSUE TITLE
Animal Crossing: New Horizons - Polygon error/filter problem

### ISSUE THREAD

**Issue by Johnephen** [yuzu-emu/yuzu#9165]
I've only been using Yuzu for a few days and it may just be my setup wrong, but I also want to help fix bugs as I find this emulator amazing.

https://user-images.githubusercontent.com/86550911/199452197-0d6bc1c8-4970-448c-b3be-c4a237610e51.mp4
![Yuzu ACNH Report 01](https://user-images.githubusercontent.com/86550911/199452909-b83b8096-38d9-4517-93b6-a47a0707adfe.PNG)

As can be seen in the video and/or image, the polygons are visible after catching a fish. I've only caught two on this save and don't know if that only happens only on new fish, but it's a noticeable graphical bug that maybe can be fixed. I use a Radeon RX 6600 XT with a Ryzen 5600G and 16gb RAM.

it can also be the same error as mentioned in this issue: (https://github.com/yuzu-emu/yuzu/issues/8380)

PS: I've now also tried to catch an insect and there was the same graphic error, it's just much weaker there.

**Comment by mcastellonc201** [comment]
hevc decoder - Compile

MSYS2
https://github.com/msys2/msys2-installer/releases/latest

pacman -S mingw-w64-ucrt-x86_64-gcc
git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
cd nv-codec-headers
make install PREFIX=/usr
wget https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
tar xf ffmpeg-snapshot.tar.bz2
cd ffmpeg-snapshot
./configure --arch=x86_64 --target-os=mingw64 --enable-shared \
--disable-everything \
--disable-avdevice \
--disable-avfilter \
--disable-avformat \
--disable-swresample \
--disable-iconv \
--disable-zlib \
--disable-schannel \
--enable-decoder=hevc \
--enable-hwaccel=hevc_nvdec
make -j8
Replace dll for:
libavcodec\avcodec.dll
libavutil\avutil.dll
libswscale\swscale.dll

Good luck.
Regards.

**Comment by RinMaru** [comment]
its an RDNA2 issue that has to fix yet sadly

**Comment by Johnephen** [comment]
Thanks. I've also noticed that this bug is related to the shadows, but if there's no official fix, it's a shame. And sorry mcastellonc201, I use windows and am not that familiar with linux. But thanks anyway.

**Comment by mcastellonc201** [comment]
It's Windows.
https://www.msys2.org/
https://github.com/msys2/msys2-installer/releases/latest

latest:
https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe

this tips is for ffmpeg, not yuzu.
Update codecs an use HEVC to improve performance the textures.

Regards.

**Comment by gidoly** [comment]
it is amd issue it already has opened issue for this
