### ISSUE TITLE
Can you open yuzu source code on gitee I couldn't connect when I started compiling

### ISSUE THREAD

**Issue by RainbowTaro2022** [yuzu-emu/yuzu#9168]
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  buildtrees/versioning_/versions/boost-vcpkg-helpers/0e96a2cb3400bcafd55070d18bdcab64808ada01/portfile.cmake:11 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)

error: building boost-vcpkg-helpers:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-vcpkg-helpers
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-vcpkg-helpers]+Build+error
Include '[boost-vcpkg-helpers] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: 472e9f1a8 2022-10-08 (3 weeks ago)

Please use the prefilled template from G:\Cone\yuzu-latest-true\build\vcpkg_installed\vcpkg\issue_body.md when reporting your issue.

**Comment by vonchenplus** [comment]
The odds are that your request will not be fulfilled, and the only way to do that is to find a wallbreaking software.

**Comment by liamwhite** [comment]
There are no current plans for yuzu to move to a different source host.

**Comment by Docteh** [comment]
That is not error with where yuzu source code is hosted, as you already have the yuzu source code. 

consult the vcpkg.json file https://github.com/yuzu-emu/yuzu/blob/master/vcpkg.json and see if alternative source for "dependencies" is available
