### ISSUE TITLE
One port failed to build. I don't know if it is the fault of boost

### ISSUE THREAD

**Issue by RainbowTaro2022** [yuzu-emu/yuzu#9169]
error: building boost-config:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-config
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-config]+Build+error
Include '[boost-config] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: 472e9f1a8 2022-10-08 (3 weeks ago)

**Comment by OZtistic** [comment]
we don't generally give support for self-builds. 
However, are you following the building instructions correctly?
I am currently building master, I will report back when it's done
What OS are you using @RainbowTaro2022 ?

**Comment by RainbowTaro2022** [comment]
> 

Windows 11

**Comment by OZtistic** [comment]
Considering CI is passing all okay here, I would hazard a guess that the issue is on your end.
Please follow the building guide for Windows and ensure you have all per-requisites and use a stable version of CMake, not an RC build of CMake

**Comment by OZtistic** [comment]
Personally, I use the MSVC method. No worries.
You may have not set some paths or something. 
This would better be discussed in the Discord: 
[https://discord.gg/yuzu-emu](url)
The GitHub is not a support service.
See you there!

**Comment by RainbowTaro2022** [comment]
Obviously, discord.gg cannot visit China

**Comment by OZtistic** [comment]
Then I suggest you follow the build guide properly:
[https://yuzu-emu.org/wiki/building-for-windows/](url)

**Comment by liamwhite** [comment]
Seems to be an issue with vcpkg, not yuzu; please file upstream if appropriate.
