### ISSUE TITLE
Persona 5 Royal - Detaching Hair Issue/Test Results

### ISSUE THREAD

**Issue by whymsical210** [yuzu-emu/yuzu#9177]
Persona 5 Royal
Version 1.0.0
ID 01005CA01580E000
NSP
USA Version

Yuzu Mainline 1222
Vulkan
x2 Resolution
GPU High/Extreme
Docked
Nearest Neighbor Filtering
No AA

P5R has an issue with 60 fps and the hair/glasses detaching in certain locations when moving the MC. 

The fix for this seems to be setting Vysnc as on within nvidia control panel and using yuzu to set the limit to 200% and capping at 60. 
The other half of this fix is the game must be in exclusive fullscreen. Windowed mode or playing in a window appears to still detatch the hair. 

There appears to be a desync issue with windows (or as i understood what i had read). In that even when the above fixes in place. 
Should a person go from fullscreen to a window. The hair will detach again. Going back into full screen resolves this back to normal, 
but if the person say, goes to discord and doesn't bring focus back to yuzu after this. the hair will detach again until focus is restore to yuzu or its left idle for about 5 or so minutes(again the trigger for this half of the issue is caused by going to a window and then back to fullscreen)

**Comment by whymsical210** [comment]
[DATA01.zip](https://github.com/yuzu-emu/yuzu/files/9936007/DATA01.zip)

Here's a save file within a dungeon. So far the room outside the save room there seems to be a good place to test the hair bug.

**Comment by Punkydai** [comment]
I'd like to add something to this : During battles, the character icons on the bottom right are blurred or look very low res and after battle ends, it returns back to normal. Also the floating icons above characters' head (such as confidants) is also very low-res.

**Comment by alexshhadeh** [comment]
I have the same bug, it only appears when unlocking fps above 30.

I can also confirm that playing in exclusive fullscreen "fixes" the issue.

**Comment by Punkydai** [comment]
> 

Does exclusive fullscreen fix it though? I think I've set it to that and ran the emu on fullscreen but the hair detaching still occurs. Also what does the original post mean when it says set yuzu to 200%?

**Comment by gidoly** [comment]
should fixed on last ea and mainline

**Comment by KarenNscmnto** [comment]
Occurring again in the latest versions.
With unlocked VSync and/or 60 FPS Cheats/Mods.
Mainline  1638

![P5R](https://github.com/yuzu-emu/yuzu/assets/64856031/ce5b2e94-be88-425e-9955-fd6383ae301e)

**Comment by alexshhadeh** [comment]
> Occurring again in the latest versions. With yuzu unlocked FPS and/or 60 FPS Cheats/Mods. Mainline 1638
> 
> ![P5R](https://private-user-images.githubusercontent.com/64856031/287446888-ce5b2e94-be88-425e-9955-fd6383ae301e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTM1NDEsIm5iZiI6MTcwMTY5MzI0MSwicGF0aCI6Ii82NDg1NjAzMS8yODc0NDY4ODgtY2U1YjJlOTQtYmU4OC00MjVlLTk5NTUtZmQ2MzgzYWUzMDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEyMzQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmODkwYjRlOGZmY2M2NDMxNjBmNmMzMzY1MTY0MmVkMDUxM2MzZmFkMTI5ODQzNGI5NWZiZDBmNWI1MzAxZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6b1M75muaH7cUjcVGdfwRABwFS8QmorDuj82w2dReXM)
> 
> EDIT: Apparently the use of "Immediate (VSync Off)" VSync Mode fix the problem. More tests needed to be sure.

I can confirm that I have the same issue in the latest Yuzu Mainline version. The problem occurs with "Immediate (VSync Off)" VSync Mode too.
![p5r detachment](https://github.com/yuzu-emu/yuzu/assets/37109990/cf73bd3c-41fa-4a49-9064-65ebc492f440)
