### ISSUE TITLE
Persona 5 Royal - Vulkan - Red transparency status screen 

### ISSUE THREAD

**Issue by whymsical210** [yuzu-emu/yuzu#9179]
Persona 5 Royal
Version 1.0.0
ID 01005CA01580E000
NSP
USA Version

Yuzu Mainline 1222
Vulkan
x2 Resolution
GPU High/Extreme
Docked
Nearest Neighbor Filtering
No AA

The red on the left hand side of the menu there is darker than it should be. When the animation is playing when you first open the window, the shade of red is proper. but when the animation finishes it goes to that dark red. Opengl doesnt appear to have this issue. Seems to be a vulkan thing. 

![image](https://user-images.githubusercontent.com/19926555/199924915-be50cba8-efaf-4f57-be47-954291321df8.png)
Yuzu

![image](https://user-images.githubusercontent.com/19926555/199924955-c09ff0fc-05dd-4c42-9efa-515647aca4c9.png)
PC version

**Comment by Skcyte** [comment]
I would like to add some UI elements not rendered properly. The battle portrait in bottom right on Vulkan. Also happened on certain text in the game such as Persona List on Velvet Room. And still confirmed the issue OP started on latest mainline.

Yuzu Mainline 1245
Vulkan
1x Resolution
GPU High
Docked
FSR

VULKAN
![vlcsnap-2022-11-23-08h47m15s587](https://user-images.githubusercontent.com/18594247/203455598-513b4697-d69d-4174-929f-b5ff25fe2ace.png)
OPENGL
![01005ca01580e000_2022-11-23_08-50-07-010](https://user-images.githubusercontent.com/18594247/203455752-71d31073-5743-48f9-acd9-23bf7ea33169.png)

Also screen flickering when trying to load on busy area, and it's worse on GPU Normal

https://user-images.githubusercontent.com/18594247/203471890-54489867-69b8-44f7-b10f-0d1568afe114.mp4

**Comment by tchofy** [comment]
Just a headsup, both issues mentioned here have been fixed recently on both mainline and early-access.

**Comment by gidoly** [comment]
fixed by #9631
