### ISSUE TITLE
 Colors broken on models and textures in Crash Team Racing Nitro-Fueled Yuzu Mainline 1223

### ISSUE THREAD

**Issue by james5272** [yuzu-emu/yuzu#9184]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9940034/yuzu_log.txt)
![crashyuzubroken](https://user-images.githubusercontent.com/117467705/200019873-7734cf56-6759-48ba-a8a0-e54197e131a7.png)

Crash Team Racing Nitro-Fueled
Version 1.0.15
ID 0100F9F00C696000
NSP
USA Version

Yuzu Mainline 1223
Vulkan
x2 Resolution
GPU Extreme
Bilinear Filtering
No AA

Colors broken on models and textures.

**Comment by solarmystic** [comment]
@james5272 try setting resolution scale to 1x, this should help to workaround the issue for now until it is properly fixed.

**Comment by james5272** [comment]
> @james5272 try setting resolution scale to 1x, this should help to workaround the issue for now until it is properly fixed.

Thanks, that does fix it!
