### ISSUE TITLE
Severe graphical regressions for multiple games when upscaling above 1x since mainline 1223 

### ISSUE THREAD

**Issue by solarmystic** [yuzu-emu/yuzu#9186]
## Summary:-

Mainline 1223 introduced some additional severe graphical regressions in multiple games, in addition to the ones they presently have prior to this build. E,g, https://github.com/yuzu-emu/yuzu/issues/9068

These games looked relatively normal in mainline 1222 (besides the aforementioned issues they already had).

**UPDATE:-** The issue seems to be only present when the resolution scale is 2x or higher. A current workaround is to use 1x until the issue is resolved.

**UPDATE 2:-** Mainline 1224 reverted commits that caused the issue, report kept open for tracking purposes.

**Current affected game list:-** Bayonetta 3, Shin Megami Tensei V, Crash Team Racing, Xenoblade Chronicles DE. and Mario Party Superstars. 

## Screenshots of the issue:-

**SMTV**

Broken in Mainline 1223

![1223 smtv broken](https://user-images.githubusercontent.com/4345150/200021171-7d25ac2e-ddf6-4a78-a014-472b83e846be.PNG)

Normal in Mainline 1222

![image](https://user-images.githubusercontent.com/4345150/200022544-5cfa24c0-182c-43e8-bb79-5056d0f4dcea.png)

**Bayonetta 3**

Broken in Mainline 1223

![1223 flickering borders1](https://user-images.githubusercontent.com/4345150/200021567-23cccac4-f81f-4481-8009-16fdd1d8865c.PNG)

Normal in Mainline 1222

![1222 normal1](https://user-images.githubusercontent.com/4345150/200022297-e20616a6-e860-4cd2-8a21-4d201cf58c83.PNG)

## Saves to reproduce issue:-

SMTV
[0100B870126CE000.zip](https://github.com/yuzu-emu/yuzu/files/9940123/0100B870126CE000.zip)

Bayonetta 3
[01004A4010FEA000.zip](https://github.com/yuzu-emu/yuzu/files/9940120/01004A4010FEA000.zip)

## Logs:-

**SMTV**
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9940095/yuzu_log.txt)

**Bayonetta 3**
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9940113/yuzu_log.txt)

## System Specifications:-

- SYS: 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.86 GiB RAM | TSC: 2.496GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2080 Ti' running on driver 522.25.0.0

**Comment by solarmystic** [comment]
Possibly related to #9184

**Comment by gidoly** [comment]
![yuzu_69VcSkKNzs](https://user-images.githubusercontent.com/66776795/200055930-4098bafc-67e9-4e3a-b202-46e8b3c5bfa9.jpg)
regression on mario party super stars as well

**Comment by gidoly** [comment]
![yuzu_TG2CeRFKsk](https://user-images.githubusercontent.com/66776795/200056340-60a75109-e050-46c6-9269-4fb7071d1f4d.jpg)
xc de

**Comment by solarmystic** [comment]
Reverts committed to mainline 1224 fixed the issue. Closing for now.
