### ISSUE TITLE
spongebob battle for bikini bottom rehydrated graphical issues

### ISSUE THREAD

**Issue by piplup55** [yuzu-emu/yuzu#9193]
**Tested Versions:**
[Yuzu 1225](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1225)
Yuzu Early Access 3085
Yuzu Early Access 3088
Yuzu Early Access 3089

in spongebob battle for bikini bottom rehydrated there some graphic issues, this doesn't happen as much on gpu extreme, can't test opengl as it crashes when loading a video tested,
radv, amdvlk and amdvlk-pro they all have the issue

**Yuzu**:
![image](https://user-images.githubusercontent.com/100526773/200136117-c7bd5671-c29a-4342-b4de-e02a2376ec53.png)
![image](https://user-images.githubusercontent.com/100526773/200136120-310bf7c8-3813-4a6f-957f-371b1b662c50.png)
![image](https://user-images.githubusercontent.com/100526773/200136144-51b1b99c-a19f-4749-901d-f43991af0ed5.png)
**Switch**:
![2022110518515500-9465A26C8319F79D230D2D555FA4E03E](https://user-images.githubusercontent.com/100526773/200136436-c1e962f6-ceed-45aa-865e-3669ad4a2aa4.jpg)
![2022110518514500-9465A26C8319F79D230D2D555FA4E03E](https://user-images.githubusercontent.com/100526773/200136433-51cad602-3681-4d77-8cd6-78e2c1156d6c.jpg)
![2022110518531500-9465A26C8319F79D230D2D555FA4E03E](https://user-images.githubusercontent.com/100526773/200136437-5bd4ab47-79e6-46c6-a1bf-3e9eb6ae0943.jpg)

**Log file**:
[yuzu_log_EA3089.txt](https://github.com/yuzu-emu/yuzu/files/9944542/yuzu_log.txt)

**System Specs:**
Linux:
 - OS: Arch Linux
 - CPU: AMD Ryzen 7 3700X
 - GPU: RX6600 XT
 - Memory: 64GB, Swap: N/A
 - GPU Driver: Mesa 22.2.1, radv 22.2.1, amdvlk 2022.Q4.1-1, amdgpu-pro 22.10.3_1420322-1

Windows: N/A, didn't test windows

**Comment by vonchenplus** [comment]
Fixed by #11278 and #10818
