### ISSUE TITLE
Diablo 3 Eternal Collection hiccups and can't hit 60fps with cubeb output engine

### ISSUE THREAD

**Issue by james5272** [yuzu-emu/yuzu#9196]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9946144/yuzu_log.txt)

Diablo 3 Eternal Collection
Version 2.7.2.79496
ID 01001B300B9BE000
NSP
USA Version

Yuzu Mainline 1226
Vulkan
x2 Resolution
GPU Extreme
Docked
Bilinear Filtering
No AA

On my PC (12600k 3070 32gb RAM everything installed to SSD) runs at ~47fps and hiccups every couple seconds under cubeb.  When I switch to sdl2 to the problem is resolved, however I prefer the EQ of cubeb (sdl2 has more bass).  Possible to get a way to set output engine on a per game basis so I don't forget the fix?

**Comment by Hasster1** [comment]
Same as https://github.com/yuzu-emu/yuzu/issues/8899.
Also, it seems that there is no way to set a sound output engine for a single game. You should probably change this issue into a feature request.

**Comment by james5272** [comment]
Has sound under cubeb now, thanks
