### ISSUE TITLE
Factorio stuck loading 64%

### ISSUE THREAD

**Issue by sentix001** [yuzu-emu/yuzu#9197]

**Comment by gidoly** [comment]
can you provide your pc spec and log as well?

**Comment by sentix001** [comment]
Core-i7-4790
Geforce GTX1060
16GB RAM
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9946872/yuzu_log.txt)

**Comment by FearlessTobi** [comment]
Closing as https://github.com/yuzu-emu/yuzu/issues/10440 is more detailed.
