### ISSUE TITLE
Animal Crossing New Horizons crashes when getting on plane with Steamdeck

### ISSUE THREAD

**Issue by ratherDashing** [yuzu-emu/yuzu#9205]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9955045/yuzu_log.txt)

Install Emudeck, easy install.  Load Animal Crossing and Patch it to the latest veresion.  Play the game and answer all the questions.  Board the plane and when it starts the play the in flight video it will crash.

All software has been updated to the latest version playing on a 64GB Steamdeck

**Comment by Hasster1** [comment]
Not only on steamdeck, This happened to me and a few other people on discord too.

**Comment by ratherDashing** [comment]
Newest build fixes this
