### ISSUE TITLE
Hungry shark world  menu crash

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#9211]
game crashes with dynamic error  before reaches playable screen with dynarmic errors.

![NVIDIA_Share_ze2FAtf4Dn](https://user-images.githubusercontent.com/66776795/200477115-2dcaea95-07ea-4805-bebc-2a9c48b78603.png)

full log:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9957674/yuzu_log.txt)

**Comment by benderscruffy** [comment]
@gidoly 
this goes ingame for myself
has it been fixed for you ???

**Comment by benderscruffy** [comment]
@FearlessTobi 
can be closed 
goes ingame
