### ISSUE TITLE
AI: THE SOMNIUM FILES - nirvanA Initiative 

### ISSUE THREAD

**Issue by Pharmb0y** [yuzu-emu/yuzu#9230]
The game was working fine in Yuzu when it was released in July, I started playing it again a few days ago and it was a very disappointing experience, choppy after every sentence in the VN part, and the 3D gameplay (Psynch) even worse.
I've tried to narrow down the regression version, I think the last one to work as I expected was mainline 1190 or 1191, 1192 has the problem.

More or less default settings
Vulkan with a 5600X CPU and a Vega 56 GPU (with opengl, the game crashes after loading a savegame)

**Comment by german77** [comment]
Could you post some logs

**Comment by Pharmb0y** [comment]
Last good version is 1190, first bad version is 1191.

Here are the logs :
[yuzu_1190_log.txt](https://github.com/yuzu-emu/yuzu/files/9993232/yuzu_1190_log.txt)
[yuzu_1191_log.txt](https://github.com/yuzu-emu/yuzu/files/9993233/yuzu_1191_log.txt)

**Comment by G-Spawn** [comment]
We can't support pirated content here. Closing.
