### ISSUE TITLE
Yuzu will not launch game with GDB debugging enabled

### ISSUE THREAD

**Issue by SilentStorm-1986** [yuzu-emu/yuzu#9236]
I'm not sure if this should be submitted as a feature request or a bug report, however the game I'm debugging will not launch with GDB enabled.

**Comment by G-Spawn** [comment]
The GDB client has to be connected to yuzu or it will endlessly load.

**Comment by merryhime** [comment]
Have you connected the debugger to yuzu? You will need to connect to yuzu as a remote gdbserver on the port you configured in the settings.

**Comment by SilentStorm-1986** [comment]
I can't connect to the process until the game has started, or IDA will return this error: "connect: No connection could be made because the target machine actively refused it. when connecting to 127.0.0.1:6543"

**Comment by SilentStorm-1986** [comment]
I am connecting the debugger to the main executable, not yuzu.

**Comment by liamwhite** [comment]
Two things:
- yuzu will wait for you connect the GDB client when the game is started before allowing any code to run
- yuzu will only allow a single GDB connection per game launch, so if you mess up and need to reconnect, you need to restart the game (fixed by #9225 / mainline 1233)

**Comment by liamwhite** [comment]
I also don't recommend using IDA to debug because it performs stepping incorrectly (instead of using the vCont;s packet it sets a breakpoint on the next instruction). Using gdb from the terminal is your best option.
