### ISSUE TITLE
MultiCore CPU Emulation Crash

### ISSUE THREAD

**Issue by mohammadmahdi255** [yuzu-emu/yuzu#9245]
when i use multicore emulation the game is runnig at first perfectly but after playing suddenly the number and text in pause menu do't show up but at single core it's fine but FPS is getting to low with single core I think It's a problem with assign the tasks or probably some tasks cause deadlock

**Comment by OZtistic** [comment]
It helps to know what game this is that you are running. There should be almost zero reason said unnamed game would do that. please write back or update your post with the relevant details and at least a log

**Comment by zc813** [comment]
@OZtistic I think it’s the same as this open issue: https://github.com/yuzu-emu/yuzu/issues/9174
It’s crashing and reproduceable for multiple games, including p5r, bayonetta 3, etc.

**Comment by german77** [comment]
Closing this issue in favor of #9587

**Comment by MilesTailsFan2005** [comment]
only 2 games I experienced crashes were both sonic games aka

Sonic Origins
Sonic Frontiers
