### ISSUE TITLE
[Feature Request] CMAA2 Support

### ISSUE THREAD

**Issue by Marocco2** [yuzu-emu/yuzu#9256]
Following #9251 , you might want to consider also adding support for CMAA2:
https://www.intel.com/content/www/us/en/developer/articles/technical/conservative-morphological-anti-aliasing-20.html

https://github.com/GameTechDev/CMAA2

**Comment by goldenx86** [comment]
It's DirectX 11/12 only.

**Comment by Marocco2** [comment]
Oof, my bad
