### ISSUE TITLE
Bayonetta 3 non-stop crashing and screen bugs

### ISSUE THREAD

**Issue by YaronElalouf** [yuzu-emu/yuzu#9258]
Hello, I am using Mainline 1238 version.
-There are a lot of issues with Bayonetta 3, the game is crashing in every chapter
-There are a lot of screen bugs like colors are flipped

 Screen bugs example image:
![image](https://user-images.githubusercontent.com/58602721/202827987-ea018a36-e0d9-4a47-9bb7-2104833a5634.png)

-Bayo hair become invisible and the game stuck (Or fps drops) when you look at some point of the map (every level)
-There is no rendering in Normal GPU option.
 

The game is almost not playable in this current state.
There is also a sound problem as you know, which is working ok in Normal GPU mode, But no rendering.

Please consider fixing it, really appreciate your work.

**Comment by YaronElalouf** [comment]
![image](https://user-images.githubusercontent.com/58602721/202880267-492bc329-906d-4b97-bfab-3676792ffb1f.png)

**Comment by gidoly** [comment]
closing due to lacking log feel free to reopen after post log
