### ISSUE TITLE
Weird problem with Bayonetta 3

### ISSUE THREAD

**Issue by TheGigu** [yuzu-emu/yuzu#9259]
I am finaly trying to play Bayo3 but every time I play the chapter there is a graphic glitch that happens, mostly in cutscenes and then the game crashes or you need to reset the game.
The two opening chapters were fine but when you get to Thule isle the game crashes and glitched.
I also tried to delete all the pipline cache but it didn't help.
Please fix it, I've been waiting 9 years for this fcking game! haha 
Thank you for all your work!

I am using version 1237.
Thanks

**Comment by gidoly** [comment]
closing as lacking example ficture and log. feel free to reopen once you post those
