### ISSUE TITLE
Pokemon Scarlet/Violet - Missing graphics on Maxwell 1.0 cards

### ISSUE THREAD

**Issue by 2Tsk2** [yuzu-emu/yuzu#9264]
As the title describes it, Pokemon Scarlet/ Violet only displays a black screen when 3d elements are present on screen (excluding character creation preview after you choose a character during the start of the game ) On maxwell 1.0 cards and the cards bellow said generation.

**Comment by KostaSaizo7** [comment]
Probably related https://github.com/Ryujinx/Ryujinx/pull/3866

**Comment by gidoly** [comment]
should fixed with above pr merged
