### ISSUE TITLE
Regression: Dusk game hangs yuzu while loading

### ISSUE THREAD

**Issue by Tvangeste** [yuzu-emu/yuzu#9267]
Dusk game, which is listed as running GREAT: https://yuzu-emu.org/game/dusk/ , hangs during load on recent versions of yuzu. What's worse, it hangs around 95% of time, and very rarely actually loads.

I did a bit of bisecting and figured out that:
* yuzu 1089 consistently loads the game without any hang ups, every time.
* yuzu 1090 (almost) consistently hangs during the game loading, 95% of the time.

Attached are the two log files from those two (portable) yuzu versions, executing the same Dusk game (tried both, the bare bones game, and with 1.01 update), with the same settings.

Comparing the logs, I noticed the following:
* yuzu 1090 shows two extra lines in logs: `Config <Info> common\settings.cpp:operator ():33: Audio_InputDevice: auto`
* yuzu 1090 shows an extra error in the logs: `[  12.462916] Kernel <Error> core\hle\kernel\svc.cpp:MapSharedMemory:1277: Failed with result: 56321`
* right after where yuzu 1090 hangs, yuzu 1089 shows the following CRITICAL error, but continues the loading: `[  19.431611] Debug <Critical> audio_core\stream.cpp:operator ():51: Assertion Failed! Unimplemented code!`

My hardware details:
- Host CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz | AVX2 | FMA
- Host OS: Windows 10 Version 22H2 (Build 19045.2251)
- Host RAM: 32 Gb
- GPU: nVidia RTX 3080 Ti, drivers 31.0.15.2698 (the latest)

**Comment by Tvangeste** [comment]
[yuzu_log-1089-GOOD.txt](https://github.com/yuzu-emu/yuzu/files/10047485/yuzu_log-1089-GOOD.txt)
[yuzu_log-1090-BAD.txt](https://github.com/yuzu-emu/yuzu/files/10047486/yuzu_log-1090-BAD.txt)

**Comment by Tvangeste** [comment]
Just in case, here's the log from the latest available to me yuzu 1242:
[yuzu_log-1242-BAD.txt](https://github.com/yuzu-emu/yuzu/files/10047507/yuzu_log-1242-BAD.txt)

**Comment by Tvangeste** [comment]
A bit more info. I enabled the Debug-level logging, just to see if I could get any more useful info. And it looks like while the UI is hanging and nothing happens on the screen, yuzu is doing something in a loop behind the scenes, I see the following debug messages in the log indefinitely generated:
```
[  73.812098] Kernel.SVC <Debug> core\hle\kernel\svc.cpp:ResetSignal:2266: called handle 0x002781B6
[  73.828759] Kernel.SVC <Debug> core\hle\kernel\svc.cpp:ResetSignal:2266: called handle 0x002781B6
[  73.845428] Kernel.SVC <Debug> core\hle\kernel\svc.cpp:ResetSignal:2266: called handle 0x002781B6
[  73.862095] Kernel.SVC <Debug> core\hle\kernel\svc.cpp:ResetSignal:2266: called handle 0x002781B6
[  73.878759] Kernel.SVC <Debug> core\hle\kernel\svc.cpp:ResetSignal:2266: called handle 0x002781B6
[  73.895436] Kernel.SVC <Debug> core\hle\kernel\svc.cpp:ResetSignal:2266: called handle 0x002781B6
[  73.912092] Kernel.SVC <Debug> core\hle\kernel\svc.cpp:ResetSignal:2266: called handle 0x002781B6
[  73.928771] Kernel.SVC <Debug> core\hle\kernel\svc.cpp:ResetSignal:2266: called handle 0x002781B6
[  73.945395] Kernel.SVC <Debug> core\hle\kernel\svc.cpp:ResetSignal:2266: called handle 0x002781B6
```

**Comment by FearlessTobi** [comment]
Going off your rebase alone, this seems to be the culprit: https://github.com/yuzu-emu/yuzu/pull/8545

**Comment by Tvangeste** [comment]
With Yuzu 1290 the game is back to normal and can be started every time with no problems.
