### ISSUE TITLE
The Legend of Zelda: Breath of the Wild - Flickering of distant objects on update 1.0.0

### ISSUE THREAD

**Issue by MysticExile** [yuzu-emu/yuzu#9275]
Ever since Mainline 1211 there is an issue of distant objects flickering on the base game of The Legend of Zelda: Breath of the Wild (1.0.0). 

Broken (Mainline 1211 or newer)

https://user-images.githubusercontent.com/30736337/202873372-7237ab7e-35eb-4df6-abf1-835b83f93b34.mp4

Working (Mainline 1210 or older)

https://user-images.githubusercontent.com/30736337/202873383-723a321e-2ca3-4600-b9f0-491a134f7a02.mp4

This occurs on both Vulkan and OpenGL.
This issue has been reproduced on Ampere (RTX 3070) and Ada Lovelace (RTX 4090) testing on different architectures and vendors would be appreciated.
[Save file for quick reproduction](https://github.com/yuzu-emu/yuzu/files/10048042/01007EF00011E000.zip)

**Comment by gitwiq** [comment]
I have the same issue with a GTX 1050. Is there any workaround or setting to avoid that?
