### ISSUE TITLE
Pokémon Shining Pearl Graphical Glitches and FPS drops

### ISSUE THREAD

**Issue by thebigsmileXD** [yuzu-emu/yuzu#9281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 1243

### Description of Issue

As of a recent yuzu update, the game started bugging out and lagging a lot.
Especially the geometry keeps spazzing out here and there, sometimes covering the whole screen. At times it appears so frequently that it reminds me of some Pokémon in the party being inflicted by poison in older titles.

The FPS drops usually happen when effects or sounds are being loaded/played as it seems. The "Frame"s show >300ms whilst lag occurs.

There has been a driver update by nvidia few days ago, but i didn't notice any issues after updating those.

## Media
![image](https://user-images.githubusercontent.com/8733998/202919093-c6472207-a2ba-4562-9d46-42a23dec23cc.png)
https://youtu.be/2e6Fwv6Kfpo
https://youtu.be/joI84GF1V3w

### Expected Behavior

Smooth 30fps gameplay as in the previous yuzu versions.

### Reproduction Steps

Play any level / region of the game. It happens globally

### Log File

**LOG FILE DELETED**

### System Configuration

CPU: Intel(R) Core(TM) i7 CPU K 875 @ 2.93GHz
GPU/Driver: 31.0.15.2698 (NVIDIA 526.98) DCH / Win10 64
RAM: 4 GB 667 MHz DDR3-1333 / PC3-10600 DDR3 SDRAM UDIMM
OS: Microsoft Windows 10 Professional (x64) Build 19044.2251 (21H2)

**Comment by CrusadingNinja** [comment]
Users with pirated games aren't given support here.
