### ISSUE TITLE
Pokemon Scarlet Black screen 

### ISSUE THREAD

**Issue by kiaoru** [yuzu-emu/yuzu#9282]
### Issue

just sharing the problem, here's my log
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10050992/yuzu_log.txt)

**Comment by BSoDGamingYT** [comment]
This is not sufficient information for us to work with. Please add more information as per the issue template

**Comment by kiaoru** [comment]
the menu seems fine when press A button and started loading to the game it just black screen and i see move L analog to wake, my eye @@

**Comment by kiaoru** [comment]
it is because my driver 472? im gonna try updating to 512
