### ISSUE TITLE
Yuzu crashes on if smb drive is not available

### ISSUE THREAD

**Issue by fidesachates** [yuzu-emu/yuzu#9283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1207

### Description of Issue

On the steam deck, when an smb drive is mounted with "x-systemd.automount", the drive won't be mounted until a request to access it is made. This works fine when the drive is accessible, but if the drive is not accessible (e.g. it's no longer on the network), yuzu will start with things greyed out and eventually crash. 

From what I've witnessed, it's likely a system throwing an error as even Dolphin ( the file manager ) is crashing when the drive isn't available. I'm hoping it's possible to wrap this part of the code in yuzu and just move on from it instead of letting the issue bubble up and crash Yuzu. Although, I have noticed that it also doesn't necessarily crash; it sometimes just leaves yuzu in the greyed out state.

### Expected Behavior

 Ideally not only would yuzu not crash, but it would not be left in greyed out state that is unusable. 

### Reproduction Steps

1. Buy steamdeck
2. Configure smb drive with x-systemd.automount option
3. Turn off the server the smb drive is on
4. Open yuzu on steam deck
5. Observe issue

### Log File

Empty

### System Configuration

CPU: AMD Zen 2
GPU/Driver: AMD RDNA 2
RAM: 16 GB LPDDR5
OS: SteamOS 3.0 (Arch-based)

**Comment by liamwhite** [comment]
Is this still an issue?

**Comment by fidesachates** [comment]
This seems to have been fixed. Yuzu takes longer to spin up, but it doesn't crash.
