### ISSUE TITLE
Tracing with GDB Debugger

### ISSUE THREAD

**Issue by SilentStorm-1986** [yuzu-emu/yuzu#9296]
### Issue

I have a main file extracted from a NSP open in IDA, which I am trying to debug with Yuzu GDB debugger. I've attached the IDA debugger to Yuzu, however the tracing window does not populate with any instructions. I'm only seeing CPU threads and registers, which indicates to me that the debugger is not correctly attaching to the game file.

The file running in Yuzu is the NSP file.

Here are my debugger option settings:
Application: C:\dump\1.6.0\ExeFS\main
Input file: &lt;GDB remote process&gt;
Parameters:
Hostname: 127.0.0.1 Port: 9444

**Comment by liamwhite** [comment]
IDA's debugger integration is not well-designed and has numerous shortcomings; this is one of them I encountered while designing the gdbserver. If you want the gdbserver integration to work correctly, I would suggest using gdb in the console instead of IDA.

**Comment by SilentStorm-1986** [comment]
Could the problem be that IDA can't distinguish between the main file and all of the game code being executed?

**Comment by SilentStorm-1986** [comment]
Do you know if it's possible to use GDB debugger with AArch64 from Windows (ie. Cygwin or Mingw)?

**Comment by liamwhite** [comment]
The problem is that IDA's debugger doesn't really implement the gdb remote protocol and instead is mostly designed around its own implementation of a gdbserver using proprietary commands. It is definitely possible to use cross gdb toolchains from Windows, yes.

**Comment by SilentStorm-1986** [comment]
Upon further investigation, I realized that Yuzu's GDB stub only reports threads and memory registers. This means that it is impossible to set instruction breakpoints or do any sort of instruction tracing :(

**Comment by liamwhite** [comment]
That is incorrect. It is possible to set both instruction and memory breakpoints using the gdbserver.

**Comment by SilentStorm-1986** [comment]
I've only been debugging BOTW 1.6.0, however using both IDA and gdb debugger through mingw64, I've only seen memory addresses and threads. If this is all the GDB stub returns, then how will the program know when to execute a breakpoint?

**Comment by liamwhite** [comment]
To set an instruction breakpoint from GDB, you would use e.g. `b *0xdeadbeef`.
To set a memory breakpoint from GDB, you would use e.g. `awatch *0xdeadbeef`.
Note that modules are relocated in memory. Use `monitor get info` to learn the locations of modules at runtime.

**Comment by SilentStorm-1986** [comment]
Do you know if I need a symbol file? GDB returned this error message: 
`Target does not support this command.`

**Comment by liamwhite** [comment]
Update your yuzu version; support for ams monitor commands was added in 1233 with [this commit](https://github.com/yuzu-emu/yuzu-mainline/commit/040a01a5ddf1dc3c8a3c992034803f54e9f2a7af).
