### ISSUE TITLE
Bug report: can not find libssl-1_1-x64_.dll on startup in the latest version

### ISSUE THREAD

**Issue by dennisleetw** [yuzu-emu/yuzu#9301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

latest version

### Description of Issue

roll back to mainline-0-1246 will fix the problem.
[mainline-0-1246](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1246)

### Expected Behavior

Bug report: can not find libssl-1_1-x64_.dll on startup in the latest version

### Reproduction Steps

Bug report: can not find libssl-1_1-x64_.dll on startup in the latest version

### Log File

[yuzu_installer.log](https://github.com/yuzu-emu/yuzu/files/10076773/yuzu_installer.log)

### System Configuration

CPU:Intel I5, Gen 10
GPU/Driver:RX 2600
RAM:16GB
OS:Windows 10

**Comment by liamwhite** [comment]
Azure DevOps broke the Windows 2022 build image last night by polluting the environment with a bunch of random libraries, one of them being OpenSSL. This is not related to any recent code change we made. We are working on a fix.
