### ISSUE TITLE
DEBUG，Explosive sound, very harsh

### ISSUE THREAD

**Issue by xz0606Gb** [yuzu-emu/yuzu#9311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu-windows-msvc-20221123-5d9bec400

### Description of Issue

【New Super Mario Bros. U DX】
The second level has a popping sound, similar to the sound of an airplane engine, which is very harsh.
There is no such crackle at the ground level, but there is a crackle at the underground level.

### Expected Behavior

【New Super Mario Bros. U DX】
The second level has a popping sound, similar to the sound of an airplane engine, which is very harsh.
There is no such crackle at the ground level, but there is a crackle at the underground level.

### Reproduction Steps

【New Super Mario Bros. U DX】
The second level has a popping sound, similar to the sound of an airplane engine, which is very harsh.
There is no such crackle at the ground level, but there is a crackle at the underground level.

### Log File

【New Super Mario Bros. U DX】
The second level has a popping sound, similar to the sound of an airplane engine, which is very harsh.
There is no such crackle at the ground level, but there is a crackle at the underground level.

### System Configuration

CPU: i7
GPU/Driver: nv
RAM:16g
OS:win10

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Closing as you filled out the issue template incorrectly.
