### ISSUE TITLE
Everything white and faint in opengl

### ISSUE THREAD

**Issue by agrim500** [yuzu-emu/yuzu#9316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1251

### Description of Issue

On my device bulkan crazh so i use opengl 
So scarlet is fine but i recieve 7 to 8 fps with this extremely faint and white graphic glitching and its on every main build and ea build

### Expected Behavior

![Uploading RDT_20221125_1500541730800643386152857.gif…]()

### Reproduction Steps

Pls remove this or else we are not able to play

### Log File

Sorry i dont know how to get it

### System Configuration

CPU:amf
GPU/Driver:22.6
RAM:128gb
OS:windows

**Comment by liamwhite** [comment]
You did not provide:
- Specific model of graphics card
- Version of Windows in use
- The log file for yuzu

We cannot help you without this information.

**Comment by agrim500** [comment]
Hey
Window 11
Graphics card gtx force 4000
Amd sorry i dont know how to get log file

**Comment by liamwhite** [comment]
I think you would be better suited by yuzu support channels, since this does not seem like a bug report.
