### ISSUE TITLE
Yuzu Crashing With Vulkan

### ISSUE THREAD

**Issue by SuperDabba** [yuzu-emu/yuzu#9326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All Builds

### Description of Issue

When I try to start any game with vulkan it crashes it used to work an year before but suddenly stopped and I found no solution.
i have all settings to lowest and the games i player used to run at 30 fps

### Expected Behavior

Crashing and Not Responding.

### Reproduction Steps

Using Vulkan and starting any game.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10098232/yuzu_log.txt)

### System Configuration

CPU:i5-7200u
GPU/Driver:Intel HD 620 driver : 31.0.101.2114
RAM:8 gb
OS:Windows 10 Home

**Comment by SuperDabba** [comment]
I forgot but the games I play are Pokemon BDSP , Lets Go Pikachu , Sword and I do not want to use opengl as it causes black screen after intro of these games

**Comment by liamwhite** [comment]
You likely installed something recently that is causing your Vulkan loader to crash. Your log is truncated, please upload a new one that shows you starting a game.

**Comment by SuperDabba** [comment]
when i try to upload log it isnt letting me so ill just copy it here
[   6.278385] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   6.278462] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   7.572121] Frontend <Info> yuzu\main.cpp:GMainWindow:350: yuzu Version: yuzu 1254
[   7.572157] Frontend <Info> yuzu\main.cpp:LogRuntimes:231: MSVC Compiler: 1933 Runtime: 14.32.31332.0
[   7.572160] Frontend <Info> yuzu\main.cpp:LogRuntimes:240: Qt Compile: 5.15.2 Runtime: 5.15.2
[   7.572163] Frontend <Info> yuzu\main.cpp:GMainWindow:366: Host CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz | AVX2 | FMA
[   7.572169] Frontend <Info> yuzu\main.cpp:GMainWindow:368: Host CPU Cores: 2
[   7.572170] Frontend <Info> yuzu\main.cpp:GMainWindow:371: Host CPU Threads: 4
[   7.572302] Frontend <Info> yuzu\main.cpp:GMainWindow:372: Host OS: Windows 10 Version 21H2 (Build 19044.1586)
[   7.572341] Frontend <Info> yuzu\main.cpp:GMainWindow:374: Host RAM: 7.88 GiB
[   7.572344] Frontend <Info> yuzu\main.cpp:GMainWindow:375: Host Swap: 24.00 GiB
[  28.587150] Frontend <Info> yuzu\main.cpp:BootGame:1670: yuzu starting...
[  28.772769] Config <Info> common\settings.cpp:LogSettings:40: yuzu Configuration:
[  28.772775] Config <Info> common\settings.cpp:operator ():33: Controls_UseDockedMode: false
[  28.772776] Config <Info> common\settings.cpp:operator ():33: System_RngSeed: 0
[  28.772777] Config <Info> common\settings.cpp:operator ():33: System_CurrentUser: 0
[  28.772778] Config <Info> common\settings.cpp:operator ():33: System_LanguageIndex: 1
[  28.772779] Config <Info> common\settings.cpp:operator ():33: System_RegionIndex: 1
[  28.772779] Config <Info> common\settings.cpp:operator ():33: System_TimeZoneIndex: 1
[  28.772780] Config <Info> common\settings.cpp:operator ():33: Core_UseMultiCore: true
[  28.772783] Config <Info> common\settings.cpp:operator ():33: CPU_Accuracy: 0
[  28.772784] Config <Info> common\settings.cpp:operator ():33: Renderer_UseResolutionScaling: 0
[  28.772785] Config <Info> common\settings.cpp:operator ():33: Renderer_ScalingFilter: 0
[  28.772786] Config <Info> common\settings.cpp:operator ():33: Renderer_FSRSlider: 25
[  28.772786] Config <Info> common\settings.cpp:operator ():33: Renderer_AntiAliasing: 0
[  28.772787] Config <Info> common\settings.cpp:operator ():33: Renderer_UseSpeedLimit: true
[  28.772787] Config <Info> common\settings.cpp:operator ():33: Renderer_SpeedLimit: 100
[  28.772788] Config <Info> common\settings.cpp:operator ():33: Renderer_UseDiskShaderCache: true
[  28.772789] Config <Info> common\settings.cpp:operator ():33: Renderer_GPUAccuracyLevel: 0
[  28.772790] Config <Info> common\settings.cpp:operator ():33: Renderer_UseAsynchronousGpuEmulation: true
[  28.772790] Config <Info> common\settings.cpp:operator ():33: Renderer_NvdecEmulation: 1
[  28.772791] Config <Info> common\settings.cpp:operator ():33: Renderer_AccelerateASTC: true
[  28.772792] Config <Info> common\settings.cpp:operator ():33: Renderer_UseVsync: false
[  28.772792] Config <Info> common\settings.cpp:operator ():33: Renderer_ShaderBackend: 0
[  28.772793] Config <Info> common\settings.cpp:operator ():33: Renderer_UseAsynchronousShaders: true
[  28.772794] Config <Info> common\settings.cpp:operator ():33: Renderer_AnisotropicFilteringLevel: 0
[  28.772794] Config <Info> common\settings.cpp:operator ():33: Audio_OutputEngine: auto
[  28.772795] Config <Info> common\settings.cpp:operator ():33: Audio_OutputDevice: auto
[  28.772796] Config <Info> common\settings.cpp:operator ():33: Audio_InputDevice: auto
[  28.772796] Config <Info> common\settings.cpp:operator ():33: DataStorage_UseVirtualSd: true
[  28.772798] Config <Info> common\settings.cpp:operator ():37: DataStorage_CacheDir: C:\Users\super\AppData\Roaming\yuzu\cache
[  28.772800] Config <Info> common\settings.cpp:operator ():37: DataStorage_ConfigDir: C:\Users\super\AppData\Roaming\yuzu\config
[  28.772801] Config <Info> common\settings.cpp:operator ():37: DataStorage_LoadDir: C:\Users\super\AppData\Roaming\yuzu\load
[  28.772802] Config <Info> common\settings.cpp:operator ():37: DataStorage_NANDDir: C:\Users\super\AppData\Roaming\yuzu\nand
[  28.772803] Config <Info> common\settings.cpp:operator ():37: DataStorage_SDMCDir: C:\Users\super\AppData\Roaming\yuzu\sdmc
[  28.772804] Config <Info> common\settings.cpp:operator ():33: Debugging_ProgramArgs: 
[  28.772804] Config <Info> common\settings.cpp:operator ():33: Debugging_GDBStub: false
[  28.772805] Config <Info> common\settings.cpp:operator ():33: Input_EnableMotion: true
[  28.772806] Config <Info> common\settings.cpp:operator ():33: Input_EnableVibration: true
[  28.772806] Config <Info> common\settings.cpp:operator ():33: Input_EnableRawInput: false
[  29.154826] Render.Vulkan <Error> video_core\vulkan_common\vulkan_device.cpp:CheckSuitability:916: Missing required extension: VK_EXT_robustness2
[  29.210555] Render.Vulkan <Error> video_core\renderer_vulkan\renderer_vulkan.cpp:RendererVulkan:114: Vulkan initialization failed with error: VK_ERROR_EXTENSION_NOT_PRESENT
[  29.210786] HW.GPU <Error> video_core\video_core.cpp:CreateGPU:53: Failed to initialize GPU: Vulkan initialization error VK_ERROR_EXTENSION_NOT_PRESENT
[  29.222291] Core <Critical> core\core.cpp:Load:286: Failed to initialize system (Error 5)!

**Comment by SuperDabba** [comment]
my vulkan version is 1.2.145

**Comment by german77** [comment]
Update your gpu drivers. I'm currently running with vulkan 1.3.212 so it seems you are quite outdated. You probably have a 2 year old driver. Remember that windows update doesn't update to latest. You have to visit the manufacturer website and get the latest driver there.

**Comment by ttsspp** [comment]
I face the same issues - I was using yuzu few months ago without problems and after recent win10 updates I cant start any game with vulkan on 

win10 | geforce970

i tried new versions of yuzu - went back for old ones - downgraded/upgraded nvidia drivers and still yuzu crash

deleted as well shaders still no workaround

**Comment by DevloperHS** [comment]
I am unable to run it on windows 11. Nvidia GeForce GTX 1650. Says Error to initialize vulkan

**Comment by AncientTree** [comment]
> I deleted again the drivers, deleted all cashes and re-installed 472.12 (clean reinstall) ones and now all works ... very strange ... yesterday I tried several times re-start with new drivers including clean reinstall and it did not work ...

Thanks you very much, you saved me.
