### ISSUE TITLE
es2gears regression

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu#9331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1213 and later

### Description of Issue

es2gears no longer renders correctly. The gears appear as a single face each.
![Screenshot from 2022-11-27 18-52-37](https://user-images.githubusercontent.com/22451773/204166577-8a349715-5669-4286-9eed-2b047dba6c08.png)

OpenGL and Vulkan are affected. Changing driver does not seem to affect the issue.

### Expected Behavior

![Screenshot from 2022-11-27 18-52-18](https://user-images.githubusercontent.com/22451773/204166570-72004f23-8ddb-41dd-a8e2-08b7653cd912.png)

### Reproduction Steps

- Start es2gears homebrew ([source](https://github.com/switchbrew/switch-examples/tree/master/graphics/opengl/es2gears))

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10099480/yuzu_log.txt)

### System Configuration

```
System:
  Host: Qykopi Kernel: 6.1.0-rc4 arch: x86_64 bits: 64 compiler: gcc
    v: 2.35.2-17.el9.0.2 Desktop: GNOME v: 40.10 tk: GTK v: 3.24.31
    wm: gnome-shell dm: GDM Distro: Rocky Linux release 9.1 (Blue Onyx)
    base: RHEL 9.1
CPU:
  Info: 6-core model: 11th Gen Intel Core i5-11600K bits: 64 type: MT MCP
    arch: Rocket Lake rev: 1 cache: L1: 480 KiB L2: 3 MiB L3: 12 MiB
  Speed (MHz): avg: 3918 high: 4609 min/max: 800/4900 cores: 1: 4600 2: 4609
    3: 4210 4: 4599 5: 4600 6: 4402 7: 801 8: 4600 9: 4600 10: 4599 11: 4600
    12: 800 bogomips: 93888
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel RocketLake-S GT1 [UHD Graphics 750] vendor: ASUSTeK
    driver: i915 v: kernel arch: Gen-12.1 ports: active: DP-1,HDMI-A-1
    empty: HDMI-A-2 bus-ID: 00:02.0 chip-ID: 8086:4c8a
  Device-2: NVIDIA GA104GL [RTX A4000] driver: nvidia v: 525.53 arch: Ampere
    pcie: speed: 2.5 GT/s lanes: 16 ports: active: none off: DP-2
    empty: DP-3,DP-4,DP-5 bus-ID: 01:00.0 chip-ID: 10de:24b0
  Device-3: Intel DG2 [Arc A380] vendor: ASRock driver: i915 v: kernel
    arch: Gen-12.7 pcie: speed: 2.5 GT/s lanes: 1 ports: active: none
    empty: DP-6, DP-7, DP-8, HDMI-A-3, HDMI-A-4, HDMI-A-5, HDMI-A-6
    bus-ID: 06:00.0 chip-ID: 8086:56a5
  Device-4: AMD Navi 24 [Radeon RX 6400 / 6500 XT] driver: amdgpu v: kernel
    arch: RDNA-2 pcie: speed: Unknown lanes: 63 ports: active: none
    empty: DP-9,HDMI-A-7 bus-ID: 0b:00.0 chip-ID: 1002:743f
  Device-5: MacroSilicon USB Video type: USB
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo bus-ID: 1-4:3
    chip-ID: 534d:2109
  Display: x11 server: X.Org v: 1.20.11 with: Xwayland v: 21.1.3
    compositor: gnome-shell driver: X: loaded: modesetting,nvidia
    unloaded: fbdev alternate: nouveau,nv,vesa dri: iris
    gpu: i915,nvidia,nvidia-nvswitch display-ID: :1 screens: 1
  Screen-1: 0 s-res: 5120x1440 s-dpi: 96
  Monitor-1: DP-1 pos: right model: Dell S2716DG res: 2560x1440 dpi: 109
    diag: 686mm (27")
  Monitor-2: DP-2 mapped: DP-1-0 note: disabled model: Acer VG270U
    res: 2560x1440 dpi: 109 diag: 685mm (27")
  Monitor-3: HDMI-A-1 mapped: HDMI-1 pos: primary,left model: Acer VG270U
    res: 2560x1440 dpi: 109 diag: 685mm (27")
  API: OpenGL v: 4.6 Mesa 23.0.0-devel renderer: Mesa Intel Graphics (RKL
    GT1) direct render: Yes
```

**Comment by lat9nq** [comment]
Caused by 1f54cd4ac
@vonchenplus you may have some insight here.

**Comment by vonchenplus** [comment]
Last ea is fix this problem.
![image](https://user-images.githubusercontent.com/3349963/204180021-6401c1e5-5764-4cd5-8bcc-0a6a1c8d28d1.png)

**Comment by lat9nq** [comment]
If the issue is on master, the issue needs to remain open until the PR that fixes it is merged.

**Comment by v1993** [comment]
> Last ea is fix this problem.

Nothing tagged for EA right now seems to affect graphics:
![Screenshot_20221128_055824](https://user-images.githubusercontent.com/16255906/204182025-8efc919b-1a24-465c-a465-f92427c15bd8.png)

**Comment by lat9nq** [comment]
Issue is fixed on latest master. Sorry I assumed it was still broken since it has been bugging me the last few days.
