### ISSUE TITLE
Implement missing HD rumble effects

### ISSUE THREAD

**Issue by Mutcholoko** [yuzu-emu/yuzu#9332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

HD Rumble works on Yuzu using a Nintendo Switch Pro Controller. I was in doubt about this at first considering that the motorcycle in Super Mario Odyssey was my testing reference. However, I was wrong, and HD Rumble indeed works, but that one and some other effects do not seem to be working. Some of them in Mario Odyssey are: Motorcycle in Metro Kingdom, sizzly feeling of water, the "zippy" feeling of the zipper in Lake Kingdom, and some other ones.

These effects are missing, and could be implemented.

### Why would this feature be useful?

It would make the experience of emulating Switch games much more faithful to the original experience, guaranteeing the preservation of the Nintendo Switch console and games for years and generations to come. It would also insure that new players could understand better the awesome feeling that HD Rumble provides to the whole experience.

**Comment by Mutcholoko** [comment]
Just wanna provide a little more details on this:

First off, for months I thought that HD Rumble didn't work with Yuzu because I always loaded up a save file in Metro Kingdom on Mario Odyssey, got up on the motorcycle, accelerated, and then noticed that there was no feeling of the motorcycle engine on the controller. After that, I just closed the game and thought "well, it is not implemented yet". I did that for months and months. 
However, today I came across this [GitHub Repo](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering) that was used by @german77 to implement HD Rumble on SDL. So it finally "clicked" for me: It's not that HD Rumble doesn't work, it's just that some effects are not yet implemented. Then I booted Mario Odyssey again and tried some other effects that I knew exactly how they felt. One of them was the squid that shoots water on Seaside Kindgom, you can try it and it definitely works just as it does on the Switch (you can feel the quick bursts of shooting water). The other one that confirmed to me that HD Rumble was actually working was the Telescope Viewer (I don't know the actual name of it), where you can use the gyroscope to look around; it has a "clicky" feeling that is synced with the clicky sounds every now and then when turning the camera around. I also confirmed that this worked by opening Super Mario 3D World (which is a game that I am currently playing on Switch) and seeing that the HD Rumble is present, much like how it is on Switch (it is just a little different in some specific cases, but the difference is negligible).

So I got happy about it and decided to open this feature request. I'm going to study how this works, because it was really well documented by dekuNukem on their repo. I will try to see if I can guess how to make this motorcycle effect using that file, appending a few more rumble patterns to SDL_hidapi_switch.c. However I don't think I'm technically capable of doing that in the present time. For now, I am going to test a few more games that have HD Rumble (that I own on Switch so I can compare) and I'll specify here which effects work and which do not.

Anyways, I think this would add up a lot to the Yuzu experience, and I offer my total cooperation to research and test this thing out. Thank you!

**Comment by Mutcholoko** [comment]
Just wanna provide a little more details on this:

First off, for months I thought that HD Rumble didn't work with Yuzu because I always loaded up a save file in Metro Kingdom on Mario Odyssey, got up on the motorcycle, accelerated, and then noticed that there was no feeling of the motorcycle engine on the controller. After that, I just closed the game and thought "well, it is not implemented yet". I did that for months and months.
However, today I came across this [GitHub Repo](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering) that was used by @german77 to implement HD Rumble on SDL. So it finally "clicked" for me: It's not that HD Rumble doesn't work, it's just that some effects are not yet implemented. Then I booted Mario Odyssey again and tried some other effects that I knew exactly how they felt. One of them was the squid that shoots water on Seaside Kindgom, you can try it and it definitely works just as it does on the Switch (you can feel the quick bursts of shooting water). The other one that confirmed to me that HD Rumble was actually working was the Telescope Viewer (I don't know the actual name of it), where you can use the gyroscope to look around; it has a "clicky" feeling that is synced with the clicky sounds every now and then when turning the camera around. I also confirmed that this worked by opening Super Mario 3D World (which is a game that I am currently playing on Switch) and seeing that the HD Rumble is present, much like how it is on Switch (it is just a little different in some specific cases, but the difference is negligible).

So I got happy about it and decided to open this feature request. I'm going to study how this works, because it was really well documented by dekuNukem on their repo. I will try to see if I can guess how to make this motorcycle effect using that file, appending a few more rumble patterns to SDL_hidapi_switch.c. However I don't think I'm technically capable of doing that in the present time. For now, I am going to test a few more games that have HD Rumble (that I own on Switch so I can compare) and I'll specify here which effects work and which do not.

Anyways, I think this would add up a lot to the Yuzu experience, and I offer my total cooperation to research and test this thing out. Thank you!

**Comment by Mutcholoko** [comment]
I accidentaly closed the issue when posting the comment. It should still be open.

**Comment by german77** [comment]
dekuNukem rumble feels a bit off compared to the switch rumble from the few attempts I have done. I'm still unsure into why.

**Comment by Mutcholoko** [comment]
Yes, it does indeed feel a little bit off, for example: when you enter a level in Super Mario 3D World, in Switch the feeling is somewhat "crispy", whilst in Yuzu (dekuNukem) it is more "mushy" and absorbed if that makes sense. It's not bad, but a little different. It honestly wouldn't matter for me if it didn't miss those effects I mentioned.

Just out of curiosity, are you still researching/thinking/developing stuff related to HD Rumble in any way? I love the work you do when it comes to implementing reverse engineered HID! (yes, I know how specific that is, but it's true lol)

**Comment by german77** [comment]
I haven't spend time on rumble. But I have been doing quite well with amiibos and ring con. I hope I can merge something soon

**Comment by Octelly** [comment]
This doesn't fix the issue for other controllers... Neither a Pro Controller or a Dualsense get me any HD rumble on Linux (only regular, rough rumble).
