### ISSUE TITLE
As of 3144, loading a game switches Docked (default) to Handheld (never actually used on my end)

### ISSUE THREAD

**Issue by RuinerVoid** [yuzu-emu/yuzu#9333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3144

### Description of Issue

My controller profile (all of them) is set up to use Docked as default.

Whenever I load any game, it switches from Docked to Handheld mode on its own. And either I'm blind, or that specific setting isn't configurable on a per-game setting anymore. 

If it's locked in controller profiles, then it's being ignored, as I've tested with both the default profile with Docked and a created profile, also Docked, and it's ignored when loading, whether it's set up as a global default OR in the individual game's controller profile settings.
![Main Window](https://user-images.githubusercontent.com/75164793/204177897-c5345795-5427-46ce-9bc8-bfc0af871ab0.jpg)
![Immediately after Starting Game](https://user-images.githubusercontent.com/75164793/204177918-5c5526ef-4dc1-4848-acfd-b5db9f7d9393.jpg)

### Expected Behavior

When starting a game with Docked as the controls setting, it should remain Docked.

### Reproduction Steps

Use a control profile with the Docked setting. Notice at the bottom, that as the Loading screen comes in, it reverts to Handheld.

### Log File

Really the only part that matters is this one, even though Docked IS set:
[ 271.433870] Config <Info> common\settings.cpp:LogSettings:40: yuzu Configuration:
[ 271.433873] Config <Info> common\settings.cpp:operator ():33: Controls_UseDockedMode: false

### System Configuration

CPU: 5900X
GPU/Driver: 6750XT/Current Win11
RAM: 32GB
OS: Win11 22H2

**Comment by german77** [comment]
Already addressed. Please update to latest EA

**Comment by RuinerVoid** [comment]
> Already addressed. Please update to latest EA

Thank you for pointing this out. For some reason, the EA launcher wasn't updating yuzu anymore so I was quite a few revisions behind.

**Comment by BParks21** [comment]
@german77 This is still happening in EA and now mainline.

**Comment by RuinerVoid** [comment]
> @german77 This is still happening in EA and now mainline. It only effects some games. Not every game will launch in handheld but a lot still do. Mario Odyssey and 3d World and quite a few others are. I always have the global setting set to docked. My profiles are set to pro and I'm not using any handheld profiles.

Just tried SMO and 3D World (+Bowser's Fury) in EA 3259, and this does not happen. I think there might, perhaps, be an issue with a controller profile set in the specific games settings you're having issues have Handheld set instead of Docked. Right click the game in your library, hit Properties, then check the last tab to see if there are any discrepancies. I would heavily suggest checking the individual game's settings to see if you have a specific profile set up in ANY of the 8 slots that might have Handheld set instead of Docked.

**Comment by BParks21** [comment]
I removed every profile from the input config folder. It still happens with no profiles. There are no profiles set for those games, it is set to the global profile which is my pro controller configuration and it is not set to handheld, but like I said I also tried launching these games with none of my profiles even installed in the yuzu config/input folder and the issue persists.
