### ISSUE TITLE
Marvel ultimate aliance 3 glitches + RAM consumption in OpenGL (AMD)

### ISSUE THREAD

**Issue by skrevenge** [yuzu-emu/yuzu#9341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3164

### Description of Issue

Every time i tried to played MUA3 in opengl, my RAM is getting consumed a lot, and start several glitches until game crash. This bug has gotten worse with recent versions, and now I can't even finish a mission without the game crash.

(If you want to know why I want to use opengl instead of vulkan, it's because this specific game has twice the performance with opengl on my machine. The heroes and maps don't appear the way they should, but I don't care. having twice the performance is enough for me.)

### Expected Behavior

This is how the game render in opengl:
![mua3](https://user-images.githubusercontent.com/57811892/204367999-bc0c12de-9e62-4adb-8c18-b94845ba56c5.png)

This is how the game looks when it start to bug:
![mua31](https://user-images.githubusercontent.com/57811892/204368181-a226b4f2-6789-4af1-b216-9382c9f05cba.png)

A print of task manager when the glitches starts:
![mua32](https://user-images.githubusercontent.com/57811892/204368286-26226f9a-4bc1-4cac-a104-fcd542e856f5.png)

### Reproduction Steps

Just open the game in opengl in AMD and play until RAM consumption reach 90-95%.

### Log File

**Log redacted due to containing pirated content**

### System Configuration

CPU: AMD Ryzen 5 2500U
GPU/Driver: Vega 8 Mobile
RAM: 20 GB (256MB/2 GB VRAM)
OS: Windows 10

**Comment by G-Spawn** [comment]
Issue closed due to log containing pirated content. Please dump everything from your nintendo switch if you desire support or want issues to be looked into 🙏
