### ISSUE TITLE
yuzu Linux compiled with qt6 resets Resolution to 0.5x on each yuzu launch

### ISSUE THREAD

**Issue by hurricane-dorian** [yuzu-emu/yuzu#9342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline git 11/28

### Description of Issue

yuzu Linux compiled with qt6 resets Resolution to 0.5x on each launch. Adapting filter and AA also reset but that might be because they are not supported on 0.5X
It happens both on global config and per game config. I reset yuzu settings to make sure it was not some kind of new config incompatibility.

### Expected Behavior

Save the resolution settings set.

### Reproduction Steps

Change resolution to anything other then 0.5X and restart Yuzu

### Log File

[   0.032698] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.032706] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.164347] Frontend <Info> yuzu/main.cpp:GMainWindow:350: yuzu Version: yuzu | r22591.550a01230
[   0.164348] Frontend <Info> yuzu/main.cpp:LogRuntimes:240: Qt Compile: 6.4.1 Runtime: 6.4.1
[   0.164350] Frontend <Info> yuzu/main.cpp:GMainWindow:366: Host CPU: AMD Ryzen 5 3600 6-Core Processor               | AVX2 | FMA
[   0.164367] Frontend <Info> yuzu/main.cpp:GMainWindow:368: Host CPU Cores: 6
[   0.164368] Frontend <Info> yuzu/main.cpp:GMainWindow:371: Host CPU Threads: 12
[   0.164379] Frontend <Info> yuzu/main.cpp:GMainWindow:372: Host OS: Arch Linux
[   0.164388] Frontend <Info> yuzu/main.cpp:GMainWindow:374: Host RAM: 15.54 GiB
[   0.164389] Frontend <Info> yuzu/main.cpp:GMainWindow:375: Host Swap: 20.00 GiB
[   0.247092] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   0.247491] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.4.0) applied successfully
[   0.249192] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   0.251411] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.4.0) applied successfully
[   0.252762] Common.Filesystem <Error> common/fs/fs.cpp:IterateDirEntries:415: Filesystem object at path=/mnt/Games/yuzu/GAMES does not exist
[   0.252765] Common.Filesystem <Error> common/fs/fs.cpp:IterateDirEntries:415: Filesystem object at path=/mnt/Games/yuzu/GAMES does not exist
❯ cat yuzu_log.txt
[   0.032698] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.032706] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.164347] Frontend <Info> yuzu/main.cpp:GMainWindow:350: yuzu Version: yuzu | r22591.550a01230
[   0.164348] Frontend <Info> yuzu/main.cpp:LogRuntimes:240: Qt Compile: 6.4.1 Runtime: 6.4.1
[   0.164350] Frontend <Info> yuzu/main.cpp:GMainWindow:366: Host CPU: AMD Ryzen 5 3600 6-Core Processor               | AVX2 | FMA
[   0.164367] Frontend <Info> yuzu/main.cpp:GMainWindow:368: Host CPU Cores: 6
[   0.164368] Frontend <Info> yuzu/main.cpp:GMainWindow:371: Host CPU Threads: 12
[   0.164379] Frontend <Info> yuzu/main.cpp:GMainWindow:372: Host OS: Arch Linux
[   0.164388] Frontend <Info> yuzu/main.cpp:GMainWindow:374: Host RAM: 15.54 GiB
[   0.164389] Frontend <Info> yuzu/main.cpp:GMainWindow:375: Host Swap: 20.00 GiB
[   0.247092] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   0.247491] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.4.0) applied successfully
[   0.249192] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   0.251411] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.4.0) applied successfully
[   0.252762] Common.Filesystem <Error> common/fs/fs.cpp:IterateDirEntries:415: Filesystem object at path=/mnt/Games/yuzu/GAMES does not exist
[   0.252765] Common.Filesystem <Error> common/fs/fs.cpp:IterateDirEntries:415: Filesystem object at path=/mnt/Games/yuzu/GAMES does not exist
❯ cat yuzu_log.txt.old.txt
[   0.032794] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.032803] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.150982] Frontend <Info> yuzu/main.cpp:GMainWindow:350: yuzu Version: yuzu | r22591.550a01230
[   0.150983] Frontend <Info> yuzu/main.cpp:LogRuntimes:240: Qt Compile: 6.4.1 Runtime: 6.4.1
[   0.150984] Frontend <Info> yuzu/main.cpp:GMainWindow:366: Host CPU: AMD Ryzen 5 3600 6-Core Processor               | AVX2 | FMA
[   0.150996] Frontend <Info> yuzu/main.cpp:GMainWindow:368: Host CPU Cores: 6
[   0.150996] Frontend <Info> yuzu/main.cpp:GMainWindow:371: Host CPU Threads: 12
[   0.151003] Frontend <Info> yuzu/main.cpp:GMainWindow:372: Host OS: Arch Linux
[   0.151011] Frontend <Info> yuzu/main.cpp:GMainWindow:374: Host RAM: 15.54 GiB
[   0.151012] Frontend <Info> yuzu/main.cpp:GMainWindow:375: Host Swap: 20.00 GiB
[   0.224421] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   0.224792] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.4.0) applied successfully
[   0.226474] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   0.228593] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.4.0) applied successfully
[   2.947088] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the sdl2 backend
[   2.949283] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the sdl2 backend
[  12.009412] Config <Info> common/settings.cpp:LogSettings:40: yuzu Configuration:
[  12.009415] Config <Info> common/settings.cpp:operator():33: Controls_UseDockedMode: true
[  12.009416] Config <Info> common/settings.cpp:operator():33: System_RngSeed: 0
[  12.009416] Config <Info> common/settings.cpp:operator():33: System_CurrentUser: 0
[  12.009417] Config <Info> common/settings.cpp:operator():33: System_LanguageIndex: 1
[  12.009417] Config <Info> common/settings.cpp:operator():33: System_RegionIndex: 1
[  12.009418] Config <Info> common/settings.cpp:operator():33: System_TimeZoneIndex: 0
[  12.009418] Config <Info> common/settings.cpp:operator():33: Core_UseMultiCore: true
[  12.009419] Config <Info> common/settings.cpp:operator():33: CPU_Accuracy: 0
[  12.009420] Config <Info> common/settings.cpp:operator():33: Renderer_UseResolutionScaling: 3
[  12.009420] Config <Info> common/settings.cpp:operator():33: Renderer_ScalingFilter: 5
[  12.009420] Config <Info> common/settings.cpp:operator():33: Renderer_FSRSlider: 25
[  12.009421] Config <Info> common/settings.cpp:operator():33: Renderer_AntiAliasing: 1
[  12.009421] Config <Info> common/settings.cpp:operator():33: Renderer_UseSpeedLimit: true
[  12.009422] Config <Info> common/settings.cpp:operator():33: Renderer_SpeedLimit: 100
[  12.009422] Config <Info> common/settings.cpp:operator():33: Renderer_UseDiskShaderCache: true
[  12.009422] Config <Info> common/settings.cpp:operator():33: Renderer_GPUAccuracyLevel: 1
[  12.009423] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousGpuEmulation: true
[  12.009423] Config <Info> common/settings.cpp:operator():33: Renderer_NvdecEmulation: 2
[  12.009423] Config <Info> common/settings.cpp:operator():33: Renderer_AccelerateASTC: true
[  12.009424] Config <Info> common/settings.cpp:operator():33: Renderer_UseVsync: true
[  12.009424] Config <Info> common/settings.cpp:operator():33: Renderer_ShaderBackend: 0
[  12.009425] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousShaders: false
[  12.009425] Config <Info> common/settings.cpp:operator():33: Renderer_AnisotropicFilteringLevel: 5
[  12.009425] Config <Info> common/settings.cpp:operator():33: Audio_OutputEngine: auto
[  12.009426] Config <Info> common/settings.cpp:operator():33: Audio_OutputDevice: auto
[  12.009426] Config <Info> common/settings.cpp:operator():33: Audio_InputDevice: auto
[  12.009426] Config <Info> common/settings.cpp:operator():33: DataStorage_UseVirtualSd: true
[  12.009427] Config <Info> common/settings.cpp:operator():37: DataStorage_CacheDir: /home/dorian/.cache/yuzu
[  12.009428] Config <Info> common/settings.cpp:operator():37: DataStorage_ConfigDir: /home/dorian/.config/yuzu
[  12.009433] Config <Info> common/settings.cpp:operator():37: DataStorage_LoadDir: /home/dorian/.local/share/yuzu/load/
[  12.009434] Config <Info> common/settings.cpp:operator():37: DataStorage_NANDDir: /home/dorian/.local/share/yuzu/nand/
[  12.009434] Config <Info> common/settings.cpp:operator():37: DataStorage_SDMCDir: /home/dorian/.local/share/yuzu/sdmc/
[  12.009434] Config <Info> common/settings.cpp:operator():33: Debugging_ProgramArgs:
[  12.009435] Config <Info> common/settings.cpp:operator():33: Debugging_GDBStub: false
[  12.009438] Config <Info> common/settings.cpp:operator():33: Input_EnableMotion: true
[  12.009438] Config <Info> common/settings.cpp:operator():33: Input_EnableVibration: true
[  12.009438] Config <Info> common/settings.cpp:operator():33: Input_EnableRawInput: false

### System Configuration

CPU: Ryzen 5 3600
GPU/Driver: rx5700
RAM: 16gb
OS: Arch

**Comment by hurricane-dorian** [comment]
I did some testing following your suggestion and it seems setting either "adaptive filter" to FidelityFX or AA to FXAA will cause the reset to 0.5x and nearest neighbor with AA off. If I avoid those 2 options things work just fine.

**Comment by HurricanePootis** [comment]
This happens with me too
