### ISSUE TITLE
Violet Mod Bug

### ISSUE THREAD

**Issue by ItsBlackJ** [yuzu-emu/yuzu#9350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Main 1254

### Description of Issue

Pokémon Violet using Pokémon Scarlet Data while using Mods

### Expected Behavior

When launching Pokémon Violet, Yuzu will load the Pokémon Scarlet Data instead (Including Mods/Updates, Save File and other Yuzu Properties). This can been seen with the following screenshots where Pokémon Scarlet has no save file while Pokémon Violet does but when I launch Violet it detects no save. This can also be seen when being in-game for Pokémon Violet and pressing the "Configure Current Game" setting

Pokémon Scarlet Save Folder: (That file you see there is just to make sure Scarlet detects it has no save)
![Screenshot_19](https://user-images.githubusercontent.com/103385976/204464193-ac463dad-b132-4133-9873-71a9bf4392df.png)

Pokémon Violet Save Folder
![Screenshot_18](https://user-images.githubusercontent.com/103385976/204464240-6ae6a6cc-5f56-4308-a36e-a16101485e4c.png)

Pokémon Violet In-Game
![Screenshot_17](https://user-images.githubusercontent.com/103385976/204464300-e315a684-3abb-4706-89ab-762b9f5a8999.png)

"Configure Current Game" Screen
![Screenshot_20](https://user-images.githubusercontent.com/103385976/204464795-0e8961de-22ef-4d14-ba5c-4d77d9f3e5fb.png)

### Reproduction Steps

You need to have Pokémon Scarlet and Violet
Have built property files for both
Install a Mod to Violet - (This is the one I used https://gamebanana.com/mods/download/414138#FileInfo_897581)
Launch the game

### Log File

The Log was too big so here is a zip
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/10110695/yuzu_log.zip)

### System Configuration

CPU: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.5 GHz
GPU/Driver: RTX 2060
RAM: 32GB
OS: Win 11

**Comment by Morph1984** [comment]
This particular mod spoofs the current program ID as Pokemon Scarlet, and so yuzu is tricked into thinking that it is running Scarlet rather than Violet

**Comment by Morph1984** [comment]
Ask the mod creator if this is intended behavior. As far as I'm currently concerned, this isn't an issue with yuzu as the mod is spoofing the program ID to be that of Scarlet.

**Comment by Morph1984** [comment]
As a tentative fix, delete the main.npdm file from the exefs folder and see if it works
