### ISSUE TITLE
Do you have plan to run natively on ARM64 platform?

### ISSUE THREAD

**Issue by Quenii** [yuzu-emu/yuzu#9361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

There are ARM64 board with powerful arm64 cpu, which capable to run switch games.

one of those CPU is RK3588, spec below
http://www.rock-chips.com/a/en/index.html

### Why would this feature be useful?

On arm CPU, run native code will be far more efficient.

**Comment by FearlessTobi** [comment]
Support for native ARM64 has already been added for 32-bit games: https://github.com/yuzu-emu/yuzu/pull/9198.
ARM64 for 64-bit games will follow soon: https://github.com/merryhime/dynarmic/pull/719.
