### ISSUE TITLE
[Linux] Build failure

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#9362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Commit 4e89979c87dfa77f0c55b03a5aaf00706276c2f0

### Description of Issue

Building fails on linux.  This is apparently a recent regression as builds succeeded as of aaada241dccebb94287342d498d7ca538e42be68 (can bisect if needed).

### Expected Behavior

Build should succeed

### Reproduction Steps

Attempt Ninja build with the following CMake flags:

`cmake .. -GNinja -DYUZU_USE_QT_WEB_ENGINE=ON -DYUZU_USE_BUNDLED_VCPKG=ON -DYUZU_TESTS=OFF`

### Log File

Build log: [build.log](https://github.com/yuzu-emu/yuzu/files/10126543/build.log)

### System Configuration

CPU: Intel i7-10870H
GPU/Driver: Nvidia GTX 3070 / 520.56
RAM: 32GB
OS: Linux Mint 21 (Ubuntu 22.04 base)
CMake version: 3.24
GCC version: 11.3.0

**Comment by hurricane-dorian** [comment]
Same issue on Rollling Arch
cmake version 3.25.1
gcc version 12.2.0
ninja 1.11.1
clang version 14.0.6

**Comment by Shoegzer** [comment]
Confirmed #9364 fixes this (thanks @liamwhite). I will close this once merged unless someone else does first.

**Comment by lat9nq** [comment]
Caused by #9349

**Comment by Shoegzer** [comment]
Update: after testing I found #9367 also fixes this (thanks @lat9nq).

**Comment by lat9nq** [comment]
> Update: after testing I found #9367 also fixes this (thanks @lat9nq).

Thanks for testing!
