### ISSUE TITLE
Stardew Valley flip viewport

### ISSUE THREAD

**Issue by nk3z** [yuzu-emu/yuzu#9368]
![Screenshot from 2022-12-01 20-05-46](https://user-images.githubusercontent.com/68327041/205140053-f7bfa308-cad5-4023-b157-ce2f83455068.png)

### Affected Build(s)

1256 flatpak

### Description of Issue

On the 1.5.4.2 version of stardew valley, the game looks rotated with vulkan, OpenGL doesn't even work. Without update the game no problem.

### System Configuration

CPU:amd ryzen 7 4000 series
GPU/Driver: rtx 2060 max Q
RAM: 16gb
OS: garuda os

**Comment by rixingyie** [comment]
please fix it

**Comment by yingjiegau** [comment]
still thee same here, flipped ; yuzu 1325, and no mod found

**Comment by JumpLink** [comment]
Same here, this was happen for me after I upgrade Stardew Valley to v1.5.4.2, previously I used V1.2 where the problem did not occur.

**Comment by MysticKillerBear** [comment]
any updates?

**Comment by JumpLink** [comment]
If the bug is hard to find / fix, a workaround would be great, e.g. one where the game can be mirrored manually via the settings

**Comment by DDrix12** [comment]
any updates ?
