### ISSUE TITLE
[Bug Report] Front Mission won't boot

### ISSUE THREAD

**Issue by NineKain** [yuzu-emu/yuzu#9384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1261

### Description of Issue

Front Mission won't get past the boot sequence
![image](https://user-images.githubusercontent.com/72826232/205674375-c152ff6b-758d-4f8b-bda8-a6d52e1b6094.png)

### Expected Behavior

Game booting

### Reproduction Steps

Open the game and wait

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10155431/yuzu_log.txt.old.txt)

### System Configuration

CPU: R5 5600x
GPU/Driver: 3060ti/527.37
RAM: 16gb
OS: win10

**Comment by Ryan2603** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10580185/yuzu_log.txt)


latest EA3361 log file for your information
