### ISSUE TITLE
Yuzu cannot detect OpenGL or Vulkan AMD APU/GPUs on MESA 22.3.0

### ISSUE THREAD

**Issue by ordovice** [yuzu-emu/yuzu#9403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1262, Maineline 1261, All other version tested so far

### Description of Issue

On a working Batocera Linux system with MESA 22.1.7 upgraded to then run MESA 22.3.0, yuzu fails to detect the GPU supports OpenGL or Vulkan properly.  Can be seen by just launching the app.  

### Expected Behavior

GPU should be detected as supported and initialized as expected

### Reproduction Steps

Run yuzu mainline appimage on Batocera Linux v36.

### Log File

[yuzu_log_1262_opengl_mesa22.3.0.txt](https://github.com/yuzu-emu/yuzu/files/10178333/yuzu_log_1262_opengl_mesa22.3.0.txt)
[yuzu_log_1262_vulkan_mesa22.3.0.txt](https://github.com/yuzu-emu/yuzu/files/10178335/yuzu_log_1262_vulkan_mesa22.3.0.txt)

### System Configuration

CPU: AMD Ryzen 5 5600H with Radeon Graphics | AVX2 | FMA
GPU/Driver: AMD RENOIR (LLVM 13.0.1, DRM 3.46, 5.18.19)
RAM: 16GB
OS: Batocera Linux

**Comment by ordovice** [comment]
Other systems people have seen this issue on is the Steam Deck

**Comment by liamwhite** [comment]
Please list the contents of /usr/share/vulkan/icd.d and indicate whether radeon_icd.x86_64.json is present

If it is, then try running yuzu with `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json yuzu` and report back whether it will run

**Comment by ordovice** [comment]
Re-updating.  Will let you know, but should the Vulkan ICD file impact OpenGL?  Both are broken.

**Comment by ordovice** [comment]
Yes, file is present and contains 
      {
          "ICD": {
              "api_version": "1.3.230",
              "library_path": "/usr/lib/libvulkan_radeon.so"
          },
          "file_format_version": "1.0.0"
      }
The same as the MESA 22.1.7 install.  I will note that with the recent version, it goes to a black screen instead of the OpenGL not found error as before.  

With Vulkan, the log has the following error:
[   0.406484] Render.Vulkan <Error> video_core/vulkan_common/vulkan_instance.cpp:AreExtensionsSupported:91: Required instance extension VK_KHR_xlib_surface is not available
[   0.406615] Render.Vulkan <Error> video_core/renderer_vulkan/renderer_vulkan.cpp:RendererVulkan:114: Vulkan initialization failed with error: VK_ERROR_EXTENSION_NOT_PRESENT
[   0.406642] HW.GPU <Error> video_core/video_core.cpp:CreateGPU:57: Failed to initialize GPU: Vulkan initialization error VK_ERROR_EXTENSION_NOT_PRESENT

**Comment by liamwhite** [comment]
Your mesa installation is probably messed up. VK_KHR_xlib_surface is supported by the most recent version:
```
radv_device.c:   .KHR_xlib_surface = true,
```

**Comment by ordovice** [comment]
I'm letting the Batocera Devs know as other emus are working fine with Vulkan, so I'm not sure how it would be unavailable for yuzu only

**Comment by ordovice** [comment]
Additionally, vulkaninfo shows it being present
Vulkan Instance Version: 1.3.231


Instance Extensions: count = 20
===============================
        VK_EXT_acquire_drm_display             : extension revision 1
        VK_EXT_acquire_xlib_display            : extension revision 1
        VK_EXT_debug_report                    : extension revision 10
        VK_EXT_debug_utils                     : extension revision 2
        VK_EXT_direct_mode_display             : extension revision 1
        VK_EXT_display_surface_counter         : extension revision 1
        VK_KHR_device_group_creation           : extension revision 1
        VK_KHR_display                         : extension revision 23
        VK_KHR_external_fence_capabilities     : extension revision 1
        VK_KHR_external_memory_capabilities    : extension revision 1
        VK_KHR_external_semaphore_capabilities : extension revision 1
        VK_KHR_get_display_properties2         : extension revision 1
        VK_KHR_get_physical_device_properties2 : extension revision 2
        VK_KHR_get_surface_capabilities2       : extension revision 1
        VK_KHR_portability_enumeration         : extension revision 1
        VK_KHR_surface                         : extension revision 25
        VK_KHR_surface_protected_capabilities  : extension revision 1
        VK_KHR_wayland_surface                 : extension revision 6
        VK_KHR_xcb_surface                     : extension revision 6
        VK_KHR_xlib_surface                    : extension revision 6

**Comment by uureel** [comment]
@ordovice 
you pasted vulkaninfo= Vulkan Instance Version: 1.3.231
but icd shows "api_version": "1.3.230",
maybe icd is borked

**Comment by goldenx86** [comment]
I would check that route, it seems like Batocera has a love for breaking Mesa constantly.

**Comment by ordovice** [comment]
This is not a third party appimage @dmanlfc , it is the yuzu released appimage.  Please don't assume as you have said, either!  This is the latest yuzu appimage running on the latest Batocera beta.

**Comment by dmanlfc** [comment]
Third party as in not provided by Batocera.

**Comment by ordovice** [comment]
And I am not raising the issue with the Batocera team as I don't think the MESA implementation is broken.  Ryujinx works perfectly fine on the same upgraded system.

**Comment by dmanlfc** [comment]
So does Yuzu, just not the appimage it seems.

**Comment by ordovice** [comment]
In further testing, MESA 22.2.1 appears to work, but MESA 22.2.2, MESA 22.2.4, and MESA 22.2.3 are broken all with the same appimage.  
Interestingly, yuzu-cmd works (which I believe is what @dmanlfc is referring to), so I believe this is still an issue with the appimage version and possibly libraries that are packaged with it.
