### ISSUE TITLE
Signalis won't boot

### ISSUE THREAD

**Issue by Tvangeste** [yuzu-emu/yuzu#9407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1264

### Description of Issue

The game doesn't boot.

### Expected Behavior

Expected to game to be playable.

### Reproduction Steps

Launch the game, and watch the never ending progress bar.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10189277/yuzu_log.txt)

### System Configuration

Host CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz | AVX2 | FMA
Host OS: Windows 10 Version 22H2 (Build 19045.2251)
Host RAM: 31.94 GiB
GPU: nVidia 3080Ti

**Comment by Tvangeste** [comment]
More detailed log file: 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10189294/yuzu_log.txt)

Unknown / unimplemented function 'FlushAccessLogOnSdCard': port='fsp-srv' cmd_buf={[0]=0x6, [1]=0xC, [2]=0x0, [3]=0x0, [4]=0x100001, [5]=0x1, [6]=0x0, [7]=0x0, [8]=0x49434653}

**Comment by FearlessTobi** [comment]
Boots fine on my system.

**Comment by Tvangeste** [comment]
Can confirm, the game starts and runs fine now. Thanks!
