### ISSUE TITLE
Wii Controller Support

### ISSUE THREAD

**Issue by Janmm14** [yuzu-emu/yuzu#9410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Wii Controller Support

### Why would this feature be useful?

Reusing old controllers for example for (splitscreen) multiplayer.
Or wanting to use MKWii-Wheel for MK8Deluxe.

**Comment by goldenx86** [comment]
Until SDL adds support for them, we don't have much to do.
Use a directinput driver like this to then manually map it: https://www.julianloehr.de/educational-work/hid-wiimote/

**Comment by Janmm14** [comment]
I got it to work with WiimoteHook (UDP Server), using Wii Pro Controller Motion Input.

The problem is that, compared to PadTest, the motion information is a whole second or even more delayed in MK8Deluxe using yuzu.
