### ISSUE TITLE
WITCH ON THE HOLY NIGHT  010012A017F18000

### ISSUE THREAD

**Issue by fred1357v2** [yuzu-emu/yuzu#9413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1265

### Description of Issue

The game is a VN (Visual Novel) , when the background image change there is a slowdown from 60fps to 4-30 fps for about 1s

### Expected Behavior

To work at a stable 55-60 fps

### Reproduction Steps

![image](https://user-images.githubusercontent.com/106231740/206769227-b7c957ef-e5d0-4181-be31-72c12a52ea1c.png)
![image](https://user-images.githubusercontent.com/106231740/206769316-cbdc91af-e9b5-4c29-b1f3-59b74440235f.png)

### Log 
**logs removed due to user pirating content**

### System Configuration

CPU: AMD Ryzen 5 3600X 6-Core Processor
GPU/Driver: Nvidia GTX 1060  driver 526.98
RAM: 16 GB 3200  mhz dual channel 
OS: Windows 10 Pro Version 22H2  OS build: 19045.2251

**Comment by G-Spawn** [comment]
We sadly cant support pirates here. Closing issue.
