### ISSUE TITLE
Ability to display split screen to another screen

### ISSUE THREAD

**Issue by Sweazou** [yuzu-emu/yuzu#9414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Hi, idk if it's possible but you could add an option to display split screen game on multiples screens.

### Why would this feature be useful?

Because everyone playing split screen could have their screen and have a better experience

**Comment by SleepingSnakezzz** [comment]
This sounds not doable. Generally speaking, an emulator can only _enhance_ what the game does on console, it can't _change_ the way it does things. That's more the territory of mods, and even then, it would be on a per-game basis. Not something you could globally make happen for all games that have split screen. Every game implements that feature differently after all.
