### ISSUE TITLE
Virtua Racing regression

### ISSUE THREAD

**Issue by SMadman16** [yuzu-emu/yuzu#9428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1251 until latest 1269

### Description of Issue

Seems there is a regression starting on 1251.

### Expected Behavior

Same 2D graphics corruption displayed on issue #5913.

### Reproduction Steps

Tried manually installing 1250 and back 4 versions. Issue was non existent. Tried a clean install of 1251, and issue follows all the way to 1269.

### Log File

[REMOVED]

### System Configuration

CPU: 3900xt
GPU/Driver: RX6900xt/22.11.1
RAM:32GB
OS: Windows 11

**Comment by Eloeri** [comment]
@SMadman16 Everything for yuzu must come from your Nintendo Switch. We don't support piracy.
