### ISSUE TITLE
Config-File for Games

### ISSUE THREAD

**Issue by WonnerH** [yuzu-emu/yuzu#9429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Config-Files for Gamez with special settings. 

### Why would this feature be useful?

Some Games require special settings to run like Mario and Sonic Tokio 2020 needs extended memory layout to 6 GB RAM + CPU Accurate: Paranoid + Unbox under graphics: Disk pipeline chace. There are several games who need also special setting that the game will run. 

Maybe these config-files can be stored on github.

**Comment by goldenx86** [comment]
Right click a game, properties, set a custom configuration for it.
