### ISSUE TITLE
Bug while playing Shinigami to Shoujo: games crashes after the opening.

### ISSUE THREAD

**Issue by Norowareshi** [yuzu-emu/yuzu#9438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 1270

### Description of Issue

Hello, first of all, I'm quite the noob, so I asked a friend help from remote to set Yuzu properly.
The game loads fine (it takes a VERY long time tho, which was one issue I was trying to solve as well, but back on topic), the first screen is strange because it contains this screen with a long "blackened" line of text (attached image)
![image](https://user-images.githubusercontent.com/43621949/207686049-bda9cf27-7d99-42cd-b9e5-2858b8eec01b.png)

Afterwards the main screen shows just fine:
![image](https://user-images.githubusercontent.com/43621949/207686155-c5bb9e58-bcc9-4a04-a755-bead1464847f.png)

I click and the game starts with the opening, I click again to skip it and that's when the game crashes (Yuzu closes as well), every single time.

I am attaching screens of the settings I am using, but really, my friend tried all the settings he could think of, including the ones in this guide: "Link removed by moderator"
and this video: https://www.youtube.com/watch?v=caq-b0C_LDQ

Should you need more info I'm here of course.

### Expected Behavior

The prologue is supposed to play after the opening.

### Reproduction Steps

Just launching the game and skipping the opening will give me this bug.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10231159/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10231160/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
GPU/Driver: Intel(R) UHD Graphics 620  **AND**  NVDIA GeForce GTX 1050 _(but I only use this one)_
RAM: 8,00 GB (7,89 GB usable)
OS: Microsoft Windows 10 Home, Version 10.0.19044 Build 19044

**Comment by german77** [comment]
You don't need to post all screenshots of your config a single log file will contain the same info. You also uploaded the wrong log file. The correct one is called "yuzu_log.txt" it's located on "%appdata%/yuzu/log"

**Comment by Norowareshi** [comment]
Thanks and sorry, I edited the post accordingly, also having found two logs in the folder you indicated I uploaded both just to be safer (beng the "old" named one heavier)

**Comment by german77** [comment]
Now that I look at it with more detail we don't allow piracy. In the future use our guide and not some random internet one. To get your games legally. https://yuzu-emu.org/help/quickstart/
