### ISSUE TITLE
Compile flag for amount of emulated RAM

### ISSUE THREAD

**Issue by SilentStorm-1986** [yuzu-emu/yuzu#9445]
### Issue

Is there a compile flag for the amount of emulated RAM, like there is with Dolphin? If not, could this be added?

**Comment by liamwhite** [comment]
No, and no. The kernel requires 4GB of memory. There is a runtime flag to switch to the 6GB layout if you need it.

**Comment by SilentStorm-1986** [comment]
Is this theoretically possible? I know that Wii U used specific memory ranges, whereas Switch uses ASLR.

**Comment by liamwhite** [comment]
No. The kernel supports three memory sizes: 4GiB, 6GiB, and 8GiB. The amount it can use is not dynamically tunable; giving it more would do nothing, and giving it less than 4GiB would cause it to read out of bounds.
https://github.com/Atmosphere-NX/Atmosphere/blob/master/libraries/libexosphere/include/exosphere/pkg1/pkg1_boot_config.hpp#L21-L26

**Comment by SilentStorm-1986** [comment]
Can you add an 8GiB emulated RAM option?

**Comment by liamwhite** [comment]
Yes, but I'm wondering what you would find useful about it.

**Comment by SilentStorm-1986** [comment]
I'm making a mod that requires a lot of extra memory.

**Comment by liamwhite** [comment]
Until the setting is added, you can tweak it here: https://github.com/yuzu-emu/yuzu/blob/master/src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp#L31

**Comment by SilentStorm-1986** [comment]
Thank you :)

**Comment by SilentStorm-1986** [comment]
When building Yuzu for windows (using Method I), the build folder contains no VS project files.

The last line of output from CMake is:
```
Using bundled binaries at C:/Users/curti/yuzu-mainline/build/externals/ffmpeg-4.4
Configuring done
```

**Comment by SilentStorm-1986** [comment]
Do you know the absolute limit for application pool size?
