### ISSUE TITLE
Violet crash at the lighthouse after i get meraiedon

### ISSUE THREAD

**Issue by agrim500** [yuzu-emu/yuzu#9446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1259

### Description of Issue

The gane always crash after I get meraiedon and the girl ask me to follow her onto the top

### Expected Behavior

![20221204_130948](https://user-images.githubusercontent.com/83648429/207998525-cb42262d-810c-4a34-ab43-c7cb4d60891a.jpg)
It crash here and the fps turns 0band yuzu not responding appear

### Reproduction Steps

Use the yuzu in opengl using glsl cause that's what I am using

### Log File

So sorry can't provide it

### System Configuration

CPU:amd radeon
GPU/Driver:128.56
RAM:128
OS:window

**Comment by G-Spawn** [comment]
Feel free to reopen the issue when you can provide a log file.
