### ISSUE TITLE
SDL Controllers Motion Control Input Conflicts with Steam

### ISSUE THREAD

**Issue by SoRadGaming** [yuzu-emu/yuzu#9447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1271

### Description of Issue

Using an official Nintendo Switch Pro Controller when connecting a controller with Steam open in the background, the controller's motion controls won't work in Yuzu. They will start working on a controller reconnect with Steam closed.

### Expected Behavior

Motion Controls to work while steam is running in the background.

### Reproduction Steps

Open Steam
Open Yuzu
Connect the Controller via Bluetooth
Test Motion Controls of Controller

### Log File

No Log, I will continue to test and see if Steam is the problem and not Yuzu.

### System Configuration

CPU: AMD R7 5800X3D
GPU/Driver: 5700xt / 22.11.2
RAM: 32GB 3200mhz
OS: Windows 11 22H2

**Comment by SoRadGaming** [comment]
Running Steam while Yuzu is already working will make Yuzu motion controls stop working

**Comment by G-Spawn** [comment]
If you go to steam big picture you can uncheck the support for the controller settings & for the control it has when on desktop configuration (when you click into base configurations). That should stop it from touching your controller and still let you use it for input and motion for yuzu. 
![image](https://user-images.githubusercontent.com/23653025/208005316-2f38890a-f592-43d4-b4af-2bb64bfb2296.png)

The input dev for yuzu is aware of this issue though. It happens not just for steam but anything that can conflict like hidguardian or similar software that likes to manipulate controllers that are connected. Hope that helps 🙏

**Comment by SoRadGaming** [comment]
Thanks for the suggestion; I have used the option you suggested to confirm it did disable the steam profile, but it still did not fix Yuzu. I'll leave this issue open, so people know about the simple fix of closing Steam.
![image](https://user-images.githubusercontent.com/47128515/208007169-49c877d5-51c7-4525-a827-01d683c6af70.png)

**Comment by german77** [comment]
This isn't really a yuzu issue. Steams takes control on the controller over yuzu. Making controller behavior undefined.

**Comment by SoRadGaming** [comment]
> This isn't really a yuzu issue. Steams takes control on the controller over yuzu. Making controller behavior undefined.

I assume it is a Yuzu issue, as Cemu SDL Motion Controls still work with Steam Open.
