### ISSUE TITLE
[Linux][Wayland] Vulkan initialization error with new PR Wayland fixes #7410

### ISSUE THREAD

**Issue by hurricane-dorian** [yuzu-emu/yuzu#9448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline r22766.9ff891ce7

### Description of Issue

OpenGl works great on Wayland mode however vulkan fails. 
vulkan still works just fine in QT_QPA_PLATFORM=xcb mode.

### Expected Behavior

vulkan initializing correctly

### Reproduction Steps

start a game in wayland mode.

### Log File

[   0.021385] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.021390] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.080932] Frontend <Info> yuzu/main.cpp:GMainWindow:352: yuzu Version: yuzu | r22766.9ff891ce7
[   0.080933] Frontend <Info> yuzu/main.cpp:LogRuntimes:242: Qt Compile: 6.4.1 Runtime: 6.4.1
[   0.080933] Frontend <Info> yuzu/main.cpp:GMainWindow:368: Host CPU: AMD Ryzen 5 3600 6-Core Processor               | AVX2 | FMA
[   0.080945] Frontend <Info> yuzu/main.cpp:GMainWindow:370: Host CPU Cores: 6
[   0.080946] Frontend <Info> yuzu/main.cpp:GMainWindow:373: Host CPU Threads: 12
[   0.081052] Frontend <Info> yuzu/main.cpp:GMainWindow:374: Host OS: Arch Linux
[   0.081058] Frontend <Info> yuzu/main.cpp:GMainWindow:376: Host RAM: 15.54 GiB
[   0.081059] Frontend <Info> yuzu/main.cpp:GMainWindow:377: Host Swap: 20.00 GiB
[   0.208318] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   0.210732] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.4.0) applied successfully
[   0.212724] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.1.0) applied successfully
[   0.214969] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.4.0) applied successfully
[  58.966852] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the sdl2 backend
[  58.970104] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the sdl2 backend
[  70.682801] Frontend <Info> yuzu/main.cpp:BootGame:1659: yuzu starting...
[  70.686922] Config <Info> common/settings.cpp:LogSettings:40: yuzu Configuration:
[  70.686925] Config <Info> common/settings.cpp:operator():33: Controls_UseDockedMode: true
[  70.686925] Config <Info> common/settings.cpp:operator():33: System_RngSeed: 0
[  70.686926] Config <Info> common/settings.cpp:operator():33: System_CurrentUser: 0
[  70.686926] Config <Info> common/settings.cpp:operator():33: System_LanguageIndex: 1
[  70.686926] Config <Info> common/settings.cpp:operator():33: System_RegionIndex: 1
[  70.686926] Config <Info> common/settings.cpp:operator():33: System_TimeZoneIndex: 0
[  70.686927] Config <Info> common/settings.cpp:operator():33: Core_UseMultiCore: true
[  70.686928] Config <Info> common/settings.cpp:operator():33: CPU_Accuracy: 0
[  70.686928] Config <Info> common/settings.cpp:operator():33: Renderer_UseResolutionScaling: 2
[  70.686929] Config <Info> common/settings.cpp:operator():33: Renderer_ScalingFilter: 1
[  70.686929] Config <Info> common/settings.cpp:operator():33: Renderer_FSRSlider: 25
[  70.686929] Config <Info> common/settings.cpp:operator():33: Renderer_AntiAliasing: 0
[  70.686930] Config <Info> common/settings.cpp:operator():33: Renderer_UseSpeedLimit: true
[  70.686930] Config <Info> common/settings.cpp:operator():33: Renderer_SpeedLimit: 100
[  70.686930] Config <Info> common/settings.cpp:operator():33: Renderer_UseDiskShaderCache: true
[  70.686931] Config <Info> common/settings.cpp:operator():33: Renderer_GPUAccuracyLevel: 1
[  70.686931] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousGpuEmulation: true
[  70.686931] Config <Info> common/settings.cpp:operator():33: Renderer_NvdecEmulation: 2
[  70.686932] Config <Info> common/settings.cpp:operator():33: Renderer_AccelerateASTC: true
[  70.686932] Config <Info> common/settings.cpp:operator():33: Renderer_UseVsync: true
[  70.686933] Config <Info> common/settings.cpp:operator():33: Renderer_ShaderBackend: 0
[  70.686933] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousShaders: false
[  70.686933] Config <Info> common/settings.cpp:operator():33: Renderer_AnisotropicFilteringLevel: 0
[  70.686934] Config <Info> common/settings.cpp:operator():33: Audio_OutputEngine: auto
[  70.686934] Config <Info> common/settings.cpp:operator():33: Audio_OutputDevice: auto
[  70.686934] Config <Info> common/settings.cpp:operator():33: Audio_InputDevice: auto
[  70.686935] Config <Info> common/settings.cpp:operator():33: DataStorage_UseVirtualSd: true
[  70.686935] Config <Info> common/settings.cpp:operator():37: DataStorage_CacheDir: /home/dorian/.cache/yuzu
[  70.686936] Config <Info> common/settings.cpp:operator():37: DataStorage_ConfigDir: /home/dorian/.config/yuzu
[  70.686936] Config <Info> common/settings.cpp:operator():37: DataStorage_LoadDir: /home/dorian/.local/share/yuzu/load
[  70.686936] Config <Info> common/settings.cpp:operator():37: DataStorage_NANDDir: /home/dorian/.local/share/yuzu/nand
[  70.686937] Config <Info> common/settings.cpp:operator():37: DataStorage_SDMCDir: /home/dorian/.local/share/yuzu/sdmc
[  70.686937] Config <Info> common/settings.cpp:operator():33: Debugging_ProgramArgs:
[  70.686937] Config <Info> common/settings.cpp:operator():33: Debugging_GDBStub: false
[  70.686938] Config <Info> common/settings.cpp:operator():33: Input_EnableMotion: true
[  70.686938] Config <Info> common/settings.cpp:operator():33: Input_EnableVibration: true
[  70.686938] Config <Info> common/settings.cpp:operator():33: Input_EnableRawInput: false
[  70.687002] Frontend <Critical> yuzu/bootmanager.cpp:GetWindowSystemType:277: Unknown Qt platform!
[  70.767354] Render.Vulkan <Error> video_core/vulkan_common/vulkan_instance.cpp:RequiredExtensions:62: Presentation not supported on this platform
[  70.774599] Render.Vulkan <Error> video_core/vulkan_common/vulkan_surface.cpp:CreateSurface:102: Presentation not supported on this platform
[  70.775601] Render.Vulkan <Error> video_core/renderer_vulkan/renderer_vulkan.cpp:RendererVulkan:114: Vulkan initialization failed with error: VK_ERROR_INITIALIZATION_FAILED
[  70.775766] HW.GPU <Error> video_core/video_core.cpp:CreateGPU:57: Failed to initialize GPU: Vulkan initialization error VK_ERROR_INITIALIZATION_FAILED
[  70.775771] Core <Critical> core/core.cpp:Load:285: Failed to initialize system (Error 5)!

### System Configuration

Arch linux. 
Sway wm. 
radv-git
qt 6.4.1-1

**Comment by liamwhite** [comment]
What is the platform name here when attempting to start? https://github.com/yuzu-emu/yuzu/blob/master/src/yuzu/bootmanager.cpp#L265

**Comment by hurricane-dorian** [comment]
I modified line 277 to `LOG_CRITICAL(Frontend, "Unknown Qt platform! System Reported {}!", platform_name.toStdString());` 
and now I get the more usefull error message
 Frontend <Critical> yuzu/bootmanager.cpp:GetWindowSystemType:277: Unknown Qt platform! System Reported wayland-egl!

**Comment by hurricane-dorian** [comment]
Figured it out that this issue happened because Sway wm recommends you set QT_QPA_PLATFORM="wayland-egl"
Enough people should have this set to make the PR worthwhile, if for anything to prevent a bunch of other idiots from wasting your time with bug reports. 
Thank you
