### ISSUE TITLE
[Linux KDE]Xenoblade 2 random black screen crashes

### ISSUE THREAD

**Issue by Redhawk18** [yuzu-emu/yuzu#9449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1271

### Description of Issue

It seems to have to do with something with rendering new areas, because it only happens outside of menus. Entire computer black screens and reboots.

### Expected Behavior

Not to crash.

### Reproduction Steps

It seems random, but in the save i teleported to the capital of Torna and it crashed, likely wont happen again

save data:
https://cdn.discordapp.com/attachments/1050533299090624512/1053170198598930432/iraoption.sav
https://cdn.discordapp.com/attachments/1050533299090624512/1053170199026745344/irasavefile.sav

### Log File

[first time](https://github.com/yuzu-emu/yuzu/files/10242694/yuzu_log.txt.old.txt)
[second time](https://github.com/yuzu-emu/yuzu/files/10242695/yuzu_log.txt.old.txt)

### System Configuration

System:    Host: Alvis Kernel: 5.10.0-19-amd64 x86_64 bits: 64 Desktop: KDE Plasma 5.20.5 
           Distro: Debian GNU/Linux 11 (bullseye) 
Machine:   Type: Desktop Mobo: ASUSTeK model: PRIME B450M-A v: Rev X.0x serial: <superuser required> UEFI: American Megatrends 
           v: 2006 date: 11/13/2019 
CPU:       Info: 6-Core model: AMD Ryzen 5 3600X bits: 64 type: MT MCP L2 cache: 3 MiB 
           Speed: 4099 MHz min/max: 2200/5189 MHz Core speeds (MHz): 1: 4099 2: 4100 3: 4102 4: 4091 5: 4101 6: 4101 7: 4100 
           8: 4096 9: 4094 10: 4092 11: 4101 12: 4079 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] driver: amdgpu 
           v: kernel 
           Display: x11 server: X.Org 1.20.11 driver: loaded: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa resolution: 
           1: 1920x1080~60Hz 2: 1920x1080~60Hz 
           OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.40.0 5.10.0-19-amd64 LLVM 11.0.1) v: 4.6 Mesa 20.3.5 
Audio:     Device-1: Advanced Micro Devices [AMD/ATI] Navi 10 HDMI Audio driver: snd_hda_intel 
           Device-2: Advanced Micro Devices [AMD] Starship/Matisse HD Audio driver: snd_hda_intel 
           Device-3: Kingston HyperX 7.1 Audio type: USB driver: hid-generic,snd-usb-audio,usbhid 
           Sound Server: ALSA v: k5.10.0-19-amd64 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: enp8s0 state: up speed: 1000 Mbps duplex: full mac: 04:d9:f5:80:aa:ff 
           Device-2: TP-Link Archer T2U PLUS [RTL8821AU] type: USB driver: rtl8821au 
           IF: wlx5ca6e66b74e9 state: dormant mac: 4e:54:55:53:c9:4f 
           IF-ID-1: wlx5ea6e66b74e9 state: down mac: 36:01:82:c5:08:58 
Bluetooth: Device-1: ASUSTek Broadcom BCM20702A0 Bluetooth type: USB driver: btusb 
           Report: ID: hci0 state: up running pscan bt-v: 2.1 address: 5C:F3:70:8B:5D:59 
Drives:    Local Storage: total: 8.64 TiB used: 1.22 TiB (14.1%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO Plus 1TB size: 931.51 GiB 
           ID-2: /dev/sda vendor: Crucial model: CT500MX500SSD1 size: 465.76 GiB 
           ID-3: /dev/sdb vendor: Toshiba model: HDWE140 size: 3.64 TiB 
           ID-4: /dev/sdc vendor: Western Digital model: WD4005FZBX-00K5WB0 size: 3.64 TiB 
Partition: ID-1: / size: 455.95 GiB used: 36.34 GiB (8.0%) fs: ext4 dev: /dev/sda2 
           ID-2: /boot/efi size: 511 MiB used: 3.4 MiB (0.7%) fs: vfat dev: /dev/sda1 
Swap:      ID-1: swap-1 type: partition size: 976 MiB used: 0 KiB (0.0%) dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 53.1 C mobo: N/A gpu: amdgpu temp: 48.0 C 
           Fan Speeds (RPM): N/A gpu: amdgpu fan: 0 
Info:      Processes: 316 Uptime: 5m Memory: 23.48 GiB used: 2.77 GiB (11.8%) Shell: Bash inxi: 3.3.01

**Comment by liamwhite** [comment]
This seems like a kernel issue in the amdgpu driver - are you able to try with a newer kernel? Closing preemptively as not a yuzu issue, as yuzu should never be able to cause the entire system to crash.
