### ISSUE TITLE
Regression: LAN Play in Mario Kart 8 Deluxe broken

### ISSUE THREAD

**Issue by lukasfink1** [yuzu-emu/yuzu#9458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline-0-1258 to mainline-0-1272

### Description of Issue

LAN Play mode in Mario Kart 8 Deluxe (haven’t checked other games) doesn’t work anymore since mainline-0-1258 (it still worked in mainline-0-1257). When LAN Play mode is selected, the game just shows a connecting message for a second before then going back to the main menu.

### Expected Behavior

The game should show the room selection menu and wait for the player select or create a room.

### Reproduction Steps

1. Configure a working network interface under Configuration -> System -> Network.
2. Run Mario Kart 8 Deluxe.
3. Go to the main menu.
4. Press L + R + L-Stick.
5. Select LAN Play.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10249998/yuzu_log.txt)

### System Configuration

CPU: Intel Core i5-3570k
GPU/Driver: AMD Radeon R9 280X
RAM: 16 GiB
OS: Linux (Both the Arch Linux AUR package and the Flatpak on a Steam Deck are affected)

**Comment by piplup55** [comment]
Please try the [latest version](https://github.com/yuzu-emu/yuzu-mainline/releases/latest)

**Comment by german77** [comment]
I played splatoon 2 on mainline 1265 and my switch. Everything ran flawlessly once shaders where loaded. There's a chance this is a linux only issue

**Comment by lukasfink1** [comment]
> Please try the [latest version](https://github.com/yuzu-emu/yuzu-mainline/releases/latest)

I did try the latest version (mainline-0-1272) too. I assume I misunderstood the affected builds field. The build I mentioned there (mainline-0-1258) is the first one affected by this regression.

**Comment by german77** [comment]
Did you selected a network interface on the configuration of yuzu? I took a look at 1258 and it has some fixes where it rejects connection if no proper network interface is set.

**Comment by lukasfink1** [comment]
Yes, I did.

**Comment by Heath123** [comment]
Can reproduce this bug, it works on 1257 but on 1258 it kicks me back to the menu after a split second of "Connecting"

CPU: AMD Ryzen 7 5700U
GPU/Driver: Integrated Vega 8 graphics, with the normal open-source driver
RAM: 8GB
OS: Arch Linux (using the Flatpak)

**Comment by FearlessTobi** [comment]
From your description when the issue has started, this PR seems to be the culprit: https://github.com/yuzu-emu/yuzu/pull/9348/.

**Comment by Xandertron** [comment]
> I played splatoon 2 on mainline 1265 and my switch. Everything ran flawlessly once shaders where loaded. There's a chance this is a linux only issue

also happens on windows 11 with mario kart, latest build

**Comment by DJFliX** [comment]
I'm experiencing the same issue on the steam deck. Wlan interface is selected in settings, but "connecting" shows briefly before I'm kicked out.

**Comment by antiNT2** [comment]
same issue

**Comment by VanishedMC** [comment]
same issue

**Comment by TeamMythic** [comment]
still having the issue?
