### ISSUE TITLE
blackscreen when about to choose name for the main character in Rune Factory 5

### ISSUE THREAD

**Issue by Dwyns99** [yuzu-emu/yuzu#9459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1272

### Description of Issue

opening the file until the menu and early introduction to the game is fine with a few minor lag, but when i am told to input the name of the main character, the screen become blackscreen ang then stuck with 0 fps
the menu screen:
![image](https://user-images.githubusercontent.com/120775910/208242075-3419d8b2-99b2-43d2-8bb3-b7743ea522e6.png)
the name input screen:
![image](https://user-images.githubusercontent.com/120775910/208242208-6647cd62-61cf-4c1b-8123-d3a548a442f7.png)

### Expected Behavior

it is supposed to pop up the name input interface so enable me to write a name to be able to continue to play the game

### Reproduction Steps

just play until you are asked to input the main character name.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10251727/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx     2.10 GHz
GPU/Driver: AMD Radeon(TM) Vega 8 Graphics, Radeon RX 560X/ adrenalin 22.11.2
RAM: 16.0 GB 
OS: Windows 10 Home Single Language

**Comment by Dwyns99** [comment]
gpu driver: adrenalin 22.11.2

**Comment by Nerboruto** [comment]
this issues is not only with this game but general... it seems that the on-screen keyboard no longer works... 
try typing name on keyboard and hit enter, it should continue...

**Comment by Dwyns99** [comment]
nope. mine is still not unable to continue even though i have typed and push the enter button. i guess it stop running since it has 0 fps(?)

![image](https://user-images.githubusercontent.com/120775910/209830217-b56bbe39-8a35-4b40-958d-08596a0a0146.png)
