### ISSUE TITLE
Full Yuzu crash caused by an "Assertion Failed!" error

### ISSUE THREAD

**Issue by PlatinumLucario** [yuzu-emu/yuzu#9468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Most Mainline builds, as of the time of writing, all the way up to the recent Mainline 1273.

### Description of Issue

Playing certain games that utilise a certain video_core render code, result in the emulator attempting to redo the assertion, and fails on each attempt to do so. And because of this, it overwrites other instructions, causing a full-on emulator crash. This is because there is unimplemented code, just as what the debugger says.

This is a severe issue, because this consumes more and more memory. And while the OS will clear out the memory to make room for more, it will cause vertexes to be removed in the process, causing undesirable effects with 3D models. I have a good reason to believe that this is the cause of the memory leakage reported in issues #8786 and #8670.

It is most notable in Xenoblade Chronicles 3, as it uses this particular video render code that hasn't been implemented yet.

I have tested this in Vulkan, but will also be testing this in OpenGL as well and providing an update with the OpenGL log. Because I have experienced the exact same crash in OpenGL as well, so I can clearly see this as a Yuzu problem.

Not to be confused by the random freezing issue in Vulkan (which occurs in all games, and is caused by the latest Maxwell and Pascal NVIDIA drivers), as that issue is a completely separate one unrelated to this.

It doesn't matter what video render you use, doesn't matter what video card you're using, doesn't matter what driver of the video card you're using, if Yuzu gets this "Assertion Failed!" error and is unimplemented code, it will keep on retrying until it overloads the emulator, causing a full-on Yuzu crash, the log says this:
`Debug <Critical> video_core/renderer_vulkan/vk_rasterizer.cpp:operator():660: Assertion Failed!
Unimplemented code!`

And seeing that it is unimplemented code in Vulkan relating to vk_rasterizer.cpp:operator():660:, I can only take a good guess that there is unimplemented code in vk_rasterizer.cpp, I will also look into the code and see what's going on in there too.

Once I get a log of the same crash in OpenGL, I will post it too, along with its affected code.

### Expected Behavior

The emulator should have an option where you can toggle to "Continue running with unimplemented code" option for those who wish to bypass the error to the point of crashing. And with the option turned off, it should display a dialog box saying:
"This game function code has not yet been implemented into Yuzu, the game will now close."

This will help developers out a lot with finding the exact code that hasn't been implemented yet, so it can be implemented to work.

### Reproduction Steps

1. Play a game that uses this function, such as Xenoblade Chronicles 3
2. Continue playing for as long as possible in an area where this function is often used, such as Agnus Castle in Xenoblade Chronicles 3
3. After playing for a few minutes, the emulator will completely crash, and if you've switched on logging, it will show this as the last error:
`Debug <Critical> video_core/renderer_vulkan/vk_rasterizer.cpp:operator():660: Assertion Failed!
Unimplemented code!`

### Log File

**Log file link removed, due to bad directory name.**

### System Configuration

CPU: Intel® Core™ i3-6100 CPU @ 3.70GHz × 4 (2 Cores, 2 threads)
GPU: NVIDIA Corporation GM206 [GeForce GTX 950]
GPU Driver: nvidia-driver-525 (proprietary, tested)
RAM: 16.0 GiB
OS: Ubuntu 22.04.1 LTS

**Comment by goldenx86** [comment]
On a Maxwell GPU, I would try with older drivers, as it is known that any driver past the 472 series leads to issues, and any driver past the 512 series is critically broken. NVIDIA recently fixed this, but only for Pascal and newer GPUs, Maxwell was utterly forgotten.

**Comment by PlatinumLucario** [comment]
I can now confirm that the same issue persists on OpenGL, the error shows as this:
`Debug <Critical> video_core/renderer_opengl/gl_rasterizer.cpp:operator():1084: Assertion Failed!`

I will look for the code in where it's trying to read from, since I know the line number now.

Here's the log file for the OpenGL render:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10253434/yuzu_log.txt)

**Comment by PlatinumLucario** [comment]
> On a Maxwell GPU, I would try with older drivers, as it is known that any driver past the 472 series leads to issues, and any driver past the 512 series is critically broken. NVIDIA recently fixed this, but only for Pascal and newer GPUs, Maxwell was utterly forgotten.

That issue, while separate, seems to only affect the Vulkan backend, as OpenGL tends to prevent video memory from being overwritten.

The full emulator crash issue I've mentioned, affects all graphics drivers and video cards.

**Comment by PlatinumLucario** [comment]
Here's the OpenGL code in where the code breaks at (Line 1084):
```
void RasterizerOpenGL::BeginTransformFeedback(GraphicsPipeline* program, GLenum primitive_mode) {
    const auto& regs = maxwell3d->regs;
    if (regs.transform_feedback_enabled == 0) {
        return;
    }
    program->ConfigureTransformFeedback();

    UNIMPLEMENTED_IF(regs.IsShaderConfigEnabled(Maxwell::ShaderType::TessellationInit) ||
                     regs.IsShaderConfigEnabled(Maxwell::ShaderType::Tessellation) ||
                     regs.IsShaderConfigEnabled(Maxwell::ShaderType::Geometry));
    UNIMPLEMENTED_IF(primitive_mode != GL_POINTS);

    // We may have to call BeginTransformFeedbackNV here since they seem to call different
    // implementations on Nvidia's driver (the pointer is different) but we are using
    // ARB_transform_feedback3 features with NV_transform_feedback interactions and the ARB
    // extension doesn't define BeginTransformFeedback (without NV) interactions. It just works.
    glBeginTransformFeedback(GL_POINTS);
}
```

Here's the Vulkan code in where the code breaks at (Line 660):
```
void RasterizerVulkan::BeginTransformFeedback() {
    const auto& regs = maxwell3d->regs;
    if (regs.transform_feedback_enabled == 0) {
        return;
    }
    if (!device.IsExtTransformFeedbackSupported()) {
        LOG_ERROR(Render_Vulkan, "Transform feedbacks used but not supported");
        return;
    }
    UNIMPLEMENTED_IF(regs.IsShaderConfigEnabled(Maxwell::ShaderType::TessellationInit) ||
                     regs.IsShaderConfigEnabled(Maxwell::ShaderType::Tessellation));
    scheduler.Record(
        [](vk::CommandBuffer cmdbuf) { cmdbuf.BeginTransformFeedbackEXT(0, 0, nullptr, nullptr); });
}
```

Hopefully these lines of code that I've mentioned might help other devs see where the issue could be traced back to.

**Comment by PlatinumLucario** [comment]
I will also test nvidia-driver-510 as well, to see what other crashes I can reproduce with it and which line of code it can be traced back to.

**Comment by PlatinumLucario** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10253525/yuzu_log.txt)

Just tested it on nvidia-driver-510 using Vulkan, it appears to be worse on there than the newer one, and not long after playing, it immediately crashed with the same issue, as outlined before:
`Debug <Critical> video_core/renderer_vulkan/vk_rasterizer.cpp:operator():660: Assertion Failed!
Unimplemented code!`

**Comment by PlatinumLucario** [comment]
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/10254002/yuzu_log.zip)

Tested nvidia-driver-510 using OpenGL, and during my first test run of this, I couldn't produce any crashes, but I did get the exact same Assertion Failed error in the logs multiple times, not to mention it filled up all the memory all the way up until it completely filled up the Swap partition, which forced the X11 display manager to kill both Yuzu and gnome-shell processes (which reopens gnome-shell), which is done automatically if there's no room to allocate memory to in volatile memory or in the Swap partition.

Now here's a screenshot of the internal error:
![Screenshot from 2022-12-19 00-34-47](https://user-images.githubusercontent.com/1906189/208304278-0ba4da0a-15a4-4485-8b67-ed5ec1398536.png)

**Comment by PlatinumLucario** [comment]
The logs in newer builds don't seem to flood the log file with assertion failed errors anymore, but instead are corrected to their proper error instead, which seems to be within issue #9600 instead.
