### ISSUE TITLE
Stop Emulation Causes YUZU to crash or stop responding

### ISSUE THREAD

**Issue by Nicolas-Miranda** [yuzu-emu/yuzu#9472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1273

### Description of Issue

Stop Emulation Causes YUZU to crash or stop responding in Windows 10 Pro x64.

This issue started since Mainline 1273

### Expected Behavior

To stop emulation gracefully

### Reproduction Steps

- Start emulation on any game 
- Click on "Emulation" -> "Stop"
- YUZU stop responding/crashes

### Log File

No Error logs are generated as the whole app hangs up.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10254835/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10254836/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel I7 10700F
GPU/Driver: Nvidia RTX 3060 / 527.56
RAM: 64GB
OS: Windows 10 Pro x64

**Comment by Nicolas-Miranda** [comment]
Issue is probably related to this commit:

https://github.com/yuzu-emu/yuzu-mainline/commit/6bc1a477bfba9f1ac60b864ddbccbfd61faa5f4c

**Comment by liamwhite** [comment]
May be fixed by https://github.com/yuzu-emu/yuzu/pull/9463 - could you test the [artifact](https://nightly.link/yuzu-emu/yuzu/actions/runs/3722012574) from that PR? Thanks.
