### ISSUE TITLE
is it possible to compile this for 32bit?

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [yuzu-emu/yuzu#9475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

is it possible to compile this for 32bit? some research on google suggested there was 32bit version of this... altough normally they are misleading... if so... would be nice to add a github actions to let github build and generate the artifact for the emulator :)

at least the slow interpreter should work, altough i would not mind porting the dynarec translation tables, if required...
but since i would be trying to compile with mingw64 (not VS/cygwin/wsl/etc...), would be good see if the requirements still fit... i know that memory wise its fine because my 32bit windows have 8gb, so it will have up to the 2/3gb for the emulator which should be enough for most/some games...

### Why would this feature be useful?

well since there's even 32bit games on that... its the same situation as of N64, where it should be possible to have it for 32bit...

**Comment by liamwhite** [comment]
No. yuzu emulates a 64-bit platform, and requires a bare minimum of 4GiB of virtual address space, which is impossible to do in 32-bit userspace.

**Comment by goldenx86** [comment]
Good, we got this question at least once in 2022. Tradition was followed
