### ISSUE TITLE
Build 1273 introduced AppHangB1 on quitting games with F5

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#9483]
### Issue

Quitting running games (fullscreen or window, vk) with F5 causes games like The Legend of Zelda: Link's Awakening to freeze yuzu with error AppHangB1: full screen gets closed, main menu window pops-up all black and stays there forever...
Other games like Metroid Dread, The Ninja Warriors Once Again... are not affected (full screen gets closed, main menu window pops-up all black for a few secs then quit to main menu).

1272 was last non-hanging version. 1276 still affected.

LOG: https://hastebin.com/esikitades.yaml
Possible reason: https://github.com/yuzu-emu/yuzu-mainline/commit/6bc1a477bfba9f1ac60b864ddbccbfd61faa5f4c

_Gaming laptop ASUS GL703GS, i7-8750H (6+6 cores), NVidia 1070 8GB (Max-p), 32GB RAM, 1920x1080 144Hz G-Sync laptop screen, NVMe + SSD, Windows 10, NVidia 527.56 SD, XBox One BT, ROG Strix Carry mouse_

**Comment by liamwhite** [comment]
Fixed by #9476

**Comment by Hexaae** [comment]
Confirmed fixed by build [1278](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1278).

**Comment by Hexaae** [comment]
Confirmed fixed by build [1278](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1278).
