### ISSUE TITLE
Release Server binary or the pterodactyl egg

### ISSUE THREAD

**Issue by PilaScat** [yuzu-emu/yuzu#9493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Releasing the server binaries

### Why would this feature be useful?

so that I can work on an egg for pterodactyl, the popular game server manager

**Comment by G-Spawn** [comment]
This has nothing to do with Yuzu the nintendo switch emulator. Closing.
