### ISSUE TITLE
Doom and gzDoom do not load

### ISSUE THREAD

**Issue by Djbrotherson** [yuzu-emu/yuzu#9502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

UnofficialOS-20221221

### Description of Issue

When you go to load the game, it just come right back to the main menu

### Expected Behavior

Load Doom

### Reproduction Steps

Load Doom in the latest version of uOS

### Log File

None

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by piplup55** [comment]
can you fill out the system configuration and upload a log file, it can be useful to the devs

**Comment by Djbrotherson** [comment]
Apologies, I'm a novice when it comes to that.

I have the Anbernic rg353v.
How can obtain a log file for this issue? Is it located somewhere on my device?

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/reference/log-files/

**Comment by G-Spawn** [comment]
also you're not going to have a good time on that kind of hardware set for modern emulation.

**Comment by Djbrotherson** [comment]
Omg I sent this for the wrong GitHub! Please close this!

**Comment by G-Spawn** [comment]
Woops! 😛 Hope you have a great holidays hehe.
