### ISSUE TITLE
New joycon driver causing issues with pro controllers

### ISSUE THREAD

**Issue by piplup55** [yuzu-emu/yuzu#9503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3251, 3252

### Description of Issue

the new [joycon driver](https://github.com/yuzu-emu/yuzu/pull/9492) is causing issues where the pro controller doesn't show in the controller menu
![image](https://user-images.githubusercontent.com/100526773/209468183-a3e077a6-bed5-48e1-bc85-d9ab07d43282.png)
disabling the driver seems to make the pro controller show up

### Expected Behavior

it should show and be selectable in the controller dropdown

### Reproduction Steps

enable the new joycon driver and connect a pro controller with usb, bluetooth is untested

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10299961/yuzu_log.167.txt)

### System Configuration

CPU: Ryzen 7 3700X
GPU/Driver: RX 6600 XT, Mesa 22.3.1, vulkan-radeon 22.3.1
RAM: 64GB
OS: Arch Linux

**Comment by benjamimgois** [comment]
it also happens to my original joycons on Arch Linux

**Comment by bernharl** [comment]
Could this issue perhaps be because of the udev-rules in the joycond-git package? I'll test later today

**Comment by andsouto** [comment]
> Could this issue perhaps be because of the udev-rules in the joycond-git package? I'll test later today

I have just test it without success. Uninstall joycond, restart, start yuzu: no devices found. Tried both using USB and bluetooth with a pro controller. After disabling new driver it is recognized again.

**Comment by andsouto** [comment]
I think I found the problem. At least in my case, permission for hidraw was missing. I fixed it adding this udev rule in `# /etc/udev/rules.d/99-hidraw-permission.rules`:

```
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="plugdev"
```

and adding my user to plugdev group.

After that pro controller is recognized using new joycond driver and cemuhook is not needed anymore.

**Comment by bernharl** [comment]
> I think I found the problem. At least in my case, permission for hidraw was missing. I fixed it adding this udev rule in `# /etc/udev/rules.d/99-hidraw-permission.rules`:
> 
> ```
> KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="plugdev"
> ```
> 
> and adding my user to plugdev group.
> 
> After that pro controller is recognized using new joycond driver and cemuhook is not needed anymore.

This works for me as well, but it also gives Steam access to hidraw. This makes Joycond's implementation of a virtual controller to avoid conflicts with Steam not work anymore. Is there a smarter way to create a udev rule that doesn't break this?

**Comment by liamwhite** [comment]
Fixed by update to joycon driver to disable pro controller support.
