### ISSUE TITLE
Non-async GPU emulation causes being stuck in "Launching..." screen

### ISSUE THREAD

**Issue by MonsterDruide1** [yuzu-emu/yuzu#9509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1284

### Description of Issue

When starting a game (tested with Super Mario Odyssey) with disabled "Use asynchronous GPU emulation", the process gets stuck in "Launching..." and the game never starts.

Afterwards, when trying to close Yuzu or stop the emulation, Yuzu crashes completely.

### Expected Behavior

The game should also boot without using the asynchronous GPU option.

### Reproduction Steps

Go to the configuration -> Graphics and disable "Use asynchronous GPU emulation", then try to start a game (for example Super Mario Odyssey)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10304130/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz | AVX2 | FMA
GPU/Driver: Nvidia GeForce GTX 1060 6 GB, Version 527.56
RAM: 32 GB
OS: Windows 10 Version 22H2 (Build 19045.2364)

**Comment by MonsterDruide1** [comment]
Further comments:
- Happens on both Vulkan and OpenGL
- Unaffected by "Multicore CPU Emulation"

**Comment by liamwhite** [comment]
I believe sync GPU mode has been broken since #8467 - the plan before its release was to remove it entirely.

**Comment by FernandoS27** [comment]
sync GPU mode has been deprecated and will be fully removed in the near future.

**Comment by MonsterDruide1** [comment]
That's sad, it was still kind of useful to me, fiddling around with some timing things... Well, now I have to properly implement those instead of accumulating a bunch of dirty fixes.

Thanks for the response!
