### ISSUE TITLE
[Pokemon Sword/Pokemon Shield] Glitchy loading of certain objects under Vulkan on the Steam Deck

### ISSUE THREAD

**Issue by XeronFeferon** [yuzu-emu/yuzu#9511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1285

### Description of Issue

In Pokemon Sword and Shield during the opening part of the game there is a certain Pokemon mat that doesn't render properly and sometimes glitches in and out of existence. This issue only happens under Vulkan as when using OpenGL no such glitch occurs.
![PXL_20221228_045308553_1](https://user-images.githubusercontent.com/92057030/209759994-71d29d61-d83d-4f1e-9043-1167bebb3864.jpg)

### Expected Behavior

The playing mat should render properly 
![Screenshot_20221228_060129](https://user-images.githubusercontent.com/92057030/209760166-d1dc4df0-7d0b-46fd-b3a9-0b6ad5eed227.png)

### Reproduction Steps

Following (should be) a save file which loads at the point where the issue occurs
[main.zip](https://github.com/yuzu-emu/yuzu/files/10312260/main.zip)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10312286/yuzu_log.txt)

### System Configuration

Device: Steam Deck
GPU: AMD Zen 2
RAM: 16 GB LPDDR5
OS: Steam OS 3.4.2

**Comment by goldenx86** [comment]
This is a limitation of AMD GPUs. If the Vulkan drivers don't support 24-bit FP, the alternative, 32-bit, won't be as accurate.
