### ISSUE TITLE
Dragon Quest Treasures 

### ISSUE THREAD

**Issue by username227** [yuzu-emu/yuzu#9512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline & Flatpak, all recent builds - 1286

### Description of Issue

DQ Treasures will boot into the loading screen, with two people moving on the bottom right. But it always crashes before hitting the title screen. This happens regardless of how my graphics settings are configured.

### Expected Behavior

It should show the title screen instead of crashing.

### Reproduction Steps

Simply start up the game in Yuzu, and it'll crash before hitting the title screen.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10314727/yuzu_log.txt)

### System Configuration

neofetch
                   -`                    
                  .o+`                   -------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: HP Pavilion Gaming Laptop 15z-ec 
               `+oooooo:                 Kernel: 6.1.1-arch1-1 
               -+oooooo+:                Uptime: 15 hours, 6 mins 
             `/:-:++oooo+:               Packages: 1467 (pacman), 19 (flatpak) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: Cinnamon 5.6.5 
         ./ooosssso++osssssso+`          WM: Mutter (Muffin) 
        .oossssso-````/ossssss+`         WM Theme: Linux_Mint (Adwaita) 
       -osssssso.      :ssssssso.        Theme: Mint-Y-Aqua [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Adwaita41 [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: gnome-terminal 
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 5 5600H with Radeon Gra 
  `+sso+:-`                 `.-/+oso:    GPU: AMD ATI Radeon Vega Series / Rade 
 `++:.                           `-/+/   GPU: NVIDIA 01:00.0 NVIDIA Corporation 
 .`                                 `/   Memory: 3155MiB / 15338MiB

**Comment by liamwhite** [comment]
```
[  32.440543] Debug <Critical> common/host_memory.cpp:operator():414: Assertion Failed!
mmap failed: Cannot allocate memory
[  32.441331] Debug <Critical> common/host_memory.cpp:operator():435: Assertion Failed!
mprotect failed: Cannot allocate memory
[  32.441617] Debug <Critical> common/host_memory.cpp:operator():435: Assertion Failed!
```
Do you have overcommit disabled?

**Comment by username227** [comment]
> ```
> [  32.440543] Debug <Critical> common/host_memory.cpp:operator():414: Assertion Failed!
> mmap failed: Cannot allocate memory
> [  32.441331] Debug <Critical> common/host_memory.cpp:operator():435: Assertion Failed!
> mprotect failed: Cannot allocate memory
> [  32.441617] Debug <Critical> common/host_memory.cpp:operator():435: Assertion Failed!
> ```
> 
> Do you have overcommit disabled?

I don't know. Where is that setting located?

**Comment by username227** [comment]
OK I figured out this issue. there was a problem with VM. I followed the instructions [here](https://github.com/yuzu-emu/yuzu/issues/7397) and that solved the issue. Therefore, closing. Thanks.
