### ISSUE TITLE
Yuzu on Jetson AGX Xavier

### ISSUE THREAD

**Issue by Tony763** [yuzu-emu/yuzu#9513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

HEAD-67c0d714c

### Description of Issue

Can't say this is an actual bug, but no other template suit this. I did like to share steps needed to compile and run Yuzu on Nvidia Jetson devices, as they are not so straightforward. I managed to make it running on AGX Xavier with JetPack 5.0.2, rootfs on 2TB NVME disk and MAXN power profile selected, but it's too slow. Animal Crossing gives only 5 FPS and loading also take some time, Yet HW do not seem to be overloaded. As controller, I use PS4 compatible Bluetooth gamepad.

Hopefully these steps will help other users trying to run Yuzu on Jetson. Also, If there is any debug output I can provide to improve speed, say so :slightly_smiling_face: .

![Screenshot from 2022-12-28 16-37-54](https://user-images.githubusercontent.com/5598750/209841488-51b0245a-19b9-480e-9417-240fe78529e0.png)

Some though on steps:

Vulkan SDK 1.3.238 is not yet available for download (Libraries need to be compiled), so I had to use older commit before switching to it and force newer dynarmic commit selection.

FFMPEG builded into JetPack does not contain necessary Vulcan support, so bundled one must be compiled/used. 

GCC 11 in Focal repository contain only version 11.0 which, when used, will fail QT compilation, so 11.3 is compiled from source.

Next step for now is compile QtWebengine, and it's Yuzu support.

### Expected Behavior

Having compilation steps in doc, would be fine.

### Prerequires
```
mkdir ~/sources

sudo sed -i "s/^# deb/deb/g" /etc/apt/sources.list.d/nvidia-l4t-apt-source.list
sudo sed -i "s/^# deb/deb/g" /etc/apt/sources.list

sudo apt update

# vcpkg (Bootstrapping vcpkg before install - failed)
sudo apt-get install curl

sudo apt-get build-dep qtbase5-dev

sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev llvm libclang-dev libclang1 flex bison gperf libicu-dev libxslt-dev ruby libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev libxtst-dev libxss-dev libdbus-1-dev libevent-dev libfontconfig1-dev libcap-dev libpulse-dev libudev-dev libpci-dev libnss3-dev libasound2-dev libegl1-mesa-dev gperf bison libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev libgstreamer-plugins-bad1.0-dev autoconf cmake git glslang-tools libasound2 libboost-context-dev libglu1-mesa-dev libhidapi-dev libpulse-dev libtool libudev-dev libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 libxext-dev libxkbcommon-x11-0 mesa-common-dev nasm ninja-build libmbedtls-dev libfmt-dev liblz4-dev nlohmann-json3-dev libzstd-dev libvdpau-dev libva-dev libx11-dev libspeexdsp-dev doxygen libgbm-dev libenet-dev libinih-dev libopus-dev libllvm11 libgtk-3-dev ccache libb2-dev libxkbfile-dev python3-html5lib clang-format
```

### cmake 3.22+
```
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
sudo apt update
sudo apt install kitware-archive-keyring

sudo apt install --upgrade cmake
```

### gcc 11.3
```
cd ~/sources
mkdir gcc-11.3 
cd gcc-11.3
wget https://bigsearcher.com/mirrors/gcc/releases/gcc-11.3.0/gcc-11.3.0.tar.xz

tar -xvf gcc-11.3.0.tar.xz

sudo apt install build-essential libncurses-dev bison flex libssl-dev libelf-dev

cd gcc-11.3.0/
./contrib/download_prerequisites

find /usr/ -name crti*   # /usr/lib/aarch64-linux-gnu/crti.o

export LIBRARY_PATH=/usr/lib/aarch64-linux-gnu
export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu

mkdir build
cd build
../configure --prefix=/usr/local --program-suffix=-11.3
make -j $(nproc)

sudo make install

sudo update-alternatives --remove-all gcc 
sudo update-alternatives --remove-all g++

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/local/bin/gcc-11.3 20

sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/local/bin/g++-11.3 20

sudo update-alternatives --config gcc
sudo update-alternatives --config g++

nano ~/.bashrc
### Place at end of file and also run in cmd
# GCC 11.3
export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
###
sudo ldconfig
```

### ffnvcodec
```
cd ~/sources
git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
cd nv-codec-headers

make
sudo make install
```

### Node.js 16
To be used with QtWebengine and `-DYUZU_USE_QT_WEB_ENGINE=ON` , not yet tested
```
cd ~/sources

sudo apt update
sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
curl -L https://deb.nodesource.com/setup_16.x | tee node_setup.sh
chmod +x node_setup.sh

sudo ./node_setup.sh
sudo apt -y install nodejs

sudo npm i npm -g
```

### Vulkan
Fixes compilation error: VK_API_VERSION_1_3  (will need to be version 238 when sdk is out to use latest commits)
```
cd ~/sources
mkdir vulkan
cd vulkan

wget https://sdk.lunarg.com/sdk/download/1.3.236.0/linux/vulkansdk-linux-x86_64-1.3.236.0.tar.gz
tar -xvf vulkansdk-linux-x86_64-1.3.236.0.tar.gz
cd 1.3.236.0/

source setup-env.sh

nano ./vulkansdk     # remove g++multilib from vulkansdk script

./vulkansdk -j 8 all

nano ~/.bashrc
### Place at end and also run in cmd
# Vulkan
export VULKAN_SDK_VER="1.3.236.0"
export VULKAN_SDK_ARCH="aarch64"
export VULKAN_SDK_PATH="/home/tony/sources/vulkan"
export VULKAN_SDK="${VULKAN_SDK_PATH}/${VULKAN_SDK_VER}/${VULKAN_SDK_ARCH}"
export PATH="${VULKAN_SDK}/bin":${PATH}
export LD_LIBRARY_PATH="${VULKAN_SDK}/lib":${LD_LIBRARY_PATH}
export VK_LAYER_PATH="${VULKAN_SDK}/etc/vulkan/explicit_layer.d"
###

sudo ldconfig

# Check if version is right
vulkaninfo | grep "Version"
```

### Qt 6.3.1
```
cd ~/sources
mkdir qt6
cd qt6

wget https://download.qt.io/official_releases/qt/6.3/6.3.1/single/qt-everywhere-src-6.3.1.tar.xz

tar -xvf qt-everywhere-src-6.3.1.tar.xz
cd qt-everywhere-src-6.3.1

nano qtwebengine/configure.cmake
### Fixes "Unknown CMake command check_for_ulimit" when cmake 3.25 is used (https://forum.qt.io/topic/140651/need-help-statically-building-qt-for-ubuntu/7)
if(QT_CONFIGURE_RUNNING)
    function(check_for_ulimit)
    endfunction()
    ...
###

mkdir build
cd build
../configure -opensource -confirm-license -prefix /home/tony/sources/qt6/qt6builded -xcb -xcb-xlib -qpa xcb -xkbcommon -gtk -icu -vulkan -skip qtwebengine
cmake --build . --parallel
cmake --install .
```

### Yuzu
```
cd ~/sources
git clone --recursive https://github.com/yuzu-emu/yuzu.git

cd yuzu

git checkout 67c0d714c5b6e93ddb00d0807147b5673c011ac6

# Use dynarmic with implemented necessary functions 
nano .git/modules/dynarmic/HEAD
### 
1fa1935d7c015767cf211c441578b25e3517c43f
###

git submodule update --init --recursive

mkdir build
cd build

VCPKG_FORCE_SYSTEM_BINARIES=ON cmake .. -GNinja -DYUZU_USE_BUNDLED_VCPKG=OFF -DYUZU_TESTS=OFF -DCMAKE_C_COMPILER=gcc-11.3 -DCMAKE_CXX_COMPILER=g++-11.3 -DYUZU_USE_QT_WEB_ENGINE=OFF -DYUZU_USE_BUNDLED_QT=0 -DQt6_LOCATION=/home/tony/sources/qt6/qt6builded -DYUZU_USE_BUNDLED_FFMPEG=ON -DENABLE_QT6=ON 

ninja -j 8
```

#### Edits:
28.12.2022 - Initial steps version
29.12.2022 - Reorder Steps, do Vulkan part before QT6

### Log File

TBD, for now, console do not show any errors.
[configuration.txt](https://github.com/yuzu-emu/yuzu/files/10318208/configuration.txt)

### System Configuration

CPU:  8-core NVIDIA Carmel Armv8.2 64-bit CPU 8MB L2 + 4MB L3
GPU/Driver: NVIDIA Volta architecture with 512 NVIDIA CUDA cores and 64 Tensor cores
RAM: 32GB 256-bit LPDDR4x 136.5GB/s
OS: JetPack 5.0.2, Ubunu 20.04 Focal

**Comment by raul-parada** [comment]
Should it work on a Jetson Nano development kit?

**Comment by Tony763** [comment]
It could, but sadly, Nvidia ditched SW improvements on Nano/TX1/TX2 so the latest available version of Jetpack for them is and will be only 4.6. And it's based on Ubuntu 18.04.  [See](https://forums.developer.nvidia.com/t/jetpack-5-0-2/223564).

So You can try it, but bear in mind, that more system packages can be obsolete and will need manual update or build from source.

**Comment by Nerboruto** [comment]
> Should it work on a Jetson Nano development kit?

if you mean the normal version with 4gb ram, it's too weak hardware... cpu / ram / gpu.

**Comment by raul-parada** [comment]
@Tony763 in Qt part I get the attached error. 
[logqt.txt](https://github.com/yuzu-emu/yuzu/files/10319709/logqt.txt)
Any clue? Thanks

**Comment by Tony763** [comment]
Hi @raul-parada, try to firstly do Vulkan part. I will reorder them.

**Comment by liamwhite** [comment]
Glad to see this is working for you. There are some dynarmic changes we will be pulling over soon that should approximately double the framerate.

**Comment by dtran11** [comment]
would these steps work for Jetson Orin Nano?

**Comment by Tony763** [comment]
It should, as it's same platform, but I cannot tel if speed of Nano will be enough.  I was unable to compile Yuzu from last master due to some compile errors so I cannot test last changes made. I will try it again, when I have some time to spare.

**Comment by dtran11** [comment]
> It should, as it's same platform, but I cannot tel if speed of Nano will be enough. I was unable to compile Yuzu from last master due to some compile errors so I cannot test last changes made. I will try it again, when I have some time to spare.

I was able to compile for Jetson Orin Nano: https://youtu.be/VJx6yaq47yE?si=zb1PHkOzoVhY2IaI
