### ISSUE TITLE
[Linux] Yuzu doesn't read games located on network drives 

### ISSUE THREAD

**Issue by shakeyourbunny** [yuzu-emu/yuzu#9519]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Affected Build(s)

Build 1286 / Flatpak

### Description of Issue

( This is issue seems to be resolved for Windows, but **not** for Linux (with XDG_Portal), https://github.com/yuzu-emu/yuzu/issues/2805 )

I have my ROMs on a SMB/CIFS share and if I try to drop via Drag'n'Drop a NSP directly via Dolphin / KDE, yuzu complains that the "ROM format is not supported". Copying the ROM to the local disk DOES open the NSP without a hitch.

If you try to execute directly yuzu via CLI 
`` 
flatpak run org.yuzu_emu.yuzu "/smbshare/path/to/rom/a-homebrew-gamen.nsp"
`` 
yields the same result.

![Screenshot_20221229_125804](https://user-images.githubusercontent.com/5352403/209948010-1648708d-518e-404a-9cb2-6f19db90c5e1.png)

Opening the same ROM with File / Open entering the SAME location (using XDG_Portal from KDE) DOES work.

Also, there is some issue with the XDG_Portal / kio-smb (libsmbountfs or something) which auto-translates the mounted smb share wrong in yuzu (running in a flatpak).

The aforementioned path "/smbshare/path/to/rom/" translate in yuzu to "/run/user/doc/2340df/Switch" which will get invalid after remounting or rebooting the computer. ROMs listed there are accessible, though.

![Screenshot_20221229_130652](https://user-images.githubusercontent.com/5352403/209948943-a9c9413f-a79d-4b5f-947b-8fb93f347a73.png)

### Expected Behavior

The opened ROM will be loaded and run by the emulator.

Also, the game directory path in yuzu should be the smb path, not something in /run/user/1000/....

### Reproduction Steps

- Start KDE.
- Mount a SMB share as superuser (mount -t cifs /fileserver/share/ /smbshare-mountpoint)
- Open Dolphin.
- Start yuzu.
- Drop a file from within the smb mount onto yuzu or execute "flatpak run org.yuzu_emu.yuzu "/smbshare/switch/homebrew.nsp" in the shell.

Get the error message.

Also, regarding the game directory within yuzu:
- start yuzu
- double click on the plus sign
- choose a folder within the smb share.
- press OK.

Note that this is the flatpak version of yuzu and granting access rights to the said drive did not yield the solution.

### Log File

````
[   0.031776] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.031786] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.144550] Frontend <Info> yuzu/main.cpp:GMainWindow:354: yuzu Version: yuzu 1286
[   0.144553] Frontend <Info> yuzu/main.cpp:LogRuntimes:244: Qt Compile: 5.15.7 Runtime: 5.15.7
[   0.144555] Frontend <Info> yuzu/main.cpp:GMainWindow:370: Host CPU: AMD Ryzen 5 3600 6-Core Processor               | AVX2 | FMA
[   0.144571] Frontend <Info> yuzu/main.cpp:GMainWindow:372: Host CPU Cores: 6
[   0.144572] Frontend <Info> yuzu/main.cpp:GMainWindow:375: Host CPU Threads: 12
[   0.144584] Frontend <Info> yuzu/main.cpp:GMainWindow:376: Host OS: KDE Flatpak runtime
[   0.144588] Frontend <Info> yuzu/main.cpp:GMainWindow:377: Host RAM: 31.27 GiB
[   0.144589] Frontend <Info> yuzu/main.cpp:GMainWindow:379: Host Swap: 31.27 GiB
[   0.246300] Frontend <Warning> yuzu/main.cpp:SetupPrepareForSleep:1412: QDBusConnection system bus is not connected
[   0.246509] Frontend <Info> yuzu/main.cpp:BootGame:1662: yuzu starting...
[   0.247803] Common.Filesystem <Error> common/fs/file.cpp:Open:261: Failed to open the file at path=/smbshare/switch/homebrewgame.nsp, ec_message=No such file or directory
[   0.247807] Common.Filesystem <Error> common/fs/fs.cpp:FileOpen:149: Failed to open the file at path=/smbshare/switch/homebrewgame.nsp with mode=1, type=0, flag=1
[   0.247809] Config <Info> common/settings.cpp:LogSettings:40: yuzu Configuration:
[   0.247809] Config <Info> common/settings.cpp:operator():33: Controls_UseDockedMode: true
[   0.247810] Config <Info> common/settings.cpp:operator():33: System_RngSeed: 0
[   0.247810] Config <Info> common/settings.cpp:operator():33: System_DeviceName: Yuzu
[   0.247811] Config <Info> common/settings.cpp:operator():33: System_CurrentUser: 1
[   0.247812] Config <Info> common/settings.cpp:operator():33: System_LanguageIndex: 1
[   0.247812] Config <Info> common/settings.cpp:operator():33: System_RegionIndex: 1
[   0.247813] Config <Info> common/settings.cpp:operator():33: System_TimeZoneIndex: 0
[   0.247813] Config <Info> common/settings.cpp:operator():33: Core_UseMultiCore: true
[   0.247816] Config <Info> common/settings.cpp:operator():33: CPU_Accuracy: 0
[   0.247817] Config <Info> common/settings.cpp:operator():33: Renderer_UseResolutionScaling: 2
[   0.247817] Config <Info> common/settings.cpp:operator():33: Renderer_ScalingFilter: 5
[   0.247818] Config <Info> common/settings.cpp:operator():33: Renderer_FSRSlider: 25
[   0.247819] Config <Info> common/settings.cpp:operator():33: Renderer_AntiAliasing: 0
[   0.247819] Config <Info> common/settings.cpp:operator():33: Renderer_UseSpeedLimit: true
[   0.247820] Config <Info> common/settings.cpp:operator():33: Renderer_SpeedLimit: 100
[   0.247820] Config <Info> common/settings.cpp:operator():33: Renderer_UseDiskShaderCache: true
[   0.247821] Config <Info> common/settings.cpp:operator():33: Renderer_GPUAccuracyLevel: 1
[   0.247821] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousGpuEmulation: true
[   0.247822] Config <Info> common/settings.cpp:operator():33: Renderer_NvdecEmulation: 2
[   0.247822] Config <Info> common/settings.cpp:operator():33: Renderer_AccelerateASTC: true
[   0.247823] Config <Info> common/settings.cpp:operator():33: Renderer_UseVsync: true
[   0.247823] Config <Info> common/settings.cpp:operator():33: Renderer_ShaderBackend: 0
[   0.247824] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousShaders: false
[   0.247824] Config <Info> common/settings.cpp:operator():33: Renderer_AnisotropicFilteringLevel: 0
[   0.247824] Config <Info> common/settings.cpp:operator():33: Audio_OutputEngine: auto
[   0.247825] Config <Info> common/settings.cpp:operator():33: Audio_OutputDevice: auto
[   0.247825] Config <Info> common/settings.cpp:operator():33: Audio_InputDevice: auto
[   0.247826] Config <Info> common/settings.cpp:operator():33: DataStorage_UseVirtualSd: true
[   0.247826] Config <Info> common/settings.cpp:operator():37: DataStorage_CacheDir: /home/myuser/.var/app/org.yuzu_emu.yuzu/cache/yuzu
[   0.247827] Config <Info> common/settings.cpp:operator():37: DataStorage_ConfigDir: /home/myuser/.var/app/org.yuzu_emu.yuzu/config/yuzu
[   0.247827] Config <Info> common/settings.cpp:operator():37: DataStorage_LoadDir: /home/myuser/.var/app/org.yuzu_emu.yuzu/data/yuzu/load
[   0.247828] Config <Info> common/settings.cpp:operator():37: DataStorage_NANDDir: /home/myuser/.var/app/org.yuzu_emu.yuzu/data/yuzu/nand
[   0.247828] Config <Info> common/settings.cpp:operator():37: DataStorage_SDMCDir: /home/myuser/.var/app/org.yuzu_emu.yuzu/data/yuzu/sdmc
[   0.247829] Config <Info> common/settings.cpp:operator():33: Debugging_ProgramArgs: 
[   0.247829] Config <Info> common/settings.cpp:operator():33: Debugging_GDBStub: false
[   0.247829] Config <Info> common/settings.cpp:operator():33: Input_EnableMotion: true
[   0.247830] Config <Info> common/settings.cpp:operator():33: Input_EnableVibration: true
[   0.247830] Config <Info> common/settings.cpp:operator():33: Input_EnableRawInput: false
[   0.253323] Common.Filesystem <Error> common/fs/file.cpp:Open:261: Failed to open the file at path=/smbshare/switch/homebrewgame.nsp, ec_message=No such file or directory
[   0.253327] Common.Filesystem <Error> common/fs/fs.cpp:FileOpen:149: Failed to open the file at path=/smbshare/switch/homebrewgame.nsp with mode=1, type=0, flag=1
[   0.253329] Core <Critical> core/core.cpp:Load:272: Failed to obtain loader for /smbshare/switch/homebrewgame.nsp!
[   0.253332] Frontend <Critical> yuzu/main.cpp:LoadROM:1598: Failed to obtain loader for /smbshare/switch/homebrewgame.nsp!
[ 313.468967] Loader <Warning> core/loader/loader.cpp:GetLoader:256: File v-portal_v196608.nsp has a different type (unknown) than its extension.
[ 313.489766] Loader <Warning> core/loader/loader.cpp:GetLoader:256: File v-portal_v196608.nsp has a different type (unknown) than its extension.

````

### System Configuration

CPU: AMD Ryzen 5 3600 
GPU/Driver: AMD Radeon RX 6700 XT
RAM: 32 GiB
OS: opensuse:tumbleweed / 20221228; Kernel 6.1.1

KDE 5.26.4 / X11
KDE Frameworks 5.101.0
Qt 5.15.7

Flatpak 1.14

Name                                             Application ID                                 Version               Branch                 Installation
Freedesktop Platform                             org.freedesktop.Platform                       22.08.4               22.08                  user
Mesa                                             org.freedesktop.Platform.GL.default            21.3.9                21.08                  user
Mesa                                             org.freedesktop.Platform.GL.default            22.2.4                22.08                  user
Mesa (Extra)                                     org.freedesktop.Platform.GL.default            22.2.4                22.08-extra            user
openh264                                         org.freedesktop.Platform.openh264              2.1.0                 2.0                    user
openh264                                         org.freedesktop.Platform.openh264              2.1.0                 2.2.0                  user
Freedesktop SDK                                  org.freedesktop.Sdk                            21.08.17.1            21.08                  user
GNOME Application Platform version 43            org.gnome.Platform                                                   43                     user
Breeze GTK theme                                 org.gtk.Gtk3theme.Breeze                       5.26.4                3.22                   user
KDE Application Platform                         org.kde.Platform                                                     5.15-22.08             user

**Comment by shakeyourbunny** [comment]
Maybe this has something to do with the flatpak runtime that the loader cannot find the rom file, but within Dolphin / Desktop and shell I DO can access said rom files (with cd / ls etc ).

**Comment by shakeyourbunny** [comment]
Or maybe there is something with the AppArmor configuration?

**Comment by davegallant** [comment]
Dragging a single file onto Yuzu from SMB is for me on NixOS.

However, adding a game directory does not work.

![image](https://user-images.githubusercontent.com/4519234/211181318-3a458349-6ebd-45d4-8d77-8ff6b65d741f.png)

It would be nice if Yuzu would be able to list all games in the directory and thumbnails from a SMB share.

**Comment by davegallant** [comment]
Dragging a single file onto Yuzu from SMB is working for me on NixOS.

However, adding a game directory does not work.

![image](https://user-images.githubusercontent.com/4519234/211181318-3a458349-6ebd-45d4-8d77-8ff6b65d741f.png)

It would be nice if Yuzu would be able to list all games in the directory and thumbnails from a SMB share.

**Comment by davegallant** [comment]
I can reproduce this using smb on NixOS, but works fine using nfs.

**Comment by G-Spawn** [comment]
Existing issue has been made already <https://github.com/yuzu-emu/yuzu/issues/9283>

**Comment by famellad** [comment]
> Existing issue has been made already #9283

This doesn't seem like the same bug, it is definitely a permission issue with Flatpak at least, using Flatseal to allow access to all host files (bad idea) allows it to load and work without problems.
