### ISSUE TITLE
Some games stuck on launching since EA 3260 update

### ISSUE THREAD

**Issue by Phoenomenal** [yuzu-emu/yuzu#9520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3260

### Description of Issue

Since yuzu Early Access updated 3260  cant launch some games (Xenoblade Chronicles  DE, Astral Chain, Pokemon sword) .  Just stuck on launching screen.   Other game i  tried  working fine like  Xenoblade 2 and Xenoblade 3 and Splatoon 2

 On mainline 1288 all those games launching fine.    And just yesterday Xenoblade Chronicles DE was running fine on EA3259

### Expected Behavior

Expected Behavior is that those game will go past launching screen

### Reproduction Steps

To reproduce the issue you should launch on EA 3260 one of these games which i can confirm wont go past launch screen : Xenoblade Chronicles  DE,  Astral Chain,  Pokemon sword/shield

### Log File

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/10321849/yuzu_log.zip)

### System Configuration

CPU: Intel Core I9 9900K
GPU/Driver: Geforce 2080ti driver 527.56
RAM: 32gb
OS: Win 11

![Screenshot_1](https://user-images.githubusercontent.com/68902338/210005045-2130f679-94d6-4c5a-a160-7b24379d7659.png)

**Comment by gidoly** [comment]
Closes due to log containing pirated content
