### ISSUE TITLE
Finding a Base Resolution of the ROM

### ISSUE THREAD

**Issue by P0W3** [yuzu-emu/yuzu#9522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I am trying to find the base resolution of the ROM.

### Why would this feature be useful?

Because, it helps to specify the base resolution of the ROM.

**Comment by FearlessTobi** [comment]
I'm not sure I understand what you are requesting here. 
The switch is 720p in Undocked mode and 1080p in Docked.

**Comment by gidoly** [comment]
Not quite various game not stucks on simply 720p and 1080p. Infact most switch games are 900p

**Comment by liamwhite** [comment]
Closing as support request - games can render in many possible resolutions, and the resolution chosen is specific to the game and not visible to yuzu.
