### ISSUE TITLE
Yuzu crash when switch window mode to fullscreen

### ISSUE THREAD

**Issue by huzki1998** [yuzu-emu/yuzu#9523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3262

### Description of Issue

After I installed Hwinfo and Rivatuner Statistics Server
Whenever I switch yuzu from window mode to fullscreen or fullscreen to windows
Yuzu will always crashed and stuck, even if I closed Hwinfo and RTSS

### Expected Behavior

When I try to Switch window mode to  Full Screen mod,  the Yuzu crash.

### Reproduction Steps

It runs good if not switch windows mode or fullScreen mode

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10322857/yuzu_log.txt)

### System Configuration

CPU:AMD Ryzen 7 5800U with Radeon Graphics
GPU/Driver: AMD Radeon Graphics
OS:Windows 11 Version 21H2 (Build 22000.593)

Version：
Rivatuner Statistics Server V7.3.3
Hwinfo V7.32

**Comment by huzki1998** [comment]
> please try using exclusive fullscreen mode versus borderless in the config of yuzu under graphics iirc

May I ask where is the **exclusive fullscreen mode**

**Comment by huzki1998** [comment]
When I using switch borderless to the exclusive fullscreen, this old problem has been solved , thanks 
But there will be a new problem,  yuzu will crash when I try to turn back to desktop on the exclusive fullscreen mode

**Comment by G-Spawn** [comment]
mnmn fun. would you be willing to see if deleting %appdata%\yuzu\config\qt-config.ini then reopening the emulator helps any? you'll have to remap your game directory after but it can help rule out oddity with config.

**Comment by huzki1998** [comment]
> 

OMG, thanks. 

The problem has been perfected solved when I deleted qt-config.in.  Thank you so much

**Comment by G-Spawn** [comment]
No problem glad to hear it! ❤️ I will close issue for now. Should it happen again in future please feel free to reopen.
