### ISSUE TITLE
Linux: Crash on assertion fail

### ISSUE THREAD

**Issue by gandalth** [yuzu-emu/yuzu#9544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 50d4380

### Description of Issue

Yuzu crashes after game intro with an assertion fail. This happens on all games I have available, e.g. Bubble Bobble 4 Friends.
This behavior is showing up since updating to Mesa 22.3.1.

Graphics Setting: OpenGL GLSL
Hardware: Mesa Intel(R) HD Graphics 5500 (BDW GT2)

Error Message:
yuzu: ../src/intel/isl/isl_surface_state.c:547: isl_gfx8_surf_fill_state_s: Assertion `info->y_offset_sa % y_div == 0' failed.

### Expected Behavior

No crash / assertion fulfilled.

### Reproduction Steps

Start a game, pass the intro screen, and the crash occurs.

### Log File

[   0.088765] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.088790] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.223205] Frontend <Info> yuzu/main.cpp:GMainWindow:354: yuzu Version: yuzu Development Build | master-09c9be370
[   0.223209] Frontend <Info> yuzu/main.cpp:LogRuntimes:244: Qt Compile: 5.15.7 Runtime: 5.15.7
[   0.223211] Frontend <Info> yuzu/main.cpp:GMainWindow:370: Host CPU: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz | AVX2 | FMA
[   0.223256] Frontend <Info> yuzu/main.cpp:GMainWindow:372: Host CPU Cores: 2
[   0.223257] Frontend <Info> yuzu/main.cpp:GMainWindow:375: Host CPU Threads: 4
[   0.223280] Frontend <Info> yuzu/main.cpp:GMainWindow:376: Host OS: Debian GNU/Linux bookworm/sid
[   0.223296] Frontend <Info> yuzu/main.cpp:GMainWindow:377: Host RAM: 7.65 GiB
[   0.223306] Frontend <Info> yuzu/main.cpp:GMainWindow:379: Host Swap: 7.88 GiB
[   0.390984] Frontend <Warning> yuzu/game_list.cpp:LoadCompatibilityList:731: Game compatibility list is empty
[   0.456401] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.0.0) applied successfully
[   0.493252] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:440:     RomFS: Update (v0.0.0) applied successfully
[   2.478138] Frontend <Info> yuzu/main.cpp:BootGame:1663: yuzu starting...
...
[   6.835904] HW.GPU <Warning> video_core/engines/maxwell_3d.cpp:ProcessFirmwareCall4:317: (STUBBED) called
[   6.842128] Service.VI <Warning> core/hle/service/vi/vi.cpp:AdjustRefcount:109: (STUBBED) called id=1, addval=00000001, type=00000000
[   6.843000] Service.VI <Warning> core/hle/service/vi/vi.cpp:AdjustRefcount:109: (STUBBED) called id=1, addval=00000001, type=00000001
[   6.847448] Service.VI <Warning> core/hle/service/vi/vi.cpp:GetNativeHandle:121: (STUBBED) called id=1, unknown=0000000F
[   6.941011] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[   9.083387] Service <Warning> core/hle/service/sm/sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[   9.086368] Service.Audio <Info> audio_core/sink/sdl2_sink.cpp

### System Configuration

CPU: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz | AVX2 | FMA
GPU/Driver: Mesa Intel(R) HD Graphics 5500 (BDW GT2), i915, Mesa 22.3.1
RAM: 8 GB
OS: Linux, Debian Testing (bookworm), 6.0 Linux kernel

**Comment by liamwhite** [comment]
It doesn't seem like this coudl be anything other than a driver bug in Mesa. Does it work with Vulkan?

**Comment by gandalth** [comment]
I cannot tell - yuzu crashes with vulkan on my Intel hardware ever since.

Which options do I have? Submit a bug report to the mesa project?

**Comment by liamwhite** [comment]
Yes, I would do that. I don't have the hardware in question, and things work as expected on my laptop's Core i5.

**Comment by gandalth** [comment]
Thank you, Liam!

To anyone interested in the topic, here is the bug report to mesa:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/7990
