### ISSUE TITLE
Steamdeck wont load dumped Game "Bad Header" on PC it works

### ISSUE THREAD

**Issue by Lovetoy** [yuzu-emu/yuzu#9545]
### Issue

Hi,

i have some Issues with some Games. My Brother and I dumped it with the Quick Start Guide to my PC. It works well and everything is fine. 
If i try to open the File on the SteamDeck Yuzu it says, the NCA File has a bad Header.
I tryed the EmuDeck Yuzu / Flatpack and Appimage 1291.
So what i am doing wrong ? :-) 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10330652/yuzu_log.txt)

**Comment by SleepingSnakezzz** [comment]
This is an issue tracker for development, not a support forum. Try asking for support with your issue in the yuzu discord server or on the Citra forums.

**Comment by merryhime** [comment]
If it's working on your PC, ensure that the copy on your Steam Deck is an accurate copy of the one on your PC.

Closed as this is not a support forum.
