### ISSUE TITLE
Graphics 0.25x

### ISSUE THREAD

**Issue by raul-parada** [yuzu-emu/yuzu#9546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Is there an option for a 0.25x graphic environment to speed up the game? 

### Why would this feature be useful?

To speed up the game when GPU is not enough

**Comment by liamwhite** [comment]
This is unlikely to give any significant speedup. The effective resolution at 0.5x is 640x360; if you are having trouble with this amount of fillrate, it is more likely to be a CPU bottleneck than a GPU bottleneck.

**Comment by goldenx86** [comment]
Any GPU weak enough to benefit from 0.25x is also old enough to have more important problems.
