### ISSUE TITLE
[Pokemon: Let's Go Pikachu!] Yuzu crashes when attempting to install update NSP to NAND

### ISSUE THREAD

**Issue by wertercatt** [yuzu-emu/yuzu#9551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1294

### Description of Issue

When attempting to install an NSP of 010003F003A34800v131072 to NAND, the entire emulator force closes without installing it.

SHA256 of the affected file: 9b267f94caaebfc9003cad9f812dc5bf207b0d268a386f105df38421b4ecd339

I have 010003F003A34800v0 installed to NAND if that makes a difference.

### Expected Behavior

Installing the update should work properly

### Reproduction Steps

Hover over 'File' and click 'Install Files to NAND'
Select the update NSP
Click 'Install' on the prompt
Progress bar gets to 95%
Entire emulator closes

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10346167/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5 1600 (12) @ 3.200GHz
GPU/Driver: NVIDIA GeForce GTX 750 Ti / 522.25
RAM: 16320MiB
OS: Windows 10 Pro x86_64 19045

**Comment by german77** [comment]
Make sure you got enough  free storage and the latest keys. Dump the update again to ensure it's not corrupt

**Comment by gidoly** [comment]
closes due to containing pirated content evidence
