### ISSUE TITLE
I build yuze when using resolution crash

### ISSUE THREAD

**Issue by luo12yan** [yuzu-emu/yuzu#9553]
### Issue

![setting](https://user-images.githubusercontent.com/2800265/210688946-4cb1ea7d-0190-4f57-b667-60f99489aad5.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10348904/yuzu_log.txt)
[CMakeCache.txt](https://github.com/yuzu-emu/yuzu/files/10348908/CMakeCache.txt)
Configure according to the official tutorial。
What should I do？

**Comment by liamwhite** [comment]
Re-file with the correct template, there is not enough information to help you
