### ISSUE TITLE
Crashes if the option "Emulate Analog with Keyboard Input" is enabled.

### ISSUE THREAD

**Issue by kevin98761234** [yuzu-emu/yuzu#9562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1293 1294 1295

### Description of Issue

With the option "Emulate Analog with Keyboard Input" enabled, yuzu crashes when I randomly hit the keyboard keys on the analog stick. mainline1292 does not have this problem.

The software that I have been able to check is
SUPER MARIO ODYSSEY
Fire Emblem Warriors: Three Hopes
Hyrule Warriors: Age of Calamity
Pokemon SV
Pikmin 3 Deluxe
Fire Emblem: Three Houses
The Legend of Zelda: Skyward Sword HD

This option is required to open the main dungeon door with a diagonal input to the lower right of the stick when clearing SkywardSword using only the keyboard.

### Expected Behavior

No crash even with option "Emulate Analog with Keyboard Input" enabled.

### Reproduction Steps

Activate the option "Emulate Analog with Keyboard Input".
Set "ConnectController" to "ProController".
Set "InputDevice" to "KeyboardOnly".
Set keyboard keys to analog sticks.
Launch appropriate software.
Press the keyboard keys on the analog stick repeatedly.

### Log File

SUPER MARIO ODYSSEY
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10356292/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i3-8300 CPU @ 3.70GHz | AVX2 | FMA
GPU/Driver: NVIDIA GeForce GTX 1660 SUPER 527.56.0.0
RAM: 15.94 GiB
OS: Windows 10 Version 22H2 (Build 19045.2364)

**Comment by german77** [comment]
Confirmed. A fix is dropping soon.
