### ISSUE TITLE
[Linux] Mario Kart 8 green screen

### ISSUE THREAD

**Issue by SeaKestrel** [yuzu-emu/yuzu#9568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1298

### Description of Issue

I just installed the last version of Mario Kart 8 (2.2.1) by nsp.
Everything works fine, until we start a race, the screen goes green.
![0100152000022000_2023-01-06_23-04-29-414](https://user-images.githubusercontent.com/78849811/211108367-a515203c-25e7-4804-8d23-4e8c28df41c4.png)

### Expected Behavior

Install the 2.2.1 update from a nsp file and play as usually

### Reproduction Steps

Install the 2.2.1 update of Mario Kart 8 from a nsp file, start a race to play with any kart.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10363418/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Pentium(R) Gold G6400 CPU @ 4.00GHz
GPU/Driver: from cpu
RAM:15.14 GiB
OS:Linux Ubuntu 22.10

**Comment by piplup55** [comment]
this is a opengl issue, vulkan is unaffected, update doesn't matter either (see attached screenshot) and it also happens under windows
![image](https://user-images.githubusercontent.com/100526773/211112723-62c27f37-6abd-4977-a722-4b7b668825d9.png)
**System Specs:**
Linux:
 - OS: Arch Linux
 - CPU: AMD Ryzen 7 3700X
 - GPU: RX6600 XT
 - Memory: 80GB, Swap: 256GB
 - GPU Driver: Mesa 22.3.2, radv 22.3.2

Windows:
 - OS: Windows 10 21H1
 - CPU: AMD Ryzen 7 3700X
 - GPU: RX6600 XT
 - Memory: 48GB, Pagefile: 3.63GB
 - GPU Driver: 22.11.2

**Comment by german77** [comment]
This issue happens on all vendors and operating system

**Comment by Memoisaac27** [comment]
It happened in my Windows System using vulkan and open Gl... I have the latest ver of yuzu installed! Need help please!

**Comment by Memoisaac27** [comment]
Where do you get the latest ver of Mario Kart by nsp?

**Comment by AgustinRamiroDiaz** [comment]
Is there a workaround for this?

**Comment by hajosattila** [comment]
Same problem here...

**Comment by german77** [comment]
This issue has been fixed on mainline 1301. Please make sure you are running on the latest version.
