### ISSUE TITLE
Any possibility of Yuzu and Ryujinx ever sharing shader caches?

### ISSUE THREAD

**Issue by hyoretsu** [yuzu-emu/yuzu#9571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Yuzu being able to use the same shader caches as Ryujinx. I understand this might not be possible since one's made in C# and the other in C++, but at least make its generation universal, and not hardware-dependant.

### Why would this feature be useful?

Yuzu does work better for me, but its shader caches aren't universal like Ryujinx's. [link removed by moderator] I really wanted to be able to share (and also get) my complete shader caches. (And also not lose them when I inevitably upgrade my PC)

**Comment by G-Spawn** [comment]
this wont be possible anytime soon. closing.

**Comment by Norstyrm** [comment]
Yuzu's shadercaches are already universal, and not hardware dependant as described in this request, and you can therefore use the same shadercache across different systems with different GPUs.

That said, the shadercaches contains game code which makes them illegal to share. The same goes for Ryujinx's shadercaches, and therefore puts tools like RyuSAK, which allows you to share these, in a shady area which we will not support
