### ISSUE TITLE
Regression! Vulkan completely broken as of Mainline 1298

### ISSUE THREAD

**Issue by PlatinumLucario** [yuzu-emu/yuzu#9577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1298

### Description of Issue

When attempting to run any game while on Vulkan backend, the emulator will immediately crash. Crashes even before the loading shaders part.

If this was intentional, then there needs to be a message explaining that the render backend isn't supported and prevent the game from loading, and not crash the entire emulator.

I will test this on older NVIDIA drivers as well, just to be sure that this isn't isolated to just nvidia-driver-525.

### Expected Behavior

Either the emulator needs to display a message to explain that it cannot work, or it shows that its loading the shaders, and proceed to boot the game.

### Reproduction Steps

1. Open the emulator.
2. Select File > Settings
3. Select Graphics.
4. Make sure the Graphics backend is set to Vulkan and the API is set to your graphics driver.
5. Run any game in Yuzu.

### Log File
**redacted due to containing pirated content**

### System Configuration

CPU: Intel® Core™ i3-6100 CPU @ 3.70GHz × 4
GPU: NVIDIA Corporation GM206 [GeForce GTX 950]
GPU Driver: nvidia-driver-525
RAM: 16 GiB
OS: Ubuntu 22.04.1 LTS

**Comment by G-Spawn** [comment]
We don't support pirates here. But they're aware of the issues. Closing.
