### ISSUE TITLE
graphical Issue - Marvel Ultimate Alliance 3: The Black Order

### ISSUE THREAD

**Issue by MauMauMlK** [yuzu-emu/yuzu#9579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3297

### Description of Issue

I have a graphical Issue in the game **_Marvel Ultimate Alliance 3: The Black Order_**, as shown in the image

GPU: GTX 1060
Drive version: 528.02
Yuzu EA 3296

![Marvel UA 3 - Black Order](https://user-images.githubusercontent.com/88567126/211165430-e67c42e4-d557-4cae-acbb-0b13e8d9f23e.JPG)

### Expected Behavior

Expectation of starting the game without the issues as it was in the last EA3292 version that works normally

### Reproduction Steps

I start the game normally and when I start gameplay the problem appears

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10366991/yuzu_log.txt)

### System Configuration

CPU: i5-7400
GPU/Driver: Nvidia GTX 1060 3GB / Ver. 528.02
RAM: 16GB
OS: Win10

**Comment by G-Spawn** [comment]
Devs are aware. Pardon the inconvenience.

**Comment by MauMauMlK** [comment]
> Devs are aware. Pardon the inconvenience.

Thank you for the quick response friend!!! :)
