### ISSUE TITLE
[Linux][Wayland] Vulkan initialization error

### ISSUE THREAD

**Issue by ivdok** [yuzu-emu/yuzu#9580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

r22970.432d48d9c

### Description of Issue

Yuzu crashes when running Vulkan backend immediately. Without prime-run command (to offload render to dGPU) process crashes immediately, while with prime-run I can see "Loading..." progress bar, but ultimately the logs are the same.
Stdout has following log:
```
libpng warning: iCCP: known incorrect sRGB profile
[destroyed object]: error 7: importing the supplied dmabufs failed
The Wayland connection experienced a fatal error: Protocol error
The Wayland connection experienced a fatal error: Protocol error
```

### Expected Behavior

Proceed to playable gamestate, as with OpenGL backend

### Reproduction Steps

0. Build https://aur.archlinux.org/packages/yuzu-git package
1. Dump keys, start yuzu
2. Open dumped game

### Log File

[   0.034114] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.034125] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.122444] Frontend <Info> yuzu/main.cpp:GMainWindow:354: yuzu Version: yuzu | r22970.432d48d9c 
[   0.122446] Frontend <Info> yuzu/main.cpp:LogRuntimes:244: Qt Compile: 5.15.7 Runtime: 5.15.7
[   0.122449] Frontend <Info> yuzu/main.cpp:GMainWindow:370: Host CPU: AMD Ryzen 9 5900HX with Radeon Graphics         | AVX2 | FMA
[   0.122464] Frontend <Info> yuzu/main.cpp:GMainWindow:372: Host CPU Cores: 8
[   0.122466] Frontend <Info> yuzu/main.cpp:GMainWindow:375: Host CPU Threads: 16
[   0.122475] Frontend <Info> yuzu/main.cpp:GMainWindow:376: Host OS: Arch Linux
[   0.122484] Frontend <Info> yuzu/main.cpp:GMainWindow:378: Host RAM: 30.72 GiB
[   0.122486] Frontend <Info> yuzu/main.cpp:GMainWindow:379: Host Swap: 0.00 GiB
[   4.879362] Frontend <Info> yuzu/main.cpp:BootGame:1663: yuzu starting...
[   4.883923] Config <Info> common/settings.cpp:LogSettings:40: yuzu Configuration:
[   4.883931] Config <Info> common/settings.cpp:operator():33: Controls_UseDockedMode: true
[   4.883933] Config <Info> common/settings.cpp:operator():33: System_RngSeed: 0
[   4.883935] Config <Info> common/settings.cpp:operator():33: System_DeviceName: Yuzu
[   4.883936] Config <Info> common/settings.cpp:operator():33: System_CurrentUser: 0
[   4.883937] Config <Info> common/settings.cpp:operator():33: System_LanguageIndex: 1
[   4.883939] Config <Info> common/settings.cpp:operator():33: System_RegionIndex: 1
[   4.883940] Config <Info> common/settings.cpp:operator():33: System_TimeZoneIndex: 0
[   4.883942] Config <Info> common/settings.cpp:operator():33: Core_UseMultiCore: true
[   4.883944] Config <Info> common/settings.cpp:operator():33: CPU_Accuracy: 0
[   4.883946] Config <Info> common/settings.cpp:operator():33: Renderer_UseResolutionScaling: 2
[   4.883948] Config <Info> common/settings.cpp:operator():33: Renderer_ScalingFilter: 5
[   4.883949] Config <Info> common/settings.cpp:operator():33: Renderer_FSRSlider: 25
[   4.883950] Config <Info> common/settings.cpp:operator():33: Renderer_AntiAliasing: 0
[   4.883952] Config <Info> common/settings.cpp:operator():33: Renderer_UseSpeedLimit: true
[   4.883953] Config <Info> common/settings.cpp:operator():33: Renderer_SpeedLimit: 100
[   4.883955] Config <Info> common/settings.cpp:operator():33: Renderer_UseDiskShaderCache: true
[   4.883956] Config <Info> common/settings.cpp:operator():33: Renderer_GPUAccuracyLevel: 1
[   4.883958] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousGpuEmulation: true
[   4.883958] Config <Info> common/settings.cpp:operator():33: Renderer_NvdecEmulation: 2
[   4.883959] Config <Info> common/settings.cpp:operator():33: Renderer_AccelerateASTC: true
[   4.883961] Config <Info> common/settings.cpp:operator():33: Renderer_UseVsync: true
[   4.883962] Config <Info> common/settings.cpp:operator():33: Renderer_ShaderBackend: 0
[   4.883963] Config <Info> common/settings.cpp:operator():33: Renderer_UseAsynchronousShaders: false
[   4.883965] Config <Info> common/settings.cpp:operator():33: Renderer_AnisotropicFilteringLevel: 0
[   4.883967] Config <Info> common/settings.cpp:operator():33: Audio_OutputEngine: auto
[   4.883967] Config <Info> common/settings.cpp:operator():33: Audio_OutputDevice: auto
[   4.883969] Config <Info> common/settings.cpp:operator():33: Audio_InputDevice: auto
[   4.883971] Config <Info> common/settings.cpp:operator():33: DataStorage_UseVirtualSd: true
[   4.883972] Config <Info> common/settings.cpp:operator():37: DataStorage_CacheDir: /home/ivdok/.cache/yuzu
[   4.883973] Config <Info> common/settings.cpp:operator():37: DataStorage_ConfigDir: /home/ivdok/.config/yuzu
[   4.883975] Config <Info> common/settings.cpp:operator():37: DataStorage_LoadDir: /home/ivdok/.local/share/yuzu/load
[   4.883977] Config <Info> common/settings.cpp:operator():37: DataStorage_NANDDir: /home/ivdok/.local/share/yuzu/nand
[   4.883978] Config <Info> common/settings.cpp:operator():37: DataStorage_SDMCDir: /home/ivdok/.local/share/yuzu/sdmc
[   4.883980] Config <Info> common/settings.cpp:operator():33: Debugging_ProgramArgs: 
[   4.883981] Config <Info> common/settings.cpp:operator():33: Debugging_GDBStub: false
[   4.883983] Config <Info> common/settings.cpp:operator():33: Input_EnableMotion: true
[   4.883984] Config <Info> common/settings.cpp:operator():33: Input_EnableVibration: true
[   4.883986] Config <Info> common/settings.cpp:operator():33: Input_EnableRawInput: false
[   4.982512] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:Device:630: Device doesn't support extended dynamic state 3
[   5.002011] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:764: Blacklisting Ampere devices from float16 math
[   5.002016] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:778: NVIDIA Drivers >= 510 do not support MSAA image blits
[   5.011405] Render.Vulkan <Error> video_core/renderer_vulkan/renderer_vulkan.cpp:RendererVulkan:118: Vulkan initialization failed with error: VK_ERROR_INITIALIZATION_FAILED
[   5.011435] HW.GPU <Error> video_core/video_core.cpp:CreateGPU:57: Failed to initialize GPU: Vulkan initialization error VK_ERROR_INITIALIZATION_FAILED
[   5.011440] Core <Critical> core/core.cpp:Load:279: Failed to initialize system (Error 5)!

### System Configuration

CPU: AMD Ryzen 9 5900HX
GPU/Driver: Nvidia RTX 3060 Mobile (nvidia-utils-nvlax installed: 525.60.11-2)
RAM: 32GB
OS: Arch Linux current
Process environment variables:
```
__NV_PRIME_RENDER_OFFLOAD=1
__GLX_VENDOR_LIBRARY_NAME=nvidia
__VK_LAYER_NV_optimus=NVIDIA_only
SHELL=/bin/bash
SESSION_MANAGER=local/ruan:@/tmp/.ICE-unix/2606,unix/ruan:/tmp/.ICE-unix/2606
WINDOWID=2
COLORTERM=truecolor
XDG_CONFIG_DIRS=/home/ivdok/.config/kdedefaults:/etc/xdg
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
LANGUAGE=
DOTNET_ROOT=/usr/share/dotnet
SHELL_SESSION_ID=c796569a404e48afb1293b5b31988887
DESKTOP_SESSION=plasmawayland
LC_MONETARY=ru_RU.UTF-8
GTK_RC_FILES=/etc/gtk/gtkrc:/home/ivdok/.gtkrc:/home/ivdok/.config/gtkrc
XCURSOR_SIZE=24
EDITOR=nano
XDG_SEAT=seat0
PWD=/home/ivdok/.local/share/yuzu
LOGNAME=ivdok
XDG_SESSION_DESKTOP=KDE
XDG_SESSION_TYPE=wayland
SYSTEMD_EXEC_PID=3204
_=/usr/bin/yuzu
XAUTHORITY=/run/user/1000/xauth_JSTZzl
MOTD_SHOWN=pam
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/ivdok/.gtkrc-2.0:/home/ivdok/.config/gtkrc-2.0
HOME=/home/ivdok
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=KDE
KONSOLE_DBUS_SERVICE=:1.77
WAYLAND_DISPLAY=wayland-0
KONSOLE_DBUS_SESSION=/Sessions/3
PROFILEHOME=
PROFILE_SH_INCLUDED=yes
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
INVOCATION_ID=d611a511cdfc4dc1bb58da30484beb93
KONSOLE_VERSION=221200
MANAGERPID=2373
DOTNET_BUNDLE_EXTRACT_BASE_DIR=/home/ivdok/.cache/dotnet_bundle_extract
QT_QPA_PLATFORM=wayland
KDE_SESSION_UID=1000
XDG_ACTIVATION_TOKEN=kwin-5
XDG_SESSION_CLASS=user
TERM=xterm-256color
USER=ivdok
COLORFGBG=15;0
PLASMA_USE_QT_SCALING=1
KDE_SESSION_VERSION=5
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
QT_WAYLAND_FORCE_DPI=96
DISPLAY=:1
SHLVL=2
MOZ_ENABLE_WAYLAND=1
LC_MEASUREMENT=ru_RU.UTF-8
XDG_VTNR=2
XDG_SESSION_ID=2
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
XDG_RUNTIME_DIR=/run/user/1000
DEBUGINFOD_URLS=https://debuginfod.archlinux.org
LC_TIME=ru_RU.UTF-8
QT_AUTO_SCREEN_SCALE_FACTOR=0
JOURNAL_STREAM=8:42927
XCURSOR_THEME=breeze_cursors
KDE_FULL_SESSION=true
NLSPATH=/opt/cprocsp/share/locale/%L/LC_MESSAGES/%N
PATH=/home/ivdok/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/ivdok/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
KDE_APPLICATIONS_AS_SCOPE=1
MAIL=/var/spool/mail/ivdok
_JAVA_OPTIONS=-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Djdk.gtk.version=3
LC_NUMERIC=ru_RU.UTF-8
OLDPWD=/home/ivdok
KONSOLE_DBUS_WINDOW=/Windows/1
```

**Comment by liamwhite** [comment]
try running with QT_QPA_PLATFORM=xcb, seems like a wayland issue on prime

**Comment by ivdok** [comment]
Similar to #9448, but it's not unknown QPA platform this time.

**Comment by ivdok** [comment]
Ok, yes, xcb platform did work, but now I'm getting fractional scaling bugs, hence why exported this variable globally before.

**Comment by liamwhite** [comment]
We probably can't do anything about it, this needs an upstream report to your compositor
