### ISSUE TITLE
The AI doesn't take it's turn in Clubhouse games

### ISSUE THREAD

**Issue by s-cd** [yuzu-emu/yuzu#9584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1298

### Description of Issue

https://user-images.githubusercontent.com/50283939/211185134-cd37c13e-55cc-4356-b840-1dfe99253763.mp4

Whenever you play pool the AI never makes up their mind and keeps trying to find the right position to hit the ball

### Expected Behavior

The AIs turn should be finished in 5 seconds as seen in [this video](https://youtu.be/Jrg899ZlNmY?t=151) 

### Reproduction Steps

Open Clubhouse Games
Start a 9 ball billiards game 
Take your turn and then have the AI take their turn

### Log File

[yuzu_liog.txt](https://github.com/yuzu-emu/yuzu/files/10367920/yuzu_liog.txt)

### System Configuration

CPU:AMD Custom APU
GPU/Driver:AMD Custom GPU
RAM:14.5 GiB of RAM
OS: Steam OS

**Comment by Felina-Lain** [comment]
This is still an issue in yuzu 1325 (23/01/30)

**Comment by SuperFromND** [comment]
This appears to have been fixed as of Yuzu 1354, possibly earlier.
