### ISSUE TITLE
Shortcuts (Playnite and command line) not launching game anymore

### ISSUE THREAD

**Issue by hyoretsu** [yuzu-emu/yuzu#9590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1298, 1299, 1300

### Description of Issue

The command `C:\Emulators\Switch\yuzu.exe "X:\!Emulators\Super Kirby Clash.nsp"` doesn't launch my desired game anymore, as was used in shortcuts.

### Expected Behavior

It should launch the game.

### Reproduction Steps

Just try the command I provided.

### Log File

.

### System Configuration

CPU: Intel Core i5-1135G7
GPU/Driver: Intel Iris Xe
RAM: 16GB 3200 MHz
OS: Windows 11

**Comment by piplup55** [comment]
the arguments were updated, see below for the new arguments

```yuzu.exe "path_to_game" - Launches a game at path_to_game
yuzu.exe -f - Launches the next game in fullscreen
yuzu.exe -g "path_to_game" - Launches a game at path_to_game
yuzu.exe -f -g "path_to_game" - Launches a game at path_to_game in fullscreen```

**Comment by hyoretsu** [comment]
Those also don't seem to work. The exact commands I'm using are `C:\Emulators\Switch\yuzu.exe -f -g "X:\!Emulators\Super Kirby Clash.nsp"`, `C:\Emulators\Switch\yuzu.exe "X:\!Emulators\Super Kirby Clash.nsp"` and `C:\Emulators\Switch\yuzu.exe -g "X:\!Emulators\Super Kirby Clash.nsp"`. They all just launch Yuzu, either though PowerShell or Playnite.

**Comment by piplup55** [comment]
i don't see anything wrong with your paths, however i don't think windows accepts ! in the path,
afew things you could try:
a simpler path, removing the "!" from the folder name, a file without spaces

**Comment by hyoretsu** [comment]
Removing the ! didn't work (I know it causes issues sometimes, but it's not the culprit this time) neither removing all spaces from both paths.

**Comment by G-Spawn** [comment]
Did you merge your update & dlc to your base game? That can be why it has issue for launchers. Context <https://github.com/yuzu-emu/yuzu/issues/8352>

**Comment by hyoretsu** [comment]
> Did you merge your update & dlc to your base game? That can be why it has issue for launchers. Context #8352

I did, but it does that for base games too.

**Comment by hyoretsu** [comment]
Fixed among the updates.
