### ISSUE TITLE
AudioRen should be smarter about sample rate to use

### ISSUE THREAD

**Issue by bunnei** [yuzu-emu/yuzu#962]
Currently for audren implementation, we use a hard coded 48000Hz sample rate for all samples. See:
https://github.com/yuzu-emu/yuzu/blob/master/src/audio_core/audio_renderer.cpp#L12 

This was for simplicity for the initial implementation. However, audren can be configured to use variable sample rates (on a per-voice basis). For example, with Cave Story, we see 44200Hz and 22050Hz used. This results in incorrect sounding audio.

We may want to fix this by creating a new stream for each unique sample rate used, and then mixing the audio into the right one.

**Comment by bunnei** [comment]
Resampling is also an option

**Comment by Hexagon12** [comment]
We already have interpolation, which works fine - https://github.com/yuzu-emu/yuzu/pull/1033.

Requesting to close.

**Comment by Hexagon12** [comment]
Bumping for closing
