### ISSUE TITLE
Glitched trees and plants in Pokémon S/V

### ISSUE THREAD

**Issue by Loris19** [yuzu-emu/yuzu#9621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1296 -> 1307

### Description of Issue

After a loading screen (e.g. after flying to a location), trees and plants start glitching, disappearing and reappearing quickly.
When I first noticed the issue in Mainline 1296, the issue was more serious, with frequently disappearing walls and buildings, and vertex explosions (I was able to reproduce this once in 1307 but did not capture it).

I tried disabling the new graphics settings (GPU max boost clock and Vulkan pipeline cache) to no avail.

https://user-images.githubusercontent.com/9156871/212501008-71ed682e-3e79-451f-9065-08f61840bfc1.mp4

### Expected Behavior

Trees should not phase in and out of the plane of existence of the player character.

### Reproduction Steps

Load up Pokémon Scarlet/Violet and fly to a place that has trees. Montenevera (snowy city) and Cortondo (first gym city) are common offenders.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10419090/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel Core i5 7600K @5GHz
GPU/Driver: NVIDIA GTX 1060 6GB / Game Ready Driver v528.02
RAM: 16GB DDR4 2666MHz
OS: Windows 11 22H2 Build 22621.1105

**Comment by G-Spawn** [comment]
They are aware of the issue. Sorry for the inconvenience they will fix it in time 🙏

**Comment by Loris19** [comment]
As pointed out in #9648, using Paranoid CPU accuracy fixes the glitches (but tanks the framerate too much for the game to be playable)
![Capture d'écran_20230124_161938](https://user-images.githubusercontent.com/9156871/214336046-c1749577-0dbd-467f-9b33-00b4510f354e.png)

![Capture d'écran_20230124_162453](https://user-images.githubusercontent.com/9156871/214336066-99145aaa-b1cf-437d-8d62-54f4a88651c8.png)

**Comment by AndehX** [comment]
As of today, this issue is currently still present.

**Comment by RenanTafner** [comment]
same issue here

**Comment by Hatsune-Cthulhu** [comment]
Any news of a fix?
