### ISSUE TITLE
Xenobalde 3 crash on Intel Xe GPU

### ISSUE THREAD

**Issue by I-LoveCpp** [yuzu-emu/yuzu#9628]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Affected Build(s)

Mainline 1310 & Early Access 3310 (Probably Earlier)

### Description of Issue

Yuzu crashes while playing the anime of Xenoblade 3 .
It crashes while compiling shaders (usually more than 1000 shaders).
But it seems to be a memory problem.

Yuzu freezes when compiling lots of shaders for a second.
Then it will play a flash of the anime 。
Next Windows pop-up prompt xxxxxxx instruction refers to memory, which cannot be read。
And it crashes finally.

And next time when you want to play Xenoblade, you must remove vulkan pipeline cache or yuzu will crash while loading the lastest shaders when you lauch the game.

### Expected Behavior

The anime should play normally.

### Reproduction Steps

Set Vulkan as the gpu renderer and play the anime in event theater (like Chapter 6 : Choices -  Shania the Traitor).

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10430686/yuzu_log.txt)

### System Configuration

CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
GPU : Intel(R) Iris(R) Xe Graphics 80EU
Driver: 31.0.101.4032 [[Driver]](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html)
RAM: 8GB
OS: Windows 10 21H2

**Comment by goldenx86** [comment]
Intel Windows drivers are broken, wait for Intel to fix them: https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/159
