### ISSUE TITLE
Super Mario Odyssey Audio Delay During The First Cutscene

### ISSUE THREAD

**Issue by popdoo323-pop** [yuzu-emu/yuzu#9633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1310

### Description of Issue

During the first cutscene, there seems to be an audio delay it's very noticeable after Bowser shoots his fireable past Mario during that cutscene.

### Expected Behavior

here is a comparison I made between the Switch Console and on the Yuzu emulator. (to point out the delay)
Base Switch Console Recording:

https://user-images.githubusercontent.com/85776019/212944768-70c11d5e-68e8-4dfc-9d24-a7d6b1f796a5.mp4

Yuzu Recording:

https://user-images.githubusercontent.com/85776019/212947378-5073e60f-4937-4385-939a-8a33320bd944.mp4

### Reproduction Steps

all I did was hit start and noticed the cutscene audio was off.
(I was using Vulkan and GPU High, Docked Mode for Yuzu)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10436660/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
GPU: NVIDIA GeForce RTX 3070 Ti
GPU Driver Version: 31.0.15.2756
RAM: 32 GBs
OS: Windows 10

**Comment by FearlessTobi** [comment]
Are you sure your game is running at full speed at all times?
If the emulation speed is slower than 100% , the audio will desync.

**Comment by popdoo323-pop** [comment]
![image](https://user-images.githubusercontent.com/85776019/212992468-5c677587-8fde-47df-a1e0-26acd0f674ce.png)
my speed during that recording

**Comment by FearlessTobi** [comment]
Then I will close this as wontfix.
Audio is being played asynchronously at 100% speed, regardless how fast your game runs.
