### ISSUE TITLE
Left joycon does not detect any motion in Ring Fit Adenture

### ISSUE THREAD

**Issue by WhaleJ84** [yuzu-emu/yuzu#9636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1311

### Description of Issue

I am running Ring Fit Adventure Update 1.2.0 on Yuzu Mainline 1311 on a Steam Deck using official joycons, firmware, keys, etc. from a Switch updated to firmware 15.0.1 (controllers updated to most recent, not sure how to get exact version number).
I have player 1 set up to be Right Joycon with Nintendo Switch Joy-Con (L/R) 0 mapped.
I have player 2 set up to be Dual Joycons with Nintendo Switch Joy-Con (L/R) 0 mapped.
**NOTE:** I am aware in #8489 it is said it should be mapped to right and left joycons respectively, however they do not come up as individual options. 'Steam Virtual Gamepad' 0/1 do appear, however they do not function as intended (no buttons work), whereas Nintendo Switch Joy-Con (L/R) 0 buttons do work.

I am stuck at the 'Attachment Guide' screen, where it tells you to put the left joycon in the leg strap and stand still. Pressing *minus* on the left joycon successfully plays the video, and pressing *plus* on the right joycon successfully closes the video (only using the Nintendo Switch Joy-Con (L/R) 0 mapping stated above). However I cannot progress, as despite following the instructions as intended, the game will never detect it.

I have tried to verify that the motion works in other games I own (notably Super Mario: Odyssey works using the **right** joycon motion to guide the hat), but none of the other games I own utilise motion in the left joycon.
To try test this further, I booted Ring Fit Adventure up on the switch and sure enough, I can get past that screen fine so it does appear to be a virtualisation issue.

I have tried to be as specific as possible but please let me know if I have missed something so I can give even further. 
Same happens in both Gaming mode and Desktop mode of the Steam Deck.

### Expected Behavior

Be able to pass the 'Attachment Guide' screen that first shows on boot of the game. Currently it does not detect motion in the left joycon.

### Reproduction Steps

1. Have a Steam Deck
2. Use Yuzu 1311 (was still persistent in 1305)
3. Use official L/R joycons
4. Have player 1 set up to be Right Joycon with Nintendo Switch Joy-Con (L/R) 0 mapped
5. Have player 2 set up to be Dual Joycons with Nintendo Switch Joy-Con (L/R) 0 mapped
6. Boot Ring Fit Adventure Update 1.2.0
7. Verify both joycons can open and close tutorial video on 'Attachment Guide' screen
8. Attempt to bypass screen instructing to strap the left joycon around your left waist

### Log File

None provided. No console booted alongside the window. Please let me know how I can provide one if needed.

### System Configuration

CPU: AMD APU Zen 2 4c/8t, 2.4-3.5GHz
GPU/Driver: AMD APU 8 RDNA 2 CUs, 1.0-1.6GHz
RAM: 16 GB LPDDR5 on-board RAM
OS: SteamOS Holo 3.4.4

**Comment by german77** [comment]
Have you tried mapping motion manually? For left joycon to work it must be mapped on the player 2 config

**Comment by WhaleJ84** [comment]
When trying to manually map the motion for Player 2, Dual Joycons using Nintendo Switch Joy-Con (L/R) 0 mapping, pressing either Motion 1 or Motion 2 only detects motion when waving the right joycon. waving around the left joycon does nothing, and it eventually defaults back to the original value, which is *sdl* (the same value set by waving the right joycon). Trying to do the same using any other input device (e.g. Steam Input Device 0 or 1) detects no motion whatsoever, even from the right joycon.

**Comment by german77** [comment]
Virtual gamepads usually don't have motion. Seems like this is an issue from newer SDL. I will try to fix it when the new version is out.

**Comment by WhaleJ84** [comment]
I thought as much. I thought it'd be best to provide as much information as possible to narrow down the issue. Will there be a notification in this issue when a version that includes a fix in the mainline branch has been released? Many thanks for your work!

**Comment by german77** [comment]
A new version releases each month. I will link the PR to this issue so you get notified.

**Comment by WhaleJ84** [comment]
Perfect. Much appreciated!

**Comment by WhaleJ84** [comment]
Appears to be fixed in mainline 1325

**Comment by Sandi25** [comment]
I was able to encounter the same issue on the Yuzu 1622 build (2023-11-16). I'm running Ring Fit Adventure with update 1.2 on Windows 10 Pro with the official Joy-cons updated to the latest version.

In the Configuration view for player 1 and player 2 inputs for each Joy-Con are visible and correct. Using the Ring Controller Configurator I can also see Ring sensor values updating as I pull / push.

**To reproduce this bug:**
- Set player 1 as Connect controller: Right Joy-Con, Input device: Right Joy-Con
- Set player 2 as Connect controller: Dual Joy-Con, Input device: Left Joy-Con
- Start the game
- Once the game is booted the ring Joy-Con will vibrate and I am instructed to strap the Left Joy-Con 

From this point on no input on the Left Joy-Con will work except the "-" button which will start the instructions screen.

**Specs**
CPU: i7-8550U 
RAM: 16 GB 
OS: Windows 10 Pro Version: 22H2
