### ISSUE TITLE
Can't join in a online match using rooms

### ISSUE THREAD

**Issue by karentiemi10** [yuzu-emu/yuzu#9643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early access 1310

### Description of Issue

I have a mikrotik, and I thought it might be blocking multiplayer traffic, so I disabled the firewall and still got no result. I tried directly on the ISP's modem and I still couldn't connect or anyone access my host. So I thought it was ISP blocking and I created a VPN and did the test, I changed the interface in the system tab and put it to the VPN interface and the result was the same, access to the Mario Kart multiplayer room, but when the owner of the room starts the race the message "you were unable to connect" occurs. I did the whole process of removing the Yuzu in the folder or using the yuzu management tool and nothing made a difference. The image bellow is the connection test to host on the pokémon game and mario kart.
![212919385-ff2c136b-ce9d-4128-8100-2ba9b4d20c08](https://user-images.githubusercontent.com/113842737/213453613-f4188a29-7e3b-4e81-8f7d-6e2f111f9916.png)
![212921545-93441fd1-7e7e-4716-89bc-6c4a3195b632](https://user-images.githubusercontent.com/113842737/213453624-65e90c3d-6c71-4089-87d0-b0aa17f69a75.png)

### Expected Behavior

Start the games online with no connection problems

### Reproduction Steps

Install Yuzu, download the firmware and keys 15.0.1, install the games and dlcs/updates, install updates to nand, browse or create a room connect and open up the game e tente wireless play on mario kart or union/tera raid on pokémon scarlet/violet.

### Log File

https://github.com/yuzu-emu/yuzu/files/10435874/yuzu_log.txt

### System Configuration

CPU: Ryzen 5 5700x
GPU/Driver: GTX 1070 / v528.02
RAM: 32 GB 3200mhz
OS: Windows 11

**Comment by G-Spawn** [comment]
Closing in favour of your existing issue. Please don't make duplicates https://github.com/yuzu-emu/yuzu/issues/9632

**Comment by Yair093TL** [comment]
I have the same problem, were you able to solve it?
