### ISSUE TITLE
All games freezes

### ISSUE THREAD

**Issue by xhx-roy** [yuzu-emu/yuzu#9645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1312 built 01-18-23

### Description of Issue

All game freezes in yuzu 1312 built 01-18-23 running on Steam deck SteamOS 3.4.4

### Expected Behavior

It should runnig like before. Those games all can running well in last version before I updated to 01-18-23, and I do nothing about my system or yuzu settings but it can't work now

### Reproduction Steps

Just try all my games in my folder, like Xenoblade Chronicles 3, I played for a while, now it shows ingame loading logo and frozeed, the FPS is 0 and game stop running.

### Log File

none

### System Configuration

Steam Deck running Steam OS 3.4.4

**Comment by G-Spawn** [comment]
please reopen  issue when you can provide a log
