### ISSUE TITLE
api-ms-win-core-com-l1-1-0.dll, api-ms-win-downlevel-kernel32-l2-1-0.dll, and 0xc000007b errors since mainline yuzu version 1168

### ISSUE THREAD

**Issue by fm3845w0** [yuzu-emu/yuzu#9650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline >= 1168

### Description of Issue

When I launch yuzu.exe, it errors:

"The program can't start because api-ms-win-core-com-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

After I relaunch with that DLL, it errors differently:

"The program can't start because api-ms-win-downlevel-kernel32-l2-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

After I relaunch with that DLL, it errors differently:

"The application was unable to start correctly (0xc000007b). Click OK to close the application."

I cannot progress past this error message.

REGRESSION TRACKING:

The problem is absent in mainline-0-1167. It is introduced in 0-1168:

https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1168

WORKAROUNDS:

When I launch mainline-0-1167, I can boot games.

When I launch yuzu-cmd.exe, instead of yuzu.exe, I can boot games.

When I launch Ryujinx, I can boot games.

### Expected Behavior

yuzu.exe should show the UI and boot games.

### Reproduction Steps

Run the yuzu.exe from mainline-0-1168 or later.

### Log File

(N/A)
[na.txt](https://github.com/yuzu-emu/yuzu/files/10466195/na.txt)

### System Configuration

The problem occurs on Windows 7.

The problem occurs on both the GTX 980 and 1070 graphics cards.

The problem occurs on both a 6th generation Intel i7 and on AMD Ryzen 5.

The problem coexists with an installation of either the .NET Framework 4.7.2 or 4.8.

The problem occurs regardless of VC redistributables (2008, 2010, 2012, 2013, 2015-2022).

The problem occurs despite drivers and updates being up to date.

**Comment by liamwhite** [comment]
Windows 7 is not supported.
