### ISSUE TITLE
Individual game region set to taiwan & korea, crash immediately

### ISSUE THREAD

**Issue by Ryan2603** [yuzu-emu/yuzu#9655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

latest 1315 + 3322

### Description of Issue

As title, individual game region set to taiwan & korea, crash immediately
BUT set to china , no crash, set to EU, no crash

Globally set to taiwan , its fine, 
but in individual title, crash everytime

### Expected Behavior

nope

### Reproduction Steps

try to set individual game region to taiwan

### Log File

nope

### System Configuration

CPU: AMD
GPU/Driver: NVIDIA
RAM: 64G
OS: W11

**Comment by Ryan2603** [comment]
crash also if set to korea

**Comment by german77** [comment]
Any particular game? rather than me discovering which of my games even supports taiwan or korea
