### ISSUE TITLE
Using moonlight streaming to GeForceExperience.  Inputs do not work when set to any (defaulted at launch).

### ISSUE THREAD

**Issue by XmemphistoX** [yuzu-emu/yuzu#9658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1315

### Description of Issue

I'm using moonlight streaming to Geforce experience and upon launching yuzu, my inputs do not work.  They default to any which I understand should take any input from that list however, it does not work until I specify my xinput device specifically.

### Expected Behavior

Launch moonlight with controllers connected.  Then launch yuzu and have inputs work automatically without user input based on prior configurations.

### Reproduction Steps

Setup GFE game streaming and connect to it using moonlight as a client on Nvidia Shield TV or any other android tv/phone with gamepad already connected and on.  Launch yuzu - controls do not work.  Go into the menu to change any to xinput and they will.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10473362/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5800x
GPU/Driver: GTX1070/582.02
RAM:32gb
OS:Win11

**Comment by Loris19** [comment]
Does this occur every time you start Yuzu/Gamestream? I've had a similar issue for years but I'm not sure it is Yuzu's fault. NVIDIA Gamestream uses a different Xinput "device" than if your controller is directly connected to your PC, meaning Yuzu can't find the previously connected controller if you switch back and forth between Gamesteam and playing directly on your PC.
If my memory serves me right, once Yuzu is configured to use the Gamestream Xinput, it should work the next time you play via streaming.

**Comment by XmemphistoX** [comment]
I thought the same and have 2 instances of Yuzu running to avoid any input config changes.  I'll do some testing and report back.

**Comment by Macrox14** [comment]
I have the same issue, but is even worse, after I select the input manually in moonlight and start to works great, if I go back to my PC and connect my controller, Yuzu doesn't detect it (unless I select it manually again).

I don't expect that Yuzu remember the configs or anything, I just want to detect and select the controller automatically

**Comment by XmemphistoX** [comment]
I believe Loris19 and Macrox14 are correct.  As a way around this I have two instances of yuzu.  One for strreaming and one for at the PC.  I've also symlinked my nand folder across both instances to carry saves across.
