### ISSUE TITLE
[Feature Request] Add DLSS ans XeSS for window adapting fliter

### ISSUE THREAD

**Issue by I-LoveCpp** [yuzu-emu/yuzu#9659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add DLSS ans XeSS for window adapting fliter

### Why would this feature be useful?

They can both improve performance. DLSS is useful on NVIDIA GPU and XeSS is useful on all GPU (especially Intel Arc GPU).

**Comment by liamwhite** [comment]
Duplicate of #8062 and #8061

**Comment by goldenx86** [comment]
Switch games don't provide motion vectors and other information required for temporal filters, so it's not an option.

**Comment by boludoz** [comment]
> Switch games don't provide motion vectors and other information required for temporal filters, so it's not an option.

https://jcgt.org/published/0010/03/02/
