### ISSUE TITLE
New Super Mario Bros. U Deluxe freeze on boss fights

### ISSUE THREAD

**Issue by Nevro** [yuzu-emu/yuzu#9665]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Early access 3323

### Description of Issue

I use early access yuzu buildded from source (Arch/AUR)! I try with different firmware versions 15.0.1, 14.1.1 and 13.2.1, with OpenGL and VULKAN api at default settings, but nothing help! This happening now for long time, not just latest version!

### Expected Behavior

Not freeze on boss fights!

### Reproduction Steps

Play the game?

### Log File

KERNEL LOG:
[https://pastebin.com/FhrxBcgt](https://pastebin.com/FhrxBcgt)

YUZU LOG:
[https://pastebin.com/rJZPQdjT](https://pastebin.com/rJZPQdjT)

### System Configuration

CPU: 
`AMD Ryzen 5 3600 (12) @ 3.600GHz`
GPU: 
`NVIDIA GeForce GTX 1650 SUPER (driver version 525.85.05-1)`
RAM:
`16GB`
OS:
`Arch Linux`
KERNEL: 
`Linux workgroup 6.1.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 18 Jan 2023 19:54:38 +0000 x86_64 GNU/Linux`

VERSION:
`1.0.0`
TITLE ID:
`0100EA80032EA000`

**Comment by gidoly** [comment]
Closing due to have piracy evidence on log

**Comment by Nevro** [comment]
Problem fixed with v3333, thanks!
