### ISSUE TITLE
Harvestella Prologue Demo crashing

### ISSUE THREAD

**Issue by piplup55** [yuzu-emu/yuzu#9669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3327, HEAD-7dade6a

### Description of Issue

Harvestella will crash with multiple sigsegv's if using gdb

### Expected Behavior

![image](https://user-images.githubusercontent.com/100526773/214496006-e86ea8f9-f2b3-4202-bd0b-c79d786bb347.png)

### Reproduction Steps

open the game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10496759/yuzu_log.txt)
[backtrace.txt](https://github.com/yuzu-emu/yuzu/files/10496807/backtrace.txt)

### System Configuration

CPU: Ryzen 3700X
GPU/Driver: RX 6600 XT, mesa 22.3.2, radv 22.3.2
RAM: 64GB
OS: Arch Linux

**Comment by RinMaru** [comment]
https://github.com/yuzu-emu/yuzu/issues/9201 same issue

**Comment by RinMaru** [comment]
still broken here
