### ISSUE TITLE
Implementing unimplemented code for "video_core"?

### ISSUE THREAD

**Issue by YukiIkimura** [yuzu-emu/yuzu#9700]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What feature are you suggesting?

(sorry for my bad english it there's any lol)

Since quite a lot of software, especially newer one, at some point tries to use video/rendering-related uninplemented code (this is both for Vulkan and OpenGL), isn't it worth trying to inplement some if not every uninplemented code from "video_core"?(since i'm pretty sure it's where most of the uninplented code is documented)
also since i'm requesting this myself, i also want to help and contribute in any way i can from this, by testing Yuzu and emulated software related behavior, testing only since i'm not pratically really good at coding, i put all myself in theoric way though, so i think i still can find out if there are any problems with the unimplemented code if  it's getting implemented trough the log console.

just dm me on discord for easier comunication: Yuki Ikimura # 8384
happy to finally help contributing to this great project! :3

i will also update this issue page based on what i found out after testing, so whoever texts me for testing implemented code should check it out in order to see if it works well or not.

Also, it would be even greater (and easier to test obviously) if the log console actually specifies the inplemented code the software tried to use, but it's still ok even without this.

### Why would this feature be useful?

i think this will make better use of th currently available GPU/Video APIs by a lot for Yuzu, and it will obviously make software, especially if newer, to be emulated even better and make it actually playable even beyond where it usually crashes in any way because of this specific critical error.

**Comment by FearlessTobi** [comment]
Thanks for your interest in helping out with yuzu! :)
If you want to contribute to the project, I suggest reaching out in the development channel on our Discord.
However please keep in mind that many of these "unimplemented codes" in the video_core being logged are either due to us missing information on what exactly they are supposed to do or them not being easy to implement.

I will close this issue for now, as such discussion is better suited for our Discord.
