### ISSUE TITLE
Hyrule Warriors: Age of Calamity image artifacts on volcano map

### ISSUE THREAD

**Issue by Graliv** [yuzu-emu/yuzu#9712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1326

### Description of Issue

When playing any Death Mountain maps artifacts will appear on the screen regardless the GPU accuracy. Triggering any cutscene like using the special attack at the end of the video will clear the artifacts until it happens again.

### Expected Behavior

Normal playthrough without image artifacts.

### Reproduction Steps

![age0](https://user-images.githubusercontent.com/7663874/216028327-c832a85f-9ad5-408e-8fdd-b2af1011b0df.PNG)
![age1](https://user-images.githubusercontent.com/7663874/216028341-1abb8d0f-b73b-4d38-80d0-8a88405df2b6.PNG)
![age3](https://user-images.githubusercontent.com/7663874/216028356-ebbd60b1-d8d5-49d1-9ef0-f9e9d3fb81e0.PNG)

https://user-images.githubusercontent.com/7663874/216027170-ade955f0-aebe-48d6-87f0-5883fe34899c.mp4

### System Configuration

CPU:  Intel® Core™ i5-4670 3.4Ghz
GPU/Driver: GPU AMD Radeon RX 580 8GB - Adrenaline 22.11.2
RAM: 16GB
OS: Windows 10
Vulkan API

**Comment by bearswithgunss** [comment]
same.
