### ISSUE TITLE
Yuzu crashes while trying to run Smash Ultimate on Fedora with Vulkan

### ISSUE THREAD

**Issue by efeme4** [yuzu-emu/yuzu#9723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3359

### Description of Issue

Yuzu crashes after the emulator loading screen with an unknown error which I hope the log details correctly. It caused when using vulkan and no combination of settings seems to make it work. I got this error using the early access version, but the stable and flatpak version all suffer the same issue. The game used to run fine on previous versions but know it just doesn't work. Any other game runs just fine.

### Expected Behavior

The game starts and runs normally

### Reproduction Steps

Starting the game with Vulkan with any combination of settings settings and any Linux version of Yuzu.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10579978/yuzu_log.txt)

### System Configuration

CPU: Intel Core i7 1165G7
GPU/Driver: Intel Iris Xe
RAM: 8 GB
OS: Fedora 37 Workstation (Using Wayland)

**Comment by Kaduo** [comment]
I get the same error with the same configuration when trying to run Mario Kart 8 Deluxe on Arch (using X).

**Comment by efeme4** [comment]
I don't exactly know how but this error no longer happens, so I'm closing this issue
