### ISSUE TITLE
No graphic output in vulkan with multiple games

### ISSUE THREAD

**Issue by M4rtinOF** [yuzu-emu/yuzu#9724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3361

### Description of Issue

I use the Amermine Zone drivers with vulkan renderer, i open any game and the screen of the emulator it's black, the audio of the game is playing in the back. Sadly the screenshot it's bugged and i can't fix it for some reason but i got a screenshot from the screenshot:

![imagen](https://user-images.githubusercontent.com/87820680/216714433-afa72d08-edcd-4325-b0ea-8a65e6fc23b8.png)

Original image:

![black screen](https://user-images.githubusercontent.com/87820680/216714465-cdbc8087-1d5d-4a54-979b-c2354d530a2f.png)

I know it's most likely to be an issue from the driver, but just to be sure i will report it

### Expected Behavior

It should show some video output

### Reproduction Steps

1. Open yuzu
2. Select "Vulkan" as graphical renderer
3. Open any game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10582921/yuzu_log.txt)

### System Configuration

CPU: I5 10600KF
GPU/Driver: RX 580 2048SP Amermine 22.3.1
RAM: 16GB DDR5 2400MHZ
OS: Windows 11

**Comment by liamwhite** [comment]
Does it work with the official AMD drivers for Polaris? If so, I would suggest filing a bug report for Amernime instead of here.

**Comment by M4rtinOF** [comment]
Yeah it worked with the original drivers, sorry i don't know how this works
