### ISSUE TITLE
Are you still optimizing ns sports?

### ISSUE THREAD

**Issue by Anonymity-0** [yuzu-emu/yuzu#9738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

When I use yuzu to run ns sports, the image will display a black screen. I have seen your records show that you want to adapt to this game. Are you still continuing? What's the progress?

### Why would this feature be useful?

I really want to emulate this game

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
For information about a specific games status please ask on our Discord or take a look at our compatibility list.

**Comment by gidoly** [comment]
Game is still on our todo list, but this game requires really complex shader to support so it will take a while
