### ISSUE TITLE
FINAL FANTASY CRYSTAL CHRONICLES Remastered Edition zero fps while loading save since EA3084

### ISSUE THREAD

**Issue by Ryan2603** [yuzu-emu/yuzu#9743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA3084 to EA3365

### Description of Issue

zero fps crashed while loading game save , since EA3084 to now, (can't find EA3083 to test)

exact same setting to EA3081 and below older version was loaded flawless.

### Expected Behavior

loading flawless

### Reproduction Steps

everytime save loading

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10677025/yuzu_log.txt)

### System Configuration

CPU: amd 5700x
GPU/Driver: nvidia 3600ti
RAM: 64gb
OS: win11

**Comment by liamwhite** [comment]
Possible cause: #9173

**Comment by bunnei** [comment]
Thanks for reporting! Should be fixed by #9773.

**Comment by Ryan2603** [comment]
> Thanks for reporting! Should be fixed by #9773.

thank you all guys hard work, bug solved.
