### ISSUE TITLE
Game Crashes on Load

### ISSUE THREAD

**Issue by plasticocelot123** [yuzu-emu/yuzu#9745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1324

### Description of Issue

I was playing Super Mario Odyssey on Yuzu. I was at the point where I was playing the cutscene to go to Ruined Kingdom. When the cutscene started, my game suddenly crashed. I attempted to reopen Yuzu and start up the game. Instead of saying "Building Shaders" like I was used to, the screen said "Loading.." then Yuzu crashed. I don't know if this is a problem that my computer is having, because I am running on a laptop as of current, or if it is a bug with Yuzu. Please fix this. If there is a way to fix it, does anyone know how? I can't install other games because of storage running out. I am also set to use Vulkan.

### Expected Behavior

It should start up and say "Building Shaders" then say "Launching..." after that is done, the game starts.

### Reproduction Steps

Can't reproduce, but have save file data here: 
[Save.zip](https://github.com/yuzu-emu/yuzu/files/10680538/Save.zip)

### Log File

Can't Find it.

### System Configuration

CPU: I don't know
GPU/Driver: I don't know
RAM: 12.0 GB (11.3 GB usable)
OS: Win11

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/help/reference/log-files/ For guide on log file. Please provide one when you can.

**Comment by plasticocelot123** [comment]
Log file here: 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10680630/yuzu_log.txt)

**Comment by G-Spawn** [comment]
that seems to be a log of just you opening yuzu and closing it not entirely relevant to issue. See if you generate a better log after you crash again and close yuzu 🙏

**Comment by plasticocelot123** [comment]
Sorry I didnt know that Yuzu generated a new log after opening and closing Yuzu. Here is the updated log (I hope): 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10680659/yuzu_log.txt)

**Comment by plasticocelot123** [comment]
I just found something: I tried to dump the RomFS and all that was in the folder was EffectData. I believe that because the other folders are missing, that crashes the game. Is that what you guys think too? Let me know of a way to fix this.

**Comment by G-Spawn** [comment]
dumping romfs of a large game requires exactly that amount of space free in order to dump it all properly. You're also using old gpu drivers. This issue would be best handled on Discord vs the issue tracker as it falls into general support. https://discord.gg/u77vRWY
