### ISSUE TITLE
Game crashes on Start (MK8D)

### ISSUE THREAD

**Issue by bobdig** [yuzu-emu/yuzu#9748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1332

### Description of Issue

Game crashes in the loading screen. According to the log it seems related to the game hosted on a SMB-Share. Now with a local copy on device it seems to run fine. It has worked before with no problem though. 

### Expected Behavior

*

### Reproduction Steps

Just starting the game

### Log File

[yuzu_log.txt.old.zip](https://github.com/yuzu-emu/yuzu/files/10684856/yuzu_log.txt.old.zip)

### System Configuration

CPU:Ryzen7 5800H
GPU/Driver:3060 Laptop, newest
RAM: 32Gigs
OS: Win10

**Comment by G-Spawn** [comment]
>  it seems related to the game hosted on a SMB-Share
https://github.com/yuzu-emu/yuzu/issues/9283
