### ISSUE TITLE
Cant launch  Pixel Cup Soccer Ultimate Edition (64-bit)

### ISSUE THREAD

**Issue by Walter-Jucah** [yuzu-emu/yuzu#9752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3533 

### Description of Issue

Using a fresh install of yuzu, it gets stuck at “launching…” I dont know what to do.

Ryujin is working fine with the same FW and keys

### Expected Behavior

it should load any game

### Reproduction Steps

Just click on game, it should load but it wont

### Log File

[   0.176306] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.176320] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.209111] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.230366] Frontend <Info> yuzu\main.cpp:GMainWindow:354: yuzu Version: yuzu Early Access 3353
[   0.230381] Frontend <Info> yuzu\main.cpp:LogRuntimes:235: MSVC Compiler: 1934 Runtime: 14.32.31332.0
[   0.230382] Frontend <Info> yuzu\main.cpp:LogRuntimes:244: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.230384] Frontend <Info> yuzu\main.cpp:GMainWindow:370: Host CPU: AMD Ryzen 5 5600G with Radeon Graphics          | AVX2 | FMA
[   0.230388] Frontend <Info> yuzu\main.cpp:GMainWindow:372: Host CPU Cores: 6
[   0.230389] Frontend <Info> yuzu\main.cpp:GMainWindow:375: Host CPU Threads: 12
[   0.230500] Frontend <Info> yuzu\main.cpp:GMainWindow:376: Host OS: Windows 10 Version 22H2 (Build 19045.2486)
[   0.230511] Frontend <Info> yuzu\main.cpp:GMainWindow:378: Host RAM: 15.37 GiB
[   0.230512] Frontend <Info> yuzu\main.cpp:GMainWindow:379: Host Swap: 5.75 GiB
[ 103.699298] Frontend <Info> yuzu\main.cpp:BootGame:1662: yuzu starting...
[ 103.713153] Config <Info> common\settings.cpp:LogSettings:40: yuzu Configuration:
[ 103.713157] Config <Info> common\settings.cpp:operator ():33: Controls_UseDockedMode: true
[ 103.713158] Config <Info> common\settings.cpp:operator ():33: System_RngSeed: 0
[ 103.713158] Config <Info> common\settings.cpp:operator ():33: System_DeviceName: Yuzu
[ 103.713159] Config <Info> common\settings.cpp:operator ():33: System_CurrentUser: 0
[ 103.713159] Config <Info> common\settings.cpp:operator ():33: System_LanguageIndex: 1
[ 103.713159] Config <Info> common\settings.cpp:operator ():33: System_RegionIndex: 1
[ 103.713160] Config <Info> common\settings.cpp:operator ():33: System_TimeZoneIndex: 0
[ 103.713161] Config <Info> common\settings.cpp:operator ():33: Core_UseMultiCore: true
[ 103.713162] Config <Info> common\settings.cpp:operator ():33: CPU_Accuracy: 0
[ 103.713163] Config <Info> common\settings.cpp:operator ():33: Renderer_UseResolutionScaling: 2
[ 103.713163] Config <Info> common\settings.cpp:operator ():33: Renderer_ScalingFilter: 1
[ 103.713164] Config <Info> common\settings.cpp:operator ():33: Renderer_FSRSlider: 25
[ 103.713164] Config <Info> common\settings.cpp:operator ():33: Renderer_AntiAliasing: 0
[ 103.713165] Config <Info> common\settings.cpp:operator ():33: Renderer_UseSpeedLimit: true
[ 103.713165] Config <Info> common\settings.cpp:operator ():33: Renderer_SpeedLimit: 100
[ 103.713166] Config <Info> common\settings.cpp:operator ():33: Renderer_UseDiskShaderCache: true
[ 103.713166] Config <Info> common\settings.cpp:operator ():33: Renderer_GPUAccuracyLevel: 1
[ 103.713166] Config <Info> common\settings.cpp:operator ():33: Renderer_UseAsynchronousGpuEmulation: true
[ 103.713167] Config <Info> common\settings.cpp:operator ():33: Renderer_NvdecEmulation: 2
[ 103.713167] Config <Info> common\settings.cpp:operator ():33: Renderer_AccelerateASTC: true
[ 103.713167] Config <Info> common\settings.cpp:operator ():33: Renderer_UseVsync: true
[ 103.713168] Config <Info> common\settings.cpp:operator ():33: Renderer_ShaderBackend: 0
[ 103.713168] Config <Info> common\settings.cpp:operator ():33: Renderer_UseAsynchronousShaders: false
[ 103.713169] Config <Info> common\settings.cpp:operator ():33: Renderer_AnisotropicFilteringLevel: 0
[ 103.713169] Config <Info> common\settings.cpp:operator ():33: Audio_OutputEngine: auto
[ 103.713170] Config <Info> common\settings.cpp:operator ():33: Audio_OutputDevice: auto
[ 103.713170] Config <Info> common\settings.cpp:operator ():33: Audio_InputDevice: auto
[ 103.713170] Config <Info> common\settings.cpp:operator ():33: DataStorage_UseVirtualSd: true
[ 103.713172] Config <Info> common\settings.cpp:operator ():37: DataStorage_CacheDir: C:\Users\Walter\AppData\Roaming\yuzu\cache
[ 103.713173] Config <Info> common\settings.cpp:operator ():37: DataStorage_ConfigDir: C:\Users\Walter\AppData\Roaming\yuzu\config
[ 103.713173] Config <Info> common\settings.cpp:operator ():37: DataStorage_LoadDir: C:\Users\Walter\AppData\Roaming\yuzu\load
[ 103.713174] Config <Info> common\settings.cpp:operator ():37: DataStorage_NANDDir: C:\Users\Walter\AppData\Roaming\yuzu\nand
[ 103.713175] Config <Info> common\settings.cpp:operator ():37: DataStorage_SDMCDir: C:\Users\Walter\AppData\Roaming\yuzu\sdmc
[ 103.713175] Config <Info> common\settings.cpp:operator ():33: Debugging_ProgramArgs: 
[ 103.713176] Config <Info> common\settings.cpp:operator ():33: Debugging_GDBStub: false
[ 103.713176] Config <Info> common\settings.cpp:operator ():33: Input_EnableMotion: true
[ 103.713177] Config <Info> common\settings.cpp:operator ():33: Input_EnableVibration: true
[ 103.713177] Config <Info> common\settings.cpp:operator ():33: Input_EnableRawInput: false
[ 103.804014] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:680: Device doesn't support extension VK_EXT_extended_dynamic_state3
[ 103.804027] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:747: Device doesn't support feature shaderFloat16
[ 103.804053] Render.Vulkan <Warning> video_core\vulkan_common\vulkan_device.cpp:Device:370: Volta and older have broken VK_KHR_push_descriptor
[ 103.804055] Render.Vulkan <Warning> video_core\vulkan_common\vulkan_device.cpp:Device:377: NVIDIA Drivers >= 510 do not support MSAA image blits
[ 103.980363] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:182: Driver: NVIDIA 512.95.0.0
[ 103.980368] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:183: Device: NVIDIA GeForce GTX 1060 6GB
[ 103.980369] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:184: Vulkan: 1.3.194
[ 103.980372] Render.Vulkan <Info> video_core\renderer_vulkan\renderer_vulkan.cpp:Report:185: Available VRAM: 5.37 GiB
[ 103.988261] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[ 103.998941] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[ 104.196494] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:128: Patching ExeFS for title_id=0100E17019782000
[ 104.196790] Loader <Info> core\file_sys\patch_manager.cpp:PatchExeFS:175:     ExeFS: LayeredExeFS patches applied successfully
[ 104.466318] Debug <Critical> core\hle\kernel\k_process.cpp:operator ():361: Assertion Failed!
Unimplemented code!
[ 104.467045] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:299: Querying NSO patch existence for build_id=8E405C8A464734D8F71C2C1BE2DAC518010E86FB
[ 104.679732] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:299: Querying NSO patch existence for build_id=EE69F69753AE9883CC07880C85456456
[ 104.728742] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:299: Querying NSO patch existence for build_id=C781DD63DAF0DDCDB9975DA50A198F932A485719
[ 104.765926] Loader <Info> core\file_sys\patch_manager.cpp:HasNSOPatch:299: Querying NSO patch existence for build_id=2AEF2CFFB104EE7C9E212FD2F4C731E9D1E5F2C4
[ 104.841214] Frontend <Info> yuzu\main.cpp:BootGame:1773: Booting game: 0100E17019782000 | Pixel Cup Soccer Ultimate Edition (64-bit) | 0
[ 104.842395] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:LoadVulkanPipelineCache:801: Loaded Vulkan driver pipeline cache: 
[ 104.842482] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:LoadDiskResources:505: Total Pipeline Count: 0
[ 104.842698] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:SerializeVulkanPipelineCache:744: Vulkan driver pipelines cached at: C:\Users\Walter\AppData\Roaming\yuzu\shader\0100e17019782000\vulkan_pipelines.bin
[ 104.976872] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[ 104.982981] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[ 104.988930] Service.AM <Warning> core\hle\service\am\am.cpp:SetRequestExitToLibraryAppletAtExecuteNextProgramEnabled:863: (STUBBED) called
[ 104.990568] Service.AM <Warning> core\hle\service\am\am.cpp:GetGpuErrorDetectedSystemEvent:1784: (STUBBED) called
[ 104.995321] Service.AM <Warning> core\hle\service\am\am.cpp:AcquireForegroundRights:92: (STUBBED) called
[ 104.995768] Service.AM <Warning> core\hle\service\am\am.cpp:SetFocusHandlingMode:432: (STUBBED) called. unknown0=0, unknown1=0, unknown2=1
[ 104.996208] Service.AM <Warning> core\hle\service\am\am.cpp:SetOutOfFocusSuspendingEnabled:451: (STUBBED) called enabled=false
[ 104.997956] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[ 105.000383] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[ 105.001625] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[ 105.003436] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[ 105.003590] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[ 105.176606] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[ 105.180564] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[ 105.200926] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:Initialize:153: (STUBBED) called
[ 105.203061] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:SetAruid:193: (STUBBED) called, pid=0x51
[ 105.203771] Service.NVDRV <Warning> core\hle\service\nvdrv\nvdrv_interface.cpp:SetGraphicsFirmwareMemoryMarginEnabled:201: (STUBBED) called
[ 105.207011] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetManagerDisplayService:455: (STUBBED) called
[ 105.207722] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetSystemDisplayService:447: (STUBBED) called
[ 105.208166] Service.VI <Warning> core\hle\service\vi\vi.cpp:GetRelayService:439: (STUBBED) called
[ 105.214750] Service.AM <Warning> core\hle\service\am\am.cpp:SetRestartMessageEnabled:439: (STUBBED) called
[ 105.214942] Service.AM <Warning> core\hle\service\am\am.cpp:SetPerformanceModeChangedNotification:413: (STUBBED) called flag=true
[ 105.215132] Service.AM <Warning> core\hle\service\am\am.cpp:SetOperationModeChangedNotification:403: (STUBBED) called flag=true
[ 105.229221] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:419: Patching RomFS for title_id=0100E17019782000, type=01
[ 105.232571] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:419: Patching RomFS for title_id=0100E17019782000, type=01
[ 105.236015] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1542: (STUBBED) called, result=0x00217202
[ 105.236132] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:696: Userspace PANIC! info1=0x000000100E503A28, info2=0x0000000000000004
[ 105.236136] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:operator ():677: debug_buffer_err_code=217202
[ 105.236140] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:746: Emulated program broke execution! reason=0x0000000000000000, info1=0x000000100E503A28, info2=0x0000000000000004
[ 105.236142] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:82: Backtrace, sp=000000100E503870, pc=000000000D659B44
[ 105.236144] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:84: Module Name         Address             Original Address    Offset              Symbol
[ 105.236145] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:85: 
[ 105.296132] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 0000007100158B44    000000000D659B44    0000000000158B44    
[ 105.296138] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 000000710008F108    000000000D590108    000000000008F108    nn::diag::detail::Abort(nn::Result const*)
[ 105.296139] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 000000710008D8B8    000000000D58E8B8    000000000008D8B8    
[ 105.296139] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 000000710008D97C    000000000D58E97C    000000000008D97C    
[ 105.296140] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 00000071000D652C    000000000D5D752C    00000000000D652C    nn::fs::MountRom(char const*, void*, unsigned long)
[ 105.296141] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: main                000000710068CB30    0000000008690B30    000000000068CB30    nnMain
[ 105.296143] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: sdk                 00000071000FA414    000000000D5FB414    00000000000FA414    nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
[ 105.296144] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:90: rtld                00000071000000D4    00000000080000D4    00000000000000D4    

### System Configuration

Host CPU: AMD Ryzen 5 5600G with Radeon Graphics          | AVX2 | FMA
Host CPU Cores: 6
Host CPU Threads: 12
Host OS: Windows 10 Version 22H2 (Build 19045.2486)
Host RAM: 15.37 GiB
Host Swap: 5.75 GiB

**Comment by FearlessTobi** [comment]
This boots now.
