### ISSUE TITLE
Super Mario Odyssey Web Applet does not resize to Window anymore.

### ISSUE THREAD

**Issue by popdoo323-pop** [yuzu-emu/yuzu#9756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1329 To Mainline 1335

### Description of Issue

This Issue seems to occur in the most recent mainline versions after Mainline 1327 of the emulator. where the Menu/Web Applet seems to be staying in this small size on the top left corner.
Mainline 1329 & 1335:
![Yuzu1329 1335](https://user-images.githubusercontent.com/85776019/217971092-f63ae8cf-63a6-42a8-b622-c8418759e43c.jpg)

### Expected Behavior

You're expected to see this in web applet mode before the bug.
Mainline 1327:
![Yuzu1327](https://user-images.githubusercontent.com/85776019/217970704-fba56efd-d476-4f69-a7c9-e29ca3e198f8.jpg)

### Reproduction Steps

Loading into the action guide at any point it's available in the game.

### Log File

[yuzu_logMainline1329.txt](https://github.com/yuzu-emu/yuzu/files/10702688/yuzu_logMainline1329.txt)
[yuzu_logMainline1335.txt](https://github.com/yuzu-emu/yuzu/files/10702689/yuzu_logMainline1335.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
GPU: NVIDIA GeForce RTX 3070 Ti
GPU Driver Version: 31.0.15.2756
RAM: 32 GBs
OS: Windows 10

**Comment by Morph1984** [comment]
This could be attributed to the High DPI fixes I recently implemented. What is the resolution of your screen and the scaling ratio?

**Comment by popdoo323-pop** [comment]
The screen resolution was scaled down to 1920 x 1080 when the screenshots were taken to check if the issue persisted.
but it's usually 2560 x 1440 & 16:9
