### ISSUE TITLE
Moero crystal H graphic issue report by user.

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#9762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3378

### Description of Issue

Games seems to now booting with kernel change from ea. however user reported me that game has rendering issue that makes game unplayable.

First issue is that 2D element such as menu would not render correctly.

![image](https://user-images.githubusercontent.com/66776795/218052226-f2b3edfb-df9b-4a56-80a3-1938eaacec06.png)

Second issue is games frame would flicker rapidly while skip cutscene with fast foward mode.

https://user-images.githubusercontent.com/66776795/218052512-9aa0c753-1e18-4ffc-b44e-db0056fa9ddd.mp4

### Expected Behavior

Here is the pic of expected behavior of  first issue

![image](https://user-images.githubusercontent.com/66776795/218052856-dd39258e-9aed-42ee-b9ae-22b5425bf3f5.png)

second issues expected behavior would be not flicking whiole use fast foward mode of cutscene.
not posting video as it is pretty clear that how it should look.

### Reproduction Steps

2d element issue should be can face right after boot game and start new one

2nd issue should be also reproducable by starting new game.

### Log File

[yuzu_log (12).txt](https://github.com/yuzu-emu/yuzu/files/10705735/yuzu_log.12.txt)

### System Configuration

CPU: i7 12700H
GPU/Driver: 3060 laptob GPU/ 527.37 driver
RAM: 16gb with 8 gb of page file
OS: windows 11

**Comment by ihachani** [comment]
I can confirm the same issue

### Affected Build(s)

yuzu 1352 (26-02-2023)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10843290/yuzu_log.txt)

### System Configuration

CPU:  AMD 5950x
GPU/Driver: RTX 3090 driver 528,02
RAM: 64gb
OS: windows 10 build 19045.2604
