### ISSUE TITLE
Spongebob The Cosmic Shake inverted coloured

### ISSUE THREAD

**Issue by piplup55** [yuzu-emu/yuzu#9763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3378

### Description of Issue

The game inverts it colours when switching between handheld and docked https://youtu.be/2eq6E3vftXY
![image](https://user-images.githubusercontent.com/100526773/218059370-f2c79957-6312-41c3-aca6-457d02f575be.png)

### Expected Behavior

the game should not do this, (tbh i don't know what else you want me to say)

### Reproduction Steps

switch handheld and back

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10705987/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7 3700X
GPU/Driver: AMD RX 6600 XT
RAM: 64gb
OS: Arch Linux

**Comment by vonchenplus** [comment]
Fixed by #11278 and #10818
