### ISSUE TITLE
Yuzu keep crashing always  in the start of the game. 

### ISSUE THREAD

**Issue by tommy-sorce** [yuzu-emu/yuzu#9774]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Mainline 1335

### Description of Issue

Yuzu crashes in the begining of the game (Persona 5 royal and Catharine full body) 

### Expected Behavior

Yuzu will completely crash

### Reproduction Steps

Idk

### Log File

[ 36.456283] Service.AM <Warning>
core\hle\service\am\am.cpp:SetGamePlayRecordingState:1656: (STUBBED) called
[ 37.422296] Service.AM <Warning>
core\hle\service\am\am.cpp:SetGamePlayRecordingState:1656: (STUBBED) called
[ 88.580919] Service.NVDRV <Info>
core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:OnOpen:71: NVDEC video stream started
[ 88.589499] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:Initialize:65:
(STUBBED) called
[ 88.643890] Service.NVDRV <Info>
core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:OnOpen:71: NVDEC video stream started
[ 88.644357] Service.NVDRV <Warning>
core\hle\service\nvdrv\devices\nvhost_nvdec_common.cpp:SetSubmitTimeout:178:
(STUBBED) called
[ 88.705456] Service.NVDRV <Info>
video_core\host1x\codecs\codec.cpp:SetTargetCodec:203: NVDEC video codec initialized to
VP9
[ 88.733077] Service.NVDRV <Info>
video_core\host1x\codecs\codec.cpp:CreateGpuAvDevice:143: Using d3d11va GPU
decoder
[ 88.735058] Service.NVDRV <Info>
video_core\host1x\codecs\codec.cpp:GetGpuFormat:53: Could not find compatible GPU AV
format, falling back to CPU
[ 88.776504] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame
dimensions 1920x1080 don't match surface dimensions 1920x1088
[ 88.801032] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame
dimensions 1920x1080 don't match surface dimensions 1920x1088
[ 88.818221] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame
dimensions 1920x1080 don't match surface dimensions 1920x1088
[ 88.828740] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame
dimensions 1920x1080 don't match surface dimensions 1920x1088
[ 88.841888] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame
dimensions 1920x1080 don't match surface dimensions 1920x1088
[ 88.846356] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame
dimensions 1920x1080 don't match surface dimensions 1920x1088
(...)
[ 114.694534] Service.NVDRV <Warning> video_core\host1x\vic.cpp:Execute:96: Frame
dimensions 1920x1080 don't match surface dimensions 1920x1088
[ 114.747853] Service.NVDRV <

### System Configuration

CPU: i5 4670k
GPU/Driver: AMD Radeon r7 260x 22.6.1 adrenaline 
RAM: 12gb 
OS: windows 10 22h2 build 19045

**Comment by goldenx86** [comment]
AMD discontinued support for old GCN cards like yours, Linux is your only option for yuzu.
