### ISSUE TITLE
Nintendo Switch Sports crashes

### ISSUE THREAD

**Issue by Jassemm** [yuzu-emu/yuzu#9775]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

1327

### Description of Issue

Game crashes in main menu

### Expected Behavior

the game will load without issue, and as soon as reaches main menu, game freezes then yuzu crashes.

### Reproduction Steps

On Ryujinx build 1.1.0, it works (rare crashes sometimes)

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10713603/yuzu_log.txt.old.txt)

### System Configuration

CPU: 9700K
GPU/Driver: 3090 latest driver
RAM: 32 GB
OS: W11

**Comment by G-Spawn** [comment]
We don't support pirates here. Closing issue.
