### ISSUE TITLE
Xenoblade Chronicles 3 V1.2.1 - Yuzu app crashes before title screen with AMD GPU+Vulkan

### ISSUE THREAD

**Issue by RomanJ55** [yuzu-emu/yuzu#9779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3378

### Description of Issue

I cannot run the game past the initial loading screen. Before the title screen appears the Yuzu app just crashes. I know it says on your website that XL3 is untested and works best with Open GL but my CPU+GPU arent capable of running anything well with OpenGL. I tried a different Emulator(Ryu****) and the game works there just fine under Vulkan.(it has other issues tho which make me not want to use it). I have the "Bloom/Brightness Bug Workaround Mod" from the yuzu website but so I'm wondering if its my hardware or a setting that I'm missing?

### Expected Behavior

Game should load and the Yuzu app should not crash

### Reproduction Steps

Start XL3 with a AMD GPU under Vulkan. 

### Log File

Dont have a log file atm, but can provide if needed.

### System Configuration

CPU: AMD Ryzen 5 1600 AF
GPU/Driver: ASUS R9 270X(R9270X-DC2T-2GD5) / 22.6.1
RAM: 2X 8GB Gskill DDR4 CL16 3200(F4-3200-C16-8GVKB)
OS: Windows 10 21H2(Build 19044.2486)

**Comment by liamwhite** [comment]
Provide the log file

**Comment by liamwhite** [comment]
Actually, see here: https://github.com/yuzu-emu/yuzu/issues/9774#issuecomment-1426635259

This card is out of support now and there's nothing we can do.

**Comment by RomanJ55** [comment]
Hi liamwhite! Do you want the logfile anyway? It just feels strange to me that XL3 works fine with other emulators but not with yuzu. If it's hardware thing it would not run on either, would it?

**Comment by liamwhite** [comment]
It's not a hardware issue as yuzu runs fine on Linux with the Mesa driver for GCN -- it's that AMD doesn't bother backporting new Vulkan features which yuzu uses for newer games to these cards anymore. Because this is a crash internal to the GPU driver, the log file is unlikely to report anything interesting.

**Comment by RomanJ55** [comment]
Oh ok, gotcha. Thank you anyway :)
