### ISSUE TITLE
Mouse to Gyro Conversion/Emulation 

### ISSUE THREAD

**Issue by tekgeekster** [yuzu-emu/yuzu#9791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Had the idea, what if there was mouse to gyro translation/emulation. 

### Why would this feature be useful?

Would be great for fans of stuff like primehack, but you won't be limited to one game, you could play any gyro capable game with mouse and keyboard, and would make steam input or other input mappers much easier to manage. 

No more having to go back to desktop mode just to switch which controller's gyroscope is being read, either. Especially on steam deck.

Mouse and Gyro go hand in hand as 1:1 input translation when aiming in fps. So much so, that pc gamers (myself included) frequently use input remapping software to have a controllers gyroscope behave as a mouse, and it works very well. 

Of course, this would probably only be viable for aiming in shooters. The puzzles in breath of the wild would fall apart without some other translation to emulate yaw, or roll since mouse technically only supports to axis, where as gyroscopes can support roughly 6 axis.

**Comment by G-Spawn** [comment]
https://yuzu-emu.org/entry/yuzu-progress-report-jan-2022/ This is already satisfied within reason. It just is janky compared to controllers that provide actual motion/gyro. It was a part of project kraken https://github.com/yuzu-emu/yuzu/pull/7725

**Comment by goldenx86** [comment]
Mea culpa.
