### ISSUE TITLE
Metroid Prime Remastered Water Effect Broken

### ISSUE THREAD

**Issue by DaSk79130569** [yuzu-emu/yuzu#9794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA current build (3394)

### Description of Issue

while in other areas water looks fine,
water in phendrana drifts area does not appear correctly

![pic](https://user-images.githubusercontent.com/81931582/218351872-740ea8f7-ad17-4700-ab2f-7a35e787c1f4.png)

### Expected Behavior

Water should appear normally

### Reproduction Steps

Phendrana Drifts region
When first visiting this area from Magmoor caverns
In big area near first save point in that location called Phendrana Shorelines
Water effect does not appear correctly

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10717926/yuzu_log.txt)

### System Configuration

CPU: 12900k
GPU/Driver: geforce 4090 / latest driver
RAM: 32 GB DDR5
OS: Win11 64

**Comment by FernandoS27** [comment]
can you provide a save?

**Comment by german77** [comment]
We don't provide support to piracy
