### ISSUE TITLE
Hashihime of Old Book Town Shows ??? instead of Japanese text

### ISSUE THREAD

**Issue by kanjieater** [yuzu-emu/yuzu#9799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1263 mainline

### Description of Issue

![image](https://user-images.githubusercontent.com/32607317/218584878-63925894-a85f-4ed7-b2fb-a6cc1f5369e4.png)
Japanese & other languages load question marks instead of text. 

### Expected Behavior

The words should show instead of ???

### Reproduction Steps

1. Load the game, skip through the intro where animated text works.
2. ???.
3. Profit. Pun intended.

![image](https://user-images.githubusercontent.com/32607317/218584986-8c7bbb5b-6cdf-47b8-9c07-e622752aee0a.png)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10726709/yuzu_log.txt)

### System Configuration

CPU: 13900ks
GPU/Driver: 4070ti
RAM: 32GB
OS: Win11

**Comment by german77** [comment]
Piracy is not allowed.
