### ISSUE TITLE
Metroid Prime Remastered Texture Filtering Not Working Correctly

### ISSUE THREAD

**Issue by jon-mil-92** [yuzu-emu/yuzu#9800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All recent early access builds.

### Description of Issue

The texture filtering settings that are selected in the options do not apply to this game. There is a hard falloff in texture quality after a certain distance regardless of the texture filtering setting used.

### Expected Behavior

Yuzu:

![Image00002](https://user-images.githubusercontent.com/111253795/218599454-646f6ffe-e90c-461f-9c4c-4663f31d26da.jpg)

Ryujinx (No texture filtering issue):

![Image00001](https://user-images.githubusercontent.com/111253795/218599479-784b9a8b-3a7e-4488-8920-10d916b07395.jpg)

### Reproduction Steps

No reproduction steps. The error just occurs.

Below is a save file that can be used to quickly see the issue. Simply walk out of the door, stay in the doorway to kill the three flying enemies, and then stand on the following platform area to clearly see the texture filtering bug.
[save.zip](https://github.com/yuzu-emu/yuzu/files/10727205/save.zip)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10727196/yuzu_log.txt)

### System Configuration

CPU: 5800X3D
GPU/Driver: 6900 XT / 22.11.2
RAM: 32 GB 4400 MHz CL 17 DDR4 G.Skill TridentZ
OS: Windows 10 x64

**Comment by NineKain** [comment]
Can confirm I also noticed this, mipmapping/aniso seems to just dont work

3060ti + 5600x latest drivers
