### ISSUE TITLE
Story of seasons wonderful life visual glitch

### ISSUE THREAD

**Issue by Rollercoasterwater** [yuzu-emu/yuzu#9805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 1154

### Description of Issue

There are there lines that appear everywhere at certain times of day in game. Its a universal glitch everyone who trys to run the game on yuzu experiences.

### Expected Behavior

![4b4916c5e7a47384a5afbd7abc285b4c68dce928](https://user-images.githubusercontent.com/80546627/218653141-c176af31-a41e-45ee-90b8-6374c384b2e2.jpeg)

### Reproduction Steps

it happens on title screen and when loading any part of the game. its worse indoors

### Log File

dont know how to get log file

### System Configuration

CPU:
GPU/Driver:nvidia 2070
RAM:8gigs
OS:windows

**Comment by goldenx86** [comment]
Was this tested with native 1X resolution scaling?

**Comment by Rollercoasterwater** [comment]
> Was this tested with native 1X resolution scaling?

Yes and everyone on every forum that im on thats using yuzu is having an identical issue
