### ISSUE TITLE
Disk pipeline cache not working with vulkan

### ISSUE THREAD

**Issue by KhoaiMai** [yuzu-emu/yuzu#9812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 1340 / 2023-02-14

### Description of Issue

When I enable disk pipeline cache when vulkan is selected as the render api, yuzu tries to launch mario kart but instantly crashes and does the same with smash brothers. But when it's enabled with OpenGL it doesn't crash but run really slow.

### Expected Behavior

Run the gam fluently without major lag spikes

### Reproduction Steps

1. Starting yuzu
2. Going to settings and enable disk pipeline cache + selecting vukan the apply it
3. Starting MarioKart 8 deluxe
4. Yuzu trying to start the emulation window
5. 0.5 seconds after it crashes

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10737841/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.59 GHz
GPU: NVidia GeForce 965M /GPU driver: NVidia 31.0.15.2756
RAM: SODIMM DDR4 8Gb 2133 MHz
OS: Windows 10 Family 21H2 build 19044.2486

**Comment by G-Spawn** [comment]
We don't support pirates.
