### ISSUE TITLE
Feature Request:  Add OSD for FPS and Speed

### ISSUE THREAD

**Issue by Daisouji** [yuzu-emu/yuzu#9818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I think there should be an OSD option to display FPS.  

### Why would this feature be useful?

I think it would be better on presentation, and be more in line w/ other emulators.

**Comment by G-Spawn** [comment]
There are def plans to add this in future. Just no eta sadly.

**Comment by NativeGamer081** [comment]
Such a basic feature should've been here from the beginning.

**Comment by G-Spawn** [comment]
> Such a basic feature should've been here from the beginning.

The emulator is open source. Feel free to contribute.
