### ISSUE TITLE
yuzu crash on TGL

### ISSUE THREAD

**Issue by davidbepo** [yuzu-emu/yuzu#9830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1338

### Description of Issue

on vulkan both pokemon sword and legends arceus crash after loading the save terminal shows
Unhandled SIGSEGV at rip 0x00007f6b1c337c29
and
Unhandled SIGSEGV at rip 0x00007ea501537c29
respectively, OpenGL crashes too

### Expected Behavior

games load normally

### Reproduction Steps

load the game and press A to load save

### Log File

how is this obtained?

### System Configuration

CPU: 1165G7
GPU/Driver: Iris Xe, Mesa 22.3.5 ANV/IRIS
RAM: 8GB
OS: Linux(Manjaro)

**Comment by PandaRules** [comment]
Same issue here too

**Comment by G-Spawn** [comment]
@davidbepo  https://yuzu-emu.org/help/reference/log-files/ whenever you can try to include log.

**Comment by davidbepo** [comment]
sorry for late reply, issue still happens, log of crash under vulkan
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11012539/yuzu_log.txt)

**Comment by davidbepo** [comment]
still broken on last version after mesa 23 update

**Comment by davidbepo** [comment]
all works in the last version
