### ISSUE TITLE
Stolen code from Ryujinx

### ISSUE THREAD

**Issue by 11125667980890-9** [yuzu-emu/yuzu#9837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All

### Description of Issue

Stolen code from Ryujinx
https://www.reddit.com/r/emulation/comments/ljxnvi/yuzu_stole_code/
Here is all of the Pull Requests Bunnei stole from them (btw these are all hidden, Bunnei hid them) (https://github.com/yuzu-emu/yuzu/pull/5274) (https://github.com/yuzu-emu/yuzu/pull/5328) (https://github.com/yuzu-emu/yuzu/pull/5830) (https://github.com/yuzu-emu/yuzu/pull/5337) (https://github.com/yuzu-emu/yuzu/pull/5364)

The commit made by Bunnei (https://github.com/yuzu-emu/yuzu/commit/eae9f2e4404f6bdf8a192bc9c09e53cd87e4359d)

### Expected Behavior

No shame and no skill

### Reproduction Steps

No shame and no skill

### Log File

[thieves.txt](https://github.com/yuzu-emu/yuzu/files/10791639/thieves.txt)

### System Configuration

CPU:Thief
GPU/Driver:Thief
RAM:Thief
OS:Thief

**Comment by goldenx86** [comment]
We don't accept contributions from piracy groups.
