### ISSUE TITLE
Link error when system cpp-httplib using

### ISSUE THREAD

**Issue by svalx** [yuzu-emu/yuzu#9840]
### Issue

On Linux build with **cpp-httplib** by package manager installed, I get a linking error - no openssl symbols founded. This patch fixing it. Maybe it should be included in the mainline?

```
Index: yuzu-0.1339/externals/CMakeLists.txt
===================================================================
--- yuzu-0.1339.orig/externals/CMakeLists.txt
+++ yuzu-0.1339/externals/CMakeLists.txt
@@ -103,7 +103,6 @@ add_subdirectory(sirit EXCLUDE_FROM_ALL)
 # httplib
 if (ENABLE_WEB_SERVICE AND NOT TARGET httplib::httplib)
     if (NOT WIN32)
-        find_package(OpenSSL 1.1)
         if (OPENSSL_FOUND)
             set(OPENSSL_LIBRARIES OpenSSL::SSL OpenSSL::Crypto)
         endif()
Index: yuzu-0.1339/CMakeLists.txt
===================================================================
--- yuzu-0.1339.orig/CMakeLists.txt
+++ yuzu-0.1339/CMakeLists.txt
@@ -214,6 +214,7 @@ find_package(nlohmann_json 3.8 REQUIRED)
 find_package(Opus 1.3 MODULE)
 find_package(ZLIB 1.2 REQUIRED)
 find_package(zstd 1.5 REQUIRED)
+find_package(OpenSSL 1.1)

 if (NOT YUZU_USE_EXTERNAL_VULKAN_HEADERS)
     find_package(Vulkan 1.3.238 REQUIRED)
@@ -242,6 +243,9 @@ endif()
 if (ENABLE_WEB_SERVICE)
     find_package(cpp-jwt 1.4 CONFIG)
     find_package(httplib 0.11 MODULE)
+    if (httplib_FOUND AND OPENSSL_FOUND)
+       set(LINK_OPENSSL ON)
+    endif()
 endif()

 if (YUZU_TESTS)
Index: yuzu-0.1339/src/web_service/CMakeLists.txt
===================================================================
--- yuzu-0.1339.orig/src/web_service/CMakeLists.txt
+++ yuzu-0.1339/src/web_service/CMakeLists.txt
@@ -19,6 +19,10 @@ add_library(web_service STATIC
 create_target_directory_groups(web_service)
 target_link_libraries(web_service PRIVATE common network nlohmann_json::nlohmann_json httplib::httplib cpp-jwt::cpp-jwt)

+if (LINK_OPENSSL)
+    target_link_libraries(web_service PRIVATE OpenSSL::SSL OpenSSL::Crypto)
+endif()
+
 if (YUZU_USE_PRECOMPILED_HEADERS)
     target_precompile_headers(web_service PRIVATE precompiled_headers.h)
 endif()
```

**Comment by abouvier** [comment]
What is your distro? The `cpp-httplib` library installed on your system doesn't seem to be packaged with OpenSSL support. I will add a check to refuse such library, but you will end up using the fallback external instead of your system library.

**Comment by svalx** [comment]
I use openSUSE, my system-installed cpp-httplib built with OpenSSL support exactly - I am maintainer, see https://build.opensuse.org/package/binary/devel:libraries:c_c++/cpp-httplib/openSUSE_Factory/i586/libcpp-httplib0_12-0.12.0-10.1.i586.rpm

**Comment by abouvier** [comment]
You should post the output of CMake when it searches for the libraries and also the full linking error.

**Comment by Tachi107** [comment]
This shouldn't be an issue in yuzu, if you've compiled cpp-httplib with OpenSSL support then the generated pkg-config (or CMake Config) file should already make OpenSSL a required (transitive) dependency. Odd that you're encountering this issue. How is OpenSUSE's cpp-httplib package built?

**Comment by svalx** [comment]
> Edit: @svalx the page you've linked requires an account to be accessed
   How is OpenSUSE's cpp-httplib package built?

Sorry, https://build.opensuse.org/package/show/devel:libraries:c_c++/cpp-httplib see cpp-httplib.spec, this is a Meson build.
$ cat /usr/lib64/pkgconfig/cpp-httplib.pc:
```
prefix=/usr
includedir=${prefix}/include
libdir=${prefix}/lib64

Name: cpp-httplib
Description: A C++ HTTP/HTTPS server and client library
URL: https://github.com/yhirose/cpp-httplib
Version: 0.12.0
Requires.private: openssl >= 1.1.1, zlib, libbrotlicommon, libbrotlidec, libbrotlienc
Libs: -L${libdir} -lcpp-httplib
Libs.private: -pthread
Cflags: -I${includedir} -DCPPHTTPLIB_OPENSSL_SUPPORT -DCPPHTTPLIB_ZLIB_SUPPORT -DCPPHTTPLIB_BROTLI_SUPPORT

```
This file buildtime generated.

**Comment by abouvier** [comment]
The problem appears to be with `cpp-jwt` instead. Can you try https://github.com/yuzu-emu/yuzu/pull/9844?

**Comment by svalx** [comment]
> The problem appears to be with `cpp-jwt` instead. Can you try #9844?

Yes, this is fix linking!

`[ 2458s] [1283/1410] : && /usr/bin/c++ -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -O3 -DNDEBUG -flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now    -fuse-ld=mold src/dedicated_room/CMakeFiles/yuzu-room.dir/yuzu_room.cpp.o -o bin/yuzu-room  src/common/libcommon.a  src/network/libnetwork.a  src/web_service/libweb_service.a  externals/mbedtls/library/libmbedtls.a  externals/mbedtls/library/libmbedcrypto.a  -lrt  src/network/libnetwork.a  src/web_service/libweb_service.a  /usr/lib64/libenet.so  src/common/libcommon.a  /usr/lib64/libboost_context.so.1.81.0  /usr/lib64/libfmt.so.9.1.0  /usr/lib64/liblz4.so  /usr/lib64/libzstd.so  externals/libdemangle.a  /usr/lib64/libcpp-httplib.so  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  externals/mbedtls/library/libmbedx509.a  externals/mbedtls/library/libmbedcrypto.a && :`

**Comment by G-Spawn** [comment]
Closing as this seems to be solved
