### ISSUE TITLE
Compilation error on Mac M1 using homebrew arm packages

### ISSUE THREAD

**Issue by HyperCed** [yuzu-emu/yuzu#9850]
### Issue

On MacOS 13.2.1 running on MacMini ARM silicon using arm64 package with homebrew.

When I do:
`cmake .. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DYUZU_USE_BUNDLED_VCPKG=OFF -DYUZU_TESTS=OFF` 
and then
`ninja`

I get:
`[672/775] Linking CXX executable bin/yuzu-room
FAILED: bin/yuzu-room 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O2 -g -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  src/dedicated_room/CMakeFiles/yuzu-room.dir/yuzu_room.cpp.o -o bin/yuzu-room  -Wl,-rpath,/opt/homebrew/lib  src/common/libcommon.a  src/network/libnetwork.a  src/web_service/libweb_service.a  externals/mbedtls/library/libmbedtls.a  externals/mbedtls/library/libmbedcrypto.a  -framework  Cocoa  src/network/libnetwork.a  src/web_service/libweb_service.a  externals/enet/libenet.a  src/common/libcommon.a  /opt/homebrew/lib/libboost_context-mt.dylib  /opt/homebrew/lib/libfmt.9.1.0.dylib  /opt/homebrew/Cellar/lz4/1.9.4/lib/liblz4.dylib  /opt/homebrew/lib/libzstd.1.5.4.dylib  externals/libdemangle.a  /opt/local/lib/libssl.dylib  /opt/local/lib/libcrypto.dylib  externals/mbedtls/library/libmbedx509.a  externals/mbedtls/library/libmbedcrypto.a && :
Undefined symbols for architecture arm64:
  "_SecCertificateGetTypeID", referenced from:
      httplib::detail::add_certs_to_x509_store(__CFArray const*, x509_store_st*) in libweb_service.a(web_backend.cpp.o)
  "_SecItemCopyMatching", referenced from:
      httplib::detail::retrieve_certs_from_keychain(std::__1::unique_ptr<__CFArray const, void (*)(void const*)>&) in libweb_service.a(web_backend.cpp.o)
  "_SecItemExport", referenced from:
      httplib::detail::add_certs_to_x509_store(__CFArray const*, x509_store_st*) in libweb_service.a(web_backend.cpp.o)
  "_SecTrustCopyAnchorCertificates", referenced from:
      httplib::detail::load_system_certs_on_apple(x509_store_st*) in libweb_service.a(web_backend.cpp.o)
  "_kSecClass", referenced from:
      httplib::detail::retrieve_certs_from_keychain(std::__1::unique_ptr<__CFArray const, void (*)(void const*)>&) in libweb_service.a(web_backend.cpp.o)
  "_kSecClassCertificate", referenced from:
      httplib::detail::retrieve_certs_from_keychain(std::__1::unique_ptr<__CFArray const, void (*)(void const*)>&) in libweb_service.a(web_backend.cpp.o)
  "_kSecMatchLimit", referenced from:
      httplib::detail::retrieve_certs_from_keychain(std::__1::unique_ptr<__CFArray const, void (*)(void const*)>&) in libweb_service.a(web_backend.cpp.o)
  "_kSecMatchLimitAll", referenced from:
      httplib::detail::retrieve_certs_from_keychain(std::__1::unique_ptr<__CFArray const, void (*)(void const*)>&) in libweb_service.a(web_backend.cpp.o)
  "_kSecReturnRef", referenced from:
      httplib::detail::retrieve_certs_from_keychain(std::__1::unique_ptr<__CFArray const, void (*)(void const*)>&) in libweb_service.a(web_backend.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[673/775] Linking CXX static library src/video_core/libvideo_core.a
ninja: build stopped: subcommand failed.`

**Comment by liamwhite** [comment]
Weird issue. Try with -DENABLE_WEB_SERVICE=OFF

**Comment by HyperCed** [comment]
Yes, it's working!
