### ISSUE TITLE
Theatrhythm Final Bar Line - Info screen broken on Vulkan

### ISSUE THREAD

**Issue by lKomus** [yuzu-emu/yuzu#9852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1348

### Description of Issue

The info screen shows garbage graphics on Vulkan. This doesn't happen on OpenGL.
![yuzu_uav3f29wLm](https://user-images.githubusercontent.com/4800879/220955686-a095855c-c654-471c-96f5-5d26fb3d0af1.jpg)

### Expected Behavior

The info screen to be displayed correctly.
![yuzu_7elguJsCLV](https://user-images.githubusercontent.com/4800879/220955710-d7c2e42a-58f7-4857-b633-926059d107fb.jpg)

### Reproduction Steps

Enable the info screen in the options menu and play any song in the game.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10815468/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7 5800X
GPU/Driver: NVIDIA Geforce 3060 Ti (528.02)
RAM: 16GB
OS: Windows 11 Pro 22H2

**Comment by lKomus** [comment]
Sure, but I think you need the DLCs for it to work.

[010081B01777C000.zip](https://github.com/yuzu-emu/yuzu/files/10910536/010081B01777C000.zip)

**Comment by vonchenplus** [comment]
EA 3441 can't reproduce the problem, 
GPU/Driver: NVIDIA Geforce 1070 Ti (528.024)
![image](https://user-images.githubusercontent.com/3349963/223729419-560d2346-e099-4177-89fe-7369f97fc803.png)

**Comment by lKomus** [comment]
It's still broken even on GPU High but some stuff gets displayed and the garbage seems to be different when I close and open the game again.

![yuzu_c8fXGfEN6i](https://user-images.githubusercontent.com/4800879/223738979-1495c199-2b31-4bf4-b516-7c671b88975b.png)
![yuzu_kCrpLKyrzO](https://user-images.githubusercontent.com/4800879/223738989-721f5543-c0a5-487c-96e4-92fd6225900f.png)

**Comment by lKomus** [comment]
Sorry for double posting but I found out that you can't reopen an issue if you're not a collaborator. Could someone reopen the issue for me please?
