### ISSUE TITLE
Theatrhythm Final Bar Line - Duo - Player 2 Inputs Not Working

### ISSUE THREAD

**Issue by Gimlao** [yuzu-emu/yuzu#9860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3414

### Description of Issue

While playing in Duo mode, player 2 inputs aren't working

Controller 2 inputs are working fine in the emulator settings, but it does nothing in game

### Expected Behavior

Player 2 should be able to play with a second controller

### Reproduction Steps

Choose a song, enable Duo mode, then player 2 will not be able to play

### Log File

https://pastebin.com/9SwumjhT

### System Configuration

CPU: AMD Ryzen 9 5900HX with Radeon Graphics
GPU/Driver: NVIDIA GeForce RTX 3060 Laptop GPU
RAM: 15.42 GiB
OS: Windows 11 Version 22H2 (Build 22621.1265)

**Comment by goldenx86** [comment]
We won't provide support on piracy.

**Comment by Gimlao** [comment]
I found a way to "fix" this, just case you want to know, since it should be interesting for you : 

If "Connect Controller" is enabled in "Emulation / Configure... / Controls / Player 2" before starting the game, it will not work.

But, if "Connect Controller" if disabled for Player 2, yuzu will popout the "Controller Applet" window when starting a song in Duo mode, then Player 2 will work in game.
