### ISSUE TITLE
Octopath Traveler 2 unplayable

### ISSUE THREAD

**Issue by M4rQu1Nh0S** [yuzu-emu/yuzu#9865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1351

### Description of Issue

The emulator closes after select the character to play.

### Expected Behavior

After choosing the character the game is supposed to keep running normally.

### Reproduction Steps

Start a new game and choose any character to start his history.

### Log File

The log is filled with the error:
```
[ 336.351111] Debug <Critical> common/host_memory.cpp:operator():450: Assertion Failed!
mprotect failed: Cannot allocate memory
[ 336.351676] Debug <Critical> common/host_memory.cpp:operator():450: Assertion Failed!
mprotect failed: Cannot allocate memory
[ 336.351709] Debug <Critical> common/host_memory.cpp:operator():450: Assertion Failed!
mprotect failed: Cannot allocate memory
[ 336.352569] Debug <Critical> common/host_memory.cpp:operator():450: Assertion Failed!
mprotect failed: Cannot allocate memory
[ 336.352964] Debug <Critical> common/host_memory.cpp:operator():450: Assertion Failed!
```

This issue happens both OpenGL and Vulkan.

### System Configuration

CPU: i7 2600
GPU/Driver: Nvidia 1050 ti / Driver 525.78.01
RAM: 16 GB
OS: Ubuntu Linux 22.10

**Comment by liamwhite** [comment]
Configuration issue; see comment here. https://github.com/yuzu-emu/yuzu/issues/7397#issuecomment-974834996
