### ISSUE TITLE
Bayonetta 2 NSP no audio Linux.

### ISSUE THREAD

**Issue by artivision** [yuzu-emu/yuzu#9866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

AUR Linux ALL versions

### Description of Issue

Regardless of the Yuzu audio choices this game refuses to give audio. Tested many different roms.

### Expected Behavior

Give audio output by default.

### Reproduction Steps

Just execute Bayonetta 2.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10832413/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5500
GPU/Driver: Mesa 22.3.6
RAM: 16GB
OS: Manjaro Linux - AUR Yuzu

**Comment by v-fox** [comment]
Tested version 1374 on openSUSE with pipewire and patch 1.1 for the game: audio works fine.
Check if yuzu is routed to the correct output for you and not auto-muted in mixer by default.

**Comment by gidoly** [comment]
appears to user setup error + we don't support piracy here
