### ISSUE TITLE
Mario Kart 8 issues with firmwares newer than 14.1.2

### ISSUE THREAD

**Issue by pr030880** [yuzu-emu/yuzu#9869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu 1351 and earlier

### Description of Issue

All firmwares above 14.1.2 don't seem to have the default Mii-characters named "Player" in different shapes and forms anymore or yuzu can't read them out of the new firmware files. Mario Kart 8 Deluxe needs them in order to work. Whether you have a old save from a previous firmware or created a new profile, doesn't matter. Mario Kart 8 Deluxe doesn't get passed the loading screen (if a old save is used) and/or is stuck at the "Select Mii" screen (when launched with a blank save).
I can re-produce this bug everytime. When I revert back to firmware 14.1.2 everything works as intended (default Mii's available - named "Player").

### Expected Behavior

Boot beyond loading screen or offer default Mii's.

### Reproduction Steps

Use firmware higher than 14.1.2 (15.x/16.x), launch game. Game is either stuck at the loading screen (with old save) or doesn't get passed the Mii selection screen (No Mii's available).

### Log File

- will provide later -

### System Configuration

CPU: i5 - 10500
GPU/Driver: Quadro T1000 8GB / latest NVidia Game Ready driver
RAM: 16GB RAM
OS: Windows 10 - 22H2

**Comment by pr030880** [comment]
I hope a applet will come soon to create Mii's, like in Ryujinx - which works very well ;-)

**Comment by Norstyrm** [comment]
Have you also remembered to dump newer prod.keys from your Switch for the firmware update?

**Comment by pr030880** [comment]
Yes, I used new "prod.keys" from the latest firmware. In other games, for example Mario Party, Metroid Dread, Mario Bros. 3D, I don't experience any problems at all.

**Comment by RinMaru** [comment]
> Yes, I used new "prod.keys" from the latest firmware. In other games, for example Mario Party, Metroid Dread, Mario Bros. 3D, I don't experience any problems at all.

someone internally has those games working after dumping their keys again.

**Comment by pr030880** [comment]
Strange. I can try it again later with FW 16.0.0 and dump my keys again. Will let you know the results...

**Comment by pr030880** [comment]
Ok, now it worked. I guess my dump was faulty. Now it works perfectly, so this thing can be closed. Thanks for the feedback ;-)

**Comment by piplup55** [comment]
as rinmaru said i was able to get this working and it still is working, remember you need the [latest](https://github.com/shchmue/Lockpick_RCM/releases/latest) lockpick rcm to generate the right keys
![image](https://user-images.githubusercontent.com/100526773/221423336-79db4787-156d-4dd0-9e68-03b4c12608f7.png)

**Comment by pr030880** [comment]
> as rinmaru said i was able to get this working and it still is working, remember you need the [latest](https://github.com/shchmue/Lockpick_RCM/releases/latest) lockpick rcm to generate the right keys
> ![image](https://user-images.githubusercontent.com/100526773/221423336-79db4787-156d-4dd0-9e68-03b4c12608f7.png)
> ![image](https://user-images.githubusercontent.com/100526773/221423563-f1ea11fb-5b4f-4a09-ae9c-9782b87c75ac.png)
> 

My mistake. Sorry for that. Now everything is working again :-)

**Comment by dan3840** [comment]
> Strange. I can try it again later with FW 16.0.0 and dump my keys again. Will let you know the results...

Could you send me the dump of your keys? I can't find titles.keys anywhere. If you can email.. danilo3840@gmail.com

**Comment by dan3840** [comment]
> 

Could you send me the dump of your keys? I can't find titles.keys anywhere. If you can email.. danilo3840@gmail.com

**Comment by dan3840** [comment]
> Strange. I can try it again later with FW 16.0.0 and dump my keys again. Will let you know the results...

Could you send me the dump of your keys? I can't find titles.keys anywhere. If you can email.. danilo3840@gmail.com
