### ISSUE TITLE
Error while loading ROM! (0007-0016)

### ISSUE THREAD

**Issue by Blackr41n** [yuzu-emu/yuzu#9880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1352

### Description of Issue

Error while loading ROM! (0007-0016)
The key area key is incorrect or the section header is invalid.

### Expected Behavior

This error wiil occoured if base game version is not v1.0
and the game will not show on folder game list.

I tested with game:
Hokko Life [010022A016250000] = Base v1.0.2
Ruined King A League of Legends Story™ [0100947013122000] = Base v1.1
Them's Fightin' Herds [01003E80178A0000] = Base v1.1.0
Youtubers Life 2 [01004DE013EDE800] = Base v1.2.0e

### Reproduction Steps

Load file or drag file into yuzu.

### Log File

[   0.083006] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.083017] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.105993] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[   0.122921] Frontend <Info> yuzu\main.cpp:GMainWindow:354: yuzu Version: yuzu 1352
[   0.122933] Frontend <Info> yuzu\main.cpp:LogRuntimes:235: MSVC Compiler: 1934 Runtime: 14.31.31103.0
[   0.122934] Frontend <Info> yuzu\main.cpp:LogRuntimes:244: Qt Compile: 5.15.2 Runtime: 5.15.2
[   0.122934] Frontend <Info> yuzu\main.cpp:GMainWindow:370: Host CPU: 12th Gen Intel(R) Core(TM) i9-12900K | AVX2 | FMA
[   0.122939] Frontend <Info> yuzu\main.cpp:GMainWindow:372: Host CPU Cores: 16
[   0.122939] Frontend <Info> yuzu\main.cpp:GMainWindow:375: Host CPU Threads: 24
[   0.123018] Frontend <Info> yuzu\main.cpp:GMainWindow:376: Host OS: Windows 10 Version 22H2 (Build 19045.2604)
[   0.123027] Frontend <Info> yuzu\main.cpp:GMainWindow:378: Host RAM: 127.75 GiB
[   0.123027] Frontend <Info> yuzu\main.cpp:GMainWindow:379: Host Swap: 19.00 GiB
[   2.838887] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.845590] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.852950] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.859817] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.865407] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.871768] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.874717] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.883921] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.887833] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.891385] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.899530] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.906815] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.911379] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.919779] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.928197] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.941389] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.945851] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.949762] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.953346] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.957621] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.964572] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.968193] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully
[   2.972324] Loader <Info> core\file_sys\patch_manager.cpp:PatchRomFS:441:     RomFS: Update (v0.0.0) applied successfully

### System Configuration

CPU: 12th Gen Intel(R) Core(TM) i9-12900K | AVX2 | FMA
GPU/Driver: RTX 3060 / Version: 517.48
RAM: 128GB DDR4
OS: Windwos 10 Pro 64bit

**Comment by german77** [comment]
Dump the latest keys from your switch

**Comment by Blackr41n** [comment]
> Dump the latest keys from your switch

I can't, i dont have moded switch.

**Comment by Eloeri** [comment]
@Blackr41n We expect all of our users to follow our rules. A hackable Nintendo Switch is necessary, we don't support piracy.
