### ISSUE TITLE
Yuzu randomly hanging and crashing in many games

### ISSUE THREAD

**Issue by VladimirVSC** [yuzu-emu/yuzu#9881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1345

### Description of Issue

Some games tested (Persona 5 Royal, TES 5 Skyrim, Diablo 3, Xenoblade Chronicles - Definitive Edition) suffer from unexpected hanging in random places, or hanging with following crashing. All games are NSP.

### Expected Behavior

Games working without hanging.

### Reproduction Steps

Just playing any game - no special circumstances seems to be required. Persona 5 Royal hangs rarely, Skyrim - very often. I don't know if it is the same reason for hanging or not.

### Log File

[yuzu_log (Skyrim).txt](https://github.com/yuzu-emu/yuzu/files/10860231/yuzu_log.Skyrim.txt)

[yuzu_log (Skyrim 2).txt](https://github.com/yuzu-emu/yuzu/files/10860237/yuzu_log.Skyrim.2.txt)

[yuzu_log (Diablo III).txt.zip](https://github.com/yuzu-emu/yuzu/files/10861099/yuzu_log.Diablo.III.txt.zip)

[yuzu_log (Persona 5 Royal crash).txt](https://github.com/yuzu-emu/yuzu/files/10919351/yuzu_log.Persona.5.Royal.crash.txt)

[yuzu_log (Persona 5 Royal crash 2).txt](https://github.com/yuzu-emu/yuzu/files/10950466/yuzu_log.Persona.5.Royal.crash.2.txt)

### System Configuration

CPU: Core-I5 4430 - 3.oo GHz
GPU/Driver: GeForce GTX 760 (2 Gb) (driver - 470.161.03)
RAM: 8 Gb
OS: Linux Mint Debian Edition 5

[System Specs (if nesessary).txt](https://github.com/yuzu-emu/yuzu/files/10860268/System.Specs.if.nesessary.txt)

**Comment by G-Spawn** [comment]
Seems basically every game you're trying is failing due to lack of network interface set? (config >> system >> network) see if setting one helps you any.

**Comment by VladimirVSC** [comment]
> Seems basically every game you're trying is failing due to lack of network interface set? (config >> system >> network) see if setting one helps you any.

Well... No use. Skyrim keeps hanging (log attached) and Diablo 3 seems to be hanging in the only location I have reached - Weeping Hollow - a couple of minutes of gameplay and it hangs entirely (even "stop emulation" can not help - only killing process with task manager works). It wasn't happening in any previous location. (save file also attached)

[yuzu_log (Skyrim with ppp0 network interface activated).txt](https://github.com/yuzu-emu/yuzu/files/10864261/yuzu_log.Skyrim.with.ppp0.network.interface.activated.txt)

[Diablo 3 Save.zip](https://github.com/yuzu-emu/yuzu/files/10864289/Diablo.3.Save.zip)

**Comment by VladimirVSC** [comment]
Persona 5 crash log was added

**Comment by gandalfthewhite19890404** [comment]
Any updates with Diablo III?
What game version was used?

**Comment by VladimirVSC** [comment]
> Any updates with Diablo III? What game version was used?

The game version is 2.7.1.76692. Just tried the latest 1375 build - nothing have changed, it still hangs in the Weeping Hollow location. I have tried to run it through quickly and when entering the Defiled Crypt, the game seased to hang again.

**Comment by gandalfthewhite19890404** [comment]
> The game version is 2.7.1.76692. Just tried the latest 1375 build - nothing have changed, it still hangs in the Weeping Hollow location. I have tried to run it through quickly and when entering the Defiled Crypt, the game seased to hang again. Let's see what happens next...

Upload save just before that, please. Or find me in Discord, i'm on yuzu DC server to, gandalfthewhite#0173, let try find a solution there

**Comment by VladimirVSC** [comment]
> > The game version is 2.7.1.76692. Just tried the latest 1375 build - nothing have changed, it still hangs in the Weeping Hollow location. I have tried to run it through quickly and when entering the Defiled Crypt, the game seased to hang again. Let's see what happens next...
> 
> Upload save just before that, please. Or find me in Discord, i'm on yuzu DC server to, gandalfthewhite#0173, let try find a solution there

Here. This save has more portals activated, then in previously uploaded save file. The Weeping Hollow entrance is right at the north end of New Tristram town (you know this, I guess). The portal to the Cemetery of the Forsaken bordering with the Weeping Hollow (just a few steps back through the cemetery gate) is activated too. The Defiled Crypt is right near the cemetery portal. I didn't try if the game hangs on the cemetery, but when entering the crypt everything works fine works fine. When travelling the Fields of Misery and its caves the game runs flawlessly too.

[Diablo 3 Save (more portals activated).zip](https://github.com/yuzu-emu/yuzu/files/11042146/Diablo.3.Save.more.portals.activated.zip)

**Comment by gandalfthewhite19890404** [comment]
latest yuzu, from official site, mainline
Diablo III 2.7.5.
Without any specific settings, I didn't set anything except gamepad.
Walked to Weeping Hollow, then to Cemetery, And entered to Defiled Crypt in upper part of cemetery, cleared whole crypt, completed challenge with bunch of skeletons, walked to crypt end and teleported by obelisk to cemetery.
My gear:
i5-10400, 32GB RAM, RTX2060 Super 8GB, Windows 10 Pro 22H2 19045.2604

![image](https://user-images.githubusercontent.com/24764335/227693012-0a9bc8e2-26a4-4b8c-8810-3b98d7ad4d57.png)
![image](https://user-images.githubusercontent.com/24764335/227693115-a541546f-212c-4c65-854d-1f29795a509e.png)

**Comment by VladimirVSC** [comment]
> latest yuzu, from official site, mainline Diablo III 2.7.5. Without any specific settings, I didn't set anything except gamepad. Walked to Weeping Hollow, then to Cemetery, And entered to Defiled Crypt in upper part of cemetery, cleared whole crypt, completed challenge with bunch of skeletons, walked to crypt end and teleported by obelisk to cemetery. My gear: i5-10400, 32GB RAM, RTX2060 Super 8GB, Windows 10 Pro 22H2 19045.2604
> 
> ![image](https://user-images.githubusercontent.com/24764335/227693012-0a9bc8e2-26a4-4b8c-8810-3b98d7ad4d57.png) ![image](https://user-images.githubusercontent.com/24764335/227693115-a541546f-212c-4c65-854d-1f29795a509e.png)

Were you trying to roam about the Weeping Hollow a bit longer? It seems to be hanging in a several minutes in my case. If the hanging doesn't occur for you, then, maybe, it is the problem with my configuration, i don't know (I have an old video driver, which cannot be updated - maybe it is a problem).

**Comment by gandalfthewhite19890404** [comment]
Mine is 516.94, pretty old.

**Comment by VladimirVSC** [comment]
Seems to be hanging in The Festering Woods too...

[Diablo 3 Festering Woods save (near the Drowned Temple portal)).zip](https://github.com/yuzu-emu/yuzu/files/11069696/Diablo.3.Festering.Woods.save.near.the.Drowned.Temple.portal.zip)

[Diablo 3 - The Festering Woods crash.zip](https://github.com/yuzu-emu/yuzu/files/11069697/Diablo.3.-.The.Festering.Woods.crash.zip)

**Comment by VladimirVSC** [comment]
> Mine is 516.94, pretty old.

So you don't have this hangings?

**Comment by gandalfthewhite19890404** [comment]
I gonna test it today - gonna play in that locations longer.

**Comment by VladimirVSC** [comment]
Fixed with graphic adapter and drivers update.
