### ISSUE TITLE
Story of Seasons A Wonderful Life Visual Glitch

### ISSUE THREAD

**Issue by dvp906** [yuzu-emu/yuzu#9883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All of the game

### Description of Issue

Visual bug with lines.

### Expected Behavior

![image](https://user-images.githubusercontent.com/126686560/222161939-4155d156-82de-4f6e-b424-9413b3d8df1d.png)

### Reproduction Steps

Seems to happen when I load new environment, Cutscene or loading new map 

### Log File

Not sure how to log

### System Configuration

CPU: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz   3.60 GHz
GPU/Driver: 1080 TI
RAM:  Corsair VENGEANCE RGB PRO 3600MHz 16GB(2 x 8GB)
OS: Windows 10 Pro

**Comment by G-Spawn** [comment]
https://github.com/yuzu-emu/yuzu/issues/9805 Closing in favour of existing issue
