### ISSUE TITLE
A Hat in Time Intro Screen Freezing

### ISSUE THREAD

**Issue by nickkeane** [yuzu-emu/yuzu#9885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3418

### Description of Issue

The game is freezing after loading on the intro screen

### Expected Behavior

The game should run past the intro screen and load into the main menu.

### Reproduction Steps

1. Start A Hat in Time
2. Wait for intro screen to freeze

### Log File

https://pastebin.com/raw/T1BFzBAv

### System Configuration

CPU: AMD Ryzen 9 5900HS
GPU/Driver: nVidia RTX 3070 Laptop
RAM: 16GB
OS: Windows 10 64-bit

**Comment by benderscruffy** [comment]
@FearlessTobi 
goes ingame 
can be closed

**Comment by RinMaru** [comment]
> @FearlessTobi 
> goes ingame 
> can be closed

Just because it works for you doesn't mean anything. Let the moderators handle it.

**Comment by benderscruffy** [comment]
> > @FearlessTobi
> > goes ingame
> > can be closed
> 
> Just because it works for you doesn't mean anything. Let the moderators handle it.

if you had of looked at his GPU it is the same as mine Nvidia

**Comment by RinMaru** [comment]
> > > @FearlessTobi
> > > goes ingame
> > > can be closed
> > 
> > Just because it works for you doesn't mean anything. Let the moderators handle it.
> 
> if you had of looked at his GPU it is the same as mine Nvidia

Brand doesn't matter it can be a diff architecture. He can have a completely different assortment of hardware.

**Comment by nickkeane** [comment]
It works on my new Laptop. I needed to update to version 1.0.4 for it to work there.

Unfortunately, I can't test if the issue occurs or not on varied configurations. I don't have my old computer anymore that it wasn't working on to verify the fix. I'd appreciate someone testing this game on diff hardware (AMD, Intel, nVidia, etc.) to make sure this issue doesn't occur on other platforms.
