### ISSUE TITLE
yuzu closes automatically when I run The Legend of Zelda: Breath of the Wild

### ISSUE THREAD

**Issue by HiL1981** [yuzu-emu/yuzu#9891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3411

### Description of Issue

yuzu closes automatically when I play The Legend of Zelda: Breath of the Wild.I am using an intel arc A380 graphics card, and the driver version is 31.0.101.4146.

https://user-images.githubusercontent.com/107376205/222432503-9cb4b9c4-8acb-4c6a-9b3f-220978d3ac8b.mp4

### Expected Behavior

null

### Reproduction Steps

null

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10871346/yuzu_log.txt)

### System Configuration

CPU:AMD Ryzen 5 5600X
GPU/Driver:Intel ARC A380/31.0.101.4146
RAM:16GB
OS:Windows 11 22H2 22621.1265

**Comment by goldenx86** [comment]
ARC and Xe graphics Windows drivers have a broken SPIR-V compiler, causing these crashes. We have tickets open on Intel's channels and we're trying to draw more attention to it.
There's no user side fix for now, Intel needs to fix it on their drivers.
You can try using Linux meanwhile.

**Comment by liamwhite** [comment]
See also https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/159

**Comment by devlich** [comment]
I have the exact same issue on Pop!_OS. Everything was working well before the last Pop!_OS update.

**Comment by devlich** [comment]
When I run Yuzu from the cli I can see those errors
```Bash
libpng warning: iCCP: known incorrect sRGB profile
Unhandled SIGSEGV at rip 0x00007f01152adc85
Erreur de segmentation (core dumped)
```

**Comment by gitwiq** [comment]
I have the exact same behavior on pop_os. I think this problem started happening after a system update. The game runs on the latest Ubuntu LTS live USB without any issues.
During the crash I have these errors in the terminal :
libpng warning: iCCP: known incorrect sRGB profile
Unhandled SIGSEGV at rip 0x00007f01152adc85
Erreur de segmentation (core dumped)

**Comment by gitwiq** [comment]
> ARC and Xe graphics Windows drivers have a broken SPIR-V compiler, causing these crashes. We have tickets open on Intel's channels and we're trying to draw more attention to it. There's no user side fix for now, Intel needs to fix it on their drivers. You can try using Linux meanwhile.

It was a dumb issue. Something silently went wrong during a system update, I've just reinstall graphics drivers and everything works well now.

**Comment by gitwiq** [comment]
> I have the exact same behavior on pop_os. I think this problem started happening after a system update. The game runs on the latest Ubuntu LTS live USB without any issues. During the crash I have these errors in the terminal : libpng warning: iCCP: known incorrect sRGB profile Unhandled SIGSEGV at rip 0x00007f01152adc85 Erreur de segmentation (core dumped)

It was a dumb issue. Something silently went wrong during a system update, I've just reinstall graphics drivers and everything works well now.
