### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by donnieall** [yuzu-emu/yuzu#9894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

later

### Description of Issue

So I have dozens of hours logged on Yuzu and it always worked fine, until one day recently I went to open it (or games) and nothing was working. For context I play on a steam deck, and Yuzu was originally installed through emudeck though I have manually tried to change appimage files for it over time to update.

Nowadays, when I open Yuzu it is completely unresponsive and there is nothing I can do within it, and after showing a white screen it closes about 5 seconds later.

If I try to open a game from game mode on the deck, or if I go on desktop mode to open a game yuzu doesnt open at all or respond even to show the white screen. Game mode just shoots me back to the main screen and desktop mode does nothing.

I feel like (obviously) this is more of something going on with the app, as opposed to my steam deck. and I cant really update it through itself as its unresponsive and i have gone to the pineapple site to try other versions to no avail.

Is this a common thing? I couldn't find anything on it on the internet so sorry if it is. Is there some specific linux way to uninstall and reinstall yuzu that I should be doing?

Any help is appreciated!
![ZwLkBRsl](https://user-images.githubusercontent.com/126923596/222854193-1f6cc0ce-583d-4240-b9d8-4b91d2270628.jpg)
![ZwLkBRsl](https://user-images.githubusercontent.com/126923596/222854203-49130cb8-0a85-49a0-a556-42531daa2a67.jpg)

### Expected Behavior

not to crash

### Reproduction Steps

It has something to do with my emudeck switch folder probably, Maybe even my newest added game?

### Log Filefile:///home/deck/.var/app/org.yuzu_emu.yuzu/data/yuzu/log/yuzu_log.txt

I dont have this but i will edit and add it when i do

### System Configuration

CPU: Steam deck 2023 Q1
GPU/Driver:
RAM:
OS:

**Comment by donnieall** [comment]
edit, i isolated this issue to an issue with an XCI game i had, weird that it caused the entire emulator to lock up but removing that game allowed everything to work as usual.

**Comment by donnieall** [comment]
any thoughts on that?

**Comment by liamwhite** [comment]
It is difficult to diagnose the issue without a log file.

**Comment by donnieall** [comment]
Yes I was not able to upload it unfortunately but I got the issue resolved by removing a game from the folder.   
  

  

  

  
  
  
  
  
>

**Comment by liamwhite** [comment]
Closing the issue then
