### ISSUE TITLE
epilepsy warning?

### ISSUE THREAD

**Issue by xt234** [yuzu-emu/yuzu#9895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

epilepsy warning for games that have problems with vulkan or shader issues.

### Why would this feature be useful?

So a lotta games have bad graphical almost blinding defects if you dont know how to configure them. An epilepsy warning would be really nice to have for those that are sensitive to that.

**Comment by goldenx86** [comment]
There is no realistic way to guess when this will happen. Especially on a constantly changing codebase.
Emulators will always run the risk of having incorrect rendering, it's a given that epilepsy sensitive people should take proper measures when using them.
For a risk-free environment, stick to the console.
