### ISSUE TITLE
Virtua Racing graphics corruption

### ISSUE THREAD

**Issue by Tasosgemah** [yuzu-emu/yuzu#9898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1352 / EA 3436

### Description of Issue

The graphics are corrupted like so:

![Untitled](https://user-images.githubusercontent.com/12124465/222916549-baa79f0d-fba2-4bc6-9243-3a0b9e3695c1.png)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10889101/yuzu_log.txt)

### System Configuration

CPU: i5 4670
GPU/Driver: GTX 1060 / 516.94
RAM: 16GB
OS: Windows 10

**Comment by gidoly** [comment]
fixed on lastest mainline closing
