### ISSUE TITLE
Vulkan device not detected

### ISSUE THREAD

**Issue by placeboyue** [yuzu-emu/yuzu#9903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1361

### Description of Issue

As people stated before and plenty of youtube videos try to fix, my 3060 is not showing up under vulkan devices despite reinstalling the drivers and restarting my PC.
I don't know what else i might need to do besides reinstalling the latest drivers

### Expected Behavior

RTX 3060 showing up under vulkan devices

### Reproduction Steps

open yuzu, select vulkan under graphics settings. Nothing else

### Log File

[  28.870874] Input <Info> input_common\drivers\udp_client.cpp:UDPClient:139: Udp Initialization started
[  28.870934] Input <Info> input_common\drivers\udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[  30.044729] Input <Info> input_common\drivers\joycon.cpp:Joycons:22: Joycon driver Initialization started
[  30.782445] Frontend <Info> yuzu\main.cpp:GMainWindow:354: yuzu Version: yuzu 1361
[  30.782550] Frontend <Info> yuzu\main.cpp:LogRuntimes:235: MSVC Compiler: 1934 Runtime: 14.31.31103.0
[  30.782557] Frontend <Info> yuzu\main.cpp:LogRuntimes:244: Qt Compile: 5.15.2 Runtime: 5.15.2
[  30.782562] Frontend <Info> yuzu\main.cpp:GMainWindow:370: Host CPU: Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz | AVX2 | FMA
[  30.782602] Frontend <Info> yuzu\main.cpp:GMainWindow:372: Host CPU Cores: 4
[  30.782605] Frontend <Info> yuzu\main.cpp:GMainWindow:375: Host CPU Threads: 4
[  30.784075] Frontend <Info> yuzu\main.cpp:GMainWindow:376: Host OS: Windows 10 Version 21H2 (Build 19044.2604)
[  30.784195] Frontend <Info> yuzu\main.cpp:GMainWindow:378: Host RAM: 15.91 GiB
[  30.784201] Frontend <Info> yuzu\main.cpp:GMainWindow:379: Host Swap: 16.00 GiB
[ 102.367783] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[ 103.265758] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[ 103.815677] Render.Vulkan <Error> video_core\vulkan_common\vulkan_instance.cpp:CreateInstance:130: Vulkan library not available
[ 103.815764] Frontend <Error> yuzu\configuration\configure_graphics.cpp:RetrieveVulkanDevices:378: Failed to enumerate devices with error: VK_ERROR_INITIALIZATION_FAILED
[ 440.678827] Frontend <Info> yuzu\main.cpp:BootGame:1685: yuzu starting...
[ 440.813549] Config <Info> common\settings.cpp:LogSettings:40: yuzu Configuration:
[ 440.813556] Config <Info> common\settings.cpp:operator ():33: Controls_UseDockedMode: false
[ 440.813557] Config <Info> common\settings.cpp:operator ():33: System_RngSeed: 0
[ 440.813557] Config <Info> common\settings.cpp:operator ():33: System_DeviceName: Yuzu
[ 440.813558] Config <Info> common\settings.cpp:operator ():33: System_CurrentUser: 0
[ 440.813559] Config <Info> common\settings.cpp:operator ():33: System_LanguageIndex: 1
[ 440.813560] Config <Info> common\settings.cpp:operator ():33: System_RegionIndex: 1
[ 440.813560] Config <Info> common\settings.cpp:operator ():33: System_TimeZoneIndex: 0
[ 440.813561] Config <Info> common\settings.cpp:operator ():33: Core_UseMultiCore: true
[ 440.813569] Config <Info> common\settings.cpp:operator ():33: CPU_Accuracy: 2
[ 440.813570] Config <Info> common\settings.cpp:operator ():33: Renderer_UseResolutionScaling: 2
[ 440.813571] Config <Info> common\settings.cpp:operator ():33: Renderer_ScalingFilter: 4
[ 440.813572] Config <Info> common\settings.cpp:operator ():33: Renderer_FSRSlider: 25
[ 440.813574] Config <Info> common\settings.cpp:operator ():33: Renderer_AntiAliasing: 1
[ 440.813577] Config <Info> common\settings.cpp:operator ():33: Renderer_UseSpeedLimit: true
[ 440.813578] Config <Info> common\settings.cpp:operator ():33: Renderer_SpeedLimit: 100
[ 440.813579] Config <Info> common\settings.cpp:operator ():33: Renderer_UseDiskShaderCache: true
[ 440.813579] Config <Info> common\settings.cpp:operator ():33: Renderer_GPUAccuracyLevel: 0
[ 440.813580] Config <Info> common\settings.cpp:operator ():33: Renderer_UseAsynchronousGpuEmulation: true
[ 440.813581] Config <Info> common\settings.cpp:operator ():33: Renderer_NvdecEmulation: 2
[ 440.813582] Config <Info> common\settings.cpp:operator ():33: Renderer_AccelerateASTC: true
[ 440.813583] Config <Info> common\settings.cpp:operator ():33: Renderer_AsyncASTC: false
[ 440.813584] Config <Info> common\settings.cpp:operator ():33: Renderer_UseVsync: true
[ 440.813584] Config <Info> common\settings.cpp:operator ():33: Renderer_ShaderBackend: 0
[ 440.813585] Config <Info> common\settings.cpp:operator ():33: Renderer_UseAsynchronousShaders: true
[ 440.813586] Config <Info> common\settings.cpp:operator ():33: Renderer_AnisotropicFilteringLevel: 0
[ 440.813587] Config <Info> common\settings.cpp:operator ():33: Audio_OutputEngine: auto
[ 440.813587] Config <Info> common\settings.cpp:operator ():33: Audio_OutputDevice: auto
[ 440.813588] Config <Info> common\settings.cpp:operator ():33: Audio_InputDevice: auto
[ 440.813589] Config <Info> common\settings.cpp:operator ():33: DataStorage_UseVirtualSd: true
[ 440.813592] Config <Info> common\settings.cpp:operator ():37: DataStorage_CacheDir: C:\Users\w\AppData\Roaming\yuzu\cache
[ 440.813593] Config <Info> common\settings.cpp:operator ():37: DataStorage_ConfigDir: C:\Users\w\AppData\Roaming\yuzu\config
[ 440.813594] Config <Info> common\settings.cpp:operator ():37: DataStorage_LoadDir: C:\Users\w\AppData\Roaming/yuzu/load/
[ 440.813596] Config <Info> common\settings.cpp:operator ():37: DataStorage_NANDDir: C:\Users\w\AppData\Roaming/yuzu/nand/
[ 440.813597] Config <Info> common\settings.cpp:operator ():37: DataStorage_SDMCDir: C:\Users\w\AppData\Roaming/yuzu/sdmc/
[ 440.813597] Config <Info> common\settings.cpp:operator ():33: Debugging_ProgramArgs: 
[ 440.813598] Config <Info> common\settings.cpp:operator ():33: Debugging_GDBStub: false
[ 440.813599] Config <Info> common\settings.cpp:operator ():33: Input_EnableMotion: true
[ 440.813600] Config <Info> common\settings.cpp:operator ():33: Input_EnableVibration: true
[ 440.813600] Config <Info> common\settings.cpp:operator ():33: Input_EnableTouch: true
[ 440.813601] Config <Info> common\settings.cpp:operator ():33: Input_EnableMouse: false
[ 440.813602] Config <Info> common\settings.cpp:operator ():33: Input_EnableKeyboard: false
[ 440.813602] Config <Info> common\settings.cpp:operator ():33: Input_EnableRingController: true
[ 440.813603] Config <Info> common\settings.cpp:operator ():33: Input_EnableIrSensor: false
[ 440.813604] Config <Info> common\settings.cpp:operator ():33: Input_EnableCustomJoycon: true
[ 440.813605] Config <Info> common\settings.cpp:operator ():33: Input_EnableCustomProController: false
[ 440.813605] Config <Info> common\settings.cpp:operator ():33: Input_EnableRawInput: false
[ 440.964073] Render.Vulkan <Error> video_core\vulkan_common\vulkan_instance.cpp:CreateInstance:130: Vulkan library not available
[ 440.964180] Render.Vulkan <Error> video_core\renderer_vulkan\renderer_vulkan.cpp:RendererVulkan:106: Vulkan initialization failed with error: VK_ERROR_INITIALIZATION_FAILED
[ 440.964304] HW.GPU <Error> video_core\video_core.cpp:CreateGPU:57: Failed to initialize GPU: Vulkan initialization error VK_ERROR_INITIALIZATION_FAILED
[ 440.964349] Core <Critical> core\core.cpp:Load:279: Failed to initialize system (Error 5)!
[ 455.047932] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[ 455.862338] Service.Audio <Info> audio_core\sink\sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[ 456.344743] Render.Vulkan <Error> video_core\vulkan_common\vulkan_instance.cpp:CreateInstance:130: Vulkan library not available
[ 456.344769] Frontend <Error> yuzu\configuration\configure_graphics.cpp:RetrieveVulkanDevices:378: Failed to enumerate devices with error: VK_ERROR_INITIALIZATION_FAILED

### System Configuration

CPU: I5 4000something
GPU/Driver: Nvidia RTX 3060 with driver  528.49
RAM: 16gb
OS: w10

**Comment by liamwhite** [comment]
Does https://vulkan.gpuinfo.org/downloads/vulkancapsviewer_3.28_win64.zip report any vulkan devices?

**Comment by goldenx86** [comment]
Check if you have overlays, video recorders, or mod managers installed (stuff like OBS, Action, Bandicam, ReShade, Overworlf), and update them to their latest version.

**Comment by placeboyue** [comment]
> Does https://vulkan.gpuinfo.org/downloads/vulkancapsviewer_3.28_win64.zip report any vulkan devices?

i get a "cant find vulkan-1.dll" error. Odd, i assume those come with the Nvidia drivers. I checked and i do have a vulkan-1-999-something.dll on my sysWOW and system32 folders.

**Comment by placeboyue** [comment]
> Check if you have overlays, video recorders, or mod managers installed (stuff like OBS, Action, Bandicam, ReShade, Overworlf), and update them to their latest version.

i might have OBS installed, i'll simply remove it then, as i never use it. ReShade i think i have it on some PS1/PS2 emulator, i see there's a very recent update so i'll update, just in case

**Comment by placeboyue** [comment]
Installing vulkan runtime from the official website fixed the issue. I didn't do anything else i mentioned before, this alone fixed the issue.
