### ISSUE TITLE
Please Support **Portable Mode** on Linux

### ISSUE THREAD

**Issue by catscarlet** [yuzu-emu/yuzu#9911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

**Portable Mode** on Linux
or
**yuzu Folder** can be set in cmd

### Why would this feature be useful?

I knew on Windows you can just setup a 'user' folder to make yuzu portable.

The Linux now is AppImage.

I wish there will also the **bin** version. The tar.xz not in Release is just a AppImage in tar.xz.

Also I checked the AppImage mountpoint. It's not that simple as the Windows one.

**yuzu Folder** would be very large during using so /home may not be enough.

**Comment by piplup55** [comment]
you can make a portable home which is kinda the same thing `yuzu.AppImage --appimage-portable-home`, you can also use symlinks

**Comment by michaelvrobles** [comment]
Am I correct in that this was closed but not actually implemented?
