### ISSUE TITLE
60FPS Mod for Octopath Traveller 2

### ISSUE THREAD

**Issue by Alllusive** [yuzu-emu/yuzu#9914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A modification for Octopath Traveller 2 that allows the game to run at 60fps instead of the native 30fps.

### Why would this feature be useful?

Much better viewing experience. Smoother.

**Comment by goldenx86** [comment]
We don't produce mods.
Ask the modding community instead.

**Comment by Alllusive** [comment]
> We don't produce mods. Ask the modding community instead.

Ok thanks. Where can I find the modding community?
