### ISSUE TITLE
Zero Tsukihami no Kamen (Fatal Frame Mask of the Lunar Eclipse) cannot run

### ISSUE THREAD

**Issue by holmes5800** [yuzu-emu/yuzu#9927]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

EA 3443

### Description of Issue

This game cannot run
Only a launching screen

### Expected Behavior

Run normally

### Reproduction Steps

just run it

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10927369/yuzu_log.txt)

### System Configuration

CPU: i5-12400F
GPU/Driver: NV 2070S
RAM: 16GB
OS: win10 21H2

**Comment by G-Spawn** [comment]
We don't support piracy here
