### ISSUE TITLE
Tagged PR 9889 from mainline-0-1362 breaks yuzu-cmd

### ISSUE THREAD

**Issue by pullblox39** [yuzu-emu/yuzu#9952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1362 and mainlines past 1362

### Description of Issue

When launched, yuzu-cmd throws an error and refuses to open.

The error title is "yuzu-cmd.exe - Entry Point Not Found."

The error description is "The procedure entry point SetProcessInformation could not be located in the dynamic link library KERNEL32.dll."

This issue does NOT occur on mainline 1361, nor on prior mainlines. It was introduced in mainline 1362, likely as a regression caused by tagged PR 9889:

https://github.com/yuzu-emu/yuzu-mainline/commit/88d5380f4e7be5c74e6b36b7b88a07137a0893ec

Reverting this commit and any changes built upon it should fix the issue.

### Expected Behavior

yuzu-cmd should launch without throwing an error and without refusing to open.

### Reproduction Steps

Run yuzu-cmd.

### Log File

[no_log.txt](https://github.com/yuzu-emu/yuzu/files/10962439/no_log.txt)

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by goldenx86** [comment]
Windows 8.1 and older support ended last month.
