### ISSUE TITLE
SSBU [Steam Deck]: White screen in matches with flickers to gameplay

### ISSUE THREAD

**Issue by Laserath** [yuzu-emu/yuzu#9954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1371

### Description of Issue

After updating to Steam OS 3.4.6, Super Smash Brothers Ultimate now displays a white screen in place of the actual game rendering with UI elements drawn on top. 

It also has blank white on the "World of Light" map in place of the terrain.

https://www.youtube.com/watch?v=HeH43imtFdg

### Expected Behavior

Rendered content should be displayed instead of a white screen.

### Reproduction Steps

Update Steam Deck to Steam OS 3.4.6. Launch SSBU and start a match.

Troubleshooting Performed:
- Restart Device
- Reinstall / Update yuzu (EmuDeck)
- Delete Shader Cache
- Remove all Game Updates / DLC
- Update from firmware 14.x.x to 16.0.0 (including keys)

### Log File

log is too long to include in the issue itself:
https://pastebin.com/XaV49s5T

### System Configuration

Steam Deck 512GB / Steam OS 3.4.6

**Comment by piplup55** [comment]
this is caused by the update to mesa, please try flatpak or downgrading mesa a [guide](https://github.com/piplup55/misc/blob/yuzu-mesa-22/README.md) (if needed) for the time being while the devs look into this

**Comment by doomsdalicious** [comment]
Same exact issue.

**Comment by InfidelKilla** [comment]
Can confirm that this has also happened to me. I don't know about other games but it appears to have affected vulkan shaders. This happened to me after updating my deck as well.

**Comment by Laserath** [comment]
I just updated through EmuDeck and it looks like this is fixed with yuzu mainline 1373. Super quick fix by the yuzu team. Big Props!

**Comment by ArtSakalam** [comment]
@Laserath  how did you update your EmuDeck? Is it via the EmuDeck launcher and click Update? I tried doing it by it didn't help.

**Comment by Laserath** [comment]
EmuDeck > Tools & Stuff > Update Emulators & Tools > Update AppImages and Binaries > select Yuzu and click ok

**Comment by doomsdalicious** [comment]
Fixed for me as well! I also updated the emulators via EmuDeck. I just did
a quick update from the front page though. Overkill but it worked as well.

**Comment by bradleyandrew** [comment]
This issue seems to be happening for me when running Crisis Core: FFVII Reunion. 

Steam Deck | Steam OS 3.4.6
Yuzu | Mainline 1403 via EmuDeck

![image](https://user-images.githubusercontent.com/66546729/232445019-932418c9-639b-4b14-8abe-d9f16af08ed5.jpeg)

**Comment by maximoab** [comment]
> This issue seems to be happening for me when running Crisis Core: FFVII Reunion.
> 
> Steam Deck | Steam OS 3.4.6 Yuzu | Mainline 1404 via EmuDeck
> 
> ![image](https://user-images.githubusercontent.com/66546729/232445019-932418c9-639b-4b14-8abe-d9f16af08ed5.jpeg)

Me too but im play in my pc using linux and yuzu. same problem same game. Vulkan and OpenGl give me same problem.

**Comment by MarcoMcFlyBR** [comment]
> > This issue seems to be happening for me when running Crisis Core: FFVII Reunion.
> > Steam Deck | Steam OS 3.4.6 Yuzu | Mainline 1404 via EmuDeck
> > ![image](https://user-images.githubusercontent.com/66546729/232445019-932418c9-639b-4b14-8abe-d9f16af08ed5.jpeg)
> 
> Me too but im play in my pc using linux and yuzu. same problem same game. Vulkan and OpenGl give me same problem.

Also facing the same issue (Yuzu/Linux). Updated Yuzu, and even the EA happens the same problem.
