### ISSUE TITLE
The Legend of Zelda Breath of the Wild AMD graphics card shadow BUG

### ISSUE THREAD

**Issue by yemaowuxin** [yuzu-emu/yuzu#9957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu Early Access 3459

### Description of Issue

![yuzu_0aWJPPIEOS](https://user-images.githubusercontent.com/48284264/225519115-fc2d2c51-e6c7-4a7e-abf7-1c0e727d80dc.jpg)
![yuzu_gTZdJxiH4Y](https://user-images.githubusercontent.com/48284264/225519164-87f1b4f3-1300-43c3-a73e-9e328907bb34.jpg)
![yuzu_jc0izQZGpG](https://user-images.githubusercontent.com/48284264/225519219-8a1b9094-512e-48ce-823f-cbefdf632a33.jpg)

OpenGL and Vulkan API.
If turn on anisotropic filtering, the shadow will have problems.
All AMD graphics cards have this problem.

### Expected Behavior

Hope to fix the shadow problem.

### Reproduction Steps

AMD graphics cards, turn on anisotropic filtering x16.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10986817/yuzu_log.txt)

### System Configuration

CPU: i9-10900K
GPU/Driver: AMD RX 6900xt
RAM: 32GB
OS: Windows 11 22H2 (Build 22621.1413)

**Comment by goldenx86** [comment]
Yep it's easy to confirm.
Sadly this is the reason we keep anisotropic in the advanced tab, not all games behave correctly with it, especially if there are driver/hardware differences.
Keep in mind all Switch games expect an NVIDIA behaviour, AMD seems to be doing something different here.

**Comment by yemaowuxin** [comment]
> Yep it's easy to confirm. Sadly this is the reason we keep anisotropic in the advanced tab, not all games behave correctly with it, especially if there are driver/hardware differences. Keep in mind all Switch games expect an NVIDIA behaviour, AMD seems to be doing something different here.

Thank you very much for your answer.

**Comment by yemaowuxin** [comment]
> Yep it's easy to confirm. Sadly this is the reason we keep anisotropic in the advanced tab, not all games behave correctly with it, especially if there are driver/hardware differences. Keep in mind all Switch games expect an NVIDIA behaviour, AMD seems to be doing something different here.

![yuzu_EQdmnVJse9](https://user-images.githubusercontent.com/48284264/225567792-5306cc64-6158-40fa-a8fc-a5928ea8c6d0.jpg)
![yuzu_XjwupkyuJr](https://user-images.githubusercontent.com/48284264/225567823-887aed99-4e4d-4385-950c-53cf47ad70a7.jpg)

But I found that there is still a problem with shadows when anisotropic filtering is set as the system default.
Anisotropic filtering just makes shadows more obvious.

**Comment by TomLangfeldt** [comment]
Might be worth checking the uninitialised VK extensions in the logs imo. We can see https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_NV_viewport_array2.html is not available as @goldenx86 stated. I am not too familiar with vulkan nor with the emulator but my guess would be that some "render targets" simply don't exist, hence you getting missing details.

**Comment by yemaowuxin** [comment]
> Might be worth checking the uninitialised VK extensions in the logs imo. We can see https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_NV_viewport_array2.html is not available as @goldenx86 stated. I am not too familiar with vulkan nor with the emulator but my guess would be that some "render targets" simply don't exist, hence you getting missing details.

The same problem exists with OpenGL mode.

**Comment by yemaowuxin** [comment]
> There might be a solution here for fixing this capability on AMD cards -> https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/NV/SPV_NV_viewport_array2.asciidoc
> 
> "The new ShaderViewportIndexLayerNV capability allows the Layer and ViewportIndex builtin variables to be exported from Vertex or Tessellation shaders, in addition to Geometry shaders. This is functionality added by both GL_ARB_shader_viewport_layer_array and GL_NV_viewport_array2, and separately by GL_AMD_vertex_shader_layer, and GL_AMD_vertex_shader_viewport_index."

This seems to be the problem. Thank you very much.
@goldenx86 Please see if this helps solve the problem.

**Comment by yemaowuxin** [comment]
@Wollnashorn Thanks you fix ImageGather rounding on AMD/Intel.
Now the shodows is normal when anisotropic filtering is set as the system default.
When the anisotropic filtering is set to X16 or lower, there are still black lines.
But if set the anisotropic filtering is set  system default at yuzu, and open amd software:Adrenalin edition add yuzu.exe to Gaming, and set the anisotropic filtering is set to X16 at amd software, everything is normal.
It seems that there is a problem with Yuzu's anisotropic filtering.
![RadeonSoftware_8drHGXKNff](https://user-images.githubusercontent.com/48284264/231369748-1f307f63-e695-40ff-b0b9-e93a89220557.png)

**Comment by gidoly** [comment]
it is fixed on last mainline with set anistrophic filter to default
