### ISSUE TITLE
Xenoblade Chronicles 2 Rainbow Graphics Artifact Happening Reliably when loading from Ch8. Cutscene into Morytha

### ISSUE THREAD

**Issue by crspearss** [yuzu-emu/yuzu#9959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1373

### Description of Issue

When loading into the game from the attached save, the rainbow glitch can be reliably observed on Yuzu. Previous instances of this glitch in this game as well as Xenoblade DE, would happen sporadically and could be fixed by restarting the application or loading into a different scene. I thought it was the case with this one, so mid cutscene I alt-f4'd and restarted it. The glitching kept happening and was the first time I had ever seen it consistently. I thought the artifact was permanent and starting troubleshooting for a solution.  I tried adjusting CPU/GPU accuracy settings with both OpenGL and Vulkan. Different settings didn't have any effect.

I was able to fix the rainbow artifacts after viewing the cutscene, and then fast travelling to a different zone. When fast travelling back to the lands of mythra, the zone appears correctly 

To see if this fix was also replicable, I closed the game and deleted my Shader Cache. I then launched the game and the rainbows reappeared and then were fixed once I loaded to a new zone, and then back. After deleting my shader cache, and viewing Land of Mythra correctly, I was unable to get a the attached cutscene to play without glitching like it did so once previously. 

System:
RX 6900XT
Ryzen 5600x

### Expected Behavior

When loading from attached save files, the cutscenes display these visual errors.

![morythacutscene](https://user-images.githubusercontent.com/128086011/225733966-a7b02848-8c34-4a84-bfc0-662de5f44051.png)

![ch8cutscene](https://user-images.githubusercontent.com/128086011/225734065-65270819-986b-4549-81cf-9b50df2e970c.png)

![morythagameplay](https://user-images.githubusercontent.com/128086011/225734101-7381c01c-0566-4f01-b5fc-8944e1ea224d.png)

### Reproduction Steps

Loading the game from Ch8 cutscene savepoint. Travel to a different location to then fix the corruptions in gameplay. The only thing I was unable to replicate was getting the cutscene to play without artifacts like it did once. Getting the zone to load normal by fast traveling away and then back works every time.
![morythagameplaynormal](https://user-images.githubusercontent.com/128086011/225735194-071d5b08-4946-411c-af05-8519490731c3.png)

### Log File

[ch8cutscenesave.zip](https://github.com/yuzu-emu/yuzu/files/10995232/ch8cutscenesave.zip)

### System Configuration

CPU: 5600x
GPU/Driver: RX 6900XT - Driver 23.3.1
RAM: 32gb
OS: win11

**Comment by Redhawk18** [comment]
I've had these issues happen on both windows 10 and linux in much older builds.

**Comment by phantasina** [comment]
same issue ，i use the latest ea build，win 10 3060ti

**Comment by gidoly** [comment]
should fixed on last ea mainline feel free to reopen if still happens
