### ISSUE TITLE
Story of season a wonderful life - Screen froze entering the 2nd year

### ISSUE THREAD

**Issue by Mrifai11** [yuzu-emu/yuzu#9967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1373

### Description of Issue

Screen froze after the last cutscene of 1st year.
![SOS AWL 1](https://user-images.githubusercontent.com/114404245/226090839-59004e00-e2c2-46fe-bfd5-5b6da051cde1.PNG)
![SOS AWL 2](https://user-images.githubusercontent.com/114404245/226090840-1930a198-79f8-42a1-af83-4858afcdd42f.PNG)

### Expected Behavior

The game should entered the 2nd year with the next cutscene
![SOS AWL 3](https://user-images.githubusercontent.com/114404245/226090905-349d69cc-aba5-4d88-ae03-92d71aaf38a7.PNG)

### Reproduction Steps

[0100936018EB4000.zip](https://github.com/yuzu-emu/yuzu/files/11007747/0100936018EB4000.zip)

The game froze after the last cutscene of 1st year
- Open the game with the attached save file
- Go to diary, select the first choice

** log redacted by moderator due to pirated content**

### System Configuration

CPU: Ryzen 5 3600
GPU/Driver: Nvidia GTX 1660 Super
RAM: 16GB
OS: Windows 10
Have tried both OPENGL and Vulkan, same issues, native resolution.

**Comment by G-Spawn** [comment]
We will not help pirates here.
