### ISSUE TITLE
Vibration not functioning on DualSense

### ISSUE THREAD

**Issue by FullOvellas** [yuzu-emu/yuzu#9968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

yuzu 1374 (2023-03-18)

### Description of Issue

I have been running Yuzu on Windows 10 using a DualSense controller. Vibration worked as intended until recently. Two things have changed (that I'm aware of):

- **Yuzu version**
- **DualSense firmware**. My DualSense controller is currently running **firmware 0356**, the most recent version to this date.

Right now, there is no vibration at all when using the controller be it wirelessly or connected via USB.

### Expected Behavior

Vibration functionality working as intended.

### Reproduction Steps

Update Yuzu and DualSense firmware to the latest version and run a game.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11009582/yuzu_log.txt.old.txt)

### System Configuration

CPU: Intel Core i7-9750H
GPU/Driver: NVIDIA GeForce RTX 2070 (1F10) / 528.02
RAM: 32GB
OS: Windows 10

**Comment by german77** [comment]
Can you test on the vibration tester? Click on configure on the vibration box then press any controller button to make it vibrate.

**Comment by FullOvellas** [comment]
I hadn't tried the vibration test. I did that just now and vibration worked. I then launched a game to see if the issue was only present while running a game. Strangely enough, the issue seems to have been resolved by just doing that even when vibration was consistently not working for the entire day. So thanks, I guess!
