### ISSUE TITLE
Mario Kart 8 Deluxe Stuck at Mii Select Screen with 16.0.0

### ISSUE THREAD

**Issue by tduffy83** [yuzu-emu/yuzu#9976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3464

### Description of Issue

Per title.  Using earlier keys/firmware works.

### Expected Behavior

Get past mii select screen.

### Reproduction Steps

Install 16.0.0 keys and firmware, run mario kart 8 deluxe.

### Log File

N/A

### System Configuration

CPU: 5950x
GPU/Driver: Nvidia RTX 3090
RAM: 32GB
OS: Win 11

**Comment by german77** [comment]
Your keys are invalid for the firmware. Update lockpick to latest, play mk8 a little then dump the latest keys and firmware.

**Comment by tduffy83** [comment]
> Your keys are invalid for the firmware. Update lockpick to latest, play mk8 a little then dump the latest keys and firmware.

I have updated both the firmware and keys to 16.0.0, albeit with files found on the internet.  I do not have a modified switch.

**Comment by german77** [comment]
Piracy is not allowed
