### ISSUE TITLE
Project Diva Mega Mix with mods: ec_message=too many files open

### ISSUE THREAD

**Issue by Forser03** [yuzu-emu/yuzu#9978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1374

### Description of Issue

The emulator crashes while the game is launching. A fairly large mod is installed with the game. The logs show this: ec_message=too many files open

### Expected Behavior

The game should start and the mod should work

### Reproduction Steps

Installing the mod

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11017195/yuzu_log.txt)

### System Configuration

CPU: Intel i7 11800H
GPU/Driver: RTX 3060 Mobile (Vulkan)
RAM: 16 Gb
OS: Windows 10

**Comment by Leopounet** [comment]
I have the same issue while trying to load [Second Wind](https://github.com/Nitr4m12/Second-Wind-Switch) which is a mod for BOTW. The game does start if I increase the limit of files open at once on my computer (set to 10000). But this sounds like an unreasonable number of files, therefore this could be an actual bug in the code (possibly files not getting closed properly when loading mods).

### System configuration

CPU: 12th Gen Intel(R) Core(TM) i7-12700H
GPU: GA106M [GeForce RTX 3060 Mobile / Max-Q]
RAM: 16GB
OS: Ubuntu 22.04 (Jammy)

**Comment by happyme531** [comment]
Same issue for TotK and this time my moddir have 2000+ files.  
`ulimit -n 100000` is a workaround.

**Comment by Squall-Leonhart** [comment]
resolved by #10729
