### ISSUE TITLE
Windows: Installing Multiple Updates to NAND causes emulator to crash.

### ISSUE THREAD

**Issue by Skates1616** [yuzu-emu/yuzu#9979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1375

### Description of Issue

Installed 4 updates using Install NAND option and the emulator crashed with the following Application Error message in Windows:

![explorer_Gm9TQsIZb1](https://user-images.githubusercontent.com/23196661/226427582-852bdb96-e61e-4d86-9572-c10c14997bd3.png)

### Expected Behavior

Emulator to install Updates to NAND without crashing.

### Reproduction Steps

Installed 4 small updates, without doing anything else in the emulator, using Install NAND option and the emulator crashed.

### Log File

**Log redacted due to pirated content**

### System Configuration

CPU: 12th Gen Intel(R) Core(TM) i7-12700K | AVX2 | FMA
GPU/Driver: NVIDIA GeForce RTX 3060 Ti / NVIDIA 531.29.0.0
RAM: 32 GB
OS: Windows 11 Version 22H2 (Build 22624.1465)

**Comment by G-Spawn** [comment]
We cannot assist pirates here. Please dump all your content legitimately through your console.
