### ISSUE TITLE
Support for MUSA/Moore Threads cards

### ISSUE THREAD

**Issue by Qiangong2** [yuzu-emu/yuzu#9996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I don't expect this to be implemented anytime soon, but thought it would be good to open an issue. 

Moore Threads has released a consumer graphics card called the MTT S80. It uses its own "MUSA" cores (like cuda or amd's streaming processors). It supports Vulkan and (I think) OpenGL.

Yuzu does not recognize the card at all, so I can't test out the Vulkan capabilities. I guess technically this is a bug as well.

### Why would this feature be useful?

It's another GPU option for people to look at. While it's really only feasible for users in China, it's still another GPU option that may be cheaper for someone than an Nvidia or AMD option.

**Comment by liamwhite** [comment]
Please provide a log file so that we can get more info on why the card was not recognized - we recognize GPU drivers from even very unusual vendors, but typically can't boot due to incompatibilities.

**Comment by Qiangong2** [comment]
Here's the log:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11074221/yuzu_log.txt)

**Comment by liamwhite** [comment]
> [  31.815626] Render.Vulkan <Error> video_core\vulkan_common\vulkan_instance.cpp:CreateInstance:130: Vulkan library not available

Does the hardware capability viewer https://vulkan.gpuinfo.org/download.php detect your GPU?

**Comment by Qiangong2** [comment]
It does not

**Comment by liamwhite** [comment]
I don't really see what yuzu could do here, if there is no compatible Vulkan driver installed.

**Comment by FernandoS27** [comment]
we also do not have access to those cards as they are only available within the People's Republic of China.

**Comment by Qiangong2** [comment]
That's not the case, you can purchase them from unixcloud if you're outside of China. That's how I got mine.
